### PR TITLE
[Constraint system] Eliminate some dead code in constraint optimization.

### PR DESCRIPTION
**Pull request by DougGregor**
The code is mistakenly dereferencing an "end" iterator and currently
has no effect. Remove it to make valgrind happier.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Review by xedin — APPROVED** [review]
\o/

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Pull request merged**
