### PR TITLE
Fix SILInliner to create move_value in OSSA only

### PR DESCRIPTION
**Pull request by meg-gupta**
Fixes rdar://105870551

### CODE REVIEW

**Comment by meg-gupta** [comment]
This showed up as a bug in CSE. More details here - https://github.com/apple/swift/pull/63889

**Review by nate-chandler — APPROVED** [review]
Thank you!

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by meg-gupta** [comment]
@swift-ci test and merge

**Comment by meg-gupta** [comment]
@swift-ci test and merge

**Pull request merged**
