### PR TITLE
[runtime] Directly reference objc_setHook_getImageName

### PR DESCRIPTION
**Pull request by jrose-apple**
(instead of using dlsym)

The original use went in before <objc/runtime.h> was updated, but now it should be present in all Xcode 10 SDKs.

rdar://problem/42137765

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test macOS

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test Linux

**Review by mikeash — COMMENTED** [review]
Looks good!

**Review by mikeash — APPROVED** [review]
Whoops, didn't actually approve it.

**Comment by jrose-apple** [comment]
```
11:15:53 Undefined symbols for architecture armv7s:
11:15:53   "___isOSVersionAtLeast", referenced from:
11:15:53       swift::setUpObjCRuntimeGetImageNameFromClass() in ObjCRuntimeGetImageNameFromClass.mm.o
11:15:53 ld: symbol(s) not found for architecture armv7s
```

Uh, hm. Do we need a runtime library that's not present to do this? Oh well, I'll go back to the old way and silence the warning.

**Comment by jrose-apple** [comment]
@swift-ci Please test macOS

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test Linux

**Comment by jrose-apple** [comment]
I suspect it just requires compiler-rt or something that's not being built in all configurations.

**Comment by jrose-apple** [comment]
@swift-ci Please test macOS

**Pull request merged**
