### PR TITLE
Add test for reproducible/deterministic compilation [WIP]

### PR DESCRIPTION
**Pull request by practicalswift**
# Q. What are "deterministic" or "reproducible" builds?

Reproducible builds are a set of software development practices that create a verifiable path from human readable source code to the binary code used by computers.

The idea of "deterministic" or "reproducible" builds is to empower anyone to verify that no flaws have been introduced during the build process by reproducing byte-for-byte identical binary packages from a given source.

The ability to reproducible build software is important in areas such as scientific computing, secure computing and general software robustness.

See https://reproducible-builds.org/ for details and history of the reproducible builds movement.

# Q. Why now? Is this urgent?

After the Debian "stretch" release reproducibility will most likely become part of the Debian Policy. Programs written in Swift won't be accepted into Debian based distributions (such as Debian and Ubuntu) unless the Swift compiler provides binary reproducibility.

# Q. What does this test case do?

This test case tests that two subsequent compilations of the same Swift file yield byte-for-byte identical executables. A first minimal test for reproducibility.

### CODE REVIEW

**Comment by practicalswift** [comment]
@swift-ci please test

**Comment by practicalswift** [comment]
@swift-ci please test

**Comment by gottesmm** [comment]
@practicalswift If this becomes a bigger issue with many test cases, it may make sense to have a folder especially for these reproducibility test cases. I don't think we are there yet though.

**Comment by practicalswift** [comment]
`diffoscope` analysis for the Linux build (after `strip`):

```
$ diffoscope t/executable-1 t/executable-2
--- t/executable-1
+++ t/executable-2
├── readelf --wide --notes {}
│ @@ -3,13 +3,13 @@
│    Owner                 Data size	Description
│    GNU                  0x00000010	NT_GNU_ABI_TAG (ABI version tag)
│      OS: Linux, ABI: 2.6.32
│
│  Displaying notes found at file offset 0x00000274 with length 0x00000024:
│    Owner                 Data size	Description
│    GNU                  0x00000014	NT_GNU_BUILD_ID (unique build ID bitstring)
│ -    Build ID: d2547ee782c10f1b0a5c5f8f5d837b07c6152a0f
│ +    Build ID: 5009c12045e5dca93166869e83b03b59140c7b19
│
│  Displaying notes found at file offset 0x00002150 with length 0x0000001c:
│    Owner                 Data size	Description
│    GNU                  0x00000009	NT_GNU_GOLD_VERSION (gold version)
│      Version: gold 1.11
├── readelf --wide --decompress --hex-dump=.swift_modhash {}
│ @@ -1,4 +1,4 @@
│
│  Hex dump of section '.swift_modhash':
│ -  0x00400dcc a9895069 ff96e002 0c5e4861 36265d6b ..Pi.....^Ha6&]k
│ +  0x00400dcc 3453b5cc 604bad19 f22b50e2 96f695a5 4S..`K...+P.....
│
╵
```

`diffoscope` analysis for the Linux build (before `strip`):

```
$ diffoscope t/executable-1 t/executable-2
--- t/executable-1
+++ t/executable-2
├── readelf --wide --symbols {}
│ @@ -41,15 +41,15 @@
│       6: 0000000000400bc0     0 FUNC    LOCAL  DEFAULT   13 __do_global_dtors_aux
│       7: 0000000000403060     1 OBJECT  LOCAL  DEFAULT   34 completed.7585
│       8: 0000000000402d80     0 OBJECT  LOCAL  DEFAULT   21 __do_global_dtors_aux_fini_array_entry
│       9: 0000000000400be0     0 FUNC    LOCAL  DEFAULT   13 frame_dummy
│      10: 0000000000402d88     0 OBJECT  LOCAL  DEFAULT   22 __frame_dummy_init_array_entry
│      11: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS /root/build-swift/swift/stdlib/public/runtime/ImageInspectionInit.cpp
│      12: 0000000000400c10    12 FUNC    LOCAL  DEFAULT   13 _ZL15sectionDataInitv
│ -    13: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS /tmp/test-4bee1e.o
│ +    13: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS /tmp/test-a34cb0.o
│      14: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS crtstuff.c
│      15: 0000000000400f10     0 OBJECT  LOCAL  DEFAULT   18 __FRAME_END__
│      16: 0000000000402d78     0 OBJECT  LOCAL  DEFAULT   20 __JCR_END__
│      17: 0000000000403048     0 OBJECT  LOCAL  HIDDEN    26 __dso_handle
│      18: 0000000000400dca     2 OBJECT  LOCAL  HIDDEN    15 __swift_reflection_version
│      19: 0000000000400d00    12 FUNC    LOCAL  HIDDEN    13 swift_rt_swift_release
│      20: 0000000000400cf0    12 FUNC    LOCAL  HIDDEN    13 swift_rt_swift_retain
├── readelf --wide --notes {}
│ @@ -3,13 +3,13 @@
│    Owner                 Data size	Description
│    GNU                  0x00000010	NT_GNU_ABI_TAG (ABI version tag)
│      OS: Linux, ABI: 2.6.32
│
│  Displaying notes found at file offset 0x00000274 with length 0x00000024:
│    Owner                 Data size	Description
│    GNU                  0x00000014	NT_GNU_BUILD_ID (unique build ID bitstring)
│ -    Build ID: d2547ee782c10f1b0a5c5f8f5d837b07c6152a0f
│ +    Build ID: 5009c12045e5dca93166869e83b03b59140c7b19
│
│  Displaying notes found at file offset 0x00002150 with length 0x0000001c:
│    Owner                 Data size	Description
│    GNU                  0x00000009	NT_GNU_GOLD_VERSION (gold version)
│      Version: gold 1.11
├── readelf --wide --decompress --hex-dump=.swift_modhash {}
│ @@ -1,4 +1,4 @@
│
│  Hex dump of section '.swift_modhash':
│ -  0x00400dcc a9895069 ff96e002 0c5e4861 36265d6b ..Pi.....^Ha6&]k
│ +  0x00400dcc 3453b5cc 604bad19 f22b50e2 96f695a5 4S..`K...+P.....
│
├── readelf --wide --decompress --hex-dump=.strtab {}
│ @@ -14,16 +14,16 @@
│    0x000000b0 6d6d795f 696e6974 5f617272 61795f65 mmy_init_array_e
│    0x000000c0 6e747279 002f726f 6f742f62 75696c64 ntry./root/build
│    0x000000d0 2d737769 66742f73 77696674 2f737464 -swift/swift/std
│    0x000000e0 6c69622f 7075626c 69632f72 756e7469 lib/public/runti
│    0x000000f0 6d652f49 6d616765 496e7370 65637469 me/ImageInspecti
│    0x00000100 6f6e496e 69742e63 7070005f 5a4c3135 onInit.cpp._ZL15
│    0x00000110 73656374 696f6e44 61746149 6e697476 sectionDataInitv
│ -  0x00000120 002f746d 702f7465 73742d34 62656531 ./tmp/test-4bee1
│ -  0x00000130 652e6f00 5f5f4652 414d455f 454e445f e.o.__FRAME_END_
│ +  0x00000120 002f746d 702f7465 73742d61 33346362 ./tmp/test-a34cb
│ +  0x00000130 302e6f00 5f5f4652 414d455f 454e445f 0.o.__FRAME_END_
│    0x00000140 5f005f5f 4a43525f 454e445f 5f005f5f _.__JCR_END__.__
│    0x00000150 64736f5f 68616e64 6c65005f 5f737769 dso_handle.__swi
│    0x00000160 66745f72 65666c65 6374696f 6e5f7665 ft_reflection_ve
│    0x00000170 7273696f 6e007377 6966745f 72745f73 rsion.swift_rt_s
│    0x00000180 77696674 5f72656c 65617365 00737769 wift_release.swi
│    0x00000190 66745f72 745f7377 6966745f 72657461 ft_rt_swift_reta
│    0x000001a0 696e005f 5f544d43 5f454e44 5f5f005f in.__TMC_END__._
╵
```

**Comment by practicalswift** [comment]
`diffoscope` analysis for the Mac build (same result before and after `strip`):

```
$ diffoscope executable-1 executable-2
--- executable-1
+++ executable-2
│┄ 'lipo' not available in path. Falling back to binary comparison.
│ @@ -131,15 +131,15 @@
│  00000820: 0000 0000 7701 0000 7701 0000 0200 0000  ....w...w.......
│  00000830: 7901 0000 4400 0000 0000 0000 0000 0000  y...D...........
│  00000840: 0000 0000 0000 0000 0000 0000 0000 0000  ................
│  00000850: 5074 0000 7c00 0000 0000 0000 0000 0000  Pt..|...........
│  00000860: 0000 0000 0000 0000 0e00 0000 2000 0000  ............ ...
│  00000870: 0c00 0000 2f75 7372 2f6c 6962 2f64 796c  ..../usr/lib/dyl
│  00000880: 6400 0000 0000 0000 1b00 0000 1800 0000  d...............
│ -00000890: df61 e75d 00f9 32a5 932f 50c5 b368 455d  .a.]..2../P..hE]
│ +00000890: 3376 08e9 f272 3c89 9dc8 74ae d65f bb6e  3v...r<...t.._.n
│  000008a0: 2400 0000 1000 0000 0009 0a00 000c 0a00  $...............
│  000008b0: 2a00 0000 1000 0000 0000 0000 0000 0000  *...............
│  000008c0: 2800 0080 1800 0000 8014 0000 0000 0000  (...............
│  000008d0: 0000 0000 0000 0000 0c00 0000 6800 0000  ............h...
│  000008e0: 1800 0000 0200 0000 0040 4505 0000 9600  .........@E.....
│  000008f0: 2f53 7973 7465 6d2f 4c69 6272 6172 792f  /System/Library/
│  00000900: 4672 616d 6577 6f72 6b73 2f43 6f72 6546  Frameworks/CoreF
```

**Comment by practicalswift** [comment]
Differences:
* Linux binaries (after `strip`): 40 bytes diff (24 + 16)
* OS X binaries (after `strip`): 16 bytes diff

**Comment by practicalswift** [comment]
```
$ diff -u <(swiftc -emit-sil - < t/test.swift) <(swiftc -emit-sil - < t/test.swift)
--- /dev/fd/63	2017-04-24 21:50:53.252704245 +0200
+++ /dev/fd/62	2017-04-24 21:50:53.252704245 +0200
@@ -1784,13 +1784,13 @@
   // function_ref swift_bufferAllocate
   %27 = function_ref @swift_bufferAllocate : $@convention(thin) (@thick AnyObject.Type, Int, Int) -> @owned AnyObject // user: %28
   %28 = apply %27(%0, %24, %26) : $@convention(thin) (@thick AnyObject.Type, Int, Int) -> @owned AnyObject // user: %29
-  %29 = open_existential_ref %28 : $AnyObject to $@opened("53342E75-2927-11E7-9799-040186211201") AnyObject // users: %34, %30
-  %30 = unchecked_ref_cast %29 : $@opened("53342E75-2927-11E7-9799-040186211201") AnyObject to $Builtin.NativeObject // user: %31
+  %29 = open_existential_ref %28 : $AnyObject to $@opened("532FC78B-2927-11E7-9799-040186211201") AnyObject // users: %34, %30
+  %30 = unchecked_ref_cast %29 : $@opened("532FC78B-2927-11E7-9799-040186211201") AnyObject to $Builtin.NativeObject // user: %31
   %31 = enum $Optional<Builtin.NativeObject>, #Optional.some!enumelt.1, %30 : $Builtin.NativeObject // user: %43
   // function_ref specialized static _HeapBuffer._valueOffset()
   %32 = function_ref @_T0s11_HeapBufferV12_valueOffsetSiyFZs07_StringB5IVarsV_s6UInt16VTgq5Tfq4d_n : $@convention(thin) () -> Int // user: %33
   %33 = apply %32() : $@convention(thin) () -> Int // user: %35
-  %34 = ref_to_raw_pointer %29 : $@opened("53342E75-2927-11E7-9799-040186211201") AnyObject to $Builtin.RawPointer // user: %37
+  %34 = ref_to_raw_pointer %29 : $@opened("532FC78B-2927-11E7-9799-040186211201") AnyObject to $Builtin.RawPointer // user: %37
   %35 = struct_extract %33 : $Int, #Int._value    // user: %36
   %36 = builtin "truncOrBitCast_Int64_Word"(%35 : $Builtin.Int64) : $Builtin.Word // user: %37
   %37 = index_raw_pointer %34 : $Builtin.RawPointer, %36 : $Builtin.Word // user: %38
```

**Comment by practicalswift** [comment]
@jckarter @gottesmm Who is the right code owner for this type of stuff? :-)

**Comment by gottesmm** [comment]
A non-reproducible build is bad. I would suggest filing an SR, committing your test disabled with:

REQUIRES: SRNNNN

And then post that in the SR.

**Comment by practicalswift** [comment]
`.swift_modhash` seems to have been introduced in commit aaaf36e83521f153ba4b0720795efe4980d9b124.

@eeckstein, do you have any idea on how to make this deterministic again? :-)

**Comment by eeckstein** [comment]
swift_modhash contains a hash over the llvm IR. So if this hash is different, also the IR is different.
In other words: if the swift_modhash differs, then something else is already going wrong during compilation.

And BTW, there is already a mechanism to check for reproducibility: the build-script option check-incremental-compilation.
See commit 62597ea58f1b8b38b2d660bd5de2a09d7459c351
The plan was to have a bot running to check for this, but it never came to it.

**Comment by practicalswift** [comment]
@eeckstein The IR generated from `-emir-ir` seems to be identical (see below). What am I missing here? :-)

```
$ diff -u <(swiftc -module-name foo -emit-ir - < t/test.swift) <(swiftc -module-name foo -emit-ir - < t/test.swift)
$
```

**Comment by practicalswift** [comment]
Seems like the `-emit-sil` outputs differs. `-emit-assembly`, `-emit-ir` and `-emit-silgen` outputs are identical.

```
$ diff -u <(swiftc -module-name foo -emit-assembly - < t/test.swift) <(swiftc -module-name foo -emit-assembly - < t/test.swift)
$ diff -u <(swiftc -module-name foo -emit-ir - < t/test.swift) <(swiftc -module-name foo -emit-ir - < t/test.swift)
$ diff -u <(swiftc -module-name foo -emit-silgen - < t/test.swift) <(swiftc -module-name foo -emit-silgen - < t/test.swift)
$ diff -u <(swiftc -module-name foo -emit-sil - < t/test.swift) <(swiftc -module-name foo -emit-sil - < t/test.swift)
--- /dev/fd/63	2017-04-26 09:34:27.911444857 +0200
+++ /dev/fd/62	2017-04-26 09:34:27.911444857 +0200
@@ -1784,13 +1784,13 @@
   // function_ref swift_bufferAllocate
   %27 = function_ref @swift_bufferAllocate : $@convention(thin) (@thick AnyObject.Type, Int, Int) -> @owned AnyObject // user: %28
   %28 = apply %27(%0, %24, %26) : $@convention(thin) (@thick AnyObject.Type, Int, Int) -> @owned AnyObject // user: %29
-  %29 = open_existential_ref %28 : $AnyObject to $@opened("C79FB569-2A52-11E7-97A2-040186211201") AnyObject // users: %34, %30
-  %30 = unchecked_ref_cast %29 : $@opened("C79FB569-2A52-11E7-97A2-040186211201") AnyObject to $Builtin.NativeObject // user: %31
+  %29 = open_existential_ref %28 : $AnyObject to $@opened("C7A0D859-2A52-11E7-97A2-040186211201") AnyObject // users: %34, %30
+  %30 = unchecked_ref_cast %29 : $@opened("C7A0D859-2A52-11E7-97A2-040186211201") AnyObject to $Builtin.NativeObject // user: %31
   %31 = enum $Optional<Builtin.NativeObject>, #Optional.some!enumelt.1, %30 : $Builtin.NativeObject // user: %43
   // function_ref specialized static _HeapBuffer._valueOffset()
   %32 = function_ref @_T0s11_HeapBufferV12_valueOffsetSiyFZs07_StringB5IVarsV_s6UInt16VTgq5Tfq4d_n : $@convention(thin) () -> Int // user: %33
   %33 = apply %32() : $@convention(thin) () -> Int // user: %35
-  %34 = ref_to_raw_pointer %29 : $@opened("C79FB569-2A52-11E7-97A2-040186211201") AnyObject to $Builtin.RawPointer // user: %37
+  %34 = ref_to_raw_pointer %29 : $@opened("C7A0D859-2A52-11E7-97A2-040186211201") AnyObject to $Builtin.RawPointer // user: %37
   %35 = struct_extract %33 : $Int, #Int._value    // user: %36
   %36 = builtin "truncOrBitCast_Int64_Word"(%35 : $Builtin.Int64) : $Builtin.Word // user: %37
   %37 = index_raw_pointer %34 : $Builtin.RawPointer, %36 : $Builtin.Word // user: %38
```

**Comment by eeckstein** [comment]
The diffs in the opened type names do not matter. Those type names are not represented in llvm IR.

It might be that the problem in your original test file is that you are writing to different output files. If you don't set the module name explicitly, the module name is derived from the output file name. And the module name is included in llvm IR. Just try to set the module name explicitly.

**Comment by practicalswift** [comment]
@eeckstein Unfortunately setting the module name explicitly (and compiling with the same output file name) does not solve the issue (see below).

Have any other ideas about the root cause of this? :-)

```
$ swiftc -emit-executable -module-name foo -gnone -o t/test t/test.swift
$ mv t/test t/executable-1
$ swiftc -emit-executable -module-name foo -gnone -o t/test t/test.swift
$ mv t/test t/executable-2
$ strip t/executable-1 t/executable-2
$ diff t/executable-1 t/executable-2
Binary files t/executable-1 and t/executable-2 differ
$ diff -u <(xxd t/executable-1) <(xxd t/executable-2)
--- /dev/fd/63	2017-04-26 21:12:06.001741920 +0200
+++ /dev/fd/62	2017-04-26 21:12:05.993741968 +0200
@@ -38,8 +38,8 @@
 00000250: 6f2e 3200 0400 0000 1000 0000 0100 0000  o.2.............
 00000260: 474e 5500 0000 0000 0200 0000 0600 0000  GNU.............
 00000270: 2000 0000 0400 0000 1400 0000 0300 0000   ...............
-00000280: 474e 5500 f066 611c 5a25 133a 39ac b835  GNU..fa.Z%.:9..5
-00000290: ffe9 84a6 f707 5862 0000 0000 0000 0000  ......Xb........
+00000280: 474e 5500 3ff7 46c8 70e6 30e4 67d6 196f  GNU.?.F.p.0.g..o
+00000290: 2e7c 9586 5e53 0846 0000 0000 0000 0000  .|..^S.F........
 000002a0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
 000002b0: 0100 0000 1200 0000 0000 0000 0000 0000  ................
 000002c0: 0000 0000 0000 0000 2900 0000 2000 0000  ........)... ...
@@ -218,8 +218,8 @@
 00000d90: 0100 0200 0000 0000 0000 0000 0000 0000  ................
 00000da0: 6279 7465 2d66 6f72 2d62 7974 6520 6964  byte-for-byte id
 00000db0: 656e 7469 6361 6c20 6269 6e61 7269 6573  entical binaries
-00000dc0: 2065 7870 6563 7465 6400 0200 84cc 4dbb   expected.....M.
-00000dd0: 2c4f d8a6 b42f b5ac bff0 2c1d 0000 0000  ,O.../....,.....
+00000dc0: 2065 7870 6563 7465 6400 0200 4298 f684   expected...B...
+00000dd0: 845a 8a2f 8e1f 0707 2932 f9be 0000 0000  .Z./....)2......
 00000de0: 2d6c 7377 6966 7443 6f72 6500 2d6c 7377  -lswiftCore.-lsw
 00000df0: 6966 7453 7769 6674 4f6e 6f6e 6553 7570  iftSwiftOnoneSup
 00000e00: 706f 7274 0000 0000 1400 0000 0000 0000  port............
$ diffoscope t/executable-1 t/executable-2
--- t/executable-1
+++ t/executable-2
├── readelf --wide --notes {}
│ @@ -3,13 +3,13 @@
│    Owner                 Data size	Description
│    GNU                  0x00000010	NT_GNU_ABI_TAG (ABI version tag)
│      OS: Linux, ABI: 2.6.32
│
│  Displaying notes found at file offset 0x00000274 with length 0x00000024:
│    Owner                 Data size	Description
│    GNU                  0x00000014	NT_GNU_BUILD_ID (unique build ID bitstring)
│ -    Build ID: f066611c5a25133a39acb835ffe984a6f7075862
│ +    Build ID: 3ff746c870e630e467d6196f2e7c95865e530846
│
│  Displaying notes found at file offset 0x00002150 with length 0x0000001c:
│    Owner                 Data size	Description
│    GNU                  0x00000009	NT_GNU_GOLD_VERSION (gold version)
│      Version: gold 1.11
├── readelf --wide --decompress --hex-dump=.swift_modhash {}
│ @@ -1,4 +1,4 @@
│
│  Hex dump of section '.swift_modhash':
│ -  0x00400dcc 84cc4dbb 2c4fd8a6 b42fb5ac bff02c1d ..M.,O.../....,.
│ +  0x00400dcc 4298f684 845a8a2f 8e1f0707 2932f9be B....Z./....)2..
│
╵
```

**Comment by eeckstein** [comment]
Looks like you created the new file "test" but compared the old files.

**Comment by practicalswift** [comment]
@eeckstein Both files were created as `test` and then renamed – see `mv t/test t/executable-1` and `mv t/test t/executable-2`. That was intentional to rule out any dependencies on the chosen output name :-)

**Comment by eeckstein** [comment]
Sorry, I missed that.
What I recommend to debug this is: write the llvm module to a temporary file in IRGen.cpp, line 294, right after

  llvm::WriteBitcodeToFile(Module, HashStream);

and see if there is any difference.

**Comment by practicalswift** [comment]
@eeckstein 

Seems like the value of `opts.getSingleOutputFilename()` is included in the bitcode!

```
# Extract `bitcode.{01,02}` by hooking in after `llvm::WriteBitcodeToFile(Module, HashStream);` (`IRGen.cpp:294`) while compiling `test.swift` twice: $ llvm-bcanalyzer -dump < bitcode.01 > bitcode.01.dump
$ llvm-bcanalyzer -dump < bitcode.02 > bitcode.02.dump
$ diff -u bitcode.01.dump bitcode.02.dump
--- bitcode.01.dump	2017-04-28 10:28:55.156661932 +0200
+++ bitcode.02.dump	2017-04-28 10:28:59.348530583 +0200
@@ -125,7 +125,7 @@
   <FUNCTION op0=43 op1=16 op2=1 op3=0 op4=1 op5=0 op6=0 op7=0 op8=0 op9=0 op10=0 op11=0 op12=0 op13=0 op14=0/>
   <FUNCTION op0=45 op1=16 op2=1 op3=0 op4=2 op5=0 op6=0 op7=0 op8=0 op9=0 op10=0 op11=0 op12=0 op13=0 op14=0/>
   <FUNCTION op0=45 op1=16 op2=1 op3=0 op4=2 op5=0 op6=0 op7=0 op8=0 op9=0 op10=0 op11=0 op12=0 op13=0 op14=0/>
-  <UnknownCode16 abbrevid=5 op0=47 op1=116 op2=109 op3=112 op4=47 op5=116 op6=101 op7=115 op8=116 op9=45 op10=48 op11=51 op12=56 op13=51 op14=97 op15=101 op16=46 op17=111/> record string = '/tmp/test-0383ae.o'
+  <UnknownCode16 abbrevid=5 op0=47 op1=116 op2=109 op3=112 op4=47 op5=116 op6=101 op7=115 op8=116 op9=45 op10=55 op11=53 op12=49 op13=100 op14=50 op15=54 op16=46 op17=111/> record string = '/tmp/test-751d26.o'
   <VSTOFFSET abbrevid=6 op0=598/>
   <CONSTANTS_BLOCK NumWords=34 BlockCodeSize=4>
     <SETTYPE abbrevid=4 op0=8/>
```

**Comment by eeckstein** [comment]
Good catch!
So you could just write object files instead of executable files

**Comment by practicalswift** [comment]
@eeckstein I'm not sure I understand. Is the temporary file really needed in the bitcode? :-)

**Comment by eeckstein** [comment]
I don't know for what purpose the filename is used.

**Comment by jckarter** [comment]
The UUIDs in printed SIL are purely for reproducibly parsing opened archetypes, and have no other effect on in-memory representation or code generation. However, now that we track def-use chains for opened archetypes in SIL instructions, it would be a good idea to stop using UUIDs and introduce an alternative indexed syntax for them in SIL, maybe something like `$%0`. SIL printing should also be the only place we use libuuid, and it'd be nice to shed that dependency on non-Darwin platforms.

**Comment by CodaFi** [comment]
The effort for reproducible builds has morphed in the two years since this was opened.  For those that are curious, the reproducible SIL modules side of this was raised recently on the forums

https://forums.swift.org/t/reproducible-swiftmodule/30017/2

I'm going to close this out as @practicalswift has since left the community.

**Comment by practicalswift** [comment]
@CodaFi Thanks for following up on this old issue. I'm just resting from compiler fuzzing: we might meet again in this repo in the future :)

**Comment by CodaFi** [comment]
@practicalswift I look forward to the day you fire the fuzzers back up!

**Pull request closed without merging**
