### PR TITLE
Bump the swift-version to 5 for lit tests

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
Verifying the version before creating new preset to support testing for Swift 5, please don't merge this PR.

**Comment by slavapestov** [comment]
I think a bunch of tests are going to need an explicit -swift-version 4

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
```
Test Result (85 failures / +85)
Swift(macosx-x86_64).ClangImporter.enum-dataflow.swift
Swift(macosx-x86_64).ClangImporter.enum.swift
Swift(macosx-x86_64).ClangImporter.objc_parse.swift
Swift(macosx-x86_64).ClangImporter.swift2_warnings.swift
Swift(macosx-x86_64).Constraints.casts_objc.swift
Swift(macosx-x86_64).Constraints.diag_ambiguities.swift
Swift(macosx-x86_64).Constraints.existential_metatypes.swift
Swift(macosx-x86_64).Constraints.iuo.swift
Swift(macosx-x86_64).Constraints.keypath.swift
Swift(macosx-x86_64).Constraints.optional.swift
Swift(macosx-x86_64).IDE.complete_after_self.swift
Swift(macosx-x86_64).IDE.complete_value_expr.swift
Swift(macosx-x86_64).IRGen.enum_value_semantics.sil
Swift(macosx-x86_64).IRGen.enum_value_semantics_future.sil
Swift(macosx-x86_64).IRGen.objc_factory_method.sil
Swift(macosx-x86_64).IRGen.partial_apply_objc.sil
Swift(macosx-x86_64).Incremental/Dependencies.reference-dependencies-fine.swift
Swift(macosx-x86_64).Interpreter/SDK.mapkit_header_static.swift
Swift(macosx-x86_64).Interpreter/SDK.objc_factory_method.swift
Swift(macosx-x86_64).Interpreter/SDK.object_literals.swift
Swift(macosx-x86_64).Interpreter.dynamic_cast_optionals_to_nsobject.swift
Swift(macosx-x86_64).Migrator.api-diff-data-dir.swift
Swift(macosx-x86_64).Migrator.api-special-cases.swift
Swift(macosx-x86_64).Migrator.avoid_insert_existing_functions.swift
Swift(macosx-x86_64).Migrator.call_expr_result.swift
Swift(macosx-x86_64).Migrator.function-hoist.swift
Swift(macosx-x86_64).Migrator.member.swift
Swift(macosx-x86_64).Migrator.missing_script.swift
Swift(macosx-x86_64).Migrator.no_double_edit_ast_pass.swift
Swift(macosx-x86_64).Migrator.pre_fixit_pass.swift
Swift(macosx-x86_64).Migrator.property.swift
Swift(macosx-x86_64).Migrator.qualified-replacement.swift
Swift(macosx-x86_64).Migrator.rename-func-decl.swift
Swift(macosx-x86_64).Migrator.rename-init.swift
Swift(macosx-x86_64).Migrator.rename.swift
Swift(macosx-x86_64).Migrator.rename_cross_file.swift
Swift(macosx-x86_64).Migrator.stdlib_rename.swift
Swift(macosx-x86_64).Migrator.string-representable.swift
Swift(macosx-x86_64).Migrator.wrap_optional.swift
Swift(macosx-x86_64).ModuleInterface.access-filter.swift
Swift(macosx-x86_64).NameLookup.nio_shadowing.swift
Swift(macosx-x86_64).Parse.enum.swift
Swift(macosx-x86_64).PrintAsObjC.availability.swift
Swift(macosx-x86_64).PrintAsObjC.classes.swift
Swift(macosx-x86_64).PrintAsObjC.protocols.swift
Swift(macosx-x86_64).SILGen.functions.swift
Swift(macosx-x86_64).SILGen.guaranteed_normal_args.swift
Swift(macosx-x86_64).SILGen.inlinable_attribute.swift
Swift(macosx-x86_64).SILGen.weak_multiple_modules.swift
Swift(macosx-x86_64).SILOptimizer.definite_init_diagnostics.swift
Swift(macosx-x86_64).Sema.diag_unintended_optional_behavior.swift
Swift(macosx-x86_64).Serialization.struct.swift
Swift(macosx-x86_64).attr.accessibility_print.swift
Swift(macosx-x86_64).attr.attr_noescape.swift
Swift(macosx-x86_64).decl/init.failable.swift
Swift(macosx-x86_64).decl.overload.swift
Swift(macosx-x86_64).decl/protocol.protocols.swift
Swift(macosx-x86_64).expr/unary/keypath.keypath.swift
Swift(macosx-x86_64).multifile/extensions/two-modules.main.swift
Swift(macosx-x86_64).multifile.inlinable.swift
Swift(macosx-x86_64).multifile/synthesized-accessors/two-modules-imported.main.swift
Swift(macosx-x86_64).sil-func-extractor.load-serialized-sil.swift
Swift(macosx-x86_64).stdlib.Filter.swift
Swift(macosx-x86_64).stdlib.Map.swift
Swift(macosx-x86_64).stdlib.Mirror.swift
Swift(macosx-x86_64).stdlib.Reflection_objc.swift
Swift(macosx-x86_64).stdlib.RuntimeObjC.swift
Swift(macosx-x86_64).stdlib.StringDiagnostics.swift
Swift(macosx-x86_64).stdlib.StringFlatMap.swift
Swift(macosx-x86_64).stdlib.TestData.swift
Swift(macosx-x86_64).stdlib.TestIndexSet.swift
Swift(macosx-x86_64).stdlib.TestMeasurement.swift
Swift(macosx-x86_64).stdlib.UnsafePointer.swift.gyb
Swift(macosx-x86_64).stdlib.UnsafeRawPointer.swift
Swift(macosx-x86_64).stdlib.simd_diagnostics.swift
Swift(macosx-x86_64).type.types.swift
Swift(macosx-x86_64).StdlibUnittest.CrashingTests.swift
Swift(macosx-x86_64).compiler_crashers_2_fixed.0160-sr7958.swift
Swift(macosx-x86_64).compiler_crashers_fixed.28638-anonymous-namespace-verifier-checksametype-swift-type-swift-type-char-const.swift
Swift(macosx-x86_64).stdlib/Collection.LazyMapBidirectionalCollection.swift
Swift(macosx-x86_64).stdlib/Collection.LazyMapRandomAccessCollection.swift
Swift(macosx-x86_64).stdlib.CollectionDiagnostics.swift
Swift(macosx-x86_64).stdlib.HashingAvalanche.swift
Swift(macosx-x86_64).stdlib.Lazy.swift.gyb
Swift(macosx-x86_64).stdlib.Range.swift.gyb
```

**Comment by shahmishal** [comment]
```
Test Result (45 failures / +45)
Swift(linux-x86_64).stdlib.Filter.swift
Swift(linux-x86_64).stdlib.Map.swift
Swift(linux-x86_64).stdlib.Mirror.swift
Swift(linux-x86_64).stdlib.StringFlatMap.swift
Swift(linux-x86_64).stdlib.UnsafePointer.swift.gyb
Swift(linux-x86_64).stdlib.UnsafeRawPointer.swift
Swift(linux-x86_64).StdlibUnittest.CrashingTests.swift
Swift(linux-x86_64).stdlib/Collection.LazyMapBidirectionalCollection.swift
Swift(linux-x86_64).stdlib/Collection.LazyMapRandomAccessCollection.swift
Swift(linux-x86_64).stdlib.HashingAvalanche.swift
Swift(linux-x86_64).stdlib.Lazy.swift.gyb
Swift(linux-x86_64).stdlib.Range.swift.gyb
Swift(linux-x86_64).ClangImporter.enum-dataflow.swift
Swift(linux-x86_64).Constraints.diag_ambiguities.swift
Swift(linux-x86_64).Constraints.existential_metatypes.swift
Swift(linux-x86_64).Constraints.iuo.swift
Swift(linux-x86_64).Constraints.keypath.swift
Swift(linux-x86_64).IDE.complete_after_self.swift
Swift(linux-x86_64).IDE.complete_value_expr.swift
Swift(linux-x86_64).IRGen.enum_value_semantics.sil
Swift(linux-x86_64).IRGen.enum_value_semantics_future.sil
Swift(linux-x86_64).IRGen.objc_factory_method.sil
Swift(linux-x86_64).Incremental/Dependencies.reference-dependencies-fine.swift
Swift(linux-x86_64).Migrator.missing_script.swift
Swift(linux-x86_64).ModuleInterface.access-filter.swift
Swift(linux-x86_64).Parse.enum.swift
Swift(linux-x86_64).SILGen.functions.swift
Swift(linux-x86_64).SILGen.guaranteed_normal_args.swift
Swift(linux-x86_64).SILGen.inlinable_attribute.swift
Swift(linux-x86_64).SILGen.weak_multiple_modules.swift
Swift(linux-x86_64).SILOptimizer.definite_init_diagnostics.swift
Swift(linux-x86_64).Sema.diag_unintended_optional_behavior.swift
Swift(linux-x86_64).Serialization.struct.swift
Swift(linux-x86_64).attr.accessibility_print.swift
Swift(linux-x86_64).attr.attr_noescape.swift
Swift(linux-x86_64).decl.overload.swift
Swift(linux-x86_64).decl/protocol.protocols.swift
Swift(linux-x86_64).expr/unary/keypath.keypath.swift
Swift(linux-x86_64).multifile/extensions/two-modules.main.swift
Swift(linux-x86_64).multifile.inlinable.swift
Swift(linux-x86_64).sil-func-extractor.load-serialized-sil.swift
Swift(linux-x86_64).type.types.swift
Swift(linux-x86_64).compiler_crashers_2_fixed.0160-sr7958.swift
Swift(linux-x86_64).compiler_crashers_fixed.28638-anonymous-namespace-verifier-checksametype-swift-type-swift-type-char-const.swift
Swift(linux-x86_64).stdlib.CollectionDiagnostics.swift
```

**Comment by shahmishal** [comment]
```
Failed Tests (32):
  Swift(windows-x86_64) :: type/types.swift
  Swift(windows-x86_64) :: stdlib/UnsafeRawPointer.swift
  Swift(windows-x86_64) :: stdlib/UnsafePointer.swift.gyb
  Swift(windows-x86_64) :: stdlib/StringFlatMap.swift
  Swift(windows-x86_64) :: stdlib/Map.swift
  Swift(windows-x86_64) :: stdlib/Filter.swift
  Swift(windows-x86_64) :: sil-func-extractor/load-serialized-sil.swift
  Swift(windows-x86_64) :: multifile/inlinable.swift
  Swift(windows-x86_64) :: multifile/extensions/two-modules/main.swift
  Swift(windows-x86_64) :: expr/unary/keypath/keypath.swift
  Swift(windows-x86_64) :: decl/protocol/protocols.swift
  Swift(windows-x86_64) :: decl/overload.swift
  Swift(windows-x86_64) :: attr/attr_noescape.swift
  Swift(windows-x86_64) :: attr/accessibility_print.swift
  Swift(windows-x86_64) :: Serialization/struct.swift
  Swift(windows-x86_64) :: Sema/diag_unintended_optional_behavior.swift
  Swift(windows-x86_64) :: SILOptimizer/definite_init_diagnostics.swift
  Swift(windows-x86_64) :: SILGen/weak_multiple_modules.swift
  Swift(windows-x86_64) :: SILGen/inlinable_attribute.swift
  Swift(windows-x86_64) :: SILGen/guaranteed_normal_args.swift
  Swift(windows-x86_64) :: SILGen/functions.swift
  Swift(windows-x86_64) :: ModuleInterface/access-filter.swift
  Swift(windows-x86_64) :: Migrator/missing_script.swift
  Swift(windows-x86_64) :: IRGen/objc_factory_method.sil
  Swift(windows-x86_64) :: IRGen/enum_value_semantics.sil
  Swift(windows-x86_64) :: IDE/complete_value_expr.swift
  Swift(windows-x86_64) :: IDE/complete_after_self.swift
  Swift(windows-x86_64) :: Constraints/keypath.swift
  Swift(windows-x86_64) :: Constraints/iuo.swift
  Swift(windows-x86_64) :: Constraints/existential_metatypes.swift
  Swift(windows-x86_64) :: Constraints/diag_ambiguities.swift
  Swift(windows-x86_64) :: ClangImporter/enum-dataflow.swift
```

**Comment by shahmishal** [comment]
[Linux log](https://github.com/apple/swift/files/5387688/consoleText-260.txt)
[Windows log](https://github.com/apple/swift/files/5387703/consoleText-258.txt)
macOS logs are too large to be attached

**Comment by lorentey** [comment]
Remaining failures: (In optimized mode)

```
Failed Tests (48):
  Swift(macosx-x86_64) :: ClangImporter/enum-dataflow.swift
  Swift(macosx-x86_64) :: ClangImporter/enum.swift
  Swift(macosx-x86_64) :: ClangImporter/objc_parse.swift
  Swift(macosx-x86_64) :: ClangImporter/swift2_warnings.swift
  Swift(macosx-x86_64) :: Constraints/casts_objc.swift
  Swift(macosx-x86_64) :: Constraints/diag_ambiguities.swift
  Swift(macosx-x86_64) :: Constraints/iuo.swift
  Swift(macosx-x86_64) :: Constraints/keypath.swift
  Swift(macosx-x86_64) :: Constraints/optional.swift
  Swift(macosx-x86_64) :: IDE/complete_after_self.swift
  Swift(macosx-x86_64) :: IDE/complete_value_expr.swift
  Swift(macosx-x86_64) :: IRGen/enum_value_semantics.sil
  Swift(macosx-x86_64) :: IRGen/enum_value_semantics_future.sil
  Swift(macosx-x86_64) :: IRGen/objc_factory_method.sil
  Swift(macosx-x86_64) :: IRGen/partial_apply_objc.sil
  Swift(macosx-x86_64) :: Incremental/Dependencies/reference-dependencies-fine.swift
  Swift(macosx-x86_64) :: Interpreter/SDK/mapkit_header_static.swift
  Swift(macosx-x86_64) :: Interpreter/SDK/objc_factory_method.swift
  Swift(macosx-x86_64) :: Interpreter/SDK/object_literals.swift
  Swift(macosx-x86_64) :: Interpreter/dynamic_cast_optionals_to_nsobject.swift
  Swift(macosx-x86_64) :: ModuleInterface/access-filter.swift
  Swift(macosx-x86_64) :: NameLookup/nio_shadowing.swift
  Swift(macosx-x86_64) :: Parse/enum.swift
  Swift(macosx-x86_64) :: PrintAsObjC/availability.swift
  Swift(macosx-x86_64) :: PrintAsObjC/classes.swift
  Swift(macosx-x86_64) :: PrintAsObjC/protocols.swift
  Swift(macosx-x86_64) :: Python/build_swift.swift
  Swift(macosx-x86_64) :: Python/python_lint.swift
  Swift(macosx-x86_64) :: SILGen/functions.swift
  Swift(macosx-x86_64) :: SILGen/guaranteed_normal_args.swift
  Swift(macosx-x86_64) :: SILGen/inlinable_attribute.swift
  Swift(macosx-x86_64) :: SILGen/weak_multiple_modules.swift
  Swift(macosx-x86_64) :: SILOptimizer/definite_init_diagnostics.swift
  Swift(macosx-x86_64) :: Sema/diag_unintended_optional_behavior.swift
  Swift(macosx-x86_64) :: Serialization/struct.swift
  Swift(macosx-x86_64) :: attr/accessibility_print.swift
  Swift(macosx-x86_64) :: attr/attr_noescape.swift
  Swift(macosx-x86_64) :: compiler_crashers_2_fixed/0160-sr7958.swift
  Swift(macosx-x86_64) :: compiler_crashers_fixed/28638-anonymous-namespace-verifier-checksametype-swift-type-swift-type-char-const.swift
  Swift(macosx-x86_64) :: decl/init/failable.swift
  Swift(macosx-x86_64) :: decl/overload.swift
  Swift(macosx-x86_64) :: decl/protocol/protocols.swift
  Swift(macosx-x86_64) :: expr/unary/keypath/keypath.swift
  Swift(macosx-x86_64) :: multifile/extensions/two-modules/main.swift
  Swift(macosx-x86_64) :: multifile/inlinable.swift
  Swift(macosx-x86_64) :: multifile/synthesized-accessors/two-modules-imported/main.swift
  Swift(macosx-x86_64) :: sil-func-extractor/load-serialized-sil.swift
  Swift(macosx-x86_64) :: type/types.swift
```

**Comment by shahmishal** [comment]
@swift-ci test

**Pull request closed without merging**
