### PR TITLE
Extend the lifetime of the buffer while copying from a _CocoaArrayWrapper

### PR DESCRIPTION
**Pull request by DougGregor**
Thanks to @atrick for finding the issue

Fixes rdar://90108215.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci swift please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Review by atrick — APPROVED** [review]
LGTM. It's reasonable to keep the source array alive until the method is done accessing the copied elements. ~I'm guessing the array might be copied to itself~. Actually, any call to `NSArray.getObjects` needs to be guarded by something that forces the array to be alive as long as the copied array contents are accessed.

Adding the `withExtendedLifetime` here is definitely harmless.

**Comment by atrick** [comment]
@lorentey Heads up for any calls to NSArray/NSDictionary `getObjects`. It copies into a C array without retaining the elements so we need to manually keep the original container alive.

**Comment by lorentey** [comment]
🙀 Wow, thanks for catching this!

I would've probably looked at this for hours, assuming `self` was kept alive, and completely missing that this is a `__consuming` method.

**Pull request merged**
