### PR TITLE
[4.0] [ClangImporter] Import-as-member support for anonymous enum constants

### PR DESCRIPTION
**Pull request by jrose-apple**
Cherry-pick of #9633 to the 4.0 branch. Reviewed by @milseman.

rdar://problem/32208235

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@shahmishal, @aciidb0mb3r, the Linux test here seems hung during SwiftPM? No output since 19:13:07.

**Comment by jrose-apple** [comment]
@swift-ci Please test Linux

**Comment by aciidb0mb3r** [comment]
This is most likely https://bugs.swift.org/browse/SR-4885, I'll take a look soon (or disable it).

**Pull request merged**
