### PR TITLE
[Callable] 'func call' -> 'func callAsFunction'.

### PR DESCRIPTION
**Pull request by rxwei**
Apply the final naming decision in [SE-0253](https://github.com/apple/swift-evolution/blob/master/proposals/0253-callable.md) to the 'tensorflow' branch implementation.

Shall be merged in time for the Swift for TensorFlow 0.4 release.

### CODE REVIEW

**Review by dan-zheng — APPROVED** [review]
Great! A sync with `master` after https://github.com/apple/swift/pull/24299 is merged would be nice.

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by rxwei** [comment]
Currently blocked on #25239.

**Comment by rxwei** [comment]
All tests pass now.

**Pull request merged**
