### PR TITLE
[IDE] A few minor changes to set `LeaveClosureBodiesUnchecked` to false in more places

### PR DESCRIPTION
**Pull request by ahoppen**

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please SourceKit stress test

**Review by xedin — APPROVED** [review]
Awesome!

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Pull request merged**
