### PR TITLE
Space Engine: check for empty spaces in Space::forConstructor

### PR DESCRIPTION
**Pull request by jrose-apple**
This is the last optimization performed in Space::simplify, so now we can remove that as well. No intended functionality change.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by jrose-apple** [comment]
@swift-ci Please test compiler performance

**Review by xedin — APPROVED** [review]
Looks great! I really wanted to remove `simplify`, but got side-tracked by other stuff, so now I'm happy :)

**Review by CodaFi — APPROVED** [review]

**Comment by jrose-apple** [comment]
[SourceKit test failed](https://ci.swift.org/job/swift-PR-osx/5974/)

```
[ RUN      ] EditTest.DiagsAfterCloseAndReopen
/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/unittests/SourceKit/SwiftLang/EditingTest.cpp:262: Failure
Value of: expired
  Actual: true
Expected: false
no second notification
[  FAILED  ] EditTest.DiagsAfterCloseAndReopen (11148 ms)
```

@benlangmuir, any ideas?

@swift-ci Please test macOS

**Pull request merged**
