### PR TITLE
SwiftCompilerSources: refactor and verify conformances to ForwardingInstruction

### PR DESCRIPTION
**Pull request by eeckstein**
* add the ability to implement SIL verification in swift
* add all missing instruction classes and require that all new instructions must be added and registered in SwiftCompilerSources as well
* add ForwardingInstruction conformances to missing forwarding instruction classes
* move all the forwarding instruction conformance definitions into ForwardingInstructions.swift

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci test

**Review by atrick — APPROVED** [review]
Awesome. I've been wanting this verification.

Tangentially, it would be nice to verify statically that all instructions added to SILNodes.def exist in Instruction.swift

**Comment by atrick** [comment]
Note that I had made some of the same fixes here:
https://github.com/apple/swift/pull/71703

So I rebased on top of this PR and am now waiting for it to be merged first.

**Comment by atrick** [comment]
@swift-ci test linux platform

**Comment by atrick** [comment]
Rerunning linux tests since the old build log is no longer available.

**Comment by eeckstein** [comment]
@swift-ci test

**Pull request merged**
