### PR TITLE
[5.1][03-18-2019] Parseable interface cherrypicks from 5.1

### PR DESCRIPTION
**Pull request by nathawes**
Various parseable interface cherry-picks.
Resolves rdar://problem/49292914

### CODE REVIEW

**Comment by nathawes** [comment]
@swift-ci please test

**Comment by nathawes** [comment]
@swift-ci please test

**Comment by nathawes** [comment]
@swift-ci please test OS X Platform

**Comment by nathawes** [comment]
@swift-ci please test

**Comment by harlanhaskins** [comment]
Is this good to merge?

**Pull request merged**
