### PR TITLE
Revert "Revert "Revert "[Build System: CMake] make add_swift_library …

### PR DESCRIPTION
**Pull request by gottesmm**
…a wrapper to add_llvm_library"""

This reverts commit 121f5b64beecc3630aea635c304e24e539c2f9b2.

Sorry to revert this again. This commit makes some pretty big changes. After
messing with the merge-conflict created by this internally, I did not feel
comfortable landing this now. I talked with Saleem and he agreed with me that
this was the right thing to do.

### CODE REVIEW

**Comment by gottesmm** [comment]
the xctest failure = /.

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by milseman** [comment]
@compnerd, @gottesmm informs me that you are ok with reverting this for now until after we branch for 5.0, to work around some current instability.

Force merging now to unblock CI systems.

**Comment by gottesmm** [comment]
Thanks @milseman!

**Pull request merged**
