### PR TITLE
Mathable for 5.1 branch

### PR DESCRIPTION
**Pull request by stephentyrone**
This PR contains the protocols and static functions for SE-0246. It is a cherry pick of https://github.com/apple/swift/pull/23824, https://github.com/apple/swift/pull/24187, and https://github.com/apple/swift/pull/24784 for 5.1 branch.

### CODE REVIEW

**Comment by stephentyrone** [comment]
@swift-ci please test

**Comment by stephentyrone** [comment]
@swift-ci please test source compatibility

**Comment by stephentyrone** [comment]
@swift-ci please test

**Comment by stephentyrone** [comment]
@swift-ci please test source compatibility

**Comment by stephentyrone** [comment]
@swift-ci please test

**Comment by stephentyrone** [comment]
@swift-ci please test source compatibility

**Comment by stephentyrone** [comment]
@swift-ci test

**Comment by stephentyrone** [comment]
@swift-ci test source compatibility

**Comment by stephentyrone** [comment]
@swift-ci please smoke test

**Comment by stephentyrone** [comment]
@swift-ci please test

**Comment by stephentyrone** [comment]
@swift-ci please test source compatibility

**Comment by airspeedswift** [comment]
Closing this for not – we need to figure out the type checker consequences before these can be added.

**Pull request closed without merging**
