### PR TITLE
[5.3] Rename Mac Catalyst-related test

### PR DESCRIPTION
**Pull request by beccadax**
Cherry-pick of #31342 to 5.3:

> Fixes rdar://62338598

Original reviewed by @nkcsgexi

### CODE REVIEW

**Comment by brentdax** [comment]
@swift-ci test

**Review by DougGregor — APPROVED** [review]

**Comment by brentdax** [comment]
The merge to master caused problems on Windows, so I’m going to need to cherry-pick a second commit to this PR.

**Comment by brentdax** [comment]
@swift-ci please test and merge

**Comment by brentdax** [comment]
@swift-ci please test and merge

**Pull request merged**
