### PR TITLE
Improve Osize

### PR DESCRIPTION
**Pull request by rajbarik**
Improve Osize by
commit 1: Expose UnrollThreshold and Inline_Benefit_Reduction_Factor in the command line for code size tuning
commit 2:  Use MinSize instead of OptimizeForSize in LLVM function annotation;

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by rajbarik** [comment]
Arnold, 

The following test fails as it checks for optsize as annotation. Let me know how to go about fixing this.
 
/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/swift/test/IRGen/optimize_for_size.sil:16:11: error: expected string not found in input
// CHECK: attributes #0 = {{{.*}}optsize
          ^
<stdin>:12:1: note: scanning from here
entry:
^
<stdin>:16:1: note: possible intended match here
attributes #0 = { minsize norecurse nounwind readnone "no-frame-pointer-elim"="true" "no-frame-pointer-elim-non-leaf" "target-cpu"="x86-64" "target-features"="+fxsr,+mmx,+sse,+sse2,+x87" }
^

**Comment by aschwaighofer** [comment]
The check line should read:
```
// CHECK: attributes #0 = {{{.*}}minsize
```

**Comment by aschwaighofer** [comment]
You would have to modify this line in the file: test/IRGen/optimize_for_size.sil

**Comment by aschwaighofer** [comment]
https://github.com/apple/swift/blob/master/docs/Testing.md describes several ways  how-to run the tests locally

**Comment by rajbarik** [comment]
Thanks. Fixing it.

**Comment by dcci** [comment]
sorry, fat fingering :(

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by rajbarik** [comment]
@aschwaighofer I think we should add a check for  CallerBaseBenefitReductionFactor not being accidentally passed as zero, no? Is it guaranteed from prior checks?
```
const uint64_t CallerBaseBenefitReductionFactor = AI.getFunction()->getModule().getOptions().CallerBaseBenefitReductionFactor;
    BaseBenefit = BaseBenefit / CallerBaseBenefitReductionFactor;
```

**Comment by aschwaighofer** [comment]
@rajbarik No I don't think there is a check. You could add one to CompilerInvocation.cpp

**Pull request merged**
