### PR TITLE
[ownership] Ban cond_br from having any non-trivial operands.

### PR DESCRIPTION
**Pull request by gottesmm**
Previously, we just banned cond_br from having non-trivial operands along
critical edges. This is a stronger condition that beyond simplifying ossa for
passes, also lets me remove the need for BranchPropagatedUser, simplifying the
linear lifetime checker.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
Lets see if anything breaks.

**Review by atrick — APPROVED** [review]
LGTM, but I would prefer not to have the 'isTrivial' check. It doesn't make sense to me to have different forms of branches depending on the operand type!

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Pull request merged**
