### PR TITLE
IRGen/Runtime: Relative-reference the nominal type descriptor and parent type from metadata.

### PR DESCRIPTION
**Pull request by jckarter**
Save a couple relocations per concrete value type, leaving only the value witness table as an absolute symbol.

### CODE REVIEW

**Comment by jckarter** [comment]
This is awaiting matching work from @egranata in lldb to handle the format change.

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
In #1157 it was noted that `gold` doesn't like the `PC64` relocations this produces, which might be a problem for Linux.

**Comment by egranata** [comment]
I'll try to get to it this week

**Comment by jckarter** [comment]
@egranata Any progress?

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by egranata** [comment]
Not yet, sorry - other work has kept me busy all week - and the stable merge seems to have left us in a rather brittle state, so I am hesitant to push changes until that is taken care of. Do you have a deadline to get this in by?

**Comment by jckarter** [comment]
No worries, thanks for the update @egranata. There's no deadline—just the occasion frustration of merge hell keeping the branch alive.

**Pull request closed without merging**
