### PR TITLE
[Runtime] Fix warnings for inconsistent nullability annotation on _stdlib_getEnviron.

### PR DESCRIPTION
**Pull request by mikeash**
rdar://problem/39739801

### CODE REVIEW

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
PR#13254 is related to this.  @jrose-apple and I discussed this on the original PR, and fixing that seemed to uncover something which needed to go through evolution :-(.

**Comment by jrose-apple** [comment]
I'm in favor of `_Null_unspecified` as well.

**Comment by mikeash** [comment]
Given that there seems to be disagreement (between standard and implementation, not just between us!) over whether it is in fact nullable, `_Null_unspecified` actually seems like an accurate annotation for once.

**Comment by mikeash** [comment]
@rjmccall No good reason! I'm going to separate that into another PR now.

**Comment by mikeash** [comment]
Switched to `_Null_unspecified` and cut out the unrelated `offsetof` fix.

**Comment by mikeash** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Pull request merged**
