### PR TITLE
ICU: Update to version 65.1 on Linux

### PR DESCRIPTION
**Pull request by spevans**
Update the ICU library used by Linux from 61.1 to 65.1

Major ICU releases seem to come out in October and March so this would be good to get into 5.2, the current version is from March 2018. 

The tests in PR https://github.com/apple/swift-corelibs-foundation/pull/2535 have been updated and also work correctly when run against native Foundation on Catalina.

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
cc @millenomi @shahmishal

**Comment by shahmishal** [comment]
Please don't merge this until CI has been updated to newer version.

**Comment by millenomi** [comment]
I'm confused; aren't we _building_ this? Is there still a configuration in which we rely on the ICU on the node?

**Comment by millenomi** [comment]
That was to @shahmishal

**Comment by shahmishal** [comment]
We use the update-checkout script for PR testing, and for CI we use Jenkins plugin to checkout branches.

**Comment by spevans** [comment]
@shahmishal is there any update on when this can go in? thanks

**Comment by shahmishal** [comment]
@swift-ci test

**Pull request merged**
