### PR TITLE
[Test] -typecheck -> -emit-ir in test fixed by #7389.

### PR DESCRIPTION
**Pull request by huonw**

### CODE REVIEW

**Comment by huonw** [comment]
@swift-ci Please smoke test and merge

**Comment by slavapestov** [comment]
Thank you!

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Comment by slavapestov** [comment]
@huonw Looks like it's not fixed after all?

**Comment by huonw** [comment]
Weird... I must've tested it wrong. Also, it seems to pass on Linux?

**Pull request closed without merging**
