### PR TITLE
[next][Frontend] Fix use of unique pointer to VFS

### PR DESCRIPTION
**Pull request by xymus**
Update to follow change in LLVM's VFS.

### CODE REVIEW

**Comment by xymus** [comment]
@dexonsmith I think you may have updated this API recently. Does this change look sound to you? And can you tell me if there are more recent VFS changes in LLVM, were are seeing test failures on the next branch that could be related rdar//71497407&71497525&71497629& 71498224.

**Comment by dexonsmith** [comment]
I don't remember changing `pushOverlay`; I'm not sure how my changes would have affected this. I'll take a deeper look though.

**Comment by xymus** [comment]
@dexonsmith I got the impression this was from your clean up of VFS ownership in Apple's LLVM at a22eda548b8e1f9362018dec194af0ca91b35da0.

**Comment by dexonsmith** [comment]
Right, I see it now. We use `auto` a lot less in Clang/LLVM (rule is, never use it if type isn't obvious from context) so we didn't hit this kind of problem there... I thought it was a change with `pushOverlay`, and was scraping `git log` to see what might have changed with that.

I'll take a look at the other issues and see if I can help.

**Comment by dexonsmith** [comment]
(And yes, the change looks sound)

**Comment by dexonsmith** [comment]
> And can you tell me if there are more recent VFS changes in LLVM, were are seeing test failures on the next branch that could be related rdar//71497407&71497525&71497629&71498224.

I looked at those, all related to virtual files in Swift's SourceManager; I don't think they could be related to VFS changes. These are the only things that are recent:
```
$ git log --since October --oneline llvm.org/main -- llvm/include/llvm/Support/VirtualFileSystem.h llvm/lib/Support/VirtualFileSystem.cpp
75cd8d756d6e Support: Add RedirectingFileSystem::create from simple list of redirections
a22eda548b8e VFS: Return new file systems as uniquely owned when possible, almost NFC
e763e032f8bb Support: Change InMemoryFileSystem::addFileNoOwn to take a MemoryBufferRef, NFC
```
and they should all be benign; potentially causing compilation errors, but very low risk of causing behaviour changes. The older changes don't look interesting either.

**Comment by xymus** [comment]
It does look like it would be a different change that would have caused these. Thank you for looking into these! @dexonsmith

**Pull request merged**
