### PR TITLE
Adjust to changes from llvm.org

### PR DESCRIPTION
**Pull request by bulbazord**
This should get swift building again

### CODE REVIEW

**Comment by xiaobai** [comment]
cc @compnerd @shahmishal @JDevlieghere

**Comment by xiaobai** [comment]
@swift-ci please test

**Comment by xiaobai** [comment]
@swift-ci please test Linux Platform

**Comment by xiaobai** [comment]
@swift-ci please test

**Review by Francesco290888 — APPROVED** [review]

**Comment by xiaobai** [comment]
Note: I closed this because it was out of date. I re-used this branch name with the intent of using the same branch name but I forgot about this PR. Will create a new one for my intended purpose.

**Pull request closed without merging**
