### PR TITLE
[embedded] When copying clang builtins from host toolchain, include macho_embedded libraries

### PR DESCRIPTION
**Pull request by kubamracek**
For Embedded Swift, the macho_embedded builtin libraries are useful, they provide builtins for armv6, armv7. They are already distributed with Xcode builds, this change only adds those to the downloadable swift.org toolchains.

Also, let's delete some old code from build-script-impl :)

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by drexin — APPROVED** [review]

**Comment by kubamracek** [comment]
@swift-ci please build toolchain macOS platform

**Review by MaxDesiatov — APPROVED** [review]

**Review by rauhul — APPROVED** [review]

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Pull request merged**
