### PR TITLE
Make serialization lazier and more interface-type-based

### PR DESCRIPTION
**Pull request by DougGregor**
Stop serializing context types in so many places, by serializing interface types instead, then lazily computing the context types when requested. Most of the time, nobody will care about the context types.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by jrose-apple** [comment]
This all looks good except I don't quite get afb39df4. Maybe I just need to look over it more, though.

**Comment by DougGregor** [comment]
We serialize `PatternBindingDecl` nodes for properties in types, and the patterns in those `PatternBindingDecl` nodes have contextual types.

And apparently I broke something badly, so I'll have to clean this PR up a bit more.

**Comment by jrose-apple** [comment]
Y'know, I think we can just drop PBDs from serialization. We already don't seem to preserve them. 

```swift
public struct X {
  public var x, y: Int
}
```

```
% xcrun swift-ide-test -print-module -module-to-print=Test -I . -source-filename=x
struct X {
  var x: Int
  var y: Int
  init(x: Int, y: Int)
}
```

**Comment by jrose-apple** [comment]
Xcode's generated interface also doesn't print `x` and `y` on the same line here across module boundaries.

**Comment by slavapestov** [comment]
Does this supersede #6154?

**Comment by DougGregor** [comment]
It has some of the pieces that went into #6154, but, it's not a full replacement. I'm still trying to make things lazy enough for that to work.

(Comments appreciated on both PRs! I'm going to look into addressing them).

**Comment by DougGregor** [comment]
The `typealias` bit isn't working yet. Drop it for now.

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
(I'll look into the PatternBindingDecl bit)

**Comment by DougGregor** [comment]
Something in AST printing still seems to be making use of `PatternBindingDecl`, and (more importantly) we can still end up serializing local types where the initializer of a `PatternBindingDecl` is its local declaration context. We could do some kind of partial serialization of `PatternBindingDecl`, but that seems dodgy.

**Comment by jrose-apple** [comment]
Hm, okay. I think I'd be happy to figure out how to get an initializer-context bound to a VarDecl instead of a PBD, but we don't have to do it now.

**Comment by DougGregor** [comment]
Hrm, I guess that does work. I had forgotten that we banned, e.g.,

    struct X {
      let (_, _) = (1, 2)
    }

**Comment by jrose-apple** [comment]
If we didn't, that would be an interesting way to inject code into every initializer…

**Comment by DougGregor** [comment]
It's not an unreasonable trick, even.

**Pull request merged**
