### PR TITLE
[Mangler] Check the order of generic type parameters before mangling them.

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@jckarter does this patch make sense to you?

**Comment by jckarter** [comment]
LGTM. It's a good thing to validate. It seems to me that we could potentially push this validation down deeper, maybe into the AST verifier—what do you think @DougGregor or @slavapestov?

**Comment by nkcsgexi** [comment]
It seems that we've already marked decls like this `invalid`. However, using `invalid` to decide whether manglable seems problematic, per @slavapestov 's previous comments. Considering mangler or the new mangler as a standalone thing, i think it is a good idea to make them more error-tolerating.

**Comment by jckarter** [comment]
I agree, I'm just surprised that we would ever construct generic signatures with out-of-order generic parameters even for invalid code. Seems to me like that's something that shouldn't ever happen.

**Comment by slavapestov** [comment]
I don't like that we silently fail if they are out of order. How about asserting in the GenericSignature constructor so we can track down exactly where this is happening?

**Comment by DougGregor** [comment]
I agree that it would be better to assert in the `GenericSignature` constructor that such signatures won't get created. The archetype builder already has a similar assertion.

**Comment by slavapestov** [comment]
We could also assert isValidGenericContext() on the parent DeclContext in validateGenericFuncSignature(). I suspect we are validating contexts in the wrong order in this test case. I need to finish my circularity branch...

**Comment by slavapestov** [comment]
@nkcsgexi Feel free to check this in since it fixes a crasher. Tomorrow if you want we can spend a few minutes digging deeper and root cause the problem.

**Pull request merged**
