### PR TITLE
Handle variadic tuples in reabstraction thunk emission

### PR DESCRIPTION
**Pull request by rjmccall**
Fixes rdar://110391963

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please test

**Comment by rjmccall** [comment]
@swift-ci Please test

**Comment by rjmccall** [comment]
@swift-ci Please test

**Comment by rjmccall** [comment]
@swift-ci Please test

**Review by eeckstein — APPROVED** [review]
SIL changes lgtm.
(I'm not really the right person to review SILGen changes)

**Comment by rjmccall** [comment]
@swift-ci Please smoke test macOS

**Comment by xedin** [comment]
I opened a revert PR for this new test Konrad added - https://github.com/apple/swift/pull/67054

**Pull request merged**
