### PR TITLE
Partially Revert #33371

### PR DESCRIPTION
**Pull request by CodaFi**
It has the right ideas, but the timing was a little funky.

The first commit is pure revert, the second restore the default since that's not a breaking change.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by CodaFi** [comment]
@swift-ci test source compatibility

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Review by slavapestov — APPROVED** [review]
Thanks!

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
