### PR TITLE
[SwiftSyntax] Added helper for swift buildables

### PR DESCRIPTION
**Pull request by kimdv**
Share a helper method to define what type should be used

https://github.com/apple/swift-syntax/pull/284

### CODE REVIEW

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/284

@swift-ci Please test

**Review by ahoppen — APPROVED** [review]

**Comment by ahoppen** [comment]
apple/swift-syntax#284

@swift-ci Please test

**Comment by ahoppen** [comment]
Looks like CI was down earlier. Let’s try again.

apple/swift-syntax#284

@swift-ci Please test

**Comment by kimdv** [comment]
@ahoppen I'm nut sure why. But the linter didn't catch the missing new line at end and missing double space between the definitions. 
Pushed and rebased. Sorry for that.

**Comment by ahoppen** [comment]
No worries @kimdv. Let’s try again.

apple/swift-syntax#284

@swift-ci Please test

**Comment by ahoppen** [comment]
Test failures are unrelated. Let’s try again.

apple/swift-syntax#284

@swift-ci Please test Linux

**Comment by ahoppen** [comment]
apple/swift-syntax#284

@swift-ci Please test Windows

**Comment by ahoppen** [comment]
apple/swift-syntax#284

@swift-ci Please test Windows

**Pull request merged**
