### PR TITLE
[5.5] [SILGen] Used formal type when bridging completion handler arguments.

### PR DESCRIPTION
**Pull request by nate-chandler**
Explanation: When calling ObjC methods from Swift as async methods, a completion handler to be passed to the ObjC method is synthesized by SILGen.  Being called from ObjC, that completion handler receives ObjC types such as ObjCBool and NSString.  On the other hand, the Swift code that is calling-as-async that ObjC method expects native types like Bool and String.  Consequently, part of the completion handler's implementation is to bridge those bridged values to native values.

The utility code for doing this bridging requires the formal type be passed in.  Previously, that foreign type was being retrieved from the lowered type.  For many things (e.g. ObjCBool and NSString), that worked fine.  However, for block types, it did not; the "formal" type that can be obtained from a SILFunctionType is still a SILFunctionType.  And the utility bridging code requires AnyFunctionTypes in order to work.

Here, the formal original native method type is passed down, bridged back to a formal ObjC type, and passed through to the bridging utility code.  Additionally, the abstraction pattern used for unsafe continuations is changed to a type reference from opaque, allowing block arguments not to have bound generic arguments or require an extra thunk.

Issue: rdar://79383990

Original PR: https://github.com/apple/swift/pull/38370 , https://github.com/apple/swift/pull/38785

Testing: New regression tests, Swift CI

Reviewed by: @jckarter

Risk: Low.

Scope: Limited to Swift import of ObjC methods as async functions.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please nominate

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please clean test windows platform

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please clean test windows platform

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
