### PR TITLE
SIL: Don't DFE functions referenced from KeyPath patterns.

### PR DESCRIPTION
**Pull request by jckarter**
Fixes rdar://problem/31776015.

### CODE REVIEW

**Comment by jckarter** [comment]
@eeckstein Mind reviewing this for inclusion in the 4.0 branch? Anywhere else in the SIL passes I should look out to prevent dead elimination of things referenced by key paths?

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Comment by eeckstein** [comment]
LGTM!

> Anywhere else in the SIL passes I should look out to prevent dead elimination of things referenced by key paths?

Look for notifyDeleteFunction().

**Comment by jckarter** [comment]
Thanks!

**Pull request merged**
