### PR TITLE
[ownership] Cleanup OperandOwnershipKindBuiltinClassifier.

### PR DESCRIPTION
**Pull request by gottesmm**
Specifically I did two things:

1. Most of the builtins were using this macro called CONSTANT_OWNERSHIP_BUILTIN,
but really were all Any, MustBeLive. I moved those to use a new macro called
ANY_OWNERSHIP_BUILTIN.

2. I loosened the restrictions around uses of 3 builtins: ErrorInMain,
UnexpectedError, WillThrow. There is no reason that these couldn't necessarily
be guaranteed uses since they are just calling hooks (I think for the
debugger).

3. I made GlobalStringTablePointer just have AnyOwnership. In intention it is a
point use of a String value. That it only takes non-trivial values is a property
of the type system.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
I was thinking about this last night. One could I imagine have a small string that is from an ownership perspective considered to be trivial (for instance if one just constructed it from trivial data). In such a case, one /would/ want to be able to pass a trivial thing to GlobalStringTablePointer.

**Review by atrick — APPROVED** [review]
A String object has ownership regardless of its representation. But the change is fine.

**Comment by ravikandhadai** [comment]
@gottesmm Thanks for pointing me to this commit. I wonder if it would makes sense now to relax the "plus one" requirement for arguments when generated code for a Named Builtin here: https://github.com/apple/swift/blob/ba7393682d220ec4c32208b958315c78177c9778/lib/SILGen/SILGenApply.cpp#L4063 

If that is possible we can eliminate specialized code emitter for the `_globalStringTablePointer` builti (https://github.com/apple/swift/blob/ba7393682d220ec4c32208b958315c78177c9778/lib/SILGen/SILGenBuiltin.cpp#L1037), when essentially doesn't make the arguments "plus one".
@atrick  let me know what you think as well.

**Pull request merged**
