### PR TITLE
Enable SwiftSynax/Parser globally

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @gottesmm @Rostepher @akyrtzi

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by akyrtzi** [comment]
Awesome! 🎉

**Comment by gottesmm** [comment]
@akyrtzi I was talking with compnerd. I am against this switch compiler thing. It is the wrong solution to this problem. From talking with compnerd, the main issue here has to do with blocks. Would you be against eliminating usage of such APIs from SourceKit or at least #ifdef them out for a function pointer + context representation.

We should keep SourceKit as standards compliant as possible.

**Comment by akyrtzi** [comment]
It's not about using blocks in the implementation, it's about using blocks at the C API level.
Without blocks, using the C API from Swift is very awkward, not even sure we can use it appropriately.

**Comment by akyrtzi** [comment]
> or at least #ifdef them out for a function pointer + context representation

This is already the case in the sourcekitd header. In the libSyntaxParser header I didn't do that because it is intended to be used by SwiftSyntax, so not offering the blocks API is not useful.

**Comment by gottesmm** [comment]
@akyrtzi the problem is in the implementation since it means that to compile sourcekit AFAIKT you need clang. You couldn't use MSVC for instance.

**Comment by akyrtzi** [comment]
To clarify, #ifdef'ing the blocks API out of sourcekitd was intended to be supported, and if this is not working then it's something we should fix.
For libSyntaxParser we should just not build it if blocks cannot be used.

**Comment by gottesmm** [comment]
@compnerd I talked with akyrtzi offline. I am fine with this as long as you put it in such that it is really clear that this is only for windows. For instance, I think we should probably put it into a SwiftWindowsSupport.cmake file.

**Comment by compnerd** [comment]
@gottesmm - I'm not sure how this is windows specific?  What happens if we are building with gcc?  gcc doesn't support blocks either.

**Comment by gottesmm** [comment]
@compnerd I do not want to allow this in more places. I am only ok with this since it is very windows specific and since from what I understand msvc helps you debug on windows better. If you want to do this in general, then again I am very against this.

**Comment by compnerd** [comment]
@gottesmm - well, the problem does exist generally is the point - on Windows, this definitely is nearly a requirement (clang is unable to generate Debug Info to the point where its possible to debug).  I think that we need to find a way to make this work across the different compilers then.

**Comment by gottesmm** [comment]
@compnerd well let me turn this around then. How can we do this without using a hack? @akyrtzi Maybe we can move it into a separate swiftpm library that builds against swift syntax?

**Comment by gottesmm** [comment]
*specifically a swiftpm package that links against SourceKit's c++ parser (or whatever) and then provides the c interface.

**Comment by compnerd** [comment]
Oh, absolutely - removing it from the core repository would absolutely solve the issue :-)

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by akyrtzi** [comment]
> *specifically a swiftpm package that links against SourceKit's c++ parser (or whatever) and then provides the c interface.

This is not feasible, the idea is that there's a single C API dynamic library in the toolchain that SwiftSyntax can use. How would this other SPM package going to access the C++ code, put all the static libraries and headers from the project in the toolchain ? That seems like a bad idea to me.

@compnerd the suggestion is to make it MSVC-only because there's much less need to use gcc for building the Swift project. If you really want to use gcc for a non-windows platform you can just exclude building libSyntaxParser, otherwise if you want to include libSyntaxParser just use clang.

**Comment by gottesmm** [comment]
@akyrtzi I am sort of done with this. Lets just get this in, do something special for MSVC so compnerd can get what he wants done and move on.

**Pull request merged**
