### PR TITLE
Reorganize code for findInitExistential

### PR DESCRIPTION
**Pull request by rajbarik**
Currently SILCombiner defines and uses findInitExistential and its associated functions as static and uses them. With the new ExistentialSpecializer pass (https://github.com/apple/swift/pull/13991/), these utility functions are needed outside of SILCombiner. This PR only reorganizes the code (no new code added) and moves  findInitExistentialFromGlobalAddr, getAddressOfStackInit, and findInitExistential  functions to Local.h/cpp.

### CODE REVIEW

**Comment by atrick** [comment]
I don't see anything controversial about this.

**Comment by slavapestov** [comment]
Maybe create a new Existential.h?

**Comment by rajbarik** [comment]
OK.

**Comment by rajbarik** [comment]
@slavapestov @atrick Please have a look. thanks.

**Comment by atrick** [comment]
LGTM

**Comment by atrick** [comment]
@swift-ci  smoke test.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Pull request merged**
