### PR TITLE
[stdlib-DO NOT MERGE] Collection search

### PR DESCRIPTION
**Pull request by lancep**

### CODE REVIEW

**Comment by lancep** [comment]
@swift-ci please test source compatibility

**Comment by lancep** [comment]
@swift-ci please test source compatibility

**Comment by lancep** [comment]
@swift-ci please test source compatibility

**Comment by lancep** [comment]
@swift-ci please test source compatibility

**Comment by lancep** [comment]
@swift-ci please test source compatibility

**Comment by natecook1000** [comment]
Closing this as superseded by some of the consumer/searcher work. @lancep, feel free to re-open or start a discussion in the forums!

**Pull request closed without merging**
