### PR TITLE
Remove prefix+ from StaticBigInt

### PR DESCRIPTION
**Pull request by stephentyrone**
This operator causes source breakage in cases like:
```
let a:Int = 7
let b = +1
let c = a + b  // Error: Cannot convert `b` from `StaticBigInt` to `Int`
```

This is an experimental PR to test removing it; I've started a [pitch thread to discuss the change](https://forums.swift.org/t/pitch-amend-se-0368-to-remove-prefix-operator/62173)

### CODE REVIEW

**Comment by stephentyrone** [comment]
@swift-ci test

**Comment by stephentyrone** [comment]
@benrimmington Can you provide some background on why you had to add this operator to begin with so that we can try to come up with some alternatives?

**Comment by stephentyrone** [comment]
Ok. Then I think we'll probably end up removing it for now (pending sign-off from LWG), since adding it turns out to be source-breaking. We can investigate other alternatives in the future.

**Comment by stephentyrone** [comment]
@swift-ci test

**Comment by stephentyrone** [comment]
@swift-ci smoke test

**Comment by stephentyrone** [comment]
@swift-ci smoke test

**Comment by stephentyrone** [comment]
@swift-ci smoke test

**Comment by tbkka** [comment]
Update:  We're still waiting to merge this until the change is accepted by the Language Working Group.

**Comment by stephentyrone** [comment]
We discussed in LWG today, and agreed to land this as-is, and run a formal amendment to -0368 in the near future.

**Pull request merged**
