### PR TITLE
Update code completion printing for removal of IUOs from the type sys…

### PR DESCRIPTION
**Pull request by rudkx**
…tem.

This doesn't address any issues in loss of functionality when trying
to complete IUO-typed things, just the various printing issues.

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@benlangmuir The PR to actually stop generating IUO-typed things is coming later, so this change should have no impact.

**Comment by rudkx** [comment]
Linux failure: Failed to fetch from git@github.com:apple/swift.git

**Comment by rudkx** [comment]
@swift-ci Please smoke test Linux platform

**Comment by rudkx** [comment]
@benlangmuir Any feedback on the changes, or do you think this is good to merge.

**Review by benlangmuir — APPROVED** [review]

**Pull request merged**
