### PR TITLE
Make -sil-print-only-function take comma separated values

### PR DESCRIPTION
**Pull request by meg-gupta**
With this, something like -sil-print-only=function='foo','bar' can be handled.

### CODE REVIEW

**Comment by meg-gupta** [comment]
I was debugging an issue where I needed to see the SIL of 2 functions and the ordering of the passes mattered. So I extended the meaning of the flag for comma separated list as well.

**Review by atrick — APPROVED** [review]
🥇

**Comment by meg-gupta** [comment]
@swift-ci please smoke test

**Comment by meg-gupta** [comment]
@swift-ci Please clean smoke test Linux platform

**Pull request merged**
