### PR TITLE
[Backtracing] Make the backtracer work for fully-static Linux.

### PR DESCRIPTION
**Pull request by al45tair**
The backtracer and its build system need a couple of changes to make them work with the new fully-static Linux support.

rdar://123507656

### CODE REVIEW

**Comment by al45tair** [comment]
This sits on top of #71844.

**Review by mikeash — APPROVED** [review]
LGTM, I'm assuming I should just be looking at the last commit here.

**Comment by al45tair** [comment]
> LGTM, I'm assuming I should just be looking at the last commit here.

Yes, that's right. It'd be nice if Github had better support for this kind of pattern (a stack of PRs).

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Pull request merged**
