### PR TITLE
[docs] LibraryEvolution: 'final' can be added or removed at will.

### PR DESCRIPTION
**Pull request by jrose-apple**
cc @slavapestov, @rjmccall

### CODE REVIEW

**Comment by tkremenek** [comment]
@swift-ci smoke test

**Comment by rjmccall** [comment]
This is a change of policy for removing final, I think.  It basically means that only code within the resilience domain of the defining module is allowed to perform optimizations that assume finality.

**Comment by jrose-apple** [comment]
Ah, right—that doesn't make any difference for method calls with Slava's formulation, but it might for things on the class level. Still, I'm not sure if any of those matter without further guarantees (like layout constraints).

**Comment by jrose-apple** [comment]
(I'm not counting additional guarantees like inlinability, but I suppose inlineable-and-final is different from inlineable-and-non-final.)

**Pull request closed without merging**
