### PR TITLE
benchmarks: fix smoke test run by setting the dynamic library path

### PR DESCRIPTION
**Pull request by eeckstein**
This is a workaround for rdar://78584073

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by shahmishal** [comment]
@swift-CI smoke benchmark Apple Silicon

**Comment by shahmishal** [comment]
@swift-ci smoke Apple Silicon benchmark

**Pull request merged**
