### PR TITLE
Small refactoring in RRCM

### PR DESCRIPTION
**Pull request by trentxintong**
Please do not merge. This is not critical.

### CODE REVIEW

**Comment by trentxintong** [comment]
@swift-ci Please smoke test

**Comment by trentxintong** [comment]
@swift-ci Please smoke test and merge

**Comment by trentxintong** [comment]
@swift-ci Please smoke test

**Comment by atrick** [comment]
Xin. I need to close this. The linux builds aren't triggering on critical commits. Please reopen when the branch is no longer gated.

**Pull request closed without merging**
