### PR TITLE
Merge 2020-12-02 into tensorflow

### PR DESCRIPTION
**Pull request by dabrahams**

### CODE REVIEW

**Comment by dabrahams** [comment]
Please test with following PRs:
apple/llvm-project#2175

@swift-ci Please clean test TensorFlow

**Comment by dabrahams** [comment]
Please test with following PRs:
apple/llvm-project#2175

@swift-ci Please clean test TensorFlow

**Comment by dabrahams** [comment]
Please test with following PRs:
apple/llvm-project#2175

@swift-ci Please clean test TensorFlow

**Comment by pschuh** [comment]
Please test with following PRs:
apple/llvm-project#2175

@swift-ci Please clean test TensorFlow

**Comment by texasmichelle** [comment]
Closing to refresh `tensorflow-merge` with upstream changes.

**Pull request closed without merging**
