### PR TITLE
[GSB] Check all superclass constraints during finalization.

### PR DESCRIPTION
**Pull request by DougGregor**
Use the same infrastructure we have for same-type-to-concrete
constraints to check superclass constraints. Specifically,

* Track all superclass constraints; never "update" a requirement source
* Remove self-derived superclass constraints
* Pick the best superclass constraint within each connected component
  of an equivalence class and use that for requirement generation.
* Diagnose conflicting superclass constraints during finalization
* Diagnose redundant superclass constraints (during finalization)
* Diagnose conflicts between superclass constraints and concrete constraints
* Diagnose superclass constraints made redundant due to a concrete constraint

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by jrose-apple** [comment]
This is causing us to diagnose in the Foundation overlay on cases like this:

```
func foo<UnitType: Unit>(measurement: Measurement<UnitType>)
```

where the "second superclass constraint" is inferred from the use as Measurement's generic parameter.

**Comment by DougGregor** [comment]
Yeah, I'll suppress the diagnostic in the case where it's an inferred-from-a-type-in-the-signature constraint that makes the explicit constraint redundant.

**Pull request merged**
