### PR TITLE
Revert "Isolated synchronous deinit"

### PR DESCRIPTION
**Pull request by ahoppen**
Reverts swiftlang/swift#60057

This PR is causing quite a few tests to fail, so let’s revert it for now.
- https://ci.swift.org/job/oss-swift-test-stdlib-with-toolchain/9936
- https://ci.swift.org/job/oss-swift_tools-RA_stdlib-RDA_test-simulator/3619
- https://ci.swift.org/job/oss-swift_tools-RA_stdlib-DA_test-device-non_executable/7338
- https://ci.swift.org/job/oss-swift_tools-RA_stdlib-RDA_test-simulator/3619

CC @ktoso

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Review by ktoso — APPROVED** [review]

**Comment by ktoso** [comment]
LGTM, unfortunate... The contributor will be offline for a few weeks so I'll see if I can manage to land this again.

**Comment by ktoso** [comment]
Actually, new idea -- we'll gate this with an experimental flag instead. Please don't revert.

I'll put up the flag so we don't have to keep rebasing the work

**Review by ktoso — CHANGES_REQUESTED** [review]
Going to change this to be guarded by experimental flag instead

**Pull request merged**
