### PR TITLE
[Test] Checked variable lifetimes extend self.

### PR DESCRIPTION
**Pull request by nate-chandler**
Verified that when a __consuming method calls a function which takes a closure that captures self weakly, self is not deallocated until the call returns.  (Note that this is a behavioral change from what occurs when lexical borrow scopes are disabled; in that case, self is deallocated before the call to the function.)

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please clean test linux platform

**Review by atrick — APPROVED** [review]
Thanks! That tests the behavior that I expect.

**Comment by atrick** [comment]
@Catfish-Man do these two tests, the sync test and the async test, match your expectations for behavior with lexical lifetimes enabled?

**Comment by nate-chandler** [comment]
@swift-ci please test

**Pull request merged**
