### PR TITLE
Remove an unnecessary StringRef from a Space Engine diagnostic

### PR DESCRIPTION
**Pull request by CodaFi**
This one is for @nkcsgexi.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please smoke test and merge

**Review by nkcsgexi — APPROVED** [review]
I appreciate it. The combining of all missing cases can be overwhelming in diagnostic messages.

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
While I'm in the area, I've got a better fix for the case we discover an enum element decl has no interface type.  I'm going to bundle it in here.

**Comment by CodaFi** [comment]
Let's see if the Linux builders are green again.

@swift-ci please smoke test Linux platform

**Comment by CodaFi** [comment]
⛵️

**Pull request merged**
