### PR TITLE
AST: Canonicalize types with respect to generic signature when mangling

### PR DESCRIPTION
**Pull request by slavapestov**
In the following example, the two declarations should have
the same mangled type:

```
protocol P {
  associatedtype P
}

func f1<T : P>(_: T) -> T.P where T.P == Int {}
func f2<T : P>(_: T) -> Int where T.P == Int {}
```

To ensure this is the case, canonicalize the entire
GenericFunctionType before taking it apart, instead of
canonicalizing structural components of it.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@bitjammer I think the test failure might be your changes?

**Comment by bitjammer** [comment]
Yes, that was me. I already fixed this, though? I cherry-picked my change to the swift-4.0-branch and stable branch. Hm ... looking.

**Comment by bitjammer** [comment]
Yeah, that was https://github.com/apple/swift-lldb/commit/991790c9ae10790639752dd3df05812f1e0a85a6 . It looks like it's checking out the stable branch, too.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Comment by DougGregor** [comment]
Huh. I'm amazed we didn't notice this before. Thanks!

**Pull request merged**
