### PR TITLE
[metadata prespecialization] Prespecialize common standard library types

### PR DESCRIPTION
**Pull request by airspeedswift**
The standard library is already prespecializing types it uses within itself, but many commonly-used types aren't actually used by the standard library. This adds uses of these types to the std lib to force their prespecialization.

Note this list is **not** ABI. We can add and remove from it in each release. I generated this starter list by looking for types used by more than 1 app in a sample of a few Mac apps run on my desktop. We should eventually make resampling some representative programs to generate this list part of the Swift release process.

There are some types in this list we can't yet prespecialize (like those parameterized by non-nominal types or `AnyObject`) but I'm assuming those are coming so they're fine to keep in here.

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@swift-ci please benchmark

**Review by nate-chandler — APPROVED** [review]
LGTM!  Some of these won't result in prespecialization immediately (such as those involving existentials) but as the functionality gets brought up it they will.

**Comment by airspeedswift** [comment]
@swift-ci please test windows

**Comment by airspeedswift** [comment]
@swift-ci please test macOS

**Comment by nate-chandler** [comment]
@swift-ci please clean test os x platform

**Comment by nate-chandler** [comment]
@swift-ci please clean test macOS

**Pull request merged**
