### PR TITLE
[ConstraintSystem] Avoid exploring too much search space when call ar…

### PR DESCRIPTION
**Pull request by xedin**
…guments are holes

Detect that disjunction is going to be applied to arguments which
don't provide any additional contextual information and allow only
a single choice to be attempted in such case to avoid triggering
exponential behavior in the solver.

The problem is most visible with operators e.g.

```swift
.foo == .bar || 1 == .baz
```

If neither member could be contextually determined and solver was
allowed to attempt all of the overloads for `==` and `||` that
would lead to exponential behavior (because each has 30+ overloads)
and generation of hundreds of partial solutions.

Resolves: rdar://problem/56400265

### CODE REVIEW

**Comment by xedin** [comment]
I just realized that I need to add one more comment which switches `Fixes` storage to `MapVector` to speed up `hasFixFor` checks.

**Comment by xedin** [comment]
I'll get this done tonight.

**Comment by xedin** [comment]
@hborla Actually on the second thought using `hasFixFor` in `simplifyAppliedOverloads` is not that impactful because during constraint generation we won't have any fixes unless expression is incorrect... 

The problem with using set/map for fixes is related to de-duplication and tracking - single locator could have multiple fixes which means we have to use something like `MapVector<ConstraintLocator *, SmallVector<ConstraintFix *, 4>>` but that's pretty hard to track by `SolverScope` to rollback because additions are not going to be linear...

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please smoke test compiler performance

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Review by hborla — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Pull request merged**
