### PR TITLE
Removes redundant buffer zeroing in CGColorSpace.swift by using `init(unsafeUninitializedCapacity:initializingWith:)

### PR DESCRIPTION
**Pull request by valeriyvan**
In `colorTable` getter removes redundant buffer zeroing by using `init(unsafeUninitializedCapacity:initializingWith:)` instead of `init(repeating:count:)`

### CODE REVIEW

**Comment by theblixguy** [comment]
Hi @valeriyvan 

Do you mind updating the title of this PR and the other PRs you’ve recently created? It might be a little confusing for reviewers to keep track of what each PR does if they are all titled the same. It would be great if you can update the description too.

Thanks you!

**Comment by valeriyvan** [comment]
@theblixguy, is it now better?

**Comment by theblixguy** [comment]
Yeah, could you do that for #30131, #30132, #30133 as well since they also have the same title as this one was before?

**Comment by valeriyvan** [comment]
Done

**Comment by milseman** [comment]
@lorentey this is a change against the CoreGraphics overlay. What is the best way to review and incorporate these kinds of changes?

**Comment by valeriyvan** [comment]
ping

**Comment by milseman** [comment]
@lorentey any news here?

**Comment by lorentey** [comment]
@swift-ci test

**Review by lorentey — APPROVED** [review]
Thanks! This looks good to me.

**Comment by lorentey** [comment]
Linux failure looks unrelated, but the macOS build has the same issue as #30133. @valeriyvan

**Comment by valeriyvan** [comment]
ping

**Comment by lorentey** [comment]
@swift-ci test

**Pull request merged**
