### PR TITLE
Change #Color to #colorLiteral (part of SE-0039).

### PR DESCRIPTION
**Pull request by tkremenek**
Change #Color to #colorLiteral (part of SE-0039).

### CODE REVIEW

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by tkremenek** [comment]
@swift-ci smoke test

**Comment by lattner** [comment]
Nice!

**Comment by tkremenek** [comment]
@swift-ci smoke test osx

**Comment by tkremenek** [comment]
@swift-ci smoke test os x

**Comment by tkremenek** [comment]
@swift-ci smoke test OS X platform

**Comment by lattner** [comment]
Wouldn't it make sense to do the other syntax changes at the same time?  Killing off the [##] part of the syntax is also important, maybe you're taking this as a second step though.

**Comment by tkremenek** [comment]
@lattner see #2208 and #2207.

**Comment by tkremenek** [comment]
@lattner, regarding:

> Killing off the [##] part of the syntax is also important, maybe you're taking this as a second step though.

What specifically are you talking about?  I'm looking at the changes specifically in the proposal.  Am I missing something?

**Comment by lattner** [comment]
The current syntax on master uses the  syntax of "[#Color(...)#]".  In addition to changing color to colorLiteral, the [##] syntax around it goes away, replaced with a single # prefix.

**Comment by tkremenek** [comment]
I am going to create a new pull request that handles all the changes for SE-0039 together.

**Pull request closed without merging**
