### PR TITLE
Revert "Finish up parent pointer removal"

### PR DESCRIPTION
**Pull request by graydon**
Reverts apple/swift#12710

This is current leading candidate for the cause of present CI breakage (link errors on metadata of nested type on extension of DispatchQueue, when building Foundation).

### CODE REVIEW

**Comment by graydon** [comment]
@swift-ci please test and merge

**Comment by shahmishal** [comment]
@swift-ci test source compatibility

**Comment by slavapestov** [comment]
@shahmishal I'm not sure what value there is in testing source compatibility with the revert. The original PR was not addressing a source compatibility problem.

**Comment by shahmishal** [comment]
I thought this PR help resolve this issue:

```
Ld build/PromiseKit.build/Release-iphoneos/PromiseKit.build/Objects-normal/armv7/PromiseKit normal armv7
    cd /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite/project_cache/PromiseKit
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk -L/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite/project_cache/PromiseKit/build/Release-iphoneos -F/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite/project_cache/PromiseKit/build/Release-iphoneos -filelist /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite/project_cache/PromiseKit/build/PromiseKit.build/Release-iphoneos/PromiseKit.build/Objects-normal/armv7/PromiseKit.LinkFileList -install_name @rpath/PromiseKit.framework/PromiseKit -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -miphoneos-version-min=8.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite/project_cache/PromiseKit/build/PromiseKit.build/Release-iphoneos/PromiseKit.build/Objects-normal/armv7/PromiseKit_lto.o -fobjc-arc -fobjc-link-runtime -fapplication-extension -L/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite/build/compat_macos/install/toolchain/usr/lib/swift/iphoneos -Xlinker -add_ast_path -Xlinker /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite/project_cache/PromiseKit/build/PromiseKit.build/Release-iphoneos/PromiseKit.build/Objects-normal/armv7/PromiseKit.swiftmodule -single_module -compatibility_version 4.1.7 -current_version 4.1.7 -Xlinker -dependency_info -Xlinker /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite/project_cache/PromiseKit/build/PromiseKit.build/Release-iphoneos/PromiseKit.build/Objects-normal/armv7/PromiseKit_dependency_info.dat -o /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite/project_cache/PromiseKit/build/PromiseKit.build/Release-iphoneos/PromiseKit.build/Objects-normal/armv7/PromiseKit
Undefined symbols for architecture armv7:
  "__T0So13DispatchQueueC0A0E10AttributesVN", referenced from:
      __T010PromiseKit4whenAA0A0CySayxGGq_9fulfilled_Si12concurrentlyts16IteratorProtocolR_ADyxG7ElementRt_r0_lF in when-526DD7E5316B947F.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Ld build/PromiseKit.build/Release-iphoneos/PromiseKit.build/Objects-normal/arm64/PromiseKit normal arm64
    cd /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite/project_cache/PromiseKit
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk -L/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite/project_cache/PromiseKit/build/Release-iphoneos -F/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite/project_cache/PromiseKit/build/Release-iphoneos -filelist /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite/project_cache/PromiseKit/build/PromiseKit.build/Release-iphoneos/PromiseKit.build/Objects-normal/arm64/PromiseKit.LinkFileList -install_name @rpath/PromiseKit.framework/PromiseKit -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -miphoneos-version-min=8.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite/project_cache/PromiseKit/build/PromiseKit.build/Release-iphoneos/PromiseKit.build/Objects-normal/arm64/PromiseKit_lto.o -fobjc-arc -fobjc-link-runtime -fapplication-extension -L/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite/build/compat_macos/install/toolchain/usr/lib/swift/iphoneos -Xlinker -add_ast_path -Xlinker /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite/project_cache/PromiseKit/build/PromiseKit.build/Release-iphoneos/PromiseKit.build/Objects-normal/arm64/PromiseKit.swiftmodule -single_module -compatibility_version 4.1.7 -current_version 4.1.7 -Xlinker -dependency_info -Xlinker /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite/project_cache/PromiseKit/build/PromiseKit.build/Release-iphoneos/PromiseKit.build/Objects-normal/arm64/PromiseKit_dependency_info.dat -o /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite/project_cache/PromiseKit/build/PromiseKit.build/Release-iphoneos/PromiseKit.build/Objects-normal/arm64/PromiseKit
Undefined symbols for architecture arm64:
  "__T0So13DispatchQueueC0A0E10AttributesVN", referenced from:
      __T010PromiseKit4whenAA0A0CySayxGGq_9fulfilled_Si12concurrentlyts16IteratorProtocolR_ADyxG7ElementRt_r0_lF in when-526DD7E5316B947F.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by slavapestov** [comment]
@shahmishal Oh, right. Anyway I have a fix almost ready.

**Pull request closed without merging**
