### PR TITLE
[stdlib] Eliminates redundant buffer zeroing in UnicodeScalarProperties

### PR DESCRIPTION
**Pull request by valeriyvan**
Eliminates redundant buffer zeroing in internal func in UnicodeScalarProperties by using `init(unsafeUninitializedCapacity:initializingWith:)`

### CODE REVIEW

**Review by natecook1000 — APPROVED** [review]
:shipit:

**Comment by natecook1000** [comment]
@swift-ci Please smoke test

**Comment by valeriyvan** [comment]
ping

**Comment by natecook1000** [comment]
@swift-ci Please smoke test and merge

**Comment by valeriyvan** [comment]
ping

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Pull request merged**
