### PR TITLE
[3.1] [ClangImporter] Make sure fake locations are always in /some/ buffer.

### PR DESCRIPTION
**Pull request by jrose-apple**
- **Explanation:** We synthesize fake source locations for module imports that come from Swift code; these locations have to be both valid and distinct for Clang to use. We've mostly been getting away with simply making fake offsets from the main file, but after the offsets start exceeding the size of the buffer they start pointing into some *other* file, and then if Clang's SourceManager tries to order those locations it gets *very* confused. This commit fixes that by allocating a 256K buffer of zeros and using offsets into that instead.
- **Scope:** Unknown. We've seen two failure modes from this: a Clang-side assertion (when assertions are enabled) and diagnostics with bogus locations about modules that have been imported from Swift. The latter can lead to Xcode crashes because of the location being named "\<built-in>"; while this is an unrelated issue that should still be fixed in Xcode, it would be better not to get into that situation in the first place.
- **Issue:** rdar://problem/31417498
- **Reviewed by:** @benlangmuir 
- **Risk:** Medium-low. We're replacing one problematic but longstanding hack with a new, hopefully much safer hack, and have not observed any regressions…but we *think* this was a rare problem to begin with.
- **Testing:** Verified that the original project no longer crashes. Unfortunately it did not seem possible to write a reduced test case that triggered the same failure as before, but the new test case fails if one adds the assertions from this patch and nothing else.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test macOS

**Comment by jrose-apple** [comment]
```
11:28:15 
/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-3.1-branch/swiftpm/Tests/FunctionalTests/ClangModuleTests.swift:146: error: -[FunctionalTests.ClangModulesTestCase testObjectiveCPackageWithTestTarget] : failed - `swift build -c Debug' failed:
11:28:15 
11:28:15 executionFailure(error: exit(1): /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-3.1-branch/buildbot_incremental/swiftpm-macosx-x86_64/release/swift-build --enable-new-resolver --chdir /var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/ClangModules_ObjCmacOSPackage.2Eus1f/ClangModules_ObjCmacOSPackage --configuration debug, output: "Compile ObjCmacOSPackage HelloWorldExample.m\nfatal error: file \'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/sysexits.h\' has been modified since the module file \'/var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/C/org.llvm.clang.buildnode/ModuleCache/26N45F80TQ5O5/Foundation-2FJBXN8U6QRTS.pcm\' was built\nnote: \'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/sysexits.h\' required by \'/var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/C/org.llvm.clang.buildnode/ModuleCache/26N45F80TQ5O5/Darwin-1IVCWVLR6MT9T.pcm\'\nnote: \'/var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/C/org.llvm.clang.buildnode/ModuleCache/26N45F80TQ5O5/Darwin-1IVCWVLR6MT9T.pcm\' required by \'/var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/C/org.llvm.clang.buildnode/ModuleCache/26N45F80TQ5O5/CoreFoundation-RZX25862PY17.pcm\'\nnote: \'/var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/C/org.llvm.clang.buildnode/ModuleCache/26N45F80TQ5O5/CoreFoundation-RZX25862PY17.pcm\' required by \'/var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/C/org.llvm.clang.buildnode/ModuleCache/26N45F80TQ5O5/Foundation-2FJBXN8U6QRTS.pcm\'\nnote: please rebuild precompiled header \'/var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/C/org.llvm.clang.buildnode/ModuleCache/26N45F80TQ5O5/Foundation-2FJBXN8U6QRTS.pcm\'\n1 error generated.\n<unknown>:0: error: build had 1 command failures\nswift-build: error: exit(1): /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-3.1-branch/buildbot_incremental/swiftpm-macosx-x86_64/release/swift-build-tool -f /private/var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/ClangModules_ObjCmacOSPackage.2Eus1f/ClangModules_ObjCmacOSPackage/.build/debug.yaml\n")
```

Hey, @aciidb0mb3r, can SwiftPM use a dedicated module cache for its tests?

**Comment by aciidb0mb3r** [comment]
Sure, I'll create a patch.

**Comment by aciidb0mb3r** [comment]
Created: https://github.com/apple/swift-package-manager/pull/1049

**Comment by jrose-apple** [comment]
Thanks!

@swift-ci please test macOS

**Comment by jrose-apple** [comment]
@swift-ci Please test macOS

**Pull request merged**
