### PR TITLE
[AutoDiff] Part 6: Implement adjoint synthesis

### PR DESCRIPTION
**Pull request by rxwei**
This patch implements adjoint synthesis for automatic differentiation. An _adjoint_ function corresponds to a _primal_ function, representing the reverse sweep on the _original_ function.

See [Automatic Differentiation in Swift](https://github.com/tensorflow/swift/blob/master/docs/AutomaticDifferentiation.md) for more information about the _adjoint_ function.

Adjoint synthesis consists of three parts:
* `AdjointValue` (#18149) caches adjoint values that can be trivially optimized according to their mathematical properties.
* `AdjointRematCloner` rematerializes non-checkpointed primal values on demand.
* `AdjointEmitter` performs a reverse sweep on the original function, emitting the adjoint code for values that are active.

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Review by dan-zheng — APPROVED** [review]
Nice!

**Comment by dan-zheng** [comment]
Does this PR enable e2e single basic block autodiff? Is it possible to add some tests?

**Comment by rxwei** [comment]
Adding tests soon.

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
Spending some time to fix bugs recently. I'm gonna check this in and add follow-up patches later this week.

**Pull request merged**
