### PR TITLE
Eliminated "dangling pointer" warnings at DriverUtils

### PR DESCRIPTION
**Pull request by JacobMao**
Resolves [SR-11741](https://bugs.swift.org/browse/SR-11741)

### CODE REVIEW

**Comment by hamishknight** [comment]
Thanks for the fix! It would be great if we could also avoid using `withMemoryRebound(to:)` here, and instead use `assumingMemoryBound(to:)`, which I believe should be safe given we're passing the pointer off to a C API. Does that sound reasonable @atrick?

**Comment by JacobMao** [comment]
@hamishknight , thanks for your review.

Sure, I can change the code like this:
```swift
      withUnsafeMutablePointer(to: &u) { p in
        let up = UnsafeMutableRawPointer(p).assumingMemoryBound(to: Optional<rusage_info_t>.self)
        let _ = proc_pid_rusage(getpid(), RUSAGE_INFO_V4, up)
      }
```

What do you think?  @atrick

**Comment by atrick** [comment]
I don't know if there's a clearly better thing to do here...

It's "safe" to use `assumingMemoryBound` when passing the resulting pointer directly to C (and not accessing the pointer in Swift), and you happen to know that the type punning will be safe according to C rules. It's unfortunate to rely on implicit restrictions like this though.

`withMemoryRebound(to:)` is the more sanctioned way to temporarily change the pointer type. Sometimes you're still forced to use `assumingMemoryBound` because we haven't yet added a `UnsafeRawPointer.withMemoryRebound(to:)`. In this case you already have a typed pointer, so `withMemoryRebound(to:)` works fine, but it's admittedly very strange to rebind the type of an in-scope local variable like this. Maybe that's the reason @hamishknight suggested changing it.

**Comment by hamishknight** [comment]
@atrick My main concern was the fact that we're re-binding to a type with a different layout, but I guess given we're re-binding to smaller type this shouldn't cause any issues on the Swift side as we'll fully re-bind the memory back to the larger type?

**Comment by atrick** [comment]
@hamin  the `withMemoryRebound` `to` type definitely needs to be "layout compatible" with self's Pointee type. That's not formally defined, but it essentially means that any reference-type members need to be at the same offset, and that the target type can be no bigger than the source type.

The doc comment also says that the `to` type needs to be the same size and stride, but that's an over simplification in the docs to make sure that multiple elements are handled correctly and avoid getting into the details of layout compatibility.

So, although this code seems to violate the docs, in practice, this use is ok (assuming it's binding to a smaller, trivial type), and it will never be flagged as a violation in the future.

In the long run, we should be able to say that `assumingMemoryBound(to:)` is only an acceptable API when the pointer's element type has been erased but is known dynamically. To get to that point, we'll need better documentation, more support for implicit pointer casts when calling C, and better diagnostics.

**Comment by hamishknight** [comment]
@atrick Thanks for clarifying! Let's take this as-is then

**Comment by hamishknight** [comment]
@swift-ci please smoke test

**Comment by hamishknight** [comment]
@swift-ci please smoke benchmark

**Comment by JacobMao** [comment]
Thanks guys

**Pull request merged**
