### PR TITLE
A couple of small SILGen fixes

### PR DESCRIPTION
**Pull request by slavapestov**
- rdar://problem/57864425
- https://bugs.swift.org/browse/SR-12000 / rdar://problem/58455443

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Review by jckarter — APPROVED** [review]
Looks good, thanks!

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Pull request merged**
