### PR TITLE
[sil-optimizer] Compile in SIL verifiers when NDEBUG is enabled and enable them only when -sil-verify-all is enabled.

### PR DESCRIPTION
**Pull request by gottesmm**

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test compiler performance

**Comment by gottesmm** [comment]
@varungandhi-apple I am going to post this PR with some thoughts to the thread on the forums on this topic.

**Review by atrick — APPROVED** [review]
👍

**Comment by gottesmm** [comment]
Going to add some tests to validate -sil-verify-all works with NDEBUG.

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
preset=buildbot,tools=R,stdlib=RD
@swift-ci Please test with preset macOS

**Comment by gottesmm** [comment]
Doing a no-asserts test using the preset to show that the test passes (that is we crash appropriately) on no-asserts builds.

**Pull request merged**
