### PR TITLE
[SourceKit] Conditionally use in-proc for repl

### PR DESCRIPTION
**Pull request by modocache**
#### What's in this pull request?

Most SourceKit build products are linked against either sourcekitd (which uses XPC) or sourcekitdInProc (which does not) based on the `SWIFT_SOURCEKIT_USE_INPROC_LIBRARY` CMake option. Adapt `sourcekitd-repl` to fit this established pattern.

/cc @akyrtzi
#### ~~Resolved~~ Related bug number: ([SR-710](https://bugs.swift.org/browse/SR-710))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by modocache** [comment]
@swift-ci please test

**Comment by modocache** [comment]
@akyrtzi I was very happy to discover the `SWIFT_SOURCEKIT_USE_INPROC_LIBRARY` CMake variable! On the other hand, it's not used everywhere. For example, `sourcekitdAPI-XPC.cpp` is included based on the host platform, not based on this variable. How would you feel about using `SWIFT_SOURCEKIT_USE_INPROC_LIBRARY` everywhere a decision about using XPC or InProc needs to be made, and having this CMake variable set in `build-script-impl`, based on the host platform? I think this would be more consistent.

**Comment by modocache** [comment]
@swift-ci please test

**Comment by briancroom** [comment]
LGTM

**Comment by akyrtzi** [comment]
LGTM!

**Comment by akyrtzi** [comment]
@swift-ci test and merge

**Comment by modocache** [comment]
Great! Thanks, @akyrtzi! 🙇

**Pull request merged**
