### PR TITLE
[cxx-interop] Fix SR-13785

### PR DESCRIPTION
**Pull request by scentini**
Currently, when Swift tries to validate that only visible declarations are used in the module's public interface, it sometimes rejects decls that come from `@_implementationOnly` modules, even in the case where there is a second, non `@_implementationOnly` module that exports the decl (SR-13785). It is common that a single C/C++ header ends up being textually included in multiple Clang modules, triggering the issue.

To address this, before rejecting a decl as not visible, we inspect all non-implementation-only modules transitively reachable from the source file. If a redeclaration exists in one of those modules, Swift won't error out anymore.

This allows us to fix build failures on Foundation caused by PR https://github.com/apple/swift/pull/32404.

### CODE REVIEW

**Comment by scentini** [comment]
@swift-ci please test

**Comment by scentini** [comment]
@swift-ci please test

**Comment by scentini** [comment]
@swift-ci please test

**Comment by scentini** [comment]
@swift-ci please test

**Comment by scentini** [comment]
cc/ @gribozavr

**Comment by CodaFi** [comment]
The approach makes sense, but I have some (possibly half-baked) ideas about the implementation. The main point is that this patch’s algorithm to gather transitive modular dependencies shouldn’t be needed. The set of modules given by `swift::namelookup::getAllImports`  
will already have done that calculation, and I would expect the cost of a `find_if`over that to be comparably performant.  The second note is that you can also check against the full set of imported modules without filtering (even overlays) by asking for the wrapper module of the ClangModule of a given redeclaration.

**Comment by scentini** [comment]
I'm not sure I understand the idea.

Say we have the following module structures, with `->` denoting an import statement:
```
A -> @_implementationOnly B -> C -> clangModule D
```

```
A -> @_implementationOnly B -> C -> clangModule D
  -> E --------------------------------^
```
In the first example the clang module D is not visible, so we cannot use decls from it, while in the second example D is visible, so Swift shouldn't error out when A is using decls from D.

How would `swift::namelookup::getAllImports` with `find_if` help determine whether there exists an import path from `A` to `D` that does not have `@_implementationOnly` imports?

> you can also check against the full set of imported modules without filtering (even overlays) by asking for the wrapper module of the ClangModule of a given redeclaration

IIUC what you suggest would allow us to lookup the wrapper module of the ClangModule directly in the set of transitive modules as opposed to collecting the clang modules. We could do this even with the current code, if that's your preference.

**Comment by hlopko** [comment]
CC @hlopko

**Comment by scentini** [comment]
@CodaFi - I learned that `swift::namelookup::getAllImports` will indeed do the calculation I'm interested in. I also learned about `ModuleDecl::isImportedImplementationOnly()` which in turn calls `getAllImports` so I went ahead and used it. Thanks for the hints! PTAL

**Comment by scentini** [comment]
@swift-ci please test

**Comment by hlopko** [comment]
@swift-ci please test

**Review by CodaFi — APPROVED** [review]
LGTM as a first go. I'm concerned about the average running time of this new check. It might be worth it to e.g. build a table in the clang importer to amortize the cost here.

**Comment by CodaFi** [comment]
@swift-ci test compiler performance

**Comment by scentini** [comment]
@CodaFi can you PTAL at the results? Seems like there is no impact on average running time, is it okay to merge this?

**Comment by CodaFi** [comment]
⛵

**Comment by CodaFi** [comment]
These results confirm that we're not setup to measure the full impact here. Because we're just running source compat a bunch of times on macOS builders, it's unlikely we're hitting this code path with enough regularity to see a win or a loss.

**Pull request merged**
