### PR TITLE
[benchmark] Add RangeIteration benchmarks

### PR DESCRIPTION
**Pull request by moiseev**
Stolen from https://github.com/apple/swift/pull/11917

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by moiseev** [comment]
@swift-ci Please smoke benchmarks

**Comment by atrick** [comment]
👍

**Review by natecook1000 — APPROVED** [review]
Wait, I don't actually see the new benchmarks in the output…

**Comment by moiseev** [comment]
@natecook1000 Yep.. It should have been reported as "Added" or something.

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by moiseev** [comment]
@swift-ci Please smoke benchmark

**Comment by moiseev** [comment]
These numbers don’t make sense at all. But at least here are the added benchmarks =)
@swift-ci Please benchmark

**Pull request merged**
