### PR TITLE
rdar://127199021, fix compatibility with apps that accidentally do [[[aSwiftArray class] new] mutableCopy]

### PR DESCRIPTION
**Pull request by Catfish-Man**

### CODE REVIEW

**Comment by Catfish-Man** [comment]
@swift-ci please smoke test

**Comment by Catfish-Man** [comment]
@swift-ci please smoke test

**Comment by Catfish-Man** [comment]
@swift-ci please smoke test

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Review by parkera — APPROVED** [review]
Please also cherry pick for 6.0 branch, thanks.

**Comment by Catfish-Man** [comment]
@swift-ci Please test Linux platform

**Pull request merged**
