### PR TITLE
Revert "Revert "[android] Update to NDK 23""

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/swift#39791

### CODE REVIEW

**Comment by compnerd** [comment]
@buttaface - CMake documentation also indicates that for cross-compiling to android, you should set `CMAKE_SYSTEM_NAME` to `Android`.  See https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling-for-android.  Is there a reason that wouldn't work?

**Comment by buttaface** [comment]
Yes, this Swift compiler repo largely doesn't conform to CMake cross-compilation. Instead, [it uses its own host variable `SWIFT_HOST_VARIANT_SDK`, which is always passed in by `build-script`,](https://github.com/apple/swift/blob/46f3cc9dd83e26bea4245a327c4ddae70d5ae327/utils/build-script-impl#L574) and if someone doesn't pass in `SWIFT_HOST_VARIANT_SDK` but passes in `CMAKE_SYSTEM_NAME` instead, [it uses `CMAKE_SYSTEM_NAME` to set `SWIFT_HOST_VARIANT_SDK` and then uses the latter from then on](https://github.com/apple/swift/blob/46f3cc9dd83e26bea4245a327c4ddae70d5ae327/CMakeLists.txt#L680). There are [a few places where `CMAKE_SYSTEM_NAME` is incorrectly used also](https://github.com/termux/termux-packages/blob/master/packages/swift/swift-cmake.patch#L195), but it is mostly `SWIFT_HOST_VARIANT_SDK`.

That is why I suggested that you pass in `SWIFT_HOST_VARIANT_SDK` on the Windows CI also, rather than depending on the translation in that second link.

Alternatives would be to reorder this linker configuration after the translation or vice versa, but I don't know if such reordering would break other things.

**Comment by compnerd** [comment]
The changes needed to remove the use of the variable are beyond the authority that I have to enact.  The current mixture of build, host, and target content means that a third variable is required.  This will be required as long as the standard library is part of the build unfortunately.  However, the tools *should* be conforming to the CMake cross-compilation options, and places which are not are a bug.  In fact, @gottesmm has fixed a few of these before, and I have as well.  If you have cases currently which do not conform to that, please let me know, and we can fix those.  But, we really do want to ensure that we get this correct so that we can take advantage of the LLVM build.

The reason that the `SWIFT_HOST_VARIANT_SDK` is set to the value of `CMAKE_SYSTEM_NAME` is because it assumes that you want to build the stdlib for the same host as the tools.  

There are cases where `SWIFT_HOST_SDK_VARIANT` was previously used incorrectly and those have been fixed which is why the Windows builds do not set them - they are building without the stdlib.

As to your idea of sinking the `SWIFT_USE_LINKER` further down, I don't think that moving it is a problem per se, as in it shouldn't break anything.  However, the reason that it is currently early is because it places all the options in a single location so that you can scan through them rather than have to hunt through the entire file.  Given that the other platforms are using the correct `CMAKE_SYSTEM_NAME` variable, I wonder if there is anything to be gained from making Android different here.

**Comment by buttaface** [comment]
> The changes needed to remove the use of the variable are beyond the authority that I have to enact.

Not sure what you're referring to, I didn't mention removing any variable.

> However, the tools should be conforming to the CMake cross-compilation options, and places which are not are a bug. 

No, this Swift compiler repo explicitly rejects using traditional CMake cross-compilation with `CMAKE_SYSTEM_NAME` and only uses `SWIFT_HOST_VARIANT_SDK` instead. That is not a bug, that is the explicit design from the beginning.

Consider [this CMake file that sets the build flags for the host tools: it checks `SWIFT_HOST_VARIANT_SDK` dozens of times and `CMAKE_SYSTEM_NAME` only once](https://github.com/apple/swift/blob/main/cmake/modules/AddSwift.cmake).

> the reason that it is currently early is because it places all the options in a single location so that you can scan through them rather than have to hunt through the entire file.

Yes, I was leery of moving it for that reason too.

> Given that the other platforms are using the correct CMAKE_SYSTEM_NAME variable, I wonder if there is anything to be gained from making Android different here.

I don't think you are too familiar with the current CMake config for this repo: by using `SWIFT_HOST_VARIANT_SDK` for Android, I am following the standard practice for this repo. By not passing in `SWIFT_HOST_VARIANT_SDK` on the Windows CI, you are the one doing something different, see the linked file for example.

**Comment by drexin** [comment]
I agree with @compnerd. `SWIFT_HOST_VARIANT_SDK` is not even set before https://github.com/apple/swift/blob/main/CMakeLists.txt#L718-L719. Passing in `SWIFT_HOST_VARIANT_ARCH ` is optional - as this block clearly shows: https://github.com/apple/swift/blob/main/CMakeLists.txt#L684-L716 - but `CMAKE_SYSTEM_NAME` has to be set properly. Regardless of what is being done today in build-script, the cmake is what's important and we are certainly aiming to move towards using the standard cmake facilities in the future, so it would be great to not make changes that are incompatible with that goal.

**Comment by buttaface** [comment]
> I agree with @compnerd.

It is not clear what you agree with. He has made multiple statements, some of them deeply wrong, while you bring up some different points of when variables are set.

> SWIFT_HOST_VARIANT_SDK is not even set before https://github.com/apple/swift/blob/main/CMakeLists.txt#L718-L719.

Yes, but as I noted above, [it is always passed in by `build-script`, so it is always set long before that](https://github.com/apple/swift/blob/46f3cc9dd83e26bea4245a327c4ddae70d5ae327/utils/build-script-impl#L574). That is why this pull passed the CI on both macOS and Linux. The only reason it fails on the Windows CI is that Saleem is not following the standard set on those other OS's by not passing in `SWIFT_HOST_VARIANT_SDK` himself, when not using `build-script` on Windows.

> Passing in SWIFT_HOST_VARIANT_ARCH is optional - as this block clearly shows: https://github.com/apple/swift/blob/main/CMakeLists.txt#L684-L716 - but CMAKE_SYSTEM_NAME has to be set properly. 

No, [`build-script` always sets `SWIFT_HOST_VARIANT_ARCH` too](https://github.com/apple/swift/blob/46f3cc9dd83e26bea4245a327c4ddae70d5ae327/utils/build-script-impl#L584), so that block is always bypassed. As for `CMAKE_SYSTEM_NAME`, CMake always sets that variable to the build host, which you can override when cross-compiling, but this repo largely doesn't use it.

> Regardless of what is being done today in build-script, the cmake is what's important and we are certainly aiming to move towards using the standard cmake facilities in the future, so it would be great to not make changes that are incompatible with that goal.

That may be the plan, but it is not how this repo works today. The standard is set by how `build-script` works today, I don't see why the Windows CI should work differently. Since this issue is easily fixed by Saleem simply setting `SWIFT_HOST_VARIANT_SDK` to Windows on the Windows CI, [as he does for dozens of other variables to match what `build-script` does](https://github.com/apple/swift/pull/39791#issuecomment-945009881), the easiest way to fix this is for him to add `SWIFT_HOST_VARIANT_SDK` too.

As discussed on that earlier pull where he reverted this, the fundamental problem is that there are two ways to cross-compile the Swift host tools, which is what I do for Android, either by setting `CMAKE_SYSTEM_NAME` or by setting `SWIFT_HOST_VARIANT_SDK`. Since the current `build-script` only sets `SWIFT_HOST_VARIANT_SDK` when cross-compiling this Swift compiler repo- for example, it doesn't set `CMAKE_SYSTEM_NAME` when cross-compiling the host tools for Mac arm64, as I keep repeatedly pointing out in my links- and this repo's CMake config uses `SWIFT_HOST_VARIANT_SDK` almost everywhere internally, it would be better if Saleem also set `SWIFT_HOST_VARIANT_SDK` on the Windows CI.

What you are "aiming to move towards" is irrelevant, it is not how this repo is built today. If this repo ever moves to using `CMAKE_SYSTEM_NAME` instead, we will have to change literally a hundred or more uses of `SWIFT_HOST_VARIANT_SDK` in this repo: this one extra change on the Windows CI is not going to make a difference.

**Comment by drexin** [comment]
Again, what build-script does, or does not pass in is completely irrelevant for how the cmake works. The cmake allows `SWIFT_HOST_VARIANT_SDK` to be passed in, but does not require it. Your PR, as it stands, would change that and require `SWIFT_HOST_VARIANT_SDK` to always be passed in.

I think a feasible solution would be to pass in `LLVM_USE_LINKER` for the Android build. Would that work for you?

**Comment by buttaface** [comment]
> Both @compnerd and I have given you reasons why we don't think this change is correct.

In that case, I've exhaustively argued the opposite: using `CMAKE_SYSTEM_NAME` to set the linker is incorrect in this Swift compiler repo. Honestly, when [I pointed out that every single build flag for the host tools but one is set by `SWIFT_HOST_VARIANT_SDK`](https://github.com/apple/swift/blob/main/cmake/modules/AddSwift.cmake), that was the mic drop for me. I don't know why the two of you are even arguing this silly point after that.

> Using CMAKE_SYSTEM, or using LLVM_USE_LINKER. If neither of those work, I would like to hear the specific reasons why they don't work.

I'll stay away from the silly reasons about being incorrect that you gave and point out that practically, I use the `build-script` to cross-compile and it _only_ passes in `SWIFT_HOST_VARIANT_SDK`, either when natively compiling or cross-compiling this repo. So it makes no sense to pass in `CMAKE_SYSTEM_NAME` on top of that when that is not how the Swift compiler build with `build-script` works.

As for `LLVM_USE_LINKER`, I already wrote you above: "I'd prefer that it's documented here instead" with all the other platform linkers.

Now, I don't think you can say I haven't given you reasons not to do those two, even if you disagree with them.

What about my patch reordering the variables above? I have not heard a peep out of you about that option. We are spending far too much time arguing about what is really a minor issue.

**Pull request closed without merging**
