### PR TITLE
New Async ABI

### PR DESCRIPTION
**Pull request by aschwaighofer**
todo:
* error in async context?
* cache async signatures

### CODE REVIEW

**Comment by rjmccall** [comment]
Arguably the error should be passed as a direct argument to the resumption function.  (That is, the error itself, not a pointer to a variable holding the error.)  However, this would make the nonthrows-to-throws promotion non-trivial for `async` functions; we're allowed to do that, but we'd need to analyze whether it's a good idea.  Maybe there's a way to make that promotion trivial that doesn't require every non-throwing async function to do extra work.  Most invasive idea: we could have different resumption points for the error and non-error resumption paths.  We'd have to reserve space in every context for an error resumption, but since promoted non-throwing functions would just never call it, it would never normally need to be initialized.  This would make error checking zero-cost, except for the cost of having more entry points in the function (but probably the error path is different code anyway).

I don't think `sret` is especially useful here, and LLVM might have a problem with it because we're not actually initializing the value during the call.

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test linux

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci please test os x

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
Please test with the changes from the PR https://github.com/apple/llvm-project/pull/2701

@swift-ci Please test

**Comment by aschwaighofer** [comment]
The windows failure will resolve when https://github.com/apple/llvm-project/pull/2692 merges into `swift/main`.

```
<unknown>:0: error: fatal error encountered during compilation; please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project

<unknown>:0: note: Can't handle guaranteed tail call under win64 yet
```

I had a successful run on windows with a version of that llvm patch here: https://github.com/apple/swift/pull/36448

**Comment by aschwaighofer** [comment]
This passed full macOS tests here: https://ci.swift.org/job/swift-PR-macos/26186/
and full linux tests here: https://ci.swift.org/job/swift-PR-Linux/26155/

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test

**Comment by aschwaighofer** [comment]
Please test with the changes from the PR https://github.com/apple/llvm-project/pull/2701

@swift-ci Please test

**Comment by DougGregor** [comment]
@swift-ci Please test Linux

**Comment by aschwaighofer** [comment]
Unrelated macOS failure:

Failed Tests (1):
  lldb-api :: lang/swift/multilang_category/TestMultilangFormatterCategories.py

And unrelated Linux failure:


unknown>:0: error: module file '/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-driver/module-cache/2QSTF3TCA9P8C/CDispatch-2JBEV7J094K3O.pcm' is out of date and needs to be rebuilt: signature mismatch
<unknown>:0: note: imported by module '_SwiftDispatchOverlayShims' in '/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-driver/module-cache/2QSTF3TCA9P8C/_SwiftDispatchOverlayShims-R85U541UTPA8.pcm'
<unknown>:0: error: missing required module '_SwiftDispatchOverlayShims'
ninja: build stopped: subcommand failed.

**Comment by aschwaighofer** [comment]
@swift-ci please smoke test

**Comment by aschwaighofer** [comment]
Restart because I have just merged the lldb test failure xfail.

@swift-ci please smoke test

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test

**Pull request merged**
