### PR TITLE
[docs] GettingStarted: Tweak one more Ninja target suggestion to work on Apple Silicon

### LINKED ISSUE #62017: Bootstrapping broken for Ninja builds on Apple silicon Macs (arm64)
**Steps To Reproduce**
Build via Ninja on an Apple silicon Mac and [spot check your build](https://github.com/apple/swift/blob/main/docs/HowToGuides/GettingStarted.md#spot-checking-an-incremental-build). Unlike `bootstrapping0/bin/swift-frontend`, `bin/swift-frontend` does not get rebuilt and hence does not reflect the change.

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
Thanks to @Rajveer100 for noticing this.

See https://github.com/apple/swift/issues/62017

### CODE REVIEW

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Comment by Rajveer100** [comment]
> Thanks to @Rajveer100 for noticing this.
> 
> See #62017

Thanks for mentioning me...I should thank you too for believing and uplifting me from the very start when I didn't even have my setup done to fixing my first issue, and coincidentally solving other issues while building and debugging various fixes...

**Review by xedin — APPROVED** [review]
Thank you!

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Pull request merged**
