### PR TITLE
[5.7] Enable string processing by default.

### PR DESCRIPTION
**Pull request by rxwei**
Cherry-pick of #42611.

---

Make frontend flag `-enable-experimental-string-processing` default to true.

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test

**Review by airspeedswift — APPROVED** [review]

**Comment by rxwei** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by rxwei** [comment]
@swift-ci please test

**Comment by rxwei** [comment]
@swift-ci please test

**Comment by stephentyrone** [comment]
@swift-ci test

**Comment by rxwei** [comment]
```console
  Swift(linux-x86_64) :: Index/Store/cross-import-overlay.swift
  Swift(linux-x86_64) :: ScanDependencies/bin_mod_import.swift
  Swift(linux-x86_64) :: SourceKit/DocSupport/doc_cross_import_common.swift
  Swift(linux-x86_64) :: SourceKit/DocSupport/doc_internal_closure_label.swift
  Swift(linux-x86_64) :: SourceKit/DocSupport/doc_swift_module_cross_import.swift
  Swift(linux-x86_64) :: SourceKit/DocSupport/doc_system_module_underscored.swift
  Swift(linux-x86_64) :: SourceKit/InterfaceGen/gen_swift_module.swift
  Swift(linux-x86_64) :: SourceKit/InterfaceGen/gen_swift_module_cross_import.swift
  Swift(linux-x86_64) :: SourceKit/InterfaceGen/gen_swift_module_cross_import_common.swift
```
Looks like most of these are related to cross-import overlays. I looked into it for a while and couldn't figure out why. Some test outputted "_StringProcessing" in the import list but not "_Concurrency", and yet those tests have neither `-disable-implicit-import-string-processing-module-import` or `implicit-import-concurrency-module-import`, or have both.

**Comment by ktoso** [comment]
Looking forward to this 😉 Would be nice to stop special casing on linux builds :-)

**Comment by stephentyrone** [comment]
@swift-ci test

**Comment by stephentyrone** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
```
Failed Tests (9):
  Swift(linux-x86_64) :: Index/Store/cross-import-overlay.swift
  Swift(linux-x86_64) :: ScanDependencies/bin_mod_import.swift
  Swift(linux-x86_64) :: SourceKit/DocSupport/doc_cross_import_common.swift
  Swift(linux-x86_64) :: SourceKit/DocSupport/doc_internal_closure_label.swift
  Swift(linux-x86_64) :: SourceKit/DocSupport/doc_swift_module_cross_import.swift
  Swift(linux-x86_64) :: SourceKit/DocSupport/doc_system_module_underscored.swift
  Swift(linux-x86_64) :: SourceKit/InterfaceGen/gen_swift_module.swift
  Swift(linux-x86_64) :: SourceKit/InterfaceGen/gen_swift_module_cross_import.swift
  Swift(linux-x86_64) :: SourceKit/InterfaceGen/gen_swift_module_cross_import_common.swift

```

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by rxwei** [comment]
@swift-ci please test

**Pull request merged**
