### PR TITLE
[Driver] Denote ABI type in driver invocation

### PR DESCRIPTION
**Pull request by modocache**
Addresses a FIXME to specify ABI type in the driver invocation.

---

See https://github.com/apple/swift/pull/439 for additional context.

### CODE REVIEW

**Comment by gribozavr** [comment]
@modocache As discussed in another PR, we'd need to change the CMake logic to put the library in a different directory.  Do you have access to a Linux machine so that you can test?

**Comment by hpux735** [comment]
There are a few places to look for changes.  One is cmake/modules/AddSwift:44 
```
# Compute the library subdirectory to use for the given sdk and
# architecture, placing the result in 'result_var_name'.
function(compute_library_subdir result_var_name sdk arch)
  set("${result_var_name}" "${SWIFT_SDK_${sdk}_LIB_SUBDIR}/${arch}" PARENT_SCOPE)
endfunction()
```

or starting a 1102 in the same file:

```
1102   # On Linux and FreeBSD add the linker script that coalesces protocol
1103   # conformance sections. This wouldn't be necessary if the link was done by
1104   # the swift binary: rdar://problem/19007002
1105   if("${CMAKE_SYSTEM_NAME}" STREQUAL "Linux" OR
1106      "${CMAKE_SYSTEM_NAME}" STREQUAL "FreeBSD")
1107     list(APPEND link_flags
1108         "-Xlinker" "-T"
1109         "-Xlinker" "${SWIFTLIB_DIR}/${SWIFTLIB_SINGLE_SUBDIR}/swift.ld")
1110   endif()
```

There are quite a few places where `SWIFTLIB_DIR` (and similar) is referenced.

**Comment by hpux735** [comment]
There's another issue with ABIs that would be nice to have fixed.  In the Foundation build scripts, I have to assume gnueabihf if it's an ARM, otherwise it won't build.

**Comment by gottesmm** [comment]
This sounds like something for @jrose-apple.

**Comment by modocache** [comment]
Sorry to keep this open so long. It's outdated to the point that the `FIXME` being addressed doesn't even exist anymore!

**Pull request closed without merging**
