### PR TITLE
[Sema] A couple of pre-checking cleanups

### PR DESCRIPTION
**Pull request by hamishknight**
Simplify a couple of things in `PreCheckExpression`, and use `preCheckTarget` for result builder pre-checking.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
@swift-ci please SourceKit stress test

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please SourceKit stress test

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please SourceKit stress test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Review by xedin — APPROVED** [review]

**Pull request merged**
