### PR TITLE
Add a failing test for SR-13785

### PR DESCRIPTION
**Pull request by scentini**
Adds a test for SR-13785:

If a symbol comes from two modules, one of which is marked as `@_implementationOnly`, Swift may choose the `@_implementationOnly` source and then error out due to the symbol being hidden.

Ideally, Swift would consider all sources for the symbol and recognize that the symbol is not hidden behind `@_implementationOnly `in all modules.

### CODE REVIEW

**Comment by scentini** [comment]
@swift-ci please test

**Comment by scentini** [comment]
@swift-ci please test

**Review by hlopko — APPROVED** [review]

**Comment by hlopko** [comment]
@swift-ci please test

**Comment by hlopko** [comment]
@swift-ci please test

**Pull request merged**
