### PR TITLE
5.7 fix cast ownership

### PR DESCRIPTION
**Pull request by atrick**
Fixes rdar://91768775 (crash when specializing a cast for AnyObject)

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
Linux error:
 FAIL: swift-package-tests :: test-swift-docc/test-swift-docc.txt

**Comment by atrick** [comment]
@swift-ci test linux

**Comment by atrick** [comment]
@eeckstein @tbkka these changes, taken together, should prevent the generation of ownership-guaranteed casts from `T : AnyObject` to `X` where X is a class type.

This SIL becomes illegal, as it should be:

```
class X {}
sil [ossa] @test : $@convention(thin) <T where T : AnyObject> (@guaranteed T) -> Builtin.Int1 {
bb0(%0 : @guaranteed $T):
  checked_cast_br %0 : $T to X, bb1, bb2
```

I'm cherry-picking this back to 5.7 because @eeckstein found this case occurring in a real project. Without these changes, the compiler ignores the SIL above, potentially miscompiling, until the function is specialized. Only when `T` is specialized as `AnyObject` will the compiler assert on the SIL above.

**Review by eeckstein — APPROVED** [review]
lgtm

**Comment by atrick** [comment]
@tbkka hello branch manager

**Comment by atrick** [comment]
@tbkka waiting for branch manager review

**Review by tbkka — APPROVED** [review]

**Pull request merged**
