### PR TITLE
[String] Custom Iterators for String Views

### PR DESCRIPTION
**Pull request by milseman**
Provide a custom iterator rather than relying a the IndexingIterator,
as an indexing model is less efficient for stateful processing of
strings. Provides around a 30% speedup.

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please benchmark

**Comment by milseman** [comment]
@swift-ci please smoke test

**Comment by milseman** [comment]
@swift-ci please benchmark

**Comment by milseman** [comment]
@swift-ci please smoke test

**Comment by milseman** [comment]
@swift-ci please benchmark

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please benchmark

**Comment by milseman** [comment]
@swift-ci please smoke test linux platform

**Comment by milseman** [comment]
@swift-ci please smoke test and merge

**Comment by milseman** [comment]
(full testing passed both platforms prior to the merge conflict on the ABI checker file)

**Comment by milseman** [comment]
@swift-ci please smoke test

**Comment by milseman** [comment]
@swift-ci please smoke test and merge

**Comment by milseman** [comment]
(again, passed testing but there was a merge conflict on abi file)

**Comment by milseman** [comment]
@swift-ci please smoke test and merge

**Comment by milseman** [comment]
@swift-ci please smoke test and merge

**Comment by milseman** [comment]
@swift-ci please smoke test

**Comment by milseman** [comment]
@swift-ci please smoke test linux platform

**Review by lorentey — APPROVED** [review]
Looks good! 👍

**Pull request merged**
