### PR TITLE
Add USR support to swift-demangle

### PR DESCRIPTION
**Pull request by keith**

### CODE REVIEW

**Comment by akyrtzi** [comment]
We prefer to have the format of USRs an implementation detail, and in fact in some instances a USR may not be just a mangled name, we synthesize some USRs for decls that don't usually have mangled names like extensions.

I would recommend against accepting this change.

**Comment by keith** [comment]
> and in fact in some instances a USR may not be just a mangled name, we synthesize some USRs for decls that don't usually have mangled names like extensions.

I think in that case this would still be fine, those would just not be successfully demangled?

**Comment by akyrtzi** [comment]
With this change I assume you want to build some tooling on top, but this works against the main point which is that we want to keep the format implementation detail that can change at any point, and tools should treat them as opaque strings.

**Comment by keith** [comment]
I don't personally want to build anything on top, but when I get USRs back from sourcekit, especially debugging issues, it's often helpful to demangling them. Right now I just manually do this transofrmation.

**Comment by akyrtzi** [comment]
I'd be fine adding this kind of functionality to `swift-ide-test`, but I'd prefer not to have this on `swift-demangle`.

**Comment by keith** [comment]
sounds good, thanks for commenting

**Comment by akyrtzi** [comment]
On `swift-ide-test` we can have it recognize the custom USRs that can be created as well.

**Pull request closed without merging**
