### PR TITLE
[Dependency Scanning] Do not add extra search paths to the Clang's explicit PCM prebuild commands

### PR DESCRIPTION
**Pull request by artemcm**
Clang dependency scanner's output will be complete here w.r.t. the required search paths.

Also enable Clang scanner's search path and include path pruning.

Resolves rdar://107018240

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci smoke test

**Comment by artemcm** [comment]
@swift-ci smoke test Windows platform

**Review by nkcsgexi — APPROVED** [review]

**Comment by artemcm** [comment]
@swift-ci smoke test and merge

**Comment by artemcm** [comment]
@swift-ci smoke test Windows platform

**Pull request merged**
