### PR TITLE
[test/IRGen] Disable incremental llvm compilation for the IRGen tests

### PR DESCRIPTION
**Pull request by vedantk**
---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

This makes the compiler's behavior at debug-time match its behavior at
the initial time of failure. It makes sense to update just the IRGen
tests in particular because these are the most likely to trigger backend
failures.

### CODE REVIEW

**Comment by vedantk** [comment]
@swift-ci Please smoke test OS X platform

**Comment by vedantk** [comment]
@eeckstein could you take a look at this?

I ran the IRGen tests locally and they pass. The smoke test failed with 1 unexpected failure in a file I didn't touch (APINotes/basic.swift). I think that the CI just tripped up here, since it's listing >100 commits in the PR (there's only 1).

**Comment by gribozavr** [comment]
I am concerned about doing manual edits and complicating the RUN lines.  I think this change should be done in one of the %-substitutions.

**Comment by rjmccall** [comment]
I agree with Dmitri 100%.

**Comment by vedantk** [comment]
Ah ok. Would it be OK to change %target-swift-frontend and the various 'mock' versions of it? This would affect all lit tests dependent on these substitutions, not just the ones in IRGen.

**Comment by eeckstein** [comment]
Actually, incremental compilation is only done if the output file is an object file.
Most (all?) of the irgen test files just output llvm-ir files.
So, is there actually any problem with incremental compilation on the irgen tests?

And I think we should not disable incremental compilation for all tests (by changing the substitutions) unless we have a good reason.

**Comment by vedantk** [comment]
Oh, I see. The {IR,SIL}Gen tests usually don't create object files, so disabling incremental compilation would only make sense for end-to-end tests.

**Pull request closed without merging**
