### PR TITLE
More small Sema fixes

### PR DESCRIPTION
**Pull request by slavapestov**
Couldn't sleep on the plane so I fixed compiler crashers instead :)

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
Ok, some patch here is totally broken. Didn't have enough battery power to do a stdlib build or run too many tests :)

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by practicalswift** [comment]
Wow! 11 crashers gone in one go! 👍

**Comment by slavapestov** [comment]
@practicalswift Gotta show the haters how it's done

**Comment by practicalswift** [comment]
@slavapestov That's the spirit! 💯

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by practicalswift** [comment]
Close now! May the Linux buildbot give us green lights for this wonderful PR! 🥇

**Pull request merged**
