### PR TITLE
[Compile Time Constant Extraction] Add extension extraction support

### PR DESCRIPTION
**Pull request by jPaolantonio**
Add extraction for computed variables in extensions.

### CODE REVIEW

**Comment by jPaolantonio** [comment]
@swift-ci test

**Review by artemcm — APPROVED** [review]
Cool. Thanks @jPaolantonio !

**Review by quinntaylor — APPROVED** [review]
Looks great! For completeness, it might also be good to add more properties declared in the extension that will resolve to `valueKind` other than `Runtime`.

**Comment by jPaolantonio** [comment]
> Looks great! For completeness, it might also be good to add more properties declared in the extension that will resolve to `valueKind` other than `Runtime`.

I agree. Ideally, that `Runtime` should also be statically extractable. We do not currently support extracting out `InitValue`s from computed properties. Will fix.

**Pull request merged**
