### PR TITLE
[stdlib] Add @usableFromInline to internal typealiases that need it

### PR DESCRIPTION
**Pull request by lorentey**
This fixes 3659 issues in the standard library, uncovered by @slavapestov's change in https://github.com/apple/swift/pull/17257

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci please smoke test

**Comment by lorentey** [comment]
@swift-ci please clean smoke test macOS platform

**Comment by milseman** [comment]
@swift-ci please smoke test compiler performance

**Review by milseman — APPROVED** [review]
LGTM. Hopefully there's not a large code size cost to the stdlib.

**Comment by slavapestov** [comment]
There should not be a code size cost at all. I already had this change in another PR, I forgot to land it, sorry!

**Review by slavapestov — APPROVED** [review]

**Comment by slavapestov** [comment]
@lorentey You can merge this change. It will have no effect on compiler performance

**Pull request merged**
