### PR TITLE
Swift Driver Cross-Repository Test, Please Ignore

### PR DESCRIPTION
**Pull request by artemcm**

### CODE REVIEW

**Comment by artemcm** [comment]
Together with: https://github.com/apple/swift-driver/pull/570
@swift-ci please smoke test

**Comment by artemcm** [comment]
Together with: apple/swift-driver#570
@swift-ci Please test Ubuntu 18.04 platform

**Comment by artemcm** [comment]
Together with: apple/swift-driver#570
@swift-ci Please test CentOS 7 platform

**Comment by artemcm** [comment]
Together with: apple/swift-driver#570
@swift-ci Please test Amazon Linux 2 platform

**Comment by edymtt** [comment]
Together with: apple/swift-driver#570
@swift-ci Please test CentOS 7 platform

**Comment by edymtt** [comment]
Together with: apple/swift-driver#570
@swift-ci please smoke test Linux

**Comment by edymtt** [comment]
CentOS 7 run seems hitting a type checker failure unrelated to the SwiftDriver change

```
10:00:52 ******************** TEST 'Swift(linux-x86_64) :: Sema/type_checker_perf/fast/rdar23620262.swift' FAILED ********************
10:00:52 Script:
10:00:52 --
10:00:52 : 'RUN: at line 1';   /home/build-user/build/buildbot_linux/swift-linux-x86_64/bin/swift-frontend -target x86_64-unknown-linux-gnu  -module-cache-path /home/build-user/build/buildbot_linux/swift-linux-x86_64/swift-test-results/x86_64-unknown-linux-gnu/clang-module-cache -swift-version 4  -ignore-module-source-info  -typo-correction-limit 10  -typecheck -verify -disable-objc-attr-requires-foundation-module /home/build-user/swift/validation-test/Sema/type_checker_perf/fast/rdar23620262.swift -solver-expression-time-threshold=1
10:00:52 --
10:00:52 Exit Code: 1
10:00:52 
10:00:52 Command Output (stderr):
10:00:52 --
10:00:52 
/home/build-user/swift/validation-test/Sema/type_checker_perf/fast/rdar23620262.swift:7:3: error: unexpected error produced: the compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions
10:00:52 _ = a.map { $0 - 1.0 }
10:00:52   ^
10:00:52 
10:00:52 --
10:00:52 
10:00:52 ********************
```

**Comment by artemcm** [comment]
Together with: apple/swift-driver#570
@swift-ci please smoke test

**Comment by artemcm** [comment]
Together with: apple/swift-driver#570
@swift-ci Please test CentOS 7 platform

**Comment by artemcm** [comment]
Together with: apple/swift-driver#570
@swift-ci please smoke test

**Comment by artemcm** [comment]
Together with: apple/swift-driver#570
@swift-ci Please test CentOS 7 platform

**Comment by artemcm** [comment]
Together with: apple/swift-driver#570
@swift-ci please smoke test

**Comment by artemcm** [comment]
Together with: apple/swift-driver#570
@swift-ci Please test CentOS 7 platform

**Comment by edymtt** [comment]
Together with: apple/swift-driver#570
@swift-ci please test Windows

**Pull request closed without merging**
