### PR TITLE
update tensorflow-swift-apis commit hash

### PR DESCRIPTION
**Pull request by marcrasi**
We want to update tensorflow-swift-apis before building v0.2, right?

Even if tensorflow-swift-apis isn't completely ready, it would be good to update the commit hash now, to give us more time to fix any failures that might appear.

When tensorflow-swift-apis is completely ready, we can update the commit hash again and it'll be a much smaller and less risky change.

### CODE REVIEW

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
we have one more thing that's super important here: https://github.com/tensorflow/swift-apis/pull/35.

**Comment by rxwei** [comment]
merged. could you update the hash?

**Review by rxwei — APPROVED** [review]

**Comment by marcrasi** [comment]
Will update hash and re-test after https://github.com/tensorflow/swift-apis/pull/36 merges.

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Pull request merged**
