### PR TITLE
[NOT FOR MERGE][stdlib] Adding a variant of ??, with a Never returning closure

### PR DESCRIPTION
**Pull request by moiseev**
To support discussion on swift-evolution mailing list, I would like to run this solution through the source compatibility test suite.

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
@swift-ci Please Test Source Compatibility

**Comment by DevAndArtist** [comment]
Just a tiny note: it's not `defaultValue`, but something like `noreturnOrError`. ;)

**Comment by moiseev** [comment]
@DevAndArtist oh sure. This is just a copy-n-paste that's not meant to be merged. Simply to support the mailing list discussion.

**Pull request closed without merging**
