### PR TITLE
Enable strict verification of begin_access patterns in all SIL passes.

### PR DESCRIPTION
**Pull request by atrick**
This also adds handling additional cases like global addressors.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
@swift-ci source compatibility test.

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
@shajrawi, @devincoughlin, @rjmccall. These changes were reviewed in an earlier PR. The only thing that changed since then is that DiagnoseStaticExclusivity now ignores access markers with "unsafe" enforcement. Unsafe accesses are not required to be from identifiable addresses. e.g. in lldb we simply load from a RawPointer. That can't be allowed with enforced access.

This works around failures caused by the original PR, which prevented DiagnoseStaticExclusivity from bailing out on unrecognized patterns. This pass, along with any optimistic exclusivity optimizations, must be sound. They cannot allow for any unknown or unrecognized access patterns. Otherwise future changes to SIL could weaken exclusivity with no way to catch the problem.

**Comment by rjmccall** [comment]
This makes sense to me, but I don't understand how it's not causing major problems with addressors and materializeForSet, since we don't emit `begin_access [unsafe]` after the `pointer_to_address` instructions in them.

**Comment by atrick** [comment]
@rjmccall Yeah, it's a problem if we inline nested static access on an `inout`.
But I think your fix takes care of that nicely.
https://github.com/apple/swift/commit/67fe633

**Comment by rjmccall** [comment]
Okay.  Do you want to take that and actually do the test updates?  I just wrote it up to unblock work on my PR, which doesn't have a known timeline yet.

**Comment by atrick** [comment]
I already stole your commit and disabled the SIL verifier check on trunk. So I'll be pushing your commit before reenabling the verification.

**Pull request merged**
