### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by gkaimakas**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test and merge

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Comment by xedin** [comment]
@swift-ci Please smoke test and merge

**Pull request merged**
