### PR TITLE
[Runtime] Add a function pointer for intercepting swift_willThrow calls.

### PR DESCRIPTION
**Pull request by mikeash**
rdar://problem/53400364

### CODE REVIEW

**Review by jckarter — APPROVED** [review]
This seems a lot better for a tools-only hook, thanks!

**Comment by mikeash** [comment]
@jckarter thank *you* for your valuable feedback!

**Review by stmontgomery — APPROVED** [review]
Looks good to me, thanks!

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test windows platform

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test windows platform

**Comment by mikeash** [comment]
@swift-ci please test windows platform

**Comment by mikeash** [comment]
The Windows failure looks unrelated so I'll merge this.

**Pull request merged**
