### PR TITLE
Reenable pruning of v-tables

### PR DESCRIPTION
**Pull request by AZero13**
The miscompilation should be resolved by now

### CODE REVIEW

**Comment by AtariDreams** [comment]
@nate-chandler Could you please initiate the tests?

**Comment by nate-chandler** [comment]
Could you point me to the commit that fixes the issue?

**Comment by AtariDreams** [comment]
@compnerd Thoughts?

**Comment by glessard** [comment]
Unfortunately the bug avoided by this workaround has not been corrected yet.
Re-enabling this is part of the bug-fix task list.

**Pull request closed without merging**
