### PR TITLE
[swift-3.1-branch] Delete the unused integer protocols

### PR DESCRIPTION
**Pull request by moiseev**
The protocols were included in Beta 2 by mistake and should be removed.
<rdar://problem/30341102>

* Explanation: The corresponding change was reverted in Swift 3.0 branch but never in master.
* Scope of Issue: Extra protocols that no types in standard library conform to.
* Origination: Accidentally shipped.
* Risk: Minimal
* Reviewed By: Ben Cohen
* Testing: Test suite
* Directions for QA: N/A

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
@swift-ci Please test macOS platform

**Comment by natecook1000** [comment]
@swift-ci Please test macOS platform

**Comment by natecook1000** [comment]
@swift-ci Please test macOS platform

**Review by airspeedswift — APPROVED** [review]

**Comment by airspeedswift** [comment]
Doesn't look like the failing test is related to the change, does this need rebasing to fix some since-resolved bug elsewhere?

**Comment by airspeedswift** [comment]
@swift-ci Please clean test macOS platform

**Pull request merged**
