### PR TITLE
[cxx-interop] Lazily instanciate var types and compute their type.

### PR DESCRIPTION
**Pull request by zoecarver**

### CODE REVIEW

**Comment by zoecarver** [comment]
@swift-ci please test

**Comment by zoecarver** [comment]
The macos and linux toolchain builds:

https://ci.swift.org/job/swift-PR-toolchain-macos/298/

https://ci.swift.org/job/swift-PR-toolchain-Linux/175/

Looks like the linux one didn't generate any artifacts :(

**Comment by zoecarver** [comment]
@swift-ci please test

**Comment by zoecarver** [comment]
@swift-ci please test

**Comment by hyp** [comment]
it was here: 

https://download.swift.org/tmp/pull-request/61026/175/ubuntu2004/PR-ubuntu2004.tar.gz

**Pull request merged**
