### PR TITLE
[ResultBuilders] Make sure that `case` body variables get types

### PR DESCRIPTION
**Pull request by xedin**
Solution application needs to set interface types for variables
declared in a `case` statement, otherwise this would lead to crashes
in SILGen.

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Review by hborla — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Pull request merged**
