### PR TITLE
[Do not merge] Test benchmark runs

### PR DESCRIPTION
**Pull request by eeckstein**

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci smoke benchmark staging

**Comment by eeckstein** [comment]
@swift-ci smoke benchmark staging

**Comment by eeckstein** [comment]
@swift-ci smoke benchmark staging

**Comment by eeckstein** [comment]
@swift-ci smoke benchmark staging

**Comment by eeckstein** [comment]
@swift-ci smoke benchmark staging

**Comment by eeckstein** [comment]
@swift-ci smoke benchmark staging

**Comment by eeckstein** [comment]
@swift-ci smoke benchmark staging

**Comment by shahmishal** [comment]
@swift-ci smoke benchmark

**Comment by shahmishal** [comment]
@swift-ci smoke benchmark

**Comment by eeckstein** [comment]
@swift-ci Please smoke benchmark

**Comment by palimondo** [comment]
@eeckstein Shouldn't the console log file also include the contents of benchmarking logs? I see only: 

````
Testing optimization level -O
    Iteration 1 for …
    … 
Logfiles written to …
````

 Or is there other way I can see these benchmarking logs?

**Comment by eeckstein** [comment]
The benchmark output is only written to the log files, but not copied into the console. But you can download the log files of the last run from the workspace. But only until the workspace gets cleaned by the next build.

**Comment by palimondo** [comment]
I'm having trouble finding the workspace… the only "Workspace" I found in Jenkins was hidden in the chevron menu after `swift-PR-osx-smoke-perf-staging` in the breadcrumbs at the top of the page but that leads to [Error: no workspace](https://ci.swift.org/job/swift-PR-osx-smoke-perf-staging/ws/). Moreover that link is not specific to a given build. Where can I get the benchmark logs from?

**Comment by shahmishal** [comment]
We run clean up job daily, so you might see the workspace because this build deleted the workspace - https://ci.swift.org/job/clean-workspace-macOS/21698/

**Comment by shahmishal** [comment]
@swift-ci benchmark

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Comment by shahmishal** [comment]
@swift-ci benchmark

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Comment by CodaFi** [comment]
@eeckstein do you still need this branch?

**Pull request closed without merging**
