### PR TITLE
 Add architecture specific path variables to SwiftConfigureSDK

### PR DESCRIPTION
**Pull request by lanza**
New variables are introduced to track the path for the architecture
specific subdirectories

This work is mostly attributed to Zach Bowling

### CODE REVIEW

**Comment by lanza** [comment]
@compnerd please test

**Comment by compnerd** [comment]
This is NFC

**Comment by compnerd** [comment]
@swift-ci please smoke test and merge

**Comment by compnerd** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
