### PR TITLE
[stdlib] Restore signatures to use UnsafeMutableBufferPointer.

### PR DESCRIPTION
**Pull request by rudkx**
Resolves rdar://problem/21933004.

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@moiseev I am pretty sure the crashes I'm seeing with this are due to the way these tests are set up.

In `CheckMutableCollectionType.swift.gyb`, there is `self.test("\(testNamePrefix)._withUnsafeMutableBufferPointerIfSupported()/semantics")`, and that is within 
```
  public func addMutableCollectionTests<
    C : MutableCollection,
    ...
```

The test does
```
var result = c._withUnsafeMutableBufferPointerIfSupported { ... }
if withUnsafeMutableBufferPointerIsSupported { /* code that force-unwraps result */ }
```

where `c` is a `C` (i.e. `MutableCollection`).

For certain collections, e.g. `ArraySlice`, we set up the tests such that `withUnsafeMutableBufferPointerIsSupported ` is true.

However, for `MutableCollection`, `_withUnsafeMutableBufferPointerIfSupported` always returns nil:
```
extension MutableCollection {
  @_inlineable
  public mutating func _withUnsafeMutableBufferPointerIfSupported<R>(
    _ body: (inout UnsafeMutableBufferPointer<Iterator.Element>) throws -> R
  ) rethrows -> R? {
    return nil
  }
```

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
This are the failures from the validation test suite in case the logs are gone before you get a chance to take a look:

```
Test Result (8 failures / +7)
  Swift(macosx-x86_64).stdlib/Array.Array_MutableRandomAccessCollectionRef.swift
  Swift(macosx-x86_64).stdlib/Array.Array_MutableRandomAccessCollectionVal.swift
  Swift(macosx-x86_64).stdlib/Array.ArraySlice_MutableRandomAccessCollectionRef.swift
  Swift(macosx-x86_64).stdlib/Array.ArraySlice_MutableRandomAccessCollectionVal.swift
  Swift(macosx-x86_64).stdlib/Array.ArraySliceWithNonZeroStartIndex_MutableRandomAccessCollectionRef.swift
  Swift(macosx-x86_64).stdlib/Array.ArraySliceWithNonZeroStartIndex_MutableRandomAccessCollectionVal.swift
  Swift(macosx-x86_64).stdlib/Array.ContiguousArray_MutableRandomAccessCollectionRef.swift
  Swift(macosx-x86_64).stdlib/Array.ContiguousArray_MutableRandomAccessCollectionVal.swift
```

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@moiseev @airspeedswift Finally tracked down the test failures I was seeing to a minor mistake in my changes - a small mismatch in function signatures.

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by moiseev** [comment]
@swift-ci Please smoke benchmark

**Comment by moiseev** [comment]
@swift-ci Please smoke benchmark

**Comment by rudkx** [comment]
Okay that's a really strange failure in the benchmarks build. It looks like the stdlib build has some of my changes but not all of them?!

**Comment by rudkx** [comment]
@swift-ci Please smoke benchmark

**Comment by moiseev** [comment]
@swift-ci Please clean smoke benchmark

**Review by moiseev — APPROVED** [review]
:shipit:

**Comment by rudkx** [comment]
For some reason the benchmark build seems to be picking up the protocol requirement changes, but it seems like for some reason the other changes aren't getting re-gyb'ed.

This should not have any impact on performance, so merging. If that assumption is incorrect we'll see it in the post-commit perf testing.

**Pull request merged**
