### PR TITLE
[const-expr] Teach const-expr evaluator about destructures and transl…

### PR DESCRIPTION
**Pull request by gottesmm**
…ate its main test into an ownership test.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
There is also a subsequent commit that is going to fix switch_enum. This just goes in first.

**Comment by ravikandhadai** [comment]
@gottesmm Thanks for making this change. I guess there was some source-level test in pound_assert.swift that failed because of not handling destructures. Is that right?  If so, can you please let me know which test failed?  Based on my understanding of this https://forums.swift.org/t/sil-ownership-model-proposal-refreshed/16872#value-projections-and-destructures, does this mean we have some entity in the pound_assert.swift test file with `Owned`  semantics?  cc @devincoughlin

**Comment by gottesmm** [comment]
I talked with @ravikandhadai and I explained to him that this only fails with my forthcoming change to have ownership be stripped at -Onone after serialization. The *.swift test will only fail once I flip the switch. These tests ensure that we do not regress from the given fix.

**Pull request merged**
