### PR TITLE
[IRGen] Introduce SymbolObjectCodeRequest

### PR DESCRIPTION
**Pull request by hamishknight**
Introduce a request that returns the object code for a specific set of symbols in a file or module.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please smoke test

**Review by CodaFi — APPROVED** [review]

**Comment by hamishknight** [comment]
@swift-ci please smoke test

**Comment by hamishknight** [comment]
@swift-ci please smoke test

**Comment by hamishknight** [comment]
Superseded by https://github.com/apple/swift/pull/33954

**Pull request closed without merging**
