### PR TITLE
[5.5]ModuleInterface: pass down -disable-availability-checking to module building command

### PR DESCRIPTION
**Pull request by nkcsgexi**
Related to: rdar://80703470

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Comment by xymus** [comment]
Using this setting would consider everything to be available instead of everything being unavailable right? I believe Karoy warned against using this for unsupported platforms. @lorentey what do you think?

**Comment by nkcsgexi** [comment]
@xymus This plan is to allow this flag as a temporary workaround for build issues due to availability checking. We should drop `-disable-availability-checking` for interface verification phase for the library authors for sure.

**Review by xymus — APPROVED** [review]
We should revert this workaround as soon as possible but it should allow the broken swiftinterfaces to build for now.

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Comment by lorentey** [comment]
> Using this setting would consider everything to be available instead of everything being unavailable right? I believe Karoy warned against using this for unsupported platforms. @lorentey what do you think?

I think my context was the special module generation runs that allow some frameworks to remain importable on 32-bit iOS archs (armv7[s], i386). Some projects have started using `-disable-availability-checking` to silence (real, but irrelevant) availability issues within their (opaque) function implementations, so that they have an easier time generating these compatibility swiftinterfaces.

(My worry was that this popularizing this setting could lead to it getting applied in places where it shouldn't be. Also, properly configuring projects to only apply this setting while emitting 32-bit modules proved surprisingly tricky -- our initial attempt accidentally disabled these checks in some watchOS configurations, too. 🙈)

However, the .swiftinterfaces generated this way are still (supposed to be) valid, so afaik it's not strictly necessary to disable availability checking while loading them. On the other hand, I don't see an issue with allowing an explicit `-disable-availability-checking` flag to also apply to interface loading. (Especially if we intend to revert it before 5.5 is finalized.)

**Review by tkremenek — APPROVED** [review]

**Pull request merged**
