### PR TITLE
[APIDigester] Build the API digester as a frontend tool instead of a standalone executable

### PR DESCRIPTION
**Pull request by owenv**
This reduces the install size of the toolchain by around 10% depending on the platform and configuration. Because the api digester now has virtually no size overhead, I moved it from the `toolchain-tools` component to `compiler`. If there's a reason to continue excluding it from some toolchains I can revert that change though.

For now, api-digester still uses llvm::cl based option parsing, but I'd like to migrate it to use the frontend option tables eventually for consistency with the other tools. There's also probably some opportunities to refactor code out of swift_api_digester_main.cpp, I haven't looked into that too much yet.

### CODE REVIEW

**Comment by owenv** [comment]
@swift-ci please smoke test

**Comment by owenv** [comment]
@swift-ci please smoke test

**Comment by owenv** [comment]
@swift-ci please smoke test macOS

**Comment by owenv** [comment]
@swift-ci please smoke test Linux

**Comment by owenv** [comment]
Hmm, these lldb failures seem unrelated

**Comment by nkcsgexi** [comment]
This is a great idea, Thanks, @owenv !

**Comment by owenv** [comment]
@swift-ci please smoke test

**Comment by owenv** [comment]
@swift-ci please build toolchain

**Comment by owenv** [comment]
@swift-ci please build toolchain macOS

**Comment by owenv** [comment]
@swift-ci please build toolchain macOS

**Comment by owenv** [comment]
I think the watchOS failure is fixed now

@swift-ci please build toolchain macOS

**Comment by owenv** [comment]
I tried the toolchain out locally and everything seemed to be working. I think this is good to go now, as long as it's ok to keep the FrameworkABIBaseline data in the toolchain-tools component, which I don't expect to cause any problems

**Review by nkcsgexi — APPROVED** [review]

**Comment by owenv** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
