### PR TITLE
[PrintAsObjC] Separate out module contents printing too

### PR DESCRIPTION
**Pull request by jrose-apple**
The top-level PrintAsObjC now just covers import printing and the near-literal prologue/epilogue text, while the decl printing (and import collecting) is in its own file. No functionality change.

(Previously: #27163)

### CODE REVIEW

**Comment by jrose-apple** [comment]
Note: The PrintAsObjC.cpp diff is easier to read if you ignore whitespace changes.

@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Review by varungandhi-apple — APPROVED** [review]
I'm slightly surprised at the line count difference -- eyeballing the changes would've made me think it overall adds <50 lines, but there is a net +82 lines.

**Review by harlanhaskins — APPROVED** [review]

**Comment by jrose-apple** [comment]
> I'm slightly surprised at the line count difference -- eyeballing the changes would've made me think it overall adds <50 lines, but there is a net +82 lines.

Some lines were changed to ~protect the innocent~ adjust to the new interface. I think that accounts for it.

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test macOS

**Pull request merged**
