### PR TITLE
Fix Issue #63291 by aligning error messages for failure to infer generic parameter and opaque result type.

### LINKED ISSUE #63291: Error messages for failure to infer generic parameter and opaque result type should be aligned
**Description**

Consider these two errors:
```swift
func f1<T>() -> T { fatalError() }
f1() // error: generic parameter 'T' could not be inferred

func f2() -> Optional<some Sequence> { 
  return nil // error: cannot infer underlying type for opaque result 'Optional<some P>' from return expression
}
```

Interestingly, the *second error* is a tailored version of the first, because the underlying type of an opaque result type is in fact a generic parameter of the implicit opaque result type declaration. So these errors are fundamentally one and the same, but the difference in their phrasings is hardly enlightening in this respect. A wording for the *second error* that is more similar to that of the much more familiar *first error* would facilitate [our efforts in presenting this feature as an extension of the generics system](https://docs.swift.org/swift-book/LanguageGuide/OpaqueTypes.html#ID614). For example, `underlying type for opaque result type '...' could not be inferred from return expression`.

### PR DESCRIPTION
**Pull request by Rajveer100**
Aligned the errors messages caused by failure to inferring generic parameter and opaque result type, by changing the messages appropriately in the `include/swift/AST/DiagnosticsSema.def` file, as well as the tests file `test/type/opaque.swift` and `test/type/opaque_return_named.swift`.

Resolves #63291.

### CODE REVIEW

**Review by AnthonyLatsis — APPROVED** [review]
Thanks! 

I can only nitpick about the format of the commit message:
* Because you’re modifying sources to fix an issue, and not just e.g. modifying/adding a test case, reserve the commit title for the brief description of your changes and use the body to link out to the issue instead.
* Use the imperative mood: "fix" rather than "fixed" or "fixes"
* A "Sema" tag/prefix would be nice.

**Comment by Rajveer100** [comment]
> Thanks!
> 
> I can only nitpick about the format of the commit message:
> 
> * Because you’re modifying sources to fix an issue, and not just e.g. modifying/adding a test case, reserve the commit title for the brief description of your changes and use the body to link out to the issue instead.
> * Use the imperative mood: "fix" rather than "fixed" or "fixes"
> * A "Sema" tag/prefix would be nice.

Will make sure next time!

**Comment by AnthonyLatsis** [comment]
At the risk of stating the obvious, you can still make amendments now if you wish to, with `git commit --amend`!

**Comment by AnthonyLatsis** [comment]
The commit history isn’t looking good. Please use separate branches for independent bug fixes, or else the pull request associated with the branch will pick up unrelated commits like what just happened here.

**Comment by Rajveer100** [comment]
Made the changes!

**Comment by Rajveer100** [comment]
I am opening a new pull request to spoil commit history on this one...

**Comment by ahoppen** [comment]
You can continue to use this pull request if you delete commits from your history and force push your branch. Since you are the only one who is working on your branch, force push is totally OK.

**Comment by Rajveer100** [comment]
Apologise for the previous errors, please refer #63567.

**Comment by Rajveer100** [comment]
> You can continue to use this pull request if you delete commits from your history and force push your branch. Since you are the only one who is working on your branch, force push is totally OK.

Actually I wanted to keep everything clean, and also renamed my branch to match the issue number for better clarity and due to that I deleted this branch, which closed the pull request.

**Comment by AnthonyLatsis** [comment]
For posterity, the branch name is not important. Renaming a branch is not worth the lost pull request and the additional burden on future readers due to code review partitioning and duplicate search results. What really matters is a clear description of the changes in both the pull request and commit messages, since that is what people will be looking at for clarifications.

**Comment by Rajveer100** [comment]
I will ensure to not repeat the same @AnthonyLatsis.

**Pull request closed without merging**
