### PR TITLE
[AutoDiff] Add `Differentiable.zeroTangentVectorInitializer`.

### PR DESCRIPTION
**Pull request by dan-zheng**
The `Differentiable.zeroTangentVectorInitializer` requirement will enable
correct, efficient differentiation of struct property and tuple element accesses.

A `zeroTangentVectorInitializer` closure is more efficient than a
`zeroTangentVector` computed property, which would always capture `self`.

Add `Differentiable.zeroTangentVector` default instance property, which
returns `self.zeroTangentVectorInitializer()`.

Todos:
- Implement derived conformances for `zeroTangentVectorInitializer`.
- Implement differentiation transform support for
  `zeroTangentVectorInitializer` and struct/tuple projection instructions.

---

Mirror of https://github.com/apple/swift/pull/28310 (with minor edits), which was merged but became lost in the
`tensorflow` branch commit history for some reason.

### CODE REVIEW

**Comment by dan-zheng** [comment]
I didn't add any tests for now because I don't think there's anything meaningful to test yet.

**Review by marcrasi — APPROVED** [review]

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by rxwei** [comment]
> The `Differentiable.zeroTangentVectorInitializer` requirement will enable
> correct, efficient reverse-mode differentiation of struct property accesses.

Also for forward-mode, because JVP should return a differential that does not capture unnecessary information from the original code.


> * Implement differentiation transform support for
>   `zeroTangentVectorInitializer` and struct/tuple projection instructions.

My earlier work in progress can be found here: https://github.com/rxwei/swift/commit/936791e8ac6e6151c9ed378ca5b1032fb2f0b0bc.

**Review by rxwei — APPROVED** [review]

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow linux

**Comment by dan-zheng** [comment]
I'll merge after filing issues for todos (`zeroTangentVectorInitializer` derived conformances and transform support).

**Pull request merged**
