### PR TITLE
[5.10][ASTGen] Move regex literal parsing from SwiftCompilerSources to ASTGen

### PR DESCRIPTION
**Pull request by rintaro**
Cherry-pick https://github.com/apple/swift/pull/69838 and https://github.com/apple/swift/pull/69930 into `release/5.10`

* **Explanation**: Support regular expression literal in Windows. `ASTGen` always builds with the host Swift compiler, without requiring bootstrapping, and is enabled in more places. Move the regex literal parsing logic there so it is enabled in more host environments including Windows, and makes use of CMake's Swift support. Also this includes an important CMake fix for Windows; previously, `swift-frontend` wasn't linked with `swiftrt.obj`, that may caused numerous unexpected issues.
* **Scope**: Regex literal parsing
* **Risk**: Mid. This also changes the build mechanism of the regex literal parsing logic in other platforms. But that mechanism is well established and tested with Macros support.
* **Testing**: Enabled all of the regex literal tests when `ASTGen` is built, to ensure everything is working.
* **Issues**: rdar://118534766
* **Reviewers**: Doug Gregor (@DougGregor), Hamish Knight (@hamishknight)

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by rintaro** [comment]
@swift-ci Please Build Toolchain

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by rintaro** [comment]
@swift-ci Please Build Toolchain

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by rintaro** [comment]
@swift-ci Please Build Toolchain

**Comment by rintaro** [comment]
@swift-ci Please test

**Review by bnbarham — APPROVED** [review]

**Pull request merged**
