### PR TITLE
Fixes for CI failures

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by dcci** [comment]
I think this one can be reverted now that my patch to fix went in, I'll take a look.

**Comment by dcci** [comment]
(at least, part of this)

**Comment by jckarter** [comment]
Thanks @slavapestov! Did we stop testing 32-bit slices in CI? Surprised PR testing didn't catch this…

**Pull request merged**
