### PR TITLE
[Sema] Uninhabited stored property downgrade to warning

### PR DESCRIPTION
**Pull request by Azoy**
Refer to here: https://github.com/apple/swift/pull/19992#issuecomment-433492051

cc: @jrose-apple @jckarter

### CODE REVIEW

**Comment by jrose-apple** [comment]
Hm. Upon reading these, I don't think the "Void" warning is necessarily a good idea, because it doesn't say *why* it's a bad idea to have, e.g., Empty as a type. Maybe we could replace the "which may be unexpected" with the "which is an enum with no cases" / "which contains an enum that has no cases"?

@jckarter, what do you think?

**Comment by jrose-apple** [comment]
(Thanks, Alejandro.)

**Comment by jckarter** [comment]
That seems like a clearer explanation, sure. Hotever, note that this would typically be paired with the "is never executed" warning about any following statements using the variable, which ought to help clarify why there's an issue.

**Comment by Azoy** [comment]
@jrose-apple does this look better?

**Comment by Azoy** [comment]
@jckarter are the bots broken?

**Comment by jckarter** [comment]
The failures certainly don't look related to this change. I'll follow up. Meanwhile, we can try a smoke test.

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Comment by Azoy** [comment]
@jckarter I think the bots are functional once again. Can you kick off again?

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Comment by Azoy** [comment]
@jckarter @xwu @jrose-apple is this ready for merge?

**Comment by jrose-apple** [comment]
LGTM. @jckarter, any further comments?

**Comment by jckarter** [comment]
Looks good. Thanks @Azoy!

**Pull request merged**
