### PR TITLE
Requestify memberwise and default initializer synthesis

### PR DESCRIPTION
**Pull request by hamishknight**
This PR introduces requests to check whether a decl needs a memberwise or default initializer, synthesizing them if needed. It also introduces requests for a couple of intermediate computations.

This allows us to get rid of `addImplicitConstructorsToStruct` and leave `addImplicitConstructorsToClass` with the task of synthesizing just the inherited initializers for now. Currently, this PR just forces the default and memberwise initializers in `addImplicitConstructors`, but this can become more lazy once we fully get rid of `addImplicitConstructors`.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test OS X platform

**Comment by hamishknight** [comment]
@swift-ci please test OS X platform

**Review by slavapestov — APPROVED** [review]
Great job!

**Comment by hamishknight** [comment]
@swift-ci please smoke test OS X platform

**Comment by hamishknight** [comment]
@swift-ci please test OS X platform

**Pull request merged**
