### PR TITLE
SE-0110 tuple splatting should not implode argument list with varargs

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes https://bugs.swift.org/browse/SR-9470.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
Gah. I switched from emacs to visual studio code recently and it doesn’t always add that trailing newline. I’ll dig around in the settings to see if it can do it automatically.

**Comment by rudkx** [comment]
I made the same switch last week and yes there is a setting. :)

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Pull request merged**
