### PR TITLE
[SE-0025][SR-1275] fileprivate [1/2]

### PR DESCRIPTION
**Pull request by CodaFi**
#### What's in this pull request?

Implements the `fileprivate` access level described in SE-0025.
#### Resolved bug number: ([SR-1275](https://bugs.swift.org/browse/SR-1275))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by CodaFi** [comment]
I apologize for the *enormous* batch of changes here.  But most of it is plumbing through the new shiny.

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by CodaFi** [comment]
Not sure what to do about the tests here.  This is going to require submissions to SwiftPM and Foundation to migrate them to fileprivate and fix the build.

**Comment by ddunbar** [comment]
Would it make sense to add `fileprivate` as a synonym for `private`, so that we can stage in the changes to other projects?

**Comment by modocache** [comment]
@ddunbar How would we disambiguate between `fileprivate` and `private`?

**Comment by CodaFi** [comment]
The migration path here is all existing uses of `private` become `fileprivate`, so it should be a find-and-replace job to get most things to compile (if at all).

**Comment by gribozavr** [comment]
@modocache If I understood correctly, the suggestion is that we introduce just the syntax in the first patch, thus avoiding the need for lockstep changes.

**Comment by CodaFi** [comment]
That seems like a trivial change I could make to this patch.  Give me a moment.

**Comment by CodaFi** [comment]
OK, the two keywords now temporarily point to the same accessibility constraint.

**Comment by ddunbar** [comment]
@swift-ci please test

**Comment by CodaFi** [comment]
Once more with feeling.

**Comment by harlanhaskins** [comment]
@swift-ci please test

**Comment by harlanhaskins** [comment]
@swift-ci please test

**Comment by CodaFi** [comment]
OK, we've finished staging the corelibs changes for this patch (thanks @modocache for doing corelibs-XCTest).  Should be smooth sailing.

**Comment by modocache** [comment]
Looks like this branch could use a rebase.

Just curious: what's the plan for merging this? Are we waiting on something, or is this good to go?

**Comment by jrose-apple** [comment]
@CodaFi found a problem in the proposal and we need to discuss it first.

**Comment by CodaFi** [comment]
This is now subsumed by #3391

**Pull request closed without merging**
