### PR TITLE
[CodeCompletion] Don't generate constraints for parts of a result builder unrelated to the code completion token

### PR DESCRIPTION
**Pull request by ahoppen**
This basically resolves all performance-related problems in `TurnipsView.swift` of the ACHNBrowserUI project in the stress tester, improving average code completion duration from 4 billion instructions to 1 billion instruction in that file.

rdar://90769979 [SR-16056]

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please SourceKit stress test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Review by xedin — COMMENTED** [review]
I suspect that you can add it to the loop in the brace statement instead because that's what drives the transformation.

**Comment by xedin** [comment]
@ahoppen I think you could skip statements entirely (just `continue`) after moving the check to `visitBraceStmt`.

**Comment by xedin** [comment]
Actually no, statements are added to the buildBlock so they’s need a placeholder

**Comment by ahoppen** [comment]
Superseded by https://github.com/apple/swift/pull/59992

**Pull request closed without merging**
