### PR TITLE
Debug info: Avoid emitting module imports twice when access path differs

### PR DESCRIPTION
**Pull request by adrian-prantl**
This fixes a recent regression from 68a5cadb90e.
rdar://problem/32327266

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci smoke test and merge

**Comment by jrose-apple** [comment]
I just ran into this today and @jimingham helped point me to this commit. This is unfortunately still not the correct fix: the "access path" is about looking *within* a module, and does not correspond to submodules. The Swift module for the Clang submodule "Darwin.C" is just named "C".

**Comment by jrose-apple** [comment]
(I will give you that this is not useful, but right now it's actively causing problems for me.)

**Comment by adrian-prantl** [comment]
Not the right fix for which situation specifically? All this commit does is avoid generating an import decl debug info entry for a module that has already been imported (through whichever access path shouldn't matter in this context).

**Comment by jrose-apple** [comment]
It doesn't solve the problem in the linked Radar.

**Comment by adrian-prantl** [comment]
Sorry for being obuste: the linked rdar://problem/32327266 is a about the lldb test failure, and that failure was fixed by this commit. Do you mean rdar://problem/31310320, which is about auto-parent-module-imports not being reflected in the debug info?

**Comment by jrose-apple** [comment]
The linked Radar talks about "Darwin.C" being shown as just "C" in the debug info. This commit doesn't fix that (and I ran into it today, albeit with a different nested module).

**Comment by adrian-prantl** [comment]
It is expected that the module is still called "C", but it is supposed to be nested inside a DW_TAG_module called "Darwin". Could you please send me your testcase? There might be something else going on that I'm missing. From what you are describing, the submodule is created with the wrong parent.

**Comment by adrian-prantl** [comment]
Hmm. What you are describing could happen if there was a *sub*module showing up in the list of imported modules that was not imported by an import statement. Would "import A.B.C" trigger an implicit import of A.B? In any case, I think I have enough to figure this out on my own now :-)
Thanks!

**Pull request merged**
