### PR TITLE
[Unit testing] Fix two testing bugs found by valgrind

### PR DESCRIPTION
**Pull request by davezarzycki**

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Review by mikeash — APPROVED** [review]
Woohoo!

**Comment by davezarzycki** [comment]
@swift-ci please smoke test macOS

**Comment by davezarzycki** [comment]
@swift-ci please smoke test macOS

**Comment by davezarzycki** [comment]
@swift-ci please smoke test linux

**Pull request merged**
