### PR TITLE
[IRGen] Improve function type metadata representation (attempt #2).

### PR DESCRIPTION
**Pull request by xedin**
This brings back all of the previously reverted commits with small change to MetadataReader to make LLDB happy and added test to make sure we do not regress like that again.

Problem with LLDB was related to `MetadataReader`, where my changes in `_readMetadata` to read whole `TargetFunctionTypeMetadata` and use its accessors mistakenly, made it so it attempted to read data from the pointer and then use as pointer when calling `readTypeFroMetadata`, which shouldn't be done because elements of `TargetFunctionTypeMetadata::getParameters` point to direct locations of parameters already.

Resolves: rdar://problem/31408030

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please clean test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by shahmishal** [comment]
@swift-ci please clean test macOS

**Comment by shahmishal** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@shahmishal Thank you!

**Comment by xedin** [comment]
@swift-ci please test macOS

**Pull request merged**
