### PR TITLE
Sr 4067 function declaration syntax

### PR DESCRIPTION
**Pull request by bitjammer**
Implement function-declaration in lib/Syntax. This necessarily forced a bunch of dependencies, like function-signature, function-argument-list, function-argument, etc.

Also implement a generic `SyntaxCollection` for unbounded lists of terms. I converted nodes on which function-declaration depends but there are probably a couple left, which I'll get to in a follow-up. 

Resolves #46650, resolves #46729

### CODE REVIEW

**Comment by bitjammer** [comment]
@swift-ci Please smoke test

**Comment by nkcsgexi** [comment]
Nice! Can we have indexed access to a type repr? For instance, from `(C1, (C2, C3?))->C4`, we can get the `C3` from a given index chain like `0:1:1:0`. This will be useful for migrator.

**Comment by bitjammer** [comment]
That's an interesting idea - can you file an SR on Compiler+Syntax with a C++ interface that you think would be useful, and perhaps some examples?

**Comment by nkcsgexi** [comment]
Sure! https://bugs.swift.org/browse/SR-4148

**Pull request merged**
