### PR TITLE
Disable failing Tensor subscript assignment tests in GPU mode.

### PR DESCRIPTION
**Pull request by bgogul**
This is related to https://bugs.swift.org/browse/TF-469

### CODE REVIEW

**Comment by bgogul** [comment]
@swift-ci please test tensorflow

**Comment by bgogul** [comment]
@eaplatanios, Just FYI.

**Review by rxwei — APPROVED** [review]
I think only the assignment ones are failing, no?

**Comment by eaplatanios** [comment]
@bgogul @rxwei Yes, that is correct. Only the assignment ones fail but `"EllipsisIndexing"` is also using an assignment inside the test so it's ok to either disable that for now or just remove the assignment from inside that test.

I'll try to debug this in the next few days. I think it's an issue with the GPU kernel implementation but haven't had a chance to look at it yet.

**Review by dan-zheng — APPROVED** [review]
Thanks @bgogul!

**Comment by bgogul** [comment]
@eaplatanios FWIW, I investigated this a bit last Friday, but did not make much progress. As far as I ca see, the issue seems to be in the tensorflow implementation and not on our end. @pschuh has seen int32 cause issues with GPU (not GPE) support in tensorflow in the past.

**Pull request merged**
