### PR TITLE
[build] allow to skip build of clang-tools-extras

### PR DESCRIPTION
**Pull request by edymtt**
Also at the same time refactor code that composes LLVM_ENABLE_PROJECTS

Supports rdar://problem/57432088

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci smoketest

**Comment by edymtt** [comment]
@swift-ci please smoketest

**Comment by edymtt** [comment]
@swift-ci Please smoke test

**Review by shahmishal — CHANGES_REQUESTED** [review]
We should also add the flags in https://github.com/apple/swift/blob/master/utils/build_swift/driver_arguments.py and add test for this new flag.

**Comment by edymtt** [comment]
@swift-ci Please smoke test

**Comment by edymtt** [comment]
@swift-ci Please Python lint

**Comment by edymtt** [comment]
@swift-ci Please test Windows platform

**Comment by edymtt** [comment]
Tackled review feedback as part of e5e274333fb4c0b99b4abbf68e082f362c2075ed

For the sake of completeness, all `build_swift` unit tests passes and we have only one unrelated lint failure

```
>  utils/python_lint.py 
./docs/conf.py:16:1: I201 Missing newline between import groups. 'from sphinx.highlighting import lexers' is identified as Third Party and 'from datetime import date' is identified as Stdlib.
> python -m unittest discover -s utils/build_swift -t utils                                                                                     
........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 760 tests in 15.428s

OK
```

**Comment by edymtt** [comment]
@swift-ci Please Python lint

**Comment by edymtt** [comment]
@swift-ci Please test Windows platform

**Comment by edymtt** [comment]
@swift-ci please clean test Windows platform

**Comment by edymtt** [comment]
@swift-ci please clean test Windows platform

**Review by Rostepher — APPROVED** [review]
This looks good to me. Thanks for cleaning this up! 👍

**Comment by CodaFi** [comment]
#28553 addresses the failure here. Thanks!

⛵️

**Pull request merged**
