### PR TITLE
Only use SIMD when stdlib vector types are available

### PR DESCRIPTION
**Pull request by Catfish-Man**

### CODE REVIEW

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Comment by Catfish-Man** [comment]
@swift-ci please benchmark

**Review by kubamracek — APPROVED** [review]

**Review by stephentyrone — APPROVED** [review]

**Comment by Catfish-Man** [comment]
@swift-ci please benchmark

**Comment by Catfish-Man** [comment]
I’m using the benchmark results to triple check that I’m not accidentally disabling SIMD everywhere

**Comment by Catfish-Man** [comment]
@swift-ci please benchmark

**Pull request merged**
