### PR TITLE
[Sema] Always allow public overrides of open methods

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
[SR-10004](https://bugs.swift.org/browse/SR-10004)

cc @xedin

### CODE REVIEW

**Comment by jrose-apple** [comment]
It makes sense in theory, but I worry that some of our other features will get in the way: specifically, dropping overrides if they can't be imported for some reason:

```
open class Base {
  open func foo() -> Any {}
}

open class Sub: Base {
  public override func foo() -> MysteriouslyDisappearingClass {} // covariant override
}
```

```
class GrandSub: Sub {
  override func foo() -> Any {} // not reported as error
}
```

But I guess this is a problem with or without the `public`, and this doesn't really make it worse. (@slavapestov, any additional thoughts?)

@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by AnthonyLatsis** [comment]
> It makes sense in theory, but I worry that some of our other features will get in the way: specifically, dropping overrides if they can't be imported for some reason

I don't understand the potential impact: this change allows public overrides of open methods without having to make them final; you could always make them open, which is less safe.

**Comment by jrose-apple** [comment]
My concern was that if the `public` method can't be imported for whatever reason, but the `open` method it overrides can, then the grand-subclass might think it can override the method when it can't. But that's already a problem.

**Comment by AnthonyLatsis** [comment]
I see, it doesn't matter whether the mysterious method is open or not if it cannot be imported. Thank you for clarifying.

**Pull request merged**
