### PR TITLE
[SE-327] Remove redundant global-actor isolation.

### PR DESCRIPTION
**Pull request by kavon**
As part of SE-327, global-actor isolation applied to
the instance-stored properties of a value type do
not require any isolation, since there is no way to
create a race on access to that storage.

https://github.com/apple/swift-evolution/blob/main/proposals/0327-actor-initializers.md#removing-redundant-isolation

This change turns global-actor annotations on such
properties into an error in Swift 6+, and a warning
in Swift 5 and earlier.

In addition, inference for global-actor isolation
no longer applies global-actor isolation to such
properties. Since this latter change only results
in warnings in existing Swift 5 code, about a now
superflous 'await', this change will happen in
Swift 5+.

Fixes rdar://87568381

### CODE REVIEW

**Comment by kavon** [comment]
@swift-ci please test

**Review by ktoso — APPROVED** [review]
Looks good, nice catch

**Comment by kavon** [comment]
@swift-ci please test and merge

**Comment by atrick** [comment]
For an ordinary stored property, I'm not sure why it's type matters. The property itself is just a value, no matter what its type is. Under what scenario would global-actor isolation be required for the stored property? Why would it make a difference whether it's a reference, existential, or generic type, vs. a struct containing a reference, existential, or generic?

**Comment by kavon** [comment]
> For an ordinary stored property, I'm not sure why it's type matters. The property itself is just a value, no matter what its type is. Under what scenario would global-actor isolation be required for the stored property? Why would it make a difference whether it's a reference, existential, or generic type, vs. a struct containing a reference, existential, or generic?

Great question. This got me thinking and discussing it again with some other folks. The type in which the stored instance property appears in matters, relative to what kinds of instances of the type are allowed to be captured in a Sendable closure. For a struct, we currently have a hard error when trying to capture a mutable `var` in a Sendable closure:

```
@MainActor
struct StatTracker {
  var count = 0

  mutating func update() {
    count += 1
  }
}

var st = StatTracker()
Task { await st.update() } // error: mutation of captured var 'st' in concurrently-executing code
```

As a result, there is no way to concurrently mutate the memory of a struct, _regardless_ of whether the stored properties of the struct are isolated to a global actor. Whether the instance can be shared only depends on whether it's `var`-bound or not, and the only kind of sharing permitted is via copying.

Things are different for classes, since the class must conform to `Sendable`. We automatically infer that a class is `Sendable` if the entire class is isolated to a global-actor. So the same instance of a class can be shared among multiple tasks. If we were to then drop the MainActor isolation from that class's stored properties, then unsynchronized concurrent accesses of those properties are possible. In fact, the reason why we could infer that the class is `Sendable` is _because_ its stored properties are protected by actor isolation.

If we knew statically that the class is not Sendable _and_ capturing it in a sendable closure were an error (and not just a warning), then we could also drop the protection on the stored properties of a class, too. But in Swift 5.5 we require the `-warn-concurrency` flag to even get a warning about `MyClass` being non-Sendable in this program:

```
class MyClass {
  var count = 0
}

func test(c: MyClass) {
  Task { print(c.count) }
}
```

**Comment by kavon** [comment]
@swift-ci please test

**Comment by kavon** [comment]
@swift-ci please test and merge

**Review by DougGregor — APPROVED** [review]

**Comment by kavon** [comment]
@swift-ci please test and merge

**Comment by kavon** [comment]
@swift-ci please test and merge

**Comment by kavon** [comment]
@swift-ci please test and merge

**Pull request merged**
