### PR TITLE
[build-script] Update the default CLANG_USER_VISIBLE_VERSION to 6.0.0

### PR DESCRIPTION
**Pull request by bob-wilson**
The swift-4.2-branch of Clang/LLVM is derived from LLVM 6.0. Set the
default Clang version to match.

rdar://problem/39960908

### CODE REVIEW

**Comment by bob-wilson** [comment]
@swift-ci please test

**Comment by gottesmm** [comment]
test?

**Comment by bob-wilson** [comment]
I don't know. What do you think should be tested here?

**Comment by gottesmm** [comment]
Actually I just saw you were touching the build system, but there weren't any tests. What is key here is that you are modifying the "input data" to the system, rather than how the information flows through it (where you would want a test). I double checked that we already have such coverage. Sorry for the noise!

Also, the linux failure is: https://bugs.swift.org/browse/SR-7589

**Comment by bob-wilson** [comment]
@swift-ci please test

**Pull request merged**
