### PR TITLE
[TypeChecker] Re-work type-checking of string interpolations

### PR DESCRIPTION
**Pull request by xedin**
Type-check tap expressions the same way as we do closures. As soon as tap 
expression gets a (contextual) type assigned - generate constraints for its
body (using conjunction constraint for incremental solving) and apply solution to
the body inline instead of using `typeCheckTapBody`.

### CODE REVIEW

**Comment by xedin** [comment]
This is still a draft because I need to to work out a few issues when string interpolations are used in closures (conjunction could get disconnected from the rest of the constraint system).

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@ahoppen Looks like the only thing that is left here are IDE work, would you mind looking into that when you have a chance?

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please SourceKit stress test

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by ahoppen** [comment]
@swift-ci Please smoke test macOS

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci Please smoke test macOS

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Comment by xedin** [comment]
Closing in favor of https://github.com/apple/swift/pull/63717

**Pull request closed without merging**
