### PR TITLE
Add test that catches (currently fixed) regression - SR-9837

### PR DESCRIPTION
**Pull request by mattpolzin**
I added a test that targets a regression I found in a Swift 5 nightly build a while ago. The regression has been fixed, but this test case would catch it in the future.

The regression, as explained in SR-9837, has to do with properly casting `Optional.none` in a generic context.

Resolves [SR-9837](https://bugs.swift.org/browse/SR-9837).

### CODE REVIEW

**Review by mikeash — APPROVED** [review]

**Comment by mikeash** [comment]
Thanks for adding this. I'll kick off the PR test and then we can get this merged.

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mattpolzin** [comment]
Should I cherry pick and open a PR against Swift-5.0-branch as well?

**Comment by mikeash** [comment]
@swift-ci please test os x platform

**Comment by mikeash** [comment]
There's a really high bar for getting changes into the 5.0 branch now. While this change is clearly harmless, I don't think it's quite worth it. We did, however, just open up a 5.1 branch. Once we satisfy PR testing here, I think it would be good to cherry-pick it onto 5.1.

**Comment by mattpolzin** [comment]
Is this ready to go? Not trying to be a bother, I know everyone is busy and this is a pretty low-prio PR.

**Comment by mikeash** [comment]
No bother at all! I appreciate the reminder. I'm going to click the merge button right now. On further reflection, I don't think we need to worry about the 5.1 branch, as we'll re-branch it at some point and this test doesn't need to be in there right away.

Thanks again, more tests for real problems always makes me happy.

**Pull request merged**
