### PR TITLE
Separate symbol graph files for extended modules

### PR DESCRIPTION
**Pull request by bitjammer**
Serialize symbol graphs for extended modules separately
    
When a module extends a type from another module, serialize those symbols into separated files dedicated to those extended modules. This makes it easier to ingest and categorize those symbols under the extended module if desired.
    
rdar://58941718

### CODE REVIEW

**Comment by bitjammer** [comment]
@swift-ci Please smoke test

**Comment by bitjammer** [comment]
@swift-ci Please test Windows platform

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by bitjammer** [comment]
What?

**Comment by bitjammer** [comment]
@swift-ci Please smoke test

**Comment by bitjammer** [comment]
@swift-ci Please test Windows platform

**Comment by bitjammer** [comment]
Spurious error. Will wait until LLVM merge is done and rebase before merging.

**Comment by bitjammer** [comment]
@swift-ci Please smoke test

**Comment by bitjammer** [comment]
@swift-ci Please test Windows platform

**Comment by bitjammer** [comment]
@swift-ci Please smoke test

**Comment by bitjammer** [comment]
@swift-ci Please test Windows platform

**Comment by bitjammer** [comment]
@swift-ci Please test Windows platform

**Pull request merged**
