### PR TITLE
Enable string processing by default.

### PR DESCRIPTION
**Pull request by rxwei**
Enable string processing by default once it goes through Swift Evolution.

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test

**Comment by rxwei** [comment]
@swift-ci please test

**Comment by rxwei** [comment]
@swift-ci please test

**Review by milseman — APPROVED** [review]

**Comment by rxwei** [comment]
@swift-ci please test

**Comment by rxwei** [comment]
apple/swift-driver#1112
@swift-ci please test

**Comment by rxwei** [comment]
apple/swift-driver#1112
@swift-ci please test macOS

**Comment by rxwei** [comment]
apple/swift-driver#1112
@swift-ci please test

**Pull request merged**
