### PR TITLE
Revert

### PR DESCRIPTION
**Pull request by adrian-prantl**
This reverts commit 0aea1c0528ae7667e4af494ac0de7ded3865533d while investigating bot breakage.

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@gottesmm ^

**Comment by gottesmm** [comment]
@shahmishal ^

**Comment by shahmishal** [comment]
Merged to unblock CI

**Pull request merged**
