### PR TITLE
SIL: Remove consumption kind from unconditional casts. (this causes some over-releases, I'll debug it as soon as I can)

### PR DESCRIPTION
**Pull request by atrick**

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
@swift-ci test.

**Comment by rjmccall** [comment]
I'm sure this test was just using @in/@out as a convenient way to get an address value and wasn't really claiming to be correct about it.

**Pull request merged**
