### PR TITLE
Sema: Don’t use ‘.’ in symbol names of synthesized properties

### PR DESCRIPTION
**Pull request by eeckstein**
Instead use ‘$’.

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci Please smoke test

**Comment by eeckstein** [comment]
@jckarter Can you please review this?

**Comment by jrose-apple** [comment]
This is no good, `$` is a valid identifier character.

**Comment by jrose-apple** [comment]
What's prompting this? Problems with mangling? Problems with the SIL parser?

**Comment by jckarter** [comment]
`$` isn't a valid Swift identifier character. The problem was that the `.` was leaking into mangled symbol names, and so far we've been trying to keep mangled symbols restricted to the commonly-supported `[A-Za-z0-9_$]` character set.

**Comment by jckarter** [comment]
@eeckstein I do think though that it'd be better to mangle unexpected characters like `.` by mapping them to `$` in the mangling rather than changing the AST names. It is useful to synthesize AST nodes with impossible identifiers for names.

**Comment by rintaro** [comment]
Since https://github.com/apple/swift/pull/5270
We can
```swift
let `$storage` = 1
print(`$storage`)
```

**Comment by jckarter** [comment]
I don't think we ever allowed `$` as anything other than the first character, though.

**Comment by rintaro** [comment]
`$` in middle of identifiers is allowed even in Swift3.0, even without backticks.
```swift
let foo$storage = 1
print(foo$storage)
```

**Comment by jckarter** [comment]
Well, that's arguably a bug we should fix (for future Swift versions) in line with #5270.

**Comment by jrose-apple** [comment]
:-/ Perhaps. I wish we had a good way to search for that one first.

(We could also do some kind of silly substitution, like `$ -> $$`, `. -> $`.)

**Comment by jckarter** [comment]
Alternatively, we could treat `.` and all other nonstandard identifier characters as if they were Unicode code units and Punycode them out-of-band. That would also allow us to accept arbitrary strings in a backtick-quoted identifier, if we wanted to…

**Comment by eeckstein** [comment]
ok, no problem, I'll handle it in the mangling

**Pull request closed without merging**
