### PR TITLE
[benchmark] Hook up CSVParsing to suite

### PR DESCRIPTION
**Pull request by milseman**
Hook up https://github.com/apple/swift/pull/13721

### CODE REVIEW

**Comment by milseman** [comment]
@chriseidhof This connects the benchmark to the suite.

Do you think you can also add the parseAlt approach? Again, that can just be as a flat source-code splat if you like, or hooked up the way this is. For an example of benchmarks with variants, see: https://github.com/apple/swift/blob/master/benchmark/single-source/CString.swift

**Comment by milseman** [comment]
@swift-ci please smoke test

**Comment by milseman** [comment]
@swift-ci please smoke benchmark

**Review by airspeedswift — COMMENTED** [review]
LGTM, only question is do we really want the inline(always) in code we're benchmarking?

**Comment by milseman** [comment]
It runs faster without it anyways. Will push

**Comment by milseman** [comment]
@swift-ci please smoke test and merge

**Comment by milseman** [comment]
@swift-ci please smoke test

**Comment by milseman** [comment]
@swift-ci please smoke test Linux Platform

**Comment by milseman** [comment]
@swift-ci please smoke test Linux Platform

**Pull request merged**
