### PR TITLE
Fix typo in ModuleAnalyzerNodes.h

### PR DESCRIPTION
**Pull request by eltociear**
propery ->property

### CODE REVIEW

**Review by LucianoPAlmeida — APPROVED** [review]

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test Windows Platform

**Comment by CodaFi** [comment]
Cool! Thanks y'all.

⛵

**Comment by eltociear** [comment]
@CodaFi Thanks review!!

**Pull request merged**
