### PR TITLE
Sink address projections in ArrayPropertyOpt and enable verification to ensure we have no address phis

### PR DESCRIPTION
**Pull request by meg-gupta**
ArrayPropertyOpt is the last pass left that generates address phis. Sink address projections by cloning to avoid address phis. Turn on verification to ensure there are no address phis in non-OSSA SIL as well.

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci test Linux Platform

**Comment by meg-gupta** [comment]
@swift-ci test Linux Platform

**Comment by meg-gupta** [comment]
@swift-ci test Windows Platform

**Comment by meg-gupta** [comment]
@swift-ci test source compatibility

**Comment by meg-gupta** [comment]
@swift-ci test macOS platform

**Comment by meg-gupta** [comment]
@swift-ci test

**Review by atrick — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
