### PR TITLE
[6.0] SE-0425 implementation

### PR DESCRIPTION
**Pull request by stephentyrone**
Implement [U]Int128 for Swift 6.0

**- Explanation:** Implements [U]Int128 according to SE-0425.
**- Scope:** Introduces two new types with Swift 6.0 availability, together with new protocol requirements on encoder/decoder implementations.
**- Issue:** https://github.com/apple/swift-evolution/blob/main/proposals/0425-int128.md
**- Original PR:** https://github.com/apple/swift/pull/72139
**- Risk:** Low. The risk primarily comes from changes to encoders and decoders and to Atomic; otherwise we are only introducing a new type and the API to support it, which should not effect existing code.
**- Testing:** New tests added to the swift test suite.
**- Reviewer:** @lorentey, @Azoy 

Resolves rdar://122958984

### CODE REVIEW

**Comment by stephentyrone** [comment]
@swift-ci test

**Comment by stephentyrone** [comment]
@swift-ci test

**Review by DougGregor — APPROVED** [review]

**Comment by stephentyrone** [comment]
@swift-ci test

**Comment by stephentyrone** [comment]
@swift-ci test source compatibility

**Comment by stephentyrone** [comment]
@swift-ci test

**Comment by stephentyrone** [comment]
@swift-ci test source compatibility

**Pull request merged**
