### PR TITLE
[Archetype builder] Improve handling of archetype anchors

### PR DESCRIPTION
**Pull request by DougGregor**
Handle archetype anchors more consistently:

* *Never* rely on the representative as an anchor, because the
representative is order-sensitive and arbitrary.
* Once we do select an anchor, make sure that it's no worse than any
other potential archetype in that equivalence class.
* Always use the archetype anchor as the first type when enumerating
the requirements of types, not the representative.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@huonw , I think you might be interested in this!

**Comment by slavapestov** [comment]
This also helps us with correctness for the SubstitutionMap's parentMap stuff...

**Comment by DougGregor** [comment]
Hmm... I think making this work is tied up with getting all of the same-named associated types in the equivalence class.

**Comment by DougGregor** [comment]
I landed this via a separate PR, https://github.com/apple/swift/pull/6760

**Pull request closed without merging**
