### PR TITLE
[5.5] Conform Never to Identifiable

### PR DESCRIPTION
**Pull request by kylemacomber**
Cherry pick of #38103

rdar://75988520

Incorporating into branch as part of evolution review discussion. This can be reverted if the Core team decides to not accept this change.

### CODE REVIEW

**Comment by kylemacomber** [comment]
@swift-ci please test

**Comment by kylemacomber** [comment]
@swift-ci please test

**Review by lorentey — APPROVED** [review]

**Comment by kylemacomber** [comment]
@swift-ci please test macOS platform

**Comment by kylemacomber** [comment]
@swift-ci please test Windows platform

**Review by tkremenek — APPROVED** [review]

**Pull request merged**
