### PR TITLE
IDE: avoid merging extensions with @available attributes when synthesizing extensions

### PR DESCRIPTION
**Pull request by nkcsgexi**
rdar://54804607

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by jrose-apple** [comment]
Strictly speaking you could merge extensions with the same availability, but otherwise good point.

**Comment by nkcsgexi** [comment]
@jrose-apple That's right. We'd like to land this safe fix for the swift-5.1-branch to avoid omitting availability information. Mind reviewing it for swift-5.1-branch?

**Comment by jrose-apple** [comment]
Does seem strictly better than what was there before, with almost zero risk.

**Review by jrose-apple — APPROVED** [review]

**Pull request merged**
