### PR TITLE
 [Refactoring] Disallow several kinds of decl to move to extension

### PR DESCRIPTION
**Pull request by rintaro**
* `AccessorDecl` and `EnumElementDecl` aren't independent decls
* `DestructorDecl` and `EnumCaseDecl` can't be put in extension

rdar://problem/40274500

Also, simplified the implementation.

### CODE REVIEW

**Comment by rintaro** [comment]
CC @ahoppen as the original author of this action.

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Review by ahoppen — APPROVED** [review]
Thanks. Looks good to me. I didn't know about `Info.RangeContext`. 

Interesting though that a var decl doesn't start a new decl context for its accessors.

**Review by nkcsgexi — APPROVED** [review]
LGTM! This refactoring could really be implemented using libSyntax API :)

**Pull request merged**
