### PR TITLE
SR-13742: Remove diagnostic preventing case [Int] which actually works

### PR DESCRIPTION
**Pull request by ktoso**
Resolves https://bugs.swift.org/browse/SR-13742

The diagnostic is not necessary because this type of pattern match just works nowadays already.

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
Could we get SIL, IR, and runtime tests for this as well?

**Comment by ktoso** [comment]
Yes happy too -- I'm a bit new to the compiler, could you point me at where would be the right spot to add those?

**Comment by CodaFi** [comment]
The SIL tests can go into `test/SILGen/`, the IR ones in `test/IRGen`, and you can write your own executable tests and stick them under `test/Interpreter`.

**Comment by ktoso** [comment]
Thanks, will do!

**Comment by ktoso** [comment]
Okey to it seems this actually needs some actual work, not just the warning removal 🤔 

When working on adding tests:

```
Assertion failed: (hasType()), function getType, file /Users/ktoso/code/swift-project/swift/lib/AST/Pattern.cpp, line 115.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /Users/ktoso/code/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-x86_64/bin/swift-frontend -target x86_64-apple-macosx10.9 -module-cache-path /Users/ktoso/code/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-x86_64/swift-test-results/x86_64-apple-macosx10.9/clang-module-cache -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -swift-version 4 -ignore-module-source-info -typo-correction-limit 10 -emit-silgen -verify-syntax-tree -module-name switch /Users/ktoso/code/swift-project/swift/test/SILGen/switch.swift
1.	Swift version 5.3-dev (LLVM 2ea629d94ab01c3, Swift 70c90e4cd6addc2)
2.	While evaluating request ASTLoweringRequest(Lowering AST to SIL for module switch)
3.	While silgen emitFunction SIL function "@$s6switch14test_isa_array2psySayAA1P_pG_tF".
 for 'test_isa_array(ps:)' (at /Users/ktoso/code/swift-project/swift/test/SILGen/switch.swift:639:1)
0  swift-frontend           0x000000010cd1f295 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 37
1  swift-frontend           0x000000010cd1e565 llvm::sys::RunSignalHandlers() + 85
2  swift-frontend           0x000000010cd1f866 SignalHandler(int) + 262
3  libsystem_platform.dylib 0x00007fff204b2d7d _sigtramp + 29
4  libdyld.dylib            0x00007fff204883e3 dyldGlobalLockRelease() + 0
5  libsystem_c.dylib        0x00007fff203c0720 abort + 120
6  libsystem_c.dylib        0x00007fff203bf9d6 err + 0
7  swift-frontend           0x000000010d29b461 swift::Pattern::getType() const (.cold.1) + 33
8  swift-frontend           0x00000001098efcaa swift::Pattern::getType() const + 442
9  swift-frontend           0x0000000108b5ebcc (anonymous namespace)::PatternMatchEmission::emitSpecializedDispatch((anonymous namespace)::ClauseMatrix&, llvm::ArrayRef<swift::Lowering::ConsumableManagedValue>, unsigned int&, unsigned int, std::__1::function<void (swift::SILLocation)> const&) + 972
10 swift-frontend           0x0000000108b5b54e (anonymous namespace)::PatternMatchEmission::emitDispatch((anonymous namespace)::ClauseMatrix&, llvm::ArrayRef<swift::Lowering::ConsumableManagedValue>, std::__1::function<void (swift::SILLocation)> const&) + 2142
11 swift-frontend           0x0000000108b5a59a swift::Lowering::SILGenFunction::emitSwitchStmt(swift::SwitchStmt*) + 4154
12 swift-frontend           0x0000000108b8d246 (anonymous namespace)::StmtEmitter::visitBraceStmt(swift::BraceStmt*) + 326
13 swift-frontend           0x0000000108b87715 swift::Lowering::SILGenFunction::emitStmt(swift::Stmt*) + 21
14 swift-frontend           0x0000000108b3483c swift::Lowering::SILGenFunction::emitFunction(swift::FuncDecl*) + 348
15 swift-frontend           0x0000000108aa7f6e swift::Lowering::SILGenModule::emitFunctionDefinition(swift::SILDeclRef, swift::SILFunction*) + 5566
16 swift-frontend           0x0000000108aa9bf4 emitOrDelayFunction(swift::Lowering::SILGenModule&, swift::SILDeclRef, bool) + 228
17 swift-frontend           0x0000000108aa699a swift::Lowering::SILGenModule::emitFunction(swift::FuncDecl*) + 122
18 swift-frontend           0x0000000108aac0d7 swift::ASTLoweringRequest::evaluate(swift::Evaluator&, swift::ASTLoweringDescriptor) const + 1943
19 swift-frontend           0x0000000108b87210 swift::SimpleRequest<swift::ASTLoweringRequest, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule> > (swift::ASTLoweringDescriptor), (swift::RequestFlags)9>::evaluateRequest(swift::ASTLoweringRequest const&, swift::Evaluator&) + 128
20 swift-frontend           0x0000000108ab0eb1 llvm::Expected<swift::ASTLoweringRequest::OutputType> swift::Evaluator::getResultUncached<swift::ASTLoweringRequest>(swift::ASTLoweringRequest const&) + 497
21 swift-frontend           0x0000000108aad558 llvm::Expected<swift::ASTLoweringRequest::OutputType> swift::Evaluator::operator()<swift::ASTLoweringRequest, (void*)0>(swift::ASTLoweringRequest const&) + 152
22 swift-frontend           0x0000000108aad405 swift::performASTLowering(swift::ModuleDecl*, swift::Lowering::TypeConverter&, swift::SILOptions const&) + 165
23 swift-frontend           0x000000010874135d performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 509
24 swift-frontend           0x0000000108739971 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 4625
25 swift-frontend           0x00000001086d152e main + 846
26 libdyld.dylib            0x00007fff20489591 start + 1
FileCheck error: '<stdin>' is empty.
FileCheck command line:  /Users/ktoso/code/swift-project/build/Ninja-RelWithDebInfoAssert/llvm-macosx-x86_64/bin/FileCheck /Users/ktoso/code/swift-project/swift/test/SILGen/switch.swift
```

Not sure when I'll get time to dive into this... 🤔

**Pull request closed without merging**
