### PR TITLE
[SE-0328] Enable structural opaque result types.

### PR DESCRIPTION
**Pull request by hborla**
* Enable structural opaque types by default
* Remove the `-enable-experimental-structural-opaque-types` frontend flag
* Ban opaque types in parameter position, per the [acceptance decision](https://forums.swift.org/t/accepted-with-modifications-se-0328-structural-opaque-result-type/53789) of SE-0328. Note that this restriction applies to `some` appearing anywhere in the parameter type, including positions that do not consume values from the caller, e.g. `func test() -> ((some P) -> Void) -> Void { ... }`

Resolves: rdar://85275081

### CODE REVIEW

**Review by slavapestov — APPROVED** [review]

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by hborla** [comment]
@swift-ci please smoke test Linux platform

**Comment by hborla** [comment]
@swift-ci please test Windows platform

**Comment by hborla** [comment]
@swift-ci please test Windows platform

**Comment by hborla** [comment]
```
Failed Tests (1):
  Swift(windows-x86_64) :: Serialization/path_obfuscator.swift
```

Windows test failure will be fixed by this revert: https://github.com/apple/swift/pull/40368

**Comment by hborla** [comment]
@swift-ci please test Windows platform

**Pull request merged**
