### PR TITLE
[AutoDiff] fix SR-12493

### PR DESCRIPTION
**Pull request by marcrasi**
We simply needed to upstream `TypeSubstCloner::visitDifferentiableFunctionExtractInst`.

The code has a detailed comment explaining what it does.

Resolves SR-12493.

### CODE REVIEW

**Comment by marcrasi** [comment]
@swift-ci please test

**Review by dan-zheng — APPROVED** [review]
Nice catch!

**Comment by dan-zheng** [comment]
Merging to unblock progress!

**Comment by zoecarver** [comment]
Is it possible that this change caused a failure on some linux bots? I saw what (I think) is [an unrelated error](https://ci.swift.org/job/swift-PR-Linux/20676/console) when testing my PR and tracked the error to [this forum post](https://forums.swift.org/t/swift-ci-build-failure-0-oss-swift-incremental-ra-ubuntu-16-04-master-12871/35131) and then here.

**Error:**
```
12:26:01 ******************** TEST 'Swift(linux-x86_64) :: AutoDiff/compiler_crashers_fixed/sr12493-differentiable-function-extract-subst-function-type.swift' FAILED ********************
12:26:01 Script:
12:26:01 --
12:26:01 : 'RUN: at line 1';   /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/buildbot_linux/swift-linux-x86_64/bin/swiftc -target x86_64-unknown-linux-gnu -toolchain-stdlib-rpath  -module-cache-path '/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/buildbot_linux/swift-linux-x86_64/swift-test-results/x86_64-unknown-linux-gnu/clang-module-cache' -swift-version 4  -Xfrontend -ignore-module-source-info  -O /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/swift/test/AutoDiff/compiler_crashers_fixed/sr12493-differentiable-function-extract-subst-function-type.swift
12:26:01 --
12:26:01 Exit Code: 254
12:26:01 
12:26:01 Command Output (stderr):
12:26:01 --
12:26:01 
clang-10: error: unable to execute command: Bus error (core dumped)
12:26:01 clang-10: error: linker command failed due to signal (use -v to see invocation)
12:26:01 <unknown>:0: error: link command failed with exit code 254 (use -v to see invocation)
12:26:01 
12:26:01 --
12:26:01 
12:26:01 ********************
```

**Comment by marcrasi** [comment]
I've seen this test pass on Linux before, so either it's flaky or https://github.com/apple/swift/pull/31134 is uncovering something that causes it to fail.

I'll try to repro on my Linux machine with/without https://github.com/apple/swift/pull/31134 and then try to fix it.

**Comment by zoecarver** [comment]
Thanks, much appreciated. Let me know if I can help. 

I can see that it passed before it was committed. But, this commit is also the only one in the blame list so it's likely flaky (or needs a config that's present on only _some_ bots).

**Comment by marcrasi** [comment]
My guess right now is that it was a flake caused by the worker being low on memory or disk, not by anything the test does.

Evidence for this hypothesis:
* I can't repro on my linux machine, with and without #31134.
* It hasn't failed on any other recent https://ci.swift.org/job/swift-PR-Linux/ jobs, including one that happened on the same worker machine: https://ci.swift.org/job/swift-PR-Linux/20662/
* `/usr/bin/time -v <the compiler command that lit runs>` on my linux machine outputs "Maximum resident set size (kbytes): 87836", so the test isn't using a huge amount of memory.

So I'd suggest running the tests again, if you don't mind. If this test does fail again, then we can disable it and spend more time investigating why it is flaky.

**Comment by zoecarver** [comment]
That sounds good to me. Thanks for doing a full investigation. 

The reason I thought that it might not be a one-time thing is both the incremental build (see forum post) and my PR had the error. But, it could easily be something else (given the logs from the forum post are unfortunately missing).

**Comment by tbkka** [comment]
We're seeing this test fail erratically on some configurations.  (Most recently, Ubuntu 20.04).   Any thoughts?

**Comment by dan-zheng** [comment]
I created https://github.com/apple/swift/pull/32394 to temporarily disable the flaky test. SR-13021 tracks re-enabling it.

**Pull request merged**
