### PR TITLE
Reenable Runtime/linux-fatal-backtrace.swift test

### PR DESCRIPTION
**Pull request by bob-wilson**
The best guess so far is that the failure that caused the test to be
disabled was a consequence of not running a clean build to regenerate
the lit.site.cfg file so that the "REQUIRES: lldb" check gave the wrong
answer. rdar://problem/33718631

### CODE REVIEW

**Comment by bob-wilson** [comment]
Mishal, what should we do to test this?

**Comment by shahmishal** [comment]
@swift-ci test Linux

**Comment by shahmishal** [comment]
@swift-ci smoke test macOS

**Review by shahmishal — APPROVED** [review]
LGTM

**Comment by bob-wilson** [comment]
The failures in those builds had nothing to do with this change. I'll wait a bit and re-test later.

**Comment by bob-wilson** [comment]
@swift-ci test Linux

**Comment by bob-wilson** [comment]
@swift-ci smoke test macOS

**Comment by bob-wilson** [comment]
The latest Linux test attempt failed because the utils/symbolicate-linux-fatal script was not executable. I added a change to fix that. Let's try again.

**Comment by bob-wilson** [comment]
@swift-ci test Linux

**Comment by bob-wilson** [comment]
I don't know what happened to that last round of tests. Let's try again.

**Comment by bob-wilson** [comment]
@swift-ci test Linux

**Comment by bob-wilson** [comment]
@swift-ci smoke test macOS

**Pull request merged**
