### PR TITLE
[AutoDiff] Rename `@transposing` to `@transpose(of:)`.

### PR DESCRIPTION
**Pull request by dan-zheng**
Rename `@transposing` to `@transpose(of:)`. `@transpose(of:)` more clearly
evokes transpose registration; the syntax is otherwise unchanged.

Discussed here: https://github.com/apple/swift/pull/28321#discussion_r347757647

Remove `@transposing`. Removal without deprecation should be fine because
there are no known users of `@transposing` attribute.

Resolves TF-992.

TF-1009 tracks `@transpose` syntax support for qualified names.

### CODE REVIEW

**Review by rxwei — APPROVED** [review]

**Review by bgogul — APPROVED** [review]
Looks good to me.

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@bgogul gave the suggestion of deleting `@transposing` outright without deprecation, as it's essentially a stub with no known users outside of tests. Deleting code is certainly good for maintenance.

I think this makes sense, so I'll do it now.

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow linux gpu

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow macOS

**Pull request merged**
