### PR TITLE
[concurrency] type-checking global-actor-isolated references in ordinary functions

### PR DESCRIPTION
**Pull request by kavon**
Non-actor isolated synchronous functions were mistakenly allowed to call & reference global-actor isolated declarations:

```swift
actor class TestActor {}

@globalActor
struct SomeGlobalActor {
  static var shared: TestActor { TestActor() }
}

@SomeGlobalActor func syncGlobActorFn() { }

func ordinaryFunc() {
  syncGlobActorFn() // reference A
  let x = syncGlobActorFn // reference B
  x()
}
```

There are two invalid references to global-actor isolated declarations. There are various ways to fix such problems:

1. marking `ordinaryFunc` as `@asyncHandler`
2. marking `ordinaryFunc` as `async`
3. making `ordinaryFunc` part of the global-actor that `syncGlobActorFn` belongs to.

We only suggest fix (3) if the incorrect global-actor reference is not part of an apply (i.e., reference B). For reference A, which directly applies the function, we suggest all 3 as possible fixes.

Thus, in terms of new fix-its: If the caller is not associated with an actor and is a synchronous function that refers to a global-actor isolated declaration, we will suggest the option of making that synchronous function part of the global-actor's context (fixing rdar://71698464). We do *not* suggest becoming part of the global-actor if the reference appears in an async context.

Resolves rdar://71548470&71698464

TODOs:
- [x] enhance regression test with fix-it checking (+ manually verify that they produce valid code)

### CODE REVIEW

**Comment by kavon** [comment]
@swift-ci please smoke test

**Comment by kavon** [comment]
@swift-ci please smoke test

**Comment by kavon** [comment]
@swift-ci please smoke test

**Review by DougGregor — APPROVED** [review]

**Comment by kavon** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
