### PR TITLE
Adapt Driver Dependencies Test Suite to Private Dependencies

### PR DESCRIPTION
**Pull request by CodaFi**

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by davidungar** [comment]
The swiftdeps file includes a version at the top. How about incrementing that?

**Comment by davidungar** [comment]
You have my sympathy! There are a *lot* of tests to fix.

**Comment by CodaFi** [comment]
We don't need to bump the version number just for private dependencies since the written format is independent of these changes. That is, unless you meant that it should have been incremented a-priori. In which case, I can do the grunt work for that in a follow-up just to make sure I get all the tests in one pass.

**Comment by CodaFi** [comment]
Hm, this is the second time I've seen SourceKit/CodeComplete/complete_checkdeps_bridged.swift fail spuriously...

@swift-ci clean smoke test Linux platform

**Comment by davidungar** [comment]
Good point about the format being compatible. I'm thinking, though, that even though we don't *need* to bump it, it could be useful to bump it. Might it offer an easy way to see which authoring strategy is being used in the frontend? For instance when we have to go in and look at a compiler that we didn't build?

**Comment by CodaFi** [comment]
@swift-ci smoke test Linux

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
