### PR TITLE
[SR-7165] Excise iostream from reflection

### PR DESCRIPTION
**Pull request by nafu**
Replace iostream with [raw_ostream](http://www.llvm.org/docs/CodingStandards.html#raw-ostream) to follow [LLVM Coding Standards](http://www.llvm.org/docs/CodingStandards.html#include-iostream-is-forbidden).
With this PR, we still use iostream for reading in tools/swift-reflection-dump/swift-reflection-dump.cpp.

Resolves [SR-7165](https://bugs.swift.org/browse/SR-7165).

### CODE REVIEW

**Comment by jckarter** [comment]
Thanks! I'm not sure we can get away with using `raw_ostream` either, though, since some of this code gets linked into runtime libraries that don't and shouldn't link against LLVM either. It's probably best to use C `printf`/`sprintf` in most of these situations.

**Comment by slavapestov** [comment]
@jckarter I don't think any part of Reflection gets linked into the runtime at the moment, and there are no plans to do so.

**Review by slavapestov — APPROVED** [review]

**Comment by jrose-apple** [comment]
If it's not linked into the runtime, it shouldn't live in stdlib/.

**Comment by jckarter** [comment]
@slavapestov I still don't think any of Reflection's clients want to link in LLVM runtime libraries either.

**Comment by nafu** [comment]
> It's probably best to use C `printf`/`sprintf` in most of these situations.

Can I try this one? Should I update this PR or create another PR?

**Comment by jckarter** [comment]
@nafu Sure, thanks for looking into it! It's up to you whether you want to update this PR or start a new one.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by jrose-apple** [comment]
Oops, it looks like we forgot about this one. I'm going to close the PR because the libraries have changed a lot since last year, but the bug's still available.

**Pull request closed without merging**
