### PR TITLE
[Gardening] Remove dead code in SerializeDoc.cpp

### PR DESCRIPTION
**Pull request by owenv**
I noticed this was unused while doing some cleanup nearby.

### CODE REVIEW

**Comment by owenv** [comment]
@swift-ci smoke test

**Review by nkcsgexi — APPROVED** [review]
Thank you for fixing this!

**Comment by owenv** [comment]
@swift-ci please smoke test Linux platform

**Comment by owenv** [comment]
@swift-ci please smoke test Linux platform

**Comment by owenv** [comment]
Failure looks like it's fixed now

@swift-ci please smoke test Linux platform

**Comment by owenv** [comment]
@swift-ci smoke test linux

**Pull request merged**
