### PR TITLE
Implement ClangImporter importSourceLoc and importSourceRange

### PR DESCRIPTION
**Pull request by NuriAmari**
Implement `ClangImporter::Implementation::importSourceLoc` and `ClangImporter::Implementation::importSourceRange`.

### CODE REVIEW

**Comment by NuriAmari** [comment]
The change to `ImportDecl.cpp` it so prevent a failing assert in `objc_ir.swift`. The issue is as follows:

A SourceRange when created asserts that both the start and end locations are either both invalid, or both valid. When you call getSourceRange or something similar on an AbstractFunctionDecl, it gives you a range from the `NameLoc` to the location of the end of the last param. By implementing `importSourceLoc`, the location of the end of the last param was no longer invalid, but `NameLoc` was initialized with an empty `SourceLoc` and hence invalid. This fails an assert, but providing a valid source location for `NameLoc` solves the problem.

**Review by zoecarver — APPROVED** [review]
Thanks, Nuri. Looks great.

**Comment by drodriguez** [comment]
@swift-ci please test

**Comment by drodriguez** [comment]
@swift-ci please test Linux platform

**Comment by drodriguez** [comment]
I think Linux failed because we started testing between apple/swift#9723 and apple/swift-markdown#11. Hopefully it works now. I don't know if macOS will fail in the same way later.

**Comment by plotfi** [comment]
Looks good to me.

**Comment by drodriguez** [comment]
Rebuild locally with LLDB and I don't get the segfault. I will keep trying, but firing macOS again just in case it was just flaky.

@swift-ci please test macOS platform

**Comment by drodriguez** [comment]
@swift-ci please test Linux platform

**Comment by Kyle-Ye** [comment]
> I think Linux failed because we started testing between #9723 and [apple/swift-markdown#11](https://github.com/apple/swift-markdown/pull/11). Hopefully it works now. I don't know if macOS will fail in the same way later.

Do you mean between **#39723** and [apple/swift-markdown#11]? And can you confirm the macOS failure has something to do with this issue. I'm currently working on add a PR [apple/swift-markdown#13] to revert the "revert" PR [apple/swift-markdown#11].

**Comment by NuriAmari** [comment]
> And can you confirm the macOS failure has something to do with this issue?
The macOS failure looks to be something else.

**Comment by drodriguez** [comment]
> Do you mean between **#39723** and [[apple/swift-markdown#11](https://github.com/apple/swift-markdown/pull/11)]?

Correct, #39723. I must have copy/pasted wrong. The Darwin failure was something related to DocC, I looked around and found that recent PR being merged, and the revert in the other repository. As it shows in the second Linux run, those problems seems to be gone.

The macOS problems seems to be unrelated to those issues, and seems to be related to these changes.

**Comment by drodriguez** [comment]
@swift-ci please smoke test macOS platform

**Comment by drodriguez** [comment]
After a long divide and conquer session, the problem happens from three invocations:

```diff
diff --git i/lib/ClangImporter/ImportDecl.cpp w/lib/ClangImporter/ImportDecl.cpp
index e0182ef422a..2c8fec87191 100644
--- i/lib/ClangImporter/ImportDecl.cpp
+++ w/lib/ClangImporter/ImportDecl.cpp
@@ -3376,8 +3376,13 @@ namespace {
       if (alreadyImportedResult != Impl.ImportedDecls.end())
         return alreadyImportedResult->second;
       result = Impl.createDeclWithClangNode<StructDecl>(
-          decl, AccessLevel::Public, Impl.importSourceLoc(decl->getBeginLoc()),
-          name, Impl.importSourceLoc(decl->getLocation()), None, nullptr, dc);
+          decl, AccessLevel::Public,
+          // FIXME: Impl.importSourceLocBAD(decl->getBeginLoc()),
+          SourceLoc(),
+          name,
+          // FIXME: Impl.importSourceLocBAD(decl->getLocation()),
+          SourceLoc(),
+          None, nullptr, dc);
       Impl.ImportedDecls[{decl->getCanonicalDecl(), getVersion()}] = result;
 
       // FIXME: Figure out what to do with superclasses in C++. One possible
@@ -4215,7 +4220,8 @@ namespace {
         Impl.createDeclWithClangNode<VarDecl>(decl, AccessLevel::Public,
                               /*IsStatic*/ false,
                               VarDecl::Introducer::Var,
-                              Impl.importSourceLoc(decl->getLocation()),
+                              // FIXME: Impl.importSourceLocBAD(decl->getLocation()), // BAD import
+                              SourceLoc(),
                               name, dc);
       if (decl->getType().isConstQualified()) {
         // Note that in C++ there are ways to change the values of const
```

These invocations are related to `VisitRecordDecl` and `VisitFieldDecl`. The header that it is imported in the LLDB test only contains a `struct` definition. However, I tried adding a macro and a typedef and those doesn't seem to fail (a function sadly needs implementation, which cannot be provided inline). My theory was that only the used pieces were failing, but the theory might be wrong.

A possible approach is leaving those three invocations with just `SourceLoc()`, which is equivalent to what was before, add a `FIXME` comment pointing to some bug in the bug tracker, and explain what we experienced there, and hopefully someone that knows more about LLDB internals can help.

One thing that I don't know if it happens automatically or not is that the test seems to be rewriting the source map, and also providing an overlay. I don't know if the current implementation of `resolveSourceLocation` have those into account, or if by ignoring them, it is creating this problem (I wonder if there's some test on the Swift side with any of those concepts that should have catch this earlier).

I also have a spindump of the Python process when it was failing, but I don't know if it actually captures close to the segfault or not (it is complicated to capture a spindump of the exact thing that's happening, but I was hoping to see an infinite recursion or similar).

**Comment by drodriguez** [comment]
@swift-ci please smoke test

**Comment by drodriguez** [comment]
@swift-ci please smoke test

**Comment by drodriguez** [comment]
The linux one seems unrelated (something with DocC). Seems that non-smoke is passing, so…

@swift-ci please test Linux platform

**Comment by bnbarham** [comment]
FWIW I put a PR up to implement these a while back (https://github.com/apple/swift/pull/39701) but let it fall off my radar. Most of the PR is changes for actually returning the imported source location in `Decl::getLoc` (`FileUnitKind::ClangModule` kinds always return `SourceLoc()` otherwise).

The other part is changing how line directives are handled. I never actually tested the performance, but I was concerned with the current implementation when line directives are involved - it grabs the presumed location for *every* location and adds a "VirtualFile" for *every* imported line. Not super important when it's just diagnostics making locations, but IMO would be good to avoid if we actually import locations for all decls. It also doesn't handle EOF properly.

One of the main issues is that it relies on the SourceManager internals and a LLVM change, which I never put up (basically just making all line entries accessible).

**Comment by drodriguez** [comment]
@bnbarham: thanks for the feedback. We have been seeing better reporting by using the `resolveSourceLocation`, but we don't have as many changes as you have in that other diff (which probably covers a little bit more than we are doing here). Maybe we also not hitting the performance problems of the virtual files because our limited use of `resolveSourceLocation` vs the number of times `importSourceLoc` is used.

PD: the Linux test failed again with the DocC problem. I see some green ones in the bots now, I will restart in a moment.

**Comment by drodriguez** [comment]
@swift-ci please smoke test Linux platform

**Comment by drodriguez** [comment]
@swift-ci Please test compiler performance

**Comment by bnbarham** [comment]
> Maybe we also not hitting the performance problems of the virtual files because our limited use of `resolveSourceLocation` vs the number of times `importSourceLoc` is used.

`importSourceLoc` just calls `resolveSourceLocation` though. But anyway, as I said - I never actually tested the performance, it just didn't seem great to add a new "virtual file" for every line + grab the presumed location every time.

**Comment by zoecarver** [comment]
I'd love to see these changes land. Is there anything currently blocking this?

@swift-ci please test linux platform.

**Comment by zoecarver** [comment]
@swift-ci please test linux platform

**Comment by drodriguez** [comment]
> I'd love to see these changes land. Is there anything currently blocking this?

Nothing beyond me wanting to check that I understood the benchmark results correctly, and those "regressions" are just talking about number of files, and not some number of seconds.

@bnbarham: from the benchmarks above, it looks like, as expected, the number of source buffers grows significantly, but nothing else regressed, specially in time. Merging this would allow you to continue your work in that other PR without a lot of conflict, but tell us if we should hold this for any other reason. Thanks!

**Comment by bnbarham** [comment]
> Nothing beyond me wanting to check that I understood the benchmark results correctly, and those "regressions" are just talking about number of files, and not some number of seconds.
> 
> @bnbarham: from the benchmarks above, it looks like, as expected, the number of source buffers grows significantly, but nothing else regressed, specially in time. Merging this would allow you to continue your work in that other PR without a lot of conflict, but tell us if we should hold this for any other reason. Thanks!

Looks like it's just the number of files to me, so seems fine. I'll close the other PR, if people are interested in having `getLoc` return the imported location I can fix those tests that currently fail and put it up again though. Although we probably wouldn't want to do that until those FIXME's are fixed.

**Pull request merged**
