### PR TITLE
Align certain records on 8-bit boundary for ARM builds

### PR DESCRIPTION
**Pull request by iachievedit**
#### What's in this pull request?

Fixes for ARM build failure introduced by https://github.com/apple/swift/commit/508e825ff2fc988da9e3ab433a5187779baa0490 (additional info bits added for PointerIntPair GetSetRecord and BehaviorRecord).

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

A smoke test on macOS does the following:
1. Builds the compiler incrementally.
2. Builds the standard library only for macOS. Simulator standard libraries and
   device standard libraries are not built.
3. lldb is not built.
4. The test and validation-test targets are run only for macOS. The optimized
   version of these tests are not run.

A smoke test on Linux does the following:
1. Builds the compiler incrementally.
2. Builds the standard library incrementally.
3. lldb is built incrementally.
4. The swift test and validation-test targets are run. The optimized version of these
   tests are not run.
5. lldb is tested.

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by hpux735** [comment]
Thanks, Joe!

**Comment by gottesmm** [comment]
Do we use these for tagged pointers anywhere?

**Comment by hpux735** [comment]
By tagged do you mean PointerIntPair?  If so, yes.  See the linked commit from @jrose-apple .  An additional field was added to the enum used in that commit, which necessitated an additional bit in the pointer.

**Comment by gottesmm** [comment]
So the issue is that there are not enough tagged pointer bits on ARM by default, so we need to manually align due to that change?

**Comment by hpux735** [comment]
Yep, that's the ticket.  I assume it's because ARM is only 32-bit, so the default alignment used on the 64-bit targets is sufficient without this modification.

**Comment by gribozavr** [comment]
@swift-ci Please smoke test

**Comment by gribozavr** [comment]
@swift-ci Please test Linux platform

**Comment by jrose-apple** [comment]
Ah, good catch, sorry for the trouble!

**Comment by iachievedit** [comment]
No worries, @jrose-apple , thanks for the merge @gribozavr I've kicked off a build for the BeagleBone and Raspberry Pis.  Much appreciated!

**Pull request merged**
