### PR TITLE
[move-only] Ensure that if we have an allocation that isn't fully initialized (and DI errors on it as such), the move checkers do not run on the allocation.

### PR DESCRIPTION
**Pull request by gottesmm**
Previously we would crash.

The methodology here is that I added a flag to alloc_stack and alloc_box called had_di_error. DI if it emits an error on said alloc_stack/alloc_box will set the flag. If the move checker sees that flag then:

1. It doesn't process the allocation.
2. It acts as if it emitted an error meaning that it will eliminate the mark_must_check and convert any copies to non-asserting variants without emitting a "found a copy, please file a bug" error.

rdar://108993297

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
Made the change smaller/simpler so that I don't have to touch the module format.

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Review by jckarter — APPROVED** [review]

**Pull request merged**
