### PR TITLE
Removed the legacy code path for non-strict-DA from deabstraction

### PR DESCRIPTION
**Pull request by mhong**
This is to facilitate bug fix work in that area (https://bugs.swift.org/browse/SR-8405).

Also removed the strict DA flag.

### CODE REVIEW

**Comment by mhong** [comment]
@swift-ci please test tensorflow

**Comment by bgogul** [comment]
Nice!

**Comment by mhong** [comment]
Merging so that I can send a follow-up PR. Happy to address any comments as needed.

**Comment by mhong** [comment]
I'll work with @bgogul to follow up on the clean-ups.

**Pull request merged**
