### PR TITLE
Sema: Clean up name lookup and fix a couple of bugs

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
I feel like a "don't perform conformance checks" flag is a bit more than just a clean-up. Can you talk more about what this is doing and why it's safe?

**Comment by slavapestov** [comment]
@jrose-apple The flag just makes the old behavior explicit where passing in a nominal type would allow conformance checks, but passing in a metatype would not.

**Comment by slavapestov** [comment]
We don't want to do conformance checks when matching protocol witnesses for example, to avoid runaway recursion. However we _do_ want witness lookup to consider protocol extension members.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Pull request merged**
