### PR TITLE
Add sequence command to lldbToolBox

### PR DESCRIPTION
**Pull request by kastiglione**
A recent addition to the debugging docs #15613 provides some exposure to using lldb's python API. This pull request adds an lldb command named `sequence` which is for running multiple commands as though they were a single command. This may sound too simple, but it can be quite useful.

The python example shown in #15613 can be implemented with `sequence` and without resorting (which I say with love) to python.

```
command alias cs sequence p/x $rax; stepi
```

I've also found `sequence` useful for breakpoint commands, and for writing `command regex` aliases. 

As an example of `command regex` (and to expand on the example shown in the header doc), gdb has a convenient and mnemonic `break ... if ...` command. Using `sequence`, lldb's `b` alias can be _extended_ to support breakpoint conditions too:

```
command regex b
s/(.+) if (.+)/seq _regexp-break %1; break mod -c "%2"/
s/(.*)/_regexp-break %1/
```

By default, `b` is an alias for `_regexp-break`. This means anyone can write a custom `b` that just builds on top of `_regexp-break`, which is what's happening here. This override allows for breakpoints to be created in this way: `b someMethod if someVar > 2`.

### CODE REVIEW

**Comment by kastiglione** [comment]
cc @vedantk

**Comment by vedantk** [comment]
Thanks, this is really neat.

Could you add comments in the docstring for `sequence` explaining what the example commands are? LGTM otherwise.

**Comment by vedantk** [comment]
Great :)

@swift-ci smoke test and merge

**Comment by vedantk** [comment]
@swift-ci smoke test and merge

**Comment by kastiglione** [comment]
Should add a mention in docs/DebuggingTheCompiler.rst?

**Comment by vedantk** [comment]
Sure, that's a good idea. You could show how the "custom_step" command can be expressed via "sequence".

**Comment by vedantk** [comment]
Looks good.

**Comment by vedantk** [comment]
@swift-ci smoke test and merge

**Comment by vedantk** [comment]
@swift-ci smoke test and merge

**Comment by vedantk** [comment]
@swift-ci smoke test and merge

**Comment by vedantk** [comment]
@swift-ci smoke test and merge

**Comment by vedantk** [comment]
Yikes, I wasn't aware we ran a python linter as part of the validation tests. @kastiglione mind taking a look at the issue?

```
18:02:35 ./utils/lldb/lldbToolBox.py:12:1: I100 Import statements are in the wrong order. import os should be before import lldb
18:02:35 ./utils/lldb/lldbToolBox.py:94:21: E261 at least two spaces before inline comment
```

**Comment by gottesmm** [comment]
@vedantk This is because people kept on having to do cleanup commits. Instead, the linting pre-merge just nips all such issues in the bud.

**Comment by kastiglione** [comment]
Thanks will do.

**Comment by compnerd** [comment]
*waves at @kastiglione*

Hmm, failure seems relevant?

```
******************** TEST 'Swift(macosx-x86_64) :: Python/python-lint.swift' FAILED ********************
18:02:35 Script:
18:02:35 --
18:02:35 /usr/bin/python /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/swift/utils/python_lint.py
18:02:35 --
18:02:35 Exit Code: 1
18:02:35 
18:02:35 Command Output (stdout):
18:02:35 --
18:02:35 ./utils/lldb/lldbToolBox.py:12:1: I100 Import statements are in the wrong order. import os should be before import lldb
18:02:35 ./utils/lldb/lldbToolBox.py:94:21: E261 at least two spaces before inline comment
18:02:35 
18:02:35 --
18:02:35 
18:02:35 ********************
```

**Comment by kastiglione** [comment]
*waves back @compnerd*

Yep, I'll update after I figure out what went wrong with my macOS update.

**Comment by kastiglione** [comment]
@vedantk The python lint diagnostics have been addressed.

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Pull request merged**
