### PR TITLE
Use a More Specific Assert for RValue Type Lowering

### PR DESCRIPTION
**Pull request by CodaFi**
Fixes a crash caused by the lowering mechanism editing the storage flags for a type.

### CODE REVIEW

**Comment by jckarter** [comment]
Looks good, thanks!

**Comment by lattner** [comment]
nice!

**Comment by bitjammer** [comment]
Sorry @CodaFi! I had to revert this as the test was still crashing in IRGen. I think the assertion is correct and actually reporting a problem with an instruction earlier in the function: https://bugs.swift.org/browse/SR-87

**Comment by CodaFi** [comment]
It's to be expected; it was a rather quick patch.  Do you know if IRGen was crashing around that assert or somewhere else?

**Comment by jckarter** [comment]
Looking closer, I agree with @bitjammer. Something's going wrong before we get here; either there's a loadable rvalue that isn't getting loaded, or since inout is involved, we're confusing lvalues and rvalues somewhere.

**Pull request merged**
