### PR TITLE
Sema: Fix crashes in witness access control checking

### PR DESCRIPTION
**Pull request by slavapestov**
This fixes a crash-on-invalid regression from the fix for
<rdar://problem/43824052>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Review by jrose-apple — APPROVED** [review]
\*siiigh\*

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Comment by slavapestov** [comment]
```
01:15:16.367 CMake Error at utils/cmake_install.cmake:44 (file):
01:15:16.367   file INSTALL cannot find "/bin/FileCheck".
```

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Pull request merged**
