### PR TITLE
StdlibUnittest: make TestSuite and other helper classes final

### PR DESCRIPTION
**Pull request by gribozavr**
These classes are not meant to be subclassed.

### CODE REVIEW

**Comment by gribozavr** [comment]
@swift-ci Please test and merge

**Comment by modocache** [comment]
Looks like the Linux build timed out, preventing this from being merged. Try kicking it off again?

**Comment by gribozavr** [comment]
@swift-ci Please test and merge

**Comment by gribozavr** [comment]
@modocache Thanks for reminding me!

**Pull request merged**
