### PR TITLE
Revert " Remove extensions on ImplicitlyUnwrappedOptional from the stdlib."

### PR DESCRIPTION
**Pull request by rudkx**
Partially reverts apple/swift#12713

It looks like this probably broke conditional casts from IUOs to NSObject.

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@DougGregor Any ideas about this build failure?

I hit it locally as well and changing the result type to `ImplicitlyUnwrappedOptional<Wrapped>` didn't seem to help.

Perhaps an associated type or conformance checking problem?

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
I'm working on new test cases for `ImplicitlyUnwrappedOptional<T>` and `Optional<T>` bridging and will push them here and re-run before merging.

**Comment by rudkx** [comment]
I've also opened a PR for 4.1: https://github.com/apple/swift/pull/13976

The difference is that the PR for master also has to back out a change to conformance checking which broke reintroducing these extensions.

**Comment by rudkx** [comment]
timeout on linux

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please smoke test Linux platform

**Comment by rudkx** [comment]
@shahmishal The linux machine here appears to have an old version of CMake so the configure failed.

**Comment by shahmishal** [comment]
@rudkx Looking into it.

**Comment by rudkx** [comment]
@swift-ci Please test OS X platform

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
Another Linux timeout

**Comment by rudkx** [comment]
@swift-ci Please smoke test Linux

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
@swift-ci Please smoke test Linux platform

**Comment by rudkx** [comment]
There was another timeout on linux. I've seen this several times now across a few different PR.

**Review by DougGregor — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
