### PR TITLE
[Debugging] Add DebugDescriptionMacro experimental feature

### PR DESCRIPTION
**Pull request by kastiglione**
This removes the leading underscore from the macro.

### CODE REVIEW

**Comment by kastiglione** [comment]
@swift-ci smoke test

**Review by adrian-prantl — APPROVED** [review]

**Comment by kastiglione** [comment]
@swift-ci test macOS

**Comment by kastiglione** [comment]
@swift-ci linux macOS

**Comment by kastiglione** [comment]
@swift-ci test linux

**Comment by drodriguez** [comment]
Does this need some handling of asserts vs. no asserts compiler?

**Comment by kastiglione** [comment]
@drodriguez I don't believe so

**Comment by kastiglione** [comment]
Thanks, I see the problem. Fix here https://github.com/apple/swift/pull/73097

**Pull request merged**
