### PR TITLE
[Migrator] Add adapter for clang lib/Edit textual edits

### PR DESCRIPTION
**Pull request by bitjammer**
This adds an adapter class that wraps Clang's lib/Edit
Commit and EditedSource classes for use in the initial
"syntactic" passes. Once the passes have completed,
the resulting source file is then passed to the Swift compiler
fix-it passes.

rdar://problem/30926261

### CODE REVIEW

**Comment by bitjammer** [comment]
@swift-ci Please smoke test

**Comment by bitjammer** [comment]
@nkcsgexi Do you want to give this a test drive before I land it? https://github.com/bitjammer/swift/tree/migrator-editor

**Comment by bitjammer** [comment]
@swift-ci Please smoke test

**Comment by nkcsgexi** [comment]
Can we add a test that without any migration pass, a source file will dump itself unchanged?

**Comment by nkcsgexi** [comment]
To elaborate, I mean to add a test file that needs no migration at all; when going through the pipeline, it keeps untouched. This makes sure we don't drop ball in between and all passes connect well.

**Comment by bitjammer** [comment]
Yep, sounds good. If each syntactic pass has to be enabled specifically, I think this command should result in no changes:

`swift -frontend -update-code -disable-migrator-fixits input.swift -emit-migrated-file-path output.swift`

**Comment by nkcsgexi** [comment]
hmm, i guess we still want all the passes, so avoid `-disable-migrator-fixits`. We can easily make a test case where no migration should be applied, simple like `func foo() -> Int { return 0 }`.

**Comment by bitjammer** [comment]
Fair enough.

**Comment by bitjammer** [comment]
OK, added a "null migration" test.

**Comment by bitjammer** [comment]
@swift-ci Please smoke test

**Comment by bitjammer** [comment]
Linux failure is unrelated.

**Comment by bitjammer** [comment]
@swift-ci Please smoke test

**Pull request merged**
