### PR TITLE
Try disabling CSV benchmarks to see if that unsticks PR benchmark runs

### PR DESCRIPTION
**Pull request by airspeedswift**
Seems like PR benchmarks aren't completing. On my machine, they are hanging on these benchmarks. Trying to see if temporarily disabling them resolves the issue.

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
@swift-ci please smoke test

**Comment by airspeedswift** [comment]
Ah except it'll still run them on master...

**Comment by moiseev** [comment]
Radar to re-enable them: <rdar://problem/36993861>

**Comment by jrose-apple** [comment]
cc @gottesmm, @shahmishal, @lancep

**Pull request merged**
