### PR TITLE
[BarrierAccessScopes] Handle end_access instructions' barrierness introduced during run.

### PR DESCRIPTION
**Pull request by nate-chandler**
As the utility runs, new gens may become local: as access scopes are determined to contain deinit barriers, their `end_access` instructions become kills; if such an `end_access` occurs in the same block above an initially-non-local gen, that gen is now local.

Previously, it was asserted that kills would not be encountered when visiting a block backwards from an initially-non-local gen.  As described above, the assertion was incorrect.

Iteration would also _stop_ at the discovered kill, if any.  That too was incorrect. To continue walking the block after finding such a newly discovered kill is needed by the book-keeping the utility does for which access scopes contain barriers: there may be more `end_access` instructions.  Concretely, there are two cases: (1) The block may contain another `end_access` and above it a deinit barrier which must result in that second scope becoming a deinit barrier. (2) Some of the block's predecessors may be in the region, all the access scope which are open at the begin of this block must be unioned into the set of scopes open at each predecessors' end, and more such access scopes may be discovered above the just-visited `end_access`.

Here, both the assertion failure and the early bailout are fixed by walking from the indicated initially-non-local gen backwards over the entire block, regardless of whether a kill was encountered.  If a kill is encountered, it is asserted that the kill is an `end_access` to account for the case described above.

rdar://139840307

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test linux platfrom

**Comment by nate-chandler** [comment]
@swift-ci please test macos platform

**Comment by nate-chandler** [comment]
@swift-ci please test linux platform

**Review by atrick — APPROVED** [review]
Makes sense!

**Pull request merged**
