### PR TITLE
AST: Fix compareDependentTypes() for protocol typealiases [3.1]

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes https://bugs.swift.org/browse/SR-3687 and rdar://problem/30118513.

### CODE REVIEW

**Comment by slavapestov** [comment]
@DougGregor Can I have your seal of approval here?

**Comment by slavapestov** [comment]
(The SILGen patch is also in https://github.com/apple/swift/pull/7082, to be reviewed by Joe -- I didn't take it out of here because both touch test/SILGen/same_type_abstraction.swift).

**Review by DougGregor — APPROVED** [review]
LGTM, thanks!

**Comment by tkremenek** [comment]
@swift-ci test

**Pull request merged**
