### PR TITLE
Remove Fallback Infrastructure For Evaluator-Based Dependencies

### PR DESCRIPTION
**Pull request by CodaFi**
Drafted for now so we don't merge this before the branch date

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci test source compatibility

**Comment by CodaFi** [comment]
@swift-ci test macOS

**Comment by CodaFi** [comment]
@swift-ci test source compatibility Debug

**Comment by CodaFi** [comment]
@swift-ci test macOS

**Comment by CodaFi** [comment]
@swift-ci test macOS

**Review by slavapestov — APPROVED** [review]
This is great!

**Pull request merged**
