### PR TITLE
[Test] Reenable SIL unit tests on windows.

### PR DESCRIPTION
**Pull request by nate-chandler**
Use `fflush(stdout)` from C++.

Issue 73252.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by eeckstein — APPROVED** [review]

**Comment by nate-chandler** [comment]
@swift-ci please test linux platform

**Comment by nate-chandler** [comment]
@swift-ci please test macos platform

**Comment by nate-chandler** [comment]
@swift-ci please smoke test macos platform

**Pull request merged**
