### PR TITLE
Extend _unsafeInheritExecutor_ to remaining @_unsafeInheritExecutor APIs

### PR DESCRIPTION
**Pull request by DougGregor**
Extend the _unsafeInheritExecutor_ workaround to all remaining APIs in the Concurrency library that have adopted `#isolation` default arguments to (safely) stay in the caller's isolation domain...

... except one. Clock.measure() is currently running into problems with the type checker workaround and needs a little more thought.

Fixes rdar://131760111.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Review by hborla — APPROVED** [review]

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Review by ktoso — APPROVED** [review]
Thank you! Lgtm

**Pull request merged**
