### PR TITLE
Revert "Don't import C++ class members that are protected or private"

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/swift#30233

This is breaking the windows bot

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC @CodaFi @gribozavr @maartenbode @shahmishal

**Comment by CodaFi** [comment]
Sorry about that extraneous failure. Getting it here: https://github.com/apple/swift/pull/30520

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by CodaFi** [comment]
@swift-ci test Windows

**Comment by compnerd** [comment]
@CodaFi any idea why Linux is failing on that test (which I thought should've been fixed by your change)

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by CodaFi** [comment]
The SHA linked in the failure didn't pick up [the real fix](https://github.com/apple/swift/commit/c56e7995901a57edc7e3bbd3cc0dc37b0762f41f). The one you picked up just unblocked Windows.

**Comment by CodaFi** [comment]
@swift-ci test Linux

**Comment by martinboehme** [comment]
Not sure what the status is here -- is there a more fundamental issue with this revert and does it make sense for me to submit a fix-forward PR?

**Comment by martinboehme** [comment]
@gribozavr says he thinks this revert is based on a bad commit and that that may be causing the issues, so I've created another revert:

https://github.com/apple/swift/pull/30528

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Pull request closed without merging**
