### PR TITLE
[Observation] Switch to peer instead of arbitrary macros

### PR DESCRIPTION
**Pull request by natecook1000**
This adopts `@attached(peer)` for generating an observable type's underscored storage when expanding the `@ObservationTracked` macro, instead of using `arbitrary` with the member macro on the observable type.

rdar://110327683

### CODE REVIEW

**Comment by natecook1000** [comment]
Tests are currently crashing with this error, even if only instantiating an `@Observable`-annotated type:

```
stderr>>> Assertion failed: (dependentIvars->Count == numFields), function initObjCClass, file Metadata.cpp, line 3396.
```

**Comment by natecook1000** [comment]
@swift-ci Please test

**Review by phausler — APPROVED** [review]
Provided we can alleviate the compiler crash, this seems correct to me

**Comment by hborla** [comment]
@swift-ci please test

**Comment by natecook1000** [comment]
@swift-ci Please test and merge

**Comment by natecook1000** [comment]
@swift-ci Please test and merge

**Pull request merged**
