### PR TITLE
[ConstraintSystem] Prefer disjunctions of bindings over other disjunc…

### PR DESCRIPTION
**Pull request by rudkx**
…tions.

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Review by xedin — APPROVED** [review]
LGTM! That's what I meant in the previous PR, it seems like disjunctions like that are generally useful to try early, maybe we should also include disjunctions which represent coercions here?

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
@xedin I think those disjunctions are pretty much always set up because of an explicit coercion in the source, right, so they might lead us to be able to attempt bindings for the first type appearing in the coercion (the type you're trying to coerce), but it won't lead to the sort of benefits we get from splitting the system.

I think I'd rather not add too much complexity here handling special cases.

Long term I think the right approach here would be to unify type variables and disjunctions in a way that allows us to have a single notion of a constraint variable, and then come up with some principled way to schedule the work of attempting options in the domain of each constraint variable (replacing the separate logic we have for getting "best" bindings and deferring certain ones in favor of trying disjunctions and this new "scheduling" logic for picking the best disjunction).

**Comment by xedin** [comment]
Yeah, that would be great!

**Pull request merged**
