### PR TITLE
Make build-script more scriptable

### PR DESCRIPTION
**Pull request by beccadax**
This PR modifies build-script so that some of its logic can be more easily used by other scripts. Specifically:

* Diagnostic notes are now printed on stderr instead of stdout so they can be more easily filtered.
* The `--expand-build-script-invocation` flag for presets now prints the command without a human-readable message before it. (Normal invocations still print it as a note with a human-readable prelude, but now on stderr.)
* A new `--print-build-dir` option stops execution right before it starts invoking tools and instead prints the full path to the build directory it was planning to use (e.g. `/Users/brent/src/build/Ninja-Release`). This allows other scripts to reuse build-script's logic for computing these paths.

### CODE REVIEW

**Comment by gottesmm** [comment]
While you are here a few thoughts:

1. I think the name expand-build-script-invocation is way too long and redundant. Why not while you are making this change rename it to expand-invocation or just expand.
2. Instead of creating a print-build-dir command (and then having a bunch of separate commands be added), why not just add a dump or dump-config or dump-machine-readable-config (not sure about the name.) that would dump a json file. Then we can just pipe everything through that.

**Comment by gottesmm** [comment]
Another thing is that expand-build-script-invocation command today seems to believe that it is taking a =0 or =1 command. Can you eliminate that as well? (No worries if you want to keep this small).

**Comment by brentdax** [comment]
Two additional commits:

1. Adds a preferred `--expand-invocation` argument. (I didn't want to delete the old one because I was worried it might appear in some CI script somewhere.)

2. Replace `--print-build-dir` with `--dump-config`, which recursively dumps all of the properties of the `BuildScriptInvocation` object as JSON. We might prefer to be more selective, but since this was less effort, I figured I'd try it first and see what you think.

<details>
<summary>Sample output</summary>

```
$ utils/build-script --release-debug --dump-config
{
  "args": {
    "benchmark_num_o_iterations": 3,
    "long_test": false,
    "cmake_c_launcher": null,
    "build_skstresstester": false,
    "extra_cmake_options": [],
    "build_toolchainbenchmarks": false,
    "test_osx": false,
    "test_tvos_host": false,
    "validation_test": null,
    "enable_stdlibcore_exclusivity_checking": false,
    "test_freebsd": false,
    "android_ndk": null,
    "build_swiftevolve": false,
    "build_osx": true,
    "build_swift_static_stdlib": false,
    "cmark_build_variant": "RelWithDebInfo",
    "build_tvos": true,
    "test_watchos_simulator": false,
    "cross_compile_hosts": [],
    "build_tvos_device": false,
    "symbols_package": null,
    "verbose_build": false,
    "build_script_impl_args": [],
    "test": null,
    "test_sourcekitlsp": false,
    "build_args": [],
    "swift_user_visible_version": {
      "components": [
        5,
        1
      ]
    },
    "build_swift_stdlib_unittest_extra": false,
    "foundation_build_variant": "RelWithDebInfo",
    "swift_assertions": true,
    "swift_compiler_version": null,
    "export_compile_commands": false,
    "build_cygwin": true,
    "darwin_deployment_version_tvos": "9.0",
    "install_destdir": "/Volumes/DocumentsHD/Code/open-swift/build/Ninja-RelWithDebInfoAssert/toolchain-macosx-x86_64",
    "build_tvos_simulator": false,
    "test_optimize_none_implicit_dynamic": null,
    "test_ios": false,
    "lto_type": null,
    "enable_sanitize_coverage": false,
    "darwin_deployment_version_ios": "7.0",
    "stdlib_deployment_targets": [
      "macosx-x86_64",
      "iphonesimulator-i386",
      "iphonesimulator-x86_64",
      "appletvsimulator-x86_64",
      "watchsimulator-i386",
      "iphoneos-armv7",
      "iphoneos-armv7s",
      "iphoneos-arm64",
      "appletvos-arm64",
      "watchos-armv7k"
    ],
    "build_swift_dynamic_sdk_overlay": true,
    "swift_analyze_code_coverage": "false",
    "llvm_assertions": true,
    "test_tvos_simulator": false,
    "install_prefix": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr",
    "cmark_assertions": true,
    "android_icu_uc": null,
    "enable_tsan_runtime": false,
    "ios_all": false,
    "build_libdispatch": false,
    "test_optimize_for_size": null,
    "build_freebsd": true,
    "build_linux": true,
    "build_watchos": true,
    "test_tvos": false,
    "build_subdir": "Ninja-RelWithDebInfoAssert",
    "lit_args": "-sv",
    "skip_build": false,
    "build_benchmarks": true,
    "host_cxx": null,
    "build_jobs": 8,
    "build_swift_dynamic_stdlib": true,
    "build_watchos_device": false,
    "llvm_build_variant": "RelWithDebInfo",
    "build_variant": "RelWithDebInfo",
    "cmake_generator": "Ninja",
    "enable_tsan": false,
    "llvm_targets_to_build": "X86;ARM;AArch64;PowerPC;SystemZ;Mips",
    "build_libicu": false,
    "test_watchos_host": false,
    "swift_tools_max_parallel_lto_link_jobs": 1,
    "build_ios_device": false,
    "assertions": true,
    "force_optimized_typechecker": false,
    "enable_lsan": false,
    "build_stdlib_deployment_targets": [
      "all"
    ],
    "build_android": false,
    "extra_swift_args": [],
    "build_libcxx": false,
    "test_watchos": false,
    "watchos": false,
    "llvm_max_parallel_lto_link_jobs": 2,
    "test_android_host": false,
    "build_external_benchmarks": false,
    "host_target": "macosx-x86_64",
    "swift_stdlib_assertions": true,
    "test_android": false,
    "android_deploy_device_path": "/data/local/tmp",
    "lldb_build_variant": "RelWithDebInfo",
    "build_runtime_with_host_compiler": false,
    "tsan_libdispatch_test": false,
    "disable_guaranteed_normal_arguments": false,
    "build_xctest": false,
    "benchmark": false,
    "test_indexstoredb": false,
    "show_sdks": false,
    "test_paths": [],
    "enable_ubsan": false,
    "benchmark_num_onone_iterations": 3,
    "android_icu_i18n": null,
    "test_optimized": null,
    "lldb_build_with_xcode": "0",
    "swift_stdlib_build_variant": "RelWithDebInfo",
    "coverage_db": null,
    "build_ninja": false,
    "build_libparser_only": false,
    "build_swiftsyntax": false,
    "build_watchos_simulator": false,
    "build_sourcekitlsp": false,
    "build_swiftpm": false,
    "clang_profile_instr_use": null,
    "test_cygwin": false,
    "tvos": false,
    "enable_asan": false,
    "android_icu_uc_include": null,
    "android_icu_i18n_include": null,
    "compiler_vendor": "none",
    "distcc": false,
    "libdispatch_build_variant": "RelWithDebInfo",
    "legacy_impl": false,
    "build_lldb": false,
    "host_libtool": null,
    "test_ios_host": false,
    "clang_compiler_version": null,
    "android_ndk_gcc_version": "4.9",
    "darwin_xcrun_toolchain": "default",
    "dry_run": false,
    "clang_user_visible_version": {
      "components": [
        7,
        0,
        0
      ]
    },
    "swift_build_variant": "RelWithDebInfo",
    "test_ios_simulator": false,
    "llbuild_assertions": true,
    "libicu_build_variant": "RelWithDebInfo",
    "dump_config": true,
    "android": false,
    "android_arch": "armv7",
    "build_playgroundsupport": false,
    "stress_test": false,
    "build_ios_simulator": false,
    "darwin_deployment_version_watchos": "2.0",
    "ios": false,
    "host_lipo": null,
    "host_test": false,
    "install_symroot": null,
    "build_foundation": false,
    "android_icu_data": null,
    "build_llbuild": false,
    "watchos_all": false,
    "android_api_level": "21",
    "test_ios_32bit_simulator": true,
    "darwin_deployment_version_osx": "10.9",
    "build_indexstoredb": false,
    "tvos_all": false,
    "build_ios": true,
    "lldb_assertions": true,
    "clean": false,
    "host_cc": null,
    "test_linux": false,
    "cmake": null,
    "cmake_cxx_launcher": null,
    "build_swift_static_sdk_overlay": false
  },
  "toolchain": {
    "cmake": "/Volumes/Xcode/Xcode.app/Contents/Developer/usr/local/bin/cmake",
    "xcrun_toolchain": "default",
    "cc": "/Volumes/Xcode/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang",
    "cxx": "/Volumes/Xcode/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++",
    "ninja": "/Volumes/Xcode/Xcode.app/Contents/Developer/usr/local/bin/ninja",
    "xcrun_sdk": "macosx"
  },
  "build_libparser_only": false,
  "workspace": {
    "source_root": "/Volumes/DocumentsHD/Code/open-swift",
    "build_root": "/Volumes/DocumentsHD/Code/open-swift/build/Ninja-RelWithDebInfoAssert"
  }
}
```
</details>

**Review by gottesmm — APPROVED** [review]
LGTM

**Comment by brentdax** [comment]
@swift-ci please smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by brentdax** [comment]
Ah, my old adversary, the Python linter.

**Comment by brentdax** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
