### PR TITLE
Windows stdlib improvements

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @hughbe

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please smoke test Linux platform

**Comment by hughbe** [comment]
Awesome! I haven't been able to figure out the module stuff yet so didn't realise I needed ucrt

**Pull request merged**
