### PR TITLE
[benchmark] Janitor Duty: Troublemaker Legacy

### PR DESCRIPTION
**Pull request by palimondo**
This PR follows-up  #20861, #21413, #21516, #21794, #22026 and #22296 in clean-up efforts to enable [robust performance measurements](https://forums.swift.org/t/towards-robust-performance-measurement/11490) by adjusting workloads to run in reasonable time (< 1000 μs), minimizing the accumulated error. To maintain long-term performance tracking, it applies [legacy factor](https://github.com/apple/swift/pull/20212) where necessary.

This one picks up on troublemakers skipped from #22026 and re-adds a few previously disabled benchmarks. Remember, there never were truly unstable benchmarks, it was our measurement methodology that was flawed before.

### CODE REVIEW

**Comment by palimondo** [comment]
@swift-ci Please benchmark

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
@swift-ci please smoke test

**Comment by palimondo** [comment]
@swift-ci please smoke test

**Comment by palimondo** [comment]
@eeckstein Please review 🙏

**Review by eeckstein — APPROVED** [review]

**Comment by palimondo** [comment]
@eeckstein Thanks!

**Pull request merged**
