### PR TITLE
[WIP]  [test] Switch %clang-importer-sdk over to using parseable interfaces

### PR DESCRIPTION
**Pull request by jrose-apple**
The mock SDK has mock overlays to go with its mock headers, and until now such overlays have always been manually compiled to swiftmodules or included via the old-and-broken -enable-source-import. Instead, we can use the new-and-exciting swiftinterface format to have them automatically compiled and cached each test run.

Still to fix:

- Move all the "-enable-source-import hackaround" manual compilers of overlays over to this.

- Dependency tracking is including the cached module files, which seems like a bad idea. (See test/Frontend/dependencies.swift.)

- We're definitely compiling the same swiftinterface with more than one configuration in the same compilation, and we need to not do that. (I suspect this is the difference between a top-level import and a recursive import.)

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
The high addition count is just from copying the existing mock overlay sources over and tweaking them to be valid/good swiftinterfaces.

**Comment by slavapestov** [comment]
Cool!

**Comment by jrose-apple** [comment]
I think this is still a lot slower than running the tests the normal way, and I need to find out why, but to check that it's not just my laptop…

@swift-ci Please test

**Comment by jrose-apple** [comment]
Confirmed slow. :-(

**Comment by CodaFi** [comment]
@jrose-apple Should we close this then?

**Comment by jrose-apple** [comment]
I think it's still desirable to get to a place where this works, because the current clang-importer-sdk mechanisms are a hack. But it's gonna have to be owned by someone other than me. I'll close it but leave the branch around.

**Pull request closed without merging**
