### PR TITLE
[stdlib] Adding derived equality/comparison operators to concrete integer types

### PR DESCRIPTION
**Pull request by moiseev**
... to aid constraint solver in some cases.
  
Resolves: rdar://problem/36113283
Resolves: [SR-6634](https://bugs.swift.org/browse/SR-6634)

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by moiseev** [comment]
@swift-ci Please smoke benchmark

**Review by xedin — COMMENTED** [review]
Thank you!

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by moiseev** [comment]
@swift-ci Please smoke test and merge

**Comment by moiseev** [comment]
@swift-ci Please smoke test and merge

**Pull request merged**
