### PR TITLE
IRGen: Freeze undef switch, select, cond_br arguments

### PR DESCRIPTION
**Pull request by aschwaighofer**
Let's make `cond_br undef : $Builtin.Int1, then, else` (and the like) a defined LLVM IR operation with un-specfied behavior.

rdar://126231554

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci test

**Comment by aschwaighofer** [comment]
Where did half of the patch go ...

**Review by atrick — APPROVED** [review]
Cool!

I don't really understand how the address case happens, but I guess we don't need to worry about it.

**Comment by aschwaighofer** [comment]
I don’t know that it does

**Comment by aschwaighofer** [comment]
@swift-ci test

**Pull request merged**
