### PR TITLE
[RemoteMirror] Add missing test.swift file for interop tests.

### PR DESCRIPTION
**Pull request by mikeash**

### CODE REVIEW

**Comment by mikeash** [comment]
@swift-ci please smoke test and merge

**Comment by rintaro** [comment]
@swift-ci please smoke test

**Comment by openloop** [comment]
You didn’t start this but why are all these magic numbers in tests? Almost every time I have written tests like this I have introduced flaky tests.

**Comment by mikeash** [comment]
Sorry, which magic numbers?

**Pull request merged**
