### PR TITLE
[SIL] NFC: Moved flag to SILExtInfo.

### PR DESCRIPTION
**Pull request by nate-chandler**
Previously the async flag was one of the bits of SILFunctionType.  Here it is moved into SILExtInfo.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test and merge

**Comment by nate-chandler** [comment]
@swift-ci please test and merge

**Comment by nate-chandler** [comment]
@swift-ci please test and merge

**Comment by nate-chandler** [comment]
@swift-ci please clean test

**Comment by nate-chandler** [comment]
@swift-ci please clean test

**Comment by nate-chandler** [comment]
@swift-ci please test and merge

**Comment by nate-chandler** [comment]
@swift-ci please test and merge

**Comment by varungandhi-apple** [comment]
Thank you!

**Pull request merged**
