### PR TITLE
build: shuffle `add_swift_target_library` (NFC)

### PR DESCRIPTION
**Pull request by compnerd**
This moves the `add_swift_target_library` into the stdlib level cmake
module directory.  This is used strictly for building the standard
library bits.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
CC: @xiaobai @gottesmm @drexin

**Comment by gottesmm** [comment]
Does this handle the swiftSwiftLang library? I am pretty sure that still uses this. That being said when I last hit this, I spoke with @harlanhaskins and he said that we can move that into a swiftpm based package build.

Then this is good to go.

**Comment by compnerd** [comment]
Interesting, Im definitely in favour of moving swiftSwiftLang into a swiftpm package.  That said, that will continue to work after this change, its just a code movement to shuffle the target specific logic into the target subdirectory.

**Comment by compnerd** [comment]
That concern has been alleviated.  For the time being `swift-lang` has been shuffled into `stdlib/tools`.  @nathawes will be look into moving that into swift-stress-tester as a follow up.

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by compnerd** [comment]
@swift-ci please clean test

**Review by drexin — APPROVED** [review]
LGTM

**Comment by lanza** [comment]
@compnerd This breaks the change you did from two weeks ago: https://github.com/apple/swift/commit/379137f6f1.

**Pull request merged**
