### PR TITLE
SE-0441: Add language-mode option with alias to swift-version

### PR DESCRIPTION
**Pull request by dempseyatgithub**
As part of the implementation of SE-0441, this PR adds a compiler option `language-mode' with an alias to the existing `swift-version` option.

### CODE REVIEW

**Comment by dempseyatgithub** [comment]
@swift-ci test

**Comment by xedin** [comment]
@dempseyatgithub could you please update a few tests to use new option so we can get some test coverage?

**Comment by dempseyatgithub** [comment]
@swift-ci test

**Comment by dempseyatgithub** [comment]
> @dempseyatgithub could you please update a few tests to use new option so we can get some test coverage?

@xedin I've added a few tests and the checks pass. I believe I've added the tests correctly.

**Comment by artemcm** [comment]
@dempseyatgithub could you please also open a PR to the swift-driver repo to update its options list according to:
https://github.com/swiftlang/swift-driver?tab=readme-ov-file#rebuilding-optionsswift

**Review by xedin — APPROVED** [review]
I'm going to tentatively approve this but let's merge this together with swift-driver changes @artemcm requested.

**Comment by dempseyatgithub** [comment]
> @dempseyatgithub could you please also open a PR to the swift-driver repo to update its options list according to: https://github.com/swiftlang/swift-driver?tab=readme-ov-file#rebuilding-optionsswift

I have opened a PR with this change: https://github.com/swiftlang/swift-driver/pull/1686.

Apologizes on having this taking so long, I seem to be a magnet for build issues.

**Comment by dempseyatgithub** [comment]
The swift-driver PR has passed its checks and been approved:
https://github.com/swiftlang/swift-driver/pull/1686

**Comment by xedin** [comment]
https://github.com/swiftlang/swift-driver/pull/1686
@swift-ci please build toolchain macOS

**Comment by xedin** [comment]
https://github.com/swiftlang/swift-driver/pull/1686
@swift-ci please test

**Comment by xedin** [comment]
https://github.com/swiftlang/swift-driver/pull/1686
@swift-ci please test source compatibility

**Comment by dempseyatgithub** [comment]
https://github.com/swiftlang/swift-driver/pull/1686
@swift-ci please build toolchain macOS

**Comment by dempseyatgithub** [comment]
The Swift Build Toolchain macOS Platform error seems to be a linking error that is not related to this change.

@xedin Would the best approach be to rebase on top of main again and run the tests again?

```
Undefined symbols for architecture arm64:
  "___isPlatformVersionAtLeast", referenced from:
      _$s20swift_willThrowTypeds19UTF8ValidationError33_03D0F4A7CE17AC628CBA43FDBE73E23FLLV_Tg5 in Swift.o
      _$ss26_stdlib_isOSVersionAtLeastyBi1_Bw_BwBwtF in Swift.o
      _$ss11AnySequenceV3mapySayqd__Gqd__xKXEKlFTm in Swift.o
      _$ss20_adHocPrint_unlocked___07isDebugC0yx_s6MirrorVq_zSbts16TextOutputStreamR_r0_lF13printTypeNameL_yyypXpsAER_r0_lF in Swift.o
      _$ss12validateUTF8ys0B16ValidationResultOSRys5UInt8VGF in Swift.o
      _$ss10repairUTF8_21firstKnownBrokenRangeSSSRys5UInt8VG_SnySiGtF in Swift.o
      _$ss12validateUTF8ys0B16ValidationResultOSRys5UInt8VGF4failL_yys0bC5Error33_03D0F4A7CE17AC628CBA43FDBE73E23FLLVYKF in Swift.o
      ...
ld: symbol(s) not found for architecture arm64
```

**Comment by xedin** [comment]
@dempseyatgithub CI always rebases PRs on top of main so there is no need to do that. I'll try to figure out what is going on with toolchain.

**Comment by xedin** [comment]
https://github.com/swiftlang/swift-driver/pull/1686
@swift-ci please clean build toolchain macOS

**Comment by xedin** [comment]
https://github.com/swiftlang/swift-driver/pull/1686
@swift-ci please build toolchain macOS

**Comment by xedin** [comment]
https://github.com/swiftlang/swift-driver/pull/1686
@swift-ci please build toolchain macOS

**Comment by xedin** [comment]
Tried with toolchain and it looks like everything works as expected! Thanks you, @dempseyatgithub!

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
Going to re-run smoke test just in case.

**Comment by dempseyatgithub** [comment]
> Going to re-run smoke test just in case.
> Tried with toolchain and it looks like everything works as expected! Thanks you, @dempseyatgithub!

You're welcome and thank you @xedin for all your help!

**Pull request merged**
