### PR TITLE
Don't leak writeback path components

### PR DESCRIPTION
**Pull request by rjmccall**
rdar://32083241

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci  Please smoke test and merge.

**Comment by jckarter** [comment]
Would a better fix be to make DiverseStack handle nontrivial components generally?

**Comment by jckarter** [comment]
This seems fine as a quick fix, though.

**Comment by rjmccall** [comment]
The reason I wanted to avoid handling nontrivial components is that the original use-case, cleanups, requires cleanups to be moved off the cleanup stack for reasons I can't remember, and you can't automatically generate a virtual move constructor the same you can automatically generate a virtual destructor.  (Although now I'm imagining totally different ways of achieving that goal.)

Or at least that's true in Clang, Swift's cleanup model is different enough that it might not be a problem.

**Comment by rjmccall** [comment]
@swift-ci Please smoke test and merge.

**Comment by rjmccall** [comment]
@swift-ci Please smoke test and merge.

**Comment by rjmccall** [comment]
@swift-ci Please smoke test Linux.

**Pull request merged**
