### PR TITLE
platform: add WIC (Windows Imaging Component) to the SDK

### PR DESCRIPTION
**Pull request by compnerd**
The Windows Imaging Component does not get included by any of the other
headers.  Explicitly add a submodule for the component.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @egorzhdan

**Review by egorzhdan — COMMENTED** [review]
I think this submodule requires linking against `Windowscodecs.lib` (I didn't check the capitalization 🙂)
https://docs.microsoft.com/en-us/windows/win32/api/wincodec/nf-wincodec-wicconvertbitmapsource#requirements

**Comment by compnerd** [comment]
Ah, thanks, I was looking to figure out the import library for this, but looking at some of the interfaces for it, didn't happen to come across it.

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Pull request merged**
