### PR TITLE
[build] disable failing Android cross-compilation test on macOS

### PR DESCRIPTION
**Pull request by finagolfin**
@shahmishal, this should disable the test failure you saw because of #33724, please let me know if it doesn't.

### CODE REVIEW

**Comment by shahmishal** [comment]
Unfortunately, also seeing the test failing on Intel system too. 
```
Swift(macosx-x86_64) :: BuildSystem/android_cross_compile.test
```

**Comment by buttaface** [comment]
Huh, it passed the Mac CI, so it should work there.

**Comment by buttaface** [comment]
Updated to disable on Intel macOS too.

**Comment by shahmishal** [comment]
@buttaface thanks!

**Pull request merged**
