### PR TITLE
Revert "[4.1] Stricter enforcement of the "large space" heuristic"

### PR DESCRIPTION
**Pull request by xedin**
Reverts apple/swift#13438

This PR caused some projects to fail the build. I will try to come up with reduced test-case and re-open the JIRA.

### CODE REVIEW

**Comment by CodaFi** [comment]
I think I know what these projects might be... all the same the source compatibility break should be discussed because this is a case where the old code demonstrably allows malformed code through to SILGen.

**Comment by rudkx** [comment]
@CodaFi Malformed in the sense that we're not always diagnosing not-fully-covered switches, or in some other sense?

**Comment by CodaFi** [comment]
In the sense that SILGen currently inserts a pessimistic fatalError default branch that causes surprises to say the least.  It’s not a full miscompile in that sense but it’s still undefined behavior.

**Comment by rudkx** [comment]
I'm not seeing a fatalError inserted in the original test case from https://bugs.swift.org/browse/SR-6316, but I do see a crash if the code is optimized. It's not great behavior 

Let's back this out of 4.1 for the moment and then discuss in https://bugs.swift.org/browse/SR-6652 whether we should adjust the heuristic for when it bails out.

**Pull request merged**
