### PR TITLE
[validation-test] XFAILing a few stdlibunittest validation tests on watchos

### PR DESCRIPTION
**Pull request by moiseev**
rdar://problem/29996991&29997033&29997073&29997111

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please smoke test and merge

**Comment by shahmishal** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
@swift-ci Please test macOS platform

**Comment by moiseev** [comment]
@swift-ci Please test macOS platform

**Comment by moiseev** [comment]
@swift-ci Please test

**Pull request merged**
