### PR TITLE
[WIP] Check the containing context when checking access for operators

### PR DESCRIPTION
**Pull request by jrose-apple**
This might help eliminate operators from overload sets sooner, if they weren't supposed to be accessed from the current context at all. Or it might not make any noticeable difference. Builds on #18048.

No functionality change; the tests added did not change behavior.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test compiler performance

**Comment by jrose-apple** [comment]
@swift-ci Please test compiler performance

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test compiler performance

**Comment by jrose-apple** [comment]
```
20:41:14 
/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swiftpm/Sources/SPMLLBuild/llbuild.swift:13:19: error: module file was created by a newer version of the compiler: /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/llbuild-macosx-x86_64/products/llbuildSwift/llbuildSwift.swiftmodule
20:41:14 @_exported import llbuildSwift
20:41:14                   ^
```

@aciidb0mb3r, @shahmishal, do we need to clean out the build directory here?

**Comment by aciidb0mb3r** [comment]
hmmm, I think we need to make sure llbuild rebuilds the Swift bindings when Swift compiler binary changes.

**Comment by aciidb0mb3r** [comment]
I'll try to fix that today. Cleaning should work in the meantime.

**Comment by shahmishal** [comment]
@jrose-apple workspace cleaned, please start testing again.

**Comment by jrose-apple** [comment]
Well, the patch does have other bugs anyway, so I'll hold off here. But hopefully it's fixed things for others.

**Comment by CodaFi** [comment]
@jrose-apple seems like the refactoring parts have been accomplished in other PRs.  Is there a bug fix here that we should take as well, or should this be closed?

**Comment by jrose-apple** [comment]
Indeed, I'm not sure what's salvageable from here. It's been a long time.

**Pull request closed without merging**
