### PR TITLE
[test] Fix Driver tests not to write to PWD (a shared directory)

### PR DESCRIPTION
**Pull request by jrose-apple**
Hopefully fixes some of the weird failures we're seeing in rdar://problem/42247881, though I'm not sure how it would be responsible for some of them.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by CodaFi** [comment]
Could you elaborate on "weird failures" for me?

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
We're seeing one or two Driver tests a week fail with "can't open file" and then a perfectly reasonable path with a correct expanded %t prefix. It's always tests in Driver/, but not necessarily the same one. This PR is the result of protecting %t/../.. from writes and seeing what fails, but I still don't see how that could cause those non-deterministic errors.

**Comment by jrose-apple** [comment]
@swift-ci Please test macOS

**Review by CodaFi — APPROVED** [review]
LGTM.  Hope you figure this out soon.

**Pull request merged**
