### PR TITLE
[SwiftSyntax] Add SyntaxFactory.makeEllipsisToken function.

### PR DESCRIPTION
**Pull request by bannzai**
## What
- Add `ellipsis` token for **gyb_syntax_support** python script. So, It will add `SyntaxFactory.makeEllipsisToken` function.
- Add test case of function parameter with `ellipsis` pattern.

## Reference
Resolves [SR-9797](https://bugs.swift.org/browse/SR-9797) and [SR-9710](https://bugs.swift.org/browse/SR-9710).

### CODE REVIEW

**Comment by rintaro** [comment]
Hi @bannzai, Welcome to the project!

I think it's a good thing to add "Ellipsis" token kind.
But we have to make the parser to parse them as `tok::ellipsis` token too. (Currently, they are parsed as `tok::oper_postfix` or `tok::oper_infix`.)
Could you change the Parser as well? I *think* all you have to do are:

*  insert:
   ```swift
   Tok.setKind(tok::ellipsis);
   ```
   before this line:
   https://github.com/apple/swift/blob/f479276d61b028d7c65cebf49bdce19ff6553417/lib/Parse/ParsePattern.cpp#L364

* Change this line:
https://github.com/apple/swift/blob/f479276d61b028d7c65cebf49bdce19ff6553417/utils/gyb_syntax_support/DeclNodes.py#L338-L339
   to:
   ```python
             Child('Ellipsis', kind='Ellipsis',
                   is_optional=True),
   ```

I believe this change fixes https://bugs.swift.org/browse/SR-9710 as well. So please add a test for that.

**Comment by bannzai** [comment]
@rintaro thank you your reviews and advice for next action!
I wrote test about [that advice](https://github.com/apple/swift/pull/22214#issuecomment-460477484) and fixed it.

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Review by rintaro — APPROVED** [review]

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
Thank you Yudai!

**Comment by bannzai** [comment]
@rintaro 

Ok! I changed issues status to `done` and I assigned myself.
Thank you for your reviews!

- https://bugs.swift.org/browse/SR-9797
- https://bugs.swift.org/browse/SR-9710

**Pull request merged**
