### PR TITLE
Revert "[IRGen] Use the lexical decl context for VarDecls."

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/swift#33306

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by 3405691582** [comment]
Sorry; do I need to create a new PR to include the fix?

**Comment by compnerd** [comment]
@3405691582 oh, you already have a fix?  in that case, could you please create a PR?  we should get that merged instead.

**Comment by 3405691582** [comment]
Added a PR to fix forward; I can cherry pick in the linked PR and recommit on that PR if that's preferred.

**Comment by compnerd** [comment]
Superseded by #33816

**Pull request closed without merging**
