### PR TITLE
Stats output dir filename issues

### PR DESCRIPTION
**Pull request by graydon**
Principal fix here is to only use the basename of a path when mangling input names into stats-dir
output filenames, so that we are much less likely to hit a path-name limit and drop a stats output
on the floor (this was happening in practice in CI).

Secondary fix is just a harmless-but-silly typo I noticed while in there.

### CODE REVIEW

**Comment by graydon** [comment]
@swift-ci please test and merge

**Comment by graydon** [comment]
@swift-ci please test Linux platform

**Comment by graydon** [comment]
@swift-ci please clean test Linux platform

**Review by jrose-apple — COMMENTED** [review]
LGTM, saw you're adding a test.

**Pull request merged**
