### PR TITLE
build: remove the last unversioned python reference

### PR DESCRIPTION
**Pull request by compnerd**
Explicitly use versioned python interpreters for tools.  This replaces
the last unversioned reference.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test android platform

**Comment by compnerd** [comment]
CC: @drexin @RLovelett @drodriguez

**Comment by drodriguez** [comment]
Give me until tonight to install Python 3 in the build machines. I will merge this when I am done.

Those two, however, I don't think they get executed in CI, so unless CMake fails trying to find values, it might interpolate to nothing, but since CI should not execute those lines, it might be fine.

> @swift-ci please test android platform

Ha ha. I wish that was working.

**Comment by drodriguez** [comment]
Seems to work OK, and I check `python3` is in the path, so I hope CMake is finding the right one.

There was a problem with `line-directive` in the file `stdlib/private/SwiftPrivateLibcExtras/Subprocess.swift`, where a `’` appears in a comment. I changed it to the ASCII `'` and no problem. If the problem appears in CI, I will know what to change.

Thanks for moving Python 3 forward!

**Pull request merged**
