### PR TITLE
[stdlib] Audit @_transparent/@inlinable in Integers.swift

### PR DESCRIPTION
**Pull request by moiseev**

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please benchmark

**Comment by moiseev** [comment]
`Join` benchmark is consistently ~40% slower in `-O` builds... 🤔

**Comment by airspeedswift** [comment]
I think we should land this for ABI purposes and address that regression on master. @eeckstein any concerns? I don't think `joined` performance is critical on a non-release branch.

**Comment by eeckstein** [comment]
That's interesting, because Join is a string benchmark.
Fine with me to merge. Please file a bug for the regression.

**Pull request merged**
