### PR TITLE
[di] Update DI/Capture Promotion so that we do not need to run mark uninitialized mixup.

### PR DESCRIPTION
**Pull request by gottesmm**
Title says it all. All but the last commit are in a different PR and are NFC commits. I am going to commit this after that lands.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test windows platform

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@atrick as promised = ).

**Comment by gottesmm** [comment]
Retesting!

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
For future reference, the cleanup PR is this: #28915.

**Review by atrick — APPROVED** [review]
Awesome! Thanks.

**Comment by atrick** [comment]
@gottesmm reminder: remove the MarkUninitializedFixup.cpp file!

**Comment by gottesmm** [comment]
Once this lands, I will remove it.

**Comment by gottesmm** [comment]
@atrick #28981

**Pull request merged**
