### PR TITLE
When building stdlib, pass -prespecialize-generic-metadata from CMake, and respect the flag in IRGenModule::shouldPrespecializeGenericMetadata

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by nate-chandler — APPROVED** [review]
LGTM.  Thank you!

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Was there a reason that Windows wasn't included in the default?

**Comment by kubamracek** [comment]
> Was there a reason that Windows wasn't included in the default?

Hey! No particular reason - but I think the old behavior (before the change) was that prespecialization was already disabled on Windows? See the condition in IRGenModule::shouldPrespecializeGenericMetadata.

**Pull request merged**
