### PR TITLE
Replace concrete init(stringInterpolationSegment:)'s with generic ones

### PR DESCRIPTION
**Pull request by DougGregor**
Remove 16 concrete `init(stringInterpolationSegment:)` overloads and
replace them with 3 generic overloads, significantly reducing the
exponential blow-up from larger string interpolations.

Fixes rdar://problem/29389887.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please benchmark

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by dabrahams** [comment]
Nice!  Why didn't it work out when *I* tried to do this?  Did it require a compiler fix?

**Comment by DougGregor** [comment]
Well, we're still waiting for benchmark results. IIRC, you removed the concrete versions but didn't put in the generic overloads like I did. 

I did not touch the compiler, although I did come across an opportunity for improvement there, too.

**Pull request merged**
