### PR TITLE
Add LLDB Linux preset (69382424)

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
preset=linux_lldb
@swift-ci Please test with preset Linux

**Review by JDevlieghere — APPROVED** [review]

**Comment by shahmishal** [comment]
LLDB tests ran into timeout.

```
********************
Testing:  0.. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90..Build timed out (after 83 minutes). Marking the build as failed.
```
https://ci.swift.org/job/swift-PR-Linux-preset/83/

@JDevlieghere, is this known issue?

**Comment by JDevlieghere** [comment]
> LLDB tests ran into timeout.
> @JDevlieghere, is this known issue?

Not known to me. CC @adrian-prantl as he's our current build wrangler and might have seen it.

**Comment by JDevlieghere** [comment]
preset=linux_lldb
@swift-ci Please test with preset Linux

**Comment by shahmishal** [comment]
@JDevlieghere @adrian-prantl It's failing on baseline CI job: https://ci.swift.org/view/LLDB/job/oss-lldb-incremental-linux-ubuntu-16_04/14450/console

This is not new issue.

**Comment by shahmishal** [comment]
@swift-ci smoke test and merge

**Pull request merged**
