### PR TITLE
Pull PointerLikeTypeTraits<DeclName> up to Identifier.h

### PR DESCRIPTION
**Pull request by jrose-apple**
General cleanup, no functionality change.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by shahmishal** [comment]
FYI - CI is currently down for planned maintenance.

**Comment by gottesmm** [comment]
@swift-ci Please test

**Comment by gottesmm** [comment]
Playground failure isn't Jordan.

**Pull request merged**
