### PR TITLE
Revert "Add path remapping with -coverage-prefix-map to coverage data"

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/swift#32175

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @keith @vedantk - seems that the CI didn't trigger on the request (CC: @shahmishal)

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by keith** [comment]
I assume the issue here is relying on `$PWD` in the tests, working on a fix

**Comment by compnerd** [comment]
Assuming #32434 works, lets go with that instead of this.

**Pull request closed without merging**
