### PR TITLE
IRGen: Enable update of extended frame pointer entry on x86_64

### PR DESCRIPTION
**Pull request by aschwaighofer**
So far this was only enabled on arm64. Let's see whether the x86_64 backend can handle it.

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test os x platform

**Comment by kastiglione** [comment]
Note there's a comment that should be updated:

https://github.com/apple/swift/blob/b7ace9eee7c94e68c5ef7f0d602faf3613982425/lib/IRGen/GenFunc.cpp#L2424-L2425

**Comment by aschwaighofer** [comment]
@swift-ci Please test windows

**Comment by aschwaighofer** [comment]
@swift-ci Please test windows

**Comment by aschwaighofer** [comment]
@swift-ci Please test windows

**Comment by fredriss** [comment]
@aschwaighofer we need this landed ASAP and in the next submission.

**Pull request merged**
