### PR TITLE
Revert "Create one undef node per type to avoid failures in graph creation."

### PR DESCRIPTION
**Pull request by bgogul**
Reverts apple/swift#18288

It looks like cached undef nodes become stale somehow.

### CODE REVIEW

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Review by rxwei — APPROVED** [review]
Please run a clean test to verify that it fixed CI. Thanks!

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by shahmishal** [comment]
@swift-ci Please clean test tensorflow

**Pull request merged**
