### PR TITLE
Don't delete allocations in DCE

### PR DESCRIPTION
**Pull request by meg-gupta**
DCE was deleting an allocation with only destroy_value users. This isn't correct when the deinit can have a side effect. This should be handled in DeadObjectElimination which does additional analysis on deinit to determine if a dead allocation can be eliminated.

### CODE REVIEW

**Comment by meg-gupta** [comment]
Fixes issue reported in https://github.com/apple/swift/issues/73768

**Comment by meg-gupta** [comment]
@swift-ci test

**Review by atrick — APPROVED** [review]
LGTM. Could you add a comment and CHECK lines to the test?

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Comment by turbolent** [comment]
Thank you for the quick fix @meg-gupta 🙏

**Pull request merged**
