### PR TITLE
[CSSimplify] Bind for-in patterns to holes if element type is `Any`

### PR DESCRIPTION
**Pull request by xedin**
If the element type is `Any` i.e. `for (x, y) in [] { ... }`
it would never match the pattern and the pattern 
(`rhs` = `(x, y)`) doesn't have any other source of 
contextual information, so instead of waiting for elements 
to become holes with an unrelated fixes, let's proactively 
bind all of the pattern elements to holes.

Resolves:  rdar://100343275

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Review by hborla — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Pull request merged**
