### PR TITLE
[SR-5814] removes dead code around REFLECT_OBJC_IVARS

### PR DESCRIPTION
**Pull request by glenna**
Removes the `REFLECT_OBJC_IVARS` define and the associated code in `Reflection.mm` as it's been unused for years.

Resolves [SR-5814](https://bugs.swift.org/browse/SR-5814).

### CODE REVIEW

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test

**Comment by gottesmm** [comment]
@harlanhaskins For the mirror work, @bitjammer may be good as well.

**Comment by gottesmm** [comment]
Also, @glenna welcome!

**Comment by harlanhaskins** [comment]
@Glenna Glad to see your PR after the workshop! 😃

**Pull request merged**
