### PR TITLE
[AutoDiff] Fix `autodiff_function` instruction worklist.

### PR DESCRIPTION
**Pull request by dan-zheng**
Fix `autodiff_function` instruction worklist registration/invalidation.

- In `VJPEmitter`, add cloned `autodiff_function` instructions in VJP
  to worklist.
- If `autodiff_function` instructions are deleted in
  `foldAutoDiffFunctionExtraction`, also remove their worklist occurrences.

Resolves [TF-515](https://bugs.swift.org/projects/TF/issues/TF-515).

---

Writing a reproducer test is difficult because the nature of the bug is ad-hoc.
Verified that `swift test` works for https://github.com/tensorflow/swift-models/commit/f9687bf4c3e2f23ede458229c49e880ac30d7cbb.

### CODE REVIEW

**Comment by rxwei** [comment]
In `Differentiation::run()`, all `autodiff_function` instructions in a module are pushed to the work list. Could you please explain why it is necessary to push more in `VJPEmitter::visitAutoDiffFunctionInst`?

**Comment by dan-zheng** [comment]
> In `Differentiation::run()`, all `autodiff_function` instructions in a module are pushed to the work list. Could you please explain why it is necessary to push more in `VJPEmitter::visitAutoDiffFunctionInst`?

If an original function has an `autodiff_function` instruction, it will be pushed to the worklist.
However, when `VJPEmitter` clones it into a VJP function, the cloned `autodiff_function` instructions needs to be manually added to the worklist.

Otherwise, the cloned `autodiff_function` instructions in the VJP won't be processed, leading to verification errors:
```
Assertion `!getAssociatedFunctions().empty() && "No associated functions. Maybe " "the differentiation pass has not run?"'
```

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by rxwei** [comment]
It's a little unfortunate that while the cloned `autodiff_function` is an exact copy of the original, it has to go through `emitAssociatiedFunctionReference` twice.

**Review by rxwei — APPROVED** [review]

**Comment by dan-zheng** [comment]
> It's a little unfortunate that while the cloned `autodiff_function` is an exact copy of the original, it has to go through `emitAssociatiedFunctionReference` twice.

Yeah, that is true.

**Pull request merged**
