### PR TITLE
Consolidate circularity checks for recursive validateDecl() calls

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@DougGregor check out 'Sema: Give synthesized ParamDecls an interface type'

**Comment by practicalswift** [comment]
Seven crashers fixed – nice! 👍

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Pull request merged**
