### PR TITLE
Enable SE-0422 Expression macro as caller-side default argument

### PR DESCRIPTION
**Pull request by ApolloZhu**
This feature has been accepted

### CODE REVIEW

**Comment by ApolloZhu** [comment]
@swift-ci please smoke test

**Comment by ApolloZhu** [comment]
@swift-ci please smoke test

**Review by DougGregor — APPROVED** [review]

**Comment by rxwei** [comment]
@swift-ci please test windows

**Comment by ApolloZhu** [comment]
@swift-ci please test windows

**Pull request merged**
