### PR TITLE
[gardening] Fix typos

### PR DESCRIPTION
**Pull request by practicalswift**

### CODE REVIEW

**Comment by CodaFi** [comment]
[While you're in the neighborhood](https://github.com/CodaFi/swift/blob/master/lib/Sema/CSSimplify.cpp#L1178).

**Comment by practicalswift** [comment]
@CodaFi Thanks! Added :-)

**Comment by practicalswift** [comment]
@swift-ci please smoke check and merge

**Comment by practicalswift** [comment]
@swift-ci please smoke test and merge

**Comment by practicalswift** [comment]
@swift-ci please test and merge

**Comment by CodaFi** [comment]
Merge failed.  We'll do it live.

⛵️

**Pull request merged**
