### PR TITLE
SIL Optimizer: Don't run mandatory inlining on deserialized functions

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Review by atrick — APPROVED** [review]
This is a good change. In theory, it should not affect performance.

**Comment by compnerd** [comment]
Hmm, should this address the recent faults that I have been seeing with the deserialization in the ` Mandatory Inlining` pass?

**Comment by atrick** [comment]
@compnerd MandatoryInlining will still deserialize methods of callees that need to be inlined. It just doesn't need to look at callers that were already serialized. The errors you were running into are likely fixed by one of @slavapestov's other PRs.

**Comment by slavapestov** [comment]
@compnerd @atrick I'm not aware of my PRs fixing any bugs, but it's possible it hides existing issues since we just deserialize less. If you build with -O it should deserialize exactly what was getting deserialized before. Do you have a test case?

**Comment by atrick** [comment]
It's common for a SIL linking or deserialization bug to show up as:
While running pass #xxx  SILModuleTransform "MandatoryInlining".

That could still be the case after this PR, but it shouldn't be as likely.

**Pull request merged**
