### PR TITLE
Cherry-pick Bitstream API changes to use llvm::Error

### PR DESCRIPTION
**Pull request by francisvm**
Swift side of changes for https://github.com/apple/llvm-project/pull/239.

### CODE REVIEW

**Comment by francisvm** [comment]
Please test with following pull request:
https://github.com/apple/llvm-project/pull/239

@swift-ci please test

**Comment by francisvm** [comment]
Please test with following pull request:
https://github.com/apple/llvm-project/pull/239

@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci please test linux

**Comment by francisvm** [comment]
Dropping this PR in the same way as https://github.com/apple/llvm-project/pull/239.

**Pull request closed without merging**
