### PR TITLE
[AutoDiff upstream] Add flag-gated `AdditiveArithmetic` derivation.

### PR DESCRIPTION
**Pull request by dan-zheng**
Add `AdditiveArithmetic` derived conformances for structs, gated by the
`-enable-experimential-additive-arithmetic-derivation` flag.

[Swift Evolution pitch thread.](https://forums.swift.org/t/additivearithmetic-conformance-synthesis-for-structs/26159)

Structs whose stored properties all conform to `AdditiveArithmetic` can derive
`AdditiveArithmetic`:
- `static var zero: Self`
- `static func +(lhs: Self, rhs: Self) -> Self`
- `static func -(lhs: Self, rhs: Self) -> Self`
- An "effective memberwise initializer":
  - Either a synthesized memberwise initializer or a user-defined initializer
    with the same type.

Effective memberwise initializers are used only by derived conformances for
`Self`-returning protocol requirements like `AdditiveArithmetic.+`, which
require memberwise initialization.

Resolves TF-844.
Unblocks TF-845: upstream `Differentiable` derived conformances.

---

Example:
```swift
struct Vector2: AdditiveArithmetic {
  var x, y: Float

  // Compiler synthesizes:
  //
  // static var zero: Self {
  //   return Self(x: Float.zero, y: Float.zero)
  // }
  //
  // static func +(lhs: Self, rhs: Self) -> Self {
  //   return Self(x: lhs.x + rhs.x, y: lhs.y + rhs.y)
  // }
  //
  // static func -(lhs: Self, rhs: Self) -> Self {
  //   return Self(x: lhs.x - rhs.x, y: lhs.y - rhs.y)
  // }
}
```

One unimplemented pitch idea is [requiring an explicit `@memberwise` attribute](https://forums.swift.org/t/additivearithmetic-conformance-synthesis-for-structs/26159/14?u=dan-zheng)
on `AdditiveArithmetic` conformances to show that derivation is memberwise:

```swift
struct Vector2: @memberwise AdditiveArithmetic { ... }
```

Explicit `@memberwise` annotation is nice because memberwise `AdditiveArithmetic`
derivation does not make sense for some types:

```swift
// Memberwise derivation doesn't make sense here, so we don't want derivation to
// silently happen without explicit `@memberwise` annotation.
struct Fraction: AdditiveArithmetic {
  var numerator, denominator: Int
}
```

If general `AdditiveArithmetic` derivation is controversial, we can limit
derivation to `TangentVector` member structs synthesized during `Differentiable`
derived conformances, which is the use case we care about.

### CODE REVIEW

**Comment by dan-zheng** [comment]
@CodaFi: would you like to review this patch, as a derived conformances code owner?

Our use case for `AdditiveArithmetic` derived conformances is [differentiable programming](https://github.com/apple/swift/blob/master/docs/DifferentiableProgramming.md#compiler-synthesized-conformances). We've been incubating `AdditiveArithmetic` derived conformances on the `tensorflow` branch since 2018 - it should be pretty stable.

---

I think a controversial change is introducing “effective memberwise initializers”, which are necessary for synthesizing `Self`-returning protocol requirements:
```swift
struct Vector2: AdditiveArithmetic {
  var x, y: Float

  // Compiler synthesizes:
  //
  // static var zero: Self {
  //   return Self(x: Float.zero, y: Float.zero)
  //          ^~~~
  //          memberwise initializer is necessary for derivation
  // }
  // ...
}
```

Synthesized memberwise initializers are also public for public types whose stored properties are all public. This breaks Swift precedent, where synthesized struct memberwise initializers are at most internal.

However, it's important for supporting use cases like TF-1077: memberwise initializers for public synthesized types (e.g. [`TangentVector` member types](https://github.com/apple/swift/blob/master/docs/DifferentiableProgramming.md#compiler-synthesized-conformances)) should be public because manually declaring public memberwise initializers for these types produces a redeclaration error.

---

Feedback on the [`AdditiveArithmetic` derivation pitch thread](https://forums.swift.org/t/additivearithmetic-conformance-synthesis-for-structs/26159) is mixed, so I'm not sure it can pass Evolution.

However, since `AdditiveArithmetic` derivation exists to support differentiable programming, we can limit `AdditiveArithmetic` derivation specifically for `TangentVector` member structs synthesized during `Differentiable` derived conformances. This seems less controversial, to support [upstreaming differentiable programming](https://forums.swift.org/t/trajectory-for-evaluating-adding-automatic-differentiation-to-swift/30048).

**Comment by dan-zheng** [comment]
@swift-ci Please test

**Comment by dan-zheng** [comment]
@swift-ci Please smoke test

**Comment by dan-zheng** [comment]
@swift-ci Please smoke test

**Review by rxwei — APPROVED** [review]

**Comment by dan-zheng** [comment]
@swift-ci Please smoke test

**Comment by dan-zheng** [comment]
Merging to unblock progress. Happy to address feedback later!

**Pull request merged**
