### PR TITLE
[DebuggerSupport] Expose a way to query the reference counts.

### PR DESCRIPTION
**Pull request by dcci**
lldb will use it to reimplement `language swift refcount <obj>`
which is currently not working. Asking the compiler allows us
to avoid maintinaing a bunch of information in the debugger which
are likely to change and break.

<rdar://problem/30538363>

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by dcci** [comment]
@swift-ci please test

**Comment by dcci** [comment]
For those interested/reading, eventually we might want to expose this information through remote mirrors.

**Comment by dcci** [comment]
This test passes locally on Linux, as expected, so let's give this another shot:
```
~/work$ ./build/Ninja-RelWithDebInfoAssert/swift-linux-x86_64/test-linux-x86_64/stdlib/Output/DebuggerSupport.swift.tmp/a.out  --stdlib-unittest-in-process --stdlib-unittest-filter "Basic"
StdlibUnittest: using filter: Basic
StringForPrintObject: All tests passed
[ RUN      ] RefCount.Basic
[       OK ] RefCount.Basic
RefCount: All tests passed
```

**Comment by dcci** [comment]
@swift-ci please test

**Comment by dcci** [comment]
@swift-ci test

**Review by mikeash — COMMENTED** [review]
LGTM!

**Comment by dcci** [comment]
@swift-ci test linux

**Comment by dcci** [comment]
@swift-ci test linux

**Comment by dcci** [comment]
@swift-ci test and merge

**Comment by dcci** [comment]
@swift-ci test and merge

**Pull request merged**
