### PR TITLE
Fixes missing Xcode "Quick Help" for enum values as switch case patterns

### PR DESCRIPTION
**Pull request by johnno1962**
Fix for bugreporter problem: #24431424 "Swift enum values used in case statements not indexed"

In Xcode, if you select an enum value as the pattern for a switch statement “Quick Help” is not available as the USR for the enum is not currently recorded in SourceKit’s tree traversal. This change picks up the missing one case where an enum value is being used as the pattern and makes sure it is returned in the "cursor info" and "index source” data.

e.g.

public enum E {

```
case one, two, three

var text: String {
    switch self {
    case .one:
        return "one"
    case .two:
        return "two"
    case .three:
        return "three"
    }
}
```

}

Without this fix, If you select the .one in the switch it will not show Quick Help as it is not seen in SourceKit’s AST traversal.

Tested by building the 2.2 branch, preparing a toolchain and launching Xcode with it loaded, building “eidolon” OSS application and running it.

With the fix it is possible to get “Quick Help” to see where enums in switch cases are defined and also use right-click “Find Selected Symbol in Workspace” to get a complete list of the places the enum value is used as the index db is fully populated. The intended use for this fix is to make sure the index db is complete to aid in Refactoring.

### CODE REVIEW

**Comment by johnno1962** [comment]
The intended use for this fix is to make sure the index db is complete to aid in Refactoring.

**Comment by tkremenek** [comment]
@johnno1962 Thanks for the patch.  Please provide a test case to regression test this.

**Comment by johnno1962** [comment]
Test commited. Is this what you meant?

**Comment by tkremenek** [comment]
@johnno1962 Yes, exactly.  Thank you!

**Comment by tkremenek** [comment]
@swift-ci Please test

**Comment by johnno1962** [comment]
Thanks @tkremenek. What would you like me to do with the main branch. The code is slightly different so I recommend I just open a separate pull request. Would that be ok?

**Comment by tkremenek** [comment]
@johnno1962 Please do a separate pull request.  Thanks!

**Comment by johnno1962** [comment]
Done. https://github.com/apple/swift/pull/1209

**Comment by johnno1962** [comment]
Thanks @tkremenek, any chance you could mention bugerport #24432660 "Swift Type references in protocol extensions not indexed correctly” to the Xcode team. Looks like a simple fix to include “source.lang.swift.decl.extension.protocol” in the nodes processed from SourceKit to produce the project index. Otherwise no USR references inside protocol extensions are included in the index. This will make "Find Selected Symbol in Workspace” work correctly with a view to eventually implementing refactoring.

**Pull request merged**
