### PR TITLE
Fixes example snippet in SetAlgebra.swift

### PR DESCRIPTION
**Pull request by valeriyvan**
Fixes example snippet in SetAlgebra.swift

### CODE REVIEW

**Comment by xwu** [comment]
@swift-ci smoke test

**Comment by CodaFi** [comment]
@swift-ci smoke test macOS

**Comment by CodaFi** [comment]
@swift-ci smoke test macOS

**Review by natecook1000 — APPROVED** [review]
:shipit:

**Comment by CodaFi** [comment]
Aha, it seems like this change isn't so benign after all. You will have to go fixup the result of `SourceKit/DocSupport/doc_clang_module.swift`.

**Comment by xwu** [comment]
🤯

**Comment by CodaFi** [comment]
Superseded

**Pull request closed without merging**
