### PR TITLE
[AutoDiff] Fix adjoint propagation for active bb address arguments

### PR DESCRIPTION
**Pull request by asl**
Ensure they are accumulated in the proper buffer.

Fixes second case of SR-16094

### CODE REVIEW

**Comment by asl** [comment]
Tagging @rxwei @BradLarson

**Review by rxwei — APPROVED** [review]

**Comment by rxwei** [comment]
@swift-ci please test and merge

**Comment by asl** [comment]
@rxwei will you please ping CI again?

**Comment by rxwei** [comment]
@swift-ci please test

**Comment by asl** [comment]
@BradLarson @rxwei Looks like main was broken, will you please ping CI again? Thanks!

**Comment by rxwei** [comment]
@swift-ci please test

**Pull request merged**
