### PR TITLE
[IRGen] Set minimum runtime availability version for CVW

### PR DESCRIPTION
**Pull request by drexin**
rdar://139375022

CVW should not be generated when the deployment target does not have the necessary runtime functions.

### CODE REVIEW

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@swift-ci smoke test

**Review by tshortli — APPROVED** [review]

**Review by rjmccall — COMMENTED** [review]
LGTM.  We'll have to remember to actually update the OS versions that provide Swift 6.1 when they're released.

**Comment by drexin** [comment]
@swift-ci smoke test

**Pull request merged**
