### PR TITLE
[stdlib] implement _fastCStringContents

### PR DESCRIPTION
**Pull request by dabrahams**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

David Smith suggested this optimization.  Thanks, David!

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please test and merge

**Comment by Catfish-Man** [comment]
Have a fix for that. Testing it now (didn't have a working build environment until a few minutes ago, sorry!).

**Comment by gribozavr** [comment]
Please add tests.

**Comment by gottesmm** [comment]
What ever happened to this?

**Comment by dabrahams** [comment]
@gottesmm As you can probably see, I never got around to adding the tests Dmitri requested, and it failed the already-existing tests.  Please feel free to pick this up and carry the ball across the goal line.

**Comment by gottesmm** [comment]
@dabrahams Ok. I was just going through old radars and was pinging this.

**Comment by dabrahams** [comment]
@Catfish-Man we still need tests before we can merge this.  Care to try?

**Comment by dabrahams** [comment]
It's not clear we can do anything here without inspecting the system encoding and making sure what we store is compatible with it.
cc: @airspeedswift

**Pull request closed without merging**
