### PR TITLE
[stdlib] Added RISCV64 support

### PR DESCRIPTION
**Pull request by colemancda**
Added support to cross-compile the StdLib for RISCV64.

Resolves [SR-16005](https://bugs.swift.org/browse/SR-16005).

### CODE REVIEW

**Comment by colemancda** [comment]
@buttaface this is an updated PR of https://github.com/apple/swift/pull/41858

**Comment by colemancda** [comment]
Here is a working compiler to test 5.6 with RISCV
https://github.com/MillerTechnologyPeru/swift/releases/tag/swift-5.6-RC1-RISCV

Swift patches
https://gist.github.com/colemancda/a6112d449b76eddf12dfa46e260bfca0
https://gist.github.com/colemancda/bab5a634176b53f0f8c76d6ab5eec578
https://gist.github.com/colemancda/840a1d6e2029c31f899a91e503c2364b

Buildroot
https://gist.github.com/colemancda/2716a33bc87b518a83a46ac520d412f1
https://gist.github.com/colemancda/94ab66fbf49f93748c8d7f7e11d8b8ce
https://gist.github.com/colemancda/83e681b53807e7f82517ec3b32d40cd3

**Comment by buttaface** [comment]
I would like to see Swift on RISC-V but I have not been able to buy any decent hardware, as I don't want to try running Swift on a microcontroller and the more powerful dev boards are always unavailable. I still don't think adding RISC-V to the LLVM targets in the linux buildbot preset is needed, as it should be there already, but I haven't checked.

@CodaFi, would you review?

**Comment by colemancda** [comment]
@buttaface  I still don't think adding RISC-V to the LLVM targets in the linux buildbot preset is needed, as it should be there already, but I haven't checked.
I tried without changing the preset, its not there. You can also check the CI logs.

https://ci.swift.org/job/swift-PR-Linux/861/consoleFull

```
+ env /home/build-user/build/cmake-linux-x86_64/bin/cmake -G Ninja -DCMAKE_C_COMPILER:PATH=/usr/bin/clang -DCMAKE_CXX_COMPILER:PATH=/usr/bin/clang++ -DCMAKE_Swift_COMPILER:PATH= -DCMAKE_LIBTOOL:PATH= -DCMAKE_AR:PATH=/usr/bin/ar -DCMAKE_RANLIB:PATH=/usr/bin/ranlib -DLLVM_VERSION_MAJOR:STRING=13 -DLLVM_VERSION_MINOR:STRING=0 -DLLVM_VERSION_PATCH:STRING=0 -DCLANG_VERSION_MAJOR:STRING=13 -DCLANG_VERSION_MINOR:STRING=0 -DCLANG_VERSION_PATCH:STRING=0 -DCMAKE_MAKE_PROGRAM=/home/build-user/build/buildbot_linux/ninja-build/ninja -DLLVM_ENABLE_ASSERTIONS:BOOL=TRUE '-DLLVM_TARGETS_TO_BUILD=X86;ARM;AArch64;PowerPC;SystemZ;Mips' '-DCMAKE_C_FLAGS=  -Wno-unknown-warning-option -Werror=unguarded-availability-new -fno-stack-protector' '-DCMAKE_CXX_FLAGS=  -Wno-unknown-warning-option -Werror=unguarded-availability-new -fno-stack-protector' '-DCMAKE_C_FLAGS_RELWITHDEBINFO=-O2 -DNDEBUG' '-DCMAKE_CXX_FLAGS_RELWITHDEBINFO=-O2 -DNDEBUG' -DCMAKE_BUILD_TYPE:STRING=Release -DLLVM_TOOL_SWIFT_BUILD:BOOL=NO -DLLVM_TOOL_LLD_BUILD:BOOL=TRUE -DLLVM_INCLUDE_DOCS:BOOL=TRUE -DLLVM_ENABLE_LTO:STRING= -DCOMPILER_RT_INTERCEPT_LIBDISPATCH=ON -DLLVM_TOOL_COMPILER_RT_BUILD:BOOL=TRUE -DLLVM_BUILD_EXTERNAL_COMPILER_RT:BOOL=TRUE '-DLLVM_LIT_ARGS=-v --time-tests -j 36' -DCMAKE_INSTALL_PREFIX:PATH=/usr/ -DINTERNAL_INSTALL_PREFIX=local '-DLLVM_ENABLE_PROJECTS=clang;compiler-rt;clang-tools-extra;lld' /home/build-user/llvm-project/llvm
~/build/buildbot_linux/llvm-linux-x86_64 ~
```

**Comment by buttaface** [comment]
> its not there. You can also check the CI logs.

I know we don't pass that flag, the question is whether it is built by default by LLVM when we don't specify the targets.

**Comment by colemancda** [comment]
I got the main changes merged in https://github.com/apple/swift/pull/61815 and moved the build preset changes to https://github.com/apple/swift/pull/61891

**Pull request closed without merging**
