### PR TITLE
[Backtracing] Add an option to output to stderr.

### PR DESCRIPTION
**Pull request by al45tair**
In CI, it would be better if the backtraces went to stderr rather than stdout, so provide an option for that.

rdar://107192120

### CODE REVIEW

**Comment by al45tair** [comment]
Original is at #64611

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
@swift-ci Please test

**Review by mikeash — APPROVED** [review]

**Review by ktoso — APPROVED** [review]

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
Explanation: Adds an option to control whether backtracer output goes to stdout or stderr.
Risk: Low. Only affects the backtracer, which only kicks in when things crash. Has been on main for a while now.
Original PR: https://github.com/apple/swift/pull/64611
Reviewed by: @ktoso, @mikeash 
Resolves: rdar://107192120
Tests: The backtracer has tests that exercise this option (it's always passed through, no matter what the setting is).

**Review by airspeedswift — APPROVED** [review]

**Pull request merged**
