### PR TITLE
[ClangImporter][ModuleWrap] Turn off libc warnings.

### PR DESCRIPTION
**Pull request by al45tair**
`swift-modulewrap` uses the `ClangImporter` to obtain a module loader, but it doesn't take an SDK argument (nor does anything bother to pass one), which means that when cross-compiling you get warnings about not being able to find the C library.

Suppress the warning by telling the `ClangImporter` that we don't care about the C library here.

rdar://115918181

### CODE REVIEW

**Comment by al45tair** [comment]
@swift-ci Please test

**Review by egorzhdan — COMMENTED** [review]
Does modulewrap need to access Swift symbols that are imported from C/C++? e.g. if the Swift module exposes a C struct in its public interface.

If not, this LGTM.

**Comment by al45tair** [comment]
Hmmm. Maybe I should make it try to set up the file mapping and just not fail the same way, rather than turning it off completely. (I'm not _sure_ whether it might need C/C++ symbols; it plainly doesn't for the things I've tried with the Static SDK, and I think this problem happens for other cross-compilation situations too, but I'm not confident enough that I'm entirely comfortable.)

**Comment by al45tair** [comment]
@swift-ci Please test

**Review by egorzhdan — APPROVED** [review]
This looks reasonable to me, thanks!

**Comment by al45tair** [comment]
@swift-ci Please smoke test macOS platform

**Pull request merged**
