### PR TITLE
build: use `add_dependencies` and inline single use

### PR DESCRIPTION
**Pull request by compnerd**
A couple of sites used `add_dependencies_multiple_targets` for a single
target.  Use `add_dependencies` instead.  This is clearer and reduces
the configuration time as arguments do not need to be processed.  The
`add_dependencies_multiple_targets` had 1 remaining usage.  Simply
inline the expansion to the two targets.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @Rostepher @edymtt @xiaobai

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by compnerd** [comment]
This is going to have a slight amount after the `_add_swift_host_library_single` and `_add_swift_target_library_single` split.

**Pull request closed without merging**
