### PR TITLE
[build-script] Argument Builder DSL Conversion: Episode 2

### PR DESCRIPTION
**Pull request by Rostepher**
# Purpose

This PR is the second part of #13117 and similarly doesn't contain any real functional changes. I've only converted the rest of the argument groups (ignoring the top level options) to the new builder DSL. All the unit-tests still pass which makes me confident that this PR is low risk.

Ignore the first 8 commits, they are from #13117.

rdar://34336890

### CODE REVIEW

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by Rostepher** [comment]
@swift-ci please smoke test

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by Rostepher** [comment]
@swift-ci please smoke test

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by Rostepher** [comment]
@swift-ci please smoke test

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by Rostepher** [comment]
@swift-ci please smoke test

**Comment by Rostepher** [comment]
@swift-ci please test Linux

**Comment by Rostepher** [comment]
@swift-ci please smoke test Linux

**Review by zisko — APPROVED** [review]
LGTM

**Pull request merged**
