### PR TITLE
Fix ownership of select_enum instruction

### PR DESCRIPTION
**Pull request by atrick**
This instruction was given forwarding ownership in the original OSSA implementation. That will obviously lead to memory leaks. Remove ownership from this instruction and verify that it is never used for non-trivial types.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test

**Review by eeckstein — APPROVED** [review]
lgtm.
I'm wondering if we should remove select_enum at all, for the same reasons @meg-gupta did with select_value.

**Comment by eeckstein** [comment]
Right, there are 2 places in SILGen where select_enum is generated. We could replace it with a utility function (which creates switch_enum). It would allow us to remove `IRGenSILFunction::visitSelectEnumInst`. The same for select_enum_addr.

**Comment by atrick** [comment]
> Right, there are 2 places in SILGen where select_enum is generated. We could replace it with a utility function (which creates switch_enum). It would allow us to remove `IRGenSILFunction::visitSelectEnumInst`. The same for select_enum_addr.

I'm in favor of removing select_enum. I noticed it was in active use and didn't want to experiment further at the moment.

**Pull request merged**
