### PR TITLE
Merge 2020-06-30 into tensorflow

### PR DESCRIPTION
**Pull request by texasmichelle**

### CODE REVIEW

**Comment by texasmichelle** [comment]
Please test with following PRs:
apple/llvm-project#1399

@swift-ci Please clean test TensorFlow

**Comment by texasmichelle** [comment]
@swift-ci please test Linux platform

**Comment by texasmichelle** [comment]
@swift-ci Please clean test TensorFlow

**Comment by texasmichelle** [comment]
@swift-ci Please clean test TensorFlow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Pull request merged**
