### PR TITLE
[NoncopyablePartialConsumption] Promote to feature.

### PR DESCRIPTION
**Pull request by nate-chandler**
Fully enable partial consumption of noncopyable values, fixing a couple of bugs exposed by doing so along the way.

rdar://126715654

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by jckarter — APPROVED** [review]

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Pull request merged**
