### PR TITLE
[5.9][move-only] Ban partial reinitialization after consuming a value.

### PR DESCRIPTION
**Pull request by gottesmm**
• Description: [5.9][move-only] Ban partial reinitialization after consuming a value. The language impact of this is that we want to be sure that partially reinitializing after consuming a value, results in an error:

```swift
struct X : ~Copyable { var i = 5, var i2 = Klass() }
var x = X()
_ = consume x
x.i = 5 // Error! Can only fully init
```
The reason why we want to do this is that the original proposal said values were never partially initialized. We already have banned partial consumption, but we realized that this was another way to create a partially alive value. Given that, we want to go through a round of forum discussion at least before we put this out there. This closes the hole in the mean time.
• Risk: This is low risk since it only affects a corner case in a specific part of the noncopyable checker. So it cannot affect anything but noncopyable code.
• Original PR: https://github.com/apple/swift/pull/67145
• Reviewed By: @jckarter
• Testing: Added Swift tests
• Resolves: rdar://111498740

### CODE REVIEW

**Comment by gottesmm** [comment]
Original:  #67145

**Comment by gottesmm** [comment]
@swift-ci test

**Review by jckarter — APPROVED** [review]
This looks good. There's a decent amount of new code, but it's in service to the new diagnostic, so it should be self-contained. We do want this diagnostic so we don't end up having to support code that does partial initializations before we hammer the semantics out.

**Comment by gottesmm** [comment]
@swift-ci test

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
