### PR TITLE
[CodeCompletion] Resolve witnesses when conformance in different file to avoid dups

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
Resolves [SR-7225](https://bugs.swift.org/browse/SR-7225).

### CODE REVIEW

**Comment by benlangmuir** [comment]
I'm probably not the right person to review this; @DougGregor or @slavapestov, could you take a look?

**Comment by jrose-apple** [comment]
Doug's actually out right now, so it may be a few days.

**Comment by AnthonyLatsis** [comment]
@DougGregor, have a couple of minutes?

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Review by DougGregor — APPROVED** [review]
Yeah, LGTM. This is the current correct way to perform filtering.

**Comment by AnthonyLatsis** [comment]
⛵️

**Comment by AnthonyLatsis** [comment]
Thanks, Anna.

**Pull request merged**
