### PR TITLE
[stdlib] add overflow checks for some pointer arithmetic

### PR DESCRIPTION
**Pull request by glessard**
- Pointer arithmetic uses operations that can overflow.
- This adds overflow checks added for recent additions to pointer arithmetic (rounding and property pointers).
- The basic `advanced(by:)` functions will be dealt with separately.

### CODE REVIEW

**Comment by glessard** [comment]
@swift-ci please benchmark

**Comment by glessard** [comment]
As expected, these changes have no real effect on current benchmarks:

### Performance (x86_64): -O

**Regression**  | **OLD** | **NEW** | **DELTA** | **RATIO**
:---            | ---: | ---: | ---:   | ---:     
FlattenListLoop | 1001 | 1623 | +62.1% | **0.62x (?)**

### Code size: -O


### Performance (x86_64): -Osize

**Regression**              | **OLD** | **NEW** | **DELTA** | **RATIO**
:---                        | ---: | ---: | ---:   | ---:     
FlattenListFlatMap          | 3020 | 4350 | +44.0% | **0.69x (?)**
&nbsp; | | | | 
**Improvement**             | **OLD** | **NEW** | **DELTA** | **RATIO**
SequenceAlgosRange          | 2390 | 2170 | -9.2%  | **1.10x (?)**
SequenceAlgosArray          | 2400 | 2180 | -9.2%  | **1.10x (?)**
DictionaryKeysContainsCocoa | 15   | 14   | -6.7%  | **1.07x (?)**

### Code size: -Osize


### Performance (x86_64): -Onone


### Code size: -swiftlibs



<details>
  <summary><strong>How to read the data</strong></summary>
The tables contain differences in performance which are larger than 8% and
differences in code size which are larger than 1%.

If you see any unexpected regressions, you should consider fixing the
regressions before you merge the PR.

**Noise**: Sometimes the performance results (not code size!) contain false
alarms. Unexpected regressions which are marked with '(?)' are probably noise.
If you see regressions which you cannot explain you can try to run the
benchmarks again. If regressions still show up, please consult with the
performance team (@eeckstein).
</details>

<details>
  <summary><strong>Hardware Overview</strong></summary>

      Model Name: Mac mini
      Model Identifier: Macmini8,1
      Processor Name: 6-Core Intel Core i7
      Processor Speed: 3.2 GHz
      Number of Processors: 1
      Total Number of Cores: 6
      L2 Cache (per Core): 256 KB
      L3 Cache: 12 MB
      Memory: 32 GB

</details>

**Comment by glessard** [comment]
@swift-ci please test

**Comment by glessard** [comment]
@swift-ci please test

**Review by Catfish-Man — APPROVED** [review]
Looks good to me, I appreciate the thorough tests

**Pull request merged**
