### PR TITLE
SILGen: Use ManagedValue variant of createAllocRefDynamic(), NFC

### PR DESCRIPTION
**Pull request by slavapestov**
Also, enable the SIL ownership verifier for test/SILGen/objc_protocols.swift.

### CODE REVIEW

**Comment by slavapestov** [comment]
@gottesmm The ManagedValue variant of allocRefDynamic() already existed, so it was just a matter of using it in the right place.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Review by gottesmm — APPROVED** [review]
LGTM

**Pull request merged**
