### PR TITLE
Bridge Parser Diagnostics into the C++ Diagnostic Engine

### PR DESCRIPTION
**Pull request by CodaFi**
Add a hook so the Swift parser can emit diagnostics that go through the normal diagnostics engine.

### CODE REVIEW

**Comment by CodaFi** [comment]
apple/swift-syntax#976

@swift-ci test

**Review by ahoppen — APPROVED** [review]

**Comment by CodaFi** [comment]
@swift-ci smoke test macOS

**Comment by CodaFi** [comment]
https://github.com/apple/swift-syntax/pull/976

@swift-ci smoke test macOS

**Review by DougGregor — APPROVED** [review]

**Comment by CodaFi** [comment]
I'll pull the round-trip failures into the hook in a follow-up.

**Pull request merged**
