### PR TITLE
Revert "[AutoDiff] Fix custom derivative thunk for Optional"

### PR DESCRIPTION
**Pull request by MaxDesiatov**
Reverts apple/swift#71721

Fixes `preset=buildbot,tools=RA,stdlib=DA` CI job, which without this revert fails on `AutoDiff/SILGen/nil_coalescing.swift` test.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
cc @asavonic @asl

**Comment by MaxDesiatov** [comment]
preset=buildbot,tools=RA,stdlib=DA
@swift-ci test with preset macOS

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Comment by asl** [comment]
@MaxDesiatov will you please post a link to failed CI job? This would help with triaging and fixing.

**Comment by MaxDesiatov** [comment]
See https://ci.swift.org/job/oss-swift_tools-RA_stdlib-DA_test-simulators/4385/console

**Comment by asl** [comment]
Ok, thanks. Looks like the test overly-optimistic matches expected code that in fact is inlined from stdlib.

**Pull request merged**
