### PR TITLE
[astgen] Address comments post-commit.

### PR DESCRIPTION
**Pull request by zoecarver**
I didn't want to address them in the last couple of PRs so that I wouldn't have to rebase everything, re-run the bots, etc.

I don't think I missed anything, but let me know if I did and I'll happily create another PR :)

### CODE REVIEW

**Comment by zoecarver** [comment]
@swift-ci please smoke test and merge

**Comment by zoecarver** [comment]
@swift-ci please smoke test and merge

**Review by AnthonyLatsis — APPROVED** [review]
You can merge incremental PRs without rebasing if they branch off of one another? TIL

**Comment by zoecarver** [comment]
> You can merge incremental PRs without rebasing if they branch off of one another? TIL

Yeah, as long as they don't change anything, I guess 🤷

**Review by CodaFi — APPROVED** [review]

**Comment by zoecarver** [comment]
@swift-ci please smoke test macOS platform

**Comment by zoecarver** [comment]
@swift-ci please smoke test macOS platform

**Pull request merged**
