### PR TITLE
[requires-evolution] Conditionally compiled catch clauses

### PR DESCRIPTION
**Pull request by owenv**
This is based on https://github.com/apple/swift/pull/27776, so only the last 2 commits are relevant. It's a WIP for now because I broke code completion (again), but everything else is working so I plan on pitching this on the forums shortly.

This change makes the following legal:

```swift
do {
  try performTask()
}
#if os(macOS)
catch TaskError.macOSOnlyError {
  macOSRecovery()
}
#endif
catch { 
  crossPlatformRecovery()
}

```

### CODE REVIEW

**Comment by owenv** [comment]
This is passing the regular test suite locally now. If anyone sees this I'd be interested in seeing how it fares on the source compatibility suite

**Comment by theblixguy** [comment]
Can you fix the merge conflict? We can run a source compat test after that

**Comment by theblixguy** [comment]
@swift-ci please test source compatibility

**Comment by theblixguy** [comment]
@swift-ci please test source compatibility

**Comment by owenv** [comment]
Hmm, looks like a couple of failures but nothing too bad. Thanks @theblixguy!

**Comment by owenv** [comment]
Let's see if this works

@swift-ci please test

**Comment by owenv** [comment]
For my own future reference: https://github.com/apple/swift-syntax/pull/190 and https://github.com/apple/llvm-project/pull/538 contain the LLDB and swift-syntax changes needed to build a working toolchain.

**Comment by owenv** [comment]
@DougGregor do you mind kicking off a toolchain build with the two PRs I linked in the comment above? I've tested this locally and was able to build a working macOS toolchain.

**Comment by xedin** [comment]
@swift-ci please build toolchain

**Comment by theblixguy** [comment]
apple/swift-syntax#190
apple/llvm-project#538

@swift-ci please build toolchain

**Comment by xedin** [comment]
Ugh, thanks @theblixguy! I totally missed previous comment...

**Comment by owenv** [comment]
Closing because conditional compilation was dropped from the final proposal

**Pull request closed without merging**
