### PR TITLE
[4.0] [Clang importer] Move the "all properties" lists into the name importer.

### PR DESCRIPTION
**Pull request by DougGregor**
Swift's ASTContext contained all of the logic to find the complete list
of properties for an Objective-C class, which is used by the Clang importer
to influence the mapping of Objective-C names into Swift. Swift's
ASTContext also included a *cache* for this information, indexed by
the Clang `ObjCInterfaceDecl *`. However, this cache was getting
populated/queried from the Clang importer's name importer, such that
the keys would be Clang declarations used to build modules and then
deallocated. If that memory eventually gets reused for a different
`ObjCInterfaceDecl *`, we would get incorrect/stale all-properties
information.

Almost Surely fixes rdar://problem/35347167, which is a
nondeterministic failure where UIView's `addGestureRecognizer(_:)` gets
occasionally imported as `add(_:)`.

(cherry picked from commit a49455e3b23d8f91580b6282a146e4a800ae5265)

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Review by slavapestov — APPROVED** [review]

**Comment by DougGregor** [comment]
@swift-ci please test macOS

**Comment by DougGregor** [comment]
@swift-ci please test macOS

**Comment by DougGregor** [comment]
@swift-ci please nominate

––– CCC Information –––
• Explanation: Eliminate a rare, nondeterministic failure where `UIView`'s `addGestureRecognizer(_:)` would get imported as `add(_:)` due to a cache based on a stale pointer. Could certainly affect other imports, but this seems to be the most common.
• Scope of Issue: Affects random projects at random times, then disappears with a rebuild.
• Origination: Swift 3 "grand renaming" Clang importer heuristics.
• Risk: Minimal
• Testing: CI bots

**Pull request merged**
