### PR TITLE
[Sema] Emit a deprecation warning if a Hashable type only implements hashValue

### PR DESCRIPTION
**Pull request by lorentey**
SE-206 deprecated `hashValue` as a protocol requirement. We should gently encourage people to migrate to `hash(into:)`, for its more secure, easier and faster hashing.

Emit a compiler warning whenever `hashValue` has an explicit implementation, but `hash(into:)` doesn’t.

rdar://problem/39838478

(This was originally part of #20685)

### CODE REVIEW

**Comment by lorentey** [comment]
Note: The warning location currently isn't set correctly when the hashValue implementation comes from a protocol extension. 

The PR below works around this, as well as reducing the sheer volume of Error-related warnings.

https://github.com/apple/swift/pull/21056
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
cc @natecook1000 for the documentation changes. (We don't have a good way to deprecate protocol requirements, so we have to point out the deprecation in the docs instead.)

**Review by natecook1000 — COMMENTED** [review]
Tiny change, otherwise LGTM. Thanks!

**Review by jrose-apple — APPROVED** [review]

**Pull request merged**
