### PR TITLE
[rebranch][test] Quote assembly generated for Windows

### PR DESCRIPTION
**Pull request by bnbarham**

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
... not sure what happened to my tests here 🤔 

@swift-ci please test

**Review by compnerd — APPROVED** [review]
Thanks for fixing this!

**Comment by bnbarham** [comment]
Failures unrelated, windows success is what we're after 👍

**Pull request merged**
