### PR TITLE
Sema: Check availability of key path components

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes <https://bugs.swift.org/browse/SR-7406> / <rdar://problem/39319212>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test

**Review by jrose-apple — APPROVED** [review]

**Comment by slavapestov** [comment]
This has been failing sporadically, it's not me:

```
[TestSwiftStepping.py FAILED]
```

Source compat failure is from @davezarzycki's reference type changes.

**Pull request merged**
