### PR TITLE
Merge 2020-10-28 into tensorflow

### PR DESCRIPTION
**Pull request by texasmichelle**

### CODE REVIEW

**Comment by texasmichelle** [comment]
Please test with following PRs:
apple/llvm-project#2056

@swift-ci Please clean test TensorFlow

**Comment by texasmichelle** [comment]
@swift-ci Please clean test TensorFlow

**Comment by texasmichelle** [comment]
@swift-ci Please clean test TensorFlow

**Comment by compnerd** [comment]
I can't seem to reproduce the test failure locally.

**Comment by texasmichelle** [comment]
I can't reproduce, either.

**Comment by texasmichelle** [comment]
@swift-ci Please clean test TensorFlow

**Review by dabrahams — APPROVED** [review]
ship it!

**Review by BradLarson — APPROVED** [review]

**Pull request merged**
