### PR TITLE
[ScanDependency] Set context hash for source module

### PR DESCRIPTION
**Pull request by cachemeifyoucan**
Set context hash for source module so swift-driver can use the hash to compute output path if needed.

rdar://119202702

### CODE REVIEW

**Comment by cachemeifyoucan** [comment]
This is the scanning change to support https://github.com/apple/swift-driver/pull/1567

**Comment by cachemeifyoucan** [comment]
@swift-ci please smoke test

**Comment by cachemeifyoucan** [comment]
@swift-ci please smoke test linux platform

**Review by artemcm — APPROVED** [review]

**Comment by cachemeifyoucan** [comment]
@swift-ci please smoke test linux platform

**Pull request merged**
