### PR TITLE
[IRGen] Use generic value witnesses for prespecialized types.

### PR DESCRIPTION
**Pull request by nate-chandler**
Previously, specialized value witnesses were emitted and used in the prespecialized value witness table corresponding to and pointed to by the prespecialized metadata for a generic type whose metadata was prespecialized. That incurs a codesize cost. Here, the generic value witnesses are used instead.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci Please test Apple Silicon macOS Platform

**Comment by nate-chandler** [comment]
@swift-ci Please test compiler performance

**Comment by nate-chandler** [comment]
@swift-ci Please test Apple Silicon macOS Platform

**Comment by nate-chandler** [comment]
@swift-ci Please test macOS Platform

**Comment by nate-chandler** [comment]
@swift-ci Please test compiler performance

**Comment by nate-chandler** [comment]
@swift-ci Please test compiler performance

**Comment by nate-chandler** [comment]
@swift-ci Please test macOS Platform

**Comment by nate-chandler** [comment]
@swift-ci Please test macOS Platform

**Comment by nate-chandler** [comment]
@swift-ci Please test compiler performance

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please clean test macos

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please clean test windows

**Comment by nate-chandler** [comment]
@swift-ci please clean test windows platform

**Comment by nate-chandler** [comment]
@swift-ci please clean test linux platform

**Comment by nate-chandler** [comment]
@swift-ci please clean test windows platform

**Comment by nate-chandler** [comment]
@swift-ci please clean test windows platform

**Review by aschwaighofer — APPROVED** [review]

**Pull request merged**
