### PR TITLE
[Executors] Make move to ExecutorJob binary compatible; deprecate Job

### PR DESCRIPTION
**Pull request by ktoso**
In https://github.com/apple/swift/pull/65038 we renamed Job to ExecutorJob and introduced a typealias. We knew this would be binary breaking however we hoped the change would not cause problems since noone had adopted this new API yet -- we were wrong.

This change introduces a binary compatible way to introduce `ExecutorJob` while keeping `Job` as deprecated and hopefully we'd be able to remove it still.

Diagnostics were adjusted to handle the new type and push developers towards the right implementation method.

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Review by xedin — APPROVED** [review]
LGTM! Please format your changes with clang-format before merging.

**Comment by ktoso** [comment]
rdar://108772378

**Review by NRC1978 — COMMENTED** [review]
Nothing really compares to you

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Pull request merged**
