### PR TITLE
Add "REQUIRES: asserts" to SourceKit crashes with that requirement.

### PR DESCRIPTION
**Pull request by practicalswift**

### CODE REVIEW

**Comment by gribozavr** [comment]
@practicalswift Why do you think these are necessary?  The testsuite is passing as it is now with `./utils/build-script -RT --no-assertions`.  What build mode are you using?

**Comment by practicalswift** [comment]
@gribozavr Sorry, I'm probably just confused about when the marking should be used.

Take `validation-test/IDE/crashers/002-swift-diagnosticengine-emitdiagnostic.swift` as an example. It triggers an assertion failure:

```
$ swift-ide-test -code-completion -code-completion-token=A -source-filename=validation-test/IDE/crashers/002-swift-diagnosticengine-emitdiagnostic.swift 2>&1 | egrep 'Assertion .* failed'
swift-ide-test: /root/build-swift/llvm/include/llvm/Support/Casting.h:95: static bool llvm::isa_impl_cl<swift::ParenType, const swift::TypeBase *>::doit(const From *) [To = swift::ParenType, From = const swift::TypeBase *]: Assertion `Val && "isa<> used on a null pointer"' failed.
````

Should it be marked as `// REQUIRES: asserts`? :-)

**Comment by gribozavr** [comment]
@practicalswift It should be annotated only if a `--no-assertions` build does not crash due to other reasons.

**Comment by practicalswift** [comment]
@gribozavr OK, got it! Closing this issue :-)

**Pull request closed without merging**
