### PR TITLE
[Test] Adapt DebugInfo/async-args for arm64e.

### PR DESCRIPTION
**Pull request by nate-chandler**

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by adrian-prantl — APPROVED** [review]
Thanks for taking care of this. The test is going to change once more very soon. I'll try to test all targets then.

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test windows platform

**Comment by nate-chandler** [comment]
@swift-ci please test windows platform

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test linux platform

**Pull request merged**
