### PR TITLE
[Concurrency/Runtime] Implement function/continuation type generation…

### PR DESCRIPTION
**Pull request by xedin**
… for `AsyncSignature`

`AsyncFunctionTypeImpl` has its `type` defaulted to `TaskContinuationFunction`
which is incorrect because it has to append arguments, result type and account
for throws bit.

These changes expand `AsyncSignature` with `ContinuationType` and expand `FunctionType`
to include all of the appropriate information.

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please clean test

**Review by rjmccall — APPROVED** [review]
LGTM, thanks!

**Comment by xedin** [comment]
@swift-ci please smoke test Linux platform

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Pull request merged**
