### PR TITLE
Revert [SE-0283] Implement Equatable, Comparable, and Hashable conformance for Tuples

### PR DESCRIPTION
**Pull request by Azoy**
Hopefully I did this right...

### CODE REVIEW

**Comment by Azoy** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
Thanks! Sorry for the back-and-forth.

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by tbkka** [comment]
Force-merging to get the revert in place, though someone will have to puzzle out the failures here.

**Pull request merged**
