### PR TITLE
[CMake] Replace swift component installation with CMake built-ins

### PR DESCRIPTION
**Pull request by bulbazord**
The current state of things is that install rules for a target, file,
or directory are only created if the component they are associated with
is being installed. However, CMake has the notion of components
associated with installation.

This commit's intent is not to get rid of the swift component system,
but rather remove some custom support code built in favor of using
CMake's built-in support.

My approach from a high level is to create install targets for each of the components using LLVM's `add_llvm_install_targets`, and then use the `COMPONENT` argument of `install` to track what gets installed with each component. I've made targets that get installed with a component depend on the actual component target itself to ensure it is built when we go to install it. This patch also changes the install target from `install` to `install-components` because we now unconditionally create install rules. The purpose of the `install-components` target is to install only the components specified in `SWIFT_INSTALL_COMPONENTS`. One benefit of this approach is that you do not need to reconfigure if you want to change which components you want to install. If you want to install $component for testing purposes (or some other reason), you can use the `install-$component` target directly.

### CODE REVIEW

**Comment by xiaobai** [comment]
cc @compnerd @gottesmm

**Comment by compnerd** [comment]
CC: @Rostepher

**Comment by xiaobai** [comment]
I think I will break this into smaller changes so it's a bit easier to review. I'll submit a PR for the first part soon.

**Comment by compnerd** [comment]
This has been merged piecemeal.

**Pull request closed without merging**
