### PR TITLE
[Experiment] Free ASTContext on separate thread

### PR DESCRIPTION
**Pull request by hamishknight**

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test compiler performance

**Comment by hamishknight** [comment]
@swift-ci please test compiler performance

**Comment by slavapestov** [comment]
Why?

**Comment by hamishknight** [comment]
@slavapestov So we don't have to wait for all the destructors to fire before proceeding with LLVM, [similar to what we do with SILModules](https://github.com/apple/swift/blob/3e8166eab549fc9673823ca14aa486656fe2f426/lib/IRGen/IRGen.cpp#L978-L983). I'm not convinced it will have much of an impact, I'm more just curious.

Plus I'm planning on making the SILGen request cached such that the SILModule lifetimes are tied to the AST context's lifetime so we don't try to free them if we're profiling through the stats reporter (and for later down the line if we have other cached SIL requests that require the SILModule to stay alive). So if we want to continue freeing the SILModules on a separate thread, this is likely how we'd do it.

**Pull request closed without merging**
