### PR TITLE
Structural opaque result types

### PR DESCRIPTION
**Pull request by DougGregor**
Implement the remainder of SE-0328 "Structural opaque result types". This includes:

* Carry the "ordinal" for opaque result types throughout the AST, serialized module files, name mangling, etc.
* Compute substitutions for all opaque generic parameters within the constraint system and use those substitutions consistently
* Generalize the emission of opaque type descriptor metadata to arbitrary requirements
* Eliminate all dependencies on a single underlying generic parameter
* Enable structural opaque result types by default

Implements rdar://51723717

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by slavapestov** [comment]
Woohoo!

**Comment by slavapestov** [comment]
Once you land this, I'm going to look into getting `func foo() -> some Sequence<Int>` working with https://github.com/apple/swift/pull/40714

**Comment by DougGregor** [comment]
> Once you land this, I'm going to look into getting `func foo() -> some Sequence<Int>` working with #40714

The key complication is in https://github.com/apple/swift/blob/main/lib/AST/ASTContext.cpp#L4321-L4345. I mostly have named opaque result types (with explicit generic parameters) working, except that both #40714 and non-trivial named opaque result types rest on figuring out this representational issue.

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test macOS

**Comment by DougGregor** [comment]
@swift-ci please smoke test Linux

**Pull request merged**
