### PR TITLE
[Diagnostics] Removing FailureDiagnosis::visitCoerceExpr from CSDiag

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
Follow up #29011, fixing the remaining failures diagnostics and removing `FailureDiagnosis::visitCoerceExpr` from `CSDiag`.

cc @xedin @hborla

### CODE REVIEW

**Review by xedin — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by LucianoPAlmeida** [comment]
Thank you @xedin :))

**Comment by xedin** [comment]
@LucianoPAlmeida Thank you for taking care of it!

**Comment by hamishknight** [comment]
I think this may be causing the source compat suite to fail for a few projects (https://ci.swift.org/job/swift-PR-source-compat-suite-debug/2157), looks like `anchor` is `nullptr` in the check `isa<CoerceExpr>(anchor)` when we do witness matching (see for example [this crash log](https://ci.swift.org/job/swift-PR-source-compat-suite-debug/2157//artifact/swift-source-compat-suite/FAIL_Alamofire_4.0_BuildXcodeWorkspaceScheme_Alamofire-iOS_generic-platform-iOS.log)).

**Comment by xedin** [comment]
@hamishknight I'm going to revert (https://github.com/apple/swift/pull/29084) but I'll also open a PR to address that. We definitely can get locators without an anchor but a valid path while comparing generics...

**Comment by LucianoPAlmeida** [comment]
@xedin Sorry for the issue, let me know if I can help with that? :)

**Comment by xedin** [comment]
No problem, I got it covered!

**Comment by LucianoPAlmeida** [comment]
> No problem, I got it covered!

Thank you so much 💯

**Comment by xedin** [comment]
@LucianoPAlmeida Could you please try to reduce a simple test-case from project crashes so we could include it into validation test?

**Comment by LucianoPAlmeida** [comment]
@xedin Sure 👍

**Comment by LucianoPAlmeida** [comment]
@xedin Just added the test case #29095 :))

**Pull request merged**
