### PR TITLE
Dynamic exclusivity refinements

### PR DESCRIPTION
**Pull request by rjmccall**
A collection of refinements to the dynamic exclusivity runtime.

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci  Please test.

**Comment by rjmccall** [comment]
@swift-ci Please smoke test and merge

**Comment by rjmccall** [comment]
@swift-ci Please smoke test and merge.

**Comment by rjmccall** [comment]
@swift-ci Please smoke test and merge.

**Comment by rjmccall** [comment]
...so it looks like @swift-ci just completely ignored my request.

**Comment by rjmccall** [comment]
@swift-ci Please smoke test.

**Comment by rjmccall** [comment]
@swift-ci Please smoke test and merge.

**Comment by kubamracek** [comment]
> Fix expected test output.
I think the test still doesn't match the output of the error messages (we print the PCs now).

**Comment by rjmccall** [comment]
@swift-ci Please smoke test.

**Pull request merged**
