### PR TITLE
ASTScope: Stop sorting declarations by source range

### PR DESCRIPTION
**Pull request by slavapestov**
ASTScope would filter out duplicate AST nodes and in some places, sort AST nodes by source range. Let's remove these and fix the underlying issues instead.

Builds upon https://github.com/apple/swift/pull/34207.

### CODE REVIEW

**Comment by slavapestov** [comment]
https://github.com/apple/llvm-project/pull/1916
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
https://github.com/apple/llvm-project/pull/1916
@swift-ci Please smoke test

**Review by davidungar — APPROVED** [review]
Looks fine! I think we discussed adding a general assertion to the AST to ensure that source ranges were in order everwhere.

**Comment by slavapestov** [comment]
@swift-ci Please test Windows

**Pull request merged**
