### PR TITLE
Sema: Allow omitting generic parameters when accessing member type with a fully-constrained 'where' clause

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes rdar://problem/78960468.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Review by DougGregor — APPROVED** [review]

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Pull request merged**
