### PR TITLE
[AutoDiff upstream] Add `-enable-experimental-differentiable-programming` driver flag.

### PR DESCRIPTION
**Pull request by dan-zheng**
This flag will enable all experimental differentiable programming features.
The default will be `true` on tensorflow branch but `false` on master branch.

Features will first be updated on tensorflow branch to use this flag, before
being upstreamed to master. The goal is to achieve a minimal code diff between
the two branches.

The [TF-820](https://bugs.swift.org/browse/TF-820) master issue tracks upstreaming differentiable programming.

---

Rationale: we chose to add a driver flag rather than a `build-script`/CMake flag for easier testing. Differentiable programming `lit` tests can be run by specifying this additional flag without recompiling the compiler and standard library.

[Forum discussion on upstreaming differentiable programming.](https://forums.swift.org/t/upstreaming-differentiable-attribute-and-differentiable-protocol/26821)

### CODE REVIEW

**Review by lattner — CHANGES_REQUESTED** [review]
I'd recommend a shorter name like "-enable-experimental-autodiff", similarly for the global.

Otherwise, LGTM but please way for an ack from someone on the Apple side.  Thanks!

**Comment by rxwei** [comment]
It seems that most existing flags are fully spelled out, e.g. `-driver-emit-experimental-dependency-dot-file-after-every-import`. I'm leaning towards the existing spelling since the feature is formally pitched and proposed as "differentiable programming", but I don't have a very strong opinion.

**Comment by lattner** [comment]
@jrose-apple @jckarter @rjmccall Anyone have an opinion on the driver flag naming?  Ted approved landing this work in master under a flag, but we need a flag :-).

**Comment by jckarter** [comment]
Anything's fine by me as long as it has `-experimental` in the name somewhere.

**Comment by dan-zheng** [comment]
+1 from me for `-enable-experimental-differentiable-programming`.

**Comment by dan-zheng** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
Works for me. Long flags over short flags is generally to not occupy a namespace with a generic name, which is less of a problem here (and also less of a problem for frontend-only flags, which are not considered stable).

**Comment by rxwei** [comment]
Thanks @jrose-apple and @jckarter! We’ll go with the existing flag name then. Could anyone approve this PR?

**Review by lattner — APPROVED** [review]

**Comment by rxwei** [comment]
@swift-ci please smoke test linux platform

**Comment by rxwei** [comment]
@swift-ci please smoke test linux

**Comment by rxwei** [comment]
@swift-ci please smoke test linux

**Comment by rxwei** [comment]
@swift-ci please test linux platform

**Comment by rxwei** [comment]
@swift-ci please test

**Comment by rxwei** [comment]
@swift-ci please test linux

**Comment by rxwei** [comment]
@swift-ci please smoke test linux

**Comment by rxwei** [comment]
@swift-ci please smoke test linux

**Comment by rxwei** [comment]
@swift-ci please smoke test Linux

**Pull request merged**
