### PR TITLE
[WIP] Add swift-foundation to toolchain build

### PR DESCRIPTION
**Pull request by jmschonfeld**
This is a WIP PR to add the swift-foundation set of projects to the toolchain build for use by swift-corelibs-foundation

### CODE REVIEW

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-foundation-icu/pull/22

@swift-ci please build toolchain linux platform

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-foundation-icu/pull/22

@swift-ci please build toolchain linux platform

**Comment by iCharlesHu** [comment]
https://github.com/apple/swift-foundation-icu/pull/22

@swift-ci please build toolchain linux platform

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-foundation-icu/pull/22

@swift-ci please build toolchain linux platform

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-corelibs-foundation/pull/4948
https://github.com/apple/swift-foundation-icu/pull/22

@swift-ci please build toolchain linux platform

**Comment by iCharlesHu** [comment]
https://github.com/apple/swift-corelibs-foundation/pull/4948
https://github.com/apple/swift-foundation-icu/pull/22

@swift-ci please build toolchain linux platform

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-corelibs-foundation/pull/4948/files
https://github.com/apple/swift-foundation-icu/pull/22

@swift-ci please build toolchain linux platform

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-corelibs-foundation/pull/4948
https://github.com/apple/swift-foundation-icu/pull/22

@swift-ci please build toolchain linux platform

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-foundation-icu/pull/22
https://github.com/apple/swift-foundation/pull/573
https://github.com/apple/swift-corelibs-foundation/pull/4959

@swift-ci please build toolchain linux platform

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-foundation-icu/pull/22
https://github.com/apple/swift-foundation/pull/573
https://github.com/apple/swift-corelibs-foundation/pull/4959

@swift-ci please build toolchain linux platform

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-foundation-icu/pull/22
https://github.com/apple/swift-foundation/pull/573
https://github.com/apple/swift-corelibs-foundation/pull/4959

@swift-ci please build toolchain linux platform

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-collections/pull/377
https://github.com/apple/swift-foundation-icu/pull/22
https://github.com/apple/swift-foundation/pull/573
https://github.com/apple/swift-corelibs-foundation/pull/4959

@swift-ci please build toolchain linux platform

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-collections/pull/378
https://github.com/apple/swift-foundation-icu/pull/22
https://github.com/apple/swift-foundation/pull/573
https://github.com/apple/swift-corelibs-foundation/pull/4959

@swift-ci please build toolchain linux platform

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-collections/pull/378
https://github.com/apple/swift-foundation-icu/pull/22
https://github.com/apple/swift-foundation/pull/573
https://github.com/apple/swift-corelibs-foundation/pull/4959

@swift-ci please build toolchain linux platform

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-collections/pull/378
https://github.com/apple/swift-foundation-icu/pull/22
https://github.com/apple/swift-foundation/pull/573
https://github.com/apple/swift-corelibs-foundation/pull/4959

@swift-ci please build toolchain linux platform

**Comment by iCharlesHu** [comment]
https://github.com/apple/swift-collections/pull/379
https://github.com/apple/swift-foundation-icu/pull/22
https://github.com/apple/swift-foundation/pull/573
https://github.com/apple/swift-corelibs-foundation/pull/4959

@swift-ci please build toolchain linux platform

**Comment by iCharlesHu** [comment]
https://github.com/apple/swift-collections/pull/379
https://github.com/apple/swift-foundation-icu/pull/22
https://github.com/apple/swift-foundation/pull/573
https://github.com/apple/swift-corelibs-foundation/pull/4959

@swift-ci please clean build toolchain linux platform

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-collections/pull/379
https://github.com/apple/swift-foundation-icu/pull/22
https://github.com/apple/swift-foundation/pull/573
https://github.com/apple/swift-corelibs-foundation/pull/4959

@swift-ci please clean build toolchain linux platform

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-collections/pull/379
https://github.com/apple/swift-foundation-icu/pull/22
https://github.com/apple/swift-foundation/pull/573
https://github.com/apple/swift-corelibs-foundation/pull/4959

@swift-ci please clean build toolchain linux platform

**Pull request closed without merging**
