### PR TITLE
[AutoDiff] Mark places to diagnose "no `AdditiveArithmetic` conforman…

### PR DESCRIPTION
**Pull request by dan-zheng**
…ce".

Mark places to diagnose "no `AdditiveArithmetic` conformance" in differentiation pass.
Setup for fixing [TF-202](https://bugs.swift.org/browse/TF-202).

### CODE REVIEW

**Comment by dan-zheng** [comment]
Actually, after some thought, fixing TF-202 outright might be easier.

Since all of the functions checking for `AdditiveArithmetic` conformance are defined under `AdjointEmitter`, we can simply set `errorOccurred = true` if no conformance is found.
Then, callers check for `errorOccurred` to determine whether to error out. This might be a bit ugly because there are many callers.

@rxwei: what do you think?

**Comment by dan-zheng** [comment]
Triggering tests in anticipation that tests will finish before I can implement a fix for TF-202.

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by rxwei** [comment]
> Since all of the functions checking for `AdditiveArithmetic` conformance are defined under `AdjointEmitter`, we can simply set `errorOccurred = true` if no conformance is found.
Then, callers check for `errorOccurred` to determine whether to error out. This might be a bit ugly because there are many callers.

That is not a viable solution. No error will be emitted based on whether `errorOccurred` is true. You have to use `context.emitNondifferentiabilityError`.

**Comment by dan-zheng** [comment]
> That is not a viable solution. No error will be emitted based on whether `errorOccurred` is true. You have to use `context.emitNondifferentiabilityError`.

Oh yes, good point. Would the solution work if `context.emitNondifferentiabilityError` is called in addition to setting `errorOccurred = true` if conformance is not found?

**Comment by rxwei** [comment]
Yes.

**Comment by dan-zheng** [comment]
I'll implement the discussed solution for TF-202 soon.
macOS tests flaked; merging regardless (this PR is NFC).

**Pull request merged**
