### PR TITLE
[NFC] Remove IRGen's ClangTypeConverter in favor of the AST one.

### PR DESCRIPTION
**Pull request by varungandhi-apple**
First two commits are from https://github.com/apple/swift/pull/34513 and can be ignored here.

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
@swift-ci please test

**Comment by varungandhi-apple** [comment]
@swift-ci please test

**Comment by varungandhi-apple** [comment]
@swift-ci please test

**Review by rjmccall — APPROVED** [review]
LGTM

**Comment by varungandhi-apple** [comment]
@swift-ci please test and merge

**Pull request merged**
