### PR TITLE
[GSB] Don't try to infer requirements from error types.

### PR DESCRIPTION
**Pull request by huonw**
Fixes rdar://problem/39548143.

### CODE REVIEW

**Comment by huonw** [comment]
@swift-ci please smoke test

**Comment by huonw** [comment]
Arguably it's fundamentally incorrect to have a `NameAliasType` with no `SubstitutionMap`, so maybe I should instead go fix that there (and/or hope https://github.com/apple/swift/pull/16268 helps).

**Comment by shahmishal** [comment]
@swift-ci please smoke test

**Comment by huonw** [comment]
Oh, nevermind, the problem is something different: the `NameAliasType` is theoretically behaving correctly here, as `getSubstitutionListSize()` for its generic signature returns 0, meaning the type doesn't store any substitutions and the map is empty. It does seem as if #16268 is very relevant to this misbehaviour.

**Comment by huonw** [comment]
> It does seem as if #16268 is very relevant to this misbehaviour.

In fact, it fixed it.

**Pull request closed without merging**
