### PR TITLE
[Serialization] Remove bogus limitation on fast path

### PR DESCRIPTION
**Pull request by jrose-apple**
The meaning of this bit changed way back in #7794, but I forgot to update this fast path. Thanks to this code falling back to the slow path if things didn't work out, there wasn't a correctness issue here, but it might have been doing more work than necessary.

Depends on #17333 (because otherwise it will immediately conflict).

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test compiler performance

**Comment by jrose-apple** [comment]
Basically no change. Okay.

**Review by DougGregor — APPROVED** [review]
LGTM

**Comment by jrose-apple** [comment]
…and it conflicted anyway.

@swift-ci Please smoke test

**Pull request merged**
