### PR TITLE
disable the string_switch test for a resilient stdlib build

### PR DESCRIPTION
**Pull request by eeckstein**

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci smoke test and merge

**Comment by slavapestov** [comment]
What was the failure? Can you file a bug?

**Comment by eeckstein** [comment]
@swift-ci smoke test linux

**Comment by eeckstein** [comment]
@swift-ci smoke test linux

**Comment by eeckstein** [comment]
@swift-ci clean smoke test linux

**Comment by eeckstein** [comment]
@slavapestov This is not a bug, the optimization just does not kick in with a resilient stdlib.

**Pull request merged**
