### PR TITLE
Revert "Implement several peephole optimizations to unblock further o…

### PR DESCRIPTION
**Pull request by meg-gupta**
…ptimizations of autodiff code (#60520)"

This reverts commit 2f5492f572818e728e3358c13315c2d4e5c9be64.

Looks like #60520 was the underlying reason for failure in - https://ci-external.swift.org/job/oss-swift-windows-toolchain-x86_64-vs2019/1779/

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci please build toolchain Windows platform

**Comment by meg-gupta** [comment]
Testing to make sure this repairs windows builds.

**Comment by meg-gupta** [comment]
From the log:
``
[4/5][ 80%][0.418s] Install the project...
-- Install configuration: "Release"
-- Installing: T:/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/lib/swift/windows/ArgumentParser.lib
-- Installing: T:/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/bin/ArgumentParser.dll
-- Installing: T:/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/lib/swift/windows/x86_64/ArgumentParser.swiftdoc
-- Installing: T:/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/lib/swift/windows/x86_64/ArgumentParser.swiftmodule
-- Installing: T:/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/lib/swift/windows/ArgumentParserToolInfo.lib
-- Installing: T:/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/bin/ArgumentParserToolInfo.dll
-- Installing: T:/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/lib/swift/windows/x86_64/ArgumentParserToolInfo.swiftdoc
-- Installing: T:/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/lib/swift/windows/x86_64/ArgumentParserToolInfo.swiftmodule
``

This is building `ArgumentParser` now, but there is another unrelated error. So this confirms the SILCombine changes were breaking the build.

**Comment by meg-gupta** [comment]
Created an issue with some more details here  - https://github.com/apple/swift/issues/61731

**Comment by meg-gupta** [comment]
@swift-ci test

**Review by compnerd — APPROVED** [review]
Thanks @meg-gupta!  The new failure is a bug in swift-syntax, this definitely should get us further towards a green build.

**Comment by compnerd** [comment]
Since the tests passed, and the toolchain has been broken for ~1w, going to mark this as ready for review and merge to enable the next set of changes.

**Comment by compnerd** [comment]
CC: @asl @BradLarson @CodaFi (Anton/Brad for the reverted bits for AD, Robert for the Syntax issues).

**Pull request merged**
