### PR TITLE
sourcekitd/format: avoid performing sibling-based indentation for PrefixUnaryExpr.

### PR DESCRIPTION
**Pull request by nkcsgexi**
rdar://47659949

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test and merge

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Review by akyrtzi — APPROVED** [review]

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Pull request merged**
