### PR TITLE
[SourceKit] Add a request tracker that manages cancellation

### PR DESCRIPTION
**Pull request by ahoppen**
Previously, `SwiftASTManager` and `SlowRequestSimulator` maintained their own list of in-progress cancellation tokens. With code completion cancellation coming up, there would need to be yet another place to track in-progress requests, so let’s centralize it.

While at it, also support cancelling requests before they are scheduled, eliminating the need for a `sleep` in a test case.

The current implementaiton leaks tiny amounts of memory if a request is cancelled after if finishes. I think this is fine because it is a pretty nieche case and the leaked memory is pretty small (a `std::map` entry pointing to a `std::function` + `bool`). Alternatively, we could require the client to always dispose of the cancellation token manually.

rdar://83762402

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Review by rintaro — APPROVED** [review]
Overall looks OK. Sorry I haven't been able to look into this deeply. But let's merge this anyway. We can adjust details when we expand the applications. e.g. when utilizing this in code completion, etc.

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
> The current implementaiton leaks tiny amounts of memory if a request is cancelled after if finishes.

As far as I can see, they always leak? If not, could you explain how they are cleared without calling `sourcekitd_request_handle_dispose`?

**Comment by ahoppen** [comment]
> As far as I can see, they always leak? If not, could you explain how they are cleared without calling `sourcekitd_request_handle_dispose`?

The request handle gets disposed automatically when the request finishes here: https://github.com/apple/swift/pull/39681/files#diff-60bea428f028f181ee34480bec368b52fa8739aa5c20872b6a7d601fd4db1f1eR401-R402. The only situation where calling `sourcekitd_request_handle_dispose` is currently necessary if you cancel a request after it has finished. Also, sorry about the comment in the PR about the leaking, I only added `sourcekitd_request_handle_dispose` after creating the PR. We should not be leaking memory if `sourcekitd_request_handle_dispose` is called.

**Comment by ahoppen** [comment]
@swift-ci Please smoke test macOS

**Comment by rintaro** [comment]
Oh I overlooked that line. Thank you for the explanation.
So you mean they leak only because it uses `operator[]`, right?
```
Requests[CancellationToken].IsCancelled = true;
```
Why don't you `find()` and update?
```cpp
auto found = Requests.find(CancellationToken);
if (found != Requests.end()) {
  found->IsCancelled = true;
  if (auto CancellationHandler = found->CancellationHandler) {
    CancellationHandler();
  }
}
```

**Comment by ahoppen** [comment]
> Oh I overlooked that line. Thank you for the explanation. So you mean they leak only because it uses `operator[]`, right?
> 
> ```
> Requests[CancellationToken].IsCancelled = true;
> ```
> 
> Why don't you `find()` and update?
> 
> ```c++
> auto found = Requests.find(CancellationToken);
> if (found != Requests.end()) {
>   found->IsCancelled = true;
>   if (auto CancellationHandler = found->CancellationHandler) {
>     CancellationHandler();
>   }
> }
> ```

We need to proactively set `IsCancelled = true` even if the request doesn’t exist in the request tracker yet, because it just might not have been registered there yet. The registration of a request in the request tracker only happens after a few async queue hops, so the client might cancel the request before the request tracker has a chance to know that it actually started. 

Anyway, the leaking is no longer an issue because we have `sourcekitd_request_handle_dispose` now.

**Pull request merged**
