### PR TITLE
[SILSSAUpdater] Clone `string_literal` arguments to `int_instrprof_increment`

### PR DESCRIPTION
**Pull request by hamishknight**
Previously we could let these arguments become phi nodes when performing jump threading. This would break IRGen, as the string value must be statically known. Update SILSSAUpdater to ensure they are instead rewritten by cloning, ensuring they remain statically known.

rdar://39146527

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please build toolchain

**Comment by eeckstein** [comment]
I'm wondering if this is the right approach at all.
There is no guarantee that other optimizations could do similar things.

I think it's better to define a separate SIL instruction, which has the string literal built in. Then it can never happen that the string literal is "separated" from the `int_instrprof_increment`

**Comment by hamishknight** [comment]
@eeckstein Makes sense, I'll look into that. Seems like we might also want to consider doing the same for llvm intrinsics like `ctlz`, which require a constant argument, as this cloning logic is currently what's preventing us from turning those arguments into phis.

**Comment by eeckstein** [comment]
@hamishknight You can take a look at the `cond_fail` instruction. It also has a "built in" string literal.

**Comment by hamishknight** [comment]
Opened https://github.com/apple/swift/pull/60979 to implement a dedicated instruction for this

**Pull request closed without merging**
