### PR TITLE
Add a high-level request to type check a file

### PR DESCRIPTION
**Pull request by CodaFi**

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]
This is great, but it's not "NFC" if we're changing the shape of requests.

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
⛵️

**Pull request merged**
