### PR TITLE
IDE: preserve the environment in the triple

### PR DESCRIPTION
**Pull request by compnerd**
Adjust the triple manipulation to preserve the environment in the case
of non-Darwin targets.  This is particularly important for android which
is an environment for Linux, and Windows, where we support specific
environments only.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @jrose-apple @benlangmuir

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by jrose-apple** [comment]
I think you might as well do this whenever the environment is non-empty. That'll help with the "simulator" environment they're slowly bringing up for iOS simulator triples.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by jrose-apple** [comment]
Looks like this failure is [also happening on master](https://ci.swift.org/job/oss-swift_tools-RA_stdlib-RD_test-simulator/1593/).

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Pull request merged**
