### PR TITLE
[DNM] [5.0] [Type checker] De-prioritize SIMD operators

### PR DESCRIPTION
**Pull request by DougGregor**
The new SIMD proposal introduced a number of new operators, the presence of
which causes more "expression too complex" failures. Route around the
problem by de-prioritizing those operators, only considering them if
we can't type check any other way and ended up seeing both SIMD types
and SIMD operators in our first attempt to type check. This should limit the
type checker performance cost of said operators to only those expressions
that need them OR that already failed to type-check.

Fixes rdar://problem/46541800.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Review by airspeedswift — APPROVED** [review]

**Comment by DougGregor** [comment]
Ugh, it's probably the `-solver-enable-operator-designated-types` version of the test failing, because of course all of that functionality isn't on the 5.0 branch.

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Pull request closed without merging**
