### PR TITLE
build: explicitly specify the platform that we are building for

### PR DESCRIPTION
**Pull request by compnerd**
This prepares the structure for building multiple platform SDKs on Windows.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @hjyamauchi @hyp

**Comment by compnerd** [comment]
@swift-ci please test

**Review by hjyamauchi — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Pull request merged**
