### PR TITLE
build: extend the symlink tree

### PR DESCRIPTION
**Pull request by compnerd**
The Linux build requires the full tree of links.  Construct it
appropriately to ensure that consumers continue to work.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test tensorflow

**Comment by compnerd** [comment]
@swift-ci plese test tensorflow

**Comment by compnerd** [comment]
@swift-ci please test tensorflow

**Comment by compnerd** [comment]
@swift-ci please test tensorflow

**Review by dan-zheng — APPROVED** [review]

**Pull request merged**
