### PR TITLE
[Constant Evaluator] Skip code-coverage instrumentation during constant evaluation

### PR DESCRIPTION
**Pull request by guitard0g**
Currently the logging API implementation may fail when code coverage is enabled due to the constant interpreter not knowing how to process the added instrumentation builtin instructions. This change adds a new builtin `int_instrprof_increment` to Builtins.def and and also tells the constant interpreter to skip this instruction. 

Additionally, this change adds new tests for the constant evaluator and OSLog to ensure compatibility with these code coverage instructions. The `OSLogConstantEvaluable` and `constant_evaluable` test suites were reworked a bit to test by compiling the same swift source code with and without code coverage enabled. 

rdar://problem/62912038

### CODE REVIEW

**Comment by ravikandhadai** [comment]
@eeckstein This PR made by @guitard0g adds a new builtin `BUILTIN_MISC_OPERATION` for the code coverage instruction: `int_instrprof_increment`, it updates a few files related to this: `Builtins.cpp` and ownership entries. Just wondering if this change looks good to you?

**Comment by eeckstein** [comment]
@ravikandhadai Yes, the changes regarding the builtin look good. Where is this builtin generated?

**Comment by ravikandhadai** [comment]
> @ravikandhadai Yes, the changes regarding the builtin look good. Where is this builtin generated?

It is generated by SILGenFunction here: https://github.com/apple/swift/blob/bcb6699bf4b3fb7e94233fe63758bf0a5e7ff5e7/lib/SILGen/SILGenFunction.cpp#L969

**Comment by guitard0g** [comment]
@swift-ci please test

**Comment by eeckstein** [comment]
> Do you think this could be changed to use the ID now?

yes, that would be good.

**Comment by guitard0g** [comment]
@swift-ci please test

**Comment by ravikandhadai** [comment]
@swift-ci please test macOS platform

**Review by ravikandhadai — APPROVED** [review]
Thanks @guitard0g. Looks good to me!

**Comment by ravikandhadai** [comment]
@swift-ci Please test macOS Platform

**Comment by guitard0g** [comment]
@swift-ci Please test macOS Platform

**Pull request merged**
