### PR TITLE
Rename lldb-vscode -> lldb-dap

### PR DESCRIPTION
**Pull request by adrian-prantl**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves #NNNNN, fix apple/llvm-project#MMMMM.

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci smoke test

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/llvm-project/pull/7985
@swift-ci test windows

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-installer-scripts/pull/275
test with https://github.com/apple/llvm-project/pull/7985
@swift-ci test windows

**Review by compnerd — APPROVED** [review]

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/275
https://github.com/apple/llvm-project/pull/7985

@swift-ci please build toolchain Windows platform

**Pull request merged**
