### PR TITLE
[test] Skip some Concurrency tests during back deployment testing

### PR DESCRIPTION
**Pull request by hamishknight**
rdar://82123254

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please smoke test

**Comment by hamishknight** [comment]
@swift-ci please smoke test

**Review by ktoso — APPROVED** [review]
I don't _really really_ know if this is right, but it definitely _seems_ right since there's no backreployment none of those would be expected to work at all...? Maybe @DougGregor to double check though.

**Comment by hamishknight** [comment]
Merging to help unblock things, will double check with Doug to be totally sure this is correct.

**Pull request merged**
