### PR TITLE
[Lexer] Tweaks for string literal lexing

### PR DESCRIPTION
**Pull request by rintaro**
* Add `formStringLiteralToken()` dedicated for forming string literal
* Fix duplicated diagnostics for unterminated string literal in interpolation
* Improve diagnostics for single quoted string literal
* Improve fix-it to remove too-many-"#" in string literal
* Bunch of code tweaks to improve readability.

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please Test Source Compatibility

**Comment by rintaro** [comment]
@swift-ci Please test compiler performance

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please ASAN test

**Comment by rintaro** [comment]
ASAN: https://ci.swift.org/view/Pull%20Request/job/swift-PR-osx-ASAN-test/59/

**Comment by rintaro** [comment]
Small cosmetic changes
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by johnno1962** [comment]
👍👍, I like the new skipToEndOfInterpolatedExpression

**Comment by johnno1962** [comment]
👍👍, I like the new skipToEndOfInterpolatedExpression

**Comment by johnno1962** [comment]
I’m seeing an assertion firing on this code:
```
print("""
  \("--)
  "”")

Assertion failed: (*End == ')' && "invalid string literal interpolations should" " not be returned as string literals"), function getStringLiteralSegments, file /Volumes/Elements/swift-source/swift/lib/Parse/Lexer.cpp, line 2255.
```
This is a step forward as it used to compile with no error and an incorrect string but its difficult to think of a the solution.

**Comment by rintaro** [comment]
Confirmed. Thank you! I'll look into it.

**Pull request merged**
