### PR TITLE
[WIP] [Runtime] Use retroactive protocol conformances when demangling to metadata

### PR DESCRIPTION
**Pull request by DougGregor**
Extend TypeDecoder with the ability to demangle (concrete) protocol
conformances, and pass along demangled retroactive conformances to
it’s builder’s createBoundGenericType().

Extend the mangled name -> metadata code in the runtime to use retroactive
conformances when satisfying generic requirements. If a retroactive
conformance is provided, the corresponding witness table will be used
instead of the one found by swift_conformsToProtocol(). This allows us to
properly demangle type names involving retroactive conformances.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test Linux

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
This PR is probably the wrong direction to go. The fifth commit already got merged; the second commit has been pulled out into https://github.com/apple/swift/pull/20491; and I think I'd prefer to stage in the conformance demangling more directly (e.g., via a compiler flag to enable it for associated conformances in witness tables) than this retroactive-conformances approach.

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
