### PR TITLE
Move TaskLocal.h out of ABI folder

### PR DESCRIPTION
**Pull request by nickolas-pohilets**
This header describes implementation details, that can be changed without breaking ABI.

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by nickolas-pohilets** [comment]
```
Test Case '-[SKSupportTests.AsyncUtilsTests testWithTimeout]' started.
/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/sourcekit-lsp/Tests/SKSupportTests/AsyncUtilsTests.swift:22: error: -[SKSupportTests.AsyncUtilsTests testWithTimeout] : failed - Expression was expected to throw but did not throw
Test Case '-[SKSupportTests.AsyncUtilsTests testWithTimeout]' failed (2.805 seconds).
```

Does not seem to be related to my changes.

**Comment by ktoso** [comment]
@swift-ci please smoke test macOS

**Comment by nickolas-pohilets** [comment]
> @swift-ci please smoke test macOS

The failed one is a validation test. Did you mean `@swift-ci Please test macOS platform`?

**Comment by ktoso** [comment]
No, the smoke was on purpose. Seems it didn’t complete tho

**Comment by ktoso** [comment]
Giving a full run another go…

**Comment by ktoso** [comment]
@swift-ci please test macOS

**Review by ktoso — APPROVED** [review]

**Comment by nickolas-pohilets** [comment]
@ktoso, can it be merged, or do I need more approvals?

**Comment by ktoso** [comment]
Yes we can merge it, done!

**Pull request merged**
