### PR TITLE
[metadata prespecialization] Add canonical records to cache.

### PR DESCRIPTION
**Pull request by nate-chandler**
Previously, every call to `swift_getGenericMetadata` involved looking into the passed-in nominal type descriptor to look for canonical prespecialized metadata records and searching through those records looking for one whose arguments matched those passed to the function.  That behavior was an evolution from the previous behavior where the search through canonical metadata records was performed in the metadata accessor itself.

Here, that behavior is removed from `swift_getGenericMetadata` entirely.  This is made possible by calling a different variant of that function from the metadata accessors of generic types for which canonical prespecialized metadata records have been formed.  The metadata accessors now call the new runtime function `swift_getCanonicalPrespecializedGenericMetadata`, either directly or by way of a newly added thunk `__swift_instantiateCanonicalPrespecializedGenericMetadata` which is analogous to `__swift_instantiateGenericMetadata` but calls through to `swift_getCanonicalPrespecializedGenericMetadata` rather than `swift_getGenericMetadata`.

The new runtime function `swift_getCanonicalPrespecializedGenericMetadata` takes an additional argument beyond those passed to `swift_getGenericMetadata`, namely, a `swift_once_t *` token.  That token is used to guard that only one attempt is made to add the canonical prespecialized metadata records attached to the nominal type descriptor to the metadata cache.

Additionally, `swift_getCanonicalSpecializedMetadata`--the entry point for canonicalizing non-canonical prespecialized metadata records--is able to make use of that same token to also avoid attempting to add more than once to the metadata cache those same canonical prespecialized records.  Reusing the once token like this (by both `swift_getCanonicalPrespecializedGenericMetadata` and `swift_getCanonicalSpecializedMetadata`) ensures that, regardless of which entry point is used, exactly one attempt will be made to add canonical prespecialized records to the metadata cache.

Reusing the once token is made possible by adding its address to the struct enum and class descriptors after the canonical prespecialized records already in those descriptors.  `swift_getCanonicalPrespecializedGenericMetadata` attempts to find the once token in the type descriptor.  If it is there, then that means that there were prespecializations and it attempts to add those prespecializations to the cache (guarded, again, by that once token).

rdar://problem/69855938

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test compiler performance

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test compiler performance

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test compiler performance

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test macos platform

**Comment by nate-chandler** [comment]
@swift-ci please test compiler performance

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test compiler performance

**Comment by nate-chandler** [comment]
@swift-ci please asan test

**Comment by nate-chandler** [comment]
@swift-ci please clean test linux platform

**Comment by nate-chandler** [comment]
@swift-ci please clean test windows platform

**Comment by nate-chandler** [comment]
@swift-ci please clean test macos platform

**Comment by jckarter** [comment]
Very nice! Should we still use the previous implementation when targeting a 5.3 runtime, or is the code size/performance hit from checking all the specializations one by one just not worth it?

**Comment by nate-chandler** [comment]
@jckarter We're a bit lucky in a way: even before this change, `getPrespecializedGenericMetadataAvailability` returns `getSwift54Availability`, the feature wasn't enabled for the stdlib in 5.3, and we couldn't target the 5.3 runtime without additions to the compatibility library.  

The 5.3 runtime doesn't know about the new trailing objects on the nominal type descriptors which would be needed to loop over the prespecializations in swift_getGenericMetadata (and its version of swift_getGenericMetadata doesn't know to do that).  The comparisons can't be done directly in the metadata accessor itself, either, because the 5.3 runtime lacks `swift_compareProtocolConformanceDescriptors` which is needed to correctly handle multiple conformances of a type to the same protocol.  

I guess if we added support in a compatibility library, we could just add swift_getCanonicalPrespecializedGenericMetadata itself, supposing we can add these trailing objects, if it's worth having this feature available for 5.3.  What do you think?

**Comment by jckarter** [comment]
Ah, I thought we had shipped partial support for prespecializations in 5.3 already. If we haven't shipped that yet, then it might be interesting to back deploy, but I don't think it's strictly necessary since this is an optimization and not core functionality.

**Pull request merged**
