### PR TITLE
[Swift 2.2] StdLib documentation improvements

### PR DESCRIPTION
**Pull request by natecook1000**
**Explanation:** This request makes a number of improvements to the standard library documentation, including adding abstracts for several types and protocols that are missing them. These changes have all been merged into `swift/master`, and have been cherry-picked for this PR.

**Scope:** These changes are strictly limited to header documentation for the standard library. There are some minor changes to GYB logic, but only in service of improving the documentation.

**SR Issue:** These changes are not covered by an SR.

**Risk:** There should be no risk, as these changes only affect comments.

**Testing:** This change passes all validation tests when run via `build-script -RT`.

### CODE REVIEW

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by gribozavr** [comment]
@natecook1000 Are you going to nominate this PR on swift-dev?

**Comment by gribozavr** [comment]
@dabrahams This is for the 2.2 branch, it needs approval from the release manager.

**Comment by dabrahams** [comment]
Sorry, I prematurely merged it.  The commit looks great to me, but I didn’t realize this was the 2.2 branch.

**Comment by tkremenek** [comment]
I approve taking this.

**Comment by tkremenek** [comment]
@dabrahams Did you end up reverting these changes from the branch?  If so, can you re-apply them?

**Pull request merged**
