### PR TITLE
AST: Add more asserts for same-type constraints in generic signatures

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
This caught a bug where we build an invalid minimized signature for the following:

```
public struct G<Word> where Word : FixedWidthInteger, Word.Magnitude == Word {}
```

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility Debug

**Comment by slavapestov** [comment]
That's funny, SRP in the source compat suite includes a copy of test/Prototypes/BigInt.swift, so it hits the same exact error.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by compnerd** [comment]
This seems to have caused a regression on the Windows builder.  This was caught by the precommit testing and the CI builds as well: https://ci-external.swift.org/job/oss-swift-windows-x86_64-vs2019/1918/

Could you please take a look at this @slavapestov?

**Pull request merged**
