### PR TITLE
[ClosureLifetimeFixup] Cleanups get CleanupLocs.

### PR DESCRIPTION
**Pull request by nate-chandler**
Otherwise at Onone we can get downstream debug info verification failures.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please clean test macOS platform

**Review by atrick — APPROVED** [review]
huh, I bet this needs to be fixed all over the code. What actually changes with CleanupLocKind? Do certain kinds of instructions require it?

**Comment by atrick** [comment]
> so instructions that are created with autogenerated locs `"<compiler-generated>":0:0` aren't required to participate in scope reentry expectations.

oh, I thought it was sufficient just to use an autogenerated location. That's why we're not doing the CleanupLoc think consistently

**Pull request merged**
