### PR TITLE
Fix some resilience tests for device testing

### PR DESCRIPTION
**Pull request by slavapestov**
- Pass -install_name @executable_path/libfoo.dylib to the linker
- Pass dylib as an argument to the binary

Fixes <rdar://problem/34148403>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by gparker42** [comment]
These tests are still failing. Please XFAIL them now.

**Pull request merged**
