### PR TITLE
[Linux] Disable fatalError() backtraces when the runtime backtracer is active.

### PR DESCRIPTION
**Pull request by al45tair**
There's no need for fatalError() to try to generate its own backtraces when the runtime's backtracer is enabled.  Not only is the code it uses more fragile but it also doesn't support async or inline frames and it can't look-up symbols properly either.

rdar://117470489

### CODE REVIEW

**Comment by al45tair** [comment]
**Explanation**: Currently if a program terminates with an assertion failure or `fatalError()`, the assertion failure code in the Swift runtime tries to generate its own backtrace using `libunwind` and `dlsym()`. When the new backtracer that was added in 5.9 is also active, this is confusing because you get two backtraces, and on Linux the `dlsym()` call is a really poor way to do a symbol lookup so the first one you see has lots of `<unavailable>` symbols listed in it. The upshot is confusing output.
**Original PR**: #69570
**Reviewed by**: @mikeash
**Resolves**: rdar://117470489
**Tests**: There is a test of the `fatalError()` backtrace already, so that just gets updated to turn off the out-of-process backtracer, plus I updated one of the out-of-process backtracer tests to explicitly check that the `fatalError()` backtracer doesn't generate any output when it's enabled.

**Comment by al45tair** [comment]
@swift-ci Please test

**Review by tomerd — APPROVED** [review]

**Comment by al45tair** [comment]
@swift-ci Please test Windows platform

**Comment by al45tair** [comment]
@swift-ci Please test Windows platform

**Comment by al45tair** [comment]
@swift-ci Please test Windows platform

**Comment by al45tair** [comment]
@swift-ci Please test

**Pull request merged**
