### PR TITLE
[DO NOT MERGE] Inline data and dataprotocol

### PR DESCRIPTION
**Pull request by atrick**
This adds three more optimizer fixes, in addition to the one that was already committed, in order to fix the performance of the generic Data initializer's dynamic customization.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci benchmark.

**Comment by atrick** [comment]
@swift-ci test source compatibility.

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
@itaiferber Let me know if the commits on this branch solve the immediate
performance problems that you're blocked on.

I still see the following regressions:
```
------- Performance: -Osize -------

| TEST                              |   OLD |   NEW |   DELTA | RATIO     |
|                                   |       |       |         |           |
| **Regression**                    |       |       |         |           |
| DataSetCountMedium                |   633 |  6284 | +892.7% | **0.10x** |
| ObjectiveCBridgeStubDataAppend    |  6428 | 36656 | +470.3% | **0.18x** |
| StringToDataMedium                |  2402 |  8059 | +235.5% | **0.30x** |
| StringToDataSmall                 |  2340 |  5356 | +128.9% | **0.44x** |
| StringToDataEmpty                 |  2331 |  5187 | +122.5% | **0.45x** |
| ObjectiveCBridgeStubToNSStringRef |    98 |   118 |  +20.4% | **0.83x   |
| DataCreateMedium                  | 14881 | 17800 |  +19.6% | **0.84x** |
```
I haven't looked at any individually. Are these expected regressions?

I'm actually surprised that DataCreateMedium still lags, because the
Sequence initializer should be mostly optimized away now. Hopefully,
this is at least within the range that we can accept until the optimizer
has more time to mature.

Note that I see a ton of code being inlined now from Data's Sequence
initializer. If there's code that probably won't benefit from
inlining, that should be moved behind an `@inline(never)` attribute.

**Comment by itaiferber** [comment]
@atrick Thanks so much for putting in the effort on this stuff! Our concerns about `CreateArrayEmpty` and `CreateArrayMedium` appear to be resolved here, but I'm really concerned about what's happening in `DataCreateMedium`, and more so, the `StringToData` tests. I'll dig into these today to see if we can figure out what's going on, and if there's anything we can do to work around these issues at the implementation level

**Comment by itaiferber** [comment]
@atrick Upon reflection, it's entirely possible that we haven't conformed `String.UTF8View` to the necessary protocols to make this efficient; looking right now

**Comment by itaiferber** [comment]
@airspeedswift @atrick @milseman It looks like we're likely hitting this because `String.UTF8View` doesn't appear to have `withContiguousStorageIfAvailable`, so we're falling into byte-wise copying. Is this expected, or should `String.UTF8View` expose the underlying buffer?

**Comment by milseman** [comment]
IMO, we should fix `String.UTF8View` to expose this

**Comment by itaiferber** [comment]
@milseman @airspeedswift Should I file a Radar or should we track this in 30541077?

**Comment by itaiferber** [comment]
@atrick Otherwise these changes are great and unblock us!

**Comment by milseman** [comment]
Wherever, I'll try to push it soon.

**Comment by milseman** [comment]
https://github.com/apple/swift/pull/21178

**Comment by itaiferber** [comment]
@milseman I just filed 46601459 so we can track this appropriately internally too. Thanks for the quick turnaround!

**Pull request closed without merging**
