### PR TITLE
Fixed extraneous ')'

### LINKED ISSUE #71806: Code fails to compile: extraneous ')' before ';'
[This line](https://github.com/apple/swift/blame/766e6231d392e488059a6fd7b89a6f1aa6a24803/lib/Sema/TypeCheckDeclPrimary.cpp#L1037) does not compile:

```
TypeCheckDeclPrimary.cpp:1037:66: error: extraneous ')' before ';'
   ctx.Diags.diagnose(initExpr->getLoc(), diag::macro_unsupported));
                                                                  ^
```

### PR DESCRIPTION
**Pull request by dhoepfl**
Removed extraneous ')'.

Resolves #71806

### CODE REVIEW

**Comment by dhoepfl** [comment]
Sorry, I tried to rename the branch.

**Comment by slavapestov** [comment]
@bnbarham It looks like we don't have a CI job that tests with `SWIFT_BUILD_SWIFT_SYNTAX` off. Should we remove the build setting?

**Comment by bnbarham** [comment]
> @bnbarham It looks like we don't have a CI job that tests with SWIFT_BUILD_SWIFT_SYNTAX off. Should we remove the build setting?

I don't think we should remove it right now, but we are working our way towards it (CC @DougGregor). Might make sense to have a CI job for it specifically, though it's likely we'd still get cases like this as it wouldn't be a PR test.

**Comment by DougGregor** [comment]
@swift-ci please smoke test Windows

**Comment by DougGregor** [comment]
I don't think it's worth the effort to bring up a CI job where `SWIFT_BUILD_SWIFT_SYNTAX` is off, since our trajectory is toward requiring swift-syntax in all compiler builds.

**Pull request merged**
