### PR TITLE
[Migrator] Re-enable wrap_optional.swift test.

### PR DESCRIPTION
**Pull request by rudkx**
This had to be reworked a bit to deal with the fact that IUOs are no
longer a distinct type and there were uses of IUOs that are not
supported after SE-0054.

Fixes: rdar://problem/37040141

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Review by nathawes — APPROVED** [review]
LGTM – thanks!

**Comment by rudkx** [comment]
@swift-ci Please smoke test Linux platform

**Comment by rudkx** [comment]
@swift-ci Please smoke test OS X platform

**Pull request merged**
