### PR TITLE
[Sema] Improve handling of `fallthrough` in `if`/`switch` expressions

### LINKED ISSUE #75880: SILGen crash on `fallthrough` out of `if` expression
This hits an assert in SILGen:

```swift
struct Err: Error {}

func foo() throws {
  switch Bool.random() {
  case true:
    let x = if .random() {
      if .random () {
        fallthrough
      }
      throw Err()
    } else {
      0
    }
  case false:
    break
  }
}
```

```
Assertion failed: (result != SharedCases.end()), function getSharedCaseBlockDest, file SILGenPattern.cpp, line 2855.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.      Program arguments: /Users/hamish/src/swift-dev/build/Release/swift-macosx-arm64/bin/swift-frontend -typecheck /Users/hamish/src/swift-test-arena/main.swift -sdk /Users/hamish/src/MacOSX.sdk -debug-diagnostic-names -emit-silgen
1.      Swift version 6.0-dev (LLVM 57564d4877d6075, Swift 78daa4150554ef0)
2.      Compiling with effective version 5.10
3.      While evaluating request ASTLoweringRequest(Lowering AST to SIL for module main)
4.      While silgen emitFunction SIL function "@$s4main3fooyyKF".
 for 'foo()' (at /Users/hamish/src/swift-test-arena/main.swift:455:1)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x0000000107d9c230 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x0000000107d9a568 llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x0000000107d9c8cc SignalHandler(int) + 360
3  libsystem_platform.dylib 0x0000000180ce9a24 _sigtramp + 56
4  libsystem_pthread.dylib  0x0000000180cbacc0 pthread_kill + 288
5  libsystem_c.dylib        0x0000000180bcaa50 abort + 180
6  libsystem_c.dylib        0x0000000180bc9d6c err + 0
7  swift-frontend           0x0000000107f5f464 (anonymous namespace)::PatternMatchEmission::getSharedCaseBlockDest(swift::CaseStmt*) (.cold.2) + 0
8  swift-frontend           0x0000000102b8abc4 (anonymous namespace)::PatternMatchEmission::getSharedCaseBlockDest(swift::CaseStmt*) + 260
9  swift-frontend           0x0000000102b8a688 swift::Lowering::SILGenFunction::emitSwitchFallthrough(swift::FallthroughStmt*) + 88
10 swift-frontend           0x0000000102bbc3d4 swift::ASTVisitor<(anonymous namespace)::StmtEmitter, void, void, void, void, void, void>::visit(swift::Stmt*) + 4368
11 swift-frontend           0x0000000102bbd04c swift::ASTVisitor<(anonymous namespace)::StmtEmitter, void, void, void, void, void, void>::visit(swift::Stmt*) + 7560
12 swift-frontend           0x0000000102bbc3d4 swift::ASTVisitor<(anonymous namespace)::StmtEmitter, void, void, void, void, void, void>::visit(swift::Stmt*) + 4368
13 swift-frontend           0x0000000102bbd04c swift::ASTVisitor<(anonymous namespace)::StmtEmitter, void, void, void, void, void, void>::visit(swift::Stmt*) + 7560
14 swift-frontend           0x0000000102bbb2b8 swift::Lowering::SILGenFunction::emitStmt(swift::Stmt*) + 24
15 swift-frontend           0x0000000102b41020 (anonymous namespace)::RValueEmitter::visitSingleValueStmtExpr(swift::SingleValueStmtExpr*, swift::Lowering::SGFContext) + 408
16 swift-frontend           0x0000000102b28994 swift::Lowering::SILGenFunction::emitExprInto(swift::Expr*, swift::Lowering::Initialization*, std::__1::optional<swift::SILLocation>) + 156
17 swift-frontend           0x0000000102b160e8 swift::Lowering::SILGenFunction::emitPatternBinding(swift::PatternBindingDecl*, unsigned int, bool) + 1264
18 swift-frontend           0x0000000102b1ce88 swift::ASTVisitor<swift::Lowering::SILGenFunction, void, void, void, void, void, void>::visit(swift::Decl*) + 180
19 swift-frontend           0x0000000102bbc2e0 swift::ASTVisitor<(anonymous namespace)::StmtEmitter, void, void, void, void, void, void>::visit(swift::Stmt*) + 4124
20 swift-frontend           0x0000000102bbb2b8 swift::Lowering::SILGenFunction::emitStmt(swift::Stmt*) + 24
21 swift-frontend           0x0000000102b932c0 (anonymous namespace)::PatternMatchEmission::emitCaseBody(swift::CaseStmt*) + 40
22 swift-frontend           0x0000000102b93c94 void llvm::function_ref<void ((anonymous namespace)::PatternMatchEmission&, llvm::ArrayRef<swift::Lowering::ConsumableManagedValue>, (anonymous namespace)::ClauseRow&)>::callback_fn<swift::Lowering::SILGenFunction::emitSwitchStmt(swift::SwitchStmt*)::$_0>(long, (anonymous namespace)::PatternMatchEmission&, llvm::ArrayRef<swift::Lowering::ConsumableManagedValue>, (anonymous namespace)::ClauseRow&) + 1848
23 swift-frontend           0x0000000102b899e4 (anonymous namespace)::PatternMatchEmission::emitDispatch((anonymous namespace)::ClauseMatrix&, llvm::ArrayRef<swift::Lowering::ConsumableManagedValue>, std::__1::function<void (swift::SILLocation)> const&) + 2508
24 swift-frontend           0x0000000102b90a70 std::__1::__function::__func<(anonymous namespace)::PatternMatchEmission::emitSpecializedDispatch((anonymous namespace)::ClauseMatrix&, llvm::ArrayRef<swift::Lowering::ConsumableManagedValue>, unsigned int&, unsigned int, std::__1::function<void (swift::SILLocation)> const&)::$_11, std::__1::allocator<(anonymous namespace)::PatternMatchEmission::emitSpecializedDispatch((anonymous namespace)::ClauseMatrix&, llvm::ArrayRef<swift::Lowering::ConsumableManagedValue>, unsigned int&, unsigned int, std::__1::function<void (swift::SILLocation)> const&)::$_11>, void (llvm::ArrayRef<swift::Lowering::ConsumableManagedValue>, llvm::ArrayRef<(anonymous namespace)::SpecializedRow>, std::__1::function<void (swift::SILLocation)> const&)>::operator()(llvm::ArrayRef<swift::Lowering::ConsumableManagedValue>&&, llvm::ArrayRef<(anonymous namespace)::SpecializedRow>&&, std::__1::function<void (swift::SILLocation)> const&) + 1300
25 swift-frontend           0x0000000102b8db90 (anonymous namespace)::PatternMatchEmission::emitSpecializedDispatch((anonymous namespace)::ClauseMatrix&, llvm::ArrayRef<swift::Lowering::ConsumableManagedValue>, unsigned int&, unsigned int, std::__1::function<void (swift::SILLocation)> const&) + 4744
26 swift-frontend           0x0000000102b8935c (anonymous namespace)::PatternMatchEmission::emitDispatch((anonymous namespace)::ClauseMatrix&, llvm::ArrayRef<swift::Lowering::ConsumableManagedValue>, std::__1::function<void (swift::SILLocation)> const&) + 836
27 swift-frontend           0x0000000102b88554 swift::Lowering::SILGenFunction::emitSwitchStmt(swift::SwitchStmt*) + 5704
28 swift-frontend           0x0000000102bbc3d4 swift::ASTVisitor<(anonymous namespace)::StmtEmitter, void, void, void, void, void, void>::visit(swift::Stmt*) + 4368
29 swift-frontend           0x0000000102bbb2b8 swift::Lowering::SILGenFunction::emitStmt(swift::Stmt*) + 24
30 swift-frontend           0x0000000102b4d3fc swift::Lowering::SILGenFunction::emitFunction(swift::FuncDecl*) + 416
31 swift-frontend           0x0000000102ac02e0 swift::Lowering::SILGenModule::emitFunctionDefinition(swift::SILDeclRef, swift::SILFunction*) + 6360
32 swift-frontend           0x0000000102ac0fb4 swift::Lowering::SILGenModule::emitOrDelayFunction(swift::SILDeclRef) + 236
33 swift-frontend           0x0000000102abe9ec swift::Lowering::SILGenModule::emitFunction(swift::FuncDecl*) + 200
34 swift-frontend           0x0000000102ac34a4 swift::ASTLoweringRequest::evaluate(swift::Evaluator&, swift::ASTLoweringDescriptor) const + 756
35 swift-frontend           0x0000000102bbacec swift::SimpleRequest<swift::ASTLoweringRequest, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>> (swift::ASTLoweringDescriptor), (swift::RequestFlags)17>::evaluateRequest(swift::ASTLoweringRequest const&, swift::Evaluator&) + 132
36 swift-frontend           0x0000000102ac8b58 swift::ASTLoweringRequest::OutputType swift::Evaluator::getResultUncached<swift::ASTLoweringRequest, swift::ASTLoweringRequest::OutputType swift::evaluateOrFatal<swift::ASTLoweringRequest>(swift::Evaluator&, swift::ASTLoweringRequest)::'lambda'()>(swift::ASTLoweringRequest const&, swift::ASTLoweringRequest::OutputType swift::evaluateOrFatal<swift::ASTLoweringRequest>(swift::Evaluator&, swift::ASTLoweringRequest)::'lambda'()) + 324
37 swift-frontend           0x0000000102ac3b8c swift::performASTLowering(swift::ModuleDecl*, swift::Lowering::TypeConverter&, swift::SILOptions const&, swift::IRGenOptions const*) + 132
38 swift-frontend           0x00000001024e5ca0 swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 724
39 swift-frontend           0x00000001024f24c0 withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) + 160
40 swift-frontend           0x00000001024e770c performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 708
41 swift-frontend           0x00000001024e6eac swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 2240
42 swift-frontend           0x00000001022ffdd4 swift::mainEntry(int, char const**) + 3108
43 dyld                     0x0000000180941058 start + 2224
fish: Job 1, './swift -frontend -typecheck ~/…' terminated by signal SIGABRT (Abort)
```

### PR DESCRIPTION
**Pull request by hamishknight**
Remove the restriction on `fallthrough` as the last statement in a `switch` expression, and prevent fallthrough from jumping out of `if` expressions.

rdar://127670432
rdar://133845101
Resolves #75880

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
@swift-ci please test Linux

**Comment by hamishknight** [comment]
@swift-ci please test Linux

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Review by xedin — APPROVED** [review]

**Pull request merged**
