### PR TITLE
[SIL] Don't print duplicated import decls

### PR DESCRIPTION
**Pull request by kitasuke**
## Issue
If we pass a raw SIL file as input to sil-opt, we get duplicated import declarations like below.
Here is commands to reproduce

### sil-opt
```
$sil-opt input.sil > output.sil
```

input.sil
```
sil_stage raw

import Builtin
import Swift
import SwiftShims

func foo() {}
...
```

output.sil
```
sil_stage raw

import Builtin
import Swift
import SwiftShims

import Builtin

import Swift

import SwiftShims

func foo() {}
...
```

### swiftc

```
$swiftc -emit-sil input.sil > output.sil
```

input.sil
```
sil_stage raw

import Builtin
import Swift
import SwiftShims

func foo() {}
...
```

output.sil
```
sil_stage canonical

import Builtin
import Swift
import SwiftShims

import Builtin

import Swift

import SwiftShims

func foo() {}
...
```

## Why
swiftc goes through `ASTPrinter` for each decl including `ImportDecl` in `SILPrinter`. So if we already have import decls in silgen, it prints the import decls twice in `SILPrinter` and `ASTPrinter`.

## Fix

Let's skip to visit  `visitImportDecl` so that we wouldn't have the duplicated import decls.

### CODE REVIEW

**Comment by slavapestov** [comment]
Can you add a test?

**Comment by kitasuke** [comment]
I added test/sil-opt/import-decls.silgen, but was it not enough to check import declarations?

**Comment by kitasuke** [comment]
I found out that this is not a specific issue for `sil-opt`. Same output is emitted when `swiftc` takes raw SIL to emit canonical SIL. Is it more appropriate to put the test case in test/SIL then?

**Review by slavapestov — COMMENTED** [review]
This test will still pass with your change reverted. You need to build and import a custom module. And as you said this is not specific to sil-opt and should be moved to test/SIL.

**Comment by kitasuke** [comment]
Addressed your feedback. Hope I correctly understood what you suggested.

**Comment by slavapestov** [comment]
Looks good, thanks!

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by kitasuke** [comment]
I really appreciate for your all the feedbacks!

**Pull request merged**
