### PR TITLE
[semantic-arc-opts] Change to always use the worklist.

### PR DESCRIPTION
**Pull request by gottesmm**
Previously we were:

1. Doing a linear scan, performing certain optimizations, and setting up a
worklist for future processing.

2. Draining the worklist of changed instructions until we reached a fix point.

The key thing here is that for (1) to be safe, we would need to not perform any
optimizations on block arguments since there was an ssumption that we would only
perform SSA-like optimizations.

I am going to be adding such optimizations soon, so it makes sense to just
convert the initial traversal to non-destructively seed the worklist and
eliminate that initial optimization pass.

This should be NFC.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
I am fixing the outliner bug. The problem is that I am eliminating an extra release breaking the pattern matching.

My solution is to just teach the outliner that if it doesn't have that missing release that it should make an outlined function with a guaranteed parameter.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by Catfish-Man** [comment]
20% improvement to NSString -> Swift String -> NSString conversion round trips :) nice!

**Comment by gottesmm** [comment]
Was just thinking about the outliner change here. Fundamentally without the release that we were peepholing before, outlining like this is not safe. That being said, I have a solution: outline with a coroutine. This will let me keep the original initial conversion in the same spot and not have to worry about lifetime extending inappropriately.

**Comment by gottesmm** [comment]
I talked with Arnold about the outliner thing. I am going to change the bridge argument code to handle this case with additional safety.

**Comment by gottesmm** [comment]
I am going to split out the outliner change into another PR.

**Comment by gottesmm** [comment]
Actually, I am going to put this down for a little bit.

**Comment by gottesmm** [comment]
Redoing the testing here.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
mmm... I forgot about that outliner issue.

**Comment by gottesmm** [comment]
I took a bit of a closer look at this. The code pattern that we are looking at is:

```
%15 = function_ref @$SSS10FoundationE19_bridgeToObjectiveCSo8NSStringCyF
%16 = apply %15(%14) : $@convention(method) (@guaranteed String) -> @owned NSString
%17 = enum $Optional<NSString>, #Optional.some!enumelt.1, %16 : $NSString
release_value %14 : $String
...
apply %objcMethod(%17, ...)  : $@convention(objc_method) (Optional<NSString> ...) ->
release_value %17 : $Optional<NSString>
```

From what I am reading in the code, we do not find the release_value of %14 due to better optimization. In such a case since we are going to use %14 in a guaranteed way anyways, we can just pass %14 as a guaranteed parameter without worry.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
The only regression I could reproduce is LazilyFilteredArrayContains. The rest are noise.

**Comment by gottesmm** [comment]
In terms of improvements, I am seeing that all are real improvements except for static array.

**Comment by gottesmm** [comment]
I think the difference in that lazy benchmark is a weird cache effect. The reason why I am pretty confidant of this is that:

1. In the benchmark everything except for retain/release calls have been inlined into the benchmark. So we know that we are not calling any stdlib code directly.
2. When I look at the assembly, the only differences are:

```
--- before.s	2019-12-06 15:44:03.000000000 -0800
+++ after.s	2019-12-06 15:44:20.000000000 -0800
@@ -113,14 +113,14 @@
 +0x1b2	    jmp                 "run_LazilyFilteredArrayContains(_:)+0x23"
 +0x1b7	ud2
 +0x1b9	ud2
-+0x1bb	leaq                1372206(%rip), %rdi
++0x1bb	leaq                1372214(%rip), %rdi
 +0x1c2	callq               "__swift_instantiateConcreteTypeFromMangledName"
 +0x1c7	movl                $64, %esi
 +0x1cc	movl                $7, %edx
 +0x1d1	movq                %rax, %rdi
 +0x1d4	callq               "DYLD-STUB$$swift_allocObject"
 +0x1d9	movq                %rax, %r15
-+0x1dc	movaps              1118573(%rip), %xmm0
++0x1dc	movaps              1118589(%rip), %xmm0
 +0x1e3	movups              %xmm0, 16(%rax)
 +0x1e7	movq                $0, -64(%rbp)
 +0x1ef	movabsq             $-2305843009213693952, %rax
@@ -128,7 +128,7 @@
 +0x1fd	leaq                -64(%rbp), %r13
 +0x201	movl                $29, %edi
 +0x206	callq               "DYLD-STUB$$_StringGuts.grow(_:)"
-+0x20b	leaq                1163982(%rip), %rax
++0x20b	leaq                1163998(%rip), %rax
 +0x212	movabsq             $-9223372036854775808, %rdx
 +0x21c	orq                 %rax, %rdx
 +0x21f	movq                1318170(%rip), %r13
@@ -139,7 +139,7 @@
 +0x23e	movq                %r13, %rcx
 +0x241	movq                %r12, %r8
 +0x244	callq               "DYLD-STUB$$String.write<A>(to:)"
-+0x249	leaq                1208176(%rip), %rdi
++0x249	leaq                1208192(%rip), %rdi
 +0x250	movl                $35, %esi
 +0x255	movl                $2, %edx
 +0x25a	callq               "DYLD-STUB$$StaticString.description.getter"
@@ -157,7 +157,7 @@
 +0x28d	movq                %r13, %rcx
 +0x290	movq                %r12, %r8
 +0x293	callq               "DYLD-STUB$$String.write<A>(to:)"
-+0x298	leaq                1207841(%rip), %rdi
++0x298	leaq                1207857(%rip), %rdi
 +0x29f	movl                $81, %esi
 +0x2a4	movl                $2, %edx
 +0x2a9	callq               "DYLD-STUB$$StaticString.description.getter"
```

I.e. some constant is offset by 16. I wonder if we need to do something to fix the alignment of globals. Not sure.

**Pull request merged**
