### PR TITLE
Clean up CMAKE logic around choice of executor for concurrency runtime

### PR DESCRIPTION
**Pull request by rokhinip**
Clean up Concurrency build system so that all the logic around choice of which executor to choose for which preset, is consolidated to one place and we have a single knob we use to determine when to use dispatch as our global executor.

Radar-Id: rdar://problem/119416196

### CODE REVIEW

**Review by kubamracek — APPROVED** [review]

**Comment by rokhinip** [comment]
@swift-ci please test

**Comment by rokhinip** [comment]
@swift-ci please test

**Comment by rokhinip** [comment]
@swift-ci test linux

**Comment by rokhinip** [comment]
@swift-ci test linux

**Comment by rokhinip** [comment]
@swift-ci please test

**Pull request merged**
