### PR TITLE
[dev-scripts] Upstream some scripts for producing scurves from csv files and graphing.

### PR DESCRIPTION
**Pull request by gottesmm**
These are two small scripts that can be used to output scurves to show performance data. SCurves are a technique used to show how an optimization effects a set of tests in a way that makes it easy to visualize the % of the tests that have improved or degraded. For instance based off of some code-size work I did recently, this is the output from these scripts used together:

out

Notice how one can really easily tell that 5% of the benchmarks reduced in code-size by 10% and that we do not have any regressions really.

I am upstreaming this b/c @atrick and others have asked me how I produce these (which I used to do by hand). Rather than doing it by hand, I scripted this so I can forget how to do this and hopefully make people's lives easier.

### CODE REVIEW

**Comment by gottesmm** [comment]
@atrick a gift for you. = ).

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
should have linted first...

**Comment by atrick** [comment]
@gottesmm cool. I love these graphs. As long as people label the Y axis "time" or "speed" appropriately.

**Comment by gottesmm** [comment]
@atrick this is just computing % change, so I am not sure if it is relevant? That would happen before. That being said, I am happy to provide both of those as an option to put on the y-axis. Maybe that with an explanation will make people think about what they are doing more.

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@atrick Also, I don't take any credit for knowing about them. I think I learned how to make them from @stephentyrone actually. Many many years ago... but maybe my memory is wrong.

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by stephentyrone** [comment]
@gottesmm Could be! (Anyway we can get log-scale y-axis?)

**Comment by gottesmm** [comment]
of course!

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@stephentyrone I was unable to get the log scale to work how I wanted it to. = (. I am out of time messing with this (I need to move on). I'll swing around at some point. Can you file an SR for that?

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Pull request merged**
