### PR TITLE
Adapted the test in debug_scope.swift into a new one, which generates sends/recvs when -Onone is turned on.

### PR DESCRIPTION
**Pull request by mhong**
Filed https://bugs.swift.org/browse/SR-8395 for it.

### CODE REVIEW

**Comment by mhong** [comment]
@swift-ci please test tensorflow

**Review by rxwei — APPROVED** [review]
LGTM. `no_copy` can be treated as the gold standard for deabstraction. Here's where we collected a whole lot of unexpected sends/receives before send/receive was implemented. When `-Onone` code generates no send/receives for this test file except for `debug_value`, we can say deabstraction is done.

**Comment by mhong** [comment]
+1. On `debug_value`, perhaps we can use a separate flag from `-Onone` to retain them (how about `-g`?), This way no_copy.swift will be free of sends/recvs, when we use `-Onone` there.

Also this would seem to correspond to C/C++ compilers: -g makes the binary debuggable. without it or -O, the generated binary is not optimized, but not debuggable either.

**Comment by rxwei** [comment]
Makes sense. Swift already has `-g`.
```
  -g                      Emit debug info. This is the preferred setting for debugging with LLDB.
```

I can land a patch to do that.

**Pull request merged**
