### PR TITLE
Sema: Warn on all non-resilient uses of `@_implementationOnly import`, even for clang targets

### PR DESCRIPTION
**Pull request by xymus**
The warning about `using '@_implementationOnly' without enabling library evolution for 'client' may lead to instability during execution` was wrongly restricted to only imports of Swift modules. Make sure they are raised for imports of clang modules as well.

rdar://135233043

### CODE REVIEW

**Review by tshortli — APPROVED** [review]

**Comment by xymus** [comment]
@swift-ci Please smoke test

I reviewed the new logic to keep the warning to use `internal import` instead of `@_implementationOnly` to imports of Swift modules only. This warning can be noisy, limiting it may prevent users from outright learning to ignore it. Typical uses of an `@_implementationOnly` import of a clang module is often for a project internal module instead of a wider layering concern as we have with Swift module targets. We can leave legacy uses of `@_implementationOnly` in peace for now.

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by xymus** [comment]
@tshortli My last change only silenced the deprecation warning in resilient modules. That's generally reliable, the one miscompile there I'm aware of would be with test clients that can't load the dependency because of different search paths. It's rare but maybe it's worth the warning.

**Comment by tshortli** [comment]
Oh, I misunderstood, thanks for clarifying. I have debugged miscompiles stemming from the combination of `@_implementationOnly import` and `@testable` imports of resilient libraries, but I agree it's way more niche and perhaps not worth the noise. I think _eventually_ we should warn about it, though.

**Pull request merged**
