### PR TITLE
Fix a static_assert, add a new one, and improve one other.

### PR DESCRIPTION
**Pull request by rudkx**
#### What's in this pull request?

Fix a few static_assert issues I noticed by inspection in Expr.h.

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

Noticed by inspection.

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please test.

@DougGregor Doug, can you take a look?

**Comment by rudkx** [comment]
@swift-ci Please test.

**Comment by rudkx** [comment]
@DougGregor Doug, can you take a look?

**Comment by DougGregor** [comment]
LGTM!

**Comment by rudkx** [comment]
The Linux LLDB build has been broken all afternoon, and that's the only failure I see here.

**Pull request merged**
