### PR TITLE
[WIP] Add benchmark for sorting different data shapes and types.

### PR DESCRIPTION
**Pull request by natecook1000**
I'm not sure if I have the counts/sizes right for making these benchmarks significant, so 🤞. This might render some of the other sorting benchmarks redundant.

### CODE REVIEW

**Comment by natecook1000** [comment]
@swift-ci please smoke benchmark

**Comment by natecook1000** [comment]
@swift-ci Please smoke benchmark

**Comment by eeckstein** [comment]
These are a lot of new benchmarks. The problem is that it increases the total benchmark runtime. Do we really need all combinations?
Also, the runtime for some benchmarks is quite small. Ideally they should be around 1000, which corresponds to 1ms.

**Comment by natecook1000** [comment]
@eeckstein Is there a way to designate them as only to be run when requested? It's important to able to test these different scenarios, for evaluating different sort implementations, but they probably don't need to be run as part of every benchmark test.

**Comment by eeckstein** [comment]
@natecook1000 Yes. You can add a new tag in the BenchmarkCategory enum, like 'sorting' and add both 'sorting' and 'skip' to the benchmark info. Then they will be skipped by default and just run if you specify:
  Benchmark_O --skip-tags='' --tags='sorting'

Currently we don't have support to pass these options to the "swift-ci benchmark" command. But if you are experimenting it's better to the benchmarks locally, anyway.

**Pull request closed without merging**
