### PR TITLE
[runtime] Fix lookup of NSObject : Hashable conformance.

### PR DESCRIPTION
**Pull request by gparker42**

### CODE REVIEW

**Comment by gparker42** [comment]
@jckarter, any suggestions for a test that might exercise this path? The symbol name was wrong when it was first written so I assume it has never been tested.

**Comment by gparker42** [comment]
(I added a call to `getNSErrorConformanceToHashable()` at a random place in the runtime to verify that the new lookup does find the symbol, but we can't put that into the test suite.)

**Comment by jckarter** [comment]
I think this code path doesn't ever get exercised. We only call `getHashableConformance()` in order to implement the `-isEqual:` method on `_SwiftNativeNSError` by forwarding to the `==` operation in the underlying bridged Swift error value. If you're using an actual `NSError`, then you'd of course go through the default `- [NSError isEqual:]` implementation. We could probably drop this code to look up the Hashable conformance and instead assert that we only ever ask for the Hashable conformance of a `_SwiftNativeNSError`.

**Comment by gparker42** [comment]
Thanks, Joe. I'll push this change as-is and file a followup to investigate whether we need this code at all.

**Comment by gparker42** [comment]
@swift-ci please smoke test

**Comment by gparker42** [comment]
@swift-ci please smoke test linux

**Comment by gparker42** [comment]
@swift-ci please smoke test

**Comment by gparker42** [comment]
@swift-ci please smoke test macosx

**Review by jckarter — APPROVED** [review]
Sounds good.

**Pull request merged**
