### PR TITLE
Fix test/IRGen/objc_generic_class_stub.swift for 32-bit platforms

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes <rdar://problem/71476765>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test macOS

**Review by atrick — APPROVED** [review]
Thanks. I'll let the PR test complete since it's not urgent.

**Comment by slavapestov** [comment]
@swift-ci Please clean smoke test Linux

**Pull request merged**
