### PR TITLE
Disable failing concurrency tests on windows

### PR DESCRIPTION
**Pull request by aschwaighofer**
SR-14333

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test

**Comment by aschwaighofer** [comment]
@swift-ci Please test windows

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test os x

**Review by ktoso — APPROVED** [review]
LGTM, lets disable for now indeed

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test os x

**Comment by drodriguez** [comment]
Just to make things more fun, this test seems to have started **passing** in the VS2017 machine (https://ci-external.swift.org/job/oss-swift-windows-x86_64/7043/console notice that it says "Unexpectedly Passed Tests"). It still passed from time to time in the VS2019 (for example https://ci-external.swift.org/job/oss-swift-windows-x86_64-vs2019/4783/console).

To avoid the flakiness creating random errors, I used `UNSUPPORTED` instead of `XFAIL` in #36530. I wonder if these `XFAIL` should be changed to `UNSUPPORTED` (or maybe only `throwing.swift`).

/cc @compnerd

**Pull request merged**
