### PR TITLE
Preserve source trivia in the lexer

### PR DESCRIPTION
**Pull request by bitjammer**
Start preserving source trivia such as whitespace and comments in tokens for use in a purely syntactic tree.

### CODE REVIEW

**Comment by bitjammer** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
Gotta ask: how does this affect compilation time and memory use in a normal build? (e.g. of the standard library)

**Comment by bitjammer** [comment]
In release-assert builds, about 2.5% time (max absolute penalty was 200 microseconds) and about 0.2% memory. I tested about 4k of the single-file tests, parse-only. I didn't notice any change in the standard library builds.

**Comment by lattner** [comment]
2.5% is a huge performance cost, if it affects the normal compiler.  This is a very large and model changing patch, have you gotten this reviewed by any one else?

**Comment by bitjammer** [comment]
I think we can bring that number down further and also possibly discard if it's still not acceptable. We discussed the general approach a little bit already with @DougGregor – Doug, can you or someone else review? @jrose-apple already suggested trying switching to `SmallVector` or the like to store leading and trailing trivia in tokens.

**Comment by bitjammer** [comment]
Sorry, one more thing: I was a little vague about my measurement. The time penalty is based on a measurement of `parseIntoSourceFile`-- I patched the compiler for those tests to take `std::chrono::high_resolution_clock` just before and after the call to that function. So, that percentage is going to be much smaller in the context of the whole compile. I can gather those numbers too, if that's not compelling.

**Comment by jrose-apple** [comment]
Ah, a 2.5% increase in _parse_ time is not nearly as bad. It's still something that has quadratic effect across a target, though, so any obvious improvements are probably worth it. (There's probably other parts of Parse we could improve as well, not to mention avoiding parsing function bodies in normal multi-file compilation.)

**Comment by bitjammer** [comment]
OK, so here's what I'm planning to do:
- Set up a parse performance bot. It might be nice to have a flag like -dump-parse but doesn't actually dump. (`-parse-only`? Rename `-parse` to `-sema`?)
- Revert this patch. I can add a flag to skip the collection work for batch compiles but I want to see if a flag is sufficient to skip enough work for it to still be worth it. I have a feeling I'll need to decouple the leading and trailing trivia from the token anyway, so I would rather just rework the patch and do more intense profiling before putting it back in. Provided we can get acceptable numbers, I'll have someone look at it then.

**Pull request merged**
