### PR TITLE
[Parse] Eliminate backtracking in collection expression parsing

### PR DESCRIPTION
**Pull request by rintaro**
Parsing collection literal expression used to take exponential time depending on the nesting level of the first element.

Stop using `parseList()` because using it complicates libSyntax parsing.

[SR-9220](https://bugs.swift.org/browse/SR-9220) / rdar://problem/45221238
[SR-7283](https://bugs.swift.org/browse/SR-7283) / rdar://problem/38913395

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
Cool, I wonder if your PR fixes this bug too: https://github.com/apple/swift/pull/15619/files#diff-1a9565d4ad49da3f2dcb708fa95d21a3

**Review by nkcsgexi — APPROVED** [review]
LGTM, Thanks for fixing this!

**Comment by rintaro** [comment]
@slavapestov Yes it fixes that. Thank you for the link. I added a test case from #15619 .

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Pull request merged**
