### PR TITLE
Add some cool badges to README

### PR DESCRIPTION
**Pull request by frootloops**

### CODE REVIEW

**Comment by azdavis** [comment]
:-1: to removing the logo but :+1: to the badges

**Comment by frootloops** [comment]
@azdavis thanks

**Comment by jrose-apple** [comment]
I don't think this really adds anything, other than perhaps the license one.

**Comment by frootloops** [comment]
@jrose-apple like that?

**Comment by gribozavr** [comment]
The badge is not exactly correct, the license is "Apache with runtime exception".

**Comment by jrose-apple** [comment]
That is what I meant, yes—simply because some people will immediately dismiss a project based on its license. I'll let someone else decide if it's a good change.

**Comment by frootloops** [comment]
@gribozavr check out the update. Is it look ok? :)

**Comment by gribozavr** [comment]
Seems fine to me!  @jrose-apple, what do you think?

**Comment by gribozavr** [comment]
@frootloops Sorry, could you change the badge so that it says "Apache 2.0 with runtime exception"?

**Comment by frootloops** [comment]
@gribozavr done

**Comment by gribozavr** [comment]
LGTM.  Over to @jrose-apple.

**Comment by nadavrot** [comment]
:-1:   I am not sure why we need the badges.

**Pull request closed without merging**
