### PR TITLE
Evolution: Some of these tests pass with swift_test_mode_optimize_none_with_implicit_dynamic

### PR DESCRIPTION
**Pull request by slavapestov**
The remaining failures still warrant investigation.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by aschwaighofer** [comment]
Thank you. The ones that are still failing might just be failing because -enable-private-import makes non external symbols external and then the symbol comparison fails. At least that was what was happening with the one failing that I have looked at so far. My plan is to only enable implicit dynamic for public symbols under enable-library-evolution. I can either do this under another flag for testing or always after clients of the feature have adopted something like https://github.com/apple/swift/pull/25246.

**Comment by slavapestov** [comment]
@aschwaighofer How about we just skip the symbol comparison step when implicit dynamic is on? As long as we still run the tests with implicit dynamic off as well we should get the right amount of test coverage.

**Comment by aschwaighofer** [comment]
Yes that would make total sense.

**Comment by slavapestov** [comment]
Ok, I can try that in a follow-up PR. Thanks!

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Pull request merged**
