### PR TITLE
GSB: Fix maybeResolveEquivalenceClass() with member type of concrete type

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes <rdar://problem/55401811>, <https://bugs.swift.org/browse/SR-11475>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Review by DougGregor — COMMENTED** [review]
Nice!

**Pull request merged**
