### PR TITLE
[di] Debride dead code from splitting PMO/DI and hide state in preparation for other commits.

### PR DESCRIPTION
**Pull request by gottesmm**
This PR contains two different commits that both eliminate code from DI that is guaranteed dead. They both exist due to the manner in which DI/PMO were split (the pass was carbon copied and then tons of constant propagation+DCE was done).

Specifically:

1. In the first commit, we ignore that collectUses always assert that our argument is an address type, so a destructure (or tuple_extract for that matter, which this code used to be), could never have been called.
2. In the second commit, I constant propagate two boolean parameters to DI's eliminate list that are always set to constant values. Then I DCE as appropriate.

### CODE REVIEW

**Comment by gottesmm** [comment]
I am trying to fix project_box et al so I am looking at DI since I need to make some improvements there. As I read the code I found these issues.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test linux platform

**Comment by gottesmm** [comment]
@swift-ci test windows platform

**Comment by gottesmm** [comment]
I did some more simplifications around this code, and I am going to include it here since it is all just NFC cleanups.

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Review by atrick — COMMENTED** [review]
Looks good.

**Pull request merged**
