### PR TITLE
Existentials don't always conform to a protocol via an abstract confo…

### PR DESCRIPTION
**Pull request by aschwaighofer**
…rmance

So it is not always correct to use the current conformance when substituting.

rdar://62894495

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test source compatibility

**Comment by aschwaighofer** [comment]
@swift-ci Please test source compatibility

**Comment by aschwaighofer** [comment]
@swift-ci please test source compatibility release

**Review by slavapestov — APPROVED** [review]
I guess the right long-term fix is to have opened archetypes store conformances or something like that.

**Comment by aschwaighofer** [comment]
@swift-ci please test source compatibility release

**Comment by aschwaighofer** [comment]
@swift-ci Please test source compatibility release

**Pull request merged**
