### PR TITLE
Streamline fixed-size buffers in the standard library

### PR DESCRIPTION
**Pull request by stephentyrone**
- It turns out that 16 is the only size that the stdlib actually uses with _FixedArray, so the .gyb isn't eliminating any boilerplate anyway; make it a normal Swift file.
- _SmallBuffer<T> simply isn't used *at all*, so get rid of it.

### CODE REVIEW

**Comment by stephentyrone** [comment]
@swift-ci smoke test

**Review by lorentey — APPROVED** [review]

**Comment by stephentyrone** [comment]
@swift-ci test and merge

**Comment by gottesmm** [comment]
Woot!

**Comment by gottesmm** [comment]
@swift-ci test and merge

**Comment by gottesmm** [comment]
@swift-ci test and merge

**Pull request merged**
