### PR TITLE
[Concurrency] Add availability to Concurrency APIs.

### PR DESCRIPTION
**Pull request by mikeash**
This allows programs to target older OSes while using Concurrency behind an availability check. When targeting older OSes, the symbols are weak-linked and the compiler will require the use of Concurrency features to be guarded by an availability check.

rdar://75850003

### CODE REVIEW

**Review by DougGregor — APPROVED** [review]
Thank you!

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
Only macOS failures are unrelated LLDB ones. Merging.

**Pull request merged**
