### PR TITLE
Quell some warnings about casting in the runtime.

### PR DESCRIPTION
**Pull request by jckarter**

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
:-( Please fix this with a `const_cast`, not by chaining reinterpret_casts.

**Comment by jckarter** [comment]
That makes it more verbose, but does it really make it clearer?

**Comment by jckarter** [comment]
The types here are already "wrong", and a combination of const_cast(reinterpret_cast()) allows conversion from any type to any other, so I don't really see how it improves maintainability either.

**Pull request merged**
