### PR TITLE
[stdlib] NFC: Fix var to let warning

### PR DESCRIPTION
**Pull request by davezarzycki**

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci pease smoke test and merge

**Comment by davezarzycki** [comment]
@swift-ci pease smoke test and merge

**Comment by gottesmm** [comment]
@davezarzycki I wonder if pease really makes swift-ci fail... Lets see.

**Comment by gottesmm** [comment]
@swift-ci peace smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
Yea I think it was the "peace" typo.

**Pull request merged**
