### PR TITLE
[CSRanking] Prefer protocol init over non-required one from a class

### PR DESCRIPTION
**Pull request by xedin**
Resolves: rdar://problem/52477337

### CODE REVIEW

**Comment by xedin** [comment]
@jrose-apple I'm not sure whether it's a good rule to always prefer required initializer over one in protocol (since we don't know what the base is) or skip this rule for initializers all together.

**Comment by jrose-apple** [comment]
I don't know if this is correct either. If the protocol *doesn't* declare an initializer, the code still isn't valid.

**Comment by xedin** [comment]
@jrose-apple This is happening when we have already formed a solution and when there is a protocol required `init` vs. `init` on something else nominal.

**Review by jrose-apple — CHANGES_REQUESTED** [review]
(We're talking about this in an Apple-internal chat.)

**Comment by xedin** [comment]
Ok, I'm going to close this one and try to remove the hack we have in constructor validation.

**Pull request closed without merging**
