### PR TITLE
Convert "armv7l" to "armv7" for the architecture component of paths

### PR DESCRIPTION
**Pull request by RLovelett**
#### What's in this pull request?

Convert "armv7l" to "armv7" for the architecture component of paths

On the Raspberry Pi 2 when trying to import Glibc, without this patch, it will attempt to find the module map at `"/usr/lib/swift/linux/armv7l/glibc.modulemap"` and fail to do so.

With this patch it will attempt to find the module map at `"/usr/lib/swift/linux/armv7/glibc.modulemap"` where it will succeed in finding the module map.

Similar behavior currently happens in the Driver and Frontend. To DRY up this behavior it has been extracted to the Swift platform.
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

/cc: @hpux735 I think he originally wrote some of this stuff. He might be able to provide pointers on pitfalls.

### CODE REVIEW

**Comment by hpux735** [comment]
LGTM.  Provided it passes tests, I think it's a good change.

**Comment by jrose-apple** [comment]
The "magic" aspect here goes with the "section", not with the "arch". I think we've been calling these "major architectures".

@swift-ci Please test

**Comment by RLovelett** [comment]
`getSectionMagicArch` -> `getMajorArchitectureName`?

**Comment by jrose-apple** [comment]
Works for me!

**Comment by RLovelett** [comment]
Well both builds failed ([OS X](https://ci.swift.org/job/swift-PR-osx/1049/) and [Linux](https://ci.swift.org/job/swift-PR-Linux/1330/)). Though I cannot understand how my change broke either.

**Comment by RLovelett** [comment]
I've gone ahead and rebased this on 3105ef9bf1d23d5130652a6f45746d038b8645c9.

**Comment by jrose-apple** [comment]
I think master was just broken. Let's try again.

@swift-ci Please test

**Comment by RLovelett** [comment]
[According to the mailing list the error that the OS X build is failing on comes from elsewhere.](https://lists.swift.org/pipermail/swift-lldb-dev/Week-of-Mon-20160502/000140.html)

Though I'm unsure of what I need to do to get it to pass on the CI.

**Comment by jrose-apple** [comment]
Well, this literally isn't changing *any* Darwin-related code, and the incremental bots are passing, so I'll take it anyway. Thanks, Ryan!

**Pull request merged**
