### PR TITLE
[AST] Only use serialized locs for 'getRawComment()' in symbol graph

### PR DESCRIPTION
**Pull request by rintaro**
* Don't use serialized source locations in `getRawComment()` by default
* Only call `getSerialiedLocs()` for decls in `SerializedASTFile` (Calling it for `SourceFile` decls is useless)
* Propagate `AllowSerialized` parameter in `findRequirementDeclWithDocComment()` (I just noticed this when investigating the issue)

rdar://problem/75010520

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@bitjammer What's was the intension of the change? https://github.com/apple/swift/commit/69c4fc47cba74c93712056bb821312d89da4ce78#diff-d87e42f4d1c72f623a9f9246f244b1ad6f375fa7d1dce3d162ebb302d17f8922R869

**Comment by rintaro** [comment]
@swift-ci Please smoke test Windows

**Comment by rintaro** [comment]
@swift-ci Please smoke test Linux

**Review by benlangmuir — APPROVED** [review]

**Comment by rintaro** [comment]
Merging because this is causing serious performance regression. @bitjammer Let me know if you have any concern.

**Comment by bitjammer** [comment]
@rintaro I was investigating what I thought was a bug with serialized source locations at the time but it turned out to be nothing. Thank you for fixing the regression.

**Pull request merged**
