### PR TITLE
Add pull request template to support new feature provide by GitHub

### PR DESCRIPTION
**Pull request by shahmishal**
#### What's in this pull request?

This commit will enable pull request template. 
#### Resolved bug number: N/A

---

Before merging this pull request to apple/swift repository:
- [x] Test pull request on Swift continuous integration.

<details> 
  <summary>

Triggering Swift CI </summary>

The swift-ci is triggered by writing a comment on this PR addressed to the github user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by dduan** [comment]
So meta!

**Comment by gottesmm** [comment]
I only have one thing to say to that:

**Comment by gottesmm** [comment]
I mean:

**Comment by gottesmm** [comment]
Thanks for making the changes Mishal. The parts about trigger the swift ci look good to me.

**Pull request merged**
