### PR TITLE
Replace all 9999 availability in non-stdlib tests.

### PR DESCRIPTION
**Pull request by stephentyrone**
Follow-on to https://github.com/apple/swift/pull/26108

### CODE REVIEW

**Comment by stephentyrone** [comment]
@jckarter Mainly tagging you to check that you folks haven't yet added anything to these tests that actually *shouldn't* be available in 5.1-aligned SDKs, and that there aren't other reasons to maintain 9999 for these.

**Comment by stephentyrone** [comment]
@swift-ci please test

**Comment by stephentyrone** [comment]
@swift-ci please test

**Comment by stephentyrone** [comment]
Linux failure is in LLDB, looks unrelated to this change: 09:44:25 error: missing required modules: 'Swift', 'SwiftOnoneSupport'

Modules again?

**Review by jckarter — APPROVED** [review]
Looks good.

**Comment by stephentyrone** [comment]
@swift-ci smoke test linux

**Comment by stephentyrone** [comment]
Checked in with @dcci about the LLDB failures, we think this is not a PR blocker, so merging with the linux smoke-test only.

**Pull request merged**
