### PR TITLE
[WIP] Add _BinaryInteger to break ambiguities in comparison

### PR DESCRIPTION
**Pull request by xwu**
SE-0104 introduces heterogeneous overloads for equality and comparison operators. However, this leads to an issue during some comparisons with a literal where the typechecker prefers heterogeneous comparison with an `Int` over homogeneous comparison, as reported in [SR-4984](https://bugs.swift.org/browse/SR-4984):

```
(swift) UInt() != 0xFFFF_FFFF_FFFF_FFFF
<REPL Input>:1:11: error: integer literal '18446744073709551615' overflows when stored into 'Int'
UInt() != 0xFFFF_FFFF_FFFF_FFFF
          ^
```

However, `UInt() == 0XFFFF_FFFF_FFFF_FFFF` works as expected.

This issue can be solved for concrete types by moving derived (in)equality and comparison operators to concrete types, as in #9909. However, the same defect would continue to persist with generic code.

Since the aim of SE-0104 was to enable better and more generic algorithms, a complete resolution is in order. This PR adds an implementation detail of `BinaryInteger` named `_BinaryInteger`, which contains the derived heterogeneous (in)equality and comparison operators. `BinaryInteger` then refines the implementation detail and already contains derived homogeneous (in)equality and comparison operators.

> WIP: local testing not complete.

Resolves [SR-4984](https://bugs.swift.org/browse/SR-4984).

### CODE REVIEW

**Comment by xwu** [comment]
cc @moiseev Translating my thoughts to code.

**Comment by moiseev** [comment]
@swift-ci Smoke test macOS platform

**Comment by moiseev** [comment]
Thanks, @xwu.

**Comment by xwu** [comment]
@moiseev This doesn't even compile yet (a few straggling syntax issues); I'll ping you when ready.

**Comment by xwu** [comment]
@moiseev K, let's give this a shot. I borked my local testing setup but it does compile.

**Comment by moiseev** [comment]
@swift-ci Smoke test macOS platform

**Comment by xwu** [comment]
@moiseev Once more please. Turns out to have been a little more complicated than I imagined, and I now have no idea if this will work.

**Comment by moiseev** [comment]
@swift-ci Please smoke test macOS platform

**Comment by moiseev** [comment]
I worry that the change you're making won't work purely because of the compiler. AFAIK, when it sees the integer literal, it tries to find a solution to the expression with literal having type `Int`, and if it finds one, then it won't try anything else. But! There is another hack that applies to the operators on concrete types, when the compiler sees an operator on a concrete type, it prefers it to anything else. This second hack is why my solution in #9909 works. As you rightfully noticed, this hack will not kick in in generic context, and in that case the compiler will be looking for the solution with `Int` regardless of the protocol hierarchy.

**Comment by moiseev** [comment]
Also... Technical issues aside. Is it really that big of a problem in generic context? Why would you compare a completely arbitrary number with an unknown type to a very concrete value (excluding 0 and 1)?

**Comment by xwu** [comment]
Result was as I feared. It's too bad the concrete type hack is limited to concrete types and doesn't go through the protocol hierarchy. Having played with this a bit, I think I agree this shouldn't be too much of a problem in practice.

**Comment by moiseev** [comment]
@xwu thanks for spending time on it anyway! We've learned something, the time is not wasted.

**Pull request closed without merging**
