### PR TITLE
[Batch mode] [rdar://40712614 ] Remove “using batch mode” remark.

### PR DESCRIPTION
**Pull request by davidungar**

### CODE REVIEW

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Comment by davidungar** [comment]
@jrose-apple At Bob's suggestion, I have pointed this PR in your direction. A simple revert did not work.

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Review by jrose-apple — APPROVED** [review]
Everything looks in place to me!

**Pull request merged**
