### PR TITLE
inherit required protocols during TangentVector synthesis

### PR DESCRIPTION
**Pull request by marcrasi**
We have been running into a limitation with TangentVector synthesis. Here's a proposed solution and implementation.

**The Problem**

If you have a protocol `P` that refines `Differentiable` and that constrains the `TangentVector` to conform to something that can be derived, the compiler can't derive a conformance to `P`.

e.g. 

```
protocol P: Differentiable where TangentVector: Encodable {}

struct S: P {
  var x: Float
}

/// error: <Cell 1>:3:8: error: type 'S.TangentVector' does not conform to protocol 'Encodable'
/// struct S: P {
///       ^
```

**Proposed Solution**

When deriving the `TangentVector`, look at the conformance the triggered the derivation, find conformance constraints on `TangentVector` implied by that conformance, and make `TangentVector` inherit the required protocols.

One nice property of this solution is that it automatically figures out that `TangentVector` must conform to `AdditiveArithmetic` and `Differentiable`, so these conformances no longer need to be hardcoded in the derivation.

### CODE REVIEW

**Review by rxwei — APPROVED** [review]
LGTM. Suggest documenting this behavior in the manifesto and the proposal.

**Review by dan-zheng — APPROVED** [review]
Nice generalization!

To confirm, I wonder if this is a workaround for associated type inference changes in https://github.com/apple/swift/pull/32578?
Some more context: https://github.com/tensorflow/swift-models/pull/620.

**Comment by marcrasi** [comment]
> To confirm, I wonder if this is a workaround for associated type inference changes in #32578?
> Some more context: tensorflow/swift-models#620.

No I think it is unrelated. Those changes look like they affect cases where a protocol constrains the `TangentVector` to be equal to a specified type. This PR is for when a protocol constrains the `TangentVector` to conform to something.

**Comment by marcrasi** [comment]
> Suggest documenting this behavior in the manifesto and the proposal.

I added a line to the manifesto in this PR, thanks. I'll add a corresponding line to the proposal in a separate PR because that's in a separate repo.

**Comment by marcrasi** [comment]
@swift-ci please test

**Pull request merged**
