### PR TITLE
AssociatedTypeInference: Stop skipping the current protocol when looking for a fixed type witness

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
Sits on top of #32799, only the second commit is relevant.

### CODE REVIEW

**Review by slavapestov — APPROVED** [review]

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Comment by AnthonyLatsis** [comment]
@swift-ci please test source compatibility debug

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Comment by AnthonyLatsis** [comment]
@swift-ci please test source compatibility debug

**Pull request merged**
