### PR TITLE
Finish and default-enable named lazy member loading

### PR DESCRIPTION
**Pull request by graydon**
This is now complete enough to consider merging, I think. All tests pass, benchmarks show a slight improvement in counters (and nothing terribly noticeable in time), various secondary projects seem to build.

### CODE REVIEW

**Comment by graydon** [comment]
@swift-ci please smoke test compiler performance

**Comment by graydon** [comment]
@swift-ci please smoke test compiler performance

**Comment by graydon** [comment]
@swift-ci please smoke test compiler performance

**Comment by graydon** [comment]
@swift ci please clean smoke test compiler performance

**Comment by graydon** [comment]
@swift ci please clean smoke test compiler performance

**Comment by graydon** [comment]
@swift ci please clean smoke test compiler performance

**Comment by graydon** [comment]
@swift ci please smoke test compiler performance

**Comment by graydon** [comment]
@swift-ci please smoke test compiler performance

**Comment by graydon** [comment]
@swift-ci please smoke test compiler performance

**Comment by graydon** [comment]
@swift-ci please smoke test compiler performance

**Comment by graydon** [comment]
@swift-ci please smoke test compiler performance

**Comment by graydon** [comment]
@swift-ci please smoke test compiler performance

**Comment by graydon** [comment]
@swift-ci please smoke test compiler performance

**Comment by graydon** [comment]
@swift-ci please smoke test compiler performance

**Review by DougGregor — APPROVED** [review]
This looks good! I so very much want to kill mirroring of protocol members :(

**Comment by ematejska** [comment]
@swift-ci please smoke test

**Comment by ematejska** [comment]
@swift-ci please test

**Comment by ematejska** [comment]
@swift-ci please test os x

**Comment by graydon** [comment]
@swift-ci please test

**Comment by graydon** [comment]
@swift-ci please test

**Comment by graydon** [comment]
@swift-ci please smoke test compiler performance

**Comment by graydon** [comment]
@swift-ci please test and merge

**Comment by graydon** [comment]
@swift-ci please test and merge

**Comment by aschwaighofer** [comment]
This very likely broke source compat:

https://ci.swift.org/job/swift-master-source-compat-suite/838

**Comment by graydon** [comment]
Ugh. I've got a dentist appointment just now but will be back in a bit to fix this. If it's urgent, reverting only 3de4297c9118f5e6bbec04a208a36827c173e3b7 ought to do the trick (turning the flag off by default).

**Comment by graydon** [comment]
(Sorry! Ran the smoke-compat subset, evidently launchscreensnapshot is doing something special)

**Comment by aschwaighofer** [comment]
@graydon I have reverted this PR in https://github.com/apple/swift/pull/13204

**Comment by graydon** [comment]
K. Sorry. Will qualify more thoroughly before retrying.

**Pull request merged**
