### PR TITLE
build: hide symbols using CMake

### PR DESCRIPTION
**Pull request by compnerd**
This uses the CMake settings to correctly select the visibility
attribute for the runtime.

Addresses rdar://63454568

### CODE REVIEW

**Comment by compnerd** [comment]
@edymtt - I think that this is a better approach to what you were trying to do.  I'd still like to understand how this is a performance thing.  These are not weak symbols, they are COMDATed symbols.  However both of those do not incur a penalty - the weak symbol just means that if one is not provided it will be used, but the resolution is done once at load time.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @drexin

**Comment by mikeash** [comment]
@compnerd This came from an internal verifier which says that weak symbols can impact app launch time. I'm not completely clear as to why, but I guess `dyld` has to do more work.

**Comment by compnerd** [comment]
@mikeash Yes, that’s absolutely correct, the original statement of the reason just made it seem like the change caused a regression at runtime.  Eric helped clear that up.  Just a miscommunication on the actual results of the change.

**Comment by mikeash** [comment]
@compnerd Yeah, it's always a bit tricky and weird when internal stuff bubbles up like this. Glad we're all on the same page now.

**Comment by edymtt** [comment]
@swift-ci please test

**Review by edymtt — APPROVED** [review]

**Comment by compnerd** [comment]
@edymtt Ill go ahead and merge this, and then follow up with the tests for ensuring that this doesn't happen again in the future.  Thanks for the help!

**Pull request merged**
