### PR TITLE
[stdlib] changes to remove `_Strideable` protocol.

### PR DESCRIPTION
**Pull request by xedin**
ABI work to remove unnecessary `_Strideable` protocol and use `Strideable` everywhere instead, which already conforms to `Comparable`.

Initial changes are done by @airspeedswift.

Resolves: rdar://problem/25214598

### CODE REVIEW

**Comment by moiseev** [comment]
What are we waiting for?!
@swift-ci Please test

**Comment by xedin** [comment]
@moiseev some of the stdlib still fails unfortunately, I am trying to figure out what is going on... e.g. `var a = [UInt8]; a[0..<8].index(of: UInt8(0))` doesn’t work yet...

**Comment by xedin** [comment]
@airspeedswift  @moiseev I've dug some more into this and it looks like there is not going to be an easy way out because some things counteract others when it comes to scoring solutions e.g. consider this:

```swift
var buffer = [UInt8](repeating: 0, count: 256)
var bufferUsed: Int = 0

let _ = buffer[0..<bufferUsed].index(of: UInt8(Unicode.Scalar("\n").value))
```

There are going to be two solutions:

 * `Range<Int>`
 * `Array.subscript(Range<Int>) -> ArraySlice<Element>`
 * `Collection.index(of:)`

And

 * `CountableRange<Int>`
 * `MutableCollection.subscript<R: RangeExpression>(R) -> SubSequence where R == CountableRange<Int>`
 * `Collection.index(of:)`

The problem here is that `CountableRange` is always preferred over `Range` since `Strideable` _clarifies_ `Comparable`, but at the same time `Array.subscript` is preferable to `MutableCollection.subscript` which is declared in extension to `MutableCollection` protocol.

I'm thinking that `Array.subscript` has to be either moved (to extension or something) or completely removed to make this case work, WDYT?

**Comment by moiseev** [comment]
@xedin `CountableRange` should go away with conditional conformances. Will it help?

**Comment by xedin** [comment]
@moiseev In this particular case - most likely that would be enough, I'm just wondering how many places like this we might have in stdlib and if it's worth fixing this situation even in presence of `CountableRange`?...

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@moiseev @airspeedswift Looks like `Strideable` could be banished after all, as well as other expressions which were ambiguous before

**Comment by moiseev** [comment]
@swift-ci please smoke test compiler performance

just in case...

**Comment by xedin** [comment]
@swift-ci please smoke test compiler performance

**Comment by xedin** [comment]
/cc @DougGregor @moiseev pointed me to a bunch of bugs which is also going to be resolved by this change:

* https://bugs.swift.org/browse/SR-5134
* https://bugs.swift.org/browse/SR-5879
* https://bugs.swift.org/browse/SR-5175
* https://bugs.swift.org/browse/SR-5366
* https://bugs.swift.org/browse/SR-4256

etc.

**Review by moiseev — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@DougGregor I've made it so ranking follows evaluation order by using different weights on different levels, now binary expressions with arguments which are truly ambiguous are going to stay that way but chained expressions etc. are going to be ranked (effectively) left-to-right.

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
One source break in `Lark`:
```
/Lark/Sources/CodeGenerator/Generator.swift:147:45: error: ambiguous use of 'map'
    let namedTypes: [NamedType] = complexes.values.map({ $0 as NamedType }) + simples.values.map({ $0 as NamedType })
                                            ^
Swift.LazyCollectionProtocol:5:17: note: found this candidate
    public func map<U>(_ transform: @escaping (Self.Elements.Element) -> U) -> LazyMapCollection<Self.Elements, U>
                ^
Swift.Collection:19:17: note: found this candidate
    public func map<T>(_ transform: (Self.Element) throws -> T) rethrows -> [T]
                ^
```

I don't know yet what is going on, will look in the morning.

**Comment by xedin** [comment]
Here is the reduced example which is ambiguous today too:

```swift
let a: [String: Int] = [:]
let b: [String: Int] = [:]
let _: [Int] = a.values.map({ $0 }) + b.values.map({ $0 })
```
It seems like we for some reason can't have `LazyMapCollection` on both sides of the `+` for some reason...

**Comment by xedin** [comment]
@moiseev @DougGregor  Looks like it might be an actually ambiguity in 3 mode, consider this:

```swift
let a: [String: Int] = [:]
let w = a.values.map { $0 }
let z = a.values.map { $0 + 42 }

let _ = w + z
```

In 3 mode this is going to throw an error:
```
error: binary operator '+' cannot be applied to two 'LazyMapCollection<LazyMapCollection<[String : Int], Int>, Int>' operands
let _ = w + z
        ~ ^ ~
note: overloads for '+' exist with these partially matching parameter lists: (C, S), (S, C)
let _ = w + z
          ^
```

Thoughts?

**Comment by xedin** [comment]
@DougGregor @moiseev Ok, I figured out why this works today - `break` is still missing and it so happens that each iteration of `compareSolutions` runs `map` one more time and that tips the scales... It looks like a mis-compile of what should have been ambiguous!

**Comment by DougGregor** [comment]
I wonder if maybe the `LazyCollection` version of `values` should just go away. More overloading == more problems. What do you think, @moiseev and @airspeedswift ?

**Comment by moiseev** [comment]
@DougGregor the original `values` with the lazy-whatever type are there for Swift 3 compatibility. It is not known however (at least to me) whether it will cause a lot of breakage should we remove it. @natecook1000, did you try to run the compat test suite without the backward compatible `values`?

**Comment by natecook1000** [comment]
We've definitely had reports that removing those overloads would break source compatibility for 3.2.

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@moiseev @DougGregor Looks like at least one more "too complex" in compatibility suite - `Plank` after we've added `+` overload :(

**Comment by airspeedswift** [comment]
@swift-ci please smoke test compiler performance

**Comment by airspeedswift** [comment]
Testing compiler perf mostly to test the new compiler perf report...

**Comment by xedin** [comment]
@airspeedswift I don't think this is viable though because of this problem, maybe the best pass we have is to go without `+` changes and fix the breakage somehow, it doesn't happen in all of the cases even because of this missing `break`...

**Comment by xedin** [comment]
Or we can have have couple other alternative choices too:

* put the `break` under the flag for <= 3
* Try to do weighting based on the evaluation order with  left-to-right priority

Both of the choices are not very good but I'm not sure what else we can do to move forward with this...

**Comment by moiseev** [comment]
@xedin it should be possible to make the newly introduced `+` overloads to extend a concrete `LazyMapCollection` type instead of a `LazyCollectionProtocol`. In this case the hacks in the compiler will kick in and "expression too complex" will be avoided.

**Comment by xedin** [comment]
@moiseev can you take a shot at doing that?

**Comment by xedin** [comment]
Ok, let's give it a try with `+` only on `LazyMapCollection` (fingers crossed).

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
\o/ Success!

**Comment by xedin** [comment]
@swift-ci please smoke test compiler performance

**Comment by xedin** [comment]
@swift-ci please smoke test compiler performance

**Review by DougGregor — APPROVED** [review]
As discussed offline, this LGTM

**Comment by airspeedswift** [comment]
:shipit:

**Comment by xedin** [comment]
@swift-ci please smoke test compiler performance

**Comment by xedin** [comment]
@swift-ci please clean test

**Comment by xedin** [comment]
Ok, everything is green, let's do this.

**Pull request merged**
