### PR TITLE
Switch test from 'not ...' to positive test with the correct verify c…

### PR DESCRIPTION
**Pull request by rudkx**
…heck.

### CODE REVIEW

**Comment by rudkx** [comment]
@xedin I think this is what you really wanted here.

**Comment by rudkx** [comment]
@swift-ci Please smoke benchmark

**Comment by rudkx** [comment]
Hmm, oops, did not mean to run benchmarks.

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by xedin** [comment]
@rudkx Right, sorry it has to be a `expected-note` :( but don't I have to use "not" if there is at least a single error present (when calling C() later on)?

**Comment by rudkx** [comment]
@xedin No. With `-verify`, it matches up the diagnostics and returns zero if they match. With `not` any failure will be treated as success (except for crashes, which require an explicit `--crash`). I suspect there are other test bugs of this sort in that directory but I didn't go looking for them.

**Comment by xedin** [comment]
@rudkx Got it, thanks!

**Pull request merged**
