### PR TITLE
[CodeCompletion] Implement .Type completion in expression context

### PR DESCRIPTION
**Pull request by rintaro**
rdar://problem/22072865

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
`Foo.Type` is not valid in expression context. `Foo.Type.self` is valid, but that creates a meta-metatype which is rare.

However if you're going to complete `Foo.Type`, please also add `Foo.Protocol` where foo is a protocol (but again, that's a type term not an expression term).

**Comment by rintaro** [comment]
> `Foo.Type` is not valid in expression context. `Foo.Type.self` is valid, but that creates a meta-metatype which is rare.

Because `.self` is *not* the only possible suffix to `Foo.Type` in expression context (e.g. `Foo.Type.Type.self`), we should not complete `.Type.self`.

> However if you're going to complete `Foo.Type`, please also add `Foo.Protocol` where foo is a protocol (but again, that's a type term not an expression term).

Fair enough. I've implemented `.Protocol` completion for both type and expression context.

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Review by benlangmuir — APPROVED** [review]

**Pull request merged**
