### PR TITLE
swift-lang: moved to swift-stress-tester

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by compnerd** [comment]
@swift-ci please test source compatibility

**Comment by compnerd** [comment]
@swift-ci please test windows platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain

**Comment by compnerd** [comment]
@swift-ci please test windows platform

**Comment by compnerd** [comment]
```
/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift-stress-tester/SwiftEvolve/Tests/SwiftEvolveTests/ShuffleGenericRequirementsEvolutionTests.swift:3:8: error: no such module 'SwiftLang'
```

**Comment by nathawes** [comment]
> /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift-stress-tester/SwiftEvolve/Tests/SwiftEvolveTests/ShuffleGenericRequirementsEvolutionTests.swift:3:8: error: no such module 'SwiftLang'

It think SwiftEvolve is importing SwiftLang without actually using it. Removing the import here: https://github.com/apple/swift-stress-tester/pull/121

**Comment by nathawes** [comment]
@swift-ci please test OS X Platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
I think that the macOS build was a flake

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by drexin** [comment]
Looks good to me.

**Review by drexin — APPROVED** [review]

**Review by nathawes — APPROVED** [review]

**Comment by compnerd** [comment]
#30118 addresses the Windows test failure

**Pull request merged**
