### PR TITLE
[cxx-interop] Import reference types as `inout` not `UnsafePointer`.

### PR DESCRIPTION
**Pull request by zoecarver**

### CODE REVIEW

**Comment by zoecarver** [comment]
@swift-ci please smoke test.

**Comment by zoecarver** [comment]
Note: this only applies to parameters.

**Comment by zoecarver** [comment]
@swift-ci please smoke test.

**Comment by zoecarver** [comment]
Going to land this patch tonight if I don't hear any objections.

**Review by egorzhdan — APPROVED** [review]
Looks great! In the future it would probably be nice to import const references as plain objects where possible. But I think this patch is a step in the right direction either way.

**Comment by zoecarver** [comment]
> In the future it would probably be nice to import const references as plain objects where possible.

I think this is a good idea, and it's something we've been discussing. It is potentially breaking in certain cases, but I think it's something we should do none the less. The nice thing about C++ interop is we don't have to bend Swift to cover all of C++'s dumb/harmful rules/edge-cases.

**Pull request merged**
