### PR TITLE
[6.0][Distributed] Diagnose missing import also for funcs in extensions

### PR DESCRIPTION
**Pull request by ktoso**
**Description:** When a distributed func was declared in an extension in a file that did not import the Distributed module, though the extension was made properly on a distributed actor, we would crash in synthesis in SILGen because synthesis refers to types in the distributed module and the import is necessary. 

This patch properly diagnoses missing imports whenever a distributed func is used somewhere.

**Reviewed by:** @xedin 
**Risk:** Low, only improved diagnostics rather than crashing the compiler for distributed func declarations.
**Testing:** CI testing, verified manually in Xcode project of original issue reporter
**Original PR:** https://github.com/apple/swift/pull/72923 https://github.com/apple/swift/pull/72948
**Radar:** rdar://125813581 rdar://120761584

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
Cherry pick AFTER https://github.com/apple/swift/pull/72974 to avoid conflicts

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
rebased post-https://github.com/apple/swift/pull/72974

**Comment by ktoso** [comment]
@swift-ci please test Linux

**Comment by ktoso** [comment]
@swift-ci please test

**Review by hborla — APPROVED** [review]

**Pull request merged**
