### PR TITLE
[benchmark] Add two benchmarks that show performance of flattening an…

### PR DESCRIPTION
**Pull request by gottesmm**
… array.

The first is a naive imperative approach using appends in a loop. The second
uses flatMap. We would like both of these to have equivalent performance.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Comment by palimondo** [comment]
@gottesmm I would to like lower the base workload of these two tests by a factor of 20: 
* remove multiplier from the loop (5)
* lower the array size to (1<<14)
… so that we can get runtimes in ballpark of [1ms for more precise measurements](https://github.com/apple/swift/pull/19910/commits/638f4f8e5ea130def90f20a4fcfecedffe46bc58).

The `FlattenListLoop` reserves capacity , which seems like an unfair advantage given the goal you state above:
> The first is a naive imperative approach using appends in a loop. The second
uses flatMap. We would like both of these to have equivalent performance.
I don't see how `flatMap` could derive this because it requires multiplication by tuple size, so I'd like to remove the pre-reservation.

Would you be OK with these modifications?

**Comment by gottesmm** [comment]
Do what you need.

I think you misunderstood me. When I say "We would like both of these to have equivalent performance" what I mean is that we would like FlattenListFlatMap to be as close to FlattenListLoop in performance as possible. In a perfect world they would be the same. If the wording is confusing, feel free to change it.

The reason why the reserve capacity is in there is as an attempt to measure the speed of light, i.e. how fast ideally could this be imperatively for comparison purposes. That being said, I do understand the larger point. My suggestion would be to add a separate version of the loop without the reserve capacity. Then we can see all 3.

**Comment by palimondo** [comment]
One more question… you called the `loop` one a "naive imperative approach". What would be a smarter way to do this? First I thought there is some kind of SIMD optimization lurking behind the fact that we're mapping over array of 4 `Int` tuple, but then thought the 4 `Int` tuple array is probably stored as packed 4 `Int`s in a consecutive memory region, so this could probably be done in O(1) with some kind of type info redeclaration. Am I thinking along the correct lines?

Which compiler/stdlib optimization opportunities did you have in mind, adding these benchmarks?

**Comment by gottesmm** [comment]
It is a naive imperative approach since it is the obvious way to do it. I think you are thinking too much about this.

**Comment by gottesmm** [comment]
Sorry, let me be a bit clearer.

It is a naive implementation to me since it is what I would write quickly.

In terms of what compiler/stdlib opportunities are available I am not sure. But this (and the additional test that I hope will get added) I think may provide interesting guidance around swift's performance when executing functional programming. I think this is a class of benchmarks that we could use more of, so I saw this as an opportunity to add coverage.

**Comment by palimondo** [comment]
So, when I really abuse the knowledge of internal structure of the [(Int, Int, Int, Int)], this is (I guess) the true *speed of light* (16x faster than FlattenLoop with `reserveCapacity`)… 

````swift
func flattenUnsafe(_ input: [(Int, Int, Int, Int)]) -> [Int] {
  return UnsafeBufferPointer(start: input, count: input.count)
    .withMemoryRebound(to: Int.self, Array.init)
}
````
Would you mind if I also added this one, or is this one a bridge too far?

**Comment by gottesmm** [comment]
I think that is not necessarily defined behavior (or at least it makes me a bit nervous). @atrick your thoughts?

One thing that I think we could use no matter what is a copy of the benchmark without reserve capacity.

**Comment by palimondo** [comment]
Sure. I’m on it. Just wanted to do all the changes together, so I’m asking about this extreme performance case, too. The idea is to serve as an inspiration for potential future optimization.

**Comment by gottesmm** [comment]
@palimondo Was thinking about this a bit. I am unsure if the unsafe version is interesting now that I am thinking about it. No /real/ work is being done (unless I am missing something).

That being said, I think adding a benchmark without the reserve capacity and an additional lazy flat map would be interesting.

**Comment by palimondo** [comment]
@atrick Heh, you give me too much credit. I wasn’t able to write that until I tried googling “swift array unsafe pointer copy”, [this gist came up](https://gist.github.com/kirsteins/6d6e96380db677169831). Then I had to play with it in REPL, until it “worked”. 
The idea comes from vague remembernce that the fastest Swift version of the Mandelbrot benchmark in language shootout used tuples as SIMD types.
The Array constructor used here is the one that takes Sequence (I guess? Not really sure either…). This isn’t O(1), as I thought initially, this is O(n) - it does depends on the size of `initialArray`. I think it just copies those Int really fast?

**Comment by palimondo** [comment]
All in all, I think if I rewrote it with `input.withUnsafeBufferPointer` as @atrick suggested, this is perfectly legal code and could serve as a benchmark of what an ideally optimized `flatMap` could achieve. Beating the naive for-in to the ground. Am I wrong? (Maybe I shouldn’t be typing this, when I woke up at 3:50am…)

**Comment by atrick** [comment]
@palimondo The gist has a bit less type inference, so it's easier for me to see what's happening. I didn't realize earlier that, if I'm guessing correctly, you're actually using Array's generic `Sequence` initializer, which has a customization point that ends up calling into the UnsafeBufferPointer API. If you just wanted a fast array copy, this would be a silly, round about way to do it. It's only needed because you want to make some dangerous layout assumption.

That said, I expect this code to crash, at least in debug builds, because you can't rebind a buffer's memory to a different element type unless they have the same stride. There's been some debate about whether to allow that. I think it creates more problems than it's worth.

The *right* way to do it is:
```
public func flatten(_ tupleArray: [(Int, Int)])  -> [Int] {
  let numInts = tupleArray.count * 2
  return tupleArray.withUnsafeBufferPointer {
    return $0.baseAddress!.withMemoryRebound(to: Int.self, capacity: numInts) {
      Array(UnsafeBufferPointer(start: $0, count: numInts))
    }
  }
}
```
Note: Swift does not provide any formal layout rule that says an array of homogeneous tuples is laid out the same as an array of those tuple elements. But with builtin integer types I feel that you're safe making this assumption.

**Comment by palimondo** [comment]
@atrick Thanks for showing me the right way. I'm still waiting for the debug build to finish and verify that my Unsafe benchmark was illegal code (I'll file a bug if that's the case), but I also had to fix it (**`input.count * 4`**), because it was copying just 1/4 of the input array 🤦‍♂️:
````swift
func flattenUnsafe(_ input: [(Int, Int, Int, Int)]) -> [Int] {
  return UnsafeBufferPointer(start: input, count: input.count * 4)
    .withMemoryRebound(to: Int.self, Array.init)
}
````
That's the danger of using just `blackHole` instead of some sanity `CheckResults`... I'll fix that, too.

So, the correct speedup vis-a-vis FlatenLoop with `reserveCapacity` is **3.4x**. @gottesmm Would adding this make sense as aspirational target for ideally optimized version of `flatMap`? I'll add lazy versions and I'll also do few more, where the mapped over sequence is not an array. I ❤️ exploring these combinations!

**Comment by palimondo** [comment]
Uhm... the debug build failed to compile after 6 hours, so I couldn't verify... Was I doing it right?
`./swift/utils/build-script -B -R --debug-swift --debug-swift-stdlib --no-assertions --swift-assertions --swift-stdlib-assertions`

**Pull request merged**
