### PR TITLE
IRGen: Use an invariant load to load metadata base offset

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@rjmccall Is this correct?

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by rjmccall** [comment]
It's not safe, no.  The load is invariant as long as it isn't hoisted before something that's guaranteed to trigger class metadata initialization, like fetching the class metadata, but it's conceivable for this load to appear in a function that triggers the class metadata to be initialized during its execution.

For example, there could be a loop like this:

var total = 0
for i in 0..<100 {
  total += MyClass().number
}

`invariant.load` allows the number to be hoisted outside of the loop, but it's possible for the first iteration of the loop to be what triggers the computation of `MyClass`'s metadata bounds.

**Comment by slavapestov** [comment]
@rjmccall Ok, I'll revert then.

**Pull request merged**
