### PR TITLE
[Macros] Introduce @freestanding and standardize on it for freestanding macros

### PR DESCRIPTION
**Pull request by DougGregor**
The syntax of "freestanding" macro declarations has shifted a bit, removing `@expression` in favor of the more general `@freestanding(expression)` and removing `@declaration(freestanding)` in favor of `@freestanding(declaration)`. Start parsing `@freestanding` and remove the others, switching all code in the repository over to the new---and hopefully final---names.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test Linux

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by rxwei** [comment]
@swift-ci please smoke test

**Pull request merged**
