### PR TITLE
[Basic] Update `moveFileIfDifferent` tests to not rely on `getUniqueID`

### PR DESCRIPTION
**Pull request by bnbarham**
These tests were relying on specifics of `getUniqueID` that aren't necessarily true - namely that moving a file from `source` to `dest` doesn't change the returned ID. They are really just testing `moveFileIfDifferent`, which doesn't need to make this assumption.

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Review by compnerd — APPROVED** [review]

**Comment by hjyamauchi** [comment]
@swift-ci please test

**Comment by hjyamauchi** [comment]
The CI is expected to fail as this is a rebranch branch. Will merge it.

**Comment by bnbarham** [comment]
Yeah, it's still failing. I need to do a different fix. I had thought the issue was just that getUniqueID was not the same between for A and B when A moves to B, but it's also that both B (before move) and B (after move) remains the same.

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
Updated. Unfortunately there's no great way to test whether we actually moved the file or not now in many cases. For now I'm just checking the contents where possible.

**Comment by hjyamauchi** [comment]
Thanks.
@swift-ci please test Linux platform
@swift-ci Test macOS Platform

**Comment by hjyamauchi** [comment]
@swift-ci please test Linux platform

**Pull request merged**
