### PR TITLE
[5.0][CSDiagnostics] Add custom diagnostic for invalid @autoclosure forwarding

### PR DESCRIPTION
**Pull request by xedin**
- **Explanation**: Suggest to add () (form a call) to correctly forward argument function
originated from @autoclosure parameter to function parameter itself
marked as @autoclosure.

- **Issue**: rdar://problem/46224703

- **Scope**: Diagnostics

- **Risk**: Very low, only affects diagnostics in small subset of cases involving `@autoclosure` parameters.

- **Testing**: Added compiler regression tests.

- **Reviewed by**: @rudkx

Resolves: rdar://problem/46224703

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Review by rudkx — APPROVED** [review]

**Review by AnnaZaks — APPROVED** [review]
Approved. However, this is not needed for convergence so we will merge it later.

**Comment by xedin** [comment]
@AnnaZaks looks like the tests are green.

**Pull request merged**
