### PR TITLE
JSON trailing comma fix

### PR DESCRIPTION
**Pull request by ghost**
The JSON standard does NOT allow trailing commas after the final object, and in only TWO files, this rule is broken, which may cause issues down the line. This is a simple fix.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Review by akyrtzi — APPROVED** [review]

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by CodaFi** [comment]
@pi1024e Why do you keep rebasing?

**Comment by CodaFi** [comment]
@pi1024e If you continue to rebase this pull request, I cannot get it merged. Please stop.

@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by pi1024e** [comment]
Oh, I am sorry

**Comment by CodaFi** [comment]
No worries.

⛵️

**Pull request merged**
