### PR TITLE
[Backtracing] Bail out earlier for privileged binaries on macOS.

### PR DESCRIPTION
**Pull request by al45tair**
Also remove the code that deals with file descriptors; we will now only start the backtracer for processes that have the get-task-allow entitlement, which means that they've been specifically signed for debugging, and *that* means that it is no longer critical to ensure that unexpectedly inherited fds are closed.

rdar://137551812

### CODE REVIEW

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
**Explanation**: This is a belt & braces improvement for the backtracer's security; instead of relying on the `swift-backtrace` process to check for some of the privileged types of program, we check up front in the runtime. We weren't doing this originally because I was concerned about calling `csops` from a potentially arbitrary sandbox, but I've been assured that that should be OK, and by checking up front for get-task-allow, we can also be more relaxed about closing file descriptors (since the process is already marked as suitable for debugging, so it's easy to get hold of its fds anyway).
**Risk**: Low. This just improves the checks that we do to make things even more secure.
**Original PR**: #77162 
**Reviewed by**: @mikeash 
**Resolves**: rdar://137551812
**Tests**: The backtracer's tests exercise this code.

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
@swift-ci Please test

**Review by tbkka — APPROVED** [review]

**Review by DougGregor — APPROVED** [review]

**Comment by al45tair** [comment]
Closing as this doesn't need to land on this branch.

**Pull request closed without merging**
