### PR TITLE
Add a [nonoverridden] kind for SILVTable entries.

### PR DESCRIPTION
**Pull request by jckarter**
This will let us track class methods that must exist for pass ordering, interface, or ABI reasons, but which can be given more efficient runtime representation because they have no overrides.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by compnerd** [comment]
Might it not be valuable to have a round trip test?

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by jckarter** [comment]
@compnerd Sure, I wanted to get the module version break in first, I'm going to add stuff that starts exercising it next.

**Pull request merged**
