### PR TITLE
Use .gitattributes to syntax-highlight GYB templates on GitHub

### PR DESCRIPTION
**Pull request by broadwaylamb**

### CODE REVIEW

**Review by gottesmm — APPROVED** [review]
LGTM

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
For those listening in. This is implementing support for this: https://github.com/github/linguist#using-gitattributes.

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by broadwaylamb** [comment]
I'm not sure how the failing test is related…

**Comment by gottesmm** [comment]
@swift-ci smoke test Linux platform

**Comment by gottesmm** [comment]
Lets try this one more time... Sorry @broadwaylamb there was recently some breakage on Linux that had been messing with normal testing. I think it is resolved now.

**Comment by broadwaylamb** [comment]
The Linux tests are passing now.

By the way, I'm just curious, why do we need to run tests if this PR doesn't change any actual code? 😊

**Comment by gottesmm** [comment]
@broadwaylamb we require all PRs to go through testing to maintain an always green state of trunk. Also, there are certain tests that we run via the normal test suite that tests non-code properties (such as linting).

That being said, I do think that with the proper time/etc what you are suggesting could be done via a whitelist for docs/etc. We are just not there yet and this is a safe default.

Just MHO.

**Pull request merged**
