### PR TITLE
Change freestanding to use pthreads threading package.

### PR DESCRIPTION
**Pull request by rokhinip**
Change freestanding to use pthreads threading package.

Rdar://102259828

### CODE REVIEW

**Comment by rokhinip** [comment]
@swift-ci please test

**Comment by rokhinip** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by rokhinip** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by al45tair** [comment]
@kubamracek It seems to me that freestanding itself probably shouldn't assume threads? Maybe we need another preset for e.g. freestanding-with-pthreads?

**Pull request closed without merging**
