### PR TITLE
Add SourceKit crash.

### PR DESCRIPTION
**Pull request by practicalswift**
Thanks to @ddunbar who suggested `swift-ide-test` as a fuzzing target:
https://twitter.com/daniel_dunbar/status/675712444228997120

### CODE REVIEW

**Comment by ddunbar** [comment]
Well, that didn't take long. :)

**Comment by rudkx** [comment]
:+1:

**Comment by gparker42** [comment]
Great idea. Hopefully this fuzzing will lead to real SourceKit improvements.

**Comment by dduan** [comment]
🎉

**Pull request merged**
