### PR TITLE
Don't suggest 'break' for empty guard bodies

### PR DESCRIPTION
**Pull request by bitjammer**
That's not valid code.

rdar://problem/28944787

### CODE REVIEW

**Comment by bitjammer** [comment]
@swift-ci Test and merge

**Comment by bitjammer** [comment]
@swift-ci smoke test and merge

**Comment by jrose-apple** [comment]
Break is no less valid than throw: both depend on the enclosing context.

**Comment by jrose-apple** [comment]
I'd actually want to keep `break` when within a loop because it reminds people that `guard` isn't required to exit the *function.*

**Comment by bitjammer** [comment]
Oh, jeez. Then `break_outside_loop` can also be misleading, then:
> 'break' is only allowed inside a loop, if, do, or switch

That shouldn't appear when you just have
```swift
guard false else {
  break
}
```

it's just a little bit too strong of wording, IMO.

**Comment by bitjammer** [comment]
What do you think of:

- If the `guard` isn't in a block that can be broken, only suggest `return` or `throw`.
- If the `guard` is in a block that can be broken, also suggest `break` but with a note drag of which stmt you'll be breaking out of.

**Comment by jrose-apple** [comment]
That seems reasonable. I don't see the problem with break_outside_loop though. "inside" means "anywhere inside", not "immediately inside".

(…though admittedly it is ambiguous about the 'if' having to be labeled)

**Comment by jrose-apple** [comment]
To be clear, the most interesting case to me is

```swift
for chara in party {
  guard chara.mana > 0 else { break }
  chara.performSignatureSpell()
}
```

(You can also put `continue` there. I think it's okay not to bother suggesting that though.)

**Pull request merged**
