### PR TITLE
[ownership] Move lowering past SILCombine and right before the inliner.

### PR DESCRIPTION
**Pull request by gottesmm**
Just a good place to test this functionality separately from the inliner.

NOTE: There is currently a draft since there is one commit I am going to get in via a different PR. This PR I am going to use initially for testing and maybe once that other commit lands, rebase on top and just move the passes as an independent change into the tree.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci smoke test compiler performance

**Comment by gottesmm** [comment]
Just to note, current source compat release failures:

```
18:12:47   FAIL: Dollar, 5.1, 4feadc, Dollar, generic/platform=macOS
18:12:47   FAIL: Dollar, 4.0, 433d4b, Dollar, generic/platform=macOS
18:12:47   FAIL: GRDB.swift, 5.0, 759c10, Swift Package
18:12:47   FAIL: GRDB.swift, 4.2, 759c10, Swift Package
18:12:47   FAIL: Kitura, 5.1, 8578c4, Swift Package
18:12:47   FAIL: Kitura, 4.0, f1c316, Swift Package
18:12:47   FAIL: ProcedureKit, 5.1, a7fa56, ProcedureKitCloud, platform=macOS
18:12:47   FAIL: ProcedureKit, 5.1, a7fa56, ProcedureKit, generic/platform=tvOS
18:12:47   FAIL: ProcedureKit, 5.1, a7fa56, ProcedureKit, generic/platform=iOS
18:12:47   FAIL: ProcedureKit, 5.1, a7fa56, ProcedureKit, platform=macOS
18:12:47   FAIL: ProcedureKit, 5.0, a7fa56, ProcedureKitCloud, platform=macOS
18:12:47   FAIL: ProcedureKit, 5.0, a7fa56, ProcedureKit, generic/platform=tvOS
18:12:47   FAIL: ProcedureKit, 5.0, a7fa56, ProcedureKit, generic/platform=iOS
18:12:47   FAIL: ProcedureKit, 5.0, a7fa56, ProcedureKit, platform=macOS
18:12:47   FAIL: ProcedureKit, 4.2, 94193d, ProcedureKitCloud, platform=macOS
18:12:47   FAIL: ProcedureKit, 4.2, 94193d, ProcedureKit, generic/platform=tvOS
18:12:47   FAIL: ProcedureKit, 4.2, 94193d, ProcedureKit, generic/platform=iOS
18:12:47   FAIL: ProcedureKit, 4.2, 94193d, ProcedureKit, platform=macOS
18:12:47   FAIL: swift-log, 5.2, 16cfcc, Swift Package
18:12:47   FAIL: swift-log, 5.0, 16cfcc, Swift Package
18:12:47   FAIL: async-http-client, 5.0, a72c5a, Swift Package
18:12:47   FAIL: swift-distributed-tracing, 5.2, 73f2b5, Swift Package
18:12:47   FAIL: swift-distributed-tracing, 5.0, 73f2b5, Swift Package
18:12:47   FAIL: swift-cluster-membership, 5.2, 0fd434, Swift Package
18:12:47   FAIL: SwiftyJSON, 5.1, bad5f2, SwiftyJSON watchOS, generic/platform=watchOS
18:12:47   FAIL: SwiftyJSON, 5.1, bad5f2, SwiftyJSON tvOS, generic/platform=tvOS
18:12:47   FAIL: SwiftyJSON, 5.1, bad5f2, SwiftyJSON iOS, generic/platform=iOS
18:12:47   FAIL: SwiftyJSON, 5.1, bad5f2, SwiftyJSON macOS, platform=macOS
18:12:47   FAIL: SwiftyJSON, 5.0, b93c5d, SwiftyJSON watchOS, generic/platform=watchOS
18:12:47   FAIL: SwiftyJSON, 5.0, b93c5d, SwiftyJSON tvOS, generic/platform=tvOS
18:12:47   FAIL: SwiftyJSON, 5.0, b93c5d, SwiftyJSON iOS, generic/platform=iOS
18:12:47   FAIL: SwiftyJSON, 5.0, b93c5d, SwiftyJSON macOS, platform=macOS
18:12:47   FAIL: SwiftyJSON, 4.2, b93c5d, SwiftyJSON watchOS, generic/platform=watchOS
18:12:47   FAIL: SwiftyJSON, 4.2, b93c5d, SwiftyJSON tvOS, generic/platform=tvOS
18:12:47   FAIL: SwiftyJSON, 4.2, b93c5d, SwiftyJSON iOS, generic/platform=iOS
18:12:47   FAIL: SwiftyJSON, 4.2, b93c5d, SwiftyJSON macOS, platform=macOS
18:12:47   FAIL: vapor_console, 5.1, fcd8c1, Swift Package
18:12:47 ========================================
```

And the debug has had issues over the past bit just building. Just going to make sure I didn't make this worse.

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
Release source compat failed due to a weird module map issue.

**Comment by gottesmm** [comment]
Not this PR for sure.

**Comment by gottesmm** [comment]
Debug one hit the same thing:

```
23:19:17 49%: Compile Triple.cpp (x86_64)
23:19:17 49%: Compile Swift source files (arm64)
23:19:17 fatal error: module map file '/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/build/compat_macos/swiftpm-macosx-x86_64/apple/Intermediates.noindex/GeneratedModuleMaps/macosx/CCryptoBoringSSL.modulemap' not found
23:19:17 
23:19:17 fatal error: module map file '/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/build/compat_macos/swiftpm-macosx-x86_64/apple/Intermediates.noindex/GeneratedModuleMaps/macosx/CCryptoBoringSSL.modulemap' not found
23:19:17 
23:19:17 fatal error: module map file '/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/build/compat_macos/swiftpm-macosx-x86_64/apple/Intermediates.noindex/GeneratedModuleMaps/macosx/CCryptoBoringSSL.modulemap' not found
23:19:17 
23:19:17 fatal error: module map file '/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/build/compat_macos/swiftpm-macosx-x86_64/apple/Intermediates.noindex/GeneratedModuleMaps/macosx/CCryptoBoringSSL.modulemap' not found
23:19:17 
23:19:18 49%: Compile Threading.cpp (x86_64)
23:19:18 49%: Compile TargetParser.cpp (x86_64)
23:19:18 1 error generated.
23:19:18 
23:19:18 2 errors generated.
23:19:18 
23:19:18 1 error generated.
23:19:18 
23:19:18 Build cancelled
23:19:18 env SDKROOT=/Applicat
```

**Comment by LucianoPAlmeida** [comment]
> Release source compat failed due to a weird module map issue.

@gottesmm There is a discussion about that on https://github.com/apple/swift/pull/35503 :)

**Comment by tbkka** [comment]
This one I happen to know something about: `FloatingPointPrinting_Float_description_uniform`. That test just converts a bunch of `float` values to `string` in a tight loop.  Interesting point: those strings should all be small, so it should not be creating refcounted objects at all.

**Comment by gottesmm** [comment]
I don't think the perf changes are real. Going to run again.

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
Not real in the sense that the regressions are changing each time suggesting noise.

**Comment by gottesmm** [comment]
If you look at the 3 groups of results for -O, -Osize every time the regressions are changing suggesting they are noise. Consider for -O:

```
FlattenListLoop | 1682 | 2515 | +49.5% | 0.67x (?)
StringInterpolation | 10800 | 12400 | +14.8% | 0.87x (?)
ObjectiveCBridgeFromNSArrayAnyObjectForced | 4500 | 4960 | +10.2% | 0.91x (?)
StringBuilderLong | 1350 | 1480 | +9.6% | 0.91x (?)
```

```
UTF8Decode_InitFromData_ascii_as_ascii | 628 | 742 | +18.2% | 0.85x (?)
StringToDataLargeUnicode | 3450 | 3900 | +13.0% | 0.88x (?)
StringInterpolation | 10900 | 12300 | +12.8% | 0.89x (?)
UTF8Decode_InitFromBytes_ascii_as_ascii | 445 | 497 | +11.7% | 0.90x (?)
ObjectiveCBridgeToNSDictionary | 15000 | 16200 | +8.0% | 0.93x (?)
```

```
StringFromLongWholeSubstringGeneric | 7 | 5 | -28.6% | 1.40x
UTF8Decode_InitFromData_ascii_as_ascii | 748 | 659 | -11.9% | 1.14x (?)
String.data.LargeUnicode | 111 | 101 | -9.0% | 1.10x (?)
```

And for -Osize:

```
Diffing.Same | 8 | 9 | +12.5% | 0.89x (?)
ObjectiveCBridgeFromNSArrayAnyObjectForced | 4660 | 5120 | +9.9% | 0.91x (?)
```

```
StringFromLongWholeSubstringGeneric | 8 | 5 | -37.5% | 1.60x
EqualStringSubstring | 44 | 39 | -11.4% | 1.13x (?)
LessSubstringSubstringGenericComparable | 44 | 39 | -11.4% | 1.13x
LessSubstringSubstring | 43 | 39 | -9.3% | 1.10x
InsertCharacterEndIndexNonASCII | 65 | 59 | -9.2% | 1.10x (?)
EqualSubstringSubstringGenericEquatable | 44 | 40 | -9.1% | 1.10x (?)
StringWalk | 2720 | 2520 | -7.4% | 1.08x (?)
EqualSubstringSubstring | 42 | 39 | -7.1% | 1.08x (?)
EqualSubstringString | 42 | 39 | -7.1% | 1.08x (?)
StrComplexWalk | 5150 | 4790 | -7.0% | 1.08x (?)
InsertCharacterEndIndex | 177 | 165 | -6.8% | 1.07x (?)
```

```
FlattenListFlatMap | 3888 | 6093 | +56.7% | 0.64x (?)
UTF8Decode_InitFromData_ascii_as_ascii | 612 | 662 | +8.2% | 0.92x (?)
```

**Comment by gottesmm** [comment]
Merging!

**Pull request merged**
