### PR TITLE
Optimizer: add the ObjCBridgingOptimization to optimize ObjectiveC bridging operations.

### PR DESCRIPTION
**Pull request by eeckstein**
Removes redundant ObjectiveC <-> Swift bridging calls.
Basically, if a value is bridged from ObjectiveC to Swift an then back to ObjectiveC again, then just re-use the original ObjectiveC value.

Also, add an additional DCE pass before ownership elimination. It can cleanup dead code which is left behind by the ObjCBridgingOptimization.

This PR also removes an old obsolete bridging optimization from SILCombine.

rdar://89987440

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Review by mikeash — APPROVED** [review]
Hooray!

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci test

**Pull request merged**
