### PR TITLE
[validation-test] Adding validation test for generic function match

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
Follow up to #29064 
Adding a validation test from a source compatibility test that crashed.

cc @xedin

### CODE REVIEW

**Comment by theblixguy** [comment]
Here's a more minimised example which produces the same crash:

```swift
public enum Foo<T> {}

public protocol FooProtocol {
  var closure: (String) -> Foo<Int> { get }
}

public struct Bar<Value>: FooProtocol {
  public let closure: (String) -> Foo<Value>
}
```

**Comment by xedin** [comment]
Thank you @LucianoPAlmeida and @theblixguy! I case of validation tests - the smaller, the better and preferably without imports if possible, so if the example that @theblixguy mentioned produces the same result - let's take it.

**Comment by LucianoPAlmeida** [comment]
Humm... sure,  thank you @theblixguy, @xedin :)

**Comment by xedin** [comment]
Let's update this PR and get it merged :)

**Review by xedin — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by theblixguy** [comment]
@swift-ci please smoke test

**Comment by LucianoPAlmeida** [comment]
Tests are ok, should be good to go? :)

**Pull request merged**
