### PR TITLE
Sema: Propagate noescape bit into closure passed to withoutActuallyEscaping

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes <rdar://problem/40853562>, <https://bugs.swift.org/browse/SR-7886>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
```
TestFoundation/xdgTestHelper/main.swift:13:18: error: module 'Foundation' was not compiled for testing
01:13:20 @testable import Foundation
01:13:20                  ^
```

This isn't my change.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Review by jckarter — APPROVED** [review]
LGTM, nice catch!

**Comment by jckarter** [comment]
@swift-ci Please smoke test Linux

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Pull request merged**
