### PR TITLE
[5.0] Recursive metadata fixes omnibus

### PR DESCRIPTION
**Pull request by rjmccall**
Cherry-pick a bunch of recursive-metadata fixes over to the temporary Swift 5.0 qualification branch.

<rdar://problem/42756323>

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci clean test

**Comment by rjmccall** [comment]
Screwed up one of the cherry-picks.

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by rjmccall** [comment]
Failures are exactly the same as on #18376, presumably because there's just an SDK mismatch.

**Pull request merged**
