### PR TITLE
[SourceKit] Fail requests when an error occurs

### PR DESCRIPTION
**Pull request by DavidGoldman**
#25089 for the Swift 5.1 branch. Original description:

Previously, requests would fail silently by returning an empty struct
in the response.

With this change, responses will properly report fail with the internal
error.

This allows IDEs to:

- Properly identify errors when they occur
- Choose to display the error to the user or perhaps handle it

### CODE REVIEW

**Comment by DavidGoldman** [comment]
@swift-ci please test

**Comment by DavidGoldman** [comment]
@swift-ci please asan test

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please asan test

**Comment by DavidGoldman** [comment]
Can you re-run? Looks like an unrelated error

**Comment by akyrtzi** [comment]
@swift-ci test OS X platform

**Pull request merged**
