### PR TITLE
[NFC] Some Uncontroversial Frontend Refactorings

### PR DESCRIPTION
**Pull request by CodaFi**
* Privatize a header that was needlessly part of libAST's includes
* Refine the return type of `loadAST` - this is needed for some upcoming work on incremental builds
* Generalize `SourceFileDeclFinder` to remove the hard dependency on a `SourceFile` as the source of decls for dependencies

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Review by davidungar — APPROVED** [review]
Love the title! And these are great changes.

I'm assuming these changes came up as you were looking at cross-module dependencies. If they are a prerequisite for that work, you could mention that in the PR description as a help for future maintainers.

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
