### PR TITLE
Add test cases for Repeated

### PR DESCRIPTION
**Pull request by frootloops**

### CODE REVIEW

**Comment by airspeedswift** [comment]
Hi @frootloops – thanks for contributing this! It's definitely good to add tests for this type. It'd be great to flesh out these tests a little more. For example, to use `expectRandomAccessCollectionAssociatedTypes` to check it's assoc types, and to check the out-of-bounds checks are working (look for uses of `expectCrashLater` elsewhere in the stdlib tests).

**Comment by frootloops** [comment]
Hi @airspeedswift! Sure! I will update the PR shortly

**Comment by frootloops** [comment]
@airspeedswift please check out the PR again

**Comment by airspeedswift** [comment]
@swift-ci please test and merge

**Review by airspeedswift — APPROVED** [review]

**Comment by frootloops** [comment]
@airspeedswift sorry for disturbing but it looks like CI hasn't started/finished properly

**Comment by CodaFi** [comment]
@swift-ci please test and merge

**Comment by CodaFi** [comment]
@frootloops You'll need to rebase and update your test.x

**Comment by frootloops** [comment]
@CodaFi done

**Comment by CodaFi** [comment]
@swift-ci please test and merge

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
Hmm looks like CI’s not listening.

**Comment by airspeedswift** [comment]
There we go. Thanks @frootloops!

**Pull request merged**
