### PR TITLE
[Build] Add the new fully-static Linux SDK.

### PR DESCRIPTION
**Pull request by al45tair**
Declare a new `LINUX_STATIC` SDK and configure it.
    
Add options to set the build architectures for the `LINUX` and `LINUX_STATIC` SDKs, similar to what we have for Darwin, because we'll be cross-compiling.

Also add an option to point the build system at the sources for the musl C library, which we're using for `LINUX_STATIC`.

rdar://123503470

### CODE REVIEW

**Comment by al45tair** [comment]
**Explanation**: Adds the fully statically linked Linux SDK to the build system.
**Original PR**: #71839
**Risk**: Low. This adds an SDK to the CMake SDK system that is only used by the fully static configuration.
**Reviewed by**: @edymtt 
**Resolves**: rdar://123503470
**Tests**: The Python changes do have some tests associated with them. The rest is only applicable if you explicitly ask `build-script` to build the standard library for the fully statically linked Linux configuration, which will have its own CI job with its own tests when we're done.

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
Cherry picked this fix: https://github.com/apple/swift/pull/73474

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
And this one too: https://github.com/apple/swift/pull/73470

**Comment by al45tair** [comment]
@swift-ci Please test

**Review by tbkka — APPROVED** [review]

**Pull request merged**
