### PR TITLE
[NFC] 32-bit-safe ImportDiagnosticTarget 

### PR DESCRIPTION
**Pull request by beccadax**
Previously, `ImportDiagnosticTarget` was a `PointerUnion` of five types. This required more spare bits than were available on 32-bit platforms, so the compiler (and more importantly, lldb) could not be built for those.

~~This commit makes `ImportDiagnosticTarget` a class which is still backed by a `PointerUnion` on 64-bit platforms, but uses `TaggedUnion` on 32-bit platforms. The API is designed to be a drop-in replacement; we might want to evolve it into something a little more like `ClangNode` in the future.~~

**Update for new implementation:** Fortunately, it turns out that there’s no good reason for `clang::ModuleMacro` to be part of the pointer union—we always convert it to `clang::MacroInfo` before looking up diagnostics anyway. Removing it gets us back into territory which ought to be 32-bit-safe.

Fixes rdar://88922618.

### CODE REVIEW

**Comment by beccadax** [comment]
@swift-ci please test

**Comment by beccadax** [comment]
The second commit simply forces the `TaggedUnion` implementation on 64-bit platforms so I can test it; I'll revert it before merging.

**Comment by beccadax** [comment]
@swift-ci test

**Review by NuriAmari — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
