### PR TITLE
NFC: Fix -Wdeprecated-copy warnings

### PR DESCRIPTION
**Pull request by davezarzycki**

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test and merge

**Comment by davezarzycki** [comment]
@swift-ci please smoke test macos

**Comment by davezarzycki** [comment]
Weird build timeouts.

@swift-ci please smoke test

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by davezarzycki** [comment]
Weird build timeouts.

@swift-ci please smoke test

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please clean test Windows platform

**Review by compnerd — APPROVED** [review]

**Pull request merged**
