### PR TITLE
test: fix after #30059

### PR DESCRIPTION
**Pull request by compnerd**
Fix the broken test that was committed in PR#30059

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
CC: @owenv

**Comment by benlangmuir** [comment]
@compnerd looks like we raced: https://github.com/apple/swift/pull/30125  I think it makes sense to change all the path separators instead of just the last one - it's an implementation detail that the earlier part of the path is just concatenated.

**Comment by compnerd** [comment]
Sounds good, I like your patch better.

**Pull request closed without merging**
