### PR TITLE
[Freestanding] Disable Task.sleep and AsyncStream.

### PR DESCRIPTION
**Pull request by nate-chandler**
rdar://99444461

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by rokhinip — APPROVED** [review]

**Comment by nate-chandler** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by nate-chandler** [comment]
@swift-ci please test macOS platform

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Pull request merged**
