### PR TITLE
[gardening][build-script] Use String literal concatenation instead of longstring literal

### PR DESCRIPTION
**Pull request by rintaro**
#### What's in this pull request?

For code readability.

Also a small fix in help document. `utils/build-script --help` output diff:

``` diff
@@ -83,7 +83,7 @@
                         cmake list 'module_regexp;flag'. Can be called
                         multiple times to add multiple such module_regexp flag
                         pairs. All semicolons in flags must be escaped with a
-                        ''
+                        '\'

 Host and cross-compilation targets:
   --host-target HOST_TARGET
```

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

### CODE REVIEW

**Comment by practicalswift** [comment]
@rintaro Does it pass `flake8`? :-)

**Comment by rintaro** [comment]
```
checking utils/build-script
utils/build-script:20:1: F401 'textwrap' imported but unused
```
I wil fix it. 😅

**Comment by practicalswift** [comment]
@swift-ci Please test and merge :-)

**Comment by gottesmm** [comment]
@swift-ci Please test python

**Comment by gottesmm** [comment]
@swift-ci Please Python lint

**Comment by gottesmm** [comment]
@rintaro This does not pass the lint. It looks like there is some sort of usage of textwrap.

**Comment by rintaro** [comment]
@gottesmm It seems 9ebc8a33f824d357940014fbfb563bd3e914a98f introduced another usage.
Rebased and fixed.

**Comment by gottesmm** [comment]
@swift-ci Please Python lint

**Pull request merged**
