### PR TITLE
[AutoDiff] Clean up syntax.

### PR DESCRIPTION
**Pull request by dan-zheng**
Clean up `utils/gyb_syntax_support/AttributeNodes.py` for differentiation-related attributes.

* Remove `Maybe{JVP,VJP}` from `DifferentiableAttributeArguments`. Follow-up to https://github.com/apple/swift/pull/30001.
* Remove unused `DifferentiableAttributeFuncSpecifier` syntax node.
* Rename "differentiation parameter" to "differentiability parameter".
  * Terminology standardized in [docs/DifferentiableProgramming.md](https://github.com/apple/swift/blob/master/docs/DifferentiableProgramming.md).

Resolves SR-12552.

### CODE REVIEW

**Comment by dan-zheng** [comment]
cc @allevato: you suggested some of these changes today.

**Comment by dan-zheng** [comment]
https://github.com/apple/swift-syntax/pull/209
@swift-ci Please test

**Review by marcrasi — APPROVED** [review]

**Comment by dan-zheng** [comment]
apple/swift-syntax#209
@swift-ci Please test Linux

**Comment by dan-zheng** [comment]
apple/swift-syntax#209
@swift-ci Please test Windows

**Comment by dan-zheng** [comment]
Windows CI seems to fail due to unrelated reasons.

**Pull request merged**
