### PR TITLE
[5.3][stdlib] Add _forEachField(of:options:body:) function (#32873)

### PR DESCRIPTION
**Pull request by lorentey**
This function walks all the fields of a struct, class, or tuple, and calls
`body` with the name, offset, and type of each field. `body` can perform
any required work or validation, returning `true` to continue walking fields
or `false` to stop immediately.

(cherry picked from #32873)

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Review by kylemacomber — APPROVED** [review]

**Comment by lorentey** [comment]
The Windows failure looks to be https://github.com/apple/swift/pull/32898; I've cherry picked that here, too.

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test linux platform

**Review by natecook1000 — APPROVED** [review]

**Pull request merged**
