### PR TITLE
Don't use __derived_enum_equals for a resilient synthesized '=='

### PR DESCRIPTION
**Pull request by jrose-apple**
(or __derived_struct_equals)

We want to make sure that if someone replaces the synthesized implementation with a handwritten one, it doesn't change the ABI. The simplest way to do that is to not use this clever workaround from #8735.

[SR-8294](https://bugs.swift.org/browse/SR-8294) / rdar://problem/42302849

### CODE REVIEW

**Comment by jrose-apple** [comment]
@graydon, I figure we can think of something better later if we want; I just don't want to paint ourselves into a corner. What do you think?

@swift-ci Please test

**Review by graydon — APPROVED** [review]
I don't have a great mental model for all the possible resilience scenarios to know if this "covers everything", but the code synthesis change looks right to me and I understand at least the outlines of the problem being solved by it, seems reasonable.

**Comment by graydon** [comment]
(@jrose-apple btw, thanks for doing this!)

**Comment by slavapestov** [comment]
@jrose-apple Ok, I guess ideally, the synthesized witness would be private, and we would support 'opaque witnesses'; then it wouldn't get a symbol at all.

Note that a top-level operator has a different mangling than a static method operator too...

**Comment by jrose-apple** [comment]
It's not about the witness case; it's about direct calls not backwards-deploying.

I'm not sure what to do about the top-level thing, but at least there's not really a reason to use a top-level operator with a concrete type anymore.

**Pull request merged**
