### PR TITLE
[DNM] Fake PR to test SwiftPM changes

### PR DESCRIPTION
**Pull request by yim-lee**

### CODE REVIEW

**Comment by yim-lee** [comment]
https://github.com/apple/swift-package-manager/pull/3938
@swift-ci Please test source compatibility

**Comment by yim-lee** [comment]
https://github.com/apple/swift-package-manager/pull/3938
@swift-ci Please test source compatibility

**Comment by yim-lee** [comment]
https://github.com/apple/swift-package-manager/pull/3938
@swift-ci Please test source compatibility

**Comment by yim-lee** [comment]
https://github.com/apple/swift-package-manager/pull/3941
@swift-ci Please test source compatibility

**Comment by yim-lee** [comment]
https://github.com/apple/swift-package-manager/pull/3942
@swift-ci Please test source compatibility

**Comment by tomerd** [comment]
https://github.com/apple/swift-package-manager/pull/3942

@swift-ci Please test source compatibility

**Pull request closed without merging**
