### PR TITLE
[stdlib] Attempt to dispatch pointer + via Strideable conformance

### PR DESCRIPTION
**Pull request by moiseev**

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please benchmark

**Comment by xedin** [comment]
What I wonder is - are there actually any perf benchmarks that use unsafe pointers with `+` operator?

**Comment by moiseev** [comment]
@swift-ci Please benchmark

**Comment by xedin** [comment]
@swift-ci please smoke test compiler performance

**Comment by xedin** [comment]
If nothing else we do a lot less work with this patch, how benchmarks are ok.

**Comment by xedin** [comment]
Looks like in optimized build PointerPlusInt didn't regress so it's a win, @moiseev ?

**Comment by moiseev** [comment]
@xedin Looks like it. I'll proceed with this change then, dropping the `-` and fixing the test failures.

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by moiseev** [comment]
@swift-ci Please smoke test Linux platform

**Comment by moiseev** [comment]
@swift-ci Please smoke test Linux platform

**Comment by moiseev** [comment]
@swift-ci Please smoke test Linux platform

**Comment by moiseev** [comment]
🤔

**Comment by moiseev** [comment]
@swift-ci Please clean test Linux platform

**Comment by moiseev** [comment]
@swift-ci Please smoke test Linux platform

**Comment by xedin** [comment]
@swift-ci please test source compatibilty

**Comment by xedin** [comment]
@moiseev let's XFAIL `SILOptimizer/array_contentof_opt.swift` on Linux and move on.

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@moiseev Let's XFAIL `test/SILOptimizer/array_contentof_opt.swift` on Linux and move on with this change.

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by moiseev** [comment]
@swift-ci Please Test Source Compatibility

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by moiseev** [comment]
@swift-ci Please Test Source Compatibility

**Review by xedin — APPROVED** [review]
Nice!

**Comment by moiseev** [comment]
@swift-ci please smoke test compiler performance

**Comment by moiseev** [comment]
@swift-ci please smoke test compiler performance

**Pull request merged**
