### PR TITLE
Modified min and max for code uniformity

### PR DESCRIPTION
**Pull request by m16vie**

### CODE REVIEW

**Comment by gribozavr** [comment]
Does this change implement what was discussed in pull request #137?

**Comment by colinta** [comment]
This changes the behavior of `max`.  If a class implements `Comparable`, calling `max(a, b, c)` currently returns the *last* instance that has the maximum value.  This means that if `a > b, b == c`, the current version of `max` returns `c`, but your version returns `b`.

Neither is correct or wrong, but the change is unnecessary change.

**Comment by mmkg** [comment]
Also, currently `max(a, b, c)` returns `b` assuming `a < b, b == c` and `max(a, b, c, d)` returns `d` assuming `a < b, b == c == d`, which seems to be wrong. Following the argument that given equal parameters, `min` and `max` should return different instances, `max` should then return the *last* maximum instance while `min` returns the *first* minimum. I suggest the following code.
```swift
/// Returns the greatest argument passed.
@warn_unused_result
public func max<T : Comparable>(x: T, _ y: T, _ z: T, _ rest: T...) -> T {
  var r = x
  if y >= r {
    r = y
  }
  if z >= r {
    r = z
  }
  for t in rest {
    if t >= r {
      r = t
    }
  }
  return r
}
```

**Comment by gribozavr** [comment]
@mmkg Please update the pull request and provide tests.

**Comment by IngCr3at1on** [comment]
@colinta I think the general idea was to create more consistency in the language handling in the first place (both are "valid" but currently they are inconsistent to my understanding). This was discussed in great detail on #137

**Comment by gribozavr** [comment]
#566 adds tests that show that we already implement #137.

**Pull request closed without merging**
