### PR TITLE
[parse/sema] Give all case bodies their own var decls without using t…

### PR DESCRIPTION
**Pull request by gottesmm**
…hose var decls for anything.

This is a step in the direction of fixing the fallthrough bug. Specifically, in
this commit I give case stmts a set of var decls for the bodies of the case
statement. I have not wired them up to anything except the var decl
list/typechecking.

rdar://47467128

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
In a forthcoming commit I am going to change emission to use these. At least with this commit we know that the basic functionality around the var decl linked list is not broken by introducing these case body var decls into that list.

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@nathawes I think this test is going to pass. Can I get that review?

**Comment by gottesmm** [comment]
@nathawes it did pass.

**Review by nathawes — APPROVED** [review]
LGTM!

**Pull request merged**
