### PR TITLE
stdlib: make CommandLine inspection work

### PR DESCRIPTION
**Pull request by compnerd**
This implements commandline access on Windows by using the Windows Shell
API to access the commandline information and making it available in
Swift.  This is needed for the correct invocation of the child process
in the unit tests.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by CodaFi** [comment]
Does `WideCharToMultiByte` guarantee the returned string is NUL-terminated?

**Comment by compnerd** [comment]
@CodaFi, yes, in this case, because the initial string is NUL-terminated and we are using `-1` for the length, the resulting string is NUL-terminated.

**Review by CodaFi — APPROVED** [review]
LGTM.  Thanks for knocking this out.

**Pull request merged**
