### PR TITLE
More Ownership Verifier Fixes

### PR DESCRIPTION
**Pull request by gottesmm**
This PR contains 3 ownership verifier fixes that were found when testing the verifier on SILGen output.

1. 157f9e9: This makes sure that the verifier ignores type dependent operands when looking at uses.
2. c15547b: This commit makes sure that the verifier considers an apply with an unowned parameter as a non-lifetime ending use when passed values with owned/guaranteed/unowned ownership. This is b/c such a parameter is +0 and the callee is required to retain it before any side effects have occurred in the callee to ensure that it has taken ownership before anything else occurs.
3. 744b31a: Guaranteed parameters and unowned parameters when forwarded should not consider a forwarding instruction to be a lifetime ending use. This is b/c both of these are +0.

rdar://29791263

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci Please smoke test and merge

**Comment by shahmishal** [comment]
FYI - CI is down for upgrade.

**Comment by gottesmm** [comment]
Thanks!

**Comment by gottesmm** [comment]
I am going to pile on some more stuff in that case.

**Comment by gottesmm** [comment]
@swift-ci Please smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci Please smoke test and merge

**Comment by shahmishal** [comment]
FYI - CI is down for upgrade.

**Comment by gottesmm** [comment]
@shahmishal Ya. I know. = ).

**Comment by gottesmm** [comment]
For when the bots get back up...

**Comment by gottesmm** [comment]
@swift-ci Please smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci Please smoke test and merge

**Comment by gottesmm** [comment]
*doh* Found a thinko. Edited a test for experimentation purposes...

**Comment by gottesmm** [comment]
@swift-ci Please smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci Please smoke test and merge

**Comment by gottesmm** [comment]
Lets try this again...

**Pull request merged**
