### PR TITLE
[NameLookup] Opaque Type Collector should skip existential types

### PR DESCRIPTION
**Pull request by angela-laar**
An error in the opaque type collector is causing basic code using existential 'any' to crash with the 'ImplicitSome' feature.

i.e. 

```
  protocol P { }

  var x: any P
```

Fixes rdar://102698119

### CODE REVIEW

**Comment by angela-laar** [comment]
@swift-ci please smoke test

**Comment by angela-laar** [comment]
@swift-ci please smoke test

**Review by hborla — APPROVED** [review]

**Comment by angela-laar** [comment]
@swift-ci please smoke test

**Comment by angela-laar** [comment]
@swift-ci please smoke test

**Comment by angela-laar** [comment]
@swift-ci please smoke test

**Comment by angela-laar** [comment]
@swift-ci please smoke test

**Comment by angela-laar** [comment]
@swift-ci please smoke test

**Comment by angela-laar** [comment]
@swift-ci please smoke test

**Comment by angela-laar** [comment]
@swift-ci please smoke test macOS

**Comment by angela-laar** [comment]
@swift-ci please smoke test linux

**Comment by angela-laar** [comment]
@swift-ci please smoke test

**Pull request merged**
