### PR TITLE
Refactor ExtInfo to use the builder pattern for construction.

### PR DESCRIPTION
**Pull request by varungandhi-apple**
- ~~We could probably reduce some of the duplication with more helper methods that call `intoBuilder()` and `build()`~~.
- I don't feel particularly strongly about the method names.
- `git-clang-format` had a bit of a field day with reformatting the surrounding code, so that's a bit unfortunate...
- ~~The first commit in present in a separate PR. https://github.com/apple/swift/pull/33117~~
- The non-introduction of invariant checking is deliberate. I imagine something or the other is going to blow up when we introduce more checks, so we can do that one-by-one and refactor small amounts of code, instead of introducing the invariant checks and doing the refactoring in this PR (which is already somewhat big).

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
Forum discussion thread: https://forums.swift.org/t/refactoring-extinfo-to-use-a-builder-style-api-to-enforce-correctness-by-construction/38726

**Comment by varungandhi-apple** [comment]
@swift-ci please test

**Comment by varungandhi-apple** [comment]
@swift-ci please test macOS platform

**Comment by varungandhi-apple** [comment]
This is going to keep creating merge conflicts, I'll resolve them after merging #33117.

**Comment by varungandhi-apple** [comment]
@swift-ci please test

**Comment by varungandhi-apple** [comment]
@swift-ci please test

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test

**Comment by varungandhi-apple** [comment]
Marked a bunch of things `constexpr`.

@swift-ci please smoke test

**Comment by varungandhi-apple** [comment]
@CodaFi any pending concerns/LGTY?

**Review by CodaFi — APPROVED** [review]

**Comment by davezarzycki** [comment]
Hi @varungandhi-apple – Thanks for doing this. Why were a bunch of methods made `constexpr`? That keyword isn't "free" as far as compile times go so unless you actually need constant evaluation then `inline` is a better compiler hint. Did you mean to add an `inline`?

**Comment by varungandhi-apple** [comment]
I don't follow why it should cause additional compile times unless we actually use the `constexpr` function for compile-time evaluation... maybe I'm missing a piece of the puzzle here. Could you explain your line of reasoning?

**Comment by davezarzycki** [comment]
You might want to double check with your colleagues at Apple, but I think I remember one of them pointing out that `constexpr` forces `clang` to interpret the code before lowering to LLVM IR. For most code, this interpretation adds little to no gains over what the LLVM optimizer can provide but layers of constexpr function calls can cause quite a bit of needless work inside of clang. So unless one actually need to use a function in a constant context (like the size of an array, bitfield sizing, enum constants, etc), then one should either use `inline` or trust the auto-inliner to do the right thing.

**Comment by davezarzycki** [comment]
I agree that *these* specific cases should be harmless.

I think the point this colleague was trying to make was educational: one should prefer `inline` over `constexpr` unless you NEED `constexpr` semantics because of aggregate compounding effects if a code base starts using `constexpr` all over the place.

**Pull request merged**
