### PR TITLE
[Serialization] Add ModuleSummary serialization format

### PR DESCRIPTION
**Pull request by kateinoigakukun**
~~This will be unblocked when https://github.com/apple/swift/pull/33324 merged.~~

This PR adds the actual serialization and deserialization implementation of module summary which will be used for cross dead function elimination.

The module summary file consists of **function summaries** and **virtual function tables**.

### Function Summary

A function summary has a globally unique identifier and function call info. The function call info indicates how the callee function is referenced (e.g. `witness_method`, `class_method` or `function_ref`).

### Virtual Function Table

A virtual function table has a map of virtual method to implementations.

```swift

protocol P {
  func foo1()
}

struct S1: P {
  func foo1() {}
}
struct S2: P {
  func foo1() {}
}
```

For example, this code will be summarized into

```yaml
witness_tables:
  P.foo1:
    - S1.foo1
    - S2.foo2
```

For more info: https://forums.swift.org/t/refactoring-plan-of-silvisitor-for-lto/37678/14

CC: @compnerd @gottesmm

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Comment by kateinoigakukun** [comment]
Finally, CI passed

**Comment by MaxDesiatov** [comment]
@compnerd @gottesmm would you be able to have a look at this please?

**Comment by kateinoigakukun** [comment]
Close as it's too stale for now.

**Pull request closed without merging**
