### PR TITLE
[scanner] Adopt new Clang API for build arguments

### PR DESCRIPTION
**Pull request by jansvoboda11**

### CODE REVIEW

**Comment by jansvoboda11** [comment]
https://github.com/apple/llvm-project/pull/7447
@swift-ci please test

**Comment by jansvoboda11** [comment]
https://github.com/apple/llvm-project/pull/7447
@swift-ci please test

**Comment by jansvoboda11** [comment]
https://github.com/apple/llvm-project/pull/7447
@swift-ci please test

**Comment by jansvoboda11** [comment]
https://github.com/apple/llvm-project/pull/7447
@swift-ci please test

**Comment by jansvoboda11** [comment]
https://github.com/apple/llvm-project/pull/7447
@swift-ci please test

**Comment by jansvoboda11** [comment]
https://github.com/apple/llvm-project/pull/7447
@swift-ci please test

**Comment by jansvoboda11** [comment]
https://github.com/apple/llvm-project/pull/7447
@swift-ci please test

**Comment by jansvoboda11** [comment]
https://github.com/apple/llvm-project/pull/7447
@swift-ci Please smoke test macOS platform

**Comment by jansvoboda11** [comment]
https://github.com/apple/llvm-project/pull/7447
@swift-ci Please smoke test macOS platform

**Review by artemcm — APPROVED** [review]

**Pull request merged**
