### PR TITLE
In performTypeChecking, defer verifyAllLoadedModules in WMO mode.

### PR DESCRIPTION
**Pull request by atrick**
Suggested by Jordan Rose.

Defer per-file verification in whole-module mode. Verifying imports between
files could cause the importer to cache declarations without adding them to the
ASTContext. This happens when the importer registers a declaration without a
valid TypeChecker instance, as is the case during verification. A subsequent
file may require that declaration to be fully imported (e.g. to synthesized a
function body), but since it has already been cached, it will never be added to
the ASTContext. The solution is to skip verification and avoid caching
it. Instead, loaded modules are now verified in WMO mode once during
performWholeModuleTypeChecking.

Fixes <rdar:36801676> [Edge][swift 4.1] SIL verification failed: external
declarations of SILFunctions with shared visibility is not allowed.

### CODE REVIEW

**Comment by atrick** [comment]
I'm still working on a test case. I understand the problem but don't fully understand causality.

**Comment by atrick** [comment]
@swift-ci test.

**Review by jrose-apple — COMMENTED** [review]
LGTM. If we want to reproduce the original test case, it's going to involve a library module and a client module.

**Comment by atrick** [comment]
@swift-ci please test and merge.

**Comment by atrick** [comment]
@swift-ci test and merge.

**Pull request merged**
