### PR TITLE
[IRGen] Do not use ObjC tagged-pointer logic on non-ObjC platforms

### PR DESCRIPTION
**Pull request by davezarzycki**
Something to squeeze in before the ABI freeze (I hope).

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please test

**Comment by rjmccall** [comment]
Seems reasonable, but @jckarter should take a look, too.

**Comment by jckarter** [comment]
The imminent ABI freeze is only for ObjC platforms, but this looks good at a glance.

**Comment by davezarzycki** [comment]
GitHub review approval would be appreciated. Thanks!

@swift-ci please smoke test

**Review by jckarter — APPROVED** [review]

**Pull request merged**
