### PR TITLE
IRGen: Clean up FIXME in emitConditionalConformancesBuffer()

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@huonw Something I noticed while working on protocol resilience. Does this make sense?

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by huonw** [comment]
Nice! That parameter wasn't great.

**Pull request merged**
