### PR TITLE
Stop depending on libtensorflow_framework.so just for InitMain().

### PR DESCRIPTION
**Pull request by pschuh**
Switch over to using InitMain() from tensorflow_framework directly, and then use it through the experimental C api.

### CODE REVIEW

**Review by dan-zheng — APPROVED** [review]

**Review by mhong — APPROVED** [review]
nice!

**Comment by pschuh** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@pschuh This broke all builds and there's no indication that this PR passed any tests. Why was this merged?

**Comment by bgogul** [comment]
Let me revert this PR for now so that Parker can look into it.

**Comment by bgogul** [comment]
@rxwei, never mind. It looks like you already reverted it.

**Pull request merged**
