### PR TITLE
Update SILLoop::canDuplicate to correctly handle begin_apply

### PR DESCRIPTION
**Pull request by rjmccall**
Leave a warning in isTriviallyDuplicatable so that future updates there will know to also update this code.

### CODE REVIEW

**Comment by aschwaighofer** [comment]
LGTM

**Comment by atrick** [comment]
@rjmccall @aschwaighofer My understanding is that it's valid to have:
```
loop:
  begin
cond_br exit, tail

tail:
  end
  br loop

exit:
  end
```

**Comment by rjmccall** [comment]
Right.  And in that situation, the loop would contain just `loop` and `tail`, right?

**Comment by aschwaighofer** [comment]
@rjmccall Yes.

**Pull request merged**
