### PR TITLE
[sourcekit] Use the driver to parse command line arguments

### PR DESCRIPTION
**Pull request by benlangmuir**
Stop parsing frontend arguments directly and use the driver instead. The most intersting part of this change is that it forces us to consider whether our compiler invocation will have inputs or not.  We have several kinds of requests that need to create a compiler instance, but not parse any inputs (interface-generation, doc-info, and indexing when operating on a module instead of source files).

rdar://17897287

### CODE REVIEW

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please test

**Review by jrose-apple — APPROVED** [review]
Looks good from my end.

**Comment by benlangmuir** [comment]
Updated tests: tests that use the built swift modules also need to pass a matching -target.  Adding the target option exposed some other tests that had mac-specific output, so disabled those on other platforms.  This is a symptom of the fact that the majority of our sourcekitd tests are really only running for the host platform, since they are not setting a target triple explicitly.

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please test

**Pull request merged**
