### PR TITLE
Resolves #75109

### LINKED ISSUE #75109: Replace old screenshot with new one
### Description

Doc to change: https://github.com/swiftlang/swift/blob/main/docs/HowToGuides/FirstPullRequest.md

The screenshot in this doc is showing apple/swift and it's now swiftlang/swift under submitting a pull request. Good first issue for someone! 
[Link to image](https://github.com/swiftlang/swift/blob/main/docs/GitHubCreatePRScreenshot.png)

### Reproduction

n/a

### Expected behavior

n/a

### Environment

n/a

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by vidhupv**
New commits include uploading the new screenshot to docs under the name SwiftGithubCreatePRScreenshot.png and also changing the name of the screenshot location in the HowTo Guide for "First Pull Requests"

### CODE REVIEW

**Review by AnthonyLatsis — COMMENTED** [review]
* Please take the screenshot directly from https://github.com/swiftlang/swift, which is where the doc suggests us to navigate. You could even crop it somewhat like this without the org name that brought about this issue:

   Screenshot 2024-07-12 at 06 09 04
* The rest of our screenshots are in light mode. Let’s be consistent about that.
* Mind tidying up the commit history and giving this pull request a proper title?

**Comment by vidhupv** [comment]
@AnthonyLatsis I shall do that. Just a couple of questions:

1. Should I do it exactly the way you sent or should I include the swiftlang/swift portion at the top of the page as well considering how that was in the current screenshot. 
2. Should I convert this pull request to draft in order to tidying the commit history?

**Comment by AnthonyLatsis** [comment]
1. What do *you* think?
2. No need. The draft state is to indicate that changes are not ready for review. For example, reviews are not requested until you undraft if you start off with a draft PR.

**Comment by AnthonyLatsis** [comment]
Could you try tidying up your commit history by squashing your commits via an interactive rebase rather than spawning new PRs? Let me know if you need help with that. You will definitely benefit from this skill if you are planning to contribute more. Also, we prefer rebasing on main over merging with main when resolving conflicts — these intermediary merge commits pollute the commit history for no good reason.

**Comment by vidhupv** [comment]
Hey, I would greatly appreciate any help on that. I am just learning to use the rebase editor on my terminal. I have dropped a few previous redundant commits and am in the process of squashing the valid ones right now.

**Comment by AnthonyLatsis** [comment]
> Hey, I would greatly appreciate any help on that.

Sure, feel free to reach out if you get stuck with anything specific.

**Comment by AnthonyLatsis** [comment]
Superseded by #75220.

**Pull request closed without merging**
