### PR TITLE
[Version] Don't allow effective sub-versions, only major versions

### PR DESCRIPTION
**Pull request by milseman**
Don't allow effective sub-versions, only major versions

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please smoke test

**Comment by milseman** [comment]
@swift-ci please smoke test

**Comment by jdfweb** [comment]
I agree

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@erg, that failure is from before my new push.

@swift-ci please smoke test

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please smoke test

**Comment by milseman** [comment]
@swift-ci please smoke test

**Comment by milseman** [comment]
@swift-ci please smoke test

**Comment by milseman** [comment]
Linux failure: /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/swiftpm/Sources/PackageLoading/Module+PkgConfig.swift:11:8: error: module file was created by an older version of the compiler; rebuild 'Basic' and try again: /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/buildbot_linux/swiftpm-linux-x86_64/debug/Basic.swiftmodule

Is this due to incremental build?

**Comment by milseman** [comment]
@erg

**Comment by milseman** [comment]
@swift-ci please clean smoke test linux platform

**Pull request merged**
