### PR TITLE
Remove AllArchetypes list

### PR DESCRIPTION
**Pull request by slavapestov**
This set of changes will help us with implementing two important generics features:
- Recursive protocol conformances (`protocol P { associatedtype A : P }`)
- Extensions where a generic parameter made is concrete by a same-type requirement (`extension Array where Element == Int`)

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
```
Foundation/NSData.swift:19:8: error: module file was created by an older version of the compiler; rebuild 'Dispatch' and try again: /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/buildbot_linux/libdispatch-linux-x86_64/src/swift/Dispatch.swiftmodule
05:32:27 import Dispatch
05:32:27        ^
```

Anyone know what's going on? @shahmishal

**Comment by shahmishal** [comment]
@swift-ci Please clean test Linux

**Comment by slavapestov** [comment]
This PR has been superseded by https://github.com/apple/swift/pull/4524

**Pull request closed without merging**
