### PR TITLE
Remove implicit conversion from DeclBaseName to Identifier

### PR DESCRIPTION
**Pull request by ahoppen**
The implicit conversion from DeclBaseName to Identifier just existed to aid migration from Identifier to DeclBaseName and is no longer needed. It will technically not even be correct once special names are introduced.

This includes the changes from #9975, #9976, #9977

### CODE REVIEW

**Comment by ahoppen** [comment]
Please test with following pull request:
apple/swift-lldb#206

@swift-ci Please test

**Comment by ahoppen** [comment]
Rebased onto an updated diagnostics branch.

@swift-ci Please test

**Comment by jrose-apple** [comment]
By the way, I'm thinking we should hold off on landing this one (and the actual introduction of special names) until after the final rebranching of swift-4.0-branch (which should happen today or tomorrow). That way it won't have a chance of destabilizing the 4.0 release, but we'll still be able to cherry-pick things without having to fix them up on the other side.

**Review by jrose-apple — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please test and merge

**Pull request merged**
