### PR TITLE
Add some tests

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@jrose-apple I added the @objc test as you suggested -- is this what you had in mind?

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
Ah, I would have preferred a test that shows that that isn't being treated as {{@objc}}, but yes, thank you.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Pull request merged**
