### PR TITLE
build: explicitly state arch for ICU

### PR DESCRIPTION
**Pull request by compnerd**
This is needed to support cross-compilation on targets which do not
support FAT binaries (i.e. non-MachO targets).  The primary user of this
functionality right now is Windows, but this support is needed for Linux
and android as well.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @gottesmm @modocache @gonzalolarralde

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by gottesmm** [comment]
@compnerd I don't remember how all of this fits together (I would have to review/page in the code again). @Rostepher any thoughts?

**Comment by compnerd** [comment]
@gottesmm this basically creates a ton more cached CMake values to specify the ICU libraries for each (os, arch) pair.  This enables multiple cross-compiled builds for non-MachO targets which do not have FAT binaries.  It effectively changes the naming pattern for the variables.

**Comment by compnerd** [comment]
@gottesmm what do you think of merging this?  This is really needed to get the Windows cross-compilation story fixed up.

**Comment by gottesmm** [comment]
I see what you did. It looks overall good. Can you double check that you caught all ICU checks?

**Comment by compnerd** [comment]
@gottesmm pretty sure that I have got all the sites covered here

**Comment by gottesmm** [comment]
Then led er rip

**Pull request merged**
