### PR TITLE
[NFC] Remove Some Users of -solver-enable-operator-designated-types

### PR DESCRIPTION
**Pull request by CodaFi**
There are now two regression tests that need this feature enabled to pass.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Review by xedin — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Comment by CodaFi** [comment]
XFAIL'ed LLDB test is actually non-deterministic.

**Comment by CodaFi** [comment]
@swift-ci please smoke test macOS platform

**Comment by CodaFi** [comment]
⛵️

**Pull request merged**
