### PR TITLE
TensorFlow: remove unnecessary dependency (NFC)

### PR DESCRIPTION
**Pull request by compnerd**
This removes the `SwiftOnoneSupport` build dependency which is now
handled properly by the build system.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @dan-zheng

**Comment by compnerd** [comment]
@swift-ci please test tensorflow

**Review by dan-zheng — APPROVED** [review]

**Comment by dan-zheng** [comment]
[CI fails with linker errors](https://ci-external.swift.org/job/swift-PR-TensorFlow-Linux/3397/console):
```
[83/84][ 98%][576.569s] Linking CXX shared library lib/swift/linux/x86_64/libswiftTensorFlow.so
FAILED: lib/swift/linux/x86_64/libswiftTensorFlow.so 
: && /home/swiftci/jenkins/workspace/swift-PR-TensorFlow-Linux/Ninja-ReleaseAssert+stdlib-Release/llvm-linux-x86_64/./bin/clang++ -fPIC -Wno-unknown-warning-option -Werror=unguarded-availability-new -fno-stack-protector -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -std=c++14 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-class-memaccess -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -fdiagnostics-color -ffunction-sections -fdata-sections -Werror=switch -Wdocumentation -Wimplicit-fallthrough -Wunreachable-code -Woverloaded-virtual -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -O3  -Wl,-z,defs -target x86_64-unknown-linux-gnu -fuse-ld=gold  "-L/home/swiftci/jenkins/workspace/swift-PR-TensorFlow-Linux/Ninja-ReleaseAssert+stdlib-Release/swift-linux-x86_64/./lib/swift/linux/x86_64" "-L/home/swiftci/jenkins/workspace/swift-PR-TensorFlow-Linux/Ninja-ReleaseAssert+stdlib-Release/swift-linux-x86_64/./bin/../lib/swift/linux/x86_64" "-L/home/swiftci/jenkins/workspace/swift-PR-TensorFlow-Linux/Ninja-ReleaseAssert+stdlib-Release/swift-linux-x86_64/./bin/../lib/swift/linux" "-L/usr/lib/x86_64-linux-gnu" "-L/usr/lib/x86_64-linux-gnu" -shared -Wl,-soname,libswiftTensorFlow.so -o lib/swift/linux/x86_64/libswiftTensorFlow.so stdlib/public/TensorFlow/LINUX/x86_64/TensorFlow.o stdlib/public/CTensorFlow/CMakeFiles/swiftCTensorFlow-linux-x86_64.dir/ctensorflow_init.cpp.o lib/swift/linux/x86_64/swiftrt.o -L/home/swiftci/jenkins/workspace/swift-PR-TensorFlow-Linux/Ninja-ReleaseAssert+stdlib-Release/llvm-linux-x86_64/./lib -Wl,-rpath,"\$ORIGIN:/usr/lib/swift/linux:/home/swiftci/jenkins/workspace/swift-PR-TensorFlow-Linux/tensorflow/bazel-bin/tensorflow" -lpthread -latomic -ldl lib/swift/linux/x86_64/libswiftPython.so lib/swift/linux/x86_64/libswiftCore.so lib/swift/linux/x86_64/libswiftGlibc.so /home/swiftci/jenkins/workspace/swift-PR-TensorFlow-Linux/tensorflow/bazel-bin/tensorflow/libtensorflow.so && :
stdlib/public/TensorFlow/LINUX/x86_64/TensorFlow.o:TensorFlow.o:function $s10TensorFlow013randomSeedForaB05usings5Int32V5graph_AE2optAeF_AeGtSg_tF: error: undefined reference to '$sSn15uncheckedBoundsSnyxGx5lower_x5uppert_tcfCSi_Tg5'
stdlib/public/TensorFlow/LINUX/x86_64/TensorFlow.o:TensorFlow.o:function $s10TensorFlow013randomSeedForaB05usings5Int32V5graph_AE2optAeF_AeGtSg_tF: error: undefined reference to '$sSn8containsySbxFSi_Tg5'
stdlib/public/TensorFlow/LINUX/x86_64/TensorFlow.o:TensorFlow.o:function $s10TensorFlow013randomSeedForaB05usings5Int32V5graph_AE2optAeF_AeGtSg_tF: error: undefined reference to '$sSn15uncheckedBoundsSnyxGx5lower_x5uppert_tcfCSi_Tg5'
stdlib/public/TensorFlow/LINUX/x86_64/TensorFlow.o:TensorFlow.o:function $s10TensorFlow013randomSeedForaB05usings5Int32V5graph_AE2optAeF_AeGtSg_tF: error: undefined reference to '$sSn8containsySbxFSi_Tg5'
stdlib/public/TensorFlow/LINUX/x86_64/TensorFlow.o:TensorFlow.o:function $s10TensorFlow013randomSeedForaB05usings5Int32V5graph_AE2optAeF_AeGtSg_tF: error: undefined reference to '$sSn15uncheckedBoundsSnyxGx5lower_x5uppert_tcfCSi_Tg5'
stdlib/public/TensorFlow/LINUX/x86_64/TensorFlow.o:TensorFlow.o:function $s10TensorFlow013randomSeedForaB05usings5Int32V5graph_AE2optAeF_AeGtSg_tF: error: undefined reference to '$sSn8containsySbxFSi_Tg5'
stdlib/public/TensorFlow/LINUX/x86_64/TensorFlow.o:TensorFlow.o:function $s10TensorFlow013randomSeedForaB05usings5Int32V5graph_AE2optAeF_AeGtSg_tF: error: undefined reference to '$sSn15uncheckedBoundsSnyxGx5lower_x5uppert_tcfCSi_Tg5'
stdlib/public/TensorFlow/LINUX/x86_64/TensorFlow.o:TensorFlow.o:function $s10TensorFlow013randomSeedForaB05usings5Int32V5graph_AE2optAeF_AeGtSg_tF: error: undefined reference to '$sSn8containsySbxFSi_Tg5'
```

Perhaps the `SwiftOnoneSupport` dependency is actually necessary?

**Comment by compnerd** [comment]
No, this is a "bogus" dep that is needed.  The module is force compiled in debug mode.

**Pull request closed without merging**
