### PR TITLE
Revert "[Macros] Unify macro resolution under `ResolveMacroRequest`"

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/swift#63247

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by hborla** [comment]
Thank you @compnerd, I filed https://github.com/apple/swift/issues/63290 to investigate why `@swift-ci please smoke test and merge` is so unreliable for Windows. We need to either fix that, or remove the ability to totally by-pass building Windows.

**Comment by shahmishal** [comment]
We need to make Windows required check, and avoid having these types of failures.

**Comment by shahmishal** [comment]
Trigger issue is resolved now

**Comment by shahmishal** [comment]
Merged this PR to unblock Windows CI

**Pull request merged**
