### PR TITLE
[ConstraintSystem] NFC: Move `ConstraintSystem.h` and related headers to `include/swift/Sema`

### PR DESCRIPTION
**Pull request by xedin**
Final step (first was https://github.com/apple/swift/pull/34206) in enabling unit testing for constraint system and related structures.

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please clean test

**Comment by xedin** [comment]
I have prepared a test fixture already, going to push that separately.

**Comment by xedin** [comment]
@swift-ci please clean test

**Review by hborla — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Comment by xedin** [comment]
🤞

**Comment by xedin** [comment]
@swift-ci please smoke test Linux platform

**Comment by xedin** [comment]
Please test with following pull request:
https://github.com/apple/swift-tools-support-core/pull/142

@swift-ci please test Linux platform

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Pull request merged**
