### PR TITLE
[SIL Diagnostics & Tests] Re-add diagnostics for detecting invalid conversions from  floating point literals to integers (<rdar://39730762>)

### PR DESCRIPTION
**Pull request by ravikandhadai**
Add test cases for checking the correctness of the diagnostics.
Contains tests specific to x86 and non-x86 architectures.

### CODE REVIEW

**Comment by ravikandhadai** [comment]
@eeckstein  @stephentyrone I had to revert the diagnostics for floating point to integer conversions due to an internal build failure. The issue was that Float80 was not available in non-x86 architectures. In this commit, I have updated and partitioned the tests so that they could be run on x86 and non-x86 architectures.

**Comment by ravikandhadai** [comment]
@swift-ci  please smoke test

**Comment by ravikandhadai** [comment]
@swift-ci please smoke test

**Review by eeckstein — APPROVED** [review]
thanks, lgtm!

**Review by stephentyrone — APPROVED** [review]
OK.

**Comment by ravikandhadai** [comment]
@swift-ci please smoke test merge

**Comment by ravikandhadai** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
