### PR TITLE
[sourcekitd] Expose the 'implicit' symbol role in the 'index' request response

### PR DESCRIPTION
**Pull request by nathawes**
Resolves rdar://problem/48148270.

### CODE REVIEW

**Comment by nathawes** [comment]
@swift-ci test

**Review by akyrtzi — APPROVED** [review]

**Comment by nathawes** [comment]
@swift-ci please test and merge

**Comment by nathawes** [comment]
@swift-ci please smoke test

**Comment by nathawes** [comment]
@swift-ci please smoke test Linux

**Pull request merged**
