### PR TITLE
[interop][SwiftToCxx] add @_expose(Cxx) attribute suppport

### PR DESCRIPTION
**Pull request by hyp**
This attribute instructs the compiler that this declaration should be included in the generated C++ bindings

### CODE REVIEW

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test source compatibility

**Comment by hyp** [comment]
@swift-ci please test source compatibility

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test windows platform

**Comment by hyp** [comment]
@swift-ci please test source compatibility

**Comment by hyp** [comment]
@swift-ci please test windows platform

**Review by zoecarver — APPROVED** [review]
Very excited to see this!

**Comment by hyp** [comment]
@swift-ci please test source compatibility

**Comment by hyp** [comment]
@swift-ci please test

**Pull request merged**
