### PR TITLE
[Preset] include sourcekit-inproc in default install on Linux

### PR DESCRIPTION
**Pull request by norio-nomura**
Resolves [SR-3699](https://bugs.swift.org/browse/SR-3699).

Is there any reason to not do this yet?

### CODE REVIEW

**Comment by alblue** [comment]
@swift-ci please test

**Comment by alblue** [comment]
There's no particular reason why this can't be done, but I haven't tested it yet with one of the build presets that packages up the instance. I'll try and build this tomorrow on my Ubuntu and Darwin boxes to verify that it doesn't have any unforseen issues.

**Comment by norio-nomura** [comment]
Ah, we should configure `sourcekitdInProc` to having `RUNPATH`.

**Comment by norio-nomura** [comment]
I added a commit that configure `RPATH` for loading `libdispatch.so` in relative path.

**Comment by alblue** [comment]
@swift-ci please test

**Comment by norio-nomura** [comment]
As a result of doing some verifications, I came to the conclusion that I can not use it as it is.
The following workarounds seem to be necessary for proper operation.
```
ln -s /usr/lib/sourcekitdInProc.framework/sourcekitdInProc /usr/lib/libsourcekitdInProc.so
```
It seems necessary to change the installation destination on Linux.

**Comment by alblue** [comment]
There's probably an easy fix somewhere to solve the installation path without needing a symlink. I'll have a look and see but if you can find/test as well that would be great. 

Alex

**Comment by norio-nomura** [comment]
Not in `apple/swift`, but we have some tests failing on SourceKitten with `sourcekitdInProc` in Swift 3.1 for Linux that built by me. https://github.com/jpsim/SourceKitten/issues/354
Those tests failed even by applying a workaround using symlink.

**Comment by norio-nomura** [comment]
https://github.com/norio-nomura/swift/tree/enable-sourcekit-test
It needs renaming `sourcekitdInProc` to proper name.

**Comment by norio-nomura** [comment]
I added https://github.com/norio-nomura/swift/commit/d9a7f494c3c50023b41b463944453ff7de2d68ba renaming to `libsourcekitdInProc.so`.

**Comment by norio-nomura** [comment]
Opened https://github.com/apple/swift/pull/8485

**Comment by norio-nomura** [comment]
Adjusted rpath that assuming `sourcekit-inproc`'s path is `/usr/lib/libsourcekitdInProc.so` by https://github.com/apple/swift/pull/8485

**Comment by alblue** [comment]
@swift-ci please smoke test

**Comment by norio-nomura** [comment]
@alblue What else is needed to advance this PR?

**Comment by norio-nomura** [comment]
#8485 has been reverted by #8988. 😞

**Comment by felix91gr** [comment]
I think now this can be merged... right? Since #9025 completed the missing piece in #8485 ^^

**Comment by alblue** [comment]
Can we rebase the change against master to check it applies, and then we can kick off tests again?

Alex

**Comment by norio-nomura** [comment]
rebased.

**Comment by alblue** [comment]
@swift-CIA please smoke test

**Comment by alblue** [comment]
@swift-ci please smoke test

**Comment by norio-nomura** [comment]
Can we retry test?

**Comment by CodaFi** [comment]
@swift-ci please clean smoke test Linux platform

**Comment by norio-nomura** [comment]
Can we retry?

**Comment by norio-nomura** [comment]
I think that failed test is not related to my changes…
https://ci.swift.org/job/swift-PR-Linux-smoke-test/7184/consoleFull#708282560ee1a197b-acac-4b17-83cf-a53b95139a76

**Comment by felix91gr** [comment]
I think you can test it, but merging with the latest tag instead of with
the latest commit.

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test Linux platform

**Comment by norio-nomura** [comment]
Yay! 🙌  Thanks! 🙏

**Comment by felix91gr** [comment]
🎉🎉🎉
Awesome!

**Pull request merged**
