### PR TITLE
Explicitly represent "pseudo-generic" functions in SIL

### PR DESCRIPTION
**Pull request by rjmccall**
#### Resolves rdar://26354279.

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

Pseudo-generic functions do not have access to their type arguments at runtime.
Use this to fix the emission of native thunks for imported ObjC-generic
initializers, since they may need to perform bridging.

For now, pseudo-genericity is all-or-nothing, but we may want to
make it apply only to certain type arguments.

Also, clean up some code that was using dead mangling nodes.

### CODE REVIEW

**Comment by rjmccall** [comment]
@jckarter Please review.

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by jckarter** [comment]
LGTM.

**Comment by jckarter** [comment]
@rjmccall Looks like there are some conflicts now.

**Comment by rjmccall** [comment]
Yeah, any change to the serialization format causes a conflict on the minor version, intentionally.  Fixed.

**Pull request merged**
