### PR TITLE
[TF] TensorPair rename to resolve TF-258.

### PR DESCRIPTION
**Pull request by eaplatanios**

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Review by rxwei — APPROVED** [review]

**Comment by eaplatanios** [comment]
@rxwei Given that 0.2 is out, I think we should close this, in favor of #22854.

**Comment by rxwei** [comment]
Yep, sorry this didn’t make it to the build.

**Comment by eaplatanios** [comment]
No worries. It was quite redundant to be honest given the other PR. :)

**Pull request closed without merging**
