### PR TITLE
build: address linter warnings

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by ematejska** [comment]
@swift-ci please test macos

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by ematejska** [comment]
@swift-ci please test macOS platform

**Comment by ematejska** [comment]
Reprodueced the error locally and checked this fixed it.   The buildbot failures make no sense.  Proceeding with merge.

**Pull request merged**
