### PR TITLE
Second pass at "Add -prefix-serialized-debugging-options" (#39544)

### PR DESCRIPTION
**Pull request by rmaz**
Second pass at https://github.com/apple/swift/pull/39138

Tests updated to handle windows path separators.

This reverts commit f5aa95b381a52838d209b05465c81a888de82dd9.

### CODE REVIEW

**Comment by rmaz** [comment]
@drodriguez could you kick off the windows tests pls

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by drodriguez** [comment]
@swift-ci please test Windows platform

**Comment by drodriguez** [comment]
@swift-ci please test

**Comment by drodriguez** [comment]
https://ci-external.swift.org/job/swift-PR-windows/17389/ was the correct Windows test from before. It failed in https://ci-external.swift.org/job/swift-PR-windows/17396/ for Jenkins reasons. Restarting again.

@swift-ci please test Windows platform

**Pull request merged**
