### PR TITLE
🌲Revert "Add driver options to swift to enable MCCAS."

### PR DESCRIPTION
**Pull request by etcwilde**
Commit 3c949028e8363463c5520aab1ea49c24f5103b6c broke Swift testing on rebranch on CI.
This commit was committed straight to rebranch. Reverting to unbreak rebranch.

rdar://115311189

### CODE REVIEW

**Review by cachemeifyoucan — APPROVED** [review]
LGTM

@rastogishubham Please do not merge in the future when all reviewers that provided feedback hasn't approved yet (feel free to ping them). 

This test needs to be guarded with macOS only.

**Comment by bnbarham** [comment]
@rastogishubham the test is failing on Linux, as it was in the original PR.

**Comment by etcwilde** [comment]
@rastogishubham, rebranch is red, but red in a specific way. If it fails and you're not sure if it is a new failure, please ask either me, or @bnbarham to double-check. Thanks.

**Comment by rastogishubham** [comment]
Sorry about that, it won't happen again, as steven mentioned, the test has to be guarded with macos I will put up a new PR with that

**Pull request merged**
