### PR TITLE
Changed copyright (2017 -> 2018)

### PR DESCRIPTION
**Pull request by arguiot**
We are in 2018, so I changed the copyright.

New copyright: Copyright (c) 2014 - 2018 Apple Inc. and the Swift project authors

### CODE REVIEW

**Comment by arguiot** [comment]
@swift-ci , could you check just to make sure I didn't break something

**Comment by xwu** [comment]
Thanks, but @AndrewSB is already working on an automated solution, as discussed in #14577. As discussed there, the code owners want more fine-grained notices that update only when the specific file is touched.

**Comment by arguiot** [comment]
Shall I close this Pull Request then?

**Comment by AndrewSB** [comment]
Yes please

**Pull request closed without merging**
