### PR TITLE
5.9: [IRGen] Add metadata pack markers for more instructions.

### PR DESCRIPTION
**Pull request by nate-chandler**
**Description:** Cleanup pack metadata when it's allocated for a destroy, alloc_stack, or other instruction when it involves a pack type.

SIL has no notion of metadata or witness tables.  SIL, however, is the right level at which to fixup stack nesting, ensuring that the various stack allocated things obey stack discipline.  When certain instructions are IRGen'd, packs of metadata and witness tables may be allocated on the stack.  Forcing these stack allocations to obey stack has two parts: (1) IRGen's SIL pass PackMetadataMarkerInserter and (2) IRGen itself.  In (1), a list (which this patch extends) of instructions which may result in pack metadata being allocated on the stack is consulted; each such instruction results in new marker instructions being inserted: a single `alloc_pack_metadata` instruction is inserted before it, and some number of `dealloc_pack_metadata` instructions are inserted on its boundary.  In (2), the on-stack metadata and witness tables emitted while IRGen'ing each such instruction are recorded.  Then when each `dealloc_pack_metadata` instruction is visited, those metadata and witness tables are cleaned up in reverse order.

The purpose of the list of instructions used by (1) is to limit the number of such marker instructions that are created.  Here, three new instructions are conditionally added to the list: `destroy_addr`, `destroy_value` and `alloc_stack`.  Such instructions only get markers if the type that they are destroying involves a pack.  

Finally, all (non-stack allocating, non-function exiting) other instructions are also given markers if any of their operands or results involve a pack type.  This will help to avoid similar problems in the future.
**Risk:** Low.  The change is just to expand the list of instructions that get these markers.
**Scope:** Narrow.  This only affects variadic generics code.
**Original PR:** https://github.com/apple/swift/pull/67493 , https://github.com/apple/swift/pull/67567 , https://github.com/apple/swift/pull/67569 , https://github.com/apple/swift/pull/67778
**Reviewed By:** @aschwaighofer
**Testing:** Added @slavapestov's source-level test cases that previously hit an assertion failure.
**Resolves:** rdar://112792831

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by aschwaighofer — APPROVED** [review]
lgtm

**Review by tbkka — APPROVED** [review]

**Pull request merged**
