### PR TITLE
[Gardening] Clean Up OS Conditionals With canImport and Vendor=apple

### PR DESCRIPTION
**Pull request by CodaFi**
Clean up a few general patterns that are now obviated by canImport

This aligns more generally with the cleanup that the Swift Package
Manager has already done in their automated XCTest-plumbing tool in
apple/swift-package-manager#1826.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by cyndyishida** [comment]
Could usages of `REQUIRES: objc_interop` be replaced with `REQUIRES: VENDOR=apple` too?

**Comment by CodaFi** [comment]
Absolutely! I think it would make for a great cleanup to the tests that use the mock SDK specifically. I'm unsure if we currently support, or may support in the future, a non-Darwin platform that undertakes the effort necessary to satisfy `objc_interop` but in such a case we ought to leave the more codegen/execution-oriented tests alone.

**Comment by compnerd** [comment]
@cyndyishida @CodaFi I dont think that conflating `VENDOR=apple` and `REQUIRES: objc_interop` makes sense.  As long as you have a compatible ObjC runtime, it is possible to enable ObjC interop elsewhere.  Please don't mix the two.

**Review by compnerd — APPROVED** [review]
I'm still not a fan of the `canImport` means because it just checks if the module exists.  The module existing doesn't mean that it is the correct module to import IMO.

**Comment by CodaFi** [comment]
Certainly, but should a future platform define their own `Darwin` or `Glibc`, we'll need to have a stern talking-to with them anyways about naming conventions!

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
