### PR TITLE
Warnings Compiling Swift: Fix redundant constraint warnings with Box types

### PR DESCRIPTION
**Pull request by therealbnut**
These implementations of `Box<T: Hashable>` implement the `==` operator, which is unnecessarily constrained to `Equatable`. It causes compile time warnings, this PR fixes those.

```
warning: redundant conformance constraint 'T': 'Equatable' 
```

### CODE REVIEW

**Comment by therealbnut** [comment]
This change seems to reapply basically the same thing as e3ea6058bc18eec3d97001e546981fec88bec3f6, which is a little concerning, someone may have accidentally clobbered some changes.

**Comment by slavapestov** [comment]
@lplarson Are you the right person to review this?

**Comment by lplarson** [comment]
@slavapestov Yeah

**Comment by lplarson** [comment]
@swift-ci benchmark

**Comment by therealbnut** [comment]
@lplarson these benchmark regressions seem unrelated, are they within acceptable tolerances?

**Comment by lplarson** [comment]
My apologies for a late response. Please resolve the merge conflicts and I'll run another benchmark to see if we get the same regressions.

**Comment by therealbnut** [comment]
@lplarson resolved, thanks

**Comment by DougGregor** [comment]
@swift-ci benchmark

**Comment by DougGregor** [comment]
@swift-ci please benchmark

**Comment by lplarson** [comment]
The regressions appear to be noise.

**Comment by lplarson** [comment]
@swift-ci smoke test and merge

**Comment by lplarson** [comment]
@swift-ci smoke test and merge

**Comment by therealbnut** [comment]
thanks everyone for the review :)

**Pull request merged**
