### PR TITLE
[benchmarks] Add an option to build with coverage info.

### PR DESCRIPTION
**Pull request by dcci**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by dcci** [comment]
To give people a little more context about this:
I'm working on a script to test lldb and I'm using the benchmark suite executables as my corpora. Having coverage allows me to understand which lines are actually executed (or hot) and set breakpoints there accordingly.

**Comment by dcci** [comment]
@swift-ci test

**Review by gottesmm — APPROVED** [review]

**Comment by vedantk** [comment]
I'd expect this to specify `-profile-generate` as well.

**Comment by dcci** [comment]
OK, updating.

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
