### PR TITLE
[Diag] [Typechecker] Diagnose throw in defer properly

### PR DESCRIPTION
**Pull request by theblixguy**
The body of a `defer` statement is an implicit `FuncDecl`, but that's implementation detail and it shouldn't leak into diagnostics. For example, we end up emitting an incorrect diagnostic when using a `throw` in a `defer`:

```swift
defer { throw Foo.bar } // error is not handled because the enclosing function is not declared 'throws'
```

Treat `throw` the same way we treat other control flow statements, like `return`, `break` & `yield` when used inside a `defer`.

### CODE REVIEW

**Comment by theblixguy** [comment]
cc @xedin

**Review by xedin — APPROVED** [review]
LGTM!

**Comment by xedin** [comment]
@swift-ci please smoke test and merge

**Comment by xedin** [comment]
@theblixguy Looks like there is a problem in verifier.

**Comment by theblixguy** [comment]
@xedin Hmm this makes sense since we're backing out of error type checking if we're in a defer body. I have fixed it now. Could you trigger the test again? Should be all good!

**Comment by xedin** [comment]
@swift-ci please smoke test and merge

**Comment by xedin** [comment]
@swift-ci please smoke test and merge

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by theblixguy** [comment]
@xedin Could you trigger the CI again? Had to make a small change! Thank you!

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by theblixguy** [comment]
Unrelated build failure: 

> 15:10:35 The following build commands failed:
15:10:35 	PhaseScriptExecution Install\ Swift\ compiler\ resources /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/buildbot_incremental/lldb-macosx-x86_64/lldb.build/CustomSwift-Release/LLDB.build/Script-49DD45051B4EDB4A00DB3579.sh

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Comment by theblixguy** [comment]
Seems like the bots are not working correctly today 😅

**Comment by xedin** [comment]
We'll just have to wait until that's cleared, unfortunately...

**Comment by theblixguy** [comment]
No problem!

**Comment by theblixguy** [comment]
Okay, let's give the tests one more try. @xedin can you invoke the CI?

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by theblixguy** [comment]
All tests have passed 🙏 🎉

**Comment by xedin** [comment]
Ok, great! Let's run source compatibility just in case...

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by theblixguy** [comment]
Hmm I don't think the source compat test ran (or maybe the CI screwed up) 🤔 

> Problem accessing /job/swift-PR-source-compat-suite/2695/. Reason:
Not Found

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Pull request merged**
