### PR TITLE
Move SIL parser to GenericFunctionTypes

### PR DESCRIPTION
**Pull request by slavapestov**
As far as I know, the SIL parser was the last major piece that relied on PolymorphicFunctionType in a non-trivial way. This series of patches brings us closer to removing PolymorphicFunctionType, SILFunction::ContextGenericParams, and ConstantInfo::{Context,Inner}GenericParams.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
Awesome!

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
NullPointerException...? Time to rewrite Jenkins in Swift.

**Comment by slavapestov** [comment]
@swift-ci Please test

**Pull request merged**
