### PR TITLE
Default to building the early SwiftSyntax package.

### PR DESCRIPTION
**Pull request by DougGregor**
Switch the polarity for early SwiftSyntax to build it by default (and embed it into Swift tools). One can use `build-script --skip-early-swiftsyntax` to disable this.

### CODE REVIEW

**Comment by DougGregor** [comment]
https://github.com/apple/swift-syntax/pull/646

@swift-ci please test

**Comment by DougGregor** [comment]
The failure here is because we're using implicit opening of existentials, but that's only supported in Swift 5.7 and newer. Trying to address this via https://github.com/apple/swift-syntax/pull/648

**Comment by DougGregor** [comment]
@swift-ci please test

**Review by kingzooz — APPROVED** [review]

**Comment by DougGregor** [comment]
Well, the good news is that `earlyswiftsyntax` built for macOS. Linux looks like it skipped building it, and there are some failures remaining that need investigation:

  Swift-validation(macosx-x86_64) :: BuildSystem/core_lipo_and_non_core_epilogue_opts.test
  Swift-validation(macosx-x86_64) :: BuildSystem/default_build_still_performs_epilogue_opts_after_split.test
  Swift-validation(macosx-x86_64) :: BuildSystem/infer_dumps_deps_if_verbose_build.test
  Swift-validation(macosx-x86_64) :: BuildSystem/infer_implies_install_all.test
  Swift-validation(macosx-x86_64) :: BuildSystem/test_early_swift_driver_and_infer.swift

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
https://github.com/apple/llvm-project/pull/5289

@swift-ci please test

**Comment by DougGregor** [comment]
https://github.com/apple/llvm-project/pull/5289

@swift-ci please test

**Comment by DougGregor** [comment]
macOS failures:

```
Failed Tests (2):
  Swift-Unit :: DependencyScan/./swiftScanTests/failed_to_discover_tests_from_gtest
  Swift-validation(macosx-x86_64) :: Python/python_lint.swift
```

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test https://github.com/apple/llvm-project/pull/5322

**Comment by DougGregor** [comment]
https://github.com/apple/llvm-project/pull/5322

@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Pull request merged**
