### PR TITLE
[Lexer] Add a few test cases for hex number literal

### PR DESCRIPTION
**Pull request by rintaro**
#### What's in this pull request?

Follow up on #3124.
Added several test cases.

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please test and merge

**Comment by jckarter** [comment]
There's also the case of `0x1.p` or `0x1.p2`. The first one isn't a valid float literal, but the second one is a toss-up—it'd be accepted as a float literal in C, at least.

**Comment by jckarter** [comment]
I guess we already diverge from C by requiring a digit after the dot in decimal literals (IOW `1.` isn't accepted) so it'd be reasonable to require the same of hex float literals.

**Comment by rintaro** [comment]
[Current published specification](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/LexicalStructure.html#//apple_ref/doc/uid/TP40014097-CH30-ID416) requires `"." ­hexadecimal-digit ...`.
So as implementation: https://github.com/apple/swift/blob/a5eed38/lib/Parse/Lexer.cpp#L872-L877

­

**Comment by jckarter** [comment]
Makes sense, thanks. Got time to add those as test cases then?

**Comment by rintaro** [comment]
I'd be happy to do that, but I'm very tired today. 
I will do that in tomorrow. (in Japan).

**Comment by jckarter** [comment]
No problem, thanks for fixing this!

**Pull request merged**
