### PR TITLE
Fix a comment typo in DerivedConformances

### PR DESCRIPTION
**Pull request by noahsark769**
While reading through #9004 I noticed that there was a comment typo, so I figured I'd submit a small request to fix it.

### CODE REVIEW

**Comment by CodaFi** [comment]
Honestly, could you improve the whole comment?  This invariant is already stated in the docs for this function, the "second clause" after the semicolon is really what should be here.

**Review by Jceciliani — APPROVED** [review]
Correct comment text edit.

**Comment by CodaFi** [comment]
@swift-ci please smoke test and merge

**Comment by noahsark769** [comment]
Wow, really sorry for the lack of followup here, this totally fell off my radar. Appreciate the merge, thanks!

**Pull request merged**
