### PR TITLE
[AST] NFC: Rename `getArgumentInterfaceType` -> `getPayloadInterfaceType`

### PR DESCRIPTION
**Pull request by hamishknight**
IMO this is a slightly clearer name, many of its uses already use the term "payload".

### CODE REVIEW

**Comment by hamishknight** [comment]
https://github.com/swiftlang/llvm-project/pull/9353

@swift-ci please test

**Comment by hamishknight** [comment]
https://github.com/swiftlang/llvm-project/pull/9353

@swift-ci please test

**Comment by felipepiovezan** [comment]
Hi @hamishknight! Changes to the swift AST interface almost always break LLDB, so I'd really appreciate it if you could wait until one of us have a chance to see these PRs on a weekday so that our bots are not broken over the weekend :)

**Comment by hamishknight** [comment]
Sure thing @felipepiovezan, sorry about that! I missed the rebranch cherry-pick, but that's landed now.

**Pull request merged**
