### PR TITLE
Add a SIL debug info verifier to detect when one source variable has

### PR DESCRIPTION
**Pull request by adrian-prantl**
conflicting types.
This causes a difficult to debug LLVM AsmPrinter assertion much later
on, so it's valuable to detect this as early as possible.

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci please test

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
