### PR TITLE
[5.3] Fix batch mode llvm ir hash consistency test

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Review by CodaFi — APPROVED** [review]

**Comment by shahmishal** [comment]
@compnerd is this known failure? 
```
FAILED: dispatch_debug.exe 
cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=tests\CMakeFiles\dispatch_debug.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1424~1.283\bin\Hostx64\x64\link.exe /nologo tests\CMakeFiles\dispatch_debug.dir\dispatch_debug.c.obj  /out:dispatch_debug.exe /implib:tests\dispatch_debug.lib /pdb:dispatch_debug.pdb /version:0.0  /INCREMENTAL:NO /INCREMENTAL:NO /subsystem:console -LIBPATH:C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1424~1.283\Lib\x64   -LIBPATH:C:\PROGRA~2\WI3CF2~1\10\Lib\100183~1.0\ucrt\x64   -LIBPATH:C:\PROGRA~2\WI3CF2~1\10\Lib\100183~1.0\um\x64 src\dispatch.lib  src\BlocksRuntime\BlocksRuntime.lib  tests\bsdtests.lib  bcrypt.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
MT: command "C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\mt.exe /nologo /manifest dispatch_debug.exe.manifest /outputresource:dispatch_debug.exe;#1" failed (exit code 0x1f) with the following output:

mt.exe : general error c101008d: Failed to write the updated manifest to the resource of file "dispatch_debug.exe". Access is denied.
```

**Comment by compnerd** [comment]
No, that is something that I've noticed with Jenkins though - its a race condition of some sorts with Jenkins keeping the file open.

**Comment by compnerd** [comment]
@swift-ci please test windows platform

**Pull request merged**
