### PR TITLE
Enable import of the _Concurrency module by default.

### PR DESCRIPTION
**Pull request by DougGregor**
Part of enabling concurrency support by default, rdar://76013588.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
Needed another swift-driver test fix, https://github.com/apple/swift-driver/pull/589

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by davezarzycki** [comment]
Hi @DougGregor! This broke building the Glibc module when concurrency isn't available. Is this expected? Do you mind if I add `-disable-implicit-concurrency-module-import` to that build target?

```
[41+6] Compiling /home/dave/b/q/t/tools/swift/stdlib/public/Platform/LINUX/x86_64/Glibc.o
FAILED: tools/swift/stdlib/public/Platform/LINUX/x86_64/Glibc.o
cd /home/dave/b/q/t/tools/swift/stdlib/public/Platform && /usr/bin/python3.9 /home/dave/ro_s/q/swift/utils/line-directive @/home/dave/b/q/t/tools/swift/stdlib/public/Platform/7aa33e6705ed949b3c899b802bc1d8414da9ed58.txt -- /home/dave/b/q/t/./bin/swiftc -c -sdk / -target x86_64-unknown-linux-gnu -resource-dir /home/dave/b/q/t/./lib/swift -O -D INTERNAL_CHECKS_ENABLED -D SWIFT_RUNTIME_OS_VERSIONING -module-cache-path /home/dave/b/q/t/./module-cache -no-link-objc-runtime -enable-library-evolution -Xfrontend -enforce-exclusivity=unchecked -module-name Glibc -swift-version 5 -swift-version 5 -autolink-force-load -runtime-compatibility-version none -disable-autolinking-runtime-compatibility-dynamic-replacements -warn-swift3-objc-inference-complete -Xfrontend -verify-syntax-tree -warn-implicit-overrides -module-link-name swiftGlibc -whole-module-optimization -parse-as-library -I /home/dave/b/q/t/./lib/swift/linux -o /home/dave/b/q/t/tools/swift/stdlib/public/Platform/LINUX/x86_64/Glibc.o @/home/dave/b/q/t/tools/swift/stdlib/public/Platform/7aa33e6705ed949b3c899b802bc1d8414da9ed58.txt
<unknown>:0: error: no such module '_Concurrency'
[41+5] Generating /home/dave/b/q/t/./lib/swift/linux/Glibc.swiftmodule/x86_64-unknown-linux-gnu.swiftmodule
FAILED: lib/swift/linux/Glibc.swiftmodule/x86_64-unknown-linux-gnu.swiftmodule lib/swift/linux/Glibc.swiftmodule/x86_64-unknown-linux-gnu.swiftdoc lib/swift/linux/Glibc.swiftmodule/x86_64-unknown-linux-gnu.swiftinterface
cd /home/dave/b/q/t/tools/swift/stdlib/public/Platform && /usr/bin/cmake -E remove -f /home/dave/b/q/t/./lib/swift/linux/Glibc.swiftmodule/x86_64-unknown-linux-gnu.swiftmodule /home/dave/b/q/t/./lib/swift/linux/Glibc.swiftmodule/x86_64-unknown-linux-gnu.swiftdoc /home/dave/b/q/t/./lib/swift/linux/Glibc.swiftmodule/x86_64-unknown-linux-gnu.swiftinterface && /usr/bin/cmake -E make_directory /home/dave/b/q/t/./lib/swift/linux /home/dave/b/q/t/./lib/swift/linux/Glibc.swiftmodule && /usr/bin/python3.9 /home/dave/ro_s/q/swift/utils/line-directive @/home/dave/b/q/t/tools/swift/stdlib/public/Platform/7aa33e6705ed949b3c899b802bc1d8414da9ed58.txt -- /home/dave/b/q/t/./bin/swiftc -emit-module -o /home/dave/b/q/t/./lib/swift/linux/Glibc.swiftmodule/x86_64-unknown-linux-gnu.swiftmodule -avoid-emit-module-source-info -sdk / -target x86_64-unknown-linux-gnu -resource-dir /home/dave/b/q/t/./lib/swift -O -D INTERNAL_CHECKS_ENABLED -D SWIFT_RUNTIME_OS_VERSIONING -module-cache-path /home/dave/b/q/t/./module-cache -no-link-objc-runtime -enable-library-evolution -Xfrontend -enforce-exclusivity=unchecked -module-name Glibc -swift-version 5 -swift-version 5 -autolink-force-load -runtime-compatibility-version none -disable-autolinking-runtime-compatibility-dynamic-replacements -warn-swift3-objc-inference-complete -Xfrontend -verify-syntax-tree -warn-implicit-overrides -module-link-name swiftGlibc -whole-module-optimization -parse-as-library -I /home/dave/b/q/t/./lib/swift/linux -emit-module-interface-path /home/dave/b/q/t/./lib/swift/linux/Glibc.swiftmodule/x86_64-unknown-linux-gnu.swiftinterface -Xfrontend -experimental-skip-non-inlinable-function-bodies @/home/dave/b/q/t/tools/swift/stdlib/public/Platform/7aa33e6705ed949b3c899b802bc1d8414da9ed58.txt
<unknown>:0: error: no such module '_Concurrency'

```

**Comment by davezarzycki** [comment]
Actually, it's messier than that. Did I miss when/where a policy change happened? I think trying to keep "minimal dependency Swift" working has value. I hope I have a fix/workaround here: #36841

**Pull request merged**
