### PR TITLE
build: install swift-autolink-extract always

### PR DESCRIPTION
**Pull request by compnerd**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

swift supports cross-compilation.  The autolink extract tool is needed when
targeting non-Darwin targets even on Darwin.  Always install it.

### CODE REVIEW

**Comment by gribozavr** [comment]
The OS X toolchain does not support cross-compilation, so this tool would be useless (and misleading) there.  I don't think we can accept this as-is.

**Comment by compnerd** [comment]
Right, you need a linker and sysroot.  However, the default build of the swift compiler can target Linux I believe.  Would you prefer a CMake variable to indicate that this tool should be installed?

**Comment by gribozavr** [comment]
It should be an installation component, like "compiler" then.

**Comment by gribozavr** [comment]
Thanks, but `cross-driver` is not quite the right way to describe this tool.  Say you are on Linux, compiling for Linux -- then it is not a cross-compiling situation, and you still want this tool.  Could you think of a better name?

We also need to update the default set of components to include the tool on Linux, and not include it on OS X.  Could you also update presets (`utils/build-presets.ini`), so that CI artifacts continue to be usable on Linux?

**Comment by compnerd** [comment]
Sure, renamed it to "aux-driver-tools" which I think describes it well.  Updated the presets for Linux as well.

**Comment by compnerd** [comment]
@gribozavr is the new name suitable, or do you have a better suggestion?

**Comment by gribozavr** [comment]
I think something like `autolink-driver` or just `autolink-extract` would be better.  LGTM otherwise.

**Comment by compnerd** [comment]
autolink-driver sounds good to me.  Rebased and updated.

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by compnerd** [comment]
I don't have push rights, could you please take care of this for me?

**Comment by tkremenek** [comment]
@gribozavr Ok to merge?

**Pull request merged**
