### PR TITLE
Basic: inline TaskQueue serialization

### PR DESCRIPTION
**Pull request by compnerd**
This inlines two methods in the TaskQueue class definition.  The
implementation is small and would need to be replicated into the default
implementation.  This repairs the Windows build of the compiler.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @BenchR267

**Comment by compnerd** [comment]
@swift-ci please test

**Review by BenchR267 — APPROVED** [review]
Thanks!

**Comment by jrose-apple** [comment]
I don't really think this header file should include details about the JSON format. Can you add a separate .cpp file instead?

**Comment by compnerd** [comment]
@jrose-apple - sure, I can split this off into a separate TU.

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Review by jrose-apple — APPROVED** [review]

**Pull request merged**
