### PR TITLE
[TF] Set up TensorFlow high-level API library.

### PR DESCRIPTION
**Pull request by dan-zheng**
Use sources from high-level API library when building the TensorFlow module.
Currently, the library lives at https://github.com/rxwei/DeepLearning.

The high-level API library repository version is pinned in
`utils/update_checkout/update-checkout-config.json`.

Notes:
- Some changes were necessary to enable compilation.
  - Namely, the TensorFlow module is no longer built with `-enable-resilience`
    because that flag causes a crash during IRGen for the `Layer.applied(to:)`
    protocol requirement.
  - Disabling resilience required some other code changes as well.

---

[SR-9739](https://bugs.swift.org/browse/SR-9739) filed for re-enabling the -enable-resilience flag for the TensorFlow module and re-adding @_frozen attributes.

### CODE REVIEW

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow Linux

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow Linux

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow Linux

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow Linux

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow Linux

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow Linux GPU

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow Linux

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow Linux

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow Linux GPU

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow Linux GPU

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow linux

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow linux

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow linux

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow linux

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow linux

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow Linux

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow Linux

**Comment by dan-zheng** [comment]
Weird unrelated CI error `Could not find include file`. Retriggering.
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow linux

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow linux

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow linux

**Review by rxwei — APPROVED** [review]
Let's merge this.

**Comment by dan-zheng** [comment]
CI seems stuck/down for Linux.
Merging to unblock critical progress.

**Comment by dan-zheng** [comment]
[SR-9739](https://bugs.swift.org/browse/SR-9739) filed for re-enabling the `-enable-resilience` flag for the TensorFlow module and re-adding `@_frozen` attributes.

**Pull request merged**
