### PR TITLE
ClangImporter: Update Swift for changes in clang (PCH + Modules issues)

### PR DESCRIPTION
**Pull request by bcardosolopes**
This sets the NeededByPCHOrCompilationUsesPCH language option when
emitting a brigding PCH.

rdar://problem/35056912
rdar://problem/30384801

Initial patch by Adrian Prantl

(cherry picked from commit 5d5f542fe47668f80a4661ccccdb0048c9629a39)
(cherry picked from commit fa2a5779b17f50260aeaad5d9c3c0062e99f07d2)

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by bcardosolopes** [comment]
Please test with following pull request:
https://github.com/apple/swift-clang/pull/222

@swift-ci Please test

**Comment by bcardosolopes** [comment]
Please test with following pull request:
apple/swift-clang#222

@swift-ci Please test

**Comment by jrose-apple** [comment]
Ah, you don't actually want to test master against upstream-with-swift.

**Comment by bcardosolopes** [comment]
@swift-ci Please test

**Comment by millenomi** [comment]
(Will this fix https://bugs.swift.org/browse/SR-9228?)

**Comment by jrose-apple** [comment]
> (Will this fix https://bugs.swift.org/browse/SR-9228?)

Yes.

**Pull request merged**
