### PR TITLE
[NFC][Sema] Fix init diagnostic typo

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
Just for reference, caught it while investigating a diagnostic nearby via [vscode-spell-checker](https://github.com/streetsidesoftware/vscode-spell-checker) VSCode extension.

### CODE REVIEW

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test

**Review by xedin — APPROVED** [review]
Thank you!

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test MacOS platform

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test Windows Platform

**Pull request merged**
