### PR TITLE
Clean up matchTypes() and related code a little

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@xedin This is the first step in a larger cleanup of some code around InOutType and the weird LValueType/InOutType conversions. Just wanted to post this part for review since I know you're hacking here too as part of the diagnostics work. If you want I can hold off merging until your changes go in, I don't mind rebasing.

**Review by xedin — APPROVED** [review]
LGTM! It seems like the merge wouldn’t be that bad with changes I have, if you were to merge this.

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Comment by slavapestov** [comment]
```
/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/swift-corelibs-foundation/TestFoundation/TestNSString.swift:393: error: TestNSString.test_FromContentsOfURL : XCTAssertEqual failed: ("Pf
07:34:08 <o
07:34:08 
07:34:08 e is encoded as ISO-8859-1
07:34:08 ÀÁÂÃÄÅÿ
07:34:08 ±
07:34:08 ") is not equal to ("This file is encoded as ISO-8859-1
07:34:08 ÀÁÂÃÄÅÿ
07:34:08 ±
07:34:08 ") - 
```

Hmm...

**Comment by PFCAwesome** [comment]
Unsubscribe

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Pull request merged**
