### PR TITLE
Revert "consider requirements of an underscored protocol to also be underscored (take two) (#59531)"

### LINKED ISSUE #59957: SymbolGraphGen: Unsafe{Mutable?}{Raw?}Pointer members have vanished
**Describe the bug**
all APIs inherited from `_Pointer` have apparently vanished from standard library symbolgraphs as of `DEVELOPMENT-SNAPSHOT-2022-07-06-a`. many of these APIs are quite important, such as:

* [`UnsafePointer.successor()`](https://swiftinit.org/reference?overload=ss8_PointerPsE9successorxyF)
* [`UnsafePointer.init(bitPattern:)`](https://swiftinit.org/reference?overload=ss8_PointerPsE10bitPatternxSgSu_tcfc)

this only affects APIs inherited from underscored protocols, `@available(*, unavailable)` APIs (such as `SIMD2.+(_:_:)`) are unaffected.

**Steps To Reproduce**
1. generate a symbolgraph with an invocation like:

```
subprocess.run((swift_symbolgraph_extract, 
                '-skip-inherited-docs', 
                '-target', 'x86_64-unknown-linux-gnu', 
                '-output-dir', 'Swift', 
                '-module-name', 'Swift'), 
```

**Expected behavior**

`_Pointer` APIs should be present, as they are in symbolgraphs generated by the april toolchain.

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
Fixes https://github.com/apple/swift/issues/59957

This PR reverts https://github.com/apple/swift/pull/59531 to re-introduce synthesized default implementations of underscored protocols to the symbol graph under their original visibility, rather than treating them as underscored.

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Comment by QuietMisdreavus** [comment]
@swift-ci Please build toolchain macOS

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Review by franklinsch — APPROVED** [review]
Thanks!

**Pull request merged**
