### PR TITLE
[DNM] Swift 6.0.2 plus a few autodiff fixes

### PR DESCRIPTION
**Pull request by clackary**
Collects some fixes for outstanding autodiff issues.

### CODE REVIEW

**Comment by clackary** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by clackary** [comment]
@swift-ci Please Build Toolchain Linux Platform

**Comment by shahmishal** [comment]
Swift 6.0.2 was already released, please target `release/6.0` if you would like these fixes in 6.0.3.

**Comment by clackary** [comment]
I saw that 6.0.2 was released already. What I'd like to do is produce a slightly modified release toolchain that matches the latest release but that also has our AD fixes. But, it looks like I can no longer ask swift-ci for things. Not sure I technically qualify for commit access lately, but I can make the request.

**Pull request closed without merging**
