### PR TITLE
Implement several peephole optimizations to unblock further optimizations of autodiff code

### LINKED ISSUE #55830: [SR-13390] Simple calls to `gradient(at:in:)` are not optimized away
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13390      |
   |Radar             | rdar://problem/67361254         |
   |Original Reporter | @dan-zheng      |
   |Type              | Task    |
   |Status            | In Progress        |
   |Resolution        |     |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 2         |
   |Component/s       | Compiler    |
   |Labels            | Task, AutoDiff        |
   |Assignee          | @dan-zheng      |
   |Priority          | Medium      |

   

   md5: be0cdb04e957f3dc103554e1b0625a17

  </details>

**Issue Description:**

Here's an example of `gradient(at:in: )` applied to a simple function over floats.

``` swift
import _Differentiation

@differentiable
@_silgen_name("foo")
func foo(_ x: Float) -> Float {
  let y = (x * x)
  let z = y + y
  return z
}

@inline(never)
func consume<T>(_ x: T) {}

@_silgen_name("test_autodiff_gradient_apply")
func test_autodiff_gradient_apply() {
  consume(gradient(at: 10, in: foo))
}
```

The `gradient` call does not get fully optimized away in SIL:

``` java
$ swiftc -emit-sil -O Example.swift
...

// test_autodiff_gradient_apply
sil hidden @test_autodiff_gradient_apply : $@convention(thin) () -> () {
bb0:
  %0 = float_literal $Builtin.FPIEEE32, 0x41200000 // 10 // user: %24
  // function_ref foo
  %1 = function_ref @foo : $@convention(thin) (Float) -> Float // user: %2
  %2 = thin_to_thick_function %1 : $@convention(thin) (Float) -> Float to $@callee_guaranteed (Float) -> Float // user: %7
  // function_ref AD__foo__jvp_src_0_wrt_0
  %3 = function_ref @AD__foo__jvp_src_0_wrt_0 : $@convention(thin) (Float) -> (Float, @owned @callee_guaranteed (Float) -> Float) // user: %4
  %4 = thin_to_thick_function %3 : $@convention(thin) (Float) -> (Float, @owned @callee_guaranteed (Float) -> Float) to $@callee_guaranteed (Float) -> (Float, @owned @callee_guaranteed (Float) -> Float) // user: %7
  // function_ref AD__foo__vjp_src_0_wrt_0
  %5 = function_ref @AD__foo__vjp_src_0_wrt_0 : $@convention(thin) (Float) -> (Float, @owned @callee_guaranteed (Float) -> Float) // user: %6
  %6 = thin_to_thick_function %5 : $@convention(thin) (Float) -> (Float, @owned @callee_guaranteed (Float) -> Float) to $@callee_guaranteed (Float) -> (Float, @owned @callee_guaranteed (Float) -> Float) // user: %7
  %7 = differentiable_function [parameters 0] [results 0] %2 : $@callee_guaranteed (Float) -> Float with_derivative {%4 : $@callee_guaranteed (Float) -> (Float, @owned @callee_guaranteed (Float) -> Float), %6 : $@callee_guaranteed (Float) -> (Float, @owned @callee_guaranteed (Float) -> Float)} // users: %50, %48, %46, %8
  %8 = convert_escape_to_noescape %7 : $@differentiable @callee_guaranteed (Float) -> Float to $@differentiable @noescape @callee_guaranteed (Float) -> Float // users: %19, %14, %9
  %9 = differentiable_function_extract [original] %8 : $@differentiable @noescape @callee_guaranteed (Float) -> Float // user: %11
  // function_ref thunk for @callee_guaranteed (@unowned Float) -> (@unowned Float)
  %10 = function_ref @$sS2fIgyd_S2fIegnr_TR : $@convention(thin) (@in_guaranteed Float, @noescape @callee_guaranteed (Float) -> Float) -> @out Float // user: %11
  %11 = partial_apply [callee_guaranteed] %10(%9) : $@convention(thin) (@in_guaranteed Float, @noescape @callee_guaranteed (Float) -> Float) -> @out Float // users: %52, %12
  %12 = convert_function %11 : $@callee_guaranteed (@in_guaranteed Float) -> @out Float to $@callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed τ_0_0) -> @out τ_0_1 for <Float, Float> // user: %13
  %13 = convert_escape_to_noescape %12 : $@callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed τ_0_0) -> @out τ_0_1 for <Float, Float> to $@noescape @callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed τ_0_0) -> @out τ_0_1 for <Float, Float> // user: %23
  %14 = differentiable_function_extract [jvp] %8 : $@differentiable @noescape @callee_guaranteed (Float) -> Float // user: %16
  // function_ref thunk for @callee_guaranteed (@unowned Float) -> (@unowned Float, @owned @escaping @callee_guaranteed (@unowned Float) -> (@unowned Float))
  %15 = function_ref @$sS4fIegyd_Igydo_S2fxq_r0_lyS2fIsegnr_Iegnro_TR : $@convention(thin) (@in_guaranteed Float, @noescape @callee_guaranteed (Float) -> (Float, @owned @callee_guaranteed (Float) -> Float)) -> (@out Float, @owned @callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed τ_0_0) -> @out τ_0_1 for <Float, Float>) // users: %20, %16
  %16 = partial_apply [callee_guaranteed] %15(%14) : $@convention(thin) (@in_guaranteed Float, @noescape @callee_guaranteed (Float) -> (Float, @owned @callee_guaranteed (Float) -> Float)) -> (@out Float, @owned @callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed τ_0_0) -> @out τ_0_1 for <Float, Float>) // users: %53, %17
  %17 = convert_function %16 : $@callee_guaranteed (@in_guaranteed Float) -> (@out Float, @owned @callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed τ_0_0) -> @out τ_0_1 for <Float, Float>) to $@callee_guaranteed @substituted <τ_0_0, τ_0_1, τ_0_2, τ_0_3> (@in_guaranteed τ_0_0) -> (@out τ_0_1, @owned @callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed τ_0_0) -> @out τ_0_1 for <τ_0_2, τ_0_3>) for <Float, Float, Float, Float> // user: %18
  %18 = convert_escape_to_noescape %17 : $@callee_guaranteed @substituted <τ_0_0, τ_0_1, τ_0_2, τ_0_3> (@in_guaranteed τ_0_0) -> (@out τ_0_1, @owned @callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed τ_0_0) -> @out τ_0_1 for <τ_0_2, τ_0_3>) for <Float, Float, Float, Float> to $@noescape @callee_guaranteed @substituted <τ_0_0, τ_0_1, τ_0_2, τ_0_3> (@in_guaranteed τ_0_0) -> (@out τ_0_1, @owned @callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed τ_0_0) -> @out τ_0_1 for <τ_0_2, τ_0_3>) for <Float, Float, Float, Float> // user: %23
  %19 = differentiable_function_extract [vjp] %8 : $@differentiable @noescape @callee_guaranteed (Float) -> Float // user: %20
  %20 = partial_apply [callee_guaranteed] %15(%19) : $@convention(thin) (@in_guaranteed Float, @noescape @callee_guaranteed (Float) -> (Float, @owned @callee_guaranteed (Float) -> Float)) -> (@out Float, @owned @callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed τ_0_0) -> @out τ_0_1 for <Float, Float>) // users: %54, %21
  %21 = convert_function %20 : $@callee_guaranteed (@in_guaranteed Float) -> (@out Float, @owned @callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed τ_0_0) -> @out τ_0_1 for <Float, Float>) to $@callee_guaranteed @substituted <τ_0_0, τ_0_1, τ_0_2, τ_0_3> (@in_guaranteed τ_0_0) -> (@out τ_0_1, @owned @callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed τ_0_0) -> @out τ_0_1 for <τ_0_2, τ_0_3>) for <Float, Float, Float, Float> // user: %22
  %22 = convert_escape_to_noescape %21 : $@callee_guaranteed @substituted <τ_0_0, τ_0_1, τ_0_2, τ_0_3> (@in_guaranteed τ_0_0) -> (@out τ_0_1, @owned @callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed τ_0_0) -> @out τ_0_1 for <τ_0_2, τ_0_3>) for <Float, Float, Float, Float> to $@noescape @callee_guaranteed @substituted <τ_0_0, τ_0_1, τ_0_2, τ_0_3> (@in_guaranteed τ_0_0) -> (@out τ_0_1, @owned @callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed τ_0_0) -> @out τ_0_1 for <τ_0_2, τ_0_3>) for <Float, Float, Float, Float> // user: %23
  %23 = differentiable_function [parameters 0] [results 0] %13 : $@noescape @callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed τ_0_0) -> @out τ_0_1 for <Float, Float> with_derivative {%18 : $@noescape @callee_guaranteed @substituted <τ_0_0, τ_0_1, τ_0_2, τ_0_3> (@in_guaranteed τ_0_0) -> (@out τ_0_1, @owned @callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed τ_0_0) -> @out τ_0_1 for <τ_0_2, τ_0_3>) for <Float, Float, Float, Float>, %22 : $@noescape @callee_guaranteed @substituted <τ_0_0, τ_0_1, τ_0_2, τ_0_3> (@in_guaranteed τ_0_0) -> (@out τ_0_1, @owned @callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed τ_0_0) -> @out τ_0_1 for <τ_0_2, τ_0_3>) for <Float, Float, Float, Float>} // user: %28
  %24 = struct $Float (%0 : $Builtin.FPIEEE32)    // user: %27
  %25 = alloc_stack $Float                        // users: %42, %38
  %26 = alloc_stack $Float                        // users: %41, %31, %27
  store %24 to %26 : $*Float                      // id: %27
  %28 = convert_function %23 : $@differentiable @noescape @callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed τ_0_0) -> @out τ_0_1 for <Float, Float> to $@differentiable @noescape @callee_guaranteed (@in_guaranteed Float) -> @out Float // user: %29
  %29 = differentiable_function_extract [vjp] %28 : $@differentiable @noescape @callee_guaranteed (@in_guaranteed Float) -> @out Float as $@noescape @callee_guaranteed (@in_guaranteed Float) -> (@out Float, @owned @callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed τ_0_0) -> @out τ_0_1 for <Float, Float>) // user: %31
  %30 = alloc_stack $Float                        // users: %32, %31
  %31 = apply %29(%30, %26) : $@noescape @callee_guaranteed (@in_guaranteed Float) -> (@out Float, @owned @callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed τ_0_0) -> @out τ_0_1 for <Float, Float>) // users: %39, %38
  dealloc_stack %30 : $*Float                     // id: %32
  %33 = alloc_stack $Float                        // users: %40, %38, %37
  %34 = integer_literal $Builtin.Int64, 1         // user: %35
  %35 = builtin "sitofp_Int64_FPIEEE32"(%34 : $Builtin.Int64) : $Builtin.FPIEEE32 // user: %36
  %36 = struct $Float (%35 : $Builtin.FPIEEE32)   // user: %37
  store %36 to %33 : $*Float                      // id: %37
  %38 = apply %31(%25, %33) : $@callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed τ_0_0) -> @out τ_0_1 for <Float, Float>
  strong_release %31 : $@callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed τ_0_0) -> @out τ_0_1 for <Float, Float> // id: %39
  dealloc_stack %33 : $*Float                     // id: %40
  dealloc_stack %26 : $*Float                     // id: %41
  dealloc_stack %25 : $*Float                     // id: %42
  // function_ref specialized consume<A>(_:)
  %43 = function_ref @$s7Example7consumeyyxlFSf_Tg5Tf4d_n : $@convention(thin) () -> () // user: %44
  %44 = apply %43() : $@convention(thin) () -> ()
  %45 = tuple ()                                  // user: %55
  %46 = differentiable_function_extract [original] %7 : $@differentiable @callee_guaranteed (Float) -> Float // user: %47
  strong_release %46 : $@callee_guaranteed (Float) -> Float // id: %47
  %48 = differentiable_function_extract [jvp] %7 : $@differentiable @callee_guaranteed (Float) -> Float // user: %49
  strong_release %48 : $@callee_guaranteed (Float) -> (Float, @owned @callee_guaranteed (Float) -> Float) // id: %49
  %50 = differentiable_function_extract [vjp] %7 : $@differentiable @callee_guaranteed (Float) -> Float // user: %51
  strong_release %50 : $@callee_guaranteed (Float) -> (Float, @owned @callee_guaranteed (Float) -> Float) // id: %51
  strong_release %11 : $@callee_guaranteed (@in_guaranteed Float) -> @out Float // id: %52
  strong_release %16 : $@callee_guaranteed (@in_guaranteed Float) -> (@out Float, @owned @callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed τ_0_0) -> @out τ_0_1 for <Float, Float>) // id: %53
  strong_release %20 : $@callee_guaranteed (@in_guaranteed Float) -> (@out Float, @owned @callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed τ_0_0) -> @out τ_0_1 for <Float, Float>) // id: %54
  return %45 : $()                                // id: %55
} // end sil function 'test_autodiff_gradient_apply'

// AD__foo__vjp_src_0_wrt_0
sil hidden @AD__foo__vjp_src_0_wrt_0 : $@convention(thin) (Float) -> (Float, @owned @callee_guaranteed (Float) -> Float) {
// %0                                             // users: %8, %8, %1
bb0(%0 : $Float):
  debug_value %0 : $Float, let, name "x", argno 1 // id: %1
  %2 = metatype $@thin Float.Type                 // users: %17, %8
  // function_ref static Float.* infix(_:_:)
  %3 = function_ref @$sSf1moiyS2f_SftFZ : $@convention(method) (Float, Float, @thin Float.Type) -> Float // user: %6
  // function_ref AD__$sSf1moiyS2f_SftFZ__jvp_src_0_wrt_0_1
  %4 = function_ref @AD__$sSf1moiyS2f_SftFZ__jvp_src_0_wrt_0_1 : $@convention(method) (Float, Float, @thin Float.Type) -> (Float, @owned @callee_guaranteed (Float, Float) -> Float) // user: %6
  // function_ref AD__$sSf1moiyS2f_SftFZ__vjp_src_0_wrt_0_1
  %5 = function_ref @AD__$sSf1moiyS2f_SftFZ__vjp_src_0_wrt_0_1 : $@convention(method) (Float, Float, @thin Float.Type) -> (Float, @owned @callee_guaranteed (Float) -> (Float, Float)) // user: %6
  %6 = differentiable_function [parameters 0 1] [results 0] %3 : $@convention(method) (Float, Float, @thin Float.Type) -> Float with_derivative {%4 : $@convention(method) (Float, Float, @thin Float.Type) -> (Float, @owned @callee_guaranteed (Float, Float) -> Float), %5 : $@convention(method) (Float, Float, @thin Float.Type) -> (Float, @owned @callee_guaranteed (Float) -> (Float, Float))} // user: %7
  %7 = differentiable_function_extract [vjp] %6 : $@differentiable @convention(method) (Float, Float, @noDerivative @thin Float.Type) -> Float // user: %8
  %8 = apply %7(%0, %0, %2) : $@convention(method) (Float, Float, @thin Float.Type) -> (Float, @owned @callee_guaranteed (Float) -> (Float, Float)) // users: %10, %9
  %9 = tuple_extract %8 : $(Float, @callee_guaranteed (Float) -> (Float, Float)), 0 // users: %11, %17, %17
  %10 = tuple_extract %8 : $(Float, @callee_guaranteed (Float) -> (Float, Float)), 1 // user: %21
  debug_value %9 : $Float, let, name "y"          // id: %11
  // function_ref static Float.+ infix(_:_:)
  %12 = function_ref @$sSf1poiyS2f_SftFZ : $@convention(method) (Float, Float, @thin Float.Type) -> Float // user: %15
  // function_ref AD__$sSf1poiyS2f_SftFZ__jvp_src_0_wrt_0_1
  %13 = function_ref @AD__$sSf1poiyS2f_SftFZ__jvp_src_0_wrt_0_1 : $@convention(method) (Float, Float, @thin Float.Type) -> (Float, @owned @callee_guaranteed (Float, Float) -> Float) // user: %15
  // function_ref AD__$sSf1poiyS2f_SftFZ__vjp_src_0_wrt_0_1
  %14 = function_ref @AD__$sSf1poiyS2f_SftFZ__vjp_src_0_wrt_0_1 : $@convention(method) (Float, Float, @thin Float.Type) -> (Float, @owned @callee_guaranteed (Float) -> (Float, Float)) // user: %15
  %15 = differentiable_function [parameters 0 1] [results 0] %12 : $@convention(method) (Float, Float, @thin Float.Type) -> Float with_derivative {%13 : $@convention(method) (Float, Float, @thin Float.Type) -> (Float, @owned @callee_guaranteed (Float, Float) -> Float), %14 : $@convention(method) (Float, Float, @thin Float.Type) -> (Float, @owned @callee_guaranteed (Float) -> (Float, Float))} // user: %16
  %16 = differentiable_function_extract [vjp] %15 : $@differentiable @convention(method) (Float, Float, @noDerivative @thin Float.Type) -> Float // user: %17
  %17 = apply %16(%9, %9, %2) : $@convention(method) (Float, Float, @thin Float.Type) -> (Float, @owned @callee_guaranteed (Float) -> (Float, Float)) // users: %19, %18
  %18 = tuple_extract %17 : $(Float, @callee_guaranteed (Float) -> (Float, Float)), 0 // users: %20, %24
  %19 = tuple_extract %17 : $(Float, @callee_guaranteed (Float) -> (Float, Float)), 1 // user: %21
  debug_value %18 : $Float, let, name "z"         // id: %20
  %21 = struct $_AD__foo_bb0__PB__src_0_wrt_0 (%10 : $@callee_guaranteed (Float) -> (Float, Float), %19 : $@callee_guaranteed (Float) -> (Float, Float)) // user: %23
  // function_ref AD__foo__pullback_src_0_wrt_0
  %22 = function_ref @AD__foo__pullback_src_0_wrt_0 : $@convention(thin) (Float, @owned _AD__foo_bb0__PB__src_0_wrt_0) -> Float // user: %23
  %23 = partial_apply [callee_guaranteed] %22(%21) : $@convention(thin) (Float, @owned _AD__foo_bb0__PB__src_0_wrt_0) -> Float // user: %24
  %24 = tuple (%18 : $Float, %23 : $@callee_guaranteed (Float) -> Float) // user: %25
  return %24 : $(Float, @callee_guaranteed (Float) -> Float) // id: %25
} // end sil function 'AD__foo__vjp_src_0_wrt_0'

// AD__foo__pullback_src_0_wrt_0
sil private @AD__foo__pullback_src_0_wrt_0 : $@convention(thin) (Float, @owned _AD__foo_bb0__PB__src_0_wrt_0) -> Float {
// %0                                             // user: %4
// %1                                             // users: %3, %2
bb0(%0 : $Float, %1 : $_AD__foo_bb0__PB__src_0_wrt_0):
  %2 = struct_extract %1 : $_AD__foo_bb0__PB__src_0_wrt_0, #_AD__foo_bb0__PB__src_0_wrt_0.pullback_0 // users: %13, %12
  %3 = struct_extract %1 : $_AD__foo_bb0__PB__src_0_wrt_0, #_AD__foo_bb0__PB__src_0_wrt_0.pullback_1 // users: %5, %4
  %4 = apply %3(%0) : $@callee_guaranteed (Float) -> (Float, Float) // users: %7, %6
  strong_release %3 : $@callee_guaranteed (Float) -> (Float, Float) // id: %5
  %6 = tuple_extract %4 : $(Float, Float), 0      // user: %8
  %7 = tuple_extract %4 : $(Float, Float), 1      // user: %9
  %8 = struct_extract %6 : $Float, #Float._value  // user: %10
  %9 = struct_extract %7 : $Float, #Float._value  // user: %10
  %10 = builtin "fadd_FPIEEE32"(%9 : $Builtin.FPIEEE32, %8 : $Builtin.FPIEEE32) : $Builtin.FPIEEE32 // user: %11
  %11 = struct $Float (%10 : $Builtin.FPIEEE32)   // user: %12
  %12 = apply %2(%11) : $@callee_guaranteed (Float) -> (Float, Float) // users: %15, %14
  strong_release %2 : $@callee_guaranteed (Float) -> (Float, Float) // id: %13
  %14 = tuple_extract %12 : $(Float, Float), 0    // user: %16
  %15 = tuple_extract %12 : $(Float, Float), 1    // user: %17
  %16 = struct_extract %14 : $Float, #Float._value // user: %18
  %17 = struct_extract %15 : $Float, #Float._value // user: %18
  %18 = builtin "fadd_FPIEEE32"(%17 : $Builtin.FPIEEE32, %16 : $Builtin.FPIEEE32) : $Builtin.FPIEEE32 // user: %19
  %19 = struct $Float (%18 : $Builtin.FPIEEE32)   // user: %20
  return %19 : $Float                             // id: %20
} // end sil function 'AD__foo__pullback_src_0_wrt_0'
```

This issue tracks improving optimizations for autodiff-generated SIL. Ideally, calls to APIs like `gradient` should get fully optimized away, with no pullback closure allocation overhead.

By comparison, manually written Swift code for `gradient` calls can get fully optimized away: [example project](https://github.com/dan-zheng/swift-apis/tree/autodiff-benchmark), [autodiff SIL](https://github.com/dan-zheng/swift-apis/blob/autodiff-benchmark/godbolt/Example.test_autodiff_gradient_apply.sil), [SIL for manual code](https://github.com/dan-zheng/swift-apis/blob/autodiff-benchmark/godbolt/Example.test_manual_gradient_apply.sil).

### PR DESCRIPTION
**Pull request by asl**
1. Simplify `differentiable_function_extract` of `differentiable_function`.
Before:
%x = differentiable_function(%orig, %jvp, %vjp)
%y = differentiable_function_extract [original] %x
After:
%y = %orig

2. Push conversion instructions inside of `differentiable_function`.
This unblocks inlining and specialization.
Before:
%x = differentiable_function(%orig, %jvp, %vjp)
%y = convert_escape_to_noescape %x
After:
%orig' = convert_escape_to_noescape %orig
%jvp' = convert_escape_to_noescape %jvp
%vjp' = convert_escape_to_noescape %vjp
%y = differentiable_function(%orig', %jvp', %vjp')

3. Another peephole is needed for reordering function conversion instructions to enable full inlining:
(convert_escape_to_noescape (convert_function (thin_to_thick_function x)))
=>
(convert_escape_to_noescape (thin_to_thick_function (convert_function x)))

Resolves #55830

Co-authored-by: Dan Zheng <danielzheng@google.com>

### CODE REVIEW

**Comment by asl** [comment]
@swift-ci please check

**Comment by asl** [comment]
@dan-zheng This is a refactored version of your peephole optimization patch. With some cleanup, fixing of FIXMEs, etc.

**Comment by dan-zheng** [comment]
Thanks for revisiting this!

My understanding of the context:
- https://github.com/apple/swift/issues/55830 tracks missing optimizations for autodiff SIL instructions, causing simple calls to `gradient(at:of:)` to suffer poor performance.
- My fix was almost done but tests (some non-AutoDiff SILOptimizer tests?) weren't all passing. Kudos if tests are passing now!
- [Here's a detailed Gist with notes.](https://gist.github.com/dan-zheng/e414e8d80357aa2b703580efe4ac18ac)

> Summary of optimizations:
> 
> ```
> // 1. Simplify `differentiable_function_extract` of `differentiable_function`.
> // Before:
> %x = differentiable_function(%orig, %jvp, %vjp)
> %y = differentiable_function_extract [original] %x
> // After:
> %y = %orig
> 
> // 2. Push conversion instructions inside of `differentiable_function`.
> // This unblocks inlining and specialization.
> // Before:
> %x = differentiable_function(%orig, %jvp, %vjp)
> %y = convert_escape_to_noescape %x
> // After:
> %orig' = convert_escape_to_noescape %orig
> %jvp' = convert_escape_to_noescape %jvp
> %vjp' = convert_escape_to_noescape %vjp
> %y = differentiable_function(%orig', %jvp', %vjp')
> 
> // 3. Another peephole is needed for reordering function conversion instructions to enable full inlining:
> (convert_escape_to_noescape (convert_function (thin_to_thick_function x)))
> =>
> (convert_escape_to_noescape (thin_to_thick_function (convert_function x)))
> ```

---

One consideration: are the peephole optimizations here only affecting autodiff-related SIL instructions?

I believe the answer is no, because we've added new `SILCombiner` visitors affecting non-autodiff SIL instructions, like `SILCombiner::visitConvertEscapeToNoEscapeInst`. With the current optimization implementation approach, these instruction visitors are necessary because we need to peer through intermediate function conversion instructions to fully statically resolve `differentiable_function` and `differentiable_function_extract`.

This has the potential to affect code generation quality for non-autodiff-related code, which is something to be careful about. You may want to add a SILOptimizer code owner (like @gottesmm) to take a look here.

I thought about different optimization implementation that avoid affecting non-autodiff SIL instructions. Those require more work than adding cases to `SILCombiner`. If we can be confident that this change does not add non-autodiff performance regressions, I think landing this PR is a great first step towards autodiff performance optimization.

**Comment by dan-zheng** [comment]
One small request: would you mind adding me as a co-author on the primary Git commit of this PR?

["Creating co-authored commits on GitHub"](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors#creating-co-authored-commits-on-github)

```
Co-authored-by: Dan Zheng <danielzheng@google.com>
```

I spent quite some time working on this, so some acknowledgement would be nice. Thanks :)

**Comment by dan-zheng** [comment]
It seems the CI invocation was spelled wrong, so I'll try triggering it again.

@swift-ci Please test

**Comment by asl** [comment]
@dan-zheng 

> One consideration: are the peephole optimizations here confirmed to only affect autodiff-related SIL instructions? (A quick check for this is running the SILOptimizer test suite.)

It looks like these patterns are quite specific to auto-diff code (which was some surprize to me). SILOptimizer tests are not affected at all. But certainly second pair of eye is always good here :)

> I thought about different optimization implementation that avoid affecting non-autodiff SIL instructions. Those require more work than adding cases to SILCombiner. 

I do not think we should move these to mandatory passes. After all, these are all optimizations, they are not required for correctness or for some preservation of semantics. So we'd rather fix the fallout, if any :)

**Comment by dan-zheng** [comment]
If other SILOptimizer tests are unaffected, great! Have you verified this by running the full test suite locally, with optimizations enabled?

**Comment by dan-zheng** [comment]
macOS and Linux CI failed early for some reason, possibly during update-checkout. I'll retrigger now.

@swift-ci Please test

**Comment by asl** [comment]
> If other SILOptimizer tests are unaffected, great! Have you verified this by running the full test suite locally, with optimizations enabled?

I have run whole testsuite, yes. However since I'm only having M1 Mac, I need to wait for CI results for x86-64-only or Linux-only checks :)

**Comment by asl** [comment]
> macOS and Linux CI failed early for some reason, possibly during update-checkout. I'll retrigger now.

Yes. Looks like docker images are unavailable... Let's see if it is something trancient.

**Comment by dan-zheng** [comment]
> One small request: would you mind adding me as a co-author on the primary Git commit of this PR?

Thanks for updating the PR description! I believe co-authorship attribution requires updating Git commits, as explained [here](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors#creating-co-authored-commits-on-github).

Could you please rebase and amend the commit message of the primary comment to contain the `Co-authored-by:` line, then force push? Successful co-authorship can be verified from the GitHub UI, both of our profile pictures will appear left of the commit.

**Comment by asl** [comment]
> > One small request: would you mind adding me as a co-author on the primary Git commit of this PR?
> 
> Thanks for updating the PR description! I believe co-authorship attribution requires updating Git commits, as explained [here](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors#creating-co-authored-commits-on-github).
> 
> Could you please rebase and amend the commit message of the primary comment to contain the `Co-authored-by:` line, then force push? Successful co-authorship can be verified from the GitHub UI, both of our profile pictures will appear left of the commit.

Yes, I will do after CI finishes. Just wanted not to distract it with multiple rebases :)

**Comment by asl** [comment]
@shahmishal Looks like the CI is unhappy (https://ci.swift.org/job/swift-PR-macos/3409/console) – can someone please take a look? Thanks!

**Comment by shahmishal** [comment]
@swift-ci Please test

**Comment by asl** [comment]
@dan-zheng Here we go: https://github.com/apple/swift/pull/60520/commits/3742583f13362aef32ba6dd1f69dd413f6fd3e8a

**Review by dan-zheng — APPROVED** [review]

**Comment by dan-zheng** [comment]
Looks good if non-autodiff programs do not have performance regressions due to this PR. Benchmarking is worthwhile to verify this.

@swift-ci Please benchmark

**Comment by dan-zheng** [comment]
@swift-ci Please test

**Comment by asl** [comment]
@swift-ci Please test

**Comment by asl** [comment]
@swift-ci Please benchmark

**Comment by asl** [comment]
@compnerd @gottesmm Will you be able to review this PR now? Or we'd simply handle any issues via post-commit review?

**Comment by asl** [comment]
@swift-ci Please test

**Comment by asl** [comment]
Let's address any further comments in post-commit review!

**Pull request merged**
