### PR TITLE
Revert "[Diag] Create frontend flags for localization and write tests

### PR DESCRIPTION
**Pull request by davezarzycki**
This reverts commit 621b3b4223f9bff2d7fa3a0435ada4e560b53072 (#32568).

The driver is double faulting on my Linux box (Fedora 32 / x86-64). It crashes due to heap corruption, then hangs trying to introspect and print the stack. There also appears to be an unrelated(?) uninitialized memory error that valgrind detects (as opposed to malloc's own self diagnostics).

CC: @HassanElDesouky

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test and merge

**Comment by HassanElDesouky** [comment]
I’m sorry for the crash. However, I can’t really understand what’s going on. Is there a particular part of my code that’s causing the issue?

**Comment by davezarzycki** [comment]
Not a problem. These things happen.

I haven't debugged it further. The test reliably crashes/hangs after #32568 and the crash/hang goes away after I revert #32568. It also seems specific to the driver and Valgrind is reporting a genuine bug in the driver, so I'd at least investigate and fix that first.

When you have a new pull request ready, please let me know and I can retest on my Linux box.

**Comment by HassanElDesouky** [comment]
Okay. I’ll need to check with @xedin on what should be done now. 

I’ll also mention you in the upcoming PR.

**Comment by xedin** [comment]
@davezarzycki Why are we reverting whole PR if there is a problem in a single test?

**Comment by davezarzycki** [comment]
1) The test was added in the PR and seemed core to the goals the PR.
2) Removing the test or hiding the bug by invoking the front end directly would have just buried the bug that was introduced/exposed by the PR.

**Comment by xedin** [comment]
@davezarzycki We could have XFAIL'ed a test and gave developer a moment to figure out what is going on and how to reproduce, we have run a whole suite and nothing failed so it shouldn't be blocking anybody from their work.

**Comment by guest10024** [comment]
Someone needs to fucking remove from this shit emails right now. Sick of
this junk shit

**Comment by davezarzycki** [comment]
> @davezarzycki We could have XFAIL'ed a test and gave developer a moment to figure out what is going on and how to reproduce, we have ran a whole suite and nothing failed so it shouldn't be blocking anybody from their work.

What would we XFAIL? Linux? Clearly it based on Ubuntu. Can we XFAIL just Fedora? If so, that's news to me. It's also news to me that this would have been the appropriate resolution. I thought we had an LLVM culture when it came to broken commits and reverting them, especially if the broken commit is recently committed. Is our revert/XFAIL culture documented somewhere?

I'm also not sure that I'd agree that this "shouldn't be blocking anybody from their work." This test is failing and causing my downstream auto-merger / CI some amount of indigestion. It's also breaking my workflow because I have to remove the test before running the test suite, otherwise it hangs for a long time until the test suite times out.

**Comment by xedin** [comment]
@davezarzycki Yes, we could have XFAIL'ed whole test via `// REQUIRES:` just like we always do. I'm not sure exactly what is documented but as far as I understand the agreements (/cc @shahmishal) we only revert like that if CI is broken and by "anybody" here I mean anybody contributing to the Swift repository, that's why previous commit, which failed on Windows, got reverted, because there was a clear indication what is going on.

**Comment by davezarzycki** [comment]
> @davezarzycki Yes, we could have XFAIL'ed whole test via `// REQUIRES:` just like we always do. I'm not sure exactly what is documented but as far as I understand the agreements (/cc @shahmishal) we only revert like that if CI is broken and by "anybody" here I mean anybody contributing to the Swift repository, that's why previous commit, which failed on Windows, got reverted, because there was a clear indication what is going on. 

Okay. I’ll try to remember to revert only if CI is broken. In any case, as I told @HassanElDesouky earlier, I’m happy to help him test a fix when it’s ready. I suspect that the PR’s driver changes just need to be run through some sanitizer like tools to find the bug.

**Comment by shahmishal** [comment]
Can we re-revert this change and mark the test `// REQUIRES: SR-XXXX` to disable this test on all platforms until it's fixed on Fedora? Also, we should file a bug report on bugs.swift.org.

**Comment by xedin** [comment]
@HassanElDesouky Is currently working on un-revert and changes, we'll see how it goes.

**Comment by davezarzycki** [comment]
Thanks. Due to the pandemic, I can only work ~6a to noon eastern time (then I watch my son), so I can’t undo the revert until tomorrow

**Comment by shahmishal** [comment]
No worries, thanks for helping with this @davezarzycki! 

@HassanElDesouky/@xedin Thanks for un-reverting!

**Pull request merged**
