### PR TITLE
Update WindowsBuild.md

### PR DESCRIPTION
**Pull request by martinboehme**
Added a note on which edition of Visual Studio to get.

### CODE REVIEW

**Comment by martinboehme** [comment]
@swift-ci Please smoke test

**Comment by compnerd** [comment]
I’m not sure if there’s value I’m mentioning that 2019 is the latest version.

**Review by compnerd — APPROVED** [review]
I think that the detail about the community version is fine, not so sure about the value of the vs2019 call out.

**Comment by martinboehme** [comment]
> I think that the detail about the community version is fine, not so sure about the value of the vs2019 call out.

Makes sense. I've removed the reference to VS 2019.

**Comment by martinboehme** [comment]
@swift-ci Please smoke test

**Comment by martinboehme** [comment]
@swift-ci Please smoke test

**Pull request merged**
