### PR TITLE
cmake: add the swiftCompilerModules stub to the exported targets

### PR DESCRIPTION
**Pull request by eeckstein**

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by eeckstein** [comment]
@swift-ci smoke test linux

**Comment by compnerd** [comment]
This unfortunately doesn't seem to work:
```
CMake Error at cmake/modules/CMakeLists.txt:10 (export):
  export given ALIAS target "swiftCompilerModules" which may not be exported.
```
https://ci-external.swift.org/job/swift-PR-windows/19535/console

**Comment by eeckstein** [comment]
@compnerd you are right, this does not work.
The swiftCompilerStub is already exported. We can create the alias on the lldb side: https://github.com/apple/llvm-project/pull/3737

**Pull request closed without merging**
