### PR TITLE
update-checkout: Do not update repository if not listed in the given branch-scheme

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
Consider two branch-schemes, where the second is a subset of the first. Suppose repositories have been cloned using the first branch scheme. Previously, a successive update using the second branch-scheme would cause update-checkout to fail in an attempt to query the branch-scheme about the target branch for a repository it does not map, even though the update, given no further errors, can be considered successful.

### CODE REVIEW

**Comment by AnthonyLatsis** [comment]
@swift-ci please Python lint

**Comment by AnthonyLatsis** [comment]
@gottesmm ping

**Comment by AnthonyLatsis** [comment]
@shahmishal ping

**Review by gottesmm — APPROVED** [review]
LGTM. Thanks for adding a test!

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Comment by AnthonyLatsis** [comment]
Thanks for reviewing!

**Pull request merged**
