### PR TITLE
[cmake] Refactor: Update CMakeLists.txt

### PR DESCRIPTION
**Pull request by cpiaseque**
Little CmakeLists.txt  refactoring.

### CODE REVIEW

**Comment by compnerd** [comment]
This just adds some whitespace, I'm not sure that there is much gained from this change. CC: @etcwilde

**Comment by kirillpyasecky** [comment]
> This just adds some whitespace, I'm not sure that there is much gained from this change. CC: @etcwilde

refactor always is a small change, but improves readability.

**Comment by compnerd** [comment]
I agree that they can be small changes, but I don't think that this is improving readability. We have plenty of cases of the dense CMakeLists, and in general do have dense C++ (as per the LLVM style). This just adds whitespace to one location which also diverges from the overall style of the project.

**Comment by kirillpyasecky** [comment]
I agree that there is plenty of cases of the dense CMakeLists, but in this case my idea was in separeting blocks, which is also often used in many projects.

**Comment by compnerd** [comment]
Sure, other projects do use the less dense form and liberally add newlines. I don't think that we generally do that in this project.

**Comment by kirillpyasecky** [comment]
See [this](https://github.com/swiftlang/swift/blob/main/cmake/modules/CMakeLists.txt) for example. You are also using blocks style.

**Comment by etcwilde** [comment]
We don't really have a hard rule for style in the CMake. @compnerd and I will usually comment on stylistic improvements if we see them in PRs that are changing the code, but without an actual formatting guide and verification in place to ensure that we're adhering to those rules, I'm reluctant to accept a change that is solely adding newlines for an arbitrary style change. If you find a bug in that region of the script and you added a newline there, then I would be fine with that.

**Comment by kirillpyasecky** [comment]
My idea was not a global change in the style of the project, but a small improvement. To be honest, I didn’t think that such a change could raise questions and doubts, because, in my opinion, it is quite intuitive.

**Comment by kirillpyasecky** [comment]
Ping

**Comment by AnthonyLatsis** [comment]
People obviously have different opinions on good style and taste. In fact, I prefer an empty line here too. I think the point Evan is making is that a small improvement is not going to be useful unless we all acknowledge that it is an objective improvement and devise a way to keep that improvement in place. Otherwise, this is just one person cleaning up what they think is inferior formatting style after another person, in an already and still inconsistently formatted code base, which does not sound like a wholesome activity. Improvement or not, reformatting code in such small volumes is also going to pollute the commit history.

**Pull request closed without merging**
