### PR TITLE
Sourcekit cmake changes

### PR DESCRIPTION
**Pull request by erg**
Changes to help SourceKit build correctly.

### CODE REVIEW

**Comment by erg** [comment]
@swift-ci Please test Linux platform

**Comment by erg** [comment]
@swift-ci Please test

**Comment by karwa** [comment]
@erg can you explain why we can't install the native tools when cross-compiling? I use that feature.

**Comment by erg** [comment]
@karwa I'm looking into it.

**Comment by karwa** [comment]
Just "regular" cross-compiling for armv7/linux from macOS. I've got a script which builds packages for both platforms in one invocation.

Everything is already built (for all platforms) before we install for any platform, so it's weird if anything fails because of the host products being installed.

**Pull request merged**
