### PR TITLE
[Foundation][gardening] Remove unnecessary `break`s

### PR DESCRIPTION
**Pull request by ikesyo**
This is the same as https://github.com/apple/swift-corelibs-foundation/pull/780. /cc @parkera

### CODE REVIEW

**Comment by parkera** [comment]
Thanks!

**Comment by parkera** [comment]
@swift-ci please test and merge

**Comment by CodaFi** [comment]
This fell victim to the playground logger failure

@swift-ci please smoke test OS X platform.

**Comment by CodaFi** [comment]
Merging manually.  Playground failures were fixed.

**Comment by ikesyo** [comment]
Thanks!

**Pull request merged**
