### PR TITLE
Fix IRGen and tests to use musttail/swiftasync correctly

### PR DESCRIPTION
**Pull request by varungandhi-apple**

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
@swift-ci smoke test

**Comment by varungandhi-apple** [comment]
@swift-ci smoke test Linux

**Review by aschwaighofer — APPROVED** [review]
LGTM

**Comment by varungandhi-apple** [comment]
@swift-ci clean smoke test Linux

**Comment by varungandhi-apple** [comment]
@swift-ci smoke test Linux

**Comment by benrimmington** [comment]
@varungandhi-apple This test is failing on [watchsimulator-i386][] and [windows-x86_64][].

```
IRGen/async/run-call-dynamic-void_to_void.swift:20:14: error: CHECK-LL: expected string not found in input
// CHECK-LL: musttail call swifttailcc void
             ^
```

[watchsimulator-i386]: <https://ci.swift.org/job/swift-PR-macos/26412/>
[windows-x86_64]: <https://ci-external.swift.org/job/swift-PR-windows/12458/>

**Comment by varungandhi-apple** [comment]
@benrimmington, the watch simulator case should be fixed with this LLVM change. https://github.com/apple/llvm-project/pull/2768 (the automerger needs to get through)

I can fix it for Windows.

**Comment by varungandhi-apple** [comment]
https://github.com/apple/swift/pull/36720

**Comment by benrimmington** [comment]
apple/llvm-project#2768 has been reverted in apple/llvm-project#2786

**Pull request merged**
