### PR TITLE
stdlib: Build with -requirement-machine-inferred-signatures=verify

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
https://github.com/apple/swift-experimental-string-processing/pull/199
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
https://github.com/apple/swift-experimental-string-processing/pull/214
@swift-ci Please smoke test

**Comment by rxwei** [comment]
I think this will build StringProcessing successfully but will fail some tests in test/StringProcessing likely due to parser changes. We are investigating this.

**Comment by rxwei** [comment]
@swift-ci please smoke test macOS

**Comment by slavapestov** [comment]
@swift-ci please smoke test macOS

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Comment by slavapestov** [comment]
https://github.com/apple/swift-experimental-string-processing/pull/214
@swift-ci Please smoke test

**Pull request merged**
