### PR TITLE
[TypeChecker] Simplify for ... in ... type checking

### PR DESCRIPTION
**Pull request by xedin**
Based on https://github.com/apple/swift/pull/21811 with diagnostic improvements.

### CODE REVIEW

**Comment by xedin** [comment]
@slavapestov I have rebased your changes with the latest master and fixed diagnostic, if you want you can cherry-pick my commit to your original PR too.

**Comment by slavapestov** [comment]
Thanks! I think the first two commits (simplify Optional/pointer conversions) were bogus. Let’s drop them for now

**Comment by xedin** [comment]
@slavapestov Will do!

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please smoke test compiler performance

**Review by slavapestov — APPROVED** [review]

**Pull request merged**
