### PR TITLE
[IRGen] Don't emit multiple copies of coverage maps

### PR DESCRIPTION
**Pull request by hamishknight**
Iterating over the IRGenModules and emitting every SILCoverageMap in the SILModule meant that we were emitting N copies of the coverage maps for parallel IRGen, where N is the number of output object files.

This has always been wrong, but was previously saved by the fact that we would drop the coverage map on the floor if we didn't have the name data available. This meant we would only emit for the IRGenModule that had emitted the entity to profile, in addition to any IRGenModules that had inlined the body of a profiled entity. As such, this prevented the duplication from being too egregious. However with the recent change to emit unused name data in the case where we don't already have name data available (#61158), we're now fully duplicating every coverage mapping, and emitting a ton of redundant name data.

Fix things such that we only emit coverage mapping records for the IRGenModule that corresponds to the entity being profiled.

rdar://102905496

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
@swift-ci please build toolchain

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
@swift-ci please build toolchain

**Review by aschwaighofer — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
