### PR TITLE
[crashers] Add license header: Apache License v2.0 with Runtime Library Exception

### PR DESCRIPTION
**Pull request by practicalswift**
#### What's in this pull request?

This is a follow-up to PR #1649.

Add license header: Apache License v2.0 with Runtime Library Exception.

Approvals given in #1649.
#### Resolved bug number: –

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by tkremenek** [comment]
Is there a reason to put the reference to Apache 2 in every test file?  The idea is that **all** the sources in the repository are under the Apache 2 license.  It doesn't seem like an explicit reference to Apache 2 is needed, but just the standard preamble that appears in the majority of source files in the repository:

```
// This source file is part of the Swift.org open source project
// See http://swift.org/LICENSE.txt for license information
```

This also seems more maintainable in case there are ever any refinements/changes to the license.  In such case, we only need to change `LICENSE.txt`, not every single file.

**Comment by MatejLach** [comment]
I agree with @tkremenek that this seems like a better way to do it. 
Looking at other languages here on github, this is how Julia does it and they seem to be fine. 

On the other hand, Rust specifies in every file which license they use, (like swift does now), and they also use Apache 2, but I don't think that is a requirement of the license so I'll just go with the Julia approach if possible.

**Comment by lattner** [comment]
Agreed, please keep with the canonical file header, that way we have consistency across the source base (it is also what lawyers have reviewed and approved).

**Comment by practicalswift** [comment]
@tkremenek @MatejLach @lattner Good points. I've now updated this PR. Looks good now? :-)

**Comment by lattner** [comment]
Please include the full header:

// This source file is part of the Swift.org open source project
//
// Copyright (c) 2014 - 2016 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See http://swift.org/LICENSE.txt for license information
// See http://swift.org/CONTRIBUTORS.txt for the list of Swift project authors

Thanks!

**Comment by practicalswift** [comment]
@lattner Updated - looks good now? :-)

**Comment by lattner** [comment]
Looks great! Thank you!

**Pull request merged**
