### PR TITLE
AST: Start returning SelfProtocolConformances from ModuleDecl::lookupConformance()

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes <rdar://problem/49241923>, <https://bugs.swift.org/browse/SR-10015>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
CoreStore failed to build but it's extremely unlikely it was my change:

```
In file included from /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/CoreStore/Sources/CoreStoreBridge.m:29:
/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/CoreStore/build/Build/Products/Debug-iphoneos/CoreStore.framework/Headers/CoreStore-Swift.h:3422:158: warning: missing terminating '"' character [-Winvalid-pp-token]
- (nonnull instancetype)initWithModel:(NSManagedObjectModel * _Nonnull)model versionChain:(NSArray<NSString *> * _Nullable)versionChain SWIFT_DEPRECATED_MSG("Use the -[initWit
                                                                                                                                                             ^
/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/CoreStore/build/Build/Products/Debug-iphoneos/CoreStore.framework/Headers/CoreStore-Swift.h:1:2: error: unterminated conditional directive
#if 0
 ^
/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/CoreStore/Sources/CoreStoreBridge.m:32:2: error: embedding a #pragma directive within macro arguments is not supported

#pragma mark - Clauses
 ^
```

**Review by rjmccall — COMMENTED** [review]
LGTM.  As I mentioned elsewhere, there's an invariant that the conforming type of a conformance should match the corresponding type in whatever substitution it appears in, so we should generalize `SelfProtocolConformance` so that it can apply to protocol compositions and/or base protocols, but otherwise this is the right basic approach.

Is there any way we can verify that abstract `ProtocolConformanceRef`s are only being used for archetypes and similar constructs?

**Pull request merged**
