### PR TITLE
[IRGen] Respect optionality of unowned(unsafe) reference properties

### PR DESCRIPTION
**Pull request by drexin**
rdar://108705703

When generating the type info for fields marked unowned(unsafe) of an optional reference (e.g. AnyObject?), we dropped the fact that it was optional along the way. This caused incorrect tags to be returned when on object of the type was stored in an optional itself and the unowned property contained `nil`. In those cases the outer optional appeared to be `nil` as well, even if it in fact contained a value.

### CODE REVIEW

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
Hm, I tested with a simplified test case and while it fixes that one, it does not seem to fix the original issue. Looking further into it.

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@aschwaighofer Fixed the other case as well. Ready for review.

**Review by aschwaighofer — APPROVED** [review]
great find!

**Comment by drexin** [comment]
@swift-ci smoke test macos

**Pull request merged**
