### PR TITLE
Disable the _StringProcessing import in the Observation module

### PR DESCRIPTION
**Pull request by DougGregor**
Fixes rdar://106374161

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Review by phausler — APPROVED** [review]
looks correct to me

**Comment by Azoy** [comment]
`add_swift_target_library` should be doing this automatically. If it's not then something changed to enable it.

**Comment by Azoy** [comment]
I just `otool -L libswiftObservation.dylib` and string processing is not a listed link dependency.

**Comment by DougGregor** [comment]
I'm fine with doing this all the time for `add_swift_target_library`. We can't do it for host libraries, because those need to be able to build with compilers that predate this flag.

**Pull request merged**
