### PR TITLE
 [AutoDiff] forbid derivative registration using @differentiable

### PR DESCRIPTION
**Pull request by marcrasi**
This is the `tensorflow` branch PR corresponding to https://github.com/apple/swift/pull/30001. Repeating the description:

Forbids the `jvp:` and `vjp:` arguments to `@differentiable`, deletes all the logic that handles them, and updates tests to use `@derivative(of:)` instead.

I left an error message saying that `jvp:` and `vjp:` are deprecated, so that there is a good explanation for anyone who missed the deprecation warning and whose code stops working. I think we should wait until next release to remove this.

I am running all the swift-apis, swift-models, swift-jupyter, swiftai, etc tests on this to catch any leftover `jvp:` or `vjp:` that we forgot to remove.

### CODE REVIEW

**Review by rxwei — APPROVED** [review]

**Review by dan-zheng — APPROVED** [review]

**Comment by dan-zheng** [comment]
I accidentally deleted `tensorflow` branch, which closed this PR. That was not intentional, sorry!
It would be nice to protect `tensorflow` branch against deletion to prevent this from happening again.

**Comment by marcrasi** [comment]
Test run caught some 'vjp:' in OpenSpiel! I'll fix that before proceeding with merging this PR.

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Comment by marcrasi** [comment]
This seems good to go now, but I'll wait until we have caught up with the master->tensorflow merge so that I don't further pile on conflicts.

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Comment by dan-zheng** [comment]
Merging now that upstream mirror #30001 has been merged.

**Pull request merged**
