### PR TITLE
Cherry-pick compiler performance fixes [5.4]

### PR DESCRIPTION
**Pull request by slavapestov**
(Mostly, see below) fixes <rdar://problem/72906325>.

```
Build times with 5.3 vs 5.4 vs this PR, building the 5.3 SwiftSyntax:

5.3:

spestov@technical-debt swift % sh perf-wmo-53.sh

real	0m42.825s
user	0m40.623s
sys	0m2.188s

spestov@technical-debt swift % sh perf-batch-53.sh

real	0m7.480s
user	0m35.239s
sys	0m6.752s

5.4:

spestov@technical-debt swift % sh perf-wmo-54.sh

real	0m46.477s
user	0m43.617s
sys	0m2.848s

spestov@technical-debt swift % sh perf-batch-54.sh

real	0m13.842s
user	0m53.109s
sys	0m8.135s

5.4 + this PR:

spestov@technical-debt swift % sh perf-wmo.sh

real	0m42.689s
user	0m40.464s
sys	0m2.214s

spestov@technical-debt swift % sh perf-batch.sh

real	0m7.994s
user	0m40.993s
sys	0m7.059s
```

You can see there’s still a small regression in batch mode. This is due to two issues which need to be addressed separately:

- The use of MD5 for the interface hash, which is now computed in more instances.
- A Clang regression that manifests via IRGen.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Review by DougGregor — APPROVED** [review]

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by slavapestov** [comment]
@swift-ci please test Linux

**Comment by slavapestov** [comment]
@swift-ci Please test macOS

**Pull request merged**
