### PR TITLE
fixed urls for cloning repositories

### PR DESCRIPTION
**Pull request by AndreasPrang**

### CODE REVIEW

**Comment by oblitum** [comment]
Isn't the current setting correct, I've cloned without problems and have never seen slash as user separator in git urls.

**Comment by krememek** [comment]
These URLs were recently changed (today) in 5ba5baf11db43a4bf70e35de378a16aced4e0f5b:

Author: Steve Klabnik <steve@steveklabnik.com>
Date:   Thu Dec 3 12:23:31 2015 -0500

    Remove extra / in git commands in README

    This works, but is usually not how it's written. A command later in the
    README was already using this style.

These URLs clone just fine.  Is there an actual problem with them?

**Comment by AndreasPrang** [comment]
It wasn't working for me. What should be the ":apple" string be for? 
@krememek: In 5ba5baf the changes has been false. 

github.com:/apple was correct. 
github.com:apple is an invalide URL.

<domain>:/path is optional for <domain>:80/path

**Comment by mxcl** [comment]
We should use the `https` URLs since they don’t require an entire SSH keychain to be setup on user computers.

**Comment by oblitum** [comment]
Agree with @mxcl, it's the easier route in any case, although the current git urls look fine.

**Comment by AndreasPrang** [comment]
@mxcl I added this in Pullrequest  #82

**Comment by oblitum** [comment]
@AndreasPrang for sake of information, you could have amended this one already instead (adding a new commit on top or just force commiting).

**Comment by jsjohnst** [comment]
@AndreasPrang your version certainly doesn't work, what was there does...

```
$  git clone git@github.com/apple/swift.git swift
fatal: repository 'git@github.com/apple/swift.git' does not exist
$  git clone git@github.com:apple/swift.git swift
Cloning into 'swift'...
remote: Counting objects: 290256, done.
remote: Total 290256 (delta 0), reused 0 (delta 0), pack-reused 290256
Receiving objects: 100% (290256/290256), 55.79 MiB | 13.13 MiB/s, done.
Resolving deltas: 100% (237379/237379), done.
Checking connectivity... done.
Checking out files: 100% (9387/9387), done.
```

**Comment by noamtamim** [comment]
@AndreasPrang @jsjohnst Don't work so hard; just take a look at GitHub's clone URL for this repo:
```
HTTPS: https://github.com/apple/swift.git
SSH:       git@github.com:apple/swift.git
```
That colon between github.com and apple is what you always use with ssh URLs, like with scp/rsync.

Also note that HTTPS is the method recommended by GitHub.

**Comment by jsjohnst** [comment]
@noamtamim I know how to use Git, so didn't need to work hard deciphering docs. I'm linking @AndreasPrang so he can learn the proper way and not make borked pull requests on highly viewed repos.

**Comment by yurikoles** [comment]
@AndreasPrang please cancel this PR, since it's wrong and a total waste of time.

**Pull request closed without merging**
