### PR TITLE
Remove "REQUIRES: deterministic-behavior" from crashers that are now deterministic

### PR DESCRIPTION
**Pull request by practicalswift**

### CODE REVIEW

**Comment by practicalswift** [comment]
@swift-ci please smoke test and merge

**Comment by practicalswift** [comment]
@swift-ci please test and merge

**Comment by practicalswift** [comment]
@swift-ci please smoke test and merge

**Comment by practicalswift** [comment]
@swift-ci please test and merge

**Comment by rudkx** [comment]
@practicalswift 28555-* is failing in PR testing. I need to revert this to get PR testing working consistently again.

**Pull request merged**
