### PR TITLE
[test] Fix Int128 test on 32-bit platforms

### PR DESCRIPTION
**Pull request by kateinoigakukun**
The test used Int.min and Int.max assuming that they are 64-bit integers. Use 64-bit integers explicitly instead.
The test failed on WebAssembly CI: https://ci.swift.org/job/oss-swift-pr-test-crosscompile-wasm-ubuntu-20_04/359/console

<details>
<pre>
/home/build-user/build/buildbot_linux/wasmstdlib-linux-x86_64/test-wasi-wasm32/stdlib/Output/Int128.swift.tmp/a.out
[ RUN      ] Int128Tests.Memory layout
[       OK ] Int128Tests.Memory layout
[ RUN      ] Int128Tests.Literals
[       OK ] Int128Tests.Literals
[ RUN      ] Int128Tests.Conversion from Double
[       OK ] Int128Tests.Conversion from Double
[ RUN      ] Int128Tests.Conversion from Float
[       OK ] Int128Tests.Conversion from Float
[ RUN      ] Int128Tests.Conversion from Float16
[       OK ] Int128Tests.Conversion from Float16
[ RUN      ] Int128Tests.Conversion from integers
check failed at /home/build-user/swift/test/stdlib/Int128.swift, line 313
first:  -2147483648 (of type Swift.Int128)
second: -9223372036854775808 (of type Swift.Int128)
check failed at /home/build-user/swift/test/stdlib/Int128.swift, line 314
first:  2147483647 (of type Swift.Int128)
second: 9223372036854775807 (of type Swift.Int128)
check failed at /home/build-user/swift/test/stdlib/Int128.swift, line 315
first:  4294967295 (of type Swift.Int128)
second: 18446744073709551615 (of type Swift.Int128)
check failed at /home/build-user/swift/test/stdlib/Int128.swift, line 321
first:  Optional(-2147483648) (of type Swift.Optional<Swift.Int128>)
second: Optional(-9223372036854775808) (of type Swift.Optional<Swift.Int128>)
check failed at /home/build-user/swift/test/stdlib/Int128.swift, line 322
first:  Optional(2147483647) (of type Swift.Optional<Swift.Int128>)
second: Optional(9223372036854775807) (of type Swift.Optional<Swift.Int128>)
check failed at /home/build-user/swift/test/stdlib/Int128.swift, line 323
first:  Optional(4294967295) (of type Swift.Optional<Swift.Int128>)
second: Optional(18446744073709551615) (of type Swift.Optional<Swift.Int128>)
check failed at /home/build-user/swift/test/stdlib/Int128.swift, line 329
first:  -2147483648 (of type Swift.Int128)
second: -9223372036854775808 (of type Swift.Int128)
check failed at /home/build-user/swift/test/stdlib/Int128.swift, line 330
first:  2147483647 (of type Swift.Int128)
second: 9223372036854775807 (of type Swift.Int128)
check failed at /home/build-user/swift/test/stdlib/Int128.swift, line 331
first:  4294967295 (of type Swift.Int128)
second: 18446744073709551615 (of type Swift.Int128)
check failed at /home/build-user/swift/test/stdlib/Int128.swift, line 337
first:  340282366920938463463374607429620727808 (of type Swift.UInt128)
second: 340282366920938463454151235394913435648 (of type Swift.UInt128)
check failed at /home/build-user/swift/test/stdlib/Int128.swift, line 338
first:  2147483647 (of type Swift.UInt128)
second: 9223372036854775807 (of type Swift.UInt128)
check failed at /home/build-user/swift/test/stdlib/Int128.swift, line 339
first:  4294967295 (of type Swift.UInt128)
second: 18446744073709551615 (of type Swift.UInt128)
check failed at /home/build-user/swift/test/stdlib/Int128.swift, line 346
first:  Optional(2147483647) (of type Swift.Optional<Swift.UInt128>)
second: Optional(9223372036854775807) (of type Swift.Optional<Swift.UInt128>)
check failed at /home/build-user/swift/test/stdlib/Int128.swift, line 347
first:  Optional(4294967295) (of type Swift.Optional<Swift.UInt128>)
second: Optional(18446744073709551615) (of type Swift.Optional<Swift.UInt128>)
check failed at /home/build-user/swift/test/stdlib/Int128.swift, line 354
first:  2147483647 (of type Swift.UInt128)
second: 9223372036854775807 (of type Swift.UInt128)
check failed at /home/build-user/swift/test/stdlib/Int128.swift, line 355
first:  4294967295 (of type Swift.UInt128)
second: 18446744073709551615 (of type Swift.UInt128)
[     FAIL ] Int128Tests.Conversion from integers
[ RUN      ] Int128Tests.Bytes and words
[       OK ] Int128Tests.Bytes and words
[ RUN      ] Int128Tests.Bitwise operations
[       OK ] Int128Tests.Bitwise operations
[ RUN      ] Int128Tests.Addition and subtraction
[       OK ] Int128Tests.Addition and subtraction
[ RUN      ] Int128Tests.Wide multiplication and division
[       OK ] Int128Tests.Wide multiplication and division
[ RUN      ] Int128Tests.Narrow multiplication and division
[       OK ] Int128Tests.Narrow multiplication and division
[ RUN      ] Int128Tests.String roundtrip
[       OK ] Int128Tests.String roundtrip
Int128Tests: Some tests failed, aborting
UXPASS: []
FAIL: ["Conversion from integers"]
SKIP: []
</pre>
</details>

### CODE REVIEW

**Comment by kateinoigakukun** [comment]
@swift-ci test WebAssembly

**Comment by kateinoigakukun** [comment]
@swift-ci smoke test

**Comment by kateinoigakukun** [comment]
The Linux CI failure on `TestSwiftExprMissingType.py` seems happening on main too

**Review by stephentyrone — APPROVED** [review]

**Comment by kateinoigakukun** [comment]
@swift-ci smoke test

**Comment by kateinoigakukun** [comment]
@swift-ci smoke test Windows

**Pull request merged**
