### PR TITLE
test: use llvm tools

### PR DESCRIPTION
**Pull request by compnerd**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

Rather than relying on the system to provide ar and nm, use the LLVM equivalent
tools instead.  Since the build is already dependent on llvm and its tools, this
just ensures that the full set is self-contained.  NFC.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @gribozavr

**Comment by gribozavr** [comment]
How would this play with cross-compiling?  Do LLVM tools work with Mach-O, ELF and PE equally well on all host platforms?

I agree that the test is not written in a portable way, but usually we'd replace direct calls with substitutions that invoke platform-specific tools for the current target.  (e.g., `%target-clang`)

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by compnerd** [comment]
I actually thought about doing the substitutions.  However, the llvm tools support Mach-O, ELF, and PE/COFF equally well on all the hosts (LLVM tests all the formats on Windows and Linux, and I definitely run tests on OS X), so this seems nicer.  It also means that its easier to extend the support if/when needed.

**Comment by gribozavr** [comment]
OK, let's use LLVM tools then.

**Pull request merged**
