### PR TITLE
[Testing] Minimize merge conflicts in IDE/complete_decl_attribute.swift

### PR DESCRIPTION
**Pull request by davezarzycki**

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by davezarzycki** [comment]
@swift-ci please smoke test linux

**Comment by davezarzycki** [comment]
@swift-ci please smoke test macos

**Review by dan-zheng — APPROVED** [review]
Nice!

**Comment by davezarzycki** [comment]
@swift-ci please smoke test linux

**Comment by davezarzycki** [comment]
@swift-ci please smoke test macos

**Pull request merged**
