### PR TITLE
[Property wrappers] Fix crash due to wrapped type/wrapper type confusion

### PR DESCRIPTION
**Pull request by DougGregor**
We had two predicates that were used to determine whether the default
argument for a wrapped property in the memberwise initializer would be
of the wrapper type (e.g., `Lazy<Int>`) vs. the wrapped type
(`Int`). Those two predicates could disagree, causing a SILGen assertion
and crash. Collapse the two predicates into one correct one,
fixing rdar://problem/57545381.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Review by hborla — APPROVED** [review]

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Pull request merged**
