### PR TITLE
Update branches for new master-next scheme.

### PR DESCRIPTION
**Pull request by bob-wilson**

### CODE REVIEW

**Comment by bob-wilson** [comment]
@gottesmm Can you review this?

**Comment by gottesmm** [comment]
LGTM! I would just talk with Mishal about removing the preview branches. @shahmishal How does that part look to you?

**Comment by gottesmm** [comment]
@swift-ci Please smoke test

**Comment by bob-wilson** [comment]
Thanks. (The smoke tests don't exercise this script, do they?)

**Comment by gottesmm** [comment]
@bob-wilson While they do not exercise this specific scheme, they will make sure that normal usage still works [which is what I was trying to test = )]

**Pull request merged**
