### PR TITLE
Sema: Use the correct source range when emitting fixits for unresolved member expressions

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes <rdar://problem/34421732>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by xedin** [comment]
Thanks!

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Pull request merged**
