### PR TITLE
[CodeCompletion] Do not include decl in own (string interp) initializer

### PR DESCRIPTION
**Pull request by bnbarham**
Strings are a single token, so the previous check would treat
completions inside string interpolations as being outside of the
initializer.

Grab the end of the token from the Lexer, but wrap in a context check to
avoid performing that for every declaration found in the lookup.

Resolves rdar://70833348

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
Just noticed I had left the types of the added tests as Int rather than String. Shouldn't matter but do you want me to fix that?

**Review by rintaro — COMMENTED** [review]
The context type shouldn't matter. So I'm OK with it.

But,
```swift
func foo(arg: Int = #^HERE^#) {}
```
I just noticed this suggests `arg` in Swift5.3, which is not OK. Does this (or your recent) change resolve it too? Could you add test cases for them?

**Comment by bnbarham** [comment]
> The context type shouldn't matter. So I'm OK with it.
> 
> But,
> 
> ```swift
> func foo(arg: Int = #^HERE^#) {}
> ```
> 
> I just noticed this suggests `arg` in Swift5.3, which is not OK. Does this (or your recent) change resolve it too? Could you add test cases for them?

The previous one should fix that case, but I can add it in this one. May as well fix the type while I'm at it as well. Thanks :)

**Comment by bnbarham** [comment]
Previous did not fix... it was only checking the initializer, not for a default argument. Added another commit to fix that one as well. Also enabled some disabled tests that should work now (have for a while I think).

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
@swift-ci please test Linux platform

**Review by rintaro — APPROVED** [review]
Thank you!

**Pull request merged**
