### PR TITLE
Fix debug scope verification.

### PR DESCRIPTION
**Pull request by dan-zheng**
Debug scope verification was enabled by default in https://github.com/apple/swift/commit/f917c9355764dc6d9308ccf2801776c62e032612.

This caused verification errors as a result of deabstraction inlining.
It's stated that `verifyDebugScopeHoles` should not be run when inlining is performed because scopes are moved around.

A simple patch is to relax debug scope verification so that only instructions with no inlined call site are checked.

Addresses [SR-8114](https://bugs.swift.org/browse/SR-8114).
Currently, since debug scope verification is enabled, any `Tensor` program compiled with `-Onone` fails verification.

### CODE REVIEW

**Comment by dan-zheng** [comment]
This isn't a robust fix, setting optimization mode to `-O` for a SILFunction has other implications when the global opt mode is `-Onone`.

@lattner: do you have ideas on a more robust fix? The condition for verifying debug scope holes should really be something like: `if (fn.isInlined() || fn.containsInlinedFunctionCalls())`.

**Comment by rxwei** [comment]
Does it accidentally fix debug scope inlining stack trace?

**Comment by dan-zheng** [comment]
@rxwei Are you asking if this patch fixes the debug scope inlining stack trace issue in [TFLowerGraph.cpp](https://github.com/apple/swift/blob/95f56d7f725f1f8487a7721e39d9eaced36f568b/lib/SILOptimizer/Mandatory/TFLowerGraph.cpp#L583)?
```c++
// Bug: `ds->InlinedCallSite` is always nullptr.
for (auto ds = loc.getScope(); ds; ds = ds->InlinedCallSite) { ... }
```
This patch doesn't fix that (it only bypasses debug scope verification for functions inlined by deabstraction), but I'm looking into that bug also.

**Comment by dan-zheng** [comment]
Curious if all tests pass.
@swift-ci Please test tensorflow

**Comment by rxwei** [comment]
I mean, originally the inlining trace wasn’t recorded possibly because optimization mode wasn’t set to ForSpeed at some point during compilation. This might have fixed that.

**Comment by mhong** [comment]
my understanding is that once we move partition pass to be right after deabstraction pass, we can compile model files without -O. In that case, internally forcing "-O" is probably not the right call.

As a short-term fix, do we want to turn off "-verify-di-holes", whenever we've run the deasbtraction pass that has inlined stuff?

**Comment by rxwei** [comment]
OTOH, what do you think of my suggesion on the jira issue? Making the compiler cleverly reject -Onone, or make ‘import TensorFlow’ imply ‘-O’ is probably a good thing until we have deabstraction. Gets rid of unnecessary user questions.

**Comment by dan-zheng** [comment]
I like the idea of making `import TensorFlow` imply `-O` until `-O` is no longer necessary.

**Comment by lattner** [comment]
Great detective work tracking this down, thank you!   Have you asked @adrian-prantl or one of the other folks working on debug scopes what the preferred fix is here?

Adrian, to summarize, the issue is that we need to do some amount of inlining even at -O0 as part of our deabstraction transformation for tensorflow.  We use "performance" inlining because we want source locations to track information about what got inlined so we can produce nice user diagnostics.  The problem with this is that the performance inliner is apparently generating invalid debug scopes.

**Comment by lattner** [comment]
Incidentally, part of "finishing deabstraction" is turning off the requirement for -O, so it would be great to fix this.

**Comment by adrian-prantl** [comment]
Can you post example SIL code that violates the verifier's assumptions (with `-sil-print-debuginfo` enabled)?
It would be interesting to learn whether the verifier is generally right and we could fix the inliner, or if it's a bug in the verifier.

**Comment by dcci** [comment]
@adrian-prantl yes, that is in line with what I had in mind.
@lattner / @dan-zheng if you can provide an example I/we might take a look at it and see whether it's a  bug or just we need to relax the verification.

**Comment by dan-zheng** [comment]
Here's an example:
```swift
// inline.swift
import TensorFlow
func test() {
  _ = Tensor(1)
}
```

```console
$ swiftc -Xllvm -sil-print-debuginfo inline.swift
SIL verification failed: Basic block contains a non-contiguous lexical scope at -Onone: DS == LastSeenScope
Verifying instruction:
     %13 = tuple (), loc "inline.swift":4:1, scope 0 // user: %14
->   return %13 : $(), loc "inline.swift":4:1, scope 0 // id: %14
In function:
sil_scope 1 { loc "inline.swift":2:6 parent @$S6inline4testyyF : $@convention(thin) () -> () }
sil_scope 2 { loc "inline.swift":4:1 parent 1 }
sil_scope 3 { loc "<compiler-generated>":0:0 parent @$SSd10TensorFlow013AccelerableByaB0A2aBP011_makeScalarA0yAA0A6HandleCyxGxFZTW : $@convention(witness_method: AccelerableByTensorFlow) (@in_guaranteed Double, @thick Double.Type) -> @owned TensorHandle<Double> }
sil_scope 4 {  parent @$S10TensorFlow0A0VyACyxGxcfC : $@convention(method) <τ_0_0 where τ_0_0 : AccelerableByTensorFlow> (@in τ_0_0, @thin Tensor<τ_0_0>.Type) -> @owned Tensor<τ_0_0> }
sil_scope 5 { loc "inline.swift":3:7 parent 2 }
sil_scope 6 {  parent 4 inlined_at 5 }
sil_scope 7 { loc "<compiler-generated>":0:0 parent @$S10TensorFlow013_TFMakeScalarA0yAA0A6HandleCyxGxAA013AccelerableByaB0RzlF : $@convention(thin) <τ_0_0 where τ_0_0 : AccelerableByTensorFlow> (@in_guaranteed τ_0_0) -> @owned TensorHandle<τ_0_0> inlined_at 6 }
sil_scope 8 {  parent 7 inlined_at 6 }
sil_scope 9 {  parent 3 inlined_at 8 }
sil_scope 10 { loc "<compiler-generated>":0:0 parent @$SSd10TensorFlowE011_makeScalarA0yAA0A6HandleCySdGSdFZ : $@convention(method) (Double, @thin Double.Type) -> @owned TensorHandle<Double> inlined_at 9 }
sil_scope 11 {  parent 4 inlined_at 5 }
sil_scope 12 { loc "<compiler-generated>":0:0 parent @$S10TensorFlow0A0V6handleACyxGAA0A6HandleCyxG_tcfC : $@convention(method) <τ_0_0 where τ_0_0 : AccelerableByTensorFlow> (@owned TensorHandle<τ_0_0>, @thin Tensor<τ_0_0>.Type) -> @owned Tensor<τ_0_0> inlined_at 11 }
sil_scope 13 {  parent @$S10TensorFlow0A0VyACyxGxcfC : $@convention(method) <τ_0_0 where τ_0_0 : AccelerableByTensorFlow> (@in τ_0_0, @thin Tensor<τ_0_0>.Type) -> @owned Tensor<τ_0_0> inlined_at 5 }

// test()
sil hidden @$S6inline4testyyF : $@convention(thin) () -> () {
bb0:
  %0 = float_literal $Builtin.FPIEEE64, 0x3FF0000000000000 // 1, loc "inline.swift":3:14, scope 2 // user: %1
  %1 = builtin "__tfop_tfc.scalarToTensor,$in"(%0 : $Builtin.FPIEEE64) : $TensorHandle<Double>, scope 10 // users: %12, %11, %10, %5, %4
  %2 = alloc_stack $Tensor<Double>, scope 12      // users: %3, %6, %9
  %3 = struct_element_addr %2 : $*Tensor<Double>, #Tensor.handle, scope 12 // user: %4
  store %1 to %3 : $*TensorHandle<Double>, scope 12 // id: %4
  strong_retain %1 : $TensorHandle<Double>, scope 12 // id: %5
  %6 = load %2 : $*Tensor<Double>, scope 12       // user: %7
  %7 = struct_extract %6 : $Tensor<Double>, #Tensor.handle, scope 12 // user: %8
  strong_release %7 : $TensorHandle<Double>, scope 12 // id: %8
  dealloc_stack %2 : $*Tensor<Double>, scope 12   // id: %9
  strong_retain %1 : $TensorHandle<Double>, scope 13 // id: %10
  strong_release %1 : $TensorHandle<Double>, scope 13 // id: %11
  strong_release %1 : $TensorHandle<Double>, loc "inline.swift":3:15, scope 2 // id: %12
  %13 = tuple (), loc "inline.swift":4:1, scope 2 // user: %14
  return %13 : $(), loc "inline.swift":4:1, scope 2 // id: %14
} // end sil function '$S6inline4testyyF'
```

**Comment by dan-zheng** [comment]
I relaxed debug scope verification in https://github.com/apple/swift/pull/17797/commits/48df845c089180d67a90e156519737792dbd872d.
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@adrian-prantl, @dcci: does the relaxation of debug scope verification in https://github.com/apple/swift/pull/17797/commits/48df845c089180d67a90e156519737792dbd872d look good to you? If so, I'll send a PR with that change upstream as well.

**Comment by adrian-prantl** [comment]
Yes, that's what I had in mind. That said, looking at your example, the scopes generated by the inliner also seem to be fine. We could also opt to teach the verifier about inlined call sites instead. The risk of not running the verifier on inlined code is that won't notice when any bugs creep in and fixing them later might be a lot more work. but as a very first step, the workaround would be fine.

**Comment by dan-zheng** [comment]
@adrian-prantl I see, that's a good point. Inlined code should be verified at some point.

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
I added a debug scope verification test: it failed prior to this patch but now passes.
I tried writing a SIL test, but the SIL parser fails when parsing the output of `swiftc -sil-print-after=tf-deabstraction -Xllvm -sil-print-debuginfo debug_scope.swift`.

Could reviewers please re-review?

**Review by dcci — APPROVED** [review]
lgtm, thanks for adding a test. (Adrian is out, so I'm reviewing for him)

**Comment by dan-zheng** [comment]
Thank you @adrian-prantl and @dcci for your feedback!

**Comment by lattner** [comment]
Thank you for fixing this @dan-zheng, and everyone for the help.  Dan, can you please upstream this to the master branch?

**Comment by dan-zheng** [comment]
@lattner I tried to upstream this patch to master in https://github.com/apple/swift/pull/17807, but I closed the PR because couldn't I come up with a suitable testcase.
It may be the case that, currently, on master, debug scope verification always succeeds for Swift programs. I can try handwriting a SIL test case later.

**Comment by lattner** [comment]
Ok thanks.  We can upstream it later I guess.  Thank you for trying!

**Comment by dan-zheng** [comment]
@dcci @adrian-prantl 
Sorry, the debug scope verification relaxation in the PR wasn't sufficient to handle deabstraction, which does performance inlining at `-Onone`.

Simple crasher:
```swift
// crash.swift
import TensorFlow
func test() {
  print(Tensor(1))
}
```

```console
```

**Comment by dcci** [comment]
@dan-zheng may I ask you to track down the first instruction that actually fails the verification in this block? (unfortunately the verifier just prints the terminator as per today, and that needs to be improved separately). It would make easier to figure out whether it's a bug.

**Comment by dan-zheng** [comment]
The first instruction that fails verification is (printed via `swiftc -Xllvm -debug-only=sil-verifier`):
```
Broken instruction!
  store %44 to %8 : $*Tensor<Double>, loc "crash.swift":4:9, scope 0 // id: %52
Please report a bug on bugs.swift.org
Pass -Xllvm -verify-di-holes=false to disable the verification
SIL verification failed: Basic block contains a non-contiguous lexical scope at -Onone: DS == LastSeenScope
```

[Full compiler output here, same link as above](https://gist.github.com/dan-zheng/f2fa7d05a3b5da2508b5126eda7122e8).

**Comment by dcci** [comment]
The scopes produced after the inline runs look OK to me, so I'm inclined to think we should enhance the verifier to handle these cases. For now, your stopgap solution works, although it might hide bugs.

**Comment by dan-zheng** [comment]
@dcci I see, thanks for the clarification!
After discussing with @rxwei and @mhong, we'd prefer to turn off `verify-di-holes` by default as a simple temporary solution. This avoids potential unexpected errors by marking functions as `-O`.

Do you have some idea of how to enhance the verifier to handle such inlined call sites? I'm happy to work on that with some guidance.

**Pull request merged**
