### PR TITLE
Fixes example snippet in OptionSet.swift

### PR DESCRIPTION
**Pull request by valeriyvan**
Fixes example snippet in OptionSet.swift

### CODE REVIEW

**Comment by xwu** [comment]
Well found, but this isn't good! I wonder if it's a known bug. The result should be as indicated in the documentation, and I can't clearly see why it's not. For kicks, I rewrote the function verbatim:

```swift
extension OptionSet where Element == Self {
  mutating func __remove(_ member: Element) -> Element? {
    let intersectionElements = intersection(member)
    guard !intersectionElements.isEmpty else { return nil }
    subtract(member)
    return intersectionElements
  }
}

options.__remove(.express) // ShippingOptions(rawValue: 2)
```

**Comment by xwu** [comment]
cc @natecook1000 @airspeedswift

**Comment by natecook1000** [comment]
It looks like that behavior was fixed in 5.3 (https://github.com/apple/swift/pull/28378), so whether or not you're getting that fix depends on which version of the stdlib your code is hitting.

**Comment by xwu** [comment]
Phew, I was worried that I was seeing some dynamic dispatch shenanigans here.

**Pull request closed without merging**
