### PR TITLE
[5.1] [Typechecker] Allow static functions to overload enum cases

### PR DESCRIPTION
**Pull request by theblixguy**
Totally forgot to cherry pick #23227 into this branch.

---

Fixes an issue with redeclaration checking where a static function would incorrectly get marked as a redeclaration of an enum element declaration, even if their types were different. See https://twitter.com/an0/status/1105187953834369025

Resolves [SR-10084](https://bugs.swift.org/browse/SR-10084).

### CODE REVIEW

**Comment by theblixguy** [comment]
Can someone run the CI for me? @xedin @jrose-apple 

Thank you!

**Comment by xedin** [comment]
@swift-ci please test

**Comment by theblixguy** [comment]
Thank you @xedin! I think this is worth adding to the change log, so I’ll create another PR for it.

**Comment by xedin** [comment]
@slavapestov Since you looked a the original PR and I don't see anything about 5.1 there after quick look, do we want take this?

**Comment by theblixguy** [comment]
Ping. Can we merge this?

**Comment by airspeedswift** [comment]
@slavapestov ?

**Comment by airspeedswift** [comment]
@swift-ci please test

**Pull request merged**
