### PR TITLE
[GSB] Don't complain about redundant requirements with inferred sources.

### PR DESCRIPTION
**Pull request by DougGregor**
If a requirement is made redundant due to another requirement that was
inferred from the signature of a generic declaration, don't diagnose
the former as redundant. The user has likely written the requirement
explicitly for clarity purposes (e.g., to emphasize the `Hashable`
requirement on a function that takes a `Set<T>`). Removing the
requirement to silence the warning would make the code less clear.

This eliminates all of the annoying, spurious warnings from the build
of the overlays.

### CODE REVIEW

**Comment by DougGregor** [comment]
This gets a lot more important once we start diagnosing redundant conformance requirements, which (currently) makes https://github.com/apple/swift/pull/7946 really really annoying to use.

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@jrose-apple I finally got around to silencing those warnings in the overlays. Sorry for the delay

**Comment by jrose-apple** [comment]
^ @phausler FYI

**Comment by phausler** [comment]
will this make the Unit/Measurement stuff stop emitting warnings?  if so 🎉 indeed!

**Comment by DougGregor** [comment]
@phausler yes, it gets rid of the Unit/Measurement warnings

**Pull request merged**
