### PR TITLE
[gardening] Remove never-read variables + tighten scope.

### PR DESCRIPTION
**Pull request by practicalswift**
Who can help me review this PR? :-)

### CODE REVIEW

**Comment by practicalswift** [comment]
@swift-ci please test

**Comment by practicalswift** [comment]
@swift-ci please benchmark

**Comment by practicalswift** [comment]
↑ Just testing the benchmark functionality - no change expected :-)

**Comment by practicalswift** [comment]
@swift-ci please benchmark

**Comment by practicalswift** [comment]
@swift-ci please benchmark

**Comment by jrose-apple** [comment]
I'm definitely concerned with finding all of these. Do they indicate logic failures in the surrounding code? Are they just trying to be consistent? Are they leftover from some prior version of the code?

**Comment by gottesmm** [comment]
@practicalswift Did you use clang-tidy to find these?

**Comment by gottesmm** [comment]
Hmmm... I wonder how I can find things that people are asking me to review.

@jrose-apple If this was found by clang-tidy, most likely it is bit-rot. When I was removing these, I was looking at each by hand just to be careful.

**Comment by practicalswift** [comment]
Regarding the gardening of `lib/IDE/TypeReconstruction.cpp`:
* The `bool found` was added by @nkcsgexi in 5a7a4f461d219c40fe6e8d1054ef7f57fc2a373b and had a use in the outer scope initially (see https://github.com/practicalswift/swift/blame/5a7a4f461d219c40fe6e8d1054ef7f57fc2a373b/lib/IDE/ReconstructType.cpp#L1680) but that use has been removed, so that's why I've moved it to the tighter scope where it is still in use.
* The `uint64_t index` and `bool is_in_class` were added by @nkcsgexi in the initial commit https://github.com/practicalswift/swift/blame/5a7a4f461d219c40fe6e8d1054ef7f57fc2a373b/lib/IDE/ReconstructType.cpp#L1425 and they didn't have any use back then :-)

**Comment by practicalswift** [comment]
Regarding the gardening of `lib/Parse/ParseStmt.cpp`:
* The `bool HaveFirst` was added by @gribozavr back in August 2013 (see https://github.com/practicalswift/swift/commit/e1d39e50525e2e40fc6f408c4be6ef6bf6d68793#diff-820a716f8b9e1992c9bd1f0e60a032cdR582) and appears to have been unused since :-)

**Comment by practicalswift** [comment]
Regarding the gardening of `lib/SILGen/SILGenExpr.cpp`:
* The `bool hasEmittedResult` was added by @lattner himself back in May 2015 (see https://github.com/practicalswift/swift/commit/6a5009e0ceb3f1a6314e0339e8b03c2d771ad076#diff-201a6bf7fb3e38068e179f351b08fd6eR3002) and appears to have been unused ever since :-)

**Comment by practicalswift** [comment]
Regarding the gardening of `lib/SILGen/SILGenPoly.cpp`:
* The `GenericEnvironment *genericEnv` was added by @eeckstein in September (see https://github.com/practicalswift/swift/commit/c65c1b5dda12002019a4b03c2204295a7a2cbacc#diff-8ec8d8d7b180ad13dcc551d02ccdd997R2323) and appears to have been unused since then :-)

**Comment by practicalswift** [comment]
Regarding the gardening of `lib/Sema/CSApply.cpp`:
* The `bool anythingShuffled` was added by @DougGregor back in May 2014 and did have a use initially. However that use is now gone :-)

**Comment by practicalswift** [comment]
Regarding the gardening of `lib/Sema/TypeCheckNameLookup.cpp`:
* The `bool anyRemoved` was added by @DougGregor back in May 2015 (see https://github.com/practicalswift/swift/commit/ca29fd9ea32f802265b84174b1e94943a44b8309#diff-554fe5ac9125c2a67ed8607539330b36R55) and appears to have been unused since then.

**Comment by practicalswift** [comment]
Regarding the gardening of `lib/Sema/TypeCheckType.cpp`:
* The `bool recovered` was added by @DougGregor back in January 2014 (see https://github.com/practicalswift/swift/commit/81279c6c00e14ff4012c60054f2e386763b6874b#diff-aee66a44df1b30cec188083399e31ec5R605). The variable was in use at that time but that use has been removed since then :-)

**Comment by practicalswift** [comment]
@swift-ci please smoke test

**Comment by practicalswift** [comment]
No objections during the last four days - merging :-)

**Comment by jrose-apple** [comment]
That's not really how review goes. If something's considered interesting enough to review, you should get *someone* to sign off on it before merging. That's not a hard rule, but for something non-blocking like this there's no reason to just go ahead.

**Review by DougGregor — COMMENTED** [review]
I browsed through these and didn't see any cases where the cleanups are wrong. Thanks for working on this (and sorry for the delay in reviewing)

**Comment by practicalswift** [comment]
@jrose-apple I agree with that in the general case :-)

In this specific case I requested a review initially, but after researching the history of each unused variable (see my updates above) I came to the conclusion that all of these were trivial typo style errors, and hence not in need of review.

I'll be more patient going forward :-)  Please let me know if you want me to revert to allow for a review.

**Comment by practicalswift** [comment]
@DougGregor Thanks! :-)

**Pull request merged**
