### PR TITLE
[QoI] fix diagnosis of non-Optional enum used in optional pattern

### PR DESCRIPTION
**Pull request by jtbandes**
``` swift
enum Foo { case Bar }
let maybeFoo = Foo.bar
```

Previously:

```
error: enum case 'Some' not found in type 'Foo'
guard let foo = maybeFoo else { fatalError() }
          ^
```

Now:

```
error: initializer for conditional binding must have Optional type, not 'Foo'
guard let foo = maybeFoo else { fatalError() }
          ^
```

Resolves [SR-1456](https://bugs.swift.org/browse/SR-1456).

### CODE REVIEW

**Comment by jtbandes** [comment]
@swift-ci please smoke test

**Comment by jtbandes** [comment]
Hmm, there is a strange test case in `SILGen/statements.swift` where  `guard let t = a` is expected to work when `a` is a custom optional type:
```
enum MyOptional<Wrapped> {
  case none
  case some(Wrapped)
}
```
Is this something we should still support? cc @lattner

**Comment by DougGregor** [comment]
That's weird; we don't want to support anything other than the true optional types in if-let/guard-let.

**Comment by slavapestov** [comment]
Renaming MyOptional to Optional might do the trick.

**Comment by jtbandes** [comment]
Would removing this be a language change that would need to go through swift-evolution? It seems like a bugfix, but conceivably some people could be using it.

**Comment by jtbandes** [comment]
I pre-emptively updated the commit to simply remove that test. 🙂
@swift-ci please smoke test

**Comment by jtbandes** [comment]
@swift-ci please test

**Comment by jtbandes** [comment]
@swift-ci clean test linux

**Comment by DougGregor** [comment]
I don't consider this a language change that needs swift-evolution. And, passing a SourceLoc for the initializer seems totally reasonable here. Thanks!

**Comment by jtbandes** [comment]
@DougGregor OK, thanks! If that qualifies as "LGTM", feel free to merge — GitHub won't let me do it for some reason.

What's the procedure for nominating changes for Swift 3.0? Do I just make another PR against `swift-3.0-branch`?

**Comment by DougGregor** [comment]
Merged. You can make a PR against the swift-3.0-branch, given it a 3.0 milestone, and assign to @tkremenek .

**Pull request merged**
