### PR TITLE
Update determination of "too complex" expression to take time into account.

### PR DESCRIPTION
**Pull request by rudkx**
By default, end expression type checking after the elapsed process is more than 600 seconds for the current expression. This threshold be overridden by using `-solver-expression-time-threshold=<seconds>`.
    
Resolves rdar://problem/32859654

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please test

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
@xedin Can you review for swift-4.0-branch?

**Review by xedin — APPROVED** [review]
LGTM!

**Comment by rudkx** [comment]
@swift-ci Please test

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Pull request merged**
