### PR TITLE
AST: repair the Windows build after #29289

### PR DESCRIPTION
**Pull request by compnerd**
Friend all types of AnyRequestBase, which may have been the intention of
the original friend request.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @hamishknight @DougGregor

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by hamishknight** [comment]
Thanks, LGTM!

**Comment by compnerd** [comment]
Not quite good enough:
```
C:\jenkins\workspace\swift-PR-windows\swift\include\swift/AST/AnyRequest.h(218): error C2248: 'swift::AnyRequest::getRawStorage': cannot access private member declared in class 'swift::AnyRequest'
C:\jenkins\workspace\swift-PR-windows\swift\include\swift/AST/AnyRequest.h(297): note: see declaration of 'swift::AnyRequest::getRawStorage'
C:\jenkins\workspace\swift-PR-windows\swift\include\swift/AST/AnyRequest.h(284): note: see declaration of 'swift::AnyRequest'
C:\jenkins\workspace\swift-PR-windows\swift\include\swift/AST/AnyRequest.h(213): note: while compiling class template member function 'llvm::hash_code swift::hash_value(const Derived &)'
        with
        [
            Derived=swift::AnyRequest
        ]
C:\jenkins\workspace\swift-PR-windows\swift\include\swift/AST/AnyRequest.h(284): note: see reference to class template instantiation 'swift::AnyRequestBase<swift::AnyRequest>' being compiled
```

**Comment by hamishknight** [comment]
@compnerd Trying a new fix: https://github.com/apple/swift/pull/29385. I can't seem to trigger the Windows CI though, could you trigger it for me?

**Pull request closed without merging**
