### PR TITLE
Hoist destroys of owned lexical values.

### PR DESCRIPTION
**Pull request by nate-chandler**
The new utility LexicalDestroyHoisting, which runs during copy propagation, hoists destroy_values of owned lexical values up to deinit barriers.  It is heavily based on the rewritten ShrinkBorrowScope.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by atrick — COMMENTED** [review]
This is super nice. Just two questions:

Why are destroys considered users?

I know we already talked about this, but now I don't understand: how can a terminator can be added to the barrier set if there's already a control flow boundary. Since this is pessimistic data flow, its block should never be visited. Is this if-condition ever reached?

>      if (!barriers.hoistingReachesEndBlocks.contains(
>              terminator->getParentBlock())) {

**Comment by nate-chandler** [comment]
Thanks!

> Why are destroys considered users?

It happens not to be a problem because the data flow starts from the instructions prior to them, so it never sees them, but it's fixed now to only add them to the set of ends.

> how can a terminator can be added to the barrier set if there's already a control flow boundary.

Great point--it can't.  Updated the comment and upgraded the condition to an assertion.

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by atrick — APPROVED** [review]
Awesome!

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
```
------- Performance (x86_64): -O -------

REGRESSION                                   OLD    NEW    DELTA    RATIO    
ArrayLiteral2                                74     82     +10.8%   **0.90x (?)**
Set.subtracting.Empty.Box                    20     22     +10.0%   **0.91x (?)**
SIMDRandomMask.Int8x16                       312    338    +8.3%    **0.92x (?)**

IMPROVEMENT                                  OLD    NEW    DELTA    RATIO    
LessSubstringSubstring                       30     22     -26.7%   **1.36x (?)**
LessSubstringSubstringGenericComparable      30     22     -26.7%   **1.36x**
EqualSubstringSubstring                      29     22     -24.1%   **1.32x**
EqualStringSubstring                         29     22     -24.1%   **1.32x**
EqualSubstringString                         29     22     -24.1%   **1.32x**
Set.subtracting.Seq.Box.Empty                276    211    -23.6%   **1.31x (?)**
EqualSubstringSubstringGenericEquatable      30     23     -23.3%   **1.30x (?)**
Breadcrumbs.MutatedUTF16ToIdx.Mixed          219    183    -16.4%   **1.20x (?)**
Breadcrumbs.MutatedIdxToUTF16.Mixed          222    188    -15.3%   **1.18x**
ObjectiveCBridgeStringHash                   96     83     -13.5%   **1.16x (?)**
Set.subtracting.Seq.Int.Empty                212    184    -13.2%   **1.15x (?)**
SortStringsUnicode                           2225   2010   -9.7%    **1.11x (?)**
ObjectiveCBridgeStringGetASCIIContents       343    314    -8.5%    **1.09x (?)**
DictionaryBridgeToObjC_Bridge                12     11     -8.3%    **1.09x (?)**
OpenClose                                    61     56     -8.2%    **1.09x (?)**
ProtocolDispatch                             239    220    -7.9%    **1.09x (?)**
Chars2                                       3200   2950   -7.8%    **1.08x (?)**
ObjectiveCBridgeStringCStringUsingEncoding   585    541    -7.5%    **1.08x (?)**
SortSortedStrings                            67     62     -7.5%    **1.08x (?)**

------- Code size: -O -------

------- Performance (x86_64): -Osize -------

REGRESSION                                OLD    NEW    DELTA    RATIO    
ArrayAppendRepeatCol                      500    670    +34.0%   **0.75x (?)**
RecursiveOwnedParameter                   221    284    +28.5%   **0.78x (?)**
ObjectiveCBridgeStubFromNSString          616    747    +21.3%   **0.82x (?)**
DataCreateEmpty                           80     90     +12.5%   **0.89x (?)**
CreateObjects                             8      9      +12.5%   **0.89x (?)**
DataCreateEmptyArray                      850    950    +11.8%   **0.89x (?)**
ArrayLiteral2                             99     109    +10.1%   **0.91x (?)**
SetUnionInt25                             71     77     +8.5%    **0.92x (?)**

IMPROVEMENT                               OLD    NEW    DELTA    RATIO    
FlattenListFlatMap                        3739   2615   -30.1%   **1.43x (?)**
SetSymmetricDifferenceInt100              150    108    -28.0%   **1.39x (?)**
FlattenListLoop                           1385   1006   -27.4%   **1.38x (?)**
LessSubstringSubstring                    30     22     -26.7%   **1.36x (?)**
EqualStringSubstring                      30     22     -26.7%   **1.36x (?)**
EqualSubstringString                      30     22     -26.7%   **1.36x**
LessSubstringSubstringGenericComparable   29     22     -24.1%   **1.32x (?)**
EqualSubstringSubstring                   30     23     -23.3%   **1.30x**
EqualSubstringSubstringGenericEquatable   29     23     -20.7%   **1.26x**
SetSymmetricDifferenceInt50               149    122    -18.1%   **1.22x**
Breadcrumbs.MutatedUTF16ToIdx.Mixed       219    184    -16.0%   **1.19x (?)**
Breadcrumbs.MutatedIdxToUTF16.Mixed       222    187    -15.8%   **1.19x (?)**
ObjectiveCBridgeStringHash                96     83     -13.5%   **1.16x (?)**
SetSymmetricDifferenceInt25               142    125    -12.0%   **1.14x (?)**
StringComparison_longSharedPrefix         332    297    -10.5%   **1.12x (?)**
ArraySetElement                           340    305    -10.3%   **1.11x**
SortStringsUnicode                        2225   2015   -9.4%    **1.10x (?)**
BridgeString.find.native.longNonASCII     433    393    -9.2%    **1.10x (?)**
SubstringEquatable                        288    264    -8.3%    **1.09x (?)**
DictionaryBridgeToObjC_Bridge             12     11     -8.3%    **1.09x (?)**
COWArrayGuaranteedParameterOverhead       2000   1850   -7.5%    **1.08x (?)**

------- Code size: -Osize -------

IMPROVEMENT                             OLD    NEW    DELTA   RATIO  
ArraySetElement.o                       1287   1267   -1.6%   **1.02x**
COWArrayGuaranteedParameterOverhead.o   1351   1331   -1.5%   **1.02x**
Sim2DArray.o                            1352   1332   -1.5%   **1.02x**
Join.o                                  1600   1580   -1.2%   **1.01x**
Memset.o                                1905   1885   -1.0%   **1.01x**
Array2D.o                               2754   2726   -1.0%   **1.01x**

------- Performance (x86_64): -Onone -------

REGRESSION                                   OLD     NEW     DELTA    RATIO    
SortSortedStrings                            130     140     +7.7%    **0.93x (?)**

IMPROVEMENT                                  OLD     NEW     DELTA    RATIO    
Breadcrumbs.MutatedIdxToUTF16.Mixed          231     197     -14.7%   **1.17x (?)**
Breadcrumbs.MutatedUTF16ToIdx.Mixed          220     188     -14.5%   **1.17x (?)**
ObjectiveCBridgeStringHash                   96      83      -13.5%   **1.16x (?)**
EqualSubstringString                         62      54      -12.9%   **1.15x (?)**
RandomDouble01LCG                            24429   21862   -10.5%   **1.12x (?)**
ObjectiveCBridgeStringGetASCIIContents       342     314     -8.2%    **1.09x**
Set.subtracting.Seq.Box.Empty                647     596     -7.9%    **1.09x (?)**
RandomDoubleLCG                              34597   31974   -7.6%    **1.08x (?)**
RandomDoubleOpaqueLCG                        34880   32238   -7.6%    **1.08x (?)**
ObjectiveCBridgeStringCStringUsingEncoding   586     547     -6.7%    **1.07x (?)**

------- Code size: -swiftlibs -------
```

**Pull request merged**
