### PR TITLE
[build] Don't build test targets in tools/ if SWIFT_INCLUDE_TESTS is turned off

### PR DESCRIPTION
**Pull request by finagolfin**
When cross-compiling the toolchain for Android, [the tests aren't built](https://github.com/apple/swift/blob/b7d26337e3252f013d271cd001635e260a50eb77/utils/build-script-impl#L1790) but these test binaries in tools/ still are and [I had to work around issues with building them](https://github.com/termux/termux-packages/blob/master/packages/swift/swift-cmake.patch#L449).

I just went through and disabled anything with `test` in its name, though of the few others I checked, it looks like `swift-reflection-dump` is only used in the tests too.

@CodaFi, let me know what you think.

### CODE REVIEW

**Comment by buttaface** [comment]
Ping, @gottesmm, maybe you have some input.

**Comment by buttaface** [comment]
@drexin, tiny build pull that maybe you could review?

**Comment by drexin** [comment]
@swift-ci test

**Comment by buttaface** [comment]
Ping, passed CI, ready to merge?

**Comment by buttaface** [comment]
@varungandhi-apple, mind reviewing?

**Review by varungandhi-apple — APPROVED** [review]

**Comment by varungandhi-apple** [comment]
@swift-ci test and merge

**Comment by buttaface** [comment]
Single test failure on Mac CI is unrelated, subsequently fixed by #35151.

**Comment by varungandhi-apple** [comment]
@swift-ci please test macOS

**Comment by buttaface** [comment]
CI should be working again now.

**Comment by buttaface** [comment]
Thanks for finally getting this in.

**Pull request merged**
