### PR TITLE
Don't prompt for credentials in update_checkout

### PR DESCRIPTION
**Pull request by moiseev**
The script is not supposed to be interactive, so it's OK to just fail if
it's unable to authenticate the user.

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
I think you need an `env` in there for portability.

**Comment by moiseev** [comment]
@jrose-apple you mean `env GIT_TERMINAL_PROMPT=0 git`?

**Comment by jrose-apple** [comment]
Yep, that's all. I think, anyway.

**Comment by moiseev** [comment]
Done. Won't hurt =)

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Pull request merged**
