### PR TITLE
PrintAsObjC: use header path relative to usr/include when importing non-framework headers

### PR DESCRIPTION
**Pull request by nkcsgexi**
We could assume usr/include belongs to header search paths. If a header
is located in a deeper location inside this directory, we need to print
the additional path components.

rdar://60857172

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
I don't believe this is the correct fix. At this point, I'd like to roll back our changes here and think a bit more about how we can solve the problem comprehensively.

**Comment by DougGregor** [comment]
FYI, I'm rolling the changes back in https://github.com/apple/swift/pull/30697.

**Pull request merged**
