### PR TITLE
[stdlib] Migrate _copyCollectionToContiguousArray to use _copyContents

### PR DESCRIPTION
**Pull request by airspeedswift**
Longstanding FIXME, we'll see if it helps.

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
@swift-ci please benchmark

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@airspeedswift update here? Is this PR still desired, or should it be closed?

**Pull request closed without merging**
