### PR TITLE
First pass at a script to generate random type definitions.

### PR DESCRIPTION
**Pull request by jckarter**
This will be useful to generate input for fuzzing runtime layout, ABI compatibility, layout algorithms, etc.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Review by xedin — APPROVED** [review]
Very cool!

**Comment by slavapestov** [comment]
You should be using Swift for this :)

**Comment by jessesquires** [comment]
@slavapestov 🤣 😆 😄 https://twitter.com/swiftlybrief/status/910360169426669568

**Comment by slavapestov** [comment]
@erg and I wrote a random type generator once. But he left Apple so I'm not sure he saved a copy of it...

**Comment by jckarter** [comment]
@swift-ci Please clean smoke test

**Pull request merged**
