### PR TITLE
Update CHANGELOG.md for #34005

### PR DESCRIPTION
**Pull request by AnthonyLatsis**

### CODE REVIEW

**Comment by AnthonyLatsis** [comment]
Are we allowed to reference pull requests in place of JIRA reports though?

**Comment by theblixguy** [comment]
You can file a new JIRA ticket and link it in the changelog.

**Comment by AnthonyLatsis** [comment]
Yeah, I am just curious whether referencing a PR directly is acceptable :)

**Comment by AnthonyLatsis** [comment]
ping

**Pull request closed without merging**
