### PR TITLE
Windows CMake Cache organization (NFC)

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @drodriguez

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by drodriguez** [comment]
Just FYI, this is not used in the CI builds, as far as I know. I do not see any reference in the `build-windows.bat` file. It also looks like something intended for an unified build, which the Swift project seems not to use in other platforms.

Thanks for the cc, but I think this might only apply to Azure?

**Comment by compnerd** [comment]
The documentation uses these files IIRC; however, you do bring up a good point - I think that we may want to consider using the CMake cache for the CI builds.  The next set of changes that I want to make would be much more complicated otherwise.

**Pull request merged**
