### PR TITLE
 Restrict RemoteASTTypeBuilder::findModule() to the list of loaded modules

### PR DESCRIPTION
**Pull request by adrian-prantl**
LLDB uses RemoteAST for its per-module SwiftASTContext. Importing
external modules here could permanently damage this context, for
example when a Clang import fails because of missing header search
options. To avoid this situation, restrict RemoteAST's access to only
the module's transitive closure of imports.

Triggering this situation needs two independent Swift compilation
units. An accompanying testcase (Swift/RemoteASTImport.test) has been
added to LLDB.

rdar://problem/40950542

### CODE REVIEW

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-lldb/pull/704
@swift-ci test

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-lldb/pull/704
@swift-ci test

**Comment by jrose-apple** [comment]
This looks correct to me; I'd just like someone within Apple to confirm that this won't mess up anyone else's use of RemoteAST.

**Comment by adrian-prantl** [comment]
If you have anyone specific in mind, please feel free to add more reviewers!

**Pull request merged**
