### PR TITLE
GSB: Add an inferred AnyObject constraint to @objc protocol requirement signatures

### PR DESCRIPTION
**Pull request by slavapestov**
This simplifies GenericSignatureImpl::requiresClass(), which no longer
has to look through the conformances of the equivalence class.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by shahmishal** [comment]
@swift-ci Please test

**Comment by shahmishal** [comment]
@swift-ci Please test source compatibility

**Comment by shahmishal** [comment]
@swift-ci Please test source compatibility

**Comment by shahmishal** [comment]
@swift-ci Please test macOS

**Comment by shahmishal** [comment]
@swift-ci Please test Linux

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Pull request merged**
