### PR TITLE
Fix build-script SwiftEvolve support

### PR DESCRIPTION
**Pull request by beccadax**
Recent changes to build-script and build-script-impl omitted swift-evolve. This change restores support for building it.

### CODE REVIEW

**Comment by brentdax** [comment]
@swift-ci please build toolchain

**Comment by benlangmuir** [comment]
> dyld: Library not loaded: @rpath/libswiftSwiftSyntax.dylib

**Comment by brentdax** [comment]
Please test with following pull request:
https://github.com/apple/swift-stress-tester/pull/36

@swift-ci please build toolchain

**Comment by brentdax** [comment]
@benlangmuir That failure is unrelated—it looks like SwiftSyntax moved its dylib while we weren't looking. I'm testing a fix for that issue now.

**Review by benlangmuir — APPROVED** [review]
LGTM, sorry for the breakage (in my defense, swift-evolve didn't exist when I opened the PR).

**Comment by brentdax** [comment]
Doing this in #22500 instead.

**Comment by brentdax** [comment]
@swift-ci please build toolchain

**Comment by brentdax** [comment]
@swift-ci please test

**Comment by brentdax** [comment]
@swift-ci please test

**Comment by brentdax** [comment]
@swift-ci please test

**Pull request merged**
