### PR TITLE
[SIL Diagnostics] Fix undefined behavior due to bit shifting in ConstantFolding.cpp

### PR DESCRIPTION
**Pull request by ravikandhadai**
Cherry picking changes from Swift master for the bug fix.
  <rdar://48605307>

### CODE REVIEW

**Comment by ravikandhadai** [comment]
@swift-ci Please test and merge

**Review by aschwaighofer — APPROVED** [review]
Thank you

**Comment by ravikandhadai** [comment]
@swift-ci Please test and merge

**Comment by ravikandhadai** [comment]
@swift-ci Please test and merge

**Comment by ravikandhadai** [comment]
@swift-ci Please merge

**Pull request merged**
