### PR TITLE
Revert "[IRGen testing] Fix bogus FileCheck check-prefix "-SAME" usage"

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/swift#31839

Revert to get Windows green.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @davezarzycki

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by davezarzycki** [comment]
That’s fine. That being said, if windows testing clean effectively blocks commits, then it should be required before merging, right? CC: @shahmishal

**Comment by benrimmington** [comment]
@davezarzycki There's also an iOS failure in [Build #20863](https://ci.swift.org/job/swift-PR-osx/20863/) (using "test" instead of "smoke test").

```
FAIL: Swift(iphonesimulator-i386) :: IRGen/class_resilience.swift (11888 of 13208)
******************** TEST 'Swift(iphonesimulator-i386) :: IRGen/class_resilience.swift' FAILED ********************
```

**Comment by davezarzycki** [comment]
Hi @benrimmington – I'm struggling to reproduce the 32-bit error. How are people supposed to run the 32-bit simulator these days? Does that require a copy of macOS earlier than Catalina?

**Comment by benrimmington** [comment]
@davezarzycki I haven't tried recently, but it used to require a 32-bit iOS simulator with a specific name (e.g. "iPhone 5"). I'm trying it now to see what the actual name should be.

The last 32-bit device was the iPhone 5, which supports up to iOS 10.3.4; and the oldest simulator available to download (in the latest Xcode + macOS) is "iOS 10.3.1 Simulator".

**Comment by davezarzycki** [comment]
> @davezarzycki I haven't tried recently, but it used to require a 32-bit iOS simulator with a specific name (e.g. "iPhone 5"). I'm trying it now to see what the actual name should be.
> 
> 
> 
> The last 32-bit device was the iPhone 5, which supports up to iOS 10.3.4; and the oldest simulator available to download (in the latest Xcode + macOS) is "iOS 10.3.1 Simulator".

Right. I get bunch of “Invalid device: iPhone 5” errors and `xcrun simctl list` doesn’t lit iPhone 5 as a valid device for 10.3 despite the fact that it should be there. I’d wager that macOS Catalina effectively cut off 32-bit simulators from working

**Comment by benrimmington** [comment]
@davezarzycki You might have missed step 2 below.

**Xcode:**

1.  Xcode → Preferences… → Components → Simulators;
    Download the "iOS 10.3.1 Simulator" (1.98 GB).

2.  Window → Devices and Simulators → Simulators → bottom-left "+" button;
    Select the "Device Type: iPhone 5" (and "OS Version: iOS 10.3") → Create.

**Terminal:**

3.  `xcrun simctl list` should now include "iPhone 5" under iOS 10.3 devices:

    ```
    == Runtimes ==
    iOS 10.3 (10.3.1 - 14E8301) - com.apple.CoreSimulator.SimRuntime.iOS-10-3
    «etc.»

    == Devices ==
    -- iOS 10.3 --
        iPhone 5 («UUID») (Shutdown)
        «etc.»
    ```

4.  `swift/utils/build-script --test --ios`
    (with `--reconfigure` and `--skip-test-osx` if needed).
    The "Swift(iphonesimulator-i386)" tests succeeded.

**Comment by benrimmington** [comment]
I've created apple/swift#31866 to update the Testing.md document.

**Pull request merged**
