### PR TITLE
Roll back a portion of SE-0110

### PR DESCRIPTION
**Pull request by rudkx**
As described in:
> https://lists.swift.org/pipermail/swift-evolution-announce/2017-June/000386.html

Specifically allow an N-ary argument function to be passed as an
argument in a place where a function of a single N-tuple is expected.

Fixes: rdar://problem/32875953
(cherry picked from commit 0ba4a312af17228afb9613874b1400cdfe520fae)

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please test

**Comment by rudkx** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
Is this going into master as well?

**Comment by rudkx** [comment]
Already there: https://github.com/apple/swift/commit/706922dd3678f5710811ad057978a0f02f392d16

**Review by DougGregor — APPROVED** [review]
LGTM, and thank you for pulling in the examples from my e-mail.

**Comment by tkremenek** [comment]
@swift-ci test source compatibility

**Comment by ematejska** [comment]
@swift-ci test source compatibility

**Pull request merged**
