### PR TITLE
[ownership] Ban ValueOwnershipKind::Any in preparation for eliminated ValueOwnershipKind::Trivial

### PR DESCRIPTION
**Pull request by gottesmm**
This PR eliminates our usage of ValueOwnershipKind::Any's old undef like semantics and temporarily bans ValueOwnershipKind::Any when ownership verification is enabled. This involves:

1. Changing SILUndef to produce owned ownership if it has a non-trivial type and trivial ownership if it has a trivial type. This involved storing in SILUndef said ValueOwnershipKind since we do not have access to a SILModule when computing the ValueOwnershipKind of a SILValue.

2. Adding an assert that bans ValueOwnershipKind::Any for /all/ values.

After this commit, I should be able to just do a sed-ish replace of all references to ValueOwnershipKind::Trivial to ValueOwnershipKind::Any and start debriding.

rdar://46294760

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci source compatibility

**Comment by gottesmm** [comment]
@swift-ci  Test Source Compatibility

**Comment by gottesmm** [comment]
@swift-ci Please Test Source Compatibility

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
(not expecting benchmark changes, just want to run the benchmarks)

**Comment by slavapestov** [comment]
"and start debriding"

What is debriding?

**Comment by gottesmm** [comment]
@slavapestov https://bit.ly/2BBYpKF

**Comment by gottesmm** [comment]
Talked with Andy. He is going to do post-commit review on this.

**Review by atrick — COMMENTED** [review]
LGTM

**Pull request merged**
