### PR TITLE
[AutoDiff upstream] Add differentiation diagnostics tests.

### PR DESCRIPTION
**Pull request by dan-zheng**
Upstream remaining differentiation diagnostics tests from `tensorflow` branch:
- `swift/test/AutoDiff/downstream/differentiation_transform_diagnostics.swift`
- `swift/test/AutoDiff/downstream/forward_mode_diagnostics.swift`

### CODE REVIEW

**Comment by dan-zheng** [comment]
@swift-ci Please smoke test

**Comment by dan-zheng** [comment]
@swift-ci Please smoke test

**Comment by dan-zheng** [comment]
@swift-ci Please smoke test

**Review by rxwei — APPROVED** [review]

**Comment by dan-zheng** [comment]
@swift-ci Please test Windows

**Pull request merged**
