### PR TITLE
[CSDiagnostics] Emit fix-its to insert requirement stubs for missing protocols in context

### PR DESCRIPTION
**Pull request by theblixguy**
This is a follow-up to https://github.com/apple/swift/pull/27026.

---

At the moment, we emit a fix-it to insert the missing conformance. For example:

```swift
protocol P {
  func method()
}

class C {
  var p: P?
  
  func assign() {
    p = self
  }
}
```

Here, we emit fix-it to add `: P` to `C`. With this change, we now also emit the requirement stub (`func method()`) if we're in editor mode.

### CODE REVIEW

**Comment by hborla** [comment]
Will this still add the requirement stub if the type already implements the requirement?

**Comment by theblixguy** [comment]
Yeah, it will, which is unfortunate. I am assuming that in most cases there won't be any conflicts. It would've been nice if there was a way to get an array of missing witnesses from the type checker (or maybe there is?).

**Comment by theblixguy** [comment]
Oh never mind, I misunderstood the role of `filterProtocolRequirements` (it filters conflicting requirements, it doesn't filter requirements that are already implemented). 

I figured out another way using `ConformanceChecker` which seems to work. Let me know what you think of this approach.

**Comment by xedin** [comment]
@swift-ci please build toolchain macOS

**Comment by theblixguy** [comment]
Toolchain: https://ci.swift.org/job/swift-PR-toolchain-osx/641/artifact/branch-master/swift-PR-33628-641-osx.tar.gz

**Review by xedin — APPROVED** [review]
LGTM! Just wanted to give it a try and see where it would insert these stubs

**Comment by theblixguy** [comment]
@swift-ci please smoke test

**Comment by theblixguy** [comment]
@swift-ci please smoke test macOS

**Pull request merged**
