### PR TITLE
[Clang importer] Ensure that we check a bridging PCH in a source file context

### PR DESCRIPTION
**Pull request by DougGregor**
When checking whether we can load a bridging precompiled header (PCH), we end
up parsing module maps. If Clang emits a warning or error while parsing the
module maps we encounter, the Swift compiler would crash because we have not
properly established the invariants of Clang's diagnostic engine. Perform a
pairsed set of BeginSourceFile/EndSourceFile calls on the Clang diagnostic
consumer to set up the appropriate state.

Fixes rdar://problem/57626886.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Review by bcardosolopes — APPROVED** [review]
LGTM

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
