### PR TITLE
Allow using MemoryLayout's .size, .stride, .alignment fields in forced-const global initializers

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Review by eeckstein — COMMENTED** [review]
See my comments for https://github.com/apple/swift/pull/67243.
The MemoryLayout stuff lgtm. As with the other change, can you add a test in https://github.com/apple/swift/blob/main/test/SILOptimizer/init_static_globals.sil?

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by eeckstein — APPROVED** [review]
lgtm

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Comment by kubamracek** [comment]
Superseded by https://github.com/apple/swift/pull/67587. Closing.

**Pull request closed without merging**
