### PR TITLE
Add regression tests to close several fixed issues

### LINKED ISSUE #44672: [SR-2063] Binary operator '||' cannot be applied error when using short syntax for enum
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-2063      |
   |Radar             | None         |
   |Original Reporter | sofacoder (JIRA User)      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI, TypeChecker        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 643294ba9d3d7b88981d16881fad8cda

  </details>

**Issue Description:**

The following code creates the error "Binary operator '\|\|' cannot be applied to two 'Bool' operands"

``` java
@objc public enum TestEnum: Int
{
    case First
    case Second
}

public class TestClass
{
    public static func demoProblem()
    {
        let number = 1
        let test = true || number == .First.rawValue // error!
        print(test)
    }
}
```

if the line with the '\|\|' operand is change in the following way, everything works fine.

``` java
        let test = true || number == TestEnum.First.rawValue
```

This is probably because the expression `.First.rawValue` is ambiguous, but then the compiler should say so. The current error is misleading.

Tested with: Apple Swift version 2.2 (swiftlang-703.0.18.8 clang-703.0.31)

### LINKED ISSUE #45389: [SR-2785] Associated Type Inference does not work on operator requirements.
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-2785      |
   |Radar             | None         |
   |Original Reporter | andersha (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Xcode 8.0 8A218a

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, TypeChecker        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 96cf17b5e62b7cf8117a68c145ad65f1

  </details>

**Issue Description:**

Consider the following snippet:

``` java
public class Box<U>: BoxProtocol {
    public typealias Value = U
}

public protocol TestCase4 {
    associatedtype Value
    static func requirement(_self: Self, value: Box<Value>)
}

public protocol TestCase4_1 {
    associatedtype Value
    static func <~(_self: Self, value: Box<Value>)
}

public class D<Value>: TestCase4 {
    public static func requirement(_self: D, value: Box<Value>) {}
}

public class D_1<Value>: TestCase4_1 {
    public static func <~ (_self: D_1, value: Box<Value>) {}
}
```

While \`D\` compiles, the type checker would complain about the lack of nested type \`Value\` in \`D_1\`, which is supposed to be inferred from the matching operator implementation like \`D\`.

### LINKED ISSUE #52024: [SR-9577] Associated type inference fails depending on name of associated type
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-9577      |
   |Radar             | None         |
   |Original Reporter | @lattner      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, AssociatedTypeInference        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 09335bcbf125fdc2adc6cf703a1965fa

  </details>

**Issue Description:**

Jeremy Howard sent me this bug report, it repros with Swift 4.2 and 4.2.1 at least.

This code is relying on associated type inference to infer the type of "Elle" in the VectorF struct. This should happen due to the init requirement in the protocol VectorBase, and the init implementation in VectorF.

Two bugs here:

1\) The associated type isn't inferred correctly in this case.  
2) **Even weirder**, if you globally rename Elle to Eele, then it works (!!!)

I assume there is some sort of memory smasher or corruption going on here inside the compiler?

``` none
public protocol VectorBase :
    RandomAccessCollection where Index==Int, Elle==Element {
  associatedtype Elle
  var data:Array<Elle> {get set}
  init(_ data_:Array<Elle>)
}

public protocol Vector: VectorBase {
}

extension Vector where Elle: FloatingPoint {
  public var count:Int {get {return data.count}}

  // RandomAccessCollection
  public var indices: Range<Int> { return 0..<count }
  public var startIndex: Int { return 0 }
  public var endIndex: Int { return count }
  // MutableCollection
  public subscript(i: Index) -> Elle {
    get { return data[i] }
    set { data[i] = newValue }
  }
}

public struct VectorF: Vector {
  //public typealias Elle = Float

  public var data:Array<Float>
  public init(_ data_:Array<Float>) {data=data_}
}
```

### LINKED ISSUE #56100: [SR-13703] CodeCompletion: Assertion failed while printing generic signature: (Val && "isa<> used on a null pointer")
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13703      |
   |Radar             | rdar://problem/70057258         |
   |Original Reporter | @nathawes      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | CodeCompletion    |
   |Labels            | Bug, Crash, FoundByStressTester        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 3188687bb08d406e0bbca0cdc9878dbf

  </details>

**Issue Description:**

Reproducing test case:

``` java
// RUN: %swift-ide-test -code-completion -code-completion-token=COMPLETE -source-filename %s

extension Result {
  public init(_ value: Success?) {
    self = value.map(#^COMPLETE^#)
  }
}

public func materialize<T>(_ f: T) {}
```

Crash trace (via sourcekitd):

``` java
Thread 3 Crashed:
0   libsystem_kernel.dylib          0x00007fff6fc5333a __pthread_kill + 10
1   libsystem_pthread.dylib         0x00007fff6fd0fe60 pthread_kill + 430
2   libsystem_c.dylib               0x00007fff6fbda8a2 __abort + 139
3   libsystem_c.dylib               0x00007fff6fbda817 abort + 135
4   libsystem_c.dylib               0x00007fff6fbd9ac6 __assert_rtn + 314
5   com.apple.SourceKitService.5.0.20200928101_osx  0x0000000106861ec1 swift::Decl::getInnermostDeclContext() const (.cold.1) + 33
6   com.apple.SourceKitService.5.0.20200928101_osx  0x0000000103f9f418 swift::Decl::getInnermostDeclContext() const + 136
7   com.apple.SourceKitService.5.0.20200928101_osx  0x0000000103f4f6f1 (anonymous namespace)::PrintAST::printSingleDepthOfGenericSignature(swift::ArrayRefView<swift::Type, swift::GenericTypeParamType*, swift::GenericTypeParamType* swift::staticCastHelper<swift::GenericTypeParamType>(swift::Type const&), true>, llvm::ArrayRef<swift::Requirement>, bool&, unsigned int, llvm::function_ref<bool (swift::Requirement const&)>) + 161
8   com.apple.SourceKitService.5.0.20200928101_osx  0x0000000103f4f608 (anonymous namespace)::PrintAST::printGenericSignature(swift::GenericSignature, unsigned int, llvm::function_ref<bool (swift::Requirement const&)>) + 1160
9   com.apple.SourceKitService.5.0.20200928101_osx  0x0000000103f5529a swift::TypeVisitor<(anonymous namespace)::TypePrinter, void>::visit(swift::Type) + 4410
10  com.apple.SourceKitService.5.0.20200928101_osx  0x0000000103f44d83 swift::Type::print(swift::ASTPrinter&, swift::PrintOptions const&) const + 67
11  com.apple.SourceKitService.5.0.20200928101_osx  0x0000000103f46785 swift::TypeBase::print(swift::ASTPrinter&, swift::PrintOptions const&) const + 21
12  com.apple.SourceKitService.5.0.20200928101_osx  0x0000000102fd12b2 swift::ide::CodeCompletionResultBuilder::addTypeAnnotation(swift::Type, swift::PrintOptions, llvm::StringRef) + 450
13  com.apple.SourceKitService.5.0.20200928101_osx  0x0000000102fdadd8 (anonymous namespace)::CompletionLookup::addTypeAnnotation(swift::ide::CodeCompletionResultBuilder&, swift::Type, swift::GenericSignature) + 168
14  com.apple.SourceKitService.5.0.20200928101_osx  0x0000000102fd78ff (anonymous namespace)::CompletionLookup::addCompoundFunctionNameIfDesiable(swift::AbstractFunctionDecl*, swift::DeclVisibilityKind, swift::DynamicLookupInfo) + 1759
15  com.apple.SourceKitService.5.0.20200928101_osx  0x0000000102fd4e93 (anonymous namespace)::CompletionLookup::foundDecl(swift::ValueDecl*, swift::DeclVisibilityKind, swift::DynamicLookupInfo) + 307
16  com.apple.SourceKitService.5.0.20200928101_osx  0x000000010409aac2 swift::SourceLookupCache::lookupVisibleDecls(swift::ImportPath::Access, swift::VisibleDeclConsumer&, swift::NLKind) + 530
17  com.apple.SourceKitService.5.0.20200928101_osx  0x0000000102fd33a9 deliverCompletionResults(swift::ide::CodeCompletionContext&, (anonymous namespace)::CompletionLookup&, swift::SourceFile&, swift::ide::CodeCompletionConsumer&) + 569
18  com.apple.SourceKitService.5.0.20200928101_osx  0x0000000102fe6c26 (anonymous namespace)::CodeCompletionCallbacksImpl::doneParsing() + 19990
19  com.apple.SourceKitService.5.0.20200928101_osx  0x0000000103e3ea55 swift::Parser::performCodeCompletionSecondPassImpl(swift::CodeCompletionDelayedDeclState&) + 933
20  com.apple.SourceKitService.5.0.20200928101_osx  0x0000000103e3e58a swift::CodeCompletionSecondPassRequest::evaluate(swift::Evaluator&, swift::SourceFile*, swift::CodeCompletionCallbacksFactory*) const + 234
21  com.apple.SourceKitService.5.0.20200928101_osx  0x0000000103e48e92 llvm::Expected<swift::CodeCompletionSecondPassRequest::OutputType> swift::Evaluator::getResultUncached<swift::CodeCompletionSecondPassRequest>(swift::CodeCompletionSecondPassRequest const&) + 386
22  com.apple.SourceKitService.5.0.20200928101_osx  0x0000000103e48c9e llvm::Expected<swift::CodeCompletionSecondPassRequest::OutputType> swift::Evaluator::operator()<swift::CodeCompletionSecondPassRequest, (void*)0>(swift::CodeCompletionSecondPassRequest const&) + 110
23  com.apple.SourceKitService.5.0.20200928101_osx  0x0000000103e3e397 swift::CodeCompletionSecondPassRequest::OutputType swift::evaluateOrDefault<swift::CodeCompletionSecondPassRequest>(swift::Evaluator&, swift::CodeCompletionSecondPassRequest, swift::CodeCompletionSecondPassRequest::OutputType) + 55
24  com.apple.SourceKitService.5.0.20200928101_osx  0x0000000102f0b561 void llvm::function_ref<void (swift::CompilerInstance&, bool)>::callback_fn<swiftCodeCompleteImpl(SourceKit::SwiftLangSupport&, llvm::MemoryBuffer*, unsigned int, (anonymous namespace)::SwiftCodeCompletionConsumer&, llvm::ArrayRef<char const*>, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)::$_2>(long, swift::CompilerInstance&, bool) + 433
25  com.apple.SourceKitService.5.0.20200928101_osx  0x0000000103007999 swift::ide::CompletionInstance::performNewOperation(llvm::Optional<llvm::hash_code>, swift::CompilerInvocation&, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, llvm::MemoryBuffer*, unsigned int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, swift::DiagnosticConsumer*, llvm::function_ref<void (swift::CompilerInstance&, bool)>) + 585
26  com.apple.SourceKitService.5.0.20200928101_osx  0x0000000103007eb8 swift::ide::CompletionInstance::performOperation(swift::CompilerInvocation&, llvm::ArrayRef<char const*>, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, llvm::MemoryBuffer*, unsigned int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, swift::DiagnosticConsumer*, llvm::function_ref<void (swift::CompilerInstance&, bool)>) + 696
27  com.apple.SourceKitService.5.0.20200928101_osx  0x0000000102f3fd74 SourceKit::SwiftLangSupport::performCompletionLikeOperation(llvm::MemoryBuffer*, unsigned int, llvm::ArrayRef<char const*>, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, llvm::function_ref<void (swift::CompilerInstance&, bool)>) + 2596
28  com.apple.SourceKitService.5.0.20200928101_osx  0x0000000102f04d4d SourceKit::SwiftLangSupport::codeComplete(llvm::MemoryBuffer*, unsigned int, SourceKit::OptionsDictionary*, SourceKit::CodeCompletionConsumer&, llvm::ArrayRef<char const*>, llvm::Optional<SourceKit::VFSOptions>) + 573
29  com.apple.SourceKitService.5.0.20200928101_osx  0x0000000102f6c678 handleSemanticRequest(sourcekitd::RequestDict, std::__1::function<void (void*)>, sourcekitd_uid_s*, llvm::Optional<llvm::StringRef>, llvm::Optional<llvm::StringRef>, llvm::ArrayRef<char const*>, llvm::Optional<SourceKit::VFSOptions>) + 2440
30  com.apple.SourceKitService.5.0.20200928101_osx  0x0000000102f6bbe8 void SourceKit::WorkQueue::DispatchData::callAndDelete<handleRequestImpl(void*, std::__1::function<void (void*)>)::$_7>(void*) + 376
31  libdispatch.dylib               0x00007fff6fab2658 _dispatch_client_callout + 8
32  libdispatch.dylib               0x00007fff6fab4d79 _dispatch_block_invoke_direct + 245
33  com.apple.SourceKitService.5.0.20200928101_osx  0x000000010603ed8f executeBlock(void*) + 15
34  com.apple.SourceKitService.5.0.20200928101_osx  0x0000000102ee921d threadFuncSync(void*) + 13
35  libsystem_pthread.dylib         0x00007fff6fd10109 _pthread_start + 148
36  libsystem_pthread.dylib         0x00007fff6fd0bb8b thread_start + 15
```

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
Closes #44672, closes #45389, closes #56100, closes #52024, closes #51217, closes #52588

### CODE REVIEW

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Review by xedin — APPROVED** [review]
Looks great, thank you!

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Pull request merged**
