### PR TITLE
SourceKit: use `std::chrono` in unittests

### PR DESCRIPTION
**Pull request by compnerd**
Rather than using the `usleep` function which is both deprecated and
non-portable (does not exist on Windows), prefer using the C++11 chrono library
for the sleep.  This also allows us to use the UDL to simplify the code rather
than relying on the comments.  NFCI

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @benlangmuir @akyrtzi

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
The comment implies that you're changing to not use `usleep`, but in fact it still calls usleep.  Did you mean to use `std::this_thread::sleep_for` or something similar?

**Comment by compnerd** [comment]
😒 I are dum-dums.  Yes, that should be a `std::this_thread::sleep_for`.  I swear I had that changed!  I hate pushing from a different machine than what I'm testing on.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Hmm, okay, well, thats easy to deal with (`std::chrono::*seconds`)

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@benlangmuir any concerns with this now?

**Review by benlangmuir — APPROVED** [review]
LGTM

**Pull request merged**
