### PR TITLE
Fix abi_v7k IR,asm test cases

### PR DESCRIPTION
**Pull request by aschwaighofer**
We pass an optional float as a pair of i32,i1 on armv7k.

rdar://27341290

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test os x platform

**Comment by gribozavr** [comment]
@aschwaighofer Because this test is:

```
// REQUIRES: CPU=armv7k
// REQUIRES: OS=watchos
```

smoke test does not run it.

**Comment by aschwaighofer** [comment]
Right, but I need a smoke test to commit it.

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test linux

**Pull request merged**
