### PR TITLE
Updates image to resolve #75109

### LINKED ISSUE #75109: Replace old screenshot with new one
### Description

Doc to change: https://github.com/swiftlang/swift/blob/main/docs/HowToGuides/FirstPullRequest.md

The screenshot in this doc is showing apple/swift and it's now swiftlang/swift under submitting a pull request. Good first issue for someone! 
[Link to image](https://github.com/swiftlang/swift/blob/main/docs/GitHubCreatePRScreenshot.png)

### Reproduction

n/a

### Expected behavior

n/a

### Environment

n/a

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by vidhupv**
Uploading new screenshot for the "HowToGuide for First Pull" after the repository name was changed from apple/swift to swiftlang/swift .

### CODE REVIEW

**Comment by AnthonyLatsis** [comment]
Why’d you close it?

**Comment by vidhupv** [comment]
I had only uploaded the screenshot and hadn't updated the Howto guide of Pull Requests so I made all the changes and created a new pull request. Hope that's alright. This was my first time contributing to a huge codebase so was a little confused whether to submit changes one by one or all together

**Comment by AnthonyLatsis** [comment]
All good. I thought maybe you had this common misconception that you cannot rewrite or add commits in a pull request.

**Comment by vidhupv** [comment]
Oh I didn't know that. When I clicked on edit I could only change the name and other details so I just redid the whole thing.

**Comment by AnthonyLatsis** [comment]
I see 🙂. This is how it works: a pull request wraps a branch of yours, so whatever you do to that branch is reflected in the pull request. Nothing about the pull request itself, like its title, description, base branch, labels, etc., will affect your branch or changes — they are independent GitHub-specific data.

**Comment by vidhupv** [comment]
Ahh,got it. Thank you. I had sent another pull request solving all the issues, I wonder if you could look into it and review. :)

**Comment by AnthonyLatsis** [comment]
Superseded by #75163.

**Pull request closed without merging**
