### PR TITLE
[silgen] Teach SILGen how to handle a corner case where the clang importer is improperly importing a method with a non-null NSError as throwing

### PR DESCRIPTION
**Pull request by gottesmm**
This has been crashing a long time and has never been correct. From an API perspective, the clang importer should have not been importing these methods as throwing. Sadly, today, we need to preserve source compatibility, so in this PR I teach SILGen how to handle this case by passing a nullptr to the non-null API. With time (maybe swift 6), we will be able to eliminate this. I filed rdar://94656178 to track that.

rdar://92755102

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Review by jckarter — APPROVED** [review]
Makes sense for now. Thanks Michael!

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Pull request merged**
