### PR TITLE
[ownership] Update SROA to support OSSA.

### PR DESCRIPTION
**Pull request by gottesmm**
Use destructure to chop up allocations. Other than that, just add
correct load/store qualifiers.

-----

Patch by @zoecarver.

### CODE REVIEW

**Comment by gottesmm** [comment]
Lets see how this looks.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by zoecarver** [comment]
@swift-ci please test OS X platform.

**Comment by zoecarver** [comment]
@swift-ci please test OS X Platform

**Comment by zoecarver** [comment]
Error with Jenkins, not because of this patch.

**Pull request merged**
