### PR TITLE
Fix for missing conformance with id-as-Any bridging

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test os x

**Comment by slavapestov** [comment]
@swift-ci Please smoke test os x

**Comment by slavapestov** [comment]
@swift-ci Please smoke test os x

**Comment by tkremenek** [comment]
@swift-ci test os x

**Comment by tkremenek** [comment]
@swift-ci test os x platform

**Comment by slavapestov** [comment]
@swift-ci Please smoke test os x

**Comment by slavapestov** [comment]
@swift-ci Please smoke test os x

**Pull request merged**
