### PR TITLE
[Docs] Create ContributionStarterGuide

### PR DESCRIPTION
**Pull request by HassanElDesouky**
This `ContributionStarterGuide.md` aims to be a place where newcomers who want to contribute to Swift can start at. 

In this file, I collected the most important talks and blogs that are related to how to start contributing to Swift. 

Hopefully, this will be the start of a more robust contribution starter guide, and the contribution to Swift won't be as intimidating as it is now.

I previously wrote about this, you can check out my two posts on Swift Forums: 
1. [Important talks and articles for first time Swift Contributors](https://forums.swift.org/t/important-talks-and-articles-for-first-time-swift-contributors/34537?u=hassaneldesouky)
2. [Contribution Starter Guide](https://forums.swift.org/t/contribution-starter-guide/34747)

### CODE REVIEW

**Comment by HassanElDesouky** [comment]
@varungandhi-apple, @theblixguy What do you think?

**Review by theblixguy — COMMENTED** [review]
Haven't looked too deeply but some suggestions:

1. We should also talk about starter bugs as that's what a new contributor would likely start working on first. Also, another way to contribute is by coming up with new ideas or suggestions which can be pitched on the Swift forums.
2. It would be great to link to this podcast as well - https://www.swiftcommunitypodcast.org/episodes/5 as it goes into how one can contribute to Swift.

**Comment by HassanElDesouky** [comment]
Great! I will add them. If you also got any ideas on how to improve this better write a comment here.

**Comment by HassanElDesouky** [comment]
Closing because this has been addressed in PR #32584 by @varungandhi-apple.

**Pull request closed without merging**
