### PR TITLE
[sil-capture-propagation] Support generic partial_apply instructions

### PR DESCRIPTION
**Pull request by swiftix**

### CODE REVIEW

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please smoke benchmark

**Comment by slavapestov** [comment]
Assuming those benchmark results are not lying that's an impressive speedup!

Once partial specialization of generics lands, we should brainstorm how to refactor the closure passes to support partial specialization here as well.

**Comment by swiftix** [comment]
@slavapestov I actually doubt these results. I haven't seen the same numbers locally, IIRC.

**Comment by swiftix** [comment]
@swift-ci please benchmark

**Comment by gparker42** [comment]
Reverted. This broke in CI. 
https://ci.swift.org/job/oss-swift-incremental-RA-osx/8801/

**Comment by gparker42** [comment]
`notifyPassManagerOfFunction` was removed in #8083. You might simply want `notifyAddFunction` now.

**Pull request merged**
