### PR TITLE
[windows] Allow only exe capitalization in tests.

### PR DESCRIPTION
**Pull request by drodriguez**
Clang 8 or 9 seems to have changed from EXE to exe. Allow the new
capitalization (which is not important in Windows).

With these changes, there will still be failures in:

- `IRGen/multithread_module.swift`: Failure during linking.
- `Driver/driver-compile.swift`: An uppercased path is lowercased in the output.
- `Driver/options.swift`: The `swift.exe` driver cannot find a valid stdlib (while `swiftc.exe` can).

### CODE REVIEW

**Comment by drodriguez** [comment]
With https://github.com/apple/swift/pull/27475

@swift-ci please test Windows platform

**Comment by drodriguez** [comment]
I don't think the code is being built with the previous PR, so it will fail building LLDB.

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
FWIW, I'm in favour of just dropping the capital.

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Review by compnerd — APPROVED** [review]
Id prefer the "incompatible" change of using the lower case only.

**Comment by drodriguez** [comment]
@swift-ci please test Windows platform

**Comment by drodriguez** [comment]
@swift-ci please test Windows platform

**Comment by drodriguez** [comment]
@swift-ci please test Windows platform

**Comment by drodriguez** [comment]
From the last Windows testing:

```
Failing Tests (3):
    Swift(windows-x86_64) :: Parse/confusables.swift
    Swift(windows-x86_64) :: IRGen/multithread_module.swift
    Swift(windows-x86_64) :: Driver/driver-compile.swift
```

I was expecting `options.swift` which fails for me locally, and I wasn't expecting `confusables.swift`, which doesn't. I think this can be merged and we can deal with the rest in different PRs as we find solutions.

PD: I also removed the uppercased EXE from the code.

**Comment by drodriguez** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test Linux platform

**Comment by drodriguez** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please smoke test Linux platform

**Pull request merged**
