### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by compnerd**
Split out the TensorFlow CI entries.  They were previously marked with a TensorFlow suffix, which obscured them in the rest of the community CI.  This makes them easier to find.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @rxwei @shahmishal @saeta 

Whats the feeling from you guys on this?  I think that it helps see the current status of the TensorFlow branches and the state of the master branch.

**Comment by rxwei** [comment]
I'm +1 on this idea. Are there other CIs that are set up against a non-master branch?

**Comment by compnerd** [comment]
@rxwei no, I don't think that there are.  @shahmishal is there public CI for the release branches?

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by shahmishal** [comment]
LGTM!

**Pull request merged**
