### PR TITLE
Sema: Move preCheckExpression() into its own file

### PR DESCRIPTION
**Pull request by slavapestov**
No code changes other than the cut-and-paste.

### CODE REVIEW

**Comment by slavapestov** [comment]
Hope this doesn't create merge conflicts with anyone's pending changes.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Review by hborla — APPROVED** [review]

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Pull request merged**
