### PR TITLE
[build] Unify android-arm64 and android-aarch64 in build-script-impl

### PR DESCRIPTION
**Pull request by bulbazord**
cc @compnerd @shahmishal

### CODE REVIEW

**Comment by xiaobai** [comment]
@swift-ci please smoke test

**Review by compnerd — COMMENTED** [review]
Hmm, how could someone even have provided android-arm64 previously and had things work?  Don't most of the paths expect android-aarch64?  Is this dead code?

**Comment by xiaobai** [comment]
@compnerd I'm not entirely sure, but when we validate the host, we expect to see android-aarch66 (and it was that way before I refactored it a few days back). It seems to me like this is probably dead code, but I'm not sure.

**Comment by compnerd** [comment]
Im pretty sure that the line and ~5 lines around it are dead code (both the android cases).  I think that it might be worth just deleting it and doing a quick test.

**Comment by drodriguez** [comment]
It is my fault. I am pretty sure I mistyped this back then.

About the question of dead code, I don't think it is completely, but it might mostly be. This lines is mostly useful for compiling LLVM and CMark, and they are normally needed for cross-compiling. I don't think a lot of people cross-compile targeting Android (they normally target the Swift stdlib, but not the compiler itself, so this doesn't apply). There are efforts of compiling the code in Android targetting Android, but that was skipping this bit because the default target if nothing is specified is the host itself.

I think this can go as is.

**Pull request merged**
