### PR TITLE
[CSApply] Don't try to transform editor placeholder if it's type is invalid

### PR DESCRIPTION
**Pull request by xedin**
CSDiag could re-typecheck closure or other expression which has
editor placeholder inside allowing type variables be bound to unresolved
type, which doesn't really form a valid solution to be applied to AST.
So we need to guard against trying to transform placeholder into a call 
to `_undefined` in such case, otherwise in asserts build it's going to crash
with an assert but in release build it would crash in some other place e.g.
SILGen or trying to type-check captures.

Resolves: rdar://problem/48937223
Resolves: rdar://problem/51599529

### CODE REVIEW

**Review by DougGregor — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please build toolchain

**Comment by shahmishal** [comment]
@swift-ci please test macOS

**Pull request merged**
