### PR TITLE
[Test] Add REQUIRES: executable_test to swift-class-virtual-method-dispatch-execution.cpp.

### PR DESCRIPTION
**Pull request by mikeash**

### CODE REVIEW

**Comment by mikeash** [comment]
@swift-ci please test and merge

**Comment by hyp** [comment]
Ah, sorry I forgot to add it to this specific test :(

**Review by hyp — APPROVED** [review]

**Comment by hyp** [comment]
@mikeash Thank you 🙏

**Comment by mikeash** [comment]
No worries, it's so easy to forget these.

**Comment by hyp** [comment]
updated https://github.com/apple/swift/pull/63572 as well with added REQUIRES to the new test there.

**Pull request merged**
