### PR TITLE
MultiDefPrunedLiveness: add support for arbitrary uses/defs.

### PR DESCRIPTION
**Pull request by atrick**
This now supports liveness holes within blocks where previously we
expected a phi def.

PrunedLiveness is streamlined for SSA liveness where we expect the
defs and uses to be related in the SSA def-use graph.
MultiDefPrunedLiveness was added on top of SSAPrunedLivenes to handle
extended SSA liveness that occurs with phis, but are still connected
in the def-use graph. Recently MultiDefPrunedLiveness was repurposed
for liveness of addressible storage. This means that we can now have
uses before defs in the same block without a corresponding phi.

Fortunately, handling this case is a straightforward extension of
MultiDefPrunedLiveness that does not complicate or penalize the
streamlined SSA case.

Restores PR: MultiDefPrunedLiveness: add support for arbitrary uses/defs. #64625
The CI failure in watchos RemoveWhere.o appears unrelated:
rdar://107341949 (Swift CI: [main, armv7k] benchmark/O-armv7k-apple-watchos2.0/RemoveWhere.o: assert in Control Flow Optimizer)

### CODE REVIEW

**Comment by atrick** [comment]
preset=buildbot_incremental,tools=RA,stdlib=RA
@swift-ci Please test with preset macOS

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci benchmark

**Comment by atrick** [comment]
@swift-ci test source compatibility

**Comment by atrick** [comment]
Building with the incremental preset failed in a SwiftPM test unrelated to this change:
```
    "Test Case '-[CommandsTests.BuildToolTests testAtMainSupport]' failed (21.408 seconds).
Test Suite 'BuildToolTests' failed at 2023-04-05 03:01:29.771.
	 Executed 1 test, with 1 failure (1 unexpected) in 21.408 (21.408) seconds
Test Suite 'SwiftPMPackageTests.xctest' failed at 2023-04-05 03:01:29.772.
	 Executed 1 test, with 1 failure (1 unexpected) in 21.408 (21.408) seconds
Test Suite 'Selected tests' failed at 2023-04-05 03:01:29.772.
	 Executed 1 test, with 1 failure (1 unexpected) in 21.408 (21.408) seconds**** FAILURE EXECUTING SUBPROCESS ****
```

**Comment by atrick** [comment]
Source compat suite fails to build Doggie on main in SILGen. No new failures here.
```
Assertion failed: ((sig && sig->isEqual(subs.getGenericSignature())) || !OrigType || !OrigType->hasTypeParameter()), function withSubstitutions, file AbstractionPattern.h, line 1099.

4.	While silgen emitFunction SIL function "@$s10DoggieCore12MappedBufferV6append10contentsOfyqd___t7ElementQyd__RszSTRd__lF".
 for 'append(contentsOf:)' (at /Users/ec2-user/jenkins/workspace/swift-main-source-compat-suite/swift-source-compat-suite/project_cache/Doggie/Sources/DoggieCore/Foundation/MappedBuffer.swift:270:21)
5.	While silgen emitFunction SIL function "@$s10DoggieCore12MappedBufferV6append10contentsOfyqd___t7ElementQyd__RszSTRd__lF01_E0L_yyqd0__AGRszSTRd__STRd0__AFQyd0__AGRSr___lF".
 for '_append(_:)' (at /Users/ec2-user/jenkins/workspace/swift-main-source-compat-suite/swift-source-compat-suite/project_cache/Doggie/Sources/DoggieCore/Foundation/MappedBuffer.swift:287:9):
    swift-frontend           0x00000001092cc793 swift::Lowering::AbstractionPattern::withSubstitutions(swift::SubstitutionMap) con
```

**Review by nate-chandler — APPROVED** [review]
LGTM

**Pull request merged**
