### PR TITLE
Don't include asl.h when SWIFT_STDLIB_HAS_ASL is not set

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test Windows to platform

**Comment by kubamracek** [comment]
@swift-ci please test Windows platform

**Review by compnerd — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please test windows platform

**Pull request merged**
