### PR TITLE
[DCE] Don't complete lifetimes of erased values.

### PR DESCRIPTION
**Pull request by nate-chandler**
DCE may enqueue a value for lifetime completion and later on erase the instruction that defines that value.  When erasing an instruction, erase each of its results from the collection of values to complete.

rdar://141560546

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Review by eeckstein — APPROVED** [review]
lgtm

**Pull request merged**
