### PR TITLE
[stdlib] Minor refactor of StrideThroughGenerator.next()

### PR DESCRIPTION
**Pull request by PatrickPijnappel**
#### What's in this pull request?

- Move a branch away from the main path.
- Add a clarifying comment.
- Clarify a variable name.

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by CodaFi** [comment]
@PatrickPijnappel If these changes are still needed, could you please

1) Rebase onto master
2) Squash them down into 1 commit
3) Move your changes into the new Stride.swift.gyb

**Comment by moiseev** [comment]
Added some tests for the past-the-end behavior: https://github.com/apple/swift/pull/3362
@PatrickPijnappel please update the tests, if you feel the problem is not covered there, and the code still needs to be changed.

**Comment by PatrickPijnappel** [comment]
@CodaFi I redid the changes as a new PR: #3375

@moiseev While it was not in my original PR, it'd be good to check the following doesn't crash:
```swift
stride(from: UInt8(0), through: UInt8(255), by: UInt8(2))
```
I could add them to the new PR.

**Comment by PatrickPijnappel** [comment]
See #3375.

**Pull request closed without merging**
