### PR TITLE
[NFC] Add a short note on what USRs are and what they're used for.

### PR DESCRIPTION
**Pull request by varungandhi-apple**
I didn't know what these were and couldn't find documentation so I figured I'd add some.

(Review from any person will do.)

### CODE REVIEW

**Review by nkcsgexi — APPROVED** [review]
Thank you for adding this!👍

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test and merge

**Comment by varungandhi-apple** [comment]
@swift-ci please test Linux platform

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test Linux

**Pull request merged**
