### PR TITLE
[ConstraintSystem] NFC: Remove `ArgumentInfoCollector` which was part…

### PR DESCRIPTION
**Pull request by xedin**
… of designated operator work

Bits of code which are leftover from https://github.com/apple/swift/pull/34315.

Resolves: rdar://49743448

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please smoke test Windows platform

**Comment by xedin** [comment]
@swift-ci please smoke test Windows platform

**Comment by xedin** [comment]
@shahmishal @compnerd looks like ci-external.swift.org has a problem.

**Review by DougGregor — APPROVED** [review]
Excellent to see more code removals here

**Comment by shahmishal** [comment]
> @shahmishal @compnerd looks like ci-external.swift.org has a problem.

This should be resolved now.

**Comment by xedin** [comment]
@swift-ci please smoke test Windows platform

**Pull request merged**
