### PR TITLE
[TF] Introduce callables.

### PR DESCRIPTION
**Pull request by dan-zheng**
Introduce callables: values that can be "called" like functions.

```swift
struct Adder {
    var base: Int
    call func(_ x: Int) -> Int {
        return base + x
    }
}
let add3 = Adder(base: 3)
add3(10) // 13
```

This is experimental functionality and highly subject to change:
the design will be updated based on feedback for SE-0253.

### CODE REVIEW

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow macOS

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Review by lattner — APPROVED** [review]
The patch looks generally great to me, thank you Dan.  I appreciate that you switched the syntax to the likely result.

For the eventual final patch (not necessary in the 0.3 release) I think it would be better to model this as a normal FuncDecl with a special name.  I don't think it is necessary to have a CallDecl node.

**Review by rxwei — APPROVED** [review]
It'd be nice to change "call member" to "call function" or "call method" in diagnostics.

**Comment by dan-zheng** [comment]
> For the eventual final patch (not necessary in the 0.3 release) I think it would be better to model this as a normal FuncDecl with a special name. I don't think it is necessary to have a CallDecl node.

Yes, switching to a normal `FuncDecl` with a "callable" bit and special name is definitely the direction.

**Comment by dan-zheng** [comment]
> It'd be nice to change "call member" to "call function" or "call method" in diagnostics.

I believe this is already done, please let me know if you found places I missed.

**Pull request merged**
