### PR TITLE
IRGen: Only emit resilient tag numbers for resilient enums

### PR DESCRIPTION
**Pull request by aschwaighofer**
rdar://24057946

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
I’m surprised this wasn’t caught by tests - are you sure this whole check isn’t dead somehow?

**Comment by slavapestov** [comment]
Or can you add IRGen tests ensuring the tag numbers are emitted in the right circumstances?

**Comment by aschwaighofer** [comment]
I will add positive and negative tests for the globals.

Here is my understanding. Before this commit:
The check ``if( isResilient(theEnum, ResilienceExpansion::Maximal)) return;`` -- if this definition is resilient in the local domain was a no-op (as you pointed out) and so we are always emitting globals even for non-resilient enums.

After this commit:
`` if (!isResilient(theEnum, ResilienceExpansion::Minimal))) return`` -- if this definition is not resilient in the minimal expansion then we have a fragile enum for which we should not emit a global. (resilient class thunk emission uses the same test)

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
Oh you’re absolutely right. Thanks for the explanation. Now I see that only negative tests would’ve caught this (or TBD tests actually, since it’s an error to have an IRGen symbol that’s not in the TBD).

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test

**Pull request merged**
