### PR TITLE
[AddressLowering] Shorten stack lifetimes.

### PR DESCRIPTION
**Pull request by nate-chandler**
During storage allocation, create all alloc_stacks at the front of the function entry block, except those for opened existential types.  Do not create any dealloc_stacks, even for opened existential types.

Then, after function rewriting, position the alloc_stacks according to uses, except those for opened existential types.  This means allocating in the block that's the least common ancestor of all uses. At this point, create dealloc_stacks on the dominance frontier of the alloc_stacks, even for allocations for opened existential types.

The behavior for opened existential types diverges from all others in order to maintain SIL validity (as much as possible) while the pass runs.  It would be invalid to create the alloc_stacks for opened existential types at the front of the entry block because the type which is opened is not yet available, but that type's opening must dominate the corresponding alloc_stack.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by atrick — APPROVED** [review]
This is great. My only concern is that, for opened existentials, we create a use-before-def for the duration of the pass until rewriting is complete. This is invalid SIL in a way that doesn't involve argument conventions. That could break verification or utilities, like SSA liveness. It's unlikely to be a problem for a trivial types.

I'll leave it to you to either comment the problem or change the approach.

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
Restored the previous behavior for alloc_stacks of opened existentials: those alloc_stacks will continue to be dominated by the opening while the pass runs, as before.

**Pull request merged**
