### PR TITLE
Update tensorflow revision.

### PR DESCRIPTION
**Pull request by rxwei**
Update tensorflow revision to https://github.com/tensorflow/tensorflow/commit/f1434386225ced4f0f2c3b1b11ab212b4b70690b to use new random ops.

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Review by dan-zheng — APPROVED** [review]

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Pull request closed without merging**
