### PR TITLE
Adjust to simulator compiler-rt change

### PR DESCRIPTION
**Pull request by beccadax**
Previously, we packaged both the device and simulator versions of compiler-rt in a single static archive, relying on the fact that they used different architectures to differentiate between them. But Apple Silicon is now here to make us repay this technical debt. apple/llvm-project#1553 separated the simulator versions of compiler-rt into libraries with different names; this PR adjusts Swift to match.

Fixes rdar://66192830.

### CODE REVIEW

**Comment by brentdax** [comment]
@swift-ci please test

**Comment by brentdax** [comment]
@swift-ci please test macOS platform

**Review by hyp — APPROVED** [review]
LGTM

**Comment by brentdax** [comment]
@swift-ci please test

**Comment by brentdax** [comment]
Failure appears to be the sporadic SR-13302.

@swift-ci please test macOS platform

**Pull request merged**
