### PR TITLE
Revert "[SR-12033] [Sema] Do not allow inferring defaultable closure `() -> $T` for autoclosure arguments result"

### PR DESCRIPTION
**Pull request by xedin**
Reverts apple/swift#35503

@LucianoPAlmeida Unfortunately we have to revert this for now and make it more tailored since these changes caused a source compatibility regression in code like this:

```
protocol P {
  associatedtype F : Error
}

extension P {
  func test(error: F?) {
    accepts_autoclosure({
      if let failure = error {
        throw failure
      }
    })
  }

  func accepts_autoclosure<T>(_ expression: @autoclosure () throws -> T) {}
}
```

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please smoke test Windows platform

**Comment by xedin** [comment]
@swift-ci please smoke test Linux platform

**Comment by xedin** [comment]
@swift-ci please smoke test Linux platform

**Comment by LucianoPAlmeida** [comment]
> @LucianoPAlmeida Unfortunately we have to revert this for now and make it more tailored since these changes caused a source compatibility regression

hum, ok sorry for that and thank you for reverting :))
I'll try to take a look on that to see if we can make an adjustment

**Comment by xedin** [comment]
@LucianoPAlmeida No worries! The fix is correct since otherwise the behavior is not obvious to users it's just the source compatibility impact :/ Could you please open a PR to avoid transitive inference of `DefaultClosureType` removed which used to be a part of this one?

**Comment by LucianoPAlmeida** [comment]
> it's just the source compatibility impact :/

That's unfortunate... do you think its possible to fix this without source compatibility break? 
 
> Could you please open a PR to avoid transitive inference of DefaultClosureType removed which used to be a part of this one?

For sure :)

**Comment by xedin** [comment]
> That's unfortunate... do you think its possible to fix this without source compatibility break?

I don't think so since there are projects which rely on this behavior. What we can do though is to rank solutions with `@autcolosure` lower than solutions where parameters accept regular closures e.g.

```swift
func test<T>(_: () -> T) {}
func test<T>(_: @autoclosure () -> T) {}

test { }
```

This example is ambiguous today but it shouldn't be.

**Comment by LucianoPAlmeida** [comment]
> What we can do though is to rank solutions with @autcolosure lower than solutions where parameters accept regular closures

That makes sense! 
Do we have a JIRA ticket for that already? If not I can create it just to track this

**Comment by xedin** [comment]
We might, it might be worth a search before creating a new one.

**Comment by LucianoPAlmeida** [comment]
> We might, it might be worth a search before creating a new one.

Right, I'll look it up. Thanks!

**Comment by LucianoPAlmeida** [comment]
Found two actually that seems to address the same issue SR-2705  and SR-6725

**Comment by xedin** [comment]
SR-2705 is what we want here.

**Pull request merged**
