### PR TITLE
docs: Migrate from SR issues to GitHub issues

### PR DESCRIPTION
**Pull request by AnthonyLatsis**

### CODE REVIEW

**Review by xedin — APPROVED** [review]
Thank you, looks great!

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Comment by AnthonyLatsis** [comment]
@swift-ci please clean smoke test macOS

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Pull request merged**
