### PR TITLE
Merge 2020-04-29 into tensorflow

### PR DESCRIPTION
**Pull request by saeta**

### CODE REVIEW

**Comment by saeta** [comment]
@swift-ci Please clean test TensorFlow

**Comment by saeta** [comment]
Related merge: https://github.com/apple/llvm-project/pull/1162

**Comment by saeta** [comment]
@swift-ci Please clean test TensorFlow

**Comment by saeta** [comment]
@swift-ci Please clean test TensorFlow

**Review by dan-zheng — APPROVED** [review]
(I only checked `update-checkout-config.json`)

**Pull request merged**
