### PR TITLE
[NFC] Drop PerformJobsState as a friend class

### PR DESCRIPTION
**Pull request by CodaFi**
Make the coupling between PerformJobsState and Compilation indirect and expose some convenient accessors in the process.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Review by jrose-apple — APPROVED** [review]
Huh. It was written this way originally because PerformJobsState was a sort of "fake extension" to Compilation, but I guess it really wasn't that closely tied after all. This seems reasonable to me.

**Comment by CodaFi** [comment]
⛵️

**Comment by davidungar** [comment]
I was surprised that you asked for my review and then merged so quickly before I could get to it. However, it’s a very innocuous change! I like the decoupling.

**Comment by CodaFi** [comment]
@davidungar Sorry about that.  I usually tag all the stakeholders I can think of as a way to cast a wide net rather than gather a list of gates for smaller patches like these.  Thank you for the vote of confidence!

**Comment by davidungar** [comment]
@CodaFi Thanks for responding. In the future if you put me down as a reviewer, if you want me to assume that you specifically want my review, please let me know somehow. Otherwise I'll assume that, as with this PR, you are casting that wide net.

**Pull request merged**
