### PR TITLE
[Concurrency] Only auto-import _Concurrency when auto-importing Swift.

### PR DESCRIPTION
**Pull request by DougGregor**
This allows the standard library to build with concurrency enabled.
Fixes rdar://70700689.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Review by rjmccall — APPROVED** [review]
Oops, LGTM

**Review by ktoso — APPROVED** [review]
Yay :)

**Comment by DougGregor** [comment]
Bah, forgot to update test cases that were missing the explicit import.

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Pull request merged**
