### PR TITLE
 SILGen: Wean SILGenApply off AbstractionPattern::getFunctionInputType()

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Review by jckarter — APPROVED** [review]
Lgtm

**Comment by slavapestov** [comment]
The Debug failure is a non-deterministic issue with associated type inference in the flume package. It’s not related to my patch. I’ll file a bug about it later today.

**Review by rjmccall — COMMENTED** [review]
LGTM.

**Pull request merged**
