### PR TITLE
Minor script tweaks

### PR DESCRIPTION
**Pull request by graydon**
Just a couple mistakes fixed, found while doing perf work last week.

### CODE REVIEW

**Comment by graydon** [comment]
@swift-ci please smoke test

**Review by huonw — COMMENTED** [review]
I don't really understand what either of these scripts are doing, so can't really say much other than that these changes don't seem wrong.

**Comment by graydon** [comment]
@swift-ci please smoke test and merge

**Comment by graydon** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
