### PR TITLE
FloatingPoint.radix should be transparent.

### PR DESCRIPTION
**Pull request by stephentyrone**
Not sure why we missed this one, but there it is.

### CODE REVIEW

**Comment by stephentyrone** [comment]
@swift-ci please smoke test

**Comment by jrose-apple** [comment]
What's the reasoning for making this transparent?

**Comment by stephentyrone** [comment]
> What's the reasoning for making this transparent?

It is occasionally necessary to select between generic algorithms in code that should be compiling down to just a few instructions. Going through a witness table in those cases is catastrophic.

**Review by lorentey — APPROVED** [review]

**Comment by jrose-apple** [comment]
FWIW, `_transparent` won't actually help you in a generic context, but okay.

**Comment by stephentyrone** [comment]
> FWIW, `_transparent` won't actually help you in a generic context, but okay.

It will still help when the compiler can specialize a generic function.

**Comment by jrose-apple** [comment]
Yes, but `@inlinable` (possibly with `@inline(__always)`) will do that too.

**Comment by stephentyrone** [comment]
`@inlinable` is definitely not sufficient on its own. `@inlinable` + `@inline(__always)` may be;

**Comment by stephentyrone** [comment]
@swift-ci please smoke test

**Pull request merged**
