### PR TITLE
Parser: Highlight 'self' and 'Self' correctly when allowed to be an identifier

### PR DESCRIPTION
**Pull request by AnthonyLatsis**

### CODE REVIEW

**Comment by rintaro** [comment]
Could you clarify the motivation for this patch? What's the issue?

**Comment by AnthonyLatsis** [comment]
The parser allows to declare generic parameters and certain bindings named  `self` or `Self` without having to escape them, but was not promoting these to identifier tokens. For example, `Self` in `struct G<Self>` is highlighted as a keyword.

**Comment by rintaro** [comment]
I see. But I think this change affects too broad. For example:
```swift
struct S {
  func foo() {
    self.foo()
  }
}
```
This `self` should be parsed as a keyword but it uses `consumeIdentifier()`.

**Comment by rintaro** [comment]
Also
```swift
struct S<Self> {
  func foo() -> Self {
    Self
  }
}
```
The parser doesn't know these `Self` in the function mean whether the current type (keyword) or the generic parameter. It's semantic thing. So I feel like, for syntax coloring, we should keep parse them as keywords.

**Comment by AnthonyLatsis** [comment]
> I see. But I think this change affects too broad

Right, I was careless, glad you noticed!

> The parser doesn't know these Self in the function mean whether the current type (keyword) or the generic parameter. It's semantic thing. So I feel like, for syntax coloring, we should keep parse them as keywords.

Yes, the intention was to fix syntax coloring only for identifiers that are known to be declarations (just the generic parameter in your example).

**Comment by AnthonyLatsis** [comment]
After a closer look, the rules on whether something is allowed to be declared `self` or `Self` seem rather sketchy. Sometimes the parser lets these identifiers through only to fail the expectations of Sema. I doubt there currently is any value in landing the intended fix, so closing this off.

**Pull request closed without merging**
