### PR TITLE
SIL: Profile the witnesMethodConformance as part of the SILFunctionType

### PR DESCRIPTION
**Pull request by aschwaighofer**
We use to return a SILFunctionType with a wrong witness method protocol
conformance e.g when there were base protocols.

rdar://40149340

### CODE REVIEW

**Review by rjmccall — APPROVED** [review]
Oh, wow.  Yeah, that would definitely explain the problems here.

**Comment by rjmccall** [comment]
This is possibly something we should pull into 4.2, since we do rely on this information already (albeit in more constrained contexts, but I can't see why it wouldn't equally cause problems for them; maybe things just happen to always line up right because of the narrowness of how the conformance is used?).  @slavapestov might have thoughts about that.

**Comment by aschwaighofer** [comment]
4.2 branch here: https://github.com/apple/swift/pull/19464

**Comment by aschwaighofer** [comment]
@swift-ci Please test macos

**Pull request merged**
