### PR TITLE
[stdlib] fix an indexing inconsistency

### PR DESCRIPTION
**Pull request by glessard**
This iteration ranged from `buffer.startIndex` until `buffer.count`, rather than `buffer.endIndex`.
The latter is more coherent with the indexing model, even though the former happens to work.

No SR.

### CODE REVIEW

**Comment by glessard** [comment]
@swift-ci please smoke test

**Comment by glessard** [comment]
@swift-ci please benchmark

**Comment by glessard** [comment]
@swift-ci please smoke test

**Review by lorentey — APPROVED** [review]
What a weird way to spell a range 👍

**Pull request merged**
