### PR TITLE
Adapt to LLVM change r293359

### PR DESCRIPTION
**Pull request by aschwaighofer**
Only define dump method's if llvm has defined the depend dump methods.

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test and merge

**Comment by bob-wilson** [comment]
Oh wait. Was this already fixed for master-next?

**Comment by aschwaighofer** [comment]
@bob-wilson I don't understand. Building swift is currently broke building with ToT swift (and the right combination of options: NinjaRelease).
Are you suggesting there is a branch that already has a similar fix in?

**Comment by aschwaighofer** [comment]
@bob-wilson I mean the build is broken with a swift/master and llvm/stable checkout.

**Comment by bob-wilson** [comment]
I don't see any changes like this on master-next and yet it is currently building successfully (https://ci.swift.org/view/swift-master-next/job/oss-swift-incremental-RA-osx-master-next-upstream-with-swift/). That is building against trunk LLVM.  Maybe it only fails with a Release build and our bot is testing a Debug build?

**Comment by aschwaighofer** [comment]
It fails if you build with: ./swift/utils/build-script --release --no-assertions

**Comment by aschwaighofer** [comment]
The bot is testing: swift/utils/build-script --preset=buildbot_incremental,tools=RA,stdlib=RA

I assume the RA part translates to --release --assertions

**Comment by aschwaighofer** [comment]
Yes:

[preset: buildbot_incremental,tools=RA,stdlib=RA]
mixin-preset=buildbot_incremental_base_all_platforms

build-subdir=buildbot_incremental

# Build Release without debug info, because it is faster to build.
release
assertions

**Comment by bob-wilson** [comment]
Ah, OK. That makes sense. Thanks.

**Pull request merged**
