### PR TITLE
[String] Internalize and drop some inlinable annotations

### PR DESCRIPTION
**Pull request by milseman**
Attempt to internalize and drop some `@inlinable` annotations. PR up to see effects.

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please smoke benchmark

**Comment by milseman** [comment]
Drat, we'd really really like to not make `StringStorage.create` `@inlinable`. I'll try some tweaks.

**Comment by milseman** [comment]
Ugh, the sole difference seems to be that `+=` used to be inlined and now isn't, and that stops a whole cascade of optimizations. I'll poke around more.

**Comment by milseman** [comment]
@swift-ci please smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci please smoke benchmark

**Comment by gottesmm** [comment]
(just doing a drive by swift-ci invocation since it wasn't running).

**Comment by milseman** [comment]
StringUTF16SubstringBuilder regression seems real (I see ~5%), but I'm getting a lot of variability. Others don't really reproduce for me.

**Comment by milseman** [comment]
@swift-ci please smoke test compiler performance

**Comment by milseman** [comment]
Rather than leave this long-running and pile more on, better to merge sooner. Adjusted commit message only.

@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please test

**Pull request merged**
