### PR TITLE
ASTScope: Remove "re-expansion" mechanism

### PR DESCRIPTION
**Pull request by slavapestov**
The subset of the AST that participates in unqualified lookup should be effectively immutable. Delayed parsing can fill in members of nominal types and extensions, as well as function bodies, but since we lazily expand scopes, and the relevant getter methods on IterableDeclContext and AbstractFunctionBody trigger parsing, ASTScope should always see a consistent view of the world.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Review by davidungar — CHANGES_REQUESTED** [review]
I would rather keep the member count and put in an assertion as we discussed. The member count would only count explicit members. Otherwise, my feeling is that this change introduces more fragility than my comfort level.

**Comment by slavapestov** [comment]
@davidungar I'm planning on switching the call to getMembers() to use getParsedMembers() instead. This evaluates a request which produces a once-allocated ArrayRef which is guaranteed to never change.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Pull request merged**
