### PR TITLE
Sema: Remove SwiftUI type witness matching compatibility hack

### PR DESCRIPTION
**Pull request by slavapestov**
Now that rdar://problem/91451771 is fixed, SwiftUI.swiftinterface should build
without this hack.

### CODE REVIEW

**Review by AnthonyLatsis — APPROVED** [review]
No way! Big thanks to the SwiftUI folks!

**Comment by AnthonyLatsis** [comment]
@slavapestov Are we waiting for something?

**Comment by AnthonyLatsis** [comment]
@slavapestov Any updates on this? What are we waiting for?

**Comment by slavapestov** [comment]
@AnthonyLatsis The hack is now disabled on main, except when building swiftinterface files. We need to keep it around a while longer since swiftinterface files generated by older compilers don't have all the right synthesized typealiases.

**Comment by AnthonyLatsis** [comment]
I see, except, what’s a scenario where a newer compiler operates on a SwiftUI swiftinterface file generated by an older compiler? An Xcode release running a development snapshot?

**Comment by AnthonyLatsis** [comment]
CI is now using Xcode 14.2. I suppose we are ready to proceed?

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test macOS

**Comment by slavapestov** [comment]
@swift-ci please smoke test macOS

**Comment by slavapestov** [comment]
Ok, CI is _still_ on 14.2. Bug is fixed in 14.3

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Comment by slavapestov** [comment]
@swift-ci please smoke test

**Comment by slavapestov** [comment]
@swift-ci please test source compatibility

**Pull request merged**
