### PR TITLE
[string] Force specialization for small Character

### PR DESCRIPTION
**Pull request by milseman**
Until we can sort out Character's small storage, specialize based on it. Worth about 20% on StringEdits.

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please smoke test

**Comment by milseman** [comment]
@swift-ci please smoke benchmark

**Comment by lorentey** [comment]
@milseman If this was inside an external package, I would have just added an overload for append and live with the code duplication. (I think we never append a small character from a generic context.) But `@_specialize` seems more sensible if the implementation would be the same.

**Comment by milseman** [comment]
`@_specialize` is not quite the same, as it does a metatype comparison and jump to the specialized version. Static overload resolution is better.

**Pull request merged**
