### PR TITLE
SILGen: Stop using CaptureKind::StorageAddress in noescape closures

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
I suspect the AllocBoxToStack SIL pass should already be handling this. If we really don't need this in SILGen we can remove some code elsewhere.

**Comment by slavapestov** [comment]
@swift-ci Please benchmark

**Comment by slavapestov** [comment]
cc @gottesmm

**Comment by atrick** [comment]
All diagnostics related to noescape closures happen before AllocBoxToStack. There are some nasty dependencies and assumptions between passes that analyze, diagnose, and optimize closures. In fact,  the diagnostics that you just added to the mandatory pipeline are completely dependent on SILGen's ability to do this; am I wrong?

**Comment by slavapestov** [comment]
@atrick This is not about diagnostics, the goal here is to stop using inout_aliasable except for captures of inout parameters.

**Comment by atrick** [comment]
@slavapestov right, if this is only about address-only types being passed to escaping closures, then it seems orthogonal to diagnostics and something we should get rid of, either by rewriting the closure optimizations or turning on opaque SIL values. My personal priority would be turning on opaque SIL values.

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
