### PR TITLE
[update-checkout] Add swift-crypto to the list of repos

### PR DESCRIPTION
**Pull request by yim-lee**
This is for https://github.com/apple/swift-package-manager/pull/3202, which adds swift-crypto as a new dependency to SwiftPM to support the upcoming package collection feature.

### CODE REVIEW

**Comment by yim-lee** [comment]
@neonichu @shahmishal @tomerd

**Comment by yim-lee** [comment]
@swift-ci test

**Comment by neonichu** [comment]
We should also add a version to check out, I think otherwise we'll check out `main`. Similar to https://github.com/apple/swift/blob/main/utils/update_checkout/update-checkout-config.json#L66

**Comment by yim-lee** [comment]
Thanks @neonichu. I suppose we will need a swift-crypto version with CMake first...on it.

**Comment by yim-lee** [comment]
Use `main` branch for now so we can test changes in SwiftPM. We will pin to version later.

@swift-ci test

**Comment by yim-lee** [comment]
@swift-ci test

**Review by tomerd — APPROVED** [review]

**Review by shahmishal — APPROVED** [review]

**Comment by shahmishal** [comment]
```
01:50:29.227 ********************
01:50:29.227 Failed Tests (1):
01:50:29.227   lldb-api :: lang/swift/completion/TestSwiftREPLCompletion.py
```
cc: @JDevlieghere

**Comment by shahmishal** [comment]
@swift-ci test linux

**Comment by yim-lee** [comment]
@shahmishal Can you please merge this? I don't have the permissions to do so. Thanks.

**Pull request merged**
