### PR TITLE
[Python] Improve Python consistency: "variable in function should be lowercase" (N806)

### PR DESCRIPTION
**Pull request by practicalswift**
#### What's in this pull request?

_Background_

See discussion with @modocache and @nadavrot in #1369.

This is PR is part 3 of 3 in the series of PRs covering the Python naming consistency fixes discussed in #1369.

The previous parts were:
- Part 1. `argument_name`, see #1374 
- Part 2. `function_name(…)`, see #1399

_Rationale_

The repo contains roughly 80 Python scripts. `snake_case` naming is used for local variables in all those scripts. This is the form recommended by the PEP 8 naming recommendations (Python Software Foundation) and typically associated with idiomatic Python code.

However, in 11 of the 80 scripts there were at least one instance of `camelCase` naming prior to this commit.

This commit improves consistency in the Python code base by making sure that these eleven remaining files also follow the variable naming convention used for Python code in the project.

_References_
- PEP 8: https://www.python.org/dev/peps/pep-0008/
- pep8-naming: https://pypi.python.org/pypi/pep8-naming
#### Resolved bug number: –

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by practicalswift** [comment]
@modocache Do you have time to review? That would be appreciated! :-)

**Comment by modocache** [comment]
Looks good to me, based on a quick scan through the source files. I'd merge this if CI passes! :100:

**Comment by modocache** [comment]
@swift-ci please test

**Comment by practicalswift** [comment]
@modocache Thanks! Unfortunately I don't think commit access is a sufficient condition for triggering @swift-ci :-)   Seems like these commands can only be issued by Apple employees at the moment.

**Comment by trentxintong** [comment]
@swift-ci Please test

**Comment by modocache** [comment]
@practicalswift Yeah, I type in "@swift-ci please test" as a sort of bat signal for Apple org members to trigger CI for me. :joy: Thanks, @trentxintong!

**Comment by jckarter** [comment]
@jckarter please swift-ci

**Comment by modocache** [comment]
Thanks, @practicalswift! :100: 

(Aside: I wish more of the Python code in `utils` was tested as part of the validation tests, like `utils/swift_build_support` is.)

**Pull request merged**
