### PR TITLE
[stdlib] Add pattern matching prototype

### PR DESCRIPTION
**Pull request by dabrahams**

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please smoke test and merge

**Comment by dabrahams** [comment]
@swift-ci Please smoke test and merge

**Comment by shahmishal** [comment]
@swift-ci Please smoke test and merge

**Comment by shahmishal** [comment]
@swift-ci Please smoke test and merge

**Comment by dabrahams** [comment]
@swift-ci Please smoke test OS X platform

**Comment by dabrahams** [comment]
@swift-ci Please smoke test OS X platform

**Comment by dabrahams** [comment]
@swift-ci Please smoke test and merge

**Pull request merged**
