### PR TITLE
Bump the CMake version to v3.30.2

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci build toolchain

**Comment by shahmishal** [comment]
@swift-ci test

**Review by justice-adams-apple — APPROVED** [review]

**Review by etcwilde — APPROVED** [review]

**Comment by finagolfin** [comment]
Looks like a bug in one of the linux rpaths; I've also [seen an issue with CMake 3.30 when cross-compiling Foundation](https://github.com/swiftlang/swift-foundation/pull/878#issuecomment-2365493005), had to work around it by [disabling these Android linker flags](https://github.com/finagolfin/swift-android-sdk/blob/5a80b4733c097b53befe867e7fd2a65c4b2791d4/swift-android.patch#L56).

**Comment by shahmishal** [comment]
https://github.com/swiftlang/swift-testing/pull/792
@swift-ci build toolchain Linux

**Comment by shahmishal** [comment]
https://github.com/swiftlang/swift-testing/pull/792

@swift-ci test linux

**Pull request merged**
