### PR TITLE
5.9: [IRGen] Dealloc on-stack metadata/wtable packs on the dominance frontier.

### PR DESCRIPTION
**Pull request by nate-chandler**
Description: After https://github.com/apple/swift/pull/66341 , packs of metadata/wtables are always heap allocated.  As an optimization, skip this heapification when possible.

Do this by inserting marker instructions in a new SIL pass that runs just before IRGen.  This pass' first step is to look for instructions which _might_ result in packs of metadata/wtables being allocated.  If no such instructions are found, the pass makes no changes.  If any are found, allocation marker instructions are inserted just before each such instruction and then at deallocation marker instructions are inserted its dominance frontier.  Finally stack nesting is fixed up.

In IRGen, when each such instruction is lowered, the packs allocated on the stack during that process are recorded.  Those packs are then associated with the prior allocation marker instruction.  Finally, when lowering the corresponding deallocation marker instructions, the recorded packs corresponding to the allocations are cleaned up.
Risk: Medium.  This adds a brand new lowering pass that runs on every function.  On the other hand, the pass will bail out if it is determined that no packs of metadata/wtables might be allocated.
Scope: Medium.  The pass only affects functions which are predicted to result in pack allocation.
Original: https://github.com/apple/swift/pull/66201
Reviewed By: Arnold Schwaigofer ( @aschwaighofer )
Testing: Added tests for the new pass and for the IRGen behavior changes.
Resolves: rdar://110268881

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by tbkka — APPROVED** [review]

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Pull request merged**
