### PR TITLE
[Parse] Fix nested ifConfig compiler checks

### PR DESCRIPTION
**Pull request by kabiroberai**
The parser is supposed to avoid looking inside unmatched `#if compiler` (et al) blocks. This usually means that the following code builds fine

```swift
#if compiler(>=100)
foo bar
#endif
```

however, a logical bug meant that if the check was nested inside an already-inactive `#if` block, it would not adhere to this evaluation-skipping behavior
```swift
#if false
#if compiler(>=100)
foo bar // error!
#endif
#endif
```

This PR fixes this specific case.

### CODE REVIEW

**Comment by kabiroberai** [comment]
I'm unsure if this fix needs to be ported to SwiftSyntax as well — I couldn't find the "skip parsing unmatched compiler checks" logic there. If it exists, could someone please point me to it?

**Comment by rintaro** [comment]
The change looks good to me. Thanks!
@kabiroberai Could you squash the change and add relevant commit message? Or I if you write it here, I can squash and add the comment when merging.

**Comment by kabiroberai** [comment]
@rintaro feel free to use the issue title: "[Parse] Fix nested ifConfig compiler checks". Thanks!

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
OK, but I hope to put more explanation in the comment. 
Let's just use the description:
```
[Parse] Fix nested ifConfig compiler checks

The parser is supposed to avoid looking inside unmatched `#if` compiler (et al) blocks.
This usually means that the following code builds fine

  #if compiler(>=100)
  foo bar
  #endif
  
however, a logical bug meant that if the check was nested inside an already-inactive
`#if` block, it would not adhere to this evaluation-skipping behavior

  #if false
  #if compiler(>=100)
  foo bar // error!
  #endif
  #endif
  
This PR fixes this specific case.
```

**Review by rintaro — APPROVED** [review]

**Pull request merged**
