### PR TITLE
[cxx-interop] Refer to `SwiftBridging` module from `usr/include/module.modulemap`

### PR DESCRIPTION
**Pull request by egorzhdan**
The recent Clang compiler change makes `-fno-modulemap-allow-subdirectory-search` the default behavior. This means that projects that use C++ interop and `#include <swift/bridging>` no longer compile, since Clang won't search for the SwiftBridging module under `usr/include/swift` anymore.

This change adds a new modulemap file to be installed at `toolchain/usr/include/module.modulemap`. This modulemap is under a default Clang include search path, which will make sure Clang can discover the SwiftBridging module.

rdar://123334601

### CODE REVIEW

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please test

**Comment by egorzhdan** [comment]
@swift-ci please build toolchain macOS

**Comment by vsapsai** [comment]
For the record, upon seeing `#include <swift/bridging>` clang would check "swift/module.modulemap" and then "swift/../module.modulemap". I don't think it is a performance problem, just wanted to share some details how "swift/bridging.modulemap" is processed.

By the way, this approach works with a test project too.

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please test

**Comment by egorzhdan** [comment]
@swift-ci please build toolchain macOS

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please test

**Comment by egorzhdan** [comment]
@swift-ci please build toolchain macOS

**Comment by egorzhdan** [comment]
https://github.com/apple/swift-installer-scripts/pull/282

@swift-ci please build toolchain Windows platform

**Comment by egorzhdan** [comment]
@swift-ci please test macOS

**Pull request merged**
