### PR TITLE
Add #ifndef NDEBUG around assert() calls that use helper functions/variables that are also under #ifndef NDEBUG

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Review by compnerd — COMMENTED** [review]
I think that this deserves a better commit message.  `assert` will compile out to nothing to `NDEBUG`, it took me a minute to realize that this was to avoid a warning.

**Review by al45tair — COMMENTED** [review]
This shouldn't be necessary. Per C99 §7.2.1.1.1:

> If `NDEBUG` is defined as a macro name at the point in the source file where `<assert.h>` is included, the `assert` macro is defined simply as
> ```
> #define assert(ignore) ((void)0)
> ```
So the compiler should never see the contents of the `assert()` in that case.

**Comment by kubamracek** [comment]
So actually the reason for this change is to support standard-non-conforming implementations of assert() that are not actually completely ifdef'd out when NDEBUG is set, in other words, the code inside an assert() must still be valid even when NDEBUG is set. Given that, @al45tair, would this change be okay?

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
I expect this to re-break regularly since most people will be building with a conforming `assert`. Is it possible to change this to always check the validity of the assert condition? That might require changing the code to call something other than `assert`, which could be annoying.

**Comment by kubamracek** [comment]
Agree with that. How about I try to address that in some principled way the *next time* we see a breakage? I'm trying to judge how much effort is worth putting into this, as it's not clear if the value outweigh the annoying-ness of changing all asserts in the codebase...

(The good part is that if the breakage happens, it'll be a very obvious compile-time failure, not some subtle misbehavior.)

**Comment by mikeash** [comment]
That sounds fine to me, no rush to fix this until the breakage becomes painful enough to motivate it.

**Review by mikeash — APPROVED** [review]

**Pull request merged**
