### PR TITLE
Diagnose an invalid use of non-polymorphic constructors

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes <rdar://problem/21991470>, <https://bugs.swift.org/browse/SR-5022>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
Seems like we'd need to downgrade this to a warning in Swift 4 mode.

**Comment by jrose-apple** [comment]
This is becoming a bigger change than the one just limited to `lazy`. Definitely needs a re-review by Slava.

@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test compiler performance

**Comment by jrose-apple** [comment]
Aw, shoot, wrong PR. Sorry, Slava.

**Comment by slavapestov** [comment]
@jrose-apple Here is a reduced version of the example from SILGen/protocol_extensions.swift:

```
import Foundation
  
class ObjCInitClass {
  @objc init(s: String) { self.x = s }

  var x: String
}

protocol ProtoDelegatesToObjC { }

extension ProtoDelegatesToObjC where Self : ObjCInitClass {
  init(string: String) {
    self.init(s: string)
  }
}

class X : ObjCInitClass, ProtoDelegatesToObjC {}

print(X(string: "hello world"))
```

The code compiles successfully with asserts off but the print() prints out a metatype and not an instance as expected. So it's just encountering undefined behavior. If I remove the @objc, I get a bus error instead. I don't think keeping this as a warning is a good idea, since there's no vtable entry for the initializer in this case and it's unlikely anyone is relying on this with good results.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by jrose-apple** [comment]
Hm, okay, fair enough.

**Pull request merged**
