### PR TITLE
NFC: Clean up term "parameter aggregate" and use "parameter group" in the infra

### PR DESCRIPTION
**Pull request by rxwei**
Addresses remaining comments in https://github.com/apple/swift/pull/19791.

### CODE REVIEW

**Review by dan-zheng — APPROVED** [review]

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux CPU

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux CPU

**Comment by rxwei** [comment]
@swift-ci please test tensorflow macOS

**Comment by rxwei** [comment]
@swift-ci please test tensorflow macOS

**Comment by rxwei** [comment]
@swift-ci please test tensorflow macOS

**Pull request merged**
