### PR TITLE
fix Result flatMapError remark

### PR DESCRIPTION
**Pull request by wonhee009**
I changed the return description in the flatmap method comment because it was wrong.

### CODE REVIEW

**Comment by wonhee009** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
Thanks!

@swift-ci smoke test and merge

**Comment by wonhee009** [comment]
@swift-ci Please smoke test

**Comment by xwu** [comment]
@swift-ci smoke test macOS platform

**Pull request merged**
