### PR TITLE
IRGen: Correctly indicate non-key same-typed generic parameters.

### PR DESCRIPTION
**Pull request by jckarter**
The correct query here is whether the generic parameter is canonical within its generic signature, not whether it's concrete.

(Note that this includes the patches from https://github.com/apple/swift/pull/15960, since without that fix this ends up crashing in IRGen elsewhere.)

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test source compatibility

**Review by DougGregor — APPROVED** [review]

**Comment by slavapestov** [comment]
Looks good, but an execution test would be nice too!

**Comment by jckarter** [comment]
@slavapestov I've got an execution test coming along with the bug I'm really trying to fix.

**Pull request merged**
