### PR TITLE
[benchmark] SR-4572 Remove jinja2 dependency from test harness generation

### PR DESCRIPTION
**Pull request by palimondo**
I've replaced jinja2 with GYB, as requested by @dabrahams in review of #8641

Resolves [SR-4572](https://bugs.swift.org/browse/SR-4572).

### CODE REVIEW

**Comment by palimondo** [comment]
I'm thinking about reducing those 3 methods for adding test in main.swift to one with the appropriate list parameter…

**Comment by palimondo** [comment]
Please review.

@swift-ci Please benchmark

**Comment by slavapestov** [comment]
@swift-ci Please benchmark

**Comment by CodaFi** [comment]
@swift-ci Please benchmark

**Comment by slavapestov** [comment]
@palimondo You need commit access to request CI. Once you've got a few PRs merged you can ask for commit access (email code-owners@swift.org with your github username and a list of five merged PRs).

**Comment by slavapestov** [comment]
Looks good to me if the benchmark suite completes without error.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by palimondo** [comment]
@slavapestov Please merge?

**Comment by palimondo** [comment]
Thank you @slavapestov !

**Pull request merged**
