### PR TITLE
[CodeComplete] Fall back to typechecking a single expression result builder doesn't typecheck

### PR DESCRIPTION
**Pull request by ahoppen**
If a result builder body fails to typecheck, we currently don't provide any code completion results at all. Instead, try to recover by type checking the expression in the result builder that contains the code completion token, on its own. 

I know this is a bit of a hack and that we might be missing some information about contextual types, but IMHO this is preferable than not providing any results at all.

Resolves rdar://78015510

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please SourceKit Stress Test

**Review by xedin — COMMENTED** [review]
Makes sense to me! You might want to mark the comment as a `FIXME:` though since the fix here would be to partially resolve result builder bodies to preserve contextual information for code completion, which is a much bigger change on a type-checker side...

**Comment by ahoppen** [comment]
Verified that there is no performance regression in code completion using the stress tester’s performance measurement capabilities.

@xedin Good idea. I changed the comment slightly.

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by rintaro — APPROVED** [review]
Thank you!

**Pull request merged**
