### PR TITLE
[Frontend][NFC] Formalize isModuleExternallyConsumed

### PR DESCRIPTION
**Pull request by CodaFi**
Yank this parameter and document the historical scope creep of this value.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci test Linux

**Review by davidungar — APPROVED** [review]
Looks very nice, especially the "why" comments!

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci test Windows

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
