### PR TITLE
[5.9] Enable macros on Windows

### PR DESCRIPTION
**Pull request by bnbarham**
Use WiX to extract a future toolchain to allow building the macros support when building the toolchain. We build swift-syntax and now wire that into the build itself.

### CODE REVIEW

**Comment by bnbarham** [comment]
https://github.com/apple/swift-installer-scripts/pull/246

@swift-ci please build toolchain windows platform

**Comment by bnbarham** [comment]
https://github.com/apple/llvm-project/pull/7513
https://github.com/apple/swift-installer-scripts/pull/246

@swift-ci please build toolchain windows platform

**Review by tristanlabelle — APPROVED** [review]

**Comment by tristanlabelle** [comment]
The tests failures seem to be what I was fixing in https://github.com/apple/swift/pull/68124 . Unfortunately the conclusion from that PR was that the approach was not the right one. I'm working on implementing a better fix now (wrapping the virtual filesystem on Windows to enforce drive preservation). I can code it in the Swift repo to unblock things faster, but ideally it would go into LLVM.

**Comment by bnbarham** [comment]
> The tests failures seem to be what I was fixing in https://github.com/apple/swift/pull/68124

I assume that implies that the substitution isn't happening on `main`, in which case I don't think we should be doing it on 5.9. And indeed that does seem to be the case - https://github.com/apple/swift/blob/main/utils/build-windows-toolchain.bat#L16.

IIUC @compnerd included it thinking it may fix some foundation test failures, but it doesn't look like we're ready to include in 5.9. So maybe the best path forward is removing the substitution and then working out the foundation failures?

**Comment by tristanlabelle** [comment]
I'm also uneasy with having the drive substitution only in 5.9 if it's causing test regressions. I would rather have time to fix those on main. Let's see what comes out of https://github.com/apple/swift/pull/68743 but if I recall, the problem there was that we had one path that reached MAX_PATH by one or two characters :/

**Comment by bnbarham** [comment]
> the problem there was that we had one path that reached MAX_PATH by one or two characters :/

😭 

If that's a test path, maybe we can just update the name. Shall see soon!

**Pull request closed without merging**
