### PR TITLE
[build-script-presets] Build llvm backends required to run lldb test

### PR DESCRIPTION
**Pull request by dcci**
<rdar://problem/42920398>

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by dcci** [comment]
@swift-ci please smoke test

**Comment by dcci** [comment]
@shahmishal let's see how long this takes.

**Comment by shahmishal** [comment]
@swift-ci please clean smoke test macOS

**Review by shahmishal — APPROVED** [review]
LGTM!

**Pull request merged**
