### PR TITLE
SILOptimizer: Remove 'unique ID' from FSO mangling

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@rajbarik Please take a look

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Comment by slavapestov** [comment]
Linux test failed at the very end — this is an lldb problem, not me:

[TestSwiftTupleTypes.py FAILED]

**Comment by rajbarik** [comment]
@slavapestov @atrick I am running into naming troubles with this kind of naming that does not include IDs. For my existential2generic transformation, I get an assertion failure [with name existing] when building swiftpm. Does it make sense to revert this one back? Are there other work arounds?

**Pull request merged**
