### PR TITLE
[Build System: CMake] Move the Compatibility libraries into stdlib/toolchain.

### PR DESCRIPTION
**Pull request by Rostepher**
This PR moves the Compatibility libraries from `stdlib/public` into `stdlib/toolchain`.

rdar://52351019

### CODE REVIEW

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by Rostepher** [comment]
@swift-ci please build toolchain macOS Platform

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by Rostepher** [comment]
@swift-ci please build toolchain macOS Platform

**Comment by Rostepher** [comment]
@swift-ci please test macOS Platform

**Comment by Rostepher** [comment]
@swift-ci please build toolchain macOS Platform

**Review by jckarter — APPROVED** [review]

**Comment by Rostepher** [comment]
I'll make a 5.1 PR in just a few.

**Pull request merged**
