### PR TITLE
DNM: toolchain build

### PR DESCRIPTION
**Pull request by compnerd**

### CODE REVIEW

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/258

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/259

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/242

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/265

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/267

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/267

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/270

@swift-ci please build toolchain Windows platform

**Comment by shahmishal** [comment]
Is it ok if we close this PR?

**Pull request closed without merging**
