### PR TITLE
Revert Clang types in SIL patch

### PR DESCRIPTION
**Pull request by varungandhi-apple**
Still keeping some printing changes so that LLDB doesn't break.

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test

**Review by eeckstein — APPROVED** [review]
Thanks!

**Comment by varungandhi-apple** [comment]
Fixed rdar://problem/58791649.

**Comment by varungandhi-apple** [comment]
There's a merge conflict because of https://github.com/apple/swift/pull/29351. It is just a documentation comment though. Let the Linux tests pass -> I'll fix the conflict -> @shahmishal can merge.

**Pull request merged**
