### PR TITLE
[Sema] NFC: Delete dead superclass coercion logic

### PR DESCRIPTION
**Pull request by davezarzycki**

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please test
@swift-ci please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci please test

**Review by slavapestov — APPROVED** [review]
Hah, I remember adding that FIXME. LGTM if the tests pass!

**Comment by davezarzycki** [comment]
The validation test suite passes on my Linux box :-)

**Comment by davezarzycki** [comment]
@slavapestov – Looks like the swift test suite is missing a test. Foundation can't compile. I'll probably need to abandon this pull request. I don't have time to look into why this isn't using going through the expected logic. :-(

```
1.	While type-checking 'appendingPathExtension(_:)' (at /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/swift-corelibs-foundation/Foundation/NSPathUtilities.swift:302:12)
2.	While type-checking statement at [/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/swift-corelibs-foundation/Foundation/NSPathUtilities.swift:302:66 - line:309:5] RangeText="{
        if str.hasPrefix("/") || self == "" || self == "/" {
            print("Cannot append extension \(str) to path \(self)")
            return nil
        }
        let result = _swiftObject._stringByFixingSlashes(compress: false, stripTrailing: true) + "." + str
        return result._stringByFixingSlashes()
    "
3.	While type-checking statement at [/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/swift-corelibs-foundation/Foundation/NSPathUtilities.swift:303:9 - line:306:9] RangeText="if str.hasPrefix("/") || self == "" || self == "/" {
            print("Cannot append extension \(str) to path \(self)")
            return nil
        "
4.	While type-checking expression at [/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/swift-corelibs-foundation/Foundation/NSPathUtilities.swift:303:12 - line:303:56] RangeText="str.hasPrefix("/") || self == "" || self == "
 #0 0x00000000048aebd4 PrintStackTraceSignalHandler(void*) (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/buildbot_linux/swift-linux-x86_64/bin/swiftc+0x48aebd4)
 #1 0x00000000048ac7f0 llvm::sys::RunSignalHandlers() (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/buildbot_linux/swift-linux-x86_64/bin/swiftc+0x48ac7f0)
 #2 0x00000000048aeff8 SignalHandler(int) (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/buildbot_linux/swift-linux-x86_64/bin/swiftc+0x48aeff8)
 #3 0x00007fa5e61c4390 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11390)
 #4 0x00007fa5e4903428 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x35428)
 #5 0x00007fa5e490502a abort (/lib/x86_64-linux-gnu/libc.so.6+0x3702a)
 #6 0x000000000480611d llvm::llvm_unreachable_internal(char const*, char const*, unsigned int) (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/buildbot_linux/swift-linux-x86_64/bin/swiftc+0x480611d)
 #7 0x0000000000fdeb51 (anonymous namespace)::ExprRewriter::coerceToType(swift::Expr*, swift::Type, swift::constraints::ConstraintLocatorBuilder, llvm::Optional<swift::Pattern*>) (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/buildbot_linux/swift-linux-x86_64/bin/swiftc+0xfdeb51)
 #8 0x0000000000ff4448 (anonymous namespace)::ExprRewriter::coerceCallArguments(swift::Expr*, swift::AnyFunctionType*, swift::ApplyExpr*, llvm::ArrayRef<swift::Identifier>, bool, swift::constraints::ConstraintLocatorBuilder) (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/buildbot_linux/swift-linux-x86_64/bin/swiftc+0xff4448)
 #9 0x0000000000fe3058 (anonymous namespace)::ExprRewriter::finishApply(swift::ApplyExpr*, swift::Type, swift::constraints::ConstraintLocatorBuilder) (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/buildbot_linux/swift-linux-x86_64/bin/swiftc+0xfe3058)
#10 0x0000000000ff6ffa (anonymous namespace)::ExprRewriter::visitApplyExpr(swift::ApplyExpr*) (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/buildbot_linux/swift-linux-x86_64/bin/swiftc+0xff6ffa)
#11 0x0000000000fe53eb (anonymous namespace)::ExprWalker::walkToExprPost(swift::Expr*) (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/buildbot_linux/swift-linux-x86_64/bin/swiftc+0xfe53eb)
#12 0x0000000001356319 swift::ASTVisitor<(anonymous namespace)::Traversal, swift::Expr*, swift::Stmt*, bool, swift::Pattern*, bool, void>::visit(swift::Expr*) (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/buildbot_linux/swift-linux-x86_64/bin/swiftc+0x1356319)
#13 0x000000000135808a (anonymous namespace)::Traversal::visitApplyExpr(swift::ApplyExpr*) (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/buildbot_linux/swift-linux-x86_64/bin/swiftc+0x135808a)
#14 0x00000000013562f0 swift::ASTVisitor<(anonymous namespace)::Traversal, swift::Expr*, swift::Stmt*, bool, swift::Pattern*, bool, void>::visit(swift::Expr*) (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/buildbot_linux/swift-linux-x86_64/bin/swiftc+0x13562f0)
#15 0x000000000135808a (anonymous namespace)::Traversal::visitApplyExpr(swift::ApplyExpr*) (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/buildbot_linux/swift-linux-x86_64/bin/swiftc+0x135808a)
#16 0x000000000135355b swift::Expr::walk(swift::ASTWalker&) (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/buildbot_linux/swift-linux-x86_64/bin/swiftc+0x135355b)
#17 0x0000000000fdcaf8 swift::constraints::ConstraintSystem::applySolution(swift::constraints::Solution&, swift::Expr*, swift::Type, bool, bool) (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/buildbot_linux/swift-linux-x86_64/bin/swiftc+0xfdcaf8)
```

**Comment by slavapestov** [comment]
Can you file a bug so that we don't forget then? Hopefully its an easy fix.

**Comment by davezarzycki** [comment]
Hi @slavapestov – Here you go: https://bugs.swift.org/browse/SR-10017

**Pull request closed without merging**
