### PR TITLE
[5.1] Use the remaining half bit in the refcount to bypass ObjC deallocation overhead

### PR DESCRIPTION
**Pull request by Catfish-Man**
(cherry picked from commit c51294671bf2b9587f4de57ed834633359d84db3)

5.1 cherry pick of https://github.com/apple/swift/pull/25418

### CODE REVIEW

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Comment by Catfish-Man** [comment]
Depends on https://github.com/apple/swift/pull/25589, so probably won't pass Linux yet

**Comment by Catfish-Man** [comment]
I meant iOS there, not Linux. That's why that failed.

**Comment by Catfish-Man** [comment]
@swift-ci please test osx platform

**Comment by Catfish-Man** [comment]
@swift-ci test osx

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Comment by Catfish-Man** [comment]
There we go, dunno why it wasn't listening

**Review by airspeedswift — APPROVED** [review]

**Pull request merged**
