### PR TITLE
[README] List additional package dependencies for building libdispatch on Ubuntu

### PR DESCRIPTION
**Pull request by briancroom**
#### What's in this pull request?

I ran into some trouble trying to build `libdispatch` on Linux because I was missing some additional packages required to get everything building. This adds the packages that are mentioned in `libdispatch`'s [INSTALL](https://github.com/apple/swift-corelibs-libdispatch/blob/master/INSTALL.md) file but were missing here. The new packages are `autoconf`, `libtool`, and `libkqueue-dev`

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by RLovelett** [comment]
This PR is likely overcome-by-events (OBE) at this point. I think some of the changes are already in the README and what is more I think that some of them are not even necessary anymore.

**Comment by CodaFi** [comment]
I think the only thing that isn't strictly necessary anymore is `libkqueue-dev` which is now pulled in as a submodule.  Otherwise I think this patch is still viable.

**Comment by CodaFi** [comment]
ping @briancroom

**Comment by briancroom** [comment]
Thanks for following up @CodaFi.

I've rebased this and adjusted it to only add `autoconf` and `libtool`. Does this look right? I haven't tried building `libdispatch` on Linux myself since June so I'm not up to speed on what may have changed there.

**Comment by briancroom** [comment]
While sitting here this has gone out of date again, and is now superseded by https://github.com/apple/swift/pull/5861 (Thanks @alblue!). Closing.

**Pull request closed without merging**
