### PR TITLE
Revert "[wrangler] Disable IDE/complete_from_clang_framework.swift"

### PR DESCRIPTION
**Pull request by rintaro**
This reverts commit 423f0c3dfeb47050f361458920f63d1df7b25d4b.

The failure was
```
/Users/buildnode/jenkins/workspace/oss-swift-incremental-RA-macos-apple-silicon/swift/test/IDE/complete_from_clang_framework.swift:127:19: error: CLANG_BAR-DAG: expected string not found in input
// CLANG_BAR-DAG: Decl[TypeAlias]/OtherModule[__ObjC]: __builtin_va_list[#(__va_list_tag)#]; name=__builtin_va_list
                  ^
```
But the offending line was removed in c5a715d4ed734257937f4d8539e3284cff8495fc . Let's re-enable the test case.

rdar://85471345

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please test

**Review by bnbarham — APPROVED** [review]

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by bnbarham** [comment]
Thanks for migrating 🙇‍♂️

**Pull request merged**
