### PR TITLE
Make the naming of underlying builtin for FP + Vector match Integer.

### PR DESCRIPTION
**Pull request by stephentyrone**
For stdlib integer types, these are named `_value` and `init(_ _value: Builtin.xxx)`. This patch adopts the same scheme for stdlib floating point and SDK overlay vector types, and removes a legacy init for integers that was only needed to support them. There should be no changes visible outside of the stdlib, and no functional change within the stdlib; the naming of some implementation details is simply more uniform now.

### CODE REVIEW

**Comment by stephentyrone** [comment]
@swift-ci Please smoke test.

**Comment by stephentyrone** [comment]
@swift-ci Please smoke test.

**Comment by slavapestov** [comment]
@stephentyrone I'm going to revert this because it broke the source compat suite (not your fault, it's a constraint solver bug).

However what exposed the bug is the addition of new unlabeled initializers on numeric types. I think we want to avoid these because they make the type checker go exponential. Since builtin types are never public, we can change these initializers without breaking anyone.

Do you want to give them labels again on floats *and* integers?

**Comment by rudkx** [comment]
As long as the initializers are not failable I don't think they're going to cause any problems. If all the overloads in an overload set return the same type we're able to split the constraint system which avoids the exponential behavior.

The problem we have with Int, Float, etc. is that around Swift 3.1 (?) timeframe we introduced unlabeled failable inits.

**Pull request merged**
