### PR TITLE
[5.1 EARLY] [ParseableInterface] Module-qualify protocol types and typealiases

### PR DESCRIPTION
**Pull request by jrose-apple**
Cherry-pick of #22830 to the early 5.1 branch for Apple purposes. Reviewed by @harlanhaskins and @nathawes.

rdar://problem/48298527 and rdar://problem/49426322

### CODE REVIEW

**Comment by jrose-apple** [comment]
apple/swift-lldb#1422
@swift-ci Please test

**Comment by jrose-apple** [comment]
apple/swift-lldb#1422
@swift-ci Please test Linux

**Comment by jrose-apple** [comment]
@rintaro, I remember seeing this failure on another PR. What's the fix? Or is it just not going to be fixed on the early branch?

```
******************** TEST 'SwiftSyntax :: print_verify_tree.swift' FAILED ********************
Script:
--
: 'RUN: at line 1';   rm -rf "/private/var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/Output/print_verify_tree.swift.tmp" && mkdir -p "/private/var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/Output/print_verify_tree.swift.tmp"
: 'RUN: at line 2';   /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.1-branch-03-18-2019/buildbot_incremental/swiftsyntax-macosx-x86_64/x86_64-apple-macosx/release/lit-test-helper -print-tree -source-file /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.1-branch-03-18-2019/swift-syntax/lit_tests/print_verify_tree.swift > /private/var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/Output/print_verify_tree.swift.tmp.result
: 'RUN: at line 3';   diff -u /private/var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/Output/print_verify_tree.swift.tmp.result /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.1-branch-03-18-2019/swift-syntax/lit_tests/output/print_verify_tree.swift.withkind
--
Exit Code: 1

Command Output (stdout):
--
--- /private/var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/Output/print_verify_tree.swift.tmp.result	2019-03-29 16:44:01.000000000 -0700
+++ /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.1-branch-03-18-2019/swift-syntax/lit_tests/output/print_verify_tree.swift.withkind	2019-03-29 13:34:40.000000000 -0700
@@ -2,10 +2,10 @@
 // RUN: %lit-test-helper -print-tree -source-file %s > %t.result
 // RUN: diff -u %t.result %S/output/print_verify_tree.swift.withkind
 
-func </TokenSyntax><TokenSyntax>foo</TokenSyntax><FunctionSignatureSyntax><ParameterClauseSyntax><TokenSyntax>(</TokenSyntax><FunctionParameterListSyntax></FunctionParameterListSyntax><TokenSyntax>) </TokenSyntax></ParameterClauseSyntax></FunctionSignatureSyntax><CodeBlockSyntax><TokenSyntax>{</TokenSyntax><CodeBlockItemListSyntax><CodeBlockItemSyntax><UnknownDeclSyntax><IfConfigClauseSyntax><TokenSyntax>
+func </TokenSyntax><TokenSyntax>foo</TokenSyntax><FunctionSignatureSyntax><ParameterClauseSyntax><TokenSyntax>(</TokenSyntax><FunctionParameterListSyntax></FunctionParameterListSyntax><TokenSyntax>) </TokenSyntax></ParameterClauseSyntax></FunctionSignatureSyntax><CodeBlockSyntax><TokenSyntax>{</TokenSyntax><CodeBlockItemListSyntax><CodeBlockItemSyntax><IfConfigDeclSyntax><IfConfigClauseListSyntax><IfConfigClauseSyntax><TokenSyntax>
 #if </TokenSyntax><FunctionCallExprSyntax><IdentifierExprSyntax><TokenSyntax>swift</TokenSyntax></IdentifierExprSyntax><TokenSyntax>(</TokenSyntax><FunctionCallArgumentListSyntax><FunctionCallArgumentSyntax><PrefixOperatorExprSyntax><TokenSyntax>>=</TokenSyntax><FloatLiteralExprSyntax><TokenSyntax>3.2</TokenSyntax></FloatLiteralExprSyntax></PrefixOperatorExprSyntax></FunctionCallArgumentSyntax></FunctionCallArgumentListSyntax><TokenSyntax>)</TokenSyntax></FunctionCallExprSyntax><CodeBlockItemListSyntax><CodeBlockItemSyntax><FunctionCallExprSyntax><MemberAccessExprSyntax><IdentifierExprSyntax><TokenSyntax>
-    components</TokenSyntax></IdentifierExprSyntax><TokenSyntax>.</TokenSyntax><TokenSyntax>append</TokenSyntax></MemberAccessExprSyntax><TokenSyntax>(</TokenSyntax><FunctionCallArgumentListSyntax><FunctionCallArgumentSyntax><StringInterpolationExprSyntax><TokenSyntax>"</TokenSyntax><StringInterpolationSegmentsSyntax><StringSegmentSyntax><TokenSyntax>-b \"</TokenSyntax></StringSegmentSyntax><ExpressionSegmentSyntax><TokenSyntax>\</TokenSyntax><TokenSyntax>(</TokenSyntax><SubscriptExprSyntax><IdentifierExprSyntax><TokenSyntax>string</TokenSyntax></IdentifierExprSyntax><TokenSyntax>[</TokenSyntax><FunctionCallArgumentListSyntax><FunctionCallArgumentSyntax><PrefixOperatorExprSyntax><TokenSyntax>..<</TokenSyntax><FunctionCallExprSyntax><MemberAccessExprSyntax><IdentifierExprSyntax><TokenSyntax>string</TokenSyntax></IdentifierExprSyntax><TokenSyntax>.</TokenSyntax><TokenSyntax>index</TokenSyntax></MemberAccessExprSyntax><TokenSyntax>(</TokenSyntax><FunctionCallArgumentListSyntax><FunctionCallArgumentSyntax><TokenSyntax>before</TokenSyntax><TokenSyntax>: </TokenSyntax><MemberAccessExprSyntax><IdentifierExprSyntax><TokenSyntax>string</TokenSyntax></IdentifierExprSyntax><TokenSyntax>.</TokenSyntax><TokenSyntax>endIndex</TokenSyntax></MemberAccessExprSyntax></FunctionCallArgumentSyntax></FunctionCallArgumentListSyntax><TokenSyntax>)</TokenSyntax></FunctionCallExprSyntax></PrefixOperatorExprSyntax></FunctionCallArgumentSyntax></FunctionCallArgumentListSyntax><TokenSyntax>]</TokenSyntax></SubscriptExprSyntax><TokenSyntax>)</TokenSyntax></ExpressionSegmentSyntax><StringSegmentSyntax><TokenSyntax>\"</TokenSyntax></StringSegmentSyntax></StringInterpolationSegmentsSyntax><TokenSyntax>"</TokenSyntax></StringInterpolationExprSyntax></FunctionCallArgumentSyntax></FunctionCallArgumentListSyntax><TokenSyntax>)</TokenSyntax></FunctionCallExprSyntax></CodeBlockItemSyntax></CodeBlockItemListSyntax></IfConfigClauseSyntax><UnknownSyntax><TokenSyntax>
-#else</TokenSyntax><TokenSyntax>
-    components</TokenSyntax><TokenSyntax>.</TokenSyntax><TokenSyntax>append</TokenSyntax><TokenSyntax>(</TokenSyntax><TokenSyntax>"-b \"\(string.substring(to: string.characters.index(before: string.endIndex)))\""</TokenSyntax><TokenSyntax>)</TokenSyntax></UnknownSyntax><TokenSyntax>
-#endif</TokenSyntax></UnknownDeclSyntax></CodeBlockItemSyntax></CodeBlockItemListSyntax><TokenSyntax>
+    components</TokenSyntax></IdentifierExprSyntax><TokenSyntax>.</TokenSyntax><TokenSyntax>append</TokenSyntax></MemberAccessExprSyntax><TokenSyntax>(</TokenSyntax><FunctionCallArgumentListSyntax><FunctionCallArgumentSyntax><StringInterpolationExprSyntax><TokenSyntax>"</TokenSyntax><StringInterpolationSegmentsSyntax><StringSegmentSyntax><TokenSyntax>-b \"</TokenSyntax></StringSegmentSyntax><ExpressionSegmentSyntax><TokenSyntax>\</TokenSyntax><TokenSyntax>(</TokenSyntax><SubscriptExprSyntax><IdentifierExprSyntax><TokenSyntax>string</TokenSyntax></IdentifierExprSyntax><TokenSyntax>[</TokenSyntax><FunctionCallArgumentListSyntax><FunctionCallArgumentSyntax><PrefixOperatorExprSyntax><TokenSyntax>..<</TokenSyntax><FunctionCallExprSyntax><MemberAccessExprSyntax><IdentifierExprSyntax><TokenSyntax>string</TokenSyntax></IdentifierExprSyntax><TokenSyntax>.</TokenSyntax><TokenSyntax>index</TokenSyntax></MemberAccessExprSyntax><TokenSyntax>(</TokenSyntax><FunctionCallArgumentListSyntax><FunctionCallArgumentSyntax><TokenSyntax>before</TokenSyntax><TokenSyntax>: </TokenSyntax><MemberAccessExprSyntax><IdentifierExprSyntax><TokenSyntax>string</TokenSyntax></IdentifierExprSyntax><TokenSyntax>.</TokenSyntax><TokenSyntax>endIndex</TokenSyntax></MemberAccessExprSyntax></FunctionCallArgumentSyntax></FunctionCallArgumentListSyntax><TokenSyntax>)</TokenSyntax></FunctionCallExprSyntax></PrefixOperatorExprSyntax></FunctionCallArgumentSyntax></FunctionCallArgumentListSyntax><TokenSyntax>]</TokenSyntax></SubscriptExprSyntax><TokenSyntax>)</TokenSyntax></ExpressionSegmentSyntax><StringSegmentSyntax><TokenSyntax>\"</TokenSyntax></StringSegmentSyntax></StringInterpolationSegmentsSyntax><TokenSyntax>"</TokenSyntax></StringInterpolationExprSyntax></FunctionCallArgumentSyntax></FunctionCallArgumentListSyntax><TokenSyntax>)</TokenSyntax></FunctionCallExprSyntax></CodeBlockItemSyntax></CodeBlockItemListSyntax></IfConfigClauseSyntax><IfConfigClauseSyntax><TokenSyntax>
+#else</TokenSyntax><CodeBlockItemListSyntax><CodeBlockItemSyntax><FunctionCallExprSyntax><MemberAccessExprSyntax><IdentifierExprSyntax><TokenSyntax>
+    components</TokenSyntax></IdentifierExprSyntax><TokenSyntax>.</TokenSyntax><TokenSyntax>append</TokenSyntax></MemberAccessExprSyntax><TokenSyntax>(</TokenSyntax><FunctionCallArgumentListSyntax><FunctionCallArgumentSyntax><StringInterpolationExprSyntax><TokenSyntax>"</TokenSyntax><StringInterpolationSegmentsSyntax><StringSegmentSyntax><TokenSyntax>-b \"</TokenSyntax></StringSegmentSyntax><ExpressionSegmentSyntax><TokenSyntax>\</TokenSyntax><TokenSyntax>(</TokenSyntax><FunctionCallExprSyntax><MemberAccessExprSyntax><IdentifierExprSyntax><TokenSyntax>string</TokenSyntax></IdentifierExprSyntax><TokenSyntax>.</TokenSyntax><TokenSyntax>substring</TokenSyntax></MemberAccessExprSyntax><TokenSyntax>(</TokenSyntax><FunctionCallArgumentListSyntax><FunctionCallArgumentSyntax><TokenSyntax>to</TokenSyntax><TokenSyntax>: </TokenSyntax><FunctionCallExprSyntax><MemberAccessExprSyntax><MemberAccessExprSyntax><IdentifierExprSyntax><TokenSyntax>string</TokenSyntax></IdentifierExprSyntax><TokenSyntax>.</TokenSyntax><TokenSyntax>characters</TokenSyntax></MemberAccessExprSyntax><TokenSyntax>.</TokenSyntax><TokenSyntax>index</TokenSyntax></MemberAccessExprSyntax><TokenSyntax>(</TokenSyntax><FunctionCallArgumentListSyntax><FunctionCallArgumentSyntax><TokenSyntax>before</TokenSyntax><TokenSyntax>: </TokenSyntax><MemberAccessExprSyntax><IdentifierExprSyntax><TokenSyntax>string</TokenSyntax></IdentifierExprSyntax><TokenSyntax>.</TokenSyntax><TokenSyntax>endIndex</TokenSyntax></MemberAccessExprSyntax></FunctionCallArgumentSyntax></FunctionCallArgumentListSyntax><TokenSyntax>)</TokenSyntax></FunctionCallExprSyntax></FunctionCallArgumentSyntax></FunctionCallArgumentListSyntax><TokenSyntax>)</TokenSyntax></FunctionCallExprSyntax><TokenSyntax>)</TokenSyntax></ExpressionSegmentSyntax><StringSegmentSyntax><TokenSyntax>\"</TokenSyntax></StringSegmentSyntax></StringInterpolationSegmentsSyntax><TokenSyntax>"</TokenSyntax></StringInterpolationExprSyntax></FunctionCallArgumentSyntax></FunctionCallArgumentListSyntax><TokenSyntax>)</TokenSyntax></FunctionCallExprSyntax></CodeBlockItemSyntax></CodeBlockItemListSyntax></IfConfigClauseSyntax></IfConfigClauseListSyntax><TokenSyntax>
+#endif</TokenSyntax></IfConfigDeclSyntax></CodeBlockItemSyntax></CodeBlockItemListSyntax><TokenSyntax>
 }</TokenSyntax></CodeBlockSyntax></FunctionDeclSyntax></CodeBlockItemSyntax></CodeBlockItemListSyntax><TokenSyntax></TokenSyntax></SourceFileSyntax>
\ No newline at end of file

--

********************
```

**Comment by harlanhaskins** [comment]
@jrose-apple That looks like fallout from @nkcsgexi's patch for #if configs in the SwiftSyntax parser

**Comment by nkcsgexi** [comment]
Yeah, i think you may need this: https://github.com/apple/swift/pull/23394

**Comment by jrose-apple** [comment]
@shahmishal Should we not run package tests on the old 5.1 branch? It doesn't seem like they're going to be in sync.

**Comment by shahmishal** [comment]
@jrose-apple We will need to update the preset on 03-18-2019 branch.

**Pull request merged**
