### PR TITLE
Only test debug NaN printing on x86_64

### PR DESCRIPTION
**Pull request by tbkka**
NaNs are mangled in various ways on various platforms.  Some
of the fun possibilities:
* sign bits sometimes can be cleared
* payloads get zeroed
* NaNs get forced to quiet
* Merely passing a value into a function can trigger these behaviors
* Trivial changes to the generated assembly can change this

This makes it very hard to validate the printing of NaN
details, since we can't be certain what value the formatter
actually saw.

So I'm simply disabling the checks for debugDescription on
NaNs except on x86_64, which has pretty well-understood NaN
support.

This should fix a test failure recently seen on 64-bit ARM hardware.

Note: Eventually, it might be nice to verify that the
debugDescription output always matches the expected
format:
```
   -?s?nan(\(0x[0-9a-f]+\))?
```
But it's not clear that anything stronger is really feasible.

### CODE REVIEW

**Comment by tbkka** [comment]
@swift-ci Please test

**Review by stephentyrone — APPROVED** [review]
I like the idea of ensuring the format is correct at some future point, but approved as is for now.

**Comment by tbkka** [comment]
I just added (most of) a check for the general format.

**Comment by tbkka** [comment]
@swift-ci Please test

**Pull request merged**
