### PR TITLE
[stdlib] Uninline float description

### PR DESCRIPTION
**Pull request by airspeedswift**
May help with some code bloat caused by the new string interpolation.

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@swift-ci please benchmark

**Comment by airspeedswift** [comment]
@tbkka I also removed some checks for inf that the C code was already handling. Be nice to remove the NaN check too but that results in more debug-style printing of nan that might not be desirable.

**Comment by airspeedswift** [comment]
This would also mean we don't need to export `swift_format_double`

**Comment by airspeedswift** [comment]
@swift-ci please benchmark

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@swift-ci please benchmark

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@swift-ci please clean test linux platform

**Comment by airspeedswift** [comment]
Unrelated linux failures need #20036

**Comment by tbkka** [comment]
Thanks for doing this!  When I initially did this, I was a little alarmed at the amount of inlining going on, but never got back to it.

> @tbkka I also removed some checks for inf that the C code was already handling. Be nice to remove the NaN check too but that results in more debug-style printing of nan that might not be desirable.

Regular `description` and `debugDescription` differ only in NaN printing.  But you could handle that distinction further down in the code. Right now, I think the `debug` flag might be entirely ignored.

**Review by tbkka — APPROVED** [review]
Looks good!

**Comment by airspeedswift** [comment]
Cool. I'll merge this for now and we can revisit sinking the nan handling later, once it's not inlinable we have flexibility to do that whenever.

**Comment by airspeedswift** [comment]
@swift-ci please test linux platform

**Pull request merged**
