### PR TITLE
[ConstraintSystem] Rank contextually unavailable overloads lower than…

### PR DESCRIPTION
**Pull request by xedin**
… other choices

Currently constraint solver is only capable of detecting universally unavailable
overloads but that's insufficient because it's still possible to pick a contextually
unavailable overload choice which could be better than e.g. generic overload, or
one with defaulted arguments, marked as disfavored etc.

Let's introduce `ConstraintSystem::isDeclUnavailable` which supports both universal
and contextual unavailability and allow constraint solver to rank all unavailable
overload choices lower than any other possible choice(s).

Resolves: rdar://problem/59056638

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
Source compatibility suite should now pass even with #29028 still un-reverted.

**Comment by theblixguy** [comment]
Unrelated failure: `/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/swift/stdlib/tools/swift-lang/SourceKitdClient.swift:15:8: error: no such module 'sourcekitd'`

@swift-ci please test source compatibility Debug

**Comment by theblixguy** [comment]
Welp, another unrelated SourceKit failure. Let's try one more time:

@swift-ci please test source compatibility Debug

**Comment by stephentyrone** [comment]
@swift-ci please test source compatibility Debug

**Comment by stephentyrone** [comment]
(Previous built went south because the machine it was on ran out of disk, restarting.)

**Comment by stephentyrone** [comment]
@xedin I went ahead and merged this, since it unbreaks some stuff. If you want to discuss further, that's also fine =)

**Comment by xedin** [comment]
Thank you, @stephentyrone!

**Pull request merged**
