### PR TITLE
Make a few IDE tests run concurrently

### PR DESCRIPTION
**Pull request by davezarzycki**
On a fast workstation, the highly-serial IDE tests are often as long or almost as long as the *entire* test suite. This makes three of the longest tests run concurrently.

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Review by rintaro — CHANGES_REQUESTED** [review]
We don't want to split them into "Input" and "Test" files because this reduces the maintainability of the tests.

Instead, could you split them into one file for each *group* of completion tests? For example for `complete_operators.swift`, we can split them into `complete_operators_postfix.swift` and `complete_operators_infix.swift`. If they are still too slow, split them into `_1`, `_2`, etc.

**Comment by davezarzycki** [comment]
Closing due to lack of interest/support.

**Pull request closed without merging**
