### PR TITLE
[stdlib] Introducing the new Arithmetic protocol

### PR DESCRIPTION
**Pull request by moiseev**
#### What's in this pull request?

This is the first in a series of incremental changes introducing the new integers model as described in [SE-0104](https://github.com/apple/swift-evolution/blob/master/proposals/0104-improved-integers.md).

This particular PR introduces the `Arithmetic` protocol, makes `FloatingPoint` conform to it, and gets rid of `AbsoluteValuable` conformance in floating point types.

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by stephentyrone** [comment]
Floating-point portion LGTM.

**Comment by lattner** [comment]
Nice Max!

**Comment by moiseev** [comment]
Build error looks unrelated. Let's benchmark.
@swift-ci Please benchmark.

**Comment by moiseev** [comment]
Resolved merge conflicts.
@swift-ci Please test and merge.

**Comment by moiseev** [comment]
Intents overlay error. Fixed later in master. Merging.

**Comment by masters3d** [comment]
@moiseev Is there a bug tracking SE-0104? I didn't find one. Can I create it?

**Pull request merged**
