### PR TITLE
[AST] Account for parameter bridging in Clang type computation.

### PR DESCRIPTION
**Pull request by varungandhi-apple**
Earlier, we assumed that only `@convention(c)` function types and `@convention(block)` function types were permitted in the components of an `@convention(c)` function type. However, that is not true because we may end up bridging a `@convention(block)` type (in parameter/return position of a `@convention(c)` function type) to a `@convention(swift)` type.

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
@swift-ci please test

**Comment by varungandhi-apple** [comment]
@swift-ci please test

**Comment by varungandhi-apple** [comment]
@swift-ci please test

**Comment by varungandhi-apple** [comment]
@swift-ci please test

**Comment by varungandhi-apple** [comment]
@swift-ci please test

**Comment by varungandhi-apple** [comment]
Hit a test failure for `test-sourcekit-lsp/test-sourcekit-lsp.py` to be fixed by https://github.com/apple/sourcekit-lsp/pull/343.

**Comment by varungandhi-apple** [comment]
@swift-ci please test Linux platform

**Review by rjmccall — APPROVED** [review]
LGTM

**Pull request merged**
