### PR TITLE
Rework the integrated REPL to use separate modules for every line

### PR DESCRIPTION
**Pull request by jrose-apple**
...like LLDB does, instead of parsing into a single SourceFile. This does break some functionality:

- no more `:dump_ast`
- no redeclaration checking, but no shadowing either—redeclarations just become ambiguous
- pretty much requires EnableAccessControl to be off, since we don't walk decls to promote them to `public` like the proper REPL

...but it allows us to remove a bit of longstanding support for type-checking / SILGen-ing / IRGen-ing only part of a SourceFile that was only used by the integrated REPL.

...which, need I remind everyone, is still *deprecated*...but sometimes convenient. So most of it still works.

* * *

Also removes support for `-enable-source-import` in the JIT. This is the only part of this PR that should affect non-integrated-REPL uses.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please asan test

**Comment by slavapestov** [comment]
Cool! We could also pull the “make everything public/open” walker out of lldb and into the frontend if we really wanted to...

**Comment by jrose-apple** [comment]
I don't really know who should review this, so I'm going to nominate @slavapestov as an all-arounder and already-commenter.

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Review by slavapestov — APPROVED** [review]

**Pull request merged**
