### PR TITLE
SIL: Fix handling of mark_dependence [nonescaping] in several utilities

### PR DESCRIPTION
**Pull request by atrick**
Fix a latent CapturePromotion bug with mark_dependence

Add AccessBase.storeBorrow

Add support throughout SIL for unknown mark_dependence uses.
   
Fixes rdar://125216361 ([nonescapable] [partial_apply [on_stack] cannot be cloned)

### CODE REVIEW

**Comment by meg-gupta** [comment]
LGTM!

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci test source compatibility

**Comment by atrick** [comment]
@swift-ci benchmark

**Comment by atrick** [comment]
SCK failures (same as main):
FAIL_penny-bot_5.9_BuildSwiftPackage.log
FAIL_swift-distributed-actors_5.7_BuildSwiftPackage.log

**Pull request merged**
