### PR TITLE
Revert "[AST] Allocate PlaceholderTypes in the correct arena"

### PR DESCRIPTION
**Pull request by hamishknight**
This reverts commit 97be0424b4afeb47973f0a1544cc89a762d9bac6.

rdar://108947854
rdar://108947721

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please smoke test

**Comment by hamishknight** [comment]
preset=buildbot_osx_package

@swift-ci please test with preset

**Review by xedin — APPROVED** [review]

**Comment by hamishknight** [comment]
Looks like the preset doesn't support PR testing :/

**Comment by hamishknight** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
