### PR TITLE
[test] Use target-swift-frontend for x-compile tests. NFC

### PR DESCRIPTION
**Pull request by milseman**

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@shahmishal does this look familiar? I think it's unrelated. Should I kick off a new build or force a clean?

```
Foundation/NSData.swift:19:8: error: module file was created by an older version of the compiler; rebuild 'Dispatch' and try again: /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/buildbot_linux/libdispatch-linux-x86_64/src/swift/Dispatch.swiftmodule
```

**Comment by milseman** [comment]
@swift-ci please clean test Linux Platform

**Comment by Rostepher** [comment]
@swift-ci please smoke test

**Review by Rostepher — APPROVED** [review]
This looks good to me! We should merge this once the tests pass. 👍

**Comment by milseman** [comment]
Do you need this in the 4.0 branch as well? Or is master good?

**Comment by Rostepher** [comment]
We might need this in the 4.0 branch I'll check.

**Comment by Rostepher** [comment]
@milseman We will need this on the 4.0 branch.

**Pull request merged**
