### PR TITLE
[Accelerate] Declare availability where missing, remove where redundant

### PR DESCRIPTION
**Pull request by lorentey**
`Accelerate.vImage`, `.vDSP` and `.vForce` are introduced in macOS 10.15 / iOS 13, but they are currently declared without availability. 

* Add the missing `@available` attributes to them and their extensions.
* Remove newly redundant `@available` attributes from the ~500 entry points defined in `vImage`/`vDSP`/`vForce` extensions. (Their availability is now inherited from the top-level extension.)
* Adjust remaining declarations that have 9999 availability to reflect the actual OS versions that introduce them.

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@stephentyrone In its current state this will conflict with your 9999 PR :( 

Feel free to merge that first if you like -- I already have a version of this based on that.

**Comment by jrose-apple** [comment]
@xymus, did you get in your change for availability on extensions to propagate to members? If not, this isn't safe to take yet either.

**Comment by lorentey** [comment]
@jrose-apple Is that a new issue? I think this has "always" worked:

```
@available(macOS 42, *) // nonsense "future" version
extension Array {
  func foo() {
    print("Hello")
  }
}

[1, 2, 3].foo() // error: 'foo()' is only available in macOS 42 or newer
```

**Comment by lorentey** [comment]
(I can revert the last commit if we need to keep the attributes on the individual members, but then we'll also need to review the codebase to add them everywhere. I think not even Accelerate declares `@available` on every new entry point in every new extension.)

**Comment by xymus** [comment]
This should be safe, the availability attribute worked as expected to declare an introduction version on extensions. My fix (#24997) was for the use of `unavailable` and `obsoleted` on extensions, which are still broken. #24997 been reverted but the blocker should itself be fixed soon.

**Comment by lorentey** [comment]
Merging to fix the ABI issue of missing @available decls. I'll submit a cherry pick to 5.1 in a jiffy.

**Pull request merged**
