### PR TITLE
[Foundation] adjust inline of append and initialization functions

### PR DESCRIPTION
**Pull request by phausler**
Use _copyContents(initialzing:) to avoid performance regressions while using generic collection/sequence APIs. This was a regression that was introduced on by ABI stability hardening of Data on the 4.2 and master branches.

### CODE REVIEW

**Comment by phausler** [comment]
@swift-ci please smoke test

**Comment by phausler** [comment]
@shahmishal do you know what happened here? I branched this from the swift-4.2-branch and it is merge targeting to that branch.

**Comment by shahmishal** [comment]
@swift-ci Please smoke test Linux

**Comment by phausler** [comment]
@parkera I’m pretty sure this belongs in 4.2: do we have to pick this to other branches?

**Review by parkera — APPROVED** [review]

**Comment by parkera** [comment]
I think master and swift-4.2-branch are the two required right now.

**Comment by phausler** [comment]
@swift-ci please smoke test and merge

**Comment by phausler** [comment]
@swift-ci please smoke test and merge

**Comment by phausler** [comment]
@swift-ci please smoke test and merge

**Comment by airspeedswift** [comment]
I think 4.2 needs full test before merge.

**Comment by phausler** [comment]
@swift-ci please test and merge

**Pull request merged**
