### PR TITLE
[5.7] Implement symbolic demangling for extended existential metadata

### PR DESCRIPTION
**Pull request by rjmccall**
Fixes rdar://96268090.  5.7 version of #59808.

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please test

**Review by hborla — APPROVED** [review]

**Review by CodaFi — APPROVED** [review]
Can't speak to the symbolic references bits, but the mangling and MetadataReader bits LGTM

**Comment by rjmccall** [comment]
Passed tests, but there were conflicts for some reason; re-testing.

**Comment by rjmccall** [comment]
@swift-ci Please test

**Pull request merged**
