### PR TITLE
[SourceKit] CMake dependency fixes

### PR DESCRIPTION
**Pull request by briancroom**
#### What's in this pull request?

While SourceKit building on Linux, I encountered some `unresolved reference` linker errors that seem to stem from a different linker behavior with respect to the ordering of libraries on the command line invocation. I've made two changes here that resolve several of these issues:
- Explicitly declare that `SourceKitCore` depends on `SourceKitSwiftLang`. This circular dependency exists in the source files but wasn't declared in the `CMakeLists`. Adding this here causes CMake to include the libraries multiple times in the invocation which lets the linker resolve the references.
- #2766 added some explicit clang dependencies to the `sourcekitdAPI` target to fix similar linker issues there. I discovered that those errors could instead be fixed by reordering some of the clang dependencies in `SourceKitSwiftLang`.

#### Related bug number: ([SR-1676](https://bugs.swift.org/browse/SR-1676))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

@modocache @llvm-beanz @gribozavr

### CODE REVIEW

**Comment by briancroom** [comment]
@swift-ci please test

**Comment by jrose-apple** [comment]
Hm. Is there any way to *avoid* the circular dependency?

@akyrtzi, @nkcsgexi

**Comment by briancroom** [comment]
I've poked around a little, and I think the dependency of `SwiftLang` on `Core` can likely be broken without too much hassle. I'll give it a go and see how it turns out.

**Comment by briancroom** [comment]
With #3101 merged, I've rebased this and cut out the circular-dependency change. This now only includes the reordering of the Clang dependencies which resolves linker issues on Linux.

**Comment by briancroom** [comment]
@swift-ci please test

**Pull request merged**
