### PR TITLE
Fix a couple of memory bugs

### PR DESCRIPTION
**Pull request by hamishknight**
Fix a stack-use-after-scope and uninitialized variable read.

rdar://65724385
rdar://65712583
rdar://65673653

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please smoke test

**Review by CodaFi — APPROVED** [review]
*tanquam ex ungue leonem*

**Comment by shahmishal** [comment]
@swift-ci please smoke test windows

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Comment by hamishknight** [comment]
@swift-ci please smoke test Linux

**Pull request merged**
