### PR TITLE
[Build System: CMake] Include the stdlib/toolchain directory before the stdlib/public directory (5.1 branch).

### PR DESCRIPTION
**Pull request by Rostepher**
Copy of #26362 for the 5.1 branch.

### CODE REVIEW

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by Rostepher** [comment]
@swift-ci please build toolchain macOS Platform

**Review by shahmishal — APPROVED** [review]

**Comment by jrose-apple** [comment]
This broke the open source package builder: https://ci.swift.org/view/Dashboard/job/oss-swift-5.1-package-osx/459/

**Comment by shahmishal** [comment]
This failure was due to out of space issue, cleaning up the node.

**Pull request merged**
