### PR TITLE
🍒[5.7][Distributed] Guard ID synthesis from happening multiple times

### PR DESCRIPTION
**Pull request by ktoso**
**Description:** Avoid synthesising the ID property many times in case of multi module builds.
**Risk:** Low
**Review by:** @DougGregor @kavon 
**Testing:** Verified using sample app; unit tests
**Original PR:** https://github.com/apple/swift/pull/42577
**Radar:** rdar://92162535

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please test

**Review by tomerd — APPROVED** [review]

**Comment by ktoso** [comment]
- 32bit watch issue;
- this did pass full tests on https://github.com/apple/swift/pull/42579 which is weird since also tests the 32bit watch

**Comment by xedin** [comment]
Not everything included in main has been cherry-picked to 5.7 so it might be something missing.

**Comment by ktoso** [comment]
Yeah there's quite a few ~5 PRs waiting on 5.7, main and the other 5.7 branch have way more.

So I'm thinking this is likely fixed since on 5.7-04182022 things seem good.
I'll re-run this once more stuff has landed.

**Review by DougGregor — APPROVED** [review]

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by kavon** [comment]
nice catch!

**Pull request merged**
