### PR TITLE
Merge 2020-05-07 into tensorflow

### PR DESCRIPTION
**Pull request by dan-zheng**
Friend PR: https://github.com/apple/llvm-project/pull/1189

### CODE REVIEW

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by dan-zheng** [comment]
Confirmed that macOS toolchain builds continue to work. Extended tests also pass.

**Review by saeta — APPROVED** [review]

**Pull request merged**
