### PR TITLE
[5.2] Adjust batch mode partition count calculation

### PR DESCRIPTION
**Pull request by kastiglione**
Cherry-pick of #28972 into `swift-5.2-branch`. Reviewed by @davidungar.

### CODE REVIEW

**Comment by kastiglione** [comment]
`git cherry-pick -m 1 ...` produced a squashed commit. Should this cherry-pick mirror the commits on the original PR instead?

**Comment by CodaFi** [comment]
Please cherry pick the original PR structure. It makes the history a big easier to reason about across branches.

**Comment by kastiglione** [comment]
@CodaFi I cherry-picked over the commits.

**Comment by DougGregor** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]

**Comment by DougGregor** [comment]
@swift-ci please test

**Pull request merged**
