### PR TITLE
Large Loadable Types: Use old ABI for block calling convention

### PR DESCRIPTION
**Pull request by shajrawi**
radar rdar://problem/28680453

Ignores debug instructions when re-creating function_ref instructions + makes sure that convention block functions / instructions use the old ABI

### CODE REVIEW

**Comment by shajrawi** [comment]
@swift-ci Please smoke test

**Comment by rjmccall** [comment]
The predicate you're looking for is getLanguage() == SILFunctionLanguage::C.  But you can still use your rule on foreign functions when they have an indirect result; you just need to actually ask the C ABI that instead of basing it on the Swift ABI.

Feel free to add a function to query that on IGM.  I think you do have an IGM here, right?

**Comment by shajrawi** [comment]
I just updated the predicate to `getLanguage() == SILFunctionLanguage::C`

**Comment by shajrawi** [comment]
@swift-ci Please smoke test

**Comment by shajrawi** [comment]
@swift-ci Please smoke test

**Comment by shajrawi** [comment]
@swift-ci Please smoke test

**Comment by shajrawi** [comment]
@swift-ci Please smoke test

**Comment by rjmccall** [comment]
That's okay, but I would still like to encourage you to handle foreign function types in a future patch.  Thunks and foreign calls are very important for code size.

**Comment by shajrawi** [comment]
Yep - will look into that!

**Comment by rjmccall** [comment]
Note that checking the language subsumes all your individual checks for CFunctionPointer/ObjCMethod/Block, so you should remove those now.

**Comment by shajrawi** [comment]
removed in PR https://github.com/apple/swift/pull/11205

**Comment by jrose-apple** [comment]
This broke the 32-bit simulator tests. I can't find a regular bot that's failing, but it broke my PR test: https://ci.swift.org/job/swift-PR-osx/9654/testReport/junit/Swift(watchsimulator-i386)/IRGen/big_types_corner_cases_sil/

**Comment by shajrawi** [comment]
Ah. adding x86_64 tests only / no checks added for other targets. on it.

**Comment by shajrawi** [comment]
@jrose-apple I added a REQUIRES x86_64 to that new tests file as part of this PR https://github.com/apple/swift/pull/11218

**Pull request merged**
