### PR TITLE
[CodeCompletion] Lazily populate 'BasicSourceFileInfo'

### PR DESCRIPTION
**Pull request by rintaro**

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Review by davidungar — APPROVED** [review]
LGTM!

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test macOS

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Pull request merged**
