### PR TITLE
[swift-api-dump] Add '--resource-dir' argument

### PR DESCRIPTION
**Pull request by modocache**
Allow a custom `-resource-dir` to be passed to `swift-ide-test`, by
adding an argument to `swift-api-dump.py`.

~~Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).~~

### CODE REVIEW

**Comment by modocache** [comment]
@swift-ci Please Python lint

**Comment by jrose-apple** [comment]
Can I ask why you need this?

**Comment by modocache** [comment]
I have several versions of Xcode installed, and I'd like to compare the Swift headers for the frameworks that ship with each of them.

**Comment by modocache** [comment]
The Python lint failures are coming from other files, my changes are fine (paging Dr. @practicalswift, Dr. @practicalswift to the Python ward please 🏥 ).

**Comment by jrose-apple** [comment]
Ah, that's not really sufficient. You need to be using the swift-ide-test that's built for each of those resource directories.

**Comment by modocache** [comment]
But, assuming that I use a `swift-ide-test` executable from the `swift-3.0.2-RELEASE` tag with Xcode 8.2, and so forth, it should work, right? I have some local changes that allow me to do that as well, but was hoping to send pull requests piecemeal.

**Comment by jrose-apple** [comment]
That part works, but then you might as well use the swift-ide-test's resource directory, which it already will.

**Comment by modocache** [comment]
Hmm, alright. I think I'll keep this on my personal fork for now. Thanks anyway!

**Pull request closed without merging**
