### PR TITLE
[6.0 🍒][CMake] Establish a dependency from standard library variants onto 'libSwiftScan'

### PR DESCRIPTION
**Pull request by artemcm**
Cherry-pick of https://github.com/swiftlang/swift/pull/77606 and https://github.com/swiftlang/swift/pull/77621 and https://github.com/swiftlang/swift/pull/73383
---------------------------

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
@swift-ci test macOS platform

**Comment by DougGregor** [comment]
@swift-ci test macOS platform

**Comment by artemcm** [comment]
@swift-ci test

**Review by nkcsgexi — APPROVED** [review]

**Comment by DougGregor** [comment]
@artemcm Please add the cherry-pick template here. The build changes here feel a bit invasive, and it's not clear how to weigh the benefit of taking this in the 6.0 branch vs. the risks associated with the build changes.

**Pull request closed without merging**
