### PR TITLE
upstream-update: adjust for SVN r326091

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @bob-wilson

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by bob-wilson** [comment]
I tested the exact same change locally and got a bunch of test failures. I haven't had a chance to investigate to see if it is due to changing the hash values.

**Comment by bob-wilson** [comment]
Yeah, it looks like things are being serialized in a different order and that is what is breaking tests. I'll try adding the "0" seed value.

**Comment by bob-wilson** [comment]
I'm going to merge this so we make forward progress. I just discussed it with @adrian-prantl . We're thinking of adding explicit "0" seed values for *all* of the djbHash calls (probably also the ones that were added in swift-clang) and then filing a bug report for someone to audit them later to see if some of those seed values can be changed to use the default.

**Pull request merged**
