### PR TITLE
[Build System: CMake] Darwin Supported Archs and Modules (5.1 04-24-2019 branch).

### PR DESCRIPTION
**Pull request by Rostepher**
Copy of #25122 for the 5.1 04-24-2019 branch.

rdar://50561574

### CODE REVIEW

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by Rostepher** [comment]
@swift-ci please nominate

**Comment by Rostepher** [comment]
@swift-ci please test Linux Platform

**Review by najacque — APPROVED** [review]

**Comment by Rostepher** [comment]
@swift-ci please test macOS Platform

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by Rostepher** [comment]
@swift-ci please test macOS Platform

**Pull request closed without merging**
