### PR TITLE
[PrintOptions] Print explicit `any` in SIL.

### LINKED ISSUE #60434: Missing `any` in -emit-silgen output
```swift
protocol P {
  associatedtype T
}

func foo(_: any P) {}
```

-emit-silgen outputs this:

```swift
sil_stage raw

import Builtin
import Swift
import SwiftShims

protocol P {
  associatedtype T
}

func foo(_: P)

sil [ossa] @main : $@convention(c) (Int32, UnsafeMutablePointer<Optional<UnsafeMutablePointer<Int8>>>) -> Int32 {
...
```

Which doesn't parse back in because of the missing `any`.

### PR DESCRIPTION
**Pull request by hborla**
This change sets `PrintOptions::PrintExplicitAny` to `true` when printing SIL.

Resolves: https://github.com/apple/swift/issues/60434

### CODE REVIEW

**Comment by hborla** [comment]
@swift-ci please test

**Review by slavapestov — APPROVED** [review]

**Comment by hborla** [comment]
@swift-ci please test

**Comment by hborla** [comment]
@swift-ci please test

**Comment by hborla** [comment]
@swift-ci please test

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by hborla** [comment]
@swift-ci please smoke test

**Pull request merged**
