### PR TITLE
Fix test/IRGen/objc_generic_class_stub.swift again

### PR DESCRIPTION
**Pull request by slavapestov**
More FileCheck shenanigans.

Fixes <rdar://problem/71560719>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@atrick My apologies for the churn.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test macOS

**Comment by slavapestov** [comment]
@swift-ci Please clean smoke test

**Comment by benlangmuir** [comment]
@swift-ci Please smoke test macOS

**Comment by benlangmuir** [comment]
Failure is unrelated. Merging to help fix bots.

**Pull request merged**
