### PR TITLE
[stdlib] Remove C-style for loops

### PR DESCRIPTION
**Pull request by nielsandriesse**
Successfully passed `build-script -t`

### CODE REVIEW

**Comment by gribozavr** [comment]
This needs review from the performance team. /cc @nadavrot

**Comment by nadavrot** [comment]
The changes look okay, but we are currently working on tracking down other performance regressions. Let's wait a few days before we commit these changes.

**Comment by gribozavr** [comment]
OK.

**Comment by kostiakoval** [comment]
It's a duplicate of #644

**Comment by lattner** [comment]
Please squash these into one commit also, thanks!

**Comment by johnlui** [comment]
@lattner I will start a new pull request, thanks!

**Comment by moiseev** [comment]
This one seems to be superseded by newer ones. Closing.

**Pull request closed without merging**
