### PR TITLE
Fix SILVerifier assert for witness_method with dynamic self type

### PR DESCRIPTION
**Pull request by meg-gupta**
Fixes rdar://71290925

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by slavapestov** [comment]
Should we instead try to fix this to work? What goes wrong if such a witness_method instruction is generated?

**Comment by aschwaighofer** [comment]
We hit the SIL verifier not liking such a witness method instruction. It only wants opened archetype type operands.

```
void checkWitnessMethodInst(WitnessMethodInst *AMI) {  
    auto lookupType = AMI->getLookupType();                                     
    if (getOpenedArchetypeOf(lookupType)) {                                     
      require(AMI->getTypeDependentOperands().size() == 1,                      
              "Must have a type dependent operand for the opened archetype");   
      verifyOpenedArchetype(AMI, lookupType);                                   
    } else {                                                                    
      require(AMI->getTypeDependentOperands().empty(),                          
              "Should not have an operand for the opened existential");         
    } 
```

**Comment by meg-gupta** [comment]
I changed what this PR was initially intended for. Turns out we do support witness_method with dynamic_self. The SILVerifier assertions for witness_method needed to be changed

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Comment by meg-gupta** [comment]
@swift-ci smoke test OS X platform

**Comment by meg-gupta** [comment]
@swift-ci smoke test Windows Platform

**Comment by slavapestov** [comment]
Thanks, changing the verifier here makes sense. We do support witness_method on concrete types just fine (either in IRGen, or the devirtualizer if that gets to run)

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Pull request merged**
