### PR TITLE
[5.0] Restore initializing entry points for @objc convenience initializers

### PR DESCRIPTION
**Pull request by jrose-apple**
- **Explanation**: Early in the Swift 5 release, @jckarter simplified Swift's implementation of convenience initializers to always go through the "allocating" entry point—in practice, delaying the responsibility of allocating `self` until necessary, which in practice means "until calling a designated initializer, or an initializer implemented in Objective-C". This had a number of benefits for the rest of the compiler, the primary one being a significant simplification in how vtables are built (which also manifests as a minor code size win). However, it also broke the decoding of object graphs with circular references through NSCoding, including Interface Builder files, because the unarchiver object can't know that its initial allocation (through Objective-C's `+allocWithZone:`) is going to be replaced. (That is, it breaks it when the implementation of `init(coder:)` in Swift is a convenience initializer.)

    To restore this capability, allow initializer delegating (`self.init`) to go through initializing (non-allocating) entry points when the delegated-to initializer is exposed to Objective-C. This doesn't change any safety guarantees or normally-observed behavior, and still allows the correct dynamic dispatch of the delegated-to initializer, but it does mean that as long as all initializers are `@objc`, the initial allocation won't be thrown away.

    This still isn't 100% the same as the behavior in Swift 4.2 and earlier, so it'll be worth release-noting.

- **Scope**: Affects convenience initializers that call `@objc` initializers, as well as the definitive initialization checking for `@objc` convenience initializers.

- **Issue**: rdar://problem/46823518

- **Risk**: Medium. Most of the patch is undoing changes that Joe made, but he made them a while ago, and so we've been living on the new way.

- **Testing**: Added compiler regression tests.

- **Reviewed by**: @jckarter

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by jrose-apple** [comment]
Oops, right. "ossa" post-dates the Swift 5 branch.

**Comment by jrose-apple** [comment]
Holding also for bug fix discovered in the original PR, rdar://problem/47266149.

**Comment by jrose-apple** [comment]
Picking up the test fix in #21861.

@swift-ci Please test

**Review by AnnaZaks — APPROVED** [review]

**Pull request merged**
