### PR TITLE
`add_swift_host_library` cleanup

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @drexin

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by drexin** [comment]
@compnerd Could you please add a description as to why these changes are safe?

**Comment by compnerd** [comment]
@drexin - its two individual changes bundled - the first one inlines a single call function (`_add_swift_host_library_single`) into its only caller (`add_swift_host_library`).  The second one fixes a couple of mistakes in the first one (I can go back and fix up the commits if you care).  It renames the usage of the variable that was named differently.  The only other thing it does is re-order the computation of the flags, it doesn't change anything but the order of the flags.  The functional change here is that path handling is delegated to CMake:

```cmake
string(REGEX MATCHALL "/[^/]+" split_path ${CMAKE_CURRENT_SOURCE_DIR})
list(GET split_path -1 dir)
```
is replaced with
```cmake
get_filename_component(dir ${CMAKE_CURRENT_SOURCE_DIR} DIRECTORY)
```

**Review by drexin — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
