### PR TITLE
[Changelog] Add entry for unsound pointer diagnostics

### PR DESCRIPTION
**Pull request by hamishknight**
Add a changelog entry for https://github.com/apple/swift/pull/27695.

### CODE REVIEW

**Review by atrick — APPROVED** [review]
Great! But should we include some information about how developers should resolve these issues? Some of the diagnostics have hints. Others don't. I'm sure some devs will be confused. In some easily searchable place we should link each of the diagnostic message to an explanation and example of doing the thing safely. It seems like release notes might be the best place.

@airspeedswift would this be too much for the release notes? The alternative would be to post it on the forums and hope devs find it with a web search.

**Comment by hamishknight** [comment]
@atrick I'd be happy to provide some examples in the changelog for ways in which users can resolve this. One question is what should we recommend for cases where the user is passing an optional array or string? I don't believe there's a straightforward workaround for those cases.

**Review by DougGregor — APPROVED** [review]
Thanks!

**Comment by hamishknight** [comment]
@swift-ci please smoke test

**Comment by hamishknight** [comment]
Spoke with @atrick, and we're going to merge this as-is. The diagnostics already suggest alternatives for the cases where there's a straightforward alternative, and I'll write up a forum post to try and help with some of the more tricky cases.

**Pull request merged**
