### PR TITLE
[5.3] [Preset] Source compat suite cross compile for macOS arm64

### PR DESCRIPTION
**Pull request by shahmishal**
master PR - https://github.com/apple/swift/pull/33297

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci Please test source compatibility

**Comment by shahmishal** [comment]
@swift-ci Please test source compatibility

**Comment by shahmishal** [comment]
@swift-ci Please test source compatibility

**Comment by shahmishal** [comment]
@swift-ci Please test source compatibility

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test

**Review by edymtt — APPROVED** [review]

**Review by tkremenek — APPROVED** [review]

**Pull request merged**
