### PR TITLE
[SE-0163] Migrate from deprecated Unicode APIs (part 2)

### PR DESCRIPTION
**Pull request by benrimmington**
Most of the changes are simple renames:

* `UTF8` → `Unicode.UTF8`
* `UTF16` → `Unicode.UTF16`
* `UTF32` → `Unicode.UTF32`
* `UnicodeScalar` → `Unicode.Scalar`
* `UnicodeCodec` → `Unicode.Encoding`

Follow-up to: apple/swift#32920

### CODE REVIEW

**Comment by benrimmington** [comment]
@swift-ci Please smoke test

**Comment by benrimmington** [comment]
@swift-ci Please smoke benchmark

**Comment by benrimmington** [comment]
@milseman This pull request uses the new names, but it doesn't deprecate the old ones.

**Review by milseman — COMMENTED** [review]
Could you clarify what your goal is? This doesn't seem like an improvement to the readability of stdlib code.

**Pull request closed without merging**
