### PR TITLE
[Parse/ASTPrinter] Print default argument for nil, [], and [:]

### PR DESCRIPTION
**Pull request by rintaro**
`DefaultArgumentKind` is extended in 5aa40dd0aa057591398339c77df91a976ae35c72, but never applied to the Swift parser.

CC: @DougGregor 
Any reason _not_ to do this?

### CODE REVIEW

**Comment by jrose-apple** [comment]
I don't think we want to be syntactically matching certain kinds of default arguments. Really we just want to be able to display *any* of them, probably with a stringified representation, as long as there's nothing non-public in the expression.

**Comment by DougGregor** [comment]
In the general case, I agree with @jrose-apple that we should stringify the default argument for printing purposes. However, this is a step in the right direction, and will handle all of the default arguments inferred for imported Objective-C APIs, so we should go ahead and merge this.

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
That Linux failure has nothing to do with this patch:

Compile Swift Module 'Basic' (21 sources)
AST verification error: archetype Self.Index not allowed in this context
archetype came from:

**Comment by DougGregor** [comment]
@swift-ci please smoke test Linux

**Comment by rintaro** [comment]
Testing locally.

**Comment by rintaro** [comment]
Applying `DefaultArgumentKind::Nil` turns the argument into `CallerDefaultInitialize`.
[`chars.rindex(of: "/")`](https://github.com/apple/swift-package-manager/blob/a2ec49e6a25ca8aae8dd06e5d0ea8aa739a77b4d/Sources/Basic/Path.swift#L361) in `swiftpm` calls [`rindex(of:from:)`](https://github.com/apple/swift-package-manager/blob/a2ec49e6a25ca8aae8dd06e5d0ea8aa739a77b4d/Sources/Basic/CollectionAlgorithms.swift#L19) which declared as
`func rindex(of element: Iterator.Element, from start: Index? = nil) -> Index?`.

Maybe, the compiler is trying to resolve `nil` as `Self.Index?` in caller context?

Anyway, it seems it's better to leave them as `DefaultArgumentKind::Normal` as is,
and stringify the default argument expression in ASTPrinter.

**Comment by DougGregor** [comment]
Ah, yes, the caller is probably trying to use `Self.Index?` from the caller context rather than using the properly-substituted type.

**Comment by rintaro** [comment]
Filed https://bugs.swift.org/browse/SR-2608 for *any* default value printing.

Closing.

**Pull request closed without merging**
