### PR TITLE
[tool] swift-config

### PR DESCRIPTION
**Pull request by krzyzanowskim**
This tool encapsulates information about a Swift project configuration for use by other project's build environments (to determine installed path, available features, required libraries, etc.).

```
usage: swift-config <OPTION>...

Get various configuration information needed to compile programs which use
Swift. Typically called from 'configure' scripts. Examples:
  swift-config --cxxflags
  swift-config --ldflags

Options:
  --version         Print Swift version.
  --prefix          Print the installation prefix.
  --src-root        Print the source root Swift was built from.
  --obj-root        Print the object root used to build Swift.
  --bindir          Directory containing Swift executables.
  --includedir      Directory containing Swift headers.
  --cmark-src-root  Print the source root CMark was built from.
  --cmark-obj-root  Print the object root used to build CMark.
  --libdir          Directory containing Swift libraries.
  --cppflags        C preprocessor flags for files that include Swift headers.
  --cflags          C compiler flags for files that include Swift headers.
  --cxxflags        C++ compiler flags for files that include Swift headers.
  --ldflags         Print Linker flags.
```

based on `llvm-config` tool

### CODE REVIEW

**Comment by gottesmm** [comment]
This is the wrong way to do this. The typical way that this is done is via importing a cmake config. We already support this and it is used by lldb to import swift and its configuration variables.

Source: cmake/modules/SwiftConfig.cmake.in.
Build: ./lib/cmake/swift/SwiftConfig.cmake

llvm-config (the analogous tool in LLVM) is something that people have wanted to kill in LLVM for a long time. We shouldn't create a swift-config and create dependencies on it lest we are stuck with the same problem.

If the problem is with an installed swift in the system, we can provide a pkg-config or the like.

**Comment by gottesmm** [comment]
@krzyzanowskim if you want I can show you how to set up this cmake integration for whatever project you need.

**Comment by krzyzanowskim** [comment]
Thank you for the opinion. I kindly disagree though. I found llvm-config a very useful when used without cmake. The same with swift-config. What is exactly "the same problem" you think about?

There are project that generate pkg-config from llvm-config all the time. I'll bring 
https://github.com/llvm-swift/LLVMSwift/blob/master/utils/make-pkgconfig.swift here, by @harlanhaskins. Though, even pkg-config, even with SPM has it's problems in practice.

Maybe the world would be a better place if every project has cmake dependency, but... is this a reasonable expectation in long term? Autotools was a standard not that long ago.

**Comment by harlanhaskins** [comment]
I should mention that make-pkgconfig script is a huge hack thats only relevant because llvm doesn’t install a pkg-config file.

**Comment by gottesmm** [comment]
@harlanhaskins if we want to do this, can't we just check in a swift.pc.in file and process it using cmake configure? I am curious why LLVM has never done this. Let me ask around.

**Comment by gottesmm** [comment]
From talking with @llvm-beanz it sounds like no one has cared. @krzyzanowskim if we had a pkg-config file, would be it good enough for you?

**Comment by llvm-beanz** [comment]
It is also probably worth noting that clang doesn’t provide a ‘clang-config’ took because the interfacing is simple and not intended to be as complicated as llvm. Swift’s library interface is also *way* simpler than LLVM, so I’m not sure how justified a ‘swift-config’ tool actually is. While I appreciate that you may find it useful, is it useful to other people enough to justify including it in distributions? If not, it probably should’t be added to Swift.

**Comment by krzyzanowskim** [comment]
pkg-config would help of course. I don't think it would be as handy as swift-config, especially for the multiple builds (needs to adjust PKG_CONFIG_PATH) but would be an improvement.

**Pull request closed without merging**
