### PR TITLE
[TSan] Do not report benign race on `_swiftEmptyArrayStorage`

### PR DESCRIPTION
**Pull request by yln**
Cherry-picks for rdar://55161564 (Unexpected TSAN error against _swiftEmptyArrayStorage).
https://github.com/apple/swift/pull/27808

### CODE REVIEW

**Comment by yln** [comment]
@swift-ci Please test

**Comment by yln** [comment]
@swift-ci Please test Linux

**Review by lorentey — APPROVED** [review]
👍

**Review by mikeash — APPROVED** [review]

**Comment by yln** [comment]
@apple/swift5-branch-managers

**Comment by yln** [comment]
It's too late in the integration cycle.

**Pull request closed without merging**
