### PR TITLE
Redo diagnostics for escaping captures and non-escaping parameter call restriction [5.1]

### PR DESCRIPTION
**Pull request by slavapestov**
5.1 cherry-pick of https://github.com/apple/swift/pull/23878 and https://github.com/apple/swift/pull/23907.

- https://bugs.swift.org/browse/SR-2969
- https://bugs.swift.org/browse/SR-2274 / rdar://problem/29403178
- https://bugs.swift.org/browse/SR-8546 / rdar://problem/43355341
- https://bugs.swift.org/browse/SR-9043 / rdar://problem/45511834
- rdar://problem/34496304

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test macOS

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by Demerro** [comment]
https://github.com/apple/swift/issues/69911

**Pull request merged**
