### PR TITLE
[ExternalGenericMetadataBuilder] Support ARM64e fixups.

### PR DESCRIPTION
**Pull request by mikeash**
Add ptrauth attributes to the witness tables and descriptor pointers, and have the test support ARM64e.

rdar://122660111

### CODE REVIEW

**Comment by mikeash** [comment]
@swift-ci please test

**Review by al45tair — APPROVED** [review]

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
We hit an assertion failure due to some missing error checking in GenericMetadataBuilder, added that now.

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test

**Pull request merged**
