### PR TITLE
[SIL Diagnostics] [WIP] Disable constant folding diagnostics on auto-generated functions

### PR DESCRIPTION
**Pull request by ravikandhadai**
This commit disables constant-propagation diagnostics on auto-generated functions such as functions obtained by generic specializations.  Diagnostics on these functions are difficult to trace back to source as they do not have AST information and their bodies could be different from what the user wrote. Performance constant propagation would still be performed on such functions.

### CODE REVIEW

**Comment by ravikandhadai** [comment]
@swift-ci please smoke test

**Review by xedin — COMMENTED** [review]
Awesome, but it looks like this might need some `clang-format` love! :)

**Comment by ravikandhadai** [comment]
@swift-ci please smoke test

**Comment by slavapestov** [comment]
This needs a test case.

**Comment by ravikandhadai** [comment]
@slavapestov  I am not sure how to test this. Do you have some ideas? The problem here is that I need to run diagnostic constant propagation (a part of mandatory phases) on an auto-generated function e.g. like a method obtained by specializing generics. In a normal workflow, such specialized functions are created after mandatory phases. But, somehow while analyzing the standard library I find that diagnostic constant propagation is run on such specialized function, which resulted in an error in Pavel's branch. So I am wondering how I can simulate this behavior for testing.

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by ravikandhadai** [comment]
I am closing this PR for now, as it doesn't seem to be a problem as of now.

**Pull request closed without merging**
