### PR TITLE
[DO NOT MERGE] Make Swift 3 / 4 consistent with SE-0054.

### PR DESCRIPTION
**Pull request by rudkx**
As with Swift 5 mode, make Swift 3 / 4 reject IUOs in places where they are not allowed according to SE-0054.

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
This also fixes some issues with the earlier commit to catch more cases of IUO used in the wrong places, and I'll commit those fixes once I fix up a couple remaining issues.

**Comment by DougGregor** [comment]
Looks like there were only two issues! RxSwift had this:

    print(convertResponseToString(data, response, error as NSError!, interval))

which has been fixed in the upstream repository already.

Alamofire has this:

    if let encodingName = response?.textEncodingName as CFString!, convertedEncoding == nil {

where the '!' is effectively unnecessary. The code is still there upstream at https://github.com/Alamofire/Alamofire/blob/master/Source/ResponseSerialization.swift#L371

**Comment by rudkx** [comment]
Yup. It looks like we give a working fix-it in both cases as well (replace `!` with `?`).

**Comment by slavapestov** [comment]
@rudkx One alternative is to emit this as a warning in Swift 3/4 mode, and continue parsing as if it were a ?.

**Comment by rudkx** [comment]
@slavapestov Yes I mentioned that possibility in another forum. I think that's a reasonable choice for these casts, but probably not for something like `[Int!]` where other errors will surface and it will be even more confusing than just rejecting `[Int!]` in the first place.

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
Updated this commit since cef6c9463c is now in, which addresses some bugs in the earlier commit.

This is now limited to switching over to using the new tests all the time.

I still do not plan on merging this without further investigation, but want to verify where things stand and fix up any remaining code in our tree (e.g. in tests) that I may have missed.

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please smoke test OS X platform

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
There is still a cast in Foundation that is disallowed by SE-0054. I opened https://github.com/apple/swift-corelibs-foundation/pull/1300 to make it a cast to Optional instead.

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please smoke test Linux platform

**Comment by rudkx** [comment]
@swift-ci Please smoke test Linux platform

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please smoke test Linux platform

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
Ran into a couple more casts in Foundation that need to be fixed up: https://github.com/apple/swift-corelibs-foundation/pull/1303

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
@swift-ci Please smoke test Linux platform

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
Please test with following pull request:
https://github.com/apple/swift/pull/12682
https://github.com/apple/swift-corelibs-foundation/pull/1306

@swift-ci Please smoke test

**Comment by rudkx** [comment]
@shahmishal Any idea what might have happened here? The multi-PR test doesn't seem to have actually started.

**Comment by shahmishal** [comment]
This is was during CI outage yesterday. 

Please test with following pull request:
#12682
apple/swift-corelibs-foundation#1306

@swift-ci Please smoke test

**Comment by shahmishal** [comment]
Also, it does not support same repository :( 
Right now you can only provide one PR per repositories

**Comment by rudkx** [comment]
Closing in favor of a new PR I will open soon.

**Pull request closed without merging**
