### PR TITLE
Stop serializing the "inherited" clause of associated type declarations.

### PR DESCRIPTION
**Pull request by DougGregor**
As we do with `where` clauses, print the "inheritance" clauses of
protocols and associated type declarations using the requirement
signature of the protocol rather than the "inherited" list.

Then, stop serializing the "inherited" list of associated type
declarations altogether. This eliminates some recursive-deserialization
problems encountered while experimenting with recursive
constraints in the standard library.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by jrose-apple** [comment]
:-/ Unfortunate to lose the ordering here, though. The canonical signature may not be in the order that makes sense to a human, and even more so if we start allowing certain redundant constraints.

**Comment by DougGregor** [comment]
Hrm. We could bring this information back but have it lazily loaded (to avoid the recursive deserialization) just for display purposes. We haven't been consistent about this in general, though

**Comment by jrose-apple** [comment]
It seems like the sort of sugar we ought to preserve, but it doesn't have to happen immediately.

**Pull request merged**
