### PR TITLE
[gardening] Add a pre-processor guard in header swift/Frontend/Parsea…

### PR DESCRIPTION
**Pull request by gottesmm**
…bleInterfaceModuleLoader.h

I also fixed a few style/doxygen errors.

### CODE REVIEW

**Comment by gottesmm** [comment]
@harlanhaskins just an FYI.

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Review by harlanhaskins — APPROVED** [review]
Thanks!

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Pull request merged**
