### PR TITLE
[utils] update-checkout: Reduce environment variable noise

### PR DESCRIPTION
**Pull request by lorentey**
This stops unnecessary overriding and printing every environment variable when cloning repositories.

(This is a followup to https://github.com/apple/swift/pull/41714)

### CODE REVIEW

**Comment by lorentey** [comment]
Before: 
```
+ env GIT_TERMINAL_PROMPT=0 HOME=/Users/klorentey LANG=en_US.UTF-8 LESS=-R \
LOGNAME=klorentey LaunchInstanceID=*** PATH=*** PWD=/Users/klorentey/Swift/swift \
SECURITYSESSIONID=*** SHELL=/opt/brew/bin/fish SHLVL=1 \ SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.***/Listeners TERM=xterm-256color \
TERM_PROGRAM=Apple_Terminal TERM_PROGRAM_VERSION=444 \
TERM_SESSION_ID=AE93EAEA-A0A0-42F1-A767-************ TMPDIR=/var/folders/tg/***/T/ \
USER=klorentey XPC_FLAGS=0x0 XPC_SERVICE_NAME=0 __CFBundleIdentifier=com.apple.Terminal \
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0 \
git clone --recursive git@github.com:apple/swift-collections.git swift-collections
```

After:
```
+ env GIT_TERMINAL_PROMPT=0 git clone --recursive git@github.com:apple/swift-collections.git swift-collections
```

**Comment by lorentey** [comment]
@swift-ci smoke test

**Review by shahmishal — APPROVED** [review]

**Comment by lorentey** [comment]
@swift-ci smoke test and merge

**Comment by lorentey** [comment]
```
<EXPR>:0: error: TestToolTests.testEnableDisableTestability : threw error "signalled(11): /home/build-user/build/buildbot_linux/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/release/swift-test --package-path /tmp/Miscellaneous_TestableExe.porkiV/Miscellaneous_TestableExe --enable-testable-imports --vv output:
```

**Comment by lorentey** [comment]
@swift-ci smoke test Linux platform

**Comment by lorentey** [comment]
@swift-ci smoke test Linux platform

**Comment by lorentey** [comment]
@swift-ci smoke test

**Comment by lorentey** [comment]
Hm, 🤔 

```
+ env GIT_TERMINAL_PROMPT=0 git clone --recursive https://github.com/KitWare/CMake.git cmake
Cloning into 'cmake'...
fatal: unable to access 'https://github.com/KitWare/CMake.git/': Failed to connect to github.com port 443 after 131117 ms: Connection timed out
```

**Comment by lorentey** [comment]
@swift-ci smoke test linux platform

**Pull request merged**
