### PR TITLE
[5.1] [Serialization] Recover when a typealias can't be deserialized

### PR DESCRIPTION
**Pull request by jrose-apple**
Cherry-pick of #23419 to the 5.1 branch. Reviewed by @harlanhaskins and @slavapestov.

[SR-9811](https://bugs.swift.org/browse/SR-9811)

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test macOS

**Comment by jrose-apple** [comment]
@swift-ci Please clean test macOS

**Comment by jrose-apple** [comment]
@devincoughlin, the failures are in configuring? copying? scan-build helper files. Is this a known issue?

**Comment by devincoughlin** [comment]
This isn't a known issue. It looks like other OS X PR tests are failing when copying other (non-scan-build) files, so I think something odd is going on here.

**Comment by jrose-apple** [comment]
@dexonsmith, who's responsible for Clang CMake stuff these days?

**Comment by devincoughlin** [comment]
I talked about this with @shahmishal and he is investigating. The CMake copy actions are getting killed. He is rebooting the node to see if that fixes the issue.

**Comment by jrose-apple** [comment]
@swift-ci Please test macOS

**Comment by jrose-apple** [comment]
@swift-ci Please test macOS

**Pull request merged**
