### PR TITLE
[docs] Fix WindowsBuild.md

### PR DESCRIPTION
**Pull request by stevapple**
Fix the problems of `docs/WindowsBuild.md`

Resolves SR-NNNN.

### CODE REVIEW

**Comment by stevapple** [comment]
CC @compnerd

**Review by compnerd — APPROVED** [review]
Thanks for updating this.  swift-driver switched to argument-parser yesterday requiring the reorder.

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
