### PR TITLE
[4.0] Don't consider KeyPathApplication operations when looking up non-SubscriptExprs.

### PR DESCRIPTION
**Pull request by jckarter**
Explanation: Introducing the global key path subscript operation introduced an ambiguity bug for code that tried to reference functions named `subscript` (using backtick quoted identifiers). This is fixed more deeply on master by #9989; this is a focused compatibility fix for 4.0.

Scope: Source compatibility regression; impacts ability to use AppKit because `NSText` has a `-subscript:` action.

Issue: SR-5513 | rdar://problem/33413614

Risk: Low, targeted bug fix

Testing: Swift CI, example from Jira

### CODE REVIEW

**Comment by jckarter** [comment]
@xedin Does this look ok for 4.0?

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test source compatibility

**Review by xedin — APPROVED** [review]
LGTM!

**Pull request merged**
