### PR TITLE
Playground Transform: Fix assertion failure in generic code

### PR DESCRIPTION
**Pull request by slavapestov**
This regression was introduced in the following commit:
<https://github.com/apple/swift/commit/6cbb494ad2eb2e6a2cf09b677b2d8d58e6fcaafa>

Fixes <rdar://problem/29935266>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by shahmishal** [comment]
@slavapestov 

Is this failure related to this PR? 

https://ci.swift.org/job/oss-swift-incremental-RA-osx/7872/console

```
PlaygroundLogger test suite: Some tests failed, aborting
UXPASS: []
FAIL: ["NSImageLogging", "SpriteKitLogging"]
```

```
--- Running PlaygroundLogger Tests ---
[ RUN      ] PlaygroundLogger test suite.VersionDecoding
stdout>>> --- Running PlaygroundLogger Tests ---
[       OK ] PlaygroundLogger test suite.VersionDecoding
[ RUN      ] PlaygroundLogger test suite.SourceRanges
[       OK ] PlaygroundLogger test suite.SourceRanges
[ RUN      ] PlaygroundLogger test suite.TIDSent
[       OK ] PlaygroundLogger test suite.TIDSent
[ RUN      ] PlaygroundLogger test suite.NameDecoding
[       OK ] PlaygroundLogger test suite.NameDecoding
[ RUN      ] PlaygroundLogger test suite.BaseTypesDecoding
[       OK ] PlaygroundLogger test suite.BaseTypesDecoding
[ RUN      ] PlaygroundLogger test suite.StructuredTypesDecoding
[       OK ] PlaygroundLogger test suite.StructuredTypesDecoding
[ RUN      ] PlaygroundLogger test suite.NSNumberDecoding
[       OK ] PlaygroundLogger test suite.NSNumberDecoding
[ RUN      ] PlaygroundLogger test suite.One+OneDecoding
[       OK ] PlaygroundLogger test suite.One+OneDecoding
[ RUN      ] PlaygroundLogger test suite.MetatypeLogging
[       OK ] PlaygroundLogger test suite.MetatypeLogging
[ RUN      ] PlaygroundLogger test suite.ExceptionSafety
[       OK ] PlaygroundLogger test suite.ExceptionSafety
[ RUN      ] PlaygroundLogger test suite.NSViewLogging
stderr>>> _RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
[       OK ] PlaygroundLogger test suite.NSViewLogging
[ RUN      ] PlaygroundLogger test suite.NSImageLogging
stdout>>> check failed at /Users/buildnode/jenkins/workspace/oss-swift-incremental-RA-osx/swift-xcode-playground-support/PlaygroundLogger/PlaygroundLogger/TestInfrastructure.swift, line 181
stdout>>> expected optional to be non-nil
stderr>>> fatal error: unexpectedly found nil while unwrapping an Optional value: file /Users/buildnode/jenkins/workspace/oss-swift-incremental-RA-osx/swift-xcode-playground-support/PlaygroundLogger/PlaygroundLogger/TestInfrastructure.swift, line 182
stderr>>> Current stack trace:
stderr>>> 0    libswiftCore.dylib                 0x0000000105755bb0 swift_reportError + 125
stderr>>> 1    libswiftCore.dylib                 0x0000000105776760 _swift_stdlib_reportFatalErrorInFile + 100
stderr>>> 2    libswiftCore.dylib                 0x000000010553d9d0 (_assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1).(closure #1).(closure #1) + 143
stderr>>> 3    libswiftCore.dylib                 0x000000010571a5d0 partial apply for (_fatalErrorMessage(StaticString, StaticString, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1).(closure #1).(closure #1) + 112
stderr>>> 4    libswiftCore.dylib                 0x000000010553ce90 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 342
stderr>>> 5    libswiftCore.dylib                 0x000000010571a510 partial apply for (_assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1).(closure #1) + 144
stderr>>> 6    libswiftCore.dylib                 0x000000010553ce90 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 342
stderr>>> 7    libswiftCore.dylib                 0x00000001056b9490 partial apply for (_fatalErrorMessage(StaticString, StaticString, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1) + 154
stderr>>> 8    libswiftCore.dylib                 0x000000010553ce90 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 342
stderr>>> 9    libswiftCore.dylib                 0x000000010553cd40 _fatalErrorMessage(StaticString, StaticString, file : StaticString, line : UInt, flags : UInt32) -> Never + 126
stderr>>> 10   PlaygroundLogger                   0x0000000105450770 static TestHelpers.unwrapOrFail<A> (A?) -> A + 759
stderr>>> 11   PlaygroundLogger                   0x00000001054266a0 NSImageLoggingTestCase.doTest() -> () + 369
stderr>>> 12   PlaygroundLogger                   0x0000000105426fe0 protocol witness for TestCase.doTest() -> () in conformance NSImageLoggingTestCase + 47
stderr>>> 13   PlaygroundLogger                   0x0000000105450710 (playground_logger_test() -> ()).(closure #1) + 70
stderr>>> 14   libswiftStdlibUnittest.dylib       0x00000001061d1ae0 specialized TestSuite._runTest(name : String, parameter : Int?) -> () + 521
stderr>>> 15   libswiftStdlibUnittest.dylib       0x000000010616e230 _childProcess() -> () + 2141
stderr>>> 16   libswiftStdlibUnittest.dylib       0x00000001061741a0 runAllTests() -> () + 717
stderr>>> 17   PlaygroundLogger                   0x000000010544e290 playground_logger_test() -> () + 7981
stderr>>> 18   PlaygroundLogger_TestDriver        0x0000000105408efb <unavailable> + 3835
stderr>>> 19   libdyld.dylib                      0x00007fff95eea5ac start + 1
stderr>>> CRASHED: SIGILL
the test crashed unexpectedly
[     FAIL ] PlaygroundLogger test suite.NSImageLogging
[ RUN      ] PlaygroundLogger test suite.SpriteKitLogging
stdout>>> --- Running PlaygroundLogger Tests ---
stdout>>> check failed at /Users/buildnode/jenkins/workspace/oss-swift-incremental-RA-osx/swift-xcode-playground-support/PlaygroundLogger/PlaygroundLogger/TestInfrastructure.swift, line 181
stdout>>> expected optional to be non-nil
stderr>>> fatal error: unexpectedly found nil while unwrapping an Optional value: file /Users/buildnode/jenkins/workspace/oss-swift-incremental-RA-osx/swift-xcode-playground-support/PlaygroundLogger/PlaygroundLogger/TestInfrastructure.swift, line 182
stderr>>> Current stack trace:
stderr>>> 0    libswiftCore.dylib                 0x000000010aed6bb0 swift_reportError + 125
stderr>>> 1    libswiftCore.dylib                 0x000000010aef7760 _swift_stdlib_reportFatalErrorInFile + 100
stderr>>> 2    libswiftCore.dylib                 0x000000010acbe9d0 (_assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1).(closure #1).(closure #1) + 143
stderr>>> 3    libswiftCore.dylib                 0x000000010ae9b5d0 partial apply for (_fatalErrorMessage(StaticString, StaticString, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1).(closure #1).(closure #1) + 112
stderr>>> 4    libswiftCore.dylib                 0x000000010acbde90 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 342
stderr>>> 5    libswiftCore.dylib                 0x000000010ae9b510 partial apply for (_assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1).(closure #1) + 144
stderr>>> 6    libswiftCore.dylib                 0x000000010acbde90 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 342
stderr>>> 7    libswiftCore.dylib                 0x000000010ae3a490 partial apply for (_fatalErrorMessage(StaticString, StaticString, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1) + 154
stderr>>> 8    libswiftCore.dylib                 0x000000010acbde90 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 342
stderr>>> 9    libswiftCore.dylib                 0x000000010acbdd40 _fatalErrorMessage(StaticString, StaticString, file : StaticString, line : UInt, flags : UInt32) -> Never + 126
stderr>>> 10   PlaygroundLogger                   0x000000010abd0770 static TestHelpers.unwrapOrFail<A> (A?) -> A + 759
stderr>>> 11   PlaygroundLogger                   0x000000010aba7270 SpriteKitLoggingTestCase.doTest() -> () + 1165
stderr>>> 12   PlaygroundLogger                   0x000000010aba8360 protocol witness for TestCase.doTest() -> () in conformance SpriteKitLoggingTestCase + 47
stderr>>> 13   PlaygroundLogger                   0x000000010abd0710 (playground_logger_test() -> ()).(closure #1) + 70
stderr>>> 14   libswiftStdlibUnittest.dylib       0x000000010b991ae0 specialized TestSuite._runTest(name : String, parameter : Int?) -> () + 521
stderr>>> 15   libswiftStdlibUnittest.dylib       0x000000010b92e230 _childProcess() -> () + 2141
stderr>>> 16   libswiftStdlibUnittest.dylib       0x000000010b9341a0 runAllTests() -> () + 717
stderr>>> 17   PlaygroundLogger                   0x000000010abce290 playground_logger_test() -> () + 7981
stderr>>> 18   PlaygroundLogger_TestDriver        0x000000010ab86efb <unavailable> + 3835
stderr>>> 19   libdyld.dylib                      0x00007fff95eea5ac start + 1
stderr>>> CRASHED: SIGILL
the test crashed unexpectedly
[     FAIL ] PlaygroundLogger test suite.SpriteKitLogging
```

**Comment by aschwaighofer** [comment]
@slavapestov I have speculatively reverted the commit because it seems to have caused the failure in

https://ci.swift.org/job/oss-swift-incremental-RA-osx/7872

**Pull request merged**
