### PR TITLE
Temporarily disable validation-test/stdlib/ModelIO.swift

### PR DESCRIPTION
**Pull request by benlangmuir**
This has been crashing sometimes in CI. Disable it until we get a real fix.

### CODE REVIEW

**Comment by benlangmuir** [comment]
@swift-ci please smoke test

**Comment by benlangmuir** [comment]
CC @lorentey

**Comment by shahmishal** [comment]
@swift-ci please smoke test macOS

**Comment by benlangmuir** [comment]
@swift-ci please smoke test macOS

**Review by lorentey — APPROVED** [review]

**Comment by benlangmuir** [comment]
@swift-ci please smoke test

**Comment by benlangmuir** [comment]
@swift-ci please smoke test Linux

**Pull request merged**
