### PR TITLE
[sil] Add a run of ownership model eliminator in the lowering pass pi…

### PR DESCRIPTION
**Pull request by gottesmm**
…peline to ensure we eliminate ownership even if a bisecting counter has disabled the normal ome run.

Just ran into this while trying to bisect.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
weird lldb error. I am going to actually do a full test of this.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
More weird lldbness.

**Comment by gottesmm** [comment]
All of the tests pass on os x. Just failed in lldb.

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Comment by gottesmm** [comment]
again the lldb test failure. The lldb test failure was fixed in:

https://github.com/apple/llvm-project/pull/24

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Review by atrick — COMMENTED** [review]
Makes sense.

@gottesmm Also, this pass should be in `Mandatory` since it's required for codegen.

**Comment by gottesmm** [comment]
@atrick SGTM

**Comment by gottesmm** [comment]
@atrick SGTM

**Comment by gottesmm** [comment]
@atrick #27916

**Pull request merged**
