### PR TITLE
Merging swift-DEVELOPMENT-SNAPSHOT-2020-01-27-a into tensorflow

### PR DESCRIPTION
**Pull request by shabalind**

### CODE REVIEW

**Comment by burmako** [comment]
@swift-ci please clean test tensorflow

**Review by burmako — APPROVED** [review]

**Review by dan-zheng — APPROVED** [review]
LGTM! I reviewed only `utils/update_checkout/update-checkout-config.json`.

**Comment by burmako** [comment]
@swift-ci please clean test tensorflow

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow macos

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Pull request merged**
