### PR TITLE
[stdlib] Unify _NativeDictionary.subscript._modify’s two yields to work around SR-10604

### PR DESCRIPTION
**Pull request by lorentey**
https://bugs.swift.org/browse/SR-10604
rdar://problem/52529030

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
Sadly, there is no easy way to count mallocs in the test suite right now, so I need to defer adding tests until we tackle https://bugs.swift.org/browse/SR-10709.

I verified this works through dtrace.

**Review by rjmccall — COMMENTED** [review]
LGTM from the ownership side.

**Review by Catfish-Man — APPROVED** [review]
Huh, somewhat unfortunate that the existing code didn't work out, but yeah this looks fine.

**Pull request merged**
