### PR TITLE
[sil-performance-inliner] Fix recent performance regressions

### PR DESCRIPTION
**Pull request by swiftix**
Do not perform any inlining of generics if it is not enabled. Don't do it even for always inline functions.

### CODE REVIEW

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by slavapestov** [comment]
Why not? Isn't the whole point of always inline that the function is always inline?

**Comment by swiftix** [comment]
@slavapestov Because inlining of generics is not enabled yet. Doing it only partially for always inline functions regresses the performance. The subsequent patch will enable it by default everywhere in one go.

**Comment by swiftix** [comment]
@swift-ci please smoke test Linux

**Pull request merged**
