### PR TITLE
[Syntax] Add #selector and #keyPath tokens

### PR DESCRIPTION
**Pull request by harlanhaskins**
Seems I missed these while writing `Token.py` originally. This is needed to avoid crashing while deserializing tokens.

### CODE REVIEW

**Comment by harlanhaskins** [comment]
@swift-ci please test

**Comment by harlanhaskins** [comment]
@swift-ci please clean smoke test

**Comment by harlanhaskins** [comment]
@swift-ci please test

**Review by rintaro — APPROVED** [review]
Thank you!

**Pull request merged**
