### PR TITLE
Make ImplicitlyUnwrappedOptional<T> an unavailable typealias.

### PR DESCRIPTION
**Pull request by rudkx**
Also remove the decl from the known decls and remove a
bunch of code referencing that decl as well as a bunch of other
random things including deserialization support.

This includes removing some specialized diagnostics code that
matched the identifier ImplicitlyUnwrappedOptional, and tweaking
diagnostics for various modes and various issues.

Fixes most of rdar://problem/37121121, among other things.

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
Ahh, LLDB.

**Comment by vedantk** [comment]
@rudkx The lldb/stable branch is in bad shape at the moment. We also recently enabled gated commits to the stable branch...

I'll talk to some folks about changing the lldb bot configuration. If we run the same subset of lldb tests run during smoke testing, you should be able to merge your lldb change.

**Comment by vedantk** [comment]
(See rdar://37034568 for context on why the stable branch is in bad health -- we're working on it.)

**Comment by vedantk** [comment]
@swift-ci Please smoke test

**Pull request merged**
