### PR TITLE
[interface-gen] Support passing Swift compiler arguments for header file interface generation

### PR DESCRIPTION
**Pull request by nathawes**
To support having Swift main files for ObjC header files included via the bridging header, add a flag to indicate whether the compiler arguments passed to interface generation for header files are Clang or Swift compiler arguments.

Resolves rdar://problem/33249361.

### CODE REVIEW

**Comment by nathawes** [comment]
@swift-ci Please smoke test

**Review by akyrtzi — APPROVED** [review]
LGTM

**Comment by nathawes** [comment]
@swift-ci Please smoke test

**Comment by nathawes** [comment]
@swift-ci smoke test OS X

**Pull request merged**
