### PR TITLE
omitNeedlessWords: Several clarifying improvements to type name matching

### PR DESCRIPTION
**Pull request by jrose-apple**
In writing up CToSwiftNameTranslation.md, I want to describe the omit-needless-words algorithm, at least as a high level, which meant that I had to understand it first. The code was fairly well-commented already, but that didn't stop it from being complicated. I think the refactorings I've done here have simplified the type name matching parts quite a bit, mainly by breaking them up into smaller composable pieces.

No intended functionality change.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by jrose-apple** [comment]
Debug UPASS is the same as on master.

**Review by DougGregor — APPROVED** [review]
This looks great, thank you for cleaning it up!

**Review by xymus — APPROVED** [review]

**Pull request merged**
