### PR TITLE
[TypeConverter] Track address lowering.

### PR DESCRIPTION
**Pull request by nate-chandler**
When opaque values are enabled, `TypeConverter` associates to an address-only type an `OpaqueValueTypeLowering`.  That lowering stores a single lowered SIL type, and its value category is "object".  So long as the module has not yet been address-lowered, that type has the appropriate value category.  After the module has been address-lowered, however, that type has the wrong value category: the type is address-only, and in an address-lowered module, its lowered type's value category must be "address".

Code that obtains a lowered type expects the value category to reflect the state of the module.  So somewhere, it's necessary to fixup that single lowered type's value category.

One option would be to update all code that uses lowered types.  That would require many changes across the codebase and all new code that used lowered types would need to account for this.

Another option would be to update some popular conveniences that call through to `TypeConverter`, for example those on SILFunction, and ensure that all code used those conveniences.  Even if this were done completely, it would be easy enough for new code to be added which didn't use the conveniences.

A third option would be to update `TypeLowering::getLoweredType` to take in the context necessary to determine whether the stored SILType should be fixed up.  That would require each callsite to be changed and potentially to carry around more context than it already had in order to be able to pass it along.

A fourth option would be to make `TypeConverter` aware of the address-loweredness, and to update its state at the end of AddressLowering.

Updating `TypeConverter`'s state would entail updating all cached `OpaqueValueTypeLowering` instances.  Additionally, when `TypeConverter` produces new `OpaqueValueTypeLowerings`, they would need to have the "address" value category from creation.

Of all the options, the last is least invasive and least error-prone, so it is taken here.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test macOS platform

**Review by atrick — COMMENTED** [review]
LGTM thanks!

**Pull request merged**
