### PR TITLE
[Sema] Protect dereferencing null TypeReprs in associated type diagnostics

### PR DESCRIPTION
**Pull request by xymus**
rdar://74446387

### CODE REVIEW

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
Can you add a test case?

**Comment by xymus** [comment]
We should be able to reproduce the failure if the default type is read from a serialized module. But I don't know how to actually trigger this diagnostic, it doesn't appear to be tested currently even for normal source files.

@slavapestov Would you know how to trigger an associated type inference ambiguity that involves the default type and get a `diag::associated_type_deduction_default`?

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by xymus** [comment]
@swift-ci Please smoke test Windows

**Pull request merged**
