### PR TITLE
Runtime: Refactor NominalTypeDescriptor to use TrailingObjects.

### PR DESCRIPTION
**Pull request by jckarter**
NFC intended. The layout of trailing matter here is getting fairly complex, so it's good to use LLVM's existing library code to keep track of it.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by gparker42** [comment]
Does the TrailingObjects machinery establish a sufficiently-stable ABI? We don't want these structs to be laid out differently after some future LLVM update.

**Comment by jckarter** [comment]
Good question. It ought to just do the `roundUpToAlignment(this + 1)` stuff you'd do manually, but LLVM doesn't have a track record of generally caring about ABI. It's a header-only template so we could fork it into a runtime-specific version to lower the chance of it breaking.

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
Changed to use a runtime-specific copy of TrailingObjects.

**Pull request merged**
