### PR TITLE
Handle loads in salvageDebugInfo and enable it in splitAggregateLoad

### PR DESCRIPTION
**Pull request by atrick**
Fixes a know issue in which load splitting drops debug info.

    After splitting the load, invoke the improved salvageLoadDebugInfo, which
    now creates a new debug_value instruction for the loaded memory
    location, inserting a dereference expression if needed.

    This fixes debug information for both -Onone debugging.

Fixes rdar://104700920 (At -Onone preserve debug info after splitting loads)
Issue: LLDB missing variables in certain case #62241

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci benchmark

**Comment by atrick** [comment]
@swift-ci test source compatibility

**Review by adrian-prantl — APPROVED** [review]

**Comment by atrick** [comment]
@swift-ci smoke test

**Comment by atrick** [comment]
@swift-ci smoke test macOS

**Pull request merged**
