### PR TITLE
DNM: testing apple/swift-installer-scripts#112

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-instaler-scripts#112

@swift-ci please build toolchain windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#3165

@swift-ci please test Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-corelibs-foundation/pull/3165

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift#42265
apple/swift-installer-scripts#115

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:

https://github.com/apple/swift-installer-scripts/pull/116
https://github.com/apple/swift-installer-scripts/pull/117

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-package-manager#4299

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/128

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/126

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/125

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/120

@swift-ci please build toolchain Windows platform

**Comment by shahmishal** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/120

@swift-ci please build toolchain Windows platform

**Pull request closed without merging**
