### PR TITLE
IUO: Update swift-api-digester for the removal of IUOs from the type …

### PR DESCRIPTION
**Pull request by rudkx**
…system.

When IUOs actually go away I will commit changes to these tests for
the mangling difference:
```
  test/api-digester/Outputs/macro-gen.def
  test/api-digester/Outputs/macro-gen.json
```

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@nkcsgexi Let me know if this looks okay. This is attempting to maintain the ability to detect changes in optionality after ImplicitlyUnwrappedOptionalType is removed from the type system (and is just maintained as an attribute on VarDecl and AbstractFunctionDecl.

**Comment by rudkx** [comment]
@nkcsgexi I'm going to merge - let me know if you see anything wrong here. Thanks!

**Comment by nkcsgexi** [comment]
Sorry for not reviewing this early. This change LGTM! @rudkx

**Comment by rudkx** [comment]
@nkcsgexi No worries! I'm always happy to merge-and-fix-later-or-revert and don't expect anybody to jump on reviewing a change.

**Pull request merged**
