### PR TITLE
swift-module-digester: reenable test for Json serialization diagnostics.

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
preset=buildbot,tools=R,stdlib=RD,smoketest=macosx,single-thread
@swift-ci Please test with preset macOS

**Comment by nkcsgexi** [comment]
preset=buildbot,tools=R,stdlib=RD,smoketest=macosx,single-thread
@swift-ci Please test with preset macOS

**Comment by nkcsgexi** [comment]
@shahmishal any idea why the preset test runner has thrown exception twice in a row? I'd like to run a smoke test with the same setting here: https://ci.swift.org/job/oss-swift_tools-R_stdlib-RD_test-simulator/.

**Comment by shahmishal** [comment]
preset=buildbot,tools=R,stdlib=RD
@swift-ci Please test with preset macOS

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Pull request merged**
