### PR TITLE
ASTPrinter: Refactor the definition of SynthesizedExtensionAnalyzer to IDETypeChecking.cpp. NFC

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by slavapestov** [comment]
Thanks! There might also be some #includes you can remove now?

**Comment by nkcsgexi** [comment]
We don't have many includes to move just by refactoring this. We plan to refactor more and then some includes can be cleaned.

**Comment by slavapestov** [comment]
It seems at the very least, you can remove this:

#include "swift/Sema/IDETypeChecking.h"

**Comment by nkcsgexi** [comment]
Not really
swift/lib/AST/ASTPrinter.cpp:59:12: error: use of undeclared identifier 'isExtensionApplied'
    return isExtensionApplied(*T->getNominalOrBoundGenericNominal()->

**Pull request merged**
