### PR TITLE
Add Windows target and toolchain to build-script

### PR DESCRIPTION
**Pull request by hughbe**
We'll need to change the compilers we look for on Windows - this is because currently we look for `clang`, which is unsupported on Windows. Instead we should look for `cl` (MSVC) or `clang-cl` (Windows clang driver).

However, we don't seem to have an option here: https://github.com/apple/swift/blob/master/utils/swift_build_support/swift_build_support/toolchain.py#L48 to conditionally change the compiler we look for on Windows. So I'll delay this for a future PR as it may require some refactoring.

Also, with this change, we choke later on down the line trying to run `build-script-impl`. It's not supported, as it's a bash script!

### CODE REVIEW

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by erg** [comment]
Is it easier to just use ``clang-cl`` instead of worrying about support for ``cl``?

**Comment by compnerd** [comment]
@erg I think that would be easier.  However, it is possible to go even further.  It is possible to use the clang driver and still build for windows without having to worry about the various flags being different.

**Comment by hughbe** [comment]
Cmake, at least more me, chokes and doesn't seem to work when trying to use clang on Windows but clang-cl works fine. I suggest we prefer clang-cl.

**Comment by compnerd** [comment]
@hughbe what exactly do you mean that cmake chokes on it?

**Comment by hughbe** [comment]
Pushed an update to use clang-cl on Windows

**Comment by hughbe** [comment]
In terms of using clang.exe/clang++.exe on Windows and CMake choking when we use it:

```
cmake -G"Ninja"^
  -DCMAKE_C_COMPILER="C:/Users/hughb/Documents/GitHub/swift/build-msvc/Ninja-DebugAssert/llvm-windows-x86_64/bin/clang.exe"^
  -DCMAKE_CXX_COMPILER="C:/Users/hughb/Documents/GitHub/swift/build-msvc/Ninja-DebugAssert/llvm-windows-x86_64/bin/clang++.exe"
```

emits the following CMake generation errors
```
-- The C compiler identification is Clang 4.0.0
-- The CXX compiler identification is Clang 4.0.0
-- Check for working C compiler: C:/Users/hughb/Documents/GitHub/swift/build-msvc/Ninja-DebugAssert/llvm-windows-x86_64/bin/clang.exe
-- Check for working C compiler: C:/Users/hughb/Documents/GitHub/swift/build-msvc/Ninja-DebugAssert/llvm-windows-x86_64/bin/clang.exe -- broken
CMake Error at C:/Program Files/CMake/share/cmake-3.6/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler
  "C:/Users/hughb/Documents/GitHub/swift/build-msvc/Ninja-DebugAssert/llvm-windows-x86_64/bin/clang.exe"
  is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: C:/Users/hughb/Desktop/stuff/CMakeFiles/CMakeTmp



  Run Build Command:"C:/Users/hughb/Documents/Utilities/ninja.exe"
  "cmTC_fe176"

  [1/2] Building C object CMakeFiles\cmTC_fe176.dir\testCCompiler.c.obj

  FAILED: CMakeFiles/cmTC_fe176.dir/testCCompiler.c.obj


  C:\Users\hughb\Documents\GitHub\swift\build-msvc\Ninja-DebugAssert\llvm-windows-x86_64\bin\clang.exe
  /nologo /DWIN32 /D_WINDOWS /W3 /D_DEBUG /MDd /Zi /Ob0 /Od /RTC1
  /showIncludes /FoCMakeFiles\cmTC_fe176.dir\testCCompiler.c.obj
  /FdCMakeFiles\cmTC_fe176.dir\ -c testCCompiler.c

  clang.exe: error: no such file or directory: '/nologo'

  clang.exe: error: no such file or directory: '/DWIN32'

  clang.exe: error: no such file or directory: '/D_WINDOWS'

  clang.exe: error: no such file or directory: '/W3'

  clang.exe: error: no such file or directory: '/D_DEBUG'

  clang.exe: error: no such file or directory: '/MDd'

  clang.exe: error: no such file or directory: '/Zi'

  clang.exe: error: no such file or directory: '/Ob0'

  clang.exe: error: no such file or directory: '/Od'

  clang.exe: error: no such file or directory: '/RTC1'

  clang.exe: error: no such file or directory: '/showIncludes'

  clang.exe: error: no such file or directory:
  '/FoCMakeFiles\cmTC_fe176.dir\testCCompiler.c.obj'

  clang.exe: error: no such file or directory:
  '/FdCMakeFiles\cmTC_fe176.dir\'

  ninja: build stopped: subcommand failed.





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt


-- Configuring incomplete, errors occurred!
See also "C:/Users/hughb/Desktop/stuff/CMakeFiles/CMakeOutput.log".
See also "C:/Users/hughb/Desktop/stuff/CMakeFiles/CMakeError.log".
```

**Comment by hughbe** [comment]
@swift-ci please clean smoke test

**Comment by hughbe** [comment]
@swift-ci please clean smoke test

**Comment by hughbe** [comment]
... then changing the generation script to:
```
cmake -G"Ninja"^
  -DCMAKE_C_COMPILER="C:/Users/hughb/Documents/GitHub/swift/build-msvc/Ninja-DebugAssert/llvm-windows-x86_64/bin/clang.exe"^
  -DCMAKE_CXX_COMPILER="C:/Users/hughb/Documents/GitHub/swift/build-msvc/Ninja-DebugAssert/llvm-windows-x86_64/bin/clang++.exe"^
  -DCMAKE_C_COMPILER_ID="Clang"^
  -DCMAKE_C_COMPILER_FORCED=TRUE^
  -DCMAKE_CXX_COMPILER_ID="Clang"^
  -DCMAKE_CXX_COMPILER_FORCED=TRUE
```

causes the following erors linking a test project
```
[2/2] Linking CXX executable Hello.exe
FAILED: Hello.exe
cmd.exe /C "cd . && C:\Users\hughb\Documents\GitHub\swift\build-msvc\Ninja-DebugAssert\llvm-windows-x86_64\bin\clang++.exe  -g  /machine:x64 /debug /INCREMENTAL CMakeFiles\Hello.dir\helloworld.cpp.obj  -o Hello.exe -Wl,--out-implib,libHello.dll.a -Wl,--major-image-version,0,--minor-image-version,0   && cd ."
clang++.exe: error: no such file or directory: '/machine:x64'
clang++.exe: error: no such file or directory: '/debug'
clang++.exe: error: no such file or directory: '/INCREMENTAL'
ninja: build stopped: subcommand failed.
```

Clang-cl works out of the box, doesn't require us to force everything

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by hughbe** [comment]
@swift-ci please clean smoke test

**Comment by hughbe** [comment]
@swift-ci please clean smoke test

**Comment by hughbe** [comment]
@swift-ci please clean smoke test

**Review by erg — COMMENTED** [review]
Looks fine for now.

**Pull request merged**
