### PR TITLE
[5.5] Support Xcode 13 beta

### PR DESCRIPTION
**Pull request by shahmishal**
* Updating availability versions
* Remove all remaining overlays in stdlib/public/Darwin/*:
   - ObjectiveC
   - Dispatch
   - CoreFoundation
   - CoreGraphics
   - Foundation
   - XCTest

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Review by lorentey — APPROVED** [review]
Looks good to me! 👍

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci clean test

**Comment by shahmishal** [comment]
https://github.com/apple/llvm-project/pull/3031
@swift-ci clean test macOS

**Pull request merged**
