### PR TITLE
DeserializeSIL: Fix two places where we want the SILType inside of the current function according to the TypeExpansionContext

### PR DESCRIPTION
**Pull request by aschwaighofer**
rdar://58095210

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
Thank you for the quick fix!

**Comment by aschwaighofer** [comment]
@swift-ci Please test os x

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Pull request merged**
