### PR TITLE
Ensure that partial_apply of partial_apply does not produce conservative global side effects

### LINKED ISSUE #62249: Performance regression in autodiff code due to inlining
After 0403a21d341566e132b119436b9100212729b9ad we are seeing performance regression due to some derivatives are not inlined anymore. Basically, the function previously was considered pure (and therefore inlined) and now – not.

Consider the code attached. Before 0403a21d341566e132b119436b9100212729b9ad all 5 variants were perfectly inlined and therefore optimized. After 0403a21d341566e132b119436b9100212729b9ad `$s5bench15eightOperations1aS2f_tFTJrSpSr` is not considered pure and therefore not inlined. This causing like 10x regression in performance.

[bench.swift.txt](https://github.com/apple/swift/files/10094896/bench.swift.txt)

### PR DESCRIPTION
**Pull request by asl**
Fixes #62249

### CODE REVIEW

**Comment by asl** [comment]
@swift-ci please test

**Comment by asl** [comment]
Tagging @BradLarson

**Comment by asl** [comment]
@swift-ci please benchmark

**Comment by asl** [comment]
@swift-ci please test macos

**Review by eeckstein — APPROVED** [review]
lgtm, thanks!

**Comment by eeckstein** [comment]
@swift-ci please test macos

**Pull request merged**
