### PR TITLE
[refactoring] Run refactoring tests on Linux

### PR DESCRIPTION
**Pull request by ahoppen**
Refactoring tests have been disabled on Linux but I can’t find a reason why that should be the case. Enable them on all platforms.

rdar://92982631

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please smoke test Linux

**Comment by ahoppen** [comment]
@swift-ci Please smoke test Windows

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@akyrtzi Do you remember why the refactoring tests weren’t run on platforms other than macOS before?

**Review by rintaro — APPROVED** [review]

**Pull request merged**
