### PR TITLE
Rework swift-stress-tester repo building

### PR DESCRIPTION
**Pull request by beccadax**
This change makes build-script-impl use a new, shared version of swift-stress-tester’s build-script-helper.py which also supports building swift-evolve. It also adds the necessary flags and variables to build swift-evolve from build-script.

This PR depends on apple/swift-stress-tester#26, which moves the script to its new location and leaves a shim at the old name for compatibility. That PR has now landed, so this one can be merged when ready.

To do:

- [ ] Get this reviewed by someone who knows their way around build-script
- [x] Land the matching commit first

### CODE REVIEW

**Comment by brentdax** [comment]
Please test with following pull request:
https://github.com/apple/swift-stress-tester/pull/26

@swift-ci Please Build Toolchain macOS Platform

**Comment by brentdax** [comment]
(Using the toolchain build to test that swift-stress-tester will still build with these changes.)

**Comment by brentdax** [comment]
Please test with following pull request:
apple/swift-stress-tester#26

@swift-ci Please Build Toolchain macOS Platform

**Comment by brentdax** [comment]
@swift-ci please smoke test

**Comment by brentdax** [comment]
@swift-ci please build toolchain

**Comment by brentdax** [comment]
I'm not sure why the toolchain builds still show "pending"—they finished last night. [Linux](
https://ci.swift.org/job/swift-PR-toolchain-Linux/118//artifact/branch-master/swift-PR-21523-118-ubuntu16.04.tar.gz), [macOS](
https://ci.swift.org/job/swift-PR-toolchain-osx/157//artifact/branch-master/swift-PR-21523-157-osx.tar.gz)

**Comment by shahmishal** [comment]
@brentdax This is a known issue, I will try to look into this issue. However, you should be able to download the toolchain.

**Pull request merged**
