### PR TITLE
test: repair the test after accidental merge without testing

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
CC: @aschwaighofer

**Comment by compnerd** [comment]
@swift-ci please smoke test macOS platform

**Comment by compnerd** [comment]
@swift-ci please smoke test macOS platform

**Comment by aschwaighofer** [comment]
I didn't know we had %target-abi. This is more reasonable then %target-os would have been.

**Comment by compnerd** [comment]
@aschwaighofer yeah, we added that when I was originally doing all the ABI conversions to support Windows.  Sounds good!  Not sure if there is a better way to check the various different ABIs.

**Pull request merged**
