### PR TITLE
[interop] Configure libstdc++ module map at runtime

### PR DESCRIPTION
**Pull request by hyp**
configure the module map dynamically.

### CODE REVIEW

**Comment by hyp** [comment]
@swift-ci please test Linux platform

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test windows platform

**Comment by hyp** [comment]
@swift-ci please test source compatibility

**Comment by compnerd** [comment]
This caused a regression for Windows which uses the unified build.

**Pull request merged**
