### PR TITLE
More cleanups for Codable and CaseIterable

### PR DESCRIPTION
**Pull request by slavapestov**
More cleanups based off of https://github.com/apple/swift/pull/16049.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Review by xedin — APPROVED** [review]
Looks great, @slavapestov! Commit messages were really helpful to understand why some of the handling has been removed!

**Comment by itaiferber** [comment]
@slavapestov Thanks for the cleanups! Currently going through these PRs to review; looks like I didn't get to this one in time.

Out of curiosity, what changed around these code paths that we can now avoid synthesizing `init(from:)` in `addImplicitConstructors`? This affected lookup before; why doesn't it now?

**Pull request merged**
