### PR TITLE
[Test] Use --allow-empty in crash_without_backtrace_optimized.swift.

### PR DESCRIPTION
**Pull request by mikeash**
rdar://problem/51076215

### CODE REVIEW

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by gottesmm** [comment]
Mike, can you perform not just a full test, but also use the custom preset swift-ci command to test this without assertions. Also I just merged to master a commit that disabled the test so you probably need to rebase this change (delete the REQUIRES line) and restart the testing.

**Comment by mikeash** [comment]
preset=buildbot,tools=RA,stdlib=RD
@swift-ci please test with preset macOS platform

**Comment by mikeash** [comment]
preset=buildbot,tools=RA,stdlib=RD
@swift-ci please test with preset Linux platform

**Comment by mikeash** [comment]
Passed with the presets. Running normal tests and merging (if they're OK too).

**Comment by mikeash** [comment]
@swift-ci please test

**Pull request merged**
