### PR TITLE
Disable ASAN on the LLVM build, keep it on Swift.

### PR DESCRIPTION
**Pull request by nadavrot**

### CODE REVIEW

**Comment by nadavrot** [comment]
When enabling ASAN on LLVM it does not build the asan libraries, and this means
that we can't use it to sanitize swift. This change disables ASAN on the
internal clang but keeps it on the Swift project.

**Comment by nadavrot** [comment]
@swift-ci Please test

**Comment by gribozavr** [comment]
Why can't we use ASan for the LLVM?  LLVM is always built with the Xcode toolchain, which has the ASan runtime.

**Comment by nadavrot** [comment]
> On Mar 31, 2016, at 5:14 PM, Dmitri Gribenko <notifications@github.com> wrote:
> 
> Why can't we use ASan for the LLVM? LLVM is always built with the Xcode toolchain, which has the ASan runtime.
> 
> 

LLVM in the toolchain is built with support for sanitizing the generated apps, not sanitizing itself.  There is a check in compiler-rt that says that if LLVM itself is sanitized then it can’t build the sanitizers.

**Comment by gribozavr** [comment]
Hm, that's a silly limitation.  It should just not use sanitizers while building sanitizers.  I guess we'd need to build LLVM twice: first, to build the new sanitizers, and second, to build a sanitized version of LLVM.

**Comment by nadavrot** [comment]
I don't think it's worth the compile time. Do we really want to sanitize the x86 backhand as part of Swift?  How many address-sanitizer bugs have we have in LLVM as part of the Swift project that were not discovered by LLVM.org ?

**Comment by nadavrot** [comment]
@swift-ci Please test and merge

**Comment by gribozavr** [comment]
C++ is not a safe language.  It is easy to have an issue in Swift that would only be caught by instrumenting LLVM.  For example, creating an invalid source buffer, and then using libSupport methods on it.

**Comment by tkremenek** [comment]
I think we need to discuss this change more before landing it.  The Swift compiler uses data structures from LLVM that implemented in both .cpp and .h files.  While contents of header files will be inlined into the translation units of .cpp files in the Swift compiler, anything that is part of the LLVM codebase proper as .cpp files will not be instrumented.  This means that things like SmallVector won't get properly instrumented, which could majorly compromise the efficacy of using Address Sanitizer.

I am going to revert this change.  I think the change is well-intended, but I think this needs to be discussed more before making it.

**Comment by nadavrot** [comment]
Reverting this pull request broke the ASAN bot.  I am going to disable the use of the just-built clang altogether.

**Comment by tkremenek** [comment]
Thanks @nadavrot.

**Comment by nadavrot** [comment]
It looks like the building the swift-sanitized without llvm-sanitized exposed a bug in swift:

https://smooshbase.apple.com/swiftci/job/swift-asan-RDA/3418/console

**Pull request merged**
