### PR TITLE
[SIL Diagnostics] Fix undefined behavior due to bit shifting in ConstantFolding.cpp

### PR DESCRIPTION
**Pull request by ravikandhadai**
<rdar://48605307>

### CODE REVIEW

**Comment by ravikandhadai** [comment]
@swift-ci Please test

**Review by aschwaighofer — APPROVED** [review]
lgtm

**Comment by ravikandhadai** [comment]
@swift-ci Please test and merge

**Comment by ravikandhadai** [comment]
@swift-ci Please clean test OS X platform

**Comment by ravikandhadai** [comment]
@swift-ci Please clean test OS X platform

**Comment by ravikandhadai** [comment]
@swift-ci Please test and merge

**Comment by ravikandhadai** [comment]
@swift-ci Please test macOS Platform and merge

**Comment by ravikandhadai** [comment]
@swift-ci Please test and merge

**Pull request merged**
