### PR TITLE
Cherry-pick some bug fixes to the 4.1 branch

### PR DESCRIPTION
**Pull request by slavapestov**
I put these into master recently.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
```
../buildbot_linux/foundation-linux-x86_64/Foundation/CoreFoundation/Base.subproj/CFBase.c.o:(.cfstrlit.data+0x0): undefined reference to `$S10Foundation19_NSCFConstantStringCN'
../buildbot_linux/foundation-linux-x86_64/Foundation/CoreFoundation/Base.subproj/CFBase.c.o:(.cfstrlit.data+0x28): undefined reference to `$S10Foundation19_NSCFConstantStringCN'
../buildbot_linux/foundation-linux-x86_64/Foundation/CoreFoundation/Base.subproj/CFBase.c.o:(.cfstrlit.data+0x50): undefined reference to `$S10Foundation19_NSCFConstantStringCN'
../buildbot_linux/foundation-linux-x86_64/Foundation/CoreFoundation/Base.subproj/CFFileUtilities.c.o:(.cfstrlit.data+0x0): undefined reference to `$S10Foundation19_NSCFConstantStringCN'
../buildbot_linux/foundation-linux-x86_64/Foundation/CoreFoundation/Base.subproj/CFFileUtilities.c.o:(.cfstrlit.data+0x28): undefined reference to `$S10Foundation19_NSCFConstantStringCN'
../buildbot_linux/foundation-linux-x86_64/Foundation/CoreFoundation/Base.subproj/CFFileUtilities.c.o:(.cfstrlit.data+0x50): more undefined references to `$S10Foundation19_NSCFConstantStringCN' follow
```

@eeckstein @parkera Looks like we need to revert the foundation mangling change in swift-4.1-branch, since foundation auto-merges master into swift-4.1-branch. Can one of you take a look at this tomorrow?

**Comment by parkera** [comment]
It was my understanding that auto merging from master to swift-4.1 was supposed to be off as of a few weeks ago. @shahmishal can you check on that?

**Comment by eeckstein** [comment]
@slavapestov Thanks for the notification.
I reverted the change on the swift-4.1-branch

**Comment by shahmishal** [comment]
master -> swift-4.1-branch is still being auto merged for swift-corelib-* repos, however we stopped auto merging for swift repo.

**Comment by slavapestov** [comment]
@swift-ci Please test Linux

**Pull request merged**
