### PR TITLE
cmake/caches: Update `Runtime-WASI-wasm32.cmake`

### PR DESCRIPTION
**Pull request by MaxDesiatov**
Disable features that are currently not available for this platform.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci build toolchain

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
preset=buildbot_incremental_linux_crosscompile_wasm
@swift-ci Please test with preset Linux Platform

**Comment by Toppole6** [comment]
Best Regards,

Adrian Imach

**Review by kateinoigakukun — APPROVED** [review]

**Pull request merged**
