### PR TITLE
Fix silcombine of inject_enum_addr when we have an empty struct with unreferenceable storage

### PR DESCRIPTION
**Pull request by meg-gupta**

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Review by nate-chandler — APPROVED** [review]

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Comment by meg-gupta** [comment]
Could not reproduce the previous error locally, trying again with a lit command line that has precedent

**Comment by meg-gupta** [comment]
I couldn't reproduce locally because my local build had NonCopyableGenerics on by default. Retrying by removing the unit test not needed for this fix. I'll add it as a follow up when I figure out what's going wrong with the feature enabled.

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Pull request merged**
