### PR TITLE
[stdlib] Wrap comments to 80 columns, NFC

### PR DESCRIPTION
**Pull request by benrimmington**
Comments updated by #4131 have overrun the 80 column limit.

### CODE REVIEW

**Comment by dabrahams** [comment]
@tkremenek This is a doc-comment-only change; can you merge it without testing please?

**Comment by gribozavr** [comment]
Please don't.  There are SourceKit tests that FileCheck some of our comments.

@swift-ci Please smoke test OS X platform

**Comment by dabrahams** [comment]
@gribozavr You've got to be kidding me 😠

**Comment by tkremenek** [comment]
@swift-ci smoke test os x

**Pull request merged**
