### PR TITLE
[Preset] Build and test SwiftSyntax part of Linux smoke pull request …

### PR DESCRIPTION
**Pull request by shahmishal**
…preset

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci smoke test Linux

**Comment by shahmishal** [comment]
cc/ @akyrtzi

**Comment by shahmishal** [comment]
```
+ /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/swift-syntax/build-script.py --release --build-dir=/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/buildbot_linux/swiftsyntax-linux-x86_64 --swift-build-exec=/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/buildbot_linux/swiftpm-linux-x86_64/x86_64-unknown-linux/release/swift-build --swift-test-exec=/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/buildbot_linux/swiftpm-linux-x86_64/x86_64-unknown-linux/release/swift-test --swiftc-exec=/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/buildbot_linux/swift-linux-x86_64/bin/swiftc --syntax-parser-header-dir=/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/swift/include/swift-c/SyntaxParser --syntax-parser-lib-dir=/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/buildbot_linux/swift-linux-x86_64/lib --swift-syntax-test-exec=/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/buildbot_linux/swift-linux-x86_64/bin/swift-syntax-test --filecheck-exec=/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/buildbot_linux/llvm-linux-x86_64/bin/FileCheck
/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/swift-syntax: error: manifest parse error(s):
/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/swift-syntax/Package.swift:3:8: error: missing required module 'Foundation'
import PackageDescription
       ^
Error: Building SwiftSyntax failed
```

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
@swift-ci Please test windows

**Pull request closed without merging**
