### PR TITLE
[Perf Test][CSSolver] Prefer components with fewer type variables with all else …

### PR DESCRIPTION
**Pull request by xedin**
…equal

If the number of disjunctions is the same in both components, let's
prefer the one which has fewer type variables because it would result
in less work done if something fails.

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please smoke test compiler performance

**Comment by xedin** [comment]
@swift-ci please clean smoke test compiler performance

**Comment by xedin** [comment]
```
17:20:03 $ git clone https://github.com/apple/swift /Users/buildnode/jenkins/workspace-private/swift-PR-compiler-performance-smoke-test-macOS/master/new/swift
17:20:03 Cloning into '/Users/buildnode/jenkins/workspace-private/swift-PR-compiler-performance-smoke-test-macOS/master/new/swift'...
17:30:03 git: Timed out
```

@shahmishal  Infra issue?

**Comment by shahmishal** [comment]
@graydon just increased the timeout, so it should resolve this issue in next build. 

https://github.com/apple/swift-source-compat-suite/commit/55a7209b54da5dbba6f2a6f440f2023edc915c75

**Comment by shahmishal** [comment]
@swift-ci please clean smoke test compiler performance

**Comment by xedin** [comment]
@shahmishal Thank you!

**Comment by xedin** [comment]
I think I know what the problem here is - it tried to put "orphan" components (constraints where all of the type variables are bound) first in the list, that's why there is more deserialization happening...

I'm going to create a separate PR to address that in `SplitterStep`.

**Pull request closed without merging**
