### PR TITLE
Fix regression from CaptureInfoRequest

### PR DESCRIPTION
**Pull request by slavapestov**
If a generic local function declares a local type and another local function, we would crash if the outer function body was not skipped, and the local function was skipped.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by jkshtj** [comment]
@slavapestov thanks for fixing this issue. I was actually looking at it as well as we had failures similar to the ones outlined in the linked ticket. 

I had a quick question about how we're forming generic signatures for local functions. Why do the generic signatures of local functions have to depend on the captured values for these functions?

**Comment by slavapestov** [comment]
> I had a quick question about how we're forming generic signatures for local functions. Why do the generic signatures of local functions have to depend on the captured values for these functions?

There's an optimization where if a local function or closure does not capture any type parameters, then its generic signature is empty. So we need to perform capture analysis to decide if the local function has a generic signature or not.

**Comment by jkshtj** [comment]
So local functions and closures have a generic signature even if they are not themselves generic, but capture generic parameters?

**Comment by slavapestov** [comment]
Yes, the idea is that a generic signature is a "flat" representation that includes all outer parameters and requirements, as well as any introduced by the declaration itself. You might find this helpful: https://download.swift.org/docs/assets/generics.pdf

**Comment by jkshtj** [comment]
Thanks and I do indeed use your book as a reference quite often 🙂.

**Pull request merged**
