### PR TITLE
Revert "Clang function types v2: Electric Boogaloo (parsing + printing)"

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/swift#28737

### CODE REVIEW

**Comment by compnerd** [comment]
This broke the macOS, Linux, Windows builder, revert until it can be re-tested.

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
CC: @varungandhi-apple

**Comment by varungandhi-apple** [comment]
Oh shit, I forgot there was an intersecting part which was not tested together. Yes, let us revert this.

**Review by varungandhi-apple — APPROVED** [review]

**Pull request merged**
