### PR TITLE
[cxx-interop] import static operator call from C++23 as member callAs…

### PR DESCRIPTION
**Pull request by compnerd**
…Function functions in Swift to preserve source compatibility

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
**Explanation**: Correct importing of `operator ()()` from C++ types into Swift.
**Scope**: This fixes a small C++ interop issue in the compiler which is required for use of `std::hash` on Windows.
**Issue**:
**Risk**: This is a pretty narrow change to how we handle `static operator()()` which was added in C++23. It impacts only the C++ interop path where this method is declared.
**Testing**: This has been on main for quite some time and we failed to bring it over for the release.
**Reviewer**: @egorzhdan @hyp @al45tair

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
Can you link to the original PR on main? Thanks.

**Comment by DougGregor** [comment]
Main PR is: https://github.com/swiftlang/swift/pull/74279

**Comment by DougGregor** [comment]
**Explanation**: The C++ standard library included in recent versions of Microsoft Visual Studio have adopted a C++23 feature "static operator()", which causes a source compatibility break for Swift/C++ interoperability on Windows. Implement support for `static operator()` in the Clang importer by importing it as an instance method `callAsFunction`. This ensures that the source-compatible change to C++23 code (from `operator()` to `static operator()`) will also be a source-compatible change for Swift/C++ interoperability.
**Issue**: https://github.com/compnerd/swift-build/issues/808
**Scope**: This is a general addition to the Clang importer for C++ interoperability, although it's applicability is very narrow: `static operator()` is a new feature in C++23, and is not yet widely used.
**Risk**: Since `static operator()` is so new in C++23, and this fix is narrowly targeted at importing that feature, the likelihood of this affecting anything else is small.
**Testing**: CI, new tests
**Reviewed By**: @egorzhdan, me
**Original PR**: https://github.com/swiftlang/swift/pull/74279

**Review by airspeedswift — APPROVED** [review]

**Pull request merged**
