### PR TITLE
[WIP] SE-0066: Standardize Function Type Syntax

### PR DESCRIPTION
**Pull request by harlanhaskins**
#### What's in this pull request?

Implements SE-0066: Standardize Function Type Syntax

Still needs test and `stdlib` migration.
#### Resolved bug number: ([SR-1434](https://bugs.swift.org/browse/SR-1434))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by harlanhaskins** [comment]
Let's see how many tests fail!

**Comment by harlanhaskins** [comment]
@swift-ci Please test

**Comment by lattner** [comment]
Hi Harlan,

I'm sorry I didn't know that you were working on this.  I just landed the full test suite adaptation and a patch to implement this...

**Comment by harlanhaskins** [comment]
Haha, no worries! Definitely wanted to get it landed. 👍

**Comment by harlanhaskins** [comment]
What about XCTest and Foundation? Are those gonna build properly now?

**Comment by lattner** [comment]
I didn't try them, right now, they will only get a warning about this.  I'll upgrade it to an error in a week or two.

**Comment by modocache** [comment]
XCTest builds fine. The new warnings are resolved in https://github.com/apple/swift-corelibs-xctest/pull/104.

**Comment by harlanhaskins** [comment]
@modocache Thanks! 👍

**Comment by briancroom** [comment]
Here's one cleaning up Foundation as well: https://github.com/apple/swift-corelibs-foundation/pull/351

**Pull request closed without merging**
