### PR TITLE
Cherry-pick LLVM Bitstream changes

### PR DESCRIPTION
**Pull request by francisvm**
This includes:

* LLVM Bitstream with llvm::Error work
* Bitcode / Bitstream separation

### CODE REVIEW

**Comment by francisvm** [comment]
Please test with following pull request:
https://github.com/apple/llvm-project/pull/298

@swift-ci please smoke test

**Comment by francisvm** [comment]
Please test with following pull request:
apple/llvm-project#298

@swift-ci please smoke test OS X Platform

**Comment by francisvm** [comment]
Please test with following pull request:
apple/llvm-project#298

@swift-ci please smoke test

**Comment by hyp** [comment]
Merging in together with https://github.com/apple/llvm-project/pull/298

**Pull request merged**
