### PR TITLE
Add known type checker crashers.

### PR DESCRIPTION
**Pull request by rudkx**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

A smoke test on macOS does the following:
1. Builds the compiler incrementally.
2. Builds the standard library only for macOS. Simulator standard libraries and
   device standard libraries are not built.
3. lldb is not built.
4. The test and validation-test targets are run only for macOS. The optimized
   version of these tests are not run.

A smoke test on Linux does the following:
1. Builds the compiler incrementally.
2. Builds the standard library incrementally.
3. lldb is built incrementally.
4. The swift test and validation-test targets are run. The optimized version of these
   tests are not run.
5. lldb is tested.

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

Add minimized tests for:
    rdar://problem/27879334

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Smoke test macOS and merge.

**Comment by slavapestov** [comment]
@rudkx Want to take a couple more? rdar://27420414 rdar://27627862

**Comment by rudkx** [comment]
@slavapestov These don't look like crashes during type checking. I'm trying to (slowly) move some of those into the validation tests so that if there are dups that aren't easy to recognize (or where we make larger changes unrelated to a single failure) we'll know what now works.

**Comment by rudkx** [comment]
@swift-ci Smoke test and merge.

**Comment by slavapestov** [comment]
They're cases where the type checker allows code which should not type check. So the actual crash is in SILGen and IRGen, respectively, but once the bugs are fixed, the code will fail to type check.

**Comment by rudkx** [comment]
@slavapestov Sure, they're related to the type checker, but I really just want to focus on getting things that actually crash in the type checker into the validation suite at this point.

Doug pointed out to me recently that compiler_crashers_2 is another place that reduced crashers are getting put into, so if you want to get these into the test suite you may consider adding them there.

**Pull request merged**
