### PR TITLE
[Test] Fix up macros using optional trivia API

### PR DESCRIPTION
**Pull request by bnbarham**
https://github.com/apple/swift-syntax/pull/1477 makes `leadingTrivia` and `trailingTrivia` non-optional.

### CODE REVIEW

**Comment by bnbarham** [comment]
https://github.com/apple/swift-syntax/pull/1477

@swift-ci please test

**Review by ahoppen — APPROVED** [review]

**Comment by bnbarham** [comment]
https://github.com/apple/swift-syntax/pull/1477

@swift-ci please test

**Comment by bnbarham** [comment]
https://github.com/apple/swift-syntax/pull/1477

@swift-ci please test

**Comment by bnbarham** [comment]
https://github.com/apple/swift-syntax/pull/1477
https://github.com/apple/swift-format/pull/497

@swift-ci please test macOS platform

**Comment by bnbarham** [comment]
https://github.com/apple/swift-syntax/pull/1477
https://github.com/apple/swift-format/pull/497

@swift-ci please test macOS platform

**Pull request merged**
