### PR TITLE
emacs stuff that shouldn't affect the build

### PR DESCRIPTION
**Pull request by dabrahams**

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please smoke test and merge

**Comment by dabrahams** [comment]
@swift-ci Please smoke test and merge

**Comment by dabrahams** [comment]
@swift-ci Please smoke test and merge

**Comment by dabrahams** [comment]
@swift-ci Please smoke test Linux platform

**Comment by dabrahams** [comment]
There's no way this broke linux.

**Comment by gottesmm** [comment]
@dabrahams You are right about the linux failure. AFAIKT The failure was in lldb (nothing to do with this).

**Pull request merged**
