### PR TITLE
	ConformanceLookupTable: Recursively inherit into subclasses when incrementally adding extension conformances.

### PR DESCRIPTION
**Pull request by jckarter**
Previously, we would only reliably propagate conformances from new extensions to immediate subclasses, since when we visit grandchild classes, we'd see no change in the immediate base class's status. Fix this by walking up the entire superclass chain when we look for new inherited conformances, and track the last processed state of different nominal type decls' extensions separately. Fixes SR-1480.

### CODE REVIEW

**Comment by jckarter** [comment]
@DougGregor Does this look reasonable?

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by DougGregor** [comment]
Yeah, this looks great. Thanks!

**Comment by jckarter** [comment]
Thanks Doug!

**Comment by AndrewSB** [comment]
Sorry to butt in @jckarter, but I saw two of your commits said "NFC", what does that stand for?

**Comment by jckarter** [comment]
No Functionality Change

**Pull request merged**
