### PR TITLE
[CodeCompletion] Implement context type analysis at subscript position

### PR DESCRIPTION
**Pull request by rintaro**
This improves completion for index part of subscript expression.

rdar://problem/38920581

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by benlangmuir** [comment]
Why does the subscript case do a qualified lookup while the function case doesn't?

**Comment by rintaro** [comment]
As for free function case, overloaded candidates are usually preserved as `OverloadSetRefExpr`. As for method case, I'm implementing qualified lookup version too in https://github.com/apple/swift/pull/20013 .

**Comment by benlangmuir** [comment]
Okay makes sense.  I commented in that PR that we should share the implementation.  Otherwise LGTM.

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Pull request merged**
