### PR TITLE
SIL ownership and reabstraction thunks.

### PR DESCRIPTION
**Pull request by atrick**
I noticed we were missing borrow scopes while testing opaque values.

I spent a lot of time trying to refactor the code but ended up creating more complexity. So this is just a simple "hack" that Michael pointed me toward. It's not too ugly and will be cleaned up once we introduce SIL `destructure`.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test.

**Comment by gottesmm** [comment]
Hmmm... the linux one looks like some sort of missing symbol error in libdispatch. I am going to try it again, just in case.

**Comment by gottesmm** [comment]
@swift-ci test linux platform

**Comment by atrick** [comment]
@swift-ci clean smoke test Linux platform.

**Pull request merged**
