### PR TITLE
[Gardening] Remove unused diagnostic definitions

### PR DESCRIPTION
**Pull request by owenv**
found using utils/find-unused-diagnostics.sh

### CODE REVIEW

**Comment by owenv** [comment]
@swift-ci please test

**Review by slavapestov — APPROVED** [review]

**Comment by owenv** [comment]
@swift-ci smoke test

**Comment by owenv** [comment]
@swift-ci smoke test

**Comment by owenv** [comment]
@shahmishal sorry to ping you about this again, but it still seems like I'm unable to trigger the CI bot. At first I thought it was because my GitHub account email wasn't public, but that doesn't seem to have been the problem. Is there any chance I haven't been added to the allowed users list?

**Comment by hamishknight** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
⛵️

**Pull request merged**
