### PR TITLE
[SourceKit] Link with libdispatch & libswiftCore on Linux

### PR DESCRIPTION
**Pull request by jpsim**
#### What's in this pull request?

This PR is exactly #2862, with some minor additional changes to account for the new libdispatch Swift overlay that was added since the original PR and so must now link `swiftCore`.

Everything else that was discussed in #2862 still applies here.

cc @akyrtzi @briancroom @modocache

All credit here goes to @briancroom @modocache and @norio-nomura, I just re-assembled the commits.
#### Resolved bug number: ([SR-1677](https://bugs.swift.org/browse/SR-1677))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by akyrtzi** [comment]
@swift-ci Please test

**Comment by jpsim** [comment]
@akyrtzi btw, I think you may need to re-trigger CI, since the last request was done during the CI maintenance window, whereas later requests have already started (https://github.com/apple/swift/pull/3616#issuecomment-233810420).

**Comment by nkcsgexi** [comment]
@swift-ci Please test

**Comment by jpsim** [comment]
Please join me in a fire dance to get CI to run 😂

**Comment by modocache** [comment]
Sounds like fun!

@swift-ci please test

**Comment by akyrtzi** [comment]
OS X failure is unrelated.

**Comment by jpsim** [comment]
Thanks @akyrtzi!

**Comment by jpsim** [comment]
FYI, SourceKit now builds successfully on Linux 🎉 (in two steps):

```
$ utils/build-script --libdispatch
$ utils/build-script --libdispatch --extra-cmake-options="-DSWIFT_BUILD_SOURCEKIT:BOOL=TRUE"
```

**Comment by paulofaria** [comment]
@jpsim what's blocking it to being available by default in the toolchain?

**Comment by jpsim** [comment]
Swift needs to be built twice for SourceKit to compile successfully, because libdispatch depends on Swift for its overlay, and SourceKit depends on libdispatch.

There's some build system refactoring needed to build SourceKit as part of a single, normal Swift build. This is being tracked as [SR-1676](https://bugs.swift.org/browse/SR-1676) which is unassigned and up for grabs if you're interested in tackling this @paulofaria.

**Comment by jhribal** [comment]
Could you please look at http://stackoverflow.com/questions/39941523/building-swift-sourcekit-on-linux?

**Comment by jeffreyhanna** [comment]
@jpsim thanks for all your work! Very happy to hear SourceKit builds on Linux now. Any chance you could point me to more detailed instructions? I'm very new to Linux :/

I saw your notes:
```
$ utils/build-script --libdispatch
$ utils/build-script --libdispatch --extra-cmake-options="-DSWIFT_BUILD_SOURCEKIT:BOOL=TRUE"
```

Assuming I need to download the swift source and then run those commands, anything else?

**Pull request merged**
