### PR TITLE
[IRGen] Return null reference from IRGenFunction::emitUnmanagedAlloc …

### PR DESCRIPTION
**Pull request by drexin**
…when layout isKnownEmpty

rdar://92418090

This fixes a runtime crash on x86 caused by allocations of size 0, which are later deallocated with swift_deallocObjectImpl, but are missing the object header.

### CODE REVIEW

**Comment by drexin** [comment]
@swift-ci test

**Comment by drexin** [comment]
@swift-ci test

**Comment by drexin** [comment]
Converted to draft, while working on further tests.

**Comment by drexin** [comment]
@swift-ci test

**Review by slavapestov — COMMENTED** [review]
I think this change makes sense regardless, as an optimization, but I'm not convinced it's the root cause of our problem here. You can certainly have a zero-sized heap allocation, for example a class with no instance fields.

The problem was that the allocationSize stored in the metadata is supposed to include the size of the header, so the minimum size should be sizeof(HeapObject). However in this case it was literally zero. That seems like it should not be allowed. Maybe the arguments to swift_allocObject() are computed incorrectly in this case?

**Comment by aschwaighofer** [comment]
@slavapestov We understand where the zero is coming from.

Here: https://github.com/apple/swift/blob/186afa56f45eb8763d84ab60c3ae360ae2d86947/lib/IRGen/StructLayout.cpp#L74

```
  // Add the heap header if necessary.
  if (requiresHeapHeader(layoutKind)) {
    builder.addHeapHeader();
  }

  bool nonEmpty = builder.addFields(Elements, strategy);

  // Special-case: there's nothing to store.
  // In this case, produce an opaque type;  this tends to cause lovely
  // assertions.
  if (!nonEmpty) {
    assert(!builder.empty() == requiresHeapHeader(layoutKind));
    MinimumAlign = Alignment(1);
==>    MinimumSize = Size(0);
```

Apparently, `addFields` ignores the previously added heap header when it returns whether the builder is empty.

We will only get here if the Layout was fixed and we only use his with a head header for computing heap objects. 

So fixing this by checking for a zero sized heap layout makes sense to me.

I don't think we ever want a header sized object that stores no data.

**Comment by aschwaighofer** [comment]
To your concern about `ClassLayout`: `ClassLayout` does not use `HeapLayout`.

**Comment by aschwaighofer** [comment]
We can fix this in the struct layout in addition to "the optimization", but with this optimization in place I would not know how to test for the fix in the struct layout computation.

**Comment by AnthonyLatsis** [comment]
Should also fix rdar://83066987, which corresponds to the failure this was reduced from.

**Comment by aschwaighofer** [comment]
@slavapestov Hmm. Thank you for making me look at this again because I did find an issue if we do the null optimization:

The runtime function `swift_deallocUninitializedObject` assumes a non-null argument. So we have to emit the null optimization in the `deallocate` function too.
```
 void                                                                          
  deallocate(IRGenFunction &IGF, llvm::Value *box, SILType _)                   
  const override {                                                              
    auto size = layout.emitSize(IGF.IGM);                                       
    auto alignMask = layout.emitAlignMask(IGF.IGM);                             
                                                                                
    emitDeallocateUninitializedHeapObject(IGF, box, size, alignMask);           
  }    
  ```

**Comment by slavapestov** [comment]
> We can fix this in the struct layout in addition to "the optimization", but with this optimization in place I would not know how to test for the fix in the struct layout computation.

We can add an assertion to the struct layout computation to ensure that we don't actually hit that case.

**Comment by slavapestov** [comment]
@drexin Can you cherry-pick this to the 5.7 branch as well? As @AnthonyLatsis alludes this came up in an executable test for a new feature (SE-0309) that's currently disabled because of this bug. We would like to re-enable that test.

**Comment by drexin** [comment]
@swift-ci test

**Review by slavapestov — APPROVED** [review]

**Comment by drexin** [comment]
@swift-ci smoke test linux

**Comment by drexin** [comment]
@swift-ci smoke test linux

**Comment by drexin** [comment]
@swift-ci smoke test linux

**Comment by drexin** [comment]
@swift-ci smoke test linux

**Pull request merged**
