### PR TITLE
Multi-statement closure type inference

### PR DESCRIPTION
**Pull request by DougGregor**
Introduce support for type inference of closures with multiple
statements. Type inference flows from the closure parameters through
the body of the closure to determine the return type. This, for example,
allows a "map" closure with multiple statements to infer the result type
based on the "return" in the body:

    let _ = ints.map { i in
      let value = i + 1
      return String(value)
    }

The frontend option `-experimental-multi-statement-closures` enables
this new behavior. It should cover all statement and declaration kinds
in a closure now:

- [x] Expressions
- [x] Brace statements
- [x] `var`/`let` declarations (note: only when there is also an initializer)
- [x] `do` statements (without a catch)
- [x] `do` statements (with catch clauses)
- [x] `if` statements
- [x] `guard` statements
- [x] `while` loops
- [x] repeat-while loops
- [x] `for`..`in` loops
- [x] `throw` statements
- [x] `defer` statements
- [x] `break` and `continue`
- [x] `switch` statements
- [x] `#assert` statements
- [x] Other kinds of declarations (local types, etc.)

### CODE REVIEW

**Comment by DougGregor** [comment]
Note that this incorporates both https://github.com/apple/swift/pull/32215 and https://github.com/apple/swift/pull/32221; only the last two commits are needed to implement this feature.

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci smoke test

**Comment by DougGregor** [comment]
@swift-ci smoke test macOS

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci smoke test

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Comment by xwu** [comment]
Darn, was really pumped about this. Any chance it’ll be resurrected?

**Comment by IanKeen** [comment]
same, I hope this makes a comeback! :(

**Pull request closed without merging**
