### PR TITLE
[swift-stdlib-tool] use correct paths when codesigning

### PR DESCRIPTION
**Pull request by rmaz**
This PR fixes the destination path when codesigning with swift-stdlib-tool. There were also 3 cases of inverted logic that needed fixing.

Equivalent `swift/5.5` PR is https://github.com/apple/swift/pull/40086

### CODE REVIEW

**Comment by rmaz** [comment]
@keith @Vercantez

**Review by keith — APPROVED** [review]

**Comment by keith** [comment]
cc @salinas-miguel @CodaFi since part of this regressed in https://github.com/apple/swift/pull/39216

**Review by salinas-miguel — APPROVED** [review]
Thanks for fixing these bugs

**Comment by CodaFi** [comment]
Thank you

@swift-ci test

**Comment by rmaz** [comment]
@CodaFi any idea who to ping about getting https://github.com/apple/swift/pull/40086 approved?

**Pull request merged**
