### PR TITLE
[5.5] Add all deserialization fatal output to the pretty stack trace

### PR DESCRIPTION
**Pull request by bnbarham**
Cherry-pick of https://github.com/apple/swift/pull/37743

-----

Rather than outputting diagnostics and to stderr, output all the extra
information added when deserialization fatally fails to the pretty stack
trace instead. Since the pretty stack trace is added to crash logs, this
should avoid the dance of requesting the compiler output.

  - Moves the previous "**** DESERIALIZATION FAILURE ..." output to the
    last pretty stack trace line

  - Removes the module and compiler version notes added to the fatal
    diagnostic

  - Adds a new effective compiler version line for all frontend failures

  - Adds a new line for the full misc version of the module that failed.
    May double up with previous "While reading from ..." lines that are
    added in various deserialization methods, but better to have it
    twice than not at all

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Review by akyrtzi — APPROVED** [review]

**Comment by bnbarham** [comment]
@swift-ci please test Linux platform

**Comment by bnbarham** [comment]
@swift-ci please test Linux platform

**Comment by bnbarham** [comment]
@swift-ci please test Linux platform

**Pull request merged**
