### PR TITLE
[5.1]  Fix a unit test for 32-bit platforms.

### PR DESCRIPTION
**Pull request by eeckstein**
rdar://problem/48456753

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by slavapestov** [comment]
5.1 branch requires a full test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by eeckstein** [comment]
@slavapestov thanks!

**Review by atrick — APPROVED** [review]

**Pull request merged**
