### PR TITLE
[windows] Various improvements in build.ps1

### PR DESCRIPTION
**Pull request by weliveindetail**
This PR contains the combined patch-set from the following individual reviews:

* https://github.com/swiftlang/swift/pull/77875
* https://github.com/swiftlang/swift/pull/77874
* https://github.com/swiftlang/swift/pull/77945
* https://github.com/weliveindetail/swift/pull/2

### CODE REVIEW

**Comment by weliveindetail** [comment]
Once LLDB testing landed, this needs additions from https://github.com/weliveindetail/swift/commit/buildps1-consolidate-deps-infos-with-lldb-testing

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by hjyamauchi** [comment]
@swift-ci please test Windows Platform

I hope this is a transient issue.
```
[2024-12-04 17:36:51] Building 'C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift' to 'T:\101' for arch 'x86_64'...
Error: The term 'if' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    at Get-BuiltToolchainTool, C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\utils\build.ps1: line 897
    at Get-ToolchainTool, C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\utils\build.ps1: line 973
    at <ScriptBlock>, C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\utils\build.ps1: line 1122
    at Isolate-EnvVars, C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\utils\build.ps1: line 623
    at Build-CMakeProject, C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\utils\build.ps1: line 1010
    at <ScriptBlock>, C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\utils\build.ps1: line 1893
    at Isolate-EnvVars, C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\utils\build.ps1: line 623
    at Build-Runtime, C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\utils\build.ps1: line 1863
    at Invoke-BuildStep, C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\utils\build.ps1: line 457
    at <ScriptBlock>, C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\utils\build.ps1: line 2878
  From System.Management.Automation.CommandNotFoundException: The term 'if' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
      at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
      at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
      at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
      at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
      at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
      at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
      at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
      at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
      at System.Management.Automation.CommandProcessorBase.Complete()
```

**Comment by hjyamauchi** [comment]
@swift-ci please test Windows Platform

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Review by compnerd — APPROVED** [review]

**Pull request merged**
