### PR TITLE
Fix associated type inference crash with constrained protocol extensions

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes https://bugs.swift.org/browse/SR-14639 / rdar://problem/78276768.

### CODE REVIEW

**Review by xedin — APPROVED** [review]

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Pull request merged**
