### PR TITLE
[SILGen] Branch on result of next() before conversion.

### PR DESCRIPTION
**Pull request by varungandhi-apple**
Fixes SR-8688, fixes rdar://problem/47162940.

TODO:
- [X] ~~Some test failures related to SourceKit & Sema (I think those are pattern matching on the AST/SIL)~~ I had an out-dated `unittests/SwiftUnitTests` target which was not getting rebuilt for some reason. 🤔

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
@swift-ci please test

**Comment by varungandhi-apple** [comment]
@swift-ci please test source compatibility

**Comment by varungandhi-apple** [comment]
@swift-ci please test macOS

**Comment by varungandhi-apple** [comment]
Based on Michael's suggestion, I'm going to add some tests to cover address-only types, so please don't merge this PR as-is.

**Review by slavapestov — APPROVED** [review]

**Comment by varungandhi-apple** [comment]
Added a test case for address-only types.

**Comment by varungandhi-apple** [comment]
@swift-ci please test

**Pull request merged**
