### PR TITLE
[simplify-instruction] When eliminating extracts from an aggregate we  just constructed, look through ownership insts.

### PR DESCRIPTION
**Pull request by gottesmm**
Just an oversight. When used with -enable-ossa-modules, this eliminates the
reported ARC traffic issue in:

SR-12377
rdar://60832825

----

This is not really doing anything new. This is just taking advantage of the OwnershipRAUW utility so this stuff will just work.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Review by meg-gupta — APPROVED** [review]
lgtm!

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
Fixed the watchOS test

**Comment by gottesmm** [comment]
@swift-ci test linux platform

**Comment by gottesmm** [comment]
@swift-ci test Linux platform

**Pull request merged**
