### PR TITLE
[stdlib][SE-0320] Update availability of new Codable additions

### PR DESCRIPTION
**Pull request by lorentey**
Replace 9999 availability with our nice new availability macros.

### CODE REVIEW

**Comment by lorentey** [comment]
Cc @mortenbekditlevsen

**Comment by lorentey** [comment]
@swift-ci test

**Review by Azoy — APPROVED** [review]

**Review by drexin — APPROVED** [review]
Thanks, Karoy!

**Comment by benrimmington** [comment]
Also in [test/stdlib/CodableTests.swift](https://github.com/apple/swift/blob/main/test/stdlib/CodableTests.swift) on lines 483 and 1057.

**Comment by lorentey** [comment]
> Also in [test/stdlib/CodableTests.swift](https://github.com/apple/swift/blob/main/test/stdlib/CodableTests.swift) on lines 483 and 1057.

Ah, good catch! Fixed

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci smoke test linux platform

**Comment by lorentey** [comment]
```
/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/swift/test/Concurrency/Runtime/async_task_cancellation_while_running.swift:11:8: error: compiled module was created by an older version of the compiler; rebuild 'Dispatch' and try again: /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/libdispatch-linux-x86_64/src/swift/swift/Dispatch.swiftmodule
```

🤔

**Comment by lorentey** [comment]
@swift-ci clean test Linux platform

**Pull request merged**
