### PR TITLE
IRGen: Refuse to compute witness table layouts of resilient protocols

### PR DESCRIPTION
**Pull request by slavapestov**
It's not correct to depend on the order of entries in a witness table
if the protocol is resilient, so don't even try.

### CODE REVIEW

**Comment by slavapestov** [comment]
@jckarter This exposes a resilience problem in keypaths. I see you have three strategies for how to reference virtual methods:

- for resilient classes, you use the dispatch thunk.
- for non-resilient classes, you use the (possibly relative) vtable offset.
- for protocols, you use the witness table offset.

The last one is wrong for resilient protocols. I think it would be better to use method descriptors for all three, now that we have them and emit them unconditionally. What do you think?

**Comment by jckarter** [comment]
If the protocol is resilient, then we should already use the dispatch thunk as the identifier. If we have method descriptors all the time, though, and they're linkable across images, then I agree it'd be more consistent to use those as identifiers consistently.

**Review by jckarter — APPROVED** [review]
Key path codegen change LGTM.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Pull request merged**
