### PR TITLE
Workaround clang backend bug 

### PR DESCRIPTION
**Pull request by rokhinip**
This is a workaround for a bug that was causing clang to fail to build Actor.cpp

### CODE REVIEW

**Comment by rokhinip** [comment]
@swift-ci please smoke test

**Review by aschwaighofer — COMMENTED** [review]
We might need to add a macro that allows this to compile on compilers that don't support the `optnone` attribute. I don't know whether the msvc compiler would support it.


```
#if __has_attribute(optnone)
#define SWIFT_OPTNONE __attribute__((optnone))
#else
#define SWIFT_OPTNONE
#endif
```

**Comment by rokhinip** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@rokhinip could you please add some details on the mis-compilation?  This could potentially impact non-Apple targets.

**Comment by rokhinip** [comment]
I'll let @aschwaighofer speak to that since he triaged it.

**Comment by aschwaighofer** [comment]
@compnerd The toolchain builder failed because of an llvm bug triggered by a change (to `Actor.cpp` in https://github.com/apple/swift/pull/41304) in the annotated function.

https://ci.swift.org/job/oss-swift-package-macos/6555/consoleText

LLVM folks will look into the bug. In the meantime we would like to unblock the toolchain builder.

**Comment by rokhinip** [comment]
@swift-ci please smoke test

**Comment by rokhinip** [comment]
macOS is failing due to `[FunctionalTests.ModuleAliasingTests testExternalSimple]` issues which is being fixed here: https://github.com/apple/swift-package-manager/pull/4117/

**Comment by rokhinip** [comment]
Please test with following PR: 
https://github.com/apple/swift-package-manager/pull/4117

@swift-ci please test macOS platform

**Comment by rokhinip** [comment]
Please test with following PR:
https://github.com/apple/swift-package-manager/pull/4117

@swift-ci please smoke test macOS platform

**Comment by aschwaighofer** [comment]
Tim put up a fix for review for the underlying LLVM issue: https://reviews.llvm.org/D119434

**Pull request merged**
