### PR TITLE
Revert "[stdlib] [SE-0031] update stdlib for SE-0031 (inout adjustment)"

### PR DESCRIPTION
**Pull request by gribozavr**
Reverts apple/swift#1456

This PR changes meaning of some tests.

### CODE REVIEW

**Comment by lattner** [comment]
Can you be more specific about what the problem is?

**Comment by gribozavr** [comment]
I have commented on one such instance in #1456.  The PR adds newlines at EOF in tests that require no newline, testing the compiler.

**Comment by dduan** [comment]
These are fixed here: https://github.com/apple/swift/pull/1459

**Comment by lattner** [comment]
Got it, thanks for catching this @gribozavr !

**Pull request merged**
