### PR TITLE
[static-stdlib] Move static-executable-args.lnk under stdlib/public/Resources/linux

### PR DESCRIPTION
**Pull request by kateinoigakukun**
This is a preparatory change for adding a static executable support for WASI

### CODE REVIEW

**Comment by kateinoigakukun** [comment]
@swift-ci Please smoke test

**Comment by kateinoigakukun** [comment]
@swift-ci Please smoke test

**Comment by kateinoigakukun** [comment]
I tested the built toolchain and it looks working at least for a simple scenario
```
$ curl https://download.swift.org/tmp/pull-request/66423/470/ubuntu2004/PR-ubuntu2004.tar.gz | tar xz
$ echo 'print("Hello")' > main.swift
$ ./usr/bin/swiftc main.swift -emit-executable
$ ./main
```

**Comment by MaxDesiatov** [comment]
Please also test a simple async `@main` function with static linking on Linux, which implicitly requires Dispatch. We had multiple regressions in that area recently, so I'm cautious about changes in that area.

**Review by MaxDesiatov — APPROVED** [review]

**Pull request merged**
