### PR TITLE
[5.7] [stdlib] Mark NFD and NFC as SPI

### PR DESCRIPTION
**Pull request by Azoy**
Cherry pick of: https://github.com/apple/swift/pull/42124

This adds a `String._nfc` and `String._nfd` iterator as `@_spi(_Unicode)` for libraries like `_StringProcessing` to use.

### CODE REVIEW

**Comment by Azoy** [comment]
@swift-ci please test

**Review by stephentyrone — APPROVED** [review]

**Comment by Azoy** [comment]
@swift-ci please test

**Comment by Azoy** [comment]
@swift-ci please test

**Comment by Azoy** [comment]
@swift-ci please test

**Pull request merged**
