### PR TITLE
[cxx-interop] Use regex instead of operand name to fix C++ constructor tests.

### PR DESCRIPTION
**Pull request by zoecarver**
This should fix the CI. 

rdar://problem/70772958

### CODE REVIEW

**Comment by zoecarver** [comment]
preset=buildbot,tools=R,stdlib=RD
@swift-ci Please test with preset macOS

**Comment by zoecarver** [comment]
I suspect this won't fix the `CrossModule` issues.

**Comment by varungandhi-apple** [comment]
Down to a single failure now:

```
Swift(macosx-x86_64) :: Interop/Cxx/class/constructors-irgen.swift
```

**Comment by zoecarver** [comment]
preset=buildbot,tools=R,stdlib=RD
@swift-ci Please test with preset macOS

**Comment by zoecarver** [comment]
Just realized I need to rebase and remove the `// REQUIRES: rdar70772958`.

**Comment by zoecarver** [comment]
preset=buildbot,tools=R,stdlib=RD
@swift-ci Please test with preset macOS

**Comment by zoecarver** [comment]
@swift-ci please test and merge.

**Comment by zoecarver** [comment]
@swift-ci please test and merge.

**Comment by zoecarver** [comment]
@swift-ci please test linux.

**Pull request merged**
