### PR TITLE
SwiftCompilerSources: rework bridging

### PR DESCRIPTION
**Pull request by eeckstein**
Introduce two modes of bridging:
* inline mode: this is basically how it worked so far. Using full C++ interop which allows bridging functions to be inlined.
* pure mode: bridging functions are not inlined but compiled in a cpp file. This allows to reduce the C++ interop requirements to a minimum. No std/llvm/swift headers are imported.

This change requires a major refactoring of bridging sources. The implementation of bridging functions go to two separate files: SILBridgingImpl.h and OptimizerBridgingImpl.h.
Depending on the mode, those files are either included in the corresponding header files (inline mode), or included in the c++ file (pure mode).

The mode can be selected with the BRIDGING_MODE cmake variable. By default it is set to the inline mode (= existing behavior). The pure mode is only selected in certain configurations to work around C++ interop issues:
* In debug builds, to workaround a problem with LLDB's `po` command (rdar://115770255).
* On windows to workaround a build problem.

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by finagolfin** [comment]
Looking forward to trying the pure mode on Android, which still has problems with C++ Interop.

**Comment by eeckstein** [comment]
@swift-ci clean smoke test linux

**Comment by eeckstein** [comment]
@swift-ci clean test linux

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
Nice!

> Any plans to backport these three bridging pulls you just added to 5.10?

Sorry, no. At this time it's not possible

**Comment by finagolfin** [comment]
> Sorry, no. At this time it's not possible

How so? If you simply don't have the time, do you mind if I backport these changes and submit them to the 5.10 branch myself?

**Comment by eeckstein** [comment]
The bar is already very high for cherry picking changes to 5.10.

**Comment by finagolfin** [comment]
OK, got it. I will simply backport it and use it locally for my upcoming native Swift 5.10 toolchain for Android instead.

**Pull request merged**
