### PR TITLE
SIL: Parsing and serialization support for subst function types

### PR DESCRIPTION
**Pull request by jckarter**

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please clean test OS X

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Comment by compnerd** [comment]
@jckarter - this broke the windows build

**Comment by compnerd** [comment]
https://compnerd.visualstudio.com/windows-swift/_build/results?buildId=18242&view=logs&j=b9e62f99-1a98-5ed7-01d2-f4794231ed79&t=a578f0e2-68b7-5e89-c822-c6512bff1b51&l=141

**Comment by jckarter** [comment]
Sorry, you can just remove the dump call.

**Pull request merged**
