### PR TITLE
docs: convert `FailableInitializers.rst` to Markdown

### PR DESCRIPTION
**Pull request by MaxDesiatov**
Resolves partially https://github.com/apple/swift/issues/49997.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Review by AnthonyLatsis — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
@AnthonyLatsis that's addressed now, thanks for the detailed review!

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test and merge

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test Linux

**Pull request merged**
