### PR TITLE
[5.1 early] [ParseableInterface] Honor "exported module names"

### PR DESCRIPTION
**Pull request by jrose-apple**
Cherry-pick of #23474 to the early 5.1 branch for Apple purposes. Reviewed by @harlanhaskins.

rdar://problem/49114811

### CODE REVIEW

**Comment by jrose-apple** [comment]
I don't think I can actually run PR tests on this branch, can I? But this change is very safe: most of it is moving existing things around without changing them, and then the last bit is changing parseable interface generation, which is still a new feature, to fix the problem, which is rare.

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@shahmishal Looks like it doesn't work after all. That's probably okay, though.

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by jrose-apple** [comment]
The failing test was "SwiftSyntax :: print_verify_tree.swift", which would not be affected by this change.

**Pull request merged**
