### PR TITLE
[Runtime] NULL check shared cache calls.

### PR DESCRIPTION
**Pull request by mikeash**
Avoid a dynamic linker failure if the calls aren't available at runtime.

rdar://74965969

### CODE REVIEW

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by cooperp** [comment]
LGTM

**Review by cooperp — APPROVED** [review]

**Comment by fredriss** [comment]
Is the null check considered an availability check by the compiler? I'm thinking that the compile might fail if the API has availability annotations and we build for an older deployment target.

**Comment by CodaFi** [comment]
@swift-ci smoke test macOS

**Comment by mikeash** [comment]
@fredriss Good thinking. A quick test here shows that it still produces a warning when guarded with a NULL check. In fact, it produces *two* warnings, because the NULL check also warns about availability! I'll switch it to do a proper version check.

**Comment by mikeash** [comment]
Updated to wrap the call in a `__builtin_available` check.

**Comment by mikeash** [comment]
@swift-ci please test

**Pull request merged**
