### PR TITLE
[Apple Silicon] Cross compile Xcode toolchain

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#682

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#682

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#682

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#682

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#682

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#682

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#682

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#682

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#682

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#682

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#682

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#682

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#682

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#682

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#682

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#682

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#682

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#682

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#682

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#682

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#682

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#682

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#682

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#682

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#682

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
@swift-ci build toolchain Linux

**Comment by shahmishal** [comment]
apple/swift-llbuild#682
https://github.com/apple/swift-package-manager/pull/2902

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#682
apple/swift-package-manager#2902

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#682
apple/swift-package-manager#2902

@swift-ci test

**Comment by shahmishal** [comment]
```
/Users/buildnode/jenkins/workspace/swift-PR-toolchain-osx/branch-master/buildbot_osx/swiftpm-macosx-x86_64/apple/Intermediates.noindex/GeneratedModuleMaps/macosx/TSCclibc.modulemap:1:8: error: redefinition of module 'TSCclibc'
21:34:32 module TSCclibc {
21:34:32        ^
21:34:32 /Users/buildnode/jenkins/workspace/swift-PR-toolchain-osx/branch-master/swiftpm/swift-tools-support-core/Sources/TSCclibc/include/module.modulemap:1:8: note: previously defined here
21:34:32 module TSCclibc {
21:34:32        ^
21:34:32 <module-includes>:3:9: error: could not build module 'CSQLite3'
21:34:32 #import "/Users/buildnode/jenkins/workspace/swift-PR-toolchain-osx/branch-master/swiftpm/swift-tools-support-core/Sources/TSCclibc/include/csqlite3.h"
21:34:32         ^
21:34:32 
/Users/buildnode/jenkins/workspace/swift-PR-toolchain-osx/branch-master/swiftpm/swift-tools-support-core/Sources/TSCLibc/libc.swift:20:19: error: could not build Objective-C module 'TSCclibc'
21:34:32 @_exported import TSCclibc
21:34:32                   ^
21:34:32 
21:34:32 Build cancelled
```
Need this PR to fix this issue: https://github.com/apple/swift-package-manager/pull/2891

**Comment by shahmishal** [comment]
apple/swift-llbuild#682

@swift-ci build toolchain macOS

**Review by edymtt — APPROVED** [review]

**Comment by shahmishal** [comment]
@swift-ci test Windows

**Comment by shahmishal** [comment]
apple/swift-llbuild#682

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#682

@swift-ci build toolchain macOS

**Pull request merged**
