### PR TITLE
[CursorInfo] Add ObjC location to generated symbol graph

### PR DESCRIPTION
**Pull request by bnbarham**
Add the file for an imported ObjC-symbol to the generated symbol graph
when ObjC documentation is requested.

Skips line/column information for now since it's not needed. If we add
those we should extract location retrieval to a common method for both
cursor info and symbol graph gen.

Resolves rdar://91658873.

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
@QuietMisdreavus is there any way to pass those symbol graph options down from symbolgraph-extract? I was thinking it'd probably be better to move these tests into SymbolGraph and then have cursor info just test the very basics. Can do that in a later PR though.

**Comment by QuietMisdreavus** [comment]
@bnbarham If you want to set an option directly in `swift-symbolgraph-extract`, you'll need to add a CLI flag for it. There's a [section of symbol-graph-specific options](https://github.com/apple/swift/blob/3dfc40898cdf6980bac4f6987e57719346833470/include/swift/Option/Options.td#L1325) in Options.td, so you should be able to add one there and load it just in [`swift_symbolgraph_extract_main.cpp`](https://github.com/apple/swift/blob/main/lib/DriverTool/swift_symbolgraph_extract_main.cpp).

**Comment by bnbarham** [comment]
> @bnbarham If you want to set an option directly in `swift-symbolgraph-extract`, you'll need to add a CLI flag for it. There's a [section of symbol-graph-specific options](https://github.com/apple/swift/blob/3dfc40898cdf6980bac4f6987e57719346833470/include/swift/Option/Options.td#L1325) in Options.td, so you should be able to add one there and load it just in [`swift_symbolgraph_extract_main.cpp`](https://github.com/apple/swift/blob/main/lib/DriverTool/swift_symbolgraph_extract_main.cpp).

Ah nice, thanks! I'll refactor those tests in a separate PR later.

**Review by QuietMisdreavus — APPROVED** [review]
This looks great, thanks!

**Review by ethan-kusters — APPROVED** [review]
Thank you!

**Review by rintaro — APPROVED** [review]

**Comment by bnbarham** [comment]
@swift-ci please test macOS platform

**Comment by bnbarham** [comment]
@swift-ci please test macOS platform

**Pull request merged**
