### PR TITLE
Reduce memory usage by freeing memory occupied by SILModules after IRGen

### PR DESCRIPTION
**Pull request by swiftix**
There is no need to keep SILModules around after IRGen has generated LLVM IR from them.
This reduces the compiler memory usage during LLVM code-generation and optimization phases roughly by 15%-20%.

rdar://29407859

### CODE REVIEW

**Comment by swiftix** [comment]
@swift-ci Please smoke test

**Comment by swiftix** [comment]
@gottesmm Is it what you had in mind?

**Comment by swiftix** [comment]
Please test with following PR:
https://github.com/apple/swift-lldb/pull/86

@swift-ci Please smoke test Linux platform

**Comment by swiftix** [comment]
Please test with following PR:
apple/swift-lldb#86

@swift-ci Please test Linux platform

**Comment by swiftix** [comment]
Please test with following PR:
apple/swift-lldb#86

@swift-ci Please smoke test Linux platform

**Comment by jrose-apple** [comment]
@mxswd is working on something similar that would destroy the entire CompilerInstance, not just the SILModule. In both cases, though, we should be weighing memory usage against time—how many destructors does the SILModule run?

**Comment by jrose-apple** [comment]
(because we should have a -disable-free mode like Clang)

**Comment by swiftix** [comment]
@jrose-apple Yeah, if @mxswd would provide a way to get rid of the entire CompilerInstance that would be nice! 

As for destructors being run by the SILModule, we currently pay the price for them anyways. It just happens after the LLVM code generation passes. So, from this perspective, it does not make things slower IMHO. But of course, it is slower than not running the destructors at all. Should we later find a way to avoid running the destructors, we could use it here as well. 

And, BTW, @gottesmm had an idea about running the SILModule destructors as a task on a separate thread, in parallel to LLVM passes. What do you think of it?

**Comment by jrose-apple** [comment]
Oh, that's clever. Since the premise is that the LLVM module doesn't need the SILModule (or the rest of the CompilerInstance), it does seem safe to do that.

**Comment by swiftix** [comment]
Please test with following PR:
apple/swift-lldb#86

@swift-ci Please smoke test

**Comment by swiftix** [comment]
Please test with following PR:
apple/swift-lldb#86

@swift-ci Please smoke test

**Comment by swiftix** [comment]
Please test with following PR:
apple/swift-lldb#86

@swift-ci Please smoke test Linux platform

**Comment by gottesmm** [comment]
@swiftix This in general looks good to me. Give me a little bit to do some due diligence.

**Comment by jckarter** [comment]
Dunno how much time this would save, but if we left the SILModule to be destructed after LLVM code generation, we could avoid paying for its destructors by `_exit`-ing as soon as the output products are on disk.

**Comment by gottesmm** [comment]
@jckarter Then we would need to have two separate ways of cleaning up since in long living processes that would not be acceptable. Maybe we are willing to do that. No matter what, IMO, we would need some sort of abstraction to make sure people are not doing dumb things.

@swiftix I think you can move the SILModule thread construction /before/ embedBitCode.

**Comment by jrose-apple** [comment]
We *do* want a `-disable-free` mode like Clang has, but we can accomplish that by simply orphaning the SILModule instead of calling `_exit`.

**Comment by swiftix** [comment]
@gottesmm Good point! I moved the the SILModule thread construction /before/ embedBitCode.

**Comment by swiftix** [comment]
Please test with following PR:
apple/swift-lldb#86

@swift-ci Please smoke test

**Comment by swiftix** [comment]
Please test with following PR:
apple/swift-lldb#86

@swift-ci Please smoke test os x platform

**Comment by swiftix** [comment]
Please test with following PR:
apple/swift-lldb#86

@swift-ci Please smoke test Linux platform

**Pull request merged**
