### PR TITLE
[SourceKit/DocSupport] Update cross-import overlay symbols reported in the module doc-info request with their required bystanders.

### PR DESCRIPTION
**Pull request by nathawes**
~~NOTE: This PR includes the changes in https://github.com/apple/swift/pull/30521. Only the latest commit is new here. Ignore the rest.~~ (Other PR since merged).

Adds a new 'key.required_bystanders' entry to each symbol coming from a cross-import overlay. The value is a list of the bystander module names that need to be imported alongside the primary module for the cross-import overlay containing the symbol to be loaded.

Resolves rdar://problem/59446044

### CODE REVIEW

**Comment by nathawes** [comment]
@swift-ci please test

**Comment by akyrtzi** [comment]
Could you add some doc-comment in the test case, to ensure we don't include the "Available when B is imported with A" comment anywhere in the structured doc-comment info for declarations ?

**Comment by nathawes** [comment]
@swift-ci please test

**Comment by nathawes** [comment]
@swift-ci please test OS X Platform

**Comment by nathawes** [comment]
@swift-ci please test

**Comment by nathawes** [comment]
@swift-ci please test OS X Platform

**Review by akyrtzi — APPROVED** [review]

**Pull request merged**
