### PR TITLE
Use conditional conformances to implement Equatable for Optional, Array, and Dictionary

### PR DESCRIPTION
**Pull request by DougGregor**
Introduce conditional conformances to `Equatable` for `Optional`, `Array`, and `Dictionary`.

Fixes rdar://problem/21504479, rdar://problem/32035512, and rdar://problem/17924430.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
Ah, the source compatibility failure in Kickstarter is real, and caused by the XCTest changes:

/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite/project_cache/Kickstarter-ReactiveExtensions/ReactiveExtensionsTests/TestHelpers/XCTAssert-Extensions.swift:5:15: note: found this candidate
internal func XCTAssertEqual<T: Equatable>(_ expression1: @autoclosure () -> [[T]],
              ^
XCTest.XCTAssertEqual:1:13: note: found this candidate
public func XCTAssertEqual<T>(_ expression1: @autoclosure () throws -> T, _ expression2: @autoclosure () throws -> T, _ message: @autoclosure () -> String = default, file: StaticString = #file, line: UInt = #line) where T : Equatable
            ^

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
But UPASS’s. Ready to go in pending core team approval

**Comment by DougGregor** [comment]
Rebased and ChangeLog'd.

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by frogcjn** [comment]
Equatable for two dimension array still not working (e.g. `[[1]] == [[1]]`)

I used the swift-4.1-DEVELOPMENT-SNAPSHOT-2017-11-30-a-osx to test:
```
Welcome to Apple Swift version 4.1-dev (LLVM 05fee6ff60, Clang f0e38d2044, Swift a1441d34f7). Type :help for assistance.
  1> [[1]] == [[1]]
error: repl.swift:1:7: error: binary operator '==' cannot be applied to two '[[Int]]' operands
[[1]] == [[1]]
~~~~~ ^  ~~~~~

repl.swift:1:7: note: overloads for '==' exist with these partially matching parameter lists: (Any.Type?, Any.Type?), ((), ()), (Bool, Bool), (Character, Character), (Character.UnicodeScalarView.Index, Character.UnicodeScalarView.Index), (CodingUserInfoKey, CodingUserInfoKey), (OpaquePointer, OpaquePointer), (AnyHashable, AnyHashable), (UInt8, UInt8), (Int8, Int8), (UInt16, UInt16), (Int16, Int16), (UInt32, UInt32), (Int32, Int32), (UInt64, UInt64), (Int64, Int64), (UInt, UInt), (Int, Int), (AnyKeyPath, AnyKeyPath), (Unicode.Scalar, Unicode.Scalar), (ObjectIdentifier, ObjectIdentifier), (String, String), (String.Index, String.Index), (UnsafeMutableRawPointer, UnsafeMutableRawPointer), (UnsafeRawPointer, UnsafeRawPointer), (UnicodeDecodingResult, UnicodeDecodingResult), (_SwiftNSOperatingSystemVersion, _SwiftNSOperatingSystemVersion), (AnyIndex, AnyIndex), (ContiguousArray<Element>, ContiguousArray<Element>), (ArraySlice<Element>, ArraySlice<Element>), (T?, T?), (T?, _OptionalNilComparisonType), (_OptionalNilComparisonType, T?), ((A, B), (A, B)), ((A, B, C), (A, B, C)), ((A, B, C, D), (A, B, C, D)), ((A, B, C, D, E), (A, B, C, D, E)), ((A, B, C, D, E, F), (A, B, C, D, E, F)), (AutoreleasingUnsafeMutablePointer<Pointee>, AutoreleasingUnsafeMutablePointer<Pointee>), (ClosedRangeIndex<Bound>, ClosedRangeIndex<Bound>), (DoubleWidth<Base>, DoubleWidth<Base>), (DoubleWidth<Base>.Words.Index, DoubleWidth<Base>.Words.Index), (LazyDropWhileIndex<Base>, LazyDropWhileIndex<Base>), (EmptyCollection<Element>, EmptyCollection<Element>), (FlattenCollectionIndex<BaseElements>, FlattenCollectionIndex<BaseElements>), (FlattenBidirectionalCollectionIndex<BaseElements>, FlattenBidirectionalCollectionIndex<BaseElements>), (Set<Element>, Set<Element>), (Dictionary<Key, Value>.Keys, Dictionary<Key, Value>.Keys), ([Key : Value], [Key : Value]), (Set<Element>.Index, Set<Element>.Index), (Dictionary<Key, Value>.Index, Dictionary<Key, Value>.Index), (ManagedBufferPointer<Header, Element>, ManagedBufferPointer<Header, Element>), (LazyPrefixWhileIndex<Base>, LazyPrefixWhileIndex<Base>), (Range<Bound>, Range<Bound>), (CountableRange<Bound>, CountableRange<Bound>), (ClosedRange<Bound>, ClosedRange<Bound>), (CountableClosedRange<Bound>, CountableClosedRange<Bound>), (ReversedIndex<Base>, ReversedIndex<Base>), (ReversedRandomAccessIndex<Base>, ReversedRandomAccessIndex<Base>), (_UIntBuffer<Storage, Element>.Index, _UIntBuffer<Storage, Element>.Index), (UnsafeMutablePointer<Pointee>, UnsafeMutablePointer<Pointee>), (UnsafePointer<Pointee>, UnsafePointer<Pointee>), (_ValidUTF8Buffer<Storage>.Index, _ValidUTF8Buffer<Storage>.Index), (Self, Other), (Self, R)
[[1]] == [[1]]
      ^
```

**Comment by DougGregor** [comment]
You'll need a snapshot from master, or wait until we get a snapshot from a rebranched Swift 4.1 (which will be available in a day or two), to get this feature.

**Comment by AnthonyLatsis** [comment]
Proposal: SE-0143.

**Pull request merged**
