### PR TITLE
Update path to runtime msi wixproj in the Windows build

### PR DESCRIPTION
**Pull request by tristanlabelle**
Accounts for changes in https://github.com/apple/swift-installer-scripts/pull/217

### CODE REVIEW

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/217

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
```
C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift-installer-scripts\platforms\Windows\sdk\sdk.wixproj" (default target) (1:7) ->
(CoreCompile target) -> 
  C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift-installer-scripts\platforms\Windows\sdk\sdk.wxs(457): error WIX0103: Cannot find the File file '!(bindpath.rtmsm.x86)\runtime.x86.msm'. The following paths were checked: !(bindpath.rtmsm.x86)\runtime.x86.msm, T:\package\sdk\runtime.x86.msm [C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift-installer-scripts\platforms\Windows\sdk\sdk.wixproj]
  C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift-installer-scripts\platforms\Windows\sdk\sdk.wxs(460): error WIX0103: Cannot find the File file '!(bindpath.rtmsm.amd64)\runtime.amd64.msm'. The following paths were checked: !(bindpath.rtmsm.amd64)\runtime.amd64.msm, T:\package\sdk\runtime.amd64.msm [C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift-installer-scripts\platforms\Windows\sdk\sdk.wixproj]
```

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/217

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/217

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/217

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/217

@swift-ci please test Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/217

@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please smoke test macOS platform

**Comment by compnerd** [comment]
@swift-ci please smoke test macOS platform

**Comment by compnerd** [comment]
Please test with following PRs:
#67734

@swift-ci please smoke test macOS platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift/pull/67734

@swift-ci please smoke test macOS platform

**Comment by tristanlabelle** [comment]
The macOS error is unrelated:
```
FAIL: Swift(macosx-x86_64) :: stdlib/Observation/ObservableAvailabilityCycle.swift (1 of 16643)
******************** TEST 'Swift(macosx-x86_64) :: stdlib/Observation/ObservableAvailabilityCycle.swift' FAILED ********************
Script:
--
: 'RUN: at line 3';   /Users/ec2-user/jenkins/workspace/swift-PR-macos-smoke-test/branch-main/build/buildbot_incremental/swift-macosx-x86_64/bin/swift-frontend -target x86_64-apple-macosx10.13  -module-cache-path /Users/ec2-user/jenkins/workspace/swift-PR-macos-smoke-test/branch-main/build/buildbot_incremental/swift-macosx-x86_64/swift-test-results/x86_64-apple-macosx10.13/clang-module-cache -sdk '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk'  -swift-version 4  -define-availability 'SwiftStdlib 9999:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999' -define-availability 'SwiftStdlib 5.0:macOS 10.14.4, iOS 12.2, watchOS 5.2, tvOS 12.2' -define-availability 'SwiftStdlib 5.1:macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0' -define-availability 'SwiftStdlib 5.2:macOS 10.15.4, iOS 13.4, watchOS 6.2, tvOS 13.4' -define-availability 'SwiftStdlib 5.3:macOS 11.0, iOS 14.0, watchOS 7.0, tvOS 14.0' -define-availability 'SwiftStdlib 5.4:macOS 11.3, iOS 14.5, watchOS 7.4, tvOS 14.5' -define-availability 'SwiftStdlib 5.5:macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0' -define-availability 'SwiftStdlib 5.6:macOS 12.3, iOS 15.4, watchOS 8.5, tvOS 15.4' -define-availability 'SwiftStdlib 5.7:macOS 13.0, iOS 16.0, watchOS 9.0, tvOS 16.0' -define-availability 'SwiftStdlib 5.8:macOS 13.3, iOS 16.4, watchOS 9.4, tvOS 16.4' -define-availability 'SwiftStdlib 5.9:macOS 14.0, iOS 17.0, watchOS 10.0, tvOS 17.0' -define-availability 'SwiftStdlib 5.10:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999' -typo-correction-limit 10  -typecheck -parse-as-library -enable-experimental-feature InitAccessors -external-plugin-path /Users/ec2-user/jenkins/workspace/swift-PR-macos-smoke-test/branch-main/build/buildbot_incremental/swift-macosx-x86_64/lib/swift/host/plugins#/Users/ec2-user/jenkins/workspace/swift-PR-macos-smoke-test/branch-main/build/buildbot_incremental/swift-macosx-x86_64/bin/swift-plugin-server -primary-file /Users/ec2-user/jenkins/workspace/swift-PR-macos-smoke-test/branch-main/swift/test/stdlib/Observation/ObservableAvailabilityCycle.swift /Users/ec2-user/jenkins/workspace/swift-PR-macos-smoke-test/branch-main/swift/test/stdlib/Observation/Inputs/ObservableClass.swift
: 'RUN: at line 5';   /Users/ec2-user/jenkins/workspace/swift-PR-macos-smoke-test/branch-main/build/buildbot_incremental/swift-macosx-x86_64/bin/swift-frontend -target x86_64-apple-macosx10.13  -module-cache-path /Users/ec2-user/jenkins/workspace/swift-PR-macos-smoke-test/branch-main/build/buildbot_incremental/swift-macosx-x86_64/swift-test-results/x86_64-apple-macosx10.13/clang-module-cache -sdk '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk'  -swift-version 4  -define-availability 'SwiftStdlib 9999:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999' -define-availability 'SwiftStdlib 5.0:macOS 10.14.4, iOS 12.2, watchOS 5.2, tvOS 12.2' -define-availability 'SwiftStdlib 5.1:macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0' -define-availability 'SwiftStdlib 5.2:macOS 10.15.4, iOS 13.4, watchOS 6.2, tvOS 13.4' -define-availability 'SwiftStdlib 5.3:macOS 11.0, iOS 14.0, watchOS 7.0, tvOS 14.0' -define-availability 'SwiftStdlib 5.4:macOS 11.3, iOS 14.5, watchOS 7.4, tvOS 14.5' -define-availability 'SwiftStdlib 5.5:macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0' -define-availability 'SwiftStdlib 5.6:macOS 12.3, iOS 15.4, watchOS 8.5, tvOS 15.4' -define-availability 'SwiftStdlib 5.7:macOS 13.0, iOS 16.0, watchOS 9.0, tvOS 16.0' -define-availability 'SwiftStdlib 5.8:macOS 13.3, iOS 16.4, watchOS 9.4, tvOS 16.4' -define-availability 'SwiftStdlib 5.9:macOS 14.0, iOS 17.0, watchOS 10.0, tvOS 17.0' -define-availability 'SwiftStdlib 5.10:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999' -typo-correction-limit 10  -typecheck -parse-as-library -enable-experimental-feature InitAccessors -external-plugin-path /Users/ec2-user/jenkins/workspace/swift-PR-macos-smoke-test/branch-main/build/buildbot_incremental/swift-macosx-x86_64/lib/swift/host/plugins#/Users/ec2-user/jenkins/workspace/swift-PR-macos-smoke-test/branch-main/build/buildbot_incremental/swift-macosx-x86_64/bin/swift-plugin-server /Users/ec2-user/jenkins/workspace/swift-PR-macos-smoke-test/branch-main/swift/test/stdlib/Observation/ObservableAvailabilityCycle.swift -primary-file /Users/ec2-user/jenkins/workspace/swift-PR-macos-smoke-test/branch-main/swift/test/stdlib/Observation/Inputs/ObservableClass.swift
--
Exit Code: 1

Command Output (stderr):
--
/Users/ec2-user/jenkins/workspace/swift-PR-macos-smoke-test/branch-main/swift/test/stdlib/Observation/Inputs/ObservableClass.swift:5:2: error: 'Observable()' is only available in macOS 14.0 or newer
@Observable final public class ObservableClass {
 ^

--

**Comment by compnerd** [comment]
@swift-ci please smoke test macOS platform

**Pull request merged**
