### PR TITLE
[Migrator] Only replace primary file with input buffer

### PR DESCRIPTION
**Pull request by bitjammer**
In the Migrator, the AST passes (effectively syntactic edits only)
run before the fix-it passes. We try to reuse as much as possible
from the original CompilerInvocation, but we need to replace the
primary input. Nuking all of the inputs is a bit foolish :-).

rdar://problem/31858212

### CODE REVIEW

**Comment by bitjammer** [comment]
@swift-ci Please smoke test and merge

**Comment by jrose-apple** [comment]
It's probably important to preserve the order, too. The compiler ought to be order-independent but it isn't.

**Comment by bitjammer** [comment]
Tests pass but there was a Java exception in Jenkins.

**Comment by bitjammer** [comment]
Whup, I just saw your comment.

**Pull request merged**
