### PR TITLE
Fix SR-2868

### PR DESCRIPTION
**Pull request by hooman**
Added a guard statement to `significandWidth` property of floating point types to fix SR-2868.

Resolves [SR-2868](https://bugs.swift.org/browse/SR-2868).

### CODE REVIEW

**Comment by stephentyrone** [comment]
This looks fine, but please also add one or more tests that exercise this in `test/stdlib/Float.swift`.

**Comment by hooman** [comment]
First, My initial fix broke the API contract for the return value of `significandWidth` of infinity values. It is corrected now.

I looked at `test/stdlib/Float.swift` to add a test, but I am not sure what is the correct place to put it: Should I create a new test specifically for testing `significandWidth`, or should I just add `significandWidth` check to each case (normal, subnormal, infinity, etc)?

**Comment by stephentyrone** [comment]
Looking at things a bit more, I think the most natural place is as a new test in test/stdlib/FloatingPoint.swift.gyb:

    FloatingPoint.test("${Self}.significandWidth") {
      expectTrue(-1, ${Self}.infinity.significandWidth)
      expectTrue(-1, ${Self}.nan.significandWidth)
      expectTrue(0, ${Self}(1).significandWidth)
      // ... some additional cases ...
    }

**Comment by hooman** [comment]
Added `*.significandWidth` tests to `test/stdlib/FloatingPoint.swift.gyb`. I think this should be enough.

**Comment by stephentyrone** [comment]
@swift-ci please test and merge.

**Comment by stephentyrone** [comment]
@hooman Thanks for following up with the added tests.

**Comment by stephentyrone** [comment]
@swift-ci please test.

**Comment by stephentyrone** [comment]
@hooman reading the logs, the Linux failure appears to be unrelated to your change (the same failure is present in some earlier unrelated test runs). I'll re-run the tests once the bots are green and we'll go from there.

**Comment by hooman** [comment]
OK, thank you.

**Comment by stephentyrone** [comment]
@swift-ci please smoke test and merge.

**Comment by stephentyrone** [comment]
@swift-ci Please test.

**Comment by stephentyrone** [comment]
@swift-ci Please smoke test.

**Comment by stephentyrone** [comment]
@swift-ct Please smoke test Linux.

**Comment by stephentyrone** [comment]
@swift-ci Please smoke test Linux.

**Comment by hooman** [comment]
Great! Thank you.

**Pull request merged**
