### PR TITLE
Add support for end_lifetime in DCE

### PR DESCRIPTION
**Pull request by meg-gupta**

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci test

**Review by gottesmm — APPROVED** [review]

**Comment by gottesmm** [comment]
@meg-gupta looks reasonable. Before this goes in, can you do a quick pattern match over the pass for places we handle destroy_value and make sure that we do not need to handle end_lifetime there? I am going to flag the ones I found.

**Comment by gottesmm** [comment]
https://github.com/apple/swift/blob/0d16eda6958b4d6cfc62ee8e3217b88e29f7dc66/lib/SILOptimizer/Transforms/DeadCodeElimination.cpp#L577
https://github.com/apple/swift/blob/0d16eda6958b4d6cfc62ee8e3217b88e29f7dc66/lib/SILOptimizer/Transforms/DeadCodeElimination.cpp#L603

I haven't thought completely through if those are interesting, but just take a quick look and make sure it is ok.

**Comment by meg-gupta** [comment]
Thanks @gottesmm. Other instance of `destroy_value` look fine to me.

**Pull request merged**
