### PR TITLE
Clarify the function of `_SwiftValue`

### PR DESCRIPTION
**Pull request by tbkka**
This expands the implementation notes for AnyObject to include a more detailed explanation of the `_SwiftValue` box and its purpose.

### CODE REVIEW

**Comment by tbkka** [comment]
@swift-ci Please smoke test

**Comment by benrimmington** [comment]
@swift-ci Please smoke test macOS platform

**Comment by tbkka** [comment]
@swift-ci Please smoke test and merge

**Comment by benrimmington** [comment]
@swift-ci Please smoke test

**Pull request merged**
