### PR TITLE
Fix a couple of problems with opaque result types

### PR DESCRIPTION
**Pull request by slavapestov**
While investigating rdar://problem/59107421 I found two problems in SILGen:

- Crash when a function with an opaque return type returns a tuple.
- Crash when emitting a keypath getter or setter thunk for a class property with an opaque result type.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Review by jckarter — APPROVED** [review]
Thanks Slava!

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Pull request merged**
