### PR TITLE
remove dead fn signature, NFC.

### PR DESCRIPTION
**Pull request by lattner**

### CODE REVIEW

**Comment by lattner** [comment]
@swift-ci please test and merge

**Comment by lattner** [comment]
@swift-ci please test and merge

**Comment by lattner** [comment]
@swift-ci please test and merge

**Comment by lattner** [comment]
@swift-ci please test and merge

**Comment by lattner** [comment]
@swift-ci please test and merge

**Comment by lattner** [comment]
sigh.

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Pull request merged**
