### PR TITLE
Fix TODO by removing unneeded ShouldSerializeAll parameters.

### PR DESCRIPTION
**Pull request by gabrielPeart**
Fix TODO by removing unneeded ShouldSerializeAll parameters.

Closed old #357 and opening this new pull request

/cc @gottesmm

### CODE REVIEW

**Comment by gottesmm** [comment]
Did you run all of the tests? Also can you remove the TODO from the title of the commit and instead say something like this:

Fix TODO by removing unneeded ShouldSerializeAll parameters.

**Comment by gabrielPeart** [comment]
Yes, I executed all tests and generated the build. Passed without problems.
Already adjusted the title, thanks for the tip.

**Comment by gottesmm** [comment]
Sorry for being unclear, when I said the title of the commit, I meant the first line of the git commit msg.

**Comment by gabrielPeart** [comment]
No problem. Looks okay now?

**Comment by gottesmm** [comment]
The actual git commit looks the same to me. Are you sure you fixed it?

**Comment by gabrielPeart** [comment]
I did amend in the commit message and sent a new pull request #420
Going to close this one.
Sorry about this extra delay.

**Pull request closed without merging**
