### PR TITLE
[Diagnostics] Use imperative msg for protocol conformance & switch-case fixits

### LINKED ISSUE #67510: Fix-Its should be phrased as imperative actions rather than questions
Swift phrases quick fixes as questions:

image

This is inconsistent with other extensions and code actions, which are phrased as imperative verbs:

image
image
image
image

### PR DESCRIPTION
**Pull request by nishithshah2211**
This commit changes fixit messages from a question/suggestion to an imperative message for protocol conformances and switch-case. The only source change is in `DiagnosticsSema.def`. Rest of the changes are in tests to get them to pass.

Resolves https://github.com/apple/swift/issues/67510.

### CODE REVIEW

**Review by ktoso — APPROVED** [review]
Yeah given the discussion in the issue I think moving to imperative form is good

**Comment by ktoso** [comment]
Let's also give @xedin and @ahoppen a chance to review 👍

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by nishithshah2211** [comment]
Previous CI run had some failing tests - addressed them with a new commit. @ktoso

**Comment by ktoso** [comment]
Thanks, let's give this a full run to be sure that's everything covered

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by nishithshah2211** [comment]
@ktoso - Linux build is failing because of this - https://github.com/apple/sourcekit-lsp/blob/6d3db6d0850d53d9521374c1c18212d6834ae1f9/Tests/SourceKitLSPTests/PullDiagnosticsTests.swift#L121. I can open a PR for that repo in parallel.

**Comment by nishithshah2211** [comment]
And the macOS build is failing on `FAIL: test_tsan_swift_dwarf (TestTsanSwiftAccessRace.TsanSwiftAccessRaceTestCase)`. Not sure how any changes in this PR should affect that.

**Comment by hborla** [comment]
@swift-ci please test

**Comment by nishithshah2211** [comment]
The windows had succeeded earlier but timed out this time 😞

I think Linux and macOS builds are expected to fail because they are running tests that are in a different repo - https://github.com/apple/sourcekit-lsp/blob/6d3db6d0850d53d9521374c1c18212d6834ae1f9/Tests/SourceKitLSPTests/PullDiagnosticsTests.swift#L121. 

What is the best way to address this? One way is to create a parallel PR that changes the `SourceKitLSPTests` test and we can try to time the PR merges. But it feels hacky.

**Comment by nishithshah2211** [comment]
> We can do cross-PR testing here to check the combined PRs.

How can that be done? I created https://github.com/apple/sourcekit-lsp/pull/799 in parallel but both need to be built together.

Another way is to avoid running the `SourceKitLSP` tests for PRs inside of this repo but I think there is likely a good reason why SourceKit-LSP tests get run for PRs in this repo.

**Review by kavon — APPROVED** [review]

**Comment by nishithshah2211** [comment]
Can the windows build be re-triggered? All other builds succeeded.

**Comment by bnbarham** [comment]
https://github.com/apple/sourcekit-lsp/pull/799

@swift-ci please test Windows platform

**Comment by nishithshah2211** [comment]
@bnbarham Thanks for triggering the CI. The builds succeeded - please merge both the PRs when you get a chance, thanks!

**Comment by ahoppen** [comment]
Thank you for your contribution @nishithshah2211

**Comment by nishithshah2211** [comment]
Thanks for the merge!

**Pull request merged**
