### PR TITLE
Fix ExistentialSpecializer to correctly cleanup storage.

### PR DESCRIPTION
**Pull request by atrick**
Handle calling conventions and cleanups in all the places (hopefully).
- when ExistentialSpecializer copies the specialized concrete arg into the
original existential value
- when ExistentialSpecializer generates a think
- when SILCombine substitutes concrete values in place of the opened
existential.

One particularly nasty problem is the existential boxes need to be
destroyed. It is not ok to simply destroy their value. The "leaks"
tool does not catch this problem.

Ownership SIL will make this all much more robust.

Fixes <rdar://problem/50595630> Multiple leaks detected - Swift Perf

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
@swift-ci test source compatibility

**Comment by atrick** [comment]
@swift-ci benchmark

**Comment by atrick** [comment]
I cannot reproduce the SortLargeExistentials regression locally. It only showed up in Osize which usually indicates something wasn't inlined.

@rajbarik will you have a chance to review these changes?

**Comment by rajbarik** [comment]
@atrick Sorry, I got sidetracked with something and did not see the email until now. I will have a look at it today.

**Pull request merged**
