### PR TITLE
[CMake] Fix dependency on codesign steps

### PR DESCRIPTION
**Pull request by llvm-beanz**
CMake's ninja generator doesn't apply POST_BUILD steps to phony targets, instead in creates standalone CUSTOM_COMMAND actions for them. The generated CUSTOM_COMMANDS then end up running always because they don't have properly specified dependencies.

This patch changes the code sign step on the lipo commands from being POST_BUILD commands to being standalone commands with properly specified inputs and outputs. It works by appending "-unsigned" to the name of the lipo target and the lipo output on Darwin build and replacing the lipo target with a target that wraps the code sign command.

With this patch re-running ninja on an already built build directory no longer results in re-codesigning all the stdlib dylibs.

### CODE REVIEW

**Comment by llvm-beanz** [comment]
@swift-ci please smoke test

**Comment by jrose-apple** [comment]
cc @lplarson, who added the codesigning logic.

**Comment by lplarson** [comment]
This looks great. Thanks for doing this, Chris!

**Comment by lattner** [comment]
Thank you for working on this ChrisB!

**Comment by gottesmm** [comment]
LGTM

**Pull request merged**
