### PR TITLE
(Properly) fix potentially inconsiderate naming

### PR DESCRIPTION
**Pull request by Inari-Whitebear**
So I don't mind master/slave terminology, but if you're going to fix it, at least end up with something others chose too. See django which ended up with Primary/Replica (after first adopting Leader/Follower in django/django#2692) in django/django#2694 (which was just closed, but still changed in https://github.com/django/django/commit/beec05686ccc3bee8461f9a5a02c607a02352ae1 )

The only thing I personally have against Leader/Follower is that it is a bit odd as a german (and seems I'm not alone in that feeling). Though I wouldn't mind that had it not already been changed from master/slave anyway. Just want it changed "properly" if it gets changed at all. It also seems to be used in literature already from what I was told.

### CODE REVIEW

**Comment by cwillmor** [comment]
Primary/replica works well for Django where it refers to database replication. But this test deals with one thread coordinating another. There's no replication involved.

**Comment by Inari-Whitebear** [comment]
I see, will have to find a better fitting thingy then, maybe.

**Comment by batmuffino** [comment]
Why can't we just call it 'Doer' and 'AlsoDoer' and call it a day? :)

**Comment by hauffi** [comment]
Why can't we just stop being political correct with a programming language and use what works already. This is a serious suggestion. I don't feel like these PC requests are needed in a community that should be focusing on bugs and real issues, not a social idea of what is wrong or right with a word on a programming language.

**Comment by jrose-apple** [comment]
To quote Katie Mack, "[This is not a change we make for the people it doesn't matter to.](https://twitter.com/AstroKatie/status/647964736823255040)". Feel free to ignore these kinds of changes if they don't interest you.

**Comment by jckarter** [comment]
I think you're on to something, @batmuffino. Looking over the test, I see no structured relationship between the threads at all. Doing away with the enum altogether and just marking them as `0` and `1` is probably a more accurate model.

**Comment by batmuffino** [comment]
@jrose-apple that's why I mentioned using the most simple names with least connotation. As a german, master/slave sounds less inconsiderate than leader/follower. But since it's basically just as @jckarter says one could also just call it primary/secondary or sth.

**Comment by jrose-apple** [comment]
I like "primary/secondary". That's a minimal change from what's there. No objections to just using an Int, though.

**Comment by DylanLukes** [comment]
@cwillmor By the same logic, wouldn't `Parent`/`Child` make more sense here, since we're dealing with threads?

But, let's actually look at what makes a good name, because I don't think `Primary`/`Replica` OR `Leader`/`Follower` are very good names at all. `Slave`/`Master` is the most semantically correct based on etymology and and the most technically correct based on prior usage of these three: the only negative is the association with 20th century American chattel slavery. **I'll make no statement of opinion on whether I think this is reasonable or not because in the current climate that's basically career suicide**.

But, if this is going to be changed, it should be changed to something that is maximally either directly or metaphorically descriptive.

While `Leader`/`Follower` are "nice" names indeed, they are not semantically correct. They imply a very different relationship. They'd make great sense in, say, a pub-sub model, where a `Follower` *willingly* chooses to follow a `Leader`. `Primary`/`Replica` are also not good names, they are totally unrelated to this particular case and are almost exclusively used in data-related contexts (RDBMS, file sharing, etc).

I propose `Parent`/`Child`. It's:

 - Accepted and widely-used terminology for processes and threads.
 - Concise and semantically reasonable.
 - Doesn't offend anyone. 

The only problem, of course,  is that because there's only one `Parent`, it could be construed as an attempt to subtly undermine American family values and the notion of the atomic family. :wink:

**Comment by landaire** [comment]
I was thinking the same as @DylanLukes. In the context of threading/processes it's already common wording that people are familiar with. `Primary` could possibly be confused with the main thread as well and in my opinion they don't convey the same meaning (although I could be misunderstanding this context).

**Comment by DylanLukes** [comment]
@landaire Good point on confusion. Might be worth grepping the repository for usages of any suggested terms. Whatever is picked, it shouldn't already be in use in with a different meaning. 

Inconsistent signifieds are even worse than inconsistent signifiers.

**Comment by jrose-apple** [comment]
In this test case, the threads aren't actually in a parent/child relationship. There's one that goes first, and one that goes second, but the "parent" thread is the main thread. (See [the full file](https://github.com/apple/swift/blob/f97b46170ffe557909f5bf460f25b201c0e7f3c8/validation-test/stdlib/StringSlicesConcurrentAppend.swift).)

**Comment by landaire** [comment]
`Primary`/`Secondary` would probably make more sense in this context then.

**Comment by DylanLukes** [comment]
On further consideration, agreed.

**Comment by nbulous** [comment]
Some other alternatives that I haven't seen mentioned here are: Master/Follower, Coordinator/Worker, Dispatcher/Runner, Queen/Worker (bees, anyone?).

**Comment by DylanLukes** [comment]
@nbulous `Leader`/`Follower` is what's there right now. `Master`/`Follower` is practically the same. I don't think any of your other suggestions really make sense in context. Based on what what @jrose-apple pointed out, `Primary`/`Secondary` or even just `First`/`Second` make the most sense.

Or, just integers. It's just a test case.

**Comment by beren12** [comment]
Leader/Follower is just odd. Please stick to programming terminology: Master/Slave, Parent/Child, etc. Code is confusing enough to not need to worry about this waste of time. There is nothing "bad" about a slave/child process/test/thread. Honestly Leader/Follower makes no sense.

**Comment by gribozavr** [comment]
How about `CreatorMutator` and `ReaderMutator`?

**Comment by radex** [comment]
> Leader/Follower is just odd. Please stick to programming terminology: Master/Slave

Just because it is standard programming terminology doesn't mean it should be. 

Does it affect you and me? No. Is it something super important to change? Perhaps not. But if someone cares and puts in the effort to propose something not as awfully connotated as master/slave, why not?

+1 to Primary/Secondary in this case.

**Comment by kmonsoor** [comment]
+1 for Primary/Secondary.

**Comment by brentdax** [comment]
If they're just two peer threads coordinating in an attempt to wreak havoc, let's call them [RobinHood and FriarTuck](http://catb.org/jargon/html/meaning-of-hack.html). Or [Fred and George](http://harrypotter.wikia.com/wiki/Fred_and_George_Weasley). Or anything that doesn't annoy people. (I don't like integers for this purpose; there are exactly two threads, not N threads.)

**Comment by Inari-Whitebear** [comment]
@brentdax: Interesting. Personally in that case I'd be concerned about another PR popping up someday (not from me, but someone) because both names are male or something. Just covering all the bases.

**Comment by hakkotsu** [comment]
And this is a real example how some stupid, unimportant, irrelevant to final product change, occupies hundreds of people to discuss some bullshit. Well done @jckarter

> Does it affect you and me? No. Is it something super important to change? Perhaps not. But if someone cares and puts in the effort to propose something not as awfully connotated as master/slave, why not?

Because its bullshit.

**Comment by jckarter** [comment]
We're deep in Wadler's law territory at this point. `Primary`/`Secondary` should be fine. @Inari-Whitebear if you don't mind updating your patch to use those terms, I'll take accept the pull request. Thanks for the discussion everyone!

**Comment by jckarter** [comment]
Thanks @Inari-Whitebear!

**Pull request merged**
