### PR TITLE
[5.9][Macros] Update plugin search options serialization

### PR DESCRIPTION
**Pull request by rintaro**
Cherry-pick #66689 and #66722 into release/5.9

* **Explanation**: Since https://github.com/apple/swift/pull/66678, plugin search compiler options (e.g. `-plugin-path`, `-load-plugin-library`) are processed by the order specified in the argument list. But they were still serialized/deserialized in the module grouped by each option kind. That may have caused incorrect plugins loading. This change fix that by updating the serialization. Also, this PR includes plugin search table change which which may improve plugin search performance.
* **Scope**: Macro plugin loading.
* **Risk**: Low. Plugin search option serialization and lldb support is a new feature for 5.9.
* **Testing**: Passed existing test suite
* **Issue**: rdar://110903149
* **Reviewer**: Ben Barham (@bnbarham), Alexis Laferrière (@xymus)

### CODE REVIEW

**Comment by rintaro** [comment]
https://github.com/apple/llvm-project/pull/7011
@swift-ci Please test

**Comment by adrian-prantl** [comment]
Does this affect any of the LLDB deserialization code in https://github.com/apple/llvm-project/blob/e2b11c251e5ef2be08e2b10bf4f0421308dcb871/lldb/source/Plugins/TypeSystem/Swift/SwiftASTContext.cpp#L1285 ?

**Comment by rintaro** [comment]
@adrian-prantl Yes, https://github.com/apple/llvm-project/pull/7011 is the corresponding change.

**Comment by rintaro** [comment]
https://github.com/apple/llvm-project/pull/7011
@swift-ci Please test

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
