### PR TITLE
Change two instances where we are using strcmp to use == as a follow …

### PR DESCRIPTION
**Pull request by gottesmm**
…up to #26158.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Review by jrose-apple — APPROVED** [review]
Thank you!

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by drodriguez** [comment]
Seems that #26158 might have affected the Windows builds (https://ci-external.swift.org/job/oss-swift-windows-x86_64/709/). I'm going to check if this fixes them or we need something else.

/cc @compnerd 

@swift-ci please test Windows platform

**Comment by gottesmm** [comment]
@drodriguez I think the problem is that MSVC is being MSVC and doing stupid things around constexpr. The getPrefixed thing can just remove the constexpr.

**Pull request merged**
