### PR TITLE
Adjust for SVN r299899

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @DougGregor @bob-wilson

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Review by bob-wilson — COMMENTED** [review]
It looks like getParamAttributes() returns null when there are no attributes. Instead of checking "Attrs->getNumAttributes()", I think you should just check if Attrs is non-null.

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by bob-wilson** [comment]
I'm going to merge this. The bots are all broken and this will at least get us closer to passing.

**Pull request merged**
