### PR TITLE
[LVA] Don't invalidate reads/writes that don't alias any tracked values.

### PR DESCRIPTION
**Pull request by zoecarver**
In DSE and RLE any unknown read/write often causes most if not all tracked values to be invalidated. This doesn't need to be the case. If the tracked value doesn't alias any of the operands of the unknown instruction, then we can safely keep the tracked value validated.

Requires #31131

### CODE REVIEW

**Review by eeckstein — COMMENTED** [review]
I don't think you can make this assumption.
Let's assume an instruction (which could e.g. be a function call), which has an address of an object reference as operand and reads that reference and writes some field in the object.
The operand (address of the reference) is not aliased with the object itself, but would overwrite values in the object.

**Comment by zoecarver** [comment]
I'm going to benchmark #31134 and #31132 together and compare it to the benchmark results from #31078. That will tell us if this patch is a significant performance improvement. If it's not, then I'm happy to drop it.

**Comment by zoecarver** [comment]
Given [my comment](https://github.com/apple/swift/pull/31208#issuecomment-617977653) on the performance improvements of this patch. I think it would be beneficial to move forward with this change. 

@eeckstein sorry for all the messages recently. No rush responding.

**Comment by zoecarver** [comment]
@swift-ci please benchmark

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
