### PR TITLE
Remove `swift-indent` tool

### PR DESCRIPTION
**Pull request by compnerd**
This removes the implementation of the `swift-indent` tool, its associated documentation, and utilities. This tool was never completed and has much better alternatives with `swift-format` which is more flexible and actually maintained.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]
Makes sense to me!

**Review by tshortli — APPROVED** [review]

**Review by etcwilde — APPROVED** [review]
LGTM.
Do we need a matching patch to the driver repo to update the options there?

**Comment by compnerd** [comment]
Yeah, it would be good to update swift-driver as well.

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Review by CodaFi — APPROVED** [review]

**Pull request merged**
