### PR TITLE
[stdlib] Remove inlineable annotation from transparent functions

### PR DESCRIPTION
**Pull request by airspeedswift**
If a function is `@_transparent` it shouldn't need to be `@inlinable` too.

Some of these uses of `@_transparent` maybe be better marked as `@inlinable` instead but that is for a later audit.

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@swift-ci please smoke test compiler performance

**Review by slavapestov — APPROVED** [review]

**Comment by airspeedswift** [comment]
@swift-ci please test linux platform

**Comment by slavapestov** [comment]
I don’t understand why there was a regression. I would expect the change to be NFC

**Comment by airspeedswift** [comment]
It’s wall time, none of the counters changed, so it could be a glitch.

@swift-ci please smoke test compiler performance

**Comment by airspeedswift** [comment]
@swift-ci please test Linux platform

**Comment by airspeedswift** [comment]
@swift-ci please test source compatibility

**Comment by airspeedswift** [comment]
Yeah, glitch.

**Comment by airspeedswift** [comment]
@swift-ci please test Linux platform

**Pull request merged**
