### PR TITLE
DO NOT MERGE: Revert "utils/find-overlay-dependencies.sh: Don't lose Foundation's CoreGraph…"

### PR DESCRIPTION
**Pull request by milseman**
Reverts apple/swift#9665

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please test OS X Platform

**Comment by milseman** [comment]
This might be the cause of linker problems with libFoundationTestsShared.dylib

**Comment by jrose-apple** [comment]
Please don't revert this. Our Foundation overlay really does depend on CoreGraphics.

**Comment by jrose-apple** [comment]
…and this script is only run manually, which means reverting it won't actually change anything.

**Comment by milseman** [comment]
Are you arguing that this will not give us a data point in the problem finding libFoundationTestsShared.dylib?

**Comment by milseman** [comment]
Irrelevant

**Pull request closed without merging**
