### PR TITLE
SILOptimizer: fix a crash in the keypath optimization

### PR DESCRIPTION
**Pull request by eeckstein**
Use the correct type lowering.

rdar://problem/61122088

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci test macOS

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by jckarter** [comment]
Thanks Erik!

**Review by jckarter — APPROVED** [review]

**Pull request merged**
