### PR TITLE
[6.0] Define availability for the 6.0 stdlib & runtime

### PR DESCRIPTION
**Pull request by lorentey**
- **Explanation:** This updates Swift 6.0 API additions & runtime features on Apple platforms, resolving their availability to the OS versions that were announced this week.
- **Scope:** Standard Library, benchmarks, runtime availability checks.
- **Risk:** Low. API with SwiftStdlib 6.0 availability will only be testable on Apple's beta releases.
- **Testing:** Regular PR testing.
- **Reviewer:** @tshortli , @Azoy, @shahmishal, @al45tair, @ktoso 
- **Original PR:** https://github.com/apple/swift/pull/74366
- **Issue:** n.a. -- routine release maintenance task

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci benchmark

**Review by stephentyrone — APPROVED** [review]

**Review by shahmishal — APPROVED** [review]

**Comment by lorentey** [comment]
```
<unknown>:0: error: fatal error encountered during compilation; please submit a bug report (https://swift.org/contributing/#reporting-bugs)
<unknown>:0: note: Missing runtime version data for Swift 5.11
```

Oops, I missed mentions of 5.11 in FeatureAvailability.def.

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci benchmark

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci benchmark

**Pull request merged**
