### PR TITLE
[benchmark] Baseline test

### PR DESCRIPTION
**Pull request by palimondo**
This PR adds new a `-check-added` option to the `run_smoke_bench.py` that finds the added benchmarks and runs an equivalent of `Benchmark_Driver check` on them. It can be run together with `-verbose` option to output more details during the benchmark analysis.

It outputs the `BenchmarkDoctor`'s report with Warnings and Errors, if the new benchmarks violate the best practices. `BenchmarkDoctor` currently always returns exit code 0. In the future, we might change this to depend on the presence of ERRORs in the report, if deemed useful, so that violations of good baseline could not be committed to the tree.

It depends on `BenchmarkDriver` and `compare_perf_tests.py` being in the same directory.

### CODE REVIEW

**Comment by palimondo** [comment]
@eeckstein Please review 🙏

Can you integrate this into @swift-ci?

**Comment by eeckstein** [comment]
Can you include that in run_smoke_bench?
Then it would run automatically for each benchmark run.
I don't know how long it takes to check new benchmarks, but if it only checks _new_ benchmarks, then the overhead time is not so important.
Integrating it into a regular CI test is not really doable because it requires two benchmark builds.

**Comment by palimondo** [comment]
I could? But than it would be invoked for each of the optimization levels, right? It should run only once, as it validates only the `-O` mode. I though it would be invoked from `@swift-ci benchmark` after the `run_smoke_bench.py`... Am I misunderstanding how `run_smoke_bench.py` get's invoked by CI?

**Comment by palimondo** [comment]
Or do you mean I should add it as another option to the `run_smoke_bench`? That could work… but it would still require *some * kind of modification to the CI, to invoke it. Is that what you meant?

**Comment by eeckstein** [comment]
Yes, just add an option and we can change the ci script to pass that option

**Comment by palimondo** [comment]
@eeckstein I've integrated the `check_added_bench.py` into `run_smoke_bench.py` as `-check-added` option. Please review.

**Comment by palimondo** [comment]
Yes. `BenchmarkDriver.__init__` calls [`_get_tests`](https://github.com/apple/swift/blob/master/benchmark/scripts/Benchmark_Driver#L107-L119), which does `Benchmark_O --list` and applies the filters (regex), if any are present.

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Pull request merged**
