### PR TITLE
[Stats] Fix a second/nanoseconds bug in process-stats-dir

### PR DESCRIPTION
**Pull request by ahoppen**
Times are expected to be represented in nanoseconds in process-stats-dir, but times with the 'swift.time.' prefix (e.g. times for specific requests) were not converted.

It appears the reasons that this hasn’t been caught so far, is that these times are not shown in Swift-CI's please test compiler performance report.

Because of this bug (almost) all the timers returned `process-stats-dir.py` were zero and thus the values for the timing always passed `scale-test`. Fixing the bug made a bunch of `scale-test` fail non-deterministically because the timings are too noisy. To fix this, I’ve added an option `--exclude-timers` to `scale-test` which explicitly ignores any values that start with `time.`.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
Let’s verify the compiler performance output is still looking good.

@swift-ci Please smoke test compiler performance

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test compiler performance

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by slavapestov — APPROVED** [review]
Thanks! I had a similar fix sitting around locally, but you beat me to it.

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Pull request merged**
