### PR TITLE
[WIP] Avoid rerunning diagnostic passes on deserialized SIL.

### PR DESCRIPTION
**Pull request by atrick**
This provides basic control over the compilation pipeline that we
typically expect when reasoning about the pass order. It obviously
saves app compile time. It's not uncommon for early mandatory passes
to assume that they won't be rerun after arbitrary optimization and
lowering. Ideally, this shouldn't be required for correctness, but for
the time being it is required at least for exclusivity
diagnostics. It's also impossible to verify access markers without
this feature.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
@swift-ci Please test compiler performance

**Comment by atrick** [comment]
@swift-ci benchmark.

**Comment by atrick** [comment]
@swift-ci Test Source Compatibility.

**Comment by gottesmm** [comment]
Cool!

**Pull request closed without merging**
