### PR TITLE
Remove duplicated import in Metada unit test

### PR DESCRIPTION
**Pull request by AgranatMarkit**
I'm find duplicated import and want to remove it.

### CODE REVIEW

**Comment by AgranatMarkit** [comment]
@swift-ci Please smoke test

**Comment by WowbaggersLiquidLunch** [comment]
@swift-ci please smoke test

**Review by WowbaggersLiquidLunch — APPROVED** [review]
even though I'm not knowledgable with the runtime, nor this file in particular, the change is obviously correct in my opinion

**Comment by WowbaggersLiquidLunch** [comment]
@AgranatMarkit do you think this is read to be merged?

**Comment by AgranatMarkit** [comment]
> @AgranatMarkit do you think this is read to be merged?

Yes i do.

**Pull request merged**
