### PR TITLE
[5.9] Don't DCE @owned phis that may have escaped

### PR DESCRIPTION
**Pull request by meg-gupta**
Cherry-pick of https://github.com/apple/swift/pull/64709

### CODE REVIEW

**Review by nate-chandler — APPROVED** [review]

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Review by atrick — APPROVED** [review]

**Comment by meg-gupta** [comment]
@swift-ci smoke test macOS platform

**Comment by nate-chandler** [comment]
5.9 branch requires full PR testing.

**Comment by meg-gupta** [comment]
@swift-ci test macOS Platform

**Comment by meg-gupta** [comment]
@swift-ci test macOS Platform

**Review by tbkka — APPROVED** [review]

**Comment by meg-gupta** [comment]
@swift-ci test Linux Platform

**Pull request merged**
