### PR TITLE
[NFC] Mark cross-import overlay + module trace test unsupported on Windows.

### PR DESCRIPTION
**Pull request by varungandhi-apple**

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test Windows platform

**Comment by varungandhi-apple** [comment]
Temporary work around for fallout from #29582

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test and merge

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test Windows platform

**Comment by varungandhi-apple** [comment]
@swift-ci please clean smoke test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
Windows doesn't support smoke tests, just the full test (but takes ~30m)

**Pull request merged**
