### PR TITLE
Revert "[5.5][TypeChecker] PreCheck: Don't strip away tuple/paren from subscripts …"

### PR DESCRIPTION
**Pull request by xedin**
Reverts apple/swift#37067

Resolves: rdar://77457640

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Review by angela-laar — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Comment by xedin** [comment]
Unrelated Windows failure:

```Failed Tests (1):
  Swift(windows-x86_64) :: Concurrency/throwing.swift
```

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Pull request closed without merging**
