### PR TITLE
[SwiftSyntax] Change vars in nodes to lets

### PR DESCRIPTION
**Pull request by harlanhaskins**
This should have applied to #14122.

### CODE REVIEW

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test

**Review by nkcsgexi — APPROVED** [review]

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test and merge

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
