### PR TITLE
[IDE] Fix SyntaxModel crash due to out-of-order walking of EnumElementDecls

### PR DESCRIPTION
**Pull request by nathawes**
`ModelASTWalker` was previously constructing `SyntaxNode`s for `EnumElementDecl`s manually when visiting their associated `EnumCaseDecl` so that they would appear as its children rather than its siblings. It wasn't actually walking these nodes though, so missed handling some things, e.g. closures passed as default argument values. It was also still walking the same `EnumElementDecl`s again in the sibling position. Because the `TokenNode`s in the range of each `EnumElementDecl` were consumed when they were manually constructed, this second visit was triggering some recently added assertions in the handling of custom attributes, which expected the corresponding `TokenNode`s to still be present.

Resolves rdar://problem/53313197

### CODE REVIEW

**Comment by nathawes** [comment]
@swift-ci please test

**Comment by nathawes** [comment]
@swift-ci please stress test

**Comment by nathawes** [comment]
@swift-ci please test

**Comment by nathawes** [comment]
@swift-ci please test

**Comment by nathawes** [comment]
@swift-ci please test OS X Platform

**Review by akyrtzi — APPROVED** [review]

**Pull request merged**
