### PR TITLE
[BuilderTransform] Remove unused `skipPrecheck` from `PreCheckResultB…

### PR DESCRIPTION
**Pull request by xedin**
…uilderRequest::evaluate`

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please smoke test

**Review by hborla — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Comment by xedin** [comment]
@swift-ci please smoke test Windows platfom

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Comment by xedin** [comment]
@swift-ci please smoke test Windows platform

**Pull request merged**
