### PR TITLE
[5.3] Revert "Merge pull request #32655 from benlangmuir/sema-repeat-53"

### PR DESCRIPTION
**Pull request by benlangmuir**
This reverts commit 46c6eeeeadd38ed1c94498e472763ab68bf2dcd7, reversing
changes made to eed09ea05011c3d7e08da0724ca7235971eb99fc.

This caused an unexpected regression.

rdar://65554791

### CODE REVIEW

**Comment by benlangmuir** [comment]
@swift-ci please test

**Review by akyrtzi — APPROVED** [review]

**Comment by benlangmuir** [comment]
```
18:10:54 Failing Tests (1):
18:10:54     Swift(iphonesimulator-i386) :: Constraints/operator.swift`
```

Unrelated failure.

**Comment by benlangmuir** [comment]
@swift-ci please test macOS

**Comment by akyrtzi** [comment]
@swift-ci please test macOS

**Pull request merged**
