### PR TITLE
[TF] Update checkout for 'tensorflow/swift-apis'

### PR DESCRIPTION
**Pull request by Shashi456**
changes mentioned in this [comment](https://github.com/tensorflow/swift-apis/pull/102#issuecomment-496397650).

--- 

Update to https://github.com/tensorflow/swift-apis/commit/ca8ac09285b0aaa7c6bbd08c375b1ba2b9e259e9.

### CODE REVIEW

**Comment by Shashi456** [comment]
@rxwei Done.

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow Linux

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow Linux

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow Linux

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow Linux

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow Linux

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow Linux

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow Linux

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow Linux

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow Linux

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow Linux

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow Linux

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow Linux

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow Linux

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow Linux

**Pull request merged**
