### PR TITLE
[SILGen] Forward address-only self to borrowing accessors.

### PR DESCRIPTION
**Pull request by nate-chandler**
Utilize and expand the pre-existing peephole.

rdar://127115078

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
```
### Performance (arm64): -O

**Regression**                          | **OLD** | **NEW** | **DELTA** | **RATIO**
:---                                    | ---:    | ---:    | ---:   | ---:     
FindString.Loop1.Substring              | 163.067 | 181.923 | +11.6% | **0.90x (?)**
&nbsp; | | | | 
**Improvement**                         | **OLD** | **NEW** | **DELTA** | **RATIO**
FindString.Rec3.String                  | 79.276  | 65.4    | -17.5% | **1.21x**
EqualStringSubstring                    | 20.781  | 17.472  | -15.9% | **1.19x**
EqualSubstringString                    | 20.552  | 17.407  | -15.3% | **1.18x**
LessSubstringSubstringGenericComparable | 20.67   | 17.75   | -14.1% | **1.16x**
EqualSubstringSubstring                 | 20.656  | 17.75   | -14.1% | **1.16x**
EqualSubstringSubstringGenericEquatable | 20.656  | 17.752  | -14.1% | **1.16x**
LessSubstringSubstring                  | 20.635  | 17.75   | -14.0% | **1.16x**
InsertCharacterEndIndexNonASCII         | 22.935  | 20.72   | -9.7%  | **1.11x (?)**
InsertCharacterEndIndex                 | 61.611  | 56.949  | -7.6%  | **1.08x**
InsertCharacterTowardsEndIndex          | 76.724  | 71.462  | -6.9%  | **1.07x**

### Code size: -O

**Improvement** | **OLD** | **NEW** | **DELTA** | **RATIO**
:---        | ---: | ---: | ---:  | ---:   
AsyncTree.o | 4445 | 4113 | -7.5% | **1.08x**

### Performance (arm64): -Osize

**Regression**                          | **OLD** | **NEW** | **DELTA** | **RATIO**
:---                                    | ---:    | ---:    | ---:   | ---:     
IndexPath.Min                           | 131.643 | 145.538 | +10.6% | **0.90x (?)**
&nbsp; | | | | 
**Improvement**                         | **OLD** | **NEW** | **DELTA** | **RATIO**
LessSubstringSubstringGenericComparable | 20.354  | 17.55   | -13.8% | **1.16x**
EqualSubstringSubstringGenericEquatable | 20.344  | 17.556  | -13.7% | **1.16x**
EqualSubstringString                    | 20.208  | 17.491  | -13.4% | **1.16x**
EqualStringSubstring                    | 20.137  | 17.446  | -13.4% | **1.15x**
LessSubstringSubstring                  | 20.25   | 17.574  | -13.2% | **1.15x**
EqualSubstringSubstring                 | 20.25   | 17.685  | -12.7% | **1.15x**
RemoveWhereFilterString                 | 103.636 | 93.8    | -9.5%  | **1.10x**
FindString.Rec3.Substring               | 58.0    | 53.31   | -8.1%  | **1.09x**
ObjectiveCBridgeToNSString              | 166.1   | 153.182 | -7.8%  | **1.08x (?)**
InsertCharacterEndIndex                 | 64.118  | 59.2    | -7.7%  | **1.08x**
FindString.Rec3.String                  | 59.692  | 55.256  | -7.4%  | **1.08x (?)**
InsertCharacterEndIndexNonASCII         | 24.14   | 22.385  | -7.3%  | **1.08x (?)**

### Code size: -Osize

**Improvement**   | **OLD** | **NEW** | **DELTA** | **RATIO**
:---              | ---: | ---: | ---:   | ---:   
AsyncTree.o       | 4413 | 3881 | -12.1% | **1.14x**
FindStringNaive.o | 4969 | 4917 | -1.0%  | **1.01x**

### Performance (arm64): -Onone

**Regression**                           | **OLD**  | **NEW** | **DELTA** | **RATIO**
:---                                     | ---:     | ---:    | ---:   | ---:     
ArrayAppendGenericStructs                | 1041.818 | 1195.0  | +14.7% | **0.87x (?)**
&nbsp; | | | | 
**Improvement**                          | **OLD**  | **NEW** | **DELTA** | **RATIO**
FindString.Loop1.Substring               | 326.857  | 194.25  | -40.6% | **1.68x**
FindString.Rec3.Substring                | 251.556  | 201.091 | -20.1% | **1.25x**
FindString.Rec3.String                   | 256.0    | 208.273 | -18.6% | **1.23x**
SIMDReduce.Int8                          | 6035.0   | 4982.0  | -17.4% | **1.21x**
FindString.Loop1.Array                   | 52052.0  | 43433.0 | -16.6% | **1.20x**
CSVParsing.UTF8                          | 198.273  | 169.357 | -14.6% | **1.17x**
CSVParsing.UTF16                         | 183.833  | 158.0   | -14.1% | **1.16x**
EqualSubstringSubstringGenericEquatable  | 22.43    | 19.55   | -12.8% | **1.15x**
ConvertFloatingPoint.MockFloat64Exactly2 | 293.25   | 256.222 | -12.6% | **1.14x**
RawBuffer.1000.findFirst                 | 46398.0  | 40669.0 | -12.3% | **1.14x**
LessSubstringSubstring                   | 23.187   | 20.397  | -12.0% | **1.14x**
LessSubstringSubstringGenericComparable  | 22.205   | 19.542  | -12.0% | **1.14x**
EqualSubstringString                     | 23.65    | 20.854  | -11.8% | **1.13x**
CSVParsing.Char                          | 232.2    | 205.5   | -11.5% | **1.13x**
FindString.Rec3.Array                    | 4168.0   | 3696.0  | -11.3% | **1.13x**
RawBuffer.1000.findLast                  | 50701.0  | 44961.0 | -11.3% | **1.13x**
EqualStringSubstring                     | 23.308   | 20.723  | -11.1% | **1.12x**
EqualSubstringSubstring                  | 22.688   | 20.261  | -10.7% | **1.12x**
RemoveWhereMoveInts                      | 807.5    | 722.333 | -10.5% | **1.12x**
RawBuffer.128.findLast                   | 7012.0   | 6281.0  | -10.4% | **1.12x**
CSVParsing.Scalar                        | 239.556  | 215.667 | -10.0% | **1.11x**
RawBuffer.39.findFirst                   | 2356.0   | 2123.0  | -9.9%  | **1.11x**
RawBuffer.7.findLast                     | 1017.5   | 920.0   | -9.6%  | **1.11x (?)**
RemoveWhereMoveStrings                   | 991.5    | 904.0   | -8.8%  | **1.10x (?)**
RawBuffer.39.findLast                    | 2616.0   | 2387.0  | -8.8%  | **1.10x**
RemoveWhereSwapInts                      | 1490.0   | 1370.0  | -8.1%  | **1.09x (?)**
ConvertFloatingPoint.MockFloat64ToDouble | 544.5    | 502.0   | -7.8%  | **1.08x**
RemoveWhereSwapStrings                   | 1771.0   | 1639.0  | -7.5%  | **1.08x (?)**

### Code size: -swiftlibs
```

**Review by jckarter — APPROVED** [review]

**Pull request merged**
