### PR TITLE
[IRGen] Distributed: Destroy loaded arguments after the call

### LINKED ISSUE #65853: Remote target (for distributed actor) arguments are not properly deinitialized
Remote target arguments reconstructed on the remote side of the distributed actor are not properly deinitialised.
If the remote target argument is a struct with some class instance references then those class instances are never released, which cause a memory leak.

We implemented minimised [test](https://github.com/ordo-one/external-reproducers/tree/main/swift/distributed-system-leak)
It perform a remote call on the distributed actor with a struct argument having a reference to the ClassValue instance.
Can find the ClassValue instance initialized twice (first time on the caller side, second time on the remote side), but reinitialised only once (on the caller side):
```
git clone https://github.com/ordo-one/external-reproducers.git
Cloning into 'external-reproducers'...
remote: Enumerating objects: 135, done.
remote: Counting objects: 100% (135/135), done.
remote: Compressing objects: 100% (88/88), done.
remote: Total 135 (delta 49), reused 91 (delta 23), pack-reused 0
Receiving objects: 100% (135/135), 27.13 KiB | 524.00 KiB/s, done.
Resolving deltas: 100% (49/49), done.
aaa % cd external-reproducers/swift/distributed-system-leak 
distributed-system-leak % swift test
Building for debugging...
[5/5] Linking DistributedSystemPackageTests
Build complete! (7.65s)
Test Suite 'All tests' started at 2023-05-11 12:45:03.890
Test Suite 'DistributedSystemPackageTests.xctest' started at 2023-05-11 12:45:03.891
Test Suite 'DistributedSystemTests' started at 2023-05-11 12:45:03.891
Test Case '-[DistributedSystemTests.DistributedSystemTests test1]' started.
Test Case '-[DistributedSystemTests.DistributedSystemTests test1]' passed (0.002 seconds).
Test Suite 'DistributedSystemTests' passed at 2023-05-11 12:45:03.893.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.002 (0.002) seconds
Test Suite 'DistributedSystemPackageTests.xctest' passed at 2023-05-11 12:45:03.893.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.002 (0.002) seconds
Test Suite 'All tests' passed at 2023-05-11 12:45:03.893.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.002 (0.003) seconds
assign<TestActor>: 1
actorReady<TestActor>: 1
resolve<TestActor>
init: 0x0000600002a301d0
recordArgument
remoteCallVoid
init: 0x0000600002a301f0
value=100
deinit: 0x0000600002a301d0
distributed-system-leak % 
```

We would expect the second ClassValue instance constructed on the remote side would be deinitialised, thus the output would also had a line
```
deinit: 0x0000600002a301f0
```

**Environment**
- Swift compiler version info
```
distributed-system-leak % swift --version
swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: arm64-apple-macosx13.0
```
- Xcode version info 
- Deployment target:
```
distributed-system-leak % uname -a
Darwin mbpro.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 arm64
```

### PR DESCRIPTION
**Pull request by xedin**
Arguments that have been loaded due to underlying method conversion
have to be destroyed after the call otherwise they are going to leak.

Resolves: https://github.com/apple/swift/issues/65853
Resolves: rdar://109207043

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@ktoso I added IRGen test because I couldn't figure out why deinit is not printed in lit environment.

**Comment by xedin** [comment]
Looks like Linux doesn't like parameters with archetypes, although it works just fine on macOS and simulators, here is the assert it's crashing with:

```
swift-frontend: /home/build-user/swift/lib/IRGen/GenArchetype.cpp:77: swift::irgen::MetadataResponse swift::irgen::emitArchetypeTypeMetadataRef(swift::irgen::IRGenFunction &, swift::CanArchetypeType, swift::irgen::DynamicMetadataRequest): Assertion `archetype->getParent() && "Not a nested archetype"' failed.
 #8 0x0000000000b4de73 swift::irgen::emitArchetypeTypeMetadataRef(swift::irgen::IRGenFunction&, swift::CanTypeWrapper<swift::ArchetypeType>, swift::irgen::DynamicMetadataRequest) (/home/build-user/build/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0xb4de73)
 #9 0x0000000000b0d11f swift::CanTypeVisitor<(anonymous namespace)::EmitTypeMetadataRef, swift::irgen::MetadataResponse, swift::irgen::DynamicMetadataRequest>::visit(swift::CanType, swift::irgen::DynamicMetadataRequest) MetadataRequest.cpp:0:0
#10 0x0000000000b0954a swift::irgen::IRGenFunction::emitTypeMetadataRef(swift::CanType, swift::irgen::DynamicMetadataRequest) (/home/build-user/build/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0xb0954a)
#11 0x0000000000c8e7ae swift::irgen::emitGenericRequirementFromSubstitutions(swift::irgen::IRGenFunction&, swift::GenericRequirement, swift::MetadataState, swift::SubstitutionMap, bool) (/home/build-user/build/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0xc8e7ae)
#12 0x0000000000b1222d swift::irgen::GenericArguments::collect(swift::irgen::IRGenFunction&, swift::SubstitutionMap) crtstuff.c:0:0
#13 0x0000000000b119f6 emitNominalMetadataRef(swift::irgen::IRGenFunction&, swift::NominalTypeDecl*, swift::CanType, swift::irgen::DynamicMetadataRequest) MetadataRequest.cpp:0:0
#14 0x0000000000b0d289 swift::CanTypeVisitor<(anonymous namespace)::EmitTypeMetadataRef, swift::irgen::MetadataResponse, swift::irgen::DynamicMetadataRequest>::visit(swift::CanType, swift::irgen::DynamicMetadataRequest) MetadataRequest.cpp:0:0
#15 0x0000000000b0954a swift::irgen::IRGenFunction::emitTypeMetadataRef(swift::CanType, swift::irgen::DynamicMetadataRequest) (/home/build-user/build/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0xb0954a)
#16 0x0000000000b0a074 swift::irgen::IRGenFunction::emitTypeMetadataRefForLayout(swift::SILType, swift::irgen::DynamicMetadataRequest) (/home/build-user/build/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0xb0a074)
#17 0x0000000000c51446 swift::irgen::IRGenFunction::emitValueWitnessTableRef(swift::SILType, swift::irgen::DynamicMetadataRequest, llvm::Value**) (/home/build-user/build/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0xc51446)
#18 0x0000000000c51370 swift::irgen::IRGenFunction::emitValueWitnessTableRef(swift::SILType, llvm::Value**) (/home/build-user/build/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0xc51370)
#19 0x0000000000c70ffa swift::irgen::IRGenFunction::emitValueWitnessFunctionRef(swift::SILType, llvm::Value*&, swift::irgen::ValueWitness) (/home/build-user/build/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0xc70ffa)
#20 0x0000000000c7446a swift::irgen::emitDestroyCall(swift::irgen::IRGenFunction&, swift::SILType, swift::irgen::Address) (/home/build-user/build/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0xc7446a)
#21 0x0000000000d3f99a swift::irgen::TypeInfo::callOutlinedDestroy(swift::irgen::IRGenFunction&, swift::irgen::Address, swift::SILType) const (/home/build-user/build/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0xd3f99a)
#22 0x0000000000cb7f0d swift::irgen::RecordTypeInfoImpl<(anonymous namespace)::LoadableStructTypeInfo, swift::irgen::LoadableTypeInfo, (anonymous namespace)::StructFieldInfo, true>::destroy(swift::irgen::IRGenFunction&, swift::irgen::Address, swift::SILType, bool) const GenStruct.cpp:0:0
#23 0x0000000000d5c5f2 (anonymous namespace)::DistributedAccessor::emitReturn(llvm::Value*) GenDistributed.cpp:0:0
#24 0x0000000000d5aedf (anonymous namespace)::DistributedAccessor::emit() GenDistributed.cpp:0:0

```

**Review by ktoso — COMMENTED** [review]
This looks great, thanks -- I'll see if I can figure out what linux doesn't like there

**Comment by xedin** [comment]
@ktoso I can XFAIL these tests on Linux and land this if you'd like?

**Comment by ktoso** [comment]
Maybe that's a good idea to ensure we're on time in apple platform releases and continue fixing on Linux. 

I'll do that

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Comment by xedin** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
Thanks a lot LGTM!

**Comment by ktoso** [comment]
I prepared a cherry pick over here https://github.com/apple/swift/pull/65941

**Pull request merged**
