### PR TITLE
use swift-collections 1.1.3 when appropriate

### PR DESCRIPTION
**Pull request by glessard**
Update the swift-collections tag used for toolchain builds to 1.1.3.

### CODE REVIEW

**Comment by glessard** [comment]
@swift-ci please smoke test

**Comment by glessard** [comment]
@swift-ci please build toolchain linux platform

**Comment by Azoy** [comment]
https://github.com/swiftlang/swift/pull/76101 might've beat you

**Comment by glessard** [comment]
Oh, wow. They were jumping the gun then, but whatever. It's time now.

**Comment by glessard** [comment]
Closed in favor of https://github.com/swiftlang/swift/pull/76101

**Pull request closed without merging**
