### PR TITLE
Merge the IRGen requests

### PR DESCRIPTION
**Pull request by hamishknight**
Similar to SILGen, merge `IRGenSourceFileRequest` and `IRGenWholeModuleRequest` into a single `IRGenRequest`.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test macOS

**Review by CodaFi — APPROVED** [review]
Very cool

**Comment by hamishknight** [comment]
@swift-ci please smoke test Linux

**Pull request merged**
