### PR TITLE
[cmake] Prepare for stage2 bootstrap swift build

### PR DESCRIPTION
**Pull request by gottesmm**
This PR consists of two small cmake changes that prepare the way for the stage 2 bootstrap swift build.

1. The first ensures that we search the passed in toolchain's path before looking in the SDK. This is important since when we perform a stage2 build, we pass in the stage1's installed artifacts as the SDK. At that point we have not split the just built toolchain libraries from the set of just built SDK libraries. This causes us to link against the just built compatibility libraries if they are built causing weird build errors.
2. The second one changes the stdlib build's swiftc variable to respect SWIFT_BUILD_RUNTIME_WITH_HOST_COMPILER. Today, we always set it to `${SWIFT_NATIVE_SWIFT_TOOLS_PATH}/swift`. This is implemented by checking if SWIFT_NATIVE_SWIFT_TOOLS_PATH is not set and if so setting the variable to the just built swift directory so that the stdlib uses the just built swift binary directory. This /does/ work when SWIFT_BUILD_RUNTIME_WITH_HOST_COMPILER is set to true but just incidentally since in the past we have always assumed that SWIFT_BUILD_RUNTIME_WITH_HOST_COMPILER meant that SWIFT_NATIVE_SWIFT_TOOLS_PATH is actually set by the user. Instead, in this commit I am changing the cmake to set swiftc based off of CMAKE_Swift_COMPILER if SWIFT_NATIVE_SWIFT_TOOLS_PATH was not initially set. Hopefully we eventually eliminate these external swift tools path in favor of more idiomatic CMake constructs.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by buttaface** [comment]
Btw, do you hit SR-14796 if you try to build the standalone stdlib like this with an official prebuilt trunk or 5.5 snapshot build for linux? That may affect people trying to use this pull with a prebuilt snapshot toolchain.

**Comment by drexin** [comment]
@swift-ci test linux

**Comment by drexin** [comment]
@swift-ci test windows

**Review by drexin — APPROVED** [review]
LGTM

**Comment by gottesmm** [comment]
@buttaface I haven't hit anything.

**Comment by davezarzycki** [comment]
Hi @gottesmm -- This broke my "unified build" setup. The problem seems to be that I have `SWIFT_BUILD_RUNTIME_WITH_HOST_COMPILER` set to true but `CMAKE_Swift_COMPILER` is not set, which later breaks the setting of `swift_compiler_tool`. We've talked about these changes in the past. Should I let my scripts find the installed copy of Swift now? If so, then it seems like we ought to tune CMake to detect this bad configuration, no?

**Comment by gottesmm** [comment]
@davezarzycki were all of your issues fixed by that PR?

**Comment by davezarzycki** [comment]
Yes, although now I probably won't use `SWIFT_BUILD_RUNTIME_WITH_HOST_COMPILER` as often now because sometimes I do what the stdlib to be built with the just-built `swift`. Thanks for checking.

**Pull request merged**
