### PR TITLE
[5.1] Code-completion, indexing, cursor-info, etc. for KeyPath dynamic member lookup

### PR DESCRIPTION
**Pull request by benlangmuir**
Cherry-pick https://github.com/apple/swift/pull/24072
Reviewed by: @rintaro @nathawes 

---

Add support for code-completion looking up keypath dynamic members, and cursor-info/indexing walking the underlying decls.

rdar://49028783
rdar://49028895
rdar://49029126

### CODE REVIEW

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
Linux failure is while building Foundation:

```
swift-corelibs-foundation/Foundation/NSError.swift:919:29: error: use of undeclared type 'POSIXErrorCode'
     public typealias Code = POSIXErrorCode
                             ^~~~~~~~~~~~~~
```

**Comment by benlangmuir** [comment]
https://github.com/apple/swift/pull/24108 should fix the Linux failure

**Comment by benlangmuir** [comment]
@swift-ci please test Linux

**Comment by rintaro** [comment]
@akyrtzi Failure is unrelated (Foundation test).

**Pull request merged**
