### PR TITLE
[5.7][SE-0349] Implementation for unaligned loads from raw memory

### PR DESCRIPTION
**Pull request by glessard**
Implementation for SE-0349, cherry-picked from https://github.com/apple/swift/pull/41033

### CODE REVIEW

**Comment by glessard** [comment]
@swift-ci please test

**Comment by glessard** [comment]
@swift-ci please test

**Comment by glessard** [comment]
@swift-ci please test

**Comment by glessard** [comment]
@swift-ci please test

**Comment by glessard** [comment]
Force-pushed to resolve changelog conflict!

**Comment by glessard** [comment]
@swift-ci please test

**Comment by glessard** [comment]
@swift-ci please test

**Review by stephentyrone — APPROVED** [review]

**Pull request merged**
