### PR TITLE
Add support for dynamic replacement of didSet/willSet

### PR DESCRIPTION
**Pull request by aschwaighofer**
The observer in a dynamic replacement of variables with a observer will
provide the dynamic replacement for the original.

var original : Int = 0 {
  didSet {
    print("original")
  }
}

@_dynamicReplacement(for: original)
var replacement : Int = 0 {
  didSet {
    print("replacement")
  }
}

rdar://48518788

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
Huh. Can I ask why this needed extra attention? I would have expected it to just work by dynamically replacing the setter.

**Comment by aschwaighofer** [comment]
> Huh. Can I ask why this needed extra attention? I would have expected it to just work by dynamically replacing the setter.

The setter references the member ref (load x/replacement.storage) and (non static) properties in extensions can have storage.
```
extension Stored {
   @_dynamicReplacement(for: i)
   var _replacement_i: Int {
     didSet {
       print("Stored.i.didSet from \(oldValue) to \(i) replacement")
     }
   }
```

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Pull request merged**
