### PR TITLE
[Utils] Handle unicode characters in backtrace-check

### PR DESCRIPTION
**Pull request by JDevlieghere**
rdar://63666780

### CODE REVIEW

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci please test macos

**Comment by JDevlieghere** [comment]
@swift-ci please test macos

**Review by compnerd — APPROVED** [review]
Thanks for making this python 2 compatible!

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Review by vedantk — APPROVED** [review]
Lgtm, thanks. There's extra context for this change in the discussion here: https://reviews.llvm.org/D79645

**Pull request merged**
