### PR TITLE
[test] Disable a flaky test: SwiftSyntax/ParserFile. rdar://36740859

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test and merge

**Comment by rintaro** [comment]
After cherry-picking this to `swift-5.0-branch`, could you revert this in the `master`?
We are waiting for a failure in `master` bots. https://github.com/apple/swift/pull/14056

**Comment by jrose-apple** [comment]
I asked in Radar for this, since the bots are not in great shape right now. Once everything goes blue again (excepting possibly the LLDB bots) then maybe, but for now please leave the test disabled.

**Comment by rintaro** [comment]
Ah, my bad we've already got a failure in the master.
Then I'm going to revert #14056 now. Thanks!

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Pull request merged**
