### PR TITLE
[sil-combine] Fix optimization of COWBufferRead for ownership

### PR DESCRIPTION
**Pull request by gottesmm**
Got to use the interior pointer functionality to simplify the algorithm/make it safer.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by eeckstein** [comment]
@gottesmm post-commit review: Please also check in your tests that the builtin can be removed completely.
That's the point of the builtin. In general, it should be removed completely.

**Comment by gottesmm** [comment]
Ok. I will fix. Thanks.

**Comment by gottesmm** [comment]
@eeckstein https://github.com/apple/swift/pull/35745

**Pull request merged**
