### PR TITLE
Revert `static-executable-args.lnk` changes 

### PR DESCRIPTION
**Pull request by MaxDesiatov**
Reverting for now due to this failure https://ci.swift.org/job/oss-swift-test-stdlib-with-toolchain-minimal/4880/:

```
CMake Error at stdlib/public/runtime/CMakeLists.txt:133 (add_dependencies):
  add_dependencies called with incorrect number of arguments
```

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci test and merge

**Comment by MaxDesiatov** [comment]
@swift-ci build toolchain

**Comment by gottesmm** [comment]
I am going to force merge this. I think this is blocking normal PR testing: https://ci.swift.org/job/oss-swift-pr-test-macoss/2432/console.

**Comment by gottesmm** [comment]
Actually, looks like the status bot also runs the minimal stdlib build as well.

**Comment by gottesmm** [comment]
After talking with @kubamracek it was confirmed to me that normal testing is being blocked. Merging!

**Comment by kateinoigakukun** [comment]
Oops, very sorry for this breakage 🙇‍♂️

**Pull request merged**
