### PR TITLE
[stdlib] Internalize _Buffer32 and _Buffer72

### PR DESCRIPTION
**Pull request by moiseev**
Part 3 of <rdar://problem/45746339>

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
@swift-ci Please benchmark

**Review by milseman — APPROVED** [review]
I strongly approve of this change, even with a benchmark regression.

**Comment by milseman** [comment]
(@stephentyrone  is planning to speed this all up anyways)

**Comment by moiseev** [comment]
@swift-ci Please smoke test Linux platform

**Pull request merged**
