### PR TITLE
test: correct typoed check name

### PR DESCRIPTION
**Pull request by compnerd**
Correct the name of the substitution.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @arnold

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by jrose-apple** [comment]
@aschwaighofer, surely?

**Comment by compnerd** [comment]
I blame the silly autocomplete from the browser.  I did indeed mean @aschwaighofer

**Pull request merged**
