### PR TITLE
[Concurrency] Key paths and global actors

### LINKED ISSUE #66830: KeyPath discards global actor
**Description**

KeyPath discards global actors, and allows access to actor-isolated properties from outside the isolated actor.

**Steps to reproduce**

```swift
import Foundation

@MainActor
class C {
    var property = false {
        willSet {
            precondition(Thread.isMainThread)
        }
    }
}

let c = C()
await Task.detached {
    c[keyPath: \.property] = true
}.value
```
```
 swiftc -strict-concurrency=complete KeyPathMainActor.swift
 ./KeyPathMainActor                                        
KeyPathMainActor/KeyPathMainActor.swift:7: Precondition failed
zsh: trace trap  ./KeyPathMainActor
```

**Expected behavior**

This probably shouldn't compile. It definitely shouldn't attempt to set the property off the main actor.

**Environment**

swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0

### PR DESCRIPTION
**Pull request by xedin**
- InferSendableFromCaptures: If key path references a global actor isolated member mark it as non-Sendable
- Diagnose use of the global actor isolated members if the access and declaration
  concurrency domains differ. (This is a warning until Swift 6).

Resolves: https://github.com/apple/swift/issues/66830
Resolves: rdar://117538832

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test

**Review by hborla — APPROVED** [review]
Thank you!

**Comment by xedin** [comment]
@swift-ci please test

**Pull request merged**
