### PR TITLE
Request-ify accessor synthesis

### PR DESCRIPTION
**Pull request by slavapestov**
Builds on https://github.com/apple/swift/pull/26356. Not quite as exciting as it sounds -- while the synthesis itself is now encapsulated in a request and some other stuff has been refactored, we still eagerly trigger synthesis in the same places as before.

This is because we have calls to methods like getAccessor(), hasAccessor() and getAllAccessors() all over the place. These are not really sound in a request evaluator world, because the set of accessors synthesized so far is not reliably predictable.

The next step is to refactor usages of the problematic methods to use new operations that distinguish between parsed and synthesized accessors, automatically triggering synthesis for the latter when needed.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test Linux

**Comment by slavapestov** [comment]
@swift-ci Please clean test Linux

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Review by rjmccall — COMMENTED** [review]
LGTM

**Pull request merged**
