### PR TITLE
[Python3] Fix test failures in update_checkout

### PR DESCRIPTION
**Pull request by tbkka**
Make the update_checkout tests pass for both Python 2 and Python 3.

### CODE REVIEW

**Comment by tbkka** [comment]
@swift-ci Please test

**Comment by tbkka** [comment]
@swift-ci Please test

**Comment by tbkka** [comment]
Both failures look entirely unrelated.  Let's try again...

**Comment by tbkka** [comment]
@swift-ci Please test

**Review by compnerd — APPROVED** [review]

**Comment by tbkka** [comment]
@swift-ci Please test macOS

**Comment by gottesmm** [comment]
Thanks!

**Pull request merged**
