### PR TITLE
Uniquely serialize conformances and make room for more protocol codes

### PR DESCRIPTION
**Pull request by rjmccall**
Schedule conformance emissions in basically the same way we do for types and declarations.  This means that we should emit them uniquely in the module file instead of redundantly at every use. Normal conformances were already unique, but uses of them used to require a separate reference record to be emitted. I was really hoping that this would produce substantially smaller module files overall, especially for modules that heavily use generics, but the effect seems pretty muted: barely 6KB in `Swift.swiftmodule`. Maybe we're paying for null references / zero lengths in a bunch of places we didn't have to before.

It also means that we can remove all the unfortunate code to support using different abbrev codes for them in different bitcode blocks, which simplifies changes to the serialization system.  Overall, it seems like a win.

Requirement lists are now emitted inline in the records that need them instead of as trailing records.  I think this will improve space usage, but mostly it assists in eliminating the problem where abbrev codes are shared between blocks.

I've also moved things around to create space for more record codes.  Previously we were assuming that codes were always 8 bits.  This part fixes rdar://89313942.

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please test

**Comment by rjmccall** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
Cool!

**Comment by rjmccall** [comment]
@swift-ci Please test Linux

**Pull request merged**
