### PR TITLE
[IRGen] Mask off metadata pack passed to DebugInfo

### PR DESCRIPTION
**Pull request by nate-chandler**
When a metadata pack is heap allocated, the pointer's LSB is set. But lldb is expecting a real pointer.  So mask it off.

Companion PR has a test: https://github.com/apple/llvm-project/pull/6961

rdar://110195273

### CODE REVIEW

**Comment by nate-chandler** [comment]
Please test with following pull request:
https://github.com/apple/llvm-project/pull/6961

@swift-ci Please test

**Comment by nate-chandler** [comment]
An alternative would be to handle the LSB on the lldb side.

**Comment by nate-chandler** [comment]
Please test with following pull request:
https://github.com/apple/llvm-project/pull/6961

@swift-ci Please test

**Comment by nate-chandler** [comment]
Please test with following pull request:
https://github.com/apple/llvm-project/pull/6961

@swift-ci Please test

**Review by aschwaighofer — APPROVED** [review]

**Pull request merged**
