### PR TITLE
[6.0][region-isolation] Tweaking diagnostics a little bit to match terminology we are using else where.

### PR DESCRIPTION
**Pull request by gottesmm**
Explanation: This PR contains small changes to the actual diagnostic text that we emit for region isolation. I am making the change to match evolved ways of talking about these errors.

- rdar://127580781

Original PRs:

- https://github.com/apple/swift/pull/73446
- https://github.com/apple/swift/pull/73459
- #73471

Risk: Low. Just tweaking diagnostics.
Testing: Updated /all/ of the region isolation tests to reflect the diagnostic change.
Reviewer: N/A

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test windows platform

**Comment by gottesmm** [comment]
This successfully passed all tests, but I by mistake included an unnecessary commit.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
I was asked to tweak the diagnostics a little bit further.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test linux platform

**Comment by gottesmm** [comment]
@swift-ci test linux platform

**Comment by gottesmm** [comment]
@swift-ci test

**Review by hborla — APPROVED** [review]

**Pull request merged**
