### PR TITLE
argparse for omit-needless-words.py

### PR DESCRIPTION
**Pull request by cbrentharris**
Using the argparse module for omit-needless-words.py, so that the code takes 
advantage of python's builtin library for parsing arguments, and reducing the length of the code. 
Also wrapping everything within a main method that is only called if the program is the main one being run.

### CODE REVIEW

**Comment by jrose-apple** [comment]
Per the "[Incremental Development](https://swift.org/contributing/#incremental-development)" guidelines on the Contributing page on the Swift site, I would prefer that the two unrelated changes (adopting `argparse`, and wrapping everything in a `main` function) be separated into two commits. However, Doug's the main author of this file, so it's his call.

**Comment by cbrentharris** [comment]
Sure no problem! @DougGregor let me know what you prefer.

**Comment by DougGregor** [comment]
I caused a conflict before seeing this pull request (sorry). Can you update and resubmit? This is a great change.

**Comment by jrose-apple** [comment]
This does mean a minimum Python requirement of 2.7, by the way. We may already require that, though. (We mostly haven't kept track of what we use as long as it works on OS X.)

**Comment by cbrentharris** [comment]
@DougGregor ok rebased and merge conflicts fixed. @jrose-apple Yes argparse is new in 2.7, but I believe many modules in the utils directory are using it.

**Pull request merged**
