### PR TITLE
[5.9] [CS] Allow ExprPatterns to be type-checked in the solver

### PR DESCRIPTION
**Pull request by hamishknight**
*5.9 cherry-pick of #64280 + #65744 + #65651 + #64566*

- Explanation: Moves ExprPattern type-checking into the constraint system, fixing a number of issues with the old implementation, including a some crashers, and fixes code completion in nested positions within an ExprPattern.
- Scope: Affects ExprPattern type-checking
- Radars: rdar://104954155, rdar://105782480, rdar://106598067, rdar://107709341, rdar://107420031, rdar://107724970
- Risk: Medium, this is certainly a non-trivial change, but it has been extensively tested, and fixes a number of issues.
- Testing: Added tests to test suite
- Reviewer: Pavel Yaskevich

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Review by airspeedswift — APPROVED** [review]

**Pull request merged**
