### PR TITLE
[AutoDiff] Attempt #1 at cross-import overlay merge

### PR DESCRIPTION
**Pull request by philipturner**
THIS IS STILL A DRAFT; PLEASE IGNORE THIS COMMENT'S CONTENT

I finished @rxwei's commit to add cross-import overlays for Darwin/Glibc/WASILibc/CRT + `_Differentiation`. Actual activation of the cross-import overlay feature is blocked by a compile failure in `SwiftCompiler/Sources/ExperimentalRegex`. You can reproduce this by un-commenting out the following in `lib/AST/Module.app` (circa line 2635):
```
if (isDifferentiableProgrammingEnabled(*this))
  return true;
```

As a temporary workaround, you must explicitly import the overlay modules. Subsequently, you do not need to pass `-Xfrontend` `-enable-cross-import-overlays` into the compiler. Once the build failure is fixed, the `TODO(philipturner)` in `test/AutoDiff/stdlib/tgmath_derivatives.swift.gyb` should be attempted. 

Relevant hyperlinks:
- https://github.com/rxwei/swift/commit/74f11f84f36c8ef369dc9f0d09952150da95047d
- [NNNN-cross-import-overlays.md](https://gist.github.com/beccadax/8f35216340e829efa5e9c1fc090fda09)

Resolves SR-15584 (partially).

### CODE REVIEW

**Comment by philipturner** [comment]
@rxwei I'm still drafting this PR, but the solution you mentioned [here](https://github.com/apple/swift/pull/40991#issuecomment-1020722568) didn't fix anything. I still have a ton of useless commits in this PR. I branched the new `patch-20` off of `main` after hard-resetting. Maybe it's that I need to purge and reset my local files, or something wierd with deleting and then re-creating `patch-20`.

If I find no solution to this problem, how alarming will it be to future pull requests (in case you forget to squash and merge again, like with `DifferentiableProgrammingImplementation.md`)?

**Comment by rxwei** [comment]
> I'm still drafting this PR, but the solution you mentioned here didn't fix anything.

Well, pretty sure it's done wrong. You didn't reset the branch to upstream main before applying new changes. That's why you still have those merge commits from main.

> how alarming will it be to future pull requests

It is not a good practice. We normally expect developers to squash their commits.

**Comment by philipturner** [comment]
I'll try again with another branch.

**Comment by rxwei** [comment]
Ok. Please verify your new branch has 1 new commit before opening a new PR.

**Pull request closed without merging**
