### PR TITLE
Clean up SIL witness table deserialization

### PR DESCRIPTION
**Pull request by slavapestov**
`SILModule::lookUpWitnessTable()` had a weird behavior where it would only deserialize a witness table if there was already a declaration for it. As a result, various callers had to ensure that the witness table declaration exists. We would also pre-declare any witness tables referenced from SIL instructions when they were created.

None of this was really necessary; instead, `lookUpWitnessTable()` should just create the declaration if it was asked to deserialize.

This is a nice cleanup in itself, but is mostly meant to support the constexpr work by @marcrasi and @ravikandhadai.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
The change is pretty small but I split it up into multiple  commits and tested each one since it's all a bit subtle. I think the end result is much easier to reason about though.

**Review by jckarter — APPROVED** [review]
LGTM

**Review by ravikandhadai — APPROVED** [review]

**Comment by slavapestov** [comment]
@swift-ci Please benchmark

**Pull request merged**
