### PR TITLE
[test] Float80 only exists on some platforms.

### PR DESCRIPTION
**Pull request by huonw**
rdar://problem/40150393

### CODE REVIEW

**Comment by huonw** [comment]
@swift-ci please smoke test

**Comment by huonw** [comment]
@airspeedswift and/or @lorentey is this the recommended way to check for `Float80`?

**Comment by jrose-apple** [comment]
Or @stephentyrone?

**Comment by airspeedswift** [comment]
That's certainly how we're doing it in the main floating point tests: https://github.com/apple/swift/blob/master/test/stdlib/FloatingPoint.swift.gyb#L417

**Comment by huonw** [comment]
Thanks.

**Comment by stephentyrone** [comment]
Just to confirm, even though this is already merged: LGTM.

**Pull request merged**
