### PR TITLE
Enable availability attributes for associated types

### PR DESCRIPTION
**Pull request by DougGregor**
Allow `@available` on associated types, which can be introduced after the protocol was introduced. These work precisely how on expects, because all of the infrastructure for introducing associated types later on has been available for a while, with two small restrictions:

1. If one uses the primary associated type syntax (e.g., `P<A, B>`), then the primary associated types must also be available in the current context.
2. Adding a new associated type to a resilient protocol requires that associated type to have a default.

Fixes rdar://108409322 and rdar://117586830

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Review by tshortli — APPROVED** [review]
Thanks! This fixes rdar://108409322.

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Pull request merged**
