### PR TITLE
[5.9] Build private swift interface files from stdlib

### PR DESCRIPTION
**Pull request by edymtt**
Cherry-pick of #64587, #64878 -- these ensure we can consume SPI from swiftinterfaces alone when we are building the standard library with `skip-early-swiftdriver` in some build setups.

Risk: low -- this generates additional files that duplicate content already in the swiftmodules

Addresses rdar://108900952

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci please test

**Comment by edymtt** [comment]
@swift-ci please build toolchain

**Comment by etcwilde** [comment]
CC @xymus

**Review by xymus — APPROVED** [review]
It looks good, thanks!

**Review by najacque — APPROVED** [review]

**Pull request merged**
