### PR TITLE
SIL Optimizer: Allow casts between nil of unrelated Optional type to …

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please benchmark

**Comment by tkremenek** [comment]
Are we still considering this for Swift 2.2?  Benchmark failed.

**Comment by tkremenek** [comment]
Closing, per offline conversation.

**Comment by slavapestov** [comment]
We are not. I'll look into finishing this stuff in master soon though.

**Pull request closed without merging**
