### PR TITLE
[interop] add itanium ABI support for trapping on uncaught exceptions when making a foreign call

### PR DESCRIPTION
**Pull request by hyp**
Enabled when C++ interop is enabled, unless Clang args disable exceptions. Still needs MSVC eh support. I'm planning to add it in a follow-up after doing some refactorings in Clang.

### CODE REVIEW

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test linux platform

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test source compatibility

**Comment by hyp** [comment]
@swift-ci please test macOS

**Comment by hyp** [comment]
@swift-ci please test source compatibility

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test source compatibility

**Comment by hyp** [comment]
@swift-ci please test linux platform

**Comment by hyp** [comment]
@swift-ci please build toolchain

**Comment by hyp** [comment]
@swift-ci please test linux platform

**Comment by hyp** [comment]
the source compat failures are unrelated (https://github.com/apple/swift/issues/63869)

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test source compatibility

**Comment by buttaface** [comment]
@hyp, it appears [this broke a couple of these tests on the Android AArch64 CI](https://ci-external.swift.org/job/oss-swift-RA-linux-ubuntu-16.04-android-arm64/lastFailedBuild/console), do we just need to add `-Xcc -fignore-exceptions` for those Android tests too, like you did for macOS?

**Comment by hyp** [comment]
@buttaface yes, please add `-Xcc -fignore-exceptions` for these failing tests. That should fix them.

**Pull request merged**
