### PR TITLE
Add release version to manpage

### PR DESCRIPTION
**Pull request by ahti**
#### What's in this pull request?

This PR passes a value to the `--release` flag of pod2man. This value is shown on the bottom left of the manpage, and it is common to put project name and version there.

Passing a value also resolves an incompatibility with newer versions of pod2man, shipped on Arch Linux and Fedora for example.
#### Resolved bug number: ([SR-2099](https://bugs.swift.org/browse/SR-2099))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

A smoke test on macOS does the following:
1. Builds the compiler incrementally.
2. Builds the standard library only for macOS. Simulator standard libraries and
   device standard libraries are not built.
3. lldb is not built.
4. The test and validation-test targets are run only for macOS. The optimized
   version of these tests are not run.

A smoke test on Linux does the following:
1. Builds the compiler incrementally.
2. Builds the standard library incrementally.
3. lldb is built incrementally.
4. The swift test and validation-test targets are run. The optimized version of these
   tests are not run.
5. lldb is tested.

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by gottesmm** [comment]
Can you add a test that pod2man works. I do not care about the output. Just that it produces reasonable output (i.e. a smoke test).

**Comment by ahti** [comment]
Where should I add this test? If it is of any help, pod2man will already exit with a non-zero status and make the build fail when it encounters errors.

**Comment by gottesmm** [comment]
Basically here is why I brought this up: I do not think that most people ever build the manpages unless they are trying to package something. That means that issues like this lie unfixed if we people on new OSes and then people (like you) run into them (which is unfortunate).

Really, the incompatibility should have been caught immediately. Perhaps by cmake. That being said, I think this is a small enough change that it is probably not interesting.

On the other hand, from reading the manpage isn't this supposed to be --release=""?

**Comment by ahti** [comment]
Good catch with the quals. Both seem to work, but I'll update it with the documented way.

The manpages are built by default, unless the user explicitly disables them (setting `SWIFT_INCLUDE_DOCS` to false), so I think this will be caught easily. I have known about this since I first built swift on Arch Linux, only found the time to track down the corresponding issue and create a PR for it just now.

**Comment by gottesmm** [comment]
Ok. SGTM.

**Comment by gottesmm** [comment]
@swift-ci Please smoke test and merge

**Pull request merged**
