### PR TITLE
[5.1] Fix a data race on _swiftEmptyArrayStorage reported by TSan #21627

### PR DESCRIPTION
**Pull request by Catfish-Man**
Cherry picking to 5.1. May be too late, sorry about that if so!

Fixes rdar://problem/45738939

### CODE REVIEW

**Review by airspeedswift — APPROVED** [review]

**Comment by Catfish-Man** [comment]
@swift-ci please test and merge

**Comment by Catfish-Man** [comment]
@swift-ci please test and merge

**Comment by Catfish-Man** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by Catfish-Man** [comment]
PR testing should be fixed now

**Comment by Catfish-Man** [comment]
@swift-ci please test Linux platform

**Pull request merged**
