### PR TITLE
SILGen: Mark associated type conformances as "used".

### PR DESCRIPTION
**Pull request by jckarter**
We neglected to do this, so we would fail to emit protocol conformances synthesized from imported ObjC declarations in cases where that was the only apparent use of the conformance, such as SR-3739 and rdar://problem/30195308.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@slavapestov, does this look OK for Swift 3.1?

**Comment by slavapestov** [comment]
LGTM.

**Comment by DougGregor** [comment]
LGTM, FWIW

**Comment by jckarter** [comment]
OS X failure looks unrelated; it's failing in other PR builds too.

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test OS X

**Pull request merged**
