### PR TITLE
Driver: enable `-force-autolink-symbol` on Darwin as well

### PR DESCRIPTION
**Pull request by compnerd**
This further generalises the support to Darwin where MachO is the object
file format.  This environment does not support COMDAT, so use
`weak_odr` to ensure that the symbol is coalesced and preserved.

Thanks to John McCall for reminding me of the weak odr on MachO!

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @rjmccall

**Comment by compnerd** [comment]
CC: @jrose-apple - bleh, seems

**Comment by compnerd** [comment]
Hmm, functions cannot have common linkage.  I wonder what we were doing previously.

**Comment by jrose-apple** [comment]
I had a global int previously, I think.

**Comment by compnerd** [comment]
Yeah, the difference is that it is a function now, and that cannot be common, it has to be weak (`weak_odr` is proper as we want the instances coalesced).  I can't make it `linkonce_odr` as that can be dead stripped.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by jrose-apple** [comment]
You could make it not a function on non-COMDAT platforms.

**Comment by compnerd** [comment]
I really would rather that we kept the behaviour the same on all the platforms.  The symbol needs to be a function since you cannot do cross-module data symbol references, but you can  do cross-module function references (as that can be trampolined).  I believe that the symbol should be preserved here with the `llvm.compiler.used` annotation of the symbol reference.

**Comment by jrose-apple** [comment]
I don't think anyone else is doing linkonce_odr + external visibility, so that feels like a risky thing to rely on. If you want to keep the behavior the same on all platforms, we should go back to not using comdat.

**Comment by jrose-apple** [comment]
> since you cannot do cross-module data symbol references

…in COFF

**Comment by compnerd** [comment]
Um, I would be really surprised if linkonce_odr+external visibility would be unused in practice.  This is safe, the only concern is whether the symbol is dead stripped or not by the linker.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by rjmccall** [comment]
We don't want to use linkonce_odr + default visibility because that creates a non-hidden weak symbol, which is heavily frowned upon in the Darwin world.

The easiest solution is to just pick a file from the module that's required to emit this.

**Comment by compnerd** [comment]
Oh, I didn't realize that `linkonce_odr` would create a weak symbol.  Hmm, I believe that emitting the symbol strong has the problem that you end up with multiple definitions or you need to emit to a single file, which seems to cause problems with incremental builds?

**Comment by rjmccall** [comment]
Yes, `linkonce_odr` is basically `weak_odr` but dead-strippable when the declaration is unreferenced.

Jordan might know better what the problem with incremental builds is.  Maybe it's hard to agree on which file to emit the symbol in.  Adding or deleting a file to a build might cause issues with that except that they likely force recompilation of other files anyway.

It's certainly better to use a single code-generation pattern, but we already can't necessarily do so because of COMDATs, so if we need target-specific workarounds, so be it.

**Comment by jrose-apple** [comment]
> Jordan might know better what the problem with incremental builds is. Maybe it's hard to agree on which file to emit the symbol in. Adding or deleting a file to a build might cause issues with that except that they likely force recompilation of other files anyway.

Yeah, that's the problem. Specifically, adding a file does *not* force recompilation (and we got vehement requests for that during the Swift 2 days), so you could get duplicate symbols in that one rare case.

**Comment by rjmccall** [comment]
How is it valid for adding a file to not force recompilation?  Existing lookups are allowed to resolve to new declarations.

**Comment by jrose-apple** [comment]
We do do that. We only rebuild the files that change, then we check their dependency info to see if they could have affected other files. But "is the first file" isn't tracked in any way at the moment.

**Comment by rjmccall** [comment]
Okay.  So we *could* probably fix this that way if we had a need to, like if there was something more expensive to emit at the module level.

**Comment by jrose-apple** [comment]
Yeah. I *think* it'd even be as simple as adding a dummy "I am first" symbol to both the "provides" and "depends" sets of the first source file. That way, if anyone new "provides" it, the formerly-first file would get rebuilt, and no longer provide it itself.

But that said, the idea of special-casing the first file is *also* a hack. COMDAT / Common linkage is actually closer to the intent of this thing, and yet another option would be some kind of bonus object file. (But that only works if swiftc is also doing the linking.)

**Comment by compnerd** [comment]
At least in the case of building with CMake (3.15+) - the linker driver is swiftc!

**Comment by compnerd** [comment]
Hmm, sounds like we should try to serialise an indicator for the primary file in the module to the swiftmodule?

**Comment by jrose-apple** [comment]
> At least in the case of building with CMake (3.15+) - the linker driver is swiftc!

Yeah, but that's not the only interesting case. If you're in any build system that compiles and links in separate steps, you need to know there's an extra object file. (Though I guess there's already an extra object file for the wrapped module on non-Darwin.)

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
