### PR TITLE
Optional codegen improvements

### PR DESCRIPTION
**Pull request by jckarter**
Get rid of the transparent intrinsics in the stdlib for optional-to-bool conversion and force-unwrapping optionals so we can generate simpler, non-memory code for these common operations.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test and merge

**Comment by gottesmm** [comment]
Are you sure there are no -Onone regressions here?

Michael

**Comment by jckarter** [comment]
I'd only expect improvements. This has the net effect of eliminating loads and stores from Onone code. We can revert if there are regressions.

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please benchmark

**Comment by rjmccall** [comment]
Awesome, Joe!

**Comment by jckarter** [comment]
@gottesmm Are the perf regressions on `ObjectiveCBridgeFromNSArrayAnyObject` and `TypeFlood` within normal variance, or do they look problematic to you? IIRC at least `TypeFlood` fluctuates quite a bit.

**Comment by jckarter** [comment]
@swift-ci Please benchmark

**Comment by jckarter** [comment]
Spoke with @gottesmm offline, these benchmark results look within expected variance. Starting a second run just to check though.

**Comment by lattner** [comment]
Nice!

**Pull request merged**
