### PR TITLE
Removed unused UnresolvedType::get

### PR DESCRIPTION
**Pull request by mxswd**
This is dead code.

### CODE REVIEW

**Comment by mxswd** [comment]
@jrose-apple

**Comment by jrose-apple** [comment]
Thanks.

@swift-ci Please smoke test and merge

**Comment by shahmishal** [comment]
retest macOS. 

@swift-ci Please smoke test macOS

**Comment by shahmishal** [comment]
Sorry, I mean Linux 

@swift-ci Please smoke test Linux

**Pull request merged**
