### PR TITLE
[CMake] Add SWIFT_STDLIB_SHORT_MANGLING_LOOKUPS to StandaloneOverlay

### PR DESCRIPTION
**Pull request by edymtt**
This will allow it to have a sensible default in configurations that use it.

Addresses rdar://85815655

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by edymtt** [comment]
@swift-ci please smoke test

**Review by kubamracek — APPROVED** [review]

**Comment by kubamracek** [comment]
As an immediate fix, LGTM.

Though we should really find a way to avoid this from happening in the future, either enforce StandaloneOverlay.cmake and stdlib/CMakeLists.txt being in sync, or including one from the other or something like that.

**Comment by edymtt** [comment]
Working on proper long term fix in #40610

**Pull request merged**
