### PR TITLE
@main: Attribute to add an entry point to a type.

### PR DESCRIPTION
**Pull request by nate-chandler**
Here a new attribute @main is added.  The type or extension that it is added to must have a static function `() -> Void` or `() throws -> Void` visible from the attribute.  If it does, that function will be called at process launch.  The same restrictions that apply to the existing `@UIApplicationMain` and `@NSApplicationMain` apply to the new attribute as well.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by benrimmington** [comment]
If you use `@main` without backticks (in comments or commit messages), [Vlad Vannov](https://github.com/main) may receive a notification!

**Comment by varungandhi-apple** [comment]
Do you think it would be useful to add a test case for the interaction of `@main` with `@available`? I think it should work out since you are not skipping type-checking, but just in case it doesn't for some reason.

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Pull request merged**
