### PR TITLE
[5.3] [semantic-arc-opts] Use all consuming uses instead of just destroying uses when validating if a LiveRange is alive in a scope.

### PR DESCRIPTION
**Pull request by gottesmm**
Just cherry-picking this fix.

rdar://63188362

----

Explanation: SemanticARCOpts is converting a legally leakable load [copy] from an access scope to a load_borrow in an harmless, incorrect way. Specifically to transform a load [copy] from an access_scope to a load_borrow, we need to validate that all uses of a load [copy] are within the access scope since load_borrows can only be used while the access_scope is valid. In the algorithm as written, we validate only that the destroy_value of the load [copy] are within that scope since all non-destroy uses will be earlier than such destroy_value. This is generally correct, except if our load [copy] is post-dominated by an unreachable. In such cases we may eliminate all destroy_value on the load [copy] since the program is going to end and we are going to leak the object. This can then cause us to ignore any non-destroy uses of the load [copy] outside of the access scope that would disqualify the load [copy] from being converted to a load_borrow. This change fixes the problem conservatively by just validating that /all/ uses of a load [copy] (rather than just destroy_value uses) are strictly within the access scope.
Scope: Fixes a miscompile. In terms of how likely this is in practice, I think it is not likely. That is because the optimizer is pretty aggressive about leaking objects on program exit. So given that we need to be post-dominated by unreachables, the base object is likely to be leaked rather than destroyed.
SR Issue: rdar://63188362
Risk: Low. I am only making the algorithm more conservative by adding all uses to a check instead of just the destroy_values.
Testing: Added a test case. Just run the compiler test suite.
Reviewer: @atrick

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Review by atrick — APPROVED** [review]
LGTM for 5.3

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
Just redoing the test since it has been a minute since I put this up.

**Comment by gottesmm** [comment]
The OS X failure was a Jenkins failure. And the Linux I think was one of those non-deterministic swiftpm ones:

```
Test Case 'WorkspaceTests.testTransitiveDependencySwitchWithSameIdentity' started at 2020-06-09 21:42:23.041
Exited with signal code 11
env SWIFTCI_USE_LOCAL_DEPS=1 SWIFTPM_MACOS_DEPLOYMENT_TARGET=10.15 LD_LIBRARY_PATH=/home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-release/5.3/buildbot_linux/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/bootstrap/lib:/home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-release/5.3/buildbot_linux/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/tsc/lib:/home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-release/5.3/buildbot_linux/llbuild-linux-x86_64/lib /home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-release/5.3/buildbot_linux/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/release/swift-test --enable-test-discovery --parallel --build-path /home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-release/5.3/buildbot_linux/swiftpm-linux-x86_64 --configuration release -Xlinker -rpath -Xlinker $ORIGIN/../lib/swift/linux
env SWIFTCI_USE_LOCAL_DEPS=1 SWIFTPM_MACOS_DEPLOYMENT_TARGET=10.15 LD_LIBRARY_PATH=/home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-release/5.3/buildbot_linux/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/bootstrap/lib:/home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-release/5.3/buildbot_linux/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/tsc/lib:/home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-release/5.3/buildbot_linux/llbuild-linux-x86_64/lib /home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-release/5.3/buildbot_linux/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/release/swift-test --enable-test-discovery --parallel --build-path /home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-release/5.3/buildbot_linux/swiftpm-linux-x86_64 --configuration release -Xlinker -rpath -Xlinker $ORIGIN/../lib/swift/linux
--- bootstrap: error: Command '['env', 'SWIFTCI_USE_LOCAL_DEPS=1', 'SWIFTPM_MACOS_DEPLOYMENT_TARGET=10.15', u'LD_LIBRARY_PATH=/home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-release/5.3/buildbot_linux/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/bootstrap/lib:/home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-release/5.3/buildbot_linux/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/tsc/lib:/home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-release/5.3/buildbot_linux/llbuild-linux-x86_64/lib', u'/home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-release/5.3/buildbot_linux/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/release/swift-test', '--enable-test-discovery', '--parallel', '--build-path', '/home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-release/5.3/buildbot_linux/swiftpm-linux-x86_64', '--configuration', 'release', '-Xlinker', '-rpath', '-Xlinker', u'$ORIGIN/../lib/swift/linux']' returned non-zero exit status 1
```

Going to retest

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
Going to wait for things to calm down on the CI

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci nominate

**Review by tkremenek — APPROVED** [review]

**Pull request merged**
