### PR TITLE
[swift-4.2-branch-06-11-2018] emit sigint for cancelled batch constituents

### PR DESCRIPTION
**Pull request by graydon**
swift-4.2-branch-06-11-2018 cherry-pick of #17167, #17228 and #17131 

- Explanation: Allow cancelling (via simulated SIGINT) batch-mode constituent jobs that were batched together with jobs that had errors. Swift side of eliminating the nonspecific error "compilation stopped by errors in other files", when a file has an error in batch-mode.
- Scope: The nonspecific error was being emitted for all files in a batch that did not contain an error, whenever some other file in the batch _did_ contain an error. This caused a lot of noise in issue and report navigator any time any file had an error.
- Risk: Low-ish. Only affects diagnostic reporting at the driver level, and only reverts an obnoxious artificial case and re-encodes it in a way that permits suppressing the situation altogether.
- Reviewed by: Jordan Rose, David Ungar.

rdar://41164520

### CODE REVIEW

**Comment by graydon** [comment]
@swift-ci please test

**Comment by graydon** [comment]
@swift-ci please nominate

**Comment by graydon** [comment]
@swift-ci please test OSX Platform

**Comment by graydon** [comment]
@swift-ci please test macos platform

**Comment by AnnaZaks** [comment]
@swift-ci please nominate

**Pull request merged**
