### PR TITLE
[benchmark] Add preliminary helper for measuring instructions executed.

### PR DESCRIPTION
**Pull request by graydon**
After my delight at discovering `proc_pid_rusage` / `rusage_info_v4` interface that allows you to inspect your process' PMC-measured count of executed instructions, I figured the compiler shouldn't have all the fun, so added a helper function here to the runtime benchmark harness as well.

The key point here is that the numbers it reports have _substantially_ lower noise than timers, and tend to be more stable between machines. So I think it's worth the effort to wire them up, get more precise reporting.

<strike>Implementation-wise: there's something amiss with the way the `proc_pid_rusage` symbol imports using `#include` within the module (see comment in patch -- I am a bit stumped)</strike>

[EDIT] I was a fool who forgot we're on a case-insensitive filesystem and LibProc.h == libproc.h, just threw clang importer into a loop. Renamed file, everything's fine.

I figure you're going to want to rearrange a bunch of stuff to treat these numbers in a useful way, so I just made a first cut here. Feel free to clone this change, close the PR and Do It How You Prefer. I just figured this was a convenient way to get the ball rolling.

### CODE REVIEW

**Review by eeckstein — APPROVED** [review]
Cool!

**Comment by graydon** [comment]
@swift-ci please test and merge

**Comment by graydon** [comment]
@swift-ci smoke benchmark

**Comment by graydon** [comment]
@swift-ci please test and merge

**Comment by palimondo** [comment]
Just curious, where did you dig this up? Googling for `proc_pid_rusage RUSAGE_INFO_V4` gives me 5 results total…

**Comment by graydon** [comment]
@swift-ci please test and merge

**Comment by graydon** [comment]
@palimondo Chatting with the kernel devs about some other tools that use it. It's a relatively new API, but super useful.

**Comment by shahmishal** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by palimondo** [comment]
Build failed with `
/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/benchmark/utils/LibProc/LibProcIncludeSystemHeader.h:15:10: error: 'libproc.h' file not found
`.

**Comment by palimondo** [comment]
@graydon 
> It's a relatively new API, but super useful.
Is this a Mojave addition? This might be a problem…

**Comment by graydon** [comment]
@palimondo oh no, sorry, I meant that the instructions field being filled-in is new; the API has been there forever. It looks like some SDKs don't provide the header but I can just probe for it and provide the prototype when it's missing.

**Comment by graydon** [comment]
@swift-ci please test and merge

**Comment by graydon** [comment]
@swift-ci please test and merge

**Comment by graydon** [comment]
Last failure was this:

~~~~
19:52:55 <stdin>:20:1: note: non-matching line after previous match is here
19:52:55  Yielding again after estimated 33980 us
19:52:55 ^
~~~~

This seems like it was fixed by 3faf9259e158365cfacda77dddd31ef5120226ae so I'm going to retry.

**Comment by graydon** [comment]
@swift-ci please test and merge

**Comment by palimondo** [comment]
I'm sorry about that failing test! Forgot to launch lit tests before pushing. 👿😇

**Pull request merged**
