### PR TITLE
[sil] Rename {,Strong}Copy{Unowned,Unmanaged}.

### PR DESCRIPTION
**Pull request by gottesmm**
As requested in #27375

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
The given test failed since the order in which the functions were output changed. It changed b/c the file uses a special flag that orders functions in the output by name and I renamed the test function from test_copy_* to test_strong_copy_*. I fixed the order in the test case.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
Resolved the merge conflict. Trying again.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Review by atrick — COMMENTED** [review]
LGTM. This makes sense now that I see the constraint: `$T must be a reference type`.

**Pull request merged**
