### PR TITLE
[ownership] Eliminate Optional return value APIs from OwnershipUtils in favor of an Invalid enum case.

### PR DESCRIPTION
**Pull request by gottesmm**
Should be NFC.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
Or actually I am going to do a full test.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
Just to provide a back link, @atrick asked me to do this when reviewing #35297.

**Review by atrick — APPROVED** [review]
I just skimmed this, but it looks much better this way since we want these Operand/Value abstractions to have the same programming model as Operands and Values.

**Pull request merged**
