### PR TITLE
[Driver, Incremental] Add enable- and disable- only-one-dependency-file flags off-by-default

### PR DESCRIPTION
**Pull request by davidungar**
Only enabled if the driver is passed -enable-only-one-dependency-file

Since every make-style dependency file has the same contents, it wastes time to output one for each source file. Only write one real one, and create empty dummy files (to keep the build system happy) for the rest.

Latest version of this facility. Intervenes earlier in the driver in order to work well with batch mode.

Landing this PR first, planning to land a separate one turning the feature on-by-default. That way, it can be easily disabled.

Preparatory for rdar://57824038

### CODE REVIEW

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Review by CodaFi — APPROVED** [review]

**Pull request merged**
