### PR TITLE
[Fixit] Add a fixit for converting non-trailing closures to trailing closures

### PR DESCRIPTION
**Pull request by nkcsgexi**
To enhance the discoverability of trailing closures, this fix helps users to convert non-trailing closures to trailing closures. To ensure disambiguity after conversion, we check name conflict before adding the note.

#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci Please test

**Comment by rintaro** [comment]
False positive:
```
struct Foo {
  func fn(_ x: () -> Int) -> [Int] {}
}

let v = Foo()
for _ in v.fn({ 1 }) { }
```
```
error: unexpected note produced: use trailing closure to simplify arguments
for _ in v.fn({ 1 }) { }
```
Too much remove: 
```
extension Foo {
  func fn2(_ x: () -> Int) {}
}
v.fn2({ 1 }); print("foo")
```
This PR emit fix-it: `{{6-8=}} {{12-14=}}`, that is to remove `({` and `);`

**Comment by rintaro** [comment]
@nkcsgexi Could you revert this for now?

**Comment by nkcsgexi** [comment]
Oh, thanks for the comments! I will push further commit to fix the cases. Do I block some one? Why do I have to revert it?

**Comment by lattner** [comment]
Our general approach is to revert eagerly if a patch cannot be immediately fixed.  As I mentioned on a comment to the patch in question, I think it should be reverted for other reasons.

**Comment by nkcsgexi** [comment]
@lattner@rintaro Faire enough. I have reverted this patch at 1e85e1b.

**Pull request merged**
