### PR TITLE
[benchmark] More CharacterProperty variations

### PR DESCRIPTION
**Pull request by milseman**

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please smoke test

**Comment by milseman** [comment]
@swift-ci please smoke benchmark

**Comment by milseman** [comment]
Err, it seems the precomputed is getting caught up in that lazy initialization bit...

**Comment by lorentey** [comment]
There is a `BenchmarkInfo.setUpFunction` property, which seems exactly what we need.

**Review by lorentey — APPROVED** [review]

**Comment by gottesmm** [comment]
@milseman @lorentey I am glad that setUpFunction is working for you = ). I added it so we could handle these sorts of cases better.

**Comment by milseman** [comment]
@swift-ci please smoke benchmark

**Comment by milseman** [comment]
@swift-ci please smoke test

**Comment by milseman** [comment]
@swift-ci please smoke test linux platform

**Comment by milseman** [comment]
@swift-ci please smoke benchmark

**Comment by milseman** [comment]
Err? CC @Rostepher 
```
CMake Error at cmake/modules/AddLLDB.cmake:69 (add_llvm_install_targets):
  Unknown CMake command "add_llvm_install_targets".
Call Stack (most recent call first):
  source/API/CMakeLists.txt:22 (add_lldb_library)
```

**Comment by milseman** [comment]
@swift-ci please smoke test linux platform

**Pull request merged**
