### PR TITLE
build: convert NDK path on Windows

### PR DESCRIPTION
**Pull request by compnerd**
Convert the NDK path to allow the native path to be used when
configuring the Swift runtime but use the CMake spelling when
performing the inner configure.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @drexin @buttaface

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Review by drexin — APPROVED** [review]
LGTM

**Comment by buttaface** [comment]
Should be fine, if it breaks my Android CI, I'll modify it later.

**Pull request merged**
