### PR TITLE
[🛑WIP][stdlib] Minify the binary size of integer inits from floating point …

### PR DESCRIPTION
**Pull request by moiseev**
…types

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please smoke benchmark

**Comment by swiftix** [comment]
@moiseev You may need to add `@_semantics("optimize.sil.specialize.generic.partial.never")` (or `@_semantics("optimize.sil.specialize.generic.never")`) to `_convertFrom`. Use the cmpcodesize script to check the size of functions being produced.

**Comment by shajrawi** [comment]
Based on my testing, this PR reduces libswiftCore's text size from 3862180 to 3857828 (i.e. not enough)

**Pull request closed without merging**
