### PR TITLE
[BatchMode] Make driver report exits per-batch, not per-constituent.

### PR DESCRIPTION
**Pull request by graydon**
I was overzealous in the amount of work I made the driver do on a per-constituent basis when a task exits. The driver's model of the task should be per-constituent, but the Pid-based reporting and output-writing should happen per-batch.

(And doing anything in the signalling patch per-constituent is pointless; it only does one thing).

This is required to run batch mode correctly under xcodebuild, or in general anything reading parseable-output. And it's required to make _sense_ of the output in any case.

(And with this change, substantial parts of the source compat suite build in batch mode)

### CODE REVIEW

**Comment by graydon** [comment]
@swift-ci please test

**Comment by graydon** [comment]
(@jrose-apple I know this should have its own dedicated test; I'll try to write one tomorrow, a bit late for it tonight)

**Comment by jrose-apple** [comment]
Yes, test please! And how does this appear in Xcode's build log? (Maybe attach a screenshot of Xcode 9.3b3, if that handles it well enough?)

**Review by jrose-apple — APPROVED** [review]
If this works for Xcode then it works for me!

**Comment by graydon** [comment]
@jrose-apple It doesn't look _fantastic_ in that, like with WMO, you no longer see the individual files, but it's not so bad; just looks like "multiple instances of WMO".

screen shot 2018-03-02 at 11 17 48 am

**Comment by graydon** [comment]
@swift-ci please test

**Comment by graydon** [comment]
@swift-ci please test Linux platform

**Comment by graydon** [comment]
@swift-ci please test

**Pull request merged**
