### PR TITLE
[CSDiag] Always find and set correct declaration context for sub-expr…

### PR DESCRIPTION
**Pull request by xedin**
…ession type-check

Replace dedicated method with `typeCheckChildIndependently` always
setting the closest possible declaration context for type-check call.
This fixes a problem where sub-expression comes from multiple levels
or nested closures but CSDiag didn't re-typecheck parent closure.

Resolves: rdar://problem/50869732

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please build toolchain

**Comment by xedin** [comment]
I'm going to reduce example from SwiftUI and add it to the suite.

**Comment by xedin** [comment]
@swift-ci please build toolchain macOS

**Comment by xedin** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Pull request merged**
