### PR TITLE
Fix double static error message

### PR DESCRIPTION
**Pull request by zoecarver**
This PR changes the error message for two static patterns in a row. For example:
```
class Foo {
 class static func baz() { } // old: 'static' specified twice
 static class func bar() { } // new: 'class' cannot appear after another 'static' or 'class' pattern
}
```
Resolves [SR-11265](https://bugs.swift.org/browse/SR-11265).

Not sure if I have permissions for this: @swift-ci Please test

### CODE REVIEW

**Comment by theblixguy** [comment]
cc @rintaro

**Comment by gregomni** [comment]
@swift-ci Please smoke test

**Comment by gregomni** [comment]
I think instead of "'static' or 'class' pattern" the message should probably be "'static' or 'class' keyword". But otherwise this is a great improvement!

**Comment by zoecarver** [comment]
Updated as per your request :)

**Comment by CodaFi** [comment]
LGTM.  Will manually squash this in

@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
[Swift-CI'll get back to you soon](https://ci.swift.org/job/swift-PR-Linux-smoke-test/16310/)

**Pull request merged**
