### PR TITLE
[lldb][cxx-interop] Tell LLDB about the extra layer of indireciton for foriegn reference types.

### PR DESCRIPTION
**Pull request by zoecarver**

### CODE REVIEW

**Comment by zoecarver** [comment]
@swift-ci please test.

**Comment by zoecarver** [comment]
@adrian-prantl not really sure how to write a test for this. Could you point me to an example swift/lldb test?

**Comment by adrian-prantl** [comment]
For Swift, you could copy `https://github.com/apple/swift/blob/main/test/DebugInfo/generic_arg.swift`, which also checks for a DW_OP_deref on a local variable.

**Comment by adrian-prantl** [comment]
For the imported types, it's best to create a C++ module in `Inputs/`, like https://github.com/apple/swift/blob/main/test/DebugInfo/C-typedef.swift does.

**Comment by adrian-prantl** [comment]
For LLDB it could be based off of https://github.com/apple/llvm-project/tree/next/lldb/test/API/lang/swift/any . We should probably create a new subdirectory for the C++ tests there. I can write the first test and add you as a reviewer and then you can copy that going forward.

**Pull request merged**
