### PR TITLE
[AutoDiff] Fix differentiation crashes related to definite initialization.

### PR DESCRIPTION
**Pull request by dan-zheng**
[SIL] Fix `alloc_stack [dynamic_lifetime]` attribute cloning.

Make `SILCloner:visitAllocStack` correctly propagate the `[dynamic_lifetime]` attribute.

Resolves SR-12886: differentiation transform error related to the `VJPEmitter`
subclass of `SILCloner`.

---

[AutoDiff] Fix SIL locations and debug scopes.

Fix SIL locations and debug scopes in `VJPEmitter` for:
- Pullback struct `struct` instructions
- Predecessor enums `enum` instructions

These instructions are not directly cloned from the original function and should
have auto-generated locations.

Resolves SR-12887: debug scope error for `VJPEmitter`-generated functions.

### CODE REVIEW

**Comment by dan-zheng** [comment]
@gottesmm: would you like to sanity check this PR? It should not be controversial.

**Comment by dan-zheng** [comment]
@swift-ci Please test

**Review by rxwei — COMMENTED** [review]
Typo: `[dynamic_lifetime]`, not `[dynamic_replacement]`.

**Comment by dan-zheng** [comment]
@swift-ci Please test

**Review by rxwei — APPROVED** [review]

**Comment by dan-zheng** [comment]
@swift-ci Please test

**Comment by dan-zheng** [comment]
The test for verification error SR-12886 added in the first commit revealed a second verification error SR-12887, so I pushed  a fix for that too.

Updated PR title and description.

**Comment by dan-zheng** [comment]
@swift-ci Please test

**Comment by dan-zheng** [comment]
@swift-ci Please test

**Comment by dan-zheng** [comment]
Unrelated llvm macOS CI error.
@swift-ci Please test macOS

**Comment by dan-zheng** [comment]
Linux CI appears to have flaked while building SwiftPM.
@swift-ci Please test Linux

**Comment by dan-zheng** [comment]
Linux and macOS platform tests have both flaked multiple times. I'll try smoke tests instead.

**Comment by dan-zheng** [comment]
@swift-ci Please smoke test

**Comment by dan-zheng** [comment]
@swift-ci Please smoke test Linux

**Comment by dan-zheng** [comment]
@swift-ci Please smoke test Linux

**Comment by dan-zheng** [comment]
@swift-ci Please smoke test Linux

**Comment by dan-zheng** [comment]
@swift-ci Please clean smoke test Linux

**Comment by dan-zheng** [comment]
Linux CI still flakes while building SwiftPM: https://ci.swift.org/job/swift-PR-Linux-smoke-test/22548/console

I'm pretty sure it's a flake because the same error occurs for other PRs: https://ci.swift.org/job/swift-PR-Linux-smoke-test/22543

I rebased on top of master in case it helps. Retriggering tests.

**Comment by dan-zheng** [comment]
@swift-ci Please smoke test

**Comment by dan-zheng** [comment]
@swift-ci Please smoke test

**Comment by dan-zheng** [comment]
@swift-ci Please smoke test

**Comment by dan-zheng** [comment]
@swift-ci Please smoke test Linux

**Comment by dan-zheng** [comment]
@swift-ci Please smoke test Linux

**Pull request merged**
