### PR TITLE
[benchmark] BenchmarkDriver check --markdown

### PR DESCRIPTION
**Pull request by palimondo**
Added `--markdown` flag for the `check` command to output the `BenchmarkDoctor`’s report in the Markdown format (as used by swift-ci on GitHub).

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Review by eeckstein — CHANGES_REQUESTED** [review]
Please look at the benchmark build log. There is a crash in the script.

**Comment by eeckstein** [comment]
It does not. I started a benchmark run

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Comment by eeckstein** [comment]
And, as it's not a compiler change, it's sufficient if you do a smoke test for this.

**Comment by palimondo** [comment]
Hmm… I ran full test, because I wanted CI to run through bencmark's `lit` tests, which are not executed during smoke test. Can we at least make those run in smoke, do that I don't need to invoke full test for that reason?

**Comment by eeckstein** [comment]
They should run with smoke test, because they are in swift/test. But maybe I'm missing something here.

**Comment by palimondo** [comment]
I think smoke test doesn't build benchmark binaries for some reason. The python tests for benchmark scriptd get executed, but not the `Benchmark_O.test.md` and `Benchmark_Driver.test-sh` because they both have `REQUIRES: benchmark` in them.

**Comment by palimondo** [comment]
But none of them would have caught this bug…😔
I can fix the test to catch that. I just don't add the `markdown` to args stub, to maintain original API. 

It didn't occur to me I need to adjust `run_smoke_bench` when I've [modified the ArgsStub](https://github.com/apple/swift/pull/21477/files#diff-27f028b6bf40a642534e6a263b61d44cR514) to make the other test's pass...

**Review by eeckstein — APPROVED** [review]

**Comment by palimondo** [comment]
@eeckstein Can we make smoke test build the benchmark binary? 
(I don't know how to make that change...)

**Comment by eeckstein** [comment]
That needs negotiation with @shahmishal. We are trying very hard to keep the smoke test time down to a minimum.

**Comment by shahmishal** [comment]
@palimondo / @eeckstein How much extra time are we looking at building benchmark binary?

**Comment by eeckstein** [comment]
When we just build a single executable, e.g. Benchmark_O (and not the Osize and Onone variants), it's about 5min user time on my machine. + 4 sec to run it (what we should do, because this gives more test coverage)

**Comment by palimondo** [comment]
Really don't know. I'm running my local builds on 2008 MBP…

**Pull request merged**
