### PR TITLE
[5.0][Sema] Emit a deprecation warning if a Hashable type only implements hashValue

### PR DESCRIPTION
**Pull request by lorentey**
(Cherry-picked from #21057 and #20866)

SE-206 deprecated `hashValue` as a protocol requirement. We should gently encourage people to migrate to `hash(into:)`, for its more secure, easier and faster hashing.

- Emit a compiler warning whenever `hashValue` has an explicit implementation, but `hash(into:)` doesn’t. (#21057)
- Update the test suite to fix regressions caused by the new warning.

rdar://problem/39838478, rdar://problem/46344811

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
Ah, my bad, this requires (at least some parts of) #20866 for the test suite.

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test

**Review by airspeedswift — APPROVED** [review]

**Pull request merged**
