### PR TITLE
Tiny optimization and cleanups

### PR DESCRIPTION
**Pull request by slavapestov**
I found a project where we were spending more than 2% of total compile time in `getTypeOfMember()`. Most callers only passed in a `VarDecl` or `EnumElementDecl`, so now it only supports those and applies `getContextSubstitutionMap()`, which is cached.

Also clean up some older code that used `TypeSubstitutionMap`, which I'd like to get rid of because it's a `DenseMap` which is wasteful for just a handful of generic parameter keys.

Finally, remove `substRootParam()` and `substBaseType()` methods on `DependentMemberType`, which were only used in a few places. There are better ways of doing the same thing with existing primitives.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Review by xedin — APPROVED** [review]

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Pull request merged**
