### PR TITLE
tests: update expected response

### PR DESCRIPTION
**Pull request by compnerd**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

It seems that clang module changes have resulted in changes for the USR that is
rendered.  Update the test accordingly.

### CODE REVIEW

**Comment by tkremenek** [comment]
@swift-ci Please test

**Comment by compnerd** [comment]
Unfortunately, this is for master-next, which @swift-ci  does not support.  @gottesmm usually tests these locally AFAIK.

**Comment by gottesmm** [comment]
@shahmishal Do you have an ETA on when we can get a swift-ci test for master-next?

**Comment by shahmishal** [comment]
@gottesmm I will have this ready by end of the week.

**Comment by shahmishal** [comment]
@gottesmm, @swift-ci now has support for master-next branch.

**Comment by gottesmm** [comment]
@swift-ci Please smoke test Linux Platform

**Comment by compnerd** [comment]
Seems to be an infrastructure issue?  It seems that it failed to clone the repositories resulting in the failure.

**Comment by shahmishal** [comment]
Does swift master-next branch have this change https://github.com/shahmishal/swift/commit/2eb743299933a1ba24752a018515c2f808007440?

**Comment by compnerd** [comment]
No, it would appear it does not.

**Comment by gottesmm** [comment]
Let me try doing a master-next update. I will make sure it is there.

Michael

**Comment by gottesmm** [comment]
@compnerd Can you rebase the branch against master-next?

**Comment by compnerd** [comment]
Rebased, though untested.

**Comment by gottesmm** [comment]
@swift-ci Please smoke test Linux Platform

**Comment by gottesmm** [comment]
@compnerd Thanks for the rebase. Hopefully the rebased changes will have the commit by @shahmishal.

**Comment by gottesmm** [comment]
@swift-ci Please smoke test OS X platform

**Comment by gottesmm** [comment]
Hmmm... That one is on me. 1 sec.

**Comment by gottesmm** [comment]
Ok. The linux test output looks ok (that is an expected failure on that branch). The only problem is the OS X test.

**Comment by gottesmm** [comment]
@swift-ci Please test OS X platform

**Comment by gottesmm** [comment]
This looks good. I think the smoke test failure was due to some issue with the incremental darwin not running maybe? @shahmishal sounds like a  bug.

The test that failed on Linux/OS X is a known failure that is being looked at. Merging!

**Pull request merged**
