### PR TITLE
Code size: destroy_addr outline

### PR DESCRIPTION
**Pull request by shajrawi**
radar rdar://problem/33942466

Part 3: outline `destroy_addr` operations

### CODE REVIEW

**Comment by shajrawi** [comment]
@swift-ci Please clean test

**Comment by shajrawi** [comment]
The Mac failure is unrelated - someone broke trunk:

SIL verification failed: struct operand type does not match field type: (*opi)->getType() == loweredType
Verifying instruction:
     %0 = integer_literal $Builtin.Int64, 2       // user: %1
->   %1 = struct $Int (%0 : $Builtin.Int64)       // user: %3
     store %1 to %2 : $*Int                       // id: %3

**Comment by shajrawi** [comment]
@swift-ci Please smoke test OS X

**Comment by atrick** [comment]
It would be really helpful as a casual reviewer to see more descriptive commit messages.
What kinds of destroy_addr generate different code?
How many "outlined" routines are emitted. One for every destroyed type?
Does this introduce overhead for some types by introducing multiple levels of calls?

**Comment by shajrawi** [comment]
Only enums and record types get outlined. scalars , resilient types and similar do not.
One outlined routine per canonical type is omitted.
There is the slight overhead of a function call of course, just like any other form of outlining

**Comment by atrick** [comment]
Thank you, but my request was that you provide information in the git commit message.

**Pull request merged**
