### PR TITLE
[CSBindings] Preserve l-valueness of optional object type

### PR DESCRIPTION
**Pull request by xedin**
Result of force unwrap is always connected to its base
optional type via `OptionalObject` constraint which
preserves l-valueness, so in case where object type got
inferred before optional type (because it got the
type from context e.g. parameter type of a function call),
we need to test type with and without l-value.

Resolves: rdar://problem/47967277

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by jrose-apple** [comment]
Is this going to hurt compile time?

**Comment by xedin** [comment]
@jrose-apple Very unlikely, since original type gets attempted first and if it succeeds `@lvalue` version is not going to be attempted. This is also pretty narrow, the situation from new test - type of the optional object got deduced through generic parameter of the Set argument before its base. Usually object type would get bound only after the base type is resolved, but sometimes we get "lucky" :)

**Comment by xedin** [comment]
@nathawes There is a failure in `test/SourceKit/CodeComplete/complete_swiftinterface.swift` on `iphonesimulator-i386` doesn't seem related to my changes, not sure if that's just an intermittent error or something else.

**Comment by jrose-apple** [comment]
I think Brent reverted that one.

**Comment by xedin** [comment]
Ok, I figured out what the problem is - implicit conversions, we have to avoid commuting bindings for `optional object` all together otherwise there is a risk of skipping viable solutions, bindings to that type variable should always come when its base is resolved.

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
