### PR TITLE
Added an experimental flag to delete all graph ops at the end of the deabstraction pass.

### PR DESCRIPTION
**Pull request by mhong**
Context: Graph mode compilation currently takes ~2 minutes on a resnet 50
model (forward pass only). One conjecture is that running the compiler
performance pipeline over the graph code might have take non-trivial time, and
that could be minimized if we move up the partition pass to be right after
deabstraction, so that we can slice out the accelerator function at the end of
the mandatory pipeline, and do not feed that function through the performance
pipeline (instead, we can optimize the accelerator function at the graph level, say
via TF grappler).

One way to simulate the compiler performance of the above change is to delete
all graph_ops after deabstraction, so that the performance pipeline only pays
the cost of optimizing host code.

**Unfortunately, the performance gain is not significant on a simplified version of the resnet50 model.**

The time cost of compiling a resnet model (source code to be released) under `-DuseToyModel` is
17.6s (with 27900 SIL instructions in the deabstraction result). After deleting
the graph ops via the new flag `-Xllvm -tf-delete-graph-ops`, the time cost
reduced to 14.6s (with 27016 SIL instructions).

This suggests that we should look into other venues for compiler performance
optimization first, such as modular (non-inline-based) compilation.

This patch is to submit the new code path for deleting graph_ops under a flag,
so that this experiment can be performed on other future models in case needed.

### CODE REVIEW

**Comment by lattner** [comment]
Thanks for doing this experiment!  I don't think this is something we should land in tree though, do you?

**Comment by mhong** [comment]
My slight preference is to submit it (this patch is flag-protected, and the flag defaults to OFF), for the slight chance that we want to redo this analysis on other programs / ML models.

Once we converge on (or complete) the longer-term solution on reducing compiler cost (e.g. reduce inlining), we can come back and easily revert this patch. 

Does that sound reasonable?

**Comment by lattner** [comment]
I will not argue strongly against it if you have a reason to believe this will be useful in the future, but the general LLVM/Swift policy is to not add a bunch of knobs like this.  They are untested dead code that accrete complexity and can never be removed once added.

This will never be taken upstream so it will always be in our diff.

**Comment by mhong** [comment]
k, closing this PR for now. In case we need to redo the experiment, we can easily revise it. Thanks.

**Pull request closed without merging**
