### PR TITLE
Add IsSDKRelative field to ModuleInterfaceLayout

### PR DESCRIPTION
**Pull request by rmaz**
When serializing the module interface path of an interface that is part of the SDK, we serialize relative to the SDK path. During deserialization we need to know if a path was serialized relative to the SDK or not. The existing logic assumes any relative path has been serialized relative to the SDK, which makes it impossible to compile modules from relative swiftinterface paths that are not part of the SDK.

Update the swiftmodule file to include an attribute to show if the path was serialized relative to the SDK or not, which is used during deserialization to correctly reconstruct the interface path.

### CODE REVIEW

**Comment by rmaz** [comment]
@swift-ci please test

**Comment by rmaz** [comment]
@swift-ci please test

**Comment by rmaz** [comment]
@swift-ci please test

**Review by xymus — APPROVED** [review]
LGTM

Do you know why it currently fails or where the compiler is using that path? I can see the `cannot open file ` error when running the test locally, but I would have expected that path to be used mostly for diagnostics or by the dependency scanner so I'm surprised the frontend tries to open the file.

**Comment by rmaz** [comment]
> LGTM
> 
> Do you know why it currently fails or where the compiler is using that path? I can see the `cannot open file ` error when running the test locally, but I would have expected that path to be used mostly for diagnostics or by the dependency scanner so I'm surprised the frontend tries to open the file.

I believe the test failure is unrelated, i'll give it another rebase to check

**Comment by xymus** [comment]
yeah the failure on `shebang-env.swift` looks unrelated and it should be fixed by now.

However I meant to ask if you know why your test fails before your fix? Why is the compiler opening that file?

**Comment by rmaz** [comment]
> However I meant to ask if you know why your test fails before your fix? Why is the compiler opening that file?

Oh I see. The test fails because the deserialized swiftinterface path for B.swiftmodule is relative, but is not found in the SDK. When deserializing the compiler will construct its path relative to the SDK, and fails with:
```
<unknown>:0: error: cannot open file '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk/relative_path/B.swiftmodule/arm64-apple-macos.swiftinterface' (No such file or directory)
```
This is raised here, while checking the dependencies of the module:
https://github.com/swiftlang/swift/blob/9e7fa1a023f4e3ad5020f572079bddc41d1ba054/lib/Frontend/ModuleInterfaceBuilder.cpp#L159-L163

**Comment by rmaz** [comment]
@swift-ci please test

**Comment by xymus** [comment]
Oh ok, we consider the swiftinterface as a dependency of the client swiftmodules to trigger a rebuild on upstream changes. That makes sense, thank you!

**Comment by rmaz** [comment]
@swift-ci please smoke test

**Comment by rmaz** [comment]
@swift-ci please test

**Comment by rmaz** [comment]
@swift-ci please test

**Comment by rmaz** [comment]
@swift-ci please smoke test Linux Platform

**Review by artemcm — APPROVED** [review]

**Pull request merged**
