### PR TITLE
[SIL.rst] Convert a bunch of bolded instruction names to inline links to the instructions docs.

### PR DESCRIPTION
**Pull request by gottesmm**
Seems useful to allow for quick navigation. I did not get all of them, but did a
bunch of them.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Review by meg-gupta — APPROVED** [review]

**Comment by atrick** [comment]
Links... cool, I didn't know it was so easy. Is this a reason for keeping it in .rst instead of .md?

**Comment by gottesmm** [comment]
@swift-ci smoke test OS X platform

**Comment by gottesmm** [comment]
@atrick people talked about it at one point I don't remember why we didn't do it. I imagine maybe history? @belkadan might remember.

**Comment by belkadan** [comment]
Originally we were going to convert all of the documents, and then we found that a few of them actually make use of ReST features that don't translate to Markdown. (In particular, we got a PR that did an automated translation of all the docs that lost a bunch of information, and realizing that we'd need manual conversions slowed the momentum for actually converting everything.)

**Pull request merged**
