### PR TITLE
Some create_benchmark.py script enhancements.

### PR DESCRIPTION
**Pull request by oscbyspro**
This patch addresses some trials and tribulations I encountered in (#71786). It:

1. fixes the auto-registration regex
2. fixes the auto-generated array's name
3. generates the current year for the license header
4. generates some dashes for the license header

#### Short how-to per README.md

```
swift-source$ ./swift/benchmark/scripts/create_benchmark.py YourTestNameHere
```

### CODE REVIEW

**Review by glessard — APPROVED** [review]
Nice!

**Comment by glessard** [comment]
@swift-ci please smoke test

**Comment by oscbyspro** [comment]
Looks like Flake8 holds it at *linterpoint*. I've paid the ransom*.

*I downloaded PyCharm and asked it to refactor the parts I wrote.

**Comment by glessard** [comment]
@swift-ci please smoke test

**Comment by oscbyspro** [comment]
@glessard can you ask @swift-ci to test it again? I doubt the failure on Windows has anything to do with this PR.

**Comment by glessard** [comment]
I didn't realize it hadn't gone through!

**Comment by glessard** [comment]
@swift-ci please test windows platform

**Pull request merged**
