### PR TITLE
[5.5] cherry-pick -clang-target related changes.

### PR DESCRIPTION
**Pull request by nkcsgexi**
rdar://72480261

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Comment by nkcsgexi** [comment]
@swift-ci Please test OS X platform

**Comment by nkcsgexi** [comment]
@swift-ci Please test OS X platform

**Review by tkremenek — APPROVED** [review]

**Pull request merged**
