### PR TITLE
Run tests under lsan

### PR DESCRIPTION
**Pull request by marcrasi**
This adds a preset that runs the primary swift tests under LSAN.

I excluded all the tests that currently fail by adding "XFAIL: lsan" to all the tests that currently fail under LSAN.

If we change the LSAN CI job to run this new preset, this should allow people to gradually ratchet up the number of tests that pass under lsan, without backsliding.

The "XFAIL: lsan" changes are in a separate commit to make reading this PR easier.

https://bugs.swift.org/browse/SR-11313

### CODE REVIEW

**Comment by gottesmm** [comment]
@akyrtzi @rintaro might be of interest to you.

**Comment by gottesmm** [comment]
Ah nm. Read the bug.

**Comment by gottesmm** [comment]
Bug +1 to this effort! Cracking down on these leaks is important especially if they can hit SourceKit!

**Comment by gottesmm** [comment]
*Bug == Big ; )

**Comment by rintaro** [comment]
Could you make it `XFAIL: lsan` so that we can know which test cases are fixed when we modify the code?

**Comment by marcrasi** [comment]
Changed it to XFAIL!

**Comment by marcrasi** [comment]
Heh, this broke a lot of SourceKit tests under non-lsan because the `// XFAIL: lsan` line changed line numbers for everything else. I fixed this by putting the XFAIL at the bottom and manually adjusting three  expected responses that were affected even with the XFAIL at the bottom.

**Comment by marcrasi** [comment]
@swift-ci please test

**Comment by marcrasi** [comment]
@swift-ci please test

**Comment by rintaro** [comment]
preset=buildbot_incremental_linux,lsan,tools=RDA,stdlib=DA
@swift-ci Please test with preset Linux Platform

**Comment by marcrasi** [comment]
@swift-ci Please test OS X platform

**Comment by rintaro** [comment]
preset=buildbot_incremental_linux,lsan,tools=RDA,stdlib=DA
@swift-ci Please test with preset Linux Platform

**Comment by rintaro** [comment]
@swift-ci Please test OS X platform

**Comment by rintaro** [comment]
preset=buildbot_incremental_linux,lsan,tools=RDA,stdlib=DA
@swift-ci Please test with preset Linux Platform

**Comment by marcrasi** [comment]
Hmm, the lsan build keeps getting killed during linking:
```
clang: error: unable to execute command: Killed
23:51:29 clang: error: linker command failed due to signal (use -v to see invocation)
```

I'll rebase this and try again. 

If it keeps happening, maybe the lsan build doesn't work on ubuntu 16 machines? I notice that the swift-linux-PR-preset build happens on ubuntu 16 machines, but the oss-swift-incremental-RA-lsan-linux-ubuntu-18_04 build happens on ubuntu 18 machines.

**Comment by marcrasi** [comment]
preset=buildbot_incremental_linux,lsan,tools=RDA,stdlib=DA
@swift-ci Please test with preset Linux Platform

**Comment by marcrasi** [comment]
preset=buildbot_incremental_linux,lsan,tools=RDA,stdlib=DA
@swift-ci Please test with preset Linux Platform

**Comment by rintaro** [comment]
@shahmishal Do you know why this preset build keeps failing in PR bot?
https://ci.swift.org/job/swift-PR-Linux-preset/57/console
https://ci.swift.org/job/swift-PR-Linux-preset/58/console

Also, is it possible to make LSAN bot to run this preset? after merging this PR?

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
