### PR TITLE
[AutoDiff] IRGen `autodiff_function` and `autodiff_function_extract` instructions

### PR DESCRIPTION
**Pull request by rxwei**
* Add type lowering for `@autodiff` function. It's a plain tuple of the original function and associated functions. Associated functions are expected to have the same representation as the original function.
* IRGen `autodiff_function` and `autodiff_function_extract` instructions.
* Fix a bug in `autodiff_function_extract` type calculation.

### CODE REVIEW

**Comment by rxwei** [comment]
Creating a struct type into directly may be simpler. I'll give that a try.

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Review by marcrasi — APPROVED** [review]

**Comment by rxwei** [comment]
@swift-ci  please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux

**Pull request merged**
