### PR TITLE
[ASTMangler] Add support for mangling generic typealiases.

### PR DESCRIPTION
**Pull request by dcci**
<rdar://problem/39915946>

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by dcci** [comment]
@swift-ci please test

**Comment by dcci** [comment]
Type reconstruction will come next, but, even with this patch alone, at least we don't crash when trying to print generic type aliases in lldb anymore :)

**Comment by dcci** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
It's a remangler failure:

```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -swift-version 4
21:30:35 Remangling failed:
21:30:35 original     = $Ss10DictionaryVy12PackageGraph0B22ContainerConstraintSetV10IdentifieraAE11RequirementayAEQq_AFQa_GGD
21:30:35 remangled    = $Ss10DictionaryVy12PackageGraph0B22ContainerConstraintSetV10IdentifieraAEyAEQq_AFQaG11RequirementaGD
```

otherwise, the changes generally look correct to be. @eeckstein is more the expert here.

**Review by eeckstein — APPROVED** [review]
lgtm!

**Comment by dcci** [comment]
Reduces to just:
```
extension DictionaryIndex {}

internal enum _VariantDictionaryBuffer<Key: Hashable, Value> {
  internal typealias Index = DictionaryIndex<Key, Value>
}

public struct Dictionary<Key: Hashable, Value> {
  internal typealias _VariantBuffer = _VariantDictionaryBuffer<Key, Value>
}

var Patatino : Dictionary<Int, Int>._VariantBuffer.Index
```

Looks like we need a special treatment for mangling extensions here?

**Comment by dcci** [comment]
@swift-ci please test

**Pull request merged**
