### PR TITLE
libSyntax: Ensure round-trip printing when we build syntax tree from parser incrementally.

### PR DESCRIPTION
**Pull request by nkcsgexi**
This also disables raw syntax token lexing in non-IDE mode. We saw memory surge when keeping syntax token parsing enabled at regular builds.
cc @DougGregor

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@nkcsgexi , in the future could you make your commit messages more descriptive? I see what the code does, but it's not at all clear from the commits what they're supposed to do.

**Comment by nkcsgexi** [comment]
@DougGregor thanks for the reminder, will be more descriptive in the future : )

**Pull request merged**
