### PR TITLE
Verify noescape closures for exclusivity diagnostics.

### PR DESCRIPTION
**Pull request by atrick**
Verify @inout_aliasable captures.
    
This is currently only done in DiagnoseStaticExclusivity because AllocBoxToStack
doesn't know how to set @noescape function types yet.

Negative test cases need to be added. This PR is currently just for SCK testing and review.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci Test Source Compatibility.

**Comment by slavapestov** [comment]
What are inout_aliasable captures actually used for these days?

**Comment by atrick** [comment]
@slavapestov `@inout_aliasable` is for any captured variable that's promoted to the stack (unboxed). SILGen emits them in the obvious cases. The reason they need to be verified is that exclusivity checking is completely different in those cases. There aren't any access markers in the SIL. Instead it is assumed that the diagnostic pass can detect all closure applications and analyze the body of the closure. So, this verification is required to guard against undefined behavior.

Incidentally, I was working on removing the `@inout_aliasable` convention on a branch, relying on the @noescape attribute instead, removing the special logic from SILGen, and unifying several passes, but I can't enable any of that until exclusivity is officially part of the language.

**Comment by atrick** [comment]
This passed SCK testing. I think we can enable this verification now by default in debug builds.

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
@swift-ci test.

**Comment by slavapestov** [comment]
@atrick What does it mean for exclusivity to be part of the language model? I thought it was already.

**Comment by atrick** [comment]
@slavapestov It's part of the language but the compiler can't make that assumption yet. We don't want to make it undefined behavior until there's some arbitrary level of confidence that code doesn't break it in practice.

**Comment by atrick** [comment]
The test failure is unrelated to this PR.

**Comment by slavapestov** [comment]
@atrick I see, so basically once exclusivity checking is complete you plan on changing the optimizer to start assuming it?

**Comment by atrick** [comment]
@slavapestov We won't make assumptions that lead to memory unsafety or undefined behavior yet. Enforcement needs to be adequate in Swift 5 if we ever want to make those assumptions.

**Comment by atrick** [comment]
@devincoughlin Does this look ok?

**Comment by devincoughlin** [comment]
Looks great!

**Review by devincoughlin — APPROVED** [review]

**Comment by atrick** [comment]
@swift-ci test and merge.

**Pull request merged**
