### PR TITLE
[Syntax] Serveral improvements for Trivia lexing

### PR DESCRIPTION
**Pull request by rintaro**
Several improvements for Trivia to improve roundtrip-ness.

* Simplified `Lever::lexTrivia` function.
* Added lexing `'\v'`(`TriviaKind::VerticalTab`) and `'\f'`(`TriviaKind::Formfeed`) support.
* ~Added `TriviaKind::StartOfFile` that is convenient for `TokenSyntax::isAtStartOfLine()` implementation~.
* ~Added `TriviaKind::Hashbang` that is for `#!/path/to/swift`~
* Added `TriviaKind::GarbageText` for any skipped text, and use it for hashbang. e.g.`#!/path/to/swift`
* Privatized `TriviaPiece` constructor and member fields so that we don't accidentaly create invalid trivia piece like: ` { TriviaKind::lineComment, 6, "foobar" }`

TODO/FIXME:
* Handle random nul(`\0`) character in the middle of a buffer.
* Handle random invalid UTF8 sequence which is skipped (not tokenized as `tok::unknown`) in `lexImpl()`
* Distinguish between CR(`\r`) and LF(`\n`)
* Support DOS newline (CR+LF). This sequence should form one trivia piece (instead of 2).

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test OS X platform

**Comment by harlanhaskins** [comment]
This looks good! You’ll also need to add equivalent declarations in `SwiftSyntax/Trivia.swift`.

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test Linux platform

**Comment by rintaro** [comment]
@swift-ci Please ASAN test

**Comment by rintaro** [comment]
@nkcsgexi Could you review this?
FYI, the last commit is https://github.com/apple/swift/pull/13248#discussion_r154718664

**Comment by nkcsgexi** [comment]
Hi @rintaro , I like the part you simplified `lexTrivia`. For the newly added trivia kinds, i'm concerned since they have their own constraints, i.e. they must appear at the beginning of a file. This makes them outliers comparing to other trivia kinds which can appear at any places in the source file.

This is not a big deal if trivia kinds are internal implementation details of libSyntax. However, they are not. Our clients will know them and start to use them. Do they have to insert `TriviaKind::StartOfFile` in any programmatically created SourceFile? What if they forget to add `TriviaKind::StartOfFile` at the start of a file? What if they insert `TriviaKind::StartOfFile` into a random place in a file? This seems to me that we have created a potential buggy area for our clients.

My suggestion will be avoiding add any new trivia kinds if they are not universally locatable.  We should think of a way to check `isAtStartOfLine` without adding new trivia kinds. A random thought on this: if a node is at the start of a file, does it really matter if `isAtStartOfLine` returns true or false, from clients' perspective?

**Comment by rintaro** [comment]
Thank you for reviewing @nkcsgexi !
I completely understand your concern, and I will drop `StartOfFile` thing from this PR.

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
As per offline discussion with @nkcsgexi , we decided to introduce `GarbageText` trivia for any skipped text, and use it for hashbang.

**Comment by nkcsgexi** [comment]
Thank you! @rintaro

**Pull request merged**
