### PR TITLE
Optimize Dictionary.filter for native dictionaries

### PR DESCRIPTION
**Pull request by rctcwyvrn**
Adds a fast path for filtering native dictionaries using the underlying bitset and preallocating the resulting dictionary, very similar to the optimization in `NativeSet` https://github.com/apple/swift/blob/main/stdlib/public/core/NativeSet.swift#L723

### CODE REVIEW

**Comment by rctcwyvrn** [comment]
@swift-ci please test

**Comment by rctcwyvrn** [comment]
@swift-ci please benchmark

**Review by lorentey — APPROVED** [review]
This looks great to me! I could only nitpick on a couple of style things.

To land this, we'll also need to double check that we have adequate test coverage for this function (incl. tests that cover both bridged and non-bridged dictionaries), and add tests as needed.

Similarly, we should prove that this results in a measurable performance improvement by adding a new benchmark! (Provided we don't have one already)

**Comment by rctcwyvrn** [comment]
@swift-ci please smoke test

**Comment by rctcwyvrn** [comment]
@swift-ci smoke test

**Comment by rctcwyvrn** [comment]
@swift-ci please smoke test

**Comment by rctcwyvrn** [comment]
@swift-ci benchmark

**Review by lorentey — APPROVED** [review]
Very nice! 🚀

**Pull request merged**
