### PR TITLE
[6.0][Macro] Get accurate dependency information for macro in explicit module build

### PR DESCRIPTION
**Pull request by cachemeifyoucan**
Explanation: Add capability for discover accurate macro plugin dependency in the dependency scanner for better swift caching build.
Scope: this fixes some issues for macro plugin lookup in swift EBM or caching build, including building interface files that has macro expansion inside or false cache miss from swift caching build.
Issue: rdar://127116512&131214106
Original PR: https://github.com/apple/swift/pull/73421 https://github.com/swiftlang/swift/pull/75082
Reviewer: @artemcm 
Risk: Low. 
Test Plan: Unit tests

### CODE REVIEW

**Comment by cachemeifyoucan** [comment]
@swift-ci please test

**Comment by cachemeifyoucan** [comment]
@swift-ci please test

**Comment by cachemeifyoucan** [comment]
@swift-ci please test

**Comment by cachemeifyoucan** [comment]
@swift-ci please test

**Comment by cachemeifyoucan** [comment]
@swift-ci please test

**Comment by cachemeifyoucan** [comment]
@swift-ci please test

**Review by nkcsgexi — APPROVED** [review]

**Pull request merged**
