### PR TITLE
[5.0][android] Link with static C++ ABI for Android.

### PR DESCRIPTION
**Pull request by drodriguez**
Normally, the C++ shared library would have link against the C++ ABI
shared library, but the Android NDK does not distribute the later, so
one need to link manually against the static C++ ABI from the NDK.

Cherry-picked from #21314

/cc @compnerd

### CODE REVIEW

**Comment by compnerd** [comment]
@apple/swift5-branch-managers (@tkremenek as proxy, since I can't tag them) ... this is relatively low risk.  It alters only the android path and adds an additional linked entity.  Without this link, certain code constructs may fail to link or run due to missing symbols.  Normally, libc++ would link against libc++abi, but it does not do so on android.  Because we are statically linking here, any issue would appear at build time and should be safe as long as it builds.

**Comment by compnerd** [comment]
@swift-ci please test

**Review by bob-wilson — APPROVED** [review]

**Comment by bob-wilson** [comment]
This looks fine to me, but let's wait to merge it until the PR for master is merged, just in case there is some unexpected fallout.

**Comment by compnerd** [comment]
@swift-ci please test

**Pull request merged**
