### PR TITLE
[6.0] Bump the deployment target for the compiler to macOS 13.0 

### PR DESCRIPTION
**Pull request by benlangmuir**
Cherry-pick recent changes to bump the deployment target to macOS-13 aligned versions, with the exception of watchOS which is held back to 6.0 to keep supporting armv7k and the i386 simulator for now.

---

* **Explanation**: Bumps our default deployment target on Darwin platforms from macOS 10.13 to macOS 13.0, notably this is the first time it is moving past the ABI stability point. This change is a prerequisite for fixing the build of the swift compiler when using Xcode 16 (further changes to fix that build will follow from @ian-twilightcoder).  This change also fixes an issue with `CommandLine.arguments` in Swift scripts, because it allows us to stop linking `CoreFoundation` into the stdlib, which was interfering with the arguments setup. For consistency, iOS and tvOS are bumped to the aligned versions (16.0). We also bump watchOS to 6.0, which is past the ABI stability point, but is not aligned (would be 9.0) because that is currently required in order to not drop support for building code that back deploys to armv7k watch and i386 watch simulator.
* **Scope**: Increases the minimum target required to run the compiler from the swift.org distributed toolchains. Does not change the minimum target that compiler can compile code for, so long as they deploy that code to run using the OS-provided stdlib or the downloadable swift 5 stdlib package. If a developer instead bundles the stdlib dylib that is part of the swift.org toolchain into their own software, then they will be affected by the minimum target change. Note: developers building swift from source already required macOS 13, so there is no change there.
* **Resolves**: rdar://133319816
* **Original PRs**:
  * Main Change: https://github.com/swiftlang/swift/pull/75914
  * watchOS fix: https://github.com/swiftlang/swift/pull/76451
  * Small fixit improvement to fix tests: https://github.com/swiftlang/swift/pull/76018
  * Test-only changes: https://github.com/swiftlang/swift/pull/76023, https://github.com/swiftlang/swift/pull/76027, https://github.com/swiftlang/swift/pull/76132, https://github.com/swiftlang/swift/pull/76183, https://github.com/swiftlang/swift/pull/76351, https://github.com/swiftlang/swift/pull/76355, https://github.com/swiftlang/swift/pull/76407
* **Risk**: Medium. Back-deployment: while I am confident that the compiler itself and the swiftinterfaces for the stdlib will handle back deployment to pre-macOS-13-aligned targets, there is a risk that some other part of the build is affected in a way we haven't run into during testing. For example, in https://github.com/swiftlang/swift/pull/76451 we discovered an issue during linking; it's hard to exhaustively test back deployment, so there may be other issues. There is also risk of CI/development disruption. Landing this change in main has involved several follow-up test fixes to cover tests not run by PR testing. While I think most of these issues have shaken out, there may be more.
* **Testing**: Full PR tests, source compatibility testing, and toolchain build all pass. Tested manually that the toolchain can successfully compile code for macOS 10.13, iOS 11.0 and watchOS 4.0.
* **Reviewers**: @etcwilde, @shahmishal, @ian-twilightcoder

### CODE REVIEW

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please build toolchain macOS

**Comment by benlangmuir** [comment]
@swift-ci please test source compatibility

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please build toolchain macOS

**Comment by benlangmuir** [comment]
@swift-ci please test source compatibility

**Comment by shahmishal** [comment]
cc: @airspeedswift for review and approval

**Review by airspeedswift — APPROVED** [review]

**Pull request merged**
