### PR TITLE
 Allow for passing a custom Archetype naming schema to the demangler.

### PR DESCRIPTION
**Pull request by adrian-prantl**
Cherry-pick of https://github.com/apple/swift/pull/22954
rdar://problem/48259889

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Review by slavapestov — COMMENTED** [review]
Can we call them generic parameters and not "archetypes" here?

**Comment by adrian-prantl** [comment]
Are you saying that we should rename `swift::Demangle::archetypeName()` to `swift::Demangle::genericParameterName()`?

I'm happy to do that, I just always thought that `T` was an Archetype and `τ_0_0` was a generic parameter, so it would be the name of the Archetype...

**Comment by slavapestov** [comment]
Yeah, I would prefer if we not use the term "archetype" in the demangler at all. It's an implementation detail of the compiler.

**Comment by adrian-prantl** [comment]
Works for me. I'll open a separate PR to rename everything.

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Pull request merged**
