### PR TITLE
[stdlib] Fix FloatingPoint.init(exactly:)

### PR DESCRIPTION
**Pull request by natecook1000**
This is another attempt at fixing this initializer — #11311 had to be reverted after a test failure that didn't show up during CI.

### CODE REVIEW

**Comment by natecook1000** [comment]
Please test with following pull request:
https://github.com/apple/swift-corelibs-foundation/pull/1293

@swift-ci Please test

**Comment by natecook1000** [comment]
Please test with following pull request:
apple/swift-corelibs-foundation#1293

@swift-ci Please test

**Comment by natecook1000** [comment]
Please test with following pull request:
https://github.com/apple/swift-corelibs-foundation/pull/1293

@swift-ci Please test Linux platform

**Comment by natecook1000** [comment]
Please test with following pull request:
https://github.com/apple/swift-corelibs-foundation/pull/1293

@swift-ci Please test Linux platform

**Comment by natecook1000** [comment]
@gparker42 What do you think? I think the issue last time was that smoke tests don't run the 32-bit simulator tests—this should be in a better state.

**Comment by gparker42** [comment]
That sounds plausible. I see that the tests here ran on watchOS simulator which should cover 32-bit.

The only difference between this and #11311 is test changes, correct?

**Comment by natecook1000** [comment]
That's right—it's just what's in that last commit.

**Comment by gparker42** [comment]
Thanks, Nate.

**Pull request merged**
