### PR TITLE
Remove the hash function from the runtime's exclusive access checks.

### PR DESCRIPTION
**Pull request by atrick**
I expect this to improve the following Onone benchmarks:
- 1.09x accessGlobal
- 1.08x accessInMatSet
- 1.06x accessIndependent

And the preexisting benchmarks:

```
| TEST                    | DELTA | SPEEDUP   |
|                         |       |           |
| Random                  | -7.9% | **1.09x** |
| MatMul                  | -7.6% | **1.08x** |
| XorShift                | -7.2% | **1.08x** |
| PolymorphicCalls        | -6.2% | **1.07x** |
| NopDeinit               | -6.1% | **1.06x** |
| Ary                     | -6.0% | **1.06x** |
| Integrate               | -5.8% | **1.06x** |
| StringWalk              | -5.5% | **1.06x** |
| ArrayInClass            | -5.2% | **1.06x** |
| MultiFileTogether       | -5.2% | **1.06x** |
| DictionaryHashableClass | -5.2% | **1.05x** |
| MultiFileSeparate       | -4.9% | **1.05x** |

```

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
@swift-ci smoke benchmark.

**Comment by atrick** [comment]
@shahmishal CI benchmark is not kicking off.
Merging now in hopes that a perf bot will pick up the change.

**Review by rjmccall — COMMENTED** [review]
LGTM.

**Pull request merged**
