### PR TITLE
[5.9] Enable macros on Windows

### PR DESCRIPTION
**Pull request by bnbarham**
Use WiX to extract a future toolchain to allow building the macros support when building the toolchain. We build swift-syntax and now wire that into the build itself.

### CODE REVIEW

**Comment by bnbarham** [comment]
https://github.com/apple/swift-installer-scripts/pull/246

@swift-ci please build toolchain windows platform

**Comment by tristanlabelle** [comment]
```
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\swift-ci\\jenkins\\workspace\\swift-PR-build-toolchain-windows\\build\\1\\tools\\swift\\unittests\\SourceKit\\SwiftLang\\CMakeFiles\\SourceKitSwiftLangTests.dir\\C_\\Users\\swift-ci\\jenkins\\workspace\\swift-PR-build-toolchain-windows\\llvm-project\\llvm\\resources\\.'
```

`MAX_PATH` is 260 and this path is 256 chars, so it's not clear if this is a MAX_PATH issue. However it should never have used the path `C:\\Users\\swift-ci\\jenkins\\workspace\\swift-PR-build-toolchain` since we map that to the `T:` drive. There's some realpath resolution that is still happening in here somewhere.

**Comment by bnbarham** [comment]
> However it should never have used the path C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain\build since we map that to the T: drive. There's some realpath resolution that is still happening in here somewhere.

To be clear, I reverted all the substitution changes here. But given this is in lit.py and we already substitute T:, I could add back in the lit related ones?

**Comment by bnbarham** [comment]
https://github.com/apple/llvm-project/pull/7513
https://github.com/apple/swift-installer-scripts/pull/246

@swift-ci please build toolchain windows platform

**Comment by tristanlabelle** [comment]
@bnbarham I think we need this change from your previous PR:

image

This is what caused the expansion of the T:\ build directory I believe.

**Comment by bnbarham** [comment]
I don't think we can take that one, or at least if we did we'd have to split it to do only the `swift_obj_root`. Otherwise we'll get mismatches with SOURCE_DIR like we were seeing in the previous PR

**Comment by bnbarham** [comment]
> Otherwise we'll get mismatches with SOURCE_DIR like we were seeing in the previous PR

Ah, that's not true because we aren't adding the substitute directory here.

**Comment by bnbarham** [comment]
https://github.com/apple/llvm-project/pull/7513
https://github.com/apple/swift-installer-scripts/pull/246

@swift-ci please build toolchain windows platform

**Comment by hyp** [comment]
> @hyp Any idea about this test failure? I'm out of my depth. It seems like the C++ interop method is called with typed instead of untyped parameters? 🤔

I'm not sure why this test is failing on this run of building the toolchain, perhaps this test is somehow missed by regular windows PR CI? In any case, this failure is due to the test assuming opaque pointer types are enabled in LLVM, but the 5.9 LLVM branch assumes that opaque pointer types are not enabled. I think it's fine to fixup the test case's CHECK line in this patch.

**Comment by bnbarham** [comment]
https://github.com/apple/llvm-project/pull/7513
https://github.com/apple/swift-installer-scripts/pull/246

@swift-ci please build toolchain windows platform

**Comment by bnbarham** [comment]
Thanks @hyp! Re-running with those changes now.

**Comment by bnbarham** [comment]
https://github.com/apple/llvm-project/pull/7513
https://github.com/apple/swift-installer-scripts/pull/246

@swift-ci please build toolchain windows platform

**Comment by bnbarham** [comment]
https://github.com/apple/llvm-project/pull/7513
https://github.com/apple/swift-installer-scripts/pull/246

@swift-ci please test

**Review by tristanlabelle — APPROVED** [review]

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
