### PR TITLE
Add missing newlines

### PR DESCRIPTION
**Pull request by johnno1962**
Hi Apple,

Just a bit of gardening adding newlines to the three files that give a warning building in Xcode.

Cheers

### CODE REVIEW

**Review by compnerd — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please smoke test and merge

**Comment by johnno1962** [comment]
WTF?

**Comment by compnerd** [comment]
@swift-ci please smoke test macOS platform

**Comment by johnno1962** [comment]
Odd problem. Only one failure this time. Third time’s a charm?

**Comment by johnno1962** [comment]
Thanks folks

**Pull request merged**
