### PR TITLE
[5.0] IRGen: Test all of the payload bits if there are not extra inhabitants

### PR DESCRIPTION
**Pull request by eeckstein**
rdar://49380548

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by tkremenek** [comment]
@swift-ci clean test

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by aschwaighofer** [comment]
@jckarter Can you review this?

**Review by jckarter — APPROVED** [review]
LGTM, thanks!

**Review by tkremenek — APPROVED** [review]

**Pull request merged**
