### PR TITLE
Rename pointer bounds

### PR DESCRIPTION
**Pull request by hnrklssn**
Renames the `@PointerBounds` macro to `@_SwiftifyImport` and makes it generally available in the standard library. The API is expected to change drastically without accompanying release notes or backwards compatibility, as the macro is intended to be applied by ClangImporter only, which will be updated in tandem with the macro.

### CODE REVIEW

**Comment by hnrklssn** [comment]
@swift-ci please smoke test

**Comment by hnrklssn** [comment]
@swift-ci please smoke test

**Review by Xazax-hun — APPROVED** [review]

**Review by DougGregor — APPROVED** [review]
LGTM, thanks!

**Comment by hnrklssn** [comment]
@swift-ci please smoke test

**Comment by hnrklssn** [comment]
@swift-ci please smoke test

**Comment by hnrklssn** [comment]
> > I took the liberty of not adding @available to _PointerParam, since it's not really intended to be "available" at runtime, only for passing info to the macro. Please let me know if that has any consequences I'm not aware of.
> 
> Availability is needed on every declaration that might be linked by a separate executable (so that the compiler can generate correct linkage relative to the deployment target of the executable for the symbols). Even if the only separate executables that reference it are macro plugins, I think it may still be appropriate to have accurate availability.

How does this work for the stdlib? If I simply try adding `@available(SwiftStdlib 6.1, *)`  to `_PointerParam`, then I get an error saying `error: '_PointerParam' is only available in macOS 9999 or newer` when building the stdlib for the host OS. I thought custom built swiftc was supposed to build with availability for all releases?

**Comment by hnrklssn** [comment]
@swift-ci please test linux

**Comment by hnrklssn** [comment]
Could this test failure actually be related to my changes?
```
FAIL: test_command_stats_force (TestStatisticsAPI.TestStatsAPI)
   Test reporting all pssible debug info stats by force loading all debug
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/build-user/llvm-project/lldb/test/API/functionalities/stats_api/TestStatisticsAPI.py", line 151, in test_command_stats_force
    self.assertEqual(debug_stats["totalDebugInfoByteSize"], 193)
AssertionError: 386 != 193
```

It doesn't seem like something that should be affected, but maybe I'm missing something. It seems like other PRs are passing fine.

**Comment by Xazax-hun** [comment]
> Could this test failure actually be related to my changes?

I remember seeing this on other PRs. I think you should just rerun the tests, hopefully should be fixed by now.

**Comment by tshortli** [comment]
> How does this work for the stdlib? If I simply try adding @available(SwiftStdlib 6.1, *) to _PointerParam, then I get an error saying error: '_PointerParam' is only available in macOS 9999 or newer when building the stdlib for the host OS. I thought custom built swiftc was supposed to build with availability for all releases?

`SwiftStdlib 6.1` maps to OS version `9999` as a temporary placeholder on all platforms since Swift 6.1 has not yet been released with any Apple OS release. It will eventually be updated to map to a real version. Every context that refers to `_PointerParam` needs to be constrained to `SwiftStdlib 6.1` too. It would be helpful to see the specific instances of `error: '_PointerParam' is only available in macOS 9999 or newer` you are seeing in order to decided what needs to be done about each.

**Comment by hnrklssn** [comment]
> > How does this work for the stdlib? If I simply try adding @available(SwiftStdlib 6.1, *) to _PointerParam, then I get an error saying error: '_PointerParam' is only available in macOS 9999 or newer when building the stdlib for the host OS. I thought custom built swiftc was supposed to build with availability for all releases?
> 
> `SwiftStdlib 6.1` maps to OS version `9999` as a temporary placeholder on all platforms since Swift 6.1 has not yet been released with any Apple OS release. It will eventually be updated to map to a real version. Every context that refers to `_PointerParam` needs to be constrained to `SwiftStdlib 6.1` too. It would be helpful to see the specific instances of `error: '_PointerParam' is only available in macOS 9999 or newer` you are seeing in order to decided what needs to be done about each.

Here are two of the errors I'm getting, if that helps:
```
[3/123] Generating /Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/lib/swift/embedded/Swift.swiftmodule/arm64-apple-macos.swiftmodule
FAILED: lib/swift/embedded/Swift.swiftmodule/arm64-apple-macos.swiftmodule lib/swift/embedded/Swift.swiftmodule/arm64-apple-macos.swiftdoc /Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/lib/swift/embedded/Swift.swiftmodule/arm64-apple-macos.swiftmodule /Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/lib/swift/embedded/Swift.swiftmodule/arm64-apple-macos.swiftdoc
cd /Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/stdlib/public/core && /Volumes/UserData/Apps/XcodeSwift.app/Contents/Developer/usr/local/bin/cmake -E make_directory /Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/stdlib/public/core/embedded/arm64 && /Volumes/UserData/Apps/XcodeSwift.app/Contents/Developer/usr/local/bin/cmake -E remove -f /Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/lib/swift/embedded/Swift.swiftmodule/arm64-apple-macos.swiftmodule /Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/lib/swift/embedded/Swift.swiftmodule/arm64-apple-macos.swiftdoc && /Volumes/UserData/Apps/XcodeSwift.app/Contents/Developer/usr/local/bin/cmake -E make_directory /Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/lib/swift/embedded /Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/lib/swift/embedded/Swift.swiftmodule && /Volumes/UserData/Apps/XcodeSwift.app/Contents/Developer/usr/local/bin/cmake -E env PYTHONIOENCODING=UTF8 /opt/homebrew/Frameworks/Python.framework/Versions/3.12/bin/python3.12 /Volumes/UserData/Code/src-swift-upstream/swift/utils/line-directive @/Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/stdlib/public/core/27fffbbc629ab2c4d5a0289f83fc862fd303eaf0.txt -- /Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/./bin/swiftc -emit-module -o /Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/lib/swift/embedded/Swift.swiftmodule/arm64-apple-macos.swiftmodule -avoid-emit-module-source-info -target arm64-apple-macos14 -resource-dir /Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/./lib/swift -O -g -D INTERNAL_CHECKS_ENABLED -D SWIFT_ENABLE_EXPERIMENTAL_CONCURRENCY -D SWIFT_ENABLE_EXPERIMENTAL_DISTRIBUTED -D SWIFT_ENABLE_RUNTIME_FUNCTION_COUNTERS -D SWIFT_ENABLE_EXPERIMENTAL_DIFFERENTIABLE_PROGRAMMING -D SWIFT_ENABLE_EXPERIMENTAL_STRING_PROCESSING -D SWIFT_ENABLE_EXPERIMENTAL_OBSERVATION -D SWIFT_ENABLE_SYNCHRONIZATION -D SWIFT_ENABLE_VOLATILE -D SWIFT_RUNTIME_OS_VERSIONING -D SWIFT_STDLIB_ENABLE_UNICODE_DATA -D SWIFT_STDLIB_HAS_COMMANDLINE -D SWIFT_STDLIB_HAS_STDIN -D SWIFT_STDLIB_HAS_ENVIRON -Xcc -DSWIFT_STDLIB_HAS_ENVIRON -D SWIFT_CONCURRENCY_USES_DISPATCH -D SWIFT_STDLIB_OVERRIDABLE_RETAIN_RELEASE -D SWIFT_THREADING_ -tools-directory /Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/llvm-macosx-arm64/./bin -module-cache-path /Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/./module-cache -no-link-objc-runtime -Xfrontend -enforce-exclusivity=unchecked -nostdimport -parse-stdlib -module-name Swift -Xfrontend -group-info-path -Xfrontend /Volumes/UserData/Code/src-swift-upstream/swift/stdlib/public/core/GroupInfo.json -swift-version 5 -Xfrontend -empty-abi-descriptor -runtime-compatibility-version none -disable-autolinking-runtime-compatibility-dynamic-replacements -Xfrontend -disable-autolinking-runtime-compatibility-concurrency -Xfrontend -disable-objc-interop -enable-experimental-feature NoncopyableGenerics2 -enable-experimental-feature SuppressedAssociatedTypes -enable-experimental-feature SE427NoInferenceOnExtension -enable-experimental-feature AllowUnsafeAttribute -enable-experimental-feature NonescapableTypes -enable-experimental-feature LifetimeDependence -enable-upcoming-feature MemberImportVisibility -Xllvm -sil-inline-generics -Xllvm -sil-partial-specialization -Xfrontend -enable-experimental-concise-pound-file -enable-experimental-feature Macros -enable-experimental-feature FreestandingMacros -enable-experimental-feature Extern -enable-experimental-feature BitwiseCopyable -plugin-path /Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/./bin/../lib/swift/host/plugins -Xcc -D__MACH__ -Xcc -D__APPLE__ -Xcc -ffreestanding -enable-experimental-feature Embedded -Xfrontend -enable-ossa-modules -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 9999:macOS\ 9999,\ iOS\ 9999,\ watchOS\ 9999,\ tvOS\ 9999 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.0:macOS\ 10.14.4,\ iOS\ 12.2,\ watchOS\ 5.2,\ tvOS\ 12.2 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.1:macOS\ 10.15,\ iOS\ 13.0,\ watchOS\ 6.0,\ tvOS\ 13.0 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.2:macOS\ 10.15.4,\ iOS\ 13.4,\ watchOS\ 6.2,\ tvOS\ 13.4 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.3:macOS\ 11.0,\ iOS\ 14.0,\ watchOS\ 7.0,\ tvOS\ 14.0 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.4:macOS\ 11.3,\ iOS\ 14.5,\ watchOS\ 7.4,\ tvOS\ 14.5 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.5:macOS\ 12.0,\ iOS\ 15.0,\ watchOS\ 8.0,\ tvOS\ 15.0 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.6:macOS\ 12.3,\ iOS\ 15.4,\ watchOS\ 8.5,\ tvOS\ 15.4 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.7:macOS\ 13.0,\ iOS\ 16.0,\ watchOS\ 9.0,\ tvOS\ 16.0 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.8:macOS\ 13.3,\ iOS\ 16.4,\ watchOS\ 9.4,\ tvOS\ 16.4 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.9:macOS\ 14.0,\ iOS\ 17.0,\ watchOS\ 10.0,\ tvOS\ 17.0 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.10:macOS\ 14.4,\ iOS\ 17.4,\ watchOS\ 10.4,\ tvOS\ 17.4,\ visionOS\ 1.1 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 6.0:macOS\ 15.0,\ iOS\ 18.0,\ watchOS\ 11.0,\ tvOS\ 18.0,\ visionOS\ 2.0 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 6.1:macOS\ 9999,\ iOS\ 9999,\ watchOS\ 9999,\ tvOS\ 9999,\ visionOS\ 9999 -Xfrontend -target-min-inlining-version -Xfrontend min -module-link-name swiftCore -whole-module-optimization -color-diagnostics -parse-as-library -resource-dir /Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/./lib/swift -I /Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/./lib/swift/embedded @/Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/stdlib/public/core/27fffbbc629ab2c4d5a0289f83fc862fd303eaf0.txt
/Volumes/UserData/Code/src-swift-upstream/swift/stdlib/public/core/SwiftifyImport.swift:44:43: error: '_PointerParam' is only available in macOS 9999 or newer
42 | /// safety of the generated wrapper function depends on this info being extensive and accurate.
43 | @attached(peer, names: overloaded)
44 | public macro _SwiftifyImport(_ paramInfo: _PointerParam...) =
   |                                           `- error: '_PointerParam' is only available in macOS 9999 or newer
45 |     #externalMacro(module: "SwiftMacros", type: "SwiftifyImportMacro")
46 |
[4/123] Compiling /Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/stdlib/public/core//OSX/arm64/Swift.o
FAILED: stdlib/public/core/OSX/arm64/Swift.o /Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/stdlib/public/core/OSX/arm64/Swift.o
cd /Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/stdlib/public/core && /Volumes/UserData/Apps/XcodeSwift.app/Contents/Developer/usr/local/bin/cmake -E make_directory /Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/stdlib/public/core/OSX/arm64 && /Volumes/UserData/Apps/XcodeSwift.app/Contents/Developer/usr/local/bin/cmake -E env PYTHONIOENCODING=UTF8 /opt/homebrew/Frameworks/Python.framework/Versions/3.12/bin/python3.12 /Volumes/UserData/Code/src-swift-upstream/swift/utils/line-directive @/Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/stdlib/public/core/d79e9d84479b1e7dbc011ca667dcf264c8d1f672.txt -- /Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/./bin/swiftc -c -sdk /Volumes/UserData/Apps/XcodeSwift.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk -target arm64-apple-macosx13.0 -resource-dir /Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/./lib/swift -F/Volumes/UserData/Apps/XcodeSwift.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk/../../../Developer/Library/Frameworks -O -g -D INTERNAL_CHECKS_ENABLED -D SWIFT_ENABLE_EXPERIMENTAL_CONCURRENCY -D SWIFT_ENABLE_EXPERIMENTAL_DISTRIBUTED -D SWIFT_ENABLE_RUNTIME_FUNCTION_COUNTERS -D SWIFT_ENABLE_EXPERIMENTAL_DIFFERENTIABLE_PROGRAMMING -D SWIFT_ENABLE_EXPERIMENTAL_STRING_PROCESSING -D SWIFT_ENABLE_EXPERIMENTAL_OBSERVATION -D SWIFT_ENABLE_SYNCHRONIZATION -D SWIFT_ENABLE_VOLATILE -D SWIFT_RUNTIME_OS_VERSIONING -D SWIFT_STDLIB_ENABLE_UNICODE_DATA -D SWIFT_STDLIB_ENABLE_VECTOR_TYPES -D SWIFT_STDLIB_HAS_COMMANDLINE -D SWIFT_STDLIB_HAS_STDIN -D SWIFT_STDLIB_HAS_ENVIRON -Xcc -DSWIFT_STDLIB_HAS_ENVIRON -D SWIFT_CONCURRENCY_USES_DISPATCH -D SWIFT_STDLIB_OVERRIDABLE_RETAIN_RELEASE -D SWIFT_THREADING_DARWIN -tools-directory /Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/llvm-macosx-arm64/./bin -module-cache-path /Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/./module-cache -no-link-objc-runtime -enable-library-evolution -library-level api -Xfrontend -require-explicit-availability=ignore -Xfrontend -enforce-exclusivity=unchecked -D SWIFT_ENABLE_REFLECTION -nostdimport -parse-stdlib -module-name Swift -Xfrontend -group-info-path -Xfrontend /Volumes/UserData/Code/src-swift-upstream/swift/stdlib/public/core/GroupInfo.json -swift-version 5 -Xfrontend -empty-abi-descriptor -runtime-compatibility-version none -disable-autolinking-runtime-compatibility-dynamic-replacements -Xfrontend -disable-autolinking-runtime-compatibility-concurrency -enable-experimental-feature NoncopyableGenerics2 -enable-experimental-feature SuppressedAssociatedTypes -enable-experimental-feature SE427NoInferenceOnExtension -enable-experimental-feature AllowUnsafeAttribute -enable-experimental-feature NonescapableTypes -enable-experimental-feature LifetimeDependence -enable-upcoming-feature MemberImportVisibility -Xllvm -sil-inline-generics -Xllvm -sil-partial-specialization -Xfrontend -enable-experimental-concise-pound-file -enable-experimental-feature Macros -enable-experimental-feature FreestandingMacros -enable-experimental-feature Extern -enable-experimental-feature BitwiseCopyable -plugin-path /Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/./bin/../lib/swift/host/plugins -Xcc -DswiftCore_EXPORTS -warn-implicit-overrides -Xfrontend -enable-lexical-lifetimes=false -Xfrontend -enable-ossa-modules -Xfrontend -disable-implicit-concurrency-module-import -Xfrontend -disable-implicit-string-processing-module-import -Xfrontend -disable-implicit-backtracing-module-import -Xfrontend -prespecialize-generic-metadata -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 9999:macOS\ 9999,\ iOS\ 9999,\ watchOS\ 9999,\ tvOS\ 9999 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.0:macOS\ 10.14.4,\ iOS\ 12.2,\ watchOS\ 5.2,\ tvOS\ 12.2 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.1:macOS\ 10.15,\ iOS\ 13.0,\ watchOS\ 6.0,\ tvOS\ 13.0 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.2:macOS\ 10.15.4,\ iOS\ 13.4,\ watchOS\ 6.2,\ tvOS\ 13.4 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.3:macOS\ 11.0,\ iOS\ 14.0,\ watchOS\ 7.0,\ tvOS\ 14.0 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.4:macOS\ 11.3,\ iOS\ 14.5,\ watchOS\ 7.4,\ tvOS\ 14.5 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.5:macOS\ 12.0,\ iOS\ 15.0,\ watchOS\ 8.0,\ tvOS\ 15.0 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.6:macOS\ 12.3,\ iOS\ 15.4,\ watchOS\ 8.5,\ tvOS\ 15.4 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.7:macOS\ 13.0,\ iOS\ 16.0,\ watchOS\ 9.0,\ tvOS\ 16.0 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.8:macOS\ 13.3,\ iOS\ 16.4,\ watchOS\ 9.4,\ tvOS\ 16.4 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.9:macOS\ 14.0,\ iOS\ 17.0,\ watchOS\ 10.0,\ tvOS\ 17.0 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 5.10:macOS\ 14.4,\ iOS\ 17.4,\ watchOS\ 10.4,\ tvOS\ 17.4,\ visionOS\ 1.1 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 6.0:macOS\ 15.0,\ iOS\ 18.0,\ watchOS\ 11.0,\ tvOS\ 18.0,\ visionOS\ 2.0 -Xfrontend -define-availability -Xfrontend SwiftStdlib\ 6.1:macOS\ 9999,\ iOS\ 9999,\ watchOS\ 9999,\ tvOS\ 9999,\ visionOS\ 9999 -Xfrontend -target-min-inlining-version -Xfrontend min -module-link-name swiftCore -whole-module-optimization -save-optimization-record=bitstream -color-diagnostics -parse-as-library -resource-dir /Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/./lib/swift -I /Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/./lib/swift/macosx -o /Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/stdlib/public/core//OSX/arm64/Swift.o @/Volumes/UserData/Code/src-swift-upstream/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/stdlib/public/core/d79e9d84479b1e7dbc011ca667dcf264c8d1f672.txt
/Volumes/UserData/Code/src-swift-upstream/swift/stdlib/public/core/SwiftifyImport.swift:44:43: error: '_PointerParam' is only available in macOS 9999 or newer
42 | /// safety of the generated wrapper function depends on this info being extensive and accurate.
43 | @attached(peer, names: overloaded)
44 | public macro _SwiftifyImport(_ paramInfo: _PointerParam...) =
   |                                           `- error: '_PointerParam' is only available in macOS 9999 or newer
45 |     #externalMacro(module: "SwiftMacros", type: "SwiftifyImportMacro")
46 |
```

**Comment by DougGregor** [comment]
> Availability is needed on every declaration that might be linked by a separate executable (so that the compiler can generate correct linkage relative to the deployment target of the executable for the symbols). Even if the only separate executables that reference it are macro plugins, I think it may still be appropriate to have accurate availability.

These declarations are weird, because they are used in the arguments to the new macro but aren't part of the expansion and shouldn't ever be used outside of those macro arguments. We'd like them not to have availability at all, because the macros themselves should be usable on early deployment targets (some of the things they expand to might require newer deployment targets, but that's fine).

**Comment by tshortli** [comment]
Doesn't the macro plugin itself need to link the symbols associated with `_PointerParam` though?

**Comment by DougGregor** [comment]
> Doesn't the macro plugin itself need to link the symbols associated with `_PointerParam` though?

The macro plugin is going to need to have its own version of any of these types, so that it itself is not deployment-target-gated.

**Comment by tshortli** [comment]
Ok, if `_PointerParam` is not expected to be linked dynamically by any back-deployable binaries then leaving availability off for convenience seems fine, but I do think the type it deserves at least a comment explaining all of this in case anyone has to investigate a scenario where these fragile assumptions have been violated.

**Comment by hnrklssn** [comment]
> some of the things they expand to might require newer deployment targets

This raises the question: do we want macro expansions with `Span` annotated with `@available`? My thinking is yes, so we can apply the macro in all contexts without causing compilation errors when Span isn't available.

**Comment by hnrklssn** [comment]
@swift-ci please smoke test

**Comment by hnrklssn** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
> > some of the things they expand to might require newer deployment targets
> 
> This raises the question: do we want macro expansions with `Span` annotated with `@available`? My thinking is yes, so we can apply the macro in all contexts without causing compilation errors when Span isn't available.

Yes, the functions we generate that use Span will have to have appropriate availability. (That can, of course, but a follow-up)

**Pull request merged**
