### PR TITLE
[master-next] Fix master-next build

### PR DESCRIPTION
**Pull request by bulbazord**
cc @xymus

### CODE REVIEW

**Review by xymus — APPROVED** [review]
Thank you!

**Comment by xymus** [comment]
@swift-ci please smoke test

**Comment by xymus** [comment]
There might have been a conflict with a change on master (#30678) to address the previous error on `moduleName = getUnderlyingModuleName(mod, initialFile);`.

**Comment by xiaobai** [comment]
I'll rebase my change on top of master-next

**Comment by xiaobai** [comment]
@swift-ci please smoke test

**Comment by xiaobai** [comment]
@swift-ci please smoke test

**Comment by xiaobai** [comment]
@swift-ci please smoke test

**Comment by xiaobai** [comment]
@swift-ci please smoke test

**Comment by xymus** [comment]
Compiled fine and it looks like only one unrelated test is failing on macOS. Thank you @xiaobai!

**Pull request merged**
