### PR TITLE
[AutoDiff] Use auto-generated locations for temporary allocations.

### PR DESCRIPTION
**Pull request by rxwei**
In `TangentBuilder` temporary allocations are emitted in order to make generic calls to `AdditiveArithmetic.zero` and `AdditiveArithmetic.+`. When we perform accumulation of two adjoint values that correspond to a lexical value in the original function, the stack allocations require a debug variable, as we use the original instruction's location. However such a debug variable wouldn't really make sense as these temporary allocations do not represent the original variable's adjoint. With lexical borrow scopes, we hit a crasher when creating temporary allocations when accumulating adjoints for lexical `begin_borrow` instructions.

This PR makes `TangentBuilder`'s temporary allocations use an auto-generated location. The existing debug info emission behavior is not changed, as we still emit `debug_value` when materializing an `AdjointValue` after any necessary adjoint accumulation.

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please smoke test

**Comment by BradLarson** [comment]
This also resolves [SR-15566](https://bugs.swift.org/browse/SR-15566), thanks!

**Comment by gottesmm** [comment]
@rxwei you missed one it is also AutoDiff/validation-test/optional_property.swift

**Comment by rxwei** [comment]
Fixed. And added a test for SR-15566.

**Comment by rxwei** [comment]
@swift-ci please smoke test

**Comment by rxwei** [comment]
@swift-ci please test windows platform

**Review by gottesmm — APPROVED** [review]

**Pull request merged**
