### PR TITLE
[Driver, Incremental] Make dummy make-file dependencies path OK for Windows

### PR DESCRIPTION
**Pull request by davidungar**
rdar://57824038

### CODE REVIEW

**Comment by davidungar** [comment]
@swift-ci please test

**Comment by davidungar** [comment]
@swift-ci please test source compatibility

**Comment by davidungar** [comment]
@drodriguez Might be a fix for Windows

**Comment by davidungar** [comment]
@swift-ci please test windows platform

**Comment by drodriguez** [comment]
BTW, there's another two errors in the Windows testing right now. You will have to drill into the output to see if this fixes the problem.

In the meantime, I also opened #28905, in case the problem is MSVC dropping a constructor result that's not saved anywhere.

**Comment by drodriguez** [comment]
@compnerd @shahmishal : it seems that this fixes the problem with the dependencies test. It has the two closure asserts failing, and it also has the unexpected passing tests for `Driver/batch_mode_with_supplementary_filelist.swift` because of #28894.

Seems that this might be a good candidate for merging, as well as reverting #28894.

**Comment by shahmishal** [comment]
Can we pull in the revert in to this PR? (`git revert 5ab6c46e556d524bf6bc7224c7e60116099385cb`)

**Review by compnerd — APPROVED** [review]

**Comment by davidungar** [comment]
Thanks a lot, folks!

- David

**Pull request merged**
