### PR TITLE
Fix mandatory devirtualization of throwing methods

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by gottesmm** [comment]
Slava, why did you merge this? I specifically asked questions in the other PR that this was extracted from and was waiting on @rudkx's response.

**Comment by rudkx** [comment]
Re: the use of the `DeadApplies` vector:

In 730ef4138552ac2b5f6e91a5595ac77dcf19b596, I added `replaceDeadApply`. At some subsequent point I deleted the stand-alone devirutalizer pass after integrating it into the performance inliner. At a future date we reworked the pass manager, removed devirtualization from the performance inliner, and I added back a new stand-alone devirutalization pass (70938b1aeeae4f5fcdb7da55e7680d451d19c44a). In that pass I eagerly devirtualized, keeping track of the applies that needed to be deleted outside of the loop (to avoid iterator invalidation issues).

At a future date, Arnold fixed a different iterator invalidation problem (a2c64103dd0bc3d0a322133b4d7fabc04c8954b9) and split the loop up into one collecting the applies to devirtualize, and another devirutalizing those, but didn't remove the now redundant collection and removal of dead applies.

**Comment by gottesmm** [comment]
Ok. SGTM!

**Pull request merged**
