### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
Please don't put something like 90d6e8d in a PR called "Small fixes" in the future. In general, putting a bunch of unrelated patches together and calling them "small" makes it more likely that other people won't bother reviewing them.

We need some kind of process for deciding whether a source-breaking change is okay to land. I don't think "two people thought about it" is sufficient.

**Pull request merged**
