### PR TITLE
[Gardening] Cleanup TokenKinds.def

### PR DESCRIPTION
**Pull request by CodaFi**
This shepherds #6618.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please test

**Comment by CodaFi** [comment]
@xwu I can't seem to request you for review, but I've made a lot of the changes that you specified on the original patch

**Comment by harlanhaskins** [comment]
This looks really great to me. Thanks @micahhainline!

**Comment by xwu** [comment]
@CodaFi Thanks, LGTM!

**Review by benlangmuir — APPROVED** [review]
LGTM

**Comment by CodaFi** [comment]
⛵️

**Pull request merged**
