### PR TITLE
Tbi fixes 4.0 branch

### PR DESCRIPTION
**Pull request by gottesmm**
This PR contains fixes for the TBI test. It eliminates the stdlib dependencies so we will no longer have any issues related to deployment targets with this test. Since there are no more dependencies on having a stdlib, I was able to conditionalize the execution of the test on having the LLVM AArch64 code generator enabled. This ensures that normal builds will run this test, preventing further breakage.

rdar://24370377

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by jrose-apple** [comment]
Please just write this in SIL.

**Comment by jrose-apple** [comment]
(Background: Michael and I have been discussing this bug in quick bits and pieces these last few days. This "solution" is definitely too clever.)

**Comment by gottesmm** [comment]
@jrose-apple At this point, I already have this done in a .swift file and I need to unblock some other people. At a later time, I am more than happy to convert this to .sil.

**Comment by jrose-apple** [comment]
This isn't even a good fix—the branch was only there because `init(bitPattern:)` produces an optional value.

**Comment by gottesmm** [comment]
@jrose-apple I did it in SIL and fixed a few other issues...

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test and merge

**Comment by gottesmm** [comment]
@swift-ci test and merge

**Comment by jrose-apple** [comment]
Thank you!

**Pull request merged**
