### PR TITLE
build: simplify the SDK packaging step

### PR DESCRIPTION
**Pull request by compnerd**
The swift install rules now can distribute the auxiliary files which removes the dependency on the source tree.  Update the rules accordingly.

### CODE REVIEW

**Comment by etcwilde** [comment]
> ?

!

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/178

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/178

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/178

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/178

@swift-ci please build toolchain Windows platform

**Pull request merged**
