### PR TITLE
[StringMemoryTest] Reduce # of iterations down to 1M and lower memory threshold

### PR DESCRIPTION
**Pull request by DougGregor**
This test is taking way too long. Cut down on the number of iterations
from 10M to 1M. Fixes rdar://problem/48658000

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@aschwaighofer can we pare this back further? It may still be slow on some targets after this...

**Comment by aschwaighofer** [comment]
Yes. We tested that an autoreleased return value optimization takes place. If it does not happen I would expect to see linear growth.

**Comment by shahmishal** [comment]
https://ci.swift.org/job/oss-swift-pr-test/6527/

```
******************** TEST 'Swift(iphonesimulator-x86_64) :: stdlib/StringMemoryTest.swift' FAILED ********************
20:02:04 Script:
20:02:04 --
20:02:04 : 'RUN: at line 1';   rm -rf "/Users/buildnode/jenkins/workspace/oss-swift-pr-test/buildbot_incremental/swift-macosx-x86_64/validation-test-iphonesimulator-x86_64/stdlib/Output/StringMemoryTest.swift.tmp" && mkdir -p "/Users/buildnode/jenkins/workspace/oss-swift-pr-test/buildbot_incremental/swift-macosx-x86_64/validation-test-iphonesimulator-x86_64/stdlib/Output/StringMemoryTest.swift.tmp"
20:02:04 : 'RUN: at line 2';   xcrun --toolchain default --sdk '/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk' /Users/buildnode/jenkins/workspace/oss-swift-pr-test/buildbot_incremental/swift-macosx-x86_64/bin/swiftc -target x86_64-apple-ios7.0  -module-cache-path '/Users/buildnode/jenkins/workspace/oss-swift-pr-test/buildbot_incremental/swift-macosx-x86_64/swift-test-results/x86_64-apple-ios7.0/clang-module-cache' -F '/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks'  -swift-version 4   -O /Users/buildnode/jenkins/workspace/oss-swift-pr-test/swift/validation-test/stdlib/StringMemoryTest.swift -o /Users/buildnode/jenkins/workspace/oss-swift-pr-test/buildbot_incremental/swift-macosx-x86_64/validation-test-iphonesimulator-x86_64/stdlib/Output/StringMemoryTest.swift.tmp/StringMemoryTest
20:02:04 : 'RUN: at line 3';   codesign -f -s - /Users/buildnode/jenkins/workspace/oss-swift-pr-test/buildbot_incremental/swift-macosx-x86_64/validation-test-iphonesimulator-x86_64/stdlib/Output/StringMemoryTest.swift.tmp/StringMemoryTest
20:02:04 : 'RUN: at line 4';   xcrun --toolchain default --sdk '/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk' simctl spawn 'iPhone 6'  /Users/buildnode/jenkins/workspace/oss-swift-pr-test/buildbot_incremental/swift-macosx-x86_64/validation-test-iphonesimulator-x86_64/stdlib/Output/StringMemoryTest.swift.tmp/StringMemoryTest | '/usr/bin/python' '/Users/buildnode/jenkins/workspace/oss-swift-pr-test/swift/utils/PathSanitizingFileCheck' --sanitize BUILD_DIR='/Users/buildnode/jenkins/workspace/oss-swift-pr-test/buildbot_incremental/swift-macosx-x86_64' --sanitize SOURCE_DIR='/Users/buildnode/jenkins/workspace/oss-swift-pr-test/swift' --use-filecheck '/Users/buildnode/jenkins/workspace/oss-swift-pr-test/buildbot_incremental/llvm-macosx-x86_64/bin/FileCheck' /Users/buildnode/jenkins/workspace/oss-swift-pr-test/swift/validation-test/stdlib/StringMemoryTest.swift
20:02:04 --
20:02:04 Exit Code: 1
20:02:04 
20:02:04 Command Output (stderr):
20:02:04 --
20:02:04 
/Users/buildnode/jenkins/workspace/oss-swift-pr-test/swift/validation-test/stdlib/StringMemoryTest.swift:56:11: error: CHECK: expected string not found in input
20:02:04 // CHECK: success
20:02:04           ^
20:02:04 <stdin>:2:1: note: scanning from here
20:02:04 failure - should not need 10MB!
20:02:04 ^
20:02:04 <stdin>:2:3: note: possible intended match here
20:02:04 failure - should not need 10MB!
20:02:04   ^
20:02:04 
20:02:04 --
20:02:04 
20:02:04 ********************
```

**Comment by aschwaighofer** [comment]
It seems the base line memory usage of a mostly empty swift file (just the call to getrusage)  is ~6mb on mac os x and ~9mb on the x86_64 simulator.

**Comment by aschwaighofer** [comment]
#23146

**Pull request merged**
