### PR TITLE
[AutoDiff] NFC: No longer use SIL loader.

### PR DESCRIPTION
**Pull request by rxwei**

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux CPU

**Comment by rxwei** [comment]
@swift-ci please test tensorflow macOS

**Review by lattner — APPROVED** [review]
How can I not love this patch (assuming it works)?  Can you please update the other similar places we're doing this as well, e.g. constexpr?

**Comment by slavapestov** [comment]
Thanks!

**Comment by rxwei** [comment]
@slavapestov There's a bug though. Calling `lookupFunctionInWitnessTable` only succeeds when I have already called `module.getSILLoader()`, which lazily constructs a loader. Otherwise it traps.

```
Assertion failed: (F->isAvailableExternally() && "external declaration of internal SILFunction not allowed"), function visitSILFunction, file /Users/rxwei/Development/Swift/swift-tf-source/swift/lib/SIL/SILVerifier.cpp, line 4857.
0  swift                    0x00000001095c4b98 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 40
1  swift                    0x00000001095c3b06 llvm::sys::RunSignalHandlers() + 198
2  swift                    0x00000001095c5222 SignalHandler(int) + 258
3  libsystem_platform.dylib 0x00007fff7b63ef5a _sigtramp + 26
4  libdyld.dylib            0x00007fff7b330149 dyldGlobalLockRelease() + 0
5  libsystem_c.dylib        0x00007fff7b3dc1ae abort + 127
6  libsystem_c.dylib        0x00007fff7b3a41ac basename_r + 0
7  swift                    0x00000001063722c3 (anonymous namespace)::SILVerifier::visitSILFunction(swift::SILFunction*) + 483
8  swift                    0x000000010636b2d9 (anonymous namespace)::SILVerifier::verify() + 25
9  swift                    0x000000010636b248 swift::SILFunction::verify(bool) const + 88
10 swift                    0x000000010636f01b swift::SILModule::verify() const + 443
11 swift                    0x0000000106b13987 swift::SerializedSILLoader::SerializedSILLoader(swift::ASTContext&, swift::SILModule*, swift::SerializedSILLoader::Callback*) + 679
12 swift                    0x0000000106b13c7d swift::SerializedSILLoader::SerializedSILLoader(swift::ASTContext&, swift::SILModule*, swift::SerializedSILLoader::Callback*) + 45
13 swift                    0x00000001062af121 swift::SerializedSILLoader::create(swift::ASTContext&, swift::SILModule*, swift::SerializedSILLoader::Callback*) + 81
```

**Pull request merged**
