### PR TITLE
[benchmark] More Robust Benchmark_Driver

### PR DESCRIPTION
**Pull request by palimondo**
> [Robust statistics](https://en.wikipedia.org/wiki/Robust_statistics) are statistics with good performance for data drawn from a wide range of probability distributions, especially for distributions that are not normal.

This PR improves the benchmark measurement methodology used by **`Benchmark_Driver`**, as originally outlined in [Towards Robust Performance Measurement](https://forums.swift.org/t/towards-robust-performance-measurement/11490/). Building on the `Benchmark_O`'s quantile report format from PR #19328, it now collects representative sub-sample (exact measurements up to sample size of 21, [ventiles](https://en.wiktionary.org/wiki/ventile) plus min and max for larger sample sizes) from benchmark measurements, which is filtered to exclude outliers (values higher than [Q3 + 1.5 * IQR](https://en.wikipedia.org/wiki/Interquartile_range#Outliers)) and combined into one empirical distribution by merging results from `-i` independent samples. The long form of this argument is renamed from misleading `--iterations` to **`--independent-samples`**. The log output format is changed to report [Five-number summary](https://en.wikipedia.org/wiki/Five-number_summary), replacing mean and standard deviation (not applicable, because the underlying distribution is non-normal) by quartiles.

To facilitate this change, the **`Benchmark_O`** was modified to use the same auto-scaling mechanism, previously used to determine number of iterations, to collect variable number of samples based on the `--sample-time` argument, when `--num-iters=1`. This type of measurement, without averaging of multiple values into the reported runtimes, is now used by the `Benchmark_Driver`. It now also reports time to run the `setUpFunction` in the `--verbose` mode.

Additional changes required to enable the above:
* `LogParser` support for parsing:
    * benchmark report summary in **quantile** format,
    * **setup** function timing, and **yields** from the `--verbose` output of `Benchmark_O`.
* **`BenchmarkDoctor`** validation:
    * new rule to enforce sensible runtimes for `setUpFunction`,
    * modified recommended runtime to be <1ms, runtimes >10ms are reported as errors.
----
I've structured the PR as a series of small, incremental changes with detailed descriptions in the commit messages, it is therefore best [**reviewed sequentially by individual commits**](https://github.com/apple/swift/pull/19910/commits/9d9200e9eb6187240e54b13f7398007be57996e8).

### CODE REVIEW

**Comment by palimondo** [comment]
@eeckstein Please review. Please also run full test, to exercise the benchmark tests.

**Comment by palimondo** [comment]
I'm working on another PR, that should land in sync with this one, since this changes the measurement methodology used in `Benchmark_Driver` to always measure with `--num-iters=1` and the benchmarks that exhibit setup overhead would report different minimum value, because the overhead is no longer amortized over multiple iterations.

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by palimondo** [comment]
@eeckstein I've pushed the fix for linter nitpicks that stopped the last build. Please re-test. (Are benchmark tests now part of smoke test, too — or should we run full test as we did before?)

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Pull request merged**
