### PR TITLE
Add cache for `USRBasedTypeContext::typeRelation`

### PR DESCRIPTION
**Pull request by hamishknight**
This brings the time taken for the cached completion:

```swift
import SwiftUI

Table(#^CC^#
```

down from ~400ms to ~190ms.

### CODE REVIEW

**Review by ahoppen — APPROVED** [review]
Nice.

**Review by rintaro — APPROVED** [review]

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Comment by hamishknight** [comment]
@swift-ci please smoke test macOS

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Pull request merged**
