### PR TITLE
[DO NOT MERGE] WIP: Messing around with BridgeStorage, just for kicks

### PR DESCRIPTION
**Pull request by milseman**

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please benchmark

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please test source compatibility

**Comment by milseman** [comment]
@Catfish-Man I'll be trying some stuff out here, want to get a couple baselines first.

**Comment by atrick** [comment]
So, after an entire day of debugging:

- Using the "standard" build-script to analyze arm but forgetting about --no-swift-stdlib-assertions (2 hours of debugging wasted)

- Repeated full stdlib builds to see how the SIL is produced

- Figuring out why IRGen generates extra allocations

- Figuring out why LLVM can't optimize this code

...there are two interesting issues.

1. On the Swift side we should not use reinterpret case for inttoptr conversions. That's easy, but that won't ultimately solve the performance problem. More below.

2. LLVM needs to optimize loads from masked pointers. I filed [PR-40735] GVN fails to hoist loads from bitmasked pointers, [Bugzilla PR](https://bugs.llvm.org/show_bug.cgi?id=40735).

The Builtin.reinterpretCast that was already in the unflaggedNativeInstance implementation is the wrong way to write this code. When dealing with tagged pointers we need to use the designated compiler builtins at all times.

After a lot of trial and error, I realized this is the currently supported sequence of Builtins:

  let bridge = Builtin.valueToBridgeObject(i._value)
  return Builtin.castReferenceFromBridgeObject(bridge)

An opaque Builtin.reinterpretCast converting between scalars and pointers are not realistically going to be handled well all the time. Before, we were just lucky that the reinterpretCast was optimized away early.

When reinterpretCast is not optimized away IRGen produces this for a simple mask and load:

```
define swiftcc i64 @testBadCast(i64) #0 {
entry:
  %bitcast = alloca i64, align 8
  %1 = and i64 %0, 1152921504606846975
  %2 = bitcast i64* %bitcast to i8*
  call void @llvm.lifetime.start.p0i8(i64 8, i8* %2)
  store i64 %1, i64* %bitcast, align 8
  %3 = bitcast i64* %bitcast to %T7badcast1CC**
  %4 = load %T7badcast1CC*, %T7badcast1CC** %3, align 8
  %5 = bitcast i64* %bitcast to i8*
  call void @llvm.lifetime.end.p0i8(i64 8, i8* %5)
  %6 = getelementptr inbounds %T7badcast1CC, %T7badcast1CC* %4, i32 0, i32 1
  %7 = load i64, i64* %6, align 8
  ret i64 %7
}
```

It should produce something like this, and will if we use valueToBridgeObject/castReferenceFromBridgeObject:

```
define swiftcc i64 @testBadCast(i64) #0 {
entry:
  %1 = and i64 %0, 1152921504606846975
  %2 = inttoptr i64 %1 to %T7badcast1CC*
  %6 = getelementptr inbounds %T7badcast1CC, %T7badcast1CC* %2, i32 0, i32 1
  %7 = load i64, i64* %6, align 8
  ret i64 %7
}
```

**Comment by gottesmm** [comment]
@atrick Sounds like something that should be added to the Standard Library Programmers Guide, no? (i.e. that we need to use: valueToBridgeObject/castReferenceFromBridgeObject).

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
