### PR TITLE
[stdlib] De-gyb internal sort functions

### PR DESCRIPTION
**Pull request by natecook1000**
This de-gybs the internal sort functions <strike>and converts them to extension methods on `MutableCollection`</strike>—conversion to extension methods can come in a separate change.

### CODE REVIEW

**Comment by natecook1000** [comment]
@swift-ci Please smoke test OS X platform

**Comment by natecook1000** [comment]
@swift-ci Please test OS X platform

**Comment by natecook1000** [comment]
@swift-ci Please benchmark

**Comment by natecook1000** [comment]
@swift-ci Please benchmark

**Comment by natecook1000** [comment]
@swift-ci Please benchmark

**Comment by airspeedswift** [comment]
Benchmarks look promising – question is, do we have enough of them I wonder.

**Comment by natecook1000** [comment]
The Phonebook test worries me a bit, since that's a test of sorting a custom `Comparable` type. My testing with stdlib types using the current sort shows a funny discrepancy: in `-Onone` build, `myInts.sort()` is 3x slower than `myInts.sort(by: <)`, while in a `-O` build, `myInts.sort()` is 2x faster than `myInts.sort(by: <)`. This change erases the difference under `-Onone`, but I'm getting SIL errors under `-O` locally so I can't see what's happening under optimization.

**Comment by gottesmm** [comment]
@airspeedswift TBH, this may be a good opportunity to clean up our sorting benchmarks.

To my mind, these are the axis that we care about:

1. Underlying Type: Trivial, Swift Ref Counted, ObjC Ref Counted
2. Container Type: None, Generic, Existential
3. Type of Comparator. Is it a default comparison, a closure, does it access underlying types.

My personal opinion is that for each "sortable" stdlib type, we should have a full suite of benchmarks like this.

**Comment by natecook1000** [comment]
Hmmm. I simplified my benchmark so it would compile and I'm seeing a big slowdown (~11x) with just the de-gybbed code, even when passing a comparator closure, which shouldn't have changed at all.

Test: https://gist.github.com/natecook1000/601463d7353114b047da54dd34d8c9dd
With swift/master:
```
$ .../swiftc -O customComp.swift
$ time ./customComp
3
real	0m0.206s
user	0m0.186s
sys	0m0.015s
$ time ./customComp by
3
real	0m0.209s
user	0m0.192s
sys	0m0.012s
```

With de-gybbed version (8c4b543):
```
$ .../swiftc -O customComp.swift
$ time ./customComp
3
real	0m2.355s
user	0m2.308s
sys	0m0.023s
$ time ./customComp by
3
real	0m2.287s
user	0m2.266s
sys	0m0.015s
```
🤔

**Comment by natecook1000** [comment]
@gottesmm That's a really good idea 👍

**Comment by airspeedswift** [comment]
@gottesmm other dimensions: size of input (small input will only call insertion sort, skip the introsort part completely), and how already-sorted the input is.

Exhaustive combinations might be overkill given the number of possibilities (we don't want to start gybbing benchmarks 👹). Be good to start with a good range of some of the more common variations though.

**Comment by airspeedswift** [comment]
rdar://30641545 is tracking the performance problems with this.

**Comment by natecook1000** [comment]
@swift-ci Please smoke test

**Comment by natecook1000** [comment]
@swift-ci Please benchmark

**Comment by natecook1000** [comment]
@swift-ci Please smoke test

**Comment by natecook1000** [comment]
@swift-ci Please benchmark

**Comment by natecook1000** [comment]
@swift-ci Please benchmark

**Comment by natecook1000** [comment]
@swift-ci Please benchmark

**Comment by airspeedswift** [comment]
So, based on the last round of benchmarks, we should rebase and merge this, right? Would help with binary size.

**Comment by airspeedswift** [comment]
cc @bob-wilson

**Comment by airspeedswift** [comment]
I rebase this as #9135 since things have changed quite a lot in the mean-time.

**Comment by bob-wilson** [comment]
Those benchmark results look OK to me. If anyone else has concerns, speak up!

**Comment by natecook1000** [comment]
Thanks @airspeedswift!

**Pull request closed without merging**
