### PR TITLE
Run the VarDeclUsageChecker on top level code declarations.

### PR DESCRIPTION
**Pull request by KingOfBrian**
Run the VarDeclUsageChecker on top level code declarations so unused variables correctly generate warnings.

Resolves [SR-2115](https://bugs.swift.org/browse/SR-2115).

### CODE REVIEW

**Comment by KingOfBrian** [comment]
@swift-ci please test

**Review by slavapestov — COMMENTED** [review]
Some more tests would be nice -- cover the other things that the VarDeclUsageChecker can diagnose

**Comment by KingOfBrian** [comment]
Good eye @slavapestov -- the additional tests definitely showed some issues. I had one misconception about what a TLCD was, and also didn't realize that the method was being pumped and would execute with partial state. I changed the code to run only on the last pump, and to walk all of the TLCD with one VarDeclUsageChecker.

**Comment by KingOfBrian** [comment]
Wow, should of ran the test suite locally! This fix uncovers a ton of warnings in the unit tests. They all seem like valid warnings, but it's going to take a few to comb through them all. I'm going to convert to let whenever suggested, but add an empty array to use all the variables instead of replacing with _ since that may alter some of the test behavior.

**Comment by KingOfBrian** [comment]
So I realized I need to be smarter with the top level unused-var declaration checks -- this will still incorrectly warn on cross-file globals.  I'm going to close this for now so I can make sure I understand everything. Thanks!

**Pull request closed without merging**
