### PR TITLE
[build-script-impl] Simplify libcxx build step

### PR DESCRIPTION
**Pull request by nathawes**
Cherry-pick from https://github.com/apple/swift/pull/32909
Fixes `ninja: error: unknown target 'cxx-headers'` on master-next after that target was removed upstream, so trying this change out on master as well.

### CODE REVIEW

**Comment by nathawes** [comment]
@swift-ci please test

**Comment by nathawes** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by nathawes** [comment]
@swift-ci please clean test

**Comment by nathawes** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by nathawes** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by nathawes** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by nathawes** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by nathawes** [comment]
@swift-ci please test

**Comment by nathawes** [comment]
@swift-ci Please Build Toolchain Linux Platform

**Comment by nathawes** [comment]
@swift-ci please clean test

**Comment by nathawes** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by nathawes** [comment]
@swift-ci please clean test

**Comment by nathawes** [comment]
@swift-ci Please Build Toolchain Linux Platform

**Comment by nathawes** [comment]
The macOS toolchain build succeeded even though it still shows as pending above. The toolchain it produced does seem to have the headers still too.

**Comment by nathawes** [comment]
The Linux toolchain failure seems unrelated:
```
project/lldb/source/Plugins/ExpressionParser/Swift/SwiftExpressionParser.cpp:1681:49: error: no member named 'getTargetMachine' in 'swift::GeneratedModule'
12:47:49                                       GenModule.getTargetMachine());
12:47:49                                       ~~~~~~~~~ ^
12:47:49 1 error generated.
```

**Review by hyp — APPROVED** [review]
LGTM

**Pull request merged**
