### PR TITLE
[embedded] When missing a source location in a PerformanceDiagnostic, at least print the function name

### PR DESCRIPTION
**Pull request by kubamracek**
I know this isn't great, but it's at least something. Turns

```
<unknown>:0: error: cannot use metatype of type 'Int' in embedded Swift
```

into:

```
<unknown>:0: error: cannot use metatype of type 'Int' in embedded Swift
in function $ss17FixedWidthIntegerPsE03bitB0SivgSi_Tg5
```

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by eeckstein — COMMENTED** [review]
It would be nice to print the demangled function name.
This can be done with `Demangle::demangleSymbolAsString` (example: https://github.com/apple/swift/blob/703a4719b0c6f3ac1a9e5e0e700530a6dd19d1f5/lib/SIL/IR/SILPrinter.cpp#L87)

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by eeckstein — APPROVED** [review]
lgtm

**Pull request merged**
