### PR TITLE
[build-script] Add option --infer to infer dependencies.

### PR DESCRIPTION
**Pull request by gottesmm**
This causes build-script to use the conservative dependency information that I
committed. Keep in mind for this to work with toolchain dependent
build-products, we need for my install-all patch to land. Once that lands
though, we have a complete solution.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
In a subsequent commit, I am going to make this just imply install_all since I think that is the typical behavior people will want.

**Comment by gottesmm** [comment]
I did a little more work here and I realized I want to do install-all as part of this. Really --infer should always imply --install-all. So once I land a few other things, I am going to push the combined patch to here. Then I should be done.

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Review by drexin — APPROVED** [review]
Nice, LGTM

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
I figured out the problem on Linux. We were trying to rebuild cmake. I fixed the code so we now use the just built one and also fixed the cmake check. We were comparing > instead of >= so even when I passed in the path to the just built cmake, we still tried to rebuild it since the version was the same = /. I added a >= and the problem went away.

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Review by benlangmuir — APPROVED** [review]
Having `--infer` imply `--install-all` will change the behaviour of the minimal swift build, which today does not need any installation.  That may be fine, but it's not really connected to the goals of `--infer`.  Seems worth calling out.  Anyway, LGTM.

**Comment by gottesmm** [comment]
@benlangmuir it just really simplifies the model so I don't have to specify what needs to be installed or not. We could teach build-script about that if we want to. I am trying to do minimum viable product work here to get enough of these wins to tide us over until we can simplify more of this.

**Pull request merged**
