### PR TITLE
Re-enable: [PackageCMO] Use InstructionVisitor to check inst serializability.

### PR DESCRIPTION
**Pull request by elsh**
This reverts commit 056d4474ad626354d3f01ec03616e25e8fe6700d and fixes bugs.

rdar://138881697

### CODE REVIEW

**Comment by elsh** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
What did you change compared to the original PR to fix the problem (the reason for the revert)?

**Comment by elsh** [comment]
> What did you change compared to the original PR to fix the problem (the reason for the revert)?

I haven't changed anything yet except for the revert, but the CI is passing, which is unexpected.

**Comment by elsh** [comment]
@swift-ci test

**Comment by elsh** [comment]
@swift-ci test

**Comment by elsh** [comment]
@swift-ci test

**Pull request merged**
