### PR TITLE
[ABI] Mangle retroactive conformances as part of bound generic types.

### PR DESCRIPTION
**Pull request by DougGregor**
A "retroactive" protocol conformance is a conformance that is provided
by a module that is neither the module that defines the protocol nor
the module that defines the conforming type. It is possible for such
conformances to conflict at runtime, if defined in different modules
that were not both visible to the compiler at the same time.

When mangling a bound generic type, also mangle retroactive protocol
conformances that were needed to satisfy the generic requirements of
the generic type. This prevents name collisions between (e.g.) types
formed using retroactive conformances from different modules. The
impact on the size of the mangling is expected to be relatively small,
because most conformances are not retroactive.

Make this use of protocol-conformance substitutable, since we are likely to see the same retroactive conformances in multiple places in the same mangled name.

Fixes the ABI part of rdar://problem/14375889.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
Whoops.

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Review by rjmccall — APPROVED** [review]
LGTM, even all the fiddly remangling bits.

**Review by eeckstein — APPROVED** [review]
lgtm!

**Comment by DougGregor** [comment]
This mangled name from a SwiftPM test:

     $SSS12PackageGraph0A19ContainerConstraintV11RequirementOySS_SSAA0aC10Identifier11TestSupportg_GACySSAHg_Gs5Error_pIgxxozo_SS9container_AI11requirementtAJsAK_pIgirzo_TR

illustrates that my attempt to make substitutions for some protocol-conformance productions (but not all of them) isn't going to work.

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
I'll come back to making protocol conformances substitutable in a bit.

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
