### PR TITLE
[docs][Windows] Add bash+cmd syntax highlighting in code snippets

### PR DESCRIPTION
**Pull request by AndrewSB**
This is a trivial improvement to the Windows documentation

### CODE REVIEW

**Comment by AndrewSB** [comment]
I just reworked the commit message, I realized I should be using the imperative.

Thanks @jrose-apple, I can't request a reviewer, correct? That's a commit-access only feature on GitHub?

**Comment by jrose-apple** [comment]
Just tagging someone in a comment is usually fine if you know who'd be interested. *I'm* not 100% sure who's tuned in to the native Windows support these days, but if it's not @compnerd then he'd probably at least know.

**Review by compnerd — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@AndrewSB can you please resolve the conflicts on this?

**Comment by AndrewSB** [comment]
Rebased, could someone please ask CI to test and merge again?

**Comment by gottesmm** [comment]
@swift-ci please test and merge

**Comment by gottesmm** [comment]
@swift-ci please test and merge

**Comment by gottesmm** [comment]
@swift-ci please test and merge

**Comment by jrose-apple** [comment]
Nitpick for Saleem and Michael: smoke tests are sufficient for doc changes.

**Pull request merged**
