### PR TITLE
[AccessBase] FindAccessBaseVisitor visits nested accesses.

### PR DESCRIPTION
**Pull request by nate-chandler**
Implemented visitNestedAccess in FindAccessBaseVisitor to visit the value found by the superclass.  Doing so is required by AccessPhiVisitor.

rdar://115033825

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by atrick — APPROVED** [review]
Thanks!

The initial thinking was that we could never see a begin_access after following a phi. That's not actually enforceable and we should end up being conservative anyway if we care about the access scope. So, this fix is correct.

But... I stared at this source for a long time to try to prove that it's complete. I mean, a very long time.

It all rests on the fact that all of the other implementations of `FindAccessVisitorImpl` happen to use `NestedAccessType::IgnoreAccessBegin`.

I think we need to leave some breadcrumb about what we've learned. For example

Why doesn't `FindAccessVisitorImpl::visitNestedAccess` always do this itself in the `StopAtAccessBegin` case`?

Or if that doesn't work, at least comment in the other visitors why they don't need to overried visitNestedAccess.

Or some other idea?

**Comment by nate-chandler** [comment]
Yeah, it's incomplete.  Like you say, the other subclasses would need to be updated or the superclass would.  I've come around to updating the superclass to implement `visitNestedAccess` as in this patch except instead of calling `SuperTy::visitNestedAccess` it either directly looks at the two cases (what's nestedAccessTy) or calls a renaming of the current impl of `visitNestedAccess`.

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by atrick** [comment]
> Yeah, it's incomplete. Like you say, the other subclasses would need to be updated or the superclass would. I've come around to updating the superclass to implement `visitNestedAccess` as in this patch except instead of calling `SuperTy::visitNestedAccess` it either directly looks at the two cases (what's nestedAccessTy) or calls a renaming of the current impl of `visitNestedAccess`.

Nice! I think that's better.

**Pull request merged**
