### PR TITLE
IRGen: Remove heap allocation of std::thread

### PR DESCRIPTION
**Pull request by aschwaighofer**

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Review by jrose-apple — APPROVED** [review]

**Comment by aschwaighofer** [comment]
@swift-ci Please clean test linux

**Comment by aschwaighofer** [comment]
@swift-ci Please test linux

**Comment by aschwaighofer** [comment]
@swift-ci Please test linux

**Comment by aschwaighofer** [comment]
@swift-ci Please test linux

**Comment by aschwaighofer** [comment]
@swift-ci Please test linux

**Comment by aschwaighofer** [comment]
@swift-ci Please test linux

**Pull request merged**
