### PR TITLE
[AutoDiff] WIP: Implement the Differentiable Curry

### PR DESCRIPTION
**Pull request by rxwei**
This PR contains my ongoing implementation of [The Differentiable Curry](https://openreview.net/forum?id=ryxuz9SzDB).

Umbrella issue: SR-11882

cc @dan-zheng @marcrasi @dimitriv

TODOs:
- Type calculation
  - [x] [SIL] Change `SILFunctionType::getAutoDiffDerivativeFunctionType` to include closure context tangents in the result linear map type.
  - [x] [Sema] Add an option to `AnyFunctionType::getAutoDiffDerivativeFunctionType` to include closure context tangents in the result linear map type, for calculating the result linear map type of `Builtin.applyDerivative*`.
- Standard library and builtins
  - [x] [AST] Change `Builtin.differentiableFunction*`'s type to include closure context tangents.
  - [x] [stdlib] Update differential operators to use the updated AD builtins.
- SIL generation
  - [x] [SILGen] Change derivative registration linear map thunks (`SILGenFunction::getThunkedAutoDiffLinearMap`) to include closure context tangents.
  - [x] [SILGen] Change `@differentiable` reabstraction thunk generation (`createAutoDiffThunk` in SILGenPoly.cpp) to include closure context tangents in derivative type calculation.
- Differentiation transform
  - [x] [Main pass] Handle closure context tangents in subset parameters thunks.
  - [ ] [ActivityAnalysis] Propagate variedness and usefulness for function values when visiting `apply`.
  - [ ] [DifferentialEmitter] Differentiate `apply` with respect to the function, forward-propagating closure context tangents.
  - [ ] [PullbackEmitter] Differentiate `apply` with respect to the function, producing closure context tangents of `AnyDerivative` type in the pullback.
  - [ ] [PullbackEmitter] Differentiate `partial_apply`, casting closure context tangents from `tan[f]` to `tan[args]`.

### CODE REVIEW

**Comment by rxwei** [comment]
AD is now using the right linear map type (with `AnyDerivative`) everywhere including the differentiation transform. Besides FileCheck errors which are obviously expected, I'm getting quite a few runtime segfaults which I think could be caused by incorrect thunking. I'm signing off for today and will continue when I get a chance (next weekend or so).

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by dan-zheng** [comment]
I accidentally deleted `tensorflow` branch, which closed this PR. That was not intentional, sorry!
It would be nice to protect `tensorflow` branch against deletion to prevent this from happening again.

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
