### PR TITLE
More strict-DA support for graph lowering, and compiler tweaks for TPU targets

### PR DESCRIPTION
**Pull request by mhong**
1. Added shape list and type list support for the new strict-DA code path in graph lowering, and migrated runtime tests to strict-DA

2. Added TPU-compiler testing on those test tagets, so that they are less likely to be broken when we import changes to google internal repo with TPU runtime testing.

3. Added a temporary patch to reject TPU programs that produce 0 result tensors, since they cannot be executed due to an XLA limitation (b/111123797).

4. Tweaked a few tests to work with google's internal setup.

### CODE REVIEW

**Comment by mhong** [comment]
@swift-ci please test tensorflow

**Comment by mhong** [comment]
Tests passed: https://ci-external.swift.org/job/swift-PR-TensorFlow-Linux/452/

**Review by lattner — APPROVED** [review]
nice!

**Review by rxwei — APPROVED** [review]

**Review by bgogul — APPROVED** [review]
Worked on a similar fix yesterday! :)

**Comment by mhong** [comment]
Thanks all for the review!

@bgogul, sorry we overlapped on the work here! I was trying to re-enable TPU tests yesterday -- since they involve sends/recvs, that in turn requires that the new strict DA code path.

**Pull request merged**
