### PR TITLE
Add benchmarks for mutable copies of bridged Swift Strings

### PR DESCRIPTION
**Pull request by Catfish-Man**

### CODE REVIEW

**Comment by Catfish-Man** [comment]
@swift-ci please smoke test

**Comment by Catfish-Man** [comment]
@swift-ci please smoke benchmark

**Comment by Catfish-Man** [comment]
@swift-ci please smoke test

**Comment by Catfish-Man** [comment]
@swift-ci please smoke test and merge

**Review by lorentey — APPROVED** [review]
⭐️⭐️⭐️

**Comment by Catfish-Man** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
