### PR TITLE
Remove generic metadata pattern from nominal type descriptors.

### PR DESCRIPTION
**Pull request by jckarter**
The NTD now references the metadata accessor function for the type, which is a better interface for most things one would want to do with type metadata from a nominal type. The only remaining use in the runtime self really has no requirement to do so. For now, don't disturb the rest of the binary layout to prevent breaking downstream clients too much at a time.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please clean test

**Comment by slavapestov** [comment]
Are there any downstream clients? I think just IRGen.

**Comment by jckarter** [comment]
LLDB has historically needed to walk the list of instantiations in generic metadata pattern caches. I'm not sure how they get to the pattern these days, whether they do it by symbol lookup or going through the NTD.

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please clean test

**Comment by jckarter** [comment]
@swift-ci Please clean test

**Comment by slavapestov** [comment]
I thought they stopped digging through runtime metadata caches directly a whileago, and use RemoteAST now instead, but maybe I'm wrong. However having the nominal type kind be a separate field is fine for now, but eventually we might want to pack it into the flags word of GenericParameterDescriptor (and probably GenericParameterDescriptor is a bad name for what it is, considering it also encodes details about the vtable for classes...) Do you want to file a JIRA or radar for cleaning up the nominal type descriptor layout?

**Comment by jckarter** [comment]
I think we already have "clean up nominal type descriptors" as a todo item for ABI stability.

**Pull request merged**
