### PR TITLE
Fix test cases and enable copy-on-write existentials

### PR DESCRIPTION
**Pull request by aschwaighofer**
Let's see where we stand ...

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke benchmark

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke benchmark

**Comment by aschwaighofer** [comment]
@swift-ci Please test os x platform

**Comment by dabrahams** [comment]
👍 gains clearly swamping losses!

**Comment by aschwaighofer** [comment]
@swift-ci Please test os x platform

**Comment by aschwaighofer** [comment]
@swift-ci Please test os x platform

**Comment by aschwaighofer** [comment]
@swift-ci Please test linux platform

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
Please clean test

**Comment by aschwaighofer** [comment]
@swift-ci Please clean test

**Comment by aschwaighofer** [comment]
@swift-ci Please test os x platform

**Comment by aschwaighofer** [comment]
Another unrelated failure in swiftpm ...

**Comment by aschwaighofer** [comment]
Wash, rinse, and repeat ...

**Comment by aschwaighofer** [comment]
@swift-ci Please test os x platform

**Comment by rudkx** [comment]
I am seeing quite a few failures when I build with:
```
./utils/build-script --release-debuginfo --debug-swift
```

Bisecting implicated this commit for most of them (one test, `stdlib/TestCharacterSet.swift`, appears to be due to 6c26b80e6e759345b475bba3bcc621cfc5151b89).

```
Failing Tests (43):
    Swift(macosx-x86_64) :: stdlib/Runtime.swift.gyb
    Swift(macosx-x86_64) :: stdlib/TestCharacterSet.swift
    Swift(macosx-x86_64) :: IRGen/existentials_objc.sil
    Swift(macosx-x86_64) :: IRGen/alloc.sil
    Swift(macosx-x86_64) :: IRGen/generic_metatypes.swift
    Swift(macosx-x86_64) :: SILGen/objc_bridging_any.swift
    Swift(macosx-x86_64) :: SILGen/opaque_values_silgen.swift
    Swift(macosx-x86_64) :: IRGen/fixed_size_buffer_peepholes.sil
    Swift(macosx-x86_64) :: IRGen/generic_metatypes_arm.swift
    Swift(macosx-x86_64) :: IRGen/global_resilience.sil
    Swift(macosx-x86_64) :: SILGen/function_conversion.swift
    Swift(macosx-x86_64) :: SILGen/protocol_extensions.swift
    Swift(macosx-x86_64) :: IRGen/witness_table_multifile.swift
    Swift(macosx-x86_64) :: SILGen/address_only_types.swift
    Swift(macosx-x86_64) :: SILGen/existential_erasure.swift
    Swift(macosx-x86_64) :: SILGen/functions.swift
    Swift(macosx-x86_64) :: Interpreter/classes.swift
    Swift(macosx-x86_64) :: stdlib/TestAffineTransform.swift
    Swift(macosx-x86_64) :: Interpreter/FunctionConversion.swift
    Swift(macosx-x86_64) :: Interpreter/generic_objc_subclass.swift
    Swift(macosx-x86_64) :: Interpreter/struct_resilience.swift
    Swift(macosx-x86_64) :: Interpreter/tuple_casts.swift
    Swift(macosx-x86_64) :: Interpreter/SDK/class_as_object.swift
    Swift(macosx-x86_64) :: Interpreter/SDK/missing_imports_repl.swift
    Swift(macosx-x86_64) :: Interpreter/SDK/objc_mangling.swift
    Swift(macosx-x86_64) :: PlaygroundTransform/print.swift
    Swift(macosx-x86_64) :: Prototypes/Result.swift
    Swift(macosx-x86_64) :: Prototypes/TextFormatting.swift
    Swift(macosx-x86_64) :: stdlib/AnyHashableCasts.swift.gyb
    Swift(macosx-x86_64) :: stdlib/BridgeIdAsAny.swift.gyb
    Swift(macosx-x86_64) :: stdlib/Builtins.swift
    Swift(macosx-x86_64) :: stdlib/DebuggerSupport.swift
    Swift(macosx-x86_64) :: stdlib/PrintArray.swift
    Swift(macosx-x86_64) :: stdlib/PrintStruct.swift
    Swift(macosx-x86_64) :: stdlib/Reflection.swift
    Swift(macosx-x86_64) :: stdlib/Reflection_jit.swift
    Swift(macosx-x86_64) :: stdlib/TestUserInfo.swift
    Swift(macosx-x86_64) :: Interpreter/SDK/Cocoa_repl.swift
    Swift(macosx-x86_64) :: Interpreter/SDK/objc_keypath.swift
    Swift(macosx-x86_64) :: Interpreter/SDK/dictionary_pattern_matching.swift
    Swift(macosx-x86_64) :: Interpreter/SDK/KVO.swift
    Swift(macosx-x86_64) :: Interpreter/SDK/Accelerate.swift
    Swift(macosx-x86_64) :: Interpreter/SDK/objc_dynamic_lookup.swift
```

**Comment by aschwaighofer** [comment]
I reproduced this with a clean build.

This is really odd. It looks like the build is not picking up the -DSWIFT_RUNTIME_ENABLE_COW_EXISTENTIALS.

The issue goes away if I change to RelWithDebInfo and that is the only change i make ...

https://github.com/apple/swift/pull/8488

should fix it.

**Pull request merged**
