### PR TITLE
SILOptimizer: Remove special handling of transparent functions from dead function elimination

### PR DESCRIPTION
**Pull request by slavapestov**
This is no longer sound after https://github.com/apple/swift/pull/12903.
We no longer special-case the linkage of transparent functions at all.

### CODE REVIEW

**Comment by slavapestov** [comment]
@aschwaighofer does this look OK?

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
Looks good. Thank you.

**Comment by swiftix** [comment]
@slavapestov Does your change has any effect on the code size? The original reason for #12635 was to reduce the code size. In particular, one of the projects from the source compatibility suite got good code size wins, IIRC. @eeckstein should be able to tell you which one it was.

**Comment by aschwaighofer** [comment]
Whatever we had before was not sound see https://github.com/apple/swift/pull/12903. I believe if we want to have “transparent always emit into client”, the SIL linkage should be ‘’shared’’.

**Pull request merged**
