### PR TITLE
Add spaces before and after closure arrow

### PR DESCRIPTION
**Pull request by ken0nek**
I add spaces around all closure arrow like this `()->()`  ->  `() -> ()`

### CODE REVIEW

**Comment by lattner** [comment]
Please make sure to audit the changes.  The change to docs/proposals/valref.rst breaks alignment of comments, for example.

**Comment by gribozavr** [comment]
@ken0nek Please also run tests, `build-script -RT`.  I am seeing failures:

```
Failing Tests (3):
    Swift :: Constraints/closures.swift
    Swift :: IDE/crashers/055-swift-valuedecl-getoverloadsignature.swift
    Swift :: expr/closure/closures.swift
```

**Comment by ken0nek** [comment]
@lattner 
All right.

Which is better,

discard changes, for example, 
```swift
var x : Array<Int,42>               // an array of 42 integers
var y : Array<val Int,42>           // an array of 42 integers
var z : Array<ref Int,42>           // an array of 42 integers-on-the-heap
var z : Array<ref Array<Int,42>, 2> // an array of 2 references to arrays
ref a : Array<Int,42>               // a reference to an array of 42 integers
var f : ()->ref Array<Int,42>       // a closure returning a reference to an array
var b : ref Array<Int,42>           // equivalent to "ref b : Int[42]"
```
or

reformat code and comments (or only indent comments), for example, 
```swift
var x : Array<Int, 42>                // an array of 42 integers
var y : Array<val Int, 42>            // an array of 42 integers
var z : Array<ref Int, 42>            // an array of 42 integers-on-the-heap
var z : Array<ref Array<Int, 42>, 2>  // an array of 2 references to arrays
ref a : Array<Int, 42>                // a reference to an array of 42 integers
var f : () -> ref Array<Int, 42>      // a closure returning a reference to an array
var b : ref Array<Int, 42>            // equivalent to "ref b : Int[42]"
```

**Comment by ken0nek** [comment]
@gribozavr Sorry for that. I check on it.

**Comment by gribozavr** [comment]
@ken0nek Reformatting the comment is better.  In that case you can just reformat one line to restore alignment.

**Comment by ken0nek** [comment]
@gribozavr 
I got errors on `Constraints/closures.swift` and `expr/closure/closures.swift` when testing

and I fixed numbers as errors say like this
screen shot 2015-12-23 at 4 41 45 pm

Finally all tests passed.

but I'm wondering if this is correct...

**Comment by gribozavr** [comment]
@ken0nek Yes, that should be correct.  Did you push an updated commit?  I don't see it...

**Comment by ken0nek** [comment]
@grachyov I didn't push in case it is wrong. But I push now and please check this.

**Comment by ken0nek** [comment]
@gribozavr Thank you for merging.
It might be a silly question and due to lack of understanding but what do numbers mean?

**Comment by gribozavr** [comment]
@ken0nek Oh, those are tests for compiler-generated fixits: the numbers specify the character positions, and the text after the equal sign is the replacement text.

**Comment by ken0nek** [comment]
@gribozavr Thank you for your quick reply. Now I got it :)

**Pull request merged**
