### PR TITLE
Remove unneeded UndoManager test which inadvertently triggered driver error

### PR DESCRIPTION
**Pull request by owenv**
This test was inadvertently checking whether the driver diagnosed a lack of input files instead of whether the program typechecked. Discovered while debugging why it failed with swift-driver

### CODE REVIEW

**Comment by owenv** [comment]
@swift-ci please smoke test

**Comment by owenv** [comment]
@jckarter I saw you linked to rdar://problem/17755906 in this test, which has something to do with proxy objects. Do you mind taking a look to see if these changes make sense? I'm not sure if this is a worthwhile fix or if I should just delete the test entirely.

**Comment by jckarter** [comment]
We can probably remove this test, since the issue of assigning through AnyObject dynamic dispatch has never been fixed.

**Comment by owenv** [comment]
@swift-ci please smoke test

**Review by DougGregor — APPROVED** [review]

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by owenv** [comment]
@swift-ci smoke test and merge

**Pull request merged**
