### PR TITLE
Revert "Keep certain function that are potentially used in the debugger"

### PR DESCRIPTION
**Pull request by etcwilde**
Reverts apple/swift#68558

This PR is causing 23 new Swift test failures on rebranch on macOS.
https://ci.swift.org/view/Swift%20rebranch/job/oss-swift-rebranch-incremental-RA-macos/2718/

The only compiler-related change in this build job was https://github.com/apple/swift/commit/e06ba23c7531989fc5edd737bd0f02d978ef9eb9

The testing on the related PR was from too long ago to see the results, but macOS should be testing green on rebranch.

```
Failed Tests (23):
  Swift(macosx-x86_64) :: Concurrency/Backdeploy/weak_linking.swift
  Swift(macosx-x86_64) :: IRGen/alwaysEmitIntoClient.swift
  Swift(macosx-x86_64) :: IRGen/asmname.swift
  Swift(macosx-x86_64) :: IRGen/async/run-call-class-witnessmethod-void-to-void.swift
  Swift(macosx-x86_64) :: IRGen/objc_implementation.swift
  Swift(macosx-x86_64) :: IRGen/prespecialized-metadata/class-fileprivate-2argument-1_distinct_use-1st_argument_generic_class-2nd_argument_distinct_generic_class.swift
  Swift(macosx-x86_64) :: IRGen/prespecialized-metadata/class-fileprivate-2argument-1_distinct_use-1st_argument_generic_class-2nd_argument_same_generic_class_different_value.swift
  Swift(macosx-x86_64) :: IRGen/prespecialized-metadata/class-fileprivate-2argument-1_distinct_use-1st_argument_generic_class-2nd_argument_same_generic_class_same_value.swift
  Swift(macosx-x86_64) :: IRGen/prespecialized-metadata/class-fileprivate-inmodule-1arg-2ancs-1distinct_use-1st_anc_gen-1arg-1st_arg_con_int-2nd_anc_gen-1st-arg_con_double.swift
  Swift(macosx-x86_64) :: IRGen/prespecialized-metadata/class-fileprivate-inmodule-1arg-2ancs-1distinct_use-1st_anc_gen-1arg-1st_arg_con_int-2nd_anc_gen-1st-arg_subclass_arg.swift
  Swift(macosx-x86_64) :: IRGen/prespecialized-metadata/class-fileprivate-inmodule-1arg-2ancs-1distinct_use-1st_anc_gen-1arg-1st_arg_subclass_arg-2nd_anc_gen-1st-arg_con_int.swift
  Swift(macosx-x86_64) :: IRGen/prespecialized-metadata/class-fileprivate-inmodule-1arg-2ancs-1distinct_use-1st_anc_gen-1arg-1st_arg_subcls_arg-2nd_anc_gen-1st-arg_subcls_arg.swift
  Swift(macosx-x86_64) :: IRGen/prespecialized-metadata/class-fileprivate-inmodule-1argument-1ancestor-1distinct_use-1st_ancestor_nongeneric-fileprivate.swift
  Swift(macosx-x86_64) :: IRGen/prespecialized-metadata/class-fileprivate-inmodule-1argument-1distinct_use-1st_argument_generic_class-1argument.swift
  Swift(macosx-x86_64) :: IRGen/prespecialized-metadata/class-fileprivate-inmodule-1argument-1distinct_use.swift
  Swift(macosx-x86_64) :: IRGen/prespecialized-metadata/class-fileprivate-inmodule-1argument-1distinct_use_generic_class.swift
  Swift(macosx-x86_64) :: IRGen/prespecialized-metadata/class-fileprivate-inmodule-1argument-1distinct_use_generic_class_specialized_at_generic_class.swift
  Swift(macosx-x86_64) :: IRGen/prespecialized-metadata/class-fileprivate-inmodule-1argument-1distinct_use_generic_enum.swift
  Swift(macosx-x86_64) :: IRGen/prespecialized-metadata/class-fileprivate-inmodule-1argument-1distinct_use_generic_struct.swift
  Swift(macosx-x86_64) :: IRGen/weak_import_deployment_target.swift
  Swift(macosx-x86_64) :: Interop/Cxx/exceptions/trap-on-exception-irgen-itanium.swift
  Swift(macosx-x86_64) :: Profiler/coverage_dead_code_elim_onone.swift
  Swift(macosx-x86_64) :: stdlib/builtin-ifdef.swift
```
Failure output: Concurrency/Backdeploy/weak_linking.swift
```
--
/Users/ec2-user/jenkins/workspace/oss-swift-rebranch-incremental-RA-macos/swift/test/Concurrency/Backdeploy/weak_linking.swift:27:28: error: BACKDEPLOY_CONCURRENCY: expected string not found in input
// BACKDEPLOY_CONCURRENCY: declare extern_weak swiftcc i8 @"$sScP8rawValues5UInt8Vvg"
                           ^
<stdin>:596:71: note: scanning from here
declare extern_weak void @"_swift_FORCE_LOAD_$_swiftCompatibility56"()
                                                                      ^
<stdin>:606:1: note: possible intended match here
declare void @swift_bridgeObjectRelease(ptr) #2
^

Input file: <stdin>
Check file: /Users/ec2-user/jenkins/workspace/oss-swift-rebranch-incremental-RA-macos/swift/test/Concurrency/Backdeploy/weak_linking.swift

-dump-input=help explains the following input dump.

Input was:
<<<<<<
            .
            .
            .
          591:  
          592: declare extern_weak void @"_swift_FORCE_LOAD_$_swiftCompatibility51"() 
          593:  
          594: declare extern_weak void @"_swift_FORCE_LOAD_$_swiftCompatibilityConcurrency"() 
          595:  
          596: declare extern_weak void @"_swift_FORCE_LOAD_$_swiftCompatibility56"() 
check:27'0                                                                           X error: no match found
          597:  
check:27'0     ~
          598: ; Function Attrs: noinline 
check:27'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
          599: declare swiftcc void @"$ss18_fatalErrorMessage__4file4line5flagss5NeverOs12StaticStringV_A2HSus6UInt32VtF"(i64, i64, i8, i64, i64, i8, i64, i64, i8, i64, i32) #8 
check:27'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          600:  
check:27'0     ~
          601: declare swiftcc { ptr, ptr } @"$ss27_allocateUninitializedArrayySayxG_BptBwlFyp_Tg5"(i64) #0 
check:27'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          602:  
check:27'0     ~
          603: declare swiftcc void @"$ss5print_9separator10terminatoryypd_S2StF"(ptr, i64, ptr, i64, ptr) #0 
check:27'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          604:  
check:27'0     ~
          605: ; Function Attrs: nounwind 
check:27'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
          606: declare void @swift_bridgeObjectRelease(ptr) #2 
check:27'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
check:27'1     ?                                                possible intended match
          607:  
check:27'0     ~
          608: attributes #0 = { "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="penryn" "target-features"="+cmov,+cx16,+cx8,+fxsr,+mmx,+sahf,+sse,+sse2,+sse3,+sse4.1,+ssse3,+x87" "tune-cpu"="generic" } 
check:27'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          609: attributes #1 = { nounwind "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="penryn" "target-features"="+cmov,+cx16,+cx8,+fxsr,+mmx,+sahf,+sse,+sse2,+sse3,+sse4.1,+ssse3,+x87" "tune-cpu"="generic" } 
check:27'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          610: attributes #2 = { nounwind } 
check:27'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          611: attributes #3 = { noinline nounwind willreturn memory(read) "frame-pointer"="non-leaf" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="penryn" "target-features"="+cmov,+cx16,+cx8,+fxsr,+mmx,+sahf,+sse,+sse2,+sse3,+sse4.1,+ssse3,+x87" "tune-cpu"="generic" } 
check:27'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            .
            .
            .
>>>>>>

--
```

### CODE REVIEW

**Comment by etcwilde** [comment]
@swift-ci please test

**Comment by etcwilde** [comment]
macOS failure:
```
Failed Tests (1):
  lldb-api :: lang/swift/variables/consume_operator/TestSwiftConsumeOperator.py
```

@adrian-prantl, I could have sworn that test was disabled, or was it re-enabled?
Looks like @felipepiovezan re-enabled it https://github.com/apple/llvm-project/pull/7497

**Comment by adrian-prantl** [comment]
Maybe the test is flaky?

**Comment by felipepiovezan** [comment]
I have disabled it again, it was an ARM vs X86 thing

**Pull request merged**
