### PR TITLE
Filter out any headermap options when serializing Xcc options.

### PR DESCRIPTION
**Pull request by adrian-prantl**
The Xcode build system introduces these to implement the unextended
module overlay at *framework build time* but they are not relevent at
all for importing the module from the install or build directory from
within the debugger.

rdar://problem/35732279

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci please test

**Comment by adrian-prantl** [comment]
@swift-ci please test

**Review by jrose-apple — CHANGES_REQUESTED** [review]
I don't think this is correct. Header maps aren't needed for framework targets, but they might be for apps or anything with a bridging header.

**Comment by adrian-prantl** [comment]
To summarize an off-line conversation: header maps are being used both for framework targets (which is the scenario I had in mind for this patch) and in apps/things-with-bridging-headers (as Jordan pointed out). This patch needs to be updated to only affect the framework use-case I had in mind.

**Comment by jrose-apple** [comment]
Unfortunately, we don't currently have that information—we approximate it by seeing if there's a bridging header. However, if there's no bridging header, this is probably safe enough.

**Comment by jrose-apple** [comment]
Oops, no, that might not be true for unit test targets, which may depend on the app's bridging header but not have one themselves.

**Pull request closed without merging**
