### PR TITLE
Fix diagnostics message for conditional conformance with marker protocol

### PR DESCRIPTION
**Pull request by omochi**
Current:

```swift
protocol P { }
struct S<T> {}
extension S: P where T: Sendable {}
// Conditional conformance to non-marker protocol 'P' cannot depend on conformance of 'T' to non-marker protocol 'Sendable'
```

Second `non-marker` is typo of `marker`.

It should be:

```
Conditional conformance to non-marker protocol 'P' cannot depend on conformance of 'T' to marker protocol 'Sendable'
```

---

I fixed diagnostics message template.

### CODE REVIEW

**Review by xedin — CHANGES_REQUESTED** [review]
The change looks good but please add a test-case before we can merge this.

**Comment by omochi** [comment]
@xedin I updated existing test case for this diagnostics.

**Review by xedin — APPROVED** [review]
Perfect, thank you!

**Comment by xedin** [comment]
@swift-ci please test

**Pull request merged**
