### PR TITLE
[cxx interop] Fix issue where const overloaded disambiguated methods were not in the lookup table

### PR DESCRIPTION
**Pull request by Huddie**
When disambiguating Cxx const and mutable overloaded methods the mutable version would fail since it was missing for the lookup table. To fix this, post import, find those decls that are cxxMethods and explicitly add them to the lookup table if they are the mutable versions.

Note: This PR may end up not being needed depending on how we settle on disambiguating const overloaded methods.

### CODE REVIEW

**Review by zoecarver — APPROVED** [review]
Perfect. Thanks.

**Comment by zoecarver** [comment]
@swift-ci please test.

**Review by hyp — APPROVED** [review]

**Comment by Huddie** [comment]
I removed the `ping` methods and test and replaced with them the `numberOfMutableMethodsCalled`
So now we call `numberOfMutableMethodsCalled` before `numberOfMutableMethodsCalledMutating` once and `numberOfMutableMethodsCalledMutating` before `numberOfMutableMethodsCalled` to confirm both ways properly add methods to the lookup table.

Reason for removing the `ping` method is that the `const` version of `ping` was an empty method `{}` which seemingly was being optimized out. Resulting in only 1 available `ping` method named `ping` not `pingMutating`, even though it maps to the `mutable` version of the `ping` C++ method.

One oddity was that the `module-interface` test was not failing (meaning it believed that the `pingMutable` method was in the interface. Not sure if this is due to lower level of optimization occurring in those test or because the optimization is occurring at a later stage of the compiler pipeline

**Comment by Huddie** [comment]
@swift-ci please test.

**Comment by Huddie** [comment]
@swift-ci please test.

**Comment by Huddie** [comment]
@swift-ci please test.

**Comment by zoecarver** [comment]
Please land this. Thanks, Ehud!

**Pull request merged**
