### PR TITLE
[Parser] Parse #keyPath in parseExprPostfixWithoutSuffix instead of parseExprUnary

### PR DESCRIPTION
**Pull request by yasserdeceukelier**
Moved the call to parseExprKeyPathObjC from parseExprUnary to parseExprPostfixWithoutSuffix. This allows to perform operations on #keyPath(...) as it now parses the suffix for it.

Fixes [Swift JIRA]  (SR-5605) Parser fails on optional #keyPath in cas
Eg. `#keyPath(SomeClass.someProperty).description` is now possible

### CODE REVIEW

**Comment by yasserdeceukelier** [comment]
@swift-ci Please smoke test

**Comment by yasserdeceukelier** [comment]
@jrose-apple @rintaro Could you review please?
I ran the parser test locally and had no failures. I was also wondering whether it is necessary to add a test for the case that this PR fixes?

**Comment by harlanhaskins** [comment]
I'd say this is definitely worth adding a test.

That said, @swift-ci please smoke test.

**Comment by harlanhaskins** [comment]
It would be worth adding a few lines to `test/expr/unary/keypath/keypath-objc.swift`. And maybe moving that test to `test/expr/postfix/keypath/keypath-objc.swift`?

**Comment by jrose-apple** [comment]
I agree with Harlan, on both counts. Just adding the test case that looks like the one from the SR should be sufficient! Then you can run just that one test by using the instructions in docs/Testing.md.

I'm glad the change was this simple after all!

**Comment by yasserdeceukelier** [comment]
@swift-ci Please smoke test

**Comment by yasserdeceukelier** [comment]
@harlanhaskins @jrose-apple Added code to test the fix & moved the test file. Does it seem ok to you?

**Comment by harlanhaskins** [comment]
Sorry, @yasserdeceukelier, invoking CI requires privileges for security reasons. Patch looks good to me, assuming the tests pass!

@swift-ci please smoke test

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test

**Comment by yasserdeceukelier** [comment]
Ah, didn't know. Makes sense though!
Thanks for following up & helping me! :D

**Comment by jrose-apple** [comment]
Merged. Thanks, Yasser! Please move the JIRA bug to "Resolved".

**Comment by yasserdeceukelier** [comment]
Moved it to resolved. 
It might have been a simple bug, but it was perfect for my first contribution. And having such helpful people is also very encouraging, thank you guys for your help & input!

**Comment by rintaro** [comment]
Sorry for not reviewing this. I was on vacation.
Thank you Yasser! 👍

**Pull request merged**
