### PR TITLE
|| has higher precedence than the ternary operator

### PR DESCRIPTION
**Pull request by stephentyrone**
Fixes https://github.com/apple/swift/pull/41553

### CODE REVIEW

**Comment by stephentyrone** [comment]
@swift-ci please smoke test

**Review by Azoy — APPROVED** [review]

**Review by finagolfin — APPROVED** [review]
Tested with the Feb. 25 trunk snapshot, finally gets the NIO tests passing again.

**Comment by stephentyrone** [comment]
@swift-ci please smoke test macOS

**Comment by stephentyrone** [comment]
@swift-ci smoke test mac

**Comment by stephentyrone** [comment]
@swift-ci please smoke test

**Comment by glessard** [comment]
Thanks for your help, @buttaface!

**Pull request merged**
