### PR TITLE
🌲 Disabling failing Linux tests for rebranch visibility

### PR DESCRIPTION
**Pull request by etcwilde**
Disabling on rebranch:
 - Frontend/dependencies-fine.swift
 - DebugInfo/BridgingHeaderPCH.swift
 - DebugInfo/ClangModuleBreadcrumbs.swift

Trying to see where the rest of the toolchain build stands on Linux.

### CODE REVIEW

**Comment by etcwilde** [comment]
@swift-ci please smoke test

**Comment by etcwilde** [comment]
I expect failures, but macOS and Linux should both be failing during the SwiftPM build.

**Comment by beccadax** [comment]
@compnerd Could your changes in #68302 have caused `Frontend/dependencies-fine.swift` to start running on Linux when it previously did not? The test appears to import Objective-C code when clang is not configured to parse it, which causes a cascade of errors where clang has a really hard time understanding things like `id` and `@class` as plain C.

**Comment by compnerd** [comment]
It seems unlikely to me, the removed aspects were:
```
// REQUIRES: shell
// Also uses awk:
// XFAIL OS=windows
```
`shell` should be available on Linux.

**Pull request merged**
