### PR TITLE
Take enable-testing into account when computing whether a class has resilient metadata

### PR DESCRIPTION
**Pull request by aschwaighofer**
rdar://87617621

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci test linux

**Comment by slavapestov** [comment]
Elsewhere we assume that exposed-in-ABI-but-internal-in-source types are fragile. Perhaps the problem is that the client code should be using fragile access patterns instead of assuming the metadata base offset symbol exists for the internal subclass? But maybe it doesn't really matter.

**Comment by aschwaighofer** [comment]
I don't know which rules are supposed to apply here. My reasoning is the following:

The defining module is compiled with enable-testing (which I read as `internal` becomes `public` in importing modules if the import is `@testable`) and resilience enabled.

The using module imports the defining module with `@testable import`. Which makes `internal` -> `public`. So I believe my choice is reasonable: we behave as if the thing is `public` which also exposes that symbol.

**Comment by aschwaighofer** [comment]
>  the client code should be using fragile access patterns instead of assuming the metadata base offset symbol exists for the internal subclass

That would imply that you have to co-compile the module that imports the resilient module `@testable`, effectively disabling resilience for `@testable` imports, is that the semantics of `@testable` imports?

**Comment by aschwaighofer** [comment]
I guess using an internal symbol is already not resilient

**Comment by slavapestov** [comment]
FWIW, testable imports are already effectively non-resilient because we don't enforce resilience constraints on non-public types -- it would be source-breaking to -enable-testing if we did.

**Comment by aschwaighofer** [comment]
@slavapestov That line of argument make sense to me. Alternative approach: https://github.com/apple/swift/pull/41044

**Pull request closed without merging**
