### PR TITLE
[SE-0247] Add contiguous string APIs

### PR DESCRIPTION
**Pull request by milseman**
SE-0247

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please benchmark

**Comment by tkremenek** [comment]
The corresponding evolution proposal has been accepted.  What is blocking this from making progress?

**Comment by tkremenek** [comment]
@swift-ci clean test

**Comment by tkremenek** [comment]
@milseman is there anything block this from moving forward?

**Comment by milseman** [comment]
I need to write more tests. I’m on that today.

**Comment by milseman** [comment]
@swift-ci please benchmark

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please test os x platform

**Comment by milseman** [comment]
@swift-ci please test Linux platform

**Comment by milseman** [comment]
```
12:30:27 
/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/swiftpm/Tests/FunctionalTests/MiscellaneousTests.swift:93: error: MiscellaneousTestCase.testCompileFailureExitsGracefully : XCTAssertTrue failed - unexpected failure matching '' against pattern contains("Compiling CompileFails Foo.swift")
```

@swift-ci please test linux platform

**Pull request merged**
