### PR TITLE
test: repair the Android CI after #30875

### PR DESCRIPTION
**Pull request by compnerd**
The added test was not correctly indicated as a running test.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @ematejska

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by ematejska** [comment]
Thanks for fixing this!

**Pull request merged**
