### PR TITLE
[sending] Remove transferring.

### PR DESCRIPTION
**Pull request by gottesmm**
Out of an abundance of caution, we:

1. Left in parsing support for transferring but internally made it rely on the internals of sending.

2. Added a warning to tell people that transferring was going to be removed very soon.

Now that we have given people some time, remove support for parsing transferring.

rdar://130253724

### CODE REVIEW

**Comment by gottesmm** [comment]
I need to do the swift parser part of this

**Review by ktoso — APPROVED** [review]
Hooray, the mix of wording was getting confusing :) LGTM

**Comment by gottesmm** [comment]
https://github.com/apple/swift-syntax/pull/2692
@swift-ci smoke test

**Review by ahoppen — COMMENTED** [review]
Should we also rip out parsing of `transferring` in swift-syntax?

Edit: Sorry, didn’t see your swift-syntax PR, sorry.

**Review by ahoppen — APPROVED** [review]
Parser changes look good

**Comment by gottesmm** [comment]
https://github.com/apple/swift-syntax/pull/2692
@swift-ci smoke test

**Review by xedin — APPROVED** [review]

**Pull request merged**
