### PR TITLE
[Migrator] Remove some now unnecessary tuple destructuring

### PR DESCRIPTION
**Pull request by bitjammer**
Some changes for SE-0110 were backed out in
https://github.com/apple/swift/pull/10414, so the migrator no longer
needs to add its own tuple destructuring.

rdar://problem/32513074

### CODE REVIEW

**Comment by bitjammer** [comment]
@swift-ci Please test

**Comment by bitjammer** [comment]
@swift-ci Please test Linux

**Comment by bitjammer** [comment]
Ah, https://github.com/apple/swift/pull/10414 is still running, thought it was merged already. I'll wait for that to get merged to run tests again.

**Comment by tkremenek** [comment]
@swift-ci clean test

**Pull request merged**
