### PR TITLE
Space Engine: Remove Space::intersect altogether

### PR DESCRIPTION
**Pull request by jrose-apple**
It was only being used for one optimization, and there's a second check later that does almost the same thing but handles UnknownCase a bit better. Less code!

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
@swift-ci Please test compiler performance

**Review by xedin — APPROVED** [review]
Awesome!

**Comment by davidungar** [comment]
Wonderful!!

**Comment by jrose-apple** [comment]
No significant difference -> prefer the solution with less code. Merging.

**Pull request merged**
