### PR TITLE
Fix the freestanding/minimal bot configuration by disabling compatibility libraries

### PR DESCRIPTION
**Pull request by kubamracek**
rdar://99833812

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Review by etcwilde — APPROVED** [review]
I think that should work to stop the failing tests. What happens if we test on a platform that needs the back deployed libraries though? Should the freestanding tests be able to locate the backdeploy libs and link them in?

**Comment by kubamracek** [comment]
Yes. But this config here is set up to specifically not support backdeployment (the libraries are not even produced). I think the code in lit.cfg is not super clear, but it's actually a very specific configuration (for the "minimal" bot that runs on macOS, links statically, etc.) rather than a general recipe for all possible standalone stdlib configurations.

**Pull request merged**
