### PR TITLE
[5.1-04-24] Fix closurescope analysis and capture promotion

### PR DESCRIPTION
**Pull request by aschwaighofer**
* CapturePromotion: Disable for dynamically_replaceable sil functions

rdar://50949761

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by bob-wilson** [comment]
This looks good to me, but I'll hold off approving it until the master PR gets a review from someone else.

**Review by bob-wilson — APPROVED** [review]

**Comment by najacque** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by aschwaighofer** [comment]
The linux failure is unrelated.

**Comment by aschwaighofer** [comment]
The mac os x failure is unrelated (same failure).

**Pull request merged**
