### PR TITLE
[SR-15562] [Sema] Do not consider warning fixes for non-augmenting fix recording

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
The problem is that for non-augmenting fixes(TreatRValueAsLValue) if there is already a fix recorded at that anchor or subexpr, this fix is not recorded. The problem in this case is since we move the checked cast warning diagnostics to fix format in #34980, warning fixes were also considered so a failure was being skipped which seems incorrect and it was causing the issue. Warning fixes should not be considered in that logic because this will cause this issue where a warning fix recorded makes  it skip the recording of any error fix which may lead the solver in this state of not able to produce a diagnostic.

Resolves SR-15562.

### CODE REVIEW

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test

**Review by xedin — APPROVED** [review]
Makes sense, thank you!

**Comment by LucianoPAlmeida** [comment]
Thanks @xedin! 
Quick question, was 5.6 branch already? If it was does it make sense to cherry-pick this?

**Comment by xedin** [comment]
Not yet, so this should make it no problem.

**Comment by LucianoPAlmeida** [comment]
> Also, I'm wrong - it was - https://github.com/apple/swift/tree/release/5.6 so you'd have to cherry-pick.

Ah ok, will do it then
Thank you :)

**Pull request merged**
