### PR TITLE
[DNM] Enable experimental lexical lifetimes to test.

### PR DESCRIPTION
**Pull request by nate-chandler**

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by atrick** [comment]
>

**Comment by gottesmm** [comment]
@swift-ci compiler performance

**Comment by gottesmm** [comment]
@swift-ci test compiler performance

**Comment by nate-chandler** [comment]
@swift-ci please test compiler performance

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Pull request closed without merging**
