### PR TITLE
[benchmark] Support multiple regular expression filters in Benchmark_Driver

### PR DESCRIPTION
**Pull request by palimondo**
This is a minor follow-up to #8975 Fix SR-4598 Add option to run subset of benchmarks matching a prefix.

It adds option to specify multiple prefixes and run all tests matching them. For example:
```
 ./Benchmark_Driver run -i 5 -f Prefix Suffix Drop 
```
runs all the benchmarks for the `Sequence` interface.

### CODE REVIEW

**Comment by swiftix** [comment]
@palimondo Can this new option be followed by other options or other arguments? If not, may be it is better to use multiple occurrences of `-f`, where each one defines a single prefix to be matched? E.g. something like:
`./Benchmark_Driver run -i 5 -f Prefix -f Suffix -f Drop further arguments go here`

Also, have you thought about using substrings or even regexes instead of string-based prefixes?

**Comment by atrick** [comment]
The relationship between the dashed argument '-f' and the positional arguments is unclear. Is the prefix string an argument of the '-f' option or does '-f' change the meaning of all positional arguments.

**Comment by palimondo** [comment]
I was hoping it would work like that, requiring multiple `-f`s, and was surprised by the description
```
Benchmark_Driver run --help
```
gave out… I have to look some more at `argparse` documentation.

The `-f` argument should be exclusive with the positional BENCHMARK arguments that normally go on at the end. At least that was my goal when I put them in mutually exclusive `benchmarks_group`.

**Comment by palimondo** [comment]
Ah, I got it. I shouldn’t have used `nargs` - that option specifies how many arguments get eaten. I need `action=‘append’`. I’ll push a fix as soon as my machine finished building master ⏲  and I can switch branch…

**Comment by palimondo** [comment]
@swiftix Re: substrings and regexes, I thought about that. Got scared and ran away… I mean, prefix works for my needs, but we could play with it, now that it’s in. Do you have specific use case in mind, or just thinking in the abstract?

**Comment by palimondo** [comment]
OK, I think this should work.

Old format doesn’t work anymore and verifies that the `-f` and `BENCHMARK`s are indeed exclusive:
```
$ ./Benchmark_Driver run -f Prefix Suffix Drop 
usage: Benchmark_Driver run [-h] [-f PREFIX] [-t TESTS] [-o OPT]
                            [-i ITERATIONS] [--output-dir OUTPUT_DIR]
                            [--swift-repo SWIFT_REPO]
                            [BENCHMARK [BENCHMARK ...]]
Benchmark_Driver run: error: argument BENCHMARK: not allowed with argument -f/--filter
```

I promote this feature in initial help (given that the subcommands arguments are hidden in their respective subcommand help...):

```
$ ./Benchmark_Driver -h
usage: Benchmark_Driver [-h] <command> ...

optional arguments:
  -h, --help  show this help message and exit

Swift benchmark driver commands:
  <command>   See COMMAND -h for additional arguments
    submit    Run benchmarks and submit results to LNT
    run       Run benchmarks and output results to stdout
    compare   Compare benchmark results

Example: ./Benchmark_Driver run -i 5 -f Prefix -f Suffix -f Drop
```

And now it works like this:

```
$ ./Benchmark_Driver run -f Prefix -f Suffix -f Drop 
57,DropFirstAnyCollection,1,368,368,368,0,368,10629120
58,DropFirstAnyCollectionLazy,1,183753,183753,183753,0,183753,10629120
59,DropFirstAnySeqCRangeIter,1,84233,84233,84233,0,84233,10723328
...
```

@swiftix @atrick @gottesmm Please review.

**Comment by palimondo** [comment]
Please review?

**Comment by palimondo** [comment]
@swiftix Turns out, supporting regular expressions was trivial. So I've added it.
Please review. // cc @atrick @gottesmm

**Comment by CodaFi** [comment]
@swift-ci please python lint

**Comment by CodaFi** [comment]
@swift-ci please python lint

**Comment by slavapestov** [comment]
Let's run the benchmarks just to be sure, then I will merge it.

@swift-ci Please benchmark

**Comment by CodaFi** [comment]
He rebased this, so once more with feeling: // @shahmishal 

@swift-ci please benchmark

**Comment by shahmishal** [comment]
@swift-ci Please smoke test

**Comment by palimondo** [comment]
Smoke test failed on python lint. But the "@swift-ci python lint" was successful? 🤷‍♂️🤦‍♂️
Looks like someone should have a look at that…

I have amended the python lint fixes and force pushed. @shahmishal Please rerun the smoke test.

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by palimondo** [comment]
Can this be merged?

**Review by atrick — APPROVED** [review]
LGTM

**Comment by shahmishal** [comment]
@palimondo thanks!!

**Pull request merged**
