### PR TITLE
[build-script] Fix build args passed to cmake commands that run tests.

### PR DESCRIPTION
**Pull request by gparker42**

### CODE REVIEW

**Comment by gparker42** [comment]
@swift-ci please smoke test

**Comment by gparker42** [comment]
@swift-ci please smoke test

**Comment by gparker42** [comment]
@gribozavr, can you double-check my shell-script skills? The symptom was that only the first argument in BUILD_ARGS ("-j4") was being passed to these cmake commands. Other values like "-v" from --verbose-build were dropped.

**Comment by gribozavr** [comment]
@gparker42 LGTM, thanks!

**Pull request merged**
