### PR TITLE
[Docs] improve @_spiOnly attribute info

### PR DESCRIPTION
**Pull request by MarcoEidinger**
Related to https://github.com/apple/swift/commit/b6800847481d29309fe86dd35c66aacc40bc9398

### CODE REVIEW

**Review by xymus — APPROVED** [review]
Makes sense, thank you!

**Comment by xymus** [comment]
We're old school here, we need to request the tests manually.

@swift-ci Please smoke test

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test macOS platform

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test Linux platform

**Pull request merged**
