### PR TITLE
 SIL: Don't drop generic signatures where all parameters are concrete

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@jrose-apple I realized this changes optimizer behavior; if the benchmark results are affected we'll have to tweak this a little bit.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please benchmark

**Comment by slavapestov** [comment]
Ok, this should now fix the optimizer crash. If it doesn't do it, I'll have to do a spot fix and postpone this for now since it's already more painful than I imagined.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please benchmark

**Comment by jrose-apple** [comment]
Is it just that we're considering these less profitable to inline or something?

**Comment by slavapestov** [comment]
@jrose-apple We don't inline generic functions at all actually

**Comment by gottesmm** [comment]
@slavapestov this is not true. I think we do it in the standard library. This is a piece of work that we did not have enough manpower to finish when @swiftix left. I think the problem was that we did not find a good heuristic yet that didn't create too much code-size increase. But for the stdlib it wasn't so bad and we saw nice perf increase.

**Comment by atrick** [comment]
@slavapestov are you picking this for 5.1? If so, I don't need to pick my fix.

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
