### PR TITLE
[Runtime] Rename swift_unknown* functions to swift_unknownObject*.

### PR DESCRIPTION
**Pull request by mikeash**
These functions don't accept local variable heap memory, although the names make it sound like they work on anything. When you try, they mistakenly identify such things as ObjC objects, call through to the equivalent objc_* function, and crash confusingly. This adds Object to the name of each one to make it more clear what they accept.

rdar://problem/37285743

### CODE REVIEW

**Comment by mikeash** [comment]
@swift-ci please test

**Review by gottesmm — APPROVED** [review]
LGTM

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test linux

**Comment by mikeash** [comment]
@swift-ci please test linux

**Pull request merged**
