### PR TITLE
swift-api-digester: include generic signature printing in the module dump.

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by slavapestov** [comment]
It looks like you don't need parentExtensionReqs anymore. Also for protocols, can you print the requirement signature instead of the generic signature?

**Comment by nkcsgexi** [comment]
@slavapestov ProtocolDecl's requirement signature contains multiple requirements. Do you think we should separately print them as multiple strings? or combining them into one is good enough?

**Comment by slavapestov** [comment]
Combining into one is enough. For ABI diffing, you’ll also want an option to print canonical generic signatures (and canonicalize all types in general).

**Comment by nkcsgexi** [comment]
Ok, I’ll merge this first and tackle canonical type in another pr.

**Pull request merged**
