### PR TITLE
Parse: Only diagnose dollar-prefixed identifiers that are Swift declarations

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
The `cannot declare entity named '$...'` error was allowed to be emitted on identifiers that are not themselves declarations.

### CODE REVIEW

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Comment by AnthonyLatsis** [comment]
@rintaro ping

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Review by rintaro — APPROVED** [review]
Sorry for the delay. LGTM!

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test macOS

**Pull request merged**
