### PR TITLE
Use Builtin.unreachable() in unavailable functions.

### PR DESCRIPTION
**Pull request by rudkx**
#### What's in this pull request?

Saves a bit of code size in the standard library by eliminating some
static strings and function calls.

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

Saves a bit of code size in the standard library by eliminating some
static strings and function calls.

rdar://problem/25767016

### CODE REVIEW

**Comment by rudkx** [comment]
cc: @gribozavr 

Dave / Dmitri - Please take a look and let me know if there is any objection to merging once tests complete.

**Comment by rudkx** [comment]
@swift-ci Please test.

**Comment by lattner** [comment]
Thank you for doing this @rudkx!

**Comment by gribozavr** [comment]
No objections, thanks @rudkx!

**Comment by rudkx** [comment]
@swift-ci Please test and merge.

**Pull request merged**
