### PR TITLE
Tests: Re-enable skip-function-bodies.swift

### PR DESCRIPTION
**Pull request by tshortli**
It doesn't appear to be failing anymore.

### CODE REVIEW

**Comment by tshortli** [comment]
@swift-ci please test

**Comment by tshortli** [comment]
@swift-ci please test Linux

**Comment by eeckstein** [comment]
It's failing here: https://ci.swift.org/job/oss-swift_tools-RA_stdlib-DA_test-simulators/3207/

**Comment by tshortli** [comment]
> It's failing here: https://ci.swift.org/job/oss-swift_tools-RA_stdlib-DA_test-simulators/3207/

Fixed properly here: https://github.com/apple/swift/pull/68736

**Pull request merged**
