### PR TITLE
Handle inaccurate ObjC nullability in `id`-as-`Any` bridging.

### PR DESCRIPTION
**Pull request by jckarter**
Make `id`-as-`Any` bridging resilient against ObjC APIs that claim to be `_Nonnull` but produce nil in practice, by wrapping up nils as `AnyObject?`s-inside-`Any`s instead of as invalid `AnyObject`s-inside-`Any`s. rdar://problem/27874026

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test macOS

**Comment by jckarter** [comment]
@slavapestov Mind reviewing this for Swift 3?

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@tkremenek Are you able to kill your previous test run? I just pushed a fix for a failure from the run before that.

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by shahmishal** [comment]
I killed this build because @jckarter requested.
> Build failed
Jenkins build - Swift Test OS X Platform
Git Commit - eb0d3c0
Test requested by - @tkremenek

**Comment by jckarter** [comment]
Thanks @shahmishal!

**Comment by slavapestov** [comment]
Looks good.

**Comment by jckarter** [comment]
Linux failure is the `no such module 'Dispatch'` thing; should be unrelated (and Linux is unlikely to be impacted by this change).

**Pull request merged**
