### PR TITLE
[WIP] Better synthesis of Hashable._hash(into:)

### PR DESCRIPTION
**Pull request by lorentey**
This is an unfinished update to #14913 that removes the glaring cheat of force-synthesizing `_hash(into:)` whenever we derive `hashValue`.

`_hash(into:)` is now automatically derived whenever it's not explicitly implemented, including inside classes and extensions of (possibly imported or synthesized) structs, enums or classes.

This is not entirely free of magic, though. To determine which implementation to generate, the body synthesizer takes a peek into the parent decl context -- if it finds an implicit `hashValue` there, the generated body implements hashing from scratch, feeding components into the hasher. Otherwise, we assume `hashValue` has an explicit implementation, and we generate the body for the (previously) default implementation of `_hash(into:)`.

To make `_CFObject`'s `Hashable` conformance apply correctly on CF types, I needed to add an explicit implementation of `_hash(into:)` to the CoreFoundation overlay. Without this change, the compiler would try to derive `_hash(into:)` directly into the imported CF types, which (understandably(?)) doesn't work. The problem seems to be that there is no other suitable DeclContext for the `Hashable` conformance, which in this case is implemented in a seemingly unrelated protocol extension. (This problem seems to be specific to CF types; I couldn't reproduce it with regular imported classes.)

This change also introduces some diagnostic regressions that are yet to be fixed.

### CODE REVIEW

**Comment by lorentey** [comment]
Cc @jrose-apple -- With the last two commits, `Hashable` derivation relies on the compiler's normal mechanism to derive `_hash(into:)` instead of the ugly piggybacking on `hashValue`.

Does this look reasonable? I'm a bit worried about that the CoreFoundation problem may indicate a deeper underlying issue.

**Comment by lorentey** [comment]
@swift-ci please smoke test

**Comment by lorentey** [comment]
@swift-ci please smoke test

**Comment by jrose-apple** [comment]
Without looking at the rest of the code, the CF issue sounds like it'll come into play whenever a protocol *other* than Hashable has a default implementation of `hashValue`. _SwiftNewtypeWrapper, for example (used for `NS_TYPED_ENUM` / `NS_STRING_ENUM` et al).

**Comment by jrose-apple** [comment]
Sorry, I guess that's specific to imported types. Maybe the way we do all other imported types is safe enough, since they're structs or enums and we can add things to them safely.

**Comment by lorentey** [comment]
Looking into this in a little more detail, CF types seem special because they gain the `_CFObject` conformance magically: the importer adds it to the opaque CF type as if it was directly on an imported class definition. 

We can't put new derived methods into that imported class, but adding the `_hash(into:)` definition into the CoreFoundation overlay looks like an acceptable workaround -- as long as there is no way for user-defined types to gain implicit conformances like that.

For non-magical imported types, the `Hashable` conformance must be added in some explicit extension somewhere, and the extension provides a suitable DeclContext for the derived `_hash(into:)` method -- so users would never run into the same situation.

**Comment by lorentey** [comment]
I (manually) merged this back to #14913, including the last commit that enables users to provide only one of `hashValue` and `_hash(into:)`, with the other member synthesized automatically by the compiler.

Some of the diagnostic regressions remain, and a test for an old compiler crasher exposed a new crash; I'll fix these on the primary PR soon.

**Pull request closed without merging**
