### PR TITLE
[4.0] [SR-5036]: Segfault using KeyPath with NSObject

### PR DESCRIPTION
**Pull request by jckarter**
Explanation: Key paths to final stored properties in NSObject subclasses would not get the correct field offset after ObjC ivar adjustment, leading to memory corruption.

Scope: Miscompile when using key paths with NSObject subclasses.

SR Issue: SR-5036, rdar://problem/32488871

Risk: Low, bug fix for new feature

Testing: Swift CI, test case from Jira

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@slavapestov I see this causes a behavior change in one of the reflection tests. Does the reflection library use the pre-adjustment field offsets for NSObject subclasses? I would expect the ultimate layout to remain the same. https://ci.swift.org/job/swift-PR-osx/8258/consoleFull#-845358922fca400bf-2f4a-462e-b517-e058d770b2d7

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@jckarter LGTM.

**Review by slavapestov — APPROVED** [review]

**Pull request merged**
