### PR TITLE
[WIP] Exclusivity access marker verification.

### PR DESCRIPTION
**Pull request by atrick**
This will be split into at least two PRs after the passes SCK testing.

The -verify-exclusivity flag will *not* be enabled in the final PR.

Access marker unit tests will be included in the final PR.

### CODE REVIEW

**Comment by atrick** [comment]
@rjmccall there's one commit here that you may want to look at "Emit unenforced access markers in SILGen"

**Comment by atrick** [comment]
@swift-ci Test Source Compatibility

**Comment by rjmccall** [comment]
Looks fine to me.

**Comment by atrick** [comment]
@swift-ci Test Source Compatibility

**Comment by atrick** [comment]
@swift-ci Test Source Compatibility

**Pull request closed without merging**
