### PR TITLE
[Index] Don't report extensions with nothing to index

### PR DESCRIPTION
**Pull request by xymus**
The indexer was looking into “empty” extensions to public types,
triggering the computation of the extension USR which could fail at
deserializing implementation-only imported types. As a solution,
don’t index extensions with no content to index.

rdar://70225906

### CODE REVIEW

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by xymus** [comment]
@rintaro @nathawes I'm not sure how to test this change, would you have suggestions or pointers for me?

**Comment by xymus** [comment]
Nevermind, it looks like there was already a test about this!

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by nathawes** [comment]
I think we may still need to still index "empty" extensions in user source code so global rename invoked on the type being extended will still be able to find and update the type names in the extensions themselves. IndexASTWalker has `IsModuleFile` and `isSystemModule` members you can use to refine the check, depending on whether it's an issue deserializing just system modules or user modules too.

The previously failing test was actually using the old indexing API (in sourcekitd) that we don't really use anymore. To add a test for the above change it'd be better to take a look at [test/Index/index_swift_only_system_module.swift](https://github.com/apple/swift/blob/main/test/Index/index_swift_only_systemmodule.swift). You basically want to copy it up to the end of the "Test-1" section and put an empty extension in your equivalent of `some-module.swift` (which becomes a system module) and one in `%s` (user code) and change the `c-index-test` invocation to do `-print-record` rather than `-print-unit`. Take a look at [test/Index/Store/record-sourcefile.swift](https://github.com/apple/swift/blob/main/test/Index/Store/record-sourcefile.swift) for an example of matching against the -print-record output.

Thanks for fixing this, and if you have any questions or want to look through it together feel free to Slack/video chat with me on Monday!

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by xymus** [comment]
I tweaked the fix to apply only on serialized module files. We don’t load implementation-only dependencies for local or system serialized modules so this bug could affect any modules, only partial modules should be safe but I wouldn’t expect them to be used here (?).

Thanks for the detailed guide for the test @nathawes! I’ve added `record-systemmodule.swift` and something to make sure that empty extensions are still recorded for source files. I used a different strategy to get to the serialized module, so let me know if you’d prefer a style closer to the other Index tests and I’ll fix it.

**Comment by nathawes** [comment]
Looks great - thanks!

**Pull request merged**
