### PR TITLE
[Print as C++] Don't crash on sugared types

### LINKED ISSUE #60850: Assertion failure `Ty->getDesugaredType() == Ty` in CFunctionSignatureTypePrinter::visitType
Given this source:

```swift
public func f(_: [Int]) { }
```

try to print a C++ header, like this:

```
swiftc -frontend -typecheck -module-name Blah -clang-header-expose-public-decls -emit-clang-header-path t.h t.swift
```

and we'll get an assertion here:

```
Assertion failed: (Ty->getDesugaredType() == Ty && "unhandle sugared type"), function visitType, file PrintClangFunction.cpp, line 131.
7  swift-frontend           0x0000000107277f28 (anonymous namespace)::CFunctionSignatureTypePrinter::visitValueType(swift::NominalType*, llvm::Optional<swift::OptionalTypeKind>, bool) (.cold.1) + 0
8  swift-frontend           0x0000000102f1c6d8 (anonymous namespace)::CFunctionSignatureTypePrinter::visitValueType(swift::NominalType*, llvm::Optional<swift::OptionalTypeKind>, bool) + 0
9  swift-frontend           0x0000000102f1ce8c swift::DeclAndTypeClangFunctionPrinter::printFunctionSignature(swift::AbstractFunctionDecl const*, llvm::StringRef, swift::Type, swift::DeclAndTypeClangFunctionPrinter::FunctionSignatureKind, llvm::ArrayRef<swift::DeclAndTypeClangFunctionPrinter::AdditionalParam>, swift::DeclAndTypeClangFunctionPrinter::FunctionSignatureModifiers)::$_3::operator()(swift::ParamDecl const*) const + 668
```

### PR DESCRIPTION
**Pull request by DougGregor**
Fixes https://github.com/apple/swift/issues/60850

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by hyp** [comment]
@DougGregor semantic interop tests go to test/Interop/SwiftToCxx

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test macOS

**Pull request merged**
