### PR TITLE
[lldb] Add a formatter for `swift::Demangle::Node`

### PR DESCRIPTION
**Pull request by broadwaylamb**
Before:
Screenshot 2021-12-15 at 19 28 50

After:
Screenshot 2021-12-15 at 19 00 20

### CODE REVIEW

**Comment by augusto2112** [comment]
@swift-ci test

**Comment by augusto2112** [comment]
@swift-ci smoke test

**Review by augusto2112 — APPROVED** [review]
Thanks for doing this!

**Comment by broadwaylamb** [comment]
ping

**Comment by augusto2112** [comment]
@swift-ci smoke test

**Comment by augusto2112** [comment]
@broadwaylamb it looks like this breaks the python_lint.swift test. Could you update your changes to make the linter happy?

```
******************** TEST 'Swift-validation(macosx-x86_64) :: Python/python_lint.swift' FAILED ********************
Script:
--
: 'RUN: at line 8';   /Applications/Xcode-beta.app/Contents/Developer/usr/bin/python3 /Users/buildnode/jenkins/workspace/swift-PR-macos-smoke-test/branch-main/swift/utils/python_lint.py
--
Exit Code: 1

Command Output (stdout):
--
./utils/lldb/lldbSwiftDataFormatters.py:76:89: E501 line too long (93 > 88 characters)
./utils/lldb/lldbSwiftDataFormatters.py:83:24: E126 continuation line over-indented for hanging indent
./utils/lldb/lldbSwiftDataFormatters.py:98:9: E722 do not use bare 'except'
./utils/lldb/lldbSwiftDataFormatters.py:112:89: E501 line too long (91 > 88 characters)
./utils/lldb/lldbSwiftDataFormatters.py:113:89: E501 line too long (89 > 88 characters)
./utils/lldb/lldbSwiftDataFormatters.py:114:89: E501 line too long (95 > 88 characters)
./utils/lldb/lldbSwiftDataFormatters.py:127:89: E501 line too long (127 > 88 characters)
./utils/lldb/lldbSwiftDataFormatters.py:141:89: E501 line too long (113 > 88 characters)
./utils/lldb/lldbSwiftDataFormatters.py:149:89: E501 line too long (101 > 88 characters)
./utils/lldb/lldbSwiftDataFormatters.py:152:89: E501 line too long (101 > 88 characters)
./utils/lldb/lldbSwiftDataFormatters.py:153:89: E501 line too long (90 > 88 characters)
```

**Comment by broadwaylamb** [comment]
@augusto2112 should be fixed.

**Comment by augusto2112** [comment]
@swift-ci smoke test

**Comment by augusto2112** [comment]
The windows test failure seems unrelated to this change (`module-cache-diagnostics.swift`), so I'm merging this. Thanks for doing this @broadwaylamb!

**Pull request merged**
