### PR TITLE
Update LLVM to stable/20240723

### PR DESCRIPTION
**Pull request by bnbarham**

### CODE REVIEW

**Comment by bnbarham** [comment]
https://github.com/swiftlang/swift-driver/pull/1718

@swift-ci please test

**Review by shahmishal — APPROVED** [review]

**Comment by bnbarham** [comment]
@swift-ci Please Build Toolchain UBI9

**Comment by bnbarham** [comment]
@swift-ci Please Build Toolchain CentOS 7

**Comment by bnbarham** [comment]
@swift-ci Please Build Toolchain Ubuntu 20.04

**Comment by bnbarham** [comment]
@swift-ci Please Build Toolchain Ubuntu 22.04

**Comment by bnbarham** [comment]
@swift-ci Please Build Toolchain Amazon Linux 2

**Comment by bnbarham** [comment]
@swift-ci please build toolchain macOS

**Comment by bnbarham** [comment]
@swift-ci please test Windows platform

**Comment by bnbarham** [comment]
@swift-ci please build toolchain Windows

**Comment by bnbarham** [comment]
https://github.com/swiftlang/swift-driver/pull/1718

@swift-ci please test windows platform

**Comment by bnbarham** [comment]
Let's try again after https://github.com/swiftlang/swift-foundation/pull/1010

**Comment by bnbarham** [comment]
https://github.com/swiftlang/swift-driver/pull/1718

@swift-ci please test windows platform

**Comment by bnbarham** [comment]
https://github.com/swiftlang/swift-driver/pull/1718

@swift-ci please build toolchain Windows

**Comment by bnbarham** [comment]
https://github.com/swiftlang/swift-driver/pull/1718

@swift-ci please build toolchain Windows

**Comment by bnbarham** [comment]
@swift-ci please test

**Pull request merged**
