### PR TITLE
Run checkPatternBindingCaptures on Extensions

### PR DESCRIPTION
**Pull request by CodaFi**
Neglecting to emit a diagnostic here caused us to submit invalid ASTs to SILGen.  I'm really hoping this isn't source breaking...

Resolves rdar://57188331, rdar://56467142, and SR-11636

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by theblixguy** [comment]
Can you update SR-11636? Since someone else started work on it recently

**Comment by CodaFi** [comment]
Oops, didn't meant to stop somebody else's work here.  Sorry Ziyuan!

**Review by slavapestov — APPROVED** [review]

**Comment by CodaFi** [comment]
What's up with Linux smoke testing this week?

@swift-ci please test Linux platform

**Comment by CodaFi** [comment]
⛵️

**Pull request merged**
