### PR TITLE
[Concurrency] Enable concurrent global executor on non-Darwin platforms

### PR DESCRIPTION
**Pull request by drexin**

### CODE REVIEW

**Comment by drexin** [comment]
@swift-ci test

**Review by ktoso — APPROVED** [review]

**Review by rjmccall — APPROVED** [review]
LGTM!  Thanks for following through on this.

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@swift-ci test

**Review by kavon — APPROVED** [review]

**Pull request merged**
