### PR TITLE
[Concurrency] Suppress diagnostics about non-`Sendable` async iterator arguments in implicit calls to `next()`.

### PR DESCRIPTION
**Pull request by hborla**
Async iterators are not `Sendable`; they're only meant to be used from the isolation domain that creates them. But the `next()` method runs on the generic executor, so calling it from an actor-isolated context passes non-`Sendable` state across the isolation boundary. `next()` should inherit the isolation of the caller (Swift evolution pitch incoming!), but for now, use the `nonisolated(unsafe)` opt out on the local iterator variable.

Resolves rdar://119613738

### CODE REVIEW

**Comment by hborla** [comment]
@swift-ci please smoke test

**Review by sophiapoirier — APPROVED** [review]

**Comment by vanvoorden** [comment]
@hborla Hi! I think I'm getting a similar warning from an `AsyncStream` with a 6.0 toolchain build:

```
Transferring '$generator' may cause a race; this is an error in the Swift 6 language mode
```

Do you have any idea if that sounds like something that will be fixed before 6.0 is live? Did you land any diffs or open any issues this year I can watch to follow along? Thanks!

**Comment by hborla** [comment]
@vanvoorden This is fallout from enabling SE-0414 under `-strict-concurrency=complete`. It's just a bug in the implementation. I filed https://github.com/apple/swift/issues/72942 for you to track the fix.

**Comment by vanvoorden** [comment]
@hborla Sounds good. Thanks!

**Pull request merged**
