### PR TITLE
[NFC][Python: black] Reformatted the benchmark Python sources using utils/python_format.py.

### PR DESCRIPTION
**Pull request by Rostepher**
Builds on the changes in #29718.

### CODE REVIEW

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by Rostepher** [comment]
@swift-ci please benchmark

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by Rostepher** [comment]
@swift-ci please benchmark

**Comment by Rostepher** [comment]
@swift-ci please benchmark

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by Rostepher** [comment]
@swift-ci please benchmark

**Comment by Rostepher** [comment]
@swift-ci please clean test

**Comment by palimondo** [comment]
I really think this was the opposite of a good idea! It has created completely unnecessary merge conflicts for me in pending PR #26462 and had hurt the readability of source code in many places. Can we please revert this?
cc @eeckstein @gottesmm

**Pull request merged**
