### PR TITLE
[SILGEN] Inject "willThrow" hooks after foreign error propagation.

### PR DESCRIPTION
**Pull request by kitaisreal**
1. Don't inject "willThrow" hooks before rethrow propagation branches.
2. Inject "willThrow" hooks after foreign error propagation branches.
3. Updated tests

cc @jckarter
More information in ticket: https://bugs.swift.org/browse/SR-11803

### CODE REVIEW

**Review by jckarter — APPROVED** [review]
LGTM. @dcci or @adrian-prantl might want to look over this too. Does this adequately preserve coverage for "Swift Error" breakpoints?

**Comment by adrian-prantl** [comment]
@kitaisreal Can you explain why it is safe to omit these specific willThrow calls in this patch?

**Comment by jckarter** [comment]
The error should already have been thrown at the point these calls were being inserted. This patch should affect paths where an already-thrown error is being propagated up the callstack.

**Comment by adrian-prantl** [comment]
That seems reasonable then.

**Review by dcci — APPROVED** [review]

**Comment by dcci** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
⛵️

**Comment by CodaFi** [comment]
@kitaisreal Don't forget to update the SR!

**Pull request merged**
