### PR TITLE
Update for LLVM API change D20147.

### PR DESCRIPTION
**Pull request by adrian-prantl**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci: please test and merge

**Comment by gparker42** [comment]
@swift-ci: please test and merge

**Comment by gparker42** [comment]
@swift-ci: please test and merge

**Comment by adrian-prantl** [comment]
@swift-ci: please test and merge

**Comment by adrian-prantl** [comment]
@swift-ci please test and merge

**Comment by adrian-prantl** [comment]
@swift-ci Please test

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
And now with testcase updates!
@swift-ci test and merge

**Comment by shahmishal** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
Linux bot has an unrelated failure:
```
18:02:37 <unknown>:0: error: error parsing input file '/tmp/TemporaryFile.Cx9Ell' (expected top-level entity)
18:02:37 Can't parse Package.swift manifest file because it contains invalid format. Fix Package.swift file format and try again.
```

**Comment by adrian-prantl** [comment]
@swift-ci test Linux platform

**Comment by adrian-prantl** [comment]
Let's give it one more try.
swift-ci please smoke test and merge

**Comment by adrian-prantl** [comment]
@swift-ci please smoke test and merge

**Comment by adrian-prantl** [comment]
@swift-ci please smoke test and merge

**Comment by adrian-prantl** [comment]
@swift-ci smoke test and merge

**Comment by adrian-prantl** [comment]
thanks @shahmishal!

**Pull request merged**
