### PR TITLE
Introduce ForwardingOperation wrapper type 

### PR DESCRIPTION
**Pull request by meg-gupta**

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci test

**Review by nate-chandler — APPROVED** [review]
lgtm!

(Might want a slightly less generic filename than "WrapperTypes"--maybe something about "Operation" considering all the types are named that way.)

**Comment by meg-gupta** [comment]
@nate-chandler I renamed to 'InstWrappers'

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Pull request merged**
