### PR TITLE
demangler: catch more cases where the demangler crashes on malformed symbols

### PR DESCRIPTION
**Pull request by eeckstein**
rdar://problem/36337512

and update type mangling rule in mangling ABI doc

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci smoke test and merge

**Review by xedin — CHANGES_REQUESTED** [review]
Thanks, @eeckstein!

**Review by xedin — APPROVED** [review]

**Comment by xedin** [comment]
Looks like there is a problem in build file on Linux:

```
CMake Error at cmake/modules/AddLLDB.cmake:69 (add_llvm_install_targets):
  Unknown CMake command "add_llvm_install_targets".
Call Stack (most recent call first):
  source/API/CMakeLists.txt:22 (add_lldb_library)
```

**Comment by eeckstein** [comment]
@swift-ci smoke test linux

**Comment by eeckstein** [comment]
@swift-ci smoke test linux

**Comment by eeckstein** [comment]
@swift-ci smoke test linux

**Pull request merged**
