### PR TITLE
NFC: Solidify and tidy up the BraceStmt interface

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
Provide simpler shortcuts and get rid of all the unnecessary indexing.

### CODE REVIEW

**Review by CodaFi — APPROVED** [review]
LGTM

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
⛵️

**Comment by AnthonyLatsis** [comment]
Thanks, Robert!

**Pull request merged**
