### PR TITLE
Re-enable a test that had been disabled at one point.

### PR DESCRIPTION
**Pull request by rudkx**
We saw a failure of this test on Linux at some point, and disabled
it. It looks like it may have been due to the fact that the
`%target-typecheck-verify-swift` provides the filename, but we
explicitly provide the filename in the test invocation here as well.

I'm going to re-enable and see if we can get through tests on all
supported platforms.

Fixes: rdar://problem/44305428

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
You should remove the file name then!

**Comment by rudkx** [comment]
@jrose-apple Yes, I'm planning on it and won't merge this until that time. I wanted to see if we somehow had some unusual difference in behavior between the platforms first. It's possible this had also started failing on macOS but it wasn't noticed by the time the test was disabled.

**Comment by rudkx** [comment]
Passes with test re-enabled. Will push a change to remove the duplicated filename, retest and merge.

**Comment by rudkx** [comment]
@swift-ci Please smoke test and merge

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Pull request merged**
