### PR TITLE
Sema: Allow unavailable protocol witnesses in unavailable nominals or extensions

### PR DESCRIPTION
**Pull request by tshortli**
Resolves rdar://99451416

### CODE REVIEW

**Comment by tshortli** [comment]
@swift-ci please test

**Comment by tshortli** [comment]
@swift-ci please test

**Comment by tshortli** [comment]
@swift-ci please test

**Review by nkcsgexi — APPROVED** [review]
Change seems reasonable to me.

**Review by artemcm — APPROVED** [review]

**Comment by tshortli** [comment]
@swift-ci please test macOS

**Pull request merged**
