### PR TITLE
[Name Lookup, ASTScope] simplified and debugged

### PR DESCRIPTION
**Pull request by davidungar**
Improved draft of ASTScope lookup, disabled by default. Includes options to enable or disable, and parser lookup disable option. Passes tests per `ninja check-swift`  with  `export SWIFT_TEST_OPTIONS=-enable-astscope-lookup` set for XFAIL purposes.

### CODE REVIEW

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Comment by davidungar** [comment]
@swift-ci please clean smoke test os x platform

**Comment by davidungar** [comment]
@swift-ci please clean smoke test

**Comment by davidungar** [comment]
@swift-ci please smoke test osx platform

**Comment by davidungar** [comment]
@swift-ci please smoke test os x platform

**Comment by davidungar** [comment]
@swift-ci please smoke test os x platform

**Comment by davidungar** [comment]
@swift-ci please smoke test os x platform

**Comment by davidungar** [comment]
@swift-ci please smoke test linux platform

**Comment by davidungar** [comment]
@swift-ci please smoke test linux platform

**Comment by compnerd** [comment]
This seems to have caused a regression on Windows.  https://dev.azure.com/compnerd/3133d6ab-80a8-4996-ac4f-03df25cd3224/_apis/build/builds/3656/logs/31

**Pull request merged**
