### PR TITLE
[5.3] [TBDGen] Fix symbol mismatch for enum case constructors

### PR DESCRIPTION
**Pull request by theblixguy**
Cherry-pick of #31826 and commit bba87cd which is needed for this branch only.

---

**Explanation**: TBDGen validation fails with an error: `symbol '<case constructor symbol here>' is in generated IR file, but not in TBD file` when we pass the `-enable-testing` flag, when using enum cases as protocol witnesses.

**Scope**: Affects use of enum cases constructors to satisfy static protocol requirements ([SE-0280](https://github.com/apple/swift-evolution/blob/master/proposals/0280-enum-cases-as-protocol-witnesses.md))

**SR Issue**: SR-12821 / rdar://problem/63364542

**Risk**: Low. This is a regression since [SE-0280](https://github.com/apple/swift-evolution/blob/master/proposals/0280-enum-cases-as-protocol-witnesses.md) landed.

**Testing**: Added new TBDGen tests.

**Reviewed by:** @slavapestov

### CODE REVIEW

**Comment by theblixguy** [comment]
@swift-ci please test

**Comment by slavapestov** [comment]
It looks like we need to cherry-pick @jckarter's fix bba87cdc10d411f2f7ee3271aa9e457fc43c9b48 into this PR to get the test to pass on macOS. Do you mind doing that?

**Comment by theblixguy** [comment]
@slavapestov Thanks! I have cherry-picked that commit into this branch.

@swift-ci please test

**Comment by slavapestov** [comment]
Thanks! I'll file the necessary paperwork internally to get this PR approved once the tests pass.

**Comment by jckarter** [comment]
@slavapestov OK by me. Thanks for fixing this @theblixguy!

**Review by tkremenek — APPROVED** [review]

**Pull request merged**
