### PR TITLE
linux: remove swiftImageInspectionShared

### PR DESCRIPTION
**Pull request by compnerd**
Merge this into the runtime as expected rather than having a separate
component.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @spevans @bob-wilson @jrose-apple 

What could go wrong?

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by bob-wilson** [comment]
I think I have a better solution. At least I understand better what happened to cause this. Let me create a PR....

**Comment by bob-wilson** [comment]
See https://github.com/apple/swift/pull/14880

**Comment by bob-wilson** [comment]
(I'm not opposed to removing the library if that's the right thing to do, but I'd much prefer a more minimal solution for Swift 4.1.)

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by bob-wilson** [comment]
Even if this is the right thing to do, can you please hold off merging it until after we've tested #14880 and confirmed that it fixes SR-7038?

**Comment by compnerd** [comment]
@bob-wilson sure thing

**Comment by compnerd** [comment]
@bob-wilson okay with me rebasing/merging this?

**Comment by bob-wilson** [comment]
Now that we've sorted out SR-7038, I have no objections from a process perspective. On the technical front, I am confused. When we tried to stop linking that library, things broke, right? What is different now?

**Comment by compnerd** [comment]
The change is merging the provider into the runtime itself.  So when the runtime is linked, the dependency is satisfied.

**Comment by bob-wilson** [comment]
OK, I guess that should be fine then. Someone else who understands this better should review it.

**Comment by jrose-apple** [comment]
That's probably @jckarter (sorry, @jckarter).

**Comment by jckarter** [comment]
I haven't been following these changes close enough to comment, sorry.

**Comment by CodaFi** [comment]
@compnerd Could you rebase this so we can get it merged?

**Comment by compnerd** [comment]
CC: @spevans

@CodaFi necromancing level infinity! :-p

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by CodaFi** [comment]
Cool!

**Comment by spevans** [comment]
The reason for have `ImageInspectionShared` and `ImageInspectionStatic` is that there are two versions of `lookupSymbol` that need to be linked in:

The version in `ImageInspectionShared` uses `dladdr()` and is used to support `-static-stdlib` . The other version in `ImageInspectionStatic` uses its own implementaion to parse a static ELF binary when used with `-static-executable`. This is used by #29039

**Comment by compnerd** [comment]
I think that it makes sense to remove `lookupSymbol` from `SwiftRT-ELF.cpp`.  That file is meant for the metadata introspection.  It would make sense for that code-movement to be part of #29039 I think.

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Comment by spevans** [comment]
@compnerd I have done an updated version of this PR in #34180

**Comment by compnerd** [comment]
Great, I'll close this off then.

**Pull request closed without merging**
