### PR TITLE
[gardening] Remove unused method getLoweredContainerOfAddress(…)

### PR DESCRIPTION
**Pull request by practicalswift**

### CODE REVIEW

**Comment by practicalswift** [comment]
`getLoweredContainerOfAddress(…)` was added by @eeckstein back in January 2016 (6ff2f09796eb267570bc5ae988a25dc7ad300348).

The last usage of `getLoweredContainerOfAddress(…)` was removed by @aschwaighofer on 2016-11-16 (cd1037b799402f4d68322011ef1b196f94281cea).

@eeckstein + @aschwaighofer, please review :-)

**Comment by practicalswift** [comment]
@swift-ci please smoke test

**Comment by practicalswift** [comment]
@swift-ci please test

**Comment by slavapestov** [comment]
This type of thing doesn't really need review. Dead code is dead code. If there's no test for it then it never worked or did anything useful in the first place.

**Comment by practicalswift** [comment]
@slavapestov Excellent! Thanks for the clear guidance!

**Pull request merged**
