### PR TITLE
uniquely allocate AutoDiffParameterIndices and AutoDiffAssociatedFunctionIdentifier

### PR DESCRIPTION
**Pull request by marcrasi**
Resolves https://bugs.swift.org/browse/SR-9428.

### CODE REVIEW

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Comment by marcrasi** [comment]
@rxwei, I have deleted `isMethodFlag` from the indices.

@swift-ci please test tensorflow

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Review by rxwei — APPROVED** [review]
Nice! LGTM.

**Comment by rxwei** [comment]
Additional comments (which need not be addressed in the short term):
* It seems that this data structure can also be used for SIL for consistency and efficiency, especially when it no longer carries the `isMethod` flag. 
* Since we need to represent result selection in SIL functions using the same bit vector representation, would it make sense to rename this to `AutoDiffIndexSet` or `AutoDiffIndexSelection`?

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow linux gpu

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow linux

**Pull request merged**
