### PR TITLE
[Parse] Improve Lexer's UTF-8 BOM handling

### PR DESCRIPTION
**Pull request by omochi**
Current `Lexer` has a function to skip UTF-8 BOM.
But its behavior has some bugs.

- It skips shebang at the beginning of file, but does not with BOM.
- A token should be prefix operator at the beginning of file, but is become infix operator with BOM.
- It skips conflict marker, but does not with BOM.
- A token at the beginning of file should be `isAtStartOfLine`, but is not with BOM.

All these bugs are come from implementation of `Lexer` that `BufferStart` is regarded as the beginning of source code even if BOM was skipped.
In text file with BOM, the end of BOM should be regarded as the beginnig of text content.

This PR fix these issues.

A design is shown below.

In text file, the beginning of text content is ordinary the beginning of file.
But if there is a BOM, the end of BOM is.

So to represent the beginning of text content, `ContentStart` field is added to `Lexer`.

## note

Two bugs about BOM + shebang are at skipping logic in libParse and libSyntax(`Lexer::lexTrivia`) both.
This PR only fix and add testcase for libParse.

I think that libSyntax should not skip BOM and should keep it as LeadingTrivia.
But to implement this idea needs more changes,
So I plan to submit it as another PR in future.

---

Reported issues is not found in bugs.swift.org.

### CODE REVIEW

**Comment by CodaFi** [comment]
@harlanhaskins I definitely agree that libSyntax should retain the BOM as leading trivia for the first syntax node.

@swift-ci please smoke test

**Comment by harlanhaskins** [comment]
It might be fine to just use `TriviaKind::GarbageText` for this. It’s not meant to be parsed by swiftc and should remain transparent, but is necessary for a full source-accurate reprint.

**Review by rintaro — APPROVED** [review]
Good catch. Thank you @omochi !

**Comment by rintaro** [comment]
We also need to update here:
https://github.com/omochi/swift/blob/035e47851fe6b70877ece7de275953e30cabedee/lib/Parse/Lexer.cpp#L2396
I will do that in https://github.com/apple/swift/pull/13500

**Comment by omochi** [comment]
Thanks to review and merge.

**Pull request merged**
