### PR TITLE
IRGen GOT entry cleanup

### PR DESCRIPTION
**Pull request by slavapestov**
The code deciding whether a relative reference has to go through a GOT entry was overly complex and conservative. Replace it with a new implementation that tries to derive from first principles whether a symbol is going to end up in the same translation unit or not.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Review by jckarter — APPROVED** [review]
Awesome!

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by slavapestov** [comment]
@compnerd I was just thinking I should do that...

**Comment by compnerd** [comment]
This is pretty interesting, thanks for doing this cleanup.   This might actually make it easier to handle the Windows IRGen and DLL storage.

**Comment by jckarter** [comment]
@compnerd Hm, if we already have something that precisely determines whether a symbol will be in the current image or not, in order to properly dllimport/dllexport things, it seems like that's more or less exactly what we'd want to use when we decide to use an indirection for a relative reference here.

**Comment by compnerd** [comment]
@jckarter sadly we do not have that.  This is why everything currently is mislabelled. I’d like to use the same primitives to correctly annotate things.

**Pull request merged**
