### PR TITLE
[Build] Move the `.cfg` file generation to a new product.

### PR DESCRIPTION
**Pull request by al45tair**
We need to move the `.cfg` file generation to a new product so that we can land it in the default toolchain for Xcode.

rdar://128612098

### CODE REVIEW

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
**Explanation**: Because of the way Xcode gets built, the code in `llvm.py` that added the `.cfg` files doesn't result in them showing up in the toolchain there. We need to add another product to the build scripts and trigger that in the correct places.
**Original PR**: #73845 
**Risk**: Low. Adds a couple of extra files to the install directory, both of which only affect people trying to use the fully static Linux SDK. Doesn't affect anything else.
**Reviewed by**: TBC
**Resolves**: rdar://128612098
**Tests**: We're running builds to make sure the files arrive in the correct location.

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
@swift-ci Please test

**Review by edymtt — APPROVED** [review]

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
