### PR TITLE
[stdlib] Switch UnsafeMutableBufferPointer.subscript to use _modify

### PR DESCRIPTION
**Pull request by airspeedswift**
This will allow in-place modification of elements.

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@rjmccall I assume there's no reason I should be wary of a `nonumtating` `_modify`...

**Comment by rjmccall** [comment]
It's always possible that it provokes corner cases in the type-checker, but no, the mutating-ness of the base should be independent, just as it is for get/set.

**Pull request merged**
