### PR TITLE
Benchmarks for dropLast and suffix

### PR DESCRIPTION
**Pull request by therealbnut**
Adds benchmarks testing dropLast and suffix, so we have a baseline for optimisations and improvements.

Note: the various arrays seemed to be in alphabetical order, with a few exceptions. I sorted those where it seemed like it was meant to be. I'm happy to revert that.

This is in order to facilitate https://github.com/apple/swift/pull/7250

It also will allow us to determine the efficiency of the non-specialised `AnySequence` implementations. For example:

```bash
 54 DropLastAnySequence             3   31460   31927    31695      0      31695    4603904
 55 DropLastCountableRange          3     800     809      804      0        804    4575232
 56 DropLastSequence                3   67560   68419    68100      0      68100    4934315
```

Ideally `DropLastAnySequence` would perform similarly to `DropLastCountableRange` (as, in this case, it wraps a `RandomAccessCollection` and could find the dropped range in constant time). Likewise for `SuffixCountableRange`.

Helps benchmark [SR-413](https://bugs.swift.org/browse/SR-413).

### CODE REVIEW

**Comment by therealbnut** [comment]
CC @dabrahams - as discussed in #7250

**Comment by therealbnut** [comment]
Note, has an unexpected build error, hold off on CI for now

**Comment by airspeedswift** [comment]
The AnySequence perf's pretty disappointing, it's definitely dispatching to the underlying type's implementation so maybe it's specialization that's failing.

Other than that, these look good. Would you mind adding one for Array too?

**Comment by therealbnut** [comment]
@airspeedswift added array benchmarks in c6dc0b0
```diff
 DropLastAnySequence             3   33643   37585    35984      0      35984    4606635
+DropLastArray                   3    1114    1215     1148      0       1148    4609365
 DropLastCountableRange          3     774     783      779      0        779    4517888
 DropLastSequence                3   65900   66555    66242      0      66242    4722688
```
and
```diff
 SuffixAnySequence               3   36442   38835    37366      0      37366    4651691
+SuffixArray                     3    1196    1214     1204      0       1204    4614827
 SuffixCountableRange            3     832     864      851      0        851    4573867
 SuffixSequence                  3   61049   61647    61296      0      61296    4728149
```

**Comment by airspeedswift** [comment]
@swift-ci Please smoke test

**Comment by airspeedswift** [comment]
@swift-ci Please benchmark

**Comment by therealbnut** [comment]
thanks :)

**Comment by therealbnut** [comment]
@airspeedswift just merged master and fixed conflicts, I think I've addressed all your feedback, was this everything? :)

**Comment by lplarson** [comment]
@swift-ci benchmark

**Comment by lplarson** [comment]
@swift-ci benchmark

**Comment by lplarson** [comment]
@swift-ci smoke test

**Comment by lplarson** [comment]
I'll merge this once we get a clean benchmark run. Blocked on https://github.com/apple/swift/pull/7979.

**Comment by lplarson** [comment]
@swift-ci benchmark

**Comment by therealbnut** [comment]
Merged master, this should include the #7979 fix now, thanks @lplarson

**Comment by CodaFi** [comment]
(Drive-by benchmarking; don't mind me)

@swift-ci benchmark

**Comment by therealbnut** [comment]
@CodaFi I think there was a problem with the CI system on your drive-by benchmark, you may need to re-run it

**Comment by shahmishal** [comment]
@swift-ci benchmark

**Comment by lplarson** [comment]
@swift-ci smoke test and merge

**Comment by lplarson** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@lplarson Next time can we do a rebase so we don't have merges in the commit stream?

**Comment by therealbnut** [comment]
@gottesmm You can change GitHub settings to prevent merge commits, squash PRs by default, make master ff-only, and require CI

**Comment by therealbnut** [comment]
I think these settings would work well given the current workflow:

https://github.com/apple/swift/settings
screen shot 2017-03-15 at 8 58 25 am

https://github.com/apple/swift/settings/branches/master
screen shot 2017-03-15 at 9 00 56 am

**Comment by therealbnut** [comment]
It makes the same restrictions if you're pushing using `git` from the terminal

**Comment by therealbnut** [comment]
Thank you @airspeedswift for your review and @lplarson for your persistence in getting it through CI and merged 💖

**Comment by gottesmm** [comment]
I am fine with merge commits. Just not on the topic branch itself.

**Comment by palimondo** [comment]
@therealbnut said in initial comment:
> Ideally DropLastAnySequence would perform similarly to DropLastCountableRange

That is not possible. The way the test is written, `MySequence` wraps the CountableRange without forwarding to its `suffix` implementation - thereby explicitly defaulting to the implementation on Sequence. The issue reported in SR-413 was fixed a year ago (see the issue for details). cc @airspeedswift

**Comment by therealbnut** [comment]
@palimondo: Note, my comment was for <code>DropLast**AnySequence**</code> (which uses `AnySequence`) not `DropLastSequence` (which uses `MySequence`).

As you can see in the benchmarks run here, it is not fixed in February this year:
```
SuffixAnySequence               3   36442   38835    37366      0      37366    4651691
SuffixArray                     3    1196    1214     1204      0       1204    4614827
```

**Comment by therealbnut** [comment]
The test intentionally does not forward to Array's `suffix` implementation in order to call the unspecialised defaulted `suffix`.

 * `DropLastSequence` benchmark tests the performance of the default implementation on `Sequence`
 * `DropLastCountableRange` benchmark tests the performance of the specialised implementation on `CountableRange`
 * `DropLastAnySequence` benchmark tests the performance of `AnySequence` which will fall somewhere around `DropLastSequence` at the moment, but ideally it would use `CountableRange`'s specialisation and perform similarly. To do this it needs generic magic that Swift doesn't have yet afaik.

Until **AnySequence** calls through to the specialised implementation [SR-413](https://bugs.swift.org/browse/SR-413) is not considered to be fixed.

**Comment by dabrahams** [comment]
I've done some work in the unicode-rethink branch to simplify forwarding collection APIs and to ensure that all customization points actually get forwarded: https://github.com/apple/swift/blob/unicode-rethink/stdlib/public/core/ForwardingWrapper.swift.gyb

Also, I've been building a new suite of collection wrappers for unicode support using techniques that could greatly benefit AnyCollection et al. by avoiding the need for a dynamically-allocated box in many cases: https://github.com/apple/swift/blob/unicode-rethink/stdlib/public/core/AnyUnicode.swift.gyb#L418

On that basis, I would not invest too much energy in tuning the performance of the existing implementations.

**Comment by therealbnut** [comment]
Sounds great!

**Comment by palimondo** [comment]
@therealbnut *AnySequence* does call through to the specialized implementation on the underlying collection. The performance issue you are seeing is due to iterating over elements through the `_IteratorBox` using witness table of the generic protocol implementation. 

Coincidentally the remaining number of elements in the suffix were just so that it gave similar timing as default implementation on the `Sequence`. I’ve marked [SR-413](https://bugs.swift.org/browse/SR-413) as Resolved:Done and opened [SR-4499](https://bugs.swift.org/browse/SR-4499) to track the underlying performance issue in existential collections.

**Pull request merged**
