### PR TITLE
Fix the no-swift-assert stdlib build.

### PR DESCRIPTION
**Pull request by atrick**
Partially revert a recent attempt to fix build warnings.

### CODE REVIEW

**Comment by atrick** [comment]
Fixes <rdar://problem/43824067> Swift CI: 1. OSS - Swift (Tools Opt+No Assert, Stdlib Opt+DebInfo, Test Simulator) - OS X (master) - SimplifyCFG crashes at AssertCommon.swift:283:10

**Comment by jrose-apple** [comment]
Oh no, my bad. @airspeedswift

**Comment by atrick** [comment]
@swift-ci smoke test and merge.

**Comment by atrick** [comment]
@swift-ci smoke test.

**Comment by airspeedswift** [comment]
Oops, sorry!

Course, if we did a release build as part of PR testing _and_ failed on warnings, we'd catch both problems :)

**Comment by jrose-apple** [comment]
Next time "test with preset", I guess.

**Pull request merged**
