### PR TITLE
[DNM][WIP] Reject unsound pointer conversions

### PR DESCRIPTION
**Pull request by hamishknight**
This is still a WIP, but the end goal is reject unsound inout-to-pointer, array-to-pointer and string-to-pointer conversions through the introduction of an underscored `@_nonEphemeral` attribute that marks pointer parameters where you cannot pass a temporary pointer argument produced from one of the aforementioned conversions (resolving [SR-2790](https://bugs.swift.org/browse/SR-2790)).

My rough plan of action is as follows:

1. **In this PR:** I'd like to run this against the compat suite to get a rough idea of what the breakage is like (from my own experience at least, I've seen these temporary pointer conversions being accidentally misused a decent amount).

2. If we're okay with making this change (unsure if this will require Swift Evolution discussion), I'll split this up – one PR for the warning and, assuming the source break isn't too widespread, one PR for the error (the details of exactly what swift version to make the switch can be discussed then). If possible, I'd like to get the warning patch in for Swift 5 (I'm hoping that splitting it up will make this easier).

3. Start a discussion on whether there's any merit to de-underscoring this attribute for usage outside of the standard library and/or exposing it to Clang for usage in (Obj-)C APIs when imported into Swift.

Any feedback on this change is greatly appreciated!

### CODE REVIEW

**Comment by jrose-apple** [comment]
(as requested by Hamish on the bug)

@swift-ci Please test source compatibility

**Comment by hamishknight** [comment]
Ah, llbuild is escaping array-to-pointer conversions, opened a PR to fix: https://github.com/apple/swift-llbuild/pull/387

**Comment by hamishknight** [comment]
@atrick Thanks for taking a look! What are your thoughts on allowing `@_nonEphemeral` inout-to-pointer conversions for stored properties on final class global/static vars? i.e allowing:

```swift
final class C {
  var foo: Int = 0
}
var c = C()
let ptr = UnsafePointer(&c.foo)
```

As I understand it, this isn't inherently unsound as we can project the address of the property. However it is certainly a questionable thing to being doing, and would likely be better served by an API that provides scoped pointer access, such as `withUnsafePointer(to:)`, which can guarantee that the object stays alive for the duration.

For now this patch rejects the above, only allowing `struct` bases – I'm curious to see if anything in the source compat suite is actually doing this. But arguably we should allow it if it's not inherently unsound. Thoughts?

**Comment by jrose-apple** [comment]
We made a promise that global/static vars will have stable addresses for use as KVO/pthread-style context pointers. Instance properties are a little less clear-cut, though. cc @rjmccall too

**Comment by hamishknight** [comment]
llbuild fix merged – could someone please kick off the source compat suite again?

**Comment by atrick** [comment]
@swift-ci test source compatibility.

**Comment by hamishknight** [comment]
Okay, so looking over the failures, we have 27 failures out of 182 targets that aren't XFailed (there were also 8 failures for Reactive(Cocoa/Swift) in debug builds that look unrelated – they seem to be consistently failing).

Broken down by project:
- CoreStore
  - 1x array-to-pointer in buffer pointer init
- Kitura
  - 5x array-to-pointer in pointer init
  - 1x string-to-pointer in pointer init
  - 1x inout-to-pointer in pointer init
- Kronos
  - 3x inout-to-pointer in buffer pointer init
- Perfect
  - 9x array-to-pointer in pointer init
- SRP -> BigInt -> SipHash
  - 15x inout-to-pointer in buffer pointer init
- Starscream
  - 2x array-to-pointer in pointer init
- Surge
  - 4x array-to-pointer in DSPSplitComplex initialiser
- SwiftLint -> Yams
  - 1x inout-to-pointer in pointer init

Totals:
- 21x array-to-pointer
- 1x string-to-pointer
- 20x inout-to-pointer

**Comment by jrose-apple** [comment]
I wonder if enforcing this for locals is a case where we should just implement DWIM behavior, like union-casting in C. "If the address is taken and immediately converted to a pointer, just require that it have the same stack address each time like in C".

**Comment by hamishknight** [comment]
As I understand it, the main problem with locals is that we don't currently guarantee that they'll stay initialised until the end of the stack frame, the optimiser is free to deinitialise them earlier. So you'd need to use something like `withExtendedLifetime`, but at that point you'd be better off using `withUnsafePointer(to:)`.

**Comment by hamishknight** [comment]
Realised I missed a useful case where we can infer `@_nonEphemeral`, namely enum case constructors for pointer payloads. I've just pushed the logic for that – would it be worth running the source compat suite on it?

**Comment by hamishknight** [comment]
I have also opened a PR for just the warning logic, which I feel is ready for review: https://github.com/apple/swift/pull/20467.

**Pull request closed without merging**
