### PR TITLE
[4.0] Revert "Re-instate "Improve disjunction selection""

### PR DESCRIPTION
**Pull request by rudkx**
This reverts commit
ecfa406fc580df48260c6ad606bfd11c10f6ad4c, which was reinstating
3c5b393e0c07c222950e626e5c4553358e22365d.

It does not revert one test change from that commit, because
inexplicably one of the tests is still failing, probably due to some
other changes that have happened since. I'm leaving a ticket open to
investigate.

I've added one of the new cases that is failing as a result of this
change.

This is being reverted not because of bugs in this particular commit,
but because it seems to be exposing other bugs in the type checker that
are resulting in source compatibility problems. We need to shake these
other bugs out of the type checker before bringing this change back.

Fixes rdar://problem/32204276 and a few dups.

(cherry picked from commit bc7dff5c9f1a861682eadd87e6631b1c78540cb4)

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please test

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
Compatibility test failures appear to be some kind of configuration issue.

**Comment by shahmishal** [comment]
@rudkx This was due to `update-checkout` script not fetching before changing to swift-4.0-branch. 

I just re-triggered the bot.

**Review by DougGregor — APPROVED** [review]
LGTM, too bad we had to revert

**Comment by rudkx** [comment]
Time-out on Linux during swiftpm testing.

**Comment by rudkx** [comment]
@shahmishal Looks like the compatibility tests are still failing for the same reason.

**Comment by rudkx** [comment]
@swift-ci Please test Linux platform

**Comment by rudkx** [comment]
@swift-ci Please test

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by shahmishal** [comment]
@rudkx I am looking into the issue.

**Comment by shahmishal** [comment]
@swift-ci Please test source compatibility

**Pull request merged**
