### PR TITLE
Fix main -> rebranch merge conflict

### PR DESCRIPTION
**Pull request by etcwilde**
Merge conflict while removing `nocapture` from
`s21move_function_dbginfo20addressOnlyValueTestyyxAA1PRzlF`. Resolution
was to remove nocapture from the expected output in both cases:
```
// CHECK-LABEL: define swiftcc void @"$s21move_function_dbginfo20addressOnlyValueTestyyxAA1PRzlF"(ptr noalias[-nocapture-] %0, ptr %T, ptr %T.P)
```

Conflict cause: 4858cb62253823f4467d8ea7d1cbae526acad66c
This is the same as the original change to this file. The conflict seems
to be due to the next line changing, when moving from llvm.dbg.addr to
llvm.dbg.value.

Conflicts:
  - test/DebugInfo/move_function_dbginfo.swift

### CODE REVIEW

**Comment by etcwilde** [comment]
@swift-ci please smoke test

**Review by adrian-prantl — APPROVED** [review]

**Comment by etcwilde** [comment]
Unexpected Linux Failures:
```
FAILED: lib/SILOptimizer/CMakeFiles/swiftSILOptimizer.dir/UtilityPasses/Link.cpp.o 
/opt/swift/5.8.1/usr/bin/clang++ -DCMARK_STATIC_DEFINE -DGTEST_HAS_RTTI=0 -DSWIFT_LLVM_SUPPORT_IS_AVAILABLE -DSWIFT_TARGET -DSWIFT_THREADING_LINUX -D_DEBUG -D_GLIBCXX_ASSERTIONS -D_LIBCPP_ENABLE_HARDENED_MODE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/home/build-user/build/buildbot_linux/swift-linux-x86_64/lib/SILOptimizer -I/home/build-user/swift/lib/SILOptimizer -I/home/build-user/swift/stdlib/public/SwiftShims -I/home/build-user/build/buildbot_linux/swift-linux-x86_64/include -I/home/build-user/swift/include -I/home/build-user/llvm-project/llvm/include -I/home/build-user/build/buildbot_linux/llvm-linux-x86_64/include -I/home/build-user/llvm-project/clang/include -I/home/build-user/build/buildbot_linux/llvm-linux-x86_64/tools/clang/include -I/home/build-user/cmark/src/include -I/home/build-user/build/buildbot_linux/cmark-linux-x86_64/src -I/home/build-user/swift-corelibs-libdispatch/src/BlocksRuntime -I/home/build-user/swift-corelibs-libdispatch -Wno-unknown-warning-option -Werror=unguarded-availability-new -fno-stack-protector -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-class-memaccess -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -Werror=switch -Wdocumentation -Wimplicit-fallthrough -Wunreachable-code -Woverloaded-virtual -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -O3 -DNDEBUG  -fno-exceptions -funwind-tables -fno-rtti -Werror=gnu -Werror=c++98-compat-extra-semi -UNDEBUG -target x86_64-unknown-linux-gnu -O2 -g0 -march=core2 -std=c++17 -MD -MT lib/SILOptimizer/CMakeFiles/swiftSILOptimizer.dir/UtilityPasses/Link.cpp.o -MF lib/SILOptimizer/CMakeFiles/swiftSILOptimizer.dir/UtilityPasses/Link.cpp.o.d -o lib/SILOptimizer/CMakeFiles/swiftSILOptimizer.dir/UtilityPasses/Link.cpp.o -c /home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp
In file included from /home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:58:
/home/build-user/swift/include/swift/Runtime/RuntimeFunctions.def:57:10: error: too many arguments provided to function-like macro invocation
         UNKNOWN_MEMEFFECTS)
         ^
/home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:48:13: note: macro 'FUNCTION' defined here
    #define FUNCTION(ID, NAME, CC, AVAILABILITY, RETURNS, ARGS, ATTRS, EFFECT) \
            ^
In file included from /home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:58:
/home/build-user/swift/include/swift/Runtime/RuntimeFunctions.def:67:10: error: too many arguments provided to function-like macro invocation
         UNKNOWN_MEMEFFECTS)
         ^
/home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:48:13: note: macro 'FUNCTION' defined here
    #define FUNCTION(ID, NAME, CC, AVAILABILITY, RETURNS, ARGS, ATTRS, EFFECT) \
            ^
In file included from /home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:58:
/home/build-user/swift/include/swift/Runtime/RuntimeFunctions.def:74:10: error: too many arguments provided to function-like macro invocation
         UNKNOWN_MEMEFFECTS)
         ^
/home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:48:13: note: macro 'FUNCTION' defined here
    #define FUNCTION(ID, NAME, CC, AVAILABILITY, RETURNS, ARGS, ATTRS, EFFECT) \
            ^
In file included from /home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:58:
/home/build-user/swift/include/swift/Runtime/RuntimeFunctions.def:82:10: error: too many arguments provided to function-like macro invocation
         MEMEFFECTS(ArgMemReadOnly))
         ^
/home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:48:13: note: macro 'FUNCTION' defined here
    #define FUNCTION(ID, NAME, CC, AVAILABILITY, RETURNS, ARGS, ATTRS, EFFECT) \
            ^
In file included from /home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:58:
/home/build-user/swift/include/swift/Runtime/RuntimeFunctions.def:89:10: error: too many arguments provided to function-like macro invocation
         UNKNOWN_MEMEFFECTS)
         ^
/home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:48:13: note: macro 'FUNCTION' defined here
    #define FUNCTION(ID, NAME, CC, AVAILABILITY, RETURNS, ARGS, ATTRS, EFFECT) \
            ^
In file included from /home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:58:
/home/build-user/swift/include/swift/Runtime/RuntimeFunctions.def:97:10: error: too many arguments provided to function-like macro invocation
         UNKNOWN_MEMEFFECTS)
         ^
/home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:48:13: note: macro 'FUNCTION' defined here
    #define FUNCTION(ID, NAME, CC, AVAILABILITY, RETURNS, ARGS, ATTRS, EFFECT) \
            ^
In file included from /home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:58:
/home/build-user/swift/include/swift/Runtime/RuntimeFunctions.def:106:10: error: too many arguments provided to function-like macro invocation
         UNKNOWN_MEMEFFECTS)
         ^
/home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:48:13: note: macro 'FUNCTION' defined here
    #define FUNCTION(ID, NAME, CC, AVAILABILITY, RETURNS, ARGS, ATTRS, EFFECT) \
            ^
In file included from /home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:58:
/home/build-user/swift/include/swift/Runtime/RuntimeFunctions.def:115:10: error: too many arguments provided to function-like macro invocation
         UNKNOWN_MEMEFFECTS)
         ^
/home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:48:13: note: macro 'FUNCTION' defined here
    #define FUNCTION(ID, NAME, CC, AVAILABILITY, RETURNS, ARGS, ATTRS, EFFECT) \
            ^
In file included from /home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:58:
/home/build-user/swift/include/swift/Runtime/RuntimeFunctions.def:123:10: error: too many arguments provided to function-like macro invocation
         UNKNOWN_MEMEFFECTS)
         ^
/home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:48:13: note: macro 'FUNCTION' defined here
    #define FUNCTION(ID, NAME, CC, AVAILABILITY, RETURNS, ARGS, ATTRS, EFFECT) \
            ^
In file included from /home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:58:
/home/build-user/swift/include/swift/Runtime/RuntimeFunctions.def:131:10: error: too many arguments provided to function-like macro invocation
         UNKNOWN_MEMEFFECTS)
         ^
/home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:48:13: note: macro 'FUNCTION' defined here
    #define FUNCTION(ID, NAME, CC, AVAILABILITY, RETURNS, ARGS, ATTRS, EFFECT) \
            ^
In file included from /home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:58:
/home/build-user/swift/include/swift/Runtime/RuntimeFunctions.def:140:10: error: too many arguments provided to function-like macro invocation
         UNKNOWN_MEMEFFECTS)
         ^
/home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:48:13: note: macro 'FUNCTION' defined here
    #define FUNCTION(ID, NAME, CC, AVAILABILITY, RETURNS, ARGS, ATTRS, EFFECT) \
            ^
In file included from /home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:58:
/home/build-user/swift/include/swift/Runtime/RuntimeFunctions.def:148:10: error: too many arguments provided to function-like macro invocation
         UNKNOWN_MEMEFFECTS)
         ^
/home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:48:13: note: macro 'FUNCTION' defined here
    #define FUNCTION(ID, NAME, CC, AVAILABILITY, RETURNS, ARGS, ATTRS, EFFECT) \
            ^
In file included from /home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:58:
/home/build-user/swift/include/swift/Runtime/RuntimeFunctions.def:157:10: error: too many arguments provided to function-like macro invocation
         UNKNOWN_MEMEFFECTS)
         ^
/home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:48:13: note: macro 'FUNCTION' defined here
    #define FUNCTION(ID, NAME, CC, AVAILABILITY, RETURNS, ARGS, ATTRS, EFFECT) \
            ^
In file included from /home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:58:
/home/build-user/swift/include/swift/Runtime/RuntimeFunctions.def:165:10: error: too many arguments provided to function-like macro invocation
         UNKNOWN_MEMEFFECTS)
         ^
/home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:48:13: note: macro 'FUNCTION' defined here
    #define FUNCTION(ID, NAME, CC, AVAILABILITY, RETURNS, ARGS, ATTRS, EFFECT) \
            ^
In file included from /home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:58:
/home/build-user/swift/include/swift/Runtime/RuntimeFunctions.def:173:10: error: too many arguments provided to function-like macro invocation
         UNKNOWN_MEMEFFECTS)
         ^
/home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:48:13: note: macro 'FUNCTION' defined here
    #define FUNCTION(ID, NAME, CC, AVAILABILITY, RETURNS, ARGS, ATTRS, EFFECT) \
            ^
In file included from /home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:58:
/home/build-user/swift/include/swift/Runtime/RuntimeFunctions.def:181:10: error: too many arguments provided to function-like macro invocation
         UNKNOWN_MEMEFFECTS)
         ^
/home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:48:13: note: macro 'FUNCTION' defined here
    #define FUNCTION(ID, NAME, CC, AVAILABILITY, RETURNS, ARGS, ATTRS, EFFECT) \
            ^
In file included from /home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:58:
/home/build-user/swift/include/swift/Runtime/RuntimeFunctions.def:189:10: error: too many arguments provided to function-like macro invocation
         UNKNOWN_MEMEFFECTS)
         ^
/home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:48:13: note: macro 'FUNCTION' defined here
    #define FUNCTION(ID, NAME, CC, AVAILABILITY, RETURNS, ARGS, ATTRS, EFFECT) \
            ^
In file included from /home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:58:
/home/build-user/swift/include/swift/Runtime/RuntimeFunctions.def:197:10: error: too many arguments provided to function-like macro invocation
         UNKNOWN_MEMEFFECTS)
         ^
/home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:48:13: note: macro 'FUNCTION' defined here
    #define FUNCTION(ID, NAME, CC, AVAILABILITY, RETURNS, ARGS, ATTRS, EFFECT) \
            ^
In file included from /home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:58:
/home/build-user/swift/include/swift/Runtime/RuntimeFunctions.def:205:10: error: too many arguments provided to function-like macro invocation
         UNKNOWN_MEMEFFECTS)
         ^
/home/build-user/swift/lib/SILOptimizer/UtilityPasses/Link.cpp:48:13: note: macro 'FUNCTION' defined here
    #define FUNCTION(ID, NAME, CC, AVAILABILITY, RETURNS, ARGS, ATTRS, EFFECT) \
            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
```

**Comment by etcwilde** [comment]
Updated to include memory effects in function macro definition in SILOptimizer/Link.cpp:

```
#define FUNCTION(ID, NAME, CC, AVAILABILITY, RETURNS, ARGS, ATTRS, EFFECT,     \
                  MEMORY_EFFECTS)                                              \
   linkEmbeddedRuntimeFunctionByName(#NAME);

...

 #define EFFECT(...)
 #define MEMORY_EFFECTS(...)
 #define UNKNOWN_MEMEFFECTS

 #include "swift/Runtime/RuntimeFunctions.def"
```

**Comment by etcwilde** [comment]
@swift-ci please smoke test

**Review by kubamracek — APPROVED** [review]

**Comment by kubamracek** [comment]
LGTM on the Link.cpp conflict.

**Comment by etcwilde** [comment]
Alright, Linux made it to the clang DebugInfo crash in index store db:
```
dbg.assign not in same function as inst
  call void @llvm.dbg.assign(metadata i1 undef, metadata !2664, metadata !DIExpression(), metadata !2690, metadata ptr %buf.i, metadata !DIExpression()), !dbg !15484
  %buf.i = alloca [400 x i8], align 16, !DIAssignID !2690
dbg.assign not in same function as inst
  call void @llvm.dbg.assign(metadata i1 undef, metadata !2664, metadata !DIExpression(), metadata !2690, metadata ptr %buf.i, metadata !DIExpression()), !dbg !15483
  %buf.i = alloca [400 x i8], align 16, !DIAssignID !2690
clang: /home/build-user/llvm-project/llvm/include/llvm/ADT/BitVector.h:358: llvm::BitVector &llvm::BitVector::set(unsigned int): Assertion `Idx < Size && "access in bound"' failed.
/home/build-user/build/buildbot_linux/unified-swiftpm-build-linux-x86_64/x86_64-unknown-linux-gnu/release/IndexStoreDB_Database.build/lmdb/mdb.c.o
```

**Pull request merged**
