### PR TITLE
[CS] Tighten up assertions for getCalleeDeclAndArgs

### PR DESCRIPTION
**Pull request by hamishknight**
Assert that we have a correct locator and that we recorded argument information for it, rather than silently returning no information.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by slavapestov** [comment]
Nice!

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Review by xedin — APPROVED** [review]

**Pull request merged**
