### PR TITLE
Lifetime dependence utilities

### PR DESCRIPTION
**Pull request by atrick**
Add LifetimeDependence utilities

- LifetimeDependence
- VariableIntroducerUseDefWalker
- LifetimeDependenceUseDefWalker
- LifetimeDependenceDefUseWalker

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci test source compatibility

**Comment by atrick** [comment]
@swift-ci benchmark

**Review by eeckstein — APPROVED** [review]
lgtm!

**Pull request merged**
