### PR TITLE
Sema: Ban forward references of captured values from 'defer' body

### PR DESCRIPTION
**Pull request by slavapestov**
While 'defer' is implemented as a local function, it doesn't
behave as one. In particular, since SILGen runs it after
destroying all local bindings that appear after the 'defer'
definition, the body of a 'defer' cannot forward reference
captured bindings the way that local functions can.

Fixes rdar://problem/75088379.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Review by jckarter — APPROVED** [review]
Thanks Slava!

**Comment by jckarter** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Comment by slavapestov** [comment]
The source combat failure is an unrelated build system issue in Kickstarter-ReactiveExtensions.

**Pull request merged**
