### PR TITLE
[cmake] Some more small changes to enable host side tools that use swift using standard cmake.

### PR DESCRIPTION
**Pull request by gottesmm**
There are 3 commits here. 2 are important one is just utility (I can split it out, but seemed useful):

1. The first commit conditionalizes -target being passed on the link line to link jobs with language C/CXX/OBJC/OBJCXX. We do not require this of Swift now since we need to do some extra work to upgrade the minimum deployment target of the compiler (NOTE: not the stdlib which will still backwards deploy to 10.9 in what I am suggesting). I put more info into the commit itself.
2. The 2nd commit exposes object libraries as a type of swiftest library. This is useful and is just putting in plumbing. I am find removing it though.
3. I am currently working with compnerd with upstream to conditionalize the cxx flags modified by llvm_update_compile_flags. That is going to take a few days to work out and I want to unblock ErikE's work on libswift so I put in temporarily a work around option while that discussion is happening upstream.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Review by compnerd — APPROVED** [review]

**Comment by gottesmm** [comment]
Small error. Needed to use LINKER_LANGUAGE not LINK_LANGUAGE. So this is going to fail.

**Comment by gottesmm** [comment]
I think we may need a newer cmake for me to use LINKER_LANGUAGE cmake generator. Until we get that I am trying to just check the property directly.

**Comment by gottesmm** [comment]
Nope, actually the problem is I need the newer cmake on the bots.

**Comment by gottesmm** [comment]
I am going to remove that commit from this PR so I can get in the other two parts.

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Pull request merged**
