### PR TITLE
Concurrency: attempt to handle Windows draining

### PR DESCRIPTION
**Pull request by compnerd**
Rather than just simply invoking abort on Windows, attempt to load
dispatch and execute the main loop by looking up `dispatch_main` in the
module.  Assuming that dispatch was used already, the `LoadLibraryW`
will provide the handle to the module currently mapped in.  This still
is not correct, since we do not link to libdispatch, so we cannot have
invoked any dispatch queuing methods.  However, this is better than the
previous behaviour of simply aborting.

This resolves the symptom in SR-14086, but not the underlying problem.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @etcwilde

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by etcwilde** [comment]
Does CoreFoundation compile/work for Windows? If yes, could we match the Mac/Linux behaviour and check for `CFRunLoopRun` first and use that if present before falling back on `dispatch_main`? If not, oh well, don't worry about it, LGTM. Thanks for fixing this.

**Comment by compnerd** [comment]
CoreFoundation does build/work on Windows.  However, we do not have a build of CoreFoundation handy.  That is actually a bug in the implementation for non-Darwin platforms (I have another patch for that I will be putting up).  The CoreFoundation implementation in Foundation is not meant to be used outside of Foundation (as per @millenomi).

**Pull request merged**
