### PR TITLE
Update API Digester test w/ temporary RangeSet removal

### PR DESCRIPTION
**Pull request by natecook1000**
Resolves failure in https://ci.swift.org/job/oss-swift-package-osx/

### CODE REVIEW

**Comment by natecook1000** [comment]
@swift-ci Please smoke test and merge

**Review by stephentyrone — APPROVED** [review]

**Comment by natecook1000** [comment]
@swift-ci Please smoke test and merge

**Comment by benrimmington** [comment]
@swift-ci Please smoke test

**Comment by benrimmington** [comment]
<https://ci.swift.org/job/swift-PR-osx-smoke-test/26467/>

```
Failed Tests (1):
  lldb-api :: lang/swift/protocol_extension_computed_property/TestProtocolExtensionComputerProperty.py

libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: recursive_mutex lock failed: Invalid argument
```

**Comment by benrimmington** [comment]
@swift-ci Please smoke test macOS platform

**Comment by benrimmington** [comment]
This will need to be cherry-picked for the `release/5.4` branch, but I'm not sure how to do that.

**Pull request merged**
