### PR TITLE
[ownership] Centralize all info about SILInstruction forwarding in the SILInstruction class hierarchy itself.

### PR DESCRIPTION
**Pull request by gottesmm**

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Review by atrick — APPROVED** [review]
lgtm except the names are attempting to describe all the invariants rather than just being unique and easily recognizable, like `OwnershipForwardingInst` and `AggregateOwnershipForwardingInst`

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Pull request merged**
