### PR TITLE
[stdlib] Introduce availability macros

### PR DESCRIPTION
**Pull request by lorentey**
Define the following availability macros throughout all Swift libraries and tests in this repository:

```
SwiftStdlib 5.0:macOS 10.14.4, iOS 12.2, watchOS 5.2, tvOS 12.2
SwiftStdlib 5.1:macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0
SwiftStdlib 5.2:macOS 10.15.4, iOS 13.4, watchOS 6.2, tvOS 13.4
SwiftStdlib 5.3:macOS 11.0, iOS 14.0, watchOS 7.0, tvOS 14.0
SwiftStdlib 5.4:macOS 11.3, iOS 14.5, watchOS 7.4, tvOS 14.5
SwiftStdlib 5.5:macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0
SwiftStdlib 5.6:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999
SwiftStdlib 9999:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999
```

These correspond to previous Swift Stdlib releases, in addition to the "5.6" release that we're currently working on, and the a placeholder "9999" release that we can use in place of an unknown future Swift release.

As part of this, we need to replace the pre-existing `SwiftStdlib 5.5` macro defined in the `_Concurrency` module with the correct `SwiftStdlib 5.1`, so that its expansion matches our release history. (The concurrency runtime now deploys back to macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0, which corresponds to the 5.1 release of the stdlib. Before this PR, this was reflected in the expansion of `SwiftStdlib 5.5`, but not its name.)

The new module `_Distributed` also defines `SwiftStdlib 5.5`, but its declarations need to have availability corresponding to the future Swift 5.6 release -- so this PR replaces it with `SwiftStdlib 5.6`.

To keep this PR (relatively) small, it does not include changes necessary to adopt these macros in existing stdlib code. (Beyond cleaning up the `_Concurrency` vs `_Distributed` situation.)

### CODE REVIEW

**Review by ktoso — APPROVED** [review]
LGTM, Distributed should likely be really defined for `9999` so maybe you can do this? Thanks !

**Review by xymus — APPROVED** [review]
This looks good! Thanks for refactoring the macros definition, it's much cleaner.

**Comment by lorentey** [comment]
```
23:22:57 Test Case '-[SKSwiftPMWorkspaceTests.SwiftPMWorkspaceTests testUnparsablePackage]' started.
23:22:57 [2021-10-28 23:22:45.005] [error]: manifest parse error(s):
23:22:57 
/private/var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/TemporaryDirectory.bdO2nV/pkg/Package.swift:3:5: error: type annotation missing in pattern
```

**Comment by lorentey** [comment]
The Windows build timed out.

**Comment by lorentey** [comment]
@swift-ci smoke test macOS platform

**Comment by lorentey** [comment]
```
lit.py: /Users/buildnode/jenkins/workspace/swift-PR-macos-smoke-test/branch-main/llvm-project/llvm/utils/lit/lit/TestingConfig.py:102: fatal: unable to parse config file '/Users/buildnode/jenkins/workspace/swift-PR-macos-smoke-test/branch-main/swift/test/lit.cfg', traceback: Traceback (most recent call last):
  File "/Users/buildnode/jenkins/workspace/swift-PR-macos-smoke-test/branch-main/llvm-project/llvm/utils/lit/lit/TestingConfig.py", line 91, in load_from_path
    exec(compile(data, path, 'exec'), cfg_globals, None)
  File "/Users/buildnode/jenkins/workspace/swift-PR-macos-smoke-test/branch-main/swift/test/lit.cfg", line 435, in <module>
    for macro in lit_config.params.get('availability_macros').split(";"):
AttributeError: 'NoneType' object has no attribute 'split'

/Users/buildnode/jenkins/workspace/swift-PR-macos-smoke-test/branch-main/swift-driver/Tests/SwiftDriverTests/IntegrationTests.swift:241: error: -[SwiftDriverTests.IntegrationTests testLitSymbolGraphFrontendTest] : XCTAssertEqual failed: ("terminated(code: 2)") is not equal to ("terminated(code: 0)")
Test Case '-[SwiftDriverTests.IntegrationTests testLitSymbolGraphFrontendTest]' failed (2.502 seconds).
```

D'oh

**Comment by lorentey** [comment]
@swift-ci test

**Pull request merged**
