### PR TITLE
IRGen: Fix Clang type conversion to map Swift.Bool to _Bool instead o…

### PR DESCRIPTION
**Pull request by slavapestov**
rdar://problem/26444628

Please don't merge -- still needs tests (and might be the wrong approach)

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
You can put me down as the reviewer if the preview branch is having the same issue.

**Comment by jrose-apple** [comment]
I assume `useSignedCharForObjCBool` is true because all the existing Objective-C runtimes on Linux use signed char…and if we were trying to interoperate with them, we'd need it. On the other hand, I wouldn't expect anything on the C side to be treating Bool as ObjCBool, and that could indicate a bridging or importer problem.

**Comment by jrose-apple** [comment]
But we can worry about that later.

**Comment by slavapestov** [comment]
Does the fix look OK in general, @jrose-apple?

**Comment by slavapestov** [comment]
Oops, I forgot to reload so I didn't see your replies earlier. Please disregard.

**Comment by slavapestov** [comment]
Hi @tkremenek, do we want this to go into swift-3.0-preview-1-branch also?

**Pull request closed without merging**
