### PR TITLE
🍒 @preconcurrency import downgrades globals concurrency errors to warnings

### PR DESCRIPTION
**Pull request by sophiapoirier**
Explanation: completes SE-0412 implementation `@preconcurrency import` specification
Scope: the changes are guarded behind an upcoming feature flag
Issue: none
Risk: low risk given that functionality is guarded behind an upcoming feature flag
Testing: `lit.py` tests included
Reviewer: @hborla

includes PRs:
https://github.com/apple/swift/pull/70421
https://github.com/apple/swift/pull/70725

### CODE REVIEW

**Comment by sophiapoirier** [comment]
@swift-ci please test

**Comment by hborla** [comment]
Thanks! We should enable `GlobalConcurrency` when `-strict-concurrency=complete` is set as well (not the `CompleteConcurrency` upcoming feature flag that exists on `main`; I already regret adding yet another way to enable complete concurrency checking).

Can you please also link the main branch PR(s) in the description?

**Comment by sophiapoirier** [comment]
@swift-ci please test

**Comment by sophiapoirier** [comment]
@swift-ci please test

**Review by airspeedswift — APPROVED** [review]

**Pull request merged**
