### PR TITLE
Allow CoreFoundation to declare CGFloat

### PR DESCRIPTION
**Pull request by salinas-miguel**
Resolves rdar://83517290

### CODE REVIEW

**Review by xedin — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

**Comment by salinas-miguel** [comment]
Not sure what the Linux failure is but I was significantly behind main so I rebased. Hopefully that fixes the failure.

**Comment by xedin** [comment]
@swift-ci please test

**Comment by salinas-miguel** [comment]
`/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/swift/test/Concurrency/Runtime/async_taskgroup_cancel_then_completions.swift:11:8: error: compiled module was created by an older version of the compiler; rebuild 'Dispatch' and try again: /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/libdispatch-linux-x86_64/src/swift/swift/Dispatch.swiftmodule`

I don't think this error from the Linux pipeline is related. Is it possible the CI bot has a stale version of libDispatch?

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Pull request merged**
