### PR TITLE
[4.0] TBD including all files from a full build.

### PR DESCRIPTION
**Pull request by huonw**
https://github.com/apple/swift/pull/10861 , https://github.com/apple/swift/pull/10724 , and https://github.com/apple/swift/pull/11142 .

**Explanation**: TBDGen now includes all the exported symbols encountered while building the standard library and test suite.
**Scope**: Future users of TBD files, as there's no functionality change outside of it.
Radar: rdar://problem/32252869 and its subtasks.
**Risk**: Low: the only changes outside of TBDGen are tightening the linkage of some symbols, which people shouldn't be relying on.
**Testing**: CI and local testing with TBD validation turned on by default (which this PR doesn't include, as that could break user's build).

### CODE REVIEW

**Comment by huonw** [comment]
@swift-ci Please test.

**Comment by huonw** [comment]
@swift-ci Please test.

@slavapestov could you review this for 4.0? (It includes the proper materializeForSet closure change.)

**Comment by huonw** [comment]
@swift-ci Please test.

**Comment by slavapestov** [comment]
LGTM

**Pull request merged**
