### PR TITLE
[Do Not Merge] [Experiment] [LegacyASTTransformer] Transform FuncDecl to FunctionDeclSyntax

### PR DESCRIPTION
**Pull request by harlanhaskins**
This is an implementation of the changes to the AST necessary to transform a `FuncDecl *` into a `FuncDeclSyntax` using the `LegacyASTTransformer`.

I personally think this is very bug-prone, and this implementation is not complete (it's missing anything to do with generics or where clauses).

### CODE REVIEW

**Comment by harlanhaskins** [comment]
This patch also has a) some conflicts, and b) some architectural improvements to the LegacyASTTransformer.

**Comment by harlanhaskins** [comment]
But what I want to highlight is the need to add tons of extra `SourceLoc`s to the AST nodes, and plumb those through all the places that synthesize the AST. It just feels brittle and bad.

@nkcsgexi

**Comment by nkcsgexi** [comment]
Thank you for opening this, Harlan! It sets an example of how we can transform to using libSyntax.

**Comment by harlanhaskins** [comment]
I'm gonna close this as we do not intend to merge it.

**Pull request closed without merging**
