### PR TITLE
[Python] Argument names should be lowercase by convention

### PR DESCRIPTION
**Pull request by practicalswift**
Fix 16 "argument name should be lowercase" violations.

As discussed with @modocache and @nadavrot in #1369.

Signature changes: 

```
-def addFunction(sizes, function, startAddr, endAddr, groupByPrefix):
+def addFunction(sizes, function, start_addr, end_addr, group_by_prefix):
-def readSizes(sizes, fileName, functionDetails, groupByPrefix):
+def readSizes(sizes, file_name, function_details, group_by_prefix):
-def compareSizes(oldSizes, newSizes, nameKey, title):
+def compareSizes(old_sizes, new_sizes, name_key, title):
-def compareSizesOfFile(oldFiles, newFiles, allSections, listCategories):
+def compareSizesOfFile(old_files, new_files, all_sections, list_categories):
-def listFunctionSizes(sizeArray):
+def listFunctionSizes(size_array):
-def compareFunctionSizes(oldFiles, newFiles):
+def compareFunctionSizes(old_files, new_files):
-def tokenPosToIndex(tokenPos, start, lineStarts):
+def tokenPosToIndex(token_pos, start, line_starts):
-def tokenizePythonToUnmatchedCloseCurly(sourceText, start, lineStarts):
+def tokenizePythonToUnmatchedCloseCurly(source_text, start, line_starts):
-def tokenizeTemplate(templateText):
+def tokenizeTemplate(template_text):
-def splitGybLines(sourceLines):
+def splitGybLines(source_lines):
-def codeStartsWithDedentKeyword(sourceLines):
+def codeStartsWithDedentKeyword(source_lines):
-    def tokenGenerator(self, baseTokens):
+    def tokenGenerator(self, base_tokens):
-    def __init__(self, lineDirective='// ###line', **localBindings):
+    def __init__(self, line_directive='// ###line', **local_bindings):
-def executeTemplate(ast, lineDirective='', **localBindings):
+def executeTemplate(ast, line_directive='', **local_bindings):
-def bodyLines(bodyText):
+def bodyLines(body_text):
-  def __init__(self, name, source, processedSource, binary):
+  def __init__(self, name, source, processed_source, binary):
```

### CODE REVIEW

**Comment by dabrahams** [comment]
I don’t mind the change, but whose convention is this that we’re conforming to?
(a link in the PR description wouldn’t hurt).

**Comment by practicalswift** [comment]
@dabrahams Sorry about not making that clear :-)

The Python code in the repo is in line with PEP-8 (https://www.python.org/dev/peps/pep-0008/) with the exception of a few ignored rules listed here: https://github.com/apple/swift/blob/master/.pep8

However, this PR is more about bringing consistency to the code base (with the additional bonus of being in line with PEP-8 :-)). The `argument_name` form is the dominant form in the repo with `argumentName` being the exception.

**Comment by dabrahams** [comment]
Does it really make sense to use a different case convention for every language in the repo?  Seems like we'd be better off following Swift convention in the absence of compelling reasons to do otherwise.

**Comment by practicalswift** [comment]
The repo contains C++, Swift, Python, shell scripts and CMake scripts.

The argument case conventions currently in use in the repo for these languages are:
* C++ code: `ArgumentName`
* Swift code: `argumentName`
* Python scripts: `argument_name`
* Shell scripts: `argument_name`
* CMake scripts: `argument_name`

I'm a big fan of consistency but I'm afraid that using the Swift case convention (`argumentName`) in all those languages would make the code look non-idiomatic for four out of the five languages. Perhaps especially for the scripting languages.

I think the current state of affairs with consistency on a per language basis is a good trade-off: it gives us local consistency (local as in per language) *and* idiomatic code. On a practical level it has the added benefit of being easily achievable since we simply follow the style already being used in the repo for each language.

Long live the status quo! :-)

**Comment by modocache** [comment]
Whether one considers standards adopted by the Python Software Foundation "compelling" is subjective, but using snake case for method and variable names in Python *is* recommended by a PSF standard: https://www.python.org/dev/peps/pep-0008/#method-names-and-instance-variables.

I would also be skeptical of pursuing a convention we couldn't reasonably enforce, but I consider @practicalswift's efforts to add and enforce lint rules in the Swift project to have been very effective so far. They've made it easier for me to work on the Python in this repository, since it has become much more consistent over the past few months.

I believe we'll be able to automate these naming convention rules soon as well, using the existing linting mechanisms.

**Comment by dabrahams** [comment]
> On Feb 21, 2016, at 11:15 AM, Brian Gesiak <notifications@github.com> wrote:
> 
> Whether one considers standards adopted by the Python Software Foundation "compelling" is subjective, but using snake case for method and variable names in Python is recommended by a PSF standard: https://www.python.org/dev/peps/pep-0008/#method-names-and-instance-variables.

That's good enough for me!

**Pull request merged**
