### PR TITLE
Class resilience part 9

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by rjmccall** [comment]
This looks good.  An alternative approach would be to always store offsets relative to the start of the class's metadata section, but I guess that would require us to dirty more memory during initialization.

**Pull request merged**
