### PR TITLE
[AutoDiff] Update generic constraints in `Differentiable` protocol.

### PR DESCRIPTION
**Pull request by rxwei**
`CotangentVector.CotangentVector == CotangentVector` is incorrect. It should be equal to `TangentVector`. So when we take the adjoint of a pullback `(U.CotangentVector) -> T.CotangentVector`, we get a differential of type `(T.CotangentVector.CotangentVector) -> U.CotangentVector.CotangentVector` (aka `T.TangentVector -> U.TangentVector`).

Concrete example:
```swift
func foo<T : Differentiable, U : Differentiable>(_ x: T) -> U { ... }
let pb = pullback(of: foo) // (U.CotangentVector) -> (T.CotangentVector)
let differential = pullback(at: .zero, in: pb) // (T.TangentVector) -> (U.TangentVector)
```

This patch does not enable higher-order differentiation nor is in the process of making that happen. It is to fix the semantics.

`TangentVector.Scalar` and `CotangentVector.Scalar` cannot be constrained because [SR-9595](https://bugs.swift.org/browse/SR-9595) got in the way. @DougGregor @rudkx, is there any workaround?

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow macOS

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux CPU

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux CPU

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux CPU

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux CPU

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux CPU

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux CPU

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux CPU

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux CPU

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux CPU

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux CPU

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux CPU

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux CPU

**Comment by rxwei** [comment]
@swift-ci please test tensorflow macOS

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux CPU

**Review by dan-zheng — APPROVED** [review]
The fixed semantics (`TangentVector.CotangentVector == CotangentVector`) make sense!

SR-9595 is unfortunate but I can make the "can derive conformances for `Differentiable`" condition check for `TangentVector.Scalar : FloatingPoint`.

**Comment by DougGregor** [comment]
I don't have a good workaround for SR-9595. It's a bug in the GenericSignatureBuilder's minimization algorithm.

**Pull request merged**
