### PR TITLE
[build-script-impl] Do not actually try to extract symbols when we perform a dry-run.

### PR DESCRIPTION
**Pull request by gottesmm**
Otherwise, we can't successfully dry-run a toolchain on darwin.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by shahmishal** [comment]
@swift-ci smoke test macOS

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
I added an option to restore the old testing behavior. But by default, we are now going to be able to run dry-run with toolchain.

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Pull request merged**
