### PR TITLE
[stdlib] Workaround C++ lifetime rules

### PR DESCRIPTION
**Pull request by davezarzycki**
http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_closed.html#900

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Review by mikeash — APPROVED** [review]
LGTM. Thanks again.

**Comment by davezarzycki** [comment]
(Thinking out loud.) I wonder if we ought to just have a `forEach` method on the concurrent collection that internally snapshots rather than expose the snapshot method? Otherwise all of the callers need to know about the C++ lifetime wart. What do you think?

**Comment by mikeash** [comment]
There’s a way to make the methods on the snapshot not callable on a temporary. I’m going to try that out tomorrow. If that ends up being unworkable, some sort of callback-based API would be a good plan B.

**Comment by davezarzycki** [comment]
@mikeash – We can close this now because of #35345 right?

**Comment by mikeash** [comment]
Yeah, this isn't actually needed after all.

**Pull request closed without merging**
