### PR TITLE
[region-isolation] Cherry-pick to swift 6

### PR DESCRIPTION
**Pull request by gottesmm**
Explanation: A bunch of work in region isolation that occurred after the branch point.
Issue: This is fixing a bunch of different issues. Radars:
rdar://123474616
rdar://123474616
rdar://125372790
rdar://125372336
rdar://125211624
rdar://124960994
Original PRs:
#72583
#72572
#72546
#72511
#72544
#72510
#72476
#72481
#72435
#72403
#72385
#72378
Risk: Low. Only affects region isolation.
Testing: Added many functional and unit tests.
Reviewer: N/A

### CODE REVIEW

**Comment by gottesmm** [comment]
Just running tests

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
Rebased with some more stuff. Linux failure was unrelated.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
The stat (ignoring test updates):

```
 include/swift/AST/ActorIsolation.h                                           |  25 +-
 include/swift/AST/DiagnosticsSIL.def                                         |  16 +-
 include/swift/Basic/ImmutablePointerSet.h                                    |  49 ++
 include/swift/SIL/SILFunction.h                                              |  11 +
 include/swift/SILOptimizer/Analysis/RegionAnalysis.h                         | 182 +------
 include/swift/SILOptimizer/Utils/PartitionUtils.h                            | 927 +++++++++++++-----------------------
 lib/AST/Decl.cpp                                                             |  25 +
 lib/AST/TypeCheckRequests.cpp                                                |   5 +
 lib/ClangImporter/ClangImporter.cpp                                          |   7 +-
 lib/ClangImporter/ImportDecl.cpp                                             |  12 +
 lib/ClangImporter/ImportType.cpp                                             |  12 +
 lib/SILGen/SILGen.cpp                                                        |   4 +
 lib/SILOptimizer/Analysis/RegionAnalysis.cpp                                 | 136 ++----
 lib/SILOptimizer/Mandatory/TransferNonSendable.cpp                           | 405 ++++++++++------
 lib/SILOptimizer/Utils/PartitionUtils.cpp                                    | 704 +++++++++++++++++++++++++++
 lib/SILOptimizer/Utils/VariableNameUtils.cpp                                 |  75 ++-
```

**Review by hborla — APPROVED** [review]

**Pull request merged**
