### PR TITLE
[stdlib] Fix array slice self-assignment bug

### PR DESCRIPTION
**Pull request by airspeedswift**
Fixes [SR-4503](https://bugs.swift.org/browse/SR-4503).

In-place mutation of an array slice doesn't need assigning back, but there needs to be a check that the assigned slice's bounds matches otherwise unmatched range assignments like `a[1..<1] = a[1..<2]` were getting thrown away.

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please test

**Review by jrose-apple — COMMENTED** [review]
Thanks! This looks correct to me.

**Review by dabrahams — CHANGES_REQUESTED** [review]
Please fix 80-column overflow; otherwise LGTM!

**Comment by airspeedswift** [comment]
@swift-ci please test and merge

**Pull request merged**
