### PR TITLE
Fixups for UnsafePointer documentation

### PR DESCRIPTION
**Pull request by Gankra**
Two minor fixups, and one big/scary documentation change.

Until now we've failed to document the Undefined Behaviour requirements on pointer offsets. In particular we lower these operations to LLVM's `GetElementPointer inbounds`: http://llvm.org/docs/LangRef.html#id214

> If the inbounds keyword is present, the result value of the getelementptr is a poison value if the base pointer is not an in bounds address of an allocated object

In order to avoid getting into the nitty gritty details of poison, I just specified staying in bounds of the current allocation is a precondition. I am very far from certain that this is the ideal wording, and we should discuss the best wording (and how much Swift wants to inherit from llvm here).

### CODE REVIEW

**Comment by Gankro** [comment]
CC @atrick @natecook1000 @bjlanier

**Comment by jrose-apple** [comment]
Don't forget "just-past-the-end" pointers, which (like in C) are also valid.

**Comment by Gankro** [comment]
@jrose-apple I didn't forget them, I was just hoping everyone in the world would assume this is included in the definition of in-bounds. I have a feeling the "correct" solution involves all of these preconditions linking to a definition, but I'm not sure where that would go.

**Comment by Gankro** [comment]
@swift-ci please smoke test

**Comment by atrick** [comment]
Looks fine to me.

**Comment by natecook1000** [comment]
TIL about poison values. LGTM! Going to merge so I can integrate these changes into some other revisions.

**Pull request merged**
