### PR TITLE
build: remove `TARGET_SDKS` from the runtime

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

The runtime and stubs are built for ALL targets, not specific ones.  This allows
us to configure when cross-compiling to Windows again.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Review by jrose-apple — CHANGES_REQUESTED** [review]
This is wrong. There's another target just above for ALL_APPLE_PLATFORMS. We just don't have an ALL_NON_APPLE_PLATFORMS.

**Comment by compnerd** [comment]
Didn't notice that originally.  It is silly to have the dual `add_library` for this.  Ive collapsed the two into a single build.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by jrose-apple** [comment]
CC @modocache, @erg, @jckarter 

I don't know if this is really "simpler". Different platforms really do need different options sometimes.

**Comment by modocache** [comment]
I agree that I imagine some targets will need different options in some cases, but this seems like a simplification for at least the runtime. I like it!

I just pulled it down to try building for Android; I'll let you know how that goes.

**Comment by compnerd** [comment]
@jrose-apple can we get some closure on this?

**Comment by compnerd** [comment]
@swift-ci please test

**Review by jrose-apple — DISMISSED** [review]

**Comment by jrose-apple** [comment]
@jckarter touches the runtime files the most, so I guess he should answer. I still feel a little weird having .mm files even opened on Linux, though.

**Comment by jckarter** [comment]
I'm a bit concerned too. I'm surprised `clang` even knows what to do with a `.mm` file on Linux.

**Comment by jckarter** [comment]
I do think that having the conditionalization in the source files is a bit nicer than having it in CMake, since our CMake code is already pretty complicated and CMake strikes me as a worse language than C preprocessor for this kind of this.

**Comment by compnerd** [comment]
@swift-ci please smoke test os x

**Comment by compnerd** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
