### PR TITLE
Remove the -resilience-bypass flag and functionality.

### PR DESCRIPTION
**Pull request by adrian-prantl**
LLDB no longer depends on it.

rdar://problem/48018240

### CODE REVIEW

**Comment by adrian-prantl** [comment]
This was factored out from https://github.com/apple/swift/pull/23425 and depends on https://github.com/apple/swift-lldb/pull/1393

**Review by slavapestov — APPROVED** [review]
Approved once the first PR is finished. Thanks!

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Pull request merged**
