### PR TITLE
[stdlib] Add contiguous storage forwarding to AnySequence, etc

### PR DESCRIPTION
**Pull request by karwa**
Means this now works:
```
(swift) [2,3].withContiguousStorageIfAvailable { print($0) }
UnsafeBufferPointer(start: 0x00007fa99cc6de20, count: 2)
// r0 : ()? = Optional(())
(swift) AnySequence([2,3]).withContiguousStorageIfAvailable { print($0) }
UnsafeBufferPointer(start: 0x00007fa99cc7e060, count: 2)
// r1 : ()? = Optional(())
```

### CODE REVIEW

**Comment by karwa** [comment]
Some more low-hanging fruit. Might as well add to this one rather than making a new PR. Documentation edits are in the style of `forEach` - "Calls the given closure ...".

I don't expect benchmark improvements because we don't actually use this function in the standard library (yet). We should do, and it should improve Slice -> Array performance (Slice doesn't implement `_copyContents/_copyToContiguousArray` AFAICT).

**Comment by karwa** [comment]
@airspeedswift is this okay to merge?

**Comment by karwa** [comment]
Ping @airspeedswift

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
These additions will need availability markup. See [this post](https://forums.swift.org/t/availability-and-the-standard-library/20932) for details on how.

**Comment by airspeedswift** [comment]
Could you add tests exercising the new functionality?

**Comment by CodaFi** [comment]
@karwa Just pinging the old issues.  Could you give us a rebase here and address the review feedback?

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
