### PR TITLE
[5.0] Build and install 'clang' and 'clangd' in the macOS & linux toolchains

### PR DESCRIPTION
**Pull request by hyp**
- Build script now builds clang_tools_extra as part of LLVM's build.
- Build script now has a new libc++ build step to allow libc++ headers to be installed in the
  resulting toolchain.
- 'clang', 'clangd', 'clang-headers' & 'compiler-rt' targets are now installed for
  the package build configurations for macOS and linux.
- 'clang-resource-dir-symlink' is used in the package build configuration for macOS and linux
  to avoid duplication of Clang's headers and compiler-rt archives.

rdar://24912710
(cherry picked from commit 1941aaa0d6a73a57d7b62edad5f833f1942e962f)

### CODE REVIEW

**Comment by hyp** [comment]
@swift-ci build toolchain

**Review by shahmishal — APPROVED** [review]
LGTM! We will need to also update the toolchain bots before merging this PR, I will merge it once bots have been updated.

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci build toolchain

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by benlangmuir** [comment]
There's an issue with the libc++ header installation: https://bugs.swift.org/browse/SR-9861

**Comment by benlangmuir** [comment]
Nevermind, that bug should not affect the swift-5 branch.

**Comment by hyp** [comment]
@swift-ci test

**Comment by hyp** [comment]
@swift-ci test

**Comment by benlangmuir** [comment]
@hyp while the Product issue doesn't specifically affect swift-5.0-branch, I think for consistency we should include the changes from https://github.com/apple/swift/pull/22404/ since they affect the way that build-script-impl is invoked.  That PR also depends on https://github.com/apple/swift/pull/22346.

**Comment by hyp** [comment]
@swift-ci test

**Comment by tkremenek** [comment]
@swift-ci clean test

**Comment by ianpartridge** [comment]
Any news on when this might land?  It will make a big improvement to the Swift 5 Docker images: https://forums.swift.org/t/which-clang-package-should-we-install/20542/12

**Comment by tkremenek** [comment]
@swift-ci clean test macos

**Comment by hyp** [comment]
@swift-ci clean test macos

**Comment by jrose-apple** [comment]
Heads-up that we'll need #22911 too.

**Comment by shahmishal** [comment]
@swift-ci test macOS

**Comment by shahmishal** [comment]
Error:

23:08:14 ** All tests passed **
23:08:14 --install-destdir is required to install products.

**Comment by ianpartridge** [comment]
I've opened https://github.com/apple/swift/pull/23027 to unblock this, as suggested by @jrose-apple.

**Comment by weissi** [comment]
@swift-ci please test

**Comment by akyrtzi** [comment]
Discussed with @shahmishal about the OSX bot failure, we think the additional PRs @benlangmuir suggested may help to resolve the failure, @hyp will cherry-pick them to this PR.

**Comment by akyrtzi** [comment]
Update: discussed with @benlangmuir and he says that clangd is problematic and is hitting an assertion hit. Given that clangd is not usable there's no reason to put all of clang+clangd in the swift-5.0 macOS toolchain, so @hyp is going to look into updating the PR to only put clang in the linux toolchain.

**Comment by ianpartridge** [comment]
That sounds great - thanks @akyrtzi @benlangmuir @hyp!

**Comment by hyp** [comment]
Updated the PR to only install clang on Linux

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@shahmishal Why do the builds fail immediately?

**Comment by hyp** [comment]
@swift-ci build toolchain

**Comment by shahmishal** [comment]
@hyp, it's due to force push 
```
Automatically restarting the build, due to invalid sha
```

**Comment by hyp** [comment]
@shahmishal is macOS failure the same one we had the last time? I took out the Mac builds, but maybe the problem is in the build script?

**Comment by shahmishal** [comment]
We need to cherry-pick these two PRs into https://github.com/apple/swift/pull/22273. Otherwise, we are going to try to install libcxx headers during PR testing. 

https://github.com/apple/swift/pull/22404/
https://github.com/apple/swift/pull/22346/

These two PRs enable support to only install libcxx headers in package preset, the current solution in PR#22273 will try to install the headers if libcxx directory exists.

https://github.com/apple/swift/pull/22273/files#diff-65b44eb6cb88af2161d8e1176231aad0R1217

```
# Build libcxx, unless it doesn't exist.
	LIBCXX_SOURCE_DIR="${WORKSPACE}/libcxx"
	if [[ ! -e "${LIBCXX_SOURCE_DIR}" ]] ; then
	  SKIP_BUILD_LIBCXX=1
	fi 
```

This is the reason we are seeing PR failing due to "--install-destdir is required to install products."

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
Cherry-picked the changes

**Comment by hyp** [comment]
error: unknown setting: libcxx-cmake-options, fixed.

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci build toolchain

**Comment by hyp** [comment]
@shahmishal tests passed, please merge

**Comment by ianpartridge** [comment]
Awesome, thanks @hyp and @shahmishal!

**Pull request merged**
