### PR TITLE
Disable test/ClangImporter/blocks_parse until it can be fixed

### PR DESCRIPTION
**Pull request by benlangmuir**
This test is failing non-deterministically.

### CODE REVIEW

**Comment by benlangmuir** [comment]
@swift-ci please smoke test and merge

**Comment by jrose-apple** [comment]
It's only been failing on watchOS, right? Can you disable it there (using UNSUPPORTED) instead of turning off the test completely?

**Comment by benlangmuir** [comment]
I've also seen it fail on iOS so I assumed all platforms are affected.  If you're confident it will pass I could try
```
REQUIRES: OS=macosx
```

**Comment by shahmishal** [comment]
We have seen it on iPhone too.

**Comment by jrose-apple** [comment]
Ah, okay, never mind.

**Pull request merged**
