### PR TITLE
SR-331: Diagnostic notes and fixits for unicode confusables

### PR DESCRIPTION
**Pull request by robinkunde**
Addresses [SR-331](https://bugs.swift.org/browse/SR-331) by adding diagnostic notes and fixits for confusable unicode characters. The confusables check only runs after the lexer encounters an invalid character or an identifier fails to resolve.

With @amackworth permission, I took over the code he wrote for https://github.com/apple/swift/pull/732. From the discussion there, it seems like the PR stalled due to disagreements over whether to use gyb for compile time code gen. I reworked the code to address most of the feedback and removed gyb usage. The flow is now as follows:

1. The latest confusables.txt file has been added at utils/UnicodeData/confusables.txt
2. A python script has been added at utils/generate_confusables.py that takes the confusables file and generates include/swift/Parse/Confusables.def
3. lib/Parse/Confusables.cpp then generates all the cases for its switch statement using the preprocessor

This way, the script only has to be rerun if we broaden the list of covered confusables or Unicode releases a new version (happens about once a year).

### CODE REVIEW

**Comment by CodaFi** [comment]
Fantastic!

@swift-ci please smoke test

**Comment by CodaFi** [comment]
Since the approach is roughly the same (and the PR comments from last time have been addressed), over to @lattner for if this is what he had in mind back then.

**Comment by CodaFi** [comment]
@robinkunde Please lint the Python script and fix the errors.

**Comment by robinkunde** [comment]
@CodaFi I can't seem to find a clean way to fix the error where it complains about the docstring line length. The leading and closing line for def file header are supposed to be 80 columns wide. The python linter insists lines be at most 79 wide.

For now I've broken it up into multiple write statements, but it looks ugly. If someone knows a better way, please chime in.

**Comment by CodaFi** [comment]
Sometimes the linter isn't always right - can we add specific exceptions for this @hughbe?

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
Just to check:

@swift-ci please test source compatibility

**Comment by CodaFi** [comment]
There's no reason to delay the inclusion of this feature any further.  Thank you @robinkunde for carrying this over the goal line, and @amackworth for the original patch.  Don't forget to resolve the SR.  I'm going to close the original pull request as wel.

⛵️

**Pull request merged**
