### PR TITLE
COFF: restructure metadata registration

### PR DESCRIPTION
**Pull request by compnerd**
Restructure the COFF metadata handling to use the linker section
grouping to emit section start/stop markers in the appropriate location.
This allows us to lookup the sections statically without having to the
walk the entire image structure.

Introduce a constructor for PE/COFF binaries.  This will ensure that the
registration occurs for all modules appropriately.  This should resolve
rdar://problem/19045112.  The registration should occur prior to
`DllMain` being invoked from `DllMainCRTStartup`.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by troughton** [comment]
When trying to build for Windows with this merged in I run into issues. When linking `swiftRemoteMirror.dll`, `swiftrt.o` is passed to the linker invocation, but since the runtime isn't being linked in I'm getting `__imp_swift_addNewDSOImage` as undefined. Are you seeing anything similar locally?

This is from a clean build. I've removed the warning flags and abbreviated some paths to make it easier to read.

```
[3/14] Linking CXX shared library lib/swift/windows/x86_64/swiftRemoteMirror.dll
FAILED: : && /mnt/c/swift-source/build/Ninja-ReleaseAssert/llvm-linux-x86_64/./bin/clang++  -fPIC -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -fno-sanitize=all -DLLVM_DISABLE_ABI_BREAKING_CHECKS_ENFORCING=1 -O3  -target x86_64-unknown-windows-msvc -nostdlib -fuse-ld=lld  "-Llib/swift/windows/x86_64" "-L lib/swift/windows/x86_64" "-L lib/swift/windows" "-L VCToolsInstallDir/Lib/x64" "-L/ucrt/x64" "-L um/x64" -shared  -o lib/swift/windows/x86_64/swiftRemoteMirror.dll lib/swift/windows/x86_64/swiftrt.o stdlib/public/SwiftRemoteMirror/CMakeFiles/swiftRemoteMirror-windows-x86_64.dir/SwiftRemoteMirror.cpp.o -L/mnt/c/swift-source/build/Ninja-ReleaseAssert/llvm-linux-x86_64/./lib lib/swift/windows/x86_64/swiftReflection.lib && :
/usr/bin/lld-link: error: lib/swift/windows/x86_64/swiftrt.o: undefined symbol: __imp_swift_addNewDSOImage
```

**Comment by compnerd** [comment]
Yeah, that is one issue that I need to fix still.  Its interesting that this somehow works on ELF.  I wonder if we should be preventing that injection here.

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Pull request merged**
