### PR TITLE
[4.1] [build-script] Fix how the playground frameworks build in build-script.

### PR DESCRIPTION
**Pull request by cwakamo**
This PR does three things by pulling in the changes from #14123:

- Removes support for building PlaygroundLogger on Linux (this never actually worked, so it doesn't make sense to keep maintaining something which doesn't work).
- Merges the "playgroundsupport" and "playgroundlogger" products in build-script and updates presets where necessary
- Updates how PlaygroundLogger and PlaygroundSupport are built, taking advantage of a new workspace and new schemes to do per-platform xcodebuild invocations (requires apple/swift-xcode-playground-support#22).

This is part of &lt;rdar://problem/37861670&gt;.

### CODE REVIEW

**Comment by cwakamo** [comment]
Please test with the following PRs:

apple/swift-xcode-playground-support#22

@swift-ci Please test

**Comment by cwakamo** [comment]
@Rostepher @shahmishal If one of y'all could review this for Swift 4.1 nomination that would be great -- I need to nominate this build-script change for 4.1 as I need to bring swift-xcode-playground-support's swift-4.1-branch up to date with master to accommodate changes to support SE-0198 in PlaygroundLogger.

**Comment by shahmishal** [comment]
LGTM! 

FYI - swift-4.1-branch is under CCC.

**Comment by cwakamo** [comment]
• Explanation: In preparation for landing the new PlaygroundLogger implementation on swift-4.1-branch, we need to bring swift-xcode-playground-support's swift-4.1-branch up-to-date with the basis of that implemenation (i.e. the modernized project structure, primarily). This change brings swift-xcode-playground-support/swift-4.1-branch up-to-date with the latest commit that's not solely aligned with master. This also pulls in changes to build-script and build-script-impl on swift/swift-4.1-branch to support building the latest and greatest swift-xcode-playground-support content.
• Scope of Issue: Affects swift-xcode-playground-support and building swift-xcode-playground-support with build-script. 
• Origination: Preparation for updating PlaygroundLogger for SE-0198 by way of a better reimplementation of PlaygroundLogger.
• Risk: Low
• Reviewed By: @shahmishal
• Testing: Tested locally; also tested that everything works in CI via PR testing
• Directions for QA: Ensure that the swift-4.1-branch bots continue to build after taking this change.

**Review by shahmishal — APPROVED** [review]

**Pull request merged**
