### PR TITLE
[stdlib] Avoid storing NULL into a Builtin.RawPointer.

### PR DESCRIPTION
**Pull request by jrose-apple**
<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by jrose-apple** [comment]
@gribozavr, mind sanity-checking this?

@swift-ci Please test

**Comment by gribozavr** [comment]
@jrose-apple LGTM, thank you!

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by gparker42** [comment]
Reverted in a14a836. It broke a compiler assertion in test sil-opt/emit-sib.swift.
https://ci.swift.org/job/oss-swift_tools-RA_stdlib-DA_test-simulator/1022/

**Comment by jrose-apple** [comment]
How exciting. Thanks, Greg.

**Comment by jrose-apple** [comment]
Reapplied in acbcf04, with a fix for the failure in the parent commit. Hoping it sticks.

**Pull request merged**
