### PR TITLE
Move modulemap to header search directory. NFC intended.

### PR DESCRIPTION
**Pull request by vsapsai**
In code we use `#include "swift/Lib/Header.h"` which is located in "include/swift/Lib/Header.h", so we use "include/" as a header search path. We should put modulemaps in the same directory and shouldn't rely on clang to search in immediate subdirectories.

rdar://106677321

### CODE REVIEW

**Comment by vsapsai** [comment]
Relevant LLVM+Clang change is https://reviews.llvm.org/D148776

**Review by eeckstein — APPROVED** [review]
lgtm

**Review by egorzhdan — APPROVED** [review]

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Review by ributzka — APPROVED** [review]
LGTM

**Comment by vsapsai** [comment]
Thanks for the reviews!

**Pull request merged**
