### PR TITLE
[Diags-Experimental-Formatting] Fixes for #sourceLocation

### PR DESCRIPTION
**Pull request by owenv**
- Always use the line number in the actual source file when extracting excerpts and adding highlights/fix-its (SourceManager::getLineNumber and SourceManager::getLineAndCol return the real and virtual line numbers respectively)
- Always use the display name when printing excerpt titles
- Don't print surrounding lines when an annotated line is in a virtual file

### CODE REVIEW

**Comment by owenv** [comment]
@swift-ci smoke test

**Comment by owenv** [comment]
The second commit is an additional test case I added to make sure the new style works when swift  emits a diagnostic in a clang-owned buffer, which also interacts with virtual files

**Comment by owenv** [comment]
@swift-ci please smoke test

**Comment by owenv** [comment]
@swift-ci please smoke test macOS

**Comment by owenv** [comment]
@swift-ci smoke test

**Comment by owenv** [comment]
@rintaro I saw you posted about some of the issues working with real and virtual source locations a few years ago here: https://forums.swift.org/t/filename-line-and-column-for-sourceloc/5463

Do you mind looking over these changes, I think I'm fixing a similar kind of problem? I don't know if adding an `isLocInVirtualFile` method to the source manager is a good idea, but I haven't thought of a good alternative yet.

Also, are you still interested in renaming some of these methods? If so, I might try to rename at least SourceManager::getLineNumber and SourceManager::getLineAndCol in a follow-up PR.

**Review by rintaro — APPROVED** [review]
The change looks good. As for `isLocInVirtualFile()` I cannot think of any better option.

> Also, are you still interested in renaming some of these methods? If so, I might try to rename at least SourceManager::getLineNumber and SourceManager::getLineAndCol in a follow-up PR.

Yes, the current method names are very confusing and error prone. Thank you for working on this!

**Comment by owenv** [comment]
@swift-ci smoke test and merge

**Pull request merged**
