### PR TITLE
[CMake] Fix unified builds after #28003

### PR DESCRIPTION
**Pull request by davezarzycki**

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by davezarzycki** [comment]
@swift-ci please clean smoke test macos

**Comment by davezarzycki** [comment]
@swift-ci please clean test macos platform

**Comment by davezarzycki** [comment]
@swift-ci please clean smoke test macos

**Comment by compnerd** [comment]
I totally missed that was changed, thanks for fixing this.

**Review by compnerd — APPROVED** [review]

**Pull request merged**
