### PR TITLE
AST: Move up getBase() to TypeRepr to allow more generic access. NFC

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by jrose-apple** [comment]
If we do this, I think we need to come up with a better name. These "bases" are all pretty different from each other, and relying on it would miss things like DictionaryType that splits in two.

What are you really trying to do?

**Comment by jrose-apple** [comment]
(and additionally, is TypeRepr::walk good enough for whatever you're trying to do?)

**Comment by nkcsgexi** [comment]
Basically, we are trying to reduce some code duplication in #9084 . we need a way to generically access the nested level inside of typerepr.

**Comment by nkcsgexi** [comment]
Per discussion with @jrose-apple , `getBase()` can be misleading as a general type repr method; thus we drop the PR.

**Pull request closed without merging**
