### PR TITLE
[ownership] Change CanonicalOSSALifetime to use an InstModCallback.

### PR DESCRIPTION
**Pull request by gottesmm**
This enables passes to use this as a utility that properly composes with how the
pass maintains its state. If an InstModCallback isn't passed in, we use the
default InstModCallback which should be cheap (always succeeding check for
nullptr + call inline default callback).

----

Should be NFC

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Review by atrick — APPROVED** [review]
Ok. This makes an assumption that `setUseValue` cannot invalidate use iterators. Can you make sure the API specifies that invariant so no one violate it?

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Pull request merged**
