### PR TITLE
[move-only] fix conformance synthesis & conformances in extensions

### PR DESCRIPTION
**Pull request by kavon**
resolves rdar://104986597

### CODE REVIEW

**Comment by kavon** [comment]
@swift-ci please smoke test and merge

**Comment by kavon** [comment]
@swift-ci please smoke test and merge

**Comment by kavon** [comment]
@swift-ci please smoke test macOS

**Comment by kavon** [comment]
@swift-ci please smoke test and merge

**Review by xedin — APPROVED** [review]

**Comment by kavon** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
