### PR TITLE
[TSan] Do not report benign race on `_swiftEmptyArrayStorage`

### PR DESCRIPTION
**Pull request by yln**
A previous commit [1] identified and fixed a benign race on
`_swiftEmptyArrayStorage`.  Unfortunately, we have some code duplication
and the fix was not applied to all the necessary places.  Essentially,
we need to ensure that the "empty array storage" object that backs many
"array like types" is never written to.

I tried to improve the test to capture this, however, it is very
finicky.  Currently, it does not go red on my system even when I remove
the check to avoid the benign race in Release mode.

Relevant classes: Array, ArraySlice, ContiguousArray, ArrayBuffer,
ContiguousArrayBuffer, SliceBuffer.

[1] b9b4c789f32ccd968c0cb7d64f364d819deb3096

rdar://55161564

### CODE REVIEW

**Comment by yln** [comment]
@swift-ci please test

**Comment by yln** [comment]
Also: it might be worth to reduce/remove this code duplication, if possible.

**Comment by yln** [comment]
@swift-ci please test

**Review by lorentey — APPROVED** [review]
This looks good, thank you Julian!

**Comment by yln** [comment]
@swift-ci Please test Linux platform

**Comment by mikeash** [comment]
I'm a bit late, but this looks good, thanks!

**Pull request merged**
