### PR TITLE
[BuildScript] Add products for Swift-DocC and Swift-DocC-Render

### PR DESCRIPTION
**Pull request by d-ronnqvist**
This adds build script products for Swift-DocC and Swift-DocC-Render so that these projects can be built as part of a Swift toolchain.

This adds two new flags to `./utils/build-script` (`--swiftdocc` and `--swiftdoccrender`) and updates the `buildbot_linux` preset and the `mixin_osx_package_base` preset to build Swift-DocC but not Swift-DocC-Render. 

Instead, when only `--swiftdocc` is passed, the Swift-DocC product will copy the already built swift-docc-render template included in the host toolchain (when present) over to the install toolchain. If the host toolchain doesn't include a swift-docc-render template, the Swift-DocC product will raise a warning.

This allows developers to build Swift-DocC from source as part of a toolchain without needing to build Swift-DocC-Render from source (assuming that they haven't made any changes to the Swift-DocC-Render source code).

For developers who want to build a toolchain with both Swift-DocC and Swift-DocC-Render built from source, there are new presets that also include the `--swiftdoccrender` flag. There's also a new `--swift-docc-render` flag added to `./utils/build-toolchain` which selects a preset that build Swift-DocC-Render.

Resolves rdar://79703353

### CODE REVIEW

**Review by shahmishal — APPROVED** [review]

**Comment by shahmishal** [comment]
apple/swift-integration-tests#93
@swift-ci build toolchain

**Comment by ethan-kusters** [comment]
apple/swift-integration-tests#93
@swift-ci build toolchain

**Comment by ethan-kusters** [comment]
@swift-ci test

**Comment by ethan-kusters** [comment]
@swift-ci Please test Linux platform

**Pull request merged**
