### PR TITLE
[Serialization] Serialize Differentiability WT index sorted

### PR DESCRIPTION
**Pull request by kateinoigakukun**
When there are sil_property and sil_differentiability_witness at once,
serialized file couldn't be deserialized because it's index table is
serialized un-sortedly but deserializer assumes that contents of table
index are sorted.

This patch fixes the un-sorted serialization and adds test case to
ensure that table index contents can be deserialized

CC: @compnerd @gottesmm

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci please test

**Review by compnerd — APPROVED** [review]

**Comment by compnerd** [comment]
CC: @slavapestov @rxwei @dan-zheng

**Review by dan-zheng — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
@swift-ci please test

**Comment by kateinoigakukun** [comment]
@slavapestov @rxwei @dan-zheng Sorry for ping, would you mind merging this PR?

**Pull request merged**
