### PR TITLE
[5.5][SymbolGraph] Add information about "inherited docs" for synthesized symbols

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
Resolves rdar://77205889

This PR ports https://github.com/apple/swift/pull/36863 and https://github.com/apple/swift/pull/37248 to `release/5.5`.

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Comment by QuietMisdreavus** [comment]
@swift-ci Please build toolchain macOS platform

**Comment by QuietMisdreavus** [comment]
Retrying the toolchain build to pull in https://github.com/apple/swift/pull/37245.

@swift-ci Please build toolchain macOS platform

**Comment by QuietMisdreavus** [comment]
Same issue in the macOS test.

@swift-ci Please test macOS platform

**Review by franklinsch — APPROVED** [review]

**Review by akyrtzi — APPROVED** [review]

**Pull request merged**
