### PR TITLE
Update UUID to take advantage of SE-0205

### PR DESCRIPTION
**Pull request by benasher44**
This updates UUID to use `withUnsafePointer` for `let`s

Now that SE-0205 has landed, we don't need to make local copies of the uuid byte tuples, in order to get pointers to them. We can use the new `withUnsafePointer` that works with `let`s.

### CODE REVIEW

**Comment by harlanhaskins** [comment]
@benasher44 Welcome to the project, and thank you for contributing to Swift! I'm going to tag @moiseev for review here, but before then I'll kick off CI.

@swift-ci please smoke test

**Comment by benasher44** [comment]
Thanks!

**Review by moiseev — APPROVED** [review]
LGTM

**Comment by millenomi** [comment]
LGTM, and we probably want an equivalent patch in the Foundation repo.

**Comment by parkera** [comment]
Agreed with @millenomi

**Comment by benasher44** [comment]
Published equivalent patch @ apple/swift-corelibs-foundation#1728 :)

**Comment by millenomi** [comment]
@swift-ci please test and merge

**Comment by millenomi** [comment]
… I don't appear to have that magic power.

**Pull request merged**
