### PR TITLE
Rename Process to CommandLine

### PR DESCRIPTION
**Pull request by parkera**
#### What's in this pull request?

As part of [SE-0086](https://github.com/apple/swift-evolution/blob/master/proposals/0086-drop-foundation-ns.md), we decided to rename the `NSTask` class to `Process`. This PR changes `Swift.Process` to `Swift.CommandLine` to make that possible.
#### Resolved bug number

Part of SE-0086
rdar://27415229

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by parkera** [comment]
swiftpm PR coming soon.

**Comment by parkera** [comment]
@swift-ci please test

**Comment by parkera** [comment]
This will fail without the swiftpm PR, but we can verify the rest.

**Comment by rintaro** [comment]
I guess adding migration aid can be harmful in this case
```swift
@available(*, unavailable, renamed: "CommandLine")
typealias Process = CommandLine
```
Is there any way to automated migration?

**Comment by parkera** [comment]
I'm going to add a temporary typealias (for a day or two), but once we rename `NSTask` to `Process`, we can't have an unavailable attribute on it.

**Comment by parkera** [comment]
@swift-ci Please test and merge

**Comment by parkera** [comment]
We're going to go ahead and merge this.

**Pull request merged**
