### PR TITLE
[DNM, Incremental] Hack to try swapping out global LLVMContext

### PR DESCRIPTION
**Pull request by davidungar**
A crude hack to try making a new LLVMContext for each primary. Not the final form of the change, but PR for testing!

### CODE REVIEW

**Comment by davidungar** [comment]
@swift-ci please smoke test os x platform

**Comment by davidungar** [comment]
@swift-ci please check compiler performance

**Comment by davidungar** [comment]
@swift-ci please check source compatability

**Comment by davidungar** [comment]
@swift-ci please test asan

**Comment by davidungar** [comment]
@swift-ci please test compiler performance

**Comment by davidungar** [comment]
@swift-ci please test source compatibility

**Comment by davidungar** [comment]
@swift-ci please test windows

**Comment by davidungar** [comment]
@swift-ci please test source compatibility debug

**Comment by davidungar** [comment]
@swift-ci please smoke test linux platform

**Comment by CodaFi** [comment]
Repeating some points from our discussion in a different forum: Ultimately, I don't think it's correct to swap this out at the points where it's being swapped - mostly because I don't think this covers all the places where there's a bad data dependency on the global context. As long as there are calls to install state outside of the context for a given module, we're going to keep observing the non-deterministic behavior. I think a patch that breaks the layering violations here would really help and would be a lot simpler to reason about.

**Comment by CodaFi** [comment]
We should even be able to do it incrementally. For example, the call to install the remarks streamer on the global context is bogus and can be refactored quite nicely if the SILModule owns its own LLVMContext.

**Comment by davidungar** [comment]
Thank you, @CodaFi . Great points! Will close and redo, according to suggestions by you and @slavapestov . See https://github.com/apple/swift/pull/31034

**Pull request closed without merging**
