### PR TITLE
Revert "tests: diable Interop/Cxx/stdlib/overlay/custom-sequence-typechecker.swift"

### PR DESCRIPTION
**Pull request by zoecarver**
Reverts apple/swift#60217

### CODE REVIEW

**Comment by zoecarver** [comment]
preset=buildbot,tools=RA,stdlib=RD,test=non_executable 
@swift-ci Please test with preset macOS

**Comment by zoecarver** [comment]
@eeckstein does this look good?

**Comment by eeckstein** [comment]
@zoecarver What was the fix which lets the test pass now?

**Comment by zoecarver** [comment]
@swift-ci please test macOS

**Comment by zoecarver** [comment]
@swift-ci please test macOS Platform

**Comment by zoecarver** [comment]
> @zoecarver What was the fix which lets the test pass now?

Nothing. I kicked this build off right after you disable the test, so I don't think any fixes landed in that time.

**Review by eeckstein — APPROVED** [review]
LGTM.
Let's take a close look at https://ci.swift.org/job/oss-swift_tools-RA_stdlib-DA_test-device-non_executable. This is the job where the test failed.
rdar://97532965

cc @meg-gupta

**Comment by eeckstein** [comment]
Maybe this was also caused by the lookuptable problem (which should be fixed by https://github.com/apple/swift/pull/60260)

**Comment by egorzhdan** [comment]
@zoecarver is it OK if I merge this?

**Pull request merged**
