### PR TITLE
[SIL] Removed Indirect_In_Constant convention.

### PR DESCRIPTION
**Pull request by nate-chandler**
It is no different from `@in`.

Continue parse `@in_constant` in textual and serialized SIL, but just as an alias for `@in`.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by atrick — APPROVED** [review]
🎆 😃

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test windows platform

**Review by eeckstein — APPROVED** [review]

**Pull request merged**
