### PR TITLE
[5.0] [Sema] Add warning for ambiguous value assignment when using Optional

### PR DESCRIPTION
**Pull request by theblixguy**
Cherry picked from #21621

* **Explanation**: If `T` is an enum or a struct, containing a case or a static property named `none`, then  assigning `.none` to a variable of type `T?` would cause it to have the value `Optional.none` rather than `T.none`.

    Example:

    ```swift
    enum Foo {
      case none
    }

    let test: Foo? = .none // Assigned Optional.none instead of Foo.none
    let isEqual: Bool = test == Foo.none // false
    ```

* **Scope**: Affects value assignment to `Optional`s.

* **Issue**: rdar://problem/26126801 + [SR-2176](https://bugs.swift.org/browse/SR-2176), [SR-3711](https://bugs.swift.org/browse/SR-3711), [SR-6044](https://bugs.swift.org/browse/SR-6044), [SR-8283](https://bugs.swift.org/browse/SR-8283), [SR-8451](https://bugs.swift.org/browse/SR-8451) & [SR-8515](https://bugs.swift.org/browse/SR-8515).

* **Risk**: Low. There's a new diagnostic in case there's any ambiguity (i.e. if the type contains a case or a property which matches the case in `Optional`).

* **Testing:** Added new `Enum` tests to verify that the new diagnostic is only emitted in special cases like above.

* **Reviewed by:** @brentdax

### CODE REVIEW

**Comment by theblixguy** [comment]
Can someone invoke the CI for me? @brentdax @xedin

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@DougGregor @xedin Do you want to take this for 5.0?

**Comment by xedin** [comment]
Since new warnings might break build in warning-as-error mode and this is pretty narrow I'd say we should just let this bake in master for a while...

**Comment by AnnaZaks** [comment]
While this is a super useful improvement, let's wait until the next release. We are trying to converge Swift 5, so focusing on fixing regressions and critical ABI tasks. Thank you!

**Pull request closed without merging**
