### PR TITLE
[SourceKit] Add a new request to translate markup text to its XML equivalence. rdar://30587403

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@bitjammer mind taking a look at this patch?

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Review by bitjammer — APPROVED** [review]
Nice!

**Comment by gparker42** [comment]
This failed ASAN testing. I'm reverting in #8088. Please do not commit again without running ASAN first.

**Comment by bitjammer** [comment]
Build log here: https://ci.swift.org/job/oss-swift-incremental-ASAN-RA-osx/177/testReport/junit/Swift(macosx-x86_64)/SourceKit_ExtractComment/extract_comments_swift/

**Comment by bitjammer** [comment]
@nkcsgexi, `LineList` only has an ArrayRef of `Line`s, and `Line` only has a `StringRef`. You might want to pass an `MC &` into `getLineListFromComment` perhaps and hold onto it in the stack frame above.

**Comment by nkcsgexi** [comment]
oh, that makes sense.

**Pull request merged**
