### PR TITLE
[Macros] Ensure reaping executable plugin process

### PR DESCRIPTION
**Pull request by rintaro**
rdar://126489446

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by rintaro** [comment]
@swift-ci Please Build Toolchain macOS platform

**Review by hamishknight — APPROVED** [review]

**Review by compnerd — APPROVED** [review]

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please build Toolchain macOS

**Pull request merged**
