### PR TITLE
stdlib: fix availability for internal COW checks.

### PR DESCRIPTION
**Pull request by eeckstein**
Those checks should only be done if linked with a built library, but not when linked with the OS libraries.

Also: disable COW checking by default, and enable it for specific tests
COW checking needs that all libraries are consistently compiled with asserts enabled. This is not the case for the Foundation overlay anymore.
Therefore it does not work with some tests which interop with Foundation.
The solution here is to disable COW checking by default, but enable it for Array tests which do not interop with Foundation.

 rdar://79412058

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by benrimmington** [comment]
Could you add a `-Xfrontend -define-availability` macro to a CMake file?

```cmake
if(enable_assertions)
  # "9999" means: enable if linked with a built library,
  # but not when linked with the OS libraries.
  # Note: this must not be changed to a "real" OS version.
  list(APPEND swift_stdlib_compile_flags "-Xfrontend" "-define-availability")
  list(APPEND swift_stdlib_compile_flags "-Xfrontend" "\"SwiftStdlib_InternalCOWChecks:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999\"")
endif()
```

```swift
@available(SwiftStdlib_InternalCOWChecks, *)

if #available(SwiftStdlib_InternalCOWChecks, *) {
```

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by varungandhi-apple** [comment]
Tracking radar: rdar://79412058 (Fix availability for internal COW checks)

**Comment by eeckstein** [comment]
@benrimmington That's an excellent idea! Unfortunately there are some problems when this goes through a swift interface file: https://ci.swift.org/job/swift-PR-macos/27765/console

**Comment by benrimmington** [comment]
Why are the failures only for watchOS simulator?

```
Swift.swiftmodule/i386-apple-watchos-simulator.swiftinterface:6029:39: error: expected version number
      if #available(_InternalCOWChecks, *) {
                                      ^
```

You could try adding a version number to the macro name:

```diff
-list(APPEND swift_stdlib_compile_flags "-Xfrontend" "_InternalCOWChecks:macOS ${v9999}, iOS ${v9999}, watchOS ${v9999}, tvOS ${v9999}")
+list(APPEND swift_stdlib_compile_flags "-Xfrontend" "_InternalCOWChecks ${v9999}:macOS ${v9999}, iOS ${v9999}, watchOS ${v9999}, tvOS ${v9999}")

-@available(_InternalCOWChecks, *)
+@available(_InternalCOWChecks 9999, *)

-if #available(_InternalCOWChecks, *) {
+if #available(_InternalCOWChecks 9999, *) {
```

**Comment by eeckstein** [comment]
Adding a version number does not help. The problem is that as soon as it goes through a `swiftinterface` file, the availability macro is missing. It would be required to add the macro to all swift compiler invocations.

> Why are the failures only for watchOS simulator?

I think it depends on the installed Xcode what module files need to be rebuilt for which platform.

**Comment by benrimmington** [comment]
> Adding a version number does not help.

The new Concurrency module uses a similar [`SwiftStdlib 5.5`](https://github.com/apple/swift/blob/6ec0bbd49c881ccfe5f32a6b9c2c21db9afa711e/stdlib/public/Concurrency/CMakeLists.txt#L100-L101) macro, without this issue AFAIK.

> The problem is that as soon as it goes through a `swiftinterface` file, the availability macro is missing.

The macro shouldn't be required by swiftinterface files, according to the apple/swift#33439 description:

> The use of availability macros in the `@available` specification is expanded at parsing and should not be visible in any compiler outputs. This includes the swiftinterfaces which will show the full classic availability specification.

**Comment by eeckstein** [comment]
ok, seems to be a problem with generating swiftinterface files. I'll let this up to someone else to investigate and fix.

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci test macOS

**Comment by eeckstein** [comment]
@swift-ci test macOS

**Comment by eeckstein** [comment]
@swift-ci test macOS

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by kavon** [comment]
@swift-ci please smoke test macOS platform

**Pull request merged**
