### PR TITLE
[Concurrency] Fix memory leak around mismatched refcounting in Embedded Concurrency

### PR DESCRIPTION
**Pull request by kubamracek**
This fixes a problem in Embedded Concurrency that manifests as a memory leak of memory of tasks, as they are never free'd. The problem is that we have been (incorrectly) using the standard Swift's HeapObject struct as the base class for Job and AsyncTask, and this comes with standard Swift's refcounting implementation, which is incompatible with Embedded Swift's runtime.

The suggested solution in this PR is to make `HeapObject.h` present a different HeapObject when using the header in Embedded Swift mode (via a `-D SWIFT_RUNTIME_EMBEDDED`).

Also adding a test that checks that all allocations involved in creating, awaiting and destroying a task are free'd.

rdar://138953689

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by ktoso — APPROVED** [review]
I'm more ok with this approach than some other alternative ideas like introducing a new "Base" for heap object. This seems more understandable without changing a lot of code, lgtm

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Pull request merged**
