### PR TITLE
bisecting arraytraps test failure

### PR DESCRIPTION
**Pull request by gparker42**
bisecting arraytraps test failure

### CODE REVIEW

**Comment by gparker42** [comment]
@swift-ci smoke test linux

**Comment by gparker42** [comment]
@swift-ci smoke test linux

**Comment by gparker42** [comment]
@swift-ci smoke test linux

**Comment by gparker42** [comment]
@swift-ci smoke test linux

**Comment by gparker42** [comment]
@swift-ci smoke test linux

**Comment by gparker42** [comment]
@swift-ci smoke test linux

**Comment by gribozavr** [comment]
@gparker42 Is this PR still needed?  The test is fixed.

**Pull request closed without merging**
