### PR TITLE
[5.6][AST] scan `@_exported` imports of source files for display decls

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
Cherrypick of https://github.com/apple/swift/pull/40810

Explanation: In `-emit-module` builds, symbols declared in headers were not being emitted in symbol graphs, due to SourceFile-based modules not including decls from the underlying Clang module.

Scope: This is a modification of `getDisplayDecls`, but it has been restricted to only affect SymbolGraphGen.

Issue: rdar://85230067

Risk: Low. While this is a change to `getDisplayDecls`, the change has been restricted to only occur during SymbolGraphGen, and should not affect regular compilation.

Testing: Source compatibility has been tested with this change, and no regressions have occurred. In addition, the following lit tests have been updated or added:

* `SymbolGraph/ClangImporter/EmitWhileBuilding` has been updated to ensure that Clang-based symbols appear during an `-emit-module` build.
* `SymbolGraph/ClangImporter/Submodules` has been added to ensure that re-exporting a Clang submodule does not crash the process, and to ensure that re-exporting multiple Clang modules does not trip the "duplicate decls" assertion added to the recursive `getDisplayDecls`.
* `ModuleInterface/exported-import` has been added to ensure that re-exporting a module does not add those symbols to the generated module interface file.

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test source compatibility

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test source compatibility

**Comment by QuietMisdreavus** [comment]
This PR now includes the change from https://github.com/apple/swift/pull/40841, as it was reverted in https://github.com/apple/swift/pull/40880.

**Review by airspeedswift — APPROVED** [review]

**Comment by QuietMisdreavus** [comment]
It looks like there were problems i'd overlooked in the source-compatibility since it had passed for `main`. I'm going to investigate them this morning.

```
(FAIL_Doggie_5.0_BuildSwiftPackage.log)

error: emit-module command failed due to signal 6 (use -v to see invocation)Assertion failed: (inserted && "there should be no duplicate decls"), function getDisplayDecls, file Module.cpp, line 967.
```

**Comment by QuietMisdreavus** [comment]
It seems like when a module re-exports two different Clang modules, there are repeat declarations of the implicit items added by the Clang importer: this specific case was failing on `__NSConstantString`. I imagine we'll specially need to handle these declarations.

**Comment by bitjammer** [comment]
@swift-ci Please test source compatibility

**Comment by franklinsch** [comment]
@swift-ci please test

**Comment by franklinsch** [comment]
@swift-ci please test source compatibility

**Comment by QuietMisdreavus** [comment]
The issue in the previous source-compatibility testing is the same one that is being fixed in https://github.com/apple/swift/pull/41115. I'm not cherry-picking it onto this branch (yet) since it only affects builds with assertions in it, but it will still be helpful to assist with developing on the branch generally.

**Comment by QuietMisdreavus** [comment]
I've rebased the branch and reworked the commits to properly reflect the changes being cherry-picked. Since https://github.com/apple/swift/pull/40696 was cherry-picked separately in https://github.com/apple/swift/pull/41017, the initial commit has been changed to only include https://github.com/apple/swift/pull/40860.

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test source compatibility

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test source compatibility

**Comment by QuietMisdreavus** [comment]
@swift-ci Please build toolchain macOS platform

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Comment by QuietMisdreavus** [comment]
@swift-ci Please build toolchain macOS platform

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test source compatibility

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Comment by QuietMisdreavus** [comment]
@swift-ci Please build toolchain macOS platform

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test source compatibility

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
