### PR TITLE
[ossa][frontend] Separately namespace enable-ossa-modules in the module cache so that the flag causes recompilation of imported resilient modules.

### PR DESCRIPTION
**Pull request by gottesmm**
This will enable users to try out the '-enable-ossa-modules' flag if their
compiler supports it and get OSSA code on all inlinable code that they use. The
idea is that this is a nice way to stage this in and get more testing.

### CODE REVIEW

**Comment by gottesmm** [comment]
My largest concern here is I need to make sure that I understand how this impacts the swift standard library. My guess is that even though we enable (in cmake) the -enable-ossa-modules flag on it, it is just compiled normally. So with the flag enabled I think we should recompile that as well from the swift interface file (I guess).

**Comment by gottesmm** [comment]
I talked with @artemcm and we came up with some good ways to test out the behavior with the stdlib.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
Looks like an lldb issue hit all 3 of the PR tests.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Review by artemcm — APPROVED** [review]
Looks good to me.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
I updated lldb in:

apple/llvm-project#2709

**Comment by gottesmm** [comment]
apple/llvm-project#2709

@swift-ci test

**Comment by gottesmm** [comment]
apple/llvm-project#2709

@swift-ci test windows platform

**Comment by gottesmm** [comment]
apple/llvm-project#2709

@swift-ci test

**Comment by gottesmm** [comment]
apple/llvm-project#2709

@swift-ci test

**Comment by gottesmm** [comment]
I have a fix for the windows test. I am just going to let the full tests finish and then retest with a smoke test again before merging.

**Comment by gottesmm** [comment]
(the problem was I put in a sub shell when I didn't need it)

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
apple/llvm-project#2709

@swift-ci smoke test

**Pull request merged**
