### PR TITLE
[cxx-interop] Overhaul virtual method support

### PR DESCRIPTION
**Pull request by egorzhdan**
This adds a new implementation of virtual method dispatch that handles reference types correctly.

Previously, for all C++ types an invocation of a virtual method would actually get dispatched statically. For value types this is expected and matches what C++ does because of slicing. For reference types, however, this is incorrect, we should do dynamic dispatch.

rdar://123852577

### CODE REVIEW

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please build toolchain macOS

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please build toolchain macOS

**Comment by glessard** [comment]
It seems like PR testing has been failing since this was merged: https://ci.swift.org/job/swift-PR-macos/

**Comment by glessard** [comment]
Fix for the tests: https://github.com/apple/swift/pull/72050

**Pull request merged**
