### PR TITLE
[stdlib] Remove a couple of obsoleted-in-4.0 methods

### PR DESCRIPTION
**Pull request by airspeedswift**
Now that 3.0 support was dropped. Missed these in #19008. Causing problems reported [here](https://forums.swift.org/t/swift-is-overly-worried-about-me-mixing-up-flatmap-and-compactmap/19801/5).

Note, the ABI checker changes are false positives. These have not been callable since ABI stability was declared, so not ABI.

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please smoke test and merge

**Review by moiseev — APPROVED** [review]
:shipit:

**Comment by jrose-apple** [comment]
Unfortunately this isn't actually going to be causing those problems. Jens is complaining about a deprecation, not an obsoletion.

**Comment by moiseev** [comment]
We don't need these guys in our ABI regardless.

**Pull request merged**
