### PR TITLE
port SwiftPrivatePthreadExtras to Windows

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @jrose-apple ... not sure of a good person to ask to take a look at this change, and I'm not sure if there is something Apple internal which might be impacted here.

**Comment by jrose-apple** [comment]
It counts as part of the stdlib, so maybe @lancep or @lorentey? It looks reasonable to me, and I don't think there'll be anything Apple-internal to worry about other than possible private tests, which are our problem anyway. (I didn't actually check though.)

**Review by lorentey — APPROVED** [review]
This looks good to me! (I'm not too familiar with this corner of the repo though.)

**Pull request merged**
