### PR TITLE
Canonicalize Definit-init conditional branch creation.

### PR DESCRIPTION
**Pull request by atrick**
This is purely a simplification of the implementation and canonicalization of the SIL.

The test case changes are a result of conditional branches being more consistently canonical, with the true branch falling through.

There is only one new commit here. This is blocked on PR #19886.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test.

**Review by gottesmm — APPROVED** [review]
LGTM

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
@swift-ci smoke test.

**Pull request merged**
