### PR TITLE
GlobalOpt: handle access markers correctly.

### PR DESCRIPTION
**Pull request by eeckstein**
rdar://problem/59345288

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Review by atrick — APPROVED** [review]
LGTM

FYIs:

- this seems fine for now, but generally we shouldn't need to "see through" access markers to check for memory access. To see if an access is a store, just check if it's a modify.

- I have a bunch of fixes for MemoryBehavior, TempRValueOpt, and LetPropertiesOpt for access markers on a branch that I'm just trying to figure out how to test

**Comment by eeckstein** [comment]
@swift-ci smoke test linux

**Pull request merged**
