### PR TITLE
[CMake] Add missing libedit dependency

### PR DESCRIPTION
**Pull request by davezarzycki**

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Review by compnerd — CHANGES_REQUESTED** [review]
Hmm, currently, libedit is not a hard dependency, and I am relying on that for the Windows build.  Can you please guard this?

```
if(LibEdit_FOUND)
  target_link_libraries(swiftImmediate PRIVATE edit)
endif()
```

**Comment by davezarzycki** [comment]
How does "Immediate" library compile then? It seems to use libedit APIs unconditionally.

**Comment by davezarzycki** [comment]
@compnerd – I think I found a workaround. Please review.

@swift-ci please smoke test

**Review by compnerd — APPROVED** [review]
Thanks!

**Pull request merged**
