### PR TITLE
Update some Readme strucutre and styles

### PR DESCRIPTION
**Pull request by BrandonMathis**
## What Changed
- Added some descriptive headers to documentation
- Adds swift logo to top of readme

### CODE REVIEW

**Comment by kud1ing** [comment]
Some of the changes are already in master (SVG logo instead of PNG). Also the PR contains an unrelated merge commit.

**Comment by BrandonMathis** [comment]
Thx @kud1ing

**Comment by gottesmm** [comment]
@BrandonMathis the general courtesy of how this works is generally ping after a week.

That being said... @tkremenek Ping?

**Comment by tkremenek** [comment]
Looks great.  Sorry for the delay.

**Pull request merged**
