### PR TITLE
[Compile Time Constant Extraction] Extract enums

### PR DESCRIPTION
**Pull request by jPaolantonio**
This PR adds compile time constant extraction of enumerations definitions and variables.

### CODE REVIEW

**Comment by jPaolantonio** [comment]
@swift-ci test

**Comment by jPaolantonio** [comment]
@swift-ci test

**Comment by jPaolantonio** [comment]
@swift-ci test

**Comment by jPaolantonio** [comment]
@swift-ci test

**Review by artemcm — APPROVED** [review]

**Pull request merged**
