### PR TITLE
Prefix experimental interop flag with -Xfrontend

### PR DESCRIPTION
**Pull request by adrian-prantl**
(cherry picked from commit 8cd4de506d6cbfc54b64243d3a5ebcaa2ec04b75)

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci  test

**Comment by adrian-prantl** [comment]
@swift-ci smoke test

**Comment by adrian-prantl** [comment]
@swift-ci smoke test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Review by JDevlieghere — APPROVED** [review]
LGTM!

**Pull request merged**
