### PR TITLE
Add AccessEnforcementOpts fast paths.

### PR DESCRIPTION
**Pull request by atrick**
Add AccessEnforcementOpts fast paths.
1. During identifyAccess, determine if there are either any
identical accesses or an accesses that aren't already marked
no_nested_storage. If there are neither, then skip the subsequent
data flow analysis.

2. In the new StorageSet, indicate whether identical storage was
seen elsewhere in the function. During dataflow, only add an access
to the out-of-scope access set if was marked as having identical
storage with another access.

3. During data flow, don't track in scope conflicts for
instructions already marked [no_nested_conflict].
0d9ebae

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci test source compatibility

**Comment by atrick** [comment]
@swift-ci test

**Review by shajrawi — APPROVED** [review]
LGTM

**Pull request merged**
