### PR TITLE
[6.1] Introduce a new Initializer subclass for the arguments of custom attributes

### PR DESCRIPTION
**Pull request by DougGregor**
* *Explanation*: Improve the modeling of declaration contexts within custom attributes, particularly those used for macro arguments. Fixes crashes involving closures within attached macro arguments.
* *Scope*: Affects the internal representation of property wrappers and attached macros.
* *Issues*: https://github.com/swiftlang/swift/issues/76409 / rdar://136997841
* *Original PR*: https://github.com/swiftlang/swift/pull/78030
* *Risk*: Low. The representational change primarily affects property wrappers, but is fairly narrow and builds on existing logic.
* *Testing*: New tests added
* *Reviewed by*: @hamishknight , @rintaro , @slavapestov

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test platform Windows

**Review by hborla — APPROVED** [review]

**Comment by DougGregor** [comment]
Windows failure doesn't ring a bell:
```
# .---command stderr------------
# | Traceback (most recent call last):
# |   File "<string>", line 1, in <module>
# |   File "c:\program files (x86)\microsoft visual studio\shared\python39_64\lib\multiprocessing\spawn.py", line 116, in spawn_main
# |     exitcode = _main(fd, parent_sentinel)
# |   File "c:\program files (x86)\microsoft visual studio\shared\python39_64\lib\multiprocessing\spawn.py", line 126, in _main
# |     self = reduction.pickle.load(from_parent)
# |   File "c:\program files (x86)\microsoft visual studio\shared\python39_64\lib\multiprocessing\connection.py", line 967, in rebuild_pipe_connection
# |     handle = dh.detach()
# |   File "c:\program files (x86)\microsoft visual studio\shared\python39_64\lib\multiprocessing\reduction.py", line 131, in detach
# |     return _winapi.DuplicateHandle(
# | PermissionError: [WinError 5] Access is denied
# | Traceback (most recent call last):
# |   File "<string>", line 1, in <module>
# |   File "c:\program files (x86)\microsoft visual studio\shared\python39_64\lib\multiprocessing\spawn.py", line 107, in spawn_main
# |     new_handle = reduction.duplicate(pipe_handle,
# |   File "c:\program files (x86)\microsoft visual studio\shared\python39_64\lib\multiprocessing\reduction.py", line 79, in duplicate
# |     return _winapi.DuplicateHandle(
# | PermissionError: [WinError 5] Access is denied
# | Traceback (most recent call last):
# |   File "<string>", line 1, in <module>
# |   File "c:\program files (x86)\microsoft visual studio\shared\python39_64\lib\multiprocessing\spawn.py", line 107, in spawn_main
# |     new_handle = reduction.duplicate(pipe_handle,
# |   File "c:\program files (x86)\microsoft visual studio\shared\python39_64\lib\multiprocessing\reduction.py", line 79, in duplicate
# |     return _winapi.DuplicateHandle(
# | PermissionError: [WinError 5] Access is denied
# `-----------------------------
```

**Comment by DougGregor** [comment]
@swift-ci please test Windows

**Pull request merged**
