### PR TITLE
Make SIMD types Codable.

### PR DESCRIPTION
**Pull request by stephentyrone**
We're considering this a bugfix, on the premise that any stdlib type that doesn't have a reason not to be Codable should be.

### CODE REVIEW

**Comment by stephentyrone** [comment]
@swift-ci please test

**Comment by stephentyrone** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
> any stdlib type that doesn't have a reason not to be Codable should be.

In particular, any _new_ type just added, like this one.

**Review by airspeedswift — APPROVED** [review]
Needs tests (can be separate PR) but LGTM.

**Comment by stephentyrone** [comment]
@swift-ci please smoke test

**Comment by stephentyrone** [comment]
@swift-ci please smoke test

**Comment by stephentyrone** [comment]
@swift-ci please smoke test

**Comment by stephentyrone** [comment]
@swift-ci please test

**Pull request merged**
