### PR TITLE
XFAIL a crasher that is periodically hanging the compiler in CI.

### PR DESCRIPTION
**Pull request by rudkx**
rdar://problem/29145783 tracks re-enabling this.

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test and merge.

**Comment by jrose-apple** [comment]
If it's actually hanging, then using REQUIRES or UNSUPPORTED is probably better than waiting for it to time out.

**Comment by rudkx** [comment]
Err, yeah, not sure what I was thinking there since it doesn't reliably fail either.

**Comment by rudkx** [comment]
@swift-ci Please smoke test and merge.

**Pull request merged**
