### PR TITLE
Update benchmark code for SE-0081 moved where clause - NFC

### PR DESCRIPTION
**Pull request by bitjammer**

### CODE REVIEW

**Comment by bitjammer** [comment]
@swift-ci Please test

**Comment by bitjammer** [comment]
Builds are too broken to run tests now. Holding off.

**Comment by gottesmm** [comment]
Build is fixed now. Trying a build.

**Comment by gottesmm** [comment]
@swift-ci Please smoke test

**Comment by bitjammer** [comment]
Looks like some of this got cleaned up when removing some redundant Equatable requirements.

**Comment by bitjammer** [comment]
@swift-ci Smoke test

**Pull request merged**
