### PR TITLE
A basic YAML to JSON conversion tool

### PR DESCRIPTION
**Pull request by harlanhaskins**
This tool will take an input YAML file, convert it piece-by-piece to JSON, and output the results to stdout.

### CODE REVIEW

**Comment by harlanhaskins** [comment]
@DougGregor Mind taking a look at this? Thanks!

**Comment by hyp** [comment]
Maybe it would be better to add this of tool to LLVM itself?

**Comment by harlanhaskins** [comment]
@swift-ci please test

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test

**Comment by jrose-apple** [comment]
I'm going to vote against checking this in. If we really need our data in JSON format rather than YAML, just don't write it in YAML.

**Comment by harlanhaskins** [comment]
I think you're right. This whole thing never sat right with me, and as much as I appreciate the read-and-writeability of YAML it's just not worth it.

**Pull request closed without merging**
