### PR TITLE
Revert "[CSRanking] Delete a pointless old ranking hack. NFC"

### PR DESCRIPTION
**Pull request by slavapestov**
This broke the source compatibility test suite. Sorry @DougGregor :-)

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
More specifically:

```
/Volumes/Transcend/swift-source-compat-suite/project_cache/ReactiveCocoa/Carthage/Checkouts/ReactiveSwift/Sources/Signal.swift:579:10: error: ambiguous use of 'flatMap(_:transform:)'
                return flatMap(.latest) { value in
                       ^
/Volumes/Transcend/swift-source-compat-suite/project_cache/ReactiveCocoa/Carthage/Checkouts/ReactiveSwift/Sources/Flatten.swift:833:14: note: found this candidate
        public func flatMap<U>(_ strategy: FlattenStrategy, transform: @escaping (Value) -> SignalProducer<U, Error>) -> Signal<U, Error> {
                    ^
/Volumes/Transcend/swift-source-compat-suite/project_cache/ReactiveCocoa/Carthage/Checkouts/ReactiveSwift/Sources/Flatten.swift:848:14: note: found this candidate
        public func flatMap<U>(_ strategy: FlattenStrategy, transform: @escaping (Value) -> SignalProducer<U, NoError>) -> Signal<U, Error> {
                    ^
```

**Comment by xedin** [comment]
@slavapestov @DougGregor good news is that I'm going to fix it soon!

**Comment by DougGregor** [comment]
*groan*. Thanks for the revert @slavapestov

**Comment by NachoSoto** [comment]
Ha @ReactiveCocoa/ReactiveSwift FTW

**Pull request merged**
