### PR TITLE
Remove swift-nio-ssl from main scheme

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci build toolchain

**Comment by kateinoigakukun** [comment]
Don't we need swift-nio to build swift-docc? https://github.com/apple/swift-docc/blob/0c546df1a341b81a94e9b67e38cdf5801d49802f/Package.swift#L147

Additionally, swift-sdk-generator will use it too. CC: @MaxDesiatov

**Review by MaxDesiatov — DISMISSED** [review]
Removing `swift-nio` would prevent Swift SDK Generator from building on Swift CI as a part of Wasm jobs, which is what we're trying to do in https://github.com/apple/swift/pull/72931.

**Comment by shahmishal** [comment]
@swift-ci build toolchain

**Comment by shahmishal** [comment]
@swift-ci build toolchain macOS

**Review by kateinoigakukun — APPROVED** [review]

**Review by MaxDesiatov — APPROVED** [review]

**Pull request merged**
