### PR TITLE
[build-script] Enable SwiftEvolve for building and testing via build-script

### PR DESCRIPTION
**Pull request by akyrtzi**

### CODE REVIEW

**Comment by akyrtzi** [comment]
\cc @brentdax

**Comment by akyrtzi** [comment]
@swift-ci Please test

**Comment by akyrtzi** [comment]
@swift-ci Please test

**Comment by benlangmuir** [comment]
This looks almost like https://github.com/apple/swift/pull/22148, but there are some differences in build-script-impl.

**Comment by brentdax** [comment]
Ugh, I thought that #22148 had merged, but it looks like a test failure stopped it. I'll close it out in favor of this PR.

**Comment by benlangmuir** [comment]
@brentdax can you comment on the differences between the PRs in `build-script-impl`?

**Comment by benlangmuir** [comment]
@swift-ci please build toolchain

**Comment by brentdax** [comment]
@benlangmuir You're right, the build-script-impl change in this PR was incomplete. I've fixed the merge conflicts in #22148; we'll see if that version now works.

**Comment by akyrtzi** [comment]
Closing in favor of https://github.com/apple/swift/pull/22148

**Pull request closed without merging**
