### PR TITLE
[Gardening] SIL: Spelling of live range.

### PR DESCRIPTION
**Pull request by nate-chandler**
Standardize on the standard spelling of the term "liverange"/"live range" replacing uses of "liferange"/"life range".

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by eeckstein — APPROVED** [review]
lgtm

**Comment by nate-chandler** [comment]
@swift-ci please smoke test

**Comment by nate-chandler** [comment]
@swift-ci please test windows platform

**Pull request merged**
