### PR TITLE
[cxx-interop] Fix lookup failure for operators in templated classes

### PR DESCRIPTION
**Pull request by egorzhdan**
If an operator is declared as a method of a templated class, we were failing to look it up during auto-conformance to `UnsafeCxxInputIterator`.

This fixes `Interop/Cxx/stdlib/use-std-map.swift` on Ubuntu.

rdar://102420290

### CODE REVIEW

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Review by zoecarver — APPROVED** [review]
LGTM. 

At some point it would be nice to have a test that std::vector's conformance starts being automatic (as that was one of the motivators for this patch) but that can be a follow up.

**Comment by egorzhdan** [comment]
Yeap, we'll need one more patch to start instantiating out-of-line `operator==`. This patch only deals with member operators.

**Pull request merged**
