### PR TITLE
Reduce breaks in Codeview linetables

### PR DESCRIPTION
**Pull request by ellishg**
Summary:
CodeView does not recognize zero as an artificial line location
and so a line location of zero causes unexpected behavior when
stepping through user code. If we find a line location of zero
and our scope has not changed, we use the most recent debug
location. That is expected to be the user code that most likely
relates to the current instruction and is similar to the behavior
in LLDB.

Test Plan:
test/DebugInfo/linetable-codeview.swift

### CODE REVIEW

**Comment by sparkasaurusRex** [comment]
@dcci @adrian-prantl Please take a look at my commit.

**Review by dcci — APPROVED** [review]
Fine by me. @adrian-prantl, what do you think?

**Comment by adrian-prantl** [comment]
This works for me, too.

**Comment by adrian-prantl** [comment]
@swift-ci test

**Pull request merged**
