### PR TITLE
[test] Update alternative interface framework module interface test to run on both arm64 and x86_64

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
Running all lit tests on x86 machine cause this test to always fail because it runs a build commands specific for `arm64`. 

```
Command Output (stderr):
--
<unknown>:0: error: could not find module 'Swift' for target 'arm64-apple-macos'; found: x86_64-apple-macos, at: .../build/Ninja-ReleaseAssert/swift-macosx-x86_64/lib/swift/macosx/Swift.swiftmodule
<unknown>:0: error: could not find module 'Swift' for target 'arm64-apple-macos'; found: x86_64-apple-macos, at: .../build/Ninja-ReleaseAssert/swift-macosx-x86_64/lib/swift/macosx/Swift.swiftmodule

--

********************
********************
Failed Tests (1):
  Swift(macosx-x86_64) :: ModuleInterface/build-alternative-interface-framework.swift


Testing Time: 0.55s
  Failed: 1
```

This updates the test to use `-target %target-cpu-...` limited require CPU arch arm64 and x86_64 on macOS and build `DummyModule` Input module for x86_64 as well. 
 

This was recently reported on the forums https://forums.swift.org/t/build-alternative-interface-framework-failed-while-running-tests/50499

### CODE REVIEW

**Comment by wongzigii** [comment]
Thanks!

**Comment by varungandhi-apple** [comment]
See discussion in https://bugs.swift.org/browse/SR-14762, this fix "works" because normally on arm64, you will end up building an arm64 stdlib, but it's not clear if it's the right fix in the first place. If you look at commit in which the test case was added (b6cd51353478), it seems to be testing the backup directory functionality and it seems like arm64 being hard-coded is not related to thing the test is trying to verify. cc @nkcsgexi

**Comment by LucianoPAlmeida** [comment]
> See discussion in https://bugs.swift.org/browse/SR-14762, this fix "works" because normally on arm64, you will end up building an arm64 stdlib, but it's not clear if it's the right fix in the first place. If you look at commit in which the test case was added ([b6cd513](https://github.com/apple/swift/commit/b6cd513534785e75b389ddac82ed5f46b831a0db)), it seems to be testing the backup directory functionality and it seems like arm64 being hard-coded is not related to thing the test is trying to verify. cc @nkcsgexi

It seems I've missed that, thanks for the explanation @varungandhi-apple :) 
Was also not sure about this, but since everything was hard coded for arm64 it made sense when I looked it up. 
I made change on the approach, to run on current target cpu and make sure that the `DummyModule` is built for x86_64 as well so it can run on both. It seems reasonable to me, but the same as before, not sure is the right fix as well, but let me know if makes sense =]

**Review by varungandhi-apple — APPROVED** [review]
This seems like a reasonable strategy.

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test MacOS Platform

**Comment by LucianoPAlmeida** [comment]
It seems that tests run in more targets CPUs than just arm64 and x86, so I'm not sure if we should add all in this case... trying to limit macOS(which I not sure only runs on that because I don't know if even then it targets simulator archs), what do you think @varungandhi-apple?

**Comment by varungandhi-apple** [comment]
Maybe we should go for `// REQUIRES: CPU=arm64 || CPU=x86_64` and leave a comment describing why that was added? That at least avoids the one-arch specific issue.

I'm all ears if you have any other ideas...

**Comment by LucianoPAlmeida** [comment]
> Maybe we should go for `// REQUIRES: CPU=arm64 || CPU=x86_64` and leave a comment describing why that was added? That at least avoids the one-arch specific issue.
> 
> I'm all ears if you have any other ideas...

I think it would be fine, different from only `// REQUIRES: CPU=arm64` people working on x86_64 Macs would be able to spot regressions locally as well :)
Just a question, `// REQUIRES: OS=macosx` works as well, so it will run in all currently supported archs for macOS which is only x86_64 and arm64, so question is if you think this is an option too?

**Comment by varungandhi-apple** [comment]
macOS can also run [`arm64e`](https://developer.apple.com/documentation/security/preparing_your_app_to_work_with_pointer_authentication) but that's not supported for 3rd parties right now. arm64e is not substantially different from arm64, so it's okay to leave it out here. I think it's preferable to have checks for both the CPU and the OS in place.

**Comment by LucianoPAlmeida** [comment]
> macOS can also run [`arm64e`](https://developer.apple.com/documentation/security/preparing_your_app_to_work_with_pointer_authentication) but that's not supported for 3rd parties right now. arm64e is not substantially different from arm64, so it's okay to leave it out here. I think it's preferable to have checks for both the CPU and the OS in place.

Ah make sense, just made the changes!
Thanks for the reference

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test

**Comment by LucianoPAlmeida** [comment]
Windows test failure its not related...

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test Windows Platform

**Comment by LucianoPAlmeida** [comment]
@varungandhi-apple There are any additional points or this is good to go?

**Comment by LucianoPAlmeida** [comment]
Added `DummyFramework` to build for arm64e as well so we restrict the test only for macOS, let me know if this makes sense :)

**Comment by varungandhi-apple** [comment]
Sorry, I missed your earlier comment. Yeah, I think this is also okay.

@swift-ci test

**Review by varungandhi-apple — APPROVED** [review]

**Comment by LucianoPAlmeida** [comment]
> Sorry, I missed your earlier comment. Yeah, I think this is also okay.

No worries @varungandhi-apple, thanks for the review :)

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test MacOS Platform

**Pull request merged**
