### PR TITLE
[libSyntax] Resolve a memory leak leaking the syntax tree

### PR DESCRIPTION
**Pull request by ahoppen**
This resolves a memory leak that occurred if `RawSyntax` nodes are allocated without an arena using `operator new`. A `ParserUnit` would never release its `ASTContext` which in turn retains the `SourceFile` and thus the syntax tree. Deleting the `ASTContext` resolves this leak.

We need to then retain `RawSyntax` nodes from `RawSyntaxCacheNode` so they are not freed while still being referenced.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Review by nkcsgexi — APPROVED** [review]
Good catch!

**Comment by aschwaighofer** [comment]
Looks like this might be causing failures on the ASAN bots:

https://ci.swift.org/view/Dashboard/job/oss-swift-incremental-ASAN-RA-osx/2244/testReport/junit/Swift(macosx-x86_64)/SwiftSyntax/VisitorTest_swift/

**Comment by ahoppen** [comment]
I'm investigating what the issue is.

**Comment by ahoppen** [comment]
I'm reverting the code that caused this issue for now in #18726.

**Pull request merged**
