### PR TITLE
An additional benchmark for KeyPath read performance. 

### PR DESCRIPTION
**Pull request by fibrechannelscsi**
This adds one additional benchmark where a read is performed on a KeyPath whose root is a reference type. Subsequent elements encountered during a project-read operation are pure struct types.

The goal is to highlight an upcoming performance optimization where, during a read or write operation, we project through non-pure-struct types first, and then use a pre-computed offset to jump to the final value once we encounter a stretch of trivially-typed memory only. In essence, if we have the following nested structure (with S and C referring to struct and non-struct types, respectively):
C<sub>1</sub> -> C<sub>2</sub> -> ... -> C<sub>m</sub> -> S<sub>1</sub> -> S<sub>2</sub> -> ..., -> S<sub>n</sub>
we project normally from C<sub>1</sub> to C<sub>m</sub>, then as soon as we get to S<sub>1</sub>, we use the pre-computed offset to jump to S<sub>n</sub>.

The upcoming optimization will not jump via an offset through intermediate stretches of trivially-typed memory. Namely, if we have the following situation:
C<sub>1</sub> -> C<sub>2</sub> -> ... -> C<sub>m</sub> -> S<sub>1</sub> -> S<sub>2</sub> -> ..., -> S<sub>n</sub> -> C<sub>m+1</sub> -> C<sub>m+2</sub> -> ... -> C<sub>m+x</sub> -> S<sub>n+1</sub> -> S<sub>n+2</sub> -> ..., -> S<sub>n+y</sub>
then only one offset will be involved, and the jump will only be performed from S<sub>n+1</sub> to S<sub>n+y</sub>.

Relates to:
https://github.com/apple/swift/pull/60758

### CODE REVIEW

**Comment by BradLarson** [comment]
@swift-ci please benchmark

**Comment by BradLarson** [comment]
@swift-ci please benchmark

**Comment by BradLarson** [comment]
@swift-ci please benchmark

**Review by eeckstein — APPROVED** [review]
lgtm

**Comment by BradLarson** [comment]
@swift-ci please test

**Pull request merged**
