### PR TITLE
Promote _Concurrency and StringProcessing to core subset of the stdlib

### PR DESCRIPTION
**Pull request by edymtt**
This is needed to support Apple internal configurations.

Addresses rdar://125909114

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci please test

**Comment by edymtt** [comment]
@swift-ci please build toolchain

**Comment by edymtt** [comment]
@swift-ci please test WebAssembly

**Review by compnerd — APPROVED** [review]
We really should consider dropping the `EXPERIMENTAL` in the options.

**Comment by stephentyrone** [comment]
Yeah, let's go ahead and get rid of `EXPERIMENTAL` if it makes sense to do so here.

**Review by stephentyrone — APPROVED** [review]

**Comment by compnerd** [comment]
I'd say that a follow up change is better - that allows us to get this change in (possibly cherry-picked to release) while we fix the option naming and test it to ensure that nothing else is dependent on the option name (e.g. windows ci caches).

**Review by etcwilde — APPROVED** [review]

**Comment by edymtt** [comment]
@swift-ci please test Windows

**Comment by edymtt** [comment]
@swift-ci please build macOS toolchain

**Comment by edymtt** [comment]
@swift-ci please build toolchain macOS

**Pull request merged**
