### PR TITLE
[libSyntax] Minor cleanup in ParsedRawSyntaxNode

### PR DESCRIPTION
**Pull request by ahoppen**
This contains a number of minor improvements to ParsedRawSyntaxNode.
- Rearrange the methods to be logically grouped
- Remove `copyDeferred`, which isn’t needed anywhere
- Reset `Range` when calling `ParsedRawSyntaxNode::reset`

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test Linux

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Review by rintaro — APPROVED** [review]

**Pull request merged**
