### PR TITLE
[Stdlib] Add Missing Implementations of underestimatedCount

### PR DESCRIPTION
**Pull request by dennisvennink**
Fixes [SR-9570](https://bugs.swift.org/browse/SR-9570).

The following types, which, to my knowledge, are all `Sequence`s from the Standard Library, have been checked:

- `AnyBidirectionalCollection`
- `AnyCollection`
- `AnyIterator`
- `AnyRandomAccessCollection`
- `AnySequence`
- `Array`
- `ArraySlice`
- `ClosedRange`
- `CollectionOfOne`
- `ContiguousArray`
- `DefaultIndices`
- `Dictionary`
- `DropFirstSequence`
- `DropWhileSequence`
- `EmptyCollection`
- `EmptyCollection.Iterator`
- `EnumeratedSequence`
- `EnumeratedSequence.Iterator`
- `FlattenSequence`
- `FlattenSequence.Iterator`
- `IndexingIterator`
- `IteratorSequence`
- `JoinedSequence`
- `KeyValuePairs`
- `LazyDropWhileSequence`
- `LazyFilterSequence`
- `LazyMapSequence`
- `LazyPrefixWhileSequence`
- `LazySequence`
- `LazyFilterSequence.Iterator`
- `LazyPrefixWhileSequence.Iterator`
- `LazyMapSequence.Iterator`
- `PartialRangeFrom`
- `PrefixSequence`
- `Range`
- `Repeated`
- `ReversedCollection`
- `ReversedCollection.Iterator`
- `Set`
- `Slice`
- `StrideThrough`
- `StrideTo`
- `String`
- `String.UnicodeScalarView`
- `String.UTF16View`
- `String.UTF8View`
- `Substring`
- `Substring.UnicodeScalarView`
- `Substring.UTF16View`
- `Substring.UTF8View`
- `UnfoldSequence`
- `Unicode.Scalar.UTF16View`
- `UnsafeBufferPointer`
- `UnsafeMutableBufferPointer`
- `UnsafeMutableRawBufferPointer`
- `UnsafeRawBufferPointer`
- `UnsafeRawBufferPointer.Iterator`
- `Zip2Sequence`

Please test and review.

### CODE REVIEW

**Comment by dennisvennink** [comment]
@moiseev [mentioned](https://forums.swift.org/t/consistent-lazy-api/19501/2) that `Iterator`s shouldn't really have been conformed to `Sequence`. So the latter two commits should probably be removed.

Is there anything else that's holding the merge back?

**Comment by CodaFi** [comment]
@swift-ci please test

**Comment by CodaFi** [comment]
Really doubting the package manager failures are yours.  Let's try again

@swift-ci please smoke test

**Comment by CodaFi** [comment]
Ah, that's more like it.  Just make sure the ABI changes you've made to stdlib are benign and update that test if they are.

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
