### PR TITLE
[cxx-interop] [NFC] Rename MemberInline.IntBox -> LoadableIntWrapper.

### PR DESCRIPTION
**Pull request by zoecarver**
[Refs.](https://github.com/apple/swift/pull/32869#discussion_r456459153)

### CODE REVIEW

**Comment by zoecarver** [comment]
@swift-ci please test Windows Platform.

**Comment by zoecarver** [comment]
I'm going to go ahead and merge this PR tomorrow unless I hear otherwise.

**Review by MForster — APPROVED** [review]

**Comment by zoecarver** [comment]
@swift-ci please smoke test and merge

**Comment by zoecarver** [comment]
@swift-ci please smoke test

**Pull request merged**
