### PR TITLE
Method dispatch cleanup

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes <rdar://problem/35860361>, <https://bugs.swift.org/browse/SR-6534>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by MrMage** [comment]
Sorry for reviving this PR, but it appears that https://github.com/apple/swift/pull/13742/commits/45c6315a71d0296d16ddf5c4847103f14c8377f4 would fix a crash I'm seeing in the latest Swift 4.1 development snapshot (from both March 7th and March 20th):

```
Assertion failed: (!D->isDynamic()), function makeFinal, file /Users/buildnode/jenkins/workspace/oss-swift-4.1-package-osx/swift/lib/Sema/TypeCheckDecl.cpp, line 1253.
0  swift                    0x00000001080524c8 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 40
1  swift                    0x0000000108052bd6 SignalHandler(int) + 694
2  libsystem_platform.dylib 0x00007fffc6eeab3a _sigtramp + 26
3  swift                    0x0000000108ca7878 (anonymous namespace)::DarwinX86AsmBackend::getCompactUnwindRegNum(unsigned int) const::CU64BitRegs + 221170
4  libsystem_c.dylib        0x00007fffc6d6f420 abort + 129
5  libsystem_c.dylib        0x00007fffc6d36893 basename_r + 0
6  swift                    0x000000010590270d (anonymous namespace)::DeclChecker::visitFuncDecl(swift::FuncDecl*) + 7741
7  swift                    0x00000001058ec6e1 (anonymous namespace)::DeclChecker::visit(swift::Decl*) + 337
8  swift                    0x00000001058fda4b (anonymous namespace)::DeclChecker::visitClassDecl(swift::ClassDecl*) + 379
9  swift                    0x00000001058ec7ee (anonymous namespace)::DeclChecker::visit(swift::Decl*) + 606
10 swift                    0x00000001058ec584 swift::TypeChecker::typeCheckDecl(swift::Decl*, bool) + 100
11 swift                    0x000000010597d844 swift::performTypeChecking(swift::SourceFile&, swift::TopLevelContext&, swift::OptionSet<swift::TypeCheckingFlags, unsigned int>, unsigned int, unsigned int, unsigned int, unsigned int) + 1604
12 swift                    0x00000001055fd0c8 swift::CompilerInstance::parseAndCheckTypes(swift::CompilerInstance::ImplicitImports const&) + 936
13 swift                    0x00000001055fc7a8 swift::CompilerInstance::performSema() + 520
14 swift                    0x0000000104b06541 performCompile(swift::CompilerInstance&, swift::CompilerInvocation&, llvm::ArrayRef<char const*>, int&, swift::FrontendObserver*, swift::UnifiedStatsReporter*) + 1921
15 swift                    0x0000000104b04dd0 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 3376
16 swift                    0x0000000104ac4683 main + 3075
17 libdyld.dylib            0x00007fffc6cdb235 start + 1
```

That crash was not there with Xcode 9.2, but started occurring with Swift 4.1 nightlies. Would there be any chance of backporting this to Swift 4.1? (No idea how much else has changed, and how bad merge conflicts would be.)

**Comment by MrMage** [comment]
Never mind, I found the underlying culprit: Apparently, Swift 4.1 chokes on the `dynamic` (which admittedly, doesn't really make sense) in

    @objc static dynamic func test() { }

Removing `dynamic` avoids the crash. Attached a minimal reproduction case; not sure if this is worth filing on bugs.swift.org given that it should be fixed in the development branch already. (Let me know if you think otherwise.)

[Swift41DynamicCrashTest.zip](https://github.com/apple/swift/files/1833487/Swift41DynamicCrashTest.zip)

**Pull request merged**
