### PR TITLE
[5.5][Dependency Scanning] Cherry-pick dependency scanner changes required for Explicit Module Builds

### PR DESCRIPTION
**Pull request by artemcm**
https://github.com/apple/swift/pull/38684: [Dependency Scanning] include -sdk in Swift module building command
https://github.com/apple/swift/pull/38703: [Dependency Scanning] Have the scanner cache answer queries relevant to current search paths only.
https://github.com/apple/swift/pull/37723: [Dependency Scanning] Add ability for `-scan-dependencies` action to serialize and deserialize dependency scanner cache from a `.moddepcache` file. Using the serialization format added in https://github.com/apple/swift/pull/37585.
https://github.com/apple/swift/pull/37585: [Dependency Scanning] Add a binary serialization format for the Inter-Module Dependencies Cache
https://github.com/apple/swift/pull/38710: Frontend: remove -swift-module-file. NFC
https://github.com/apple/swift/pull/38761: [Dependency Scanning] Split the ModuleDependencyCache into two: current scan cache & global.

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Review by nkcsgexi — APPROVED** [review]
LGTM for the 5.5 branch

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Review by airspeedswift — APPROVED** [review]

**Comment by artemcm** [comment]
@swift-ci please test Windows platform

**Comment by artemcm** [comment]
@swift-ci please test Windows platform

**Pull request merged**
