### PR TITLE
Enable valid-parse checking with the new parser

### PR DESCRIPTION
**Pull request by DougGregor**
Ensure that any time the existing parser accepts a source file, the new parser produces a valid parse (no unexpected/missing nodes) for that same source file.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please clean test macOS

**Comment by DougGregor** [comment]
@swift-ci please smoke test macOS

**Comment by DougGregor** [comment]
@swift-ci please test macOS

**Comment by DougGregor** [comment]
@swift-ci please build toolchain

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by DougGregor** [comment]
https://github.com/apple/swift-syntax/pull/902

@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
Windows issue is unrelated.

**Comment by DougGregor** [comment]
@swift-ci please build toolchain

**Pull request merged**
