### PR TITLE
[5.2] Remove dependency on libatomic on Linux

### PR DESCRIPTION
**Pull request by drexin**
Due to some unfortunate interplay between clang and libstdc++, clang was
    not able to correctly identify to alignment of PoolRange and
    SideTableRefCountBits, causing it to emit library calls instead of
    inlining atomic operations. This was fixed by adding the appropriate
    alignment to those types. In addition to that the march for the Linux
    target was set to 'core2', which is the earliest architecture to support
    cx16, which is necessary for the atomic operations on PoolRange.

### CODE REVIEW

**Comment by drexin** [comment]
@swift-ci test

**Comment by drexin** [comment]
@swift-ci test windows

**Comment by drexin** [comment]
@swift-ci test windows

**Comment by drexin** [comment]
@swift-ci test

**Comment by drexin** [comment]
@swift-ci test

**Review by tkremenek — APPROVED** [review]

**Pull request merged**
