### PR TITLE
[wasm] test: fix actor_recursive_deinit.swift for WASI

### PR DESCRIPTION
**Pull request by kateinoigakukun**

### CODE REVIEW

**Comment by kateinoigakukun** [comment]
@swift-ci test WebAssembly

**Comment by kateinoigakukun** [comment]
@swift-ci smoke test

**Review by ktoso — APPROVED** [review]
Cool, thanks!

**Comment by kateinoigakukun** [comment]
@swift-ci test WebAssembly

**Comment by kateinoigakukun** [comment]
@swift-ci smoke test

**Pull request merged**
