### PR TITLE
Bump `swift-argument-parser` to 1.4.0

### PR DESCRIPTION
**Pull request by MaxDesiatov**
rdar://118081439

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
https://github.com/apple/swift-package-manager/pull/7450
https://github.com/apple/swift-driver/pull/1578
https://github.com/apple/sourcekit-lsp/pull/1172

@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
https://github.com/apple/swift-package-manager/pull/7450
https://github.com/apple/swift-driver/pull/1578
https://github.com/apple/sourcekit-lsp/pull/1172

@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
https://github.com/apple/swift-package-manager/pull/7450
https://github.com/apple/swift-driver/pull/1578
https://github.com/apple/sourcekit-lsp/pull/1172

@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
https://github.com/apple/swift-package-manager/pull/7450
https://github.com/apple/swift-driver/pull/1578
https://github.com/apple/sourcekit-lsp/pull/1172

@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
https://github.com/apple/swift-package-manager/pull/7450
https://github.com/apple/swift-driver/pull/1578
https://github.com/apple/sourcekit-lsp/pull/1172

@swift-ci smoke test

**Comment by bnbarham** [comment]
https://github.com/swiftlang/swift-package-manager/pull/7450
https://github.com/swiftlang/swift-driver/pull/1578
https://github.com/swiftlang/sourcekit-lsp/pull/1172

@swift-ci smoke test

**Comment by bnbarham** [comment]
https://github.com/swiftlang/swift-package-manager/pull/7450
https://github.com/swiftlang/swift-driver/pull/1578
https://github.com/swiftlang/sourcekit-lsp/pull/1172

@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
https://github.com/swiftlang/swift-package-manager/pull/7450
https://github.com/swiftlang/swift-driver/pull/1578
https://github.com/swiftlang/sourcekit-lsp/pull/1172

@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
https://github.com/swiftlang/swift-package-manager/pull/7450
https://github.com/swiftlang/swift-driver/pull/1578
https://github.com/swiftlang/sourcekit-lsp/pull/1172

@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
https://github.com/swiftlang/swift-package-manager/pull/7450
https://github.com/swiftlang/swift-driver/pull/1578
https://github.com/swiftlang/sourcekit-lsp/pull/1172

@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
https://github.com/swiftlang/swift-package-manager/pull/7450
https://github.com/swiftlang/swift-driver/pull/1578
https://github.com/swiftlang/sourcekit-lsp/pull/1172

@swift-ci build toolchain

**Comment by MaxDesiatov** [comment]
https://github.com/swiftlang/swift-package-manager/pull/7450
https://github.com/swiftlang/swift-driver/pull/1578
https://github.com/swiftlang/sourcekit-lsp/pull/1172

@swift-ci smoke test

**Pull request merged**
