### PR TITLE
[ownership] Change all passes except for Mandatory Inlining to use DeadEndBlocksAnalysis.

### PR DESCRIPTION
**Pull request by gottesmm**
I didn't change MandatoryInlining since from a comment there it seems that since
MandatoryInlining is a module pass still and we don't really manage invalidation
well there.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
I am running source compat to see if we trip the analysis verification.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test macOS platform

**Comment by gottesmm** [comment]
@swift-ci smoke test OS X platform

**Comment by gottesmm** [comment]
@swift-ci test OS X platform

**Review by atrick — APPROVED** [review]

**Pull request closed without merging**
