### PR TITLE
[Index] Apply RelationContainedBy role to references contained by VarDecl.

### PR DESCRIPTION
**Pull request by ileitch**
This reverts abf6a30ba0224c19a574c3f95d727f41e1551276 and includes a fix for the crash.

### CODE REVIEW

**Comment by ileitch** [comment]
@bnbarham PTAL

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
@swift-ci please test source compatibility

**Comment by bnbarham** [comment]
Thanks @ileitch! I've started the source compatibility tests to double check :)

**Comment by ileitch** [comment]
All green ✅. Squashed the bug fix commit.

**Comment by bnbarham** [comment]
Woo 💃. Thanks again.

Runs were:
  https://ci.swift.org/view/Pull%20Request/job/swift-PR-source-compat-suite/5679/
  https://ci.swift.org/view/Pull%20Request/job/swift-PR-source-compat-suite-debug/3941/

Running smoke test so we can merge.

**Comment by bnbarham** [comment]
@swift-ci please smoke test

**Comment by bnbarham** [comment]
Thanks @ileitch!

**Pull request merged**
