### PR TITLE
Add presets for llbuild smoke tests and add testing of sourcekit-lsp

### PR DESCRIPTION
**Pull request by benlangmuir**
Adds presets for the llbuild smoke test jobs, and adds testing of sourcekit-lsp to prevent downstream CI failures.

Based on https://forums.swift.org/t/pr-test-presets-for-llbuild/28669/

### CODE REVIEW

**Comment by benlangmuir** [comment]
@swift-ci please smoke test

**Comment by benlangmuir** [comment]
preset=buildbot_llbuild_linux_platform,tools=RA,stdlib=RA
@swift-ci please test with preset Linux

**Comment by benlangmuir** [comment]
Note: I verified SwiftPM presets have no changes at all.  IndexStore-DB and SourceKit-LSP presets just have removal of duplication.  The only presets that are functionally changed are llbuild's.

**Comment by benlangmuir** [comment]
If you're reviewing this, it's worth looking at the commits separately:
* First, we add llbuild presets that are almost identical to the existing bot configuration
* Second, we refactor the swiftpm+sourcekit-lsp presets, which is NFC
* Third, we use the newly factored presets to make llbuild test sourcekit-lsp

**Comment by benlangmuir** [comment]
@swift-ci please smoke test macOS

**Review by dmbryson — APPROVED** [review]

**Pull request merged**
