### PR TITLE
[ownership] Accept unconditional_checked_cast_addr, treating it like a write.

### PR DESCRIPTION
**Pull request by gottesmm**
Just missed this on my first pass through.

rdar://62609950

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci test windows platform

**Comment by gottesmm** [comment]
@compnerd this is failing due to a problem on the windows infrastructure.

S:\jenkins\workspace\swift-PR-windows\llvm\lib\Analysis\PhiValues.cpp(228): fatal error C1069: cannot read compiler command line

Merging!

**Comment by compnerd** [comment]
You could have just rerun the CI ;)

**Comment by gottesmm** [comment]
@compnerd I think I did. It failed twice.

**Comment by gottesmm** [comment]
But maybe my memory is wrong.

**Pull request merged**
