### PR TITLE
[TypeChecker] SE-0324: Extend Swift -> C pointer conversions to `inout`

### PR DESCRIPTION
**Pull request by xedin**
Fixes an oversight where `inout` -> C pointer conversion wasn't covered
by implementation of new pointer conversion semantics proposed by SE-0324.

Resolves: rdar://92583588

### CODE REVIEW

**Review by hborla — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test source compatibility debug

**Review by atrick — APPROVED** [review]
Thank you Pavel!

I guess for completeness the tests could also add:

```
void const_opt_void_ptr_func(const void * _Nullable buffer);

```

And could call

```
const_int_${Size}_ptr_func(&x${Size}) // OK
const_uint_${Size}_ptr_func(&x${Size}) // OK
const_opt_int_${Size}_ptr_func(&x${Size}) // OK
const_opt_uint_${Size}_ptr_func(&x${Size}) // OK
```

**Comment by xedin** [comment]
Done!

**Comment by xedin** [comment]
@swift-ci please smoke test

**Pull request merged**
