### PR TITLE
[DO NOT MERGE] dummy PR for swift-stress-tester PR tests

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
Please test with following pull request:
apple/swift-stress-tester#43

@swift-ci Please test

**Comment by nkcsgexi** [comment]
https://github.com/apple/swift-stress-tester/pull/44

@swift-ci Please smoke test

**Comment by nkcsgexi** [comment]
@shahmishal According to the log, the PR testing seems to be not covering swift-stress-tester.

**Comment by shahmishal** [comment]
@nkcsgexi, to trigger stress test you will need to specify stress tester. 

https://github.com/apple/swift/blob/master/docs/ContinuousIntegration.md#sourcekit-stress-testing

**Comment by nkcsgexi** [comment]
@swift-ci Please Sourcekit Stress test

**Comment by nkcsgexi** [comment]
apple/swift-stress-tester#44

@swift-ci Please Sourcekit Stress test

**Pull request closed without merging**
