### PR TITLE
Frontend: re-serialise static library status

### LINKED ISSUE #77756: swiftinterface compilation does not re-serialise static library builds
### Description

It seems that I recently started getting link errors related to `swiftCxx.lib` and `swiftCxxStdlib.lib` such as:

Windows (x64/arm64):
```
lld-link: error: could not open 'swiftCxx.lib': no such file or directory
lld-link: error: could not open 'swiftCxxStdlib.lib': no such file or directory
```
```
LINK : fatal error LNK1104: cannot open file 'swiftCxx.lib'
```
where I presume it should probably need to load instead `libswiftCxx.lib` and `libswiftCxxStdlib.lib`  which actually exist in the toolchain directory, as opposed to `swiftCxx.lib` and `swiftCxxStdlib.lib` which don't exist there.

Locally reverting https://github.com/swiftlang/swift/pull/77559 (and https://github.com/swiftlang/swift-installer-scripts/pull/344) seems to make this error go away.

### Reproduction

On a recent toolchain build in the main branch:

Windows
```
C:\Users\hiroshi\Test>cat Test.swift
import CXXModule

C:\Users\hiroshi\Test>cat Inputs\header.h
#ifndef HEADER_H
#define HEADER_H

#endif // HEADER_H

C:\Users\hiroshi\Test>cat Inputs\module.modulemap
module CXXModule {
  header "header.h"
  requires cplusplus
}

C:\Users\hiroshi\Test>swiftc Test.swift -cxx-interoperability-mode=default -o Test.exe -I C:\Users\hiroshi\SwiftCxxTest\Inputs
error: link command failed with exit code 1104 (use -v to see invocation)
LINK : fatal error LNK1104: cannot open file 'swiftCxx.lib'
clang: error: linker command failed with exit code 1104 (use -v to see invocation)
```

### Expected behavior

Successful linking, no link errors.

### Environment

With a recent main-branch toolchain build on windows.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by compnerd**
When compiling the swiftmodule from the textual swift interface, ensure that we re-serialise the static or dynamic nature of the module. This is required for proper code generation where the static and dynamic linking is material to symbolic references. This also opens the possibility of optimizations on other platforms via internalisation of the symbols.

Fixes: #77756

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Review by hjyamauchi — APPROVED** [review]

**Review by egorzhdan — APPROVED** [review]
LGTM, thank you!

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Windows platfom

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Pull request merged**
