### PR TITLE
[Serialization] Deserialize protocol requirement signatures lazily

### PR DESCRIPTION
**Pull request by jrose-apple**
Also, stop serializing protocols' generic environments. Always good to do less work, and it's a stepping stone towards recovering from trying to deserialize a protocol with missing requirements.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by jrose-apple** [comment]
@swift-ci Please test compiler performance

**Comment by jrose-apple** [comment]
One thing I want the perf test to tell us is whether this is ever actually lazy in practice. It's possible that almost all the time we need a protocol, we immediately need its requirement signature anyway.

**Comment by jrose-apple** [comment]
I should write a test too to show that some uses of protocols are indeed lazy.

**Review by slavapestov — APPROVED** [review]

**Comment by jrose-apple** [comment]
@swift-ci Please test compiler performance

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test Linux

**Comment by jrose-apple** [comment]
macOS build timed out in the LLDB suite. Concerning?

**Comment by jrose-apple** [comment]
@swift-ci Please test macOS

**Comment by jrose-apple** [comment]
# Summary for master full

**Unexpected test results, excluded stats for ProcedureKit, Tagged, Wordy, SwifterSwift, Deferred**

**Regressions found (see below)**

- [Debug-batch](#debug-batch-60d116390427c2a5)
    - [debug-batch brief](#debug-batch-brief-60d116390427c2a5)
    - [debug-batch detailed](#debug-batch-detailed-60d116390427c2a5)
- [Release](#release-60d116390427c2a5)
    - [release brief](#release-brief-60d116390427c2a5)
    - [release detailed](#release-detailed-60d116390427c2a5)



<a name="debug-batch-60d116390427c2a5">

# Debug-batch

<a name="debug-batch-brief-60d116390427c2a5">

## debug-batch brief
<details>
<summary>Regressed (0)</summary>

name | old | new | delta | delta_pct
---: | ---: | ---: | ---: | ---:
</details>
<details>
<summary>Improved (1)</summary>

name | old | new | delta | delta_pct
---: | ---: | ---: | ---: | ---:
Frontend.NumInstructionsExecuted | 30,238,758,535,495 | 29,850,679,558,989 | -388,078,976,506 | -1.28% :white_check_mark:
</details>
<details>
<summary>Unchanged (delta < 1.0% or delta < 100.0ms) (2)</summary>

name | old | new | delta | delta_pct
---: | ---: | ---: | ---: | ---:
LLVM.NumLLVMBytesOutput | 1,159,863,670 | 1,159,867,920 | 4,250 | 0.0%
time.swift-driver.wall | 2717.1s | 2726.3s | 9.2s | 0.34%
</details>

<a name="debug-batch-detailed-60d116390427c2a5">

## debug-batch detailed
<details>
<summary>Regressed (2)</summary>

name | old | new | delta | delta_pct
---: | ---: | ---: | ---: | ---:
Driver.NumDriverPipePolls | 99,308 | 100,314 | 1,006 | 1.01% :no_entry:
Sema.RequirementSignatureRequest | 70,501 | 503,111 | 432,610 | 613.62% :no_entry:
</details>
<details>
<summary>Improved (14)</summary>

name | old | new | delta | delta_pct
---: | ---: | ---: | ---: | ---:
AST.NumASTBytesAllocated | 70,803,597,646 | 69,177,046,419 | -1,626,551,227 | -2.3% :white_check_mark:
Frontend.NumInstructionsExecuted | 30,238,758,535,495 | 29,850,679,558,989 | -388,078,976,506 | -1.28% :white_check_mark:
Sema.IsFinalRequest | 3,604,528 | 3,564,028 | -40,500 | -1.12% :white_check_mark:
Sema.NumConformancesDeserialized | 6,414,578 | 6,321,507 | -93,071 | -1.45% :white_check_mark:
Sema.NumDeclsDeserialized | 48,611,723 | 47,431,372 | -1,180,351 | -2.43% :white_check_mark:
Sema.NumGenericSignatureBuilders | 1,157,746 | 1,139,340 | -18,406 | -1.59% :white_check_mark:
Sema.NumLazyGenericEnvironments | 9,784,055 | 8,871,199 | -912,856 | -9.33% :white_check_mark:
Sema.NumLazyGenericEnvironmentsLoaded | 222,509 | 217,208 | -5,301 | -2.38% :white_check_mark:
Sema.NumLazyIterableDeclContexts | 6,424,118 | 6,229,587 | -194,531 | -3.03% :white_check_mark:
Sema.NumTypesDeserialized | 15,933,866 | 14,370,547 | -1,563,319 | -9.81% :white_check_mark:
Sema.NumUnloadedLazyIterableDeclContexts | 4,184,846 | 4,027,701 | -157,145 | -3.76% :white_check_mark:
Sema.OverriddenDeclsRequest | 7,771,744 | 7,521,614 | -250,130 | -3.22% :white_check_mark:
Sema.SelfBoundsFromWhereClauseRequest | 5,116,320 | 5,064,656 | -51,664 | -1.01% :white_check_mark:
Sema.USRGenerationRequest | 12,691,929 | 12,189,860 | -502,069 | -3.96% :white_check_mark:
</details>
<details>
<summary>Unchanged (delta < 1.0% or delta < 100.0ms) (99)</summary>

name | old | new | delta | delta_pct
---: | ---: | ---: | ---: | ---:
AST.NumDecls | 93,543 | 93,543 | 0 | 0.0%
AST.NumDependencies | 216,530 | 216,536 | 6 | 0.0%
AST.NumInfixOperators | 34,812 | 34,812 | 0 | 0.0%
AST.NumLinkLibraries | 0 | 0 | 0 | 0.0%
AST.NumLoadedModules | 262,351 | 262,351 | 0 | 0.0%
AST.NumLocalTypeDecls | 123 | 123 | 0 | 0.0%
AST.NumObjCMethods | 15,290 | 15,290 | 0 | 0.0%
AST.NumPostfixOperators | 18 | 18 | 0 | 0.0%
AST.NumPrecedenceGroups | 17,193 | 17,193 | 0 | 0.0%
AST.NumPrefixOperators | 60 | 60 | 0 | 0.0%
AST.NumReferencedDynamicNames | 122 | 122 | 0 | 0.0%
AST.NumReferencedMemberNames | 4,071,570 | 4,071,570 | 0 | 0.0%
AST.NumReferencedTopLevelNames | 315,682 | 315,682 | 0 | 0.0%
AST.NumSourceBuffers | 399,348 | 399,348 | 0 | 0.0%
AST.NumSourceLines | 3,118,982 | 3,118,982 | 0 | 0.0%
AST.NumSourceLinesPerSecond | 2,449,780 | 2,444,402 | -5,378 | -0.22%
AST.NumStoredPropertiesQueries | 9,230,775 | 9,230,709 | -66 | -0.0%
AST.NumTotalClangImportedEntities | 4,384,726 | 4,366,625 | -18,101 | -0.41%
Driver.ChildrenMaxRSS | 138,669,678,592 | 138,316,761,088 | -352,917,504 | -0.25%
Driver.DriverDepCascadingDynamic | 0 | 0 | 0 | 0.0%
Driver.DriverDepCascadingExternal | 0 | 0 | 0 | 0.0%
Driver.DriverDepCascadingMember | 0 | 0 | 0 | 0.0%
Driver.DriverDepCascadingNominal | 0 | 0 | 0 | 0.0%
Driver.DriverDepCascadingTopLevel | 0 | 0 | 0 | 0.0%
Driver.DriverDepDynamic | 0 | 0 | 0 | 0.0%
Driver.DriverDepExternal | 0 | 0 | 0 | 0.0%
Driver.DriverDepMember | 0 | 0 | 0 | 0.0%
Driver.DriverDepNominal | 0 | 0 | 0 | 0.0%
Driver.DriverDepTopLevel | 0 | 0 | 0 | 0.0%
Driver.NumDriverJobsRun | 19,038 | 19,038 | 0 | 0.0%
Driver.NumDriverJobsSkipped | 0 | 0 | 0 | 0.0%
Driver.NumDriverPipeReads | 98,737 | 99,207 | 470 | 0.48%
Driver.NumProcessFailures | 0 | 0 | 0 | 0.0%
Frontend.MaxMallocUsage | 870,503,063,936 | 863,012,146,968 | -7,490,916,968 | -0.86%
Frontend.NumProcessFailures | 0 | 0 | 0 | 0.0%
IRModule.NumIRAliases | 120,775 | 120,775 | 0 | 0.0%
IRModule.NumIRBasicBlocks | 4,612,399 | 4,612,399 | 0 | 0.0%
IRModule.NumIRComdatSymbols | 0 | 0 | 0 | 0.0%
IRModule.NumIRFunctions | 2,144,169 | 2,144,169 | 0 | 0.0%
IRModule.NumIRGlobals | 2,243,366 | 2,243,366 | 0 | 0.0%
IRModule.NumIRIFuncs | 0 | 0 | 0 | 0.0%
IRModule.NumIRInsts | 60,944,740 | 60,944,740 | 0 | 0.0%
IRModule.NumIRNamedMetaData | 92,490 | 92,490 | 0 | 0.0%
IRModule.NumIRValueSymbols | 3,922,915 | 3,922,915 | 0 | 0.0%
LLVM.NumLLVMBytesOutput | 1,159,863,670 | 1,159,867,920 | 4,250 | 0.0%
Parse.NumFunctionsParsed | 171,430 | 171,430 | 0 | 0.0%
Parse.NumIterableDeclContextParsed | 1,174,574 | 1,174,574 | 0 | 0.0%
SILModule.NumSILGenDefaultWitnessTables | 0 | 0 | 0 | 0.0%
SILModule.NumSILGenFunctions | 1,081,632 | 1,081,632 | 0 | 0.0%
SILModule.NumSILGenGlobalVariables | 36,840 | 36,840 | 0 | 0.0%
SILModule.NumSILGenVtables | 12,417 | 12,417 | 0 | 0.0%
SILModule.NumSILGenWitnessTables | 46,027 | 46,027 | 0 | 0.0%
SILModule.NumSILOptDefaultWitnessTables | 0 | 0 | 0 | 0.0%
SILModule.NumSILOptFunctions | 1,535,400 | 1,535,400 | 0 | 0.0%
SILModule.NumSILOptGlobalVariables | 37,716 | 37,716 | 0 | 0.0%
SILModule.NumSILOptVtables | 20,593 | 20,593 | 0 | 0.0%
SILModule.NumSILOptWitnessTables | 101,019 | 101,019 | 0 | 0.0%
Sema.AccessLevelRequest | 2,754,452 | 2,747,525 | -6,927 | -0.25%
Sema.AttachedFunctionBuilderRequest | 0 | 0 | 0 | 0.0%
Sema.AttachedPropertyWrapperTypeRequest | 325,238 | 325,238 | 0 | 0.0%
Sema.AttachedPropertyWrappersRequest | 1,327,704 | 1,327,704 | 0 | 0.0%
Sema.CustomAttrNominalRequest | 0 | 0 | 0 | 0.0%
Sema.DefaultAndMaxAccessLevelRequest | 58,834 | 58,838 | 4 | 0.01%
Sema.DefaultDefinitionTypeRequest | 5,525 | 5,525 | 0 | 0.0%
Sema.DefaultTypeRequest | 323,597 | 323,597 | 0 | 0.0%
Sema.EnumRawTypeRequest | 17,342 | 17,342 | 0 | 0.0%
Sema.ExtendedNominalRequest | 3,481,073 | 3,461,217 | -19,856 | -0.57%
Sema.FunctionBuilderTypeRequest | 0 | 0 | 0 | 0.0%
Sema.InheritedDeclsReferencedRequest | 3,944,000 | 3,909,916 | -34,084 | -0.86%
Sema.InheritedTypeRequest | 237,275 | 235,144 | -2,131 | -0.9%
Sema.IsDynamicRequest | 1,979,673 | 1,979,673 | 0 | 0.0%
Sema.IsGetterMutatingRequest | 401,137 | 401,137 | 0 | 0.0%
Sema.IsObjCRequest | 1,804,549 | 1,802,217 | -2,332 | -0.13%
Sema.IsSetterMutatingRequest | 279,242 | 279,242 | 0 | 0.0%
Sema.LazyStoragePropertyRequest | 2,418 | 2,418 | 0 | 0.0%
Sema.MangleLocalTypeDeclRequest | 246 | 246 | 0 | 0.0%
Sema.NamedLazyMemberLoadFailureCount | 22,096 | 22,040 | -56 | -0.25%
Sema.NamedLazyMemberLoadSuccessCount | 19,819,103 | 19,849,036 | 29,933 | 0.15%
Sema.NominalTypeLookupDirectCount | 25,146,135 | 25,037,618 | -108,517 | -0.43%
Sema.NumConstraintScopes | 17,953,007 | 17,941,060 | -11,947 | -0.07%
Sema.NumConstraintsConsideredForEdgeContraction | 52,838,335 | 52,835,720 | -2,615 | -0.0%
Sema.NumDeclsFinalized | 1,732,370 | 1,732,370 | 0 | 0.0%
Sema.NumDeclsTypechecked | 889,394 | 889,394 | 0 | 0.0%
Sema.NumDeclsValidated | 2,308,548 | 2,308,548 | 0 | 0.0%
Sema.NumFunctionsTypechecked | 198,299 | 198,299 | 0 | 0.0%
Sema.NumLeafScopes | 11,558,900 | 11,548,830 | -10,070 | -0.09%
Sema.NumTypesValidated | 1,728,522 | 1,728,522 | 0 | 0.0%
Sema.OpaqueReadOwnershipRequest | 423,239 | 423,239 | 0 | 0.0%
Sema.PropertyWrapperBackingPropertyInfoRequest | 322,765 | 322,765 | 0 | 0.0%
Sema.PropertyWrapperBackingPropertyTypeRequest | 325,238 | 325,238 | 0 | 0.0%
Sema.PropertyWrapperTypeInfoRequest | 0 | 0 | 0 | 0.0%
Sema.RequirementRequest | 67,193 | 67,189 | -4 | -0.01%
Sema.SelfAccessKindRequest | 4,334,315 | 4,330,891 | -3,424 | -0.08%
Sema.SetterAccessLevelRequest | 156,459 | 156,459 | 0 | 0.0%
Sema.StructuralTypeRequest | 0 | 0 | 0 | 0.0%
Sema.SuperclassDeclRequest | 334,832 | 333,936 | -896 | -0.27%
Sema.SuperclassTypeRequest | 40,164 | 40,164 | 0 | 0.0%
Sema.TypeDeclsFromWhereClauseRequest | 31,565 | 31,569 | 4 | 0.01%
Sema.UnderlyingTypeDeclsReferencedRequest | 168,818 | 167,637 | -1,181 | -0.7%
</details>

<a name="release-60d116390427c2a5">

# Release

<a name="release-brief-60d116390427c2a5">

## release brief
<details>
<summary>Regressed (0)</summary>

name | old | new | delta | delta_pct
---: | ---: | ---: | ---: | ---:
</details>
<details>
<summary>Improved (0)</summary>

name | old | new | delta | delta_pct
---: | ---: | ---: | ---: | ---:
</details>
<details>
<summary>Unchanged (delta < 1.0% or delta < 100.0ms) (3)</summary>

name | old | new | delta | delta_pct
---: | ---: | ---: | ---: | ---:
Frontend.NumInstructionsExecuted | 30,737,772,647,005 | 30,757,563,893,156 | 19,791,246,151 | 0.06%
LLVM.NumLLVMBytesOutput | 993,457,920 | 993,462,564 | 4,644 | 0.0%
time.swift-driver.wall | 5176.2s | 5181.7s | 5.5s | 0.11%
</details>

<a name="release-detailed-60d116390427c2a5">

## release detailed
<details>
<summary>Regressed (0)</summary>

name | old | new | delta | delta_pct
---: | ---: | ---: | ---: | ---:
</details>
<details>
<summary>Improved (2)</summary>

name | old | new | delta | delta_pct
---: | ---: | ---: | ---: | ---:
Sema.NumLazyGenericEnvironments | 1,264,569 | 1,200,553 | -64,016 | -5.06% :white_check_mark:
Sema.NumTypesDeserialized | 3,259,721 | 3,173,085 | -86,636 | -2.66% :white_check_mark:
</details>
<details>
<summary>Unchanged (delta < 1.0% or delta < 100.0ms) (19)</summary>

name | old | new | delta | delta_pct
---: | ---: | ---: | ---: | ---:
AST.NumLoadedModules | 17,619 | 17,619 | 0 | 0.0%
AST.NumTotalClangImportedEntities | 778,391 | 778,391 | 0 | 0.0%
IRModule.NumIRBasicBlocks | 3,940,364 | 3,940,364 | 0 | 0.0%
IRModule.NumIRFunctions | 1,812,431 | 1,812,431 | 0 | 0.0%
IRModule.NumIRGlobals | 1,989,687 | 1,989,687 | 0 | 0.0%
IRModule.NumIRInsts | 36,182,589 | 36,182,589 | 0 | 0.0%
IRModule.NumIRValueSymbols | 3,533,575 | 3,533,575 | 0 | 0.0%
LLVM.NumLLVMBytesOutput | 993,457,920 | 993,462,564 | 4,644 | 0.0%
SILModule.NumSILGenFunctions | 748,037 | 748,037 | 0 | 0.0%
SILModule.NumSILOptFunctions | 1,001,862 | 1,001,862 | 0 | 0.0%
Sema.NumConformancesDeserialized | 2,288,924 | 2,288,924 | 0 | 0.0%
Sema.NumConstraintScopes | 17,605,053 | 17,605,053 | 0 | 0.0%
Sema.NumDeclsDeserialized | 6,169,509 | 6,159,243 | -10,266 | -0.17%
Sema.NumDeclsValidated | 1,197,884 | 1,197,884 | 0 | 0.0%
Sema.NumFunctionsTypechecked | 201,866 | 201,866 | 0 | 0.0%
Sema.NumGenericSignatureBuilders | 209,143 | 207,900 | -1,243 | -0.59%
Sema.NumLazyGenericEnvironmentsLoaded | 22,181 | 22,075 | -106 | -0.48%
Sema.NumLazyIterableDeclContexts | 765,847 | 763,650 | -2,197 | -0.29%
Sema.NumTypesValidated | 741,424 | 741,424 | 0 | 0.0%
</details>

**Comment by jrose-apple** [comment]
Much better!

**Pull request merged**
