### PR TITLE
 swift-module-digester: always canonicalize super class types.

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by slavapestov** [comment]
Do you canonicalize all types, or just superclasses?

**Comment by nkcsgexi** [comment]
We canonicalize all types when checking ABI stability. This patch is to canonicalize super class type names disregarding of checking ABI or source compatibility.

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by slavapestov** [comment]
@nkcsgexi Why do you need to canonicalize superclass types but not other types when checking API stability?

**Comment by nkcsgexi** [comment]
Because synthesizing type alias of the same name with an old type is an api-notes' way to maintain source-compatibility for many frameworks.

**Comment by slavapestov** [comment]
@nkcsgexi I see, so its specific to imported modules? Maybe you should conditionalize the check on that hten.

**Comment by nkcsgexi** [comment]
yeah, i think it's specific to imported module. Since we'll deploy ABI checker for Swift modules with all types canonicalized, i'm not sure it's useful to introduce another flag.

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Pull request merged**
