### PR TITLE
[Syntax] Consolidate 'TupleElement' and 'FunctionCallArgument' kinds

### PR DESCRIPTION
**Pull request by rintaro**
into `TupleExprElement`. They had exact the same layout.

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please Python lint

**Review by nkcsgexi — APPROVED** [review]

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by rintaro** [comment]
https://github.com/apple/swift-syntax/pull/150
@swift-ci Please test

**Comment by rintaro** [comment]
https://github.com/apple/swift-syntax/pull/150
@swift-ci Please test

**Comment by rintaro** [comment]
https://github.com/apple/swift-syntax/pull/150
@swift-ci Please test

**Comment by rintaro** [comment]
https://github.com/apple/swift-syntax/pull/152
@swift-ci Please test

**Pull request merged**
