### PR TITLE
[5.9] Introduce `-unavailable-decl-optimization=stub`

### PR DESCRIPTION
**Pull request by tshortli**
Cherry pick of https://github.com/apple/swift/pull/65557

Implement a new `-unavailable-decl-optimization` mode that replaces the bodies of unavailable functions with calls to a standard library function that invokes `fatalError`. Unlike `-unavailable-decl-optimization=complete`, this compilation mode is designed to improve the code size of unavailable code while also preserving ABI compatibility. This is important since there are existing compiled binaries that link the symbols for unavailable functions even though those symbols should be provably unreachable.

This optimization is implemented in SILGen by inserting a call to a new standard library function `_diagnoseUnavailableCodeReached()` in the prologue of each unavailable function. The existing dead code elimination optimization pass then determines that the remainder of the function body is unreachable and removes all other code, leaving the body of the function as a single call to a no-return function.

There are several follow up changes that can be made to maximize the effectiveness of this optimization:
- Some functions that could benefit from this optimization are generated during IRGen, like value witnesses functions. The same technique will need to be reproduced for IRGen to reduce code size further.
- The generated machine code for the stubbed functions is not optimal. It currently includes stack pointer management before calling `_diagnoseUnavailableCodeReached()` and sometimes also includes a `brk` instruction after the call. Some work to reduce the machine code for these stubs down to the minimal necessary instructions (probably just a single branch?) may be warranted.

Resolves rdar://107388493

### CODE REVIEW

**Comment by tshortli** [comment]
@swift-ci please test

**Comment by tshortli** [comment]
@swift-ci please test

**Comment by tshortli** [comment]
@swift-ci please test

**Comment by tshortli** [comment]
@swift-ci please test

**Comment by tshortli** [comment]
@swift-ci please test

**Review by nkcsgexi — APPROVED** [review]

**Comment by nkcsgexi** [comment]
This is a mode behind an opt-in flag so it should be safe to be landed on 5.9

**Comment by tshortli** [comment]
@swift-ci please test

**Comment by tshortli** [comment]
@swift-ci please test

**Pull request merged**
