### PR TITLE
Fix input environment not being respected by swift_build_support.shell.run()

### PR DESCRIPTION
**Pull request by gwynne**
In `swift_build_support`'s `shell` module, the `run()` function was removing the passed-in environment from the keyword arguments dictionary, preventing it from being passed along to `subprocess.Popen()`.

This appears to only have affected `update_checkout`, and therein, the only usage of `run()` with non-default environment was in the `obtain_additional_swift_sources()` function. The effect was to ignore the attempt to set `GIT_TERMINAL_PROMPT=0` for the `git clone`, `git checkout`, and `git submodule` commands.

Hardly catastrophic, but it's nonetheless a little unpleasant that this went completely unnoticed since at least 2017. (Admittedly because it didn't really affect much of anything.)

(Note: Also had to fix the actual use site in `update_checkout` to pass a string rather than a number as the environment value - this has been broken since at least https://github.com/apple/swift/commit/8c721dee4c3b2de7b38b4b3c50602a1968b45564)

### CODE REVIEW

**Comment by gwynne** [comment]
@swift-ci please smoke test

**Review by compnerd — COMMENTED** [review]
@swift-ci please test

**Review by compnerd — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by Mrnamluxury** [comment]
> In `swift_build_support`'s `shell` module, the `run()` function was removing the passed-in environment from the keyword arguments dictionary, preventing it from being passed along to `subprocess.Popen()`.
> 
> 
> 
> This appears to only have affected `update_checkout`, and therein, the only usage of `run()` with non-default environment was in the `obtain_additional_swift_sources()` function. The effect was to ignore the attempt to set `GIT_TERMINAL_PROMPT=0` for the `git clone`, `git checkout`, and `git submodule` commands.
> 
> 
> 
> Hardly catastrophic, but it's nonetheless a little unpleasant that this went completely unnoticed since at least 2017. (Admittedly because it didn't really affect much of anything.)
> 
> 
> 
> (Note: Also had to fix the actual use site in `update_checkout` to pass a string rather than a number as the environment value - this has been broken since at least https://github.com/apple/swift/commit/8c721dee4c3b2de7b38b4b3c50602a1968b45564)

[]()]()

**Pull request merged**
