### PR TITLE
[Parse] Allow #if to guard switch case clauses

### PR DESCRIPTION
**Pull request by rintaro**
Resolves: [SR-4196](https://bugs.swift.org/browse/SR-4196),  [SR-2](https://bugs.swift.org/browse/SR-2)

evolution discussion: https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20170508/036568.html

~~**Depends on #9413**: Only the last commit is relevant to this PR.~~ merged

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
Can you add at least one execution test, so we can see that nothing down the pipeline gets tripped up by this?

**Comment by CodaFi** [comment]
@jrose-apple can we get #7955 merged before I review this.  It may require some rebasing but I can't tell because of the chain of dependencies here

**Comment by rintaro** [comment]
Rebased on master
@swift-ci  Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@CodaFi Could you review this?

**Review by CodaFi — APPROVED** [review]

**Comment by CodaFi** [comment]
One last thing before I merge this: Can you add something to the existing tests that uses nested configuration blocks?

**Comment by rintaro** [comment]
Added test case in executable test.
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@CodaFi Could you merge this?
Also, do you think it's possible to get this into 4.0 branch?

**Comment by CodaFi** [comment]
⛵️ 

You can cherry pick this to 4.0.  I will nominate internally.

**Comment by CodaFi** [comment]
Sorry to contradict myself so directly: If it were just this patch we would consider it, but because this feature depends on the earlier refactoring passes this is going to involve cherry-picking too much new code into 4.0 branch.

Sorry, but it's probably not a good idea right now to take this.

**Comment by rintaro** [comment]
@CodaFi Thanks for merging.
Yeah, agreed. I will wait for 4.1.

**Pull request merged**
