### PR TITLE
Enable ArrayPropertyOpt on OSSA

### PR DESCRIPTION
**Pull request by meg-gupta**
- Add tests with array semantic calls having @guaranteed self
- Support copy_value as self value 
- Support hoisting/copying self of array semantic calls in OSSA. This is common with #35380. And can be reviewed once in common for both PRs

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test source compatibility

**Comment by meg-gupta** [comment]
@swift-ci benchmark

**Review by atrick — COMMENTED** [review]
This relies on the same replaceAllUsesWithUndef fix as
https://github.com/apple/swift/pull/35380
But otherwise looks good.

**Review by atrick — APPROVED** [review]
LGTM

**Comment by meg-gupta** [comment]
@swift-ci test and merge

**Pull request merged**
