### PR TITLE
SILGen: Fix bridging of optional function types to AnyObject

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes <rdar://problem/35403187>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by shahmishal** [comment]
ci.swift.org is down for update, I will re-trigger this PR once update has been completed.

**Comment by shahmishal** [comment]
@swift-ci Please smoke test

**Comment by shahmishal** [comment]
@swift-ci Please smoke test

**Comment by rjmccall** [comment]
Yeah, that's what I had in mind, thanks!

**Pull request merged**
