### PR TITLE
Put the transformation checks on the return statement instead of to variables

### PR DESCRIPTION
**Pull request by ghost**
In OwnedToGuaranteedTransform, FunctionSignatureTransform::OwnedToGuaranteedAnalyze() calls OwnedToGuaranteedAnalyzeResults(), assigns the results to a variable, calls OwnedToGuaranteedAnalyzeParameters(), and assigns that to a variable, and then calls a boolean checking if ANY of those are true.

If the first function returned true, why would we have to call the other one. As a result, I put them on a single return statement conjoined by an OR operator.

### CODE REVIEW

**Comment by xwu** [comment]
This will cause a functional change if either of these function calls has side effects. A quick review of the functions suggest that they do have side effects and are always called on purpose.

**Comment by gottesmm** [comment]
I think this is fine. My only concern is if it violates 80 columns. If it does, can you just do an early if, return? I.e.:

```
if (!foo())
  return false;
return bar();
```

**Comment by gottesmm** [comment]
Actually, sorry, just read this. We need both to execute.

**Comment by gottesmm** [comment]
The reason why is we can optimize args or results. If either works, we should try to transform.

**Comment by AnthonyLatsis** [comment]
They do have side effects, but you can still make those bools `const` instead.

**Pull request closed without merging**
