### PR TITLE
[IRGen] Pass component generic sig when emitting key path component f…

### PR DESCRIPTION
**Pull request by drexin**
…or external property

rdar://101179225

When no generic environment was present, we passed nullptr, which is not correct when the property uses an external associated type, causing crashes in IRGen. In those cases, we have to pass the component generic sig instead.

### CODE REVIEW

**Comment by drexin** [comment]
@swift-ci smoke test windows

**Comment by drexin** [comment]
@swift-ci test

**Comment by drexin** [comment]
@swift-ci test macos

**Review by aschwaighofer — APPROVED** [review]
LGTM but maybe @jckarter wants to chime in

**Pull request merged**
