### PR TITLE
Update swift to build against cas-support

### PR DESCRIPTION
**Pull request by cachemeifyoucan**
Updata swift to build against CAS support

### CODE REVIEW

**Comment by cachemeifyoucan** [comment]
Please test with following pull request:
https://github.com/apple/llvm-project/pull/4850

@swift-ci Please test

**Comment by cachemeifyoucan** [comment]
@swift-ci Please test Windows platform

**Comment by cachemeifyoucan** [comment]
Please test with following pull request:
https://github.com/apple/llvm-project/pull/4850

@swift-ci Please test Windows platform

**Comment by cachemeifyoucan** [comment]
Please test with following pull request:
https://github.com/apple/llvm-project/pull/4850

@swift-ci Please test Windows platform

**Comment by cachemeifyoucan** [comment]
Please test with following pull request:
https://github.com/apple/llvm-project/pull/4850

@swift-ci Please test

**Review by benlangmuir — APPROVED** [review]

**Review by akyrtzi — APPROVED** [review]

**Comment by cachemeifyoucan** [comment]
Please test with following pull request:
https://github.com/apple/llvm-project/pull/4850

@swift-ci Please test

**Comment by cachemeifyoucan** [comment]
Please test with following pull request:
https://github.com/apple/llvm-project/pull/4850

@swift-ci Please test Windows platform

**Comment by cachemeifyoucan** [comment]
Please test with following pull request:
https://github.com/apple/llvm-project/pull/4850

@swift-ci Please test Windows platform

**Comment by cachemeifyoucan** [comment]
Please test with following pull request:
https://github.com/apple/llvm-project/pull/4850

@swift-ci Please test Windows platform

**Comment by cachemeifyoucan** [comment]
Please test with following pull request:
https://github.com/apple/llvm-project/pull/4850

@swift-ci Please test

**Pull request merged**
