### PR TITLE
[benchmark] run_smoke_bench with BenchmarkDriver

### PR DESCRIPTION
**Pull request by palimondo**
This PR extends the `BenchmarkDriver` with support for specifying `sample-time` and performing the measurement of all tests in a single batch run. This is then used to refactor `run_smoke_bench` to reuse existing library functionality (with full unit test coverage), instead of a hand-rolled parser and comparison logic.

There was a slight change in output format in `-verbose` mode: the re-run tests are printed as a single list, instead of each benchmark on a new line.

### CODE REVIEW

**Comment by palimondo** [comment]
@eeckstein Please review 🙏

Do you think you could similarly reuse the existing library in the Apple-internal long-term performance measurement script? Or can I somehow help you do that? I would like to centralize the code, so that we re-use the parser and comparison logic as much as possible, to make further changes to benchmarking infrastructure easier and less disruptive.

**Comment by eeckstein** [comment]
> Do you think you could similarly reuse the existing library in the Apple-internal long-term performance measurement script?

In general yes, but currently we have no resources to work on this.

**Comment by palimondo** [comment]
> move everything to Benchmark_Deiver and remove smoke_bench

I don’t think so? It seems to me the code size comparisons are a bit separate topic from what’s currently covered by `Benchmark_Driver`. Also I’d like to maintain full unit test coverage for `BD` and `compare_perf…`.

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
@eeckstein When the benchmark finishes, the regressions/improvements should be same as reported in #21658 and there should be one added and one removed benchmark.

**Review by eeckstein — APPROVED** [review]
Thanks for doing the test.
LGTM!

**Comment by palimondo** [comment]
BTW, it looks like the refactored version is a bit more sensitive around the bottom threshold, because the final comparison contains merged samples from all the previous runs, whereas the original seems to be only retaining one result per benchmark from a given iteration when it fits inside the threshold or exceeds the `num_results_dont_differ` counter.

Thanks for the review! I'll merge in the morning, after the smoke test is done. 😴💤

**Pull request merged**
