### PR TITLE
[test] Logging a list of available features before executing the tests

### PR DESCRIPTION
**Pull request by moiseev**
It would be nice to have a full list of features enabled for every platform we run tests on logged somewhere.

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by moiseev** [comment]
Based on the https://github.com/apple/swift/pull/7801 experience.

**Review by modocache — APPROVED** [review]
This is a great idea! Thanks. 👍

**Review by erg — COMMENTED** [review]
Yes!

**Comment by moiseev** [comment]
Let's give it one more chance...
@swift-ci Please smoke test Linux platform

**Review by shahmishal — APPROVED** [review]
:)

**Pull request merged**
