### PR TITLE
[cast-optimizer] Bail out on a conditional downcast to a subclass of a bridged ObjC class

### PR DESCRIPTION
**Pull request by swiftix**
This is very conservative fix for rdar://problem/32316838.

### CODE REVIEW

**Comment by swiftix** [comment]
Explanation: The compiler should not turn conditional casts into non-conditional casts if a cast can fail.

Scope: Without this fix, the programs may crash at runtime of they e.g. use a downcast of  swift type to a subclass of their bridged ObjC class

Issue: rdar://problem/32316838

Risk: Low, because it disables the optimization in certain cases.

Testing: Swift CI

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by swiftix** [comment]
@jckarter Do you mind reviewing it for swift-4.0-branch?

There is also #9822, but it is more aggressive and tries to actually create a conditional cast if required.  But the current PR is probably a safer bet for the swift-4.0-branch. WDYT?

**Review by jckarter — APPROVED** [review]
Looks good, thanks! I agree with your assessment that it's best to take this conservative bailout for the 4.0 branch instead of attempting a deeper fix.

**Review by jckarter — APPROVED** [review]
Looks good, thanks! I agree with your assessment.

**Pull request merged**
