### PR TITLE
Fix AccessEnforcementOpts in debug builds.

### PR DESCRIPTION
**Pull request by atrick**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci smoke test and merge.

**Comment by gottesmm** [comment]
@atrick why was this broken? You aren't specific in the commit message.

**Comment by atrick** [comment]
Debug builds leave in static markers, which none of this stuff cares about, and there was an assert to check that the analysis covered all the markers.

**Comment by gottesmm** [comment]
Thanks!

**Pull request merged**
