### PR TITLE
[Driver] Remove built-in `run` subcommand

### PR DESCRIPTION
**Pull request by aciidgh**
This is as per discussion in https://bugs.swift.org/browse/SR-5332

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Comment by aciidb0mb3r** [comment]
Related to https://github.com/apple/swift-package-manager/pull/1258

**Comment by jrose-apple** [comment]
Looks good, but let's wait until the package manager change goes in, so there's minimum disruption for downloadable toolchains.

**Comment by hartbit** [comment]
@jrose-apple The package manager change has been merged into master: https://github.com/apple/swift-package-manager/pull/1258

**Comment by aciidb0mb3r** [comment]
Thanks @jrose-apple and @hartbit.

@jrose-apple Do I need to cherry pick this to swift-4.0-branch?

**Comment by jrose-apple** [comment]
If the `swift-run` command is going into 4.0, then yes, please. Will need to go through the usual release process, feel free to mark me as the reviewer.

**Pull request merged**
