### PR TITLE
[RemoteMirror] Add swift_reflection_interop_projectEnumValue()

### PR DESCRIPTION
**Pull request by al45tair**
Added a counterpart to the `swift_reflection_projectEnumValue()` API for the legacy interop support in `SwiftRemoteMirrorLegacyInterop.h`.

Also updated the test to use it to extract information from an enum.

rdar://62128103

### CODE REVIEW

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Review by mikeash — APPROVED** [review]
LGTM, and thanks for automating the test!

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
@swift-ci Please clean smoke test Linux platform

**Pull request merged**
