### PR TITLE
[ownership] On non-Darwin platforms, serialize the stdlib in OSSA form.

### PR DESCRIPTION
**Pull request by gottesmm**
This PR has two commits in it:

1. The first fixes a bunch of deserialization invalidation issues. These memory error causing bugs were being triggered in the global variable case when building Foundation when in this mode.
2. The second changes non-Darwin platforms to match Darwin and serialize the stdlib in OSSA form. Previously I enabled this only for Darwin since I ran into the bug from the first PR. To ensure that the Darwin side didn't regress, I upstreamed that while I investigated 1. Now that I figured that out, this PR turns it on and restores the tests I had to modify to allow for the platforms to differ here in favor of their original form.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test windows platform

**Review by atrick — APPROVED** [review]
Very nice! So out of curiosity, is there a potential issue with asking to deserialize entities that were already deleted, separate from memory corruption? We don't want to repeatedly deserialize.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@atrick I didn't look into that. In the deserialization case it is when we early on deserialize _swiftEmptyArrayStorage, then DCE it, then down the line after maybe additional inlining/etc it becomes exposed after deserializing a different function.

**Comment by gottesmm** [comment]
@atrick I didn't look into that. In the deserialization case it is when we early on deserialize _swiftEmptyArrayStorage, then DCE it, then down the line after maybe additional inlining/etc it becomes exposed after deserializing a different function.

**Comment by gottesmm** [comment]
@swift-ci test

**Pull request merged**
