### PR TITLE
[SourceKit/CodeFormat] Don't modify multiline string indentation regardless of it being column-aligned or not.

### PR DESCRIPTION
**Pull request by nathawes**
Resolves rdar://problem/61463947

### CODE REVIEW

**Comment by nathawes** [comment]
@swift-ci please test

**Comment by nathawes** [comment]
@swift-ci please test Windows Platform

**Comment by benlangmuir** [comment]
LGTM for the specific change.  One question: are we not indenting in multi-line strings *at all*? What happens on a blank line after opening a multi-line string?

**Comment by nathawes** [comment]
> LGTM for the specific change. One question: are we not indenting in multi-line strings _at all_?
> What happens on a blank line after opening a multi-line string?

We're not. Indentation is left as is, so hitting enter after the opening quotes puts you at column 1 on the next line (same behavior as 5.2).  This change is just so we don't mess up leading indentation where we didn't before. There are a bunch of open indentation issues we still need to look at for multi-line strings and also block comments (which have a bunch of the same issues).

**Review by benlangmuir — APPROVED** [review]
Great, thanks for the explanation

**Pull request merged**
