### PR TITLE
build-script-impl: reorganise the option

### PR DESCRIPTION
**Pull request by compnerd**
This reorders the option list.  It tries to categorise them by area and
then sort them alphabetically.  This should help work through the list
and remove the now defunct options as well as try to reduce the set of
options into different build configurations that we can support and try
to organise the CMake invocations properly.

There is still a group of uncategorised options that should get sorted
out at some point.  However, this is still a huge step forward towards
simplifying (and hopefully eradicating) this monstrous script.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Review by bulbazord — APPROVED** [review]
Looks fine to me. Seems like it should be easier to add and understand settings in the future. If you've verified that no settings got dropped (which is going to be hard for me to verify by just looking) then I think this is fine.

**Comment by compnerd** [comment]
CC: @shahmishal

**Comment by shahmishal** [comment]
@Rostepher @edymtt Can you please review this?

**Review by Rostepher — APPROVED** [review]
I'm definitely in favor of having these sorted and categorized. Should make maintenance easier in the future. LGTM!

**Pull request merged**
