### PR TITLE
[Parse] Set missing contextual keyword token kind for `async`

### PR DESCRIPTION
**Pull request by bnbarham**
Resolves rdar://93080331.

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Review by rintaro — APPROVED** [review]

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
@DougGregor since you specifically changed some of these in https://github.com/apple/swift/pull/33333

**Review by ahoppen — APPROVED** [review]
Looks like this needs corresponding SwiftSyntax changes.

**Comment by bnbarham** [comment]
@swift-ci please test macOS platform

**Comment by bnbarham** [comment]
apple/swift-syntax#444

@swift-ci please test macOS platform

**Pull request merged**
