### PR TITLE
Two of the macros tests are failing to import SwiftDiagnostics.

### PR DESCRIPTION
**Pull request by al45tair**
Marking these as UNSUPPORTED for now, pending a fix.

### CODE REVIEW

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by xymus** [comment]
We are considering disabling these before the branch lockdown, unless there's a fix close by.

**Review by xymus — APPROVED** [review]

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
@swift-ci Please smoke test and merge

**Pull request merged**
