### PR TITLE
[transferring] Implement swift_attr support for transferring results and parameters.

### PR DESCRIPTION
**Pull request by gottesmm**
rdar://125211624

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
I forgot to add to suppress availability to the test... = /.

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
The original transferring test was done in objc and I thought I could force the linux/windows to handle it... I was wrong. So now I have an objc/non-objc version of the test.

**Comment by gottesmm** [comment]
Still something weird, going to build on Linux to figure it out

**Review by beccadax — APPROVED** [review]

**Pull request merged**
