### PR TITLE
[5.9 🍒] TypeCheckType: Fix existential `any` migration diagnostics for extra-modular protocols

### LINKED ISSUE #65034: Enabling upcoming feature `ExistentialAny` does not work for standard library protocols.
**Description**

Enabling upcoming feature `ExistentialAny` does not work for standard library protocols.

For example, it should produce a compile error, considering `Decoder` is a bare protocol. However, the compiler does not produce any error or warning, even though for other non-standard library protocols it produces errors and warnings correctly.
```
init(from decoder: Decoder) throws { /* ... */ }
```

**Steps to reproduce**

1. `swift repl -enable-upcoming-feature ExistentialAny`
2. put following;
```swift
protocol P {}
extension Int: P {}
```
3. put following:
```swift
let value: P = 42
```
It produces an error
```
expression failed to parse:
error: repl.swift:5:12: error: use of protocol 'P' as a type must be written 'any P'
let value: P = 42
           ^
           any P
```
4. put following;
```swift
let value: Codable = 42
```
It works!

**Expected behavior**
`Codable` should also produce a compile error, but it doesn't.

**Environment**
- Swift compiler version info 
  ```
  swiftc -version
  swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
  Target: x86_64-apple-macosx13.0
  ```
- Xcode version info 
   ```
   Xcode 14.3
   Build version 14E222b
   ```
- Deployment target: N/A

As I checked, it seems `any P` check is not working for standard library protocols without associated types including `Codable`, `Decoder`, `Encoder`, `CustomStringConvertible`, `CustomDebugStringConvertible`, `ExpressibleBy*Literal`, and so on.

Forum thread: https://forums.swift.org/t/any-p-check-doesnt-work-for-standard-library-protocols/64276

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
* **Explanation**: See #65112.
* **Scope**: Missing diagnostics for adoption of explicit existential `any` in Swift 6 mode.
* **Issue**: Resolves #65034.
* **Risk**: Very low. A simple and predictable functional change.
* **Testing**: No additional testing warranted. This change does not impact code generation whatsoever, and is source-compatible unless the `ExistentialAny` feature is enabled (enabling the feature is supposed to be source-breaking).
* **Reviewer**: @hborla
* **Main branch PRs**: 
  * #65112 
  * #65132

### CODE REVIEW

**Comment by AnthonyLatsis** [comment]
@swift-ci please test

**Comment by AnthonyLatsis** [comment]
@hborla ping

**Review by hborla — APPROVED** [review]

**Comment by AnthonyLatsis** [comment]
@swift-ci please test

**Comment by AnthonyLatsis** [comment]
I’m wondering if we can set up our CI↔︎GitHub infra to require rerunning successful checks after a period of time.

**Pull request merged**
