### PR TITLE
Remove duplicated line

### PR DESCRIPTION
**Pull request by pahmed**

### CODE REVIEW

**Comment by shahmishal** [comment]
Reverting this change due to test failure "IDE/dump_api.swift"

**Comment by pahmed** [comment]
Sorry, but how removing this comment could cause test failure?

**Comment by rudkx** [comment]
@pahmed The file you changed is the expected test output. The test input (dump_api.swift) has this comment in two different places, and apparently the dumper is emitting them next to one another in the output.

**Comment by pahmed** [comment]
Got it, thanks rudkx

**Pull request merged**
