### PR TITLE
Temporarily disable 16-bit floating point tests on linux

### PR DESCRIPTION
**Pull request by eeckstein**
rdar://104134160

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test linux

**Comment by eeckstein** [comment]
Not needed anymore. Fixed by https://github.com/apple/swift/pull/63304

**Pull request closed without merging**
