### PR TITLE
[5.5] [Concurrency] Deprecate Task.sleep(_:) in favor of Task.sleep(nanoseconds:).

### PR DESCRIPTION
**Pull request by varungandhi-apple**
main PR: https://github.com/apple/swift/pull/38477

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
@swift-ci test

**Comment by varungandhi-apple** [comment]
@swift-ci test

**Comment by varungandhi-apple** [comment]
@swift-ci test

**Comment by varungandhi-apple** [comment]
@swift-ci test Linux

**Comment by varungandhi-apple** [comment]
@swift-ci test

**Comment by varungandhi-apple** [comment]
Fixes rdar://81703306

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
