### PR TITLE
[ConstraintGraph] Fix `contractEdges` to gather constraints only once

### PR DESCRIPTION
**Pull request by xedin**
Currently we have this non-optimal behavior in `contractEdges` where
for every type variable it gathers constraints for its whole equivalence
class before checking if any are "contractable", instead constraints
could be gathered/filtered once which removes a lot of useless work.

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please smoke test compiler performance

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Review by rudkx — APPROVED** [review]
LGTM!

How much does this speed up type checking cases like [SR-7632](https://bugs.swift.org/browse/SR-7632)?

**Comment by slavapestov** [comment]
Can we add a scale_test for this?

**Comment by xedin** [comment]
@slavapestov I will try, but the problem is that we don't really have a good counter right now to measure the effect at the moment...

**Comment by slavapestov** [comment]
@xedin You should just add a new counter that would be quadratic without this change. I think it’s important to test this so we don’t regress in the future.

**Comment by xedin** [comment]
@graydon Could you please take a look at statistics changes? I wonder why I get `No data` when I run new scale test I added, I did everything exactly like `incrementScopeCounter`...

**Comment by xedin** [comment]
I wonder if that’s because that particular test would actually never find any contractable constraints... I will try putting it in find since that actual iteration.

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please source compatibility

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please source compatibility

**Comment by xedin** [comment]
@rudkx I've made it so counter tracks number of constraints iterated on every run of `contractEdges` and a test from 0 to 25k with 1k increments which takes about ~5 secs. on my machine.

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please source compatibility

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Pull request merged**
