### PR TITLE
Merge tag 'swift-DEVELOPMENT-SNAPSHOT-2019-12-16-a ' into tensorflow

### PR DESCRIPTION
**Pull request by dan-zheng**

### CODE REVIEW

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by asuhan** [comment]
Thanks!

**Review by asuhan — APPROVED** [review]

**Comment by dan-zheng** [comment]
> Thanks! Should we squash the additional commits into the merge? I can try this myself.

Sure, if you'd like to! I don't feel strongly.

**Comment by asuhan** [comment]
Squashing the additional commits is a pain, we'll go ahead as-is.

**Comment by asuhan** [comment]
@swift-ci Please clean test tensorflow

**Pull request merged**
