### PR TITLE
Don't include revisions in --version output by default

### PR DESCRIPTION
**Pull request by jrose-apple**
New build-script-impl option `swift-include-revisions-in-version`, which controls whether revision numbers show up in `--version` output. Turning this on results in the compiler being rebuilt every time the current checked-out revision changes, which then results in the standard library being rebuilt unnecessarily. The default is off.

As far as the standard presets go, this is turned on for non-incremental buildbot builds and package builds, and off in incremental buildbot builds.

Present for @dabrahams. 

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by jrose-apple** [comment]
Low-priority review request for @gribozavr.

@swift-ci Please smoke test

**Comment by practicalswift** [comment]
@jrose-apple Thank you! I've been thinking about fixing this for quite a while! Thanks for doing it! :-)

**Comment by dabrahams** [comment]
on Fri Apr 08 2016, Jordan Rose <notifications-AT-github.com> wrote:

> New build-script-impl option swift-include-revisions-in-version, which controls
> whether revision numbers show up in --version output. Turning this on results in
> the compiler being rebuilt every time the current checked-out revision changes,
> which then results in the standard library being rebuilt unnecessarily. The
> default is off.
>
> As far as the standard presets go, this is turned on for non-incremental
> buildbot builds and package builds, and off in incremental buildbot builds.
>
> Present for @dabrahams. 

My hero!

Thanks.

-- 
Dave

**Comment by jrose-apple** [comment]
I'm afraid I'll have to betray you all; Dmitri reminded me that this version string is used to avoid reusing the Clang module cache when something has changed. That means that changing the importer could result in crashes.

I could still add this and just have it on by default, but I'm reluctant to even allow turning it off. The most likely symptom of a stale Clang module cache is crashes in clang::ASTReader, but it could also result in changed apinotes or import strategies not being applied, which means tests would just inexplicably fail locally.

I think this needs a cleverer solution.

**Comment by jrose-apple** [comment]
I'll leave the branch around for a while in case anyone wants to do something with it.

**Comment by gparker42** [comment]
> Dmitri reminded me that this version string is used to avoid reusing the Clang module cache when something has changed.

Can you add such a comment to the current version code, so that we aren't tempted to remove it again later while Dmitri isn't looking?

**Pull request closed without merging**
