### PR TITLE
[build-script] When building packages install llvm-cov, llvm-profdata…

### PR DESCRIPTION
**Pull request by gottesmm**
… for use with swiftpm.

rdar://44567818
https://bugs.swift.org/browse/SR-9082

----

I think this will work. But lets see.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci build linux toolchain

**Comment by gottesmm** [comment]
@swift-ci build toolchain

**Review by shahmishal — APPROVED** [review]
LGTM

**Comment by gottesmm** [comment]
To be clear, the linux change affects /all/ linux installations not just packages.

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
I just verified by hand that both toolchains have llvm-cov and llvm-profdata installed. I am going to add an integration test in a separate PR.

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by aciidb0mb3r** [comment]
I tested the built linux toolchain, the codecov feature is indeed working. Thanks!

**Comment by gottesmm** [comment]
@aciidb0mb3r can you put your test into an integration test? So we can make sure this always works?

**Comment by gottesmm** [comment]
(just asking since you said you had an impl).

**Comment by gottesmm** [comment]
I think the tsan test is XFAILed now. Lets try this once again.

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Pull request merged**
