### PR TITLE
A couple of ReturnStmt tweaks

### PR DESCRIPTION
**Pull request by hamishknight**
Introduce `ReturnStmt::createParsed` and `ReturnStmt::createImplicit`, and tweak a couple of other things.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Review by bnbarham — APPROVED** [review]
Thanks for the cleanup 🙇. Going to do `BraceStmt` too 😆?

**Comment by hamishknight** [comment]
https://github.com/apple/llvm-project/pull/8027

@swift-ci please test

**Comment by hamishknight** [comment]
> Going to do BraceStmt too 😆?

Heh, we actually have `BraceStmt::createImplicit` already, just need to go through and migrate everything passing `true` to `BraceStmt::create` 😅

**Review by ktoso — APPROVED** [review]

**Pull request merged**
