### PR TITLE
[cxx-interop] Add support for percent, ampersand, and pipe operators.

### PR DESCRIPTION
**Pull request by zoecarver**
Adds support for three more basic infix operators: `%`, `&`, and `|`.

### CODE REVIEW

**Comment by MForster** [comment]
@swift-ci Please test

**Review by MForster — APPROVED** [review]
Thanks!

**Comment by MForster** [comment]
@swift-ci Please test OS X Platform

**Review by gribozavr — APPROVED** [review]

**Comment by MForster** [comment]
@swift-ci Please test

**Comment by MForster** [comment]
@swift-ci Please test

**Comment by zoecarver** [comment]
@swift-ci please test windows platform

**Pull request merged**
