### PR TITLE
SIL verifier: Fix polarity of consuming check through (unchecked_addr_cast (open_existential_addr)).

### PR DESCRIPTION
**Pull request by jckarter**
This was looking for a single non-consuming use instead of checking for the absence of any consuming uses, leading to false-positives when there were multiple non-consuming uses. Fixes rdar://problem/44116763.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Review by aschwaighofer — APPROVED** [review]
LGTM. If we wanted to be more strict here we would have to check users recursively

**Comment by jckarter** [comment]
@swift-ci Please test Linux

**Comment by jckarter** [comment]
@swift-ci Please test OS X

**Comment by jckarter** [comment]
Compatibility suite failures look like unrelated known failures.

**Pull request merged**
