### PR TITLE
[5.0][stdlib] tee _stdlib_AtomicInt > SwiftPrivate

### PR DESCRIPTION
**Pull request by moiseev**
5.0 version of https://github.com/apple/swift/pull/21337

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please testr

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
@swift-ci Please test

**Review by najacque — APPROVED** [review]

**Pull request merged**
