### PR TITLE
[Changelog] Add SE-0268 to the changelog

### PR DESCRIPTION
**Pull request by theblixguy**

### CODE REVIEW

**Comment by theblixguy** [comment]
@swift-ci please smoke test

**Review by CodaFi — APPROVED** [review]
LGTM. Owen also landed an SE, so you'll have to give this a quick rebase.

**Comment by theblixguy** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by theblixguy** [comment]
@swift-ci please smoke test

**Comment by theblixguy** [comment]
@swift-ci please smoke test Linux

**Comment by theblixguy** [comment]
@swift-ci please smoke test Linux

**Pull request merged**
