### PR TITLE
[4.0] [QoI] Improve diagnostic for raw representable argument mismatch

### PR DESCRIPTION
**Pull request by xedin**
* Description: Covers some common situations when switching from literal types e.g.
string or int to more Swift Way of raw representable enum of choices.

* Scope of the issue: diagnostic improvements for raw representable type mismatches in arguments.

* Risk: Low.

* Tested: New test cases added, Swift CI.

* Reviewed by: Mark Lacey.

* Resolves: rdar://problem/32431165, rdar://problem/31977537, rdar://problem/32432253

(cherry picked from commit 2d8dca026662ca2677c7f577585f07af0e9f9432)

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please clean test Linux platform

**Comment by xedin** [comment]
@swift-ci please clean test Linux platform

**Comment by xedin** [comment]
Something is going on with mangling probably:

```
12:32:12 CoreFoundation/Base.subproj/CFRuntime.c:(.text+0xb72): undefined reference to `_T010Foundation21__CFSwiftGetBaseClasss9AnyObject_pXpyF'
```

**Comment by xedin** [comment]
@swift-ci please clean test Linux platform

**Review by rudkx — APPROVED** [review]
LGTM!

**Pull request merged**
