### PR TITLE
[Caching] Embed bridging header in binary module correctly when caching

### PR DESCRIPTION
**Pull request by cachemeifyoucan**
When caching is enabled with include-tree, the bridging header PCH is created from the include tree directly. Setup the rewriter correctly when embedding the bridging header into swift binary module.

rdar://125719747

### CODE REVIEW

**Comment by cachemeifyoucan** [comment]
Need clang change here: https://github.com/apple/llvm-project/pull/8531

**Comment by cachemeifyoucan** [comment]
Please test with following pull request:
https://github.com/apple/llvm-project/pull/8531

@swift-ci please smoke test

**Comment by cachemeifyoucan** [comment]
Please test with following pull request:
https://github.com/apple/llvm-project/pull/8531

@swift-ci please smoke test linux platform

**Review by artemcm — APPROVED** [review]

**Comment by cachemeifyoucan** [comment]
@swift-ci please smoke test

**Pull request merged**
