### PR TITLE
[6.0] Metadata and runtime support for invertible protocol requirements

### PR DESCRIPTION
**Pull request by DougGregor**
* **Explanation**: Implement metadata and runtime support for invertible protocol requirements (which covers noncopyable generics), so that we can evaluate constraints such as `T: Copyable` at runtime, e.g., for conditional conformances and existentials.
* **Issue**: rdar://123466649
* **Original PR**: https://github.com/apple/swift/pull/72470
* **Reviewer**: @mikeash , @al45tair 
* **Risk**: Moderate. This is a significant change to the runtime checking of generic constraints that affects all programs. Specifically, every time we check generic constraints (dynamic casting to existential types, conditional conformance checking, demangling a name to type metadat, etc.), every generic argument argument will be checked against the constraint `T: Copyable` unless it was specifically disabled (e.g., via a `T: ~Copyable` constraint). Moreover, this extends the metadata for nominal types and generic requirements in a manner that is backward compatible *except* for generic types that suppress conformances. We can't think of any way in which this would cause problems, but it's a risk.
* **Testing**: New tests, source compatibility suite.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please benchmark

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Review by airspeedswift — APPROVED** [review]

**Pull request merged**
