### PR TITLE
Remove copy constructors and assignment operators from RelativeDirect…

### PR DESCRIPTION
**Pull request by swiftix**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [x] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

…PointerImpl.

There were places were RelativeDirectPointers were copied using bitwise copies, which is semantically wrong. This patch makes sure it cannot happen anymore.

### CODE REVIEW

**Comment by swiftix** [comment]
@bitjammer Do you mind reviewing it? This is my naive attempt to fix the issue we discussed this morning. I'm not 100% sure about the  `Metadata.h` fixes. They work, but may be there is a more elegant way to fix the issue?

Specifically, I provided a copy constructor for TargetClassMetadata, because it is used by tests. Since Description is not copyable anymore, I had to play tricks involving the `memcpy` and then explicitly calling the setDescription.

I also introduced the `NullPtr` trick to mimic a RelativeDirectPointer value with the offset of 0. But may be it can be done in a nicer way?

And of course, there is another way to solve the whole issue with `getDescription`. We could simply make it return the actual absolute pointer, I guess.

**Comment by bitjammer** [comment]
@swift-ci Please test

**Comment by bitjammer** [comment]
When reflecting on a remote process, I don't think we can make getDescription resolve the address because the base will be in the wrong address space: we read these metadata out of the target and send back to an analysis process.

**Comment by bitjammer** [comment]
Which tests require the copy constructor for TargetClassMetadata?

**Comment by bitjammer** [comment]
@slavapestov Any comments?

**Comment by slavapestov** [comment]
No objections from me.

**Comment by swiftix** [comment]
@bitjammer The test in question is the `unittests/runtime/Metadata.cpp`, which has a following snippet:

```cpp
FullMetadata<ClassMetadata> MetadataTest2 = {
  { { nullptr }, { &_TWVBo } },
  { { { MetadataKind::Class } }, nullptr, 0, ClassFlags(), nullptr, 0, 0, 0, 0, 0 }
};
```

This snippet invokes the copy constructors of `TargetClassMetadata `, when it creates `FullMetadata `.

**Comment by swiftix** [comment]
@swift-ci Please test

**Comment by swiftix** [comment]
@bitjammer @slavapestov All tests pass. OK to merge in the current form then? Or do you think it requires any stylistic/other changes?

**Comment by bitjammer** [comment]
Looks good to me! Thank you!

**Pull request merged**
