### PR TITLE
[AutoDiff] Enable end-to-end differentiation using `Builtin.autodiffGetVJP`

### PR DESCRIPTION
**Pull request by rxwei**
This patch makes `Builtin.autodiffGetVJP` usable as a differential operator. It gives you the vector-Jacobian product function, for example:

```swift
func func_to_diff(x: Float) -> Float {
  return x * x
}
let (y, pullback) = Builtin.autodiffGetVJP(func_to_diff)(4)
pullback(1) // 8
```

We are still fixing various issues, including:
- Teaching SILGen to emit reabstraction thunks for `@autodiff` functions.
- Changing `Builtin.autodiffGetVJP` to `Builtin.autodiffApplyVJP` so that
  - the parent function (any differential operator defined as functions in stdlib) can `rethrow` when the closure throws, and
  - the argument to the builtin need not be `@escaping`.

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Review by marcrasi — APPROVED** [review]

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow macOS

**Pull request merged**
