### PR TITLE
Turn on AnyHashable

### PR DESCRIPTION
**Pull request by jckarter**
Integrate `AnyHashable` into the clang importer and runtime bridging.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@atrick @aschwaighofer Any idea what could cause this kind of crash?

```
Assertion failed: (fn->getLinkage() == linkage), function getOrCreateFunction, file /Users/buildnode/jenkins/workspace/swift-PR-osx/swift/lib/SIL/SILModule.cpp, line 319.
0  swift                    0x000000010d0e989b llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 43
1  swift                    0x000000010d0e8ac6 llvm::sys::RunSignalHandlers() + 70
2  swift                    0x000000010d0ea171 SignalHandler(int) + 641
3  libsystem_platform.dylib 0x00007fff9329c52a _sigtramp + 26
4  libsystem_platform.dylib 0x00007fff679e4ac5 _sigtramp + 3564406197
5  swift                    0x000000010d0e9dbe abort + 14
6  swift                    0x000000010d0e9da1 __assert_rtn + 81
7  swift                    0x000000010a802c5b swift::SILModule::getOrCreateFunction(swift::SILLocation, swift::SILDeclRef, swift::ForDefinition_t) + 2187
8  swift                    0x000000010a573260 swift::CastOptimizer::optimizeBridgedSwiftToObjCCast(swift::SILInstruction*, bool, swift::SILValue, swift::SILValue, swift::CanType, swift::CanType, swift::Type, swift::Type, swift::SILBasicBlock*, swift::SILBasicBlock*) + 1088
9  swift                    0x000000010a573a72 swift::CastOptimizer::optimizeBridgedCasts(swift::SILInstruction*, bool, swift::SILValue, swift::SILValue, swift::CanType, swift::CanType, swift::SILBasicBlock*, swift::SILBasicBlock*) + 674
10 swift                    0x000000010a573fcd swift::CastOptimizer::simplifyCheckedCastAddrBranchInst(swift::CheckedCastAddrBranchInst*) + 1069
11 swift                    0x000000010a5f3db4 processFunction(swift::SILFunction&, bool, unsigned int) + 3348
12 swift                    0x000000010a5f874d (anonymous namespace)::ConstantPropagation::run() + 45
13 swift                    0x000000010a5919ff swift::SILPassManager::runPassesOnFunction(llvm::ArrayRef<swift::SILFunctionTransform*>, swift::SILFunction*, bool) + 2255
14 swift                    0x000000010a592a29 swift::SILPassManager::runFunctionPasses(llvm::ArrayRef<swift::SILFunctionTransform*>) + 1193
15 swift                    0x000000010a593d64 swift::SILPassManager::runOneIteration() + 964
16 swift                    0x000000010a59ea47 swift::runSILOptimizationPasses(swift::SILModule&) + 231
17 swift                    0x000000010a2911ef performCompile(swift::CompilerInstance&, swift::CompilerInvocation&, llvm::ArrayRef<char const*>, int&, swift::FrontendObserver*) + 13903
18 swift                    0x000000010a28c8cf swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 2895
19 swift                    0x000000010a24f210 main + 2448
20 libdyld.dylib            0x00007fff9512e5ad start + 1
```

**Comment by aschwaighofer** [comment]
I have not yet had a chance to look at that one but there is code in the cast optimizer that calls:
ASTContext::getBridgedToObjC 

And it currently returns the wrong answer for casts from AnyObject (false) to formerly unbridged (struct Unbridged{}) types. Under id-as-any it needs to return the “SwiftValue” generic box type or at least Type() and not None.

I am working on fixing ASTContext::getBridgedToObjC. Maybe this is related. I will look at this next.

**Comment by jckarter** [comment]
@aschwaighofer I think the assertion failure might be benign in this case. It looks like `getOrCreateFunction` is trying to summon the symbol declaration with `PublicExternal` linkage, but there's already a definition with `Public` linkage, which should be OK. I think I can relax the assertion to be:

```diff
-    assert(fn->getLinkage() == linkage);
+    assert(fn->getLinkage() == constant.getLinkage(ForDefinition)
+           || fn->getLinkage() == constant.getLinkage(NotForDefinition));
```

Does that seem reasonable?

**Comment by jckarter** [comment]
Unfortunately, relaxing the assertion reveals another assertion failure behind it:

```
Assertion failed: (srcAddr->getType() == destAddr->getType()), function createCopyAddr, file /Users/jgroff/src/s/swift/include/swift/SIL/SILBuilder.h, line 516.
Process 1267 stopped
* thread #1: tid = 0xfb316, 0x00000001055b7dda libsystem_kernel.dylib`__pthread_kill + 10, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001055b7dda libsystem_kernel.dylib`__pthread_kill + 10
libsystem_kernel.dylib`__pthread_kill:
->  0x1055b7dda <+10>: jae    0x1055b7de4               ; <+20>
    0x1055b7ddc <+12>: movq   %rax, %rdi
    0x1055b7ddf <+15>: jmp    0x1055b0d8f               ; cerror_nocancel
    0x1055b7de4 <+20>: retq   
(lldb) bt
* thread #1: tid = 0xfb316, 0x00000001055b7dda libsystem_kernel.dylib`__pthread_kill + 10, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x00000001055b7dda libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x000000010570d92b libsystem_pthread.dylib`pthread_kill + 90
    frame #2: 0x0000000102ee708e swift`abort + 14
    frame #3: 0x0000000102ee7071 swift`__assert_rtn + 81
    frame #4: 0x00000001005a292d swift`swift::SILBuilder::createCopyAddr(swift::SILLocation, swift::SILValue, swift::SILValue, swift::IsTake_t, swift::IsInitialization_t) + 333
    frame #5: 0x0000000100335c27 swift`swift::SILCloner<swift::SILInliner>::visitCopyAddrInst(swift::CopyAddrInst*) + 343
    frame #6: 0x0000000100331f6b swift`swift::SILCloner<swift::SILInliner>::visitSILBasicBlock(swift::SILBasicBlock*) + 91
    frame #7: 0x0000000100331a06 swift`swift::SILInliner::inlineFunction(swift::FullApplySite, llvm::ArrayRef<swift::SILValue>) + 1206
    frame #8: 0x00000001003f5969 swift`(anonymous namespace)::SILPerformanceInliner::inlineCallsIntoFunction(swift::SILFunction*) + 12217
    frame #9: 0x00000001003f288a swift`(anonymous namespace)::SILPerformanceInlinerPass::run() + 410
    frame #10: 0x000000010034a10f swift`swift::SILPassManager::runPassesOnFunction(llvm::ArrayRef<swift::SILFunctionTransform*>, swift::SILFunction*, bool) + 2255
    frame #11: 0x000000010034b139 swift`swift::SILPassManager::runFunctionPasses(llvm::ArrayRef<swift::SILFunctionTransform*>) + 1193
    frame #12: 0x000000010034c474 swift`swift::SILPassManager::runOneIteration() + 964
    frame #13: 0x0000000100357157 swift`swift::runSILOptimizationPasses(swift::SILModule&) + 231
    frame #14: 0x0000000100049c3f swift`performCompile(swift::CompilerInstance&, swift::CompilerInvocation&, llvm::ArrayRef<char const*>, int&, swift::FrontendObserver*) + 13903
    frame #15: 0x000000010004531f swift`swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 2895
    frame #16: 0x0000000100007c90 swift`main + 2448
    frame #17: 0x000000010540b255 libdyld.dylib`start + 1
    frame #18: 0x000000010540b255 libdyld.dylib`start + 1
```

**Comment by jckarter** [comment]
The operands are a value and an address, suggesting something is confused about whether it's working with address-only types or not:

```
  %274 = load %271 : $*AnyHashable, scope 0       // users: %275, %277
  %276 = alloc_stack $AnyHashable, loc "/Users/jgroff/src/s/swift/stdlib/public/SDK/Foundation/Foundation.swift":1512:26, scope 0
```

**Comment by jckarter** [comment]
The mismatch happens in the SILCloner while inlining something. Let me try to figure out what.

**Comment by jckarter** [comment]
@aschwaighofer It's trying to inline `AnyHashable._bridgeToObjectiveC()` into `_dictionaryUpCast`. The code is already incorrect in the callee; maybe our bridging cast specialization doesn't expect address-only bridged types? The call looks like this in the callee:

```
  %273 = function_ref @_TFE10FoundationVs11AnyHashable19_bridgeToObjectiveCfT_CSo8NSObject : $@convention(method) (@in_guaranteed AnyHashable) -> @owned NSObject, scope 145 // users: %282, %275
  %274 = load %271 : $*AnyHashable, scope 145     // user: %275
  %275 = apply %273(%274) : $@convention(method) (@in_guaranteed AnyHashable) -> @owned NSObject, scope 145 // user: %276
```

The parameter to the call is indirect so it shouldn't be loaded first.

**Comment by jckarter** [comment]
@swift-ci Please test OS X

**Comment by jckarter** [comment]
@swift-ci Please test OS X

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
Build failed due to unrelated breakage:

```
/Users/buildnode/jenkins/workspace/swift-PR-osx/swiftpm/Sources/Basic/JSON.swift:139:24: error: adjacent operators are in non-associative precedence group 'DefaultPrecedence'
                stream <<< Format.asJSON(key) <<< ": " <<< contents[key]!
                       ^                      ~~~
/Users/buildnode/jenkins/workspace/swift-PR-osx/swiftpm/Sources/Basic/JSON.swift:139:47: error: adjacent operators are in non-associative precedence group 'DefaultPrecedence'
                stream <<< Format.asJSON(key) <<< ": " <<< contents[key]!
                                              ^        ~~~
/Users/buildnode/jenkins/workspace/swift-PR-osx/swiftpm/Sources/Basic/OutputByteStream.swift:254:20: warning: operator should no longer be declared with body
infix operator <<< { associativity left }
                   ^
/Users/buildnode/jenkins/workspace/swift-PR-osx/swiftpm/Sources/Basic/OutputByteStream.swift:475:24: error: adjacent operators are in non-associative precedence group 'DefaultPrecedence'
                stream <<< Format.asJSON(key) <<< ":" <<< Format.asJSON(value)
                       ^                      ~~~
/Users/buildnode/jenkins/workspace/swift-PR-osx/swiftpm/Sources/Basic/OutputByteStream.swift:475:47: error: adjacent operators are in non-associative precedence group 'DefaultPrecedence'
                stream <<< Format.asJSON(key) <<< ":" <<< Format.asJSON(value)
                                              ^       ~~~
<unknown>:0: error: build had 1 command failures
```

**Comment by jckarter** [comment]
@rjmccall, IIRC you were working on the precedence group stuff. Looks like something in swiftpm needs to be updated.

**Pull request merged**
