### PR TITLE
[gardening] Remove unused method getSyntheticSignature()

### PR DESCRIPTION
**Pull request by practicalswift**

### CODE REVIEW

**Comment by practicalswift** [comment]
This should probably be reviewed by @DougGregor :-)

**Comment by practicalswift** [comment]
@swift-ci please test

**Comment by practicalswift** [comment]
@swift-ci please smoke test

**Comment by slavapestov** [comment]
It's fine to remove this.

**Comment by practicalswift** [comment]
@slavapestov Thanks for the quick feedback!

**Pull request merged**
