### PR TITLE
[Sema] Corrections for for-await-in syntax to prevent specific bad code-gen scenarios and improve diagnostics

### PR DESCRIPTION
**Pull request by phausler**
SILGen verification crash when no other async functions are called in a function body not marked as async when a for-await-in syntax is used. This corrects the diagnostics to ensure that the type check effects sees the proper async call that the for-await-in syntax infers.

for-await-in syntax was missing a diagnistic hint for inserting a try when the protocol conformance of the sequence shows a potential of throwing. (also there was a superfluous check for the nominal type in that type check (which was removed).

for-await-in syntax and for-try-await-in syntax did not infer async or throwing to closure constraints, both were added to properly identify the asyncy-ness/throwy-ness of the iteration.

Resolves:
rdar://73952786
rdar://73883058
rdar://73953266
rdar://73995416
rdar://74008250

### CODE REVIEW

**Comment by phausler** [comment]
@swift-ci please smoke test

**Comment by phausler** [comment]
ooh that is a fun error from windows:
```
fatal: not a git repository (or any of the parent directories): .git
error: https://github.com/apple/swift.git did not send all necessary objects

fatal: not a git repository (or any of the parent directories): .git
```
network failure?

**Comment by phausler** [comment]
Mac failure is:
```
/Users/buildnode/jenkins/workspace/swift-PR-macos-smoke-test/branch-main/swiftpm/Sources/Build/SPMSwiftDriverExecutor.swift:80:39: error: value of type '[Job.ArgTemplate]' has no member 'joinedArguments'
10:51:18       result += " # \(job.commandLine.joinedArguments)"
10:51:18                       ~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~
10:51:18 [14/21][ 66%][34.489s] Linking Swift shared library lib/libXcodeproj.dylib
10:51:18 ninja: build stopped: subcommand failed.
```

**Comment by phausler** [comment]
@swift-ci please smoke test

**Comment by phausler** [comment]
@swift-ci please smoke test

**Review by DougGregor — APPROVED** [review]

**Comment by phausler** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
Toolchain build had a strange error:
```
20:52:08 fatal error
20:52:08 : module map file '/Users/buildnode/jenkins/workspace/swift-PR-toolchain-osx/branch-main/buildbot_osx/swiftpm-macosx-x86_64/apple/Intermediates.noindex/GeneratedModuleMaps/macosx/CCryptoBoringSSL.modulemap' not found
```

**Comment by kylemacomber** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Pull request merged**
