### PR TITLE
[stdlib] Remove no-longer-used _Incrementable protocol

### PR DESCRIPTION
**Pull request by airspeedswift**
No longer used, just hanging around.

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please clean test

**Comment by slavapestov** [comment]
Hey, I was planning on using it.

**Comment by airspeedswift** [comment]
make yer own, this one's going in the shredder

**Comment by DougGregor** [comment]
@airspeedswift , this appears to have broken SwiftyJSON:

/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite/project_cache/Kitura/.build/checkouts/SwiftyJSON.git--6955445084174387031/Source/SwiftyJSON.swift:406:26: error: use of undeclared type '_Incrementable'
public struct JSONIndex: _Incrementable, Equatable, Comparable {
                         ^~~~~~~~~~~~~~

**Comment by airspeedswift** [comment]
It broke Kitura, rather, which is running on a diverged fork of SwiftyJSON from a while back. Looks like SwiftyJSON itself removed it over a year ago.

**Pull request merged**
