### PR TITLE
[5.5][Refactoring] Add @completionHandlerAsync to sync function

### PR DESCRIPTION
**Pull request by bnbarham**
Cherry-picks https://github.com/apple/swift/pull/37358 (to avoid a merge conflict) and https://github.com/apple/swift/pull/37417

-----

When adding an async alternative, add the @completionHandlerAsync
attribute to the sync function. Check for this attribute in addition to
the name check, ie. convert a call if the callee has either
@completionHandlerAsync or a name that is completion-handler-like name.

The addition of the attribute is currently gated behind the experimental
concurrency flag.

Resolves rdar://77486504

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
@swift-ci please test Linux platform

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
@swift-ci please nominate

--- CCC ---

Explanation: Add a "@completionHandlerAsync" attribute to the sync function when performing the "Add Async Alternative" refactoring and experimental concurrency features are enabled with -enable-experimental-concurrency. Have the function conversion check if this attribute is on the callee of a callsite when deciding whether to convert it (in addition to the existing name check).

Adding the attribute also enables a warning when that function is used in an async context (already used for implicitly imported ObjectiveC async functions).

Radar/SR Issue: rdar://77486504

Risk: Very low - only affects the async refactoring and only when experimental concurrency features are enabled.

Testing: Added new test cases to the refactoring test suite

**Review by akyrtzi — APPROVED** [review]

**Pull request merged**
