### PR TITLE
[WIP] An alternative design for heterogeneous comparison

### PR DESCRIPTION
**Pull request by xwu**
SE-0104 introduces heterogeneous overloads for equality and comparison operators. However, this leads to an issue during some comparisons with a literal where the typechecker prefers heterogeneous comparison with an `Int` over homogeneous comparison, as reported in [SR-4984](https://bugs.swift.org/browse/SR-4984):

```
(swift) UInt() != 0xFFFF_FFFF_FFFF_FFFF
<REPL Input>:1:11: error: integer literal '18446744073709551615' overflows when stored into 'Int'
UInt() != 0xFFFF_FFFF_FFFF_FFFF
          ^
```

However, `UInt() == 0xFFFF_FFFF_FFFF_FFFF` works as expected because a concrete implementation of `==` is defined in `UInt`. This issue can be solved for concrete types by moving derived equality and comparison operators to concrete types, as in #9909.

Even after #9909, however, the same defect continues to persist with generic code. The workaround for `0xFFFF_FFFF_FFFF_FFFF` is to write `0xFFFF_FFFF_FFFF_FFFF as T`, which by itself is not extremely onerous. However, other pitfalls like `x == ~0` vs. `x == (~0 as T)` (or any bitwise operation) are concerning because they do not trip compiler diagnostics. Although the aim of SE-0104 was to enable better and more generic algorithms, this represents a real setback in ergonomics due to the frequency with which such comparisons are used: consistent use of homogeneous comparisons can affect a significant swath of code. (For example, see https://github.com/xwu/NumericAnnex/pull/3/commits/042ae884abecfabc9f655041da8eea7d58854bfd.)

#9932 demonstrates that it is not possible to support heterogeneous comparison in generic code without this problem. Therefore, this PR moves the implementation of heterogeneous comparison operators from `BinaryInteger` to a refinement named `_BinaryInteger` to which concrete types conform. Generic code will then be able to use only homogeneous comparison--until such time as the compiler supports additional features that make possible the intended design.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by xwu** [comment]
@moiseev Humor me on this one for a bit: let's see if it'll actually work. Then, we can discuss whether it's a terrible idea.

**Comment by moiseev** [comment]
@swift-ci Please smoke test macOS platform

**Comment by xwu** [comment]
@moiseev Test failures seem unrelated; can we try again?

**Comment by moiseev** [comment]
@swift-ci Please smoke test macOS platform

**Comment by xwu** [comment]
:/ Well, this has me stumped. Failures again, but still looking unrelated.

```
/Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/swift/validation-test/Reflection/existentials.swift:60:14: error: expected string not found in input
```

**Comment by moiseev** [comment]
Let's try this...
@swift-ci Please clean smoke test macOS platform

**Comment by dabrahams** [comment]
on Fri May 26 2017, Maxim Moiseev <notifications-AT-github.com> wrote:

> Let's try this...
> @swift-ci Please clean smoke test macOS platform

Likely due to https://bugs.swift.org/browse/SR-4914
-- 
-Dave

**Comment by dabrahams** [comment]
Sorry, I meant https://bugs.swift.org/browse/SR-4608

**Pull request closed without merging**
