### PR TITLE
Root the virtual <compiler-generated> file in the root directory. 

### PR DESCRIPTION
**Pull request by adrian-prantl**
Using CWD gives a false sense of accuracy.

rdar://124233848

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Review by cachemeifyoucan — APPROVED** [review]
LGTM

**Review by cachemeifyoucan — COMMENTED** [review]
Wait, I read the PR wrong. If `<compiler-generated>` is already in empty directory, which does it still get printed as `compile_dir/<compiler-generated>` by dwarfdump?
Is it because <compiler-generated> doesn't have its own `DW_TAG_compile_unit`?
Or maybe it should just be that `dwarfdump` should not print it as if `<compiler-generated>` is from comp_dir?

**Comment by adrian-prantl** [comment]
My understanding is that there is no "empty" directory, rather that all relative paths are relative to `DW_AT_compilation_dir`, which I think makes sense. So if we don't want that to happen, we need to pick an absolute path.

**Comment by cachemeifyoucan** [comment]
Why not tell dwarfdump that `<PATH>` is an absolute path?
Also, if you set comp_dir to `\` for compiler-generated, what will the DWARF generated be? There is still no compile_unit for compiler-generated and the path in DW_at_call_file is still `"<compiler-generated>"`, right? Then dwarfdump might just append the compile_dir from the source file again and this doesn't change anything?

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
> Why not tell dwarfdump that <PATH> is an absolute path?

dwarfdump tries to be as vendor-neutral as possible. The fact that the Swift frontend uses `<>` as identifiers for non-files is just an implementation detail of the Swift frontend.

> Also, if you set comp_dir to / for compiler-generated, what will the DWARF generated be? There is still no compile_unit for compiler-generated and the path in DW_at_call_file is still "<compiler-generated>", right? Then dwarfdump might just append the compile_dir from the source file again and this doesn't change anything?

No, in this case the DIR portion should be `/` and thus DW_AT_comp_dir won't get appended. At least that's the plan :-)

**Pull request merged**
