### PR TITLE
[TF-504] Remove irrelevant fields in _ExecutionContext

### PR DESCRIPTION
**Pull request by burmako**
This PR fixes https://bugs.swift.org/browse/TF-505 by removing the only unused field in _ExecutionContext, namely: loadedPrograms. Unraveling that thread revealed TFEState and _TensorComputation which were unused as well. Also, per chat with @bgogul, I removed all `deprecated_gpe_mode` tests.

### CODE REVIEW

**Comment by burmako** [comment]
@swift-ci Please test tensorflow

**Comment by burmako** [comment]
@swift-ci Please test tensorflow

**Review by bgogul — APPROVED** [review]
Thanks, Eugene!

**Comment by burmako** [comment]
@swift-ci Please test tensorflow

**Comment by burmako** [comment]
@swift-ci Please test tensorflow

**Comment by burmako** [comment]
@swift-ci Please test tensorflow

**Comment by burmako** [comment]
@swift-ci Please clean test tensorflow linux CPU

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Pull request merged**
