### PR TITLE
Add [nonatomic] attribute to all SIL reference counting instructions.

### PR DESCRIPTION
**Pull request by swiftix**
#### What's in this pull request?

Add [nonatomic] attribute to all SIL reference counting instructions.

Support serialization/deserialization, printing and parsing of this attribute.
Update all affected places to explicitly use the new attribute.

THIS IS WORK IN PROGRESS. DO NOT MERGE YET.
#### Resolved bug number: ([SR-249](https://bugs.swift.org/browse/SR-249))

---

Before merging this pull request to apple/swift repository:
- [x] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by swiftix** [comment]
@swift-ci Please smoke test Linux platform

**Comment by swiftix** [comment]
@swift-ci Please smoke test Linux platform

**Comment by swiftix** [comment]
@swift-ci Please smoke test Linux platform

**Comment by swiftix** [comment]
@jckarter Joe, do you mind taking a look? 

This PR contains a lot of almost mechanical changes and boiler plate code to introduce the new `[nonatomic]` attribute for all reference counting SIL instructions. This includes:
- serialization/deserialization of SIL with this attribute
- parsing and printing SIL with this attribute
- Updating all constructors/builders to take an explicit parameter to set this attribute and updating all the relevant call sites to pass this parameter
- propagating the nonatomic flag from a SIL instruction through the IRGen internals down to the places, where the actual reference counting runtime function is picked based on this flag.

**Comment by rjmccall** [comment]
Please make the isAtomic flag an enum class : bool instead of a bare bool, either in IRGen.h or somewhere in AST/SIL.

Do you really need to pass this to the in-memory operations?  You're not doing anything in SIL that would allow IRGen to ever use anything except atomic refcounting for them.

**Comment by swiftix** [comment]
@rjmccall 

> Please make the isAtomic flag an enum class : bool instead of a bare bool, either in IRGen.h or somewhere in AST/SIL.

Sure. Good point!

> Do you really need to pass this to the in-memory operations? You're not doing anything in SIL that would allow IRGen to ever use anything except atomic refcounting for them.

I'm not sure I understand your question. Can you elaborate?

My overall plan is that there will be a SIL optimization pass which marks some of SIL refcounting instructions as `nonatomic`. IRGen then needs to lower them properly. 

So far, I added this "isAtomic" flag to some APIs in a couple of IRGen base classes. As  a result a bunch of classes derived from those had to be adjusted as well to add this additional parameter to their corresponding derived functions.

Do you mean that I changed too many classes in IRGen and some of those changes could be avoided, because they are not necessary?

**Comment by rjmccall** [comment]
I mean that you've changed the SIL ref-counting operations (retain, release, etc.), but not the SIL memory access operations (load, store, copy_addr, destroy_addr); and yet you've added the isAtomic flag to all the IRGen load/store operations.

**Comment by swiftix** [comment]
Based on @rjmccall's comment, I introduced a `enum class Atomicity : bool`, which is now used instead of a simple `bool` flag. This is definitely safer than using a boolean.

In the next update, I'm going to address the comment about the in-memory operations.

**Comment by swiftix** [comment]
@swift-ci Please smoke test Linux platform

**Comment by jckarter** [comment]
Looks good.

**Comment by swiftix** [comment]
I removed the atomicity flag from `destroy` and `loadAsCopy` methods.

But
* `LoadableTypeInfo::copy` is used by visitRetainValueInst in IRGenSIL.cpp
* `LoadableTypeInfo::consume` is used by visitReleaseValueInst in IRGenSIL.cpp

So, I guess `consume` and `copy` methods still need this atomicity parameter, or?

**Comment by swiftix** [comment]
@swift-ci Please smoke test Linux platform

**Comment by rjmccall** [comment]
That makes sense to me.

**Comment by swiftix** [comment]
@rjmccall OK. Thank for reviewing this PR, John!  I'll test and merge.

**Comment by swiftix** [comment]
@swift-ci Please smoke test

**Pull request merged**
