### PR TITLE
[benchmark] De-trivialize OpenClose and Calculator.

### PR DESCRIPTION
**Pull request by milseman**
They're still pretty trivial, but this at least adds a small
constant-folding barrier.

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please smoke test and merge

**Comment by palimondo** [comment]
As a general principle, shouldn’t the changes to benchmarks be… *benchmarked*… in the PR that makes them, so that they don’t pop up as mysterious  regressions/improvements in unrelated PRs? 

I know they will not be reported as such, because we always compare to the current tip of the tree baseline. I just mean for transparency, so that it is easier to attribute the source of change in benchmark baselines correctly.

**Comment by milseman** [comment]
@swift-ci please smoke benchmark

**Comment by milseman** [comment]
@swift-ci please smoke benchmark

**Pull request merged**
