### PR TITLE
[String] Fix crash when given null UBP

### PR DESCRIPTION
**Pull request by milseman**
Resolves [SR-9869](https://bugs.swift.org/browse/SR-9869).

rdar://problem/47864610

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
Asking for reviews from either @atrick or @jrose-apple, as this is mostly about the nullability of UBP's base address. My changes here are mostly about forwarding the null-ness down the stack (rather than crashing at the top), and then special-casing empty UBPs at the bottom.

**Comment by milseman** [comment]
@swift-ci please test

**Comment by jrose-apple** [comment]
👍 I can't see any problems with this approach; even with assertions on it should not do any extra comparisons.

**Comment by atrick** [comment]
The code looks more correct to me now. It looks like you introduced an extra nil comparison but the compiler should remove it considering it has no effect.

**Pull request merged**
