### PR TITLE
[stdlib]String normalization functions (#21026)

### PR DESCRIPTION
**Pull request by lancep**
5.0 cherry pick of https://github.com/apple/swift/pull/21026

### CODE REVIEW

**Comment by lancep** [comment]
@swift-ci please test

**Comment by lancep** [comment]
@swift-ci please benchmark

**Comment by lancep** [comment]
@swift-ci please test

**Comment by lancep** [comment]
@swift-ci please test

**Review by airspeedswift — APPROVED** [review]

**Pull request merged**
