### PR TITLE
Fix OperandOwnership of select_value

### PR DESCRIPTION
**Pull request by meg-gupta**
select_value is supported only on integer types. Fix OperandOwnership to reflect that.

Fixes rdar://101616865

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Review by atrick — COMMENTED** [review]
I'm not sure why there was an ownership error before this fix, or why we can't support guaranteed forwarding. It's nice if we can just enforce trivial types, but the value ownership is still guaranteed:
`CONSTANT_OR_NONE_OWNERSHIP_INST(Guaranteed, SelectValue)`

**Comment by meg-gupta** [comment]
Before this change we returned `OperandOwnership::GuaranteedForwarding` for case value operands, causing ` swift::checkOperandOwnershipInvariants` to return `false` because `select_value` isn't supported in `swift::canOpcodeForwardGuaranteedValues`. Since I learnt `select_value` is intended for integral types only from `SIL.rst`, I am changing it to `trivial` here.

**Review by atrick — APPROVED** [review]
😎

**Comment by meg-gupta** [comment]
@swift-ci smoke test and merge

**Comment by meg-gupta** [comment]
@swift-ci smoke test and merge

**Pull request merged**
