### PR TITLE
IDE: simplify logic from PR#15505 (NFC)

### PR DESCRIPTION
**Pull request by compnerd**
Use a range based loop to simplify the logic.  NFC.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @dcci

**Review by dcci — COMMENTED** [review]
Thanks for the cleanup. This pattern is spread all over the file, I was just lazy and mimicked the logic used everywhere else. For consistency, maybe we should prefer range loops everywhere here? I'm not asking you to do this, unless you want to.

As a meta-point, I and @slavapestov have plans to replace part of this file with TypeDecoder so we weren't particularly obsessed about clean ups.

**Comment by compnerd** [comment]
Sure, I don't mind going through the rest of the file to clean it up.  You know the saying, nothing is as permanent as a temporary change :-).

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Pull request merged**
