### PR TITLE
[TF] Remove all TensorFlow tests.

### PR DESCRIPTION
**Pull request by rxwei**
The TensorFlow module has been moved to [tensorflow/swift-apis](https://github.com/tensorflow/swift-apis), and all tests have been copied. Tests here are not updated against library changes, and are currently blocking updating the checkout hash for tensorflow/swift-apis for v0.4 toolchain builds.

```console
Failing Tests (8):
    Swift(macosx-x86_64) :: TensorFlowRuntime/dataset_1.swift
    Swift(macosx-x86_64) :: TensorFlowRuntime/dynamic_attributes.swift
    Swift(macosx-x86_64) :: TensorFlowRuntime/dynamic_compilation_tensor_group.swift
    Swift(macosx-x86_64) :: TensorFlowRuntime/tensor_array_protocol.swift
    Swift(macosx-x86_64) :: TensorFlowRuntime/tensor_autodiff_runtime.swift
    Swift(macosx-x86_64) :: TensorFlowRuntime/tensor_group.swift
    Swift(macosx-x86_64) :: TensorFlowRuntime/tracer.swift
    Swift(macosx-x86_64) :: TensorFlowRuntime/tracer_tffunc.swift

  Expected Passes    : 28
  Expected Failures  : 1
  Unexpected Failures: 8
```

This PR removes all TensorFlow tests and unblocks things.

Note:
- TensorFlow is being well-tested in tensorflow/swift-apis. Removing tests is okay.
- The only existing test that's not being removed by this PR is `Sema/struct_key_path_iterable.swift`. It should not depend on TensorFlow, so we should update it soon.

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by bgogul** [comment]
Dataset.map relies on the functionality tested by these tests:
```
    Swift(macosx-x86_64) :: TensorFlowRuntime/tracer.swift
    Swift(macosx-x86_64) :: TensorFlowRuntime/tracer_tffunc.swift
```
What are the failures in these tests?

**Comment by rxwei** [comment]
They rely on the old `TenosrArrayProtocol` definition. I thought these were tested in swift-apis. If not, could you move them to swift-apis?

```
********************
Command Output (stderr):
--
/Users/rxwei/Development/Swift/swift-tf-source/swift/test/TensorFlowRuntime/tracer_tffunc.swift:20:8: error: type 'State' does not conform to protocol 'TensorArrayProtocol'
struct State : TensorGroup {
       ^
TensorFlow.TensorArrayProtocol:5:9: note: protocol requires property '_tensorHandles' with type '[_AnyTensorHandle]'; do you want to add a stub?
    var _tensorHandles: [_AnyTensorHandle] { get }
        ^

Command Output (stderr):
--
/Users/rxwei/Development/Swift/swift-tf-source/swift/test/TensorFlowRuntime/tracer.swift:162:10: error: type 'State' does not conform to protocol 'TensorArrayProtocol'
  struct State : _TensorArrayProtocolEnhanced {
         ^
TensorFlow.TensorArrayProtocol:7:5: note: protocol requires initializer 'init(_handles:)' with type '(_handles: C)'; do you want to add a stub?
    init<C>(_handles: C) where C : RandomAccessCollection, C.Element : _AnyTensorHandle
    ^
```

**Review by dan-zheng — APPROVED** [review]
👍 for unblocking `swift-apis`.

**Comment by rxwei** [comment]
@bgogul Since this is blocking v0.4 release, I'm going to merge it now to make progress. I filed [TF-548](https://bugs.swift.org/browse/TF-548) for migrating tests to swift-apis.

**Comment by bgogul** [comment]
> @bgogul Since this is blocking v0.4 release, I'm going to merge it now to make progress. I filed [TF-548](https://bugs.swift.org/browse/TF-548) for migrating tests to swift-apis.

Sounds good.  I closed the new one as it duplicates https://bugs.swift.org/browse/TF-541, which already tracks migration of tests.

**Pull request merged**
