### PR TITLE
[stdlib] Switch Dictionary.subscript(_:default:) to use _modify

### PR DESCRIPTION
**Pull request by airspeedswift**
Getting rid of another addressor.

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
@swift-ci please smoke test

**Comment by airspeedswift** [comment]
@eeckstein @rjmccall any ideas about the regression in DictionarySubscriptDefaultMutation?

**Review by lorentey — COMMENTED** [review]
👍

**Review by lorentey — APPROVED** [review]

**Comment by eeckstein** [comment]
I'll take a look

**Comment by palimondo** [comment]
@eeckstein, @lorentey I was searching through for PRs with benchmarks to see if a regression was caught in `DictionarySubscriptDefaultMutation*` family of benchmarks. I'm seeing 0.5x slowdown between 2018-09-18 and 2018-10-02 on both `O` and `Onone` builds. Have you seen that?

**Comment by lorentey** [comment]
#19664 is an unrelated low-level optimizer issue. We worked around the defaulted subscript regression in #19663.

**Pull request merged**
