### PR TITLE
Use %target-cpu in the tests to support running on Apple Silicon hard…

### PR DESCRIPTION
**Pull request by shahmishal**
…ware

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test Apple Silicon

**Review by DougGregor — APPROVED** [review]

**Comment by shahmishal** [comment]
@swift-ci test Apple Silicon

**Comment by shahmishal** [comment]
@swift-ci test macOS

**Comment by shahmishal** [comment]
@swift-ci test linux

**Pull request merged**
