### PR TITLE
[DO NOT MERGE] Removed PlaygroundQuickLook, CustomPlaygroundQuickLookable, and friends.

### PR DESCRIPTION
**Pull request by cwakamo**
This pull request removes the `PlaygroundQuickLook` enum, the `CustomPlaygroundQuickLookable` protocol, and the runtime pieces which supported `PlaygroundQuickLook.init(reflecting:)`.

This is the implementation of an upcoming [swift-evolution proposal](https://github.com/cwakamo/swift-evolution/blob/playground-quicklook-api-revamp/proposals/nnnn-playground-quicklook-api-revamp.md) which aims to remove these types from the standard library and replace them with a new `CustomPlaygroundDisplayConvertible` protocol in the PlaygroundSupport library.

### CODE REVIEW

**Comment by cwakamo** [comment]
Please test with the following PRs:

apple/swift-corelibs-foundation#1415
apple/swift-xcode-playground-support#20

@swift-ci Please test

**Comment by cwakamo** [comment]
@swift-ci Please test OS X platform

**Comment by cwakamo** [comment]
Please test with the following PRs:

apple/swift-corelibs-foundation#1415
apple/swift-xcode-playground-support#20

@swift-ci Please test OS X platform

**Comment by cwakamo** [comment]
Please test with the following PRs:

apple/swift-corelibs-foundation#1415
apple/swift-xcode-playground-support#20

@swift-ci Please test source compatibility

**Comment by cwakamo** [comment]
Please test with the following PRs:

apple/swift-corelibs-foundation#1415
apple/swift-xcode-playground-support#20

@swift-ci Please test

**Comment by cwakamo** [comment]
Please test with the following PRs:

apple/swift-corelibs-foundation#1415
apple/swift-xcode-playground-support#20

@swift-ci Please test source compatibility

**Comment by cwakamo** [comment]
Please test with the following PRs:

apple/swift-corelibs-foundation#1415
apple/swift-xcode-playground-support#20

@swift-ci Please test source compatibility

**Comment by natecook1000** [comment]
@cwakamo Was this PR superseded by another? The proposal says it was accepted and implemented.

**Comment by cwakamo** [comment]
Closing this PR as we did not end up going in this direction.

**Comment by AnthonyLatsis** [comment]
Proposal: SE-0198

**Pull request closed without merging**
