### PR TITLE
[SR-12725] Diagnose unhandled generic argument mismatch involving FunctionArgument

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
Let's always attempt the fallbacks if we don't handle the locator path specifically.
If even then we can't diagnose, then return false.

cc @xedin :)

Resolves SR-12725.

### CODE REVIEW

**Review by xedin — APPROVED** [review]
LGTM!

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by LucianoPAlmeida** [comment]
@xedin Can we cherry-pick this to 5.3? :)

**Comment by xedin** [comment]
@LucianoPAlmeida Sure! That PR would have to have some additional information in the description though - https://swift.org/blog/5-3-release-process/ (`Pull Requests for Release Branch` bit).

**Pull request merged**
