### PR TITLE
[NFC] Fix occasional @lvalue exposures

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
One example:
```swift
let closure = {
                ^ () -> @lvalue Bool in
  var helper = true
  return helper
}
```

### CODE REVIEW

**Comment by owenv** [comment]
Nice! I think this fix is reasonable, but I wonder if it would be better to strip lvalue-ness during diagnostic formatting instead. That way future diags wouldn't need to worry about handling this case.  For example, we already strip parens and apply some other transformations [here](https://github.com/apple/swift/blob/b32e82c720f6b6a5150fb09c63292f6709947d11/lib/AST/DiagnosticEngine.cpp#L510).

**Comment by AnthonyLatsis** [comment]
@owenv That's so much better, thanks for the tip!

**Comment by CodaFi** [comment]
I don't like the idea of stripping these in the diagnostic engine itself.  It seems like it will mask these LValue-surfacing bugs.

**Comment by AnthonyLatsis** [comment]
> It seems like it will mask these LValue-surfacing bugs.

@CodaFi Do you mean that you're concerned about cases when lvalue-ness itself is the bug instead?

**Review by xedin — CHANGES_REQUESTED** [review]
I think a better alternative would be to add a new parameter `wantRValue` to `FailureDiagnostic::getType` and possibly `FailureDiagnostic::resolveType` just like `ConstraintSystem::getFixedTypeRecursive` has it set up, and default it to`true`. Diagnostics shouldn't generally care about l-valueness and places which do can request l-value type explicitly.

**Comment by AnthonyLatsis** [comment]
@xedin It seems like it would be harder for places that care about lvalue-ness to notice and subsequently spot why they aren't handling lvalue types, and for future `-> Type` methods to follow the convention. Do you think it should be the responsibility of each individual case not to feed an @lvalue type to the engine?

**Comment by xedin** [comment]
@AnthonyLatsis Since there is separation of concerns now between fix and diagnostic and `FailureDiagnostic`'s main job is to emit diagnostics there is no need for it to check specifically for l-value or inout types, even when comparing it should compare object types. So I think it would be best to leave l-value/inout checks to fix and remove that from consideration for diagnostics.

**Comment by AnthonyLatsis** [comment]
I'm a bit confused since the purpose of this PR is to make sure we don't show internal attributes in diagnostic messages, and diagnostic formatting feels like exactly the right place for this kind of stripping (unless it is bad that lvalue types can slip through to diag emission). 

I'll rebase in a moment.

**Comment by AnthonyLatsis** [comment]
@xedin There is a nuance: the  diagnostic at hand (`unable to infer complex closure return type`) is emitted by `FailureDiagnosis` (not `FailureDiagnostic`), and the method(s) responsible for the lvalue output is `getTypeOfExpressionWithoutApplying`. Should I add the `wantsRValue` flag to those as well?

**Comment by xedin** [comment]
@AnthonyLatsis That's actually might not be possible because `FailureDiagnosis` tries to do both find a failure and diagnose it so having access to l-value/inout information is important to it...

**Comment by AnthonyLatsis** [comment]
@xedin Can we smoke test?

**Comment by AnthonyLatsis** [comment]
@xedin If everything looks good, can we test and land this before we run into any new merge conflicts?

**Review by xedin — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
Sorry this actually fell out from my radar...

**Comment by AnthonyLatsis** [comment]
Thanks for sharing your thoughts and reviewing!

**Pull request merged**
