### PR TITLE
swift-reflection-dump: Virtualize logical-to-physical address mapping. 

### PR DESCRIPTION
**Pull request by jckarter**
Instead of copying the entire object file and moving around its sections to make an approximate
representation of its mapped state, use the memory-mapped buffer from `llvm::ObjectFile`, and
deal with non-contiguous logical mappings entirely in readBytes.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test Windows

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test Windows

**Comment by jckarter** [comment]
@swift-ci Please test Windows

**Comment by alexshap** [comment]
@jckarter, many thanks for these improvements, just one request - let me test / finish https://github.com/apple/swift/pull/26419 - I have already rebased multiple times, but CI is kinda slow in my experience, so every rebase introduces more waiting time

**Comment by jckarter** [comment]
@swift-ci Please test Windows

**Comment by jckarter** [comment]
@alexshap This should be the last of the big changes in this area I need to make for the time being.

**Comment by alexshap** [comment]
@jckarter - maybe I can commit that PR first (when CI finishes successfully) ?

**Comment by jckarter** [comment]
@alexshap OK.

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test Windows

**Comment by jckarter** [comment]
@swift-ci Please test Windows

**Comment by jckarter** [comment]
@swift-ci Please test Windows

**Comment by jckarter** [comment]
@compnerd Hm, I'm getting this on the Windows bot:

```
FAILED: libdispatch-prefix/src/libdispatch-stamp/libdispatch-configure 
cmd.exe /C "cd /D S:\swift\libdispatch-prefix\src\libdispatch-build && "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -DCMAKE_AR= -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=S:/llvm/bin/clang-cl.exe "-DCMAKE_C_FLAGS=/DWIN32 /D_WINDOWS /Zc:inline /Zc:strictStrings /Oi /W4 -wd4141 -wd4146 -wd4180 -wd4244 -wd4258 -wd4267 -wd4291 -wd4345 -wd4351 -wd4355 -wd4456 -wd4457 -wd4458 -wd4459 -wd4503 -wd4624 -wd4722 -wd4800 -wd4100 -wd4127 -wd4512 -wd4505 -wd4610 -wd4510 -wd4702 -wd4245 -wd4706 -wd4310 -wd4701 -wd4703 -wd4389 -wd4611 -wd4805 -wd4204 -wd4577 -wd4091 -wd4592 -wd4319 -wd4709 -wd4324 -w14062 -we4238" -DCMAKE_CXX_COMPILER=S:/llvm/bin/clang-cl.exe "-DCMAKE_CXX_FLAGS=/GS- /Oy /Zc:inline /Zc:strictStrings /Oi /Zc:rvalueCast /W4 -wd4141 -wd4146 -wd4180 -wd4244 -wd4258 -wd4267 -wd4291 -wd4345 -wd4351 -wd4355 -wd4456 -wd4457 -wd4458 -wd4459 -wd4503 -wd4624 -wd4722 -wd4800 -wd4100 -wd4127 -wd4512 -wd4505 -wd4610 -wd4510 -wd4702 -wd4245 -wd4706 -wd4310 -wd4701 -wd4703 -wd4389 -wd4611 -wd4805 -wd4204 -wd4577 -wd4091 -wd4592 -wd4319 -wd4709 -wd4324 -w14062 -we4238 /we4062 /wd4068 /permissive- -DOBJC_OLD_DISPATCH_PROTOTYPES=0" -DCMAKE_MAKE_PROGRAM=C:/PROGRA~2/MICROS~1/2017/COMMUN~1/Common7/IDE/COMMON~1/MICROS~1/CMake/Ninja/ninja.exe -DCMAKE_INSTALL_PREFIX=S:/swift/libdispatch-prefix "-DCMAKE_LINKER=C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/link.exe" -DCMAKE_RANLIB= -DCMAKE_TOOLCHAIN_FILE= -DBUILD_SHARED_LIBS=YES -DENABLE_SWIFT=NO -DENABLE_TESTING=NO -GNinja c:\jenkins\workspace\swift-PR-windows\swift-corelibs-libdispatch && "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E touch S:/swift/libdispatch-prefix/src/libdispatch-stamp/libdispatch-configure"
CMake Error at CMakeLists.txt:2 (cmake_minimum_required):
  CMake 3.15.1 or higher is required.  You are running version
  3.12.18081601-MSVC_2


-- Configuring incomplete, errors occurred!
```

**Comment by jckarter** [comment]
@swift-ci Please test Linux

**Comment by jckarter** [comment]
@swift-ci Please test Windows

**Comment by jckarter** [comment]
Looks like I got past the CMake issue this time. Now I'm seeing the same Driver failures on Windows as before.

**Pull request merged**
