### PR TITLE
MandatoryPerformanceOptimizations: perform function signature optimization to remove metatype arguments

### PR DESCRIPTION
**Pull request by eeckstein**
Generic specialization already takes care of removing metatype arguments of generic functions.
But sometimes non-generic functions have metatype arguments which must be removed.
We need handle this case with a function signature optimization.

This enables, for example, to use `OptionSet` in embedded swift.

rdar://121206953

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Review by atrick — COMMENTED** [review]
Briefly scanned. ✅

**Pull request merged**
