### PR TITLE
[TypeChecker] Mark perf test-case for rdar://problem/22282851 as fast

### PR DESCRIPTION
**Pull request by xedin**
Recent changes to contraction of the closure argument/parameter type
variables resulted in speed up in type-checker performance which resolved
one of existing "slow" test-cases.

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please smoke test and merge

**Comment by rudkx** [comment]
Not sure which builds we're running for those branches, but if it's not failing there we're probably fine without it (unless of course someone in the future adds those builds...).

**Comment by xedin** [comment]
Alright, I'll cherry-pick into 5.0 only for now, and if we ever need it will cherry-pick to 4.1 as well.

**Pull request merged**
