### PR TITLE
Disable lexical-lifetimes with copy-propagation.

### PR DESCRIPTION
**Pull request by nate-chandler**
If -disable-copy-propagation is passed, just emit lexical diagnostic markers but do not enable lexical lifetimes.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by atrick — APPROVED** [review]
Thanks!

**Comment by nate-chandler** [comment]
@swift-ci please clean test linux platform

**Comment by nate-chandler** [comment]
@swift-ci please clean test macos platform

**Comment by nate-chandler** [comment]
@swift-ci please clean test linux platform

**Comment by nate-chandler** [comment]
@swift-ci please clean test macos platform

**Comment by nate-chandler** [comment]
@swift-ci please clean test linux platform

**Pull request merged**
