### PR TITLE
[Runtime] swift_demangle: Update buffer size after copying

### PR DESCRIPTION
**Pull request by Azoy**
Previously this would update buffer size before copying if the given buffer size was smaller than the result size. This lead to writing past the given buffer rather than truncating like the comment states. Update it after copying so that we get truncation along with error indication.

cc: @jckarter @rjmccall

### CODE REVIEW

**Comment by compnerd** [comment]
@Azoy, can you explain how we would write past the buffer?  `strlcpy` is used to explicitly avoid that situation.  We would be truncating properly previously.

**Comment by compnerd** [comment]
Wow, that is subtle.  Would you mind adding a test case for this?

**Comment by jckarter** [comment]
@swift-ci Please test

**Review by rjmccall — APPROVED** [review]
Yikes.

**Comment by jckarter** [comment]
@swift-ci Please test OS X

**Pull request merged**
