### PR TITLE
Workaround for difference in behavior between optimizer and runtime understanding of casts (2.2)

### PR DESCRIPTION
**Pull request by slavapestov**
@rudkx Is this right?

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@tkremenek Note that swift-ci Please test doesn't actually run with optimizations, which is why this slipped through in the first place. It would be great if we could fix that.

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by jckarter** [comment]
Yeah, running without optimization bit me too recently.

**Comment by slavapestov** [comment]
@tkremenek Is the 'Please' optional now? :)

**Comment by jckarter** [comment]
Maybe it has INTERCAL semantics, where it rejects your request if you don't use the right percentage of times.

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@tkremenek I'll do one final test run of this and my other 2.2.1 PRs with check-swift-all-optimized -- will update here when its done.

**Comment by rudkx** [comment]
@slavapestov Yes, that's the right _semantic to use to disable specialization of that function (and any optimization within the function).

**Comment by slavapestov** [comment]
@tkremenek Can you merge this one please?

**Pull request merged**
