### PR TITLE
[Swift 5.0] Cherry-pick swiftSyntax related changes

### PR DESCRIPTION
**Pull request by ahoppen**
I am going to gather some more swiftSyntax related changes that I'd like to cherry-pick into Swift 5.0 here.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by tkremenek** [comment]
CC @akyrtzi 

This PR was open before the final `swift-5.0-branch` was cut.  If this was in `master` as of November 16, 2018, then this change was pulled into the final re-branching of Swift 5.  Closing as this PR was opened against an older version of this branch.  If this change should be pulled in, please open a new PR.

**Pull request closed without merging**
