### PR TITLE
[test] Update APINotes, Serialization, and PrintAsObjC tests for Swift 3 removal

### PR DESCRIPTION
**Pull request by jrose-apple**
Mostly done with find/replace to compare Swift 4 and Swift 5 instead of Swift 3 and Swift 4. There are some interesting changes here because API notes for 4 also apply to 3 unless otherwise specified, and 4.2 is the next version after 4 rather than 5, but everything should still be correct and testing useful stuff.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Review by slavapestov — APPROVED** [review]
Thanks!

**Comment by jrose-apple** [comment]
More LLDB test flakery. I'll double-check that we have a bug tracking this.

@swift-ci Please test Linux

**Comment by jrose-apple** [comment]
Filed [SR-8245](https://bugs.swift.org/browse/SR-8245).

**Comment by jrose-apple** [comment]
Same issue. One more try, then I'll give up and wait for the LLDB team.

@swift-ci Please test Linux

**Pull request merged**
