### PR TITLE
ClangImporter: Fix diagnostics for NS* prefix stripping from generic types

### PR DESCRIPTION
**Pull request by slavapestov**
Radar: rdar://problem/26206263

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@DougGregor Can you please review?

**Comment by tkremenek** [comment]
@swift-ci test linux

**Comment by DougGregor** [comment]
Weird use of SubstitutedType, but it makes perfect sense to do this for Swift 3 preview 1. Thanks!

**Pull request merged**
