### PR TITLE
[pruned-liveness] Teach PrunedLiveBlocks how to handle liveness for multiple bits.

### PR DESCRIPTION
**Pull request by gottesmm**
This is in preparation for landing a larger FieldSensitivePrunedLiveness (I am chopping off a larger part of that work).

Importantly, by committing this separately, I can use the current PrunedLiveness implementation to validate this larger piece of work.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Review by atrick — APPROVED** [review]
Makes sense for testing. As we discussed, the lightweight utility really should use neither a SmallVector nor a DenseMap. So we'll need to fix that later.

**Comment by gottesmm** [comment]
@swift-ci test macOS platform

**Pull request merged**
