### PR TITLE
Fix a warning in LICM in release builds

### PR DESCRIPTION
**Pull request by shajrawi**
rdar://problem/43623829

### CODE REVIEW

**Comment by shajrawi** [comment]
@swift-ci Please smoke test and merge

**Comment by shajrawi** [comment]
@swift-ci Please smoke test Linux

**Comment by shajrawi** [comment]
@swift-ci Please smoke test Linux

**Comment by shajrawi** [comment]
@swift-ci Please smoke test and merge

**Comment by shajrawi** [comment]
@swift-ci Please smoke test OS X

**Comment by shahmishal** [comment]
@swift-ci Please smoke test Linux

**Pull request merged**
