### PR TITLE
[swift-5.0-branch] Cherry pick TBDGen changes

### PR DESCRIPTION
**Pull request by harlanhaskins**
This patch cherry-picks most of the TBDGen changes, including adoption of TAPI v3, into swift-5.0-branch.

rdar://34560882

### CODE REVIEW

**Comment by harlanhaskins** [comment]
@swift-ci please test

**Comment by harlanhaskins** [comment]
@swift-ci please test

**Comment by jrose-apple** [comment]
The current swift-5.0-branch is mostly just being used for some Apple-internal processes right now. There'll be another rebranch from master before the release is done.

**Comment by harlanhaskins** [comment]
@swift-ci please test

**Comment by harlanhaskins** [comment]
Foundation failure seems unrelated.

@swift-ci please test Linux platform

**Comment by harlanhaskins** [comment]
:boat:

**Pull request merged**
