### PR TITLE
[Diagnostics] SR-11419 Diagnose protocol stub note in editor mode only

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
Check for editor mode when emitting stub diagnostic stub note.
Fixing all the tests where there was **no** `-diagnostics-editor-mode`

Resolves [SR-11419](https://bugs.swift.org/browse/SR-11419).

cc @CodaFi :)

### CODE REVIEW

**Comment by CodaFi** [comment]
Thanks!

@swift-ci please smoke test

**Comment by LucianoPAlmeida** [comment]
@CodaFi can you kick the CI again? :)

**Comment by theblixguy** [comment]
@swift-ci please smoke test

**Comment by LucianoPAlmeida** [comment]
Thank's @theblixguy :)

**Comment by CodaFi** [comment]
⛵️

**Pull request merged**
