### PR TITLE
Allow initialized let/var declarations in function builders.

### PR DESCRIPTION
**Pull request by DougGregor**
Introduce support for initialized let/var declarations within function
builder closures, e.g.,

    let (a, b) = c()

We generate constraints for the declarations as elsewhere, but the types of
the declared variables (a and b in this case) are bound to the type of the
pattern by one-way constraints, to describe the flow of type information
through the closure.

We generate constraints for the declarations as elsewhere, but the types of
the declared variables (a and b in this case) are bound to the type of the
pattern by one-way constraints, to describe the flow of type information
through the closure.

Implements rdar://problem/57330696.

### CODE REVIEW

**Comment by DougGregor** [comment]
The first two commits are from https://github.com/apple/swift/pull/29801; only the third commit is needed here.

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Review by xedin — COMMENTED** [review]
Looks great!

**Pull request merged**
