### PR TITLE
Removing more calls to ValueDecl::getType()

### PR DESCRIPTION
**Pull request by slavapestov**
Almost ready to push it down to VarDecl.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by gparker42** [comment]
This broke two iOS tests. Reverting in #6019.

**Comment by gparker42** [comment]
Never mind, Slava pushed followups before my revert. We'll just fix it elsewhere.

**Pull request merged**
