### PR TITLE
[gardening] "[ a, b ]" → "[a, b]", "\t" → " ", "are are" → "are"

### PR DESCRIPTION
**Pull request by practicalswift**
#### What's in this pull request?

`[ a, b ]` → `[a, b]`, `\t` → ` `,`are are`→`are`
#### Resolved bug number: –

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by gribozavr** [comment]
@practicalswift Sorry, but I'm not a fan of the brackets change.  We don't have a consistent agreed-upon style here for Swift.  And we have a lot of code that has spaces in array literals (maybe even more than code that does not have spaces).

**Comment by practicalswift** [comment]
@gribozavr Ah, okay, sorry about that.

Am I correct that `[a, b]` is preferred over `[ a, b ]` for the C++ code in the repo. Judging from the number of `[a, b]` vs. `[ a, b ]` prior to my cleaning it sure looks like `[a, b]` is preferred :-)

**Comment by gribozavr** [comment]
C++ code is covered by the LLVM guidelines.  C++ code can only use square brackets for subscripting (not array literals), and since we don't use fancy operator overloading, there is only ever one element like this `xs[i]`, which does not use spaces.

For Python, we conform to PEP-8.

For Swift, we don't have a rule.

**Comment by practicalswift** [comment]
@gribozavr OK, thanks for clarifying! Will adjust accordingly :-)

**Pull request merged**
