### PR TITLE
Dictionary decodable fix

### PR DESCRIPTION
**Pull request by linqingmo**
Fix two misspellings.

### CODE REVIEW

**Comment by CodaFi** [comment]
Good catch.  Can you please add a test too?

**Comment by CodaFi** [comment]
@swift-ci please test

**Comment by linqingmo** [comment]
@CodaFi Thanks for adding test.

**Comment by itaiferber** [comment]
@linqingmo Good catch; this is some embarrassing copy-pasta on my part. LGTM.

**Review by itaiferber — APPROVED** [review]

**Comment by linqingmo** [comment]
@itaiferber my pleasure.😀

**Pull request merged**
