### PR TITLE
Fix witness thunk archetypes

### PR DESCRIPTION
**Pull request by slavapestov**
Work in progress.

@swiftix with this patch, the generic inliner no longer crashes, but instead compiling Swift.o appears to hang. I'll keep looking.

### CODE REVIEW

**Comment by swiftix** [comment]
@slavapestov Interesting. It is either  an infinite loop somewhere or it just inlines too much, bloats the code and make it look like it takes forever.

**Comment by slavapestov** [comment]
My patch has a few of its own test failures too. I'm about to push a fixed version.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please clean test Linux

**Comment by slavapestov** [comment]
@swift-ci Please clean test Linux

**Comment by slavapestov** [comment]
@erg Any idea why the Linux build is failing? Looks like swiftpm is not being rebuilt.

**Comment by swiftix** [comment]
@slavapestov Thanks, Slava! It works. I can compile the stdlib with it.

**Comment by erg** [comment]
@slavapestov It's an incremental build and the source files don't change so nothing rebuilds. It would be fine, except the compiler changed between runs and the version number on the compiled files is too low, so it fails. We don't have a mechanism in place to recompile everything if the compiler changes yet.

**Pull request merged**
