### PR TITLE
[sil-opaque-values] Allow open_existential_addr to be loaded (post-ownership).

### PR DESCRIPTION
**Pull request by atrick**

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci smoke test and merge.

**Comment by gottesmm** [comment]
@atrick I think this would make more sense in SIL than in SILOptimizer. It is really checking behavior of the SIL verifier than an optimization.

**Comment by gottesmm** [comment]
your thoughts?

**Comment by gottesmm** [comment]
(feel free to move it afterwards if you agree)

**Pull request merged**
