### PR TITLE
Fold dynamic_method into objc_method

### PR DESCRIPTION
**Pull request by slavapestov**
Follow-up to https://github.com/apple/swift/pull/12260. Since `dynamic_method` and `objc_method` now have the same IRGen lowering; the only difference remaining is SIL verifier invariants. We can merge the SIL verifier checks together and remove `dynamic_method` altogether.

The next step here is to refactor SILGen to use `objc_method` for Objective-C protocol method calls as well, removing the volatile bit from `witness_method` and simplifying its IRGen lowering.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by DougGregor** [comment]
SwiftyJSON is using `_Incrementable`. I don't think that's you :) 

/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite/project_cache/Kitura/.build/checkouts/SwiftyJSON.git--6955445084174387031/Source/SwiftyJSON.swift:406:26: error: use of undeclared type '_Incrementable'
public struct JSONIndex: _Incrementable, Equatable, Comparable {
                         ^~~~~~~~~~~~~~

**Pull request merged**
