### PR TITLE
[stdlib] Random unification

### PR DESCRIPTION
**Pull request by Azoy**
This is the implementation for apple/swift-evolution#760

### CODE REVIEW

**Comment by Azoy** [comment]
cc: @airspeedswift Nate had an idea in the previous PR to constrain the shuffle implementation for `MutableCollection` to `RandomAccessCollection` due to complexity issues `MutableCollection` could have.
```swift
extension MutableCollection where Self: RandomAccessCollection {}
```

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
@Azoy can you rebase? Looks like you're still based off of a November master. Also if you could squash incremental commits if they were just changing the implementation from feedback. Thanks!

**Pull request closed without merging**
