### PR TITLE
[Docs] Differentiable programming manifesto.

### PR DESCRIPTION
**Pull request by dan-zheng**
We have completed a comprehensive proposal (in Swift Evolution format) for the differentiable programming feature we’ve been incubating over the last 1.5 years. We’ve gone over many iterations on the feature design, and have partially completed the implementation. Now we are ready to start a discussion on Swift Evolution, specifically on upstreaming and standardizing the feature.

Since this proposal is overly long (~60 pages), we hope to start by merging it into the `docs/` directory in apple/swift, and draft bite-sized proposals that contain references to the mega-proposal.

Richard, Dan, Marc and Bart

### CODE REVIEW

**Review by rxwei — APPROVED** [review]
Great!

**Review by lattner — APPROVED** [review]
LGTM, but please wait for someone on the Apple side to approve this as well.  Thanks!

**Comment by rxwei** [comment]
I've renamed the document to "Differentiable Programming Manifesto". Now awaiting approval.

**Comment by rxwei** [comment]
@swift-ci please smoke test

**Comment by rxwei** [comment]
@DougGregor

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
