### PR TITLE
Sink SanitizeExpr down into code completion

### PR DESCRIPTION
**Pull request by slavapestov**
This sits on top of https://github.com/apple/swift/pull/32561.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@horla I'm having trouble with PR testing. Only the final two commits are new.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
Thank you!

**Pull request merged**
