### PR TITLE
Sema: Fix conformance checking for 'rethrows' protocol requirements

### PR DESCRIPTION
**Pull request by slavapestov**
A protocol requirement in a non-'@rethrows' protocol cannot be
witnessed by a rethrows-via-conformance witness, because there
is not enough information at a potential call site of the
protocol requirement to determine if the witness uses a
rethrows source or not.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Review by phausler — APPROVED** [review]
good catch! these changes look solid to me and from what I can tell it works just fine from the perspective of AsyncSequence; we should however watch out on the unit tests to make sure they pass.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Pull request merged**
