### PR TITLE
[CSBindings] Instead of using a flag track constraints which delay type variable

### PR DESCRIPTION
**Pull request by xedin**
- Keep track of all constraints which caused a particular type variable to
   be de-prioritized.

- Convert a property to a method which would determine whether
   given set of potential bindings is "fully bound" and has to
   be delayed until certain constraints are simplified.

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please clean test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Review by hborla — APPROVED** [review]
LGTM! I really like the naming and documentation changes you've made - it makes the code a lot easier to understand.

**Comment by xedin** [comment]
Thank you!

**Pull request merged**
