### PR TITLE
[embedded] Add back lazy collection operations, collection diffing and StaticBigInt to Embedded Stdlib

### PR DESCRIPTION
**Pull request by kubamracek**
Straightforward enablement of a bunch of files to the Embedded stdlib, which seem to be excluded for no reason:

- DiscontiguousSlice.swift
- DropWhile.swift
- Filter.swift
- FlatMap.swift
- Flatten.swift
- Join.swift
- Map.swift
- PrefixWhile.swift
- CollectionDifference.swift
- Diffing.swift
- StaticBigInt.swift
- UnfoldSequence.swift

rdar://139729059
rdar://139729075
rdar://139729137

### CODE REVIEW

**Comment by rauhul** [comment]
thanks!

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by benrimmington** [comment]
`StaticBigInt` will be limited by issue #75652.

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
> `StaticBigInt` will be limited by issue #75652.

Good point. Let's use https://github.com/swiftlang/swift/issues/75652 to track that problem. (The suggestion to increase the bitWidth sounds reasonable to me.)

**Review by phausler — APPROVED** [review]
Seems reasonable to me given the current status of embedded

**Pull request merged**
