### PR TITLE
Context descriptors

### PR DESCRIPTION
**Pull request by jckarter**
Replacing today's nominal type descriptors with a hierarchy of context descriptors, with more efficient encoding of name information and more precise description of generic contexts.

swift-dev discussion: https://lists.swift.org/pipermail/swift-dev/Week-of-Mon-20171113/005971.html

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
Please test with the following pull request:
apple/swift-xcode-playground-support#19

@swift-ci Please test macOS

**Comment by jckarter** [comment]
@swift-ci Please test source compatibility

**Comment by graydon** [comment]
Holy Toledo!

**Comment by jckarter** [comment]
Please test with the following pull request:
apple/swift-xcode-playground-support#19

@swift-ci Please test macOS

**Comment by jckarter** [comment]
Please test with the following pull request:
apple/swift-xcode-playground-support#19

@swift-ci Please test

**Comment by jrose-apple** [comment]
It looks like this has regressed the printing of local types. See discussion in [SR-6787](https://bugs.swift.org/browse/SR-6787).

**Comment by jckarter** [comment]
It *changes* it; I wouldn't say it's a regression.

**Pull request merged**
