### PR TITLE
ASTMangler: Fix mangling of SILFunctionType with @pack conventions

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes rdar://problem/107151125.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Review by adrian-prantl — COMMENTED** [review]
Does that affect any of the LLDB unit tests that hardcode function names? I guess we'll find out :-)

**Comment by slavapestov** [comment]
@adrian-prantl The test already passed and merged in the 5.9 branch. The main branch PR was held up by an unrelated CI issue.

**Pull request merged**
