### PR TITLE
AST: Remove OpenedArchetypeType::getOpenedExistentialType()

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
Clients can explicitly ask for the opened existential type on the archetype's generic environment, or use `getExistentialType` to obtain a specific archetype's existential bounds .

### CODE REVIEW

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test macOS

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Review by slavapestov — APPROVED** [review]

**Comment by AnthonyLatsis** [comment]
@slavapestov That was quick, thank you!

**Comment by AnthonyLatsis** [comment]
@swift-ci please clean smoke test macOS

**Pull request merged**
