### PR TITLE
[SE-0274] Stage in #filePath

### PR DESCRIPTION
**Pull request by beccadax**
To give users of `#file` a brief window to transition if necessary, we are first adding `#filePath` without changing `#file`’s behavior. This commit makes that change.

Fixes <rdar://problem/58586626>.

### CODE REVIEW

**Comment by brentdax** [comment]
@swift-ci please test

**Comment by brentdax** [comment]
@swift-ci please test

**Review by jckarter — APPROVED** [review]
Looks good.

**Comment by brentdax** [comment]
@swift-ci please smoke test

**Review by jckarter — APPROVED** [review]
Makes sense.

**Comment by brentdax** [comment]
@swift-ci please test

**Comment by brentdax** [comment]
@swift-ci please test Windows platform

**Comment by brentdax** [comment]
@swift-ci please test Linux platform

**Pull request merged**
