### PR TITLE
[SIL] Doc'd store_unowned and load_unowned.

### PR DESCRIPTION
**Pull request by nate-chandler**
Address the todo from 2016.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please smoke test

**Comment by nate-chandler** [comment]
@swift-ci please smoke test windows platform

**Comment by nate-chandler** [comment]
@swift-ci please test windows platform

**Comment by nate-chandler** [comment]
@swift-ci please test windows platform

**Comment by nate-chandler** [comment]
@swift-ci please smoke test windows platform

**Review by atrick — APPROVED** [review]
LGTM

**Pull request merged**
