### PR TITLE
Revert "build: remove `SWIFT_NEED_EXPLICIT_LIBDISPATCH` (NFC)"

### PR DESCRIPTION
**Pull request by davezarzycki**
This reverts commit 18570c723f7369da72566a81ec906d5e534f7ef6 (pull request #28338) because it breaks building on platforms that do not want or need libdispatch.

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by davezarzycki** [comment]
@swift-ci please test

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by davezarzycki** [comment]
I really hope that I didn't miss a policy change, but I don't think I did. Reverting

**Comment by compnerd** [comment]
@davezarzycki - bleh, there was a stupid mistake in the patch that somehow made it through the build tests.  I had a fix for it in #28360 but could not get it merged due to the CI being down.

**Pull request merged**
