### PR TITLE
Correct a Most Vexing Parse in -asserts Builds

### PR DESCRIPTION
**Pull request by CodaFi**
This thing looks like a function prototype otherwise.

### CODE REVIEW

**Review by davidungar — APPROVED** [review]
I ran into the same thing; thanks for putting up this PR.

**Comment by CodaFi** [comment]
@swifft-ci smoke test

**Comment by CodaFi** [comment]
@swifft-ci smoke test

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Review by DougGregor — APPROVED** [review]

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
