### PR TITLE
[Serialization] Serialize Clang types for non-modular headers.

### PR DESCRIPTION
**Pull request by varungandhi-apple**
Since frameworks have modularized headers, this is only a problem for app targets which use non-modular headers. Such an app target's swiftmodule may be used by a test module. If we have an `@convention(c)` function type with a non-trivial C type in such an app target, it is probably safe to serialize it optimistically and hope that the test target imports the same headers.

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
@swift-ci test

**Comment by varungandhi-apple** [comment]
Ah, the test needs to be Darwin-only.

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test

**Comment by varungandhi-apple** [comment]
This causes a test failure when `UseClangFunctionTypes` is turned on, because we test for this behavior.

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test

**Review by rjmccall — APPROVED** [review]
Well, if this just magically works, ok.

**Pull request merged**
