### PR TITLE
More resilient vtable plumbing

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@shahmishal The source compat test suite failure looks unrelated to my change - is it an infrastructure issue after the beta 6 upgrade?

**Comment by shahmishal** [comment]
@lplarson Have you seen this before? 

```
fatal error: Must be implmented by subclasses: file /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite/swiftpm/Sources/Commands/SwiftTool.swift, line 371
```

**Comment by ematejska** [comment]
@swift-ci please test

**Comment by ematejska** [comment]
@swift-ci Please test source compatibility

**Comment by ematejska** [comment]
@swift-ci please smoke test

**Comment by slavapestov** [comment]
@shahmishal @lplarson Sorry, it's a bug in my code. Never mind

**Comment by slavapestov** [comment]
@swift-ci Please clean test Linux

**Comment by slavapestov** [comment]
@swift-ci Please test Linux

**Comment by slavapestov** [comment]
@swift-ci Please test macOS

**Comment by slavapestov** [comment]
@swift-ci Please test Linux

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Pull request merged**
