### PR TITLE
[NameLookup ASTScope] Latest experimental ASTScope code, off by default.

### PR DESCRIPTION
**Pull request by davidungar**
Update master with the latest (experimental) ASTScope code, still disabled-by-default.

### CODE REVIEW

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Comment by davidungar** [comment]
@swift-ci please smoke test os x platform

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Comment by davidungar** [comment]
@swift-ci Please Test Source Compatibility Debug

**Comment by compnerd** [comment]
This may have regressed the Windows test suite: https://dev.azure.com/compnerd/windows-swift/_build/results?buildId=5940&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=2fdae087-0aee-589c-2ab0-2b8fc539478d&l=179

**Pull request merged**
