### PR TITLE
[master] Move SwiftSyntax to its own repository

### PR DESCRIPTION
**Pull request by ahoppen**
This PR sets up the infrastructure to build SwiftSyntax from its own repository. For this it does:
- Add the new `swift-syntax` repository to `update-checkout`
- Add a `build-script` option to build and test `swift-syntax`
- Update the build presets to test SwiftSyntax when running `@swift-ci Please test`
- Remove SwiftSyntax from this repository

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by harlanhaskins — APPROVED** [review]
LGTM, pending passing on CI.

This shouldn’t break folks who haven’t cloned swift-syntax, right? They just won’t pass `—build-swiftsyntax`

**Comment by ahoppen** [comment]
The flag to pass to `build-script` is `--swiftsyntax` but yeah, that should be the case. I'll double check locally.

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
What's the rationale for moving it out? Are we still going to build it in CI?

**Comment by ahoppen** [comment]
We are still going to build it as part of CI if you do `@swift-ci Please test`.

There are multiple reasons to move this out:
- If it is a SwiftPM project, people can depend on it while still using the default Xcode toolchain which doesn't include SwiftSyntax.
- SwiftSyntax can now depend on `corelibs-foundation` which will make it a lot easier to port to Linux. Otherwise the compiler project would have needed to depend on Foundation which was not desirable.
- The package should be more discoverable and have a lower burden to contribute to this way.
- If the development is a little bit more separate from the compiler we should be able to accept minor improvements to the Swift side more easily that would otherwise be blocked by a locked down release branch.

**Comment by ahoppen** [comment]
Fixed the issue that caused this in the swift-syntax repo.

@swift-ci Please test

**Comment by shahmishal** [comment]
@swift-ci build toolchain

**Comment by shahmishal** [comment]
@swift-ci Please Build Toolchain

**Review by akyrtzi — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please test

**Pull request merged**
