### PR TITLE
[BuildSystem] Stop building for i386-watch-simulator

### PR DESCRIPTION
**Pull request by cyndyishida**
In Xcode16 it is not supported.

resolves: rdar://138924057

### CODE REVIEW

**Comment by cyndyishida** [comment]
@swift-ci  please test

**Comment by cyndyishida** [comment]
@swift-ci please test

**Comment by cyndyishida** [comment]
@swift-ci please test

**Review by etcwilde — APPROVED** [review]

**Comment by cyndyishida** [comment]
@egorzhdan Do you know if there are additional changes needed for disabling i386-watch-sim for the `Cxx` & `Cxxstdlib` modules?

**Comment by cyndyishida** [comment]
@swift-ci please test

**Comment by cyndyishida** [comment]
Going to merge this, the macOS log shows builds of x86_64-watch-sim and nothing for `i386`

**Comment by egorzhdan** [comment]
@cyndyishida there shouldn't be any extra changes required for Cxx and CxxStdlib, removing i386 from `SUPPORTED_WATCHOS_SIMULATOR_ARCHS` should be enough

**Pull request merged**
