### PR TITLE
[5.4] Apple Silicon Test Corrections

### PR DESCRIPTION
**Pull request by CodaFi**
Contains

* https://github.com/apple/swift/pull/36273
* https://github.com/apple/swift/pull/36271
* https://github.com/apple/swift/pull/36269
* https://github.com/apple/swift/pull/36262

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci please test Apple Silicon macOS Platform

**Comment by CodaFi** [comment]
@shahmishal This is the new set of failed tests

```
14:42:44 Failed Tests (7):
14:42:44   Swift(macosx-arm64) :: execution/arc_36509461.swift
14:42:44   Swift(macosx-arm64) :: compiler_scale/scale_neighbouring_getset.gyb
14:42:44   Swift(macosx-arm64) :: Sanitizers/symbolication.swift
14:42:44   Swift(macosx-arm64) :: Sanitizers/asan_recover.swift
14:42:44   Swift(macosx-arm64) :: Sanitizers/asan.swift
14:42:44   Swift(macosx-arm64) :: Sanitizers/asan-globals-overwrite.swift
14:42:44   Swift(macosx-arm64) :: Interpreter/indirect_enum.swift
```

**Comment by shahmishal** [comment]
Going to merge this change to unblock Apple Silicon testing.

**Pull request merged**
