### PR TITLE
[4.2][stdlib] update the fatal error message displayed during invalid int-to-int conversions (<rdar://39542040>) (#16480)

### PR DESCRIPTION
**Pull request by ravikandhadai**

### CODE REVIEW

**Comment by ravikandhadai** [comment]
@moiseev Hi Max, as mentioned in the radar, I cherry-picked the fix on to the swift 4.2 branch.

**Comment by ravikandhadai** [comment]
@swift-ci please smoke test

**Comment by moiseev** [comment]
@swift-ci Please test

**Review by moiseev — APPROVED** [review]
LGTM

**Pull request merged**
