### PR TITLE
Break docs/ABI.rst into a subdirectory of documents.

### PR DESCRIPTION
**Pull request by jckarter**
There's a lot of information here for one document, so I think another layer of organization is warranted. This commit only breaks up the existing content by heading, it does not update or otherwise change any content.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Comment by jckarter** [comment]
@rjmccall @milseman @atrick Any objections?

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Comment by atrick** [comment]
👍 Thank you.

**Comment by bob-wilson** [comment]
I'm seeing a failure on master-next after this change:

Warning, treated as error:
/Users/bwilson/local/master-next/src/oss/swift/docs/ABI/TypeMetadata.rst:149: ERROR: Unknown target name: "existential container layout".

**Comment by jckarter** [comment]
@bob-wilson Thanks, https://github.com/apple/swift/pull/11278 should address that.

**Comment by CodaFi** [comment]
One more, #11280

**Pull request merged**
