### PR TITLE
Fix an issue found with UBSAN where we call walk() with a nullptr for…

### PR DESCRIPTION
**Pull request by rudkx**
… 'this'.

Fixes: rdar://problem/43657456

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by shahmishal** [comment]
@swift-ci please smoke test Linux platform

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please smoke test Linux platform

**Pull request merged**
