### PR TITLE
[upstream-update] update for SVN r266919

### PR DESCRIPTION
**Pull request by compnerd**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

getSymbolName changed from ErrorOr to Expected.  Update the API accordingly.

### CODE REVIEW

**Comment by compnerd** [comment]
CC @slavapestov

**Comment by modocache** [comment]
@swift-ci please test

**Comment by modocache** [comment]
@swift-ci Please test

**Comment by modocache** [comment]
@swift-ci please test

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by compnerd** [comment]
CC @rudkx

**Comment by rudkx** [comment]
I already made this change and another one related to Expected<> in commit b044c4d74feb4fa232ed017451c9b06395ea5867.

**Pull request closed without merging**
