### PR TITLE
[AutoDiff] Rename "TFDifferentiation.cpp" to "Differentiation.cpp"

### PR DESCRIPTION
**Pull request by rxwei**
Initially we added the "TF" prefix to align with tensorflow-branch passes for easier maintenance, but there are many other AD-related source files throughout the compiler that do not start with "TF". Moreover, AD is independent from TF support and will be upstreamed soon. This patch removes the "TF" prefix.

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Review by dan-zheng — APPROVED** [review]

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by rxwei** [comment]
https://ci-external.swift.org/view/Pull%20Request/job/swift-PR-TensorFlow-Linux/ The CI site is down. Comments may not be useful.

**Comment by dan-zheng** [comment]
@shahmishal https://ci-external.swift.org appears to be down. Do you happen to know what's going on? Thank you!

**Comment by rxwei** [comment]
CI is down. Manually tested and all tests are passing. Merging to unblock progress.

**Pull request merged**
