### PR TITLE
Revert "[benchmark] Report Quantiles from Benchmark_O and a TON of Gardening"

### PR DESCRIPTION
**Pull request by benlangmuir**
Reverts apple/swift#19097

This broke in CI: https://ci.swift.org/job/oss-swift-incremental-RA-osx/4909/testReport/

### CODE REVIEW

**Comment by palimondo** [comment]
@benlangmuir Do I revert the revert and add a commit which fixes the test?

**Comment by benlangmuir** [comment]
@palimondo that would work, although it will squash all your commits into one and you'll need to update the commit message to not just say "revert: revert: ...".  Alternatively you could create a new PR from the branch you used for #19097 but cherry-pick your new fix on top.

**Comment by palimondo** [comment]
@benlangmuir I'm not sure I follow completely. What would be the best way to have a good history?
I've added the fix into that branch from #19097. Do I now rebase that on top of master and push again?

**Comment by benlangmuir** [comment]
Once the branch is in the state you want, I think you just create a new PR for it.

**Comment by palimondo** [comment]
It's showing only the fix commit and nothing else: https://github.com/apple/swift/compare/master...palimondo:fluctuation-of-the-pupil?expand=1

**Comment by benlangmuir** [comment]
Ah, that's unhelpful.  Maybe git is confused because your commits are already in the branch history.  Maybe reverting the revert is the way to go.  Sorry for leading you astray in that case.  I guess we can always find the history by looking at what was merged in with the original PR.

**Comment by palimondo** [comment]
I think I got it. I've cherrypicked all changes from that branch including the fix onto another branch forked from master. I'll redo the description from the original PR and pig you from new PR.

**Pull request merged**
