### PR TITLE
DependenciesScanner: prefer private Swift module interfaces if present

### PR DESCRIPTION
**Pull request by nkcsgexi**
rdar://67257185

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Review by xymus — APPROVED** [review]
LGTM!

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci Please smoke test OS X platform

**Comment by nkcsgexi** [comment]
@swift-ci Please smoke test OS X platform

**Pull request merged**
