### PR TITLE
Backward compatible utf8 view slicing

### PR DESCRIPTION
**Pull request by dabrahams**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please test

**Comment by dabrahams** [comment]
@swift-ci Please test source compatibility

**Comment by dabrahams** [comment]
@swift-ci Please benchmark

**Comment by dabrahams** [comment]
@swift-ci Please test

**Comment by dabrahams** [comment]
@swift-ci Please test

**Comment by dabrahams** [comment]
@swift-ci Please test source compatibility

**Comment by dabrahams** [comment]
@swift-ci Please test source compatibility

**Comment by dabrahams** [comment]
@swift-ci Please benchmark

**Comment by dabrahams** [comment]
@swift-ci Please benchmark

**Comment by dabrahams** [comment]
@swift-ci Please test source compatibility

**Comment by dabrahams** [comment]
@swift-ci Please test source compatibility

**Comment by dabrahams** [comment]
There's no possible reason this change could interfere with the `Set` benchmarks.  I can only assume these results are unreal, but I'll request an additional smoke benchmark just in case.

**Comment by dabrahams** [comment]
@swift-ci Please smoke benchmark

**Comment by dabrahams** [comment]
@swift-ci Please smoke benchmark

**Comment by dabrahams** [comment]
@aschwaighofer Can you see any reason why these changes should have a dramatic effect on the speed of `Set` benchmarks?

**Comment by aschwaighofer** [comment]
There is additional code in (at least) the init, startIndex, endIndex methods. This can affect inlining decisions. I seemed to remember that for example SetIntersect is fully inlined.

**Comment by dabrahams** [comment]
on Tue Jul 18 2017, Arnold Schwaighofer <notifications-AT-github.com> wrote:

> There is additional code in (at least) the init, startIndex, endIndex
> methods. This can affect inlining decisions. I seemed to remember that
> for example SetIntersect is fully inlined.

But there's no String involved in these Set benchmarks.  Is that
realistic?

-- 
-Dave

**Comment by aschwaighofer** [comment]
Ah right. SetIntersect is a set of ints. No, that does not make sense. Does it reproduce?

**Comment by dabrahams** [comment]
Yes, it reproduces!  Instruments profiles are attached:

[Branch.trace.zip](https://github.com/apple/swift/files/1157642/Branch.trace.zip)
[Baseline.trace.zip](https://github.com/apple/swift/files/1157643/Baseline.trace.zip)

**Comment by dabrahams** [comment]
@aschwaighofer Also attaching sil renditions of this program in both cases, with all trivial differences removed, for your analysis pleasure!

```swift
@inline(never)
public func run_SetIntersect(_ N: Int, Random: ()->Int64, sink: (inout Set<Int>)->()) {
  let size = 400

  var set = Set<Int>(minimumCapacity: size)
  var otherSet = Set<Int>(minimumCapacity: size)

  for _ in 0 ..< size {
    set.insert(Int(truncatingBitPattern: Random()))
    otherSet.insert(Int(truncatingBitPattern: Random()))
  }

  var and = Set<Int>()
  for _ in 0 ..< N * 100 {
    and = set.intersection(otherSet)
  }
  sink(&and)
}
```

[sil.zip](https://github.com/apple/swift/files/1157666/sil.zip)

**Comment by dabrahams** [comment]
@eeckstein the one difference I can see in the -Onone sil output is:

```swift
// _NativeSetBuffer.assertingGet(_:)
sil hidden_external [serialized] @_T0s16_NativeSetBufferV12assertingGetxs01_aB5IndexVyxGF : $@convention(method) <Element> (_NativeSetIndex<Element>, @guaranteed _NativeSetBuffer<Element>) -> @out Element
```

**Comment by dabrahams** [comment]
The diffs in normalized SIL output are:

```diff
--- /tmp/baseline.sil	2017-07-20 13:09:07.000000000 -0700
+++ /tmp/branch.sil	2017-07-20 13:09:07.000000000 -0700
@@ -69,7 +69,7 @@
   %## = enum $SetIteratorRepresentation<Int>, #SetIteratorRepresentation._native!enumelt.1, %## : $(start: _NativeSetIndex<Int>, end: _NativeSetIndex<Int>, buffer: _NativeSetBuffer<Int>) // user: %##
   br bb##(%## : $SetIteratorRepresentation<Int>)   // id: %##
 
-// %##                                            // users: %##, %##
+// %##                                            // users: %##, %##, %##
 bb##(%## : $SetIteratorRepresentation<Int>):       // Preds: bb## bb##
   %## = unchecked_enum_data %## : $SetIteratorRepresentation<Int>, #SetIteratorRepresentation._native!enumelt.1 // users: %##, %##, %##
   %## = tuple_extract %## : $(start: _NativeSetIndex<Int>, end: _NativeSetIndex<Int>, buffer: _NativeSetBuffer<Int>), 0 // user: %##
@@ -100,7 +100,7 @@
   %## = struct_element_addr %## : $*Int, #Int._value // user: %##
   strong_retain %## : $_RawNativeSetStorage        // id: %##
   retain_value %## : $Set<Int>                     // id: %##
-  br bb##(%## : $_NativeSetIndex<Int>, %## : $_NativeSetBuffer<Int>, %## : $Builtin.Int64) // id: %##
+  br bb##(%## : $SetIteratorRepresentation<Int>, %## : $_NativeSetIndex<Int>, %## : $_NativeSetBuffer<Int>, %## : $Builtin.Int64) // id: %##
 
 bb##:                                              // Preds: bb## bb##
   %## = load %## : $*_VariantSetBuffer<Int>        // user: %##
@@ -108,11 +108,12 @@
   dealloc_stack %## : $*_VariantSetBuffer<Int>     // id: %##
   return %## : $Set<Int>                          // id: %##
 
-// %##                                            // users: %##, %##
-// %##                                            // users: %##, %##, %##, %##, %##, %##, %##, %##
+// %##                                            // user: %##
+// %##                                            // users: %##, %##, %##
+// %##                                            // users: %##, %##, %##, %##, %##, %##, %##, %##, %##
 // %##                                            // users: %##, %##, %##, %##, %##, %##, %##
-bb##(%## : $_NativeSetIndex<Int>, %## : $_NativeSetBuffer<Int>, %## : $Builtin.Int64): // Preds: bb## bb##
-  %## = struct_extract %## : $_NativeSetBuffer<Int>, #_NativeSetBuffer._storage // users: %##, %##, %##
+bb##(%## : $SetIteratorRepresentation<Int>, %## : $_NativeSetIndex<Int>, %## : $_NativeSetBuffer<Int>, %## : $Builtin.Int64): // Preds: bb## bb##
+  %## = struct_extract %## : $_NativeSetBuffer<Int>, #_NativeSetBuffer._storage // users: %##, %##, %##, %##
   %## = builtin "cmp_slt_Int64"(%## : $Builtin.Int64, %## : $Builtin.Int64) : $Builtin.Int1 // user: %##
   %## = ref_element_addr %## : $_RawNativeSetStorage, #_RawNativeSetStorage.capacity // user: %##
   %## = struct_element_addr %## : $*Int, #Int._value // user: %##
@@ -161,7 +162,8 @@
   %## = builtin "truncOrBitCast_Int64_Word"(%## : $Builtin.Int64) : $Builtin.Word // user: %##
   %## = pointer_to_address %## : $Builtin.RawPointer to [strict] $*Int // user: %##
   %## = index_addr %## : $*Int, %## : $Builtin.Word // user: %##
-  %## = load %## : $*Int                        // users: %##, %##, %##
+  %## = struct_element_addr %## : $*Int, #Int._value // user: %##
+  %## = load %## : $*Builtin.Int64              // users: %##, %##, %##, %##
   fix_lifetime %## : $_NativeSetBuffer<Int>       // id: %##
   %## = builtin "cmp_eq_Int64"(%## : $Builtin.Int64, %## : $Builtin.Int64) : $Builtin.Int1 // user: %##
   %## = builtin "or_Int1"(%## : $Builtin.Int1, %## : $Builtin.Int1) : $Builtin.Int1 // user: %##
@@ -174,6 +176,49 @@
   cond_br %##, bb##, bb##                        // id: %##
 
 bb##:                                             // Preds: bb##
+  cond_br %##, bb##, bb##                         // id: %##
+
+bb##:                                             // Preds: bb##
+  %## = integer_literal $Builtin.Int64, 9223372036854775807 // user: %##
+  %## = builtin "cmp_ult_Int64"(%## : $Builtin.Int64, %## : $Builtin.Int64) : $Builtin.Int1 // user: %##
+  cond_fail %## : $Builtin.Int1                  // id: %##
+  %## = integer_literal $Builtin.Int64, -64      // user: %##
+  %## = builtin "cmp_slt_Int64"(%## : $Builtin.Int64, %## : $Builtin.Int64) : $Builtin.Int1 // user: %##
+  %## = builtin "int_expect_Int1"(%## : $Builtin.Int1, %## : $Builtin.Int1) : $Builtin.Int1 // user: %##
+  cond_br %##, bb##, bb##                        // id: %##
+
+bb##:                                             // Preds: bb##
+  %## = builtin "ssub_with_overflow_Int64"(%## : $Builtin.Int64, %## : $Builtin.Int64, %## : $Builtin.Int1) : $(Builtin.Int64, Builtin.Int1) // users: %##, %##
+  %## = tuple_extract %## : $(Builtin.Int64, Builtin.Int1), 0 // user: %##
+  %## = tuple_extract %## : $(Builtin.Int64, Builtin.Int1), 1 // user: %##
+  cond_fail %## : $Builtin.Int1                  // id: %##
+  %## = integer_literal $Builtin.Int64, 63       // user: %##
+  %## = builtin "and_Int64"(%## : $Builtin.Int64, %## : $Builtin.Int64) : $Builtin.Int64 // user: %##
+  %## = builtin "lshr_Int64"(%## : $Builtin.Int64, %## : $Builtin.Int64) : $Builtin.Int64 // user: %##
+  br bb##(%## : $Builtin.Int64)                  // id: %##
+
+bb##:                                             // Preds: bb##
+  br bb##(%## : $Builtin.Int64)                   // id: %##
+
+bb##:                                             // Preds: bb##
+  %## = builtin "cmp_slt_Int64"(%## : $Builtin.Int64, %## : $Builtin.Int64) : $Builtin.Int1 // user: %##
+  %## = builtin "int_expect_Int1"(%## : $Builtin.Int1, %## : $Builtin.Int1) : $Builtin.Int1 // user: %##
+  cond_br %##, bb##, bb##                        // id: %##
+
+bb##:                                             // Preds: bb##
+  br bb##                                         // id: %##
+
+bb##:                                             // Preds: bb##
+  %## = integer_literal $Builtin.Int64, 63       // user: %##
+  %## = builtin "and_Int64"(%## : $Builtin.Int64, %## : $Builtin.Int64) : $Builtin.Int64 // user: %##
+  %## = builtin "shl_Int64"(%## : $Builtin.Int64, %## : $Builtin.Int64) : $Builtin.Int64 // user: %##
+  br bb##(%## : $Builtin.Int64)                  // id: %##
+
+bb##:                                             // Preds: bb##
+  %## = builtin "cmp_slt_Int64"(%## : $Builtin.Int64, %## : $Builtin.Int64) : $Builtin.Int1 // user: %##
+  br bb##(%## : $Builtin.Int1)                    // id: %##
+
+bb##:                                             // Preds: bb##
   br bb##(%## : $Builtin.Int64)                  // id: %##
 
 // %##                                           // users: %##, %##, %##, %##
@@ -216,8 +261,10 @@
 bb##:                                             // Preds: bb##
   br bb##(%## : $Builtin.Int64)                  // id: %##
 
-// %##                                           // users: %##, %##
+// %##                                           // users: %##, %##, %##
 bb##(%## : $Builtin.Int64):                      // Preds: bb## bb## bb##
+  strong_retain %## : $_RawNativeSetStorage       // id: %##
+  release_value %## : $SetIteratorRepresentation<Int> // id: %##
   %## = load %## : $*Builtin.Int64               // user: %##
   %## = builtin "assumeNonNegative_Int64"(%## : $Builtin.Int64) : $Builtin.Int64 // user: %##
   %## = builtin "cmp_eq_Int64"(%## : $Builtin.Int64, %## : $Builtin.Int64) : $Builtin.Int1 // user: %##
@@ -287,62 +334,6 @@
   br bb##(%## : $Builtin.Int64)                  // id: %##
 
 bb##:                                             // Preds: bb##
-  cond_br %##, bb##, bb##                         // id: %##
-
-bb##:                                             // Preds: bb##
-  %## = integer_literal $Builtin.Int64, 9223372036854775807 // user: %##
-  %## = builtin "cmp_ult_Int64"(%## : $Builtin.Int64, %## : $Builtin.Int64) : $Builtin.Int1 // user: %##
-  cond_fail %## : $Builtin.Int1                  // id: %##
-  %## = integer_literal $Builtin.Int64, -64      // user: %##
-  %## = builtin "cmp_slt_Int64"(%## : $Builtin.Int64, %## : $Builtin.Int64) : $Builtin.Int1 // user: %##
-  %## = builtin "int_expect_Int1"(%## : $Builtin.Int1, %## : $Builtin.Int1) : $Builtin.Int1 // user: %##
-  cond_br %##, bb##, bb##                        // id: %##
-
-bb##:                                             // Preds: bb##
-  %## = builtin "ssub_with_overflow_Int64"(%## : $Builtin.Int64, %## : $Builtin.Int64, %## : $Builtin.Int1) : $(Builtin.Int64, Builtin.Int1) // users: %##, %##
-  %## = tuple_extract %## : $(Builtin.Int64, Builtin.Int1), 0 // user: %##
-  %## = tuple_extract %## : $(Builtin.Int64, Builtin.Int1), 1 // user: %##
-  cond_fail %## : $Builtin.Int1                  // id: %##
-  %## = integer_literal $Builtin.Int64, 63       // user: %##
-  %## = builtin "and_Int64"(%## : $Builtin.Int64, %## : $Builtin.Int64) : $Builtin.Int64 // user: %##
-  %## = builtin "lshr_Int64"(%## : $Builtin.Int64, %## : $Builtin.Int64) : $Builtin.Int64 // user: %##
-  br bb##(%## : $Builtin.Int64)                  // id: %##
-
-bb##:                                             // Preds: bb##
-  br bb##(%## : $Builtin.Int64)                   // id: %##
-
-bb##:                                             // Preds: bb##
-  %## = builtin "cmp_slt_Int64"(%## : $Builtin.Int64, %## : $Builtin.Int64) : $Builtin.Int1 // user: %##
-  %## = builtin "int_expect_Int1"(%## : $Builtin.Int1, %## : $Builtin.Int1) : $Builtin.Int1 // user: %##
-  cond_br %##, bb##, bb##                        // id: %##
-
-bb##:                                             // Preds: bb##
-  br bb##                                         // id: %##
-
-bb##:                                             // Preds: bb##
-  %## = integer_literal $Builtin.Int64, 63       // user: %##
-  %## = builtin "and_Int64"(%## : $Builtin.Int64, %## : $Builtin.Int64) : $Builtin.Int64 // user: %##
-  %## = builtin "shl_Int64"(%## : $Builtin.Int64, %## : $Builtin.Int64) : $Builtin.Int64 // user: %##
-  br bb##(%## : $Builtin.Int64)                  // id: %##
-
-bb##:                                             // Preds: bb##
-  %## = builtin "cmp_slt_Int64"(%## : $Builtin.Int64, %## : $Builtin.Int64) : $Builtin.Int1 // user: %##
-  br bb##(%## : $Builtin.Int1)                    // id: %##
-
-bb##:                                             // Preds: bb## bb## bb## bb## bb##
-  %## = struct_extract %## : $_NativeSetIndex<Int>, #_NativeSetIndex.offset // user: %##
-  %## = struct_extract %## : $Int, #Int._value  // user: %##
-  %## = builtin "cmp_eq_Int64"(%## : $Builtin.Int64, %## : $Builtin.Int64) : $Builtin.Int1 // user: %##
-  cond_br %##, bb##, bb##                        // id: %##
-
-bb##:                                             // Preds: bb##
-  br bb##(%## : $_NativeSetIndex<Int>, %## : $_NativeSetBuffer<Int>, %## : $Builtin.Int64) // id: %##
-
-bb##:                                             // Preds: bb##
-  release_value %## : $_NativeSetBuffer<Int>      // id: %##
-  br bb##                                          // id: %##
-
-bb##:                                             // Preds: bb##
   %## = ref_element_addr %## : $_RawNativeSetStorage, #_RawNativeSetStorage.capacity // user: %##
   %## = struct_element_addr %## : $*Int, #Int._value // user: %##
   %## = load %## : $*Builtin.Int64              // user: %##
@@ -359,7 +350,6 @@
 // %##                                           // user: %##
 bb##(%## : $Builtin.Int64):                      // Preds: bb## bb##
   %## = builtin "assumeNonNegative_Int64"(%## : $Builtin.Int64) : $Builtin.Int64 // user: %##
-  %## = struct_extract %## : $Int, #Int._value  // users: %##, %##, %##
   %## = integer_literal $Builtin.Int64, 4294967295 // user: %##
   %## = builtin "and_Int64"(%## : $Builtin.Int64, %## : $Builtin.Int64) : $Builtin.Int64 // user: %##
   %## = integer_literal $Builtin.Int64, 32       // user: %##
@@ -465,6 +455,7 @@
   cond_br %##, bb##, bb##                        // id: %##
 
 bb##:                                             // Preds: bb##
+  %## = struct $Int (%## : $Builtin.Int64)      // users: %##, %##
   fix_lifetime %## : $_NativeSetBuffer<Int>       // id: %##
   %## = alloc_stack $Int                         // users: %##, %##
   // function_ref specialized _VariantSetBuffer.nativeInsert(_:forKey:)
@@ -504,6 +495,23 @@
 bb##:                                             // Preds: bb##
   br bb##(%## : $Builtin.Int64)                  // id: %##
 
+bb##:                                             // Preds: bb## bb## bb## bb## bb##
+  %## = struct_extract %## : $_NativeSetIndex<Int>, #_NativeSetIndex.offset // user: %##
+  %## = struct_extract %## : $Int, #Int._value  // user: %##
+  %## = builtin "cmp_eq_Int64"(%## : $Builtin.Int64, %## : $Builtin.Int64) : $Builtin.Int1 // user: %##
+  cond_br %##, bb##, bb##                        // id: %##
+
+bb##:                                             // Preds: bb##
+  %## = struct $Int (%## : $Builtin.Int64)      // user: %##
+  %## = struct $_NativeSetIndex<Int> (%## : $Int) // user: %##
+  %## = tuple $(start: _NativeSetIndex<Int>, end: _NativeSetIndex<Int>, buffer: _NativeSetBuffer<Int>) (%##, %##, %##) // user: %##
+  %## = enum $SetIteratorRepresentation<Int>, #SetIteratorRepresentation._native!enumelt.1, %## : $(start: _NativeSetIndex<Int>, end: _NativeSetIndex<Int>, buffer: _NativeSetBuffer<Int>) // user: %##
+  br bb##(%## : $SetIteratorRepresentation<Int>, %## : $_NativeSetIndex<Int>, %## : $_NativeSetBuffer<Int>, %## : $Builtin.Int64) // id: %##
+
+bb##:                                             // Preds: bb##
+  release_value %## : $_NativeSetBuffer<Int>      // id: %##
+  br bb##                                          // id: %##
+
 // %##                                           // user: %##
 bb##(%## : $_CocoaSetBuffer):                    // Preds: bb##
   %## = struct_extract %## : $_CocoaSetBuffer, #_CocoaSetBuffer.cocoaSet // user: %##
```

**Comment by shajrawi** [comment]
I was just looking at the diffs myself earlier: $SetIteratorRepresentation<Int> seems to be the only major difference: extra uses / retains / struct_extract that involve it (that are not present in the baseline) - I am building my own local copy at the moment to help investigate what's causing this

**Comment by dabrahams** [comment]
on Thu Jul 20 2017, Joe Shajrawi <notifications-AT-github.com> wrote:

> I was just looking at the diffs myself earlier:
> $SetIteratorRepresentation<Int> seems to be the only major difference:

I noticed that too.

> extra uses / retains / struct_extract that involve it (that are not
> present in the baseline) - I am building my own local copy at the
> moment to help investigate what's causing this

Thanks!

-- 
-Dave

**Comment by shajrawi** [comment]
I traced it back to the changes that were made to `public var endIndex: Index {`: 
In fact, reverting that function to its old version makes the SIL exactly like baseline.

I am trying to figure out the reason for that - seems like the extra call to `index(_ i: Index?, offsetBy n: IndexDistance) -> Index` causes this - removing that call (or replacing it with anything else) resolves the issue. However, adding inline always to the UTF8 version of it does not help.

**Comment by dabrahams** [comment]
@swift-ci Please smoke benchmark

**Comment by dabrahams** [comment]
@swift-ci Please smoke benchmark

**Comment by dabrahams** [comment]
@swift-ci Please test

**Comment by dabrahams** [comment]
@swift-ci Please test

**Comment by dabrahams** [comment]
With a workaround in `endIndex`, the performance looks better.  Thanks for all your help @shajrawi !

**Comment by milseman** [comment]
@dabrahams I assume this was also meant to be cherry-picked into 4.0?

**Comment by dabrahams** [comment]
@milseman Yep

**Pull request merged**
