### PR TITLE
[SpaceEngine] Couple of minor improvements

### PR DESCRIPTION
**Pull request by xedin**
* `Intersection` of two constructor spaces should produce a constructor space (not a disjunction);
* When it's detected that `switch` has redundant cases, don't include them into "covered" space to reduce some work done by exhaustiveness checker.
* Remove `isUseful` due to eager empty sub-space pruning

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by jrose-apple** [comment]
I'm pretty sure these are both correct (as discussed), but @CodaFi's likely to spot any issues we didn't think of.

**Review by CodaFi — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test compiler performance

**Comment by xedin** [comment]
@swift-ci Please smoke test compiler performance

**Comment by xedin** [comment]
Not sure where this debug build slowdown comes from but release seems to be fine and there are no other apparent regressions so I'm going to merge it if nobody objects.

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by jrose-apple** [comment]
Hm. The release build is slower too, just by a smaller amount. It's probably within noise but it could be that one of these changes actually does make the space engine take longer. (A full compiler perf test takes like 8 hours, though.)

**Comment by xedin** [comment]
Maybe it happens because of `Disjunct` to `Constructor` change, but that is more of a correctness issue. Just as an experiment let's revert that change and see.

**Comment by xedin** [comment]
@swift-ci please smoke test compiler performance

**Comment by xedin** [comment]
@swift-ci please smoke test compiler performance

**Comment by jrose-apple** [comment]
Welp. If that's really the difference, that's kind of scary, because that was indeed a correctness fix.

**Comment by xedin** [comment]
Unfortunately yes :( I'll look into why that is exactly, close this one and commit two other changes separately.

**Pull request closed without merging**
