### PR TITLE
Preparations for subst() preserving sugared TypeAliasTypes

### PR DESCRIPTION
**Pull request by slavapestov**
Mostly NFC, except for the change to have ProtocolConformanceRef::subst() return invalid conformances instead of asserting. That's necessary for the next PR, but shouldn't impact anything today.

Also, I'm adding a couple of crashing test cases for unrelated bugs.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Review by CodaFi — APPROVED** [review]
LGTM.  Hope you're able to dig up what happened in that regression.

**Comment by slavapestov** [comment]
```
18:28:52 Failing Tests (1):
18:28:52     Swift(macosx-x86_64) :: Python/python-lint.swift
```

This ain't me.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Pull request merged**
