### PR TITLE
Use relatively new LLVM_FALLLTHROUGH instead of our own SWIFT_FALLTHROUGH

### PR DESCRIPTION
**Pull request by hughbe**

### CODE REVIEW

**Comment by practicalswift** [comment]
Excellent! This will make `clang-tidy` happy too :-)

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by hughbe** [comment]
@practicalswift nice! What is clang tidy complaining about? It can't figure out the fact we explicitly fallthrough?

**Comment by gparker42** [comment]
Missed a spot:
`swift/include/swift/Parse/Parser.h:23:10: fatal error: 'swift/Basic/Fallthrough.h' file not found
#include "swift/Basic/Fallthrough.h"`

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Pull request merged**
