### PR TITLE
[Parse] Don't tell CodeCompletion nonsense about protocol/AT where clauses.

### PR DESCRIPTION
**Pull request by huonw**
This doesn't give particularly useful information yet (i.e. Self isn't
listed, see rdar://problem/31981641 ), but it does stop the completion
code from just directly crashing.

Fixes rdar://problem/31981486.

(Isn't it great when your own fixme's come back to bite you.)

### CODE REVIEW

**Comment by huonw** [comment]
@swift-ci Please smoke test and merge.

**Comment by huonw** [comment]
@swift-ci Please smoke test and merge.

**Comment by slavapestov** [comment]
@huonw the failing test is a crasher test case I added for this exact bug. If you want, you can resolve it and remove your newly-added test (or remove mine, or keep both).

**Comment by huonw** [comment]
@swift-ci Please smoke test OSX.

**Comment by huonw** [comment]
@swift-ci Please smoke test

**Comment by huonw** [comment]
@swift-ci Please smoke test and merge.

**Comment by huonw** [comment]
@swift-ci Please smoke test

**Comment by huonw** [comment]
@swift-ci Please smoke test and merge.

**Comment by huonw** [comment]
@swift-ci Please smoke test

**Pull request merged**
