### PR TITLE
Extend operator decls to allow any designated nominal type for lookup.

### PR DESCRIPTION
**Pull request by rudkx**
Rather than limiting this to protocols, allow any nominal type.

Rename -enable-operator-designated-protocols to
-enable-operator-designated-types to reflect the change.

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Review by xedin — APPROVED** [review]
Besides minor renaming nits, LGTM!

**Comment by rudkx** [comment]
@xedin Thanks for catching those. I have other edits to extend this further, but I've fixed up the naming prior to merging.

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Pull request merged**
