### PR TITLE
Sema: Gut synthesizeMemberForLookup()

### PR DESCRIPTION
**Pull request by slavapestov**
More cleanups based off of https://github.com/apple/swift/pull/16053.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test

**Review by itaiferber — APPROVED** [review]
Looks good from my (limited) end! Significant cleanup here, and it's more elegant to boot. Thanks 🙂

**Review by xedin — APPROVED** [review]
LGTM! Small nit - there is a typo (`than` right before `synthesizeMemberForLookup`)  in the first commit message.

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
