### PR TITLE
[stdlib] Condition Mutex.swift on platform

### PR DESCRIPTION
**Pull request by Azoy**
Mutex.swift was previously never conditional and always built, but the handle was conditioned based on platform. In a minimal toolchain, we don't have a platform to piggyback on, so we shouldn't build Mutex.swift either.

Resolves: rdar://129287049

### CODE REVIEW

**Comment by Azoy** [comment]
@swift-ci please smoke test

**Comment by Azoy** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with preset

**Comment by Azoy** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Review by stephentyrone — APPROVED** [review]

**Comment by stephentyrone** [comment]
Are we going to end up having to be able to check for availability? Should we put an unavailable placeholder in to give people a better error on other platforms?

**Comment by Azoy** [comment]
It seems like we should be able to have an unavailable availability for Mutex on platforms that don't support it (we can compile a special version of `Mutex` on those platforms). Yes we do, I'm going to put up a PR with this and the Mutex changes to 6.0

**Comment by Azoy** [comment]
@swift-ci please smoke test

**Comment by Azoy** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Pull request merged**
