### PR TITLE
[5.9] SE-0365 bug fixes

### PR DESCRIPTION
**Pull request by calda**
This PR cherry picks two bug fixes for [SE-0365](https://github.com/apple/swift-evolution/blob/main/proposals/0365-implicit-self-weak-capture.md) into the Swift 5.9 release branch. 

- **Explanation**: This fixes two bugs in the implementation of SE-0365, where code that is expected to compile would unexpectedly result in an error (examples below).
- **Scope**: This fixes two bugs in the implementation of SE-0365, which originally landed in Swift 5.8.
- **Issue**: fixes issues described in https://github.com/apple/swift/pull/65310 / https://github.com/apple/swift/pull/65211 and shown below (I didn't see or file an issue or radar for these issues, I just fixed them once I found them)
- **Risk**: These are targeted fixes than only affect the behavior of implicit self in `weak self` closures. There is little risk that this would cause a source compatibility issue, since these changes allow code that was previously rejected. It is also unlikely that this would cause a regression since there are pretty extensive unit tests for the expected behavior.
- **Testing**: CI test suite and source compatibility tests
- **Reviewers**: @DougGregor (5.9 release manager), @xedin 

I CP'd both of these changes in the same PR because the implementation of https://github.com/apple/swift/pull/65310 depends on changes in https://github.com/apple/swift/pull/65211

---

Examples of code that is currently rejected in Swift 5.8 / 5.9 but compiles successfully with these changes as expected by SE-0365:

```swift
class Test {
  func method() { }
  
  func foo(condition: Bool) {
    doVoidStuff { [weak self] in
      guard condition, let self else { return }
      method() // 🛑 Unexpected error: call to method 'method' in closure requires explicit use of 'self' to make capture semantics explicit
    }
  }
}
```

```swift
doVoidStuff { [weak self] in
  guard let self else { return }
  func innerFunction() {
    // 🛑 Error: call to method 'test' in closure requires explicit use of 'self' to make capture semantics explicit
    test()
  }
}
```

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Review by hborla — APPROVED** [review]

**Comment by hborla** [comment]
@swift-ci please test

**Comment by calda** [comment]
Looks like the Swift Test macOS Platform job failed in update-checkout. Smoke tests passed though.

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by calda** [comment]
All green now, thanks @xedin

**Pull request merged**
