### PR TITLE
[Macros] Improve error handling for executable macro plugins

### PR DESCRIPTION
**Pull request by rintaro**
* Handle broken pipe
* Handle invalid response (malformed message, unexpected message kind)

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
Still many FIXME, but at least plugin crashing doesn't cause compiler crashing.

**Review by bnbarham — APPROVED** [review]

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Pull request merged**
