### PR TITLE
New SIL instructions to support tail-allocated arrays in SIL.

### PR DESCRIPTION
**Pull request by eeckstein**
These new SIL instructions are used in Array and Set/Dictionary implementations (via new builtins), instead of ManagedBuffer/ManagedBufferPointer.
The effect is that the amount of SIL generated for array/set/dictionary operations is significantly smaller.
TODO: The stdlib's ManagedBuffer should also use those new builtins. This needs some more work on the alloc_ref and alloc_ref_dynamic SIL instructions.

### CODE REVIEW

**Comment by eeckstein** [comment]
@rjmccall, @jckarter: can you please look at my SIL changes (see docs/SIL.rst) and the new builtins (see Builtins.def)
@dabrahams: I already discussed the stdlib changes with you in person. If you have any additional comments, please let me know.

**Comment by jckarter** [comment]
This looks great!

**Comment by eeckstein** [comment]
@swift-ci Please test

**Comment by eeckstein** [comment]
@swift-ci Please test

**Comment by eeckstein** [comment]
@swift-ci Please benchmark

**Comment by lattner** [comment]
Nice!

**Comment by eeckstein** [comment]
@swift-ci Please test

**Comment by eeckstein** [comment]
@swift-ci Please test

**Comment by eeckstein** [comment]
@swift-ci Please test

**Comment by eeckstein** [comment]
@swift-ci Please benchmark

**Comment by gribozavr** [comment]
@eeckstein This PR could have broken LLDB, could you take a look?  https://ci.swift.org/job/oss-lldb-incremental-linux-ubuntu-14_04/5353/

**Comment by gribozavr** [comment]
@eeckstein Reverted in https://github.com/apple/swift/pull/4796.

**Comment by eeckstein** [comment]
@gribozavr Yep, this broke lldb. Thanks for reverting

**Pull request merged**
