### PR TITLE
Fix a case where guard let bindings were not emitted in their own scope. 

### PR DESCRIPTION
**Pull request by adrian-prantl**
This is a follow-up to e9d557ae287c3f5ea77d4ca79511834db76b66b3.  The
debug_value for the guard let binding is introduced by SGF.emitStmtCondition(),
so we also need to enter the debug scope before running that function.

rdar://74538257

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by compnerd** [comment]
@adrian-prantl this seems to have regressed the Windows build - the pre-commit CI actually caught the issue, can you please take a look?

**Comment by adrian-prantl** [comment]
@compnerd Sorry about that!

I've been looking at https://ci-external.swift.org/job/swift-PR-windows/11145/consoleText but from the context it's not clear where that happened to the `throw`. Do you have access to a Windows machine? Do you think you could paste the sil output for that test?

**Pull request merged**
