### PR TITLE
Fix misspellings

### PR DESCRIPTION
**Pull request by kkshinkai**
Replace “intializer” with “initializer”

### CODE REVIEW

**Comment by kkshinkai** [comment]
@swift-ci Do we need to test ... comments?

**Comment by kkshinkai** [comment]
@swift-ci smoke test and merge

**Comment by CodaFi** [comment]
Hey, thanks for the corrections. CI privileges are restricted to those with write access for security purposes, though.

@swift-ci smoke test and merge

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Pull request merged**
