### PR TITLE
utils: update the build-windows-toolchain.bat to extract the toolchain

### PR DESCRIPTION
**Pull request by compnerd**
Fetch a prebuilt toolchain to build the toolchain.  This is required to enable the macro support on Windows.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain windows platform

**Comment by shahmishal** [comment]
@swift-ci please build toolchain windows platform

**Comment by shahmishal** [comment]
@swift-ci test Windows

**Comment by compnerd** [comment]
@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain windows platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain windows platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain windows platform

**Comment by shahmishal** [comment]
@swift-ci please build toolchain windows platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain windows platform

**Comment by shahmishal** [comment]
@swift-ci please build toolchain windows platform

**Comment by shahmishal** [comment]
@swift-ci please build toolchain windows platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain windows platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain windows platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain windows platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain windows platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain windows platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/246

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/246

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/246

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/245

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/245

@swift-ci please test Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/245

@swift-ci please test Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/245

@swift-ci please test Windows platform

**Review by DougGregor — APPROVED** [review]

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/245

@swift-ci please test Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/245

@swift-ci please test Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/245

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/245

@swift-ci please smoke test

**Pull request merged**
