### PR TITLE
[Constraint graph] Associate all constraints with components.

### PR DESCRIPTION
**Pull request by DougGregor**
The connected components computation was not forming components when all of
the type variables in a component were already bound. Any remaining
constraints involving those type variables would then arbitrarily end up
in component 0, due to the the default-construction behavior of a map’s
operator[] with missing keys, artificially increasing the size of that
component with (typically) additional disjunctions.

Ensure that all constraints get into a component, creating one to hold
the a constraint even when all of the type variables are already bound.
Then, assert the invariant that every constraint is associated with a
component.

In time, we should probably eliminate this notion of disjunctions that
remain even when the type variable has been bound. For now, strengthen the
invariant to at least ensure that they get solved in isolation.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please test compiler performance

**Comment by DougGregor** [comment]
Hey @xedin , think that 1.5% reduction in constraint scopes might be meaningful? 🤞

**Comment by xedin** [comment]
Fewer scopes is always good because we create one per component. It could be either improving efficiency or breaking source compatibility or both :)

**Pull request merged**
