### PR TITLE
[NFC] Define SILGen Request Zone and GenerateSIL Request

### PR DESCRIPTION
**Pull request by CodaFi**
Define a high-level request for SILGen and switch the high-level
entrypoint to vector through it.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
apple/llvm-project#587

@swift-ci test

**Comment by CodaFi** [comment]
apple/llvm-project#587

@swift-ci test macOS platform

**Comment by dan-zheng** [comment]
Is there a plan to add SILOptimizer requests too? I'm curious because I've thought about adding some requests for the [differentiation transform](https://github.com/apple/swift/blob/tensorflow/lib/SILOptimizer/Mandatory/Differentiation.cpp).

**Comment by CodaFi** [comment]
Yes.  If you'd like to get around to doing that, this pull request is the template I'm going to use to do the SILOptimizer, IRGen, and TBDGen.

**Comment by CodaFi** [comment]
Alright, let's get this moving again.

**Comment by CodaFi** [comment]
Going to leave this here as a reminder for what it looks like to generate these zones when the time comes.  But ultimately these requests are going to live in libFrontend and a dedicated Frontend Zone.

**Comment by CodaFi** [comment]
@swift-ci please test

**Comment by CodaFi** [comment]
@swift-ci please test

**Comment by CodaFi** [comment]
apple/llvm-project#587

@swift-ci test

**Comment by CodaFi** [comment]
apple/llvm-project#587

@swift-ci test

**Comment by CodaFi** [comment]
⛵️

**Pull request merged**
