### PR TITLE
[ASTGen] Implement SequenceExpr generation

### PR DESCRIPTION
**Pull request by rintaro**
Implement `arrowExpr`, `assignmentExpr`, `binaryOperatorExpr`, `discardAssignmentExpr`, `postfixOperatorExpr `, `prefixOperatorExpr `, `sequenceExpr`, `typeExpr` `unresolvedAsExpr`, `unresolvedIsExpr`, and `unresolvedTernaryExpr`.

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please test Windows

**Review by hamishknight — APPROVED** [review]
Nice!

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Pull request merged**
