### PR TITLE
[4.0] [ClangImporter] Import class and enum members under Swift 3 and 4 names.

### PR DESCRIPTION
**Pull request by jrose-apple**
Cherry-pick of #9523 (reviewed by @milseman) and #9579 (reviewed by @DougGregor) to the 4.0 branch.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by milseman** [comment]
Failure is:
```
11:27:24  // CHECK-DIAGS-4: [[@LINE-1]]:{{[0-9]+}}: error: 'classWithManyRenamesForInt' has been replaced by 'init(swift4Factory:)'
11:27:24                    ^
11:27:24 <stdin>:42:2: note: scanning from here
11:27:24  let _: RenamedGeneric<SwiftClass> = OldRenamedGeneric<SwiftClass>()
11:27:24  ^
11:27:24 <stdin>:42:2: note: with expression "@LINE-1" equal to "48"
11:27:24  let _: RenamedGeneric<SwiftClass> = OldRenamedGeneric<SwiftClass>()
11:27:24  ^
11:27:24 <stdin>:47:46: note: possible intended match here
11:27:24 SOURCE_DIR/test/APINotes/versioned-objc.swift:48:28: error: 'classWithManyRenamesForInt' has been replaced by 'init(for:)'
11:27:24                                              ^
11:27:24 
11:27:24 --
11:39:49 Failing Tests (1):
11:39:49     Swift(macosx-x86_64) :: APINotes/versioned-objc.swift
```

**Comment by jrose-apple** [comment]
Need to figure out if I left out a commit, or what.

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
Approved by Ted via email.

**Pull request merged**
