### PR TITLE
[SourceKit][Format] Avoid indenting when multiple function call ends at this same line.

### PR DESCRIPTION
**Pull request by nkcsgexi**
#### Resolved bug number: ([SR-603](https://bugs.swift.org/browse/SR-603))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

A smoke test on macOS does the following:
1. Builds the compiler incrementally.
2. Builds the standard library only for macOS. Simulator standard libraries and
   device standard libraries are not built.
3. lldb is not built.
4. The test and validation-test targets are run only for macOS. The optimized
   version of these tests are not run.

A smoke test on Linux does the following:
1. Builds the compiler incrementally.
2. Builds the standard library incrementally.
3. lldb is built incrementally.
4. The swift test and validation-test targets are run. The optimized version of these
   tests are not run.
5. lldb is tested.

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

…at the same line.

This fixes SR-603.

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please test and merge

**Comment by therealbnut** [comment]
Yay, thank you @nkcsgexi :)

**Comment by therealbnut** [comment]
Hi @nkcsgexi, thank you very much for your work.

I think there may be some edge cases this may not consider:
```swift
UIView.animate(withDuration: 12.0, animations: {
    print("statements have good indentation")
    }, completion: { done in // this shouldn't be indented
        print("statements have weird indentation")
})
```

Compared to this:
```swift
UIView.animate(withDuration: 12.0, animations: {
    print("statements have good indentation")
}) { done in // this previously has correct indentation, but will it break with your changes?
    print("statements have good indentation")
}
```
I'm not sure if this change will actually break this case...

**Comment by nkcsgexi** [comment]
Hi @therealbnut , I think the behavior is intended. In this first case, the line you commented is inside arguments of the function call, thus giving another level is proper. For the second case, where the line you marked is the end of a call and the beginning of the trailing closure, we should not add a new level of indentation, so to keep the trailing closure standalone. thoughts?

**Comment by therealbnut** [comment]
For the first case I agree that it should be indented if it was like this (auto-formatted by Xcode8 8S128d):
```swift
UIView.animate(
    withDuration: 12.0,
    animations: {
        print("statements have weird indentation")
    },
    completion: { done in
        print("statements have weird indentation")
}) // this line will be fixed by your bug fix, thanks again :)
```
However, in the first example the argument label is on the same line as the closing bracket (`}, completion: {`). That line is both part of the argument label, and part of the closure. 

I expect indentation to approximately reflect the syntax tree, all arguments at the same level should get the same indentation. So sibling closures should get the same indentation on their closing bracket.

Having the print statement at the same level as the closure's closing bracket makes it less clear that the closure has finished. At a glance a programmer may think that `completion` is an expression inside the first closure.

I think the second case is already formatted correctly. I just wanted to confirm there isn't a false-positive with `}) {` in your fix. I don't know enough about your code to confirm myself.

**Comment by nkcsgexi** [comment]
@therealbnut , Thanks for bringing up two indentation schemes for the inlined closure call! I think it makes sense for us to support both preferences. Could you file a jira bug as usual and assign to me? I'm happy to work on it. For the trailing closure case, I can assure you that the pull request did not break existing behavior : )

**Comment by therealbnut** [comment]
@nkcsgexi done, thank you :) https://bugs.swift.org/browse/SR-2188

**Pull request merged**
