### PR TITLE
[CMake] Better dependency checking

### PR DESCRIPTION
**Pull request by davezarzycki**
This builds on #38123

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Review by drexin — APPROVED** [review]
LGTM

**Comment by davezarzycki** [comment]
@swift-ci please clean test macos

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
This breaks the windows build :-( https://dev.azure.com/compnerd/swift-build/_build/results?buildId=52693&view=logs&j=ec47c80d-c7cf-5f2b-7138-13cd268bea3d&t=590c4a12-cfb0-5e86-e81d-27e1d6a8e1a1

**Pull request merged**
