### PR TITLE
[OpaqueValues] Handled more instructions.

### PR DESCRIPTION
**Pull request by nate-chandler**
- unchecked_bitwise_cast to loadable type
- existential_metatype
- select_enum

Based on https://github.com/apple/swift/pull/61897 , https://github.com/apple/swift/pull/61917 .

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please smoke test

**Review by atrick — APPROVED** [review]
LGTM
...except no need to call forceDeleteWithUsers after replaceAllUsesWith

**Review by atrick — CHANGES_REQUESTED** [review]
Actually, `visitUncheckedBitwiseCastInst` isn't fully handled yet

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by atrick — APPROVED** [review]

**Pull request merged**
