### PR TITLE
[CMake] Use CMake caches for lldb in build-script

### PR DESCRIPTION
**Pull request by weliveindetail**
This requires https://github.com/apple/swift-lldb/pull/1765

### CODE REVIEW

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-lldb/pull/1765
@swift-ci test

**Comment by adrian-prantl** [comment]
@weliveindetail you can test two commits at the same time using the syntax I used in the previous comment. Then, once both PRs are tested, manually click the "merge" buttons in both pull requests in rapid succession to avoid breaking PR testing for everybody else.

**Comment by weliveindetail** [comment]
PR test failed with:
```
19:57:28 In file included from /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/lldb/source/Plugins/ExpressionParser/Swift/SwiftREPL.cpp:41:
19:57:28 In file included from /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/include/swift/SIL/SILModule.h:38:
19:57:28 In file included from /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/include/swift/SIL/TypeLowering.h:16:
19:57:28 In file included from /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/include/swift/ABI/MetadataValues.h:25:
19:57:28 
/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/include/swift/Runtime/Unreachable.h:27:20: error: redefinition of 'swift_runtime_unreachable'
19:57:28 inline static void swift_runtime_unreachable(const char *msg) {
19:57:28                    ^
19:57:28 /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/include/swift/Runtime/Unreachable.h:27:20: note: previous definition is here
19:57:28 inline static void swift_runtime_unreachable(const char *msg) {
19:57:28                    ^
19:57:28 1 error generated.
```

Will do this in the morning without modules + one more detail I missed.
Thanks @adrian-prantl for the cross-repo PR test trick!

**Comment by weliveindetail** [comment]
test with apple/swift-lldb#1765
@swift-ci test

**Pull request merged**
