### PR TITLE
[Refactoring] SyntacticRename should walk into ObjC Keypath components when matching name locations.

### PR DESCRIPTION
**Pull request by nathawes**
It wasn't previously so missed them.

Resolves rdar://61573935

### CODE REVIEW

**Comment by nathawes** [comment]
@swift-ci please test

**Review by bnbarham — APPROVED** [review]
LGTM!

**Comment by nathawes** [comment]
@swift-ci please test macOS

**Comment by nathawes** [comment]
@swift-ci please smoke test macOS

**Pull request merged**
