### PR TITLE
🍒 6.0: allow custom options when building the compiler with debug info

### PR DESCRIPTION
**Pull request by edymtt**
**Explanation**: allow to pass custom compiler flags when building the compiler with debug info -- currently those are hardcoded to `-g`, but in some Apple internal configurations we would like to change them.
**Radar**: rdar://127503136
**Scope**: CMake logic that builds the Swift part of the compiler and tools, build-script logic that handles command line arguments
**Risk**: low
* the logic is opt in and used when building in debug or release with debuginfo
* its default case matches the current situation (that is, using `-g`)
**Testing**:

* added build-script tests to ensure flags are propagated correctly to CMake

**Reviewed By**: @al45tair in https://github.com/apple/swift/pull/73603

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci please test

**Comment by edymtt** [comment]
@swift-ci please build toolchain

**Comment by edymtt** [comment]
@swift-ci please test WebAssembly

**Review by shahmishal — APPROVED** [review]

**Comment by edymtt** [comment]
@swift-ci please test Linux

**Comment by edymtt** [comment]
@swift-ci please build toolchain Linux

**Comment by edymtt** [comment]
@swift-ci please test WebAssembly

**Comment by edymtt** [comment]
@swift-ci please test Linux

**Comment by edymtt** [comment]
@swift-ci please build toolchain Linux

**Comment by edymtt** [comment]
@swift-ci please clean test WebAssembly

**Comment by edymtt** [comment]
WebAssembly has the same 51 test failures as `release/6.0`

**Pull request merged**
