### PR TITLE
[test] Using lit incremental mode and rearranging tests.

### PR DESCRIPTION
**Pull request by moiseev**
The incremental mode orders test by the last time modified, instead of
by the path, it also touches the files for failed tests, in order for
them to be prioritized on the next run. Using this mode as the default
improves both the CI and local development experience: CI builds
triggered by the commit, that includes changes to the tests, will run
those tests first; locally, it makes a lot of sense to run previously
failed tests first to make sure they've been fixed.

Since this mode changes the order in which tests get executed, the
'1_stdlib' name no longer has any effect, and can be fixed.

A few most time consuming tests were moved from tests/stdlib to
validation-test/stdlib to speed up the execution of unit test suite
(a.k.a build-script -t).

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by gottesmm** [comment]
+1!

**Comment by moiseev** [comment]
Tests failed due to an incorrect symlink in 'validation-test/stdlib'. Fixed now.
@swift-ci Please test.

**Comment by jrose-apple** [comment]
Can you split the renaming and the rearranging into separate commits, for bookkeeping purposes? This is especially relevant if we continue to cherry-pick things to the swift-3.0-branch.

**Comment by moiseev** [comment]
@jrose-apple Done.

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
Thank you!

**Comment by moiseev** [comment]
@swift-ci Please test and merge

**Comment by gottesmm** [comment]
@swift-ci Please test and merge

**Comment by moiseev** [comment]
Thanks @gottesmm. I wonder why mine did not work...

**Pull request merged**
