### PR TITLE
Fix else code style

### PR DESCRIPTION
**Pull request by frootloops**

### CODE REVIEW

**Comment by jtbandes** [comment]
Is this conforming to some explicitly stated code style?

Personally, I much prefer the newline being there in most cases.

**Comment by gribozavr** [comment]
For the C++ code, LLVM guidelines clearly state that `} else {` is preferred.

For Swift code:

```
$ git grep '} else {' stdlib/ test/ validation-test/ | wc -l
     505
$ git grep '  else {' stdlib/ test/ validation-test/ | wc -l
      83
```

@dabrahams @moiseev What is your preference?  I like `} else {`, but I can see argument being made both ways.

**Comment by moiseev** [comment]
I'm certainly in favor of the `} else {` style. This way `else` is explicitly seen as a component of a larger `if ... else` expression.

**Comment by frootloops** [comment]
@gribozavr I just rebase the branch and it's ready to be merged if you don't mind :)

**Comment by lattner** [comment]
I agree with max that "} else {" is preferred, but @dabrahams should definitely weigh in.

**Comment by gribozavr** [comment]
@frootloops:
@dabrahams, @moiseev and I discussed this and we came to conclusion that we would like to use the newline style, `} \n else {`, primarily for two reasons (please correct me if I'm misrepresenting the arguments):

- It makes it easy to insert comments about conditions without compromising consistency:

```
  ...
}
// Check for the unusual case.
else if foo > bar {
}
```

- It makes it easy to comment out an `else-if` block:

```
  ...
}
//else if foo > bar {
// ...
//}
```

**Comment by gribozavr** [comment]
@frootloops We have two suggestions for you:

- Remove Swift parts from this pull request.  The C++ parts are good and ready to land.

- If you like, you can open another pull request that changes all Swift code to use the newline style.

**Comment by frootloops** [comment]
@gribozavr I have updated the PR

**Pull request merged**
