### PR TITLE
SIL Optimizer: Don't run predictable memory optimizations on deserialized functions

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke benchmark

**Comment by slavapestov** [comment]
@atrick Looks like we’re still missing a piece of the puzzle here.

**Comment by slavapestov** [comment]
... or maybe it’s just noise. The “improvements” look very suspect too.

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
