### PR TITLE
[opt-remark] Teach arg inference how to handle simple loads from globals.

### PR DESCRIPTION
**Pull request by gottesmm**
Just adding new patterns.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Review by francisvm — APPROVED** [review]
Looks good, thanks. I haven't thought how this manifests with nested loads and I can't come up with an example where it would infer the wrong thing.

**Comment by gottesmm** [comment]
I fixed the reason that it crashed. Forgot to update the yaml.

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci test windows platform

**Comment by gottesmm** [comment]
Realized I force pushed to the wrong branch. This is the right one though.

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Pull request merged**
