### PR TITLE
doc-serialization: exclude non-public decls when serializing module group info.

### PR DESCRIPTION
**Pull request by nkcsgexi**
This reduces the size of x86_64.swiftdoc about 10%.

rdar://48689311

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by jrose-apple** [comment]
At first glance the logic looks identical before and after to me. What decls were affected by this change?

**Comment by jrose-apple** [comment]
Ah, I see, the access control check was moved before the GroupInfo check.

**Comment by compnerd** [comment]
This broke the windows build!

**Pull request merged**
