### PR TITLE
[benchmark] Add UTF8Decode_InitDecoding_repairUTF8

### PR DESCRIPTION
**Pull request by benrimmington**
Adds a benchmark for the internal [`repairUTF8(_:firstKnownBrokenRange:)`](https://github.com/apple/swift/blob/5f98d39dd4114eb02f2cdb661fc00247a4f4bef1/stdlib/public/core/StringUTF8Validation.swift#L156-L204) function.

This benchmark is intended for #30780.

"UTF8Decode_InitDecoding_repairUTF8" doesn't conform to the [naming convention](https://github.com/apple/swift/blob/main/benchmark/Naming.md), but neither do the existing benchmarks.

### CODE REVIEW

**Comment by benrimmington** [comment]
@swift-ci Please smoke test

**Comment by benrimmington** [comment]
@swift-ci Please benchmark

**Comment by benrimmington** [comment]
This benchmark is intended for #30780.

* "UTF8Decode_InitDecoding_repairUTF8" doesn't conform to the [naming convention](https://github.com/apple/swift/blob/master/benchmark/Naming.md), but neither do the existing benchmarks.

* I decided not to use a [setUpFunction](https://github.com/apple/swift/blob/f7b826f74bea0d2924bda685b2cde84b85f61bc3/benchmark/utils/TestsUtils.swift#L137-L144) for the input array mapping, to keep it local to the runFunction.

**Comment by eeckstein** [comment]
> I decided not to use a setUpFunction for the input array mapping, to keep it local to the runFunction.

Why?

**Comment by benrimmington** [comment]
@swift-ci Please smoke test

**Comment by benrimmington** [comment]
@swift-ci Please smoke test

**Comment by benrimmington** [comment]
@swift-ci Please benchmark

**Comment by benrimmington** [comment]
[Benchmark #1861](https://ci.swift.org/job/swift-PR-osx-perf/1861/):

> In file included from /Users/buildnode/jenkins/workspace/swift-PR-osx-perf/llvm-project/clang-tools-extra/clangd/CompileCommands.cpp:12:
> /Users/buildnode/jenkins/workspace/swift-PR-osx-perf/llvm-project/clang/include/clang/Driver/Options.h:44:10: fatal error: 'clang/Driver/Options.inc' file not found

**Comment by benrimmington** [comment]
@swift-ci Please benchmark

**Comment by benrimmington** [comment]
@eeckstein Does this look better with the setUpFunction?

**Pull request closed without merging**
