### PR TITLE
[ClangImporter] Make completion handlers Sendable

### PR DESCRIPTION
**Pull request by beccadax**
If a method has an `async` variant, the non-`async` variant will now mark its completion handler parameter `@Sendable`. This shouldn't be a breaking change in Swift 5 code since these declarations are automatically `@_predatesConcurrency`.

Also adds:

• Support for `@_nonSendable` on parameters, which can be used to override this implicit `@Sendable`
• Support for `@Sendable` on block typedefs; it's generally going to be a good idea to mark completion block typedefs `@Sendable`.

Fixes rdar://85569247.

### CODE REVIEW

**Comment by beccadax** [comment]
@swift-ci please test

**Comment by beccadax** [comment]
@swift-ci please test source compatibility

**Comment by beccadax** [comment]
@swift-ci please test

**Comment by beccadax** [comment]
@swift-ci smoke test

**Comment by beccadax** [comment]
@swift-ci smoke test

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
