### PR TITLE
test: attempt to fix windows builder

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @bitjammer

**Comment by compnerd** [comment]
@swift-ci please smoke test and merge

**Comment by compnerd** [comment]
@swift-ci please test windows platform

**Comment by compnerd** [comment]
https://dev.azure.com/compnerd/swift-build/_build/results?buildId=24034&view=logs&j=0e514031-a9b0-5d19-4075-e5711178f10f&t=81e01596-0d15-5c40-bfa8-129b1c333c7d for faster CI

**Comment by bitjammer** [comment]
Ah, yeah, that's probably it. Thank you @compnerd, it's been a while, didn't know there were Windows bots now. I feel like `please test` should include Windows...

**Comment by compnerd** [comment]
Yeah, that is a capacity issue, I hope that we will be able to resolve that.  The local build finally got through the swiftCore build, seems like it fixes it.

**Pull request merged**
