### PR TITLE
IRGen: ensure that declarations are not COMDATed

### PR DESCRIPTION
**Pull request by compnerd**
Unfortunately, declarations cannot be marked with their COMDAT groups.
This fixes multithreaded IRGen where we would emit declarations for the
global initializers with COMDATs causing the IR Verifier to object.  The
existing test cases cover this scenario.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @jckarter @rjmccall

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Review by rjmccall — APPROVED** [review]
Okay, and this will be fixed if we later come along and emit the definition because `updateLinkageForDefinition` just applies the whole linkage afresh.  SGTM.

**Pull request merged**
