### PR TITLE
TargetConstantFolding: address review comments

### PR DESCRIPTION
**Pull request by eeckstein**
This PR addresses review comments of https://github.com/apple/swift/pull/59665

* move the source file to SILOptimizer/IRGenTransforms
* add a file level comment
* document and verify that the pass runs after serialization
* catch overflows when truncating a constant value

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci test

**Review by atrick — APPROVED** [review]
No objections here.

For the record, I was reacting to the fact that IRGenOptions is now part of AST lowering, which tells anyone working on the compiler that any SIL pass is free to use target info.

**Comment by eeckstein** [comment]
good point.
I've put the assert into `SILModule::getIRGenOptionsOrNull`. This prevents all optimizations to use IRGenOptions before serialization.

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Pull request merged**
