### PR TITLE
[embedded] Move _CustomStringConvertibleOrNone/_LosslessStringConvertibleOrNone to avoid detaching doccomments from their declarations

### PR DESCRIPTION
**Pull request by kubamracek**
It turns out that the addition of the _CustomStringConvertibleOrNone/_LosslessStringConvertibleOrNone typealiases happened at a very unfortunate source code location that causes the doccomments to get detached from their declarations. Let's fix that.

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
> I think #68597 might have detached the `ObjectIdentifier` initializers from their documentation.

Good catch, fixed in this PR too.

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by benrimmington — APPROVED** [review]

**Comment by kubamracek** [comment]
> I'm not suggesting another change, but can opaque types and metatypes be used?
> 
> ```diff
> - public init<Object: AnyObject>(_ x: Object)
> + public init(_ x: some AnyObject)
> ```
> 
> ```diff
> - public init<Object>(_ x: Object.Type)
> + public init(_ x: (some Any).Type)
> ```

Correct me if I'm wrong, but my understanding is that these two options are equivalent in basically all aspects, and they are just two different syntactical options for exactly the same thing. So yes, either can be used, and I thought it's mostly a matter of personal preference -- or is there some official recommendation to use one over the other? (I'd be happy to change it to use "some" if that's the preferred way.)

**Comment by kubamracek** [comment]
Right, but those are using "any", and are problematic in embedded Swift. "some" and generics are completely fine. The code snippet we're talking about is not using existentials or metatypes.

**Pull request merged**
