### PR TITLE
[update-checkout] Now that all of the bots use --scheme instead of --branch, remove --branch.

### PR DESCRIPTION
**Pull request by gottesmm**
Title says it all.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci Please smoke test

**Comment by gottesmm** [comment]
@swift-ci Please python lint

**Comment by erg** [comment]
Whoa, it can python lint?!

**Comment by gottesmm** [comment]
I am going to fix the python lint problems in a separate PR and move the linting to run with the smoke tests. That is how these issues keep on sneaking in.

**Comment by shahmishal** [comment]
@erg yes :)

**Pull request merged**
