### PR TITLE
IRGen: Add a pass to disable tail calling of objc_retainAutoreleasedR…

### PR DESCRIPTION
**Pull request by aschwaighofer**
…eturnValue

We don't want this to happen:

  callq  0x01ec08 ; symbol stub for: objc_msgSend
  movq   %rax, %rdi
  popq   %rbp // <== Blocks the handshake from objc_autoreleaseReturnValue
  jmp    0x01ec20 ; symbol stub for: objc_retainAutoreleasedReturnValue

This was exposed by the change to callee_guaranteed closures.

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by gparker42** [comment]
Is this pass architecture-specific? arm and arm64 have no trouble with such tail calls.

**Comment by aschwaighofer** [comment]
No it is not but maybe it should be specific to x86_64:
@gparker Do The arm implemtations only look for the marker and not for the retainAutoreleasedReturnValue call so that an epilog sequence inserted before the tail jump is no problem?

**Comment by gparker42** [comment]
That's right. On arm and arm64 and i386 the only requirement is the no-op move instruction after the call site.

**Comment by aschwaighofer** [comment]
@swiftc-ci Please test

**Comment by slavapestov** [comment]
Instead of doing this as a separate pass, please just update the places in IRGen that generate calls to this function to clear the flag.

**Comment by aschwaighofer** [comment]
It is *not* IRGen putting these on. LLVM marks calls with the tail call flag because they don't access stack local memory. This is why we only see this issue in release builds.

**Comment by aschwaighofer** [comment]
This pass runs late in LLVM's pipeline (pre backend code gen) to remove the flag again

**Comment by slavapestov** [comment]
Oh I see, thanks for explaining. I guess it would be nice if there was a "never mark this as tail" flag that IRGen could set, but in the absence of that I understand why we need a separate pass.

**Comment by aschwaighofer** [comment]
Duuh, now that you mention I rememeber there actually is ``notail``. I will do that instead!

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test and merge

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Pull request merged**
