### PR TITLE
In immediate mode, detect the host OS version on Apple platforms.

### PR DESCRIPTION
**Pull request by jrose-apple**
Follow-up to #6430. This allows interpreter mode to pick up the current version of macOS instead of defaulting to 10.9, making it unnecessary to write `#available`. A -target flag can still override this if you're trying to write a portable script. The logic is a little tortured to avoid having to actually link to
Foundation.framework or libobjc.

Finishes rdar://problem/29433205.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@erg, can you review the CMake changes; @jckarter, is it worth the circumlocution here to avoid loading Foundation?

(I didn't actually check to see if linking to fewer things improves startup time. If it does, maybe we should dynamically load libedit as well.)

@swift-ci Please test

**Comment by jckarter** [comment]
It looks like `swiftc` already links `libobjc` and `CoreFoundation`, so I don't know how much we save trying to avoid bringing in `Foundation`. All these dylibs are hopefully in the shared cache anyway.

**Comment by jrose-apple** [comment]
The first commit removes swiftc's link to libobjc and CF, since we're not actually using it for anything. I'm less concerned about memory usage or IO than static constructors.

**Comment by jrose-apple** [comment]
(although the time difference between `xcrun swiftc --version` and `xcrun $PWD/../build/ninja/swift*/bin/swiftc --version` was clearly tilted in favor of Xcode's copy, despite mine being a Release+Asserts build)

**Comment by jckarter** [comment]
You might look specifically at the pre-`main` time, which is hopefully less sensitive to compiler flags. I would hope that everything in the shared cache is sufficiently pre-bound that it wouldn't make much difference which parts of it you map in.

**Comment by erg** [comment]
The cmake changes look fine if we don't want to link against ``objc``.

**Comment by jrose-apple** [comment]
DYLD_PRINT_STATISTICS shows that the cost of linking Foundation is about 1.5-3ms of a total 9-11ms launch time, over a few repeated trials.

Without Foundation (and with CF and libobjc removed):

```
Total pre-main time:   8.15 milliseconds (100.0%)
         dylib loading time:   0.99 milliseconds (12.1%)
        rebase/binding time:   4.95 milliseconds (60.7%)
            ObjC setup time:   0.22 milliseconds (2.7%)
           initializer time:   1.93 milliseconds (23.7%)
           slowest intializers :
             libSystem.B.dylib :   0.31 milliseconds (3.8%)
                        swiftc :   1.54 milliseconds (18.9%)
```

With Foundation:

```
Total pre-main time:   9.62 milliseconds (100.0%)
         dylib loading time:   1.76 milliseconds (18.2%)
        rebase/binding time:   3.17 milliseconds (32.9%)
            ObjC setup time:   0.73 milliseconds (7.6%)
           initializer time:   3.89 milliseconds (40.4%)
           slowest intializers :
             libSystem.B.dylib :   0.45 milliseconds (4.6%)
                CoreFoundation :   0.38 milliseconds (4.0%)
                    Foundation :   0.27 milliseconds (2.8%)
                        swiftc :   2.33 milliseconds (24.3%)
                      Kerberos :   0.28 milliseconds (2.9%)
```

I'm not sure whether this is significant but it seems like we might as well save it.

**Comment by jrose-apple** [comment]
For comparison, Clang is down in the 5-7ms range. Maybe they just have fewer symbols.

```
Total pre-main time:   6.49 milliseconds (100.0%)
         dylib loading time:   1.31 milliseconds (20.2%)
        rebase/binding time:   3.56 milliseconds (54.9%)
            ObjC setup time:   0.38 milliseconds (5.8%)
           initializer time:   1.16 milliseconds (17.8%)
           slowest intializers :
             libSystem.B.dylib :   0.38 milliseconds (5.9%)
                         clang :   0.65 milliseconds (10.0%)
```

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test Linux

**Comment by jrose-apple** [comment]
@swift-ci Please test macOS

**Comment by jckarter** [comment]
Thanks for measuring! I agree we may as well save some start time if we can.

**Comment by jrose-apple** [comment]
@swift-ci Please test macOS

**Pull request merged**
