### PR TITLE
Enable serialization of witness tables by default

### PR DESCRIPTION
**Pull request by swiftix**
Now that we remove the [serialized] flag from functions after their early serialization, we can run another round of optimizations on them. Due to this change, it should be OK to serialize witness tables now because marking the witness methods [serialized] does not affect how well they can be optimized.

### CODE REVIEW

**Comment by swiftix** [comment]
@swift-ci please smoke benchmark

**Comment by swiftix** [comment]
@slavapestov You meant this change when talking about `sil-serialize-witness-tables` changes, right?

**Comment by slavapestov** [comment]
@swiftix Yes, this is exactly what I meant, but of course also doing the extra step of removing the flag completely and constant-folding any places where it comes up.

**Comment by swiftix** [comment]
@slavapestov What about `-sil-serialize-vtables`? Do we want to enable them by default and remove the flag as well?

**Comment by slavapestov** [comment]
@swiftix No, -sil-serialize-vtables needs a bit more work. We don't want to serialize them in resilient builds, for instance. Let's discuss is in person next week.

**Comment by swiftix** [comment]
@swift-ci please smoke test OS X

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@slavapestov OK, I pushed some updates. Now `-sil-serialize-witness-tables` is removed completely.

**Comment by swiftix** [comment]
@huonw This PR touches a lot TBD-related things. I simply removed silSerializeWitnessTables flags everywhere. Is it OK? Or should I take any special care regarding the TBD implementation?

**Review by huonw — APPROVED** [review]
Looks fine; TBD is just passing that argument along to other subsystems, so it shouldn't need any special treatment.

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by swiftix** [comment]
@swift-ci please smoke test compiler performance

**Comment by swiftix** [comment]
@swift-ci please smoke test compiler performance

**Comment by swiftix** [comment]
@swift-ci please smoke test compiler performance

**Comment by swiftix** [comment]
@swift-ci Please test source compatibility

**Comment by swiftix** [comment]
@swift-ci Please test source compatibility

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by swiftix** [comment]
@swift-ci please smoke benchmark

**Comment by swiftix** [comment]
@swift-ci please smoke benchmark

**Pull request merged**
