### PR TITLE
[CMake] More dependency updates.

### PR DESCRIPTION
**Pull request by jrose-apple**
Things that depend on MapKit and QuartzCore also need to be updated.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@jckarter, yet another one to cherry-pick.

@swift-ci Please smoke test and merge

**Comment by jrose-apple** [comment]
@aciidb0mb3r, know what's up with this one?
```
Test Case 'GitRepositoryTests.testRemotes' started at 17:26:18.175
error: Unknown subcommand: get-url
usage: git remote [-v | --verbose]
   or: git remote add [-t <branch>] [-m <master>] [-f] [--tags|--no-tags] [--mirror=<fetch|push>] <name> <url>
   or: git remote rename <old> <new>
   or: git remote remove <name>
   or: git remote set-head <name> (-a | --auto | -d | --delete |<branch>)
   or: git remote [-v | --verbose] show [-n] <name>
   or: git remote prune [-n | --dry-run] <name>
   or: git remote [-v | --verbose] update [-p | --prune] [(<group> | <remote>)...]
   or: git remote set-branches [--add] <name> <branch>...
   or: git remote set-url [--push] <name> <newurl> [<oldurl>]
   or: git remote set-url --add <name> <newurl>
   or: git remote set-url --delete <name> <url>

    -v, --verbose         be verbose; must be placed before a subcommand

/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/swiftpm/Tests/SourceControlTests/GitRepositoryTests.swift:320: error: GitRepositoryTests.testRemotes : XCTAssertEqual threw error "exit(129): git -C /tmp/spm-tests-testRemotes().xtJmp2/test-repo remote get-url origin" - 
```

**Comment by jrose-apple** [comment]
This change is Darwin-only; force-merging to clear up CI.

**Comment by aciidb0mb3r** [comment]
@jrose-apple reverted here https://github.com/apple/swift-package-manager/pull/686

**Pull request merged**
