### PR TITLE
Fix test/Concurrency/objc_async_protocol_irgen.swift for 32-bit

### PR DESCRIPTION
**Pull request by atrick**
This test was introduced without 32-bit testing.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci smoke test

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
The test was introduced here and only smoke tested https://github.com/apple/swift/pull/36822

**Comment by hk-mars** [comment]
Good

**Comment by atrick** [comment]
@swift-ci test macOS

**Comment by atrick** [comment]
The 162 lldb failures are unrelated to this PR.

**Pull request merged**
