### PR TITLE
Frontend: Remove support for the `-check-api-availability-only` flag

### PR DESCRIPTION
**Pull request by tshortli**
The functionality for this flag is no longer necessary because the emit module jobs for deprecated architectures no longer use an artificially low deployment target.

Resolves rdar://104758113

### CODE REVIEW

**Comment by tshortli** [comment]
@swift-ci please test

**Comment by tshortli** [comment]
@swift-ci please test

**Comment by tshortli** [comment]
@swift-ci please test

**Review by xymus — APPROVED** [review]
This looks good! I'm glad we don't have to think about this workaround anymore.

**Pull request merged**
