### PR TITLE
Swift 3 api preserving changes

### PR DESCRIPTION
**Pull request by dabrahams**
- Optimizations for String/Substring interaction
- Makes String(otherString) non-failable for Swift 4

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please benchmark

**Comment by dabrahams** [comment]
@swift-ci Please test

**Comment by dabrahams** [comment]
@airspeedswift Clearly some of the optimization was lurking in other commits.

**Comment by airspeedswift** [comment]
Yup. But take this into master for now and then hunt those down in a separate PR?

**Comment by dabrahams** [comment]
@airspeedswift The regression of StringFromLongWholeSubstringGeneric doesn't bother you?

**Comment by airspeedswift** [comment]
Not if it's only in unoptimized builds... plus does that one get faster once we pull in the other changes?

**Comment by dabrahams** [comment]
Yes, so merging.

**Pull request merged**
