### PR TITLE
IDE: Remove prepareForRetypechecking()

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Comment by benlangmuir** [comment]
I'm happy with this as long as someone has audited all the code-completion entry points to the typechecker to ensure they go through SanitizeExpr (probably via CSGen).  @slavapestov have you done that already? If not, @rintaro could you take a look?

**Comment by slavapestov** [comment]
@benlangmuir I had a quick look a few days ago and I think everything goes through generateConstraints() which does SanitizeExpr. Also I'm not proposing taking this for the 5.1 branch, so if there are issues on master hopefully we'll find them before too long.

**Comment by benlangmuir** [comment]
SGTM, thanks!

**Review by benlangmuir — APPROVED** [review]

**Pull request merged**
