### PR TITLE
[Update Checkout] Print hashes at the end of the successful clone/update.

### PR DESCRIPTION
**Pull request by shahmishal**
- Support dump-hashes with skipped repos
- Remove duplicated code from dump hashes

```
12:03:39 update-checkout succeeded
12:03:39 compiler-rt                        : b3ec1d1c7f3309762b9a0aaaae6c7408c0c6e6a7
12:03:39 sourcekit-lsp                      : 20662cd553ae4b769055d55c6ee49ae52a8824cb
12:03:39 indexstore-db                      : b3b4bbadeab6627cc680b856d3903e3ffa99c5e1
12:03:39 swift-stress-tester                : 9e211a1e9dd19281e54e06575f08c09b3f6da39d
12:03:39 swift-xcode-playground-support     : 8caffe97601cd20f0cfe4fb354e81541f1a7f576
12:03:39 libcxx                             : e81f28f906dcdd4d1667ecf6948c4d837ca3a4db
12:03:39 swift-corelibs-foundation          : 73f2a6217b69f8b781fc1f40963d3c5c2f2a269b
12:03:39 clang                              : e6ad8a4a2747549545461a2d577acd67c25771fe
12:03:39 llbuild                            : 58212a6e3d02d7563423ee47f253c376c2bbb219
12:03:39 cmark                              : 32fa49671d0fc5d1f65d2bcbabfb1511a9d65c27
12:03:39 lldb                               : cbab79f262f80db6c8b41fb8cb4e464a34486330
12:03:39 llvm                               : af1f73e9e916e297f5d224c64b1a185bad068f01
12:03:39 swiftpm                            : f4bbde8cde74df4ffc2a4ec232803df38fc5797a
12:03:39 swift-corelibs-xctest              : a15b58d25d92e438cf134b6f379784bdeac29a10
12:03:39 swift-corelibs-libdispatch         : 4169c8d3382fd1083289ee3b22a349acef584141
12:03:39 swift-syntax                       : aa56781c038bcd10ef23bab9b798721f789a0c53
12:03:39 ninja                              : b25c08bda4949192c69cea4cee057887341a2ffc
12:03:39 swift-integration-tests            : ec906551c1d1db92ade0a2e4abe41b491ab09b83
12:03:39 swift                              : 20fd8dedef8904532e6cbdb8e1d7483790101c8e
12:03:39 clang-tools-extra                  : d4d300e7a4c9186747bd167bb1456601aa1da89f
12:03:39 icu                                : b3054b334d8cf84dcae12df7e1a4f1f5c0997445
```

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci smoke test and merge

**Comment by shahmishal** [comment]
cc/ @benlangmuir

**Comment by gottesmm** [comment]
@shahmishal why did you remove the code for dumping this in json form? That allows one to dump the current state into a .json file and feed it into update-checkout on a different machine and reproduce the exact set of hashes! If you want to change the meaning of dump-hashes, I am fine with that, but please add the json functionality back under a different option. This is another reason why we need update-checkout tests.

**Comment by gottesmm** [comment]
Nm. I read the commit wrong. Sorry for the noise!

**Pull request merged**
