### PR TITLE
[5.0] IRGen: gatherbits - extend the bits before we shift left

### PR DESCRIPTION
**Pull request by aschwaighofer**
* No ABI impact
* Correctness (of enums)

rdar://46264497

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by eeckstein** [comment]
@swift-ci test macOS

**Review by eeckstein — APPROVED** [review]
lgtm!

**Pull request merged**
