### PR TITLE
Make the function to compute the prebuilt module cache path public 

### PR DESCRIPTION
**Pull request by adrian-prantl**
so it can be called by LLDB. (NFC).

rdar://76112632

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Review by nkcsgexi — APPROVED** [review]
Makes sense to me!

**Comment by adrian-prantl** [comment]
@swift-ci smoke test

**Review by benlangmuir — APPROVED** [review]

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Pull request merged**
