### PR TITLE
[SourceKit/DocInfo] Add is_async for properties with async getters

### PR DESCRIPTION
**Pull request by bnbarham**
Resolves rdar://80546521

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
@swift-ci please clean test Linux platform

**Review by hamishknight — APPROVED** [review]
LGTM! Would it also be worth adding a test case for the imported Obj-C method as `async` property case?

**Comment by bnbarham** [comment]
> LGTM! Would it also be worth adding a test case for the imported Obj-C method as `async` property case?

Eh, I figured that we have tests for the importer already so they seemed unnecessary. But it can't hurt, so I've added one anyway (and for the regular function import).

@swift-ci please test

**Comment by bnbarham** [comment]
@swift-ci please clean test Linux platform

**Comment by bnbarham** [comment]
I suppose it would help if I actually added the new files 🤦 

@swift-ci please test

**Comment by bnbarham** [comment]
@swift-ci please test Linux platform

**Comment by bnbarham** [comment]
And again...

@swift-ci please clean test Linux platform

**Comment by bnbarham** [comment]
@swift-ci please clean test Linux platform

**Comment by artemcm** [comment]
@swift-ci please clean test Linux platform

**Comment by bnbarham** [comment]
Thanks for re-running @artemcm!

**Pull request merged**
