### PR TITLE
test: adjust path separator for tests

### PR DESCRIPTION
**Pull request by compnerd**
LLVM improved path canonicalisation in the rebranch.  Adjust the path separator matching to allow the test to pass.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @bnbarham @etcwilde @shahmishal

**Comment by compnerd** [comment]
Thanks @bnbarham for reminding me to regex properly.  Friends don't let friends regex without Swift :-p

**Comment by compnerd** [comment]
CC: @bnbarham @etcwilde @shahmishal @adrian-prantl

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift#62988
https://github.com/apple/llvm-project/pull/5995

@swift-ci please test

**Comment by shahmishal** [comment]
You can't use the PR from same repo :(

**Review by adrian-prantl — APPROVED** [review]

**Comment by compnerd** [comment]
Going to merge this as this is targeting rebranch and the tests are being run at #62988.

**Pull request merged**
