### PR TITLE
[Foundation] Measurement: Add a correct hash(into:) implementation

### PR DESCRIPTION
**Pull request by lorentey**
The new definition normalizes measurements with dimensional units to their base unit, ensuring that the generated hash values are consistent with the definition of ==. It also feeds the unit to the hasher, not just the numerical value.

The old `hashValue` definition was invalid, and has been removed. (I.e., replaced by a compiler-supplied implementation that works in terms of `hash(into:)`.)

rdar://problem/46187171

(This PR was split out of #20685)

### CODE REVIEW

**Comment by lorentey** [comment]
(Tests to cover hashing are coming soon.)

**Review by itaiferber — CHANGES_REQUESTED** [review]
We won't be able to make this change on its own — we have to maintain hash values identically between `Measurement` and `NSMeasurement` for bridging; with just this side, measurements are going to disappear from bridged sets and similar.

We should probably coordinate matching changes within Foundation at the same time.

**Review by parkera — APPROVED** [review]

**Comment by parkera** [comment]
Hm, good point @itaiferber. I was going to suggest also making sure the change made its way to swift-corelibs too.

**Comment by itaiferber** [comment]
We should probably have the implementation also match equality exactly: `NSMeasurement` does not convert two values to their base unit before comparing for equality; unless we change the definition of equality, we'll need hashing to do the same thing.

**Comment by parkera** [comment]
I wonder if we can actually change the definition of equality on either side in a source compatible way.

**Comment by lorentey** [comment]
@itaiferber @parkera There is no need to ever match hash values between structs defined in the Swift overlay and the corresponding Cocoa classes, even if they're bridged. Values get rehashed during bridging when necessary.

Swift and Cocoa have very different approaches to hashing -- starting with the fact that Swift's hash values are explicitly unstable across executions, since they're randomly seeded. Trying to preserve specific hash values for these types is therefore unnecessary.

Differences in the definition of equality are more unfortunate, but String and NSString manages to (mostly) make it work. `Set` and `Dictionary` needs to special-case bridging to handle duplicate String keys that arise during rehashing; it looks like `Measurement` needs the same workaround.

If `Measurement` can be changed to match equality with `NSMeasurement`, then that would simplify matters greatly. That's a source-breaking change, though.

Note that Swift deprecated `hashValue` as a `Hashable` requirement in 4.2; the new hashing interface is `hash(into:)`, and we'll need to migrate the overlays to using it soon. (#20685 has some experimental commits for this.)

**Comment by lorentey** [comment]
To clarify: the issue only affects `Measurement`, not `NSMeasurement`. 

Foundation proper doesn't need to be changed -- `NSMeasurement`'s hashing is consistent with its own definition for `isEqual(_:)`.

**Comment by lorentey** [comment]
@swift-ci please smoke test

**Comment by lorentey** [comment]
This is now subsumed into #23832.

**Pull request closed without merging**
