### PR TITLE
Fix memory error in the implementation of IndexSubset.

### PR DESCRIPTION
**Pull request by bgogul**
Fixes  rdar://problem/56338898

### CODE REVIEW

**Comment by bgogul** [comment]
@swift-ci please smoke test

**Comment by rintaro** [comment]
@swift-ci Please ASAN test

**Review by rintaro — APPROVED** [review]
Makes sense. Thanks for fixing this!

**Review by dan-zheng — APPROVED** [review]
@bgogul: could you please also cherry pick this patch to `tensorflow` branch? Thanks 🙂

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
