### PR TITLE
Cherry-pick commits to 5.1 for -emit-archive

### PR DESCRIPTION
**Pull request by gottesmm**
These cherry-picks are very low risk and give us the benefit of swift being able to emit archives.

### CODE REVIEW

**Comment by gottesmm** [comment]
@jrose-apple @compnerd hows this look?

**Comment by gottesmm** [comment]
@swift-ci test

**Review by compnerd — APPROVED** [review]
This is a good idea to cherry-pick, it will be needed for static library support.

**Review by jrose-apple — APPROVED** [review]
Thanks to @troughton!

**Pull request merged**
