### PR TITLE
[IRGen] Emit name data for unused coverage counters

### PR DESCRIPTION
**Pull request by hamishknight**
Previously, if all the coverage counters for a given SIL function were optimized out, we would have dropped the coverage map on the floor, leading to inaccurate coverage reports in `-O`. However LLVM allows us to emit the name data for the coverage maps separately by defining an `__llvm_coverage_names` global with the name data, which is picked up by its instrumentation lowering pass. Use this to continue to emit coverage maps for functions that do not get emitted.

This then allows us to avoid eagerly emitting coverage mapped functions, allowing them to be lazily emitted as needed even under `-Onone`.

rdar://99813754

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test macOS

**Review by aschwaighofer — APPROVED** [review]
lgtm

**Comment by hamishknight** [comment]
https://github.com/apple/llvm-project/pull/5316

@swift-ci please test macOS

**Comment by hamishknight** [comment]
https://github.com/apple/llvm-project/pull/5316

@swift-ci please test macOS

**Pull request merged**
