### PR TITLE
Update the README.md instructions for utils/update-checkout option.

### PR DESCRIPTION
**Pull request by djwbrown**
Update the README.md instructions for utils/update-checkout option. Should read `--clone-with-ssh`.

### CODE REVIEW

**Comment by kud1ing** [comment]
Seems to include unrelated changes.

**Comment by djwbrown** [comment]
Includes some unrelated changes which have already been merged into apple/swift master (see #424). Should I close this pull request?

**Comment by kud1ing** [comment]
One can prevent this by using a separate branch for the PR.
I am not a Swift developer, i've only noticed it.

**Comment by djwbrown** [comment]
OK, I will close and re-open with an isolated change.

**Comment by kud1ing** [comment]
Ok and maybe add the link https://github.com/apple/swift/blob/master/utils/update-checkout#L89 so the reviewers can more easily see that your change makes sense. Thanks.

**Comment by kud1ing** [comment]
By the way, when you edit a file via the GitHub website, a new branch is created automatically.

**Pull request closed without merging**
