### PR TITLE
reland: Emit coverage mappings for all modules

### PR DESCRIPTION
**Pull request by keith**
This reverts commit 499ed05fd9571c2633acc19c30fa36dcb07a6002.

The change here is to pass 	`-num-threads 1` to avoid an issue on windows where the output of both modules was interleaved. This still goes down the multithreaded codepath so it still validates the fix.

I filed https://bugs.swift.org/browse/SR-13016 for future investigation around this multithreaded issue

https://github.com/apple/swift/pull/32216#discussion_r438459013

### CODE REVIEW

**Comment by CodaFi** [comment]
Do you have an SR for the XFAIL on Windows?

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by keith** [comment]
added to the description, also happy to add in a comment there if you'd prefer!

**Comment by CodaFi** [comment]
That's all I need for now!

To aid your debugging, have you tried marking both files as `-primary-file`?

**Comment by keith** [comment]
Interesting, I'm still working on getting a windows VM setup to actually debug at all 😞 but that's a good thing I can try!

**Comment by keith** [comment]
seems like my XFAIL didn't work, does it have to be at the top or something? I copy pasted from some other test and that's the only major difference I see

**Comment by CodaFi** [comment]
Try using `UNSUPPORTED OS=windows-msvc` then.

**Comment by keith** [comment]
I tested your primary-file idea on macOS and it still works as expected, I pushed that here and removed the XFAIL, do you mind re-running the tests so we can see if that works for windows too (I'm still building on my windows VM)

**Comment by keith** [comment]
looks like we commented around the same time, I can push that if this option doesn't work while I continue to debug it

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by keith** [comment]
hrm this windows failure looks like a flake

**Comment by CodaFi** [comment]
@swift-ci smoke test Windows

**Comment by keith** [comment]
Yay! It looks like your idea worked! Thanks a ton!

**Comment by keith** [comment]
Ah crap, it looks like while the test did pass in this configuration, it's because it's not actually validating the right behavior. If I revert my actual change and run with the `primary-file` args on macOS, it still passes.

**Comment by keith** [comment]
I've reverted that change so that it fails again, and will continue to debug a bit, I now have a windows environment setup and I can't reproduce the CI failure 😞

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by keith** [comment]
@swift-ci please test Windows platform

**Comment by keith** [comment]
was hoping the behavior might differ if I was trying to rebuild on the same commit

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by keith** [comment]
Yippee it passed!

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by keith** [comment]
Thanks again everyone for your help!

**Pull request merged**
