### PR TITLE
Correct spelling mistake in `SetAlgebra` protocol heading comment

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by stefanstefan2001** [comment]
No spelling mistake here:)(.
iff mens if and only if

**Comment by mesmerizingr** [comment]
Wow, thanks 🙂 Didn't know that 🤔

**Comment by mesmerizingr** [comment]
If it's [this](https://en.wikipedia.org/wiki/If_and_only_if#Origin_of_iff) case then reject this change.

**Comment by gribozavr** [comment]
@mesmerizingr Yes, this is the case.

**Pull request closed without merging**
