### PR TITLE
Add libSwiftScan entry-points to query supported compiler flags and compiler features

### PR DESCRIPTION
**Pull request by artemcm**
For the client library (`libSwiftDriver`), this is critical for multiplexing library instances, and for compatibility with different versions of `libSwiftDrvier`.

Resolves rdar://73631930

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by nkcsgexi** [comment]
Thanks for adding these! Can we change the design to returning the full list of supported arguments and features instead of checking if one is supported? The benefit is that the client side has better debuggability because we have the full list visible from swift-driver. The logic of checking if an argument is supported can be trivially implemented from the client side.

**Comment by artemcm** [comment]
> Thanks for adding these! Can we change the design to returning the full list of supported arguments and features instead of checking if one is supported? The benefit is that the client side has better debuggability because we have the full list visible from swift-driver. The logic of checking if an argument is supported can be trivially implemented from the client side.

Yeah, I think that's a better thing to do, I'll make the change.

**Comment by artemcm** [comment]
@nkcsgexi, I've changed the query format as per your suggestion.

**Review by nkcsgexi — APPROVED** [review]
LGTM!

**Comment by artemcm** [comment]
@swift-ci please smoke test

**Pull request merged**
