### PR TITLE
[Constraint system] Cleanups for function builders support for if let/if case let

### PR DESCRIPTION
**Pull request by DougGregor**
Various cleanups to improve function builders support for if let/if case let:
* Expand` SolutionApplicationTarget` to `StmtConditions`.
* Properly deal with `as` patterns by not prechecking patterns (oops).

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Review by xedin — APPROVED** [review]

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test macOS

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
Failure is unrelated to my change (this time).

**Comment by DougGregor** [comment]
@swift-ci please smoke test macOS

**Pull request merged**
