### PR TITLE
[benchmark] Compile and run benchmarks on Linux

### PR DESCRIPTION
**Pull request by mtake**
Exclude Objective-C or Mach specific implementations, or replace them with POSIX based implementations so that we can compile and run benchmarks on Linux.

(This PR supersedes #7810 in favor of not including unrelated merged commits from other people.)

### CODE REVIEW

**Comment by mtake** [comment]
@gottesmm I noticed #7860 has been merged. I would appreciate if you can do the remaining integration work for building the benchmarks on Linux in the smoketest/full test presets.

**Comment by gottesmm** [comment]
@mtake It is going to take me time to do it. I have other things on my schedule that are more important. Sorry.

Additionally, that change was actually reverted since some people don't include their buildbot config in presets *looks at lldb* = p. So I didn't see it to update it.

**Comment by lplarson** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@lplarson IMO, we should just get this in as an incremental improvement as long as it does not break the linux build or affect the darwin build. I wish that we did have the infrastructure in place so we could get this on in the normal linux build. But my schedule is not being helpful. I don't want to hold this up.

**Comment by lplarson** [comment]
@swift-ci benchmark

**Comment by lplarson** [comment]
@swift-ci benchmark

**Comment by lplarson** [comment]
@swift-ci benchmark

**Comment by mtake** [comment]
@lplarson Looks like the build error https://ci.swift.org/job/swift-PR-osx-perf/389/consoleFull#-278967002ee1a197b-acac-4b17-83cf-a53b95139a76 is relared to the @phausler's commit
https://github.com/apple/swift/commit/dc783c064c4a027c14c7805a068ec817e074592b#diff-60fab3968490aded2585457736a8b091

**Comment by lplarson** [comment]
@swift-ci smoke test and merge

**Pull request merged**
