### PR TITLE
Handle more copy-move-assignment cases

### PR DESCRIPTION
**Pull request by etcwilde**
The `copy-move-assignment-irgen` test case was failing on my Linux machine because the input pointers into the copy-move function call had additional attributes, and the function mangle was slightly different indicating that the function had been merged. I broke this PR into three commits to try making it clearer what each transform was.

- The first one splits the parameters going into the copy-assignment call to handle the possible presence of the additional attributes.
Here is what the call looks like when it fails: 
`call void @_ZN31NonTrivialCopyAndCopyMoveAssignC2ERKS_Tm(%struct.NonTrivialCopyAndCopyMoveAssign* noundef nonnull align 4 dereferenceable(5) %2, %struct.NonTrivialCopyAndCopyMoveAssign* noundef nonnull align 4 dereferenceable(5) %4)`.
The test did not contain any attributes on the parameter pointers.

- The second commit adds `_ZN31NonTrivialCopyAndCopyMoveAssignC2ERKS_Tm` to the accepted list of function mangles. My macBook is showing another call form still `@_ZN31NonTrivialCopyAndCopyMoveAssignC1EOS_`. I haven't fully made sense of what this demangles to, so I'm not prepared to suggest that it's correct at the moment though.

- The third commit reduces the cases down to alternation over only the parts of the function that are different instead of on the entire mangle.

### CODE REVIEW

**Comment by etcwilde** [comment]
@swift-ci please test

**Comment by etcwilde** [comment]
@swift-ci please test

**Comment by etcwilde** [comment]
@swift-ci please test

**Comment by etcwilde** [comment]
Okay, dropping the shortened version. Windows was giving me too much headache.

**Comment by etcwilde** [comment]
@swift-ci please test

**Review by hyp — APPROVED** [review]
Thank you!

**Comment by buttaface** [comment]
@etcwilde, I think [this update broke this test for 32-bit platforms like Android armv7](https://ci-external.swift.org/job/oss-swift-RA-linux-ubuntu-16.04-android/lastFailedBuild/consoleText):
```
/home/ubuntu/jenkins/workspace/oss-swift-RA-linux-ubuntu-16.04-android/swift/test/Interop/Cxx/class/copy-move-assignment-irgen.swift:23:11: error: CHECK: expected string not found in input
// CHECK: call {{void|\%struct.NonTrivialCopyAndCopyMoveAssign\*}} @{{_ZN31NonTrivialCopyAndCopyMoveAssignC1EOS_|_ZN31NonTrivialCopyAndCopyMoveAssignC2EOS_|_ZN31NonTrivialCopyAndCopyMoveAssignC1ERKS_Tm|_ZN31NonTrivialCopyAndCopyMoveAssignC2ERKS_Tm|"\?\?0NonTrivialCopyAndCopyMoveAssign@@QEAA@AEBU0@@Z"}}(
          ^
<stdin>:60:139: note: scanning from here
 %6 = call %struct.NonTrivialCopyAndCopyMoveAssign* @_ZN31NonTrivialCopyAndCopyMoveAssignD2Ev(%struct.NonTrivialCopyAndCopyMoveAssign* %1)
                                                                                                                                          ^
```

**Comment by finagolfin** [comment]
You're right, the problem is elsewhere, not this pull.

**Pull request merged**
