### PR TITLE
Fixes in response to feedback on #37771.

### PR DESCRIPTION
**Pull request by gottesmm**

### CODE REVIEW

**Comment by gottesmm** [comment]
I created the branch but forgot to push it!

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test macOS platform

**Review by benlangmuir — APPROVED** [review]
Thanks!

**Comment by gottesmm** [comment]
@swift-ci smoke test macOS platform

**Pull request merged**
