### PR TITLE
Don't use resilient getter for playgroundPrintHook when resilience is off

### PR DESCRIPTION
**Pull request by kubamracek**
While the stdlib doesn't yet have a way of turning Library Evolution off, I'm exploring that in <https://github.com/apple/swift/pull/33535>. Let's fix the code in `_shouldReportMissingReflectionMetadataWarnings` to be able to handle both cases (resilience on, or off).

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test stdlib with toolchain

**Review by compnerd — COMMENTED** [review]
This keeps the old behavior so this should be safe for the Darwin side.  Do you want to add the knob to control this as part of the change?  It doesn't seem too useful as it is.

**Comment by kubamracek** [comment]
The knob is here: <https://github.com/apple/swift/pull/33443>. Unfortunately, it's a bit of a chicken-and-egg: The knob is also not useful because switching it fails the build (because of this PR, and others).

I was thinking of fixing the build first, but I guess all the piece are interconnected. Whatever's your preference :)

**Comment by compnerd** [comment]
Personally, I tend to favor a single commit for functionality.  But, I can see how this could make it easier to get there.  I think I have a slight preference for this to be part of the knob introducing change, but you can make the call based on difficulty.

**Review by compnerd — APPROVED** [review]

**Pull request merged**
