### PR TITLE
update swift-collections to 0.0.4

### PR DESCRIPTION
**Pull request by tomerd**
motivation: swift-collections 0.0.4 includes critical fixes for SwiftPM use of it

changes: update swift-collections to 0.0.4

### CODE REVIEW

**Comment by tomerd** [comment]
cc @lorentey

**Review by lorentey — APPROVED** [review]
LGTM -- the 0.0.4 release has now been tagged, so this should be testable!

**Comment by lorentey** [comment]
@swift-ci test

**Comment by tomerd** [comment]
cc @compnerd

**Comment by tomerd** [comment]
@shahmishal this is needed to unblock https://github.com/apple/swift-package-manager/pull/3595

**Comment by shahmishal** [comment]
@swift-ci test windows

**Pull request merged**
