### PR TITLE
[cxx-interop][SwiftCompilerSources] Use `swift::SILDebugLocation` instead of `BridgedLocation`

### PR DESCRIPTION
**Pull request by egorzhdan**
rdar://83361087

### CODE REVIEW

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Review by eeckstein — APPROVED** [review]
nice!

**Pull request merged**
