### PR TITLE
Small reflection fixes

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@aciidb0mb3r This looks like a swiftpm bug unrelated to my change -- have you seen it before? https://ci.swift.org/job/swift-PR-Linux-smoke-test/7429/consoleFull#-18214046556633f0f-8823-4f82-9a4a-0c0d97ce7760

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Comment by aciidb0mb3r** [comment]
Haven't seen this one ☹️

**Pull request merged**
