### PR TITLE
[concurrency] Overload resolution for async-looking ObjC methods

### PR DESCRIPTION
**Pull request by kavon**
# Problem Summary

Suppose we have the following declaration for `Delegate` in ObjC:

```objc
#import <Foundation/Foundation.h>

@interface Request : NSObject

@end

@interface Delegate : NSObject

  // Error because request is _Nonnull AND not exactly 'NSObject'
- (void)addWork:(Request * _Nonnull)request completionHandler:(void (^ _Nullable)(void))handler;

@end
```

A call to a `Delegate.addWork(_: completionHandler :)` in Swift such as:

```swift
func f() {
  let r = Request()
  let d = Delegate()
  d.addWork(r)
}
```

is currently viewed as ambiguous when concurrency extensions are enabled, because of two factors that are simultaneously true:
1. async-looking ObjC methods with a completion handler are automatically made available with an `async` version.
2. the completion handler argument for `Delegate.addWork` is optional and is not provided at this call-site.

Here are the two overloads of `Delegate.addWork` that are considered by the constraint solver:

```
1. decl __ObjC.(file).Delegate.addWork(_:completionHandler:) : (Delegate) -> (Request, (() -> Void)?) -> Void
2. decl __ObjC.(file).Delegate.addWork : (Delegate) -> (Request) async -> Void
```

Currently, the problem is that if you get a bad ordering of overload options in the solver, where overload (2) is checked first, the solver decides to not consider other options (i.e., short-circuit) resulting in a selection of overload 2 despite it having a non-zero "badness" score because it results in a sync/async mismatch. This current patch tells the constraint solver to keep considering other options in this case (i.e., the mismatch) so that it lands correctly on overload 1, but more generally I think this change to short-circuiting is perhaps not a good solution.

In particular, I don't necessarily think this call-site is ambiguous if additional contextual information is available. For example, I believe it's not possible to call an async function (i.e., pick overload 2) from a synchronous context, even if the programmer tried to add an `await` to the call expression. This happens to be the case for `f` above. Additionally, even if the context of the call-site were asynchronous, the call-site is not marked with `await` so the only correct choice here is to pick overload 1. 

Thus, perhaps it's possible to filter out incorrect overloads during the enumeration of overload possibilities, or something along those lines? There is also some infrastructure for "favored" overloads that I'm not yet familiar with.

# Details

This PR fixes SR-13760 / rdar://70543421

TODO:
- [x] Fix bug.
- [x] Create regression test.

### CODE REVIEW

**Comment by DougGregor** [comment]
This looks like a reasonable short-term fix. I'm not sure we want to filter out the async overloads entirely, but I suppose we could. Is there a small-scale regression test you can include?

**Comment by varungandhi-apple** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]

**Comment by DougGregor** [comment]
Clean bill of health, merging!

**Comment by xedin** [comment]
A better fix here would be to prevent CSGen hacks from favoring overloads which would result in async/sync mismatches, it would prevent short-circuiting logic from kicking-in.

**Pull request merged**
