### PR TITLE
[LookupVisibleDecls] Tweak unquialified lookup

### PR DESCRIPTION
**Pull request by rintaro**
- Show static var decls in non-qualified metatype lookup
- Show enum element decls in non-qualified metatype lookup
- Never show initializers in non-qualified lookup
- Perform instance lookups in lazy var initializer
- Perform non-qualified metatype lookup inside static func

rdar://problem/57622639

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by CodaFi** [comment]
@swift-ci smoke test macOS

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test Linux

**Review by benlangmuir — COMMENTED** [review]
Needs tests :smile:

**Comment by rintaro** [comment]
Oops! Forgot to `git add` 😢

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Review by benlangmuir — APPROVED** [review]

**Comment by rintaro** [comment]
@swift-ci Please smoke test Linux

**Comment by rintaro** [comment]
@swift-ci Please smoke test OS X

**Pull request merged**
