### PR TITLE
[5.7] SILGen: Emit a closure literal in a function conversion as the converted type.

### PR DESCRIPTION
**Pull request by jckarter**
Explanation: Eliminates the reabstraction thunk emitted when calling a function that takes an `(A...) async throws -> R` function parameter with a literal closure argument that doesn't throw, by folding the type conversion into the closure literal's code generation. This is particularly interesting for the `Task.init` constructors, since the symbol name of the closure entry point that the runtime ultimately sees is useful for instrumentation purposes.

Scope: An optimization that removes unnecessary thunks from code generation.

Risk: Low. This unblocks an optimization, which has already been working in the 5.7 branch for pretty much all code we've thrown at it, to apply in more situations.

Testing: Swift CI

Issue: rdar://92756873

Reviewed by: @rjmccall

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Review by tbkka — APPROVED** [review]

**Comment by jckarter** [comment]
Interesting. In `test/stdlib/unmanaged_rc.swift`, it no longer inlines the closure to `_withUnsafeGuaranteedRef`. Let me see if I can fill in the missing pattern match to unblock that inlining.

**Comment by jckarter** [comment]
@swift-ci Please test

**Pull request merged**
