### PR TITLE
[OSSACompleteLifetime] Recurse into scoped addresses.

### PR DESCRIPTION
**Pull request by nate-chandler**
Previously, when determining and completing lifetimes of scoped addresses, `computeTransitiveLiveness` was used to determine the liveness used for completing the lifetime.

That approach had two problems:
(1) The function does not find scope-ending uses of `load_borrow`s. The result was determining that the lifetime of the enclosing `store_borrow` ended before that of the `load_borrow`.
(2) The function did not complete lifetimes of values defined within the scoped address whose lifetimes the scoped address had to contain. This was an inconsistency between the handling of scoped addresses and that of values.

Here, both are addressed by implementing a `TransitiveAddressWalker` (as `computeTransitiveLiveness`'s callee does) which not only visits existing `end_borrow`s of `load_borrows` but completes them (and other inner guaranteed values or scoped addresses).

rdar://141246601

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Comment by nate-chandler** [comment]
Source compat failures match failures in baseline
```
========================================
Failures:
  FAIL: SwiftLint-Legacy, 4.2, 60f98e, Swift Package
  FAIL: SwiftLint-Legacy, 4.0, 60f98e, Swift Package
```

**Review by meg-gupta — APPROVED** [review]

**Pull request merged**
