### PR TITLE
[Sema] Descriptive -debug-time-function-bodies

### PR DESCRIPTION
**Pull request by modocache**
Generated getters and setters don't have their names printed alongside them in the log output for `-debug-time-function-bodies`. Here are some examples:

```
get {}
set {}
final get {}
final set {}
@objc get {}
@objc set {}
@objc final get {}
@objc final set {}
(closure)
```

Re-use the logic from the diagnostics for `-warn-long-function-bodies=` in order to print getter and setter names (but not attributes such as `final` or `@objc`), for example:

```
getter bar
setter bar
global function foo()
global function baz(one:two:three:)
deinitializer deinit
initializer init()
```

Addresses [SR-2910](https://bugs.swift.org/browse/SR-2910). This might effect consumers of `-debug-time-function-bodies` that parse the function names, since their format is changed here. For example, the UI in https://github.com/RobertGummesson/BuildTimeAnalyzer-for-Xcode may change.

---

This is some initial work related to an email I sent to the swift-dev mailing list: https://lists.swift.org/pipermail/swift-dev/Week-of-Mon-20171106/005934.html. Feedback there or here would be appreciated!

I noticed there were no tests for `-debug-time-function-bodies`. Should I add some?

### CODE REVIEW

**Comment by modocache** [comment]
@swift-ci please smoke test

**Comment by modocache** [comment]
@jrose-apple, are you a good person to review this change?

**Comment by jrose-apple** [comment]
This looks fine. There are no tests for these options because they're not really supported, but I'm not against adding some.

I feel like we do this kind of thing all over the compiler—see also `swift::printDeclDescription` in PrettyStackTrace.cpp, `printArtificialName` in Index.cpp, `getName` in IRGenDebugInfo.cpp, `SILGenModule::getMagicFunctionName` in SILGenFunction.cpp, and possibly more. (This list is from searching for calls to `getAccessorStorageDecl()`.) I wonder if it's worth having a bug to unify these a little more.

**Comment by modocache** [comment]
I created tasks https://bugs.swift.org/browse/SR-6415 and https://bugs.swift.org/browse/SR-6416 and assigned them to myself. Thanks, @jrose-apple!

**Pull request merged**
