### PR TITLE
SR-10689: Fix bugs of DataProtocol's firstRange(of:in:)/lastRange(of:in:).

### PR DESCRIPTION
**Pull request by YOCKOW**
`DataProtocol`'s `firstRange(of:in:)` and `lastRange(of:in:)` return a wrong value or crash under some conditions because they handle indices incorrectly. 

Resolves [SR-10689](https://bugs.swift.org/browse/SR-10689).

----
Note: This PR is a counterpart of https://github.com/apple/swift-corelibs-foundation/pull/2499 .

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by YOCKOW** [comment]
I'm sorry. The failure is caused by my rudimentary mistake. I'll fix it.

**Comment by YOCKOW** [comment]
I am sorry for the late fix. Now it is rebased and would pass tests.

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by CodaFi** [comment]
apple/swift-corelibs-foundation#2499

@swift-ci test

**Comment by YOCKOW** [comment]
All tests of this PR and [scf#2499](https://github.com/apple/swift-corelibs-foundation/pull/2499) have passed.
I believe these are not stale.

**Review by phausler — APPROVED** [review]
Looks good to me

**Comment by YOCKOW** [comment]
@phausler 
Thank you very much.
It would be ready to be merged.

**Pull request merged**
