### PR TITLE
[update-checkout] Add support to clone libcxx and clang-tools-extra f…

### PR DESCRIPTION
**Pull request by shahmishal**
…or master, master-next and swift-5.0-branch scheme

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci smoke test

**Comment by compnerd** [comment]
@shahmishal - libc++ without libc++abi isn't that great of an idea.  If you are going to add libc++, Id say you should add libc++abi as well.

**Comment by shahmishal** [comment]
cc/ @dexonsmith @benlangmuir 

@compnerd Thanks for pointing this out to me.

**Comment by dexonsmith** [comment]
> @shahmishal - libc++ without libc++abi isn't that great of an idea. If you are going to add libc++, Id say you should add libc++abi as well.

On Darwin, the libc++ headers are NOT in the SDK, and live along-side Clang.  They are needed in order to create a working C++ toolchain.  But the libc++abi headers are in the SDK, so they aren't needed here.

Perhaps installing the libc++ headers should be conditional on the platform (i.e., only on macOS)?

**Comment by compnerd** [comment]
@shahmishal - oh if you are ensuring that libc++ is not built, then that is okay.  But you can't really build libc++ without libc++abi (or libsupc++ or libcxxrt, but those paths aren't as well tested) or msvcrt.

**Comment by dexonsmith** [comment]
Right, we're just looking to install libc++ headers here.  Not trying to build libc++.1.dylib.

**Comment by shahmishal** [comment]
@swift-ci smoke test Linux

**Pull request merged**
