### PR TITLE
[ParseableInterface] Fix failing to build a module when the importing file has errors.

### PR DESCRIPTION
**Pull request by nathawes**
We were checking the parent invocation's DiagnosticEngine rather than the sub-instance's to determine if there were any errors building the module, which meant we would fail to load the module if there were errors prior to the import statement in the importing file.

This also meant code completion would fail to load the module, because it always emits a bogus error in order to mark the AST as erroneous so that different parts of the compiler (e.g. the verifier) have less strict assumptions.

rdar://problem/43906499

### CODE REVIEW

**Comment by nathawes** [comment]
@swift-ci please smoke test

**Review by jrose-apple — APPROVED** [review]
Oops. I'm guessing at one point before ForwardingDiagnosticConsumer we were just sharing engines; this makes more sense!

**Comment by nathawes** [comment]
@swift-ci smoke test

**Review by harlanhaskins — APPROVED** [review]

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test

**Comment by nathawes** [comment]
@swift-ci please smoke test

**Comment by nathawes** [comment]
@swift-ci please smoke test

**Comment by jrose-apple** [comment]
@nathawes Brent had to revert this because the test failed on the 32-bit iOS simulator.

**Comment by nathawes** [comment]
Thanks – I'll take a look today.

**Pull request merged**
