### PR TITLE
SILGen: Fix block to func reabstraction thunks block argument handling

### PR DESCRIPTION
**Pull request by aschwaighofer**
The block parameter is passed @guaranteed if we use a @callee_guaranteed
convention.

SR-5441
rdar://33255593

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test linux

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test macos

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test macos

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test

**Comment by CodaFi** [comment]
Looks like this is superseded by 3e04f21.

**Pull request closed without merging**
