### PR TITLE
[AutoDiff] Adopt AdditiveArithmetic protocol for AD

### PR DESCRIPTION
**Pull request by rxwei**
SE proposal [Make Numeric Refine a new AdditiveArithmetic Protocol](https://forums.swift.org/t/make-numeric-refine-a-new-additivearithmetic-protocol/17269) is currently being considered for a formal review by the core team. This patch adopts the new protocol and switches to unified operator lookup for the automatic differentiation transform. Concretely, this patch includes the following:

1. Apply #19989: Introduce `AdditiveNumeric` and refactor `Numeric`.
2. Make `VectorNumeric` refine `AdditiveNumeric`, sharing additive arithmetic operators.
3. Remove `*(Self, Self)` to make `VectorNumeric` correctly define an abstract vector space (also discussed on the SE thread), keeping only `*(Scalar, Self)` and `*=(inout Self, Scalar)`.
4. Further constrain `Differentiable`'s `TangentVector` and `CotangentVector` to be also differentiable. This limits customization points that won't make sense mathematically.
5. Since we are no longer dealing with `+` defined separately in `VectorNumeric` and `Numeric`, the AD core transform has been refactored to use the unified `+` operator under `AdditiveArithmetic`.

Note: Some ABI stability tests and operator resolution tests have been temporarily disabled to prevent duplicate work: #19989 is going to handle all of this anyway and the TF branch will be patched when #19989 lands in master.

Todo next:
Remove `init(_:)` from `VectorNumeric`. This is a degenerate case because seeding a VJP using a vector of 1s to get a "gradient" is simply incorrect. AD type checking, the core transform, and primitive definitions in the TF module need to be refactored to make this change possible.

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Review by dan-zheng — APPROVED** [review]
LGTM!
I'm a fan of the unification of the `+` operator under `AdditiveArithmetic`.
Also a fan of renaming `ScalarElement` to `Scalar` and `Dimensionality` to `Shape`.

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow macos

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
Oops, should've squashed it.

**Pull request merged**
