### PR TITLE
[Sema/ClangImporter] Improvements to witness matching

### LINKED ISSUE #65730: ClangImporter: Subclass composition from applying imported `@Sendable` to class type not wrapped in existential
```objc
@interface C @end

__attribute__((__swift_attr__("@Sendable")))
C *test();
```

The imported result type of `test` is the constraint type `C & Sendable`, but should be `any C & Sendable`.

**Environment**
- Swift 5.9-dev (c1d5118c21d)

### PR DESCRIPTION
**Pull request by xedin**
- Fix locators for requirement-witness matching (modern locators can be anchored on declarations)

- Warn about sendability mismatches associated with ObjC requirements

   Instead of stripping concurrency, handle stripping gracefully during `repairFailures` and reflect that in the solution score.
   This way we can maintain source compatibility and allow adding concurrency annotations.

-  ClangImporter: Wrap compositions with Sendable protocol into existentials

Resolves: https://github.com/apple/swift/issues/65730

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility release

**Comment by xedin** [comment]
@swift-ci please test

**Review by hborla — APPROVED** [review]
Should we replace the ObjC checks with a check for preconcurrency requirements? I think we want the same behavior for Swift requirements that are marked `@preconcurrency`, and ObjC isn't special other than all imported declarations are treated as `@preconcurrency`.

**Comment by xedin** [comment]
I want to investigate expanding this separately, main goal was to remove the workaround for ObjC requirements that got concurrency stripped always and thus had no path for witnesses to be updated...

**Pull request merged**
