### PR TITLE
Distributed: Remove unnecessary unwrapping of TypeAliasType

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by ktoso** [comment]
linux error seems unrelated `fatal error: module map file '/home/build-user/build/buildbot_linux/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/release/llbuildBasic.build/module.modulemap' not found`

**Comment by ktoso** [comment]
@swift-ci please smoke test Linux

**Comment by ktoso** [comment]
Failure was unrelated: 

`fatal error: module map file '/home/build-user/build/buildbot_linux/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/release/llbuildBasic.build/module.modulemap' not found` https://ci.swift.org/job/swift-PR-macos-smoke-test/9867/console

**Review by xedin — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please smoke test

**Pull request merged**
