### PR TITLE
Remove unneeded default case from StdlibUnittest

### PR DESCRIPTION
**Pull request by natecook1000**
#### What's in this pull request?

This removes a default case that was triggering a warning on every build.
#### Resolved bug number: n/a

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by gribozavr** [comment]
We need this for bringing up resilience.  Could you add a comment that says that instead of removing it?

**Comment by natecook1000** [comment]
Oh sure—is there a way to suppress the warning?

**Comment by gribozavr** [comment]
I'm afraid there isn't.

**Comment by natecook1000** [comment]
Comment added. I'll try to suppress the warning in my brain.

**Pull request merged**
