### PR TITLE
Temporarily put uses of "Span" and "RawSpan" behind an experimental feature flag

### PR DESCRIPTION
**Pull request by DougGregor**
While Span is present, we don't yet have an official way to create Span instances. Until then, put uses of Span and RawSpan behind an experimental feature flag (`Span`) that must be set to use these.

Addresses rdar://139308307.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Review by glessard — COMMENTED** [review]
Looks like what I hoped for.

**Comment by glessard** [comment]
@swift-ci please build toolchain macOS platform

**Review by glessard — APPROVED** [review]

**Review by stephentyrone — APPROVED** [review]

**Comment by DougGregor** [comment]
Update incoming for the pointer-bounds tests before I can merge this

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Pull request merged**
