### PR TITLE
[Gardening] Rename getInOutOrLValueObjectType to getWithoutSpecifierType

### PR DESCRIPTION
**Pull request by CodaFi**
Factored out a simple `sed` to rename this primitive.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please smoke test and merge

**Comment by CodaFi** [comment]
Please test with following PR:
apple/swift-lldb#228

@swift-ci Please smoke test

**Comment by CodaFi** [comment]
⛵️

**Comment by jrose-apple** [comment]
`lvalue` isn't a specifier. I'm not sure this is the way to go. @rudkx, @rjmccall?

**Comment by CodaFi** [comment]
I debated calling it something like `getWithoutEphemeralType()`, but we don't use the terminology in the manifesto consistently throughout the codebase.

**Comment by CodaFi** [comment]
`@lvalue` *is* also a type specifier in the same vein, just one that cannot be spelled.

**Comment by jrose-apple** [comment]
I'm not sure what your definition of "specifier" is that encompasses "var", "let", "none", "inout", and "lvalue".

**Comment by rudkx** [comment]
I don't really see how the old name was particularly offensive or the new one particularly better. I think `getMaterializableObjectType()` might be an improvement except the result would not always pass the `isMaterializable()` test since we do not reform tuples with the `inout` removed from the elements.

**Comment by CodaFi** [comment]
> I don't really see how the old name was particularly offensive

If we're going to be adding new attributes, this name is going to have to be

`getInOutOrLValueOrSharedOrObjectType`

**Comment by rjmccall** [comment]
This is temporary, right?  We won't actually be introducing a SharedType, and InOutType will be going  away.  I'm not sure there's much point in renaming stuff.

**Pull request merged**
