### PR TITLE
[DebuggerSupport] Attempt expanding objects with `.class` display style

### PR DESCRIPTION
**Pull request by vedantk**
When pretty-printing objects, attempt to expand & print objects which
have the `.class` display style even if they do not have any instance
variables. The pretty-printer will still bail out if the object does not
conform to CustomReflectable.

This is enough to teach the pretty-printer to format bridged NSStrings.

rdar://36843869

### CODE REVIEW

**Comment by vedantk** [comment]
@swift-ci please smoke test

**Comment by vedantk** [comment]
pre-patch:
▿ StructWithTwoMembers\n  - a : 1\n

post-patch:
▿ StructWithTwoMembers\n  - a : 1\n  - b : Hello World\n

**Comment by vedantk** [comment]
(This fixes some expression evaluation test failures in lldb re: strings, although some tests for summary generation remain broken.)

**Review by milseman — COMMENTED** [review]
I'm not super familiar with `DebuggerSupport.swift`, but this LGTM

**Review by dcci — APPROVED** [review]
LGTM.

**Comment by vedantk** [comment]
The Linux smoke tester timed out after ~2hrs. I'll try again.

**Comment by vedantk** [comment]
@swift-ci Please smoke test Linux platform

**Comment by vedantk** [comment]
@swift-ci Please smoke test and merge

**Comment by vedantk** [comment]
@swift-ci Please smoke test and merge

**Pull request merged**
