### PR TITLE
[Serialization] Recover from deserialization failures in `ModuleFile::lookupClassMembers`

### PR DESCRIPTION
**Pull request by xymus**
Code attempting to access a missing member on an `AnyObject` triggers a typo correction that deserializes all class members in imported modules, even non-public ones. This change makes sure the compiler recovers from deserializing class members referencing implementation-only imported types.

rdar://79427805

### CODE REVIEW

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Review by bnbarham — APPROVED** [review]

**Comment by xymus** [comment]
@swift-ci Please test Windows platform

**Comment by xymus** [comment]
@swift-ci Please smoke test macOS

**Comment by xymus** [comment]
@swift-ci Please test Windows platform

**Review by artemcm — APPROVED** [review]

**Pull request merged**
