### PR TITLE
[sil] Eliminate the src parameter from end_borrow.

### PR DESCRIPTION
**Pull request by gottesmm**
This does not eliminate the entrypoints on SILBuilder yet. I want to do this in
two parts so that it is functionally easier to disentangle changing the APIs
above SILBuilder and changing the underlying instruction itself.

rdar://33440767

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Review by atrick — APPROVED** [review]
LGTM

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Pull request merged**
