### PR TITLE
Putting white spaces in between if/while clauses and braces.

### PR DESCRIPTION
**Pull request by wxxsw**
#### What's in this pull request?

Fix whitespaces.

### CODE REVIEW

**Comment by gottesmm** [comment]
Can you change the commit message so that it specifically says that you are putting white spaces in between if/while clauses and braces with an example.

**Comment by wxxsw** [comment]
Thx @gottesmm

**Comment by gottesmm** [comment]
Can you put a dummy example into the commit message so that people can understand without reading the actual diff what the patch does?

Something like.

[gardening] Put white spaces in between if/while clauses and braces where it is missing.

For instance:

'if (foo){' => 'if (foo) {'

**Comment by wxxsw** [comment]
Thank you, it's better.

**Comment by gottesmm** [comment]
@swift-ci Please test and merge

**Comment by gottesmm** [comment]
The test failure looks like some other issue. These changes should be NFC.

**Comment by gottesmm** [comment]
I had to revert this change since it introduced 80+ line violations. Please file a new diff with these changes, sans any of those 80+ line violations.

**Comment by wxxsw** [comment]
https://github.com/apple/swift/pull/2025 @gottesmm

**Pull request merged**
