### PR TITLE
Fix lifetime of intermediate phis created by the SSAUpdater for RLE

### PR DESCRIPTION
**Pull request by meg-gupta**
The lifetime of the final phi created by the SSAUpdater was adjusted previously.
With this PR, the lifetime of all intermediate phi's will be fixed by creating destroy_values in leaking blocks.

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci test

**Review by eeckstein — APPROVED** [review]
LGTM!

**Comment by meg-gupta** [comment]
The test failure is not related to this PR.

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Comment by meg-gupta** [comment]
@swift-ci test Linux Platform

**Pull request merged**
