### PR TITLE
RFC / DO NOT MERGE – Remove TVO_CanBindToInOut, add TVO_IsGenericTypeParam

### PR DESCRIPTION
**Pull request by davezarzycki**
As a part of the ongoing "war on InOutType", I've made an attempt at cleaning up the TypeVariable options. After this patch series, `TVO_CanBindToInOut` is gone and the validation test suite still passes on my Linux box. Feedback would be appreciated. Please note that I did need to XFAIL one of the "compiler crasher" tests, but this seemed acceptable.

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please test

**Comment by CodaFi** [comment]
It’s an interesting idea, but isn’t the inverted polarity spreading the flag even further implicitly?  An audit of this flag should pretty much only need to conserve it around closures for inout inference - everywhere else is suspect (you found one place in the opening process that can be flipped already).

**Comment by davezarzycki** [comment]
Are you saying that the use of `TVO_CanBindToInOut` is not always justified, and that removing it as much as possible is preferable to making it be the default?

**Comment by CodaFi** [comment]
It's pretty much never needed.  @slavapestov applied it to all the type variables at the time out of an abundance of caution.

**Comment by davezarzycki** [comment]
Got it. Thanks!

**Comment by rudkx** [comment]
FWIW, I looked at removing some of these recently, specifically in the pattern binding code that you've been working on, and the problem is that we then fail to get a solution in the solver and produce a worse diagnostic.

I think if we eliminate the inout-to-pointer conversions for operators (as seen [here](https://forums.swift.org/t/ban-inout-to-unsafepointer-conversion-for-operator-arguments/11415)), we can make `&` part of the argument grammar, emit a parse error in other places (or re-claim this as a unary operator), and then eliminate more uses of the `InOut` type variable flag.

**Comment by davezarzycki** [comment]
If the unary `&`, a.k.a. `InOutExpr` syntax is to become a parser problem, then will we need to ban it in `IfExpr`? For example `b ? &x : &y`:

See `test/expr/expressions.swift`, line 819, and friends.

**Comment by slavapestov** [comment]
@davezarzycki It's an error for InOutExpr to appear in an IfExpr like that anyway

**Pull request closed without merging**
