### PR TITLE
[cxx-interop] implicitly imported CxxShim module should not force cli…

### LINKED ISSUE #65831: [cxx-interop] a Swift module that enables interop should not force client Swift module to fail to import CxxShim
RIght now when a Swift module A enables interoperability, and Swift module B that consumes it doesn't, the compiler will fail to compile B with the following error:

```
lib/swift/macosx/arm64/libcxxshim.modulemap:1:8: error: module 'CxxShim' requires feature 'cplusplus'
module CxxShim {
       ^
<unknown>:0: error: could not build Objective-C module 'CxxShim'

--
```

Module A should not force the client to consume B, or if B consumes it, it should not require cplusplus.

### PR DESCRIPTION
**Pull request by hyp**
…ent modules to enable C++ interoperability

Fixes https://github.com/apple/swift/issues/65831

### CODE REVIEW

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test source compatibility

**Review by egorzhdan — COMMENTED** [review]
Would `libcxxstdlibshim.h` also require a similar fix?

**Comment by hyp** [comment]
> libcxxstdlibshim

No, the compiler doesn't implicitly add it as an import when C++ interop is enabled.

**Review by egorzhdan — COMMENTED** [review]
I think there is a less intrusive way to fix this: can we make the implicit import of CxxShim `@_implementationOnly`?

In `Frontend.cpp`:
```
if (Invocation.getLangOptions().EnableCXXInterop && canImportCxxShim()) {
  pushImport(CXX_SHIM_NAME, {ImportFlags::ImplementationOnly});
}
```

That way IIUC the compiler would also refuse to compile such modules with cross-module optimization enabled instead of crashing.

**Comment by hyp** [comment]
Yes, I can try that.

**Comment by hyp** [comment]
@egorzhdan updated :)

**Review by egorzhdan — APPROVED** [review]

**Pull request merged**
