### PR TITLE
[cxx-interop] Import libstdc++ as a Clang module

### PR DESCRIPTION
**Pull request by egorzhdan**
This change adds a module map for libstdc++, which allows it to be properly imported into Swift as a module. The module map is installed into `usr/lib/swift/linux/{arch}` similarly to `glibc.modulemap`, and is passed to Clang as `-fmodule-map-file`.

That means it is now possible to import std directly from Swift on Linux, when C++ interop is enabled.

The module map currently declares a single `std` module without splitting the headers into submodules. This is going to change in the near future.

rdar://87654514

### CODE REVIEW

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test macOS platform

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
This patch depends on https://github.com/apple/swift/pull/42222 being merged first.

Apologies for spamming this PR with git rebases, the test failure wasn't reproducible for me locally.

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Review by zoecarver — APPROVED** [review]
Thank you Egor. This looks great (as usual).

**Comment by egorzhdan** [comment]
@swift-ci please smoke test Windows

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test Windows

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test Windows

**Comment by buttaface** [comment]
@egorzhdan, I cross-compile the trunk toolchain for Android occasionally, and [this pull broke cross-compiling the libswift portion of the compiler, because the Android NDK has a C++ modulemap](https://github.com/buttaface/termux-packages/runs/6137733070?check_suite_focus=true#step:6:7780) (for some reason, this works fine when natively building the Apr. 21 trunk snapshot on my Android phone). I then [disabled the new C++ modulemap portion of this pull for Android](https://github.com/buttaface/termux-packages/commit/24e4198e5b98b054be53588f2f683e2fe6fc465b#diff-2587a829c1dff85339003c6946945249960d25ec122ae053969ed30b36bdded8R164), and [it cross-compiles](https://github.com/buttaface/termux-packages/actions/runs/2224908864) and works fine.

Is that what you recommend for such platforms that have a C++ modulemap of their own, or is there something else I should do instead?

**Comment by egorzhdan** [comment]
@buttaface oh this is interesting. Looks like Swift on Android uses libc++, but when cross-compiling, it uses libstdc++? I'm not familiar with Android, sorry about that. In general, I think the best approach is to always use the system-wide default C++ standard library. If the default stdlib is libc++, which already has a modulemap, then the logic in this PR should not be used.
Does compilation break when building natively with your patch? If it doesn't, then we can just remove `NOT "${sdk}" STREQUAL "ANDROID" AND`, like you did in your patch.

**Comment by buttaface** [comment]
Thanks for the quick response.

> Looks like Swift on Android uses libc++, but when cross-compiling, it uses libstdc++?

No, Android always uses libc++, and the Android C++ module map exists in both the cross-compilation and native build environments.

I took a closer look at the build commands and the only difference is that [cross-compiling this libswift file specifies the `-sdk` and `-resource-dir` flags explicitly](https://github.com/apple/swift/blob/1b0aa6d7f106722237d1bb3256e9c6982898005c/SwiftCompilerSources/CMakeLists.txt#L103), whereas natively bootstrapping doesn't add those two flags. That means the native build never [passes your new module map file to the Clang Importer](https://github.com/apple/swift/blob/2285c518f73a8efc253e82e24c952bc211faf09b/lib/ClangImporter/ClangImporter.cpp#L701), so there is no conflict.

If that Swift file can be built without the `-resource-dir` flag, maybe it shouldn't be specified when cross-compiling either?

> If the default stdlib is libc++, which already has a modulemap, then the logic in this PR should not be used.
Does compilation break when building natively with your patch? If it doesn't, then we can just remove NOT "${sdk}" STREQUAL "ANDROID" AND, like you did in your patch.

I haven't tried removing it when natively building, but given my above finding that the native build never used your new module map and what you said about libc++ not needing it, removing that line seems like the solution.

**Pull request merged**
