### PR TITLE
[docs] Add SourceKit's `is_test_candidate`

### PR DESCRIPTION
**Pull request by modocache**
#### What's in this pull request?

When indexing, SourceKit finds methods that match what XCTest considers
to be a test; see: https://github.com/apple/swift/blob/197875ab6d9af0b07f22dde4729e4d0d37a4b324/tools/SourceKit/tools/sourcekitd/lib/API/Requests.cpp#L889-L890. Document this behavior.
#### Resolved bug number: None

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by DougGregor** [comment]
@akyrtzi ?

**Comment by akyrtzi** [comment]
LGTM, but keep in mind that going forward we should phase 'is_test_candidate' out and replace it with 'is_test' which will also ensure that the class is a subclass of XCTest. We can have both present until we transition over to 'is_test'.

**Comment by modocache** [comment]
@akyrtzi Are you aware of any `is_test_candidate` consumers that rely on it being able to detect methods that aren't defined on `XCTestCase` subclasses? I had thought we could simply modify [`isTestCandidate()`](https://github.com/apple/swift/blob/aec6ea71a0172bf027d2540f1e9b36e92fae6763/lib/Index/Index.cpp#L796) to:

1. Use `isInstanceMember()` to more easily detect whether the decl is an instance method (originally suggested in https://github.com/apple/swift/pull/2364#discussion_r62286214).
2. Detect whether the method is defined on an `XCTestCase` subclass.

We may also want to, when Objective-C interop is disabled, determine whether the method has `internal` or `public` access control; see https://github.com/apple/swift/pull/2364#issuecomment-216227106. We don't need to bake this into the `isTestCandidate()` implementation, however--the tool that generates a list of XCTest methods for swift-corelibs-xctest can check `is_test_candidate` and the access control exposed by SourceKit.

**Comment by akyrtzi** [comment]
It is fine to enhance 'is_test_candidate' to be more accurate, it is just that if we make it accurate I don't like the name 'is_test_candidate'. We can make it accurate and add both keys 'is_test_candidate' and 'is_test' for transition purposes.

**Pull request merged**
