### PR TITLE
[Runtime] Look up Error bridging symbols indirectly through special symbols that won't be stripped in static builds.

### PR DESCRIPTION
**Pull request by mikeash**
This fixes a problem where error bridging didn't work in stripped executables using the static versions of the Swift libraries. ErrorObject.mm looks up some symbols with dlsym, but stripping makes it so it can't find those. This change makes a separate set of symbols explicitly made for ErrorObject.mm to look up, and marks them as dynamically referenced so stripping won't remove them. Longer term, we'd like a better solution for looking up these symbols, but this will do for now.

rdar://problem/39810532

### CODE REVIEW

**Comment by mikeash** [comment]
@swift-ci please test

**Review by jckarter — APPROVED** [review]
LGTM, thanks Mike!

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci Please test OS X platform

**Review by gottesmm — CHANGES_REQUESTED** [review]
This needs an end-to-end test that actually strips a binary and checks the test.

**Comment by mikeash** [comment]
@gottesmm `ErrorBridgedStatic.swift` does this. The previous test didn't quite exercise the machinery enough to catch the problem, but I added another test that does.

**Comment by gottesmm** [comment]
I.e. we have functionality that actually strips the binary and then runs the test?

**Comment by mikeash** [comment]
That's right. It doesn't show up in the diffs because it was already there from before, but `ErrorBridgedStatic.swift` strips the test executable before running it. You can see it here:

https://github.com/mikeash/swift/blob/177f34cd0edfa8583a608cf084f3e95c9a9ddf1d/test/stdlib/ErrorBridgedStatic.swift#L4

I also confirmed that the test fails without my fix.

**Review by gottesmm — APPROVED** [review]

**Comment by gottesmm** [comment]
k SGTM.

**Comment by mikeash** [comment]
Cheers, thanks for the double check.

**Comment by benlangmuir** [comment]
This has appears to be crashing some tests (rdar://problem/40378113) I'm going to revert.

**Pull request merged**
