### PR TITLE
Delay the formal accesses associated with pointer conversions until the call

### PR DESCRIPTION
**Pull request by rjmccall**
Fixes rdar://31781386.

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please smoke test and merge.

**Comment by rjmccall** [comment]
@swift-ci Please test and merge.

**Comment by jrose-apple** [comment]
StringToPointer could use this treatment too!

**Comment by jrose-apple** [comment]
Also please add some tests with optional arrays to optional pointers. Those have been broken for a long time.

**Comment by rjmccall** [comment]
Will do.

I haven't done it for strings yet because those are never mutating accesses.

**Comment by rjmccall** [comment]
Wait, we allow optional arrays to be converted to optional pointers?  If so, that's going to be really annoying.

I had meant to test converting non-optional things to optional pointers, it was just an oversight.

**Comment by jrose-apple** [comment]
We do, and we do it wrong. IIRC it was my fault that we do it wrong. The conclusion I came to after talking to @gottesmm was that the optionality should be folded into the ArrayToPointer expr, rather than handled through any sort of OptionalEvaluation context.

(I know, I understand why that's wrong now. I'm sorry.)

**Comment by rjmccall** [comment]
...my second attempt to derive a test case for this crashed in the Verifier.

**Comment by rjmccall** [comment]
Addressed @jrose-apple's comments in #9033.

**Pull request merged**
