### PR TITLE
Fix potentially appending "/wd4068" on mac builds

### PR DESCRIPTION
**Pull request by hughbe**
Not sure what's causing this, I'd have thought this code works, and looks to have worked for a long time.

Anyways, fixes SR-3952

@jrose-apple @phausler

### CODE REVIEW

**Comment by hughbe** [comment]
See #6885

**Comment by hughbe** [comment]
@swift-ci please clean smoke test

**Comment by phausler** [comment]
Looks good; I will verify the patch tomorrow when I get back to the office and can kick off another build

**Comment by hughbe** [comment]
Perfect, you might want to run a clean build just in case CMake's cache is weird

**Comment by hughbe** [comment]
Any luck?

**Comment by jrose-apple** [comment]
If he doesn't get back to you by the end of the day let's just merge it. It's probably not harmful and I think someone else hit the same issue.

**Comment by phausler** [comment]
I was able to try it out yesterday; seems like it works as expected

**Pull request merged**
