### PR TITLE
Change FSO argument explosion heuristic and add some TODOs

### PR DESCRIPTION
**Pull request by trentxintong**

### CODE REVIEW

**Comment by trentxintong** [comment]
@swift-ci Please test

**Comment by trentxintong** [comment]
@swift-ci Please test

**Comment by trentxintong** [comment]
@swift-ci Please smoke test

**Comment by trentxintong** [comment]
@swift-ci Please smoke test

**Comment by trentxintong** [comment]
@swift-ci Please test

**Comment by trentxintong** [comment]
@swift-ci Please test

**Comment by trentxintong** [comment]
@swift-ci Please smoke test

**Comment by gottesmm** [comment]
@trentxintong Are you going to handle the non-generic argument of generic function case?

**Comment by trentxintong** [comment]
@gottesmm I am. I feel thats an important test we are missing for FSO.

**Comment by gottesmm** [comment]
Thanks! I just was not sure b/c of the TODO.

**Comment by trentxintong** [comment]
I put the TODO 2 days ago and i changed my mind after the we talked on Thursday.

**Comment by gottesmm** [comment]
No worries!

**Comment by shahmishal** [comment]
@swift-ci Please ASAN test

**Comment by trentxintong** [comment]
@swift-ci Please ASAN test

**Comment by trentxintong** [comment]
@swift-ci Please ASAN test

**Comment by trentxintong** [comment]
@swift-ci Please benchmark

**Comment by trentxintong** [comment]
@swift-ci Please ASAN test

**Comment by trentxintong** [comment]
@swift-ci Please benchmark

**Comment by trentxintong** [comment]
@swift-ci Please ASAN test

**Comment by trentxintong** [comment]
@swift-ci Please benchmark

**Comment by trentxintong** [comment]
@swift-ci Please benchmark

**Comment by trentxintong** [comment]
@swift-ci Please test

**Comment by trentxintong** [comment]
@swift-ci Please test

**Comment by trentxintong** [comment]
@swift-ci Please test

**Pull request merged**
