### PR TITLE
[Type Checker] Directional Path Consistency algorithm

### PR DESCRIPTION
**Pull request by xedin**
#### What's in this pull request?

Improvements to the TypeChecker, namely DPC
(directional path consistency) algoritm which tries to 
solve individual sub-expressions and combine
resolved types as a way to reduce pre-existing OSR domains. Solving
is done bottom-up so each consecutive sub-expression tightens
possible solution domain even further.

_Note_: Original PR (https://github.com/apple/swift/pull/4485); Changes: updated test for SR-2102 to avoid importing Foundation and clang-format'ed sources and tests.
#### Resolved bug number: ([SR-2102](https://bugs.swift.org/browse/SR-2102))

And most likely at least couple of others related to "expression is too complex" I haven't seen yet.

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

A smoke test on macOS does the following:
1. Builds the compiler incrementally.
2. Builds the standard library only for macOS. Simulator standard libraries and
   device standard libraries are not built.
3. lldb is not built.
4. The test and validation-test targets are run only for macOS. The optimized
   version of these tests are not run.

A smoke test on Linux does the following:
1. Builds the compiler incrementally.
2. Builds the standard library incrementally.
3. lldb is built incrementally.
4. The swift test and validation-test targets are run. The optimized version of these
   tests are not run.
5. lldb is tested.

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

DPC algoritm tries to solve individual sub-expressions and combine
resolved types as a way to reduce pre-existing OSR domains. Solving
is done bottom-up so each consecutive sub-expression tightens
possible solution domain even further.

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci Smoke test macOS.

**Comment by rudkx** [comment]
@swift-ci Test and merge.

**Comment by xedin** [comment]
@rudkx Sorry if it's stupid question, but regarding issues at bugs.swift.org that this PR handles, should I assign them to myself and resolve once everything is merged?

**Comment by rudkx** [comment]
@xedin In this case I'll take care of that as well as reviewing any other known performance test cases we have.

**Comment by rudkx** [comment]
It looks like the tests passed (macOS and Linux), but the automation won't do the merge because it wasn't specifically the macOS smoke test.

**Pull request merged**
