### PR TITLE
[windows][test] Mark the test as unsupported on Windows, but correctly.

### PR DESCRIPTION
**Pull request by drodriguez**
Can I blame this on auto-complete?

Continuation of #36214.

### CODE REVIEW

**Comment by drodriguez** [comment]
@swift-ci please test Windows platform

**Comment by drodriguez** [comment]
@swift-ci please smoke test and merge

**Review by ktoso — APPROVED** [review]
LGTM, thanks again Daniel

**Comment by drodriguez** [comment]
@swift-ci please smoke test macOS platform

**Comment by ktoso** [comment]
Pretty nasty "everything" crashing which definitely was not caused by this PR.
Supposedly we lost a large number of nodes and they're recovering now -- let me trigger again.

**Pull request merged**
