### PR TITLE
Delete backdeploy concurrency library

### PR DESCRIPTION
**Pull request by etcwilde**
This library served its purpose and has overstayed its welcome. The library shipped in Xcode can't change again from the state it was in, so changes to the sources here will not affect that library, which is confusing. The library does not currently build due to changes in the runtime headers, so it does not give meaningful signal to anything anymore. If you need to test things in a backdeploy concurrency environment, use the copy from the toolchain in Xcode as that will give you a far clearer picture of what the code will actually be running with than the state of the sources here did.

rdar://105793056

### CODE REVIEW

**Comment by etcwilde** [comment]
@swift-ci please test

**Comment by etcwilde** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by ktoso** [comment]
Yes please! It's an ongoing annoyance 👍

**Review by ktoso — APPROVED** [review]

**Comment by tomerd** [comment]
\o/

**Pull request merged**
