### PR TITLE
Carefully split the build's invocation of add_swift_library into host…

### PR DESCRIPTION
**Pull request by gottesmm**
…/target variants.

The key thing here is that all of the underlying code is exactly the same. I
purposely did not debride anything. This is to ensure that I am not touching too
much and increasing the probability of weird errors from occurring. Thus the
exact same code should be executed... just the routing changed.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Review by compnerd — APPROVED** [review]
I will trust you that the duplication is an exact duplication (it isn't exactly easy to diff that) but does appear that way.

**Comment by gottesmm** [comment]
@compnerd yes. It was a copy/paste. I didn't touch anything.

**Comment by gottesmm** [comment]
Actually, I am going to add additionally checks in both to make sure we are passing things down the right path.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
Linux builds failed b/c swift-5.0-branch on apple/swift-clang hadn't been merged yet into stable I think. We are using the newly built clang to compile Foundation, so this should have worked. Lets take this out for another spin.

**Comment by gottesmm** [comment]
@swift-ci test linux platform

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Pull request merged**
