### PR TITLE
🍒[5.7][Distributed] Cache checking distributed func

### PR DESCRIPTION
**Pull request by ktoso**
**Description:** By caching distributed func checking, we're able to invoke it wherever we want: in typechecking as well as to guard the synthesis of the distributed funcs.
**Risk:** Low
**Review by:** @DougGregor @xedin 
**Testing:** PR testing
**Original PR:** https://github.com/apple/swift/pull/42298
**Radar:**  rdar://91562751

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please build toolchain macOS
(in order to verify in Xcode manually)

**Comment by xedin** [comment]
@ktoso you used incorrect base, I switched to release/5.7

**Review by xedin — APPROVED** [review]

**Comment by xedin** [comment]
This needs an approval from @DougGregor or @hborla since I'm not in the release managers list.

**Review by hborla — APPROVED** [review]

**Comment by ktoso** [comment]
> @ktoso you used incorrect base, I switched to release/5.7

oh no, thanks!

**Comment by ktoso** [comment]
Thanks Holly!

**Comment by ktoso** [comment]
Applied review feedback from original PR

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please build toolchain macOS

**Pull request merged**
