### PR TITLE
Set C++ float type when converting evaluated value to string.

### PR DESCRIPTION
**Pull request by zoecarver**
Fixes SR-14052.

### CODE REVIEW

**Comment by zoecarver** [comment]
@swift-ci please smoke test.

**Comment by zoecarver** [comment]
@swift-ci please smoke test macOS.

**Comment by zoecarver** [comment]
@swift-ci please smoke test Windows.

**Review by xymus — APPROVED** [review]
Thanks! if this worked as expected on your end you can merge it when you want. We're working on fixing CI...

Can you also submit this to the next branch if it reproduces there too?

**Comment by zoecarver** [comment]
@xymus Not sure if this fixes it on the next branch. I'm a bit backlogged right now, so I'm not sure I'll have time to test it today, probably tomorrow.

**Pull request merged**
