### PR TITLE
Critical String fixes and high-value enhancements

### PR DESCRIPTION
**Pull request by dabrahams**
Explanation: Critical String fixes and high-value enhancements
Scope: security bug fix, source-compatible library extension, optimizations
Radar: rdar://32300763 Critical String fixes and high-value enhancements
Risk: moderate
Testing: Passed full validation + benchmarking on master; passed validation and and source compatibility  on the 4.0 branch; benchmark pending.

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please test

**Comment by dabrahams** [comment]
@swift-ci Please test source compatibility

**Comment by dabrahams** [comment]
@swift-ci Please benchmark

**Comment by dabrahams** [comment]
@swift-ci Please test

**Comment by dabrahams** [comment]
@swift-ci Please test

**Comment by dabrahams** [comment]
@swift-ci Please benchmark

**Comment by dabrahams** [comment]
@swift-ci Please benchmark

**Comment by dabrahams** [comment]
@swift-ci Please test source compatibility

**Comment by dabrahams** [comment]
@swift-ci Please test source compatibility

**Comment by tkremenek** [comment]
@airspeedswift @dabrahams Benchmarking results are available if you go to the details of the job.  The job failed because it expects to get results back for `master`.  Do the results look like what you expect?

**Comment by airspeedswift** [comment]
I think these are the results:

(`StringHasPrefix`/`Suffix` can be ignored)

<details open>
  <summary>Regression (6)</summary>
  
TEST                                                    | OLD    | NEW    | DELTA   | SPEEDUP   
---                                                     | ---    | ---    | ---     | ---       
StringHasPrefix                                         | 16     | 33     | +106.2% | **0.48x** 
StringHasSuffix                                         | 16     | 33     | +106.2% | **0.48x** 
StringFromLongWholeSubstring                            | 15594  | 19842  | +27.2%  | **0.79x** 
BitCount                                                | 12     | 14     | +16.7%  | **0.86x (?)** 
IterateData                                             | 706    | 755    | +6.9%   | **0.94x** 
Calculator                                              | 31     | 33     | +6.5%   | **0.94x** 

</details>

<details open>
  <summary>Improvement (9)</summary>
  
TEST                                                    | OLD    | NEW    | DELTA   | SPEEDUP   
---                                                     | ---    | ---    | ---     | ---       
SubstringFromLongString                                 | 158    | 10     | -93.7%  | **15.80x** 
SubstringFromLongStringGeneric                          | 340    | 77     | -77.4%  | **4.42x** 
StringFromLongWholeSubstringGeneric                     | 218    | 133    | -39.0%  | **1.64x** 
StringWithCString                                       | 189695 | 137287 | -27.6%  | **1.38x** 
DictionaryRemove                                        | 2781   | 2430   | -12.6%  | **1.14x** 
ObjectiveCBridgeStubNSDateRefAccess                     | 344    | 315    | -8.4%   | **1.09x** 
ArrayAppendAscii                                        | 24031  | 22072  | -8.2%   | **1.09x** 
StringMatch                                             | 9059   | 8373   | -7.6%   | **1.08x** 
NopDeinit                                               | 28948  | 27429  | -5.2%   | **1.06x** 

</details>

**Comment by dabrahams** [comment]
AFAICT when I got to the details I don't get anything I can compare to.  I see one set of results for O and O_none.  I'm not even sure these are the results for the branch under test, as AFAIK Mishal has the baseline tests run first.

**Comment by tkremenek** [comment]
This was reverted in:

https://github.com/apple/swift/pull/9813

pending investigation if SR-4955 is related to this change.

**Comment by dabrahams** [comment]
Given my current understanding of the problem, I'd say the risk here is quite low, FWIW.  I'll keep the bug updated, though.

**Pull request merged**
