### PR TITLE
[Backtracing] Disable assembly language on ARM Windows.

### PR DESCRIPTION
**Pull request by al45tair**
On ARM Windows, we need MARMASM to assemble the context capture code, but CMake doesn't support MARMASM until version 3.26, which isn't yet released.

(Confusingly it appears to have partial but non-working support in the present versions.)

rdar://106284325

### CODE REVIEW

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
Humm, no. That doesn't work (uploaded it and triggered PR testing, but it's turned ASM off for macOS for some reason).

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Review by compnerd — APPROVED** [review]
Thanks!

**Pull request merged**
