### PR TITLE
[CodeCompletion] Enable completion for subscript after dot

### PR DESCRIPTION
**Pull request by rintaro**
For:

```swift
  func test(str: String) {
    str.#^COMPLETE^#
  }
```

Suggest `[<#String.Index#>]`, `[<#Range<String.Index>#>]`, etc. with erasing dot instruction.

rdar://problem/28874899

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
Fixed test cases.
@swift-ci Please smoke test

**Comment by rintaro** [comment]
review ping @benlangmuir ?

**Comment by CodaFi** [comment]
This is superseded by #24867 according to the radar.  Closing it out.

**Pull request closed without merging**
