### PR TITLE
[stdlib] Explicitly declare Collection requirements on child protocols

### PR DESCRIPTION
**Pull request by moiseev**
~~See if this solution does not have the performance impact that
https://github.com/apple/swift/pull/18066/ had.~~
**UPD**: it does not.

Related to https://github.com/apple/swift/pull/18107

Addresses: <rdar://problem/42408692>

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
@swift-ci Please benchmark

**Comment by airspeedswift** [comment]
Does this also mean we can remove the `_index` methods?

**Comment by moiseev** [comment]
Depends on the reasons @milseman added them.

**Comment by milseman** [comment]
The reason they're there is so that a conformer can refer to the default implementation. For example, String's views can give constant-time answers to `distance` in some situations, but have to fall back to the default otherwise. Ideally, we'd have some way to refer to it, but that doesn't exist in the language. Rather than copy-paste the default, factoring it out into an underscored method allows us to call it.

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
@swift-ci please smoke test compiler performance

**Pull request merged**
