### PR TITLE
[Macros] Always use `GeneratedSourceInfo::originalSourceRange` for the insertion range of a macro expansion.

### PR DESCRIPTION
**Pull request by hborla**
For computing the original insertion range of a macro expansion, some places were using `GeneratedSourceRange::originalSourceRange`, and others were using the source range of `GeneratedSourceRange::astNode`. For attached macros, the `astNode` is the "attached to" declaration, which isn't the same as the insertion range of the macro expansion.

This change introduces `SourceFile::getMacroInsertionRange` for getting the original source range of a macro expansion buffer, and updates callers in ASTScope creation and ASTVerifier to use the new method.

### CODE REVIEW

**Comment by hborla** [comment]
@swift-ci please smoke test

**Review by DougGregor — APPROVED** [review]
This is a nice improvement, thank you!

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by kkk669** [comment]
@hborla @DougGregor 

Thank you for the improvements, but this change seems to be causing another issue. #70733

**Pull request merged**
