### PR TITLE
[SR-11572] Fix ambiguous function decl involving variadic parameters

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
Tweak the ranking function declaration request to consider that a function declaration with no variadic parameter is more specialized than a function declaration that have any variadic parameter.

cc @xedin @hborla 

Resolves SR-11572.

### CODE REVIEW

**Comment by AnthonyLatsis** [comment]
This seems more like an overload resolution problem. The third one is causing an ambiguity and yet it shouldn't even be considered as a viable candidate because of that argument label.

```swift
func foo<T>(some: T ...) { }
func foo<T>(some: T, _: T) { }

func foo(another: Int, _: Int) { }

foo(some: Int.zero, Int.zero) // Ambiguous use of 'foo'
```

**Comment by LucianoPAlmeida** [comment]
Hey @AnthonyLatsis Thank you for the comment :) 

Ambiguity is introduced also if you define the third function with the same label e.g. `func foo<T>(some arg1: T, _ arg2: T) { }`, I think it would happen with any function added that could be considered a disjunction choice in this context

But for this case in specific, the thing is that the solver is initially considering the third one as an option adding it as a disjunction choice, although it skips it because it is not a viable candidate ... 
```
  (attempting disjunction choice $T0 bound to decl sr9839.(file).SR11572(some:)@... : <T where T : SR11572_P, T.T == Void> (some: T...) -> () at ... [[locator@0x11d019a00 [OverloadedDeclRef@...]]];
    (overload set choice binding $T0 := ($T8...) -> ())
    ($T8 potentially_incomplete bindings={(supertypes of) SR11572_S})
    Initial bindings: $T8 := SR11572_S
    (attempting type variable $T8 := SR11572_S
      (found solution 0 0 0 0 0 0 0 0 0 0 0 0)
    )
  )
  (attempting disjunction choice $T0 bound to decl sr9839.(file).SR11572(some:_:)@... : <T, K where T : SR11572_P, K : SR11572_P> (some: T, K) -> () at ... [[locator@0x11d019a00 [OverloadedDeclRef@...]]];
    (overload set choice binding $T0 := ($T9, $T10) -> ())
    ($T9 potentially_incomplete bindings={(supertypes of) SR11572_S})
    ($T10 potentially_incomplete bindings={(supertypes of) SR11572_S})
    Initial bindings: $T9 := SR11572_S
    (attempting type variable $T9 := SR11572_S
      ($T10 potentially_incomplete bindings={(supertypes of) SR11572_S})
      Initial bindings: $T10 := SR11572_S
      (attempting type variable $T10 := SR11572_S
        (found solution 0 0 0 0 0 0 0 0 0 0 0 0)
      )
    )
  )
  (skipping disjunction choice $T0 bound to decl sr9839.(file).SR11572(another:_:)@...: (SR11572_S, SR11572_S) -> () at ... [[locator@0x11d019a00 [OverloadedDeclRef@...]]];
```
Which let it on a state of producing the two viable solutions... so because of that and the fact the I couldn't find an explicit way on the ranking decl that enforces the specific rule favoring non-variadic over variadic overload decl, I though tweak the ranking decl request would be a good solution.

But note, I don't fully understand the overload resolution process, and I'm still learning about various parts of the type checker, I may be missing on some things :))

If you could, mind point out where on the codebase or docs one can find more information about the overload resolution process? Maybe it can help find a better solution for this.
Thanks in advance :)

**Comment by xedin** [comment]
@LucianoPAlmeida I think before we can proceed with this it has to be made clear why in this case:

```swift
func foo<T>(some: T ...) { }
func foo<T>(some: T, _: T) { }

foo(some: Int.zero, Int.zero) 
```

solver attempts only one choice?...

**Comment by LucianoPAlmeida** [comment]
Sure, Thank you for taking a look @xedin
I was looking into this yesterday but not really sure yet, l’ll go back later tonight after work 👍 
Ping you when I have an answer to that :)

**Comment by LucianoPAlmeida** [comment]
@xedin The solver is attempting only one choice because it stops at the disjunction step 
[here](https://github.com/apple/swift/blob/8f306261ea995beae8316e0f17b715d4a19474e3/lib/Sema/CSStep.cpp#L570) 
Basically the non-variadic `func SR11572<T: SR11572_P, K: SR11572_P>(some arg1: T, _ arg2: K) { }` constraint is set favored over the variadic one meaning (`(*lastChoice).isFavored() is true` and `(*choice.Choice).isFavored() is false`). 
So it short circuits and breaks there returning the step as successfully solved. Therefore doesn't even attempt the second one. 
I still didn't look where this favoring is set... do you know where that may be done?

**Comment by xedin** [comment]
@LucianoPAlmeida The question is why is it favored, meaning what is marking it favored? It seems like favoring might not be a good answer here...

**Comment by LucianoPAlmeida** [comment]
> @LucianoPAlmeida The question is why is it favored, meaning what is marking it favored? It seems like favoring might not be a good answer here...

Ohh, sorry ... I'm looking into it :)

**Comment by LucianoPAlmeida** [comment]
@xedin 
The favoring is done at `CSGen` on `favorMatchingOverloadExprs` for `ApplyExpr` based on a logic of number of arguments [here](https://github.com/apple/swift/blob/8f306261ea995beae8316e0f17b715d4a19474e3/lib/Sema/CSGen.cpp#L738) with the function type.
So since the non-variadic function has the same number of args of the function type, it ends up favoring it. 

So when you introduce a third function with the same number of arguments that could be considered an overload choice(even on that wouldn't match because of the label that will be discarded later), because it can't really favor one over the other [here](https://github.com/apple/swift/blob/8f306261ea995beae8316e0f17b715d4a19474e3/lib/Sema/CSGen.cpp#L723) based on this number of args rule ... therefore no favoring happens making the solver attempt all the overload leading to the ambiguity.

**Comment by xedin** [comment]
I expected something like that but this but still... I think such favoring is wrong just because there could be a concrete overload which requires conversion for one of the arguments but still would be considered better than variadic based on favoring, although the score would stay otherwise...

I don't think there is a general enough rule that variadic should be worth in case of 2 or N overloads, I think both instances should be ambiguous.

**Comment by LucianoPAlmeida** [comment]
> I expected something like that but this but still... I think such favoring is wrong just because there could be a concrete overload which requires conversion for one of the arguments but still would be considered better than variadic based on favoring, although the score would say otherwise...
> 

@xedin 
Totally agree with that, I even thought in tweak this and not favoring any overload if there is an overload that involves variadics, but not sure if doing so will be source-compatible...

> I don't think there is a general enough rule that variadic should be worse in case of 2 or N overloads, I think both instances should be ambiguous.

IMO wouldn't seem incorrect if a function with a fixed number of arguments is considered more specific than an N-parameter variadic one if both matches the call, at least to me seems a reasonable choice (that's why the current implementation)... but also wouldn't find incorrect if the compiler fails with ambiguity in both cases...

So, what you think we could do here? :)

**Comment by xedin** [comment]
> IMO wouldn't seem incorrect if a function with a fixed number of arguments is considered more specific than an N-parameter variadic one if both matches the call, at least to me seems a reasonable choice (that's why the current implementation)... 

This is what SR-11572 is all about actually. Why would two argument overload be more specific than variadic function in such case? The problem is we can't really change behavior here because that would mean a source compatibility break. It might make sense to at least make current behavior consistent with N overloads and always pick a non-variadic ones but I think doing that (and removing current favoring from constraint generation) might cause performance degradations in other places...

**Comment by LucianoPAlmeida** [comment]
> This is what [SR-11572](https://bugs.swift.org/browse/SR-11572) is all about actually. Why would two argument overload be more specific than variadic function in such case? 
Ahh sure, I see the point, just meant as personal opinion :)

> The problem is we can't really change behavior here because that would mean a source compatibility break. It might make sense to at least make current behavior consistent with N overloads and always pick a non-variadic ones but I think doing that (and removing current favoring from constraint generation) might cause performance degradations in other places...

Right, maybe we don't need to remove current favoring from CSGen, we can let as it is and in case it can't favor any overloads we fallback to Ranking which is the current implementation here. 

What do you think @xedin ? I don't know how much this current approach impact performance... 
do you have any suggestions on another approaches we can do here? 
I can't think any other, besides maybe increase the score while comparing solutions or disfavor variadics on `ConstraintSystem::resolveOverload`? Really not sure ...

**Comment by xedin** [comment]
I'd have to think about this some more but I'm meaning towards just keeping this as is and closing that JIRA as won't fix because we can't really break source compatibility and make that case ambiguous...

**Comment by LucianoPAlmeida** [comment]
> I'd have to think about this some more but I'm leaning towards just keeping this as is and closing that JIRA as won't fix because we can't really break source compatibility and make that case ambiguous...

Right, Thanks @xedin! Let me know when you decide then :)

**Comment by xedin** [comment]
@LucianoPAlmeida I have talked to @DougGregor about this today and we have come to a conclusion that it would be best to keep this behavior as is for now and re-evaluate after performance work is done.

**Comment by LucianoPAlmeida** [comment]
@xedin Right, that makes sense 👍 
I'll close this then, thank you :)

**Comment by xedin** [comment]
Thank you for working on this! sorry that we can't take this right away but I think we might be able to do something about this in the future...

**Comment by LucianoPAlmeida** [comment]
> sorry that we can't take this right away but I think we might be able to do something about this in the future...

No problem :) glad to help on the discussion, hope we get this right in the future.
Ahh, I'll link this in the JIRA ticket just for future reference 👍

**Comment by xedin** [comment]
Thank you!

**Pull request closed without merging**
