### PR TITLE
Bump host tools deployment version for Darwin OS

### PR DESCRIPTION
**Pull request by rintaro**
```
DARWIN_DEPLOYMENT_VERSION_OSX = '10.13'
DARWIN_DEPLOYMENT_VERSION_IOS = '11.0'
DARWIN_DEPLOYMENT_VERSION_TVOS = '11.0'
DARWIN_DEPLOYMENT_VERSION_WATCHOS = '4.0'
```

### CODE REVIEW

**Comment by rintaro** [comment]
https://github.com/apple/swift-syntax/pull/882
@swift-ci Please clean test

**Comment by rintaro** [comment]
@swift-ci Please clean test

**Review by shahmishal — APPROVED** [review]

**Comment by rintaro** [comment]
@swift-ci Please clean test

**Comment by DougGregor** [comment]
@swift-ci Please clean test macOS

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci build toolchain

**Comment by shahmishal** [comment]
@swift-ci test macOS

**Comment by shahmishal** [comment]
@swift-ci test Linux

**Comment by shahmishal** [comment]
@swift-ci test macOS

**Comment by shahmishal** [comment]
@swift-ci smoke test Linux

**Pull request merged**
