### PR TITLE
Weakly import declarations with conditional availability

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes <rdar://46674512>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Review by jrose-apple — COMMENTED** [review]
I don't think this is the correct approach. You need to weak-reference things if your deployment target isn't new enough; it doesn't matter what the use site's AvailabilityContext is. Therefore it doesn't need to be an extra parameter.

**Comment by slavapestov** [comment]
It’s not passing in the use site’s local AvailabilityContext. It’s always passing in the global one from the ASTContext. I guess I could get rid of the extra parameter but I’m not a huge fan of all the global state in the ASTContext in general.

**Comment by jrose-apple** [comment]
I agree about the global state but in this case I think it's the lesser of two evils. Having the parameter encourages people to pass the wrong thing, especially if/when we start using AvailabilityContext in SIL.

**Comment by slavapestov** [comment]
@jrose-apple OK then, I'll clean that up. Other than changing it to always use the global AvailabilityContext do you think this is the right approach?

**Comment by jrose-apple** [comment]
Yeah, I think this is reasonable. If we wanted to handle backwards-deployment-without-availability or directly testing symbols for presence/absence it'd be more difficult, but for what we need right now this makes sense. (And the explicit `@_weakLinked` is close to handling the rest.)

**Comment by jrose-apple** [comment]
Conformances might be tricky, though, since those aren't Decls.

**Pull request merged**
