### PR TITLE
[interop] generate C interfaces for Swift top-level functions that use primitive types

### PR DESCRIPTION
**Pull request by hyp**

### CODE REVIEW

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test windows platform

**Comment by hyp** [comment]
@swift-ci please test Windows platform

**Comment by shahmishal** [comment]
@swift-ci please test Windows platform

**Pull request merged**
