### PR TITLE
[BatchMode] Test that some external definitions are adequately (but lazily) emitted.

### PR DESCRIPTION
**Pull request by graydon**
This tests a few kinds of external definition are adequately emitted (but also not multiply emitted); this is one of the areas we're worried that batch mode might have problems, but so far it appears not to.

More suggestions of things to test here welcome!

### CODE REVIEW

**Comment by graydon** [comment]
@swift-ci please test

**Comment by davidungar** [comment]
Cool!

- David

**Comment by jrose-apple** [comment]
I remain startled that this is working. `SILModule::constructSIL` has this in it:

```c++
  // Emit external definitions used by this module.
  for (size_t i = 0, e = mod->getASTContext().LastCheckedExternalDefinition;
       i != e; ++i) {
    auto def = mod->getASTContext().ExternalDefinitions[i];
    SGM.emitExternalDefinition(def);
  }
```

and while functions are handled pretty lazily, it really looks like the RawRepresentable conformance ought to be emitted everywhere. Why isn't it?

**Comment by graydon** [comment]
@jrose-apple Near as I can tell, it's all lazy.

~~~C++
void SILGenModule::emitExternalWitnessTable(ProtocolConformance *c) {                                                                                                                                            
  auto root = c->getRootNormalConformance();                                                                                                                                                                     
  // Emit the witness table right now if we used it.                                                                                                                                                             
  if (usedConformances.count(root)) {                                                                                                                                                                            
    getWitnessTable(c);                                                                                                                                                                                          
    return;                                                                                                                                                                                                      
  }                                                                                                                                                                                                              
  // Otherwise, remember it for later.                                                                                                                                                                           
  delayedConformances.insert({root, {lastEmittedConformance}});                                                                                                                                                  
  lastEmittedConformance = root;                                                                                                                                                                                 
}
~~~

**Comment by jrose-apple** [comment]
Oh. Well then.

**Review by jrose-apple — APPROVED** [review]

**Pull request merged**
