### PR TITLE
[ConstraintSystem] Format fixes to the type inference debug output. 

### PR DESCRIPTION
**Pull request by amritpan**

### CODE REVIEW

**Review by xedin — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test macOS Platform

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Pull request merged**
