### PR TITLE
Resilient re-ordering of associated types

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@DougGregor Maybe this is a bad idea, but the cleanup and evolution tests are still valid. :)

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by DougGregor** [comment]
Sorting associated types is a good step... I'm still debating (with myself) whether we should go all the way to indirecting associated types so we can resiliently add defaulted ones later.

**Pull request merged**
