### PR TITLE
[5.8] Introduce if/switch expressions

### PR DESCRIPTION
**Pull request by hamishknight**
*5.8 cherry-pick of https://github.com/apple/swift/pull/63022*

---

Introduce SingleValueStmtExpr, which allows the embedding of a statement in an expression context. This then allows us to parse and type-check `if` and `switch` statements as expressions. In the future, SingleValueStmtExpr could also be used for e.g `do` expressions.

For now, only single expression branches are supported for producing a value from an `if`/`switch` expression, and each branch is type-checked independently. A multi-statement branch may only appear if it ends with a `throw`, and it may not `break`, `continue`, or `return`.

The placement of `if`/`switch` expressions is also currently limited by a syntactic use diagnostic. Currently they're only allowed in bindings, assignments, throws, and returns. But this could be lifted in the future if desired.

### CODE REVIEW

**Comment by hamishknight** [comment]
https://github.com/apple/swift-syntax/pull/1305
https://github.com/apple/sourcekit-lsp/pull/706
https://github.com/apple/swift-format/pull/482
https://github.com/apple/swift-stress-tester/pull/227

@swift-ci please test

**Review by airspeedswift — APPROVED** [review]

**Comment by hamishknight** [comment]
https://github.com/apple/swift-syntax/pull/1305
https://github.com/apple/sourcekit-lsp/pull/706
https://github.com/apple/swift-format/pull/482
https://github.com/apple/swift-stress-tester/pull/227

@swift-ci please build toolchain

**Comment by hamishknight** [comment]
https://github.com/apple/swift-syntax/pull/1305
https://github.com/apple/sourcekit-lsp/pull/706
https://github.com/apple/swift-format/pull/482
https://github.com/apple/swift-stress-tester/pull/227

@swift-ci please test Windows

**Review by ahoppen — APPROVED** [review]

**Review by zoecarver — APPROVED** [review]

**Comment by hamishknight** [comment]
https://github.com/apple/swift-syntax/pull/1305
https://github.com/apple/sourcekit-lsp/pull/706
https://github.com/apple/swift-format/pull/482
https://github.com/apple/swift-stress-tester/pull/227

@swift-ci please test

**Review by airspeedswift — APPROVED** [review]

**Comment by hamishknight** [comment]
:ship:

**Pull request merged**
