### PR TITLE
Update class-fingerprint.swift

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves #NNNNN, fix apple/llvm-project#MMMMM.

### CODE REVIEW

**Comment by bnbarham** [comment]
preset=buildbot,tools=RA,stdlib=RD,test=non_executable
@swift-ci please test with preset macOS platform

**Comment by compnerd** [comment]
preset=buildbot,tools=RA,stdlib=RD,test=non_executable
@swift-ci please test with preset macOS platform

**Comment by compnerd** [comment]
preset=buildbot,tools=RA,stdlib=RD,test=non_executable
@swift-ci please test with preset macOS platform

**Comment by compnerd** [comment]
preset=buildbot,tools=RA,stdlib=RD,test=non_executable
@swift-ci please test with preset macOS platform

**Pull request closed without merging**
