### PR TITLE
Fix the LLVM repo path in lldbToolBox.py

### PR DESCRIPTION
**Pull request by MForster**
I guess this got broken in the monorepo migration.

### CODE REVIEW

**Comment by MForster** [comment]
@gottesmm, I think this would be something that you could review?

**Comment by compnerd** [comment]
CC: @JDevlieghere @dcci

**Comment by JDevlieghere** [comment]
I haven't used `lldbToolBox.py` but the change looks good with the new layout.

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci please test linux platform

**Comment by gribozavr** [comment]
@swift-ci Please smoke test Linux

**Comment by MForster** [comment]
Ok, so the smoke tests succeeded. I can't find logs for the previous failed "Swift Test Linux Platform" tests. 

Merge?

**Pull request merged**
