### PR TITLE
[nfc] Fix class-template-uninstantiable-members-irgen for i386.

### PR DESCRIPTION
**Pull request by zoecarver**
This is just a matter of changing the regex expression. Will fix the simulator bots.

### CODE REVIEW

**Comment by zoecarver** [comment]
@swift-ci please test macOS platform.

**Comment by zoecarver** [comment]
@swift-ci please smoke test linux.

**Comment by zoecarver** [comment]
@swift-ci please smoke test Windows.

**Comment by zoecarver** [comment]
@swift-ci please test Windows.

**Comment by milseman** [comment]
Merging to unblock CI

**Pull request merged**
