### PR TITLE
[tests] Add a `%batch-code-completion` lit substitution

### PR DESCRIPTION
**Pull request by ahoppen**
I could never remember the command to run batch code completion tests. Add a lit substitution for it.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Review by hamishknight — APPROVED** [review]
Nice!

**Review by bnbarham — APPROVED** [review]
The sad thing is that I'll probably still go look at a test to then copy paste `%batch-code-completion`. But very nice, will also make it easier to make changes if we want/need to :)

**Comment by ahoppen** [comment]
@swift-ci Please smoke test Linux

**Comment by ahoppen** [comment]
@swift-ci Please smoke test macOS

**Review by rintaro — APPROVED** [review]

**Pull request merged**
