### PR TITLE
[5.9] build: fix accidental cmake expansions

### PR DESCRIPTION
**Pull request by stephank**
* **Explanation**: CMake 3.25 broke the build because it introduced new global variables `LINUX`, `ANDROID`, etc., and 'string or variable' is ambiguous in certain syntax. Fixing these in 5.9 should help packaging on platforms that are already on newer CMake versions, e.g. NixOS 23.05, Ubuntu 23.04, Fedora 39 (rawhide).

* **Issue**: #65028

* **Risk**: Few merge conflicts in the backport, but otherwise this is hard for me to assess as a first-time contributer and CMake novice.

* **Testing**: I believe CI already covers the important platforms / codepaths here?

* **Reviewer**: Unsure, there's no specific owner for the build system it seems? Tagging previous reviewers: @finagolfin, @etcwilde, @compnerd 

* **Main branch PR**: #65534

### CODE REVIEW

**Review by compnerd — APPROVED** [review]
:sigh: Quoting.  Thank for backporting this.

**Comment by finagolfin** [comment]
@MaxDesiatov, would you run the CI on this?

**Comment by finagolfin** [comment]
@egorzhdan, please run the CI on this.

**Comment by finagolfin** [comment]
Sigh, linux CI crashed when checking out the source.

**Comment by egorzhdan** [comment]
@swift-ci please test Linux

**Comment by finagolfin** [comment]
Windows CI failed when building libdispatch after the Swift compiler is installed, appears unrelated to this pull.

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by finagolfin** [comment]
@DougGregor, ready for final approval and merge.

**Comment by finagolfin** [comment]
@compnerd, does anybody else need to sign off on this, or can this go in now? Please merge if the latter.

**Comment by jaredjones** [comment]
Looks like this missed the `release/5.9.0` branch.

**Comment by finagolfin** [comment]
Pinging @DougGregor as release manager again.

**Comment by finagolfin** [comment]
@stephank, looks like this needs a rebase.

**Comment by stephank** [comment]
Rebased, fixed conflict with add66990b39f3f46ab858384ef2e511e2bf6f73a and fixed quotes in a new addition from df94d008c3186f8db9252f5cb203ffd4b2e6bc3c.

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by finagolfin** [comment]
Pinging @DougGregor as 5.9 release manager for this repo, wdyt?

**Review by DougGregor — APPROVED** [review]

**Comment by DougGregor** [comment]
Yea, this is great. Thank you!

**Comment by finagolfin** [comment]
@bc-lee, anyone can propose getting this into 5.9.1, feel free to open a pull similar to this. I was surprised this wasn't already in, but it appears the 5.9 releases for this repo aren't actually being cut from the release/5.9 branch.

**Pull request merged**
