### PR TITLE
[reflection-dump] Teach reflection dump how to dump protocols from the __swift5_protos section of a .o

### PR DESCRIPTION
**Pull request by gottesmm**
I am spending a little bit of time learning more how the metadata/runtime system fit all together. This PR teaches swift-reflection-dump how to dump the protocols from __swift5_protos. My small project here is to get enough done that I can create a runtime function (based off this work) that gets all conformances for a specific protocol.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
I forgot to disable this when not on macho (I only implemented it for that).

**Comment by gottesmm** [comment]
Fixed. Lets try this again.

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Review by jckarter — APPROVED** [review]
Awesome!

**Comment by gottesmm** [comment]
For those looking in, some notes:

1. swiftReflection currently uses iostream in a bunch of places. I didn't add to the problem here, but I also didn't fix it (it is a larger PR).
2. I did not implement support for non-darwin platforms for now. This is just experimental. If I eventually use these techniques to do reflection on protocols for the perf test suite, I will implement that as well. This is just some fun stuff for me.

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Pull request merged**
