### PR TITLE
[5.10][CodeCompletion] Fix issue in which parts of a result builder were incorrectly skipped

### PR DESCRIPTION
**Pull request by ahoppen**
* **Explanation**: `getLoc` does not necessarily return the start location of the location (e.g. for `a.b().c()` it returns the location of `c` because that’s the location of the call). But we used the location from `getLoc` as the start location of the synthesized `buildExpression` call. In the added test case, this means that the `buildExpression` call only contained `everlay() {}` and not the code completion token. We thus inferred that we could skip it the entire `MyStack {}.pnTabGesture {}.everlay() {}` call for code completion, which isn’t correct.
* **Scope**: Source locations of expressions in result builders that support `buildExpression`
* **Risk**: Very low
* **Testing**: Added regression test 
* **Issue**: rdar://120798355
* **Reviewer**:  @xedin on https://github.com/apple/swift/pull/70898

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by airspeedswift** [comment]
Original: #70898

**Review by airspeedswift — APPROVED** [review]

**Comment by bnbarham** [comment]
@swift-ci please test Windows platform

**Pull request merged**
