### PR TITLE
Update master to build with Xcode 10.2 beta 1

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci smoke test

**Comment by shahmishal** [comment]
@swift-ci smoke test

**Comment by shahmishal** [comment]
Swift `master` and `swift-5.0-branch` now requires Xcode 10.2 beta.

**Comment by palimondo** [comment]
Oh, OK. Are changes like these announced somewhere on the forums? (My search reveals no info about that.)

**Comment by shahmishal** [comment]
I updated the README however, I did not make an announcement on forums. 
https://github.com/apple/swift/commit/bad0eb969008e8f4348657826e1c6fdcfd153027

I will make an announcement on forums now.

**Pull request merged**
