### PR TITLE
[stdlib] Dictionary/Set enhancements (redux)

### PR DESCRIPTION
**Pull request by natecook1000**
This is a fix for #9030, which broke the bots.

### CODE REVIEW

**Comment by natecook1000** [comment]
@swift-ci Please test

**Comment by natecook1000** [comment]
@swift-ci Please test Linux platform

**Comment by natecook1000** [comment]
@swift-ci Please test macOS platform

**Comment by natecook1000** [comment]
@swift-ci Please test macOS platform

**Comment by natecook1000** [comment]
@swift-ci Please smoke test Linux platform

**Comment by natecook1000** [comment]
@swift-ci Please test macOS platform

**Comment by DougGregor** [comment]
@swift-ci Please smoke test Linux platform

**Comment by DougGregor** [comment]
This hit the key path failures that have been fixed on master.

**Comment by DougGregor** [comment]
@swift-ci Please test macOS

**Pull request merged**
