### PR TITLE
Removed some TF attr modifiers (e.g. $dtype)

### PR DESCRIPTION
**Pull request by mhong**
Also extended attr sanity check code in TFDeabstraction::formGraphOp() to make
sure for a $tensor attr, its # scalar values match the # of scalars specified in
the subsequent shape attr. e.g. We have 2 scalar elements below.

```swift
  let shape : TensorShape = [1, 2]
  _ = #tfop("Const", dtype: Float.self, value$tensor: [17.0 as Float, 18.0], shape: shape)
```

These special attr modifiers are still needed:
- `$tensor`: for graph lowering to know an int/double array refers to a tensor
- `$shape`: for graph lowering to lower an int array to a shape attr properly
- `$array`: as needed for extracting a dtype list (see https://github.com/apple/swift/pull/18992).

### CODE REVIEW

**Comment by mhong** [comment]
@swift-ci please test tensorflow

**Review by lattner — APPROVED** [review]
This looks super nice!

Just to double check: lowergraph does know how to generate a shape and a shapelist attribute still, right?  How do we know whether something is a shape vs some other array of integers?


Could you upgrade createDatasetCreationContext to make a graphop as well when you get a chance?  Hopefully that will obsolete the "legacy" shapearray processing stuff.

**Review by rxwei — COMMENTED** [review]
I think the `$array` modifier is still needed once you resolve conflicts.

**Comment by mhong** [comment]
Good catch on the $shape modifier! It's needed for proper lowering, since an int array itself is not sufficient for compiler to know it's a shape attr. Added back that modifier now.

Also need to add back $array, because of https://github.com/apple/swift/pull/18992.

We don't need $shapearray, because graph lowering code looks at the actual swift type name (e.g. TensorShape at 
https://github.com/apple/swift/blob/64b2bbff43f850f7a21124c8cb2c54c5f7048fdf/lib/SILOptimizer/Mandatory/TFLowerGraph.cpp#L2037) to infer the attr kind.

**Comment by mhong** [comment]
@swift-ci please test tensorflow

**Comment by mhong** [comment]
@rxwei indeed. added it back. :)

**Review by rxwei — APPROVED** [review]

**Comment by mhong** [comment]
@swift-ci please test tensorflow

**Comment by mhong** [comment]
The GPU unit test run has a failed test that seems unrelated to this PR: https://ci-external.swift.org/view/Pull%20Request/job/swift-PR-TensorFlow-Linux-gpu/51/

**Comment by mhong** [comment]
Tests passed:
https://ci-external.swift.org/view/Pull%20Request/job/swift-PR-TensorFlow-Linux/756/
https://ci-external.swift.org/view/Pull%20Request/job/swift-PR-TensorFlow-Linux-gpu/54/

**Comment by mhong** [comment]
Thanks for the review!

**Pull request merged**
