### PR TITLE
Optimize grapheme breaking

### PR DESCRIPTION
**Pull request by Catfish-Man**
Fixes rdar://122968369

### CODE REVIEW

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Comment by Catfish-Man** [comment]
@swift-ci please benchmark

**Comment by Catfish-Man** [comment]
@swift-ci Please Apple Silicon benchmark

**Comment by Catfish-Man** [comment]
Not quite the results I was hoping for but still seems worth doing

```
------- Performance (arm64): -Osize -------

REGRESSION                                 OLD       NEW       DELTA    RATIO    
BufferFillFromSlice                        10.702    12.061    +12.7%   **0.89x (?)**

IMPROVEMENT                                OLD       NEW       DELTA    RATIO    
StringSwitch                               221.1     163.786   -25.9%   **1.35x**
String.initRepeating.1AsciiChar.Count100   280.125   243.6     -13.0%   **1.15x**
StringWordBuilderReservingCapacity         749.667   687.188   -8.3%    **1.09x**
StringWordBuilder                          763.571   701.0     -8.2%    **1.09x**
```

**Comment by Catfish-Man** [comment]
Windows build timed out while testing plutil somehow

**Comment by glessard** [comment]
@swift-ci please test windows platform

**Comment by Catfish-Man** [comment]
I'd like to do a little more benchmarking and make sure this is all working as expected before I land it

**Comment by milseman** [comment]
@Catfish-Man thanks for looking at it more. I want to make sure there's a win for the extra complexity.

**Review by milseman — CHANGES_REQUESTED** [review]
(Waiting on benchmark wins)

**Comment by Catfish-Man** [comment]
The changes in https://github.com/apple/swift/pull/71668 speed up the slow path enough that this is likely not worth the complexity anymore

**Pull request closed without merging**
