### PR TITLE
Revert three PRs to fix the windows arm64 CI

### PR DESCRIPTION
**Pull request by hjyamauchi**
Revert "[windows] Various improvements in build.ps1" https://github.com/swiftlang/swift/pull/77948
Revert "[windows][toolchain] Enable builtins and sanitizers" https://github.com/swiftlang/swift/pull/77770
Revert "utils: unlock building swift-inspect" https://github.com/swiftlang/swift/pull/77810

To fix CI https://ci-external.swift.org/job/swift-main-windows-toolchain-arm64

### CODE REVIEW

**Comment by hjyamauchi** [comment]
@swift-ci please test

**Comment by hjyamauchi** [comment]
@swift-ci please test

**Comment by hjyamauchi** [comment]
@swift-ci please test

**Comment by hjyamauchi** [comment]
@swift-ci please test

**Comment by hjyamauchi** [comment]
@swift-ci please test

**Comment by hjyamauchi** [comment]
A local build succeeded. Waiting for the CI to pass.

**Review by compnerd — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Pull request merged**
