### PR TITLE
Ban address phis in non-OSSA SIL

### PR DESCRIPTION
**Pull request by meg-gupta**
LoopRotate and ArrayPropertyOpt were the remaining optimizations generating address phis. This PR changes them  to avoid generating address phis and turns on verification to make sure we don't have address phis in SIL

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test source compatibility

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test source compatibility

**Review by atrick — APPROVED** [review]
Thanks!
😄 🥳

**Pull request merged**
