### PR TITLE
[utils] Python 3 support + tidies in check-incremental

### PR DESCRIPTION
**Pull request by alexwlchan**
#### What's in this pull request?
- Use print as a function, not as a statement
- Commonise the code for compiling and getting binary statistics into
  a reusable function
- Pull out `VERBOSE` and `NUM_ITERATIONS` as top-level constants, to
  make it clear where/how to change them.
- Use a docstring rather than a block comment.
- In the original version, `"Iteration {}:".format(iteration)` would
  index from 0; in human-readable output, index 1 is more sensible.
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

n/a

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by jrose-apple** [comment]
cc @eeckstein, who's the author of this utility.

**Comment by eeckstein** [comment]
@alexwlchan did you test your changes by compiling with the SWIFT_CHECK_INCREMENTAL_COMPILATION option?

**Comment by CodaFi** [comment]
@swift-ci please Python lint.

**Comment by CodaFi** [comment]
@swift-ci please smoke test.

**Comment by CodaFi** [comment]
Thanks @alexwlchan!

**Pull request merged**
