### PR TITLE
[RemoteMirror] Gracefully handle a NULL TypeInfo passed to convertChild.

### PR DESCRIPTION
**Pull request by mikeash**
rdar://problem/64066210

### CODE REVIEW

**Review by tbkka — APPROVED** [review]
👍

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test linux platform

**Comment by slavapestov** [comment]
No test? Do we know who/why is NULL being passed in here?

**Comment by mikeash** [comment]
@slavapestov I don't, I've just seen crash logs indicating that we're crashing on NULL here from time to time. I'd expect we're reading bad data in the target app (always a hazard with these analysis tools) but it's hard to be sure.

**Pull request merged**
