### PR TITLE
[embedded] Ask LLVM to build armv6 armv6m armv7 armv7m armv7em Mach-O builtins

### LINKED ISSUE #5: `pico-blink` Build Error: Undefined symbols for architecture armv6m:   "___muldi3"
When trying to build the `pico-blink` example on macOS with:

```
cd swift-embedded-examples/pico-blink
rm -rf .build ; TOOLCHAINS=org.swift.59202404131a ./build.sh
```

I get the following error:

```
# Link
$CLANG .build/release/Support.build/{Support.c,crt0.S}.o .build/release/Blinky.build/*.o -target armv6m-apple-none-macho -o $BUILDROOT/blinky $LD_FLAGS
+ /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2024-04-13-a.xctoolchain/usr/bin/clang .build/release/Support.build/Support.c.o .build/release/Support.build/crt0.S.o .build/release/Blinky.build/Blinky.swift.o -target armv6m-apple-none-macho -o /path/to/swift-embedded-examples/pico-blink/.build/armv6m-apple-none-macho/release/blinky -static -Wl,-e,_reset -dead_strip -Wl,-no_zero_fill_sections -Wl,-segalign,4 -Wl,-segaddr,__RESET,0x20000000 -Wl,-segaddr,__VECTORS,0x20000100 -Wl,-seg1addr,0x20000200 -Wl,-pagezero_size,0 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/15.0.0/lib/darwin/macho_embedded/libclang_rt.soft_static.a
ld: warning: ignoring file /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2024-04-13-a.xctoolchain/usr/lib/clang/17/lib/darwin/macho_embedded/libclang_rt.soft_static.a, building for free standing-armv6m but attempting to link with file built for macOS-armv7
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/15.0.0/lib/darwin/macho_embedded/libclang_rt.soft_static.a, building for free standing-armv6m but attempting to link with file built for macOS-armv7
Undefined symbols for architecture armv6m:
  "___muldi3", referenced from:
      _$s6Blinky4MainV5delayyySiFZTf4nd_n in Blinky.swift.o
ld: symbol(s) not found for architecture armv6m
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Is the `___muldi3` symbol not available on armv6m? If not, why is it being used?

System information:

```
swift-DEVELOPMENT-SNAPSHOT-2024-04-13-a.xctoolchain
Apple Swift version 6.0-dev (LLVM 01231f56c62f4c4, Swift abaa63821080b92)
Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:25 PDT 2024; root:xnu-10063.101.17~1
```

Toolchain ID:
```
$ plutil -extract CFBundleIdentifier raw -o - /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-*.xctoolchain/Info.plist                                    
org.swift.59202404131a
```

Git commit of `swift-embedded-examples`: 
```
69dc23e718c5b20797daec17d4754cd42bb21c24
```

Full build log: [pico-blink-build-log.txt](https://github.com/apple/swift-embedded-examples/files/15029563/pico-blink-build-log.txt)

### PR DESCRIPTION
**Pull request by kubamracek**
Fixes https://github.com/apple/swift-embedded-examples/issues/5.

Needs https://github.com/swiftlang/llvm-project/pull/8957.

### CODE REVIEW

**Comment by kubamracek** [comment]
Please test with following pull request:
https://github.com/swiftlang/llvm-project/pull/8957

@swift-ci Please Build Toolchain macOS Platform

**Review by rauhul — APPROVED** [review]
Are the prints for debugging or intentional additions?

**Comment by kubamracek** [comment]
Intentional. It's very hard to understand what's going on in the build script around builtins, so this is trying to shed some light to that in the logs.

**Comment by kubamracek** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by kubamracek** [comment]
```
[% 16:35:49 ~/Downloads/Library/Developer/Toolchains/swift-PR-75375-1381.xctoolchain] file ./usr/lib/clang/17/lib/darwin/macho_embedded/*
./usr/lib/clang/17/lib/darwin/macho_embedded/libclang_rt.hard_pic.a:    Mach-O universal binary with 4 architectures: [arm_v7:current ar archive random library] [arm subarchitecture=16:current ar archive random library] [i386:current ar archive random library] [x86_64:current ar archive random library]
./usr/lib/clang/17/lib/darwin/macho_embedded/libclang_rt.hard_pic.a (for architecture armv7):	current ar archive random library
./usr/lib/clang/17/lib/darwin/macho_embedded/libclang_rt.hard_pic.a (for architecture armv7em):	current ar archive random library
./usr/lib/clang/17/lib/darwin/macho_embedded/libclang_rt.hard_pic.a (for architecture i386):	current ar archive random library
./usr/lib/clang/17/lib/darwin/macho_embedded/libclang_rt.hard_pic.a (for architecture x86_64):	current ar archive random library
./usr/lib/clang/17/lib/darwin/macho_embedded/libclang_rt.hard_static.a: Mach-O universal binary with 4 architectures: [arm_v7:current ar archive random library] [arm subarchitecture=16:current ar archive random library] [i386:current ar archive random library] [x86_64:current ar archive random library]
./usr/lib/clang/17/lib/darwin/macho_embedded/libclang_rt.hard_static.a (for architecture armv7):	current ar archive random library
./usr/lib/clang/17/lib/darwin/macho_embedded/libclang_rt.hard_static.a (for architecture armv7em):	current ar archive random library
./usr/lib/clang/17/lib/darwin/macho_embedded/libclang_rt.hard_static.a (for architecture i386):	current ar archive random library
./usr/lib/clang/17/lib/darwin/macho_embedded/libclang_rt.hard_static.a (for architecture x86_64):	current ar archive random library
./usr/lib/clang/17/lib/darwin/macho_embedded/libclang_rt.soft_pic.a:    Mach-O universal binary with 4 architectures: [arm_v7:current ar archive random library] [arm subarchitecture=14:current ar archive random library] [arm subarchitecture=15:current ar archive random library] [arm subarchitecture=16:current ar archive random library]
./usr/lib/clang/17/lib/darwin/macho_embedded/libclang_rt.soft_pic.a (for architecture armv7):	current ar archive random library
./usr/lib/clang/17/lib/darwin/macho_embedded/libclang_rt.soft_pic.a (for architecture armv6m):	current ar archive random library
./usr/lib/clang/17/lib/darwin/macho_embedded/libclang_rt.soft_pic.a (for architecture armv7m):	current ar archive random library
./usr/lib/clang/17/lib/darwin/macho_embedded/libclang_rt.soft_pic.a (for architecture armv7em):	current ar archive random library
./usr/lib/clang/17/lib/darwin/macho_embedded/libclang_rt.soft_static.a: Mach-O universal binary with 4 architectures: [arm_v7:current ar archive random library] [arm subarchitecture=14:current ar archive random library] [arm subarchitecture=15:current ar archive random library] [arm subarchitecture=16:current ar archive random library]
./usr/lib/clang/17/lib/darwin/macho_embedded/libclang_rt.soft_static.a (for architecture armv7):	current ar archive random library
./usr/lib/clang/17/lib/darwin/macho_embedded/libclang_rt.soft_static.a (for architecture armv6m):	current ar archive random library
./usr/lib/clang/17/lib/darwin/macho_embedded/libclang_rt.soft_static.a (for architecture armv7m):	current ar archive random library
./usr/lib/clang/17/lib/darwin/macho_embedded/libclang_rt.soft_static.a (for architecture armv7em):	current ar archive random library
```

Seems like it works!

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Pull request merged**
