### PR TITLE
[ConstraintSystem] Add a fix to ignore contextual type mismatch

### PR DESCRIPTION
**Pull request by xedin**
Ignore contextual type mismatch to allow solver to make progress
towards solution and diagnose the problem later.

### CODE REVIEW

**Comment by xedin** [comment]
/cc @sl This is still work in progress since I have to port some tailored diagnostics over but you can see that there are some decent improvements here already.

I think this is final major preliminary work required before porting argument-to-parameter conversion mismatches.

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
Besides 2 diagnostic regressions related to protocol composition I consider this done.

**Comment by xedin** [comment]
I'll address them in the follow-up PR since this one is getting pretty big.

**Review by DougGregor — APPROVED** [review]
This looks great! I love seeing the CSDiag code away in favor of nicely-structured code.

**Review by hborla — APPROVED** [review]

**Pull request merged**
