### PR TITLE
TempRValueOptPass: fix a miscompile with open_existential_addr

### PR DESCRIPTION
**Pull request by eeckstein**
The uses of open_existential_addr were not handled correctly.

rdar://problem/56130674

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by atrick** [comment]
LGTM. Thanks!

**Comment by gottesmm** [comment]
LGTM.

**Comment by ddunbar** [comment]
For bugs like this, would it make sense to also add a higher level execution test case that doesn't just check the SIL, but also adds some minimized Swift program which exercises the code at runtime to check that it behaves properly? That might help build up additional resilience to these types of issues over times, because such test cases would cover multiple scenarios, not just the focused one probed for at the SIL level.

**Comment by eeckstein** [comment]
@ddunbar Yes, it would make sense. Sorry that I didn't do it for this PR, but other high priority things came in.

**Pull request merged**
