### PR TITLE
Fix EscapeAnalysis losing precision during merge.

### PR DESCRIPTION
**Pull request by atrick**
Array storage was being stack promoted even though it escaped. This
happened because multiple locally allocated arrays were merged into
the same locally allocated array value box. For this to become a
problem, other bizarre merge events need to take place, such as a
value node being mapped with a content node. The series of events led
to a missing edge in the connection graph. One of the arrays was
mapped directly to a project_box instruction which had forgotten it's
relationship with the alloc_box.

It is a trivial one line fix to simply preserve all value mappings.

Fixes <rdar://58371330> app crashes (miscompile)

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci test source compatibility

**Comment by atrick** [comment]
@swift-ci benchmark

**Review by eeckstein — APPROVED** [review]
lgtm

**Comment by atrick** [comment]
@swift-ci test

**Pull request merged**
