### PR TITLE
Use _DictionaryBuilder instead of Dictionary for casts

### PR DESCRIPTION
**Pull request by Catfish-Man**

### CODE REVIEW

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Comment by Catfish-Man** [comment]
@swift-ci please benchmark

**Comment by Catfish-Man** [comment]
Heh. I was trying to speed up JSON decoding but hey, I'll take it.

**Review by lorentey — APPROVED** [review]
Good catch! AFAICS the casts can't cause duplicate keys here, so it's safe to use the builders.

**Comment by lorentey** [comment]
I think the string-keyed dictionaries in JSON decoding always go through the separate non-verbatim path. (Which is lucky, since the element count can decrease during bridging.)

**Comment by jrose-apple** [comment]
Can we do even better than this? If the derived type is specifically a subclass of the base type (or an array or optional or set thereof), the hash value can't change. At least, I think it can't.

**Comment by Catfish-Man** [comment]
@jrose-apple hm. That certainly SHOULD be true for any liskov-correct type. I kinda doubt it's actually true though?

**Comment by jrose-apple** [comment]
I don't mean that the base class and subclass implementations will be the same. I mean that anything that calls `hash(into:)` on the base class will get the subclass's implementation anyway.

**Comment by Catfish-Man** [comment]
Oh! I see. That does seem like it should be true then. Taking advantage of it could be a bit tricky though.

**Comment by lorentey** [comment]
That's a great point! I don't see any reason the hashes would change as long as the derived type is a subclass of the original, or it is derived by substituting a class type with its subclass in a type parameter of a stdlib-provided generic.

If the hashes don't change, we could implement the cast as something like a CoW copy instead. (I.e., like `_NativeDictionary.copy()` but with extra casts.)

Examples of hash-invariant casts: (`where DerivedType: BaseType`)

```
BaseType → DerivedType
Optional<BaseType> → Optional<DerivedType>
Array<BaseType> → Array<DerivedType>
Set<BaseType> → Set<DerivedType>
etc. 
```

Examples of casts that potentially change hashing and thus require full rehashing:

```
UserDefinedGeneric<BaseType> → UserDefinedGeneric<DerivedType>
AnyHashable → DerivedType
BaseType → AnyHashable
BaseType → BridgedType (e.g. String → NSString or NSString → String)
BaseType → Optional<BaseType>
BaseType → Array<BaseType>
BaseType → Set<BaseType>
etc.
```

As far as I can see, this particular entry point is only called in the `BaseType → DerivedType` case above. (Although perhaps `BaseType` could be a class-constrained (or `@objc`) protocol? But that's okay too.)

**Comment by jrose-apple** [comment]
We'd have to be careful that `Array<BaseType> → Array<DerivedType>` doesn't stir in the type or something, too. I guess this would be an `_internalInvariant` (or whatever that name is) if we actually did it.

(It's not quite a CoW copy unless the representation is the same, either. Going from protocol -> instance or vice versa wouldn't be, and same for the collections because of the type checking.)

**Pull request merged**
