### PR TITLE
Implement extractInlinableText with swift-syntax

### PR DESCRIPTION
**Pull request by DougGregor**
Replace the existing C++ implementation of extractInlinableText with a new implementation based on swift-syntax. It uses SwiftIfConfig to remove inactive regions (with a special mode), and a new compiler-only entrypoint in the library to remove comments and `#sourceLocation`.

Fixes rdar://117491193

### CODE REVIEW

**Comment by DougGregor** [comment]
https://github.com/swiftlang/swift-syntax/pull/2832

@swift-ci please test

**Comment by DougGregor** [comment]
This will almost surely blow up on Linux, Windows, or both because I have a layering violation with ASTGen. I'm mostly curious whether this works at all.

**Review by CodaFi — APPROVED** [review]
🚀

**Comment by DougGregor** [comment]
https://github.com/swiftlang/swift-syntax/pull/2832

@swift-ci please smoke test

**Pull request merged**
