### PR TITLE
Merge branch 'tensorflow' of github.com:apple/swift into tensorflow-merge

### PR DESCRIPTION
**Pull request by dan-zheng**

### CODE REVIEW

**Comment by dan-zheng** [comment]
I'm testing `utils/build-toolchain-tensorflow` now on macOS and Ubuntu, wait please for success to merge.

**Comment by dan-zheng** [comment]
@marcrasi: could you please confirm that `tensorflow -> tensorflow-merge` PRs should be merged via "Create a merge commit" instead of "Squash and merge"?

Same for `tensorflow-merge -> tensorflow` PRs. All other PRs can be squashed to shorten commit log.

**Comment by marcrasi** [comment]
Yes, both of those should be "Create a merge commit"

**Comment by dan-zheng** [comment]
Confirmed that `utils/build-toolchain-tensorflow` succeeds on macOS and Ubuntu.
`utils/build-script --xcode` also works on macOS.

**Review by burmako — APPROVED** [review]

**Pull request merged**
