### PR TITLE
[WIP] [NFC] Translating RST docs to Markdown

### PR DESCRIPTION
**Pull request by felix91gr**
This is a work in progress.

The idea is to convert everything under `docs` to MD so that they are rendered properly on Github. This makes it possible to see the documentation on platforms where you can't run the `sphinx` builder, like on mobile.

### CODE REVIEW

**Comment by felix91gr** [comment]
@gottesmm how do you think I should proceed?

I'm thinking of three possibilities:

1. A **Wiki** *(which we don't have? I'm not certain of this)*. This would allow for a nice flow while browsing the docs, because of interlinking (just like a wiki).
2. **MD files** right next to the RST ones.
3. A **subfolder** with the documentation on MD.

**Comment by dabrahams** [comment]
Github can render restructuredText.  What am I missing?

**Comment by felix91gr** [comment]
> Github can render restructuredText. What am I missing?

This is what I see when I open the [Lexicon](https://github.com/apple/swift/blob/master/docs/Lexicon.rst):
image

I'm using FF v54 on Linux (elementaryOS, a derivative of Ubuntu. Currently based on Ubuntu 16.04 LTS)

**Comment by felix91gr** [comment]
I made a draft of how the Lexicon would look. There are some \` characters to clean up and some links with other documents that I haven't linked to yet, but it serves as a draft of how it can look. I think it looks pretty nice, I hope the other `rst` files can be converted as fully as this one.

**Comment by davedelong** [comment]
Related: https://bugs.swift.org/browse/SR-7454

**Comment by CodaFi** [comment]
It's been a few years, but this work is no less valuable to the project.  @felix91gr If you wish to continue this work, please assign SE-7454 to yourself and send us some updated patches.

Thank you for everything you did here in the mean time.

**Pull request closed without merging**
