### PR TITLE
DiagnosticVerifier: Allow specifying locations vs. ranges in fix-it verifications

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
This spares us from needless repetition in the bounds of insertion fix-its.

### CODE REVIEW

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test macOS

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test macOS

**Comment by rintaro** [comment]
Sorry, but I personally don't think this is a good idea. `{{5=a}}` _looks_ like replace the character at column 5 with `a` at a glance.
Are there particular cases we strongly want this change?

**Comment by AnthonyLatsis** [comment]
It reduces duplication, and therefore potential typing errors, and makes it easier to read through numerous verified fix-its that benefit from this change, especially the ones that use offsets like `-1:1--1:1` (I prefer these for robustness). It sounds like an edge case for someone to mistake `5-6=` for `5=`. We could continue rendering a range to clarify in case that happens. WDYT?

**Comment by rintaro** [comment]
For making fix-it test cases, I usually add `{{none}}` to `expected-error` etc. so the verifier can suggest the "correct" expected fix-its.  So I rarely type expected fix-its manually. (Of course, I always check the suggested fix-its are actually correct.)
As for readability, for me, since they are test cases, I'd more appreciate if all test cases are written in a consistent syntax.

**Comment by AnthonyLatsis** [comment]
`{{none}}` is convenient, but even if you use `--verify-apply-fixits`, you still have to add lines/offsets on your own. On the other hand, the force-verifying of lines that we discussed earlier would alleviate the latter to some extent. Anyway, thanks for the feedback!

**Pull request closed without merging**
