### PR TITLE
[stdlib] Hashable: Add non-public top-level hashing interface

### PR DESCRIPTION
**Pull request by lorentey**
The new _topLevelHash(seed:) requirement allows stdlib types to specialize their hashing when they’re hashed on their own (i.e., not as a component of some composite type).

This makes it possible to get rid of discriminator/terminator values and to eliminate most of _Hasher’s resiliency overhead, leading to a measurable speedup, especially for tiny keys.

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci please test

**Comment by lorentey** [comment]
@swift-ci please benchmark

**Comment by xwu** [comment]
Nit: maybe better named `_topLevelHashValue` for consistency?

**Comment by lorentey** [comment]
I went with `_rawHashValue(seed:)`, which seems like a suitably scary name, while also a good match for what it does.

With the latest rebase, the `Hasher._hash` functions have grown an `@effects(readnone)` attribute that lets the compiler do CSE and other optimizations on them. Additionally, their implementation switched to using SipHash cores directly, which could lead to another small performance boost.

**Comment by lorentey** [comment]
@swift-ci benchmark

**Comment by lorentey** [comment]
@swift-ci benchmark

**Comment by lorentey** [comment]
@swift-ci please benchmark

**Comment by lorentey** [comment]
@swift-ci please smoke test

**Comment by lorentey** [comment]
@swift-ci please smoke test

**Comment by lorentey** [comment]
@swift-ci test and merge

**Comment by lorentey** [comment]
@swift-ci test and merge

**Comment by lorentey** [comment]
@swift-ci test and merge

**Comment by lorentey** [comment]
@swift-ci test and merge

**Comment by lorentey** [comment]
@swift-ci please test and merge

**Comment by lorentey** [comment]
@swift-ci please test and merge

**Comment by lorentey** [comment]
@swift-ci please test and merge

**Pull request merged**
