### PR TITLE
[DNM] Parse `/.../` regex literals

### PR DESCRIPTION
**Pull request by hamishknight**
Try to lex regex literals with `/.../` delimiters when in an expression context in the parser, with a rule that it may not start with a space, tab or `)` character.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
@rintaro The lexing logic is still WIP as:

- Sub-lexing still needs to taken care of
- The heuristic needs formalizing
- The lexing loop needs to handle additional cases e.g invisible ASCII
- Prefix operators on regex literals needs to be implemented

But let me know if you have any initial thoughts

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by rintaro** [comment]
> * Sub-lexing still needs to taken care of

What do you think are the issues sub-lexing might cause?

> * The lexing loop needs to handle additional cases e.g invisible ASCII

Could you elaborate? Any example?

**Comment by hamishknight** [comment]
> What do you think are the issues sub-lexing might cause?

I don't *think* it currently causes any issues, e.g for delayed body parsing we start on the opening `{`. But it seems like a sub-lexer should be able to handle the case where it starts on an opening `/`. 

> Could you elaborate? Any example?

String literals currently diagnose invisible ASCII characters they come across, we probably ought to do the same for regex literals.

https://github.com/apple/swift/blob/d3702bacbb418afd4d4915cbebd77265dad50a65/lib/Parse/Lexer.cpp#L1338-L1344

**Comment by hamishknight** [comment]
@swift-ci please test macOS

**Comment by hamishknight** [comment]
@swift-ci please build toolchain

**Comment by hamishknight** [comment]
Updated to re-lex regex literals from the parser

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
Continuing work on https://github.com/apple/swift/pull/42119

**Pull request closed without merging**
