### PR TITLE
Merge branch 'tensorflow' into tensorflow-merge

### PR DESCRIPTION
**Pull request by asuhan**
Bring the new changes in the tensorflow branch.

### CODE REVIEW

**Comment by asuhan** [comment]
I had to resolve merge conflicts in:

include/swift/AST/Attr.h
lib/AST/Type.cpp
lib/Parse/ASTGen.cpp
lib/Parse/ParseDecl.cpp
lib/SILOptimizer/Mandatory/Differentiation.cpp
lib/Sema/TypeCheckDecl.cpp

Also, I made the `derivativeGenericSignature` field of `AutoDiffConfig` a `GenericSignatureImpl*`, not sure if that's the right fix. In any case, tests pass.

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Review by rxwei — APPROVED** [review]

**Review by dan-zheng — APPROVED** [review]

**Comment by dan-zheng** [comment]
I don't believe CI is strictly necessary on merge PRs other than the final `apple/tensorflow-merge -> apple/tensorflow` PR, so let's perhaps merge this now and create + test the final PR.

**Comment by rxwei** [comment]
Oh I thought it's to the tensorflow branch.

**Pull request merged**
