### PR TITLE
Update Policy.swift with designated types for logical and range operators.

### PR DESCRIPTION
**Pull request by rudkx**
…nge operators.

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by benrimmington** [comment]
Can the *infix* operators (`...` and `..<`) also have `Comparable` as their designated type?

**Comment by rudkx** [comment]
@benrimmington Yes, thanks - just missed it.

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Pull request merged**
