### PR TITLE
[NFC][test] Minor typo corrections on test messages

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
A minor PR to fix some found typos and test CI access.

It does not resolve any SR.

### CODE REVIEW

**Comment by LucianoPAlmeida** [comment]
@swift-ci please smoke test

**Review by varungandhi-apple — APPROVED** [review]

**Comment by varungandhi-apple** [comment]
Hmm, it doesn't seem to have worked. Ping @shahmishal: can you double-check that Luciano has CI access?

**Review by xedin — APPROVED** [review]
Thank you!

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by varungandhi-apple** [comment]
@xedin what we're trying to do (I think) is double-check that Luciano's CI and commit privileges are working. So let's let him run the tests and merge the PR. 😅

**Comment by xedin** [comment]
He can try merging, if he has access to do that, he'd have access to trigger CI.

**Comment by shahmishal** [comment]
@LucianoPAlmeida Does not have access yet, I will add him soon (by tomorrow)

**Comment by LucianoPAlmeida** [comment]
> @LucianoPAlmeida Does not have access yet, I will add him soon (by tomorrow)

Right, Thank you @shahmishal!

**Comment by LucianoPAlmeida** [comment]
@varungandhi-apple @xedin now we confirm that the CI is still not on, I think we can move with this, I can test CI in another PR when it is ready :)

**Comment by varungandhi-apple** [comment]
The Linux problem keeps coming up, so we can't merge at the moment. We can also re-run the tests tomorrow and see if anything has changed, since it's not urgent that we merge this.

**Comment by xedin** [comment]
@swift-ci please smoke test Linux platform

**Comment by xedin** [comment]
@swift-ci please smoke test Linux platform

**Comment by LucianoPAlmeida** [comment]
@swift-ci please smoke test Linux platform

**Comment by shahmishal** [comment]
Sorry, still have not had a chance to add you. 

@swift-ci please smoke test Linux platform

**Comment by LucianoPAlmeida** [comment]
Ahh no problem @shahmishal, I was just checking :)

**Comment by LucianoPAlmeida** [comment]
Hey guys 
There are any updates here @shahmishal? Sorry, I know it is pretty busy there, but just pinging to check :)

**Comment by LucianoPAlmeida** [comment]
Ping @shahmishal :)

**Comment by shahmishal** [comment]
@LucianoPAlmeida You should have access to trigger now, sorry it took this long.

**Comment by LucianoPAlmeida** [comment]
> @LucianoPAlmeida You should have access to trigger now, sorry it took this long.

No problem @shahmishal :) 
Thank you!

**Comment by LucianoPAlmeida** [comment]
@swift-ci please smoke test

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test Windows platform

**Comment by LucianoPAlmeida** [comment]
Windows failure is unrelated

**Pull request merged**
