### PR TITLE
build: create a helper function to define custom targets

### PR DESCRIPTION
**Pull request by compnerd**
Replace the duplicated logic for defining the targets for the standard
library variants with a call to a function that creates the targets.
This allows us to easily add variants of the standard library without
having to track all the sites for the name.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @gottesmm @Rostepher

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Review by Rostepher — CHANGES_REQUESTED** [review]
This looks pretty great, my only nit-pick is with your indentation. I think the standard CMake style for long command calls spanning lines requires that subsequent lines are only indented a single level. For example:

```CMake
set_target_properties(${name}${variant}-all
                           PROPERTIES
                             FOLDER "Swift libraries/Aggregate")
```

I think it's much easier to read when formatted without the extra whitespace:

```CMake
set_target_properties(${name}${variant}-all
  PROPERTIES
    FOLDER "Swift libraries/Aggregate")
```

This might be a small example, but when extrapolated to much larger nested calls with long variables (like in AddSwift) lines can quickly surpass the 80 (or 120) character limit.

We may also want to consider quoting variable expansions for safety, but it's not a large concern right now.

I do appreciate all the hard work you're putting into cleaning up and simplifying the CMake though! Thanks a bundle.

**Comment by compnerd** [comment]
I think that I'm just far more used to the C/C++/ObjC/ObjC++ style indentation which makes me prefer that.  I can re-indent the changes though.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@Rostepher I believe that I've addressed you comments about the indentation.  Going to go ahead and merge this.  If you have additional comments, I can handle them in a follow up.

**Comment by Rostepher** [comment]
👍

**Pull request merged**
