### PR TITLE
[5.1] Installation support for sourcekit-lsp

### PR DESCRIPTION
**Pull request by benlangmuir**
Cherry-pick to 5.1:
* https://github.com/apple/swift/pull/26619
* https://github.com/apple/swift/pull/26300
* https://github.com/apple/swift/pull/26269

Add --install-sourcekit-lsp option to build-script and update presets for package bots to install it. Also adds missing install actions to a few test presets to make it possible to test sourcekit-lsp.

### CODE REVIEW

**Comment by benlangmuir** [comment]
https://github.com/apple/indexstore-db/pull/51
https://github.com/apple/sourcekit-lsp/pull/145

@swift-ci please test

**Comment by benlangmuir** [comment]
apple/indexstore-db#51
apple/sourcekit-lsp#145

@swift-ci please build toolchain

**Comment by benlangmuir** [comment]
macOS failure is from pylint: `./utils/build-script:278:13: W503 line break before binary operator`

**Review by akyrtzi — APPROVED** [review]

**Comment by benlangmuir** [comment]
apple/indexstore-db#51
apple/sourcekit-lsp#145

@swift-ci please test

**Comment by benlangmuir** [comment]
apple/indexstore-db#51
apple/sourcekit-lsp#145

@swift-ci please test

**Pull request merged**
