### PR TITLE
Build: Add build of ASN1 and Certificates for SwiftPM

### PR DESCRIPTION
**Pull request by neonichu**
SwiftPM is getting new dependencies, this adds them to the Windows build.

This includes https://github.com/apple/swift/pull/64045 for the purpose of CI right now

### CODE REVIEW

**Comment by neonichu** [comment]
https://github.com/apple/swift-package-manager/pull/6228
@swift-ci Please Build Toolchain Windows Platform

**Comment by neonichu** [comment]
```
cmd.exe /C "cd . && T:\1\bin\swiftc.exe -output-file-map Sources\X509\CMakeFiles\X509.dir\Release\output-file-map.json -incremental -j 36 -emit-library -static -o lib\X509.lib -module-name X509 -module-link-name X509 -emit-module -emit-module-path swift\X509.swiftmodule -emit-dependencies  -O -Xcc -FT:/4 -I T:\4\swift -I T:\12\swift -I C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift-crypto\Sources\CCryptoBoringSSL\include -I T:\14\swift @CMakeFiles\X509.rsp   && cd ."
C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift-certificates\Sources\X509\Certificate.swift:15:8: error: missing required modules: 'CoreFoundation', 'Dispatch'
```

**Comment by neonichu** [comment]
Ah yah, the swift-certificates CMake build is still broken

**Comment by neonichu** [comment]
https://github.com/apple/swift-certificates/pull/33
https://github.com/apple/swift-package-manager/pull/6228
@swift-ci Please Build Toolchain Windows Platform

**Comment by neonichu** [comment]
https://github.com/apple/swift-package-manager/pull/6228
@swift-ci Please Build Toolchain Windows Platform

**Comment by neonichu** [comment]
```
-- Check for working Swift compiler: T:/1/bin/swiftc.exe - works
CMake Error at CMakeLists.txt:24 (find_package):
  Could not find a package configuration file provided by "SwiftSyntax" with
  any of the following names:

    SwiftSyntaxConfig.cmake
    swiftsyntax-config.cmake

  Add the installation prefix of "SwiftSyntax" to CMAKE_PREFIX_PATH or set
  "SwiftSyntax_DIR" to a directory containing one of the above files.  If
  "SwiftSyntax" provides a separate development package or SDK, be sure it
  has been installed.
```

Probably missed something when re-numbering things.

**Comment by neonichu** [comment]
https://github.com/apple/swift-package-manager/pull/6228
@swift-ci Please Build Toolchain Windows Platform

**Comment by neonichu** [comment]
https://github.com/apple/swift-package-manager/pull/6228
@swift-ci please smoke test

**Comment by neonichu** [comment]
https://github.com/apple/swift-package-manager/pull/6228
@swift-ci please smoke test

**Comment by neonichu** [comment]
https://github.com/apple/swift-package-manager/pull/6228
@swift-ci Please Build Toolchain Windows Platform

**Comment by neonichu** [comment]
https://github.com/apple/swift-package-manager/pull/6228
@swift-ci please smoke test windows

**Comment by neonichu** [comment]
https://github.com/apple/swift-package-manager/pull/6228
@swift-ci please smoke test

**Comment by neonichu** [comment]
https://github.com/apple/swift-package-manager/pull/6228
@swift-ci Please Build Toolchain Windows Platform

**Review by tomerd — APPROVED** [review]

**Review by compnerd — APPROVED** [review]

**Pull request merged**
