### PR TITLE
[Runtime] Make the swift_getTypeByMangled... functions emit error messages.

### PR DESCRIPTION
**Pull request by al45tair**
When type lookups fail, these functions should at least generate a warning.

rdar://103950409

### CODE REVIEW

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
It'd be nice if we could make failure to look up a type into a fatal error, but these functions are also used from e.g. RemoteMirror so I don't think we can.

**Comment by mikeash** [comment]
I didn't add this when I first added the error reporting, because I was afraid of cases where a NULL result is accepted. For a warning, I'm a bit worried about log spam. Not quite sure how to handle that, unless we can be sure that acceptable NULLs won't happen in normal programs.

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Review by mikeash — APPROVED** [review]

**Comment by al45tair** [comment]
@swift-ci Please smoke test Windows platform

**Pull request merged**
