### PR TITLE
Sema: Coerce [keyPath:] index to rvalue.

### PR DESCRIPTION
**Pull request by jckarter**
Fixes SR-5384 | rdar://problem/33160409.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Comment by jckarter** [comment]
@phausler Recognize this corelibs foundation build error?

```
Foundation/NSRange.swift:264:40: error: '_utf16Index' is unavailable
                location: r.lowerBound._utf16Index - target.startIndex._utf16Index,
                                       ^~~~~~~~~~~
Swift.String.Index:14:16: note: '_utf16Index' was obsoleted in Swift 4.0
    public var _utf16Index: Int { get }
               ^
Foundation/NSRange.swift:264:72: error: '_utf16Index' is unavailable
                location: r.lowerBound._utf16Index - target.startIndex._utf16Index,
                                                                       ^~~~~~~~~~~
Swift.String.Index:14:16: note: '_utf16Index' was obsoleted in Swift 4.0
    public var _utf16Index: Int { get }
               ^
Foundation/NSRange.swift:265:38: error: '_utf16Index' is unavailable
                length: r.upperBound._utf16Index - r.lowerBound._utf16Index
                                     ^~~~~~~~~~~
Swift.String.Index:14:16: note: '_utf16Index' was obsoleted in Swift 4.0
    public var _utf16Index: Int { get }
               ^
Foundation/NSRange.swift:265:65: error: '_utf16Index' is unavailable
                length: r.upperBound._utf16Index - r.lowerBound._utf16Index
                                                                ^~~~~~~~~~~
Swift.String.Index:14:16: note: '_utf16Index' was obsoleted in Swift 4.0
    public var _utf16Index: Int { get }
               ^
```

**Comment by phausler** [comment]
Cc @dabrahams this was part of your string index changes right?

**Comment by nkcsgexi** [comment]
#10812 is to revert this potential culprit.

**Comment by nkcsgexi** [comment]
@swift-ci Please smoke test

**Comment by dabrahams** [comment]
@phausler yes this was my doing; I failed to merge apple/swift-corelibs-foundation#1096
 so stuff broke, sorry.

**Pull request merged**
