### PR TITLE
[wasm] Enable Observation module build for Wasm target

### PR DESCRIPTION
**Pull request by kateinoigakukun**
There is no reason not to enable it :)

### CODE REVIEW

**Comment by kateinoigakukun** [comment]
@swift-ci test WebAssembly

**Comment by kateinoigakukun** [comment]
@swift-ci smoke test

**Comment by kateinoigakukun** [comment]
@swift-ci test WebAssembly

**Comment by kateinoigakukun** [comment]
@swift-ci smoke test

**Review by MaxDesiatov — APPROVED** [review]

**Pull request merged**
