### PR TITLE
[CodeCompletion] Fix assertion failure if completing in a macro call argument

### PR DESCRIPTION
**Pull request by ahoppen**
rdar://106966610

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Review by bnbarham — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please clean smoke test macOS

**Comment by ahoppen** [comment]
@swift-ci Please clean smoke test

**Comment by ahoppen** [comment]
@swift-ci Please clean smoke test

**Pull request merged**
