### PR TITLE
[Testing] NFC: Make BoxingCasts test concurrent

### PR DESCRIPTION
**Pull request by davezarzycki**
This test is the slowest test on my machine.

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please test

**Comment by davezarzycki** [comment]
Unrelated error: `Swift(iphonesimulator-i386) :: Interop/Cxx/value-witness-table/witness-layout-opts-irgen.swift`

@swift-ci please test

**Review by tbkka — APPROVED** [review]
Nice!  That should help speed things up.

**Comment by davezarzycki** [comment]
@swift-ci please smoke test macos

**Comment by davezarzycki** [comment]
@swift-ci please smoke test macos

**Pull request merged**
