### PR TITLE
Removes redundant buffer zeroing in Metal.swift by using `init(unsafeUninitializedCapacity:initializingWith:)`

### PR DESCRIPTION
**Pull request by valeriyvan**
In functions `getDefaultSamplePositions` and `getSamplePositions` removes redundant buffer zeroing by using `init(unsafeUninitializedCapacity:initializingWith:)` instead of `init(repeating:count:)`

### CODE REVIEW

**Comment by milseman** [comment]
@lorentey this is a change against the Metal overlay. What is the best way to review and incorporate these kinds of changes?

**Comment by valeriyvan** [comment]
ping

**Comment by milseman** [comment]
@lorentey any news here?

**Comment by lorentey** [comment]
@swift-ci test

**Review by lorentey — APPROVED** [review]
Thanks! This looks good to me.

**Comment by lorentey** [comment]
Ah, it’s missing a  all to `baseAddress`.

```

16:03:02 FAILED: stdlib/public/Darwin/Metal/OSX/x86_64/Metal.o 
16:03:02 cd /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/stdlib/public/Darwin/Metal && /usr/bin/python /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/utils/line-directive @/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/stdlib/public/Darwin/Metal/a8a9J.txt -- /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/./bin/swiftc -c -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -target x86_64-apple-macosx10.9 -resource-dir /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/./lib/swift -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/../../../Developer/Library/Frameworks -O -D INTERNAL_CHECKS_ENABLED -D SWIFT_ENABLE_RUNTIME_FUNCTION_COUNTERS -D SWIFT_ENABLE_EXPERIMENTAL_DIFFERENTIABLE_PROGRAMMING -module-cache-path /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/./module-cache -no-link-objc-runtime -Xfrontend -sil-verify-all -enable-library-evolution -Xfrontend -enable-ownership-stripping-after-serialization -Xfrontend -enforce-exclusivity=unchecked -module-name Metal -swift-version 5 -swift-version 5 -autolink-force-load -runtime-compatibility-version none -disable-autolinking-runtime-compatibility-dynamic-replacements -warn-swift3-objc-inference-complete -Xfrontend -verify-syntax-tree -warn-implicit-overrides -Fsystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/PrivateFrameworks/ -module-link-name swiftMetal -force-single-frontend-invocation -parse-as-library -I /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/./lib/swift/macosx -o /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/stdlib/public/Darwin/Metal/OSX/x86_64/Metal.o @/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/stdlib/public/Darwin/Metal/a8a9J.txt
16:03:02 
/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/stdlib/public/Darwin/Metal/Metal.swift:94:41: error: cannot convert value of type 'UnsafeMutableBufferPointer<MTLSamplePosition>' to expected argument type 'UnsafeMutablePointer<MTLSamplePosition>'
16:03:02             __getDefaultSamplePositions(buf, count: sampleCount)
16:03:02                                         ^
16:03:02 /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/stdlib/public/Darwin/Metal/Metal.swift:268:34: error: cannot convert value of type 'UnsafeMutableBufferPointer<MTLSamplePosition>' to expected argument type 'UnsafeMutablePointer<MTLSamplePosition>?'
16:03:02             __getSamplePositions(buf, count: numPositions)
16:03:02                                  ^
```

**Comment by valeriyvan** [comment]
ping

**Comment by valeriyvan** [comment]
ping

**Comment by lorentey** [comment]
@swift-ci test

**Comment by valeriyvan** [comment]
@lorentey, could you please run tests now?

**Comment by lorentey** [comment]
@swift-ci test

**Pull request merged**
