### PR TITLE
[5.4] [SILOpt] Turn off PruneVTables. 

### PR DESCRIPTION
**Pull request by varungandhi-apple**
Fixes rdar://73638176.

Cherry-pick from https://github.com/apple/swift/pull/35622.

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
@swift-ci smoke test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Review by DougGregor — APPROVED** [review]

**Comment by varungandhi-apple** [comment]
@swift-ci test Linux

**Comment by varungandhi-apple** [comment]
@swift-ci test macOS

**Comment by compnerd** [comment]
Hmm, is this the same issue that occurred previously with VTable pruning with WMO where types with non-internal visibility were pruned?

**Comment by varungandhi-apple** [comment]
Sounds like it yeah, we have an open class with a public property (and the property has a public type).

**Pull request merged**
