### PR TITLE
[test] Add tests for imported array parameters with nullability.

### PR DESCRIPTION
**Pull request by jrose-apple**
The feature was all implemented in Clang; the Swift-side tests just help confirm that it's working as expected.

rdar://problem/25846421

### CODE REVIEW

**Comment by jrose-apple** [comment]
https://github.com/apple/swift-clang/pull/43

@swift-ci Please test

**Comment by jrose-apple** [comment]
apple/swift-clang#43

@swift-ci Please test

**Comment by shahmishal** [comment]
apple/swift-clang#43

@swift-ci Please test

**Comment by jrose-apple** [comment]
Ugh, I realized I did that wrong. 88a4fbb needs to go in *before* apple/swift-clang#43, but e68e312 can't go in until *after.* I'll split 88a4fbb out into its own PR.

**Comment by jrose-apple** [comment]
Once more with ~~feeling~~ an unrelated flaky test reverted.

apple/swift-clang#43

@swift-ci Please test

**Pull request merged**
