### PR TITLE
build: check the compiler against the correct variable

### PR DESCRIPTION
**Pull request by compnerd**
We were checking the compiler ID against the name of the compiler
binary.  This happened to pass incorrectly on Windows, which hid the
bug.

Resolves dar://problem/56866783

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @edymtt

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by edymtt** [comment]
I was testing a similar changes in #28056 as well -- since this is more complete, I will close mine in favor of this.

**Review by edymtt — APPROVED** [review]

**Pull request merged**
