### PR TITLE
[CHANGELOG] Add SR-2394

### PR DESCRIPTION
**Pull request by modocache**
Add an explanation of the difference in ClangImporter behavior introduced by the SR-2394 implementation.

### CODE REVIEW

**Comment by slavapestov** [comment]
Looks like there's a conflict -- CHANGELOG.md is getting a lot of updates these days :)

**Comment by jrose-apple** [comment]
Resolved using the web editor, just to see what it's like. Looks like it does make a proper merge commit.

@swift-ci Please smoke test

**Comment by slavapestov** [comment]
I don't like to see merge commits introduced in PRs, they should be rebased instead. But we can just squash this when merging, since it's only one commit anyway.

**Comment by jrose-apple** [comment]
Fair enough.

**Comment by modocache** [comment]
Thanks for resolving the conflicts!

**Pull request merged**
