### PR TITLE
Update Swift:master to work with new stable re-branch from swift-5.1-branch

### PR DESCRIPTION
**Pull request by shahmishal**
We are using this pull request to verify the re-branch of the stable from swift-5.1-branch. 

https://forums.swift.org/t/updating-stable-branch-later-next-week-feb-2019/20288

### CODE REVIEW

**Comment by shahmishal** [comment]
https://github.com/apple/swift-llvm/pull/140
https://github.com/apple/swift-clang/pull/259
https://github.com/apple/swift-compiler-rt/pull/35
https://github.com/apple/swift-libcxx/pull/1
https://github.com/apple/swift-clang-tools-extra/pull/2

@swift-ci build toolchain

**Comment by shahmishal** [comment]
https://github.com/apple/swift-llvm/pull/140
https://github.com/apple/swift-clang/pull/259
https://github.com/apple/swift-compiler-rt/pull/35
https://github.com/apple/swift-libcxx/pull/1
https://github.com/apple/swift-clang-tools-extra/pull/2

Need to create LLDB stable-next PR.

**Comment by shahmishal** [comment]
https://github.com/apple/swift-llvm/pull/140
https://github.com/apple/swift-clang/pull/259
https://github.com/apple/swift-compiler-rt/pull/35
https://github.com/apple/swift-libcxx/pull/1
https://github.com/apple/swift-clang-tools-extra/pull/2
https://github.com/apple/swift-lldb/pull/1309

@swift-ci Please build toolchain

**Comment by shahmishal** [comment]
https://github.com/apple/swift-llvm/pull/140
https://github.com/apple/swift-clang/pull/259
https://github.com/apple/swift-compiler-rt/pull/35
https://github.com/apple/swift-libcxx/pull/1
https://github.com/apple/swift-clang-tools-extra/pull/2
https://github.com/apple/swift-lldb/pull/1309

@swift-ci Please test

**Comment by shahmishal** [comment]
LLDB test failures /cc @fredriss 

https://ci.swift.org/job/swift-PR-Linux/11151/

```
01:13:09.190   Expected Passes    : 1503
01:13:09.190   Unsupported Tests  : 85
01:13:09.190   Unresolved Tests   : 113
01:13:09.190   Unexpected Failures: 29
```

**Comment by shahmishal** [comment]
https://github.com/apple/swift-llvm/pull/140
https://github.com/apple/swift-clang/pull/259
https://github.com/apple/swift-compiler-rt/pull/35
https://github.com/apple/swift-libcxx/pull/1
https://github.com/apple/swift-clang-tools-extra/pull/2
https://github.com/apple/swift-lldb/pull/1309

@swift-ci Please smoke test

**Comment by fredriss** [comment]
@dcci was going to look into the Linux failures

**Comment by shahmishal** [comment]
https://github.com/apple/swift-llvm/pull/140
https://github.com/apple/swift-clang/pull/259
https://github.com/apple/swift-compiler-rt/pull/35
https://github.com/apple/swift-libcxx/pull/1
https://github.com/apple/swift-clang-tools-extra/pull/2
https://github.com/apple/swift-lldb/pull/1309

@swift-ci Please clean smoke test macOS

**Comment by shahmishal** [comment]
https://github.com/apple/swift-llvm/pull/140
https://github.com/apple/swift-clang/pull/259
https://github.com/apple/swift-compiler-rt/pull/35
https://github.com/apple/swift-libcxx/pull/1
https://github.com/apple/swift-clang-tools-extra/pull/2
https://github.com/apple/swift-lldb/pull/1309

@swift-ci Please smoke benchmark

**Comment by shahmishal** [comment]
https://github.com/apple/swift-llvm/pull/140
https://github.com/apple/swift-clang/pull/259
https://github.com/apple/swift-compiler-rt/pull/35
https://github.com/apple/swift-libcxx/pull/1
https://github.com/apple/swift-clang-tools-extra/pull/2
https://github.com/apple/swift-lldb/pull/1309

@swift-ci Please smoke benchmark

**Comment by shahmishal** [comment]
https://github.com/apple/swift-llvm/pull/140
https://github.com/apple/swift-clang/pull/259
https://github.com/apple/swift-compiler-rt/pull/35
https://github.com/apple/swift-libcxx/pull/1
https://github.com/apple/swift-clang-tools-extra/pull/2
https://github.com/apple/swift-lldb/pull/1309

@swift-ci Please smoke benchmark

**Comment by shahmishal** [comment]
https://github.com/apple/swift-llvm/pull/140
https://github.com/apple/swift-clang/pull/259
https://github.com/apple/swift-compiler-rt/pull/35
https://github.com/apple/swift-libcxx/pull/1
https://github.com/apple/swift-clang-tools-extra/pull/2
https://github.com/apple/swift-lldb/pull/1309

@swift-ci Please clean smoke test macOS

**Comment by shahmishal** [comment]
https://github.com/apple/swift-llvm/pull/140
https://github.com/apple/swift-clang/pull/259
https://github.com/apple/swift-compiler-rt/pull/35
https://github.com/apple/swift-libcxx/pull/1
https://github.com/apple/swift-clang-tools-extra/pull/2
https://github.com/apple/swift-lldb/pull/1309

@swift-ci Please smoke benchmark

**Comment by shahmishal** [comment]
@bob-wilson failed to build in benchmark job
```
13:14:59 /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-perf/swift/include/swift/Basic/SourceManager.h:40:49: error: no member named 'Status' in namespace 'clang::vfs'
13:14:59   mutable llvm::DenseMap<StringRef, clang::vfs::Status> StatusCache;
13:14:59                                     ~~~~~~~~~~~~^
13:14:59 /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-perf/swift/include/swift/Basic/SourceManager.h:53:21: error: no member named 'getRealFileSystem' in namespace 'clang::vfs'; did you mean 'llvm::vfs::getRealFileSystem'?
13:14:59                     clang::vfs::getRealFileSystem())
13:14:59                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
13:14:59                     llvm::vfs::getRealFileSystem
```

**Comment by bob-wilson** [comment]
I looked at this with Mishal. The benchmark is building master and missing the changes from the Swift PR.

**Comment by shahmishal** [comment]
https://github.com/apple/swift-llvm/pull/140
https://github.com/apple/swift-clang/pull/259
https://github.com/apple/swift-compiler-rt/pull/35
https://github.com/apple/swift-libcxx/pull/1
https://github.com/apple/swift-clang-tools-extra/pull/2
https://github.com/apple/swift-lldb/pull/1309

@swift-ci Please test

**Comment by fredriss** [comment]
Linux LLDB failures should be fixed by https://github.com/apple/swift-lldb/pull/1310. You might want to update the LLDB PR

**Comment by shahmishal** [comment]
https://github.com/apple/swift-llvm/pull/140
https://github.com/apple/swift-clang/pull/259
https://github.com/apple/swift-compiler-rt/pull/35
https://github.com/apple/swift-libcxx/pull/1
https://github.com/apple/swift-clang-tools-extra/pull/2
https://github.com/apple/swift-lldb/pull/1309

@swift-ci Please test Linux

**Comment by shahmishal** [comment]
https://github.com/apple/swift-llvm/pull/140
https://github.com/apple/swift-clang/pull/259
https://github.com/apple/swift-compiler-rt/pull/35
https://github.com/apple/swift-libcxx/pull/1
https://github.com/apple/swift-clang-tools-extra/pull/2
https://github.com/apple/swift-lldb/pull/1309

@swift-ci Please test macOS

**Comment by shahmishal** [comment]
https://github.com/apple/swift-llvm/pull/140
https://github.com/apple/swift-clang/pull/259
https://github.com/apple/swift-compiler-rt/pull/35
https://github.com/apple/swift-libcxx/pull/1
https://github.com/apple/swift-clang-tools-extra/pull/2
https://github.com/apple/swift-lldb/pull/1309

@swift-ci Please test macOS

**Comment by shahmishal** [comment]
https://github.com/apple/swift-llvm/pull/140
https://github.com/apple/swift-clang/pull/259
https://github.com/apple/swift-compiler-rt/pull/35
https://github.com/apple/swift-libcxx/pull/1
https://github.com/apple/swift-clang-tools-extra/pull/2
https://github.com/apple/swift-lldb/pull/1309

@swift-ci Please test macOS

**Comment by shahmishal** [comment]
@dcci @fredriss we are almost there! 

https://ci.swift.org/job/swift-PR-Linux/11173/

```
16:28:08 ********************
16:28:08 Unexpected Passing Tests (1):
16:28:08     lldb-Suite :: lang/swift/any/TestSwiftAnyType.py
16:28:08 
16:28:08 ********************
16:28:08 Failing Tests (1):
16:28:08     LLDB :: Reproducer/TestGDBRemoteRepro.test
16:28:08 
16:28:08   Expected Passes    : 1643
16:28:08   Unsupported Tests  : 85
16:28:08   Unexpected Passes  : 1
16:28:08   Unexpected Failures: 1
```

**Comment by dcci** [comment]
@shahmishal you can give it another try, I just merged something new.

**Comment by shahmishal** [comment]
https://github.com/apple/swift-llvm/pull/140
https://github.com/apple/swift-clang/pull/259
https://github.com/apple/swift-compiler-rt/pull/35
https://github.com/apple/swift-libcxx/pull/1
https://github.com/apple/swift-clang-tools-extra/pull/2
https://github.com/apple/swift-lldb/pull/1309

@swift-ci Please test Linux

**Comment by shahmishal** [comment]
Looks good, we can merge this tomorrow morning.

**Pull request merged**
