### PR TITLE
[main] Support Xcode 13 beta

### PR DESCRIPTION
**Pull request by shahmishal**
* Updating availability versions
* Remove all remaining overlays in stdlib/public/Darwin/*:
   - ObjectiveC
   - Dispatch
   - CoreFoundation
   - CoreGraphics
   - Foundation

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Review by lorentey — APPROVED** [review]

**Comment by shahmishal** [comment]
@swift-ci clean test

**Comment by shahmishal** [comment]
@swift-ci python lint

**Comment by shahmishal** [comment]
https://github.com/apple/llvm-project/pull/3027
@swift-ci clean test macOS

**Comment by shahmishal** [comment]
apple/llvm-project#3027
@swift-ci clean test macOS

**Pull request merged**
