### PR TITLE
switch Dataset.swift to use unknown rank (SR-8632)

### PR DESCRIPTION
**Pull request by marcrasi**
It seems to work quite well. Dataset API no longer relies on constexpr!

I discovered a bug in lowering and a bug in constexpr while writing test cases. I included those testcases, with XFAIL, so that someone can fix them later.

### CODE REVIEW

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Review by rxwei — APPROVED** [review]
LGTM. Thanks!

Dataset shape attributes _do_ require constexpr, it's just just that we no longer need to propagate struct members.

Now that we have a dynamic dataset API, I'll arrange next steps towards using a single `Dataset` type to unify all datasets.

**Comment by rxwei** [comment]
[SR-8573](https://bugs.swift.org/browse/SR-8573) is the last step towards supporting generalized `Dataset` API. @njjiang is working on this I believe.

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@marcrasi Could you please file bugs for those bugs you discovered?

**Comment by marcrasi** [comment]
hmm, I think that the failures are just flakes. Let's try again.

@swift-ci please test tensorflow

**Pull request merged**
