### PR TITLE
[Concurrency] Initialize local variable in `tryDiagnoseExecutorConfor…

### PR DESCRIPTION
**Pull request by xedin**
…mance`

Resolves: rdar://108458906

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@ktoso Could you please add a test-case for this too?

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Comment by ktoso** [comment]
Thanks a lot! I'll see if I can figure out a way to test this

**Comment by xedin** [comment]
@swift-ci please smoke test

**Review by ktoso — APPROVED** [review]

**Pull request closed without merging**
