### PR TITLE
[update-checkout] Update swift-certificates to 0.4.1, swift-asn1 back to 0.7.0

### PR DESCRIPTION
**Pull request by yim-lee**
Required to fix Windows build

### CODE REVIEW

**Comment by yim-lee** [comment]
cc @compnerd

**Comment by yim-lee** [comment]
https://github.com/apple/swift-package-manager/pull/6465

@swift-ci please smoke test

**Comment by yim-lee** [comment]
https://github.com/apple/swift-package-manager/pull/6465

@swift-ci please test

**Review by compnerd — APPROVED** [review]
Thanks!

**Comment by yim-lee** [comment]
https://github.com/apple/swift-package-manager/pull/6465/files

@swift-ci please smoke test

**Comment by yim-lee** [comment]
https://github.com/apple/swift-package-manager/pull/6465/files

@swift-ci please test

**Pull request merged**
