### PR TITLE
Several compile time fixes related to large string arrays.

### PR DESCRIPTION
**Pull request by eeckstein**
Fix several complexity bugs in the optimizer, which showed up when compiling huge string arrays.

The included test contains an array with > 60000 strings. It used to compile in > 1 hour. Now it needs less than 1 minute.

For details see the commit messages.

rdar://problem/56268570

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Review by atrick — APPROVED** [review]
Thanks Erik. All these commits look good. Only one comment.

Regarding SimplifyCFG, I have needed to fix the same problem many times. I've always done it by ensuring that blocks are processed in the correct order so that the merged block is never spliced into another block. That probably could be done with SimplifyCFG. I'll leave that up to you since the fix in this PR is sufficient. But I wonder if you at least tried processing the blocks in forward order, and whether that negatively impacted some other SimplifyCFG transform.

**Comment by eeckstein** [comment]
I tried a few things with SimplifyCFG. Not exactly changing the order, but a similar method, which didn't really work.

**Pull request merged**
