### PR TITLE
[swift-4.0-branch][stdlib] Source compatibility fix for a flatMap on [String]

### PR DESCRIPTION
**Pull request by moiseev**
* Explanation: [“”].flatMap behavior without explicit type context has changed when String became a Collection
* Scope of Issue: For source compatibility, in Swift 3 mode default behavior should be reinstated to return [String], not [Character] 
* Risk: minimal
* Reviewed By: Dave Abrahams
* Testing: automated test  suite
* Directions for QA: N/A
* Radar: <rdar://problem/32114115> rdar://problem/32112497

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
A clone of https://github.com/apple/swift/pull/9466

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
@swift-ci Please Test Source Compatibility

**Comment by airspeedswift** [comment]
Test suite failure looks benign so this is ok to merge.

**Pull request merged**
