### PR TITLE
Enable canonicalizing switch_enums in OSSA

### PR DESCRIPTION
**Pull request by meg-gupta**
This change primarily turns on canonicalizing switch_enums in OSSA.

It also splits SimplifyCFG into a header, so that it can be used by the UnitTestRunner to test individual portions of SimplifyCFG.

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci test

**Review by nate-chandler — APPROVED** [review]
lgtm!

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Review by atrick — APPROVED** [review]
LGTM

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Pull request merged**
