### PR TITLE
Fix crash in member lookup when base type contains type variables.

### PR DESCRIPTION
**Pull request by rudkx**
We were crashing during performTypoCorrection if the base type contained
type variables.

rdar://problem/28387684

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
Hmmm, gotta run those validation tests.

**Comment by rudkx** [comment]
@swift-ci Please test

**Comment by rudkx** [comment]
Hmm, "EXIT WRONG SHA", any idea what's causing that @shahmishal?

https://ci.swift.org/job/swift-PR-Linux/4298/console

**Comment by rudkx** [comment]
@swift-ci Please smoke test and merge.

**Comment by shahmishal** [comment]
Its due to https://github.com/jenkinsci/ghprb-plugin/issues/414

**Comment by rudkx** [comment]
Ah thanks, good to know!

**Comment by rudkx** [comment]
LLDB test failed. Seems unrelated. Perhaps it's flaky?

**Comment by rudkx** [comment]
@swift-ci Please smoke test and merge.

**Comment by rudkx** [comment]
@swift-ci Please smoke test Linux platform

**Comment by shahmishal** [comment]
Linux is failing due to LLDB tests, which will be disabled once this PR passes smoke test. 
https://github.com/apple/swift/pull/5631

**Comment by rudkx** [comment]
@swift-ci Please smoke test Linux platform

**Comment by rudkx** [comment]
@shahmishal Thanks Mishal, I've kicked off tests again.

**Pull request merged**
