### PR TITLE
[Coverage] Add counters for performance evaluation

### PR DESCRIPTION
**Pull request by vedantk**
This should help investigate performance issues (like r://39332957).

### CODE REVIEW

**Comment by vedantk** [comment]
@swift-ci Please smoke test

**Review by davidungar — APPROVED** [review]
LGTM, but Graydon may catch something.

**Review by graydon — APPROVED** [review]
If you want to track these numbers in release builds as well as assert builds, you'll want to define the counter in include/swift/Basic/Statistics.def and access it as a field on the UnifiedStatsReporter object hanging off the AST. Otherwise this is fine for debugging / assert-only builds.

**Review by slavapestov — COMMENTED** [review]
@graydon is this the right way to add a counter these days?

**Comment by graydon** [comment]
@slavapestov Counters are less of a mess than timers. You can use either counter subsystem (the LLVM one or the UnifiedStatsReporter one). In an assert build the USR one merges-in all the LLVM counters and reports them to the stats-dir file. In a release/no-assert build the USR ones are the only ones that exist: LLVM ones are compiled-out. Pick whichever one you want based on whether you want field reports from shipping compilers to be able to include them.

**Comment by vedantk** [comment]
Thanks for the feedback -- it does seem worthwhile to have these counters in release builds.

**Comment by CodaFi** [comment]
@vedantk Are you still interested in this after #15909 and Graydon's driver improvements?

**Comment by vedantk** [comment]
This needs to be reworked to use the USR. I'll set it aside for now.

**Pull request closed without merging**
