### PR TITLE
Merge tag 'swift-DEVELOPMENT-SNAPSHOT-2019-10-31-a' into tensorflow

### PR DESCRIPTION
**Pull request by dan-zheng**

### CODE REVIEW

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by marcrasi** [comment]
I just launched a toolchain build for this branch. Let's see what happens with that. Otherwise, looks good!

**Comment by dan-zheng** [comment]
> I just launched a toolchain build for this branch. Let's see what happens with that. Otherwise, looks good!

`./swift/utils/build-toolchain-tensorflow -t` on Ubuntu failed for me during LLDB tests:
```
Failing Tests (35):
    LLDB :: Reproducer/Swift/TestBridging.test
    LLDB :: Reproducer/Swift/TestModule.test
    LLDB :: Reproducer/Swift/TestSimple.test
    LLDB :: Swift/No.swiftmodule.test
    LLDB :: Swift/astcontext_error.test
    LLDB :: Swift/cond-breakpoint.test
    LLDB :: Swift/global.test
    LLDB :: SwiftREPL/Basic.test
    LLDB :: SwiftREPL/Class.test
    LLDB :: SwiftREPL/ComputedProperties.test
    LLDB :: SwiftREPL/CrashArgs.test
    LLDB :: SwiftREPL/Deadlock.test
    LLDB :: SwiftREPL/Dict.test
    LLDB :: SwiftREPL/ErrorReturn.test
    LLDB :: SwiftREPL/ExclusivityREPL.test
    LLDB :: SwiftREPL/GenericTypealias.test
    LLDB :: SwiftREPL/Generics.test
    LLDB :: SwiftREPL/MetatypeRepl.test
    LLDB :: SwiftREPL/Optional.test
    LLDB :: SwiftREPL/OptionalUnowned.test
    LLDB :: SwiftREPL/PropertyWrapperPrivate.test
    LLDB :: SwiftREPL/PropertyWrapperPublic.test
    LLDB :: SwiftREPL/PropertyWrapperTopLevel.test
    LLDB :: SwiftREPL/RecursiveClass.test
    LLDB :: SwiftREPL/Redefinition.test
    LLDB :: SwiftREPL/SimpleExpressions.test
    LLDB :: SwiftREPL/Struct.test
    LLDB :: SwiftREPL/Subclassing.test
    LLDB :: SwiftREPL/SwiftInterface.test
    LLDB :: SwiftREPL/SwiftInterfaceForceModuleLoadMode.test
    LLDB :: SwiftREPL/SwiftTypeLookup.test
    LLDB :: SwiftREPL/UninitVariables.test
    LLDB :: SwiftREPL/ZeroSizeStruct.test
    LLDB :: SwiftREPL/enum-singlecase.test
    LLDB :: SwiftREPL/one-char-string.test
```
[Full log for building LLDB here.](https://gist.github.com/dan-zheng/95bb4112578d501cfd41f03ce6888169)
Many tests are unresolved with this error:
```
UNRESOLVED: lldb-Suite :: lang/swift/anytype_array/TestAnyTypeArray.py (29 of 300)
******************** TEST 'lldb-Suite :: lang/swift/anytype_array/TestAnyTypeArray.py' FAILED ********************
Unable to find 'RESULT: PASSED' in dotest output (exit code 1):

lldb version 7.0.0 (https://github.com/apple/llvm-project.git revision bd31d693aabf94c5d68480408d9a1752ed900ea4)
Swift version 5.1.1-dev (Swift 012b9929e5)
LLDB library dir: /home/danielzheng/swift-merge2/build/buildbot_linux/lldb-linux-x86_64/bin
LLDB import library dir: /home/danielzheng/swift-merge2/build/buildbot_linux/lldb-linux-x86_64/bin
Traceback (most recent call last):
  File "/home/danielzheng/swift-merge2/lldb/test/dotest.py", line 7, in <module>
    lldbsuite.test.run_suite()
  File "/home/danielzheng/swift-merge2/llvm-project/lldb/packages/Python/lldbsuite/test/dotest.py", line 941, in run_suite
    import lldb
  File "/home/danielzheng/swift-merge2/build/buildbot_linux/lldb-linux-x86_64/lib/python3.7/site-packages/lldb/__init__.py", line 38, in <module>
    from . import _lldb
ImportError: dynamic module does not define init function (init_lldb)
```

---

I won't investigate these LLDB issues further, but I will report results for macOS:
* `./swift/utils/build-toolchain-tensorflow --pkg`
* `./swift/utils/build-toolchain-tensorflow -t --pkg`

**Comment by marcrasi** [comment]
Downstream repo tests reveal some additional errors that I'll investigate.

swift-apis:
```
[91/93] Compiling FastaiNotebook_07_batchnorm 07_batchnorm.swift
/fastai_dev/swift/FastaiNotebook_07_batchnorm/Sources/FastaiNotebook_07_batchnorm/07_batchnorm.swift:209:26: error: circular reference
    @noDerivative public var delegates: [(Self.Output) -> ()] = []
                         ^
/fastai_dev/swift/FastaiNotebook_07_batchnorm/Sources/FastaiNotebook_07_batchnorm/07_batchnorm.swift:209:30: note: through reference here
    @noDerivative public var delegates: [(Self.Output) -> ()] = []
                             ^
/fastai_dev/swift/FastaiNotebook_07_batchnorm/Sources/FastaiNotebook_07_batchnorm/07_batchnorm.swift:209:30: note: through reference here
    @noDerivative public var delegates: [(Self.Output) -> ()] = []
                             ^
/fastai_dev/swift/FastaiNotebook_07_batchnorm/Sources/FastaiNotebook_07_batchnorm/07_batchnorm.swift:219:6: note: through reference here
    @differentiable
     ^
/fastai_dev/swift/FastaiNotebook_07_batchnorm/Sources/FastaiNotebook_07_batchnorm/07_batchnorm.swift:154:19: warning: 'Raw' is deprecated: 'Raw' has been renamed to '_Raw' to indicate that it is not a guaranteed/stable API.
        let ret = Raw.fusedBatchNormV2(
                  ^
/fastai_dev/swift/FastaiNotebook_07_batchnorm/Sources/FastaiNotebook_07_batchnorm/07_batchnorm.swift:154:19: note: use '_Raw' instead
        let ret = Raw.fusedBatchNormV2(
                  ^~~
                  _Raw
/fastai_dev/swift/FastaiNotebook_07_batchnorm/Sources/FastaiNotebook_07_batchnorm/07_batchnorm.swift:175:27: warning: 'Raw' is deprecated: 'Raw' has been renamed to '_Raw' to indicate that it is not a guaranteed/stable API.
                let res = Raw.fusedBatchNormGradV2(
                          ^
/fastai_dev/swift/FastaiNotebook_07_batchnorm/Sources/FastaiNotebook_07_batchnorm/07_batchnorm.swift:175:27: note: use '_Raw' instead
                let res = Raw.fusedBatchNormGradV2(
                          ^~~
                          _Raw
<unknown>:0: error: type of expression is ambiguous without more context
```

swift-quotes:
```
Test Case 'StructureTests.testThrow' started at 2019-11-05 20:35:47.228
/swift/Tests/QuoteTests/StructureTests.swift:449: error: StructureTests.testThrow : XCTAssertEqual failed: ("Closure(
  [],
  [Throw(
    Conversion(
      Call(
        Name(
          "X",
          "<unstable USR>",
          FunctionType(
            [],
            [],
            TypeName("X", "<unstable USR>"))),
        [],
        [],
        TypeName("X", "<unstable USR>")),
      TypeName("Error", "s:s5ErrorP")))],
  FunctionType(
    [],
    [],
    TupleType(
      [])))") is not equal to ("Closure(
  [],
  [Throw(
    Conversion(
      Call(
        Name(
          "X",
          "",
          FunctionType(
            [],
            [],
            TypeName("X", "<unstable USR>"))),
        [],
        [],
        TypeName("X", "<unstable USR>")),
      TypeName("Error", "s:s5ErrorP")))],
  FunctionType(
    [],
    [],
    TupleType(
      [])))") -
Test Case 'StructureTests.testThrow' failed (0.0 seconds)
```

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Comment by marcrasi** [comment]
@swift-ci please clean test tensorflow

**Pull request merged**
