### PR TITLE
[CMake] Get ELF SwiftRT building

### PR DESCRIPTION
**Pull request by etcwilde**
These patches add the missing header search paths for building the `swiftrt.o`, as well as adding it to the default settings when building for BSD and Android to ensure that it isn't forgotten.

### CODE REVIEW

**Comment by etcwilde** [comment]
@swift-ci please smoke test

**Comment by etcwilde** [comment]
Linux failure:
```
******************** TEST 'lldb-shell :: SwiftREPL/BreakpointSimple.test' FAILED ********************
Exit Code: -9
Timeout: Reached timeout of 600 seconds

Command Output (stderr):
--
RUN: at line 3: /home/build-user/build/buildbot_linux/lldb-linux-x86_64/bin/lldb --no-lldbinit -S /home/build-user/build/buildbot_linux/lldb-linux-x86_64/test/Shell/lit-lldb-init-quiet --repl < /home/build-user/llvm-project/lldb/test/Shell/SwiftREPL/BreakpointSimple.test | /home/build-user/build/buildbot_linux/llvm-linux-x86_64/bin/FileCheck /home/build-user/llvm-project/lldb/test/Shell/SwiftREPL/BreakpointSimple.test
+ /home/build-user/build/buildbot_linux/lldb-linux-x86_64/bin/lldb --no-lldbinit -S /home/build-user/build/buildbot_linux/lldb-linux-x86_64/test/Shell/lit-lldb-init-quiet --repl
+ /home/build-user/build/buildbot_linux/llvm-linux-x86_64/bin/FileCheck /home/build-user/llvm-project/lldb/test/Shell/SwiftREPL/BreakpointSimple.test

--
```

**Comment by etcwilde** [comment]
@swift-ci please test Linux

**Comment by etcwilde** [comment]
@swift-ci please test macOS

**Review by compnerd — APPROVED** [review]

**Pull request merged**
