### PR TITLE
[4.0] Treat irrefutable casts as irrefutable patterns.

### PR DESCRIPTION
**Pull request by CodaFi**
Explanation: Treat irrefutable casts as irrefutable patterns
Scope: Limited.  Silences what were spurious warnings.
Radar/SR: Reported 
Risk: Low
Testing: Regression tests included in patch

This is a cherry-pick of #9449 and #9464.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@jrose-apple mind one more review for 4.0?

**Comment by jrose-apple** [comment]
Looks good to me, but at this point a manager should probably look at it too.

**Comment by tkremenek** [comment]
@swift-ci test source compatibility

**Comment by CodaFi** [comment]
Unexpected pass by Sourcery?

**Comment by CodaFi** [comment]
@swift-ci test source compatibility

**Comment by lplarson** [comment]
I'm reviewing the expected failures.

**Comment by CodaFi** [comment]
@swift-ci test source compatibility

**Comment by CodaFi** [comment]
There we go.

Over to you @tkremenek

**Pull request merged**
