### PR TITLE
[AutoDiff] Gardening.

### PR DESCRIPTION
**Pull request by dan-zheng**
Fix formatting, fix unused variable warnings.

### CODE REVIEW

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow macOS

**Review by rxwei — APPROVED** [review]

**Pull request merged**
