### PR TITLE
[SymbolGraph] Generate symbol graphs for macro declarations

### PR DESCRIPTION
**Pull request by bnbarham**

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by QuietMisdreavus** [comment]
This looks really nice! Do you know how something like this will show up in a module-wide symbol graph? Could you add a test to `test/SymbolGraph/Symbols` that makes sure it shows up properly?

**Comment by bnbarham** [comment]
Do you mind if I do that in a separate PR @QuietMisdreavus? I'd like to get the symbol graph response in cursor info ASAP.

**Review by QuietMisdreavus — APPROVED** [review]
Sure thing, this looks good on its own.

**Comment by bnbarham** [comment]
Thanks!

**Pull request merged**
