### PR TITLE
[5.9] [interop][SwiftToCxx] avoid emitting ambiguous C++ overloads and emit unavailable type stubs for top level types that could not be emitted in the C++ section of the generated header 

### PR DESCRIPTION
**Pull request by hyp**
[interop][SwiftToCxx] emit unavailable type stubs for top level types that could not be emitted in the C++ section of the generated header

[interop][SwiftToCxx] avoid emitting ambiguous C++ overloads
Just do an arity check for now

[interop][SwiftToCxx] do not expose move-only Swift types

Explanation: Before this change top-level Swift types that were unsupported in C++ were silently dropped with no indication to the user. Now,  such types are emitted a C++ stub class that's marked as unavailable, with a message indicating why it's available in C++. Additionally, Swift now also emits some comments for the other kinds of top-level declarations in the generated C++ section, so that the user could find some indication that such declarations are not supported in C++. Additionally, this change also ensures that we do not emit ambiguous C++ function/method overloads for Swift functions/initializers that are exposed to C++. This is done using an arity based check. In the future argument labels will be taken into account, but for now this conservative restriction will ensure that the generated header should have valid C++ code. Also, provide helpful diagnostic / unavailable messages stating that protocols and move-only types are not yet supported in C++.

Scope: Swift's and C++ interoperability, generated header printer (C++ section).
Risk: Medium.
Testing: Swift unit tests, manual testing on some adopter projects and several Swift packages that import C.
PR: https://github.com/apple/swift/pull/65728

### CODE REVIEW

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test source compatibility

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test source compatibility

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
