### PR TITLE
[api_checker/infer-imports.py] Look for Swift-only frameworks as well

### PR DESCRIPTION
**Pull request by akyrtzi**

### CODE REVIEW

**Comment by akyrtzi** [comment]
@swift-ci smoke test and merge

**Comment by akyrtzi** [comment]
\cc @nkcsgexi

**Comment by akyrtzi** [comment]
@swift-ci smoke test and merge

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by akyrtzi** [comment]
@swift-ci smoke test

**Pull request merged**
