### PR TITLE
[build-script] Add a preset for building the stdlib against a swift.o…

### PR DESCRIPTION
**Pull request by gottesmm**
…rg toolchain.

This is partly to provide an easy way for people to build the stdlib against a
toolchain. Sadly, it seems to not be able to build against the tests due to our
tests seemingly requiring our tools. We should be able to split out the stdlib
only tests. But, this at least is a way forward and an example.

The preset is called "stdlib_RDA,standalone,notest". It requires one parameter:
toolchain_path which should be the bin directory of your toolchain. Example:

```
build-script --preset=stdlib_RDA,standalone,notest toolchain_path=$MY_TOOLCHAIN/usr/bin
```

### CODE REVIEW

**Comment by gottesmm** [comment]
@shahmishal what do you think?

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by shahmishal** [comment]
LGTM! You will need to update the test Python/build_swift.swift

**Review by shahmishal — APPROVED** [review]

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Pull request merged**
