### PR TITLE
[Do Not Merge]: Adding counter and timer to NominalTypeDecl::lookupDirect

### PR DESCRIPTION
**Pull request by davidungar**
Beginning of work to reduce time spent in NominalTypeDecl::lookupDirect. Adds timer "lookupDirect" and counter "NominalTypeLookupDirectCount".

Also remove redundant (NominalType|Extension)Decl::getMembers

### CODE REVIEW

**Comment by davidungar** [comment]
@swift-ci Please smoke test

**Review by CodaFi — CHANGES_REQUESTED** [review]
The cleanup looks great, but it seems a little out of place here.  Could you open another pull request with all  of that split out?

**Comment by graydon** [comment]
Measured before/after, and it doesn't seem to reduce the number of deserialized entities; think it's idempotent. But in principle I agree it's nice to clean up excess calls!

**Comment by davidungar** [comment]
I am splitting this up into two different PRs, as per CodaFi's suggestion.

**Pull request closed without merging**
