### PR TITLE
IRGen: support static linking on Windows

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Hmm, this might be mishandling C/C++ linkage.

**Comment by CodaFi** [comment]
Having this as a bit in the AST seems like a huge layering violation. A swiftmodule doesn't have to have anything to do with the final binary image on disk, and one could conceivably share a swiftmodule between a static archive and a dylib if they so choose.

**Comment by compnerd** [comment]
@CodaFi nope, link time is too late.  This needs to be available _before_ compiling.  We need to know at compile time if the module  is statically or dynamically linked.   I had brought up this idea at https://forums.swift.org/t/enabling-static-linking-on-windows/40509/10.  I'm open to another solution if you have one.

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by CodaFi** [comment]
Discussed this with @compnerd further and there isn't really a good alternative either of us could identify. Approving so we can make progress here. The ABI isn't set in stone on Linux or Windows so we have the opportunity to amend this in the future if need be.

**Review by CodaFi — APPROVED** [review]

**Pull request merged**
