### PR TITLE
[cxx-interop] Update `GettingStartedWithC++Interop` documentation

### PR DESCRIPTION
**Pull request by cabmeurer**
Update the `GettingStartedWithC++Interop` to specify `Project` Build settings, and update example for iOS implementation to use SwiftUI 

@zoecarver @hyp

### CODE REVIEW

**Review by zoecarver — APPROVED** [review]

**Comment by zoecarver** [comment]
@swift-ci please smoke test.

**Comment by zoecarver** [comment]
@swift-ci please smoke test.

**Comment by calebabm** [comment]
@zoecarver when you get a chance, would you merge this? Thank you!

**Comment by cabmeurer** [comment]
@zoecarver when you get a chance, could you merge this? Thank you!

**Pull request merged**
