### PR TITLE
 [Type checker] Use the declared interface type of a type declaration.

### PR DESCRIPTION
**Pull request by DougGregor**
Fix a silly error where we were returning the interface type of a type
declaration rather than the *declared* interface type, which meant we were
getting a metatype where we shouldn't.

Fixes rdar://problem/36003312.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Review by jrose-apple — APPROVED** [review]

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
