### PR TITLE
Sema: Issue missing-witness notes in a sorted order so that witnesses belong to the same protocol are neighbors. SR-4251

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@jrose-apple is there a way to test temporal order of notes being issued?

**Comment by jrose-apple** [comment]
You can use FileCheck instead of -verify. But this isn't the problem @dabrahams was talking about in SR-4251, at least not the primary problem. He observed diagnostics like this:

```
Swift._UTF16StringStorage:7:16: note: candidate has non-matching type '_UTF16StringStorage'
    public var codeUnits: _UTF16StringStorage { get }
               ^
Swift._FixedFormatUnicode:2:16: note: candidate has non-matching type 'LazyMapRandomAccessCollection<Self.CodeUnits, UInt16>'
    public var rawUTF16: LazyMapRandomAccessCollection<Self.CodeUnits, UInt16> { get }
               ^
/Users/Shared/dabrahams/s/swift/test/Prototypes/AnyUnicode.swift:491:7: note: protocol requires property 'codeUnits' with type 'AnyCodeUnits'; do you want to add a stub?
  var codeUnits: AnyCodeUnits { get }
      ^
/Users/Shared/dabrahams/s/swift/test/Prototypes/AnyUnicode.swift:492:7: note: protocol requires property 'rawUTF16' with type 'AnyUTF16'; do you want to add a stub?
  var rawUTF16: AnyUTF16 { get }
      ^
```

And those really need to be emitted like this:

```
/Users/Shared/dabrahams/s/swift/test/Prototypes/AnyUnicode.swift:491:7: note: protocol requires property 'codeUnits' with type 'AnyCodeUnits'; do you want to add a stub?
  var codeUnits: AnyCodeUnits { get }
      ^
Swift._UTF16StringStorage:7:16: note: candidate has non-matching type '_UTF16StringStorage'
    public var codeUnits: _UTF16StringStorage { get }
               ^
/Users/Shared/dabrahams/s/swift/test/Prototypes/AnyUnicode.swift:492:7: note: protocol requires property 'rawUTF16' with type 'AnyUTF16'; do you want to add a stub?
  var rawUTF16: AnyUTF16 { get }
      ^
Swift._FixedFormatUnicode:2:16: note: candidate has non-matching type 'LazyMapRandomAccessCollection<Self.CodeUnits, UInt16>'
    public var rawUTF16: LazyMapRandomAccessCollection<Self.CodeUnits, UInt16> { get }
               ^
```

**Comment by najacque** [comment]
@swift-ci please test

**Comment by nkcsgexi** [comment]
This is not a correct fix for SR-4251, thus closing it for now.

**Pull request closed without merging**
