### PR TITLE
AST: Fix regression from SubstFlags::UseErrorTypes removal

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes <rdar://problem/54952911>.

### CODE REVIEW

**Review by DougGregor — APPROVED** [review]
LGTM! That's quite the reproducer you've got there.

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by slavapestov** [comment]
Sorry this was still a WIP earlier and the test crashed due to another bug. Should be good to merge now.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Pull request merged**
