### PR TITLE
Disable DCE of dead lexical borrows

### PR DESCRIPTION
**Pull request by meg-gupta**
DCE of dead lexical borrows can lead to illegal lifetime shortening. Disable this

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci test

**Review by atrick — APPROVED** [review]
LGTM

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test Linux

**Comment by meg-gupta** [comment]
@swift-ci test Linux

**Comment by meg-gupta** [comment]
This was fixed by another PR.

**Pull request closed without merging**
