### PR TITLE
Remove apostrophe from filename

### PR DESCRIPTION
**Pull request by hitstergtd**
#### What's in this pull request?

Remove apostrophe from filename:
_./test/SourceKit/Inputs/libIDE-mock-sdk/README.DON'T_MODIFY_FILES_DIRECTLY_

No changes to contents of the file named above.

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by tkremenek** [comment]
How about "DON'T" to "DO_NOT"?

**Comment by hitstergtd** [comment]
@tkremenek, OK.

**Comment by hitstergtd** [comment]
@tkremenek, Done.

**Comment by tkremenek** [comment]
Thank you. Can you squash this into a single commit?

**Comment by hitstergtd** [comment]
OK. Apologies, I've closed this Pull and open another one. I had a snafu in my previous fork.

**Comment by hitstergtd** [comment]
Done. Please see pull #1873. Sorry about the multiple pulls!

**Pull request closed without merging**
