### PR TITLE
[docs] Address post-merge comments in #33786

### PR DESCRIPTION
**Pull request by varungandhi-apple**

### CODE REVIEW

**Review by kastiglione — APPROVED** [review]

**Comment by varungandhi-apple** [comment]
Let's merge this. I can update the HTTPS vs SSH bit later.

@swift-ci please smoke test and merge

**Comment by kastiglione** [comment]
Agreed, this isn't blocked by that discussion.

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test and merge

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
