### PR TITLE
[Preset] Enable optimized test for Linux package.

### PR DESCRIPTION
**Pull request by shahmishal**
#### What's in this pull request?

[Preset] Enable optimized test for Linux package.
#### Resolved bug number: N/A

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci Please test Linux

**Comment by slavapestov** [comment]
Ping?

**Comment by shahmishal** [comment]
@swift-ci Please test

**Comment by shahmishal** [comment]
```
23:40:37 ********************
23:40:37 Failing Tests (9):
23:40:37     Swift(linux-x86_64) :: PCMacro/for.swift
23:40:37     Swift(linux-x86_64) :: PCMacro/didset.swift
23:40:37     Swift(linux-x86_64) :: PCMacro/switch.swift
23:40:37     Swift(linux-x86_64) :: PCMacro/plus_equals.swift
23:40:37     Swift(linux-x86_64) :: PCMacro/operators.swift
23:40:37     Swift(linux-x86_64) :: PCMacro/func_decls.swift
23:40:37     Swift(linux-x86_64) :: PCMacro/else.swift
23:40:37     Swift(linux-x86_64) :: PCMacro/mutation.swift
23:40:37     Swift(linux-x86_64) :: PCMacro/if.swift
23:40:37 
23:40:37   Expected Passes    : 732
23:40:37   Expected Failures  : 19
23:40:37   Unsupported Tests  : 8423
23:40:37   Unexpected Failures: 9
23:40:37 *** Failed while running tests for swift (check-swift-all-optimize-linux-x86_64)
```

**Comment by shahmishal** [comment]
@eeckstein Have you seen these test failures?

**Comment by eeckstein** [comment]
@shahmishal No (as it fails only on linux)
I looked into it a bit and I think it's a compiler problem

**Comment by eeckstein** [comment]
I filed rdar://problem/30234450

**Comment by shahmishal** [comment]
@swift-ci Please test Linux

**Comment by shahmishal** [comment]
@swift-ci Please test Linux

**Comment by CodaFi** [comment]
To restore the build logs:

@swift-ci please test

**Comment by shahmishal** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@shahmishal is this PR abandoned, or should it get merged?

**Comment by CodaFi** [comment]
@swift-ci please test linux platform

**Comment by CodaFi** [comment]
@swift-ci please test linux platform

**Comment by CodaFi** [comment]
Ha, 

@swift-ci please clean test linux platform

**Comment by CodaFi** [comment]
@swift-ci please clean test linux platform

**Comment by shahmishal** [comment]
@swift-ci Please test source compatibility benchmark

**Comment by shahmishal** [comment]
@swift-ci Please test compiler performance

**Comment by shahmishal** [comment]
@swift-ci Please test compiler performance

**Comment by shahmishal** [comment]
@swift-ci Please test compiler performance

**Comment by shahmishal** [comment]
@swift-ci Please test compiler performance

**Comment by shahmishal** [comment]
@swift-ci Please test compiler performance

**Comment by shahmishal** [comment]
@swift-ci Please test compiler performance

**Comment by shahmishal** [comment]
@swift-ci Please test compiler performance

**Comment by graydon** [comment]
@swift-ci Please test compiler performance

**Comment by graydon** [comment]
@swift-ci Please test compiler performance

**Comment by graydon** [comment]
@swift-ci Please test compiler performance

**Comment by graydon** [comment]
@swift-ci Please test compiler performance

**Comment by graydon** [comment]
@swift-ci Please test compiler performance

**Comment by shahmishal** [comment]
@swift-ci please smoke test compiler performance

**Comment by shahmishal** [comment]
@swift-ci please smoke test compiler performance

**Comment by shahmishal** [comment]
@swift-ci please smoke test compiler performance

**Comment by shahmishal** [comment]
@swift-ci please smoke test compiler performance

**Comment by shahmishal** [comment]
@swift-ci please smoke test compiler performance

**Comment by shahmishal** [comment]
@swift-ci test Linux

**Comment by shahmishal** [comment]
@swift-ci test Linux

**Comment by shahmishal** [comment]
@swift-ci Please test macOS

**Comment by eeckstein** [comment]
@swift-ci test Linux

**Comment by eeckstein** [comment]
@swift-ci test Linux

**Pull request merged**
