### PR TITLE
[Frontend] Move some stats + outputs to end of pipeline

### PR DESCRIPTION
**Pull request by hamishknight**
Move some stat collection and supplementary output logic to `performEndOfPipelineActions` to better fit the model of an inverted pipeline.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test macOS

**Comment by hamishknight** [comment]
@swift-ci please clean test macOS

**Review by CodaFi — APPROVED** [review]
Having to tail-call this function manually makes me a bit nervous, but this looks great.

**Comment by hamishknight** [comment]
@CodaFi Hmm, how about we factor out a `performCompilePipeline` function and have `performCompile` call both it and `performEndOfPipelineActions`?

**Comment by hamishknight** [comment]
@swift-ci please test macOS

**Comment by hamishknight** [comment]
@swift-ci please test macOS

**Comment by hamishknight** [comment]
@swift-ci please test macOS

**Comment by hamishknight** [comment]
https://github.com/apple/llvm-project/pull/1357

@swift-ci please test

**Comment by hamishknight** [comment]
https://github.com/apple/llvm-project/pull/1357

@swift-ci please test

**Comment by hamishknight** [comment]
https://github.com/apple/llvm-project/pull/1357

@swift-ci please test Windows

**Comment by hamishknight** [comment]
Merging for now, will work on cleaning up the interface in a follow up.

**Pull request merged**
