### PR TITLE
[AST] don't break a doc comment with a regular comment

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
Resolves rdar://95307936

When a declaration has a regular comment between its doc comment and the declaration itself, that doc comment is lost:

```swift
/// This is documentation
// This is a comment
public func myFunc() {}
```

This PR changes the comment attachment rules to skip over ordinary comments instead of using them to break them apart like a blank line would.

Notably, this change surfaced a bug in the standard library documentation: The default implementation of the `!=` operator in Equatable [had a regular comment between the doc comment and the declaration](https://github.com/apple/swift/blob/8b8f5472a4f5008a3bb3fc867a70cba969444ba0/stdlib/public/core/Equatable.swift#L179-L197), causing that documentation to be lost. (This is why i had to update the tests in `test/SourceKit/DocSupport`, because the documentation for `!=` started showing up!)

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Review by bnbarham — APPROVED** [review]
Seems reasonable to me, thanks @QuietMisdreavus! I don't think I had any good reason for not doing this in https://github.com/apple/swift/commit/22f59831abdb3acc2683deb4126d676f22fc6176, probably just went with keeping the current behavior assuming there was a good reason for it.

**Review by ahoppen — APPROVED** [review]
Thank you. Makes sense to me

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Pull request merged**
