### PR TITLE
Use array copy runtime implementation instead of the array value witnesses

### PR DESCRIPTION
**Pull request by aschwaighofer**
And add builtins for the added runtime functions (assign-take, assign-copy).

rdar://27412867
SR-3376

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please benchmark

**Comment by rjmccall** [comment]
That seems like a tolerable set of regressions in exchange for dropping three value witnesses.  Awesome!

**Comment by jckarter** [comment]
Are we still able to specialize when the type of the array element being copied/moved is known?

**Comment by eeckstein** [comment]
great work!

**Pull request merged**
