### PR TITLE
[ConstraintSolver] Fix computeFavoredTypeForExpr not to impose types …

### PR DESCRIPTION
**Pull request by xedin**
…on the merged binary operators

`LinkedExprAnalyzer` is not always precise in collecting types of expressions,
so let's not try to impose anything upon linked operator expressions, which are
"mergable", except actually merging argument/result types together to help
constraint solver.

Resolves: rdar://problem/27700622

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please smoke test Linux platform

**Comment by xedin** [comment]
@shahmishal Can you please take a look at what is going on? There is no stacktrace or something in the build log :(

**Comment by shahmishal** [comment]
```
Foundation/Decimal.swift:1393:47: error: '+' is unavailable: Please use explicit type conversions or Strideable methods for mixed-type arithmetics.
    exponent = a._exponent - b._exponent - 38 + exponent
                                              ^
Swift.Strideable:5:24: note: '+' was obsoleted in Swift 4
    public static func +(lhs: Self.Stride, rhs: Self) -> Self
                       ^
Foundation/Decimal.swift:1393:28: error: '-' is unavailable: Please use explicit type conversions or Strideable methods for mixed-type arithmetics.
    exponent = a._exponent - b._exponent - 38 + exponent
                           ^
Swift.Strideable:9:24: note: '-' was obsoleted in Swift 4
    public static func -(lhs: Self, rhs: Self) -> Self.Stride
                       ^
```

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please clean smoke test

**Comment by xedin** [comment]
@swift-ci please clean smoke test

**Review by rudkx — COMMENTED** [review]
This might be okay (pending fixing the current failures you're seeing), but there's really a deeper issue here with the forcing of types that's happening.

I'll try to dig up another related bug report that we have, where implementing math operations on a class hierarchy fails because we're forcing types in the constraint optimizer rather than going through the usual binding choices in the solver.

**Comment by rudkx** [comment]
My reduced test case from rdar://problem/28688585:

```
class Base {
  var value: Int

  init(value: Int) {
    self.value = value
  }

  func add(_ other: Base) -> Base {
    return Base(value: value + other.value)
  }
}

class Derived : Base {
}

func + (lhs: Base, rhs: Base) -> Base {
  return lhs.add(rhs)
}

let a = Derived(value: 1)
_ = a + a + a
```

**Comment by xedin** [comment]
@rudkx I agree, it looks like there is not going to be an easy fix because changing optimizer behavior leads to solver picking unavailable Stridable overloads in certain cases where optimizer would **wrongly** link + favor other type...

It would be great if we could just delete the whole thing and let the solver to the right thing, will see if that's possible.

**Comment by xedin** [comment]
@rudkx This version of the patch solved the problem you've mentioned but it fails with this Stridable overload problem, I'll try to see if it could be fixed...

**Comment by xedin** [comment]
@swift-ci please smoke test OS X platform

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test OS X platform

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Review by rudkx — APPROVED** [review]
LGTM!

**Review by rudkx — APPROVED** [review]

**Comment by xedin** [comment]
@rudkx Looks like there is an expression in one of the source compat projects is too complex now, do you think it's worth just fixing that expression or XFAIL'ing the test to move forward with this? Linking is not really a solution for that like that at the first place...

**Comment by rudkx** [comment]
@xedin Can you investigate the failure before we decide to XFAIL it?

If we XFAIL we at least need an opened bug and a plan in mind of how we'll get it re-enabled.

**Comment by xedin** [comment]
@rudkx there is an expression in there which involves + closures and arrays, I will try to decude it in to standalone example... I think at least we could split it into multiple expressions in the project itself and create a radar to track reduced example separately, because that fits into larger performance work, WDYT?

**Comment by xedin** [comment]
@shahmishal it looks like OS X test can't report its status because github doesn't allow commit to happen - it says 422 - "description is too long", what should I do to fix that?

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@rudkx I haven't picked up the revert of `performMemberLookup` changes, maybe that what caused "too complex" in that test, going to give rebased version a try.

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@rudkx Here is the expression in expression in question - https://github.com/pinterest/plank/blob/master/Sources/Core/ObjCModelRenderer.swift#L166

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@rudkx going to wait for the source compat suite to run to verify but it looks like we don't have to track literal presence anymore while linking expressions together because we don't bind types which means it's up to solver to deduce everything. Got failing "Plank" to pass locally with these changes too.

**Review by rudkx — APPROVED** [review]
LGTM!

**Pull request merged**
