### PR TITLE
IRGen thunk outlining mangling fixes

### PR DESCRIPTION
**Pull request by slavapestov**
- Change the mangling to free up space in the W namespace
- Correctly mangle generic types
- ODR identical thunks together

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
Note that this fixes a miscompile - we used to fold together outlined retain and release calls for different generic signatures, which is wrong

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by jckarter** [comment]
Looks good to me. Might be a good check that the demangler robustly handles/ignores the old manglings since the OS manglers on some platforms may still try to digest them.

**Comment by shajrawi** [comment]
As I mentioned on PR 15555 - looks good to me. thanks for doing this.

**Pull request merged**
