### PR TITLE
[tests] Verify the libSyntax tree on SILGen tests

### PR DESCRIPTION
**Pull request by ahoppen**
The SILGen testsuite consists of valid Swift code covering most language features. We can use these tests to verify that no unknown nodes are in the file's libSyntax tree. That way we will (hopefully) catch any future changes or additions to the language which are not implemented in libSyntax.

For this I created new lit-substitutions `%target-swift-emit-silgen`, `%target-swift-emit-sil`, `%target-swift-emit-ir` that just resolve to `%target-swift-frontend` with the corresponding emit-flag and `-verify-syntax-tree`.

### CODE REVIEW

**Review by nkcsgexi — APPROVED** [review]
LGTM!

**Review by eeckstein — COMMENTED** [review]
What is the purpose of the new substitutions?
Is it just simplification of the run command lines or do you intend to substitute to something else for libSyntax tests?

**Comment by ahoppen** [comment]
@eeckstein The idea is that it would be really easy to miss the `-verify-syntax-tree` when creating new tests (which are one of the most interesting since they probably contain new syntax). This way it's harder to miss.

@swift-ci Please smoke test

**Comment by eeckstein** [comment]
I see. lgtm!

**Comment by nkcsgexi** [comment]
Shouldn't we handle `@_silgen_name` as a regular decl attribute?

**Comment by ahoppen** [comment]
We do. But it has an effect on whether the following declaration needs a body or not.

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test and merge

**Comment by jrose-apple** [comment]
Eek. I missed this when it went in but I really don't like it. We have too many substitutions already.

Is there any reason we can't just add this to the AST verifier, and only run it when we make it past parsing?

**Comment by ahoppen** [comment]
We are verifying the libSyntax tree and not the AST, so we can't build it into the AST verifier. And to verify the libSyntax tree, we actually need to generate it, which is associated with some cost, which is why I decided to put the option behind another flag. We could have just added `-verify-syntax-tree` but as I mentioned above, I thought that this would be easy to miss, so I created another substitution that inserts it automatically.

**Comment by jrose-apple** [comment]
But `-verify-syntax-tree` doesn't control whether the tree is built, only whether it's verified. And it's stored in the SourceFile, so you totally can get at it from the AST verifier.

(I must be missing something at this point.)

**Comment by ahoppen** [comment]
It does control whether the syntax tree gets built: https://github.com/apple/swift/blob/master/lib/Frontend/CompilerInvocation.cpp#L216

**Comment by jrose-apple** [comment]
Aack, I was looking just for the LangOptions setting! \*sigh\* Okay then.

**Pull request merged**
