### PR TITLE
[DO NOT MERGE] Revert "Increase inlining benefits for function calls with many arguments or results"

### PR DESCRIPTION
**Pull request by asl**
This is open just to run benchmarks

### CODE REVIEW

**Comment by asl** [comment]
@swift-ci please benchmark

**Comment by asl** [comment]
@eeckstein Looks like there are observable differences in benchmarks. Anything you'd want me to check?

For anyone looking into this: OLD is current `main` (after https://github.com/swiftlang/swift/pull/77629), NEW is before https://github.com/swiftlang/swift/pull/77629.

So *regressions* are actually *improvements* and vice versa.

### Performance (x86_64): -O

**Regression**                          | **OLD** | **NEW**  | **DELTA** | **RATIO**
:---                                    | ---:    | ---:     | ---:   | ---:     
StringDistance.utf16.ascii              | 113.0   | 150.938  | +33.6% | **0.75x (?)**
UTF8Decode_InitFromData                 | 134.923 | 173.818  | +28.8% | **0.78x (?)**
UTF8Decode_InitFromCustom_contiguous    | 138.462 | 171.357  | +23.8% | **0.81x (?)**
UTF8Decode_InitFromBytes                | 141.2   | 172.231  | +22.0% | **0.82x (?)**
UTF8Decode_InitDecoding                 | 141.333 | 172.1    | +21.8% | **0.82x**
Array.removeAll.keepingCapacity.Object  | 5.958   | 7.168    | +20.3% | **0.83x (?)**
NibbleSort                              | 1360.0  | 1614.545 | +18.7% | **0.84x (?)**
KeyPathNestedClasses                    | 163.538 | 193.917  | +18.6% | **0.84x (?)**
Dictionary4OfObjects                    | 235.2   | 276.2    | +17.4% | **0.85x (?)**
KeyPathClassStructs                     | 411.75  | 483.5    | +17.4% | **0.85x (?)**
CStringLongNonAscii                     | 129.667 | 143.818  | +10.9% | **0.90x (?)**
Phonebook                               | 993.364 | 1084.364 | +9.2%  | **0.92x (?)**
StringComparison_nonBMPSlowestPrenormal | 436.176 | 472.308  | +8.3%  | **0.92x (?)**
DistinctClassFieldAccesses              | 31.648  | 34.125   | +7.8%  | **0.93x (?)**
&nbsp; | | | | 
**Improvement**                         | **OLD** | **NEW**  | **DELTA** | **RATIO**
SubstringFromLongStringGeneric2         | 31.16   | 26.37    | -15.4% | **1.18x (?)**
CharacterLiteralsLarge                  | 69.045  | 60.114   | -12.9% | **1.15x (?)**
ChaCha                                  | 85.333  | 74.5     | -12.7% | **1.15x (?)**
Set.isDisjoint.Seq.Int.Empty            | 42.786  | 38.486   | -10.0% | **1.11x (?)**
Set.isSubset.Int.Empty                  | 51.2    | 46.471   | -9.2%  | **1.10x (?)**
SubstringFromLongString2                | 26.125  | 23.939   | -8.4%  | **1.09x (?)**
CharacterLiteralsSmall                  | 213.75  | 196.0    | -8.3%  | **1.09x (?)**
SortLettersInPlace                      | 232.667 | 214.444  | -7.8%  | **1.08x (?)**
Set.isDisjoint.Box.Empty                | 57.667  | 53.361   | -7.5%  | **1.08x (?)**

### Code size: -O

**Regression**          | **OLD** | **NEW** | **DELTA** | **RATIO**
:---                    | ---:  | ---:  | ---:  | ---:   
SubstringTest.o         | 18232 | 18846 | +3.4% | **0.97x**
StringComparison.o      | 33732 | 34354 | +1.8% | **0.98x**
StringSplitting.o       | 35080 | 35694 | +1.8% | **0.98x**
CSVParsing.o            | 57486 | 58100 | +1.1% | **0.99x**
&nbsp; | | | | 
**Improvement**         | **OLD** | **NEW** | **DELTA** | **RATIO**
SortLettersInPlace.o    | 8575  | 8106  | -5.5% | **1.06x**
SortIntPyramids.o       | 8910  | 8438  | -5.3% | **1.06x**
StaticArray.o           | 11487 | 11031 | -4.0% | **1.04x**
Phonebook.o             | 10495 | 10111 | -3.7% | **1.04x**
NibbleSort.o            | 13824 | 13368 | -3.3% | **1.03x**
RGBHistogram.o          | 20798 | 20326 | -2.3% | **1.02x**
SortLargeExistentials.o | 22832 | 22320 | -2.2% | **1.02x**
SortStrings.o           | 23918 | 23434 | -2.0% | **1.02x**
WordCount.o             | 37421 | 36829 | -1.6% | **1.02x**
ChaCha.o                | 15047 | 14831 | -1.4% | **1.01x**
Breadcrumbs.o           | 47337 | 46729 | -1.3% | **1.01x**

### Performance (x86_64): -Osize

**Regression**                           | **OLD**  | **NEW**  | **DELTA** | **RATIO**
:---                                     | ---:     | ---:     | ---:   | ---:     
FlattenListLoop                          | 1112.0   | 1565.0   | +40.7% | **0.71x (?)**
UTF8Decode_InitFromBytes                 | 141.75   | 174.727  | +23.3% | **0.81x (?)**
KeyPathNestedClasses                     | 168.538  | 204.556  | +21.4% | **0.82x (?)**
UTF8Decode_InitDecoding                  | 138.667  | 168.3    | +21.4% | **0.82x (?)**
UTF8Decode_InitFromData                  | 139.286  | 167.833  | +20.5% | **0.83x**
Array.removeAll.keepingCapacity.Object   | 5.856    | 7.048    | +20.4% | **0.83x (?)**
UTF8Decode_InitFromCustom_contiguous     | 141.615  | 169.0    | +19.3% | **0.84x (?)**
StaticArray                              | 1.83     | 2.13     | +16.4% | **0.86x (?)**
KeyPathGet                               | 176.5    | 204.0    | +15.6% | **0.87x (?)**
StringDistance.utf16.ascii               | 112.133  | 127.0    | +13.3% | **0.88x (?)**
KeyPathClassStructs                      | 440.25   | 496.333  | +12.7% | **0.89x (?)**
KeyPathMutatingGetset                    | 193.727  | 216.9    | +12.0% | **0.89x (?)**
CStringLongNonAscii                      | 129.588  | 144.231  | +11.3% | **0.90x (?)**
UTF8Decode_InitFromCustom_noncontiguous  | 263.375  | 289.714  | +10.0% | **0.91x (?)**
FlattenListFlatMap                       | 3664.0   | 4028.0   | +9.9%  | **0.91x (?)**
MapReduceClass2                          | 132.611  | 144.214  | +8.7%  | **0.92x (?)**
StringComparison_nonBMPSlowestPrenormal  | 437.059  | 473.0    | +8.2%  | **0.92x (?)**
String.initRepeating.longMixStr.Count100 | 671.0    | 724.5    | +8.0%  | **0.93x (?)**
CxxStringConversion.cxx.to.swift         | 105.333  | 113.5    | +7.8%  | **0.93x (?)**
StringDistance.scalars.ascii             | 702.333  | 756.667  | +7.7%  | **0.93x (?)**
&nbsp; | | | | 
**Improvement**                          | **OLD**  | **NEW**  | **DELTA** | **RATIO**
StringWithCString2                       | 0.001    | 0.0      | -50.0% | **2.00x (?)**
CharacterLiteralsLarge                   | 61.619   | 50.107   | -18.7% | **1.23x (?)**
SubstringFromLongStringGeneric2          | 30.5     | 26.128   | -14.3% | **1.17x (?)**
ChaCha                                   | 83.0     | 72.556   | -12.6% | **1.14x (?)**
ArrayLiteral2                            | 81.632   | 72.952   | -10.6% | **1.12x (?)**
DropLastSequence                         | 348.167  | 311.667  | -10.5% | **1.12x (?)**
DropLastSequenceLazy                     | 347.5    | 312.167  | -10.2% | **1.11x (?)**
DistinctClassFieldAccesses               | 43.605   | 39.25    | -10.0% | **1.11x (?)**
Set.isSubset.Int.Empty                   | 50.72    | 45.731   | -9.8%  | **1.11x (?)**
Set.isStrictSubset.Int.Empty             | 43.021   | 39.028   | -9.3%  | **1.10x (?)**
CharacterLiteralsSmall                   | 209.889  | 191.7    | -8.7%  | **1.09x (?)**
CharIteration_ascii_unicodeScalars       | 4500.0   | 4111.111 | -8.6%  | **1.09x (?)**
Set.isDisjoint.Seq.Box.Empty             | 51.186   | 46.83    | -8.5%  | **1.09x (?)**
Set.isSuperset.Seq.Empty.Int             | 52.275   | 47.923   | -8.3%  | **1.09x (?)**
CharIteration_tweet_unicodeScalars       | 8711.111 | 8060.0   | -7.5%  | **1.08x (?)**
ReversedBidirectional                    | 6180.0   | 5766.0   | -6.7%  | **1.07x (?)**

### Code size: -Osize

**Regression**          | **OLD** | **NEW** | **DELTA** | **RATIO**
:---                    | ---:  | ---:  | ---:  | ---:   
SubstringTest.o         | 16699 | 17342 | +3.9% | **0.96x**
StringComparison.o      | 29320 | 29971 | +2.2% | **0.98x**
StringSplitting.o       | 33902 | 34392 | +1.4% | **0.99x**
&nbsp; | | | | 
**Improvement**         | **OLD** | **NEW** | **DELTA** | **RATIO**
SortIntPyramids.o       | 8374  | 7964  | -4.9% | **1.05x**
Phonebook.o             | 9460  | 9033  | -4.5% | **1.05x**
StaticArray.o           | 9884  | 9474  | -4.1% | **1.04x**
NibbleSort.o            | 13469 | 13059 | -3.0% | **1.03x**
RGBHistogram.o          | 18096 | 17652 | -2.5% | **1.03x**
SortLettersInPlace.o    | 6740  | 6575  | -2.4% | **1.03x**
SortLargeExistentials.o | 22412 | 21950 | -2.1% | **1.02x**
SortStrings.o           | 23177 | 22775 | -1.7% | **1.02x**
ChaCha.o                | 13573 | 13377 | -1.4% | **1.01x**
WordCount.o             | 35007 | 34542 | -1.3% | **1.01x**

### Performance (x86_64): -Onone

**Regression**                       | **OLD**  | **NEW** | **DELTA** | **RATIO**
:---                                 | ---:     | ---:    | ---:    | ---:     
SetSubtractingInt100                 | 107.684  | 232.3   | +115.7% | **0.46x**
SetSubtractingInt50                  | 149.0    | 286.429 | +92.2%  | **0.52x (?)**
SetSubtractingInt25                  | 172.0    | 310.5   | +80.5%  | **0.55x (?)**
Set.subtracting.Seq.Int100           | 2405.0   | 3133.0  | +30.3%  | **0.77x (?)**
Set.subtracting.Seq.Int50            | 2631.0   | 3399.0  | +29.2%  | **0.77x (?)**
Set.subtracting.Seq.Int25            | 2767.0   | 3524.0  | +27.4%  | **0.79x (?)**
UTF8Decode_InitDecoding              | 146.0    | 175.0   | +19.9%  | **0.83x (?)**
UTF8Decode_InitFromData              | 138.6    | 165.875 | +19.7%  | **0.84x (?)**
SetSubtractingBox25                  | 663.333  | 792.0   | +19.4%  | **0.84x (?)**
UTF8Decode_InitFromBytes             | 142.923  | 169.7   | +18.7%  | **0.84x (?)**
UTF8Decode_InitFromCustom_contiguous | 147.769  | 174.727 | +18.2%  | **0.85x (?)**
KeyPathNestedClasses                 | 171.154  | 200.5   | +17.1%  | **0.85x (?)**
StringRemoveDupes                    | 492.75   | 569.0   | +15.5%  | **0.87x (?)**
DataSubscriptMedium                  | 52.282   | 60.188  | +15.1%  | **0.87x (?)**
ArrayAppendReserved                  | 2283.333 | 2618.0  | +14.7%  | **0.87x (?)**
KeyPathGet                           | 188.455  | 211.111 | +12.0%  | **0.89x (?)**
Set.subtracting.Seq.Box25            | 5388.0   | 5992.0  | +11.2%  | **0.90x (?)**
&nbsp; | | | | 
**Improvement**                      | **OLD**  | **NEW** | **DELTA** | **RATIO**
RC4                                  | 9578.0   | 8325.0  | -13.1%  | **1.15x (?)**
CharacterLiteralsSmall               | 778.0    | 717.333 | -7.8%   | **1.08x (?)**

### Code size: -swiftlibs

**Improvement**                 | **OLD** | **NEW** | **DELTA** | **RATIO**
:---                            | ---:   | ---:   | ---:  | ---:   
libswiftSwiftOnoneSupport.dylib | 180224 | 163840 | -9.1% | **1.10x**
libswiftStdlibUnittest.dylib    | 360448 | 344064 | -4.5% | **1.05x**


<details>
  <summary><strong>How to read the data</strong></summary>
The tables contain differences in performance which are larger than 8% and
differences in code size which are larger than 1%.

If you see any unexpected regressions, you should consider fixing the
regressions before you merge the PR.

**Noise**: Sometimes the performance results (not code size!) contain false
alarms. Unexpected regressions which are marked with '(?)' are probably noise.
If you see regressions which you cannot explain you can try to run the
benchmarks again. If regressions still show up, please consult with the
performance team (@eeckstein).
</details>

<details>
  <summary><strong>Hardware Overview</strong></summary>

      Model Name: Mac mini
      Model Identifier: Macmini8,1
      Processor Name: 6-Core Intel Core i7
      Processor Speed: 3.2 GHz
      Number of Processors: 1
      Total Number of Cores: 6
      L2 Cache (per Core): 256 KB
      L3 Cache: 12 MB
      Memory: 32 GB

</details>

**Comment by eeckstein** [comment]
I didn't expect so many code size regressions. But overall I think it's fine. Changing the inlining heuristic always causes a bit of churn.

**Comment by asl** [comment]
> I didn't expect so many code size regressions. But overall I think it's fine. Changing the inlining heuristic always causes a bit of churn.

Yes, functions with many parameters often have lots of live values, so inlining them can increase the overall code size. Though we are saving a lot on argument spills / restores

**Pull request closed without merging**
