### PR TITLE
SILGen: Handle key paths with `@objc optional` property and subscript components

### LINKED ISSUE #58337: [SR-16076] Compiler crashes in release mode when using compactMap with a key path to an @objc optional property
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-16076      |
   |Radar             | None         |
   |Original Reporter | @davedelong      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Xcode 13.3 and Xcode 13.2.1

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | swift    |
   |Labels            | Bug        |
   |Assignee          | @AnthonyLatsis      |
   |Priority          | Medium      |

   

   md5: 2b2d253ea8e84f4670e030c4b62dd6c5

  </details>

**Issue Description:**

Given this code:

``` swift
@objc protocol OptionalVar {
    @objc optional var name: String { get }
}

extension NSObject: OptionalVar { }

let objects = [
    NSObject(),
    NSObject(),
    NSObject()
] as Array<OptionalVar>

let names = objects.compactMap(\.name)
print("Names: \(names)")
```

This will build and run fine in debug mode (`-Onone`), but the compiler crashes when in building in release mode (`-O`).

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
Resolves #58337

### CODE REVIEW

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test macOS

**Comment by AnthonyLatsis** [comment]
Note that this will still crash during SIL generation if the `optional` requirement has a setter. I wonder why `optional` requirements are even allowed to have a setter if we lack the plumbing for that case.

**Comment by jckarter** [comment]
Thanks! Yeah, setters on optional properties (and on properties found through dynamic member lookup on `AnyObject`) were one thing we put off thinking we could come up with a clever way to model, but never got around to. Modeling the key path component as get-only should be sufficient in the meantime.

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by AnthonyLatsis** [comment]
> Modeling the key path component as get-only should be sufficient in the meantime.

Will do in a follow-up!

**Comment by AnthonyLatsis** [comment]
@jckarter Should I consider this approved?

**Review by slavapestov — APPROVED** [review]

**Comment by jckarter** [comment]
It looks like the type checker after this change still treats a key path referencing an `@objc optional` property as a `WritableKeyPath`, which after this fix, causes us to still crash if people try to do something like `foo[keyPath: \.optionalProperty] = bar`. Would you be able to fix that aspect as well?

**Comment by AnthonyLatsis** [comment]
Sorry, got carried away. Will look into this later today!

**Pull request merged**
