### PR TITLE
Un-break resilience tests on non-mac platforms

### PR DESCRIPTION
**Pull request by milseman**

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please test

**Comment by slavapestov** [comment]
Did you actually see them fail on Linux? They passed when I merged the PR.

However for the iOS simulators, I don't know how to make the simulator copy the dylib when it runs the binary. @jrose-apple any ideas?

**Comment by jrose-apple** [comment]
I'm sure this was just faster than having three UNSUPPORTED lines.

`%target-run` treats arguments as resources, and will copy them. You can pass the dylib as an (ignored) argument and that'll take care of it. But @gparker42 would know if there's a better way, or if it's already supposed to work.

**Comment by gparker42** [comment]
Yes, that's the best way to copy a file along with the test executable in the current infrastructure.

You also might need to fix the rpaths and install names of the test dylibs and executables. The values currently used have absolute paths. Having said that, it might work anyway because I think remote test execution also sets DYLD_LIBRARY_PATH and that might be sufficient in this case.

**Pull request merged**
