### PR TITLE
[AST] Perf: Improve getDesugaredType() efficiency

### PR DESCRIPTION
**Pull request by davezarzycki**
Make getDesugaredType() as fast as possible for now. With the old way:

1) Switching over the sugared types turned into a frequently mispredicted branch because the sugar in the type system is random as far as the processor is concerned.
2) Storing the underlying/singlely-desugared type at different offsets in memory adds more code bloat and misprediction.

Short of a major redesign to avoid pointer chasing, this is probably as fast as the method will get.

@DougGregor / @CodaFi / @slavapestov – With this change, `NameAliasType` now caches some – but not all – results to avoid pointer chasing (just like the syntax sugared types do so they don't need to ask the AST ever time). My question is this, is the caching I setup in `getSinglyDesugaredTypeSlow()` correct? Could it cache more? It certainly cannot cache all results, otherwise a couple tests break.

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please test

**Comment by davezarzycki** [comment]
For reference, this fails if we cache all `NameAliasType` desugaring: `compiler_crashers_2_fixed/0114-rdar33189068.swift`

**Comment by jckarter** [comment]
What sort of performance impact does this have in practice?

**Comment by slavapestov** [comment]
The underlying type of a TypeAliasDecl should never change after being computed. We should add an assertion somewhere for that.

**Comment by davezarzycki** [comment]
Hi @slavapestov – If we add an assert, then `compiler_crashers_2_fixed/0114-rdar33189068.swift` will crash. Want a bug report for now?

**Comment by davezarzycki** [comment]
Hi Joe – On my "Kaby Lake" MacBook Pro, I see about a 3.57% improvement when building `Swift.swiftmodule`

**Comment by davezarzycki** [comment]
Hi @slavapestov – Just FYI: https://bugs.swift.org/browse/SR-6694

**Comment by jckarter** [comment]
@davezarzycki Nice!

**Pull request merged**
