### PR TITLE
Update mailmap

### PR DESCRIPTION
**Pull request by lilyball**
I should have done this a while ago.

### CODE REVIEW

**Review by beccadax — APPROVED** [review]
Looks perfect to me. Oh, and the patch is fine too. 😇

**Comment by beccadax** [comment]
@swift-ci please smoke test

**Comment by beccadax** [comment]
There was a bug in swift-driver, but it should have been fixed. One more time…

@swift-ci please smoke test

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
