### PR TITLE
check-incremental: explicitly use python3

### PR DESCRIPTION
**Pull request by edymtt**
Addresses rdar://88092462

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci please python lint

**Review by drexin — APPROVED** [review]

**Comment by edymtt** [comment]
preset=buildbot,tools=R,stdlib=RD
@swift-ci Please test with preset macOS Platform

**Comment by edymtt** [comment]
@swift-ci please smoke test

**Comment by edymtt** [comment]
@swift-ci please test Apple Silicon

**Review by jorng — CHANGES_REQUESTED** [review]
You'll need to update the `subprocess.check_output` call on line 38 to decode the output and return a string.

```py
md5 = subprocess.check_output(["md5", "-q", output_file], text=True)
```

**Comment by edymtt** [comment]
@swift-ci please python lint

**Comment by edymtt** [comment]
preset=buildbot,tools=R,stdlib=RD
@swift-ci Please test with preset macOS Platform

**Comment by edymtt** [comment]
@swift-ci please smoke test

**Comment by edymtt** [comment]
@swift-ci please test Apple Silicon

**Review by jorng — APPROVED** [review]

**Review by compnerd — APPROVED** [review]

**Comment by edymtt** [comment]
The preset job failure is unrelated to this PR -- we are failing the test `Concurrency/property_initializers_swift6.swift`, but we pass successfully the build of the standard library (the part that uses `check-incremental`)

**Pull request merged**
