### PR TITLE
Various Python cleanups

### PR DESCRIPTION
**Pull request by practicalswift**
Fixes:
- Unused import
- Redundant backslash
- Use of discouraged if not x in y
- Use of deprecated form of raising exceptions

Follow-up to PR #655 as requested by @gribozavr

### CODE REVIEW

**Comment by gribozavr** [comment]
@nadavrot @gottesmm @eeckstein Could you review the `pass-pipeline` and `cmpcodesize` changes?

@akyrtzi Could you review SourceKit bindings?

**Comment by eeckstein** [comment]
cmpcodesize LGTM

**Comment by akyrtzi** [comment]
To clarify about sourcekitd bindings: this was experimental, it has no tests and no-one depends on it AFAIK.
That said, the changes LGTM.

**Comment by gribozavr** [comment]
@gottesmm Could you review the `pass-pipeline` changes?

**Comment by practicalswift** [comment]
@akyrtzi Is it worth keeping `tools/SourceKit/bindings/python/sourcekitd/` in the main Swift repo or is it a candidate for deletion?

**Comment by gottesmm** [comment]
The pass-pipeline changes look ok to me. If it breaks anything, the next time I use it, I will fix it.

**Comment by gribozavr** [comment]
Thanks everyone for reviews!  Merging.

**Comment by akyrtzi** [comment]
@practicalswift it may be worth keeping as a starting point in case anyone is interested in enhancing the python bindings.

**Comment by practicalswift** [comment]
@akyrtzi Sounds good! Let's keep it around :-)

**Pull request merged**
