### PR TITLE
Remove The Parser Hack For If-Let

### PR DESCRIPTION
**Pull request by CodaFi**
The parser used to rewrite

```
if let x: T
```

into

```
if let x: T?
```

This transformation is correct at face value, but relied on being able
to construct TypeReprs with bogus source locations. Instead of having
the parser kick semantic analysis into shape, let's perform this
reinterpretation when we resolve if-let patterns in statement
conditions.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci test source compatibility

**Review by akyrtzi — APPROVED** [review]
Thank you! 🙇🏻‍♂️

**Comment by CodaFi** [comment]
@swift-ci test source compatibility release

**Review by slavapestov — APPROVED** [review]

**Comment by CodaFi** [comment]
Hm... so this is source breaking because we didn't catch

```
 if let _ = b ?? b {}
```

where `b : Any` before. Let's hope it passes source compat, because missing the error is a hole.

**Comment by CodaFi** [comment]
@swift-ci test source compatibility release

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by CodaFi** [comment]
@swift-ci test Windows

**Comment by CodaFi** [comment]
@swift-ci test Windows

**Comment by CodaFi** [comment]
@swift-ci test Windows

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
