### PR TITLE
[CMake] Add support for installing FileCheck, if requested.

### PR DESCRIPTION
**Pull request by ddunbar**
#### What's in this pull request?

This adds a new installable component for use in installing `FileCheck` into the toolchain (as discussed on swift-dev).

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by ddunbar** [comment]
@swift-ci please test

**Comment by ddunbar** [comment]
@gribozavr can you review?

**Comment by gribozavr** [comment]
It is probably OK, but it does feel hacky that we are installing a file built by LLVM.

But I do see that it can become a complex if we wanted to thread it through the LLVM build system which does not have such a convenient notion of things to install (it uses separate top-level targets IIRC).

**Comment by tkremenek** [comment]
This LGTM.

**Comment by ddunbar** [comment]
I agree it is gross, but it is an "expedient hack" to improve our development.

**Comment by ddunbar** [comment]
@swift-ci please test and merge

**Pull request merged**
