### PR TITLE
[Distributed] NFC: Disable remote call test on 32-bit watchOS

### PR DESCRIPTION
**Pull request by xedin**

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
Very weird... it failed on check-swift-validation-macosx-x86_64 😕 but we see it pass consistently in smoke tests... very confused :| 


```
10:05:06 --
10:05:06 Exit Code: 2
10:05:06 
10:05:06 Command Output (stderr):
10:05:06 --
10:05:06 FileCheck error: '<stdin>' is empty.
10:05:06 FileCheck command line:  /Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/buildbot_incremental/llvm-macosx-x86_64/bin/FileCheck --allow-unused-prefixes /Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/swift/test/Distributed/Runtime/distributed_actor_remoteCall.swift --dump-input=always
10:05:06 
10:05:06 --
```

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Comment by xedin** [comment]
macOS succeeded, let's try one more time. I think the changes in my other PR might have resolved the issue.

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Pull request merged**
