### PR TITLE
Move tensorflow commit to pick up shape inference API.

### PR DESCRIPTION
**Pull request by bgogul**
Moves the tensorflow commit to tensorflow/tensorflow@fee0b38d so that we pick up tensorflow/tensorflow@b898082, where a new experimental shape inference API is introduced.

### CODE REVIEW

**Comment by bgogul** [comment]
@swift-ci please clean test tensorflow

**Comment by bgogul** [comment]
@swift-ci please clean test tensorflow

**Comment by bgogul** [comment]
@swift-ci please clean test tensorflow

**Comment by bgogul** [comment]
@swift-ci please clean test tensorflow gpu

**Comment by bgogul** [comment]
@swift-ci please clean test tensorflow-gpu

**Comment by bgogul** [comment]
@swift-ci please clean test tensorflow

**Comment by bgogul** [comment]
@swift-ci please clean test tensorflow

**Comment by bgogul** [comment]
@swift-ci please clean test tensorflow-gpu

**Comment by bgogul** [comment]
@swift-ci please clean test tensorflow-gpu

**Comment by bgogul** [comment]
@swift-ci please clean test tensorflow-gpu

**Comment by bgogul** [comment]
@swift-ci please clean test tensorflow gpu

**Comment by bgogul** [comment]
@swift-ci please clean test tensorflow gpu

**Comment by bgogul** [comment]
@swift-ci please clean test tensorflow

**Comment by bgogul** [comment]
@swift-ci please clean test tensorflow gpu

**Comment by bgogul** [comment]
@swift-ci please clean test tensorflow gpu

**Comment by bgogul** [comment]
@swift-ci please clean test tensorflow linux

**Comment by bgogul** [comment]
@swift-ci please clean test tensorflow

**Review by pschuh — APPROVED** [review]

**Comment by bgogul** [comment]
The GPU tests are failing because the nccl files in ~/.cache/bazel is not compatible with the tensorflow commit hash. This should build if the ~/.cache/bazel is completely removed. See the successful run here: 
https://ci-external.swift.org/view/Pull%20Request/job/swift-PR-TensorFlow-Linux-gpu/1853/

Merging this in now.

**Pull request merged**
