### PR TITLE
[IRGen] Restore previous async non-constant PAF emission.

### PR DESCRIPTION
**Pull request by nate-chandler**
Previously, because partial apply forwarders for async functions were not themselves fully-fledged async functions, they were not able to handle dynamic functions.  Specifically, the reason was that it was not possible to produce an async function pointer for the partial apply forwarder because the size to be used was not knowable.

Thanks to https://github.com/apple/swift/pull/36700, that cause has been eliminated.  With it, partial apply forwarders are fully-fledged async functions and in particular have their own async function pointers.  Consequently, it is again possible for these partial apply forwarders to handle non-constant function pointers.

Here, the previous behavior is restored.

rdar://76122027

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
The only failure was because swiftasynccc wasn't enabled for i386 at the time this ran, here:
```
/Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/swift/test/IRGen/async/run-call-dynamic-void_to_void.swift:20:14: error: CHECK-LL: expected string not found in input
// CHECK-LL: musttail call swifttailcc void
             ^
<stdin>:83:81: note: scanning from here
define hidden swiftcc void @"$s4main3runyyYF"(%swift.context* swiftasync %0) #0 !dbg !50 {
                                                                                ^
<stdin>:105:2: note: possible intended match here
 tail call swiftcc void %11(%swift.context* swiftasync %0)
 ^
```

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci Please test Apple Silicon macOS Platform

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci Please test Apple Silicon macOS Platform

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci Please test Apple Silicon macOS Platform

**Comment by nate-chandler** [comment]
@swift-ci please test windows platform

**Comment by nate-chandler** [comment]
@swift-ci please test windows platform

**Comment by nate-chandler** [comment]
@swift-ci please test windows platform

**Comment by nate-chandler** [comment]
@swift-ci please test macos platform

**Comment by nate-chandler** [comment]
@swift-ci please clean test macos platform

**Comment by nate-chandler** [comment]
@swift-ci please clean test macos platform

**Comment by nate-chandler** [comment]
@swift-ci please clean test windows platform

**Pull request merged**
