### PR TITLE
Fix extended existential symbolic demangling on arm64e.

### PR DESCRIPTION
**Pull request by rjmccall**
Fixes rdar://96367576 and rdar://96367737.

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please test

**Comment by rjmccall** [comment]
@swift-ci Please test

**Comment by rjmccall** [comment]
@swift-ci Please test Apple Silicon macOS Platform

**Comment by rjmccall** [comment]
@swift-ci Please test Linux

**Review by al45tair — APPROVED** [review]
LGTM.

**Pull request merged**
