### PR TITLE
Add support for init function

### PR DESCRIPTION
**Pull request by gottesmm**
This series of commits performs a few tasks that culminate in the addition of the ability to initialize data before timing a benchmark.

Specifically:

1. Instead of creating a tuple containing data, legacy tests just now create a BenchmarkInfo struct. We still store them in the precommitTest, otherTests, stringTests variables.

2. Now that all tests use BenchmarkInfo, we no longer have to choose running either the legacy tests or use the new registered tests. Instead, we start with the registered list of benchmarks and any benchmarks that have not been registered yet are added later to that same list. This ensures that even when running in legacy mode, we get the advantage of being able to initialize global data.

3. Since we are always using BenchmarkInfo now, I pushed BenchmarkInfo all the way through the driver into Test. This is important since we are iterating over tests when we want to run the initialization closure.

3. An optional closure field called initFunction is added to BenchmarkInfo. If it is non-nil, the harness will invoke it right /before/ sampling has begun. Since the initFunction is specified in the benchmark file one to access all of the types/functions of the benchmark file in the closure.

rdar://34556274

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
I added support for a tearDown method as well and made it so that we run before/after all individual samples, rather than just ensuring that we run these before any samples have been taken.

Now this can be used like normal unittest setUp and tearDown.

**Comment by swiftix** [comment]
@gottesmm I wonder if you should add a template for the benchmark somewhere, which shows how you define those new functions, categories, etc. Developers could then just copy&paste it when they add a new benchmark and then adjust to their needs.

**Comment by gottesmm** [comment]
Sure. I can do that in a follow on commit. I can't do more than that since I am putting aside this work for a little bit.

**Comment by palimondo** [comment]
Hmm… in the commit 5cdd946 you say:
> This also ensures benchmarks that are run are always given an ascending index
instead of sometimes having indices being skipped.

I believe that was a feature. All tests were internally numbered and you could run them by this number, instead of the long name. Of course these numbers were not stable in the long run (adding and removing tests would re-assign the numbers), but were a practical shortcut when executing just a portion of a test suite you are working on.

**Comment by jrose-apple** [comment]
Tiny request: can you mention "benchmark" in your PR title next time? I had to click in to find out what this was talking about.

**Pull request merged**
