### PR TITLE
AST: Fix GenericSignatureBuilder bug with protocol typealiases

### PR DESCRIPTION
**Pull request by slavapestov**
If a nested type of a generic parameter was a typealias, and the
generic parameter was not at depth 0, index 0, we would resolve
the type down to the wrong PotentialArchetype, causing bogus
diagnostics and crashes.

Make sure we apply a substitution to the typealias's underlying
type before resolving it, to map it to the correct PotentialArchetype.

Note that the original test case in the radar works now, but the more
comprehensive test I added exposes an existing problem where generic
signature canonicalization is not idempotent. When this is fixed,
the RUN: line in the test can be changed from -typecheck to -emit-ir.

Fixes <rdar://problem/30248571>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@DougGregor and @huonw this might amuse you.

**Comment by slavapestov** [comment]
@huonw Wait, is this the same bug as https://github.com/apple/swift/pull/7389/?

**Comment by huonw** [comment]
This does the same stuff as the first commit as #7389, but I had to/am doing more to fix more things with them (e.g. explicit same-type requirements mentioning protocol typealiases will sometimes get dropped).

**Comment by DougGregor** [comment]
Yeah, this is the same as #7389, although that PR is growing beyond what fits in 3.1. This narrow fix (as noted, the same as the first commit in #7389) does look safe enough for 3.1.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Pull request merged**
