### PR TITLE
Add the compile db compile_commands.json to .gitignore.

### PR DESCRIPTION
**Pull request by gottesmm**
Title says it all.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci Please smoke test and merge

**Comment by modocache** [comment]
Awesome! This will make it easier to use code completion tools like YouCompleteMe. Thanks, @gottesmm!!

**Comment by gottesmm** [comment]
@modocache I have already been using it and by mistake did a git clean -fdx and lost my symlink.

**Comment by modocache** [comment]
It's like I'm thinking stuff, and it's materializing as comments from your GitHub account onto this thread. 🎱 ✨

**Pull request merged**
