### PR TITLE
To be able to correctly exercise Concurrency on freestanding, default to using 'pthread' threading package

### PR DESCRIPTION
**Pull request by kubamracek**
rdar://102259828

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by rokhinip — APPROVED** [review]

**Comment by kubamracek** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by kubamracek** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by kubamracek** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by kubamracek** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by mikeash — APPROVED** [review]

**Pull request merged**
