### PR TITLE
[stdlib] Remove unneeded `numericCast`s

### PR DESCRIPTION
**Pull request by benrimmington**
Follow-up to: [SE-0191](https://github.com/apple/swift-evolution/blob/master/proposals/0191-eliminate-indexdistance.md)

### CODE REVIEW

**Comment by benrimmington** [comment]
Cc: @airspeedswift

**Review by xedin — COMMENTED** [review]
Thank you! If nothing else this would make it easier to type-check these expressions without use of a generic function :)

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
(Not that I expect fireworks here)

@swift-ci benchmark

**Comment by CodaFi** [comment]
Yup, all noise.

**Comment by CodaFi** [comment]
Thanks!

⛵️

**Pull request merged**
