### PR TITLE
[Platform] Update musl modulemap and improve musl platform support.

### PR DESCRIPTION
**Pull request by al45tair**
We need to declare separate top-level modules for every header in the musl C library.  Note that our set-up here does require some tweaks to musl itself (specifically, the `alltypes.h` header needs some fairly serious massaging to make it module compatible; in particular, we need to pull out every type declaration into its own separate modularized header in `bits/types`).

Also update `Platform.swift` a little for more musl support.

rdar://123503615

### CODE REVIEW

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
**Explanation**: This adds the modulemap and header for musl.
**Original PR**: #71840
**Reviewed by**: @ian-twilightcoder 
**Resolves**: rdar://123503615
**Tests**: There are no tests that cover this yet. There will be coverage in the CI for the fully static SDK when it's up.

**Comment by al45tair** [comment]
@swift-ci Please test

**Review by tbkka — APPROVED** [review]

**Comment by al45tair** [comment]
@swift-ci Please test macOS platform

**Pull request merged**
