### PR TITLE
[AutoDiff] Use `AdditiveArithmetic.zero` to initialize cotangent vectors

### PR DESCRIPTION
**Pull request by rxwei**
Update the differentiation transform to emit a call to `AdditiveArithmetic.zero` to initialize a `0` in the cotangent space. This also helps remove the legacy code that used `ExpressibleByIntegerLiteral.init(integerLiteral:)`.

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Review by marcrasi — APPROVED** [review]
Yay! Lots of lines gone!

**Comment by rxwei** [comment]
A couple of further cleanups to do:
- Remove `FloatingPoint` from `KnownProtocols.def`.
- Remove `ASTContext::getTangentSpace` and possibly `TangentSpace`.

**Comment by rxwei** [comment]
That should already be the case, unless some `AdjointValue`s were created wrong. Do you have a crasher somewhere?

**Comment by jekbradbury** [comment]
`AdjointEmitter::materializeZeroIndirect` directly looks up the `AdditiveArithmetic` conformance on `type` rather than its cotangent vector. Here's a crasher (can file a bug if that's easier):
```swift
struct ModelParams: VectorNumeric, Differentiable {
  var w: Tensor<Float>
}

struct Model: Differentiable {
  typealias TangentVector = ModelParams
  typealias CotangentVector = ModelParams

  @differentiable(wrt: (self))
  var w: Tensor<Float>
  func tangentVector(from cotangent: CotangentVector) -> TangentVector {
    return cotangent
  }
  func moved(along direction: CotangentVector) -> Model {
    return self // incorrect dummy implementation to pass type checking
  }
}

let model = Model(w: Tensor<Float>(zeros: [5]))
let x = Tensor<Float>(zeros: [5])
let pb = pullback(at: model) { m in (m.w + x).sum() }
print(pb(Float(1.0)))
```

**Comment by rxwei** [comment]
`type` is expected to be the type of the cotangent. I expect all `AdjointValue`s to represent a value in the cotangent space. I'll fix that soon.

**Pull request merged**
