### PR TITLE
[emacs support] Parse new where clause syntax

### PR DESCRIPTION
**Pull request by dabrahams**

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please smoke test and merge

**Comment by shahmishal** [comment]
@swift-ci Please smoke test and merge

**Comment by dabrahams** [comment]
@swift-ci Please smoke test and merge

**Comment by dabrahams** [comment]
@swift-ci Please smoke test Linux platform

**Comment by dabrahams** [comment]
@swift-ci Please smoke test Linux platform

**Pull request merged**
