### PR TITLE
Use the "nearly divisionless" algorithm on all targets.

### LINKED ISSUE #53302: [SR-10912] Use Lemire's Nearly Divisionless Random Integer Generation on 32-bit Systems
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-10912      |
   |Radar             | None         |
   |Original Reporter | @palimondo      |
   |Type              | Bug    |
   |Status            | In Progress        |
   |Resolution        |     |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Standard Library    |
   |Labels            | Bug        |
   |Assignee          | @stephentyrone      |
   |Priority          | Medium      |

   

   md5: 166b2942a0feb9bafe0ca0e6c0728c8c

  </details>

**is blocked by**:  
* [SR-10910](https://bugs.swift.org/browse/SR-10910) Support multipliedFullWidth on 32-bit systems  

**Issue Description:**

Pending support for `multipliedFullWidth` on 32-bit systems (SR-10910), enable the use of Lemire's nearly divisionless random integer generation also on 32-bit systems.

### PR DESCRIPTION
**Pull request by stephentyrone**
We have multipliedFullWidth available everywhere now, so we don't need to carry around the old implementation on 32b targets.

Also adds a few more benchmarks for random number generation.

Resolves #53302

### CODE REVIEW

**Comment by stephentyrone** [comment]
@swift-ci please benchmark

**Comment by stephentyrone** [comment]
@swift-ci please benchmark

**Comment by stephentyrone** [comment]
@swift-ci test

**Review by Azoy — APPROVED** [review]
The stdlib changes look good to me. I wonder if for the benchmarks it makes sense to add separate IntegerOpaque benchmarks like the ones you did for Double so we can see clearly which integer benchmarks are constant ranges vs. going through the algorithm. I was going to ask to land these benchmarks separately, but I don't think CI runs 32b benchmarks for this to matter for this PR.

**Comment by eeckstein** [comment]
Is it possible to reduce the number of benchmarks to a representative subset?
We cannot add benchmarks for every permutation of every language feature. That would explode the benchmark runtime.

Alternatively, you can keep all the benchmarks, but add a `.skip` attribute, which excludes the from the regular run.

**Comment by stephentyrone** [comment]
This _is_ the reduced set of benchmarks! I'm not sure why we would reduce it further if we care about performance at all. I'm pretty sure that report and track fewer benchmark results for the entirety of the Swift compiler and standard library than we did for a single API in Accelerate when I was working on it(!) A reasonable set of "all" the benchmarks, just for random integers, would include the full matrix of (every builtin integer type + representative custom types) x (fast and slow generators) x (various ranges--tiny, about half, nearly all) x (compile time constant vs unknown bounds). I'm probably leaving a few dimensions out.  The benchmarks are fast--much, much faster to run than the test suite--so I don't see what we gain by stripping it down below the minimum representative sample, and there's a lot to lose in doing so.

**Comment by eeckstein** [comment]
ok, fine with me

**Pull request merged**
