### PR TITLE
[PrintAsObjC] Silence -Wnullability for the generated declarations.

### PR DESCRIPTION
**Pull request by jrose-apple**
- **Explanation**: Since Swift 3 and Swift 4 might have different views of an Objective-C API's nullability, we can end up with incompatible overrides, including with inherited initializers. This is unfortunate but also realistic; the Swift 3 code is *not* set up to handle the new nullability used by Swift 4 and Objective-C. This change silences -Wnullability for declarations in the generated Objective-C header ("MyApp-Swift.h"), to allow these mismatches.
- **Scope**: Affects warnings emitted in generated headers.
- **Radar**: rdar://problem/32571301
- **Reviewed by**: @milseman  
- **Risk**: Low
- **Testing**: Passed updated compiler regression tests.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by jrose-apple** [comment]
@swift-ci Please test macOS

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by ematejska** [comment]
@swift-ci test os x

**Comment by ematejska** [comment]
@swift-ci test source compatibility

**Pull request merged**
