### PR TITLE
[AST] NFC: Avoid fall through warnings in non-assert builds

### PR DESCRIPTION
**Pull request by davezarzycki**

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test and merge

**Review by airspeedswift — APPROVED** [review]
LGTM though I'm not totally up with the front-end code idioms.

**Comment by davezarzycki** [comment]
I'm happy to commit style/convention/idiomatic fixes as they are pointed out.

**Comment by airspeedswift** [comment]
Looks like all this did was substitute one warning for another.

```
./swift/include/swift/AST/Ownership.h:55:1: warning: control may reach end of non-void function [-Wreturn-type]
}
^
./include/swift/AST/Ownership.h:67:1: warning: control may reach end of non-void function [-Wreturn-type]
}
^
```

**Comment by davezarzycki** [comment]
Thanks @airspeedswift – I'll open a pull request shortly.

**Comment by davezarzycki** [comment]
Please see #17795

**Pull request merged**
