### PR TITLE
[stdlib][perf experiment] revert conditional BidirectionalCollection workaround

### PR DESCRIPTION
**Pull request by airspeedswift**
Reverts apple/swift#18066, to see the impact on performance. Don't merge, just trying to isolate a problem.

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please benchmark

**Comment by airspeedswift** [comment]
@moiseev @huonw @eeckstein so this was the cause it looks like – not sure if there's a quick fix for this though, since we really do need the fix in 4.2. any ideas?

**Comment by huonw** [comment]
The 4.2 submission https://github.com/apple/swift/pull/18097 is ready to merge, after we decide what to do about the regression.

It seems like this can only be due to some performance cliff in the optimiser, given how removing a function call caused a performance regression.

**Comment by eeckstein** [comment]
I'm currently looking into the perf regression.

**Comment by eeckstein** [comment]
I looked at the DropLastAnyCollection benchmark. It looks like this is not related to the optimizer. In both versions everything is inlined. The difference is that the new version has an _additional inner loop_ which iterates over the input range. So it seems that the change introduced a complexity bug.

**Comment by airspeedswift** [comment]
Closed in favor of #18165

**Pull request closed without merging**
