### PR TITLE
Metadata cache optimizations

### PR DESCRIPTION
**Pull request by rjmccall**
#### What's in this pull request?

This PR optimizes the runtime's metadata caches, now that it is no longer guaranteeing an exact in-memory representation that will be consumed by LLDB.

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

A smoke test on macOS does the following:
1. Builds the compiler incrementally.
2. Builds the standard library only for macOS. Simulator standard libraries and
   device standard libraries are not built.
3. lldb is not built.
4. The test and validation-test targets are run only for macOS. The optimized
   version of these tests are not run.

A smoke test on Linux does the following:
1. Builds the compiler incrementally.
2. Builds the standard library incrementally.
3. lldb is built incrementally.
4. The swift test and validation-test targets are run. The optimized version of these
   tests are not run.
5. lldb is tested.

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please smoke test and merge.

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by DougGregor** [comment]
Error that seems unrelated...

20:43:28 stderr>>> Assertion failed: (registered == c && "objc_readClassPair failed to instantiate the class in-place"), function swift_instantiateObjCClass, file /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/stdlib/public/runtime/SwiftObject.mm, line 1273.
20:43:28 stderr>>> CRASHED: SIGABRT
20:43:28 the test crashed unexpectedly

**Comment by rjmccall** [comment]
Not necessarily.  I want to take a look; for once, please *don't* force-merge. :)

**Comment by rjmccall** [comment]
Found the bug.  As part of this, I had incidentally fixed a bug where we weren't considering tuple labels when uniquing tuple types, and that exposed a bug where the runtime's mangling of tuple type metadata wasn't preserving those labels either, causing generic class instantiations to fail if you instantiated both A<(T,U)> and A<(a:T,b:U)>.

@swift-ci Please smoke test and merge.

**Comment by DougGregor** [comment]
@swift-ci please smoke test Linux

**Comment by gparker42** [comment]
This is causing asan failures. Reverting in #4549.

**Pull request merged**
