### PR TITLE
[ownership] Use the SILFunction attribute [ossa] instead of the global flag -assume-parsing-unqualified-ownership-sil

### PR DESCRIPTION
**Pull request by gottesmm**

### CODE REVIEW

**Comment by gottesmm** [comment]
Just a trial run.

**Comment by gottesmm** [comment]
@swift-ci test

**Review by atrick — APPROVED** [review]
Thanks!

Reminder.
- remove -assume-parsing option

- possibly disable destroy/copy_value support in case other SILOpt passes aren't handling them. But I would prefer that passes handle them because of opaque SIL values.

**Comment by gottesmm** [comment]
For those listening in, in this commit I made -assume-parsing-unqualified-ownership-sil a no-op. I am going to remove it in a forthcoming commit. This is just to reduce the diff.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Pull request merged**
