### PR TITLE
AST: Make the versioned variants of `#if canImport()` more reliable and consistent

### PR DESCRIPTION
**Pull request by tshortli**
Previously, when evaluating a `#if canImport(Module, _version: 42)` directive the compiler could diagnose and ignore the directive under the following conditions:

- The associated binary module is corrupt/bogus.
- The `.tbd` for an underlying Clang module is missing a `current-version` field.

This behavior is surprising when there is a valid `.swiftinterface` available and it only becomes apparent when building against an SDK with an old enough version of the module that the version in the `.swiftinterface` is too low, making this failure easy to miss. Some modules have different versioning systems for their Swift and Clang modules and it can also be intentional for a distributed binary `.swiftmodule` to contain bogus data (to force the compiler to recompile the `.swiftinterface`) so we need to handle both of these cases gracefully and predictably.
    
Now the compiler will enumerate all module loaders, ask each of them to attempt to parse the module version and then consistently use the parsed version from a single source. The `.swiftinterface` is preferred if present, then the binary module if present, and then finally the `.tbd`. The `.tbd` is still always used exclusively for the `_underlyingVersion` variant of `canImport()`.
    
Resolves rdar://88723492

### CODE REVIEW

**Comment by tshortli** [comment]
@swift-ci please test

**Review by nkcsgexi — APPROVED** [review]
Thank you!

**Comment by tshortli** [comment]
@swift-ci please smoke test and merge

**Review by artemcm — APPROVED** [review]
Very nice!

**Pull request merged**
