### PR TITLE
[DO NOT MERGE] [stdlib] Lazy compact map sequence

### PR DESCRIPTION
**Pull request by TellowKrinkle**
This is the implementation for [apple/swift-evolution#793](https://github.com/apple/swift-evolution/pull/793)

Note: One of the new tests fails due to what looks like a bug in the Swift overload resolution.  Should I modify it to pass and then submit a bug report on the Jira or do something else?

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by moiseev** [comment]
@swift-ci Please smoke benchmark

**Comment by moiseev** [comment]
@tellowkrinkle do you mind resolving the merge conflict?

**Comment by tellowkrinkle** [comment]
@moiseev It's been resolved

**Comment by moiseev** [comment]
@swift-ci Please benchmark

**Comment by moiseev** [comment]
@swift-ci Please benchmark

**Comment by tellowkrinkle** [comment]
Do those benchmarks run in Swift 4 mode or Swift 5 mode?

**Comment by moiseev** [comment]
Benchmarks, I think, are even Swift 3. But I was only interested in benchmarks *compiling*, as there was one failed attempt in the past, where it failed to typecheck some "complex" expressions.

**Pull request closed without merging**
