### PR TITLE
Basic: use IndexType instead of unsigned

### PR DESCRIPTION
**Pull request by compnerd**
Explicitly specify the aliased type (IndexType) rather than the
underlying type (unsigned) when invoking `CreateNode` to disambiguate
overload when targeting Windows.  NFC.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by hughbe** [comment]
Sorry! I caused a merge conflict here - trying to resolve it through the GitHub UI to ease your work didn't work :(

**Comment by hughbe** [comment]
@swift-ci please test

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by hughbe** [comment]
Here's a simple reproduction:

```
void addChild(uint64_t) { std::cout << "1"; }
void addChild(const char*) { std::cout << "2"; }

int main() { addChild(unsigned(0)); }
```

This looks like a Clang bug - GCC/MSVC reject this.

**Comment by hughbe** [comment]
Opened http://bugs.llvm.org/show_bug.cgi?id=32073, obviously a breaking change - I suggested a warning instead of an error

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test OS X platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Pull request merged**
