### PR TITLE
stdlib: disable FP80 on Windows

### PR DESCRIPTION
**Pull request by compnerd**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

The Windows ABI does not support FP80 (it is FP32, FP64 only).  Ensure that FP80
support is guarded by an OS check.

### CODE REVIEW

**Comment by gribozavr** [comment]
This seems unfortunate, but if it is an ABI decision, there isn't much we can do to fix it.

I think that you'd also need to also fix the Clang importer to import `long double` as `Double`.

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by gribozavr** [comment]
@compnerd But... how did the Cygwin port work without this change?

**Comment by compnerd** [comment]
Thats a good question.  Im not sure how that happens to work.  I just happened to notice this, and thought Id fix it.  Im happy to address the clang importer point, but Im not sure how to do accomplish that off the top of my head (just append an define or perhaps theres another flag?).  Ill look into that.

**Comment by gribozavr** [comment]
Clang importer is controlled by `lib/ClangImporter/MappedTypes.def`.  Looking at it, it seems to me that no change is actually required.

**Comment by compnerd** [comment]
I think that there are a couple of clauses I missed, Ill upload a newer version.  Sorry.

**Comment by jckarter** [comment]
Changes LGTM, but I agree with @gribozavr that we should have a test that `long double` APIs get imported as `Float64` when targeting Windows.

**Comment by compnerd** [comment]
Id love to add a test for that.  However, I seem to be having some issues convincing swift to permit importing such a function for a test.

If I create a module with:
    long double ldc(void);

The call itself is pruned if I target x86_64-apple-macosx10.10 (or any other target really).  @jckarter could you please advise on how to proceed with that?

**Comment by compnerd** [comment]
Actually, the clang importer explicitly excludes a mapping for LongDouble.  I think that we can address that separately and then add a test at that time.  Is that acceptable @gribozavr, @jckarter?

**Comment by jckarter** [comment]
Ah, yeah, if we already ignore long double imports, then there's no problem.

**Comment by compnerd** [comment]
Sounds like theres nothing left to do for this change then besides running it through CI?

**Comment by tinysun212** [comment]
Could you explain that 'The Windows ABI does not support FP80', please?
Is it related the parameter passing?  ( https://msdn.microsoft.com/en-us/library/zthk2dkh.aspx )
I'll be grateful if someone explain this and show the example code that fails when the FP80 is not supported.

**Comment by jckarter** [comment]
The Windows ABI specifies that the x87 is always set to double precision, and that `long double` is an alias of `double`.

**Comment by tinysun212** [comment]
I ran a test program.
```
Environment          sizeof(double)    sizeof(long double)
 MSVC 32bit                 8                     8
 MSVC 64bit                 8                     8
 Cygwin Clang 32bit         8                    12
 Cygwin Clang 64bit         8                    16
 Mingw64 GCC                8                    16
```
It seems to depend on 32/64bit and compiler implementation,
or Cygwin modified the ABI. Is it right?

**Comment by rjmccall** [comment]
There are a lot of different compilers targeting Windows that don't guarantee much in the way of interoperability.  Each is essentially its own separate platform as far as ABI goes.

**Comment by compnerd** [comment]
-windows-msvc and -windows-itanium are interoperable (at least for C), and both have the same behavior wrt long double being treated as double.  Can we move forward with this?

**Comment by jckarter** [comment]
What @rjmccall said. Cygwin and GCC might support long double for C code they compile, but when calling into system stdcall APIs the x87 must be in double-precision mode.

**Comment by compnerd** [comment]
ping?

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
Looks good, thanks @compnerd!

**Pull request merged**
