### PR TITLE
[moveOnly] Add a semi-generic _copy function similar to the semi-generic _move

### PR DESCRIPTION
**Pull request by gottesmm**
The way this works is that:

1. I added a new instruction called explicit_copy_value. From the perspective of Copy Propagation it is just a copy_value that it can not remove. This ensures that we have a way of explicitly forcing a copy of a value. After ownership is lowered, it just becomes a retain.
2. I did the same trick that I did with _move to make this function able to be generically used only on values that are not address only (that is not generic or existential). We do this by allowing one level of specialization to occur. We error otherwise since to handle that other case we would need to support opaque values (which we do not yet).

----

NOTE: I also noted in a different PR I did not make _move public. I did this in this PR as well so we can get both of these operators together. Thanks to @glessard for helping me to catch that!

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
Unhappily, I didn't clang-format this. So I just did that and now need to restart testing =---(.

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Review by glessard — COMMENTED** [review]
LGTM, though I am not so familiar with the SIL-related code.

**Pull request merged**
