### PR TITLE
Fix the mid-level pass pipeline

### PR DESCRIPTION
**Pull request by ghost**
This is a pull request originally created by @atrick. However, this was made months ago and with the many changes that has gone on since, I figured I would put those changes in a PR.

Original PR: #22445

> Don't inline array semantic calls before the mid-level pipeline.

> Fix the mid-level pipeline restart mechanism.

### CODE REVIEW

**Comment by pi1024e** [comment]
@swift-ci please test

**Comment by pi1024e** [comment]
@swift-ci please smoke test

**Review by theblixguy — CHANGES_REQUESTED** [review]
This contains commits unrelated to the original patch (one from #26122 for example). Also, seems like the merge was not committed correctly?

**Comment by xwu** [comment]
@atrick put his PR on hold because of performance issues that need to be investigated. If you're interested in this progressing forward, you can ping him to see if he's ready to resume or if you can help, but it's not cool to claim his work for your own.

**Comment by pi1024e** [comment]
I gave him credit, because I want to see these performance improvements in swift. I understand why it is not cool, and I apologize if it came out that way; I will ask him about it.

**Comment by CodaFi** [comment]
A lot of these changes are purely stylistic and should probably be landed individually.  Could you split them from this patch and submit them in chunks?

**Pull request closed without merging**
