### PR TITLE
[TF] Update tensorflow-swift-apis checkout.

### PR DESCRIPTION
**Pull request by rxwei**
Now tracking https://github.com/tensorflow/swift-apis/commit/16e4c2fdc33dc95978999ea1764a44bb4eecea54.

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Review by dan-zheng — APPROVED** [review]

**Comment by rxwei** [comment]
Note: This doesn't work yet because `Random.swift` exists in both repos.

**Comment by dan-zheng** [comment]
> Note: This doesn't work yet because `Random.swift` exists in both repos.

Deduping source files in CMake is possible. That likely involves renaming/copying `swift-apis` sources to a temporary directory. Some options:
* Copy to a temporary directory and only alter duplicated filenames (e.g. `Random.swift` -> `Random_.swift`).
* Copy to a temporary directory and prepend all filenames with `DeepLearning` prefix (e.g. `Random.swift` -> `DeepLearningRandom.swift`).
  * This approach produces saner filenames. If crashes occur in `DeepLearning` source code, the filename in the stack trace clearly contains `DeepLearning`.
* Rename `swift-apis` sources in place.
 * Alternating

**Comment by rxwei** [comment]
Thanks for listing these options! I'm just gonna rename Random.swift to PRNG.swift for now.

**Pull request closed without merging**
