### PR TITLE
Fix function prototypes in simd.h test

### PR DESCRIPTION
**Pull request by beccadax**
Clang is no longer allowing function prototypes to leave out return types (see https://github.com/llvm/llvm-project/commit/2cb2cd242ca08d0bbd2a51a41f1317442e5414fc). Fix a test header that does this for no particularly good reason.

Part of rdar://113413583.

### CODE REVIEW

**Comment by beccadax** [comment]
@swift-ci smoke test

**Review by etcwilde — APPROVED** [review]
Didn't clang used to assume `int`? This is just for testing and I don't think there's any real code behind it, so it probably doesn't matter?

**Comment by beccadax** [comment]
Yes, the functions implicitly returned `int`s before. However, before the header's test functions were mass-updated in 2019, they had explicit `void` return types, so I think that's the actual intent of the test: https://github.com/apple/swift/commit/1a9ae47d062814934f02748d69031210a096d668#diff-15eb75e568c5d065782cde9f8f57dc9f85ee7fece17776a27f5ee0894bcce5cfR32-R33

**Review by stephentyrone — APPROVED** [review]

**Comment by beccadax** [comment]
@swift-ci please smoke test macOS platform

**Pull request merged**
