### PR TITLE
Fix the build by ensuring that the test only runs if LLVM can compile…

### PR DESCRIPTION
**Pull request by gottesmm**
… ARM.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Review by rjmccall — APPROVED** [review]
Ah, right, I always forget that Swift is more reliant on the LLVM target being compiled in than Clang is.

**Comment by gottesmm** [comment]
No worries! Was a quick patch.

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Pull request merged**
