### PR TITLE
[WIP] Improve appending String view performance

### PR DESCRIPTION
**Pull request by airspeedswift**
Implements `_copyContents` for utf8 view, and uses `_copyContents` from `_ContiguousArrayStorage`

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci Please smoke benchmark

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
@swift-ci please test and merge

**Comment by milseman** [comment]
@airspeedswift update here? Is this PR still valid, or should it be closed?

**Pull request closed without merging**
