### PR TITLE
[move-only] When adding implicit liveness uses for class field/global accesses, do not use the terminator, use the end access.

### PR DESCRIPTION
**Pull request by gottesmm**
Previously, when doing this I could just use the terminator both in cases of
inout and for class field/global accesses... but after some recent changes to
field sensitive pruned liveness, this seems to no longer work. So just do the
right thing and use the field access.

The specific bug was that we would introduce a destroy_addr along one of the
paths where the value wasn't defined resulting in a dominance error.

I added a SIL test that shows this fixes the issue, a swift test, and also an
Interpreter test that validates the correctness.

rdar://111659649

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Review by jckarter — APPROVED** [review]

**Comment by gottesmm** [comment]
I found the problem. We were not properly converting an assignable_but_not_consumable to initable_but_not_consumable in DefiniteInitialization.

**Comment by gottesmm** [comment]
@swift-ci test

**Review by jckarter — APPROVED** [review]

**Comment by gottesmm** [comment]
Mishal just validated for me on the bot, that the test passes now.

**Pull request merged**
