### PR TITLE
[ConstraintGraph] NFC: Adjustency list and equivalence class printing…

### PR DESCRIPTION
**Pull request by xedin**
… should respect printing flags

This is a follow-up to https://github.com/apple/swift/pull/28336 which fixes a couple more places 
where `PrintOptions` haven't been properly propagated which leads to type variables being printed as `_`.

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please smoke test

**Review by CodaFi — APPROVED** [review]

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Pull request merged**
