### PR TITLE
Add 'none' to the list of available conditional compilation OS values, to support building for -none target triples

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Review by rauhul — APPROVED** [review]

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by artemcm — APPROVED** [review]

**Review by compnerd — APPROVED** [review]

**Review by MaxDesiatov — APPROVED** [review]

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test Windows platform

**Pull request merged**
