### PR TITLE
[stdlib] Providing fixits for IntMax and UIntMax

### PR DESCRIPTION
**Pull request by moiseev**
.. in order to improve migration experience.

rdar://problem/32284841

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
@swift-ci Please Test Source Compatibility

**Review by bitjammer — APPROVED** [review]
Thanks!

**Comment by moiseev** [comment]
@swift-ci Please Test Source Compatibility

**Comment by moiseev** [comment]
@swift-ci Please test

**Pull request merged**
