### PR TITLE
Move SwiftSource.cmake to stdlib

### PR DESCRIPTION
**Pull request by drexin**
All swift sources are in stdlib only and all references to swift sources have been moved there in previous PRs. This should be the last reference that's not yet in there.

### CODE REVIEW

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@swift-ci smoke test

**Review by compnerd — APPROVED** [review]

**Comment by drexin** [comment]
@swift-ci test

**Pull request merged**
