### PR TITLE
Alloc stack optimization (for review).

### PR DESCRIPTION
**Pull request by eeckstein**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by eeckstein** [comment]
@rjmccall (and everyone else who is interested) can you please take a brief look.

I do not intend to merge this PR, it's just for review, e.g. source still needs documentation, tests are missing.

I already did some measurements (see my commit message).

Some additional notes on the design: one goal was to not degrade performance compared to our current fast path (values fit in the 3-word inline buffer). Therefore I implemented several variants of the runtime functions. They don't contain any control logic in the fast path and therefore they are (almost) as fast as our current implementation.
Also, originally I tried to combine as many alloc_stacks as possible. But with this approach the runtime function gets more complicated and performance was bad (very bad). Now, by only combining at most 2 allocations, all needed parameters can be passed efficiently, which is also good for code size.

I implemented a bump-pointer allocation for the slow path. There are some discussions ongoing and we might change this in future to dynamic alloca.
We could also extend the bump pointer approach to let the bump pointer live across function calls. This would further reduce malloc traffic a lot.
And there are other possible improvements: for example re-using non-overlapping stack slots.

**Comment by rjmccall** [comment]
This is a really complicated code-generation strategy; I'm not surprised that it has such a significant cost.

**Comment by eeckstein** [comment]
Hm, what do you mean with "significant cost"?

**Comment by rjmccall** [comment]
Well, you said that the code wasn't very efficient if you tried to make more than two things at once.  I'm saying that I find that quite credible; there's a lot of complexity here.

**Comment by eeckstein** [comment]
Yeah, I think one problem of doing everything in a single function were mis-predicted branches. Now, the new small runtime functions don't contain any control statements, except for the slow-path (which can be predicted).

**Pull request closed without merging**
