### PR TITLE
[cxx-interop] Initial tests for `std::function` usage

### PR DESCRIPTION
**Pull request by egorzhdan**
This makes sure that `std::function` is imported consistently on supported platforms, and that it allows basic usage: calling a function with `callAsFunction`, initializing an empty function, and passing a function retrieved from C++ back to C++ as a parameter.

rdar://103979602

### CODE REVIEW

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by hyp** [comment]
yay!

**Review by hyp — APPROVED** [review]
LG, not sure why it's failing :(

**Comment by egorzhdan** [comment]
The Windows failure is interesting, I think we might be treating `std::function` as an unsafe type there
```
C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\test\Interop\Cxx\stdlib\use-std-function.swift:12:11: error: cannot find 'FunctionIntToInt' in scope
  let f = FunctionIntToInt()
          ^~~~~~~~~~~~~~~~
C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\test\Interop\Cxx\stdlib\use-std-function.swift:13:14: error: cannot find 'isEmptyFunction' in scope
  expectTrue(isEmptyFunction(f))
             ^~~~~~~~~~~~~~~
C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\test\Interop\Cxx\stdlib/Inputs\std-function.h:12:1: note: function 'isEmptyFunction' unavailable (cannot import)
bool isEmptyFunction(FunctionIntToInt f) { return (bool)f; }
^
```

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
The new failure on Windows:

```
<unknown>:0: error: cannot initialize object parameter of type 'const std::_Func_class<int, int>' with an expression of type 'const std::function<int (int)>'
<unknown>:0: error: failed to synthesize call to the base method 'callAsFunction' of type 'callAsFunction'
<unknown>:0: error: missing return in instance method expected to return 'Int32'
```

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
Ahhh we were missing `export *` in the modulemap... 🤦‍♂️

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Pull request merged**
