### PR TITLE
SR-14273: Bytecode Witnesses

### PR DESCRIPTION
**Pull request by gmittert**
This is an initial implementation of SR-14273: Bytecode Witnesses. It's still pretty experimental, but it works right now for a significant subset of types.

## About: 
By marking a type `@_GenerateBytecodeLayout`, rather than generating code for a types value witness functions, the Swift Compiler will instead generate a small function that calls into a runtime function that will release the type by interpreting a compile time generated bytestring (See included .rst file for the layout of said byte string). This allows for a much smaller representation for the value witness functions. This is especially useful for heavily nested enums which the current irgen creates large value witness functions due to having many branches. In my testing, the Bytestring and new functions that call into the runtime are on average 85% smaller than the functions they replace.

As this is fairly experimental, its current implementation is in a standalone library that is linked into the final executable with `-Xfrontend -enable-autolinking-runtime-compatibility-bytecode-layouts`. It also requires you to link against libcxx due to its use of std::vector. (the libcxx usage can probably be removed by implementing a dynamic array that doesn't rely on libcxx, but if this is eventually going to be merged into the swift runtime, then I believe it has access to libcxx there).

## Changes since Feedback:
Since posting here: https://forums.swift.org/t/sr-14273-byte-code-based-value-witnesses/50554 the main work has been moving everything out of the runtime library and having it work there so that it can be updated more easily until it's reasonably stable as well as fixing bugs and supporting the various platforms swift supports.

I've not changed the actual bytecode format too much. I experimented with the various suggestions in the thread, but found that I ended up needing quite a bit of information to compute extrainhabitants/spare bits regardless.

### CODE REVIEW

**Comment by aschwaighofer** [comment]
This is really cool!

What are the next steps? What are your thoughts?

Here are some of mine:

1.) Back deployment

I think this will stay outside of the runtime for a while until we have stabilized on a byte code string implementation. Therefore, I think we should replace the libcxx runtime dependencies by implementing some header only array (and the functionality you need from iostream?). Also for backwards deployment we will want a static library implementation that we can link in -- if you deployment target is older than the version that added the runtime library with byte code layout string support.

2.) Bytcode layout string instantiation at runtime

The current implementation will call through the value witness of generic arguments. This introduces some overhead that we would like to get rid of.
I think we should store the byte code layout strings at some (negative offset; above the vwt pointer?) relative offset to the metadata so that the runtime can at generic type instantiation time concatenate (+ optimize) the fields byte code layout strings. For example, for a generic struct, we would do this instantiation somewhere around here: https://github.com/apple/swift/blob/5d0bfeec172cd90e4823c16ae5f8e250f6e50d49/stdlib/public/runtime/Metadata.cpp#L2353
This optimization would only be available to new runtimes though. So for back-deployment we still need the scheme implemented in this PR. _I think_.

3.) Flag for evaluation
In addition to the attribute `@_GenerateLayoutBytecode`, in order to evaluate this on projects we would need an additional flag that enables byte code implementation for all types that support it.

**Comment by gmittert** [comment]
> I think we have to revisit the SpareBits computation.
> 
> AFAICT you can always compute spare bits. Since you can compute them from the layout.
> 
> This does not match with what Swift does today. It will only compute spare bits if it can do so statically.
> ... 
> To match the ABI I think that means you have to track when you can use the spare bits.

@aschwaighofer  To check my understanding: Swift doesn't use spare bits on non fixed sized multi enums. Looking at stdlib/public/runtime/Enum.cpp:loadMultiEnumTag, it only uses the up to 4 extra tag bytes. Therefore, it's incorrect for the bytecode runtime to always assume there are spare bits in a multi enum.

Would checking in the bytecode interpreter if an enum type is non fixed sized (i.e. contains either a Resilient type or non fixed size Archetype) be a sufficient check to correct determine if a multi enum uses spare bits or not?

**Comment by aschwaighofer** [comment]
Yes, I think this is roughly right.

You can't use spare bits if they would not be available to the runtime.

I think that means that you need to emit the info as part of the type layout string (a bit that tells us whether we can use the spare bits for a multi payload enum).
We want to be able to instantiate type layout strings so asking whether there is a archetype or resilient type reference won't give the right answer if we dynamically replaced them in the string.

As to generating comprehensive test cases. I suggest putting break points at the two source locations I mentioned above to find examples of all possible cases.

Here are some examples to start with:

```
// Module1.swift
// Compile with -enable-library-evolution -I. 
import Module2

@frozen
public struct GenericMember<T> {
  var a: Int8 = 0
  var b: Int64 = 0
  var t: T? = nil
  public init() {}
}

@frozen
public struct FragileWithSpareBits {
  var a: Int8 = 0
  var b: Int64 = 0
  public init() {}
}

@frozen
public enum FragileNonFixedMultiPayloadEnum<T> {
    case a(GenericMember<T>)
    case b(FragileWithSpareBits)
}

@frozen
public enum FragileFixedMultiPayloadEnum {
    case a(FragileWithSpareBits)
    case b(FragileWithSpareBits)
}

@frozen
public enum FargileWithResilient {
    case a(FragileWithSpareBits)
    case b(ResilientWithSpareBits)
}
```
```
// Module2.swift
// Compile with -enable-library-evolution -emit-module -module-name Module2     
                                                                                
public enum ResilientWithSpareBits {                                            
    case a(ResilientStructWithSpareBits)                                        
    case b(ResilientStructWithSpareBits)                                        
}                                                                               
                                                                                
                                                                                
public struct ResilientStructWithSpareBits {                                    
  var a: Int8 = 0                                                               
  var b: Int64 = 0                                                              
  public init() {}                                                              
}  
```

If you added the following patch:
```
diff --git a/lib/IRGen/GenEnum.cpp b/lib/IRGen/GenEnum.cpp
index ba6db93f6a1..2bd392372fd 100644
--- a/lib/IRGen/GenEnum.cpp
+++ b/lib/IRGen/GenEnum.cpp
@@ -6888,7 +6888,6 @@ const TypeInfo *TypeConverter::convertEnumType(TypeBase *key, CanType type,
   // Assert that the layout query functions for fixed-layout enums work, for
   // LLDB's sake.
 #ifndef NDEBUG
-
   // ... but not if we're building a legacy layout, in which case we only know
   // the extra inhabitant *count* and not the actual extra inhabitant values, so
   // we simply crash if we go do this.
@@ -6940,6 +6939,10 @@ const TypeInfo *TypeConverter::convertEnumType(TypeBase *key, CanType type,
 
     tagBits &= spareBits;
     assert(tagBits.none() && "tag bits overlap spare bits?!");
+  } else {
+    LLVM_DEBUG(llvm::dbgs() << "Non-fixed layout for enum ";
+               type->print(llvm::dbgs());
+               llvm::dbgs() << ":\n";);
   }
 #endif
   return ti;
```

You can use invocations like the following to see whether you have spare bits:
```
bin/swiftc -enable-library-evolution -module-name Module2 Module2.swift -Xllvm -debug-only=enum-layout -emit-ir -o /dev/null
Layout for enum ResilientWithSpareBits:
  no-payload mask:	11111111_11111111_11111111_11111111_11111111_11111111_11111111_11111111_11111111_11111111_11111111_11111111_11111111_11111111_11111111_11111111
  spare bits mask:	00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_01111111_11111111_11111111_11111111_11111111_11111111_11111111_00000000
  payload tag bits:	00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_10000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000
```

```
% bin/swiftc -emit-ir -enable-library-evolution Module1.swift -Xllvm -debug-only=enum-layout -I. > /dev/null
Non-fixed layout for enum Optional<τ_0_0>:
Non-fixed layout for enum FragileNonFixedMultiPayloadEnum<τ_0_0>:
Layout for enum FragileFixedMultiPayloadEnum:
  no-payload mask:	11111111_11111111_11111111_11111111_11111111_11111111_11111111_11111111_11111111_11111111_11111111_11111111_11111111_11111111_11111111_11111111
  spare bits mask:	00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_01111111_11111111_11111111_11111111_11111111_11111111_11111111_00000000
  payload tag bits:	00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_10000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000
Non-fixed layout for enum ResilientWithSpareBits:
Non-fixed layout for enum FargileWithResilient:
```

**Comment by gmittert** [comment]
For the sake of not continuously adding more complexity to this PR, I've disabled multi enums in this PR and then I'll take a stab at getting the NonFixed multi enums correct in another PR after this one.

@swift-ci please smoke test

**Pull request closed without merging**
