### PR TITLE
[DO NOT MERGE] [build-script] iOS simulator should still build 32-bit by default.

### PR DESCRIPTION
**Pull request by jrose-apple**
build-script version of #10510.

rdar://problem/32862833

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test Linux

**Comment by jrose-apple** [comment]
@swift-ci Please test macOS

**Comment by lplarson** [comment]
Seems reasonable to me. I have limited knowledge of this area, though.

**Review by shahmishal — APPROVED** [review]

**Comment by shahmishal** [comment]
Lets hold off from merging this PR until we have support to test with older iOS simulators.

**Comment by jrose-apple** [comment]
Did we ever figure out what to do here?

**Pull request closed without merging**
