### PR TITLE
[closure-lifetime] Add a fix_lifetime to communicate the end of lifet…

### PR DESCRIPTION
**Pull request by gottesmm**
…ime of the

closure.

Otherwise, we have ownership expressed via a control flow dependence instead of
a data dependence. This causes from an ownership issues since from a semantics
perspective, the trivial closure we use is not related to the parent operand. So
a pass like Semantic ARC Opts that uses def-use edges will remove such copies as
being unneeded. From an ownership semantics perspective, the fix_lifetime acts
as an artificial "regular use".

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
With this I can move Semantic ARC Opts pass Closure Lifetime Fixup.

**Comment by gottesmm** [comment]
The linux failure is the infamous weird dependency error. Doing a clean test!

**Comment by gottesmm** [comment]
@swift-ci clean smoke test linux platform

**Comment by rintaro** [comment]
@swift-ci Please smoke test Linux platform

**Comment by aschwaighofer** [comment]
Did you actually see issues? The mark_dependence chain should prevent destroy's from being hoisted.

**Comment by aschwaighofer** [comment]
Consider this example:

```
sil [ossa] @$s11TestClosure10testSimple1cyAA1CC_tF : $@convention(thin) (@guaranteed C) -> () {
// %0                                             // users: %3, %1
bb0(%0 : @guaranteed $C):
  debug_value %0 : $C, let, name "c", argno 1     // id: %1
  // function_ref closure #1 in testSimple(c:)
  %2 = function_ref @$s11TestClosure10testSimple1cyAA1CC_tFyyXEfU_ : $@convention(thin) (@guaranteed C) -> () // user: %4
  %3 = copy_value %0 : $C                         // users: %9, %5, %4
  %4 = partial_apply [callee_guaranteed] [on_stack] %2(%3) : $@convention(thin) (@guaranteed C) -> () // users: %8, %5
  %5 = mark_dependence %4 : $@noescape @callee_guaranteed () -> () on %3 : $C // user: %7
  // function_ref use_closure(_:)
  %6 = function_ref @$s11TestClosure11use_closureyyyyXEF : $@convention(thin) (@noescape @callee_guaranteed () -> ()) -> () // user: %7
  %7 = apply %6(%5) : $@convention(thin) (@noescape @callee_guaranteed () -> ()) -> ()
  dealloc_stack %4 : $@noescape @callee_guaranteed () -> () // id: %8
  destroy_value %3 : $C                           // id: %9
  %10 = tuple ()                                  // user: %11
  return %10 : $()                                // id: %11
}
```
Given  the mark_dependence it should not be allowed to hoist the destroy_value across ``%5``'s uses

**Comment by gottesmm** [comment]
The problem is with convert_escape_to_no_escape. I have seen cases where we do not connect the uses of the convert_escape_to_no_escape with the original lifetime and eliminate the copy_value, destroy_value.

**Comment by gottesmm** [comment]
@aschwaighofer I just updated the patch. The two main changes are:

1. In the vast majority of the cases, we can just use the copy_value as the argument to the cvt_escape_to_no_escape and everything works.
2. In the case of the switch_enum peephole, I added a mark_dependence on the copy_value and fed that into the cvt_escape_to_no_escape. This ensures that we can avoid needing to mess with the type of the copy_value (an Optional) which doesn't match the cvt_escape_to_no_escape (since its operand comes from the switch_enum payload of that same optional.

**Comment by gottesmm** [comment]
In terms of 2, it seemed like the way of connecting the two together with the least amount of instructions.

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test OS X platform

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Review by aschwaighofer — APPROVED** [review]
LG. Thank you.

**Pull request merged**
