### PR TITLE
More conservative about when we can move a release across an instruction

### PR DESCRIPTION
**Pull request by trentxintong**

### CODE REVIEW

**Comment by trentxintong** [comment]
@swift-ci please benchmark

**Comment by atrick** [comment]
Thanks for fixing that. The new logic seems correct to me.

**Comment by trentxintong** [comment]
Its not complete yet. But we can keep improving it.

**Comment by trentxintong** [comment]
@swift-ci Please benchmark

**Comment by trentxintong** [comment]
@swift-ci Please test

**Comment by trentxintong** [comment]
@swift-ci Please ASAN test

**Comment by trentxintong** [comment]
@swift-ci Please test

**Comment by trentxintong** [comment]
@swift-ci Please ASAN test

**Comment by trentxintong** [comment]
@swift-ci Please test

**Comment by trentxintong** [comment]
@swift-ci Please ASAN test

**Comment by trentxintong** [comment]
@swift-ci Please test

**Comment by trentxintong** [comment]
@swift-ci Please test

**Comment by trentxintong** [comment]
@swift-ci Please test

**Pull request merged**
