### PR TITLE
Ensure the correct function is called by prepending std:: to the std math functions

### PR DESCRIPTION
**Pull request by AZero13**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves #NNNNN, fix apple/llvm-project#MMMMM.

### CODE REVIEW

**Review by xedin — COMMENTED** [review]
Could you please elaborate why it makes any difference?

**Comment by AtariDreams** [comment]
> Could you please elaborate why it makes any difference?

Truncating doubles to floats loses precision, and promoting floats to doubles is more expensive.

**Comment by AtariDreams** [comment]
@compnerd Thoughts?

**Comment by glessard** [comment]
@swift-ci please test

**Review by compnerd — APPROVED** [review]
Sure, it does avoid some silliness with the C and C++ definitions.

**Pull request merged**
