### PR TITLE
Revert "[opt] remove trivially dead instructions in mandatory combine"

### PR DESCRIPTION
**Pull request by xedin**
Reverts apple/swift#30429

Testing to see whether this is a cause of SIL failure in source compatibility project Kingfisher.

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
Reverting this PR fixes Kingfisher project failures in debug configuration.

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
Looks like there is an unrelated break now related to `MovieSwiftUI`...

**Comment by zoecarver** [comment]
@xedin we tested fairly extensively (source compatibility and device filecheck preset). What's the error?

**Comment by xedin** [comment]
@zoecarver https://ci.swift.org/view/Source%20Compatibility/job/swift-master-source-compat-suite-debug/2848/artifact/swift-source-compat-suite/ (Kingfisher fails in 4 configurations).

**Comment by zoecarver** [comment]
Hmm I see. It might have somehow removed the destroy_addr. I'll play around with it a bit and see if I can make a reproducer.

**Comment by zoecarver** [comment]
Looks like the kingfisher build is now succeeding. Still no reproducer but, it was something to do with one of the enum operators.

**Comment by zoecarver** [comment]
@xedin I'll keep trying to debug why the crash happened but I'm beginning to suspect it wasn't this commit, actually. When building Kingfisher from master, it doesn't crash anymore but, when I checkout a5d1214220b8ddf29acf7c08c8bb42993ed56c54 and try to build I get the crash. Anyway, as I said, I'll keep trying to figure out what the cause is.

**Comment by zoecarver** [comment]
Ignore the last comment. I tracked down the issue, it was this commit (oops). Here's the following pattern that we incorrectly remove (`unchecked_take_enum_data_addr`):
```
%96 = alloc_stack $KingfisherOptionsInfoItem    // users: %111, %105, %98, %97
  copy_addr %13 to [initialization] %96 : $*KingfisherOptionsInfoItem // id: %97
  %98 = unchecked_take_enum_data_addr %96 : $*KingfisherOptionsInfoItem, #KingfisherOptionsInfoItem.downloadPriority!enumelt // user: %99
  %99 = load [trivial] %98 : $*Float
```

**Pull request merged**
