### PR TITLE
[DO NOT MERGE] Demo https://bugs.swift.org/browse/SR-4328

### PR DESCRIPTION
**Pull request by dabrahams**
Demonstrates [SR-4328](https://bugs.swift.org/browse/SR-4328) failing on the bots with presumably a different tool/SDK configuration than the one I'm using

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please smoke test

**Comment by dabrahams** [comment]
@swift-ci Please test

**Comment by dabrahams** [comment]
preset=buildbot,tools=RA,stdlib=DA
@swift-ci Please test macOS with preset

**Comment by dabrahams** [comment]
preset=dave
@swift-ci Please test macOS with preset

**Comment by dabrahams** [comment]
preset=dave
@swift-ci Please test macOS with preset

**Comment by dabrahams** [comment]
@swift-ci Please smoke test OS X platform

**Comment by dabrahams** [comment]
@swift-ci Please smoke test macOS

**Comment by dabrahams** [comment]
preset=dave
@swift-ci Please test macOS with preset

**Comment by shahmishal** [comment]
preset=dave
@swift-ci Please test macOS with preset

**Comment by shahmishal** [comment]
@dabrahams Please re-open if you are still seeing the issue with preset testing.

**Pull request closed without merging**
