### PR TITLE
[Sema] ban multi-arguments to tuple coercion

### PR DESCRIPTION
**Pull request by dduan**
#### What's in this pull request?

Implements part of SE-0110. Single argument in closures will not be accepted if
there exists explicit type with a number of arguments that's not 1.

``` swift
let f: (Int, Int) -> Void = { x in } // this is now an error
```

Note there's a second part of SE-0110 which could be considered additive,
which says one must add an extra pair of parens to specify a single arugment
type that is a tuple:

``` swift
let g ((Int, Int)) -> Void = { y in } // y should have type (Int, Int)
```

This patch does _not_ implement that part.

_Edit:_

Updates for Foundation, XCTest and SwiftPM:

https://github.com/apple/swift-corelibs-foundation/pull/497
https://github.com/apple/swift-corelibs-xctest/pull/149
https://github.com/apple/swift-package-manager/pull/581
#### Resolved bug number: ([SR-2008](https://bugs.swift.org/browse/SR-2008), partial)

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

A smoke test on macOS does the following:
1. Builds the compiler incrementally.
2. Builds the standard library only for macOS. Simulator standard libraries and
   device standard libraries are not built.
3. lldb is not built.
4. The test and validation-test targets are run only for macOS. The optimized
   version of these tests are not run.

A smoke test on Linux does the following:
1. Builds the compiler incrementally.
2. Builds the standard library incrementally.
3. lldb is built incrementally.
4. The swift test and validation-test targets are run. The optimized version of these
   tests are not run.
5. lldb is tested.

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by dduan** [comment]
@swift-ci test

**Comment by dduan** [comment]
@swift-ci test

@DougGregor

**Comment by dduan** [comment]
@swift-ci test

**Comment by dduan** [comment]
@swift-ci test

**Comment by dduan** [comment]
@swift-ci test

**Comment by dduan** [comment]
@swift-ci test

**Comment by dduan** [comment]
the Foundation build failure has been addressed in this PR: https://github.com/apple/swift-corelibs-foundation/pull/497

**Comment by CodaFi** [comment]
Nice!

AFAICT we can use this patch to sniff out problems in the dependencies first and merge this after they're fixed, right?

**Comment by dduan** [comment]
@CodaFi correct. I've done so with Foundation and XCTest.

**Comment by CodaFi** [comment]
Has this been tested against lldb, swift-playgrounds, and swiftpm?

**Comment by dduan** [comment]
@CodaFi ran test on lldb, got this. Are the unexpected success normal?

```
=============
Issue Details
=============
ERROR: test_dictionary_nsobject_any_object_dsym (lang/swift/variables/dict_nsobj_anyobj/TestSwiftDictionaryNSObjectAnyObject.py)
ERROR: test_dictionary_nsobject_any_object_dwarf (lang/swift/variables/dict_nsobj_anyobj/TestSwiftDictionaryNSObjectAnyObject.py)
ERROR: test_dictionary_nsobject_any_object_gmodules (lang/swift/variables/dict_nsobj_anyobj/TestSwiftDictionaryNSObjectAnyObject.py)
ERROR: test_with_dsym (lang/swift/tagged_pointer/TestSwiftTaggedPointer.py)
ERROR: test_with_dsym (lang/swift/foundation_value_types/notification/TestSwiftFoundationTypeNotification.py)
ERROR: test_with_dsym (lang/swift/po/nested_nsdict/TestSwiftPONestedNSDictionary.py)
ERROR: test_with_dsym (lang/swift/po/sys_types/TestSwiftPOSysTypes.py)
ERROR: test_with_dwarf (lang/swift/foundation_value_types/notification/TestSwiftFoundationTypeNotification.py)
ERROR: test_with_dwarf (lang/swift/po/sys_types/TestSwiftPOSysTypes.py)
ERROR: test_with_dwarf (lang/swift/po/nested_nsdict/TestSwiftPONestedNSDictionary.py)
ERROR: test_with_dwarf (lang/swift/tagged_pointer/TestSwiftTaggedPointer.py)
ERROR: test_with_gmodules (lang/swift/po/sys_types/TestSwiftPOSysTypes.py)
ERROR: test_with_gmodules (lang/swift/foundation_value_types/notification/TestSwiftFoundationTypeNotification.py)
ERROR: test_with_gmodules (lang/swift/po/nested_nsdict/TestSwiftPONestedNSDictionary.py)
ERROR: test_with_gmodules (lang/swift/tagged_pointer/TestSwiftTaggedPointer.py)
UNEXPECTED SUCCESS: testREPL (repl/po_repl_type/TestREPLPOReplType.py)
UNEXPECTED SUCCESS: testREPL (repl/subclassing/TestREPLSubclassing.py)
UNEXPECTED SUCCESS: testREPL (repl/structs/TestREPLStructs.py)
UNEXPECTED SUCCESS: testREPL (repl/breakpoints/TestREPLBreakpoints.py)
UNEXPECTED SUCCESS: test_add_dsym_mid_execution (macosx/add-dsym/TestAddDsymMidExecutionCommand.py)
UNEXPECTED SUCCESS: test_cross_module_extension_dsym (lang/swift/cross_module_extension/TestSwiftCrossModuleExtension.py)
UNEXPECTED SUCCESS: test_cross_module_extension_dwarf (lang/swift/cross_module_extension/TestSwiftCrossModuleExtension.py)
UNEXPECTED SUCCESS: test_cross_module_extension_gmodules (lang/swift/cross_module_extension/TestSwiftCrossModuleExtension.py)
UNEXPECTED SUCCESS: test_dsym (functionalities/exec/TestExec.py)
UNEXPECTED SUCCESS: test_dsym (lang/swift/file_private/TestFilePrivate.py)
UNEXPECTED SUCCESS: test_dsym (functionalities/fat_archives/TestFatArchives.py)
UNEXPECTED SUCCESS: test_dsym (expression_command/timeout/TestCallWithTimeout.py)
UNEXPECTED SUCCESS: test_dwarf (functionalities/fat_archives/TestFatArchives.py)
UNEXPECTED SUCCESS: test_dwarf (functionalities/exec/TestExec.py)
UNEXPECTED SUCCESS: test_dwarf (lang/swift/file_private/TestFilePrivate.py)
UNEXPECTED SUCCESS: test_dwarf (expression_command/timeout/TestCallWithTimeout.py)
UNEXPECTED SUCCESS: test_expr_dsym (lang/objc/modules-inline-functions/TestModulesInlineFunctions.py)
UNEXPECTED SUCCESS: test_expr_dsym (lang/objc/objc-new-syntax/TestObjCNewSyntax.py)
UNEXPECTED SUCCESS: test_expr_dwarf (lang/objc/objc-new-syntax/TestObjCNewSyntax.py)
UNEXPECTED SUCCESS: test_expr_dwarf (lang/objc/modules-inline-functions/TestModulesInlineFunctions.py)
UNEXPECTED SUCCESS: test_expr_gmodules (lang/objc/modules-inline-functions/TestModulesInlineFunctions.py)
UNEXPECTED SUCCESS: test_fd_leak_basic_dsym (functionalities/avoids-fd-leak/TestFdLeak.py)
UNEXPECTED SUCCESS: test_fd_leak_basic_dwarf (functionalities/avoids-fd-leak/TestFdLeak.py)
UNEXPECTED SUCCESS: test_fd_leak_basic_gmodules (functionalities/avoids-fd-leak/TestFdLeak.py)
UNEXPECTED SUCCESS: test_fd_leak_log_dsym (functionalities/avoids-fd-leak/TestFdLeak.py)
UNEXPECTED SUCCESS: test_fd_leak_log_dwarf (functionalities/avoids-fd-leak/TestFdLeak.py)
UNEXPECTED SUCCESS: test_fd_leak_log_gmodules (functionalities/avoids-fd-leak/TestFdLeak.py)
UNEXPECTED SUCCESS: test_fd_leak_multitarget_dsym (functionalities/avoids-fd-leak/TestFdLeak.py)
UNEXPECTED SUCCESS: test_fd_leak_multitarget_dwarf (functionalities/avoids-fd-leak/TestFdLeak.py)
UNEXPECTED SUCCESS: test_fd_leak_multitarget_gmodules (functionalities/avoids-fd-leak/TestFdLeak.py)
UNEXPECTED SUCCESS: test_frame_var_after_stop_at_implementation_dsym (lang/objc/real-definition/TestRealDefinition.py)
UNEXPECTED SUCCESS: test_gmodules (lang/swift/file_private/TestFilePrivate.py)
UNEXPECTED SUCCESS: test_gmodules (functionalities/fat_archives/TestFatArchives.py)
UNEXPECTED SUCCESS: test_gmodules (functionalities/exec/TestExec.py)
UNEXPECTED SUCCESS: test_gmodules (expression_command/timeout/TestCallWithTimeout.py)
UNEXPECTED SUCCESS: test_imp_ivar_type (lang/objc/ivar-IMP/TestObjCiVarIMP.py)
UNEXPECTED SUCCESS: test_lldbmi_break_insert_function (tools/lldb-mi/breakpoint/TestMiBreak.py)
UNEXPECTED SUCCESS: test_lldbmi_break_insert_function_pending (tools/lldb-mi/breakpoint/TestMiBreak.py)
UNEXPECTED SUCCESS: test_multiple_debuggers_dsym (api/multiple-debuggers/TestMultipleDebuggers.py)
UNEXPECTED SUCCESS: test_multiple_debuggers_dwarf (api/multiple-debuggers/TestMultipleDebuggers.py)
UNEXPECTED SUCCESS: test_multiple_debuggers_gmodules (api/multiple-debuggers/TestMultipleDebuggers.py)
UNEXPECTED SUCCESS: test_process_attach_with_wrong_arch_dsym (macosx/universal/TestUniversal.py)
UNEXPECTED SUCCESS: test_process_attach_with_wrong_arch_dwarf (macosx/universal/TestUniversal.py)
UNEXPECTED SUCCESS: test_process_attach_with_wrong_arch_gmodules (macosx/universal/TestUniversal.py)
UNEXPECTED SUCCESS: test_process_launch_for_universal_dsym (macosx/universal/TestUniversal.py)
UNEXPECTED SUCCESS: test_process_launch_for_universal_dwarf (macosx/universal/TestUniversal.py)
UNEXPECTED SUCCESS: test_process_launch_for_universal_gmodules (macosx/universal/TestUniversal.py)
UNEXPECTED SUCCESS: test_qRegisterInfo_returns_all_valid_results_debugserver (tools/lldb-server/TestLldbGdbServer.py)
UNEXPECTED SUCCESS: test_qRegisterInfo_returns_one_valid_result_debugserver (tools/lldb-server/TestLldbGdbServer.py)
UNEXPECTED SUCCESS: test_restart_bug_dsym (functionalities/signal/raise/TestRaise.py)
UNEXPECTED SUCCESS: test_restart_bug_dwarf (functionalities/signal/raise/TestRaise.py)
UNEXPECTED SUCCESS: test_restart_bug_gmodules (functionalities/signal/raise/TestRaise.py)
UNEXPECTED SUCCESS: test_sbdebugger_create_target_with_file_and_target_triple_dsym (macosx/universal/TestUniversal.py)
UNEXPECTED SUCCESS: test_sbdebugger_create_target_with_file_and_target_triple_dwarf (macosx/universal/TestUniversal.py)
UNEXPECTED SUCCESS: test_sbdebugger_create_target_with_file_and_target_triple_gmodules (macosx/universal/TestUniversal.py)
UNEXPECTED SUCCESS: test_specialized_typedef_from_pch_gmodules (lang/cpp/gmodules/TestWithModuleDebugging.py)
UNEXPECTED SUCCESS: test_swift_private_typealias_dsym (lang/swift/private_typealias/TestSwiftPrivateTypeAlias.py)
UNEXPECTED SUCCESS: test_swift_private_typealias_dwarf (lang/swift/private_typealias/TestSwiftPrivateTypeAlias.py)
UNEXPECTED SUCCESS: test_swift_private_typealias_gmodules (lang/swift/private_typealias/TestSwiftPrivateTypeAlias.py)
UNEXPECTED SUCCESS: test_swift_returns_dsym (lang/swift/return/TestSwiftReturns.py)
UNEXPECTED SUCCESS: test_swift_returns_dwarf (lang/swift/return/TestSwiftReturns.py)
UNEXPECTED SUCCESS: test_swift_returns_gmodules (lang/swift/return/TestSwiftReturns.py)
UNEXPECTED SUCCESS: test_symbol_name_dsym (functionalities/completion/TestCompletion.py)
UNEXPECTED SUCCESS: test_symbol_name_dwarf (functionalities/completion/TestCompletion.py)
UNEXPECTED SUCCESS: test_symbol_name_gmodules (functionalities/completion/TestCompletion.py)
UNEXPECTED SUCCESS: test_top_level_expressions_gmodules (expression_command/top-level/TestTopLevelExprs.py)
UNEXPECTED SUCCESS: test_with_dsym (expression_command/persist_objc_pointeetype/TestPersistObjCPointeeType.py)
UNEXPECTED SUCCESS: test_with_dwarf (expression_command/persist_objc_pointeetype/TestPersistObjCPointeeType.py)
UNEXPECTED SUCCESS: test_with_gmodules (expression_command/persist_objc_pointeetype/TestPersistObjCPointeeType.py)
UNEXPECTED SUCCESS: test_with_python_api_dsym (macosx/safe-to-func-call/TestSafeFuncCalls.py)
UNEXPECTED SUCCESS: test_with_python_api_dsym (macosx/queues/TestQueues.py)
UNEXPECTED SUCCESS: test_with_python_api_dwarf (macosx/safe-to-func-call/TestSafeFuncCalls.py)
UNEXPECTED SUCCESS: test_with_python_api_dwarf (macosx/queues/TestQueues.py)
UNEXPECTED SUCCESS: test_with_python_api_gmodules (macosx/queues/TestQueues.py)
UNEXPECTED SUCCESS: test_with_python_api_gmodules (macosx/safe-to-func-call/TestSafeFuncCalls.py)
UNEXPECTED SUCCESS: test_with_run_command_dsym (functionalities/data-formatter/data-formatter-stl/libcxx/list/TestDataFormatterLibcxxList.py)
UNEXPECTED SUCCESS: test_with_run_command_dsym (functionalities/signal/TestSendSignal.py)
UNEXPECTED SUCCESS: test_with_run_command_dwarf (functionalities/signal/TestSendSignal.py)
UNEXPECTED SUCCESS: test_with_run_command_dwarf (functionalities/data-formatter/data-formatter-stl/libcxx/list/TestDataFormatterLibcxxList.py)
UNEXPECTED SUCCESS: test_with_run_command_gmodules (functionalities/data-formatter/data-formatter-stl/libcxx/list/TestDataFormatterLibcxxList.py)
UNEXPECTED SUCCESS: test_with_run_command_gmodules (functionalities/signal/TestSendSignal.py)

===================
Test Result Summary
===================
Test Methods:       2770
Reruns:               15
Success:            2248
Expected Failure:    136
Failure:               0
Error:                15
Exceptional Exit:      0
Unexpected Success:   81
Skip:                290
Timeout:               0
Expected Timeout:      0
```

**Comment by CodaFi** [comment]
I'm not sure about the tests, but that it builds is a positive sign WRT this patch.

**Comment by dduan** [comment]
swiftpm changes: https://github.com/apple/swift-package-manager/pull/581

**Comment by CodaFi** [comment]
And a quick rebase please.

**Comment by dduan** [comment]
@CodaFi I tried to test playground logger with `build.py` but it complains that it foundation is missing. What's the proper way to test it against my swift branch?

**Comment by dduan** [comment]
@CodaFi rebased

**Comment by CodaFi** [comment]
```bash
./swift/utils/build-script --playgroundlogger <FURTHER-OPTIONS>
```

Should do it.

**Comment by dduan** [comment]
@CodaFi Thanks! playgroundlogger is in good shape. No change needed.

**Comment by DougGregor** [comment]
The Swift changes look fantastic; thanks for pushing this through!

**Comment by dduan** [comment]
Here's lldb test results ran on master. I think the unexpected success is part of the deal (except the count is different?)
```
Test Methods:       2770
Reruns:               15
Success:            2278
Expected Failure:    133
Failure:               0
Error:                15
Exceptional Exit:      0
Unexpected Success:   84
Skip:                260
Timeout:               0
Expected Timeout:      0
```

**Comment by CodaFi** [comment]
You don't have to worry about that here.  What I meant was more that there are test cases inside LLDB that run swift code that may need migration.  But if the suite builds without hard compiler errors then your job is done.

**Comment by CodaFi** [comment]
@swift-ci please smoke test.

**Comment by DougGregor** [comment]
@swift-ci please smoke test OS X

**Comment by DougGregor** [comment]
the ErrorProtocol issue is something I need to investigate; re-running tests.

**Comment by gottesmm** [comment]
@DougGregor Can you disable that test using a requires while you investigate?

**Comment by DougGregor** [comment]
This caused a pretty serious regression. We no longer type-check this:

    let a = [(1, 2), (3, 4)]
    a.map { print($0.1) }

**Comment by dduan** [comment]
```
    let a = [(1, 2), (3, 4)]
    a.map { print($1) }
```

would work, no?

**Comment by DougGregor** [comment]
It shouldn't work. The element type is (Int, Int), and we should be passing that as a single argument to the closure, not splatting it out to two arguments.

**Comment by DougGregor** [comment]
It's probably falling into the "second part of SE-0110" that isn't yet implemented. It might be that we simple cannot separate the two parts.

**Comment by dduan** [comment]
I see. Let's revert this then.

**Comment by dduan** [comment]
I'll work on the second part tonight.

**Pull request merged**
