### PR TITLE
[ConstraintSystem] Order `VarDecl`s before other kinds of decls in disjunctions.

### PR DESCRIPTION
**Pull request by hborla**
Order `VarDecl`s before other kinds of declarations because they are effectively favored over functions when the two are in the same overload set. This disjunction order allows `SK_UnappliedFunction` to prune later overload choices that are functions when a solution has already been found with a property, which enables solving code like this quickly:

```swift
func f(
  a: String?,
  b: String?,
  c: Int,
  d: String?,
  e: String?
) -> Int {
  return (a?.unicodeScalars.count ?? 0) +
  (b?.unicodeScalars.count ?? 0) +
  c +
  (d?.unicodeScalars.count ?? 0) +
  (e?.unicodeScalars.count ?? 0)
}
```

This resolves the source compatibility regression in penny-bot.

Resolves: rdar://125674969

### CODE REVIEW

**Comment by hborla** [comment]
@swift-ci please test source compatibility

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by hborla** [comment]
My added test failed because I added it to a file that overloads `count(where:)`! The source compat failures are a UPASS of RxReactiveObjc, and importantly, penny-bot passed.

**Comment by hborla** [comment]
@swift-ci please smoke test

**Review by xedin — APPROVED** [review]
:shipit:

**Comment by rintaro** [comment]
@swift-ci please smoke test macOS

**Comment by rintaro** [comment]
(The failure looked unrelated `lldb-api :: lang/swift/embedded/frame_variable/TestSwiftEmbeddedFrameVariable.py`)

**Comment by hborla** [comment]
Same failure again

@swift-ci please smoke test macOS

**Comment by rintaro** [comment]
@swift-ci please smoke test macOS

**Comment by hborla** [comment]
@swift-ci please smoke test macOS

**Pull request merged**
