### PR TITLE
[Sema] Diagnose misplaced InOutExpr in `preCheckExpression`

### PR DESCRIPTION
**Pull request by xedin**
Since there are cases where use of `&` is still allowed e.g. case statement patterns, let's move
diagnostics of extraneous use of `InOutExpr` to `preCheckExpression` where it's much
easier to do so comparing to doing that in parsing, where we'd have to thread a flag through
most of the `parseExpr*` calls to support that case.

Resolves: rdar://problem/40945329
Resolves [SR-7877](https://bugs.swift.org/browse/SR-7877).

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@slavapestov That example is going to be diagnosed by `preCheckExpression` I've added, but there are cases which can't be e.g. allowed one in `test/Parse/pointer_conversion.swift.gyb` line 302 `p == &x` and disallowed in `test/expr/expressions.swift` line 830 `&x += y`, both are related to operators so it doesn't seem we can't just reject it all upfront instead need to double-check after solution is formed...

**Review by rudkx — APPROVED** [review]
LGTM!

**Pull request merged**
