### PR TITLE
Rewrite ClosureScopeAnalysis for generality.

### PR DESCRIPTION
**Pull request by atrick**
Handle recursive non-escaping local functions.

Previously, it was thought that recursion would force a closure to be
escaping. This is not necessarilly true.

Update AccessEnforcementSelection to conservatively handle closure cycles.

Fixes rdar://88726092 (Compiler hangs when building)

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci test source compatibility

**Comment by atrick** [comment]
@swift-ci benchmark

**Comment by atrick** [comment]
@swift-ci test macos

**Comment by atrick** [comment]
@swift-ci test windows

**Comment by atrick** [comment]
All the non-smoke-test targets are failing when updating the git repos

**Comment by atrick** [comment]
I'm planning to merge this later today or tomorrow. As soon as CI is cooperative.

**Comment by atrick** [comment]
@swift-ci test

**Review by eeckstein — APPROVED** [review]
lgtm!

**Comment by atrick** [comment]
@shahmishal I'd like to get this merged asap, but can't figure out why Mac PR testing fails the same way each time as follows:
```
error: branch 'ci_pr_41826' not found.
+ true
[Pipeline] sh
+ git -C /Users/ec2-user/jenkins/workspace/swift-PR-macos-perf/swift branch -D main
error: branch 'main' not found.
```

**Comment by shahmishal** [comment]
> @shahmishal I'd like to get this merged asap, but can't figure out why Mac PR testing fails the same way each time as follows:
> 
> ```
> error: branch 'ci_pr_41826' not found.
> + true
> [Pipeline] sh
> + git -C /Users/ec2-user/jenkins/workspace/swift-PR-macos-perf/swift branch -D main
> error: branch 'main' not found.
> ```

```
 ERROR: can't find CMake (please install CMake)
```

I will look into this right now

**Comment by atrick** [comment]
@shahmishal hope I didn't mess up your investigation by starting a clean build. Here's one of the failure logs: https://ci.swift.org/job/swift-PR-macos-perf/68/console

**Comment by atrick** [comment]
@swift-ci smoke test

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci clean test macOS

**Comment by atrick** [comment]
@swift-ci smoke test

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
Possibly a spurious swifpm failure:
```
swiftpm/Tests/BasicsTests/CancellatorTests.swift:292
:  error: -[BasicsTests.CancellatorTests testFoundationProcessForceKill]
: failed - Found unexpected diagnostics
:  - [warning]: timeout waiting for cancellation with 1 cancellation handlers remainingTest Case '
-[BasicsTests.CancellatorTests testFoundationProcessForceKill]' failed (3.183 seconds).Test Suite 'CancellatorTests' failed at 2022-03-18 10:42:38.770.
- ```

**Comment by atrick** [comment]
@swift-ci smoke test macOS

**Pull request merged**
