### PR TITLE
Remove TFWarnScalarTransfer flag.

### PR DESCRIPTION
**Pull request by bgogul**
As the title says...

### CODE REVIEW

**Comment by bgogul** [comment]
@swift-ci please test tensorflow

**Comment by bgogul** [comment]
It looks like the send_recvs.swift test fails in GPU mode. The fix for that would be to split the GPU portion of send_recvs.swift  test into a separate file, which is not ideal. I am going to drop this PR and we can revisit this later as needed.

**Comment by mhong** [comment]
You can selectively disable GPU tests via:
```swift
#if CUDA	
  return	
#endif
```

If GPU testing is only failing for GPE mode, please still feel free to submit the PR this way.

**Comment by bgogul** [comment]
> You can selectively disable GPU tests via:
> 
> ```swift
> #if CUDA	
>   return	
> #endif
> ```
> 
> If GPU testing is only failing for GPE mode, please still feel free to submit the PR this way.

The test is already guarded by an #if CUDA flag. Unfortunately, using #if does not eliminate with `expected-warning` and `expected-note` checks.

**Comment by dan-zheng** [comment]
I'll close this PR now since [graph program extraction code](https://github.com/apple/swift/pull/24418) has been deleted.

**Pull request closed without merging**
