### PR TITLE
Drop read/write/close LibcShims and use the platform APIs directly from the SwiftPrivate module

### PR DESCRIPTION
**Pull request by kubamracek**
This was attempted before by @mikeash in https://github.com/apple/swift/pull/20194, later reverted in https://github.com/apple/swift/pull/20372. I'd like to try again -- the goal is to avoid depending on read/write/close APIs in libswiftCore.

### CODE REVIEW

**Review by compnerd — COMMENTED** [review]
I really like this change, but one minor question, is the renaming of `read`, `write`, `close` required for something or can we just use the regular libc names?

**Review by mikeash — APPROVED** [review]
Do you know if the problem that prompted https://github.com/apple/swift/pull/20372 is resolved, or is this part of finding out?

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by al45tair — APPROVED** [review]

**Comment by kubamracek** [comment]
> Do you know if the problem that prompted #20372 is resolved, or is this part of finding out?

This is part of figuring that out, yes :)

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by kubamracek** [comment]
@swift-ci please test macOS platform

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by kubamracek** [comment]
Note that I have now reproduced the scenario that led to the revert last time (https://github.com/apple/swift/pull/20372, rdar://problem/45817565) and the build failure no longer occurs -- I believe this is due some recent work by Eric. So let's go forward with this change!

**Comment by kubamracek** [comment]
> I really like this change, but one minor question, is the renaming of read, write, close required for something or can we just use the regular libc names?

I did the "rename" to avoid the name clash with methods called read/write/close on the structs defined in IO.swift. This felt like a less invasive solution compared to renaming of the methods, but I can easily do it the other way if you'd prefer that.

**Comment by compnerd** [comment]
I assume that the "do it the other way" is mostly a typealias in the appropriate section or explicitly naming references to calls to the internal function.  I think that is kinda nicer, but I'm not too concerned either way.  To a certain extent it is about style, and I'm not convinced that this particular bit of style impacts much.

**Comment by kubamracek** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Pull request merged**
