### PR TITLE
Don't return nil from URL(string: "", relativeTo: someURL)

### PR DESCRIPTION
**Pull request by lilyball**
#### What's in this pull request?

`NSURL` allows for creating relative URLs where the relative part is the
empty string, as long as there is some base URL. We should match that
behavior.

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

A smoke test on macOS does the following:
1. Builds the compiler incrementally.
2. Builds the standard library only for macOS. Simulator standard libraries and
   device standard libraries are not built.
3. lldb is not built.
4. The test and validation-test targets are run only for macOS. The optimized
   version of these tests are not run.

A smoke test on Linux does the following:
1. Builds the compiler incrementally.
2. Builds the standard library incrementally.
3. lldb is built incrementally.
4. The swift test and validation-test targets are run. The optimized version of these
   tests are not run.
5. lldb is tested.

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by kballard** [comment]
@parkera I believe you introduced the current behavior.

**Comment by parkera** [comment]
I need to double check on this behavior but I'm out of office right now. Please don't merge yet.

**Comment by kballard** [comment]
Someone just pointed out to me that `NSURL(string: "")` also returns non-`nil` but `URL(string: "")` returns `nil`.

**Comment by kballard** [comment]
Also if returning non-`nil` causes problems with `URL`, then you'll presumably get the same issues with `NSURL(string: "") as URL`. So we should probably support `NSURL(string: "")` as well and just make sure `URL` can handle an empty string.

**Comment by parkera** [comment]
We specifically wanted to disable this behavior of creating NSURL with an empty string. It doesn't make any sense and it leads to confusing behavior for the path related methods.

I'm not sure about the case where we have a base URL.

**Comment by kballard** [comment]
We're automatically migrating people's code from `NSURL` to `URL`, and a behavior change like this can cause silent breakage. I only found this problem because it caused one of my unit tests to fail. I agree that it's kind of nonsense to have a `URL` whose value is the empty string, but it is existing behavior, and as I already pointed out, since you can cast `NSURL` to `URL`, you can create a `URL` that represents an empty string anyway.

All that said, rejecting `URL(string: "")` is probably going to break much less code than rejecting `NSURL(string: "", relativeTo: someURL)`.

**Comment by parkera** [comment]
Sometimes we use SDK upgrades as a way to change behavior of framework code (a.k.a. 'linked on or after' check). We chose to do a similar thing here for struct URL. We don't want empty string struct URL to exist.

I did try your `NSURL(string: "") as URL` and we do end up with an empty-path struct URL. That's a bug I would actually like to fix (probably by making the conditional cast return nil and the force cast use ".", like `init(fileURLWithPath:)` does).

**Comment by kballard** [comment]
After thinking about it, I'm comfortable with `URL(string: "")` and `URL(string: "", relativeTo: nil)` returning `nil`, on the basis that an empty URL is pretty useless and it's not likely to break code. But `URL(string: "", relativeTo: someURL)` is definitely useful.

As for casting `NSURL(string: "") as URL`, I'm confused about what you mean about an "empty-path struct URL". Surely you don't mean that `path == ""` because that's perfectly valid. Using `"."` as the path for an empty file URL seems like reasonable behavior, but it doesn't make much sense for non-file URLs because `"."` doesn't necessarily mean "the current location" for anything else. And of course since it's perfectly reasonable to have `path == ""` for non-file URLs, I just don't see the point.

**Comment by kballard** [comment]
Bump

**Comment by parkera** [comment]
I talked about this with some people and the current consensus seems to be that an empty URL is (potentially) legitimate but an empty file URL is not. I'm not sure it's worth a discrepancy in behavior, but I'll take it under consideration for a future update of Swift.

**Comment by kballard** [comment]
Even for the case where the URL has a base URL?

**Comment by CodaFi** [comment]
Just to see what happens

@swift-ci please smoke test

**Comment by CodaFi** [comment]
@parkera Do you still think it's worthwhile to keep this one and the other URL initializer pull request open then?

**Comment by CodaFi** [comment]
Alrighty then.  Closing this out.  If you wish to revisit this discussion, I recommend bringing it up in swift-dev.

**Pull request closed without merging**
