### PR TITLE
Make MinSizeRel builds produce debug info

### PR DESCRIPTION
**Pull request by kubamracek**
MinSizeRel in CMake doesn't produce debug info by default, and there's no such thing as MinSizeRelWithDebInfo... So let's just make MinSizeRel produce debug info.

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test stdlib with toolchain

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test stdlib with toolchain

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test stdlib with toolchain

**Review by compnerd — APPROVED** [review]
I don't like that we are changing the semantics of the defaults, _but_ this is probably almost always what you want.

**Pull request merged**
