### PR TITLE
[Constraint solver] Filter out more overloads with argument labels that don't match

### PR DESCRIPTION
**Pull request by DougGregor**
The constraint solver has long had a mechanism for filtering out overloads for which the argument labels don't line up. However, it was only applied for member functions and initializers, and even there it wasn't applied uniformly. Extend this filtering to cover more cases:

* Match argument labels for subscript expressions (e.g., `a[foo: x]`), so subscript declarations with incompatible argument labels / # of parameters won't be considered.
* Only add the key path application "overload" if the expression is of the form `a[keyPath: b]`.
* Match argument labels for unresolved member lookups (e.g., `.init(value: b)`)
* Match argument labels for non-member overload sets (e.g., `someGlobalFunc(a)`)

While here, add some simple statistics we can look at to see how well these "early" argument label checks  do at reducing the number of terms in disjunctions that the constraint solver had to churn through.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please test compiler performance

**Comment by DougGregor** [comment]
Looks like something shifted on master; I'll update the tests appropriately once the other testing has completed.

**Review by xedin — CHANGES_REQUESTED** [review]
Failing tests are related to improvements made by https://github.com/apple/swift/pull/22797 (specially the one where `ascii:` label is suggested), presence of the overloads with incorrect labels in vital for diagnostics!

I think `areConservativelyCompatibleArgumentLabels` should be removed from lookup altogether because this verification should be done (and is done) by the solver, and it doesn't cause any performance problems because label matching is the first thing which gets checked, so even though the overload might exist in the disjunction we don't really explore its sub-paths beyond `applicable function` constraint which gets simplified right after member type variable is bound.

**Comment by DougGregor** [comment]
Earlier elimination of potential overloads based on argument label gets rid of the disjunction entirely in cases where there is no type-based overloading (only overloading based on argument labels or arity), allowing the constraint solver to break up the problem more immediately. It also allows any techniques that abstract over the common structure of overload sets to work better, because the remaining overloads are more likely to have a common structure. Most of the "common structure of overload sets" optimizations are limited to `CSGen.cpp` right now (e.g., see https://github.com/apple/swift/blob/master/lib/Sema/CSGen.cpp#L2526-L2575, which tries to find a common return type among the overloads), but applying these techniques more generally during solving should expose more connected components as the solver progresses. For example, https://github.com/apple/swift/pull/22858 tries to pull out common structure among the overload set at the time we form the disjunction, so instead of getting `$T0 bind overload decl1 or $T0 bind overload decl2` we can get something like `($T0, $T0) -> Bool bind overload decl1 or ($T0, $T0) -> Bool bind overload decl2`.

I should have included a more clear scale test for (e.g.) subscripts overloaded on arity to see where this matters. And we do need a solution for diagnostics here, possibly something that adds back the overloads dropped by `areConservativelyCompatibleArgumentLabels`.

**Comment by xedin** [comment]
@DougGregor I think you would agree that the presence of disjunctions itself is not a problem, the problem is related to how each attempted overload is solved (or processed), we already do pretty good job with concrete types - each argument and result type would get its own independent sub-component, but not the generic ones, because generic parameter type would be "opened" into a type variable and newly created `argument conversion` constraints would not spit the system,  especially in operator cases where signature is usually `(Self, Self)`. I think that's the the problem we need to try and solve.

The problem I have is this kind of optimizations (including "common result type" one) impedes diagnostics at no real performance gain for the cases that are still really bad - generics. Overload choices with incorrect labels are already filtered out efficiently when `applicable function` constraint is resolved, so solver wouldn't cover any sub-space besides binding the overload itself.

**Comment by DougGregor** [comment]
Earlier filtering aids some optimizations that currently happen early on, e.g., during constraint generation. If we were to move such optimizations later on (e.g., during solving), then disjunctions could behave the same way as early filtering. However, it is a lot of code to move.

**Comment by xedin** [comment]
I think that's the most viable approach.

**Comment by DougGregor** [comment]
Most of this is subsumed by https://github.com/apple/swift/pull/23012

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
