### PR TITLE
[docs] Streamable => TextOutputStreamable, NFC

### PR DESCRIPTION
**Pull request by benrimmington**
[SE-0137](https://github.com/apple/swift-evolution/blob/master/proposals/0137-avoiding-lock-in.md) is renaming `Streamable` to `TextOutputStreamable`.

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please smoke test OS X platform

**Comment by tkremenek** [comment]
@swift-ci test linux

**Comment by tkremenek** [comment]
@swift-ci test linux

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci please smoke test Linux platform.

**Comment by CodaFi** [comment]
@dabrahams Is this good to merge.

**Pull request merged**
