### PR TITLE
Platform: correct link dependency for WinSDK.User

### PR DESCRIPTION
**Pull request by compnerd**
Add the User32 link dependency for uses of the User module.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
CC: @egorzhdan

**Review by egorzhdan — APPROVED** [review]
Looks good!

**Comment by compnerd** [comment]
@swift-ci please smoke test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Pull request merged**
