### PR TITLE
[test] Limit temporary allocation IRGen test to x86_64 to unblock bots

### PR DESCRIPTION
**Pull request by xwu**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves #NNNNN, fix apple/llvm-project#MMMMM.

### CODE REVIEW

**Comment by xwu** [comment]
cc @shahmishal @grynspan @stephentyrone

**Comment by xwu** [comment]
@swift-ci test

**Comment by stephentyrone** [comment]
If it's only the very-large-buffer check, I think I'd prefer to remove that (brittle) test instead of disabling all the checks for non-x86.

**Comment by beccadax** [comment]
Force-merging to unblock CI bots.

**Comment by xwu** [comment]
> If it's only the very-large-buffer check, I think I'd prefer to remove that (brittle) test instead of disabling all the checks for non-x86.

@stephentyrone I will follow up to remove the test, and then noodle with it to add it back in a separate file.

Hoping @shahmishal can help guide how to actually _test_ that it doesn't mess anything up again with Ubuntu on aarch64 as it appears that even a full test run doesn't do it.

**Pull request merged**
