### PR TITLE
Self parameters can be @_noImplicitCopy or @_eagerMove.

### PR DESCRIPTION
**Pull request by nate-chandler**
Expand the support for annotating parameters `@_noImplicitCopy` and `@_eagerMove` to include the implicit `self` parameter of methods.  Spell this as an annotation on the method itself.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test macOS platform

**Review by atrick — APPROVED** [review]
Thanks!

**Comment by nate-chandler** [comment]
@swift-ci please test windows platform

**Pull request merged**
