### PR TITLE
Enable lifetime dependence diagnostics for Nonescapable types.

### PR DESCRIPTION
**Pull request by atrick**
Adds -Xfrontend -disable-lifetime-dependence-diagnostics.

Removes -Xllvm -enable-lifetime-dependence-insertion

Removes -Xllvm -enable-lifetime-dependence-diagnostics

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci smoke test

**Review by meg-gupta — APPROVED** [review]
Yay! LGTM!

**Pull request merged**
