### PR TITLE
[runtime] Clean up symbols in error machinery.

### PR DESCRIPTION
**Pull request by gparker42**

### CODE REVIEW

**Comment by gparker42** [comment]
@swift-ci please test

**Comment by gparker42** [comment]
@swift-ci please test

**Comment by gparker42** [comment]
@swift-ci please test

**Comment by gparker42** [comment]
please test with the following pull request:
https://github.com/apple/swift-corelibs-foundation/pull/1318

@swift-ci please smoke test linux

**Comment by shahmishal** [comment]
ci.swift.org is down for update, I will re-trigger this PR once update has been completed.

**Comment by shahmishal** [comment]
please test with the following pull request:
apple/swift-corelibs-foundation#1318

@swift-ci please smoke test linux

**Comment by shahmishal** [comment]
@swift-ci please test macOS

**Comment by shahmishal** [comment]
@swift-ci please test Linux

**Comment by shahmishal** [comment]
please test with the following pull request:
apple/swift-corelibs-foundation#1318

@swift-ci please test

**Comment by gparker42** [comment]
please test with the following pull request:
apple/swift-corelibs-foundation#1318

@swift-ci please smoke test linux

**Comment by gparker42** [comment]
please test with the following pull request:
apple/swift-corelibs-foundation#1318

@swift-ci please smoke test linux

**Comment by gparker42** [comment]
please test with the following pull request:
apple/swift-corelibs-foundation#1318

@swift-ci please test

**Comment by gparker42** [comment]
please test with the following pull request:
apple/swift-corelibs-foundation#1318

@swift-ci please test

**Comment by gparker42** [comment]
please test with the following pull request:
apple/swift-corelibs-foundation#1318

@swift-ci please test linux

**Comment by gparker42** [comment]
please test with the following pull request:
apple/swift-corelibs-foundation#1318

@swift-ci please test

**Pull request merged**
