### PR TITLE
[Syntax] Remove LegacyASTTransformer

### PR DESCRIPTION
**Pull request by harlanhaskins**
As it is no longer ever instantiated except in swift-syntax-test, and since Syntax nodes are being
plumbed through the parser, the `LegacyASTTransformer` no longer needs to
exist.

Note: These tests will fail until I can run them locally and update the expected outputs.

### CODE REVIEW

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
The best PRs are negative-line-count PRs.

**Review by nkcsgexi — APPROVED** [review]
Nice! Thank you, Harlan!

**Comment by harlanhaskins** [comment]
@swift-ci please test and merge

**Comment by harlanhaskins** [comment]
@swift-ci please test and merge

**Pull request merged**
