### PR TITLE
SILOptimizer: Replace [].append(contentsOf:) with [].append(element:)

### PR DESCRIPTION
**Pull request by eeckstein**
if the argument is an array literal.

For example:
arr += [1, 2, 3]

is replaced by:
arr.append(1)
arr.append(2)
arr.append(3)

This gives considerable speedups up to 10x (for our micro-benchmarks which test this).

This is based on the work of @ben-ng, who implemented the first version of this optimization (thanks!). The original PR is https://github.com/apple/swift/pull/6652

This PR also contains a commit which adds some clean-up passes before the inliner. This is necessary for this optimization.

<rdar://problem/17750612>

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci Please test

**Comment by eeckstein** [comment]
@swift-ci Please smoke benchmark

**Comment by dabrahams** [comment]
on Fri Mar 31 2017, eeckstein <notifications-AT-github.com> wrote:

> if the argument is an array literal.
>
> For example:
> arr += [1, 2, 3]
>
> is replaced by:
> arr.append(1)
> arr.append(2)
> arr.append(3)
>
> This gives considerable speedups up to 10x (for our micro-benchmarks which test this).

Wow.  It seems very counter-intuitive to me, though.  Shouldn't we be
generating an array literal like that one in memory?

-- 
-Dave

**Comment by eeckstein** [comment]
@swift-ci Please test and merge

**Comment by eeckstein** [comment]
@swift-ci Please test and merge

**Comment by eeckstein** [comment]
> Shouldn't we be generating an array literal like that one in memory?

We do. Still the element-append version is faster.

**Comment by rjmccall** [comment]
I assume we have to allocate a new array object to do it, which is probably most of the overhead.

We could add some low-level interface for appending elements if you think it's worthwhile/maintainable.

**Comment by eeckstein** [comment]
@swift-ci Please smoke test and merge

**Comment by eeckstein** [comment]
@swift-ci Please smoke test and merge

**Comment by dabrahams** [comment]
on Fri Mar 31 2017, John McCall <notifications-AT-github.com> wrote:

> I assume we have to allocate a new array object to do it, which is
> probably most of the overhead.

Calling append allocates new array objects, and it does so over and over
as the capacity is reached.  There's no arguing with the numbers, but
the numbers make no sense to me, so I'm concerned that there's something
very wrong at a deeper level.

> We could add some low-level interface for appending elements if you think it's
> worthwhile/maintainable.

Sorry, I don't follow.  What do you have in mind?

-- 
-Dave

**Comment by ben-ng** [comment]
@eeckstein thank you for getting this across the finish line!

**Comment by eeckstein** [comment]
@dabrahams I see your point. I'll investigate this in detail.
What we could do is call reserveCapacity if multiple element are going to be appended.
Or provide compiler-internal function(s), like append(element1, element2). I think that's what @rjmccall had in mind.

**Pull request merged**
