### PR TITLE
Fix the mid-level function-pass pipeline

### PR DESCRIPTION
**Pull request by meg-gupta**
Reopening #31163 

rdar://62549587

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci benchmark

**Comment by meg-gupta** [comment]
@swift-ci Please Test Source Compatibility

**Comment by meg-gupta** [comment]
@swift-ci test compiler performance

**Comment by meg-gupta** [comment]
@swift-ci test compiler performance

**Comment by meg-gupta** [comment]
@swift-ci benchmark

**Comment by meg-gupta** [comment]
Having module passes in between function passes in the pipeline had an unexpected side-effect. It forced recomputation of BottomUpFunctionOrder. When I converted EagerSpecializer to a function pass, we lost this unintended side effect and saw some regression, which was fixed by #30710 . #30710 has regressions of its own. So I am going to fix EagerSpecializer separately.

**Review by atrick — APPROVED** [review]
@meg-gupta thanks for bringing this PR back to life after over a year and getting it checked in!

**Comment by meg-gupta** [comment]
@swift-ci test compiler performance

**Pull request merged**
