### PR TITLE
Number bridge updates

### PR DESCRIPTION
**Pull request by phausler**
This adds deprecation migration notes for numeric types like Int, Int32, Float etc from NSNumbers so that developers can easily migrate to better interfaces for constructing numeric values from NSNumbers.

This also relaxes the bridging of Floating point values so that NSNumber -> Float does not lead to unexpected behavior. 

This resolves the following issues:
<rdar://problem/32633511>
<rdar://problem/32739894> (and a number of other related issues that will be updated later)
https://bugs.swift.org/browse/SR-5179

### CODE REVIEW

**Comment by phausler** [comment]
@swift-ci please test

**Comment by phausler** [comment]
@swift-ci please test

**Comment by najacque** [comment]
@swift-ci please test

**Comment by najacque** [comment]
Ok, now that master is fixed...
@swift-ci please test

**Comment by najacque** [comment]
We had breakage on master. Should be fixed now... Let's try this again.
@swift-ci please test

**Comment by phausler** [comment]
@swift-ci please test

**Comment by phausler** [comment]
@swift-ci please clean test

**Comment by phausler** [comment]
@swift-ci please test macos

**Pull request merged**
