### PR TITLE
Class resilience part 11

### PR DESCRIPTION
**Pull request by slavapestov**
Some code review feedback from @rjmccall (but not everything -- still working on it), as well as a fix for a problem with method overrides that I missed during testing when constant-folding `-enable-class-resilience` to true.

### CODE REVIEW

**Comment by slavapestov** [comment]
Some code review feedback from @rjmccall (but not everything -- still working on it), as well as a fix for a problem with method overrides that I missed during testing when constant-folding `-enable-class-resilience` to true.

**Review by rjmccall — APPROVED** [review]
LGTM.

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
Source compat failure is fixed in https://github.com/apple/swift/pull/13711.

**Pull request merged**
