### PR TITLE
[Migrator] Clear LLVM global state before argument setup.

### PR DESCRIPTION
**Pull request by varungandhi-apple**
Fixes rdar://78576743 (CI issue).

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
@swift-ci smoke test

**Review by etcwilde — CHANGES_REQUESTED** [review]
The change looks good to me.
Can we add an offending test case?

**Comment by varungandhi-apple** [comment]
The test `Migrator/no_duplicate_aarch64_use_tbi.swift` is failing right now but it should pass with this change. Is that good enough or are you suggesting I should add a separate test case?

**Review by etcwilde — APPROVED** [review]
Yeah, I think that works for me. I wonder if it would make sense to clear out the LLVM globals any time you build a new compiler instance?

**Comment by varungandhi-apple** [comment]
I've filed https://bugs.swift.org/browse/SR-14673 to track that improvement idea.

**Pull request merged**
