### PR TITLE
SILGen: Partial applications of methods don't lie about their nonnull-ness.

### PR DESCRIPTION
**Pull request by jckarter**
Fixes rdar://problem/26210805.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test and merge

**Comment by jckarter** [comment]
@stephentyrone @gribozavr Any chance this failure is related to your floating-point work?

```
******************** TEST 'Swift :: stdlib/FixedPointDiagnostics.swift.gyb' FAILED ********************
Script:
--
rm -rf /home/buildnode/jenkins/workspace/swift-PR-Linux/buildbot_linux/swift-linux-x86_64/validation-test-linux-x86_64/stdlib/Output/FixedPointDiagnostics.swift.gyb.tmp && mkdir -p /home/buildnode/jenkins/workspace/swift-PR-Linux/buildbot_linux/swift-linux-x86_64/validation-test-linux-x86_64/stdlib/Output/FixedPointDiagnostics.swift.gyb.tmp && /home/buildnode/jenkins/workspace/swift-PR-Linux/swift/validation-test/stdlib/../../utils/gyb /home/buildnode/jenkins/workspace/swift-PR-Linux/swift/validation-test/stdlib/FixedPointDiagnostics.swift.gyb -o /home/buildnode/jenkins/workspace/swift-PR-Linux/buildbot_linux/swift-linux-x86_64/validation-test-linux-x86_64/stdlib/Output/FixedPointDiagnostics.swift.gyb.tmp/main.swift
/home/buildnode/jenkins/workspace/swift-PR-Linux/swift/validation-test/stdlib/../../utils/line-directive /home/buildnode/jenkins/workspace/swift-PR-Linux/buildbot_linux/swift-linux-x86_64/validation-test-linux-x86_64/stdlib/Output/FixedPointDiagnostics.swift.gyb.tmp/main.swift -- /home/buildnode/jenkins/workspace/swift-PR-Linux/buildbot_linux/swift-linux-x86_64/bin/swift -frontend -target x86_64-unknown-linux-gnu  -parse -verify /home/buildnode/jenkins/workspace/swift-PR-Linux/buildbot_linux/swift-linux-x86_64/validation-test-linux-x86_64/stdlib/Output/FixedPointDiagnostics.swift.gyb.tmp/main.swift
--
Exit Code: 1

Command Output (stdout):
--
/home/buildnode/jenkins/workspace/swift-PR-Linux/swift/validation-test/stdlib/FixedPointDiagnostics.swift.gyb:106:8: error: unexpected note produced: expected an argument list of type '(Int, Int)'
    (x + x) as Stride   // expected-error {{}} // not convertible to 'Stride'
       ^
/home/buildnode/jenkins/workspace/swift-PR-Linux/swift/validation-test/stdlib/FixedPointDiagnostics.swift.gyb:106:8: error: unexpected note produced: expected an argument list of type '(Int, Int)'
    (x + x) as Stride   // expected-error {{}} // not convertible to 'Stride'
       ^
/home/buildnode/jenkins/workspace/swift-PR-Linux/swift/validation-test/stdlib/FixedPointDiagnostics.swift.gyb:106:8: error: unexpected note produced: expected an argument list of type '(Int, Int)'
    (x + x) as Stride   // expected-error {{}} // not convertible to 'Stride'
       ^
/home/buildnode/jenkins/workspace/swift-PR-Linux/swift/validation-test/stdlib/FixedPointDiagnostics.swift.gyb:106:8: error: unexpected note produced: expected an argument list of type '(Int, Int)'
    (x + x) as Stride   // expected-error {{}} // not convertible to 'Stride'
       ^
/home/buildnode/jenkins/workspace/swift-PR-Linux/swift/validation-test/stdlib/FixedPointDiagnostics.swift.gyb:106:8: error: unexpected note produced: expected an argument list of type '(Int, Int)'
    (x + x) as Stride   // expected-error {{}} // not convertible to 'Stride'
       ^
```

**Comment by rjmccall** [comment]
> On May 11, 2016, at 5:55 PM, Joe Groff <notifications@github.com> wrote:
> @stephentyrone <https://github.com/stephentyrone> @gribozavr <https://github.com/gribozavr> Any chance this failure is related to your floating-point work?
> 

This was me.  Ted reverted my patch and I re-committed with a fix; are you still seeing the failure?

John.

**Comment by jckarter** [comment]
@rjmccall No, I probably just started CI at the wrong time. Thanks.

**Pull request merged**
