### PR TITLE
[Build] Use host generator tools when cross-compiling

### PR DESCRIPTION
**Pull request by bnbarham**

### CODE REVIEW

**Comment by haoNoQ** [comment]
This, uhh, makes sense! Thanks a lot for looking into this!

It probably makes sense to put this straight into `next`?

**Comment by bnbarham** [comment]
@swift-ci build toolchain

**Comment by bnbarham** [comment]
>This, uhh, makes sense! Thanks a lot for looking into this!
> 
> It probably makes sense to put this straight into next?

This is `swift` rather than `llvm-project` and the branches are a little different. We don't really build `next` at all 😅. `rebranch` will be merged into `main` which will then be merged into `next`. So... it'll get there eventually (and there's lots of other fixes where that's the case).

**Comment by haoNoQ** [comment]
Oh ok gotcha!

**Comment by bnbarham** [comment]
@swift-ci build toolchain

**Review by drexin — COMMENTED** [review]
LGTM

**Review by compnerd — APPROVED** [review]

**Pull request merged**
