### PR TITLE
Improve symbolication of stacktraces on Linux.

### PR DESCRIPTION
**Pull request by gmilos**
The symbolication script now:

* Finds lldb site-package relative to swift executable (so it'll work without explicit `PYTHONPATH`)
* Caches lldb target for better performance
* Defaults to stdin as the log source

### CODE REVIEW

**Comment by alblue** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please python lint

**Comment by alblue** [comment]
@swift-ci please smoke test

**Comment by gmilos** [comment]
Fixing here:
https://github.com/apple/swift/pull/10244

Not sure why this is not picked up in my local lint.

**Pull request merged**
