### PR TITLE
Backport some fixes for C++ interop tests on 5.4

### PR DESCRIPTION
**Pull request by compnerd**
Backport some changes from main, which should repair the tests for the 5.4 release branch.  This should allow us to get the CI into a green state on Windows as well.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
CC: @gottesmm @zoecarver

**Comment by airspeedswift** [comment]
Hi @compnerd - can you fill out the PR description please?

**Comment by compnerd** [comment]
@airspeedswift, sure, done :)  I wanted to make sure that the full set of fixes were incorporated first is all.

**Comment by compnerd** [comment]
@swift-ci please test

**Review by zoecarver — APPROVED** [review]
This LGTM. Thanks!!

**Comment by shahmishal** [comment]
```
Swift(linux-x86_64).Interop/Cxx/static.constexpr-static-member-var.swift
Swift(macosx-x86_64).Interop/Cxx/static.constexpr-static-member-var.swift
```
@compnerd @zoecarver Are we still missing change from main branch?

**Comment by compnerd** [comment]
@shahmishal - its actually that I grabbed an extra change, just need to drop 52490b1f5506e58f2162391f67739e251f4459aa.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Seems like an unrelated flake on the Linux side.

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Pull request merged**
