### PR TITLE
swift-api-digester: refactor a chained if to a switch statement. NFC

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci Please smoke test and merge

**Comment by nkcsgexi** [comment]
@swift-ci Please smoke test and merge

**Comment by dabrahams** [comment]
@swift-ci Please smoke test Linux platform

**Comment by nkcsgexi** [comment]
@swift-ci Please smoke test and merge

**Pull request merged**
