### PR TITLE
FIx an overrelease in StdlibUnittest's getSystemVersionPlistProperty

### PR DESCRIPTION
**Pull request by porglezomp**
The `getSystemVersionPlistProperty` overreleases objects if certain `StdlibUnittest` initialization happens inside an autoreleasepool. Just picking two lines from the function:
```objective-c
NSString *PropertyNameString = [NSString stringWithUTF8String:PropertyName];
// …
[PropertyNameString release];
```
the `+stringWithUTF8String:` method returns an autoreleased object, so explicitly releasing it is an overrelease.

## Steps To Reproduce
Write a `StdlibUnittest` file that has at least one `.xfail` or `.skip`, and that calls `runAllTests()` from inside an autoreleasepool block. The test included with the PR crashed with a SIGILL before, and passes now.

Fixes rdar://51245681

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci smoke test

**Comment by porglezomp** [comment]
I'm not sure if I put the test in the right place. The other `StdlibUnittest` tests are in `validation-tests/`, but this is a regression test.

CC @Catfish-Man

**Comment by porglezomp** [comment]
I'll fix the Linux failure by adding `REQUIRES: foundation`, I'm not sure what the cause of the OS X failure is.

**Comment by shahmishal** [comment]
@swift-ci smoke test

**Comment by shahmishal** [comment]
@swift-ci Python lint

**Comment by shahmishal** [comment]
@swift-ci Python lint

**Comment by shahmishal** [comment]
@swift-ci smoke test

**Comment by shahmishal** [comment]
@swift-ci Python lint

**Pull request merged**
