### PR TITLE
Remove `TestDecimal.swift`

### PR DESCRIPTION
**Pull request by edymtt**
Addresses rdar://61160009

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci please smoke test

**Comment by edymtt** [comment]
(This would be another preparatory step to remove the obsolete overlay code in this repository, similar to #37702)

**Review by lorentey — APPROVED** [review]
👍

**Comment by varungandhi-apple** [comment]
+0 -632: The perfect PR. 😄

**Comment by edymtt** [comment]
@swift-ci please smoke test Linux

**Pull request merged**
