### PR TITLE
[stdlib] Move unused functions to LegacyABI.swift

### PR DESCRIPTION
**Pull request by benrimmington**

### CODE REVIEW

**Comment by benrimmington** [comment]
@swift-ci Please smoke test

**Comment by benrimmington** [comment]
@swift-ci Please smoke test

**Comment by benrimmington** [comment]
<https://ci.swift.org/job/swift-PR-macos-smoke-test/14674/>

> Failed Tests (1):
>   Swift(macosx-x86_64) :: api-digester/stability-stdlib-abi-with-asserts.test

```diff
+Func _unsafeMinus(_:_:) has been removed
+Func _unsafePlus(_:_:) has been removed
+Func unimplemented_utf8_32bit(_:file:line:) has been removed
```

#33694 (ModuleAnalyzerNodes.cpp) is required, to include obsoleted/unavailable declarations in the ABI baseline.

**Comment by benrimmington** [comment]
@swift-ci Please smoke test

**Review by glessard — APPROVED** [review]

**Pull request merged**
