### PR TITLE
[Demangler] Further optimizations for the remangler.

### PR DESCRIPTION
**Pull request by al45tair**
Replace use of `snprintf()` with some custom code (this is around 10x faster on my machine).

Move a few of the `Node` member functions to the header so they're inlined.

Optimize the `deepEquals()` function by adding an `isSimilarTo()` method on `Node`; the checks that were happening in the `deepEquals()` function could be implemented more efficiently by making use of details of the internal representation of `Node`.

rdar://125739630

### CODE REVIEW

**Comment by al45tair** [comment]
**Explanation**: These are needed to help offset the effects of the prespecialized metadata support, which has put the remangler into a performance critical path it wasn't previously in.
**Original PR**: #72884
**Reviewed by**: @mikeash 
**Risk**: Low. This is mostly rearrangement of existing code, and there is a good suite of tests for the de/remangler.
**Resolves**: rdar://125989715
**Tests**: The demangling and remangling tests exercise all of this code.

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
@swift-ci Please test macOS platform

**Review by tbkka — APPROVED** [review]

**Comment by al45tair** [comment]
@swift-ci Please test macOS platform

**Comment by al45tair** [comment]
@swift-ci Please test

**Pull request merged**
