### PR TITLE
[Sema] Implement @_nonEphemeral

### PR DESCRIPTION
**Pull request by hamishknight**
This PR contains a subset of the changes in #27695, specifically just the implementation for the `@_nonEphemeral` attribute and the diagnosis of invalid temporary pointers conversions passed to it.

This includes all array-to-pointer and string-to-pointer conversions, and most inout-to-pointer conversions with the exception of:

- Global and static variables
- Stored properties on such variables that are accessed directly (e.g excluding ones with property observers, ones on classes, protocols, and resilient types in general)
- Force unwraps of any of the above

If landed, this will leave #27695 with just the changes required to start producing warnings in user code (by annotating the standard library + inferring the attribute in various places).

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test Linux platform

**Review by xedin — COMMENTED** [review]
From the type-checker/diagnostics perspective this looks good to me! I'm not really sure whether adding a new underscored attribute is the best way to go about it though.

It's already possible to determine that solver converts some type to a pointer implicitly and that it happened as part of the argument-to-parameter conversion. Maybe I just don't understand what is the intended use of this attribute...

**Comment by hamishknight** [comment]
@xedin Thanks for looking through this! The goal of the attribute is to allow us to selectively mark parameters which shouldn't accept temporary pointer arguments (you can take a look at the last two commits of https://github.com/apple/swift/pull/27695 to see which decls I'm planning on marking).

We still want all other pointer parameters to continue accepting these temporary pointer conversions, as we don't know whether or not such conversions will be unsound (though the implementation of a SIL pass will help catch a bunch of cases there).

**Review by atrick — APPROVED** [review]
I only did a quick scan through this, but it looks like an excellent way to stage in the work.

**Comment by hamishknight** [comment]
Merged as a part of https://github.com/apple/swift/pull/27695.

**Pull request closed without merging**
