### PR TITLE
build: use the just build compiler if available

### PR DESCRIPTION
**Pull request by compnerd**
It is possible to partially build the necessary tools.  Attempt to use
the just-built compiler if available.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @hyp

**Comment by buttaface** [comment]
What does this fix exactly? [`SWIFT_NATIVE_SWIFT_TOOLS_PATH` is already set to the just-built compiler by default](https://github.com/apple/swift/blob/master/CMakeLists.txt#L512), this patch will simply override that even when it isn't.

That will break cross-compiling the Swift compiler and stdlib at one go, ie when the Swift compiler is cross-compiled for a target other than the host and since that cannot be used to cross-compile the stdlib too, [a host compiler for Swift is passed in with `SWIFT_NATIVE_SWIFT_TOOLS_PATH`](https://github.com/apple/swift/blob/d9d929a59454ba9476092e575663cf8f31926918/utils/build-script-impl#L1722). I have been experimenting with using precisely such a build config for cross-compiling the Swift compiler and stdlib to Android.

**Comment by compnerd** [comment]
I'm seeing a build failure with SWIFT_NATIVE_TOOLS_PATH for the translation tools and not the compiler break.  I'm trying to repair that scenario.

**Comment by buttaface** [comment]
I'm not familiar with that scenario: `SWIFT_NATIVE_SWIFT_TOOLS_PATH` is set to the wrong Swift compiler then? This fix is going to break the `--cross-compile-hosts` scenario, when cross-compiling the stdlib with the just-built host compiler.

**Comment by compnerd** [comment]
It’s less that it’s set to the wrong computer, it’s more that there is no compiler (other than the just built one).  The native tools are being used for the internationalization tools only.

**Comment by buttaface** [comment]
Well, if the just-built one is there, why isn't it set by the main CMakeLists.txt, as shown in my first link above, in your scenario?

**Comment by compnerd** [comment]
Because `SWIFT_NATIVE_TOOLS_PATH` is set, and that just checks if the value is equal to "", which it is not, so that branch is never taken.

**Comment by buttaface** [comment]
That sounds like the real problem then, fix where "SWIFT_NATIVE_TOOLS_PATH is set" to a non-existent Swift compiler in your scenario instead. This doesn't seem the right way to correct a bad SWIFT_NATIVE_TOOLS_PATH being passed in, if you're breaking other scenarios doing it.

**Comment by compnerd** [comment]
Perhaps you have a better solution in mind, but the scenario is that the internationalization tools are split out, and the `SWIFT_NATIVE_TOOLS_PATH` is being used to pass those in.  This does need a solution in the short term.  I'm okay with you driving this to a solution if you are interested.

**Comment by buttaface** [comment]
Can you point me at the build-script command or CMake invocation for this main Swift repo that you're trying to fix? I'll take a look.

**Comment by compnerd** [comment]
Its the 5.3 branch btw, and the failure occurs at testing time - not build time.  The build completes, the tests fail due to the "missing" compiler.

Full logs for a recentish run are at https://dev.azure.com/compnerd/swift-build/_build/results?buildId=37997

The CMake invocation for build:
```cmd
"C:\Program Files\CMake\bin\cmake.exe" 
  -B D:\a\1\b/toolchain
  -C D:\a\1\s/swift-build/cmake/caches/toolchain-5.3.cmake
  -C D:\a\1\s/swift-build/cmake/caches/windows-x86_64.cmake
  -C D:\a\1\s/swift-build/cmake/caches/org.compnerd.dt.cmake
  -D CMAKE_BUILD_TYPE=Release
  -D CMAKE_INSTALL_PREFIX=D:\a\1\a/toolchain-windows-x64/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr
  -D LLDB_FRAMEWORK_INSTALL_DIR=D:\a\1\a/toolchain-windows-x64/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/Library/PrivateFrameworks
  -D LLVM_DEFAULT_TARGET_TRIPLE=x86_64-unknown-windows-msvc
  -D LLVM_USE_HOST_TOOLS=NO
  -D LLVM_TABLEGEN=D:\a\1\b\llvm-tools\bin\llvm-tblgen.exe
  -D CLANG_TABLEGEN=D:\a\1\b\llvm-tools\bin\clang-tblgen.exe
  -D LLDB_TABLEGEN=D:\a\1\b\llvm-tools\bin\lldb-tblgen.exe
  -D SWIFT_PATH_TO_LIBDISPATCH_SOURCE=D:\a\1\s/swift-corelibs-libdispatch
  -D SWIFT_NATIVE_SWIFT_TOOLS_PATH=D:\a\1\b/llvm-tools/bin
  -D LLVM_EXTERNAL_SWIFT_SOURCE_DIR=D:\a\1\s/swift
  -D LLVM_EXTERNAL_CMARK_SOURCE_DIR=D:\a\1\s/swift-cmark
  -DLLVM_ENABLE_LIBEDIT=NO
  -DLLVM_PARALLEL_LINK_JOBS=2
  -DPYTHON_EXECUTABLE=C:\hostedtoolcache\windows\Python\2.7.18\x64/python.exe
  -DLLVM_DEFAULT_TARGET_TRIPLE=x86_64-unknown-windows-msvc
  -DSWIFT_WINDOWS_x86_64_ICU_UC_INCLUDE=D:\a\1/icu/icu-windows-x64/Library/icu-67/usr/include/unicode
  -DSWIFT_WINDOWS_x86_64_ICU_UC=D:\a\1/icu/icu-windows-x64/Library/icu-67/usr/lib/icuuc67.lib
  -DSWIFT_WINDOWS_x86_64_ICU_I18N_INCLUDE=D:\a\1/icu/icu-windows-x64/Library/icu-67/usr/include
  -DSWIFT_WINDOWS_x86_64_ICU_I18N=D:\a\1/icu/icu-windows-x64/Library/icu-67/usr/lib/icuin67.lib
  -DSWIFT_PARALLEL_LINK_JOBS=2
  -DSWIFT_BUILD_DYNAMIC_STDLIB=YES
  -DSWIFT_BUILD_DYNAMIC_SDK_OVERLAY=YES
  -G Ninja
  -S D:\a\1\s/llvm-project/llvm
```

The failing invocation for tests:
```cmd
"C:\Program Files\CMake\bin\cmake.exe" --build D:\a\1\b/toolchain --target check-swift
```

With the message:
```
ninja: error: 'D:/a/1/b/llvm-tools/bin/swift.exe', needed by 'tools/swift/test/CMakeFiles/check-swift-windows-x86_64', missing and no known rule to make it
```

I'm not convinced that this change is even correct but it was an initial stab at what I thought it might've been.

**Comment by buttaface** [comment]
Ah, just a typo? I think `SWIFT_NATIVE_SWIFT_TOOLS_PATH=D:\a\1\b/llvm-tools/bin` should be `SWIFT_NATIVE_LLVM_TOOLS_PATH=D:\a\1\b/llvm-tools/bin`.

**Comment by compnerd** [comment]
No, but you're right that is confusing.  The llvm-tools has clang, llvm, lldb, and swift tools in it (llvm-config, llvm-tblgen, clang-tblgen, lldb-tblgen, and swift-serialize-diagnostics).  BTW, the caches aren't interesting, you can swap them with the content in swift/cmake/caches/Windows-x86_64.cmake

**Comment by buttaface** [comment]
OK, but which of those prebuilt tools are you trying to pass in and actually use? If you don't want to use the prebuilt Swift tools in `D:\a\1\b/llvm-tools/bin`, then you can just have it use those prebuilt LLVM tools by setting `SWIFT_NATIVE_LLVM_TOOLS_PATH` instead.

**Comment by compnerd** [comment]
Ah, the prebuilt tools Id like to use in this case are `swift-serialize-diagnostics` (and `swift-def-to-yaml-converter`).

**Comment by buttaface** [comment]
Oh, I see, you want to mix some prebuilt Swift tools in with a fresh build? Such mixing is not supported by the current CMake config though, and this pull isn't the way to fix it.

If you just want to run some tests locally and don't need this to work upstream, my suggestion would be to pass the path in with `SWIFT_NATIVE_LLVM_TOOLS_PATH` and then amend `localization/CMakeLists.txt` to look there for these two tools instead. Another possibility is to not build the stdlib, if you don't need it for your tests.

If you need this working upstream, that's a whole different can of worms.

**Comment by compnerd** [comment]
I think that we might be able to get away with a less than perfect solution though.  Sadly, I do need this working in upstream (since this is meant to be fore the releases).  The test suite currently requires the standard library for the compiler side of the tests even sadly.  I think that the longer term fix is to split up the test suite into two suites so that they can be run independently, but for the immediate term, we need another solution.

One thing that we could do is to ensure that the build and host are the same when using the just built compiler.  But again, Im not 100% certain that this fixes the test suite execution.

**Comment by buttaface** [comment]
Alright, if this is to get Swift 5.3 for Windows released soon, feel free to do whatever you need, including merging this pull. We can always figure out a better solution for the long-term later on, as that will take more work.

**Comment by compnerd** [comment]
I think I know how to fix both the issue that you are worried about and the actual testing at the same time.  I'll upload a new revision in a little bit.

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
