### PR TITLE
AST: Parse `#_hasSymbol`

### PR DESCRIPTION
**Pull request by tshortli**
Introduce the compiler directive `#_hasSymbol` which will be used to detect directly whether weakly linked symbols are present at runtime. It  is intended for use in combination with `@_weakLinked import` or `-weak-link-at-target`.

```
if #_hasSymbol(foo(_:)) {
  foo(42)
}
```

Parsing only; type checking and SILGen will be coming in later commits.

SwiftSyntax parsing has been implemented in https://github.com/apple/swift-syntax/pull/661.
    
Resolves rdar://99342017

### CODE REVIEW

**Comment by tshortli** [comment]
https://github.com/apple/swift-syntax/pull/661

@swift-ci please smoke test

**Comment by tshortli** [comment]
https://github.com/apple/swift-syntax/pull/661

@swift-ci please smoke test

**Comment by tshortli** [comment]
https://github.com/apple/swift-syntax/pull/661

@swift-ci please smoke test

**Comment by tshortli** [comment]
After some research I've concluded that taking a string literal to identify the symbol will not be as simple as I'd imagined. The corresponding decl ref needs to be identified during type checking in order to SILGen the condition. I'm going to rework this to take an expression instead of a string literal.

**Comment by tshortli** [comment]
https://github.com/apple/swift-syntax/pull/661

@swift-ci please smoke test

**Comment by tshortli** [comment]
https://github.com/apple/swift/pull/61001
https://github.com/apple/swift-syntax/pull/661

@swift-ci please smoke test Windows

**Comment by tshortli** [comment]
https://github.com/apple/swift/pull/61001
https://github.com/apple/swift-syntax/pull/661

@swift-ci please smoke test

**Review by xymus — APPROVED** [review]
It looks good!

**Pull request merged**
