### PR TITLE
[AST/Sema] TypeWrappers: Extend implementation to support wrapped type

### PR DESCRIPTION
**Pull request by xedin**
-  Rename type wrapper init parameter to `storage:`
-  Rename type wrapper storage property to `$storage`
- Introduce a `Wrapped` type parameter requirement
- Adjust synthesized type wrapper init calls to pass the wrapped type
- Add `propertyKeyPath` parameter to type wrapper subscripts
  subscripts are going to have both wrapped property and storage references - `propertyKeyPath:storageKeyPath:`
- TypeWrappers: Use special subscript to manage storage of classes
  For wrapped classes allow to declare a special subscript that allows to pass down wrapped type instance.
- Synthesize a body for memberwise initializer lazily to avoid forcing other synthesis
- Synthesize an initializer that accepts a fully constructed wrapper type

Resolves: rdar://99884355

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by meg-gupta** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please test

**Review by hborla — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please clean smoke test macOS platform

**Comment by xedin** [comment]
@swift-ci please clean smoke test Linux platform

**Pull request merged**
