### PR TITLE
[embedded] Allow serialization of SILLinkage::shared functions without promoting them to public

### PR DESCRIPTION
**Pull request by kubamracek**
Currently, CMO's "everything" serialization promotes shared functions (thunks, specializations) to public. This isn't generally a problem, unless an importing module triggers specialization of the the exact same function, in which case we end up tripping the following assert (see the test case demonstrating this):

```
Assertion failed: (stripExternalFromLinkage(fn->getLinkage()) == stripExternalFromLinkage(linkage)), function getOrCreateFunction, file SILFunctionBuilder.cpp, line 35.

3.	While evaluating request ExecuteSILPipelineRequest(Run pipelines { Mandatory Diagnostic Passes + Enabling Optimization Passes } on SIL for Main)
4.	While running pass #456 SILModuleTransform "MandatoryPerformanceOptimizations".

7  swift-frontend           0x0000000109d0cfe4 swift::SILFunctionBuilder::getOrCreateFunction(swift::SILLocation, llvm::StringRef, swift::SILLinkage, swift::CanTypeWrapper<swift::SILFunctionType>, swift::IsBare_t, swift::IsTransparent_t, swift::IsSerialized_t, swift::IsDynamicallyReplaceable_t, swift::IsDistributed_t, swift::IsRuntimeAccessible_t, swift::ProfileCounter, swift::IsThunk_t, swift::SubclassScope) (.cold.3) + 0
8  swift-frontend           0x0000000105aa1114 swift::SILFunctionBuilder::getOrCreateFunction(swift::SILLocation, llvm::StringRef, swift::SILLinkage, swift::CanTypeWrapper<swift::SILFunctionType>, swift::IsBare_t, swift::IsTransparent_t, swift::IsSerialized_t, swift::IsDynamicallyReplaceable_t, swift::IsDistributed_t, swift::IsRuntimeAccessible_t, swift::ProfileCounter, swift::IsThunk_t, swift::SubclassScope) + 520
9  swift-frontend           0x0000000105aa26cc swift::SILFunctionBuilder::getOrCreateSharedFunction(swift::SILLocation, llvm::StringRef, swift::CanTypeWrapper<swift::SILFunctionType>, swift::IsBare_t, swift::IsTransparent_t, swift::IsSerialized_t, swift::ProfileCounter, swift::IsThunk_t, swift::IsDynamicallyReplaceable_t, swift::IsDistributed_t, swift::IsRuntimeAccessible_t) + 84
10 swift-frontend           0x000000010580b97c swift::trySpecializeApplyOfGeneric(swift::SILOptFunctionBuilder&, swift::ApplySite, llvm::SmallSetVector<swift::SILInstruction*, 8u>&, llvm::SmallVectorImpl<swift::SILFunction*>&, swift::OptRemark::Emitter&, bool) + 13468
11 swift-frontend           0x0000000105733b70 swift::specializeAppliesInFunction(swift::SILFunction&, swift::SILTransform*, bool) + 808
12 swift-frontend           0x0000000104cb4e58 $s9Optimizer19FunctionPassContextV17specializeApplies2in11isMandatorySb3SIL0B0C_SbtF + 44
13 swift-frontend           0x0000000104cb7658 $s9Optimizer33mandatoryPerformanceOptimizationsAA10ModulePassVvpfiyAA0eF7ContextVcfU_ + 1456
```

The problem is that getOrCreateSharedFunction expects that if the function already exists, it must be shared and not public. Let's fix this by not promoting the linkage to public during serialization in the "everything" mode.

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by eeckstein — COMMENTED** [review]
I don't like this fix, because it's cheating about the linkage. If a function is referenced in another module it should have public linkage.
We had horrible bugs in the past because we didn't have a sound linkage+serialization model.

IMO, the right fix should be in the specializer: when it checks if a specialization is already available, it should accept a public function (in case it's a specialization from another module). Maybe it's sufficient to just relax the assert condition.

We should stick to the linkage model which is documented in https://github.com/apple/swift/blob/main/include/swift/SIL/SILLinkage.h, because the compiler relies on this. For example: https://github.com/apple/swift/blob/5ced53e9b3756e571c652019e424e687a25b538b/include/swift/SIL/SILLinkage.h#L70

**Comment by slavapestov** [comment]
Maybe you can use PublicNonABI linkage? That's basically like Shared except the function becomes a root for DFE.

**Comment by kubamracek** [comment]
> Maybe it's sufficient to just relax the assert condition.

Changed the PR to this option.

**Review by eeckstein — APPROVED** [review]
Thanks!
lgtm

**Comment by kubamracek** [comment]
@swift-ci please test

**Pull request merged**
