### PR TITLE
Extend validation test Stride.swift showing `Strideable`'s implementation is broken 

### PR DESCRIPTION
**Pull request by valeriyvan**
This PR extends validation test Stride.swift showing that `Strideable`'s implementation is broken.
E.g. this simple line crashes: 
```
let a = Array(stride(from: 0, through: Int8.max, by: 3))
```

Specifically the problem lies in both `struct StrideToIterator<Element: Strideable>` and `struct StrideThroughIterator<Element: Strideable>`. The latter could be fixed thanks for having internal `_didReturnEnd` property. But for `struct StrideToIterator<Element: Strideable>` which doesn't have such property, I don't see a nice way to fix this bug. Both these structs are frozen.

Side note: looking to `Strideable` protocol I see a flaw which doesn't allow nice fix for the bug. It's `advanced(by:)` requirement:
```
func advanced(by n: Stride) -> Self
```
It returns `Self` giving no way to signal caller that it's impossible to advance value. I believe it should return optional `Self?`.

Bug filed https://bugs.swift.org/browse/SR-13883.

### CODE REVIEW

**Comment by benrimmington** [comment]
Could there be an `extension Strideable where Stride: FixedWidthInteger`, which uses `addingReportingOverflow(_:)` instead of the `advanced(by:)` default implementation?

https://github.com/apple/swift/blob/887464b7b67d5202bfa7adc4e3f045ff1027a5a7/stdlib/public/core/Stride.swift#L164-L172

Then each iterator's `next()` method would `guard _current.index != endIndex`.

See also the conditional conformances to `RandomAccessCollection`, which are currently disabled.

https://github.com/apple/swift/blob/887464b7b67d5202bfa7adc4e3f045ff1027a5a7/stdlib/public/core/Stride.swift#L309-L312

https://github.com/apple/swift/blob/887464b7b67d5202bfa7adc4e3f045ff1027a5a7/stdlib/public/core/Stride.swift#L518-L521

**Comment by valeriyvan** [comment]
> Could there be an `extension Strideable where Stride: FixedWidthInteger`, which uses `addingReportingOverflow(_:)` instead of the `advanced(by:)` default implementation?

It will only fix implementation for `FixedWidthInteger`. All other will still crash on edges of interval.

**Comment by xwu** [comment]
This is fixable. Is there a corresponding bug already filed?

**Comment by valeriyvan** [comment]
> This is fixable. Is there a corresponding bug already filed?

https://bugs.swift.org/browse/SR-13883
 
> > It will only fix implementation for `FixedWidthInteger`. All other will still crash on edges of interval.
> 
> What others are you referring to?

Here I meant custom types conforming to `Strideable`.

**Comment by xwu** [comment]
> Here I meant custom types conforming to `Strideable`.

`Stride` is required to conform to `SignedNumeric`, so it can only be a small handful of types.

**Comment by valeriyvan** [comment]
> > Here I meant custom types conforming to `Strideable`.
> 
> `Stride` is required to conform to `SignedNumeric`, so it can only be a small handful of types.

Then it means this bug could be fixed! That's great!

**Comment by xwu** [comment]
> Then it means this bug could be fixed! That's great! I could try to do it.

You're right it's not so easy, though. We can't do anything different just because `Stride` is known to be a fixed-width integer, actually. This requires some more experimentation. Since I put in the `_step` functions to begin with, I'll do some experimenting.

**Comment by valeriyvan** [comment]
> > Then it means this bug could be fixed! That's great! I could try to do it.
> 
> You're right it's not so easy, though. We can't do anything different just because `Stride` is known to be a fixed-width integer, actually. This requires some more experimentation. Since I put in the `_step` functions to begin with, I'll do some experimenting.

Could change in `Strideable` be discussed? 
`advanced(by n: Stride)` should return optional.

**Comment by xwu** [comment]
> Could change in `Strideable` be discussed?

No need. As I said, this is fixable.

**Comment by xwu** [comment]
Incidentally, why did you choose to extend the _validation_ test suite here instead of the usual test suite? The `Strideable` tests are located at `test/stdlib/Strideable.swift`.

**Comment by valeriyvan** [comment]
> Incidentally, why did you choose to extend the _validation_ test suite here instead of the usual test suite? The `Strideable` tests are located at `test/stdlib/Strideable.swift`.

My bad.

**Comment by valeriyvan** [comment]
Should I close this PR?

**Comment by xwu** [comment]
Only if you feel that the issue has been addressed. If there's some other issue that your tests do cover, then it's always great to have well-selected test cases to exercise the code.

**Comment by valeriyvan** [comment]
I ran my tests against your PR. Initial fix had problems. But the latest passes all my tests. Currently this PR makes no sense. Therefore I will close it after merge of your fix.

**Review by MinKhent88 — APPROVED** [review]
validation-test/stdlib/Stride.swift

**Pull request closed without merging**
