### PR TITLE
SwiftSyntax: Commit gyb-generated files to master

### PR DESCRIPTION
**Pull request by ahoppen**
This is a companion PR to https://github.com/apple/swift-syntax/pull/159. It adds the necessary flags to forward `--swiftsyntax-verify-generated-files` and adds a preset with which we can test SwiftSyntax in CI. At the moment SwiftSyntax is using a hard-baked command in CI.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/159

@swift-ci Please smoke test

**Comment by ahoppen** [comment]
Just realized I hadn't updated the generated files to match. Let's restart the test.

https://github.com/apple/swift-syntax/pull/159

@swift-ci Please smoke test

**Comment by ahoppen** [comment]
Swift-CI didn’t pull in the SwiftSyntax sources. Try again.

https://github.com/apple/swift-syntax/pull/159

@swift-ci Please smoke test

**Comment by ahoppen** [comment]
Test failure seemed unrelated. Let’s try one more time.

https://github.com/apple/swift-syntax/pull/159

@swift-ci Please smoke test macOS platform

**Comment by ahoppen** [comment]
The bug causing CI tests to fail should be fixed now

https://github.com/apple/swift-syntax/pull/159

@swift-ci Please smoke test macOS platform

**Review by nkcsgexi — APPROVED** [review]

**Review by nkcsgexi — APPROVED** [review]

**Pull request merged**
