### PR TITLE
[benchmark] Add some distance(from:to:) benchmarks for String views

### PR DESCRIPTION
**Pull request by lorentey**
This adds some new benchmarks dedicated to the `distance(from:to:)` functions on `String`'s four views, to see the effect of https://github.com/apple/swift/pull/62717 more directly.

rdar://103575481

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci benchmark

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci benchmark

**Comment by lorentey** [comment]
Local results before #62717:

```
940 StringDistance.characters                    132 14753.0   None       None   None 16744.0       None
941 StringDistance.scalars                       400   115.0   None       None   None   174.0       None
942 StringDistance.utf16                         192 10251.0   None       None   None 11237.0       None
943 StringDistance.utf8                          400     4.0   None       None   None    10.0       None
```

After #62717:

```
940 StringDistance.characters                    129 15108.0   None       None   None 15624.0       None
941 StringDistance.scalars                       400   119.0   None       None   None   170.0       None
942 StringDistance.utf16                         400   243.0   None       None   None   281.0       None
943 StringDistance.utf8                          400     4.0   None       None   None    10.0       None
```

`StringDistance.utf16` gets faster by a factor of 42. 😛

**Review by Keithbreadley — APPROVED** [review]

**Comment by karwa** [comment]
Some suggestions:

1. Benchmark with an ASCII sample string (String knows if its contents are ASCII, and all of these views can/should have fast-paths for `distance(from:to:)` in that case -- I don't know if they actually do)
2. Substring views might also be interesting?
3. Is it worth hoisting view construction out of the loops which call `distance(from:to:)`? View construction can involve retain/release calls, which in this instance could be significant. Perhaps the optimizer will notice they can be hoisted by itself, but the benchmarks may be more robust by doing it manually.

**Comment by lorentey** [comment]
```
  File "/Users/ec2-user/jenkins/workspace/swift-PR-macos-perf/swift/benchmark/scripts/Benchmark_Driver", line 631, in <listcomp>
    (min(memory_use), max(memory_use))
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
```

Cool! 🙄

**Comment by lorentey** [comment]
1. That's gilding this lily a bit more than I'd have preferred, but it's a good idea, and it's pretty easy to implement, too. 👍 

2. Properly benchmarking `Substring.*.distance` isn't straightforward, and I don't think it would be worth investing effort in it right now. `Substring`'s character view does have some extraordinarily slow edge cases thanks to the character slicing misfeature in SE-0180, but monitoring the performance of those isn't at all a priority. Distance calculations in the other substring views tend to directly forward to the base string, making them largely uninteresting. So `Substring` seems more of a correctness challenge than a performance one -- instead adding more benchmark coverage, I'd much rather work on making sure the new UTF-16 breadcrumb paths actually work correctly.

3. I think the cost of view construction ought to be part of these benchmarks -- if calling e.g. `string.utf8.distance(from:to:)` involves retaining string storage, then I think the measurement should certainly include that overhead. (The views are ~just tools that let us sort the String API surface into neat thematic groups; if they have overhead, then that's a bug.)

(Caveat: This PR is shaving an extremely deeply nested yak; it's four or five steps removed from the thing I actually want to work on, and I'm already in a rather foul mood because of it. I still keep finding more rabbit holes, but my patience is wearing thin. 🙈)

**Comment by lorentey** [comment]
@swift-ci smoke benchmark

**Comment by lorentey** [comment]
```
WARNING runtime: 'StringDistance.utf8.ascii' execution took 1 μs.
INFO runtime: Increase the workload of 'StringDistance.utf8.ascii' to be more than 20 μs.
/Users/ec2-user/jenkins/workspace/swift-PR-macos-perf/swift/benchmark/scripts/run_smoke_bench:29: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import load_source
Traceback (most recent call last):
  File "/Users/ec2-user/jenkins/workspace/swift-PR-macos-perf/swift/benchmark/scripts/run_smoke_bench", line 393, in <module>
    sys.exit(main())
  File "/Users/ec2-user/jenkins/workspace/swift-PR-macos-perf/swift/benchmark/scripts/run_smoke_bench", line 147, in main
    return test_opt_levels(args)
  File "/Users/ec2-user/jenkins/workspace/swift-PR-macos-perf/swift/benchmark/scripts/run_smoke_bench", line 196, in test_opt_levels
    check_added(args, output_file)
  File "/Users/ec2-user/jenkins/workspace/swift-PR-macos-perf/swift/benchmark/scripts/run_smoke_bench", line 389, in check_added
    doctor.check()
  File "/Users/ec2-user/jenkins/workspace/swift-PR-macos-perf/swift/benchmark/scripts/Benchmark_Driver", line 734, in check
    self.analyze(self.measure(test))
  File "/Users/ec2-user/jenkins/workspace/swift-PR-macos-perf/swift/benchmark/scripts/Benchmark_Driver", line 729, in analyze
    rule(benchmark_measurements)
  File "/Users/ec2-user/jenkins/workspace/swift-PR-macos-perf/swift/benchmark/scripts/Benchmark_Driver", line 630, in _constant_memory_use
    (min_i1, max_i1), (min_i2, max_i2) = [
  File "/Users/ec2-user/jenkins/workspace/swift-PR-macos-perf/swift/benchmark/scripts/Benchmark_Driver", line 631, in <listcomp>
    (min(memory_use), max(memory_use))
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
```

🙄🙄🙄

**Comment by lorentey** [comment]
@swift-ci benchmark

**Comment by lorentey** [comment]
@swift-ci benchmark

**Comment by lorentey** [comment]
```
WARNING runtime: 'StringDistance.utf8.ascii' execution took 2 μs.
INFO runtime: Increase the workload of 'StringDistance.utf8.ascii' to be more than 20 μs.
/Users/ec2-user/jenkins/workspace/swift-PR-macos-perf/swift/benchmark/scripts/run_smoke_bench:29: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import load_source
Traceback (most recent call last):
  File "/Users/ec2-user/jenkins/workspace/swift-PR-macos-perf/swift/benchmark/scripts/run_smoke_bench", line 393, in <module>
    sys.exit(main())
  File "/Users/ec2-user/jenkins/workspace/swift-PR-macos-perf/swift/benchmark/scripts/run_smoke_bench", line 147, in main
    return test_opt_levels(args)
  File "/Users/ec2-user/jenkins/workspace/swift-PR-macos-perf/swift/benchmark/scripts/run_smoke_bench", line 196, in test_opt_levels
    check_added(args, output_file)
  File "/Users/ec2-user/jenkins/workspace/swift-PR-macos-perf/swift/benchmark/scripts/run_smoke_bench", line 389, in check_added
    doctor.check()
  File "/Users/ec2-user/jenkins/workspace/swift-PR-macos-perf/swift/benchmark/scripts/Benchmark_Driver", line 734, in check
    self.analyze(self.measure(test))
  File "/Users/ec2-user/jenkins/workspace/swift-PR-macos-perf/swift/benchmark/scripts/Benchmark_Driver", line 729, in analyze
    rule(benchmark_measurements)
  File "/Users/ec2-user/jenkins/workspace/swift-PR-macos-perf/swift/benchmark/scripts/Benchmark_Driver", line 630, in _constant_memory_use
    (min_i1, max_i1), (min_i2, max_i2) = [
  File "/Users/ec2-user/jenkins/workspace/swift-PR-macos-perf/swift/benchmark/scripts/Benchmark_Driver", line 631, in <listcomp>
    (min(memory_use), max(memory_use))
ValueError: min() arg is an empty sequence
```

**Review by stephentyrone — APPROVED** [review]

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci benchmark

**Comment by lorentey** [comment]
This is getting very silly now.

```
******************** TEST 'Swift(macosx-x86_64) :: benchmark/benchmark-scripts.test-sh' FAILED ********************
Script:
--
: 'RUN: at line 1';   /Applications/Xcode-beta.app/Contents/Developer/usr/bin/python3 -m unittest discover -s /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/benchmark/scripts/
--
Exit Code: 1

Command Output (stderr):
--
FFFFFF........s....................................................................
======================================================================
FAIL: test_benchmark_has_constant_memory_use (test_Benchmark_Driver.TestBenchmarkDoctor)
Benchmark's memory footprint must not vary with num-iters.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/benchmark/scripts/test_Benchmark_Driver.py", line 1034, in test_benchmark_has_constant_memory_use
    self.assertNotIn("ConstantMemory", output)
AssertionError: 'ConstantMemory' unexpectedly found in "WARNING memory: 'ConstantMemory' has very wide range of memory used between independent, repeated measurements.\nINFO memory: 'ConstantMemory' mem_pages [i1, i2]: min=[0, 0] 𝚫=0 R=[1460, 1475]\nWARNING memory: 'VariableMemory' has very wide range of memory used between independent, repeated measurements.\nINFO memory: 'VariableMemory' mem_pages [i1, i2]: min=[0, 0] 𝚫=0 R=[1472, 1752]\nWARNING memory: 'HighVariance' has very wide range of memory used between independent, repeated measurements.\nINFO memory: 'HighVariance' mem_pages [i1, i2]: min=[0, 0] 𝚫=0 R=[6200, 6244]\n"

======================================================================
FAIL: test_benchmark_has_no_significant_setup_overhead (test_Benchmark_Driver.TestBenchmarkDoctor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/benchmark/scripts/test_Benchmark_Driver.py", line 948, in test_benchmark_has_no_significant_setup_overhead
    self.assertNotIn("NoOverhead", output)
AssertionError: 'NoOverhead' unexpectedly found in "WARNING memory: 'NoOverhead' has very wide range of memory used between independent, repeated measurements.\nINFO memory: 'NoOverhead' mem_pages [i1, i2]: min=[0, 0] 𝚫=0 R=[1000, 1000]\nERROR runtime: 'SO' has setup overhead of 4 μs (5.8%).\nINFO runtime: Move initialization of benchmark data to the `setUpFunction` registered in `BenchmarkInfo`.\nWARNING memory: 'SO' has very wide range of memory used between independent, repeated measurements.\nINFO memory: 'SO' mem_pages [i1, i2]: min=[0, 0] 𝚫=0 R=[1000, 1000]\nERROR runtime: 'Zero' execution took 0 μs.\nINFO runtime: Ensure the workload of 'Zero' has a properly measurable size (runtime > 20 μs) and is not eliminated by the compiler (use `blackHole` function if necessary).\nWARNING memory: 'Zero' has very wide range of memory used between independent, repeated measurements.\nINFO memory: 'Zero' mem_pages [i1, i2]: min=[0, 0] 𝚫=0 R=[1000, 1000]\nWARNING memory: 'LOA' has very wide range of memory used between independent, repeated measurements.\nINFO memory: 'LOA' mem_pages [i1, i2]: min=[0, 0] 𝚫=0 R=[1000, 1000]\n"

======================================================================
FAIL: test_benchmark_name_is_at_most_40_chars_long (test_Benchmark_Driver.TestBenchmarkDoctor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/benchmark/scripts/test_Benchmark_Driver.py", line 813, in test_benchmark_name_is_at_most_40_chars_long
    self.assertNotIn("BenchmarkName", output)
AssertionError: 'BenchmarkName' unexpectedly found in "WARNING memory: 'BenchmarkName' has very wide range of memory used between independent, repeated measurements.\nINFO memory: 'BenchmarkName' mem_pages [i1, i2]: min=[0, 0] 𝚫=0 R=[1000, 1000]\nWARNING naming: 'ThisTestNameIsTooLongAndCausesOverflowsInReports' name is composed of 11 words.\nINFO naming: Split 'ThisTestNameIsTooLongAndCausesOverflowsInReports' name into dot-separated groups and variants. See [http://bit.ly/BenchmarkNaming\nERROR](http://bit.ly/BenchmarkNaming/nERROR) naming: 'ThisTestNameIsTooLongAndCausesOverflowsInReports' name is 48 characters long.\nINFO naming: Benchmark name should not be longer than 40 characters.\nWARNING memory: 'ThisTestNameIsTooLongAndCausesOverflowsInReports' has very wide range of memory used between independent, repeated measurements.\nINFO memory: 'ThisTestNameIsTooLongAndCausesOverflowsInReports' mem_pages [i1, i2]: min=[0, 0] 𝚫=0 R=[1000, 1000]\n"

======================================================================
FAIL: test_benchmark_name_matches_naming_conventions (test_Benchmark_Driver.TestBenchmarkDoctor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/benchmark/scripts/test_Benchmark_Driver.py", line 775, in test_benchmark_name_matches_naming_conventions
    self.assertNotIn("BenchmarkName", output)
AssertionError: 'BenchmarkName' unexpectedly found in "WARNING memory: 'BenchmarkName' has very wide range of memory used between independent, repeated measurements.\nINFO memory: 'BenchmarkName' mem_pages [i1, i2]: min=[0, 0] 𝚫=0 R=[1000, 1000]\nWARNING memory: 'CapitalWordsConvention' has very wide range of memory used between independent, repeated measurements.\nINFO memory: 'CapitalWordsConvention' mem_pages [i1, i2]: min=[0, 0] 𝚫=0 R=[1000, 1000]\nWARNING memory: 'ABBRName' has very wide range of memory used between independent, repeated measurements.\nINFO memory: 'ABBRName' mem_pages [i1, i2]: min=[0, 0] 𝚫=0 R=[1000, 1000]\nWARNING naming: 'TooManyCamelCaseHumps' name is composed of 5 words.\nINFO naming: Split 'TooManyCamelCaseHumps' name into dot-separated groups and variants. See [http://bit.ly/BenchmarkNaming\nWARNING](http://bit.ly/BenchmarkNaming/nWARNING) memory: 'TooManyCamelCaseHumps' has very wide range of memory used between independent, repeated measurements.\nINFO memory: 'TooManyCamelCaseHumps' mem_pages [i1, i2]: min=[0, 0] 𝚫=0 R=[1000, 1000]\nWARNING memory: 'Existential.Array.method.1x.Val4' has very wide range of memory used between independent, repeated measurements.\nINFO memory: 'Existential.Array.method.1x.Val4' mem_pages [i1, i2]: min=[0, 0] 𝚫=0 R=[1000, 1000]\nWARNING memory: 'Flatten.Array.Array.Str.for-in.reserved' has very wide range of memory used between independent, repeated measurements.\nINFO memory: 'Flatten.Array.Array.Str.for-in.reserved' mem_pages [i1, i2]: min=[0, 0] 𝚫=0 R=[1000, 1000]\nWARNING memory: 'Flatten.Array.String?.as!.NSArray' has very wide range of memory used between independent, repeated measurements.\nINFO memory: 'Flatten.Array.String?.as!.NSArray' mem_pages [i1, i2]: min=[0, 0] 𝚫=0 R=[1000, 1000]\nERROR naming: 'wrongCase' name doesn't conform to benchmark naming convention.\nINFO naming: See [http://bit.ly/BenchmarkNaming\nWARNING](http://bit.ly/BenchmarkNaming/nWARNING) memory: 'wrongCase' has very wide range of memory used between independent, repeated measurements.\nINFO memory: 'wrongCase' mem_pages [i1, i2]: min=[0, 0] 𝚫=0 R=[1000, 1000]\nERROR naming: 'Wrong_convention' name doesn't conform to benchmark naming convention.\nINFO naming: See [http://bit.ly/BenchmarkNaming\nWARNING](http://bit.ly/BenchmarkNaming/nWARNING) memory: 'Wrong_convention' has very wide range of memory used between independent, repeated measurements.\nINFO memory: 'Wrong_convention' mem_pages [i1, i2]: min=[0, 0] 𝚫=0 R=[1000, 1000]\nERROR naming: 'Illegal._$%[]<>{}@^()' name doesn't conform to benchmark naming convention.\nINFO naming: See [http://bit.ly/BenchmarkNaming\nWARNING](http://bit.ly/BenchmarkNaming/nWARNING) memory: 'Illegal._$%[]<>{}@^()' has very wide range of memory used between independent, repeated measurements.\nINFO memory: 'Illegal._$%[]<>{}@^()' mem_pages [i1, i2]: min=[0, 0] 𝚫=0 R=[1000, 1000]\n"

======================================================================
FAIL: test_benchmark_runtime_range (test_Benchmark_Driver.TestBenchmarkDoctor)
Optimized benchmark should have runtime between 20 μs and 1000 μs.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/benchmark/scripts/test_Benchmark_Driver.py", line 865, in test_benchmark_runtime_range
    self.assertNotIn("Cheetah", output)
AssertionError: 'Cheetah' unexpectedly found in "ERROR runtime: 'Sylph' execution took 0 μs.\nINFO runtime: Ensure the workload of 'Sylph' has a properly measurable size (runtime > 20 μs) and is not eliminated by the compiler (use `blackHole` function if necessary).\nWARNING memory: 'Sylph' has very wide range of memory used between independent, repeated measurements.\nINFO memory: 'Sylph' mem_pages [i1, i2]: min=[0, 0] 𝚫=0 R=[1000, 1000]\nWARNING runtime: 'Unicorn' execution took 3 μs.\nINFO runtime: Increase the workload of 'Unicorn' to be more than 20 μs.\nWARNING memory: 'Unicorn' has very wide range of memory used between independent, repeated measurements.\nINFO memory: 'Unicorn' mem_pages [i1, i2]: min=[0, 0] 𝚫=0 R=[1000, 1000]\nWARNING memory: 'Cheetah' has very wide range of memory used between independent, repeated measurements.\nINFO memory: 'Cheetah' mem_pages [i1, i2]: min=[0, 0] 𝚫=0 R=[1000, 1000]\nWARNING runtime: 'Hare' execution took at least 1001 μs.\nINFO runtime: Decrease the workload of 'Hare' by a factor of 2 (10), to be less than 1000 μs.\nWARNING memory: 'Hare' has very wide range of memory used between independent, repeated measurements.\nINFO memory: 'Hare' mem_pages [i1, i2]: min=[0, 0] 𝚫=0 R=[1000, 1000]\nERROR runtime: 'Tortoise' execution took at least 500000 μs.\nINFO runtime: Decrease the workload of 'Tortoise' by a factor of 512 (1000), to be less than 1000 μs.\nWARNING memory: 'Tortoise' has very wide range of memory used between independent, repeated measurements.\nINFO memory: 'Tortoise' mem_pages [i1, i2]: min=[0, 0] 𝚫=0 R=[1000, 1000]\nERROR runtime: 'OverheadTurtle' has setup overhead of 200000 μs (25.0%).\nINFO runtime: Move initialization of benchmark data to the `setUpFunction` registered in `BenchmarkInfo`.\nERROR runtime: 'OverheadTurtle' execution took at least 600000 μs (excluding the setup overhead).\nINFO runtime: Decrease the workload of 'OverheadTurtle' by a factor of 1024 (1000), to be less than 1000 μs.\nWARNING memory: 'OverheadTurtle' has very wide range of memory used between independent, repeated measurements.\nINFO memory: 'OverheadTurtle' mem_pages [i1, i2]: min=[0, 0] 𝚫=0 R=[1000, 1000]\n"

======================================================================
FAIL: test_benchmark_setup_takes_reasonable_time (test_Benchmark_Driver.TestBenchmarkDoctor)
Setup < 200 ms (20% extra on top of the typical 1 s measurement)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/benchmark/scripts/test_Benchmark_Driver.py", line 983, in test_benchmark_setup_takes_reasonable_time
    self.assertNotIn("NormalSetup", output)
AssertionError: 'NormalSetup' unexpectedly found in "WARNING memory: 'NormalSetup' has very wide range of memory used between independent, repeated measurements.\nINFO memory: 'NormalSetup' mem_pages [i1, i2]: min=[0, 0] 𝚫=0 R=[1000, 1000]\nERROR runtime: 'LongSetup' setup took at least 200001 μs.\nINFO runtime: The `setUpFunction` should take no more than 200 ms.\nWARNING memory: 'LongSetup' has very wide range of memory used between independent, repeated measurements.\nINFO memory: 'LongSetup' mem_pages [i1, i2]: min=[0, 0] 𝚫=0 R=[1000, 1000]\n"

----------------------------------------------------------------------
Ran 83 tests in 0.147s

FAILED (failures=6, skipped=1)

--

********************
```

**Comment by lorentey** [comment]
@swift-ci test

**Pull request merged**
