### PR TITLE
[Concurrency] Tweak where concurrency tests run

### PR DESCRIPTION
**Pull request by DougGregor**
They need libdispatch (whether on macOS or anywhere else) but don't yet work with arm64e.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test macOS

**Comment by rjmccall** [comment]
Suggestion: use a lit feature for "supports concurrency execution" instead of duplicating this across tests.

**Pull request merged**
