### PR TITLE
[sourcekitd] Use add_llvm_symbol_exports instead of our old copy

### PR DESCRIPTION
**Pull request by benlangmuir**
Reduces duplication with llvm and, more importantly, gives us Linux
support via a linker script. This will let us link libsourcekitdInProc
in binaries that have their own copy of llvm symbols on Linux, and let
sourcekit-lsp stop using dlopen with `RTLD_DEEPBIND`, which fixes
running with asan among other things.

### CODE REVIEW

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please build toolchain

**Comment by benlangmuir** [comment]
@swift-ci please build toolchain macOS

**Comment by benlangmuir** [comment]
@swift-ci please test macOS

**Comment by compnerd** [comment]
The macOS failure is due to an incorrect automerge in lldb fixed by @fredriss on Friday.

```
/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/llvm-project/lldb/source/Plugins/ExpressionParser/Swift/SwiftREPL.cpp:570:32: error: no type named 'ImplicitModuleImportKind' in 'swift::SourceFile'
      const swift::SourceFile::ImplicitModuleImportKind implicit_import_kind =
            ~~~~~~~~~~~~~~~~~~~^
/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/llvm-project/lldb/source/Plugins/ExpressionParser/Swift/SwiftREPL.cpp:571:30: error: no member named 'ImplicitModuleImportKind' in 'swift::SourceFile'
          swift::SourceFile::ImplicitModuleImportKind::Stdlib;
          ~~~~~~~~~~~~~~~~~~~^
2 errors generated.
```

Lets give this another shot.

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please build macOS toolchain

**Comment by compnerd** [comment]
@swift-ci please build toolchain macOS

**Pull request merged**
