### PR TITLE
[IRGen] Add Builtin.addressOfRawLayout

### PR DESCRIPTION
**Pull request by Azoy**
This patch adds a distinct new instruction for converting the address of a raw layout to a `Builtin.RawPointer`. We want a distinction here because we want to keep raw layout operations opaque to the optimizer for the most part because it cannot reason about the formal access of raw layout (due to it having the ability vend mutable pointers to its storage in a borrowing context for example). This mostly works just like `address_to_pointer` except I haven't added this instruction to any optimizer pass or any instruction simplification to preserve it all the way to LLVM lowering.

In addition to the new instruction is a builtin that lowers directly to a call to this named `Builtin.addressOfRawLayout` with appropriate feature guards to ensure we don't have cond failures and such.

### CODE REVIEW

**Comment by Azoy** [comment]
@swift-ci please test

**Comment by atrick** [comment]
This generally looks great but...

Making RawLayoutAddressToPointer an instruction (as opposed to a Builtin) makes it tempting to handle it like other address casts, which allows passes to recognize that the address operand and pointer result are the same value. This completely defeats the purpose, which is to make the rawLayout storage opaque to the compiler. To do that, we need to make sure the compiler has no way of knowing that address operand and pointer result are related. It needs to be as if that pointer was materilized out of thin air.

So, for example handling RawLayoutAddressToPointer in ConversionOperation and isAccessStorageTypeCast exposes the relationship between the address and pointer result. The compiler will use that information to know that the raw layout storage is actually the same object as the struct type that defines it. I think we're trying to prevent that.

If we want to use an instruction for this (still not clear why that's good), then we should document it in SIL.rst, explaining that it creates an opaque separation between the address and resulting operand, along with the motivating example of an immutable address passed to a mutating function.

**Comment by Azoy** [comment]
@swift-ci please test

**Comment by Azoy** [comment]
@atrick I've gone ahead and removed the instruction and just have this lowering to a builtin instruction directly. Let me know what you think

**Comment by atrick** [comment]
> @atrick I've gone ahead and removed the instruction and just have this lowering to a builtin instruction directly. Let me know what you think

Nice. That satisfies my paranoia. Sorry about all the extra work.

Could we capture the information about this builtin's purpose, so that someone doesn't come along later and add compiler support for it? Maybe in Builtins.def. Something about how the purpose is to return an opaque pointer to memory that the compiler cannot associate with the rawLayout value. Furthermore, this opaque pointer must be the only way to access the rawLayout value. Otherwise, alias analysis could incorrectly assume immutability.
Maybe it's also worth a note in IRGen about how LLVM should never see operations on this address as 'invariant' even though the source address appears immutable.

**Review by atrick — APPROVED** [review]
LGTM. One suggestion about more comments...

**Comment by Azoy** [comment]
@atrick added more comments to \_really\_ document this and assert that this shouldn't be touched by the optimizer and LLVM cannot view this pointer as invariant ever.

**Comment by Azoy** [comment]
@swift-ci please test

**Comment by atrick** [comment]
> @atrick added more comments to _really_ document this and assert that this shouldn't be touched by the optimizer and LLVM cannot view this pointer as invariant ever.

Fantastic!

**Comment by Azoy** [comment]
@swift-ci please test

**Comment by drodriguez** [comment]
Does the `Cell.swift` test need changes after #72692 landed more or less at the same time? I am seeing a difference in the mangling and I am not sure what might be going on.

**Comment by Azoy** [comment]
@drodriguez resolved here: https://github.com/apple/swift/pull/72700

**Pull request merged**
