### PR TITLE
Fix -Wunknown-pragmas warnings with gcc in swift demangling code

### PR DESCRIPTION
**Pull request by nico**
No intended behavior change.

### CODE REVIEW

**Comment by nico** [comment]
@compnerd Want to bless this one too? IIRC it even modifies lines you touched :)

**Review by compnerd — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by nico** [comment]
Linux test output:

```
2024-08-06 04:06:49.563 swift-corelibs-foundationPackageTests.xctest[13785:70dfa700] httpServer: accept failed: Invalid argument (22)
TestFoundation/TestURLSession.swift:637: error: TestURLSession.test_connectTimeout : XCTAssertEqual failed: ("nil") is not equal to ("Optional(Foundation.URLError.Code.timedOut)") - Task should fail with URLError.timedOut error
2024-08-06 04:06:52.564 swift-corelibs-foundationPackageTests.xctest[13785:70dfa700] httpServer: accept failed: Invalid argument (22)
Test Case 'TestURLSession.test_connectTimeout' failed (3.002 seconds)
...
Test Suite 'TestURLSession' failed at 2024-08-06 04:07:08.747
	 Executed 79 tests, with 13 tests skipped and 1 failure (0 unexpected) in 19.292 (19.292) seconds
```

I'm gonna go out on a limb and say that that's unrelated to this change :)

What's the process for flakes? Re-run and hope for the best? Look at the output, realize it's non-sensical and just merge? Something else?

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by nico** [comment]
CI came back green, can someone hit merge? :)

**Pull request merged**
