### PR TITLE
[5.9] CMake: fix missing `SWIFT_CONCURRENCY_GLOBAL_EXECUTOR`

### PR DESCRIPTION
**Pull request by MaxDesiatov**
Explanation: Resolves issues with static linking on Linux
Risk: Medium, affects Linux builds and top-level CMake declarations.
Original PR: https://github.com/apple/swift/pull/65795.
Reviewed by: @al45tair @drexin @etcwilde 
Resolves: some of the issues reported in https://github.com/apple/swift/issues/65097
Tests: Added in https://github.com/apple/swift-integration-tests/pull/115

`SWIFT_CONCURRENCY_GLOBAL_EXECUTOR` is defined in `stdlib/cmake/modules/StdlibOptions.cmake`, which is not included during the first pass of evaluation of the root `CMakeLists.txt`. It is available on subsequent evaluations after the value is stored in CMake cache. This led to subtle bugs, where `usr/lib/swift_static/linux/static-stdlib-args.lnk` didn't contain certain flags on clean toolchain builds, but did contain them in incremental builds.

Not having these autolinking flags in toolchain builds leads to errors when statically linking executables on Linux.

Additionally, since are trivial tests previously didn't link Dispatch statically, the didn't expose a bug where `%import-static-libdispatch` substitution had a missing value. To fix that I had to update `lit.cfg` and clean up some of the related path computations to infer a correct substitution value.

Resolves some of the errors reported in https://github.com/apple/swift/issues/65097.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
https://github.com/apple/swift-integration-tests/pull/78

@swift-ci build toolchain

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci build toolchain

**Comment by MaxDesiatov** [comment]
https://github.com/apple/swift-integration-tests/pull/115

@swift-ci build toolchain

**Review by tomerd — APPROVED** [review]

**Review by al45tair — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
https://github.com/apple/swift-integration-tests/pull/115

@swift-ci build toolchain

**Comment by MaxDesiatov** [comment]
https://github.com/apple/swift-integration-tests/pull/115

@swift-ci build toolchain macOS

**Review by drexin — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
Current `build toolchain` failure is unrelated and is tracked in rdar://109774179

**Review by airspeedswift — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
https://github.com/apple/swift-integration-tests/pull/115

@swift-ci build toolchain macOS

**Pull request merged**
