### PR TITLE
[Macros] Invoke member macro expansion during qualified lookup.

### PR DESCRIPTION
**Pull request by hborla**
Otherwise, members that are added via macro expansion will not be visible in other source files.

### CODE REVIEW

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by hborla** [comment]
@swift-ci please smoke test macOS

**Comment by hborla** [comment]
@swift-ci please smoke test macOS

**Comment by hborla** [comment]
@swift-ci please smoke test macOS

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by asl** [comment]
@hborla This seems to break main. See e.g. https://ci.swift.org/job/swift-PR-macos/6157/

**Comment by hborla** [comment]
Thanks for the heads up @asl, and sorry about that! This PR raced with https://github.com/apple/swift-syntax/pull/1210. @ahoppen is preparing a fix for the test I added.

**Comment by asl** [comment]
Well, ok. Note that it blocks all incoming PRs. Maybe you'd remove the test in the meantime? And recommit with the fix?

**Comment by hborla** [comment]
The fix is merged already: https://github.com/apple/swift/pull/63495

**Comment by asl** [comment]
Great, thanks!

**Pull request merged**
