### PR TITLE
fix @differentiable function in .swiftinterface

### PR DESCRIPTION
**Pull request by marcrasi**
While messing with .swiftinterface files, I discovered that `@differentiable` functions don't get printed correctly in .swiftinterface files.

The test in `test/AutoDiff/differentiable_attr_parseable_interface.swift` demonstrates what this fixes.

The extra test in `test/Serialization/differentiable_attr.swift` was already passing before this change, but I noticed that that file didn't have a `@differentiable` function as a param, so I thought it would be good it to add to that file too.

### CODE REVIEW

**Review by rxwei — APPROVED** [review]
Nice. Thanks!

I think we should make this test be located in `test/AutoDiff` as `differentiable_attr_parseable_interface.swift` for now. Similarly, while a lot other test files in `test/AutoDiff` should in principle be in other test folders, we grouped them in the same folder in order to easily identify what to upstream when the time comes.

**Review by dan-zheng — APPROVED** [review]
Nice! I believe this at least partially resolves [TF-489](https://bugs.swift.org/browse/TF-489).
Could you try re-enabling `validation-test/ParseableInterface/verify_all_overlays.py`?

**Comment by marcrasi** [comment]
Okay, I tried re-enabling that. But it is still failing just as much as before. So I un-re-enabled it.

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Pull request merged**
