### PR TITLE
Replace stdlib and test/stdlib 9999 availability.

### PR DESCRIPTION
**Pull request by stephentyrone**
macOS 9999 -> macOS 10.15
iOS 9999 -> iOS 13
tvOS 9999 -> tvOS 13
watchOS 9999 -> watchOS 6

Less churn-inducing reworking of #25230

### CODE REVIEW

**Comment by stephentyrone** [comment]
Note that this *does not* include changes to test/*, only test/stdlib/*. There will be a follow-on PR with the remaining test changes. This also does not change the availability for ElementaryFunctions, because we've pended that out of 5.1.

**Comment by stephentyrone** [comment]
@swift-ci please test

**Comment by stephentyrone** [comment]
@milseman This is failing on a guard that you added in `b19c2cf9c33`:
```swift
  private init?<S: StringProtocol>(
    _ range: NSRange, _genericIn string: __shared S
  ) {
    // Corresponding stdlib version
    guard #available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *) else {
      fatalError()
    }
    ...
  }
```
What is this check actually trying to do? This init is called unconditionally from
```swift
  public init?(_ range: NSRange, in string: __shared String) {
    self.init(range, _genericIn: string)
  }
```
so I don't see how it was ever going to do the right thing.

**Comment by stephentyrone** [comment]
@swift-ci please test

**Review by milseman — APPROVED** [review]
LGTM, other than being dead code that we're adding to service an incomplete availability model.

**Pull request merged**
