### PR TITLE
Refactor CaseIterableTests

### PR DESCRIPTION
**Pull request by tattn**
I refactored CaseIterableTests.
Thanks @slavapestov (https://github.com/apple/swift/pull/25086)

### CODE REVIEW

**Comment by tattn** [comment]
@swift-ci please smoke test

**Review by slavapestov — APPROVED** [review]

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@tattn Sorry, only developers with commit access can trigger CI.

**Comment by tattn** [comment]
@slavapestov Oh, I see.
Thanks reviews :smile:

**Pull request merged**
