### PR TITLE
[stdlib] De-gyb everything

### PR DESCRIPTION
**Pull request by Azoy**
See here: https://forums.swift.org/t/struggling-to-find-things-in-the-new-stdlib-for-5-0-e-g-where-is-addingreportingoverflow-implemented/18612/7

This removes all `.gyb` files from the stdlib. There might be a lot of formatting problems as I just copied over the un-gybbed version of all of these files. I did however go through and do some simple formatting for things that were excessive over the 80 col limit or did not align to stdlib code style.

cc: @airspeedswift @stephentyrone @lorentey

### CODE REVIEW

**Comment by xwu** [comment]
I think this would be much easier to review if the first commits were just the ungybbed versions, and then any formatting or changes you've made were subsequent commits.

**Comment by Azoy** [comment]
@xwu would you prefer a separate commit for each file I formatted post degyb? I'm thinking about having 2 separate commits for splitting up `FloatingPointTypes` and `IntegerTypes`.

**Comment by xwu** [comment]
Not only that, but I wonder if we could even have separate PRs by theme. Some of these files are trivial to de-gyb; others could use some more attention.

**Comment by Azoy** [comment]
Is there any specific groupings you had in mind? Most of these were trivial to de-gyb, but I spent more time with splitting up floating points and integer types. Maybe we can do those 3 PRs?

**Comment by Azoy** [comment]
Closing in favor of smaller prs

**Pull request closed without merging**
