### PR TITLE
Initial support for compile-time generation of vprintf format strings, behind the SWIFT_STDLIB_STATIC_PRINT flag

### PR DESCRIPTION
**Pull request by Catfish-Man**
Based on a heavily stripped down version of OSLog's formatting system, with modifications to make it more amenable to stack promotion.

This lacks float and object support for now

### CODE REVIEW

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Review by kubamracek — APPROVED** [review]

**Comment by Catfish-Man** [comment]
@swift-ci please test and merge

**Comment by Catfish-Man** [comment]
@swift-ci please test and merge

**Pull request merged**
