### PR TITLE
Emit swiftmodule as intermediate file even if it's top level output

### PR DESCRIPTION
**Pull request by kateinoigakukun**
`ShouldTreatModuleAsTopLevelOutput` is set to false when using `-emit-module-interface`, so we expect that the output file should be temporary.
But since the emit-module job is top level, `getOutputFilename` infers that the file is specified by `-o`. 
So I changed to infer the file name as temporary file if `ShouldTreatModuleAsTopLevelOutput` is false.

This bug can be problem when using `-static`, `-emit-module-interface`, `-emit-library` and `-o` on Linux.

```swift
$ touch Module.swift
$ swiftc Module.swift -static -emit-library -emit-module-interface -o libModule.a -v
Swift version 5.1-dev (LLVM c5340df2d1, Swift 768ac78cb0)
Target: x86_64-unknown-linux-gnu
/home/katei/swift-source/build/Ninja-DebugAssert/swift-linux-x86_64/bin/swift -frontend -c -primary-file Module.swift -emit-module-path /tmp/Module-67124f.swiftmodule -emit-module-doc-path /tmp/Module-67124f.swiftdoc -target x86_64-unknown-linux-gnu -disable-objc-interop -color-diagnostics -static -parse-as-library -module-name Module -o /tmp/Module-67124f.o
/home/katei/swift-source/build/Ninja-DebugAssert/swift-linux-x86_64/bin/swift -frontend -merge-modules -emit-module /tmp/Module-67124f.swiftmodule -parse-as-library -sil-merge-partial-modules -disable-diagnostic-passes -disable-sil-perf-optzns -target x86_64-unknown-linux-gnu -disable-objc-interop -color-diagnostics -static -emit-module-doc-path libModule.swiftdoc -emit-module-interface-path Module.swiftinterface -module-name Module -o libModule.a
<unknown>:0: warning: module interfaces are only supported with -enable-library-evolution
/home/katei/swift-source/build/Ninja-DebugAssert/swift-linux-x86_64/bin/swift-autolink-extract /tmp/Module-67124f.o -o /tmp/Module-16bebe.autolink
/usr/bin/ar crs libModule.a /tmp/Module-67124f.o
/usr/bin/ar: libModule.a: file format not recognized
<unknown>:0: error: static-link command failed with exit code 1 (use -v to see invocation)

```

### CODE REVIEW

**Review by davidungar — CHANGES_REQUESTED** [review]
Not your fault, but the affected function is already too big to be readily understandable IMO.
At the very least, I would request that you introduce a new variable and make the argument const so that readers don't miss the potential change. Better still would be to break up this function into sensible pieces. 
WRT to the correctness of the change, I can't help you; I'm not familiar enough with the context, sorry!

**Comment by DougGregor** [comment]
Please add a test into `test/Driver`

**Comment by kateinoigakukun** [comment]
I added test case!

**Comment by kateinoigakukun** [comment]
Could you review again?

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by CodaFi** [comment]
@swift-ci test

**Review by davidungar — CHANGES_REQUESTED** [review]
I'm very sorry this request escaped my notice. Thank you @CodaFi , for the ping! After reading the changes over, and reading the huge function in question, I still don't think that a maintainer could understand the reasons for the code, even before your change. I'm assuming that you do understand the function this PR changes, and that you put in some serious study time to do so! 

It would be great to use your investment here to help future developers. Would you like to do whatever you can think of: such as adding "why" comments, breaking up the function, etc. in order to make it easier for future folks to maintain this code?

Heartfelt thanks!

PS Please feel free to ping me immediately in the future.

**Pull request closed without merging**
