### PR TITLE
Fix and reenable NewArray.swift.gyb

### PR DESCRIPTION
**Pull request by gribozavr**

### CODE REVIEW

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by gribozavr** [comment]
@swift-ci Please test Windows

**Comment by CodaFi** [comment]
Tagging @airspeedswift because they disabled this originally.

**Comment by gribozavr** [comment]
@swift-ci Please test Windows

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
