### PR TITLE
In swift-project-settings.el, don't outdent case labels.

### PR DESCRIPTION
**Pull request by atrick**
I fixed a couple small annoyances in the emacs C++ syntax support.

@gottesmm @rudkx is anyone still using the checked in swift-project-settings.el? Do people actually apply .dir-locals? Shouldn't this be consistent with clang-format?

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci smoke test.

**Comment by gottesmm** [comment]
I wish that we were not using .dir-locals in general. Every time the prompt comes up it annoys me slightly. I use clang-format on my c++ code.

**Comment by atrick** [comment]
FWIW, I'm on board with removing .dir-locals. I'm not sure if anyone wants it. At the moment I just want to quickly fix some annoyances though.

**Comment by rudkx** [comment]
I haven't been using either. I just try to remember to `clang-format` everything and tend to use my own settings from my own config files.

**Comment by rudkx** [comment]
BTW, @gottesmm, you can do:
```
;; Don't set or prompt about dir local variables.
(setq enable-dir-local-variables nil)
```

to avoid the prompts re: dir locals. I added this to my init file a few years back.

**Comment by atrick** [comment]
@rudkx thanks. I'll disable .dir-locals and avoid using swift-project-settings. When the time is right, we can just delete both these files.

**Pull request merged**
