### PR TITLE
[Runtime] Detect and log redundant subclass/superclass conformances.

### PR DESCRIPTION
**Pull request by al45tair**
When we rely on a protocol conformance, and the type in question has multiple conformances to that protocol in its inheritance chain, emit a runtime warning.

It's quite tricky to cause this problem - you need a type in one dylib that is extended to conform to a protocol in another dylib, subclassed in another module and then some subclass has protocol conformance added as well.  If they're in
the same module, the compiler will give an error and prevent the problem completely.

rdar://73364629

### CODE REVIEW

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
Note that you'll only get a warning _if_ you rely on a protocol conformance _and_ there are multiple redundant conformances in the inheritance hierarchy. It's fairly tricky to trigger (I needed two dylibs and an executable). I haven't added a test to Swift for it; I don't know whether that's worth doing?

**Comment by mikeash** [comment]
Looks good. I think a test is worthwhile. We have other tests that build dylibs from multiple files so you should be able to find examples to crib from.

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
@swift-ci Please smoke test macOS platform

**Pull request merged**
