### PR TITLE
Define InterfaceTypeRequest

### PR DESCRIPTION
**Pull request by CodaFi**
Now that VarDecl's interface type computation is rationalized, the final piece was formalizing the `ParamDecl` case returning the null `Type`. 

Define a request for the interface type. This is not the end of this story by a long shot.  The pattern binding request needs to be divided into a checked initializer request and a checked pattern request.  The naming pattern request needs to do a lot less work by just checking one or the other.  A bunch of places in the compiler have ad-hoc circularity breaking code that also needs to be swept up under the evaluator.  The decl validation machinery still needs to be expunged.

There's a lot to do, but we can at least celebrate the little things.

🎉 **validateDecl is dead!** 🎉

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please test

**Comment by CodaFi** [comment]
@swift-ci please test source compatibility

**Comment by CodaFi** [comment]
⛵️

**Comment by compnerd** [comment]
I believe that this has regressed the Windows build: https://github.com/asuhan/swift/commit/4fc20a4a9a1659d4b05b208ed1a510d71df22c3e

`?:` is a non-portable GNU extension (see AST/Decl.cpp:2819)

**Comment by graydon** [comment]
Congratulations!

**Pull request merged**
