### PR TITLE
[5.5-abi][Concurrency] Remove Task.current because it prevents task-local alloc #36993

### PR DESCRIPTION
**Pull request by ktoso**
This change makes #36993 actually safe -- there is no way to randomly get and store a `Task` anymore other than via the unsafe API.

More context: https://forums.swift.org/t/se-0304-2nd-review-structured-concurrency/47217/88

The `Task.Handle` API is always safe to keep the task around because that task is guaranteed to be heap allocated (unlike "any" task, which may be an async-let task which is task-local allocated).

FYI @airspeedswift 

Please review @DougGregor if this is actually okey to merge -- we're removing conformances here; Noone should have been realistically been using them but I have no idea if this won't cause some form of "cond fail"?

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Review by kavon — APPROVED** [review]
This makes a lot of sense to me, given the allocation strategy we're going to use for them.

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
Going to re-target this at the ABI breaking branch.

**Comment by ktoso** [comment]
Re targeting PR was a mess, will make a new one

**Pull request closed without merging**
