### PR TITLE
Build system recognizes OpenBSD.

### PR DESCRIPTION
**Pull request by 3405691582**
Commit for CMake and build scripts to recognize OpenBSD. To keep this
commit relatively short, this just deals with the rather simple and
uncontroversial changes to the build system.

Note that OpenBSD calls "x86_64" as "amd64", Since the Swift stdlib will
be put in a subdirectory named after ARCH, to ensure the standard
library is properly found later, we use the native architecture name for
OpenBSD in the build system rather than trying to deal with the
difference the other way around.

### CODE REVIEW

**Comment by compnerd** [comment]
This conflicts with a big shuffle that we are trying to do (#29807), Id appreciate it if you could wait for that

**Comment by 3405691582** [comment]
Sure! There's no rush.

**Comment by 3405691582** [comment]
Done.

**Review by finagolfin — APPROVED** [review]

**Comment by compnerd** [comment]
:-( I really dislike that its expanding the horrors of the SDK setup which I'm trying to remove.  Sadly, no way around that currently.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by 3405691582** [comment]
Fixed the linter failure. Should pass cleanly now.

**Comment by CodaFi** [comment]
@swift-ci python lint

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by 3405691582** [comment]
Linux failure looks unrelated (same failures exhibited on older prior builds [like 19724](https://ci.swift.org/job/swift-PR-Linux/19724)).

**Comment by CodaFi** [comment]
It is unrelated - corelibs has a poor implementation of filesystem APIs on Linux which is causing a non-deterministic failure in SourceKit-LSP's tests. I'll merge this when we unblock this.

**Comment by CodaFi** [comment]
Not sure if it’s fixed, but

@swift-ci smoke test Linux platform

**Comment by CodaFi** [comment]
@swift-ci smoke test Linux platform

**Comment by CodaFi** [comment]
@swift-ci smoke test Linux

**Comment by CodaFi** [comment]
@swift-ci smoke test Linux

**Comment by CodaFi** [comment]
Still hitting this...

@swift-ci please clean smoke test Linux platform

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
