### PR TITLE
[AutoDiff] Remove 'withoutDerivative(at:in:)' and 'withDerivative(_:)'.

### PR DESCRIPTION
**Pull request by rxwei**
These APIs are not included in the initial proposal. This PR moves them to `DifferentiationUnittests`.

### CODE REVIEW

**Comment by rxwei** [comment]
Please review 67e84b6.

**Comment by rxwei** [comment]
@swift-ci please smoke test and merge

**Review by dan-zheng — APPROVED** [review]
LGTM (seems like users of removed APIs can redefine in their own code, thanks to the non-hardcoded design)

**Comment by rxwei** [comment]
@swift-ci please smoke test and merge

**Comment by porterchild** [comment]
I'd just like to say that there are some Autodiff bugs that require workarounds using `.withDerivative` in my codebase (mostly related to [SR-14218](https://bugs.swift.org/browse/SR-14218) and array differentiation) and I'm not sure I would have found workarounds without having `withDerivative`. It is also useful when I want to print gradients as they propagate as a 'poor man's debugger'. 

There may be reasons (scope of the current proposal (?)) to remove it, and it is technically re-definable by users, but from a beginner's standpoint, I think `withDerivative` hugely increases usability, and it's very unlikely I would have thought to re-define it myself

**Pull request merged**
