### PR TITLE
[5.0] [Sema] Diagnose internal(set) from @inlinable functions

### PR DESCRIPTION
**Pull request by harlanhaskins**
This patch mainly consolidates the functions used to check accessors vs.
other decls, and makes sure we check setter access as well as regular
decl access.

rdar://45217648

### CODE REVIEW

**Comment by harlanhaskins** [comment]
@apple/swift5-branch-managers This adds a new warning in Swift 4.2 and error in Swift 5 detecting an ABI violation regarding @inlinable declarations calling an internal setter.

**Comment by AnnaZaks** [comment]
Let's test source compatibility as well once the basic tests pass.

**Comment by harlanhaskins** [comment]
@swift-ci please test

**Comment by harlanhaskins** [comment]
@swift-ci please test source compatibility

**Comment by harlanhaskins** [comment]
Source compact suite failed with 4 UPASSes.

**Review by AnnaZaks — APPROVED** [review]

**Pull request merged**
