### PR TITLE
[TypeChecker/SILGen] Allow `any Sendable` to match `Any` while matching generic arguments

### PR DESCRIPTION
**Pull request by xedin**
Allow `any Sendable` to match `Any` constraint while matching
generic arguments i.e. `[any Sendable]` -> `[Any]` when `any Sendable`
type comes from context that involves `@preconcurrency` declarations.

To facilitate that we need a new expression that models an unsafe bitcast
from one type to the other - `UnsafeCastExpr`. This expression is going
to be introduced by the solver during solution application phase to 
erase `any Sendable` to `Any` in generic argument positions.

Resolves: rdar://140300022

### CODE REVIEW

**Comment by xedin** [comment]
We can use `UnsafeCastExpr` to model both `CovariantFunctionConversionExpr` and `CovariantReturnConversionExpr`. I'll attempt to make that chance one this lands.

**Comment by xedin** [comment]
@swift-ci please test

**Review by atrick — COMMENTED** [review]
`SILGenBuilder::createUncheckedForwardingCast` LGTM

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility debug

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Pull request merged**
