### PR TITLE
[stdlib] Clean up warnings

### PR DESCRIPTION
**Pull request by dabrahams**

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please smoke test and merge

**Comment by dabrahams** [comment]
@natecook1000 This commit makes some documentation fixes you might want to look over.

**Comment by dabrahams** [comment]
@moiseev Any chance you could clean up this test failure and land the patch?  It gets rid of all the warnings due to new Integer stuff.  Thx

**Comment by moiseev** [comment]
@swift Please smoke test and merge

**Comment by airspeedswift** [comment]
@swift-ci Please smoke test and merge

**Comment by dabrahams** [comment]
@swift-ci Please smoke test and merge

**Comment by shahmishal** [comment]
@swift-ci Please smoke test and merge

**Pull request merged**
