### PR TITLE
[CodeCompletion] Fix call arguments completion in overloaded case

### PR DESCRIPTION
**Pull request by rintaro**
In `<expr> '(' <code-completion-token>` case, we usually complete call arguments. However, if `<expr>` isn't typechecked, for example because of overloading, we used to give up arguments completions.

Now, use possible callee informations from `CodeCompletionTypeContextAnalyzer`. This increases the chance to provide arguments completions.

rdar://problem/43703157

(#20703 is a groundwork for this PR)

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by benlangmuir** [comment]
Will this work for individual label completions (i.e. what you get in `overload(x: 1, <complete>)`?

**Comment by rintaro** [comment]
That's still TODO. [(`OVERLOAD1` and `OVERLOAD2`)](https://github.com/apple/swift/blob/5fdf8ee088c068149b6c587c7476df2dd8dc22b7/test/IDE/complete_call_arg.swift#L10-L11).

For example, given:
```swift
func foo(arg1: Int, bar: Double) {}
func foo(arg1: Int, baz: Int){}
func foo(arg1: String, qux: Int) {}

func _test(x:C ) {
  foo(arg1: 1, #^COMPLETE^#
}
```
`bar:`, `baz:`, and `qux:` are all suggested. But `qux: ` is not relevant here because `arg1` is `Int`.

**Review by benlangmuir — APPROVED** [review]
LGTM other than some nitpicks about wording.

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Pull request merged**
