### PR TITLE
[ConstraintSystem] Allow injecting `callAsFunction` after defaulted arguments

### PR DESCRIPTION
**Pull request by xedin**
- Adjust argument matching to be less aggressive while matching misplaced trailing closures
   against defaulted parameters that do not accept trailing closures.

   For example:

   ```swift
   func test(a: Int? = 42, b: String? = nil) {}

   test {
     ...
   }
   ```

  Trailing closure in this case should be marked as "extraneous" instead of matched
   against parameter `a:`.

- If trailing closure is extraneous in a call to `.init` on callable type, let's not attempt to
   to fix it and allow solver to inject `.callAsFunction` first.

Resolves: rdar://problem/94959816

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please build toolchain macos

**Comment by xedin** [comment]
@swift-ci please build toolchain macos

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test

**Review by hborla — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Pull request merged**
