### PR TITLE
Centralize task creation in the Concurrency runtime

### PR DESCRIPTION
**Pull request by DougGregor**
**Explanation**: Centralize and clean up task creation facilities for the concurrency runtime. This reduces the number of entry points we use to create tasks while making them more general, so we can extend the task-creation facilities without breaking the ABI again. This itself is a significant ABI break for Swift Concurrency.
**Scope**: Affects all programs using Swift Concurrency
**Radar/SR Issue**: rdar://79584250
**Risk**: Moderate. It's a rework of compiler/runtime interaction for concurrent task creation, so it carries some risk of breaking programs using concurrency.
**Testing**: PR testing and CI on main.
**Original PR**: https://github.com/apple/swift/pull/38021

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Review by ktoso — APPROVED** [review]
👍

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
Spurious failure on Linux. Retrying...

**Comment by DougGregor** [comment]
@swift-ci please test Linux

**Comment by DougGregor** [comment]
macOS hit the async_stream failure but is otherwise good. Rerunning...

**Comment by DougGregor** [comment]
@swift-ci please test macOS

**Comment by DougGregor** [comment]
@swift-ci please nominate

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test Linux

**Review by tkremenek — APPROVED** [review]

**Pull request merged**
