### PR TITLE
[IRGen testing] Reapply: Fix bogus FileCheck check-prefix "-SAME" usage

### PR DESCRIPTION
**Pull request by davezarzycki**
The correct usage of "-SAME" is after the check-prefix, not in the middle. I've updated the constants to what is emitted today.

Now with verified 32-bit fixes.

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@davezarzycki please grab the changes in #31845 if you are re-applying the changes

**Review by compnerd — CHANGES_REQUESTED** [review]
#31845 contains the fixes for Windows, though it fails on macOS which is fixed here.  The two should be merged.

**Comment by davezarzycki** [comment]
Cherry-pick of #31845. No other changes:

@swift-ci please smoke test

**Comment by davezarzycki** [comment]
@swift-ci please smoke test
@swift-ci please test windows

**Comment by davezarzycki** [comment]
This was originally approved in #31839, so I'm going to merge now that I've had a chance to run the 32-bit iOS tests on my Mac and now that @compnerd provided a fix for Windows.

**Pull request merged**
