### PR TITLE
[IRGen] Always use os version from swift invocation in IRGen

### PR DESCRIPTION
**Pull request by cachemeifyoucan**
Do not infer IRGen target from clang importer. `-clang-target` can give it a different OS version for importing clang Decls and that triple should not be used to generate code.

rdar://130547690

### CODE REVIEW

**Comment by cachemeifyoucan** [comment]
@swift-ci please smoke test

**Comment by cachemeifyoucan** [comment]
@swift-ci please smoke test

**Review by artemcm — APPROVED** [review]

**Comment by cachemeifyoucan** [comment]
Alternative fix: https://github.com/swiftlang/swift/pull/74755

**Comment by cachemeifyoucan** [comment]
Taking the other fix. Closing.

**Pull request closed without merging**
