### PR TITLE
[test] Re-enable SmallString tests with updated platform checks

### PR DESCRIPTION
**Pull request by lorentey**
- Tagged NSString checks are only expected to work on recent macOS/iOS versions
- SmallStrings are a thing on Linux, too, although they don't bridge as tagged pointers.

rdar://problem/49083892

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Review by milseman — APPROVED** [review]
LGTM

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci please test linux platform

**Comment by Catfish-Man** [comment]
Sadly this is going to merge conflict my bridging changes, but that's fine, they need to wait on S-E anyway. Looks good.

**Review by Catfish-Man — APPROVED** [review]

**Pull request merged**
