### PR TITLE
Some small constraint system cleanups.

### PR DESCRIPTION
**Pull request by rudkx**

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by aschwaighofer** [comment]
https://ci.swift.org/job/oss-swift_tools-R_stdlib-RD_test-simulator/699/

utils/build-script --preset=buildbot,tools=R,stdlib=RD install_destdir="${WORKSPACE}/install" installable_package="${SWIFT_INSTALLABLE_PACKAGE}"

```
FAIL: Swift(macosx-x86_64) :: Sema/type_checker_perf/fast/rdar33806601.swift (7244 of 10620)
******************** TEST 'Swift(macosx-x86_64) :: Sema/type_checker_perf/fast/rdar33806601.swift' FAILED ********************
Script:
--
/Users/buildnode/jenkins/workspace/oss-swift_tools-R_stdlib-RD_test-simulator/Ninja-Release/swift-macosx-x86_64/bin/swiftc -frontend -target x86_64-apple-macosx10.9  -module-cache-path '/var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/swift-testsuite-clang-module-cacheOpYdJG' -sdk /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -swift-version 3 -typecheck -verify -disable-objc-attr-requires-foundation-module /Users/buildnode/jenkins/workspace/oss-swift_tools-R_stdlib-RD_test-simulator/swift/validation-test/Sema/type_checker_perf/fast/rdar33806601.swift -solver-expression-time-threshold=1
--
Exit Code: 1

Command Output (stderr):
--
/Users/buildnode/jenkins/workspace/oss-swift_tools-R_stdlib-RD_test-simulator/swift/validation-test/Sema/type_checker_perf/fast/rdar33806601.swift:12:27: error: unexpected error produced: expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions
let _: (P, P) -> Double = {
```

**Comment by aschwaighofer** [comment]
I disabled the test.

http://bugs.swift.org/browse/SR-6518

**Pull request merged**
