### PR TITLE
Add deserialization support for section attribute

### PR DESCRIPTION
**Pull request by kastiglione**
While working on #71425, I hit an assert indicating the `@_section` attribute was not handled in `DeclDeserializer::deserializeDeclCommon`. This change adds the missing deserialization for the `@_section` attribute.

### CODE REVIEW

**Comment by kastiglione** [comment]
Alternatively, should the `_section` attribute be marked `NotSerialized`?

**Comment by kastiglione** [comment]
@swift-ci smoke test

**Review by eeckstein — COMMENTED** [review]
Can you add a test?

**Comment by kastiglione** [comment]
@eeckstein is there a convention for testing deserialization? The way I would construct a test is to serialize a swiftmodule containing the section attribute, and then load it from a separate invocation. If the loading crashes, the test fails.

**Comment by eeckstein** [comment]
Yes. You can look at some examples in https://github.com/apple/swift/tree/main/test/Serialization, for example https://github.com/apple/swift/blob/main/test/Serialization/attr-extern.swift

**Comment by kastiglione** [comment]
@swift-ci test

**Comment by kastiglione** [comment]
@swift-ci test linux

**Comment by kastiglione** [comment]
@swift-ci test

**Review by eeckstein — APPROVED** [review]
lgtm!

**Comment by kastiglione** [comment]
@swift-ci test macOS

**Comment by kastiglione** [comment]
@swift-ci test linux

**Comment by kastiglione** [comment]
@swift-ci test macOS

**Pull request merged**
