### PR TITLE
Infer imports for linking

### PR DESCRIPTION
**Pull request by jrose-apple**
Alternate version of #16299. Checks what modules are being used in inlinable code, and adds them to the "usable from inline" list for autolinking purposes.

This isn't quite as clean as the version Slava had, but that one started affecting name lookup, and so I went for a more heavy-handed version.

rdar://problem/39338239

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test compiler performance

**Comment by jrose-apple** [comment]
#16211 added the notion of "usable from inline imports", by the way, if you're looking for the context.

**Review by graydon — APPROVED** [review]
Discussed on chat, this looks sensible to me (as far as I can understand it and its backstory).

**Comment by slavapestov** [comment]
LGTM

**Comment by jrose-apple** [comment]
I have a fix for this particular issue but now I'm foreseeing problems with using this within Apple due to the way we lay out certain SDK content. I'll talk with Graydon and Doug about it tomorrow.

**Pull request closed without merging**
