### PR TITLE
Improve diagnostics for comparisons to nil.

### PR DESCRIPTION
**Pull request by rudkx**
#### What's in this pull request?

Noticed by inspection, the diagnostics for comparing against literal `nil` were not treating the operands symmetrically, so we were only emitting a diagnostic if the `nil` was on the right hand side.

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

As implemented the diagnostic specific to nil was only firing when nil
was on the right hand side.

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please test.

**Comment by rudkx** [comment]
@CodaFi Robert, it looks like you touched this last - mind reviewing?

**Comment by rudkx** [comment]
@swift-ci Please smoke test.

**Comment by CodaFi** [comment]
LGTM.  Thank you for cleaning up that icky stretch of code.

**Comment by rudkx** [comment]
@swift-ci Please smoke test.

**Pull request merged**
