### PR TITLE
Functions with differing phis should not be merged.

### PR DESCRIPTION
**Pull request by rudkx**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

Check that the incoming blocks of phi nodes are identical, and block
function merging if they are not.

rdar://problem/26387654

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Test and merge.

**Comment by rudkx** [comment]
@eeckstein Erik, can you review?

**Comment by eeckstein** [comment]
LGTM

**Comment by rudkx** [comment]
The CI bots were pretty broken earlier in the day, so I directly committed in da9c34644472c80a98cdf2706469735e58ed31e1.

**Pull request closed without merging**
