### PR TITLE
Stub out a tool that runs a script over a Swift AST

### PR DESCRIPTION
**Pull request by rjmccall**
The tool is currently hard-coded to find functions in the SwiftUI library that take parameters of type `(...) -> T` where `T: View` but where the parameter isn't annotated with `@ViewBuilder`.  The long-term vision here, of course, is that this reads and interprets a script file, but that's quite a bit more work (especially to generate a million bindings to the AST).  In the meantime, I think having a functional harness that people familiar with the C++ API can easily hack on to make their own tools is still pretty useful.

The harness does try to open a script file and lex the first token of it, because that's exactly as far as I got before deciding to hard-code the query I wanted.  Since this input is otherwise ignored, you can just point the tool at any old `.swift` file (or just an empty file) and it'll be fine.

### CODE REVIEW

**Comment by rjmccall** [comment]
Not sure whether to actually commit this.

**Comment by rjmccall** [comment]
@swift-ci Please smoke test.

**Comment by compnerd** [comment]
I mentioned this idea to @nkcsgexi a while ago - basically providing the same functionality that the clang ASTMatchers provide.  I would like to see this sort of grow into its own library sorta how clang does it, but at least this can provide the starting point (note, I've not yet looked through the code).

**Comment by rjmccall** [comment]
@swift-ci Please smoke test.

**Comment by rjmccall** [comment]
@compnerd My dream is that this could become a tool that end-users could reasonably hope to use.  I don't see an ASTMatchers approach ever getting there.

**Comment by rjmccall** [comment]
Alright, committing so that this can be out there.

**Pull request merged**
