### PR TITLE
[Frontend] Remove FrontendObserver

### PR DESCRIPTION
**Pull request by hamishknight**
It only has two clients, `swift-ast-script` and `swift-remoteast-test`. The former can be modified to use its own `CompilerInstance`, and the latter can use a callback on `performFrontend` instead.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please smoke test

**Comment by hamishknight** [comment]
Ah damn just saw https://github.com/apple/swift/pull/24917, there may still be external clients depending on these...

**Comment by CodaFi** [comment]
Yeah, we shouldn't remove these. It might also be useful in the future to formalize the side effects that hang off the frontend pipeline with this class.

**Comment by hamishknight** [comment]
Hmm okay yeah, I'll close this for now and perhaps re-visit it when we have a clearer picture of what the inverted pipeline will look like (and the degree to which normal frontend invocations will use it).

**Pull request closed without merging**
