### PR TITLE
[GPE] Make TF infinite-loop error more user-friendly

### PR DESCRIPTION
**Pull request by rxwei**
```swift
import TensorFlow
func foo() {
  var t: Tensor<Float> = [[1.0, 2.0]]
  var i = 0
  repeat {
    t += t + t
  } while i < 10
}
foo()
```

Previously this test would yield the following error:
```console
test.swift:6:9: error: Cannot partition function '$S4test3fooyyF' -- is there an infinite loop?
          t += t + t
               ^
```

This is confusing because the function name is a SIL name, the term "partitioning" is an implementation detail, and the source location is a rather random AST node within the loop. This patch moves the source loc to the function declaration and makes the error messages a bit more user-friendly.

After the patch:
```console
test.swift:2:6: error: Functions containing infinite loops are not supported by TensorFlow yet
func foo() {
     ^
```

### CODE REVIEW

**Comment by rxwei** [comment]
Getting the AST location of the `while`/`repeat` loop would be nice too, but it seems that the previous implementation based on `pred`'s location does not always work. This can be improved later.

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by mhong** [comment]
The new error message is nicer! I'm fine with this change, but I'm curious in what cases do the SILLocation of `pred` not work here? For a large function, it'd be useful to pinpoint where the infinite loop is (if that's not too hard).

**Review by mhong — APPROVED** [review]

**Comment by mhong** [comment]
Could this be related to https://bugs.swift.org/browse/SR-8309?

**Comment by rxwei** [comment]
I’ll send a follow up patch to find the AST node of the loop and display the diagnostic there.

**Comment by mhong** [comment]
When looking into sil loc, it might be useful to tackle it along with a more general form of infinite loop (beyond a self loop). See https://bugs.swift.org/browse/SR-8251 and https://github.com/apple/swift/pull/17897 for context. I'd be happy to take on this, or support you there if you want to take a look first.

**Pull request merged**
