### PR TITLE
WinSDK: add Shell32

### PR DESCRIPTION
**Pull request by dduan**
This header and .lib features useful APIs such as [SHFileOperation](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shfileoperationw), which seems to be the preferred way to manipulate file systems for certain things.

### CODE REVIEW

**Comment by dduan** [comment]
@swift-ci smoke test

**Comment by dduan** [comment]
@swift-ci smoke test

**Comment by dduan** [comment]
@swift-ci smoke test Windows Platform

**Comment by dduan** [comment]
smoke test Linux Platform

**Review by compnerd — COMMENTED** [review]
Hmm, I'm wondering if we want to rename the old module or not.  The original module is the lightweight Shell API, and this is the full one.  Either way, as long as it builds, this seems reasonable, but I would like to test the build locally, since we're missing coverage on Foundation :(. I learnt the hard way with the last rebranch.

**Comment by dduan** [comment]
ah. The only test I ran locally is modifying the installed .modulemap and use one of the APIs in the local build. It appeared to have worked well.

**Comment by dduan** [comment]
@swift-ci smoke test Linux Platform

**Review by compnerd — APPROVED** [review]
Seems that I can build Foundation with this change just fine.  Still not sure about how to best handle the lightweight vs full API surface for shell, but that can be improved as a follow up.

**Comment by compnerd** [comment]
@swift-ci please smoke test Linux platform

**Pull request merged**
