### PR TITLE
Update build.ps1 for installer changes for VCRuntime dlls

### PR DESCRIPTION
**Pull request by tristanlabelle**
Build script counterpart to https://github.com/apple/swift-installer-scripts/pull/256

### CODE REVIEW

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/256

@swift-ci please build toolchain Windows platform

**Comment by tristanlabelle** [comment]
This failed because the list of redist files varies per toolchain version. The fix will be to harvest the directory. Working on this
```
Build FAILED.

       "C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift-installer-scripts\platforms\Windows\bundle\installer.wixproj" (default target) (1:7) ->
       "C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift-installer-scripts\platforms\Windows\rtl\msi\rtlmsi.wixproj" (default target) (4:5) ->
       (CoreCompile target) -> 
         C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift-installer-scripts\platforms\Windows\rtl\msi\rtlmsi.wxs(49): error WIX0103: Cannot find the File file 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Redist\\MSVC\\14.34.31931\\x64\\Microsoft.VC143.CRT\\vcruntime140_threads.dll'. The following paths were checked: C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Redist\\MSVC\\14.34.31931\\x64\\Microsoft.VC143.CRT\\vcruntime140_threads.dll [C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift-installer-scripts\platforms\Windows\rtl\msi\rtlmsi.wixproj]

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/256

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/256

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
@swift-ci please test

**Pull request merged**
