### PR TITLE
stdlib: Code size improvements for Dictionary for -Osize

### PR DESCRIPTION
**Pull request by eeckstein**
The first change is to remove some @inline(__always) attributes. Those were added before we had the guaranteed-by-default calling convention. They are not necessary anymore.

The second change is to not specialize some slow-path functions. This results that no specialization code for these functions is generated at the client side. Instead those functions are directly called in the libSwiftCore.
Note that Key-related hash and equality comparisons are still specialized, because otherwise the performance hit for Osize would be too big.

Some Dictionary benchmarks regress a bit with -Osize, but the code size wins are big.

rdar://problem/46534453

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by lorentey** [comment]
Hm; I wonder if some of these would better be implemented by moving methods that don't depend on Key/Value to a non-generic _CoreNativeDictionary struct.

**Comment by eeckstein** [comment]
As I see it, all of the functions I annotated depend on the Value type.
In general, it's an interesting idea, because you probably could make such functions resilient without hurting performance.

**Comment by aroben** [comment]
Any idea what's causing the two -O performance regressions? Is it the removal of `@inline(__always)`?

And the -O code size regressions seem particularly surprising, given that this change should produce less code, not more.

**Comment by eeckstein** [comment]
The -O regressions could be noise (I didn't see them when running the benchmarks locally), e.g. because of different code alignment.
The -Osize regressions are because we now execute generic code instead of specialized code.
I experimented a lot to keep those regressions in an acceptable range. For example, Key-type related functions (e.g. lookup) are still specialized. Otherwise the regressions would be really bad.

**Comment by aroben** [comment]
Any idea what's going on with the "Code size: -O" regressions? For example, `DictionaryKeysContains.o` got about 2KB bigger.

**Comment by eeckstein** [comment]
This is a result of different inlining decisions

**Review by airspeedswift — APPROVED** [review]

**Pull request merged**
