### PR TITLE
[no-implicit-copy] A few small fixes.

### PR DESCRIPTION
**Pull request by gottesmm**
In this PR, I am fixing a few small things from the review + a few cleanups of my own. Specifically:

1. I removed the move only bit from TypeLowering. We don't need this yet (and may not at all). So I am removing it.
2. I renamed the no implicitcopy tests from move_only_checker_* -> noimplicitcopy*. Even though the checker is the move only checker, we are testing noimplicitcopy functionality. So I think it makes more sense.
3. In order to make sure that we don't silently fail to match a mark_must_check, I changed the move checker to emit a diagnostic error that says that it did not know how to check a noimplicitcopy. This is better than not emitting anything or crashing.
4. I am going to in a little bit push to this branch a few refactorings to slim down the move checker into a few parts (too much work goes on in 1 function). I am still refactoring though.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@jckarter I got rid of the type lowering moveonly bit in this PR.

**Comment by gottesmm** [comment]
@swift-ci test macOS platform

**Review by jckarter — APPROVED** [review]

**Comment by jckarter** [comment]
Thanks!

**Pull request merged**
