### PR TITLE
[Documentation] Add missing 'of' to UnicodeScalar documentation.

### PR DESCRIPTION
**Pull request by Jnosh**
Just a small documentation typo fix.

### CODE REVIEW

**Comment by CodaFi** [comment]
While you're here, there's [one more](https://github.com/Jnosh/swift/blob/637d2d7af170977a43836905b0b91e7b83d86a6b/stdlib/public/core/UnicodeScalar.swift#L324) of this specific kind of typo that you can fix.

**Comment by Jnosh** [comment]
Thanks for pointing that out!

I added that fix to this PR and a similar typo in a code comment as well.

**Comment by natecook1000** [comment]
@swift-ci Please smoke test and merge

**Comment by CodaFi** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
