### PR TITLE
[silopt] Wire up the SerializeSIL pass pipeline so we always serialize at -O even if we don't run all or a subset of the passes.

### PR DESCRIPTION
**Pull request by gottesmm**

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Review by aschwaighofer — APPROVED** [review]
lgtm

**Comment by gottesmm** [comment]
The linux build failed in sourcekit-lsp test. I don't think that can result from this. Trying again.

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Pull request merged**
