### PR TITLE
[DebugInfo] Salvage debug info for allocations in SILSROA

### PR DESCRIPTION
**Pull request by Snowy1803**
Debug Value instructions pointing to an allocation split by SILSROA were dropped. This PR fixes this by recreating debug values for each new allocation introduced by SILSROA. Also, when an empty struct or tuple is split, a debug value of undef is emitted in place of the allocation and the previous debug values, to avoid losing track of the 0-size variable.

Some SILOptimizer SILSROA tests were emitting empty debug values, and then used a CHECK-NEXT, which fails when they are recovered. We already have SILSROA DebugInfo tests to ensure the pass works with debug values, so there is no need to test with impossible debug values.

This increases the number of variables in the standard library by 1%.

### CODE REVIEW

**Comment by Snowy1803** [comment]
@swift-ci please test

**Review by adrian-prantl — APPROVED** [review]

**Comment by adrian-prantl** [comment]
I am very confused by this test failure.

**Comment by adrian-prantl** [comment]
@swift-ci test macos

**Comment by adrian-prantl** [comment]
@swift-ci test macosx

**Comment by adrian-prantl** [comment]
@swift-ci smoke test

**Comment by Snowy1803** [comment]
@swift-ci please smoke test linux platform
smoke test macOS platform

**Comment by Snowy1803** [comment]
@swift-ci please smoke test Linux platform

**Comment by Snowy1803** [comment]
@swift-ci please smoke test macOS platform

**Pull request merged**
