### PR TITLE
[Sema] @_exported imports reexport @_spi decls as they reexport APIs

### PR DESCRIPTION
**Pull request by xymus**
Enable transitive imports of all SPI groups through @_exported imports. This brings to SPI the same behavior we already have for API.

```swift
// Module A
@_spi(S) public func foo() {}

// Module B
@_exported import A

// Module C
@_spi(S) import B

foo() // SPI imported through the reexport of A from B
```

rdar://101566534

### CODE REVIEW

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Review by elsh — APPROVED** [review]
lgtm

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by xymus** [comment]
@swift-ci Please smoke test macOS

**Pull request merged**
