### PR TITLE
Updating usage of SanitizerCoverage.

### PR DESCRIPTION
**Pull request by plotfi**
SanitizerCoverage has changed from createSanitizerCoverageModulePass to createModuleSanitizerCoverageLegacyPassPass + createSanitizerCoverageLegacyPassPass

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @bob-wilson @dcci

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
Seems like an infrastructure failure:

```
-- Found PythonInterp: /usr/local/bin/python3.7 (found version "1.4") 
CMake Error at CMakeLists.txt:655 (message):
  Python 2.7 or newer is required


-- Configuring incomplete, errors occurred!
See also "/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master-next/buildbot_incremental/llvm-macosx-x86_64/CMakeFiles/CMakeOutput.log".
See also "/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master-next/buildbot_incremental/llvm-macosx-x86_64/CMakeFiles/CMakeError.log".-- Found PythonInterp: /usr/local/bin/python3.7 (found version "1.4") 
CMake Error at CMakeLists.txt:655 (message):
  Python 2.7 or newer is required


-- Configuring incomplete, errors occurred!
See also "/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master-next/buildbot_incremental/llvm-macosx-x86_64/CMakeFiles/CMakeOutput.log".
See also "/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master-next/buildbot_incremental/llvm-macosx-x86_64/CMakeFiles/CMakeError.log".
```

**Comment by compnerd** [comment]
CC: @shahmishal

**Comment by shahmishal** [comment]
@gottesmm might be able to help here, he has been watching `master-next` branch

**Comment by plotfi** [comment]
What is going on with this infra? This I figured would be a pretty trivial change.

**Comment by shahmishal** [comment]
master-next branch looks to be broken - https://ci.swift.org/view/swift-master-next/job/oss-swift-incremental-RA-osx-master-next/4849/console

**Comment by compnerd** [comment]
@shahmishal yeah, seems like it is failing to find the right python?  Did python get upgraded to 3 perhaps?

**Comment by shahmishal** [comment]
```
-- Found PythonInterp: /usr/local/bin/python3.7 (found version "1.4") 
CMake Error at CMakeLists.txt:655 (message):
  Python 2.7 or newer is required
```
This does not make sense, it found 3.7 but it needs 2.7 or newer?

**Comment by compnerd** [comment]
Right, the error message is poor.  It means that it needs `python[>=2.7&<3]`.

**Comment by plotfi** [comment]
What is the version of python on the build servers here? Can we just modify the build script to handle this and work around the breaking infra in this case?

**Comment by plotfi** [comment]
@shahmishal @compnerd is the infra working again? It’s been several days at this point

**Comment by milseman** [comment]
CC @gottesmm for ideas

**Comment by compnerd** [comment]
Spoke with Mishal offline about this.  Lets get this merged since the build is currently broken, and this looks correct.  Lets get this merged for now.

**Comment by plotfi** [comment]
@compnerd @shahmishal thank you!

**Pull request merged**
