### PR TITLE
[AutoDiff] Clean up differentiation-related attributes.

### PR DESCRIPTION
**Pull request by dan-zheng**
- Unify syntax for `@differentiating` and `@transposing` attributes:
  `DerivativeRegistrationAttributeArguments`.
- Remove obsolete `linear` flag from `@differentiating` attribute.
  The `@transposing` attribute is now used for transpose registration.
- Unify parsing diagnostics.
- Unify duplicated parsing `errorAndSkipToEnd` logic.
  - Create a shared `errorAndSkipUntilConsumeRightParen` helper and use it when
    parsing `@differentiating` and `@transposing` attribute to improve (reduce)
    diagnostics.
- Minor formatting changes.

---

Todos:
- Upstream changes to previously upstreamed code, e.g. `Parser::parseDifferentiationParametersClause`.
- TF-991: deprecate `@differentiating` and rename to `@derivative(of:)`.
- TF-992: deprecate `@transposing` and rename to `@transpose(of:)`.

### CODE REVIEW

**Comment by dan-zheng** [comment]
Verifying that tests pass.
@swift-ci Please test tensorflow

**Review by rxwei — APPROVED** [review]

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Pull request merged**
