### PR TITLE
build-script: Run lldb tests for Swift support per-commit

### PR DESCRIPTION
**Pull request by vedantk**
- Side-step code signing issues by using the system debug server

- Skip testing categories that add minimal coverage-per-unit-time

- Only enable testing from the whitelisted `swiftpr` category

rdar://35534424

- Using CMake to build lldb has been deferred until r://37130314 is addressed

### CODE REVIEW

**Comment by vedantk** [comment]
@swift-ci Please smoke test

**Review by dcci — APPROVED** [review]
LGTM once we get the swift-lldb bots fully green

**Comment by vedantk** [comment]
Right, we'll need to deal with the test failures related to String layout (rdar://36744510) and stale module caches first (https://reviews.llvm.org/D42277).

**Review by shahmishal — APPROVED** [review]
LGTM

**Comment by shahmishal** [comment]
Thanks @vedantk!

**Comment by vedantk** [comment]
@swift-ci Please smoke test

**Comment by vedantk** [comment]
@swift-ci Please smoke test

**Comment by vedantk** [comment]
@swift-ci Please test

**Comment by vedantk** [comment]
@swift-ci Please smoke test macOS platform

**Comment by shahmishal** [comment]
@swift-ci please smoke test macOS

**Comment by vedantk** [comment]
As-is, this might introduce too much of a delay for swift PR testing. I'm working on a change to limit the tests run and will update the PR when that's done.

**Comment by vedantk** [comment]
@swift-ci Please smoke test

**Comment by vedantk** [comment]
@swift-ci Please smoke test

**Comment by vedantk** [comment]
Excellent, just 22 minutes on the macOS tester.

**Comment by vedantk** [comment]
Once https://github.com/apple/swift-lldb/pull/296 lands, this can go in.

**Comment by vedantk** [comment]
@swift-ci smoke test and merge

**Comment by vedantk** [comment]
@swift-ci Please smoke test

**Comment by vedantk** [comment]
Ouch, LLDB_BUILD_FRAMEWORK is not supported on CMake < 3.7.

**Comment by vedantk** [comment]
@swift-ci Please smoke test

**Pull request merged**
