### PR TITLE
Enable inlining of generics

### PR DESCRIPTION
**Pull request by swiftix**
Enable inlining of generics by default.

Add profitability heuristic tweaks for generic functions
- This should limit uncontrolled code size growth.

Transparent and always inline generic functions are now always inlined.

### CODE REVIEW

**Comment by swiftix** [comment]
@swift-ci Please smoke test

**Comment by swiftix** [comment]
The failure is related to the debug info emission by IRGen. It is tracked by rdar://28859432

**Comment by swiftix** [comment]
@swift-ci Please smoke test

**Comment by swiftix** [comment]
@swift-ci Please smoke test

**Comment by swiftix** [comment]
@swift-ci Please smoke test

**Comment by swiftix** [comment]
@adrian-prantl Hmm. This PR still fails https://ci.swift.org/job/swift-PR-osx-smoke-test/4408/console, even though your recent changed are merged. Could you have a look?

**Comment by swiftix** [comment]
@swift-ci Please smoke test

**Comment by adrian-prantl** [comment]
The problem here is that there is a SILFunction with a nullptr DeclContext. The function is a protocol witness.

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by adrian-prantl** [comment]
Can you try replacing a479f91 with:

diff --git a/lib/IRGen/IRGenSIL.cpp b/lib/IRGen/IRGenSIL.cpp
index d3edda3249..706578d643 100644
--- a/lib/IRGen/IRGenSIL.cpp
+++ b/lib/IRGen/IRGenSIL.cpp
@@ -731,19 +731,33 @@ public:
     copy.push_back(alloca.getAddress());
   }
 
+  /// Determine whether a generic variable has been inlined.
+  static bool isInlinedGeneric(VarDecl *VarDecl, const SILDebugScope *DS) {
+      if (!DS->InlinedCallSite)
+        return false;
+      if (VarDecl->hasType())
+        return VarDecl->getType()->hasArchetype();
+      return VarDecl->getInterfaceType()->hasArchetype();
+  }
+  
   /// Emit debug info for a function argument or a local variable.
   template <typename StorageType>
   void emitDebugVariableDeclaration(StorageType Storage,
                                     DebugTypeInfo Ty,
                                     SILType SILTy,
                                     const SILDebugScope *DS,
-                                    ValueDecl *VarDecl,
+                                    VarDecl *VarDecl,
                                     StringRef Name,
                                     unsigned ArgNo = 0,
                                     IndirectionKind Indirection = DirectValue) {
     // Force all archetypes referenced by the type to be bound by this point.
     // TODO: just make sure that we have a path to them that the debug info
     //       can follow.
+
+    // FIXME: The debug info type of all inlined instances of a variable must be
+    // the same as the type of the abstract variable.
+    if (isInlinedGeneric(VarDecl, DS))
+      return;
+
     auto runtimeTy = getRuntimeReifiedType(IGM,
                                            Ty.getType()->getCanonicalType());
     if (!IGM.IRGen.Opts.Optimize && runtimeTy->hasArchetype())
@@ -3753,6 +3767,10 @@ void IRGenSILFunction::visitAllocBoxInst(swift::AllocBoxInst *i) {
         CurSILFn->getDeclContext(), Decl,
         i->getBoxType()->getFieldType(IGM.getSILModule(), 0).getSwiftType(),
           type, /*Unwrap=*/false);
+
+    if (isInlinedGeneric(Decl, i->getDebugScope()))
+      return;
+
     IGM.DebugInfo->emitVariableDeclaration(
         Builder,
         emitShadowCopy(boxWithAddr.getAddress(), i->getDebugScope(), Name, 0),

**Comment by slavapestov** [comment]
```
+      if (VarDecl->hasType())
+        return VarDecl->getType()->hasArchetype();
+      return VarDecl->getInterfaceType()->hasArchetype();
```

hasArchetype() is always false on an interface type, you want to call hasTypeParameter() instead. Also, you can ignore VarDecl->getType() altogether. Only look at interface types.

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please benchmark OS X

**Comment by swiftix** [comment]
@swift-ci please benchmark OS X

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
I fixed the most of the performance issues with benchmarks. The -Onone regressions were mostly due to iron generation of pre-specializaitons. The remaining few regressions seem to be due to different inlining decisions being taken. We can tweak it over time.

**Comment by swiftix** [comment]
@swift-ci please test OS X

**Comment by swiftix** [comment]
@swift-ci please test OS X

**Comment by swiftix** [comment]
@swift-ci please clean test OS X

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by jrose-apple** [comment]
You don't need to ask for another test for "wrong SHA" failures.

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by jrose-apple** [comment]
This seems to be causing issues on the full-build bots ([here](https://ci.swift.org/job/oss-swift_tools-RA_stdlib-RDA_long-test/1586/), [here](https://ci.swift.org/job/oss-swift_tools-RA_stdlib-RD_test-simulator/2704/), etc). Can you look into this now, or should I revert the PR for the time being?

**Comment by jrose-apple** [comment]
Spoke to Roman via messenger. I'm going to revert this to get the bots unblocked. He and @adrian-prantl are looking into the failures.

**Pull request merged**
