### PR TITLE
cmake: Add ``-Fsystem ${SDK_PATH}/System/Library/PrivateFrameworks`` for overlays builds.

### PR DESCRIPTION
**Pull request by erg**

### CODE REVIEW

**Comment by erg** [comment]
@swift-ci Please smoke test

**Review by jrose-apple — APPROVED** [review]

**Comment by erg** [comment]
@swift-ci Please smoke test

**Comment by erg** [comment]
@swift-ci Please smoke test and merge

**Comment by erg** [comment]
@swift-ci Please smoke test and merge

**Comment by erg** [comment]
Fixes rdar://problem/31308670

**Pull request merged**
