### PR TITLE
[AddressLowering] Set the right yield operand.

### PR DESCRIPTION
**Pull request by nate-chandler**
Rather than always setting the 0th operand of a yield instruction, set the operand at the index of the original operand.

Based off https://github.com/apple/swift/pull/61924

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by atrick — APPROVED** [review]
huh... right on

**Comment by nate-chandler** [comment]
@swift-ci please test macOS platform

**Comment by nate-chandler** [comment]
@swift-ci please test

**Pull request merged**
