### PR TITLE
[ConstraintSystem] Fix crash on function conversion reliant on conditional conformance

### PR DESCRIPTION
**Pull request by theblixguy**
This PR fixes a compiler crasher related to a function conversion reliant on conditional conformance. Example:

```swift
protocol P {}
struct S<T> {}
extension S : P where T : P {}

func foo(_ fn: (S<String>) -> Void) {}
func bar(_ fn: (P) -> Void) {
  foo(fn)
}
```

Resolves [SR-10992](https://bugs.swift.org/browse/SR-10992).

### CODE REVIEW

**Comment by theblixguy** [comment]
cc @xedin

**Review by xedin — COMMENTED** [review]
@theblixguy Could you please convert example from validation test to the one which checks produces diagnostic? Also I think there are probably more places which could benefit from using this new method, at least CSDiagnostics probably should.

How about adding new `getConstraintLocator` method to `FailureDiagnostic` itself to avoid unnecessary indirection?

**Comment by theblixguy** [comment]
@xedin Do you mean you want the exact same method in `FailureDiagnostic` as well (which would then internally call `CS.getConstraintLocator(anchor, path, flags)`)?

**Comment by xedin** [comment]
@theblixguy Yes, I think it could be done separately but it would make sense to call it on `FailureDiagnostic` instead of current indirect way. At least it would be great to audit where `summaryFlags` is set to `0` at the moment and change that here.

**Comment by theblixguy** [comment]
@xedin Okay, I have added it to FailureDiagnostic! Found two more uses of `summaryFlags` being `0` which I removed.

**Review by xedin — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test

**Comment by theblixguy** [comment]
All tests have passed! I'll cherry pick this to 5.1 if that's okay?

**Comment by xedin** [comment]
@theblixguy Sounds good, thanks!

**Pull request merged**
