### PR TITLE
[CMake] Quote use of SWIFT_PATH_TO_LIBDISPATCH_SOURCE

### PR DESCRIPTION
**Pull request by smeenai**
If the variable is empty, expanding it without quoting can end up with
invalid CMake syntax. We get away with it here because of how the if
happens to be structured, but adding an OR clause after the EXISTS
clause would expose the issue, for example.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by smeenai** [comment]
CC @compnerd @gottesmm @jrose-apple

**Comment by compnerd** [comment]
*shrug*

**Comment by compnerd** [comment]
@swift-ci please smoke test and merge

**Comment by compnerd** [comment]
@swift-ci please smoke test macOS

**Pull request merged**
