### PR TITLE
[5.1] [Serialization] Teach serialization to get a generic signature from opaque types

### PR DESCRIPTION
**Pull request by harlanhaskins**
Description: Fixes incorrect serialization of opaque return types for @inlinable code, and teaches serialization how to deserialize a generic signature from an opaque result type.

Scope of the issue: This prevents returning opaque result types from some @inlinable declarations when in incremental mode

Risk: Low, the patch ensures we start a cross-reference correctly regardless if the return type of a function is an opaque return type, and that we're able to deserialize it

Testing: Manually compiling projects using SwiftUI with @inlinable declarations and CI testing of reduced reproduction cases.

Reviewed-by: @jckarter 

Radar: rdar://53958358

### CODE REVIEW

**Comment by harlanhaskins** [comment]
@swift-ci please test

**Comment by harlanhaskins** [comment]
@swift-ci please test

**Comment by harlanhaskins** [comment]
@swift-ci please nominate

**Comment by harlanhaskins** [comment]
@tkremenek Looks like we never got this in. Can you approve this PR as well? (We pulled PR #27141 into swift-5.1-branch-08-28-2019)

**Comment by harlanhaskins** [comment]
@tkremenek Ping

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
