### PR TITLE
Fix Mem2Reg for enum stack locations

### PR DESCRIPTION
**Pull request by meg-gupta**
We complete lifetimes of enums in mem2reg since address forms may be incomplete on non payloaded paths and promoting them to value form can cause ownership verification errors. This was done per stack allocation. This is an issue since same value maybe stored on multiple stack locations and can use insertion of the lifetime end on blocks where the lifetime was previously completed by the utility.

Move lifetime completion to the end of mem2reg to not run into this.

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test

**Review by eeckstein — APPROVED** [review]
lgtm

**Comment by meg-gupta** [comment]
This change is problematic when an  enum value in `initializationPoint` of a stack allocation is stored and loaded from another stack allocation that will also be deleted by mem2reg.

**Pull request closed without merging**
