### PR TITLE
[stdlib] Revert count(where:)

### PR DESCRIPTION
**Pull request by airspeedswift**
This is causing performance problems in the type checker currently, due to conflicts with `Collection.count`. Temporarily reverting until we can resolve the issue.

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please smoke test

**Comment by khanlou** [comment]
Ah, this is a shame — let me know if there's anything I can do to help!

**Comment by jpsim** [comment]
I'd be interested to know why this happens for `Collection.count`/`Sequence.count(where:)` but not `Sequence.first`/`Sequence.first(where:)`.

**Comment by xedin** [comment]
I am sure that performance is degraded for first and and count, we just didn’t yet observe it in practice probably because they are used less in conjunction with operators...

**Comment by Wdtwsm777** [comment]
> This is causing performance problems in the type checker currently, due to conflicts with `Collection.count`. Temporarily reverting until we can resolve the issue.

**Pull request merged**
