### PR TITLE
Unicode experimentation

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
CC: @drexin @tbkka @tachoknight

**Comment by tbkka** [comment]
Ooooh...  This is exciting!

**Comment by compnerd** [comment]
Please test with following PRs:
apple/llvm-project#1445

@swift-ci please test Linux platform

**Comment by compnerd** [comment]
Please test with following PRs:
apple/llvm-project#1445

@swift-ci please test Linux platform

**Comment by compnerd** [comment]
Please test with following PRs:
apple/llvm-project#1445

@swift-ci please test Linux platform

**Pull request closed without merging**
