### PR TITLE
[stdlib] Make all the stdlib APIs `@_inlineable`

### PR DESCRIPTION
**Pull request by moiseev**
This change in theory should allow us to remove a special stdlib-only
sil-serialize-all compilation mode.

<rdar://problem/34138683>

### CODE REVIEW

**Comment by moiseev** [comment]
/cc @slavapestov and @swiftix 
Meanwhile, I will go and resolve the conflicts...

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
@swift-ci Please smoke benchmark

**Comment by moiseev** [comment]
@swift-ci Please Test Source Compatibility

**Comment by slavapestov** [comment]
Thanks! I'll take a look at the bugs you found along the way later tonight.

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by gparker42** [comment]
So the plan is to add @_inlineable everywhere, then audit everything later to correct ABI stability?

**Comment by moiseev** [comment]
@gparker42 that's the plan, yes.

**Comment by swiftix** [comment]
@swift-ci Please test

**Comment by swiftix** [comment]
@moiseev Could you update the PR and resolve the conflicts?

**Comment by moiseev** [comment]
@swift-ci Please test Linux platform

**Comment by swiftix** [comment]
@swift-ci  please test Linux platform

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
@swift-ci Please test Linux platform

**Comment by swiftix** [comment]
Having issues when compiling with this PR and disabling `-sil-serialize-all`.

@slavapestov @aschwaighofer I filed a couple of radars about the issues I face. Please check your mail ;-)

**Comment by aschwaighofer** [comment]
@swiftix The issue with memcpy is not an IRGen issue. If you use llvm intrinsics you get what you asked for ...

For whatever reason, Int32()._value no longer boils down to a constant. Easy fix is just to use zero (or one; same effect both mean no alignment) here.  Writing 0 or 1 might be less obtuse anyway ...

I might be worthy to figure out whether we expect Int32()._value to boil down to a constant and why this does not happen anymore. But that has nothing to do with IRGen.

```
  Builtin.int_memcpy_RawPointer_RawPointer_Int64(
    dest, src, size,
    /*alignment:*/ Int32()._value,
    /*volatile:*/ false._value)
```

**Comment by moiseev** [comment]
Resolving conflicts.
@swift-ci Please test

**Comment by moiseev** [comment]
@swift-ci Please clean build Linux platform

**Comment by moiseev** [comment]
Attn. @swiftix 
@swift-ci Please test

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
@swift-ci Pleas esmoke benchmark

**Comment by moiseev** [comment]
@swift-ci Please smoke benchmark

**Comment by moiseev** [comment]
@swift-ci Please Test Source Compatibility

**Comment by moiseev** [comment]
@swift-ci Please smoke benchmark

**Comment by moiseev** [comment]
@swift-ci Please Test Source Compatibility

**Comment by moiseev** [comment]
@swift-ci Please smoke benchmark

**Comment by gottesmm** [comment]
@moiseev Congrats!

**Comment by jrose-apple** [comment]
Looks like this busted up the resilience bot pretty bad: https://ci.swift.org/job/oss-swift_tools-RA_stdlib-RDA_test-macos-resilience/59/. @moiseev, are you going to have time to fix this or should I revert for now?

**Comment by moiseev** [comment]
@jrose-apple Working on a fix. @swiftix identified the problem.

**Comment by jrose-apple** [comment]
Thanks, just doing my build-czar-ly rounds.

**Pull request merged**
