### PR TITLE
[SR-615][Compiler] Don't error when lexing UTF-8 BOM

### PR DESCRIPTION
**Pull request by tanadeau**

### CODE REVIEW

**Comment by lattner** [comment]
Thanks for tackling this, some comments:
- The patch will have the check be performed once per token lexed, it would make more sense for this to happen once per source file.  As such, please move this to Lexer::Lexer or perhaps Lexer::primeLexer.
- Please include a test case.

Thanks!

**Comment by lattner** [comment]
FWIW, the analogous code in clang is here:
https://github.com/apple/swift-clang/blob/stable/lib/Lex/Lexer.cpp#L68

**Comment by tanadeau** [comment]
I moved the check to the Lexer's constructor and added a test case.

**Comment by lattner** [comment]
LGTM, thanks!

**Pull request merged**
