### PR TITLE
Look at code size/perf impact of disabling speculative devirtualization.

### PR DESCRIPTION
**Pull request by gottesmm**
@airspeedswift @aschwaighofer

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci test compiler performance

**Comment by gottesmm** [comment]
For those listening in, I think polymorphic calls was the original benchmark that inspired this optimization.

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
