### PR TITLE
SILGen: Support multiple-entry case blocks with address-only bindings

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes <rdar://problem/27863650>, <rdar://problem/28170927>, <https://bugs.swift.org/browse/SR-2555>, <rdar://problem/30870493>, <https://bugs.swift.org/browse/SR-4163>.

### CODE REVIEW

**Comment by slavapestov** [comment]
Getting there...

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by gregomni** [comment]
I think this also ought to fix https://bugs.swift.org/browse/SR-2555 - I'll tie those two bugs together as related.

**Comment by slavapestov** [comment]
@gregomni Thanks! That's the same exact bug, just the example uses generic parameters and not existentials. I'll close both out when I merge this.

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Pull request merged**
