### PR TITLE
Remove typeCheckExpressionShallow()

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Review by xedin — COMMENTED** [review]
Awesome! I was wondering if shallow _really_ necessary...

**Comment by rudkx** [comment]
Nice cleanup!

**Comment by slavapestov** [comment]
I’ve merged everything here except for the last usage which was in string interpolation. That still needs a bit of work to fix a diagnostics regression.

**Comment by rudkx** [comment]
@slavapestov Is this worth keeping open until you take a look at the string interpolation usage?

**Pull request closed without merging**
