### PR TITLE
Fix symbolicate linux fatal for streaming stacktraces 2

### PR DESCRIPTION
**Pull request by gmilos**
`symbolicate-linux-fatal` doesn't handle series of stack-traces properly. Only the first one is symbolicated OK. More details:
https://bugs.swift.org/browse/SR-7651

It turns out it was a simple setup issue, where File Addr vs Phys Addr (a.k.a.` text_section.GetFileAddress() - text_section.GetFileOffset()`) were only properly considered on the first iteration.

This is a reworked and updated version of: #16494

### CODE REVIEW

**Comment by alblue** [comment]
@swift-ci please smoke test

**Comment by gmilos** [comment]
@swift-ci please smoke test

**Comment by gmilos** [comment]
@swift-ci please smoke test

**Comment by gmilos** [comment]
@swift-ci please smoke test

**Pull request merged**
