### PR TITLE
SILCombiner: Fix partial_apply optimization of @callee_guaranteed closures

### PR DESCRIPTION
**Pull request by aschwaighofer**
@callee_guaranteed closure contexts must not be released when replacing
a closure application.

SR-5441
rdar://33255593

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test

**Comment by gottesmm** [comment]
Can you use emitDestroyValueOperation? Then when we update SILCombine for ownership this will just work.

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test and merge

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test and merge

**Pull request merged**
