### PR TITLE
[IRGen & Runtime] Remove prefab'ed VWT for reference storage types

### PR DESCRIPTION
**Pull request by davezarzycki**
This also adds missing value witness symbols for reference storage types that now allow optional user facing types.

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please test

**Comment by eeckstein** [comment]
What's the motivation for using meta programming here?

**Comment by davezarzycki** [comment]
Hi @eeckstein – This meta-programming logic should have been a part of #16237, but it was overlooked. The short summary is that adding new reference storage types involves a lot of boilerplate. Meta-programming allows Swift to decouple policy from implementation, and let researchers like myself spend more time experimenting and less time fixing merge conflicts in the implementation. Also, by meta-programming the reference storage types, some bugs were fixed along the way.

**Comment by eeckstein** [comment]
I was asking because IMO this change actually makes things more complicated instead of easier, especially given that currently it only effects 2 storage types.
But I see that you already did the same in other parts of the compiler and it was already discussed in the other PR. So I'm fine with that.

**Review by eeckstein — DISMISSED** [review]
lgtm

**Comment by rjmccall** [comment]
I feel like adding this new level of metaprogramming isn't really adding much right now.

What do we even use these value witnesses for?

**Comment by davezarzycki** [comment]
Hi @rjmccall – I'm not sure what these value witnesses are used for. All I know is that the following won't compile at the moment due to a missing value witness table:
```
public class Foo<T> {
  unowned var other: Foo<T>?
}
```
If not generating these value witness tables is an option, then great!

**Comment by rjmccall** [comment]
I think they're only currently used by EmitTypeLayoutRef::visitReferenceStorageType.  A lot of that code looks suspect, and it looks like there are a lot more cases than just optional-`unowned` references that we aren't prefabbing witnesses for.  Since reference storage types are always fixed-layout, I suggest just deleting the whole method and all the corresponding prefab VWTs for `weak`/`unowned` types in the runtime.

@jckarter Agreed?

**Comment by jrose-apple** [comment]
A struct containing a single weak or unowned reference is the current simplest workaround for having an Array of weak or unowned things. It's probably not the ideal behavior of a weak array, but it does work.

**Comment by rjmccall** [comment]
I agree that we could use prefab value witnesses for that, but I don't think we actually do.  And there's actually quite a lot of combinations here that we would have to provide prefab VWTs for, between different refcounting schemes and different reference storage kinds, and a lot of potential to screw up a corner case.

**Comment by davezarzycki** [comment]
Hi @rjmccall – I've repurposed this pull request to test your proposal. I've removed `EmitTypeLayoutRef::visitReferenceStorageType()` and adjusted the runtime and test suite accordingly. Questions for you or @jckarter:

1) `unowned(safe)` behaves differently for `AnyObject` and unknown objects with ObjC interop enabled. The former allows zero extra inhabitants, whereas the latter allows one. Is this expected?
2) `unowned(safe)` with `AnyObject` or unknown objects are bitwise takable when "native", but not when ObjC interop is enabled. Is this expected?
3) How does what ask CI to test the source compatibility for code size?

@swift-ci please test

**Comment by rjmccall** [comment]
1. There is no good reason for `AnyObject` and unknown object to have different extra-inhabitant counts.
2. Yes.  `unowned(safe)` references are implemented using `weak` references for non-Swift references, and we want to give that implementation a lot of flexibility.
3. You mean, the code-size impact of the PR on the compatibility suite?  That is a really good question; I don't know the answer.  @eeckstein?

**Comment by davezarzycki** [comment]
One more question: if the code size impact is acceptable, can we merge this? Or do we need to sort out why `AnyObject` and unknown object have different extra inhabitant counts under ObjC interop first?

**Comment by eeckstein** [comment]
It's: swift-ci Please test compiler performance
See https://github.com/apple/swift/blob/master/docs/ContinuousIntegration.md

**Comment by davezarzycki** [comment]
@swift-ci please test compiler performance

**Comment by rjmccall** [comment]
I think we can merge this, but would you mind investigating that bug next?

**Comment by davezarzycki** [comment]
@rjmccall – In short, yes, I'll look into it. Is it urgent or blocking anything?

**Comment by rjmccall** [comment]
Well, it's an ABI bug, but no, I don't think it's blocking anything.

**Comment by davezarzycki** [comment]
Hey @rjmccall – So `unowned(safe)` reference storage types are interesting/weird. Native unowned objects use the loadable logic and are allowed to have extra inhabitants, but unknown unowned objects use the address-only logic and that currently don't allow extra inhabitants (regardless of the reference storage type). Is this a bug?

**Comment by rjmccall** [comment]
Oh, there's some sub-optimality here because we don't necessarily know whether the `unowned(safe) NativeRefCountableType` we're looking at is a substitution of `unowned(safe) T` and therefore has to be ABI-compatible with code that's treating the reference as unknown-refcountable.  So we actually need to be using the same conservative extra-inhabitants rules for all types.

In principle we could optimize that by picking a different ReferenceStorageType in SIL type lowering based on the abstraction pattern of the original `unowned` variable, and then just preserve that through substitutions all the way down into IRGen.

**Comment by davezarzycki** [comment]
Hey @rjmccall and @eeckstein have any idea why the perf test failed? I see lots of unrelated errors like: ```package at '/Users/buildnode/jenkins/workspace-private/swift-PR-compiler-performance-macOS/project_cache/URBNJSONDecodableSPM' requires a minimum Swift tools version of 4.0.0 (currently 3.1.0)```

On the hope that the errors were spurious, let's try again:
@swift-ci please test compiler performance

Separately, I think I'm going to need to create a follow up bug to track the oddities we're observing here because I don't feel confident about fixing them. In the mean time, I'm going to create a pull request to fix some bugs in the meta-programmed reference storage type logic found during source inspection.

**Comment by davezarzycki** [comment]
@swift-ci please test compiler performance

**Comment by davezarzycki** [comment]
Never mind, I found and fixed the ObjC `AnyObject` versus archetype of AnyObject extra inhabitant bug. Please see the second commit where address-only reference storage types are taught about optionality.

@swift-ci please test

**Comment by davezarzycki** [comment]
@swift-ci please test compiler performance

**Comment by davezarzycki** [comment]
@eeckstein – What's going on with the perf test suite failing?

@rjmccall – In the mean time, are you okay with merging now and reverting if there is a regression?

**Comment by davezarzycki** [comment]
I've rebased this pull request. Let's see if that makes the perf test suite finish with results.

@swift-ci please test compiler performance

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Review by rjmccall — APPROVED** [review]
Yeah, LGTM.

**Comment by davezarzycki** [comment]
Sure

**Pull request merged**
