### PR TITLE
[stdlib]Add benchmark for strings with long shared prefixes

### PR DESCRIPTION
**Pull request by lancep**
As per Michael's suggestion in https://github.com/apple/swift/pull/13217, this is a benchmark that exercises the path for long, shared prefixes

### CODE REVIEW

**Comment by lancep** [comment]
@swift-ci please benchmark

**Comment by lancep** [comment]
@swift-ci please benchmark

**Comment by lancep** [comment]
@swift-ci please benchmark

**Comment by lancep** [comment]
@swift-ci please smoke test and merge

**Comment by lancep** [comment]
CC @milseman FYI

**Comment by milseman** [comment]
Could you make sure it's not totally trivial, that is either use the `count` or, better yet, feed the comparison result into `blackHole`?

**Comment by lancep** [comment]
@swift-ci please benchmark

**Comment by lancep** [comment]
@swift-ci please benchmark

**Comment by lancep** [comment]
@swift-ci please smoke test and merge

**Comment by lancep** [comment]
@swift-ci please smoke test and merge

**Comment by lancep** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
