### PR TITLE
Trimming metadata

### PR DESCRIPTION
**Pull request by jckarter**
Sundry changes that together shave about half a megabyte off the dylibs in a relwithdebinfo build.

### CODE REVIEW

**Comment by slavapestov** [comment]
Nice!

65,536 generic parameters ought to be enough for anybody, right?

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Comment by lattner** [comment]
Is a variable size ULEB style encoding reasonable here, or do you want fixed sizes to allow indexing across these records?

**Comment by jckarter** [comment]
The old data structures in Swift 4 and before had the same limit and nobody seemed to notice. These sizes aren’t particularly speed sensitive so we could reserve space for larger argument counts if we really needed to.

**Comment by lattner** [comment]
I don't care about > 64K.  I was suggestion variable size so that the vastly most common case only uses one byte :)

**Comment by jckarter** [comment]
That'd be clever. Going from 32 -> 16 bits only really saved 4KB across the stdlib and overlays, so we'd see at most another 2KB benefit in return.

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Pull request merged**
