### PR TITLE
Use dedicated expressions for bridging conversions

### PR DESCRIPTION
**Pull request by rjmccall**

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Comment by rjmccall** [comment]
@swift-ci Please smoke test OS X.

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Comment by DougGregor** [comment]
@swift-ci please test macOS

**Comment by rjmccall** [comment]
@swift-ci Please test and merge

**Comment by rjmccall** [comment]
@swift-ci Please test and merge

**Comment by rjmccall** [comment]
@swift-ci Please test and merge

**Pull request merged**
