### PR TITLE
Mark the Dispatch classes as a new kind of "foreign" class.

### PR DESCRIPTION
**Pull request by jrose-apple**
Progress on rdar://problem/26850367, which is that Swift will happily let you extend the new Dispatch classes but then fails to find the symbols at link-time.

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by jrose-apple** [comment]
@slavapestov @rjmccall Just the groundwork so far, but any comments? I'll be doing the functional change tomorrow.

@ everyone else: more detail in the commit mesasge.

@swift-ci Please test

**Comment by slavapestov** [comment]
Looks good to me, thanks for working on this!

While I appreciate the desire to audit all call sites of isForeign(), it does seem like keeping it around as as synonym for getForeignClassKind() != ForeignClassKind::Normal might be a good idea.

**Comment by slavapestov** [comment]
Also I see you removed the foreign bit from the module format, presumably because we never serialize foreign classes. Might be nice to assert that this is the case, too.

**Comment by jrose-apple** [comment]
Yeah, unless @rjmccall feels strongly I'll probably put back `isForeign` for almost all of them. Some of them really do work better checking for a CF type, though.

Re: assertion: https://github.com/apple/swift/pull/3253/files#diff-6b91911d460e26cbbc8876d758503512R2313

**Comment by slavapestov** [comment]
Oh, oops, I missed that :-)

**Comment by rjmccall** [comment]
Looks like a reasonable approach to me.

**Comment by jrose-apple** [comment]
Okay, fully implemented, in case either of you want to review the actual change.

@swift-ci Please test

**Pull request merged**
