### PR TITLE
[benchmark] More StringBuilder/Interpolation benchmarks

### PR DESCRIPTION
**Pull request by milseman**
In preparation for evaluating small string performance tradeoffs, add a few explicitly small/large benchmark workloads

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please smoke benchmark

**Comment by milseman** [comment]
@shahmishal Have you seen this before:
```
<unknown>:0: error: no such file or directory: '/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/llbuild-macosx-x86_64/products/llbuildSwift/CMakeFiles/BuildSystemBindings.swift.o'
```
?

@swift-ci please test OS X Platform

**Comment by shahmishal** [comment]
Failure is related to https://github.com/apple/swift/pull/14914

**Pull request merged**
