### PR TITLE
[libSyntax] JSON serialization improvements

### PR DESCRIPTION
**Pull request by ahoppen**
This PR adds incorporates two changes that significantly speed up the serialization time of JSON from C++:
- Make `key` a `StringRef`
  - Most keys are string literals and if they are converted directly to StringRef, the string length can be computed at compile time, increasing
performance.
- Introduce `ScalarReferenceTraits`
  - For ScalarTraits, a buffer was always created on the heap to which the scalar string value was written just to be copied to the output buffer again. In case the value already exists in a memory buffer it is way cheaper to avoid the heap allocation and copy the string straight to the output buffer.
- Minimise String escapes
  - For several enums we know that they never contain characters that need to be escaped, thus we can just skip the escaping which needs to walk the entire string and just add the quotes around the string statically.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Review by harlanhaskins — APPROVED** [review]
LGTM.

Interesting to see a `const StringRef &` I’m the original code, IIRC StringRef is usually meant to be passed by value because it’s just a pointer and length

**Review by rintaro — APPROVED** [review]
LGTM. Just be aware that we want to port `json` back to `llvm` repo. https://bugs.swift.org/browse/SR-6891 .

**Comment by ahoppen** [comment]
@rintaro I believe that the YAML serialiser would probably also benefit from my improvements. Assuming that it's got a very similar architecture.

**Pull request merged**
