### PR TITLE
Fake PR commit

### PR DESCRIPTION
**Pull request by bcardosolopes**
Fake commit msg

### CODE REVIEW

**Comment by bcardosolopes** [comment]
Please test with following pull request:
https://github.com/apple/swift-clang/pull/306

@swift-ci Please clean test Linux platform

**Comment by bcardosolopes** [comment]
Please test with following pull request:
apple/swift-clang#306

@swift-ci Please ASAN test

**Comment by bcardosolopes** [comment]
@swift-ci Please test Linux platform

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by CodaFi** [comment]
I figure we probably don't need this anymore.

**Pull request closed without merging**
