### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by benrimmington**
Follow-up to <https://github.com/apple/swift/pull/24080>

### CODE REVIEW

**Comment by benrimmington** [comment]
Cc: @slavapestov

**Comment by slavapestov** [comment]
Oops, apparently I’m really bad at this. Thanks for fixing up my mess.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Comment by benrimmington** [comment]
@jckarter @slavapestov I've resolved a conflict, and added another missing reference.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Pull request merged**
