### PR TITLE
ExplicitModuleLoader: take a JSON file that specifies details of explicit Swift modules

### PR DESCRIPTION
**Pull request by nkcsgexi**
Instead of taking paths of Swift module files from front-end command line
arguments, we should take a JSON file specifying details of explicit modules.
The advantages is (1) .swiftdoc and .swiftsourceinfo can be associated
with a .swiftmodule file, and (2) module names are explicitly used as
keys in the JSON input so we don't need to eagerly deserialize a .swiftmodule
file to collect the module name.

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Comment by nkcsgexi** [comment]
@swift-ci Please smoke test Linux platform

**Comment by compnerd** [comment]
@nkcsgexi - this seems to have caused a regression on the windows CI: https://ci-external.swift.org/job/oss-swift-windows-x86_64-vs2019/1770/consoleText 

Could you please take a look?

**Comment by nkcsgexi** [comment]
@compnerd ah, Will do. Thanks for pinging!

**Pull request merged**
