### PR TITLE
[nfc][opts] Add a few pretty-stack traces to performance diagnostics.

### PR DESCRIPTION
**Pull request by zoecarver**
It can be very hard to debug (from a compiler engineers perspective) why the perforamnce diagnostics aren't allowing a certain pattern. Usually this means adding a bunch of random SIL dumps to debug. With these stack traces, you can now just add `-Xllvm -swift-diagnostics-assert-on-error=1` and the stack dumps will do the rest.

### CODE REVIEW

**Comment by zoecarver** [comment]
@swift-ci please smoke test

**Review by eeckstein — APPROVED** [review]
lgtm.
BTW, I always debug this in a debugger where I can see the stack trace.

**Comment by zoecarver** [comment]
@swift-ci please smoke test linux platform

**Comment by zoecarver** [comment]
@swift-ci please smoke test linux

**Comment by zoecarver** [comment]
@swift-ci please smoke test

**Comment by zoecarver** [comment]
@swift-ci please smoke test linux

**Pull request merged**
