### PR TITLE
GenericSpecializer: use an alternative mangling if the function has re-abstracted resilient type parameters.

### PR DESCRIPTION
**Pull request by eeckstein**
If the specialized function has re-abstracted (= converted from indirect to direct) resilient argument or return types, use an alternative mangling: "TB" instead of "Tg".
Resilient parameters/returns can be converted from indirect to direct if the specialization is created within the type's resilience domain, i.e. in its module (where the type is loadable).
In this case we need to generate a different mangled name for the specialized function to distinguish it from specializations in other modules, which cannot re-abstract this resilient type.

This fixes a miscompile resulting from ODR-linking specializations from different modules, which in fact have different function signatures.

https://bugs.swift.org/browse/SR-13900
rdar://71914016

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by eeckstein** [comment]
@swift-ci smoke test linux

**Comment by shahmishal** [comment]
@swift-ci smoke test linux

**Comment by shahmishal** [comment]
@swift-ci smoke test linux

**Comment by shahmishal** [comment]
@swift-ci smoke test linux

**Comment by shahmishal** [comment]
@swift-ci smoke test Linux

**Comment by shahmishal** [comment]
@swift-ci smoke test Linux

**Comment by shahmishal** [comment]
@swift-ci smoke test Linux

**Comment by eeckstein** [comment]
@swift-ci smoke test Linux

**Pull request merged**
