### PR TITLE
Don't interleave parsing with type checking for the main file

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes <https://bugs.swift.org/browse/SR-284>, <https://bugs.swift.org/browse/SR-4426>.

### CODE REVIEW

**Comment by davidungar** [comment]
Yes! Make this work, please! :)

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
Note that the regression tests are for unrelated bugs, but I'm saving CI cycles

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Pull request merged**
