### PR TITLE
[Macros] Emit plugin dependencies to loaded module trace.

### PR DESCRIPTION
**Pull request by rxwei**
Emit plugins loaded with `-load-plugin-library` to loaded module trace.

Resolves rdar://102212316.

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]

**Comment by rxwei** [comment]
@swift-ci please smoke test

**Comment by rxwei** [comment]
@swift-ci please smoke test

**Comment by rxwei** [comment]
@swift-ci please smoke test

**Comment by rxwei** [comment]
@swift-ci please smoke test

**Comment by rxwei** [comment]
@swift-ci please smoke test

**Comment by rxwei** [comment]
@swift-ci please smoke test

**Comment by rxwei** [comment]
@swift-ci please smoke test linux

**Review by artemcm — APPROVED** [review]

**Pull request merged**
