### PR TITLE
[NFC] Sema: Internalize the use of UnboundGenericType in applyUnboundGenericArguments

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
Further progress will be unlocked with #32116

### CODE REVIEW

**Review by slavapestov — APPROVED** [review]

**Review by CodaFi — APPROVED** [review]

**Review by xedin — APPROVED** [review]

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test and merge

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test and merge

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test Linux

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test Linux

**Pull request merged**
