### PR TITLE
Fix Windows build for #29289

### PR DESCRIPTION
**Pull request by hamishknight**
MSVC appears to require the template parameters be explicitly specified here.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please smoke test

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Comment by hamishknight** [comment]
@swift-ci Please test Windows platform

**Comment by hamishknight** [comment]
Superseded by https://github.com/apple/swift/pull/29386

**Comment by compnerd** [comment]
@hamishknight - actually, if this is up already, the question is, is the tighter friendship correct?  If so, I think that this should supersede #29386

**Comment by hamishknight** [comment]
@compnerd IMO the looser friendship makes more sense, `ActiveRequest` is already friends with `AnyRequest`, and if we were to add more subclasses, it would probably make sense to generalise `isStorageEqual` across them (which would likely require friendship with all base class specialisations).

**Comment by hamishknight** [comment]
@swift-ci please smoke test

**Comment by hamishknight** [comment]
@swift-ci Please test Windows platform

**Comment by hamishknight** [comment]
@swift-ci please smoke test

**Comment by hamishknight** [comment]
@swift-ci Please test Windows platform

**Comment by hamishknight** [comment]
@swift-ci please test Windows platform

**Comment by hamishknight** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please clean test Windows platform

**Comment by compnerd** [comment]
really triggering a build you cannot trigger: https://dev.azure.com/compnerd/swift-build/_build/results?buildId=24862&view=results

**Comment by compnerd** [comment]
Still fails: https://dev.azure.com/compnerd/swift-build/_build/results?buildId=24862&view=logs&j=0e514031-a9b0-5d19-4075-e5711178f10f&t=6491fbec-4801-5529-2943-0955e3c2f90f&l=4851

**Comment by compnerd** [comment]
I think that we should revert it until we can properly fix this

**Comment by hamishknight** [comment]
@compnerd Okay yup, I'm fine with that

**Pull request closed without merging**
