### PR TITLE
Further progress towards incomplete type metadata

### PR DESCRIPTION
**Pull request by rjmccall**

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Comment by rjmccall** [comment]
@swift-ci Please smoke test OS X.

**Comment by rjmccall** [comment]
Build failure is a time-out with no errors visible in the log, which is why I'm dropping to a smoke test.

**Comment by rjmccall** [comment]
@swift-ci Please test and merge.

**Comment by rjmccall** [comment]
@swift-ci Please test and merge.

**Comment by rjmccall** [comment]
Linux didn't like the interesting atomic type.

**Comment by rjmccall** [comment]
@swift-ci Please test and merge.

**Comment by rjmccall** [comment]
@swift-ci Please test and merge.

**Comment by rjmccall** [comment]
@swift-ci Please test and merge.

**Comment by rjmccall** [comment]
Wait, how are Slava's commits being reported as part of this PR?

**Comment by rjmccall** [comment]
Argh, I feel like that's something I need to fix.  I'll let the OS X tests complete, and assuming they succeed, I'll rebase and do a smoke test.

**Comment by rjmccall** [comment]
Oh right, I had it as merge. :)

**Comment by rjmccall** [comment]
@slavapestov I apologize for whatever happened here.

**Comment by rjmccall** [comment]
I think I did too deep of a rebase.  I'm surprised that github just accepted it, though.

**Comment by slavapestov** [comment]
It’s OK. Those were pretty good bug fixes, applying them twice can’t hurt.

**Pull request merged**
