### PR TITLE
[5.9] Limit loading error when importing a module with package name built from interface

### PR DESCRIPTION
**Pull request by elsh**
Cherry-pick of https://github.com/apple/swift/pull/65481 & https://github.com/apple/swift/pull/65855

Explanation: Previously a diagnostic was added to show an error when loading a module with package name if it was built from interface. It was expected if the file being built is a .swift file. If it's an interface, however, it should not throw an error (since interface files do not contain `package` symbols unless inlinable or usableFromInline). The change in this PR adds the check and was previously merged to main (Ref: rdar://108633068). This PR needs to be in 5.9 as it happens to fix a blocker for adoption of the `package` access modifier: the error occurs during a build that runs api-digester which treats the source as an interface, leading to a build failure.  

Scope: Unblocks building Swift projects containing `package` access modifier that run api-digester.
Issue: rdar://108945440
Risk: Low. The change is minimal as it checks the source kind before throwing an error.
Testing: Tests were added to ensure that it does not throw an error if the source kind is interface.
Reviewer: @xymus @tshortli @nkcsgexi

### CODE REVIEW

**Comment by elsh** [comment]
https://github.com/apple/swift/pull/65481 main

**Comment by elsh** [comment]
@swift-ci smoke test

**Comment by elsh** [comment]
@swift-ci smoke test

**Review by xymus — APPROVED** [review]
It looks good!

**Comment by elsh** [comment]
@swift-ci smoke test

**Review by nkcsgexi — APPROVED** [review]
Thank you, Ellie!

**Comment by elsh** [comment]
@swift-ci smoke test

**Comment by elsh** [comment]
@swift-ci smoke test

**Comment by elsh** [comment]
@swift-ci test

**Pull request merged**
