### PR TITLE
WIP DO NOT MERGE: Primary files mode refactoring setup review fixes rebased

### PR DESCRIPTION
**Pull request by davidungar**
In midst of fixing up my PR; had to rebase to latest master.

### CODE REVIEW

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Comment by davidungar** [comment]
@swift-ci please smoke test OS X platform

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Comment by davidungar** [comment]
@swift-ci please smoke test OS X Platform

**Comment by davidungar** [comment]
@swift-ci please smoke test OS X Platform

**Comment by davidungar** [comment]
@swift-ci please clean smoke test OS X Platform

**Comment by davidungar** [comment]
@swift-ci please clean smoke test OS X Platform

**Comment by shahmishal** [comment]
@davidungar ci.swift.org is down for maintenance, it will be back online soon.

**Comment by shahmishal** [comment]
@swift-ci please clean smoke test OS X Platform

**Comment by shahmishal** [comment]
@swift-ci please clean smoke test OS X Platform

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Pull request closed without merging**
