### PR TITLE
Respect SWIFT_STDLIB_SINGLE_THREADED_RUNTIME and use nonatomic refcounting in swift_retain, swift_release, etc.

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Review by mikeash — APPROVED** [review]

**Review by gottesmm — APPROVED** [review]
LGTM. Thanks Kuba!

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Review by compnerd — APPROVED** [review]

**Pull request merged**
