### PR TITLE
[Serialization] Minor ModuleFile/ModuleFileSharedCore improvements

### PR DESCRIPTION
**Pull request by rintaro**
* Add properties to `ModuleFile` that hold some informations from the control block.
* ~`ExtendedValidationInfo` parameter for `ModuleFileSharedCore::load()` cannot be `nullptr`. Make it non-defaulted Rvalue reference.~
* Remove `ExtendedValidationInfo` parameter from `ModuleFileSharedCore::load()`. Now that all required information can be fetched from `ModuleFile`.

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by akyrtzi** [comment]
It's a bit unclear to me why we need the bits accessible from both `ModuleFile` and `ExtendedValidationInfo`.
You are replacing the accesses from `ExtendedValidationInfo` with accesses from `ModuleFile` but then why do we need them in `ExtendedValidationInfo` and if we do need them, why add the accessors in `ModuleFile` and not initialize the `ExtendedValidationInfo` bits from the `Core` object?

**Comment by rintaro** [comment]
These bits are not actually needed in `ExtendedValidationInfo` because other users don't use them. [But when reading `OPTIONS_BLOCK` inside `CONTROL_BLOCK`](https://github.com/apple/swift/blob/ca721677e8443904b67e180eb3e7ff89c74f3547/lib/Serialization/ModuleFileSharedCore.cpp#L87-L89), `ExtendedValidationInfo` is the only thing to store the informations. So we need to initialize `ExtendedValidationInfo` first, then read bits from it to initialize `ModuleFileSharedCore`.

**Comment by rintaro** [comment]
Added another commit to remove `ExtendedValidationInfo` parameter from `ModuleFileSharedCore::load()`. Any of callers don't use it.

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by akyrtzi** [comment]
Nice improvement to avoid passing `ExtendedValidationInfo` to so many APIs!
Is `ExtendedValidationInfo` still usable from other places or can it be moved to implementation detail of `ModuleFileSharedCore`?

**Comment by rintaro** [comment]
`getSDKPath()` and `getExtraClangImporterOptions()` still has some users which directly call `validateControlBlock()`.

**Review by akyrtzi — APPROVED** [review]

**Pull request merged**
