### PR TITLE
 Runtime: Don't attempt to round-trip mangled names for private types.

### PR DESCRIPTION
**Pull request by jckarter**
By design, we don't want private or function-nested types to be accessible by mangled name, since they don't have stable identities, and they could inadvertently become ABI if someone serialized a mangled string and expected to deserialize it into a type. Fixes rdar://problem/39826794 .

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
Private class names, at least, unfortunately *do* need to be stable, because nothing stopped you from archiving one in Swift 3. But local names, definitely.

**Comment by jckarter** [comment]
We'll still use the old remangler for ObjC runtime class names. This is only for the new mangler, which has AFAIK never been exposed to any persistence API.

**Review by mikeash — COMMENTED** [review]
Looks good. And thanks for adding the newline.

**Pull request merged**
