### PR TITLE
Driver: add support for baremetal targets

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by artemcm — APPROVED** [review]

**Comment by etcwilde** [comment]
heh, this looks an awful lot like https://github.com/apple/swift/pull/35970

**Comment by compnerd** [comment]
I had a look at the failure, I’ll upload a fix later today.

**Comment by compnerd** [comment]
Updated #35970; lets see if this makes it through this time!

**Comment by kubamracek** [comment]
https://github.com/apple/swift/pull/35970 is now merged, awesome, thanks! :)

**Pull request closed without merging**
