### PR TITLE
[sil] Now that we aren't using mark-uninitialized-fixup anywhere, remove it.

### PR DESCRIPTION
**Pull request by gottesmm**
Nothing like paying down technical debt in order to help write another optimization/feature = ).

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by gottesmm** [comment]
Failure was some test in SourceKit, IDE-ish land.

**Comment by atrick** [comment]
Thanks

**Pull request merged**
