### PR TITLE
[5.5][Refactoring] Avoid redeclarations or shadowing in async refactored code

### PR DESCRIPTION
**Pull request by bnbarham**
Cherry-picking https://github.com/apple/swift/pull/37302

-----

When converting a call or function, rename declarations such that
redeclaration errors and shadowing are avoided. In some cases this will
be overly conservative, but since any renamed variable can be fixed with
edit all in scope, this is preferred over causing redeclaration errors
or possible shadowing.

Resolves rdar://73973517

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
@swift-ci please test Linux platform

**Comment by bnbarham** [comment]
Another spurious failure..

@swift-ci please test Linux platform

**Comment by bnbarham** [comment]
@swift-ci please nominate

--- CCC ---

Explanation: When performing the convert to async refactoring (whether on a call or function), declarations are hoisted out of the closure and into the parent scope. This can introduce potential redeclarations and/or shadowing. It's also actually a common occurrence in completion handler code - nested calls often have the same name closure argument names, eg. "res"/"result".

This change renames the declarations in hoisted code so that redeclarations/shadowing are avoided. 

Radar/SR Issue: rdar://73973517

Risk: Low - only affects the async refactoring

Testing: Added new test cases to the refactoring test suite

**Review by airspeedswift — APPROVED** [review]

**Pull request merged**
