### PR TITLE
[Diagnostics] Require explicit releasenone.

### PR DESCRIPTION
**Pull request by nate-chandler**
Functions which which consume their arguments will release them on any branches where the arguments are unused.  Users of `@_effects(readnone)` and `@_effects(readonly)` may not consider this when annotating their functions.  Require that functions annotated thus are also annotated @_effects(releasenone).

In order to support this, adjust SILFunctionBuilder to allow distinct non-custom effects and to interpret such "conflicting" guarantees to provide the strongest guarantee.  For example, annotating a function both `@_effects(readnone)` and `@_effects(releasenone)` is equivalent to only annotating it `@_effects(readnone)`.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
These diagnostics are raised when reading the swiftinterface in the SDK.  One solution would be to make them warnings:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/lib/swift/Swift.swiftmodule/x86_64-apple-macos.swiftinterface:21053:15: error: annotation implies no releases, but consumes parameter 'stringInterpolation'
  @inlinable @_effects(readonly) public init(stringInterpolation: Swift.DefaultStringInterpolation) {
              ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/lib/swift/Swift.swiftmodule/x86_64-apple-macos.swiftinterface:21053:46: note: parameter 'stringInterpolation' defined here
  @inlinable @_effects(readonly) public init(stringInterpolation: Swift.DefaultStringInterpolation) {
                                             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/lib/swift/Swift.swiftmodule/x86_64-apple-macos.swiftinterface:21053:15: note: add explicit @_effects(releasenone) if this is intended
  @inlinable @_effects(readonly) public init(stringInterpolation: Swift.DefaultStringInterpolation) {
              ^
                                @_effects(releasenone)
```

**Review by atrick — APPROVED** [review]
This looks great to me!

@rjmccall  I suggested that programmers can only use `_effects(readonly)` on consuming arguments if they also explicitly declare `_effects(releasenone)`. Nate added a nice diagnostics that warns them of the danger.

I explained the issue here:

Document _effects(readonly) pitfalls #68287
https://github.com/apple/swift/pull/68287

```
In special situations, the library author may still want to use
`readonly` for functions with owned argument. They must be able to
guarantee that the owned arguments are not effectively released from
the caller's perspective. This could be because all paths through the
function have an equivalent retain, or they may know that the argument
is a tagged object for which a release has no effect. To make sure
this is intentional, the library author must also explicitly specify
`_effects(releasenone)`.
```

@Catfish-Man can you confirm that `releasenone` is in fact intentional in `SmallString.init()` where Nate added the effect in this PR.

**Comment by nate-chandler** [comment]
Downgraded to warnings.

@swift-ci please test

**Comment by nate-chandler** [comment]
Moved new diagnostics into `SILFunctionBuilder::addFunctionAttributes`.

@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
Similar infrastructure issue: `common.ExecuteCommandFailure: ExecuteCommandFailure(command="git -C /Users/ec2-user/jenkins/workspace/swift-PR-source-compat-suite-debug-macos/swift-source-compat-suite/project_cache/AsyncNinja clean -ffdx", returncode=1)`

@swift-ci Please Test Source Compatibility Debug

**Comment by nate-chandler** [comment]
@swift-ci please test

**Pull request merged**
