### PR TITLE
Bump compiler version to Swift 5.1

### PR DESCRIPTION
**Pull request by tkremenek**
Bump the Swift compiler version to 5.1 on `master` branch.

### CODE REVIEW

**Comment by tkremenek** [comment]
@swift-ci clean test

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by airspeedswift** [comment]
Temporarily reverting the `flatMap` obsolescence. I think this is still good to get in with this version, so we stay on the path to removing it entirely as it causes problems/confusion with diagnostics. But we can do that later once the version bump is properly settled in.

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
bah missed some other math obsoletions

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@swift-ci please test

**Pull request merged**
