### PR TITLE
FSO: Enable non-generic parameter optimization in generic function

### PR DESCRIPTION
**Pull request by trentxintong**

### CODE REVIEW

**Comment by trentxintong** [comment]
@jckarter what is the right way to check whether a function parameter is generic or not. The hasArchetype() check does not seem to handle this case  - _NativeSetStorage<τ_0_0>. i.e. it returns false for _NativeSetStorage<τ_0_0>.

**Comment by jckarter** [comment]
Check `hasTypeParameter` rather than `hasArchetype`.

**Comment by trentxintong** [comment]
@jckarter why am i gettting a non-null pointer when calling getStructOrBoundGenericStruct() on $_SliceBuffer<τ_0_0> ? should getStructOrBoundGenericStruct() return null in case its a unbound generic struct ?

**Comment by jckarter** [comment]
Is `_SliceBuffer` a struct? You can use `getAnyNominal` to get the NominalTypeDecl from an arbitrary nominal type.

**Comment by trentxintong** [comment]
%29 = struct $_SliceBuffer<Element> (%0 : $AnyObject, %1 : $UnsafeMutablePointer<Element>, %27 : $UInt, %6 : $Int), loc "/Volumes/Files/FSO/swift/stdlib/public/core/SliceBuffer.swift":28:5, scope 6 // users: %31, %32

**Comment by jckarter** [comment]
No, if it's a struct type it should give you the StructDecl.

**Comment by trentxintong** [comment]
OK. so if i want to bail on generic type. i should use hasTypeParameter on the SILType

**Comment by rjmccall** [comment]
Yes, if you want to bail on types that don't depend on any type parameters, that's the right thing to check.

**Pull request closed without merging**
