### PR TITLE
[CS] Emit syntactic diagnostics for for loop where clauses

### PR DESCRIPTION
**Pull request by hamishknight**
When moving the type-checking of for-in loops into the constraint system, we inadvertently stopped running the syntactic expression diagnostics for the where clause. Re-enable this diagnostic logic.

Resolves SR-13260
Resolves rdar://65903005

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Review by xedin — APPROVED** [review]
Looks great!

**Comment by hamishknight** [comment]
@xedin Worth a 5.3 cherry-pick?

**Comment by xedin** [comment]
I think it's okay to cherry-pick since this is mostly just moving existing logic around.

**Comment by hamishknight** [comment]
@swift-ci please test macOS

**Comment by hamishknight** [comment]
@swift-ci please clean test macOS

**Comment by hamishknight** [comment]
@swift-ci please clean test macOS

**Comment by hamishknight** [comment]
@swift-ci please clean test macOS

**Comment by hamishknight** [comment]
@swift-ci please test macOS

**Comment by hamishknight** [comment]
@swift-ci please smoke test macOS

**Comment by hamishknight** [comment]
@swift-ci please smoke test macOS

**Pull request merged**
