### PR TITLE
[ConstraintSystem] Look through l-value while checking whether dynami…

### PR DESCRIPTION
**Pull request by xedin**
…c key path is recursive

Fix a crash in dynamic member lookup attempting to recursively
lookup a member on the same base type.

The problem is related to `isSelfRecursiveKeyPathDynamicMemberLookup`
which failed to look through l-value wrapping base type on each side of
the comparison, that's important because it's possible to have l-value
mismatch due to the fact that implicit call always gets l-value base
type but actual subscript which triggered dynamic lookup might be r-value.

Resolves: [SR-11743](https://bugs.swift.org/browse/SR-11743)
Resolves: rdar://problem/57091169

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please smoke test

**Review by theblixguy — COMMENTED** [review]
Thanks for fixing my bug! IIRC there are a few dupes of this on JIRA with the same assertion failure.

**Comment by xedin** [comment]
@theblixguy No problem! Would really appreciate if you could help me find the dupes :)

**Comment by theblixguy** [comment]
I think one of them is linked to that ticket, I did a quick search but I can't find the dupes, but I do remember seeing a few crashes which were probably related to this. Maybe I was looking at something else. Anyway, I've run into this exact crash many times, so really happy to see it finally being fixed. Here's another test case that you can add (which causes the same crash, but doesn't use protocols or default implementation):


```swift
@dynamicMemberLookup
struct Foo {
  let value: Int

  subscript<T>(dynamicMember member: KeyPath<Self, T>) -> T {
    return self[keyPath: member]
  }
}
```

**Comment by xedin** [comment]
Thank you! We definitely want as many test-cases as possible! :)

**Comment by xedin** [comment]
Hm, looks like GitHub didn't pick up my new commit, I'll give it some time.

**Comment by xedin** [comment]
Ok, here we go.

**Comment by xedin** [comment]
@swift-ci please smoke test

**Pull request merged**
