### PR TITLE
[gardening] Adding some links to SIL files 

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
Just adding links to some referenced files to make navigating easier  and fixing a broken ref :))

### CODE REVIEW

**Comment by jrose-apple** [comment]
I don't know if this works if we actually sphinx-build the ReST, but it *is* useful within GitHub. What do you think, @atrick, @eeckstein?

**Comment by atrick** [comment]
Thanks, this works for me. I don't actually know how we're supposed to work on the docs locally and preview changes short of posting a PR.

**Comment by atrick** [comment]
@swift-ci smoke test.

**Comment by atrick** [comment]
@swift-ci smoke test and merge.

**Comment by LucianoPAlmeida** [comment]
Hey @atrick :))
Should this smoke test be run already?

**Comment by atrick** [comment]
@swift-ci smoke test and merge.

**Comment by LucianoPAlmeida** [comment]
Hey guys :)) @atrick @jrose-apple 
Since is just docs, the build should've pass right? Is there some issue with the CI? Or is something on my branch that merging master updates in will fix.

**Comment by atrick** [comment]
@swift-ci smoke test OS X platform.

**Comment by atrick** [comment]
Trying again...

**Pull request merged**
