### PR TITLE
(blocked) IRGen: Remove relative-reference-to-coalesceable-string workarounds for rdar://problem/22674524.

### PR DESCRIPTION
**Pull request by jckarter**
We now require a new enough version of ld for Darwin that this workaround should no longer be necessary.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test and merge

**Comment by jckarter** [comment]
@swift-ci Please test and merge

**Comment by jckarter** [comment]
Darn, looks like we hit a FIXME in the AArch64 backend:

https://github.com/apple/swift-llvm/blob/ba2d09cd11ccf976067ce8e2127ed57574221f39/lib/Target/AArch64/MCTargetDesc/AArch64MachObjectWriter.cpp#L256

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
Alas, looks like even if I work around the LLVM backend bug, there's a linker bug on arm64 too. rdar://problem/26840634

**Comment by stephentyrone** [comment]
Should this be closed?

**Comment by jckarter** [comment]
Yeah, it's probably bitrotted at this point.

**Pull request closed without merging**
