### PR TITLE
Update CHANGELOG for SE-0075

### PR DESCRIPTION
**Pull request by CodaFi**
Doing due diligence here.  

I want to try to delay merging this until I stabilize this feature and patch a few regressions that were introduced to make it easier to revert the feature if my efforts prove fruitless.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please smoke test.

**Comment by CodaFi** [comment]
@swift-ci please smoke test.

**Comment by slavapestov** [comment]
Should this go in now?

**Comment by rintaro** [comment]
https://bugs.swift.org/browse/SR-3438 is the blocker.

**Comment by CodaFi** [comment]
Scuttling this now that it has been reverted for inclusion later.

**Pull request closed without merging**
