### PR TITLE
[cxx-interop] Fix issue with layout of FRTs that contain base classes or un-importable members.

### PR DESCRIPTION
**Pull request by zoecarver**

### CODE REVIEW

**Comment by zoecarver** [comment]
This only fixes base classes. We still need to fix this case:

```
struct X {
  ~X() = delete;
};

struct
  __attribute__((swift_attr("import_reference")))
  __attribute__((swift_attr("retain:immortal")))
  __attribute__((swift_attr("release:immortal")))
Y {
 X x; int y;
};

func test(y: Y) -> CInt { y.y }
```

That will require some refactoring, though.

**Comment by zoecarver** [comment]
@swift-ci please test

**Comment by zoecarver** [comment]
@swift-ci please test source compatibility

**Comment by hyp** [comment]
LGTM!

**Comment by ktoso** [comment]
Resolves rdar://101092361

**Pull request merged**
