### PR TITLE
[CMake] Make INSTALL_IN_COMPONENT optional

### PR DESCRIPTION
**Pull request by bulbazord**
Several CMake functions (e.g. add_swift_target_library) take the option
`INSTALL_IN_COMPONENT`, specifying which swift component you want a target to be
associated with for the purposes of installation. However, there are several
instances where you want to add a library but never install them. The workaround
for this was to make the swift component `never_install`. Although this is kind
of a hack, it does work. However, I am in the process of adding CMake
targets for the components themselves so they can have installation targets.
Instead of propagating the `never_install` workaround, I think it would be
cleaner to make `INSTALL_IN_COMPONENT` optional and remove `never_install`
completely.

cc @compnerd @Rostepher @gottesmm

### CODE REVIEW

**Comment by xiaobai** [comment]
@swift-ci please smoke test

**Comment by xiaobai** [comment]
@swift-ci please smoke test

**Comment by xiaobai** [comment]
@swift-ci please smoke test

**Comment by xiaobai** [comment]
@swift-ci please smoke test

**Comment by Rostepher** [comment]
I'm not sure we should make this optional until the other work is complete. It's helpful to have the error when the install component is missing. Without that precondition it's possible to have install components go missing due to messy merge conflicts.

**Comment by xiaobai** [comment]
Fair enough. I can understand wanting to deal with and track down problems stemming from bad merges. I think for now I'll drop this and revisit it at a later time.

**Pull request closed without merging**
