### PR TITLE
[stdlib] Rearrange + on RangeReplaceableCollection/Sequence once again

### PR DESCRIPTION
**Pull request by moiseev**
Based on the discssion here https://github.com/apple/swift/pull/13697

### CODE REVIEW

**Comment by jrose-apple** [comment]
I'm still confused as to why we can't put the other one on RRC too, but sure.

**Comment by moiseev** [comment]
@jrose-apple The code that gets ambiguous is this: `[first] + rest`. Where `rest` is an `Array`. But, `[first]` is not strictly an array, it can also be a `Set`, which is not a `RRC`. Therefore, I think, ambiguity is between "set as Sequence + array as RRC" and "array as RRC and array as RRC".

**Comment by jrose-apple** [comment]
Hm. How is `rest + [last]` not equally ambiguous, then?

We won't pull the type "Set" out of thin air, and we *should* still default to Array as the default array literal type. So I'm not sure I buy this explanation.

What does `-Xfrontend -debug-constraints` say? cc @xedin

**Comment by moiseev** [comment]
> Hm. How is rest + [last] not equally ambiguous, then?

Maybe it is, but we don't have expression like this in the codebase.

**Comment by xedin** [comment]
@jrose-apple Looked it for a bit this morning, the other way around is also ambiguous in stdlib :)

```swift
/Users/xedin/work/swift/swift/stdlib/public/core/Codable.swift:2686:78: error: ambiguous use of operator '+'
        let context = DecodingError.Context(codingPath: container.codingPath + [key],
                                                                             ^
```

**Comment by moiseev** [comment]
After having discussed with @xedin we decided to merge this PR and then, when the ranking bug is fixed, move the last `+` overload from `Sequence` to `RangeReplaceableCollection`.

**Pull request merged**
