### PR TITLE
CI: attempt to fix the index for swift

### PR DESCRIPTION
**Pull request by compnerd**
The file endings matter for some of the tests.  Try a different approach
to refreshing the index.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @drodriguez

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci  please smoke test and merge

**Comment by compnerd** [comment]
@swift-ci  please smoke test and merge

**Comment by compnerd** [comment]
@swift-ci please smoke test and merge

**Comment by compnerd** [comment]
@swift-ci please smoke test Linux platform

**Comment by drodriguez** [comment]
I wonder if Jenkins can be setup to do the checkout for these jobs with the right options. It is out of our capabilities, but hopefully it is something that has to be done once and not more. Also, we might be at a point that it might be better to switch the VS2019 host to an specific job, to have a good signal in Windows again.

**Pull request merged**
