### PR TITLE
[NFC] Add one '-' to a line on OptimizationTips.rst to silence a complaint when building

### PR DESCRIPTION
**Pull request by davidungar**
Add one '-' to a line on OptimizationTips.rst to silence a complaint when building

### CODE REVIEW

**Comment by davidungar** [comment]
@swift-ci please smoke test and merge

**Comment by davidungar** [comment]
@swift-ci please smoke test linux platform

**Comment by gottesmm** [comment]
FYI: #30119

**Comment by gottesmm** [comment]
Going to take this since yours got through before mine.

**Pull request merged**
