### PR TITLE
Add DebugPrefixMap remapping back to module creation

### PR DESCRIPTION
**Pull request by DavidGoldman**
Same as #23602 but merging into master as well

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@compnerd Will this work for windows?

**Comment by DavidGoldman** [comment]
Hmm, seems to be an error with the test:

```
Script:
--
: 'RUN: at line 1';   rm -rf "/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/test-iphonesimulator-i386/DebugInfo/Output/debug_prefix_map.swift.tmp" && mkdir -p "/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/test-iphonesimulator-i386/DebugInfo/Output/debug_prefix_map.swift.tmp"
: 'RUN: at line 2';   /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/bin/swiftc -frontend -target i386-apple-ios7.0  -module-cache-path '/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/swift-test-results/i386-apple-ios7.0/clang-module-cache' -sdk '/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk' -swift-version 4   -emit-module-path /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/test-iphonesimulator-i386/DebugInfo/Output/debug_prefix_map.swift.tmp/Globals.swiftmodule /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/test/DebugInfo/Globals.swift
: 'RUN: at line 3';   env SDKROOT= '/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/bin/swiftc' -module-cache-path '/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/swift-test-results/i386-apple-ios7.0/clang-module-cache' -swift-version 4  -g -debug-prefix-map /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/test/DebugInfo=/var/empty -debug-prefix-map /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/test-iphonesimulator-i386/DebugInfo/Output/debug_prefix_map.swift.tmp=/var/empty /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/test/DebugInfo/debug_prefix_map.swift -I /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/test-iphonesimulator-i386/DebugInfo/Output/debug_prefix_map.swift.tmp -emit-ir -o - | '/usr/bin/python' '/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/utils/PathSanitizingFileCheck' --sanitize BUILD_DIR='/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64' --sanitize SOURCE_DIR='/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift' --use-filecheck '/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/llvm-macosx-x86_64/bin/FileCheck' /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/test/DebugInfo/debug_prefix_map.swift
--
Exit Code: 2

Command Output (stderr):
--
/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/test/DebugInfo/debug_prefix_map.swift:5:8: error: module 'Globals' was created for incompatible target i386-apple-ios7.0: /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/test-iphonesimulator-i386/DebugInfo/Output/debug_prefix_map.swift.tmp/Globals.swiftmodule
import Globals
       ^
FileCheck error: '-' is empty.
FileCheck command line:  /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/llvm-macosx-x86_64/bin/FileCheck /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/test/DebugInfo/debug_prefix_map.swift

--
```

any idea how I can fix?

**Comment by adrian-prantl** [comment]
`%swiftc_driver` does not expand to include a target triple. Can you use one of the %target-swift expansions instead?

**Comment by compnerd** [comment]
@adrian-prantl - I *think* that it should - clang does have similar functionality that does work on Windows

**Comment by DavidGoldman** [comment]
Thanks, should be good now.

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by DavidGoldman** [comment]
Looks to have failed due to an unrelated SPM `clibc` module import error: 

```
<unknown>:0: warning: missing submodule 'clibc'
/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/swiftpm/Sources/SPMLibc/libc.swift:17:19: error: no such module 'clibc'
@_exported import clibc
                  ^
--- bootstrap: error: build failed with exit status 1
```

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by DavidGoldman** [comment]
Looks like another unrelated failure:

```
FAIL: Swift(watchsimulator-i386) :: PrintAsObjC/accessibility.swift (9738 of 11842)
******************** TEST 'Swift(watchsimulator-i386) :: PrintAsObjC/accessibility.swift' FAILED ********************
```

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Pull request merged**
