### PR TITLE
[LookupVisibleDecls] Look through DynamicSelfType in meta type lookup

### PR DESCRIPTION
**Pull request by rintaro**
We need to unwrap DynamicSelfType to get the visible decls on the meta type.

rdar://problem/58778439

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
This is fine, but please add a test case. I'm hoping that one day we can scrap LookupVisibleDecls and merge it with the normal qualified lookup path, so at this point, the test cases have more long term value than the code itself :-)

**Comment by rintaro** [comment]
Ah, I forgot to `git add` the test cases 🤔

**Review by slavapestov — APPROVED** [review]
Approved on the condition that you add a (passing) test case :-)

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Pull request merged**
