### PR TITLE
experiment

### PR DESCRIPTION
**Pull request by slavapestov**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test compiler performance

**Comment by slavapestov** [comment]
@swift-ci Please smoke benchmark

**Review by xedin — COMMENTED** [review]
This is awesome! I should really take a better look at what is going on in CSApply...

**Comment by rudkx** [comment]
@xedin there's a lot going on in there, and when I was working on IUOs I noticed a lot of opportunities for ~~rewriting it~~ small targeted refactorings

**Pull request closed without merging**
