### PR TITLE
[5.2] SR-7732: Dynamic casting CFError to Error results in a memory leak (from #28686)

### PR DESCRIPTION
**Pull request by tbkka**
The special handling for casting CFError/NSError to Swift Error
type was using cleanup code that didn't correctly handle this case.
This replaces the cleanup code with a more targeted version.

Resolves SR-7732
Resolves rdar://40423061

### CODE REVIEW

**Comment by tbkka** [comment]
Cherry-picking from #28686

**Comment by tbkka** [comment]
@swift-ci Please test Linux

**Comment by tbkka** [comment]
@swift-ci Please test macOS

**Review by DougGregor — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
