### PR TITLE
[swift-reflection-dump] Turn --binary-filename into a positional argu…

### PR DESCRIPTION
**Pull request by adrian-prantl**
…ment.

I mostly find it annoying to type and this makes the usage of the tool more consistent with other similar tools like dwarfdump or otool.

### CODE REVIEW

**Review by mikeash — APPROVED** [review]
Good move.

Any chance we have other users that this might break? It might be worth accepting both forms, but I'm guessing the automated uses are confined to these tests.

**Comment by adrian-prantl** [comment]
Maybe I'm misjudging the popularity of swift-reflection-dump but I thought all users of the tool are already on the reviewers list :-)

**Comment by mikeash** [comment]
You are probably right! I'm fine with making this change as-is, and if it turns out it breaks someone else, we can tell them how to fix their stuff.

**Review by artemcm — APPROVED** [review]

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Pull request merged**
