### PR TITLE
[Distributed] Diagnose missing inout on remoteCall decls

### LINKED ISSUE #58671: [Distributed] missing diagnosis for missing inout on remoteCall params
A bad remote call declaration like this:

```
  func remoteCall<Act, Err, Res>(
      on actor: Act,
      target: RemoteCallTarget,
      invocation: InvocationEncoder, // MISSING 'inout'
      throwing: Err.Type,
      returning: Res.Type
  ) async throws -> Res
      where Act: DistributedActor,
      Act.ID == ActorID,
      Err: Error,
      Res: SerializationRequirement {
    fatalError("NOT IMPLEMENTED \(#function)")
  }
```

Is not diagnosed as bad (missing the inout), and thus ends up erroring like:

```
<unknown>:0: error: unexpected error produced: '&' used with non-inout argument of type 'MissingRemoteCall_missingInout_on_encoder.InvocationEncoder' (aka 'FakeInvocationEncoder')
```

Reported via forums: https://forums.swift.org/t/help-some-issues-with-compiling-distributed-actors-project-with-latest-trunk/57134/2

--

rdar://92754877

### PR DESCRIPTION
**Pull request by ktoso**
Resolves https://github.com/apple/swift/issues/58671
Resolves rdar://92754877

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
Unrelated CI crash

```

fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2671)
```

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
@swift-ci please smoke test linux

**Review by xedin — APPROVED** [review]

**Comment by ktoso** [comment]
@swift-ci please smoke test linux
@swift-ci please smoke test macos

**Comment by shahmishal** [comment]
@swift-ci please smoke test linux

**Pull request merged**
