### PR TITLE
[WIP] Enhance -assume-single-threaded option

### PR DESCRIPTION
**Pull request by mtake**
(This PR was replaced with #7557)

This PR is part of [SR-3945](https://bugs.swift.org/browse/SR-3945) which extends the scope of ```-assume-single-threaded``` option to value types.

This PR is not fully integrated with swift build system yet. The same environment variable ```SWIFT_ASSUME_SINGLE_THREADED``` is used at compile time to configure swift compiler to generate single threaded code and, as well as at runtime to configure swift native runtime for single threaded code.

To use this PR, set an arbitrary text to ```SWIFT_ASSUME_SINGLE_THREADED``` while running ```build-script``` as well as running your program. Without the variable defined, this PR should have no effect.

### CODE REVIEW

**Comment by mtake** [comment]
@swiftix @gottesmm Please review

**Comment by swiftix** [comment]
@mtake Thanks for submitting this PR! The overall direction looks good. This is exactly what I expected. BTW, we have even an issue radar number for exactly this functionality: https://bugs.swift.org/browse/SR-3945. You can mention it in the PR description or in your commit message.

I just had a first quick look. Here are the initial comments:
- Could you please rebase on top of the swift/master, so that the PR contains only your commit? Right now it shows a lot of unrelated merged commits.
- Minor nitpick: You introduced a couple of free-standing functions like getAtomicity(SILBuidler& B). May be they should be members of the types representing their arguments, so that we get e.g. B.getAtomicity()? No strong preference here though.
- We need a better integration with the swift build system. We just need to add a new --assume-single-threaded option in the build-script, which should be pretty straight-forward.
- Tests! You can take the existing tests which were committed as part of my initial assume-single-threaded commit and extend them.
  - Add tests for all the new instructions which now have the atomicity flag at the SIL level
  - Add tests for checking that SIL level atomicity attributes are properly lowered by IRGen
  - It would be nice to have tests for the swift-runtime to show e.g. that only non-atomic ref counting operations are invoked inside the runtime. 
  - It would be nice to have tests for the stdlib (i.e. Swift.o) to show e.g. that only non-atomic ref counting operations are invoked.

Something to consider for the future:
- Right now you've taken a totally static approach when it comes to runtime/stdlib changes. I.e. they need to be compiled in a special mode, so that they use only non-atomic ref-counting operations. 
- But it can be interesting to go for a more dynamic approach, so that the same runtime can be used with --assume-single-threaded and non-assume-single-threaded-apps. The idea would be that depending on some setting (e.g. an environment variable or something like this) the atomic versions of the ref-counting runtime functions would actually behave like non-atomic. They could e.g. forward the calls to the non-atomic versions. Or may be we could even interpose those atomic ref-counting operations to refer to the non-atomic ones at the dynamic linking time.
- Even if what I propose cannot be done, it would be nice to be able to build both atomic and non-atomic runtimes/stdlibs in one run of the build script, just like we do it for static and dynamic versions of the standard library.
- If you need help with the build system integration, please let us know.

**Comment by slavapestov** [comment]
There's something wrong with how this PR was created. It has a bunch of other people's changes in it.

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@mtake 

- The implementation with the environment variable seems interesting. We still need to check if it affects the performance of atomic cases too much due to the additional conditional branch instruction. If this is the case, we would need to go for the approach where we produce different binaries for the atomic and non-atomic runtime libraries.

- BTW, we cannot easily test your PR on the CI bots, because it would require setting an environment variable, which is not currently possible using `@swift-ci` commands. But I'll try to test it locally on my machine till the end of the week. In general, we really need to have an option in the swift/util/build-script to enable the builds of non-atomic components (e.g. stdlib and runtime).

- Could you locally rebase your PR to contain only your commits and then push force it using `git push --force`? Currently it contains about 35 commits from other people and those commits have nothing to do with your PR. Alternatively, you can submit a new PR, which would contain only your commits.

**Comment by gottesmm** [comment]
If you want to test on the PR bots, you can add in a commit on your branch a change to the preset that the bot will invoke or add an additional preset.

There is support in swift-ci for invoking arbitrary presets.

**Comment by gottesmm** [comment]
You can add a preset by looking in ./utils/build-presets.ini. I would just copy the section under:

[preset: buildbot_incremental,tools=RA,stdlib=RD,smoketest=macosx]

And create a preset maybe with the name:

[preset: buildbot_incremental,tools=RA,stdlib=RD,smoketest=macosx,single-thread]

and add your flag to that after the em-dash to ensure that it is passed to build-script-impl if you need to do so.

**Comment by mtake** [comment]
Will create a new PR with my commit.

**Comment by swiftix** [comment]
Here is what I usually do:
- fork the original, i.e. apple/swift
- clone my fork to my machine
- Configure the upstream: https://help.github.com/articles/configuring-a-remote-for-a-fork/
- create locally a branch for my feature
- develop and commit on this branch
- once I'm ready, I sync it with upstream like this (note that I do not merge!):
   - `git fetch upstream master`, which receives the latest changes from apple/swift master 
   - `git rebase  upstream/master`, which rebases your commits on top of those changes
- push it to my branch on github using `git push` if it is a first time or eventually using `git push --force` if required
- create a PR


Please let me know if it helps or if you need more help.

**Comment by slavapestov** [comment]
Instead of merging upstream into your branch, rebase your branch on top of upstream:

```
git fetch origin
git rebase -i origin/master
git push -f mygithubrepo HEAD:refs/heads/remote-branch-name
```

**Comment by mtake** [comment]
@swiftix Your suggestion worked perfectly.  Thanks!

**Comment by mtake** [comment]
This PR was replaced with #7557

**Pull request closed without merging**
