### PR TITLE
test: triplicate a test

### PR DESCRIPTION
**Pull request by compnerd**
The runtime can be out of date and cause spurious failures.  Copy the
test over thrice to deal with that.  Requested by Mark Lacey.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @rudkx @jrose-apple 

Not sure if Jordan has strong opinions on having three copies of the test (I think that it is probably better to rely on developers to do clean builds than have three copies of the test).

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by jrose-apple** [comment]
No, I'm with Mark, since there's plenty of times when I configure to build the iOS stdlib but haven't built it *yet.* (And left a comment to that effect back in December.) You need to add the REQUIRES check to actually make this useful, though.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by jrose-apple** [comment]
As I said on #13225, it's probably still using the stdlib because you're importing types from C. I don't think the importer is set up to avoid looking things up in -parse-stdlib mode, and it's not really worth your time to do that.

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Pull request merged**
