### PR TITLE
[DiscardingTG] Remove reabstraction thunk for `() -> Void` to `() -> T`

### PR DESCRIPTION
**Pull request by kateinoigakukun**
Concurrency runtime expects discarding task operation entrypoint function not to have result type, but the current SILGen implementation generates reabstraction thunk to convert `() -> Void` to `() -> T` for the operation function.

Since the `T` is always `Void` for DiscardingTG, the mismatch of result type expectation does not cause any problem on most platforms, but the signature mismatch causes a problem on WebAssembly.

This patch introduces new builtin operations for creating discarding task, which always takes `() -> Void` as the operation function type.

The issue https://github.com/apple/swift/issues/63060 was partially fixed by https://github.com/apple/swift/pull/66219, but https://github.com/apple/swift/pull/68793 revealed the issue again since it added extra reabstraction for the given operation closure.

### CODE REVIEW

**Comment by kateinoigakukun** [comment]
@swift-ci Please test

**Review by slavapestov — COMMENTED** [review]
@jckarter Maybe there's a way to achieve this without a new builtin, using your reabstraction peephole logic?

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Review by ktoso — APPROVED** [review]
Thank you for fixing this up, I missed the discarding group with the latest work — thanks! LGTM

**Pull request merged**
