### PR TITLE
Fix ArrayElementPropagation in ossa when replacing array.get_element with a non control equivalent value

### PR DESCRIPTION
**Pull request by meg-gupta**
Ex: When original value is outside the loop, and array.get_element calls are within the loop

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci test

**Review by eeckstein — APPROVED** [review]
lgtm!

**Comment by meg-gupta** [comment]
@swift-ci test linux platform

**Comment by meg-gupta** [comment]
@swift-ci test windows platform

**Comment by meg-gupta** [comment]
Looks like this change exposed a bug on Linux. Will look into it..

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test Linux Platform

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
This is fixed with https://github.com/swiftlang/swift/pull/77610

**Pull request closed without merging**
