### PR TITLE
[CSGen] Type-check capture list together with closure body

### PR DESCRIPTION
**Pull request by xedin**
Delay constraint generation for capture list until body of the associated closure is resolved.
This means that we can unify capture checking with that of regular pattern bindings for 
multi-statement closures.

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test

**Review by hamishknight — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Comment by xedin** [comment]
@swift-ci please test source compatibility debug

**Pull request merged**
