### PR TITLE
Merge `rebranch` into `main` to support `stable/20230725` llvm-project branch

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci build toolchain

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci build toolchain

**Comment by etcwilde** [comment]
@swift-ci test

**Comment by etcwilde** [comment]
@swift-ci build toolchain

**Comment by etcwilde** [comment]
Hit the missing compiler on Windows again.
```
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:12 (project):
  The CMAKE_C_COMPILER:

    T:/1/bin/clang-cl.exe

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:12 (project):
  The CMAKE_CXX_COMPILER:

    T:/1/bin/clang-cl.exe

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
```
This part appears to be picking up the wrong compiler still:
https://github.com/apple/swift/blob/24fbd54ffa99bd4c78035803be26dd4eb2c5c5b9/cmake/modules/Libdispatch.cmake#L11-L19

**Comment by etcwilde** [comment]
@swift-ci test

**Comment by etcwilde** [comment]
@swift-ci build toolchain

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci build toolchain

**Comment by shahmishal** [comment]
@swift-ci Please Build Toolchain UBI9

**Comment by shahmishal** [comment]
@swift-ci Please Build Toolchain CentOS 7

**Comment by shahmishal** [comment]
@swift-ci Please Build Toolchain Ubuntu 18.04

**Comment by shahmishal** [comment]
@swift-ci Please Build Toolchain Ubuntu 20.04

**Comment by shahmishal** [comment]
@swift-ci Please Build Toolchain Amazon Linux 2

**Comment by shahmishal** [comment]
@swift-ci Please Build Toolchain Ubuntu 22.04

**Comment by shahmishal** [comment]
@swift-ci Please Build Toolchain Ubuntu 22.04

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci build toolchain

**Comment by shahmishal** [comment]
@swift-ci Please Build Toolchain UBI9

**Comment by shahmishal** [comment]
@swift-ci Please Build Toolchain CentOS 7

**Comment by shahmishal** [comment]
@swift-ci Please Build Toolchain Ubuntu 18.04

**Comment by shahmishal** [comment]
@swift-ci Please Build Toolchain Ubuntu 22.04

**Comment by shahmishal** [comment]
@swift-ci Please Build Toolchain Amazon Linux 2

**Pull request merged**
