### PR TITLE
[update-checkout] Allow untracked files

### PR DESCRIPTION
**Pull request by rintaro**
#### What's in this pull request?

Allow untracked files when updating.

I have several untracked files in my work tree for personal use.
Moreover, `utils/build-toolchain` creates installed files in the source directory.
It's very annoying to stash them away...

```
$ utils/update-checkout 

... <snip> ...

--- Updating '/Users/rintaro/git/swift-oss/swift' ---
Please, commit your changes.
?? swift-nightly-install/
?? swift-nightly-symroot/
?? utils/my-personal-util

$
```

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

### CODE REVIEW

**Comment by ddunbar** [comment]
I'm not sure this is a good idea, in other situations it will cause problems (e.g., if you have untracked source files from PRs that have now been merged).

Note that one trick you can use for your personal stuff is to hide a .gitignore in those directories, and have that gitignore ignore itself and the directory it is in.

**Comment by rintaro** [comment]
@ddunbar 
In that case, `shell.call(["git", "rebase", "FETCH_HEAD"], echo=False)` will *successfully* fail.
```
error: The following untracked working tree files would be overwritten by checkout:
	test.txt
Please move or remove them before you can switch branches.
Aborting
```
Anyway, thank you for the tips!

**Comment by gottesmm** [comment]
Maybe add an option?

Michael

**Comment by rintaro** [comment]
I studied the history of this piece of code:
2/1 6e66d6caefc6fb531e836472cdff6b2a54b009d9 Introduced
2/2 ae6db3ae501fb0cd9c4a3f0e581dd2f52ec9223e Limited to if `--branch` is specified, as requested https://github.com/apple/swift/commit/6e66d6caefc6fb531e836472cdff6b2a54b009d9#commitcomment-15833382
6/6 62c5816f20076dce5349c56a8ffc8e90b86d974d Always enabled, because `branch` is always set.

So, instead of ignoring untracked files, how about:
```diff
-      if branch:
+      if branch != get_current_branch():
```

**Comment by gottesmm** [comment]
@rintaro Can you be more specific.

Also, we do not support building in the source tree in general, so if build-toolchain is littering your source directories with files, IMO, the right fix is to fix build-toolchain.

**Comment by rintaro** [comment]
@gottesmm Sorry, it was unclear.

From ae6db3a change, my understanding is that
"check for uncommitted changes" is *not* necessary if the current branch is already the target branch.
If so, in that case, we can skip this `if` block:
https://github.com/apple/swift/compare/master...rintaro:update-checkout-check-branch

**Comment by jrose-apple** [comment]
I'm with @rintaro (and past @DougGregor) on this one. My source directories aren't clean. I don't feel like cleaning them to run update-checkout, because they're random things like "notes.md".

**Comment by jrose-apple** [comment]
I realize I could and possibly should have a different workflow, but update-checkout shouldn't require it. This should really stay a low-friction tool, or I'll just stop using it.

**Comment by DougGregor** [comment]
Yes, I'm definitely with @jrose-apple here. update-checkout shouldn't force us to have fully-clean source directories.

**Comment by ddunbar** [comment]
Should this just be merged then?

**Comment by gribozavr** [comment]
> Moreover, `utils/build-toolchain` creates installed files in the source directory.

A separate point, but I think we should change it so that it does not.

**Comment by gribozavr** [comment]
I think this is good to land.

**Comment by gribozavr** [comment]
@swift-ci Please Python lint

**Pull request merged**
