### PR TITLE
[update-checkout] Update the cmake that we build on Linux on main to cmake 3.20.2 (latest).

### PR DESCRIPTION
**Pull request by gottesmm**
I am not changing the minimum cmake requirements anywhere. I am just changing
this to get ahead of bumpings of minimum cmake requirements in various places.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Review by drexin — APPROVED** [review]
👍

**Comment by buttaface** [comment]
Is the plan to increase the minimum to 3.20 for the next 5.6/6.0 release? Because just by increasing this for trunk, you will likely see CMake config changes that don't work for older CMake get introduced, which will effectively push the minimum up for the next release.

My understanding is that older CMake versions are still supported because the system packages in Ubuntu are these old versions. I'm fine with making those people use a newer CMake, as I only use Linux distros that keep CMake current, but just pointing out that you will be increasing the minimum CMake version too with this change (well, to whatever the minimum of the CMake version used on the macOS/Windows CI and this is).

**Review by compnerd — CHANGES_REQUESTED** [review]
Please use an unreleased CMake, 3.20.2 had a regression that I did get fixed, but I believe that will be in 3.20.3

**Comment by gottesmm** [comment]
I am actually going to do a lower one, 3.19. something.

**Pull request closed without merging**
