### PR TITLE
[ConstraintSystem] Refactor matchCallArguments

### PR DESCRIPTION
**Pull request by omochi**
This PR contains multiple small refactors for `matchCallArguments`.

@xedin Please review this PR.

I checked all commits by primary test suite.

I explain details here.

## use claim for trailing closure

Argument claiming is operated by modification of `claimedArgs` and `numClaimedArgs`.
There is a helper function `claim` for doing it.
But code for trailing closure in `bindNextParameter` modifies them directly.
This patch changes it to use `claim` function.

## remove unused nextArgIdx operation

This operation for `nextArgIdx` is meaningless.
It seems to come from old code and some changes make it meaningless.
This patch removes it.
 
## use local variable for temporary loop

This simple loop uses `nextArgIdx`.
But it doesn't relate to role of this variable which has a large scope.
This patch changes it to use individual local variable.

## remove unnecessary skipClaimedArgs call

There are multiple call of `skipClaimedArgs`.
But almost of them are meaningless.
Because the only use position of `nextArgIdx` which is `claimNextNamed` calls `skipClaimedArgs` on beginning of it before use `nextArgIdx`.
This patch removes them.
After this, use position of `skipClaimedArgs` is a only one in `claimNextNamed`.

## change nextArgIdx to local variable

A `matchCallArguments` is large function.
So it's local variable `nextArgIdx` also has large scope.
And it is reference captured by some nested function.
Splitting this variable into individuals which has small scope makes code more readable.
This patch does it.

## change paramIdx to local variable

Same idea with `nextArgIdx`.

There are some for-loops with `paramIdx`.
All of them doesn't need to use shared large scope variable.

This patch changes it.

And I replaced them to `for-in` style from three statements style if it can be.

## use for-in

This patch changes to `for-in` style if it can be.

### CODE REVIEW

**Review by xedin — APPROVED** [review]
Looks good, thank you!

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by theblixguy** [comment]
Debug failure is unrelated:

> stderr: error: unable to write symref for HEAD: No space left on device

@swift-ci please test source compatibility debug

**Comment by theblixguy** [comment]
@swift-ci please test source compatibility release

**Comment by xedin** [comment]
@swift-ci please test source compatibility release

**Comment by xedin** [comment]
CI is not feeling very well today...

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility release

**Comment by omochi** [comment]
thank you

**Comment by xedin** [comment]
Thank you for a great contribution!

**Pull request merged**
