### PR TITLE
merge swift-DEVELOPMENT-SNAPSHOT-2018-10-01-a into tensorflow

### PR DESCRIPTION
**Pull request by marcrasi**
You can see all the manual fixes in https://github.com/apple/swift/commit/e34739e31d72739e7235adb1f9a705287e9da74e, which is the latest commit in this PR.

A summary of the substantial ones:
* The merge exposed a pointer arithmetic bug in TFLowerGraph, which I fixed.
* Added two lines to `DerivedConformanceParameterized.cpp` that tell it to synthesize a "modify" accessor for "allParameters". Without this, "test/TensorFlowRuntime/parameter_update.swift" fails with a linker error because there is no modify accessor.
* `getUnlabeledType(ctx)` vanished from upstream. AutoDiff attr typechecking used that to disregard labels while checking the adjoint. So I manually implemented a check that disregards labels.
* Deleted some `@compilerEvaluable` attribute code and a `@compilerEvaluable` attribute test, becuase I don't see any value in keeping all that stuff in sync right now. There is still some leftover `@compilerEvaluable`  attribute code that I'd like to delete soon in future PRs.

Also, here's a corresponding LLDB merge: https://github.com/apple/swift-lldb/pull/958. It's completely trivial.

### CODE REVIEW

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Comment by marcrasi** [comment]
@swift-ci please clean test tensorflow

**Comment by rxwei** [comment]
> `getUnlabeledType(ctx)` vanished from upstream. AutoDiff attr typechecking used that to disregard labels while checking the adjoint. So I manually implemented a check that disregards labels.

I'm fine with this, but I also think it can make sense to require identical labels in the adjoint.

> Deleted some `@compilerEvaluable` attribute code and a `@compilerEvaluable` attribute test, becuase I don't see any value in keeping all that stuff in sync right now. There is still some leftover `@compilerEvaluable` attribute code that I'd like to delete soon in future PRs.

Do you plan to revive the code when you and Chris run the proposal?

**Review by rxwei — APPROVED** [review]

**Comment by marcrasi** [comment]
> > `getUnlabeledType(ctx)` vanished from upstream. AutoDiff attr typechecking used that to disregard labels while checking the adjoint. So I manually implemented a check that disregards labels.
> 
> I'm fine with this, but I also think it can make sense to require identical labels in the adjoint.

Sounds reasonable. We could change that whenever.
 
> > Deleted some `@compilerEvaluable` attribute code and a `@compilerEvaluable` attribute test, becuase I don't see any value in keeping all that stuff in sync right now. There is still some leftover `@compilerEvaluable` attribute code that I'd like to delete soon in future PRs.
> 
> Do you plan to revive the code when you and Chris run the proposal?

Yes, if the attribute ends up being part of the proposal, which seems kind of uncertain right now. We'll see.

**Pull request merged**
