### PR TITLE
Revert "[NFC][Python: black] Reformatted the benchmark Python sources using utils/python_format.py."

### PR DESCRIPTION
**Pull request by palimondo**
Reverts apple/swift#29719

This is to enable landing of #26462 without mayor conflicts. Since #29719 appears to be a result of automatic source code transformation by a Black formatter, it could be re-done later, if still deemed beneficial. Personally I dislike the result quite a bit, but if that’s really the maintainer’s consensus, so be it…

### CODE REVIEW

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@palimondo please be sure when you are done landing your change here. Please reapply this!

**Comment by compnerd** [comment]
This has conflicts, if this is still useful, please update it.

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
