### PR TITLE
Fixup Structure of Mock SDKSettings

### PR DESCRIPTION
**Pull request by CodaFi**
This better reflects the actual structure of the files as they appear in
the 10.15 and 10.15.4 SDKs respectively.

rdar://69412779

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by shahmishal** [comment]
@swift-ci smoke test Windows

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
