### PR TITLE
Revert "[build] Support installing swift-driver without swiftpm"

### PR DESCRIPTION
**Pull request by shahmishal**
Reverts apple/swift#34186

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test source compat suite

**Comment by shahmishal** [comment]
@swift-ci Please Test Source Compatibility

**Comment by shahmishal** [comment]
@swift-ci smoke test

**Review by artemcm — APPROVED** [review]

**Comment by brentdax** [comment]
The reverted PR did not cause the regression in the source compatibility suite.

**Pull request closed without merging**
