### PR TITLE
[cmake] Add support for external clang/clang-cl

### PR DESCRIPTION
**Pull request by lxbndr**
We need an option to pass external host clang location in case we can't use just-built clang, e.g. when we are building for
different target architecture.

Also, this adds target options for clang-cl, enabling us to build for arm64 on Windows@amd64.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by lxbndr** [comment]
cc @compnerd

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Running a build at https://dev.azure.com/compnerd/swift-build/_build/results?buildId=56346&view=results as well - just to ensure that this won't impact the nightlies/releases for the time being.

**Comment by compnerd** [comment]
The build passed, and though the patch wasn't applied to the toolchain build, it was applied to the SDK build and that seemed to pass.  I'm going to guess that this should be fine for the compatibility.

**Review by compnerd — APPROVED** [review]
Looks good to me.

**Pull request merged**
