### PR TITLE
Sema: Small ConstraintGraph cleanup

### PR DESCRIPTION
**Pull request by slavapestov**
We used `operator[]` to both insert and find vertices in the ConstraintGraph. Split it up into two operations to better enforce invariants.

Also, when freeing a vertex, we don't have to clear it -- assuming all changes were undone correctly, then at the time we're ready to undo the creation of the vertex, it should be empty already. Just assert instead.

Finally, `ConstraintGraphNode::Bindings` doesn't need to be Optional anymore because we never reset it. Once again, it should be empty when we free the node.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Review by xedin — COMMENTED** [review]
Looks reasonable!

**Pull request merged**
