### PR TITLE
[IRGen] Blacklist metadata globals from address sanitizer.

### PR DESCRIPTION
**Pull request by mikeash**
Otherwise asan pads them in an attempt to detect overflows, which messes with other code which assumes that metadata is contiguous.

rdar://problem/39128762

### CODE REVIEW

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test

**Review by jckarter — APPROVED** [review]
Looks good, thanks Mike!

**Review by slavapestov — APPROVED** [review]

**Pull request merged**
