### PR TITLE
We did the implicit untupling but forgot to do implicit tupling. Oops.

### PR DESCRIPTION
**Pull request by varungandhi-apple**
Fixes rdar://problem/58578342

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
@swift-ci please test
@swift-ci please test source compatibility

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by varungandhi-apple** [comment]
@CodaFi LGTY?

**Review by CodaFi — APPROVED** [review]

**Comment by varungandhi-apple** [comment]
FTR: this was supposed to fix rdar://problem/58425942 not the one I mentioned earlier.

**Pull request merged**
