### PR TITLE
[SIL] Add support for the UTF8NoNullPad string encoding

### PR DESCRIPTION
**Pull request by vedantk**
Add support for non-null-terminated StringLiteralInsts in SIL.

I grant that the `Encoding` argument is a strange place to do this. However, it makes some sense and is very convenient.

Context: I'll need this to fix up the profiling code. The only alternative I've found is to add special logic to `emitBuiltinCall` which intercepts `int_instrprof_increment` intrinsics and rewrites the function name argument. While this works, it is incredibly intrusive and gross.

### CODE REVIEW

**Comment by jrose-apple** [comment]
This seems reasonable to me, although I'm not a SIL code owner. (@jckarter?) I'm a little unhappy with the name, though, because the NUL at the end isn't padding; it's a C string terminator. Maybe "UTF8NoNullTerminator" or "UTF8NonNullTerminated"?

**Comment by jckarter** [comment]
I don't like this. I'd prefer to have it so that `string_literal` instructions explicitly include the null terminator when it's wanted. You should also check that non-null-terminated string literals don't end up in the `__TEXT, __cstring` section of the object file, since that could interfere with string literal coalescing in the linker.

**Comment by vedantk** [comment]
@jckarter I'd like that too. Here's my new plan:

1. Change `Encoding::UTF8` -> `Encoding::UTF8AddNull` ("AddNull" is consistent with the llvm API), and  change `Encoding::UTF8NoNullPad` -> `Encoding::UTF8`.
2. Change existing uses of `Encoding::UTF8` to `Encoding::UTF8AddNull`.
3. While lowering non-null-terminated string literals, assert that they aren't in `__TEXT,__cstring`. E.g in my use case, they will be in `__DATA,__llvm_prof_names`.

Does that sound ok?

**Comment by jckarter** [comment]
The encoding shouldn't need to know whether to add a null or not, we can add the null to the string_literal value.

**Comment by jckarter** [comment]
It looks like LLVM's already smart enough to put non-null-terminated strings in `__TEXT,__const` instead of `__cstring`.

**Comment by jckarter** [comment]
Alternately, if this is only for code coverage, and the string literals belong in a separate section anyway, should we make the coverage-related instructions take their own string literal operands? They should always be constant, right?

**Comment by vedantk** [comment]
The coverage instructions (well just `int_instrprof_increment`) has a constant string operand. We use `createStringLiteral` to create this operand (SILGenProfiling.cpp), but we need to find a way to make sure it isn't null-terminated. I'm not sure what you mean by 'taking their own string literal operands'.

Since you'd rather not control null-termination behavior with StringLiteralInst::Encoding, I'm testing the effects of removing the null padding from `IRGenModule::getAddrOfGlobalString`.

**Comment by jckarter** [comment]
I see, I didn't realize it was handled by a builtin rather than a proper SIL instruction. I was saying that it might make sense for a dedicated SIL instruction to take the function name as a direct operand, in other words:

```
coverage_increment "CurrentFuncName", N
```

rather than:

```
%funcname = string_literal utf8 "CurrentFuncName"
%numcounters = integer_literal N
coverage_increment %funcname, %numcounters
```

since the operands should always be constant, and we can handle the special formatting and linkage requirements for this instruction's operands in LLVM.

**Comment by vedantk** [comment]
I prefer your earlier proposal to change the StringLiteral lowering s.t null terminators aren't added automatically. I like that it forces us to be more explicit and that it's more general. That said, when I tested this change I got 29 unexpected test failures!

Wdyt of this plan: (1) move all clients of `UTF8` to `UTF8AddNull` temporarily, (2) incrementally move these users back to `UTF8` by fixing up their string values with null terminators, and (3) remove `UTF8AddNull`?

We can add a comment stating that there should be no new users of `Encoding::UTF8AddNull`. While we'd have to file a bug to track progress towards (3), step (1) can be done quickly. That will help with the stable merge.

**Comment by jckarter** [comment]
I agree that making the terminator explicit is independently a good idea. A better way to stage in the change might be to add an `emitStringLiteralWithNullTerminator` to SILBuilder and update all uses of `createStringLiteral` to that.

**Comment by vedantk** [comment]
Ok! @gottesmm advised me to base changes on master, so I'll close this PR and file another momentarily.

**Pull request closed without merging**
