### PR TITLE
Fix static exclusivity verification for withoutActuallyEscaping.

### PR DESCRIPTION
**Pull request by atrick**
Add a SIL attribute [without_actually_escaping].

Teach static exclusivity verification about withoutActuallyEscaping.

Fixes <rdar://problem/43059088> Assertion in DiagnoseStaticExclusivity.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
@swift-ci test source compatibility.

**Comment by atrick** [comment]
@shajrawi I'm looking for a bug fix review here.

Also, @jckarter may be interested.

**Comment by atrick** [comment]
@swift-ci smoke test.

**Review by shajrawi — CHANGES_REQUESTED** [review]
LGTM! But, can you please update `convert_function`'s documentation in `SIL.rst`?

**Comment by atrick** [comment]
@shajrawi thanks, I almost forgot!

**Comment by atrick** [comment]
@swift-ci smoke test.

**Review by shajrawi — APPROVED** [review]

**Pull request merged**
