### PR TITLE
Remove _silgen_name from all Apple overlays except Dispatch and Foundation

### PR DESCRIPTION
**Pull request by jrose-apple**
Steps towards getting rid of `_silgen_name` altogether, which is generally unsafe and not something we're interested in supporting in its current form. I left out Dispatch and Foundation for now because those have code owners active in the Swift project. The "platform" overlay (Darwin/Glibc) has also been exempted for now because I didn't want to poke at any low-level import dependencies.

There are a few downsides to all this: these headers get installed along with the shims even though they're only used to build the overlays, and only on Apple platforms. I or someone else should go back later and
1. Split these new shim headers into their own folders with their own module maps.
2. Add separate CMake targets for each one, for better dependencies.
3. Don't install the headers on irrelevant platforms.

Overall, though, I think this is a safety and simplicity win.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@moiseev, @slavapestov, can you review these changes?

@swift-ci Please test macOS platform

@swift-ci Please smoke test Linux platform

**Comment by jrose-apple** [comment]
@swift-ci Please test macOS platform

**Comment by modocache** [comment]
The `DebugInfo/bbentry-location.swift` failure has been blocking me all day. :(

**Comment by CodaFi** [comment]
Let's see if #5325 got it, then.

@swift-ci please test OS X platform.

**Comment by jckarter** [comment]
Thanks for trying to clean this up! Maybe we should also hide `_silgen_name` behind a flag so that it's harder for people to try to add more uses of it outside of the stdlib (and maybe Foundation, which is pretty tied up in the runtime too).

**Comment by jrose-apple** [comment]
That's my ultimate goal (and I want the flag to be `-parse-stdlib`, ideally), but we've still got a bit more to do before that. (In particular, IIRC it's used by LLDB and playgrounds to inject symbols or make identifiable SIL functions.)

**Comment by jckarter** [comment]
Cool. LLDB and Playgrounds shouldn't be too much of a problem; the former already has its own special frontend mode, and the Playground logger directly manipulates ASTs, so doesn't need to be subjected to parser-level restrictions.

**Comment by jrose-apple** [comment]
Max talked to me in person a few days ago, and Slava left behind an emoji, so I'm going to assume this is okay to merge and possibly undergo refinement later. Retesting just to be safe.

@swift-ci Please test macOS

**Pull request merged**
