### PR TITLE
[Concurrency] Stub out an experimental concurrency support library.

### PR DESCRIPTION
**Pull request by DougGregor**
The experimental concurrency model will require a supporting runtime
and possibly end-user-visible library constructs. Introduce a stub of
such a library, enabled by a new `build-script` option
`--enable-experimental-concurrency`, so we have a place to put this
work.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by rickky008** [comment]
Thx you

**Comment by DougGregor** [comment]
@swift-ci smoke test

**Comment by DougGregor** [comment]
@swift-ci smoke test

**Comment by DougGregor** [comment]
@swift-ci please test Windows

**Comment by DougGregor** [comment]
@swift-ci smoke test macOS

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by gribozavr** [comment]
@DougGregor I'm very interested in this work -- is there a proposal draft for it?

**Pull request merged**
