### PR TITLE
Pull the ArrayRef use-of-temporary fixes into Swift 2.3

### PR DESCRIPTION
**Pull request by benlangmuir**
Backport the ArrayRef fixes we've made in Swift master to 2.3 so that we can compile this branch with newer and more aggressive Clang versions.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by benlangmuir** [comment]
@swift-ci Please test

**Comment by benlangmuir** [comment]
Paging @erg and @shahmishal
`update-checkout: error: unrecognized arguments: --github-comment @swift-ci Please test`

**Comment by shahmishal** [comment]
@benlangmuir This is due to `update-checkout` script on swift-2.3-branch is out of date and it does not contain `--github-comment` flag.

**Comment by slavapestov** [comment]
Do we still need this?

**Comment by benlangmuir** [comment]
Nope.

**Pull request closed without merging**
