### PR TITLE
Enhance README.md for adding 'sh' to the code block.

### PR DESCRIPTION
**Pull request by lamtrinhdev**
Enhance README.md for adding 'sh' to the code block.

### CODE REVIEW

**Comment by lamtrinhdev** [comment]
Dear @parispittman ,

I have a minor update link for README.md. Could you please help me to review it?

Thanks,
Lam

**Review by LucianoPAlmeida — APPROVED** [review]
Looks like a good small improvement :)

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test

**Comment by LucianoPAlmeida** [comment]
My approval is gray which means that I probably lost write access, I've been away from swift repo for a while so may this is due inactivity or more likely due to change of repo? 
cc @xedin, @AnthonyLatsis

**Comment by AnthonyLatsis** [comment]
I think you should contact @shahmishal about loss of write access.

**Comment by AnthonyLatsis** [comment]
@lamtrinhdev Thank you. Please squash your commits and provide a meaningful commit message.

**Comment by lamtrinhdev** [comment]
Dear @AnthonyLatsis  and @LucianoPAlmeida ,

Thank you for your support. Let me close this PR and create the new PR at https://github.com/swiftlang/swift/pull/75981 .

Thanks,
Lam

**Comment by AnthonyLatsis** [comment]
You do not need to create a new PR to edit your commit history. Please prefer an interactive rebase instead (see https://github.com/swiftlang/swift/blob/main/docs/HowToGuides/FAQ.md#how-do-i-clean-up-my-git-history).

**Comment by lamtrinhdev** [comment]
Dear @AnthonyLatsis ,

Thank you for your support. I learned the new things. 

Thanks,
Lam

**Pull request closed without merging**
