### PR TITLE
[5.0] Disable propagateSoleConformingType optimization since it is causing …

### PR DESCRIPTION
**Pull request by gottesmm**
…miscompiles.

I am currently preparing a smaller test case, but I need to disable this in the
short term.

rdar://46409354

### CODE REVIEW

**Comment by slavapestov** [comment]
CC @rajbarik

**Comment by gottesmm** [comment]
@rajbarik I am going to get you a test case in a bit.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
This should not be ABI effecting and is needed for convergence to fix a miscompile we are seeing.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Review by eeckstein — APPROVED** [review]
lgtm!

**Comment by rajbarik** [comment]
Please send me the test case. Thanks.

**Comment by rajbarik** [comment]
@gottesmm anything for me? Thanks.

**Comment by gottesmm** [comment]
@rajbarik working on it right now.

**Comment by gottesmm** [comment]
@rajbarik I found the problem. The problem is that in the analysis you are only looking at nominal types declared in the given module. One must also check extensions as well. Consider the following sil:

----
import Foundation

protocol Foo {
  var myName: String { get }
}

extension URL : Foo {
  var myName : String { return "URL" }
}

struct MyStruct : Foo {
  var myName : String { return "MyStruct" }
}

@inline(never)
func printName(_ f: Foo) {
  print(f.myName)
}

@inline(never)
func main() {
  let u = URL(string: "file:///foobar")!
  printName(u)
}

main()
----

with near ToT compiling without optimization prints "URL". With optimization + wmo, we print out MyStruct.

**Comment by gottesmm** [comment]
@rajbarik here: https://github.com/apple/swift/blob/master/lib/SILOptimizer/Analysis/ProtocolConformanceAnalysis.cpp#L37

**Comment by gottesmm** [comment]
@slavapestov @rajbarik This might fix it. What do you guys think?

```
diff --git a/lib/SILOptimizer/Analysis/ProtocolConformanceAnalysis.cpp b/lib/SILOptimizer/Analysis/ProtocolConformanceAnalysis.cppindex b16d47ddbb..3d93ecd786 100644
--- a/lib/SILOptimizer/Analysis/ProtocolConformanceAnalysis.cpp
+++ b/lib/SILOptimizer/Analysis/ProtocolConformanceAnalysis.cpp
@@ -17,6 +17,7 @@
 #include "swift/AST/ASTContext.h"
 #include "swift/AST/ASTWalker.h"
 #include "swift/AST/Module.h"
+#include "swift/AST/ProtocolConformance.h"
 #include "swift/SIL/SILInstruction.h"
 #include "swift/SIL/SILModule.h"
 #include "swift/SIL/SILValue.h"
@@ -41,7 +42,24 @@ public:
           ProtocolConformanceCache[Protocol].push_back(NTD);
         }
       }
+      return true;
     }
+
+    if (auto *e = dyn_cast<ExtensionDecl>(D)) {
+      auto *ntd = e->getExtendedNominal();
+      if (!isa<ProtocolDecl>(ntd)) {
+        for (auto *conformance : e->getLocalConformances()) {
+          if (isa<NormalProtocolConformance>(conformance)) {
+            auto *prot = conformance->getProtocol();
+            if (prot->getEffectiveAccess() <= AccessLevel::Internal) {
+              ProtocolConformanceCache[prot].push_back(ntd);
+            }
+          }
+        }
+      }
+      return true;
+    }
+
     return true;
   }
 };
```

**Comment by rajbarik** [comment]
Thanks a lot, Slava. The fix looks good to me. I can run tests in the morning.

**Comment by rajbarik** [comment]
@slavapestov @gottesmm Is Slava's patch good enough or should I create a PR out of this (with your example as the test case) and submit?

**Comment by slavapestov** [comment]
@rajbarik Please create a PR with Michael's change and a test case.

@DougGregor might be able to suggest a cleaner way to list out all conformances defined in the module, but this is good enough for now.

**Comment by gottesmm** [comment]
@slavapestov @rajbarik https://bugs.swift.org/browse/SR-9462

This will cause miscompiles on master. We need this fixed ASAP.

**Comment by slavapestov** [comment]
@gottesmm Can you disable the optimization on master too?

**Comment by rajbarik** [comment]
Please find the fix and test case.

**Pull request merged**
