### PR TITLE
[sil] Mark all members of SILFunctionBuilder private and make composi…

### PR DESCRIPTION
**Pull request by gottesmm**
…tion classes friend clases.

This is the final step towards making sure no one can use a SILFunctionBuilder
except through composition classes.

rdar://42301529

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by jrose-apple** [comment]
Do you have an interest in knowing all the composition classes? If not, this may actually be a case where inheritance is easier to use. (Then you can use `protected`.)

**Comment by gottesmm** [comment]
These are not meant to be substitutable with the original class. So it makes sense to make them composable.

**Comment by jrose-apple** [comment]
Still, C++ private inheritance supports that.

**Comment by gottesmm** [comment]
Jordan and I chatted about this offline. I explained to him that I prefer to use composition instead of private inheritance since it is generally considered a code-smell.

**Comment by gottesmm** [comment]
To be clear, I consider it to be a code-smell. I wasn't trying to speak for Jordan.

**Comment by atrick** [comment]
FWIW: It's probably fine either way. If SILFunctionBuilder were a public API (as in, exported to compiler plugin or something) you would want to use private inheritance to limit access, or even force clients to inherit from a SILFunctionBuilderBuilder... For an internal utility there's really no problem with listing all the clients. I personally think private inheritance tends to obfuscate the code.

**Pull request merged**
