### PR TITLE
Runtime: Add a runtime entry point to print metadata names for debugging

### PR DESCRIPTION
**Pull request by aschwaighofer**

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci test

**Comment by aschwaighofer** [comment]
@swift-ci test

**Comment by aschwaighofer** [comment]
Does `p nameForMetadata(...)` work for you in a shipped runtime?

All my attempts (granted I have used `e nameForMetadata()`) to use it failed. The way I explained that to myself is that `nameForMetadata` is an internal symbol.

```
% nm -a my-stdlibs/macosx/libswiftCore.dylib | grep nameForMetadata 
00000000002ffdb0 t __ZN5swift15nameForMetadataEPKNS_14TargetMetadataINS_9InProcessEEEb
0000000000300044 t __ZNK5swift14MetadataOrPack15nameForMetadataEv
```

**Comment by mikeash** [comment]
I didn't actually know about `nameForMetadata` until I saw this PR, so I don't know if it actually works. I always use `swift_getTypeName` and it's good. Nice thing about that is that even when you have no debug symbols, you can cast your way to victory with just C types, so `p (char *)swift_getTypeName(0xdeadbeef, 1)`.

**Pull request closed without merging**
