### PR TITLE
test: repair Interpreter/SDK/interpreter_with_options on ASi

### PR DESCRIPTION
**Pull request by compnerd**
Remove the target specific binary and instead compile a test binary on
the fly.  Because this test is restricted to macOS platforms, we know
that we assume that we will have a compatible Objective-C runtime at our
disposal.  Use that to create a stub library for testing
`NSClassFromString`.

This allows this test to execute on ARM64.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @brentdax

**Comment by compnerd** [comment]
@swift-ci please test

**Review by beccadax — APPROVED** [review]
🤮

Thanks for cleaning that up.

**Comment by compnerd** [comment]
```
<unknown>:0: error: fatal error encountered during compilation; please file a bug report with your project and the crash log
<unknown>:0: note: Cannot read '/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/./lib/swift/iphonesimulator/layouts-x86_64.yaml'
```

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Pull request merged**
