### PR TITLE
[WIP][Compare Perf] Add support for markdown and html

### PR DESCRIPTION
**Pull request by shahmishal**
#### What's in this pull request?

Compare perf results supports following args:

```
optional arguments:
  -h, --help            show this help message and exit
  --old-file OLD_FILE   Baseline performance test suite (csv file)
  --new-file NEW_FILE   New performance test suite (csv file)
  --format FORMAT       Supported format git, html and markdown
  --output OUTPUT       Output file name
  --changes-only        Output only affected tests
  --new-branch NEW_BRANCH
                        Name of the new branch
  --old-branch OLD_BRANCH
                        Name of the old branch
  --delta-threshold DELTA_THRESHOLD
                        delta threshold
```
#### Resolved bug number: N/A

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci Please perf test

**Comment by practicalswift** [comment]
@shahmishal Nice stuff!

A friendly side note - I think there might be a few `flake8` regressions in there that might be worth looking in to:

```
$ flake8 | cut -f4- -d: | sort | uniq -c
    126  E111 indentation is not a multiple of four
      3  E122 continuation line missing indentation or outdented
      3  E127 continuation line over-indented for visual indent
      3  E128 continuation line under-indented for visual indent
      1  E131 continuation line unaligned for hanging indent
      1  E203 whitespace before ':'
      3  E222 multiple spaces after operator
      3  E231 missing whitespace after ','
      6  E302 expected 2 blank lines, found 1
     16  E501 line too long (… > 79 characters)
      2  E711 comparison to None should be 'if cond is not None:'
      1  F401 'os' imported but unused
      1  F841 local variable 'geogebra_value' is assigned to but never used
      1  F841 local variable 'normalList' is assigned to but never used
      1  I100 Import statements are in the wrong order. import argparse should be before import csv
      1  I100 Import statements are in the wrong order. import csv should be before import sys
      1  N806 variable in function should be lowercase
```

I can fix them afterwards but that will cause some unnecessary `git blame` noise :-)

**Comment by shahmishal** [comment]
@practicalswift Thanks I will fix it :)

**Comment by gottesmm** [comment]
@shahmishal I wonder if we can make flake8 testing a lit test...

**Comment by gottesmm** [comment]
@practicalswift Thanks for the command line. I think we can probably make this into a lit test. We could make cmake search for flake8 and enable it only if we find flake8.

**Comment by shahmishal** [comment]
@swift-ci Please perf test

**Comment by shahmishal** [comment]
@swift-ci Please perf test

**Comment by practicalswift** [comment]
@shahmishal Nice! `flake8` gives :+1: now :-)

When running with the extension `flake8-import-order` enabled it gives the following warning about imports not being in the recommended order:

```
./benchmark/scripts/compare_perf_tests.py:17:1: I100 Import statements are in the wrong order. import csv should be before import sys
./benchmark/scripts/compare_perf_tests.py:18:1: I100 Import statements are in the wrong order. import argparse should be before import csv
```

**Comment by shahmishal** [comment]
@swift-ci Please perf test

**Comment by shahmishal** [comment]
@swift-ci Please benchmark

**Pull request merged**
