### PR TITLE
Make SWIFT_STDLIB_ENABLE_LTO flag apply LTO to C/C++ compile flags too

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
...and if I read the core right, SWIFTLIB_SINGLE_TARGET_LIBRARY is actually always set now? Maybe it would make sense to remove it? (I can do that in a subsequent PR if that's desirable.)

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by edymtt — APPROVED** [review]
This sounds reasonable to me -- this function only handles target libraries, `TARGET_LIBRARY` seems now a meaningless parameter (legacy of the old function that used to handle also host libraries)

We do have an instance when this function is called without `TARGET_LIBRARY`

https://github.com/apple/swift/blob/5f268cceab6afb4c3415c14cb7cb3328d25dccdb/stdlib/private/BlocksRuntimeStubs/CMakeLists.txt#L14

but since we are building for the target this seems an oversight (another hint that this parameter is redundant)

**Comment by kubamracek** [comment]
https://github.com/apple/swift/pull/38978

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by compnerd — APPROVED** [review]

**Pull request merged**
