### PR TITLE
Fix the emission of open-existential-metatype l-values

### PR DESCRIPTION
**Pull request by rjmccall**
rdar://32288618

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please smoke test and merge.

**Comment by rjmccall** [comment]
@swift-ci Please smoke test and merge.

**Comment by slavapestov** [comment]
Thanks for fixing this! There might be a simpler solution though, to have Sema coerce the base to an rvalue if its a metatype. You cannot have a mutating static method after all.

**Comment by rjmccall** [comment]
That's true, but the fix seems reasonable, and I'm reluctant to add any extra requirements to CSApply's treatments of member expressions. :)

**Comment by rjmccall** [comment]
@swift-ci Please smoke test.

**Comment by rjmccall** [comment]
Honestly, in general I feel a lot more comfortable with doing heroics in SILGen, where we implement most of Swift's evaluation semantics anyway, than in Sema, where we often have to come up with super-awkward abstractions just to make things fit the conceit of a syntax tree. It would be much simpler if CSApply just assigned each source expression a type and then, maybe, recorded how to do a particular implicit conversion in some way that didn't interfere so much with the expression tree.

**Comment by rjmccall** [comment]
Hmm.  The downside is that I can't really pull this change into swift-4.0-branch without pulling at least #9637.

**Pull request merged**
