### PR TITLE
[SILGen] Gave arguments lexical lifetimes.

### PR DESCRIPTION
**Pull request by nate-chandler**
When the frontend flag -enable-experimental-lexical-lifetimes is passed, arguments of non-trivial, non-address types get lexical borrow scopes.  The borrow scope begins in the function prolog.  Usages of the arguments are actually usages of the borrowed value.  The borrow scope is ended when the function's scope ends.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by atrick — APPROVED** [review]
Looks like basically the right idea

**Comment by nate-chandler** [comment]
@swift-ci please clean test windows platform

**Comment by nate-chandler** [comment]
@swift-ci please clean test windows platform

**Pull request merged**
