### PR TITLE
[DebugInfo] Emit distinct DILocation for different inline instances

### LINKED ISSUE #55703: [SR-13263] Invalid Debug Information Generation
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13263      |
   |Radar             | None         |
   |Original Reporter | @compnerd      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963900-471558bd-8a5b-48c6-9c51-3a16a7f09fde.gz)

      
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 3         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | @adrian-prantl      |
   |Priority          | Medium      |

   

   md5: 1cf1abd3137f286141ea88df6a315030

  </details>

**Issue Description:**

lit test reproducer:

``` swift
// RUN: %empty-directory(%t)
// RUN: %target-swiftc_driver -DM -emit-module -emit-module-path %t/M.swiftmodule %s -module-name M
// RUN: not --crash %target-swiftc_driver -O -g -I %t -c %s -o /dev/null

#if M
import _Differentiation

public struct S<T> {
  class C {}
  let c: C
  internal var b: Bool
}

extension S: AdditiveArithmetic {
  public static var zero: S { fatalError() }

  public static func == (_ lhs: S, _ rhs: S) -> Bool { fatalError() }
  public static func + (_ lhs: S, _ rhs: S) -> S { fatalError() }
  public static func - (_ lhs: S, _ rhs: S) -> S { fatalError() }
}

extension S: Differentiable {
  public typealias TangentVector = S
}

#else
import _Differentiation
import M

struct T: Differentiable {
  var u1: U
  var u2: U
}

struct U: Differentiable {
  var s: S<Float>
  var v: V
}

struct V: Differentiable {
  var s: S<Float>
}
#endif
```

Crash:

```
swift-frontend: swift-dev/llvm-project/llvm/lib/CodeGen/AsmPrinter/DwarfExpression.cpp:572: void llvm::DwarfExpression::addFragmentOffset(const llvm::DIExpression *): Assertion `FragmentOffset >= OffsetInBits && "overlapping or duplicate fragments"' failed.
Stack dump:
1.  Swift version 5.3-dev (LLVM 6d510c802af0d59, Swift 3e090b483352b3c)
2.  Running pass 'Function Pass Manager' on module '/dev/null'.
3.  Running pass 'X86 Assembly Printer' on function '@"$s4null1TV4move5alongyAC13TangentVectorV_tF"'
```

### PR DESCRIPTION
**Pull request by asavonic**
LLVM seems to determine a variable instance as a combination of DILocalVariable
and DILocation. Therefore if multiple llvm.dbg.declare have the same
variable/location parameters, they are considered to be referencing the same
instance of variable.

Swift IRGen emits a set of llvm.dbg.declare calls for every variable
instance (with unique SILDebugScope), so it is important that these calls have
distinct variable/location parameters. Otherwise their DIExpression may be
incorrect when treated as referencing the same variable. For example, if they
have a DIExpression with fragments, we will see this as multiple declarations of
the same fragment. LLVM detects this and crashes with assertion failure:

DwarfExpression.cpp:679: void llvm::DwarfExpression::addFragmentOffset(const
llvm::DIExpression *): Assertion `FragmentOffset >= OffsetInBits &&
"overlapping or duplicate fragments"' failed.

The patch resolves #55703. The LIT test (debug_scope_distinct.swift) is the
reproducer from that issue.

### CODE REVIEW

**Comment by asl** [comment]
@swift-ci please test

**Comment by asavonic** [comment]
The LIT test is a bit too minimal - it has some undefs in IR, which does not play nicely with optimizations. I cannot reproduce CI failures locally, but the issue is obvious. I'll change the test to avoid undefs, and we can try again.

**Comment by asl** [comment]
@swift-ci please test

**Comment by asl** [comment]
@swift-ci please test

**Comment by asl** [comment]
@swift-ci please test

**Comment by asl** [comment]
@swift-ci please test macos platform

**Comment by asl** [comment]
@swift-ci please test macos platform

**Comment by asl** [comment]
@swift-ci please test

**Comment by asl** [comment]
@adrian-prantl ping :)

**Comment by asavonic** [comment]
@adrian-prantl, can you please check if the patch is OK?

**Comment by asl** [comment]
@adrian-prantl Gentle ping

**Comment by adrian-prantl** [comment]
(Sorry for the delayed response, I've been on vacation)

In the reproducer, the inlined-at locations are all at line 0 and it looks like that is the actual problem. I think it would be okay to emit line 0 inlined-at locations as distinct to avoid this problem, but a better solution would be to ensure the autodifferentiation transformation would assign meaningful line numbers. Inlined functions with no source location at the call site are not a great user experience.

Would you mind changing the patch to only apply the distinct locations to line-0 call sites?

**Comment by asavonic** [comment]
Right, it seems that the compiler lost the actual line number somewhere, and it is better to fix this issue.
However, these locations are tied to the same local variable (multiple instances of it after inlining), so the correct line number would also be the same for both, and we're back to the same problem.

**Comment by asavonic** [comment]
> though I'd prefer we could assert that no function call is on line 0.

This is likely because these calls are artificial, and generated by the compiler to support differentiation.
I will check if this is the case.

>> However, these locations are tied to the same local variable (multiple instances of it after inlining), so the correct line number would also be the same for both, and we're back to the same problem.

> I don't think that's true. If the same function is inlined multiple times, and locations are tracked correctly, then the inlined call sites would differ and the locations would be distinct.

Without the patch, all it takes to get a collision of `inlinedAt` locations is for them to have the same source line and scope.
Lines are not unique in general: we can have multiple inlined calls on the same *source* line.
Scopes (DISubprogram in this case) are not unique either, at least we don't have a unique scope for each inline instance.

I think this is the same problem that LLVM had back in the day:
https://github.com/llvm/llvm-project/commit/df706288fba670943e164893e1fa0ccda3e24895

**Comment by adrian-prantl** [comment]
Okay, if LLVM also generates all inlinedAt locations as distinct, we should match that behavior. One thing I was worried about here was that we would generate distinct inlinedAt information for two instructions originating from the same inlined call, however, these should share the same SILDebugScope on so the caching mechanism should prevent this from happening.

LGTM! And thanks for pointing this out.

**Review by adrian-prantl — APPROVED** [review]

**Comment by finagolfin** [comment]
[This is failing on Android armv7](https://ci-external.swift.org/job/oss-swift-RA-linux-ubuntu-16.04-android/4861/consoleText), similar to previous tests that were disabled for 32-bit in #66879:
```
Command Output (stderr):
--
/home/ubuntu/jenkins/workspace/oss-swift-RA-linux-ubuntu-16.04-android/swift/test/IRGen/debug_scope_distinct.swift:10:11: error: CHECK: expected string not found in input
// CHECK: call void @llvm.dbg.value(metadata {{.*}} %[[ARG0]], metadata ![[VAR1:[0-9]+]], metadata !DIExpression(DW_OP_LLVM_fragment, 0, 64)), !dbg ![[LOC1:[0-9]+]]
          ^
<stdin>:1030:42: note: scanning from here
 %.sroa.013.0.copyload = load ptr, ptr %0, align 4, !dbg !286
                                         ^
<stdin>:1030:42: note: with "ARG0" equal to "\\.sroa\\.013\\.0\\.copyload"
 %.sroa.013.0.copyload = load ptr, ptr %0, align 4, !dbg !286
                                         ^
<stdin>:1078:2: note: possible intended match here
 call void @llvm.dbg.value(metadata i64 %22, metadata !280, metadata !DIExpression(DW_OP_LLVM_fragment, 40, 64)), !dbg !309
 ^

Input file: <stdin>
Check file: /home/ubuntu/jenkins/workspace/oss-swift-RA-linux-ubuntu-16.04-android/swift/test/IRGen/debug_scope_distinct.swift

-dump-input=help explains the following input dump.

Input was:
<<<<<<
            .
            .
            .
         1025:  call void @llvm.dbg.declare(metadata ptr %3, metadata !268, metadata !DIExpression()), !dbg !283 
         1026:  call void @llvm.lifetime.start.p0(i64 5, ptr nonnull %2), !dbg !286 
         1027:  call void @llvm.lifetime.start.p0(i64 5, ptr nonnull %3), !dbg !286 
         1028:  call void @llvm.dbg.value(metadata ptr %0, metadata !266, metadata !DIExpression(DW_OP_deref)), !dbg !286 
         1029:  call void @llvm.dbg.value(metadata ptr %1, metadata !267, metadata !DIExpression(DW_OP_deref)), !dbg !286 
         1030:  %.sroa.013.0.copyload = load ptr, ptr %0, align 4, !dbg !286 
check:10'0                                              X~~~~~~~~~~~~~~~~~~~~ error: no match found
check:10'1                                                                    with "ARG0" equal to "\\.sroa\\.013\\.0\\.copyload"
         1031:  call void @llvm.dbg.value(metadata ptr %.sroa.013.0.copyload, metadata !280, metadata !DIExpression(DW_OP_LLVM_fragment, 0, 32)), !dbg !287 
check:10'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         1032:  %.sroa.414.0..u1.sroa_idx = getelementptr inbounds i8, ptr %0, i32 4, !dbg !286 
check:10'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         1033:  %.sroa.414.0.copyload = load i8, ptr %.sroa.414.0..u1.sroa_idx, align 4, !dbg !286 
check:10'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         1034:  call void @llvm.dbg.value(metadata i8 %.sroa.414.0.copyload, metadata !280, metadata !DIExpression(DW_OP_LLVM_fragment, 32, 8)), !dbg !287 
check:10'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         1035:  %.sroa.515.0..u1.sroa_idx = getelementptr inbounds i8, ptr %0, i32 5, !dbg !286 
check:10'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            .
            .
            .
         1073:  %.sroa.4.0..u2.sroa_idx = getelementptr inbounds %T4main1TV13TangentVectorV, ptr %0, i32 0, i32 2, i32 0, i32 1, !dbg !286 
check:10'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         1074:  %.sroa.4.0.copyload = load i8, ptr %.sroa.4.0..u2.sroa_idx, align 4, !dbg !286 
check:10'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         1075:  call void @llvm.dbg.value(metadata i8 %.sroa.4.0.copyload, metadata !280, metadata !DIExpression(DW_OP_LLVM_fragment, 32, 8)), !dbg !309 
check:10'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         1076:  %.sroa.5.0..u2.sroa_idx = getelementptr inbounds %T4main1TV13TangentVectorV, ptr %0, i32 0, i32 2, i32 1, !dbg !286 
check:10'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         1077:  %22 = load i64, ptr %.sroa.5.0..u2.sroa_idx, align 1, !dbg !286 
check:10'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         1078:  call void @llvm.dbg.value(metadata i64 %22, metadata !280, metadata !DIExpression(DW_OP_LLVM_fragment, 40, 64)), !dbg !309 
check:10'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
check:10'2      ?                                                                                                                           possible intended match
         1079:  %.u26 = getelementptr inbounds %T4main1TV, ptr %1, i32 0, i32 2, !dbg !286 
check:10'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         1080:  call void @llvm.dbg.value(metadata ptr %.u26, metadata !281, metadata !DIExpression(DW_OP_deref)), !dbg !309 
check:10'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         1081:  %23 = load ptr, ptr %.u26, align 4, !dbg !310 
check:10'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         1082:  %.u26.s.b = getelementptr inbounds %T4main1TV, ptr %1, i32 0, i32 2, i32 0, i32 1, !dbg !310 
check:10'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         1083:  %24 = load i8, ptr %.u26.s.b, align 4, !dbg !310 
check:10'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            .
            .
            .
>>>>>>
```
@felipepiovezan, can you check if this test is failing on watchos too?

**Comment by adrian-prantl** [comment]
@asavonic This may just be too dependent on the architecture. Can you put a REQUIRES on the test that limits it to 64 bit architectures?

**Comment by asavonic** [comment]
@finagolfin, @adrian-prantl, thank you for letting me know, I missed the follow-up patch that disabled these tests for watchOS. Can you please check the patch #67699?

**Pull request merged**
