### PR TITLE
[Parse][CodeCompletion] Stop code completion within a closure causing parser recovery after the closure.

### PR DESCRIPTION
**Pull request by nathawes**
For example, the completion below would trigger error recovery within the first closure, which we recover from by skipping to that closure's right brace. The fact that we recovered though, wasn't being recorded. The closure was treated as still being in error, triggering another recovery after it that skips over the `Thing` token, giving a lone closure expression, rather than a
call as the next expression.
```
CreateThings {
    Thing { point in
      print("hello")
      point.#^HERE^#
    }
    Thing { _ in }
}
```
This isn't an issue for code completion when the outer closure is a regular closure, but when it's a function builder, invalid elements result in no types being applied (no valid solutions) and we end up with no completion results. We should have a fallback to handle when the other elements are legitimately invalid (rather than from parser recovery skipping things), but when the other elements *are* valid this fix gets us results in the meantime and should still give more accurate results compared to a single-function-builder-element fallback once we have one.

The fix here is removing the error status from the parser result after the initial parser recovery. We still needed to propagate the fact that the parsed AST node contained a code completion token though, so that the code completion callbacks still happen. This required dropping the invariant that `ParserResult::hasCodeCompletion()` implies `ParserResult::isError()`. To ensure there was no unintended behavior change, this updates existing checks of `ParserResult::isError()` that weren't directly related to this fix to use `ParserResult::isErrorOrHasCompletion()` instead (which is equivalent to the behavior of `isError()` prior to this change).

### CODE REVIEW

**Comment by nathawes** [comment]
@swift-ci please test

**Review by rintaro — APPROVED** [review]
LGTM!

We should eventually remove `setHasCodeCompletionAndIsError()` because parsing code completion token doesn't necessarily mean "is error". We can use `result.setHasCodeCompletion(); result. setIsParseError()` where both are actually needed. But I suspect we don't need `setIsParseError()` in most cases.

**Review by xedin — COMMENTED** [review]
Awesome! Quick question - if there are multiple completion tokens in the file, would parser detect both - an error and a completion expression at the same time? It seems that it would be useful to add a test so that function builder has multiple code completion tokens.

**Comment by rintaro** [comment]
@xedin There can't be multiple code completion token in a code completion invocation. If there's `\0` character in a file and it's not at `Lexer.CodeCompletionPtr`, they are just invalid source characters.

In `swift-ide-test`, if there're multiple tokens (`#^NAME^#`) in a file, other tokens are completely removed from the file when testing a token. For example, given:
```
Thing {
  foo.#^FOO^#
  bar.#^BAR^#
}
```
The source file is converted to:
```
Thing {
  foo.\0
  bar.
}
```
When testing `#^FOO^#`.

**Comment by xedin** [comment]
@rintaro This might be a side effect but while Nathan and I were working on the member completion changes I have found a case where unrelated completion token was converted into `ErrorExpr` - `test/IDE/complete_skipbody.swift` - while completing `#^FUNCTIONBODY^#` `value.#^LOCALFUNC_PARAMINIT^#` became `ErrorExpr`. I had to adjust constraint generation to avoid failing on multi-statement closure bodies (https://github.com/apple/swift/pull/33590).

**Comment by nathawes** [comment]
Right, `bar.` with a missing member after it like in Rintaro's example would become an ErrorExpr. What test case specifically are you after? A separate ErrorExpr in the same closure as the completion expr?

**Comment by xedin** [comment]
@nathawes That, and somewhere else but in the same function builder body so we had all cases covered.

**Comment by xedin** [comment]
It's not as important for the a regular code because all expressions are type-checked separately but function builders are a different story - whole body is one giant constraint system, so we need to make sure `ErrorExpr` from other completion tokens don't interfere.

**Comment by nathawes** [comment]
@swift-ci please smoke test

**Pull request merged**
