### PR TITLE
build: remove `SWIFT_NEED_EXPLICIT_LIBDISPATCH` (NFC)

### PR DESCRIPTION
**Pull request by compnerd**
This flag was being used as an alias for whether or not the host is
non-Darwin.  Rather than adding custom checks for this, use the explicit
check that CMake supports.  This simplifies the logic and avoids the
proliferation of custom variables which can become confusing for others
who are not familiar with the custom build infrastructure.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by davezarzycki** [comment]
@compnerd – This change makes libdispatch now required on non-Darwin platforms when previously it was not required. When/where was this dependency change discussed? If it was not discussed, can we please revert this change?

**Pull request merged**
