### PR TITLE
[AST] Perf: targeted use of __builtin_assume() in dyn_cast wrappers

### PR DESCRIPTION
**Pull request by davezarzycki**
Workaround:
https://bugs.llvm.org/show_bug.cgi?id=35790
See also:
https://bugs.llvm.org/show_bug.cgi?id=28430

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please test and merge

**Comment by davezarzycki** [comment]
@swift-ci please test and merge

**Comment by gottesmm** [comment]
@davezarzycki Can you post in the llvmbugs that this worked as a workaround?

**Comment by davezarzycki** [comment]
@gottesmm – In fact, I learned about the workaround from LLVM problem 28430. In that report, they tried the workaround, it failed during testing due to what was then believed to be temporary bugs in clang. After that, work on 28430 stalls.

**Comment by gottesmm** [comment]
@davezarzycki Ah ok. SGTM. Thanks!

**Pull request merged**
