### PR TITLE
Be conservative with classifying some casts that could change in the future.

### PR DESCRIPTION
**Pull request by jckarter**
- Existentials may eventually be able to conform to protocols
- Functions may grow new arms we haven't designed and implemented yet,
  which could influence how they cast in the future.

rdar://problem/38684452

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
Failures look unrelated...

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Review by rjmccall — APPROVED** [review]
Seems reasonable.

**Pull request merged**
