### PR TITLE
[stdlib] Fixed image inspection for Win32

### PR DESCRIPTION
**Pull request by tinysun212**
Removed calling FreeLibrary().
See GetModuleHandle function in MSDN.

### CODE REVIEW

**Comment by tinysun212** [comment]
@swift-ci Please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by LuizZak** [comment]
Relevant snip:

> The **GetModuleHandle** function returns a handle to a mapped module without incrementing its reference count. However, if this handle is passed to the **FreeLibrary** function, the reference count of the mapped module will be decremented. Therefore, do not pass a handle returned by **GetModuleHandle** to the **FreeLibrary** function. Doing so can cause a DLL module to be unmapped prematurely.

\- https://msdn.microsoft.com/en-us/library/windows/desktop/ms683199(v=vs.85).aspx)

**Comment by CodaFi** [comment]
Good catch.

**Pull request merged**
