### PR TITLE
[CodeCompletion] Use --strip-trailing-cr for diff test

### PR DESCRIPTION
**Pull request by rintaro**
https://ci-external.swift.org/job/oss-swift-windows-x86_64-vs2019/739/

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by 3405691582** [comment]
Could you instead strip with sed and then diff? --strip-trailing-cr is a GNU extension and not available on all platforms.

**Comment by rintaro** [comment]
@swift-ci Please smoke test OS X platform

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test Linux

**Pull request merged**
