### PR TITLE
[3.0] IRGen: Add missing bitcasts to emitNativeUnowned* operations.

### PR DESCRIPTION
**Pull request by jckarter**
Fixes rdar://problem/27664203.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swiftix Does this look good for Swift 3?

**Comment by tkremenek** [comment]
CI config issue for mac OS failure.  Will re-run in a minute

**Comment by tkremenek** [comment]
@swift-ci test os x

**Comment by jckarter** [comment]
@tkremenek Looks like there's still some kind of config issue with the second run.

**Comment by tkremenek** [comment]
@jckarter On it.

**Comment by tkremenek** [comment]
@swift-ci test os x

**Comment by swiftix** [comment]
@jckarter LGTM. I'm testing it now on the original project mentioned in the radar, just for the case.

**Comment by swiftix** [comment]
@jckarter I can confirm, it fixes the original problem reported in the radar. Thanks!

**Comment by jckarter** [comment]
@swiftix Thanks! Does this test failure look familiar? It looks unrelated to this change.

```
******************** TEST 'Swift(macosx-x86_64) :: SILOptimizer/copyforward.sil' FAILED ********************
14:55:31 Script:
14:55:31 --
14:55:31 xcrun --toolchain default --sdk /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-3.0-branch/buildbot_incremental/swift-macosx-x86_64/bin/sil-opt -target x86_64-apple-macosx10.9  -module-cache-path '/var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/swift-testsuite-clang-module-cachehpXeuX' -enable-sil-verify-all /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-3.0-branch/swift/test/SILOptimizer/copyforward.sil -copy-forwarding -enable-copyforwarding -enable-destroyhoisting | FileCheck /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-3.0-branch/swift/test/SILOptimizer/copyforward.sil
14:55:31 --
14:55:31 Exit Code: 1
14:55:31 
14:55:31 Command Output (stderr):
14:55:31 --
14:55:31 
/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-3.0-branch/swift/test/SILOptimizer/copyforward.sil:257:10: error: expected string not found in input
14:55:31 //CHECK: copy_addr
14:55:31          ^
14:55:31 <stdin>:283:169: note: scanning from here
14:55:31 sil_scope 12 { loc "/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-3.0-branch/swift/test/SILOptimizer/copyforward.sil":260:13 parent @backward_takenoinit : $@convention(thin) <τ_0_0> () -> @out τ_0_0 }
14:55:31 <stdin>:283:173: note: possible intended match here
14:55:31 sil_scope 12 { loc "/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-3.0-branch/swift/test/SILOptimizer/copyforward.sil":260:13 parent @backward_takenoinit : $@convention(thin) <τ_0_0> () -> @out τ_0_0 }
14:55:31 <stdin>:294:2: error: CHECK-NOT: string occurred!
14:55:31  copy_addr [take] %1 to %0 : $*T, loc "/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-3.0-branch/swift/test/SILOptimizer/copyforward.sil":266:3, scope 12 // id: %5
14:55:31  ^
14:55:31 /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-3.0-branch/swift/test/SILOptimizer/copyforward.sil:273:14: note: CHECK-NOT: pattern specified here
14:55:31 //CHECK-NOT: copy_addr
14:55:31              ^
14:55:31 
```

**Comment by swiftix** [comment]
@jckarter No, this test failure doesn't look familiar. I cannot remember seeing it.

**Comment by jckarter** [comment]
The failure did not repro in master, and I don't think it can possibly be related to this patch, which only touches IRGen. Any ideas @eeckstein or @aschwaighofer ?

**Comment by aschwaighofer** [comment]
I don't see how this commit can possibly affect the outcome of the SIL optimizer.

(Other than unrelated non deterministic uninitialized memory bugs)

**Comment by eeckstein** [comment]
no idea either

**Pull request merged**
