### PR TITLE
Front-end: EmitSyntax action should use the syntax tree generated from parser.

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci Please clean test Linux platform

**Comment by harlanhaskins** [comment]
Now that this is switched over, final nail in the coffin for `LegacyASTTransformer`?

**Comment by nkcsgexi** [comment]
@harlanhaskins I just cannot wait to remove that whole file 😈

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Pull request merged**
