### PR TITLE
Mark ObjC-only String entry points 'dynamic' to avoid emitting Swift entry points for them

### PR DESCRIPTION
**Pull request by Catfish-Man**

### CODE REVIEW

**Comment by Catfish-Man** [comment]
@swift-ci please smoke benchmark

**Comment by jrose-apple** [comment]
Does it matter if they're all `internal` anyway?

**Comment by Catfish-Man** [comment]
> Does it matter if they're all `internal` anyway?

It avoids a layer of thunks, unfortunately

**Comment by Catfish-Man** [comment]
@swift-ci please smoke benchmark

**Comment by Catfish-Man** [comment]
@swift-ci please smoke benchmark

**Comment by Catfish-Man** [comment]
Most of those "wins" don't actually use this code, so I'm calling that a no

**Pull request closed without merging**
