### PR TITLE
[Sema] Fix a couple of property override crashers

### PR DESCRIPTION
**Pull request by hamishknight**
Adjust `buildStorageReference` to handle metatype self parameters, and to ignore property wrapper mutability when not accessing via the wrapped value.

Resolves SR-12443 & SR-12456.
Resolves rdar://problem/61090634.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Comment by hamishknight** [comment]
@swift-ci please test macOS

**Review by slavapestov — APPROVED** [review]

**Pull request merged**
