### PR TITLE
[CopyPropagation] Replace LexicalDestroyHoisting with OwnedLifetimeCanonicalization.

### PR DESCRIPTION
**Pull request by nate-chandler**
Replace usages of lexical destroy hoisting with owned lifetime canonicalization now that the latter supports lexical values.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
```
### Performance (arm64): -O


### Code size: -O


### Performance (arm64): -Osize

**Regression**                          | **OLD** | **NEW** | **DELTA** | **RATIO**
:---                                    | ---:  | ---:    | ---:   | ---:
CharIteration_punctuated_unicodeScalars | 632.5 | 699.326 | +10.6% | **0.90x (?)**
ObserverUnappliedMethod                 | 257.0 | 279.608 | +8.8%  | **0.92x (?)**
&nbsp; | | | |
**Improvement**                         | **OLD** | **NEW** | **DELTA** | **RATIO**
StringSwitch                            | 203.0 | 161.846 | -20.3% | **1.25x**

### Code size: -Osize


### Performance (arm64): -Onone

**Regression**          | **OLD** | **NEW** | **DELTA** | **RATIO**
:---                    | ---:    | ---:    | ---:   | ---:
RawBufferCopyBytes      | 9.941   | 12.5    | +25.7% | **0.80x (?)**
&nbsp; | | | |
**Improvement**         | **OLD** | **NEW** | **DELTA** | **RATIO**
SortArrayInClass        | 65354.0 | 52081.0 | -20.3% | **1.25x (?)**
Set.isStrictSubset.Box0 | 66.75   | 61.5    | -7.9%  | **1.09x**

### Code size: -swiftlibs
```

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Review by atrick — APPROVED** [review]
Nice!

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please clean test windows platform

**Comment by nate-chandler** [comment]
@swift-ci please clean test linux platform

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Review by atrick — APPROVED** [review]
Fantastic! This would be too confusing without the precise comments!

As already discussed:

It would help to elaborate in the comment on liveness vs. pruned liveness (this utility doesn't distinguish them).

Possibly cleanup the APIs so it's always clear whether dead-end blocks are considered.

When the dead block is also LiveOut:
```
case PrunedLiveBlocks::LiveOut:
  assert(asImpl().isDefBlock(block))
  return isInstructionLive(inst, /*isLive=*/true)
```

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Comment by nate-chandler** [comment]
@swift-ci please smoke test linux platform

**Comment by nate-chandler** [comment]
@swift-ci please smoke test linux platform

**Pull request merged**
