### PR TITLE
[CS] A couple of cleanups

### PR DESCRIPTION
**Pull request by hamishknight**
- Remove `ConstraintGraph::removeEdge`, using `retireConstraint` instead.
- Avoid recording constraints as both "generated" and "retired".
- Clarify a doc comment.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Review by xedin — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
@swift-ci please test macOS

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
Debug source compat failure is unrelated.

**Pull request merged**
