### PR TITLE
[Concurrency] Apply `@preconcurrency` to typealiases at the point of use

### LINKED ISSUE #60487: `@preconcurrency` on a function `typealias` has no effect
**Describe the bug**
`@preconcurrency` on a function `typealias` has no effect. It should either have an effect as to would on a method taking a function or produce a diagnostics that it is not supported.

**Steps To Reproduce**
```swift
@preconcurrency typealias Callback = @Sendable () -> ()
func methodWithPreconcurrencyOnTypealias(callback: Callback) {}
@preconcurrency func methodWithPreconcurrencyOnMethod(callback: @Sendable () -> ()) {}

func usage() {
    var mutableVariable = 0
    methodWithPreconcurrencyOnTypealias {
        mutableVariable += 1 // sendable warning
    }
    
    methodWithPreconcurrencyOnMethod {
        mutableVariable += 1 // no sendable warning
    }
}
```

**Expected behavior**
It would be best if we wouldn't get a warning and `methodWithPreconcurrencyOnTypealias(callback:)` would be treated the same as `methodWithPreconcurrencyOnMethod(callback:)`. 
However, [`typealias` is no listed in `SE-0337` as a a nominal declaration where the `@preconcurrency` attribute can be used](https://github.com/apple/swift-evolution/blob/main/proposals/0337-support-incremental-migration-to-concurrency-checking.md#preconcurrency-attribute-on-nominal-declarations) and therefore should at least produce some diagnostics. 

**Screenshots**
Screenshot 2022-08-10 at 13 31 52

**Environment (please fill out the following information)**
 - OS: 13.0 Beta (22A5311f)
 - Xcode: Version 14.0 beta 5 (14A5294e)

### PR DESCRIPTION
**Pull request by DougGregor**
When referencing a `@preconcurrency` typealias from code that does not
require strict concurrency, strip off `@Sendable` and global actor
types. This is consistent with references to functions/properties/etc.
that are `@preconcurrency`.

Fixes https://github.com/apple/swift/issues/60487, https://github.com/apple/swift/issues/60488., rdar://98343624.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
Calling this a draft because I don't want to apply this transformation in the declaration of a `@preconcurrency` entity.

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by dnadoba** [comment]
Please correct me if I'm wrong but from my rough understanding of the code change and added tests it looks like this does **not** fix https://github.com/apple/swift/issues/60488.
There is also an open PR https://github.com/apple/swift/pull/60500 which says it fixes https://github.com/apple/swift/issues/60488.

**Pull request merged**
