### PR TITLE
[SymbolGraph] Add a test to ensure macros are output

### PR DESCRIPTION
**Pull request by bnbarham**

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
@QuietMisdreavus they were indeed there :)

**Review by QuietMisdreavus — APPROVED** [review]
Excellent, thanks for following up!

**Comment by bnbarham** [comment]
@swift-ci please smoke test macOS platform

**Comment by bnbarham** [comment]
@swift-ci please smoke test macOS platform

**Pull request merged**
