### PR TITLE
IRGen: fix get/store enum tag functions for big-endian platforms

### PR DESCRIPTION
**Pull request by mundaym**
Use sized loads and stores, rather than memcpy calls, to get and
set tag values in the payload and extra tag bytes. The code works
the same regardless of the endianness of the target platform.

### CODE REVIEW

**Comment by mundaym** [comment]
@jckarter Can you take a look at this? I'd also appreciate it if you could trigger the benchmark regression CI tests.

It's a similar fix to https://github.com/apple/swift/pull/19832 however I've approached the problem slightly differently. Instead of fixing up addresses on big endian platforms I've rewritten the code generator so that it no longer depends on the endianness of the target platform at all.

Since this code handles enums dynamically I'm not sure it makes sense to move it under the `EnumPayload` umbrella just yet.  We could perhaps come up with another abstraction (`EnumPayloadDynamic` maybe?).

Thanks.

**Comment by jckarter** [comment]
@swift-ci Please benchmark

**Comment by jckarter** [comment]
What does this achieve? It seems like a pretty severe code size cost, assuming LLVM doesn't just fold this back to a memcpy.

**Comment by mundaym** [comment]
Thanks for taking a look.

> What does this achieve?

We need to change this code to make it work on big-endian platforms. Without patching this code we can't run the tests to completion (with this PR we fail 11 validation tests at this point). `memcpy` isn't a portable way to copy data between values of different sizes. We can fix up the addresses to make it work but this way is much cleaner and more robust IMO.

> It seems like a pretty severe code size cost

It shouldn't cost anything really, and the benchmarks appear to back that up (except perhaps for the `SubstringString` comparison functions that I'll investigate). The new code doesn't cost any more because the old code called the `emitMemCpy` function which was manually unrolled to emit fixed size `memcpy` calls.

> There's already a runtime function that does this in the runtime implementation; maybe we could expose that and emit runtime calls instead of open-coding it.

We could replace the new `emitGetTag` and `emitSetTag` functions with a runtime call. For the code that sets/gets the payload value however I think the code in this PR is optimal (one fixed sized store followed by a `memset` to zero the rest of the payload).

**Comment by jckarter** [comment]
> It shouldn't cost anything really, and the benchmarks appear to back that up (except perhaps for the SubstringString comparison functions that I'll investigate). The new code doesn't cost any more because the old code called the emitMemCpy function which was manually unrolled to emit fixed size memcpy calls.

I didn't realize we were already open-coding this. It'd be nice to fix that, since `small_memcpy` already exists in the runtime for this purpose. I think it's used exclusively for enum tag manipulation, so we could adapt it to be the get/set tag entry point that does the right thing for big-endian platforms.

**Comment by mundaym** [comment]
> I didn't realize we were already open-coding this. It'd be nice to fix that, since small_memcpy already exists in the runtime for this purpose. I think it's used exclusively for enum tag manipulation, so we could adapt it to be the get/set tag entry point that does the right thing for big-endian platforms.

I've thought about this a bit and I'm not sure it makes sense to call the runtime version of `small_memcpy` from the generated code. The open coded version included here should compile down to just over 10 instructions on x86_64 (roughly: https://godbolt.org/z/kcmcUl). Though it does take more instructions on machines without fast unaligned accesses. A function call is likely to require (at least) a few instructions anyway and the open coded version probably benefits from very predictable branches.

So if we care about the performance of this generated code then I think we should continue to open code the get/set tag functionality. If on the other hand we *don't* really care about the performance of this generated code then I think it would make more sense to call the higher level runtime functions instead as that would allow us to simplify IRGen a lot more.

Regardless, to me it makes sense to separate that change from this one to minimize the impact of this change on performance (in case, for example, it causes a regression and needs to be rolled back).

**Comment by jckarter** [comment]
I suspect that code size is more important than performance here, since unspecialized code is generally undesirable on hot paths, so the higher-level we can go with runtime entry points, the better. I'm fine with splitting that off as a different change.

**Comment by mundaym** [comment]
Thanks. I'll take a look at calling out to the runtime but I'd like to merge this PR (or something similar to it) if possible anyway to reduce the number of patches we are maintaining. Are there any changes you'd like me to make?

I can't recreate the performance regressions on my laptop (Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz) so I think the benchmark changes are just (alignment?) noise. I don't think they are hitting the modified code paths anyway.

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by mundaym** [comment]
Is this OK to be merged now? (I don't have commit access.) Thanks!

**Comment by jckarter** [comment]
Done. Thanks!

**Pull request merged**
