### PR TITLE
Preserve TypeAliasType sugar when substituting types

### PR DESCRIPTION
**Pull request by slavapestov**
Follow-up to https://github.com/apple/swift/pull/27280. Fixes <rdar://problem/45313760>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@DougGregor There are a few places where we previously built TypeAliasType by hand; those can be simplified now because they shouldn't be needed. But I was running into a few problems so I think this part can land separately.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility Release

**Comment by slavapestov** [comment]
https://github.com/apple/swift-lldb/pull/2014
@swift-ci Please smoke test

**Review by DougGregor — COMMENTED** [review]
Very nice! Am I wrong to be thinking how we've set the stage for reworking `BoundGenericType` to work via `SubstitutionMap`?

**Pull request merged**
