### PR TITLE
Refuse to import C arrays that are longer than 4096

### PR DESCRIPTION
**Pull request by dnadoba**
C arrays of size N are imported as N-element tuples in swift. Arrays past 1024 starts exhibiting semi-exponential behaviour in time. This Pull request refuses to import arrays that are longer than 4096. We chose 4096 as the upper limit because we don't want to break arrays of size PATH_MAX.

I'm contributing to swift for the first time. I appreciate any feedback.

Resolves [SR-9373](https://bugs.swift.org/browse/SR-9373).

### CODE REVIEW

**Comment by jrose-apple** [comment]
Thanks for picking this up, David, and welcome to the project! This implementation looks good, but I suggest adding a few more tests:

- A struct containing a too-large array should still be imported; that particular field should just be dropped. (We handle this specifically in our IRGen.)

- A parameter type that's *just* the too-large array (as opposed to the array-of-arrays you have here) should also still be imported as a pointer to the element type. There's pretty much no way this could break given the current way the code is written, but we should still have a test for it!

I'll start the source compat tests now, but since new tests will reset the "some checks haven't completed yet" status I'll just wait for the normal tests.

@swift-ci Please test source compatibility

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Review by jrose-apple — APPROVED** [review]

**Comment by dnadoba** [comment]
@jrose-apple can you merge it please?

**Comment by jrose-apple** [comment]
Whoops! Meant to come back to this and then let it slip. Thanks, David!

**Pull request merged**
