### PR TITLE
[ConstraintSystem] Make binding producer responsible for adjustments to the binding set

### PR DESCRIPTION
**Pull request by xedin**
Since wrapping bindings into optional type based on `ExpressibleByNilLiteral` or
adjusting position of `Any` doesn't affect ranking it could be performed by
`TypeVarBindingProducer` instead.

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please smoke test compiler performance

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please smoke test compiler performance

**Comment by xedin** [comment]
Ok, some more heap use in debug mode I think we could leave with until the refactoring of potential bindings is complete which would offset that.

**Comment by xedin** [comment]
@swift-ci please clean test

**Review by hborla — APPROVED** [review]

**Pull request merged**
