### PR TITLE
[SE-0091] Require member operators to refer to the enclosing nominal type

### PR DESCRIPTION
**Pull request by DougGregor**
#### What's in this pull request?

Member operators should be placed within a nominal type (or extension
thereof) that they operate on. Aside from being good style, enforcing
this in the type checker can help with dependency tracking.
#### Resolved bug number: ([rdar://problem/27536066](rdar://problem/27536066))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

A smoke test on macOS does the following:
1. Builds the compiler incrementally.
2. Builds the standard library only for macOS. Simulator standard libraries and
   device standard libraries are not built.
3. lldb is not built.
4. The test and validation-test targets are run only for macOS. The optimized
   version of these tests are not run.

A smoke test on Linux does the following:
1. Builds the compiler incrementally.
2. Builds the standard library incrementally.
3. lldb is built incrementally.
4. The swift test and validation-test targets are run. The optimized version of these
   tests are not run.
5. lldb is tested.

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

…

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@jrose-apple, these feel like reasonable restrictions to aid dependency analysis

@rudkx, can you review?

**Comment by jrose-apple** [comment]
I haven't thought through 100% whether this restriction is sufficient. We still do overload resolution on the full set of operators, and sometimes that helps select the types of the operands.

**Comment by rudkx** [comment]
@shahmishal The linux failure here looks like either a configuration problem or perhaps something spurious.

**Comment by rudkx** [comment]
@jrose-apple Can you give an example of where this might be overly permissive?

**Comment by rudkx** [comment]
@DougGregor LGTM. I'll cherry-pick to swift-3.0-branch, fill out the template, and kick off a new PR.

**Pull request merged**
