### PR TITLE
[Macros] Use 'LibraryPluginProvider' in swift-plugin-server

### PR DESCRIPTION
**Pull request by rintaro**
Move `PluginProvider` logic to `SwiftCompilerPluginMessageHandling` module so the compiler can reuse that logic for the in-process plugins (in follow-ups)

Remove `CPluginServer` as nothing uses it anymore

### CODE REVIEW

**Comment by rintaro** [comment]
https://github.com/apple/swift-syntax/pull/2300
@swift-ci Please smoke test

**Comment by rintaro** [comment]
https://github.com/apple/swift-syntax/pull/2300
@swift-ci Please smoke test

**Comment by rintaro** [comment]
https://github.com/apple/swift-syntax/pull/2300
@swift-ci Please smoke test

**Comment by rintaro** [comment]
https://github.com/apple/swift-syntax/pull/2300
@swift-ci Please smoke test

**Comment by rintaro** [comment]
https://github.com/apple/swift-syntax/pull/2300
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
https://github.com/apple/swift-syntax/pull/2300
@swift-ci Please smoke test

**Comment by rintaro** [comment]
https://github.com/apple/swift-syntax/pull/2300
@swift-ci Please smoke test

**Comment by rintaro** [comment]
https://github.com/apple/swift-syntax/pull/2300
@swift-ci Please smoke test

**Comment by rintaro** [comment]
https://github.com/apple/swift-syntax/pull/2300
@swift-ci Please smoke test

**Comment by rintaro** [comment]
https://github.com/apple/swift-syntax/pull/2300
@swift-ci Please smoke test

**Review by hamishknight — APPROVED** [review]

**Review by ahoppen — APPROVED** [review]

**Comment by rintaro** [comment]
https://github.com/apple/swift-syntax/pull/2300
@swift-ci Please smoke test

**Pull request merged**
