### PR TITLE
Minor improvements to utils/update-checkout.py

### PR DESCRIPTION
**Pull request by mnvr**
Please see the individual commit messages for details.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please python lint

**Comment by mnvr** [comment]
I've added a new commit to fix the linting error.

**Comment by CodaFi** [comment]
@swift-ci please python lint

**Comment by CodaFi** [comment]
@swift-ci please python lint

**Comment by CodaFi** [comment]
LGTM, but I’m going to tag @gottesmm, the last person I can remember that updated core behavior in one of these scripts.

**Comment by mnvr** [comment]
Ping.

**Comment by CodaFi** [comment]
@mnvr I'm sorry we allowed this to sit for so long.  We can't take this patch in its current state. I'm going to see what I can do to salvage parts of the cleanups in the python component, but I'm afraid I have to close this due to age.

We will be much more diligent about keeping up with contributions like this in the future.  Thank you for everything you did here.

**Comment by mnvr** [comment]
@CodaFi No worries, and thank you for the detailed reply!

**Pull request closed without merging**
