### PR TITLE
[CoreGraphics] Make CGColor adopt _ExpressibleByColorLiteral. 

### PR DESCRIPTION
**Pull request by DougGregor**
The backflips here are because we cannot add initializers to imported
CF types; they would be factory initializers. Fixes
rdar://problem/32196175.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by jrose-apple** [comment]
Hm, that's still not sound, is it? Because there could be subclasses of CGColor that didn't implement the normal initializer?

**Comment by DougGregor** [comment]
You can't subclass CF types.

**Comment by jrose-apple** [comment]
A mere mortal can't subclass CF types, but they can still have subclasses, and none of their initializers are inherited.

**Pull request merged**
