### PR TITLE
Runtime: Fix undersized allocation for out-of-line optional cast result.

### PR DESCRIPTION
**Pull request by jckarter**
We accounted for the size difference between T and T? in the inline case, but not the out-of-line case. rdar://problem/27671131

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please ASAN test

**Comment by jckarter** [comment]
@rjmccall, Does this look good for Swift 3?

**Comment by gribozavr** [comment]
Could you add a targeted test for this issue?  Because it only broke in one test, we only have incidental coverage for this codepath.

**Comment by rjmccall** [comment]
Yes, this looks fine to me.  I agree that it's easier to just unconditionally allocate an extra byte than to worry about whether there are extra inhabitants.

**Comment by jckarter** [comment]
Yeah, it might be cleaner to summon the `Optional<T>` metadata and use its `allocateBuffer` witness to do this, but this seemed like a good minimal fix to get the bots clean again.

**Comment by gottesmm** [comment]
This needs tests.

**Comment by jckarter** [comment]
It's exercised by the existing test suite. The tests that were failing on the ASAN bot appear to be passing now:

```
PASS: Swift(macosx-x86_64) :: stdlib/Dictionary.swift (8019 of 8482)
PASS: Swift(macosx-x86_64) :: stdlib/Set.swift (8056 of 8482)
```

**Comment by gottesmm** [comment]
@jckarter Ok on the test... On another note, I don't think that the PR asan test works now. I think xin was looking into it but it is not clear to me if it was fixed.

**Comment by trentxintong** [comment]
I do not believe the ASAN external bots are fixed. Those are machines not controlled by us and the radar got pushed back because of WWDC and other releases.

**Comment by gribozavr** [comment]
> It's exercised by the existing test suite.

These is incidental coverage.  If someone changes how the infrastructure of those tests work, we will lose this coverage.

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by tkremenek** [comment]
@swift-ci test linux

**Comment by tkremenek** [comment]
@swift-ci test linux

**Comment by tkremenek** [comment]
@swift-ci test os x

**Comment by tkremenek** [comment]
@swift-ci test os x

**Comment by tkremenek** [comment]
@swift-ci test os x

**Comment by tkremenek** [comment]
@swift-ci test os x

**Comment by tkremenek** [comment]
ASAN testing timed out.

OS X testing failure *may* be infrastructure.  Re-running with wiped workspace.

**Comment by tkremenek** [comment]
From OS X:

~~~
/Users/buildnode/jenkins/workspace/swift-PR-osx/buildbot_incremental/swift-macosx-x86_64/test-iphonesimulator-i386/Serialization/Output/failed-clang-module.swift.tmp/MixModA.framework/Modules/module.modulemap:3:10: error: inferred submodules require a module with an umbrella
  module * { export * }
         ^
/Users/buildnode/jenkins/workspace/swift-PR-osx/buildbot_incremental/swift-macosx-x86_64/test-iphonesimulator-i386/Serialization/Output/failed-clang-module.swift.tmp/MixModA.framework/Modules/module.modulemap:3:10: error: inferred submodules require a module with an umbrella
  module * { export * }
         ^
~~~

**Comment by tkremenek** [comment]
@swift-ci test os x platform

**Comment by jckarter** [comment]
@tkremenek The ASAN bot at least tested the tests we were interested in. OS X is still failing on the same modulemap error, but that's almost definitely unrelated.

**Comment by jckarter** [comment]
@gribozavr Crafting a test that would reliably fail outside of asan will also require depending on incidental details of the allocator, AFAICT.

**Comment by gribozavr** [comment]
@jckarter I'm not asking for a test that would fail outside of ASan -- failing only under ASan is fine (that's why we have that bot); just for a test that would cover this codepath, and that is not an emergent behavior in other tests.

**Pull request merged**
