### PR TITLE
[stdlib] Implement Equatable/Comparable sequence algos in terms predicate ones

### PR DESCRIPTION
**Pull request by airspeedswift**
Raising this PR mainly for benchmarking, expecting the benchmarks to regress, but if they don't, this should be a code-size win.

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
Excellent! It is tempting to de-gyb this file entirely, given it's now down to documentation duplication. @natecook1000 what's your take?

**Comment by airspeedswift** [comment]
@swift-ci please smoke test compiler performance

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@swift-ci please benchmark

**Comment by airspeedswift** [comment]
@swift-ci please benchmark

**Comment by airspeedswift** [comment]
@swift-ci please smoke test compiler performance

**Comment by airspeedswift** [comment]
@swift-ci please test compiler performance

**Review by natecook1000 — APPROVED** [review]
De-gybbing sounds good—CollectionAlgorithms is already like that, so 👍

**Comment by airspeedswift** [comment]
@swift-ci please test compiler performance

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@swift-ci please test compiler performance

**Pull request merged**
