### PR TITLE
Revert "Add -prefix-serialized-debugging-options"

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/swift#39138

This is causing a failure on Windows: https://ci-external.swift.org/job/oss-swift-windows-x86_64-vs2019/6659/consoleText

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
CC: @drodriguez

**Comment by drodriguez** [comment]
Sorry about that. Is Windows CI not part of "please test" these days? I have to be explicit?

**Comment by compnerd** [comment]
It is, but it doesn't always trigger, so you should explicitly check for it.  @shahmishal might be able to identify why it didn't trigger.

**Comment by tbkka** [comment]
Merging to unblock other PRs that are failing on this.

**Pull request merged**
