### PR TITLE
[Parse] Consolidate parsing IfConfig clauses

### PR DESCRIPTION
**Pull request by rintaro**
`#if/#elseif/#else/#endif` parsing have 2 functions: statement-side and declaration-side.
They have many duplicated code which tend to accidentally be diverged (e.g. 3b42894f13a9d37df0b1ba8c22db89fdaa57823c).
This PR consolidate them.

Also, since fixing some issues around here will add fair amount of code, I split out related code into new `ParseIfConfig.cpp`
(I'm planning to fix [SR-3455](https://bugs.swift.org/browse/SR-3455), [SR-3663](https://bugs.swift.org/browse/SR-3663), [SR-3415](https://bugs.swift.org/browse/SR-3415), [SR-4032](https://bugs.swift.org/browse/SR-4032) and [SR-4031](https://bugs.swift.org/browse/SR-4031))

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
Awesome work -- thank you for putting so much effort into fixing up #if parsing!

**Comment by rintaro** [comment]
@bitjammer Could you review this?

**Comment by bitjammer** [comment]
Beauty. LGTM

**Comment by rintaro** [comment]
Thank you!
@swift-ci Please smoke test and merge

**Pull request merged**
