### PR TITLE
[silgen] Only borrow args for coroutines rather than general applies …

### PR DESCRIPTION
**Pull request by gottesmm**
…and do not conditionalize based off of the ownership flag being set.

This is the last part of SILGen conditionalized on EnableSILOwnership being
set. It also (as you can tell from the diff) eliminates a bunch of code from the
tests.

rdar://29791263

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by atrick** [comment]
I don't understand why coroutines would be handled differently than normal applies. A coroutine is itself a "scoped" operation". So it uses it's operands up to the end_apply. There's no reason to add another borrow scope around the coroutine.

**Comment by atrick** [comment]
That said, it look like these are mostly test case changes, and it would be easy to remove the `isForCoroutine` flag later... as long as the overall end design is that begin_apply/apply have the same ownership rules, but any code that determines lifetime based on apply arguments needs to also find the end_apply.

**Comment by gottesmm** [comment]
I talked with Andy offline. I am fine with having begin_apply/end_apply be like begin/end borrow for these uses. I do think it complicates the model slightly (since this is another formed of scoped use), but you could also argue the other way that considering apply and begin_apply as different things also complicates the model. Andy and I agreed that we will try this and if it confuses people down the line, we can put in the begin_borrow scope for coroutine. I am going to make that change in a subsequent commit though.

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Pull request merged**
