### PR TITLE
[NFC][Build System: build-script] Re-organized the build_swift module

### PR DESCRIPTION
**Pull request by Rostepher**
Re-organizes the `build_swift` module to maintain a similar nested structure to `swift_build_support` and other Python scripting that already exists in the project.

### CODE REVIEW

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by Rostepher** [comment]
@swift-ci please test and merge

**Comment by Rostepher** [comment]
@swift-ci please test

**Review by compnerd — APPROVED** [review]

**Pull request merged**
