### PR TITLE
swift-module-differ: refactor node definition to a separate file. NFC

### PR DESCRIPTION
**Pull request by nkcsgexi**
The original implementation file contains both nodes definition and detection
logics. This patch splits the two parts.

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by vivkong** [comment]
Hi @nkcsgexi, our nightly master branch build on s390x started failing with the following error after this refactoring:

```
/root/swift-master/swift/tools/swift-api-digester/ModuleAnalyzerNodes.cpp:1163: error: undefined reference to 'swift::ide::api::operator<<(llvm::raw_ostream&, swift::ide::api::SDKNodeKind)'
```

Any suggestions on how to fix this?  Thanks!

**Comment by nkcsgexi** [comment]
hmm, this operator is defined in [APIDigesterData.h](https://github.com/apple/swift/blob/master/include/swift/IDE/APIDigesterData.h#L61), which should be included in `ModuleAnalyzerNodes.cpp`. Could you try to move the operator declaration around and see if it could fix the error?

**Comment by vivkong** [comment]
Thanks @nkcsgexi.  We tried moving the definition of `SwiftDeclCollector::printTopLevelNames` from `ModuleAnalyzerNodes.cpp` to `ModuleAnalyzerNodes.h` and the build could continue.  Is it possible to make this change?

**Comment by nkcsgexi** [comment]
Hey @vivkong , I have an upcoming patch that may resolve the build failure you observed. I'll push it soon and ping you there.

**Comment by vivkong** [comment]
Thanks @nkcsgexi!  I will try your new changes when it's available.

I actually tried building on Ubuntu 18.04 and I didn't hit the compile error so I think it was clang.  I then updated my clang to a newer version on Ubuntu 16.04 and didn't see any compile error anymore.

**Pull request merged**
