### PR TITLE
Importer refactor

### PR DESCRIPTION
**Pull request by milseman**
```
Refactor some 3k lines of code from the class definition (nested 3
indentation levels) to static functions or out-of-line
definitions. Reduces some of code browsing burden of the class, though
I hope to do more cleanup to the file as a whole.

Move helper methods off of the Impl and into CFTypeInfo.h, where we
have the other CF type reasoning logic.

Many of the Impl's methods are relevant to only one file or task. Make
more of them static, and when possible, move them off of the Impl
class.

NFC
```

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please smoke test

**Comment by milseman** [comment]
@shahmishal any reason why I can't merge this after it passed all tests?

**Comment by gottesmm** [comment]
I am doing the master-next merge so the tree is locked. I sent out an announcement to apple-swift-dev on Friday.

Michael

**Pull request merged**
