### PR TITLE
[master-next][cmake] Fix zlib cmake issue: Target <X> links to target "ZLIB::ZLIB" but the target was not found

### PR DESCRIPTION
**Pull request by nathawes**
...after the changes in https://reviews.llvm.org/D79219.

Resolves rdar://problem/66057385

### CODE REVIEW

**Comment by nathawes** [comment]
@swift-ci please smoke test

**Comment by nathawes** [comment]
Looks like lldb has the same problem:
```
17:51:15 CMake Error at /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master-next/buildbot_incremental/llvm-macosx-x86_64/lib/cmake/llvm/AddLLVM.cmake:823 (add_executable):
17:51:15   Target "lit-cpuid" links to target "ZLIB::ZLIB" but the target was not
17:51:15   found.  Perhaps a find_package() call is missing for an IMPORTED target, or
17:51:15   an ALIAS target is missing?
17:51:15 Call Stack (most recent call first):
17:51:15   cmake/modules/AddLLDB.cmake:171 (add_llvm_executable)
17:51:15   utils/lit-cpuid/CMakeLists.txt:1 (add_lldb_executable)
```

**Comment by gottesmm** [comment]
@fredriss @JDevlieghere

**Review by compnerd — APPROVED** [review]

**Review by JDevlieghere — APPROVED** [review]
Thanks!

**Pull request merged**
