### PR TITLE
[IDE/completion] Hide clang decls that are marked as 'swift_private',…

### PR DESCRIPTION
**Pull request by benlangmuir**
#### What's in this pull request?

… from the code-completion results.

Backporting a fix from Swift 3.0 to Swift 2.3.

Conflicts:
    lib/IDE/CodeCompletion.cpp
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

rdar://problem/26659660

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by akyrtzi** [comment]
LGTM, thanks!

**Comment by benlangmuir** [comment]
@swift-ci Please smoke test

**Comment by benlangmuir** [comment]
The linux failures look unrelated.  The OS X bot is failing completely:
/Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/swift/utils/build-script: preset 'buildbot_incremental,tools=RA,stdlib=RD,smoketest=macosx' not found

**Comment by benlangmuir** [comment]
@shahmishal is the Swift 2.3 branch not working with smoke test presets?

**Pull request merged**
