### PR TITLE
Reformat driver arguments

### PR DESCRIPTION
**Pull request by Rostepher**
# Purpose

This is a follow-up PR to #12873. There's no functional changes in this PR, rather just a bunch of reformatting in the `driver_arguments.py` file to make all the argument parsing code more consistent.

I've moved all the top-level arguments into a single grouping at the top of the parser code. Then I re-formatted all string literals to use single rather than double quotes. Lastly I re-ordered the arguments passed to `parser.add_argument` such that `help` is always last (for readability) and `action` comes first.

rdar://34336890

### CODE REVIEW

**Comment by Rostepher** [comment]
Ignore the first handful of commits, those are from #12873. Once that's merged I'll rebase this branch and they should disappear.

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by Rostepher** [comment]
@swift-ci please smoke test

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by Rostepher** [comment]
@swift-ci please smoke test

**Review by lplarson — COMMENTED** [review]
LGTM

**Pull request merged**
