### PR TITLE
Implementing Core team resolution 2017 05 10

### PR DESCRIPTION
**Pull request by dabrahams**

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please test and merge

**Comment by dabrahams** [comment]
@swift-ci Please test and merge

**Comment by dabrahams** [comment]
@swift-ci Please test Mac OS Platform and merge

**Comment by dabrahams** [comment]
@swift-ci please test so x platform and merge

**Comment by dabrahams** [comment]
@swift-ci please test so x platform and merge

**Comment by dabrahams** [comment]
@swift-ci please test os x platform and merge

**Comment by dabrahams** [comment]
@swift-ci please test os x platform and merge

**Comment by dabrahams** [comment]
@swift-ci Please smoke test OS X platform

**Comment by dabrahams** [comment]
@swift-ci please test and merge

**Comment by dabrahams** [comment]
@swift-ci please test and merge

**Comment by dabrahams** [comment]
@swift-ci please test OS X platform and merge

**Comment by dabrahams** [comment]
@swift-ci please test OS X platform and merge

**Comment by dabrahams** [comment]
@swift-ci please test OS X platform

**Comment by moiseev** [comment]
@swift-ci Please test macOS platform

**Pull request merged**
