### PR TITLE
Python 3 removes the reduce builtin

### PR DESCRIPTION
**Pull request by RLovelett**
#### What's in this pull request?

Python 3 removes the `reduce` builtin. This fix is merely the result of the [suggestion in the Python 3 docs](https://docs.python.org/3.0/whatsnew/3.0.html#builtins).

Perhaps the solution is a refactoring to use a `for` loop as suggested in the docs. That's not really for me to say though as I understand next to nothing about Python or "preferred" methods. This was the smallest change I could make to get it back to working.

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by gribozavr** [comment]
@swift-ci Please Python lint

**Comment by gribozavr** [comment]
@RLovelett Thank you!  Would you mind looking at the linter issues?

```
./utils/update-checkout:13:1: I201 Missing newline before sections or imports.
./utils/update-checkout:15:1: I100 Import statements are in the wrong order. import argparse should be before from functools
```

You can run the linter locally with `utils/python-lint`.

**Comment by RLovelett** [comment]
Fixed them. Thank you @gribozavr for all the work you do on this project.

**Comment by gribozavr** [comment]
@swift-ci Please Python lint

**Comment by gribozavr** [comment]
@RLovelett No, thank **you**!

**Pull request merged**
