### PR TITLE
Re-land 7e33575c with history

### PR DESCRIPTION
**Pull request by kubamracek**
The empty final diff is on purpose - I accidentally merged https://github.com/apple/swift/pull/40173 by squashing and that's bad because the individual commit history is important.

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please smoke test

**Review by compnerd — APPROVED** [review]
Oh, this is a clever, clever idea.

**Comment by kubamracek** [comment]
Let's just hope the muscle memory doesn't kick in and I don't press 'squash' again 😄

**Comment by kubamracek** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
The Windows test failure has been fixed in main now.

**Comment by kubamracek** [comment]
@swift-ci please test Windows platform

**Pull request merged**
