### PR TITLE
Second attempt at simplifying performMemberLookup()

### PR DESCRIPTION
**Pull request by davezarzycki**
Simplify performMemberLookup() by having the normal code path handle both simple and compound named constructors. As a part of the fallout, a redundant diagnostic can also be removed.

This branch restores the favored constructor optimization.

### CODE REVIEW

**Comment by davezarzycki** [comment]
My local full validation test just crapped out. Closing until I have a fix.

**Comment by xedin** [comment]
@davezarzycki could you please squash all of the changes into a single commit please? This would make it friendlier to bisect later if needs to be...

**Comment by jrose-apple** [comment]
@xedin That's not a policy we have in general for this project, and it makes it harder to review the change. (In theory there also ought to be an option to git-bisect to only look at the first parent of merge commits, too, but that doesn't exist today as far as I can tell.)

**Comment by xedin** [comment]
@jrose-apple I understand that, that is why i didn't say that it was a policy or anything, but this particular change removes and re-adds the same code in different comments which makes sense to squash.

**Comment by davezarzycki** [comment]
I agree with both of you. I've squashed the two commits in question and left the third, non-regression one alone. I've run the validation tests and I'm about to resubmit a pull request.

**Pull request closed without merging**
