### PR TITLE
[Runtime] Demangle generic types with their instantiation arguments.

### PR DESCRIPTION
**Pull request by DougGregor**
Introduce logic to demangle a generic type involving generic parameters,
using its mangled generic signature to interpret the corresponding
instantiation arguments.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by CodaFi** [comment]
@DougGregor Do we still need this?

**Comment by DougGregor** [comment]
We can close this, unless @jckarter wants to do any of the mangled-name-to-realize-generic-metadata through this code path. I suspect he'll have a better way to do it.

**Comment by jckarter** [comment]
I might be able to steal some code from this, but yeah, we don't need to leave the PR open.

**Pull request closed without merging**
