### PR TITLE
[gardening][Calendar] No need to discard the retrun value of `insert(…

### PR DESCRIPTION
**Pull request by ikesyo**
…_:)` which is discardable

### CODE REVIEW

**Comment by ikesyo** [comment]
@swift-ci smoke test

**Comment by ikesyo** [comment]
@swift-ci Please smoke test

**Comment by ikesyo** [comment]
@swift-ci Please smoke test and merge

**Comment by ikesyo** [comment]
@swift-ci Please smoke test and merge

**Comment by parkera** [comment]
LGTM; next time feel free to add me as a reviewer so I don't miss these.

**Pull request merged**
