### PR TITLE
[build-script] Add preset to set up CI testing for the stress tester

### PR DESCRIPTION
**Pull request by ahoppen**
This configures a preset `buildbot_skstresstester_macos` that can be used for CI testing of the stress tester.

This does not yet set up testing the stress tester as a downstream dependency of the Swift and SwiftSyntax project.

### CODE REVIEW

**Comment by ahoppen** [comment]
preset=buildbot_skstresstester_macos
@swift-ci Please test with preset macOS Platform

**Comment by ahoppen** [comment]
There have been a couple changes to the SwiftSyntax and stress tester repositories. Let’s just verify again.

preset=buildbot_skstresstester_macos
@swift-ci Please test with preset macOS Platform

**Comment by ahoppen** [comment]
And get this PR green.

@swift-ci Please smoke test

**Comment by shahmishal** [comment]
Is there a reason for deleting `buildbot_swiftevolve_macos` preset?

**Comment by ahoppen** [comment]
I only added it a couple days ago and now realized that there is never a situation where we only want to test one of the two since they both live in the same repository.

**Comment by ahoppen** [comment]
Building the stress tester failed because the sources in SwiftSyntax `master-gen` were not up-to-date. Let’s try again.

preset=buildbot_skstresstester_macos
@swift-ci Please test with preset macOS Platform

**Comment by ahoppen** [comment]
preset=buildbot_skstresstester_macos
@swift-ci Please test with preset macOS Platform

**Pull request merged**
