### PR TITLE
[gardening]Fix recently introduced typo: "grey" → "gray"

### PR DESCRIPTION
**Pull request by naoyashiga**
#### What's in this pull request?

A fix for the recently introduced typo: "grey" → "gray"

#### Resolved bug number:

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by benlangmuir** [comment]
You may be interested to know that 'grey' is also a correct spelling.  It is usually spelled 'grey' in Canada and the UK.

**Comment by PatrickPijnappel** [comment]
@benlangmuir Swift is standardized on US spelling though ;).

**Comment by naoyashiga** [comment]
@PatrickPijnappel I think so too.

I checked this comment, so I knew this repository prefer american english.
https://github.com/apple/swift/pull/479#issuecomment-164639669

**Comment by lattner** [comment]
I don't know what is the "right" american english spelling, but whatever it is that's what we'd prefer.  Thanks!

**Comment by jckarter** [comment]
US spelling allows either "gray" or "grey".

**Comment by dduan** [comment]
🇺🇸🇺🇸🇺🇸Swift: Made in California™🇺🇸🇺🇸🇺🇸

**Comment by mxcl** [comment]
We should subscribe to the “50 Shades” spelling book.

**Pull request merged**
