### PR TITLE
[dead-function-elimination] Do not consider transparent functions as anchors

### PR DESCRIPTION
**Pull request by swiftix**
Transparent functions are emitted into the client in most cases, so there is no need to keep them alive in the defining module unless they are used there.

The only exception are transparent global initializers, because bodies of global initializer functions are never SIL serialized and are always IRGened into the defining module, so that clients can invoke them

This change results in small code size reductions of the binaries being produced after recent changes related to the early SIL serialization and the removal of -sil-serialize-all mode.

Fixes rdar://problem/35022861

### CODE REVIEW

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by swiftix** [comment]
@swift-ci please smoke benchmark

**Comment by swiftix** [comment]
@swift-ci Please test source compatibility

**Comment by swiftix** [comment]
@swift-ci please clean test Linux

**Comment by swiftix** [comment]
I had a hope to land it quickly, but there seems to be a Linux specific issue. I'll try to reproduce it on  Linux when the time permits.

**Comment by shajrawi** [comment]
@swift-ci please clean test

**Comment by shajrawi** [comment]
The Mac failure is unrelated - someone broke trunk:

SIL verification failed: struct operand type does not match field type: (*opi)->getType() == loweredType
Verifying instruction:
%0 = integer_literal $Builtin.Int64, 2 // user: %1
-> %1 = struct $Int (%0 : $Builtin.Int64) // user: %3
store %1 to %2 : $*Int // id: %3

**Comment by shajrawi** [comment]
@swift-ci Please smoke test OS X

**Comment by swiftix** [comment]
@shajrawi Hey Joe, are you trying to revive this PR? Sorry, I didn't have time to look into the Linux issue yet.

**Comment by shajrawi** [comment]
no worries - I just merged it / linux passes :)

**Pull request merged**
