### PR TITLE
CSE OSSA: Enable lookThroughOwnershipInsts for some more instructions

### PR DESCRIPTION
**Pull request by meg-gupta**

### CODE REVIEW

**Comment by meg-gupta** [comment]
Still trying to repro - rdar://74359921. But not looking through ownership instructions in these cases can cause the `llvm::DenseMapInfo<SimpleValue>::getHashValue` return different hashes but `llvm::DenseMapInfo<SimpleValue>::isEqual` return `true`. This inconsistency can cause an assert fire in ScopedHashTable::grow

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
I am going to merge this. Working on refactoring CSE to filter operands based on ownership constraints while computing hashes.

**Comment by slavapestov** [comment]
Thanks!

**Pull request merged**
