### PR TITLE
[CodeCompletion] Split CodeCompletion.cpp into multiple files

### PR DESCRIPTION
**Pull request by ahoppen**
CodeCompletion.cpp has gotten way too big for my taste. Split it up into multiple files. The basic ideas were to
- Create a new header + cpp file for roughly every class that was previously either defined in CodeCompletion.h or CodeCompletion.cpp
- CodeCompletion.cpp now essentially contains the implementation of `CodeCompletionCallbacksImpl` + a few random utilities. We can consider splitting those off in a follow-up PR, as necessary
- Every solver-based code completion receives its own header + cpp file, containing the `TypeCheckCompletionCallback` + the `deliver*Results` method. In a follow-up PR we can make the the `deliver*Results` methods members of the callback. I didn’t do it in this PR because this PR should purely move code around and not make any changes.

`include/IDE` and `lib/IDE` now contain a lot more files than previously. We can consider moving those into subfolders in a follow-up PR. For now, I’d like to merge this PR ASAP to avoid possible merge conflicts.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test Windows

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Review by rintaro — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please smoke test Windows

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Pull request merged**
