### PR TITLE
Allow @_silgen_name to be used on globals and add a @_silgen_name(raw: ...) version that skips mangling

### PR DESCRIPTION
**Pull request by kubamracek**
Attribute @_silgen_name is today only allowed to be used on functions, this PR allows usage on globals as well. The motivation for that is to be able to "forward declare" globals just like it's today possible to do with functions (for the cases where it's not practical or convenient to use a bridging header).

Separately, this PR also adds a `@_silgen_name(raw: ...)` syntax, which simply avoids mangling the name (by using the `\01` name prefix that LLVM uses). The motivation for that is to be able to reference the "magic Darwin linker symbols" that can be used to look up section bounds (in the current dylib/module) -- those symbols don't use the underscore prefix in their mangled names. The attached testcases showcase this as a low-level "linker set" implementation.

### CODE REVIEW

**Comment by jckarter** [comment]
It isn't safe to export the symbol of a global generally because anyone directly accessing it would bypass the one-time initializer, which is why this hasn't been allowed yet. If `@_silgen_name`-ing a global also required that the initializer get optimized into a static constant in the binary, that would be safer.

**Comment by kubamracek** [comment]
@jckarter Added a check that rejects `@_silgen_name` if the global isn't guaranteed to be statically initialized. (See added test.)

**Review by jckarter — APPROVED** [review]

**Comment by kubamracek** [comment]
Please test with following pull request:
https://github.com/apple/swift-syntax/pull/1850

@swift-ci Please test

**Comment by kubamracek** [comment]
Please test with following pull request:
https://github.com/apple/swift-syntax/pull/1850

@swift-ci Please test

**Pull request merged**
