### PR TITLE
[lldb] Switch PR testing and build to use CMake by default.

### PR DESCRIPTION
**Pull request by dcci**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by dcci** [comment]
@swift-ci smoke test

**Comment by slavapestov** [comment]
Yes, thank you!

**Review by shahmishal — APPROVED** [review]

**Comment by dcci** [comment]
```
15:19:28 /bin/sh: line 1: 65237 Killed: 9 
```

@shahmishal any idea what's causing this?

**Comment by dcci** [comment]
@swift-ci smoke test

**Comment by shahmishal** [comment]
@dcci Do you have link to the job?

**Comment by compnerd** [comment]
The Linux failure:

```
FAIL: Swift(linux-x86_64) :: Python/build_swift.swift (8145 of 11792)
******************** TEST 'Swift(linux-x86_64) :: Python/build_swift.swift' FAILED ********************
Script:
--
: 'RUN: at line 10';   /usr/bin/python -m unittest discover -s /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/swift/utils/build_swift/ -t /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/swift/utils/
--
Exit Code: 1

Command Output (stderr):
--
....................................................................................................................................................................................................................................................................................................................................................F..........................................................................................................................................................................FF........................................................................................................................................................................................
======================================================================
FAIL: test_default_value_lldb_build_with_xcode (build_swift.tests.test_driver_arguments.buildbot_incremental,tools=RA,stdlib=RA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/swift/utils/build_swift/tests/test_driver_arguments.py", line 126, in test
    .format(dest, default_value, parsed_value))
AssertionError: Invalid default value for "lldb_build_with_xcode": 1 != 0

======================================================================
FAIL: test_option_lldb_build_with_cmake (build_swift.tests.test_driver_arguments.buildbot_incremental,tools=RA,stdlib=RA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/swift/utils/build_swift/tests/test_driver_arguments.py", line 144, in test
    self.assertEqual(getattr(namespace, option.dest), option.value)
AssertionError: '1' != '0'

======================================================================
FAIL: test_option_lldb_build_with_xcode (build_swift.tests.test_driver_arguments.buildbot_incremental,tools=RA,stdlib=RA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/swift/utils/build_swift/tests/test_driver_arguments.py", line 144, in test
    self.assertEqual(getattr(namespace, option.dest), option.value)
AssertionError: '0' != '1'

----------------------------------------------------------------------
Ran 697 tests in 16.106s

FAILED (failures=3)

--

********************
```

**Comment by dcci** [comment]
OK, it just looks like the test has to be updated.

**Comment by dcci** [comment]
Let's give this another try.

**Comment by dcci** [comment]
@swift-ci smoke test

**Comment by shahmishal** [comment]
@swift-ci smoke test macOS

**Comment by dcci** [comment]
@swift-ci test

**Comment by dcci** [comment]
@swift-ci test

**Comment by dcci** [comment]
@swift-ci test

**Comment by dcci** [comment]
@swift-ci test

**Comment by dcci** [comment]
@swift-ci test

**Comment by dcci** [comment]
@swift-ci test

**Comment by dcci** [comment]
@swift-ci smoke test

**Comment by dcci** [comment]
@swift-ci smoke test

**Comment by dcci** [comment]
@fredriss the tests I see failing:

```
12:58:12 Failing Tests (7):
12:58:12     LLDB :: SwiftREPL/Basic.test
12:58:12     LLDB :: SwiftREPL/CFString.test
12:58:12     LLDB :: SwiftREPL/ComputedProperties.test
12:58:12     LLDB :: SwiftREPL/CrashArgs.test
12:58:12     LLDB :: SwiftREPL/UninitVariables.test
12:58:12     lldb-Unit :: Editline/./EditlineTests/EditlineTestFixture.EditlineReceivesMultiLineText
12:58:12     lldb-Unit :: Editline/./EditlineTests/EditlineTestFixture.EditlineReceivesSingleLineText
```

I'll reproduce them on the laptop.

**Comment by dcci** [comment]
@swift-ci please smoke test macOS

**Comment by dcci** [comment]
test with https://github.com/apple/swift-lldb/pull/1494
@swift-ci please smoke test

**Comment by dcci** [comment]
test with https://github.com/apple/swift-lldb/pull/1499
@swift-ci please smoke test

**Comment by dcci** [comment]
test with apple/swift-lldb#1499
@swift-ci please smoke test macos

**Comment by dcci** [comment]
test with apple/swift-lldb#1499
@swift-ci please smoke test macos

**Comment by dcci** [comment]
test with apple/swift-lldb#1499
@swift-ci please smoke test macos

**Comment by shahmishal** [comment]
test with apple/swift-lldb#1499
@swift-ci please test

**Comment by dcci** [comment]
All the lldb tests are passing, it's only foundation that's failing. I'll  pull the trigger.

**Pull request merged**
