### PR TITLE
🌸[6.0][Concurrency] Remove _unsafeInheritExecutor from public APIs, use #isolation

### PR DESCRIPTION
**Pull request by ktoso**
**Description:** In order to avoid isolation boundary warnings when task groups are used inside (global) actors we need to inherit isolation contest to most of their async APIs. Specifically, this PR resolves next() and waitForAll() now inheriting caller isolation.

Without this fix, the added test case would have failed with: 
> Passing argument of non-sendable type 'inout ThrowingTaskGroup<Void, any Error>' outside of main actor-isolated context may introduce data races

**Risk:** Low, because all existing ABI entrypoints are retained.
**Review by:** @hborla 
**Testing:** CI testing
**Original PR:** https://github.com/apple/swift/pull/72794 https://github.com/apple/swift/pull/72578 https://github.com/apple/swift/pull/72862
**Radar:** rdar://122846553Otherwise we get warnings when task groups are used within an actor.
Add global actor tests to cover the specific situation.

resolves rdar://122846553

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please test

**Review by hborla — APPROVED** [review]

**Comment by hborla** [comment]
@swift-ci please test

**Pull request merged**
