### PR TITLE
Clarify ownership of dependency tracker.

### PR DESCRIPTION
**Pull request by davidungar**
The dependency tracker is allocated as a local in `performFrontend` and at first glance, it appears that it could be moved into the following block. But it can't. It needs to last as long as the CompilerInstance. So, move its ownership into the CompilerInstance.

### CODE REVIEW

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Review by jrose-apple — APPROVED** [review]
I suspect it was the way it was before because I was trying to save a heap allocation, but for an object that's created at most once per compilation, that's almost certainly over-micro-optimization. This is less clever and therefore better.

**Comment by davidungar** [comment]
Thanks!

**Pull request merged**
