### PR TITLE
[WIP] SIL type lowering cleanups

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by gottesmm** [comment]
Slava, I am going to be landing some TypeLowering stuff today, can you please wait until that lands?

**Comment by gottesmm** [comment]
This is the PR that I am worried about: #5494

**Comment by gottesmm** [comment]
Its done! Thanks I appreciate it = ).

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by tkremenek** [comment]
@slavapestov Is this ready to be merged?

**Comment by tkremenek** [comment]
Looks like this patch no longer builds.

**Comment by slavapestov** [comment]
@tkremenek No, this is still a work in progress.

**Pull request closed without merging**
