### PR TITLE
Revert public fragile hack

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@eeckstein This is the revert that should fix the stdlib size regression in 3.0

**Comment by eeckstein** [comment]
Thanks!

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@jrose-apple Do you mind looking this over whenever you have a spare minute? (It's not for 3.0)

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
Hm. I really don't like the existence of the stub constructors. Can't we just take non-required constructors out of the vtable?

**Comment by slavapestov** [comment]
Well, we have to emit *something* in place of the vtable entry.

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
I don't understand why there's a vtable entry at all. If it's not a required initializer, you can't dynamically dispatch to it.

**Pull request merged**
