### PR TITLE
[WIP] Move out enum tests into a separate CXXInterop/enum directory

### PR DESCRIPTION
**Pull request by sureyeaah**
https://github.com/apple/swift/pull/30182/ was reverted because of failure on windows. This PR fixes it.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by sureyeaah** [comment]
@swift-ci Please test Windows platform

**Comment by gribozavr** [comment]
@swift-ci Please test Windows platform

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
