### PR TITLE
Revert "Don't import C++ class members that are protected or private" and "SILCombine: optimize creating enums with tuple payloads"

### PR DESCRIPTION
**Pull request by martinboehme**
Reverts apple/swift#30233 and https://github.com/apple/swift/commit/95cacf84b75fb669dfe1cca6ca9de1d364ee1463.

The previous revert (https://github.com/apple/swift/pull/30518) seems to have run into issues, so trying another revert based on a more recent commit.

### CODE REVIEW

**Comment by gribozavr** [comment]
@swift-ci Please smoke test

**Comment by martinboehme** [comment]
Build bot failures seem to be because of https://github.com/apple/swift/commit/95cacf84b75fb669dfe1cca6ca9de1d364ee1463.

See comment here:

https://github.com/apple/swift/commit/95cacf84b75fb669dfe1cca6ca9de1d364ee1463#r37941142

**Comment by gribozavr** [comment]
@swift-ci Please smoke test

**Comment by martinboehme** [comment]
Will create a new clean revert of #30233.

**Pull request closed without merging**
