### PR TITLE
[IRGen] Add some PrettyStackTraces for metadata emission

### PR DESCRIPTION
**Pull request by jrose-apple**
Hopefully helpful in debugging things like [SR-8540](https://bugs.swift.org/browse/SR-8540).

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Review by aschwaighofer — APPROVED** [review]
Looks good to me

**Review by rjmccall — APPROVED** [review]

**Comment by jrose-apple** [comment]
Um.

@swift-ci Please clean smoke test Linux

**Pull request merged**
