### PR TITLE
[stdlib] Move DoubleWidth into its own file

### PR DESCRIPTION
**Pull request by natecook1000**
`Integers.swift.gyb` is long enough as it is.

### CODE REVIEW

**Comment by natecook1000** [comment]
@swift-ci Please smoke test

**Comment by moiseev** [comment]
The error is:

```
stdout>>> check failed at /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/swift/test/stdlib/Integers.swift.gyb, line 634
stdout>>> expected: true
stdout>>> check failed at /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/swift/test/stdlib/Integers.swift.gyb, line 637
stdout>>> expected: true
stdout>>> check failed at /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/swift/test/stdlib/Integers.swift.gyb, line 640
stdout>>> expected: true
[     FAIL ] DoubleWidth.Literals
[ RUN      ] DoubleWidth.Arithmetic/unsigned
stdout>>> check failed at /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/swift/test/stdlib/Integers.swift.gyb, line 652
stdout>>> expected: (0, 88) (of type Swift.DoubleWidth<Swift.UInt8>)
stdout>>>   = [+]58
stdout>>> actual: (27, 88) (of type Swift.DoubleWidth<Swift.UInt8>)
stdout>>>   = [+]1B58
stdout>>> 
stdout>>> check failed at /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/swift/test/stdlib/Integers.swift.gyb, line 653
stdout>>> expected: (0, 97) (of type Swift.DoubleWidth<Swift.UInt8>)
stdout>>>   = [+]61
stdout>>> actual: (30, 97) (of type Swift.DoubleWidth<Swift.UInt8>)
stdout>>>   = [+]1E61
stdout>>> 
[     FAIL ] DoubleWidth.Arithmetic/unsigned
[ RUN      ] DoubleWidth.Arithmetic/signed
stdout>>> check failed at /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/swift/test/stdlib/Integers.swift.gyb, line 675
stdout>>> expected: (0, 88) (of type Swift.DoubleWidth<Swift.Int8>)
stdout>>>   = [+]58
stdout>>> actual: (27, 88) (of type Swift.DoubleWidth<Swift.Int8>)
stdout>>>   = [+]1B58
stdout>>> 
stdout>>> check failed at /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/swift/test/stdlib/Integers.swift.gyb, line 676
stdout>>> expected: (0, 159) (of type Swift.DoubleWidth<Swift.Int8>)
stdout>>>   = [+]9F
stdout>>> actual: (-31, 159) (of type Swift.DoubleWidth<Swift.Int8>)
stdout>>>   = [-]E19F
stdout>>> 
stdout>>> check failed at /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/swift/test/stdlib/Integers.swift.gyb, line 677
stdout>>> expected: (0, 168) (of type Swift.DoubleWidth<Swift.Int8>)
stdout>>>   = [+]A8
stdout>>> actual: (-28, 168) (of type Swift.DoubleWidth<Swift.Int8>)
stdout>>>   = [-]E4A8
stdout>>> 
stdout>>> check failed at /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/swift/test/stdlib/Integers.swift.gyb, line 678
stdout>>> expected: (0, 97) (of type Swift.DoubleWidth<Swift.Int8>)
stdout>>>   = [+]61
stdout>>> actual: (30, 97) (of type Swift.DoubleWidth<Swift.Int8>)
stdout>>>   = [+]1E61
stdout>>> 
[     FAIL ] DoubleWidth.Arithmetic/signed
```

**Comment by natecook1000** [comment]
@swift-ci Please smoke test

**Comment by natecook1000** [comment]
@moiseev Gyb/brain fail

**Comment by natecook1000** [comment]
Also, we should figure out how to make sure the integers tests run on a big-endian platform.

**Comment by dabrahams** [comment]
on Tue Jun 06 2017, Nate Cook <notifications-AT-github.com> wrote:

> Also, we should figure out how to make sure the integers tests run on a big-endian platform.

That would be nice, but if they're not using explicit byte-swapping, or
bitcasting tricks like memcpy I don't think there's much risk here,
FWIW.

-- 
-Dave

**Pull request merged**
