### PR TITLE
[Backtracing][Linux] Enable Linux backtracing, add tests.

### PR DESCRIPTION
**Pull request by al45tair**
Turn on the Linux backtracing implementation and update the tests.

rdar://101623265

### CODE REVIEW

**Comment by al45tair** [comment]
This is based on #66410 and includes all of its commits. The first actual commit for this PR is 600ab1d.

**Comment by al45tair** [comment]
Explanation: Adds the tests for the backtracer, and enables it for Linux.
Risk: Low. Only affects Linux.
Original PR: #66338
Reviewed by: @MaxDesiatov 
Resolves: rdar://101623265
Tests: The tests in `test/Backtracing` exercise this code. Most of them also test macOS, and the output must match on both platforms for CI to pass.

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
https://github.com/apple/swift-corelibs-xctest/pull/447

@swift-ci Please test

**Review by MaxDesiatov — APPROVED** [review]

**Review by tbkka — APPROVED** [review]

**Pull request merged**
