### PR TITLE
[cxx-interop] Add conversions between `std::chrono::duration` and `Swift.Duration`

### PR DESCRIPTION
**Pull request by egorzhdan**
rdar://123696734

### CODE REVIEW

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please test Windows

**Review by phausler — APPROVED** [review]
looks correct to me.

**Comment by egorzhdan** [comment]
Thanks @phausler for a quick review! :)

**Pull request merged**
