### PR TITLE
[cxx-interop] test, enable more tests on windows

### PR DESCRIPTION
**Pull request by hyp**
These tests require the C++ standard library

### CODE REVIEW

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
vector test is still borked somehow, will need to investigate. anyways, this should work.

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please smoke test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Review by egorzhdan — APPROVED** [review]
👍

**Pull request merged**
