### PR TITLE
Manually merge master into master-next

### PR DESCRIPTION
**Pull request by varungandhi-apple**

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test

**Comment by varungandhi-apple** [comment]
```
    Fixed merge conflicts in:
    - lib/ClangImporter/ClangImporter.cpp
    - lib/ClangImporter/ImportType.cpp
    - lib/Frontend/CompilerInvocation.cpp
    - lib/Serialization/ModuleFile.cpp
```

**Comment by varungandhi-apple** [comment]
Looking at the test failures... 👀

**Comment by varungandhi-apple** [comment]
There are at least a couple of issues here:

1. Baseline CI failures.
2. Use of the implicit StringRef -> std::string conversion which has been made explicit on LLVM's apple/master and swift/master-next.

Working on the second one right now, so we can simultaneously patch LLVM's swift/master and Swift's master.

**Comment by varungandhi-apple** [comment]
https://github.com/apple/llvm-project/pull/1461 contains the StringRef -> std::string changes; that needs to be merged before this change.

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test

**Comment by varungandhi-apple** [comment]
LLVM's swift/master-next is borked for GCC 5.4.0. Waiting on an LLVM-side fix...

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test macOS platform

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test Windows platform

**Comment by varungandhi-apple** [comment]
The macOS cxx-headers issue is being worked on in https://github.com/apple/swift/pull/32909 .

**Comment by nathawes** [comment]
The cxx-headers issue should be resolved now.

@swift-ci please smoke test macOS platform

**Comment by nathawes** [comment]
@swift-ci please smoke test OS X platform

**Comment by nathawes** [comment]
macOS test failures:
```
16:27:31 Failed Tests (6):
16:27:31   Swift(macosx-x86_64) :: Sema/SwiftUI/rdar58972627.swift
16:27:31   Swift(macosx-x86_64) :: Sema/SwiftUI/rdar57410798.swift
16:27:31   Swift(macosx-x86_64) :: Sema/SwiftUI/rdar57201781.swift
16:27:31   Swift(macosx-x86_64) :: Sema/SwiftUI/rdar56710317.swift
16:27:31   Swift(macosx-x86_64) :: ClangImporter/availability_macosx_canonical_versions_appext.swift
16:27:31   Swift(macosx-x86_64) :: ClangImporter/availability_macosx_canonical_versions.swift
```

**Review by nathawes — APPROVED** [review]

**Pull request merged**
