### PR TITLE
typo - remove some "and"

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Comment by zachpanz88** [comment]
The way that you changed the text actually changed the original meaning of the text. There are some redundant "and"s but you removed some that should not have been removed.

**Comment by OskarStark** [comment]
which meaning did i change? ``clean and modern`` ?

**Comment by zachpanz88** [comment]
Well the program offers "offers seamless access to existing C and Objective-C code and frameworks" meaning that it offers access to both C code and frameworks and Objective-C code and frameworks. The way you phrased it, "offers seamless access to existing C, Objective-C code, and frameworks," implies that it offers just access to C, includes Objective-C code, and has frameworks on the side. The way that you phrased it completely changes the original meaning of the text.

**Comment by davidcbilas** [comment]
The revision could still be improved grammatically and for readability.  I would suggest:

Swift is a high-performance system programming language.  It has a clean, modern syntax; offers seamless access to existing C, Objective-C code, and frameworks; and is memory safe (by default).

**Comment by zachpanz88** [comment]
@davidcbilas I agree with that improvement. It is grammatically correct and clarifies the meaning.

**Comment by zygoat** [comment]
The only change necessary in the original text is the removal of the second “and” (before “offers seamless access”), which appears to be what @zachpanz88 proposed in the first comment.

The semicolons offered by @davidcbilas disrupt the readability and offer little value above that provided by commas.

**Comment by davidcbilas** [comment]
I would agree with that.  My addition of semi-colons were based on the original revision, which had commas within comma-separate clauses.

**Comment by lattner** [comment]
This conflicts with subsequent changes.

**Pull request closed without merging**
