### PR TITLE
[swift-3.0-branch] Introduce siphash for strings on non-ObjC platforms

### PR DESCRIPTION
**Pull request by moiseev**
- Explanation: Use siphash for string hashing on non-ObjC platforms
- Scope of Issue: Introduces a more secure hashing algorithm
- Origination:
- Risk: Minimal
- Reviewed By: Dmitri Gribenko
- Testing: Ran the existing test suite.
- Directions for QA: N/A

Requires: https://github.com/apple/swift-corelibs-foundation/pull/634

rdar://problem/28289426

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please  test

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by tkremenek** [comment]
@swift-ci clean test linux

**Comment by tkremenek** [comment]
@moiseev this doesn't build on Linux.

**Comment by tkremenek** [comment]
```
swift-PR-Linux/branch-swift-3.0-branch/swiftpm/Sources/Basic/ByteString.swift:50:30: error: value of type 'String' has no member '_contiguousUTF8'
13:20:30         let stringPtrStart = string._contiguousUTF8
13:20:30                              ^~~~~~ ~~~~~~~~~~~~~~~
13:20:30 /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-swift-3.0-branch/swiftpm/Sources/Basic/OutputByteStream.swift:176:30: error: value of type 'String' has no member '_contiguousUTF8'
13:20:30         let stringPtrStart = string._contiguousUTF8
13:20:30                              ^~~~~~ ~~~~~~~~~~~~~~~
```

**Comment by shahmishal** [comment]
Please test with: 
apple/swift-corelibs-foundation#634

@swift-ci Please test

**Comment by moiseev** [comment]
Please test with:
https://github.com/apple/swift-package-manager/pull/656

@swift-ci Please test

**Comment by shahmishal** [comment]
Please test with: 
apple/swift-corelibs-foundation#634
apple/swift-package-manager#656

@swift-ci Please test Linux

**Comment by tkremenek** [comment]
Swift 3.0.1 is meant to be a bug-fix release or take critical changes.  This is a fairly significant semantic change to the behavior of hashing, that doesn't seem to fit either category.  Let's take this for Swift 3.1.

**Comment by gribozavr** [comment]
@moiseev If you will be pulling these fixes into 3.1, please also take this commit: https://github.com/apple/swift/pull/4850

**Comment by lattner** [comment]
3.1 should rebranch from master.

**Pull request closed without merging**
