### PR TITLE
Fix indentation of sample code in rst files.

### PR DESCRIPTION
**Pull request by DevYeom**
Incorrect spaces found while reading the docs were corrected.

### CODE REVIEW

**Comment by DevYeom** [comment]
@swift-ci please smoke test

**Review by Ajisaputrars — APPROVED** [review]

**Comment by DevYeom** [comment]
@swift-ci Please smoke test

**Comment by DevYeom** [comment]
@eeckstein Could you please review this?

**Review by eeckstein — APPROVED** [review]
lgtm

**Comment by DevYeom** [comment]
@eeckstein Please run smoke test and merge.

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Pull request merged**
