### PR TITLE
[swiftSyntax] SwiftSyntax on Linux

### PR DESCRIPTION
**Pull request by ahoppen**
Let's see if there are any major issues why this doesn't compile or if it magically works.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please smoke test Linux platform

**Comment by DougGregor** [comment]
Magic!

**Comment by harlanhaskins** [comment]
Unfortunately it won’t. It needs extra CMake hoop to get it to link the just-built Foundation with the SwiftSyntax module.

**Comment by ahoppen** [comment]
@harlanhaskins Why doesn't compilation fail right now, then? Or does it only fail if I actually start using it?

**Comment by harlanhaskins** [comment]
It compiled successfully because it wasn’t building SwiftSyntax.

https://github.com/apple/swift/blob/fcf9cfb3d0fb2665872e7e8bd377dce06be56f3b/tools/CMakeLists.txt#L48

I tried for a long time to get it building on Linux a few months back in #14854 but I couldn’t figure out the right CMake goop.

**Pull request closed without merging**
