### PR TITLE
[Sema] Minimum access for protocol requirement members to 'fileprivate'.

### PR DESCRIPTION
**Pull request by rintaro**
#### What's in this pull request?

CC: @jrose-apple 
I'm not sure this is the right fix.

``` swift
// ModA/File1.swift
private protocol P  {
  func privMethod() // This was implicitly `internal`.
}
public class C : P {
  public init() {}
  fileprivate func privMethod() {
    print("FOOBAR")
  }
}
```

`C.privMethod()` _was_ visible from other file. (Because `P.privMethod()` was `internal`)

``` swift
// ModA/File2.swift
extension C {
  public func callPrivMethod() {
    // This should be "error: use of unresolved identifier 'privMethod'",
    // but was not.
    privMethod()
  }
}
```

This compiles.
But, ends up with runtime error  `'fatal error: call of deleted method'`

```
// main.swift
C().callPrivMethod()
```

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

A smoke test on macOS does the following:
1. Builds the compiler incrementally.
2. Builds the standard library only for macOS. Simulator standard libraries and
   device standard libraries are not built.
3. lldb is not built.
4. The test and validation-test targets are run only for macOS. The optimized
   version of these tests are not run.

A smoke test on Linux does the following:
1. Builds the compiler incrementally.
2. Builds the standard library incrementally.
3. lldb is built incrementally.
4. The swift test and validation-test targets are run. The optimized version of these
   tests are not run.
5. lldb is tested.

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by rintaro** [comment]
macOS: https://ci.swift.org/job/swift-PR-osx/3331/
Linux: https://ci.swift.org/job/swift-PR-linux/3522/

**Comment by jrose-apple** [comment]
[SE-0025](https://github.com/apple/swift-evolution/blob/master/proposals/0025-scoped-access-level.md) says we shouldn't care if the member has a higher access, but this might be a good enough patch fix anyway.

(We have a similar problem on a larger scale in [SR-2315](https://bugs.swift.org/browse/SR-2315), and I expect the fix for that will take care of this as well. But I think this is a reasonable thing to do anyway.)

**Comment by jrose-apple** [comment]
Both tests passed, force-merging.

**Pull request merged**
