### PR TITLE
Disable some failing tests while I look into a solution.

### PR DESCRIPTION
**Pull request by gottesmm**
Disable some failing tests while I look into a solution.

rdar://33358110

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
I think the problem is that _isDebugAssertConfiguration is based off of how the test itself is compiled instead of how the stdlib is compiled.

**Comment by eeckstein** [comment]
Can you just comment out the failing tests?
Assuming you will have a fix soon, I think it's acceptable to not run those tests for a few days and get back the bot.

**Comment by gottesmm** [comment]
I already have a fix.

**Comment by gottesmm** [comment]
or rather, I have a fix for the UPASS.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by jrose-apple** [comment]
If this is really dependent on the stdlib, you want `REQUIRES: optimized_stdlib`.

**Comment by jrose-apple** [comment]
I don't know if there's an equivalent of that for StdlibUnittest, though.

**Comment by gottesmm** [comment]
@jrose-apple Sure, I could do that. It does make it a bit less nice. When I rip out these, I will rip out that feature as well. I want to unblock this bot and I don't want to restart the testing.

**Comment by jrose-apple** [comment]
That feature already exists.

**Comment by gottesmm** [comment]
Jordan and I spoke offline. I explained to him I was talking about ripping out unoptimized_stdlib after the bot gets green.

**Comment by gottesmm** [comment]
He is correct that REQUIRES: optimized_stdlib would be sufficient. I just want to get this bot green and I don't want to restart the testing.

**Pull request merged**
