### PR TITLE
Few fixes in README.md file and fixed Langref.html 

### PR DESCRIPTION
**Pull request by vicky002**
Added a semicolon, as it was little misleading the sentence while reading.

### CODE REVIEW

**Comment by benlangmuir** [comment]
@jrose-apple are we interested in minor updates to the archived documents like this?

**Comment by jrose-apple** [comment]
Mm. I don't think we're interested in typo updates to older documents, but the last commit fixes rendering issues. I think we'd take that one.

(I commented on the first commit.)

**Comment by vicky002** [comment]
ok sir thanks and No typo updates anymore. :+1: .

**Comment by jrose-apple** [comment]
Ah, just to be clear, typo updates are (still) fine for the current docs and source. It's docs/archive/ that isn't really worth it.

**Comment by vicky002** [comment]
ohh ok. Now I'll check in current docs only.

**Comment by vicky002** [comment]
@jrose-apple sir please check once, I have fixed few typos. :+1:

**Comment by jrose-apple** [comment]
All of the word changes seem good. All of the comma changes are incorrect; please remove them.

Thanks!

**Comment by jrose-apple** [comment]
One bad comma left (the original one in README.md). After removing that, can you squash these all into a single commit? If you don't want to force-push to your master branch you can open a new pull request.

**Pull request closed without merging**
