### PR TITLE
[embedded] Resolve ptrauth crashes by signing HeapObjects's isa pointers in embedded Swift

### PR DESCRIPTION
**Pull request by kubamracek**
Virtual function calls verify isa signatures even in non-objc-interop mode on Embedded Swift, so we need to sign isa pointers in swift_allocObject and friends.

rdar://121398826

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by eeckstein — APPROVED** [review]
lgtm

**Review by mikeash — APPROVED** [review]
Is it possible to use `SpecialPointerAuthDiscriminators::ObjCISA` and `SpecialPointerAuthDiscriminators::HeapDestructor` rather than the magic numbers? Might not be possible to get at those definitions from here.

**Comment by kubamracek** [comment]
> Is it possible to use `SpecialPointerAuthDiscriminators::ObjCISA` and `SpecialPointerAuthDiscriminators::HeapDestructor` rather than the magic numbers? Might not be possible to get at those definitions from here.

Not without some larger refactoring: MetadataValues.h is a C++ header (and SpecialPointerAuthDiscriminators is a namespace), but this EmbeddedShims.h header is a C header (and needs to stay as C to be importable to Swift). I'll try to think about what can be done about this later.

**Comment by mikeash** [comment]
Makes sense. Not a big deal, it’s not like these numbers will ever change.

**Pull request merged**
