### PR TITLE
Remove Linux XFAIL in stdlib StringTraps tests

### PR DESCRIPTION
**Pull request by ezephir**
Partially resolves SR-216.
## 

Tested on Ubuntu 14.04 and OS X 10.10

### CODE REVIEW

**Comment by gribozavr** [comment]
@ezephir Do we need to import Foundation at all on OS X?

**Comment by ezephir** [comment]
Removing the import doesn't cause the tests to fail. I left it because I was concerned that importing Foundation might somehow subtly change what's being tested and I hadn't looked into it further.

Is it okay to remove it or is this something I need to look into further?

**Comment by ezephir** [comment]
@gribozavr I've looked into how things work some more and I feel better about removing the Foundation import on OS X. I've updated the PR with that change and also a rebase against master.

**Comment by gparker42** [comment]
Thanks for testing this!

**Pull request merged**
