### PR TITLE
build: improve SourceKit handling of libdispatch

### PR DESCRIPTION
**Pull request by compnerd**
Avoid overwriting the `swiftCore` target in the SourceKit build.
Instead, link to the explicit variant of the swiftCore.  This tracks the
dependency better and enables multiple parallel cross-compilations of
the stdlib.

Implicitly link against swiftCore when linking against libdispatch.
Remove the extraneous link against the Blocks runtime on Linux.  The
`add_sourcekit_executable` call already handles this.  Ensure that we
enable the swift SDK overlay for libdispatch by sending it the path to
the swift compiler.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC @gottesmm @dgrove-oss

**Comment by compnerd** [comment]
Please test with following pull request:
apple/swift-corelibs-libdispatch#307

@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by Rostepher** [comment]
I'll take a look at this when I can. If this change is urgent then let me know and I can try to prioritize reviewing.

**Comment by compnerd** [comment]
@Rostepher it's moderately urgent.  I think that we want to make sure that the unified build is working properly for everyone.  However, until the Darwin builds are switched over, I don't think that we can remove the autotools build.

CC: @das @gottesmm

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Please test with following pull request:
apple/swift-corelibs-libdispatch#307

@swift-ci please test Linux platform

**Comment by compnerd** [comment]
Please test with following pull request:
apple/swift-corelibs-libdispatch#307

@swift-ci please clean test Linux platform

**Comment by compnerd** [comment]
Please test with following pull request:
apple/swift-corelibs-libdispatch#307

@swift-ci please clean test Linux platform

**Comment by compnerd** [comment]
@swift-ci please clean test Linux platform

**Comment by compnerd** [comment]
Please test with following pull request:
apple/swift-corelibs-libdispatch#307

@swift-ci please clean test Linux platform

**Comment by compnerd** [comment]
Please test with following pull request:
apple/swift-corelibs-libdispatch#307

@swift-ci please clean test Linux platform

**Comment by compnerd** [comment]
Please test with following pull request:
apple/swift-corelibs-libdispatch#307

@swift-ci please clean test Linux platform

**Comment by compnerd** [comment]
@swift-ci please clean test macOS platform

**Comment by compnerd** [comment]
@swift-ci please clean test macos platform

**Comment by gottesmm** [comment]
I merged the libdispatch change. Trying a normal linux test.

**Comment by gottesmm** [comment]
@swift-ci test linux

**Comment by gottesmm** [comment]
@swift-ci clean test linux

**Comment by gottesmm** [comment]
(should have done a clean test)

**Comment by compnerd** [comment]
The clean build also succeeded.  Lets get this in then!

**Pull request merged**
