### PR TITLE
[Mangling] Add a new mangling for opaque return type to use when mangling an ObjC runtime name

### PR DESCRIPTION
**Pull request by theblixguy**
The old remangler does not handle opaque result types and can crash when mangling an ObjC runtime name for a class that is in a local context that returns an opaque type, for example:

```swift
func opaqueTypeFunc() -> some MyProtocol {
  class Foo: MyProtocol { ... }
  return Foo()
}

var opaqueTypeVar: some MyProtocol {
  class Bar: MyProtocol { ... }
  return Bar()
}
```

Introduce a new `Qu` mangling to represent the opaque return type in old mangling.

Resolves SR-13203

### CODE REVIEW

**Comment by jckarter** [comment]
I think we need to implement a real mangling here. The ObjC runtime name can become load-bearing ABI, if the class name ends up being used in a keyed archiver, nib, or other serialized format, and it needs to be unique relative to any other class names that might be instantiated in the process.

**Comment by theblixguy** [comment]
Okay! Something I didn't fully understand is that we mangle the return type as `Qr` (for above example), so does that also have the same problem as you mentioned above? Because here, I am swapping `Qr` with `Xe` but I don't know how that affects uniqueness and etc.

Anyhow, do you suggest we use a new mangling similar to `Qr` (+ maybe a discriminator?) for this situation and update the old demangler, remangler and etc along with it?

**Comment by theblixguy** [comment]
@jckarter, I have used a new `Qu` mangling to represent the return type in the old remangler. Does that seem in line with what you had in mind?

Given we don't allow overloading with opaque return types, I think the new mangled name should be completely unique. Is my assumption correct?

**Comment by jckarter** [comment]
I think that should work.

**Comment by theblixguy** [comment]
@jckarter Great! Thank you! I'll add this to `Mangling.rst` as well.

**Comment by theblixguy** [comment]
@jckarter I have added it to `Mangling.rst`. Does everything look good to you?

**Comment by jckarter** [comment]
Looks good to me. Thanks!

**Comment by theblixguy** [comment]
@swift-ci please test

**Comment by theblixguy** [comment]
@swift-ci please test

**Comment by theblixguy** [comment]
@swift-ci please test Linux

**Comment by slavapestov** [comment]
This needs an executable test in test/Interpreter/ which prints the runtime name. Otherwise we don't know if the mangling works as specified or not.

**Comment by theblixguy** [comment]
@slavapestov Sure, I have added some new tests here: https://github.com/apple/swift/pull/33340

**Pull request merged**
