### PR TITLE
Implement an optimization that does CSE of the apply-witnessmethod-open_existential trio

### PR DESCRIPTION
**Pull request by nadavrot**

### CODE REVIEW

**Comment by nadavrot** [comment]
@swift-ci Please test

**Comment by nadavrot** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@nadavrot Your pull request includes a bunch of irrelevant commits. Can you update the branch you are diff'ing against to ensure that your final merge only includes your patch and nothing else?

**Comment by nadavrot** [comment]
@swift-ci Please test

**Comment by nadavrot** [comment]
@slavapestov sure thing!

**Pull request closed without merging**
