### PR TITLE
Check protocols for selector conflicts

### PR DESCRIPTION
**Pull request by beccadax**
Although we have always checked classes to see if their `@objc` members had the same selectors, it turns out we never did this for protocols. Oops. Keep a table of ObjC selector names for protocols, just as we do for classes, and diagnose any conflicts between them.

Fixes rdar://80990066.

### CODE REVIEW

**Comment by beccadax** [comment]
@swift-ci please smoke test

**Comment by beccadax** [comment]
@swift-ci please test source compatibility

**Comment by beccadax** [comment]
@swift-ci please smoke test

**Comment by beccadax** [comment]
Linux failure looks like an infrastructure issue.

@swift-ci please smoke test Linux platform

**Comment by beccadax** [comment]
@swift-ci please test source compatibility

**Review by hamishknight — APPROVED** [review]

**Comment by beccadax** [comment]
The source compatibility suite failures appear to match e.g. https://ci.swift.org/job/swift-main-source-compat-suite/12/, which was run at the same time, so I think they are unrelated.

There appear to have been no instances of this new warning in the source compatibility suite.

**Pull request merged**
