### PR TITLE
[5.9] Enable CxxStdlib on Windows

### PR DESCRIPTION
**Pull request by compnerd**
Cherry pick a number of modularisation and build fixes to 5.9 from main.  These improve the C++ interop usability on Windows.  The combination of that with the build changes allow us to build CxxStdlib on Windows.  The changes to the frontend are required to repair the autolinking behaviour on Windows so that we can continue to mirror the other platforms and use static linking.

**Explanation:** Backport a number of module map improvements and fix the build and autolinking for `CxxStdlib` on Windows.
**Scope:** This enables the `CxxStdlib` module which is required for the C++ interop to interact with certain C++ STL types (e.g. `std::string`) in Swift.
**Issue:** #67649
**Risk:** This is a relatively low risk change as the majority of it is Windows specific.  The non-windows specific changes include passing an additional flag to the Swift module compilation which the CI will catch any issues with.
**Testing:** The module was used in a test library on Windows with main and verified that we could use the module and statically link against it with autolinking.
**Reviewer:** @hyp

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @egorzhdan @DougGregor

**Comment by compnerd** [comment]
@swift-ci please test

**Review by egorzhdan — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Review by ravikandhadai — APPROVED** [review]

**Comment by hyp** [comment]
This should also go to release/5.9.0 @compnerd

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Pull request merged**
