### PR TITLE
 [AST] Preserve sugar for generic typealiases. 

### PR DESCRIPTION
**Pull request by dcci**
<rdar://problem/43110802>

### CODE REVIEW

**Comment by dcci** [comment]
@slavapestov addressed your comment about the parent type. Can you please take a look? (I need to update the several differences in SourceKit tests after this change, so I want to a make sure it's correct before going through  )

**Comment by slavapestov** [comment]
In the future, instead of creating new pull requests for every revision, please update an existing PR. It's easier to see the full review history that way.

**Review by slavapestov — APPROVED** [review]

**Comment by slavapestov** [comment]
You can push the current HEAD (irrespective of the local branch name) to an arbitrary branch on a remote repo named `foo` by doing:

`git push -f foo HEAD:refs/heads/other-branch-name`

**Comment by dcci** [comment]
@swift-ci test and merge

**Pull request merged**
