### PR TITLE
[Basic] Desensitize OutputFileMap to DenseMap implementation changes

### PR DESCRIPTION
**Pull request by davezarzycki**
(I'm surprised there isn't a DenseMap method that returns a sorted array of key-value pairs.)

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Review by davidungar — CHANGES_REQUESTED** [review]
I don't understand, and cannot find an explanation here, for why dense map implementation changes are a problem. What would happen if the order did change? (That ought be a comment somewhere in the code.)

Also, the write function is now both sorting and writing. Assuming the change is needed, I would want to see it factored out: In other words, there would be a separate function, called before the write function, that would be named something like: `canonicalizeOrdering` and a comment explaining why it was necessary, and what would break if the ordering were not canonicalized. (If I were coding it, I would even go farther, having a short function called `insulateFromDenseMapImplementationChanges` that did nothing but call the `canonicalizeOrdering` function. I really like intention-revealing selectors.)

The biggest issue I'm feeling here is a maintainability problem: as the code stands, the next person to have to deal with it won't understand enough to avoid breaking something.

Thanks!

**Comment by davezarzycki** [comment]
Writing the contents of an unordered hash table out to disk is a common programming problem, at least if one cares about predictable results over time. Consider `test/Driver/filelists.swift`. If LLVM updates their algorithms (hashing and/or `DenseMap`), then this test might break because the key/value pairs will be stored in a different order in memory. For example, a LLVM algorithm change can force this change in the Swift test suite:
```
diff --git i/test/Driver/filelists.swift w/test/Driver/filelists.swift
index 544715b9b3..571381c074 100644
--- i/test/Driver/filelists.swift
+++ w/test/Driver/filelists.swift
@@ -7,16 +7,16 @@
 // CHECK-NOT: Handled
 // CHECK: Handled a.swift
 // CHECK-NEXT: Supplementary "./a.swift":
-// CHECK-NEXT: Supplementary swiftmodule: "./a.swiftmodule"
 // CHECK-NEXT: Supplementary swiftdoc: "./a.swiftdoc"
+// CHECK-NEXT: Supplementary swiftmodule: "./a.swiftmodule"
 // CHECK-NEXT: Handled b.swift
 // CHECK-NEXT: Supplementary "./b.swift":
-// CHECK-NEXT: Supplementary swiftmodule: "./b.swiftmodule"
 // CHECK-NEXT: Supplementary swiftdoc: "./b.swiftdoc"
+// CHECK-NEXT: Supplementary swiftmodule: "./b.swiftmodule"
 // CHECK-NEXT: Handled c.swift
 // CHECK-NEXT: Supplementary "./c.swift":
-// CHECK-NEXT: Supplementary swiftmodule: "./c.swiftmodule"
 // CHECK-NEXT: Supplementary swiftdoc: "./c.swiftdoc"
+// CHECK-NEXT: Supplementary swiftmodule: "./c.swiftmodule"
 // CHECK-NEXT: Handled modules
 // CHECK-NOT: Handled
 
```

**Review by jrose-apple — APPROVED** [review]

**Comment by davidungar** [comment]
To someone new to the code base, the sort operation--which is not needed for serialization--implies that either the compiler will break if the map is not sorted, or that the compilation will slow down if the map is not sorted. But you seem to be implying that the only problem that will occur if the order of the map changes is that a test will fail. Do I understand correctly?

**Comment by davezarzycki** [comment]
Hi David – The `test/Driver/filelists.swift` failure is a symptom, but not the problem. The problem is twofold:

1) Updates to fundamental algorithms and collection types, when used correctly, shouldn't cause observable differences in compiler behavior, including the test suite.
2) Sensitivity to unspecified/undefined algorithm or collection type behavior will periodically waste other people's time.

I spent half a day trying to figure out when an innocent change to `include/swift/Basic/FileTypes.def` broke this test. As it turned out, a new file type can change the enum number assigned to other types, and that changes LLVM hashing results, which changes DenseMap bucket assignment, which causes OutputFileMap order to be unstable, but the test relies on stable output.

To be totally clear, I think "the right thing to do" is for `OutputFileMap` to have *stable* order. Sorting is one way to achieve this goal. If you have a better proposal, then please say so.

**Comment by davidungar** [comment]
I'm so sorry you had to spend a half a day figuring out why a too-brittle test failed. I gather that the change to `FileTypes.def` didn't break the *compiler*, but it broke the test. In my view, this event reinforces a widespread problem we have in maintaining and enhancing the Swift compiler: it is too hard to tell which aspects of a test measure *essential* behavior vs which aspect measure *incidental* behavior. I have often looked at test and seen very few comments explaining why the test is there, and what the essential invariant is. In addition to inadequate documentation, some tests, as you sadly discovered, are too brittle.

In the case at hand with this PR, the compiler is *correct* without the sort. It's job is to compile and run Swift code. The test as it stands, is *brittle* without the sort. I believe the answer is to fix the test, not add code to the compiler. Here are my reasons:

1. Every line of code we add to the compiler slows down our work but increasing the build time, slowing down Xcode, and adding to the work involved when any part of it is refactored, modified, etc.

2. Every operation we add to the compiler increases the cognitive burden on the compiler engineer, particularly when the purpose of the operation is unclear. In this case, I would rather investigate a fix to the test, since as I undestand it, it is the test that is broken, yielding a false-negative, not the compiler.

To address your points:

Your point 1:  "Updates to fundamental algorithms and collection types, when used correctly, shouldn't cause observable differences in compiler behavior, including the test suite."

My rebuttal: Suppose we made the compiler 20% faster when used incrementally, as did batch mode last year. That's an observable difference. That's OK. Suppose we changed the order of symbols in a .o file, but everything continued to work OK. Is that observable? Depends. I think your point 1 needs to be refined in order to be clear enough to make sense to me.

Your point 2: "Sensitivity to unspecified/undefined algorithm or collection type behavior will periodically waste other people's time." 

My rebuttal: It will, and it did waste your time. But if I understand you correctly, it was the *test* that was sensitive, not the *compiler.* Fix the test, not the compiler. As I wrote above, adding code that is not vital to the correct execution of compiled Swift programs also wastes other people's time. It can be worthwhile if it significantly speeds up the compiler--our code base has a fair amount of that--but in this case there seems to be a better solution.

I'm so sorry that you ran into this hassle, and I appreciate that you're trying to fix things for folks in the future. But, I believe that this is wrong fix for the long run; and the cumulative effect of applying this paradigm will do more harm than benefit, even though it is easier to modify the compiler than to fix the test. Now, if this sort turns out to be needed for the compiled code to run properly, I would change my mind.

**Comment by davezarzycki** [comment]
I've placed a comment in the source and updated the test suite to be more robust.

@swift-ci please smoke test

**Comment by jrose-apple** [comment]
Dave Z is right here. It's generally a (self-imposed) requirement that the compiler produce deterministic output, because if there *is* a correctness bug somewhere else we want it to be dependent on as few external factors as possible. A DenseMap's iteration order changes not only from machine to machine, but also from run to run.

**Comment by davidungar** [comment]
@jrose-apple How could *this* map's iteration order change from run to run? Could a sort here mask other bugs? I suspect that we may have different definitions of *deterministic.* What are you thinking?

**Comment by jrose-apple** [comment]
An llvm::DenseMap is a hash table, and we shouldn't be assuming how it does its hashing. Maybe it has a per-executing hash seed like Swift does; maybe it uses the address of its storage as salt; maybe it sometimes gets extra capacity from `malloc` and sometimes doesn't depending on system memory pressures or the version of the OS.

I don't *think* a sort here can mask other bugs because we're talking about a file that's only used as communication between the driver and the frontend, which means there's no public requirements on the format at all. It's true that *not* sorting might *turn up* bugs, the same way that order dependencies between .swift files would turn up if we shuffled those when passing them to the frontend, but I think it's valid to make a distinction there: even if it turns out the frontend starts relying on the sorted nature of the supplementary output file map, 

(Note that the determinism principle here isn't necessarily something applied universally—[Foundation.JSONSerialization](https://developer.apple.com/documentation/foundation/jsonserialization) doesn't sort its dictionaries by default, for example—but it *is* a principle we've generally followed in projects of LLVM descent for any sort of output.)

**Comment by davidungar** [comment]
Interesting thoughts about llvm::DenseMap. I figured that, given the culture here about determinism, that the llvm team would have provided a deterministic abstraction, that another run with the same inputs might provide the same outputs. But, sure, let's assume that each run can yield a different ordering of the iteration. I'm still uneasy about the philosophy behind this change and thus, the change itself.

Apologies in advance for bringing up another reason, but the sort changes the algorithmic complexity from O(n) to (n log n). Maybe that's been in the back of my mind. It could be significant with lots of files. (I worry much more about superlinear algorithmic complexity than constant multipliers.)

When I read "I don't think a sort here can mask other bugs" and  "It's true that not sorting might turn up bugs", I don't quite understand what you're asserting. Would you like to clarify?

The tradeoff here seems to be one of adding complexity to the compiler vs adding complexity to the test. When I think about the cumulative effect of each option (over many such PRs), I end up favoring the latter course. In the short term, it may be easier to add complexity to the compiler, but in the long term the effort needed to maintain both the compiler and the tests will be lesser with prioritizing simplicity in the compiler over simplicity in the test.

How can I explain my thoughts better? Here's a hypothetical scenario: Suppose in the future, this map becomes a carrier for more information, and that information has no straightforward ordering. When one performs this change, if the sort is not in the compiler, one can change the compiler first and then address the test. Perhaps the test will have to be changed to ignore the new information. But if the sort is in the compiler, the engineer will have to stop dead and figure out what to do then and there.

In this particular case, one might object that this map will never be extended, but what about other cases? I believe it's better to not impose tighter constraints on the compiler if necessary unless the testing burden would be overwhelming.

Anyway, I hope that explains my position. I realize I am challenging a meme in the culture but I can't in good conscience just sit by and agree to something that I believe will have deleterious long-term effects.

**Comment by jrose-apple** [comment]
In reverse order…

> Here's a hypothetical scenario: Suppose in the future, this map becomes a carrier for more information, and that information has no straightforward ordering. When one performs this change, if the sort is not in the compiler, one can change the compiler first and then address the test. Perhaps the test will have to be changed to ignore the new information. But if the sort is in the compiler, the engineer will have to stop dead and figure out what to do then and there.

I think that's a great example of why this is a *good* change. Since this map is serialized, it's important that we have a way to serialize it deterministically; if new information is added with no straightforward ordering, it is in fact the case that the patch author will have to decide how to handle that.

> The tradeoff here seems to be one of adding complexity to the compiler vs adding complexity to the test. When I think about the cumulative effect of each option (over many such PRs), I end up favoring the latter course. In the short term, it may be easier to add complexity to the compiler, but in the long term the effort needed to maintain both the compiler and the tests will be lesser with prioritizing simplicity in the compiler over simplicity in the test.

This isn't optimizing for testing; it's optimizing for debugging a future problem. We want to minimize circumstances where we're trying to reproduce a bug and it happens only *some* of the time, or based on conditions that differ from machine to machine.

> When I read "I don't think a sort here can mask other bugs" and "It's true that not sorting might turn up bugs", I don't quite understand what you're asserting. Would you like to clarify?

I'll try again. It's something like "There may exist a 'bug' that happen only when certain permutation of keys appears, but if that permutation never actually appears (by design rather than coincidence), it's not a bug that hurts people. There may *also* be a bug that happens only when a certain permutation appears, and the sort makes that permutation *less* likely but not impossible, and that would be masking a real issue; but in this particular case I think that's unlikely."

If we thought this was a real problem, we could also fuzz the parsing code with a variety of orders. But I don't think we think our JSON parsing is broken, and then it's *unlikely* (but I suppose not impossible) that the code on top of the JSON parsing is assuming an order.

> Interesting thoughts about llvm::DenseMap. I figured that, given the culture here about determinism, that the llvm team would have provided a deterministic abstraction, that another run with the same inputs might provide the same outputs. But, sure, let's assume that each run can yield a different ordering of the iteration. I'm still uneasy about the philosophy behind this change and thus, the change itself.
>
> Apologies in advance for bringing up another reason, but the sort changes the algorithmic complexity from O(n) to (n log n). Maybe that's been in the back of my mind. It could be significant with lots of files. (I worry much more about superlinear algorithmic complexity than constant multipliers.)

There *are* other map data structures used in LLVM project (see the [Programmer's Manual](http://llvm.org/docs/ProgrammersManual.html#map-like-containers-std-map-densemap-etc)), and if we identified this as a performance concern we could use a sorted structure up front, or make sure to do a one-time sort ahead of time. But the intent is not necessarily to have every run execute the exact same instructions, but only to guarantee the same behavior and the same output. This is definitely tricky, though, since it means iteration order needs to not affect output! And some people (like @gottesmm) have advocated to remove iteration from DenseMap by default, requiring you to call something like `unordered_entries()` to remind clients at the use site that they might not get the same order every time.

**Comment by davezarzycki** [comment]
@jrose-apple – I support your perspective and position in this pull request but I don't have the time to debate it with @davidungar and we can sort the DenseMap output later.

@davidungar – I believe I made the requested changes, can you please approve this? Thanks.

**Comment by davidungar** [comment]
@jrose-apple Thank you for clarifying. Often you understand something about the behavior of the system that I do not, and I'm happy to be proven wrong in those cases. Here, I *think* I understand the facts of the issue accurately: There is no advantage to the compiler user of a sort to this structure.

You mention: " if new information is added with no straightforward ordering, it is in fact the case that the patch author will have to decide how to handle that." That argument begs the question. The question is whether we should insist that the compiler produce this file in a sorted, deterministic order. If we specify that the file order may be variable, then the patch author need not worry about it. 

> This isn't optimizing for testing; it's optimizing for debugging a future problem. We want to minimize circumstances where we're trying to reproduce a bug and it happens only some of the time, or based on conditions that differ from machine to machine.
The original motivation as I understood it was a test failure caused by an algorithm change:

> I spent half a day trying to figure out why an innocent change to include/swift/Basic/FileTypes.def broke this test.
The compiler worked, but the test broke. But I understand your point. I'd be surprised if the DenseMap were so inconsistent and the system so sensitive to the ordering that we'd ever see such a bug. But if we do, I'll you and @davezarzycki lunch.

Thanks for clarifying the bug-likelihood w.r.t. sorting point. (I wish we had memory-safety in the language!) I really like your idea, though, of removing all the sorts we have just for the sake of determinism and deliberately fuzzing every ordering for testing.

I don't see where you've addressed my objection to the increase in big-O complexity from N to N log N. In fact, *any* sort--sorting up front, or a one-time sort--we use for almost anything (radix sort being an outlier) will introduce a log N term to the time required. In cases where the N might be significant, the log N can potentially become an issue. Unordered hashing, by contrast, as you know, has only O(N) expected complexity, but can go pathological in the worse case.

It seems that our differing experiences has left us with different ideas about nourishing a large code base in order for it to thrive. Thank you for your thoughtfulness and think about where you'd like to go to collect that free lunch when you're proven right!

**Review by davidungar — APPROVED** [review]
@davezarzycki Thanks a lot! Sorry to have slowed things down. Hope I was right, but I guess time will tell.

**Pull request merged**
