### PR TITLE
[Completion] Remove unused DocWords

### PR DESCRIPTION
**Pull request by bnbarham**
The various keyword/recommended/etc fields were parsed and added to
completions, but never actually plumbed through SourceKit. Since they're
still unused and the implementation is not particularly lightweight,
just remove for now.

Resolves rdar://82464220

### CODE REVIEW

**Comment by bnbarham** [comment]
@rintaro I've left the documentation in the test files for now, do you think it's worth removing them as well (eg. test/Inputs/clang-importer-sdk/usr/include/ctypes.h).

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
@swift-ci please test

**Review by rintaro — APPROVED** [review]
Thank you!

> I've left the documentation in the test files for now, do you think it's worth removing them as well

Let's keep it for now, to ensure that those fields don't crash the doc-comment parser.

**Comment by bnbarham** [comment]
> Let's keep it for now, to ensure that those fields don't crash the doc-comment parser.

Sounds good, thanks.

**Pull request merged**
