### PR TITLE
[build] specify deployment targets for compatibility libraries

### PR DESCRIPTION
**Pull request by edymtt**
This is needed in situations where the minimum deployment target is
specified in build-script -- these libraries do not to obey to that
since we need to ensure we are able to back deploy those correctly.

Addresses rdar://59249988

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci please test

**Comment by edymtt** [comment]
@swift-ci please smoke test

**Comment by edymtt** [comment]
@swift-ci please clean test Windows

**Review by lorentey — APPROVED** [review]
This looks good to me! 

At some point soon, we'll need to bump the deployment targets we use for the stdlib/runtime/overlays to the last major OS releases (or the ones below), but I believe these should always deploy to the lowest possible versions.

**Comment by edymtt** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by edymtt** [comment]
@swift-ci Please Build Toolchain Linux Platform

**Comment by shahmishal** [comment]
@edymtt Would it be possible to use the values from https://github.com/apple/swift/blob/master/utils/build_swift/build_swift/defaults.py#L55 to avoid having to duplicate version info in multiple places? 

```
DARWIN_DEPLOYMENT_VERSION_OSX = '10.9'
DARWIN_DEPLOYMENT_VERSION_IOS = '7.0'
DARWIN_DEPLOYMENT_VERSION_TVOS = '9.0'
DARWIN_DEPLOYMENT_VERSION_WATCHOS = '2.0'
```

**Comment by edymtt** [comment]
I'm not sure if I can import straight from a Python file -- I see the main `CMakeLists.txt` defines them again at https://github.com/apple/swift/blob/master/CMakeLists.txt#L311

```
set(SWIFT_DARWIN_DEPLOYMENT_VERSION_OSX "10.9" CACHE STRING
    "Minimum deployment target version for OS X")

set(SWIFT_DARWIN_DEPLOYMENT_VERSION_IOS "7.0" CACHE STRING
    "Minimum deployment target version for iOS")

set(SWIFT_DARWIN_DEPLOYMENT_VERSION_TVOS "9.0" CACHE STRING
    "Minimum deployment target version for tvOS")

set(SWIFT_DARWIN_DEPLOYMENT_VERSION_WATCHOS "2.0" CACHE STRING
    "Minimum deployment target version for watchOS")
```

I preferred to define those locally to be on the safe side -- just in case I misunderstood that those values now happen to be in the same but in the future they need to diverge. If that's not the case, I can try to refine this PR further.

**Review by shahmishal — APPROVED** [review]

**Comment by compnerd** [comment]
The values need to be defined in CMake, not in python, @edymtt is correct about defining twice.

**Pull request merged**
