### PR TITLE
Re-apply #70910 and fix 32-bit build with SWIFT_CONCURRENCY_ENABLE_PRIORITY_ESCALATION

### PR DESCRIPTION
**Pull request by nickolas-pohilets**
Reverts https://github.com/apple/swift/pull/73808

Moved `isDistributedRemoteActor` up, as suggested [by @rjmccall](https://github.com/apple/swift/pull/73808#issuecomment-2135592830).

Now the layout looks like this:

```
0:  isa
4:  refcount
8:  isDistributedRemoteActor
12: alignment padding
16: StatusStorage
20: StatusStorage
24: StatusStorage 
28: StatusStorage 
32: PriorityQueue
36: PriorityQueue
40: PriorityQueue
44: PriorityQueue
48: PriorityQueue
52: PriorityQueue
56: trailing padding
```

### CODE REVIEW

**Comment by ktoso** [comment]
Thanks, I'll verify this on a 32bit box and report back!

**Comment by ktoso** [comment]
@swift-ci please test

meanwhile letting this test run here as well so it's ready to go when we are

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
Either way I'll make myself a reminder to implement the "TODO: make a flagset", we should do this anyway (rdar://128999427)

**Comment by nickolas-pohilets** [comment]
Fix few issues. @ktoso, could you pls start new CI job?

Implementation is quite hacky, I'm not super happy about it and open for better suggestions.

1. I have doubts about how reliable implementation of the `size_without_trailing_padding`  is. If it is not reliable, `static_assert` in Actor.cpp can give false negatives, which is pretty bad. Should we add assertions for each individual field, to be sure?
2. Added unit-tests are probably too strict. Based on [this discussion](https://stackoverflow.com/questions/53837373/standard-layout-and-tail-padding), current implementation of the unit test relies too much on Itanium ABI. For other ABI, test may fail not because there are bugs in the implementation, but because fixture types are not suitable.

**Comment by ktoso** [comment]
Previous seemed to have passed initial testing, I'll pick the last two commits as well and run another "complete" test run, those take multiple hours, but we'll know soon. 

Not sure 1) though, perhaps @rjmccall has insight on that. 

In the meantime I'll verify the latest commits here, thanks for looking into this.

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
I've confirmed 32bit issue is solved by this patch, thank you @nickolas-pohilets.

**Review by ktoso — APPROVED** [review]

**Comment by ktoso** [comment]
Resolves rdar://114953765

**Comment by ktoso** [comment]
I gave this another read and as mentioned above verified internally as well.
I think we should give it another go and have prepared a pick for Swift 6.0 over here: https://github.com/apple/swift/pull/74112

Thanks for your effort over this long review period, thanks @nickolas-pohilets !

**Pull request merged**
