### PR TITLE
Fix `symbol-visibility-linux.test-sh` on CentOS

### PR DESCRIPTION
**Pull request by egorzhdan**
rdar://108041802

### CODE REVIEW

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test Linux

**Comment by egorzhdan** [comment]
@swift-ci please test Windows

**Review by bnbarham — APPROVED** [review]

**Review by compnerd — APPROVED** [review]
:sigh: ... more std::char_traits leakage into the binaries :(

**Pull request merged**
