### PR TITLE
[interop][SwiftToCxx] do not assert when emitting a public var and fu…

### PR DESCRIPTION
**Pull request by hyp**
…nction with the same C++ name

### CODE REVIEW

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test source compatibility

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test

**Review by ravikandhadai — APPROVED** [review]

**Pull request merged**
