### PR TITLE
[AutoDiff] Fix real vector initialization and add more logging

### PR DESCRIPTION
**Pull request by rxwei**
* Fix real vector initialization.
* NFC: Add more logging and real vector test cases

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux CPU

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux GPU

**Review by marcrasi — APPROVED** [review]

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux GPU

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux GPU

**Comment by rxwei** [comment]
GPU is always flaky :(

**Pull request merged**
