### PR TITLE
 Add stronger SILVerifier support for formal access. 

### PR DESCRIPTION
**Pull request by atrick**
Ensure that all formal access follows recognizable patterns
at all points in the SIL pipeline.

This is important to run acccess enforcement optimization late in the pipeline.

This is a single-commit PR building on https://github.com/apple/swift/pull/16877

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
@swift-ci test source compatibility.

**Comment by gottesmm** [comment]
+1! Static verification FTW!

**Comment by atrick** [comment]
@swift-ci test source compatibility.

**Comment by atrick** [comment]
This PR can't be merged until I handle all the access patterns that show up in debug builds.

**Comment by atrick** [comment]
Closing and folding the change into https://github.com/apple/swift/pull/16877.

**Pull request closed without merging**
