### PR TITLE
[CodeCompletion] Reduce accumulating memory per fast completion

### PR DESCRIPTION
**Pull request by rintaro**
For each fast completion, the memory grows for the source buffer and the AST of the function body. They are kept until the next slow completion.

To mitigate the memory consumption per completion, use sliced source text which is actually needed for the second pass.

rdar://problem/58119719

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Review by benlangmuir — APPROVED** [review]

**Pull request merged**
