### PR TITLE
[5.1] Enable evolution tests for swift_test_mode optimize_none_with_implicit_dynamic

### PR DESCRIPTION
**Pull request by aschwaighofer**
rdar://51304243

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test macos x

**Review by slavapestov — APPROVED** [review]

**Comment by aschwaighofer** [comment]
@swift-ci Please test mac os

**Comment by aschwaighofer** [comment]
@swift-ci Please test os x platform

**Pull request merged**
