### PR TITLE
Re-enable swift docc tests

### PR DESCRIPTION
**Pull request by talzag**
rdar://90181251

This re-enables Swift-DocC tests in toolchain builds.

### CODE REVIEW

**Comment by talzag** [comment]
Please test with the following pull request:
https://github.com/apple/swift-docc/pull/101

@swift-ci please test

**Comment by talzag** [comment]
Please test with the following pull request:
https://github.com/apple/swift-docc/pull/101

@swift-ci please smoke test macOS platform

**Comment by talzag** [comment]
Please test with the following pull request:
https://github.com/apple/swift-docc/pull/101

@swift-ci Please Build Toolchain macOS Platform

**Comment by talzag** [comment]
Please test with following pull request:
https://github.com/apple/swift-docc/pull/101

@swift-ci Please test

**Comment by talzag** [comment]
https://github.com/apple/swift-docc/pull/101

@swift-ci Please test

**Comment by talzag** [comment]
https://github.com/apple/swift-docc/pull/101

@swift-ci Please Build Toolchain

**Comment by talzag** [comment]
https://github.com/apple/swift-docc/pull/101
@swift-ci Please smoke test macOS platform

**Comment by talzag** [comment]
https://github.com/apple/swift-docc/pull/101
@swift-ci Please smoke test macOS platform

**Comment by talzag** [comment]
https://github.com/apple/swift-docc/pull/101

@swift-ci Please Build Toolchain

**Comment by talzag** [comment]
https://github.com/apple/swift-docc/pull/101
@swift-ci Please Build Toolchain macOS Platform

**Comment by talzag** [comment]
https://github.com/apple/swift-docc/pull/101
@swift-ci Please Build Toolchain Linux Platform

**Comment by talzag** [comment]
https://github.com/apple/swift-docc/pull/101
@swift-ci Please Build Toolchain Linux Platform

**Comment by talzag** [comment]
https://github.com/apple/swift-docc/pull/101
@swift-ci Please Build Toolchain macOS Platform

**Comment by talzag** [comment]
https://github.com/apple/swift-docc/pull/101
@swift-ci Please Build Toolchain Linux Platform

**Comment by talzag** [comment]
https://github.com/apple/swift-docc/pull/101
@swift-ci Please Build Toolchain macOS Platform

**Comment by talzag** [comment]
https://github.com/apple/swift-docc/pull/101
@swift-ci Please Build Toolchain Linux Platform

**Comment by talzag** [comment]
https://github.com/apple/swift-docc/pull/101
@swift-ci Please Build Toolchain Linux Platform

**Comment by talzag** [comment]
https://github.com/apple/swift-docc/pull/101

@swift-ci Please Build Toolchain Linux Platform

**Comment by talzag** [comment]
https://github.com/apple/swift-docc/pull/101

@swift-ci Please Build Toolchain macOS Platform

**Comment by talzag** [comment]
https://github.com/apple/swift-docc/pull/101
@swift-ci Please Build Toolchain macOS Platform

**Comment by talzag** [comment]
https://github.com/apple/swift-docc/pull/101
@swift-ci Please Build Toolchain macOS Platform

**Comment by talzag** [comment]
https://github.com/apple/swift-docc/pull/101
@swift-ci Please Build Toolchain macOS Platform

**Comment by talzag** [comment]
https://github.com/apple/swift-docc/pull/101
@swift-ci Please Build Toolchain Linux Platform

**Comment by talzag** [comment]
@swift-ci Please test

**Comment by talzag** [comment]
@swift-ci Please Build Toolchain

**Comment by talzag** [comment]
@swift-ci Please smoke test

**Comment by talzag** [comment]
@swift-ci Please test

**Comment by talzag** [comment]
@swift-ci Please Build Toolchain

**Comment by talzag** [comment]
@swift-ci Please test

**Comment by talzag** [comment]
@swift-ci Please smoke test

**Comment by talzag** [comment]
@swift-ci please build toolchain

**Comment by talzag** [comment]
@swift-ci please test macOS platform

**Comment by talzag** [comment]
@swift-ci Please test

**Comment by talzag** [comment]
@swift-ci Please smoke test

**Comment by talzag** [comment]
@swift-ci please test

**Comment by talzag** [comment]
@swift-ci please test

**Comment by talzag** [comment]
@swift-ci Please smoke test

**Comment by talzag** [comment]
@swift-ci please build toolchain

**Comment by talzag** [comment]
@swift-ci please test

**Comment by talzag** [comment]
@swift-ci please smoke test

**Comment by talzag** [comment]
@swift-ci please build toolchain

**Comment by talzag** [comment]
@swift-ci Please Build Toolchain Linux Platform

**Review by ethan-kusters — APPROVED** [review]
Thanks for your work on this @talzag!

I think we should get sign-off from @shahmishal or @drewmaxwell-apple on this as well.

@talzag can you briefly summarize the work you did to confirm the issues that caused us to originally disable these tests have been resolved?

**Comment by talzag** [comment]
> @talzag can you briefly summarize the work you did to confirm the issues that caused us to originally disable these tests have been resolved?

Thanks @ethan-kusters. After making sure that DocC tests passed when run both serially and concurrently, I repeatedly ran CI tests (smoke, full, and toolchain). After almost a month, I haven't seen any more issues with DocC tests. I believe that the flakiest tests have all been disabled, and the rest of the tests are now stable and deterministic.

**Comment by talzag** [comment]
Ping @shahmishal or @drewmaxwell-apple for a review, too.

**Review by shahmishal — APPROVED** [review]

**Pull request merged**
