### PR TITLE
ppc64le custom presets.

### PR DESCRIPTION
**Pull request by asowani**
Contains build presets for ppc64le.

### CODE REVIEW

**Comment by asowani** [comment]
Can this custom preset be merged to 4.2 branch please? Unless this becomes available, Jenkins build for 4.2 branch cannot be started. Thanks!

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by airspeedswift** [comment]
Is this a merge of a fix from master? If not, the process would normally be to do that first.

**Comment by airspeedswift** [comment]
Hi @asowani – is this PR still active or can it be closed? If the goal is to add this support, please add it to master first, then it can be added to 4.2 subsequently via a PR that cherry-picks that change. Thanks!

**Comment by asowani** [comment]
@airspeedswift I will add this change to Master. I am not sure if this PR should be kept open in order to get cherry-picked or can be closed safely. Please advise. Thanks!

**Comment by airspeedswift** [comment]
It is probably easiest to close this PR and raise a new one when needed. In fact, is it really necessary to get this change onto 4.2? The branch is almost done at this point so just working on master alone would make more sense if this port is a work-in-progress.

**Comment by asowani** [comment]
@airspeedswift I have already raised a PR for master branch at https://github.com/apple/swift/pull/16883
This PR is still open.

**Pull request closed without merging**
