### PR TITLE
Introduce DescriptiveDeclKind::Property

### PR DESCRIPTION
**Pull request by jrose-apple**
...and collapse StaticVar/ClassVar and StaticLet/ClassLet into StaticProperty/ClassProperty.

"var" and "let" aren't great nouns to use in diagnostics to begin with, especially alongside semantic terms like "instance method". Focus on the type vs. non-type aspect instead with "property", which better matches how people talk about member vars (and lets) anyway.

### CODE REVIEW

**Comment by jrose-apple** [comment]
CCing some people who've had opinions on diagnostics in the past: @erica, @xwu, @jckarter, @lattner.

@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
Ah, right, sometimes people match diagnostic strings in unusual configurations.

@swift-ci Please test

**Comment by lattner** [comment]
+1, nice improvement!

**Comment by jrose-apple** [comment]
Huh, not sure how that one didn't get caught locally.

**Comment by jrose-apple** [comment]
Ah, because I hadn't rebased recently.

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
That was a reasonable comment period, I guess. One more test to check if anyone added any new diagnostics.

@swift-ci Please smoke test

**Comment by xwu** [comment]
Just saw this; LGTM!

**Pull request merged**
