### PR TITLE
[Sema] NFC: Use exhaustive switches in PatternKind::Named

### PR DESCRIPTION
**Pull request by davezarzycki**
Also, flip the polarity so that programmers that add new ReferenceOwnership kinds know what to do. This is a followup to #15419.

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Review by rudkx — APPROVED** [review]
LGTM, thanks!

**Comment by davezarzycki** [comment]
Thanks @rudkx – This makes my research branch easier to maintain.

**Pull request merged**
