### PR TITLE
Switch enum changes for convert optional to optional

### PR DESCRIPTION
**Pull request by gottesmm**
This commit contains the beginnings of the switch_enum changes for ownership.

Specifically, it creates a new API called SwitchEnumBuilder. The builder is a closure based API that ensures that if you use object types for your switch, all of the case headers will have proper managed values and cleanups. It also will ensure that people do not forget to pass through the original argument in the default case. The API will just take care of that for you. It does not make any assumptions about whether or not the switch has a continuation block.

The rest of the PR is wiring up this builder to emitOptionalToOptional.

rdar://29791263

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci Please smoke test

**Comment by gottesmm** [comment]
I think on the Linux side I ran into a compatibility issue with my usage of tuple. I am trying this again with just normal structs and using emplace_back in SmallVector.

**Comment by gottesmm** [comment]
@swift-ci Please smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci Please smoke test and merge

**Comment by jrose-apple** [comment]
switch_enum has the tendency to be slower than select_enum. Did you benchmark this?

**Comment by gottesmm** [comment]
@jrose-apple I am not sure if that is true anymore. I think that observation was made in the early days of swift. In the optimizer, IIRC, we even just canonicalize away from these. If smooshbase finds that a big issue came up at -Onone, I will look into it.

**Pull request merged**
