### PR TITLE
Improvements to Escape Analysis

### PR DESCRIPTION
**Pull request by meg-gupta**
This PR consists of improvements to EscapeAnalysis around guaranteed args

Escape analysis returns unnecessarily conservative results for guaranteed args which can limit ARC optimizations among others.

Example:

```
sil hidden [noinline] @$s4test3fooyyF : $@convention(thin) () -> () {
bb0:
  %box = alloc_box $<τ_0_0> { var τ_0_0 } <Builtin.Int32>
  %proj = project_box %box : $<τ_0_0> { var τ_0_0 } <Builtin.Int32>, 0
  %funcref = function_ref @userg : $@convention(thin) (@guaranteed <τ_0_0> { var τ_0_0 } <Builtin.Int32>) -> ()
  strong_retain %box : $<τ_0_0> { var τ_0_0 } <Builtin.Int32>
  apply %funcref (%box) : $@convention(thin) (@guaranteed <τ_0_0> { var τ_0_0 } <Builtin.Int32>) -> () // id: applyId
  strong_release %box : $<τ_0_0> { var τ_0_0 } <Builtin.Int32>
  strong_release %box : $<τ_0_0> { var τ_0_0 } <Builtin.Int32>
  %tup = tuple ()    
  return %tup : $()    
}
```

Here EscapeAnalysis::canEscapeTo returns true for %box and %applyId in spite of it not escaping. The current implementation depends on isUsePoint which is stricter than necessary. isUsePoint considers any apply arg as a use. guaranteed args cannot be released in an apply unless they have already escaped.

UsePoints used to compute EscapeAnalysis::canEscapeTo in turn get used in AliasAnalysis' mayReadFromMemory, mayWriteToMemory, canApplyDecrementRefCount, etc. The effectiveness of optimizations like RLE, ARCSequenceOpts, DSE depends on these queries.

With this change, "use points" are split into "release points" and "access points". ReleasePoints consists of release and consuming apply instructions. AccessPoints consists of guaranteed args passed to apply instructions. canEscapeTo is split into canEscapeToRelease and canEscapeToAccess.

With this apply's MemoryBehavior can be computed using both canEscapeToRelease and canEscapeToAccess. And queries like AliasAnalysis::canApplyDecrementRefCount is improved for guaranteed args.

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci Please Test Source Compatibility

**Comment by airspeedswift** [comment]
@swift-ci please benchmark@swift-ci please benchmark

**Comment by meg-gupta** [comment]
@swift-ci please benchmark

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci Please Test Source Compatibility

**Comment by meg-gupta** [comment]
@swift-ci please benchmark

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
