### PR TITLE
[libcxx] Simplify the conditions for building libcxx

### PR DESCRIPTION
**Pull request by benlangmuir**
Now we build libcxx if and only if --libcxx is passed, like with other
optional products.  This loses the intended "build if sources are
checked out" behaviour, but behaves more predictably.

### CODE REVIEW

**Comment by benlangmuir** [comment]
@swift-ci please smoke test

**Comment by benlangmuir** [comment]
@swift-ci please build toolchain

**Comment by benlangmuir** [comment]
CC @shahmishal @hyp

**Review by shahmishal — APPROVED** [review]
Thanks!

**Pull request merged**
