### PR TITLE
[stdlib] Add PointwiseMultiplicative protocol.

### PR DESCRIPTION
**Pull request by dan-zheng**
`PointwiseMultiplicative` represents a ring over multiplication with identity element "one".

```swift
public protocol PointwiseMultiplicative : AdditiveArithmetic {
  static var one: Self { get }
  var reciprocal: Self { get }

  static func .*(lhs: Self, rhs: Self) -> Self
  static func .*=(lhs: inout Self, rhs: Self)
}
```

Enables revamping optimizers, which requires division (i.e. multiplication with multiplicative inverse). https://github.com/tensorflow/swift-apis/pull/218

### CODE REVIEW

**Comment by rxwei** [comment]
The protocol requirements should not use operators from existing `Numeric` protocols. We should probably use `.*` for now.

**Comment by rxwei** [comment]
This protocol should also inherit from `AdditiveArithmetic`.

**Review by rxwei — APPROVED** [review]

**Comment by dan-zheng** [comment]
Ready for review.
- Add `reciprocal` requirement to `PointwiseMultiplicative`. This enables `(Self, Self) -> Self` division (via multiplication with reciprocal).
- Conform `Differentiable` synthesized struct types to `PointwiseMultiplicative` protocol if possible. This unblocks optimizer revamp: https://github.com/tensorflow/swift-apis/pull/218.

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Pull request merged**
