### PR TITLE
[stdlib] Restore concrete initializers on Unsafe{Raw}Pointer

### PR DESCRIPTION
**Pull request by airspeedswift**
This is part 1 of 2-part solution to [SR-9800](https://bugs.swift.org/browse/SR-9800)

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@swift-ci please smoke test

**Comment by airspeedswift** [comment]
@swift-ci please smoke test

**Comment by airspeedswift** [comment]
@swift-ci please smoke test macOS platform

**Review by atrick — APPROVED** [review]
This all looks good to me.

I don't exactly remember why we needed to be permissive with `AutoreleasingUnsafeMutablePointer`. I think it's used for some particular ObjC APIs and the hope was that eventually wouldn't be needed(?) Anyway, we clearly want to revert to the 4.2 behavior, so this PR does the right thing.

**Review by moiseev — APPROVED** [review]
:shipit:

**Comment by airspeedswift** [comment]
@swift-ci please benchmark

**Comment by airspeedswift** [comment]
@swift-ci please test source compatibility

**Pull request merged**
