### PR TITLE
Explicit llvm::StringRef -> std::string

### PR DESCRIPTION
**Pull request by Ktwu**
https://github.com/llvm/llvm-project/commit/777180a32b61070a10dd330b4f038bf24e916af1 got rid of implicit casting for llvm::StringRef; it's an expensive operation. This change attempts to respect this upcoming work by dumbly migrating StringRef -> std::string sites (as exposed by my local build).

### CODE REVIEW

**Comment by xiaobai** [comment]
@swift-ci please test

**Comment by xiaobai** [comment]
cc @compnerd

**Comment by compnerd** [comment]
Just even scrolling through this, I noticed a few places which made me uneasy.  This is going to require a careful audit :-(

**Comment by Ktwu** [comment]
@compnerd I wouldn't want this to go in *without* a careful audit :D

If you mark up which place scare you, maybe I can split up this PR?

**Comment by compnerd** [comment]
This is far too large, please split this up.  The driver one should be rather easy and quick to get through.  Similarly Frontend should be quick and easy.

**Comment by Ktwu** [comment]
@compnerd  noted, I'll break up future PRs.

I believe that the string casting has been resolved by someone else since I uploaded this PR, so closing!

**Pull request closed without merging**
