### PR TITLE
CopyForwarding - small redesign to fix bugs.

### PR DESCRIPTION
**Pull request by atrick**
Copy forwarding was designed with some assumptions about symmetry of
operations. If copy_value/destroy_value are expanded somewhere for a given
value, then they should be expanded everywhere. The pass took a conservative
approach to SIL patterns that were guaranteed safe and bailed out on unknown
patterns. However, due to some over-aggressive code factoring, the assumption
wasn't being checked in one corner case.

This redesign makes a clear distinction between the requirements for forward
vs. backward propagation.

Fixes <rdar://35646292> Swift CI: resilience bot seg faults in
stdlib/RangeReplaceable.swift.gyb

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test.

**Comment by slavapestov** [comment]
Thanks for fixing this! Don't forget you need to un-XFAIL the actual failing test though.

**Comment by atrick** [comment]
@swift-ci test and merge.

**Comment by atrick** [comment]
@swift-ci test and merge.

**Pull request merged**
