### PR TITLE
Revert "[cxx-interop] Fix crash when indexing with C++ interop enabled."

### PR DESCRIPTION
**Pull request by zoecarver**
This reverts commit 883a9abf53799591dbb4c074bc3dd682327f3fcb. Leaves the test.

### CODE REVIEW

**Comment by zoecarver** [comment]
@swift-ci please test

**Comment by zoecarver** [comment]
@swift-ci please test macos

**Comment by zoecarver** [comment]
@swift-ci please test macOS platform

**Comment by zoecarver** [comment]
@swift-ci please test macOS platform

**Comment by hyp** [comment]
@swift-ci please test macOS platform

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@zoecarver I updated this test to now only run on supported SDKs with CF_OPTIONS fix :)

**Pull request merged**
