### PR TITLE
Revert "[swiftc (49 vs. 5396)] Add crasher in swift::constraints::ConstraintGraphNode::getEquivalenceClass(...)"

### PR DESCRIPTION
**Pull request by airspeedswift**
Reverts apple/swift#6658

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci Please test

**Comment by airspeedswift** [comment]
@swift-ci please clean test macOS platform

**Comment by CodaFi** [comment]
Is it possible this is nondeterministic? // @practicalswift

**Comment by airspeedswift** [comment]
Test seems to be failing in the same way on all subsequent PRs, but it's possible the original PR struck it lucky, or it's a clean vs incremental build thing.

**Pull request merged**
