### PR TITLE
Use common BottomUpFunctionOrder instance while updating FunctionWorklist

### PR DESCRIPTION
**Pull request by meg-gupta**
Using the same BottomUpFunctionOrder object for subsequent updates to the FunctionWorklist can provide caching of DFS  states and speed up in the case where newly created functions have a lot of common callees to be explored via DFS.
However if the newly created functions have a large number of unique callees, this leads to some unwanted reordering of FunctionWorklist. This fix favors the former case because DFS is more expensive than list reordering. Also based on experiments related to compilation times in some common Swift programs.

Fixes rdar://69073705

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci test

**Review by eeckstein — APPROVED** [review]
LGTM!

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
This can cause sub-optimal bottom up function order when a newly added function has a caller who is also newly added and present in the SubBottomUpOrder.

**Pull request closed without merging**
