### PR TITLE
ClangImporter: Adapt to clang -m[OS]-version-min change

### PR DESCRIPTION
**Pull request by aschwaighofer**
Clang change 1ac71826854a809f67ae15ddacaaa9a6eb8189e8.

This is ailing the bots.

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
WARNING: DONT MERGE THIS BECAUSE the clang change was already reverted on swift-4.1-branch and is only waiting to get through to stable!!!!

**Comment by aschwaighofer** [comment]
@swift-ci Please clean test mac os x

**Comment by aschwaighofer** [comment]
@swift-ci Please clean test mac os platform

**Comment by aschwaighofer** [comment]
@swift-ci Please clean test OS X platform

**Comment by aschwaighofer** [comment]
```
FAILED: lib/swift/iphoneos/arm64/libswiftXCTest.dylib 
: && /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/llvm-macosx-x86_64/./bin/clang++  -Wno-unknown-warning-option -Werror=unguarded-availability-new -fno-stack-protector -stdlib=libc++ -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -std=c++11 -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -fcolor-diagnostics -Werror=switch -Wdocumentation -Wimplicit-fallthrough -Wunreachable-code -Woverloaded-virtual -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -fno-sanitize=all -DLLVM_DISABLE_ABI_BREAKING_CHECKS_ENFORCING=1 -O3 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -dynamiclib -Wl,-headerpad_max_install_names -stdlib=libc++   -target arm64-apple-ios7.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -arch arm64 -F /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/../../../Developer/Library/Frameworks -mios-version-min=8.0 -Wl,-sectcreate,__TEXT,__info_plist,/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/stdlib/public/SDK/XCTest/Info.plist  "-L/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/./lib/swift/iphoneos/arm64" "-L/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/./bin/../lib/swift/iphoneos/arm64" "-L/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/./bin/../lib/swift/iphoneos" -o lib/swift/iphoneos/arm64/libswiftXCTest.dylib -install_name @rpath/libswiftXCTest.dylib stdlib/public/SDK/XCTest/iphoneos/arm64/XCTest.o stdlib/public/SDK/XCTest/CMakeFiles/swiftXCTest-iphoneos-arm64.dir/XCTestCaseAdditions.mm.o -L/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/llvm-macosx-x86_64/./lib -framework Foundation -framework XCTest lib/swift/iphoneos/arm64/libswiftCoreMedia.dylib lib/swift/iphoneos/arm64/libswiftUIKit.dylib -framework CoreMedia -framework UIKit lib/swift/iphoneos/arm64/libswiftFoundation.dylib lib/swift/iphoneos/arm64/libswiftObjectiveC.dylib lib/swift/iphoneos/arm64/libswiftCore.dylib -framework Foundation -framework CoreFoundation && :
clang-5.0: warning: argument unused during compilation: '-miphoneos-version-min=8.0' [-Wunused-command-line-argument]
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: embedded dylibs/frameworks are only supported on iOS 8.0 and later (@rpath/XCTest.framework/XCTest) file '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest' for architecture arm64
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by bob-wilson** [comment]
Sorry, Arnold. I made exactly the same change for master-next yesterday but held off creating a PR when Alex reverted it.

**Comment by CodaFi** [comment]
Looks like Bob got to this in a84243c

**Pull request closed without merging**
