### PR TITLE
[android] Link with static C++ ABI for Android.

### PR DESCRIPTION
**Pull request by drodriguez**
Normally, the C++ shared library would have link against the C++ ABI
shared library, but the Android NDK does not distribute the later, so
one need to link manually against the static C++ ABI from the NDK.

/cc @compnerd

### CODE REVIEW

**Review by compnerd — APPROVED** [review]
Might be nice to extract the path into a variable at this point (its being repeated ~4x).

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by drodriguez** [comment]
Added the variable to avoid repetition. Tell me if you want the variable somewhere else, or just there is fine.

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Pull request merged**
