### PR TITLE
Deserialize fewer vtables in -Onone

### PR DESCRIPTION
**Pull request by slavapestov**
Also some small cleanups.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
For this program, 

```
print("Hello world")

[1, 2, 3, 4, 5, 6].map { $0 * 2 }.reduce(0, +)
```

`swiftc -emit-sil | wc -l` goes from 18014 to 14982.

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by gottesmm** [comment]
Nice commit messages.

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test compiler performance

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test compiler performance

**Comment by slavapestov** [comment]
@gottesmm since this consists of the changes we already discussed, together with tests and new commit messages, I'm assuming you're OK with me merging this.

**Comment by gottesmm** [comment]
Yes

**Comment by gottesmm** [comment]
Sorry, I should have been clearer when I say nice commit messages.

**Pull request merged**
