### PR TITLE
Cherry pick fixes from 5.0 to swift-5.1-branch

### PR DESCRIPTION
**Pull request by bob-wilson**
The PR includes 2 fixes that were merged to swift-5.0-branch without being pulled in for the 5.1 branch:

rdar://problem/48208253: Rintaro's code completion fix
rdar://problem/48239213: Andy's change to disable merging of read/modify exclusivity access markers

### CODE REVIEW

**Comment by bob-wilson** [comment]
@swift-ci please test

**Comment by slavapestov** [comment]
Please remove my two patches from this PR -- I'm merging them in https://github.com/apple/swift/pull/22819

**Comment by bob-wilson** [comment]
OK, let's try again without Slava's changes.

**Comment by bob-wilson** [comment]
@swift-ci please test

**Comment by bob-wilson** [comment]
@swift-ci please test

**Comment by bob-wilson** [comment]
I don't understand these build failures. Trying yet again....

**Comment by bob-wilson** [comment]
@swift-ci please test

**Comment by bob-wilson** [comment]
I reproduced the failure locally. The IRGen/class_resilience_objc.swift test is failing this CHECK line:

// CHECK: @"$s21class_resilience_objc27ClassWithEmptyThenResilientC9resilient0I7_struct0H3IntVvpWvd" = hidden global [[INT]] 0,

because the output has:

hidden global i64 8, align 8

@rjmccall Do you have any idea what is wrong here? There were some differences between 5.0 and master and I tried to get the right adjustments for 5.1 (which is in between those).

**Comment by rjmccall** [comment]
@bob-wilson I already pulled that commit to 5.1 in #22818.

**Comment by bob-wilson** [comment]
OK, dropping John's change.... Let's try again.

**Comment by bob-wilson** [comment]
@swift-ci please test

**Comment by bob-wilson** [comment]
@swift-ci please test linux platform

**Comment by bob-wilson** [comment]
@swift-ci please test linux platform

**Pull request merged**
