### PR TITLE
[ResultBuilders] `buildPartialBlock` support

### PR DESCRIPTION
**Pull request by rxwei**
This PR implements support for `buildPartialBlock` as proposed in https://forums.swift.org/t/pitch-buildpartialblock-for-result-builders/55561. This is similar to the existing support for `buildBlock(combining:into:)` except that it also checks for availability when deciding whether to fall back to plain old `buildBlock`.

> In the result builder transform, the compiler will look for static members `buildPartialBlock(first:)` and `buildPartialBlock(accumulated:next:)` in the builder type. If the following conditions are met:
> - Both methods `buildPartialBlock(first:)` and `buildPartialBlock(accumulated:next:)` exist.
> - The availability of the enclosing declaration is greater than or equal to the availability of `buildPartialBlock(first:)` and `buildPartialBlock(accumulated:next:)`.

When there's no available `buildPartialBlock` to call and there's no `buildBlock`, emit a diagnostic:
```console
result builder 'Builder' does not implement any 'buildBlock' or a combination of 'buildPartialBlock(first:)' and 'buildPartialBlock(accumulated:next:)' with sufficient availability for this call site
```

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test

**Comment by rxwei** [comment]
@swift-ci please clean test

**Comment by rxwei** [comment]
@swift-ci please test windows

**Comment by rxwei** [comment]
@swift-ci please clean test

**Review by xedin — APPROVED** [review]

**Comment by rxwei** [comment]
Oddly I haven't been able to repro any of these test failures even with a clean local build... I'm going to switch to different machine and try again.

**Comment by rxwei** [comment]
Yeah, still couldn't repro on a different machine with a clean build.  I assume it's CI hiccup. Re-triggering.

**Comment by rxwei** [comment]
@swift-ci please clean test

**Comment by rxwei** [comment]
@swift-ci please build toolchain macOS

**Comment by rxwei** [comment]
@swift-ci please test

**Pull request merged**
