### PR TITLE
[Test] Disable stdlib/StaticBigInt on macOS

### PR DESCRIPTION
**Pull request by xymus**

### CODE REVIEW

**Comment by tbkka** [comment]
@xymus Is there a link to the test failure?   Unlike #62594, this isn't obviously a test mis-configuration issue.

CC: @benrimmington @stephentyrone

**Comment by xymus** [comment]
I updated rdar://103369837 with links to failures under macosx-x86_64 and iphoneos-arm64. The disabling in this PR didn't take effect because I forgot the `x` in `macosx`.

@tbkka Do we have a fix in sight? Otherwise we may want to disable this test on 3 platforms.

**Comment by tbkka** [comment]
The test failures we're seeing internally are all manifesting similar errors:
```
stderr>>> dyld: lazy symbol binding failed: Symbol not found: _$ss12StaticBigIntV22_builtinIntegerLiteralABBI_tcfC
stderr>>>   Referenced from: .../test-iphoneos-arm64/stdlib/Output/StaticBigInt.swift.tmp/a.out
stderr>>>   Expected in: /usr/lib/swift/libswiftCore.dylib
```
It looks like the tests need to be updated to only run when testing against a suitably new libswiftCore.dylib.

**Comment by tbkka** [comment]
`UNSUPPORTED: use_os_stdlib` is what we need for that macOS failure

**Pull request merged**
