### PR TITLE
Make our LLVM level passes obey disable-llvm-optzns.

### PR DESCRIPTION
**Pull request by gottesmm**
We weren't performing the right check here... I added a test that tests both
positive/negative cases.

rdar://40097698

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by jrose-apple** [comment]
I thought -disable-llvm-optzns meant that we wouldn't even schedule the LLVM optimizer pipeline. What does it actually mean?

**Comment by gottesmm** [comment]
What it actually means is that we don't add passes to the pipeline. I was thinking the same thing TBH. I am just fixing the bug for now without rearchitecting. If you think we should rearchitect, file a bug?

**Comment by jrose-apple** [comment]
I'll leave it for now; I don't have a strong enough idea of what IRGen folks would consider the right design to suggest this one.

**Pull request merged**
