### PR TITLE
[metadata prespecialization] Mark tests unsupported on windows.

### PR DESCRIPTION
**Pull request by nate-chandler**

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please smoke test

**Comment by nate-chandler** [comment]
@swift-ci please test windows platform

**Comment by compnerd** [comment]
I think that it’s just missing COMDAT, I’ll take a look.

**Comment by compnerd** [comment]
#29150 is better than marking the tests as unsupported

**Review by compnerd — CHANGES_REQUESTED** [review]
Please dont mark tests unsupported simply because they fail

**Comment by nate-chandler** [comment]
Thank you very much, @compnerd .  The plan was to correct the tests on Windows.  Since you have already done that, closing this.

**Pull request closed without merging**
