### PR TITLE
Suggest narrowing an existing availability context, when feasible.

### PR DESCRIPTION
**Pull request by graydon**
Targeted fix for the case of a user having an existing type refinement context
(via #available or @available guard) that doesn't restrict to the version range
required by the callee: provides a specific fixit to adjust the existing guard to
match requirement, rather than suggesting introducing a new one.

rdar://problem/28815071

### CODE REVIEW

**Review by jrose-apple — APPROVED** [review]

**Comment by graydon** [comment]
@swift-ci please smoke test and merge

**Comment by slavapestov** [comment]
Nitpick: typo in PR title, "exising"

**Comment by graydon** [comment]
@swift-ci please smoke test and merge

**Comment by graydon** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
