### PR TITLE
[Doc] Fix errors in SIL.rst.

### PR DESCRIPTION
**Pull request by dan-zheng**
Fix "Title underline too short" errors:

    Warning, treated as error:
    /Users/danielzheng/swift-dev/swift/docs/SIL.rst:5604:Title underline too short.
    
    differentiable_function
    `````````````````
    make: *** [/Users/danielzheng/swift-dev/build/Xcode-ReleaseAssert+swift-DebugAssert/swift-macosx-x86_64/docs/CMakeFiles/docs_html] Error 2
    Command /bin/sh failed with exit code 2

Todo: install Sphinx on TensorFlow CI machines to catch these errors.

### CODE REVIEW

**Review by rxwei — APPROVED** [review]

**Comment by rxwei** [comment]
Feel free to merge without running CI.

**Comment by dan-zheng** [comment]
Installed [Sphinx](http://www.sphinx-doc.org/en/master/usage/installation.html) on all three CI machines to catch `.rst` errors in the future.
```
$ sudo apt-get install python3-sphinx
$ brew install sphinx-doc
```

**Comment by dan-zheng** [comment]
> Feel free to merge without running CI.

I don't plan to land other patches soon so I'll start CI.

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by burmako** [comment]
Looks like another legitimate error, also in an .rst file:

```
Warning, treated as error:
/Users/swiftci/jenkins/workspace/swift-PR-TensorFlow-macOS/swift/docs/ARCOptimization.rst:100:Pygments lexer name 'sil' is not known
```

**Comment by dan-zheng** [comment]
macOS CI now fails with:
```
Warning, treated as error:
/Users/swiftci/jenkins/workspace/swift-PR-TensorFlow-macOS/swift/docs/ARCOptimization.rst:100:Pygments lexer name 'sil' is not known
```

Investigating briefly, it seems others have ran into it [here](https://forums.swift.org/t/python-3-support-for-building-swift-toolchain/27020/8). If it's not easily fixable, I'll uninstall `sphinx` from the macOS CI machine.

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow macOS

**Comment by dan-zheng** [comment]
macOS CI fails with a super weird error:
```
/Users/swiftci/jenkins/workspace/swift-PR-TensorFlow-macOS/swift/test/AutoDiff/differentiable_function_silgen.swift:35:15: error: CHECK-AST: expected string not found in input
// CHECK-AST: (function_conversion_expr implicit type='@differentiable (Float) -> (Float)'
              ^
<stdin>:69:110: note: scanning from here
 (func_decl range=[SOURCE_DIR/test/AutoDiff/differentiable_function_silgen.swift:23:1 - line:25:1] "apply()" interface type='() -> ()' access=internal
                                                                                                             ^
<stdin>:79:2: note: possible intended match here
 (differentiable_function implicit type='@differentiable (Float) -> Float' location=SOURCE_DIR/test/AutoDiff/differentiable_function_silgen.swift:24:18 range=[SOURCE_DIR/test/AutoDiff/differentiable_function_silgen.swift:24:18 - line:24:18]
 ^
```

I ssh'd into the macOS CI machine and found that the `RUN` line produces the following `-dump-ast` output:
```
(function_conversion_expr implicit type
='@differentiable (Float) -> (Float)'
```

Note the newline after `(function_conversion_expr implicit type`: it is what causes the FileCheck error. I believe it is fixed in https://github.com/apple/swift/pull/27476/commits/83972262aabbd2f88e2f2f70c711e7c076cd141d, verified on the macOS CI machine. The error probably leaked through because macOS CI was down for https://github.com/apple/swift/pull/27471.

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Pull request merged**
