### PR TITLE
Add a new tool called SILLLVMGen that performs IRGen on a sil or sib file without adding any additional complexity.

### PR DESCRIPTION
**Pull request by gottesmm**
Add a new tool called SILLLVMGen that performs IRGen on a sil or sib file without adding any additional complexity.

I am going to use this in bug reducer for debugging runtime crashes. I just
found the branch and cleaned it up, so I fugred I would commit it sooner rather
than after I lost the branch again.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci Please smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci Please smoke test and merge

**Comment by jrose-apple** [comment]
I'm concerned about having a tool that basically just does what `swift -frontend` does. Can we discuss this before you start using it?

**Comment by gottesmm** [comment]
@jrose-apple That was my plan. Lets talk on Monday. I have an idea for unifying all of these disparate tools.

**Pull request merged**
