### PR TITLE
[MoveOnlyAddressChecker] Fix representation for consumed fields.

### PR DESCRIPTION
**Pull request by nate-chandler**
An instruction can consume multiple (discontiguous) fields.  Use a `SmallBitVector` to track the fields consumed by an instruction rather than a `TypeTreeLeafRange`.

rdar://125103951

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test linux platform

**Review by jckarter — APPROVED** [review]

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test linux platform

**Comment by nate-chandler** [comment]
@swift-ci please test linux platform

**Comment by nate-chandler** [comment]
@swift-ci please test linux platform

**Pull request merged**
