### PR TITLE
[stdlib] Update documentation of integer types

### PR DESCRIPTION
**Pull request by benrimmington**
* Remove documentation comments which can be inherited.
* Remove internal comments which are obsolete or unused.
* Move non-inherited documentation to BinaryInteger overrides.

### CODE REVIEW

**Comment by benrimmington** [comment]
@swift-ci Please smoke test

**Comment by benrimmington** [comment]
@swift-ci Please smoke test

**Comment by natecook1000** [comment]
@benrimmington Thanks for this cleanup! Looks good to me.

@amartini51 Do we have a way of validating that this doesn't lose documentation on the endpoint symbols before actually merging and waiting for the docs to get updated?

**Comment by natecook1000** [comment]
Merging! I'll follow up to verify that the docs are still attached.

**Pull request merged**
