### PR TITLE
[CodeCompletion] '#file', '#line', et al. after '#'

### PR DESCRIPTION
**Pull request by rintaro**
* Implement completion for `#file`, `#line`, et al. after `#` in expression context
* Polymorphic type annotation for `#file`, `#line`, et al. depending on context types
* Suggest `#selector` and `#keyPath` only if the context type matches
* Add `CompletionLookup::CurrModule` instance field to avoid recurring computation for `CurrDeclContext->getParentModule()`

rdar://problem/47169238

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Review by benlangmuir — APPROVED** [review]
> Suggest #selector and #keyPath only if the context type matches

I see from the test changes that it wasn't working before, but to clarify: this was always what it was supposed to do, right?

Change looks great! Happy to see us getting the types right now.

**Comment by rintaro** [comment]
>  this was always what it was supposed to do, right?

After `#` we used to unconditionally emit them.

**Pull request merged**
