### PR TITLE
[Build System: CMake] Install the layouts-*.yaml files in the compiler component (5.1 branch).

### PR DESCRIPTION
**Pull request by Rostepher**
Copy of #23898 for the 5.1 branch.

### CODE REVIEW

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by Rostepher** [comment]
@swift-ci please test Linux

**Comment by Rostepher** [comment]
@swift-ci please test Linux

**Review by shahmishal — APPROVED** [review]

**Comment by Rostepher** [comment]
@swift-ci please test Linux

**Pull request merged**
