### PR TITLE
Introduce and use SWIFT_TRAILING_OBJECTS_OVERLOAD_TOKEN to simplify MSVC hacks

### PR DESCRIPTION
**Pull request by hughbe**

### CODE REVIEW

**Comment by hughbe** [comment]
@swift-ci please test

**Comment by hughbe** [comment]
Triggered wrong tests, sorry

**Comment by jrose-apple** [comment]
Nitpick: Can you specifically name it SWIFT_TRAILING_OBJECTS_OVERLOAD_TOKEN? There's no "generic" involved.

**Comment by hughbe** [comment]
Generic as in "typename template". Since there's confusion though, would be worth renaming

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by hughbe** [comment]
Updated, let me know what you think

**Review by jrose-apple — APPROVED** [review]
LGTM. Feel free to merge after it passes tests. :-)

**Pull request merged**
