### PR TITLE
[NFC] AssociatedTypeInference: Improve dumping of an inference solution

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
It was a challenge to read through those value witnesses previously.

Before: 
```
Type Witnesses:
  A := Int value 0
  B := Bool value 1
Value Witnesses:
0:  0x7f8e2a0c8ea8 foo
0x7f8e2a0c84d0 Module name=test
  0x7f8e2a0c86d0 FileUnit file="/Users/anthonylatsis/Desktop/test.swift"
    0x7f8e2a0c8b10 ProtocolDecl name=P
    for 0x7f8e2a0d26d0 foo
0x7f8e2a0c84d0 Module name=test
  0x7f8e2a0c86d0 FileUnit file="/Users/anthonylatsis/Desktop/test.swift"
    0x7f8e2a0d24a0 StructDecl name=Foo
1:  0x7f8e2a0d2020 bar
0x7f8e2a0c84d0 Module name=test
  0x7f8e2a0c86d0 FileUnit file="/Users/anthonylatsis/Desktop/test.swift"
    0x7f8e2a0c8b10 ProtocolDecl name=P
    for 0x7f8e2a0d2a38 bar
0x7f8e2a0c84d0 Module name=test
  0x7f8e2a0c86d0 FileUnit file="/Users/anthonylatsis/Desktop/test.swift"
    0x7f8e2a0d24a0 StructDecl name=Foo
```

After:
```
Type Witnesses:
  B := Bool value 1
  A := Int value 0
Value Witnesses:
0:
  test.(file).P.foo(arg:)@/Users/anthonylatsis/Desktop/test.swift:12:8 ->
  test.(file).Foo.foo(arg:)@/Users/anthonylatsis/Desktop/test.swift:20:8
1:
  test.(file).P.bar(arg:arg2:)@/Users/anthonylatsis/Desktop/test.swift:13:8 ->
  test.(file).Foo.bar(arg:arg2:)@/Users/anthonylatsis/Desktop/test.swift:21:8
```

### CODE REVIEW

**Comment by CodaFi** [comment]
While you're here, could you amend `dumpRef` to print a newline? It's a pet peeve of mine that it doesn't do that.

**Review by slavapestov — APPROVED** [review]

**Comment by AnthonyLatsis** [comment]
@CodaFi The call hierarchy is telling me that a fair amount of callers don't want a newline, and some others only want it because the ref ends the line..

**Comment by CodaFi** [comment]
Naturally. Alright, we can clean this up later then.

⛵

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by AnthonyLatsis** [comment]
Sorry to interrupt the tests. I went and made the `value №` part of a type witness row comprehensive as well. Here's an example:
```swift
protocol P {
  associatedtype A
  associatedtype B
  associatedtype C
  associatedtype D = String

  func bar(a: A)
  func foo(b: B, c: C)
}
extension P {
  func bar(a: Self) {}
}
struct Foo: P {
  func foo(b: Bool, c: Never) {}
}
```
```
Type Witnesses:
  D := String, abstract
  A := Foo, inferred from $0
  B := Bool, inferred from $1
  C := Never, inferred from $1
Value Witnesses:
$0:
  test.(file).P.bar(a:)@/Users/anthonylatsis/Desktop/test.swift:26:8 ->
  test.(file).P extension.bar(a:)@/Users/anthonylatsis/Desktop/test.swift:30:8
$1:
  test.(file).P.foo(b:c:)@/Users/anthonylatsis/Desktop/test.swift:27:8 ->
  test.(file).Foo.foo(b:c:)@/Users/anthonylatsis/Desktop/test.swift:33:8
```

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Pull request merged**
