### PR TITLE
[InterfaceGen] Print @discardableResult in generated interfaces

### PR DESCRIPTION
**Pull request by bnbarham**
Resolves rdar://58805969.

### CODE REVIEW

**Comment by bnbarham** [comment]
As far as I can tell this was explicitly excluded since the very initial commit before it was fully implemented. I'm *assuming* it was meant to be temporary?

**Comment by bnbarham** [comment]
@swift-ci please test

**Review by rintaro — APPROVED** [review]

**Comment by bnbarham** [comment]
@swift-ci please smoke test

**Comment by bnbarham** [comment]
@swift-ci please test

**Pull request merged**
