### PR TITLE
[Sema] -serialize-diagnostics-path should imply -diagnostics-editor-mode so that live issues and editor builds can have the consistent behavior.

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Review by jrose-apple — COMMENTED** [review]
Please revert this. IDEs aren't necessarily the only consumers of serialized diagnostics.

**Comment by jrose-apple** [comment]
Xi and Argyrios came to talk to me about this in person, and the conclusion was that we'd rename "editor mode" to something that more directly talked about how diagnostics would be consumed.

**Pull request merged**
