### PR TITLE
Replace deprecated Python unit test method usage

### PR DESCRIPTION
**Pull request by gwynne**
Python 2.7's `unittest` module deprecated the `assertEquals()` method, preferring the name `assertEqual()`. Replace all outdated uses with the recommended usage.

### CODE REVIEW

**Comment by gwynne** [comment]
@swift-ci please test

**Comment by gwynne** [comment]
@swift-ci please test

**Comment by gwynne** [comment]
@swift-ci please test

**Review by gottesmm — APPROVED** [review]
I verified on python.org that what @gwynne said was correct. See:

https://docs.python.org/2/library/unittest.html#deprecated-aliases

This LGTM.

**Comment by gottesmm** [comment]
@gwynne is there a way that we can put something into python lint or the like to ensure that this never re-enters the code-base?

**Comment by gwynne** [comment]
@gottesmm I caught it because `python_lint.py` caught it when run with Python 3 - once I get some of those changes in we'll catch it that way.

**Pull request merged**
