### PR TITLE
Replace std::transform with llvm::transform

### PR DESCRIPTION
**Pull request by cypherean**
Replace uses of std::transform with llvm::transform where applicable to simplify the code.

Resolves SR-14138.

### CODE REVIEW

**Comment by cypherean** [comment]
@swift-ci please test

**Comment by varungandhi-apple** [comment]
Thanks for the PR. I think it looks good; I'm not sure if you ran `clang-format` or not... some of the formatting seems a bit odd. 😅 In case you missed it, we have instructions on how to run clang-format [here](https://github.com/apple/swift/blob/main/docs/HowToGuides/FAQ.md#how-do-i-format-my-changes). 

New contributors can't kick off PR testing or merge changes onto the `main` branch, because we previously had some malicious folks come in and kick off CI on lots of PRs, leading to .

@swift-ci please smoke test

**Comment by varungandhi-apple** [comment]
@swift-ci smoke test Linux

**Comment by varungandhi-apple** [comment]
@swift-ci smoke test macOS

**Comment by cypherean** [comment]
Okay, thanks for letting me know about the tests.

Yes, I did run `clang-format`. And the tests have passed as well. Please let me know if any changes are required.

**Review by varungandhi-apple — APPROVED** [review]

**Comment by varungandhi-apple** [comment]
LGTM, we can merge this. :shipit:

**Pull request merged**
