### PR TITLE
[4.0] A couple of cast optimizer bug fixes

### PR DESCRIPTION
**Pull request by swiftix**
Description: Cast optimizer would miscompute code in some cases or crash the compiler
Scope of the issue: Minor bug fix.
Origination: SR-4420 and SR-4450
Risk: Low, this is a small bugfix. It mostly reduces the scope of the optimization.
Tested: New test cases added.
Reviewed by: Arnold Schwaighofer
Resolves: rdar://32124747 (SR-4420) and rdar://31372306 (SR-4450)

### CODE REVIEW

**Comment by swiftix** [comment]
@aschwaighofer Arnold, could you please review for CCC?

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by aschwaighofer** [comment]
LGTM

**Comment by swiftix** [comment]
Approved by Ted

**Pull request merged**
