### PR TITLE
Inline ascii grapheme fastpaths

### PR DESCRIPTION
**Pull request by dabrahams**
/cc @milseman

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please benchmark

**Comment by airspeedswift** [comment]
The only benchmark regression here that might not be noise is Calculator? Other than that, seems like a clear win.

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by dabrahams** [comment]
I made a mistake that changed the meaning of the code slightly, thus the failures.  A little more care could reproduce the performance win without breaking tests.  See also #9798 which is similar.

**Comment by dabrahams** [comment]
@swift-ci Please benchmark

**Comment by dabrahams** [comment]
@swift-ci Please test

**Comment by dabrahams** [comment]
Superseded by #9798, which can be modified to do only the ASCII part or otherwise optimized

**Pull request closed without merging**
