### PR TITLE
[TypeChecker] Fix a problem with rethrows classification.

### PR DESCRIPTION
**Pull request by rudkx**
We failed to properly classify arguments that are of optional function
type, in this case leading to a verification failure due to the throws
attribute on the apply expression not being set to some value.
    
Fixes: SR-9102 / rdar://problem/45615204

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Review by rjmccall — APPROVED** [review]
Seems reasonable.  The constraint-system part is just to get an easier-to-analyze pattern?

**Comment by rudkx** [comment]
@rjmccall It's to avoid inferring throwing-function types for nil-literal operands. In `decl/func/rethrows.swift` there are a couple tests where we start emitting diagnostics about missing `try` without that change. I suppose it could be pattern-matched as a special-case in the error type checking code as well.

**Review by xedin — APPROVED** [review]
LGTM!

**Pull request merged**
