### PR TITLE
Removed && !defined(__ANDROID__)

### PR DESCRIPTION
**Pull request by amraboelela**

### CODE REVIEW

**Comment by milseman** [comment]
@amraboelela could you give an explanation in the commit message? That way when inspecting git blame in the future, it's more understandable.

**Comment by amraboelela** [comment]
Do I need to create a new PR?
And what should I say in the commit message?

**Comment by amraboelela** [comment]
How about now? :)

**Comment by CodaFi** [comment]
You can squash these (I recommend `git rebase -i`) down into one patch, then use `git commit --amend` to rewrite the commit message with the more informative message instead of adding empty commits

**Comment by milseman** [comment]
I can squash on merge as well

**Pull request closed without merging**
