### PR TITLE
dummy commit

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test compiler performance

**Comment by slavapestov** [comment]
The compiler perf tests were failing with my changes. I thought I reduced a test case but it requires asserts and it wasn't the same problem. Trying with a dummy commit to see if I haven't totally lost the plot.

@graydon It would be great if the build log for the compiler perf test would actually have the failing output when a project fails to build!

**Comment by slavapestov** [comment]
Ok so it's failing on master too:

```
  FAIL: vapor, 3.0, Swift Package, ExecuteCommandFailure(command="sandbox-exec -f /Users/buildnode/jenkins/workspace-private/swift-PR-compiler-performance-macOS/swift-source-compat-suite-sandbox/sandbox_package.sb /Users/buildnode/jenkins/workspace-private/swift-PR-compiler-performance-macOS/master/new/build/compat_macos/install/toolchain/usr/bin/swift build --disable-sandbox -C /Users/buildnode/jenkins/workspace-private/swift-PR-compiler-performance-macOS/project_cache/vapor --verbose --configuration debug -Xswiftc -stats-output-dir -Xswiftc ''"'"'/Users/buildnode/jenkins/workspace/swift-PR-compiler-performance-macOS/swift-source-compat-suite/stats-new-full-master-debug'"'"''", returncode=1)
```

Maybe it is https://bugs.swift.org/browse/SR-6200 after all, but it would be nice to see the actual build failure in the log.

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
https://github.com/apple/swift-source-compat-suite/pull/94
@swift-ci Please test compiler performance

**Comment by najacque** [comment]
borrowing this PR to test some infrastructure -- ignore subsequent comments.

**Comment by najacque** [comment]
@swift-ci please nominate

**Comment by najacque** [comment]
This pull request has been nominated for inclusion to master

**Pull request closed without merging**
