### PR TITLE
IRGen: disable class fast casting on Windows

### PR DESCRIPTION
**Pull request by eeckstein**
It causes some problems on CI.

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Review by compnerd — COMMENTED** [review]
Can you please link the radar that tracks this?  I don't want this to slip through the cracks

**Comment by compnerd** [comment]
Thinking a bit more, would it make more sense to make this Darwin vs non-Darwin?  That way we can have some sort of comparison point between platforms.  I know that @shahmishal has been pushing for more homogenous builds.

**Review by compnerd — CHANGES_REQUESTED** [review]
Actually, this disables it on the Windows host - we should disable this by target configuration and for !Apple targets.

**Comment by eeckstein** [comment]
@compnerd you are right, it needs to be checked for the target. I changed that and added a link to the Jira.
I don't want to disable it for Linux, though, because linux tests didn't show any problem.

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by compnerd** [comment]
I think that this really does deserve a radar - Windows is a supported platform and disabling optimizations without any plans to re-enable them is not going to help Swift scale up.  Could you also please include any notes from your investigation on the failure?

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain Windows platform

**Comment by atrick** [comment]
I added investigation notes to the SR: https://bugs.swift.org/browse/SR-16112

**Comment by compnerd** [comment]
If it is reasonable, I think that #42286 might be preferable - it keeps the optimization enabled.

**Pull request closed without merging**
