### PR TITLE
Fix regression with lazy properties and add another test case [4.0]

### PR DESCRIPTION
**Pull request by slavapestov**
* Description: When type checking an expression without applying the solution, we would set the types of anonymous closure parameters to ErrorType. This resulted in SILGen crashes because of un-typechecked AST when a lazy property was initialized by an expression containing a closure with anonymous parameters.

* Origination: Regression from another set of fixes to 'lazy' in 4.0.

* Tested: New test added. Also add another test for an odd behavior with 'lazy' that worked in 3.1 but we don't want to allow anymore. This second part is not really necessary for 4.0 branch, but it's just a new test.

* Reviewed by: Pavel Yaskevich (first two patches), Mark Lacey (ASan fix)

* Radar: <rdar://problem/33219081>

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Review by xedin — APPROVED** [review]
LGTM!

**Comment by slavapestov** [comment]
This is failing in ASan unfortunately. I'll have a corrected version soon.

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Review by xedin — APPROVED** [review]
LGTM!

**Pull request merged**
