### PR TITLE
SIL: move all the block-list modifying APIs to SILFunction.

### PR DESCRIPTION
**Pull request by eeckstein**
... and remove SILFunction::getBlocks().

It's just a cleanup, NFC.

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Review by atrick — APPROVED** [review]
Works for me

**Comment by atrick** [comment]
@eeckstein This comment is not directly related to the PR, but I'm reminded that `SILBasicBlock::getParent()` should not return `SILFunction`. It should always return a valid parent, but that parent should be some abstraction over global initializers and functions, say SILBlob. The caller should always need to explicitly check before assuming it is a SILFunction. Otherwise, we have a rare failure mode that is hard to test for. Some of SILFunction's APIs might be in that SILBlob abstraction instead so we don't need to always check for global initializers. The block list could be there as long as no one tries to add blocks.

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by eeckstein** [comment]
@atrick I'm not sure if it's worth to support getting the parent of a global initializer block. We currently don't have a need for that.
We could just rename `SILBasicBlock::getParent()` to `SILBasicBlock::getFunction()` and assert that the block is inside a function.

**Pull request merged**
