### PR TITLE
Fix for memory leak when partially applying function with @autoreleased return value

### PR DESCRIPTION
**Pull request by slavapestov**
This is a backport of the fix for rdar://problem/24805609 to Swift 2.2.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@jckarter and @jrose-apple Do you mind reviewing this?

**Comment by jrose-apple** [comment]
Your test case doesn't have any partial application in it, does it?

**Comment by slavapestov** [comment]
Unfortunately, it does. Dynamic method calls look up the method, partially apply self, wrap it in an optional, then destructure the optional :)

**Comment by slavapestov** [comment]
I guess I should cook up a SILGen test, though...

**Comment by tkremenek** [comment]
@slavapestov do you plan on incorporating a SILGen test into this pull request?

**Comment by slavapestov** [comment]
@tkremenek That sounds like a good idea. I'll cook something up now.

**Comment by slavapestov** [comment]
@swift-ci Please test

**Pull request merged**
