### PR TITLE
Prefix countRepresentedWords with underscore [NFC]

### PR DESCRIPTION
**Pull request by xwu**
An incidental issue uncovered while reading through the code for other reasons: 

Per comments, `countRepresentedWords` is slated for eventual removal along with `_word(at:)`. It's not a part of SE-0104. Therefore, let's show users that it's not intended for public consumption.

Interestingly, all current uses of the API in the Swift project itself are for implementing `_word(at:)` or calling `_word(at:)`.

### CODE REVIEW

**Comment by CodaFi** [comment]
>Interestingly, all current uses of the API in the Swift project itself are for implementing _word(at:) or calling _word(at:).

@swift-ci please test source compatibility

**Comment by moiseev** [comment]
@CodaFi These integers were only introduced in 4.0, so there should be no 3.0 code that could use it. And hence no compatibility problems =)

**Comment by moiseev** [comment]
@xwu Thanks!

**Comment by moiseev** [comment]
@swift-ci Please test and merge

**Pull request merged**
