### PR TITLE
Add a few deserialization recovery paths.

### PR DESCRIPTION
**Pull request by hjyamauchi**
This avoids cross-reference modularization error crashes in lldb/lldb-dap on Windows, seen with our internal app, reported at https://github.com/apple/swift/issues/69374.

### CODE REVIEW

**Review by xymus — APPROVED** [review]
It looks good. Thanks!

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by hjyamauchi** [comment]
If you look at [the Linux PR build history](https://ci.swift.org/job/swift-PR-Linux/), it looks like the same set of the Linux lldb tests were broken in the range from #11445-#11452 (eg., the same lldb test failures are seen in the next, but unrelated run: [#11456](https://ci.swift.org/job/swift-PR-Linux/11446/)).

Also, I wasn't able to locally reproduce the Linux lldb test failures with this change.

So rerun it. @swift-ci Please test Linux platform

**Comment by hjyamauchi** [comment]
@swift-ci Please test Linux platform

**Pull request merged**
