### PR TITLE
Allow a global-actor to be dropped for some non-async functions.

### PR DESCRIPTION
**Pull request by kavon**
It's ok to drop the global-actor qualifier `@G` from a function's type if:

- the cast is happening in a context isolated to global-actor `G`
- the function value will _not_ be `@Sendable`
- the function value is not async.

It's primarily safe to drop the attribute because we're already in the same isolation domain. So if we prevent the value from later leaving that isolation domain, it's OK to simply drop the global-actor. This means we no longer need to warn about code like this:

```
@MainActor func doIt(_ x: [Int], _ f: @MainActor (Int) -> ()) {
  x.forEach(f)
// warning: converting function value of type '@MainActor (Int) -> ()' to '(Int) throws -> Void' loses global actor 'MainActor'
}
```

resolves rdar://94462333

TODOs:
- [x] Resolve the tension between the constraint solver and TypeCheckConcurrency.
- [x] Break ties in the ranking of equivalent solutions in solver.

### CODE REVIEW

**Comment by kavon** [comment]
@swift-ci please test

**Comment by kavon** [comment]
@swift-ci please test

**Comment by kavon** [comment]
@swift-ci please test

**Comment by kavon** [comment]
@swift-ci please test

**Comment by kavon** [comment]
Turns out there's more work needed to be done to break ties in the constraint solver. Before, we could only _add_ a global-actor to a non-async function type, but now we have contexts where you can either add _or_ remove the global actor at any time. With the way I've currently implemented things, this is leading to the constraint solver finding more than 1 solution that has the same score, which yields a new ambiguity error that didn't happen before. For example:

```
@MainActor func mainActorFn() { }

@MainActor func contextualTypeHasMainActor() {
  // error: type of expression is ambiguous without more context
  let _: @MainActor () -> () = ((true ? mainActorFn : {}) : $T4)

  // in short, here's what happens for $T4, the type of the ternary expression:
  // solution 1 says $T4 := @MainActor () -> () is valid, since I can convert the `else` branch to have @MainActor.
  // solution 2 says $T4 := () -> () is valid, since I can convert the `then` branch to drop its @MainActor.
}
```

It might be easy to fix this by simply increasing the score each time one of these conversions that add or drop the main actor happens. This way, solution 1 above should get chosen, since it would have fewer conversions. Doing this naively might put extra burden on the solver, so a good default binding for type variables in constraints might help short-circuit the work (thanks Pavel).

**Review by DougGregor — APPROVED** [review]
Yeah, this looks good. I can see how it will get simpler once we sink isolation checking into the constraint solver, but this is good step forward. Thank you for the thorough testing!

**Comment by DougGregor** [comment]
@swift-ci please smoke test macOS

**Comment by kavon** [comment]
@swift-ci please smoke test and merge

**Comment by kavon** [comment]
@swift-ci please test and merge

**Pull request merged**
