### PR TITLE
Fixup IRGen Tests on AS Hosts

### PR DESCRIPTION
**Pull request by CodaFi**

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please test Apple Silicon macOS Platform

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by shahmishal** [comment]
```  502 61682 61059   0  9:28PM ??         0:00.22 /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Resources/Python.app/Contents/MacOS/Python /Users/buildnode/jenkins/workspace/swift-PR-macos-apple-silicon/branch-main/swift/utils/swift_build_sdk_interfaces.py -module-cache-path /Users/buildnode/jenkins/workspace/swift-PR-macos-apple-silicon/branch-main/buildbot_incremental/swift-macosx-arm64/swift-test-results/arm64-apple-macosx10.9/clang-module-cache -sdk /Users/buildnode/jenkins/workspace/swift-PR-macos-apple-silicon/branch-main/swift/test/ModuleInterface/swift_build_sdk_interfaces/Inputs/broken-stdlib-sdk/ -v -o /Users/buildnode/jenkins/workspace/swift-PR-macos-apple-silicon/branch-main/buildbot_incremental/swift-macosx-arm64/test-macosx-arm64/ModuleInterface/swift_build_sdk_interfaces/Output/ignore-non-stdlib-failures.test-sh.tmp/output -skip-stdlib -ignore-non-stdlib-failures
  502 61683 61059   0  9:28PM ??         0:00.12 /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Resources/Python.app/Contents/MacOS/Python /Users/buildnode/jenkins/workspace/swift-PR-macos-apple-silicon/branch-main/swift/utils/PathSanitizingFileCheck --sanitize BUILD_DIR=/Users/buildnode/jenkins/workspace/swift-PR-macos-apple-silicon/branch-main/buildbot_incremental/swift-macosx-arm64 --sanitize SOURCE_DIR=/Users/buildnode/jenkins/workspace/swift-PR-macos-apple-silicon/branch-main/swift --use-filecheck /Users/buildnode/jenkins/workspace/swift-PR-macos-apple-silicon/branch-main/buildbot_incremental/llvm-macosx-arm64/bin/FileCheck -check-prefix=CHECK-IGNORING-FAILURES /Users/buildnode/jenkins/workspace/swift-PR-macos-apple-silicon/branch-main/swift/test/ModuleInterface/swift_build_sdk_interfaces/ignore-non-stdlib-failures.test-sh
```

Test was stuck, unfortunately I was not able to run sample on it.

**Comment by CodaFi** [comment]
@swift-ci please test Apple Silicon macOS Platform

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Pull request merged**
