### PR TITLE
[runtime] RuntimeMetadata: Remove unused infrastructure

### PR DESCRIPTION
**Pull request by grynspan**
When we added compiler/runtime support for runtime attributes, we anticipated needing more runtime support than was actually needed. This PR removes the extra infrastructure.

### CODE REVIEW

**Comment by grynspan** [comment]
@swift-ci please test

**Review by xedin — APPROVED** [review]

**Review by compnerd — APPROVED** [review]
Odd, is there no field that was in the struct?  We should mark that with a comment indicating that this was removed.

**Comment by grynspan** [comment]
> Odd, is there no field that was in the struct? We should mark that with a comment indicating that this was removed.

You mean in `MetadataSections`? That field is still present. It's the one thing we _do_ need.

**Comment by grynspan** [comment]
@swift-ci please test macOS

**Comment by grynspan** [comment]
@swift-ci please test macOS

**Comment by al45tair** [comment]
Could we maybe have a reference in the comment to the PR or changeset that added this in the first place? Just for completeness?

**Review by al45tair — APPROVED** [review]
Looks fine in principle; I assume none of this is used by anything else. As I said in my other comment, it would be good to have the PR and/or changeset that added these mentioned in the log comment for this change.

**Comment by grynspan** [comment]
> Looks fine in principle; I assume none of this is used by anything else. As I said in my other comment, it would be good to have the PR and/or changeset that added these mentioned in the log comment for this change.

Ah, sorry, I hit merge before I saw this comment! Fortunately git blame should capture exactly what introduced the new code.

**Pull request merged**
