### PR TITLE
SILGen: Pass down right substitutions when getting a read-only local property.

### PR DESCRIPTION
**Pull request by jckarter**
Fixes rdar://problem/28933116.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
I feel like there have been a lot of these lately. Is there a way we can do a better job in the future?

**Comment by jckarter** [comment]
Better fuzzing?

**Comment by jrose-apple** [comment]
:-/ Is there no way to tell that we're using the wrong substitutions in any of these circumstances? Say, by adding wrapper types for different kinds of substitutions (like caller vs. callee), or including an owner pointer in debug builds?

**Comment by jckarter** [comment]
The SIL verifier catches all of these cases already; we just lacked test coverage. There are perhaps better abstractions we could use in SILGen to track things.

**Pull request merged**
