### PR TITLE
[pmo] Teach pmo to ignore debug instruction uses.

### PR DESCRIPTION
**Pull request by gottesmm**
Just noticed this while trying to figure out why a change I was trying to make
in capture promotion wasn't optimizing loads away.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
NOTE: This just causes us to promote loads, we still are very conservative at -Onone about eliminating the actual allocations. In fact, we do a check based off of the debug info attached to the allocation rather than relying on debug instructions like these. So nothing has changed beyond we will promote more loads.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
This is a pretty safe commit. Going to do post-commit.

**Comment by meg-gupta** [comment]
lgtm

**Pull request merged**
