### PR TITLE
Build swift-format as part of CI testing and install it into open source toolchains

### PR DESCRIPTION
**Pull request by ahoppen**
Build swift-format whenever SwiftSyntax is being built but don’t install it into any toolchains.

rdar://101550649

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by allevato** [comment]
@swift-ci Please smoke test macOS platform

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please build toolchain macOS

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please build toolchain macOS

**Comment by ahoppen** [comment]
@swift-ci Please build toolchain Linux

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please build toolchain

**Comment by ahoppen** [comment]
https://github.com/apple/swift-format/pull/438

@swift-ci Please build toolchain

**Comment by ahoppen** [comment]
https://github.com/apple/swift-format/pull/438

@swift-ci Please smoke test

**Comment by ahoppen** [comment]
https://github.com/apple/swift-format/pull/438

@swift-ci Please build toolchain

**Comment by ahoppen** [comment]
https://github.com/apple/swift-format/pull/438

@swift-ci Please build toolchain

**Comment by ahoppen** [comment]
https://github.com/apple/swift-format/pull/438

@swift-ci Please smoke test

**Comment by ahoppen** [comment]
apple/swift-format#438

@swift-ci Please build toolchain Windows

**Comment by ahoppen** [comment]
The Windows toolchain failure appears to be unrelated. https://github.com/apple/swift/pull/37710 failed with the same error.

**Pull request merged**
