### PR TITLE
[Dependency Scanning] Produce canonical output path for Clang PCMs.

### PR DESCRIPTION
**Pull request by artemcm**
Instead of relying on the client (driver) to perform its own computation of the matching output path.

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
https://github.com/apple/swift-driver/pull/1223
@swift-ci test

**Comment by artemcm** [comment]
https://github.com/apple/swift-driver/pull/1223
@swift-ci test

**Comment by artemcm** [comment]
https://github.com/apple/swift-driver/pull/1223
@swift-ci test

**Comment by artemcm** [comment]
https://github.com/apple/swift-driver/pull/1223
@swift-ci test

**Comment by artemcm** [comment]
https://github.com/apple/swift-driver/pull/1223
@swift-ci test

**Comment by artemcm** [comment]
https://github.com/apple/swift-driver/pull/1223
@swift-ci test

**Comment by artemcm** [comment]
https://github.com/apple/swift-driver/pull/1223
@swift-ci test

**Review by nkcsgexi — APPROVED** [review]
Make sense to me!

**Pull request merged**
