### PR TITLE
Fix build breaks for master-next against llvm.org.

### PR DESCRIPTION
**Pull request by MForster**
StringRef conversion to std::string needs to be explicit now.

### CODE REVIEW

**Comment by MForster** [comment]
@gribozavr @compnerd 

What is the right way to submit changes like this? This is needed to fix a build breakage of `master-next`, but the changes apply to `master` as well. I'm submitting this pull request to `master`, in expectation that the changes will be automerged into `master-next`. 

Is that appropriate?

**Comment by MForster** [comment]
There is one failing test, which is already broken at head as well:

```
Failing Tests (1):
    Swift(linux-x86_64) :: Incremental/fail/main.swift
```

**Comment by CodaFi** [comment]
This is targeting master. Should this be against `master-next`?

**Comment by CodaFi** [comment]
For now, let's take this on master-next with the other string conversion fixes. We should cherry-pick them all to master in one go.

**Comment by MForster** [comment]
Moved to [here](https://github.com/apple/swift/pull/30234).

**Pull request closed without merging**
