### PR TITLE
[5.8] Build-script: ensure we can target armv7k with watchOS 9 SDK

### PR DESCRIPTION
**Pull request by edymtt**
Updating to match `SDKSettings.plist`

Addresses rdar://100563701

(cherry picked from commit 82262fc90d547a5b01207034ba213b1fd9ab292d)

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci please test

**Comment by edymtt** [comment]
@swift-ci please build toolchain

**Review by shahmishal — APPROVED** [review]

**Comment by edymtt** [comment]
@swift-ci please python lint

**Comment by edymtt** [comment]
@swift-ci please test

**Comment by edymtt** [comment]
@swift-ci please build toolchain

**Pull request merged**
