### PR TITLE
build: set defaults for SourceKit on Windows

### PR DESCRIPTION
**Pull request by compnerd**
SourceKit on Windows is ported and the instructions explicitly enable it
since the defaults were not set to enable it by default.  Adjust the
CMake logic to enable it by default for Windows builds as well.  This
reduces the complexity of the default build invocation for Windows.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @gwynne @akyrtzi

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Review by gwynne — APPROVED** [review]
I'm not really fond of all these various "change the defaults based on prevailing conditions" checks, but sensible defaults for the platform do make sense.

**Comment by akyrtzi** [comment]
🎉

**Comment by compnerd** [comment]
@gwynne - I think that at this point it may be reasonable to default SourceKit to enabled and if someone wishes to port to a platform where SourceKit does not yet run, then it can be disabled there specifically until it is enabled.  However, I would really rather that be a separate change - I don't feel like I have the authority to make that decision, and think that the SourceKit developers should make that call.

**Pull request merged**
