### PR TITLE
[test] Add availability to keypath test

### PR DESCRIPTION
**Pull request by Azoy**
This test fails on older OSes because this conformance doesn't exist on older OSes. Conditionally `CHECK` based on 5.8 availability.

Resolves: rdar://99933227

cc: @benpious

### CODE REVIEW

**Comment by Azoy** [comment]
@swift-ci please smoke test

**Comment by Azoy** [comment]
@swift-ci please smoke test

**Comment by Azoy** [comment]
@swift-ci please smoke test

**Comment by Azoy** [comment]
@swift-ci please smoke test macOS

**Comment by Azoy** [comment]
@swift-ci please smoke test Windows

**Comment by benpious** [comment]
I don't entirely understand why this happened. Is there a situation where these tests are run with the version of the stdlib that ships with the OS instead of the version that just got built? 

Is this something I should have known about before I put my PR up?

**Comment by lorentey** [comment]
In some CI configurations, we build the test suite with the latest toolchain but deploy & run it on older OS versions to catch potential compatibility issues. Please don't worry about breaking this -- there is no easy way to run such tests on un-merged PRs, so in practice we just monitor the (internal) CI jobs and adjust the tests when a failure happens. (Which happens almost every time we add a new test to the stdlib; it's easy to forget about these configurations. 🙈)

This particular test was a bit of a puzzle, as @Azoy had to figure out how to explain the situation to lit -- it's a bit easier to do with tests that use StdlibUnittest. (Then again, we always have the option to simply disable a test in back deployment configurations: that's easy to do and it works every time.)

**Pull request closed without merging**
