### PR TITLE
[Gardening] Remove DoubleWidth related dead code

### PR DESCRIPTION
**Pull request by palimondo**
Remove auxiliary benchmark and tests for `DoubleWidth` which was removed from stdlib and stashed into prototype in #15470. These scattered remains were just a dead code. I'm leaving a comment breadcrumb in [test/Prototypes/DoubleWidth.swift.gyb](https://github.com/apple/swift/blob/master/test/Prototypes/DoubleWidth.swift.gyb) pointing here, to assist in easy resurrection (revert these commits).

### CODE REVIEW

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
@swift-ci please test

**Comment by openloop** [comment]
This kind of stuff is important. White space is important.

**Comment by palimondo** [comment]
@eeckstein I'd like to remove the `DoubleWidthDivision` benchmark that always returns zero because the tested type was removed from `stdlib`. Please review 🙏

**Review by eeckstein — APPROVED** [review]

**Pull request merged**
