### PR TITLE
[Sema] Make public imports of private modules an error

### PR DESCRIPTION
**Pull request by xymus**
Now that library-level and its inference should be more widely available, one of the next steps is to turn the warning about public imports of private modules into an error.

rdar://83731983

### CODE REVIEW

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by xymus** [comment]
Let's wait until we sort out the known offenders before merging.

**Comment by xymus** [comment]
@swift-ci Please smoke test

cc @nkcsgexi This makes reporting public imports of private modules an error when the env var `ENABLE_PUBLIC_IMPORT_OF_PRIVATE_AS_ERROR` is set. We can add it to the list of checks to test.

**Review by nkcsgexi — APPROVED** [review]
Thanks! Makes sense to me!

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Pull request merged**
