### PR TITLE
build: use VFS overlay for Windows SDK

### PR DESCRIPTION
**Pull request by compnerd**
The Windows SDK provides headers which have incorrect cases.  The
incorrect cases are in the SDK headers as well.  On case sensitive file
systems this causes build issues due to the incorrect name.  Use the
clang VFS overlay to avoid the need for providing copies to the expected
cases.  This improves the cross-compilation on Linux to Windows.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by jrose-apple** [comment]
Please don't do this yet. It's not Swift's responsibility to generally support cross-compilation to Windows, and it's not clear to me that this is the right answer for how to implement it. The VFS is a hack.

**Comment by compnerd** [comment]
@jrose-apple oh, this isn't something that the swift compiler itself will vend, it is only for building the standard library itself.  Its not absolutely needed, but it does make the barrier to entry much lower.

**Comment by jrose-apple** [comment]
Uh, hm. The *runtime* or the *standard library?* Because everything imported by the latter also needs to be importable by all clients today.

**Comment by compnerd** [comment]
@jrose-apple, the headers are included by the runtime code, not the standard library.

**Comment by jrose-apple** [comment]
Okay. Can you limit this to building the runtime, then, rather than adding it to all `add_swift_library` invocations?

**Comment by compnerd** [comment]
@jrose-apple that sounds like a good idea, Ill do that in a follow up :-)

**Comment by jrose-apple** [comment]
Thank you!

**Pull request merged**
