### PR TITLE
AST: Remove SPI bit from AccessScope

### PR DESCRIPTION
**Pull request by slavapestov**
As far as I can tell, it wasn't actually used for anything.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Review by xymus — APPROVED** [review]
Oh right. It was left behind by a previous clean up. Thank you!

**Comment by slavapestov** [comment]
```
/private/var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/Miscellaneous_Unicode.T8n2Hl/Miscellaneous_Unicode/Tests/πשּׁµ𝄞🇺🇳🇮🇱x̱̱̱̱̱̄̄̄̄̄Tests/πשּׁµ𝄞🇺🇳🇮🇱x̱̱̱̱̱̄̄̄̄̄Tests.swift:1:8: error: module compiled with Swift 5.3.2 cannot be imported by the Swift 5.4 compiler: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/XCTest.swiftmodule/x86_64-apple-macos.swiftmodule
19:45:54 import XCTest
19:45:54        ^
```

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Pull request merged**
