### PR TITLE
build-script: basic support for building with GCC

### PR DESCRIPTION
**Pull request by MaxDesiatov**
This doesn't resolve all of the issues experienced when building the toolchain with GCC, but at least it allows the build script to start building LLVM. This is a prerequisite for building the whole toolchain on Alpine Linux with Musl.

Related to SR-4632.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
I'm not sure that this is valuable in its current state - the gcc build is horribly broken as of my last test (~2y ago).  The generated compiler (after fixing the build - which will need to happen again) miscompiles the standard library.  I would rather that we hold off on this until the other fixes are merged.

**Comment by compnerd** [comment]
CC: @etcwilde

**Comment by MaxDesiatov** [comment]
> miscompiles the standard library. I would rather that we hold off on this until the other fixes are merged.

Are you referring to the Swift standard library here? If so, that's not the configuration I'm fixing here. The goal is not to compile `swiftc` with GCC, but to compile LLVM/clang with GCC, which in turn can then compile `swiftc` on their own. Wouldn't that avoid miscompiles then?

**Comment by MaxDesiatov** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
Can you describe why `apk add clang` is insufficient for this?  Adding this new build model adds a dependency on the split swift build which has a ~10% build penalty (compared to the current system which would allow for the build-script to build with the unified swift build).  The current instructions for Ubuntu and CentOS recommend that you install the host's clang packages.  We should document the same for Alpine and recommend that you install the clang package.

**Pull request closed without merging**
