### PR TITLE
Fix-it for `var` parameter doesn't delete enough whitespace

### PR DESCRIPTION
**Pull request by maveric94**
Resolves [SR-10293](https://bugs.swift.org/browse/SR-10293).

### CODE REVIEW

**Comment by CodaFi** [comment]
Hi, thanks for the patch.  A few notes

1) We don’t usually change the diagnostic engine by teaching it about non-whitespace parts of the language.
2) Please re-run the tests.  I’m sure at least one has changed with this patch.
3) Please add an integration test from that SR.

**Comment by CodaFi** [comment]
Come to think of it, this diagnostic is from Swift 2-3 and we no longer support that made. You can probably refactor the “invalid parameter attribute” diagnostic to instead detect keywords and insert some```` quotes.

**Comment by sl** [comment]
I'm picking up work on this pull request in #24059. There's some further discussion of the issue there.

**Comment by sl** [comment]
This was resolved in #24059. Closing this for now. If there's something in here that was missed though feel free to reopen 🙂

**Pull request closed without merging**
