### PR TITLE
[ssa-updater] Modernize style before adding support for guaranteed parameters

### PR DESCRIPTION
**Pull request by gottesmm**
Specifically:

1. I made methods, variables camelCase.
2. I expanded out variable names (e.x.: bb -> block, predBB -> predBlocks, U -> wrappedUse).
3. I changed typedef -> using.
4. I changed a few c style for loops into for each loops using llvm::enumerate.

NOTE: I left the parts needed for syncing to LLVM in the old style since LLVM
needs these to exist for CRTP to work correctly for the SILSSAUpdater.

----

Just getting this off my local branch so it can percolate a little.

### CODE REVIEW

**Comment by gottesmm** [comment]
Oh I also fixed any/all instances of PHI -> Phi.

**Comment by gottesmm** [comment]
@swift-ci test

**Review by atrick — APPROVED** [review]
I'm fine with this but `bb` is generally an accepted abbreviation for basicBlock. I don't want to give that up everywhere. There are very few of these all-lower acronyms, like `ii`. They're pervasive and they directly mirror the typename so there's no possibility for confusion.

**Comment by atrick** [comment]
Thanks for fixing `PHI` -> `Phi`. It may not be important in the scheme of things but was a pet peeve of mine.

**Comment by gottesmm** [comment]
@swift-ci test windows platform

**Comment by gottesmm** [comment]
@atrick I am going to do a follow up that undoes those changes b/c I want to validate the bigger change was NFC here.

**Pull request merged**
