### PR TITLE
[Compile Time Constant Extraction] Emit fully-qualified types and more kinds of literal expressions

### PR DESCRIPTION
**Pull request by artemcm**
- Add emission of supported Arrays, Dictionaries, Tuples, Booleans, and Optionals thanks to `Expr::printConstExprValue`.
- Print fully-qualified type names
- Add `features.json` entry so that compiler clients/users know this features is supported.

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
@swift-ci test Linux platform

**Comment by artemcm** [comment]
@swift-ci test Windows platform

**Review by nkcsgexi — APPROVED** [review]

**Review by tshortli — APPROVED** [review]

**Comment by artemcm** [comment]
@swift-ci test Windows platform

**Pull request merged**
