### PR TITLE
Merge tag 'swift-DEVELOPMENT-SNAPSHOT-2019-09-16-a' into tensorflow-merge

### PR DESCRIPTION
**Pull request by dan-zheng**
Current status:
```console
$ ./swift/utils/build-script --preset=tensorflow_test
...
Failing Tests (13):
    Swift(linux-x86_64) :: AutoDiff/simd.swift
    Swift(linux-x86_64) :: AutoDiff/control_flow.swift
    Swift(linux-x86_64) :: AutoDiff/leakchecking.swift
    Swift(linux-x86_64) :: AutoDiff/class_method.swift
    Swift(linux-x86_64) :: AutoDiff/simple_math.swift
    Swift(linux-x86_64) :: AutoDiff/protocol_requirement_autodiff.swift
    Swift(linux-x86_64) :: AutoDiff/e2e_differentiable_property.swift
    Swift(linux-x86_64) :: AutoDiff/generics.swift
    Swift(linux-x86_64) :: AutoDiff/autodiff_indirect_diagnostics.swift
    Swift(linux-x86_64) :: AutoDiff/array.swift
    Swift(linux-x86_64) :: AutoDiff/anyderivative.swift
    Swift(linux-x86_64) :: AutoDiff/transposing_attr_type_checking.swift
    Swift(linux-x86_64) :: AutoDiff/control_flow_sil.swift
```

### CODE REVIEW

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Review by marcrasi — APPROVED** [review]

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Pull request merged**
