### PR TITLE
[SwiftSyntax] Add a human readable name for diagnostics to all nodes

### PR DESCRIPTION
**Pull request by ahoppen**
Companion of https://github.com/apple/swift-syntax/pull/654

### CODE REVIEW

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/654

@swift-ci Please smoke test

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/654

@swift-ci Please smoke test

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/654

@swift-ci Please smoke test

**Review by bnbarham — APPROVED** [review]

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/654

@swift-ci Please smoke test

**Pull request merged**
