### PR TITLE
Android md

### PR DESCRIPTION
**Pull request by amraboelela**
https://bugs.swift.org/browse/SR-4443

Resolves [SR-4443](https://bugs.swift.org/browse/SR-4443).

### CODE REVIEW

**Comment by CodaFi** [comment]
Please rebase instead of pulling with a merge to clear out these superfluous commits.

**Comment by milseman** [comment]
@amraboelela could you provide a commit message for the merger.

Whoever merges this, please squash with the provided commit message

**Comment by amraboelela** [comment]
commit message is: You will also need to push the icu libraries

**Comment by amraboelela** [comment]
I was able to rebase it to apple/master :)

**Review by modocache — CHANGES_REQUESTED** [review]
The documentation looks good to me, thanks @amraboelela!

To follow up on what @milseman suggested: it looks like your _commit_ has a very short message: https://github.com/apple/swift/pull/11404/commits/a0319ea1d36bbbd16544c4eb698c28e2dbb15dcb. It would be great if you could update this message to indicate what this change is about. I think something like this would be nice:

```
[docs] Update Android instructions for icu

<Insert explanation of why these new docs
are necessary here>
```

Just in case you're not sure how to update the commit message, I think the following commands in your terminal should do it:

```sh
# Enter your Swift directory:
cd /path/to/your/swift

# Make sure you're working on the branch you pushed:
git checkout android-md

# Double-check you don't have any uncommitted
# changes. You should see:
#     On branch android-md
#     nothing to commit, working tree clean
git status

# Double check the current commit message.
# You should see:
# "You will also need to push the icu libraries"
git log -1

# Update the commit message. This will bring up
# an editor where you can make changes:
git commit --amend

# Double-check your new commit message:
git log -1

# Attempt to your remote branch. I am assuming
# "origin" points to "github.com/amraboelela/swift".
# You should see "error: failed to push some refs"
git push origin android-md

# Now that you've double-checked, force push:
git push --force origin android-md
```

Let me know if you have any questions!

**Comment by modocache** [comment]
Oh I see, I could also use the new GitHub features to provide a commit message. Whoops! :)

I think "You will also need to push the icu libraries" is too short of a commit message, though. I wouldn't be surprised if there are people working in this repository who don't even know Android-related code or documentation exists! Could you provide more detail in the commit message?

**Comment by amraboelela** [comment]
Changed the commit message.

**Comment by modocache** [comment]
@swift-ci please test and merge

**Comment by modocache** [comment]
^ @milseman Hope that's what you had in mind. My knowledge of all the new GitHub pull request mechanics is a little hazy...

**Review by modocache — APPROVED** [review]
Thanks, @amraboelela! 👍

**Comment by milseman** [comment]
@swift-ci please smoke test and merge

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test and merge

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
We'll do it live!

⛵️

**Pull request merged**
