### PR TITLE
[5.0] SIMD into stdlib

### PR DESCRIPTION
**Pull request by stephentyrone**
Implements SE-0229.

Also updates simd module types in the Apple SDKs to use the new types, and updates a couple tests to work with the new types and protocols.

(cherry picked from commit fb8b9e143de12a5f07794577e7a26272de101ea1)

Resolves <rdar://problem/17045503>

### CODE REVIEW

**Comment by stephentyrone** [comment]
@apple/swift5-branch-managers This is an ABI-impacting change for the SDK, because it changes the definition of the existing types in the simd module.

**Comment by stephentyrone** [comment]
This is blocked by https://github.com/apple/swift-lldb/pull/1112.

**Comment by stephentyrone** [comment]
This will need to pick up https://github.com/apple/swift/pull/20914

**Comment by stephentyrone** [comment]
@swift-ci please test

**Review by airspeedswift — APPROVED** [review]

**Pull request merged**
