### PR TITLE
[StdLib] Refactor DictionaryKeyValueTypes test input data

### PR DESCRIPTION
**Pull request by ezephir**
Split the input file into a pure Swift and Objective-C interop files in
anticipation of refactoring tests to remove XFAILs on Linux.
## 

Tested on OS X 10.10 and Ubuntu 14.04.

### CODE REVIEW

**Comment by gparker42** [comment]
This change splits `resetLeaksOfDictionaryKeysValues()` and `expectNoLeaksOfDictionaryKeysValues()` into ObjC and non-ObjC functions. That is fine, but it also needs to add calls to the new ObjC functions to the existing tests.

**Comment by ezephir** [comment]
Thanks. I've updated the PR with those calls.

**Comment by tkremenek** [comment]
@swift-ci Please test

**Comment by gottesmm** [comment]
The linux test here failed because of a check out failure (not sure why). Rerunning the linux platform.

@swift-ci Please test Linux Platform

**Comment by dabrahams** [comment]
@ezephir Can you update the PR so it merges cleanly and we can retest it?  Thanks.

**Comment by ezephir** [comment]
@dabrahams Updated! Thanks for taking a look.

**Comment by dabrahams** [comment]
@swift-ci please test

**Comment by dabrahams** [comment]
@swift-ci Please test

**Comment by gottesmm** [comment]
Passes tests... Merging.

**Comment by gribozavr** [comment]
@dabrahams Did you review?

**Comment by gottesmm** [comment]
@gribozavr Sorry if that was premature. I can revert if/when you want me to.

**Comment by gribozavr** [comment]
I reviewed it, LGTM.

**Pull request merged**
