### PR TITLE
[ownership] Remove BranchPropagatedUser.

### PR DESCRIPTION
**Pull request by gottesmm**
The first commit is: #30197. The second commit builds on that by removing BranchPropagatedUser. I was able to do this in an Algebraic way by converting them to just be Operand *.

For more info, read the commit msg. I put info in the notes.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test asan

**Comment by gottesmm** [comment]
@swift-ci asan test

**Comment by gottesmm** [comment]
OS X full test passed before I rebased. Linux failed for something related to incremental builds. Pretty sure it isn't me. But going to do a full linux test again just in case.

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Comment by gottesmm** [comment]
@swift-ci test linux platform

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test linux platform

**Comment by gottesmm** [comment]
@swift-ci test windows platform

**Comment by gottesmm** [comment]
@swift-ci test windows platform

**Comment by gottesmm** [comment]
@swift-ci test windows platform

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by gottesmm** [comment]
Another random swiftpm test failure.

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Review by atrick — APPROVED** [review]
Absolutely thrilled to see this!

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by gottesmm** [comment]
Restarting testing due to disabled flaky test.

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by shahmishal** [comment]
@swift-ci clean test linux platform

**Pull request merged**
