### PR TITLE
Unify the capitalization across all user-visible error messages 

### PR DESCRIPTION
**Pull request by kubamracek**
Unify the capitalization across all user-visible error messages (fatal errors, assertion failures, precondition failures) produced by the runtime, standard library and the compiler.

The current state of runtime error messages is really inconsistent.  It seems that most messages start with a capital letter, so let's change all the user-visible messages to be capitalized this way.  I'm focusing on user-visible messages, so I didn't modify the cases where a preconditionFailure was used purely as an internal sanity check and would never be displayed to the user.

Here's a few "before"s:

```
fatal error: unexpectedly found nil while unwrapping an Optional value
fatal error: Can't take a suffix of negative length from a collection
fatal error: can't remove last element from an empty collection
```

And "after"s:

```
Fatal error: Unexpectedly found nil while unwrapping an Optional value
Fatal error: Can't take a suffix of negative length from a collection
Fatal error: Can't remove last element from an empty collection
```

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by milseman — APPROVED** [review]
LGTM

**Comment by milseman** [comment]
@kubamracek:
```
/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/test/DebugInfo/ErrorVar.swift:16:12: error: expected string not found in input
 // CHECK: call void @llvm.dbg.declare({{.*}}, metadata ![[ERROR:[0-9]+]], metadata ![[DEREF:[0-9]+]])
           ^
<stdin>:194:29: note: scanning from here
 call void @llvm.dbg.declare(metadata i64* %placeholder.addr, metadata !88, metadata !DIExpression()), !dbg !89
                            ^
<stdin>:234:2: note: possible intended match here
 call void @llvm.dbg.declare(metadata %swift.error** %error.addr, metadata !106, metadata !DIExpression()), !dbg !109
 ^
```

**Comment by kubamracek** [comment]
Yup, I saw the failure.  It's not relevant to this patch, and I already emailed Adrian.

**Comment by kubamracek** [comment]
@milseman Can I get also get for LGTM for 4.0 at <https://github.com/apple/swift/pull/11604>?

**Comment by kubamracek** [comment]
@swift-ci please smoke test and merge

**Comment by jrose-apple** [comment]
This deliberately diverges from the (current) style for compiler error messages. Is that something we want to do?

**Comment by kubamracek** [comment]
Since the runtime messages are used in a completely different context (compiler output vs. runtime stderr), I don't feel they need to use the same style.  The compiler warnings/errors are always prepended with a path:line:column, and followed by the content of the offending line.  A runtime error is most commonly just a plain line with "assertion failed: something" (and "something" is already using capitalization in most places).  Since it's not the compiler who prints those, but it's user's process, I don't think we should force the compiler style on the messages here.

**Comment by milseman** [comment]
@swift-ci please smoke test

**Comment by kubamracek** [comment]
@swift-ci please smoke test

**Pull request merged**
