### PR TITLE
[DO NOT MERGE] Update README

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci smoke benchmark staging

**Comment by shahmishal** [comment]
@swift-ci Please smoke test compiler performance

**Comment by shahmishal** [comment]
@swift-ci Please smoke test compiler performance

**Comment by shahmishal** [comment]
@swift-ci Please test source compatibility debug

**Comment by shahmishal** [comment]
@swift-ci Please test source compatibility debug

**Comment by shahmishal** [comment]
@swift-ci Please test source compatibility release

**Comment by shahmishal** [comment]
@swift-ci Please test source compatibility

**Comment by shahmishal** [comment]
preset=buildbot_linux_1604
@swift-ci Please test Linux with preset

**Comment by shahmishal** [comment]
preset=buildbot_linux_1604
@swift-ci please test with preset Linux

**Comment by shahmishal** [comment]
@swift-ci Please Sourcekit Stress test

**Comment by shahmishal** [comment]
@swift-ci Please Sourcekit Stress test

**Comment by shahmishal** [comment]
@swift-ci Please test Windows

**Comment by shahmishal** [comment]
https://github.com/apple/swift-source-compat-suite/pull/349

@swift-ci Please Sourcekit Stress test

**Comment by shahmishal** [comment]
@swift-ci test new Xcode

**Comment by shahmishal** [comment]
@swift-ci test new Xcode

**Comment by shahmishal** [comment]
@swift-ci test new Xcode

**Comment by rintaro** [comment]
@swift-ci Please Python lint

**Comment by shahmishal** [comment]
@swift-ci test new Xcode

**Comment by shahmishal** [comment]
https://github.com/apple/llvm-project/pull/511

@swift-ci build toolchain macOS

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by shahmishal** [comment]
@swift-ci test new Xcode

**Comment by shahmishal** [comment]
@swift-ci test new Xcode

**Comment by shahmishal** [comment]
@swift-ci test new Xcode

**Comment by shahmishal** [comment]
@swift-ci smoke test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci Please test Windows

**Comment by shahmishal** [comment]
@swift-ci smoke test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test Windows

**Comment by shahmishal** [comment]
@swift-ci benchmark Linux

**Comment by shahmishal** [comment]
@swift-ci benchmark Linux

**Comment by shahmishal** [comment]
@swift-ci benchmark Linux

**Comment by rintaro** [comment]
@swift-ci Please build toolchain

**Comment by shahmishal** [comment]
@swift-ci test2

**Comment by shahmishal** [comment]
@swift-ci test Amazon Linux 2

**Comment by rintaro** [comment]
@swift-ci Please build toolchain macOS

**Comment by rintaro** [comment]
@swift-ci Please build toolchain macOS

**Pull request closed without merging**
