### PR TITLE
Consolidated four CoreGraphics execution tests

### PR DESCRIPTION
**Pull request by gribozavr**
I don't see any reason to split the tests like this. I merged the tests into the biggest and best-organized test file.

I also removed the `REQUIRES: OS=macosx` line from the test because CoreGraphics API should be available on all platforms.

### CODE REVIEW

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by gribozavr** [comment]
@swift-ci Please test

**Review by CodaFi — APPROVED** [review]

**Comment by gribozavr** [comment]
@swift-ci Please test macOS

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by gribozavr** [comment]
@swift-ci Please test Windows

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by gribozavr** [comment]
@swift-ci Please test Windows

**Comment by govom2p** [comment]
Can you help me change to vietnames language github board because I am not familiar with this application and have language weaknesses

**Pull request merged**
