### PR TITLE
DNM: Add -Rmodule-interface-rebuild to startOnMainActor

### PR DESCRIPTION
**Pull request by etcwilde**
Add remark to see why we're rebuilding from the swiftinterface occasionally, instead of using the perfectly good swiftmodule for the stdlib.

This is starting to affect the Windows CI now. Hopefully I get lucky and can trigger the failure first try.

The other workaround is [here](https://github.com/apple/swift/pull/64587), to produce the `private.swiftinterface`. We're supposed to prefer digging things out of the swiftmodule for the stdlib though, so that fix will just mask the issue for now.

### CODE REVIEW

**Comment by etcwilde** [comment]
@swift-ci please test

**Review by compnerd — APPROVED** [review]

**Comment by etcwilde** [comment]
We can merge if I don't catch it the first time so that we get some parallel data collection action going.

**Comment by etcwilde** [comment]
@swift-ci please smoke test

**Comment by etcwilde** [comment]
Windows failure:

```
FAIL: Swift(windows-x86_64) :: Concurrency/Runtime/startOnMainActor.swift (547 of 9197)
******************** TEST 'Swift(windows-x86_64) :: Concurrency/Runtime/startOnMainActor.swift' FAILED ********************
Script:
--
: 'RUN: at line 1';   rm -rf "T:\swift\test-windows-x86_64\Concurrency\Runtime\Output\startOnMainActor.swift.tmp" && mkdir -p "T:\swift\test-windows-x86_64\Concurrency\Runtime\Output\startOnMainActor.swift.tmp"
: 'RUN: at line 2';   't:\\swift\\bin\\swiftc.exe' -target x86_64-unknown-windows-msvc  -vfsoverlay T:/swift\stdlib\windows-vfs-overlay.yaml -swift-version 4  -Xfrontend -define-availability -Xfrontend 'SwiftStdlib 9999:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999' -Xfrontend -define-availability -Xfrontend 'SwiftStdlib 5.0:macOS 10.14.4, iOS 12.2, watchOS 5.2, tvOS 12.2' -Xfrontend -define-availability -Xfrontend 'SwiftStdlib 5.1:macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0' -Xfrontend -define-availability -Xfrontend 'SwiftStdlib 5.2:macOS 10.15.4, iOS 13.4, watchOS 6.2, tvOS 13.4' -Xfrontend -define-availability -Xfrontend 'SwiftStdlib 5.3:macOS 11.0, iOS 14.0, watchOS 7.0, tvOS 14.0' -Xfrontend -define-availability -Xfrontend 'SwiftStdlib 5.4:macOS 11.3, iOS 14.5, watchOS 7.4, tvOS 14.5' -Xfrontend -define-availability -Xfrontend 'SwiftStdlib 5.5:macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0' -Xfrontend -define-availability -Xfrontend 'SwiftStdlib 5.6:macOS 12.3, iOS 15.4, watchOS 8.5, tvOS 15.4' -Xfrontend -define-availability -Xfrontend 'SwiftStdlib 5.7:macOS 13.0, iOS 16.0, watchOS 9.0, tvOS 16.0' -Xfrontend -define-availability -Xfrontend 'SwiftStdlib 5.8:macOS 13.3, iOS 16.4, watchOS 9.4, tvOS 16.4' -Xfrontend -define-availability -Xfrontend 'SwiftStdlib 5.9:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999'  -libc MD -Xfrontend -Rmodule-interface-rebuild -Xfrontend -disable-availability-checking C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\test\Concurrency\Runtime\startOnMainActor.swift -o T:\swift\test-windows-x86_64\Concurrency\Runtime\Output\startOnMainActor.swift.tmp/a.out 1>&2
: 'RUN: at line 3';   echo T:\swift\test-windows-x86_64\Concurrency\Runtime\Output\startOnMainActor.swift.tmp/a.out
: 'RUN: at line 4';     T:\swift\test-windows-x86_64\Concurrency\Runtime\Output\startOnMainActor.swift.tmp/a.out
--
Exit Code: 127

Command Output (stdout):
--
$ ":" "RUN: at line 1"
$ "rm" "-rf" "T:\swift\test-windows-x86_64\Concurrency\Runtime\Output\startOnMainActor.swift.tmp"
$ "mkdir" "-p" "T:\swift\test-windows-x86_64\Concurrency\Runtime\Output\startOnMainActor.swift.tmp"
$ ":" "RUN: at line 2"
$ "t:\\swift\\bin\\swiftc.exe" "-target" "x86_64-unknown-windows-msvc" "-vfsoverlay" "T:/swift\stdlib\windows-vfs-overlay.yaml" "-swift-version" "4" "-Xfrontend" "-define-availability" "-Xfrontend" "SwiftStdlib 9999:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999" "-Xfrontend" "-define-availability" "-Xfrontend" "SwiftStdlib 5.0:macOS 10.14.4, iOS 12.2, watchOS 5.2, tvOS 12.2" "-Xfrontend" "-define-availability" "-Xfrontend" "SwiftStdlib 5.1:macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0" "-Xfrontend" "-define-availability" "-Xfrontend" "SwiftStdlib 5.2:macOS 10.15.4, iOS 13.4, watchOS 6.2, tvOS 13.4" "-Xfrontend" "-define-availability" "-Xfrontend" "SwiftStdlib 5.3:macOS 11.0, iOS 14.0, watchOS 7.0, tvOS 14.0" "-Xfrontend" "-define-availability" "-Xfrontend" "SwiftStdlib 5.4:macOS 11.3, iOS 14.5, watchOS 7.4, tvOS 14.5" "-Xfrontend" "-define-availability" "-Xfrontend" "SwiftStdlib 5.5:macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0" "-Xfrontend" "-define-availability" "-Xfrontend" "SwiftStdlib 5.6:macOS 12.3, iOS 15.4, watchOS 8.5, tvOS 15.4" "-Xfrontend" "-define-availability" "-Xfrontend" "SwiftStdlib 5.7:macOS 13.0, iOS 16.0, watchOS 9.0, tvOS 16.0" "-Xfrontend" "-define-availability" "-Xfrontend" "SwiftStdlib 5.8:macOS 13.3, iOS 16.4, watchOS 9.4, tvOS 16.4" "-Xfrontend" "-define-availability" "-Xfrontend" "SwiftStdlib 5.9:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999" "-libc" "MD" "-Xfrontend" "-Rmodule-interface-rebuild" "-Xfrontend" "-disable-availability-checking" "C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\test\Concurrency\Runtime\startOnMainActor.swift" "-o" "T:\swift\test-windows-x86_64\Concurrency\Runtime\Output\startOnMainActor.swift.tmp/a.out"
# command stderr:
Unsupported redirect: (('>&', 1), '2')
error: command failed with exit status: 127

--
```

**Pull request closed without merging**
