### PR TITLE
[ConstraintSystem] Handle `InOut` base introduced by diagnostic re-ty…

### PR DESCRIPTION
**Pull request by xedin**
…pecheck

While trying to lookup member reference on some base type, handle
base being an `InOutType`, which could be a result of previous
sub-expression re-typechecks made by diagnostics.

Resolves: rdar://problem/45771997

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by slavapestov** [comment]
It would be good if we could record re-typechecking hacks with FIXMEs or something so we can find them all later and rip them out once we stop doing that.

**Comment by xedin** [comment]
@slavapestov Are you suggesting to mark my new comment as a FIXME?

**Comment by xedin** [comment]
Just to clarify, this situation is result of a hack only if we consider all diagnostics based on the re-typecheck a hack which it might as well be, but it's different from all other perf and what-not hacks we have in the solver.

**Review by rudkx — APPROVED** [review]
Seems reasonable as a short-term fix.

**Comment by xedin** [comment]
@slavapestov Marked changes with `FIXME(diagnostics)`

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please smoke test

**Pull request merged**
