### PR TITLE
[Parse] Don't use tok::unknown as a dummy token

### PR DESCRIPTION
**Pull request by rintaro**
Use `tok::NUM_TOKENS` instead. `tok::unknown` can easily appear in source code.

For instance `skipUntil(tok::eof)` did not work as expected, because that was
`skipUntil(tok::eof, tok::unknown)` hence does stop at error tokens such as
`0xG` (invalid hex number literal).

Revert 2abc92bbb557a7ba440fdb5b6d0f5b15edd5c80b, since that was accidental side-effect of 45118037cc84b3c8d8f594f56f9566287a7a5fba.
Forward references are not allowed at top level, actually.

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@lattner Can you review this?

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by lattner** [comment]
LGTM!  This is a great idea.

**Review by lattner — APPROVED** [review]

**Pull request merged**
