### PR TITLE
[gardening] Fix typos. Fix headers. Python cleanups.

### PR DESCRIPTION
**Pull request by practicalswift**

### CODE REVIEW

**Comment by practicalswift** [comment]
@swift-ci please smoke test and merge

**Comment by practicalswift** [comment]
@swift-ci please test and merge

**Comment by practicalswift** [comment]
@swift-ci please smoke test OS X platform

**Comment by practicalswift** [comment]
@swift-ci please test OS X platform

**Comment by practicalswift** [comment]
@swift-ci please smoke test and merge

**Comment by practicalswift** [comment]
@swift-ci please test and merge

**Comment by practicalswift** [comment]
@swift-ci please smoke test OS X platform

**Comment by practicalswift** [comment]
@swift-ci please test OS X platform

**Comment by practicalswift** [comment]
@swift-ci please smoke test and merge

**Comment by practicalswift** [comment]
@swift-ci please test and merge

**Comment by practicalswift** [comment]
@swift-ci please smoke test OS X platform

**Comment by practicalswift** [comment]
@swift-ci please test OS X platform

**Comment by practicalswift** [comment]
@swift-ci please smoke test OS X platform

**Comment by practicalswift** [comment]
@swift-ci please test OS X platform

**Comment by practicalswift** [comment]
@swift-ci please test

**Comment by practicalswift** [comment]
@swift-ci please smoke test

**Comment by practicalswift** [comment]
@swift-ci please smoke test and merge

**Comment by practicalswift** [comment]
@swift-ci please test and merge

**Comment by practicalswift** [comment]
@swift-ci please smoke test and merge

**Comment by practicalswift** [comment]
@swift-ci please test and merge

**Comment by practicalswift** [comment]
@shahmishal The buildbots are having quite some problems with this PR. Do you know the root cause? :-)

**Comment by practicalswift** [comment]
@swift-ci please smoke test and merge

**Comment by practicalswift** [comment]
@swift-ci please test and merge

**Comment by shahmishal** [comment]
@practicalswift It should be good now, I just merged https://github.com/apple/swift/pull/8614

**Comment by practicalswift** [comment]
@shahmishal Excellent! I'll try again!

**Comment by practicalswift** [comment]
@swift-ci please smoke test and merge

**Comment by practicalswift** [comment]
@swift-ci please test and merge

**Comment by practicalswift** [comment]
@swift-ci please smoke test and merge

**Comment by practicalswift** [comment]
@swift-ci please test and merge

**Comment by practicalswift** [comment]
@swift-ci please smoke test

**Comment by practicalswift** [comment]
@swift-ci please test

**Comment by practicalswift** [comment]
@shahmishal Do you have any idea about the root cause? :-)

**Comment by practicalswift** [comment]
@swift-ci please smoke test and merge

**Comment by practicalswift** [comment]
@swift-ci please test and merge

**Comment by practicalswift** [comment]
@swift-ci please smoke test and merge

**Comment by practicalswift** [comment]
@swift-ci please test and merge

**Comment by practicalswift** [comment]
@swift-ci please smoke test and merge

**Comment by practicalswift** [comment]
@swift-ci please test and merge

**Comment by practicalswift** [comment]
@swift-ci please smoke test OS X platform

**Comment by practicalswift** [comment]
@swift-ci please test OS X platform

**Comment by practicalswift** [comment]
@swift-ci please test OS X platform

**Comment by practicalswift** [comment]
@swift-ci please smoke test OS X platform

**Comment by practicalswift** [comment]
@swift-ci please smoke test and merge

**Comment by practicalswift** [comment]
@swift-ci please test and merge

**Pull request merged**
