### PR TITLE
Merge pull request #9098 from KingOfBrian/feature/SE-0169

### PR DESCRIPTION
**Pull request by ematejska**
SE-0169: Add support for shared private(cherry picked from commit 75a1dcaf28fd7450958764bdfe518719688cbb8d)

rdar://problem/31684646

### CODE REVIEW

**Comment by ematejska** [comment]
@swift-ci test

**Comment by ematejska** [comment]
@swift-ci Please Test Source Compatibility

**Comment by tkremenek** [comment]
I thought this change was only for `--swift-version 3`, but  we see `FAIL: Kickstarter-ReactiveExtensions` in the compatibility suite.

**Comment by ematejska** [comment]
@swift-ci Please Test Source Compatibility

**Comment by ematejska** [comment]
@tkremenek That's correct, it should only be in the Swift 3 mode.  I'll review the source compat results.

**Comment by ematejska** [comment]
@swift-ci Please Test Source Compatibility

**Comment by ematejska** [comment]
@tkremenek:  All the tests that failed in the source compat suite were xfailed in a followup run and the errors are unrelated.  The kickstarter issue seems to be  <rdar://problem/30788078>.   Merging now.  The other issues Xfailed are https://bugs.swift.org/browse/SR-4731, https://bugs.swift.org/browse/SR-4730, https://bugs.swift.org/browse/SR-4709, https://bugs.swift.org/browse/SR-4705, https://bugs.swift.org/browse/SR-4696

**Pull request merged**
