### PR TITLE
[embedded] Fix a compiler crash when using generic classes in -O/-Osize

### PR DESCRIPTION
**Pull request by kubamracek**
Honestly not sure if this is the right approach, please suggest any better solutions :)

The added testcase currently triggers a compiler crash, under -Osize (doesn't happen in -Onone):

```
Assertion failed: (vtable), function emitLazySpecializedClassMetadata, file GenMeta.cpp, line 5113.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
3.	While evaluating request IRGenRequest(IR Generation for module main)
4.	While emitting lazy specialized class metadata for type '_ContiguousArrayStorage<Int>'
7  swift-frontend           0x0000000107f56c90 swift::irgen::emitLazySpecializedClassMetadata(swift::irgen::IRGenModule&, swift::CanType) (.cold.4) + 0
8  swift-frontend           0x00000001031c1798 swift::irgen::emitLazySpecializedClassMetadata(swift::irgen::IRGenModule&, swift::CanType) + 656
9  swift-frontend           0x000000010314148c swift::irgen::IRGenerator::emitLazyDefinitions() + 2056
10 swift-frontend           0x000000010323bb68 swift::IRGenRequest::evaluate(swift::Evaluator&, swift::IRGenDescriptor) const + 2584
```

What happens is: A generic function in the module ends up using implementation of arrays from the stdlib. This functionality gets loaded (deserialized). MandatoryPerfOpts ends up not actually specializing any of it, because there is no non-generic anchor from which it would be used, and namely it doesn't specialize the vtable of _ContiguousArrayStorage. Then the performance pipeline, later, ends up inlining and specializing the implementation of arrays. This creates a reference to _ContiguousArrayStorage<Int> from some non-generic functions (!) because they are specialized (by the performance pipeline). IRGen ends up lowering those functions, and crashes when it cannot find a specialized vtable for _ContiguousArrayStorage<Int>.

### CODE REVIEW

**Review by eeckstein — CHANGES_REQUESTED** [review]
No, this is not the right fix.
The right fix is to disable the generic specializer in the optimizer pipeline in embedded mode. In embedded mode everything should already be specialized in the mandatory pipeline, so no generic functions should remain in the executable code paths. Generic functions should only remain for serialization and for those, specialization needs to happen on the client side.

We should add a check in the verifier that in embedded mode there is no call of a generic function inside a non-generic function.

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Review by eeckstein — APPROVED** [review]
lgtm

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Pull request merged**
