### PR TITLE
[CodeCompletion] Filter out inapplicable member from callee analysis

### PR DESCRIPTION
**Pull request by rintaro**
Similar to #23065, but this is for callee analysis (filtering out from qualified lookup result).
rdar://problem/48604807 / https://bugs.swift.org/browse/SR-9938

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Review by benlangmuir — APPROVED** [review]

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test Linux platform

**Comment by rintaro** [comment]
@swift-ci Please smoke test Linux platform

**Pull request merged**
