### PR TITLE
[5.9][CodeCompletion] Enable SwiftParser parsing for code completion 

### PR DESCRIPTION
**Pull request by rintaro**
cherry-pick #65078 into release/5.9

**Explanation**: The new `SwiftSyntax` parsing is required for macro expansion, but it was disabled for a source manager mode that has code completion token in the buffer. Because of that, any macro generated declarations weren't suggested in code completion. Enable SwiftParser parsing for code completion, but without the roundtrip/validation testing. With this change, macros are correctly expanded, and those introduced decls are correctly suggested in code completion
**Scope**: Code completion with macros
**Risk**: Low-Mid. This introduces a new thing to code completion, but it is well tested in other modes including compilation and SourceKit cursor info
**Testing**: Added a regression test case
**Issues**: rdar://107900870
**Reviewers**: Ben Barham (@bnbarham) Alex Hoppen (@ahoppen)

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by rintaro** [comment]
@swift-ci Please test Windows

**Comment by rintaro** [comment]
@swift-ci Please test Windows

**Review by airspeedswift — APPROVED** [review]

**Pull request merged**
