### PR TITLE
Use a request to compute AbstractStorageDecl::getImplInfo() 

### PR DESCRIPTION
**Pull request by slavapestov**
Previously the ImplInfo was first set by the parser, then in some cases later updated by the type checker. For example, a lazy property would start out as a stored property (`hasStored()` returns true), then after type checking it was "lowered" to a computed property (`hasStorage()` returns false).

The goal is to do the StorageImplInfo computation using a request so it is always up to date and correct, merging some code from the parser together with some code that previously ran as part of `maybeAddAccessorsToStorage()`.

This PR gets us *most* of the way there -- `maybeAddAccessorsToStorage()` still updates the StorageImplInfo for lazy properties and property wrappers.

Follow-up to https://github.com/apple/swift/pull/26235.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Review by rjmccall — APPROVED** [review]
This all looks right at a first glance, but I might need a second look. :)

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test Linux

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Pull request merged**
