### PR TITLE
Revert "Revert "build: simplify version tracking logic""

### PR DESCRIPTION
**Pull request by compnerd**
This reverts commit be37141b0fc5ad82dafbaaed2936a5a62c4de1e0.  Add a
small fix in the dereferencing.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @shahmishal

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please build macOS toolchain

**Comment by shahmishal** [comment]
@swift-ci please build toolchain macOS

**Comment by compnerd** [comment]
```
$ usr/bin/swiftc --version
Apple Swift version 5.2-dev (LLVM 312410efca, Swift 1602d65dc2)
```

**Comment by shahmishal** [comment]
Thanks!!

**Pull request merged**
