### PR TITLE
[Threading][TSan] Fix TSan errors from lazy init on Linux.

### PR DESCRIPTION
**Pull request by al45tair**
Move the TSan functionality from Concurrency into Threading. Use it in the Linux ulock implementation so that TSan knows about ulock and will tolerate the newer swift_once implementation that uses it.

This should also slightly improve the performance of Concurrency, since the tsan tests will be inlined rather than it always doing a subroutine call.

rdar://110665213

### CODE REVIEW

**Comment by al45tair** [comment]
Explanation: The Linux implementation of `swift::once` uses a custom lock implementation so that it fits into a `swift_once_t` (which is necessary because the compiler reserves space for those when generating code). TSan doesn't see the lock in question as it has no interceptor for it, so we need to tell TSan about the lock otherwise it'll generate errors for accesses made during a lazy Swift initializer.
Risk: Low. Affects TSan on Linux only.
Original PR: #66721 
Reviewed by: @yln @weissi 
Resolves: rdar://110665213
Tests: This PR adds a new test, `test/Sanitizers/tsan/once.swift`, that explicitly tests this case. Before the code changes, the test fails. After the code changes, it passes.

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Review by tomerd — APPROVED** [review]

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
