### PR TITLE
Add support for Xcode 12.3 (12C33)

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
@swift-ci test new Xcode

**Review by keith — APPROVED** [review]

**Review by Toppole69 — COMMENTED** [review]
H

**Review by Toppole69 — COMMENTED** [review]
-

**Review by Toppole69 — COMMENTED** [review]
G

**Review by Toppole69 — COMMENTED** [review]
J

**Pull request merged**
