### PR TITLE
[5.1] One-way constraints for function builders

### PR DESCRIPTION
**Pull request by DougGregor**
Cherry-pick the work to enable one-way constraints for function builders to the 5.1 branch as an experiment. Implements rdar://problem/50150793.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please test compiler performance

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test compiler performance

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test compiler performance

**Review by AnnaZaks — APPROVED** [review]

**Comment by DougGregor** [comment]
@swift-ci build toolchain

**Pull request merged**
