### PR TITLE
Add new benchmarks for UTF16 transcoding

### PR DESCRIPTION
**Pull request by Catfish-Man**
This is just the new benchmarks for https://github.com/apple/swift/pull/72205, so I can get CI to show the improvements I'm testing.

### CODE REVIEW

**Comment by Catfish-Man** [comment]
@swift-ci please Apple Silicon benchmark

**Comment by Catfish-Man** [comment]
@swift-ci please benchmark

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Review by Azoy — APPROVED** [review]

**Comment by Catfish-Man** [comment]
@swift-ci please test windows platform

**Pull request merged**
