### PR TITLE
Make sure uintptr_t bits is initialized to zero to avoid garbage value

### PR DESCRIPTION
**Pull request by practicalswift**

### CODE REVIEW

**Comment by practicalswift** [comment]
@swift-ci please smoke test

**Comment by gparker42** [comment]
This field was deliberately left without an initializer. What undefined behavior did you see?

**Comment by practicalswift** [comment]
@gparker42 Sorry, didn't catch that it was intentional (I'm really new to this code!). Is it due to performance reasons? Feel free to close this PR and sorry for adding noise :-)

The theoretical UB case I was thinking about was any call to `isNativeOrNull()` …

```c++
  bool isNativeOrNull() const {
    return bits == 0 || (bits & NativeMarkerMask) == NativeMarkerValue;
  }
```

… in the case of not calling `setNativeOrNull(…)` prior to the `isNativeOrNull()` call. My reading of the code is that `bits` could potentially be set to a garbage value in that case.

**Comment by practicalswift** [comment]
@gparker42 Friendly ping :-) Should this one be closed? I assume the field was deliberately left without an initializer for performance reasons?

**Comment by najacque** [comment]
@swift-ci please test

**Comment by practicalswift** [comment]
@swift-ci please test OS X platform

**Comment by najacque** [comment]
Btw, I'm looking into a problem with the bots.  The last test request seems to be working though.

**Comment by najacque** [comment]
Ok, now that master is fixed...
@swift-ci please test

**Comment by najacque** [comment]
More breakage on master.  Should be fixed now...  Let's try this again.
@swift-ci please test

**Comment by practicalswift** [comment]
@gparker42 Should this PR be closed? Is the non-initialization due to performance reasons?

**Comment by CodaFi** [comment]
@swift-ci please test macOS

**Pull request closed without merging**
