### PR TITLE
AST: split out diagnostics serialization

### PR DESCRIPTION
**Pull request by compnerd**
Create a new diagnostics serialization library, splitting out of
swiftAST to reduce the overheads for building the tooling for
cross-compiling the toolchain.  This should reduce the build time for
swift-serialize-diagnostics to enable cross-compilation.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by compnerd** [comment]
This converts the build targets from 2871 to 489, reducing the build time for the `swift-serialize-diagnostics` tool by 90%.

**Comment by compnerd** [comment]
CC: @xedin @HassanElDesouky

**Comment by compnerd** [comment]
@swift-ci please clean test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by compnerd** [comment]
@swift-ci please clean test Linux platform

**Comment by HassanElDesouky** [comment]
Thank you!

**Review by xedin — COMMENTED** [review]
Makes sense! A better name for this would be `swiftLocalization` and you could move files to `swift/Localization` instead because `LocalizationFormat` has both YAML and serialized localization producers and it doesn't have to be only diagnostics, anything which is localizable could be using both these classes...

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Review by xedin — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Pull request merged**
