### PR TITLE
Remove the (empty, unused) SIMDOperators module [5.1]

### PR DESCRIPTION
**Pull request by stephentyrone**
We originally planned to use this to hide some simd operators from the typechecker unless the user explicitly opted into having them but that scheme turned out to be ill-conceived, so we moved them back into the stdlib. This change simply cleans up the empty vestigial module.

### CODE REVIEW

**Comment by stephentyrone** [comment]
@swift-ci please test

**Review by Rostepher — APPROVED** [review]
LGTM! 👍

**Comment by stephentyrone** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
@stephentyrone We re-branched 5.1 from master, should we close this PR?

**Comment by stephentyrone** [comment]
Yup, no longer needed =)

**Pull request closed without merging**
