### PR TITLE
Re-enable Lazy validation test.

### PR DESCRIPTION
**Pull request by rudkx**
Works for me locally.

Resolves rdar://problem/31897334.

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test and merge

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
It's still failing on some of the Apple-internal builders. Reverting.

**Pull request merged**
