### PR TITLE
SE-0246: Protocols and static functions

### PR DESCRIPTION
**Pull request by stephentyrone**
This implements the protocols and static functions proposed in SE-0246, plus some initial test coverage. It also has some rough accompanying cleanup of tgmath. It does not include the globals (on scalars or SIMD types) nor does it deprecate much in tgmath.h.

<rdar://problem/17625344>

### CODE REVIEW

**Comment by stephentyrone** [comment]
@swift-ci please test

**Comment by stephentyrone** [comment]
@swift-ci please test source compatibility

**Comment by Coeur** [comment]
As SE-0246 gives a standard name for those functions, please deprecate for Swift 5.1 `formSquareRoot` and eventually `squareRoot`. See [the comment from Steve Canon](https://forums.swift.org/t/accepted-with-modifications-se-0246-generic-math-functions/22244/23?u=coeur):
>Even the existing method `x.formSquareRoot( )` was probably ill-considered because it doesn't offer any efficiency wins, but everyone was quite gung-ho about testing out the edges of the naming conventions at that point. It's a vestigial curiosity now that we might deprecate at some future point.

By deprecating for Swift 5.1 `formSquareRoot`/`squareRoot` in favor or `sqrt`, we would be consistent with the availability messages for M_SQRT2/M_SQRT1_2 coming from https://github.com/apple/swift/pull/23956/files.

**Comment by xwu** [comment]
I’m sure Steve is well aware of his own comment :)

Deprecation would require discussion on Swift Evolution and is not a part of SE-0246.

**Comment by Coeur** [comment]
@xwu  Oh, I didn't realize it was the same person.

**Pull request merged**
