### PR TITLE
ClangImporter: NFC: simplify `importFullName` calls

### PR DESCRIPTION
**Pull request by egorzhdan**
This is just a cleanup of `importFullName` invocations, discussed here: https://github.com/apple/swift/pull/37695#discussion_r675859664

This change makes `importFullName` return a pair of a canonical & alternative names instead of having one of them passed as a parameter.

### CODE REVIEW

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
How about we refactor `importFullName` to return a std::pair and have all the callers ignoring it pass `std::ignore` to `std::tie`?

**Comment by egorzhdan** [comment]
@CodaFi sounds good, that seems to be a cleaner solution.

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Review by CodaFi — APPROVED** [review]

**Pull request merged**
