### PR TITLE
[AutoDiff] Make activity analysis work on side effecting code.

### PR DESCRIPTION
**Pull request by rxwei**
* Make activity analysis only track values whose types are differentiable.
* Extend the original data flow analysis to propagate `VARIED` and `USEFUL` though `apply` (with indirect results), `store` and other side-effecting operations.
* When primal or adjoint synthesis fails, erase all generated functions for that differentiation task to avoid unexpected verification failures.

Note: This patch does not make differentiating through loads and stores work. That will be done in my next patch.

### CODE REVIEW

**Comment by rxwei** [comment]
This is at least gonna make the “zero derivative over nested generic call” problem become a crasher :)

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Review by dan-zheng — APPROVED** [review]

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow Linux

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Pull request merged**
