### PR TITLE
[Backtracing] Disable for the minimal preset.

### PR DESCRIPTION
**Pull request by al45tair**
Disable backtracing for the minimal preset.

rdar://106459980

### CODE REVIEW

**Comment by al45tair** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
Ah, mentioning PRs on the same repo doesn't work. That's why.

**Comment by al45tair** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by al45tair** [comment]
OK. The remaining failure is not to do with this.

**Comment by aschwaighofer** [comment]
Can we merge this?
I would like to test https://github.com/apple/swift/pull/64252 with the minimal config

**Review by kubamracek — APPROVED** [review]

**Pull request merged**
