### PR TITLE
🍒[Observation] Forward availability and defines to extensions

### PR DESCRIPTION
**Pull request by phausler**
Explanation:
Using availability markers and #if guards for observable types incorrectly emit extensions that are inherently incompatible with extensions.

This forwards the relevant availability to the extensions.

Scope:
Observation; no code-gen, or API, just macro emissions only when availability/`#if` checks are applied to `@Observable` types.

Risk:
Low

Review: @DougGregor

Resolves:
rdar://112132715

### CODE REVIEW

**Comment by phausler** [comment]
@swift-ci please test

**Comment by phausler** [comment]
@swift-ci please test

**Comment by phausler** [comment]
@swift-ci please test

**Comment by phausler** [comment]
@swift-ci please test

**Comment by phausler** [comment]
@swift-ci please test

**Comment by phausler** [comment]
@swift-ci please test

**Review by stephentyrone — APPROVED** [review]

**Pull request merged**
