### PR TITLE
Ensure that we have a valid witness to IteratorProtocol.next()

### PR DESCRIPTION
**Pull request by CodaFi**
Resolves rdar://57003406

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please smoke test and merge

**Comment by CodaFi** [comment]
Hm, seems like an infrastructure problem

@swift-ci please smoke test

**Review by slavapestov — CHANGES_REQUESTED** [review]
This needs a test case.

**Comment by CodaFi** [comment]
Reducing Alex's test is proving difficult.  I'll get it in a follow-on.

@swift-ci please smoke test

**Comment by CodaFi** [comment]
⛵️

**Pull request merged**
