### PR TITLE
[mandatory-combine] Improve basic block traversal when initializing worklist

### PR DESCRIPTION
**Pull request by gottesmm**
This PR contains two different small improvements to mandatory combine that will not change the output of the pass, but generally make the pass safer and easier to maintain. Specifically:

1. The first patch just causes mandatory combine to bail early when we see a function that is an external declaration before we do anything else. This just provides a nice invariant I use in the next patch.

2. The second patch cleans up the worklist initialization in mandatory combine. Specifically, I:
a. Simplified the data structures.
b. Changed the "visited block" set to ensure that we only add blocks once to the worklist instead of inserting the blocks into the worklist and then using the set to filter out if we had already popped the block off the worklist before. This is more efficient and simplifies the code. I changed the name of the set to fit closer to its new role: blockAlreadyAddedToWorklist.

----

[mandatory-combine] Simplify block traversal used to initialize worklist.

Previously, we were using a pointer set to ensure that was checked when a value
was popped off the worklist. In this commit, I change the code so that we
instead use the set to guard insertion into the worklist.

I changed the name of the set to blockAlreadyAddedToWorklist. Hopefully that
will make things a bit clearer.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci asan test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by nate-chandler** [comment]
Do any of these changes apply to `SILCombiner::addReachableCodeToWorklist`?

**Review by nate-chandler — APPROVED** [review]
LGTM

**Comment by gottesmm** [comment]
@nate-chandler Maybe? I would rather do that in a different PR at another time (feel free to grab that task if you want). I just saw this when I was seeing if I needed to add code to mandatory combiner to ensure that changing #27599 did not mess with codegen. Turns out I didn't need to change anything. But I found this locally so I thought I would upstream it.

**Pull request merged**
