### PR TITLE
[CSGen/CSApply] Don't expect implicit casts to have type reprs

### PR DESCRIPTION
**Pull request by xedin**
Implicit casts are allowed to be constructed with a type, instead
of a type repr. Constraint generation should honor that, and fallback
to using cast type when repr is was not given.

### CODE REVIEW

**Review by hborla — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please smoke test

**Review by ktoso — APPROVED** [review]
LGTM, thank you!

**Comment by ktoso** [comment]
Uncovered in distributed work: the same needs to be done in CSApply we think

**Comment by xedin** [comment]
@ktoso @hborla Updated PR to handle casts without reprs correctly in CSApply.

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
Also while doing this I found out that there are a lot of places in `ExprRewriter` that still use `cs.DC` which is incorrect - they should be switched to `dc`, I'm going to adjust that in a follow-up PR.

**Comment by ktoso** [comment]
Sweet, thanks -- I can confirm this solved the issues with implicit synthesized casts 👍 

// tagged distributed just so we can easily find it "related to distributed work", hope you don't mind 👍

**Comment by xedin** [comment]
Yeah, I don't mind :)

**Pull request merged**
