### PR TITLE
Add AccessedStorageAnalysis.

### PR DESCRIPTION
**Pull request by atrick**
An interprocedural analysis pass that summarizes the dynamically
enforced formal accesses within a function. These summaries will be
used by a new AccessEnforcementOpts pass to locally fold access scopes
and remove dynamic checks based on whole module analysis.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test.

**Review by eeckstein — APPROVED** [review]
lgtm!

**Comment by atrick** [comment]
Not much point in merging this until we're sure that the corresponding optimizations are ready. Since posting this PR, a couple of unrelated correctness issues have come up that I need to resolve. I'll merge this once I get back to finishing the optimizations related to this analysis.

**Comment by atrick** [comment]
@swift-ci smoke test and merge.

**Pull request merged**
