### PR TITLE
Remove warning for conflicting implementationOnly imports

### PR DESCRIPTION
**Pull request by keith**
This warning occurred in the case that you had multiple files in a
module, some that used `@_implementationOnly import Foo` and some that
used `import Foo`. The downside of having this warning is that users
cannot represent in which files `Foo` has to be imported publicly vs
which files are only using it in an implementation only capacity. The
other downside is that if users go to add a public dependency on `Foo`
to their module, they would have to change all the other
`@_implementationOnly import Foo` calls in the module to no longer have
the annotation.

Related conversation: https://forums.swift.org/t/update-on-implementation-only-imports/26996/13

### CODE REVIEW

**Comment by harlanhaskins** [comment]
I would really prefer if we left this warning in. This has caught a lot of mistakes, and removing it would lead to more mistakes where frameworks accidentally leak dependencies and their `.swiftinterface`s become unbuildable.

**Comment by keith** [comment]
Not to keep beating this drum but this is definitely a case where I could see the ability to disable specific warnings for your build as a benefit. In this case I think the UX we'd have to put developers through to substitute all the imports each time would be a pain in the case they actually need to switch from implementation only to public, but I agree if they just forgot to add the annotation this is a benefit.

**Comment by kastiglione** [comment]
> I consider the maintenance burden of removing `@_implementationOnly` import on all the import declarations as a benefit; frameworks authors should be explicit about that.

This has a inverse burden: If one day I have to remove `@_implementationOnly` from all imports of a certain module, then in the future I have no signal to indicate when that module can once again be imported implementation-only.
 
Put it another way: how can a framework author best limit its dependency leakage/pollution, if not by marking each file with the correct import type?

This warning seems to discourage those who'd like to be careful about dependencies.

**Comment by harlanhaskins** [comment]
`@_implementationOnly` does not control whether or not a given file depends on the module it's importing, though. It only really controls whether or not the entire module exposes that dependency to its clients. If _any_ file imports without `@_implementationOnly`, then the _entire_ module leaks the dependency.

**Comment by kastiglione** [comment]
> `@_implementationOnly` does not control whether or not a given file depends on the module it's importing, though. It only really controls whether or not the entire module exposes that dependency to its clients. If any file imports without @_implementationOnly, then the entire module leaks the dependency.

I just did a quick test: `@_implementationOnly` on a per file basis controls the diagnostics for that file. So, using `@_implementationOnly` in one file tells you that file is implementation-only safe. Being able to preserve this would be helpful in identifying which files in the module are the source of dependency leaks.

> it forces module authors to be careful about what dependencies their modules are leaking.

We're not in disagreement, we want module authors to be careful or aware of what they're leaking. But having one file cause all other files to fall in line, makes the job of being careful harder.

**Comment by harlanhaskins** [comment]
> So, using @_implementationOnly in one file tells you that file is implementation-only safe. 

This phrasing really makes me think you're using `@_implementationOnly` for the wrong reason. My understanding is that `@_implementationOnly` doesn't exist so that a given file gets diagnostics about whether or not it exposes public APIs that use that module, it exists so that modules don't expose their usage of another module to clients, because clients may not have that module available when _they_ are building. If a client _does_ have access to the module, then you should not be using `@_implementationOnly`.

**Comment by kastiglione** [comment]
> My understanding is that `@_implementationOnly` doesn't exist so that a given file gets diagnostics about whether or not it exposes public APIs that use that module, it exists so that modules don't expose their usage of another module to clients, because clients may not have that module available when they are building.

It may exist for the latter, but it does do both. Which seems like a good thing.
 
> If a client does have access to the module, then you should not be using `@_implementationOnly`.

During a build, the client _could_ access to the module – but we think there are benefits to hiding where possible. Specifically, we'd like to prevent extension pollution and cascading recompiles, by hiding implementation-only modules from upward (reverse) dependencies.

Consider this, with dashed lines meaning implementation-only:

graph

* B (and above) won't have the extensions of D (and below) polluted/visible
* Changing D will cause D and C to be recompiled, but not necessarily cause B and above to be recompiled

These are why we're exploring implementation-only imports.

**Comment by kastiglione** [comment]
> My understanding is that `@_implementationOnly` doesn't exist so that a given file gets diagnostics about whether or not it exposes public APIs that use that module

fwiw (for completeness) here's a gist showing two files in a module, one with a normal import and the other with an `@_implementationOnly` import of the same module.

Adding `@_implementationOnly` to the normal import in `B2.swift` will give a compiler error.

https://gist.github.com/kastiglione/b88490037f650a658a8f60af40aa9d0f

**Comment by harlanhaskins** [comment]
You're right that it _does_ exhibit this behavior, but my argument is that removing this warning to support this unintended side benefit, and introduce surface for misuse of this experimental feature for its _intended_ use case, is undesirable.

**Comment by kastiglione** [comment]
Ignoring this question of removing the warning: Do you think it's reasonable to expand its intended uses to what we've described?

**Pull request closed without merging**
