### PR TITLE
Builtin.rebindMemory

### PR DESCRIPTION
**Pull request by atrick**
Add Builtin.rebindMemory.

Required for UnsafeRawPointer.withMemoryReboud(to:).

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci test

**Review by glessard — APPROVED** [review]
LGTM. Looks like this builtin will work perfectly for the `withMemoryRebound` improvements.

**Comment by atrick** [comment]
@swift-ci test

**Review by glessard — APPROVED** [review]

**Pull request merged**
