### PR TITLE
[cast-optimizer] Extract out the isConditional code path of the optim…

### PR DESCRIPTION
**Pull request by gottesmm**
…ize bridge functions into helper functions.

This doesn't actually change any code since the helper functions in this commit
have the exact same body except isCondition is set to true. I am going to
"constant propagate" this value in subsequent commits.

NFC.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by atrick** [comment]
I generally like the bottom up refactoring approach much better, but this is just a code dup patch, so I'll just have to trust that the code will be simpler after you do this...

**Comment by gottesmm** [comment]
Ok. Let me do a bit more of the work in this PR so it becomes more apparent where this is going. I am trying to do the minima work to clean up the control flow.

**Comment by gottesmm** [comment]
I am doing this in a better, different way.

**Pull request closed without merging**
