### PR TITLE
[Sema] Suppress deprecation warnings in synthesized code

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
Resolves [SR-8634](https://bugs.swift.org/browse/SR-8634).

### CODE REVIEW

**Comment by jrose-apple** [comment]
@CodaFi has brought this up before and I'm not sure it's correct. We want to know in general if the compiler is synthesizing incorrect code.

**Comment by AnthonyLatsis** [comment]
@jrose-apple Right, the solution is not to synthesize at all if something is unavailable, and synthesize with possible corrections if something is deprecated. But if there aren't any deprecation corrections passed with @available we can rely on, we have to either refrain from synthesizing or suppress the upcoming warning in `TypeCheckAvailability`.

For example, should we synthesize `rawValue` here? Because it's a warning we're talking about, I think we should. Besides, we'd be leaving `.b` and `.c` out if we don't.
``` swift
enum Foo: Int {
  @available(*, deprecated)
  case a
  case b
  case c
}
```

**Comment by AnthonyLatsis** [comment]
I just found out this doesn't compile:
``` swift
enum Foo: Int {
  @available(*, unavailable)
  case a
  case b
  case c
}
```
I'm not sure what `Foo.b.rawValue` should be equal to, 0 or 1?

**Comment by jrose-apple** [comment]
Oh, I agree we need to synthesize `rawValue` to handle `a` (and `init(rawValue:)`), and I agree that it shouldn't warn, and I know we don't have an equivalent of GCC's `__extension__` to silence the warning locally…but I *don't* know if we want to silence this for all synthesized declarations ahead of time. It seems too easy for us to miss something, like if we inherited initializers by synthesizing `super.init` calls and forgot to mark the inherited initializer as `deprecated`.

One possibility would be to come up with a compiler-only attribute to silence deprecation warnings, just like. We can put that on synthesized declarations that we *know* can reference deprecated members without themselves being deprecated.

Maybe I'm just being oversensitive, though.

* * *

I don't know what to do about the `unavailable` case. I'd suggest that it still claims a number, since that's most compatible with "I had an existing enum and I added `unavailable` to one case". That might be worth addressing in a separate PR, though, and probably then a second SR too.

**Comment by AnthonyLatsis** [comment]
> but I don't know if we want to silence this for all synthesized declarations ahead of time. It seems too easy for us to miss something, like if we inherited initializers by synthesizing super.init calls and forgot to mark the inherited initializer as deprecated.

I don't really understand how an emitted warning will help here, or why synthesized declarations that are themselves deprecated for some reason would cause a problem if the warning isn't emitted. Could you elaborate some more? We definitely don't want it to be emitted in synthesized code in the first place, right?

**Comment by jrose-apple** [comment]
Here's the example:

```swift
class Base {
  init(good: Int) { }
  @available(*, deprecated) init(bad: Int) { }
}

class Sub: Base {
  // initializers inherited
}

Sub(bad: 0) // should warn
```

If the compiler implemented this by synthesizing this declaration in Sub:

```swift
  init(bad: Int) {
    super.init(bad: bad)
  }
```

then we'd get a warning today telling us that that `super.init` call was wrong. The correct fix in this case would be to make sure the synthesized declaration was also marked deprecated:

```swift
  @available(*, deprecated)
  init(bad: Int) {
    super.init(bad: bad)
  }
```

Silencing the warning in all synthesized code would make it less likely that we'd notice this issue; we'd have to wait for a bug report from outside with the original test case.

I'm not sure if this is *sufficient* justification to look for a different answer, but it is why I'm worried.

**Comment by AnthonyLatsis** [comment]
Now I get your point, thanks. Inheritance is probably the only case when we preserve availability, if I'm not mistaken.. I feel like ensuring we have a test for that is a better option than adding a new internal attribute. In both cases it all boils down to having an appropriate test, so there's only a subtle difference in safety.

**Comment by AnthonyLatsis** [comment]
I agree that the presence of an unexpected warning is more likely to be noticed. Let's add a test for `Sub(bad: 0) // should warn` if it survives the bots, I haven't found one. I'm not familiar with what's going on in the Clang Importer, but if there's anything concerning you, I can look for certain tests.

**Comment by jrose-apple** [comment]
It's good to add the test, but note that in this case it's not actually related, since we *don't* synthesize bodies for inherited initializers in Sema. (We take care of it in SILGen.)

@swift-ci Please smoke test

**Comment by zx2c4** [comment]
@jrose-apple Any plans to backport this to Swift 4.2.x?

**Comment by jrose-apple** [comment]
We generally don't backport fixes to earlier releases if they're not being released for all platforms (especially when there are already beta releases for 5.0), but if this is important to you for Linux you could cherry-pick it and open a PR per the [4.2.x process forum post](https://forums.swift.org/t/announcing-swift-4-2-2-and-monthly-swift-4-2-x-dot-releases-for-linux/20148).

**Comment by zx2c4** [comment]
> if this is important to you for Linux

Actually, no -- I'm writing an iOS/macOS app that uses the LAError enum and was hoping those warnings would go away in Xcode.

**Comment by jrose-apple** [comment]
Ah, then you'll have to wait for Xcode 10.2 to GM.

**Pull request merged**
