### PR TITLE
Revert "Revert "swift-lang: shuffle the source directory structure (N…

### PR DESCRIPTION
**Pull request by compnerd**
…FC)""

This reverts commit beb8ecd8cc38c2626ec82aca3f62dabf28752be7.  Add a
workaround for the dependency issue.

It is unclear why `sourcekitd` is getting added improperly as a
dependency on `lib/sourcekitd.framework/sourcekitd`.  This workaround
adjusts the dependency such that we end up with a dependency on
`lib/sourcekitd.framework/Versions/A/sourcekitd` as an order-only
dependency.  This should fix the compile issue.  I am unable to
reproduce this issue with the `add_library` usage for adding a Swift
library.  This allows us to cleave the host and target libraries, and so
the workaround is sufficient to make progress and the problem will be
resolved with the migration towards CMake for handling the dependencies.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @drexin @benlangmuir

**Comment by compnerd** [comment]
@swift-ci please clean test macOS platform

**Comment by compnerd** [comment]
@swift-ci please clean test macOS platform

**Comment by compnerd** [comment]
@swift-ci please clean test macOS platform

**Comment by compnerd** [comment]
@swift-ci please clean test macOS platform

**Comment by compnerd** [comment]
@swift-ci please clean test macOS platform

**Comment by compnerd** [comment]
```
$ ../ninja-build/ninja -t query stdlib/tools/swift-lang/OSX/x86_64/SwiftLang.o
stdlib/tools/swift-lang/OSX/x86_64/SwiftLang.o:
  input: CUSTOM_COMMAND
    bin/swift
    stdlib/tools/swift-lang/YGUk1.txt
    /Users/abdulras/SourceCache/swift/swift/stdlib/tools/swift-lang/SwiftLang.swift
    /Users/abdulras/SourceCache/swift/swift/stdlib/tools/swift-lang/SourceKitdClient.swift
    /Users/abdulras/SourceCache/swift/swift/stdlib/tools/swift-lang/SourceKitdRequest.swift
    /Users/abdulras/SourceCache/swift/swift/stdlib/tools/swift-lang/SourceKitdResponse.swift
    /Users/abdulras/SourceCache/swift/swift/stdlib/tools/swift-lang/SourceKitdUID.swift
    stdlib/tools/swift-lang/8/UIDs.swift
    /Users/abdulras/SourceCache/swift/build/Ninja-ReleaseAssert/llvm-macosx-x86_64/bin/clang-7
    || apinotes/copy_apinotes
    || bin/swift
    || clang-tablegen-targets
    || include/swift/Option/SwiftOptions
    || include/swift/Parse/include-swift-Parse-ParsedSyntaxBuilders.h
    || include/swift/Parse/include-swift-Parse-ParsedSyntaxNodes.h
    || include/swift/Parse/include-swift-Parse-ParsedSyntaxRecorder.h
    || include/swift/Parse/swift-parse-syntax-generated-headers
    || include/swift/Syntax/include-swift-Syntax-SyntaxBuilders.h
    || include/swift/Syntax/include-swift-Syntax-SyntaxFactory.h
    || include/swift/Syntax/include-swift-Syntax-SyntaxKind.h
    || include/swift/Syntax/include-swift-Syntax-SyntaxNodes.h
    || include/swift/Syntax/include-swift-Syntax-SyntaxVisitor.h
    || include/swift/Syntax/include-swift-Syntax-TokenKinds.def
    || include/swift/Syntax/include-swift-Syntax-Trivia.h
    || include/swift/Syntax/swift-syntax-generated-headers
    || intrinsics_gen
    || lib/Basic/lib-Basic-8-UnicodeExtendedGraphemeClusters.cpp
    || lib/ClangImporter/generated_sorted_cf_database
    || lib/ClangImporter/lib-ClangImporter-SortedCFDatabase.def
    || lib/Migrator/symlink_migrator_data
    || lib/Parse/lib-Parse-8-ParsedSyntaxBuilders.cpp
    || lib/Parse/lib-Parse-8-ParsedSyntaxNodes.cpp
    || lib/Parse/lib-Parse-8-ParsedSyntaxRecorder.cpp
    || lib/Syntax/lib-Syntax-8-SyntaxBuilders.cpp
    || lib/Syntax/lib-Syntax-8-SyntaxFactory.cpp
    || lib/Syntax/lib-Syntax-8-SyntaxKind.cpp
    || lib/Syntax/lib-Syntax-8-SyntaxNodes.cpp
    || lib/Syntax/lib-Syntax-8-SyntaxSerialization.cpp
    || lib/Syntax/lib-Syntax-8-SyntaxVisitor.cpp
    || lib/Syntax/lib-Syntax-8-Trivia.cpp
    || lib/libSourceKitCore.a
    || lib/libSourceKitSupport.a
    || lib/libSourceKitSwiftLang.a
    || lib/libsourcekitdAPI.a
    || lib/libswiftAST.a
    || lib/libswiftBasic.a
    || lib/libswiftClangImporter.a
    || lib/libswiftDemangling.a
    || lib/libswiftDriver.a
    || lib/libswiftFrontend.a
    || lib/libswiftFrontendTool.a
    || lib/libswiftIDE.a
    || lib/libswiftIRGen.a
    || lib/libswiftImmediate.a
    || lib/libswiftIndex.a
    || lib/libswiftLLVMPasses.a
    || lib/libswiftMarkup.a
    || lib/libswiftMigrator.a
    || lib/libswiftOption.a
    || lib/libswiftParse.a
    || lib/libswiftParseSIL.a
    || lib/libswiftPrintAsObjC.a
    || lib/libswiftSIL.a
    || lib/libswiftSILGen.a
    || lib/libswiftSILOptimizer.a
    || lib/libswiftSema.a
    || lib/libswiftSerialization.a
    || lib/libswiftSymbolGraphGen.a
    || lib/libswiftSyntax.a
    || lib/libswiftSyntaxParse.a
    || lib/libswiftTBDGen.a
    || lib/sourcekitd.framework/Versions/A/XPCServices/SourceKitService.xpc/Contents/MacOS/SourceKitService
    || lib/sourcekitd.framework/Versions/A/sourcekitd
    || stdlib/public/Darwin/CoreFoundation/lib-swift-macosx-CoreFoundation.swiftmodule-x86_64.swiftmodule
    || stdlib/public/Darwin/CoreFoundation/stdlib-public-Darwin-CoreFoundation-OSX-x86_64
    || stdlib/public/Darwin/CoreFoundation/swiftCoreFoundation-swiftmodule-macosx-x86_64
    || stdlib/public/Darwin/CoreGraphics/lib-swift-macosx-CoreGraphics.swiftmodule-x86_64.swiftmodule
    || stdlib/public/Darwin/CoreGraphics/stdlib-public-Darwin-CoreGraphics-8-CGFloat.swift
    || stdlib/public/Darwin/CoreGraphics/stdlib-public-Darwin-CoreGraphics-OSX-x86_64
    || stdlib/public/Darwin/CoreGraphics/swiftCoreGraphics-swiftmodule-macosx-x86_64
    || stdlib/public/Darwin/Dispatch/lib-swift-macosx-Dispatch.swiftmodule-x86_64.swiftmodule
    || stdlib/public/Darwin/Dispatch/stdlib-public-Darwin-Dispatch-OSX-x86_64
    || stdlib/public/Darwin/Dispatch/swiftDispatch-swiftmodule-macosx-x86_64
    || stdlib/public/Darwin/Foundation/lib-swift-macosx-Foundation.swiftmodule-x86_64.swiftmodule
    || stdlib/public/Darwin/Foundation/stdlib-public-Darwin-Foundation-8-NSValue.swift
    || stdlib/public/Darwin/Foundation/stdlib-public-Darwin-Foundation-OSX-x86_64
    || stdlib/public/Darwin/Foundation/swiftFoundation-swiftmodule-macosx-x86_64
    || stdlib/public/Darwin/IOKit/lib-swift-macosx-IOKit.swiftmodule-x86_64.swiftmodule
    || stdlib/public/Darwin/IOKit/stdlib-public-Darwin-IOKit-OSX-x86_64
    || stdlib/public/Darwin/IOKit/swiftIOKit-swiftmodule-macosx-x86_64
    || stdlib/public/Darwin/ObjectiveC/lib-swift-macosx-ObjectiveC.swiftmodule-x86_64.swiftmodule
    || stdlib/public/Darwin/ObjectiveC/stdlib-public-Darwin-ObjectiveC-OSX-x86_64
    || stdlib/public/Darwin/ObjectiveC/swiftObjectiveC-swiftmodule-macosx-x86_64
    || stdlib/public/Darwin/XPC/lib-swift-macosx-XPC.swiftmodule-x86_64.swiftmodule
    || stdlib/public/Darwin/XPC/stdlib-public-Darwin-XPC-OSX-x86_64
    || stdlib/public/Darwin/XPC/swiftXPC-swiftmodule-macosx-x86_64
    || stdlib/public/Platform/lib-swift-macosx-Darwin.swiftmodule-x86_64.swiftmodule
    || stdlib/public/Platform/stdlib-public-Platform-8-Darwin.swift
    || stdlib/public/Platform/stdlib-public-Platform-8-tgmath.swift
    || stdlib/public/Platform/stdlib-public-Platform-OSX-x86_64
    || stdlib/public/Platform/swiftDarwin-swiftmodule-macosx-x86_64
    || stdlib/public/SwiftShims/copy_shim_headers
    || stdlib/public/SwiftShims/symlink_clang_headers
    || stdlib/public/core/lib-swift-macosx-Swift.swiftmodule-x86_64.swiftmodule
    || stdlib/public/core/stdlib-public-core-8-AtomicInt.swift
    || stdlib/public/core/stdlib-public-core-8-FloatingPointParsing.swift
    || stdlib/public/core/stdlib-public-core-8-FloatingPointTypes.swift
    || stdlib/public/core/stdlib-public-core-8-IntegerTypes.swift
    || stdlib/public/core/stdlib-public-core-8-SIMDVectorTypes.swift
    || stdlib/public/core/stdlib-public-core-8-Tuple.swift
    || stdlib/public/core/stdlib-public-core-8-UnsafeBufferPointer.swift
    || stdlib/public/core/stdlib-public-core-8-UnsafeRawBufferPointer.swift
    || stdlib/public/core/stdlib-public-core-OSX-x86_64
    || stdlib/public/core/swiftCore-swiftmodule-macosx-x86_64
    || stdlib/tools/swift-lang/stdlib-tools-swift-lang-8-UIDs.swift
    || stdlib/tools/swift-lang/stdlib-tools-swift-lang-OSX-x86_64
    || tools/SourceKit/include/SourceKit/Core/generated_sourcekit_uids
    || tools/SourceKit/include/SourceKit/Core/tools-SourceKit-include-SourceKit-Core-ProtocolUIDs.def
    || tools/SourceKit/tools/sourcekitd/bin/XPC/Client/sourcekitd_exports
  outputs:
    cmake_object_order_depends_target_swiftSwiftLang-macosx-x86_64
    lib/swift/macosx/x86_64/libswiftSwiftLang.dylib
    stdlib/tools/swift-lang/stdlib-tools-swift-lang-OSX-x86_64-SwiftLang.o
    stdlib/tools/swift-lang/CMakeFiles/stdlib-tools-swift-lang-OSX-x86_64-SwiftLang.o
```

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by compnerd** [comment]
@swift-ci please clean test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Review by benlangmuir — APPROVED** [review]
It's not ideal, but as long as this makes it through CI it's fine with me.  Hopefully this will all be gone soon.

**Comment by compnerd** [comment]
@swift-ci please clean test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please clean test macOS platform

**Comment by compnerd** [comment]
@swift-ci please clean test macOS platform

**Comment by aschwaighofer** [comment]
Looks like this is causing failures:

https://ci.swift.org//job/swift-master-source-compat-suite/4652

**Comment by benlangmuir** [comment]
That looks like we're missing the dependency again 😞 The only sourcekitd-related action I see in the log is creating the `.exports` file.
```
swift-lang/SourceKitdClient.swift:15:8: error: no such module 'sourcekitd'
import sourcekitd
       ^
```

**Pull request merged**
