### PR TITLE
[CodeCompletion] Suggest 'Self' inside struct, enum and classe

### PR DESCRIPTION
**Pull request by rintaro**
In `protocol`, `Self` is implicitly declared as a generic parameter.
In `struct` and `enum`, `Self` is just an alias for the nominal type.
In `class`, `Self` is a dynamic type and usable only in result types and inside function bodies.

rdar://problem/61307680

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test Linux

**Comment by rintaro** [comment]
@swift-ci Please smoke test Linux

**Review by benlangmuir — APPROVED** [review]
LGTM; one suggestion for an additional test, which could be a follow-up.

**Comment by rintaro** [comment]
@benlangmuir I guess you were suggesting test cases in `where` clause or somewhere else?

**Comment by rintaro** [comment]
@swift-ci Please smoke test Linux

**Comment by benlangmuir** [comment]
Huh, I don't know where my comment went.  I suggested testing Self inside a computed property body,

```swift
var foo: String { "\(Self.self)" }
```

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test macOS

**Pull request merged**
