### PR TITLE
Introduce a BoundGenericAliasType into the type hierarchy.

### PR DESCRIPTION
**Pull request by adrian-prantl**
#### What's in this pull request?

```
Introduce a BoundGenericAliasType into the type hierarchy and wire it up
for emitting debug info.
Previously bound generial alias types were represented as substituted types
which made them transparent for debug info and some kinds of diagnostics.
This commit introduced a sugared BoundGenericAliasType as a child of
BoundGenericType and a new base class BoundGenericNominalType for all
other bound generic types.
```
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

   rdar://problem/25093437

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

A smoke test on macOS does the following:
1. Builds the compiler incrementally.
2. Builds the standard library only for macOS. Simulator standard libraries and
   device standard libraries are not built.
3. lldb is not built.
4. The test and validation-test targets are run only for macOS. The optimized
   version of these tests are not run.

A smoke test on Linux does the following:
1. Builds the compiler incrementally.
2. Builds the standard library incrementally.
3. lldb is built incrementally.
4. The swift test and validation-test targets are run. The optimized version of these
   tests are not run.
5. lldb is tested.

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

for emitting debug info.
Previously bound generial alias types were represented as substituted types
which made them transparent for debug info and some kinds of diagnostics.
This commit introduced a sugared BoundGenericAliasType as a child of
BoundGenericType and a new base class BoundGenericNominalType for all
other bound generic types.

rdar://problem/25093437

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@slavapestov, @DougGregor, @rudkx: Could you please take a look at this?
To what degree do we currently support nested generic type aliases? There is one known problem in TypeCheckType that I couldn't solve so far.

**Comment by slavapestov** [comment]
@adrian-prantl Let's discuss this in person on Monday -- I need some time to digest the pull request.

Thanks for working on this though!

**Comment by adrian-prantl** [comment]
I finally had some time to look at this again. I was able to make some progress by extending ConstraintSystem::openGeneric() to check whether a type variable was already introduced (is this the right place to do this?), but the main problem of how to correctly set the parent type in TypeChecker::applyUnboundGenericArguments() remains.

I pushed a rebased version of the patch.

The result type of getIntFn()
```
public struct Outer<P> {
  public typealias FunTy<Q> = (Q) -> (P)
  func getIntFn() -> FunTy<Int>? { return nil }
}
```
is currently
(optional_type
  (bound_generic_alias_type decl=main.(file).Outer.FunTy
    (parent=unbound_generic_type decl=main.(file).Outer)
    (struct_type decl=Swift.(file).Int)))
but I think the parent should be a (bound_generic_type archetype_type P).

@slavapestov: Any ideas how/where to fix this?

**Comment by slavapestov** [comment]
I'm not sure if adding this hack to openGeneric() is the right idea. I'll take a look at this PR and see what I can come up with.

**Comment by slavapestov** [comment]
Can we close this? The code has changed a fair bit and I have a different approach in mind.

**Pull request closed without merging**
