### PR TITLE
stdlib: Fix for NSFastEnumerator breakage in resilient builds

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please benchmark

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@moiseev Does this fix look reasonable? The other alternative is to mark _fastEnumerationStorageMutationsTarget as @_fixed_layout.

**Comment by gparker42** [comment]
Is there any practical gain in future flexibility by enforcing the function boundary instead of exposing the variable directly? Allowing the most direct access to the variable possible would improve performance, and I can't think of any future where we would regret that.

**Comment by slavapestov** [comment]
@gparker42 No, just an aesthetic difference I guess. My fix removes the @_inlinable and @_versioned attributes, the other approach adds a @_fixed_layout attribute. However in the interest of minimizing changes for now until the stdlib folks complete their audit, I'll change my patch to go with the latter approach, since I want to get this checked in to get the bot passing again.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
The macOS failure looks unrelated to my change:

```
<unknown>:0: error: fatal error encountered during compilation; please file a bug report with your project and the crash log
<unknown>:0: note: No available targets are compatible with this triple.
```

**Comment by slavapestov** [comment]
Let's try the full test

**Comment by slavapestov** [comment]
@swift-ci Please test macOS

**Comment by slavapestov** [comment]
@swift-ci Please test macOS

**Pull request merged**
