### PR TITLE
Sema: Targeted fix for bad interaction between resilience checks and -enable-testing [4.0 06-02-2017]

### PR DESCRIPTION
**Pull request by slavapestov**
Cherry-pick of #10179.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by shahmishal** [comment]
@swift-ci Please test

**Comment by shahmishal** [comment]
@swift-ci Please test macOS

**Comment by shahmishal** [comment]
@swift-ci Please clean test macOS

**Pull request merged**
