### PR TITLE
[runtime] addressed review comments outlined in #1950

### PR DESCRIPTION
**Pull request by shawnce**
#### What's in this pull request?

Addresses final review comments outlined in #1950 
@gparker42

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by gparker42** [comment]
@swift-ci Please test

**Comment by shawnce** [comment]
Working on understanding Linux build failure

**Comment by shawnce** [comment]
I guess this is a "flaky" test that can fail on Linux?

```
    @skipIfWindows #llvm.org/pr24452: Get lldb-mi tests working on Windows
    @skipIfFreeBSD # llvm.org/pr22411: Failure presumably due to known thread races
    @expectedFlakeyLinux("llvm.org/pr24717")
    def test_lldbmi_break_insert_function_pending(self):
```

**Comment by gparker42** [comment]
I'm not worried about that lldb test failure.

**Comment by gparker42** [comment]
Looks good.

**Pull request merged**
