### PR TITLE
[stdlib] Rename `VectorNumeric` to `VectorProtocol`.

### PR DESCRIPTION
**Pull request by dan-zheng**
Depends on https://github.com/tensorflow/swift-apis/pull/205.
Resolves [TF-559](https://bugs.swift.org/browse/TF-559).

### CODE REVIEW

**Comment by rxwei** [comment]
`ShapedVectorProtocol` should actually be removed. You can do that in this patch.

**Comment by dan-zheng** [comment]
> `ShapedVectorProtocol` should actually be removed. You can do that in this patch.

Done.

**Comment by dan-zheng** [comment]
Shall we first merge https://github.com/tensorflow/swift-apis/pull/205, then update `tensorflow-swift-apis` in `update-checkout-config.json` and merge this PR?

**Review by rxwei — APPROVED** [review]

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Pull request merged**
