### PR TITLE
[5.5] [SymbolGraph] add sourceOrigin info for all protocol implementations

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
Resolves rdar://78680450

This PR ports https://github.com/apple/swift/pull/37777 to the `release/5.5` branch.

**Change Information**

* Explanation: Adds `sourceOrigin` information for symbols that implement protocol requirements when the protocol and the implementation are in the same module.
* Scope of issue: Currently, the `sourceOrigin` field in the symbol graph's relationships only appears when a symbol is synthesized, or when the protocol being implemented was defined in a different module. When a symbol is implementing a locally-defined protocol and also inherits docs, there is currently no way to relate the implementation to the symbol that defined the docs it's inheriting.
* Risk: Low. The added code only adds a new field in more places.
* Automated Testing: The lit test "SymbolGraph/Relationships/Synthesized/InheritedDocs" has been updated to exercise this situation.

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Comment by QuietMisdreavus** [comment]
@swift-ci Please build toolchain macOS platform

**Comment by QuietMisdreavus** [comment]
```
FATAL: Unable to delete script file /var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/jenkins3885156208099152097.sh
```

@swift-ci Please test macOS platform

**Comment by QuietMisdreavus** [comment]
Ditto for the toolchain build.

@swift-ci Please build toolchain macOS platform

**Comment by QuietMisdreavus** [comment]
Toolchain build failed again in the SwiftPM tests:

```
Tests/SimpleTests/SwiftTests.swift:1:8: error: module compiled with Swift 5.3.2 cannot be imported by the Swift 5.5 compiler: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/XCTest.swiftmodule/x86_64-apple-macos.swiftmodule
```

@swift-ci Please build toolchain macOS platform

**Comment by shahmishal** [comment]
This is known issue, and it was resolved with this PR https://github.com/apple/swift/pull/37823

**Comment by shahmishal** [comment]
@swift-ci Please build toolchain macOS platform

**Review by franklinsch — APPROVED** [review]

**Review by airspeedswift — APPROVED** [review]

**Pull request merged**
