### PR TITLE
Revert "[stdlib] One-sided ranges and RangeExpression (#8710)"

### PR DESCRIPTION
**Pull request by aschwaighofer**
This seems to have broken the resilient build.

This reverts commit 946b776e371717f89ba5b4225efcbec5eb07d1b0.

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test and merge

**Comment by airspeedswift** [comment]
Please *don't* revert. This seems like it could be a resilience bug. Better to XFAIL the test in resilient mode.

**Comment by airspeedswift** [comment]
I'll do the XFAIL now.

**Comment by airspeedswift** [comment]
I raised #9140

**Pull request merged**
