### PR TITLE
[Gardening] Remove the unused utils/guard-malloc-swift script.

### PR DESCRIPTION
**Pull request by Rostepher**
This script appears to be completely unused and unmodified for nearly 6 years. I think it's probably safe to remove it.

### CODE REVIEW

**Comment by Rostepher** [comment]
@swift-ci please smoke test

**Comment by Rostepher** [comment]
@swift-ci please smoke test Linux platform

**Comment by Rostepher** [comment]
@swift-ci please smoke test macOS platform

**Comment by gribozavr** [comment]
As far as I know, nobody used it even 3 years ago.

**Review by shahmishal — APPROVED** [review]

**Review by compnerd — APPROVED** [review]

**Comment by compnerd** [comment]
This is largely replaceable with the sanitizers.

**Pull request merged**
