### PR TITLE
[DNM] Revert "Type reconstruction for variadic generics"

### PR DESCRIPTION
**Pull request by xedin**
Reverts apple/swift#63789

Testing to see whether this is the change that regressed RxSwift and distributed actors.

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test source compatibility release

**Comment by xedin** [comment]
@slavapestov looks like RxSwift and distributed-actors source compat regressions were caused by #63789.

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by AnthonyLatsis** [comment]
FYI the issue tracking this is #63869

**Pull request closed without merging**
