### PR TITLE
Remove ImportHintKind::Reference

### PR DESCRIPTION
**Pull request by CodaFi**
The only place in the Clang Importer that needs to deal with anything
related to C++, and it doesn't actually do anything.  Remove the
import hint and the last place where the importer creates InOutTypes
as well.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please test

**Comment by CodaFi** [comment]
@rjmccall The blame shows you were the last one to touch this codepath, but even then it was just shuffling some code around.  Can you remember what this is for?

**Review by jrose-apple — APPROVED** [review]
We may want this some day, but we can deal with it then. LGTM!

**Comment by CodaFi** [comment]
@swift-ci please test source compatibility

**Comment by CodaFi** [comment]
Source compatibility failures are unrelated.

:boat:

**Pull request merged**
