### PR TITLE
Add CustomReflectable implementation to most Foundation value types.

### PR DESCRIPTION
**Pull request by parkera**
#### What's in this pull request?

Adds CustomReflectable implementation to most Foundation value types.

Also improves the basic debugDescription and description methods.
#### Resolved bug number

rdar://26580762

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

A smoke test on macOS does the following:
1. Builds the compiler incrementally.
2. Builds the standard library only for macOS. Simulator standard libraries and
   device standard libraries are not built.
3. lldb is not built.
4. The test and validation-test targets are run only for macOS. The optimized
   version of these tests are not run.

A smoke test on Linux does the following:
1. Builds the compiler incrementally.
2. Builds the standard library incrementally.
3. lldb is built incrementally.
4. The swift test and validation-test targets are run. The optimized version of these
   tests are not run.
5. lldb is tested.

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by parkera** [comment]
@swift-ci Please test and merge

**Comment by parkera** [comment]
```
<unknown>:0: error: could not acquire lock file for module 'Darwin': failed to create link /var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/C/org.llvm.clang.buildnode/ModuleCache/1SZRYF7WWU99E/Darwin-HUB66TE1ZK5G.pcm.lock to /var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/C/org.llvm.clang.buildnode/ModuleCache/1SZRYF7WWU99E/Darwin-HUB66TE1ZK5G.pcm.lock-b0ff6f2d: No such file or directory
/Users/buildnode/jenkins/workspace/swift-PR-osx/swiftpm/Sources/PackageDescription/Package.swift:14:8: error: no such module 'Darwin.C'
import Darwin.C
       ^
<unknown>:0: error: build had 1 command failures
```

@shahmishal some kind of config problem? (https://ci.swift.org/job/swift-PR-osx/2762/)

**Comment by parkera** [comment]
@swift-ci Please test and merge

**Comment by parkera** [comment]
Transient I guess.

**Comment by michael-lehew** [comment]
Thanks for getting these in, hope my WIP was marginally helpful, these LGTM.

**Comment by parkera** [comment]
The idea here was to print out the contents when less than a certain size (64) and otherwise just the count. If I messed something up there (totally possible) then I welcome a PR to fix it.

**Comment by exalted** [comment]
It's no biggie to me. I've just bumped into this, when I was using `.description` on device token when remote notifications are registered in an iOS device for years and I was surprised to see the output changed all the sudden... that's all. 

Btw, I don't see the check for 64 bytes... just so you know. 

Thanks!

**Pull request merged**
