### PR TITLE
[cxx-interop] compilations that do not enable C++ interoperability sh…

### LINKED ISSUE #65832: [cxx-import] a Swift module that imports 'CxxStdlib' and forces the client to enable interop produces unclear diagnostic
RIght now when a Swift module A enables interoperability and imports `Cxxstdlib`, and Swift module B that consumes it doesn't, the compiler will fail to compile B with the following error:

```
<unknown>:0: error: cannot load underlying module for 'CxxStdlib'
```

This diagnostic should be improved, and should suggest to the user to enable C++ interoperability.

### LINKED ISSUE #65833: [cxx-import] a Swift module that imports a C++ module and forces the client to enable interop produces unclear diagnostic
Right now when a Swift module A enables interoperability and imports a C++ module `cxxmod`, and Swift module B that consumes it doesn't, the compiler will fail to compile B with the following error:

```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "cxxmod.h"
        ^
/Users/alex/i/swift/test/Interop/SwiftToCxx/cross-module-refs/Inputs/cxxmod.h:1:1: error: unknown type name 'class'; did you mean 'Class'?
class TestMough {
^
<unknown>:0: note: 'Class' declared here
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "cxxmod.h"
        ^
/Users/alex/i/swift/test/Interop/SwiftToCxx/cross-module-refs/Inputs/cxxmod.h:1:16: error: expected ';' after top level declarator
class TestMough {
               ^
<unknown>:0: error: could not build Objective-C module 'cxxmod'
```

The diagnostic should be improved to be more clear that the client needs to enable interoperability.

### PR DESCRIPTION
**Pull request by hyp**
…ould not be able to import modules that do enable C++ interoperability by default

A supplemental hidden frontend option allows advanced users to opt-out of this requirement.

Fixes https://github.com/apple/swift/issues/65833
Fixes https://github.com/apple/swift/issues/65832

### CODE REVIEW

**Comment by hyp** [comment]
@swift-ci please test

**Review by zoecarver — APPROVED** [review]
This is great, thanks Alex!

**Comment by hyp** [comment]
@swift-ci please test linux platform

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test source compatibility

**Comment by hyp** [comment]
@swift-ci please test windows platform

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test source compatibility

**Pull request merged**
