### PR TITLE
AST: Assert we were given a type parameter in GenericSignatureImpl::requiresClass

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
Doing the absolute minimum here to ease progression.

### CODE REVIEW

**Comment by AnthonyLatsis** [comment]
Let us see if anything hits the assert

@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci test source compatibility

**Comment by AnthonyLatsis** [comment]
@CodaFi is the source compat job expected not to show any details on failures?

**Comment by theblixguy** [comment]
I think you can access the logs from Status -> Build Artifacts

**Comment by AnthonyLatsis** [comment]
Neat, thank you!

**Comment by CodaFi** [comment]
Oh, the release and debug builders both hit a weird internal failure. I suspect there's either a file system race somewhere deep in the build, or they've run out of space. Let's try again.

@swift-ci test source compatibility

**Comment by CodaFi** [comment]
@swift-ci test Windows

**Comment by AnthonyLatsis** [comment]
> Oh, the release and debug builders both hit a weird internal failure

Did the release builder not crash on generating SIL for an opaque type property in SwiftMovie?

**Comment by AnthonyLatsis** [comment]
@swift-ci please test source compatibility debug

**Comment by AnthonyLatsis** [comment]
@swift-ci please test source compatibility debug

**Comment by CodaFi** [comment]
@swift-ci please test source compatibility debug

**Comment by AnthonyLatsis** [comment]
Yay!

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
