### PR TITLE
Clang-format files touched by ConstExpr work.

### PR DESCRIPTION
**Pull request by jmolloy**
This PR runs clang-format on files touched in the constexpr work and in particular files that will be touched by a followup PR.

NFC, just formatting.

### CODE REVIEW

**Review by lattner — APPROVED** [review]
LGTM thanks!  Please check out the test failure though

**Comment by lattner** [comment]
Looks like a build error?

/home/swiftci/jenkins/workspace/swift-PR-TensorFlow-Linux/swift/lib/SILOptimizer/Mandatory/TFConstExpr.cpp:709:7: error: no matching function for call to 'classifyFunction'
  if (classifyFunction(callee) == WellKnownFunction::AssertionFailure) {
      ^~~~~~~~~~~~~~~~
/home/swiftci/jenkins/workspace/swift-PR-TensorFlow-Linux/swift/lib/SILOptimizer/Mandatory/TFConstExpr.cpp:60:26: note: candidate function not viable: no known conversion from 'swift::SILFunction *' to 'llvm::StringRef' for 1st argument
static WellKnownFunction classifyFunction(StringRef mangledName) {
                         ^

**Comment by jmolloy** [comment]
Thanks Chris. Yes, merge conflict SNAFU. Fixed now.

@swift-ci please test tensorflow

**Comment by jmolloy** [comment]
@swift-ci Please test tensorflow

**Pull request merged**
