### PR TITLE
Libdispatch overlay fixes

### PR DESCRIPTION
**Pull request by mwwa**
#### What's in this pull request?

Dispatch overlay changes and bug fixes stemming from feedback from previous betas.
#### Resolved bug number:

([SR-1817](https://bugs.swift.org/browse/SR-1817))([SR-1771](https://bugs.swift.org/browse/SR-1771))([SR-1770](https://bugs.swift.org/browse/SR-1770))([SR-1769](https://bugs.swift.org/browse/SR-1769))

```
<rdar://problem/26725156> <rdar://problem/26873917>
<rdar://problem/26918843> <rdar://problem/26810149>
<rdar://problem/27117023> <rdar://problem/27121422>
<rdar://problem/27236887> <rdar://problem/27337555>
```

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by mwwa** [comment]
@DougGregor Can you review?

**Comment by mwwa** [comment]
@swift-ci please test

**Comment by mwwa** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test and merge

**Pull request merged**
