### PR TITLE
On 'canImport' of Clang submodules of modules with an umbrella header, attempt to infer the submodule

### PR DESCRIPTION
**Pull request by artemcm**
Resolves rdar://124163264

### CODE REVIEW

**Comment by cachemeifyoucan** [comment]
Can we add a test case to make sure canImport of submodule works?

**Comment by artemcm** [comment]
> Can we add a test case to make sure canImport of submodule works?

Yup, working on it.

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
@swift-ci smoke test

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
@swift-ci test

**Pull request merged**
