### PR TITLE
🍒[5.5][Concurrency] Unstructured tasks must not attempt to copy "parent (task local) pointers"

### PR DESCRIPTION
**Pull request by ktoso**
**Explanation:** When we create an unstructured task we must copy all task values values to the new task. When a task has a parent task, it's task locals list begins with a pointer to the parent's task locals. When copying values to an unstructured task we did not account for the "parent pointer" type of task local item, which leads to attempts to copy null `valueType`s which is illegal. In any case, copying a parent pointer even if it worked is specifically _against_ what we should be doing here -- a deep copy. Solution: don't copy parent pointers.
**Reviewer:** @drexin @DougGregor
**Radar/SR Issue:** rdar://80032684
**Risk:** Small.
**Testing:** PR testing and CI on main.
**Original PR:** https://github.com/apple/swift/pull/38218

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please nominate

**Review by DougGregor — APPROVED** [review]

**Comment by ktoso** [comment]
Linux failure unrelated:

```
<unknown>:0: error: error opening input file 'lib/libYamsTests.a' (The file was not recognized as a valid object file)
01:26:45.252 ninja: build stopped: subcommand failed.
```

**Comment by ktoso** [comment]
@swift-ci please test Linux

**Pull request merged**
