### PR TITLE
[benchmark] Add interpolation; more stable builder

### PR DESCRIPTION
**Pull request by milseman**

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please smoke benchmark

**Comment by milseman** [comment]
@swift-ci please smoke test

**Comment by milseman** [comment]
That's pretty noisy... let me try a full run.

@swift-ci please benchmark

**Comment by milseman** [comment]
Ugh, so much noise.

**Comment by huonw** [comment]
Unfortunately this breaks on 32-bit platforms, so I'm reverting.

```
19:20:30 
/Users/buildnode/jenkins/workspace/oss-swift-incremental-RA-osx/swift/benchmark/single-source/StringInterpolation.swift:79:35: error: integer literal '4398046511103' overflows when stored into 'UInt'
19:20:30   let numOct: UInt = min(UInt(N), 0x0000_03FF_FFFF_FFFF)
19:20:30                                   ^
19:20:30 /Users/buildnode/jenkins/workspace/oss-swift-incremental-RA-osx/swift/benchmark/single-source/StringInterpolation.swift:78:35: error: integer literal '1152921504606846975' overflows when stored into 'UInt'
19:20:30   let numHex: UInt = min(UInt(N), 0x0FFF_FFFF_FFFF_FFFF)
19:20:30                                   ^
```

**Pull request merged**
