### PR TITLE
test: fix after 45dc14a27501

### PR DESCRIPTION
**Pull request by compnerd**
Fix the tests after 45dc14a27501.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @nathawes

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by nathawes** [comment]
Sorry! And thanks for fixing it.

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Pull request merged**
