### PR TITLE
[CSBindings] Don't favor application result types before application …

### PR DESCRIPTION
**Pull request by xedin**
…happens

Until `ApplicableFunction` constraint is simplified result type associated with 
it cannot be bound because the binding set if incomplete.

Resolves: rdar://139237088

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
https://github.com/swiftlang/swift/pull/76952 incoverred the fact that application result types bound too eagerly in some cases.

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Review by hamishknight — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test

**Pull request merged**
