### PR TITLE
build: use correct variable to check for clang

### PR DESCRIPTION
**Pull request by edymtt**
Addresses rdar://problem/56866783

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci test Windows

**Comment by edymtt** [comment]
Based on discussion in #28055, this seems the fix I should have in the first place

**Comment by shahmishal** [comment]
@swift-ci smoke test

**Review by shahmishal — APPROVED** [review]

**Comment by edymtt** [comment]
Duplicate of #28058

**Pull request closed without merging**
