### PR TITLE
[TF-503] Remove @_silgen_name functions from CompilerRuntime.swift

### PR DESCRIPTION
**Pull request by burmako**
This PR fixes https://bugs.swift.org/browse/TF-503 by cleaning up some of the currently unused functionality in CompilerRuntime.swift. I was unsure about `SWIFT_TENSORFLOW_SYNC_EXECUTION`, but I removed it and no tests failed.

### CODE REVIEW

**Comment by bgogul** [comment]
@swift-ci please test tensorflow

**Comment by bgogul** [comment]
@swift-ci please clean test tensorflow

**Review by bgogul — APPROVED** [review]
Looks good. Let us wait for the CI to finish before merging?

**Comment by burmako** [comment]
Sounds good!

**Comment by bgogul** [comment]
@swift-ci please clean test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow linux CPU

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow linux CPU

**Comment by burmako** [comment]
@swift-ci Please test tensorflow linux CPU

**Comment by burmako** [comment]
@swift-ci please test tensorflow

**Comment by burmako** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Pull request merged**
