### PR TITLE
[swiftc (61 vs. 5458)] Add crasher in swift::DiagnosticEngine::emitDiagnostic

### PR DESCRIPTION
**Pull request by practicalswift**
Add test case for crash triggered in `swift::DiagnosticEngine::emitDiagnostic`.

Current number of unresolved compiler crashers: 61 (5458 resolved)

/cc @jtbandes - just wanted to let you know that this crasher caused an assertion failure for the assertion `false && "encountered %error in diagnostic text"` added on 2016-11-19 by you in commit 32635696 :-)

Assertion failure in [`lib/AST/DiagnosticEngine.cpp (line 490)`](https://github.com/apple/swift/blob/df4b7752ff770f3cabd8ea8091aa72d21ce43c0f/lib/AST/DiagnosticEngine.cpp#L490):

```
Assertion `false && "encountered %error in diagnostic text"' failed.

When executing: void formatDiagnosticText(llvm::StringRef, ArrayRef<swift::DiagnosticArgument>, llvm::raw_ostream &)
```

Assertion context:

```c++
      Modifier = InText.substr(0, Length);
      InText = InText.substr(Length);
    }

    if (Modifier == "error") {
      assert(false && "encountered %error in diagnostic text");
      Out << StringRef("<<ERROR>>");
      break;
    }

    // Parse the optional argument list for a modifier, which is brace-enclosed.
```
Stack trace:

```
0 0x0000000003923da8 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/path/to/swift/bin/swift+0x3923da8)
1 0x00000000039244e6 SignalHandler(int) (/path/to/swift/bin/swift+0x39244e6)
2 0x00007f1e9ec973e0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x113e0)
3 0x00007f1e9d1bd428 gsignal /build/glibc-Qz8a69/glibc-2.23/signal/../sysdeps/unix/sysv/linux/raise.c:54:0
4 0x00007f1e9d1bf02a abort /build/glibc-Qz8a69/glibc-2.23/stdlib/abort.c:91:0
5 0x00007f1e9d1b5bd7 __assert_fail_base /build/glibc-Qz8a69/glibc-2.23/assert/assert.c:92:0
6 0x00007f1e9d1b5c82 (/lib/x86_64-linux-gnu/libc.so.6+0x2dc82)
7 0x000000000144f7f7 formatDiagnosticText(llvm::StringRef, llvm::ArrayRef<swift::DiagnosticArgument>, llvm::raw_ostream&) (/path/to/swift/bin/swift+0x144f7f7)
8 0x000000000144e5d7 formatDiagnosticText(llvm::StringRef, llvm::ArrayRef<swift::DiagnosticArgument>, llvm::raw_ostream&) (/path/to/swift/bin/swift+0x144e5d7)
9 0x000000000144d8b0 swift::DiagnosticEngine::emitDiagnostic(swift::Diagnostic const&) (/path/to/swift/bin/swift+0x144d8b0)
10 0x000000000144cbff swift::DiagnosticEngine::flushActiveDiagnostic() (/path/to/swift/bin/swift+0x144cbff)
11 0x00000000013775f3 swift::ASTVisitor<(anonymous namespace)::AttributeChecker, void, void, void, void, void, void>::visit(swift::DeclAttribute*) (/path/to/swift/bin/swift+0x13775f3)
12 0x0000000001375b11 swift::TypeChecker::checkDeclAttributes(swift::Decl*) (/path/to/swift/bin/swift+0x1375b11)
13 0x0000000001287e1f (anonymous namespace)::DeclChecker::visitProtocolDecl(swift::ProtocolDecl*) (/path/to/swift/bin/swift+0x1287e1f)
14 0x00000000012777cd (anonymous namespace)::DeclChecker::visit(swift::Decl*) (/path/to/swift/bin/swift+0x12777cd)
15 0x0000000001286e6b (anonymous namespace)::DeclChecker::visitClassDecl(swift::ClassDecl*) (/path/to/swift/bin/swift+0x1286e6b)
16 0x00000000012776ab (anonymous namespace)::DeclChecker::visit(swift::Decl*) (/path/to/swift/bin/swift+0x12776ab)
17 0x00000000012775d3 swift::TypeChecker::typeCheckDecl(swift::Decl*, bool) (/path/to/swift/bin/swift+0x12775d3)
18 0x00000000012f2f85 swift::performTypeChecking(swift::SourceFile&, swift::TopLevelContext&, swift::OptionSet<swift::TypeCheckingFlags, unsigned int>, unsigned int, unsigned int) (/path/to/swift/bin/swift+0x12f2f85)
19 0x0000000000f6c706 swift::CompilerInstance::performSema() (/path/to/swift/bin/swift+0xf6c706)
20 0x00000000004a6b26 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) (/path/to/swift/bin/swift+0x4a6b26)
21 0x0000000000464c77 main (/path/to/swift/bin/swift+0x464c77)
22 0x00007f1e9d1a8830 __libc_start_main /build/glibc-Qz8a69/glibc-2.23/csu/../csu/libc-start.c:325:0
23 0x0000000000462319 _start (/path/to/swift/bin/swift+0x462319)
```

### CODE REVIEW

**Comment by practicalswift** [comment]
@swift-ci please test and merge

**Comment by jtbandes** [comment]
@practicalswift This might be challenging, but I'm curious if for this particular category of assertions (`%error`) you might be able to determine which diagnostic message was being emitted, and tag the person who appears in git blame for that diagnostic (either in the .def file or the line of code that's emitting it)? The goal of my adding this assertion is to catch other people's errors, not my own (although I admit there could be bugs in my code) 😉

**Comment by practicalswift** [comment]
@jtbandes In this particular case - who would be the correct person to ping? :-)

**Comment by jtbandes** [comment]
In this case the diagnostic is being emitted from here: https://github.com/apple/swift/blob/e367520d63b7c5aae1e7490507b7a35ef9870726/lib/Sema/TypeCheckAttr.cpp#L1811-L1814

And the text itself is here: https://github.com/apple/swift/blob/e367520d63b7c5aae1e7490507b7a35ef9870726/include/swift/AST/DiagnosticsSema.def#L3358-L3361

And it looks like myself and @slavapestov are to blame for these ;)

**Pull request merged**
