### PR TITLE
[SILOpt] Don't do callee analysis on destructors of imported classes.

### PR DESCRIPTION
**Pull request by jrose-apple**
If by chance we haven't imported the members of a particular class, SIL should not fault them in if at all possible. We won't be able to see their bodies anyway.

rdar://problem/29535170

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swiftix ping

**Comment by swiftix** [comment]
LGTM

**Review by swiftix — APPROVED** [review]
LGTM

**Pull request merged**
