### PR TITLE
[TF] Move all random number APIs from TF stdlib to the deep learning library.

### PR DESCRIPTION
**Pull request by rxwei**
- Move `Tensor`'s [random number initializers](https://github.com/apple/swift/blob/bf24b296929b49babe19b04da0554f5d9f885558/stdlib/public/TensorFlow/Tensor.swift#L615) to [Initializers.swift](https://github.com/tensorflow/swift-apis/blob/master/Sources/DeepLearning/Initializers.swift).
  - Replace the obsolete `_TFHoistable` hack with sane delegate initialization.
- Move [random number generators and distributions](https://github.com/apple/swift/blob/tensorflow/stdlib/public/TensorFlow/Random.swift) to [Random.swift](https://github.com/tensorflow/swift-apis/blob/master/Sources/DeepLearning/Random.swift) and their tests to [PRNGTests.swift](https://github.com/tensorflow/swift-apis/blob/master/Tests/DeepLearningTests/PRNGTests.swift).
- Update trivial model tests to use concrete numeric weights generated by random initializers using the original configuration.
- Adopt the new `Optimizer.update(_:along:)` type signature in `test/AutoDiff/model_autodiff_runtime.swift`. This change was introduced in https://github.com/tensorflow/swift-apis/pull/6.
  - Note: It is unprincipled to add tests here that depend on the deep learning library (circular dependency!). When CI becomes ready, we should move the test over to `DeepLearning` as an XCTest.
- Update checkout to https://github.com/tensorflow/swift-apis/commit/ba8b82cf98770583d0a94a3b7fb38d15128e9ba6.

This enables developing these APIs without an active compiler build and XCTest (!), and is a part of our "move things out of the compiler repo" effort.

Corresponding PR in the **swift-apis** repo: https://github.com/tensorflow/swift-apis/pull/8.

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow macOS

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Review by dan-zheng — APPROVED** [review]
Yay for migration out of compiler repository!

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow macOS

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow macOS

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow Linux GPU

**Comment by rxwei** [comment]
@swift-ci please test tensorflow macOS

**Comment by rxwei** [comment]
macOS CI machine is not working. Tested it locally on macOS. Merging now.

**Pull request merged**
