### PR TITLE
[DNM][AST] Keep track of an "isDerivableFromSwiftType" bit for Clang types.

### PR DESCRIPTION
**Pull request by varungandhi-apple**
I wasn't sure what to name the type, so I've named it `ClangTypeWrapper` for now.

Probably clean up the PR a little bit tomorrow but I figured I should put it up sooner rather than later for feedback and testing.

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
@swift-ci please test

**Comment by varungandhi-apple** [comment]
@swift-ci please test source compatibility

**Comment by varungandhi-apple** [comment]
@swift-ci please clean test

**Comment by varungandhi-apple** [comment]
There's some other breakage because of the SIL stuff, marking this as DNM right now.

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by varungandhi-apple** [comment]
The behavior for marking something "isDerivable" in this PR is not correct. Arguably, "isDerivable" is the wrong name altogether. We do not want the mangling for existing code to change. However, since multiple C types are mapped to the same Swift type, some function types like `void (unsigned long)` will get marked as "not derivable" because `unsigned long -> Int -> long`. We should instead check for something like "does this function type have additional attributes".

**Comment by varungandhi-apple** [comment]
I've opened https://github.com/apple/swift/pull/34057 with a more recent version of these changes, so I'm closing this PR.

**Pull request closed without merging**
