### PR TITLE
Fix for crash involving optionals, empty tuple and closures [3.1]

### PR DESCRIPTION
**Pull request by slavapestov**
rdar://problem/30429709

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@DougGregor You already looked at the master PR, can you approve this one also?

**Review by DougGregor — APPROVED** [review]
LGTM!

**Comment by practicalswift** [comment]
Nice!

**Pull request merged**
