### PR TITLE
[6.0🍒] NCGenerics reverse condfail fix + bonus content!

### PR DESCRIPTION
**Pull request by kavon**
- Explanation: 
    - Fixes an issue with the ASTPrinter where an incorrect swiftinterface can be generated (rdar://130179698).
    - Fixes a reverse condfail where the new compiler can't read a slightly older stdlib's swiftinterface (rdar://130424971). 
    - In addition, there are NFC / documentation improvements which these patches depend on or are mostly harmless.
- Scope: Bug fixes with modules.
- Issue: rdar://130179698&130450351&130424971
- Original PR: 
    -  https://github.com/swiftlang/swift/pull/74672 (reviewed by @jckarter)
    - https://github.com/swiftlang/swift/pull/74743 (reviewed by @jckarter)
- Risk: Low; bug fixes for cases that hadn't come up before.
- Testing: Swift CI + new tests
- Reviewer: see above

### CODE REVIEW

**Comment by kavon** [comment]
@swift-ci test

**Comment by kavon** [comment]
@swift-ci test

**Comment by kavon** [comment]
@swift-ci test

**Comment by kavon** [comment]
@swift-ci test

**Review by jckarter — APPROVED** [review]

**Review by tbkka — APPROVED** [review]

**Pull request merged**
