### PR TITLE
[CMake] Revert recent changes.

### PR DESCRIPTION
**Pull request by gottesmm**
[CMake] Revert recent changes.

These changes caused a number of issues:

1. No debug info is emitted when a release-debug info compiler is built.
2. OS X deployment target specification is broken.
3. Swift options were broken without any attempt any recreating that
functionality. The specific option in question is --force-optimized-typechecker.

Such refactorings should be done in a fashion that does not break existing
users and use cases.

This reverts commit e6ce2ff388a8da3a14882939132ff1b7279b3cde.
This reverts commit e8645f37503202ebdb07e1a725111aa1c13745d6.
This reverts commit 89b038ea7e6db3e289cbd76b8d8a4e4019cd1e96.
This reverts commit 497cac64d9bcd03d80d7aab87ffcf03534afcdf5.
This reverts commit 953ad094da874e5b607eecffeeb0ae2587d48b7c.
This reverts commit e096d1c033a823219b9afe30fb1015d202e2d5e9.

rdar://30549345

### CODE REVIEW

**Comment by gottesmm** [comment]
@llvm-beanz I found these issues this evening. I am reverting since issues 1/3 are holding back engineering work. Feel free to recommit once these issues are fixed.

**Comment by gottesmm** [comment]
@swift-ci Please clean smoke test and merge

**Comment by jrose-apple** [comment]
Looks like it also broke the LTO build. @llvm-beanz, I can send you the link to the LTO bot if you want to see how it's configured.

**Comment by llvm-beanz** [comment]
The broken debug info is caused by an issue I discussed with @gottesmm back in October. Swift's build-script handles the `CMAKE_${LANG}_FLAGS_${BUILD_TYPE}` in non-standard and incorrect ways. I suspect the LTO issue is the same.

I'm re-applying the Export file changes that got reverted here as collateral in PR7529. These should have no impact on the swift build, but without them LLDB/upstream-with-swift no longer builds.

I may have time to fix build-script, but the refactoring changes are less important.

**Pull request merged**
