### PR TITLE
[SILOpt] Fix mutable state in EagerSpecializer

### PR DESCRIPTION
**Pull request by drexin**
rdar://118554892

On the first occurance of a `@_specialize` attribute with `target:` argument, `onlyCreatePrespecializations` would be set to `true`, preventing any subsequent pre-specializations with `exported: false`

### CODE REVIEW

**Comment by drexin** [comment]
@swift-ci smoke test

**Review by eeckstein — APPROVED** [review]
lgtm!

**Review by aschwaighofer — APPROVED** [review]
LGTM. Thank you!

**Comment by drexin** [comment]
@swift-ci smoke test

**Pull request merged**
