### PR TITLE
Embrace operators in types more thoroughly

### PR DESCRIPTION
**Pull request by DougGregor**
#### What's in this pull request?

This pull request starts pushing operators into types within the standard library, covering most of the operators in concrete types (both generic and non-generic). It also starts synthesizing '==' operators for enums as members (rather than as globals), which cleans up a pile of code.
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

A smoke test on macOS does the following:
1. Builds the compiler incrementally.
2. Builds the standard library only for macOS. Simulator standard libraries and
   device standard libraries are not built.
3. lldb is not built.
4. The test and validation-test targets are run only for macOS. The optimized
   version of these tests are not run.

A smoke test on Linux does the following:
1. Builds the compiler incrementally.
2. Builds the standard library incrementally.
3. lldb is built incrementally.
4. The swift test and validation-test targets are run. The optimized version of these
   tests are not run.
5. lldb is tested.

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci Please smoke test and merge

**Comment by gottesmm** [comment]
The failure on the linux bot was due to a workspace issue. I cleared the linux workspace. I guess we need to do a git clean -fd with a flag in update-checkout so when people add tests this does not happen.

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
corelibs Foundation exposed a bug in this code:

TYPE MISMATCH IN ARGUMENT 0 OF APPLY AT expression at [Foundation/NSPathUtilities.swift:248:12 - line:248:20] RangeText="self == ""
  argument value:   %2 = argument of bb0 : $NSString                // users: %22, %18, %5
  parameter type: @owned NSObject
0  swift           0x000000000331ea38 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 40
1  swift           0x000000000331d206 llvm::sys::RunSignalHandlers() + 54
2  swift           0x000000000331f56a
3  libpthread.so.0 0x00007fc1a9644340
4  libc.so.6       0x00007fc1a801bcc9 gsignal + 57
5  libc.so.6       0x00007fc1a801f0d8 abort + 328

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@swift-ci please smoke test Linux and merge

**Comment by DougGregor** [comment]
@swift-ci please smoke test Linux

**Comment by DougGregor** [comment]
That failure makes it look like something didn't actually get rebuilt; the referenced symbol (_TFsoi2eeFTSSSS_Sb) is the global == for String, which this PR removed. Testing locally to make sure this isn't a real issue.

**Pull request merged**
