### PR TITLE
[Demangler] Fix isThunkSymbol() to handle continuations.

### PR DESCRIPTION
**Pull request by al45tair**
`isThunkSymbol()` was returning false for await resume and suspend resume thunks because the `Node` tree for those has an `AsyncAwaitResumePartialFunction` and/or `AsyncSuspendResumePartialFunction` as the first child of the top level `Global`, with the actual thunk in the _second_ child location.

rdar://100424460

### CODE REVIEW

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
TODO: I need to update the `Demangle/demangle.swift` test cases with some examples for this.

**Review by eeckstein — APPROVED** [review]
lgtm.

And yes, please add a test

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
Added some tests and fixed a bug they exposed, which also made the fix simpler :-)

**Pull request merged**
