### PR TITLE
Fixes sparkles typo on FirstPullRequest.md

### PR DESCRIPTION
**Pull request by zaneenders**
Fixes possible typo of trying to use the sparkles emoji.

N/A

### CODE REVIEW

**Review by AnthonyLatsis — APPROVED** [review]

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Comment by AnthonyLatsis** [comment]
I suggest giving the commit message some more attention before merging:
* Capital letter.
* Imperative mood.
* "sparkles" is ambiguous without context; just "typo" and (optionally) the location is optimal in this case.

**Comment by zaneenders** [comment]
Thanks @AnthonyLatsis. How's that?

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Comment by AnthonyLatsis** [comment]
Thank you.

**Pull request merged**
