### PR TITLE
[code-completion] Remove special handling for completion on the RHS of an assignment

### PR DESCRIPTION
**Pull request by nathawes**
This simplifies the code and prevents an assertion failure this code was hitting computing the type relations between the result types and what it determined as the expected type.

Resolves rdar://problem/53958454

### CODE REVIEW

**Comment by nathawes** [comment]
@swift-ci please test

**Comment by nathawes** [comment]
@swift-ci please test

**Comment by nathawes** [comment]
@swift-ci please test

**Review by rintaro — APPROVED** [review]
Nice simplification!

**Comment by nathawes** [comment]
🙇‍♂️ Thanks for suggesting it @rintaro!

**Pull request merged**
