### PR TITLE
Enable verbose logging for LLDB tests when building with Xcode

### PR DESCRIPTION
**Pull request by adrian-prantl**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci smoke test

**Comment by adrian-prantl** [comment]
@swift-ci smoke test

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-lldb/pull/1009
@swift-ci smoke test

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-lldb/pull/1009
@swift-ci smoke test

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-lldb/pull/1009
@swift-ci smoke test

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-lldb/pull/1009
@swift-ci smoke test

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-lldb/pull/1009
@swift-ci smoke test

**Comment by adrian-prantl** [comment]
test with apple/swift-lldb#1009
@swift-ci smoke test

**Comment by adrian-prantl** [comment]
test with apple/swift-lldb#1009
@swift-ci smoke test

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by tkremenek** [comment]
This PR was open before the final `swift-5.0-branch` was cut.  If this was in `master` as of November 16, 2018, then this change was pulled into the final re-branching of Swift 5.  Closing as this PR was opened against an older version of this branch.  If this change should be pulled in, please open a new PR.

**Pull request closed without merging**
