### PR TITLE
[runtime] Remove function pointer hooks from Error implementation.

### PR DESCRIPTION
**Pull request by gparker42**

### CODE REVIEW

**Comment by gparker42** [comment]
@swift-ci please test

**Comment by gparker42** [comment]
@jckarter Do you know of a reason to keep these? The only client of function pointer hooks that I know of is heap debuggers, and they don't need any of these functions.

**Comment by jckarter** [comment]
Would the errorRetain/Release hooks still be useful to heap debuggers if we changed the error format to be different from being just an ObjC object? We'd possibly want to cram small "tagged" error values in there.

**Review by jckarter — APPROVED** [review]
Sure, we could add back whatever hooks future debugging tools need later, they just might not work as well with older runtimes.

**Comment by gparker42** [comment]
I assume that errors that are actually on the heap will ultimately go through either objc's retain/release or swift_retain/swift_release. The debugging tools already patch into those paths so they shouldn't need an additional hook.

**Pull request merged**
