### PR TITLE
[IRGen testing] Fix bogus FileCheck check-prefix "-SAME" usage

### PR DESCRIPTION
**Pull request by davezarzycki**
The correct usage of "-SAME" is after the check-prefix, not in the middle. I've updated the constants to what is emitted today.

This was found during the drafting of: #31811

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by davezarzycki** [comment]
Hi @compnerd – The Windows failure in question might have always been a failure given that the tests were broken until this PR.

**Review by rjmccall — APPROVED** [review]
Thanks, LGTM.

**Comment by compnerd** [comment]
@davezarzycki can I revert this until Ive had a chance to look into the failure?  This is going hide additional possible introduced failures.

**Pull request merged**
