### PR TITLE
[update-checkout] Update swift-crypto to 1.1.5

### PR DESCRIPTION
**Pull request by yim-lee**
[v1.1.5](https://github.com/apple/swift-crypto/releases/tag/1.1.5) contains a fix for cmake build on aarch64

### CODE REVIEW

**Comment by yim-lee** [comment]
@swift-ci test

**Comment by yim-lee** [comment]
@swift-ci Please Test Source Compatibility

**Comment by yim-lee** [comment]
@swift-ci Please test Apple Silicon macOS Platform

**Comment by yim-lee** [comment]
@tomerd @neonichu @shahmishal

**Review by shahmishal — APPROVED** [review]

**Review by tomerd — APPROVED** [review]

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Pull request merged**
