### PR TITLE
update-checkout: use semantic revision

### PR DESCRIPTION
**Pull request by compnerd**
Use the semantic name (v2.1.0-rc1) instead of an explicit ref to make it
easier to identify the revision in use.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test tensorflow

**Comment by marcrasi** [comment]
Sometimes we have to clean test when we change the update-checkout-config.json. I'll try triggering that.

**Comment by marcrasi** [comment]
@swift-ci please clean test tensorflow

**Comment by dan-zheng** [comment]
CI fails with this error:
```
Updating '/home/swiftci/jenkins/workspace/swift-PR-TensorFlow-Linux/swift-tools-support-core'
Error on repo "/home/swiftci/jenkins/workspace/swift-PR-TensorFlow-Linux/swift-tools-support-core": Traceback (most recent call last):
  File "/home/swiftci/jenkins/workspace/swift-PR-TensorFlow-Linux/swift/utils/update_checkout/update_checkout/update_checkout.py", line 91, in update_single_repository
    config, repo_name, scheme_name, scheme_map, cross_repos_pr)
  File "/home/swiftci/jenkins/workspace/swift-PR-TensorFlow-Linux/swift/utils/update_checkout/update_checkout/update_checkout.py", line 58, in get_branch_for_repo
    scheme_branch = scheme_map[repo_name]
KeyError: u'swift-tools-support-core'
```

This error occurs because CI was last triggered for the `tensorflow-merge -> tensorflow` PR https://github.com/apple/swift/pull/28847, which involved changes to `update-checkout-config.json`.

Sometimes, CI machines are left in an incompatible state after testing `tensorflow-merge -> tensorflow` PRs, so a clean test (`@swift-ci Please clean test tensorflow`) is necessary.

This error should naturally go away when https://github.com/apple/swift/pull/28847 is merged soon today. I'd recommend waiting for that PR to be merged before this one.

**Comment by compnerd** [comment]
@swift-ci please clean test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by dan-zheng** [comment]
CI fails:
```
You have bazel 0.26.1 installed.
Please upgrade your bazel installation to version 0.27.1 or higher to build TensorFlow!
```

I'll update bazel on all CI machines now.

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Pull request merged**
