### PR TITLE
Add missing swift-syntax-generated-headers dependencies to ensure SyntaxKind.h is generated before it's used

### PR DESCRIPTION
**Pull request by nathawes**
This is breaking the build.

Resolves rdar://problem/35259197.

### CODE REVIEW

**Comment by nathawes** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
Ah, you found it. Thank you @nathawes

**Comment by nathawes** [comment]
No worries! @DougGregor

**Comment by nathawes** [comment]
The Linux test failure seems unrelated.

**Comment by nathawes** [comment]
@swift-ci please smoke test

**Pull request merged**
