### PR TITLE
Fix some bugs with yields and the large-loadable-types pass

### PR DESCRIPTION
**Pull request by rjmccall**

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please smoke test.

**Comment by rjmccall** [comment]
@swift-ci Please smoke test Linux.

**Comment by rjmccall** [comment]
@swift-ci Please smoke test Linux.

**Comment by rjmccall** [comment]
@swift-ci Please smoke test Linux

**Comment by rjmccall** [comment]
@swift-ci Please test Linux

**Comment by rjmccall** [comment]
@#$&^@#

**Comment by rjmccall** [comment]
Sigh, a time-out.  It's possible that #20342 will land with this as a dependency before this actually lands itself.

**Review by shajrawi — COMMENTED** [review]
LGTM

**Pull request merged**
