### PR TITLE
[IRGen] Support indirect results for coroutines

### PR DESCRIPTION
**Pull request by asl**

### CODE REVIEW

**Comment by asl** [comment]
@swift-ci please test

**Comment by asl** [comment]
preset=buildbot,tools=RA,stdlib=DA
@swift-ci test with preset macOS

**Comment by asl** [comment]
@aschwaighofer @rjmccall ping

**Review by aschwaighofer — APPROVED** [review]
LGTM

**Comment by asl** [comment]
@swift-ci please test

**Comment by asl** [comment]
@swift-ci please smoke test linux platform

**Comment by asl** [comment]
@swift-ci please smoke test

**Comment by asl** [comment]
@swift-ci please smoke test

**Pull request merged**
