### PR TITLE
Fix shebang lines in python scripts

### PR DESCRIPTION
**Pull request by panzarino**
The statement `print "..."` can only be used in python 2, not python 3 (python 3 uses `print()`). This makes sure that the files are executed with python 2 and not python 3 because some users may have python 3 as their default.

### CODE REVIEW

**Comment by modocache** [comment]
Alternatively, we could keep the shebangs as they are, and `from _future_ import print_function`. But I imagine these scripts are not Python 3 compatible in other ways...?

**Comment by modocache** [comment]
`utils/cmpcodesize` also contains two scripts that use the generic `python` shebang. Should those be included in this pull request?

**Comment by gribozavr** [comment]
Unfortunately this approach does not work on OS X, there's no `python2`.

Instead, I would appreciate review help with #90.

**Comment by zachpanz88** [comment]
Sorry I'm running on linux. My bad.

**Pull request closed without merging**
