### PR TITLE
[Preset] New preset to build macOS toolchain without test

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci build toolchain

**Comment by jrose-apple** [comment]
Hm. Why without testing?

**Comment by shahmishal** [comment]
@swift-ci build toolchain

**Comment by shahmishal** [comment]
@jrose-apple This is just to create a new toolchain for evolution proposals. Proposal PR will still require testing, but this way we can split the work on to multiple systems.

**Comment by shahmishal** [comment]
@swift-ci build toolchain

**Comment by shahmishal** [comment]
@swift-ci build toolchain

**Comment by gparker42** [comment]
Is this faster than an ordinary test run? If it is, and it supported Linux, then it could be useful when those of us without Linux machines abuse the CI system to find our Linux compile-time errors.

**Comment by jrose-apple** [comment]
I assume not; an ordinary test run builds fewer things and doesn't try running the tests if the compiler or stdlib build fails.

**Comment by gparker42** [comment]
And in the success case I probably want to continue to the tests anyway. Good point.

**Comment by shahmishal** [comment]
@swift-ci build toolchain

**Comment by gottesmm** [comment]
@shahmishal Cool! On the toolchain download! I think having the ability for swift-ci to provide minimal artifacts (especially in the case of benchmarks) would be awesome!

**Comment by shahmishal** [comment]
@swift-ci smoke test and merge

**Pull request merged**
