### PR TITLE
[stdlib] Change post-nil guarantee for IteratorProtocol.next()

### PR DESCRIPTION
**Pull request by PatrickPijnappel**
#### What's in this pull request?

Swift evolution proposal: https://github.com/apple/swift-evolution/pull/213
Swift evolution thread: http://thread.gmane.org/gmane.comp.lang.swift.evolution/focus=8519
Update from #1544 to resolve conflicts with master.

Changes the guarantee for `IteratorProtocol.next()` to:

``` swift
/// Advance to the next element and return it, or `nil` if no next element
/// exists.  Once `nil` has been returned, all subsequent calls return `nil`.
///
/// - Precondition: `next()` has not been applied to a copy of `self`
///   since the copy was made.
```

All `IteratorType` implementations in the standard library already comply.

### CODE REVIEW

**Comment by lattner** [comment]
SE-0052 is accepted, @dabrahams or @gribozavr, can you please review this?  Thanks!

**Comment by lattner** [comment]
Oh, also @PatrickPijnappel it looks like this patch has conflicts.  Can you please update it when you get a chance?  Thanks!

**Comment by gribozavr** [comment]
The wording LGTM, but I'd like @dabrahams to also take a look.

**Comment by PatrickPijnappel** [comment]
@lattner @gribozavr Ok, resolved the conflicts!
- The first line of the docs in IteratorType next() diverged a bit, but wasn't consistent with the docs for the implementations. I used the original formulation in this commit.
- Also I standardized the docs on 'advances/returns' vs. the 'advance/return' which half of them used (as I understand it the former is the preferred style?).

**Comment by gribozavr** [comment]
CC @natecook1000 for the documentation style.

**Comment by natecook1000** [comment]
The documentation style ('advances'  instead of 'advance') is right on. I think describing the `nil`-returning behavior in the `IteratorProtocol` documentation should be sufficient, though—does that note need to be on every iterator?

This paragraph could use a note about the behavior, too, since it's giving instructions about how to implement an iterator: https://github.com/apple/swift/pull/1702/files#diff-b9ba8d4ad76ba94c1eeabc504d582b57R120

**Comment by dabrahams** [comment]
on Wed May 04 2016, Dmitri Gribenko <notifications-AT-github.com> wrote:

> The wording LGTM, but I'd like @dabrahams to also take a look.

The summary should be a single sentence fragment; see
https://swift.org/documentation/api-design-guidelines/#write-doc-comment

-- 
Dave

**Comment by PatrickPijnappel** [comment]
@natecook1000 I'd say the `nil` behavior and the non-copy requirement are important for consumers of the API, though defintely I agree they should not be in the summary line. I'm out at the moment but will adjust on Monday.

I agree the `nil`

**Comment by PatrickPijnappel** [comment]
@dabrahams Ok moved the guarantee away from the summary, so that's now a single line!

**Comment by dabrahams** [comment]
No such guideline exists.  BTW, I was not saying you should move that information out of the summary (nor was I saying you shouldn’t); if it belongs in the summary you can use a semicolon to join the parts instead of a period.

**Comment by PatrickPijnappel** [comment]
@dabrahams Is there still something blocking this?

**Comment by gribozavr** [comment]
@natecook1000 Could you review, please?

**Comment by natecook1000** [comment]
@gribozavr LGTM

**Comment by gribozavr** [comment]
@swift-ci Please test and merge

**Comment by PatrickPijnappel** [comment]
@gribozavr Build seems to have failed on an unrelated issue.

**Comment by gribozavr** [comment]
Indeed.  What I want to test is that SourceKit tests (which sometimes include snippets of the doc comments) are not affected by this change.

**Comment by gribozavr** [comment]
@swift-ci Please smoke test

**Comment by gribozavr** [comment]
Tests have passed, merging!

**Pull request merged**
