### PR TITLE
Allow final on dynamic members

### PR DESCRIPTION
**Pull request by aschwaighofer**
Dynamic is about dynamically replacing a method implementiation not
overriding.

rdar://49535048

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
Hmm, I missed a digit in the radar number: rdar://49535048

**Comment by aschwaighofer** [comment]
@swift-ci Please test os x platform

**Review by slavapestov — COMMENTED** [review]
Why is this gated on -swift-version 5?

**Comment by aschwaighofer** [comment]
```
class C {
  @objc
  final dynamic func foo() {
  }
}
```
Used to be an error.

**Comment by aschwaighofer** [comment]
@swift-ci please test macOS

**Comment by slavapestov** [comment]
We don’t require a swift version check when loosening existing restrictions. Also we already shipped swift 5 and it wouldn’t make sense to introduce new behavior changes in -swift-version 5 anyway. I would just make this unconditional and remove the diagnostic.

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
Thank you for revising, new version looks good.

**Pull request merged**
