### PR TITLE
[Sema][Diagnostics][SR-14644] Improving diagnostics for key path with invalid components

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
This just adjust the `hasSingleInvalidComponent` key path expr method to only consider key path rooted on type expr because we only want to detect key paths without components e.g. `\Int` because actually key paths with invalid components like the SR example `\Int.byteSwapped.signum()` are represented in the AST also with a single invalid component but rooted on the whole expression. Also skips the fix for hole root key path if it has any invalid component as it would be already diagnosed.

Resolves SR-14644.

### CODE REVIEW

**Review by xedin — APPROVED** [review]
LGTM!

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test macOS platform

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test macOS platform

**Pull request merged**
