### PR TITLE
[SourceKit] While indexing, give accessors distinguishable names. rdar://28395479

### PR DESCRIPTION
**Pull request by nkcsgexi**
rdar://problem/28395479

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by jrose-apple** [comment]
I'm not particularly happy with these particular names. Every part of the compiler seems to do this differently, but set with no arguments in particular is definitely a lie.

**Comment by jrose-apple** [comment]
If these are names shown to users it matters even more that they reflect the syntax of the actual language. I would say that makes dot syntax inappropriate. :-/

**Comment by nkcsgexi** [comment]
@jrose-apple What do you think are the right names for these accessors (for presentation reasons only)? I'm happy to update to a more accurate version. Something like:
`get()`, `set(value:)`, `didSet(oldValue:)` and `willSet(newValue:)`?
These also improve the discoverability of these variables.

**Comment by jrose-apple** [comment]
Hm. Maybe just "someProp get", "someProp willSet", "subscript(_:) set" etc. (I though about "getter for someProp", but I think that would look funny in the list alongside regular method names.) @natecook1000 may also have some ideas.

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci  please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
`#selector` uses `getter:propName` and `setter:propName`. I think we should standardize on that, if we have to spell these.

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Pull request merged**
