### PR TITLE
Move more Standard Library options to dedicated file

### PR DESCRIPTION
**Pull request by edymtt**
This addresses most of the options with computed defaults.

Addresses rdar://86723940

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci please smoke test

**Comment by edymtt** [comment]
@swift-ci please test Apple Silicon

**Comment by edymtt** [comment]
@swift-ci please build toolchain

**Comment by edymtt** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by edymtt** [comment]
@swift-ci Please ASAN test

**Review by compnerd — APPROVED** [review]
This movement is fine, but it does make me wish for the names being more consistent internally.  That is not your fault, and definitely beyond the scope of this change, but if you so feel inclined (as a separate change) ... ;-).

Also, thank you for taking the time to move the default value computation next to the option, I think that it makes this so much easier for longer term maintenance.

**Comment by edymtt** [comment]
@swift-ci please smoke test

**Comment by edymtt** [comment]
@swift-ci please test Apple Silicon

**Comment by edymtt** [comment]
@swift-ci please build toolchain

**Comment by edymtt** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by edymtt** [comment]
`stdlib_S_standalone_minimal_macho_x86_64,build,test` passed -- https://ci.swift.org/job/swift-PR-stdlib-with-toolchain-osx-preset/100/

**Comment by edymtt** [comment]
preset=stdlib_S_standalone_darwin_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by edymtt** [comment]
@swift-ci please test Windows

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by edymtt** [comment]
The Windows failure seems unrelated to this changes, since it's happening in the incremental bot as well -- e.g. https://ci-external.swift.org/job/oss-swift-windows-x86_64-vs2019/7549/

```
[950/958] Linking CXX executable bin\lldb-server.exe
FAILED: bin/lldb-server.exe 
cmd.exe /C "cd . && "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_exe --intdir=tools\lldb-server\CMakeFiles\lldb-server.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100177~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100177~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1429~1.300\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\lldb-server.rsp  /out:bin\lldb-server.exe /implib:lib\lldb-server.lib /pdb:bin\lldb-server.pdb /version:0.0 /INCREMENTAL:NO /STACK:10000000 /INCREMENTAL:NO /subsystem:console  && cd ."
LINK: command "C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1429~1.300\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\lldb-server.rsp /out:bin\lldb-server.exe /implib:lib\lldb-server.lib /pdb:bin\lldb-server.pdb /version:0.0 /INCREMENTAL:NO /STACK:10000000 /INCREMENTAL:NO /subsystem:console /MANIFEST /MANIFESTFILE:bin\lldb-server.exe.manifest" failed (exit code 1181) with the following output:
LINK : fatal error LNK1181: cannot open input file 'swiftCompilerModules.lib'
```

**Comment by edymtt** [comment]
Linux runs are hitting the same failure as e.g. https://ci.swift.org/view/Packages/job/oss-swift-package-linux-ubuntu-16_04/6820/console

```
18:05:11 RuntimeError: Found a load command that loads something executable and writeable
18:05:11 
18:05:11 error: command failed with exit status: 1
18:05:11 
18:05:11 --
18:05:11 
18:05:11 ********************
18:05:11 Testing:  0.. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90.. 
18:05:11 ********************
18:05:18 Failed Tests (1):
18:05:18   swift-package-tests :: test-snapshot-binaries/linux_load_commands.py
```

**Comment by edymtt** [comment]
@swift-ci please build macOS toolchain

**Comment by edymtt** [comment]
@swift-ci please build toolchain macOS

**Comment by edymtt** [comment]
@swift-ci please test Linux

**Comment by edymtt** [comment]
@swift-ci please build toolchain Linux

**Comment by edymtt** [comment]
@swift-ci please build toolchain Linux platform

**Comment by edymtt** [comment]
@compnerd for now I made a note about renaming, not sure if/when I will be able to get to that

**Pull request merged**
