### PR TITLE
[Performance diagnostics] Enable checking of throw instructions

### PR DESCRIPTION
**Pull request by DougGregor**
When performance diagnostics were introduced, typed throws didn't exist
so it was not generally possible to have throws anywhere without
triggering performance diagnostics. As a short term hack, we disabled
checking of `throw` instructions and the basic blocks that terminate
in a `throw`.

Now that typed throws is available and can be used to eliminate
allocations with error handling, remove all of the hacks. We'll now
diagnose attempts to throw or catch existential values (e.g., the `any
Error` used for untyped throws), but typed throws are fine.

### CODE REVIEW

**Comment by DougGregor** [comment]
This builds on https://github.com/swiftlang/swift/pull/77748. That PR made typed throws avoid allocations in practice, lifting a restriction. This PR removes the hack that allowed untyped throws through the performance-annotation checker, even though they would allocate. So this PR tightens up performance annotation checking in a way that may reject existing code (that should always have been rejected).

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Review by eeckstein — COMMENTED** [review]
Please remove the declaration of `neBlocks`, too. And at that occasion also in `visitFunctionEmbeddedSwift`.
You can remove the `NonErrorHandlingBlocks` utility at all. It's not used anywhere else and we will not need it anymore - at least not in C++.

**Comment by DougGregor** [comment]
Rebased on top of https://github.com/swiftlang/swift/pull/77780, removed `NonErrorHandlingBlocks`.

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Review by eeckstein — APPROVED** [review]
lgtm, thanks!

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test macOS

**Pull request merged**
