### PR TITLE
[Driver] Default SDKROOT to / on FreeBSD.

### PR DESCRIPTION
**Pull request by dcci**
#### What's in this pull request?

https://github.com/apple/swift/pull/1048, now with tests.
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

This is needed for the testusuite to run correctly.

### CODE REVIEW

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by dcci** [comment]
Tests passed. Can I go forward and try my new magic superpower (and commit) ?
Thanks!

--
Davide

**Comment by lattner** [comment]
SGTM so long as @gribozavr approves :-)

**Comment by gribozavr** [comment]
@dcci Go for it :)

**Comment by gribozavr** [comment]
@dcci Sorry, I reverted your PR because because the test fails on OS X 10.10, which does not support `env -u`.

**Pull request merged**
