### PR TITLE
Add insert-bb tool to utils

### PR DESCRIPTION
**Pull request by beccadax**
This is a little script I wrote to help with SIL diffing. It prints a modified version of its SIL input which adds a new basic block containing only “placeholder”—but more importantly, it updates all references to existing higher-numbered basic blocks. This can help to reduce the amount of noise in SIL diffs without removing any information from the file.

### CODE REVIEW

**Comment by gottesmm** [comment]
Can you use python instead of perl? I don't think we have any other perl scripts in the codebase.

**Comment by brentdax** [comment]
We do have *one* in utils/, but point taken. I'll rewrite it when I have a little time.

**Comment by gottesmm** [comment]
Thanks! What is the one in utils? (If I get bored, I may just fix that).

**Comment by gottesmm** [comment]
or I guess I can look myself = p. Thanks!

**Comment by CodaFi** [comment]
@brentdax Is this something you still want to pursue, or should I turn it into an SR and let somebody else take it?

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
