### PR TITLE
[Docs] Fix a typo in docs/WindowsCrossCompile.md

### PR DESCRIPTION
**Pull request by spencerkohan**
The line: "how to cross compile Swift on Windows" should read "how to cross compile Swift for Windows".  I believe this is a typo.

### CODE REVIEW

**Comment by spencerkohan** [comment]
@swift-ci Please smoke test

**Comment by compnerd** [comment]
I think that they both make sense.  BTW, you need to be authorized to perform the test runs :-)

**Comment by compnerd** [comment]
@swift-ci please smoke test and merge

**Comment by RUSshy** [comment]
Can we have snapshot builds for windows please ? 

https://swift.org/download/#snapshots

**Pull request merged**
