### PR TITLE
[benchmark] Add binary floating-point properties benchmarks

### PR DESCRIPTION
**Pull request by xwu**
It's been reported that certain properties such as `nextUp` are hundreds of times slower than they need to be. This PR adds some benchmarks in preparation for fixing the issue.

### CODE REVIEW

**Comment by xwu** [comment]
@swift-ci Please smoke benchmark

**Comment by xwu** [comment]
@swift-ci Please smoke benchmark

**Comment by xwu** [comment]
@swift-ci Please smoke benchmark

**Comment by xwu** [comment]
@stephentyrone The generic floating-point conversion initializers use `nextUp` to decide when rounding is tied. Since we're going to be using them a lot more now and no one's picked up the starter bug, I'm just going to go ahead and speed up the whole lot of them.

**Comment by xwu** [comment]
@swift-ci Please smoke test Linux platform

**Comment by xwu** [comment]
@swift-ci Please smoke test Linux platform

**Comment by xwu** [comment]
@swift-ci Please smoke test Linux platform

**Comment by xwu** [comment]
@swift-ci Please smoke benchmark

**Comment by xwu** [comment]
@swift-ci Please smoke benchmark

**Comment by xwu** [comment]
@swift-ci Please smoke benchmark

**Review by stephentyrone — APPROVED** [review]
LGTM.

**Comment by xwu** [comment]
@swift-ci Please smoke test and merge

**Comment by xwu** [comment]
@swift-ci Please smoke test and merge

**Comment by xwu** [comment]
@swift-ci Please smoke test and merge

**Pull request merged**
