### PR TITLE
[Docs] Add note for intel users when setting up clion

### PR DESCRIPTION
**Pull request by 0x41c**
This pull request addresses any hassle that an intel user might face while following the already-written documentation on setting up CLion to work with swift. This was added because while following the documentation, a new user (such as myself) might get confused as to why their llvm or clang build isn't showing up.

### CODE REVIEW

**Review by ktoso — APPROVED** [review]
Sounds good, thanks for adding the note!

**Comment by ktoso** [comment]
@swift-ci please smoke test and merge

**Comment by 0x41c** [comment]
Tests failed due to an unrelated issue.

**Comment by 0x41c** [comment]
@ktoso Could you run swift-ci again and see if the merge fixed it?

**Comment by ktoso** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
