### PR TITLE
[Foundation] Address a potential leak when writing a data to a URL and the file system representation fails

### PR DESCRIPTION
**Pull request by phausler**
Resolves <rdar://problem/36889982>

### CODE REVIEW

**Comment by phausler** [comment]
@swift-ci please smoke test

**Comment by gottesmm** [comment]
@phausler Is it possible for you to make a test case that goes down that path? I will see if I can jerry-rig something for you vis-a-vis the leaks checking.

**Comment by phausler** [comment]
I have a hunch on how to trigger it but it will require some subclassing shenanigans with NSURL. From what I can tell this cannot happen on Darwin platforms with properly constructed urls.

**Comment by gottesmm** [comment]
Ok. Nm then.

**Review by parkera — APPROVED** [review]

**Pull request merged**
