### PR TITLE
Implicitly set -enable-lexical-lifetimes=false for the Swift standard library

### PR DESCRIPTION
**Pull request by DougGregor**
Older compilers cannot handle this flag.

Fixes rdar://88605521

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Review by nate-chandler — APPROVED** [review]
Thank you!

**Comment by DougGregor** [comment]
Closing out this egregious hack. The proper fix was https://github.com/apple/swift/pull/41261

**Pull request closed without merging**
