### PR TITLE
[ConstraintLocator] Add generic signature to `OpenedGeneric` element

### PR DESCRIPTION
**Pull request by xedin**
This information is useful for requirement diagnostics, because
generic signature represents the source of generic requirements.

### CODE REVIEW

**Review by DougGregor — APPROVED** [review]
LGTM, thank you!

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Pull request merged**
