### PR TITLE
When SWIFT_ENABLE_REFLECTION is Off, don't build the reflection runtime code (stdlib/public/Reflection/*.cpp)

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by kubamracek** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Review by compnerd — APPROVED** [review]
I don't know how to fix the one thing I noticed - the commit message.  I had to read it three times before it got through my head what you were trying to do.  I suspect that others will want this functionality as well.

**Review by mikeash — APPROVED** [review]

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
Fixing commit message / PR title.

**Review by adrian-prantl — APPROVED** [review]

**Pull request merged**
