### PR TITLE
Improve handling of copy_value and destroy_value in MemoryBehaviorVisitor

### PR DESCRIPTION
**Pull request by meg-gupta**
- Also, compute use points for destroy_value
- Cleanup explicit checks for refcount instructions in RLE

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci benchmark

**Comment by meg-gupta** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
This needs tests.

**Comment by meg-gupta** [comment]
@gottesmm  Added tests

**Comment by meg-gupta** [comment]
@swift-ci test

**Review by eeckstein — APPROVED** [review]
lgtm!

**Comment by meg-gupta** [comment]
@swift-ci smoke test OS X Platform

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test Linux Platform

**Pull request merged**
