### PR TITLE
Improve the performance of IRGenDebugInfo.

### PR DESCRIPTION
**Pull request by adrian-prantl**
This commit changes how inline information is stored in SILDebugScope
from a tree to a linear chain of inlined call sites (similar to what
LLVM is using). This makes creating inlined SILDebugScopes slightly
more expensive, but makes lowering SILDebugScopes into LLVM metadata
much faster because entire inlined-at chains can now be cached. This
means that SIL is no longer preserve the inlining history (i.e., ((a
was inlined into b) was inlined into c) is represented the same as (a
was inlined into (b was inlined into c)), but this information was not
used by anyone.

On my late 2012 i7 iMac, this saves about 4 seconds when compiling the
RelWithDebInfo x86_64 swift standard library — or 40% of IRGen time.

rdar://problem/28311051
rdar://problem/27658378

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
osx build failed because of an unrelated error in ClangImporter.

**Comment by adrian-prantl** [comment]
Likely: https://github.com/apple/swift/pull/8534

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by slavapestov** [comment]
Awesome!

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
LLDB TestSwiftStepping.TestSwiftStepping failed on Linux but the generated DWARF is identical.
Oh, it looks like that test is broken on master as well:
https://ci.swift.org/job/oss-lldb-incremental-linux-ubuntu-16_04/

**Comment by adrian-prantl** [comment]
@swift-ci smoke test linux platform and merge

**Comment by adrian-prantl** [comment]
@swift-ci smoke test linux platform and merge

**Comment by adrian-prantl** [comment]
@swift-ci smoke test Linux Platform

**Comment by adrian-prantl** [comment]
@swift-ci smoke test and merge

**Comment by adrian-prantl** [comment]
timeout in swiftpm tests!?

**Comment by adrian-prantl** [comment]
@swift-ci smoke test linux platform and merge

**Comment by adrian-prantl** [comment]
@swift-ci smoke test and merge

**Pull request merged**
