### PR TITLE
Mark swift sections as swift4 for Swift 4.2

### PR DESCRIPTION
**Pull request by aschwaighofer**
rdar://36363251

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
The formats of these sections still changed, and the version bump is intended to ensure that tools that expect the old formats don't see the new formats. Did we ship any previous compilers with these section names?

**Comment by bob-wilson** [comment]
On the swift-4.1-branch, "git grep swift4_" shows nothing using that prefix. The names were all "swift2_" or "swift3_" until recently.

**Comment by aschwaighofer** [comment]
@jckarter We never have used the swift4 prefix. It used to be swift2/3 (e.g in swift-4.1-branch) before the change to swift5. This change is intended for disambiguation between swift 4.2 and later.

**Comment by bob-wilson** [comment]
Does this change need to be coordinated with LLDB?

**Comment by bob-wilson** [comment]
@dcci ?

**Comment by aschwaighofer** [comment]
I don't think so. ``$ cd lldb; git grep swift5`` returns nothing relevant. I don't remember fallout when I changed the prefix to swift5. I do not see a relevant commit in stable within the two weeks i committed the swift5 change.

**Comment by aschwaighofer** [comment]
AFAICT the smoketest preset 'buildbot_incremental,tools=RA,stdlib=RD,smoketest=macosx' runs lldb tests so the PR #15238 should also test lldb.

``
/Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-swift-4.2-branch/swift/utils/build-script --test --validation-test --lit-args=-v --compiler-vendor=apple --reconfigure --verbose-build --build-ninja --build-swift-stdlib-unittest-extra --lldb --lldb-no-debugserver --lldb-use-system-debugserver --lldb-build-type=Release --lldb-test-swift-only --lldb-assertions --build-subdir=buildbot_incremental --release --assertions --test --validation-test --llvm-targets-to-build=X86 --compiler-vendor=apple --reconfigure --verbose-build --build-ninja --build-swift-stdlib-unittest-extra --swift-stdlib-build-type=RelWithDebInfo --swift-stdlib-enable-assertions=true --skip-build-ios --skip-test-ios --skip-build-tvos --skip-test-tvos --skip-build-watchos --skip-test-watchos --stdlib-deployment-targets=macosx-x86_64 --swift-primary-variant-sdk=OSX --swift-primary-variant-arch=x86_64 --skip-build-benchmarks
``

**Pull request merged**
