### PR TITLE
[ownership] Move SemanticARCOpts into a separate folder in preparation for splitting into multiple small pseudo-passes.

### PR DESCRIPTION
**Pull request by gottesmm**
SemanticARCOpts keeps on growing with various optimizations attached to a single
"optimization" manager. Move it to its own folder in prepation for splitting it
into multiple different optimizations and utility files.

### CODE REVIEW

**Comment by gottesmm** [comment]
@atrick just what we talked about.

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by atrick** [comment]
thanks

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Pull request merged**
