### PR TITLE
[5.1 04-29-19] [stdlib] Revise CollectionDifference documentation

### PR DESCRIPTION
**Pull request by natecook1000**
This is a cherry pick of #24675.

### CODE REVIEW

**Comment by natecook1000** [comment]
@swift-ci Please test

**Comment by natecook1000** [comment]
@swift-ci Please test Linux platform

**Comment by natecook1000** [comment]
@swift-ci Please test Linux platform

**Comment by brentdax** [comment]
@swift-ci Please test Linux platform

**Comment by natecook1000** [comment]
@swift-ci Please test Linux platform

**Comment by brentdax** [comment]
@natecook1000 Please message me when you merge this.

**Comment by brentdax** [comment]
Should be unblocked by apple/swift-corelibs-foundation#2252.

**Comment by brentdax** [comment]
@swift-ci please test linux platform

**Review by airspeedswift — APPROVED** [review]
Approving since it's comments only.

**Pull request merged**
