### PR TITLE
Fix test/stdlib/VarArgs.swift on the minimal/standalone bot

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test stdlib with toolchain

**Comment by kubamracek** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Review by compnerd — APPROVED** [review]
Might be nice to associate a SR/rdar to clean this up?  Or do you think that we will need to live with this forever?  If so, maybe we should introduce a separate helper library and inject that via a lit macro.

**Pull request merged**
