### PR TITLE
Bump `wasi-libc` to `wasi-sdk-24` in `update-checkout-config.json`

### PR DESCRIPTION
**Pull request by kateinoigakukun**
wasi-libc 23 and later includes a critical fix under multithreads https://github.com/WebAssembly/wasi-libc/commit/887613873d839decf16ccc5277a03f09678a93a4

### CODE REVIEW

**Comment by kateinoigakukun** [comment]
@swift-ci test WebAssembly

**Comment by kateinoigakukun** [comment]
@swift-ci smoke test

**Comment by kateinoigakukun** [comment]
@swift-ci test WebAssembly

**Comment by kateinoigakukun** [comment]
@swift-ci smoke test

**Comment by kateinoigakukun** [comment]
@swift-ci smoke test

**Review by shahmishal — APPROVED** [review]

**Pull request merged**
