### PR TITLE
Read machO sections section by section

### PR DESCRIPTION
**Pull request by augusto2112**
This changes how ReflectionContext reads machO reflection sections by reading them individually instead of as one big memory block spanning from the first to the last section (and including whatever else is in between). This change will enable an optimization on LLDB's side where, if we're reading read-only data, we read from the file-cache instead of the child process, which should speed up debugging when working with remote processes.

(cherry picked from commit b54d42653e7b07a9eb5d9213bb405857242bcb35)

### CODE REVIEW

**Comment by augusto2112** [comment]
@adrian-prantl I merged the PR I opened last week (https://github.com/apple/swift/pull/37043) to main, since I didn't know we were supposed to work on release/5.5 now. This just cherry-picks those changes.

**Comment by augusto2112** [comment]
@swift-ci please test

**Review by adrian-prantl — APPROVED** [review]

**Comment by augusto2112** [comment]
Linux failing test:
```
18:28:17 Failed Tests (1):
18:28:17   Swift(linux-x86_64) :: AutoDiff/compiler_crashers_fixed/rdar71191415-nested-differentiation-of-extension-method-optimized.swift
```

I believe the failing test is unrelated to the changes on this commit, as they should only affect macOS.

**Comment by augusto2112** [comment]
@swift-ci please test

**Pull request merged**
