### PR TITLE
Clean up SILGen's noescape closure implementation

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes <rdar://problem/38545956>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Review by aschwaighofer — COMMENTED** [review]
Nice!

**Pull request merged**
