### PR TITLE
Delete ReferencedNameTracker

### PR DESCRIPTION
**Pull request by CodaFi**
The `DependencyRecorder` has grown a mapping from primaries to sets of `Reference`s they consume. This removes the last reason we had for keeping the `ReferencedNameTracker` abstraction around.

While we're here, put the `UsedDeclEnumerator` back in its place - it turns out to have hidden information from the dependency verifier and reported incorrect cascading information. On top of that, we no longer have to go through the mangle->demangle->copy dance when producing keys in the dependency verifier. Instead, just use the ASTPrinter to print out the fully-qualified declared interface type of each subject. This explains e.g. the change from `__C` to `ObjectiveC`.

Once we cut over to private dependencies, we can delete everything with the word "cascading" in it - and also get the dependency graph out of the business of using access control levels to add implementation/interface edges which we know to be incorrect.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci test compiler performance

**Comment by CodaFi** [comment]
@swift-ci clean test macOS

**Comment by CodaFi** [comment]
Not sure if this works

@swift-ci clean test compiler performance

**Review by davidungar — APPROVED** [review]
Didn't burrow down into the details, but it looks fine to me.

**Pull request merged**
