### PR TITLE
Remote reflection fixes (3.0)

### PR DESCRIPTION
**Pull request by slavapestov**
- Description: This PR fixes a couple of issues that were observed with the remote mirrors library. In particular the fix for multi-threaded IRGen mode is important for building with WMO and running with Instruments.
- Scope of the issue: Affects anyone using remote mirrors.
- Risk: Low.
- Reviewed by: @bitjammer or @rjmccall 
- Tested: new tests added
- Radars: rdar://problem/27359445 and rdar://problem/27906876.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test macOS

**Comment by slavapestov** [comment]
@swift-ci Please test macOS

**Comment by slavapestov** [comment]
This is ready for review -- @bitjammer or @rjmccall, do you mind taking a look?

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
This is ready for review - @bitjammer and @rjmccall, can you take a look?

**Comment by bitjammer** [comment]
Looks reasonable to me.

**Pull request merged**
