### PR TITLE
Comment the new code that diagnoses noescape recursion.

### PR DESCRIPTION
**Pull request by atrick**
This used to be done in Sema. It's a special rule required for
exclusivity that is totally non-obvious. Explain what the code is
doing.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci smoke test and merge.

**Review by slavapestov — APPROVED** [review]

**Comment by atrick** [comment]
@swift-ci smoke test and merge.

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
(just doing a drive by to help ci along)

**Pull request merged**
