### PR TITLE
Rename Mac Catalyst-related test

### PR DESCRIPTION
**Pull request by beccadax**
Fixes rdar://62338598

### CODE REVIEW

**Comment by brentdax** [comment]
@swift-ci please smoke test

**Review by nkcsgexi — APPROVED** [review]

**Comment by brentdax** [comment]
@swift-ci please smoke test macOS platform

**Comment by brentdax** [comment]
@swift-ci please smoke test macOS platform

**Comment by brentdax** [comment]
@swift-ci please smoke test macOS platform

**Comment by brentdax** [comment]
@swift-ci please smoke test macOS platform

**Comment by brentdax** [comment]
@swift-ci please smoke test macOS platform

**Comment by compnerd** [comment]
@brentdax this broke the windows builder (the path is far too long).

**Pull request merged**
