### PR TITLE
Release node factory storage after each demangling operation

### PR DESCRIPTION
**Pull request by tbkka**
This adds missing clear() operations to a number of places in
RemoteMirror in order to reclaim memory after (de)mangling results
are no longer needed.

Before this, the RemoteMirror library had an unfortunate tendency to use
excessive amounts of memory as the demangler kept appending data to its
internal slab allocator.

Resolves rdar://72958641

### CODE REVIEW

**Review by mikeash — APPROVED** [review]
Looks good. Thanks for taking care of this.

**Comment by airspeedswift** [comment]
Is this GTM?

**Comment by tbkka** [comment]
Not yet Good To Merge.  Testing showed a few remaining issues to track down.

**Comment by tbkka** [comment]
Made an additional change to ensure that we track all enum cases, even if their payload types cannot be fully resolved.  (Why the payload type can't be fully resolved for some cases is a different question that will need further investigation.)

**Comment by mikeash** [comment]
@tbkka Is this new change meant to address the weird results from enums with CF types as associated values (rdar://74729349), or is that a happy coincidence?

**Comment by tbkka** [comment]
@mikeash That would be a happy coincidence, I think.  I was just poking at another strange crash.

**Comment by mikeash** [comment]
I ran my test case against your changes and it seems to have fixed most of them. There's one case that's not happy, I'll see if I can make that work.

**Comment by tbkka** [comment]
@swift-ci Please test

**Comment by tbkka** [comment]
@swift-ci Please test

**Comment by tbkka** [comment]
@swift-ci Please test Windows platform

**Pull request merged**
