### PR TITLE
[6.0] Support closures that capture opened pack element types

### PR DESCRIPTION
**Pull request by slavapestov**
Partial 6.0 cherry-pick of https://github.com/apple/swift/pull/73712 and previous PRs.

* **Description**: Closures can capture values of pack element type, which are introduced by a `repeat` expression or a `for ... in repeat` loop. For example, here we accidentally capture a pack element type, because `&&` takes an autoclosure:
  ```
  protocol P { var foo: Bool { get } }

  func f<each T: P>(_ ts: repeat each T) {
    for t in repeat each ts {
      _ = true && t.foo
    }
  }
  ```
  This would cause crashes and type checking errors. This PR implements the SIL lowering support for closures that capture pack elements. Some solver support is incomplete, however a bunch of cases now work.

* **Scope of the issue**: Affects many users, and is even easier to hit now with `for ... in repeat` loops.

* **Origination**: This never worked.

* **Risk**: I believe **Low** for code that doesn't use packs, **Medium** for code using packs. There's a bunch of stuff here:
  * I redid ASTVerifier support for local archetypes. This is off in an noassert build.
  * I changed the HasArchetype bit in TypeBase into HasPrimaryArchetype and added a hasPrimaryArchetype() predicate to test it, but the existing hasArchetype() predicate has the same behavior as before. I only updated a few callers to use the new hasPrimaryArchetype().
  * There are some new assertions. I made a workaround in autodiff to simulate the old noassert behavior in a narrow case
  * Capture analysis now tracks uses of local archetypes. Any existing code that didn't crash before should end up getting an empty list of local archetype captures here. But a logic error might break existing code that uses packs.
  * Type lowering now consults the list of captured archetypes. If it's not empty, a bunch of new code runs to build a new generic signature, extend the substitution map for the call, etc. I hooked this into the existing mechanism which drops the generic signature for a closure in generic context that has no generic captures. It should all short-circuit trivially if the list of captured archetypes is empty.
  * There is a new pass that runs after SILGen to rewrite SIL instructions in a non-trivial way. This pass only runs if there were captured local archetypes.
  * There's a representation change for variables declared within the scope of a `for ... in repeat` loop. Some extra book-keeping that used to exist is now subsumed into my new logic. This might break existing code, but pack iteration is a new feature in 6.0. This change was separately reviewed on `main` by @simanerush.
  * For the most part validation tests pass at each intermediate commit so it should be easy to bisect any regressions.

* **Reviewed by**: review pending - @hborla @rjmccall @simanerush 

* **Radar**: rdar://113505724, rdar://122293832, rdar://124329076.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
Since my SILCloner refactoring is on 6.0 this needs some minor adjustments in the new SILGenLocalArchetype.cpp transform. I’ll just copy the code over

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by eeckstein** [comment]
I reviewed https://github.com/apple/swift/pull/73541/commits/28fd20c4025df60e459e9bd1baca5e23570b257c and https://github.com/apple/swift/pull/73541/commits/f6d67743e7cf3d139396a413c42dc5db951b27a3#diff-9bcf6c807c755531489d2fbe8aeaa54308636dd1879f26a6d7917f08f6a5fb55R130-R152: LGTM

**Comment by slavapestov** [comment]
(swift-distributed-actors fails with the same error in the baseline source compat run)

**Comment by slavapestov** [comment]
@swift-ci Please test

**Review by hborla — APPROVED** [review]

**Pull request merged**
