### PR TITLE
Remove the "shrink" part of the solver.

### PR DESCRIPTION
**Pull request by rudkx**
At one point this phase was providing a lot of value in reducing the
number of expressions we ultimately decided were too complex, but at
this point it doesn't seem to be helping very often.

Based on experimenting with some of our slow test cases, in several
cases it actually increases the amount of work we do before we decide
an expression is too complex, sometimes making it take 2-3x longer.

I will open a bug to track restoring the two expressions that we are
now "too complex" on, so that the tests can be restored once we fix
some of the underlying problems.

### CODE REVIEW

**Comment by rudkx** [comment]
The source compatibility suite failures are unrelated to my changes and are all happening on the builders.

**Review by xedin — COMMENTED** [review]
Changes looks good to me, but from souce compatibility perspective `Kitura` and `SPR` now both fail with “too complex” expressions...

**Comment by rudkx** [comment]
@xedin Ah, I missed that in all the noise, and was waiting on https://github.com/apple/swift-source-compat-suite/pull/218 before re-running.

I'll take a look.

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
It's easy enough to rip this out when the time comes. There are conflicts with this PR, so I'll close and re-do later.

**Pull request closed without merging**
