### PR TITLE
AllocBoxToStack: Improve alloc_stack/dealloc_stack scoping

### PR DESCRIPTION
**Pull request by eeckstein**
Instead of inserting all alloc_stack/dealloc_stack instructions at the begin/end of the function, insert them at the actual lifetime boundaries.

rdar://problem/16723128

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci Please smoke test

**Comment by eeckstein** [comment]
@swift-ci Please smoke benchmark

**Comment by gottesmm** [comment]
+1! = D

Michael

**Comment by eeckstein** [comment]
@swift-ci Please smoke test and merge

**Comment by eeckstein** [comment]
@swift-ci Please smoke test and merge

**Comment by eeckstein** [comment]
@swift-ci Please smoke test and merge

**Comment by eeckstein** [comment]
@swift-ci Please smoke test and merge

**Pull request merged**
