### PR TITLE
Remove SwiftExperimental

### PR DESCRIPTION
**Pull request by CodaFi**
See [here](https://lists.swift.org/pipermail/swift-dev/Week-of-Mon-20170717/004953.html) for discussion.  This should not be merged until we come to a consensus about what to do with this library.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please clean test

**Comment by CodaFi** [comment]
Internal consensus is that the target should be removed but the operators distributed into parse/typechecking tests.

**Comment by CodaFi** [comment]
@swift-ci please clean test

**Comment by CodaFi** [comment]
@swift-ci please clean test

**Review by moiseev — APPROVED** [review]
:shipit:

**Review by dabrahams — APPROVED** [review]
Assuming some consensus was reached about what to do with the code, and @moiseev approves, so do I.

**Review by airspeedswift — APPROVED** [review]

**Comment by CodaFi** [comment]
Thanks all!

⛵️

**Comment by CodaFi** [comment]
@swift-ci please test and merge

**Pull request merged**
