### PR TITLE
[AutoDiff] Add a missing cleanup for a zero value with differentiating 'store'.

### PR DESCRIPTION
**Pull request by rxwei**
Zeros emitted when differentiating a `store` needs to be cleaned up.

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
Adding a test.

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Review by dan-zheng — APPROVED** [review]
Nice! Leak counts in `test/AutoDiff/leakchecking.swift` are unchanged?

**Comment by rxwei** [comment]
They are unchanged. More tests coming.

**Pull request merged**
