### PR TITLE
Sema: Ban shadowing generic parameters from outer scopes

### PR DESCRIPTION
**Pull request by slavapestov**
Code like that is usually indicative of programmer error, and does not round-trip through module interface files since there is no source syntax to refer to an outer generic parameter.

For source compatibility this is a warning, but becomes an error with -swift-version 6.

Fixes rdar://problem/108385980 and https://github.com/apple/swift/issues/62767.

### CODE REVIEW

**Review by xedin — COMMENTED** [review]
Could you please add a test for this changes?

**Comment by slavapestov** [comment]
@xedin Yep, I forgot to `git add` the file :)

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Pull request merged**
