### PR TITLE
Typed throws ABI revert

### PR DESCRIPTION
**Pull request by aschwaighofer**

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci test

**Comment by nate-chandler** [comment]
@swift-ci please test windows platform

**Comment by tbkka** [comment]
The Typed Throws ABI still has a lot of issues.  I agree with reverting it until we can work through those.

**Review by tbkka — APPROVED** [review]

**Comment by aschwaighofer** [comment]
The failures on windows seem related to a broken bot -- nothing in this PR touches how we copy an array in the runtime.

Looks like maybe the disk is full or something.

```
FAIL: Swift-Unit :: runtime/./SwiftRuntimeTests.exe/3/61 (11052 of 11118)
******************** TEST 'Swift-Unit :: runtime/./SwiftRuntimeTests.exe/3/61' FAILED ********************
Script(shard):
--
GTEST_OUTPUT=json:T:\5\tools\swift\unittests\runtime\.\SwiftRuntimeTests.exe-Swift-Unit-6880-3-61.json GTEST_SHUFFLE=0 GTEST_TOTAL_SHARDS=61 GTEST_SHARD_INDEX=3 T:\5\tools\swift\unittests\runtime\.\SwiftRuntimeTests.exe
--

Note: This is test shard 4 of 61.

[==========] Running 1 test from 1 test suite.

[----------] Global test environment set-up.

[----------] 1 test from TestArrayCopy

[ RUN      ] TestArrayCopy.test_swift_arrayInitWithTakeFrontToBackPOD

[       OK ] TestArrayCopy.test_swift_arrayInitWithTakeFrontToBackPOD (0 ms)

[----------] 1 test from TestArrayCopy (0 ms total)



[----------] Global test environment tear-down
Exception Code: 0x80000003

LLVM ERROR: IO failure on output stream: bad file descriptor
```

**Review by drexin — APPROVED** [review]
LGTM. Thanks!

**Comment by aschwaighofer** [comment]
@swift-ci test windows

**Pull request merged**
