### PR TITLE
[stdlib] Parse my tweets faster! 2x forwards, 3x reverse

### PR DESCRIPTION
**Pull request by milseman**
Adds in a special case grapheme break detection between two values
within scalar ranges where we have special knowledge. Any sub-0x300
scalars, except CR-LF, are guaranteed to have grapheme breaks between
them. We're reasonably confident this will not change in future
versions of Unicode. We might add more ranges in the future, but
should do so conservatively, anticipating future Unicode changes.
    
In these cases we can very quickly break, even for strings that have
mixed latin and emoji characters. In a ASCII string with a single
emoji in it, we traverse the string 2x faster forwards and 3x faster
in reverse. (Reverse is 3x faster as it involves some forwards
traversal inside of the index). For a string that's half Latin half
non-Latin, we're about 1.5x faster forwards and backwards.

Adds in tests and new (disabled) micro benchmarks

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
That same `Reflection/typeref_decoding_imported.swift` is failing on my unrelated PR too.

**Comment by jrose-apple** [comment]
@shahmishal, @aschwaighofer, does the cleaning job clean the PR test bots too?

**Comment by airspeedswift** [comment]
@swift-ci Please clean test linux platform

**Comment by shahmishal** [comment]
> @shahmishal, @aschwaighofer, does the cleaning job clean the PR test bots too?

@jrose-apple Yes

**Comment by natecook1000** [comment]
@swift-ci Please test OS X platform

**Comment by airspeedswift** [comment]
Looks like a legit crash inside a SwiftPM test

**Comment by milseman** [comment]
I'll investigate. If it's related, then that'll be good test fodder, as we seem to be a little low on our test coverage of grapheme breaking.

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please smoke test os x platform

**Comment by airspeedswift** [comment]
@swift-ci Please test macOS platform

**Pull request merged**
