### PR TITLE
[5.6] IRGen: Fix using weak linkage to avoid duplicate metadata by only applying this to PROTOCOL related data

### PR DESCRIPTION
**Pull request by aschwaighofer**
rdar://86256970

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by compnerd** [comment]
@aschwaighofer would you mind adding a bit more detail to the commit message?  What is "this"?

**Comment by aschwaighofer** [comment]
@compnerd "this" is using weak hidden linkage for objective-c metadata.

This PR is a cherry-pick of https://github.com/apple/swift/pull/40486.

**Comment by compnerd** [comment]
Ah!  Thanks; that would be great to have in the commit message.  BTW, for cherry-picks, the `-x` option is very helpful for tracking the original commit.

**Comment by aschwaighofer** [comment]
We originally used internal linkage which causes duplicate metadata entries.

I then applied weak hidden linkage generally to all objective-c metadata (in https://github.com/apple/swift/pull/40342). This causes linkage issues with `CATEGORY` objective-c metadata. The linker applies some optimization to category metadata that does not expect to see weak symbols. So, this PR selectively applies weak hidden linkage only to `PROTOCOL` objective c metadata.

**Comment by compnerd** [comment]
Hmm, I assume that weak hidden translates to internal ODR?  The category metadata needs to be visible across module boundaries, and the category DCE that ld64 does as an optimization over ObjC metadata will require it to be weak ODR so that it can iterate and drop the category.  The change itself seems reasonable, its purely the commit message which I was hoping could be improved so that future readers can follow the change.  The reference to the cherry-picked commit would also work - as I believe that the original commit had a bit more context in the commit message.

**Comment by aschwaighofer** [comment]
I have updated the commit message.

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Review by tbkka — APPROVED** [review]

**Pull request merged**
