### PR TITLE
stdlib: Remove unused, unsafe helper function _withUninitializedString

### PR DESCRIPTION
**Pull request by belkadan**
No functionality change.

### CODE REVIEW

**Comment by benrimmington** [comment]
@swift-ci Please smoke test

**Comment by benrimmington** [comment]
@swift-ci Please smoke test macOS platform

**Review by kylemacomber — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
Does anyone mind if this is merged now?

**Comment by belkadan** [comment]
Maybe people were expecting me to merge it, but my personal account doesn't have commit access. (And I don't use my Apple account anymore.)

**Pull request merged**
