### PR TITLE
[Docs] Revise wording for nominal types educational note

### PR DESCRIPTION
**Pull request by xwu**
This is a companion update for the educational note on nominal types. I've made a few changes to the wording in the hopes of cutting down confusion:

* It's nitpicky, but I've called them "structures" and "enumerations" in line with _TSPL_.
* The term "structural type," afaict, wouldn't apply to a special type like `AnyObject`; moreover, it doesn't seem like a term we need to teach users, useful as it might be in other contexts, and particularly seems confusable here with "structure types" (i.e., structs).
* The original text calls protocols "protocol types" in contradistinction with existential types, but elsewhere we use that term as a synonym for existential types; I'd imagine a user would be confused by these contradictory uses of the same term--that paragraph is entirely reworded.

### CODE REVIEW

**Review by owenv — APPROVED** [review]
LGTM!

**Comment by xwu** [comment]
@swift-ci smoke test and merge

**Comment by slavapestov** [comment]
@hborla Should diagnostic messages ever contain the word 'nominal'? I only see a few:

```
ERROR(sil_member_lookup_bad_type,none,
      "cannot lookup member %0 in non-nominal, non-module type %1",
      (DeclName, Type))
ERROR(non_nominal_no_initializers,none,
      "non-nominal type %0 does not support explicit initialization",
      (Type))
NOTE(associated_type_witness_conform_impossible,none,
     "candidate can not infer %0 = %1 because %1 "
     "is not a nominal type and so can't conform to %2",
     (Identifier, Type, Type))
```

**Comment by slavapestov** [comment]
Especially "non-nominal, non-module type" is bad because we don't want users to think of modules as types.

**Comment by hborla** [comment]
@slavapestov I would love if we can remove the term `nominal` from all diagnostics and instead use a more specific term that users will understand. For example, instead of saying `non-nominal type does not support explicit initialization`, we could be more descriptive about the kind of type we have such as `structural type does not support initialization` or `metatype does not support initialization` instead of finding one jargony term to categorize them all

**Comment by slavapestov** [comment]
@hborla Breaking out the different type kinds here sounds good. The specific case I've seen on Twitter/forums where folks get confused by the "non-nominal type doesn't support initialization" is where the type is a generic parameter and they forgot to add a constraint to a protocol with an init() requirement, so we could suggest that as the fix as well.

**Comment by theblixguy** [comment]
That's a really good idea! I have opened https://github.com/apple/swift/pull/33763 to remove "nominal" from diagnostic text.

**Comment by xwu** [comment]
Thanks @theblixguy! It would definitely be nice to remove this term from user-facing diagnostics completely!

@swift-ci smoke test Linux platform

**Pull request merged**
