### PR TITLE
TextualInterface: print __conuming before accessors

### PR DESCRIPTION
**Pull request by nkcsgexi**
rdar://80535144

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by slavapestov** [comment]
It looks like there's some duplicate logic and we might need to add __consuming in a few more places (or factor out the duplication). In `PrintAST::printAccessors()`:

```
  // We sometimes want to print the accessors abstractly
  // instead of listing out how they're actually implemented.
...

    if (mutatingGetter) printWithSpace("mutating");

...
```

and

```
auto PrintAccessor = [&](AccessorKind Kind) -> bool {
...
if (!PrintAccessorBody) {
...
printMutabilityModifiersIfNeeded(Accessor);
```

**Comment by nkcsgexi** [comment]
@slavapestov My previous attempt to refactor this into `printMutabilityModifiersIfNeeded` had failed several tests and fixing them introduces perplexing logics into the common function.

**Pull request merged**
