### PR TITLE
[Incremental] Turn fine-grained-dependencies on-by-default.

### PR DESCRIPTION
**Pull request by davidungar**
Turn off by passing in `-disable-fine-grained-dependencies`.

### CODE REVIEW

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Comment by davidungar** [comment]
@swift-ci please test

**Comment by davidungar** [comment]
@swift-ci please test windows

**Comment by davidungar** [comment]
@swift-ci please test source compatibility

**Comment by davidungar** [comment]
@swift-ci please test compiler performance

**Comment by varungandhi-apple** [comment]
Just a random thought (kinda' struck me after reading your PR): do you find it odd that we have the default values for different options duplicated in several places? It does seem a little bit dissatisfying but maybe it is fine. Do you think maybe we should lift out the default values into a separate header in the future or is the status quo better?

**Comment by davidungar** [comment]
@swift-ci please test windows platform

**Comment by davidungar** [comment]
> Just a random thought (kinda' struck me after reading your PR): do you find it odd that we have the default values for different options duplicated in several places? It does seem a little bit dissatisfying but maybe it is fine. Do you think maybe we should lift out the default values into a separate header in the future or is the status quo better?

Thanks for reading it over, and I like your thought. I did find one place where I could remove a dependence. It would be nice to have a central place for flags common to both driver and frontend, but I'm not sure how that would work with a driver written in Swift. 

Anyway, I'll make the one change and retest. Thanks again!

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Comment by davidungar** [comment]
@swift-ci please smoke test os x platform

**Comment by davidungar** [comment]
@swift-ci please smoke test os x platform

**Comment by davidungar** [comment]
@swift-ci please clean smoke test linux platform

**Comment by davidungar** [comment]
@swift-ci please smoke test linux

**Pull request merged**
