### PR TITLE
[stdlib] Cleanup usage of Builtin.castToNativeObject(...).

### PR DESCRIPTION
**Pull request by gottesmm**
Previously often times when casting a value, we would just pass along the
cleanup of the uncasted value. With semantic SIL this is no longer correct since
the cleanup now needs to be on the cast result.

This caused problems for certain usages of Builtin.castToNativeObject(...) by
the stdlib. Specifically, the stdlib was using this on AnyObject values that
were not necessarily native. Since we were recreating the cleanup on the native
value, a swift native release was being used =><=.

In this commit I solve this problem by:

1. Adding an assert in Builtin.castToNativeObject(...) that ensures that any value
passed to Builtin.castToNativeObject() is known conservatively to use swift
native reference counting.

2. I changed all uses where we do not have a precondition of a native ref
counting type to use Builtin.castToUnknownObject(...).

3. I added a new Builtin called Builtin.unsafeCastToNativeObject(...) that does
not have the compile time check. I used this to rewrite callsites in the stdlib
where we know via preconditions that an AnyObject will dynamically always be
native.

rdar://29791263
rdar://30981898

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci Please test

**Comment by gottesmm** [comment]
preset=buildbot,tools=RA,stdlib=DA
@swift-ci Please test macOS with preset

**Comment by gottesmm** [comment]
@swift-ci Please test

**Comment by gottesmm** [comment]
@swift-ci Please test

**Comment by dabrahams** [comment]
@gottesmm sounds like a good plan!

**Comment by gottesmm** [comment]
@swift-ci Please smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci Please smoke test and merge

**Pull request merged**
