### PR TITLE
[SourceKit] Test adjustments for improved formatting in BasicFormat

### PR DESCRIPTION
**Pull request by ahoppen**
Companion of https://github.com/apple/swift-syntax/pull/2511

### CODE REVIEW

**Comment by ahoppen** [comment]
https://github.com/apple/sourcekit-lsp/pull/1072

@swift-ci Please smoke test

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/2511

@swift-ci Please smoke test

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/2511

@swift-ci Please smoke test Windows

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/2511

@swift-ci Please smoke test Windows

**Review by bnbarham — APPROVED** [review]

**Pull request merged**
