### PR TITLE
Adding the Backdeploy 5.6 compatibility library

### PR DESCRIPTION
**Pull request by etcwilde**
This PR starts adding the stubs for the Swift 5.6 back deployment compatibility library.
At this time it adds the ability to set the `-runtime-compatibility-version` to `5.6` in order to link the compatibility library, and declares two symbols for the `swift_task_future_wait` and `swift_task_future_wait_throwing` function replacements.
These functions currently just forward the call to the original implementation.

I have checked that this library is actually used by running
```
build/Ninja-ReleaseAssert/swift-macosx-arm64/bin/swiftc \
    -runtime-compatibility-version 5.6 test.swift \
    -parse-as-library -sdk $(xcrun --show-sdk-path -sdk macosx) \
    -target arm64-apple-macos11.0
```
then inspecting and executing the resulting binary.

### CODE REVIEW

**Comment by etcwilde** [comment]
@swift-ci please test

**Comment by etcwilde** [comment]
Also, if someone knows how to actually test these backdeploy libraries with anything beyond "it compiles, ship it", I'm all ears.

**Comment by etcwilde** [comment]
@swift-ci please test

**Comment by etcwilde** [comment]
Updated the `weak_linking.swift` back deployment test  to check for `_swift_FORCE_LOAD_$_swiftCompatibilityConcurrency` and `_swift_FORCE_LOAD_$_swiftCompatibility56` when back-deploying to 10.15. It only checks for `_swift_FORCE_LOAD_$_swiftCompatibility56` when back-deploying to macOS 12.0, and ensures that nothing is back-deployed for macOS 13.0.

**Review by DougGregor — APPROVED** [review]
This LGTM. I'm sure the contents of the compatibility library will shift around a bit as we start implementing the compatibility fixes, but the structure, build model, and linking here all look :100:.

**Pull request merged**
