### PR TITLE
libSyntax: support declaration modifiers, like static, private, etc.

### PR DESCRIPTION
**Pull request by nkcsgexi**
Some declaration modifiers may have more details attached, like
"private(set)". This patch represents the detail part "(set)" as a token
list.

Also, this patch fixes an issue where back tracking scope doesn't
recover leading/trailing trivia information.

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@rintaro could you review this please? especially the part of recovering trivia information.

**Comment by rintaro** [comment]
Could you hold this? This workaround shouldn't be needed if we correctly restore the Lexer state when backtracking. The problem is mismatch between start position of LeadingTrivia and `Lexer::getStateForBeginningOfToken()`. I'll look into it.

**Comment by nkcsgexi** [comment]
Sure, thank you for looking into this! @rintaro

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci Please clean test Linux platform

**Comment by nkcsgexi** [comment]
@swift-ci Please clean test Linux platform

**Pull request merged**
