### PR TITLE
Update checkout `swift-apis`.

### PR DESCRIPTION
**Pull request by dan-zheng**
https://github.com/tensorflow/swift-apis/commit/5caa4600e0796cc04dc755f7d7c4befe7bd336cd

### CODE REVIEW

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Review by rxwei — APPROVED** [review]

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow clean

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow clean

**Comment by rxwei** [comment]
clean test

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by dan-zheng** [comment]
> clean test

thanks, little trouble there

**Pull request merged**
