### PR TITLE
[WIP] Everybody gets a tracer

### PR DESCRIPTION
**Pull request by graydon**
This PR has been dragging on for .. a while .. but I think it's probably worth merging now. The punchline is that every request (in the request-evaluator sense) now gets traced/profiled automatically,   and a fair quantity of their arguments do too. I also sprinkled a few others around places I thought might be interesting, expanded the entity vocabulary, and improved the formatting of entity names where possible. The trace logs and profiles are roughly readable/informative now.

(I tried to do quite a lot of template-metaprogram tricks to cut down on the number of explicit overloads and specializations relative to the vocabulary here, all of them either failed in some resolution-ordering corner case I couldn't figure out, or else broke the layering-violation-avoidance tricks, so wouldn't link. I'm happy enough with this state.)

### CODE REVIEW

**Comment by graydon** [comment]
@swift-ci please test

**Comment by graydon** [comment]
@swift-ci please test

**Comment by graydon** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]
This looks fantastic! The only comment I have is to please update `docs/RequestEvaluator.md` to remove the entry that asks someone to implement this.

**Comment by graydon** [comment]
@swift-ci please test and merge

**Pull request merged**
