### PR TITLE
Changing the hyperlink word in README.md from 'the website' to 'Swift.org'

### PR DESCRIPTION
**Pull request by KrishMunot**

### CODE REVIEW

**Comment by jrose-apple** [comment]
Thanks for sticking around! One last nitpick: can you change the title to be a little more descriptive, per the [Contributing Code](https://swift.org/contributing/#commit-messages) guidelines? It's good to see just from the "title" line of a commit that this only affects the readme file.

**Comment by KrishMunot** [comment]
Thanks for nudging me in the right direction @jrose-apple  .I have made the changes, do let me know if its done in the right way. :)

**Comment by jrose-apple** [comment]
Ah, sorry, it's the *commit message* I was asking about, not just the pull request title. The commit message shows up in the one-line log modes (including `git log --oneline`, GitHub's list of commits, and the swift-commits mailing list).

**Comment by KrishMunot** [comment]
I got stuck in some merge conflict issues and have decided to close this PR once the [new PR](https://github.com/apple/swift/pull/257/commits) is merged. Do check and let me know if that must be valid.

**Pull request closed without merging**
