### PR TITLE
[swift 2.3] Backwards-deployment support for Core Data's generics.

### PR DESCRIPTION
**Pull request by jrose-apple**
- **Explanation:** Swift clients of Core Data depend on conformances to these protocols being present at runtime.
- **Scope:** Pretty much everything that uses Core Data on iOS, it turns out—specifically the `fetchedObjects` property of NSFetchedResultsController. (We saw this a lot in labs.)
- **Issue:** rdar://problem/26825103.
- **Reviewed by:** Ben Trumbull (from the Core Data team)
- **Risk:** Very low.
- **Testing:** Added compiler regression tests, manually checked against the submitted project.

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
The Linux failures seem to be happening without the patch as well: https://ci.swift.org/view/swift-2.3-branch/job/oss-swift-2.3-incremental-RA-linux-ubuntu-14_04/2/.

**Comment by tkremenek** [comment]
This appears to fail on macOS as well:

https://ci.swift.org/view/swift-2.3-branch/job/oss-swift-2.3-incremental-RA-osx/30/

**Comment by tkremenek** [comment]
@jrose-apple I reverted this change from `swift-2.3-branch`.

**Pull request merged**
