### PR TITLE
[swift_new_type] Audited and un-audited CF reference types 

### PR DESCRIPTION
**Pull request by milseman**
#### What's in this pull request?

1)
    Special case logic for CF types, which may be coming in as
    unmanaged. In this case, we will use audit information if present to
    import with the new type, otherwise we have to fall back to
    Unmanaged<CF...>.

```
We still import global variables that must be unmanaged onto the new
type, though they keep their unmanaged types. This helps to
consolidate the definitions, as well as make future migration easier
if they get audited.

Test cases included.
```

2)
    Code cleaup and generalization to also catch typedefs of CF reference
    types. Tests will be included in a subsequent commit, as this now
    exhibits a latent problem when interacting with Unmanaged.
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please test

@DougGregor please review

**Comment by milseman** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
LGTM!

**Comment by milseman** [comment]
[TestMiBreak.py FAILED]
Command invoked: /usr/bin/python /home/buildnode/jenkins/workspace/swift-PR-Linux/lldb/test/dotest.py --executable /home/buildnode/jenkins/workspace/swift-PR-Linux/buildbot_linux/lldb-linux-x86_64/bin/lldb --rerun-all-issues -C /home/buildnode/jenkins/workspace/swift-PR-Linux/buildbot_linux/llvm-linux-x86_64/bin/clang -s 2016-05-09-18_20_43 --results-port 57638 --inferior -p TestMiBreak.py /home/buildnode/jenkins/workspace/swift-PR-Linux/lldb/packages/Python/lldbsuite/test --event-add-entries worker_index=0:int

LLDB failure?

**Pull request merged**
