### PR TITLE
[stdlib] Modernize sort code

### PR DESCRIPTION
**Pull request by airspeedswift**
When reviewing #18629 I realized this code was pretty horribly out of date, style-wise. Mostly this is making free functions that pass `&self` into mutating methods, with some minor other cleanups along the way.

Not expecting this to impact performance unless it interacts with the optimizer in some odd way.

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@swift-ci please smoke test compiler performance

**Comment by airspeedswift** [comment]
fyi @overlazy

**Comment by overlazy** [comment]
@airspeedswift  [sort3](https://github.com/apple/swift/blob/75d31f73023e42a04b80ea5416183fb17cdfe202/stdlib/public/core/Sort.swift#L325) becomes public

**Pull request merged**
