### PR TITLE
ClosureSpecializer: We don't need to insert releases for inlined thin_to_thick functions

### PR DESCRIPTION
**Pull request by aschwaighofer**
The fact that we wanted to insert them blocked us from inlining them for certain callees.

rdar://32595213

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test

**Comment by aschwaighofer** [comment]
@swift-ci Please benchmark

**Comment by dabrahams** [comment]
@shahmishal I think CI is stuck

**Comment by aschwaighofer** [comment]
I ran locally and measured a 40% improvement on MapStringReduce and no serious regressions.

**Comment by dabrahams** [comment]
Hmm, looking at the results for #10149 and this one, the Chars regression looks real. @aschwaighofer could you take a look at that?

**Comment by aschwaighofer** [comment]
Looked at this when I ran locally -- the generated code is the same.

**Comment by dabrahams** [comment]
Thank you!  It's very sad that we had to discuss it at all; maybe someday we'll figure out how to avoid  these misleading results.

**Comment by palimondo** [comment]
@dabrahams I'm working on that. Sometimes during next week I should have something to show.

**Pull request merged**
