### PR TITLE
XFAIL: test/Concurrency/throwing.swift on windows

### PR DESCRIPTION
**Pull request by aschwaighofer**
It seems to fail.

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test

**Comment by aschwaighofer** [comment]
https://bugs.swift.org/browse/SR-14576

**Comment by aschwaighofer** [comment]
@swift-ci smoke test linux

**Comment by aschwaighofer** [comment]
@swit-ci smoke test macOS

**Comment by xedin** [comment]
@shahmishal @aschwaighofer Looks like we need the same XFAIL in 5.5 branch as well for Windows.

**Pull request merged**
