### PR TITLE
[stdlib]Catch the reasonable mistake 'UnsafeRawMutableBufferPointer'

### PR DESCRIPTION
**Pull request by devKobe24**
[stdlib]Catch the reasonable mistake 'UnsafeRawMutableBufferPointer'

Issue: [[SR-6360](https://bugs.swift.org/browse/SR-6360)]
Tag: https://github.com/apple/swift/issues/48910

We could make things easier on people by adding an unavailable typealias with a renamed field.

Resolve: https://github.com/apple/swift/issues/48910, fix: https://github.com/apple/swift/pull/69881

cc: @glessard

### CODE REVIEW

**Comment by devKobe24** [comment]
@swift-ci Please smoke test

**Comment by glessard** [comment]
@devKobe24 thanks! This illustrates the behaviour you intend, but would not change the toolchain. The typealias would need to be in the standard library code, e.g. alongside the definition of `UnsafeMutableRawBufferPointer`.

**Comment by devKobe24** [comment]
@swift-ci Please smoke test

**Comment by devKobe24** [comment]
@glessard 

Hello,

Thank you so much for enlightening me on the crucial aspects.

It's my first contribution, and I'm quite nervous and excited, haha.

It's such a fun and thrilling adventure.

Sincerely from Korea, Kobe.

**Pull request closed without merging**
