### PR TITLE
SILGen: Fix crash with access to unowned/weak property in other module [3.1]

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes <rdar://problem/30290896>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@jrose-apple Yes, another inappropriate VarDecl::getType() usage. Maybe we should just push this method down to ParamDecl...

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
Unrelated failure:

```
20:48:49 /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/System/Library/Frameworks/CoreVideo.framework/Headers/CVOpenGLESTexture.h:23:2: note: after modifying system headers, please delete the module cache at '/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-3.1-branch/buildbot_incremental/swift-macosx-x86_64/./module-cache/18EZ0IW0QIRZ2'
20:48:49 #include <OpenGLES/gltypes.h>
20:48:49  ^
20:48:49 
Assertion failed: (idx < size()), function operator[], file /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-3.1-branch/llvm/include/llvm/ADT/SmallVector.h, line 145.
20:48:49 0  swift                    0x000000010395a748 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 40
20:48:49 1  swift                    0x000000010395adf6 SignalHandler(int) + 454
20:48:49 2  libsystem_platform.dylib 0x00007fffcbc22bba _sigtramp + 26
20:48:49 3  libsystem_platform.dylib 0x000070000f1bc160 _sigtramp + 1129944512
20:48:49 4  libsystem_c.dylib        0x00007fffcbaa9420 abort + 129
20:48:49 5  libsystem_c.dylib        0x00007fffcba70893 basename_r + 0
20:48:49 6  swift                    0x000000010369d23a clang::FileManager::GetUniqueIDMapping(llvm::SmallVectorImpl<clang::FileEntry const*>&) const + 394
20:48:49 7  swift                    0x0000000102e64acd clang::ASTWriter::WriteHeaderSearch(clang::HeaderSearch const&) + 77
20:48:49 8  swift                    0x0000000102e82393 clang::ASTWriter::WriteASTCore(clang::Sema&, llvm::StringRef, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, clang::Module*) + 11699
20:48:49 9  swift                    0x0000000102e7f3e4 clang::ASTWriter::WriteAST(clang::Sema&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, clang::Module*, llvm::StringRef, bool) + 660
20:48:49 10 swift                    0x0000000102ebf6db clang::PCHGenerator::HandleTranslationUnit(clang::ASTContext&) + 171
20:48:49 11 swift                    0x0000000102c9cc8c clang::MultiplexConsumer::HandleTranslationUnit(clang::ASTContext&) + 44
20:48:49 12 swift                    0x0000000102ecdda2 clang::ParseAST(clang::Sema&, bool, bool) + 578
20:48:49 13 swift                    0x0000000102c64969 clang::FrontendAction::Execute() + 73
20:48:49 14 swift                    0x0000000102c2e1c1 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 1137
20:48:49 15 swift                    0x00000001038ed8ae llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) + 222
20:48:49 16 swift                    0x00000001038eda30 RunSafelyOnThread_Dispatch(void*) + 48
20:48:49 17 swift                    0x000000010395be2d ExecuteOnThread_Dispatch(void*) + 13
20:48:49 18 libsystem_pthread.dylib  0x00007fffcbc2caab _pthread_body + 180
20:48:49 19 libsystem_pthread.dylib  0x00007fffcbc2c9f7 _pthread_body + 0
20:48:49 20 libsystem_pthread.dylib  0x00007fffcbc2c1fd thread_start + 13
```

**Comment by slavapestov** [comment]
@swift-ci Please test macOS

**Comment by slavapestov** [comment]
@swift-ci Please clean test macOS

**Review by jrose-apple — APPROVED** [review]

**Comment by ematejska** [comment]
@swift-ci please test

**Comment by slavapestov** [comment]
@ematejska I forgot to update the test for the old mangling in the 3.1 branch. Updated patch coming up.

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please clean test macOS

**Pull request merged**
