### PR TITLE
[4.2][SE-0202][stdlib] Random unification

### PR DESCRIPTION
**Pull request by lorentey**
This is @Azoy's implementation of [SE-0202], cherry picked from #16413.

Reviewed by @natecook1000, @milseman, @stephentyrone, @xwu & myself

[SE-0202]: https://github.com/apple/swift-evolution/blob/master/proposals/0202-random-unification.md

rdar://problem/39666971

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci please test

**Comment by lorentey** [comment]
cc @airspeedswift, @tkremenek

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test

**Comment by airspeedswift** [comment]
@swift-ci please test macOS platform

**Comment by Azoy** [comment]
@airspeedswift after this gets merged, should I write up a pr for the changelog and update the proposal status?

**Comment by airspeedswift** [comment]
@Azoy yes please

**Comment by huonw** [comment]
There's two small tweaks that are probably good to pull in. I've done them for the 04-30-2018 branch at https://github.com/apple/swift/pull/16524. If this fails again could you pull them in here too?

**Comment by huonw** [comment]
I realised that I could edit this PR directly, and because of timezones, the

@swift-ci please test 

run will likely finish before everyone else comes back online; so I added those fixes.

**Comment by huonw** [comment]
@swift-ci please test

**Pull request merged**
