### PR TITLE
Update where clause warning to error for Swift 4

### PR DESCRIPTION
**Pull request by ematejska**
Update the warning of "where' clause next to generic parameters is deprecated" to an error for Swift > 3.

rdar://problem/32203888

### CODE REVIEW

**Comment by ematejska** [comment]
@swift-ci please test

**Comment by ematejska** [comment]
@swift-ci please smoke test

**Comment by ematejska** [comment]
@swift-ci smoke test

**Review by bitjammer — APPROVED** [review]

**Review by jckarter — APPROVED** [review]
Looks good.

**Comment by ematejska** [comment]
@swift-ci smoke test

**Comment by ematejska** [comment]
@swift-ci test

**Comment by ematejska** [comment]
@swift-ci please smoke test

**Comment by ematejska** [comment]
@swift-ci test

**Comment by ematejska** [comment]
The one failure in the full OS X platform test is also failing for other PR's. Merging.

**Pull request merged**
