### PR TITLE
Cache Identifier::isOperator() result

### PR DESCRIPTION
**Pull request by danra**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by tkremenek** [comment]
@swift-ci smoke test

**Comment by tkremenek** [comment]
@swift-ci smoke test

**Comment by tkremenek** [comment]
@swift-ci test linux

**Comment by tkremenek** [comment]
@swift-ci test osx

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by danra** [comment]
@tkremenek How can I run the failing test locally on my Xcode?
Also, would appreciate your input on why this test might be failing.

Thanks!
Dan

**Comment by tkremenek** [comment]
@swift test

**Comment by tkremenek** [comment]
This is producing a failure on OS X:

```
******************** TEST 'Swift :: ClangModules/objc_parse.swift' FAILED ********************
Script:
--
/Users/buildnode/jenkins/workspace/swift-PR-osx/buildbot_incremental/swift-macosx-x86_64/bin/swiftc -frontend -target x86_64-apple-macosx10.9  -module-cache-path '/var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/swift-testsuite-clang-module-cacheFYJuT5' -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk   -enable-source-import -sdk '/Users/buildnode/jenkins/workspace/swift-PR-osx/swift/test'/Inputs/clang-importer-sdk -I '/Users/buildnode/jenkins/workspace/swift-PR-osx/swift/test'/Inputs/clang-importer-sdk/swift-modules   -emit-sil -I /Users/buildnode/jenkins/workspace/swift-PR-osx/swift/test/ClangModules/Inputs/custom-modules /Users/buildnode/jenkins/workspace/swift-PR-osx/swift/test/ClangModules/objc_parse.swift -verify
--
Exit Code: 1

Command Output (stderr):
--
/Users/buildnode/jenkins/workspace/swift-PR-osx/swift/test/ClangModules/objc_parse.swift:380:40: error: unexpected warning produced: no method declared with Objective-C selector 'action'
  obj.object(obj, doSomething:Selector("action"))
                                       ^
/Users/buildnode/jenkins/workspace/swift-PR-osx/swift/test/ClangModules/objc_parse.swift:380:40: error: unexpected note produced: wrap the selector name in parentheses to suppress this warning
  obj.object(obj, doSomething:Selector("action"))
                                       ^
/Users/buildnode/jenkins/workspace/swift-PR-osx/swift/test/ClangModules/objc_parse.swift:383:40: error: unexpected warning produced: no method declared with Objective-C selector 'action'
  rev.object(rev, doSomething:Selector("action"))
                                       ^
/Users/buildnode/jenkins/workspace/swift-PR-osx/swift/test/ClangModules/objc_parse.swift:383:40: error: unexpected note produced: wrap the selector name in parentheses to suppress this warning
  rev.object(rev, doSomething:Selector("action"))
                                       ^
```

**Comment by tkremenek** [comment]
@danra The Jenkins pull request bot builds and runs everything using the build-script preset:

```
swift/utils/build-script --preset=buildbot_all_platforms,tools=RA,stdlib=RA
```

That will run all the tests, but will also build for all platforms.  The smoke test only builds for OS X:

```
swift/utils/build-script --preset=buildbot_incremental,tools=RA,stdlib=RA
```

**Comment by tkremenek** [comment]
@danra I'm not certain if this code needs to run in a multi-threaded context.  I do not believe so, but I also know that the failing test involves Clang modules, which is multi-threaded.

**Comment by tkremenek** [comment]
@DougGregor Any ideas why this test would be failing?

**Comment by danra** [comment]
I guess: the issue isn't multi-threading, but that the default copy constructor is used in some places, replacing the Pointer member but leaving the cache in place.

**Comment by lattner** [comment]
Separately from the test failure, a better way to cache this is to encode it into the token kind.  That way we could have tok::identifier and tok::operator (renamed to avoid the C++ keyword)

**Pull request closed without merging**
