### PR TITLE
When ptrauth-copying vtable/wtables, allow NULL entries (due to VFE)

### PR DESCRIPTION
**Pull request by kubamracek**
rdar://86552670

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by mikeash — COMMENTED** [review]
I take it this doesn't work as-is? I can never keep track of which ptrauth things implicitly accept an unsigned 0 value and which require an explicit check.

**Review by mikeash — APPROVED** [review]
LGTM presuming you've verified that the old code doesn't already accept NULL.

**Comment by kubamracek** [comment]
Correct, the old code crashes. The added test case triggers the crash.

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Pull request merged**
