### PR TITLE
[CodeCompletion] Migrate some tests to batch completion test #3

### PR DESCRIPTION
**Pull request by rintaro**
```
17.59s: Swift(macosx-x86_64) :: IDE/complete_type_in_func_param.swift
15.08s: Swift(macosx-x86_64) :: IDE/complete_keywords.swift
14.37s: Swift(macosx-x86_64) :: IDE/complete_sself.swift
12.97s: Swift(macosx-x86_64) :: IDE/complete_in_closures.swift
9.85s: Swift(macosx-x86_64) :: IDE/complete_pattern.swift
9.65s: Swift(macosx-x86_64) :: IDE/complete_single_expression_return.swift
```
to
```
1.18s: Swift(macosx-x86_64) :: IDE/complete_in_closures.swift
0.95s: Swift(macosx-x86_64) :: IDE/complete_keywords.swift
0.69s: Swift(macosx-x86_64) :: IDE/complete_sself.swift
0.66s: Swift(macosx-x86_64) :: IDE/complete_type_in_func_param.swift
0.56s: Swift(macosx-x86_64) :: IDE/complete_single_expression_return.swift
0.52s: Swift(macosx-x86_64) :: IDE/complete_pattern.swift
```

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci This set was easy. Pure script migration 👍

**Review by bnbarham — APPROVED** [review]

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test macOS

**Pull request merged**
