### PR TITLE
Move Playground QuickLook support  => PlaygroundSupport

### PR DESCRIPTION
**Pull request by dabrahams**

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please test and merge

**Comment by dabrahams** [comment]
@swift-ci Please test Linux platform

**Comment by dabrahams** [comment]
@swift-ci Please smoke test Linux platform

**Comment by dabrahams** [comment]
@swift-ci Please test and merge

**Comment by talibanes** [comment]
Que pinches abre? Usted ya no open ny mother's jajaja
Sent from my BlackBerry® by Boost Mobile

-----Original Message-----

**Pull request merged**
