### PR TITLE
[gardening] break long comment lines

### PR DESCRIPTION
**Pull request by edymtt**
Takes review feedback from #38415

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci please smoke test

**Review by drexin — APPROVED** [review]
👍

**Comment by edymtt** [comment]
@swift-ci please test toolchain

**Comment by edymtt** [comment]
@swift-ci please build toolchain

**Comment by edymtt** [comment]
The toolchain failed because of a known issue that has been since fixed in #38466

We had a toolchain build successfully with #38415
https://ci.swift.org/view/Packages/job/oss-swift-package-macos/6012/

and a 5.5 toolchain was built successfully as part of #38445

as such I don't expect this PR to introduce any regression by modifying comment lines

**Pull request merged**
