### PR TITLE
A potentially simpler fix for SR-8164

### PR DESCRIPTION
**Pull request by bgogul**
Resolves [SR-8164](https://bugs.swift.org/browse/SR-8164).

### CODE REVIEW

**Review by mhong — APPROVED** [review]
Indeed this is a lot simpler. Nice!

It loses some power for sanity checks. e.g. if we have two blocks in a sequential region, each having a branchInst as the term inst, and the first branch does not produce any output tensors -- the old code would catch that when lowering the BranchInst of the second block, based on the assert of `graphFn.outputSetter != GraphFunctionBody::NOT_COND_REGION`. 
Presumably these two blocks should have been contracted into a single block before we run the canonicalize code, so that a sequential SESE region should not have a sequence of single basic blocks.

But arguably the complexity of such sanity check code outweighs the benefits they deliver, so I'm fine with deleting the checks for now.

**Comment by lattner** [comment]
this patch is a lot simpler, thank you!

**Review by lattner — APPROVED** [review]

**Comment by bgogul** [comment]
@mhong 
> It loses some power for sanity checks. e.g. if we have two blocks in a sequential region, each having a branchInst as the term inst, and the first branch does not produce any output tensors -- the old code would catch that when lowering the BranchInst of the second block, based on the assert of graphFn.outputSetter != GraphFunctionBody::NOT_COND_REGION.
> Presumably these two blocks should have been contracted into a single block before we run the canonicalize code, so that a sequential SESE region should not have a sequence of single basic blocks.
Even if the two blocks are not contracted, this would compute the correct graph as far as I understand TFLowerGraph code.  Am I mistaken?

**Comment by mhong** [comment]
Before this PR, we will not be able to lower two sequence blocks (the existing asserts will fire, because both blocks will have branch/return statements). But this is now relaxed, and I believe relaxing this can be good (like in your CFG rewrite work, the new graph might have such sequential blocks).

**Pull request merged**
