### PR TITLE
Make JSON fix-it outputs be per-primary in batch mode.

### PR DESCRIPTION
**Pull request by jrose-apple**
This means moving the output path into SupplementaryOutputPaths, and using the same sort of diagnostic dispatching that serialized diagnostics use. This is part of what's needed to run the migrator in batch mode (though it's not sufficient itself).

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
It looks like moving the migrator to batch mode would be more tricky, since the output paths there are currently in MigratorOptions rather than FrontendOptions. I think we can leave that as is for now; it's not a *requirement* that the migrator use batch mode.

**Review by davidungar — APPROVED** [review]
Nice!

**Comment by jrose-apple** [comment]
Review ping for Xi.

**Comment by nkcsgexi** [comment]
@jrose-apple Does this change imply migrator is agnostic to batch mode?

**Comment by jrose-apple** [comment]
Unfortunately no; the migrator will have to be sure not to use batch mode until it can represent having one of each *other* output per input (the remap file and the file-with-changes-applied). I didn't touch that yet, and at worst we'll say the migrator doesn't use batch mode this time around.

**Comment by nkcsgexi** [comment]
@jrose-apple thank you for the explanation! Could we have an assertion on the migrator path that batch mode is not used?

**Comment by jrose-apple** [comment]
That makes sense, sure.

**Comment by nkcsgexi** [comment]
Thank you!

**Review by nkcsgexi — APPROVED** [review]
Otherwise LGTM!

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Pull request merged**
