### PR TITLE
[LangOpts] NFC: Future proof language version checking

### PR DESCRIPTION
**Pull request by davezarzycki**

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by davezarzycki** [comment]
I don't think swift-ci likes forced branch updates

**Comment by CodaFi** [comment]
If you force-push at a branch, try to invoke the same CI command twice.  It's a bug on Github's end.

**Pull request closed without merging**
