### PR TITLE
[AutoDiff] Allow tgmath differentiation of `Double`

### PR DESCRIPTION
**Pull request by philipturner**
See https://github.com/apple/swift/pull/40885#issuecomment-1020447498. This allows automatic differentiation of type-generic math functions on 64-bit numbers, which has been missing since at least May 2020. `test/AutoDiff/stdlib/tgmath_derivatives.swift.gyb` was modified to test the new functions.

By duplicating declarations of a few derivatives, I avoided build failures potentially caused by a name collision between `foo(Double, ...)` and `foo(FloatingPoint, ...)`, where `foo` is a function listed below. There seems to be no other way to get this to compile.
- `fma`
- `fmod`/`remainder`
- `trunc`
- `round`/`floor`/`ceil`
- `sqrt`

### CODE REVIEW

**Comment by philipturner** [comment]
I don't understand how the first two commits got in there, but they're changes I made in early December while converting the Differentiable Programming Implementation to Markdown.

**Comment by rxwei** [comment]
@swift-ci please smoke test

**Comment by rxwei** [comment]
> I don't understand how the first two commits got in there, but they're changes I made in early December while converting the Differentiable Programming Implementation to Markdown.

When you pull changes from apple:main, it's better to pull and rebase, i.e. `git pull upstream main --rebase`. If your local main branch already contains those merge commits, you'll need to reset it.

```bash
git checkout main
git fetch upstream
git reset --hard upstream/main
```

**Comment by philipturner** [comment]
@rxwei I thought it would be better to separate out conversation from what's going on in the draft thread. I started making this comment in https://github.com/apple/swift/pull/40885, but then "Review requested" lit up and I figured Saleem might be active on that PR soon.

I've been trying for hours, but I can't get cross-import overlays to work. I tried messing with where `PlatformDifferentiation` is included in the standard library's CMakeLists.txt, adding extra stuff to PlatformDifferentiation's CMakeLists.txt, and making all the functions declared in PlatformDifferentiation both `public` and `@inlinable`.

Just like yesterday, I still get the following errors upon testing `tgmath_derivatives.swift.gyb`, indicating that the symbols for derivatives declared in `TgmathDerivatives.swift` are not visible to what should be importing them:
```
xit Code: 1

Command Output (stdout):
--
/Users/philipturner/Documents/Swift-Compiler/swift-project/swift/test/AutoDiff/stdlib/tgmath_derivatives.swift.gyb:196:23: error: expression is not differentiable
      checkGradient({ pow($0, $1) }, x, y, ulps: ulps)
                      ^
/Users/philipturner/Documents/Swift-Compiler/swift-project/swift/test/AutoDiff/stdlib/tgmath_derivatives.swift.gyb:196:23: note: cannot differentiate functions that have not been marked '@differentiable' and that are defined in other files
      checkGradient({ pow($0, $1) }, x, y, ulps: ulps)
                      ^
/Users/philipturner/Documents/Swift-Compiler/swift-project/swift/test/AutoDiff/stdlib/tgmath_derivatives.swift.gyb:196:23: error: expression is not differentiable
      checkGradient({ pow($0, $1) }, x, y, ulps: ulps)
                      ^
/Users/philipturner/Documents/Swift-Compiler/swift-project/swift/test/AutoDiff/stdlib/tgmath_derivatives.swift.gyb:196:23: note: cannot differentiate functions that have not been marked '@differentiable' and that are defined in other files
      checkGradient({ pow($0, $1) }, x, y, ulps: ulps)
...
```

How did you manage to build in the first place?

**Comment by rxwei** [comment]
I should clarify that I did _not_ manage to build in the first place. It was a quick attempt to set it up, and I didn't spend time on it after that. Also, since this PR is not about cross import overlays, I think we should this discussion to SR-15584.

**Pull request merged**
