### PR TITLE
Sema: Fix performance regression by only checking for selector conflicts in primary files

### PR DESCRIPTION
**Pull request by slavapestov**
Should fix the regression from https://github.com/apple/swift/pull/26975.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test compiler performance

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test compiler performance

**Comment by slavapestov** [comment]
@swift-ci Please smoke test compiler performance

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test compiler performance

**Review by CodaFi — APPROVED** [review]
Do we have a multifile test to ensure we only diagnose in the primary?

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Pull request merged**
