### PR TITLE
Make algorithms prototype standalone-testable and work with 4.1

### PR DESCRIPTION
**Pull request by dabrahams**
@swift-ci Please test and merge

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please test Linux platform

**Comment by dabrahams** [comment]
@swift-ci please test and merge

**Comment by dabrahams** [comment]
@swift-ci Please test Linux platform

**Comment by dabrahams** [comment]
@swift-ci Please smoke test OS X platform

**Comment by natecook1000** [comment]
@swift-ci Please smoke test

**Review by natecook1000 — APPROVED** [review]
LGTM!

**Comment by dabrahams** [comment]
@swift-ci Please test Linux platform

**Comment by dabrahams** [comment]
@swift-ci Please test and merge

**Pull request merged**
