### PR TITLE
[DNM] Enable experimental concurrency mode by default

### PR DESCRIPTION
**Pull request by DougGregor**

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by kavon** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by kavon** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci Please Build Toolchain Linux

**Comment by DougGregor** [comment]
The macOS failure appears to be because we are still implicitly importing the `_Concurrency` module when building a `.swiftinterface` (for Combine, in this case) into a `.swiftmodule`. We should probably disable it there, too.

**Comment by DougGregor** [comment]
The Linux failure is a real source compatibility problem due to our theft of `await` as a keyword:

```
/home/buildnode/jenkins/workspace/swift-PR-toolchain-Linux/branch-main/swiftpm/swift-tools-support-core/Sources/TSCBasic/Await.swift:18:28: error: value of type '(@escaping (Result<T, ErrorType>) -> Void) -> Void' has no member 'get'
16:46:46     return try await(body).get()
16:46:46                     ~~~~~~ ^~~
16:46:46 /home/buildnode/jenkins/workspace/swift-PR-toolchain-Linux/branch-main/swiftpm/swift-tools-support-core/Sources/TSCBasic/Await.swift:18:16: error: 'await' in a function that does not support concurrency
16:46:46     return try await(body).get()
16:46:46                ^
16:46:46 /home/buildnode/jenkins/workspace/swift-PR-toolchain-Linux/branch-main/swiftpm/swift-tools-support-core/Sources/TSCBasic/Await.swift:17:13: note: add 'async' to function 'await' to make it asynchronous
16:46:46 public func await<T, ErrorType>(_ body: (@escaping (Result<T, ErrorType>) -> Void) -> Void) throws -> T {
16:46:46             ^
16:46:46 ninja: build stopped: subcommand failed.
```

**Comment by kavon** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by kavon** [comment]
@swift-ci Please Build Toolchain Linux Platform

**Comment by kavon** [comment]
@swift-ci please test source compatibility

**Comment by kavon** [comment]
Hmm. Looks like there's still an issue with the macOS toolchain build, with respect to `swift-macosx-arm64` and the first few components while building:

```
FAILED: stdlib/toolchain/Compatibility51/CMakeFiles/swiftCompatibility51-macosx-arm64e.dir/Overrides.cpp.o 
/usr/local/bin/sccache /Users/buildnode/jenkins/workspace/swift-PR-toolchain-osx/branch-main/buildbot_osx/llvm-macosx-arm64/./bin/clang++ -DCMARK_STATIC_DEFINE -DGTEST_HAS_RTTI=0 -DLLVM_DISABLE_ABI_BREAKING_CHECKS_ENFORCING=1 -DSWIFT_INLINE_NAMESPACE=__runtime -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Istdlib/toolchain/Compatibility51 -I/Users/buildnode/jenkins/workspace/swift-PR-toolchain-osx/branch-main/swift/stdlib/toolchain/Compatibility51 -I/Users/buildnode/jenkins/workspace/swift-PR-toolchain-osx/branch-main/swift/stdlib/include -I/include -Iinclude -I/Users/buildnode/jenkins/workspace/swift-PR-toolchain-osx/branch-main/swift/include -I/Users/buildnode/jenkins/workspace/swift-PR-toolchain-osx/branch-main/llvm-project/llvm/include -I/Users/buildnode/jenkins/workspace/swift-PR-toolchain-osx/branch-main/buildbot_osx/llvm-macosx-arm64/include -I/Users/buildnode/jenkins/workspace/swift-PR-toolchain-osx/branch-main/llvm-project/clang/include -I/Users/buildnode/jenkins/workspace/swift-PR-toolchain-osx/branch-main/buildbot_osx/llvm-macosx-arm64/tools/clang/include -I/Users/buildnode/jenkins/workspace/swift-PR-toolchain-osx/branch-main/cmark/src -I/Users/buildnode/jenkins/workspace/swift-PR-toolchain-osx/branch-main/buildbot_osx/cmark-macosx-arm64/src -gline-tables-only -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -fdiagnostics-color -Werror=switch -Wdocumentation -Wimplicit-fallthrough -Wunreachable-code -Woverloaded-virtual -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -O2  -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -fvisibility=hidden -fvisibility-inlines-hidden  -fno-exceptions -fno-rtti -Werror=gnu -UNDEBUG -fno-sanitize=all -Wall -Wglobal-constructors -Wexit-time-destructors -DSWIFT_COMPATIBILITY_LIBRARY=1 -DSWIFT_TARGET_LIBRARY_NAME=swiftCompatibility51 -target arm64e-apple-macosx10.9 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -arch arm64e -F/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/../../../Developer/Library/Frameworks -mmacosx-version-min=10.9 -O2 -g -DNDEBUG -DSWIFT_LIBRARY_EVOLUTION=1 -DSWIFT_RUNTIME_OS_VERSIONING -std=c++14 -MD -MT stdlib/toolchain/Compatibility51/CMakeFiles/swiftCompatibility51-macosx-arm64e.dir/Overrides.cpp.o -MF stdlib/toolchain/Compatibility51/CMakeFiles/swiftCompatibility51-macosx-arm64e.dir/Overrides.cpp.o.d -o stdlib/toolchain/Compatibility51/CMakeFiles/swiftCompatibility51-macosx-arm64e.dir/Overrides.cpp.o -c /Users/buildnode/jenkins/workspace/swift-PR-toolchain-osx/branch-main/swift/stdlib/toolchain/Compatibility51/Overrides.cpp
error: failed to execute compile
caused by: Compiler not supported
```

Perhaps `main` wasn't in a good state when I triggered it...

**Comment by kavon** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by DougGregor** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by kavon** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by kavon** [comment]
@swift-ci please test source compatibility

**Comment by kavon** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by kavon** [comment]
@swift-ci Please Build Toolchain Linux Platform

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci build toolchain

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by MaxDesiatov** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by kavon** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by kavon** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by kavon** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by kavon** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by DougGregor** [comment]
@swift-ci please build toolchain

**Pull request closed without merging**
