### PR TITLE
IRGen should not emit bodies of public_external functions

### PR DESCRIPTION
**Pull request by swiftix**
The only exception from this rule are those public_external functions that should always be emitted into the client code.

Recent changes that eliminated the -sil-serialize-all mode and adding this check to IRGen allow us to get rid of ExternalFunctionDefinitionsElimination and ExternalDefsToDecls passes, which are not needed anymore.

### CODE REVIEW

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci Please test source compatibility

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci Please test source compatibility

**Comment by swiftix** [comment]
@swift-ci Please test source compatibility

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by swiftix** [comment]
@swift-ci Please test source compatibility

**Comment by swiftix** [comment]
@swift-ci please test OS X

**Comment by swiftix** [comment]
@swift-ci please test OS X

**Comment by swiftix** [comment]
@swift-ci please test OS X

**Comment by swiftix** [comment]
@swift-ci Please test source compatibility

**Comment by swiftix** [comment]
@swift-ci Please test source compatibility

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
The source compatibility failure is unrelated and exists on master. The other failure is also unrelated was fixed by #12388

**Comment by slavapestov** [comment]
Awesome work @swiftix!

**Pull request merged**
