### PR TITLE
[CS] Fix locator for dynamic member key-path IUO unwrap

### PR DESCRIPTION
**Pull request by hamishknight**
We need to be looking at the callee locator for the recorded IUO unwrap when rewriting in CSApply. In addition, clean up a bit of code and improve a diagnostic for dynamic member lookup.

SR-15249

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
@swift-ci please test

**Review by xedin — APPROVED** [review]
Thank you!

**Pull request merged**
