### PR TITLE
[PrintAsObjC] More tweaks to +new unavailability

### PR DESCRIPTION
**Pull request by jrose-apple**
Another follow-up to #12295. Downgrades `+new` unavailability to deprecation in pre-Swift-5 modes. The general policy has been that even if something crashes at run time, we don't make it a hard error in Swift 4 mode (or Swift 3 mode!) if it wasn't a hard error in Swift 4.0 (3.0). In this case, we thought we could get away with it, and then it turns out it actually caused some problems. (And as #13320 shows, we can still make mistakes.)

This change isn't perfect because the diagnostic appears in *clients* rather than in the module that's being compiled as Swift 4 (instead of Swift 5). But it still means that someone who hasn't changed *anything* from a valid Swift 4.0 project will be able to compile without any changes, even if they were relying on being able to call `+new` when `-init` was unavailable for some reason.

Finally, include a message when making `+new` unavailable / deprecated. We've seen a few people run into this and not know what changed.

rdar://problem/35942058

### CODE REVIEW

**Comment by jrose-apple** [comment]
@JaviSoto, @DougGregor, what do you think of this one? I think we got the most important change already, but this might still improve the state of the world.

**Comment by jrose-apple** [comment]
@swift-ci Please test macOS

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test Linux

**Comment by JaviSoto** [comment]
I love the idea of the explicit error message. The policy for avoiding breaking changes is totally fair too.
Sorry for breaking so many things :( I definitely learned a lot from this one!

**Review by DougGregor — APPROVED** [review]
LGTM

**Comment by jrose-apple** [comment]
Don't stress about it, Javi. It was listed as a starter bug and none of us thought too deeply about it either. That's the reviewer's responsibility more than a spare-time contributor's! We're still in a better place for you adding this. :-)

**Comment by JaviSoto** [comment]
Thank you Jordan <3

**Pull request merged**
