### PR TITLE
Introduce LoweredSILRequest

### PR DESCRIPTION
**Pull request by hamishknight**
Add a request that produces lowered SIL for a file or module and use it in IRGenRequest if no SILModule is provided.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please smoke test

**Review by CodaFi — APPROVED** [review]
:shipit:

**Comment by hamishknight** [comment]
@swift-ci please smoke test macOS

**Comment by hamishknight** [comment]
@swift-ci please smoke test macOS

**Pull request merged**
