### PR TITLE
Merge 2020-06-02 into tensorflow

### PR DESCRIPTION
**Pull request by xihui-wu**

### CODE REVIEW

**Comment by xihui-wu** [comment]
@swift-ci Please clean test TensorFlow

**Comment by xihui-wu** [comment]
@swift-ci Please clean test TensorFlow

**Comment by xihui-wu** [comment]
@swift-ci Please clean test TensorFlow

**Comment by dan-zheng** [comment]
macOS CI failures are expected, the CI machine needs to be upgraded to macOS 10.15.

```
Failing Tests (5):
    Swift(macosx-x86_64) :: Python/python_lint.swift
    Swift(macosx-x86_64) :: IRGen/prespecialized-metadata/class-inmodule-2argument-1super-2argument-run.swift
    Swift(macosx-x86_64) :: IRGen/prespecialized-metadata/class-inmodule-1argument-run.swift
    Swift(macosx-x86_64) :: IRGen/prespecialized-metadata/class-inmodule-1argument-metatype-run.swift
    Swift(macosx-x86_64) :: IRGen/prespecialized-metadata/class-class-flags-run.swift
```
 
Let's go ahead and merge this PR despite the failures to unblock progress.

**Review by dan-zheng — APPROVED** [review]

**Pull request merged**
