### PR TITLE
[Experiment/DNM] @package imports found via fast dependency scanning

### PR DESCRIPTION
**Pull request by owenv**
This is just an experiment to see if the dependency scanner + explicit module builds is a good approach for package imports by way of an `@package` attribute.

### CODE REVIEW

**Comment by owenv** [comment]
@swift-ci smoke test

**Comment by owenv** [comment]
@swift-ci please build macOS toolchain

**Comment by owenv** [comment]
@swift-ci please build toolchain macOS

**Comment by DougGregor** [comment]
Very cool idea!

**Comment by owenv** [comment]
@swift-ci smoke test

**Comment by owenv** [comment]
@swift-ci smoke test

**Comment by owenv** [comment]
@swift-ci please build toolchain macOS

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
