### PR TITLE
[Preset] Disable LLDB tests from PR testing and Swift package preset.…

### PR DESCRIPTION
**Pull request by shahmishal**
… <rdar://problem/30271691>

### CODE REVIEW

**Comment by shahmishal** [comment]
cc/ @chrisbieneman 

@swift-ci Please test and merge

**Comment by slavapestov** [comment]
I hope this is just temporary :)

**Comment by shahmishal** [comment]
@chrisbieneman requested we disable LLDB tests because they are unstable. He might be able to provide more detail on how long we will have this disabled for.

**Comment by llvm-beanz** [comment]
At the moment the LLDB test suite has failures that the team has been unable to stay on top of. This patch disables the LLDB tests only for nightly packages produced off master, so that they can be more reliably released, and it gets LLDB test failures out of the way of blocking Swift compiler development via PR testing.

Hopefully we will be able to invest in the reliability of the test suite in the future and reverse this, however we currently don't have the resources to make that commitment.

**Pull request merged**
