### PR TITLE
[NFC] Refactor CSApply's ExprWalker a bit and propagate closure check…

### PR DESCRIPTION
**Pull request by CodaFi**
…ing errors

There is exactly one place where the 'skipClosures' condition needs to be
honored, and that is when applying the solution.

Also, teach typeCheckClosureBody to propagate failures
outward instead of ignoring them.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by rudkx** [comment]
"Great minds, etc." : https://github.com/rudkx/swift/commit/1812ee96753ee6cced4ac078ef2d543fc2870088

I think I missed a spot which is why I was still seeing some failures.

**Comment by rudkx** [comment]
BTW, it's definitely not NFC if it fixes the crashes.

**Comment by CodaFi** [comment]
> BTW, it's definitely not NFC if it fixes the crashes.

This patch alone doesn't fix the crash, this was just cleanup that I noticed after you commented on the spot fix.

**Comment by rudkx** [comment]
Ah, okay, I didn't review the change in detail yet and it looked like perhaps it was enough to avoid making it to the place where we crash.

**Review by rudkx — APPROVED** [review]
LGTM.

**Comment by CodaFi** [comment]
⛵️

**Pull request merged**
