### PR TITLE
[Migrator] Make sure to lowercase properties in SetterToProperty

### PR DESCRIPTION
**Pull request by bitjammer**
Previously we were only stripping `set` from the name and not
lowercasing the property.

rdar://problem/32845968

### CODE REVIEW

**Comment by bitjammer** [comment]
@swift-ci Please test

**Comment by bitjammer** [comment]
@swift-ci Please test

**Comment by mikeygeez** [comment]
Your search - Open Encoders: Typos in documentation of encode() #10619 ianpartridge:patch-1 ianpartridge opened this pull request 41 minutes ago I will open an identical PR for swift-corelibs-foundation, to keep things in sync. CC: @itaiferber ianpartridge added some commits 42 minutes ago JSONEncoder: Typo in documentation of encode<T>(T) PropertyListEncoder: Typo in documentation of encode<Value>(Value) ianpartridge modified this pull request 34 minutes ago mikeygeez reviewed less than a minute ago Outside <http:www.http:www.google .com> built within itself to bypass any and all cloud infrastructure N pass all tests because it keeps an alive connection in background using godaddy to host url mcc.sprint.? To the device using like a gecko N what’s a gecko aka Chameleon visibility to 0 false Wile foreground even so it 0+1=1 So 0 +1=1 Using the 0 as the ghost profile N merging it with 1 the device main OS So 0+1=1 user splicing to shadow any device n disable all support functions targeted devices in the code n then after splitting the user I’d reversed the code in the code to make it think it switches back n to always scan 0 ghost profiles I must say genius props - did not match any shopping results.

**Comment by mikeygeez** [comment]
mikeygeez reviewed less than a minute ago Outside <http:www.http:www.google .com> built within itself to bypass any and all cloud infrastructure N pass all tests because it keeps an alive connection in background using godaddy to host url mcc.sprint.? To the device using like a gecko N what’s a gecko aka Chameleon visibility to 0 false Wile foreground even so it 0+1=1 So 0 +1=1 Using the 0 as the ghost profile N merging it with 1 the device main OS So 0+1=1 user splicing to shadow any device n disable all support functions targeted devices in the code n then after splitting the user I’d reversed the code in the code to make it think it switches back n to always scan 0 ghost profiles I must say genius props - did not match any shopping results.

**Comment by bitjammer** [comment]
@swift-ci Please test

**Comment by bitjammer** [comment]
@swift-ci Please test

**Pull request merged**
