### PR TITLE
[stdlib] Free function + into static func +

### PR DESCRIPTION
**Pull request by moiseev**

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please test and merge

**Comment by moiseev** [comment]
@swift-ci Please test macOS platform

**Comment by moiseev** [comment]
@swift-ci Please test macOS platform

**Comment by jrose-apple** [comment]
Why are these on Sequence instead of RangeReplaceableCollection?

**Comment by xedin** [comment]
I concur with @jrose-apple - I think the only one which has to stay in Sequence is `<Other : RangeReplaceableCollection>(Self, Other)` (where `Self` is `Sequence`) but we can move the rest to `RangeReplaceableCollection` right?

**Comment by moiseev** [comment]
Because I tried to put them all in `extension RangeReplaceableCollection` first and it introduced an ambiguity 🤷‍♂️, that is avoided with this approach.

**Comment by moiseev** [comment]
To me it seems more logical to group `S -> RRC -> RRC` and `RRC -> S -> RRC` together.

**Comment by jrose-apple** [comment]
Putting them on RRC may actually be more efficient if we ever get to change how operator lookup works, so it might be worth investigating that ambiguity.

**Pull request merged**
