### PR TITLE
[DRAFT] Just for testing source compat

### PR DESCRIPTION
**Pull request by gottesmm**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test source compatibility suite

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
Interesting error in two ways:

1. The problem here is that part of PredictableMemOpt uses the linear lifetime checker to determine where to put compensating releases and we inserted a compensating release before some end_borrows that already existed for the value in the "leaking block".

2. The "leaking block" in this case was an asserting block, so we could have used DeadEndBlocks to not insert the release at all and instead just leak the value.

**Comment by gottesmm** [comment]
3. I wonder if we could get it wrong if we promoted a load_borrow and a load [copy] and cause this error ourselves... Hmmm...

**Comment by gottesmm** [comment]
I think I can fix this by:

1. Always inserting the destroy_value/end_borrow at the end of the block (modulo noreturn apply/terminators).
2. Having a set of end_borrow that /we/ inserted and if our destroy_value is before them, move the destroy_value after.

**Comment by gottesmm** [comment]
With a local fix that I have, I compile swiftpm.

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
Weirdly, I am not reproducing that crash locally. I am going to try and use the exact preset. Lets see what comes up.

**Comment by gottesmm** [comment]
Just produced a toolchain locally without hitting this Hmmm....

**Comment by gottesmm** [comment]
Trying to build again this time using the exact preset from the bots (instead of the toolchain).

@shahmishal is there any reason why we aren't just using the build toolchain option? We could add support to that tool for sccache.

**Comment by gottesmm** [comment]
Alright finally reproduced.

**Comment by gottesmm** [comment]
```

**Comment by gottesmm** [comment]
```

**Comment by gottesmm** [comment]
This is the bad function:

```
sil private [ossa] @$s18SourceControlTests15DummyRepository33_930BD6D7F12677EEB688E87EF3E216CDLLC5fetchyyKF : $@conventio[51/1849] (@guaranteed DummyRepository) -> @error Error {                                                                                  // %0                                             // users: %3, %1                                                                bb0(%0 : @guaranteed $DummyRepository):                                                                                             debug_value %0 : $DummyRepository, let, name "self", argno 1 // id: %1                                                            debug_value undef : $Error, var, name "$error", argno 2 // id: %2                                                                 %3 = ref_element_addr %0 : $DummyRepository, #DummyRepository.provider // user: %4                                                %4 = load_borrow %3 : $*@sil_unowned DummyRepositoryProvider // users: %6, %5                                                     %5 = copy_unowned_value %4 : $@sil_unowned DummyRepositoryProvider // users: %8, %28                                              end_borrow %4 : $@sil_unowned DummyRepositoryProvider // id: %6                                                                   %7 = integer_literal $Builtin.Int64, 1          // user: %15                                                                      %8 = begin_borrow %5 : $DummyRepositoryProvider // users: %25, %11, %23                                                           %9 = alloc_stack $Int                           // users: %21, %26, %13                                     
  // function_ref DummyRepositoryProvider.numFetches.getter                                                                       
  %10 = function_ref @$s18SourceControlTests23DummyRepositoryProvider33_930BD6D7F12677EEB688E87EF3E216CDLLC10numFetchesSivg : $@co
nvention(method) (@guaranteed DummyRepositoryProvider) -> Int // user: %11
  %11 = apply %10(%8) : $@convention(method) (@guaranteed DummyRepositoryProvider) -> Int // users: %12, %13
  %12 = struct_extract %11 : $Int, #Int._value    // user: %15
  store %11 to [trivial] %9 : $*Int               // id: %13
  %14 = integer_literal $Builtin.Int1, -1         // user: %15
  %15 = builtin "sadd_with_overflow_Int64"(%12 : $Builtin.Int64, %7 : $Builtin.Int64, %14 : $Builtin.Int1) : $(Builtin.Int64, Buil
tin.Int1) // user: %16
  (%16, %17) = destructure_tuple %15 : $(Builtin.Int64, Builtin.Int1) // users: %20, %18
  cond_fail %17 : $Builtin.Int1                   // id: %18
  %19 = tuple ()
  %20 = struct $Int (%16 : $Builtin.Int64)        // users: %25, %21
  store %20 to [trivial] %9 : $*Int               // id: %21
  %22 = tuple ()
  end_borrow %8 : $DummyRepositoryProvider        // id: %23
  // function_ref DummyRepositoryProvider.numFetches.setter
  %24 = function_ref @$s18SourceControlTests23DummyRepositoryProvider33_930BD6D7F12677EEB688E87EF3E216CDLLC10numFetchesSivs : $@co
nvention(method) (Int, @guaranteed DummyRepositoryProvider) -> () // user: %25
  %25 = apply %24(%20, %8) : $@convention(method) (Int, @guaranteed DummyRepositoryProvider) -> ()
  dealloc_stack %9 : $*Int                        // id: %26
  %27 = tuple ()
  destroy_value %5 : $DummyRepositoryProvider     // id: %28
  %29 = tuple ()                                  // user: %30
  return %29 : $()                                // id: %30
} // end sil function '$s18SourceControlTests15DummyRepository33_930BD6D7F12677EEB688E87EF3E216CDLLC5fetchyyKF'
```

**Comment by gottesmm** [comment]
(edited the bad SIL in the PR. Had a copy/paste problem).

**Comment by gottesmm** [comment]
Notice the uses of %8.

**Comment by gottesmm** [comment]
2.      While running pass #4854 SILModuleTransform "MandatoryInlining".

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
Looks like only 2 source compat failures in debug!

```
01:49:30   FAIL: Chatto, 4.0.3, 3e4b1a, ChattoApp, generic/platform=iOS
01:49:30   FAIL: Chatto, 4.0.3, 3e4b1a, ChattoAdditions, generic/platform=iOS
01:49:30   FAIL: Chatto, 4.0.3, 3e4b1a, Chatto, generic/platform=iOS
01:49:30   FAIL: CoreStore, 5.0, b2dba0, CoreStore watchOS, generic/platform=watchOS
01:49:30   FAIL: CoreStore, 5.0, b2dba0, CoreStore tvOS, generic/platform=tvOS
01:49:30   FAIL: CoreStore, 5.0, b2dba0, CoreStore OSX, generic/platform=macOS
01:49:30   FAIL: CoreStore, 5.0, b2dba0, CoreStore iOS, generic/platform=iOS
01:49:30   FAIL: CoreStore, 4.2, 286360, CoreStore watchOS, generic/platform=watchOS
01:49:30   FAIL: CoreStore, 4.2, 286360, CoreStore tvOS, generic/platform=tvOS
01:49:30   FAIL: CoreStore, 4.2, 286360, CoreStore OSX, generic/platform=macOS
01:49:30   FAIL: CoreStore, 4.2, 286360, CoreStore iOS, generic/platform=iOS
01:49:30   FAIL: CoreStore, 4.0, 83e608, CoreStore watchOS, generic/platform=watchOS
01:49:30   FAIL: CoreStore, 4.0, 83e608, CoreStore tvOS, generic/platform=tvOS
01:49:30   FAIL: CoreStore, 4.0, 83e608, CoreStore OSX, generic/platform=macOS
01:49:30   FAIL: CoreStore, 4.0, 83e608, CoreStore iOS, generic/platform=iOS
```

**Comment by gottesmm** [comment]
The core store one should be an easy fix (small cast optimizer issue). The chatto one I need to investigate (says we are leaking, could be a real leak).

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compat suite

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
Re-reving the test to see where we are now.

**Comment by gottesmm** [comment]
@swift-ci test source compat suite

**Comment by gottesmm** [comment]
@swift-ci test source compat suite

**Comment by gottesmm** [comment]
The new swiftpm failure was: https://github.com/apple/swift/pull/27902. I included the fix for that in this branch.

**Comment by gottesmm** [comment]
@swift-ci test source compat suite

**Comment by gottesmm** [comment]
@swift-ci test source compat suite

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
