### PR TITLE
[Serialization] Wire up the generic parameter of a protocol early.

### PR DESCRIPTION
**Pull request by DougGregor**
When we deserialize a protocol declaration, we had a bunch of
intervening code before it would deserialize and wire up its generic
parameter (`Self`), including configuring the generic environment. If
any of that code referenced an `AssociatedTypeDecl` of that protocol,
the deserialization of the AssociatedTypeDecl could end up computing
an erroneous type.

This might be the source of the nondeterministic deserialization
failure that seems to afflict `AssociatedTypeDecls` in
rdar://problem/30382791.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by slavapestov** [comment]
But why was it non-deterministic?

**Comment by DougGregor** [comment]
... we still don't know the source of nondeterminism here.

**Comment by jrose-apple** [comment]
Looks like this didn't do it. :-( https://ci.swift.org/job/oss-swift_tools-RA_stdlib-RDA_long-test/1624

**Pull request merged**
