### PR TITLE
Update RangeGenerator.next() function for removal of ++ operator

### PR DESCRIPTION
**Pull request by nielsandriesse**
Related to: https://github.com/apple/swift-evolution/blob/master/proposals/0004-remove-pre-post-inc-decrement.md

### CODE REVIEW

**Comment by nielsandriesse** [comment]
Comparison of SIL: https://gist.github.com/nielsandriesse/708f80d3446a63fefb5f

**Comment by nielsandriesse** [comment]
Performance seems identical (optimized build): https://gist.github.com/nielsandriesse/69021ed7cedf239696c4

**Comment by gribozavr** [comment]
@nadavrot This PR needs attention from your team.

**Comment by lattner** [comment]
The SIL looks the same to me.

**Comment by lattner** [comment]
Thanks Niels!

**Comment by nadavrot** [comment]
The new SIL looks worse (see BB2). There is an extra copy_add, inject_enum_add, and 2 destroy_ instructions. 9 instructions vs 5 instructions.

**Comment by lattner** [comment]
Ah, I'm sorry I missed that, feel free to revert if you think that is the best path, sorry for jumping the gun.

**Comment by nielsandriesse** [comment]
Considering the pending removal of these operators, I filed a bug for this optimization case: https://bugs.swift.org/browse/SR-213

**Comment by nadavrot** [comment]
@lattner No problem.  

Our internal performance tracking system detected a few regressions for -Onone, but nothing for -O.

Let's keep this commit in the tree. I don't see a reason to hinder progress.   

@atrick @aschwaighofer Can we optimize BB3 in the second SIL file?

**Pull request merged**
