### PR TITLE
[Concurrency] Teach `Type::stripConcurrency` about tuples, sugared types, and bound generic types

### PR DESCRIPTION
**Pull request by xedin**
In recursive mode strip sendable and other concurrency use from all aforementioned types in 
`@preconcurrency` declarations.

### CODE REVIEW

**Comment by slavapestov** [comment]
Can we instead use Type::transformRec() to handle all the cases simultaneously?

**Comment by xedin** [comment]
I can do that separately, don't want to change too much because I want to get it into 5.10.

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Review by hborla — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Pull request merged**
