### PR TITLE
Sema: Follow-on fix for <https://github.com/apple/swift/pull/6267> [3.1]

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes <https://bugs.swift.org/browse/SR-3656> and <rdar://problem/30058733>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@DougGregor can you review this for 3.1 please?

**Comment by slavapestov** [comment]
@swift-ci Please test

**Review by DougGregor — APPROVED** [review]
LGTM. Does  this cover the enum case as well?

**Comment by slavapestov** [comment]
I'll add a test.

**Comment by slavapestov** [comment]
The following crashes in Swift 3.0 GM, and master in Swift 3 mode (a faithful simulation!):

```
enum HasAnyCase {
  case any(_: Any)
}

HasAnyCase.any(data: 123)
```

I'll fix the crash too since it's straightforward.

**Comment by slavapestov** [comment]
@DougGregor I fixed the enum case crash. Care to take another look?

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by DougGregor** [comment]
Okay, thanks! LGTM

**Pull request merged**
