### PR TITLE
Un-set CMAKE_C_COMPILER_LAUNCHER and CMAKE_CXX_COMPILER_LAUNCHER in s…

### PR DESCRIPTION
**Pull request by shahmishal**
…tdlib and unittests

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test macOS

**Comment by shahmishal** [comment]
@swift-ci test macOS

**Comment by shahmishal** [comment]
@swift-ci smoke test Linux

**Comment by gottesmm** [comment]
What happens if you use distcc with this instead of sccache? Will distcc work correctly with a just built compiler?

**Comment by shahmishal** [comment]
Yes, it will work fine with distcc. Distcc will fail to find the compiler on remote server and build locally.

**Comment by shahmishal** [comment]
@swift-ci test macOS

**Comment by gottesmm** [comment]
That is unfortunate... That is going to make building with distcc really noisy and also make it hard to diagnose when /real/ distcc failures are happening. Can you add make this conditional on an option (enabled by default of course)? Can you make distcc being selected via build-script set that flag?

**Comment by gottesmm** [comment]
Or even hackier, I guess you could check what the CMAKE_C_COMPILER_LAUNCHER actually is and conditionalize based off that?

**Comment by shahmishal** [comment]
Yes, I was just thinking that. If it contains sscache don’t set it to empty string.

**Comment by shahmishal** [comment]
I will squash and merge. 

@swift-ci smoke test

**Review by gottesmm — APPROVED** [review]
I am fine with this.

**Pull request merged**
