### PR TITLE
[5.0] Cherry-pick changes to allow testing the OS or just-built Swift dylibs

### PR DESCRIPTION
**Pull request by mikeash**
Also a bit more work to ensure some additional tests respect this.

### CODE REVIEW

**Comment by mikeash** [comment]
This is a cherry-pick of https://github.com/apple/swift/pull/23598, https://github.com/apple/swift/pull/24003, and https://github.com/apple/swift/pull/24109, plus a couple of minor additions.

**Comment by kevints** [comment]
@swift-ci please test

**Comment by kevints** [comment]
The bot fails with an error compiling the dispatch overlay, which might suffer from the same issue (perhaps it's finding the system overlay dylibs rather than the just-built ones):

```
15:19:02 cd /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.0-branch/buildbot_incremental/swift-macosx-x86_64/stdlib/public/SDK/Dispatch && /usr/bin/python /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.0-branch/swift/utils/line-directive @/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.0-branch/buildbot_incremental/swift-macosx-x86_64/stdlib/public/SDK/Dispatch/QrFmE.txt -- /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.0-branch/buildbot_incremental/swift-macosx-x86_64/./bin/swiftc -c -sdk /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk -target arm64-apple-ios7.0 -resource-dir /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.0-branch/buildbot_incremental/swift-macosx-x86_64/./lib/swift -F /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/../../../Developer/Library/Frameworks -O -D INTERNAL_CHECKS_ENABLED -D SWIFT_ENABLE_RUNTIME_FUNCTION_COUNTERS -I /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.0-branch/buildbot_incremental/swift-macosx-x86_64/./lib/swift/iphoneos/arm64 -module-cache-path /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.0-branch/buildbot_incremental/swift-macosx-x86_64/./module-cache -no-link-objc-runtime -Xfrontend -sil-verify-all -Xfrontend -enable-resilience -Xfrontend -enable-sil-ownership -Xfrontend -enable-mandatory-semantic-arc-opts -Xfrontend -enforce-exclusivity=unchecked -swift-version 5 -swift-version 4 -autolink-force-load -warn-swift3-objc-inference-complete -Xfrontend -verify-syntax-tree -warn-implicit-overrides -Fsystem /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/PrivateFrameworks/ -module-link-name swiftDispatch -force-single-frontend-invocation -parse-as-library -o /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.0-branch/buildbot_incremental/swift-macosx-x86_64/stdlib/public/SDK/Dispatch/iphoneos/arm64/Dispatch.o @/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.0-branch/buildbot_incremental/swift-macosx-x86_64/stdlib/public/SDK/Dispatch/QrFmE.txt
15:19:02 
/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.0-branch/swift/stdlib/public/SDK/Dispatch/Queue.swift:100:108: error: missing argument label 'rawValue:' in call
15:19:02                                         return __dispatch_queue_attr_make_with_autorelease_frequency(attr, __dispatch_autorelease_frequency_t(0))
15:19:02                                                                                                                                               ^
15:19:02                                                                                                                                               rawValue: 
15:19:02 /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.0-branch/swift/stdlib/public/SDK/Dispatch/Queue.swift:100:73: error: value of optional type '__dispatch_autorelease_frequency_t?' must be unwrapped to a value of type '__dispatch_autorelease_frequency_t'
15:19:02                                         return __dispatch_queue_attr_make_with_autorelease_frequency(attr, __dispatch_autorelease_frequency_t(0))
15:19:02                                                                                                            ^
15:19:02 /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.0-branch/swift/stdlib/public/SDK/Dispatch/Queue.swift:100:73: note: coalesce using '??' to provide a default when the optional value contains 'nil'
15:19:02                                         return __dispatch_queue_attr_make_with_autorelease_frequency(attr, __dispatch_autorelease_frequency_t(0))
15:19:02                                                                                                            ^
15:19:02                                                                                                                                                  ?? <#default value#>
15:19:02 /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.0-branch/swift/stdlib/public/SDK/Dispatch/Queue.swift:100:73: note: force-unwrap using '!' to abort execution if the optional value contains 'nil'
15:19:02                                         return __dispatch_queue_attr_make_with_autorelease_frequency(attr, __dispatch_autorelease_frequency_t(0))
15:19:02                                                                                                            ^
15:19:02                                                                                                                                                 !
15:19:02 /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.0-branch/swift/stdlib/public/SDK/Dispatch/Queue.swift:103:108: error: missing argument label 'rawValue:' in call
15:19:02                                         return __dispatch_queue_attr_make_with_autorelease_frequency(attr, __dispatch_autorelease_frequency_t(1))
15:19:02                                                                                                                                               ^
15:19:02                                                                                                                                               rawValue: 
15:19:02 /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.0-branch/swift/stdlib/public/SDK/Dispatch/Queue.swift:103:73: error: value of optional type '__dispatch_autorelease_frequency_t?' must be unwrapped to a value of type '__dispatch_autorelease_frequency_t'
15:19:02                                         return __dispatch_queue_attr_make_with_autorelease_frequency(attr, __dispatch_autorelease_frequency_t(1))
15:19:02                                                                                                            ^
15:19:02 /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.0-branch/swift/stdlib/public/SDK/Dispatch/Queue.swift:103:73: note: coalesce using '??' to provide a default when the optional value contains 'nil'
15:19:02                                         return __dispatch_queue_attr_make_with_autorelease_frequency(attr, __dispatch_autorelease_frequency_t(1))
15:19:02                                                                                                            ^
15:19:02                                                                                                                                                  ?? <#default value#>
15:19:02 /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.0-branch/swift/stdlib/public/SDK/Dispatch/Queue.swift:103:73: note: force-unwrap using '!' to abort execution if the optional value contains 'nil'
15:19:02                                         return __dispatch_queue_attr_make_with_autorelease_frequency(attr, __dispatch_autorelease_frequency_t(1))
15:19:02                                                                                                            ^
15:19:02                                                                                                                                                 !
15:19:02 /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.0-branch/swift/stdlib/public/SDK/Dispatch/Queue.swift:106:108: error: missing argument label 'rawValue:' in call
15:19:02                                         return __dispatch_queue_attr_make_with_autorelease_frequency(attr, __dispatch_autorelease_frequency_t(2))
15:19:02                                                                                                                                               ^
15:19:02                                                                                                                                               rawValue: 
15:19:02 /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.0-branch/swift/stdlib/public/SDK/Dispatch/Queue.swift:106:73: error: value of optional type '__dispatch_autorelease_frequency_t?' must be unwrapped to a value of type '__dispatch_autorelease_frequency_t'
15:19:02                                         return __dispatch_queue_attr_make_with_autorelease_frequency(attr, __dispatch_autorelease_frequency_t(2))
15:19:02                                                                                                            ^
15:19:02 /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.0-branch/swift/stdlib/public/SDK/Dispatch/Queue.swift:106:73: note: coalesce using '??' to provide a default when the optional value contains 'nil'
15:19:02                                         return __dispatch_queue_attr_make_with_autorelease_frequency(attr, __dispatch_autorelease_frequency_t(2))
15:19:02                                                                                                            ^
15:19:02                                                                                                                                                  ?? <#default value#>
15:19:02 /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.0-branch/swift/stdlib/public/SDK/Dispatch/Queue.swift:106:73: note: force-unwrap using '!' to abort execution if the optional value contains 'nil'
15:19:02                                         return __dispatch_queue_attr_make_with_autorelease_frequency(attr, __dispatch_autorelease_frequency_t(2))
15:19:02                                                                                                            ^
15:19:02                                                                                                                                                 !
```

**Comment by shahmishal** [comment]
@swift-ci 5.0 test macOS

**Comment by shahmishal** [comment]
@swift-ci test 5.0 macOS

**Comment by shahmishal** [comment]
@swift-ci test 5.0 macOS

**Comment by shahmishal** [comment]
```
11:53:58 Failing Tests (5):
11:53:58     Swift(macosx-x86_64) :: execution/interpret-with-dependencies.swift
11:53:58     Swift(macosx-x86_64) :: SIL/Serialization/deserialize_stdlib.sil
11:53:58     Swift(macosx-x86_64) :: SIL/Serialization/deserialize_objectivec.sil
11:53:58     Swift(macosx-x86_64) :: SIL/Serialization/deserialize_darwin.sil
11:53:58     Swift(macosx-x86_64) :: SIL/Serialization/deserialize_coregraphics.swift
```

**Comment by shahmishal** [comment]
@swift-ci test 5.0 macOS

**Comment by shahmishal** [comment]
Two new failures: 

```
16:22:48 Failing Tests (2):
16:22:48     Swift(iphonesimulator-i386) :: stdlib/HashingRandomization.swift
16:22:48     Swift(iphonesimulator-i386) :: SILOptimizer/global_init_with_empty.swift
```

**Comment by shahmishal** [comment]
@swift-ci test 5.0 macOS

**Comment by shahmishal** [comment]
@swift-ci test 5.0 macOS

**Comment by kevints** [comment]
@swift-ci please test 5.0 with https://github.com/apple/swift-xcode-playground-support/pull/37

**Comment by shahmishal** [comment]
apple/swift-xcode-playground-support#37

@swift-ci please test 5.0

**Comment by shahmishal** [comment]
apple/swift-xcode-playground-support#37

@swift-ci please clean test 5.0

**Comment by jrose-apple** [comment]
The Dispatch thing is because Swift 5.0 needs to build against an Xcode 10.2 SDK.

**Pull request merged**
