### PR TITLE
Improve memory behaviour by recognizing let alloc_stacks

### PR DESCRIPTION
**Pull request by meg-gupta**

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by hyp** [comment]
Thanks, this fixes https://github.com/apple/swift/issues/61499

**Review by atrick — APPROVED** [review]
Thanks!

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Comment by meg-gupta** [comment]
Going to close this, because we need to first fix existing problems w.r.t inferring memory behavior of let's. Using @hyp's original commit with a test here - https://github.com/apple/swift/pull/61539

**Pull request closed without merging**
