### PR TITLE
caches: disable more components for the toolchain build

### PR DESCRIPTION
**Pull request by compnerd**
Windows builds in waves:
  - build build tools
  - build tools (compilers, debuggers, linkers, assemblers)
  - build runtimes (Swift runtime, standard library, experimental libraries)
  - build core libraries
  - build Swift tooling

We do not need to build the C++ interop module at the moment when building the tools.  This disables that and the extra content which currently does not result in any artifacts.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @airspeedswift @DougGregor @hyp

This is a cherry-pick from main that should repair the build for Windows nightlies.  This is just impacts the nightlies which use this file for configuration data for the build and has no impact on the actual compiler or standard library.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
This is presumably because we're not doing any bootstrapping on Windows?

**Review by DougGregor — APPROVED** [review]

**Comment by compnerd** [comment]
@DougGregor correct, because of the size of the toolchain, we cannot both install and build the toolchain on the builders.

**Pull request merged**
