### PR TITLE
Only bridge smol Strings to tagged NSStrings if we're pretty sure they'll fit, otherwise make a regular String

### PR DESCRIPTION
**Pull request by Catfish-Man**

### CODE REVIEW

**Comment by Catfish-Man** [comment]
@swift-ci please smoke benchmark

**Comment by Catfish-Man** [comment]
Hmph. PlistPerfEncode regressing is interesting… I should dig into that.

**Comment by Catfish-Man** [comment]
Also I should see how things change once I land eager smol bridging

**Comment by Catfish-Man** [comment]
Please test with following pull request:
https://github.com/apple/swift/pull/23409

@swift-ci please smoke benchmark

**Comment by Catfish-Man** [comment]
Sigh… looks like it didn't pick up the base PR. That's ok, I have more changes.

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
