### PR TITLE
[swift-stdlib-tool] Fix finding sibling directories

### PR DESCRIPTION
**Pull request by keith**
When used without passing `--source-libraries`, this tool fetches its
current path and uses that to find the directories of the swift
libraries near it.

Since https://github.com/apple/swift/pull/39216 it was searching the
nearby directories recursively, and only for files, instead of just
looking at 1 level, only for directories. Because of this it would never
discover `path/to/lib/swift-5.0/...` because it was only looking for
files.

This fixes this issue with a new function, and renames the previous
function to be more explicit for the other use case that does want that
behavior.

### CODE REVIEW

**Comment by keith** [comment]
cc @salinas-miguel @CodaFi

**Comment by keith** [comment]
I will submit a 5.6 cherry pick once this is reviewed, this is currently broken in Xcode 13.3 beta 1 which is how we discovered it

**Comment by keith** [comment]
@DougGregor since you're the 5.6 compiler release manager can you check this one out? I think we should cherry pick it to this release since it's a regression from 5.5

**Review by CodaFi — APPROVED** [review]

**Comment by CodaFi** [comment]
@swift-ci test

**Pull request merged**
