### PR TITLE
Revert "Revert "[ConstraintSystem] Use correct locator when filtering disjunc…"

### PR DESCRIPTION
**Pull request by xedin**
Reverts apple/swift#36335

test/Constraints/diagnostics.swift has been adjusted.

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by davezarzycki** [comment]
What PR fixed `test/Constraints/diagnostics.swift`?

**Comment by davezarzycki** [comment]
Never mind. I found it.

**Pull request closed without merging**
