### PR TITLE
[Deserialization] Configure protocol before loading requirement signature

### PR DESCRIPTION
**Pull request by DougGregor**
Fixes a crash when deserializing recursive protocol conformances,
rdar://problem/34681729.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by slavapestov** [comment]
Thanks!

**Comment by DougGregor** [comment]
Thanks for the tiny reproduction :)

**Comment by DougGregor** [comment]
@swift-ci please clean smoke test Linux

**Pull request merged**
