### PR TITLE
[Debugging] Use SWIFT_NATIVE_SWIFT_TOOLS_PATH if defined

### PR DESCRIPTION
**Pull request by kastiglione**
Fixes cross-host builds. See https://github.com/apple/swift/pull/71425/files#r1498582734

### CODE REVIEW

**Comment by kastiglione** [comment]
@swift-ci test

**Comment by kateinoigakukun** [comment]
@swift-ci Please build toolchain macOS platform

**Comment by kastiglione** [comment]
@swift-ci please build toolchain macOS platform

**Comment by kastiglione** [comment]
@swift-ci Please build toolchain macOS platform

**Review by kateinoigakukun — APPROVED** [review]

**Comment by kastiglione** [comment]
@swift-ci test linux

**Comment by kastiglione** [comment]
@swift-ci test windows

**Comment by kastiglione** [comment]
@swift-ci test windows

**Comment by kateinoigakukun** [comment]
@swift-ci smoke test macOS platform

**Comment by kastiglione** [comment]
@swift-ci smoke test macOS platform

**Comment by kastiglione** [comment]
@swift-ci smoke test windows

**Comment by kateinoigakukun** [comment]
@swift-ci smoke test macOS platform

**Comment by kastiglione** [comment]
@swift-ci smoke test windows

**Comment by kastiglione** [comment]
@swift-ci smoke test windows

**Comment by kastiglione** [comment]
@swift-ci smoke test macOS platform

**Pull request merged**
