### PR TITLE
[Diag] Remove following white space when removing tokens after l-paren

### PR DESCRIPTION
**Pull request by rintaro**
It's common to emit fix-it to remove the first token after l-paren.
For example, in this case

``` swift
func f(inout x: Int, inout y: Int) {}
```

`fixItRemove` used to remove the space after the second `inout`, but not for the first `inout`:

``` swift
func f( x: Int, y: Int) {}
       ~
```

Extend "extra work" in `fixItRemove` to remove these whitespace.
## 

Also, replaced `fixItRemoveChars` with `fixItReplace` where we can.
We prefer token range based fix-it, to minimally alter the source code.

Consider fixing:

``` swift
func foo(name /* comment */ name: Arg) {
```

Previously:

``` swift
  func foo(name: Arg) {
```

Now:

``` swift
  func foo(/* comment */ name: Arg) {
```

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
I'm concerned we're missing some more general rule here. What's special about `(`? It *is* often followed by two identifiers in a row, or a keyword and then an identifier, but the same is true after a newline. (Which, admittedly, is caught by the current rule.)

**Comment by rintaro** [comment]
Generally, I think, we *can* do this for every characters except that can form identifiers or operators.
Particularly, `(`, `)`, `{`, `}`, `[`, `]`, `,`, `:`, `;`, and `=`

And probably, we *should* do more.
For example, *if* we want to fix `= a+try some()`,
it should become `= try a+some()` instead of `= try a+ some()`

Hmm...

**Comment by jrose-apple** [comment]
Interesting. But for `(a.foo)! + b`, removing the `!` shouldn't produce `(a.foo)+ b`. So it's not as simple as saying "if either side is missing a space, we should remove the space".

**Comment by rintaro** [comment]
Good point. Now, I'm not sure what should we do 😕

**Comment by jrose-apple** [comment]
The complicated thing would be to add an optional argument to fixItRemove stating how to deal with space on either side. People could get that wrong, but at least it would be explicit. Is that too much trouble, though?

**Comment by lattner** [comment]
I think that adding a configuration flag to fixItRemove (or perhaps add a new variant of fixItRemove) is the right way to go.

**Comment by rintaro** [comment]
Thank you @jrose-apple @lattner !
I will try adding an optional argument to `fixItRemove`.
Before that, I need to figure out what is the reasonable default,
and how many variants are needed (`bool` or `enum`)

Anyway, I close this PR for now. Thanks again!

**Pull request closed without merging**
