### PR TITLE
[5.5][Concurrency] Propagate Darwin vouchers across async tasks.

### PR DESCRIPTION
**Pull request by mikeash**
Cherry pick https://github.com/apple/swift/pull/39115 to `release/5.5`.

Darwin OSes support vouchers, which are key/value sets that can be adopted on a thread to influence its execution, or sent to another process. APIs like Dispatch propagate vouchers to worker threads when running async code. This change makes Swift Concurrency do the same.

The change consists of a few different parts:

1. A set of shims (in VoucherShims.h) which provides declarations for the necessary calls when they're not available from the SDK, and stub implementations for non-Darwin platforms.
2. One of Job's reserved fields is now used to store the voucher associated with a job.
3. Jobs grab the current thread's voucher when they're created.
4. A VoucherManager class manages adoption of vouchers when running a Job, and replacing vouchers in suspended tasks.
5. A VoucherManager instance is maintained in ExecutionTrackingInfo, and is updated as necessary throughout a Job/Task's lifecycle.

This cherry-pick also incorporates:

* d5c0469f3eedb69e910f6e40fa9824192e09cc51 [Concurrency] Replace SWIFT_TASK_PRINTF_DEBUG with a SWIFT_TASK_DEBUG_LOG macro.
* 09f3d9932a6a3f8135d712d47f3f3afa9d4e3d27 [Concurrency] Add availability checking when calling voucher_needs_adopt from the SDK.
* c216d91a054b38529495127b8053a5029a98a4d5 [Concurrency] Use overload resolution to stub voucher_needs_adopt.

rdar://76080222

### CODE REVIEW

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test macos platform

**Review by al45tair — APPROVED** [review]

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
