### PR TITLE
Parser: avoid allocating delayed parser state on heap.

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by jrose-apple** [comment]
Hmm. Does the delayed parser state really stay alive as long as the ASTContext does?

**Comment by nkcsgexi** [comment]
Not really, they're not useful once the decl context is parsed. I think the creation and destroying of these states costs unnecessary memory manipulation. What do you think?

**Comment by jrose-apple** [comment]
I'm concerned about allocating things on the ASTContext that never go away, especially if we ever try to reuse the ASTContext for repeated parsing or multiple modules or something. Most of the other things we put there are either being uniqued or live for a long time. I don't know how to measure this tradeoff, though.

**Comment by nkcsgexi** [comment]
That's fair. Let's close this PR to keep the life cycle of `DelayedDeclListState` only necessary.

**Pull request closed without merging**
