### PR TITLE
Start removing typeCheckExpressionShallow()

### PR DESCRIPTION
**Pull request by slavapestov**
`typeCheckExpressionShallow()` is used in three places:
- Converting a Bool to an Int1
- Calling a closure in the REPL
- String interpolation

This PR nukes the first two.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by shahmishal** [comment]
@swift-ci Please smoke test macOS

**Pull request merged**
