### PR TITLE
DNM: all android changes 2 testing

### PR DESCRIPTION
**Pull request by hyp**

### CODE REVIEW

**Comment by hyp** [comment]
@swift-ci please build toolchain

**Comment by finagolfin** [comment]
Please rebuild the linux toolchain with apple/swift-package-manager#7615, as [I'm currently using your last build from a month ago](https://github.com/finagolfin/swift-android-sdk/pull/151/files#diff-76992bc322b65ab94f299c05ba3cbd8b3ab2e32ebfdde6db5adba70fa9f5a26aR130) to test these pulls on my Android CI and I had to [manually patch that overlay into the SwiftPM executable](https://github.com/finagolfin/swift-android-sdk/pull/151/files#diff-76992bc322b65ab94f299c05ba3cbd8b3ab2e32ebfdde6db5adba70fa9f5a26aR173) otherwise, as it generates a test runner file in Swift that has to have this new overlay.

So far, seven out of eleven of the Swift packages whose tests I run in the Android x86_64 emulator are passing, and I'm working on getting the remaining four NIO-based packages ported over to your new Android overlay.

**Comment by hyp** [comment]
Please test with following PR:
https://github.com/apple/swift-package-manager/pull/7615

@swift-ci Please build toolchain

**Comment by hyp** [comment]
Please test with following PR:
https://github.com/apple/swift-package-manager/pull/7615

@swift-ci Please build toolchain

**Pull request closed without merging**
