### PR TITLE
[Build System: CMake] Install the Swift shims in the stdlib component (5.1 branch).

### PR DESCRIPTION
**Pull request by Rostepher**
Copy of #23903 for the 5.1 branch.

### CODE REVIEW

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by Rostepher** [comment]
@swift-ci please test Linux

**Review by shahmishal — APPROVED** [review]

**Comment by Rostepher** [comment]
Unrelated LLDB test fails on Linux.

**Comment by Rostepher** [comment]
@swift-ci please test Linux

**Comment by Rostepher** [comment]
@swift-ci please build macOS toolchain

**Comment by Rostepher** [comment]
@swift-ci please build toolchain macOS platform

**Comment by Rostepher** [comment]
@swift-ci please build toolchain Linux platform

**Comment by shahmishal** [comment]
@swift-ci please build toolchain macOS

**Pull request merged**
