### PR TITLE
[DNM] remaining work for SIL COW representation

### PR DESCRIPTION
**Pull request by eeckstein**
The second part of https://github.com/apple/swift/pull/31728

Still work in progress. Not to be merged yet.

### CODE REVIEW

**Comment by eeckstein** [comment]
@dan-zheng Can you please help me fixing a small issue with AutoDiff?
Following tests are failing with this PR:
```
AutoDiff/stdlib/array.swift
AutoDiff/SILOptimizer/differentiation_activity_analysis.swift
```

The reason is that the SIL code for Array literals looks a bit different. After storing all elements, a new runtime function is called. For details see: https://github.com/apple/swift/pull/31730/commits/af196a1f781cb85bb37b743400b3a8c5813b8008

I think it's a simple fix to handle this runtime function, but I'm not really understanding the code.

**Comment by dan-zheng** [comment]
> @dan-zheng Can you please help me fixing a small issue with AutoDiff?

I can help take a look today, thanks for the context!

I wonder what is the urgency of this PR? I can try to share an update before EOD today.

**Comment by eeckstein** [comment]
Thanks, it's not urgent

**Comment by eeckstein** [comment]
@dan-zheng I rebased this PR.

**Comment by eeckstein** [comment]
@dan-zheng Any progress on this?
I'd like to land my changes this or next week.
If you don't have time, is it okay for you if I just temporarily disable the 2 AutoDiff tests?

**Comment by dan-zheng** [comment]
I will try to finish fixing the AutoDiff tests by tomorrow and share an update. Sorry for the delay!

(It would be ideal to keep the AutoDiff tests passing because users depend on the tested behavior.)

**Comment by eeckstein** [comment]
ok, thanks! BTW, I just rebased the PR.

**Comment by eeckstein** [comment]
@dan-zheng Is there any update?

**Comment by dan-zheng** [comment]
Yes, the AutoDiff fixes have been done in https://github.com/eeckstein/swift/pull/3 for a few days. Sorry for not clarifying that explicitly!

**Comment by eeckstein** [comment]
@dan-zheng Thanks!

**Pull request closed without merging**
