### PR TITLE
Introduce and use SWIFT_DELETE_OPERATOR_DELETED

### PR DESCRIPTION
**Pull request by hughbe**
Consolidates MSVC hacks, following #6828

### CODE REVIEW

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by hughbe** [comment]
@jckarter FYI, addressing your comments from #6828, sorry for the churn

**Comment by jckarter** [comment]
No worries, thanks @hughbe!

**Pull request merged**
