### PR TITLE
[IRGen] Introduce OptimizedIRRequest

### PR DESCRIPTION
**Pull request by hamishknight**
Introduce a request that returns the optimized IR for a whole-module or file, and use it in SILLLVMGen. For now this manually wraps the entire compiler pipeline, but eventually will be able to just call into IRGen.

### CODE REVIEW

**Comment by hamishknight** [comment]
https://github.com/apple/llvm-project/pull/1469

@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Review by CodaFi — APPROVED** [review]
I like where this is going. Swift LGTM.

**Comment by hamishknight** [comment]
https://github.com/apple/llvm-project/pull/1469

@swift-ci please test

**Pull request merged**
