### PR TITLE
[4.0] [QoI] Improve diagnostics of unsatisfied generic requirements

### PR DESCRIPTION
**Pull request by xedin**
* Description: Fixes a problem related to presence of InOutType in function parameters
which diagnostics related to generic parameter requirements didn't handle
correctly, and improves diagnostics for unsatisfied generic requirements
in operator applications, which we didn't attempt to diagnose at all.

* Origination: Once String because a Sequence some of the diagnostics degraded, this patch attempts to correct this situation by improving diagnostics to generic requirements.

* Risk: Low.

* Tested: Added new tests, Swift CI.

* Reviewed by: Doug Gregor, Jordan Rose.

* Resolves: rdar://problem/33477726
(cherry picked from commit 242006706e76436fe2b7d63d2863c42c12fb5f9e)

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@DougGregor please review for 4.0

**Review by DougGregor — APPROVED** [review]
LGTM!

**Pull request merged**
