### PR TITLE
Sema: Make -debug-generic-signatures output legible

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
Fixes missing/extra newlines and duplication so that the output is properly split into blocks.

### CODE REVIEW

**Comment by CodaFi** [comment]
I know there is at least one test that is Filechecking the output of this thing. Did it not change?

**Comment by AnthonyLatsis** [comment]
Yeah, all of them are passing locally.

**Comment by CodaFi** [comment]
Hm, I suppose that means we're just running FileCheck in its whitespace-agnostic mode. Do you have an example of what the new formatted output looks like?

@swift-ci smoke test

**Comment by AnthonyLatsis** [comment]
I think that's because there's nothing CHECKing what's in between the logical blocks, or in between multiple conformances. 

new/old

```swift
protocol P8 {
  associatedtype A
}

struct X0 { }

struct X1 { }

extension X1: P8 {
  typealias A = X0
}
```
```
0x7f8f8e828528 Module name=conditional_conformances
  0x7f8f8f0844e8 FileUnit file="/Users/anthonylatsis/Desktop/swift-source/swift/test/Generics/conditional_conformances.swift"
    0x7f8f8f0cec30 ProtocolDecl name=P8
Generic signature: <Self where Self : P8>
Canonical generic signature: <τ_0_0 where τ_0_0 : P8>

Protocol requirement signature:
conditional_conformances.(file).P8@/Users/anthonylatsis/Desktop/swift-source/swift/test/Generics/conditional_conformances.swift:353:10
Requirement signature: <Self>
Canonical requirement signature: <τ_0_0>

0x7f8f8e828528 Module name=conditional_conformances
  0x7f8f8f0844e8 FileUnit file="/Users/anthonylatsis/Desktop/swift-source/swift/test/Generics/conditional_conformances.swift"
    0x7f8f8f0cf078 ExtensionDecl line=361 base=X1
(normal_conformance type=X1 protocol=P8
  (assoc_type req=A type=X0))
```
```
0x7ff34e828528 Module name=conditional_conformances
  0x7ff33e8004e8 FileUnit file="/Users/anthonylatsis/Desktop/swift-source/swift/test/Generics/conditional_conformances.swift"
    0x7ff31e849230 ProtocolDecl name=P8

Generic signature: <Self where Self : P8>
Canonical generic signature: <τ_0_0 where τ_0_0 : P8>
Protocol requirement signature:
conditional_conformances.(file).P8@/Users/anthonylatsis/Desktop/swift-source/swift/test/Generics/conditional_conformances.swift:353:10
Requirement signature: <Self>
Canonical requirement signature: <τ_0_0>
0x7ff34e828528 Module name=conditional_conformances
  0x7ff33e8004e8 FileUnit file="/Users/anthonylatsis/Desktop/swift-source/swift/test/Generics/conditional_conformances.swift"
    0x7ff31e849678 ExtensionDecl line=361 base=X1
(normal_conformance type=X1 protocol=P8
  (assoc_type req=A type=X0))conditional_conformances.(file).X2@/Users/anthonylatsis/Desktop/swift-source/swift/test/Generics/conditional_conformances.swift:365:8
```

**Review by CodaFi — APPROVED** [review]
Very nice!

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
