### PR TITLE
build: improve static library generation

### PR DESCRIPTION
**Pull request by compnerd**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

Modern `ar` implementations support constructing the index table on the
construction.  This means that we dont need to re-read the contents and run a
second program after the initial library construction to get current behaviour.
This is a simplification of the generated build rules which improves performance
since the data is not re-read nor a second tool invoked.

### CODE REVIEW

**Comment by compnerd** [comment]
CC @gribozavr

**Comment by compnerd** [comment]
ping

**Comment by gribozavr** [comment]
@compnerd How does this actually work?  The CMake documentation is scarce.

There is also `CMAKE_<LANG>_CREATE_STATIC_LIBRARY` (https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_CREATE_STATIC_LIBRARY.html#variable:CMAKE_<LANG>_CREATE_STATIC_LIBRARY) which is documented as "Rule variable to create a static library.", but you are not changing this variable.  The one that you are changing is documented as "It is used in place of CMAKE_<LANG>_CREATE_STATIC_LIBRARY on some platforms in order to support large object counts."

Sounds like we need to change both... it also does not help that CMake documentation does not explain it.

**Comment by compnerd** [comment]
@gribozavr right, the reason that Im modifying that rule is because that is the rule used to create static libraries using `ar`.  The reason that the FINISH rule is set to the empty string is because both the CREATE and APPEND are changed to use the `s` option to AR which creates the symbol list.  This means that the index is always up-to-date and there is no need to use `ranlib`.  This is why this is a small speed boost -- only a single tool is run and you only need to walk the content once.

**Comment by gribozavr** [comment]
So why don't we need to modify `CMAKE_<LANG>_CREATE_STATIC_LIBRARY`?  From the docs it looks like that rule should be the primary one used.

**Comment by gribozavr** [comment]
> because both the CREATE and APPEND are changed

Sorry, I'm not seeing the change to the APPEND rule in the patch.

**Comment by compnerd** [comment]
Ah, I guess I missed that when I did the `git add -p`. Ill upload a new version.  The reason why I dont modify the `CMAKE_<LANG>_CREATE_STATIC_LIBRARY` is because on certain toolchains, a static library is _not_ an archive.  We dont want to replace that rule as it may get that wrong.  The rule that I do modify is intended to be used specifically for static archives, which usually have the `ranlib` too run afterwards to generate the index.

**Comment by gribozavr** [comment]
> on certain toolchains, a static library is not an archive

I see.  CMake documentation makes it sound like the ARCHIVE and STATIC_LIBRARY rules are interchangeable if not for "large object counts".

@swift-ci Please test

**Pull request merged**
