### PR TITLE
Explicit code-block fence around doc code snippet.

### PR DESCRIPTION
**Pull request by invalidname**
Documentation: puts code-block fence syntax around a snippet in `AsyncStream` and `AsyncThrowingStream` whose formatting is ambiguous because it comes immediately after a numbered list.

Also fixes a grammatical error in the docs for `init(_:bufferingPolicy:_:)`.

This change only affects documentation comments.

### CODE REVIEW

**Comment by invalidname** [comment]
@swift-ci please smoke test

**Review by amartini51 — APPROVED** [review]

**Comment by invalidname** [comment]
@swift-ci please smoke test

**Comment by invalidname** [comment]
@swift-ci please smoke test

**Comment by invalidname** [comment]
@swift-ci please smoke test

**Pull request merged**
