### PR TITLE
Add Codable conformance to common CG types

### PR DESCRIPTION
**Pull request by itaiferber**
**What's in this pull request?**
Addresses [SR-5237](https://bugs.swift.org/browse/SR-5237).
Gives a custom `Codable` implementation for `CGAffineTransform`, `CGPoint`, `CGSize`, `CGRect`, and `CGVector`, along with unit tests.

### CODE REVIEW

**Comment by itaiferber** [comment]
@swift-ci Please test

**Comment by itaiferber** [comment]
Some large test values need to be gated on OS version for JSON.

**Comment by itaiferber** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
For my own edification, can you share the rationale for making these all unkeyed? It seems like the affine transform, at least, would benefit from labels in its default encoded representation.

**Comment by itaiferber** [comment]
@jrose-apple These types are the common currency types for doing most graphics work (macOS has `NSPoint`, `NSRect`, etc. from AppKit, but works with the CG variants when doing anything CG related, and iOS & co. use exclusively the CG versions) — they're often transacted upon and very often encoded. When they're encoded, they're usually encoded many many times over (think arrays of points to represent paths). Their representations are basically locked in forever; we can't change them without causing massive breakage across all OSes, so, it's relatively safe to do this, and it's more efficient than encoding keys.

**Comment by itaiferber** [comment]
Missed a `CGAffineTransform` test case

**Comment by itaiferber** [comment]
@swift-ci Please test

**Comment by itaiferber** [comment]
@swift-ci Please test

**Comment by itaiferber** [comment]
@swift-ci Please test macOS

**Comment by itaiferber** [comment]
@swift-ci Please smoke test Linux

**Review by phausler — APPROVED** [review]
looks reasonable to me

**Pull request merged**
