### PR TITLE
Update the ScanDependencies test to use `%target`

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test Apple Silicon

**Review by artemcm — APPROVED** [review]

**Review by artemcm — CHANGES_REQUESTED** [review]
`%target` seems to be doing the wrong thing, it substitutes `%t` to the test directory path.

**Comment by shahmishal** [comment]
Good point it should be `%target-cpu`

**Review by artemcm — APPROVED** [review]

**Comment by shahmishal** [comment]
@swift-ci test Apple Silicon

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test Apple Silicon

**Comment by shahmishal** [comment]
@swift-ci test macOS

**Comment by shahmishal** [comment]
@swift-ci smoke test Linux

**Comment by beccadax** [comment]
One of the input files has a `-target x86_64-apple-macosx10.9` embedded in it: https://github.com/apple/swift/blob/d3d87e844714b0ee03b308dc587091cbaad41375/test/ScanDependencies/Inputs/Swift/XWithTarget.swiftinterface#L2

We'd have to change this to a .swiftmodule directory with Intel and ARM variants of the swiftinterface to make this test run on arm64. Well, that or generate the file somehow.

**Comment by shahmishal** [comment]
```
--
Exit Code: 1

Command Output (stderr):
--
<unknown>:0: remark: did not find a prebuilt standard library for target 'x86_64-apple-macos' compatible with this Swift compiler; building it may take a few minutes, but it should only happen once for this combination of compiler and target
/Users/buildnode/jenkins/workspace/swift-PR-macos-apple-silicon/branch-main/swift/test/ScanDependencies/clang-target.swift:23:8: error: module 'XWithTarget' was created for incompatible target x86_64-apple-macosx10.9: /Users/buildnode/jenkins/workspace/swift-PR-macos-apple-silicon/branch-main/buildbot_incremental/swift-macosx-arm64/test-macosx-arm64/ScanDependencies/Output/clang-target.swift.tmp.module-cache/XWithTarget-3MQAMVCS0C8YL.swiftmodule
import XWithTarget
       ^

--
```

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test Apple Silicon

**Comment by xedin** [comment]
```
14:02:13 Failed Tests (2):
14:02:13   Swift(macosx-arm64) :: Driver/loaded_module_trace_foundation.swift
14:02:13   Swift(macosx-arm64) :: ScanDependencies/clang-target.swift
```

**Comment by artemcm** [comment]
The test needs a little bit more work.
@shahmishal , sorry for the trouble. I'm trying Becca's suggestion in:
https://github.com/apple/swift/pull/38086

**Comment by artemcm** [comment]
This issue is resolved in https://github.com/apple/swift/pull/38086, this PR can be closed now.
Thank you, @shahmishal!

**Comment by shahmishal** [comment]
@artemcm Thanks!

**Pull request closed without merging**
