### PR TITLE
[Docs] Fix minor code typo in SILProgrammersManual.md

### PR DESCRIPTION
**Pull request by Azoy**

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please smoke test and merge

**Comment by CodaFi** [comment]
The syntax in this document is weird and it seems incomplete.  Is this one to move to the historical pile, or is this being worked on still?

// @atrick, @gottesmm ?

**Comment by gottesmm** [comment]
@CodaFi this is actually something new that we are starting to fill out.

**Comment by atrick** [comment]
@CodaFi I removed a couple remnants of fake SIL syntax here:
https://github.com/apple/swift/pull/18413

What's weird and how would you better convey they information?

**Comment by CodaFi** [comment]
> What's weird

I just scanned the whole document for syntax after the patch got put up.  You got the nits I was thinking of in that patch.  Thanks!

**Pull request merged**
