### PR TITLE
SE-0193: Public default argument generators cannot reference declarations that are @usableFromInline

### PR DESCRIPTION
**Pull request by slavapestov**
Refactor resilience diagnostics to enforce more restrictions on default argument expressions of public functions. They can only reference other public declarations, and not @usableFromInline declarations.

This is a source-breaking change from Swift 4.1, where public default argument expressions could reference @_versioned declarations; hopefully nobody relied on that, but it would be easy enough to add an `isSwiftVersionAtLeast(5)` check in there if we have to.

### CODE REVIEW

**Comment by slavapestov** [comment]
@DougGregor @jrose-apple Can you two decide if we're taking this change, or if we're going to only allow public functions to be referenced from default arguments?

**Comment by jrose-apple** [comment]
I still would say no but I defer to @DougGregor (including @DougGregor deciding either the core team or the forums needs to discuss it).

**Comment by DougGregor** [comment]
The patch looks good, but I feel like we need core team approval to go ahead and merge it. I'll add it to the agenda for the upcoming meeting.

**Review by DougGregor — CHANGES_REQUESTED** [review]
The Core Team discussed this today and decided that default arguments should not be able to reference `@usableFromInline` entities that would otherwise be inaccessible. In other words, default arguments should follow the access-control rules strictly.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Review by jrose-apple — APPROVED** [review]
Thanks, this new version looks good. (We did some back-and-forth on internal chat.)

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Pull request merged**
