### PR TITLE
[benchmark] BucketSort gardening and adjustments

### PR DESCRIPTION
**Pull request by palimondo**
Increased workload to sorting of 10k items.
Used SplitMix64 PRNG for randomness.
Adjusted formatting and naming to match Swift conventions.
Adjusted documentation.

### CODE REVIEW

**Comment by palimondo** [comment]
@rajbarik, @atrick I took a swing at adjusting the `BucketSort` benchmark along the comments in #24206. Please review.

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
@swift-ci please smoke test

**Comment by palimondo** [comment]
Note: the reported performance change is caused by the removal of `legacyFactor`.

**Review by atrick — APPROVED** [review]
Thanks.

**Comment by atrick** [comment]
Merging now since this changes `legacyFactor` to have a stable baseline before @rajbarik enables Existential Specialization.

**Pull request merged**
