### PR TITLE
DebugInfo: Bypass resilience to calculate if a global is indirect or not

### PR DESCRIPTION
**Pull request by slavapestov**
Progress on <rdar://problem/39722386>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@adrian-prantl @dcci With this patch, both small and large resilient globals now work with `frame var`, addressing the FIXME from Adrian's earlier PR that added the `DW_OP_deref`:

```
// does not fit in the inline buffer -- worked before
let mySillyGlobalVariable = Notification(name: Notification.Name("abc"), object: "hello world", userInfo: ["hello":"world"])

// fits in the inline buffer -- used to fail because it would dereference unnecessarily
let myOtherSillyVariable = URL(string: "http://www.apple.com")
```

However, in the REPL, large globals still don't inspect properly. Is there something else I need to look at?

**Comment by adrian-prantl** [comment]
It's unclear to me how globals variables are modeled in the REPL. If they are actual globals then one would think they should behave the same.
```
  1> :log enable lldb expr
  1> let i = 24
...
// i
sil_global [let] @_T013__lldb_expr_11iSivp : $Int
```

Looks like they are. Does the log output tell us anything useful?

**Comment by slavapestov** [comment]
They are actual global, the question is do they have different debug info

**Comment by slavapestov** [comment]
@adrian-prantl Do we emit/look at debug info for globals in the REPL? I added some asserts in the code that parses DW_OP_deref and they don't fire.

**Comment by slavapestov** [comment]
I'm going to check this in since it addresses the FIXME for statically-compiled globals. But I suspect REPL might need an lldb-side fix, so I'll leave the radar open.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by adrian-prantl** [comment]
This is just speculation since I'm not really familiar with this part, but from looking at SwiftREPLMaterializer it's possible that they are handled as persistent variables (similar to how $R0 is handled in the debugger):

https://github.com/apple/swift-lldb/blob/cf4011b558df3bc202f850612679654adff83e04/source/Plugins/ExpressionParser/Swift/SwiftREPLMaterializer.cpp#L312

**Pull request merged**
