### PR TITLE
[ClangImporter] import compound macros independent of order

### PR DESCRIPTION
**Pull request by IngmarStein**
This patch fixes an importer problem which occurred for macros defined in terms of two other macros which might not have been imported before. For example, the macro `CPU_TYPE_X86_64` (defined as `CPU_TYPE_X86 | CPU_ARCH_ABI64`) in Foundation wasn't imported although the importing logic was implemented.

`importMacro()` is now called for each of the constituents before checking the constant value.

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

A smoke test on macOS does the following:
1. Builds the compiler incrementally.
2. Builds the standard library only for macOS. Simulator standard libraries and
   device standard libraries are not built.
3. lldb is not built.
4. The test and validation-test targets are run only for macOS. The optimized
   version of these tests are not run.

A smoke test on Linux does the following:
1. Builds the compiler incrementally.
2. Builds the standard library incrementally.
3. lldb is built incrementally.
4. The swift test and validation-test targets are run. The optimized version of these
   tests are not run.
5. lldb is tested.

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please clean test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please clean test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |
| Linux platform | @swift-ci Please clean test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by DougGregor** [comment]
Changes to SourceKit's interface generation tests are really hard to vet. Are you able to extend a simpler test in test/IDE or test/ClangModules to exercise this functionality?

**Comment by IngmarStein** [comment]
Those tests are already in `test/IDE` (print_clang_framework), I've just updated `Foo.h` in `test/SourceKit` to match. The series of `FOO_MACRO_X` is now identical in both test suites.

**Comment by IngmarStein** [comment]
To elaborate a bit on the last comment: the tests which were already in `test/IDE` didn't catch the error. I've only reproduced the issue in an interactive session:
```
$ swift
Welcome to Apple Swift version 3.0 (swiftlang-800.0.43.6 clang-800.0.38). Type :help for assistance.
  1> import Foundation
  2> CPU_TYPE_X86
$R0: cpu_type_t = 7
  3> CPU_ARCH_ABI64
$R1: Int32 = 16777216
  4> CPU_TYPE_X86_64
$R2: cpu_type_t = 16777223
  5> ^D
$ swift
Welcome to Apple Swift version 3.0 (swiftlang-800.0.43.6 clang-800.0.38). Type :help for assistance.
  1> import Foundation
  2> CPU_TYPE_X86_64
error: repl.swift:2:1: error: use of unresolved identifier 'CPU_TYPE_X86_64'
CPU_TYPE_X86_64
^~~~~~~~~~~~~~~
```

**Comment by IngmarStein** [comment]
Should I also create another PR based on swift-3.0-branch?

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by IngmarStein** [comment]
Rebased on current HEAD to resolve merge conflicts.

**Comment by IngmarStein** [comment]
Another round of testing?

**Comment by IngmarStein** [comment]
I guess you're busy wrapping up Swift 3.0. I just wanted to point out that this is a bugfix and doesn't add any new features.

**Comment by IngmarStein** [comment]
Could this be something for Swift 3.1?

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Pull request merged**
