### PR TITLE
Turn off library evolution for stdlib by default, keep it on only for Darwin

### PR DESCRIPTION
**Pull request by kubamracek**
Based on the discussion in <https://github.com/apple/swift/pull/33443>. This PR restricts the usage of -enable-library-evolution for the standard library only to Darwin platforms.

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by slavapestov — COMMENTED** [review]
My main concern is that we might hit more bugs that are Linux-only, because this is going to change the build configuration. Also, there might be SILGen and IRGen tests that use stdlib types which need to be tweaked to handle differences in calling conventions.

**Comment by kubamracek** [comment]
I'll be happy to fix tests as needed (I'm using the PR to discover what tests will break).

But your first part is more important: Are you suggesting we should keep using -enable-library-validation for stdlib on Linux? 

Note that I'm mostly just a messenger here; I definitely do see your point about causing more divergence between the platforms, and potentially hitting bugs that only exist on one of them. To me, it seems like that a no-LV stdlib should be a supported (and tested) configuration, though — with my motivation being the "mininal" size-optimized stdlib I'm trying to bring up (see https://github.com/apple/swift/pull/33286).

**Comment by gottesmm** [comment]
@slavapestov we don't have a stable ABI on Linux... why would we compile the stdlib with resilience?

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Comment by jckarter** [comment]
I think working through any issues this exposes would be worth it in principle, since it'd be great not to pay the library evolution penalty on platforms where it doesn't buy anything. If it ends up being too much of a quagmire for what @kubamracek is currently working on, we don't have to do it right away though, and maybe we should go back to selectively disabling it for new configurations first.

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Comment by kubamracek** [comment]
I've marked all failing tests as UNSUPPORTED, but that's just an experiment to see if that's really all the fallout from turning off resilience. I don't actually intend to land this PR as it is now.

**Comment by kubamracek** [comment]
@swift-ci please test

**Pull request closed without merging**
