### PR TITLE
[SILGen] Consolidate emission of SILDeclRef definitions

### PR DESCRIPTION
**Pull request by hamishknight**
Fill in the missing `SILDeclRef` cases in `emitDelayedFunction`, and rename it to `emitFunctionDefinition`. This will allow SIL to be emitted only for a specific set of symbols.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Review by slavapestov — APPROVED** [review]
Wow, thank you! This is exactly what I had in mind when I refactored emitDelayedFunction() into its current form, but I didn't quite see it through to completion.

**Pull request merged**
