### PR TITLE
Replace strcpy -> strlcpy in swift_getTupleTypeMetadata

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Review by mikeash — COMMENTED** [review]
Is this call available on Windows? /cc @compnerd

**Comment by kubamracek** [comment]
Turns out we have a nice available-everywhere `_swift_strlcpy` already...

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by compnerd — APPROVED** [review]

**Comment by compnerd** [comment]
> Is this call available on Windows? /cc @compnerd

No, `strlcpy` isn't available, but we did implement a copy in the runtime.  It is a non-portable function as it isn't standardized IIRC.

**Pull request merged**
