### PR TITLE
[Concurrency] Fix disallowed override isolation to carry `@preconcurr…

### PR DESCRIPTION
**Pull request by xedin**
…ency` bit

If ObjC member cannot be overridden due to isolation mismatch set `@preconcurrency` bit to make the diagnostic a warning instead of an error in Swift 5 mode.

Resolves: rdar://130776220

### CODE REVIEW

**Review by hborla — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@slavapestov This PR reverts https://github.com/swiftlang/swift/commit/0097ef68a669ff43135e83f8e34a865b8ec93011 because diagnostics reply on flags set on "unspecified" isolation at the moment, to downgrade diagnostics in Swift 5 mode.

**Comment by xedin** [comment]
@swift-ci please test

**Pull request merged**
