### PR TITLE
[5.6] Disable _move, _copy, _noImplicitCopy on 5.6 since we don't need it.

### PR DESCRIPTION
**Pull request by gottesmm**
Reverting the defer commit to reduce churn and just disabling these features in the short term on 5.6. They are still on main, we are just trying to reduce churn in the code base.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Review by tbkka — APPROVED** [review]
Thank you.

**Comment by gottesmm** [comment]
Docc failed on macOS. Not this commit.

**Comment by gottesmm** [comment]
Failed b/c of something else:

```
20:27:19 #import "SIL/SILBridging.h"
20:27:19         ^
20:27:19 
/Users/buildnode/jenkins/workspace/swift-PR-macos/branch-release/5.6/swift/include/swift/SIL/SILBridging.h:18:10: error: 'string' file not found
20:27:19 #include <string>
20:27:19          ^
20:27:19 
/Users/buildnode/jenkins/workspace/swift-PR-macos/branch-release/5.6/swift/libswift/Sources/SIL/Argument.swift:13:8: error: could not build Objective-C module 'SILBridging'
20:27:19 import SILBridging
20:27:19     
```

**Comment by gottesmm** [comment]
@swift-ci test macOS platform

**Pull request merged**
