### PR TITLE
[docs] Fix typo in DebuggingTheCompiler.md

### PR DESCRIPTION
**Pull request by eltociear**
specfied -> specified

### CODE REVIEW

**Comment by LucianoPAlmeida** [comment]
Makes sense!
@swift-ci Please smoke test

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test Linux Platform

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test Windows Platform

**Comment by gottesmm** [comment]
LGTM

**Pull request merged**
