### PR TITLE
Backport swift 3.0 code coverage fixes to swift 2.3

### PR DESCRIPTION
**Pull request by vedantk**
#### What's in this pull request?

This PR backports several swift 3.0 code coverage fixes to swift 2.3.
#### Resolved bug number: ([SR-1850](https://bugs.swift.org/browse/SR-1850))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by vedantk** [comment]
@swift-ci Please test

**Comment by tkremenek** [comment]
@swift-ci smoke test OS X platform

**Comment by vedantk** [comment]
I forwarded compiler-rt/swift-3.0-branch to compiler-rt/swift-2.3-branch.

**Comment by vedantk** [comment]
@swift-ci smoke test OS X platform

**Comment by vedantk** [comment]
The build preset the bot wants to use doesn't exist in 2.3. I've backported a few changes to swift/utils/build-presets.ini and am testing them locally. I'll update the PR once that's done.

**Comment by vedantk** [comment]
@swift-ci smoke test OS X platform

**Comment by vedantk** [comment]
@tkremenek Is this good to merge, or does the code coverage backporting effort need more discussion?

**Comment by tkremenek** [comment]
@vedantk sorry, I was (am) on vacation.  I'll merge now.

**Comment by vedantk** [comment]
Thanks for taking a look at this while you were away :).

**Pull request merged**
