### PR TITLE
Add a section to SIL.rst describing the SIL Ownership Model.

### PR DESCRIPTION
**Pull request by gottesmm**
rdar://34145830

### CODE REVIEW

**Comment by gottesmm** [comment]
@rjmccall @atrick @jckarter What do you guys think?

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
I am going to add a separate document later that goes into far more depth, but I would like to get this in.

**Comment by atrick** [comment]
This all looks great. There's just one paragraph that's deeply misleading:

> A value with ``@guaranteed`` ownership is a scoped-lifetime, immutable value
> that is derived from an ``@owned`` value. The ``@guaranteed`` value's lifetime
> acts as a constraint on the lifetime of the ``@owned`` value and statically
> prevent the ``@owned`` value from being destroyed until the ``@guaranteed``
> value's lifetime has ended.

`end_borrow` guarantees that the value's lifetime does not need to extend beyond that point, absent other direct uses of the owned value. I'm sure we don't want to introduce additional SIL semantics that don't serve a purpose and can't be enforced. We do want to be able to remove begin/end_borrow without affecting semantics.

I think the confusion came about because `load_borrow/end_borrow` was originally proposed to implement shared-borrowed variables at the language level allowing the borrowed value to be represented in SSA. But we now have `end_access` to enforce the borrowed scope.

**Pull request closed without merging**
