### PR TITLE
Allow AddressUseDefWalker to continue past MarkUninitializedInst

### PR DESCRIPTION
**Pull request by atrick**
Also adds test infrastructure to match the C++ tests so we can guarantee consistency across code bases.

### CODE REVIEW

**Review by eeckstein — APPROVED** [review]
lgtm

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci smoke test

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci test source compatibility

**Pull request merged**
