### PR TITLE
test: fix for Windows

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test and merge

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Review by varungandhi-apple — APPROVED** [review]

**Review by beccadax — APPROVED** [review]
LGTM. Sorry about this—I think I asked swift-ci for Windows PR tests a couple times and never got them.

**Comment by compnerd** [comment]
@brentdax - that sounds like something that @shahmishal should look into (could you please file a radar?) - you should be able to trigger those

**Comment by compnerd** [comment]
@swift-ci please smoke test Linux platform

**Comment by compnerd** [comment]
The Windows failure is going to be addressed by #29967, merging to improve the state

**Pull request merged**
