### PR TITLE
SILGen: Fix emitBuiltinCreateAsyncTaskFuture

### PR DESCRIPTION
**Pull request by aschwaighofer**
We need to re-abstract the function argument.

I think this should fix rdar://74957357.

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Review by DougGregor — APPROVED** [review]
Nice catch, thank you!

**Comment by DougGregor** [comment]
The libtool issues caused the macOS failures:

```swift
09:29:26 Failed Tests (2):
09:29:26   lldb-api :: lang/swift/clangimporter/static_archive/TestSwiftStaticArchiveTwoSwiftmodules.py
09:29:26   lldb-api :: lang/swift/parseable_interfaces/static/TestSwiftInterfaceStaticNoDebugInfo.py
```

**Comment by DougGregor** [comment]
@swift-ci please smoke test macOS

**Pull request merged**
