### PR TITLE
[gyb] added feature to gyb.py to search for an process a new template…

### PR DESCRIPTION
**Pull request by flyin1600**
… tag, when encountered in AST it is processed in line

Added new tag <{TEMPLATE_FILE_NAME} for processing embedded templates in gyb templates.  Created a new class to represent a template, and when they are encountered in the AST they are processed in place in a new ParseContext

### CODE REVIEW

**Comment by hughbe** [comment]
@swift-ci please python lint

**Comment by flyin1600** [comment]
linted

**Comment by CodaFi** [comment]
@swift-ci please python lint.

**Comment by CodaFi** [comment]
@swift-ci please python lint

**Comment by flyin1600** [comment]
I did go back and python lint it, and it looks like it's passing lint now, but it's been waiting status on the Linux and OS X platform tests since Friday, and ideas why?

**Comment by hughbe** [comment]
There's a bunch of bugs with the GitHub triggers :(

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by flyin1600** [comment]
I tried to build and run tests locally but my MacBook Pro kernel panics every time, I can redo it and say exactly which library if needed.  Is that a known issue?

is there a way to run the smoke test without building all of swift?

**Comment by flyin1600** [comment]
I see your edit, I'll take a look, thanks!

**Comment by flyin1600** [comment]
so CI is running and it appears to be failing at the same point it fails to build on my local machine.  Every time I reach this point in the build, it hangs and I have 5 python threads spinning at 100% cpu

[727/1180] cd /Users/andrewlipiecki/build/Ninja-RelWithDebInfoAssert/swift-macosx-x86_64/stdlib/public/SwiftRemoteMirror && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo -create -output /Users/andrewlipiecki/build/Ninja-RelWithDebInfoAssert/swift-macosx-x86_64/./lib/swift/macosx/libswiftRemoteMirror.dylib /Users/andrewlipiecki/build/Ninja-RelWithDebInfoAssert/swift-macosx-x86_64/lib/swift/macosx/x86_64/libswiftRemoteMirror.dylib && codesign -f -s - /Users/andrewlipiecki/build/Ninja-RelWithDebInfoAssert/swift-macosx-x86_64/./lib/swift/macosx/libswiftRemoteMirror.dylib

This is running lipo and code signing...so I don't see how it could have anything to do with my change to gyb.  I'm going to file a GitHub issue for this.

**Comment by flyin1600** [comment]
I apparently don't have permission to create an issue, as I don't see the Issues tab in the swift repo

**Comment by gottesmm** [comment]
@flyin1600 We use a separate bug tracker. bugs.swift.org

**Comment by flyin1600** [comment]
thank you, I'll file something over there

**Comment by flyin1600** [comment]
@swift-ci please smoke test

**Pull request closed without merging**
