### PR TITLE
SILGen: Hop to the executor for actor-constrained methods in their @objc async thunks.

### PR DESCRIPTION
**Pull request by jckarter**
If a Swift async method is actor-constrained, then when it's projected into ObjC, it should still
run its task on the correct actor, along with the completion handler that ObjC passes into it.
Fixes rdar://76415650.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Review by DougGregor — APPROVED** [review]
LGTM, thanks!

**Comment by jckarter** [comment]
@swift-ci Please test Linux

**Comment by jckarter** [comment]
@swift-ci Please test Linux

**Comment by jckarter** [comment]
@swift-ci Please test OS X

**Comment by jckarter** [comment]
@swift-ci Please smoke test Linux

**Pull request merged**
