### PR TITLE
[TBDGen] Add back standalone OBJC_METACLASS symbols

### PR DESCRIPTION
**Pull request by cyndyishida**
It turns out there are valid usecases for exposing a standalone objc-metaclass symbols and tbd files must encode it correctly.
resolves: rdar://118499886

### CODE REVIEW

**Comment by cyndyishida** [comment]
@mikeash pointed out that emitting METACLASS symbol may not be necessary at all but I'm a little more worried about the possible fallout there.

**Review by mikeash — APPROVED** [review]

**Comment by cyndyishida** [comment]
@swift-ci please smoke test

**Review by tshortli — APPROVED** [review]

**Review by cooperp — APPROVED** [review]

**Comment by cyndyishida** [comment]
@swift-ci please smoke test

**Review by aschwaighofer — APPROVED** [review]
Makes sense to me.

Thank you!

**Comment by cyndyishida** [comment]
I suspect my expectation that these exported `OBJC_METACLASS` class symbols wouldn't be static-link time referenced was wrong. 

The (failing test)[https://github.com/apple/swift/blob/main/test/Interpreter/SDK/objc_getClass.swift] has code across binary boundaries like 
```
// libresilient_objc_class
open class ResilientGenericNSObjectOutsideParent<A>: NSObject { ... }
open class ResilientConcreteNSObjectOutsideChild : ResilientGenericNSObjectOutsideParent<String> { ... }

// main
class ResilientSubclassOfConcreteNSObject : ResilientConcreteNSObjectOutsideChild { ... } 
```
results in IR like 
```
@"OBJC_METACLASS_$_main.ResilientSubclassOfConcreteNSObject" = hidden global %objc_class { ptr @"OBJC_METACLASS_$_NSObject", ptr @"OBJC_METACLASS_$_resilient_objc_class.ResilientConcreteNSObjectOutsideChild", ptr @_objc_empty_cache, ptr null, i64 ptrtoint (ptr @_METACLASS_DATA_main.ResilientSubclassOfConcreteNSObject to i64) }, align 8
```
This subclassing dependency mostly makes sense to me. @mikeash @aschwaighofer Is this behavior expected? If so I can pursue less invasive options being 
1. separate out OBJC_CLASS vs OBJC_METACLASS in TBD generation. I would need to sort out how to ensure this won't trip up installAPI verification for obj-c or mixed frameworks. 
2. Have IR also emit a matching OBJC_CLASS symbol.

**Comment by mikeash** [comment]
Oh dear, I was thinking the metaclass wouldn't be referenced since it can't be subclassed from ObjC, but of course you can subclass it from Swift, and Swift still has a metaclass which wants to reference the superclass metaclass.

**Comment by cyndyishida** [comment]
@swift-ci please smoke test

**Comment by cyndyishida** [comment]
The new patch adds back exported `OBJC_METACLASS_$_*` to TBDGen, instead of messing with IRGen.
This does rely on tapi expecting such input and handling this correctly for installapi verification(rdar://121262040)

**Review by cooperp — APPROVED** [review]
LGTM

**Pull request merged**
