### PR TITLE
Refactor `_swift_withWin32DbgHelpLibrary()` to avoid using `GetCurrentProcess()` per Microsoft documentation

### LINKED ISSUE #62290: _swift_withWin32DbgHelpLibrary() should not use GetCurrentProcess()
**Description**

The Microsoft [documentation](https://learn.microsoft.com/en-us/windows/win32/api/dbghelp/nf-dbghelp-syminitialize) for the DbgHelp library warns developers not to pass `GetCurrentProcess()` as the handle to `SymInitialize()` etc. We should use some other handle, e.g. one returned from `GlobalAlloc()`.

I'll modify `_swift_withWin32DbgHelpLibrary()` to use a unique handle and pass it to its callback.

**Steps to reproduce**
N/A

**Expected behavior**
N/A

**Environment**
N/A

### PR DESCRIPTION
**Pull request by grynspan**
The Microsoft [documentation](https://learn.microsoft.com/en-us/windows/win32/api/dbghelp/nf-dbghelp-syminitialize) for the DbgHelp library warns developers not to pass `GetCurrentProcess()` as the handle to `SymInitialize()` etc.

This change uses a privately-held handle duplicated from `GetCurrentProcess()`. It also takes care to set DbgHelp library options consistently in case something elsewhere calls `SymSetOptions()` and sets them to something incompatible with the runtime's expectations.

We still have no way to thread-safely use the library in coordination with code outside the runtime, but at least the runtime should avoid stomping on shared system resources.

Resolves #62290.

### CODE REVIEW

**Comment by grynspan** [comment]
@swift-ci please smoke test

**Comment by grynspan** [comment]
@swift-ci please smoke test

**Comment by grynspan** [comment]
@swift-ci please smoke test

**Comment by grynspan** [comment]
@swift-ci please smoke test

**Comment by grynspan** [comment]
@swift-ci please smoke test

**Comment by grynspan** [comment]
@swift-ci please test windows

**Review by compnerd — APPROVED** [review]
I don't think I ever noticed the fine print there.  This is terrifying, this is terrible, and we should feel bad.  Thanks for this fix, sorry for any scars that it may have inflicted upon you.

**Comment by al45tair** [comment]
I particularly enjoy this part (emphasis mine):
> `[in] hProcess]
> 
> A handle that identifies the caller. This value should be unique and nonzero, _but need not be a process handle_.
So, they called it `hProcess` and gave it the type `HANDLE`, but it can actually be any unique value.

Maybe we'd be better off just casting the address of something to `HANDLE` and passing that, since that will be unique and means we don't need to worry about `DuplicateHandle()` failing.

**Comment by grynspan** [comment]
That comment _lies_. If you pass some other address with `fInvadeProcess = true` then `SymInitialize()` succeeds but symbolication with `SymFromAddr()` fails with error `ERROR_MOD_NOT_FOUND`.

I suspect `UnDecorateSymbolName()` would work in that scenario since it doesn't take a handle argument, but I haven't tested it specifically.

**Comment by al45tair** [comment]
> That comment _lies_. If you pass some other address with `fInvadeProcess = true` then `SymInitialize()` succeeds but symbolication with `SymFromAddr()` fails with error `ERROR_MOD_NOT_FOUND`.

Joy :joy:

**Comment by grynspan** [comment]
@swift-ci please smoke test

**Comment by grynspan** [comment]
@swift-ci please smoke test

**Pull request merged**
