### PR TITLE
[NFC] llvm-all-the-optionals!

### PR DESCRIPTION
**Pull request by etcwilde**
This is phase-1 of switching from `llvm::Optional` to `std::optional` in the next rebranch. llvm::Optional was removed from upstream LLVM, so we need to migrate off rather soon. On Darwin, std::optional, and llvm::Optional have the same layout, so we don't need to be as concerned about ABI beyond the name mangling. `llvm::Optional` is only returned from one function in
```
getStandardTypeSubst(StringRef TypeName,
                     bool allowConcurrencyManglings);
```
It's the return value, so it should not impact the mangling of the function, and the layout is the same as `std::optional`, so it should be mostly okay. This function doesn't appear to have users, and the ABI was already broken 2 years ago for concurrency and no one seemed to notice so this should be "okay".

I'm doing the migration incrementally so that folks working on main can cherry-pick back to the release/5.9 branch. Once 5.9 is done and locked away, then we can go through and finish the replacement. Since `None` and `Optional` show up in contexts where they are not `llvm::None` and `llvm::Optional`, I'm preparing the work now by going through and removing the namespace unwrapping and making the `llvm` namespace explicit. This should make it fairly mechanical to go through and replace llvm::Optional with std::optional, and llvm::None with std::nullopt. It's also a change that can be brought onto the release/5.9 with minimal impact. This should be an NFC change.

### CODE REVIEW

**Comment by etcwilde** [comment]
@swift-ci please test

**Review by MaxDesiatov — APPROVED** [review]

**Review by QuietMisdreavus — APPROVED** [review]
SymbolGraphGen looks good. (I also took a look at Markup, and that looks good too.)

**Comment by etcwilde** [comment]
@swift-ci please test

**Review by xedin — APPROVED** [review]
Sema changes look good to me!

**Review by ahoppen — APPROVED** [review]
The following directories look good to me

include/swift/IDE
include/swift/Parse
include/swift/Refactoring
lib/IDE
lib/IDETool
lib/Index
lib/Parse
tools/SourceKit
tools/swift-ide-test

**Review by ktoso — APPROVED** [review]
I looked at concurrency and distributed files, LGTM

**Comment by etcwilde** [comment]
@swift-ci please smoke test

**Comment by etcwilde** [comment]
@swift-ci please smoke test

**Comment by etcwilde** [comment]
@swift-ci please smoke test

**Comment by gottesmm** [comment]
@etcwilde asked me to force merge this to prevent some merge conflict train wrecks.

**Pull request merged**
