### PR TITLE
[SyntaxParse] Prevent memory leak in Syntax parsing

### PR DESCRIPTION
**Pull request by rintaro**
`ParsedRawSyntaxNode` holds opaque pointer `void *` pointer for "recorded" node. The parser doesn't know how the memory is managed. When any `ParsedRawSyntaxNode` holding "recorded" node is discarded, that leaks because the parser doesn't know how to release it.

In this patch, to prevent that kind of leaking, make `ParsedRawSyntaxNode` move-only, nullify the original node when moved, assert the it does not hold recorded node in the destructor.

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please Sourcekit Stress test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test macOS

**Comment by compnerd** [comment]
@rintaro this may have broken the Windows builds:

```
C:\agent\_work\1\s\swift\lib\Parse\ParseType.cpp(411): error C2280: 'swift::ParsedTypeSyntax::ParsedTypeSyntax(swift::ParsedTypeSyntax &)': attempting to reference a deleted function
C:/agent/_work/1/s/swift/include/swift/Parse/ParsedSyntaxNodes.h.gyb(82): note: compiler has generated 'swift::ParsedTypeSyntax::ParsedTypeSyntax' here
C:/agent/_work/1/s/swift/include/swift/Parse/ParsedSyntaxNodes.h.gyb(82): note: 'swift::ParsedTypeSyntax::ParsedTypeSyntax(swift::ParsedTypeSyntax &)': function was implicitly deleted because a base class invokes a deleted or inaccessible function 'swift::ParsedSyntax::ParsedSyntax(swift::ParsedSyntax &)'
C:\agent\_work\1\s\swift\include\swift/Parse/ParsedSyntax.h(68): note: 'swift::ParsedSyntax::ParsedSyntax(swift::ParsedSyntax &)': function was implicitly deleted because a data member invokes a deleted or inaccessible function 'swift::ParsedRawSyntaxNode::ParsedRawSyntaxNode(swift::ParsedRawSyntaxNode &)'
C:\agent\_work\1\s\swift\include\swift/Parse/ParsedRawSyntaxNode.h(100): note: 'swift::ParsedRawSyntaxNode::ParsedRawSyntaxNode(swift::ParsedRawSyntaxNode &)': function was explicitly deleted
```

https://dev.azure.com/compnerd/windows-swift/_build/results?buildId=8674&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=2915bb0c-b896-5031-2bc6-f61128a41015&l=947

**Pull request merged**
