### PR TITLE
[sourcekit] Fix non-deterministic failure in CompileNotifications tests

### PR DESCRIPTION
**Pull request by benlangmuir**
Our notifications are dispatched in the XPC event handler, which is not
synchronized with replies to explicit XPC send_message_with_reply calls.
This is fine for most users of sourcekitd, since the notifications are
already enqueued on the client side, but for testing we need a way to
guarantee that all notifications are passed to the client-side handler
before we exit. This commit introduces a new request for testing that
triggers a notification, allowing the client to wait on that
notification to ensure all previously posted notifications have been
handled.

Note: the non-deterministic test failures can be triggered by adding a
sleep of ~100 ms in the event handler before the notification is
dispatched to the main queue.

Incidentally fix a race in the in-process sourcekit's notification handling
that became more obvious after this change.

rdar://40311995

### CODE REVIEW

**Comment by benlangmuir** [comment]
@swift-ci please smoke test

**Comment by slavapestov** [comment]
Nitpick: typo in commit message ("deterinistic")

**Comment by benlangmuir** [comment]
@swift-ci please smoke test linux

**Comment by benlangmuir** [comment]
The linux failures seem to indicate we're loosing this notification in some cases.  It may be related to linux using the in-process sourcekitd.  Investigating...

**Comment by benlangmuir** [comment]
Sure enough, there was a race in the in-process library (thanks TSan!).

**Comment by benlangmuir** [comment]
@swift-ci please smoke test

**Pull request merged**
