### PR TITLE
Runtime: Fix problems with nil-to-nil casts [master]

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by gribozavr** [comment]
> We have a special rule that Optional.none successfully dynamically casts to Optional.none for any T and U.

Not for 2.2, but this rule seems to be a special case and inconsistent with the static type system.  Usually, as far as I understand, we try to make dynamic casts resemble the static type system.  Do you know why we have this behavior?  Should we consider removing this behavior?

**Comment by slavapestov** [comment]
Regarding that special case, it surprised me too. @jckarter and @atrick might remember the intent here.

**Comment by atrick** [comment]
@gribozavr @jckarter
I do *not* think the runtime should accept nil-to-nil casts unless non-nil values of the same payload type could be converted. This case was likely my misunderstanding combined with implementation laziness. When adding cases to Runtime casting, my overriding intent was to mimic SIL behavior, toward the goal of making specialization completely transparent. I don't think the current runtime behavior meets that standard yet because specialized SIL will reduce Optional<A> is Optional<B> to false if A is unrelated to B.

That said, off the top of my head I don't know how to implement a fix for this case because I'm not sure how to dynamically obtain the opened existential type for a nil payload. @slavapestov, can you follow up on this?

**Comment by atrick** [comment]
`Optional<A> is Optional<A> to false if A is unrelated to B`

**Comment by atrick** [comment]
You get the idea :)

**Comment by atrick** [comment]
After looking at the code, I don't think it would be too hard to handle this case:

`Optional<Existential> is Optional<Class>`

_conformsToProtocol already handles nil values by answering whether a conformance is possible in the abstract.

**Comment by jrose-apple** [comment]
I was talking to @jckarter about this, and the problem seems to be there's really no way to know. If you go from `Optional<UIView>` to `Optional<AnyObject>` and then back down to `Optional<UIDocument>`, casting a value would fail, but casting `nil` really can't. Similarly, going from *any* (non-final) class type or existential to another existential can't reliably fail, because there could be a subclass or other implementer that does conform.

If we can only detect *some* cases, is it better to fail for those cases and succeed on others, or succeed everywhere?

Is this controversial enough to go to swift-evolution? :-/

**Comment by jckarter** [comment]
If `T` is a subtype of `U`, and `S` is a supertype of both `T` and `U`, then `(x as S) as? U` ought to succeed, since `x as U` is possible. We'd lose that if we didn't successfully cast a `T?` containing nil to another optional type. For instance, if you have a `nil` of type `UIView?`, that can implicitly convert to `NSObject?` or `AnyObject?` as a subtype. If you conditionally cast the `AnyObject?` back down to `NSObject?`, that should succeed.

**Comment by atrick** [comment]
I think the `struct/class <-> existential` case is noncontroversial and needs to be fixed.

The `existential <-> existential` case is interesting, but AFAIC we just always allow it. I only care that the runtime is consistent with SIL and I don't think there's any logic in SIL to reduce/infer this. If we do add some inference in SIL, we should (from now on) make sure the runtime has the same logic.

**Comment by jckarter** [comment]
The existential to existential case should follow the rules of whatever's dynamically inside the source existential, since `(x as Existential) as? T` should be equivalent to `x as? T`.

**Comment by atrick** [comment]
Yes to @jckarter. I was specifically referring to the `Optional<ExistentialA>.none to Optional<ExistentialB>.none` case. We correctly always allow it, even though there may be no type that conforms to both ExistentialA and ExistentialB. That is what motivated my adding the .none to .none case in the runtime.

The problem with the current implementation is that some cases are optimized at the SIL level such that specialized an unspecialized code exhibit opposite behavior. The nonexistential casts are obviously a problem. It's uncommon when one side of the cast is an existential, but here is one such example:

```
func anyToAnyIs<T, U>(a: T, _ : U.Type) -> Bool {
  return a is U
}

protocol PP: class {}
struct CC {}

public func foo() -> Bool {
  return anyToAnyIs(nil as PP?, Optional<CC>.self)
}

print(foo())
```

I filed https://bugs.swift.org/browse/SR-1113

**Pull request closed without merging**
