### PR TITLE
Fix critical edges

### PR DESCRIPTION
**Pull request by atrick**
Handle critical edges consistently in all SIL stages.
    
This will allow passes that optimize phis to be run in the mandatory
pipeline. It also simplifies SIL invariants and will unblock
much needed simplification of BlockArgument handling.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
@swift-ci test source compatibility.

**Comment by atrick** [comment]
@swift-ci smoke test linux.

**Comment by atrick** [comment]
@swift-ci smoke test linux.

**Comment by gottesmm** [comment]
@atrick So this bans non cond br critical edges in raw sil?

**Comment by atrick** [comment]
@gottesmm Yes, this gives raw and canonical SIL the same invariants, so that all our passes and utilities are just correct by definition. It's also one important piece in simplifying the SILBlockArgument APIs in general.

This PR originally fixed SILGen to emit the default switch block, but that's irrelevant after @rjmccall 's commit yesterday that defined away the problem.

**Pull request merged**
