### PR TITLE
[docs] Update SIL.rst

### PR DESCRIPTION
**Pull request by benrimmington**
Follow-up to: https://github.com/apple/swift/pull/35993#issuecomment-785080679

View file: [docs/SIL.rst#is-unique](https://github.com/apple/swift/blob/f21cd2d551f6317e67bd3f4c5a7b3b361ad05b3d/docs/SIL.rst#is-unique)

### CODE REVIEW

**Comment by benrimmington** [comment]
@swift-ci Please test

**Comment by MaxDesiatov** [comment]
Thanks for resolving this1

**Comment by Teemperor** [comment]
Thanks

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Comment by benrimmington** [comment]
The swift-ci test (or smoke test) doesn't appear to build the HTML documentation.

```
CMake Warning at docs/CMakeLists.txt:24 (message):
  Unable to find sphinx-build program.  Not building docs
```

But I don't know if swift-ci toolchains or nightly snapshots will be broken?

Can the [`-W`][] option be removed from [docs/CMakeLists.txt][], so that `sphinx-build` warnings don't break the entire build?

[`-W`]: <https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-W>
[docs/CMakeLists.txt]: <https://github.com/apple/swift/blob/main/docs/CMakeLists.txt>

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test Linux platform

**Review by MaxDesiatov — APPROVED** [review]

**Comment by varungandhi-apple** [comment]
> Can the -W option be removed from docs/CMakeLists.txt, so that sphinx-build warnings don't break the entire build?

I think this should be okay. We don't have warnings as errors turned on for CI either. That said, I don't remember how long building the docs takes and whether it is happening serially or in parallel, so I'm not sure if we should be building the docs in CI by default... (is that what you're suggesting?)

**Comment by benrimmington** [comment]
> I'm not sure if we should be building the docs in CI by default... (is that what you're suggesting?)

No, I'm only suggesting that a broken link in documentation isn't serious enough to justify a complete build failure.

Since the docs_html phase isn't tested by swift-ci, we won't notice the failure until someone reports it.

**Comment by varungandhi-apple** [comment]
Okay, yeah that sounds reasonable. FWIW, I'm okay with removing the `-W`.

**Pull request merged**
