### PR TITLE
[build-presets] No need to disable static stdlib (NFC)

### PR DESCRIPTION
**Pull request by modocache**
#### What's in this pull request?

Static stdlib builds are disabled unless `--build-swift-static-stdlib` is explicitly passed in to the build scripts. As a result, `--build-swift-static-stdlib=0` is pointless--unless it's being used to counteract another `--build-swift-static-stdlib` being passed to the build script, but this is not the case in any of the uses in the build presets.

Remove the unnecessary parameters to make the build presets easier to understand.

This is a re-submission of https://github.com/apple/swift/pull/1747, which I accidentally pushed as a branch on the main apple/swift repository. This pull request correctly originates from my fork of Swift.
#### Resolved bug number: None

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci Please test

**Comment by modocache** [comment]
It looks like the OS X CI has stalled out...?

**Comment by modocache** [comment]
@gottesmm Friendly ping! I think CI may have stalled. Could you try asking @swift-ci to please test again?

**Comment by gottesmm** [comment]
@swift-ci Please test

**Comment by modocache** [comment]
Tests are passing and this seems like an obvious win to me. Merging myself, comment here if anyone has any objections.

**Pull request merged**
