### PR TITLE
Fix a few stdlib coding convention violations

### PR DESCRIPTION
**Pull request by dabrahams**

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please smoke test and merge

**Comment by palimondo** [comment]
@dabrahams It looks like this commit contains manual edit to `benchmark/CMakeLists.txt` and `benchmark/utils/main.swift` that are not coupled with corresponding edits of `benchmark/CMakeLists.txt.gyb` and `benchmark/utils/main.swift.gyb`.

@gottesmm, how come the `validation-test/benchmarks/generate-harness.test-sh` we added in #8641 didn't catch this? OMG, where is it? I don't see it in master at all?!

**Comment by palimondo** [comment]
Judging from the title of this PR, I question if the addition of Substring.swift and corresponding mods to test harness were intended here...

**Comment by dabrahams** [comment]
They were intended, but they weren't supposed to be part of the same PR.

**Comment by dabrahams** [comment]
AFAICT there is no edit required in those gyb files.  I re-ran generate-test-harness.py, and IIUC it made the edits to main.swift and CMakeLists.txt by discovering the new tests in single-source/Substring.swift

**Comment by palimondo** [comment]
Haha, you are quite right! Mea culpa. I forgot that additions are auto-discovered during harness generation. Editing gybs is required only when we change the template itself.

Lesson learned: don't comment as a first thing in a morning when all you've got are 10 minutes and you need to run before you can verify the code. I'm sorry Dave!

**Comment by dabrahams** [comment]
@palimondo n/p.  The worst part was thinking I had messed up somehow.l

**Pull request merged**
