### PR TITLE
Serialization: Restrict swiftmodules to distribution channels

### PR DESCRIPTION
**Pull request by xymus**
There are scenarios where different compilers are distributed with compatible serialization format versions and the same tag. Distinguish swiftmodules in such a case by assigning them to different distribution channels. A compiler expecting a specific channel will only read swiftmodules from the same channel. The channels should be defined by downstream code as it is by definition vendor specific.

For compiler developers, using a compiler without a set channel or defining the env var `SWIFT_IGNORE_SWIFTMODULE_REVISION` skips this new check.

rdar://123731777

### CODE REVIEW

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by xymus** [comment]
Removed having the channel default to the vendor name as it's likely not a stable enough value for testing. The channel will need to be set in downstream code where it is useful.

@swift-ci Please smoke test

**Review by tshortli — APPROVED** [review]
Looks great, thanks!

**Comment by xymus** [comment]
@swift-ci Please smoke test macOS

**Comment by xymus** [comment]
@swift-ci Please smoke test Linux

**Pull request merged**
