### PR TITLE
[crashers] NFC: Limit time spent in solver for crashers 28684 and 28686

### PR DESCRIPTION
**Pull request by xedin**

### CODE REVIEW

**Comment by xedin** [comment]
@davezarzycki reported slow down in these two fixed crashers related to https://github.com/apple/swift/pull/15134

**Comment by xedin** [comment]
@swift-ci please smoke test and merge

**Comment by davezarzycki** [comment]
Out of curiosity, given that these files catastrophically fail parsing, why are we spending any time in the type checker?

**Comment by xedin** [comment]
@davezarzycki I think because by default compile is going to continue after errors to find all of the errors possible (as far as I understand it).

**Comment by davezarzycki** [comment]
Thanks @xedin. That makes sense, especially for reasonable and normally error-free code, unlike these two tests.

Should we perhaps create a test target for these freeze dried parse stress tests so that all of them are throttled if they get past parsing?

**Comment by xedin** [comment]
I think that would make sense, I just don't know how to do it :)

**Comment by davezarzycki** [comment]
Well, `-parse` instead of `-typecheck` would be a start :-)

**Pull request merged**
