### PR TITLE
Separate TypeDeclFinder from AccessScopeChecker

### PR DESCRIPTION
**Pull request by jrose-apple**
<del>...and collapse the latter into TypeCheckAccess.cpp, since it's not a reusable component anyway.</del>

...and move the latter into lib/Sema as TypeAccessScopeChecker, since it's not interesting outside of Sema anyway.

No functionality change.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
Whoops, TypeCheckProtocol *does* use this. Hm.

(I can't believe I forgot to recompile locally.)

**Comment by jrose-apple** [comment]
Take two.

@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test Linux

**Comment by jrose-apple** [comment]
Did someone fix a compiler crasher on Linux? Because this commit shouldn't have…

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test Linux

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test Linux

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test Linux

**Comment by jrose-apple** [comment]
@slavapestov Low-priority ping

**Review by slavapestov — APPROVED** [review]

**Comment by jrose-apple** [comment]
Just to be sure

@swift-ci Please smoke test

**Pull request merged**
