### PR TITLE
Sema: Diagnose inconsistent use of `@_weakLinked` import

### PR DESCRIPTION
**Pull request by tshortli**
Just like for `@_implementationOnly import`, we need to diagnose inconsistency in use of the `@_weakLinked` attribute.

```swift
@_weakLinked import Foo
// ...
import Foo // error: 'Foo' inconsistently imported with @_weakLinked
```

Resolves rdar://98465034

### CODE REVIEW

**Comment by tshortli** [comment]
@swift-ci please test

**Comment by tshortli** [comment]
@swift-ci please test

**Review by hamishknight — APPROVED** [review]

**Comment by tshortli** [comment]
@swift-ci please smoke test and merge

**Review by nkcsgexi — APPROVED** [review]
Thank you for adding this!

**Pull request merged**
