### PR TITLE
[NFC] Remove (swift) spelling from SWIFT_CC

### PR DESCRIPTION
**Pull request by Azoy**
cc: @mikeash @rjmccall

### CODE REVIEW

**Comment by compnerd** [comment]
@Azoy why replace the generic dispatch of the calling convention (which allows for alternate calling conventions) with explicit names?  At that point, why not just use the GNU spelling directly?

**Comment by Azoy** [comment]
@compnerd I understand the intent of the generic dispatch, however 99.99% of the use case was for the swift cc and the other single use case for preserve_most along with the C dispatch not being used at all (not needed because functions are just declared in extern "C"). I did this because of the repeated information in the signature `SWIFT_CC(swift)`. I am unaware of the GNU spelling.

**Comment by compnerd** [comment]
@Azoy `__attribute__((__swiftcall__))` and `__attribute__((__preserve_most__))` are the GNU spellings.

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
