### PR TITLE
Suppress NRVO in copy forwarding unless the copy is just a move.

### PR DESCRIPTION
**Pull request by atrick**
Fixes <rdar://problem/39059402> CopyForwarding + Guaranteed Bug

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
@gottesmm thanks for the test case. Feel free to merge this after your review.

**Comment by gottesmm** [comment]
This should fix the problem.

**Comment by gottesmm** [comment]
I do think that it may pessimize certain NRVO scenarios, but all the scenarios I can think of are ones where you would probably merge the take into the copy_addr.

**Review by gottesmm — COMMENTED** [review]
LGTM

**Pull request merged**
