### PR TITLE
[stdlib] Move DoubleWidth to test/Prototypes

### PR DESCRIPTION
**Pull request by moiseev**
It is with deep regret and profound sadness that I have to do this. Our beloved type `DoubleWIdth` that served as a witness of usefulness of the new integer protocols has to move from being a part of the standard library to a mere prototype.

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
Why is that?

**Comment by airspeedswift** [comment]
cos it generates binaries the size of a humpback whale...

**Comment by airspeedswift** [comment]
We need to set aside time to figure out why and fix that underlying problem. Meanwhile it can stay testing in Prototypes ready to move back once we do.

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by moiseev** [comment]
@swift-ci please test

**Pull request merged**
