### PR TITLE
[IRGen] Disable simple single payload enum in layout strings

### PR DESCRIPTION
**Pull request by drexin**
rdar://119792426

There are a few issues with wrong assumptions around extra inhabitants that cause tags to not be identified properly in some cases. Until a proper fix is identified, we emit tag functions instead.

### CODE REVIEW

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@swift-ci smoke test linux

**Review by aschwaighofer — APPROVED** [review]

**Comment by drexin** [comment]
@swift-ci smoke test

**Review by aschwaighofer — APPROVED** [review]

**Comment by drexin** [comment]
@swift-ci smoke test

**Pull request merged**
