### PR TITLE
Remove per-SourceFile "used conformances" lists

### PR DESCRIPTION
**Pull request by slavapestov**
Continuation of https://github.com/apple/swift/pull/24268. Sema no longer needs to completely check ahead of time all ClangImporter-synthesized conformances it thinks are going to be used by SILGen, IRGen and the runtime.

### CODE REVIEW

**Review by DougGregor — APPROVED** [review]
This looks great!

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please benchmark

**Comment by slavapestov** [comment]
@swift-ci Please test compiler performance

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Comment by slavapestov** [comment]
# Summary for master full

**Unexpected test results, excluded stats for ProcedureKit, Tagged, Wordy, Deferred**

**Regressions found (see below)**

- [Debug-batch](#debug-batch-43752ed5281ccd9d)
    - [debug-batch brief](#debug-batch-brief-43752ed5281ccd9d)
    - [debug-batch detailed](#debug-batch-detailed-43752ed5281ccd9d)
- [Release](#release-43752ed5281ccd9d)
    - [release brief](#release-brief-43752ed5281ccd9d)
    - [release detailed](#release-detailed-43752ed5281ccd9d)



<a name="debug-batch-43752ed5281ccd9d">

# Debug-batch

<a name="debug-batch-brief-43752ed5281ccd9d">

## debug-batch brief
<details>
<summary>Regressed (0)</summary>

name | old | new | delta | delta_pct
---: | ---: | ---: | ---: | ---:
</details>
<details>
<summary>Improved (0)</summary>

name | old | new | delta | delta_pct
---: | ---: | ---: | ---: | ---:
</details>
<details>
<summary>Unchanged (delta < 1.0% or delta < 100.0ms) (3)</summary>

name | old | new | delta | delta_pct
---: | ---: | ---: | ---: | ---:
Frontend.NumInstructionsExecuted | 27,325,385,146,220 | 27,267,471,404,188 | -57,913,742,032 | -0.21%
LLVM.NumLLVMBytesOutput | 1,115,254,588 | 1,115,132,294 | -122,294 | -0.01%
time.swift-driver.wall | 2539.7s | 2534.7s | -5.0s | -0.2%
</details>

<a name="debug-batch-detailed-43752ed5281ccd9d">

## debug-batch detailed
<details>
<summary>Regressed (2)</summary>

name | old | new | delta | delta_pct
---: | ---: | ---: | ---: | ---:
Driver.NumDriverPipePolls | 215,947 | 219,009 | 3,062 | 1.42% :no_entry:
Driver.NumDriverPipeReads | 232,047 | 235,851 | 3,804 | 1.64% :no_entry:
</details>
<details>
<summary>Improved (6)</summary>

name | old | new | delta | delta_pct
---: | ---: | ---: | ---: | ---:
AST.NumUsedConformances | 260,455 | 0 | -260,455 | -100.0% :white_check_mark:
Sema.EnumRawTypeRequest | 17,388 | 15,495 | -1,893 | -10.89% :white_check_mark:
Sema.InheritedDeclsReferencedRequest | 4,275,636 | 4,192,561 | -83,075 | -1.94% :white_check_mark:
Sema.NumConformancesDeserialized | 6,456,488 | 6,373,617 | -82,871 | -1.28% :white_check_mark:
Sema.SelfBoundsFromWhereClauseRequest | 6,114,789 | 6,040,790 | -73,999 | -1.21% :white_check_mark:
Sema.UnderlyingTypeDeclsReferencedRequest | 165,852 | 163,918 | -1,934 | -1.17% :white_check_mark:
</details>
<details>
<summary>Unchanged (delta < 1.0% or delta < 100.0ms) (98)</summary>

name | old | new | delta | delta_pct
---: | ---: | ---: | ---: | ---:
AST.NumASTBytesAllocated | 64,466,599,695 | 64,317,656,557 | -148,943,138 | -0.23%
AST.NumDecls | 92,845 | 92,845 | 0 | 0.0%
AST.NumDependencies | 165,171 | 165,173 | 2 | 0.0%
AST.NumImportedExternalDefinitions | 1,010,583 | 1,009,923 | -660 | -0.07%
AST.NumInfixOperators | 34,221 | 34,221 | 0 | 0.0%
AST.NumLinkLibraries | 0 | 0 | 0 | 0.0%
AST.NumLoadedModules | 201,880 | 201,880 | 0 | 0.0%
AST.NumLocalTypeDecls | 123 | 123 | 0 | 0.0%
AST.NumObjCMethods | 15,429 | 15,429 | 0 | 0.0%
AST.NumPostfixOperators | 18 | 18 | 0 | 0.0%
AST.NumPrecedenceGroups | 16,906 | 16,906 | 0 | 0.0%
AST.NumPrefixOperators | 85 | 85 | 0 | 0.0%
AST.NumReferencedDynamicNames | 122 | 122 | 0 | 0.0%
AST.NumReferencedMemberNames | 4,049,595 | 4,049,595 | 0 | 0.0%
AST.NumReferencedTopLevelNames | 312,993 | 312,993 | 0 | 0.0%
AST.NumSourceBuffers | 271,377 | 271,377 | 0 | 0.0%
AST.NumSourceLines | 2,974,061 | 2,974,061 | 0 | 0.0%
AST.NumSourceLinesPerSecond | 2,390,803 | 2,398,175 | 7,372 | 0.31%
AST.NumTotalClangImportedEntities | 3,958,536 | 3,969,087 | 10,551 | 0.27%
Driver.ChildrenMaxRSS | 111,014,045,696 | 111,089,254,400 | 75,208,704 | 0.07%
Driver.DriverDepCascadingDynamic | 0 | 0 | 0 | 0.0%
Driver.DriverDepCascadingExternal | 0 | 0 | 0 | 0.0%
Driver.DriverDepCascadingMember | 0 | 0 | 0 | 0.0%
Driver.DriverDepCascadingNominal | 0 | 0 | 0 | 0.0%
Driver.DriverDepCascadingTopLevel | 0 | 0 | 0 | 0.0%
Driver.DriverDepDynamic | 0 | 0 | 0 | 0.0%
Driver.DriverDepExternal | 0 | 0 | 0 | 0.0%
Driver.DriverDepMember | 0 | 0 | 0 | 0.0%
Driver.DriverDepNominal | 0 | 0 | 0 | 0.0%
Driver.DriverDepTopLevel | 0 | 0 | 0 | 0.0%
Driver.NumDriverJobsRun | 18,540 | 18,540 | 0 | 0.0%
Driver.NumDriverJobsSkipped | 0 | 0 | 0 | 0.0%
Driver.NumProcessFailures | 0 | 0 | 0 | 0.0%
Frontend.MaxMallocUsage | 616,136,881,368 | 615,484,624,872 | -652,256,496 | -0.11%
Frontend.NumInstructionsExecuted | 27,325,385,146,220 | 27,267,471,404,188 | -57,913,742,032 | -0.21%
Frontend.NumProcessFailures | 0 | 0 | 0 | 0.0%
IRModule.NumIRAliases | 115,571 | 115,571 | 0 | 0.0%
IRModule.NumIRBasicBlocks | 4,399,402 | 4,399,190 | -212 | -0.0%
IRModule.NumIRComdatSymbols | 0 | 0 | 0 | 0.0%
IRModule.NumIRFunctions | 2,083,526 | 2,083,318 | -208 | -0.01%
IRModule.NumIRGlobals | 2,107,813 | 2,107,070 | -743 | -0.04%
IRModule.NumIRIFuncs | 0 | 0 | 0 | 0.0%
IRModule.NumIRInsts | 54,867,102 | 54,865,946 | -1,156 | -0.0%
IRModule.NumIRNamedMetaData | 90,000 | 90,000 | 0 | 0.0%
IRModule.NumIRValueSymbols | 3,789,105 | 3,788,332 | -773 | -0.02%
LLVM.NumLLVMBytesOutput | 1,115,254,588 | 1,115,132,294 | -122,294 | -0.01%
Parse.NumFunctionsParsed | 168,448 | 168,448 | 0 | 0.0%
Parse.NumIterableDeclContextParsed | 815,484 | 815,484 | 0 | 0.0%
SILModule.NumSILGenDefaultWitnessTables | 0 | 0 | 0 | 0.0%
SILModule.NumSILGenFunctions | 1,071,861 | 1,071,612 | -249 | -0.02%
SILModule.NumSILGenGlobalVariables | 40,105 | 40,106 | 1 | 0.0%
SILModule.NumSILGenVtables | 11,745 | 11,745 | 0 | 0.0%
SILModule.NumSILGenWitnessTables | 45,902 | 45,715 | -187 | -0.41%
SILModule.NumSILOptDefaultWitnessTables | 0 | 0 | 0 | 0.0%
SILModule.NumSILOptFunctions | 1,499,596 | 1,499,174 | -422 | -0.03%
SILModule.NumSILOptGlobalVariables | 40,991 | 40,992 | 1 | 0.0%
SILModule.NumSILOptVtables | 19,254 | 19,254 | 0 | 0.0%
SILModule.NumSILOptWitnessTables | 99,776 | 99,454 | -322 | -0.32%
Sema.AccessLevelRequest | 2,552,863 | 2,551,888 | -975 | -0.04%
Sema.AttachedPropertyDelegateRequest | 1,329,471 | 1,328,788 | -683 | -0.05%
Sema.AttachedPropertyDelegateTypeRequest | 224,573 | 224,573 | 0 | 0.0%
Sema.CustomAttrNominalRequest | 0 | 0 | 0 | 0.0%
Sema.DefaultAndMaxAccessLevelRequest | 56,979 | 56,979 | 0 | 0.0%
Sema.DefaultTypeRequest | 371,663 | 371,663 | 0 | 0.0%
Sema.ExtendedNominalRequest | 3,453,471 | 3,426,631 | -26,840 | -0.78%
Sema.InheritedTypeRequest | 656,493 | 656,991 | 498 | 0.08%
Sema.IsDynamicRequest | 1,948,316 | 1,947,676 | -640 | -0.03%
Sema.IsFinalRequest | 3,766,324 | 3,758,206 | -8,118 | -0.22%
Sema.IsObjCRequest | 1,708,608 | 1,708,074 | -534 | -0.03%
Sema.MangleLocalTypeDeclRequest | 246 | 246 | 0 | 0.0%
Sema.NamedLazyMemberLoadFailureCount | 20,644 | 20,608 | -36 | -0.17%
Sema.NamedLazyMemberLoadSuccessCount | 18,820,840 | 18,854,997 | 34,157 | 0.18%
Sema.NominalTypeLookupDirectCount | 31,648,869 | 31,621,455 | -27,414 | -0.09%
Sema.NumConstraintScopes | 17,288,395 | 17,285,847 | -2,548 | -0.01%
Sema.NumConstraintsConsideredForEdgeContraction | 43,286,824 | 43,286,079 | -745 | -0.0%
Sema.NumDeclsDeserialized | 46,606,137 | 46,382,648 | -223,489 | -0.48%
Sema.NumDeclsFinalized | 1,759,960 | 1,755,457 | -4,503 | -0.26%
Sema.NumDeclsTypechecked | 1,003,674 | 1,003,674 | 0 | 0.0%
Sema.NumDeclsValidated | 2,179,307 | 2,179,276 | -31 | -0.0%
Sema.NumFunctionsTypechecked | 952,829 | 952,749 | -80 | -0.01%
Sema.NumGenericSignatureBuilders | 1,126,670 | 1,126,297 | -373 | -0.03%
Sema.NumLazyGenericEnvironments | 9,216,912 | 9,175,842 | -41,070 | -0.45%
Sema.NumLazyGenericEnvironmentsLoaded | 213,413 | 213,363 | -50 | -0.02%
Sema.NumLazyIterableDeclContexts | 6,127,234 | 6,095,468 | -31,766 | -0.52%
Sema.NumLeafScopes | 11,585,600 | 11,583,387 | -2,213 | -0.02%
Sema.NumTypesDeserialized | 15,360,140 | 15,309,093 | -51,047 | -0.33%
Sema.NumTypesValidated | 1,644,417 | 1,644,417 | 0 | 0.0%
Sema.NumUnloadedLazyIterableDeclContexts | 3,874,453 | 3,848,679 | -25,774 | -0.67%
Sema.OverriddenDeclsRequest | 7,669,619 | 7,636,599 | -33,020 | -0.43%
Sema.PropertyDelegateBackingPropertyInfoRequest | 222,184 | 222,184 | 0 | 0.0%
Sema.PropertyDelegateBackingPropertyTypeRequest | 224,573 | 224,573 | 0 | 0.0%
Sema.PropertyDelegateTypeInfoRequest | 0 | 0 | 0 | 0.0%
Sema.RequirementRequest | 68,968 | 68,968 | 0 | 0.0%
Sema.SetterAccessLevelRequest | 145,194 | 145,194 | 0 | 0.0%
Sema.SuperclassDeclRequest | 74,108 | 74,053 | -55 | -0.07%
Sema.SuperclassTypeRequest | 34,367 | 34,367 | 0 | 0.0%
Sema.TypeDeclsFromWhereClauseRequest | 30,730 | 30,730 | 0 | 0.0%
Sema.USRGenerationRequest | 12,707,187 | 12,628,875 | -78,312 | -0.62%
</details>

<a name="release-43752ed5281ccd9d">

# Release

<a name="release-brief-43752ed5281ccd9d">

## release brief
<details>
<summary>Regressed (0)</summary>

name | old | new | delta | delta_pct
---: | ---: | ---: | ---: | ---:
</details>
<details>
<summary>Improved (0)</summary>

name | old | new | delta | delta_pct
---: | ---: | ---: | ---: | ---:
</details>
<details>
<summary>Unchanged (delta < 1.0% or delta < 100.0ms) (3)</summary>

name | old | new | delta | delta_pct
---: | ---: | ---: | ---: | ---:
Frontend.NumInstructionsExecuted | 28,878,195,378,618 | 28,860,675,710,815 | -17,519,667,803 | -0.06%
LLVM.NumLLVMBytesOutput | 944,150,642 | 944,126,750 | -23,892 | -0.0%
time.swift-driver.wall | 4487.4s | 4483.4s | -4.1s | -0.09%
</details>

<a name="release-detailed-43752ed5281ccd9d">

## release detailed
<details>
<summary>Regressed (0)</summary>

name | old | new | delta | delta_pct
---: | ---: | ---: | ---: | ---:
</details>
<details>
<summary>Improved (1)</summary>

name | old | new | delta | delta_pct
---: | ---: | ---: | ---: | ---:
AST.NumUsedConformances | 261,370 | 0 | -261,370 | -100.0% :white_check_mark:
</details>
<details>
<summary>Unchanged (delta < 1.0% or delta < 100.0ms) (22)</summary>

name | old | new | delta | delta_pct
---: | ---: | ---: | ---: | ---:
AST.NumImportedExternalDefinitions | 231,098 | 230,989 | -109 | -0.05%
AST.NumLoadedModules | 16,804 | 16,804 | 0 | 0.0%
AST.NumTotalClangImportedEntities | 792,972 | 796,460 | 3,488 | 0.44%
IRModule.NumIRBasicBlocks | 3,824,271 | 3,824,209 | -62 | -0.0%
IRModule.NumIRFunctions | 1,743,720 | 1,743,646 | -74 | -0.0%
IRModule.NumIRGlobals | 1,849,488 | 1,849,392 | -96 | -0.01%
IRModule.NumIRInsts | 34,233,047 | 34,232,789 | -258 | -0.0%
IRModule.NumIRValueSymbols | 3,360,268 | 3,360,138 | -130 | -0.0%
LLVM.NumLLVMBytesOutput | 944,150,642 | 944,126,750 | -23,892 | -0.0%
SILModule.NumSILGenFunctions | 743,967 | 743,795 | -172 | -0.02%
SILModule.NumSILOptFunctions | 997,831 | 997,671 | -160 | -0.02%
Sema.NumConformancesDeserialized | 2,330,004 | 2,327,532 | -2,472 | -0.11%
Sema.NumConstraintScopes | 15,705,417 | 15,705,371 | -46 | -0.0%
Sema.NumDeclsDeserialized | 6,283,264 | 6,283,789 | 525 | 0.01%
Sema.NumDeclsValidated | 1,208,430 | 1,208,430 | 0 | 0.0%
Sema.NumFunctionsTypechecked | 479,219 | 479,215 | -4 | -0.0%
Sema.NumGenericSignatureBuilders | 210,060 | 210,238 | 178 | 0.08%
Sema.NumLazyGenericEnvironments | 1,288,739 | 1,288,243 | -496 | -0.04%
Sema.NumLazyGenericEnvironmentsLoaded | 22,291 | 22,291 | 0 | 0.0%
Sema.NumLazyIterableDeclContexts | 797,520 | 802,466 | 4,946 | 0.62%
Sema.NumTypesDeserialized | 3,323,862 | 3,324,408 | 546 | 0.02%
Sema.NumTypesValidated | 734,764 | 734,764 | 0 | 0.0%
</details>

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Pull request merged**
