### PR TITLE
[docs] Add a section about debugging the typechecker to DebuggingTheC…

### PR DESCRIPTION
**Pull request by gottesmm**
…ompiler.rst.

### CODE REVIEW

**Comment by gottesmm** [comment]
@xedin Hows this look?

**Comment by gottesmm** [comment]
Just the content, I need to wordsmith this a little bit.

**Review by xedin — APPROVED** [review]
Looks great, thank you!

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Pull request merged**
