### PR TITLE
Revert "Use AccessPath in LICM and split loads for combine load/store hoisting"

### PR DESCRIPTION
**Pull request by atrick**
Reverts apple/swift#33987. Apparently the Windows build failed, although it seems unlikely that this would be affected by the platform.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci smoke test and merge

**Comment by atrick** [comment]
@shahmishal Am I supposed to have force merge privileges?

**Comment by compnerd** [comment]
@atrick - I just finished testing locally with something that I think should fix this - #34727
Since this should fix it, I think we should fix forward :)

**Comment by atrick** [comment]
Closing. Thanks @compnerd

**Pull request closed without merging**
