### PR TITLE
[docs] Note that cross repo testing doesn't work for Windows CI.

### PR DESCRIPTION
**Pull request by varungandhi-apple**

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test

**Comment by varungandhi-apple** [comment]
https://bugs.swift.org/browse/SR-13565

**Review by compnerd — APPROVED** [review]

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test and merge

**Comment by compnerd** [comment]
I believe that this should be addressed with #33997

**Pull request closed without merging**
