### PR TITLE
[4.0] Diagnose exclusivity violations for noescape closures

### PR DESCRIPTION
**Pull request by devincoughlin**
This PR enables checking exclusivity violations for no escape closures. For testing purposes it includes all the commits from https://github.com/apple/swift/pull/10360 plus one additional commit (73d7476) that is the only new content for this PR w/r/t 10360.

### CODE REVIEW

**Comment by devincoughlin** [comment]
@swift-ci Please test

**Review by atrick — APPROVED** [review]
Approved for CCC.

**Comment by devincoughlin** [comment]
@swift-ci Please test source compatibility

**Comment by najacque** [comment]
@swift-ci please clean test

**Comment by devincoughlin** [comment]
CCC Information:

Explanation:
Add stricter static enforcement of exclusive access for variables captured
by no escape closures. With this change, the compiler will diagnose when
a no escape closure that accesses a capture is passed to a function if that
access conflicts with an access that is already in progress at the time the
function  is applied.

For example, the compiler will now diagnose statically on the following:

x.mutatingMethod {
  x.mutate()
}

This diagnostic a warning in Swift 3.2 and an error in Swift 4 mode.

Note: This change does not distinguish separate stored properties
accessed inside the closure — inside the closure it treats an access
to a struct stored property as an access to the whole. We plan to relax
this in the future, so this change is stricter that what we intend to
eventually enforce. Nonetheless, we want to get this stricter model
into swift-4.0 branch to gauge its impact and determine if additional model
changes are needed.

Scope of Issue:
This is a source-breaking change. In Swift 4.0 it will cause errors for
code that previously compiled. Fortunately this appears rare: there is
only one project in the Swift Source Compatibility suite with violations.
That project (siesta) has 3 violations, all the in the same function.

Radar: rdar://problem/32020710

Risk: This is a medium risk change. It adds new diagnostics (errors in
Swift 4) and a new analysis pass that runs on all noescape
closures that capture variables. The key risks are implementation mistakes
(crashes in the analysis) and the potential for source breakage
in Swift 4 code. We think this source breakage is relatively rare, but it
will happen.

Testing: We've added the usual regression tests and also evaluated on
the source compatibility suite.

**Pull request merged**
