### PR TITLE
Disable test on  iphonesimulator-i386 / 32bit

### PR DESCRIPTION
**Pull request by shajrawi**
unblocks the bot

### CODE REVIEW

**Comment by shajrawi** [comment]
@swift-ci Please smoke test and merge

**Comment by shajrawi** [comment]
cc @milseman @xedin this should unblock the bot / fallout from https://github.com/apple/swift/pull/22388

**Comment by shajrawi** [comment]
`/Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/swift/stdlib/public/Darwin/QuartzCore/NSValue.swift.gyb:33:50: error: use of undeclared type 'Type'` has been failing on and off on all the bots since yesterday - it is unrelated..

**Comment by shajrawi** [comment]
@swift-ci Please clean smoke test OS X

**Review by xedin — COMMENTED** [review]
Thank you!

**Pull request merged**
