### PR TITLE
No more `pipes`

### PR DESCRIPTION
**Pull request by kavon**
eliminates `pipes` in favor of `shlex` in our python utilites.

This solves deprecation warnings in build-script:

```
DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
```

This change assumes that the minimum version
of Python3 is 3.3, which has `shlex.quote`.

Since our build bots currently use 3.6 as their
Python version, we can't yet use `shlex.join`
to further simplify some of the code using
quote.

### CODE REVIEW

**Comment by kavon** [comment]
@swift-ci please test

**Comment by kavon** [comment]
@swift-ci please test and merge

**Comment by kavon** [comment]
turns out the linter test doesn't report all issues it found.

**Comment by kavon** [comment]
@swift-ci smoke test and merge

**Review by xedin — APPROVED** [review]

**Pull request merged**
