### PR TITLE
[5.6][SE-0309] Disable SE-0309 in Swift 5.6.

### PR DESCRIPTION
**Pull request by hborla**
* **Explanation**: [SE-0309](https://github.com/apple/swift-evolution/blob/main/proposals/0309-unlock-existential-types-for-all-protocols.md) enables using protocols with `Self` or associated type requirements as existential types. This feature is not fully implemented; one of the missing pieces from the proposal in Swift 5.6 is [covariant erasure for dependent-member types](https://github.com/apple/swift/pull/39492), which allows calling the APIs that use `Self` or associated type in covariant position on the existential type. Without this functionality, the API surface on SE-0309 existentials is fairly limited, and leads to confusing error messages when attempting to call APIs that should be available via covariant erasure. This change adds a frontend flag `-enable-experimental-universal-existentials` for SE-0309, and disables the feature by default. This change also disables building the experimental _Distributed library by default, because it adopts SE-0309 (in code that no longer exists on the `main` branch).
* **Scope**: This is a new feature in Swift 5.6, so there is no impact on existing code.
* **Risk**: Because this is a new feature, there is no risk for taking this change.
* **Testing**: Added the `-enable-experimental-universal-existentials` flag to several existing tests that make use of SE-0309.

### CODE REVIEW

**Comment by hborla** [comment]
@swift-ci please clean test

**Comment by AnthonyLatsis** [comment]
Thanks! I imagined this was going to be more of a pain in one place but then you just gated it behind a flag 😅

**Comment by hborla** [comment]
@AnthonyLatsis it was pretty convenient that I happened to already put the code that identifies SE-0309 existentials back for SE-0335 😆

**Comment by hborla** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]

**Review by airspeedswift — APPROVED** [review]

**Pull request merged**
