### PR TITLE
[Sema] Intro the @_spiOnly attribute on import statements

### PR DESCRIPTION
**Pull request by xymus**
Prepare the scene for the @_spiOnly attribute on import statements. This modifier will effectively import the target only in the private swiftinterface and swiftmodule, the import will be absent from the public swiftinterface. Type-checking will ensure that imported types are only used in SPI and implementation details, uses in API will be diagnosed.

This PR introduces the attribute, the import filters and the flag required to enable the feature. Next I'll add swiftinterface printing support, exportability diagnostics, and integration with adjacent SDK sanity checks.

### CODE REVIEW

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by xymus** [comment]
I changed the flag behavior to keep it out of the swiftinterfaces. If we don't print it and always assume the feature to be enabled there we can make older and future compilers compatible with the same swiftinterfaces.

@swift-ci Please smoke test

**Review by tshortli — APPROVED** [review]

**Comment by xymus** [comment]
@swift-ci Please smoke test Linux

**Comment by xymus** [comment]
There are connection issues on the CI bots.

@swift-ci Please smoke test macOS

**Pull request merged**
