### PR TITLE
[ClangImporter] Always import types under their Swift 4 name.

### PR DESCRIPTION
**Pull request by jrose-apple**
This means all cross-module references and all mangled names will consistently use the Swift 4 name (the canonical type), no special handling required.

The main thing we lose here is that the Swift 4 names of imported types become usable in Swift 3 mode without any diagnostics, similar to how most language features introduced in Swift 4 are available in Swift 3 mode. It also implies that the Swift 4 name will show up in demangled names.

rdar://problem/31616162 rdar://problem/31848862

(This PR also slurps in some improvements to swift-ide-test that I should really break out separately.)

### CODE REVIEW

**Comment by jrose-apple** [comment]
Slava has pointed out to me that I should be very careful considering the implications of this, since it means Swift 3 users will mostly be going through typealiases. Known TODOs:

- Don't show "aka" for these typealiases; showing the Swift 4 name wouldn't be helpful in most cases.
- When importing a Swift 3 API in Swift 4 mode, look through the typealias. This will be something akin to #8737, but more limited.

@swift-ci Please test macOS

**Comment by jrose-apple** [comment]
The unrelated cleanup / general improvements have been split out to #9007, #9008, #9010.

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Review by milseman — APPROVED** [review]
This LGTM!

**Pull request merged**
