### PR TITLE
[LangOptions] Specify PowerPC 32-bit as big endian

### LINKED ISSUE #58206: [SR-15945] RFE: PowerPC 32-bit Support
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15945      |
   |Radar             | None         |
   |Original Reporter | @colemancda      |
   |Type              | New Feature    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164964475-e7ed9d87-7dde-466f-a623-d329b5d6ec9a.gz)

      
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | New Feature        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 5741c004b901bbdfd704755eb25f68fd

  </details>

**Issue Description:**

Swift should support compiling to ppc and ppcle.

### PR DESCRIPTION
**Pull request by colemancda**
Add fixes PowerPC 32-bit support:
- Specify PPC32 as big endian (e.g. `#if _endian(big)`)

Resolves [SR-15945](https://github.com/apple/swift/issues/58206)

### CODE REVIEW

**Comment by colemancda** [comment]
@compnerd Can you review please?

**Comment by colemancda** [comment]
@MaxDesiatov Can you review please? Its a simple but crucial change I missed with my previously merged commit.

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Comment by MaxDesiatov** [comment]
> Can you review please?

Sorry, I'm not a code owner here, so you'll have to get a review from someone else.

**Comment by colemancda** [comment]
@DougGregor Can you review please? The PR @CodaFi [previously merged](https://github.com/apple/swift/pull/41656) crashes because PPC32 endianness is undefined.

**Pull request closed without merging**
