### PR TITLE
[sourcekitd][test] Test CursorInfo works correctly with modules loaded via a parseable interface

### PR DESCRIPTION
**Pull request by nathawes**
Add test that we report documentation, refactoring actions and other symbol info correctly when using modules built via parseable interfaces.

Resolves rdar://problem/43906499

### CODE REVIEW

**Comment by nathawes** [comment]
@swift-ci test

**Comment by nathawes** [comment]
@swift-ci please test OS X Platform

**Comment by nathawes** [comment]
@swift-ci please test OS X Platform

**Comment by nathawes** [comment]
@swift-ci smoke test

**Comment by nathawes** [comment]
@swift-ci please smoke test

**Comment by nathawes** [comment]
@swift-ci please test

**Comment by nathawes** [comment]
@swift-ci please test

**Review by jrose-apple — APPROVED** [review]

**Review by nkcsgexi — APPROVED** [review]

**Pull request merged**
