### PR TITLE
[5.0] Data Inlinability Refinements

### PR DESCRIPTION
**Pull request by itaiferber**
**What's in this pull request?**
Cherry-picks #21754 to swift-5.0-branch. Resolves 46780357

### CODE REVIEW

**Comment by itaiferber** [comment]
@swift-ci Please benchmark

**Comment by itaiferber** [comment]
@swift-ci Please test

**Comment by itaiferber** [comment]
@parkera Who should we get to review here?

**Review by airspeedswift — APPROVED** [review]

**Comment by airspeedswift** [comment]
@itaiferber I can approve from a landing-in-5.0 perspective but it probably needs a second engineer from Foundation to review for correctness.

**Review by phausler — APPROVED** [review]

**Comment by phausler** [comment]
@airspeedswift it looks good to me, this is just a cherry-pick from master of the work Itai did for annotating the reasons for inlines and slight tweaks for those.

**Comment by itaiferber** [comment]
Thanks @airspeedswift!

**Pull request merged**
