### PR TITLE
[test] IRGen/opaque_result_alwaysInlineIntoClient: disable on non-local test configs

### PR DESCRIPTION
**Pull request by lorentey**
This silences a CI blocker issue.

rdar://97995151

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci smoke test and merge

**Review by xedin — APPROVED** [review]

**Comment by lorentey** [comment]
Hm, a better fix for this class of problems would probably be to disable the `swift_interpreter` feature when `remote_run` or `device_run` is configured in `lit.cfg`.

**Comment by lorentey** [comment]
@swift-ci smoke test

**Comment by xedin** [comment]
Interesting! Thank you, @lorentey!

**Pull request merged**
