### PR TITLE
5.0 build

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
@swift5-branch-managers this is a low risk build only fix.  It is a set of cherry-picks from master, changing the way that the fat library linking works.  This fixes it so use the right target on non-MachO targets to actually link against the correct variant.  It also cherry-picks a change to re-order the CMake registration to allow cross-compiling the windows SDK again.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by gottesmm** [comment]
@compnerd I don't think you can ping someone via an edit. @apple/swift5-branch-managers (for compnerd's post here): 
https://github.com/apple/swift/pull/21084#issuecomment-444971152

**Comment by compnerd** [comment]
@apple/swift5-branch-managers ... sorry, can't GitHub, see the above comment.

**Review by bob-wilson — APPROVED** [review]

**Comment by compnerd** [comment]
@bob-wilson - could you merge this please?

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @tkremenek

**Pull request merged**
