### PR TITLE
Replace buildin.addressof with withUnsafeMutablePointer

### PR DESCRIPTION
**Pull request by trentxintong**

### CODE REVIEW

**Comment by trentxintong** [comment]
@swift-ci Please test

**Comment by trentxintong** [comment]
@swift-ci Please smoke test

**Comment by gparker42** [comment]
@jrose-apple, is this really an improvement? I'm worried that it looks safer than it actually is because it breaks the safe usage of `withUnsafeMutablePointer`. If we're going to do that then we may as well keep doing the thing that also looks unsafe.

**Comment by jrose-apple** [comment]
Builtin.addressof is no more or less safe than withUnsafeMutablePointer; they are unsound in exactly the same cases.

**Comment by jrose-apple** [comment]
(modulo lifetime concerns)

**Comment by jrose-apple** [comment]
Oh, wait, never mind. I should read the patch first.

Xin, I meant to put the whole body inside the withUnsafeMutablePointer. It's *not* considered safe to propagate that address out of the body.

**Comment by gribozavr** [comment]
> It's not considered safe to propagate that address out of the body.

Why?  It is an address of a global.  It is valid for the whole program execution.

**Comment by jckarter** [comment]
I agree with @jrose-apple, `Builtin.addressof` with a comment that we're relying on its operand being a non-reabstracted global variable is better than pretending we're being safe by misusing `withUnsafePointer`.

**Comment by jrose-apple** [comment]
I'm not sure if that's agreeing with me or @gribozavr. I want to use withUnsafeMutablePointer the usual way with a comment saying we're relying on it being the actual address (on the grounds that external developers should be able to do the same thing). @gribozavr wants to use Builtin.addressof with the same comment (which is what @trentxintong originally implemented, though without the comment). The current patch doesn't do either (sorry, Xin).

**Comment by gribozavr** [comment]
> @gribozavr wants to use Builtin.addressof with the same comment

I don't actually care whether there is a comment or not.  The use of the builtin is enough of a signal that something unusual is happening, and the whole method is small enough for the reader to immediately notice the atomic operations.

**Comment by trentxintong** [comment]
@jrose-apple sorry that i misunderstood you. 

I am fine to move everything in the function into the closure (i feel it might "look" safer), But i also agree with @gribozavr that the variable is an address of a global which is valid for the whole program execution and the builtin is enough of a signal that something unusual is happening.

I am going to let this stay as a builtin.addressof unless we have compelling reasons that withUnsafeMutablePointer leads to a real improvement.

**Comment by jckarter** [comment]
Sure, that's fine until we decide to either try to kill `addressof` or to get more aggressive reasoning about global writes for some reason.

**Comment by jrose-apple** [comment]
All right, guess I'm overruled. Thanks for the discussion, at least (and thanks for humoring me, Xin).

**Pull request closed without merging**
