### PR TITLE
[Constraint solver] Remove expression from the constructor.

### PR DESCRIPTION
**Pull request by DougGregor**
Rather than setting up the constraint solver with a single expression
(that gets recorded for parents/depths), record each expression that
goes through constraint generation.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Review by xedin — COMMENTED** [review]
My two cents are related to the fact that we don't really need to recompute the weights for the individually type-checked sub-expressions in CSDiag all of the sub-CSs could refer to the original one for this.

**Comment by DougGregor** [comment]
> My two cents are related to the fact that we don't really need to recompute the weights for the individually type-checked sub-expressions in CSDiag all of the sub-CSs could refer to the original one for this.

Ah, sure. At the very least, we can look up the chain *first*.

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Pull request merged**
