### PR TITLE
Fix some opaque pointer LLVM IR tests (5)

### PR DESCRIPTION
**Pull request by aschwaighofer**

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci test

**Comment by aschwaighofer** [comment]
@swift-ci test

**Comment by ktoso** [comment]
I don't know much about opaque pointers but if the distributed tests pass LGTM from my side 😅

**Review by ktoso — APPROVED** [review]

**Comment by aschwaighofer** [comment]
@swift-ci test

**Comment by aschwaighofer** [comment]
@swift-ci test macOS

**Comment by aschwaighofer** [comment]
@swift-ci test macOS

**Comment by aschwaighofer** [comment]
@swift-ci test macOS

**Pull request merged**
