### PR TITLE
[CS] Fix conditional conformances in overload ranking.

### PR DESCRIPTION
**Pull request by huonw**
Resolves rdar://problem/35480952.

### CODE REVIEW

**Comment by huonw** [comment]
@swift-ci Please smoke test and merge

**Comment by huonw** [comment]
Eh, @DougGregor, I guess this wasn't as successful as we'd hoped. :(

**Comment by huonw** [comment]
@swift-ci Please smoke test

**Comment by DougGregor** [comment]
Oh, it's totally good. The one test that broke was actually FIXME'd already because it was giving the wrong result. I'll give this a little more testing and then get a PR merged for it.

**Comment by DougGregor** [comment]
https://github.com/apple/swift/pull/12905 pulls in the first commit from this and then introduces some cleanup.

**Pull request closed without merging**
