### PR TITLE
[stdlib] Remove vestigial _DisabledRangeIndex associated type

### PR DESCRIPTION
**Pull request by airspeedswift**
Use of this type was removed a while back, in #13342, but this part got missed.

### CODE REVIEW

**Comment by airspeedswift** [comment]
@gottesmm @jckarter this type is referenced in https://github.com/apple/swift/blob/master/test/SIL/Parser/witness_with_inherited_gp.sil. That test seems stale and long-disabled, should we just delete it?

**Comment by gottesmm** [comment]
@airspeedswift I would not delete the test. I would try to rephrase it with a different type or copy in the type into the test.

**Comment by jrose-apple** [comment]
@gottesmm Take a look at this particular test before answering. :-) I'm with Ben.

**Comment by jckarter** [comment]
Yes, delete the meaningless test. Thanks!

**Comment by gottesmm** [comment]
If it is meaningless feel free to delete. My only concern was if we are losing coverage.

**Comment by jrose-apple** [comment]
Ready to merge?

**Comment by airspeedswift** [comment]
Yeah. I never got to delete the old test. But the part with this type is commented out anyway, so I'll do it in a separate PR.

**Pull request merged**
