### PR TITLE
[update_checkout] Complain about duplicate scheme definitions

### PR DESCRIPTION
**Pull request by vedantk**
Duplicate definitions for the same scheme go out of sync, and cause
angst due to the wrong repos getting checked out.

### CODE REVIEW

**Comment by vedantk** [comment]
@swift-ci smoke test

**Review by shahmishal — APPROVED** [review]

**Review by JDevlieghere — APPROVED** [review]

**Comment by gottesmm** [comment]
@vedantk can you add a test for this?

**Comment by vedantk** [comment]
I've added a test. @shahmishal I believe this should be force-merged to avoid wasting any more machine resources/time.

And the python linting 'test' that caused a build failure on macOS should be deleted.

**Comment by gottesmm** [comment]
@vedantk where is the test?

**Comment by vedantk** [comment]
It's a doctest -- don't have the time to extend the scheme_mock test case, we can set this aside for now.

**Comment by gottesmm** [comment]
Thanks!

**Pull request closed without merging**
