### PR TITLE
Driver: mark test as XFAIL on windows

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @drodriguez

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
Actually, no, this is wrong, it does work, it is a question of which `rm` is in use.  The one from git actually does work.

**Comment by compnerd** [comment]
@swift-ci please smoke test macOS platform

**Comment by compnerd** [comment]
CC: @shahmishal

**Comment by drodriguez** [comment]
I don't think this is the file that was failing. The failing file was `test/Driver/batch_mode_with_supplementary_filelist_unicode.swift` and this PR modifies `test/Driver/batch_mode_with_supplementary_filelist.swift` instead.

**Comment by drodriguez** [comment]
David opened #28902 and I opened #28905 with possible fixes. I don't have a Windows machine at home to test, so the CI machines are doing the work.

**Pull request merged**
