### PR TITLE
Sema: Filter out protocol extension default implementations of operators

### PR DESCRIPTION
**Pull request by slavapestov**
In solution ranking we always prefer a protocol operator over
a protocol extension operator. So if their interface types are
identical, any set of fixed type assignments that satisfies
the default implementation will also satisfy the protocol requirement.

Thus, we can filter out the default implementation early and not
consider it at all.

This speeds up expressions involving bitwise shift operators,
for example.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Review by xedin — APPROVED** [review]

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Pull request merged**
