### PR TITLE
[SDK] Support {public} modifier for os_log

### PR DESCRIPTION
**Pull request by lilyball**
Also match clang's parsing for public/private. This way `{privatestuff}`
isn't incorrectly treated as `{private}`, but `{private,errno}` is.

If the format string ends in the middle of a `{modifier}` string, don't
incorrectly attempt to parse the rest of the string as the format
specifier, e.g. `"%{stuff"`.

### CODE REVIEW

**Comment by kballard** [comment]
I feel like we should consider turning this stuff into a builtin, so we can re-use clang's format string parsing, instead of trying to replicate it.

**Comment by kballard** [comment]
To expound upon this, the current behavior of `os_log` in Swift (without this PR) makes it almost entirely useless, because it's impossible to log string values. Not even static strings (passed as arguments) are interpreted as public, presumably because Swift doesn't produce `__NSCFConstantString`s (which is—I assume—how `os_log` detects them). So all I can log right now are integers, and that's not very useful.

**Comment by jrose-apple** [comment]
`os_log` is an Apple feature, not part of the Swift open source project, so I'd normally have to check this with the framework owner. In this case though I think the code owner would be @mwwa from Dispatch.

(This is mostly a general disclaimer that people shouldn't submit new overlay features and enhancements as pull requests. Bug fixes we have a chance of taking, though, and this is in that realm since it's about parity with Objective-C.)

**Comment by kballard** [comment]
I figured you'd say something like that, which is why this PR is strictly a bug fix. The comments I left about future development are mostly just to spur discussion, with the intention of eventually submitting a bug report proposing any actual enhancements.

**Comment by CodaFi** [comment]
Support for this modifier [shipped with 8.3 beta 1](https://github.com/apple/swift/commit/92ef777085a8345f93166d65520f06100e138d62#diff-d7d691f7dfed37f5cebb1e7706e76c97R174).  Closing this.

**Pull request closed without merging**
