### PR TITLE
[inliner] Treat inline_always as meaning truly inline_always even in …

### PR DESCRIPTION
**Pull request by gottesmm**
…situations where we have large caller CFGs.

Currently if a caller is > 400 blocks, the inliner bails out of finding
inlinable targets. This is incorrect behavior for inline always functions. In
such cases, we should continue inlining inline always functions and skip any
functions that are not inline always.

rdar://45976860

### CODE REVIEW

**Comment by gottesmm** [comment]
I am going to add some tests before I commit this. Just want to do some initial testing/benchmarking.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci test compiler performance

**Review by eeckstein — APPROVED** [review]
lgtm

**Comment by milseman** [comment]
Do we know why the stdlib is 5% bigger with this? This is worth taking even if we have to suffer that regression, but I'm thinking that this might expose some needless code bloat.

**Comment by gottesmm** [comment]
I didn't look into it. @airspeedswift and @eeckstein talked about this and decided we were ok taking the code-size hit.

**Pull request merged**
