### PR TITLE
Do not set alignment and don't set disableAddressSanitizer on @llvm.used and @llvm.compiler.used

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by compnerd — APPROVED** [review]
Its really unfortunate that we need to special case this.  Id actually suggest that you should file this upstream at https://bugs.llvm.org if possible - this seems like poor behaviour in LLVM.

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test Windows platform

**Pull request merged**
