### PR TITLE
Foundation exclusivity tests

### PR DESCRIPTION
**Pull request by devincoughlin**
Update two Foundation overlay tests to remove exclusivity violations.

### CODE REVIEW

**Comment by devincoughlin** [comment]
@phausler @millenomi Would you be willing to take a look?

**Comment by devincoughlin** [comment]
@swift-ci Please smoke test

**Comment by devincoughlin** [comment]
@swift-ci smoke test OS X platform

**Review by atrick — APPROVED** [review]
LGTM

**Pull request closed without merging**
