### PR TITLE
ASTPrinter: add an option to skip keywords with an underscore prefix

### PR DESCRIPTION
**Pull request by nkcsgexi**
DocSupport will use set this flag to avoid printing __consuming, __owned, and __shared.

rdar://47777848

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by akyrtzi** [comment]
I think we should hide them from interface generation in general (disable in `PrintOptions::printInterface()`). It's similar to how we set `SkipPrivateStdlibDecls = true` inside that function.

**Comment by harlanhaskins** [comment]
Looks fine to me. Can you add a test to make sure we don't ever set this to true for parseable interfaces? We always want to print these in parseable interfaces.

**Comment by nkcsgexi** [comment]
@harlanhaskins what kind of test do you have in mind? We should have existing tests to ensure parseable interface handles underscored attributes, right?

**Comment by nkcsgexi** [comment]
Maybe i could add an assertion at the entry point of parseable interface generation?

**Comment by harlanhaskins** [comment]
Alternatively, could you set it explicitly in `PrintOptions::printForParseableInterface()`?

**Comment by nkcsgexi** [comment]
@harlanhaskins sure, will do

**Comment by jrose-apple** [comment]
I think we were deliberately printing these. @airspeedswift?

**Review by akyrtzi — APPROVED** [review]

**Comment by akyrtzi** [comment]
Discussed with @airspeedswift and he is fine with hiding them from documentation but would like them to be present in the generated interface.

**Comment by nkcsgexi** [comment]
@airspeedswift @akyrtzi The latest commit moved the flag back to documentation generation option so that we won't skip them in the generated interface from IDE.

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Review by harlanhaskins — APPROVED** [review]

**Comment by nkcsgexi** [comment]
@swift-ci Please smoke test OS X Platform

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Pull request merged**
