### PR TITLE
[CodeCompletion] Implement completion for # directives

### PR DESCRIPTION
**Pull request by rintaro**
* Enable `#` completion at arbitrary expr position.
  * `#selector(<@objc method>)`
  * `#keyPath(<@objc property>)`
  * `#available(<platform ...>, *)` - only in statement condition
* Implement completion for `#` at directive position. 
  * `#sourceLocation(file: <name>, line: <number>)`
  * `#warning("<message>")`/`#error("<message>")`
  * `#if <condition>`, `#elseif <condition>`, `#else`, `#endif`
* Implement completion for condition part of conditional compilation directive.
  * `os(<name>)`, `arch(<name>)`, `canImport(<module>)`, `targetEnvironment(simulator)`
  * `true`/`false`
  * Custom conditional compilation flags specified by `-D`

rdar://problem/19572779
rdar://problem/29976235

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
Review ping @benlangmuir ?

**Review by benlangmuir — APPROVED** [review]
🎉

**Pull request merged**
