### PR TITLE
Frontend: add a frontend flag to disable building module from textual interface

### PR DESCRIPTION
**Pull request by nkcsgexi**
This is for testing purposes to ensure prebuilt modules are up to date.

rdar://68770805

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci Please smoke test Linux platform

**Comment by nkcsgexi** [comment]
@swift-ci Please smoke test Linux platform

**Comment by harlanhaskins** [comment]
Could you also do this by setting the existing `SWIFT_FORCE_MODULE_LOADING` environment variable to `only-serialized`

**Comment by nkcsgexi** [comment]
@harlanhaskins unfortunately not. ModuleInterfaceLoader will not be installed at all if `SWIFT_FORCE_MODULE_LOADING` is set to `only-serialized`. We still need the interface loader in this case to locate the prebuilt modules.

**Comment by nkcsgexi** [comment]
@swift-ci Please smoke test Linux platform

**Comment by nkcsgexi** [comment]
@swift-ci Please smoke test Linux platform

**Comment by nkcsgexi** [comment]
@swift-ci Please clean test Linux platform

**Comment by nkcsgexi** [comment]
@swift-ci Please smoke test Linux platform

**Comment by nkcsgexi** [comment]
@swift-ci Please smoke test Linux platform

**Comment by nkcsgexi** [comment]
@swift-ci Please smoke test Linux platform

**Comment by nkcsgexi** [comment]
@swift-ci Please clean test Linux platform

**Pull request merged**
