### PR TITLE
[embedded] use dedicated CMakeLists.txt to build unicode data tables

### PR DESCRIPTION
**Pull request by edymtt**
This will avoid CMake configuration errors in `llvm_process_sources`
 in configurations that build only the the standard library for embedded.

Addresses rdar://130229502

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci please test

**Comment by edymtt** [comment]
@swift-ci please build toolchain

**Review by phausler — APPROVED** [review]
Seems much cleaner to me to do it this way

**Review by porglezomp — APPROVED** [review]

**Comment by edymtt** [comment]
@swift-ci please test macOS

**Pull request merged**
