### PR TITLE
Constraint simplification cleanups

### PR DESCRIPTION
**Pull request by slavapestov**
- We can now solve a BindParam when both sides are type variables
- We can now solve a Bind when both sides are type variables with different lvalue-ness

Fixes <rdar://problem/45511838>, <https://bugs.swift.org/browse/SR-9068>.

### CODE REVIEW

**Review by xedin — APPROVED** [review]
LGTM. FYI @rudkx and I mostly shy away from using `Bind` too much because (sometimes) it merges types too early and binding calculation code misses some potential bindings as a result, or (I saw that at least ones) causes infinite recursion because of `isBindable` check re-creates bind constraint infinitely if it fails.

**Comment by slavapestov** [comment]
@xedin It looks like this PR may have fixed https://bugs.swift.org/browse/SR-9068

**Comment by xedin** [comment]
@slava_pestov Most likely yes, we had a bunch of bind constraints introduced by hacks in PreCheckExpression and other places like contractEdges, which got fixed at some point...

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
The failure is a UPASS because the bug was fixed.

**Pull request merged**
