### PR TITLE
[gardening] PEP-8 cleanups.

### PR DESCRIPTION
**Pull request by practicalswift**

### CODE REVIEW

**Comment by practicalswift** [comment]
@swift-ci please smoke test

**Comment by practicalswift** [comment]
@swift-ci please test

**Comment by gottesmm** [comment]
@practicalswift I am about to make a fix to the bug reducer, can you wait a second on this?

**Comment by practicalswift** [comment]
@gottesmm Sure, let me know when you're done! :-)

**Comment by gottesmm** [comment]
You'll see it ; p

**Comment by gottesmm** [comment]
(the bug is really dumb, I just gotta find a repro real quick, if the bug-reducer found a candidate and then found a bunch of non-crasher candidates, it would return the last one it tested...).

**Comment by gottesmm** [comment]
You know what, I am going to do the test tomorrow. Go ahead, I'll just fix things.

**Pull request merged**
