### PR TITLE
[stdlib] Fixing a buggy example in the comments in the file UnsafeRawPointer.swift

### PR DESCRIPTION
**Pull request by ravikandhadai**

### CODE REVIEW

**Comment by jrose-apple** [comment]
I thought the point of these APIs was that they do unaligned loads and stores.

**Comment by ravikandhadai** [comment]
Actually, in the current form they do require alignment, as was clarified by @atrick. In fact, `storeBytes` has a precondition that checks the alignment and so does `load`.  I am actually interested in an unaligned version and came across this bug.

**Comment by atrick** [comment]
The underlying primitive assumes alignment. We should definitely have unaligned variants, or add an unaligned flag as an argument, but no one has gotten around to written the Swift evolution proposal.

**Review by atrick — APPROVED** [review]
LGTM

**Comment by ravikandhadai** [comment]
@swift-ci please test and merge

**Pull request merged**
