### PR TITLE
Add support for rebranch in update-checkout script

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci smoke test and merge

**Comment by xymus** [comment]
It looks like the tests were lost by Jenkins.

@swift-ci smoke test and merge

**Comment by zoecarver** [comment]
Looks like there are still Jenkins issues.

**Comment by zoecarver** [comment]
@swift-ci please smoke test.

**Comment by zoecarver** [comment]
@swift-ci please smoke test and merge.

**Pull request merged**
