### PR TITLE
[windows] Enable SourceKit tests in CI.

### PR DESCRIPTION
**Pull request by drodriguez**
Small change to see what's broken in the community CI.

### CODE REVIEW

**Comment by drodriguez** [comment]
@swift-ci please clean test Windows platform

**Comment by gmittert** [comment]
There are still a handful of broken Sourcekit tests on Windows
```
Failing Tests (11):
    Swift(windows-x86_64) :: SourceKit/CodeComplete/injected_vfs.swift
    Swift(windows-x86_64) :: SourceKit/CodeComplete/injected_vfs_complete_open.swift
    Swift(windows-x86_64) :: SourceKit/CodeComplete/injected_vfs_swiftinterface.swift
    Swift(windows-x86_64) :: SourceKit/CompileNotifications/code-completion.swift
    Swift(windows-x86_64) :: SourceKit/CompileNotifications/type-context-info.swift
    Swift(windows-x86_64) :: SourceKit/CursorInfo/injected_vfs.swift
    Swift(windows-x86_64) :: SourceKit/Sema/injected_vfs.swift
    Swift(windows-x86_64) :: SourceKit/Sema/injected_vfs_after_edit.swift
    Swift(windows-x86_64) :: SourceKit/Sema/injected_vfs_sourcetext.swift
    Swift(windows-x86_64) :: SourceKit/Sema/sema_playground.swift
    Swift(windows-x86_64) :: SourceKit/SyntaxMapData/diags.swift
```
By my count, but I'm good to enable these on the Windows CI so we can see that they're broken

**Review by gmittert — APPROVED** [review]

**Comment by gmittert** [comment]
@swift-ci please smoke test

**Comment by gmittert** [comment]
Looks like there are 3 fewer failures than I have locally so that's good. I believe the notification tests and the playground test fail because it generates an error message for both `S:\...` and `C:\...` when it only expects on error and it might not do that on CI depending on how it's set up.

**Comment by drodriguez** [comment]
I think I have a small fix for the `diags.swift` one which should be isolated, and hopefully doesn’t create more problems.

It is good that the `sed` problems I was having doesn’t happen in this case.

I also think that the `%drive` changes in the test might get the VFS failures down to 2 or 3 (one of them probably `SourceKit/CodeComplete/injected_vfs_swiftinterface.swift`)

**Comment by drodriguez** [comment]
Included as part of #28250.

**Pull request closed without merging**
