### PR TITLE
ConstExpr: Significant progress to supporting more complicated cases 

### PR DESCRIPTION
**Pull request by lattner**
- Add a specific diagnostic for loops, which we don't support yet (intentionally).
 - Implement support for copy_addr, begin_access, end_access, destroy_addr, debug_value_addr
 - Add support for ptrtoint of strings to word size, and llvm.expect.
 - Fix updateIndexedElement to be (a) correct, and (b) handle overwriting subelements of uninit memory, which happens with piecewise initialization of constant values.
 - Fix a crasher in lookupOrLinkWitnessTable.  Add better logging.
 - Reimplement substitution mapping from caller to callee to be much closer to correct, still not perfect though.

Many of these cases are exercised by SignedInteger<>.init(_:) which is
incredibly complicated.

### CODE REVIEW

**Comment by lattner** [comment]
@swift-ci please test and merge

**Comment by lattner** [comment]
@swift-ci please test tensorflow

**Comment by lattner** [comment]
@swift-ci please test tensorflow

**Review by rxwei — APPROVED** [review]

**Comment by rxwei** [comment]
This PR is out of sync, please do a rebase onto the tensorflow branch.

**Comment by lattner** [comment]
I will when I have time to do so, thanks!

**Comment by lattner** [comment]
Rebased in my tree, failing testcase reduced down to:

public func testArray() {
  let v = Array(0..<60)
  () = #tfop("Foo", bar: v)
}

it is the ongoing saga of substitution mapping not being exactly right.

**Pull request closed without merging**
