### PR TITLE
[Serialization] Refactor subset of `ModuleFile` into `ModuleFileCore`

### PR DESCRIPTION
**Pull request by akyrtzi**
The difference with `ModuleFile` is that `ModuleFileCore` provides immutable data and is independent of a particular ASTContext.
It is designed to be able to be shared across multiple `ModuleFile`s of different `ASTContext`s in a thread-safe manner.

### CODE REVIEW

**Comment by akyrtzi** [comment]
@swift-ci Please test

**Comment by akyrtzi** [comment]
@swift-ci Please test

**Comment by akyrtzi** [comment]
@swift-ci test OS X platform

**Comment by slavapestov** [comment]
Perhaps we can come up with a different, more descriptive name? ASTModuleFile vs ModuleFile or something?

**Comment by akyrtzi** [comment]
> Perhaps we can come up with a different, more descriptive name? ASTModuleFile vs ModuleFile or something?

@slavapestov what do you think about:
* `ModuleFile` (immutable/sharable state)
* `ModuleFileContext` (mutable, tied to an ASTContext, contains AST decls)?

**Review by xymus — APPROVED** [review]
LGTM and the performance opportunity here is impressive.

I don't mind much about the names but if we are to change them my tendency would be to make it clear that `ModuleFileCore` is immutable and shared so maybe something like `ModuleFileSharedCore`.

**Review by nkcsgexi — APPROVED** [review]
LGTM. The change is huge and I didn't get a chance to review every detail, but a brief glancing convinced me this is a great design choice.

**Comment by akyrtzi** [comment]
@swift-ci Please test

**Comment by akyrtzi** [comment]
@swift-ci Please test

**Comment by akyrtzi** [comment]
I took the suggestion by @xymus for naming.

**Comment by akyrtzi** [comment]
@swift-ci test OS X platform

**Pull request merged**
