### PR TITLE
[benchmark] Fix spurious benchmark regressions

### PR DESCRIPTION
**Pull request by lorentey**
The benchmark driver accidentally fails to set the `SWIFT_DETERMINISTIC_HASHING` environment variable for its subprocesses, which means that hashed collections have far more performance variance than expected.

I think the recent plague of flaky benchmark results (especially `DictionaryOfAnyHashableStrings_insert`) has been due to this issue.

Additionally, update CMake to postprocess the benchmark executables with [`swift-darwin-postprocess.py`](https://github.com/apple/swift/blob/main/utils/swift-darwin-postprocess.py) to work around a dyld issue on macOS Monterey that makes the benchmark executable fail with spurious unknown selector exceptions.

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci benchmark

**Comment by lorentey** [comment]
@swift-ci smoke test

**Comment by lorentey** [comment]
```
21:31:01 + /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-main/buildbot_linux/benchmarks-linux-x86_64/bin/Benchmark_Onone --num-iters=1 XorLoop
21:31:01 DriverUtils/DriverUtils.swift:706: Fatal error: Benchmark runs require deterministic hashing to be enabled.
21:31:01 
21:31:01 This prevents spurious regressions in hashed collection performance.
21:31:01 You can do this by setting the SWIFT_DETERMINISTIC_HASHING environment
21:31:01 variable to 1.
21:31:01 
21:31:01 If you know what you're doing, you can disable this check by passing
21:31:01 the option '--allow-nondeterministic-hashing to the benchmarking executable.
21:31:01 Current stack trace:
21:31:01 0    libswiftCore.so                    0x00007f69fee47dc0 swift_reportError + 50
21:31:01 1    libswiftCore.so                    0x00007f69feec2310 _swift_stdlib_reportFatalErrorInFile + 112
21:31:01 2    libswiftCore.so                    0x00007f69febcc802 <unavailable> + 1419266
21:31:01 3    libswiftCore.so                    0x00007f69febcc623 <unavailable> + 1418787
21:31:01 4    libswiftCore.so                    0x00007f69febcb170 _assertionFailure(_:_:file:line:flags:) + 414
21:31:01 5    Benchmark_Onone                    0x0000557c6a4c484f <unavailable> + 1194063
21:31:01 6    Benchmark_Onone                    0x0000557c6a6c7007 <unavailable> + 3301383
21:31:01 7    libc.so.6                          0x00007f69fd08b750 __libc_start_main + 240
21:31:01 8    Benchmark_Onone                    0x0000557c6a3d7029 <unavailable> + 221225
21:31:01 ('-- Warning: {}', 'Host toolchain could not locate a compiler to build swift-driver. (Try `--skip-early-swift-driver`)')
```

**Comment by lorentey** [comment]
@swift-ci benchmark

**Comment by lorentey** [comment]
@swift-ci smoke test

**Review by glessard — APPROVED** [review]
Nice find.

**Pull request merged**
