### PR TITLE
pack expansion within a container type fails to type check with Const…

### PR DESCRIPTION
**Pull request by sophiapoirier**
…raintSystem assertion

rdar://104716322

### CODE REVIEW

**Comment by sophiapoirier** [comment]
@swift-ci Please smoke test

**Review by hborla — APPROVED** [review]

**Comment by sophiapoirier** [comment]
my force-push was merely a commit message edit.

**Comment by sophiapoirier** [comment]
@swift-ci Please smoke test

**Comment by sophiapoirier** [comment]
I have reverted the original patch and reimplemented this based on conversation with @slavapestov and @hborla

**Comment by sophiapoirier** [comment]
@swift-ci Please smoke test

**Comment by sophiapoirier** [comment]
@swift-ci Please smoke test

**Comment by sophiapoirier** [comment]
@swift-ci Please smoke test

**Review by slavapestov — APPROVED** [review]

**Comment by slavapestov** [comment]
I hope it's OK if I merge this since it unblocks a PR I have.

**Comment by sophiapoirier** [comment]
> I hope it's OK if I merge this since it unblocks a PR I have.

My only outstanding question/concern is just the one to @rjmccall about my last test change, however if that change is problematic and something more needs to be done to revert it and enable that to pass again, that can certainly happen in a  follow-up PR.

**Pull request merged**
