### PR TITLE
[SourceKit/DocSupport] Add a field to mark functions that are async

### PR DESCRIPTION
**Pull request by bnbarham**
Resolves rdar://72444843

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Review by nathawes — APPROVED** [review]
LGTM!

**Review by Bo886 — APPROVED** [review]
n

**Review by Bo886 — APPROVED** [review]
o

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
@swift ci please test linux platform

**Comment by bnbarham** [comment]
@swift-ci please test linux platform

**Comment by bnbarham** [comment]
Another unrelated failure, 4th time's a charm!

@swift-ci please test macos platform

**Pull request merged**
