### PR TITLE
NFC: More Expr node tail allocations

### PR DESCRIPTION
**Pull request by davezarzycki**

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test and merge

**Comment by davezarzycki** [comment]
@swift-ci please smoke test and merge

**Comment by slavapestov** [comment]
This is cool. Have you observed a memory usage decrease with this and your other changes?

**Comment by davezarzycki** [comment]
Hi @slavapestov – I've been tracking build times, not total memory usage. Unless somebody at Apple has been committing nontrivial performance over the last week or so, my changes have more than halved the build time required for the stdlib on my Linux box. The gains are good but not as dramatic on my MacBook Pro. What if any performance changes have you guys noticed?

PS – What if anything do I need to do to get CI to retest this once the master branch is unbroken?

Here is another go:
@swift-ci please smoke test and merge

**Comment by davezarzycki** [comment]
Trying again with #13553

**Pull request closed without merging**
