### PR TITLE
[Sema] Improve diagnostic for closure return contextual mismatch

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
Improving diagnostic for closure result contextual mismatch.

### CODE REVIEW

**Comment by LucianoPAlmeida** [comment]
Still need to figure out how to add the regression test
```swift
import SwiftUI

struct EqualWitdthHStack : Layout {
  func sizeThatFits(proposal: ProposedViewSize, subviews: Self.Subviews, cache: inout Self.Cache) -> CGSize { fatalError() }
  func placeSubviews(in bounds: CGRect, proposal: ProposedViewSize, subviews: Self.Subviews, cache: inout ()) {}
}

struct MyView : View {
  var body : some View {
    EqualWitdthHStack {
      EmptyView()
    }
  }
}
```

**Comment by AnthonyLatsis** [comment]
Is this tracked by an issue? Maybe we can try and devise a self-contained test case.

**Review by xedin — APPROVED** [review]
LGTM! You can add a test-case to validation-test/Sema/SwiftUI but you'd need to add `-enable-experimental-feature ResultBuilderASTTransform` to the frontend options.

**Comment by xedin** [comment]
There is no issue tracking it because AST transform is still experimental and that was the only way to trigger the opaque opening issue I described in https://github.com/apple/swift/pull/59982#discussion_r922523692

**Comment by xedin** [comment]
Hm, I looked at `ConstraintSystem::openOpaqueType` again and I think with your change it would be broken for multi-statement closures because they used to produce `CTP_ReturnStmt` and now would produce `CTP_ClosureResult` instead... Please add a test-case with opaque result and multi-statement closure to make sure everything is opened correctly even without result builders.

**Comment by LucianoPAlmeida** [comment]
> You can add a test-case to validation-test/Sema/SwiftUI but you'd need to add `-enable-experimental-feature ResultBuilderASTTransform` to the frontend options.

Added, would that work? I was not sure this would run because it involves SwiftUI types available only on macOS 13+ (beta)

> Hm, I looked at `ConstraintSystem::openOpaqueType` again and I think with your change it would be broken for multi-statement closures because they used to produce `CTP_ReturnStmt` and now would produce `CTP_ClosureResult` instead... Please add a test-case with opaque result and multi-statement closure to make sure everything is opened correctly even without result builders.

Added as well! On thing is that having a closure result as an opaque result type e.g. `() -> some P` is not allowed, so the closest to involving an opaque type was as contextual type in generic context.

**Comment by xedin** [comment]
> Yeah, CI is using macOS 11.

That is actually not a problem because CI has beta Xcode installed and the test-case is targeting 13.0 which should be supported (it is not a runtime test). @LucianoPAlmeida You can double-check if the test you added passed in CI.

**Comment by xedin** [comment]
> On thing is that having a closure result as an opaque result type e.g. () -> some P is not allowed, so the closest to involving an opaque type was as contextual type in generic context.

Do we have a test-case for that?

**Comment by LucianoPAlmeida** [comment]
> Do we have a test-case for that?

Looks like we kind of have a test but is commented out 
https://github.com/apple/swift/blob/main/test/type/opaque_return_structural.swift#L22-L23

**Comment by LucianoPAlmeida** [comment]
> @LucianoPAlmeida You can double-check if the test you added passed in CI.

Sure! But even targeting macOS 13 that fails for me locally (I'm on 12.5.1). So even if CI passes that would be a problem for people running locally?

**Comment by xedin** [comment]
Okay, I think that could be fixed separately…

**Comment by LucianoPAlmeida** [comment]
> Only other way is to build a skeleton of Layout that uses callAsFunction that would probably means that you could get rid of SwiftUI completely while at it. :)

Got a repro and just updated! Couldn't quite get a non-swift UI that actually repros the case which is definitely possible but it would take a bit more time and I thought that was enough as it is to repro the scenario. So let me know if is OK =]

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test

**Review by xedin — APPROVED** [review]

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test

**Pull request merged**
