### PR TITLE
[5.5] Update the ScanDependencies test to use %target-cpu

### PR DESCRIPTION
**Pull request by artemcm**
Cherry-pick of https://github.com/apple/swift/pull/38086
---------------------------------------------------

Rationale: [Test-only] We recently cherry-picked a set of changes into `release/5.5` to add support for the `-clang-target` compilation flow in: #38420. There was a followup change that made sure that the tests added in #38420 are generic w.r.t. the host architecture that wasn't brought in as a part of the original cherry-pick. This PR brings in that test-only fix to ensure the test runs on Apple Silicon. 
Risk: None
Original PR: #38086
Issue: rdar://80799746
Code Reviewed By: @nkcsgexi 
Testing Details: Regression test included

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci please smoke test

**Review by nkcsgexi — APPROVED** [review]

**Comment by artemcm** [comment]
@swift-ci please smoke test Linux platform

**Comment by artemcm** [comment]
@swift-ci please nominate

**Review by DougGregor — APPROVED** [review]

**Comment by artemcm** [comment]
@swift-ci please test

**Pull request merged**
