### PR TITLE
[IDE][AST] Handle frameworks with traditional overlays where the underlying module declares cross imports in sourcekit

### PR DESCRIPTION
**Pull request by nathawes**
We weren't handling this case, so their generated interfaces / doc info wouldn't include symbols from the cross-import overlays, and we wouldn't map the underscored cross-import overlay name back to the declaring framework's name in cusor-info, completion results or when indexing.

Resolves rdar://problem/62138551

### CODE REVIEW

**Comment by nathawes** [comment]
@swift-ci please test

**Comment by nathawes** [comment]
Failure seems unrelated:
```
Failing Tests (1):
    Swift(macosx-x86_64) :: AutoDiff/compiler_crashers_fixed/tf1232-autodiff-generated-declaration-mangling.swift
```

**Comment by nathawes** [comment]
@swift-ci please test OS X Platform

**Comment by nathawes** [comment]
@swift-ci please test

**Comment by nathawes** [comment]
@swift-ci please test Windows Platform

**Comment by nathawes** [comment]
@swift-ci please test windows

**Comment by nathawes** [comment]
@swift-ci please test

**Comment by nathawes** [comment]
@swift-ci please test Windows Platform

**Review by akyrtzi — APPROVED** [review]

**Pull request merged**
