### PR TITLE
[IRGen] Pack metadata may be allocated based on type layouts.

### PR DESCRIPTION
**Pull request by nate-chandler**
Previously, `mayRequirePackMetadata` only considered whether a type involved a pack.  That failed to account for the case of outlined value functions that require pack metadata when the type involves a pack in its layout.  Here, `mayRequirePackMetadata` now considers also whether the layout corresponding to a type involves a pack.

rdar://119829826

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by aschwaighofer — APPROVED** [review]
lgtm

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test windows platform

**Comment by nate-chandler** [comment]
@swift-ci please test windows platform

**Pull request merged**
