### PR TITLE
[ConstraintSystem] Detect and diagnose missing 'each' and provide a fix-it

### PR DESCRIPTION
**Pull request by xedin**
Diagnose situations where value pack is referenced without an explicit 'each':

```swift
func compute<each T>(_: repeat each T) {}

func test<each T>(v: repeat each T) {
  repeat compute(v) // should be `repeat compute(each v)`
}
```

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please build toolchain macOS

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
Dropped the change `pack type` -> `type pack`.

**Review by hborla — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Pull request merged**
