### PR TITLE
WIP: utils: Add swiftenvs, which allow the overriding of compiler tools.

### PR DESCRIPTION
**Pull request by erg**
This PR lets you fake a build or instrument an actual build of Swift using ``build-script`` and ``cmake``. My hope is that it will reduce the compilation time to seconds and allow faster iteration on ``cmake`` changes. This is just to test that it can pass CI tests--it needs some documentation as well.

I know there are builtin ninja and cmake tools to do things like this.

### CODE REVIEW

**Comment by erg** [comment]
@swift-ci Please smoke test

**Comment by erg** [comment]
@swift-ci Please smoke test

**Comment by erg** [comment]
@swift-ci Please smoke test

**Comment by erg** [comment]
@swift-ci Please smoke test Linux

**Comment by dabrahams** [comment]
> On Mar 20, 2017, at 1:06 AM, Doug Coleman <notifications@github.com> wrote:
> 
> My hope is that it will reduce the compilation time to seconds

This part sounds like my fantasy but not very likely!  Missing context?

**Comment by erg** [comment]
Right now it's a **fake build** that writes out the command-line arguments to the .o, .dylib files so we can do things like test that asserts are enabled. I got sick of waiting hours for a build to finish just to check that compiler flags are correct.

However, I think it's possible to speed up actual compilation as well...

**Comment by practicalswift** [comment]
Nice! Minor nit - consider addressing the `shellcheck`-warnings for the shell scripts in this PR :-)

**Comment by erg** [comment]
@swift-ci Please test Linux

**Comment by erg** [comment]
@swift-ci Please clean test Linux platform

**Comment by erg** [comment]
@swift-ci Please smoke test

**Comment by erg** [comment]
@practicalswift I fixed all but two shellcheck errors that seem bogus:


```
In utils/swiftenv-script line 115:
    local command; command="${script_args[@]:0:1}"
                           ^-- SC2124: Assigning an array to a string! Assign as array, or use * instead of @ to concatenate.


In utils/swiftenv-script line 125:
                *) subcommand="${command_args[@]:0:1}"; subcommand_args=("${command_args[@]:1}");;
                              ^-- SC2124: Assigning an array to a string! Assign as array, or use * instead of @ to concatenate.
```

**Comment by erg** [comment]
@swift-ci Please smoke test

**Comment by erg** [comment]
@swift-ci Please smoke test

**Comment by erg** [comment]
@swift-ci Please smoke test and merge

**Comment by erg** [comment]
@swift-ci Please smoke test and merge

**Pull request merged**
