### PR TITLE
Mark another thorough String test as requiring an optimized stdlib

### PR DESCRIPTION
**Pull request by jrose-apple**
This one's taking a pretty long time on simulators, only sometimes making it under the timeout limit.

### CODE REVIEW

**Comment by jrose-apple** [comment]
cc @mikeash

**Comment by jrose-apple** [comment]
@milseman ping

**Review by milseman — APPROVED** [review]
LGTM

**Comment by jrose-apple** [comment]
Mike, do you think this one's important to get over to the 5.0 branch too?

**Comment by benlangmuir** [comment]
@jrose-apple Speaking as the current build czar: yes, I think this should get into 5.0.

**Comment by jrose-apple** [comment]
#22043

**Pull request merged**
