### PR TITLE
[stdlib] Demote internal preconditions to invariant checks

### PR DESCRIPTION
**Pull request by milseman**

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please benchmark

**Comment by milseman** [comment]
@swift-ci please benchmark

**Comment by milseman** [comment]
https://ci.swift.org/view/Pull%20Request/job/swift-PR-osx-perf/700/

**Comment by milseman** [comment]
@swift-ci please benchmark

**Comment by milseman** [comment]
Hmm, I had around 10% locally on StringWordBuilder, but not sure why it doesn't repro.

**Comment by milseman** [comment]
@swift-ci please benchmark

**Comment by milseman** [comment]
https://ci.swift.org/view/Pull%20Request/job/swift-PR-osx-perf/711/

**Comment by milseman** [comment]
The optimizer fix that re-enabled constant folding: https://github.com/apple/swift/pull/21192

**Comment by milseman** [comment]
@swift-ci please benchmark

**Comment by atrick** [comment]
I wrote in inlining heuristic fix for this silliness months ago, but that itself has regressions so it's a regression deadlock. Hopefully I'll get back to that very soon though.

**Comment by atrick** [comment]
Feel free to file an SR where we can list benchmarks that have regressed because of inlining noise triggered by removing branches and similar changes along with the old run times. Then we can come back after these improvements/bug fixes land and if they haven't recovered figure out why they're so noisy.

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
