### PR TITLE
AST: Types nested inside a subclass shadow types in the superclass with same name

### PR DESCRIPTION
**Pull request by slavapestov**
The existing rules sometimes behaved this way, because validateDecl()
bails out silently without error on circularity.

Let's make this explicit instead, and get it working in all cases.

Fixes <https://bugs.swift.org/browse/SR-3492>, <rdar://problem/16724197>,
and <rdar://problem/45889192>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Review by DougGregor — APPROVED** [review]
LGTM!

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility Release

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Pull request merged**
