### PR TITLE
Python 2/3 compat: gyb, gyb_sourcekit_support, gyb_syntax_support, li…

### PR DESCRIPTION
**Pull request by compnerd**
…ne-directive

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @gwynne @drodriguez @stephentyrone @drexin @shahmishal @edymtt

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by compnerd** [comment]
This is a rebased change that should hopefully enable `line-directive-tool` and `gyb` to use `python3`.  Note that this change on its own has no impact other than to make the code compatible with both versions, once this is merged, I can switch over the invocations of the tool to use python3 instead of python2.

**Comment by compnerd** [comment]
@drodriguez, @stephentyrone - you might remember this change from the original PR that @gwynne put up quite some time ago. I think that at this point we really do need to start migrating towards python 3.  LLVM has decided that they will be dropping support for Python 2 at the end of the year, with the builds upstream now preferring python 3.  Python 3 is easily available now (though there are some issues to be ironed out - @shahmishal and @JDevlieghere are probably better than I to explain the macOS specific issues).  python.org has EOL'ed Python 2 at the beginning of this year.  I'm hoping that we might be able to migrate the bulk of the day-to-day builds to python 3 in an incremental fashion.

**Comment by compnerd** [comment]
CC: @tachoknight

**Comment by compnerd** [comment]
@swift-ci please test Linux platfom

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci  please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Review by JDevlieghere — APPROVED** [review]

**Comment by eeckstein** [comment]
@compnerd Looks like this broke the python lint test. I saw this on a PR test: https://ci.swift.org/job/swift-PR-osx/21352/console
```
Command Output (stdout):
--
./utils/gyb_syntax_support/__init__.py:4:1: I100 Import statements are in the wrong order. 'from . import Classification' should be before 'from .AvailabilityNodes import AVAILABILITY_NODES'
./utils/gyb_syntax_support/__init__.py:10:1: I100 Import statements are in the wrong order. 'from . import Token' should be before 'from .GenericNodes import GENERIC_NODES'
./utils/gyb_syntax_support/__init__.py:10:1: I202 Additional newline in a group of imports. 'from . import Token' is identified as Application Relative and 'from .GenericNodes import GENERIC_NODES' is identified as Application Relative.
./utils/gyb_syntax_support/__init__.py:12:1: I202 Additional newline in a group of imports. 'from .NodeSerializationCodes import SYNTAX_NODE_SERIALIZATION_CODES, get_serialization_code, verify_syntax_node_serialization_codes' is identified as Application Relative and 'from . import Token' is identified as Application Relative.
./utils/gyb_syntax_support/__init__.py:16:1: I202 Additional newline in a group of imports. 'from .PatternNodes import PATTERN_NODES' is identified as Application Relative and 'from .NodeSerializationCodes import SYNTAX_NODE_SERIALIZATION_CODES, get_serialization_code, verify_syntax_node_serialization_codes' is identified as Application Relative.
./utils/gyb_syntax_support/__init__.py:19:1: I202 Additional newline in a group of imports. 'from .Trivia import TRIVIAS' is identified as Application Relative and 'from .StmtNodes import STMT_NODES' is identified as Application Relative.
```
Though, I didn't see it on other builds.

**Comment by compnerd** [comment]
@eeckstein bleh, didn't seem to show up in the testing.  I'll take a look, thanks for pointing this out!

**Comment by compnerd** [comment]
I wonder if its a python2 vs python3 issue

**Comment by compnerd** [comment]
@tachoknight unfortunately I had already replicated the issue and was working on fixing it.  Thanks though!

#32157 should address the linter warnings

**Comment by compnerd** [comment]
@tachoknight - I think that it might be interesting/useful to see if you can drop any of that patch now.  I suspect that it is possible.  I think that with the other change that I have in flight we are pretty close to defaulting to python3 on the Swift build :-D

**Pull request merged**
