### PR TITLE
[test] rth: Use dynamic linking to properly test backwards-deployment

### PR DESCRIPTION
**Pull request by jrose-apple**
The added test worked before as well; it's to make sure I didn't break the existing behavior.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by lplarson** [comment]
Would you elaborate a bit on how this properly tests resilience over the previous method?

**Comment by jrose-apple** [comment]
The old version of `rth` would *statically* link a "new" client with an "old" library, but that can lead to missing symbol errors if something was added to the "new" library. The client should be able to weakly reference any new symbols, but `ld` still checks that they're present at link-time.

Swift doesn't actually *try* to weak-link anything that wasn't imported from Clang, so I don't have a test case yet. But it's one of the things I'm working on that I took over from Slava, rdar://problem/29888071.

Anyway, the purpose of resilience is to allow changing out a library *after* a client has been built, and that includes linking. This is closer to what actually happens when backwards-deploying an app on an older OS, or updating an OS out from under existing apps.

**Comment by jrose-apple** [comment]
"It wasn't wrong but it could be more right."

**Comment by lplarson** [comment]
Thanks! LGTM.

**Review by lplarson — APPROVED** [review]

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test macOS

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
I cannot catch a break with this rewrite. Guess I need to stop cutting corners. :-/

**Comment by jrose-apple** [comment]
I finally got it working on all platforms. A bunch of things have changed if you want to take a look again, @lplarson.

@swift-ci Please test

**Comment by lplarson** [comment]
LGTM.

**Comment by jrose-apple** [comment]
Dang it, Linux.

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Pull request merged**
