### PR TITLE
[opt] promote stack alloc_ref to object

### PR DESCRIPTION
**Pull request by zoecarver**
Based on #30736. This patch updates `StackPromotion` to promote `alloc_ref`s on the stack to `object` instructions. Given that there's currently no support for `object` instructions in the optimizer, this pass shouldn't have many (if any) performance improvements. It just lays the groundwork for future performance improvements. 

In the future, the promotion could probably be more aggressive but, as of now, it will only promote stack `alloc_ref`s so there shouldn't be any regression.

### CODE REVIEW

**Comment by zoecarver** [comment]
@swift-ci please benchmark

**Comment by zoecarver** [comment]
As said in the summary, I don't expect any performance improvements. That's just to check for regressions (which shouldn't be possible because stack `alloc_ref`s and `object`s both allocate objects in the same way).

**Comment by zoecarver** [comment]
@swift-ci please benchmark

**Comment by eeckstein** [comment]
See my comment in https://github.com/apple/swift/pull/30736

**Comment by zoecarver** [comment]
I'm closing this given the discussion in #30787 and because #30810 had significantly better performance improvements.

**Pull request closed without merging**
