### PR TITLE
Improve multi-file enum diagnostics

### PR DESCRIPTION
**Pull request by CodaFi**
Given a setup where one file declares an enum and the other switches on it, decomposition fails because it can't get any useful interface types out of the AST.  Version 1 of this patch adds a short hack that just throws in the enum case constructor heads into the space and reports that back to the user because it's better than nothing, but there's got to be a better way to do this.

@slavapestov?

### CODE REVIEW

**Comment by slavapestov** [comment]
Why are there no interface types in the AST? The enum should be validated before it is referenced from inside any function bodies

**Comment by CodaFi** [comment]
Here's what I'm getting back from this setup:

```swift
// Test File 1
func f(_ x : Foo) {
  switch x {
    
  }
}

// Test File 2
enum Foo {
  case bar(Bool)
  case baz(Bool)
}

```

```text
(lldb) p eed->dump()
(enum_element_decl "bar")
(lldb) p E->dump()
(enum_decl "Foo" interface type='Foo.Type' access=internal @_fixed_layout
  (enum_case_decl
    (enum_element_decl "bar"))
  (enum_element_decl "bar")
  (enum_case_decl
    (enum_element_decl "baz"))
  (enum_element_decl "baz"))
(lldb) 
```

**Comment by CodaFi** [comment]
Ah, wait: This is an ordering problem.  I need everything in the other file to be type checked before I ask for the interface type of the enum decl.

**Comment by slavapestov** [comment]
Well, you *don't* want to type check everything in the other file -- that would be a performance problem. However, since the declaration 'Foo' is referenced here, probably all of the enum cases contained therein should also be validated. How was this working before?

**Comment by slavapestov** [comment]
You could try just calling TypeChecker::validateDecl() on the enum case decl before getting its type.

**Comment by CodaFi** [comment]
That works, but it means I have to thread an instance of the typechecker through this whole thing, and probably validate a lot of enum element declarations that will already go through validation.  Is there some later phase of semantic analysis I can stick this in to get around that?

**Comment by slavapestov** [comment]
Well, validating a decl more than once is a no-op. We validate all case members of referenced enums later anyway since we need that to compute layouts in IRGen.

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
Yep, that got it.

@swift-ci please test macOS platform

**Comment by CodaFi** [comment]
Yep, that got it.

@swift-ci please test macOS platform

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
⛵️

**Comment by nkcsgexi** [comment]
@CodaFi are you planning to merge this to swift-4.0-branch?

**Comment by CodaFi** [comment]
Along with your last pull request.  Just gonna take it all in that one place if that's OK.

**Comment by nkcsgexi** [comment]
That will be a good idea! Thank you!

**Pull request merged**
