### PR TITLE
🍒 [Concurrency] prevent races in task cancellation

### PR DESCRIPTION
**Pull request by ktoso**
**Explanation:** The way we triggered cancellation handlers on an already cancelled task was racy and may cause a handler not being triggered and potentially leaving resources never cleaned up. The new impl moves the checking in the right spot so we always trigger properly.
Reviewer: @rjmccall (reviewed original PR) @DougGregor 
Radar/SR Issue: rdar://78177513
Risk: Small.
Testing: PR testing and CI on main.
Original PR: #38404

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
Note to self, pull in https://github.com/apple/swift/pull/38469 if it proves indeed unbreaking the one flaky test

**Comment by ktoso** [comment]
@swift-ci nominate

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
