### PR TITLE
Workaround the current actor runtime's unwillingness to deal with priorities properly

### PR DESCRIPTION
**Pull request by aschwaighofer**
rdar://79378627

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Review by DougGregor — APPROVED** [review]
Thank you!

**Comment by aschwaighofer** [comment]
@swift-ci test linux

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Pull request merged**
