### PR TITLE
`Dynamicism` is not a word

### PR DESCRIPTION
**Pull request by Goles**
Switched it for dynamism, which I guess was the original intent.

### CODE REVIEW

**Comment by ekimia** [comment]
+1

**Comment by MosheBerman** [comment]
screen shot 2015-12-03 at 2 02 44 pm

**Comment by phroggyy** [comment]
@MosheBerman, it is indeed a word. However, the comments in the code imply a reduction of dynamicism. Dynamicisim is a hyopthesis, and hence cannot be concretely reduced, which is why we can probably assume dynamism was implied (as in making it less dynamic).

**Comment by sdegutis** [comment]
Bikeshedding.

**Comment by Goles** [comment]
@MosheBerman interesting, I'm opening a PR in the Apple dictionary because it's not there...?

Anyway, I think dynamism is the correct way to go here ;)

**Comment by codykrainock** [comment]
:+1:

**Comment by ashfurrow** [comment]
I like Dynammicism ¯\\_(ツ)_/¯

**Comment by Goles** [comment]
@MosheBerman Actually, I dug a bit deeper and it's not a word according to several English dictionaries (can't really search in Oxford's because one has to be a member...).

As @ashfurrow said... ¯\(ツ)/¯

**Comment by JasonGallagher** [comment]
Dynamicigery

**Comment by Bernard-Bernie-Sanders** [comment]
As a linguist, I agree to this in its entirety. The word is invalid (not able to exist) but clearly not intended or in actual (proper) use. Outsourcing, ey?

**Comment by MosheBerman** [comment]
@Goles I don't see it in my my paper dictionary. (Merriam Webster's Collegiate Dictionary, Eleventh edition.) 

Guess I'll join the party:   ¯\(ツ)/¯

**Comment by Bernard-Bernie-Sanders** [comment]
there is a not missing in my comment: "The word is _not_ invalid but clearly not intended or in actual (proper) use."

**Comment by lattner** [comment]
d9e9fea changed the wording in this document to avoid the dynami-schism controversy :-)

**Comment by MosheBerman** [comment]
Lol, @lattner!

**Comment by phillfarrugia** [comment]
https://teespring.com/dynamicism

**Comment by Goles** [comment]
Neat! I guess I can sleep tonight.

Thanks @lattner!

**Pull request closed without merging**
