### PR TITLE
Disable large types irgen pass

### PR DESCRIPTION
**Pull request by shajrawi**
radar rdar://problem/32064645

Disable large types irgen pass (for now)

Swift 4.0 PR https://github.com/apple/swift/pull/9447

### CODE REVIEW

**Comment by shajrawi** [comment]
@eeckstein Can you please review?

**Comment by shajrawi** [comment]
@swift-ci Please smoke test

**Comment by eeckstein** [comment]
LGTM!

**Comment by slavapestov** [comment]
Will it be re-enabled again in 4.0 branch? A lot of users are looking forward to this.

**Comment by shajrawi** [comment]
No.

**Comment by jckarter** [comment]
Can we keep a flag around so people can try it out, and we can still get bug reports and feedback on it? That's what we did with bridging pch.

**Comment by NachoSoto** [comment]
😰 Wh.... Why? What's `rdar://problem/32064645`? What's the point of having a transparent process if you guys keep linking private bugs...? 😕

**Comment by shajrawi** [comment]
@jckarter I plan to add such a flag in a later commit on master, but, since this is an ABI change anyone whom wants to test their code with that flag enabled will need to rebuild the entire toolchain with it. else they'd crash when calling the standard library..etc

**Comment by shajrawi** [comment]
@swift-ci Please smoke test

**Comment by shajrawi** [comment]
@swift-ci Please smoke test

**Comment by jckarter** [comment]
@NachoSoto Looks like there were some bad interactions between this transform and the rest of the optimizer.

**Comment by NachoSoto** [comment]
Thanks @jckarter! What's the plan moving forward then? I've been waiting for this change for several years, so I was pretty excited.

**Comment by shajrawi** [comment]
@NachoSoto we'll get back to this transformation at some point, making sure it is truly great, but it is not going to be re-enabled on the 4.0 branch.

**Comment by NachoSoto** [comment]
"At some point"?

**Comment by NachoSoto** [comment]
🤷‍♂️

**Pull request merged**
