### PR TITLE
Re-apply "SwiftSyntax: Teach SwiftSyntax to use SourceKitd to serialize syntax trees. (#14424)"

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by nkcsgexi** [comment]
@swift-ci please test source compatibility

**Comment by nkcsgexi** [comment]
@swift-ci please test source compatibility

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Comment by nkcsgexi** [comment]
@swift-ci please test source compatibility

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please test source compatibility

**Comment by nkcsgexi** [comment]
@swift-ci please test source compatibility

**Comment by nkcsgexi** [comment]
@swift-ci Please clean test

**Comment by nkcsgexi** [comment]
@swift-ci please test source compatibility

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please test source compatibility

**Comment by nkcsgexi** [comment]
@swift-ci please test source compatibility

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please test source compatibility

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Comment by nkcsgexi** [comment]
@swift-ci Please test OS X platform

**Comment by nkcsgexi** [comment]
All tests passed. 🚢

**Comment by DougGregor** [comment]
Testing for the source compatibility suite is broken with

```
/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite/swift/tools/SwiftSourceKitClient/SourceKitdClient.swift:15:8: error: no such module 'sourcekitd'
import sourcekitd
       ^
```

I think it might be a missing dependency somewhere.

**Comment by DougGregor** [comment]
@nkcsgexi , I had to revert this and https://github.com/apple/swift/pull/14497 in https://github.com/apple/swift/pull/14499, because the source compatibility suite testing was broken with the error above. Sorry :(

**Comment by nkcsgexi** [comment]
@DougGregor thank you for reverting! I remember I've tested the source compatibility suite and the tests passed : ( 
I'll take a look today.

**Pull request merged**
