### PR TITLE
[Concurrency] Build C only libdispatch before Swift on non-Darwin pla…

### PR DESCRIPTION
**Pull request by drexin**
…tforms

_Concurrency depends on libdispatch and since it is not available by
default on non-Darwin platforms, it needs to be built before the Swift
project, so that the dependency can be resolved.

### CODE REVIEW

**Comment by drexin** [comment]
@swift-ci test

**Comment by drexin** [comment]
Failing some BuildSystem tests on Linux. Probably just need to be adjusted for the new dependency.

**Review by ktoso — APPROVED** [review]

**Comment by drexin** [comment]
@swift-ci test

**Comment by drexin** [comment]
@swift-ci test

**Pull request merged**
