### PR TITLE
Create fewer generic signature builders

### PR DESCRIPTION
**Pull request by DougGregor**
The `GenericSignatureBuilder` is slow, so instead of making it fast... build fewer of them!

* Don't create a generic signature builder for non-generic members of generic types; re-use the parent's generic signature instead
* Don't create a generic signature builder for extensions of generic types and protocols that don't add requirements; re-use the nominal type's generic signature instead
* When we've created a generic signature builder and formed a generic signature from it, re-use that generic signature builder as the canonical generic signature builder

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
In my local testing, this cuts the time to type check the standard library down by a third.

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please test compiler performance

**Comment by DougGregor** [comment]
@swift-ci please test compiler performance

**Comment by DougGregor** [comment]
@swift-ci please test compiler performance

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@swift-ci please test compiler performance

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
Ahhh, found the issue. It wasn't triggering on my branch.

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@swift-ci please smoke test Linux

**Comment by DougGregor** [comment]
@swift-ci please smoke test Linux

**Comment by DougGregor** [comment]
@swift-ci please smoke test Linux

**Comment by shajrawi** [comment]
Doug, I think this might be causing the parsing test failures on the bots?

**Comment by DougGregor** [comment]
I'm pulling in the pieces of this that don't break the parsing tests, separately. https://github.com/apple/swift/pull/12091 has the improvements that avoid creating GSBs when there's already an obvious generic signature to use.

**Pull request merged**
