### PR TITLE
[LifetimeCompletion] Flag ends synthesized in dead-ends.

### PR DESCRIPTION
**Pull request by nate-chandler**
Flag lifetime-ending instructions created by lifetime completion which are placed within a dead-end block.  Then, during OSSA lowering, eliminate these instructions.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
```
### Performance (arm64): -O

**Regression**                             | **OLD**  | **NEW**  | **DELTA** | **RATIO**
:---                                       | ---:     | ---:     | ---:   | ---:
ArrayAppendToGeneric                       | 147.692  | 179.167  | +21.3% | **0.82x (?)**
Data.init.Sequence.809B.Count.RE           | 11.458   | 12.636   | +10.3% | **0.91x (?)**
&nbsp; | | | |
**Improvement**                            | **OLD**  | **NEW**  | **DELTA** | **RATIO**
StringWithCString2                         | 0.001    | 0.0      | -50.0% | **2.00x (?)**
UTF8Decode_InitDecoding_ascii              | 95.913   | 83.889   | -12.5% | **1.14x**
UTF8Decode_InitFromBytes_ascii             | 130.765  | 114.45   | -12.5% | **1.14x (?)**
UTF8Decode_InitFromCustom_contiguous_ascii | 94.042   | 82.542   | -12.2% | **1.14x (?)**
UTF8Decode_InitDecoding_ascii_as_ascii     | 102.727  | 90.792   | -11.6% | **1.13x**
UTF8Decode_InitFromData_ascii_as_ascii     | 106.381  | 94.417   | -11.2% | **1.13x (?)**
UTF8Decode_InitFromBytes_ascii_as_ascii    | 132.471  | 118.737  | -10.4% | **1.12x**
CxxStringConversion.cxx.to.swift           | 63.667   | 57.273   | -10.0% | **1.11x (?)**
UTF8Decode_InitFromData_ascii              | 101.3    | 91.56    | -9.6%  | **1.11x (?)**
CStringLongAscii                           | 89.333   | 81.577   | -8.7%  | **1.10x (?)**
ObjectiveCBridgeToNSSet                    | 5109.524 | 4711.364 | -7.8%  | **1.08x (?)**

### Code size: -O


### Performance (arm64): -Osize

**Regression**                                      | **OLD**  | **NEW**  | **DELTA** | **RATIO**
:---                                                | ---:     | ---:     | ---:    | ---:
StringWithCString2                                  | 0.0      | 0.001    | +100.0% | **0.50x (?)**
ArrayAppendGenericStructs                           | 983.571  | 1144.167 | +16.3%  | **0.86x (?)**
StrComplexWalk                                      | 1949.167 | 2146.364 | +10.1%  | **0.91x**
DataAppendBytesMedium                               | 1615.652 | 1740.909 | +7.8%   | **0.93x (?)**
&nbsp; | | | |
**Improvement**                                     | **OLD**  | **NEW**  | **DELTA** | **RATIO**
CxxStringConversion.cxx.to.swift                    | 74.444   | 59.444   | -20.1%  | **1.25x (?)**
UTF8Decode_InitDecoding_ascii                       | 99.478   | 87.654   | -11.9%  | **1.13x**
UTF8Decode_InitFromCustom_contiguous_ascii          | 97.286   | 87.583   | -10.0%  | **1.11x (?)**
UTF8Decode_InitDecoding_ascii_as_ascii              | 102.524  | 92.583   | -9.7%   | **1.11x**
UTF8Decode_InitFromBytes_ascii                      | 127.188  | 115.35   | -9.3%   | **1.10x (?)**
UTF8Decode_InitFromData_ascii_as_ascii              | 104.727  | 95.083   | -9.2%   | **1.10x**
UTF8Decode_InitFromData_ascii                       | 101.85   | 92.667   | -9.0%   | **1.10x (?)**
UTF8Decode_InitFromBytes_ascii_as_ascii             | 129.5    | 119.211  | -7.9%   | **1.09x**
UTF8Decode_InitFromCustom_contiguous_ascii_as_ascii | 143.769  | 132.429  | -7.9%   | **1.09x (?)**
CStringLongAscii                                    | 88.88    | 82.444   | -7.2%   | **1.08x (?)**

### Code size: -Osize


### Performance (arm64): -Onone

**Regression**                             | **OLD**   | **NEW**   | **DELTA** | **RATIO**
:---                                       | ---:      | ---:      | ---:   | ---:
CharacterRecognizer.mixed                  | 12.239    | 14.333    | +17.1% | **0.85x**
&nbsp; | | | |
**Improvement**                            | **OLD**   | **NEW**   | **DELTA** | **RATIO**
ArrayAppendGenericStructs                  | 1214.0    | 742.857   | -38.8% | **1.63x (?)**
CxxStringConversion.cxx.to.swift           | 74.875    | 54.917    | -26.7% | **1.36x (?)**
UTF8Decode_InitFromData_ascii              | 104.75    | 92.588    | -11.6% | **1.13x (?)**
UTF8Decode_InitFromData_ascii_as_ascii     | 106.333   | 94.458    | -11.2% | **1.13x**
UTF8Decode_InitDecoding_ascii_as_ascii     | 107.333   | 96.0      | -10.6% | **1.12x**
UTF8Decode_InitFromBytes_ascii             | 131.824   | 118.053   | -10.4% | **1.12x**
UTF8Decode_InitDecoding_ascii              | 112.053   | 100.545   | -10.3% | **1.11x**
UTF8Decode_InitFromBytes_ascii_as_ascii    | 133.176   | 120.053   | -9.9%  | **1.11x**
DataAppendArray                            | 1764.865  | 1597.183  | -9.5%  | **1.10x (?)**
UTF8Decode_InitFromCustom_contiguous_ascii | 117.235   | 106.55    | -9.1%  | **1.10x (?)**
AnyHashableWithAClass                      | 36392.857 | 33615.385 | -7.6%  | **1.08x (?)**

### Code size: -swiftlibs
```

**Comment by atrick** [comment]
For anyone else reviewing, particularly @eeckstein, these flags aren't strictly necessary. Another pass should run late in the pipeline that removes useless instructions on dead end paths. For the narrow purpose of extending OSSA lifetimes, we could use `extend_lifetime`, which is always deleted after OSSA.

But, the flags still seem like a good idea. They are safe. If an optimization drops the flags, it is harmless. The flags cache useful information from SILGen. They handle more than just the lifetime-extending instructions like `destroy_value` and `end_borrow`. It's good to strip useless instructions as soon as possible. Most importantly, we don't need to teach all downstream OSSA passes to recognize a new `extend_lifetime` instruction when looking for all the lifetime ends.

**Comment by nate-chandler** [comment]
I already wrote the pass to delete these instructions later on.  I plan to check it in later if we still have regressions that need to be sorted out.

I believe the flags actually are necessary in some cases.  If we insert these formal lifetime ends on the availability boundary somewhere before a block which terminates in an unreachable, we wouldn't reasonably be able to determine that the lifetime end was eligible for removal later on.

For example, starting with 
```
start:
  %x = ...
  cond_br %c, left, right
left:
  destroy_value %x
  cond_br %c2, exit, die1
die1:
  br die2
die2:
  apply
  unreachable
right:
  br die3
br die2
```
lifetime completion will insert a destroy on the availability boundary
```
start:
  %x = ...
  cond_br %c, left, right
left:
  destroy_value %x
  cond_br %c2, exit, die1
die1:
  br the_end
the_end:
  apply
  unreachable
right:
  br die3
die3:
  destroy_value %x // <--- this is inserted
  br the_end
```
There would be no good way to determine that the inserted destroy_value could be removed.

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by atrick** [comment]
If we always emitted `extend_lifetime` in dead end blocks, then we wouldn't need flag. But we don't want to fix all the passes to recognize that instruction.

**Review by atrick — APPROVED** [review]
LGTM

**Pull request merged**
