### PR TITLE
[Distributed] Enable no-longer-experimental distributed by default

### PR DESCRIPTION
**Pull request by ktoso**
Remove experimental flag, SE-0336 was accepted.

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please smoke test and merge

**Comment by ktoso** [comment]
@swift-ci please smoke test and merge

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
@swift-ci please clean test

**Comment by ktoso** [comment]
@swift-ci please smoke test Linux

**Comment by ktoso** [comment]
Disabled the ELF test for now just to be able to merge the flag removal if we decide we need to do so tomorrow.

**Comment by ktoso** [comment]
@swift-ci please clean test

**Comment by xedin** [comment]
@swift-ci please clean test Linux platform

**Comment by xedin** [comment]
@swift-ci please clean test macOS platform

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Comment by xedin** [comment]
@shahmishal Looks like there are infra issues on Linux:

```
Cannot contact i-0d9e64375f4a6962e: hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@3ad8a28b:i-0d9e64375f4a6962e": Remote call on i-0d9e64375f4a6962e failed. The channel is closing down or has closed down
Could not connect to i-0d9e64375f4a6962e to send interrupt signal to process
```

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Pull request merged**
