### PR TITLE
Bump Swift Compiler version to 4.0.1

### PR DESCRIPTION
**Pull request by zisko**
Bumps the Swift Compiler version to 4.0.1

rdar://34471818

### CODE REVIEW

**Comment by zisko** [comment]
@swift-ci Please clean test and merge

**Comment by shahmishal** [comment]
@swift-ci Please clean test and merge

**Review by shahmishal — APPROVED** [review]
LGTM!

**Comment by zisko** [comment]
@swift-ci Please clean smoke test and merge

**Comment by najacque** [comment]
@swift-ci Please clean smoke test and merge

**Comment by shahmishal** [comment]
```
Test Result (2 failures / +2)
Swift(macosx-x86_64).Serialization/Recovery.crash-recovery.swift
Swift(macosx-x86_64).Serialization/Recovery.types-4-to-3.swift
```

**Comment by zisko** [comment]
@swift-ci Please clean smoke test and merge

**Pull request merged**
