### PR TITLE
Rdar 25802399 change may to must

### PR DESCRIPTION
**Pull request by graydon**
Minor diagnostic fix for clarity: user was unsure whether "foo may not be bar" meant that the state of affairs was indeterminate (may be? may not be?) or whether the compiler was saying that foo is prohibited from being bar.

(with helpful link to RFC 2119)

rdar://25802399

### CODE REVIEW

**Comment by graydon** [comment]
@swift-ci please test

**Review by slavapestov — APPROVED** [review]

**Comment by graydon** [comment]
@swift-ci please test and merge

**Comment by graydon** [comment]
@swift-ci please test and merge

**Comment by graydon** [comment]
@swift-ci please test and merge

**Comment by graydon** [comment]
@swift-ci please test and merge

**Pull request merged**
