### PR TITLE
[syntax-coloring] Rework the syntax map to use offset + length and simplify the delta logic

### PR DESCRIPTION
**Pull request by nathawes**
This patch changes the syntax map data structure to be offset based rather than line/col based in order to avoid calling `getLineAndColumn` for the start and end offset of every token. This removes the 30% of time spent in `getLineAndColumn` during this request for large files (rdar://problem/28965123).

The logic for returning the affected range and the token ranges to highlight following an edit also made several assumptions that no longer hold. This patch changes it to compare the syntax maps from before and after the edit, find the first mismtaching tokens from the start and end of the syntax maps
and return the tokens in that range (adjusted to line boundaries). This fixes syntax highlighting issues with interpolated multi-line strings (rdar://problem/32148117) and block comments.

With the above changes the per-keystroke time spent for syntax highlighting (with sematic info disabled) drops from ~80ms to just under 50ms for a 12KLOC file.

This patch also changes unterminated/invalid regular and multi-line strings to now be highlighted as strings.

Resolves rdar://problem/28965123 and rdar://problem/32148117.

### CODE REVIEW

**Comment by nathawes** [comment]
@swift-ci Please smoke test

**Review by bitjammer — APPROVED** [review]
Code looks good. I would suggest you add doc comments for the functions you've touched and also add some developer comments for some of the more opaque stuff like comparison of ranges  and offsets, why you're checking them, etc.

**Comment by nathawes** [comment]
@swift-ci Please smoke test

**Comment by nathawes** [comment]
@swift-ci Please smoke test

**Pull request merged**
