### PR TITLE
Build Synchronization on Windows installer

### PR DESCRIPTION
**Pull request by Azoy**

### CODE REVIEW

**Comment by Azoy** [comment]
https://github.com/apple/swift-installer-scripts/pull/272/files
@swift-ci please build toolchain Windows platform

**Review by compnerd — APPROVED** [review]

**Comment by Azoy** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@Azoy just checking, is this something that should be backported to 5.10?

**Comment by Azoy** [comment]
No, I don't think Atomics will land in Swift 5.10

**Pull request merged**
