### PR TITLE
Basic: make the member specifiers match the declaration

### PR DESCRIPTION
**Pull request by compnerd**
Visual Studio does not like the member being declared as `const` and then used
as `constexpr`.

  ```
  include\swift\Basic\ImmutablePointerSet.h(352): error C2370: 'swift::ImmutablePointerSetFactory<T>::AllocAlignment': redefinition; different storage class
  include\swift\Basic\ImmutablePointerSet.h(185): note: see declaration of 'swift::ImmutablePointerSetFactory<T>::AllocAlignment'
  include\swift\Basic\ImmutablePointerSet.h(352): error C2059: syntax error: '='
  include\swift\Basic\ImmutablePointerSet.h(353): error C2059: syntax error: 'alignof'
  ```

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by jrose-apple** [comment]
`const` and `constexpr` don't imply each other anymore, so you probably want both.

**Comment by compnerd** [comment]
Made it `constexpr const`.  This required moving the definition back inline.

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@jrose-apple , hmm, seems that it doesn't.  Sorry, not following what you mean by a separate template here.  Template what over what?

**Comment by jrose-apple** [comment]
Like, move `AllocAlignment` out into a separate struct, which can be defined after ImmutablePointerSet is complete.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@jrose-apple, this seems to work for Visual Studio for me.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by jrose-apple** [comment]
The nested template is a little redundant but I guess it doesn't hurt anything in practice.

@swift-ci Please smoke test macOS

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test macOS platform

**Comment by compnerd** [comment]
Seems that VS no longer needs this?  If it builds, I'm happy without this.

**Pull request closed without merging**
