### PR TITLE
IRGen: Use argmemonly for a couple of readonly runtime functions

### PR DESCRIPTION
**Pull request by aschwaighofer**

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
CC @jckarter

**Review by aschwaighofer — COMMENTED** [review]
This is not correct. ArgMemOnly can only be use by functions that are accessing memory based on the pointer arguments.

**Comment by aschwaighofer** [comment]
One of this functions must do more than just read from the pointer array to get the metatype arguments ... I am seeing failures in optimized mode.

**Comment by aschwaighofer** [comment]
Or some code that initializes the arguments is inlined in llvm ir then you could have

```
Type *args[5];
pointer->field = // inlined initialization
arg[1] = pointer
argmemonly(args)
```

It would be legal for the optimizer to reorder to:
```
Type *args[5];
arg[1] = pointer
argmemonly(args)
pointer->field = // inlined initialization
```

**Comment by jckarter** [comment]
Hm, that shouldn't happen, but it's probably not worth spending much time on right now.

**Comment by aschwaighofer** [comment]
I filed https://bugs.swift.org/browse/SR-6889

**Pull request closed without merging**
