### PR TITLE
[ConstraintSystem][NFC] Make test file named `argument_matching.swift`

### PR DESCRIPTION
**Pull request by omochi**
- Make test file named `argument_matching.swift` by renaming from `keyword_argument.swift`.
  New filename indicates that is contains test cases for matching of not only labeled argument but also unlabeled.

- Move test cases about argument matching from `diagnostics.swift` to `argument_matching.swift` which has more specific interest.

This patch only changes place of test cases.
It doesn't have changes about compiler.

I planned this patch in response to comment here.
https://github.com/apple/swift/pull/31934

@xedin @LucianoPAlmeida Please review this

### CODE REVIEW

**Comment by LucianoPAlmeida** [comment]
LGTM! :)

**Comment by omochi** [comment]
@swift-ci please smoke test

**Review by xedin — APPROVED** [review]
Thank you, @omochi!

**Comment by omochi** [comment]
@swift-ci Please smoke test Windows

**Comment by omochi** [comment]
A last one error on windows isn’t related. I will merge.

**Pull request merged**
