### PR TITLE
[CSRanking] Fix solution filtering not to erase everything when set i…

### PR DESCRIPTION
**Pull request by xedin**
…s completely ambiguous

Since constraint solver has been improved to diagnose more problems
via "fixes", sometimes applying fixes might lead to producing solutions
which are completely ambiguous when compared to each other, and/or are
incomparable, which leads to `findBestSolutions` erasing all of them
while trying to compute best "partial" solution, which is incorrect.

Resolves: [SR-8396](https://bugs.swift.org/browse/SR-8396)
Resolves: rdar://problem/42678836

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please smoke test

**Review by rudkx — APPROVED** [review]
Seems like the right thing to do.

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Pull request merged**
