### PR TITLE
[ShrinkBorrowScope] Adopt iterative dataflow.

### PR DESCRIPTION
**Pull request by nate-chandler**
Adopt IterativeBackwardReachability and VisitBarrierAccessScopes.  Enables hoisting borrow scopes over loops and avoiding hoisting borrow scopes into unrelated access scopes, respectively.

rdar://93186505
rdar://93060369

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please smoke test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please smoke test

**Review by atrick — COMMENTED** [review]
LGTM

**Pull request merged**
