### PR TITLE
Run lit tests with -v in standalone/freestanding testing presets

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by compnerd — APPROVED** [review]
This is reasonable, I just wonder if there is any increase in time.

**Comment by kubamracek** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by kubamracek** [comment]
> This is reasonable, I just wonder if there is any increase in time.

Running the PR testing now. I doubt there will be any visible time increase, because -v basically only asks lit to print more stuff when a test fails, but lit already collects the outputs of failed tests (into the test-result.xml file).

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by kubamracek** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Pull request merged**
