### PR TITLE
[python] Bring code base in line with PEP-8 again

### PR DESCRIPTION
**Pull request by practicalswift**
Bring code base in line with PEP-8 again.

### CODE REVIEW

**Comment by practicalswift** [comment]
@swift-ci please python lint

**Comment by practicalswift** [comment]
@swift-ci please test

**Comment by practicalswift** [comment]
@swift-ci please smoke test

**Comment by gottesmm** [comment]
Hmmm... we should probably add a lit test that does pep8 testing.

**Comment by gottesmm** [comment]
If flake8 is available.

**Pull request merged**
