### PR TITLE
Fixup a test

### PR DESCRIPTION
**Pull request by CodaFi**
Validation order changed.

Get the bots passing again.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by theblixguy** [comment]
Thank you! (I was confused when the CI failed on one of my PRs).

**Review by beccadax — COMMENTED** [review]
It might be worth merging anyway just to fix the build, but is this diagnostic actually accurate?

**Comment by CodaFi** [comment]
The diagnostic is a catch-all introduced to cut off a crasher.  We should be able to do much much better soon.

**Review by beccadax — APPROVED** [review]

**Comment by CodaFi** [comment]
⛵️

**Pull request merged**
