### PR TITLE
[ClangImporter] Break circularity when importing macros

### PR DESCRIPTION
**Pull request by jrose-apple**
Rather than being smart about this, just record an import failure when we start importing a particular macro and update it at the end. Also add a PrettyStackTrace to make this a little easier to track down in the future.

The old logic for importing macros that just aliased other macros managed to handle this in a clever way, but that was never tested for the newer logic that evaluates expressions (#6678). Macro importing in general probably deserves some cleanup, but meanwhile we should make sure not to crash!

rdar://problem/34986930

### CODE REVIEW

**Comment by jrose-apple** [comment]
cc @IngmarStein (if you're still interested) and @karwa.

@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by rjmccall** [comment]
I don't know why you want my review on this; I'm not particularly an expert in either macros or how we import them in Swift.  As a general approach for breaking circularity problems, the patch seems fine.

**Comment by jrose-apple** [comment]
Doug's been too busy to get to it, and there aren't that many others who regularly work on the importer. That's probably worth improving in the future. Meanwhile, the second pair of eyes is appreciated, so thank you!

**Pull request merged**
