### PR TITLE
Fix @available(macCatalyst N, iOS N+M) bug

### PR DESCRIPTION
**Pull request by beccadax**
Previously, availability checking computed a declaration’s availability as the intersection of all `@available` attributes with active platforms. This meant that Swift would not allow you to use an API that was available earlier in a child platform than in its parent until it was also available in the parent platform. That was incorrect.

This PR corrects availability checking to find the most specific `@available` attribute with an `introduced:` version and use that instead.

Fixes rdar://60892534, rdar://61813677.

### CODE REVIEW

**Comment by brentdax** [comment]
This was reviewed internally to Apple by @devincoughlin. It has also been tested there, since Swift CI's ability to test Mac Catalyst changes is currently limited, so I'll stick to a smoke test here.

**Comment by brentdax** [comment]
@swift-ci please smoke test and merge

**Comment by brentdax** [comment]
@swift-ci please test

**Comment by brentdax** [comment]
@devincoughlin Requesting a re-review because I discovered a bug in the original implementation.

**Review by DougGregor — APPROVED** [review]
This looks like the right semantics, thanks!

**Pull request merged**
