### PR TITLE
[6.0] [SE-0365] Fix issue where implicit self was unexpectedly disallowed in nested closures

### PR DESCRIPTION
**Pull request by calda**
- Issues: 
   - https://github.com/apple/swift/issues/70089
   - https://github.com/apple/swift/issues/69911
 - Original PR:
   - https://github.com/apple/swift/pull/70575

### Explanation

This PR fixes issues related to [SE-0365](https://github.com/apple/swift-evolution/blob/main/proposals/0365-implicit-self-weak-capture.md) and [SE-0269](https://github.com/apple/swift-evolution/blob/main/proposals/0269-implicit-self-explicit-capture.md) where the following code would unexpectedly fail to compile:

```swift
class Test {
  var x = 0

  func test() {
    withEscapingClosure { [weak self] in
      guard let self else { return }
            
      withEscapingClosure { [self] in
        x += 1 // unexpected error in 5.10: reference to property 'x' in closure requires explicit use of 'self' to make capture semantics explicit
      }

      withNonEscapingClosure {
        x += 1 // unexpected error in 5.10: reference to property 'x' in closure requires explicit use of 'self' to make capture semantics explicit
      }
    }
  }
}

func withEscapingClosure(_: @escaping () -> Void) {}
func withNonEscapingClosure(_: () -> Void) {}
```

### Scope

This change fixes several bugs related to [SE-0365](https://github.com/apple/swift-evolution/blob/main/proposals/0365-implicit-self-weak-capture.md) and [SE-0269](https://github.com/apple/swift-evolution/blob/main/proposals/0269-implicit-self-explicit-capture.md). This bug fixes are important usability improvements to using nested closures, and match the expected behavior documented in those proposals.

Most relevant to Swift 6, this change also includes other minor bug fixes that are source breaking, where invalid code was previously allowed to compile. Examples include:

```swift
class Test {
  var x = 0
  static var staticOptional: Test? = Test()

  func testInvalidCodeUnexpectedlyAllowed() {
    withEscapingClosure { [weak self = Test()] in
      guard let self else { return }
      x += 1 // unexpectedly allowed in 5.10, now a warning in Swift 5 mode and an error in Swift 6 mode
    }

    withEscapingClosure { [self = Test()] in
      withEscapingClosure { [weak self] in
        guard let self else { return }
        x += 1 // unexpectedly allowed in 5.10, now a warning in Swift 5 mode and an error in Swift 6 mode
      }
    }

    withEscapingClosure { [weak self] in
      guard let self = self ?? .staticOptional else { return }
      withEscapingClosure { [weak self] in
        guard let self else { return }
        x += 1 // unexpectedly allowed in 5.10, now a warning in Swift 5 mode and an error in Swift 6 mode
      }
    }

    let `self` = Test()
    withEscapingClosure { [weak self] in
      guard let self else { return }
      x += 1 // unexpectedly allowed in 5.10, now a warning in Swift 5 mode and an error in Swift 6 mode
    }
  }
}

func withEscapingClosure(_: @escaping () -> Void) {}
```

All of these examples are supposed to be rejected, but are currently accepted. This PR fixes those issues by making them emit a warning in Swift 5 mode, and be an error in Swift 6 mode.

If we don't land this change in Swift 6, we won't be able to fully fix those issues until the next major language mode.

### Risk

The main risk is that this change could unintentionally introduce a regression in edge cases that we have not found yet. If there are regressions and we don't catch them before the release of Swift 6, we may not be able to fix the regression until Swift 7 (if the bug fix is source breaking, e.g. because the bug accidentally permits code that should be rejected). The best mitigation approach here is thorough testing:

### Testing

We have extensively tested this change in both the Swift 5 and Swift 6 language modes. We added a large number of new test cases for basically every combination of nested closure varieties that we could think of. @hamishknight in particular was very helpful in coming up with even more cases that needed test coverage.

In addition to these new tests, all of the existing tests pass, including the source compatibility suite.

#### Reviewers

Please review: 
 - Original reviewers: @hamishknight, @slavapestov 
 - Release manager: @DougGregor 
 
 Thanks!

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Review by hborla — APPROVED** [review]
Yes, thank you for fixing this!

**Comment by hborla** [comment]
@swift-ci please test

**Comment by hborla** [comment]
@swift-ci please test Linux

**Comment by calda** [comment]
Thanks @hborla! Is this ready to be merged?

**Comment by hborla** [comment]
Yep!

**Pull request merged**
