### PR TITLE
[Lex] Reject standalone dollars as identifiers

### PR DESCRIPTION
**Pull request by CodaFi**
#### What's in this pull request?

Fixes a case where we accidentally accepted a single dollar as an identifier.  This patch supersedes #3004.
#### Resolved bug number: ([SR-1661](https://bugs.swift.org/browse/SR-1661))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

A smoke test on macOS does the following:
1. Builds the compiler incrementally.
2. Builds the standard library only for macOS. Simulator standard libraries and
   device standard libraries are not built.
3. lldb is not built.
4. The test and validation-test targets are run only for macOS. The optimized
   version of these tests are not run.

A smoke test on Linux does the following:
1. Builds the compiler incrementally.
2. Builds the standard library incrementally.
3. lldb is built incrementally.
4. The swift test and validation-test targets are run. The optimized version of these
   tests are not run.
5. lldb is tested.

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please smoke test.

**Comment by CodaFi** [comment]
@swift-ci please smoke test.

**Comment by CodaFi** [comment]
@swift-ci please smoke test Linux platform.

**Comment by CodaFi** [comment]
Let's see if we can't get Linux green again?

@swift-ci please smoke test Linux platform.

**Comment by CodaFi** [comment]
I want to land this clean

@swift-ci please smoke test Linux platform.

**Comment by jtbandes** [comment]
Should this be included in the Swift 3 branch? cc @tkremenek

**Comment by lattner** [comment]
This is source breaking, right?

**Comment by lattner** [comment]
Source breaking changes should wait until we have a framework to support them.  Also, $ is commonly used by dollar.swift, so I'd suggest a targeted fixme that rewrites the $ to a valid identifier, e.g. "💲"  (yes, I'm serious).  This will allow the migrator Swift 3->4 migrator to handle the framework.

**Comment by jtbandes** [comment]
Related proposal that's been waiting for a long time to be merged/closed: https://github.com/apple/swift-evolution/pull/354

**Comment by jtbandes** [comment]
(I'm working with others on a proposal to refine the operator/identifier characters — there's been some interest in including `$` as an operator, too, but I think our proposal will leave it as is: invalid except as part of `$0` or LLDB variables `$R1`)

**Comment by jtbandes** [comment]
What does "a framework to support them" mean? Aren't source-breaking changes encouraged to happen ASAP (3.0.1 or 3.1 or 4) so we can avoid them in the future?

**Comment by jrose-apple** [comment]
We already passed that deadline: it was 3.0. At this point source-breaking changes need to be justified and will be handled on a case-by-case basis.

**Comment by jrose-apple** [comment]
…but the process for doing this hasn't been decided and written up yet.

**Comment by jtbandes** [comment]
I see. And is the swift 3 branch still being used for 3.1? (Sorry for hijacking this PR thread...)

**Comment by jrose-apple** [comment]
Most likely no, we will rebranch there. (Which may mean downgrading this to a warning.)

**Comment by lattner** [comment]
We discussed this topic today in the core team.  Here are some specific requests:
1) Please change this to reject $ with a fixit to `$`  instead of using the emoji I suggested above.
2) Please conditionalize rejection on Swift 4 mode.  This is now a thing, you can see an example of it being used here: https://github.com/apple/swift/commit/12fb0bad7b00337c8a28eb9e0afd4b64e3ddfadc

As to deciding the fate of single $ identifiers, I'm working with a swift-evolution proposal to run this topic by the community.  That could possibly lead to backtracking on our rejection of $, but in the meantime we should still reject it the right way.  Thanks @CodaFi!

**Comment by lattner** [comment]
Sigh, please fixit this from `$` to ``$``... i.e. a dollar sign in backticks.  :-)

**Comment by lattner** [comment]
Maybe this is how you spell it in markdown??  \`$\`

**Comment by lattner** [comment]
OMG, I win! :-)

**Comment by rintaro** [comment]
`$` spelled as `` `$` `` spelled as ``` `` `$` `` ``` spelled as ```` ``` `` `$` `` ``` ```` ...

**Pull request merged**
