### PR TITLE
Fix a null pointer dereferencing bug

### PR DESCRIPTION
**Pull request by swiftix**
Generic signature of a SubstitutionMap may be empty, if the map is empty.

Fixes rdar://31910351 (SR-4750)

### CODE REVIEW

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by slavapestov** [comment]
Why are you performing lookups into an empty substitution map though?

**Comment by swiftix** [comment]
@slavapestov It seems to happen in the PerformanceInliner, in the SILCloner.

```
    frame #0: 0x00000001021f30d7 swiftc`swift::SubstitutionMap::lookupSubstitution(this=0x00007fff5fbf56f8, type=swift::CanSubstitutableType @ 0x00007fff5fbf1d50) const at SubstitutionMap.cpp:116
    frame #1: 0x00000001021fb46a swiftc`swift::QuerySubstitutionMap::operator(this=0x00007fff5fbf3b70, type=0x00000001097bc088)(swift::SubstitutableType*) const at Type.cpp:55
    frame #2: 0x00000001022274d8 swiftc`swift::Type llvm::function_ref<swift::Type (swift::SubstitutableType*)>::callback_fn<swift::QuerySubstitutionMap>(callable=140734799756144, params=0x00000001097bc088) at STLExtras.h:92
    frame #3: 0x0000000102215cca swiftc`llvm::function_ref<swift::Type (swift::SubstitutableType*)>::operator(this=0x00007fff5fbf3150, params=0x00000001097bc088)(swift::SubstitutableType*) const at STLExtras.h:105
    frame #4: 0x00000001022155a3 swiftc`substType(this=0x00007fff5fbf3110, type=0x00000001097bc088)>, llvm::function_ref<llvm::Optional<swift::ProtocolConformanceRef> (swift::CanType, swift::Type, swift::ProtocolType*)>, swift::OptionSet<swift::SubstFlags, unsigned int>)::$_17::operator()(swift::TypeBase*) const at Type.cpp:3050
    frame #5: 0x0000000102214f0f swiftc`llvm::Optional<swift::Type> llvm::function_ref<llvm::Optional<swift::Type> (callable=140734799753488, params=0x00000001097bc088)>::callback_fn<substType(swift::Type, llvm::function_ref<swift::Type (swift::SubstitutableType*)>, llvm::function_ref<llvm::Optional<swift::ProtocolConformanceRef> (swift::CanType, swift::Type, swift::ProtocolType*)>, swift::OptionSet<swift::SubstFlags, unsigned int>)::$_17>(long, swift::TypeBase*) at STLExtras.h:92
    frame #6: 0x000000010220f601 swiftc`llvm::function_ref<llvm::Optional<swift::Type> (swift::TypeBase*)>::operator(this=0x00007fff5fbf2dd0, params=0x00000001097bc088)(swift::TypeBase*) const at STLExtras.h:105
    frame #7: 0x000000010220c348 swiftc`swift::Type::transformRec(this=0x00007fff5fbf3160, fn=function_ref<llvm::Optional<swift::Type> (swift::TypeBase *)> @ 0x00007fff5fbf2dd0)>) const at Type.cpp:3377
    frame #8: 0x000000010220ac45 swiftc`substType(derivedType=Type @ 0x00007fff5fbf3160, substitutions=swift::TypeSubstitutionFn @ 0x00007fff5fbf3150, lookupConformances=swift::LookupConformanceFn @ 0x00007fff5fbf3140, options=(Storage = 1))>, llvm::function_ref<llvm::Optional<swift::ProtocolConformanceRef> (swift::CanType, swift::Type, swift::ProtocolType*)>, swift::OptionSet<swift::SubstFlags, unsigned int>) at Type.cpp:2999
    frame #9: 0x000000010220a160 swiftc`swift::Type::subst(this=0x00007fff5fbf32f8, substitutions=swift::TypeSubstitutionFn @ 0x00007fff5fbf31d8, conformances=swift::LookupConformanceFn @ 0x00007fff5fbf31c8, options=(Storage = 1))>, llvm::function_ref<llvm::Optional<swift::ProtocolConformanceRef> (swift::CanType, swift::Type, swift::ProtocolType*)>, swift::OptionSet<swift::SubstFlags, unsigned int>) const at Type.cpp:3104
    frame #10: 0x00000001020b0871 swiftc`swift::GenericEnvironment::getSubstitutionMap(this=0x00007fff5fbf3730, depTy=Type @ 0x00007fff5fbf3320, reqs=ArrayRef<swift::Requirement> @ 0x00007fff5fbf3310)>, llvm::function_ref<llvm::Optional<swift::ProtocolConformanceRef> (swift::CanType, swift::Type, swift::ProtocolType*)>) const::$_2::operator()(swift::Type, llvm::ArrayRef<swift::Requirement>) const at GenericEnvironment.cpp:371
    frame #11: 0x00000001020b072b swiftc`bool llvm::function_ref<bool (swift::Type, llvm::ArrayRef<swift::Requirement>)>::callback_fn<swift::GenericEnvironment::getSubstitutionMap(callable=140734799755056, params=Type @ 0x00007fff5fbf3388, params=ArrayRef<swift::Requirement> @ 0x00007fff5fbf3378)>, llvm::function_ref<llvm::Optional<swift::ProtocolConformanceRef> (swift::CanType, swift::Type, swift::ProtocolType*)>) const::$_2>(long, swift::Type, llvm::ArrayRef<swift::Requirement>) at STLExtras.h:92
    frame #12: 0x00000001020b37fa swiftc`llvm::function_ref<bool (swift::Type, llvm::ArrayRef<swift::Requirement>)>::operator(this=0x00007fff5fbf3678, params=Type @ 0x00007fff5fbf33e8, params=ArrayRef<swift::Requirement> @ 0x00007fff5fbf33d8)(swift::Type, llvm::ArrayRef<swift::Requirement>) const at STLExtras.h:105
    frame #13: 0x00000001020b361e swiftc`swift::GenericSignature::enumeratePairedRequirements(this=0x00007fff5fbf3598, depTy=CanType @ 0x00007fff5fbf3470)>) const::$_4::operator()(swift::CanType) const at GenericSignature.cpp:311
    frame #14: 0x00000001020b1a1f swiftc`swift::GenericSignature::enumeratePairedRequirements(this=0x00000001092a4180, fn=function_ref<bool (swift::Type, llvm::ArrayRef<swift::Requirement>)> @ 0x00007fff5fbf3678)>) const at GenericSignature.cpp:377
    frame #15: 0x00000001020afeaf swiftc`swift::GenericEnvironment::getSubstitutionMap(this=0x00000001092a41a0, subs=swift::TypeSubstitutionFn @ 0x00007fff5fbf3780, lookupConformance=swift::LookupConformanceFn @ 0x00007fff5fbf3770)>, llvm::function_ref<llvm::Optional<swift::ProtocolConformanceRef> (swift::CanType, swift::Type, swift::ProtocolType*)>) const at GenericEnvironment.cpp:362
    frame #16: 0x00000001021d780a swiftc`swift::ProtocolConformance::subst(this=0x00000001097bc0f8, substType=Type @ 0x00007fff5fbf39e0, subs=swift::TypeSubstitutionFn @ 0x00007fff5fbf39d0, conformances=swift::LookupConformanceFn @ 0x00007fff5fbf39c0)>, llvm::function_ref<llvm::Optional<swift::ProtocolConformanceRef> (swift::CanType, swift::Type, swift::ProtocolType*)>) const at ProtocolConformance.cpp:818
    frame #17: 0x00000001021d7167 swiftc`swift::ProtocolConformanceRef::subst(this=0x00007fff5fbf3b98, origType=Type @ 0x00007fff5fbf3af0, subs=swift::TypeSubstitutionFn @ 0x00007fff5fbf3ae0, conformances=swift::LookupConformanceFn @ 0x00007fff5fbf3ad0)>, llvm::function_ref<llvm::Optional<swift::ProtocolConformanceRef> (swift::CanType, swift::Type, swift::ProtocolType*)>) const at ProtocolConformance.cpp:110
    frame #18: 0x0000000100d6a104 swiftc`swift::TypeSubstCloner<swift::SILInliner>::remapConformance(this=0x00007fff5fbf54a0, type=Type @ 0x00007fff5fbf3ba0, conf=ProtocolConformanceRef @ 0x00007fff5fbf3b98) at TypeSubstCloner.h:102
    frame #19: 0x0000000100d6a024 swiftc`swift::SILCloner<swift::SILInliner>::getOpConformance(this=0x00007fff5fbf54a0, ty=Type @ 0x00007fff5fbf3c40, conformance=ProtocolConformanceRef @ 0x00007fff5fbf3c38) at SILCloner.h:181
    frame #20: 0x0000000100d69e02 swiftc`swift::SILCloner<swift::SILInliner>::getOpConformances(this=0x00007fff5fbf54a0, ty=Type @ 0x00007fff5fbf3ce8, conformances=ArrayRef<swift::ProtocolConformanceRef> @ 0x00007fff5fbf3cd8) at SILCloner.h:190
    frame #21: 0x0000000100d6a4bf swiftc`swift::SILCloner<swift::SILInliner>::getOpSubstitution(this=0x00007fff5fbf54a0, sub=Substitution @ 0x00007fff5fbf3de0) at SILCloner.h:197
  * frame #22: 0x0000000100d5fa8c swiftc`swift::TypeSubstCloner<swift::SILInliner>::visitApplyInst(this=0x00007fff5fbf54a0, Inst=0x000000011134de60) at TypeSubstCloner.h:130
    frame #23: 0x0000000100d56de3 swiftc`swift::SILVisitor<swift::SILInliner, void>::visit(this=0x00007fff5fbf54a0, V=0x000000011134de60) at SILNodes.def:202
    frame #24: 0x0000000100d55789 swiftc`swift::SILCloner<swift::SILInliner>::visitSILBasicBlock(this=0x00007fff5fbf54a0, BB=0x0000000110c07c38) at SILCloner.h:404
    frame #25: 0x0000000100d54d9e swiftc`swift::SILInliner::inlineFunction(this=0x00007fff5fbf54a0, AI=FullApplySite @ 0x00007fff5fbf5078, Args=ArrayRef<swift::SILValue> @ 0x00007fff5fbf5068) at SILInliner.cpp:107
    frame #26: 0x0000000100f70141 swiftc`(anonymous namespace)::SILPerformanceInliner::inlineCallsIntoFunction(this=0x00007fff5fbf5908, Caller=0x0000000110c08070) at PerformanceInliner.cpp:790
    frame #27: 0x0000000100f6fb0a swiftc`(anonymous namespace)::SILPerformanceInlinerPass::run(this=0x0000000111372440) at PerformanceInliner.cpp:860
```

when it tries to remap the substitutions:
```
frame #22: 0x0000000100d5fa8c swiftc`swift::TypeSubstCloner<swift::SILInliner>::visitApplyInst(this=0x00007fff5fbf54a0, Inst=0x000000011134de60) at TypeSubstCloner.h:130
   127 	
   128 	    SmallVector<Substitution, 16> TempSubstList;
   129 	    for (auto &Sub : Inst->getSubstitutions()) {
-> 130 	      TempSubstList.push_back(asImpl().getOpSubstitution(Sub));
   131 	    }
   132 	
   133 	    ApplyInst *N = Builder.createApply(
(lldb) p Inst->dumpInContext()
     %0 = argument of bb0 : $Optional<RxMutableBox<Queue<ScheduledItemType>>> // users: %14, %6, %13, %2
     // function_ref static Thread.setThreadLocalStorageValue<A>(_:forKey:)
  %3 = function_ref @_T0So6ThreadC7RxSwiftE03setA17LocalStorageValueyxSg_SS6forKeyts9AnyObjectRzlFZ : $@convention(method) <τ_0_0 where τ_0_0 : AnyObject> (@owned Optional<τ_0_0>, @owned String, @thick Thread.Type) -> () // user: %13
     %4 = metatype $@thick Thread.Type            // user: %13
     %9 = load %8 : $*String                      // users: %10, %13
->   %13 = apply %3<RxMutableBox<Queue<ScheduledItemType>>>(%0, %9, %4) : $@convention(method) <τ_0_0 where τ_0_0 : AnyObject> (@owned Optional<τ_0_0>, @owned String, @thick Thread.Type) -> ()
```

The replacement type in the substitution is concrete, as you can see.

**Comment by swiftix** [comment]
In fact, if the substitution map in the `TypeSubstCloner` is empty (i.e. we are not in a generic context), we can just skip any remapping and return the original type or conformance.

**Comment by slavapestov** [comment]
After discussing this with @swiftix we realized the root cause is a special case hack for AnyObject. It's going aaay... really soon now

**Comment by swiftix** [comment]
Closing. It was subsumed by a different PR.

**Pull request closed without merging**
