### PR TITLE
Manually merge main into next

### PR DESCRIPTION
**Pull request by bnbarham**
Two conflicts - GlobalExecutor.cpp and RequirementMachineRequests.cpp

### CODE REVIEW

**Review by ktoso — CHANGES_REQUESTED** [review]
Please watch out and don't merge this as-is -- we merged a fix to main which is very important: https://github.com/apple/swift/pull/39798 So pull from main again or cherry pick this fix please @bnbarham 

Once that's in, the GlobalExecutor change is good.

**Comment by bnbarham** [comment]
> Please watch out and don't merge this as-is -- we merged a fix to main which is very important: #39798 So pull from main again or cherry pick this fix please @bnbarham
> 
> Once that's in, the GlobalExecutor change is good.

Fixed, doesn't really matter but would have just had another conflict anyway 😆

**Comment by etcwilde** [comment]
> @etcwilde I didn't notice that #39780 was a single commit rather than merge. Is that normal for merging into next? That's the reason for all the commits in this one 🤷.

Hmm, interesting. What did I do? It shouldn't break things too much. I hope....

**Comment by bnbarham** [comment]
> If that matters then perhaps we should revert that commit and then re-merge.

FWIW I've done that in https://github.com/apple/swift/pull/39801 if we do. If not we can just merge this one 🤷

**Pull request closed without merging**
