### PR TITLE
Cherry-pick RequirementMachine fixes to 5.7 branch

### PR DESCRIPTION
**Pull request by slavapestov**
rdar://problem/91232987, rdar://problem/90192939, rdar://problem/91304291

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Review by DougGregor — APPROVED** [review]

**Comment by slavapestov** [comment]
@swift-ci Please test macOS

**Comment by slavapestov** [comment]
@swift-ci Please test macOS

**Comment by slavapestov** [comment]
@swift-ci Please test macOS

**Comment by slavapestov** [comment]
@swift-ci Please test macOS

**Pull request merged**
