### PR TITLE
Exclude properties of class with type Self [5.1]

### PR DESCRIPTION
**Pull request by slavapestov**
Cherry-picking @johnno1962's PR https://github.com/apple/swift/pull/23485 to the 5.1 branch.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by johnno1962** [comment]
:( I've looked at the compatibility failures ad it's not clear they are `Self` related (many are SPM manifest version related). Would it be possible to run the compatibility checks on master branch?

**Comment by slavapestov** [comment]
The failures are not related.

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by johnno1962** [comment]
Thanks @slavapestov

**Pull request merged**
