### PR TITLE
[code-completion] Add Bool type context for if/guard/while conditions

### PR DESCRIPTION
**Pull request by benlangmuir**
* Explanation: This adds a type context of `Bool` when code-completing in an `if/guard/while` statement condition (not including conditions that are bindings).
* Scope: Affects priority of code-completions in boolean conditions on if/while/guard statements.
* Radar: rdar://problem/26509084
* Risk: Low; just extends existing code-completion type-relation code that we had for `repeat ... while` to consider more statement kinds.
* Testing: Regression tests added.

### CODE REVIEW

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please test macOS

**Review by nathawes — APPROVED** [review]
LGTM!

**Comment by benlangmuir** [comment]
Investigating the test failure.

**Comment by benlangmuir** [comment]
Aha, this had a dependency on https://github.com/apple/swift/pull/11562 that I didn't realize.  The parser change there is necessary or we just throw out the whole condition.  I'll rebase the PR since that was just merged.

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please test

**Pull request merged**
