### PR TITLE
`line-directive` decode utf8 charset

### PR DESCRIPTION
**Pull request by etcwilde**
The line-directive was failing due to receiving non-ascii chars.
This patch sets the command to expect utf-8 encoded strings.

I'm not sure how to cross-test within the same repo, but this patch should fix the encoding issue in https://github.com/apple/swift/pull/34343.

rdar://70403601

### CODE REVIEW

**Comment by etcwilde** [comment]
@swift-ci please test

**Review by edymtt — COMMENTED** [review]
To test this, what would you think of augmenting `validation-test/Python/line-directive.swift` with an invocation like

```
// RUN: %{python} %utils/line-directive -- %{python} -c "print('Hello 😄🂐')" 
```

**Comment by etcwilde** [comment]
> To test this, what would you think of augmenting `validation-test/Python/line-directive.swift` with an invocation like
> 
> ```
> // RUN: %{python} %utils/line-directive -- %{python} -c "print('Hello 😄🂐')" 
> ```

Yeah, that seems reasonable. Let me make sure that it fails without the changes and I'll put it up as part of the test.

**Review by atrick — APPROVED** [review]
Thanks! I'll try to reproduce the original issue, but clearly this is the right fix. A separate unit test makes more sense.

**Review by gottesmm — APPROVED** [review]
Add the test/etc, then LGTM

**Comment by etcwilde** [comment]
@swift-ci please test

**Comment by etcwilde** [comment]
🤦 missed a space `/Applications/Xcode-beta.app/Contents/Developer/usr/bin/python3-c`.
@swift-ci please test

**Comment by etcwilde** [comment]
https://ci.swift.org/job/oss-swift-RA-linux-ubuntu-18_04/892/

```
FAIL: Swift-validation(linux-x86_64) :: Python/line-directive.swift (8917 of 15603)
******************** TEST 'Swift-validation(linux-x86_64) :: Python/line-directive.swift' FAILED ********************
Script:
--
: 'RUN: at line 1';   /usr/bin/python3.6 /home/build-user/swift/utils/line-directive
: 'RUN: at line 2';   /usr/bin/python3.6 /home/build-user/swift/utils/line-directive -- /usr/bin/python3.6 -c "print('Hello ??')"
--
Exit Code: 1

Command Output (stdout):
--
Unable to decode the command from the command line:
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 13-20: surrogates not allowed

--
```

So it seems that some python utf8 decoders have implicit surrogate conversion while others don't. That's just obnoxious.

**Comment by etcwilde** [comment]
It looks like we also break `llvm-lit`. Not going to lie, that's amuses me greatly.

```
Traceback (most recent call last):
  File "/home/build-user/llvm-project/llvm/utils/lit/lit.py", line 6, in <module>
    main()
  File "/home/build-user/llvm-project/llvm/utils/lit/lit/main.py", line 117, in main
    report.write_results(tests_for_report, elapsed)
  File "/home/build-user/llvm-project/llvm/utils/lit/lit/reports.py", line 101, in write_results
    self._write_testsuite(file, suite, list(test_iter))
  File "/home/build-user/llvm-project/llvm/utils/lit/lit/reports.py", line 111, in _write_testsuite
    self._write_test(file, test, name)
  File "/home/build-user/llvm-project/llvm/utils/lit/lit/reports.py", line 136, in _write_test
    file.write(output)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 220-221: ordinal not in range(128)
```

**Comment by gottesmm** [comment]
:doh:

**Comment by etcwilde** [comment]
I've put the fix up here; https://github.com/apple/swift/pull/58617
It's almost done testing.

**Pull request merged**
