### PR TITLE
Fix README.md build table formatting

### PR DESCRIPTION
**Pull request by proydakov**
Fixed bad format in Markdown README

### CODE REVIEW

**Comment by proydakov** [comment]
@swift-ci Please smoke test

**Comment by proydakov** [comment]
@swift-ci please test

**Comment by louisdh** [comment]
Already fixed this in #8200 🙃
This is due to GitHub's new Markdown parser, btw.

**Comment by CodaFi** [comment]
@proydakov For future reference, [invoking CI requires privileges](https://swift.org/contributing/#contributing-code)

**Pull request closed without merging**
