### PR TITLE
[TypeChecker] Un-XFAIL perf test-case for rdar://23620262

### PR DESCRIPTION
**Pull request by xedin**
Resolves: rdar://problem/38378503

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please clean test

**Comment by xedin** [comment]
I think this one has been fixed by @hborla's changes in https://github.com/apple/swift/pull/34399.

**Review by hborla — APPROVED** [review]
Awesome, thank you! I didn't even think to check for XFAIL'd "fast" tests

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
Let’s run macOS a couple more times to ensure that there is no flakiness.

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Pull request merged**
