### PR TITLE
[Serialization] Make serialization of witnesses deterministic

### PR DESCRIPTION
**Pull request by DougGregor**
Serialization of the requirement-to-synthetic-environment map was
walking in DenseMap order. However, the keys to this map are
known---they're always the generic parameters of the requirement. So,
walk those generic parameters to make it deterministic, and don't
bother serializing them because they're known to the deserializer
already.

Fixes rdar://problem/29689811. Obsoletes https://github.com/apple/swift/pull/6288 by pulling in that one commit.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by jrose-apple** [comment]
Does it make sense to assert that the map always has the same number of items as the generic parameter list?

**Comment by DougGregor** [comment]
Yeah, I can assert that. `SubstitutionMap` should eventually know how to do this, once it gets weaned off `TypeSubstitutionMap`.

**Comment by slavapestov** [comment]
Careful, it has the same number of keys as generic parameters in the signature (which is the sum of all outer generic parameter lists).

**Comment by jckarter** [comment]
This may have broken the `parse_stdlib` tests: https://ci.swift.org/job/oss-swift-incremental-RA-linux-ubuntu-14_04-long-test/

When we try to print a `GenericTypeParamType` in SIL mode, we use the sugar type from the GenericEnvironment, but since the types get deserialized now with associations to nameless `GenericTypeParamDecl`s, that ends up taking precedence and causing us to print them as `<anonymous>`, making the output unparsable. See https://github.com/apple/swift/blob/2c6b9f7/lib/AST/ASTPrinter.cpp#L3966 .

**Pull request merged**
