### PR TITLE
Tidy up debug printing and dumping a bit, moving from errs() to dbgs()

### PR DESCRIPTION
**Pull request by lattner**
Tidy up debug printing and dumping a bit, moving from errs() to dbgs()
in a few places.

### CODE REVIEW

**Comment by lattner** [comment]
@swift-ci please test tensorflow

**Review by dan-zheng — APPROVED** [review]

**Review by rxwei — APPROVED** [review]
Nice

**Review by mhong — APPROVED** [review]
Nice!

What's the benefit of using dbgs() over errs()?

I understand the use of DEBUG(). For dbgs(), does it allow user to dump the output somewhere else (and if so, how?)

**Comment by lattner** [comment]
The only advantage is that it is more consistent with the rest of the codebase.  DEBUG goes away in release builds too.

**Pull request merged**
