### PR TITLE
[embedded] Start building embedded stdlib on Windows

### PR DESCRIPTION
**Pull request by kubamracek**
This is a baby step, no testing yet, no Concurrency yet, but just to get the stdlib(s) building.

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by MaxDesiatov — APPROVED** [review]
yes plz

**Review by compnerd — APPROVED** [review]

**Comment by kubamracek** [comment]
Hm, looking at the Windows CI build log, I don't think the change did anything. Does anyone has any idea why?

**Comment by kubamracek** [comment]
@swift-ci please test Windows platform

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test Windows platform

**Comment by kubamracek** [comment]
@swift-ci please test Windows platform

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test Windows platform

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by edymtt — APPROVED** [review]

**Pull request merged**
