### PR TITLE
Move a few lines from stability-stdlib-abi-with-asserts.test to stability-stdlib-abi-without-asserts.test

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@glessard This was failing in the noasserts bots. It appears the change is independent of asserts vs noasserts, and should go in the noasserts diff instead (which is concatenated with the asserts diff).

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by glessard** [comment]
I initially tried to add it to the no-asserts exclusion list, and it still failed. That's why I added it to the with-asserts file instead.

**Comment by slavapestov** [comment]
https://ci.swift.org/job/oss-swift_tools-R_stdlib-RD_test-simulator//6876/consoleFull

**Review by glessard — APPROVED** [review]
LGTM

**Review by lorentey — APPROVED** [review]

**Pull request merged**
