### PR TITLE
Avoid generating address phis in LoopUnroll

### PR DESCRIPTION
**Pull request by meg-gupta**

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test linux platform

**Comment by meg-gupta** [comment]
@swift-ci test macOS platform

**Comment by meg-gupta** [comment]
This is similar to the fixes in https://github.com/apple/swift/pull/60763
Merging in.

**Review by atrick — COMMENTED** [review]
Big thanks!

**Pull request merged**
