### PR TITLE
Fixes for s390x

### PR DESCRIPTION
**Pull request by vivkong**
In the first commit, we need to use Swift calling convention when dealing with BoxPair on s390x.  BoxPair is expected to be returned in 2 registers but there is no native C type that is returned in two registers by the default ABI on s390x.

The second commit fixes the way enum payloads are packed for big endian order.

Both of these commits resolve test failures on s390x therefore no new test cases are added.

### CODE REVIEW

**Comment by jckarter** [comment]
Thanks @vivkong!

@rjmccall @aschwaighofer As a followup, does `SWIFT_CC(swift)` let us get rid of the `BoxPair::Return` hack altogether on all our supported platforms?

**Comment by vivkong** [comment]
@aschwaighofer I have to question for a fix I need in clang for s390x.  I saw the original commit was done by you.  In `lib/CodeGen/TargetInfo.cpp`, `isSwiftErrorInRegister()` in `SystemZABIInfo` needs to return `false`.  Should I open a bug?

**Comment by aschwaighofer** [comment]
@vivkong According to llvm's calling convention description swiferror is passed in R9:
https://github.com/apple/swift-llvm/blob/stable/lib/Target/SystemZ/SystemZCallingConv.td#L37
https://github.com/apple/swift-llvm/blob/stable/lib/Target/SystemZ/SystemZCallingConv.td#L75

Are there bugs in the SystemZ backend that precludes this from working?  If yes, it makes sense to disable usage of swifterror on SystemZ by returning false from ``isSwiftErrorInRegister`` until the backend is fixed.

**Comment by vivkong** [comment]
@aschwaighofer, It's not working correctly at the moment.  How should I request this change in Clang?  Or would it be better to temporary set `IsSwiftErrorInRegister` to false in https://github.com/apple/swift/blob/master/lib/IRGen/IRGenModule.cpp?utf8=%E2%9C%93#L408 ?

**Comment by aschwaighofer** [comment]
@vivkong I pushed a fix to llvm.org and it is on stable and swift-4.1-branch.

**Comment by aschwaighofer** [comment]
@vivkong Can you file a bug at https://bugs.llvm.org that swifterror support is broken on SystemZ if there is not one already?

**Comment by vivkong** [comment]
@aschwaighofer Thanks!  And will do.

**Comment by vivkong** [comment]
I'd like to get feedback on these changes and possibly get them merged.  Thanks.

**Review by aschwaighofer — COMMENTED** [review]
The BoxPair change is subsumed by: https://github.com/apple/swift/pull/13299
[runtime] Remove TwoWordPair and use the Swift calling convention instead. (#13299)

The big endian changes are fine by me.

**Comment by rjmccall** [comment]
I agree with Arnold's take.

**Comment by vivkong** [comment]
Thanks for the review.  I've removed the commit for BoxPair.

**Comment by vivkong** [comment]
Can we please kick off the smoke test?  Thanks.

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
At this point you should probably [ask for commit/testing privileges](https://swift.org/contributing/#contributing-code), even if you just use it for tests and still wait for review. You've been around long enough!

**Comment by vivkong** [comment]
Sorry can we try kicking off the tests again?

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test

**Comment by vivkong** [comment]
Thanks for your help @jrose-apple @aschwaighofer.

I'd like to have this in Swift 5.0 branch and if possible 4.1.  Do I have to create a PR for Swift 5.0?  I couldn't find the 5.0 release process (probably didn't look hard enough) so I wasn't sure if this will be merged in 5.0.

**Comment by jrose-apple** [comment]
5.0 is just a staging branch right now; we'll do another rebranch of master before the release. 4.1 is the usual cherry-pick-and-request process.

**Pull request merged**
