### PR TITLE
[5.0] [String] ASCII fast-path for UTF16View

### PR DESCRIPTION
**Pull request by milseman**
5.0 cherry-pick of https://github.com/apple/swift/pull/20848

### CODE REVIEW

**Comment by milseman** [comment]
This includes a cherry-pick of https://github.com/apple/swift/pull/20899, otherwise we would conflict upon either of us being merged.

**Comment by milseman** [comment]
@apple/swift5-branch-managers

* Convergence

This adds important performance improvements to the ASCII strings which are bridged to Cocoa. This is a very frequent use case (identifiers, selectors, key paths, etc).

* ABI impact

This has no ABI impact.

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please test

**Review by airspeedswift — APPROVED** [review]

**Pull request merged**
