### PR TITLE
build-script: add flag to pass arguments to dsymutil

### PR DESCRIPTION
**Pull request by edymtt**
This is currently needed to disable DWARF verification in some Apple internal configurations.

Addresses rdar://125092216

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci please python lint

**Comment by edymtt** [comment]
@swift-ci please test

**Comment by edymtt** [comment]
@swift-ci please build toolchain

**Comment by edymtt** [comment]
@swift-ci please test WebAssembly

**Review by JDevlieghere — APPROVED** [review]

**Review by 187ram — APPROVED** [review]

**Review by shahmishal — APPROVED** [review]

**Comment by edymtt** [comment]
@swift-ci please build toolchain macOS

**Comment by edymtt** [comment]
Please test with following pull request:
https://github.com/apple/swift-integration-tests/pull/133

@swift-ci please build toolchain macOS

**Review by compnerd — APPROVED** [review]
This seems fine to me, but perhaps we should name the parameter dsymutil-extra-args as they are appended.

**Review by etcwilde — APPROVED** [review]

**Comment by edymtt** [comment]
Took @compnerd 's suggestion in efdd4954d3711d454492d1c3058cca6ee8b0707d -- ended up renaming that to `extra-dsymutil-args` to match the existing `extra-swift-args` and `extra-cmake-options` flags.

**Comment by edymtt** [comment]
@swift-ci please test

**Comment by edymtt** [comment]
@swift-ci please test WebAssembly

**Comment by edymtt** [comment]
Please test with following pull request:
https://github.com/apple/swift-integration-tests/pull/133

@swift-ci please build toolchain

**Comment by edymtt** [comment]
@swift-ci please test WebAssembly

**Comment by edymtt** [comment]
@swift-ci please test Windows

**Pull request merged**
