### PR TITLE
Revert "Merge pull request #32628 from benlangmuir/sema-repeat"

### PR DESCRIPTION
**Pull request by benlangmuir**
This reverts commit 35eab3e3a8abc215c622862df139f97dc387d197, reversing
changes made to d5a549a9e49e7ac256f5599caa7b491c2fe7b4b4.

This caused an unexpected regression.

rdar://65554791

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by benlangmuir** [comment]
@swift-ci please smoke test

**Comment by benlangmuir** [comment]
```
Failing Tests (1):
    Swift(windows-x86_64) :: stdlib/ForEachField.swift
```

Unrelated failure.

**Comment by benlangmuir** [comment]
@swift-ci please smoke test Windows

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Pull request merged**
