### PR TITLE
[Typechecker] Check for generic signature when matching overrides

### PR DESCRIPTION
**Pull request by theblixguy**
At the moment, we trigger an error for the following code:

```swift
class Base {
  func a<T>(_ val: T) -> String { return "not equatable" }
  func a<T: Equatable>(_ val: T) -> String { return "equatable" }
}

class Derived: Base {
  // error: cannot override more than one superclass declaration
  override func a<T>(_ val: T) -> String { return super.a(val) }
  override func a<T: Equatable>(_ val: T) -> String { return super.a(val) }
}
```

even though the overrides are valid because they have different generic signatures. This PR adds a check to `isOverrideBasedOnType()` to ensure we also take into consideration the generic signature of the overridden and base declarations. This means we can ignore the other declaration and not include it in the match.

Resolves [SR-10198](https://bugs.swift.org/browse/SR-10198)
Resolves rdar://problem/49339618

### CODE REVIEW

**Comment by theblixguy** [comment]
cc @slavapestov

**Comment by slavapestov** [comment]
Should the other check be removed then?

**Comment by theblixguy** [comment]
@slavapestov Which other check?

**Comment by slavapestov** [comment]
Here you're comparing signatures for exact equality again. I'm not sure that works given that the base class and derived class can have different generic signatures. Doesn't this need to use the same logic you added recently to compute the override signature, etc?

**Comment by theblixguy** [comment]
@slavapestov I was trying to use that but it didn't work, but I realised I made a mistake which is why it wasn't working. I have updated my code now, although `requirementsNotSatisfiedBy()` does not work here so I have to compare canonical signatures directly as before.

**Comment by slavapestov** [comment]
I guess I don’t understand when this function is getting called...

**Comment by theblixguy** [comment]
`visitFuncDecl() -> checkOverrides() -> match() -> isOverrideBasedOnType()`.

**Comment by slavapestov** [comment]
So wouldn't isOverrideBasedOnType() return false in the cases you added where the override has a relaxed set of requirements?

**Comment by theblixguy** [comment]
It doesn't seem to i.e. this still works:

```
class SR_10198_Base {
  func foo<T: Equatable>(_ val: T) {}
}

class SR_10198_Derived: SR_10198_Base {
  override func foo<T>(_ val: T) {}
}
```

**Comment by slavapestov** [comment]
Ok, but we need to figure out what's going on because clearly as written this code should be rejecting the overrides when the generic signatures don't match exactly. Can you step through the code and see why that is not happening?

**Comment by theblixguy** [comment]
For the above example, we get:

```
overridden sig: <T where T : Equatable>
base sig: <T where T : Equatable>
derived sig: <T>
```

We are indeed returning false from `isOverrideBasedOnType` for the above case. I think what's happening is that we're falling down to checking for subtyping in `match()`.

**Comment by slavapestov** [comment]
I see. So `isOverrideBasedOnType()` only handles the perfect match case, but we can still succeed with a subtype match. That's a bit confusing, but OK. If you add a comment I'd be happy to take this change.

**Comment by theblixguy** [comment]
@slavapestov Done!

**Review by slavapestov — APPROVED** [review]

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by theblixguy** [comment]
Hmm `Assertion failed: (!params.empty())` in `compiler_crashers_2_fixed/0078-sr4059.swift`, which is being hit in `swift::GenericSignature::get()`. I've seen this before when fixing the original bug. Should we add a check to `getOverrideGenericSignature()`?

**Comment by slavapestov** [comment]
It sounds like you're creating a GenericSignatureBuilder, failing to add any parameters, and then asking it for the built signature.

It should be easy to detect we're in this case before creating the GenericSignatureBuilder and just return null as the override signature. I believe this just means that the derived class is not generic, and the base class method does not have its own generic parameters.

**Comment by slavapestov** [comment]
Also can you try to come up with a reduced test case for the crash and add it to your existing tests?

**Comment by theblixguy** [comment]
@slavapestov Figured a better fix is to simply do `!derivedGenericCtx || !derivedGenericCtx->isGeneric()` early and bail out. I have added a reduced test case as well.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by theblixguy** [comment]
Thank you! All tests have passed!

**Comment by slavapestov** [comment]
Alright, I think we can merge this now. Thank you!

**Pull request merged**
