### PR TITLE
[sil] Rename test/SILOptimizer/{unreachable_code,diagnose_unreachable…

### PR DESCRIPTION
**Pull request by gottesmm**
…}.swift

This matches the name of the SIL test (diagnose_unreachable.sil) for these types
of errors.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
Not sure why this failed.

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@shahmishal Do you know why this is failing. I just moved a test... this is 200% NFC.

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by shahmishal** [comment]
@swift-ci smoke test macOS

**Pull request merged**
