### PR TITLE
[6.0] AsyncIteratorProtocol conformance fixes

### PR DESCRIPTION
**Pull request by DougGregor**
Explanation: Address two issues that make conformance to `AsyncIteratorProtocol` harder to conform to than they need to be. First, correctly infer the thrown error type from `next()` if it adopts typed throws but `next(isolation:)` is defaulted. Second, default `next()` in terms of `next(isolation:)` so one need only implement one of them.
Issue: rdar://125446918 & rdar://125447861
Original PR: https://github.com/apple/swift/pull/72673
Risk: Low. The change only impacts associated type inference in a narrow case for new code (where `next()` has adopted type throws) and makes conformance to `AsyncIteratorProtocol` simpler.
Testing: New tests.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test Windows

**Review by hborla — APPROVED** [review]

**Comment by DougGregor** [comment]
@swift-ci please test macOS

**Comment by DougGregor** [comment]
@swift-ci please test

**Pull request merged**
