### PR TITLE
Fix typo in partial_specialization.sil

### PR DESCRIPTION
**Pull request by eltociear**
peformed -> performed

### CODE REVIEW

**Comment by xwu** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by CodaFi** [comment]
@swift-ci

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Review by shivaylamba — APPROVED** [review]

**Comment by xwu** [comment]
@swift-ci smoke test Windows platform

**Pull request merged**
