### PR TITLE
Add silcombines for destructure_tuple and destructure_struct

### PR DESCRIPTION
**Pull request by meg-gupta**

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test windows platform

**Comment by eeckstein** [comment]
We already have this simplifications in SwiftCompilerSources: https://github.com/apple/swift/blob/main/SwiftCompilerSources/Sources/Optimizer/InstructionSimplification/SimplifyDestructure.swift

To let it run in the SILCombiner, just let it conform to `SILCombineSimplifyable` and add a `SWIFT_SILCOMBINE_PASS` in `Passes.def`.

In general, we should implement new SILCombine simplifications in swift rather than in C++.

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Review by eeckstein — APPROVED** [review]
lgtm, thanks

**Pull request merged**
