### PR TITLE
Rip out SILGenApply's ArchetypeCalleeBuilder

### PR DESCRIPTION
**Pull request by slavapestov**
This is a major simplification to the code path for forming protocol method calls.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by jckarter** [comment]
Awesome! So many red lines…

**Pull request merged**
