### PR TITLE
stdlib: remove unneeded @_transparent attributes

### PR DESCRIPTION
**Pull request by gribozavr**
Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by gribozavr** [comment]
@swift-ci Please benchmark

**Comment by gribozavr** [comment]
@swift-ci Please benchmark

**Comment by jrose-apple** [comment]
The pointer conversions are very hot paths, and I think we probably want them to be available for diagnostics if we get more path-sensitive analysis. I would leave these the way they are.

**Comment by gribozavr** [comment]
> The pointer conversions are very hot paths,

Then we should be using `@inline(always)`.

> and I think we probably want them to be available for diagnostics if we get more path-sensitive analysis.

When we get a more powerful analysis engine, we can upgrade them to `@_transparent` again.

> I would leave these the way they are.

The reason I'm doing this is that these functions are keeping all of Array's implementation details exposed as `public`.

**Comment by jckarter** [comment]
IIRC `@inline(always)` still doesn't inline at -Onone. Was that changed recently?

**Comment by gribozavr** [comment]
> IIRC @inline(always) still doesn't inline at -Onone.

It still doesn't.  :(  Dropping this.

**Comment by jrose-apple** [comment]
Either we want the conversion from inout-Array-to-pointer to be inlineable, or we don't. You can use `@_versioned` instead of `public` if you want, but it has just as much implication of ABI stability.

**Comment by jrose-apple** [comment]
Also, we shouldn't choose between `@_transparent` and `@inline(__always)` based on what the compiler does today if `@_transparent` is actually the right choice. See [TransparentAttr.rst](https://github.com/apple/swift/blob/master/docs/TransparentAttr.rst).

**Comment by gribozavr** [comment]
@jrose-apple I think we want `@inline(__always)` is the right choice (there are no diagnostics that could benefit from inlining these functions), but it has no effect at Onone, so it causes performance regressions.

**Comment by jrose-apple** [comment]
Debugging should never step into them.

**Comment by gribozavr** [comment]
@jrose-apple The debugger never steps into anything in the standard library.

**Pull request closed without merging**
