### PR TITLE
[5.9][Macros] Generalize `conformance` macros as `extension` macros

### PR DESCRIPTION
**Pull request by hborla**
* **Explanation**: Conformances macros are problematic and limited. This change implements a generalization of conformance macros as extension macros. This allows adding members in extensions, properly extending nested types with a macro expansion that will actually compile if added to the code directly, and enables a path forward for suppressing expanded conformances if the extended type already conforms to the protocol.
* **Issue**: rdar://110616211
* **Risk**: Low. This change preserves the `conformance` macro role (for now) rather than replacing it, and `extension` macros are not yet used.
* **Testing**: Added new tests.
* **Main branch PR**: https://github.com/apple/swift/pull/66967

### CODE REVIEW

**Comment by hborla** [comment]
https://github.com/apple/swift-syntax/pull/1861

@swift-ci please test

**Comment by hborla** [comment]
https://github.com/apple/swift-syntax/pull/1861

@swift-ci please test

**Comment by hborla** [comment]
https://github.com/apple/swift-syntax/pull/1861

@swift-ci please test macOS

**Review by DougGregor — APPROVED** [review]

**Comment by hborla** [comment]
https://github.com/apple/swift-syntax/pull/1861

@swift-ci please test

**Pull request merged**
