### PR TITLE
[ConstraintSystem] `openOpaqueType`: remove logic that duplicates `bindArchetypesFromContext`

### PR DESCRIPTION
**Pull request by xedin**
`openGenericParameters` calls `bindArchetypesFromContext` which would bind all of the
external generic parameters in the opaque type signature.

Resolves: rdar://107280056

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Review by slavapestov — APPROVED** [review]
Nice!

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Pull request merged**
