### PR TITLE
[4.2] Move SwiftSyntax to its own repository

### PR DESCRIPTION
**Pull request by ahoppen**
This PR sets up the infrastructure to build SwiftSyntax from its own repository for the `swift-4.2-branch`. For this it does:
- Add the new `swift-syntax` repository to `update-checkout`
- Add a `build-script` option to build and test `swift-syntax`
- Update the build presets to test SwiftSyntax when running `@swift-ci Please test`

Removing SwiftSyntax from the `swift-4.2-branch` of this repository will be done in a separate PR.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by akyrtzi** [comment]
For anyone else reading this, we've decided against removing SwiftSyntax from swift-4.2-branch. It won't affect things and we want to make swift-4.2-branch changes as minimum as possible.

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please build toolchain

**Comment by ahoppen** [comment]
@swift-ci Please Build Toolchain

**Review by akyrtzi — APPROVED** [review]

**Review by shahmishal — APPROVED** [review]

**Pull request merged**
