### PR TITLE
[master-next] driver: update for change to Expected<>

### PR DESCRIPTION
**Pull request by compnerd**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

ErrorOr<> was replaced with Expected<> upstream.  getError() is no longer
available.  Furthermore, Error::message is no longer available either.  Use
toString to stringify the error message.

### CODE REVIEW

**Comment by compnerd** [comment]
CC @gottesmm

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Comment by compnerd** [comment]
That ran the build on master, not master-next.  I think that the trigger is different for master-next.

**Comment by jrose-apple** [comment]
Ah, it looks like it's always going to do this against the stable-next branch, which hasn't been updated to the most recent upstream-with-swift.

**Comment by compnerd** [comment]
@vedantk did a similar change on master-next.  Abandoning.

**Pull request closed without merging**
