### PR TITLE
[5.4][Runtime] Scan backwards within conformance sections when scanSectionsBackwards is true.

### PR DESCRIPTION
**Pull request by mikeash**
Cherry-pick https://github.com/apple/swift/pull/35489 to 5.4.

This more closely matches the previous behavior.

rdar://73362732

### CODE REVIEW

**Comment by mikeash** [comment]
@swift-ci please test

**Review by tbkka — APPROVED** [review]
Looks straightforward enough.

**Review by airspeedswift — APPROVED** [review]

**Comment by mikeash** [comment]
@swift-ci please test os x platform

**Comment by mikeash** [comment]
@swift-ci please test os x platform

**Comment by mikeash** [comment]
@swift-ci please test Windows platform

**Comment by mikeash** [comment]
@swift-ci please test Windows platform

**Pull request merged**
