### PR TITLE
stubs: provide an out-of-line definition of `sqrtf` on Win x86

### PR DESCRIPTION
**Pull request by compnerd**
`ucrt` does not provide a definition for `sqrtf` in the runtime
component.  It is expected that the symbol will be expanded by the
inline definition to lower to `sqrt` with the argument widened and the
result narrowed.  However, this requires the Swift shims to depend on
`ucrt` which is not permissible as it exists to break the circular
dependency in the modules.  This provides an out-of-line alias for the
symbol to allow the Swift runtime to resolve the symbol.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @stephentyrone

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by stephentyrone** [comment]
Does this actually work? I would expect it to fail for exactly the same reason using `__builtin_sqrt` does.

**Comment by compnerd** [comment]
Yeap, this works as it explicitly spells out the function to call.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by stephentyrone** [comment]
> Yeap, this works as it explicitly spells out the function to call.

But LLVM knows about sqrt, so it is licensed to optimize this: `(float)sqrt((double)f)` to `sqrtf(f)`, and if it does, I think this just becomes an infinite loop, right?

**Comment by compnerd** [comment]
The backend I believe does know this the problem is the frontend.  clang aggressively lowers `__builtin_sqrtf` as a `__builtin_` prefixed call to `sqrtf` and then will result in that being a spelt out call that never gets replaced.

This works as verified by building and running the stdlib, and statically:

```
_sqrtf:
  00000000: 55                 push        ebp
  00000001: 89 E5              mov         ebp,esp
  00000003: 83 E4 F8           and         esp,0FFFFFFF8h
  00000006: 83 EC 18           sub         esp,18h
  00000009: F3 0F 10 45 08     movss       xmm0,dword ptr [ebp+8]
  0000000E: 66 0F 57 C9        xorpd       xmm1,xmm1
  00000012: F3 0F 5A C0        cvtss2sd    xmm0,xmm0
  00000016: 66 0F 2E C1        ucomisd     xmm0,xmm1
  0000001A: 72 06              jb          00000022
  0000001C: F2 0F 51 C0        sqrtsd      xmm0,xmm0
  00000020: EB 14              jmp         00000036
  00000022: F2 0F 11 04 24     movsd       mmword ptr [esp],xmm0
  00000027: E8 00 00 00 00     call        _sqrt
  0000002C: DD 5C 24 10        fstp        qword ptr [esp+10h]
  00000030: F2 0F 10 44 24 10  movsd       xmm0,mmword ptr [esp+10h]
  00000036: F2 0F 5A C0        cvtsd2ss    xmm0,xmm0
  0000003A: F3 0F 11 44 24 0C  movss       dword ptr [esp+0Ch],xmm0
  00000040: D9 44 24 0C        fld         dword ptr [esp+0Ch]
  00000044: 89 EC              mov         esp,ebp
  00000046: 5D                 pop         ebp
  00000047: C3                 ret
```

**Comment by stephentyrone** [comment]
We got _both_ kinds of square root, `sqrtsd` _and_ `call _sqrt`!

**Comment by compnerd** [comment]
I think that #35066 should be a better approach; closing if favor of that.

**Pull request closed without merging**
