### PR TITLE
[Dependency Scanning] Separate module output path from Clang scanner's module cache

### PR DESCRIPTION
**Pull request by artemcm**
- **Add option to specify a separate Clang Dependency scanner module cache.**
Clang dependency scanning produces scanner PCMs which we may want to live in a different filesystem location than the main build module cache.

-  **Specify Explicit Module output path to the scanner explicitly.**
Instead of the code querying the compiler's built-in Clang instance, refactor the dependency scanner to explicitly keep track of module output path. It is still set according to `-module-cache-path` as it has been prior to this change, but now the scanner can use a different module cache for scanning PCMs, as specified with `-clang-scanner-module-cache-path`, without affecting module output path.

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
@swift-ci test

**Review by xymus — APPROVED** [review]

**Review by nkcsgexi — APPROVED** [review]
Sounds like the global module cache dir is still a necessary evil.

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
@swift-ci test and merge

**Comment by artemcm** [comment]
@swift-ci test Linux platform

**Comment by artemcm** [comment]
@swift-ci test and merge

**Pull request merged**
