### PR TITLE
[Syntax] Fix roundtrip test

### PR DESCRIPTION
**Pull request by rintaro**
Previously, `Lexer` state hadn't been correctly restored beyond multiple `parseIntoSourceFile()` invocation. It used to result trivia loss between `TopLevelCodeDecl`.
This PR fixes that by holding exact `ParserPosition` (renamed from `Parser::ParserPosition`) in `PersistentParserState`.

Also, `utils/round-trip-syntax-test` used to always report "SUCCESS" because of a logic error in the script.

### CODE REVIEW

**Comment by rintaro** [comment]
@akyrtzi You introduced `PersistentParserState::ParserPos` in 803ba0e2be27c69707ebbf35e8e6d8a921b06a19.
Is there any particular reason *not* to hold Lexer state in `PersistentParserState`?

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by akyrtzi** [comment]
With the caveat that it's been a long time since I introduced that so I'm likely lacking a lot of context, I can't think of a reason.

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Pull request merged**
