### PR TITLE
[Sema] Do not attempt openning same generic argument twice while checking default parameter

### LINKED ISSUE #61061: (lib/Sema/ConstraintSystem.cpp) ConstraintSystem::openGenericParameter: Assertion `result.second' failed!
```swift 
struct S<T> where T:Hashable
{
    init(x:[[T: T]] = [:]) 
    {
    }
}
```

```
$ ~/.swiftenv/versions/DEVELOPMENT-SNAPSHOT-2022-09-10-a/usr/bin/swiftc test6.swift 
error: compile command failed due to signal 6 (use -v to see invocation)
swift-frontend: /home/build-user/swift/lib/Sema/ConstraintSystem.cpp:1742: swift::TypeVariableType *swift::constraints::ConstraintSystem::openGenericParameter(swift::DeclContext *, swift::GenericTypeParamType *, swift::constraints::OpenedTypeMap &, swift::constraints::ConstraintLocatorBuilder): Assertion `result.second' failed.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project and the crash backtrace.
Stack dump:
0.      Program arguments: /home/ec2-user/.swiftenv/versions/DEVELOPMENT-SNAPSHOT-2022-09-10-a/usr/bin/swift-frontend -frontend -c -primary-file test6.swift -target x86_64-unknown-linux-gnu -disable-objc-interop -color-diagnostics -new-driver-path /home/ec2-user/.swiftenv/versions/DEVELOPMENT-SNAPSHOT-2022-09-10-a/usr/bin/swift-driver -empty-abi-descriptor -resource-dir /home/ec2-user/.swiftenv/versions/DEVELOPMENT-SNAPSHOT-2022-09-10-a/usr/lib/swift -module-name test6 -o /tmp/TemporaryDirectory.KgVjGE/test6-1.o
1.      Swift version 5.8-dev (LLVM 6ad20b8df5a475e, Swift 005c9f340315004)
2.      Compiling with the current language version
3.      While evaluating request TypeCheckSourceFileRequest(source_file "test6.swift")
4.      While type-checking 'S' (at test6.swift:1:1)
5.      While type-checking 'init(x:)' (at test6.swift:3:5)
6.      While evaluating request DefaultArgumentExprRequest(test6.(file).S.init(x:).x@test6.swift:3:10)
```

i reproduced this on `DEVELOPMENT-SNAPSHOT-2022-09-10-a`, `DEVELOPMENT-SNAPSHOT-2022-09-06-a`, and `DEVELOPMENT-SNAPSHOT-2022-08-18-a`.

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
Use the already opened type variable for same generic argument instead of attempting to open it twice. 

Resolves https://github.com/apple/swift/issues/61061

### CODE REVIEW

**Review by xedin — APPROVED** [review]
Thank you, @LucianoPAlmeida!

**Comment by xedin** [comment]
@swift-ci please test

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test macOS platform

**Pull request merged**
