### PR TITLE
Desugar protocol compositions in extended types.

### PR DESCRIPTION
**Pull request by varungandhi-apple**
Resolves [SR-11227](https://bugs.swift.org/browse/SR-11227) and linked rdar://problem/53712389.

~~I just realized that we're not checking the recursive case ... I'll do that on Monday.~~ Done.

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test

**Comment by varungandhi-apple** [comment]
Couple of things:

1. Removing the call to `setType()` after `validateExtendedType()` (and threading `newExtendedType` through) leads to a bunch of crashes. I _could_ investigate why that is, but I'd rather not do that right now if I can get away with it.

2. The first commit is a bit too big... I'm not really sure how I could split it up into unrelated bits -- any advice would be appreciated.

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test

**Comment by jrose-apple** [comment]
:-/ This loses source information. Why are we desugaring again?

**Comment by varungandhi-apple** [comment]
There was a crash related to this because we weren't set up to handle compositions in extended types where we ended up just picking out the first protocol in the composition (see `ExtendedNominalRequest::evaluate` before this PR). @slavapestov suggested that I could implement a desugaring so that it works more generally, not just fixing the crash. There's a bunch of other cleanup which got mixed up here, so I'll open a separate PR for that.

Could you pinpoint where we're dropping source locations?

**Comment by jrose-apple** [comment]
It's not source *locations* that are dropped; it's the fact that the user wrote the extended type as a typealias. We do lose that information in some places to fix crashes, but we should be considering that a hack, not a desired state.

**Comment by slavapestov** [comment]
@varungandhi-apple means "desugaring" in the sense of turning `extension P1 & P2` into `extension P1 where Self : P2`, not "desugaring typealiases".

**Comment by jrose-apple** [comment]
Sure, but what if it was `extension P1AndP2`?

**Comment by jrose-apple** [comment]
To be clear, I'm not sure if we *want* to support that, or if we want to not bother preserving it, but we should be thinking about it explicitly.

**Comment by varungandhi-apple** [comment]
Closing this in favor of the new PR #27008 which does no desugaring.

**Pull request closed without merging**
