### PR TITLE
[IRGen] NFC: Add missing #include used by ref storage macros

### PR DESCRIPTION
**Pull request by davezarzycki**

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test and merge

**Comment by davezarzycki** [comment]
@swift-ci please smoke test linux

**Comment by compnerd** [comment]
The Foundation tests have been broken for ~1.5 days :-(

**Comment by davezarzycki** [comment]
@swift-ci please smoke test linux

**Comment by davezarzycki** [comment]
@swift-ci please smoke test linux

**Comment by davezarzycki** [comment]
@swift-ci please smoke test linux

**Pull request merged**
