### PR TITLE
Improve README: Add a notice to cd into swift directory before building Swift

### PR DESCRIPTION
**Pull request by agisilaos**
Today, I tried to build Swift for the first time and I had an issue. I couldn't build it because I was getting an error: `utils/build-script: No such file or directory`

Then when I was talking with @harlanhaskins he said that I need to `cd` into the swift directory first.

I didn't know that and I couldn't see that in the documentation. Even though for many experienced swift contributors that's something they know, for a newbie that's not the case.

With this PR I added a first step/ notice to the README file so newbies and first-time contributors like myself can have all the info that they need in front of them when they try to build Swift.

### CODE REVIEW

**Comment by agisilaos** [comment]
@swift-ci please smoke test

**Comment by harlanhaskins** [comment]
Hey Agis!

Thanks for adding this. Just for a heads up, CI privileges are not granted automatically, but only after you’ve shown a track record of good contributions. With that,

@swift-ci please smoke test

**Comment by harlanhaskins** [comment]
Taking a closer look, it seems earlier in the directions, we `cd swift-source` before running `./swift/utils/update-checkout`. Maybe instead of `cd swift-source/swift` this should just say `cd swift`?

**Comment by agisilaos** [comment]
@harlanhaskins I thought of that as well, but when it comes to documentation I "prefer" things to be dead simple. That's why I kept it like: `cd swift-source/swift`. I guess that's a personal preference so if you strongly dissagree, I can follow the pattern than you wrote above.

One of the edge cases I thought was: What if someone closes the terminal window and needs to cd again in the swift directory, where the swift directory is gonna be found?

Let me know if that makes sense or if it's complete nonsense and if I only think of such edge cases. 😂

**Comment by harlanhaskins** [comment]
Sorry for dropping this and picking it up just now. I'd like to think of the README as forming some sort of narrative, and we can assume that state changes like `cd swift-source/` and `cd swift/` are going to be stacked on top of each other. Otherwise, you can easily imagine someone trying to `cd swift-source/swift-source/swift`. These examples are kinda contrived, but I'd probably optimize for the single read through instead of the edge case you described.

**Comment by agisilaos** [comment]
@harlanhaskins Ready for review. ⭐️ Thank you for the detailed comment!

**Comment by harlanhaskins** [comment]
One last thing, before we merge, can you rebase your changes into one commit? We’d also prefer you not merge master back into your fork, and instead periodically rebase your fork onto master. It avoids the several merge commits. Once you do, I’ll run CI and merge!

**Comment by CodaFi** [comment]
Let's just take this and squash it down.

@swift-ci please smoke test

**Comment by CodaFi** [comment]
⛵️

**Comment by agisilaos** [comment]
Thanks @CodaFi. 🙌🏼

**Pull request merged**
