### PR TITLE
Upgrade some deprecation warnings from Swift 3 to errors in Swift 4.

### PR DESCRIPTION
**Pull request by huonw**
Fixes rdar://problem/28961650 .

Individual commits for relatively easy reverting, if necessary.

### CODE REVIEW

**Comment by huonw** [comment]
@swift-ci Please smoke test

**Comment by huonw** [comment]
@swift-ci Please Test Source Compatibility

**Comment by huonw** [comment]
Hm, I wonder if this should maybe go into swift-4.0-branch-2017-07-11 rather than swift-4.0-branch, since it's relatively safe from a code perspective but we may want more time to assess any downstream breakage?

**Comment by slavapestov** [comment]
LGTM

**Pull request merged**
