### PR TITLE
[SoruceKit] Audit SwiftASTManager to prevent deadlocks

### PR DESCRIPTION
**Pull request by ahoppen**
After fixing https://github.com/apple/swift/pull/42258, I re-audited `SwiftASTManager` to prevent any further deadlocks by further narrowing locks scopes and making sure that some callbacks are always called from a background queue that can’t have claimed any locks.

- Ensure that no callbacks are called when either of these mutexes are held:
  - `SwiftASTConsumer::CancellationRequestCallbackAndIsCancelledMtx`
  - `ASTBuildOperation::DependencyStampsMtx`
    - Exception: We allow calls to `getBuferStamp` because that doesn’t claim any locks)
    - No change was necessary here
  - `ASTBuildOperation::ConsumersAndResultMtx`
  - `ASTBuildOperation::CacheMtx`
    - No change was necessary here
  - `ASTBuildOperation::ScheduledConsumersMtx`
    - Make sure we always inform the consumers asynchronously, even if the operation was already cancelled when the consumer got enqueued by introducing `ConsumerNotificationQueue`
- Ensure that all callbacks to `SwiftASTConsumer` (i.e. `requestCancellation` and `handlePrimaryAST`, `failed`, `cancelled`) are performed asyncronously from a queue to avoid deadlocks

rdar://110357502

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by bnbarham** [comment]
That's a lot of mutexes, locks, and queues 😓 Changes seem okay, but in general this feels somewhat fragile. I do wonder if such fine grained locking is really worth it in these cases but since we already have it 🤷

**Review by bnbarham — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test Windows

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Review by rintaro — APPROVED** [review]

**Pull request merged**
