### PR TITLE
Remove previous hack for SR-5206

### PR DESCRIPTION
**Pull request by itaiferber**
**What's in this pull request?**
Better resolves [SR-5206](https://bugs.swift.org/browse/SR-5206) until the introduction of conditional conformance.

As a temporary workaround for SR-5206, certain Foundation types which had custom behavior in JSONEncoder and JSONDecoder [were granted special knowledge](https://github.com/apple/swift/pull/10818) of those types internally in order to preserve strategies on encode/decode.

This replaces that special knowledge with a more general-purpose fix that works for all types and all encoders/decoders.

Thanks to @norio-nomura for thinking of the approach on this.

### CODE REVIEW

**Comment by itaiferber** [comment]
@swift-ci Please test macOS

**Comment by itaiferber** [comment]
@swift-ci Please smoke test Linux

**Comment by itaiferber** [comment]
Mm. These `fileprivate` extensions are visible in accessibility checking, so are changing the errors that you'd get when you fail to inherit `init(from:)` from a superclass. Changing the parameter names to these initializers should prevent this.

**Comment by itaiferber** [comment]
@swift-ci Please test

**Comment by norio-nomura** [comment]
@itaiferber Can this change go to Swift 4.0.1?

**Comment by itaiferber** [comment]
@norio-nomura Unfortunately, the bar for inclusion into the next patch release is incredibly high, and this isn't considered a high enough priority item for inclusion. However, I believe I can get this pushed into the release after that.

**Comment by norio-nomura** [comment]
@itaiferber Thank you for your reply and information.🙏
I will look forward to that release.

**Comment by mathiasquintero** [comment]
Do we know if Xcode 9.1 will ship with a toolchain that includes this fix?

**Comment by itaiferber** [comment]
@mathiasquintero It should, yes.

**Comment by jrose-apple** [comment]
Ah, that's not correct. Xcode 9.1 contains the targeted fixes that went to swift-4.0-branch after the 4.0 release.

**Comment by itaiferber** [comment]
@mathiasquintero @jrose-apple Sorry! Misread that as "Swift 4.1" instead of "Xcode 9.1" — skimmed too quick. Jordan has the answer.

**Comment by mathiasquintero** [comment]
@jrose-apple @itaiferber but wasn't this later cherrypicked to that branch?

**Comment by jrose-apple** [comment]
Heh, I missed that too, but that cherry-pick was very recent. We can't promise that that'll make it into Xcode 9.1 rather than a possible later point release before we're ready for Swift 4.1.

**Comment by mathiasquintero** [comment]
Here's hoping for 4.0.2 ;)

**Pull request merged**
