### PR TITLE
[stdlib] Use subscript { _read } for UnsafeBuffer

### PR DESCRIPTION
**Pull request by airspeedswift**
Just for benchmarking for now.

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please benchmark

**Comment by airspeedswift** [comment]
@swift-ci please benchmark

**Comment by airspeedswift** [comment]
@swift-ci please benchmark

**Comment by airspeedswift** [comment]
@rjmccall @eeckstein  this one suggests noticeable regressions in -Onone, since `SortIntPyramid` is using `UnsafeMutableBufferPointer` to do the sorting, any reason for concern?

**Comment by eeckstein** [comment]
fine with me

**Comment by airspeedswift** [comment]
@swift-ci please test

**Pull request closed without merging**
