### PR TITLE
Add useful data description

### PR DESCRIPTION
**Pull request by LondonAtlas**
Updated the Data structure's "description" property to print out the bytes in the data structure instead of just printing how many bytes are in it. This is far more useful for debugging purposes over a byte count. Just printing the byte count is also a duplication of the actual property count which therefore makes the description property redundant.

@swift-ci Please smoke test

### CODE REVIEW

**Comment by xwu** [comment]
It looks like you'll have to rebase this PR. However, I have some concerns.

First, if this kind of output is useful for debugging, it should be in `debugDescription`, not `description` (which is potentially user-facing). I'd highly recommend making a change there.

Secondly, outputting the entire sequence of raw bytes is not, in general, useful output when `Data` can hold arbitrarily large amounts of data. You'll see that in the existing code `customMirror` only appends the sequence of bytes if `self.count < 64`. That would be a sensible default, I think, for something like `debugDescription` as well.

**Comment by parkera** [comment]
Can this PR be rebased so it shows just the changes requested?

**Comment by parkera** [comment]
Also, I agree with @xwu on this - the intention here was to have Data only output its content if it's a small size. Otherwise you could be stuck printing megabytes (or more) of content.

**Review by parkera — CHANGES_REQUESTED** [review]
As described above, please only print out if a small number of bytes.

**Comment by xwu** [comment]
I'd also add that I would find the number of bytes to be useful information in `description` whether or not the bytes are also printed; I see no reason to remove that from the description.

**Comment by karwa** [comment]
It would be nice if large Data instances could print out a snippet of their contents, rather than large amounts of data just printing a size and no snippet at all.

2 ideas from me:
- Printing first 64 bytes: you're not going to interpret lots of hex with your eyeballs. If the data has some kind of pattern to identify it, usually it will be a header pattern.
- Printing first 32 bytes + last 32 bytes: in case you're dealing with packets of data and there is some easily-identifiable pattern between the end of one packet and the start of another.

Plus the count, of course.

**Comment by CodaFi** [comment]
Because this has been inactive for a while I'm going to close it.  @LondonAtlas please feel free to reopen this (after a rebase)

**Pull request closed without merging**
