### PR TITLE
[Driver] -c with LTO should still emit bitcode

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by compnerd — APPROVED** [review]
I do wonder if we should use a mixture of different triples (Linux, Android, Windows, macOS, iOS) just to get some test coverage even though the code is target agnostic.

**Comment by CodaFi** [comment]
@davidungar @artemcm  Does this need to be fixed in the new driver?

**Comment by artemcm** [comment]
> @davidungar @artemcm Does this need to be fixed in the new driver?

Thanks for catching this. Yeah, I think it does.
https://github.com/apple/swift-driver/pull/410 should do the job.

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Pull request merged**
