### PR TITLE
gyb: use a stable hash for Syntax

### PR DESCRIPTION
**Pull request by compnerd**
This changes the hash from the Python `hash` function to SHA1.  Python 3
adopted SIP as the hashing algorithm which changed the hash results.  We
could no longer use a different python interpreter across the builds.  A
stable hashing algorithm allows easier migration.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @akyrtzi @nathawes

**Comment by compnerd** [comment]
@swift-ci please test

**Review by harlanhaskins — APPROVED** [review]

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-syntax#224

@swift-ci please test macOS platform

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-syntax#224

@swift-ci please test macOS platform

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-syntax#224

@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@akyrtzi any idea why there seems to be a diff on the hash?

**Comment by akyrtzi** [comment]
I don't know, is it different between python versions again?

**Comment by akyrtzi** [comment]
I got the same hash as the bot after applying this patch. I couldn't try python3 because I got
```
ModuleNotFoundError: No module named 'Child'
```
when running the degyb command in python3. Not sure why you got a different hash but if you are confident that python versions will not affect it you could apply the bot hash on your swift-syntax PR.

**Comment by compnerd** [comment]
I think that I had some old change laying around or something, rerunning does indeed give me the same hash.  Thanks @akyrtzi!

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-syntax#224

@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platfom

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@akyrtzi - seems that I will need some help to get this change merged, since I cannot merge the change on the swift-syntax repository :-(

**Pull request merged**
