### PR TITLE
Remove repetitive wording.

### PR DESCRIPTION
**Pull request by amartini51**
Fixes <rdar://59618453>

### CODE REVIEW

**Comment by amartini51** [comment]
@gottesmm I'm not 100% sure of the last piece of this change — do you use `ManagedBufferPointer` in addition to, or instead of `ManagedBuffer` when multiple classes are being used for storage?

**Comment by gottesmm** [comment]
@amartini51 I am not the person to review this change. I would ask one of the stdlib folks. I think that @lorentey would be a good one.

**Review by lorentey — APPROVED** [review]
👍

**Comment by lorentey** [comment]
@swift-ci smoke test

**Comment by amartini51** [comment]
@gottesmm Thanks. Looks like I can't remove you as a reviewer, but you can "dismiss" the request to review.

@lorentey I'm not 100% sure of the last piece of this change — do you use ManagedBufferPointer in addition to, or instead of ManagedBuffer when multiple classes are being used for storage?

**Comment by lorentey** [comment]
Ah -- `ManagedBufferPointer` does support wrapping classes that aren't `ManagedBuffer` subclasses, although this isn't exercised very often. (The big limitation is that such a class must have no stored properties.) 

(One use case for this is having all empty instances of a generic container type use the same type-punned empty singleton storage, no matter what the Element type is.)

**Comment by CodaFi** [comment]
@swift-ci smoke test Linux platform

**Pull request merged**
