### PR TITLE
build: indicate VC++ CRT type for Windows builds

### PR DESCRIPTION
**Pull request by compnerd**
Indicate whether the debug or release CRT is in use when building for
Windows.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by troughton** [comment]
Would it be better for the debug CRT to be conditional on `DEBUG`, since there are multiple types of release builds?

As a side note: is there actually a benefit to using the debug CRT? I know whatever the stdlib is linked against also becomes whatever Swift binaries/libraries that use that stdlib are linked against, but I’m not sure how useful its checks actually are for Swift code.

**Comment by compnerd** [comment]
It actually is useful, the debug CRT is able to actually do additional debugging (like malloc tracing).

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by troughton** [comment]
Is there a way to implement it so that the configuration of the built Swift product (e.g. with `swiftc -O` for release) determines which CRT is used? Is it possible to leave the CRT symbols unresolved for the stdlib and then link against it when linking the final Swift executable?

As an aside, I still think `RELEASE` is the wrong condition here. I could go either way on `RelWithDebInfo` builds, but I definitely think `MinSizeRel` should use the non-debug CRT.

**Pull request merged**
