### PR TITLE
[ConstraintSystem] Add same-type requirement fix/diagnostic

### PR DESCRIPTION
**Pull request by xedin**
Extend new requirement failure diagnostics by adding "same-type"
generic requirement failures.

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
Had to rebase after rvalue-to-lvalue changes went in

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
Going to merge in a couple of hours if nobody objects...

**Review by rudkx — APPROVED** [review]
LGTM!

**Pull request merged**
