### PR TITLE
[SwiftSyntax] Verify swift-syntax code gen

### PR DESCRIPTION
**Pull request by kimdv**
https://github.com/apple/swift-syntax/pull/1546

### CODE REVIEW

**Comment by kimdv** [comment]
https://github.com/apple/swift-syntax/pull/1546

@swift-ci please smoke test

**Comment by kimdv** [comment]
https://github.com/apple/swift-syntax/pull/1546

@swift-ci please smoke test

**Comment by kimdv** [comment]
@swift-ci please smoke test macOS

**Comment by kimdv** [comment]
@swift-ci please smoke test

**Review by ahoppen — APPROVED** [review]

**Pull request merged**
