### PR TITLE
AST: Remove some unnecessary getCanonicalType() calls

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by rjmccall** [comment]
It's quite a bit faster to do some of these manipulations on canonical types; getAs<> expands to a lot of code.  The queries on SILType, at least, seem like they ought to stay optimized.

**Comment by slavapestov** [comment]
Really? The set of operations that were "optimized" in this manner were completely arbitrary and the "optimized" getNominalParent() was even wrong.

I think we will get better performance wins by reworking the expression type checker and SIL optimizer, not hunting for small micro optimization like this.

**Comment by rjmccall** [comment]
Slava, micro performance isn't in opposition with macro performance.  And yes, we didn't have optimized access paths for literally everything; I don't see why that's an argument against having optimized access paths for anything.  You just seem to have launched onto a random crusade against getCanonicalType().

And how was getNominalParent() wrong?

**Comment by rjmccall** [comment]
@slavapestov and I talked about this, and I've submitted #8080 to revert most of these changes.

**Pull request merged**
