### PR TITLE
🛑Compiler support for synthesizing Hashable._hash(into:)

### PR DESCRIPTION
**Pull request by lorentey**
This improves compiler support for synthesizing `Hashable` implementations, to make use of the resilient hashing interface introduced by #14913. It removes the default implementation of `_hash(into:)`; the requirement is now automatically synthesized as needed.

Fully synthesized implementations of `Hashable` now generate a `_hash(into:)` implementation that does the actual work of hashing a type's components. They also add a `hashValue` implementation that simply instantiates a new hasher and feeds it to `_hash(into:)`. For example, here is how `Hashable` conformance is derived for a simple struct:

```swift
struct Book: Hashable {
  let title: String
  let authors: [Author]
  let pageCount: Int

  @derived var hashValue: Int { 
    return _hashValue(for: self) // defined in stdlib
  }
  @derived func _hash(into hasher: inout _Hasher) {
    hasher.append(title)
    hasher.append(authors)
    hasher.append(pageCount)
  }
}
```

This also enables partial synthesis: when exactly one of `hashValue` or `_hash(into:)` was explicitly provided, the compiler automatically synthesizes the other requirement. This works in all cases where `Hashable` conformance can be implemented: in structs, enums, classes or extensions.

### CODE REVIEW

**Comment by lorentey** [comment]
This is currently blocked by [SR-7156](https://bugs.swift.org/browse/SR-7156); in particular, vtable problems cause issues in swift-corelibs-foundation.

**Comment by lorentey** [comment]
@swift-ci smoke test

**Comment by lorentey** [comment]
@swift-ci smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test Linux

**Comment by slavapestov** [comment]
@lorentey I didn't realize the Codable vtable bug was blocking this work. I'll take a look at it soon.

**Comment by lorentey** [comment]
This is now incorporated into and superseded by #16073.

**Pull request closed without merging**
