### PR TITLE
Cleanup/fix AccessEnforcementOpts

### PR DESCRIPTION
**Pull request by atrick**
Simplify the analysis and dataflow to make the pass faster eliminate bugs as a side effect.

This is broken into a series of commits. The commit called "Redo the data flow" can't be reviewed as a diff. It's best just to read the new code, referencing the old code if it's helpful.

I'm posting this somewhat prematurely (I haven't done self-review or looked into adding more tests) so there is plenty of time for review. I don't plan on checking in until a week from now.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
@swift-ci test source compatibility.

**Comment by atrick** [comment]
@swift-ci benchmark.

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
@swift-ci test source compatibility.

**Comment by atrick** [comment]
@swift-ci test linux platform.

**Review by shajrawi — APPROVED** [review]
LGTM

**Pull request merged**
