### PR TITLE
[stdlib] Update one String initializer and client to use @_spi

### PR DESCRIPTION
**Pull request by xymus**
Let's try replacing an informal SPI comment with the `@_spi(Foundation)` attribute. The compiler will then enforce that only source files that explicitly import the standard library with its "Foundation" SPI will have access to this constructor.

The only client should be an indirection in Foundation. Still, if any clients see the following error they should instead use the initializer from Foundation `init(_ cocoaString: NSString)` or explicitly import the "Foundation" SPI with `@_spi(Foundation) import Swift`.

~~~
error: extraneous argument label '_cocoaString:' in call
    self = String(_cocoaString: cocoaString)
~~~

### CODE REVIEW

**Review by lorentey — APPROVED** [review]

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by xwu** [comment]
...How are people building the Swift Foundation overlay project with this in place? I can't test the overlay locally on my machine, and it doesn't appear that CI is actually building and testing the overlay over at swift-corelibs-foundation...

**Comment by xymus** [comment]
@xwu This SPI is available only in the binary swiftmodule interface of the stdlib. To use it make sure you build the clients with the same compiler that built the stdlib. This way the client compiler can read the binary swiftmodule interface and access the SPI.

This is by design, an SPI should be used only by targets that are part of the same project. In this case as most people build these libraries with build-script this should be automatic.

**Comment by xwu** [comment]
@xymus Understood, but this means that the Foundation overlay cannot be built with the toolchain shipped with Xcode. Meanwhile, swift-corelibs-foundation _must_ be built with the toolchain shipped with Xcode. The consequence, then, is that it’s impossible to work on changes to both projects in parallel (which indeed we should encourage in order to prevent them from falling out of sync), and that it’s not possible to test the Foundation overlay locally without building the entire toolchain. Can we revert this?

**Comment by nkcsgexi** [comment]
IIUC, reverting this temporarily won't remove the barriers immediately because the toolchain shipped with Xcode is already without this SPI in the stdlib.

**Comment by xwu** [comment]
Right, but it would make it possible to use future shipped toolchains to work on both implementations of the Foundation API simultaneously, and consideration for reinstating this PR (or, indeed, going further in adopting this more widely) when SR-12177 is addressed and Foundation contributors at that time can be advised to download a development toolchain.

**Comment by nkcsgexi** [comment]
@xymus It seems this init is the only Foundation SPI in the Swift standard library. Do we plan to add more `@_spi(Foundation)` in the future? If not, reverting it may be the right thing to do to remove the productivity barrier IMO.

**Comment by xymus** [comment]
@nkcsgexi I believe Foundation team is working on new features using other stdlib SPIs. If it has not already landed they may soon be using SPIs under a different group name. Reverting this one SPI is likely not enough even for a mid-term solution.

@xwu This change is pretty old, is there something else that changed recently for this to become a problem?

To be clear, using either a locally built toolchain or a dev toolchain from swift.org should give access to the SPI, only the Xcode toolchain doesn't have them (by design). A solution could be to publish the private swiftinterface of the stdlib aligned with the Xcode toolchain for manual installation for cases such as these. However, it feels to me like https://bugs.swift.org/browse/SR-12177 may the best thing to fix here.

**Comment by xwu** [comment]
@xymus There hasn't been any systematic attempt to keep the overlay in sync with the open-source project, with bugs fixed in one but not the other. I've resumed syncing up the `Decimal` implementations--which no one has tackled since this PR and the migration of the overlay to the other repository--and...it's a huge regression in the workflow. Two Xcode projects within the same repo that need to be maintained in sync really shouldn't require two distinct toolchains to compile locally, and right now the barrier is a single API or, alternatively, resolving SR-12177 which is of equal vintage. As there hasn't been any movement on that front, it'd be nice to make some headway here.

**Comment by nkcsgexi** [comment]
It seems adopting foundation-specific SPIs in the standard library does introduce some productivity barriers to OSS developers. What do you think? @kylemacomber @lorentey

**Pull request merged**
