### PR TITLE
Enable colors in FileCheck and Swift tests

### PR DESCRIPTION
**Pull request by hamishknight**
If we're attached to a tty, pass `--color` to FileCheck and `--color-diagnostics` to Swift invocations in tests.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please Python lint

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please Python lint

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please Python lint

**Review by gottesmm — COMMENTED** [review]
build-script changes LGTM

**Pull request merged**
