### PR TITLE
Unified the use of character and string sequences.

### PR DESCRIPTION
**Pull request by Nirma**
Thought this makes the intent a little clearer and makes the code read a little easier.

### CODE REVIEW

**Comment by cwillmor** [comment]
Is there any strong reason to go one way or the other? Expressions of the form `foo << 'a'` and `foo << "a"` are both pretty common in the Swift codebase (904 and 880 instances, respectively).

**Comment by Nirma** [comment]
@cwillmor Either way will work, but I was just thinking in terms of readability and making syntax usage uniform.
If the code is going to use single quote literals in one place and single characters written as double quote literals in another place its better perhaps to use one convention or the other.

**Comment by jckarter** [comment]
Printing a char is theoretically cheaper than printing a string, at least, though I imagine LLVM optimizes away the difference in many case.

**Comment by Nirma** [comment]
@cwillmor @jckarter Thanks for commenting!
Would there be any drawback to doing this change?

**Comment by lattner** [comment]
This is a legit (nano) optimization, merged.  Thanks!

**Pull request merged**
