### PR TITLE
[OSLog] Remove the dependency on `_Concurrency`

### PR DESCRIPTION
**Pull request by egorzhdan**
_Concurrency is not used in the module, and having it as a dependency causes a ninja error when trying to build stdlib without `-D SWIFT_ENABLE_EXPERIMENTAL_CONCURRENCY=YES`:

```
ninja: error: 'stdlib/private/OSLog/swift_Concurrency-swiftmodule-macosx-arm64', needed by 'stdlib/private/OSLog/OSX/arm64/OSLogTestHelper.o', missing and no known rule to make it
```

### CODE REVIEW

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Review by bro4all — APPROVED** [review]

**Review by zoecarver — APPROVED** [review]

**Comment by egorzhdan** [comment]
@swift-ci please build toolchain Linux platform

**Comment by egorzhdan** [comment]
@swift-ci please build toolchain Linux platform

**Comment by egorzhdan** [comment]
@swift-ci please build toolchain Linux platform

**Comment by egorzhdan** [comment]
The failure on Linux is unrelated, and this change only affects Darwin toolchains.

**Pull request merged**
