### PR TITLE
Kill ClosuresWithUncomputedCaptures and split off TypeCheckDeclPrimary.cpp from TypeCheckDecl.cpp

### PR DESCRIPTION
**Pull request by slavapestov**
This sits on top of https://github.com/apple/swift/pull/28367.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by shahmishal** [comment]
@swift-ci Please smoke test

**Comment by shahmishal** [comment]
@swift-ci Please test source compatibility

**Pull request merged**
