### PR TITLE
Use underscored syntax for versioned canImport condition

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by nkcsgexi** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Review by harlanhaskins — APPROVED** [review]
Thank you!

**Comment by nkcsgexi** [comment]
@swift-ci Please clean test Linux platform

**Pull request merged**
