### PR TITLE
Fix a non-deterministic load forwarding in RLE

### PR DESCRIPTION
**Pull request by trentxintong**
Depending on the order load forwarding is performed, we could end up with a different SIL.

### CODE REVIEW

**Comment by trentxintong** [comment]
@swift-ci Please test

**Comment by trentxintong** [comment]
@swift-ci Please benchmark

**Comment by trentxintong** [comment]
@eeckstein can you please review this patch ?

**Comment by trentxintong** [comment]
@swift-ci Please smoke test

**Comment by trentxintong** [comment]
@swift-ci Please benchmark

**Comment by trentxintong** [comment]
@swift-ci Please test

**Comment by eeckstein** [comment]
LGTM

**Comment by trentxintong** [comment]
@swift-ci Please test

**Pull request merged**
