### PR TITLE
[cxx-interop][5.9] windows ABI fixes

### LINKED ISSUE #66326: [cxx-interop] fix the C++ methods dispatch for the Windows target
Right now on Windows several C++ interop tests don't work as their methods aren't dispatched correctly. We need to fix it in Swift 5.9.

### PR DESCRIPTION
**Pull request by hyp**
[cxx-interop] Fix the windows ABI for returning indirect values out of methods
    
    Fixes https://github.com/apple/swift/issues/66326
    
    This allows us to reneable Windows method tests. Note that Windows still has
    a broken convention for non-trivial record with non-trivial destructor but
    trivial copy-constructor, so classes in the methods.swift test need an explicit
    copy constructor.
    
    Fixes rdar://88391102

[cxx-interop] Windows: unify address-only logic and mark non-trivial loadable C++ types as unavailable
    
    Windows logic for determining address-only type layout for a C++ type is now unified with other platforms.
    However, this means that on Windows, a C++ type with a custom destructor, but a default copy constructor
    is now loadable, even though it's non-trivial. Since Swift does not support such type operations at the
    moment (it can't be yet destroyed), mark such type as unavailable in Swift instead, when building for
    the Windows target.
    
    This fixes the Windows miscompilation related to such types when they were passed indirectly to C++
    functions even though they're actually passed directly.

- Explanation: 
Windows MSVC ABI  had two problems with IRGen for calls to C++:
1) Methods returning values indirectly had incorrect order between `this` and the returned value. This is now fixed, and we get the ordering right for the MSVC ABI.
2) Non-trivial but passed in registers types (MSVC ABI example - C++ class with destructor but default copy constructor) were incorrectly passed indirectly as we marked them as address-only. This patch now marks them loadable, which fixes that issue. However, we cannot yet support such types correctly semantically, as they can't be yet destroyed from Swift. Therefore, mark such types as unavailable on Windows to avoid missing C++ destructor calls from Swift.

- Scope: C++ interop, Clang importer, IRGen.
- Risk: Low, the affected code changes only affect the MSVC windows target, and only affect C++ imported types, not C.
- Testing: Unit tests.
- Original PR: https://github.com/apple/swift/pull/67268

### CODE REVIEW

**Comment by hyp** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]

**Comment by hyp** [comment]
@swift-ci please test windows platform

**Comment by hyp** [comment]
@swift-ci please test linux platform

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test source compatibility

**Pull request merged**
