### PR TITLE
[AST] Introduce hasTrailingClosure in ParenPattern and TuplePattern

### PR DESCRIPTION
**Pull request by rintaro**
This preserves more source information in AST.
Also, without that, `getEndLoc()` of these patterns cannot return correct value.

Fixes a crasher reported in #6883.
```swift
switch a {
  case .A(1) { 2 }: break
}
```
was failed with:
```
child source range not contained within its parent: 
  parent range: [test.swift:2:10 - line:2:12] RangeText="(1)"
  child range: [test.swift:2:14 - line:2:18] RangeText="{ 2 }"
```

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by practicalswift** [comment]
@rintaro Impressive turnaround time! Thanks! :-)

**Comment by jrose-apple** [comment]
Oh no. :-( Can we reject this in Swift 4 mode, at least?

**Comment by rintaro** [comment]
@jrose-apple You mean, reject trailing closures in Pattern position?

**Comment by jrose-apple** [comment]
That's supposed to be allowed for expression patterns, not pattern-patterns.

```swift
switch person {
case people.first { $0.isCEO }:
  print("oh, it's the CEO")
default:
  break
}
```

**Comment by rintaro** [comment]
@jrose-apple 
I'm not 100% sure if I've got what you mean, but I added diagnostics in the second commit.
Could you take a look?

**Comment by jrose-apple** [comment]
The point is that enum cases are supposed to be used for deconstruction when they're patterns, and it doesn't make sense to deconstruct into a closure. I'm not even sure we intended to allow trailing closures when *constructing* enum cases, but I guess that's useful for cases that consist of just a single enum.

@jckarter, thoughts?

**Comment by jckarter** [comment]
You could argue we should accept this on the principle that "a pattern should look like the expression that produces a matching value". This wouldn't ever really be useful for trailing closures, though, since function values have no equality concept you can really match by. I think a better fix would be to have `ResolvePattern` refuse to resolve a `TupleExpr` with a trailing closure as a pattern and leave it as an `ExprPattern`.

**Comment by rintaro** [comment]
> I think a better fix would be to have ResolvePattern refuse to resolve a TupleExpr with a trailing closure as a pattern and leave it as an ExprPattern.

I agree, but sadly, this introduces source breaking change in Swift3 mode.
```swift
enum E {
    struct S {
        let val: Int
        static func ~=(pattern: () -> Int, s: S) -> Bool {
            return pattern() == s.val
        }
    }
    
    case A(Int, S)
}

let e = E.A(12, E.S(val: 42))

switch e {
case E.A(12) { 42 }: print("matched")
default: break
}
```
In Xcode8/Swift3, this doesn't crash because, I guess, it doesn't have`ASTVerifier` pass,
and the pattern matches because the pattern is `EnumElementPattern` with *illformed* `TuplePattern`.

But if we leave it as `ExprPattern`, it would be no longer match because `E` is not `Equatable`.

What do you think?

**Comment by jckarter** [comment]
@rintaro We would have to judge based on how widespread the breakage is. Have you seen this in real code in the wild?

**Comment by rintaro** [comment]
@jckarter Never :)

**Comment by rintaro** [comment]
I've prepared "leave it as an ExprPattern" version here.
https://github.com/apple/swift/compare/master...rintaro:sem-pattern-trailingclosure

**Comment by practicalswift** [comment]
Is this one ready for merge? :-)

**Comment by CodaFi** [comment]
We have tools for this now!

@swift-ci please test source compatibility

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by jrose-apple** [comment]
Whoops, that failure is my and @erg's fault.

**Comment by CodaFi** [comment]
@swift-ci please test source compatibility

**Comment by CodaFi** [comment]
@swift-ci please test source compatibility

**Comment by CodaFi** [comment]
@rintaro We seem to handle all of these cases just fine.  Should I close this?

**Comment by rintaro** [comment]
Sure. Closing.

**Pull request closed without merging**
