### PR TITLE
Enable sourcekitd to be built by default on Linux

### PR DESCRIPTION
**Pull request by alblue**
The Linux build has a dependency on the libdispatch library,
which is needed by the various native libraries for sourcekitd.

On macOS, the dependency for libdispatch is satisfied directly through
the base OS, but on Linux no such dependency exists.

Modify this so that if the SourceKit library is built, and the
libdispatch library is already present, then we shell out to make
the libdispatch binary project when the SourceKit is built.

Issue: SR-1676

This is a resubmission of pull #5903 with an additional fix which should build the Ubuntu 14.04 platform. Since it is environment specific, I have tested it on an Ubuntu 14.04 image that I have used; but I don't know the exact environmental setup of the Ubuntu 14.04 CI bot is.

Resolves [SR-1676](https://bugs.swift.org/browse/SR-1676).

### CODE REVIEW

**Comment by RLovelett** [comment]
I've tried running this build locally and it does indeed generate the SourceKit files (e.g., `libsourcekitdInProc.so`).

Of course the question now is will this lead to those assets being distributed? When I run `utils/build-script --preset="buildbot_linux_1604" install_destdir="${SWIFT_INSTALL_DIR}" installable_package="${SWIFT_INSTALLABLE_PACKAGE}"` the resulting package does not contain anything SourceKit related.

Is that a follow on change or will we not be distributing that library?

**Comment by alblue** [comment]
Hmm. I will have to look into that; it would be sensible if it were distributed with the archives. 

Alex

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by alblue** [comment]
I think it would make sense to add an --install-libsourcekit command line option to the build script, and have that in place for the appropriate installs, similar to the way that --install-libdispatch works.

**Comment by alblue** [comment]
Thanks. Looks like it has kicked off this build for 14.04:

https://ci.swift.org/job/oss-swift-incremental-RA-linux-ubuntu-14_04/613/changes

**Comment by alblue** [comment]
Looks like it failed again - can you please revert?

Thanks,

Alex

**Comment by alblue** [comment]
Resubmitted change as pull #6858

**Pull request merged**
