### PR TITLE
[String] Drop many @inlinable annotations

### PR DESCRIPTION
**Pull request by milseman**
Drop append-related @inlinable annotations for String, StringGuts, StringStorage, and the Views. Drop several for larger operations, such as case conversion. Drop as many as we can from StringGuts for now.

Cleanup and remove init-from-CString inlinability

Streamline more String creation logic. Streamline and de-genericize non-inlinable internal functions to create a String from UTF-8 efficiently.

### CODE REVIEW

**Comment by milseman** [comment]
(fixing 32-bit as well).

@xedin, do you know why changes here could cause the test at https://ci.swift.org/job/swift-PR-Linux/4923/consoleFull#-1612600944ba62d58e-7248-467b-91e0-c7508d5cf947 to crash? Should I XFAIL it to unblock this?

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please smoke test compiler performance

**Comment by milseman** [comment]
@swift-ci please smoke benchmark

**Comment by slavapestov** [comment]
3.6% speedup in release builds is excellent!

Here's a fix for the XFAIL: https://github.com/apple/swift/pull/16587

**Pull request merged**
