### PR TITLE
test: require X86_64 for disable-availability-checking.swift

### PR DESCRIPTION
**Pull request by nkcsgexi**
rdar://80799638

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci Please test Apple Silicon macOS Platform

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by shahmishal** [comment]
```
17:24:09 Test Case '-[SwiftDriverTests.SwiftDriverTests testVerboseImmediateMode]' started.
17:24:09 /Users/buildnode/jenkins/workspace/swift-PR-macos-apple-silicon/branch-main/swift-tools-support-core/Sources/TSCBasic/Process.swift:825: error: -[SwiftDriverTests.SwiftDriverTests testVerboseImmediateMode] : failed: caught error: "signalled(11): /Users/buildnode/jenkins/workspace/swift-PR-macos-apple-silicon/branch-main/buildbot_incremental/swiftdriver-macosx-arm64/arm64-apple-macosx/release/swift-driver --driver-mode=swift -v /var/folders/ld/md151_257fldz2fn_bzqb5hm0000gp/T/TemporaryDirectory.Hp0OqT/ImmediateTest.swift output:
17:24:09     /Users/buildnode/jenkins/workspace/swift-PR-macos-apple-silicon/branch-main/buildbot_incremental/toolchain-macosx-arm64/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -interpret /var/folders/ld/md151_257fldz2fn_bzqb5hm0000gp/T/TemporaryDirectory.Hp0OqT/ImmediateTest.swift -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -resource-dir /Users/buildnode/jenkins/workspace/swift-PR-macos-apple-silicon/branch-main/buildbot_incremental/toolchain-macosx-arm64/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift -module-name ImmediateTest -target-sdk-version 11.1.0
17:24:09     Apple Swift version 5.5-dev (LLVM e39f186d725b6de, Swift aea6c3e079d6e2c)
17:24:09     Target: arm64-apple-macosx11.0
17:24:09     Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project and the crash backtrace.
17:24:09     Stack dump:
17:24:09     0.	Program arguments: /Users/buildnode/jenkins/workspace/swift-PR-macos-apple-silicon/branch-main/buildbot_incremental/toolchain-macosx-arm64/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -interpret /var/folders/ld/md151_257fldz2fn_bzqb5hm0000gp/T/TemporaryDirectory.Hp0OqT/ImmediateTest.swift -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -resource-dir /Users/buildnode/jenkins/workspace/swift-PR-macos-apple-silicon/branch-main/buildbot_incremental/toolchain-macosx-arm64/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift -module-name ImmediateTest -target-sdk-version 11.1.0
17:24:09     1.	Apple Swift version 5.5-dev (LLVM e39f186d725b6de, Swift aea6c3e079d6e2c)
17:24:09     2.	
17:24:09     3.	While running user code "/var/folders/ld/md151_257fldz2fn_bzqb5hm0000gp/T/TemporaryDirectory.Hp0OqT/ImmediateTest.swift"
17:24:09     Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
17:24:09     0  swift-frontend                  0x0000000108489108 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
17:24:09     1  swift-frontend                  0x00000001084880bc llvm::sys::RunSignalHandlers() + 128
17:24:09     2  swift-frontend                  0x0000000108489974 SignalHandler(int) + 292
17:24:09     3  libsystem_platform.dylib        0x00000001807e8c44 _sigtramp + 56
17:24:09     4  libsystem_platform.dylib        0x00000001106e2be8 _sigtramp + 18446744071829430236
17:24:09     5  libdyld.dylib                   0x00000001807acae8 dlsym + 204
17:24:09     6  libdyld.dylib                   0x000000018c371918 dlsym + 196890364
17:24:09     7  libdyld.dylib                   0x000000018c334614 dlsym + 196639736
17:24:09     8  libdyld.dylib                   0x000000018c36e708 dlsym + 196877548
17:24:09     9  libdyld.dylib                   0x000000018c354634 dlsym + 196770840
17:24:09     10 libdyld.dylib                   0x000000018c385fdc dlsym + 196974016
17:24:09     11 libdyld.dylib                   0x000000018c3847a8 dlsym + 196967820
17:24:09     12 libdyld.dylib                   0x000000018c384500 dlsym + 196967140
17:24:09     13 libdyld.dylib                   0x000000018c384c28 dlsym + 196968972
17:24:09     14 libdyld.dylib                   0x000000018c382094 dlsym + 196957816
17:24:09     15 libdyld.dylib                   0x000000018c3822d0 dlsym + 196958388
17:24:09     16 libswiftSwiftOnoneSupport.dylib 0x00000001bc8d2d40 __swift_instantiateConcreteTypeFromMangledName + 56
17:24:09     17 libswiftSwiftOnoneSupport.dylib 0x00000001106bc018 __swift_instantiateConcreteTypeFromMangledName + 18446744070821679888
17:24:09     18 swift-frontend                  0x00000001042c6364 llvm::orc::runAsMain(int (*)(int, char**), llvm::ArrayRef<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, llvm::Optional<llvm::StringRef>) + 1044
17:24:09     19 swift-frontend                  0x0000000104237b58 swift::RunImmediately(swift::CompilerInstance&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, swift::IRGenOptions const&, swift::SILOptions const&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule> >&&) + 6068
17:24:09     20 swift-frontend                  0x0000000104210578 performCompileStepsPostSILGen(swift::CompilerInstance&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule> >, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::PrimarySpecificPaths const&, int&, swift::FrontendObserver*) + 1208
17:24:09     21 swift-frontend                  0x000000010420ff04 bool llvm::function_ref<bool (swift::CompilerInstance&)>::callback_fn<performAction(swift::CompilerInstance&, int&, swift::FrontendObserver*)::$_19>(long, swift::CompilerInstance&) + 584
17:24:09     22 swift-frontend                  0x0000000104204af0 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 4168
17:24:09     23 swift-frontend                  0x00000001041b9274 swift::mainEntry(int, char const**) + 492
17:24:09     24 libdyld.dylib                   0x00000001807bcf34 start + 4
17:24:09     "
17:24:09 Test Case '-[SwiftDriverTests.SwiftDriverTests testVerboseImmediateMode]' failed (6.860 seconds).
```

**Comment by shahmishal** [comment]
@nkcsgexi is this related to your changes?

**Comment by nkcsgexi** [comment]
@shahmishal hmm, I don't think it's related.

**Pull request merged**
