### PR TITLE
Sema: Move code completion entry points to TypeCheckCodeCompletion.cpp

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Review by hborla — APPROVED** [review]
LGTM, thanks!

**Review by xedin — APPROVED** [review]
LGTM, thank you! It's good to have everything in one place. /cc @nathawes @rintaro

**Review by rintaro — APPROVED** [review]

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Comment by slavapestov** [comment]
@swift-ci Please clean smoke test macOS

**Pull request merged**
