### PR TITLE
Reflection: use `std::strtol` instead of `std::atoi`

### PR DESCRIPTION
**Pull request by compnerd**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

Address post-commit review comments from Harlan.  Use `std::strtol` as it can
deal with hex and octal inputs.

### CODE REVIEW

**Comment by gribozavr** [comment]
We don't care about hex and octal digits here, the code above makes sure the digits are only 0...9.  This code is parsing mangled names.

**Comment by compnerd** [comment]
Thats what I thought to (which is why I opted to use atoi).  @harlanhaskins asked for this change though.

**Comment by harlanhaskins** [comment]
I suggested it before seeing the validation beforehand. I suppose atoi is alright, but the lack of failure reporting in atoi raises a red flag

**Comment by compnerd** [comment]
@harlanhaskins okay, so whats the plan on this?  Are we happy with the code as is and this can be abandoned or do we want to pursue some changes here?

**Comment by harlanhaskins** [comment]
I'm hesitantly okay with this now. Sorry for stirring the pot.

**Comment by gribozavr** [comment]
I see the benefit in using `strtol` as long as we actually check the error code.

**Comment by compnerd** [comment]
@gribozavr updated with the error handling, but Im really not sure how much it buys us.  I did also remove an allocation, which can be nice, but, really, Im not convinced that it really is an improvement.  Note that it previously didnt have any error handling either.

**Comment by gribozavr** [comment]
@swift-ci Please test and merge

**Pull request merged**
