### PR TITLE
Fix the clang dependency of sourcekit libraries.

### PR DESCRIPTION
**Pull request by hjyamauchi**
Because swift_swap_compiler_if_needed updates the compiler ID to Clang, we need to account for it when deciding to add a dependencies on clang. Otherwise, the sourcekit build could fail due to lack of clang dependency.

### CODE REVIEW

**Comment by hjyamauchi** [comment]
@compnerd

**Review by compnerd — COMMENTED** [review]
We need to track if we need to add the dependency, if we are using clang to build, we won't be needing to swap and this might add a dependency on a just built clang that cannot be used.

**Comment by hjyamauchi** [comment]
> We need to track if we need to add the dependency, if we are using clang to build, we won't be needing to swap and this might add a dependency on a just built clang that cannot be used.

Done. PTAL.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Review by compnerd — APPROVED** [review]
I hope that one day we can remove these workarounds and build components without UB in the build system.

**Pull request merged**
