### PR TITLE
[Do not merge] testing PR

### PR DESCRIPTION
**Pull request by owenv**
Using this PR to debug the issues I've been having triggering CI

### CODE REVIEW

**Comment by owenv** [comment]
@swift-ci please smoke test

**Comment by owenv** [comment]
@swift-ci please test

**Comment by owenv** [comment]
@swift-ci please test

**Comment by owenv** [comment]
@shahmishal Sorry to bother you about this, but are there any public logs I might be able to use to debug the CI trigger? I've been consistently unable to use it since getting commit access to the repo. I thought it was due to an email discrepancy between my GitHub account and git config at first, but that doesn't seem to be the case.

**Comment by shahmishal** [comment]
Can you try again? it should be resolved now.

**Comment by owenv** [comment]
@swift-ci please smoke test

**Comment by owenv** [comment]
@shahmishal It looks like it triggered correctly, I'll monitor until it finishes and then close this. Thanks for your help!

**Pull request closed without merging**
