### PR TITLE
Fix the build by using %target-run and some other improvements

### PR DESCRIPTION
**Pull request by gottesmm**
Fix the build by using %target-run and some other improvements

rdar://36916944.

### CODE REVIEW

**Comment by gottesmm** [comment]
@jrose-apple Question. When I merged this same commit to swift-4.1, I did a full test which IIRC should test the simulator, do you know why this didn't fail there?

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
I am going to merge this to unblock internal bots. I am going to figure out in a bit why we aren't performing these tests publicly.

**Comment by jrose-apple** [comment]
Thanks, Michael. Not everything in validation-test/execution was a crasher. Please put those back.

**Pull request merged**
