### PR TITLE
[Serialization] Write in the binary swiftmodule file whether it was rebuilt from a swiftinterface

### PR DESCRIPTION
**Pull request by xymus**
Keep track of whether a swiftmodule was built from a swiftinterface or from source. This information will be used to change how the compiler deals with those dependencies.

Also tweak the fan favorite DESERIALIZATION FAILURE error message to add whether the swiftmodule was rebuilt and if it's library-evolution enabled.

Extracting this logic in this PR as it's used by both #61649 and #61765.

### CODE REVIEW

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Review by bnbarham — APPROVED** [review]

**Comment by xymus** [comment]
@swift-ci Please smoke test macOS

**Review by tshortli — APPROVED** [review]

**Comment by xymus** [comment]
@swift-ci Please smoke test macOS

**Comment by xymus** [comment]
@swift-ci Please smoke test macOS

**Pull request merged**
