### PR TITLE
[test/Syntax/round_trip_stdlib.swift] Exclude the test for an ASAN build

### PR DESCRIPTION
**Pull request by akyrtzi**
It is too slow, rdar://64215520

### CODE REVIEW

**Comment by akyrtzi** [comment]
@swift-ci smoke test and merge

**Comment by akyrtzi** [comment]
@swift-ci smoke test OS X platform

**Comment by gribozavr** [comment]
@akyrtzi Could you replace the internal radar with a public bug? Thanks!

**Comment by akyrtzi** [comment]
@shahmishal do you want to file a jira since you were the one that reported it?

**Pull request merged**
