### PR TITLE
Add -b flag to checkout

### PR DESCRIPTION
**Pull request by twof**
I think this is necessary to create a new branch

I'm going through the initial setup steps, and I think this step needs to be updated to include the -b flag so a new branch is checked out rather than checking out an existing branch, which devs won't yet have.

I don't think I should run CI here since it's a non-code change, but let me know if I should do it anyway. Thanks!

### CODE REVIEW

**Review by varungandhi-apple — APPROVED** [review]

**Comment by varungandhi-apple** [comment]
> I don't think I should run CI here since it's a non-code change, but let me know if I should do it anyway. Thanks!

You can't merge changes without CI barring exceptional cases; the CI has to pass before merging.

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test and merge

**Comment by twof** [comment]
ah thanks for letting me know!

**Comment by twof** [comment]
Did the `Test and Merge (smoke test)` not finish up? I can't see the details. https://ci.swift.org is giving me a 502

**Comment by twof** [comment]
Thanks!

**Pull request merged**
