### PR TITLE
[AutoDiff] Part 5: Add AdjointValue for efficient backpropagation through aggregates

### PR DESCRIPTION
**Pull request by rxwei**
Implement a symbolic adjoint value data structure for efficiently handling of aggregate adjoints. This will ensure that empty (`0`) adjoints never get emitted unless they have to.

For example, if the original program is
```
sil @foo : $(T) -> T {
bb0(%0 : $T):
  %1 = apply %f(%0) : $(T) -> T
  %2 = apply %g(%1) : $(T) -> (T, T)
  %3 = tuple_extract %2, 0
  return %3 : $T
}
```

Vanilla adjoint code emitted would be:
(Omitting bloated code for T.init() and builtin literal init, and assuming `f` and `g` are user-defined primitive `@differentiable` functions)
```
  %adj3 = <seed>
  %adj2 = tuple (%adj3, 0)
  %adj2_0 = tuple_extract %adj2, 0
  %adj1 = apply %adj_g(%1, %2, %adj2_0) : $(T, T, T) -> T
  %adj0 = apply %adj_f(%0, %1, %adj1) : $(T, T, T) -> T
  return %adj0 : %T
```

With staged `AdjointValue`, the code will be reduced down to:
```
  %adj3 = <seed>
  %adj1 = apply %adj_g(%1, %2, %adj3) : $(T, T, T) -> T
  %adj0 = apply %adj_f(%0, %1, %adj1) : $(T, T, T) -> T
  return %adj0 : %T
```

### CODE REVIEW

**Comment by rxwei** [comment]
Since the patch is small, I included some minor formatting changes.

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Review by dan-zheng — APPROVED** [review]

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
https://ci-external.swift.org/job/swift-PR-TensorFlow-Linux/422

**Review by lattner — COMMENTED** [review]
LGTM!

**Pull request merged**
