### PR TITLE
[Sema] Don’t fail constraint generation if a closure contains an ErrorExpr

### PR DESCRIPTION
**Pull request by ahoppen**
It appears like this was missed in #60062.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please SourceKit stress test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please SourceKit stress test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test Linux

**Review by xedin — APPROVED** [review]

**Pull request merged**
