### PR TITLE
[DNM] Test build.ps1 on VS2022 CI

### PR DESCRIPTION
**Pull request by tristanlabelle**
Testing https://github.com/apple/swift/pull/64948 on the `main-windows-vs2022` to see if the CI hits the same issues.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please build toolchain Windows platform

**Comment by tristanlabelle** [comment]
All projects' cloning fail with:
```
Cloning into 'swift-argument-parser'...
warning: Could not find remote branch main-windows-vs2022 to clone.
fatal: Remote branch main-windows-vs2022 not found in upstream origin
```
Should it be trying to checkout this branch name on all repos?

**Comment by compnerd** [comment]
@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Pull request closed without merging**
