### PR TITLE
Add no-assertions preset for Linux

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
preset=buildbot_linux,no_assertions
@swift-ci Please test with preset Linux Platform

**Comment by shahmishal** [comment]
@swift-ci test

**Review by tomerd — APPROVED** [review]

**Comment by shahmishal** [comment]
preset=buildbot_linux,no_assertions
@swift-ci Please test with preset Linux Platform

**Comment by shahmishal** [comment]
preset=buildbot_linux,no_assertions
@swift-ci Please test with preset Linux Platform

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
AutoDiff/validation-test/differentiable_protocol_requirements.swift

Is passing with assertions disabled, @rxwei is this expected?

**Comment by rxwei** [comment]
> AutoDiff/validation-test/differentiable_protocol_requirements.swift
> 
> Is passing with assertions disabled, @rxwei is this expected?

Hmm do you mean it's _failing_ with assertions disabled? https://ci.swift.org/job/swift-PR-Linux-preset/5/
It's unexpected, but it also doesn't appear to be failing:
```swift
******************** TEST 'Swift(linux-x86_64) :: AutoDiff/validation-test/differentiable_protocol_requirements.swift' FAILED ********************
Script:
--
: 'RUN: at line 1';   rm -rf "/home/build-user/build/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/AutoDiff/validation-test/Output/differentiable_protocol_requirements.swift.tmp" && mkdir -p "/home/build-user/build/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/AutoDiff/validation-test/Output/differentiable_protocol_requirements.swift.tmp" && /home/build-user/build/buildbot_linux/swift-linux-x86_64/bin/swiftc -target x86_64-unknown-linux-gnu -toolchain-stdlib-rpath  -module-cache-path /home/build-user/build/buildbot_linux/swift-linux-x86_64/swift-test-results/x86_64-unknown-linux-gnu/clang-module-cache -swift-version 4  -Xfrontend -define-availability -Xfrontend 'SwiftStdlib 9999:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999' -Xfrontend -define-availability -Xfrontend 'SwiftStdlib 5.0:macOS 10.14.4, iOS 12.2, watchOS 5.2, tvOS 12.2' -Xfrontend -define-availability -Xfrontend 'SwiftStdlib 5.1:macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0' -Xfrontend -define-availability -Xfrontend 'SwiftStdlib 5.2:macOS 10.15.4, iOS 13.4, watchOS 6.2, tvOS 13.4' -Xfrontend -define-availability -Xfrontend 'SwiftStdlib 5.3:macOS 11.0, iOS 14.0, watchOS 7.0, tvOS 14.0' -Xfrontend -define-availability -Xfrontend 'SwiftStdlib 5.4:macOS 11.3, iOS 14.5, watchOS 7.4, tvOS 14.5' -Xfrontend -define-availability -Xfrontend 'SwiftStdlib 5.5:macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0' -Xfrontend -define-availability -Xfrontend 'SwiftStdlib 5.6:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999' -O -module-cache-path /home/build-user/build/buildbot_linux/swift-linux-x86_64/swift-test-results/x86_64-unknown-linux-gnu/clang-module-cache /home/build-user/swift/test/AutoDiff/validation-test/differentiable_protocol_requirements.swift -o /home/build-user/build/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/AutoDiff/validation-test/Output/differentiable_protocol_requirements.swift.tmp/a.out -module-name main  && echo /home/build-user/build/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/AutoDiff/validation-test/Output/differentiable_protocol_requirements.swift.tmp/a.out && /usr/bin/env DYLD_LIBRARY_PATH='/home/build-user/build/buildbot_linux/swift-linux-x86_64/lib/swift/linux' LD_LIBRARY_PATH='/home/build-user/build/buildbot_linux/swift-linux-x86_64/lib/swift/linux:' SIMCTL_CHILD_DYLD_LIBRARY_PATH='/home/build-user/build/buildbot_linux/swift-linux-x86_64/lib/swift/linux'  /home/build-user/build/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/AutoDiff/validation-test/Output/differentiable_protocol_requirements.swift.tmp/a.out
--
Exit Code: 0

Command Output (stdout):
--
/home/build-user/build/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/AutoDiff/validation-test/Output/differentiable_protocol_requirements.swift.tmp/a.out
[ RUN      ] ProtocolRequirementDifferentiation.func
[       OK ] ProtocolRequirementDifferentiation.func
[ RUN      ] ProtocolRequirementDifferentiation.constructor, accessor, subscript
[       OK ] ProtocolRequirementDifferentiation.constructor, accessor, subscript
ProtocolRequirementDifferentiation: All tests passed

--
Command Output (stderr):
--
/home/build-user/swift/test/AutoDiff/validation-test/differentiable_protocol_requirements.swift:24:38: warning: redundant conformance constraint 'Self.TangentVector' : 'AdditiveArithmetic'
extension DiffReq where TangentVector: AdditiveArithmetic {
                                     ^

--
```

**Comment by shahmishal** [comment]
It's passing causing UPASS

**Comment by rxwei** [comment]
Oh it's XFAIL'd.  I think we can change the three XFAIL's to UNSUPPORTED.

**Comment by shahmishal** [comment]
preset=buildbot_linux,no_assertions
@swift-ci Please test with preset Linux Platform

**Comment by shahmishal** [comment]
@swift-ci test

**Pull request merged**
