### PR TITLE
AccessEnforcementOpts: Fix a bug that caused a compiler assert when dealing with nested scopes

### PR DESCRIPTION
**Pull request by shajrawi**
radar rdar://problem/48318054

### CODE REVIEW

**Comment by shajrawi** [comment]
@swift-ci Please test

**Comment by shajrawi** [comment]
@swift-ci Please test

**Comment by shajrawi** [comment]
@swift-ci Please test

**Comment by shajrawi** [comment]
@swift-ci Please test OS X

**Comment by shajrawi** [comment]
@swift-ci Please test OS X

**Comment by shajrawi** [comment]
@swift-ci Please smoke test OS X

**Comment by shajrawi** [comment]
@swift-ci Please smoke test OS X

**Comment by shajrawi** [comment]
@swift-ci Please test OS X

**Comment by shajrawi** [comment]
@swift-ci Please test OS X

**Comment by shahmishal** [comment]
@swift-ci Please test OS X

**Comment by shahmishal** [comment]
@swift-ci Please test OS X

**Comment by shahmishal** [comment]
@swift-ci Please test macOS

**Comment by shajrawi** [comment]
@swift-ci Please test

**Comment by shajrawi** [comment]
@swift-ci Please test

**Comment by shajrawi** [comment]
@swift-ci Please test

**Comment by shajrawi** [comment]
@swift-ci Please test

**Pull request merged**
