### PR TITLE
Xcode 14 beta 4 no longer supports iOS armv7, armv7s and i386 arch

### PR DESCRIPTION
**Pull request by shahmishal**
> Building iOS projects with deployment targets for the armv7, armv7s, and i386 architectures is no longer supported. (92831716)

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Review by edymtt — APPROVED** [review]

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test macOS

**Comment by shahmishal** [comment]
@swift-ci test Linux

**Review by drewmaxwell-apple — APPROVED** [review]
Looks like that's everything.

**Comment by jakepetroules** [comment]
Can you also:

- add arm64e to macOS, tvOS, watchOS
- add arm64 to watchOS

**Comment by shahmishal** [comment]
@jakepetroules Can you file an issue?

**Comment by jakepetroules** [comment]
> @jakepetroules Can you file an issue?

Done as #60382

**Pull request merged**
