### PR TITLE
Revert "[IRGen] Put 'ret void' instead of unreachable for non swiftasync cc"

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/swift#39680

I think that this might have regressed the Windows CI; the change itself is relevant to Windows as well as the TCO path in PEI is unsupported ATM :-(.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
CC: @DougGregor @kateinoigakukun

**Review by kateinoigakukun — APPROVED** [review]
For the record, `test/IRGen/async/hop_to_executor.sil` failed
https://ci-external.swift.org/job/oss-swift-windows-toolchain-x86_64-vs2019/439/console

**Comment by compnerd** [comment]
If #40448 passes (which it _should_ as I tested it locally), we should prefer that over this.  This just verified that this failure was caused by that change.

**Comment by DougGregor** [comment]
Windows passed with this revert, so that was the cause... but let's hope #40448 passes so we don't need this.

**Pull request closed without merging**
