### PR TITLE
[NFC] Remove bits and pieces referring to Ubuntu 14.04 LTS (Trusty Tahr)

### PR DESCRIPTION
**Pull request by varungandhi-apple**
Ubuntu 20.04 LTS is out now; the last version to support 14.04 was Swift 5.1,
so it is ok to delete this.

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test

**Review by shahmishal — APPROVED** [review]
Thanks!

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test Linux platform

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test Linux platform

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test Linux platform

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test Linux platform

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test Linux platform

**Pull request merged**
