### PR TITLE
Revert "[CSDiagnostics] Don't mention special names in requirement diagnostics"

### PR DESCRIPTION
**Pull request by xedin**
Reverts apple/swift#19447

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@jrose-apple Maybe this is not actually worth reverting because note is going to point to declaration in question, with one caveat - if it's implicit initializer it would point to the type where requirement was declared...

**Comment by jrose-apple** [comment]
In plenty of contexts notes might not be displayed without clicking into an error, and in the case of Xcode they're often not displayed at all today. :-( The main error should be informative without having to do that.

If you want to clean up the obviously useless cases, you could say "if there's a special name and zero or one unlabeled parameters" as your condition or something.

**Comment by xedin** [comment]
Sure, that makes sense, I'll change the condition to only print names if they have at least one label instead of reverting.

**Comment by xedin** [comment]
Talked to Jordan offline, and it seems like better option here would be to enable empty label printing for special names, which would make `initializer 'init'` be printed as `initializer 'init(_:)'`, so I'm going to revert my changes and do it another way...

**Pull request merged**
