### PR TITLE
Request-ify TypeChecker::computeCaptures()

### PR DESCRIPTION
**Pull request by slavapestov**
We now compute captures of functions, closures and default arguments lazily, instead of as a side effect of primary file checking.

This fixes a specific issue with the `-experimental-skip-*` flags, where functions declared after a top-level `guard` statement are considered to have local captures, but nothing was forcing these captures to be computed.

Fixes rdar://problem/125981663.

### CODE REVIEW

**Review by tshortli — APPROVED** [review]
Nice!

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Pull request merged**
