### PR TITLE
[silgen] Ensure that cleanup cloner clones formal access cleanups to formal access cleanups.

### PR DESCRIPTION
**Pull request by gottesmm**
This has been a long standing issue that we have been hacking around in various
points in SILGen. Now CleanupCloner just does the right thing.

I was unable to cause any issues to pop up in tree (since I believe we hacked
around this and converged on correctness). But it does come up in combination
with new code in https://github.com/apple/swift/pull/31779.

rdar://63514765

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test source compatibilité

**Comment by gottesmm** [comment]
@swift-ci test windows platform

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Review by atrick — APPROVED** [review]
Thanks for fixing this!

**Comment by gottesmm** [comment]
The source compatibility failure is a known unrelated failure.

**Pull request merged**
