### PR TITLE
[Autodiff] Adds logic to generate specialized functions in the closure-spec pass

### PR DESCRIPTION
**Pull request by jkshtj**
Approved in [this](https://github.com/jkshtj/swift/pull/1#pullrequestreview-2051950876 ) PR. 

PR to merge into Swift main branch.

### CODE REVIEW

**Comment by jkshtj** [comment]
@swift-ci please test

**Comment by jkshtj** [comment]
@eeckstein could I get a quick approval on this?

**Review by eeckstein — APPROVED** [review]
lgtm!

**Comment by jkshtj** [comment]
@swift-ci please test

**Comment by jkshtj** [comment]
@swift-ci please test

**Comment by jkshtj** [comment]
@swift-ci  please test

**Comment by jkshtj** [comment]
@shahmishal swift-ci seems to be broken.

**Comment by shahmishal** [comment]
@jkshtj Do you have commit access to swift repo?

**Comment by jkshtj** [comment]
> @jkshtj Do you have commit access to swift repo?

I do

**Comment by shahmishal** [comment]
I see the trigger comment has a extra space: 
Screenshot 2024-05-13 at 2 39 01 PM

**Comment by jkshtj** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
Fixed the issue with Windows trigger by adding you to the allow list.

**Comment by shahmishal** [comment]
@swift-ci test Windows

**Comment by jkshtj** [comment]
> I see the trigger comment has a extra space:

Ah, I'm sorry for the mistake. Looks like that was it. 

Is there a way to make these swift-ci invocations agnostic to certain cosmetic things - capitalization, spaces etc.?

**Comment by jkshtj** [comment]
@swift-ci please test

**Comment by jkshtj** [comment]
@swift-ci please test linux

**Comment by jkshtj** [comment]
@swift-ci please test macos and Windows

**Comment by jkshtj** [comment]
@swift-ci please test

**Comment by jkshtj** [comment]
@swift-ci test Windows

**Pull request merged**
