### PR TITLE
Honor #sourceLocation filenames in serialized diagnostics

### PR DESCRIPTION
**Pull request by jrose-apple**
I'm not sure why we never handled this. Oops.

rdar://problem/43647151

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Review by CodaFi — APPROVED** [review]
LGTM.  Could you add a short test that uses -vfsoverlay in a follow-up?

**Review by DougGregor — APPROVED** [review]
Woah. How did we miss this for so long?

**Comment by jrose-apple** [comment]
[Source compat run here](
https://ci.swift.org/job/swift-PR-source-compat-suite/1775/)

@CodaFi How's this version?

@swift-ci Please test

**Comment by CodaFi** [comment]
Looks great, thanks!

**Comment by jrose-apple** [comment]
@swift-ci Please test Linux

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Review by davidungar — APPROVED** [review]
I don't really know enough about virtual files. What other places where we use `getIdentifierForBuffer`  should be changed?

**Comment by jrose-apple** [comment]
> What other places where we use `getIdentifierForBuffer` should be changed?

Good question, and I feel bad for not thinking of it. I found a few more and I'll fix them in a follow-up PR.

**Comment by CodaFi** [comment]
> What other places where we use getIdentifierForBuffer should be changed?

Probably 

```
SILGenFunction::emitSourceLocationArgs
GroupNameCollectorFromJson::getGroupNameInternal
MappingTraits<SourceLoc>::mapping
```

**Comment by davidungar** [comment]
Tx. Hmmm...How about adding to the Doxygen comment to `getDisplayNameForLocation` and/or `getIdentifierForBuffer` explaining when it is appropriate to call one instead of the other? I'm worried that a future developer might add code calling the wrong one.

**Pull request merged**
