### PR TITLE
IRGen: Initialize single case enum extrainhabitant value witness in generated code

### PR DESCRIPTION
**Pull request by aschwaighofer**
Older Swift runtimes miss this initialization in the swift_initEnumMetadataSingleCase runtime call.

rdar://49786768

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
Compiler fix for https://github.com/apple/swift/pull/24278

**Comment by bob-wilson** [comment]
Should we do this conditionally based on the deployment target or is it cheap enough to just do it all the time?

**Comment by aschwaighofer** [comment]
Cheap: This is a single load/store that is executed only once per type initialization (once per program run) of a single case enum type.

We could conditionalize this on a deployment target in the future. I don’t know that we have deployment target support plumped through the compiler. It would not be worth to do it for this.

**Comment by bob-wilson** [comment]
OK, that sounds fine then.

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test os x

**Comment by aschwaighofer** [comment]
@swift-ci Please test os x

**Pull request merged**
