### PR TITLE
FreeBSD build support

### PR DESCRIPTION
**Pull request by jamesamcl**
This patch extends the build script to support FreeBSD.

### CODE REVIEW

**Comment by fuxx** [comment]
:cool:

**Comment by aviflax** [comment]
:fireworks:

**Comment by leogiertz** [comment]
🦄

**Comment by GuillaumeBibaut** [comment]
awesome! want! :+1:

**Comment by krememek** [comment]
There is currently no active testing for FreeBSD support (obviously), so as interest in a FreeBSD port grows it would be good to see some automated testing come up.  I'm fine with taking these kind of changes to facilitate incremental development of a port as long as they don't break support for other platforms.  Note that because there is no active support for FreeBSD others in the community may innocently break support for FreeBSD (such as it is) at any time until there is some automated testing.  We expect to unleash some continuous integration testing for Swift.org very soon, but obviously it won't include FreeBSD immediately since there has been no work on that port.

**Comment by krememek** [comment]
I'm accepting this; if this breaks building/testing on other platforms I will back this change out.

**Comment by rgrinberg** [comment]
:100:

**Comment by fuxx** [comment]
:+1: * :100:

**Comment by hamzasheikh** [comment]
@krememek How soon will @udp (or other contributors') name be added to https://swift.org/CONTRIBUTORS.txt? Will it be done as part of this repo or outside of it?

**Comment by udp** [comment]
@hamzasheikh - not sure why you singled out my PR but I didn't write a patch so I could be listed as a contributor.  I'm watching this repo and the volume of "typo" pull requests coming in is ridiculous - can't believe people are this determined to get anything into the repository.

**Comment by papertigers** [comment]
@udp were you able to successfully compile with the build script changes? I got an error still

**Comment by udp** [comment]
@papertigers Not yet, I'm still working on it.  This was just a first step really.

**Comment by stass** [comment]
>  We expect to unleash some continuous integration testing for Swift.org very soon, but obviously it won't include FreeBSD immediately since there has been no work on that port.

I'm curious, what is needed to get this going?  Is any code help needed, or is it just a matter of putting all the necessary things in place?

**Comment by her** [comment]
yes 😍

**Pull request merged**
