### PR TITLE
[6.0] Implement pack element reference captures

### PR DESCRIPTION
**Pull request by slavapestov**
6.0 cherry-pick of https://github.com/apple/swift/pull/74020 and @xedin's https://github.com/apple/swift/pull/73849.

**Description:** Builds upon https://github.com/apple/swift/pull/73541 to implement the missing cases involving closures appearing inside pack expansion expressions.

**Scope of the issue:** A very commonly reported bug.

**Origination:** This never worked.

**Risk:** Low. This re-purposes existing code for capturing OpaqueValueExprs, which arises up in property wrapper lowering. Now closures track captures of PackElementExprs in the same way.

**Reviewed:** @hborla @rjmccall 

**Radar:** rdar://110711746, rdar://119212867, rdar://124202697.

### CODE REVIEW

**Review by hborla — APPROVED** [review]

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Pull request merged**
