### PR TITLE
[ConsumeObjectChecker] End lifetimes at consumes.

### PR DESCRIPTION
**Pull request by nate-chandler**
The checker already verifies that no non-destroy consuming users occur after any `move_value`s corresponding to `consume` operators applied to a value.  There may, however, be _destroy_ users after it.

Previously, the checker did not shorten the lifetime from those destroys (i.e. those that appear after those `move_value`s) up to `move_value`s.  The result was that the value's lifetime didn't end at the `consume`.

Here, the checker is fixed to rewrite the lifetimes so that they both end at `consume`s and also maintain their lexical lifetimes on paths away from the `consume`s.  This is done by using `OwnedValueCanonicalization`/`CanonicalizeOSSALifetime`.

Specifically, it passes the `move_value`s that correspond to source-level `consume`s as the `lexicalLifetimeEnds` to the canonicalizer.  Typically, the canonicalizer retracts the lexical lifetime of the value from its destroys.  When these `move_value`s are specified, however, instead it retracts them from the lifetime boundary obtained by maximizing the lifetime within its original lifetime while maintaining the property that the lifetime ends at those `move_value`s.

rdar://113142446

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Comment by nate-chandler** [comment]
please test with following pull request:
https://github.com/apple/llvm-project/pull/8836

@swift-ci please test

**Review by atrick — APPROVED** [review]
This fills in a major missing part of the design. Thanks!

**Pull request merged**
