### PR TITLE
[ConstraintSystem] Infer some of the bindings attributes on demand

### PR DESCRIPTION
**Pull request by xedin**
One step closer to being able to make potential binding inference incremental.

Let's make most of the flags in `PotentialBindings` be computed on demand based
on information captured in the bindings, including:

- `IsHole` - could be determined based on a presence of a single binding to a hole type;
- `NumDefaultableBindings` - just a number of bindings originated in defaultable constraint;
- `IsPotentiallyIncomplete` - determined based on bindings and locator;
- `SubtypeOfExistentialType` - determined based on recorded bindings;

Most of the flags here are only used for ranking and recorded in a `BindingScore`
so don't have to be re-computed multiple times.

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Comment by xedin** [comment]
@nkcsgexi @artemcm Linux CI is failing with:

```
/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/swift-driver/Tests/SwiftDriverTests/IncrementalCompilationTests.swift:15:18: error: module 'SwiftDriver' was not compiled for testing
19:20:48 @testable import SwiftDriver
19:20:48 ~~~~~~~~~~       ^
```

**Comment by artemcm** [comment]
> @nkcsgexi @artemcm Linux CI is failing with:
> 
> ```
> /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/swift-driver/Tests/SwiftDriverTests/IncrementalCompilationTests.swift:15:18: error: module 'SwiftDriver' was not compiled for testing
> 19:20:48 @testable import SwiftDriver
> 19:20:48 ~~~~~~~~~~       ^
> ```

Investigating! Thanks.

**Comment by xedin** [comment]
@swift-ci please test

**Review by hborla — APPROVED** [review]
Nice!

**Pull request merged**
