### PR TITLE
[overlay] Rename scheduleOneShot and scheduleRepeating

### PR DESCRIPTION
**Pull request by moiseev**
rdar://29587696

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by ianpartridge** [comment]
Hi @moiseev this change needs making in `swift-corelibs-libdispatch` too. Are you going to do that or would you like me to open a PR?

**Comment by moiseev** [comment]
Good catch, @ianpartridge ! /cc @ktopley-apple.

**Comment by moiseev** [comment]
@ianpartridge, normally changes would be applied to both the overlay here as well as xcorelibs-lilbdispatch, but for some reason this change was not. Turns out there is work going on that will make them in sync again. So, yes, this change will be applied to xcorelibs by the Dispatch team. Thanks for pointing it out!

**Comment by ianpartridge** [comment]
OK @moiseev - I'll look out for the commit on `swift-corelibs-foundation`. Thanks for looking into it.

**Pull request merged**
