### PR TITLE
Minor fixes (proposal)

### PR DESCRIPTION
**Pull request by kant**
For the sake of clarity and understanding.

It does not resolve any bug.

### CODE REVIEW

**Comment by CodaFi** [comment]
I’m not sure the code voice is correct, but the capitalization of ‘Ninja’ is.

**Comment by krilnon** [comment]
It should just say "Xcode", not "Xcode.app" or "`Xcode.app`".

**Comment by xwu** [comment]
...and user interface text is properly shown in quotation marks, not code voice.

**Comment by CodaFi** [comment]
Superseded by the merge of #13481.

**Pull request closed without merging**
