### PR TITLE
test: repair the prespecialized-metadata tests on ASi

### PR DESCRIPTION
**Pull request by compnerd**
Introduce `llvm_src_root` and `llvm_obj_root` to mirror `swift_src_root`
and `swift_obj_root`.  This allows us to repair the paths used in the
tests without having to hardcode the build layout into the tests.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @nate-chandler @drexin

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by nate-chandler** [comment]
Neat!

**Review by drexin — APPROVED** [review]
LGTM

**Pull request merged**
