### PR TITLE
Stop using -sil-serialize-all when building the standard library

### PR DESCRIPTION
**Pull request by swiftix**
We can finally get rid of `-sil-serialize-all` when building the standard library! This option will be completely eliminated in the future commits.

Instead of serializing just everything as we did before, we now serialize only functions annotated with `@_inlineable`. This way we can selectively control what needs to be available to the clients. This is an important step towards building a resilient standard library.

While this is a huge change for the serialization of the stdlib, it should be virtually invisible to the clients. For example, there are no noticeable performance regressions on any of the benchmarks.

Big thanks to @moiseev, who annotated the whole library with `@_inlineable` attributes.

### CODE REVIEW

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please smoke benchmark

**Comment by swiftix** [comment]
@swift-ci Please Test Source Compatibility

**Comment by slavapestov** [comment]
Oops:

```
*swift::GenericCloner::initCloned(swift::SILFunction *, swift::IsSerialized_t, const swift::ReabstractionInfo &, llvm::StringRef): Assertion `(!Serialized || Orig->isSerialized()) && "Specialization cannot make body more resilient"' failed.
```

**Comment by swiftix** [comment]
Yeah, I'm looking into it. I was testing with the no-asserts compiler and haven't noticed it locally. Should be easy to fix though

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by swiftix** [comment]
@swift-ci please clean test

**Comment by aciidb0mb3r** [comment]
Disabled the failing test while I investigate the underlying issue in swiftpm's test configuration: 

https://github.com/apple/swift-package-manager/pull/1351

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by swiftix** [comment]
@swift-ci Please Test Source Compatibility

**Comment by swiftix** [comment]
@swift-ci Please Test Source Compatibility

**Comment by swiftix** [comment]
@swift-ci please smoke benchmark

**Comment by swiftix** [comment]
@swift-ci Please Test Source Compatibility

**Comment by swiftix** [comment]
@swift-ci please smoke benchmark

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by swiftix** [comment]
Source Compatibility Suite failures are unrelated.

**Comment by gottesmm** [comment]
Congrats!

**Comment by eeckstein** [comment]
That's really awesome!

**Pull request merged**
