### PR TITLE
[NFC] Drop More Type Checkers

### PR DESCRIPTION
**Pull request by CodaFi**
Drop TypeCheckers out of 

- Typo Correction
- Sequence folding
- Pattern checking
- A bunch of expression checking
- DeclRef building
- Pattern resolution
- Access enforcement
- Exportability

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Review by slavapestov — APPROVED** [review]

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
⛵️

**Pull request merged**
