### PR TITLE
[sil-opt] Fix covering all-case of trapping instruction of SILInstruction::mayTrap

### PR DESCRIPTION
**Pull request by freddi-kit**
Hi, I found that the function which checking trapping SIL instruction may have an issue, so I want to fix by this PR.
(moved from https://github.com/apple/swift/pull/33830 to fix commit comment)

# Abstract
Making `SILInstruction:: mayTrap ` covering all cases of trapping instruction.

# Issue
Having no issue-report

# Description
It seems that `SILInstruction::mayTrap()` is checking that the instruction may trap or not. 

And, according to the [sil.rst](https://github.com/apple/swift/blob/master/docs/SIL.rst#checked-conversions), there are 4 instruction may trap (runtime-failure). 

- `cond_fail`
- `unconditional_checked_cast`
- `unconditional_checked_cast_addr`
- `unconditional_checked_cast_value`

ref: https://github.com/apple/swift/blob/master/docs/SIL.rst#cond_fail and https://github.com/apple/swift/blob/master/docs/SIL.rst#checked-conversions 

However, `unconditional_checked_cast_value` is missed on `mayTrap ` case in current implementation so this commit added it to cover all-case.

This missing case has a risk to remove instruction which should be marked as side-effect, on like Dead Code Elimination, so should be fixed

### CODE REVIEW

**Comment by freddi-kit** [comment]
If the current one is correct, I think it would be better to add some comments of it, what do you think?

**Review by eeckstein — CHANGES_REQUESTED** [review]
Can you add a test case in https://github.com/apple/swift/blob/master/test/SILOptimizer/side-effect.sil
As an example, see the test function "sil @checkedcast".

Otherwise LGTM!

**Comment by freddi-kit** [comment]
Oh, sorry for not adding test, let me add it! 👍

**Comment by freddi-kit** [comment]
@eeckstein Added test of `unconditional_checked_cast_value` with missing `unconditional_checked_cast_addr`. 

 
If no `unconditional_checked_cast_addr` in mayTrap, test result is `<func=r,param0=>`. But now it will be `<func=r,param0=;trap>` to show it as trap. Please check it.

**Review by eeckstein — APPROVED** [review]
LGTM, thanks!

**Comment by freddi-kit** [comment]
Thank you for reviewing

**Comment by freddi-kit** [comment]
@swift-ci please test

**Comment by freddi-kit** [comment]
Should I run test?

**Comment by theblixguy** [comment]
@swift-ci please test

**Comment by theblixguy** [comment]
@swift-ci please test macOS

**Comment by theblixguy** [comment]
@swift-ci please test Windows

**Comment by theblixguy** [comment]
@swift-ci please test macOS

**Comment by theblixguy** [comment]
macOS failure should be fixed once https://github.com/apple/swift-package-manager/pull/2924 is merged.

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Pull request merged**
