### PR TITLE
Reverse the order of improvements in the output of compare_perf_tests

### PR DESCRIPTION
**Pull request by moiseev**
Both regressions and improvements are sorted by the delta, which in case
of improvements produces the reversed order due to negative values of
delta.
This change makes the improvements ordered 'naturally':
most-improved-first.

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by shahmishal** [comment]
@swift-ci Please smoke Benchmark

**Review by shahmishal — APPROVED** [review]

**Comment by moiseev** [comment]
Sorry, @shahmishal , can you review it again =) I've added a couple more changes based on @swiftix's input.

**Comment by moiseev** [comment]
@swift-ci Please smoke benchmark

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by shahmishal** [comment]
LGTM! 
@swift-ci Please smoke benchmark

**Comment by moiseev** [comment]
@swift-ci Please smoke test Linux platform

**Comment by moiseev** [comment]
@swift-ci Please smoke test and merge

**Comment by moiseev** [comment]
@swift-ci Please smoke test and merge

**Comment by moiseev** [comment]
@swift-ci Please smoke test and merge

**Comment by moiseev** [comment]
@swift-ci Please smoke test and merge

**Comment by palimondo** [comment]
@moiseev This change messes up the HTML output. It also incorrectly partitions results into groups (I can give you my log files where 5.8% delta lands in No Change section). 
CC @shahmishal, @gottesmm @atrick 

Could we please, instead of doing a partial fix, just land my PR #8991 instead?
I don't support the @atrick's use case of accepting merged (appended) outputs from multiple  `Benchmark_Driver` runs, but I'll fix that later.

**Comment by moiseev** [comment]
@palimondo oh, I did not know anyone was working on this. Sorry. You definitely spent more time looking at this script than I.

**Pull request merged**
