### PR TITLE
[crashers] Remove 91 fixed crashers that lack explicit Apache license text [WIP - removal might not be needed!]

### PR DESCRIPTION
**Pull request by practicalswift**
#### What's in this pull request?

This is a follow up to PR #1646.

/cc @tkremenek + @lattner 

Prior to this commit:

```
$ git grep -E '[^a-zA-Z]MIT[^a-zA-Z]' | grep /compiler_crashers_fixed/ | wc -l
76
(+ 15 without the "MIT" string)
$ ls validation-test/compiler_crashers_fixed/*.swift | wc -l
5083
```

After this commit:

```
$ git grep -E '[^a-zA-Z]MIT[^a-zA-Z]' | grep /compiler_crashers_fixed/ | wc -l
0
$ ls validation-test/compiler_crashers_fixed/*.swift | wc -l
5007
```

After this commit there are six (6) crashers (non-fixed, non-fuzzing, not written by me) left that lack an explicit Apache license. These are:

```
* validation-test/compiler_crashers/24245-swift-constraints-constraintsystem-solve.swift
* validation-test/compiler_crashers/24798-no-stacktrace.swift
* validation-test/compiler_crashers/25962-swift-archetypebuilder-getallarchetypes.swift
* validation-test/compiler_crashers/26303-llvm-llvm-unreachable-internal.swift
* validation-test/compiler_crashers/26813-generic-enum-tuple-optional-payload.swift
* validation-test/compiler_crashers/28180-rawrepresentable-extension-with-initializer.swift
```

Before deleting them I'd like to try to find fuzzing crash cases triggering the same crash locations as those.

I have a very large set of unpublished fuzzing crash cases that haven't been submitted for inclusion due to being "crash location duplicates" of other crash cases already in the repo. Hopefully I can find such independently discovered functionally equivalent crash cases ("duplicates") that can replace those five remaining mentioned above. I'll try doing so during the weekend.
#### Resolved bug number: –

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by tkremenek** [comment]
@practicalswift Thank you for working on this!  Since this is a WIP pull request, do you want to add "WIP" in the subject?  It sounds like you are looking for substitute tests before we remove these ones.

**Comment by lattner** [comment]
The typical way we handle this is to try to contact the contributor of the test, to see if they're ok with relicensing.  Is there any way to find out where these came from?

**Comment by practicalswift** [comment]
@tkremenek This PR is not WIP actually :-)

This commit only touches on `validation-test/compiler_crashers_fixed/` and since these crashes are already fixed it would be quite hard to find substitutes for those.

So this PR simply deletes the 91 already fixed crash cases in  `validation-test/compiler_crashers_fixed/` which lack an explicit Apache license header.

The part you're referring to as WIP is probably the remaining 6 non-fuzzing crashes in `validation-test/compiler_crashers/` which lack an explicit Apache license header . These are of higher value since they are crashing current `swiftc`. Those six cases are not touched upon by this PR. They will be taken care of in an upcoming PR :-)

So this PR is ready to go if you're okay it :-)

**Comment by practicalswift** [comment]
@lattner That would be even better! I'll compile a list :-)

**Comment by lattner** [comment]
Thank you @practicalswift, you continue to be amazing!

**Comment by practicalswift** [comment]
@lattner:

These are skilled compiler crash finders that discovered the (now fixed) crash cases in `validation-test/compiler_crashers_fixed/`: @0xc010d, @AlexDenisov, @PartiallyFinite, @airspeedswift, @allu22 @benshan (2 cases), @codafi, @fluidsonic (7 cases), @jansabbe, @jtbandes (2 cases), @julasamer, @jvasileff (2 cases), @lerno, @martijnwalraven, @mattdaw, @mayoff, @neilpa, @owensd, @radex, @rnapier (2 cases), @robrix (6 cases), @tenderlove, @tmu (4 cases), @valfer, @zats and @zneak :-)

* `00006-swift-mangle-mangler-manglecontext.swift` is written by @AlexDenisov
* `00007-convenience-init-in-extension.swift` is written by @0xc010d
* `00012-emitdirecttypemetadataref.swift` is written by @robrix
* `00017-llvm-foldingset-llvm-attributesetnode-nodeequals.swift` is written by @jvasileff
* `00018-swift-irgen-emitpolymorphicarguments.swift` is written by @owensd
* `00024-emitdirecttypemetadataref.swift` is written by @robrix
* `00025-no-stacktrace.swift` is written by @robrix
* `00027-void-map-over-sequence.swift` is written by @tmu
* `00029-class-with-anyobject-type-constraint.swift` is written by @jansabbe
* `00030-string-as-extensibe-collection.script.swift` is written by @tmu
* `00036-szone-malloc-should-clear.swift` is written by @tenderlove
* `00039-string-join.script.swift` is written by @tmu
* `00040-std-function-func-swift-constraints-solution-computesubstitutions.swift` is written by @tmu
* `00043-substdependenttypes.swift` is written by @jvasileff
* `00047-emitdirecttypemetadataref.swift` is written by @robrix
* `00048-no-stacktrace.random.runtime.swift` is written by @lerno
* `00049-swift-nominaltypedecl-getmembers.swift` is written by @rnapier
* `00051-resolvetypedecl.swift` is written by @rnapier
* `00052-no-stacktrace.swift` is written by @robrix
* `00053-std-function-func-swift-type-subst.swift` is written by @julasamer
* `00239-swiftdeclconverter-importconstructor.swift` is written by @fluidsonic
* `00240-argemitter-emitexpanded.swift` is written by @fluidsonic
* `00241-swift-lowering-typeconverter-getconstantinfo.swift` is written by @fluidsonic
* `00242-swift-lowering-silgenfunction-emitclosurevalue.swift` is written by @fluidsonic
* `00272-llvm-irbuilder-createcall.swift` is written by @fluidsonic
* `00323-swift-apply-generic-protocol.swift` is written by @valfer
* `00324-swift-shortcircuit-isequal.swift` is written by @martijnwalraven
* `01340-llvm-getelementptrinst-getindexedtype.swift` is written by @fluidsonic
* `01341-broken-function-found-compilation-aborted.swift` is written by @fluidsonic
* `01647-no-stacktrace.swift` is written by @radex
* `01956-method-declared-to-return-its-own-name.swift` is written by @mayoff
* `02257-swift-any-from-nsmutablearray.swift` is written by @mattdaw
* `22725-swift-constraints-constraintsystem-solvesimplified.swift` is written by @robrix
* `24797-no-stacktrace.swift` is written by @neilpa
* `24879-getmemberforbasetype.swift` is written by @zneak
* `24887-no-stack-trace.swift` is written by @codafi
* `26298-llvm-densemapbase.swift` is written by @airspeedswift
* `27818-swift-astvisitor.swift` is written by @zats
* `28182-anonymous-namespace-favorcalloverloads.swift` is written by @jtbandes
* `28183-swift-typebase-isequal.swift` is written by @jtbandes
* `28184-swift-constraints-constraintsystem-gettypeofmemberreference.swift` is written by @benshan
* `28185-llvm-foldingset-swift-genericfunctiontype-nodeequals.swift` is written by @benshan
* `28186-swift-silwitnessvisitor-visitprotocoldecl.swift` is written by @PartiallyFinite
* `28187-llvm-foldingset-swift-constraints-constraintlocator.swift` is written by @allu22

**Comment by owensd** [comment]
I'm perfectly fine with my test being re-licensed.

**Comment by jansabbe** [comment]
Sure, you can re-license my test as well.

**Comment by practicalswift** [comment]
@lattner These crash cases in `validation-test/compiler_crashers_fixed/` are backed by Radar/OpenRadar reports:

* `00001-swift-typeloc-iserror.swift` - rdar://17157251
* `00010-circular-protocol-reference.swift` - rdar://18061131
* `00012-emitdirecttypemetadataref.swift` - rdar://17822208
* `00013-llvm-getelementptrinst-getindexedtype.swift` - rdar://17359448
* `00014-enum-in-generic-type.swift` - rdar://17330553
* `00015-no-stacktrace.swift` - rdar://17225563
* `00016-swift-typebase-getcanonicaltype.swift` - rdar://18405200
* `00019-llvm-instvisitor.swift` - rdar://17929884
* `00019-llvm-instvisitor.swift` - rdar://17557409 (same?)
* `00023-getcallerdefaultarg.swift` - rdar://18041799
* `00024-emitdirecttypemetadataref.swift` - rdar://17662010
* `00025-no-stacktrace.swift` - rdar://17501507
* `00027-void-map-over-sequence.swift` - rdar://18118173
* `00031-no-stacktrace.swift` - rdar://17240590
* `00032-swift-irgen-irgenfunction-emittypemetadataref.swift` - rdar://17240737
* `00033-error.swift` - rdar://17240924
* `00034-swift-typebase-getcanonicaltype.swift` - rdar://17242441
* `00035-cerror.swift` - rdar://17242486
* `00038-hang-on-init-of-recursive-generic-type.timeout.swift` - rdar://18072376
* `00039-string-join.script.swift` - rdar://18174611
* `00040-std-function-func-swift-constraints-solution-computesubstitutions.swift` - rdar://18175202
* `00041-szone-malloc-should-clear.swift` - rdar://18176436
* `00042-nested-pattern-match-with-type-cast.timeout.swift` - rdar://17970286
* `00045-swift-lowering-adjustfunctiontype.swift` - rdar://17317691
* `00046-any-array-containing-ints.repl.swift` - rdar://17916262
* `00047-emitdirecttypemetadataref.swift` - rdar://18248167
* `00050-protocols-with-circular-typealiases.swift` - rdar://17986597
* `00052-no-stacktrace.swift` - rdar://18332184
* `00054-swift-substitutedtype-get.swift` - rdar://18349699
* `00055-no-stacktrace.swift` - rdar://18734297
* `00226-swift-lowering-silgenfunction-emitcurrythunk.swift` - rdar://18456545
* `00243-transform-transform.swift` - rdar://18495979
* `00322-swift-mangle-mangler-manglenominaltype.swift` - rdar://18637242
* `00324-swift-shortcircuit-isequal.swift` - rdar://18662915
* `00325-global-is-external.swift` - rdar://18678220
* `00326-llvm-constantexpr-getgetelementptr.swift` - rdar://18633758
* `01338-undefined-symbols-for-architecture.swift` - rdar://18706056
* `01339-phi-node-operands-not-same-as-result.swift` - rdar://18756378
* `01647-no-stacktrace.swift` - rdar://18851497
* `01648-global-is-external.swift` - rdar://18850296
* `22725-swift-constraints-constraintsystem-solvesimplified.swift` - rdar://19343997
* `23639-llvm-jit-runfunction.runtime.swift` - rdar://19423783
* `24797-no-stacktrace.swift` - rdar://20220559
* `26296-duplicate-subscript-declaration.swift` - rdar://22007370
* `27818-swift-astvisitor.swift` - rdar://22917580
* `28182-anonymous-namespace-favorcalloverloads.swift` - rdar://23719809
* `28183-swift-typebase-isequal.swift` - rdar://23720006

**Comment by practicalswift** [comment]
And for the six remaining non-fixed crash cases (in `validation-test/compiler_crashers/`), these are the skilled compiler crash finders that discovered the issues: @robrix, @neilpa, @adocyn, @airspeedswift, @austinzheng and @deville.

* `24245-swift-constraints-constraintsystem-solve.swift` is written by @robrix
* `24798-no-stacktrace.swift` is written by @neilpa
* `25962-swift-archetypebuilder-getallarchetypes.swift` is written by @adocyn
* `26303-llvm-llvm-unreachable-internal.swift` is written by @airspeedswift
* `26813-generic-enum-tuple-optional-payload.swift` is written by @austinzheng
* `28180-rawrepresentable-extension-with-initializer.swift` is written by @deville

**Comment by fluidsonic** [comment]
Feel free to re-license my contributions here if necessary.

**Comment by robrix** [comment]
Likewise, feel free to re-license any crashers I’ve submitted.

**Comment by austinzheng** [comment]
I give permission for any tests I've contributed to be re-licensed. Please let me know if any further action is required from me to make this happen.

**Comment by rnapier** [comment]
Please relicense my contributions as required.

**Comment by jtbandes** [comment]
I'm also happy for my contributions to be re-licensed as necessary!

**Comment by jvasileff** [comment]
Please relicense my contributions as necessary.

**Comment by AlexDenisov** [comment]
I'm fine, go ahead and relicense if needed.

**Comment by CodaFi** [comment]
Please, relicense as needed.

**Comment by benshan** [comment]
Please relicense my contributions as needed.

**Comment by mattdaw** [comment]
Please relicense my contributions as needed.

**Comment by PartiallyFinite** [comment]
Please relicense my contributions as needed.

**Comment by tenderlove** [comment]
Please re-license my code as needed. Thanks.

--
Aaron Patterson
http://tenderlovemaking.com/
I'm on an iPhone so I apologize for top posting.

**Comment by zneak** [comment]
You can re-license my code as needed.

Félix

**Comment by radex** [comment]
I'm also good with relicensing :)

**Comment by 0xc010d** [comment]
Please relicense my contribution as needed.

**Comment by deville** [comment]
Feel free to relicense my contribution as well.

**Comment by julasamer** [comment]
Please relicense my contribution as needed as well.

**Comment by martijnwalraven** [comment]
Feel free to relicense the test I contributed as necessary.

**Comment by neilpa** [comment]
You can relicense my contributed test.

**Comment by valfer** [comment]
You can relicense my contributed test.

**Comment by practicalswift** [comment]
Oh, somehow missed:

* `00023-getcallerdefaultarg.swift` (now fixed) issue found by @stigi

Sorry about that.

**Comment by airspeedswift** [comment]
Fine to relicense my test code.

**Comment by stigi** [comment]
Please feel free to relicense my contributions in `00023-getcallerdefaultarg.swift` as needed.

**Comment by tmu** [comment]
Greetings from Finland, my contributions can also be relicensed

- 00027-void-map-over-sequence.swift
- 00030-string-as-extensibe-collection.script.swift
- 00039-string-join.script.swift
- 00040-std-function-func-swift-constraints-solution-computesubstitutions.swift

**Comment by adocyn** [comment]
Please relicense my contributions as required.

**Comment by allu22** [comment]
Feel free to relicense my contribution as well.

**Pull request closed without merging**
