### PR TITLE
Unique synthesized foreign type witnesses and make witness tables part of the metadata cache key

### PR DESCRIPTION
**Pull request by aschwaighofer**
rdar://24958043

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
What do you mean by "witnesses"?

**Comment by aschwaighofer** [comment]
Witness tables

**Comment by slavapestov** [comment]
Can you clarify that in the commits/comments? When I first saw that the "witnesses" were part of the uniquing key, I thought you meant the witness thunk function pointers themselves, which would be quite odd :)

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test os x

**Comment by aschwaighofer** [comment]
@swift-ci Please test source compatibility

**Comment by aschwaighofer** [comment]
@swift-ci Please test source compatibility

**Comment by aschwaighofer** [comment]
Source compatibility run: https://ci.swift.org/view/Pull%20Request/job/swift-PR-source-compat-suite/1206/

**Pull request merged**
