### PR TITLE
[libSyntax] Support parsing type-identifier

### PR DESCRIPTION
**Pull request by rintaro**
CC: @nkcsgexi 

* The first commit is for split token.
  Previously, the split token was always tokenized as `tok::oper_binary_unspaced`.
  We wan't to specify the kind of token.
* The second commit is the main commit on this PR.
  It uses `SyntaxBuilder` for building libSyntax nodes.

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Review by nkcsgexi — APPROVED** [review]
LGTM!

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Pull request merged**
