### PR TITLE
[Stdlib] Remove SwiftPrivate's dependency on Darwin.

### PR DESCRIPTION
**Pull request by mikeash**
Revert #20194, which seems to be more trouble than it's worth. Instead, move the functions that SwiftPrivate needs back into LibcShims.h/cpp as SPI.

rdar://problem/45817565

### CODE REVIEW

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test Linux platform

**Comment by mikeash** [comment]
@swift-ci please test Linux platform

**Pull request merged**
