### PR TITLE
[5.0] Use clang's effective llvm triple for IR generation

### PR DESCRIPTION
**Pull request by aschwaighofer**
Instead of using the target that was passed to the driver. Use the target from
the clang importer that might have been changed by clang (i.e armv7 to thumbv7
on darwin)

rdar://32599805

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
Same failure as on the incremental bot without this change:

https://ci.swift.org/view/swift-5.0-branch/job/oss-swift-5.0-incremental-RA-linux-ubuntu-16_10/224/consoleFull#-11440285893122a513-f36a-4c87-8ed7-cbc36a1ec144

**Comment by aschwaighofer** [comment]
@swift-ci Please test linux

**Comment by xedin** [comment]
@aschwaighofer There is a known issue with Linux + 5.0 branch which this hits, do you want me to force merge this changes?

**Pull request merged**
