### PR TITLE
[AutoDiff] TF-19: Perform activity analysis on all types.

### PR DESCRIPTION
**Pull request by rxwei**
(This is based on #22828 by @pschuh with additional changes.)

This allows generating warnings in cases like: `Float(Int(x))` and other such cases.

Note that this may break some existing semantics by being stricter. In these cases you can work around it by tagging the function `@_semantics("autodiff.nonvarying")`.

The user-facing form of this is `Differentiable.withoutDerivative()`.

Resolves [TF-19](https://bugs.swift.org/browse/TF-19) and [TF-164](https://bugs.swift.org/browse/TF-164).

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Review by dan-zheng — APPROVED** [review]
LGTM

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Pull request merged**
