### PR TITLE
ExistentialSpecializer Test Case

### PR DESCRIPTION
**Pull request by rajbarik**
Test case for ExistentialSpecializer https://github.com/apple/swift/pull/13991/

### CODE REVIEW

**Comment by rajbarik** [comment]
@slavapestov This is the test case for testing ExistentialSpecializer.

**Comment by slavapestov** [comment]
This should be part of the other PR.

**Comment by rajbarik** [comment]
Thanks @slavapestov. Will merge.

**Comment by slavapestov** [comment]
@rajbarik asked me to close

**Pull request closed without merging**
