### PR TITLE
Add a --no-test option to build-toolchain

### PR DESCRIPTION
**Pull request by aschwaighofer**
Builds a toolchain without running tests on macos.

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test and merge

**Comment by jrose-apple** [comment]
Is this better than just changing the default? @shahmishal

**Comment by aschwaighofer** [comment]
Changing the default will need to be synchronized with the bot setups and needs to be done by folks in charge of those. This is better than not having the option at all.

I agree with you otherwise that we could just do what we do on linux: change the default and use the ``--test`` option.

**Comment by shahmishal** [comment]
‘build-toolchain’ is not used in CI, however people in the community might be using it to build toolchain for other platform.

**Comment by aschwaighofer** [comment]
@shahmishal On linux the default is to build the toolchain in the no_test preset. Only on macOS we build the preset that tests. On linux you have to add ``--test`` if you want the preset with tests.

I can change the behavior on macOS to mirror what we do on linux if that won't break CI (as you suggest) and folks are okay with that change.

**Pull request merged**
