### PR TITLE
Move gradients from stdlib to swift-apis

### PR DESCRIPTION
**Pull request by tanmayb123**
As discussed in https://github.com/tensorflow/swift-apis/issues/53, this PR will move operations from the standard library to "swift-apis" https://github.com/tensorflow/swift-apis/pull/63

### CODE REVIEW

**Comment by rxwei** [comment]
Great. Please also make sure to move the op definition in Ops.swift and tests in TensorFlowRuntime/test/*.swift.

**Comment by tanmayb123** [comment]
Yep - coming in another PR.

**Comment by rxwei** [comment]
It needs to be in this PR because CI has to pass.

**Comment by rxwei** [comment]
You can also copy things over to swift-apis and merge things there first. That makes sure we don't lose APIs or break things during the process.

**Comment by tanmayb123** [comment]
I've already submitted that PR: https://github.com/tensorflow/swift-apis/pull/63

**Comment by tanmayb123** [comment]
I'm closing this PR, I'll create a new one with other changes.

**Pull request closed without merging**
