### PR TITLE
Revert 1e3de357: XFAIL TSAN Tests on AS Hosts

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please test Apple Silicon macOS platform

**Comment by CodaFi** [comment]
Looks like the issue persisted

```
/Users/buildnode/jenkins/workspace/swift-PR-macos-apple-silicon/branch-main/swift/test/Sanitizers/tsan.swift:75:11: error: CHECK: expected string not found in input
14:44:21 // CHECK: ThreadSanitizer: data race
14:44:21           ^
14:44:21 <stdin>:1:1: note: scanning from here
14:44:21 ThreadSanitizer: unsupported vm address limit 0x800000000000, expected 0x000fc0000000.
14:44:21 ^
14:44:21 
14:44:21 Input file: <stdin>
14:44:21 Check file: /Users/buildnode/jenkins/workspace/swift-PR-macos-apple-silicon/branch-main/swift/test/Sanitizers/tsan.swift
14:44:21 
14:44:21 -dump-input=help explains the following input dump.
14:44:21 
14:44:21 Input was:
14:44:21 <<<<<<
14:44:21           1: ThreadSanitizer: unsupported vm address limit 0x800000000000, expected 0x000fc0000000.
14:44:21 check:75     X~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ error: no match found
14:44:21 >>>>>>
14:44:21 
```

**Comment by kubamracek** [comment]
I think that's expected — I did not merge the fix into 20210107, <https://github.com/apple/llvm-project/pull/2637>.

**Comment by kubamracek** [comment]
@swift-ci please test Apple Silicon macOS platform

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci test

**Review by CodaFi — APPROVED** [review]

**Comment by jckarter** [comment]
Force-merging this because these tests are UPASS-ing on the CI bots and the failures in PR testing are unrelated.

**Pull request merged**
