### PR TITLE
[test] Fix a DebugInfo test

### PR DESCRIPTION
**Pull request by moiseev**
A test fix missing from https://github.com/apple/swift/pull/11598

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please test macOS

**Comment by moiseev** [comment]
@swift-ci Please smoke test Linux

**Comment by adrian-prantl** [comment]
Thanks! LGTM. I thought I had a similar PR yesterday, but perhaps I forgot to merge it!?

**Comment by moiseev** [comment]
@adrian-prantl ahh, found it! https://github.com/apple/swift/pull/11611 tests passed, I'll merge yours. Thanks!

**Pull request closed without merging**
