### PR TITLE
Don't re-force member loading in already-forced class hierarchies

### PR DESCRIPTION
**Pull request by CodaFi**
When deserializing a the (named) members of a class hierarchy, we
needn't walk all the way up the hierarchy, just into our superclass.
This will, in turn, walk to its superclass, etc.  This is as opposed to
this work being repeated at each level of the recursive hierarchy.
Should be a small perf win over the last patch.

Resolves rdar://57882571 and SR-11949

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please test source compatibility

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please test source compatibility

**Comment by CodaFi** [comment]
@swift-ci please test source compatibility

**Comment by CodaFi** [comment]
@swift-ci please clean smoke test macOS platform

**Comment by xedin** [comment]
Looks like there is a test failure:
```
16:16:06     Swift(macosx-x86_64) :: NameBinding/named_lazy_member_loading_objc_interface.swift
```

**Comment by CodaFi** [comment]
Cool, least we know this fixes source compatibility.

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
⛵️

**Pull request merged**
