### PR TITLE
[interop][SwiftToCxx] remove extraneous semicolon when emitting 'prag…

### PR DESCRIPTION
**Pull request by hyp**
…ma clang module import'

The semicolon actually causes a compiler error in that case

### CODE REVIEW

**Comment by hyp** [comment]
@swift-ci please test source compatibility

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test source compatibility

**Comment by hyp** [comment]
@swift-ci please test macos platform

**Review by egorzhdan — APPROVED** [review]

**Pull request merged**
