### PR TITLE
Slightly clarify removeAll(where:)

### PR DESCRIPTION
**Pull request by dabrahams**
Improve parameter naming, use "guard" to reduce nesting

### CODE REVIEW

**Review by airspeedswift — APPROVED** [review]

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by dabrahams** [comment]
@swift-ci please test
again

**Comment by dabrahams** [comment]
@swift-ci please test

**Review by airspeedswift — CHANGES_REQUESTED** [review]
Sorry, just noticed that you need to make the same change on the protocol version, too.

**Comment by dabrahams** [comment]
Sorry, what is the "protocol version?"

**Comment by airspeedswift** [comment]
It's a customization point, so this signature with the old internal name is [in the protocol too](https://github.com/apple/swift/blob/1e8974682c09184366d89a17b792991ff8b0dd6d/stdlib/public/core/RangeReplaceableCollection.swift#L363), not just these two extensions.

**Review by airspeedswift — APPROVED** [review]

**Review by natecook1000 — APPROVED** [review]
LGTM!

**Pull request merged**
