### PR TITLE
[WIP] Fix Class Declaration node

### PR DESCRIPTION
**Pull request by artemmukhin**
Class Declaration node (`DeclNodes.py`) doesn’t contain optional `final` modifier.

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@ortem, that's a great start! Unfortunately, changing the declaration alone is insufficient. We have to teach parser to respect the updated scheme. Take a look at https://github.com/apple/swift/blob/master/lib/Parse/ParseDecl.cpp#L2449, where we collect all individual `DeclModifier` to `ModifierList`. You may need to do this step too for class declaration syntax.

**Comment by ortem** [comment]
@nkcsgexi thank you for the explanation, I will try to fix this problem soon!

**Comment by ortem** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@ortem could you add a test case in `round_trip_parse_gen.swift`? Please add a class declaration with more than one modifier, e.g. `private final class C {}`. Then, see the declaration is properly recognized by its kind tag in `round_trip_parse_gen.swift.withkinds`.

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by ortem** [comment]
@nkcsgexi yes, sure! Unfortunately, I can't understand how to run such tests from terminal (so I just edited `round_trip_parse_gen.swift.withkinds` manually for now). Could you explain me please, what means `%swift-syntax-test -input-source-filename %s -parse-gen > %t` in the beginning of `round_trip_parse_gen.swift`?

**Comment by ortem** [comment]
Also `ClassDecl` doesn't conform to `DeclGroup` trait, because I changed `DeclModifier` with `ModifierList`. Should I remove `DeclGroup` from `ClassDecl`'s traits or change the `DeclGroup` definition?

**Comment by ortem** [comment]
@swift-ci please smoke test

**Comment by ortem** [comment]
The changes are not relevant now, so I think this PR should be closed.

**Pull request closed without merging**
