### PR TITLE
Address John's feedback.

### PR DESCRIPTION
**Pull request by gottesmm**
Specifically to commits:

36a8d0d5c0691f2235fb6877339772e22a075dd7
6df5462ee28ab2a1756ee411f0e94f8cda92df6c

rdar://31521023

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
For those reading in, John asked for 1 more comment addition, but I do not understand what he is saying yet. I thought I would just get these in real quick before I get home. I am going to do that comment change in another PR.

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@rjmccall The follow up commit.

**Comment by rjmccall** [comment]
Yeah, I saw.  Looks fine.

**Pull request merged**
