### PR TITLE
[Runtime] Remove RuntimeFunctionCounters.

### PR DESCRIPTION
**Pull request by mikeash**
The exported symbols risk name collisions, and shouldn't be available in release builds. As this functionality is currently unused, remove it for now.

rdar://problem/35864525

### CODE REVIEW

**Comment by gparker42** [comment]
@swift-ci please test

**Comment by gottesmm** [comment]
Can you leave this in and trigger it based off asserts instead? We were hoping that this work could be used to help people debug perf changes. By keeping it in tree, we prevent it from breaking.

**Comment by gparker42** [comment]
Has anyone ever used these functions? Are there not profiling tools that will collect the same data?

**Comment by swiftix** [comment]
The original idea of this feature was not so much to collect the stats, but to make it possible to write very fine-grained unit tests able to check that e.g. only a certain amount of specific runtime calls (e.g. ref-counting) was performed by a given piece of code/closure or to check that certain runtime functions are not invoked by a given piece of code. 

I'm not sure if such a functionality is available by means of any existing profiling tools. But I may be wrong...

**Comment by mikeash** [comment]
@gparker42 Do you know if there are existing facilities that would cover this? I suspect they're oriented toward out-of-process profilers, whereas this use case would be a process monitoring itself, so maybe that makes the existing stuff not suitable.

As far as enabling interesting tests, is it actually being used for such tests at the moment? There don't appear to be any in the repository, but of course that doesn't mean it isn't being used for investigation somewhere. If it's not being used at all then I'd like to take it out just because we can end up accumulating layers of "we'll eventually use that" stuff. We can always put it back if a need emerges.

**Comment by shajrawi** [comment]
I second @gottesmm  - I would rather if it is left in and triggered based off asserts or something - these counters would be extremely useful in resilience work as @swiftix mentioned - we just enabled resilience by heavy-handedly adding attributes. these counter would help in our effort to remove (some of) these attributes.

**Comment by mikeash** [comment]
OK, I'm convinced. I'll close this and see about just turning it off for release builds instead.

**Pull request closed without merging**
