### PR TITLE
Correctly distinguish between tuple fields and associated values in patterns

### PR DESCRIPTION
**Pull request by varungandhi-apple**
See the second commit message for more details.

I'm not sure whether I should've broken things up into multiple commits, since there are couple of unrelated things that I noticed and cleaned up, but they're not really related to the main content of the PR.

Fixes [SR-11160](https://bugs.swift.org/browse/SR-11160) and related rdar://problem/53312914.

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test

**Comment by varungandhi-apple** [comment]
Skimming through the failure logs, I think the only failure is because of SwiftPM where they're relying on buggy behavior. 😢 Looking at [this line](https://github.com/apple/swift-package-manager/blob/a86b5284c833fa181a03f121a6205928ccdf48c5/Sources/PackageLoading/ModuleMapGenerator.swift#L75) and [this one](https://github.com/apple/swift-package-manager/blob/a86b5284c833fa181a03f121a6205928ccdf48c5/Sources/PackageLoading/ModuleMapGenerator.swift#L186):

```
enum Z { case z(Int, Int) }
func f() {
  switch Z.z(Int, Int) {
  case .z(let (a, b)): print(a, b)
  }
}
```

should compile fine but it doesn't now.

I'm trying to think of how we could make the fix without breaking them...

**Comment by theblixguy** [comment]
cc @aciidb0mb3r

**Comment by aciidb0mb3r** [comment]
I am fine with fixing the SwiftPM code but you probably the source compatibility probably needs to be discussed somewhere ~

**Comment by varungandhi-apple** [comment]
@aciidb0mb3r thanks! Actually, I think it is a blessing in disguise -- we caught this sooner rather than later thanks to SwiftPM 😅. I've added this hazard to [SR-11212](https://bugs.swift.org/browse/SR-11212).

**Comment by varungandhi-apple** [comment]
Current status: we have a couple of cases failing on master (non-exhaustive match) thanks to SR-11212.

https://github.com/apple/swift/blob/039bd76159f34c770b272fde3f7a62e888a9a7e1/test/Sema/exhaustive_switch.swift#L1226-L1236

Everything else still works.

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test

**Comment by varungandhi-apple** [comment]
Notes for reviewer(s):

1. As an aside, I have added some examples for PatternKinds but I'm not sure of all of those, so I'd appreciate some help with fixing them.

2. I've addressed the core issues (we emit a warning, not an error), so the PR is ready for review (barring point 3).

3. I will add more test cases that make sure everything runs as expected (i.e. we don't have a type-checks fine but some inconsistency causes a runtime crash).

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test

**Review by xedin — APPROVED** [review]
I think this looks great, @varungandhi-apple! I have left a small comment about `Type` usage.

**Comment by xedin** [comment]
@varungandhi-apple I think exhaustiveness checker should be consistent with SE-0110 so we should consider these source breaks as fixing invalid implementation behavior. It still needs to be discussed on the forums though.

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test

**Comment by jrose-apple** [comment]
> I think exhaustiveness checker should be consistent with SE-0110 so we should consider these source breaks as fixing invalid implementation behavior.

That's not a sufficient reason for a source-break these days. Remember, we're not just talking about a developer's code; we're also talking about the packages they are using, and starting with Swift 5.1 any already-compiled binary frameworks with inlinable code as well.

**Comment by xedin** [comment]
I'm trying to say that we should, I'm simplify pointing out my opinion on the matter.

**Pull request merged**
