### PR TITLE
[Syntax] Serialize RawSyntax to JSON

### PR DESCRIPTION
**Pull request by harlanhaskins**
This patch will allow for serialization of `RawSyntax` trees to JSON, which allows external tools to get access to a `RawSyntax` tree.

This also adds a hook into `swift-syntax-test` to generate JSON for a given Swift source file.

### CODE REVIEW

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test

**Comment by harlanhaskins** [comment]
Not sure what to do about this...

```
swift-syntax-test: /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/swift/lib/ClangImporter/ClangImporter.cpp:546: void getNormalInvocationArguments(std::vector<std::string> &, swift::ASTContext &, const swift::ClangImporterOptions &): Assertion `!GlibcModuleMapPath.empty()' failed.
/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/Syntax/Output/serialize_struct_decl.swift.script: line 2: 26163 Aborted                 (core dumped) /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/buildbot_linux/swift-linux-x86_64/bin/swift-syntax-test -input-source-filename /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/swift/test/Syntax/serialize_struct_decl.swift -serialize-raw-tree > /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/Syntax/Output/serialize_struct_decl.swift.tmp
```

**Review by bitjammer — APPROVED** [review]
Code LGTM.

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test

**Comment by najacque** [comment]
@swift-ci please test

**Comment by najacque** [comment]
Ok, now that master is fixed...
@swift-ci please test

**Comment by najacque** [comment]
We had more breakage on master. Should be fixed now... Let's try this again.
@swift-ci please test

**Comment by harlanhaskins** [comment]
Still getting `Assertion `!GlibcModuleMapPath.empty()' failed.` and I can't figure out why...

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test and merge

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
