### PR TITLE
stdlib: Drop a redundant generic parameter

### PR DESCRIPTION
**Pull request by AnthonyLatsis**

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please smoke test and merge

**Comment by airspeedswift** [comment]
Thanks!

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test macOS

**Comment by AnthonyLatsis** [comment]
@swift-ci please clean smoke test macOS and merge

**Comment by AnthonyLatsis** [comment]
@swift-ci please clean smoke test macOS

**Pull request merged**
