### PR TITLE
runtime: ingest LLVMSupport into the runtime

### PR DESCRIPTION
**Pull request by compnerd**
This adds a new copy of LLVMSupport into the runtime.  This is the final
step before changing the inline namespace for the runtime support.  This
will allow us to avoid the ODR violations from the header definitions of
LLVMSupport.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @mikeash @jckarter

**Comment by compnerd** [comment]
I'll be updating the commit message to include this, but LLVMSupport was forked at 22492eead218ec91d349c8c50439880fbeacf2b7.  The allocation updates are corresponding to upstream changes.

**Review by mikeash — APPROVED** [review]
Yaay

**Comment by jckarter** [comment]
Do we need all of llvmSupport? Can we bring over only the bits we use?

**Comment by compnerd** [comment]
@jckarter I believe that we dont need all of LLVMSupport.  My intention is to bring it in its entirety to compile.  Im going to more or less immediately follow this up with 2 changes:
1. introduce an inline namespace for avoiding the ODR violation that this causes (which is the original motivation for all the work)
2. begin to strip this down to just the pieces that we are actually using.

I want to introduce the library in its complete form because its much easier to track the provenance that way.  It makes it simpler to split the operation into copy, delete rather than do it as one.  However, Im happy to just stack that into this change and merge the entire thing at once, as long as the steps remain to help make it easier to follow what happened.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/llvm-project#1205

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/llvm-project#1206

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/llvm-project#1206

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/llvm-project#1206

@swift-ci please test macOS platform

**Comment by compnerd** [comment]
Please test with following PRs:
apple/llvm-project#1206

@swift-ci please test windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
apple/llvm-project#1206

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/llvm-project#1206

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/llvm-project#1206

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/llvm-project#1206

@swift-ci please test

**Comment by compnerd** [comment]
Going to have to do the namespacing and pruning together to avoid growing dependencies on ncurses

**Comment by compnerd** [comment]
Verifying leakage with:
```shell
$ nm -C --defined-only lib/swift/linux/x86_64/libswiftCore.so | grep -v -e __swift::__runtime -e ' swift::' -e ' std::' | grep llvm::
```

There are current a couple of small leaks which will be cleaned up by the pruning.

```
0000000000639430 t llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::AllocatorList<llvm::yaml::Token, llvm::BumpPtrAllocatorImpl<llvm::MallocAllocator, 4096ul, 4096ul, 128ul> >::Node, true, false, void>, false, false> llvm::simple_ilist<llvm::AllocatorList<llvm::yaml::Token, llvm::BumpPtrAllocatorImpl<llvm::MallocAllocator, 4096ul, 4096ul, 128ul>>::Node>::eraseAndDispose<llvm::AllocatorList<llvm::yaml::Token, llvm::BumpPtrAllocatorImpl<llvm::MallocAllocator, 4096ul, 4096ul, 128ul> >::Disposer(llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::AllocatorList<llvm::yaml::Token, llvm::BumpPtrAllocatorImpl<llvm::MallocAllocator, 4096ul, 4096ul, 128ul> >::Node, true, false, void>, false, false>, llvm::AllocatorList<llvm::yaml::Token, llvm::BumpPtrAllocatorImpl<llvm::MallocAllocator, 4096ul, 4096ul, 128ul> >::Disposer)
0000000000611850 t unsigned int llvm::ComputeEditDistance<char>(llvm::ArrayRef<char>, llvm::ArrayRef<char>, bool, unsigned int)
000000000061b8d0 t llvm::sys::UnicodeCharSet::rangesAreValid() const
```

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test windows platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
```
$ nm --defined-only -demangle ./lib/swift/macosx/x86_64/libswiftCore.dylib | grep -v -e '__swift::__runtime::llvm' | grep -e 'llvm::'
00000000003cb3c0 t (anonymous namespace)::OldDemangler::demangleIdentifier(llvm::Optional<swift::Demangle::Node::Kind>)
0000000000441c30 s (anonymous namespace)::OldDemangler::demangleIdentifier(llvm::Optional<swift::Demangle::Node::Kind>)::op_char_table
```

This symbol is actually leaked on all the platforms, and can be cleaned up subsequently

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
```
$ nm --defined-only --demangle lib/swift/linux/libswiftCore.so | grep -v
 -e '__swift::__runtime::llvm' | grep llvm::
0000000000589810 t (anonymous namespace)::OldDemangler::demangleIdentifier(llvm::Optional<swift::Demangle::Node::Kind>)
000000000001a6f0 r (anonymous namespace)::OldDemangler::demangleIdentifier(llvm::Optional<swift::Demangle::Node::Kind>)::op_char_table
```
Linux is also in sync with macOS here

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
Spoke with JoeG and MikeA about this offline.  We all agree that this is bringing us into a better state for stability moving forward, addresses the ODR violation issue.

This allows for a transitioning state where we could start vending the ADTs as part of the runtime and work towards removing the some of the C++-ness of the ABI definitions to allow for easier sharing between the runtime and the compiler.  It would also allow for easier use of the ABI type definitions in the Swift code.

**Pull request merged**
