### PR TITLE
[closure-spec] Do not try to process begin_apply. It is not supported now.

### PR DESCRIPTION
**Pull request by gottesmm**
[closure-spec] Do not try to process begin_apply. It is not supported now.

We were crashing when we saw this.

rdar://44612356

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
Ignore the first commit. It is just setting up the FullApplySiteKind.

**Comment by gottesmm** [comment]
Forgot to commit a typo fix...

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
Actually, I am going to rebase this on top of master. So only 1 commit now.

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Review by aschwaighofer — APPROVED** [review]
LGTM

**Pull request merged**
