### PR TITLE
QuickLook Project to navigate sources

### PR DESCRIPTION
**Pull request by johnno1962**
A simplified project to navigate sources quickly as an alternative to the generated Swift.xcodeproj. Compiles to the point of linking.

### CODE REVIEW

**Comment by gribozavr** [comment]
I'm sorry, but we explicitly don't want a second build system.  I don't have an opinion about using it for IDE purposes only.  /cc @jrose-apple

**Comment by johnno1962** [comment]
I understand. It was not intended as an alternative build, just a curated project to help people find their way around. It compiles only as a check the include paths are as good as they can be.

**Comment by gribozavr** [comment]
Well, the fact that it compiles at all makes me concerned that some people will inadvertently use it to compile.

**Comment by johnno1962** [comment]
I tried to avoid this with the project name but I appreciate your reservations. This is quite a speculative pull request really.

**Comment by jrose-apple** [comment]
I agree with Dmitri. We do not want a second list of files that we need to keep up to date, sorry.

My recommendation is to make your own xcworkspace that includes the generated xcodeproj. That way you can add custom file references, save schemes even through blowing away your whole build directory, and still build like everyone else. I also find that Open Quickly works wonders.

**Comment by johnno1962** [comment]
Fair enough, I probably agree. I’ve made the browsing project available as a separate project https://github.com/johnno1962/SwiftLook in case it’s of use to people..

Thanks for alll your work!

**Pull request closed without merging**
