### PR TITLE
[Demangler] Fix OldRemangler to cope with Type nodes

### PR DESCRIPTION
**Pull request by al45tair**
The Demangler can wrap types in a `Node::Kind::Type` node; these need to be handled by following the node's first child pointer.  Failing to do this led to a crash or assertion failure in some cases.

rdar://63678171

### CODE REVIEW

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
@swift-ci Please smoke test macOS platform

**Review by eeckstein — APPROVED** [review]
lgtm!

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
@swift-ci Please smoke test macOS platform

**Comment by al45tair** [comment]
@swift-ci Please smoke test macOS platform

**Comment by al45tair** [comment]
@swift-ci Please smoke test macOS platform

**Pull request merged**
