### PR TITLE
[ownership] Once we strip ownership ignoring transparent functions fr…

### PR DESCRIPTION
**Pull request by gottesmm**
…om our module, strip ownership as we serialize.

### CODE REVIEW

**Comment by gottesmm** [comment]
Forgot to add one test.

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Review by eeckstein — APPROVED** [review]

**Pull request merged**
