### PR TITLE
Update the error message when subscripting String with Int.

### PR DESCRIPTION
**Pull request by natecook1000**
Instead of referring to a doc comment that isn't really accessible to the developer, let's just be accurate about what type they should be using here.

rdar://problem/33715475

### CODE REVIEW

**Comment by amartini51** [comment]
I think this is an improvement — it gives concrete, actionable feedback of what to you should do when you see this error.

The doc comments have more detailed information about why these methods shouldn't exist.  However, I'm not finding a way to view that content in Xcode or on developer.apple.com.  Is that expected?

**Review by amartini51 — APPROVED** [review]

**Comment by natecook1000** [comment]
IIRC the doc comments that have this info are on extensions, which don’t end up being attached to any particular symbol when SourceKit imports the module. Would this info make sense to move to the actual subscript docs? It feels a little weird to explain why an API isn’t written a different way, and there is an SE proposal to add `Int`-offset-based element access and slicing…

**Comment by natecook1000** [comment]
@swift-ci Please smoke test and merge

**Comment by amartini51** [comment]
Looks like the smoke test failed because test/stdlib/UnavailableStringAPIs.swift.gyb is expecting the old error messages.

**Comment by natecook1000** [comment]
@swift-ci Please smoke test

**Comment by natecook1000** [comment]
@swift-ci Please smoke test

**Pull request merged**
