### PR TITLE
[Coding] Make Codable conformances for Optional and collections conditional.

### PR DESCRIPTION
**Pull request by DougGregor**
Array, Set, Dictionary, and Optional all provide unconditional conformances
to Encodable & Decodable that dynamically check whether their type arguments
are Encodable/Decodable. Now that we have conditional conformances, make
these unconditional conformances properly conditional, removing all of
the Swift 4-era type-erasure hacks.

Fixes rdar://problem/34989162.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please smoke test Linux

**Comment by itaiferber** [comment]
These look good! We can further simplify `DerivedConformanceCodable.cpp` by removing the explicit checks for `Array`, `Dictionary`, `Set`, and `Optional` as well — mentioned this via email but wanted to make sure the commend didn't get lost.

**Review by itaiferber — CHANGES_REQUESTED** [review]
These look good! (I have pretty much line for line the same diff on a local branch here.) We can further simplify `DerivedConformanceCodable.cpp` by removing the explicit checks for `Array`, `Dictionary`, `Set`, and `Optional` as well — mentioned this via email but wanted to make sure the commend didn't get lost.

**Review by itaiferber — APPROVED** [review]
Excellent, thank you, Doug! 😄

**Comment by DougGregor** [comment]
@swift-ci please test and merge

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please smoke test Linux

**Comment by DougGregor** [comment]
@swift-ci please smoke test Linux

**Comment by itaiferber** [comment]
🎉🙌

**Comment by norio-nomura** [comment]
Are `[Any]` and `[String: Any]` no longer `Codable`?

**Comment by itaiferber** [comment]
@norio-nomura `[Any]` and `[String : Any]` never really were `Codable` because `Any` doesn’t (and can’t truly) conform to `Codable` — it would just fail at runtime if you tried. Now that is caught statically.

**Comment by norio-nomura** [comment]
@itaiferber Oh, yes. I was a bit confused. Thank you very much.

**Pull request merged**
