### PR TITLE
[Concurrency] refactor GlobalConcurrency checking from ActorIsolationRequest to DeclChecker

### PR DESCRIPTION
**Pull request by sophiapoirier**

### CODE REVIEW

**Comment by sophiapoirier** [comment]
@swift-ci please test

**Review by xedin — APPROVED** [review]
LGTM, one stylistic suggestion is to switch to use early returns now that this is a function.

**Comment by sophiapoirier** [comment]
> LGTM, one stylistic suggestion is to switch to use early returns now that this is a function.

oops sorry @xedin I missed the notification for this comment and only noticed it on screen just as I was pressing the merge button. I'll slip that edit into a future changeset.

**Comment by xedin** [comment]
No worries!

**Pull request merged**
