### PR TITLE
[stdlib] Add dictionary overloads for merging methods

### PR DESCRIPTION
**Pull request by natecook1000**
This resolves the issue where a dictionary can’t be passed to the `Dictionary.merge` and `.merging` methods by providing dictionary-specific overloads for those two methods.

### CODE REVIEW

**Comment by natecook1000** [comment]
@swift-ci Please smoke test

**Comment by natecook1000** [comment]
@swift-ci Please smoke test

**Comment by moiseev** [comment]
LGTM

**Comment by natecook1000** [comment]
@swift-ci Please test source compatibility

**Comment by natecook1000** [comment]
@swift-ci Please Test Source Compatibility

**Pull request merged**
