### PR TITLE
Implement legacy UTF8 APIs in terms of new components

### PR DESCRIPTION
**Pull request by dabrahams**

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please benchmark

**Comment by dabrahams** [comment]
@swift-ci Please test

**Comment by dabrahams** [comment]
@swift-ci Please smoke benchmark

**Comment by dabrahams** [comment]
@swift-ci Please smoke benchmark

**Comment by dabrahams** [comment]
@swift-ci Please smoke test

**Comment by dabrahams** [comment]
@swift-ci Please smoke test linux platform

**Comment by dabrahams** [comment]
@swift-ci Please smoke test OS X platform

**Comment by dabrahams** [comment]
@swift-ci Please benchmark

**Comment by dabrahams** [comment]
@swift-ci Please benchmark

**Comment by dabrahams** [comment]
@swift-ci Please benchmark

**Comment by dabrahams** [comment]
@swift-ci Please smoke test

**Comment by dabrahams** [comment]
@swift-ci Please benchmark

**Comment by dabrahams** [comment]
@swift-ci Please smoke test

**Comment by dabrahams** [comment]
@swift-ci Please benchmark

**Comment by dabrahams** [comment]
@swift-ci Please benchmark

**Comment by dabrahams** [comment]
@swift-ci Please smoke test and merge

**Comment by dabrahams** [comment]
@swift-ci Please smoke test and merge

**Comment by airspeedswift** [comment]
Do we have an idea what happened with MapReduceString and StringEdits? Anything we can do to recoup?

**Comment by dabrahams** [comment]
@aschwaighofer this PR contains a bunch of commits that change inlining and incidentally remove gobs of ARC traffic.  It would be really helpful to understand whether these things are caused by the calling convention, and if not, whether there's anything we can do to control them.

**Comment by dabrahams** [comment]
@airspeedswift As you surmised from the speculative revert commits, I'm having a hard time finding a magic combination that appears to eliminate all regressions.

**Comment by aschwaighofer** [comment]
If adding @inline(__always) affects the result that means that the optimizer was able to actually inline the function (because it could identify it as the callee). This means that it can as well specialize the function by changing it from owned to guaranteed - which it does (almost? @gottesmm) unconditionally (it needs to find the post dominating release (set). does that fail often @gottesmm ?). i.e it very likely did change the calling convention to @guaranteed before you added the @inline(_always) annotation. Therefore, changing the default convention would probably not do us any good here because the optimizer already does it for us.

What inlining in general gives more context to other optimizations. This is good in two directions:
- simplifications, value propagation: allows for values being propagated allowing simplifications like removing control-flow (which can help arc), it might also allow ARC to now decern that two references are actually the same reference
- code motion: exposing the content of the function to the caller allows ARC to move ref count instructions from the caller downward in the control flow (into the callee), removing it from some paths. It might also move things upward for pairing.

Can you point at a specific regression you want me to look at?

**Comment by gottesmm** [comment]
@aschwaighofer Yes. I am not sure. I gave this code over to Xin and he changed the pass significantly. Erik and I are maintaining it now. But it would be good for someone to go back in and see if we are missing any patterns.

**Comment by dabrahams** [comment]
@aschwaighofer None of the regressions that come from just taking the first commit, without the additional inlining commits, stood out for me.  They all had the same character when I analyzed them: R/R traffic where it shouldn't exist, suppressable by inlining the invoker of that R/R traffic into its caller.  We could run another benchmark in CI against a PR that reverts all the inlining commits in this one if you want to know what those are, but I suspect you would want a local run anyway(?)

**Comment by dabrahams** [comment]
@aschwaighofer There's a pretty good, simple example of this in https://bugs.swift.org/browse/SR-4837

**Pull request merged**
