### PR TITLE
[Threading][TSan] Fix TSan errors from lazy init on Linux.

### PR DESCRIPTION
**Pull request by al45tair**
Move the TSan functionality from Concurrency into Threading. Use it in the Linux ulock implementation so that TSan knows about ulock and will tolerate the newer swift_once implementation that uses it.

This should also slightly improve the performance of Concurrency, since the tsan tests will be inlined rather than it always doing a subroutine call.

rdar://110665213

### CODE REVIEW

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by al45tair** [comment]
See also #66877, which is the 5.9 cherry pick.

**Comment by al45tair** [comment]
@kubamracek I assume the issue here with the freestanding preset isn't one I've created by fixing the TSan problem in 5.8? Just wanted to get confirmation before I ask for branch manager approval (this is for a Linux point release).

**Comment by al45tair** [comment]
Apparently the bot is misconfigured and is downloading the wrong toolchain, which is why the standalone preset failed.

**Review by tomerd — APPROVED** [review]

**Review by kubamracek — APPROVED** [review]

**Review by tbkka — APPROVED** [review]

**Pull request merged**
