### PR TITLE
[FieldSensitivePL] NFC: Added unit tests.

### PR DESCRIPTION
**Pull request by nate-chandler**
Ported versions of the unit tests that Andy added to pruned liveness to FieldSensitivePL.

rdar://110862719

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by atrick — APPROVED** [review]
Nice.

Some of the SSA tests were moved to an "incomplete" file because the SIL verifier says the SIL is invalid when we enable complete OSSA. I don't think that applied to liveness of memory  locations. I think all the SIL here is valid regardless of the OSSA mode. So you shouldn't need to call some of them "incomplete" SIL

**Comment by nate-chandler** [comment]
All tests are now in test/SILOptimizer/field_sensitive_liverange_unit.sil and the "incomplete" file has been deleted.

**Comment by nate-chandler** [comment]
@swift-ci please test and merge

**Pull request merged**
