### PR TITLE
Revert "[silgen] If we have a direct guaranteed convention and have a…

### PR DESCRIPTION
**Pull request by gottesmm**
…n owned value, perform a borrow."

This reverts commit 4c8595b0028e4ff8ea289e9f91a426ef2118681f.

I fixed the issues with debug tests + release stdlib. Looks like there are some issues with debug tests + debug stdlib = /.

rdar://30955427

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci Please test and merge

**Comment by gparker42** [comment]
Is that the right Radar number?

**Comment by gottesmm** [comment]
I looked last night and didn't see a radar # for it, so I just stuck in the original radar # for it. I see there is one now.

**Comment by gottesmm** [comment]
<rdar://problem/31145269> Container tests failing in debug stdlib builds

**Pull request merged**
