### PR TITLE
[CSGen] A couple of improvements to pattern binding handling

### PR DESCRIPTION
**Pull request by xedin**
-  Resolve binding pattern before using it
- Fail early if pattern binding is incorrect

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test

**Review by hborla — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
Source compat suite failure is unrelated:

```
$ rm -rf /Users/buildnode/jenkins/workspace/swift-PR-source-compat-suite/swift-source-compat-suite/project_cache/Kickstarter-ReactiveExtensions
rm: /Users/buildnode/jenkins/workspace/swift-PR-source-compat-suite/swift-source-compat-suite/project_cache/Kickstarter-ReactiveExtensions: Directory not empty
```

**Pull request merged**
