### PR TITLE
Experiment. Add DIExpr to SILDebugVariable::operator==

### PR DESCRIPTION
**Pull request by gottesmm**

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
I am also going to locally build with/without the patch and make sure that dsymutil on libswiftcore.dylib and then run dwarfdump --statistic on the two dsyms and diff them.

**Comment by adrian-prantl** [comment]
I'd like to see the statistics result before signing off on this.

**Comment by gottesmm** [comment]
@adrian-prantl what statistics are you looking for? I don't know what you are referring to.

**Comment by adrian-prantl** [comment]
these:

**Comment by adrian-prantl** [comment]
> I am also going to locally build with/without the patch and make sure that dsymutil on libswiftcore.dylib and then run dwarfdump --statistic on the two dsyms and diff them.

**Comment by gottesmm** [comment]
@adrian-prantl got a good diff result:

```
gottesmm@ Ninja-RelWithDebInfoAssert % xcrun dwarfdump --statistics .//swift-macosx-x86_64-old/lib/swift/macosx/libswiftCore.dylib.dSYM > old
gottesmm@ Ninja-RelWithDebInfoAssert % xcrun dwarfdump --statistics .//swift-macosx-x86_64-new/lib/swift/macosx/libswiftCore.dylib.dSYM > new
gottesmm@ Ninja-RelWithDebInfoAssert % diff old new
3c3
<   "file": "swift-macosx-x86_64-old/lib/swift/macosx/libswiftCore.dylib.dSYM/Contents/Resources/DWARF/libswiftCore.dylib(x86_64)",
---
>   "file": "swift-macosx-x86_64-new/lib/swift/macosx/libswiftCore.dylib.dSYM/Contents/Resources/DWARF/libswiftCore.dylib(x86_64)",
126c126
<   "file": "swift-macosx-x86_64-old/lib/swift/macosx/libswiftCore.dylib.dSYM/Contents/Resources/DWARF/libswiftCore.dylib(arm64)",
---
>   "file": "swift-macosx-x86_64-new/lib/swift/macosx/libswiftCore.dylib.dSYM/Contents/Resources/DWARF/libswiftCore.dylib(arm64)",
```

**Comment by gottesmm** [comment]
Given that there isn't a diff and that is what @adrian-prantl wanted, I am going to merge and do post-commit. I want to base another commit on top of this and have it test over night on CI.

**Pull request merged**
