### PR TITLE
 [TBDGen] Add support for Objective-C Categories.

### PR DESCRIPTION
**Pull request by ributzka**
Emit Objective-C Categories for extensions that have the @objc attribute directly (or indirectly via one of its methods, subscripts, etc) attached.

Also associate and emit all methods for that category into the API JSON file.

This fixes rdar://94734748.

### CODE REVIEW

**Comment by ributzka** [comment]
@swift-ci Please test

**Review by nkcsgexi — APPROVED** [review]
LGTM!

**Review by cachemeifyoucan — APPROVED** [review]
LGTM

**Comment by ributzka** [comment]
Thanks

**Pull request merged**
