### PR TITLE
[build] Clear out old supported Xcode versions

### PR DESCRIPTION
**Pull request by kastiglione**
Leave support for only 12.3 and newer.

### CODE REVIEW

**Comment by kastiglione** [comment]
@swift-ci smoke test

**Review by keith — APPROVED** [review]

**Comment by kastiglione** [comment]
I don't know if it's worth keeping 12.4 or older. I'm suspecting "no".

**Comment by shahmishal** [comment]
This will still fail because CI is still using `("12.3", "12C33")`

**Comment by kastiglione** [comment]
I wondered about that, ok I'll restore 12.3 and 12.4.

**Comment by kastiglione** [comment]
@swift-ci smoke test

**Review by shahmishal — APPROVED** [review]

**Pull request merged**
