### PR TITLE
[stdlib] UnicodeScalarProperties: use RawValue over UInt32

### PR DESCRIPTION
**Pull request by troughton**
On Windows, `__swift_stdlib_UNumericType` and `__swift_stdlib_UCharCategory` are imported as `Int32`s rather than `UInt32`. Change the constructors to use the type's inferred `RawValue` rather than always `UInt32`.

### CODE REVIEW

**Comment by troughton** [comment]
CC @milseman

**Comment by milseman** [comment]
@swift-ci please test

**Review by milseman — APPROVED** [review]
LGTM

**Comment by milseman** [comment]
(first time resolving a merge conflict through Github browser, let's see how it goes)

@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please test

**Pull request merged**
