### PR TITLE
[Sema] Remove iterative type checker

### PR DESCRIPTION
**Pull request by DougGregor**
While an interesting design, the iterative type checker didn't pan out. It was replaced by the request-evaluator design (partially) adopted by the type checker in https://github.com/apple/swift/pull/16963.

### CODE REVIEW

**Comment by slavapestov** [comment]
Can you keep the document around? It's still interesting because it does a good job of explaining the problems with the current design.

**Comment by DougGregor** [comment]
Hmm... we can keep the document around. I guess I could update it for the request-evaluator. It affects my negative line count, though :)

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
