### PR TITLE
[ConstraintLocator] Always store the PathElementKind in each locator path element.

### PR DESCRIPTION
**Pull request by hborla**
* Always storing the `PathElementKind` lifts the restriction of only allowing 8 different kinds of path elements to store non-numeric values (because of the previous 3 bit storage for `storedKind` and the 1:1 mapping of `StoredKind` to `PathElementKind`)
* This change also removes the `StoredKind` enum and instead statically enforces invariants about the stored value(s) for each custom path element where possible.

### CODE REVIEW

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by hborla** [comment]
@swift-ci please test source compatibility

**Review by xedin — APPROVED** [review]
Looks great! One more thing we might want to consider enforcing is that nothing could be a direct subclass of the `LocatorPathElt` expect to `StoredInteregerElement` and `StoredPointerElement` to avoid mistakes in the future, WDYT?

**Comment by hborla** [comment]
@xedin I think that's a good idea! I think I can enforce that all custom locator path elements are derived from either `StoredInteregerElement` or `StoredPointerElement`

**Comment by xedin** [comment]
@hborla Great!

**Comment by hborla** [comment]
@xedin Okay, now if there is a custom path element that inherits directly from `LocatorPathElt`, you'll get this error message:

```
error: static_assert failed due to requirement 'isValidCustomPathElement<swift::constraints::ConstraintLocator::PathElement::InvalidElt>()' "Custom path elements must inherit from StoredIntegerElement or StoredPointerElement"
```

**Comment by hborla** [comment]
@swift-ci please smoke test

**Pull request merged**
