### PR TITLE
runtime, build: homogenise the assertions toggle

### PR DESCRIPTION
**Pull request by compnerd**
Sink a couple of build configuration toggles related to the runtime into
the standard library build.

Unify the `SWIFT_STDLIB_ASSERTIONS` and `LLVM_ENABLE_ASSERTIONS` into a
new `SWIFT_RUNTIME_ENABLE_ASSERTIONS` which matches the style of the
other Swift runtime options.

Delay the configuration rendering until the end of the configuration to
allow the options to propagate back up.  This needs to be done until the
runtime configuration is fully sunk into the runtime build.

Remove the use of `LLVM_ENABLE_ASSERTIONS` in the runtime in preparation
to sever the LLVM dependency for the runtime, ingesting the LLVM Support
ADT definitions.  That will allow the ODR violations to be eradicated by
means of an inline namespace.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @drexin @mikeash

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Review by mikeash — APPROVED** [review]

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
