### PR TITLE
[stdlib] Sanitize _HeapBuffer interface; rename it to _BridgingBuffer

### PR DESCRIPTION
**Pull request by lorentey**
- `_HeapBuffer` was at the wrong abstraction level, for no good reason. We now have `ManagedBuffer` for the general case; we don’t need a slightly less general variant of it.
- Current usages of `_HeapBuffer` are hyper specific: they all are flat buffers of `AnyObjects`, facilitating bridging. Thus it makes sense to dedicate `_HeapBuffer` for this single usecase.
- Introduce a dedicate `ManagedBuffer` subclass for bridging buffers. This will make it slightly easier to recognize these in heap dumps.
- Inlinability audit.

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci benchmark

**Review by lancep — APPROVED** [review]
LGTM!

**Comment by lorentey** [comment]
lldb test failure was unrelated; see https://github.com/apple/swift-lldb/pull/1005

**Comment by lorentey** [comment]
@swift-ci please smoke test macOS platform

**Comment by lorentey** [comment]
@swift-ci please smoke test macOS platform

**Comment by lorentey** [comment]
@swift-ci smoke test

**Comment by lorentey** [comment]
@swift-ci benchmark

**Comment by lorentey** [comment]
@swift-ci smoke test

**Comment by lorentey** [comment]
@swift-ci smoke test

**Comment by lorentey** [comment]
@swift-ci smoke test linux platform

**Comment by lorentey** [comment]
@swift-ci smoke test linux platform

**Comment by lorentey** [comment]
@swift-ci benchmark

**Comment by lorentey** [comment]
@swift-ci smoke test linux platform

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci please smoke test

**Comment by lorentey** [comment]
@swift-ci smoke test

**Comment by lorentey** [comment]
@swift-ci smoke test

**Comment by lorentey** [comment]
@swift-ci benchmark

**Comment by lorentey** [comment]
@swift-ci benchmark

**Comment by lorentey** [comment]
@swift-ci please smoke test

**Comment by lorentey** [comment]
@swift-ci please smoke test

**Pull request merged**
