### PR TITLE
[SE-0251] Additions to SIMD types.

### PR DESCRIPTION
**Pull request by stephentyrone**
- extension from 2 and 3-element vectors to 3- and 4-element vectors.
- the .one member
- swizzles via subscript-by-simd
- min/max/sum reductions
- min/max/clamp on vectors-of-comparable
- any and all
- copysign

Fixes <rdar://problem/48276450>

### CODE REVIEW

**Comment by stephentyrone** [comment]
@swift-ci please test

**Comment by stephentyrone** [comment]
@swift-ci please test source compatibility

**Comment by stephentyrone** [comment]
@swift-ci please test source compatibility.

**Comment by airspeedswift** [comment]
Is this gtm?

**Comment by stephentyrone** [comment]
Yes. I wanted to check with you before pushing it in, but I’ll do it now and make a clone for 5.1 later today.

**Pull request merged**
