### PR TITLE
[stdlib] Implement SE-147: Move initialize(from:) from Pointer to BufferPointer

### PR DESCRIPTION
**Pull request by airspeedswift**
This PR implements [SE-147](https://github.com/apple/swift-evolution/blob/master/proposals/0147-move-unsafe-initialize-from.md)

Specifically it:
 - deprecates `initialize(from:)` in `UnsafeMutable{Raw}BufferPointer`
 - introduces a safer replacement in `UnsafeMutable{Raw}BufferPointer`
 - alters any uses of the old one in the std lib to use the new one
 - eliminates the version of `Array.append` that takes a collection as no-longer necessary
 - moves `Array`'s `+=` operator up to `RangeReplaceableCollection`

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci Please test

**Comment by airspeedswift** [comment]
@swift-ci Please benchmark

**Comment by airspeedswift** [comment]
@swift-ci Please test OS X platform

**Comment by airspeedswift** [comment]
Uh-oh. Looks like Data in swift-corelibs-foundation is using _copyContents.

https://github.com/apple/swift-corelibs-foundation/blob/master/Foundation/Data.swift#L1439

**Comment by shahmishal** [comment]
@swift-ci Please clean test macOS

**Comment by shahmishal** [comment]
Please test with following pull request:
apple/swift-corelibs-foundation#760

@swift-ci Please test Linux platform

**Comment by airspeedswift** [comment]
Please test with following pull request:
apple/swift-corelibs-foundation#760

@swift-ci Please test Linux platform

**Comment by airspeedswift** [comment]
@swift-ci Please test macOS platform

**Comment by atrick** [comment]
👍

**Pull request merged**
