### PR TITLE
[AutoDiff] Enable differentiable programming by default for testing.

### PR DESCRIPTION
**Pull request by dan-zheng**
The `build-script` driver argument for differentiable programming is [already
enabled by default](https://github.com/apple/swift/blob/8035d3915137eefee88173dda7a6b59bc4612bd5/utils/build_swift/build_swift/driver_arguments.py#L1068-L1071), for testing purposes. This makes macOS and Linux CI run
AutoDiff tests.

Now, the CMake flag for differentiable programming is also enabled.
This should make Windows CI run AutoDiff tests as well.

As before, compiler invocations that do not use differentiable programming
features should not be affected.

---

Let's confirm that AutoDiff tests pass on Windows CI before merging.
AutoDiff test failures on Windows are expected, so we should fix those first.

### CODE REVIEW

**Comment by dan-zheng** [comment]
@swift-ci Please smoke test

**Comment by dan-zheng** [comment]
An AutoDiff test failed on Windows, as expected:
```
Failing Tests (1):
    Swift(windows-x86_64) :: AutoDiff/validation-test/reabstraction.swift
```
We'll look into this soon!

**Comment by dan-zheng** [comment]
@swift-ci Please smoke test

**Comment by dan-zheng** [comment]
@swift-ci Please smoke test Windows

**Comment by dan-zheng** [comment]
Re-running to see latest Windows failures.
@swift-ci Please smoke test Windows

**Comment by compnerd** [comment]
Right now, I'm seeing these two failures that are yet unresolved:

```
    Swift(windows-x86_64) :: AutoDiff/validation-test/reabstraction.swift
    Swift(windows-x86_64) :: AutoDiff/validation-test/derivative_registration.swift
```

Both of these are due to the runtime not finding conformance not being found for the types.

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
