### PR TITLE
Avoid using separate '-D' + '...' flags in CFLAGS in CMake

### PR DESCRIPTION
**Pull request by kubamracek**
Please look at the code change, and think "how could this possibly be a significant change?". If you come up empty, like me when I originally hit this, then [click here](https://cmake.org/cmake/help/latest/command/target_compile_options.html#option-de-duplication) to reveal the solution. CMake 🤷

### CODE REVIEW

**Review by al45tair — APPROVED** [review]
Aaaargh!

**Comment by mikeash** [comment]
I'm pretty sure I've seen this before. Also, WTF CMake?!

**Review by mikeash — APPROVED** [review]

**Review by nate-chandler — APPROVED** [review]
`Error, your directive was too legible.` -CMake, probably

**Comment by mikeash** [comment]
Proposed:

```diff
@@ -55,9 +55,9 @@ public enum CommandLine {
-  public static var arguments: [String]
+  public static var arguments: Set<String>
```

**Review by rokhinip — APPROVED** [review]

**Review by compnerd — APPROVED** [review]
This isn't really that weird.  It actually is a positive. The point is that people often repeat the options on the command line, CMake will deduplicate it to get a saner command line.

**Comment by compnerd** [comment]
> Proposed:
> 
> ```diff
> @@ -55,9 +55,9 @@ public enum CommandLine {
> -  public static var arguments: [String]
> +  public static var arguments: Set<String>
> ```

@mikeash ITYM `Array<String>` 🤓

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Pull request merged**
