### PR TITLE
[embedded] Start building embedded support on Linux/ELF, expand archs of the embedded stdlib to cover common embedded targets

### PR DESCRIPTION
**Pull request by kubamracek**
There is nothing Apple / Mach-O specific in the Embedded Swift setup, let's enable the Embedded Swift support in the Linux toolchains and start building the embedded stdlib for ELF, too.

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by finagolfin** [comment]
Nice, any plans to set up a CI that runs the compiler tests on actual hardware? At least, it would be nice to have a 32-bit non-embedded CI set up, that could run all the native executable tests too. I don't think anybody is doing that right now, unless there's still a 32-bit watchOS CI running internally right now somewhere.

I think it wouldn't be hard to set up a linux armv7 CI on one of the existing linux AArch64 images, since 64-bit distros usually support building and running 32-bit binaries also.

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
I think this is causing failures on the incremental bots, which look like:

```
<unknown>:0: error: fatal error encountered during compilation; please submit a bug report (https://swift.org/contributing/#reporting-bugs)
<unknown>:0: note: No available targets are compatible with triple "riscv32-none-none-eabi"
```

I put up what I think is a fix at https://github.com/apple/swift/pull/70057, and am going to kick off testing of a revert PR in case that isn't right.

**Pull request merged**
