### PR TITLE
Do not attempt to parse the PlaceholderSwiftModule map when not present

### PR DESCRIPTION
**Pull request by artemcm**

### CODE REVIEW

**Review by nkcsgexi — APPROVED** [review]

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test Windows platform

**Comment by artemcm** [comment]
@swift-ci please test Windows platform

**Comment by artemcm** [comment]
@swift-ci please test Windows platform

**Comment by artemcm** [comment]
@swift-ci please test Windows platform

**Comment by artemcm** [comment]
@swift-ci please test Windows platform

**Comment by artemcm** [comment]
@swift-ci please test Windows platform

**Pull request merged**
