### PR TITLE
Revert "IRGen: Weakly link symbols for unavailable declarations"

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/swift#64353

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @tshortli

**Comment by compnerd** [comment]
CC: @Azoy

**Comment by compnerd** [comment]
Error message for ease of finding:

```
DateComponentsFormatter.swift.obj : fatal error LNK1227: conflicting weak extern definition for '$s10Foundation9FormatterC11objectValueyypSgSSKF'.  New default '.weak.$s10Foundation9FormatterC11objectValueyypSgSSKF.default.$s10Foundation23DateComponentsFormatterC10UnitsStyleO8rawValueAESgSi_tcfC' conflicts with old default '.weak.$s10Foundation9FormatterC11objectValueyypSgSSKF.default.$s10Foundation18ByteCountFormatterC5UnitsV8rawValueSuvg' in ByteCountFormatter.swift.obj
```

**Comment by tshortli** [comment]
Sorry about that. Looks like I'll need to avoid making unavailable declarations weak on Windows.

**Review by tshortli — APPROVED** [review]

**Comment by compnerd** [comment]
@tshortli - another option would be to fix up the symbols so that they are coalesced properly through the application of COMDATs.  There are examples in IRGen where we do this.

**Comment by Azoy** [comment]
This good to go?

**Pull request merged**
