### PR TITLE
[5.3] IRGen: Fix asserting local extern declarations.

### PR DESCRIPTION
**Pull request by aschwaighofer**
Explanation:
LLVM currently asserts on local extern variables in C headers passed to
Swift when the definition exists outside that header.

Scope: This never worked.

Risk: Low.

Testing: Regression test added.

Reviewed-by: John McCall

Original PR: #33306

rdar://67951491

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci please nominate

**Review by tkremenek — APPROVED** [review]

**Comment by 3405691582** [comment]
This probably needs to pick the commits from #33816 and #33827 as well, which add the optional `dso_local` match to the check. 

This may not be a Windows related thing; I haven't found out what is different to have these annotations show up in the IR or not, but perhaps there's some configuration or other dependent change that caused these to appear.

**Comment by aschwaighofer** [comment]
This PR includes  #33816 and #33827 

But I also need to include #31272 and #31035 for the tests to pass.

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test windows

**Pull request merged**
