### PR TITLE
Debug Info: Insert dbg.value intrinsics immediately after the instruction they describe.

### PR DESCRIPTION
**Pull request by adrian-prantl**
```
Debug Info: Insert dbg.value intrinsics immediately after the instruction
they describe.

This improves the live ranges of local variables during debugging.

<rdar://problem/26627376>
```

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci please test and merge

**Comment by adrian-prantl** [comment]
macOS error is unrelated.

**Comment by adrian-prantl** [comment]
@swift-ci please test OS X platform

**Comment by adrian-prantl** [comment]
This time it found an actual error.

**Comment by adrian-prantl** [comment]
@swift-ci please test and merge

**Comment by adrian-prantl** [comment]
@swift-ci please test and merge

**Comment by e78l** [comment]
Hello,
The "Debug Info..." commit seems to have caused build failures in swiftpm for me on Linux. Based on https://bugs.swift.org/browse/SR-2754, I would guess it makes LLVM use a lot of memory when compiling https://github.com/apple/swift-package-manager/blob/master/Sources/Utility/StringMangling.swift

swiftpm built fine after reverting this locally (git revert -m 1 7d7eb082d571fd293db7a6f34ecedb17cf1fd9dc)

**Pull request merged**
