### PR TITLE
[6.0][SIL] Adjust `isTypeMetadataForLayoutAccessible()` to visit more lowered positions

### LINKED ISSUE #71455: `Assertion failed: (type->isLegalFormalType())` when declaring a tuple from a parameter pack expansion
### Description

Follow-up from #67645

### Reproduction

```swift
func foo<each T>(ts: (repeat each T)) {
  let tuple = (repeat ((each T).self, each ts))
}
```

### Stack dump

```text
Assertion failed: (type->isLegalFormalType()), function isTypeMetadataAccessible, file SIL.cpp, line 106.
Stack dump:
0.	Program arguments: ./swift-frontend /Users/simanerush/Developer/Swift/Swift-Files/test.swift -typecheck -interpret
1.	Swift version 5.11-dev (LLVM 69fa38fd6c00774, Swift 2fa1022a912a1c0)
2.	Compiling with the current language version
3.	While evaluating request ASTLoweringRequest(Lowering AST to SIL for module test)
4.	While silgen emitFunction SIL function "@$s4test3foo2tsyxxQp_t_tRvzlF".
 for 'foo(ts:)' (at /Users/simanerush/Developer/Swift/Swift-Files/test.swift:78:1)
5.	While verifying SIL function "@$s4test3foo2tsyxxQp_t_tRvzlF".
 for 'foo(ts:)' (at /Users/simanerush/Developer/Swift/Swift-Files/test.swift:78:1)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x000000010a5de084 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x000000010a5dc718 llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x000000010a5de6cc SignalHandler(int) + 304
3  libsystem_platform.dylib 0x0000000180cbda24 _sigtramp + 56
4  libsystem_pthread.dylib  0x0000000180c8dcc0 pthread_kill + 288
5  libsystem_c.dylib        0x0000000180b99a40 abort + 180
6  libsystem_c.dylib        0x0000000180b98d30 err + 0
7  swift-frontend           0x00000001046c1990 swift::SILModule::isTypeMetadataAccessible(swift::CanType) + 120
8  swift-frontend           0x00000001046c20e4 isTypeMetadataForLayoutAccessible(swift::SILModule&, swift::SILType) + 464
9  swift-frontend           0x00000001046c1ff4 isTypeMetadataForLayoutAccessible(swift::SILModule&, swift::SILType) + 224
10 swift-frontend           0x00000001046c1ec4 swift::SILModule::isTypeMetadataForLayoutAccessible(swift::SILType) + 152
11 swift-frontend           0x00000001046c1d9c swift::SILModule::isTypeABIAccessible(swift::SILType, swift::TypeExpansionContext) + 308
12 swift-frontend           0x00000001046f252c swift::SILFunction::isTypeABIAccessible(swift::SILType) const + 92
13 swift-frontend           0x0000000104a20654 (anonymous namespace)::checkTypeABIAccessible(swift::SILFunction const&, swift::SILType) + 88
14 swift-frontend           0x0000000104a42a20 (anonymous namespace)::SILVerifier::checkDestroyAddrInst(swift::DestroyAddrInst*) + 228
15 swift-frontend           0x0000000104a0bfd8 (anonymous namespace)::SILVerifierBase<(anonymous namespace)::SILVerifier>::visitDestroyAddrInst(swift::DestroyAddrInst*) + 48
16 swift-frontend           0x0000000104a04e78 swift::SILInstructionVisitor<(anonymous namespace)::SILVerifier, void>::visit(swift::SILInstruction*) + 4132
17 swift-frontend           0x0000000104a038e8 swift::SILVisitorBase<(anonymous namespace)::SILVerifier, void>::visitSILBasicBlock(swift::SILBasicBlock*) + 128
18 swift-frontend           0x0000000104a034b4 (anonymous namespace)::SILVerifier::visitSILBasicBlock(swift::SILBasicBlock*) + 36
19 swift-frontend           0x00000001049fd6dc (anonymous namespace)::SILVerifier::visitSILBasicBlocks(swift::SILFunction*) + 176
20 swift-frontend           0x00000001049fbb68 (anonymous namespace)::SILVerifier::visitSILFunction(swift::SILFunction*) + 1788
21 swift-frontend           0x00000001049f5824 (anonymous namespace)::SILVerifier::verify(bool) + 144
22 swift-frontend           0x00000001049f566c swift::SILFunction::verify(swift::CalleeCache*, bool, bool, bool) const + 148
23 swift-frontend           0x00000001035077f8 swift::SILFunction::verifyIncompleteOSSA() const + 48
24 swift-frontend           0x0000000103506bf8 swift::Lowering::SILGenModule::postEmitFunction(swift::SILDeclRef, swift::SILFunction*) + 252
25 swift-frontend           0x0000000103504dd0 swift::Lowering::SILGenModule::emitFunctionDefinition(swift::SILDeclRef, swift::SILFunction*) + 3108
26 swift-frontend           0x00000001035075a4 swift::Lowering::SILGenModule::emitOrDelayFunction(swift::SILDeclRef) + 428
27 swift-frontend           0x0000000103504178 swift::Lowering::SILGenModule::emitFunction(swift::FuncDecl*) + 416
28 swift-frontend           0x0000000103503fcc swift::Lowering::SILGenModule::visitFuncDecl(swift::FuncDecl*) + 32
29 swift-frontend           0x0000000103503ce8 swift::ASTVisitor<swift::Lowering::SILGenModule, void, void, void, void, void, void>::visit(swift::Decl*) + 972
30 swift-frontend           0x000000010350390c swift::Lowering::SILGenModule::visit(swift::Decl*) + 60
31 swift-frontend           0x000000010350bb68 (anonymous namespace)::SILGenModuleRAII::emitSourceFile(swift::SourceFile*) + 308
32 swift-frontend           0x000000010350b718 swift::ASTLoweringRequest::evaluate(swift::Evaluator&, swift::ASTLoweringDescriptor) const + 708
33 swift-frontend           0x00000001037276dc std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>> swift::SimpleRequest<swift::ASTLoweringRequest, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>> (swift::ASTLoweringDescriptor), (swift::RequestFlags)9>::callDerived<0ul>(swift::Evaluator&, std::__1::integer_sequence<unsigned long, 0ul>) const + 116
34 swift-frontend           0x0000000103727628 swift::SimpleRequest<swift::ASTLoweringRequest, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>> (swift::ASTLoweringDescriptor), (swift::RequestFlags)9>::evaluateRequest(swift::ASTLoweringRequest const&, swift::Evaluator&) + 40
35 swift-frontend           0x000000010352ad14 llvm::Expected<swift::ASTLoweringRequest::OutputType> swift::Evaluator::getResultUncached<swift::ASTLoweringRequest>(swift::ASTLoweringRequest const&) + 304
36 swift-frontend           0x000000010350c1c0 llvm::Expected<swift::ASTLoweringRequest::OutputType> swift::Evaluator::operator()<swift::ASTLoweringRequest, (void*)0>(swift::ASTLoweringRequest const&) + 40
37 swift-frontend           0x000000010350c0c8 swift::performASTLowering(swift::ModuleDecl*, swift::Lowering::TypeConverter&, swift::SILOptions const&, swift::IRGenOptions const*) + 188
38 swift-frontend           0x00000001027a96f4 swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 240
39 swift-frontend           0x00000001027d98a0 performAction(swift::CompilerInstance&, int&, swift::FrontendObserver*)::$_28::operator()(swift::CompilerInstance&) const + 140
40 swift-frontend           0x00000001027d9804 bool llvm::function_ref<bool (swift::CompilerInstance&)>::callback_fn<performAction(swift::CompilerInstance&, int&, swift::FrontendObserver*)::$_28>(long, swift::CompilerInstance&) + 32
41 swift-frontend           0x00000001027d8cb4 llvm::function_ref<bool (swift::CompilerInstance&)>::operator()(swift::CompilerInstance&) const + 40
42 swift-frontend           0x00000001027d7afc withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) + 452
43 swift-frontend           0x00000001027d2854 performAction(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 1164
44 swift-frontend           0x00000001027ac47c performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 256
45 swift-frontend           0x00000001027ab124 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 2344
46 swift-frontend           0x000000010264d1ac run_driver(llvm::StringRef, llvm::ArrayRef<char const*>, llvm::ArrayRef<char const*>) + 1744
47 swift-frontend           0x000000010264c034 swift::mainEntry(int, char const**) + 1148
48 swift-frontend           0x000000010264b730 main + 36
49 dyld                     0x000000018090d0e0 start + 2360
```

### Expected behavior

The code should compile

### Environment

Swift version 5.11-dev (LLVM 69fa38fd6c00774, Swift 2fa1022a912a1c0)
Target: arm64-apple-darwin23.2.0

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by simanerush**
## Cherry-pick of #71376 

- **Explanation:** Fixes an issue where `isTypeMetadataForLayoutAccessible()` in SIL did not visit lowered positions for pack expansion types, resulting in compiler crashes.
- **Scope**: Additive change in SIL.
- **Issue:** #71455, #67645,  rdar://119267393
- **Original PR:** #71376 
- **Risk:** Very Low
- **Testing:** Added a test case to the test suite. 
- **Reviewer:** @xedin

### CODE REVIEW

**Comment by simanerush** [comment]
@swift-ci please smoke test

**Comment by simanerush** [comment]
@swift-ci please test

**Review by xedin — APPROVED** [review]
Thank you!

**Comment by hborla** [comment]
Can you please fill out the template from https://forums.swift.org/t/swift-6-0-release-process/70220#pull-requests-for-release-branch-8 in the PR description? Thank you!

**Comment by simanerush** [comment]
@hborla Done!

**Review by hborla — APPROVED** [review]

**Pull request merged**
