### PR TITLE
[5.1][Stdlib] Special-case major version 9999 as always available.

### PR DESCRIPTION
**Pull request by mikeash**
rdar://problem/43776049

### CODE REVIEW

**Comment by mikeash** [comment]
@swift-ci please test and merge

**Comment by lorentey** [comment]
The failure on Linux was due to a package manager issue; it has been resolved by https://github.com/apple/swift-package-manager/pull/2027.

**Comment by lorentey** [comment]
@swift-ci please test linux platform

**Comment by mikeash** [comment]
Not sure what happened that time around. Something crashed but I can't tell what or why. Trying again in the hope that it's spurious.

**Comment by mikeash** [comment]
@swift-ci please test linux platform

**Pull request merged**
