### PR TITLE
[nfc][cxx-interop] Remove brittle, special-case code for old operator implementation; add a test.

### PR DESCRIPTION
**Pull request by zoecarver**

### CODE REVIEW

**Comment by zoecarver** [comment]
@swift-ci please test.

**Review by Huddie — APPROVED** [review]
Awesome! 🚀

**Review by egorzhdan — APPROVED** [review]
This is the best kind of patches. Thanks!

There is also a piece of dead code in ClangImporter:
```cpp
bool importer::isImportedAsStatic(const clang::OverloadedOperatorKind op)
```
but it can be removed in another PR.

**Comment by zoecarver** [comment]
> There is also a piece of dead code in ClangImporter:

Good catch! Updated the patch :)

**Comment by zoecarver** [comment]
@swift-ci please test.

**Pull request merged**
