### PR TITLE
[SR-10150] Specify supported python version in README

### PR DESCRIPTION
**Pull request by nafu**
We cannot follow the instructions in README if we use python 3.x for now.

If we use python 3.x, some errors occur such as: https://bugs.swift.org/browse/SR-9941
The supported python version is unclear and this will block contributors to get started.

There are already some PRs for better python support but those are still WIPs.

- https://github.com/apple/swift/pull/23272
- https://github.com/apple/swift/pull/23038
- https://github.com/apple/swift/pull/23256

Those would take more time to be merged so that revising current README would be better.

Resolves [SR-10150](https://bugs.swift.org/browse/SR-10150).

### CODE REVIEW

**Comment by gottesmm** [comment]
@gwynne again your thoughts?

**Review by gwynne — APPROVED** [review]
Good note to have until Python 3 support is merged.

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by nafu** [comment]
@gottesmm @gwynne Thank you :)

**Pull request merged**
