### PR TITLE
More runtime support for subclass existentials

### PR DESCRIPTION
**Pull request by slavapestov**
Builds upon https://github.com/apple/swift/pull/8876 and https://github.com/apple/swift/pull/8788.

- Runtime metadata instantiation for subclass existentials
- Scalar downcasts
- More tests, mainly casts

Next up: dynamic casts.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by gparker42** [comment]
I suspect this breaks non-smoke tests. An unrelated PR test failed IRGen/subclass_existentials.sil on 32-bit iOS simulator: https://ci.swift.org/job/swift-PR-osx/7053/

**Comment by gparker42** [comment]
Jordan is fixing the test in #9020.

**Comment by jrose-apple** [comment]
Thanks for tracking down the original commit.

**Pull request merged**
