### PR TITLE
[IRGen] fix partial_apply witness method crash

### PR DESCRIPTION
**Pull request by marcrasi**
IRGen crashes while handling `partial_apply` instructions that don't bind the self value of witness methods. For example:
```
  %req = witness_method $T, #P.req : <Self where Self : P><A> (Self) -> (A) -> () : $@convention(witness_method: P) <τ_0_0 where τ_0_0 : P><τ_1_0> (@in_guaranteed τ_1_0, @in_guaranteed τ_0_0) -> ()
  %partially_applied = partial_apply %req<T, S>() : $@convention(witness_method: P) <τ_0_0 where τ_0_0 : P><τ_1_0> (@in_guaranteed τ_1_0, @in_guaranteed τ_0_0) -> ()
```

This is the crash:
```
llvm-project/llvm/lib/IR/Instructions.cpp:400: void llvm::CallInst::init(llvm::FunctionType *, llvm::Value *, ArrayRef<llvm::Value *>, ArrayRef<llvm::OperandBundleDef>, const llvm::Twine &): Assertion `(i >= FTy-
>getNumParams() || FTy->getParamType(i) == Args[i]->getType()) && "Calling a function with a bad signature!"' failed.
```

The crash happens because `emitPartialApplicationForwarder` does not handle the case where the `self` of a witness method is one of the forwarded arguments. This PR fixes the problem by handling this case.

We discovered the problem because AutoDiff generates `partial_apply` instructions that trigger the crash. This PR includes an AutoDiff testcase that triggers the crash.

This PR also includes a non-AutoDiff SIL testcase that triggers the crash. I wasn't able to find non-AutoDiff Swift code that triggers the crash.

### CODE REVIEW

**Comment by slavapestov** [comment]
I think this is fine for `witness_method`, but be advised you can't do this for `class_method`, since there we recover the generic parameters from the `self` value itself.

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by marcrasi** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
