### PR TITLE
[validation-test] Add some scale-tests.

### PR DESCRIPTION
**Pull request by huonw**

### CODE REVIEW

**Comment by huonw** [comment]
@swift-ci Please test and merge.

**Comment by huonw** [comment]
@swift-ci Please test and merge.

**Comment by huonw** [comment]
@swift-ci Please test and merge.

**Comment by huonw** [comment]
@swift-ci Please test and merge.

**Comment by shahmishal** [comment]
@swift-ci Please test and merge

**Comment by shahmishal** [comment]
@huonw  it might have not triggered because of "." at the end of the trigger phrase.

**Comment by huonw** [comment]
Hm, it did trigger for my first comment with its ., before I force-pushed an update.

**Pull request merged**
