### PR TITLE
[Foundation] Simplify the comparison routines for Measurement

### PR DESCRIPTION
**Pull request by phausler**
#### What's in this pull request?

The default implementation for comparable automatically adds >, >= etc by having == and < defined. Also the dynamic check for comparison of measurements that are convertible should traverse through the same runtime equality check instead of a static dispatch call out.
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

This resolves:
rdar://problem/27556581 Measurement type defines two '==' functions

### CODE REVIEW

**Comment by phausler** [comment]
@swift-ci Please smoke test OS X

**Comment by michael-lehew** [comment]
LGTM

**Comment by gribozavr** [comment]
Thanks!  Could you add some tests?  You might want to use `checkEquatable`, it is perfect for testing the Equatable conformance.  Some examples here: https://github.com/apple/swift/pull/4007/files#diff-ed5a4381f29cf62e292c7f51500b3f29R15

**Comment by phausler** [comment]
Closing in favor of a more robust refinement with more testing

**Pull request closed without merging**
