### PR TITLE
LoadableByAddress handle constructors + bug fixes

### PR DESCRIPTION
**Pull request by shajrawi**
radar rdar://problem/48089230

Supports both the re-write of function return values that are multi-element tuples and a more efficient construction for structs and tuples

### CODE REVIEW

**Comment by shajrawi** [comment]
@swift-ci Please test

**Comment by shajrawi** [comment]
@swift-ci Please test source compatibility

**Review by aschwaighofer — COMMENTED** [review]
Can you add test cases that mix more than one layer of tuples, function types, and large loadable types?

Something like:

```
struct Big<T> {
  var a1 : T
  var a2 : T
  var a3 : T
  var a4 : T
  var a5 : T
  var a6 : T
  var a7 : T
  var a8 : T
  init(_ t: T) {
    a1 = t
    a2 = t
    a3 = t
    a4 = t
    a5 = t
    a6 = t
    a7 = t
    a8 = t
  }
}

func nonGeneric() -> ((Big<Int>, Big<Int>), () -> Big<Int>)? {
  return nil
}

func nonGeneric2() -> ((Big<Int>, Big<Int>), () -> Big<Int>) {
  return ((Big(1), Big(2)), { return Big(1) })
}

func generic<T>(_ t: T) -> ((Big<T>, Big<T>), () -> Big<T>)? {
  return nil
}
func generic2<T>(_ t: T) -> ((Big<T>, Big<T>), () -> Big<T>) {
  return ((Big(t), Big(t)), { return Big(t) })
}

func useStuff() {
  print(nonGeneric()!.0)
  print(nonGeneric()!.1)
  print(nonGeneric2().0)
  print(nonGeneric2().1)
  print(generic(1)!.0.0)
  print(generic(1)!.1)
  print(generic2(1).0)
  print(generic2(1).1)
}
```

**Comment by shajrawi** [comment]
@swift-ci Please test

**Comment by shajrawi** [comment]
@swift-ci Please test source compatibility

**Comment by shajrawi** [comment]
`llvm-config: error: component libraries and shared library` - unrelated CI failure for that test.

**Comment by shajrawi** [comment]
@swift-ci Please test

**Comment by shajrawi** [comment]
@swift-ci Please test

**Comment by shajrawi** [comment]
@swift-ci Please test source compatibility

**Comment by shajrawi** [comment]
@swift-ci Please test source compatibility

**Comment by shajrawi** [comment]
```
llvm-config: error: component libraries and shared library
10:50:11 
10:50:11 llvm-config: error: missing: /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/llvm-macosx-x86_64/lib/libLLVMTestingSupport.a
10:50:11 CMake Warning at cmake/Modules/CompilerRTUtils.cmake:263 (message):
10:50:11   llvm-config finding testingsupport failed with status 1
10:50:11 Call Stack (most recent call first):
10:50:11   CMakeLists.txt:69 (load_llvm_config)
```
on all the bots.. will retry after that's fixed.

**Comment by shajrawi** [comment]
@swift-ci Please test

**Comment by shajrawi** [comment]
@swift-ci Please test

**Comment by shajrawi** [comment]
@swift-ci Please test

**Comment by shajrawi** [comment]
@swift-ci Please test

**Comment by shajrawi** [comment]
@swift-ci Please test

**Comment by shajrawi** [comment]
@swift-ci Please test

**Comment by shajrawi** [comment]
@swift-ci Please test

**Comment by shajrawi** [comment]
@swift-ci Please test source compatibility

**Comment by shajrawi** [comment]
@swift-ci Please test source compatibility

**Comment by shajrawi** [comment]
@swift-ci Please test source compatibility

**Comment by shajrawi** [comment]
@swift-ci Please test source compatibility

**Comment by shajrawi** [comment]
@swift-ci Please test

**Comment by shajrawi** [comment]
@swift-ci Please test

**Comment by shajrawi** [comment]
splitting the last commit from this PR

**Comment by shajrawi** [comment]
@swift-ci Please test

**Comment by shajrawi** [comment]
@swift-ci Please test

**Comment by shajrawi** [comment]
@swift-ci Please test macOS

**Comment by shajrawi** [comment]
@swift-ci Please test macOS

**Comment by shajrawi** [comment]
@swift-ci Please test macOS

**Comment by shajrawi** [comment]
@swift-ci Please smoke test macOS

**Comment by shajrawi** [comment]
@swift-ci Please smoke test macOS

**Comment by shajrawi** [comment]
@swift-ci Please smoke test macOS

**Comment by shajrawi** [comment]
@swift-ci Please test macOS

**Comment by shajrawi** [comment]
Mac CI bot not triggering a test, will try to create a new PR

**Comment by shajrawi** [comment]
re-created the PR at https://github.com/apple/swift/pull/23276

**Pull request closed without merging**
