### PR TITLE
Run tests with `-tf-target-gpu` when `--enable-tensorflow-gpu` is enabled.

### PR DESCRIPTION
**Pull request by dan-zheng**
This patch should make GPU tests pass, which is important for a future GPU CI machine. Run the following:
```
swift/utils/build-script --preset tensorflow_test,gpu
```

Thanks to @mhong for verifying that tests pass locally.

### CODE REVIEW

**Comment by mhong** [comment]
Great work, Dan! Notes from my local testing

1. Confirm the compiler flag is passed properly

```
$ ../llvm/utils/lit/lit.py -asv --param swift_tensorflow_gpu  --param swift_test_mode=optimize --param swift_tensorflow_path=../build/bazel-bin/tensorflow ../build/Ninja-ReleaseAssert+stdlib-Release/swift-linux-x86_64/test-linux-x86_64/TensorFlowRuntime/tensor_debuglog.swift
```

Its output includes this, where `-Xllvm -tf-target-tpu` is present:
```
/usr/local/google/home/hongm/ssd_part/git/swift-base/build/Ninja-ReleaseAssert+stdlib-Release/swift-linux-x86_64/bin/swift -frontend -target x86_64-unknown-linux-gnu  -module-cache-path '/usr/local/google/home/hongm/ssd_part/git/swift-base/build/Ninja-ReleaseAssert+stdlib-Release/swift-linux-x86_64/swift-test-results/x86_64-unknown-linux-gnu/clang-module-cache' -swift-version 4  -Xllvm -tf-dump-intermediates -Xllvm -tf-dump-graph -Xllvm -tf-target-tpu -O -emit-sil /usr/local/google/home/hongm/ssd_part/git/swift-base/swift/test/TensorFlowRuntime/tensor_debuglog.swift >/dev/null
```

2. Run all existing runtime tests under GPU
```
../llvm/utils/lit/lit.py -sv --param swift_tensorflow_gpu  --param swift_test_mode=optimize --param swift_tensorflow_path=../build/bazel-bin/tensorflow ../build/Ninja-ReleaseAssert+stdlib-Release/swift-linux-x86_64/test-linux-x86_64/TensorFlowRuntime/
```
We got:
```
-- Testing: 24 tests, 12 threads --
Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90.. 
Testing Time: 13.16s
  Expected Passes    : 23
  Unsupported Tests  : 1
```

3. Confirm a test case could fail if it uses an op that does not have GPU kernel.

Test case:
```swift
public func foo() {
  TensorFlow.enableGPU()
  let a = Tensor<Float>(1.0)
  _hostOp(a)
  #tfop("Assert", Tensor<Bool>(true), [a]) as Void
  expectEqualWithScalarTensor(1, a)
}
SendsRecvsTests.testAllBackends("foo", foo)

runAllTests()
```
As expected, we get:
```
stderr>>> No registered 'Assert' OpKernel for GPU devices compatible with node {{node op/foo.._2.44.13_/device_GPU_0}} = Assert[T=[DT_FLOAT], summarize=3, _device="/device:GPU:0"](op/foo.._1.44.13_/device_GPU_0, op/foo...44.13_/device_GPU_0)
```

If we comment out `TensorFlow.enableGPU()`, the test works.

**Review by mhong — APPROVED** [review]

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
Awaiting e2e test of the following commands, on a GPU-enabled machine:
```
git clone https://github.com/dan-zheng/swift.git -b use-gpu-flag-for-tests
./swift/utils/update-checkout --clone --scheme tensorflow
swift/utils/build-script --preset tensorflow_test,gpu
```

**Comment by dan-zheng** [comment]
Fixed to use `--param swift_tensorflow_gpu=true` in https://github.com/apple/swift/pull/18585/commits/4f3b0af8f9211f1e895bb92f15e30f340118b719.

**Comment by mhong** [comment]
Dan, I suggest landing this patch, if the CPU testing still passes.

I'll then send follow-up PRs to disable / fix relevant GPU tests, so that GPU testing will pass as well.

Thanks again for the nice work!

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
Thanks @mhong!
Merging.

**Pull request merged**
