### PR TITLE
Fix some more misuses of LLVM's YAML parser

### PR DESCRIPTION
**Pull request by jrose-apple**
Follow-up for #15111. https://reviews.llvm.org/D44317 should prevent this from happening again.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Review by davidungar — APPROVED** [review]
Great!

**Comment by jrose-apple** [comment]
Linux tests got interrupted somehow.

@swift-ci Please smoke test Linux

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test Linux

**Pull request merged**
