### PR TITLE
Track whether a task is actively running

### PR DESCRIPTION
**Pull request by rjmccall**
Tracking this as a single bit is actually largely uninteresting to the runtime.  To handle priority escalation properly, we really need to track this at a finer grain of detail: recording that the task is running on a specific thread, enqueued on a specific actor, or so on.  But starting by tracking a single bit is important for two reasons:
    
- First, it's more realistic about the performance overheads of tasks: we're going to be doing this tracking eventually, and the cost of that tracking will be dominated by the atomic access, so doing that access now sets the baseline about right.
    
- Second, it ensures that we've actually got runtime involvement in all the right places to do this tracking.
    
*A propos* of the latter: there was no runtime involvement with awaiting a continuation, which is a point at which the task potentially transitions from running to suspended.  We must do the tracking as part of this transition, rather than recognizing in the run-loops that a task is still active and treating it as having suspended, because the latter point potentially races with the resumption of the task.  To do this, I've had to introduce a runtime function, swift_continuation_await, to do this awaiting rather than inlining the atomic operation on the continuation.

Some related fixes and enhancements are included in this PR; see the commit list for details.

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please test

**Comment by rjmccall** [comment]
@swift-ci Please test

**Comment by rjmccall** [comment]
@swift-ci Please test

**Comment by rjmccall** [comment]
@swift-ci Please test

**Comment by rjmccall** [comment]
@swift-ci Please test

**Comment by rjmccall** [comment]
@swift-ci Please test Linux

**Comment by CodaFi** [comment]
@swift-ci test macOS platform

**Comment by rjmccall** [comment]
@swift-ci Please test Linux

**Comment by rjmccall** [comment]
@swift-ci Please test Windows

**Comment by dabezt31** [comment]
Why tf is it failing so many times

**Comment by rjmccall** [comment]
Well, some of them are my fault (portability problems that didn't show up in my testing), and some of them aren't (builder instability, maybe a broken test from a different PR).

**Pull request merged**
