### PR TITLE
[Runtime][ABI] Have swift_willThrow take the error value in the return register.

### PR DESCRIPTION
**Pull request by mikeash**
This modifies the `swift_willThrow` function to take its error parameter in the error return register. This will allow for reduced code size by eliminating the need to shuffle registers around quite so much, since the error can stay in the same place. (Currently we aren't giving LLVM quite enough information to actually achieve this in practice, but with this change, we'll be able to make that happen.)

~~Since this function exists for the benefit of lldb, lldb may need a corresponding update. Holding this PR until we figure that out.~~ Update: lldb doesn't inspect the parameter currently, so it's all good.

rdar://problem/37578477

### CODE REVIEW

**Review by aschwaighofer — APPROVED** [review]
Looks good to me.

**Comment by mikeash** [comment]
@swift-ci please test

**Review by jckarter — APPROVED** [review]
Thanks for picking this up!

**Comment by mikeash** [comment]
@jckarter Thanks for doing all the hard parts for me. 😸

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test linux

**Comment by mikeash** [comment]
@swift-ci please test linux

**Comment by mikeash** [comment]
@swift-ci please test linux

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test

**Pull request merged**
