### PR TITLE
[SILOpt] Run DestroyAddrHoisting in the mandatory pipeline when optimizing.

### PR DESCRIPTION
**Pull request by nate-chandler**
Run SSADestroyHoisting in the pipeline where DestroyHoisting was previously running.

rdar://90495704

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
preset=buildbot,tools=R,stdlib=RD
@swift-ci Please test with preset macOS

**Comment by nate-chandler** [comment]
@swift-ci please build toolchain macOS

**Review by atrick — APPROVED** [review]
Thanks!

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test macOS platform

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Pull request merged**
