### PR TITLE
[DON'T MERGE] TEST

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test new Xcode

**Comment by shahmishal** [comment]
@swift-ci test new Xcode

**Comment by shahmishal** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by shahmishal** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by shahmishal** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by shahmishal** [comment]
@swift-ci test new Xcode

**Comment by shahmishal** [comment]
@swift-ci Please test macOS Apple Silicon

**Comment by shahmishal** [comment]
@swift-ci Please test Apple Silicon

**Comment by abertelrud** [comment]
https://github.com/apple/swift-package-manager/pull/3334
@swift-ci Please test Apple Silicon

**Comment by shahmishal** [comment]
apple/swift-package-manager#3334
@swift-ci Please test Apple Silicon

**Comment by shahmishal** [comment]
https://github.com/apple/swift-integration-tests/pull/86
@swift-ci test CentOS 8

**Comment by shahmishal** [comment]
https://github.com/apple/llvm-project/pull/2930
@swift-ci test Windows

**Comment by shahmishal** [comment]
@swift-ci test new Xcode

**Comment by shahmishal** [comment]
@swift-ci smoke Apple Silicon benchmark

**Comment by abertelrud** [comment]
https://github.com/apple/swift-package-manager/pull/3540
@swift-ci build toolchain

**Comment by shahmishal** [comment]
@swift-ci smoke Apple Silicon benchmark GlobalISel

**Comment by shahmishal** [comment]
@swift-ci Apple Silicon benchmark GlobalISel

**Comment by shahmishal** [comment]
@swift-ci test new Xcode

**Comment by abertelrud** [comment]
apple/swift-package-manager#3536
@swift-ci build toolchain

**Comment by abertelrud** [comment]
apple/swift-package-manager#3536
@swift-ci build toolchain

**Comment by abertelrud** [comment]
https://github.com/apple/swift-package-manager/pull/3545
@swift-ci build toolchain

**Comment by shahmishal** [comment]
**Errors Detected:** Unexpected pass.
Log: [Swift Test macOS Platform (smoke test)](https://ci.swift.org/job/oss-swift-incremental-RA-macos/)

```
Unexpectedly Passed Tests (2):
   lldb-shell :: SwiftREPL/ResilientDict.test
   lldb-shell :: SwiftREPL/ResilientArray.test
```

**Comment by shahmishal** [comment]
https://github.com/apple/swift-driver/pull/772
https://github.com/apple/llvm-project/pull/3125
@swift-ci build toolchain

**Comment by shahmishal** [comment]
@swift-ci test new Xcode

**Comment by bitjammer** [comment]
https://github.com/apple/swift-driver/pull/772
https://github.com/apple/llvm-project/pull/3125

@swift-ci build toolchain

**Comment by bitjammer** [comment]
https://github.com/apple/swift-driver/pull/772
https://github.com/apple/llvm-project/pull/3125

@swift-ci build toolchain Linux Platform

**Comment by bitjammer** [comment]
https://github.com/apple/swift-driver/pull/772
https://github.com/apple/llvm-project/pull/3125

@swift-ci build toolchain

**Comment by bitjammer** [comment]
https://github.com/apple/swift-driver/pull/772
https://github.com/apple/llvm-project/pull/3125

@swift-ci build toolchain

**Comment by bitjammer** [comment]
https://github.com/apple/swift-driver/pull/772
https://github.com/apple/llvm-project/pull/3125

@swift-ci build toolchain

**Comment by bitjammer** [comment]
https://github.com/apple/swift-driver/pull/772
https://github.com/apple/llvm-project/pull/3125

@swift-ci build toolchain macOS Platform

**Comment by bitjammer** [comment]
https://github.com/apple/swift-driver/pull/772
https://github.com/apple/llvm-project/pull/3125

@swift-ci build toolchain macOS Platform

**Comment by bitjammer** [comment]
https://github.com/apple/swift-driver/pull/772
https://github.com/apple/llvm-project/pull/3125

@swift-ci build toolchain macOS Platform

**Comment by bitjammer** [comment]
https://github.com/apple/swift-driver/pull/772
https://github.com/apple/llvm-project/pull/3125

@swift-ci build toolchain macOS Platform

**Comment by bitjammer** [comment]
https://github.com/apple/swift-driver/pull/772
https://github.com/apple/llvm-project/pull/3125

@swift-ci build toolchain macOS Platform

**Comment by bitjammer** [comment]
https://github.com/apple/swift-driver/pull/772
https://github.com/apple/llvm-project/pull/3125

@swift-ci build toolchain macOS Platform

**Comment by bitjammer** [comment]
https://github.com/apple/swift-driver/pull/772
https://github.com/apple/llvm-project/pull/3125

@swift-ci build toolchain macOS Platform

**Comment by bitjammer** [comment]
https://github.com/apple/swift-driver/pull/772
https://github.com/apple/llvm-project/pull/3125

@swift-ci build toolchain macOS Platform

**Comment by shahmishal** [comment]
@swift-ci build toolchain new Xcode

**Comment by shahmishal** [comment]
@swift-ci test new Xcode

**Comment by shahmishal** [comment]
@swift-ci build toolchain new Xcode

**Comment by shahmishal** [comment]
@swift-ci test new Xcode

**Comment by shahmishal** [comment]
https://github.com/apple/swift-collections/pull/111
@swift-ci build toolchain

**Comment by shahmishal** [comment]
@swift-ci test-new

**Comment by shahmishal** [comment]
@swift-ci test-new

**Comment by shahmishal** [comment]
@swift-ci smoke test Linux

**Comment by shahmishal** [comment]
@swift-ci-test test

**Comment by shahmishal** [comment]
@swift-ci-test test

**Comment by shahmishal** [comment]
@swift-ci-test test

**Comment by shahmishal** [comment]
@swift-ci-test test Linux

**Comment by shahmishal** [comment]
@swift-ci-test test Linux

**Comment by shahmishal** [comment]
@swift-ci-test test Linux

**Comment by shahmishal** [comment]
@swift-ci-test test Linux

**Comment by NuriAmari** [comment]
@swift-ci-test test Linux

**Comment by shahmishal** [comment]
@swift-ci-test smoke test Linux

**Comment by shahmishal** [comment]
@swift-ci-test smoke test Linux

**Comment by shahmishal** [comment]
@swift-ci-test smoke test Linux

**Comment by shahmishal** [comment]
@swift-ci-test test Linux

**Comment by shahmishal** [comment]
@swift-ci-test test and merge

**Comment by shahmishal** [comment]
@swift-ci-test test and merge

**Comment by shahmishal** [comment]
@swift-ci-test smoke test and merge

**Comment by shahmishal** [comment]
@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
@swift-ci test source compat

**Comment by shahmishal** [comment]
@swift-ci test source compat debug

**Comment by shahmishal** [comment]
@swift-ci test source compat debug

**Comment by shahmishal** [comment]
@swift-ci benchmark

**Comment by shahmishal** [comment]
@swift-ci please test compiler performance

**Comment by shahmishal** [comment]
@swift-ci Please build toolchain Linux

**Comment by shahmishal** [comment]
@swift-ci please smoke test compiler performance

**Comment by shahmishal** [comment]
@swift-ci please smoke test compiler performance

**Comment by shahmishal** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by shahmishal** [comment]
@swift-ci please test stdlib with toolchain

**Comment by shahmishal** [comment]
@swift-ci please test stdlib with toolchain

**Comment by shahmishal** [comment]
preset=buildbot_incremental,tools=RA,stdlib=RD,smoketest=macosx,flto
@swift-ci Please test with preset macOS Platform

**Comment by shahmishal** [comment]
@swift-ci build toolchain Windows

**Comment by shahmishal** [comment]
@swift-ci build toolchain Linux

**Comment by shahmishal** [comment]
@swift-ci-test test

**Comment by shahmishal** [comment]
@swift-ci-test test

**Comment by shahmishal** [comment]
@swift-ci test Windows

**Comment by shahmishal** [comment]
@swift-ci test Windows

**Comment by shahmishal** [comment]
@swift-ci test Windows

**Pull request closed without merging**
