### PR TITLE
[DNM] swift-driver testing pr

### PR DESCRIPTION
**Pull request by owenv**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

Testing https://github.com/apple/swift-driver/pull/263

### CODE REVIEW

**Comment by owenv** [comment]
https://github.com/apple/swift-driver/pull/263

@swift-ci please test

**Comment by shahmishal** [comment]
main branch on swift is not ready yet, please use master.

**Comment by shahmishal** [comment]
main branch is ready now

**Comment by artemcm** [comment]
apple/swift-driver#263

@swift-ci please test

**Pull request closed without merging**
