### PR TITLE
Fix the type-checker's recursive value type checking.

### PR DESCRIPTION
**Pull request by rjmccall**
Fixes rdar://30355804

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Comment by slavapestov** [comment]
Does this fix rdar://30010094 as well?

**Comment by rjmccall** [comment]
Apparently not, probably because it's multi-file.

**Comment by rjmccall** [comment]
@slavapestov #8729

**Pull request merged**
