### PR TITLE
[Syntax] add UTF-8 BOM support to libSyntax

### PR DESCRIPTION
**Pull request by omochi**
This PR add UTF8-BOM support to libSyntax.
3 bytes sequence `EF BB BF` at `BufferStart` is treated UTF-8 BOM in Lexer.
UTF-8 BOM becomes TriviaPiece and kind is `TriviaKind::garbageText`.

First commit is adding of tests to prevent regression.
So it just tests behavior of Lexer before PR.

There are 5 cases below.
- CommentRetentionMode::None + TriviaRetentionMode::WithoutTrivia
- CommentRetentionMode::ReturnAsTokens + TriviaRetentionMode::WithoutTrivia
- CommentRetentionMode::AttachToNextToken + TriviaRetentionMode::WithoutTrivia
- CommentRetentionMode::None + TriviaRetentionMode::WithTrivia
- CommentRetentionMode::AttachToNextToken + TriviaRetentionMode::WithTrivia

Second commit is changes to implement BOM handling,
and changes tests a little in first commit.

### CODE REVIEW

**Comment by rintaro** [comment]
I think the whole of the second commit can be just inserting this:
```cpp
if (CurPtr == ContentStart && ContentStart != BufferStart) {
  // Add UTF8-BOM to LeadingTrivia.
  LeadingTrivia.push_back(TriviaPiece::garbageText({BufferStart, ContentStart - BufferStart}));
}
```
between L2037 and L2038 https://github.com/apple/swift/blob/861ee3a11211369a78853c853a9e0145c0beff6a/lib/Parse/Lexer.cpp#L2037-L2038

What do you think?

**Comment by rintaro** [comment]
Could you add `"\xEF\xBB\xBF" "aaa"` test case with `isAtStartOfLine()` check?
I'm not sure your current solution works as expected

**Comment by omochi** [comment]
Oh it is very simple, so cool.
Function is perfect.

But I think it has a problem.

In my work, I followed these rules below which I read from existing codes.

1. All token, trivia, comment, white spaces are read from position of `CurPtr` or front for peeking. never see back. (front means greater address, like `CurPtr + 1`)

2. All trivia are generated in `lexTrivia`.

Your idea violates both.

I think rule 1 is very important for code reader.
Because this rule is consistent in whole of Lexer and
this is well known design pattern so often seen in 
other programming languages parser implementation.
So it is surprising that generating BOM trivia at `CurPtr - 3 (== BufferStart)`.

I think rule 2 is can be ignored.
Because this is specific design for this Lexer and 
area of influence is small.

In conclusion, my new proposal is below.

Keep my changes in constructor L191-L193.
https://github.com/apple/swift/blob/861ee3a11211369a78853c853a9e0145c0beff6a/lib/Parse/Lexer.cpp#L191-L194

```
  // Keep information about existance of UTF-8 BOM for transparency source code
  // editing with libSyntax.
  CurPtr = BufferStart;
  ContentStart = BufferStart + BOMLength;
```

Make new change at beginning of `lexImpl` to below.

https://github.com/apple/swift/blob/861ee3a11211369a78853c853a9e0145c0beff6a/lib/Parse/Lexer.cpp#L2035-L2039

```
  if (TriviaRetention == TriviaRetentionMode::WithTrivia) {
    LeadingTrivia.clear();
    TrailingTrivia.clear();
    
    if (CurPtr == BufferStart && BufferStart < ContentStart) {
      // Add UTF8-BOM to LeadingTrivia.
      size_t len = ContentStart - BufferStart;
      assert(len == 3 && "UTF-8 BOM is 3 bytes");
      LeadingTrivia.push_back(TriviaPiece::garbageText({BufferStart, len}));
      CurPtr += len;
    }
  }
  NextToken.setAtStartOfLine(CurPtr == ContentStart);
```

Other changes are discarded.

**Comment by rintaro** [comment]
Okey, but `WithoutTrivia` mode still need to *skip* the BOM, right?
How about this?
```cpp
  if (TriviaRetention == TriviaRetentionMode::WithTrivia) {
    LeadingTrivia.clear();
    TrailingTrivia.clear();
  }
  if (CurPtr == BufferStart) {
    if (BufferStart < ContentStart) {
      if (TriviaRetention == TriviaRetentionMode::WithTrivia) {
        // Add UTF8-BOM to LeadingTrivia.
      }
      // Consume UTF8-BOM.
      CurPtr = ContentStart;
    }
    NextToken.setAtStartOfLine(true);
  } else {
    NextToken.setAtStartOfLine(false);
  }
```

**Comment by omochi** [comment]
Oh. Yes my code is wrong with `WithoutTrivia`.
I think its good.
I will update commit tomorrow.

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by omochi** [comment]
thank you @rintaro 😁

**Pull request merged**
