### PR TITLE
Improvements for cross-module-optimization

### PR DESCRIPTION
**Pull request by eeckstein**
* Include small non-generic functions for serializaion
* serialize initializer of global variables: so that global let variables can be constant propagated across modules

rdar://problem/60696510

For details see the commit messages

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Comment by eeckstein** [comment]
@swift-ci test linux

**Comment by compnerd** [comment]
Hey @eeckstein - this seems to have been checked in with a failing windows test.  The CI actually caught that, and the bots are currently red.  Could you please look into that or revert this please?

**Comment by eeckstein** [comment]
@compnerd Sorry, I didn't look at the windows build log. https://github.com/apple/swift/pull/32520 will fix it. Unfortunately PR testing is currently broken, so I cannot merge it :-(

**Pull request merged**
