### PR TITLE
Add Dictionary and Set {En,De}codable conformance

### PR DESCRIPTION
**Pull request by itaiferber**
Cherry-pick of #9231 to swift-4.0-branch
rdar://problem/30634792

### CODE REVIEW

**Comment by itaiferber** [comment]
@swift-ci Please smoke test and merge

**Comment by itaiferber** [comment]
@shahmishal Linux failed because it couldn't check out the `swift-4.0-branch` for a bunch of repos; any idea what's going on here?

**Comment by itaiferber** [comment]
@swift-ci Please clean smoke test and merge

**Comment by shahmishal** [comment]
@itaiferber For release branch you will need to run full test. "@swift-ci please test and merge"

**Comment by itaiferber** [comment]
@shahmishal Ah, thanks!

**Comment by itaiferber** [comment]
@swift-ci Please test and merge

**Comment by shahmishal** [comment]
@swift-ci Please clean test and merge

**Pull request merged**
