### PR TITLE
[AutoDiff] Fix ownership error in `VJPCloner::visitApplyInst`.

### PR DESCRIPTION
**Pull request by dan-zheng**
Change the following code pattern:

```
%x1 = convert_function %x0 : $@differentiable (...) -> ...
%x2 = begin_borrow %x1
... // use %x2
%x3 = end_borrow %x2
destroy_value %x0
```

To the following:

```
%x1 = begin_borrow %x0 : $@differentiable (...) -> ...
%x2 = convert_function %x0
... // use %x2
%x3 = end_borrow %x1
destroy_value %x0
```

Resolves SR-13933: "multiple consuming users" ownership error caused by
`VJPCloner::visitApply` related to `@differentiable`-function-typed callees.

Also upstream [test/AutoDiff/SILOptimizer/generics.swift](http://github.com/apple/swift/tree/tensorflow/test/AutoDiff/downstream/generics.swift) from `tensorflow` branch.

### CODE REVIEW

**Comment by dan-zheng** [comment]
@swift-ci Please smoke test

**Review by marcrasi — APPROVED** [review]

**Review by rxwei — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by dan-zheng** [comment]
There was a flaky AutoDiff test on Linux, which we've seen before, so I temporary disabled it with an explanation.

<details>
<p>

```
15:51:19 FAIL: Swift(linux-x86_64) :: AutoDiff/compiler_crashers_fixed/sr12732-optimize-partial-apply-convention-thin-only.swift (13818 of 13862)
15:51:19 ******************** TEST 'Swift(linux-x86_64) :: AutoDiff/compiler_crashers_fixed/sr12732-optimize-partial-apply-convention-thin-only.swift' FAILED ********************
15:51:19 Script:
15:51:19 --
15:51:19 : 'RUN: at line 1';   /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-main/buildbot_linux/swift-linux-x86_64/bin/swiftc -target x86_64-unknown-linux-gnu -toolchain-stdlib-rpath  -module-cache-path /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-main/buildbot_linux/swift-linux-x86_64/swift-test-results/x86_64-unknown-linux-gnu/clang-module-cache -swift-version 4  -Xfrontend -ignore-module-source-info  -Osize /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-main/swift/test/AutoDiff/compiler_crashers_fixed/sr12732-optimize-partial-apply-convention-thin-only.swift
15:51:19 --
15:51:19 Exit Code: 254
15:51:19 
15:51:19 Command Output (stderr):
15:51:19 --
15:51:19 
clang-10: error: unable to execute command: Bus error (core dumped)
15:51:19 clang-10: error: linker command failed due to signal (use -v to see invocation)
15:51:19 <unknown>:0: error: link command failed with exit code 254 (use -v to see invocation)
15:51:19 
15:51:19 --
15:51:19 
15:51:19 ********************
```

</p>
</details>

**Comment by dan-zheng** [comment]
@swift-ci Please test

**Pull request merged**
