### PR TITLE
[inliner] Make inlining of @inline(__always) a guaranteed optimization run after diagnostics.

### PR DESCRIPTION
**Pull request by gottesmm**
This PR just adds it to the pass pipeline. I am testing the first commit in a different PR.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test compiler performance

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
Some tests are going to fail. I am going to see if I can just disable this on them. Most of them are not actually testing the facilities of always inlining (e.x.: a debug info test).

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
Hmmm... seems real. I wonder if this is a miscompile.

**Comment by gottesmm** [comment]
As expected, the always inline hit -Onone code in code-size. Looks like with -O the amount of bytes output shrank a little in an insignificant way! -0.11%. 

I am not surprised since we always are going to inline these.

**Comment by slavapestov** [comment]
Why does the compile time increase even in release mode? I would naively expect we're doing the same amount of inlining with -O.

**Comment by slavapestov** [comment]
Does this force inlining of generic `@inline(always)` functions? It appears that it doesn't. We might want it to do that for consistency with `@_transparent`, which is inlined even when generic.

**Comment by gottesmm** [comment]
@slavapestov I think the reason why we emit more code is that we are inlining before a bunch of cleanups have happened. That is my guess.

I would rather run devirt before this on always inline functions in a pass pipeline rather than add support to the inliner for that.

**Comment by atrick** [comment]
@gottesmm @slavapestov @eeckstein I was going to add an `@inline(optimize)` and migrate most stdlib functions to that before adding a new always-inline pass. Yes, `@inline(always)` should apply to -Onone and generics, but I don't think it should be used as an optimizer "hint". In fact, optimizer hints should not generally affect the pass pipeline; that will be a very confusing world (and waste compile time). Sometimes we have explicit pipeline directives, like `@optimize(late)`. And `@optimize(always)` can also effectively mean "inline early". But simply biasing something toward being inlined should not affect pass order.

I suspect the immediate need here is not to fix `@inline(always)` semantics, but instead some other pass pipeline bug that blocks optimization. The real problem needs to be explained so we can undo the workaround when it's fixed. @gottesmm when inserting a new pass in the pipeline, the pass order requirements should be documented. If there are any hard or soft dependencies on other passes, that should be explicit, along with explaining the original motivation for running the pass at that point. I've tried to do this in pass file headers, but in cases like this, commenting the pipeline itself would be helpful.

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
