### PR TITLE
[Parse] Fix issue with incremental re-parsing for SwiftSyntax emitting bogus parsing error

### PR DESCRIPTION
**Pull request by akyrtzi**
rdar://60232712

### CODE REVIEW

**Review by nathawes — APPROVED** [review]
LGTM!

**Comment by akyrtzi** [comment]
@swift-ci smoke test and merge

**Comment by akyrtzi** [comment]
@swift-ci smoke test

**Comment by akyrtzi** [comment]
@swift-ci smoke test

**Comment by akyrtzi** [comment]
@swift-ci smoke test OS X platform

**Pull request merged**
