### PR TITLE
[AST/Sema] Don't crash when referencing enum case in where-clause

### PR DESCRIPTION
**Pull request by JaSpa**
#### What's in this pull request?

Before, something like this crashed:

``` swift
protocol P {}
enum E<T where E.C : P> { case C }
```

The compiler tried to compute the interface type of the `C` case, but failed because `E` had no generic signature set. Now it bails out before trying to do this, producing the correct error message about `C` being no member type of `E`.

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by tkremenek** [comment]
@swift-ci please test

**Comment by tkremenek** [comment]
@DougGregor please review.

**Comment by practicalswift** [comment]
@JaSpa Thanks for taking on `28224-swift-genericfunctiontype-get.swift`! :+1:

**Comment by tkremenek** [comment]
@swift-ci Please test

**Comment by DougGregor** [comment]
LGTM

**Comment by JaSpa** [comment]
I resolved the merge conflict

**Comment by tkremenek** [comment]
@swift-ci Please test

**Pull request merged**
