### PR TITLE
Add CHANGELOG.md entry about @objc(Name) on enums and enum cases

### PR DESCRIPTION
**Pull request by lilyball**

### CODE REVIEW

**Comment by kballard** [comment]
#797 should be merged before this.

**Comment by jrose-apple** [comment]
We actually had a Radar for this too, rdar://problem/21930334. Can you add that in the same style as the other Radar references?

**Comment by kballard** [comment]
Sure thing.

**Comment by kballard** [comment]
PR updated.

**Comment by jrose-apple** [comment]
Thanks!

**Pull request merged**
