### PR TITLE
[benchmarks] Add support for building the benchmarks via build-script…

### PR DESCRIPTION
**Pull request by gottesmm**
… against the just created toolchain.

Now one can on Darwin/Linux build the benchmarks via swiftpm from build-script by passing in:

```
build-script $NORMAL_ARGS --install-swift --install-swiftpm --install-llbuild --toolchain-benchmarks --swiftpm --llbuild
```

This is done using the infrastructure that BenL added for sourcekit-lsp.

----

NOTE: Disabled by default.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by compnerd** [comment]
CC: @drodriguez

**Comment by gottesmm** [comment]
@compnerd @drodriguez once you guys get the install part of build-script up, I am going to change this so that we produce binaries more like what the cmake benchmark suite currently does (i.e. Benchmark_Onone, Benchmark_O, Benchmark_Osize).

**Comment by drodriguez** [comment]
Thanks for the CC.

I think I have some local commit dealing with IndexStore-DB and SourceKit-LSP which should apply quite cleanly to these Benchmarks. Having a product inside another product seems new, but I don’t expect it to be a problem. I also like a lot more `has_target_needing_toolchain` than `is_build_script_impl_product` (I might do that rename). The binary names can be change before or after (it might take a while to land everything up to this part).

**Pull request merged**
