### PR TITLE
Fix coverage test on Windows

### PR DESCRIPTION
**Pull request by keith**
Relying on $PWD made this invalid on Windows

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Review by compnerd — APPROVED** [review]
This seems good to repair the build.  Do you think that you could do a follow up change to use something other than `foo`, `bar`, `baz` (`outer`, `middle`, `inner` or something else a bit more meaningful would be great).

**Comment by compnerd** [comment]
@swift-ci please smoke test macOS platform

**Comment by compnerd** [comment]
@swift-ci please smoke test Linux platform

**Comment by keith** [comment]
Yea sure I can clean that up

**Comment by keith** [comment]
Here's the follow up! https://github.com/apple/swift/pull/32443

**Pull request merged**
