### PR TITLE
AST: Targeted fix for conformance lookup issue

### PR DESCRIPTION
**Pull request by slavapestov**
When substituting a type like T.A.B where A and B are
associated types and the conformance requirement on T.A
is implied by conformance requirements on T, we would
crash.

The problem is that we have no way of representing an
abstract conformance with nested concrete types.

This patch adds a workaround that we can live with until
ConformanceAccessPaths are plumbed through all the way.

Fixes <rdar://problem/30737546> and
<https://bugs.swift.org/browse/SR-3500>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@DougGregor So this is the hack I put into 3.1, but ported to master... Unfortunately, it doesn't build the standard library. Gah!

**Comment by DougGregor** [comment]
It *looks* okay; I'm surprised it blows up in the standard library.

**Comment by slavapestov** [comment]
I'll look into it further soon. It wouldn't be the first time a fix exposed a bug elsewhere, after all :)

**Comment by swiftix** [comment]
When it is planned to be merged? It may unblock/fix quite some radars ;-)

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Pull request merged**
