### PR TITLE
[cxx-interop] Copy bridging header to same directory as other headers

### PR DESCRIPTION
**Pull request by drodriguez**
The `bridging` header for C++ interop was calculating an include directory using `CMAKE_BINARY_DIR` and `CMAKE_CFG_INTDIR` while the rest of the headers consistently use `CMAKE_CURRENT_BINARY_DIR` and no `CMAKE_CFG_INTDIR`.

In some configurations of CMake (for example when using Swift as an external project of LLVM and building an unified toolchain), this means that the `brigding` header will end up in a different directory than the rest of the headers, which complicates testing.

The changes in this commit reuses `SWIFT_INCLUDE_DIR` to keep consistency with the rest of the headers. Any build started by `build-script` should not notice the difference.

### CODE REVIEW

**Comment by drodriguez** [comment]
@swift-ci please test

**Review by kalebers — APPROVED** [review]

**Comment by egorzhdan** [comment]
Thanks @drodriguez!
Looks like there's a merge conflict since I landed https://github.com/apple/swift/pull/72186 a few days ago, would you mind rebasing this?

**Comment by drodriguez** [comment]
@swift-ci please test

**Review by egorzhdan — APPROVED** [review]
LGTM!

**Pull request merged**
