### PR TITLE
Symbol graph support

### PR DESCRIPTION
**Pull request by bitjammer**
Adds a tool `swift-symbolgraph-extract` that reads an existing Swift
module and prints a platform- and language-agnostic JSON description of
the module, primarly for documentation.

Adds a small sub-library `SymbolGraphGen` which houses the core
implementation for collecting relevant information about declarations.
The main entry point is integrated directly into the driver as a mode:
the tool is meant to be run outside of the normal edit-compile-run/test
workflow to avoid impacting build times.

Along with common options for other tools, unique options include
`pretty-print` for debugging, and a `minimum-access-level` options for
including internal documentation.

A symbol graph is a directed graph where the nodes are symbols in a
module and the edges are relationships between them. For example, a
`struct S` may have a member `var x`. The graph would have two nodes for
`S` and `x`, and one "member-of" relationship edge. Other relationship
kinds include "inherits-from" or "conforms to". The data format for a
symbol graph is still under development and may change without notice
until a specificiation and versioning scheme is published.

Various aspects about a symbol are recorded in the nodes, such as
availability, documentation comments, or data needed for printing the
shapes of declarations without having to understand specifics about the
langauge.

Implicit and public-underscored stdlib declarations are not included by
default.

rdar://problem/55346798

### CODE REVIEW

**Comment by bitjammer** [comment]
@akyrtzi Can you add anyone else that you'd like to take a look?

**Review by jackhl — APPROVED** [review]
LGTM!

**Comment by akyrtzi** [comment]
@nkcsgexi this involves reading information from a Swift module, could you take a look?

**Comment by bitjammer** [comment]
Please test

**Comment by bitjammer** [comment]
@swift-ci please smoke test

**Comment by bitjammer** [comment]
@swift-ci please smoke test

**Comment by bitjammer** [comment]
@swift-ci please smoke test

**Comment by bitjammer** [comment]
@swift-ci please smoke test

**Comment by bitjammer** [comment]
@swift-ci Please test

**Comment by bitjammer** [comment]
@swift-ci Please smoke test

**Comment by bitjammer** [comment]
@swift-ci Please smoke test

**Comment by bitjammer** [comment]
@swift-ci Please smoke test

**Comment by bitjammer** [comment]
@swift-ci Please test

**Comment by bitjammer** [comment]
Per e-mail, we'll do post-commit review on this and refine it as needed. This uses its own driver mode so will not affect any other workflows in the compiler.

**Comment by compnerd** [comment]
This broke the windows builders: https://ci-external.swift.org/job/oss-swift-windows-x86_64/2422/

**Pull request merged**
