### PR TITLE
[5.8] COWOpts: fix a crash in case a buffer "escapes" to a cond_br condition

### PR DESCRIPTION
**Pull request by eeckstein**
rdar://103638121

This is a cherry-pick of https://github.com/apple/swift/pull/62758

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Review by tbkka — APPROVED** [review]

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci test macos

**Pull request merged**
