### PR TITLE
[WIP] Don't allow non-canonical types when serializing SIL

### PR DESCRIPTION
**Pull request by jrose-apple**
rdar://problem/17795074

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
Should we instead enforce canonical-ness when building SIL rather than when serializing it?

**Comment by jrose-apple** [comment]
I started going down that route with a CanSubstitutionMap and it required changing more code than I was comfortable with. It's probably the right answer long-term.

**Comment by jrose-apple** [comment]
I am a little surprised that worked. (The failures are unrelated UPASSes.)

**Comment by slavapestov** [comment]
@jrose-apple I guess I wasn't even thinking you'd enforce it at the type level, just via assertions in the SILBuilder.

**Comment by jrose-apple** [comment]
Even if we do get something like that, the check on `addTypeRef` seems like good defense-in-depth asserting anyway.

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
