### PR TITLE
[Exclusivity] Add CapturePromotion support for access markers.

### PR DESCRIPTION
**Pull request by atrick**
This only affects -enforce-exclusivity mode.

This is tested by existing lit tests with the -enforce-exclusivity option. I expect the markers to be emitted by default soon, so this doesn't need special tests.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci smoke test and merge.

**Comment by gottesmm** [comment]
@atrick Just an FYI, I am going to try later today to land some changes to capture promotion so that I can move mark_uninitialized behind the project_box.

**Comment by atrick** [comment]
@gottesmm ok, I did some small refactoring. Let me know if you have questions.

**Comment by atrick** [comment]
@swift-ci smoke test and merge.

**Comment by atrick** [comment]
@swift-ci smoke test and merge.

**Pull request merged**
