### PR TITLE
Update master-next for LLVM changes

### PR DESCRIPTION
**Pull request by smeenai**

### CODE REVIEW

**Comment by smeenai** [comment]
CC @compnerd @dcci @xiaobai

**Review by compnerd — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by smeenai** [comment]
The build failure is unrelated.

It's clear that the master-next build has lots of different breakages right now. Can we get these fixes in so we can fix them in an incremental manner, instead of constantly churning through CI and having to address additional unrelated failures (while new failures are introduced in the meantime)?

**Comment by smeenai** [comment]
Added more fixes. Can I get another test?

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by smeenai** [comment]
The build failure here is fixed by https://github.com/apple/swift-lldb/pull/2024

**Comment by smeenai** [comment]
Would appreciate another retest and merge here.

**Comment by xiaobai** [comment]
@swift-ci please test

**Comment by xiaobai** [comment]
@swift-ci please test

**Comment by xiaobai** [comment]
@swift-ci please test

**Comment by gmittert** [comment]
@swift-ci please test

**Review by dcci — APPROVED** [review]
LGTM

**Comment by dcci** [comment]
@swift-ci test

**Comment by smeenai** [comment]
Build failures appear unrelated. This doesn't fix all the master-next breakage, but it should at least make it better.

**Pull request merged**
