### PR TITLE
[5.5][Property Wrappers] Always check actor isolation and initializer effects in `PropertyWrapperInitializerInfoRequest`.

### PR DESCRIPTION
**Pull request by hborla**
Cherry-pick of https://github.com/apple/swift/pull/37627

* **Explanation**: Property wrappers can be initialized in a number of different ways. Most property wrappers are initialized via `init(wrappedValue:)`, which allows assignment to the wrapped property to be treated as initialization of the backing property wrapper. Property wrappers can also be default-initialized if the wrapper has an `init()` or if all arguments to the initializer are specified in the wrapper attribute. For local property wrappers, default initializers were never checked for effects and actor isolation, which caused 2 bugs: a SILGen crash, and allowing invalid code to compile. These checks were removed from `typeCheckSynthesizedWrapperInitializer` (which applies to both initialization via `init(wrappedValue:)` and default initializers) to avoid a circular dependency with actor isolation checking, but the new code only checked the `init(wrappedValue:)` initializer. The circular dependency issue with actor isolation checking was fixed in https://github.com/apple/swift/pull/36521, so actor isolation and effects checking can safely be done when these initializers are created.
* **Scope**: The scope of the change is limited to property wrappers.
* **Risk**: Low. The change is mostly moving code from one place to another to make sure it applies to both possible property wrapper initializers.
* **Testing**: Added SILGen tests exercising local property wrapper default initialization, and a test for actor isolation checking in local wrapper initializers.
* **Reviewer**: @slavapestov 

Resolves: rdar://74616133

### CODE REVIEW

**Comment by hborla** [comment]
@swift-ci please test

**Review by tkremenek — APPROVED** [review]

**Comment by hborla** [comment]
@swift-ci please test Windows platform

**Comment by hborla** [comment]
@swift-ci please test Windows platform

**Comment by hborla** [comment]
@swift-ci please test Windows platform

**Comment by hborla** [comment]
@swift-ci please test Windows platform

**Pull request merged**
