### PR TITLE
[stdlib] Remove overly-permissive UnsafePointer init

### PR DESCRIPTION
**Pull request by airspeedswift**
Follow-on building on #22275 removing the generic init, leaving only the inits from that PR

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please smoke test

**Comment by airspeedswift** [comment]
Please test with following pull request:
https://github.com/apple/swift-corelibs-foundation/pull/1870

@swift-ci please test linux platform

**Comment by airspeedswift** [comment]
@swift-ci please test macOS platform

**Review by atrick — APPROVED** [review]
I'll approve under the assumption that you'll add tests in UnsafePointerDiagnostics.swift something like this:

```
_ = UnsafePointer<Int>(ps) // expected-error {{error: cannot convert value of type 'UnsafePointer<String>' to expected argument type 'UnsafePointer<_>'}}
_ = UnsafeMutablePointer<Int>(mps) // expected-error {{error: cannot convert value of type 'UnsafeMutablePointer<String>' to expected argument type 'UnsafeMutablePointer<_>'}}
_ = UnsafePointer<String>(pi) // expected-error {{error: cannot convert value of type 'UnsafePointer<Int>' to expected argument type 'UnsafePointer<_>'}}
_ = UnsafeMutablePointer<String>(mpi) // expected-error {{error: cannot convert value of type 'UnsafeMutablePointer<Int>' to expected argument type 'UnsafeMutablePointer<_>'}}
```

**Comment by moiseev** [comment]
@atrick I just added the tests you recommended. Plus the reproducer for [SR-9800](https://bugs.swift.org/browse/SR-9800).

**Comment by moiseev** [comment]
apple/swift-corelibs-foundation#1870
@swift-ci please test linux platform

**Comment by moiseev** [comment]
@swift-ci Please test macOS platform

**Review by moiseev — APPROVED** [review]

**Comment by airspeedswift** [comment]
@swift-ci please smoke test and merge

**Comment by moiseev** [comment]
@swift-ci Please smoke test Linux platform

**Pull request merged**
