### PR TITLE
[5.5] Handle multiple awaits and suspend-on-exit for async let tasks.

### PR DESCRIPTION
**Pull request by jckarter**
Description: Implements a new ABI for `async let` that can support multiple awaits of the same binding, cancelling and suspending the task when it is still running on scope exit, and efficiently consuming and deallocating the task in one step in the common case.

Scope: Completes the implementation of `async let`.

Issues: rdar://77855176, rdar://80043610

Reviewed by: @ktoso 

Risk: Moderate; it's a substantial reimplementation of the feature. However, impact on the rest of the compiler and runtime should be minimal.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Review by ktoso — APPROVED** [review]

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please nominate

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
