### PR TITLE
Revert "[Typechecker] Diagnose key paths with contextual root type but no leading dot"

### PR DESCRIPTION
**Pull request by xedin**
Reverts apple/swift#30164

### CODE REVIEW

**Comment by xedin** [comment]
@theblixguy Let's revert and go with parser identification of such cases, sounds good?

**Comment by xedin** [comment]
@swift-ci please smoke test

**Review by dan-zheng — APPROVED** [review]
Thank you Pavel for proactively reverting to support [our use case](https://github.com/apple/swift/pull/30164#issuecomment-596926932)!

**Comment by saeta** [comment]
+1 thank you!

**Comment by theblixguy** [comment]
Sounds good! I’ll put up a new PR shortly!

**Comment by xedin** [comment]
No worries, take your time and thank you again!

**Comment by xedin** [comment]
@theblixguy Just wanted to ask you whether you are still interested in working on alternative solution for this?

**Comment by theblixguy** [comment]
@xedin Yes, sorry been a little busy in the past few days. I’ll put up a PR for the other approach shortly!

**Comment by xedin** [comment]
@theblixguy No worries, take your time!

**Pull request merged**
