### PR TITLE
[interop] do not import function template with templated rvalue ref

### PR DESCRIPTION
**Pull request by hyp**

### CODE REVIEW

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test source compatibility

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test source compatibility

**Comment by hyp** [comment]
@swift-ci please test windows platform

**Comment by hyp** [comment]
@swift-ci please test macos platform

**Comment by hyp** [comment]
@swift-ci please test macos platform

**Review by egorzhdan — APPROVED** [review]

**Pull request merged**
