### PR TITLE
Enforce existential `any` behind a feature flag

### PR DESCRIPTION
**Pull request by angela-laar**
In Swift 6, `any` will be required for all existential types. To opt into this behavior before Swift 6, developers will now be able to use the `-enable-upcoming-feature ExistentialAny` flag. 

rdar://97928440

### CODE REVIEW

**Comment by angela-laar** [comment]
@swift-ci please smoke test

**Comment by angela-laar** [comment]
@swift-ci please test

**Comment by angela-laar** [comment]
@swift-ci please smoke test

**Review by hborla — APPROVED** [review]

**Comment by angela-laar** [comment]
@swift-ci please smoke test

**Pull request merged**
