### PR TITLE
Eliminates redundant buffer zeroing in vDSP_FFT.swift

### PR DESCRIPTION
**Pull request by valeriyvan**
Eliminates redundant buffer zeroing in vDSP_FFT.swift

### CODE REVIEW

**Comment by stephentyrone** [comment]
The Accelerate overlay is owned by the Accelerate team; they're posted here, but strictly speaking aren't part of the swift project; I'll ping them to suggest the change, however.

**Comment by valeriyvan** [comment]
ping

**Comment by stephentyrone** [comment]
The Accelerate overlay doesn’t actually use the Swift repo. I suggested the change to them, but they’ll merge it to their repo if they decide to take it—nothing will happen with this PR.

**Comment by valeriyvan** [comment]
Ok. Got it.

**Pull request closed without merging**
