### PR TITLE
[gardening] Increase consistency with regards to spacing after colons

### PR DESCRIPTION
**Pull request by practicalswift**
Increase consistency with regards to spacing after colons.

### CODE REVIEW

**Comment by practicalswift** [comment]
@swift-ci please test

**Comment by practicalswift** [comment]
@swift-ci please smoke test

**Comment by practicalswift** [comment]
@swift-ci please smoke test

**Comment by practicalswift** [comment]
@swift-ci please smoke test

**Comment by practicalswift** [comment]
@swift-ci please test

**Comment by practicalswift** [comment]
@swift-ci please smoke test and merge

**Comment by moiseev** [comment]
AFAIK, the rule of thumb is "add a space on the type-side of the colon". So in generics it would be `<T : Collection>` but in parameters -- `x: MyCollection`.

**Comment by practicalswift** [comment]
@moiseev The form `<T: Collection>` is used consistently (instead of `<T : Collection>`) in the Apple Swift book. Should I go with `<T: Collection>` or `<T : Collection>`? :-)

**Comment by practicalswift** [comment]
I've now removed all `<X : Y>` vs. `<X: Y>` changes from this PR to make it merge:able :-)

**Comment by practicalswift** [comment]
@swift-ci please smoke test

**Comment by moiseev** [comment]
@practicalswift FWIW, the `<T : P>` convention (with two spaces) is what we tend to use in the Standard Library. The fact it is *not* what is used in the book is really unfortunate.

**Comment by practicalswift** [comment]
@swift-ci please smoke test

**Comment by practicalswift** [comment]
@swift-ci please test

**Comment by practicalswift** [comment]
@moiseev OK, then let's go with `<T : P>` then! :-)

Is there someone in the Swift team who is in contact with the Swift book team and can bring up this inconsistency and get it resolved? :-)

**Comment by practicalswift** [comment]
@swift-ci please smoke test and merge

**Comment by practicalswift** [comment]
@moiseev FWIW `<T: P>` (the style used in the Swift book) seems to be preferred in this unscientific poll with 178 respondents: https://twitter.com/practicalswift/status/750349404452913153

Results:
* `class A<T: B where …> {` (used in the Swift book) – preferred by 82 %
* `class A<T : B where …> {` (used in the standard library) – preferred by 11 %
* `class A<T:B where …> {` (control group, used by whom?) – preferred by 7 %

**Comment by moiseev** [comment]
Nice! It might be a consequence of people using XCode and reading TSPL, though.
Let's agree for now, that `<A : B>` is what is used in the standard library. We also have some other differences from the book/xcode styles: like 2-space indentation, and 80 characters width.

**Comment by practicalswift** [comment]
@moiseev Agreed! 👍

**Pull request merged**
