### PR TITLE
[SILGen] Used formal type when bridging completion handler arguments.

### PR DESCRIPTION
**Pull request by nate-chandler**
rdar://79383990

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please clean test macos platform

**Comment by nate-chandler** [comment]
@swift-ci please clean test macos platform

**Comment by nate-chandler** [comment]
@swift-ci please clean test macos platform

**Comment by nate-chandler** [comment]
@swift-ci please test macos platform

**Review by jckarter — APPROVED** [review]

**Pull request merged**
