### PR TITLE
[5.6] Upstream defer handling for the move function

### PR DESCRIPTION
**Pull request by gottesmm**
Just upstreaming the rest of the commits to 5.6 needed to add move support for reinitializing self in a defer and other fixes that I did on main as well.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
Looks like the SILFunction constructor is slightly different on 5.6 from main. I am going to clean up the history here a little bit/fix that.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
Forgot to fix the difference in between 5.6 and main... oops. Putting up the patch and restarting testing!

**Review by atrick — APPROVED** [review]
These changes from the previous algorithm all look positive. I'll review the algorithm as a whole separately.

**Pull request merged**
