### PR TITLE
testing apple/swift-installer-scripts#170

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves #NNNNN, fix apple/llvm-project#MMMMM.

### CODE REVIEW

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-installer-scripts#170

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
CC: @MaxDesiatov

**Comment by compnerd** [comment]
```
C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift-installer-scripts\platforms\Windows\sdk-amd64.wxs(215): error LGHT0103: The system cannot find the file 'T:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk\\usr\lib\swift\dispatch\generic_base.h'. [C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift-installer-scripts\platforms\Windows\sdk.wixproj]
```

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/170

@swift-ci please build toolchain Windows platform

**Comment by MaxDesiatov** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/170

@swift-ci please build toolchain Windows platform

**Pull request closed without merging**
