### PR TITLE
[4.1] Disable ModelIO test on ios on tvos

### PR DESCRIPTION
**Pull request by aschwaighofer**
This test currently fails and blocks testing.

rdar://35490456

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by shahmishal** [comment]
ci.swift.org is down for update, I will re-trigger this PR once update has been completed.

**Comment by shahmishal** [comment]
@swift-ci Please test

**Comment by shahmishal** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
I'm going to merge this since it's blocking CI on the 4.1 branch.

**Comment by shahmishal** [comment]
@aschwaighofer We also need this for swift-4.0-branch. 

https://ci.swift.org/view/swift-4.0-branch/job/oss-swift-4.0-package-osx/632/consoleFull#-169438179ba62d58e-7248-467b-91e0-c7508d5cf947

**Comment by aschwaighofer** [comment]
@shahmishal 4.0 cherry pick is here https://github.com/apple/swift/pull/12966

**Pull request merged**
