### PR TITLE
SILType: rename isLoadableOrLowered to isLoadableOrOpaque

### PR DESCRIPTION
**Pull request by shajrawi**
per the suggestion in https://github.com/apple/swift/commit/4fca6b482c990bec4fea5a3f1cff15e0fe02756e#commitcomment-28299207

### CODE REVIEW

**Comment by shajrawi** [comment]
@swift-ci Please smoke test and merge

**Comment by slavapestov** [comment]
Thank you :)

**Comment by shajrawi** [comment]
@swift-ci Please smoke test Linux

**Comment by atrick** [comment]
Thanks Joe. I totally agree.

**Pull request merged**
