### PR TITLE
[build-script] Fix how the playground frameworks build in build-script.

### PR DESCRIPTION
**Pull request by cwakamo**
This PR does three things:

- Removes support for building PlaygroundLogger on Linux (this never actually worked, so it doesn't make sense to keep maintaining something which doesn't work). This PR incorporates my earlier changes from #14003.
- Merges the "playgroundsupport" and "playgroundlogger" products in build-script and updates presets where necessary
- Updates how PlaygroundLogger and PlaygroundSupport are built, taking advantage of a new workspace and new schemes to do per-platform xcodebuild invocations (requires apple/swift-xcode-playground-support#18).

Resolves &lt;rdar://problem/36512531&gt;.

### CODE REVIEW

**Comment by cwakamo** [comment]
Please test with the following PR:
apple/swift-xcode-playground-support#18

@swift-ci Please test

**Comment by shahmishal** [comment]
Please test with the following PR:
apple/swift-xcode-playground-support#18

@swift-ci build toolchain

**Review by Rostepher — APPROVED** [review]
So long as the additional testing Mishal requested passes, this looks good to me.

**Review by shahmishal — APPROVED** [review]
LGTM! Thanks!

**Comment by cwakamo** [comment]
The toolchains built successfully, and I did a sanity check of the macOS toolchain. Going ahead and merging this.

**Pull request merged**
