### PR TITLE
[runtime] Don't use C++ thread_local on two old Apple simulators.

### PR DESCRIPTION
**Pull request by gparker42**
32-bit iOS 9 simulator and 32-bit watchOS 2 simulator do not support
C++ thread_local, even though clang's has_feature(cxx_thread_local)
thinks they do.

rdar://35063043

### CODE REVIEW

**Comment by gparker42** [comment]
@swift-ci please test

**Comment by jeremyhu** [comment]
LGTM. 👍

**Comment by rjmccall** [comment]
LGTM.

**Comment by compnerd** [comment]
@gparker42, is there a PR for clang to get the value right?

**Comment by gparker42** [comment]
rdar://35083787 is for clang.

**Pull request merged**
