### PR TITLE
utils: introduce new `-Summary` option for `build.ps1`

### PR DESCRIPTION
**Pull request by compnerd**
Add a new `-Summary` option to understand the build times expenditure. This prints a summary at the end of the build time, though should be further refined to include tests, auxiliary operations, and the like.

~~~
Arch  Checkout                                                BuildID                 Elapsed Time
----  --------                                                -------                 ------------
x64   S:\SourceCache\swift-project\swift\tools\swift-inspect  swift-inspect           00:00:00.2372939
x64   S:\SourceCache\swift-project\sqlite-3.43.2              sqlite-3.43.2           00:00:00.5062697
x64   S:\SourceCache\swift-project\zlib                       zlib-1.3                00:00:00.5615253
arm64 S:\SourceCache\swift-project\zlib                       zlib-1.3                00:00:00.5623726
x86   S:\SourceCache\swift-project\zlib                       zlib-1.3                00:00:00.6185541
x64   S:\SourceCache\swift-project\swift-system               2                       00:00:00.6562858
x64   S:\SourceCache\swift-project\Yams                       5                       00:00:00.6647429
x64   S:\SourceCache\swift-project\swift-certificates         11                      00:00:00.6649416
arm64 S:\SourceCache\swift-project\swift-corelibs-xctest      304                     00:00:00.6688467
x64   S:\SourceCache\swift-project\swift-asn1                 10                      00:00:00.6795648
x64   S:\SourceCache\swift-project\swift-corelibs-xctest      104                     00:00:00.6938559
x64   S:\SourceCache\swift-project\swift-argument-parser      6                       00:00:00.7351350
x64   S:\SourceCache\swift-project\swift-tools-support-core   3                       00:00:00.7400418
x64   S:\SourceCache\swift-project\indexstore-db              15                      00:00:00.7402386
x86   S:\SourceCache\swift-project\swift-corelibs-xctest      204                     00:00:00.7414125
x64   S:\SourceCache\swift-project\cmark                      cmark-gfm-0.29.0.gfm.13 00:00:00.7435080
x64   S:\SourceCache\swift-project\swift-crypto               8                       00:00:00.7593080
arm64 S:\SourceCache\swift-project\libxml2                    libxml2-2.11.5          00:00:00.7659147
x64   S:\SourceCache\swift-project\libxml2                    libxml2-2.11.5          00:00:00.7885430
x64   S:\SourceCache\swift-project\sourcekit-lsp              16                      00:00:00.8459008
arm64 S:\SourceCache\swift-project\icu\icu4c                  icu-69.1                00:00:00.8544044
x86   S:\SourceCache\swift-project\libxml2                    libxml2-2.11.5          00:00:00.8552676
x64   S:\SourceCache\swift-project\icu\icu4c                  icu-69.1                00:00:00.8986529
x64   S:\SourceCache\swift-project\curl                       curl-8.4.0              00:00:00.9157392
arm64 S:\SourceCache\swift-project\curl                       curl-8.4.0              00:00:00.9292362
x64   S:\SourceCache\swift-project\swift-package-manager      12                      00:00:00.9352117
x86   S:\SourceCache\swift-project\icu\icu4c                  icu-69.1                00:00:00.9890039
x86   S:\SourceCache\swift-project\curl                       curl-8.4.0              00:00:01.0041779
x64   S:\SourceCache\swift-project\llbuild                    4                       00:00:01.0835003
arm64 S:\SourceCache\swift-project\swift-corelibs-libdispatch 302                     00:00:01.2923527
x64   S:\SourceCache\swift-project\swift-corelibs-libdispatch 102                     00:00:01.2940821
x86   S:\SourceCache\swift-project\swift-corelibs-libdispatch 202                     00:00:01.3725038
x64   S:\SourceCache\swift-project\swift-docc                 swift-docc              00:00:01.5638843
x64   S:\SourceCache\swift-project\swift-corelibs-foundation  103                     00:00:03.2156545
arm64 S:\SourceCache\swift-project\swift-corelibs-foundation  303                     00:00:03.2375292
x86   S:\SourceCache\swift-project\swift-corelibs-foundation  203                     00:00:03.3768394
x64   S:\SourceCache\swift-project\swift                      101                     00:00:03.4123377
x86   S:\SourceCache\swift-project\swift                      201                     00:00:03.4822752
arm64 S:\SourceCache\swift-project\swift                      301                     00:00:03.5000946
x64   S:\SourceCache\swift-project\swift-collections          9                       00:00:04.1620695
x64   S:\SourceCache\swift-project\swift-format               14                      00:00:07.9155136
arm64 S:\SourceCache\swift-project\llvm-project\llvm          300                     00:00:08.0239769
x64   S:\SourceCache\swift-project\llvm-project\llvm          100                     00:00:08.0504294
x86   S:\SourceCache\swift-project\llvm-project\llvm          200                     00:00:08.1190769
x64   S:\SourceCache\swift-project\swift-markdown             13                      00:00:12.4397452
x64   S:\SourceCache\swift-project\swift-driver               7                       00:00:24.9125831
x64   S:\SourceCache\swift-project\llvm-project\llvm          1                       00:01:04.5879144
x64   S:\SourceCache\swift-project\llvm-project\llvm          0                       00:01:10.9225001
~~~

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
CC: @shahmishal @hyp @hjyamauchi @tristanlabelle @etcwilde

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Review by hjyamauchi — APPROVED** [review]

**Review by shahmishal — APPROVED** [review]
Thank you!

**Review by etcwilde — APPROVED** [review]

**Comment by compnerd** [comment]
Going to merge this for now and continue to refine this.  Current CI run shows:

~~~
Arch  Checkout                                                                        BuildID                 Elapsed  
                                                                                                              Time     
----  --------                                                                        -------                 ---------
x64   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\llvm-project\llvm          1                       00:38:...
x64   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift-docc                 swift-docc              00:10:...
x86   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift                      201                     00:07:...
x64   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift                      101                     00:06:...
arm64 C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift                      301                     00:06:...
x64   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\llvm-project\llvm          0                       00:02:...
x64   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swiftpm                    12                      00:02:...
x64   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\icu\icu4c                  icu-69.1                00:01:...
x64   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift-driver               7                       00:01:...
x64   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\tools\swift-inspect  swift-inspect           00:01:...
x64   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\sourcekit-lsp              16                      00:01:...
x86   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift-corelibs-foundation  203                     00:00:...
arm64 C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift-corelibs-foundation  303                     00:00:...
x64   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift-corelibs-foundation  103                     00:00:...
x64   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift-format               14                      00:00:...
x86   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\icu\icu4c                  icu-69.1                00:00:...
x86   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\llvm-project\llvm          200                     00:00:...
arm64 C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\icu\icu4c                  icu-69.1                00:00:...
arm64 C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\llvm-project\llvm          300                     00:00:...
arm64 C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift-corelibs-libdispatch 302                     00:00:...
x64   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\llvm-project\llvm          100                     00:00:...
x64   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift-corelibs-libdispatch 102                     00:00:...
x86   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift-corelibs-libdispatch 202                     00:00:...
arm64 C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\curl                       curl-8.4.0              00:00:...
x64   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\curl                       curl-8.4.0              00:00:...
x64   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift-tools-support-core   3                       00:00:...
x86   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\curl                       curl-8.4.0              00:00:...
x64   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\llbuild                    4                       00:00:...
x64   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift-markdown             13                      00:00:...
x64   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift-crypto               8                       00:00:...
x64   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\Yams                       5                       00:00:...
x64   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\cmark                      cmark-gfm-0.29.0.gfm.13 00:00:...
x64   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift-argument-parser      6                       00:00:...
arm64 C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\zlib                       zlib-1.3                00:00:...
x86   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\zlib                       zlib-1.3                00:00:...
x64   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\indexstore-db              15                      00:00:...
x64   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift-system               2                       00:00:...
x64   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift-certificates         11                      00:00:...
x64   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\sqlite-3.43.2              sqlite-3.43.2           00:00:...
x64   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift-collections          9                       00:00:...
x64   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift-asn1                 10                      00:00:...
x86   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift-corelibs-xctest      204                     00:00:...
x64   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift-corelibs-xctest      104                     00:00:...
arm64 C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift-corelibs-xctest      304                     00:00:...
arm64 C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\libxml2                    libxml2-2.11.5          00:00:...
x64   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\libxml2                    libxml2-2.11.5          00:00:...
x86   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\libxml2                    libxml2-2.11.5          00:00:...
x64   C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\zlib                       zlib-1.3                00:00:...
~~~

DocC seems to rank pretty high up, with it being the second longest build step (after the entire set of compilers/debugger/linker).

**Pull request merged**
