### PR TITLE
Pin `swift-async-algorithms` to 1.0.1 in `update-checkout-config.json`

### PR DESCRIPTION
**Pull request by MaxDesiatov**
We've temporarily unpinned this repository in https://github.com/apple/swift/pull/72728 to get recent changes. Now a new tag is available, we should pin it again.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Review by kateinoigakukun — APPROVED** [review]

**Comment by kateinoigakukun** [comment]
@swift-ci build toolchain

**Comment by kateinoigakukun** [comment]
@swift-ci test

**Comment by kateinoigakukun** [comment]
@shahmishal If you have a moment, could you update the dependency in the CI configuration? :pray:

**Comment by shahmishal** [comment]
Please also update `next` and `rebranch` scheme

**Comment by kateinoigakukun** [comment]
@swift-ci test

**Comment by kateinoigakukun** [comment]
@swift-ci build toolchain

**Review by shahmishal — APPROVED** [review]

**Comment by kateinoigakukun** [comment]
Thanks!

**Pull request merged**
