### PR TITLE
[string] Hoist UTF8View fast-path for known ASCII

### PR DESCRIPTION
**Pull request by milseman**

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please smoke benchmark

**Comment by milseman** [comment]
This speeds up ArrayAppendAscii by ~2x.

**Comment by milseman** [comment]
I've been seeing Sim2DArray pop up a lot of a supposed regression, only to disappear in subsequent runs. Is there something wrong with this benchmark?

**Comment by milseman** [comment]
Not sure how a benchmark that has no Strings in it is being regressed by a minor tweak to UTF8 decoding

**Review by lorentey — COMMENTED** [review]
Nice! 👍

**Pull request merged**
