### PR TITLE
Add some crashers to the validation test suite.

### PR DESCRIPTION
**Pull request by rudkx**

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Test and merge.

**Comment by rudkx** [comment]
@shahmishal Linux PR testing is failing due to a cmake problem, but the regular CI is passing.

Configuration problem perhaps?

**Comment by shahmishal** [comment]
Can you please try clean Linux test?

**Comment by rudkx** [comment]
@swift-ci Clean test Linux

**Comment by rudkx** [comment]
Strange, this test does not seem to be failing on Linux. I believe we're doing an asserts-enabled build for testing and we're not hitting the assert we see on macOS, either.

**Comment by rudkx** [comment]
@swift-ci Clean test and merge.

**Comment by rudkx** [comment]
@swit-ci Clean test.

**Comment by rudkx** [comment]
@swift-ci Please test.

**Comment by rudkx** [comment]
@swift-ci Please clean test.

**Comment by rudkx** [comment]
@swift-ci Please clean test.

**Comment by rudkx** [comment]
@swift-ci Please smoke test and merge.

**Comment by rudkx** [comment]
@swift-ci Linux smoke test.

**Comment by shahmishal** [comment]
@swift-ci Linux smoke test.

**Comment by shahmishal** [comment]
@swift-ci smoke test Linux

**Comment by shahmishal** [comment]
@swift-ci smoke test Linux

**Pull request merged**
