### PR TITLE
[Sema] Fix a couple of AnyObject lookup bugs

### PR DESCRIPTION
**Pull request by hamishknight**
- Suppress a spurious "single-element tuple" diagnostic by handling `DynamicSubscriptExpr` in MiscDiagnostics.
- Properly reject `@objc` generic subscripts instead of quietly marking their accessors as non-objc.
- Don't consider a protocol's generic signature when trying to coalesce decls for `AnyObject` lookup.

Resolves SR-8611, SR-12799 & SR-12801.
Resolves rdar://43645564 & rdar://62906344.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility Debug

**Review by xedin — APPROVED** [review]
Thank you!

**Pull request merged**
