### PR TITLE
[build] Fix cmake config for reflection test without dynamic stdlib

### PR DESCRIPTION
**Pull request by kateinoigakukun**
Build SwiftReflectionTest only if swift-reflection-test is available because it depends on the tool and the tool is not available when no dynamic stdlib is built

### CODE REVIEW

**Comment by kateinoigakukun** [comment]
@swift-ci Please smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci build toolchain

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Review by Azoy — APPROVED** [review]
Makes sense to me 👍

**Pull request merged**
