### PR TITLE
Merge 2020-04-07 into tensorflow

### PR DESCRIPTION
**Pull request by texasmichelle**

### CODE REVIEW

**Comment by texasmichelle** [comment]
@swift-ci Please clean test TensorFlow.

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by dan-zheng** [comment]
The extended test suite passed. Merging.

**Pull request merged**
