### PR TITLE
Adding more comment for Reflection tests that does not support ASAN

### PR DESCRIPTION
**Pull request by lamtrinhdev**
### Summary:

As reference the PR https://github.com/swiftlang/swift/pull/75509 (Reflection tests are incompatible with ASAN), Adding more comment on some files in Reflection tests

### Modifications:

+ validation-test/Reflection/existentials.swift
+ validation-test/Reflection/existentials_objc.swift
+ validation-test/Reflection/functions.swift
+ validation-test/Reflection/functions_objc.swift
+ validation-test/Reflection/inherits_NSObject.swift
+ validation-test/Reflection/inherits_ObjCClasses.swift
+ validation-test/Reflection/inherits_Swift.swift

### Result:

Adding more "UNSUPPORTED: asan"

### CODE REVIEW

**Comment by lamtrinhdev** [comment]
Dear @tbkka ,

As the PR https://github.com/swiftlang/swift/pull/75509 . I would like to add some more comments on other files in "Reflection tests".

Please help me to review it.

Thanks,
Lam

**Comment by tbkka** [comment]
Looks good.  The specific problem is that `%target-swift-reflection-test` is now incompatible with ASAN.  In looking at that, I noticed that some of the tests that use `%target-swift-reflection-test` do not have `REQUIRES: reflection-test-support`    Could you please add that in as well while you're cleaning up things here?

**Comment by lamtrinhdev** [comment]
Dear @tbkka ,

Sure. Thank you for your advice. I updated all of them. Please help me to review it.

Thanks,
Lam

**Comment by tbkka** [comment]
Looks great!   Let's make sure it passes CI, then I'll merge it.

**Comment by tbkka** [comment]
@swift-ci Please test

**Comment by tbkka** [comment]
Thank you!

**Pull request merged**
