### PR TITLE
[SILGen] Silence redundant unreachable enum case warning

### PR DESCRIPTION
**Pull request by theblixguy**
When an enum case is already handled, for example:

```swift
enum Foo { case a, b }
func takesFoo(arg: Foo) {
  switch arg {
    case _: break
    case .b: break
  }
}
```

We would get two warnings on `case .b`: `case is already handled by previous patterns; consider removing it` & `case will never be executed`. The first warning comes from Space Engine and the second warning comes from SILGenPattern.

So, silence the (redundant) warning emitted by SILGenPattern for switch statements (except `default` case).

Resolves #54657
Resolves rdar://problem/59655513

### CODE REVIEW

**Comment by jckarter** [comment]
IIRC there isn't perfect overlap between the two diagnostics, so disabling either one will cause us to miss cases the other doesn't catch either. @CodaFi how does this sound to you now?

**Comment by CodaFi** [comment]
The space engine only has incomplete redundancy checking for expression patterns - there we do something awful that approximates redundancy checking for (non-range) literals. Proper patterns always overlap, so we could at least ditch it for those cases.

**Comment by theblixguy** [comment]
I have updated the implementation to check for expression patterns and continue to emit the diagnostic in that case. I tried a couple of test cases involving redundant expression patterns but I couldn't get the redundant warning to trigger in Xcode 12. Do you know a test case which triggers it?

**Comment by theblixguy** [comment]
Ping. Does the change look good now @CodaFi?

**Comment by theblixguy** [comment]
Ping.

**Review by CodaFi — APPROVED** [review]
LGTM. Joe can sign off on SIL.

**Review by jckarter — APPROVED** [review]
Looks good to me too.

**Pull request merged**
