### PR TITLE
Make python_format script executable

### PR DESCRIPTION
**Pull request by keith**
It doesn't look like this script gets run much, but it should be
executable so it can be.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test Linux

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by stephentyrone** [comment]
@swift-ci smoke test Linux

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
