### PR TITLE
Revert "SIL: let SingleValueInstruction only inherit from a single SILNode."

### PR DESCRIPTION
**Pull request by edymtt**
Reverts apple/swift#35554

This is to unblock the CI bots, which are failing to build `SwiftSyntaxBuilderTest` with message `error: fatalError`

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci please smoke test

**Comment by shahmishal** [comment]
I thought this PR fixed the issue https://github.com/apple/swift-syntax/pull/256
cc: @ahoppen

**Comment by edymtt** [comment]
This fixes a different error that happened before, e.g

https://ci.swift.org/job/oss-swift-incremental-RA-macos/13244/
https://ci.swift.org/view/Pull%20Request/job/swift-PR-macos/25351/console

(and that happened during PR testing of apple/swift-syntax#256 as well, see https://ci.swift.org/job/swift-syntax-PR-Linux/70/)

**Comment by shahmishal** [comment]
Thanks @edymtt!

**Pull request merged**
