### PR TITLE
[stdlib] Constrain BinaryInteger.Words to be a Collection

### PR DESCRIPTION
**Pull request by lorentey**
`BinaryInteger.Words` could previously only be constrained to a `Sequence` of `UInts`; it is now possible to constrain it to `Collection`, so that we match the interface accepted in SE-104.

### CODE REVIEW

**Comment by moiseev** [comment]
Can it be a stronger requirement, like a `BidirectionalCollection` for example?

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by lorentey** [comment]
@moiseev Not yet (or at least not as easily): it leads to seemingly unrelated errors in BidirectionalCollection.swift and elsewhere, and then a compiler crash. I'll see if I can make sense of it.

It is also not yet possible to have `Int.Words` and `UInt.Words` conform to `RandomAccessCollection` -- so we can't replace the custom implementation with `CollectionOfOne` yet.

**Comment by moiseev** [comment]
@lorentey I don't understand your second point about inability to use `CollectionOfOne`. It is still a `Collection` so regardless of the constraints on `Words` it should be usable... What am I missing?

**Comment by lorentey** [comment]
@moiseev Me neither! Something gets confused when `[U]Int.Words` is a random-access collection, but it's okay for `Int8.Words` and the rest of the integers. However, luckily we now get error messages rather than just a crash:

```
/Users/lorentey/Git/Swift/swift/stdlib/public/core/Indices.swift.gyb:127:17: error: 'Self.Indices.Indices.IndexDistance.Words.SubSequence.Element' cannot be equal to both 'Base.Element' and 'UInt'
  where Indices == DefaultBidirectionalIndices<Self>
                ^
/Users/lorentey/Git/Swift/swift/stdlib/public/core/Indices.swift.gyb:127:17: note: same-type constraint 'Self.Indices.Indices.IndexDistance.Words.Iterator.Element' == 'UInt' implied here
  where Indices == DefaultBidirectionalIndices<Self>
                ^
/Users/lorentey/Git/Swift/swift/stdlib/public/core/Indices.swift.gyb:127:17: error: 'Self.Indices.Indices.IndexDistance.Words.SubSequence.Element' cannot be equal to both 'Base.Element' and 'UInt'
  where Indices == DefaultBidirectionalIndices<Self>
                ^
/Users/lorentey/Git/Swift/swift/stdlib/public/core/Indices.swift.gyb:127:17: note: same-type constraint 'Self.Indices.Indices.IndexDistance.Words.Iterator.Element' == 'UInt' implied here
  where Indices == DefaultBidirectionalIndices<Self>
                ^
/Users/lorentey/Git/Swift/swift/stdlib/public/core/Indices.swift.gyb:127:17: error: 'Self.Indices.Indices.IndexDistance.Words.SubSequence.Iterator.Element' cannot be equal to both 'Elements.Element' and 'UInt'
  where Indices == DefaultBidirectionalIndices<Self>
                ^
```

(It goes on for a couple dozen more errors like this.) Does this ring a bell for you?

**Comment by moiseev** [comment]
> /Users/lorentey/Git/Swift/swift/stdlib/public/core/Indices.swift.gyb:127:17: error: 'Self.Indices.Indices.IndexDistance.Words.SubSequence.Element' cannot be equal to both 'Base.Element' and 'UInt'

This begs for a another equality constraint like `SubSequence.Base.Element == UInt`. But hard to tell... And no, I haven't seen anything like that before.

**Comment by moiseev** [comment]
@swift-ci Please smoke benchmark

**Comment by moiseev** [comment]
Since messing with constraints like this sometimes has an unwelcome changes in compilation time, I'd rather not merge this change without measuring the stdlib compile time with and without this patch applied.

**Comment by lorentey** [comment]
Understood! 👍 Shall I time it on my end?

FWIW, my timings for incremental builds using `./swift/utils/build-script -R` aren't great:

```
before: 264.68 real      1099.82 user        48.22 sys
after:  301.12 real      1223.43 user        53.47 sys
```

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by lorentey** [comment]
I fixed the build time regression by relaxing the BinaryInteger.Words constraint to `_Indexable`.

To ensure `words.count` remains available in generic contexts, I moved `Collection`'s `count` property up into `_Indexable` (along with `isEmpty`).

Updated build times: (incremental `build-script -R` on latest master)

```
before: 269.12 real      1091.76 user        47.95 sys
after:  274.38 real      1136.65 user        49.71 sys
```

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
FWIW, here are my local measurements of build time with and without the change applied:

```
before: 317.25s user 25.48s system 303% cpu 1:53.08 total
after: 340.38s user 26.32s system 301% cpu 2:01.79 total

before: 309.81s user 25.82s system 290% cpu 1:55.43 total
after: 343.30s user 26.98s system 287% cpu 2:08.89 total
```

Regression of about ~10%.

**Comment by lorentey** [comment]
@moiseev Weird; I get consistently better ratios. (On an i7 rMBP with -j8, with the PR rebased onto current master.)

With `Collection` conformance:

 Name | real | user | sys
 --- | --- | --- | ---
 before  |      295.93  |    1234.35  |      64.31
 after c809110  |     332.85   |   1380.12   |     68.63
 Change | 112% | 112% | 107%

With `_Indexable`:

 Name | real | user | sys
 --- | --- | --- | ---
 before  |      295.93  |    1234.35  |      64.31
 after 11e30ed  |     304.44  |    1282.90  |      63.69
 Change | 103% | 104% | 99%

In any case, instance-level `bitWidth` is still in the `BinaryInteger` protocol, so people can continue to use that in generic contexts; it's not super important to make `words.count` available, too. I'm a-okay with closing this PR without a merge! (I'll keep monitoring compiler performance and resubmit if/when we can do this without a performance penalty.)

**Comment by moiseev** [comment]
@lorentey what are you timing exactly? I just cannot explain why I see the difference and you don't =)

My procedure is essentially this:

```sh
utils/build-script -r --skip-build-benchmarks
find ./stdlib/public/core/* -name '*.swift*' -print0 | xargs -0 touch
time ninja -C ../build/Ninja-RelWithDebInfoAssert+stdlib-DebugAssert/swift-macosx-x86_64 swift-stdlib-macosx
```

What's yours?

I tried it again just now on my desktop with these results:

```

before 147.09s user 8.52s system 240% cpu 1:04.63 total
after 162.12s user 8.68s system 245% cpu 1:09.68 total
```

**Comment by lorentey** [comment]
@moiseev Ah, that explains it! I just used `time build-script -R`, so my timings included the compilation time for benchmarks and overlays, too. 🐢 (Ninja compiled about 510 or so files, AFAICR.)

**Pull request closed without merging**
