### PR TITLE
[stdlib] Standard library Circular Buffer

### PR DESCRIPTION
**Pull request by kitaisreal**
Introduce RingBuffer to Standard Library

Current implementation steps:
1. Implemented RingBuffer structure
2. Added tests
3. Use internally in Sequence.

Tasks to do.
- [x] Use ManagedBuffer as RingBuffer storage
- [x] Add documentation
- [x] Simplify tests
- [x] Is ring buffer sufficient for swift contains naming. Maybe it is better CircularArray (Contiguous Array, Array etc.) ?
- [x] Update benchmarks for Queue using RingBuffer as backing storage.
- [ ] Add additional benchmarks for RingBuffer.

@CodaFi should evolution proposal and also topic on forum be created ?

https://bugs.swift.org/browse/SR-8190

### CODE REVIEW

**Comment by CodaFi** [comment]
All public API changes to the standard library require a Swift Evolution proposal. If you would like help drafting this proposal, please post on the [Swift Evolution section of the Swift forums](https://forums.swift.org/c/evolution/). You will definitely also want to draw up a PR to the Swift Standard Library Preview Package. You can find more details about that [here](https://swift.org/blog/preview-package/).

For now, let's see what's what

@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci benchmark

**Comment by lorentey** [comment]
For previous work in this area, it is useful to look at NIO's [ByteBuffer](https://github.com/apple/swift-nio/blob/b4483e5c493e7697d3b65b7bb24ba15d6234392a/Sources/NIO/ByteBuffer-core.swift) and my own [Deque](https://github.com/attaswift/Deque). One important lesson we learned is never to use `Int` as a `Collection` index.

**Comment by kitaisreal** [comment]
1. Changed name to CircularArray. Mostly because it is consistent with other collection names Array, ContinuousArray. RingBuffer is also good alternative but Buffer in name seems confusing. Another good alternative is boost CircularBuffer https://www.boost.org/doc/libs/1_72_0/doc/html/circular_buffer.html
@airspeedswift, @CodaFi, @lorentey what name looks more swift natural ?
2. Used UnsafeMutablePointer for backing storage instead ManagedBuffer.
3. Updated Sequence failed tests.
4. Updated tests.
5. Updated benchmarks.
```
Workload n = 1000
ATL1M-C02XG4Z3:swift-macosx-x86_64 mkita$ bin/./Benchmark_O --num-iters=20 run 658 659 660
#,TEST,SAMPLES,MIN(μs),MAX(μs),MEAN(μs),SD(μs),MEDIAN(μs)
658,QueueCircularArray,200,2660,3920,2888,187,2870
659,QueueConcrete,200,1800,3020,1961,127,1960
660,QueueGeneric,200,1850,4980,2434,474,2270
```
```
Workload n = 100000
ATL1M-C02XG4Z3:swift-macosx-x86_64 mkita$ bin/./Benchmark_O --num-iters=20 run 658 659 660
#,TEST,SAMPLES,MIN(μs),MAX(μs),MEAN(μs),SD(μs),MEDIAN(μs)
658,QueueCircularArray,28,293410,385720,330783,27602,321320
659,QueueConcrete,47,211380,315520,238085,23584,228410
660,QueueGeneric,48,214980,334680,244039,23395,241920
```
It was confusing to me, I made following benchmark:
```swift
func queueIncrementBenchmark<Queue: AbstractQueue>(type: Queue.Type) where Queue.Element == Int {
    var queue = Queue.construct()
    for i in 0..<300*120 {
        queue.enqueue(i);
        _ = queue.dequeue();
    }

    for i in 0..<300*120 {
        queue.enqueue(i);
    }

    for _ in 0..<300*120 {
        _ = queue.dequeue();
    }
}

```
```
ATL1M-C02XG4Z3:swift-macosx-x86_64 mkita$ bin/./Benchmark_O --num-iters=20 run 658 659
#,TEST,SAMPLES,MIN(μs),MAX(μs),MEAN(μs),SD(μs),MEDIAN(μs)
658,QueueCircularArray,200,25520,72680,29565,5178,27700
659,QueueGeneric,90,109130,197250,122926,16795,116160
```
It seems to me when we are using two arrays queue, we getting penalty only on first deque call, when array is reversed. Then it will be faster because we are not making any bound checks, complex index manipulation on elements remove. @lorentey What do you think?

**Comment by theblixguy** [comment]
@swift-ci please test

**Comment by theblixguy** [comment]
@swift-ci please benchmark

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
