### PR TITLE
I can make it worse

### PR DESCRIPTION
**Pull request by Catfish-Man**

### CODE REVIEW

**Comment by Catfish-Man** [comment]
@swift-ci please benchmark

**Comment by Catfish-Man** [comment]
Well… that… actually made it better

**Comment by glessard** [comment]
### Performance (x86_64): -O

| **Regression**                          | **OLD** | **NEW** | **DELTA** |     **RATIO** |
| :-------------------------------------- | ------: | ------: | --------: | ------------: |
| FlattenListLoop                         |     958 |    1581 |    +65.0% | **0.61x (?)** |
| FlattenListFlatMap                      |    4065 |    4387 |     +7.9% | **0.93x (?)** |
| &nbsp;                                  |         |         |           |               |
| **Improvement**                         | **OLD** | **NEW** | **DELTA** |     **RATIO** |
| EqualStringSubstring                    |      30 |      23 |    -23.3% | **1.30x (?)** |
| UTF8Decode_InitFromCustom_contiguous    |     161 |     127 |    -21.1% | **1.27x (?)** |
| LessSubstringSubstring                  |      29 |      23 |    -20.7% | **1.26x (?)** |
| EqualSubstringSubstringGenericEquatable |      29 |      23 |    -20.7% | **1.26x (?)** |
| EqualSubstringString                    |      29 |      23 |    -20.7% | **1.26x (?)** |
| LessSubstringSubstringGenericComparable |      29 |      23 |    -20.7% | **1.26x (?)** |
| UTF8Decode_InitDecoding                 |     160 |     127 |    -20.6% | **1.26x (?)** |
| EqualSubstringSubstring                 |      30 |      24 |    -20.0% | **1.25x (?)** |
| StringUTF16Builder                      |     230 |     200 |    -13.0% | **1.15x (?)** |
| ObjectiveCBridgeStringHash              |      78 |      68 |    -12.8% |     **1.15x** |
| StringComparison_longSharedPrefix       |     331 |     295 |    -10.9% | **1.12x (?)** |
| AngryPhonebook                          |     336 |     301 |    -10.4% |     **1.12x** |
| Set.isSubset.Int.Empty                  |      49 |      44 |    -10.2% | **1.11x (?)** |
| UTF8Decode_InitFromCustom_noncontiguous |     355 |     321 |     -9.6% | **1.11x (?)** |
| NSStringConversion                      |     363 |     329 |     -9.4% | **1.10x (?)** |
| AngryPhonebook.ASCII2.Small             |     149 |     136 |     -8.7% | **1.10x (?)** |
| NormalizedIterator_fastPrenormal        |     580 |     530 |     -8.6% | **1.09x (?)** |
| StringBuilder                           |     212 |     195 |     -8.0% | **1.09x (?)** |
| SortStringsUnicode                      |    2115 |    1955 |     -7.6% | **1.08x (?)** |
| StringBuilderSmallReservingCapacity     |     220 |     205 |     -6.8% | **1.07x (?)** |
| ArraySetElement                         |     304 |     284 |     -6.6% | **1.07x (?)** |

### Code size: -O


### Performance (x86_64): -Osize

| **Regression**                          | **OLD** | **NEW** | **DELTA** |     **RATIO** |
| :-------------------------------------- | ------: | ------: | --------: | ------------: |
| FlattenListFlatMap                      |    2698 |    4010 |    +48.6% | **0.67x (?)** |
| PrefixAnySeqCRangeIter                  |      14 |      18 |    +28.6% | **0.78x (?)** |
| Set.isSubset.Seq.Empty.Int              |      77 |      85 |    +10.4% | **0.91x (?)** |
| Set.isDisjoint.Seq.Empty.Box            |      83 |      91 |     +9.6% | **0.91x (?)** |
| Set.isStrictSubset.Box0                 |      77 |      84 |     +9.1% | **0.92x (?)** |
| &nbsp;                                  |         |         |           |               |
| **Improvement**                         | **OLD** | **NEW** | **DELTA** |     **RATIO** |
| UTF8Decode_InitDecoding                 |     160 |     126 |    -21.2% | **1.27x (?)** |
| LessSubstringSubstring                  |      29 |      23 |    -20.7% | **1.26x (?)** |
| EqualSubstringSubstring                 |      29 |      23 |    -20.7% | **1.26x (?)** |
| EqualStringSubstring                    |      29 |      23 |    -20.7% | **1.26x (?)** |
| EqualSubstringSubstringGenericEquatable |      29 |      23 |    -20.7% |     **1.26x** |
| EqualSubstringString                    |      29 |      23 |    -20.7% | **1.26x (?)** |
| LessSubstringSubstringGenericComparable |      29 |      23 |    -20.7% |     **1.26x** |
| UTF8Decode_InitFromCustom_contiguous    |     160 |     127 |    -20.6% | **1.26x (?)** |
| StringBuilder                           |     218 |     190 |    -12.8% | **1.15x (?)** |
| ObjectiveCBridgeStringHash              |      78 |      68 |    -12.8% |     **1.15x** |
| UTF8Decode_InitFromCustom_noncontiguous |     279 |     245 |    -12.2% | **1.14x (?)** |
| StringComparison_longSharedPrefix       |     333 |     293 |    -12.0% | **1.14x (?)** |
| AngryPhonebook                          |     336 |     301 |    -10.4% | **1.12x (?)** |
| SortStringsUnicode                      |    2145 |    1955 |     -8.9% | **1.10x (?)** |
| AngryPhonebook.ASCII2.Small             |     149 |     136 |     -8.7% | **1.10x (?)** |
| StringBuilderSmallReservingCapacity     |     217 |     201 |     -7.4% | **1.08x (?)** |
| SubstringEqualString                    |     174 |     162 |     -6.9% | **1.07x (?)** |
| StringHashing_nonBMPSlowestPrenormal    |     300 |     280 |     -6.7% | **1.07x (?)** |

### Code size: -Osize


### Performance (x86_64): -Onone

| **Regression**                          | **OLD** | **NEW** | **DELTA** |     **RATIO** |
| :-------------------------------------- | ------: | ------: | --------: | ------------: |
| StringAdder                             |     376 |     405 |     +7.7% | **0.93x (?)** |
| &nbsp;                                  |         |         |           |               |
| **Improvement**                         | **OLD** | **NEW** | **DELTA** |     **RATIO** |
| LessSubstringSubstringGenericComparable |      32 |      25 |    -21.9% |     **1.28x** |
| UTF8Decode_InitDecoding                 |     166 |     133 |    -19.9% |     **1.25x** |
| UTF8Decode_InitFromCustom_contiguous    |     168 |     135 |    -19.6% | **1.24x (?)** |
| EqualSubstringSubstringGenericEquatable |      32 |      26 |    -18.7% | **1.23x (?)** |
| LessSubstringSubstring                  |      34 |      28 |    -17.6% | **1.21x (?)** |
| EqualSubstringSubstring                 |      34 |      28 |    -17.6% | **1.21x (?)** |
| EqualStringSubstring                    |      34 |      28 |    -17.6% |     **1.21x** |
| EqualSubstringString                    |      34 |      28 |    -17.6% | **1.21x (?)** |
| SIMDReduce.Int8                         |    7175 |    6186 |    -13.8% | **1.16x (?)** |
| ObjectiveCBridgeStringHash              |      78 |      68 |    -12.8% | **1.15x (?)** |
| NSStringConversion                      |     394 |     363 |     -7.9% | **1.09x (?)** |
| SortStringsUnicode                      |    3415 |    3170 |     -7.2% | **1.08x (?)** |

### Code size: -swiftlibs



<details>
  <summary><strong>How to read the data</strong></summary>
The tables contain differences in performance which are larger than 8% and
differences in code size which are larger than 1%.


If you see any unexpected regressions, you should consider fixing the
regressions before you merge the PR.

**Noise**: Sometimes the performance results (not code size!) contain false
alarms. Unexpected regressions which are marked with '(?)' are probably noise.
If you see regressions which you cannot explain you can try to run the
benchmarks again. If regressions still show up, please consult with the
performance team (@eeckstein).
</details>

<details>
  <summary><strong>Hardware Overview</strong></summary>


      Model Name: Mac mini
      Model Identifier: Macmini8,1
      Processor Name: 6-Core Intel Core i7
      Processor Speed: 3.2 GHz
      Number of Processors: 1
      Total Number of Cores: 6
      L2 Cache (per Core): 256 KB
      L3 Cache: 12 MB
      Memory: 32 GB

</details>

**Comment by karwa** [comment]
How about...

```swift
func zeroBytes(hi: inout UInt64, lo: inout UInt64, from len: Int) {
    hi = hi.bigEndian
    lo = lo.bigEndian
    if len <= 8 {
        let hi_len_bits = len &* 8
        hi = (hi >> (64 &- hi_len_bits)) << (64 &- hi_len_bits)
        lo = 0
    } else if len <= 16 {
        let low_len_bits = (len &- 8) &* 8
        lo = (lo >> (64 &- low_len_bits)) << (64 &- low_len_bits)
    }
    hi = hi.bigEndian
    lo = lo.bigEndian
}
```

```swift

func getByteString(_ v: UInt64) -> String {
  "0x" + withUnsafeBytes(of: v) { bytes in
    bytes.lazy.map { ($0 < 10 ? "0" : "") + String($0, radix: 16) }.joined()
  }
}

let initial_hi: UInt64 = 0x88_99_AA_BB_CC_DD_EE_FF
let initial_lo: UInt64 = 0x11_22_33_44_55_66_77_88
print("X", "\t", "-", getByteString(initial_hi), getByteString(initial_lo))
print("")

for i in 0..<17 {
  var hi = initial_hi
  var lo = initial_lo
  zeroBytes(hi: &hi, lo: &lo, from: i)
  print(i, "\t", "-", getByteString(hi), getByteString(lo))
}

X 	 - 0xffeeddccbbaa9988 0x8877665544332211

0 	 - 0x0000000000000000 0x0000000000000000
1 	 - 0xff00000000000000 0x0000000000000000
2 	 - 0xffee000000000000 0x0000000000000000
3 	 - 0xffeedd0000000000 0x0000000000000000
4 	 - 0xffeeddcc00000000 0x0000000000000000
5 	 - 0xffeeddccbb000000 0x0000000000000000
6 	 - 0xffeeddccbbaa0000 0x0000000000000000
7 	 - 0xffeeddccbbaa9900 0x0000000000000000
8 	 - 0xffeeddccbbaa9988 0x0000000000000000
9 	 - 0xffeeddccbbaa9988 0x8800000000000000
10 	 - 0xffeeddccbbaa9988 0x8877000000000000
11 	 - 0xffeeddccbbaa9988 0x8877660000000000
12 	 - 0xffeeddccbbaa9988 0x8877665500000000
13 	 - 0xffeeddccbbaa9988 0x8877665544000000
14 	 - 0xffeeddccbbaa9988 0x8877665544330000
15 	 - 0xffeeddccbbaa9988 0x8877665544332200
16 	 - 0xffeeddccbbaa9988 0x8877665544332211
```

**Comment by glessard** [comment]
@swift-ci please test

**Comment by Catfish-Man** [comment]
@swift-ci please benchmark

**Comment by Catfish-Man** [comment]
@swift-ci please smoke test

**Comment by glessard** [comment]
### Performance (x86_64): -O

| **Regression**                          | **OLD** | **NEW** | **DELTA** |     **RATIO** |
| :-------------------------------------- | ------: | ------: | --------: | ------------: |
| StringComparison_ascii                  |     383 |     422 |    +10.2% | **0.91x (?)** |
| &nbsp;                                  |         |         |           |               |
| **Improvement**                         | **OLD** | **NEW** | **DELTA** |     **RATIO** |
| EqualSubstringSubstring                 |      30 |      23 |    -23.3% |     **1.30x** |
| EqualStringSubstring                    |      30 |      23 |    -23.3% | **1.30x (?)** |
| AngryPhonebook                          |     336 |     266 |    -20.8% |     **1.26x** |
| LessSubstringSubstring                  |      29 |      23 |    -20.7% |     **1.26x** |
| EqualSubstringSubstringGenericEquatable |      29 |      23 |    -20.7% | **1.26x (?)** |
| EqualSubstringString                    |      29 |      23 |    -20.7% | **1.26x (?)** |
| LessSubstringSubstringGenericComparable |      29 |      23 |    -20.7% | **1.26x (?)** |
| AngryPhonebook.ASCII2.Small             |     149 |     123 |    -17.4% | **1.21x (?)** |
| NSStringConversion                      |     361 |     316 |    -12.5% | **1.14x (?)** |
| NSStringConversion.Rebridge             |      92 |      81 |    -12.0% | **1.14x (?)** |
| StringUTF16Builder                      |     230 |     210 |     -8.7% | **1.10x (?)** |
| StringComparison_longSharedPrefix       |     332 |     304 |     -8.4% | **1.09x (?)** |
| Set.isSubset.Int.Empty                  |      48 |      44 |     -8.3% | **1.09x (?)** |
| ObjectiveCBridgeStringHash              |      78 |      72 |     -7.7% | **1.08x (?)** |
| Set.isDisjoint.Box.Empty                |      53 |      49 |     -7.5% | **1.08x (?)** |
| StringHashing_nonBMPSlowestPrenormal    |     300 |     280 |     -6.7% | **1.07x (?)** |

### Code size: -O


### Performance (x86_64): -Osize

| **Regression**                          | **OLD** | **NEW** | **DELTA** |     **RATIO** |
| :-------------------------------------- | ------: | ------: | --------: | ------------: |
| PrefixAnySeqCntRange                    |      14 |      18 |    +28.6% | **0.78x (?)** |
| FlattenListLoop                         |    1421 |    1586 |    +11.6% | **0.90x (?)** |
| Set.isSubset.Seq.Empty.Int              |      77 |      85 |    +10.4% | **0.91x (?)** |
| Set.isDisjoint.Empty.Int                |      81 |      89 |     +9.9% | **0.91x (?)** |
| Set.isDisjoint.Empty.Box                |      82 |      90 |     +9.8% | **0.91x (?)** |
| Set.isDisjoint.Seq.Empty.Box            |      83 |      91 |     +9.6% | **0.91x (?)** |
| Set.isSuperset.Seq.Int.Empty            |      84 |      92 |     +9.5% | **0.91x (?)** |
| Set.isStrictSubset.Int0                 |      75 |      82 |     +9.3% | **0.91x (?)** |
| ObjectiveCBridgeStubToNSStringRef       |      87 |      95 |     +9.2% | **0.92x (?)** |
| &nbsp;                                  |         |         |           |               |
| **Improvement**                         | **OLD** | **NEW** | **DELTA** |     **RATIO** |
| AngryPhonebook                          |     336 |     259 |    -22.9% | **1.30x (?)** |
| FlattenListFlatMap                      |    3953 |    3058 |    -22.6% | **1.29x (?)** |
| LessSubstringSubstring                  |      29 |      23 |    -20.7% |     **1.26x** |
| EqualSubstringSubstring                 |      29 |      23 |    -20.7% |     **1.26x** |
| EqualStringSubstring                    |      29 |      23 |    -20.7% | **1.26x (?)** |
| EqualSubstringSubstringGenericEquatable |      29 |      23 |    -20.7% |     **1.26x** |
| EqualSubstringString                    |      29 |      23 |    -20.7% | **1.26x (?)** |
| LessSubstringSubstringGenericComparable |      29 |      23 |    -20.7% | **1.26x (?)** |
| AngryPhonebook.ASCII2.Small             |     149 |     119 |    -20.1% |     **1.25x** |
| NSStringConversion.Rebridge             |      93 |      81 |    -12.9% | **1.15x (?)** |
| NSStringConversion                      |     366 |     322 |    -12.0% | **1.14x (?)** |
| StringBuilder                           |     217 |     198 |     -8.8% | **1.10x (?)** |
| SortStringsUnicode                      |    2145 |    1960 |     -8.6% | **1.09x (?)** |
| Data.init.Sequence.64kB.Count0.I        |     179 |     165 |     -7.8% | **1.08x (?)** |
| StringComparison_longSharedPrefix       |     332 |     309 |     -6.9% | **1.07x (?)** |

### Code size: -Osize


### Performance (x86_64): -Onone

| **Regression**                          | **OLD** | **NEW** | **DELTA** |     **RATIO** |
| :-------------------------------------- | ------: | ------: | --------: | ------------: |
| StringToDataMedium                      |    2850 |    3100 |     +8.8% | **0.92x (?)** |
| Breadcrumbs.MutatedIdxToUTF16.ASCII     |      13 |      14 |     +7.7% | **0.93x (?)** |
| &nbsp;                                  |         |         |           |               |
| **Improvement**                         | **OLD** | **NEW** | **DELTA** |     **RATIO** |
| EqualStringSubstring                    |      35 |      28 |    -20.0% | **1.25x (?)** |
| EqualSubstringSubstringGenericEquatable |      32 |      26 |    -18.7% |     **1.23x** |
| LessSubstringSubstringGenericComparable |      32 |      26 |    -18.7% | **1.23x (?)** |
| EqualSubstringSubstring                 |      34 |      28 |    -17.6% |     **1.21x** |
| EqualSubstringString                    |      34 |      28 |    -17.6% |     **1.21x** |
| LessSubstringSubstring                  |      34 |      29 |    -14.7% | **1.17x (?)** |
| NSStringConversion                      |     395 |     348 |    -11.9% | **1.14x (?)** |
| ObjectiveCBridgeStringHash              |      78 |      71 |     -9.0% | **1.10x (?)** |
| ArrayOfGenericPOD2                      |    1059 |     979 |     -7.6% | **1.08x (?)** |

### Code size: -swiftlibs



<details>
  <summary><strong>How to read the data</strong></summary>
The tables contain differences in performance which are larger than 8% and
differences in code size which are larger than 1%.


If you see any unexpected regressions, you should consider fixing the
regressions before you merge the PR.

**Noise**: Sometimes the performance results (not code size!) contain false
alarms. Unexpected regressions which are marked with '(?)' are probably noise.
If you see regressions which you cannot explain you can try to run the
benchmarks again. If regressions still show up, please consult with the
performance team (@eeckstein).
</details>

<details>
  <summary><strong>Hardware Overview</strong></summary>


      Model Name: Mac mini
      Model Identifier: Macmini8,1
      Processor Name: 6-Core Intel Core i7
      Processor Speed: 3.2 GHz
      Number of Processors: 1
      Total Number of Cores: 6
      L2 Cache (per Core): 256 KB
      L3 Cache: 12 MB
      Memory: 32 GB

</details>

**Comment by Catfish-Man** [comment]
Using the other PR, this one was just for a few experiments

**Comment by glessard** [comment]
@karwa The change we settled on in https://github.com/apple/swift/pull/59823 is similar in approach to your suggestion.

**Comment by karwa** [comment]
Glad I could help! Calculating the endianness-correct mask instead of byte-swapping back and forth is a nice improvement, too.

**Pull request closed without merging**
