### PR TITLE
Squash a noisy warning

### PR DESCRIPTION
**Pull request by dabrahams**

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please smoke test and merge

**Comment by practicalswift** [comment]
@swift-ci please smoke test and merge

**Comment by jtbandes** [comment]
@swift-ci please smoke test and merge

**Comment by jtbandes** [comment]
@dabrahams I think I fixed the problem (updated your commit); testing/merging.

**Comment by dabrahams** [comment]
@jtbandes thanks!

**Pull request merged**
