### PR TITLE
Add missing StringRef -> std::string conversions

### PR DESCRIPTION
**Pull request by CodaFi**
We've really got to cherry-pick that patch to master...

Fixes the master-next build

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@CodaFi why not push this change to master?  The `str` method exists and is making that conversion explicit.

**Comment by CodaFi** [comment]
This has to be done in concert with the other patches in master-next.  It’s just an annoyance I don’t have time for at the moment.

**Review by stephentyrone — APPROVED** [review]

**Comment by davidungar** [comment]
I'll pull over the `str()` fixes into master. Need to do that before I move the files around. Tx, Robert!

**Pull request merged**
