### PR TITLE
[interop][sourcekit] print submodules of CxxStdlib when printing out …

### PR DESCRIPTION
**Pull request by hyp**
…IDE interface of it

### CODE REVIEW

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please build toolchain

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please build toolchain

**Review by egorzhdan — COMMENTED** [review]
What is the purpose of this?

**Comment by hyp** [comment]
@egorzhdan to print out the module interface for libc++ fully in an IDE that uses sourcekit.

**Comment by hyp** [comment]
unfortunately it might not be enough :(

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please build toolchain

**Comment by hyp** [comment]
@swift-ci please build toolchain

**Pull request merged**
