### PR TITLE
[Runtime] Fixes for demangling to metadata

### PR DESCRIPTION
**Pull request by DougGregor**
Fix three different issues that affect the runtime's demangling to metadata:

* The verification enabled by `SWIFT_ENABLE_MANGLED_NAME_VERIFICATION` could cause the metadata machinery to deadlock, because demangling to metadata was requesting complete metadata when it only needs abstract metadata.
* Our mangling of generic parameter references, which are used in generic requirements (that runtime conditional conformances and runtime demangling depend on), could end up colliding, causing corrupted metadata.
* The resolution of generic parameter references used an older function signature for associated type access functions, which meant that we were calling it incorrectly... and getting bogus results.

Fixes [SR-7553](https://bugs.swift.org/browse/SR-7553) / rdar://problem/39769906

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please benchmark

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by slavapestov** [comment]
Just out of curiosity why did you run the benchmarks? Is any of this code performance-sensitive?

**Pull request merged**
