### PR TITLE
[ClangImporter] `-Xclang -fbuiltin-headers-in-system-modules` is being passed when it shouldn't

### PR DESCRIPTION
**Pull request by al45tair**
We were accidentally setting `requiresBuiltinHeadersInSystemModules` because the `else` here gets executed for things that are not WASI or Musl.  Fix by making it conditional.

rdar://128219177

### CODE REVIEW

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Review by egorzhdan — APPROVED** [review]

**Comment by ian-twilightcoder** [comment]
This is a good change, but `getLibcFileMapping` can return `{}` for other reasons than target mismatches. I think we need to restore `requiresBuiltinHeadersInSystemModules = !libcFileMapping.empty()`

**Comment by al45tair** [comment]
It can, but I believe those are all failure cases that we wouldn't expect to see in practice (unlike the target mismatch).

**Comment by ian-twilightcoder** [comment]
Still makes me nervous, but ok.

**Pull request merged**
