### PR TITLE
[6.0][stdlib] API additions for basic noncopyable primitives

### PR DESCRIPTION
**Pull request by lorentey**
- **Explanation:** Implement API additions from [SE-0437](https://github.com/apple/swift-evolution/blob/main/proposals/0437-noncopyable-stdlib-primitives.md).
- **Scope:** Additive changes to core types in the Standard Library. Replaces the implementation of `swap(_:_:)`.
- **Risk:** Low.
- **Testing:** Newly implemented, basic test coverage. Manual testing for "condfail"-style failures with obsolete compiler builds.
- **Reviewer:** @glessard, @Azoy
- **Original PR:** https://github.com/apple/swift/pull/73807
- **Issue:** rdar://128504726

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test source compatibility

**Comment by lorentey** [comment]
@swift-ci build toolchain

**Comment by lorentey** [comment]
The release configuration source compat suite failed with this assert in CareKit 5.0:

```
Assertion failed: (FragmentOffset >= OffsetInBits && "overlapping or duplicate fragments"), function addFragmentOffset, file DwarfExpression.cpp, line 686.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Running pass 'Function Pass Manager' on module '/Users/ec2-user/jenkins/workspace/swift-PR-source-compat-suite-macos/swift-source-compat-suite/project_cache/CareKit-build/Build/Intermediates.noindex/CareKitUI.build/Release-iphoneos/CareKitUI.build/Objects-normal/arm64/OCKContactDisplayable.o'.
1.	Running pass 'AArch64 Assembly Printer' on function '@"$s9CareKitUI10HeaderViewV4bodyQrvg"'
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
Rename failed: /Users/ec2-user/jenkins/workspace/swift-PR-source-compat-suite-macos/swift-source-compat-suite/project_cache/CareKit-build/Build/Intermediates.noindex/CareKitUI.build/Release-iphoneos/CareKitUI.build/Objects-normal/arm64/LabeledValueTaskView-b1ec3bec.o.tmp -> /Users/ec2-user/jenkins/workspace/swift-PR-source-compat-suite-macos/swift-source-compat-suite/project_cache/CareKit-build/Build/Intermediates.noindex/CareKitUI.build/Release-iphoneos/CareKitUI.build/Objects-normal/arm64/LabeledValueTaskView.o: No such file or directory
Rename failed: /Users/ec2-user/jenkins/workspace/swift-PR-source-compat-suite-macos/swift-source-compat-suite/project_cache/CareKit-build/Build/Intermediates.noindex/CareKitUI.build/Release-iphoneos/CareKitUI.build/Objects-normal/arm64/OCKLocalization-a3beb310.o.tmp -> /Users/ec2-user/jenkins/workspace/swift-PR-source-compat-suite-macos/swift-source-compat-suite/project_cache/CareKit-build/Build/Intermediates.noindex/CareKitUI.build/Release-iphoneos/CareKitUI.build/Objects-normal/arm64/OCKLocalization.o: No such file or directory
Rename failed: /Users/ec2-user/jenkins/workspace/swift-PR-source-compat-suite-macos/swift-source-compat-suite/project_cache/CareKit-build/Build/Intermediates.noindex/CareKitUI.build/Release-iphoneos/CareKitUI.build/Objects-normal/arm64/LinkButton-b9669bec.o.tmp -> /Users/ec2-user/jenkins/workspace/swift-PR-source-compat-suite-macos/swift-source-compat-suite/project_cache/CareKit-build/Build/Intermediates.noindex/CareKitUI.build/Release-iphoneos/CareKitUI.build/Objects-normal/arm64/LinkButton.o: No such file or directory
Rename failed: /Users/ec2-user/jenkins/workspace/swift-PR-source-compat-suite-macos/swift-source-compat-suite/project_cache/CareKit-build/Build/Intermediates.noindex/CareKitUI.build/Release-iphoneos/CareKitUI.build/Objects-normal/arm64/OCKGridView-32ece8b3.o.tmp -> /Users/ec2-user/jenkins/workspace/swift-PR-source-compat-suite-macos/swift-source-compat-suite/project_cache/CareKit-build/Build/Intermediates.noindex/CareKitUI.build/Release-iphoneos/CareKitUI.build/Objects-normal/arm64/OCKGridView.o: No such file or directory
0  swift-frontend           0x000000010ae53638 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 40
1  swift-frontend           0x000000010ae517d8 llvm::sys::RunSignalHandlers() + 248
2  swift-frontend           0x000000010ae53c9e SignalHandler(int) + 270
3  libsystem_platform.dylib 0x00007ff8112e05ed _sigtramp + 29
4  swift-frontend           0x000000010760ecf4 llvm::DwarfCompileUnit::createAndAddScopeChildren(llvm::LexicalScope*, llvm::DIE&) + 4580
5  libsystem_c.dylib        0x00007ff8111d9b45 abort + 123
6  libsystem_c.dylib        0x00007ff8111d8e5e err + 0
7  swift-frontend           0x000000010ba57e73 llvm::DwarfExpression::addFragmentOffset(llvm::DIExpression const*) (.cold.1) + 35
8  swift-frontend           0x0000000107643188 llvm::DwarfExpression::addFragmentOffset(llvm::DIExpression const*) + 184
9  swift-frontend           0x0000000107613160 decltype(auto) std::__1::__variant_detail::__visitation::__base::__dispatcher<3ul>::__dispatch[abi:v160006]<std::__1::__variant_detail::__visitation::__variant::__value_visitor<llvm::detail::Visitor<llvm::DwarfCompileUnit::constructVariableDIEImpl(llvm::DbgVariable const&, bool)::$_5, llvm::DwarfCompileUnit::constructVariableDIEImpl(llvm::DbgVariable const&, bool)::$_4, llvm::DwarfCompileUnit::constructVariableDIEImpl(llvm::DbgVariable const&, bool)::$_3, llvm::DwarfCompileUnit::constructVariableDIEImpl(llvm::DbgVariable const&, bool)::$_2, llvm::DwarfCompileUnit::constructVariableDIEImpl(llvm::DbgVariable const&, bool)::$_1>>&&, std::__1::__variant_detail::__base<(std::__1::__variant_detail::_Trait)1, std::__1::monostate, llvm::Loc::Single, llvm::Loc::Multi, llvm::Loc::MMI, llvm::Loc::EntryValue> const&>(std::__1::__variant_detail::__visitation::__variant::__value_visitor<llvm::detail::Visitor<llvm::DwarfCompileUnit::constructVariableDIEImpl(llvm::DbgVariable const&, bool)::$_5, llvm::DwarfCompileUnit::constructVariableDIEImpl(llvm::DbgVariable const&, bool)::$_4, llvm::DwarfCompileUnit::constructVariableDIEImpl(llvm::DbgVariable const&, bool)::$_3, llvm::DwarfCompileUnit::constructVariableDIEImpl(llvm::DbgVariable const&, bool)::$_2, llvm::DwarfCompileUnit::constructVariableDIEImpl(llvm::DbgVariable const&, bool)::$_1>>&&, std::__1::__variant_detail::__base<(std::__1::__variant_detail::_Trait)1, std::__1::monostate, llvm::Loc::Single, llvm::Loc::Multi, llvm::Loc::MMI, llvm::Loc::EntryValue> const&) + 272
10 swift-frontend           0x000000010760f97a llvm::DwarfCompileUnit::constructVariableDIEImpl(llvm::DbgVariable const&, bool) + 282
11 swift-frontend           0x000000010760e93e llvm::DwarfCompileUnit::createAndAddScopeChildren(llvm::LexicalScope*, llvm::DIE&) + 3630
12 swift-frontend           0x000000010760fd7f llvm::DwarfCompileUnit::constructSubprogramScopeDIE(llvm::DISubprogram const*, llvm::LexicalScope*)Rename failed: /Users/ec2-user/jenkins/workspace/swift-PR-source-compat-suite-macos/swift-source-compat-suite/project_cache/CareKit-build/Build/Intermediates.noindex/CareKitUI.build/Release-iphoneos/CareKitUI.build/Objects-normal/arm64/OCKDetailView-ac84cba5.o.tmp -> /Users/ec2-user/jenkins/workspace/swift-PR-source-compat-suite-macos/swift-source-compat-suite/project_cache/CareKit-build/Build/Intermediates.noindex/CareKitUI.build/Release-iphoneos/CareKitUI.build/Objects-normal/arm64/OCKDetailView.o: No such file or directory
 + 159
13 swift-frontend           0x000000010762366e llvm::DwarfDebug::endFunctionImpl(llvm::MachineFunction const*) + 1902
14 swift-frontend           0x0000000107601757 llvm::DebugHandlerBase::endFunction(llvm::MachineFunction const*) + 55
15 swift-frontend           0x00000001075e08db llvm::AsmPrinter::emitFunctionBody() + 12843
16 swift-frontend           0x0000000106d73aad (anonymous namespace)::AArch64AsmPrinter::runOnMachineFunction(llvm::MachineFunction&) + 173
17 swift-frontend           0x00000001084ac2a1 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) + 641
18 swift-frontend           0x000000010ab1dc45 llvm::FPPassManager::runOnFunction(llvm::Function&) + 1669
19 swift-frontend           0x000000010ab259e4 llvm::FPPassManager::runOnModule(llvm::Module&) + 68
20 swift-frontend           0x000000010ab1e5f2 llvm::legacy::PassManagerImpl::run(llvm::Module&) + 1954
21 swift-frontend           0x0000000104f99d61 swift::compileAndWriteLLVM(llvm::Module*, llvm::TargetMachine*, swift::IRGenOptions const&, swift::UnifiedStatsReporter*, swift::DiagnosticEngine&, llvm::raw_pwrite_stream&, llvm::sys::SmartMutex<false>*, llvm::raw_pwrite_stream*) + 305
Rename failed: /Users/ec2-user/jenkins/workspace/swift-PR-source-compat-suite-macos/swift-source-compat-suite/project_cache/CareKit-build/Build/Intermediates.noindex/CareKitUI.build/Release-iphoneos/CareKitUI.build/Objects-normal/arm64/OCKGraphAxisView-f99a4abf.o.tmp -> /Users/ec2-user/jenkins/workspace/swift-PR-source-compat-suite-macos/swift-source-compat-suite/project_cache/CareKit-build/Build/Intermediates.noindex/CareKitUI.build/Release-iphoneos/CareKitUI.build/Objects-normal/arm64/OCKGraphAxisView.o: No such file or directory
22 swift-frontend           0x0000000104f98f45 swift::performLLVM(swift::IRGenOptions const&, swift::DiagnosticEngine&, llvm::sys::SmartMutex<false>*, llvm::GlobalVariable*, llvm::Module*, llvm::TargetMachine*, llvm::StringRef, llvm::vfs::OutputBackend&, swift::UnifiedStatsReporter*) + 2405
23 swift-frontend           0x0000000104fa012b (anonymous namespace)::LLVMCodeGenThreads::Thread::run() + 491
24 swift-frontend           0x0000000104f9ff39 (anonymous namespace)::LLVMCodeGenThreads::runThread(void*) + 9
25 libsystem_pthread.dylib  0x00007ff8112b31d3 _pthread_start + 125
26 libsystem_pthread.dylib  0x00007ff8112aebd3 thread_start + 15
Command SwiftCompile failed with a nonzero exit code
```

`$s9CareKitUI10HeaderViewV4bodyQrvg` demangles to `CareKitUI.HeaderView.body.getter`:

https://github.com/carekit-apple/CareKit/blob/5288dce002c38d81ee6470fc7dbe41f5d80de375/CareKitUI/CareKitUI/Shared/Components/HeaderView.swift#L57
```swift
    public var body: some View {
        HStack(spacing: style.dimension.directionalInsets2.trailing) {
            image?
                .font(.largeTitle)
            VStack(alignment: .leading, spacing: style.dimension.directionalInsets1.top / 4.0) {
                title
                    .font(.headline)
                    .fontWeight(.bold)
                    // Allows multiline text to wrap to the next line
                    .fixedSize(horizontal: false, vertical: true)
                detail?
                    .font(.caption)
                    .fontWeight(.medium)
                    // Allows multiline text to wrap to the next line
                    .fixedSize(horizontal: false, vertical: true)
            }.foregroundColor(Color.primary)
        }
    }
```

This does include some Optional use, but it is unclear how the changes in this PR could trigger these symptoms.

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci clean build toolchain

**Comment by lorentey** [comment]
@swift-ci test source compatibility

**Comment by lorentey** [comment]
@swift-ci test source compatibility

**Comment by lorentey** [comment]
The last rebase also removes the preexisting `Optional._take` alias for the new `Optional.take`, matching #73807.

This isn't expected to trigger issues outside of this repo; there are no known external adopters of the underscored spelling. (And it never shipped in any previous Swift release.)

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci build toolchain

**Comment by lorentey** [comment]
@swift-ci test source compatibility

**Comment by lorentey** [comment]
Holding for condfail investigations, or rescheduling.

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test source compatibility

**Review by stephentyrone — APPROVED** [review]

**Pull request merged**
