### PR TITLE
[ConstraintSystem] Remove used/checked conformances cache

### PR DESCRIPTION
**Pull request by xedin**
-  Adjust `ConformanceRequirement` locator to carry `ProtocolConformance`
- Stop using `CheckedConformances` cache
  - Change `applySolutionToForEachStmt` to double-check conformance;
  -  Adjust requirement failures to retrieve conformance information from locator
- Remove obsolete used/checked conformances cache from `ConstraintSystem` and `Solution`

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please smoke test compiler performance

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by slavapestov** [comment]
Nice cleanup!

**Comment by xedin** [comment]
@swift-ci please test source compatibility debug

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please smoke test compiler performance

**Comment by xedin** [comment]
I suspect that this `Frontend.MaxMallocUsage` difference in release more is just flakiness...

**Comment by xedin** [comment]
Looks like some of the counters are indeed a bit flaky.

**Pull request merged**
