### PR TITLE
libSyntax: allow children of syntax nodes to have multiple choices. rdar://35879331

### PR DESCRIPTION
**Pull request by nkcsgexi**
Some structures of syntax nodes can have children choices, e.g. a
dictionary expression can either contain a single ':' token or a list of
key-value pairs.

This patch gives the existing code generation infrastructure a way to
specify such node choices. Node choices are specified under a child
declaration with two constraints: a choice cannot be declared as
optional, and a choice cannot have further recursive choices.

Since we don't have too many node structures with choices, part of the
SyntaxFactory code for these nodes is manually typed.

This patch also teaches AccessorBlock to use node choices.

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Review by harlanhaskins — APPROVED** [review]
Seems good to me 👍

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Review by rintaro — APPROVED** [review]
Good start!
I'm not a fan of hardcoded check function (i.e. `checkAccessorListOrStmtList`), but we are able to fix it later.

**Comment by nkcsgexi** [comment]
@rintaro yeah, me neither. The observation here is that we may only have several (three for now) either nodes, so that hard coding them is not a huge effort.

**Pull request merged**
