### PR TITLE
benchmarks: some additions to the reporting scripts

### PR DESCRIPTION
**Pull request by eeckstein**
* add an option to the bench_code_size script to separately report code size for the swift libraries
* add an option to the compare_perf_tests script to output improvements and regressions in an single table.

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci smoke test and merge

**Comment by palimondo** [comment]
@eeckstein What is the intended use of `single-table` option? It looks like it is not used by CI bots, yet ([recent benchmark report](https://github.com/apple/swift/pull/18667#issuecomment-413059973)). Right?

I had a minor conflict around this change and though I might also write a test for it, while I'm at it...

**Comment by eeckstein** [comment]
I'd like to improve the output format of the benchmark report. But it's still in experimental phase. So it's not yet used by the bots

> I had a minor conflict around this change and though I might also write a test for it, while I'm at it...

That would be cool!

**Comment by palimondo** [comment]
I was asking, because it isn't clear to me what it should do… (it also isn't using the formatter correctly)

Can you hold on changing this for a moment? I'm nearing completion on my PR and like to finish it without more conflicts. I promise to get back to this and change it the way you'd like to to work. Could you describe what you're after in more details?

**Comment by eeckstein** [comment]
Let me get back to you next week.

**Pull request merged**
