### PR TITLE
Rename "textual interface" to "parseable interface"

### PR DESCRIPTION
**Pull request by jrose-apple**
We already have something called "module interfaces" -- it's the generated interface view that you can see in Xcode, the interface that's meant for developers using a library. Of course, that's also a textual format. To reduce confusion, rename the new module stability feature to "parseable [module] interfaces".

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
I can see us still changing the name of the Xcode feature too (I liked "module view" or "module interface view") but for now let's just change the new thing.

**Comment by nkcsgexi** [comment]
Actually, i prefer "Module View" for it's being shorter. @akyrtzi What do you think?

**Comment by akyrtzi** [comment]
I like "Module View" as well. It allows representing something that is not necessarily a textual dump of source code.

**Comment by jrose-apple** [comment]
Okay, I'll do that one next!

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test Linux

**Pull request merged**
