### PR TITLE
[ClangImporter] Use UnboundGenericTypes in compatibility typealiases.

### PR DESCRIPTION
**Pull request by jrose-apple**
When a type is renamed, we leave behind a "compatibility typealias" whose underlying type uses the new name. For generic types, though, we were using the generic parameters and environment of the original type, which is completely bogus. "Fix" this by just dropping the generic part entirely and making a typealias that refers to the *unbound* generic type, as if written as `typealias OldName = NewName` instead of `typealias OldName<Element> = NewName<Element>`. The rest of the compiler can handle that fine.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Review by slavapestov — APPROVED** [review]
LGTM!

**Comment by DougGregor** [comment]
Wait, so... the type checker is resolving this `UnboundGenericType`?

**Comment by jrose-apple** [comment]
That's how we're currently modeling `typealias OldName = NewName` when NewName happens to be a generic type, even in pure Swift code. I wouldn't mind that changing in the future, but for now it seems okay to take advantage of it.

**Pull request merged**
