### PR TITLE
[PrintAsObjC] Make sure the preprocessor checks work in a compiler different than clang

### PR DESCRIPTION
**Pull request by akyrtzi**
The C preprocessor rules don't short-circuit so "#if defined(__has_feature) && __has_feature(modules)" will always fail if '__has_feature' is not defined.

### CODE REVIEW

**Comment by akyrtzi** [comment]
@swift-ci smoke test

**Review by jrose-apple — APPROVED** [review]

**Comment by akyrtzi** [comment]
Test failure is unrelated.

**Comment by akyrtzi** [comment]
@swift-ci smoke test Linux platform

**Comment by akyrtzi** [comment]
@swift-ci smoke test and merge

**Pull request merged**
