### PR TITLE
Added never-failing Result

### PR DESCRIPTION
**Pull request by hfhbd**
Hey, 

inspired by Combine.Publisher.replaceError(with:) I would like to add replaceFailure(with:) to the Result Type.

Implemented replaceFailure(with:) to create a never-failing result and to replace any failure with a success value. Also added a safe get() function for a never-failing result.

### CODE REVIEW

**Comment by harlanhaskins** [comment]
Thanks for your contribution! Just a heads-up, this change will need to go through the [Swift Evolution process](https://github.com/apple/swift-evolution/blob/master/process.md) and be approved by the core team before we'll be able to merge this PR. I'll go ahead and mark this as "Swift Evolution pending discussion", and I'd recommend pitching this on forums.swift.org before writing your proposal.

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by CodaFi** [comment]
@hfhbd Did you ever wind up writing an evolution proposal for this?

**Comment by hfhbd** [comment]
@CodaFi I wrote a this [pitch](https://forums.swift.org/t/never-failing-result-type) and got mixed answers. But I am up to create a proposal.

**Comment by CodaFi** [comment]
Please do if you can. It would be good to get an up-or-down vote on this.

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
