### PR TITLE
Windows: add some defines from `WinUser.h`

### PR DESCRIPTION
**Pull request by compnerd**
Add the windows message queue status flags macros.  This should allow the use of the macros when writing Windows code.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please smoke test macOS platform

**Comment by grynspan** [comment]
Gross.

**Review by grynspan — APPROVED** [review]

**Comment by grynspan** [comment]
Would be great if you could add some link to the MSVC++ equivalent in a comment.

**Comment by compnerd** [comment]
> Gross.

Limitations of the clang importer :)

> Would be great if you could add some link to the MSVC++ equivalent in a comment.

The variables themselves are the MSVC++ equivalents.  They just don't import due to the "complex macro" representation.  I'm not sure that there are stable links to the declaration if that is what you were suggesting.

**Pull request merged**
