### PR TITLE
Revert "[Incremental] Dependency fixes in preparation for fine-grained dependencies"

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/swift#29009

This change broke the Windows bot.  Reverting until the issue on the Windows bots can be addressed.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @davidungar @CodaFi

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by compnerd** [comment]
CC: @harlanhaskins

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by CodaFi** [comment]
Please don’t merge that second revert. That commit is ancient.  There is a deeper cause to these failures.

**Comment by CodaFi** [comment]
Do you have any insight into the reason things aren’t working here?

**Comment by compnerd** [comment]
No, not off hand; Actually, taking a closer look, seems that the failure that exits without the second change is actually what is happening on Windows - so that brings things to parity.   I'll remove that change from the stack, but I cannot get this merged :/

**Comment by compnerd** [comment]
```
Assertion failed: interface->getKey().isInterface() && implementation->getKey().isImplementation() && "Interface must be interface, implementation must be implementation.", file C:\agent\_work\6\s\toolchain\swift\include\swift/AST/FineGrainedDependencies.h, line 396
```

**Comment by compnerd** [comment]
@CodaFi can you either force push the revert or fix it?

**Comment by CodaFi** [comment]
I don’t have the authority.  I’ll ask our build czars.

**Comment by shahmishal** [comment]
Merged to unblock Windows CI

**Pull request merged**
