### PR TITLE
Access static stored properties declared in Swift directly.

### PR DESCRIPTION
**Pull request by jckarter**
Targeted fix for SR-1025.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@slavapestov Mind reviewing this?

**Comment by slavapestov** [comment]
Thanks, looks good. Do you mind checking in just the test to master?

**Comment by jckarter** [comment]
Sure thing @slavapestov. #1912 brings the test to master.

@tkremenek, can we consider this for a 2.2 update?

**Comment by tkremenek** [comment]
@swift-ci test

**Pull request merged**
