### PR TITLE
Remove constexpr to satisfy MSVC being what it is.

### PR DESCRIPTION
**Pull request by gottesmm**

### CODE REVIEW

**Comment by gottesmm** [comment]
@drodriguez

**Comment by gottesmm** [comment]
@swift-ci please test Windows platform

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by compnerd** [comment]
Yeah, don't think that `drop_front` is a constexpr expression, thanks for fixing this @gottesmm

**Review by drodriguez — APPROVED** [review]
The error in Windows seems to be an unrelated flaky test. I was not sure the constexpr could be removed, but if it is not necessary, away with it :D

**Pull request merged**
