### PR TITLE
Simplify devirtualization and fix a bug

### PR DESCRIPTION
**Pull request by slavapestov**
Replace if statements with asserts, figure out why assert is firing, delete some code, repeat.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by swiftix** [comment]
@slavapestov So, you couldn't resit, but remove all this "can be converted in an ABI compatible way" logic? ;-) Overall, it looks simpler. But I see a high potential for breaking things. IIRC, not all of the affected code paths are currently covered by tests. We need to see if it breaks things in the wild.

**Review by swiftix — APPROVED** [review]
So, let's merge and see of anything is broken.

**Comment by slavapestov** [comment]
"So, let's merge and see of anything is broken." That's the spirit :-)

**Pull request merged**
