### PR TITLE
[Mem2Reg] Always bail on dynamic_lifetime.

### PR DESCRIPTION
**Pull request by nate-chandler**
rdar://136388508

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Review by eeckstein — APPROVED** [review]

**Review by meg-gupta — APPROVED** [review]

**Comment by nate-chandler** [comment]
@swift-ci please smoke test linux platform

**Comment by nate-chandler** [comment]
@swift-ci please test macos platform

**Comment by nate-chandler** [comment]
@swift-ci please test linux platform

**Pull request merged**
