### PR TITLE
utils: add support to run the Windows toolchain tests

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @shahmishal

**Comment by compnerd** [comment]
This covers swift compiler, standard library, and the core libraries (dispatch, foundation, xctest).

**Comment by compnerd** [comment]
@swift-ci please test

**Review by shahmishal — APPROVED** [review]

**Comment by shahmishal** [comment]
@swift-ci please test

**Pull request merged**
