### PR TITLE
IRGen: Correctly compute the offset for a non-fixed field after an empty field

### PR DESCRIPTION
**Pull request by aschwaighofer**
rdar://62349871

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test os x

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Review by slavapestov — APPROVED** [review]

**Pull request merged**
