### PR TITLE
build: rename `EXPERIMENTAL_STRING_PROCESSING_SOURCE_DIR`

### PR DESCRIPTION
**Pull request by compnerd**
Rename the variable to `SWIFT_PATH_TO_STRING_PROCESSING_SOURCE` to match the variables used for libdispatch, swift-syntax.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by etcwilde** [comment]
CC @edymtt

**Comment by compnerd** [comment]
CC: @etcwilde

**Comment by compnerd** [comment]
@swift-ci please test

**Review by eeckstein — APPROVED** [review]

**Pull request merged**
