### PR TITLE
CMake: add option to link Swift content from Darwin toolchain

### PR DESCRIPTION
**Pull request by edymtt**
This is needed in specific Apple internal configurations -- as a result of the limited applicability, this option is not exposed through `build-script` on purpose.

Addresses rdar://127014753

### CODE REVIEW

**Review by compnerd — APPROVED** [review]
This is rather unfortunate - these dependencies will not be tracked by the build and so the build may not always be entirely correct.

**Comment by edymtt** [comment]
Thanks for understanding -- I'm not fond of these changes either, my plan is to remove those once I figure out a better long term solution.

**Comment by edymtt** [comment]
@swift-ci please test

**Comment by edymtt** [comment]
@swift-ci please build toolchain

**Comment by edymtt** [comment]
@swift-ci please test WebAssembly

**Review by al45tair — APPROVED** [review]
It's a bit unpleasant, but it lets us make progress fixing things so we hopefully won't need it at some point and can get rid of it again.

**Pull request merged**
