### PR TITLE
[🍒 6.0] CMake: ensure Swift host tools depend on HostCompatibilityLibs target

### PR DESCRIPTION
**Pull request by edymtt**
**Explanation**: explicitly add a dependency between Swift host tools and the compatibility libraries we just built -- we never noticed this was missing in the first place because in most configurations the latter are able to build before the former need them
**Radar**: rdar://126552386
**Scope**: CMake logic that builds the Swift part of the compiler and tools
**Risk**: low
* there are no functional changes in how the compiler is built
* in the worst case, we hit the same failure again because the added dependencies are not enough
**Testing**:

* CI testing -- in particular run compatibility suite and built toolchain

**Reviewed By**: @compnerd in https://github.com/apple/swift/pull/73065

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci please test

**Comment by edymtt** [comment]
@swift-ci please test WebAssembly

**Comment by edymtt** [comment]
@swift-ci please test Apple Silicon

**Comment by edymtt** [comment]
@swift-ci please build toolchain

**Comment by edymtt** [comment]
@swift-ci Please Test Source Compatibility Release

**Review by compnerd — APPROVED** [review]

**Review by shahmishal — APPROVED** [review]

**Pull request merged**
