### PR TITLE
Update test to remove dependency on Foundation.

### PR DESCRIPTION
**Pull request by marksands**
#### What's in this pull request?

Per @gribozavr's comment [here](https://github.com/apple/swift/commit/78db42ea71621324cef31493e23ea1883486d83a), this provides a slimmed test case in pure swift that uses no standard libraries.
#### Related to bug number: ([SR-1267](https://bugs.swift.org/browse/SR-1267))

The fix is already in place, but this provides a better test case.

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

Using APIs from Foundation and the standard library can be a source of
pain and can create fragile tests due to API changes. This reduces the
test case to pure swift and eliminates the use of the standard library APIs.

See also issue #2256

This is my first contribution to swift, so feedback welcome!

### CODE REVIEW

**Comment by gribozavr** [comment]
CC @jopamer

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
[SR-1274](https://bugs.swift.org/browse/SR-1274) turned out to be the same issue, and Diego has a very nice reduced test case there:

```swift
protocol Protocol {}
class ConformingClass: Protocol {}
class BaseClass<T: Protocol> {}
class ConcreteClass<T: ConformingClass> : BaseClass<T>{}
```

**Comment by marksands** [comment]
@jrose-apple Ahh very nice! 👏 Feel free to pass on this, then. I appreciate everyone taking the time to look at this.

**Comment by marksands** [comment]
Unless you want me to update my test case? Which I can certainly do! But I don't want to steal Diego's credit..

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by jrose-apple** [comment]
I think it's fine. It's referenced in this pull request, and one of us would have committed it had we investigated SR-1274 before SR-1267. Thanks for the update!

**Comment by jopamer** [comment]
Thanks - yeah - I definitely should have included this test instead. (I was just in a hurry to get the fix into 2.2.)

**Comment by jopamer** [comment]
I think you need to remove the "XFAIL: linux" from the top of the file. Once that's done, we should be able to pull this in. Thanks again!

**Comment by marksands** [comment]
@jopamer done!

**Comment by jopamer** [comment]
Thanks!

**Comment by jopamer** [comment]
@swift-ci Please test

**Comment by jopamer** [comment]
@shahmishal Infrastructure issue?

**Comment by shahmishal** [comment]
@jopamer This is real REPL failure which has been failing for few days in master. 
https://bugs.swift.org/browse/SR-1109

Following test are failing on OS X after these commits on master 
2e38280047571ebbbba0debff7c67590b944b046
09000e974bd48d36a1201d910d8aca9581ff431b
 
```
Failing Tests (2):
    Swift :: SourceKit/DocSupport/doc_clang_module.swift
    Swift :: SourceKit/DocSupport/doc_swift_module.swift
```

**Comment by jopamer** [comment]
Ok, thanks Mishal! So this PR looks good then - merging.

**Pull request merged**
