### PR TITLE
[5.1] [ConstraintSystem] Fix crash on function conversion reliant on conditional conformance

### PR DESCRIPTION
**Pull request by theblixguy**
This PR fixes a compiler crasher related to a function conversion reliant on conditional conformance. Example:

```swift
protocol P {}
struct S<T> {}
extension S : P where T : P {}

func foo(_ fn: (S<String>) -> Void) {}
func bar(_ fn: (P) -> Void) {
  foo(fn)
}
```

Resolves [SR-10992](https://bugs.swift.org/browse/SR-10992).

---

Cherry pick of #25721.

### CODE REVIEW

**Comment by theblixguy** [comment]
cc @xedin

**Comment by xedin** [comment]
@theblixguy Could you please squash everything into a single commit?

**Comment by theblixguy** [comment]
@xedin Done!

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@theblixguy Looks like there are 2 tests which trigger exactly the same assert now this is trying to fix, bad merge? :)

**Comment by theblixguy** [comment]
Oh no, seems like the commit where I added getConstraintLocator to FailureDiagnostic has gone missing! I’ll fix this in a moment.

**Comment by theblixguy** [comment]
Wait this has the same changes as the other PR 🤔

**Comment by xedin** [comment]
Maybe the difference is that 5.1 doesn't have all of the changes that master has.

**Comment by xedin** [comment]
But it kind of seems unlikely in this case, because assert in old `getConstraintLocator` should effectively be noop now for the case when summary flags is pre-computed, maybe something else is going on here.

**Comment by theblixguy** [comment]
Ah I see, it seems like `simplifyConformsToConstraint` is calling that method but passing the wrong flags. I think this is happening when creating the `MissingConformance::forRequirement` fix. Maybe the builder is returning wrong flags?

**Comment by theblixguy** [comment]
Nevermind, it seems like there are still some uses of summeryFlags=0 left.

**Comment by theblixguy** [comment]
@xedin should be fixed now. Does the change look okay to you?

**Comment by xedin** [comment]
@swift-ci please test

**Review by xedin — APPROVED** [review]

**Comment by theblixguy** [comment]
Hmm getting an unrelated assertion now:

> 18:57:41 swift: /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-swift-5.1-branch/swift/lib/Sema/CSDiagnostics.cpp:220: swift::ValueDecl *swift::constraints::RequirementFailure::getDeclRef() const: Assertion `isa<TypeExpr>(AE->getFn()) || isa<OverloadedDeclRefExpr>(AE->getFn())' failed.

**Comment by theblixguy** [comment]
@hamishknight seems like you were the last person who touched getDeclRef in commit 894a1e50bf4c88adc77f46f34e47f01174e8091e (PR #24826) and got rid of that assertion. I think we need your PR changes in this branch as well.

**Comment by xedin** [comment]
@theblixguy We need to figure out how to reduce the scope of the changes required, otherwise it wouldn't be able to land in 5.1

**Comment by theblixguy** [comment]
Hmm Hamish’s PR is pretty small and fixes two bugs in the process. Let me try adjusting getDeclRef only and see if the tests pass locally on my machine.

**Comment by xedin** [comment]
Alright, I'll try to look at his PR again tonight and get it in to 5.1

**Comment by theblixguy** [comment]
Sounds good!

**Comment by xedin** [comment]
@theblixguy looks like you'd have to resolve merge conflict because I can re-run CI.

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test

**Comment by theblixguy** [comment]
Sorry I messed up when fixing the merge conflict! Could you re run the CI? Thank you!

**Comment by xedin** [comment]
@swift-ci please test

**Comment by theblixguy** [comment]
Nice it seems like @hamishknight’s  PR solved the problem 🎉

**Pull request merged**
