### PR TITLE
[IRGen] Reject enums with inaccessible tpye metadata in layout string…

### PR DESCRIPTION
**Pull request by drexin**
… generation

rdar://107679697

Because we are currently handling most enums in layout strings by going through the metadata, we have to ensure that the metadata is accessible from the current module and reject the enum otherwise.

### CODE REVIEW

**Comment by drexin** [comment]
@swift-ci smoke test

**Review by aschwaighofer — APPROVED** [review]

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@swift-ci smoke test

**Pull request merged**
