### PR TITLE
[5.1] Un-set CMAKE_C_COMPILER_LAUNCHER and CMAKE_CXX_COMPILER_LAUNCHER in s…

### PR DESCRIPTION
**Pull request by shahmishal**
…… (#23806)

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@fredriss @dcci @adrian-prantl Is this known issue on `swift-5.1-branch`?

```
01:30:19 Testing Time: 428.19s
01:30:19 ********************
01:30:19 Failing Tests (3):
01:30:19     lldb-Suite :: lang/swift/foundation/TestSwiftFoundation.py
01:30:19     lldb-Suite :: lang/swift/unknown_reference/TestSwiftUnknownReference.py
01:30:19     lldb-Suite :: lang/swift/unknown_self/TestSwiftUnknownSelf.py
01:30:19 
```

**Comment by shahmishal** [comment]
@swift-ci test Linux

**Comment by adrian-prantl** [comment]
```
01:24:12 Build Command Output:
01:24:12 /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-swift-5.1-branch/lldb/packages/Python/lldbsuite/test/lang/swift/unknown_reference/main.swift:12:8: error: missing required module 'CoreFoundation'
01:24:12 import Foundation
01:24:12        ^
```

These tests all depend on swiftcorelibs-foundation. It looks like the same error also started happening on the bots: https://ci.swift.org/view/LLDB/job/oss-lldb-swift-5.1-incremental-linux-ubuntu-18_04/378/consoleFull#-3714861073122a513-f36a-4c87-8ed7-cbc36a1ec144

**Comment by adrian-prantl** [comment]
Unfortunately the last 10 or so builds were failing with a compile error in libdispatch so I can't even say when this broke.

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test Linux

**Comment by shahmishal** [comment]
@swift-ci test Linux

**Pull request merged**
