### PR TITLE
Merge `rebranch` into `main` to support `stable/20221013` llvm-project branch

### PR DESCRIPTION
**Pull request by shahmishal**
This merge is pulling in support for new llvm-project branch created from `next` on Oct 13th 2022.

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci build toolchain

**Comment by shahmishal** [comment]
@swift-ci clean test

**Comment by shahmishal** [comment]
@swift-ci clean build toolchain

**Comment by eeckstein** [comment]
@swift-ci clean test

**Comment by eeckstein** [comment]
@swift-ci clean build toolchain

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci build toolchain

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci build toolchain

**Comment by shahmishal** [comment]
@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
@swift-ci test macOS

**Comment by shahmishal** [comment]
@swift-ci build toolchain

**Comment by shahmishal** [comment]
@swift-ci clean test

**Comment by shahmishal** [comment]
cc: @compnerd @bnbarham @eeckstein

**Comment by shahmishal** [comment]
Do not merge this pull request, I will merge it when we are ready.

**Pull request merged**
