### PR TITLE
[LibSyntax] Add leading and trailing spacing for `SpacedBinaryOperator`

### PR DESCRIPTION
**Pull request by kimdv**
Swift Syntax PR: https://github.com/apple/swift-syntax/pull/333

### CODE REVIEW

**Review by ahoppen — APPROVED** [review]

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/333

@swift-ci Please smoke test

**Comment by ahoppen** [comment]
apple/swift-syntax#333

@swift-ci Please smoke test

**Comment by kimdv** [comment]
@ahoppen I don't need to rebase here?

**Comment by ahoppen** [comment]
I just triggered CI out of habit. 

You don’t need to rebase this PR because nothing has changed `Token.py` recently but I think https://github.com/apple/swift-syntax/pull/333 needs to be rebased.

**Comment by ahoppen** [comment]
Edit: I think apple/swift-syntax#333 also shouldn’t need a rebase because it’s touching different files than https://github.com/apple/swift-syntax/pull/332. But rebasing never hurts.

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/333

@swift-ci Please smoke test

**Pull request merged**
