### PR TITLE
[Build] Use magic linker symbols to specify an @rpath-relative install name when targeting pre-stable-ABI OSes.

### PR DESCRIPTION
**Pull request by mikeash**
Magic symbols of the form `$ld$install_name$os9.0$@rpath/libswiftCore.dylib` tell the linker to use that install name when targeting that OS version. Use these symbols to specify an `@rpath` install name for all back-deployment libraries when targeting watchOS 2.0-5.1, iOS 7.0-12.1, and macOS 10.9-10.14.

### CODE REVIEW

**Comment by mikeash** [comment]
@swift-ci please test

**Review by gottesmm — APPROVED** [review]
LGTM. Thanks!

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test and merge

**Comment by mikeash** [comment]
@swift-ci please test and merge

**Comment by mikeash** [comment]
@swift-ci please test and merge

**Comment by shahmishal** [comment]
@swift-ci please test and merge

**Comment by mikeash** [comment]
@swift-ci please test and merge

**Comment by mikeash** [comment]
@swift-ci please test and merge

**Comment by mikeash** [comment]
@swift-ci please test osx platform

**Comment by mikeash** [comment]
@swift-ci Please smoke test OS X platform

**Pull request merged**
