### PR TITLE
[stdlib] _StringObject: Use a full 8-bit discriminator on 32-bit platforms

### PR DESCRIPTION
**Pull request by lorentey**
#20561 gave us plenty of extra inhabitants in the variant enum, so we can get rid of the 7-bit hack.

It’d also be possible now to increase small string capacity to a spacious 11 bytes; however this needs a full overhaul of the 32-bit String representation, so it needs a little bit more time in the oven.

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci please test

**Comment by lorentey** [comment]
@swift-ci please smoke test

**Review by milseman — APPROVED** [review]
Awesome, LGTM!

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test

**Pull request merged**
