### PR TITLE
[stdlib] Change Slice, Substring, CollectionOfOne and ReversedCollection to use _read/_modify

### PR DESCRIPTION
**Pull request by lorentey**
This adds `Substring` to #20893, hopefully improving benchmarks.

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci benchmark

**Comment by lorentey** [comment]
@swift-ci smoke test

**Comment by lorentey** [comment]
cc @airspeedswift

**Comment by lorentey** [comment]
D'oh, it actually made them worse.

**Comment by CodaFi** [comment]
Hm, let's try again shall we?

@swift-ci please benchmark

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Comment by lorentey** [comment]
Closing.

**Pull request closed without merging**
