### PR TITLE
[Python] Update list of Python files without .py suffix in .pep8 file

### PR DESCRIPTION
**Pull request by practicalswift**
Changes:
- Add `ld` (`test/Driver/Inputs/filelists/ld`)
- Remove `pre-commit-benchmark` (deleted)

### CODE REVIEW

**Comment by jrose-apple** [comment]
:-/ It seems wrong to have to update this every time we need a new helper tool for tests. Is there a way to get it to detect files from their #! line? Maybe "files in test/** and utils/** with no extension with a first line matching `#!.+python`"?

**Comment by practicalswift** [comment]
@jrose-apple Yes, I agree that is problematic.

Unfortunately the `.pep8` format is quite limited so I'm afraid the `filename` directive is the only inclusion mechanism available.

The way I'm finding Python files without `.py` suffix is almost exactly what you suggested :-)  This is what I'm using in my local "check-Swift-repo-consistency"-routine:

```
$ git grep '#!.*python' | cut -f1 -d: | sort | egrep -v '.py$' | sed 's%^.*/%%g' | sort
docs/scripts/ns-html2rst
test/Driver/Inputs/filelists/ld
utils/build-script
utils/gyb
utils/line-directive
utils/recursive-lipo
utils/submit-benchmark-results
utils/update-checkout
utils/viewcfg
```

Turns out `test/Driver/Inputs/filelists/ld` is the only Python file under `test/` that is missing a `.py` extension.

Possible solutions:
* Should we simply skip linting Python files without `.py` suffix under `test/`?
* If not, should we standardize on having a `.py` suffix for all Python files under `test/`?

**Comment by jrose-apple** [comment]
Well, the reason `ld` doesn't is because it's acting like the real `ld`, but I suppose we could change the test so that it symlinks it into a temporary directory (`ln -s %S/Inputs/filelists/ld.py %t/ld`) rather than just pointing at the existing one.

**Comment by practicalswift** [comment]
@jrose-apple Yes, `ld` is a special case. The symlink solution sounds smart. Please let me know if you want me to make any changes to this PR to make it merge:able :-)

**Comment by jrose-apple** [comment]
Okay, I moved `ld` to `fake-ld.py` in 839dfc0. Everything else seems reasonable.

**Comment by practicalswift** [comment]
@jrose-apple PR updated accordingly. Let me know if any further changes are needed :-)

**Comment by jrose-apple** [comment]
Ah, now there are conflicts because of your other change. Can you rebase and try again?

**Comment by practicalswift** [comment]
@jrose-apple Rebased :-)

**Comment by jrose-apple** [comment]
I hate to keep bugging you but you snuck the "E114" change into this commit. Was that intentional?

**Comment by practicalswift** [comment]
@jrose-apple Good you noticed that :-) That change belongs in #1292, so removed it from this PR. Also added the remaining missing files. Let me know if any changes are needed :-)

**Comment by practicalswift** [comment]
Rebased again :-)

**Comment by jrose-apple** [comment]
…are the `.in` files valid Python? Valid enough to check with pep8? I mean, it's too bad that we wouldn't get any checking otherwise, but…

**Comment by practicalswift** [comment]
@jrose-apple Yes, they are all passing `flake8`. They are 100 % Python with `"@PATH_TO_DRIVER_LIBRARY@"` strings as the only magic :-)

```
$ flake8 ./benchmark/scripts/Benchmark_DTrace.in ./benchmark/scripts/Benchmark_GuardMalloc.in ./benchmark/scripts/Benchmark_RuntimeLeaksRunner.in
$ head -1 ./benchmark/scripts/Benchmark_DTrace.in ./benchmark/scripts/Benchmark_GuardMalloc.in ./benchmark/scripts/Benchmark_RuntimeLeaksRunner.in
==> ./benchmark/scripts/Benchmark_DTrace.in <==
#!/usr/bin/env python

==> ./benchmark/scripts/Benchmark_GuardMalloc.in <==
#!/usr/bin/env python

==> ./benchmark/scripts/Benchmark_RuntimeLeaksRunner.in <==
#!/usr/bin/env python
$ egrep '@.*@' ./benchmark/scripts/Benchmark_DTrace.in ./benchmark/scripts/Benchmark_GuardMalloc.in ./benchmark/scripts/Benchmark_RuntimeLeaksRunner.in
./benchmark/scripts/Benchmark_DTrace.in:DRIVER_LIBRARY_PATH = "@PATH_TO_DRIVER_LIBRARY@"
./benchmark/scripts/Benchmark_GuardMalloc.in:sys.path.append("@PATH_TO_DRIVER_LIBRARY@")
./benchmark/scripts/Benchmark_RuntimeLeaksRunner.in:sys.path.append("@PATH_TO_DRIVER_LIBRARY@")
```

**Comment by shahmishal** [comment]
@swift-ci Please test

**Comment by practicalswift** [comment]
@shahmishal Build seems to have passed :+1: Let me know if any further changes are needed :-)

**Comment by jrose-apple** [comment]
Thanks for sticking this one out. :-)

**Pull request merged**
