### PR TITLE
Basic: Remove VariadicGenerics feature [5.9]

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Review by hborla — APPROVED** [review]

**Comment by slavapestov** [comment]
https://github.com/apple/llvm-project/pull/6949
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Pull request merged**
