### PR TITLE
[SE-0316] Introduce the GlobalActor protocol to describe global actors.

### PR DESCRIPTION
**Pull request by DougGregor**
**Explanation**:  Based on the discussion of [SE-0316](https://github.com/apple/swift-evolution/blob/main/proposals/0316-global-actors.md),  introduce a `GlobalActor` protocol that describes types that can be global actors.
**Scope**: Affects the definition of global actors. The only one that currently exists is `MainActor`.
**Radar/SR Issue**: rdar://79339591
**Risk**: Very low.
**Testing**: PR testing and CI on main.
**Original PR**: https://github.com/apple/swift/pull/37917
**Reviewed by**: John McCall

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please nominate

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test Linux

**Review by airspeedswift — APPROVED** [review]

**Pull request merged**
