### PR TITLE
build: remove some left over variables

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by buttaface** [comment]
These were removed later in #29665.

**Comment by compnerd** [comment]
Thanks @buttaface!

**Pull request closed without merging**
