### PR TITLE
Fix QuartzCore test to pass the necessary number of components to `CGColor(colorSpace:components:)`.

### PR DESCRIPTION
**Pull request by jckarter**

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please ASAN test

**Comment by jckarter** [comment]
@swift-ci Please smoke test Linux

**Comment by jckarter** [comment]
@atrick Does this look OK for inclusion in 3.0?

**Review by atrick — APPROVED** [review]
LGTM for Swift #!

**Comment by jckarter** [comment]
Looks like at least the affected test passes the ASAN bot now.

https://ci.swift.org/job/swift-PR-osx-ASAN-test/38/console
```
PASS: Swift(macosx-x86_64) :: stdlib/QuartzCore.swift (3335 of 8701)
```

**Comment by jckarter** [comment]
@swift-ci Please smoke test OS X

**Pull request merged**
