### PR TITLE
Use stack allocation for Swift closures

### PR DESCRIPTION
**Pull request by aschwaighofer**
Adds an ``on_stack`` version of ``partial_apply``
It does not take ownership of its non-trivial arguments, is a trivial
function type and therefore must not be destroyed. The compiler must
make sure to extend the lifetime of non-trivial arguments beyond the
last use of the closure.

Closure lifetime fixup will use ``partial_apply [on_stack]``  as appropriate.

```
  %objc = copy_value %0 : $AnObject
  %closure = partial_apply [stack] [callee_guaranteed] %16(%obj) : $@convention(thin) (@guaranteed AnObject) -> ()
  %closure2 = mark_dependence %closure : $@NoEscape @callee_guaranteed () -> () on %obj : $AnObject
  %user = function_ref @useClosure : $@convention(thin) (@NoEscape @callee_guaranteed () -> ()) -> ()
  apply %user(%closure2) : $@convention(thin) (@NoEscape @callee_guaranteed () -> ()) -> ()
  dealloc_stack %closure : $() ->()
  destroy_value %obj : $AnObject // noescape closure does not take ownership
```

SR-904
rdar://35590578

### CODE REVIEW

**Comment by eeckstein** [comment]
nice!

**Comment by gottesmm** [comment]
+1!

**Comment by milseman** [comment]
😍 Thank you!

Are there any guidelines or guarantees as to when this will and will not kick in that we can rely on? I'd like to add a section to [stdlib programmer's manual](https://github.com/apple/swift/blob/master/docs/StandardLibraryProgrammersManual.md).

**Comment by aschwaighofer** [comment]
@milseman While it is a best effort as this matches patterns I expect any closure directly passed to a swift closure parameter to be allocated on the stack.

```
useClosure(otherArg, { ... })
```

Objective-C block arguments remain allocated on the heap for now.

**Comment by jrose-apple** [comment]
I suspect that's limited to non-escaping closures, yeah?

**Comment by aschwaighofer** [comment]
@jrose-apple Yes

**Comment by milseman** [comment]
What would be an example of a pattern match failure? Is there any way we can write tests to enforce this better? We pretty much *have* to make all closure-taking functions inlinable currently, and this could help with that. But, the only source-level test I see here calls an `@inlinable` initializer, which sorta defeats the potential benefit of this change.

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test source compatibility

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@milseman I am going to add a more comprehensive set of tests that verify that the closure is stack allocated in a followup PR: https://github.com/aschwaighofer/swift/compare/partial_apply_stack...aschwaighofer:partial_apply_stack_tests

**Comment by gottesmm** [comment]
@aschwaighofer Can you add documentation around triviality/ownership to SIL.rst. I was trying to reason about this today and I had no clue.

**Comment by gottesmm** [comment]
nm I found it.

**Pull request merged**
