### PR TITLE
[overlay] Make the UIKit shim function properly available

### PR DESCRIPTION
**Pull request by moiseev**
<rdar://problem/33789760>

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please test macOS

**Comment by moiseev** [comment]
@swift-ci Please smoke test Linux

**Comment by jrose-apple** [comment]
Ah, I think you can stick the attribute before the declaration as well, but if this doesn't cause warnings itself then okay.

**Comment by moiseev** [comment]
@jrose-apple no extra warnings have been found in the build log.

**Pull request merged**
