### PR TITLE
Add missing `else` to guard statements in code listing

### PR DESCRIPTION
**Pull request by amartini51**
Fixes rdar://84895831

Cherry-pick of https://github.com/apple/swift/pull/40019

### CODE REVIEW

**Comment by amartini51** [comment]
@swift-ci Please smoke test.

**Review by ktoso — APPROVED** [review]
Thanks!

**Comment by amartini51** [comment]
@swift-ci Please test Windows.

**Comment by amartini51** [comment]
@swift-ci Please test.

**Comment by amartini51** [comment]
@swift-ci Please test macOS platform.

**Pull request merged**
