### PR TITLE
[OpaqueValues] Two tweaks to enable std::vector<uint32_t> iteration.

### PR DESCRIPTION
**Pull request by nate-chandler**
Enabled by two small changes in opaque values mode:

- When creating a foreign-to-native thunk, create a temporary when the foreign convention is indirect-non-inout only when using lowered addresses.
- When transforming, load address even when their type is address-only.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by atrick — APPROVED** [review]
LGTM

**Comment by nate-chandler** [comment]
@swift-ci please test windows platform

**Comment by nate-chandler** [comment]
@swift-ci please test windows platform

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test linux platform

**Comment by nate-chandler** [comment]
@swift-ci please test windows platform

**Comment by nate-chandler** [comment]
@swift-ci please test windows platform

**Comment by nate-chandler** [comment]
@swift-ci please test and merge

**Comment by nate-chandler** [comment]
@swift-ci please test windows platform

**Comment by nate-chandler** [comment]
@swift-ci please test windows platform

**Pull request merged**
