### PR TITLE
benchmark: NIOChannelPipeline imitation

### PR DESCRIPTION
**Pull request by weissi**
adds a benchmark that imitates SwiftNIO's ChannelPipeline. Recently,
Swift master regressed on this benchmark, therefore I believe adding it
to Swift provides value as it seems to be different enough to the existing
benchmarks.

### CODE REVIEW

**Comment by weissi** [comment]
@swift-ci bench

**Comment by weissi** [comment]
@swift-ci test bench

**Comment by CodaFi** [comment]
@swift-ci please benchmark

**Comment by weissi** [comment]
@swift-ci please benchmark

**Comment by weissi** [comment]
ok, now I actually compiled that locally :P

**Comment by weissi** [comment]
@swift-ci please benchmark

**Comment by weissi** [comment]
@swift-ci please benchmark

**Comment by CodaFi** [comment]
@swift-ci please benchmark

**Comment by weissi** [comment]
@swift-ci please benchmark

**Review by gottesmm — APPROVED** [review]
LGTM

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Pull request merged**
