### PR TITLE
[IRGen] Fetch the correct IGM for synthesized files

### PR DESCRIPTION
**Pull request by drexin**
rdar://128870792

Synthesized files are treated as not having a parent source file, but that can cause issues for macro code. The declarations will have the source file of their use site declared as parent source file, which means they should be emitted into the same IGM. If we don't use the correct IGM, we can get inconsistencies when referencing the generated code, which will cause linking issues.

### CODE REVIEW

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@swift-ci smoke test

**Review by aschwaighofer — APPROVED** [review]
lgtm, thanks!

**Comment by drexin** [comment]
@swift-ci smoke test

**Pull request merged**
