### PR TITLE
Improve usability of `build-toolchain` script.

### PR DESCRIPTION
**Pull request by ghost**
This script improves several things:

* Previously it was incredilby easy to accidently mis-use the script. For
  example running `build-toolchain -n` would set `BUNDLE_PREFIX` to `-n`.
  The new implementation of command line argument parsing is less fragile
  and easier to extend.

* Provides `--help` (or `-h`) output.

* Prints the value of several environment variables before running
  `build-script`.

* Shows the invocation of `build-script`.

The accepted order of command line arguments has not changed to avoid
breaking existing users of the script.

### CODE REVIEW

**Comment by jrose-apple** [comment]
cc @johnno1962

**Comment by jrose-apple** [comment]
Seems reasonable to me, but let's see what Mishal or JohnH think.

@swift-ci Please smoke test

**Review by shahmishal — APPROVED** [review]
LGTM

**Comment by jrose-apple** [comment]
Cool. Thanks, Dan!

**Comment by johnno1962** [comment]
LGTM. If there was a way to run the script to build the compiler/sourcekit but not rebuild all the various architecture stdlibs and overlays even better! I’ve looked into this but couldn’t make any headway.

**Comment by danliew-apple** [comment]
@johnno1962 Unfortunately I don't know enough about `build-script` to know how to do that. It seems that `build-script` is designed so that if you use a "preset" that you can't pass additional options (but you can pass substitutions like `install_destdir=/some/path`).

So if you what you want is possible we'd need a different preset for this. Adding a new preset is a bit out of scope for what this PR is trying achieve.

**Pull request merged**
