### PR TITLE
[gardening] Remove three unused diagnostics.

### PR DESCRIPTION
**Pull request by practicalswift**
Remove three unused diagnostics.

Last usage removed in eb3ba78d9411616e30cb9ec92b3881456d1f3059 by @DougGregor

### CODE REVIEW

**Comment by slavapestov** [comment]
Nice!

**Comment by practicalswift** [comment]
Is there a plan for getting the buildbots reliable and speedy?

I just realised that my brain interprets reported buildbot failures as a result of some hidden pseudorandom process rather than a sign that the PR is breaking the build :-)

In other words, my experience is that the following holds:

`P(buildbot problem | build failure) > P(actual issue in the code | build failure)`

That is troubling :-)

**Comment by practicalswift** [comment]
Buildbots sleeping? :-)  24 h have passed and none of the builds have completed.

**Comment by gribozavr** [comment]
@swift-ci Please smoke test

**Comment by lattner** [comment]
Thanks!

**Comment by practicalswift** [comment]
Thanks for merging! 

Regarding my buildbot comment - seems like I misunderstood things. I incorrectly assumed that the status "Some checks haven’t completed yet" which is reported just after creating a PR meant that the buildbots are auto-triggered upon PR creation.

Turns out that the swift-ci command is still needed. Buildbots, sorry for claiming that you are slow! :-)

**Comment by practicalswift** [comment]
To follow up regarding the build bots. Having interacted with the build bots quite heavily during the last couple of days it seems like the reliability has increased significantly compared to say a few weeks back. So forget my whining - it was based on old information. Sorry about that :-)

**Pull request merged**
