### PR TITLE
[5.0] Increase the stack size limit for running llvm codegen threads …

### PR DESCRIPTION
**Pull request by aschwaighofer**
…to 8MB

Without this compilation may fail in llvm because we run out of stack space. The
limit for the main thread is 8MB on mac osx but 512KB for other threads.

rdar://47787344
rdar://49586719

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by tkremenek** [comment]
@swift-ci clean smoke test

**Comment by atrick** [comment]
@najacque  @shahmishal OSX testing fails because of a cmake error
build-script: error: unrecognized arguments: --cmake-c-launcher --cmake-cxx-launcher /usr/local/bin/sccache

**Comment by atrick** [comment]
@swift-ci smoke test OSX platform

**Comment by atrick** [comment]
@swift-ci clean smoke test

**Comment by shahmishal** [comment]
@swift-ci test macOS

**Review by najacque — APPROVED** [review]

**Pull request merged**
