### PR TITLE
Fix property wrapper init diagnostics

### PR DESCRIPTION
**Pull request by slavapestov**
This is a regression between 5.2 and master. The first commit is the actual bug fix; the other three are small cleanups I noticed.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@compnerd Looks like the builder is out of disk space:

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\xmemory(243): fatal error C1088: Cannot flush compiler intermediate file: 'C:\Users\ci\AppData\Local\Temp\_CL_3db5008bex': No space left on device
```

**Review by CodaFi — APPROVED** [review]
LGTM

**Comment by compnerd** [comment]
@slavapestov fixed up - seems that another host had filled up the entire disk with the clang module cache

**Pull request merged**
