### PR TITLE
[stdlib] update the fatal error message displayed during invalid integer conversions

### PR DESCRIPTION
**Pull request by ravikandhadai**
(<rdar://39542040>)

### CODE REVIEW

**Comment by ravikandhadai** [comment]
@moiseev  As I had discussed, I have  removed "signed" qualifier from the error message printed during integer conversions. Let me know if the new error message sounds okay or if you would prefer to change it. Now if you do, 
> let x: UInt = 128
> Int8(x) 
Fatal error: Not enough bits to represent the passed value:

We used to get "Fatal error: Not enough bits to represent a  signed value:"

**Review by moiseev — COMMENTED** [review]
:shipit:

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by xedin** [comment]
@swift-ci please smoke test

**Review by xedin — COMMENTED** [review]
Nice!

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
It's not triggering for some reason...

**Comment by ravikandhadai** [comment]
Yes it happens if there is a force push to the branch.

**Comment by ravikandhadai** [comment]
@swift-ci please smoke test

**Comment by shahmishal** [comment]
@swift-ci please smoke test

**Comment by shahmishal** [comment]
@swift-ci smoke test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by ravikandhadai** [comment]
Seems like all checks have passed. Good to be merged?

**Comment by ravikandhadai** [comment]
Thanks @airspeedswift !

**Pull request merged**
