### PR TITLE
Fix OSSA RAUW utility's insertion point

### PR DESCRIPTION
**Pull request by meg-gupta**
This change ensures OSSA RAUW consistently inserts borrows before the old value. Before this it inserted new borrows before the old value only when it was in the same block as new value. 
Since we can expect the users of OSSA RAUW have made sure that newValue will dominate oldValue, update the utility to always insert before the old value.

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Review by nate-chandler — APPROVED** [review]

**Comment by atrick** [comment]
It seems difficult to use the RAUW utility correctly in this respect. It's not obvious from reading the code why you need another builder. Is there any reason for prepareReplacement to be inserting fixup code for the incoming value *after* the old value instead of before the old value? I would either expect prepareReplacement to insert before the old value or to use the same insertion point as SILCombine. If they both use the same insertion point, then the instructions should be inserted in the correct order.

**Comment by meg-gupta** [comment]
@atrick Right, thank you! There isn't any reason for `prepareReplacement` to be inserting after the `oldValue`. I updated the api and now all uses of OSSA RAUW api can consistently expect the new instructions to be inserted before `oldValue`.

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Review by atrick — APPROVED** [review]
Hopefully this approach works well in other cases too.

**Pull request merged**
