### PR TITLE
Fixup omitting frame pointers on various compilers and architectures

### PR DESCRIPTION
**Pull request by hughbe**
Commit 1:
- Add `momit-leaf-frame-pointer` on i686 architectures
- There is a comment "Add -momit-leaf-frame-pointer on x86.", so we should do this on x86

Commit 2:
- Add `/Oy` with MSVC/Clang-cl to omit frame pointers
- https://msdn.microsoft.com/en-us/library/2kxx5t2c.aspx

Commit 3:
- There is a comment "Add -momit-leaf-frame-pointer on x86.", so we should do this on x86_64

### CODE REVIEW

**Comment by hughbe** [comment]
@swift-ci please clean smoke test

**Comment by hughbe** [comment]
@compnerd PTAL. The second commit I know is correct.
However, the 1st and 3rd commits rely on the comment that we omit frame pointers on x86. It currently seems like this is not the case.
So, either this is the correct fix, or we need to update the comment to say "on x86 and x86_64"

**Comment by hughbe** [comment]
@swift-ci please clean smoke test

**Comment by hughbe** [comment]
@swift-ci please clean smoke test

**Comment by hughbe** [comment]
@swift-ci please clean smoke test

**Comment by hughbe** [comment]
@swift-ci please clean smoke test

**Comment by compnerd** [comment]
The change is correct, but please collapse the patches into a single one before pushing this.

**Comment by hughbe** [comment]
Squash and merge it is

**Pull request merged**
