### PR TITLE
Revert recent foundation commits that cause source compatibility failure

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@phausler I have to revert these commits because they seem to fail several compatibility tests. https://ci.swift.org/job/swift-master-source-compat-suite/748/

**Comment by phausler** [comment]
please do not merge this...

**Comment by phausler** [comment]
The failure is not in Data, but in Sequence and RangeReplaceableCollection. 

cc @airspeedswift

**Comment by nkcsgexi** [comment]
@swift-ci Please Test Source Compatibility

**Comment by nkcsgexi** [comment]
These are the only commits from where the bot starts to fail. Let's test source compatibility here to see if the reverting fixes the tests.

**Comment by parkera** [comment]
We're still working on this.

**Comment by phausler** [comment]
#10803 is the preferred method to fix this, plus I added a unit test to verify the expected behavior for that incompatibility

**Comment by nkcsgexi** [comment]
@phausler it will be great to test source compatibility in PR before merging. Thank you!

**Pull request closed without merging**
