### PR TITLE
build-script-impl: For cmake configuration use distcc

### PR DESCRIPTION
**Pull request by erg**

### CODE REVIEW

**Comment by erg** [comment]
@swift-ci Please smoke test

**Comment by erg** [comment]
@swift-ci Please smoke test

**Review by HuskyAlvarez — APPROVED** [review]

**Comment by erg** [comment]
@swift-ci Please smoke test

**Review by dabrahams — COMMENTED** [review]
This doesn't make sense.  I don't understand why we would ever want to use distcc for a pure configuration step.

**Comment by erg** [comment]
If the assumption is that the ``cmake`` configure step distributes to other machines if the C compiler path is something like ``-DCMAKE_C_COMPILER:PATH=/opt/distcc-r796/bin/distcc``, then configuring through distcc but restricting the machines to localhost should stop ``clang`` from distributing.

If that's not what's happening, then I still don't know what to do.

**Comment by dabrahams** [comment]
I guess I don't know enough to make a judgement here.  If you test it and everything works as it should with and without distcc, I can't argue.

**Comment by shahmishal** [comment]
@erg what is the status of this PR?

**Comment by jrose-apple** [comment]
@erg isn't working on Swift anymore, so we can probably close it. (He can always reopen if he picks it up again.)

**Comment by shahmishal** [comment]
@jrose-apple Sounds good!

**Pull request closed without merging**
