### PR TITLE
Provide alternative implementations of builtin functions if they are not available in the runtime

### PR DESCRIPTION
**Pull request by hughbe**

### CODE REVIEW

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Review by shahzadlone — APPROVED** [review]

**Comment by CodaFi** [comment]
It's been two years and these builtins have since moved. Please provide an updated pull request either by rebasing this one and reopening it or by moving these functions to the right header.  Please also tag either me or @stephentyrone and we'll try our best to get this reviewed.

**Pull request closed without merging**
