### PR TITLE
[OSSACanonicalizeOwned] Record traversed defs and don't traverse copies of guaranteed values.

### PR DESCRIPTION
**Pull request by nate-chandler**
The utility performs two def-use traversals.  The first determines liveness from uses.  The second rewrites copies.

Previously, the defs whose uses are analyzed were discovered twice, once during each traversal.  The non-triviality of the discovery logic (i.e. the logic determining when to walk into the values produced by the instructions which were the users of visited uses) opened the possibility for a divergence between the two discoveries.  This possibility had indeed been realized--the two discoveries didn't find exactly the same defs, the two traversals didn't visit exactly the same uses, and issues ensued.

Here, the defs whose uses are analyzed are discovered only once during the first traversal.  The second "traversal" now reuses the defs discovered in the first traversal, eliminating the possibility of a def discovery difference.

Extra care is taken to preserve the traversal order of the first traversal (as compared to the order before this change).  Evidently diagnostics depend on it.  The second traversal's order is changed, which results in slight SIL perturbations in certain cases (e.g. an instruction which consumes a value and its copy may see the order of those operands reversed).

Because discovery of defs walks into reborrows and borrowed-from instructions, copies are processed whose underlying value is a reborrow or borrowed-from.  Such copies cannot generally be sunk to consuming uses because the lifetime of their underlying value (the reborrow or borrowed-from) may not extend to the consuming use.   Eliminating such copies is outside the scope of OSSACanonicalizeOwned--it's the responsibility of a separate OSSACanonicalizeGuaranteed utility.  For this reason, when visiting copies during the first traversal, the copies are only walked into (and added to the list of defs) if their operand is not a reborrow or borrowed-from.

rdar://139842132

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Comment by nate-chandler** [comment]
@swift-ci please clean test linux platform

**Review by atrick — APPROVED** [review]
👍

**Comment by nate-chandler** [comment]
@swift-ci please test linux platform

**Comment by nate-chandler** [comment]
@swift-ci please test macos platform

**Pull request merged**
