### PR TITLE
Fix SR-3137

### PR DESCRIPTION
**Pull request by slavapestov**
Add some regression tests, and fix a crash in typo correction: https://bugs.swift.org/browse/SR-3137

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
Nitpick: can you use more descriptive for your pull requests, and actually describe the issue a little, even if it's just copying from the commit message? The Notifications page doesn't give us anything but the title, which makes it hard to see what's worth clicking into.

**Comment by slavapestov** [comment]
@jrose-apple Sure, but I can't promise that _anything_ I push is worth clicking into :)

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Comment by slavapestov** [comment]
@jrose-apple Looks like PR testing is hitting this too, is there a fix coming soon?

```
Test Result (10 failures / ±0)
Swift(macosx-x86_64).DebugInfo.variables-repl.swift
Swift(macosx-x86_64).Interpreter.repl.swift
Swift(macosx-x86_64).Interpreter.repl_13695499.swift
Swift(macosx-x86_64).Interpreter.repl_17597453.swift
Swift(macosx-x86_64).Interpreter.repl_autolinking.swift
Swift(macosx-x86_64).Interpreter.repl_conformance_lookup.swift
Swift(macosx-x86_64).Interpreter.repl_diagnostics.swift
Swift(macosx-x86_64).Interpreter.repl_hashbang.swift
Swift(macosx-x86_64).Interpreter/SDK.Cocoa_repl.swift
Swift(macosx-x86_64).Interpreter/SDK.missing_imports_repl.swift
```

**Comment by jrose-apple** [comment]
We think it goes away when the workspace is cleaned. @mxswd @shahmishal

**Comment by slavapestov** [comment]
@swift-ci Please clean smoke test macOS

**Comment by slavapestov** [comment]
@jrose-apple Nope that didn't help

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Comment by slavapestov** [comment]
This is now part of #6484.

**Pull request closed without merging**
