### PR TITLE
[CodeCompletion] Introduce 'NotApplicable' and 'Unknown' type relation

### PR DESCRIPTION
**Pull request by rintaro**
Now, kinds of type relations are:

* `NotApplicable`: The result is not relevant for type relation (e.g. keywords, and overloads)
* `Unknown`: The relation was not calculated (e.g. cached results), or the context type is unknown
* `Invalid`: The result type is invalid for this context (i.e. 'Void' for non-'Void' context)
* `Unrelated`: The result type has no relation to the context type
* `Convertible`: The result type is convertible to the context type
* `Identical`: The result type is identical to the context type

rdar://problem/59201827

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Review by benlangmuir — APPROVED** [review]
There is a switch for printing the result (e.g. to add "/TypeRelation[Invalid]"), used by swift-ide-test .  We should at least add a default case if we don't want to actually print anything new.

**Comment by rintaro** [comment]
Added 2 commits.
- Handle new kinds in type relation printing.
- Fixed a bug where cached results weren't `Unknown`.

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Review by benlangmuir — APPROVED** [review]

**Pull request merged**
