### PR TITLE
[AutoDiff] Rename `AutoDiffFunction` to `DifferentiableFunction`.

### PR DESCRIPTION
**Pull request by dan-zheng**
Rename:
- `AutoDiffFunctionExpr` -> `DifferentiableFunctionExpr`
- `AutoDiffFunctionExtractOriginalExpr` -> `DifferentiableFunctionExtractOriginalExpr`
- `AutoDiffFunctionInst` -> `DifferentiableFunctionInst`
- `AutoDiffFunctionExtractInst` -> `DifferentiableFunctionExtractInst`
- `AutoDiffFunctionExtractee` -> `DifferentiableFunctionExtractee`

"Differentiable function" is a clearer name because these expressions and
instructions involve constructing/extracting from differentiable functions.
"AutoDiff" (automatic differentiation) is an internal detail.

Update docs, comments, and tests.

### CODE REVIEW

**Comment by dan-zheng** [comment]
Verified `grep` results:
```console
$ grep -nri AutoDiffFunction include lib docs test
# No remaining usages.

$ grep -nri autodiff_function include lib docs test
# No relevant remaining usages.
# Differentiation transform SIL diagnostics still start with "autodiff",
# e.g. `diag::autodiff_function_not_differentiable_error`.

$ grep -nri adfi include lib
# No relevant remaining usages; renamed to `dfi`.

$ grep -nri adfei include lib
# No relevant remaining usages; renamed to `dfei`.
```

**Comment by rxwei** [comment]
I'll add: The name is also motivated by the fact that we'll add a `linear_function` instruction. These two name will get along very well.

**Review by rxwei — APPROVED** [review]

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow macOS

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow macOS

**Comment by dan-zheng** [comment]
macOS CI seems down, I've just restarted the CI machine.
Passing Ubuntu CI should be sufficient for merging.

**Pull request merged**
