### PR TITLE
[sourcekit] Retain semantic annotations across queries

### PR DESCRIPTION
**Pull request by benlangmuir**
Do not remove semantic annotations, so that if a client sends multiple
magic `replacetext 0, 0, ""` requests they will all return the same
result. This makes sourcekitd more robust around providing semantic
highlighting if the editor may make multiple queries for document
update.

rdar://64904029

### CODE REVIEW

**Comment by benlangmuir** [comment]
@swift-ci please test

**Review by akyrtzi — APPROVED** [review]

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please test Windows

**Comment by benlangmuir** [comment]
@swift-ci please test Windows

**Pull request merged**
