### PR TITLE
[ConstraintSystem] remove TupleType::isSingleUnlabeledPackExpansion in favor of constraints::getPatternTypeOfSingleUnlabeledPackExpansionTuple

### PR DESCRIPTION
**Pull request by sophiapoirier**

### CODE REVIEW

**Comment by sophiapoirier** [comment]
@swift-ci please test

**Review by xedin — CHANGES_REQUESTED** [review]

**Comment by sophiapoirier** [comment]
@swift-ci please test

**Review by xedin — APPROVED** [review]
Thank you!

**Comment by sophiapoirier** [comment]
@swift-ci please test Windows

**Comment by sophiapoirier** [comment]
@swift-ci please test Windows

**Pull request merged**
