### PR TITLE
Field offset global linkage

### PR DESCRIPTION
**Pull request by slavapestov**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by huonw** [comment]
There's a hack in TBDGen that might be able to be removed after this patch? (And also fix rdar://problem/32252689 )

**Comment by slavapestov** [comment]
I've decided to make field offsets private for resilient types, but they're still public for non-resilient types. I'm closing this.

**Pull request closed without merging**
