### PR TITLE
Integrate python-lint into validation tests

### PR DESCRIPTION
**Pull request by hughbe**
@gottesmm suggested this. I finally got round to it!

I expect the tests to fail due to python linting failures. I want to make sure that I've correctly setup this so that I get a big red X in the CI.

I'll fix the python-lint violations after that

### CODE REVIEW

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by hughbe** [comment]
Looks like the Linux CI doesn't have flake8 so python-lint tests never run. @shahmishal is it possible to install flake8 on the Linux CI machines for parity with OSX?

However, OSX does correctly identify linting errors:
```
Script:
--
/usr/bin/python /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/swift/utils/python-lint
--
Exit Code: 1

Command Output (stdout):
--
./utils/swift_build_support/tests/test_workspace.py:53:80: E501 line too long (83 > 79 characters)
./utils/swift_build_support/tests/test_workspace.py:142:80: E501 line too long (85 > 79 characters)

--
```

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by hughbe** [comment]
@practicalswift FYI - sorry you'll never get to garden python-lints again ;)

**Comment by practicalswift** [comment]
@hughbe That sounds excellent! Let's raise the gardening bar :-)

**Comment by shahmishal** [comment]
```
FAIL: Swift(macosx-x86_64) :: Python/python-lint.swift (6263 of 9568)
******************** TEST 'Swift(macosx-x86_64) :: Python/python-lint.swift' FAILED ********************
Script:
--
/usr/bin/python /Users/buildnode/jenkins/workspace/oss-swift-incremental-ASAN-RA-osx/swift/utils/python-lint
--
Exit Code: 1

Command Output (stdout):
--
./utils/build-script:22:28: E261 at least two spaces before inline comment
./utils/round-trip-syntax-test:14:1: E302 expected 2 blank lines, found 1
./utils/round-trip-syntax-test:15:80: E501 line too long (83 > 79 characters)
./utils/round-trip-syntax-test:19:80: E501 line too long (104 > 79 characters)
./utils/round-trip-syntax-test:20:80: E501 line too long (104 > 79 characters)
./utils/round-trip-syntax-test:43:17: E128 continuation line under-indented for visual indent
./utils/round-trip-syntax-test:58:17: E128 continuation line under-indented for visual indent
./utils/round-trip-syntax-test:73:80: E501 line too long (151 > 79 characters)
./utils/round-trip-syntax-test:77:80: E501 line too long (103 > 79 characters)
./utils/round-trip-syntax-test:89:1: E302 expected 2 blank lines, found 1
./utils/round-trip-syntax-test:99:1: E302 expected 2 blank lines, found 1
./utils/round-trip-syntax-test:113:1: E302 expected 2 blank lines, found 1
./utils/round-trip-syntax-test:114:21: E225 missing whitespace around operator
./utils/round-trip-syntax-test:122:80: E501 line too long (81 > 79 characters)
./utils/round-trip-syntax-test:127:13: E128 continuation line under-indented for visual indent
./utils/round-trip-syntax-test:128:13: E128 continuation line under-indented for visual indent
./utils/round-trip-syntax-test:130:13: E128 continuation line under-indented for visual indent
./utils/round-trip-syntax-test:131:13: E128 continuation line under-indented for visual indent
./utils/round-trip-syntax-test:133:13: E128 continuation line under-indented for visual indent
./utils/round-trip-syntax-test:134:13: E128 continuation line under-indented for visual indent
./utils/round-trip-syntax-test:136:13: E128 continuation line under-indented for visual indent
./utils/round-trip-syntax-test:137:13: E128 continuation line under-indented for visual indent
./utils/round-trip-syntax-test:138:13: E128 continuation line under-indented for visual indent
./utils/round-trip-syntax-test:138:80: E501 line too long (81 > 79 characters)
./utils/round-trip-syntax-test:144:13: E128 continuation line under-indented for visual indent
./utils/round-trip-syntax-test:153:80: E501 line too long (90 > 79 characters)
./utils/round-trip-syntax-test:155:80: E501 line too long (97 > 79 characters)
./utils/round-trip-syntax-test:156:13: E128 continuation line under-indented for visual indent
./utils/round-trip-syntax-test:157:80: E501 line too long (101 > 79 characters)
./utils/round-trip-syntax-test:158:13: E128 continuation line under-indented for visual indent
./utils/round-trip-syntax-test:160:29: E231 missing whitespace after ','
./utils/round-trip-syntax-test:161:13: E128 continuation line under-indented for visual indent

--

********************
```

**Comment by shahmishal** [comment]
https://ci.swift.org/job/oss-swift-incremental-ASAN-RA-osx/236/testReport/junit/Swift(macosx-x86_64)/Python/python_lint_swift/

**Pull request merged**
