### PR TITLE
Adopt a search path for bridgeable types in component modules (no longer just in Foundation)

### PR DESCRIPTION
**Pull request by millenomi**
Required for the work in <https://github.com/apple/swift-corelibs-foundation/pull/1799>.

### CODE REVIEW

**Comment by millenomi** [comment]
@jrose-apple All this code currently runs on all OSes, including where Swift Foundation is not available. As a reminder, Swift Foundation _may_ be available and _must_ be functional on Darwin as we target that platform for test purposes only (which is why all the search paths I introduce in this patch include the `Swift`-prefixed spelling of the Foundation modules to search in).

**Comment by millenomi** [comment]
cfr. https://github.com/apple/swift-corelibs-foundation/pull/1799

**Comment by millenomi** [comment]
The Linux crash is expected without the SCF changes; the macOS pass was not. Trying to build a toolchain with this so that I can try building SCF on Darwin and reproduce the crash I'm seeing in apple/swift-corelibs-foundation#1799

**Comment by millenomi** [comment]
Please test with the following:
https://github.com/apple/swift-clang/pull/245
https://github.com/apple/swift-package-manager/pull/1914
https://github.com/apple/swift-corelibs-foundation/pull/1799

@swift-ci please test

**Comment by millenomi** [comment]
Please test with the following:
https://github.com/apple/swift-clang/pull/245
https://github.com/apple/swift-package-manager/pull/1914
https://github.com/apple/swift-corelibs-foundation/pull/1799
https://github.com/apple/swift-lldb/pull/1187

@swift-ci please test

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
