### PR TITLE
[test] Enable standalone_build feature properly and fix three tests

### PR DESCRIPTION
**Pull request by finagolfin**
@davezarzycki, if you can kick off the CI, I believe this will enable all those tests.

### CODE REVIEW

**Comment by theblixguy** [comment]
@swift-ci please test

**Review by davezarzycki — APPROVED** [review]
Thanks for catching and fixing this!

**Comment by buttaface** [comment]
Well, the fact that one `standalone_build` test now fails on macOS shows that they're running now, I'll look into why it fails.

**Comment by buttaface** [comment]
Good to test.

**Comment by buttaface** [comment]
Ready for another CI run, should pass now.

**Comment by davezarzycki** [comment]
@swift-ci please test

**Comment by buttaface** [comment]
Single linux failure is unrelated, all pulls on CI are failing because of that same test.

**Comment by davezarzycki** [comment]
@swift-ci please smoke test linux

**Comment by buttaface** [comment]
Passes CI, ready to merge.

**Comment by davezarzycki** [comment]
Thanks for fixing this :-)

**Comment by buttaface** [comment]
Thanks for answering my questions and the quick turnaround, now to get my other pull that depends on this in.

**Pull request merged**
