### PR TITLE
IRGen to copy non trivial structs with ptrauth qualified field function pointers

### PR DESCRIPTION
**Pull request by meg-gupta**

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test

**Review by aschwaighofer — APPROVED** [review]
LGTM

**Comment by meg-gupta** [comment]
@swift-ci test macOS platform

**Comment by meg-gupta** [comment]
@swift-ci test macOS platform

**Comment by meg-gupta** [comment]
@swift-ci test macOS platform

**Pull request merged**
