### PR TITLE
SILOptimizer: move DestroyHoisting out of the mandatory pipeline

### PR DESCRIPTION
**Pull request by eeckstein**
Now that we have OSSA also in the early stage of the -O pipeline, we can do DestroyHoisting there.

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Review by atrick — APPROVED** [review]
Thanks

**Comment by atrick** [comment]
ooof, we probably want to track those regressions somehow so we can use them as incentive to fix the pass pipeline

**Comment by eeckstein** [comment]
Yeah, this is a real regression. We are ending up with more retain/releases.
I will take a look before I merge.

**Comment by eeckstein** [comment]
This needs some fixes in CopyPropagation and/or PredictableMemoryAccessOptimizations until this can be merged

**Pull request closed without merging**
