### PR TITLE
Merging swift-DEVELOPMENT-SNAPSHOT-2019-05-20-a into tensorflow

### PR DESCRIPTION
**Pull request by bgogul**

### CODE REVIEW

**Comment by bgogul** [comment]
@swift-ci please test tensorflow

**Review by marcrasi — APPROVED** [review]

**Comment by bgogul** [comment]
@swift-ci please clean test tensorflow

**Comment by bgogul** [comment]
@swift-ci please clean test tensorflow

**Comment by bgogul** [comment]
Tests succeed:
 -https://ci-external.swift.org/view/Pull%20Request/job/swift-PR-TensorFlow-Linux-gpu/1501/
 - https://ci-external.swift.org/view/Pull%20Request/job/swift-PR-TensorFlow-Linux/2318/

I tested locally on my mac as well.

**Pull request merged**
