### PR TITLE
[utils] Make update-checkout output more readable

### PR DESCRIPTION
**Pull request by lorentey**
In Python 3, subprocess output is read as binary data by default, which isn’t what we want.

Instead of reading process output as byte strings, then manually decoding them into strings, simply pass `text=True` to functions in the `subprocess` module, so that we get properly decoded strings right out the box.

This fixes places that forget to do the decoding step — most especially, the `update-checkout` script. That script prints Git output as byte strings, which leads to unreadable results.

Additionally, in shell.run, use the same pipe for capturing both stdout and stderr. The distinction is pretty pointless in this use case; however, keeping the two channels separate means that we lose the original ordering of printed messages, which does matter.

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
Ah, I didn't know Python 2.7 was still a thing on the Linux bots 😬

```
  File "/usr/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
```

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
Before:
```
Updating '/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift-installer-scripts'
/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift-installer-scripts
b"Your branch is up to date with 'origin/main'.\n"b"Already on 'main'\n"
/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift-installer-scripts

/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift-installer-scripts
b'HEAD is now at cee3f49 Merge pull request #77 from apple/add-support-for-version-dir\n'
```

After:
```
Updating '/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift-installer-scripts'
Updating '/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift-installer-scripts'
/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift-installer-scripts
Already on 'main'
Your branch is up to date with 'origin/main'.

/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift-installer-scripts

/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift-installer-scripts
HEAD is now at cee3f49 Merge pull request #77 from apple/add-support-for-version-dir
```

Stdout and stderr are still garbled; I think the process pool isn't opening new pipes for each process.

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
And now it looks like this:

```
[swift-installer-scripts]               Updating '/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift-installer-scripts'
[swift-installer-scripts]               + git checkout main
[swift-installer-scripts]               Already on 'main'
[swift-installer-scripts]               Your branch is up to date with 'origin/main'.
```

Things are in order, and interleaved messages are neatly labeled with their corresponding repository name.

**Comment by shahmishal** [comment]
Thanks @lorentey!

**Comment by shahmishal** [comment]
It would be also nice if we stop printing all env variable with command line output.

**Comment by lorentey** [comment]
@shahmishal Fix at https://github.com/apple/swift/pull/41778

**Pull request merged**
