### PR TITLE
[test] Check for sftp-server for remote-run --debug-as-local tests

### PR DESCRIPTION
**Pull request by jrose-apple**
Not all systems have sftp-server installed.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Comment by davezarzycki** [comment]
Hey @jrose-apple – While I'm testing this, can you update the pull request to look for `sftp-server` here: `/usr/libexec/openssh/sftp-server`? That's where Red Hat Fedora installs it.

**Comment by jrose-apple** [comment]
Huh, Ubuntu also put it in an openssh subdirectory but with a symlink from /usr/lib/. I guess OpenSSH is common enough to be worth hardcoding.

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Review by davezarzycki — APPROVED** [review]
I've verified that 6e04cd303210a17d56f062796c88fc95bd4c5393 works. Also, ya, there is an implicit dependency on OpenSSH's version of `sftp-server` here.

**Review by shahmishal — APPROVED** [review]
LGTM!

**Pull request merged**
