### PR TITLE
Migrate llvm::make_unique to std::make_unique

### PR DESCRIPTION
**Pull request by JDevlieghere**
Now that we've moved to C++14, we no longer need the llvm::make_unique
implementation from STLExtras.h. This patch is a mechanical replacement
of (hopefully) all the llvm::make_unique instances in the swift repo.

### CODE REVIEW

**Comment by jrose-apple** [comment]
Swift needs to move to C++14 first, doesn't it?

**Comment by JDevlieghere** [comment]
As far as I can tell Swift inherit the C++ version used by LLVM.

**Comment by jrose-apple** [comment]
It seems to for Ninja builds, but not Xcode builds.

```
% git grep c++11
CMakeLists.txt:# Xcode: use libc++ and c++11 using proper build settings.
cmake/modules/SwiftXcodeSupport.cmake:  set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LANGUAGE_STANDARD "c++11"
```

(We might just be able to take that out; I have no idea. But Swift is a separate project from LLVM and a switch to C++14, while *required* to stay up to date with LLVM, should be done deliberately and communicated on the Swift forums.)

**Comment by JDevlieghere** [comment]
I'll let @jfbastien take of the communication :-)

**Comment by jfbastien** [comment]
https://forums.swift.org/t/llvm-is-now-on-c-14/27931

**Comment by JDevlieghere** [comment]
Thanks, @jfbastien!

**Comment by JDevlieghere** [comment]
PR for Xcode support: https://github.com/apple/swift/pull/26673

**Comment by benlangmuir** [comment]
Since this change touches a lot of code, I would prefer we do something more targeted until we move swift master to use the new llvm.  Otherwise we're just asking for merge conflicts between master and master-next.

If this API is removed from llvm, we can always copy it into swift for example.

**Comment by JDevlieghere** [comment]
> Since this change touches a lot of code, I would prefer we do something more targeted until we move swift master to use the new llvm. Otherwise we're just asking for merge conflicts between master and master-next.

Unless you expect this code to change a lot, I'm not sure if it makes sense to diverge. The resolution should be fairly obvious when it happens.   

> If this API is removed from llvm, we can always copy it into swift for example.

Yes, I was holding off the removal until this patch was landed. Do you mean keeping in in swift-llvm?

**Comment by benlangmuir** [comment]
> Unless you expect this code to change a lot, I'm not sure if it makes sense to diverge. The resolution should be fairly obvious when it happens.

Diverge from what?  This patch itself is diverging from swift master.

**Comment by JDevlieghere** [comment]
> > Unless you expect this code to change a lot, I'm not sure if it makes sense to diverge. The resolution should be fairly obvious when it happens.
> 
> Diverge from what?

Sorry, the order of my replies is a bit confusing. I meant diverging swift-llvm to include the helper that's gone upstream.

 > This patch itself is diverging from swift master.

Yup, but isn't that the point of `master-next`, to track upstream?

**Comment by benlangmuir** [comment]
I spent more time thinking about this, and I withdraw my objection. Sorry for the churn.

**Review by jrose-apple — APPROVED** [review]

**Pull request merged**
