### PR TITLE
[Immediate] SIL Module Lazy Compilation

### PR DESCRIPTION
**Pull request by zachary-kent**
This PR implements lazy compilation at the SIL module granularity, meaning that the main SIL module will only be IRGen'd when the entry point to the script is invoked. By adding a materialization unit for the main SIL module and lazy re-exports, this PR lays the groundwork for function at-a-time lazy compilation.

### CODE REVIEW

**Comment by zachary0kent** [comment]
@swift-ci please test

**Comment by zachary0kent** [comment]
@swift-ci please test

**Comment by lhames** [comment]
Re-running to see If the original failures at https://ci.swift.org/job/swift-PR-Linux/9352/ were transient.

@swift-ci please test

**Comment by zachary0kent** [comment]
@swift-ci please test

**Comment by zachary0kent** [comment]
@swift-ci please test

**Comment by zachary0kent** [comment]
@swift-ci please test

**Comment by zachary0kent** [comment]
@swift-ci please smoke test

**Comment by zachary0kent** [comment]
@swift-ci please smoke test

**Comment by zachary0kent** [comment]
@swift-ci please smoke test

**Comment by zachary0kent** [comment]
@swift-ci please test

**Review by lhames — APPROVED** [review]
LGTM.

Eventually we'll want to hoist `SILMaterializationUnit` into a header somewhere, but I think it's fine to bake in `lib/Immediate/Immediate.cpp` for a bit first.

**Pull request merged**
