### PR TITLE
SILGen: Fix partial application of enum case with one-element labeled tuple [5.0]

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes <rdar://problem/46748491>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test Linux

**Comment by slavapestov** [comment]
Not me:

```
/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.0-branch/swiftpm/Sources/SourceControl/RepositoryManager.swift:42:37: error: 'Result' is ambiguous for type lookup in this context
20:25:37     public typealias LookupResult = Result<RepositoryHandle, AnyError>
20:25:37                                     ^~~~~~
20:25:37 Swift.Result:1:13: note: found this candidate
20:25:37 public enum Result<Success, Failure> where Failure : Error {
20:25:37             ^
20:25:37 Basic.Result:1:13: note: found this candidate
20:25:37 public enum Result<Value, ErrorType> where ErrorType : Error {
20:25:37             ^
```

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test Linux

**Comment by slavapestov** [comment]
@swift-ci Please test Linux

**Comment by slavapestov** [comment]
Actually don't merge this yet

**Review by AnnaZaks — APPROVED** [review]

**Pull request merged**
