### PR TITLE
Adding getSwiftRevision(). 

### PR DESCRIPTION
**Pull request by ematejska**
rdar://problem/23626073

Adding getSwiftRevision().  This is to aid cleaning up some lldb code.

### CODE REVIEW

**Comment by ematejska** [comment]
@swift-ci please test

**Comment by ematejska** [comment]
@swift-ci please smoke test

**Review by jrose-apple — APPROVED** [review]

**Comment by ematejska** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
@swift-ci Please test Linux

**Pull request merged**
