### PR TITLE
Clang importer: Global vars imported as static member properties are final.

### PR DESCRIPTION
**Pull request by jckarter**

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by milseman** [comment]
I will also run the builder's validation set up on this hash

**Comment by milseman** [comment]
check-swift-all-macosx-x86_64 passes for me, and I have very high confidence.

I will continue to monitor the builder (poor little Mac mini, trying as hard as it can to keep up), but will merge to un-block other work .

**Pull request merged**
