### PR TITLE
merge swift-DEVELOPMENT-SNAPSHOT-2020-01-06-a into tensorflow

### PR DESCRIPTION
**Pull request by marcrasi**
Fixes:
* Update checkout for tensorflow-swift-apis to include https://github.com/tensorflow/swift-apis/pull/607.
* [Cherry-pick commit](https://github.com/apple/swift/commit/ad8f9d3f0daa555163dbabf2a8a628a1b693c7ae) from master that fixes a master compile error.
* `validation-test/compiler_crashers_fixed/28180-rawrepresentable-extension-with-initializer.swift` was crashing at [this cast](https://github.com/apple/swift/blob/1aa9508c212591988e6219c00d05689e012b2978/lib/Sema/TypeCheckProtocol.cpp#L3076) because our modification to `getRequirement` was returning the wrong thing. Fixed it by making it use `proto->getSingleRequirement(name);` when there is no `filter`, which is what it does on master. ([commit](https://github.com/apple/swift/commit/3f956f0ea28d39b5030f186a069ae9689cb18129))
* `test/AutoDiff/compiler_crashers_fixed/tf1017-diff-attr-invalid-original-interface-type.swift ` was failing because of missing argument label. I also fixed this in the same commit as the previous bullet point.

Remaining tests to run before this is ready to merge:
- [ ] macos toolchain tests
- [x] swift-apis tests

### CODE REVIEW

**Review by dan-zheng — APPROVED** [review]
Thanks for the detailed PR description!
I only reviewed [`utils/update_checkout/update-checkout-config.json`](https://github.com/apple/swift/blob/tensorflow-merge/utils/update_checkout/update-checkout-config.json), which looks good.

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Comment by marcrasi** [comment]
@swift-ci please clean test tensorflow

**Comment by marcrasi** [comment]
Grr, the mac toolchain tests seem quite flaky. I've rerun them a few times and changed my version of xcode and stuff and it's passing all the swift and lldb tests now, but it hangs when trying to build swiftpm. I'll try rerunning it from scratch agian.

**Comment by marcrasi** [comment]
Yay, finally got the full toolchain build and tests passing on mac! Merging now.

**Pull request merged**
