### PR TITLE
Revert "[NFC] Clarify semantics of getImportedModules."

### PR DESCRIPTION
**Pull request by varungandhi-apple**
This reverts commit 4b5d8851147bed1f0945b7e23cbf788ce7869891.

Fixes rdar://70448782.

I will re-work and re-land the refactoring later.

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
@swift-ci please test

**Review by xymus — APPROVED** [review]
Thanks!

**Review by beccadax — APPROVED** [review]
I'm fine with this as long as it doesn't undo any of the renaming.

**Comment by varungandhi-apple** [comment]
@swift-ci please test Linux

**Pull request merged**
