### PR TITLE
[test] Fix conditional conformance tests for 32-bit platforms.

### PR DESCRIPTION
**Pull request by huonw**

### CODE REVIEW

**Comment by huonw** [comment]
@swift-ci please test and merge

**Comment by gparker42** [comment]
Did you intend to disable three of these tests on all platforms by removing their RUN: lines? (It's common to disable a test by adding a nonsensical REQUIRES: line if that is the effect you want.)

**Comment by huonw** [comment]
Confusingly, they're not tests: they're `/Inputs/`. That's why I thought I'd disabled them before with the `PTRSIZE=64`, but that REQUIRES needed to be in the actual IRGen/... test rather than those files.

**Comment by gparker42** [comment]
Ah yes, that makes sense.

**Comment by shahmishal** [comment]
Failed due to: 

```
Failing Tests (1):
    Swift(iphonesimulator-i386) :: IRGen/protocol_resilience.sil
```

```
******************** TEST 'Swift(iphonesimulator-i386) :: IRGen/protocol_resilience.sil' FAILED ********************
Script:
--
rm -rf "/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/test-iphonesimulator-i386/IRGen/Output/protocol_resilience.sil.tmp" && mkdir -p "/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/test-iphonesimulator-i386/IRGen/Output/protocol_resilience.sil.tmp"
/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/bin/swiftc -frontend -target i386-apple-ios7.0  -module-cache-path '/var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/swift-testsuite-clang-module-cacheFlyCsb' -sdk /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk -swift-version 3 -emit-module -enable-resilience -emit-module-path=/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/test-iphonesimulator-i386/IRGen/Output/protocol_resilience.sil.tmp/resilient_protocol.swiftmodule -module-name=resilient_protocol /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/test/IRGen/../Inputs/resilient_protocol.swift
/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/bin/swiftc -frontend -target i386-apple-ios7.0  -module-cache-path '/var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/swift-testsuite-clang-module-cacheFlyCsb' -sdk /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk -swift-version 3 -I /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/test-iphonesimulator-i386/IRGen/Output/protocol_resilience.sil.tmp -emit-ir -enable-resilience -assume-parsing-unqualified-ownership-sil /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/test/IRGen/protocol_resilience.sil | /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/utils/PathSanitizingFileCheck --sanitize 'BUILD_DIR=/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64' --sanitize 'SOURCE_DIR=/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift' --use-filecheck '/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/llvm-macosx-x86_64/./bin/FileCheck' /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/test/IRGen/protocol_resilience.sil
/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/bin/swiftc -frontend -target i386-apple-ios7.0  -module-cache-path '/var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/swift-testsuite-clang-module-cacheFlyCsb' -sdk /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk -swift-version 3 -I /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/test-iphonesimulator-i386/IRGen/Output/protocol_resilience.sil.tmp -emit-ir -enable-resilience -O -assume-parsing-unqualified-ownership-sil /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/test/IRGen/protocol_resilience.sil
--
Exit Code: 1

Command Output (stderr):
--
/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/test/IRGen/protocol_resilience.sil:301:16: error: expected string not found in input
// CHECK-NEXT: store i64 0, i64* [[COUNT_PTR]]
               ^
<stdin>:300:2: note: scanning from here
 store i32 0, i32* %0, align 4
 ^
<stdin>:300:2: note: with variable "COUNT_PTR" equal to "%0"
 store i32 0, i32* %0, align 4
 ^

--

********************
```

**Comment by xedin** [comment]
@huonw Are you still around to fix it?

**Comment by xedin** [comment]
I've created https://github.com/apple/swift/pull/12871 which changes to make the last test pass.

**Comment by xedin** [comment]
Merged my PR.

**Pull request closed without merging**
