### PR TITLE
Flake8 fixes

### PR DESCRIPTION
**Pull request by graydon**
This PR fixes 3 classes of flake8 lints in newer flake8 editions (ambiguous variable name, unknown escape, and bare except). These are all plausibly error sources and I am happy to have them fixed.

I suggest W504 is better to just ignore and have proposed doing so here -- it's a "which side of a binary operator should a newline go on" issue -- and it seems like a cause of needless churn rather than an important potential bug. Googling around, nobody seems to think it's an especially robust choice and even [Flake8's page related to the previous state of affairs, when the bit was set the other way](https://lintlyci.github.io/Flake8Rules/rules/W503.html) has truly perplexing language on it.

### CODE REVIEW

**Comment by graydon** [comment]
@swift-ci please test

**Review by gottesmm — COMMENTED** [review]
I am all for improving our python linting. As long as this catches things on the bots (so we do not introduce more problems), I am all for this. Is everything you updated being checked?

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by graydon** [comment]
@swift-ci please test

**Comment by graydon** [comment]
@swift-ci python lint

**Comment by graydon** [comment]
@swift-ci please test and merge

**Pull request merged**
