### PR TITLE
Slight grammatical improvement.

### PR DESCRIPTION
**Pull request by thel3l**

### CODE REVIEW

**Comment by thel3l** [comment]
Lel. 
The rest of the text is written in second person. Suddenly changing will make the doc sound weird.

**Comment by lunaroyster** [comment]
To remove the pronoun,

To find out which optimization inserts, removes or moves a certain instruction, set a breakpoint in...

**Comment by thel3l** [comment]
We don't need to remove the pronoun. Read the rest of the doc. Its all in second person. The best fit is 

***Sometimes you may want to know which optimization inserts, removes or m..***

**Comment by thel3l** [comment]
@gottesmm Any updates?

**Comment by robokova** [comment]
just wanted to leave my mark here, too.

**Comment by gribozavr** [comment]
This LGTM.

**Pull request merged**
