### PR TITLE
[utils] Remove Python 2

### PR DESCRIPTION
**Pull request by dduan**
The library `six` provides compatibility between Python 2, and 3. It's no
longer necessary once we migrate off Python 2 completely.

Also remove any custom logic for Python 2 (the ones referenced by
a comment anyways).

https://bugs.swift.org/browse/SR-16025

[six's doc](https://six.readthedocs.io)
[amazing explanation wrt `__ne__`](https://stackoverflow.com/a/30676267/243798)

### CODE REVIEW

**Comment by dduan** [comment]
@swift-ci smoke test

**Comment by dduan** [comment]
@swift-ci smoke test

**Comment by dduan** [comment]
@swift-ci smoke test

**Comment by dduan** [comment]
@swift-ci smoke test

**Comment by dduan** [comment]
@swift-ci smoke test

**Comment by dduan** [comment]
@swift-ci smoke test Linux Platform

**Comment by dduan** [comment]
@swift-ci smoke test Linux Platform

**Comment by Aftabalamkhan120** [comment]
> The library `six` provides compatibility between Python 2, and 3. It's no
> 
> longer necessary once we migrate off Python 2 completely.
> 
> 
> 
> Also remove any custom logic for Python 2 (the ones referenced by
> 
> a comment anyways).
> 
> 
> 
> https://bugs.swift.org/browse/SR-16025
> 
> 
> 
> [six's doc](https://six.readthedocs.io)
> 
> [amazing explanation wrt `__ne__`](https://stackoverflow.com/a/30676267/243798)

**Comment by dduan** [comment]
🤔, I ran the following on `main` branch and the same tests failed:

```
../llvm-project/llvm/utils/lit/lit.py ../build/Ninja-ReleaseAssert/swift-macosx-arm64/validation-test-macosx-arm64 --filter 'Python'
```

```
Failed Tests (2):
  Swift-validation(macosx-x86_64) :: Python/build_swift.swift
  Swift-validation(macosx-x86_64) :: Python/python_lint.swift
```

**Comment by dduan** [comment]
@swift-ci smoke test Linux Platform

**Comment by dduan** [comment]
@swift-ci smoke test Linux Platform

**Comment by dduan** [comment]
@swift-ci smoke test macOS Platform

**Comment by dduan** [comment]
@swift-ci smoke test macOS Platform

**Comment by dduan** [comment]
@swift-ci smoke test macOS Platform

**Comment by dduan** [comment]
@swift-ci smoke test

**Comment by shahmishal** [comment]
@swift-ci test

**Review by shahmishal — APPROVED** [review]

**Review by compnerd — APPROVED** [review]

**Pull request merged**
