### PR TITLE
SILVerifier: turn on the ownership verifier again

### PR DESCRIPTION
**Pull request by eeckstein**
It was turned off by mistake

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Review by atrick — APPROVED** [review]
As I recall when I added this flag (6 months ago), the ownership verifier was only running once after SILGen and once before ownership lowering, unless `-sil-verify-all` was used. That may have been changed. I need to review the rebase, which looks to be in a bad state. Until then we need it running as much as possible in the builds. Thanks for the test.

**Pull request merged**
