### PR TITLE
[stdlib] Revert lazy mirror children

### PR DESCRIPTION
**Pull request by airspeedswift**
The improvements in #32041 inadvertently mean that custom mirrors's children no longer produce an AnyCollection that can be downcast to AnyRandomAccessCollection, which some users relied on being able to do. Reverting this change until that can be restored.

Resolves rdar://74564058

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please smoke test and merge

**Comment by airspeedswift** [comment]
@swift-ci please smoke test macOS platform

**Comment by airspeedswift** [comment]
@swift-ci please smoke test macOS platform

**Comment by kylemacomber** [comment]
@swift-ci please smoke test macOS platform

**Comment by airspeedswift** [comment]
@swift-ci please smoke test macOS platform

**Pull request merged**
