### PR TITLE
Update WindowsBuild.md

### PR DESCRIPTION
**Pull request by compnerd**
Change the LLDB python flag.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
CC: @JDevlieghere

**Comment by CodaFi** [comment]
@swift-ci smoke test macOS

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Pull request merged**
