### PR TITLE
Update tensorflow and tensorflow-bindings to recent commits.

### PR DESCRIPTION
**Pull request by bgogul**

### CODE REVIEW

**Comment by bgogul** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
You should regenerate wrappers in tensorflow-bindings against the new TF version as well. Otherwise code will break (there's a runtime test breakage).

**Comment by bgogul** [comment]
> You should regenerate wrappers in tensorflow-bindings against the new TF version as well. Otherwise code will break (there's a runtime test breakage).

I actually used the same tensorflow commit id as the one used in your recent [commits](https://github.com/tensorflow/swift-bindings/commit/f1553d52941b860f51cbae003e91383fcc58547b) to regenerate the wrappers in tensorflow-swift-bindings. That should have been enough, right?

In any case, let me regenerate the bindings to the latest TF version.

**Comment by bgogul** [comment]
@swift-ci please clean test tensorflow

**Comment by bgogul** [comment]
@swift-ci please clean test tensorflow

**Comment by bgogul** [comment]
One test is failing as there are some changes in the generated ops. I will close this PR and create a new one.

**Pull request closed without merging**
