### PR TITLE
Minor improvements to the new diagnostics formatter

### PR DESCRIPTION
**Pull request by DougGregor**
Introduce two minor improvements to the new diagnostics formatter:

* Don't aggregate across warnings/errors/remarks, because that leads to confusing outputs.
* Add support for the `remark` diagnostic severity.

### CODE REVIEW

**Comment by DougGregor** [comment]
https://github.com/apple/swift-syntax/pull/2143

@swift-ci please smoke test

**Comment by DougGregor** [comment]
https://github.com/apple/swift-syntax/pull/2143
https://github.com/apple/swift-format/pull/605

@swift-ci please smoke test macOS

**Review by ktoso — APPROVED** [review]
Oh much nicer! 💯

**Comment by DougGregor** [comment]
https://github.com/apple/swift-syntax/pull/2143
https://github.com/apple/swift-format/pull/605

@swift-ci please smoke test

**Comment by DougGregor** [comment]
https://github.com/apple/swift-syntax/pull/2143
https://github.com/apple/swift-format/pull/605

@swift-ci please smoke test

**Pull request merged**
