### PR TITLE
SILGen: Drop value argument when lowering Builtin.sizeof/alignof/strideof

### PR DESCRIPTION
**Pull request by jckarter**
The metatype value isn't needed to do the memory layout computation, and
IRGen only looks at the substitutions passed to the generic signature, so
we can reduce SIL code size, and avoid leaving behind useless metadata
accesses, if we don't emit it.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by buttaface** [comment]
@jckarter, it appears [you committed an executable called `foo`](https://github.com/apple/swift/pull/60252/files#diff-2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae) by mistake.

**Pull request merged**
