### PR TITLE
[silgen] Change SILGenFunction::WritebackStack to use a std::unique_ptr.

### PR DESCRIPTION
**Pull request by gottesmm**
[silgen] Change SILGenFunction::WritebackStack to use a std::unique_ptr.

We are already mallocing this std::vector, but have been managing its lifetime
ourselves in order to not expose LValueWriteback in SILGenFunction.
std::unique_ptr lets us hide that type as well and not manage its lifetime
ourselves!

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci Please smoke test and merge

**Comment by jrose-apple** [comment]
Are we really saving anything here? IIRC, empty std::vectors don't allocate.

**Comment by gottesmm** [comment]
@jrose-apple The reason why this is being allocated out of line is to not expose LValueWriteback in SILGenFunction.h due to circular header include problems.

**Comment by jrose-apple** [comment]
Wait, right, the comment says that right there. Thanks.

**Comment by gottesmm** [comment]
@jrose-apple I am actually going to be reworking this whole thing, so it won't have to be done out of line anymore.

**Pull request closed without merging**
