### PR TITLE
[stdlib] Remove `#warning` in Random.cpp (_WIN32)

### PR DESCRIPTION
**Pull request by benrimmington**

### CODE REVIEW

**Comment by benrimmington** [comment]
@compnerd Have you managed to test `swift_stdlib_random` on Windows?

Please merge this pull request, if you think the `#warning` isn't needed.

**Comment by compnerd** [comment]
@benrimmington no, I don't think that we have tests for this yet which is why I haven't removed the warning yet.

**Comment by benrimmington** [comment]
`swift_stdlib_random` is used in [`SystemRandomNumberGenerator._fill(bytes:)`](https://github.com/apple/swift/blob/019919d667c3f348261ac0b11469d45a7da5bb40/stdlib/public/core/Random.swift#L171-L177), which has a [validation-test](https://github.com/apple/swift/blob/019919d667c3f348261ac0b11469d45a7da5bb40/validation-test/stdlib/Random.swift#L11-L29).

Should the `_fill(bytes:)` customization point be removed in Swift 5? It doesn't appear to be used elsewhere (since #17604).

Could the validation-test call `swift_stdlib_random` (exported via `SWIFT_RUNTIME_STDLIB_API`) directly?

Cc: @mikeash, @Azoy

**Comment by Azoy** [comment]
@benrimmington I have a ready implementation to formally introduce `fillBytes(_:)`, but I haven't gotten around to writing the actual proposal. I'm not sure even if I had something ready by tomorrow that it'd go through review before Nov. 16 however. I've been very busy 😞

**Comment by benrimmington** [comment]
@Azoy Can your `fillBytes(_:)` proposal be reviewed for Swift 5.1 or later? It might be able to use the new `DataProtocol`.

Does your `next(upperBound:)` amendment need to be reviewed by next week?

Shall I remove `_fill(bytes:)` now, so that it isn't in the Swift 5.0 ABI?

Shall I also remove the `_fill(bytes:)` validation-test? Other tests are indirectly using `swift_stdlib_random`.

**Comment by Azoy** [comment]
cc: @lorenty who might have some opinions on what we could do.

**Comment by lorentey** [comment]
Oh, I haven't realized we aren't using `_fill(bytes:)` anymore. Removing it seems like a good idea indeed!

As long as we don't need it, It seems cleaner to add a de-underscored version later than trying to support both.

**Comment by lorentey** [comment]
I submitted #20463 to remove it!

**Pull request closed without merging**
