### PR TITLE
Update tests for change to swiftcall

### PR DESCRIPTION
**Pull request by rjmccall**

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please test with following pull request:
https://github.com/apple/swift-clang/pull/215

**Comment by rjmccall** [comment]
@swift-ci Please test with following PR https://github.com/apple/swift-clang/pull/215

**Comment by rjmccall** [comment]
Please test with following PR:
https://github.com/apple/swift-clang/pull/215

@swift-ci Please test.

**Comment by rjmccall** [comment]
Got to get the magic words right.

**Comment by rjmccall** [comment]
The automerger seems to have gone ahead and automerged, so this is tardy now.

**Comment by rjmccall** [comment]
@swift-ci Please smoke test OS X.

**Comment by rjmccall** [comment]
...OS X failure is an ownership verification failure in the 32-bit iOS simulator.  Trying a smoke test.

**Comment by rjmccall** [comment]
(my patch does not touch SIL)

**Comment by gottesmm** [comment]
@rjmccall I am fixing the simulator failure here: https://github.com/apple/swift/pull/20150#issuecomment-434173284

**Comment by rjmccall** [comment]
Thanks, Doug.

**Pull request merged**
