### PR TITLE
Fix a handful of regressions

### PR DESCRIPTION
**Pull request by slavapestov**
rdar://problem/45919829, rdar://problem/45901706, rdar://problem/45900947

### CODE REVIEW

**Review by DougGregor — APPROVED** [review]
Grab-baggy but LGTM

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
apple/swift-lldb#1066
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Review by jckarter — APPROVED** [review]

**Comment by jckarter** [comment]
your face is grab-baggy

**Pull request merged**
