### PR TITLE
GSB: Optimize PotentialArchetype::getDependentType()

### PR DESCRIPTION
**Pull request by slavapestov**
We were spending a lot of time in DependentMemberType::get(), via PotentialArchetype::getDependentType(), which is a recursive walk from the root to the leaf. We can reduce this cost with two changes:

- DerivedSameTypeComponent doesn't need to store a `PotentialArchetype *` at all, only a `Type`.
- PotentialArchetype's representation can be changed to just store the canonical dependent type directly, instead of a union of `GenericParamKey` with `AssociatedTypeDecl *`.

We still have to rebuild `DependentMemberType` to "re-sugar" them with the right generic parameter name. While this is important when the type is ultimately meant for user consumption, there are many places where we do it unnecessarily. Fixing those is the next step here.

On this incredibly silly benchmark, an asserts build is now twice as fast as without this change, from ~8 seconds to 4:

```
public protocol P1 {
  associatedtype A
  associatedtype B
  associatedtype C
  associatedtype D
}

public protocol P2 {
  associatedtype A : P1
  associatedtype B : P1
  associatedtype C : P1
  associatedtype D : P1
}

public protocol P3 {
  associatedtype A : P2
  associatedtype B : P2
  associatedtype C : P2
  associatedtype D : P2
}

public protocol P4 {
  associatedtype A : P3
  associatedtype B : P3
  associatedtype C : P3
  associatedtype D : P3
}

public protocol P5 {
  associatedtype A : P4
  associatedtype B : P4
  associatedtype C : P4
  associatedtype D : P4
}

public protocol P6 {
  associatedtype A : P5
  associatedtype B : P5
  associatedtype C : P5
  associatedtype D : P5
}

public protocol P7 {
  associatedtype A : P6
  associatedtype B : P6
  associatedtype C : P6
  associatedtype D : P6
}

public protocol P8 {
  associatedtype A : P7
  associatedtype B : P7
  associatedtype C : P7
  associatedtype D : P7
}

public protocol P9 {
  associatedtype A : P8
  associatedtype B : P8
  associatedtype C : P8
  associatedtype D : P8
}

public protocol P10 {
  associatedtype A : P9
  associatedtype B : P9
  associatedtype C : P9
  associatedtype D : P9
}
```

### CODE REVIEW

**Review by DougGregor — APPROVED** [review]
Very nice!

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test

**Pull request merged**
