### PR TITLE
Add missing testcase

### PR DESCRIPTION
**Pull request by adrian-prantl**
rdar://problem/27891980

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci Please smoke test and merge

**Comment by tkremenek** [comment]
@swift-ci test macOS

**Comment by adrian-prantl** [comment]
@swift-ci test macOS and merge

**Comment by adrian-prantl** [comment]
@swiftci Please test platform macOS

**Comment by adrian-prantl** [comment]
@swift-ci Please test OS X platform

**Comment by adrian-prantl** [comment]
@swift-ci Please test OS X platform

**Pull request merged**
