### PR TITLE
[benchmark] Data.[init,append].Sequence various sizes

### PR DESCRIPTION
**Pull request by palimondo**
Follow-up to #21766 for benchmarking the refinement of the new `Data` implementation in #21754.

This PR adds thorough performance coverage of the `init` and `append` methods for `Sequence`s. During the discussion in https://github.com/apple/swift/pull/21754#discussion_r247278139, the use of stack allocated buffer for sequences shorter than 2kB ([`_withStackOrHeapBuffer`](https://github.com/apple/swift/blob/6fc4cef671947d1d2482951853f7f82854473d91/stdlib/public/SwiftShims/FoundationOverlayShims.h#L62)) has been mentioned as potential reason for the performance differences we were seeing there. This adds benchmarks to validate that hypothesis.

During experimentation with these benchmarks I've learned of my previous mistake: `ExactCount` vs. `UnderestimatedCount` wasn't actually an apples-to-apples comparison. Though functionally equivalent, the [`repeatElementSeq`](https://github.com/apple/swift/blob/61e85ced7d16d968bcb462999cba05919280458e/benchmark/single-source/DataBenchmarks.swift#L307-L311) wasn't compiled and optimized to same code as `repeatElement`. The slowdown we were seeing could be caused by the difference in sequence implementation. My bad! 🙇‍♂️

To rectify this, I have first created  [`Bytes`](https://github.com/apple/swift/blob/61e85ced7d16d968bcb462999cba05919280458e/benchmark/single-source/DataBenchmarks.swift#L320-L335) that produces simple increasing byte sequence and depending on the `exact` parameter reports either exact count or `0` as its `underestimatedCount`. This sequence is very simple I have worried it would be inlinable even when other more complex sequences were not. Therefore I've created [`Count0`](https://github.com/apple/swift/blob/61e85ced7d16d968bcb462999cba05919280458e/benchmark/single-source/DataBenchmarks.swift#L313-L318) wrapper that always reports `underestimatedCount = 0` and can be used to erase the exact from other sequences. Using this I've added a second **`RE`** benchmark variant that uses `repeatElement`, as was originally the case with the `DataAppendSequence`.

To thoroughly explore the problem space, I have created another 2 variants from all tests: one using shared [generic non-inlinable test method](https://github.com/apple/swift/blob/61e85ced7d16d968bcb462999cba05919280458e/benchmark/single-source/DataBenchmarks.swift#L443-L457) and another with sequence created directly in the same block, which theoretically allows for the sequence to be inlined into the `Data`'s `init` or `append` methods — denoted with **`.I`** suffix for **inlinable**.

I've also added sequences that test around the edges of the two possible thresholds (`511B/513B`, `2047B/2049B`) for the stack allocated / heap allocated buffer and in my local tests it looks like the complicated implementation is bringing no measurable advantage. I suspect that the complexity of [`_withStackOrHeapBuffer`](https://github.com/apple/swift/blob/6fc4cef671947d1d2482951853f7f82854473d91/stdlib/public/SwiftShims/FoundationOverlayShims.h#L62) is the reason for the slowdown between `Count` and `Count0`. 

Notes about the benchmark results:
* The the `Bytes`-based as well `repeatElement`-based (`RE`) perform similarly.
* It looks like sequence inlining is not happening.

In summary:
* Existing sequence benchmarks were collected into **`809B`**  group (using `*100` multiplier).
* New variants **`511B/513B`** and **`2047B/2049B`** test the advantage of stack allocated buffer.
* Benchmarks for longer **`64kB`**  sequence (multiplier of `1`) were added.
* **`Count`** is a test group where sequences report their full length in `underestimatedCount`.
* In the **`Count0`** group `underestimatedCount` always returns `0`.
* By default test are using **`Bytes`** sequence.
* Variants marked with **`.RE`** are using **`repeatElement`** sequence.
* In variants marked with **`.I`**, the sequence can be potentially inlined into `Data`'s methods.

The scaling is derived from the presumption that `809B` creates/appends ~80kB of data, so the new `64kB` group should be faster but roughly in the same ball park.

### CODE REVIEW

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
The [`append`](https://github.com/apple/swift/blob/31f0bd5a98611913bdebdc28a69ff7dea0507db4/benchmark/single-source/DataBenchmarks.swift#L391-L397) test is using a shared generic test function, which precludes (I guess?) inlining of the sequence into the `Data.append<S: Sequence>`, while the `Data.init` family is tested in a same block, ie. with possibility to inline the `Sequence` into the initialization. Comparing `init` and `append`, it seems like none of the `repeatElement`, [`repeatElementSeq`](https://github.com/apple/swift/blob/31f0bd5a98611913bdebdc28a69ff7dea0507db4/benchmark/single-source/DataBenchmarks.swift#L261-L265) (base on the `sequence` function), nor the lazily mapped `Range` and it's `IndexedIterator` are getting inlined. But the single-purpose `Bytes` sequence is getting inlined. In `Data.init.Sequence.64kB.ExactCountB` it is blowing far past the other variants: it takes just 4 μs on my 2008 MBP, so it'll be unmeasurable on the CI, unless I change the loop multiplier.

I'm on a fence about adding inlined and non-inlined variants of `init/append`.  Can we try to formulate some sensible strategy on what variants make sense with regards to different generic/specialized code and inlining criteria? I don't yet have a firm grasp on all the compilation magic that's going on there… @atrick, @eeckstein, what do you think?

**Comment by palimondo** [comment]
You might want to re-run the benchmarks again, once we get the first results in, so that we can see the difference #21754 made. I'm going to drop some 💤s… See you tomorrow! 👋🌌😴

**Comment by palimondo** [comment]
I must have messed something up with that last push… I'll fix it tomorrow. Nothing to see here yet.

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
@atrick @eeckstein @itaiferber @phausler Please review.

Notes about the benchmark results:
* The the `Bytes`-based as well `repeatElement`-based (`RE`) perform similarly.
* It looks like sequence inlining is not happening.

I've pushed another update (and triggered a benchmark), where I've added `Array.init/append.Sequence.64kB` benchmarks for direct comparison. I've also added sequences that test around the edges of the two possible thresholds for the stack allocated / heap allocated buffer and in my local tests it looks like the complicated implementation is bringing no measurable advantage. I suspect that the complexity of [`_withStackOrHeapBuffer`](https://github.com/apple/swift/blob/6fc4cef671947d1d2482951853f7f82854473d91/stdlib/public/SwiftShims/FoundationOverlayShims.h#L62) is the reason for the slowdown between `Count` and `Count0`. Let me know what you think...

**Comment by palimondo** [comment]
Ping @atrick @eeckstein @itaiferber @phausler

**Review by phausler — APPROVED** [review]
Looks reasonable to me for measuring that particular set of cases. I honestly think more coverage is better so I don’t see a need for paring this down any.

**Comment by palimondo** [comment]
Umm… I mean… at least the `Array` benchmarks are not really part of this. It's here just to illustrate the performance gap we should probably close or at least reasonably justify before considering the implementation good enough to ship.

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
@swift-ci please smoke test

**Comment by palimondo** [comment]
@phausler I'm going to merge this based on your previous approval once the checks pass, if you didn't change your mind about the multitude of these benchmarks.

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Pull request merged**
