### PR TITLE
[Concurrency] Use an availability macro instead of OS versions 9999

### PR DESCRIPTION
**Pull request by xymus**
The use of an availability macro will make it easier to update those versions to the marketing versions when they are announced. Plus internal branches can redefine only the macro for customized availability.

### CODE REVIEW

**Review by ktoso — APPROVED** [review]
Oh my that's lovely! <3

Thanks so much for making that happen :-)

**Comment by xymus** [comment]
Let's try this with the Concurrency module first. I remain open to suggestions for a better macro name.

@swift-ci Please smoke test

**Review by mikeash — APPROVED** [review]
❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️

**Comment by mikeash** [comment]
As far as naming goes, maybe `SwiftStdlib 5.5` or `SwiftRuntime 5.5` would be clearer. But the one you have is fine too and I have no particular attachment to any of them.

**Comment by xymus** [comment]
Updated with `SwiftStdlib 5.5`, thanks for the suggestion!

@swift-ci Please smoke test

**Review by DougGregor — COMMENTED** [review]
This is very cool! Two questions!:
* Shouldn't we also do this for the standard library, which uses the same pattern?
* Lots of tests also use this. Should we also put this into the normal lit config so we can use `SwiftStdlib <version number>` there, too?

**Comment by xymus** [comment]
Good points. I plan on adding the same macro for the standard library, however it looks like it has some left-over uses of 9999 for older versions that will need more care to turn on or avoid. I'll add it to the lit config at the same time, I didn't think of that.

@swift-ci Please smoke test macOS

**Comment by xymus** [comment]
@swift-ci Please smoke test macOS

**Pull request merged**
