### PR TITLE
[AutoDiff] Cleanup 1: Remove gradient synthesis and ban #gradient.

### PR DESCRIPTION
**Pull request by rxwei**
As we've finished generalized differentiability, we start to remove legacy code from the compiler. The first step is to remove gradient synthesis from the core transform.

Gradient synthesis was the phase of differentiation that replaced `#gradient(f)` with a function call to `f`'s gradient function. This had lots of mathematical problems, and is no longer necessary under generalized differentiability because all differential operators are now defined as stdlib functions.

-----------------

### Changes
1. Remove gradient synthesis code paths along with any mentions of "gradient" from the core transform.
2. Remove `VectorNumeric.init(_:)` -- it was used by gradient synthesis to initialize a 1 value. The removal brought up a couple of crashers with initializing a 0 tangent vector. When a zero needed to be materialized, the compiler tried to find `VectorNumeric.init(_:)` instead of `VectorNumeric.zero`. The good thing is that it's only affecting one or two tests so I just commented them out for now. Fixing this is my immediate next step.
4. In the process of migrating tests, I found a verification failure in the seed initialization for the adjoint/pullback of indirect calls whose original function is followed by a `tuple_extract` when only one result is active. It tried to seed the adjoint/pullback using the entire tuple, but it should pass the active result's adjoint element instead. I fixed that for both VJP mode and non-VJP mode.
5. Migrate tests to use functional differential operators. 
    - Disable the tensor runtime AD test because there's a segfault when we use the `pullback(at:in:)` operator. I will fix this in a separate PR.
    - After the switch, the diagnostics test shows that errors are no longer accumulating for some reason, but the compiler is still able to emit correct error messages for each error case. I commented out all except one case of diagnostics checks in `autodiff_diagnostics.swift` because this can be investigated later.

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Review by dan-zheng — APPROVED** [review]
Hurray!

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Pull request merged**
