### PR TITLE
[5.5] Delete flaky tests and add back test coverage to other crasher tests

### PR DESCRIPTION
**Pull request by gottesmm**
I am doing this specially for 5.5 in order to ensure that the bots do not hit
issues related to this.

NOTE: We already covered this explicitly with crash tests. That being
said, just for completeness/paranoia I am currently merging some literal
versions of these into main and will add them later. I just do not want to have
spurious failures on the bots.

----

CCC

Explanation: When I originally added these FileCheck tests, I thought they were stable... but after a day of testing on the bots, it is clear that they are not. This just deletes these tests so that the 5.5 bots are not hit by instability. There are already runtime based tests that test out the same things (using no-crash/crash cases).
Scope: Without this change, the 5.5 bots will fail sometime.
SR Issue: rdar://81031901
Risk: None. We are just removing flaky tests and added a few additional ones to ensure test coverage.
Testing: I added back some of the tests as appropriate.
Reviewer: @mikeash

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Review by mikeash — APPROVED** [review]

**Comment by gottesmm** [comment]
@swift-ci nominate

**Review by DougGregor — APPROVED** [review]

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test linux platform

**Pull request merged**
