### PR TITLE
[AutoDiff] Add tests.

### PR DESCRIPTION
**Pull request by dan-zheng**
Add the following:
- Crasher tests.
- Activity analysis tests.
- Control flow differentiation known incorrect derivative tests.

Crasher tests are in `test/AutoDiff/compiler_crashers`.
They each reference a JIRA issue and start with `RUN: not --crash`.
They should be moved to `test/AutoDiff/compiler_crashers_fixed` when they are fixed.

---

The following issues are newly tracked:
TF-429, TF-756, TF-781, TF-881, TF-923, TF-928, TF-945.

Some of these issues are in-progress!

### CODE REVIEW

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Review by rxwei — APPROVED** [review]

**Comment by dan-zheng** [comment]
Added activity analysis tests in `test/AutoDiff/activity_analysis.swift`.

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Pull request merged**
