### PR TITLE
[SIL] BuiltinInsts have type dependent operands.

### PR DESCRIPTION
**Pull request by nate-chandler**
Collect all types in the substitution map which constitute type-dependent operands and record them in the instruction's operand list.  Fixes a bug where `open_existential_metatype` (e.g.) is deleted as dead because it has no users even when the type it defines is used in a substitution map of a builtin.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Review by drexin — APPROVED** [review]
LGTM

**Review by Azoy — COMMENTED** [review]
Thank you for tracking this down!

**Comment by nate-chandler** [comment]
@swift-ci please test windows platform

**Pull request merged**
