### PR TITLE
[migrator] Add an AST pass to handle tuple mismatches

### PR DESCRIPTION
**Pull request by akyrtzi**
Migrates code that compiles fine in Swift 3 but breaks in Swift 4 due to
changes in how the typechecker handles tuple arguments.

### CODE REVIEW

**Comment by akyrtzi** [comment]
@swift-ci smoke test and merge

**Comment by akyrtzi** [comment]
@swift-ci smoke test

**Comment by akyrtzi** [comment]
@swift-ci smoke test

**Comment by jrose-apple** [comment]
@xedin is actively working on this in #9219.

**Comment by akyrtzi** [comment]
That's great! In general these can be complementary, and we'll certainly evaluate how successful the fixits are in projects.

**Pull request merged**
