### PR TITLE
[Clang importer] Move the "all properties" lists into the name importer.

### PR DESCRIPTION
**Pull request by DougGregor**
Swift's ASTContext contained all of the logic to find the complete list
of properties for an Objective-C class, which is used by the Clang importer
to influence the mapping of Objective-C names into Swift. Swift's
ASTContext also included a *cache* for this information, indexed by
the Clang `ObjCInterfaceDecl *`. However, this cache was getting
populated/queried from the Clang importer's name importer, such that
the keys would be Clang declarations used to build modules and then
deallocated. If that memory eventually gets reused for a different
`ObjCInterfaceDecl *`, we would get incorrect/stale all-properties
information.

Almost Surely fixes rdar://problem/35347167, which is a
nondeterministic failure where UIView's `addGestureRecognizer(_:)` gets
occasionally imported as `add(_:)`.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Review by jrose-apple — APPROVED** [review]
Oh…oh gosh. Is there anything else the name importer does that reaches up to the ASTContext in a mutable way?

**Comment by DougGregor** [comment]
Time for an audit!

**Comment by DougGregor** [comment]
Note that this happens on the first build where Clang modules are built (or rebuilt), because the module build forms the stale pointers. Immediately rebuilding will work because the new Swift frontend job won't see any stale pointers.

**Pull request merged**
