### PR TITLE
Accelerate fix interpolate between neighbours tests

### PR DESCRIPTION
**Pull request by FlexMonkey**
The single- and double-precision InterpolateBetweenNeighbours tests created illegal indices in the control vector that lead to undefined behaviour and occasional test failures. This PR fixes that.

cc: @stephentyrone

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
Windows failure is unrelated:

```
FAIL: Swift(windows-x86_64) :: Frontend/crash-in-user-code.swift (5166 of 6058)
```

**Comment by lorentey** [comment]
@FlexMonkey could you remove the `REQUIRES: rdar50301438` line so that this test gets reenabled on CI? As it stands, swift-ci doesn't actually run this test, so the PR test results don't indicate anything. 😉

**Comment by FlexMonkey** [comment]
> @FlexMonkey could you remove the `REQUIRES: rdar50301438` line so that this test gets reenabled on CI? As it stands, swift-ci doesn't actually run this test, so the PR test results don't indicate anything. 😉

That's done! Cheers.

**Pull request closed without merging**
