### PR TITLE
Conform to existing conventions for Vim ftplugin

### PR DESCRIPTION
**Pull request by ghost**
This commit adds standard conventions for Vim filetype plugins:

- Allows users to opt out of using the provided ftplugin file, if they
  choose to install and use another set of runtime files for Swift
  (which offers its own version of ftplugin for Swift), It also prevents
  this ftplugin file from being sourced again if a ftplugin file for
  Swift was already sourced. Vim's documentation on this recommends
  offering users this option as well, under the "DISABLING" section
  of `:help write-filetype-plugin`).

- Adds the `b:undo_ftplugin` buffer local variable, which is used to
  undo the filetype settings when the `:setfiletype` command is used
  (See :help `undo_ftplugin`). Also prefer using the full names for Vim
  settings instead of short ones as they are more readable.

The above conventions are in place in many of the ftplugin files
shipped with Vim, so they can be used as a reference, as well.

Vim documentation References: 

- [`:help write-filetype-plugin`](https://vimhelp.org/usr_41.txt.html#41.12)
- [`:help undo_ftplugin`](https://vimhelp.org/usr_41.txt.html#undo_ftplugin)

### CODE REVIEW

**Comment by ajh17** [comment]
@swift-ci Please smoke test

**Comment by CodaFi** [comment]
@swift-ci Please smoke test

**Comment by CodaFi** [comment]
@swift-ci smoke test macOS

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
