### PR TITLE
test: convert rm -rf && mkdir -p into %empty-directory

### PR DESCRIPTION
**Pull request by compnerd**
This converts the instances of the pattern for which we have a proper
substitution in lit.  This will make it easier to replace it
appropriately with Windows equivalents.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@gribozavr, @gottesmm: probably makes you two happy :-)

**Comment by compnerd** [comment]
CC: @Rostepher

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by Rostepher** [comment]
I greatly appreciate this PR! Thanks for cleaning this up.

**Comment by compnerd** [comment]
Sure thing!  Okay, the failures are "valid".  The file content changes has changed offsets.  I'll adjust that accordingly.

**Comment by compnerd** [comment]
@swift-ci please test

**Pull request merged**
