### PR TITLE
Add a SWIFT_STDLIB_HAS_STDIN flag to compile out the readLine API (for the 'freestanding' preset)

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Review by mikeash — APPROVED** [review]

**Review by compnerd — APPROVED** [review]
Im mostly good with this - I just wish that the commit message could be a bit better.  Namely, it is very confusing because deadline is a library, and it's easy to mixup `readLine` and readline.  But, not sure how much better we could do (perhaps the quoting is the best we can do?).  FWIW, I think that this would be useful for other environments as well (e.g. Android) where stdin is meant to be inaccessible.

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Pull request merged**
