### PR TITLE
[5.5] fix weak reference lifetime warnings and disable by default

### PR DESCRIPTION
**Pull request by atrick**
Fix weak reference lifetime warnings, making them more precise and avoiding spurious warnings. Adding logic to this pass and increasing precision adds risk, so disable the warnings by default.

Only issue weak lifetime warnings for users who select object lifetime
optimization. The risk of spurious warnings outweighs the benefits.

Although the warnings are generally useful regardless of the level of
optimization, it isn't really critical to issue them unless the optimizer
aggressively shrinks reference lifetimes.

Fixes rdar://79146338 Xcode warns that "referenced object is
deallocated here" but that object was passed into a method that causes
strong retention)

### CODE REVIEW

**Comment by atrick** [comment]
@eeckstein I'm looking for a CCC review for these cherry-picks that disable the warnings by default and also fix them for users who select lifetime optimization.

**Review by eeckstein — APPROVED** [review]
lgtm!

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
--- CCC ---

Explanation: Fix weak reference lifetime warnings, making them more precise and avoiding spurious warnings. Only run the diagnostic when Optimize Object Lifetimes is enabled.

Scope: Fixes spurious warnings that could previously occur in any build.

Radar/SR Issue: rdar://79146338 Xcode warns that "referenced object is
deallocated here" but that object was passed into a method that causes
strong retention)

Origin: New diagnostic pass introduced in Swift 5.5.

Risk: The diagnostic itself can crash. Increasing its precision can caused spurious warnings. Disabling them by default eliminates both risks.

Testing: I found no spurious warnings in a full SCK build.

Reviewer: Erik Eckstein

**Comment by atrick** [comment]
protocol conformance collision failure 😕

**Comment by atrick** [comment]
@swift-ci test macOS

**Comment by atrick** [comment]
@swift-ci test macOS

**Comment by atrick** [comment]
@swift-ci test macOS platform

**Review by tkremenek — APPROVED** [review]

**Comment by tkremenek** [comment]
@swift-ci clean test

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci clean test

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci test macOS

**Comment by atrick** [comment]
@swift-ci test macOS

**Comment by atrick** [comment]
@swift-ci clean test macOS

**Comment by atrick** [comment]
@swift-ci test macOS

**Pull request merged**
