### PR TITLE
[stdlib] Fix calling convention mismatch for debugger utility functions

### PR DESCRIPTION
**Pull request by kateinoigakukun**
The functions `swift_retainCount`, `swift_unownedRetainCount`, and `swift_weakRetainCount` are declared in `HeapObject.h` as using the C calling convention, but the Swift declarations referenced them by `@_silgen_name`, which uses the Swift calling convention. This patch fixes the mismatch without any ABI/API breakage by calling the utility functions through C interop.

### CODE REVIEW

**Comment by kateinoigakukun** [comment]
@swift-ci Please smoke test

**Comment by tbkka** [comment]
I'm unfamiliar with the underlying issue here.  @jckarter does this look right to you?

**Comment by MaxDesiatov** [comment]
Hi @jckarter would you have a moment to take a look? Thank you!

**Comment by al45tair** [comment]
Just to elaborate slightly on what this is all about; on x86-64 and arm64, the C and Swift calling conventions are _very similar_, and if you are calling a C function and the compiler thinks it's using Swift calling convention and it doesn't `throw`, it's extremely unlikely that you'll have a problem. It is _technically_ wrong, but you'll get away with it.

On WASM, however, the calling conventions _are genuinely different enough that they aren't compatible_, so we need them to match up properly.

**Comment by MaxDesiatov** [comment]
IIUC the calling conventions more or less match the other platforms, but for this code to work on Wasm unchanged, C and Swift calling conventions have to be exactly the same.

When targeting Wasm, function signature used by the caller and the callee should exactly match each other, otherwise a spec-compliant implementation must trap on a mismatch.

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci build toolchain

**Comment by MaxDesiatov** [comment]
preset=buildbot_incremental_linux_crosscompile_wasm
@swift-ci Please test with preset Linux Platform

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci build toolchain

**Comment by MaxDesiatov** [comment]
preset=buildbot_incremental_linux_crosscompile_wasm
@swift-ci Please test with preset Linux Platform

**Comment by MaxDesiatov** [comment]
@swift-ci test linux

**Review by tbkka — APPROVED** [review]

**Comment by jckarter** [comment]
This looks good to me.

**Review by al45tair — APPROVED** [review]
After the `bitPattern:` change, LGTM.

**Comment by MaxDesiatov** [comment]
@swift-ci build toolchain macos

**Comment by stephentyrone** [comment]
This is both an ABI-breaking change and by virtue of being ABI-breaking introduces new API without necessary availability annotations, neither of which are acceptable in the stdlib. Reverting.

**Comment by stephentyrone** [comment]
This can be fixed by marking the new implementations either backDeployed or alwaysEmitIntoClient. Please put up a new PR that handles this correctly, and tag @lorentey or me to review.

**Comment by kateinoigakukun** [comment]
@stephentyrone Thank you for catching this and sorry for the breakage. For future reference, could you tell me what part of this change breaks the ABI? Thanks in advance 🙏

**Comment by stephentyrone** [comment]
@kateinoigakukun it's breaking because new code compiled against these interfaces will reference symbols that do not exist on older swift runtimes. E.g. use of the function `_getUnownedRetainCount` will generate a call to the symbol `_$ss22_getUnownedRetainCountySuyXlF`, but that doesn't exist in any runtime that predates this change.

For trivial shims like this, you can work around this by marking them `@_alwaysEmitIntoClient` (so that the symbol will unconditionally be emitted into the calling binary), or `@backdeployed(before:)` (where it will only be emitted into the calling binary when targeting a swift runtime version that doesn't have the symbol).

**Comment by kateinoigakukun** [comment]
I totally got it! Thanks for your kind explanation.

**Comment by al45tair** [comment]
Sorry, I should have spotted this — the issue here is that the `@_silgen_name` means we aren't adding a symbol (e.g. we're just telling Swift that `_getRetainCount` uses the symbol `swift_retainCount`), whereas after the change there are three new public functions.

It would probably be better to fix `@_cdecl` to allow declarations with no function body, like `@_silgen_name` does, since that wouldn't suffer from this problem.

**Comment by stephentyrone** [comment]
IIRC, there's still a lingering problem with modules and `@_silgen_name` (which probably doesn't matter in this case because all of these are linked into the libswiftCore.dylib anyway), but could actually bite you with `@_cdecl` as well in the more general case.

**Comment by lorentey** [comment]
Another issue was that calling `unsafeBitCast` on an instance of a reference type may introduce undefined behavior.

I submitted #67853 to try fixing all of these.

**Pull request merged**
