### PR TITLE
[Concurrency] Add a debug variable that holds the current version of the concurrency library.

### PR DESCRIPTION
**Pull request by mikeash**
This allows lldb to know which version of the internals layout it needs to use.

rdar://135886268

### CODE REVIEW

**Review by rokhinip — APPROVED** [review]

**Comment by mikeash** [comment]
I tried to sprinkle the warning comment in a few different places to make it more likely to be noticed when one of us makes a change. Hopefully this is good coverage. I'm open to adding it in more places if anyone thinks that would be worthwhile.

**Review by adrian-prantl — APPROVED** [review]
This is great, thanks!

**Review by al45tair — APPROVED** [review]
LGTM, though ideally we wouldn't be changing ABI details anyway…

**Comment by mikeash** [comment]
This would also cover various non-ABI internal details that the debugger might like to poke around in.

**Comment by mikeash** [comment]
`test/abi/macOS/arm64/concurrency.swift` and `test/abi/macOS/x86_64/concurrency.swift` needed an entry for this new symbol.

**Comment by mikeash** [comment]
@swift-ci please smoke test

**Pull request merged**
