### PR TITLE
[WIP] Remove duplicate interpolation SILGen code

### PR DESCRIPTION
**Pull request by beccadax**
This is a refactoring that doesn't work yet. The first eight commits are all from #27292; the last commit is new, and attempts to switch from manually creating a temporary allocation to using `ManagedValue::materialize()`. The problem is that doing this breaks the OSLogInterpolation tests, and I'm not sure how to fix them.

This change appears to break OSLog in two ways:

1. `error: 'OSLogMessage' struct is unoptimizable: 'init' is not constant evaluable`. This is because `beginOfInterpolation()` in the OSLog optimization pass starts interpreting instructions at the `alloc_stack` instruction, but the change I made to SILGen causes it to emit the allocating init call before the `alloc_stack` instead of after. I have some code stashed locally which fixes this by finding the `store` instruction that initialized the `alloc_stack` and then tracing all of its operands recursively to find the earliest instruction involved in initializing the `OSLogMessage` instance; this seems to work, but it's very complex and I think I may be taking the wrong approach.

2. `error: globalStringTablePointer builtin must used only on string literals`. When I see this, the argument is a reference to the `formatString` property, which suggests that this change also breaks something more subtle in the OSLog pass.

I'm posting this PR so I can share it with people who may know how to fix this problem. But first, I'll run tests so we can see what we're dealing with.

### CODE REVIEW

**Comment by brentdax** [comment]
@swift-ci please smoke test

**Comment by brentdax** [comment]
Example of the failures: https://ci.swift.org/job/swift-PR-osx-smoke-test/17542/consoleFull#16525587803122a513-f36a-4c87-8ed7-cbc36a1ec144

@ravikandhadai Any thoughts about this?

**Comment by ravikandhadai** [comment]
@brentdax I can help you fix this. Unfortunately, the logic in the `beginOfInterpolation` function of the OSLogOptimization pass is a bit fragile and it has been a pain point.  The function tries to find the first SIL instruction that is generated for the string interpolation passed to the os log APIs. (Btw,  the second error relating to `globalStringTablePointer` is just because of the first.) 

> I have some code stashed locally which fixes this by finding the store instruction that initialized the alloc_stack and then tracing all of its operands recursively to find the earliest instruction involved in initializing the OSLogMessage instance; this seems to work, but it's very complex and I think I may be taking the wrong approach.

I think this kind of backward dependency analysis is possible, and could benefit other applications of constant evaluation. But my concern is, as you say, it could be complex and will also have to be conservative (if there are intervening function calls) meaning that it could result in more code being analyzed.  There is also a  requirement specific to OSLog that we shouldn't follow some parts of the backward dependency chain that corresponds to the "dynamic" argument being logged.

An alternative is to "mark" the start and end of the SIL instructions generated for a string interpolation during SILgen. I am not sure how feasible this is? We either need dummy instruction or a way to associate some metadata with the SIL instruction. Not sure, how easy it is to do. 

Anyway, I will take a look at the new SIL to see if there is a better way to change that code.

**Comment by brentdax** [comment]
@ravikandhadai The dependency analysis [wasn't actually too horrible](https://gist.github.com/brentdax/dee3cc01f4ff4567a138365d922f71eb); the only problem was that it didn't seem to resolve the situation completely—I still got `globalStringTablePointer` errors even with it in place.

**Comment by ravikandhadai** [comment]
@brentdax  I have created a PR here: https://github.com/apple/swift/pull/27419 that fixes this issues. I tested it on this PR also. The change does the backward dependency traversal that we discussed here.

**Comment by brentdax** [comment]
Now that #27419 has fixed the issue blocking this change, I'm folding it back into #27292. Thank you, @ravikandhadai!

**Pull request closed without merging**
