### PR TITLE
Invoke correct CMake when building tsan libdispatch

### PR DESCRIPTION
**Pull request by edymtt**
This should address a build failure on TSAN - libdispatch Linux bots

Addresses rdar://88339546

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci please python lint

**Comment by edymtt** [comment]
preset=buildbot_incremental_linux,tsan-libdispatch-test
@swift-ci Please test with preset Linux Platform

**Comment by buttaface** [comment]
Btw, the CI no longer runs the libdispatch or tsan tests because of a pull six months ago, reported in SR-11568.

**Comment by edymtt** [comment]
Thanks for the pointers, I was not fully aware for the context.

For now I will focus on the immediate failure, so to be in a position in which we can tackle the deeper issue.

**Comment by edymtt** [comment]
@swift-ci please python lint

**Comment by edymtt** [comment]
preset=buildbot_incremental_linux,tsan-libdispatch-test
@swift-ci Please test with preset Linux Platform

**Comment by edymtt** [comment]
@swift-ci Please smoke test and merge

**Comment by yln** [comment]
> Btw, the CI no longer runs the libdispatch or tsan tests because of a pull six months ago, reported in [SR-11568](https://bugs.swift.org/browse/SR-11568).

I've confirmed that the config is up and running again:
https://ci.swift.org/view/Dashboard/job/oss-swift-tsan-libdispatch-linux-ubuntu-18_04/

Note that we are only running the intersection of `TSan/compiler-rt + Linux + libdispatch` (no Swift) tests.  This config is meant to protect agains issues that would only show with the version of libdispatch used on Linux (compiled from source), but not with the system-provided one (Apple platforms).  We have end-to-end "TSan for Swift on Linux" in the Swift repo.
```
Testing Time: 3.25s
  Excluded: 398
  Passed  :  37
```

So since there is no Swift testing, we can ignore the few `build-script-impl` at the bottom that do nothing.

**Comment by buttaface** [comment]
Just to be clear, I'm talking about the normal linux CI that runs 15k tests from the compiler validation suite on every pull, eg [all tsan tests are now disabled for a recent CI run](https://ci.swift.org/job/swift-PR-Linux-smoke-test/35/console) because they depend on libdispatch.

I was unaware of this separate `swift-tsan-libdispatch-linux-ubuntu-18_04` CI bot that @yln now points out, that apparently runs 30-40 tests a couple times per day? If it's been decided that's enough and there's no need to run these libdispatch and tsan tests for every pull, I'll close that bug report I reopened.

**Comment by yln** [comment]
Thanks for clarifying this; I was confused.  Both should be running!
So basically we are not running any tests with `REQUIRES: libdispatch` on Linux CI; that's not just TSan tests and should be fixed.
@edymtt: can you help with repairing this again?

**Pull request merged**
