### PR TITLE
[IRGen] Fix 32-bit ARM extra inhabitant logic

### PR DESCRIPTION
**Pull request by davezarzycki**
This reverts:
89768cb3a3796f262bb5f263ec7920f7745af041
06b566f269394bf773464fb1791e27412237ad8f

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please test platform

**Review by rjmccall — APPROVED** [review]
Oops, thanks.

I would really like to completely eliminate the possibility of this kind of bug by having a target-assumptions database that exhaustively generates both `System.h` and the initialization code in `SwiftTargetInfo.cpp`.  Do you have any interest in working on that?  I think it's actually a good match for TableGen for once.

**Comment by davezarzycki** [comment]
@please test

**Comment by davezarzycki** [comment]
@swift-ci please test

**Comment by davezarzycki** [comment]
Hi @rjmccall – Do you have a bug tracking the TableGen idea? I'd be happy to follow it. Otherwise, I don't see myself having the time to work on that in the foreseeable future, nor do I see it blocking my work.

**Comment by rjmccall** [comment]
Just thought I'd ask. :)

**Pull request merged**
