### PR TITLE
Fix disable-arc-opts flag.

### PR DESCRIPTION
**Pull request by jray319**
Fix disable-arc-opts flag to be correctly applied.

### CODE REVIEW

**Comment by jray319** [comment]
@swift-ci please test

**Comment by gottesmm** [comment]
LGTM.

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Review by gottesmm — APPROVED** [review]

**Comment by CodaFi** [comment]
Thanks for your changes here @jray319.  We managed to pick them up in #28215.  Closing this out.

**Pull request closed without merging**
