### PR TITLE
[AutoDiff upstream] Add `inout` parameter differentiation tests.

### PR DESCRIPTION
**Pull request by dan-zheng**
Upstream tests from `tensorflow` branch: [`test/AutoDiff/downstream/inout_parameters.swift`](https://github.com/apple/swift/blob/tensorflow/test/AutoDiff/downstream/inout_parameters.swift).

### CODE REVIEW

**Comment by dan-zheng** [comment]
cc @efremale

**Comment by dan-zheng** [comment]
@swift-ci Please test

**Review by rxwei — APPROVED** [review]
LGTM, but I can't find any tests where the inout parameter's type is a generic parameter.

**Comment by dan-zheng** [comment]
Yes, more test coverage would be ideal. Let's merge these for now.

**Comment by efremale** [comment]
It seems the first 4 tests ("Float.+=", "Float.-=", "Float.*=", "Float./=") are doing exactly the same thing (+= everywhere). We should fix that.

**Pull request merged**
