### PR TITLE
[stdlib] Backward compatibility fix for a flatMap on [String]

### PR DESCRIPTION
**Pull request by moiseev**
Since `String` started to conform to `Collection`, the `flatMap` with a
sequence returning closure is now a better match than the one that
relies on the optional promotion in this code:

```swift
[""].flatMap { $0 }
```

which results in the default type of this expression changing from
`[String]` to `[Character]`.

Restoring the old behavior in Swift 3 mode by adding a very explicit
overload.

Fixes: <rdar://problem/32024978>

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
@swift-ci Please Test Source Compatibility

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by moiseev** [comment]
@swift-ci Please Test Source Compatibility

**Comment by moiseev** [comment]
@swift-ci Please Test Source Compatibility

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by Coeur** [comment]
>Fixes: rdar://problem/32024978
Can someone fill http://www.openradar.me/32024978 or provide a public resource?

**Comment by moiseev** [comment]
@Coeur The description of this PR explains it, doesn't it?

The following code:

```swift
struct S { var p: String }

func f(xs: [S]) -> [String] {
   return xs.flatMap { $0.p }
}
```

would not compile once `String` becomes `Collection` without this fix, with the error being something like 'cannot convert `[Character]` to return type `[String]`'.

**Pull request merged**
