### PR TITLE
[5.1] Add diagnostics for incorrect property wrapper references in function arguments 

### PR DESCRIPTION
**Pull request by sl**
Cherry pick commit from #25889

Resolves [SR-10928](https://bugs.swift.org/browse/SR-10928).

### CODE REVIEW

**Comment by sl** [comment]
@swift-ci please test

**Comment by sl** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test

**Pull request merged**
