### PR TITLE
Don't change the token kind of `yield` until we commit to a statement.

### PR DESCRIPTION
**Pull request by rjmccall**
Per Rintaro's code review in #18156.

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please smoke test.

**Review by rintaro — APPROVED** [review]
LGTM, thank you!

**Comment by rjmccall** [comment]
@swift-ci Please smoke test OS X.

**Comment by rjmccall** [comment]
@swift-ci Please test OS X.

**Comment by rjmccall** [comment]
(Mishal killed the full build because I'd only started it as part of flailing against the bots, which were down.)

**Pull request merged**
