### PR TITLE
Use new noncopyable types infrastructure

### PR DESCRIPTION
**Pull request by kavon**
depends on https://github.com/apple/llvm-project/pull/8384

This PR switches the compiler over to use the infrastructure underpinning NoncopyableGenerics, without actually enabling that experimental feature. This means the compiler can take advantage of the newer, better diagnostics that are now the same whether you enable the feature or not. Overall this is meant to be an NFC.

As a result of using the new infrastructure, it's possible to remove a bunch of old scaffolding code that was used either for the old or new infrastructure. For example, we no longer need a special flag in the control block of the swiftmodule to indicate whether it was compiled with NoncopyableGenerics infrastructure, since it's just always used as of this new module version.

### CODE REVIEW

**Comment by kavon** [comment]
@swift-ci smoke test

**Comment by kavon** [comment]
https://github.com/apple/llvm-project/pull/8384
@swift-ci smoke test

**Comment by kavon** [comment]
https://github.com/apple/llvm-project/pull/8384
@swift-ci smoke test

**Comment by kavon** [comment]
https://github.com/apple/llvm-project/pull/8384
@swift-ci test

**Comment by kavon** [comment]
https://github.com/apple/llvm-project/pull/8384
@swift-ci smoke test

**Comment by kavon** [comment]
https://github.com/apple/llvm-project/pull/8384
@swift-ci smoke test

**Comment by kavon** [comment]
https://github.com/apple/llvm-project/pull/8384
@swift-ci test

**Comment by kavon** [comment]
https://github.com/apple/llvm-project/pull/8384
@swift-ci test

**Comment by kavon** [comment]
https://github.com/apple/llvm-project/pull/8384
@swift-ci smoke test

**Comment by kavon** [comment]
https://github.com/apple/llvm-project/pull/8384
@swift-ci Please clean smoke test

**Comment by kavon** [comment]
https://github.com/apple/llvm-project/pull/8384
@swift-ci smoke test

**Comment by kavon** [comment]
https://github.com/apple/llvm-project/pull/8384
@swift-ci smoke test

**Comment by lorentey** [comment]
https://github.com/apple/llvm-project/pull/8384
@swift-ci smoke test macOS platform

**Comment by kavon** [comment]
https://github.com/apple/llvm-project/pull/8384
@swift-ci smoke test macOS platform

**Comment by kavon** [comment]
https://github.com/apple/llvm-project/pull/8384
@swift-ci smoke test linux

**Comment by kavon** [comment]
https://github.com/apple/llvm-project/pull/8384
@swift-ci smoke test windows

**Pull request merged**
