### PR TITLE
AST: Reconstitute sugar types deeply.

### PR DESCRIPTION
**Pull request by nkcsgexi**
@slavapestov do you have any objection to this?

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by slavapestov** [comment]
LGTM

**Comment by jrose-apple** [comment]
This broke SIL printing; please make sure we don't do it in SIL mode.

**Comment by jrose-apple** [comment]
Sorry, not this commit specifically, but whatever started calling reconstituteSugar in printing.

**Comment by nkcsgexi** [comment]
Another merged commit preserves the original behavior. https://github.com/apple/swift/commit/383b0abd628fbb4d039f992a8181ebdcb6d3d4bb

**Comment by slavapestov** [comment]
@jrose-apple It's actually not even specific to SIL printing, we just can't parse `[Foo : Bar].Index`, apparently.

**Comment by jrose-apple** [comment]
That's unfortunate but not surprising, but even on top of that it seems like SIL printing shouldn't use sugar.

**Comment by slavapestov** [comment]
Most of the types printed in SIL are canonical types, but replacement types in SubstitutionLists are not canonical apparently, so you'll see sugared types pop up occasionally in generic apply instructions and so on. It usually works :)

**Pull request merged**
