### PR TITLE
[Tests] Remove `no_asserts` from sema perf tests

### PR DESCRIPTION
**Pull request by davezarzycki**
This discourages regressions. Also add a timeout to a slow test.

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Review by xedin — APPROVED** [review]
Thank you! Do you know how much longer did the CI take after these changes?

**Comment by davezarzycki** [comment]
I didn’t notice the test suite taking longer.

**Comment by xedin** [comment]
Even better! :)

**Comment by davezarzycki** [comment]
Well with enough cores, the time to run the validation suite is equal to the longest test, so lots of short tests can fit into the leftover time. Given that the IDE tests are needlessly serial and painfully quadratic, there is plenty of leftover time. ;-)

**Comment by brentdax** [comment]
This seems to have broken one of our ASAN bots: https://ci.swift.org/job/oss-swift-incremental-ASAN-RA-osx/4023/

**Comment by davezarzycki** [comment]
@brentdax - I think an argument can be made that the sanitizers and performance testing don't get along. The former have huge and variable slowdown rates and the latter don't compensate. Therefore I'll just add `no_asan` to the `REQUIRES` line.

**Comment by xedin** [comment]
@davezarzycki I would be great if you could file a JIRA for the broken test so we can keep track of that and add `no_asan` to requires. Running this perf tests in ASAN configuration doesn't make much sense.

**Comment by davezarzycki** [comment]
https://bugs.swift.org/browse/SR-11751
https://bugs.swift.org/browse/SR-11752
https://bugs.swift.org/browse/SR-11753

**Pull request merged**
