### PR TITLE
Importer support for float80

### PR DESCRIPTION
**Pull request by stephentyrone**
Teach the importer to map between C's `long double` type and `Float80` on non-Windows x86_64 and i386 platforms, and take advantage of this mapping to clean up a few details in the stdlib.

This also makes available the full set of platform math functions for `Float80`.

Resolves [SR-2046](https://bugs.swift.org/browse/SR-2046).

### CODE REVIEW

**Comment by stephentyrone** [comment]
@swift-ci Please test.

**Comment by jrose-apple** [comment]
Importer side looks good, and none of the rest looks like anything alarming.

**Comment by vivkong** [comment]
Got a build failure on Linux on Z (s390x) related to this commit:
```
/home/swiftbuild/workspace/Swift/CONFIG/FIVE/GIT_BRANCH/master/label/csz25097/swift/stdlib/public/Platform/tgmath.swift.gyb:207:34: error: 'Float80' is unavailable: Float80 is only available on non-Windows x86 targets.
09:08:10 public func cos(_ x: Float80) -> Float80 {
09:08:10                                  ^~~~~~~
09:08:10 Swift.Float80:2:15: note: 'Float80' has been explicitly marked unavailable here
09:08:10 public struct Float80 {
09:08:10               ^
09:08:10 /home/swiftbuild/workspace/Swift/CONFIG/FIVE/GIT_BRANCH/master/label/csz25097/swift/stdlib/public/Platform/tgmath.swift.gyb:207:22: error: 'Float80' is unavailable: Float80 is only available on non-Windows x86 targets.
09:08:10 public func cos(_ x: Float80) -> Float80 {
09:08:10                      ^~~~~~~
09:08:10 Swift.Float80:2:15: note: 'Float80' has been explicitly marked unavailable here
09:08:10 public struct Float80 {
09:08:10               ^
```

**Comment by jrose-apple** [comment]
Looks like Steve forgot one of the `#if` blocks, the one for `OverlayFloatTypes`. Feel free to put up a PR for that if you don't want to wait for him.

**Comment by vivkong** [comment]
ah OK.  I have a patch ready.  Will create a PR.  Thanks @jrose-apple!

**Comment by stephentyrone** [comment]
Great, thanks @vivkong! I'm happy to review.

**Review by ricksentam — COMMENTED** [review]
@stephentyrone 

- [ ] #37189 



>

**Pull request merged**
