### PR TITLE
Generalize storage implementations to support generalized accessors

### PR DESCRIPTION
**Pull request by rjmccall**
The storage kind has been replaced with three separate "impl kinds", one for each of the basic access kinds (read, write, and read/write).  This makes it far easier to mix-and-match implementations of different accessors, as well as subtleties like implementing both a setter and an independent read/write operation.

AccessStrategy has become a bit more explicit about how exactly the access should be implemented.  For example, the accessor-based kinds now carry the exact accessor intended to be used.  Also, I've shifted responsibilities slightly between AccessStrategy and AccessSemantics so that AccessSemantics::Ordinary can be used except in the sorts of semantic-bypasses that accessor synthesis wants.  This requires knowing the correct DC of the access when computing the access strategy; the upshot is that SILGenFunction now needs a DC.

Accessor synthesis has been reworked so that only the declarations are built immediately; body synthesis can be safely delayed out of the main decl-checking path.

### CODE REVIEW

**Comment by rjmccall** [comment]
Please test with following pull request:
https://github.com/apple/swift-lldb/pull/722

@swift-ci Please smoke test.

**Comment by rjmccall** [comment]
Please test with following pull request:
apple/swift-lldb#722

@swift-ci Please smoke test.

**Comment by rjmccall** [comment]
Please test with following pull request:
apple/swift-lldb#722

@swift-ci Please smoke test.

**Comment by rjmccall** [comment]
Please test with following pull request:
apple/swift-lldb#722

@swift-ci Please smoke test.

**Comment by rjmccall** [comment]
Please test with following pull request:
apple/swift-lldb#722

@swift-ci Please smoke test.

**Comment by rjmccall** [comment]
Please test with following pull request:
apple/swift-lldb#722

@swift-ci Please smoke test.

**Comment by rjmccall** [comment]
Please test with following pull request:
apple/swift-lldb#722

@swift-ci Please smoke test.

**Comment by atrick** [comment]
PR #17623 may result in a manual merge for the SILGen LValue access scope stuff.

**Comment by rjmccall** [comment]
Please test with following pull request:
apple/swift-lldb#722

@swift-ci Please test.

**Comment by rjmccall** [comment]
Please test with following pull request:
apple/swift-lldb#722

@swift-ci Please test.

**Comment by rjmccall** [comment]
Please test with following pull request:
apple/swift-lldb#722

@swift-ci Please test.

**Pull request merged**
