### PR TITLE
Enable CxxStdlib on Windows

### PR DESCRIPTION
**Pull request by compnerd**
This improves the C++ interop support on Windows by mitigating a clang issue in the build system when building natively and enables the CxxStdlib module.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/220

@swift-ci please build toolchain Windows platform

**Review by egorzhdan — APPROVED** [review]
This is awesome! Thank you @compnerd!

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/220

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
Okay, seems that packaging is not yet ready for this.  I am going to merge this anyway - we just won't be distributing the files for now.  This should at least give us some coverage from the testing side.

**Comment by compnerd** [comment]
Bleh, seems that rebase is not enabled, okay, then I'll split this up.  The underlying change is the one that should resolve the issue that @eeckstein hit, the top most commit needs a bit more tweaking anyway to ensure that we don't collide on things.

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/220

@swift-ci please build toolchain Windows platform

**Review by egorzhdan — APPROVED** [review]

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/220

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Pull request merged**
