### PR TITLE
 [CodeCompletion] Completion for UnresolvedMember via CodeCompletionExpr

### PR DESCRIPTION
**Pull request by rintaro**
Using dummy `UnresolvedMemberExpr` doesn't give us much benefit. Instead, use    `CodeCompletionExpr` which is type checked as type variable so we can use `CodeCompletionTypeContextAnalyzer` to infer context types.
This way, we can eliminate most of special logic for `CompletionKind::UnresolvedMember`.

rdar://problem/39098974
rdar://problem/42828673

### CODE REVIEW

**Comment by slavapestov** [comment]
Nice!

**Review by benlangmuir — APPROVED** [review]
This is a huge improvement! Thanks!

**Comment by xedin** [comment]
I have recently talked to @nathawes about this too!

**Comment by davezarzycki** [comment]
This pull request introduced a `-Wself-assign-overload` warning (`Status |= Status` in ParseStmt.cpp). Was this intentional?

**Comment by rintaro** [comment]
@davezarzycki Ah, thank you! it's not intentional. I'll fix it.

**Comment by rintaro** [comment]
https://github.com/apple/swift/pull/18666

**Pull request merged**
