### PR TITLE
[windows] Provide a symlink alternative for Windows.

### PR DESCRIPTION
**Pull request by drodriguez**
Python 2.7 in Windows do not have os.symlink. Provide one by using Win32
API, and try to match the behaviour that seems to be implied by the Unix
implementation (meaning, the destination is removed before the symlink
is created).

Before this change, calling update-checkout.cmd in Windows will have failed when os.symlink was used.

This is not used by the build script at the moment, but people might use the script in Windows to update their local copies. Sadly creating symlinks in Windows require the user to be Administrators, but that's also a requirement for adapting the Windows SDK to be used modularly, so developers should be already setup.

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci clean smoke test

**Comment by shahmishal** [comment]
@swift-ci test Windows

**Review by shahmishal — APPROVED** [review]

**Comment by drodriguez** [comment]
The Windows tests are failing, btw, so there is not going to be a green build there (at the end there's something about a "Error 87" or something like that). Also, this part is not exercised during the build process at the moment.

**Comment by drodriguez** [comment]
@swift-ci clean smoke test

**Pull request merged**
