### PR TITLE
Single payload enum reflection

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test and merge

**Comment by jckarter** [comment]
Nice!

**Comment by slavapestov** [comment]
@swift-ci Please test and merge

**Comment by slavapestov** [comment]
@swift-ci Please test and merge

**Comment by slavapestov** [comment]
I've already tested this several times and hit typos in the Linux test. Now the test passes so I'm merging this directly.

**Pull request merged**
