### PR TITLE
[scale-test] numerical nonlinear regression, avoids linear(log()) mis-fitting

### PR DESCRIPTION
**Pull request by graydon**
This implements Nelder-Mead simplex nonlinear optimization for fitting polynomial and exponential models to scale-test input, replacing the previous approach of doing linear regression in log-space (which broke down when there were constant offsets to the data -- unfortunately quite common).

It doesn't use numpy (which is why it's manual and wonky) but it does seem to more-or-less work; NM is unstable and sensitive to initial guesses so we have to do a few retries before giving up sometimes, but in practice it seems to hit a usable simplex within a few tries on most data.

Feedback/improvements welcome. I included a handful of test vectors which succeed on this, some of which failed on the older linear-regression-in-log-space scheme. Probably there's still a bunch of room for improvement though; this kinda stuff isn't super familiar territory for me.

### CODE REVIEW

**Comment by gottesmm** [comment]
@graydon This sounds like a question for @stephentyrone!

**Comment by graydon** [comment]
@swift-ci please test

**Review by huonw — APPROVED** [review]
Amazing! My only problems with this PR are some minor code style and that I didn't get to write it.

**Comment by graydon** [comment]
@swift-ci please test and merge

**Comment by huonw** [comment]
@swift-ci please test and merge

**Comment by graydon** [comment]
@swift-ci please test and merge

**Comment by graydon** [comment]
@swift-ci please test and merge

**Pull request merged**
