### PR TITLE
[4.0] Fix a bug related to handling of self-recursive apply and partial_apply instructions by TypeSubstCloner and generic specializer

### PR DESCRIPTION
**Pull request by swiftix**
Description: TypeSubstCloner and generic specializer would produce incorrect SIL for applies and partial_applies, especially for self-recursive functions. Types and number of arguments may get wrong in such cases.

Scope of the issue: SIL optimizer would produce SIL which does not pass the SIL verifier or crash the compiler later if verifier is disabled. Some internal projects are affected by this issue. Potentially it can happen on any code with self-recursive functions when it is optimized with -O.
Origination: Bug reports on internal projects (rdar://31899989 and rdar://31886854)

Risk: Low. The majority of the code is re-factoring, which among other things removes the possibility to provide wrong types when constructing different kinds of apply instructions. Plus it introduces stricter checks in the TypeSubstCloner for self-recursive functions.

Tested: New test cases added. Internal projects successfully build with these changes.

Reviewed by: Erik Eckstein and Slava Pestov

Resolves: rdar://31899989 and rdar://31886854

### CODE REVIEW

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by swiftix** [comment]
@slavapestov Slava, can you please review for CCC? This PR is basically the combined PR consisting of #9460 and #9470, which you looked at yesterday. I combined them, because #9460 depends on #9470 anyways.

**Comment by slavapestov** [comment]
LGTM.

**Comment by swiftix** [comment]
Approved by Ted

**Pull request merged**
