### PR TITLE
Demangle function names in remarks

### PR DESCRIPTION
**Pull request by anemet**

### CODE REVIEW

**Comment by anemet** [comment]
@swift-ci Please smoke test

**Comment by anemet** [comment]
@swift-ci Please smoke test

**Comment by anemet** [comment]
@swift-ci Please smoke test

**Comment by anemet** [comment]
@swift-ci Please smoke test

**Comment by anemet** [comment]
@eeckstein, does this look good to you?  Particularly using Demangling from lib/SIL.  It's already used by the lib/SIL/SILPrinter but I want to make sure I am not violating some layering constraints.

**Comment by eeckstein** [comment]
Looks good. They only thing you have to decide if you want to print the full demangled named (which is often unreadable) or the simplified demangled named (which might be ambiguous).

**Comment by anemet** [comment]
Thanks for the suggestion, @eeckstein.  I went with simplified name.

**Comment by anemet** [comment]
@swift-ci Please smoke test and merge

**Comment by anemet** [comment]
@swift-ci Please smoke test and merge

**Comment by anemet** [comment]
@swift-ci Please smoke test and merge

**Comment by anemet** [comment]
@swift-ci Please smoke test and merge

**Comment by anemet** [comment]
@swift-ci Please smoke test

**Comment by shahmishal** [comment]
@anemet Please re-trigger the request, ci.swift.org was down during your request.

**Comment by anemet** [comment]
@swift-ci Please smoke test and merge

**Pull request merged**
