### PR TITLE
[Syntax] Split ActorDecl into its own syntax node apart from ClassDecl.

### PR DESCRIPTION
**Pull request by DougGregor**

### CODE REVIEW

**Comment by DougGregor** [comment]
https://github.com/apple/swift-syntax/pull/496
@swift-ci please smoke test

**Comment by DougGregor** [comment]
https://github.com/apple/swift-syntax/pull/496
@swift-ci please smoke test

**Comment by DougGregor** [comment]
https://github.com/apple/swift-syntax/pull/496
@swift-ci please smoke test

**Comment by DougGregor** [comment]
https://github.com/apple/swift-syntax/pull/496
@swift-ci please smoke test

**Comment by ktoso** [comment]
Awesome!

Tho internally we're still going to be matching on ClassDecl or going to change that as well soon?

**Review by ktoso — APPROVED** [review]

**Review by ahoppen — APPROVED** [review]

**Comment by DougGregor** [comment]
https://github.com/apple/swift-syntax/pull/496
@swift-ci please smoke test macOS

**Comment by DougGregor** [comment]
https://github.com/apple/swift-syntax/pull/496
@swift-ci please clean test macOS

**Comment by DougGregor** [comment]
Subsumed by https://github.com/apple/swift/pull/60052

**Pull request closed without merging**
