### PR TITLE
Perform substitution on conformances if we are supposed to substitute…

### PR DESCRIPTION
**Pull request by aschwaighofer**
… opaque archetypes

rdar://50413632

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
This should also have a test case :)

**Comment by slavapestov** [comment]
Also this smells like a bug in ProtocolConformance::subst(). I don't even understand why we have two separate code paths in this function.

**Comment by slavapestov** [comment]
Is it because ProtocolConformanceRef::subst() takes SubstOptions but ProtocolConformance::subst() does not?

**Comment by aschwaighofer** [comment]
Yes. The problem this patch fixes is that opaque archetypes were not substituted in the conformance. The call to ProtocolConformance::subst()  does not take options.

**Comment by slavapestov** [comment]
Do you mind fixing the root cause then? It should be easy to plumb the options in.

**Comment by aschwaighofer** [comment]
I will follow up on this later.

**Pull request merged**
