### PR TITLE
[Test] Removed unneeded check lines.

### PR DESCRIPTION
**Pull request by nate-chandler**
The lines are irrelevant to the test and are currently failing on 32bit.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please smoke test

**Comment by kateinoigakukun** [comment]
@swift-ci test WebAssembly

**Comment by nate-chandler** [comment]
@swift-ci test WebAssembly

**Comment by nate-chandler** [comment]
@swift-ci please smoke test

**Comment by kateinoigakukun** [comment]
Hmm, still failing 
```
--
/home/build-user/swift/test/IRGen/moveonly_value_functions_onone.swift:304:16: error: CHECK-SAME: expected string not found in input
// CHECK-SAME: i64 0, 
               ^
<stdin>:1326:115: note: scanning from here
 %19 = call swiftcc %swift.metadata_response @"$s30moveonly_value_functions_onone26InnerDeinitingReleasableNCVMa"(i32 0, ptr %T) #16
                                                                                                                  ^
```

**Comment by kateinoigakukun** [comment]
I had time to address the remaining issue: https://github.com/apple/swift/pull/72054

**Comment by nate-chandler** [comment]
Thanks!

**Pull request merged**
