### PR TITLE
[NFC] GenericSignatureImpl: Spell conformsToProtocol & getConformsTo in terms of requirements

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
Make it clear that only abstract conformances are of interest to these methods.

### CODE REVIEW

**Comment by AnthonyLatsis** [comment]
Huh, does git always mark adjacent changes as conflicting?

**Review by slavapestov — APPROVED** [review]

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test and merge

**Review by CodaFi — APPROVED** [review]

**Comment by CodaFi** [comment]
You'll need to give this one more rebase after the const-ification patches.

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test Linux

**Comment by AnthonyLatsis** [comment]
@swift-ci please clean smoke test OS X

**Pull request merged**
