### PR TITLE
Require @usableFromInline on associated type witnesses

### PR DESCRIPTION
**Pull request by jrose-apple**
...when the protocol and the conforming type are not both public but are both public-or-usableFromInline. It's possible to write inlinable functions that depend on these types:

```
public protocol HasAssoc {
  associatedtype Assoc
}
public func getAssoc<T: HasAssoc>(_: T) -> T.Assoc

@usableFromInline struct Impl: HasAssoc {
  @usableFromInline typealias Assoc = Int
}

@inlinable func test() {
  let x: Int = getAssoc(Impl())
}
```

rdar://problem/43824052

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by jrose-apple** [comment]
@swift-ci Please benchmark

**Review by slavapestov — APPROVED** [review]

**Review by lorentey — APPROVED** [review]
Good catch!

**Review by harlanhaskins — APPROVED** [review]

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Pull request merged**
