### PR TITLE
[sourcekit] Add optional compile notifications

### PR DESCRIPTION
**Pull request by benlangmuir**
When enabled, send a notification before/after every "compilation", which for now means `performSema`. This piggy-backs and modifies some existing code that we had for "tracing" operations in sourcekitd that unfortunately was untested.  At least now some of the basic parts are tested via the new notifications.
    
Part of rdar://38438512

### CODE REVIEW

**Comment by benlangmuir** [comment]
@swift-ci please smoke test

**Comment by benlangmuir** [comment]
Oh, the linux one is more interesting.  I didn't realize we didn't build the -InProc.cpp file on macOS (I guess on macOS the in-process sourcekit still uses xpc serialization).

**Comment by benlangmuir** [comment]
@swift-ci please smoke test

**Review by nkcsgexi — APPROVED** [review]
Looking good! A general question: why do we make the configuration change a new request rather than an option in actual requests?

**Comment by benlangmuir** [comment]
@nkcsgexi that would be awkward because when the ASTManager causes a compile it is not tied to any specific request.

**Comment by nkcsgexi** [comment]
ah, I see. Thank you for clarification!

**Pull request merged**
