### PR TITLE
optimize flag computation

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @drexin @gottesmm

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by compnerd** [comment]
@swift-ci please test windows platform

**Comment by compnerd** [comment]
@swift-ci please smoke test Linux platform

**Comment by compnerd** [comment]
@swift-ci please smoke test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Review by drexin — APPROVED** [review]

**Comment by rintaro** [comment]
@compnerd This probably caused build failures
https://ci.swift.org/job/oss-swift-incremental-RA-osx/11636
https://ci.swift.org/job/oss-swift-incremental-RA-linux-ubuntu-16_04/13293
This change removed these dependencies from the gyb generated files
https://github.com/apple/swift/blob/3789b6eb357993e31e86b0e30d79eb0570d4a87c/cmake/modules/SwiftHandleGybSources.cmake#L111-L134

**Pull request merged**
