### PR TITLE
swift-api-digester: fix recently found false positives. 

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by jrose-apple** [comment]
I'm not sure "the same printed name" is good enough unless you're printing canonical types.

**Comment by jrose-apple** [comment]
Or is it okay because those will be listed as a difference elsewhere?

**Comment by nkcsgexi** [comment]
We just avoid printing them to the final output. We can always dig into the type and figure out what indeed has changed. This patch is mostly about reducing unnecessary information in current settings.

**Pull request merged**
