### PR TITLE
Do not merge: test PR for Swift-LMDB #5

### PR DESCRIPTION
**Pull request by franklinsch**
Test PR for https://github.com/apple/swift-lmdb/pull/5#issuecomment-1851810033

### CODE REVIEW

**Comment by franklinsch** [comment]
Please test with following pull request:
https://github.com/apple/swift-lmdb/pull/5

@swift-ci please test

**Comment by franklinsch** [comment]
Please test with following pull request:
https://github.com/apple/swift-lmdb/pull/5

@swift-ci Please Build Toolchain macOS Platform

**Comment by franklinsch** [comment]
Please test with following pull request:
https://github.com/apple/swift-lmdb/pull/5

@swift-ci Please Build Toolchain Linux Platform

**Comment by hassila** [comment]
I think the Linux failure is due to this:

https://github.com/apple/swift-package-manager/pull/7188

**Comment by franklinsch** [comment]
@daniel-grumberg Any feedback on this PR?

**Comment by hassila** [comment]
Can probably close this issue as the one under test has been merged.

**Pull request closed without merging**
