### PR TITLE
[OpaqueValues] Initial support for AD.

### PR DESCRIPTION
**Pull request by nate-chandler**
Just enough to build `_Differentiation`.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Review by atrick — COMMENTED** [review]
Wow! I'm not qualified to review the AD SILGen. But I'm glad you did this because the AD people were the ones who really wanted opaque values when they started... years ago. presumably it could simplify the representation

**Comment by rxwei** [comment]
Oh thank you, we absolutely still want this!

cc @BradLarson @asl

**Pull request merged**
