### PR TITLE
Support for copy-on-write existentials - IRGen Support

### PR DESCRIPTION
**Pull request by aschwaighofer**
This adds non-witness implementation of copy-on-write opaque existentials to IRGen.

Missing is the runtime support.

All this is hidden behind the CMake flag 'SWIFT_RUNTIME_ENABLE_COW_EXISTENTIALS' and the compiler frontend flag '-enable-cow-existentials'.

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please clean test

**Comment by dabrahams** [comment]
🎉

**Comment by aschwaighofer** [comment]
@swift-ci Please clean test

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test

**Comment by aschwaighofer** [comment]
@swift-ci Please clean test

**Pull request merged**
