### PR TITLE
[SourceKit] Link SwiftCompilerModules to SourceKit

### PR DESCRIPTION
**Pull request by rintaro**
This is required for SourceKit to parse Regex literals

Also link it to `swift-ide-test` too, to test IDE functionalities for regex literals.

rdar://90236990

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by rintaro** [comment]
@swift-ci Please test macOS

**Comment by rintaro** [comment]
Hmm I can't reproduce the crash locally.
```
FAILED: lib/sourcekitd.framework/Versions/A/XPCServices/SourceKitService.xpc/Contents/MacOS/SourceKitService
...
0  0x107706970  __assert_rtn + 127
1  0x10770c3d6  ld::tool::OutputFile::writeAtoms(ld::Internal&, unsigned char*) (.cold.1) + 0
2  0x1076518d9  ld::tool::OutputFile::compressedOrdinalForAtom(ld::Atom const*) const + 335
3  0x107655df9  ld::tool::OutputFile::addDyldInfo(ld::Internal&, ld::Internal::FinalSection*, ld::Atom const*, ld::Fixup*, ld::Fixup*, ld::Fixup*, ld::Atom const*, ld::Atom const*, unsigned long long, unsigned long long) + 1523
4  0x107646901  ld::tool::OutputFile::generateLinkEditInfo(ld::Internal&) + 1149
5  0x107640304  ld::tool::OutputFile::write(ld::Internal&) + 116
6  0x1075bfc35  main + 747
A linker snapshot was created at:
	/tmp/SourceKitService-2022-02-29-232110.ld-snapshot
ld: Assertion failed: (0 && "dylib not assigned ordinal"), function compressedOrdinalForAtom, file OutputFile.cpp, line 4973.
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
@eeckstein Do you know what causes this error?

**Comment by rintaro** [comment]
@swift-ci Please test

**Review by eeckstein — APPROVED** [review]
lgtm

**Pull request merged**
