### PR TITLE
AST: Allocate FunctionTypes containing type variables in the solver arena

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test compiler performance

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Review by xedin — COMMENTED** [review]
Good catch!

**Comment by xedin** [comment]
@swift-ci Please test compiler performance

**Comment by slavapestov** [comment]
@swift-ci Please test compiler performance

**Comment by slavapestov** [comment]
@swift-ci Please test compiler performance

**Comment by slavapestov** [comment]
@swift-ci Please test compiler performance

**Comment by graydon** [comment]
@swift-ci Please clean test compiler performance

**Comment by graydon** [comment]
@swift-ci Please clean test compiler performance

**Comment by slavapestov** [comment]
@swift-ci Please test compiler performance

**Comment by slavapestov** [comment]
@swift-ci Please test compiler performance

**Comment by shahmishal** [comment]
@swift-ci Please test compiler performance

**Pull request merged**
