### PR TITLE
[SR-11540] Fix ambiguos overload apply to argument for contextual closure 

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
This fixes SR-11540 by just disfavoring overloads to closures with anonymous var that are function types with more than one argument that matches arguments of no-arg function types.

The first approach was to not accept cases like `func foo(<T, R>(action: (T) -> R) -> Void {})` match `foo(action: { return }`, in a way that:

```swift
func foo<T, R>(action: (T) -> R) -> Void {}
foo(action: { return }) // expected-error {{contextual type for closure argument list expects 1 argument, which cannot be implicitly ignored}}
// expected-error@-1 {{generic parameter 'T' could not be inferred}} expected-error@-1{{generic parameter 'R' could not be inferred}}

// Is expected to be foo(action: { _ in return }) 
```
But since it broke few tests(that was actually accepting this syntax) and I was not sure if this would be a source-compatible change... so opting to just disfavor the overload disambiguate seemed like a better option :) 

cc @xedin @hborla 

Resolves SR-11540.

### CODE REVIEW

**Comment by xedin** [comment]
@LucianoPAlmeida Do you know where `T := ()` binding comes from for `<T, R>(action: (T) -> R)` overload?

**Comment by LucianoPAlmeida** [comment]
Hey @xedin :) 

> @LucianoPAlmeida Do you know where `T := ()` binding comes from for `<T, R>(action: (T) -> R)` overload?

Not really, I thought that for closures with implicit parameters, it automatically always tried to bind an empty tuple '()' by default ... 

For the 
```swift
func SR11540_1<T, R>(action: (T) -> R) -> Void {} 
SR11540_1(action: { return }) // OK
```
The source locator binding points to the call expr ... 
```
Resolved overloads:
  selected overload set choice SR11540_1: $T0 == (($T1) -> $T2) -> Void


Opened types:
  locator@0x11b8dae00 [DeclRef@/Users/lucianoalmeida/Documents/Programming/swift-lang/swift/test/expr/closure/sr9839.swift:12:1] opens τ_0_1 -> $T2, τ_0_0 -> $T1
  ($T3 involves_type_vars bindings={(subtypes of) ($T1) -> $T2})
  Initial bindings: $T3 := ($T1) -> $T2
  (attempting type variable $T3 := ($T1) -> $T2
    (increasing score due to disfavored overload)
    ($T1 potentially_incomplete bindings={(subtypes of) ()})
    ($T4 involves_type_vars bindings={(supertypes of) ()})
    Initial bindings: $T1 := ()
    (attempting type variable $T1 := ()
(lldb) p srcLocator->getAnchor()
(swift::Expr *) $2 = 0x000000011b8d4cb0
(lldb) p srcLocator->getAnchor()->dump()
(call_expr type='<null>' arg_labels=action:
  (declref_expr type='<null>' decl=sr9839.(file).SR11540_1(action:)@/Users/lucianoalmeida/Documents/Programming/swift-lang/swift/test/expr/closure/sr9839.swift:7:6 function_ref=single)
  (tuple_expr type='<null>' names=action
    (closure_expr type='<null>' discriminator=0 single-expression
      (parameter_list range=[/Users/lucianoalmeida/Documents/Programming/swift-lang/swift/test/expr/closure/sr9839.swift:12:19 - line:12:19])
      (tuple_expr implicit type='()'))))
(lldb) p Binding.isDefaultableBinding()
(bool) $3 = false
(lldb) p dstLocator->getAnchor()->dump()
(declref_expr type='<null>' decl=sr9839.(file).SR11540_1(action:)@/Users/lucianoalmeida/Documents/Programming/swift-lang/swift/test/expr/closure/sr9839.swift:7:6 function_ref=single)
(lldb) p Binding.BindingType->dump()
(tuple_type num_elements=0)
```

**Comment by xedin** [comment]
I think this is a side-effect of one of the hacks for SE-0110. Solver shouldn't be inferring bindings for parameters unless they are either used in the body, come from context or explicitly specified in closure declaration. Overload of `(T) -> R` matches neither situation so we really need to figure out how parameter gets to be inferred as `()`.

**Comment by LucianoPAlmeida** [comment]
> I think this is a side-effect of one of the hacks for SE-0110. Solver shouldn't be inferring bindings for parameters unless they are either used in the body, come from context or explicitly specified in closure declaration.

This situation should be caught at `matchFunctionTypes` I think ... but currently, because of some of that logic of imploding parameters (maybe SE-0110), a function type `()-> $T0` is matching correctly with a `($T1) -> $T2` for an `ArgumentConversion`, that's why I implemented such logic, because I thought that a closure function type with a least one param and with anonymous variables shouldn't be able to convert to an empty param function type. Really not sure about it ... I'm just going back to this right now ... let me see If I can find something else :)

**Comment by LucianoPAlmeida** [comment]
Hummm maybe the binding is coming from context of the closure ... 

So ... if we take that 
```swift
let c = { return }
// c is infered as () -> () 

// so the generic types T and R on  SR11540_1(action: { return }) 
func SR11540_1<T, R>(action: (T) -> R) -> Void {} 

```

Are infered by the type of closure of the param, that's where the `T := () `bind maybe comming from :))

**Comment by xedin** [comment]
> This situation should be caught at matchFunctionTypes I think...

That's exactly what needs to happen and it's not happening because `canImplodeParams` doesn't check the case of empty parameter list. Which, I think, is unfortunately intentional, we can increase a score upon trying to implode something into an empty list, that's going to be a much more narrow fix for this situation.

**Comment by xedin** [comment]
Or maybe go all in and actually increase `SK_FunctionConversion` score on any implode we have to do to support SE-0110 edge cases.

**Comment by LucianoPAlmeida** [comment]
> Or maybe go all in and actually increase `SK_FunctionConversion` score on any implode we have to do to support SE-0110 edge cases.

Awesome! Let's try this ... I'll ping you in a moment with the changes :))

**Comment by LucianoPAlmeida** [comment]
Right, just increase the score whenever we have to implode the parameters 👍 @xedin

**Review by xedin — APPROVED** [review]
LGTM!

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by LucianoPAlmeida** [comment]
Seems like a test broke ... let me check that

**Comment by LucianoPAlmeida** [comment]
Just adjusted the test case that was failing. Now local tests are OK :)

**Comment by xedin** [comment]
Sounds good! Make sense to me that it would type-check.

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by LucianoPAlmeida** [comment]
Thank you @xedin :)

**Comment by xedin** [comment]
No problem! :)

**Pull request merged**
