### PR TITLE
SILCombiner: Remove bogus dump() call

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by atrick** [comment]
@slavapestov you beat me to this by one minute. I had removed it on a branch and must not have pushed it.

**Review by atrick — APPROVED** [review]

**Comment by slavapestov** [comment]
Random lldb test timed out, not my fault:

```
02:14:24 TIMEOUT: test_swift_stepping_dwarf (lang/swift/stepping/TestSwiftStepping.py)

```

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Pull request merged**
