### PR TITLE
Teach class hierarchy analysis to recurse through superclasses in other files

### PR DESCRIPTION
**Pull request by rjmccall**
rdar://45110471

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Comment by slavapestov** [comment]
Is CHA useful at all in non-WMO mode? Perhaps we can skip it. It's going to be doing a quadratic amount of work, which we want to avoid. I don't think devirtualization asks anything of CHA except in WMO for example.

**Comment by rjmccall** [comment]
Apparently the mandatory inliner does do some amount of devirtualization.

I was pretty careful to avoid doing a quadratic amount of work, unless you mean the linear scan of the subclass list.

**Comment by slavapestov** [comment]
I just mean the duplication of work between frontend jobs.

**Comment by rjmccall** [comment]
Ah.  I didn't teach it to look at all classes in the module; I just taught it to walk the complete module-local ancestry of the classes in the current file, which is something I'm pretty sure we already do in a million places while compiling them.

It's possible that there could be a subclass in a different file that CHA won't know about after this change, but I think the limited used of CHA in that case should be fine.  The issue here is specifically that we're assuming that we know all possible overrides of the method because it's `fileprivate`, but that does require us to fully investigate all the classes in the current file, which we weren't in this weird situation.

**Comment by rjmccall** [comment]
The PR description could've been clearer about that, though.

**Pull request merged**
