### PR TITLE
Removed the "infer import as member" feature

### PR DESCRIPTION
**Pull request by gribozavr**
It was not launched since it was added in 2016. I don't think anyone has any intention to launch it, and therefore I believe it is dead code now.

### CODE REVIEW

**Comment by CodaFi** [comment]
Huh, nice find.

@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci test source compatibility

**Comment by CodaFi** [comment]
So, of course, we cannot actually remove this because there is one remaining adopter in the public SDK: 

```
System/Library/Frameworks/CoreGraphics.framework/Versions/A/Headers/CoreGraphics.apinotes
3:SwiftInferImportAsMember: true
```

Which is already called out in the code itself. Thankfully, that code also limits adoption to *only* CoreGraphics, so if we can patch up their APINotes then we can merge this PR. Let's leave this on the backburner just to have.

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
