### PR TITLE
Fix SILCombine of inject_enum_addr to correctly check for unreferenceable storage

### PR DESCRIPTION
**Pull request by meg-gupta**

### CODE REVIEW

**Review by atrick — APPROVED** [review]
LGTM

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Review by nate-chandler — APPROVED** [review]

**Comment by meg-gupta** [comment]
@swift-ci test swift source compatibility

**Comment by meg-gupta** [comment]
@swift-ci Please Test Source Compatibility

**Comment by meg-gupta** [comment]
All failures are unrelated

**Comment by meg-gupta** [comment]
@swift-ci smoke test linux platform

**Pull request merged**
