### PR TITLE
[build] Clean llbuild before building by default

### PR DESCRIPTION
**Pull request by edymtt**
Introduce a new parameter `--skip-llbuild-clean` to prevent this from
happening.

This mimicks similar logic in place for `swiftpm`, `swift-driver`
(#33563)  and `xctest` (#19512)

Addresses rdar://75057069

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci please smoke test

**Comment by edymtt** [comment]
@swift-ci please clean test Windows

**Review by shahmishal — APPROVED** [review]

**Comment by edymtt** [comment]
@swift-ci please smoke test

**Comment by edymtt** [comment]
@swift-ci please clean test Windows

**Review by compnerd — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please test Windows palatform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by edymtt** [comment]
@swift-ci please test Windows platform

**Comment by edymtt** [comment]
@swift-ci please smoke test Linux

**Comment by edymtt** [comment]
@swift-ci please test Windows platform

**Comment by edymtt** [comment]
@swift-ci please test Windows platform

**Comment by edymtt** [comment]
Windows PR testing failue is unrelated to this PR (VS2019 incremental bot is failing the same way)

**Pull request merged**
