### PR TITLE
[exclusivity] teach LICM how to handle static markers

### PR DESCRIPTION
**Pull request by shajrawi**
radar rdar://problem/47802266

### CODE REVIEW

**Comment by shajrawi** [comment]
@swift-ci Please smoke test and merge

**Comment by shajrawi** [comment]
@swift-ci Please clean smoke test Linux

**Comment by shajrawi** [comment]
@swift-ci Please smoke test Linux

**Comment by shajrawi** [comment]
```
16:45:16 Test Suite 'All tests' passed at 2019-03-14 23:45:16.070
16:45:16 	 Executed 1 test, with 0 failures (0 unexpected) in 0.001 (0.001) seconds
16:45:16 /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/swift-nightly-install/usr/bin/swift test --package-path /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/indexstore-db --build-path /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/buildbot_linux/indexstoredb-linux-x86_64 --configuration release --verbose -Xcxx -I -Xcxx /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/swift-nightly-install/usr/lib/swift
16:45:16 + /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/sourcekit-lsp/Utilities/build-script-helper.py build --verbose --package-path /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/sourcekit-lsp --build-path /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/buildbot_linux/sourcekitlsp-linux-x86_64 --configuration release --toolchain /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/swift-nightly-install
16:45:16 lsb_release -r
16:45:16 /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/swift-nightly-install/usr/bin/swiftc --driver-mode=swift -L /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/swift-nightly-install/usr/lib/swift/pm/4_2 -lPackageDescription -swift-version 4.2 -I /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/swift-nightly-install/usr/lib/swift/pm/4_2 -sdk / /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/sourcekit-lsp/Package.swift -fileno 8
16:45:16 /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/swift-nightly-install/usr/bin/swiftc --driver-mode=swift -L /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/swift-nightly-install/usr/lib/swift/pm/4_2 -lPackageDescription -swift-version 4.2 -I /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/swift-nightly-install/usr/lib/swift/pm/4_2 -sdk / /tmp/TemporaryFile.ZdCDpX.swift -fileno 7
16:45:17 /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/swift-nightly-install/usr/bin/swift build --package-path /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/sourcekit-lsp --build-path /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/buildbot_linux/sourcekitlsp-linux-x86_64 --configuration release --verbose -Xswiftc -enable-testing -Xcxx -I -Xcxx /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/swift-nightly-install/usr/lib/swift
16:45:17 Traceback (most recent call last):
16:45:17   File "/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/sourcekit-lsp/Utilities/build-script-helper.py", line 83, in <module>
16:45:17     main()
16:45:17   File "/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/sourcekit-lsp/Utilities/build-script-helper.py", line 76, in main
16:45:17     swiftpm('build', swift_exec, swiftpm_args, env)
16:45:17   File "/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/sourcekit-lsp/Utilities/build-script-helper.py", line 14, in swiftpm
16:45:17     subprocess.check_call(cmd, env=env)
16:45:17   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
16:45:17     raise CalledProcessError(retcode, cmd)
16:45:17 subprocess.CalledProcessError: Command '['/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/swift-nightly-install/usr/bin/swift', 'build', '--package-path', '/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/sourcekit-lsp', '--build-path', '/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/buildbot_linux/sourcekitlsp-linux-x86_64', '--configuration', 'release', '--verbose', '-Xswiftc', '-enable-testing', '-Xcxx', '-I', '-Xcxx', '/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/swift-nightly-install/usr/lib/swift']' returned non-zero exit status -4
```
@shahmishal any idea what that is?

**Comment by shahmishal** [comment]
/cc @benlangmuir @aciidb0mb3r 

We are seeing this on multiple PRs, is this issue with SwiftPM? 

```
Command '['/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/swift-nightly-install/usr/bin/swift', 'build', '--package-path', '/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/sourcekit-lsp', '--build-path', '/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/buildbot_linux/sourcekitlsp-linux-x86_64', '--configuration', 'release', '--verbose', '-Xswiftc', '-enable-testing', '-Xcxx', '-I', '-Xcxx', '/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/swift-nightly-install/usr/lib/swift']' returned non-zero exit status -4
```

**Comment by shahmishal** [comment]
@swift-ci test Linux

**Comment by benlangmuir** [comment]
@shahmishal I talked to @aciidb0mb3r and he mentioned it seems more likely it's coming from the swift compile.  The last compilation in the log is:

```
/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/swift-nightly-install/usr/bin/swiftc --driver-mode=swift -L /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/swift-nightly-install/usr/lib/swift/pm/4_2 -lPackageDescription -swift-version 4.2 -I /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-master/swift-nightly-install/usr/lib/swift/pm/4_2 -sdk / /tmp/TemporaryFile.ZdCDpX.swift -fileno 7
```

Which is for parsing the Package.swift file from one of the dependencies, IIUC.

**Comment by benlangmuir** [comment]
The latest failure is different: Expr/TestIRMemoryMap.test

**Comment by shajrawi** [comment]
because it is a full test instead of a smoke test. and lldb runs first. the test in question has nothing to do with this PR or Swift in general: `# RUN: %clangxx %p/Inputs/call-function.cpp -g -o %t`

**Comment by shajrawi** [comment]
@swift-ci Please smoke test Linux

**Review by atrick — COMMENTED** [review]
LGTM

**Pull request merged**
