### PR TITLE
[stdlib] Update the stdlib to use Unicode 15 data

### LINKED ISSUE #63754: Unicode.Scalar.Properties.isEmoji returns false for Unicode 15 emoji
**Description**

**Steps to reproduce**
```swift
let scalars: [Unicode.Scalar] = ["😎", "🩵", "💙", "🪼", "$", "A"]
for s in scalars {
    print(s, "-->", s.properties.isEmoji)
}
```

**Expected behavior**
The [isEmoji](https://developer.apple.com/documentation/swift/unicode/scalar/properties-swift.struct/isemoji) properties of Unicode 15.0 emoji (in this case, the teal heart and jellyfish) should return true. Instead, they return false.

Screenshot 2023-02-17 at 1 34 11 PM

**Environment**
- Swift compiler version info
```
swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: arm64-apple-macosx13.0
```
- Xcode version info:
```
Xcode 14.2
Build version 14C18
```
- Playgrounds version info used in this test: `Version 4.2.1 (1726.28)`
- Deployment target: iOS 16.4 DP1

### PR DESCRIPTION
**Pull request by Azoy**
Resolves: https://github.com/apple/swift/issues/63754, rdar://106954505, and rdar://100282762

### CODE REVIEW

**Comment by Azoy** [comment]
@swift-ci please test

**Comment by Azoy** [comment]
@swift-ci plese test

**Review by glessard — APPROVED** [review]

**Comment by edymtt** [comment]
@swift-ci please test

**Comment by Azoy** [comment]
@swift-ci please test

**Comment by Azoy** [comment]
@swift-ci please test macOS

**Review by lorentey — APPROVED** [review]
Looks good, but we should get rid of the version 14 files altogether -- nobody should ever mention or look at those!

**Comment by Azoy** [comment]
@swift-ci please test macOS

**Comment by Azoy** [comment]
@swift-ci please test Linux

**Pull request merged**
