### PR TITLE
[Diagnostics] Remove obsolete FailureDiagnosis::visitIdentityExpr from CSDiag

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
The idea was to remove the code, see how many tests fail and maybe start working on them. But since none of the test breaks locally ¯\_(ツ)_/¯, this may be obsolete? :)

cc @xedin @hborla

### CODE REVIEW

**Review by hborla — APPROVED** [review]
Awesome, thank you!

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by LucianoPAlmeida** [comment]
Thank you for the review :)

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please smoke test Linux platform

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Pull request merged**
