### PR TITLE
[5.1] [CSDiagnostics] Removes lazy when applying computed property fix-it

### PR DESCRIPTION
**Pull request by theblixguy**
Cherry-pick of #24274.

### CODE REVIEW

**Comment by theblixguy** [comment]
cc @xedin

**Review by xedin — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by theblixguy** [comment]
Unrelated OSX failure:

```
19:51:06 FATAL: Unable to delete script file /var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/jenkins3773126030451336711.sh
```

**Comment by xedin** [comment]
Infra problem, let’s try again.

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Pull request merged**
