### PR TITLE
[CAS] Teach swift-cache-tool about plugin-cas

### PR DESCRIPTION
**Pull request by cachemeifyoucan**
Teach swift-cache-tool to use PluginCAS

### CODE REVIEW

**Comment by cachemeifyoucan** [comment]
@swift-ci please smoke test

**Comment by cachemeifyoucan** [comment]
@swift-ci please smoke test

**Comment by cachemeifyoucan** [comment]
@swift-ci please smoke test

**Comment by cachemeifyoucan** [comment]
@swift-ci please smoke test

**Comment by cachemeifyoucan** [comment]
ping

**Review by artemcm — APPROVED** [review]

**Pull request merged**
