### PR TITLE
[GSB] Diagnose explicit constraints made redundant by inferred ones.

### PR DESCRIPTION
**Pull request by DougGregor**
Extend the diagnosis of redundant constraints to also include explicitly-specified constraints made redundant by inferred constraints. The canonical example is something like:

     func f<T: Hashable>(_: Set<T>)

where the parameter of type `Set<T>` implies `T: Hashable`. With this PR, we start warning about the explicit `T: Hashable` constraint being redundant.

### CODE REVIEW

**Comment by DougGregor** [comment]
@dabrahams take a look at the second commit

**Comment by DougGregor** [comment]
@phausler I'd like your opinion on the Foundation commit: is the resulting code clearer or not?

@gribozavr You argued against this a while ago, with a crappy prototype of this warning. Now that I've gone through the exercise of doing the warning right and updating the standard library, I think I like it, but didn't want to put it in without giving you a chance to pipe up.

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
I'm going to go ahead and merge based on positive feedback from @dabrahams and my own experience working with this warning. We can back it out if we decide we don't like it.

**Comment by phausler** [comment]
The change to measurement makes sense to me, no Measurement can ever be anything but Unit. Furthermore the CoreData change looks good to me as well.

**Comment by jrose-apple** [comment]
Very sad about this change. :-( This is definitely the opposite direction from what I'd want.

**Pull request merged**
