### PR TITLE
[stdlib] Fix counting of arguments in _countFormatSpecifiers.

### PR DESCRIPTION
**Pull request by ghost**
#### Resolved bug number: ([SR-1378](https://bugs.swift.org/browse/SR-1378))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by gribozavr** [comment]
Thanks!  Could you add a test to `./test/1_stdlib/NSStringAPI.swift`?

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by rsfinn** [comment]
I don't think this solution works in general. Simply counting different characters following the percent sign won't work for ordinary (non-positional) formatters; it fails for "%@ %@", for example, as well as for "%2d %2d".

I think you're going to have to explicitly look for one or more digits after the percent sign, and then look for the presence of a dollar sign following the digits.  (I was working on a solution but got busy on my day job and never actually submitted it.)

**Comment by ak3n** [comment]
@rsfinn I will close this PR then and you will open a new one.

P.S. And please, don't forget to assign issues. :)

**Comment by rsfinn** [comment]
Yes, of course.  Sorry I didn't follow through the first time.  Thanks for your gracious deferral.  :)

**Pull request closed without merging**
