### PR TITLE
Merge remote-tracking branch 'origin/master' into master-next

### PR DESCRIPTION
**Pull request by benlangmuir**

### CODE REVIEW

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
CC @adrian-prantl @smeenai whose commits collided.  I preferred the changes that were on master to minimize diffs.

**Comment by smeenai** [comment]
Sorry about that! I'd originally put up a PR against master-next but was advised to put it on master instead: https://github.com/apple/swift/pull/30374.

For future reference, for changes which are technically only needed on master-next but don't hurt to have on master either, is it better to put those on master or master-next?

**Comment by benlangmuir** [comment]
Windows PR test failed because it is checking out the wrong branch of llvm-project @compnerd @shahmishal

**Comment by benlangmuir** [comment]
Linux failure was building llvm itself - I think this is an issue because Ubuntu 16.04 uses an older clang compiler that doesn't support the conversion that it's trying to do.  We saw a similar issue recently in clangd.

**Pull request merged**
