### PR TITLE
[5.1] IRGen: Correctly compute fixed sized'ness of resilient enums

### PR DESCRIPTION
**Pull request by aschwaighofer**
rdar://51422528

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Review by slavapestov — APPROVED** [review]

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test OS X platform

**Pull request merged**
