### PR TITLE
[NFC] Fix typo for existential-member-access-limitations.md and nominal-types.md

### PR DESCRIPTION
**Pull request by lamtrinhdev**
Fix the typo for:

+ existential-member-access-limitations.md 
    * typo: "supertype" -> "super type"
+ nominal-types.md.
     * typo: "metatypes" -> "meta types"

This is just the updated typo, so it does not link to any issue.

### CODE REVIEW

**Comment by lamtrinhdev** [comment]
@swift-ci please smoke test

**Comment by lamtrinhdev** [comment]
Dear @AnthonyLatsis ,

Sorry for tagging you. However, the PR is not assigned to any member or team. I do not know how to assign the correct member or team. Could you please help to correct the member or team for reviewing this PR?

Thanks,
Lam

**Review by AnthonyLatsis — COMMENTED** [review]
I am going to have to differ here:
* [Metatype](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/types#Metatype-Type) 
* [Supertype](https://en.wikipedia.org/wiki/Subtyping)

**Comment by AnthonyLatsis** [comment]
The bot will only listen to people with write access. Please read [our docs on submitting pull requests](https://github.com/swiftlang/swift/blob/main/docs/HowToGuides/FirstPullRequest.md).

**Comment by lamtrinhdev** [comment]
Thank you for your support, @AnthonyLatsis . I am clear now.

**Pull request closed without merging**
