### PR TITLE
[Immediate] Switch immediate mode from MCJIT to LLJIT.

### PR DESCRIPTION
**Pull request by lhames**
This patch switch's the underlying implementation of Swift's immediate mode from MCJIT to LLJIT.

LLJIT is a simple LLVM IR JIT. Its interface is similar to MCJIT, but its implementation is based on LLVM's newer ORC APIs. This initial patch does not make use of any of LLJIT/ORC's advanced features, but will provide better diagnostics when JIT'd code fails to link. Once LLJIT has proven usable in this basic configuration we can start experimenting with more advanced features, including lazy compilation.

### CODE REVIEW

**Comment by lhames** [comment]
@swift-ci Please test

**Comment by lhames** [comment]
We're failing on Linux in runAsMain(...). Best guess off the top of my head is that this is due to runAsMain not setting an envp argument. I'll try fixing that tomorrow.

**Review by DougGregor — APPROVED** [review]
Awesome!

**Comment by lhames** [comment]
@swift-ci test windows

**Comment by lhames** [comment]
Hrm. Let's try that again...

@swift-ci test platform windows

**Comment by dexonsmith** [comment]
@swift-ci smoke test

**Comment by lhames** [comment]
Thanks Duncan!

What’s the bar for merging? Is a pass on the smoke tests enough?

**Comment by dexonsmith** [comment]
> Thanks Duncan!
> 
> What’s the bar for merging? Is a pass on the smoke tests enough?

I'm not really the expert for this repo.  Looking above, those are the only two with the "Required" badge.  But it's moot since the smoke test also crashed out with java.io.EOFException and it looks like infrastructure issues again.

@shahmishal , are you comfortable merging this despite the lack of signal?

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
```
01:13:23.356 Failing Tests (5):
01:13:23.356     Swift(linux-x86_64) :: execution/interpret-with-dependencies-linux.swift
01:13:23.356     Swift(linux-x86_64) :: Interpreter/shebang-env.swift
01:13:23.356     Swift(linux-x86_64) :: Interpreter/unused-type.swift
01:13:23.356     Swift(linux-x86_64) :: Interpreter/fractal.swift
01:13:23.356     Swift(linux-x86_64) :: Interpreter/mandelbrot.swift
```
Are these expected failures with this change? 
https://ci.swift.org/job/swift-PR-Linux-smoke-test/20766/console

We need to make sure these checks are green before merging the change into master branch.

**Comment by lhames** [comment]
@swift-ci test

**Comment by lhames** [comment]
@shahmishal Those tests depended on the LLVM fix in https://github.com/apple/llvm-project/commit/00515155fa1bbf95b6a2eb87217a79fde02881fb . I can’t tell whether that had been merged before those CI tests ran. I’m re-running them now...

**Comment by lhames** [comment]
@swift-ci smoke test

**Comment by lhames** [comment]
rdar://problem/57405697

**Comment by compnerd** [comment]
@lhames - seems that this is causing some problems on Windows due to the import symbol not being setup in the JIT.  IIRC, I had made some changes to the MCJIT to actually synthesize the import symbols which may be missing from LLJIT?  Any idea on that?

https://ci-external.swift.org/job/oss-swift-windows-x86_64-vs2019/322/

**Comment by lhames** [comment]
Hi Saleem. I’m on the road today, but can take a look tomorrow.

Can you point me to the import symbol synthesis code? On Windows LLJIT should be using RuntimeDyldCOFF, but if the synthesis code is in MCJIT I will just need to replicate that in LLJIT, which should be a relatively quick fix.

**Comment by compnerd** [comment]
@lhames hmm, I'll take a quick glance, but its been far too long (~3 years?) since I added that.  The IAT is similar to the PLT except that it is per module rather than AS-wide.  Each imported symbol has a synthetic symbol `__imp_<symbol>` that has the pointer to the function.  IIRC, each entry is 32-bits (since even 64-bit programs have limited addressing on Windows).

**Pull request merged**
