### PR TITLE
[Parse] Drop Swift3 support for misc diagnostics

### PR DESCRIPTION
**Pull request by rintaro**
Several diagnostics were warning in Swift3, but errors in Swift4+

Related https://github.com/apple/swift/pull/10908
CC: @huonw

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Review by huonw — APPROVED** [review]
Nice!

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Pull request merged**
