### PR TITLE
[5.3][SR-7293] Refactoring action to add Equatable Conformance

### PR DESCRIPTION
**Pull request by tkachukandrew**
This PR adds cursor refactoring action which adds Equatable conformance code for selected class or struct (it is possible to add it to extension too).

Resolves [SR-7293](https://bugs.swift.org/browse/SR-7293).

Cherry-pick #29847 (reviewed by @nathawes)

### CODE REVIEW

**Comment by nathawes** [comment]
@swift-ci please test

**Comment by nathawes** [comment]
@akyrtzi approved via slack message. Merging.

**Comment by nathawes** [comment]
@swift-ci please test Windows Platform

**Comment by nathawes** [comment]
@swift-ci please test Windows Platform

**Review by akyrtzi — APPROVED** [review]

**Pull request merged**
