### PR TITLE
[5.1] llvm-tblgen search fixes

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @Rostepher

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by Rostepher** [comment]
So long as testing passes I'm fine with this change.

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift#23906

@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Pull request merged**
