### PR TITLE
[do not merge] Always use underestimatedCount when building array

### PR DESCRIPTION
**Pull request by natecook1000**
Testing different implementation of #8038

### CODE REVIEW

**Comment by natecook1000** [comment]
@swift-ci Please benchmark

**Comment by natecook1000** [comment]
@swift-ci Please benchmark

**Comment by dabrahams** [comment]
@bob-wilson Do these numbers look OK to you?  I'd like to see these changes made if possible.

**Comment by bob-wilson** [comment]
@aschwaighofer  Can you review at these results?

I was expecting something like the results for https://github.com/apple/swift/pull/8038, where there were only 2 minor regressions. Now there are a bunch more regressions, including a big one for LazyFilteredArrays.

**Comment by natecook1000** [comment]
I think we'd still want the part of #8038 that returns `0` for `underestimatedCount`—I think that should resolve the LazyFilteredArrays issue. Should I add that one change to this branch and re-benchmark?

**Comment by aschwaighofer** [comment]
@natecook1000 Yes

**Comment by natecook1000** [comment]
@swift-ci Please benchmark

**Comment by natecook1000** [comment]
@swift-ci Please benchmark

**Comment by natecook1000** [comment]
Closing for now; @airspeedswift I think you had a different approach here…

**Pull request closed without merging**
