### PR TITLE
[WIP] [stdlib] Stable sort test implementation

### PR DESCRIPTION
**Pull request by natecook1000**
This switches to a stable merge sort that uses an n/2 buffer for merging sub-arrays. It really works only on collections with contiguous storage buffers. In my early testing it's quicker than the existing sort in a wide variety of cases.

Timing of the existing sort of `[Int]`, with 10,000 to 1,000,000 elements:
```
data                        10000     100000    1000000
--------------------------------------------------------
sorted                       0.01       0.10       1.30
reversed                     0.01       0.11       1.35
random (wide)                0.01       0.16       1.90
random (4 items)             0.02       0.28       3.28
repeated runs                0.02       0.28       3.26
steps                        0.02       0.28       3.20
random runs (max)            0.01       0.15       1.91
random runs (4 items)        0.02       0.28       3.23
a few inserts                0.02       0.20       2.54
new at end                   0.01       0.16       2.10
```

Timing of this stable sort of `[Int]`:
```
data                        10000     100000    1000000
--------------------------------------------------------
sorted                       0.00       0.01       0.06
reversed                     0.00       0.01       0.07
random (wide)                0.01       0.13       1.60
random (4 items)             0.01       0.10       1.22
repeated runs                0.01       0.10       1.22
steps                        0.00       0.01       0.06
random runs (max)            0.01       0.13       1.52
random runs (4 items)        0.01       0.10       1.18
a few inserts                0.00       0.04       0.36
new at end                   0.00       0.01       0.13
```

### CODE REVIEW

**Comment by natecook1000** [comment]
@swift-ci Please smoke benchmark

**Comment by milseman** [comment]
Are non-trivial types copied, moved, or swapped when working with the external storage?

**Comment by natecook1000** [comment]
Moved — that all happens in this function: https://github.com/apple/swift/pull/14524/files#diff-68c134d8478193cbe9299610501ff45bR438

**Comment by milseman** [comment]
In that case, I'm interested in why SortLargeExistentials and SortStringsUnicode regress. It might be a case of perturbed code having different ARC. I don't think fixing these should block this work, just would be nice to figure out why the more complicated workloads of sort regressed.

Related, would you be willing to also contribute your [Int] benchmark you used to develop this?

**Comment by natecook1000** [comment]
My hunch is that where my test was of sorting really big data sets, those tests run lots of iterations of sorting relatively smaller arrays. With that workload the buffer allocations may make up a bigger portion of the execution time.

I can definitely contribute my benchmark — does it make sense to have those as part of the `single-source` batch of benchmarks? It tests a bunch of different shapes of data, and I've added boxed `Int`s and extra-large structs as additional data types.

**Comment by milseman** [comment]
single-source is ideal, and you'd probably want to tag it a "regression" benchmark (meaning that it's useful for detecting regressions but isn't necessarily a real-world situation).

**Pull request closed without merging**
