### PR TITLE
[CSGen] Remove favoring based on literals from computeFavoredTypeForExpr

### PR DESCRIPTION
**Pull request by hborla**

### CODE REVIEW

**Comment by hborla** [comment]
@swift-ci please test compiler performance

**Comment by hborla** [comment]
@swift-ci please smoke test compiler performance

**Review by DougGregor — APPROVED** [review]
Excellent!

**Review by xedin — COMMENTED** [review]
I think this effectively makes `favorMatching*Operators` a dead code because they rely on the favoring for the argument expressions. That in turn means that solver would no longer consider overloads like `(Int, Int) -> Int` first for literal expressions like `1 + 2 + 3` which might not be a problem by itself since concrete overloads are already partitioned first but it would still result more checking because it wouldn't stop right after favored.

**Comment by hborla** [comment]
@swift-ci please test compiler performance

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by hborla** [comment]
@swift-ci please test compiler performance

**Pull request merged**
