### PR TITLE
[Serialization] Collapse indirection in DeclContextID

### PR DESCRIPTION
**Pull request by jrose-apple**
...by making it a tagged union of either a DeclID or a LocalDeclContextID. This should lead to smaller module files and be slightly more efficient to deserialize, and also means that every AST entity kind is serialized in exactly one way, which allows factoring out a common loop in writing AST block entities.

I suggest reviewing each commit separately. I'm not entirely convinced the second one is worth it.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by jrose-apple** [comment]
For code size

@swift-ci Please smoke benchmark

**Review by slavapestov — APPROVED** [review]

**Comment by jrose-apple** [comment]
…oh wait, that *is* code size rather than swiftmodule size. Oh well.

**Comment by jrose-apple** [comment]
Shaves 0.6% off of the stdlib compiled module for macOS, and 1% off the one for Foundation.

**Comment by brentdax** [comment]
What's the downside? That it replaces proven code with new code?

**Comment by jrose-apple** [comment]
Mainly that there's not a good common name for the un-templated function. `writeDecl` is obvious; `writeASTBlockEntity` looks funny to me.

**Review by varungandhi-apple — APPROVED** [review]

**Pull request merged**
