### PR TITLE
Revert "migrator: handle AppKit protocol migrations. rdar://42480588"

### PR DESCRIPTION
**Pull request by xedin**
Reverts apple/swift#18226

Unfortunately these changes have regressed multiple internal bots - rdar://problem/42652615

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
I'm actually going to force revert it for now because everything is failing not being able to `import AppKit` on some platforms.

**Comment by xedin** [comment]
It looks like `REQUIRES: objc_interop` is not enough here to prevent it from running on anything expect macOS.

**Comment by xedin** [comment]
@nkcsgexi ^

**Comment by nkcsgexi** [comment]
Thank you for reverting it! @xedin i will take a look later

**Pull request merged**
