### PR TITLE
Avoid depending on missing nodeToString and genericParameterName symbols in the freestanding stdlib

### PR DESCRIPTION
**Pull request by kubamracek**
rdar://90995253

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by mikeash — APPROVED** [review]

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test macOS platform

**Comment by kubamracek** [comment]
@swift-ci please test macOS platform

**Comment by kubamracek** [comment]
@swift-ci please test macOS platform

**Pull request merged**
