### PR TITLE
Require asserts for AD tests using the debug-only flag

### PR DESCRIPTION
**Pull request by asuhan**

### CODE REVIEW

**Review by dan-zheng — APPROVED** [review]
Thanks, nice catch! (If we had CI running tests with no-assertions, I think this error could've been caught earlier.)

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow clean

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by bgogul** [comment]
> Thanks, nice catch! (If we had CI running tests with no-assertions, I think this error could've been caught earlier.)

Do we even need `--debug-only=differentiation` for the test?

**Comment by dan-zheng** [comment]
> > Thanks, nice catch! (If we had CI running tests with no-assertions, I think this error could've been caught earlier.)
> 
> Do we even need `--debug-only=differentiation` for the test?

Sadly, yes we do, for the purposes for checking AD-generated structs and enums.

During one of the recent merges, structs and enums were changed to be implicit (as they should), meaning they no longer show up via any dumping (e.g. `-emit-sil`). So, I added `LLVM_DEBUG` print statements to print the structs and enums via `-debug-only=differentiation`.

We could add a separate `-Xllvm` flag just for printing the data structures, but I think reusing `-debug-only=differentiation` is fine. Other SILOptimizer tests also use `-debug-only` to FileCheck various properties.

**Pull request merged**
