### PR TITLE
[5.0] demangler: catch more cases where the demangler crashes on malformed symbols

### PR DESCRIPTION
**Pull request by eeckstein**
rdar://problem/36337512

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by xedin** [comment]
@eeckstein should I cherry-pick my function parameter label backwards compatibility changes to 5.0 branch as well?

**Comment by shahmishal** [comment]
@swift-ci smoke test

**Comment by shahmishal** [comment]
@swift-ci smoke test

**Pull request merged**
