### PR TITLE
Start recovering from missing types in SIL deserialization

### PR DESCRIPTION
**Pull request by jrose-apple**
Now that `@inlinable` is a supported feature, we need to handle cases where a function is inlinable but it references some type that imports differently in different Swift versions. To start, handle the case where a SIL function's type is now invalid and therefore the entire function can't be imported. ~This doesn't open up anything interesting yet, but it's a start.~ This simple case is enough to fix problems when a SIL function is only referenced from a witness table and not actually used.

rdar://problem/40899824

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test compiler performance

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
[Full macOS tests](https://ci.swift.org/job/swift-PR-osx/5845/)

@swift-ci Please smoke test macOS

**Comment by jrose-apple** [comment]
@swift-ci Please test Linux

**Comment by jrose-apple** [comment]
\*sigh\* Typo.

@swift-ci Please smoke test macOS

**Comment by jrose-apple** [comment]
@swift-ci Please test Linux

**Review by slavapestov — APPROVED** [review]

**Review by shajrawi — COMMENTED** [review]
LGTM

**Pull request merged**
