### PR TITLE
[AutoDiff] Support differentiating global constant closures.

### PR DESCRIPTION
**Pull request by rxwei**
* When there is a reference to a global `let` closure, we find its initializer in `@main`, trace back to the original `function_ref`, and differentiate that.

* NFC: Refactor `findReferenceToVisibleFunction` and `findWitnessMethod` to a single template.

Resolves [SR-9695](https://bugs.swift.org/browse/SR-9695).

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Review by dan-zheng — APPROVED** [review]
Great!

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Pull request merged**
