### PR TITLE
SILCombiner: Clean up the concrete -> existential peephole a bit

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by gottesmm** [comment]
@slavapestov Are the dynamic self checks really not needed anymore (just double checking)?

**Comment by slavapestov** [comment]
I need to add a test case before merging but it looks like they were only needed back when the combiner did devirt. The devirtualizer knows to insert the right bitcasts when I tested this manually.

**Comment by slavapestov** [comment]
@gottesmm I added the test.

Actually I realized it would be nice if peephole was be generalized so that all occurrences of the opened existential are replaced with the concrete type, not just witness_method and apply. Right now, we still alloc_stack an opened existential and cast the result, instead of just alloc_stack'ing the concrete type, which results in less efficient code in IRGen. I think now with the opened archetype use tracking, we should be able to implement this pretty easily.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by gottesmm** [comment]
@slavapestov Thanks! I just remember a lot of bugs coming up due to issues related to that. Just didn't want to have to fix them again!

**Comment by slavapestov** [comment]
If they come up again, we'll fix them properly instead of just disabling the optimization. ;-)

**Pull request merged**
