### PR TITLE
Fix unnecessary one-time recompile of stdlib with -enable-ossa-flag

### PR DESCRIPTION
**Pull request by meg-gupta**
This includes a bit in the module format to represent if the module was compiled with -enable-ossa-modules flag. When compiling a client module with -enable-ossa-modules flag, all dependent modules are checked for this bit, if not on, recompilation is triggered with -enable-ossa-modules.

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test

**Review by 8704dev — APPROVED** [review]

**Comment by meg-gupta** [comment]
Please test with following pull request:
https://github.com/apple/llvm-project/pull/3316

@swift-ci test

**Comment by meg-gupta** [comment]
Please test with following pull request:
apple/llvm-project#3316

@swift-ci test

**Comment by meg-gupta** [comment]
Please test with following pull request:
apple/llvm-project#3316

@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test windows platform

**Review by artemcm — APPROVED** [review]
This change looks good!

**Comment by meg-gupta** [comment]
Please test with following pull request:
apple/llvm-project#3316

@swift-ci test windows platform

**Comment by meg-gupta** [comment]
Please test with following pull request:
apple/llvm-project#3316

@swift-ci test windows platform

**Comment by atrick** [comment]
@meg-gupta Thanks! This is really important for adoption to have working well. Looks like great work to me.

**Pull request merged**
