### PR TITLE
[api-digester] Serialize protocol USRs in conformances

### PR DESCRIPTION
**Pull request by dmcyk**
Currently SDK conformance nodes include protocol `name` and `printedName` keys, where both are equal, demangled names. Seems like this is sufficient for changes analysis, but its not possible to uniquely identify the protocols.
For my use case including USR would be very useful, as then protocols can be identified across module boundaries. Currently I can't be certain about this even with some intermediate analysis, as there could be a collision in protocol names between modules.

The information is already there, it only has to be serialised.

Tests for stdlib are passing on my local machine without any changes. 
I tried to update them as well, but there were other changes as well, so I guess the file stdlib inputs are not totally up to date?

@nkcsgexi do you think this is relevant for upstreaming?

### CODE REVIEW

**Review by nkcsgexi — APPROVED** [review]
This seems to me a valuable addition👍. Could you remove the unrelated white space change?

**Comment by dmcyk** [comment]
Fixed 👍

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci Please smoke test OS X platform

**Pull request merged**
