### PR TITLE
[build-script] Pass llbuild build type arg to build-script-impl

### PR DESCRIPTION
**Pull request by aciidgh**

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Review by graydon — COMMENTED** [review]
I think you'll might also want to do something about setting --llbuild-enable-assertions. Not sure which flag to derive it from, but maybe there's at least one not-explicitly-specified config where the right inferred setting is 0?

**Comment by ddunbar** [comment]
Can we piggy back on whatever swiftc itself uses to determine if assertions are enabled?

**Comment by graydon** [comment]
Yeah, I believe `utils/build_swift/driver_arguments.py` has a set of options for sub-project specific assertions, which you'll need to add a `--llbuild-assertions` entry for, and then a function `_apply_default_arguments` that propagates the umbrella `build-script` command-line argument `--assertions` and `--no-assertions` to the sub-arguments like `--swift-assertions`, `--llvm-assertions`, `--cmark-assertions` and so forth (and which get passed along to `build-script-impl` in ways I think are determined by `convert_to_impl_arguments` in `build-script`) . I'd suggest wiring those 3 places up to pass along `--llbuild-assertions` the same way.

**Comment by aciidb0mb3r** [comment]
I don't see an option to control assertions in llbuild's cmake configuration. I think we can file a separate bug for tracking that.

**Comment by aciidb0mb3r** [comment]
@graydon @ddunbar _nag_

**Comment by graydon** [comment]
(LGTM!)

**Review by ddunbar — APPROVED** [review]
LGTM, but lets also try and get the asserts part sooner rather than later. If you don't feel like tackling it, hand me a bug for it.

**Comment by aciidb0mb3r** [comment]
https://bugs.swift.org/browse/SR-7121

**Comment by aciidb0mb3r** [comment]
Reproduces locally if I try to build bindings. Reverting..

**Comment by aciidb0mb3r** [comment]
Actually, reproduces with debug build too :|

**Pull request merged**
