### PR TITLE
Revert "Sema: Remove some unreachable code from CSApply"

### PR DESCRIPTION
**Pull request by ahoppen**
As discussed in https://github.com/apple/swift/pull/36493 and https://github.com/apple/swift/pull/36494, this reverts https://github.com/apple/swift/pull/36028 and adds the test cases from those PRs.

I have also adjusted the tests to live in `validation-test/IDE/crashers_2_fixed` and use `swift-ide-test` instead of `sourcekitd-test`.

Fixes rdar://75219757 [SR-14319] and rdar://75200446 [SR-14318]

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by xedin — APPROVED** [review]
LGTM! We'd have to wait until code completion is completely ported to use `typeCheckForCodeCompletion` before removing this unfortunately...

**Comment by slavapestov** [comment]
Nice find! Probably some parts of that PR are almost certainly still dead, but we can wait to re-apply it until we finish cleaning up code completion.

**Comment by ahoppen** [comment]
Yeah, most likely the majority is still unreachable and sorry for reverting. But as you said, we can probably just re-apply it later.

**Comment by ahoppen** [comment]
@swift-ci Please smoke test Windows

**Pull request merged**
