### PR TITLE
[5.0] [ABI] [stdlib] Remove magnitude-based overload of abs(_:).

### PR DESCRIPTION
**Pull request by DougGregor**
The standard library has two versions of the `abs(_:)` function:

```
func abs<T : SignedNumeric>(_ x: T) -> T where T.Magnitude == T
func abs<T : SignedNumeric & Comparable>(_ x: T) -> T
```

The first is more specialized than the second because `T.Magnitude` is
known to conform to `Comparable`. Indeed, it’s a more specialized
implementation that returns `magnitude`.

However, this overload behaves oddly: in the expression `abs(-8)`, the type
checker will pick the first overload because it is more specialized. That’s
a general guiding principle for overloading: pick the most specialized
overload that works.

Remove the more-specialized version of `abs(_:)` completely, so there is
only a single definition of `abs(_:)` in the standard library.
Teach the more-general implementation of
`abs(_:)` to dynamically test whether `T.self == T.Magnitude`, and use
`magnitude` in those cases, which provides more consistent semantics
as well as fixing the regression and simplifying the type checking problem.

Fixes rdar://problem/42345366.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test Linux

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
The "failures" in the source compatibility suite are UPASS's which are likely unrelated:

```
  | UPASS_Lark_4.0_BuildSwiftPackage.log | 35.04 KB | view-- | -- | -- | --
  | UPASS_SRP_4.0_BuildSwiftPackage.log | 41.95 KB | view
  | UPASS_SwiftLint_4.0_BuildSwiftPackage.log | 138.69 KB | view
  | UPASS_SwiftLint_4.2_BuildSwiftPackage.log
```

**Review by AnnaZaks — APPROVED** [review]
LGTM

**Pull request merged**
