### PR TITLE
[6.0.x] Remove libicu build and update list of Swift runtime libraries to be de-duplicated

### PR DESCRIPTION
**Pull request by finagolfin**
__Explanation:__ Libicu is entirely unused on non-Darwin platforms too since the Foundation re-core to use `_FoundationICU`, so shave 35 MB off the 6.0 non-Darwin toolchains by removing it. Also, update the list of libraries that are deduplicated by the autolink-extract tool.

__Scope:__ Only affects code for non-Darwin platforms, that is now entirely unused.

__Issue:__ None

__Original PRs:__ #75262, #75342, and #76224

__Risk:__ Very low

__Testing:__ Passed all CI on trunk

__Reviewer:__ @jmschonfeld @compnerd @parkera @etcwilde 

We are unnecessarily still shipping libicu in the 6.0 toolchains despite having another copy in `lib_FoundationICU`. This was removed in 6.1 months ago without a problem.

### CODE REVIEW

**Comment by finagolfin** [comment]
@jmschonfeld, need a CI run here.

**Comment by jmschonfeld** [comment]
@swift-ci please test

**Comment by finagolfin** [comment]
Passed CI, just needs approval from @compnerd and other owners.

**Comment by finagolfin** [comment]
@shahmishal, let me know what you think as the linux platform manager about shaving these unused libraries off the 6.0 toolchain in a patch release.

**Comment by shahmishal** [comment]
I would like to get a review from @parkera and @airspeedswift.

**Comment by parkera** [comment]
I don't want to aggressively cherry pick this back without any evidence that it resolves the named bug. We're already doing it on main, though.

**Comment by finagolfin** [comment]
@parkera, this has nothing to do with any bug, I think you might have got this mixed up with #76606. This is just about a simple cleanup on the toolchain for libicu libraries that are now unused on linux and Windows after the Foundation re-core, which uses `_FoundationICU` instead.

**Comment by parkera** [comment]
Ok, thanks

**Review by parkera — APPROVED** [review]
I think this is fine since we've already landed similar changes on main. I see it as an opportunity fix to along with other changes already staged for a 6.0.x but not a driver for the release itself.

**Comment by finagolfin** [comment]
Ping @shahmishal, do we need anyone else to sign off? I think you and I pinged all relevant reviewers weeks ago.

**Comment by finagolfin** [comment]
Ping @airspeedswift, I think Mishal just wanted you to sign off.

**Comment by finagolfin** [comment]
Ping @shahmishal, would be good to get this in before the next patch release.

**Comment by shahmishal** [comment]
cc: @airspeedswift

**Review by DougGregor — APPROVED** [review]
Yeah, we should take this

**Comment by DougGregor** [comment]
It's been a while, so re-running CI before merging

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by finagolfin** [comment]
Passed CI, ready for merge.

**Pull request merged**
