### PR TITLE
[Statistic] Adjust for LLVM r374490

### PR DESCRIPTION
**Pull request by smeenai**
Use appropriate member functions instead of accessing Value directly.

### CODE REVIEW

**Comment by smeenai** [comment]
CC @adrian-prantl @compnerd @dcci 

I'll need someone to commit this for me.

**Review by compnerd — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
CC: @shahmishal - I figure that you might want to be aware since you just setup the master-rebase scheme

**Comment by smeenai** [comment]
@compnerd @shahmishal what's the master-rebase scheme? Is there any documentation or forum post I can read?

**Pull request merged**
