### PR TITLE
[indexing-model] Merged master and fixed SE-0046 conflicts

### PR DESCRIPTION
**Pull request by harlanhaskins**
#### What's in this pull request?

Merged master into the swift-3-indexing-model branch.

#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

This reverts commit c0eafa7c64713aff56737b1b4220ee4eaf01f402.

### CODE REVIEW

**Comment by harlanhaskins** [comment]
@gribozavr I mistakenly pushed the merge to apple/swift, so I reverted it and re-applied it in this PR. My main concerns were resolving conflicts in `stdlib/public/core/Collection.swift`, `stdlib/public/core/CollectionAlgorithms.swift.gyb`, and `stdlib/public/core/Sequence.gyb` by just wholesale ignoring the changes from master.

**Comment by gribozavr** [comment]
```
$ git branch
* swift-3-indexing-model
$ git reset --hard 48fbd6b
HEAD is now at 48fbd6b [stdlib] Reorder protocol conformances
$  git push -f origin swift-3-indexing-model
```

**Comment by harlanhaskins** [comment]
Thanks for handling that! I hope you'll understand my reluctance to `git push -f` straight to the Apple repo 😉

I reset this PR back to the first merge commit.

**Comment by gribozavr** [comment]
Thank you!

It would have been easier to review if you merged the git hash after the SE-0046, `510f29abf77e202780c11d5f6c7449313c819030` instead of `master`.

I see conflict markers in:

```
stdlib/private/StdlibCollectionUnittest/LoggingWrappers.swift.gyb
stdlib/private/StdlibUnittest/StdlibUnittest.swift.gyb
...
```

**Pull request closed without merging**
