### PR TITLE
[benchmark] DataCreateSmall - Fix legacyFactor

### PR DESCRIPTION
**Pull request by palimondo**
Adjust the multipliers for legacy factor and inner loop to account for the improved performance of the `Data` implementation.

### CODE REVIEW

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
@swift-ci please smoke test

**Comment by palimondo** [comment]
@swift-ci please smoke test OS X

**Comment by palimondo** [comment]
@eeckstein Please review 🙏

**Comment by eeckstein** [comment]
ok, no problem

**Pull request merged**
