### PR TITLE
[Typechecker] Look through all optionals when diagnosing uninhabited types

### PR DESCRIPTION
**Pull request by theblixguy**
This PR fixes an issue where we wouldn't look through all the optionals in a type when diagnosing the declaration of a property initialised with a function which returns an uninhabited type, for example:

```swift
func foo() -> Never? {
    return nil
}

func bar() -> Never?? {
    return nil
}

let one = foo() // warning: constant 'one' inferred to have type 'Never?', which is an enum with no cases
let two = bar() // no warning
```

Resolves [SR-10995](https://bugs.swift.org/browse/SR-10995).

### CODE REVIEW

**Comment by theblixguy** [comment]
cc @xedin

**Comment by slavapestov** [comment]
I’m not sure the original check was correct. `Never?` is inhabited; nil is a valid value.

**Comment by theblixguy** [comment]
I suppose for optionals, we can check whether we have `some` or `none`. Eg:

```swift
func foo() -> Never? {
  return fatalError()
}

func bar() -> Never? {
  return nil
}

let f = foo() // no warning
let g = bar() // warning
```

**Comment by slavapestov** [comment]
@theblixguy That's too much work for very little gain. However, you could still argue that an inferred type of `Never?` (or `Never??`, etc) is _unexpected_, even though it is not _uninhabited_. For example,  we diagnose if the inferred type of a property is `()` or `()?`. Could we just change the diagnostic text in this case?

**Comment by theblixguy** [comment]
Sure, we can omit the "is an enum with no cases" part for Optional<Never>. Would that be okay? So something like `constant 'property' inferred to have type 'Never?', which might be unexpected`?

**Comment by slavapestov** [comment]
Sounds good!

**Comment by theblixguy** [comment]
@slavapestov Done!

**Review by slavapestov — APPROVED** [review]

**Comment by slavapestov** [comment]
@swift-ci Please smoke test and merge

**Comment by theblixguy** [comment]
Hmm seems like the CI didn't run the tests

**Comment by theblixguy** [comment]
Could we re-run the smoke test and merge? Seems like it didn’t run before. Thanks!

**Comment by xedin** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
