### PR TITLE
Sema: Force property wrappers in EmittedMembersRequest::evaluate() [5.2]

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes <rdar://problem/61229365>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Review by tkremenek — APPROVED** [review]

**Comment by tkremenek** [comment]
@swict-ci clean test

**Comment by tkremenek** [comment]
@swift-ci clean test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by slavapestov** [comment]
@compnerd I know this is the 5.2 branch but this doesn't look branch-specific?

```
ERROR: [WS-CLEANUP] Cannot delete workspace: Unable to delete 'S:\jenkins\workspace\swift-PR-windows\swift\.git\objects\pack\tmp_pack_yzGpTa'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
ERROR: Cannot delete workspace: Unable to delete 'S:\jenkins\workspace\swift-PR-windows\swift\.git\objects\pack\tmp_pack_yzGpTa'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
```

**Comment by slavapestov** [comment]
@swift-ci please test

**Pull request merged**
