### PR TITLE
Fix tests on Windows CI with VS2022

### PR DESCRIPTION
**Pull request by tristanlabelle**
While trying the migrate the CI to VS2022, some tests are failing. See https://ci-external.swift.org/job/win64-vs2022/1765/console

`test/Driver/Dependencies/one-way-merge-module-fine.swift`: is using bash file path wildcard syntax which is unreliable on Windows. We use bash from the git installation and it appears that not all versions will support this syntax. The fix is to expand them.

`test/ModuleInterface/ModuleCache/prefer-local-module-to-sdk-framework.swift`: is using extra long paths. The VS2022 CI is using a more recent version of Python where `os.path.realpath` expands substitute drives, which we were using to avoid running into `MAX_PATH` limitations. We may need to address this in `lit.py` but for here we can at least shorten some paths to see if we hit further issues.

### CODE REVIEW

**Review by compnerd — APPROVED** [review]
Thanks!

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by tristanlabelle** [comment]
I'm seeing 2 test failures on linux, though the logs say there are 3 including one unexpected. The two tests that outputted errors succeeded on macOS. Is this flakiness?

```
Test Case 'SwiftDriverTests.testToolSearching' started at 2023-06-13 17:11:26.670
<EXPR>:0: error: SwiftDriverTests.testToolSearching : threw error "failed to retrieve frontend target info"
Test Case 'SwiftDriverTests.testToolSearching' failed (0.003 seconds)

Test Case 'SwiftDriverTests.testWMOWithJustObjectInputs' started at 2023-06-13 17:11:27.026
/home/build-user/swift-driver/Tests/SwiftDriverTests/SwiftDriverTests.swift:2919: error: SwiftDriverTests.testWMOWithJustObjectInputs : XCTAssertEqual failed: ("2") is not equal to ("1") -
/home/build-user/swift-driver/Tests/SwiftDriverTests/SwiftDriverTests.swift:2920: error: SwiftDriverTests.testWMOWithJustObjectInputs : XCTAssertEqual failed: ("Optional(SwiftDriver.Job.Kind.autolinkExtract)") is not equal to ("Optional(SwiftDriver.Job.Kind.link)") -
Test Case 'SwiftDriverTests.testWMOWithJustObjectInputs' failed (0.004 seconds)

Test Suite 'SwiftDriverTests' failed at 2023-06-13 17:11:27.099
Executed 164 tests, with 2 tests skipped and 3 failures (1 unexpected) in 2.704 (2.704) seconds

Test Suite 'release.xctest' failed at 2023-06-13 17:11:27.273
Executed 353 tests, with 37 tests skipped and 3 failures (1 unexpected) in 218.073 (218.073) seconds
Test Suite 'All tests' failed at 2023-06-13 17:11:27.273
Executed 353 tests, with 37 tests skipped and 3 failures (1 unexpected) in 218.073 (218.073) seconds
```

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Pull request merged**
