### PR TITLE
[5.7] Integrate string processing API changes into release/5.7

### PR DESCRIPTION
**Pull request by rxwei**
Friend PR: apple/swift-experimental-string-processing#298.

### CODE REVIEW

**Comment by rxwei** [comment]
apple/swift-experimental-string-processing#291
@swift-ci please test

**Review by stephentyrone — APPROVED** [review]

**Comment by Azoy** [comment]
https://github.com/apple/swift-experimental-string-processing/pull/298
@swift-ci please test

**Comment by Azoy** [comment]
https://github.com/apple/swift-experimental-string-processing/pull/298
@swift-ci please test

**Comment by Azoy** [comment]
https://github.com/apple/swift-experimental-string-processing/pull/298
@swift-ci please test

**Comment by Azoy** [comment]
https://github.com/apple/swift-experimental-string-processing/pull/298
@swift-ci please test macOS

**Pull request merged**
