### PR TITLE
Move makeOp function from tensoflow-swift-bindings to CompilerRuntime.swift

### PR DESCRIPTION
**Pull request by bgogul**

### CODE REVIEW

**Comment by bgogul** [comment]
@swift-ci please test tensorflow

**Review by burmako — APPROVED** [review]

**Comment by burmako** [comment]
@swift-ci Please test tensorflow

**Comment by bgogul** [comment]
@swift-ci please clean test tensorflow

**Comment by bgogul** [comment]
@swift-ci please clean test tensorflow

**Comment by burmako** [comment]
@swift-ci please clean test tensorflow

**Pull request merged**
