### PR TITLE
SILGen: Fix function conversions involving DynamicSelfType

### PR DESCRIPTION
**Pull request by slavapestov**
This was already implemented but the check looked at the lowered
types and not the AST types, and DynamicSelfType is erased at the
top level of a lowered type.

Fixes <https://bugs.swift.org/browse/SR-10309>, <rdar://problem/49703441>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@shahmishal Known problem?

```
20:16:54 sccache --stop-server 2> /dev/null || true
20:16:54 + sccache --stop-server
20:16:54 Stopping sccache server...
20:16:54 + true
20:16:54 export SCCACHE_IDLE_TIMEOUT=0
20:16:54 + export SCCACHE_IDLE_TIMEOUT=0
20:16:54 + SCCACHE_IDLE_TIMEOUT=0
20:16:54 sccache --start-server
20:16:54 + sccache --start-server
20:16:54 Starting sccache server...
20:16:59 error: Timed out waiting for server startup
20:17:00 Build step 'Execute shell' marked build as failure
```

**Comment by slavapestov** [comment]
@swift-ci Please clean test macOS

**Comment by shahmishal** [comment]
> @shahmishal Known problem?
> 
> ```
> 20:16:54 sccache --stop-server 2> /dev/null || true
> 20:16:54 + sccache --stop-server
> 20:16:54 Stopping sccache server...
> 20:16:54 + true
> 20:16:54 export SCCACHE_IDLE_TIMEOUT=0
> 20:16:54 + export SCCACHE_IDLE_TIMEOUT=0
> 20:16:54 + SCCACHE_IDLE_TIMEOUT=0
> 20:16:54 sccache --start-server
> 20:16:54 + sccache --start-server
> 20:16:54 Starting sccache server...
> 20:16:59 error: Timed out waiting for server startup
> 20:17:00 Build step 'Execute shell' marked build as failure
> ```

Yes, I will add a fix for this soon.

**Comment by shahmishal** [comment]
@swift-ci Please clean test macOS

**Comment by shahmishal** [comment]
@swift-ci Please clean test macOS

**Pull request merged**
