### PR TITLE
AST: Rename getFullName -> getName on ValueDecl & MissingMemberDecl

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
Follow-up to #30606

Now that `FuncDecl::getName` and `EnumElementDecl::getName` have been replaced with `ValueDecl::getBaseIdentifier`, we can rename `ValueDecl::getFullName` to `getName()` and thereby address the targeted FIXME.

### CODE REVIEW

**Comment by AnthonyLatsis** [comment]
apple/llvm-project#1107

@swift-ci please smoke test

**Comment by CodaFi** [comment]
(Just to get this blue, this is still mergeable)

@swift-ci test Windows

**Comment by CodaFi** [comment]
(Oh, it's cross-repo, ignore me)

**Comment by jckarter** [comment]
Looks good, thanks for seeing this through @AnthonyLatsis! Since this is just a rename, and we wouldn't want to deal with churn merging across branches, we probably want this in the `swift-5.3-branch` too once it lands in master.

**Comment by AnthonyLatsis** [comment]
Makes sense. Does the `swift-5.3-branch` also need a dedicated llvm branch for cross-repo testing?

**Comment by AnthonyLatsis** [comment]
@jckarter Also, someone needs to shepherd the PRs for me since the change is cross-repo. Thanks!

**Comment by jckarter** [comment]
@AnthonyLatsis Sounds good! Pulling this into `release/5.3` in the swift repo and `swift/release/5.3` on the llvm-project repo should do the job for the 5.3 branch.

**Pull request merged**
