### PR TITLE
[stdlib] Add build option to enable _debugPrecondition in Release mode

### PR DESCRIPTION
**Pull request by lorentey**
It is sometimes desirable to always perform (relatively cheap) runtime checks in the stdlib, even in configurations where we’d otherwise elide them.

Add a build-time option to the standard library (`SWIFT_STDLIB_ENABLE_DEBUG_PRECONDITIONS_IN_RELEASE`) to make `_debugPrecondition` work like `_precondition`, i.e., to enable it even in ReleaseAssert configurations.

This option will keep additional checks in the following places, even in release mode:

- Range checking in the subscript operations of all unsafe buffer pointer types.
- Nil checking in `Optional.unsafelyUnwrapped`
- Additional argument validation in `Unsafe[Mutable][Raw]Pointer`’s initialization/assignment/move/deinitialization/binding methods
- Protection against initializing `Unsafe[Mutable][Raw]Pointer` with invalid data. (Negative count, nil pointer for non-empty buffer, etc)
- Checks against index overflow in `Unsafe[Mutable]BufferPointer`’s index manipulation methods
- Checks against backward ranges in `Range(uncheckedBounds:)`, `ClosedRange(uncheckedBounds:)`
- Dynamic isa check in `unsafeDowncast(_:to:)`
- Additional [cheap] checks to catch invalid Sequence/Collection implementations in `Array.init<S:Sequence>(_:)` and elsewhere
- Checks against `Character` containing multiple grapheme clusters
- More index validation in `EmptyCollection`

(Additional cases will get added as the stdlib evolves.)

The option is disabled by default — so `_debugPrecondition`s continue to be disabled in optimized builds, even after this change lands, unless someone specifically builds a stdlib that enables them.

rdar://89118585

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Comment by stephentyrone** [comment]
I am mildly worried about testing this, since the stdlib is not built this way in CI. What's the plan?

**Comment by lorentey** [comment]
Ah, there is also the fact that parts of our unit tests are currently looking at `_isDebugAssertConfiguration` to figure out whether to expect traps for the cases above. Oh well, more updates incoming.

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
🤔
```
Failed Tests (50):
  Swift(macosx-x86_64) :: bindings-build-record.swift
  Swift(macosx-x86_64) :: chained-additional-kinds-fine.swift
  Swift(macosx-x86_64) :: chained-after-fine.swift
  Swift(macosx-x86_64) :: chained-fine.swift
  Swift(macosx-x86_64) :: chained-private-after-fine.swift
  Swift(macosx-x86_64) :: chained-private-after-multiple-fine.swift
  Swift(macosx-x86_64) :: chained-private-after-multiple-nominal-members-fine.swift
  Swift(macosx-x86_64) :: chained-private-fine.swift
  Swift(macosx-x86_64) :: check-interface-implementation-fine.swift
  Swift(macosx-x86_64) :: crash-added-fine.swift
  Swift(macosx-x86_64) :: crash-new-fine.swift
  Swift(macosx-x86_64) :: crash-simple-fine.swift
  Swift(macosx-x86_64) :: dependencies-preservation-fine.swift
  Swift(macosx-x86_64) :: driver-show-incremental-arguments-fine.swift
  Swift(macosx-x86_64) :: driver-show-incremental-conflicting-arguments-fine.swift
  Swift(macosx-x86_64) :: driver-show-incremental-inputs-fine.swift
  Swift(macosx-x86_64) :: driver-show-incremental-malformed-fine.swift
  Swift(macosx-x86_64) :: driver-show-incremental-mutual-fine.swift
  Swift(macosx-x86_64) :: driver-show-incremental-swift-version-fine.swift
  Swift(macosx-x86_64) :: embed-bitcode-parallel-fine.swift
  Swift(macosx-x86_64) :: fail-added-fine.swift
  Swift(macosx-x86_64) :: fail-chained-fine.swift
  Swift(macosx-x86_64) :: fail-interface-hash-fine.swift
  Swift(macosx-x86_64) :: fail-new-fine.swift
  Swift(macosx-x86_64) :: fail-simple-fine.swift
  Swift(macosx-x86_64) :: fail-with-bad-deps-fine.swift
  Swift(macosx-x86_64) :: file-added-fine.swift
  Swift(macosx-x86_64) :: independent-fine.swift
  Swift(macosx-x86_64) :: independent-half-dirty-fine.swift
  Swift(macosx-x86_64) :: independent-parseable-fine.swift
  Swift(macosx-x86_64) :: malformed-but-valid-yaml-fine.swift
  Swift(macosx-x86_64) :: malformed-fine.swift
  Swift(macosx-x86_64) :: mutual-fine.swift
  Swift(macosx-x86_64) :: mutual-interface-hash-fine.swift
  Swift(macosx-x86_64) :: nominal-members-fine.swift
  Swift(macosx-x86_64) :: one-way-depends-after-fine.swift
  Swift(macosx-x86_64) :: one-way-depends-before-fine.swift
  Swift(macosx-x86_64) :: one-way-external-delete-fine.swift
  Swift(macosx-x86_64) :: one-way-external-fine.swift
  Swift(macosx-x86_64) :: one-way-fine.swift
  Swift(macosx-x86_64) :: one-way-merge-module-fine.swift
  Swift(macosx-x86_64) :: one-way-parallel-fine.swift
  Swift(macosx-x86_64) :: one-way-parseable-fine.swift
  Swift(macosx-x86_64) :: one-way-provides-after-fine.swift
  Swift(macosx-x86_64) :: one-way-provides-before-fine.swift
  Swift(macosx-x86_64) :: one-way-while-editing-fine.swift
  Swift(macosx-x86_64) :: only-skip-once.swift
  Swift(macosx-x86_64) :: private-after-fine.swift
  Swift(macosx-x86_64) :: private-fine.swift
  Swift(macosx-x86_64) :: whole-module-build-record.swift

```

**Comment by lorentey** [comment]
@swift-ci clean test macOS platform

**Pull request merged**
