### PR TITLE
[docs] Update Testing.md

### PR DESCRIPTION
**Pull request by benrimmington**
Add details on 32-bit testing with an iOS simulator.

### CODE REVIEW

**Comment by CodaFi** [comment]
Cool

@swift-ci smoke test and merge

**Comment by benrimmington** [comment]
Unexpected failure:

> Swift(linux-x86_64) :: AutoDiff/compiler_crashers_fixed/sr12650-noderivative-parameter-type-mangling.swift

**Comment by CodaFi** [comment]
Ugh, I've seen that failure before once in a blue moon. There's UB afoot.

@swift-ci smoke test Linux platform

**Comment by benrimmington** [comment]
Linux platform checks were successful.

**Comment by CodaFi** [comment]
⛵

**Comment by theblixguy** [comment]
I think the full command should be:

```
xcrun simctl create 'iPhone 5' com.apple.CoreSimulator.SimDeviceType.iPhone-5 com.apple.CoreSimulator.SimRuntime.iOS-10-3
```

(at least according to #31928)

**Comment by benrimmington** [comment]
@theblixguy The runtime argument is optional.

```sh
xcrun simctl help create                                                            

Create a new device.
Usage: simctl create <name> <device type id> [<runtime id>]

	<device type id>    A valid available device type. Find these by running "xcrun simctl list devicetypes".
	                    Examples: ("iPhone X", "com.apple.CoreSimulator.SimDeviceType.iPhone-X")
	<runtime id>        A valid and available runtime. Find these by running "xcrun simctl list runtimes".
	                    If no runtime is specified the newest runtime compatible with the device type is chosen.
	                    Examples: ("watchOS3", "watchOS3.2", "watchOS 3.2", "com.apple.CoreSimulator.SimRuntime.watchOS-3-2",
	                               "/Volumes/path/to/Runtimes/watchOS 3.2.simruntime")
```

For example:

```sh
xcrun simctl create 'iPhone 5' 'com.apple.CoreSimulator.SimDeviceType.iPhone-5'

No runtime specified, using 'iOS 10.3 (10.3.1 - 14E8301) - com.apple.CoreSimulator.SimRuntime.iOS-10-3'
```

**Comment by theblixguy** [comment]
Oh, I see. Sorry, I actually misread iPhone 5 as iPhone 5s! We don't need to worry about newer runtimes like iOS 11 and later so this is fine.

**Pull request merged**
