### PR TITLE
[tests] Enable several test cases on non-Darwin platforms

### PR DESCRIPTION
**Pull request by rintaro**
#### What's in this pull request?

Enable several test cases on non-Darwin platforms.
- test/1_stdlib/ManagedBuffer.swift
- test/1_stdlib/Mirror.swift
- test/Interpreter/SDK/libc.swift
- validation-test/stdlib/ArrayNew.swift.gyb
- validation-test/stdlib/Dictionary.swift
- validation-test/stdlib/Unicode.swift

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

### CODE REVIEW

**Comment by gribozavr** [comment]
@swift-ci Please test and merge

**Comment by gribozavr** [comment]
@rintaro Thank you!

**Comment by gribozavr** [comment]
@rintaro Seems like Linux tests failed, could you take a look?

**Comment by rintaro** [comment]
I'm looking into it.

https://ci.swift.org/job/swift-PR-Linux/1551/console
```
[ RUN      ] ManagedBuffer.basic
stdout>>> check failed at /home/buildnode/jenkins/workspace/swift-PR-Linux@2/swift/test/1_stdlib/ManagedBuffer.swift, line 149
stdout>>> 12 >= 13
[     FAIL ] ManagedBuffer.basic
```

```swift
tests.test("basic") {                                                             
  do {                                                                            
    let s = TestManagedBuffer<LifetimeTracked>.create(0)                          
    expectEqual(1, LifetimeTracked.instances)                                     
  }                                                                               
                                                                                  
  expectEqual(0, LifetimeTracked.instances)                                       
  do {                                                                            
    let s = TestManagedBuffer<LifetimeTracked>.create(10)                         
    expectEqual(0, s.count)                                                       
    expectLE(10, s.myCapacity)                                                    
    expectGE(12, s.myCapacity)  // allow some over-allocation but not too much 
    // ^ Failing test
```

**Comment by gribozavr** [comment]
If we need to relax the bounds by a little bit, feel free to do so.

**Comment by gparker42** [comment]
That capacity test is dependent on the malloc implementation. It is likely that 13 is the expected result on that Linux version.

**Comment by rintaro** [comment]
@gparker42
The problem is, I'm not sure what should be the acceptable max capacity 😅

**Comment by gribozavr** [comment]
@rintaro Bump it to what's needed on your system, and we can bump it further if it is needed for other systems.  We just don't want to set it too high, since what's the point in checking at all then.

**Comment by rintaro** [comment]
@gribozavr OK, updated to `13` for now :)

**Comment by gribozavr** [comment]
@swift-ci Please test and merge

**Pull request merged**
