### PR TITLE
[CMake] Fix Apple-lldb-Linux.cmake cache used in build-script

### PR DESCRIPTION
**Pull request by weliveindetail**
Fixing an unfortunate inconsistency with upstream..

### CODE REVIEW

**Comment by compnerd** [comment]
This change is required with apple/swift-lldb#1785 as that changes the name of the file.

**Review by compnerd — APPROVED** [review]

**Comment by jrose-apple** [comment]
apple/swift-lldb#1785
@swift-ci Please smoke test

**Comment by weliveindetail** [comment]
Apart from the swift-lldb change, this also requires Saleem's `LLVMDistributionSupport.cmake`. Unfortunately, I can't merge it: https://github.com/apple/swift-llvm/pull/164

**Comment by jrose-apple** [comment]
apple/swift-lldb#1785
apple/swift-llvm#164
@swift-ci Please smoke test

**Comment by weliveindetail** [comment]
I should have copied my comment from the other PR here:
> This is still missing a patch to adjust the downstream-only part of swift-lldb. I will try and get this in today.

**Comment by weliveindetail** [comment]
apple/swift-lldb#1785
apple/swift-llvm#164
@swift-ci Please smoke test

**Comment by weliveindetail** [comment]
build-script passes `--lldb-use-sytem-debugserver`
I will put this on hold until Monday

**Comment by jrose-apple** [comment]
Ah, yeah. You can't *not* use the system debugserver on macOS without, um, something security/entitlements-related that I forgot.

**Comment by compnerd** [comment]
@weliveindetail - that change just needs a rebase, it was marked for the wrong branch.  I was hoping that I could get something that would be fine if I changed the base, but, seems that it needs a rebase :-( - I commented on the original PR to explain the flow.

**Comment by weliveindetail** [comment]
@compnerd
> The change should be made against the wift-5.1-branch. Once that is verified it will flow into stable.
Not sure we want a change like this in swift-5.1-branch on this point.

**Comment by weliveindetail** [comment]
apple/swift-lldb#1785
@swift-ci Please smoke test

**Comment by weliveindetail** [comment]
apple/swift-lldb#1785
@swift-ci Please smoke test

**Comment by weliveindetail** [comment]
apple/swift-lldb#1822
@swift-ci smoke test

**Pull request closed without merging**
