### PR TITLE
[Associated type inference] Support `@_implements` on type witnesses and use it for async sequence `Failure`

### PR DESCRIPTION
**Pull request by DougGregor**
Extend the longstanding support for `@_implements` on witnesses to also work on type witnesses, as part of associated type inference. This permits an associated type witness to have a different name from the associated type itself.

Then ,use that for the type aliases of inferred type witnesses to `AsyncSequence` and `AsyncIteratorProtocol`'s Failure associated type are getting in the way of existing types with the same name. Therefore, when we create these type aliases, given them weird names (e.g., `__AsyncSequence.Failure`) and wire them up with `@_implements(<protocol>, Failure)` so that associated type inference will find them.

This is probably a model we should move to in general, because it's odd that we inject new declarations into types that could cause conflicts. However, start by staging it in for just this one associated type where we have source-compatibility concerns, and we can expand it over time.

Fixes rdar://124362873.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Review by tshortli — COMMENTED** [review]
This seems like it will have condfail implications so it probably ought to have a language feature and swiftinterface suppression.

**Comment by DougGregor** [comment]
> This seems like it will have condfail implications so it probably ought to have a language feature and swiftinterface suppression.

It turns out that older compilers allow the syntax but don't use it. We've had a [benign but correct use](https://github.com/apple/swift/blob/main/stdlib/public/core/RandomAccessCollection.swift#L272-L273) in the standard library for a couple of years.

There is a second [attempted use in the standard library](https://github.com/apple/swift/blob/main/stdlib/public/core/Sequence.swift#L456-L457) that's more troublesome. I want to switch it over to `@_implements`, but the compiler (current and prior) rejects it. Fixing that will definitely force me to add a language feature and swift interface suppression.

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
All source-compatibility failures there are unrelated and under investigation

**Pull request merged**
