### PR TITLE
Merge tag 'swift-DEVELOPMENT-SNAPSHOT-2019-11-20-a' into tensorflow-merge

### PR DESCRIPTION
**Pull request by dan-zheng**
Initial merge commit contains untouched merge conflicts to facilitate review.

---

Issues that surfaced in the merge:
- TF-989: make differentiation transform generate ossa reabstraction thunks.
  This is necessary to re-enable marking the thunks as transparent.
- TF-990: fix control flow differentiation to work with `mergeBasicBlocks`
  called during mandatory inlining.

### CODE REVIEW

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow macOS

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow linux

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow linux cpu

**Comment by dan-zheng** [comment]
Running extended test suite now - they passed previously before merging `tensorflow -> tensorflow-merge`, so it's likely they'll continue to pass.

Results expected within two hours.

**Review by burmako — APPROVED** [review]

**Comment by dan-zheng** [comment]
Extended test suite has passed! Merging.

**Pull request merged**
