### PR TITLE
[5.0][stdlib][SR-2239]: add support for AArch64 variadics

### PR DESCRIPTION
**Pull request by futurejones**
Cherry-pick of: https://github.com/apple/swift/pull/20862
Adds support for AArch64 variadics.

Resolves [SR-2239](https://bugs.swift.org/browse/SR-2239).

Previous issues preventing building of the `swift-5.0-branch` have been fixed by defaulting to the "gold" linker.
This has been updated in https://github.com/apple/swift/pull/20846

We are now seeing successful builds of the `swift-5.0-branch` on AArch64 Linux Ubuntu 16.04
http://futurejones.xyz:8080/job/swift-5.0-aarch64/

### CODE REVIEW

**Comment by tkremenek** [comment]
This can land after https://github.com/apple/swift/pull/20877 is merged

**Review by bob-wilson — CHANGES_REQUESTED** [review]
The corresponding PR for master got a number of review comments. I couldn't tell if those concerns have been addressed (because the PR was merged before the review), but I think not. We should make sure we're happy with the changes and get any follow-up commits included here before merging this.

**Comment by futurejones** [comment]
@bob-wilson @tkremenek  I have assessed the comments of the reviewers of the PR for the master and I have found no issues that need to be addressed before this PR can be merged. 

This code and the other related PR's have been thoroughly tested on the target platform before submitting. 

Suggestions about refactoring code that effect platforms other than AArch64/Linux can be best addressed in future PR's.

**Comment by tkremenek** [comment]
All PRs with the *pending-convergence* label are being held for merging.  The `swift-5.0-branch` branch is being qualified and change is being throttled until we get the branch into a good baseline.  That restriction should hopefully be lifted soon.

**Comment by tkremenek** [comment]
All PRs with the *pending-convergence* label are being held for merging.  The `swift-5.0-branch` branch is being qualified and change is being throttled until we get the branch into a good baseline.  That restriction should hopefully be lifted soon.

**Comment by bob-wilson** [comment]
@futurejones Perhaps other open-source projects work differently, but at least for Swift, the expectation is that you will come to an agreement during the code review process. When I look at https://github.com/apple/swift/pull/20862 I see a bunch of requests for changes that you marked as "resolved" without either changing anything or convincing others to accept your opinion that those changes should be done later. That is not how it works. We really do want your contributions to Swift and I know it can be frustrating to be asked for follow-up changes when you're just trying to get it to work, but we also have to watch out for the long-term quality of the code. Please work with the reviewers to reach a consensus about what to do on the master branch. If that doesn't happen soon, I think we should revert the change from master until the review is completed.

**Comment by futurejones** [comment]
@bob-wilson please see my comments on https://github.com/apple/swift/pull/20862
I hope this satisfies the requirements to get this PR merged. 
 
@tkremenek can we move forward on this please.

**Comment by bob-wilson** [comment]
I will defer to the reviewers of https://github.com/apple/swift/pull/21237 whether they think this should go in to the 5.0 branch with or without those changes (or perhaps a subset of them).

**Comment by drodriguez** [comment]
In my opinion, this one is obsolete after merging #21885 (thanks for that, btw).

**Pull request closed without merging**
