### PR TITLE
[cxx-interop] Pull changes from `swift-6` compat mode into `swift-5.9`

### PR DESCRIPTION
**Pull request by egorzhdan**
This gives projects using C++ interop compat mode 5.9 access to the new features such as virtual methods and move-only types.

rdar://126485814

### CODE REVIEW

**Comment by egorzhdan** [comment]
@swift-ci please test

**Comment by egorzhdan** [comment]
@swift-ci please test macOS

**Comment by hyp** [comment]
Swift-5.10 is not a valid interop version. Do you want to use 5.9 instead?

**Comment by egorzhdan** [comment]
🤦‍♂️ Right, thank you!

**Comment by egorzhdan** [comment]
@swift-ci please test

**Comment by egorzhdan** [comment]
@swift-ci please test

**Comment by egorzhdan** [comment]
@swift-ci please test macOS

**Comment by egorzhdan** [comment]
Hmm, this only seems to fail on macOS, and only with a release compiler:
```
(invalid_conformance)<unknown>:0: error: fatal error encountered during compilation; please submit a bug report (https://swift.org/contributing/#reporting-bugs)
<unknown>:0: note: Invalid conformance in type-checked AST
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Program arguments: /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/swift-macosx-x86_64/bootstrapping0/bin/swift-frontend -frontend -c /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/SwiftCompilerSources/Sources/SIL/ApplySite.swift /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/SwiftCompilerSources/Sources/SIL/Argument.swift /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/SwiftCompilerSources/Sources/SIL/BasicBlock.swift /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/SwiftCompilerSources/Sources/SIL/Builder.swift /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/SwiftCompilerSources/Sources/SIL/Effects.swift /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/SwiftCompilerSources/Sources/SIL/ForwardingInstruction.swift /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/SwiftCompilerSources/Sources/SIL/Function.swift /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/SwiftCompilerSources/Sources/SIL/FunctionConvention.swift /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/SwiftCompilerSources/Sources/SIL/GlobalVariable.swift /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/SwiftCompilerSources/Sources/SIL/Instruction.swift /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/SwiftCompilerSources/Sources/SIL/Location.swift /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/SwiftCompilerSources/Sources/SIL/Operand.swift /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/SwiftCompilerSources/Sources/SIL/Registration.swift /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/SwiftCompilerSources/Sources/SIL/SILStage.swift /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/SwiftCompilerSources/Sources/SIL/SubstitutionMap.swift /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/SwiftCompilerSources/Sources/SIL/Type.swift /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/SwiftCompilerSources/Sources/SIL/Value.swift /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/SwiftCompilerSources/Sources/SIL/VTable.swift /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/SwiftCompilerSources/Sources/SIL/WitnessTable.swift /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/SwiftCompilerSources/Sources/SIL/Utilities/AccessUtils.swift /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/SwiftCompilerSources/Sources/SIL/Utilities/SequenceUtilities.swift /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/SwiftCompilerSources/Sources/SIL/Utilities/SmallProjectionPath.swift /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/SwiftCompilerSources/Sources/SIL/Utilities/WalkUtils.swift -supplementary-output-file-map /var/folders/bb/hcrjxg1s0b96pfst0ymhmp240000gn/T/supplementaryOutputs-334c25 -target x86_64-apple-macosx10.13 -enable-objc-interop -sdk /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -I /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/swift-macosx-x86_64/bootstrapping0/bin/../lib -I /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/lib -I /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/swift-macosx-x86_64/bootstrapping1/SwiftCompilerSources -color-diagnostics -O -cxx-interoperability-mode=default -validate-tbd-against-ir=none -disable-target-os-checking -min-runtime-version 5.9.2 -disable-implicit-string-processing-module-import -external-plugin-path /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/lib/swift/host/plugins#/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/local/lib/swift/host/plugins#/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/swift/host/plugins#/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/lib/swift/host/plugins#/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -plugin-path /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/swift-macosx-x86_64/bootstrapping0/lib/swift/host/plugins -plugin-path /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/swift-macosx-x86_64/bootstrapping0/local/lib/swift/host/plugins -Xcc -std=c++17 -Xcc -DCOMPILED_WITH_SWIFT -Xcc -DSWIFT_TARGET -Xcc -UIBOutlet -Xcc -UIBAction -Xcc -UIBInspectable -Xcc -UNDEBUG -Xcc -I -Xcc /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/llvm-project/llvm/include -Xcc -I -Xcc /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/llvm-macosx-x86_64/include -Xcc -I -Xcc /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/llvm-project/clang/include -Xcc -I -Xcc /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/llvm-macosx-x86_64/tools/clang/include -Xcc -I -Xcc /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/include -Xcc -I -Xcc /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/swift-macosx-x86_64/SwiftCompilerSources/../include -target-sdk-version 14.2 -dwarf-version=4 -parse-as-library -module-name SIL -cross-module-optimization -o /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/swift-macosx-x86_64/bootstrapping1/SwiftCompilerSources/SIL.o
1.	Apple Swift version 6.0-dev (LLVM a28c877176ffe52, Swift 567052f5bdf0824)
2.	Compiling with effective version 5.10
3.	While evaluating request ASTLoweringRequest(Lowering AST to SIL for module SIL)
4.	While silgen emitFunction SIL function "@$s3SIL7OperandV2eeoiySbAC_ACtFZ".
 for '==(_:_:)' (at /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/SwiftCompilerSources/Sources/SIL/Operand.swift:30:10)

```

**Comment by egorzhdan** [comment]
Ah! We're importing `swift::Operand * _Nonnull op` as `UnsafeMutablePointer<swift.Operand>` where `swift.Operand` is a non-copyable type, but the current version of the Swift stdlib doesn't yet support non-copyable generics, which means `UnsafeMutablePointer<swift.Operand>` isn't a valid type 🤯

**Comment by egorzhdan** [comment]
@swift-ci please test

**Comment by egorzhdan** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
