### PR TITLE
Update master to build with Xcode 9 beta 4

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci Please test Linux

**Comment by moiseev** [comment]
@swift-ci  Please test Linux

**Comment by shahmishal** [comment]
@swift-ci Please test Linux

**Comment by AnshulYADAV007** [comment]
Hey @shahmishal,

I want to contribute to Swift. Currently I am doing two online courses viz "Compilers" by Stanford Lagunita and "Developing iOS 10 Apps with swift" on ITunes U. I have done my graduation in Computer Science and Engineering, thus you can assume knowledge of Datastructures and Algorithms and concepts of OOPs. Will these courses be sufficient for the theoretical knowledge needed to contribute to this project?  Or should I choose some other courses before contributing to this project. 

Please guide me about the preparation part for contributing to the project. Here is my email address: anshulyadav98@gmail.com.

Thanks

**Pull request merged**
