### PR TITLE
[DNM] test toolchain build

### PR DESCRIPTION
**Pull request by tomerd**
for testing https://github.com/apple/swift-package-manager/pull/5989

### CODE REVIEW

**Comment by tomerd** [comment]
https://github.com/apple/swift-package-manager/pull/5989

@swift-ci please build toolchain macOS platform

**Comment by tomerd** [comment]
cc @neonichu

**Comment by neonichu** [comment]
```
"/var/folders/pf/p5g2vb2j0yx1x6vlmxdppc700000gn/T/TemporaryDirectory.H7eDjQ/swiftpm-manifest"])
/Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/swiftpm/Package.swift:16:8: error: module compiled with Swift 5.5 cannot be imported by the Swift 5.8 compiler: /Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/buildbot_osx/intermediate-install/macosx-x86_64/Library/Developer/Toolchains/swift-PR-62749-465.xctoolchain/usr/lib/swift/pm/ManifestAPI/PackageDescription.swiftmodule/x86_64-apple-macos.swiftmodule
import PackageDescription
       ^
```

**Comment by tomerd** [comment]
https://github.com/apple/swift-package-manager/pull/5989

@swift-ci please build toolchain macOS platform

**Pull request closed without merging**
