### PR TITLE
ASTDemangler: Add support for member types of opaque result types

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes <rdar://problem/63188053>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by jckarter** [comment]
Thanks Slava!

**Review by jckarter — APPROVED** [review]

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Comment by slavapestov** [comment]
@swift-ci Please clean smoke test Linux

**Comment by slavapestov** [comment]
@swift-ci Please clean smoke test Linux

**Comment by slavapestov** [comment]
@swift-ci Please clean smoke test Linux

**Comment by slavapestov** [comment]
@swift-ci Please clean smoke test Linux

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Pull request merged**
