### PR TITLE
[update-checkout] Pin swift-crypto to a version

### PR DESCRIPTION
**Pull request by yim-lee**
[swift-crypto v1.1.4](https://github.com/apple/swift-crypto/releases/tag/1.1.4) has all the changes we need and we can pin to that version instead of `main`.

### CODE REVIEW

**Comment by yim-lee** [comment]
@swift-ci test

**Comment by yim-lee** [comment]
@swift-ci Please Test Source Compatibility

**Comment by yim-lee** [comment]
@tomerd @neonichu @shahmishal

**Review by tomerd — APPROVED** [review]

**Comment by tomerd** [comment]
```
java.io.EOFException
13:35:22 	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2759)
13:35:22 	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3234)
13:35:22 	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:913)
13:35:22 	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:375)
13:35:22 	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
13:35:22 	at hudson.remoting.Command.readFrom(Command.java:142)
13:35:22 	at hudson.remoting.Command.readFrom(Command.java:128)
13:35:22 	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
13:35:22 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
13:35:22 Caused: java.io.IOException: Unexpected termination of the channel
13:35:22 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
13:35:22 Caused: java.io.IOException: Backing channel 'ubuntu-16.04-05' is disconnected.
13:35:22 	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:216)
13:35:22 	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:285)
13:35:22 	at com.sun.proxy.$Proxy73.isAlive(Unknown Source)
13:35:22 	at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1147)
13:35:22 	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1139)
13:35:22 	at hudson.tasks.CommandInterpreter.join(CommandInterpreter.java:155)
13:35:22 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:109)
13:35:22 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
13:35:22 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
13:35:22 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
13:35:22 	at hudson.model.Build$BuildExecution.build(Build.java:206)
13:35:22 	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
13:35:22 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
13:35:22 	at hudson.model.Run.execute(Run.java:1880)
13:35:22 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
13:35:22 	at hudson.model.ResourceController.execute(ResourceController.java:97)
13:35:22 	at hudson.model.Executor.run(Executor.java:428)
13:35:22 FATAL: Unable to delete script file /tmp/jenkins2330423680142586913.sh
13:35:22 
java.io.EOFException
13:35:22 	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2759)
13:35:22 	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3234)
13:35:22 	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:913)
13:35:22 	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:375)
13:35:22 	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
13:35:22 	at hudson.remoting.Command.readFrom(Command.java:142)
13:35:22 	at hudson.remoting.Command.readFrom(Command.java:128)
13:35:22 	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
13:35:22 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
13:35:22 Caused: java.io.IOException: Unexpected termination of the channel
13:35:22 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
13:35:22 Caused: hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@2822954a:ubuntu-16.04-05": Remote call on ubuntu-16.04-05 failed. The channel is closing down or has closed down
13:35:22 	at hudson.remoting.Channel.call(Channel.java:991)
13:35:22 	at hudson.FilePath.act(FilePath.java:1069)
13:35:22 	at hudson.FilePath.act(FilePath.java:1058)
13:35:22 	at hudson.FilePath.delete(FilePath.java:1543)
13:35:22 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:123)
13:35:22 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
13:35:22 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
13:35:22 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
13:35:22 	at hudson.model.Build$BuildExecution.build(Build.java:206)
13:35:22 	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
13:35:22 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
13:35:22 	at hudson.model.Run.execute(Run.java:1880)
13:35:22 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
13:35:22 	at hudson.model.ResourceController.execute(ResourceController.java:97)
13:35:22 	at hudson.model.Executor.run(Executor.java:428)
13:35:22 Build step 'Execute shell' marked build as failure
```

@shahmishal node disconnected?

**Comment by tomerd** [comment]
@swift-ci test Linux

**Comment by shahmishal** [comment]
Ubuntu-16.04-05 is having issue, going to take it offline.

**Comment by tomerd** [comment]
@swift-ci smoke test

**Pull request merged**
