### PR TITLE
Sema: Remove unnecessary circularity breaks

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@CodaFi This isn't ready to merge yet because it depends on the request-ification of checkRawValues().

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Review by CodaFi — APPROVED** [review]
I love it!  By the by, source breaks in debug builds only are indicative of assertions kicking off requests.

**Comment by slavapestov** [comment]
@jckarter When you get a chance do you mind taking a look at the OpaqueTypeDecl stuff?

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Pull request merged**
