### PR TITLE
[SILOpt] Apply _Class pre-specializations to wrapped single references

### PR DESCRIPTION
**Pull request by drexin**
rdar://119047505

A struct wrapping a single reference has an identical layout to the reference itself, so we can apply the same pre-specializations.

### CODE REVIEW

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by aschwaighofer** [comment]
Does the code (`lowered.hasRetainablePointerRepresentation`) behave correctly for over aligned structs?

```
@_alignment(16)
struct S {
  var c : SomeClass
}
```

**Comment by drexin** [comment]
@swift-ci smoke test

**Review by aschwaighofer — APPROVED** [review]

**Comment by drexin** [comment]
@swift-ci smoke test windows

**Pull request merged**
