### PR TITLE
Runtime hook for logging on the use of unstable runtime names with NSCoding

### PR DESCRIPTION
**Pull request by jrose-apple**
- **Explanation**: Foundation's standard serialization mechanism, NSKeyedArchiver, can end up storing mangled names into persistent archives, which isn't really a good idea. This provides a run-time hook that Foundation can call (on a new enough OS) to validate that we're not doing such a thing. (Consider it the run-time half of #10155.)
- **Scope**: Affects classes that conform to NSCoding that do not have "simple" mangled names, if they are actually archived or unarchived.
- **Radar**: rdar://problem/32414508
- **Reviewed by**: me (@eeckstein's parts), @itaiferber (my parts)
- **Risk**: Low. This adds a new entry point via the Foundation overlay; nothing uses it yet. The only change to existing classes is the new metadata flag, which nothing else is reading.
- **Testing**: Added compiler regression tests.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
Whoops. Fix in #10433. Waiting for that to pass on master first.

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by DougGregor** [comment]
Shouldn't this use the new runtime diagnostic infrastructure?

**Comment by ematejska** [comment]
@swift-ci Please test os x

**Comment by jrose-apple** [comment]
@swift-ci Please test macOS

**Comment by jrose-apple** [comment]
Whoops, full tests for a release branch.

@swift-ci Please test Linux

**Comment by jrose-apple** [comment]
@DougGregor: I talked to @kubamracek about that and we weren't sure it applied here:
- This is not a fatal error, so it may not be worth interrupting your program over.
- On decode, there's no particular stack frame that's relevant.
- You may not have the source of the class in question. (Imagine trying to archive a generic class from the standard library.)
- Other API misuse in Foundation won't get the same treatment.

Since the "runtime issues" infrastructure is getting added so late, I decided not to complicate discussions of either feature by linking them together. We can always consider changing it in a later release, or making it something that's used generally throughout the SDKs.

**Comment by DougGregor** [comment]
Point-by-point...

* SE-0160 produces warnings already, not fatal errors, so that's already handled by the infrastructure @kubamracek added.
* When decoding, it is useful to know what initiated the decode. Where did we get the archive with this class it's warning from? I guess it's annoying that we don't know how many frames to skip, but stack trace is better than no stack trace.
* Not having the source to the class in question is a problem regardless of whether you're logging normally or going through the new infrastructure
* Maybe other uses of Foundation APIs should get this treatment :)

Yes, it's new infrastructure, but it's also a bit improvement.

**Comment by jrose-apple** [comment]
Okay, I'll file a follow-up bug to consider adopting it in the Swift 4 timeframe. I do want to make sure the basic thing does get in, at least.

**Comment by jrose-apple** [comment]
Filed <rdar://problem/32900735> Use the new runtime issues infrastructure for reporting NSCoding issues.

**Comment by DougGregor** [comment]
WFM, thank you!

**Pull request merged**
