### PR TITLE
Move explicit module frontend options out of the set of flags emitted into module interfaces.

### PR DESCRIPTION
**Pull request by artemcm**
They never belonged there and were placed there by accident.

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci please test

**Review by beccadax — APPROVED** [review]
Looks good, but unfortunately, I'm about to cause a merge conflict: https://github.com/apple/swift/pull/34068

**Comment by artemcm** [comment]
> Looks good, but unfortunately, I'm about to cause a merge conflict: #34068

I'll rebase after, thanks for the heads up. 👍

**Review by DougGregor — APPROVED** [review]

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Pull request merged**
