### PR TITLE
[AutoDiff] Support differentiating w.r.t. not all parameters

### PR DESCRIPTION
**Pull request by rxwei**
* When computing minimal differentiation indices for an `apply`, we must check whether a function argument is an argument being differentiated w.r.t. in the parent function. In that case, even though the value. For example:
    ```swift
    func f(x: Float, y: Float, z: Float) -> Float {
        g(x, 0, z)
          ^     ^
        These should be differentiated w.r.t. even when they are not ACTIVE per activity analysis.
    }
    ```
* Different differentiation indices should use different primal value structs.

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux CPU

**Review by marcrasi — APPROVED** [review]

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux CPU

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux CPU

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux CPU

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux CPU

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux CPU

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux CPU

**Pull request merged**
