### PR TITLE
[Protocol Metadata] Create protocol metadata using WeakAnyLinkage to avoid duplication

### PR DESCRIPTION
**Pull request by ghost**
I've noticed that some SWIFT binaries show duplicate metadata entries such as __PROTOCOL_NSObject along with all descending linked metadata.
The Issue is that the protocol global is created with internal linkage. Because of the internal linkage, the linker will not merge identical records in the final output.
The fix is to update the linkage type to WeakAnyLinkage, same as in ObjC.

Also, from review feedback, we also match the visibility with ObjC visibility(GlobalValue::HiddenVisibility);

Resolves SR-15376.

### CODE REVIEW

**Comment by aschwaighofer** [comment]
I think we also should match the visibility by setting it to hidden.

```
  GV->setVisibility(GlobalValue::HiddenVisibility);
```

https://github.com/llvm/llvm-project/blob/1c2d3338eb8a280fc49eef143f502c5f44f72e4c/clang/lib/CodeGen/CGObjCMac.cpp#L7074

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test

**Comment by gmittert** [comment]
@swift-ci please smoke test linux

**Comment by CodaFi** [comment]
@swift-ci test Linux platform

**Comment by aschwaighofer** [comment]
@swift-ci Please test macOS

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by gmittert** [comment]
@swift-ci please smoke test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by gmittert** [comment]
@swift-ci please smoke test

**Pull request merged**
