### PR TITLE
Add support for UnsafeRawBufferPointer to DispatchData

### PR DESCRIPTION
**Pull request by ktopley-apple**
(Radar 28503167)

rdar://problem/28503167

### CODE REVIEW

**Comment by ktopley-apple** [comment]
@mwwa @das @moiseev @jrose-apple please review

**Comment by jrose-apple** [comment]
(commented in apple/swift-corelibs-libdispatch#230)

**Comment by ktopley-apple** [comment]
Updated for review comments from  apple/swift-corelibs-libdispatch#230.

**Comment by ktopley-apple** [comment]
@swift-ci please test

**Review by mwwa — APPROVED** [review]

**Comment by ktopley-apple** [comment]
@swift-ci please merge

**Comment by moiseev** [comment]
@ktopley-apple this command does not exist. You have to click the merge button yourself =)

**Comment by ktopley-apple** [comment]
I would love to, but I don't have a merge button in this repo ;-)

**Comment by ktopley-apple** [comment]
Thank you :-)

**Comment by jrose-apple** [comment]
^ @tkremenek: Kim should probably have access here too.

**Pull request merged**
