### PR TITLE
[CS] Refactor IUO handling

### PR DESCRIPTION
**Pull request by hamishknight**
The current IUO design always forms a disjunction at the overload reference, for both:

- An IUO property `T!`, forming `$T := T? or T`
- An IUO-returning function `() -> T!`, forming `$T := () -> T? or () -> T`

This is simple in concept, however it's suboptimal for the latter case of IUO-returning functions for a couple of reasons:

- The arguments cannot be matched independently of the disjunction
- There's some awkwardness when it comes e.g wrapping the overload type in an outer layer of optionality such as `(() -> T!)?`:
  - The binding logic has to "adjust" the correct reference type after forming the disjunction.
  - The applicable fn solving logic needs a special case to handle such functions.
- The CSApply logic needs various hacks such as ImplicitlyUnwrappedFunctionConversionExpr to make up for the fact that there's no function conversion for IUO functions, we can only force unwrap the function result.
  - This lead to various crashes in cases where we we'd fail to detect the expr and peephole the force unwrap.
  - This also lead to crashes where the solver would have a different view of the world than CSApply, as the former would consider an unwrapped IUO function to be of type `() -> T` whereas CSApply would correctly see the overload as being of type `() -> T?`.

To remedy these issues, IUO-returning functions no longer have their disjunction formed at the overload reference. Instead, a disjunction is formed when matching result types for the applicable fn constraint, using the callee locator to determine if there's an IUO return to consider. CSApply then consults the callee locator when finishing up applies, and inserts the force unwraps as needed, eliminating ImplicitlyUnwrappedFunctionConversionExpr.

This means that now all IUO disjunctions are of the form `$T := T? or T`. This will hopefully allow a further refactoring away from using disjunctions and instead using type variable binding logic to apply the correct unwrapping.

Fixes SR-10492
Resolves: rdar://50169820

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by slavapestov** [comment]
Nice cleanup!

**Comment by hamishknight** [comment]
@swift-ci please test compiler performance

**Comment by hamishknight** [comment]
@swift-ci please SourceKit stress test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Review by xedin — COMMENTED** [review]
Looks great! Using a disjunction at-the-point-of-IUO definitely makes more sense. We have talked about this offline but I'm going to leave it here as well - I think ultimately we can get rid of a disjunction all together by allocating an intermediate type variable in `matchFunctionResultTypes` that is _not_ going to be bindable directly but instead binding inference would choice whether to use optional or unwrapped type based on conversion constraints associated with it, this way there is not going to be any "guessing" involved.

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
@swift-ci please SourceKit stress test

**Comment by hamishknight** [comment]
@swift-ci please test compiler performance

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
@swift-ci please test

**Review by xedin — APPROVED** [review]
Looks great, thank you, Hamish! I think we can land this and follow-up with more changes to eliminate a disjunction from IUO handling.

**Comment by hamishknight** [comment]
@swift-ci please test

**Pull request merged**
