### PR TITLE
[NFC] Some Small Performance Improvements to Evaluator Dependencies

### PR DESCRIPTION
**Pull request by CodaFi**

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci test performance

**Comment by CodaFi** [comment]
@swift-ci test performance

**Comment by CodaFi** [comment]
@swift-ci test compiler performance

**Review by davidungar — APPROVED** [review]
Looks fine, but not an area I know much about. Good to get the performance.

**Pull request closed without merging**
