### PR TITLE
Enable test case Integers.swift.gyb under x86_64 (and hence Linux x86_64)

### PR DESCRIPTION
**Pull request by practicalswift**
#### What's in this pull request?

Enable test case `Integers.swift.gyb` under `x86_64` (and hence `Linux x86_64`).
#### Resolved bug number: –

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by tkremenek** [comment]
@swift-ci please test

**Comment by practicalswift** [comment]
@swift-ci Please test again - I believe the build failure is spurious :-)

**Comment by gottesmm** [comment]
@swift-ci Please test OS X Platform

(Not reviewing, just drive by starting test)

**Comment by gottesmm** [comment]
@swift-ci Please test OS X Platform

**Comment by practicalswift** [comment]
Is the OS X error real? Everything works fine under Linux and considering that this test was enabled previously under OS X this change shouldn't change the state of things under OS X :-)

**Comment by jrose-apple** [comment]
Yes, that's real. OS X includes the iOS simulators, and the failure is happening on the i386 simulator. Apparently we can't generate the double-width multiplication there; it's probably something that compiler-rt provides since there's no hardware support.

**Comment by practicalswift** [comment]
@jrose-apple Ah, I see. I've now changed from `CPU=i386_or_x86_64` to `CPU=x86_64`. That should solve the issue? :-)

**Comment by practicalswift** [comment]
@swift-ci Please test :-)

**Comment by gribozavr** [comment]
@swift-ci Please test and merge

**Pull request merged**
