### PR TITLE
[NFC] Centralize lookup of NSCopying

### PR DESCRIPTION
**Pull request by beccadax**
Adds `NSCopying` to ~~KnownProtocols.def~~ the `ASTContext::get<name>Decl()` mechanism, removes it from KnownFoundationEntities.def, and updates a couple places where we looked it up manually to use ~~`ASTContext::getProtocol()`~~ `ASTContext::getNSCopyingDecl()` .

### CODE REVIEW

**Comment by brentdax** [comment]
@swift-ci please smoke test

**Review by harlanhaskins — APPROVED** [review]
Nice!

**Comment by jrose-apple** [comment]
Probably supersedes the ClangImporter's getNSCopyingType, too.

**Comment by brentdax** [comment]
@jrose-apple I think `getNSCopyingType()` gets the clang version of the type. Am I wrong? Or is that true but not an obstacle?

**Comment by jrose-apple** [comment]
No, it's going for the type-as-imported. But maybe it makes sense for Clang to do the lookup more directly. (Or maybe it doesn't, since we have lookup tables for Swift.)

**Comment by jrose-apple** [comment]
Anyway, that doesn't have to go into this PR.

**Comment by brentdax** [comment]
@swift-ci please smoke test

**Comment by brentdax** [comment]
The KnownProtocol mechanism uses a form of lookup that doesn’t look into underlying clang modules, so I had to switch approaches, instead sharing implementation with e.g. `getNSErrorDecl()`.

**Review by jrose-apple — COMMENTED** [review]
Still seems worth it!

**Comment by brentdax** [comment]
@jrose-apple I've converted over the `ClangImporter` use too. (I tried doing the same thing for the use of `NSObjectProtocol`, but the straightforward change broke a test involving a typedef'd protocol and I didn't want to go off on a tangent debugging it.)

@swift-ci please smoke test

**Pull request merged**
