### PR TITLE
Fix macOS test failures.

### PR DESCRIPTION
**Pull request by dan-zheng**
Currently, there are three failing tests on macOS:
```
Failing Tests (3):
    Swift(macosx-x86_64) :: Interpreter/SDK/objc_bridge_cast.swift
    Swift(macosx-x86_64) :: stdlib/CoreMediaOverlay.swift
    Swift(macosx-x86_64) :: stdlib/CoreMedia.swift
```
The last two tests are fixed by cherry-picking https://github.com/apple/swift/commit/0a23ccfe7f993430544359f698cfd125529506e0 from upstream.
The first test is temporarily marked as unsupported.

### CODE REVIEW

**Comment by rxwei** [comment]
Is this a cherry-pick merge?

**Comment by rxwei** [comment]
Better not squash this one.

**Review by rxwei — APPROVED** [review]

**Comment by dan-zheng** [comment]
I confirmed that all tests pass on my macOS machine.
@marcrasi, do you agree that this PR should not be squashed? One commit is cherry-picked from master and one commit is my own. I'm not sure what merge strategy is best.

**Review by marcrasi — APPROVED** [review]
Yeah, I think a merge will be best for this.

It'll make it really clear in the git history that we have a cherry-pick, which should make it easier to pull in the upstream changes that include the cherry-picked commit. Maybe git will even figure everything out automatically.

**Comment by dan-zheng** [comment]
@marcrasi Thanks! I'll merge without squashing.

**Pull request merged**
