### PR TITLE
[NO MERGE][+0->+1]

### PR DESCRIPTION
**Pull request by gottesmm**
Just for testing/visibility/etc.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
This was landed via a different PR.

**Comment by gottesmm** [comment]
Oops actually I am wrong. Confused this with a different PR.

**Comment by CodaFi** [comment]
@gottesmm Do you still want this old PR?

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
