### PR TITLE
Add a -verify-linetable LLVM option.

### PR DESCRIPTION
**Pull request by adrian-prantl**
While stepping through Swift programs in LLDB I noticed that sometimes
the line table entries go like this:

```
  foo(bar(baz)) // Some auxiliary code for the entire expression.
  ^

  foo(bar(baz))
      ^

  foo(bar(baz)) // And then back again for that actual call to foo.
  ^

```

This verification step is aimed at identifying situations like this so
they can be fixed.

<rdar://problem/44317688>

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by vedantk** [comment]
I think we should try to fix a handful of issues identified by this check before merging it (per the rationale in https://reviews.llvm.org/D46100#1079885). It would be useful to pass this over the source compatibility suite, see what we find, and make sure that the assumptions in the assert are valid.

**Comment by vedantk** [comment]
That said, the assert does look good to me.

**Review by dcci — COMMENTED** [review]
This looks sane. How many failures do we have if we flip the switch to true?

**Comment by adrian-prantl** [comment]
It doesn't even compile trivial programs such as swift/test/DebugInfo/guard-let.swift without asserting. Here's is the debug output for it:

```
clear
clear
insert(20,19)
clear
clear
clear
insert(20,28)
clear
insert(22,1)
clear
clear
insert(20,19)
clear
insert(20,28)
clear
insert(22,1)
insert(20,19)
insert(21,7)
insert(21,3)
insert(22,1)
```

**Comment by adrian-prantl** [comment]
fnptr.swift
```
clear
insert(51,1)
clear
insert(14,21)
insert(14,5)
insert(22,5)
insert(35,21)
insert(35,5)
insert(36,5)
insert(36,15)
insert(36,5)
```

**Comment by adrian-prantl** [comment]
Hopefully these failures can all be tracked down to very few root causes.

**Pull request merged**
