### PR TITLE
[5.9] MultiDefPrunedLiveness: add support for arbitrary uses/defs

### PR DESCRIPTION
**Pull request by atrick**
This now supports liveness holes within blocks where previously we
expected a phi def.

PrunedLiveness is streamlined for SSA liveness where we expect the
defs and uses to be related in the SSA def-use graph.
MultiDefPrunedLiveness was added on top of SSAPrunedLivenes to handle
extended SSA liveness that occurs with phis, but are still connected
in the def-use graph. Recently MultiDefPrunedLiveness was repurposed
for liveness of addressible storage. This means that we can now have
uses before defs in the same block without a corresponding phi.

Fortunately, handling this case is a straightforward extension of
MultiDefPrunedLiveness that does not complicate or penalize the
streamlined SSA case.

Fixes rdar://107740403 ([move-only] Add support for addressable values in MultiDefPrunedLiveness)

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test

**Review by nate-chandler — APPROVED** [review]

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@tbkka could you merge this if it looks ok to cherry-pick. It doesn't directly fix any bugs, but a bug could arise if future cherry-picks depend on the new behavior. And @gottesmm  will need equivalent logic to check noncopyable types.

**Review by tbkka — APPROVED** [review]

**Pull request merged**
