### PR TITLE
Bitstream api

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC @bob-wilson

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by jrose-apple** [comment]
This is a good start but it's not sufficient. We'll also need to rework the loops to check for isAtEndOfStream, like apple/swift-clang#37.

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@jrose-apple any suggestions on how to go about diagnosing why Im seeing an invalid ID for the decl?  (hitting the "declaration ID out-of-range for AST file" assertion in `ASTReader::GetDecl`).

**Comment by jrose-apple** [comment]
That sounds like a Clang module cache didn't get rebuilt.

**Comment by bob-wilson** [comment]
I included these changes in the latest master-next merge. There was a bug in the change to remove the BitstreamReader where there was a duplicate call to advance the cursor. I fixed that in 343fe88

**Pull request closed without merging**
