### PR TITLE
[Exclusivity] Enforce exclusive access for class offsets in KeyPaths

### PR DESCRIPTION
**Pull request by atrick**
Add dynamic enforcement of exclusive access when a KeyPath directly accesses a final
stored property on an instance of a class. For read-only projections, this begins and ends
the access immediately. For mutable projections, this uses the ClassHolder to perform
a long-term access that lasts as long as the lifetime of the ClassHolder.

rdar://problem/31972680

Follow up on: @devincoughlin https://github.com/apple/swift/pull/15502
and: @gottesmm https://github.com/apple/swift/pull/16016

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test.

**Review by gottesmm — APPROVED** [review]
LGTM!

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
@swift-ci test source compatibility.

**Comment by atrick** [comment]
@swift-ci test source compatibility

**Pull request merged**
