### PR TITLE
Concurrency: Implement withUnsafe[Throwing]Continuation

### PR DESCRIPTION
**Pull request by slavapestov**
This PR introduces two new entry points named `withUnsafe[Throwing]Continuation()` in the `_Concurrency` module. The two new entry points have the following types:

```
withUnsafeContinuation: <T> ((UnsafeContinuation<T>) -> Void) async -> T
withUnsafeThrowingContinuation: <T> ((UnsafeThrowingContinuation<T>) -> Void) async throws -> T
```

These are handy for when you want to manually wrap callback-based code with an async interface.

Example (no-op) usage:

```
let x: Int = await withUnsafeContinuation { c in c.resume(123) }
// x = 123
```

Note that the continuation's `resume()` method is not implemented yet, though.

These new functions are implemented in terms of two new built-ins, `Builtin.withUnsafe[Throwing]Continuation()`, which traffic in a new `Builtin.RawUnsafeContinuation` type. The built-ins lower to the existing SIL `get_async_continuation`/`await_async_continuation` instructions, with a call to the provided function value in the middle. In order for the library wrappers to lower to the same SIL as direct usage of the builtins, I marked the wrappers as `@_alwaysEmitIntoClient`, and also added explicit `@_alwaysEmitIntoClient` initializers to `Unsafe[Throwing]Continuation<T>`.

I changed the SIL instructions to traffic in the new `Builtin.RawUnsafeContinuation` type rather than `Unsafe[Throwing]Continuation<T>`. Instead, the wrapping of the continuation value in a `Unsafe[Throwing]Continuation<T>` is handled elsewhere, in the library code and SILGen's bridging logic.

Fixes rdar://problem/71125023.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Review by jckarter — APPROVED** [review]
Looks great, thanks Slava!

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Review by aschwaighofer — APPROVED** [review]
The IRGen part LGTM, thank you.

**Review by rjmccall — APPROVED** [review]
LGTM

**Comment by DougGregor** [comment]
@swift-ci please smoke test Linux

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
