### PR TITLE
[CS] A couple of minor `-debug-constraints` improvements

### PR DESCRIPTION
**Pull request by hamishknight**
Deindent a couple of log messages, and ensure we always log the failure of a constraint.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Review by xedin — APPROVED** [review]
I think since we have switched completely to the new diagnostic framework I don't think we need a notion of `failing constraint` anymore. It used to be a fallback thing before for diagnostics.

**Comment by hamishknight** [comment]
@xedin Hmm, surely we still need it when not in diagnostic mode?

**Comment by xedin** [comment]
I don't think we need to record a constraint just the fact that something previously failed.

**Comment by hamishknight** [comment]
@swift-ci please test macOS

**Comment by hamishknight** [comment]
@xedin Could you elaborate a little on what that would look like? Would e.g the callers of `addConstraint` need to handle the failure themselves if the constraint system no longer tracks it?

**Comment by xedin** [comment]
Sure! The most common pattern we currently have is a check for `failedConstraint` to avoid trying to call `simplify` e.g. (`CS.failedConstraint || CS.simplify()`). I think we could record whether anything failed as a flag in `SolverState` instead and shortcut directly in `simplify()`...

**Comment by hamishknight** [comment]
@xedin Sounds good! I'll merge this for now, and take care of that in a follow-up.

**Comment by xedin** [comment]
@hamishknight Yeah, no worries!

**Pull request merged**
