### PR TITLE
[TypeChecker] SE-0324: Extend Swift -> C pointer conversions to arrays

### PR DESCRIPTION
**Pull request by xedin**
Extends implementation to support conversions between arrays
and pointers (when element type is an (un-)signed integer) that are
allowed by the SE-0324 proposal.

Resolved: rdar://99089335

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
Interesting, looks like my changes made existing conversion slightly more narrow...

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
Debug build failure seems unrelated:

```
Undefined symbols for architecture x86_64:
  "(extension in XCTest):__C.XCTestCase.addTeardownBlock(() async throws -> ()) -> ()", referenced from:
      SWIMNIOExampleTests.BaseClusteredXCTestCase.setUp() -> () in BaseXCTestCases.swift.o
ld: symbol(s) not found for architecture x86_64
```

**Comment by xedin** [comment]
Indeed it fails on main branch as well i.e. https://ci.swift.org/job/swift-main-source-compat-suite-debug/362/

**Review by hborla — APPROVED** [review]

**Comment by atrick** [comment]
@xedin looks great! Thanks for taking care of this.

**Pull request merged**
