### PR TITLE
[CSDiag] Diagnose KeyPath tuple access as unsupported even when sugared

### PR DESCRIPTION
**Pull request by xedin**
Follow-up for [SR-9213](https://bugs.swift.org/browse/SR-9213)

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by theblixguy** [comment]
Great @xedin! Do you have any idea where I need to start if I want to add support for tuple KeyPaths? I have seen Joe mention it in the Swift forums and how it could be a "starter bug". I've spent a bit of time understanding how KeyPaths are implemented, but not totally sure where to begin. Any direction/tips would be greatly appreciated! 😃

**Comment by slavapestov** [comment]
Does this also fix rdar://37160546 and rdar://34186458?

**Comment by xedin** [comment]
@theblixguy I'm actually not sure what exactly is going on with that... @jckarter could you please clarify a bit (if we don't have an SR for this already)?

**Comment by xedin** [comment]
@slavapestov Unfortunately not, these actually produce solution but then crash trying to apply it.

@theblixguy If you are interested these are the SR for both issues:
 - https://bugs.swift.org/browse/SR-6906
 - https://bugs.swift.org/browse/SR-4888

Trying to fix these might shed some light on what needs to be done to support tuples in keypath expressions.

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by jckarter** [comment]
> Trying to fix these might shed some light on what needs to be done to support tuples in keypath expressions.

The main thing missing to support tuples is a representation in AST KeyPathExpr and in SIL's KeyPathPattern for tuple components. The runtime implementation could readily support tuple fields using the same code as for structs.

**Pull request merged**
