### PR TITLE
Back-deploy concurrency

### PR DESCRIPTION
**Pull request by DougGregor**
Back-deployment support for Swift concurrency.

### CODE REVIEW

**Comment by yehiabairm** [comment]
@swift-ci  please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please build toolchain macOS

**Comment by DougGregor** [comment]
@swift-ci please test macOS

**Comment by DougGregor** [comment]
@swift-ci please build toolchain macOS

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please build toolchain macOS

**Comment by DougGregor** [comment]
@swift-ci please test macOS

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please build toolchain macOS

**Comment by DougGregor** [comment]
This is actually wonderful news:
```
Test Result (5 failures / -6)
Swift(macosx-x86_64).BuildSystem.infer_dumps_deps_if_verbose_build.test
Swift(macosx-x86_64).BuildSystem.infer_implies_install_all.test
Swift(macosx-x86_64).Python.build_swift.swift
Swift(macosx-x86_64).Python.python_lint.swift
Swift(macosx-x86_64).Python.swift_build_support.swift
```

It's just silly pedantic Python failures that don't matter.

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please build toolchain macOS

**Comment by DougGregor** [comment]
@swift-ci please test Windows

**Review by ViniciusDeep — APPROVED** [review]

**Review by airspeedswift — APPROVED** [review]

**Comment by DougGregor** [comment]
Alright, there's a bit more to come here to fix some known bugs, but this is a good baseline to land. :shipit:

**Comment by unnamedd** [comment]
Woohoo!!! Great work done here @DougGregor!

**Pull request merged**
