### PR TITLE
Foundation: fix typo in Publishers+Timer.swift

### PR DESCRIPTION
**Pull request by MaxDesiatov**
`addSubsriber` -> `addSubscriber`

### CODE REVIEW

**Comment by CodaFi** [comment]
A heads up that even though the overlays are still visible in this project, they are owned by Foundation. In order for this change to take full effect, Foundation needs to reflect this change on their end. rdar://63545357

@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
@CodaFi do you mean Apple's proprietary Foundation or apple/swift-corelibs-foundation repository?

**Comment by CodaFi** [comment]
The former. The overlays have been returned to the framework authors themselves.

**Comment by bendjones** [comment]
Oops! Thanks for this will CP to the proper place.

**Comment by bendjones** [comment]
CC @parkera @phausler

**Review by parkera — APPROVED** [review]

**Comment by parkera** [comment]
Thank you!

**Pull request merged**
