### PR TITLE
[CS] Resolve callees for key path components

### PR DESCRIPTION
**Pull request by hamishknight**
This PR changes `getCalleeLocator` such that it now takes a `ConstraintLocator` argument, allowing it to resolve callees for cases where we have a `KeyPathExpr` base and a `KeyPathComponent` locator element. To make it clear that we're looking for a callee at the anchor, this PR also renames it to `getAnchormostCalleeLocator` (open to alternative naming suggestions).

This change is then plumbed through to CSDiagnostics, where `getAnchormostChoiceFor` can be used to get the choice for the anchor of a given locator. Finally, a `getAnchormostChoice` member has been added to make the common case of getting the choice made for the anchor of the failure more convenient.

Resolves [SR-11435](https://bugs.swift.org/browse/SR-11435).

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Review by xedin — APPROVED** [review]
Looks great! I like updated logic but I not sure sure about the naming, maybe we should keep names the same? When it comes to key path component locators I think original naming still makes sense, if locator points to a component you get a locator to retrieve overload choice associated with that component.

**Comment by hamishknight** [comment]
@xedin Thanks for the quick review! I'm happy to keep the same namings, my only concern was that if you gave `getCalleeLocator` a locator such as:

```swift
functionA(functionB())
          ^^^^^^^^^^^
             "leaf"
^^^^^^^^^^^^^^^^^^^^^^
        anchor
```

you might expect to receive a callee locator that describes `functionB` rather than `functionA` (and you might not realise that simplifying the locator will change how `getCalleeLocator` behaves). What do you think?

**Comment by xedin** [comment]
@hamishknight I think that's something we could document in the comment for `getCalleeLocator` but I'm not sure we can/want to do much about that, that's why diagnostics have `getAnchor()` and `getRawAnchor()`.

In my opinion solution for it would be for calls to propagate locators down to its arguments during constraint generation, so `visit*Expr` methods would not only get an expression pointer but also a `ConstraintLocatorBuilder` that way constraints/type variables associated with `functionB()` in your example would always get a locator rooted in the call.

**Comment by hamishknight** [comment]
@xedin Fair enough, I've gone ahead and reverted the naming changes as well as expanded on the doc comment for `getCalleeLocator`. Also given that `getChoiceFor(getLocator())` is no longer too onerous to write, I've removed the convenience member for that.

If that all looks good to you, I'll go ahead and smoke test + merge :)

**Comment by xedin** [comment]
@hamishknight Looks great, let's :shipit:

**Comment by hamishknight** [comment]
@swift-ci please smoke test and merge

**Comment by hamishknight** [comment]
@swift-ci please smoke test and merge

**Comment by hamishknight** [comment]
@swift-ci please smoke test Linux platform

**Comment by hamishknight** [comment]
@swift-ci please smoke test Linux platform

**Pull request merged**
