### PR TITLE
[Mem2Reg] Bail on address-only types.

### PR DESCRIPTION
**Pull request by nate-chandler**
It is impossible to have a value of address-only type, so don't try promoting.

rdar://131882748

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test linux platform

**Comment by nate-chandler** [comment]
@swift-ci please test linux platform

**Comment by nate-chandler** [comment]
@swift-ci Please Test Source Compatibility Release

**Review by atrick — APPROVED** [review]
Thanks! So that's how you do resilient types in a test case.

**Pull request merged**
