### PR TITLE
[NFC][test] Add additional test case for issue 57376

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
Adds additional test case to #57376

### CODE REVIEW

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test

**Review by AnthonyLatsis — COMMENTED** [review]
The test looks good, thanks. Is there a proposal for the `@rethrows` feature?

**Comment by LucianoPAlmeida** [comment]
> The test looks good, thanks. Is there a proposal for the `@rethrows` feature?

I'm not sure there is a numbered proposal for that, but pitch is here https://forums.swift.org/t/pitch-rethrowing-protocol-conformances/42373
And proposal is linked there as well https://github.com/DougGregor/swift-evolution/blob/rethrows-protocol-conformances/proposals/NNNN-rethrows-protocol-conformances.md

**Comment by AnthonyLatsis** [comment]
> I'm not sure there is a numbered proposal for that, but pitch is here

Yeah, I knew about the pitch too. What threw me off is the attribute is not underscored nor enabled with an experimental feature flag.

**Comment by LucianoPAlmeida** [comment]
> Yeah, I knew about the pitch too. What threw me off is the attribute is not underscored nor enabled with an experimental feature flag.

Ah yeah, I read some article that pointed to this https://twitter.com/slava_pestov/status/1480618687677743109 as reference 😆

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test

**Pull request merged**
