### PR TITLE
Don't set overrides on imported protocol requirements [5.0]

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes rdar://problem/42635132.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci clean test linux

**Comment by slavapestov** [comment]
@shahmishal It looks like we're still checking out the wrong lldb branch?

```
/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-swift-5.0-branch/lldb/source/Plugins/ExpressionParser/Swift/SwiftASTManipulator.cpp:598:34: error: no matching function for call to 'create'
02:53:26   result_loc_info.binding_decl = swift::PatternBindingDecl::create(
02:53:26                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
02:53:26 /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-swift-5.0-branch/swift/include/swift/AST/Decl.h:1946:30: note: candidate function not viable: requires 6 arguments, but 7 were provided
02:53:26   static PatternBindingDecl *create(ASTContext &Ctx, SourceLoc StaticLoc,
02:53:26                              ^
02:53:26 /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-swift-5.0-branch/swift/include/swift/AST/Decl.h:1952:30: note: candidate function not viable: requires 8 arguments, but 7 were provided
02:53:26   static PatternBindingDecl *create(ASTContext &Ctx, SourceLoc StaticLoc,
02:53:26                              ^
02:53:26 /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-swift-5.0-branch/lldb/source/Plugins/ExpressionParser/Swift/SwiftASTManipulator.cpp:1239:7: error: no matching function for call to 'create'
02:53:26       swift::PatternBindingDecl::create(
02:53:26       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
02:53:26 /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-swift-5.0-branch/swift/include/swift/AST/Decl.h:1946:30: note: candidate function not viable: requires 6 arguments, but 7 were provided
02:53:26   static PatternBindingDecl *create(ASTContext &Ctx, SourceLoc StaticLoc,
02:53:26                              ^
02:53:26 /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-swift-5.0-branch/swift/include/swift/AST/Decl.h:1952:30: note: candidate function not viable: requires 8 arguments, but 7 were provided
02:53:26   static PatternBindingDecl *create(ASTContext &Ctx, SourceLoc StaticLoc,
02:53:26                              ^
02:53:26 /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-swift-5.0-branch/lldb/source/Plugins/ExpressionParser/Swift/SwiftASTManipulator.cpp:1502:26: error: no member named 'getStorageKind' in 'swift::VarDecl'
02:53:26     if (variable.m_decl->getStorageKind() !=
02:53:26         ~~~~~~~~~~~~~~~  ^
02:53:26 /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-swift-5.0-branch/lldb/source/Plugins/ExpressionParser/Swift/SwiftASTManipulator.cpp:1503:37: error: no member named 'Computed' in 'swift::AbstractStorageDecl'
02:53:26         swift::AbstractStorageDecl::Computed)
02:53:26         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
```

Maybe @rjmccall needs to cherry-pick some patches on the lldb side?

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@fredriss Have you seen this before? 

```
/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.0-branch/lldb/source/Plugins/ExpressionParser/Swift/SwiftASTManipulator.cpp:598:34: error: no matching function for call to 'create'
  result_loc_info.binding_decl = swift::PatternBindingDecl::create(
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by fredriss** [comment]
@shahmishal never seen this

**Comment by fredriss** [comment]
There have been no modification involving PatternBindingDecl::create in LLDB since 2015...

**Comment by rjmccall** [comment]
No, see my comment above.  A patch to that code was committed on July 6th as  https://github.com/apple/swift-lldb/commit/906c4bf9d7262fdd307521732f824656820d3cd1, and it should be in swift-5.0-branch.

**Comment by fredriss** [comment]
Are you talking about 906c4bf9d7262fdd307521732f824656820d3cd1? because according to 'git branch --contains' it is on swift-5.0-branch. But this patch doesn't touch the line where the error is reported

**Comment by fredriss** [comment]
Doh, it touches exactly this piece of code, sorry. The commit is on swift-5.0-branch

**Comment by fredriss** [comment]
Sorry, I'm reacting to Mishal's message, but I should have read the history of the PR. John analysis is exactly correct, this build has checked out the swift-4.2-branch in LLDB.

**Comment by slavapestov** [comment]
@swift-ci Please test macOS

**Comment by shahmishal** [comment]
@swift-ci Please test macOS

**Pull request merged**
