### PR TITLE
Merge master into the TensorFlow branch

### PR DESCRIPTION
**Pull request by saeta**
Brings the tensorflow branch up to date with master.

### CODE REVIEW

**Comment by saeta** [comment]
Can confirm: all tests passing locally on linux. PTAL @dan-zheng ?

**Comment by dan-zheng** [comment]
I believe we can trigger CI on `tensorflow-merge -> tensorflow` PRs.
@swift-ci Please test tensorflow

**Review by dan-zheng — APPROVED** [review]
LGTM if tests pass!
I'll build a toolchain locally and verify that `swift test` on [tensorflow/swift-apis](https://github.com/tensorflow/swift-apis) also works.

**Comment by dan-zheng** [comment]
I built a toolchain and ran `swift test` on swift-apis.
Compilation succeeds when running `swift test`, but I ran into the known linker error on macOS:
```
2019-06-11 11:35:48.398 xctest[98347:18759624] The bundle “TensorFlowPackageTests.xctest” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2019-06-11 11:35:48.399 xctest[98347:18759624] (dlopen_preflight(/Users/danielzheng/swift-merge/tensorflow-swift-apis/.build/x86_64-apple-macosx/debug/TensorFlowPackageTests.xctest/Contents/MacOS/TensorFlowPackageTests): Library not loaded: /usr/lib/swift/libswiftPython.dylib
  Referenced from: /Users/danielzheng/swift-merge/tensorflow-swift-apis/.build/x86_64-apple-macosx/debug/TensorFlowPackageTests.xctest/Contents/MacOS/TensorFlowPackageTests
  Reason: image not found)
```

I think merging the PR now is reasonable.

**Pull request merged**
