### PR TITLE
Fixed typo. “swift” to “Swift”

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by nadavrot** [comment]
I don't know if this is a typo. The file extension is 'swift' not 'Swift'. 

I prefer not to merge this because this change can cause merge conflicts if someone else is working on this file and this change does not improve the readability of the code in a meaningful way.

**Comment by salutis** [comment]
I disagree. @RajkumarPunchh corrected grammar and improved readability. In _swift benchmarks_, "swift" is an adjective whereas in _Swift benchmarks_, "Swift" is a proper noun. Two different words, two very different meanings.

Also, "can cause merge conflicts" is not a good reason to reject important correction.

**Comment by RajkumarPunchh** [comment]
@nadavrot "I prefer not to merge this because this change can cause merge conflicts if someone else is working on this file", seriously? if this is one of the reasons of rejecting a pull request, how will you make sure that every Swift contributor is working on a  distinct file.

**Comment by salutis** [comment]
@nadavrot +1

**Pull request closed without merging**
