### PR TITLE
[6.0][lld] Allow opt-out from building lld via --skip-build-lld

### PR DESCRIPTION
**Pull request by al45tair**
Cherry pick of #73539.

rdar://129053233

### CODE REVIEW

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
**Explanation**: Apparently in addition to #70715 (cherry picked as #73970), we need #73539 to avoid a problem created by the former.
**Original PR**: #73539
**Risk**: Low. Already on main.
**Reviewed by**: @bnbarham @krispymb @edymtt 
**Resolves**: rdar://129053233
**Tests**: The Python build script tests were updated by this PR.

**Comment by al45tair** [comment]
macOS PR testing failed because of:

```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'llvm/test/CodeGen/X86/apx/asm-constraint-jR.ll'
  'llvm/test/CodeGen/X86/apx/asm-constraint-jr.ll'
```

caused by https://github.com/llvm/llvm-project/pull/92338, and apparently fixed in https://github.com/llvm/llvm-project/pull/93794.

**Review by edymtt — APPROVED** [review]

**Comment by al45tair** [comment]
@swift-ci Please test macOS platform

**Review by shahmishal — APPROVED** [review]

**Pull request merged**
