### PR TITLE
[6.0][region-isolation] Add support for missing cases of nonisolated(unsafe).

### PR DESCRIPTION
**Pull request by gottesmm**
Explanation: This commit adds missing support for nonisolated(unsafe) to release/6.0. Without this, many cases of nonisolated(unsafe) will not work.

Radars:

- rdar://128299305

Original PRs:

- https://github.com/apple/swift/pull/73930

Risk: Low. Just affects region isolation.
Testing: Added tests to the test suite.
Reviewer: N/A

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Review by hborla — APPROVED** [review]

**Comment by gottesmm** [comment]
Original PR: #73930

**Comment by gottesmm** [comment]
Windows failed in unrelated code:   Swift(windows-x86_64) :: ModuleInterface/swift_build_sdk_interfaces/find-modules.test-sh

Testing again

**Comment by gottesmm** [comment]
@swift-ci test windows platform

**Pull request merged**
