### PR TITLE
stdlib/Concurrency/PartialAsyncTask.swift: Correct typos

### PR DESCRIPTION
**Pull request by Achoo-kr**
I fixed some typos in Concurrency/PartialAsyncTask.swift.
Please check out the changes.

### CODE REVIEW

**Comment by Achoo-kr** [comment]
cc. @ktoso @kavon 

Forgot to tag you guys. Thanks in advance :)

**Review by ktoso — APPROVED** [review]

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
Thanks :)

**Comment by AnthonyLatsis** [comment]
@Achoo-kr Please read our [contributing guidelines](https://github.com/apple/swift/blob/e8d43434db9bb86e1a38f9b315604c3b8f2d047f/CONTRIBUTING.md) before submitting changes, regardless of how simple they are. If you have time before this gets auto-merged, please consider amending your commit message to start with a capital letter and include the file name that contains the typo fixes.

**Comment by Achoo-kr** [comment]
@AnthonyLatsis

I didn't know that. Thanks for noticing!

**Pull request merged**
