### PR TITLE
[CodeCompletion] Map the result type for keypath member lookup

### PR DESCRIPTION
**Pull request by rintaro**
```swift
struct Circle {
  var center: Point { get }
  var radius: Length { get }
}

@dynamicMemberLookup
struct Wrapper<T> {
  subscript<U>(dynamicMember: KeyPath<T, U>) -> Wrapped<U> { get }
}

func test(value: Wrapper<Circle>) {
  value.#HERE#
}
```
The type of `center` and `radius` should be `Wrapped<Point>` and `Wrapped<Length>` respectively.

rdar://problem/50073837

NOTE: This implementation doesn't properly handle:
- Nested wrapper
  (e.g. `Wrapper<Wrapper<Point>>`)
- Generic result type in `KeyPath`
  (e.g. `subscript<U>(dynamicMember: KeyPath<T, Box<U>>) -> Wrapper<U>`)

### CODE REVIEW

**Comment by rintaro** [comment]
@xedin, @DougGregor Could you check I'm doing right thing?

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Review by xedin — APPROVED** [review]
Seems reasonable to me, thanks Rintaro!

**Review by benlangmuir — APPROVED** [review]

**Pull request merged**
