### PR TITLE
[Onone][prespecialize] Added iteration through reversed() arrays.

### PR DESCRIPTION
**Pull request by djwbrown**
In response to [SR-3334], which pointed out a large cost to iteration over
ReversedRandomAccessCollections at optimization level -Onone. By adding
iteration through a.reversed() in the _Prespecialize struct, we can get to
about the same performance as forward iteration.

Resolves [SR-3334](https://bugs.swift.org/browse/SR-3334).
@swift-ci **First major contribution**, please test, peer review and feedback if necessary.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swiftix Can you take a look?

**Comment by swiftix** [comment]
@swift-ci Please benchmark

**Comment by swiftix** [comment]
@swift-ci Please smoke test

**Comment by airspeedswift** [comment]
Do we have benchmarks that test the performance of reversed collections? We should add as part of this change if not.

**Comment by djwbrown** [comment]
Is there any need to make the benchmark generic beyond just testing Int?

**Comment by swiftix** [comment]
@djwbrown It could be interesting to provide the benchmark in a separate PR, so that we could first  benchmark it without the current PR and then with your PR to see the improvements due to pre-specializations.

**Comment by airspeedswift** [comment]
@djwbrown Would be good to test a bidirectional collection, since that is a different wrapper view. Also the hope is these will collapse down to one type with conditional conformance so it'd be great to have some benchmarks ready for when that change is made. Except I don't think there are any good examples of concrete bidirectional collections in the std lib right now, so perhaps use `AnyBidirectionalCollection(0..<100_000)`

Forward-only collections are handled differently since you can't wrap it in low-cost view, so instead it generates a new array and returns that. But for completeness we should add it at the same time (could use `Dictionary`). Also a sequence (e.g. `sequence(first: 0) { $0 < 100_000 ? $0+1 : nil }`)

**Comment by djwbrown** [comment]
@swiftix I've opened a second PR #6512 as you suggested.

**Comment by swiftix** [comment]
@djwbrown Now that #6512 is merged, you should probably remove it from this PR?

**Comment by djwbrown** [comment]
Didn't know I could use git force push, and by deleting the branch accidentally closed this PR. Sorry! See #6582 for optimization without benchmarks (just the first commit here).

**Pull request closed without merging**
