### PR TITLE
[sema] Fix error message for enums with an invalid raw type

### PR DESCRIPTION
**Pull request by adamshin**
Resolves https://bugs.swift.org/browse/SR-9019

### CODE REVIEW

**Comment by adamshin** [comment]
@swift-ci Please smoke test

**Comment by CodaFi** [comment]
Hi @adamshin, thanks for the patch.

You should run the tests and make sure to update them with respect to the changes you’ve made to the diagnostic text.

Also note that CI requires privileges for security purposes.

**Comment by adamshin** [comment]
Ah, thanks for the info. This is my first time contributing so I'm still learning the ropes. 🙂

I didn't see any tests that seemed to be affected by this change. Would I need to add a new one?

**Comment by CodaFi** [comment]
No problem.  I wrote [a short explainer](https://forums.swift.org/t/need-a-workflow-advice/12536/14?u=codafi) of some Swift-specific testing concepts that help here

A quick `git grep` reveals you should update the following files

```
test/Generics/inheritance.swift
test/IDE/print_ast_tc_decls_errors.swift
test/Parse/enum.swift
test/Sema/accessibility_private.swift
test/Sema/enum_raw_representable.swift
```

**Comment by brentdax** [comment]
@swift-ci please smoke test

**Pull request merged**
