### PR TITLE
Importer: remove `ImportAsMember` inference support

### PR DESCRIPTION
**Pull request by compnerd**
This functionality is not actively in use and the last usage of this has
been removed.  Remove the infrastructure that is no longer in need.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @gribozavr @hlopko @scentini

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by CodaFi** [comment]
Unfortunately we cannot take this as is. I will reopen Dmitri’s PR when we can.

**Comment by compnerd** [comment]
Converting to draft to prevent accidental merge

**Comment by compnerd** [comment]
@CodaFi - I don't think that opening @gribozavr's PR would be as helpful, the tree has diverged, so this change is likely more useful at this point.  Would you mind just converting this change to an open PR from draft when we can actually merge this change?

**Comment by CodaFi** [comment]
@compnerd Please rebase this, and let's get it merged. I want to commend you on your patience here - I know this was blocking good work you were doing elsewhere and I'm sorry it took so long to get the stars to align to make this happen.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
