### PR TITLE
[stdlib] String: Walk Chinese/Japanese faster: 2x/4x forwards/backwards

### PR DESCRIPTION
**Pull request by milseman**
This adds more fast path checks for grapheme breaks between BMP
scalars. Notably the rather vast range of 0x3400–0xA4CF which includes
unified common Han ideographs as well as the first extension to
unified Han ideographs. It also happens to pick up various Yijin and
Yi symbols/radicals. Additionally, the narrow hiragana/katakana ranges
0x3041-0x3096 and 0x30A1-0x30FA (including pre-composed semi-voiced
characters but excluding the combining semi-voice marks) have fast
paths.
    
The net effect is that the vast majority of modern Chinese and
Japanese text should be fast-pathed. This is especially important, as
adopting Unicode 9 might otherwise pessimize performance here relative
to the tries.

Gyb up StringWalk benchmark, to avoid the code explosion. Add in benchmarks for
walking Chinese, Japanese, and Korean text.

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please benchmark

**Comment by nkcsgexi** [comment]
谢谢你！

**Comment by airspeedswift** [comment]
I'm guessing the speedup in StringWalk was due to benchmark refactoring rather than that making Chinese faster happened to give ASCII a 5x speedup...

**Comment by airspeedswift** [comment]
(I'm pretty sure the other benchmarks are noise, especially StringHasPrefix which seems to have gotten constant-folded recently so needs refactoring...)

**Comment by milseman** [comment]
@swift-ci please smoke benchmark

**Pull request merged**
