### PR TITLE
[CSSolver] Prune disjunction choices based on their equivalence class

### PR DESCRIPTION
**Pull request by xedin**
There are situations where we know equivalence relationship between
multiple disjunctions, let's prune dependent choice space based on
choice picked for the parent disjunction.

Resolves: rdar://problem/35540159

### CODE REVIEW

**Comment by xedin** [comment]
This used to be _incorrectly_ done by `LinkedExprAnalyzer` via using bind constraints between type variables which sometimes leads to incorrect results. This, I think, is much better approach which makes sequences of operators with know types effectively constant to solve.

**Comment by xedin** [comment]
@swift-ci please smoke test compiler performance

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Review by DougGregor — APPROVED** [review]
LGTM

**Comment by xedin** [comment]
Just a note that this is not perfect and I think we have a common understanding that `LinkedExprAnalyzer` has to go away in favor of logic in the solver which does similar thing but based on each individual choice.

**Pull request merged**
