### PR TITLE
Remove -enable-protocol-typealiases staging flag

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by gregomni** [comment]
Awesome! Thanks for all your work on this!

**Comment by slavapestov** [comment]
You did most of it, so thank *you*!

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test and merge

**Pull request merged**
