### PR TITLE
Force foundation and libdispatch to re-build always on non-darwin platforms. (#12736)

### PR DESCRIPTION
**Pull request by Rostepher**
(cherry picked from commit bef1e6d0f1627c8720426e579f8752b5ca264a2a)

### CODE REVIEW

**Comment by Rostepher** [comment]
@swift-ci please smoke test

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by Rostepher** [comment]
@swift-ci please smoke test

**Comment by shahmishal** [comment]
```
Test Case 'TestNSNumberBridging.testNSNumberBridgeFromInt32' started at 2017-11-09 08:57:49.497
TestFoundation/TestNSNumberBridging.swift:252: error: TestNSNumberBridging.testNSNumberBridgeFromInt32 : XCTAssertNil failed: "-2.14748e+09" - 
TestFoundation/TestNSNumberBridging.swift:252: error: TestNSNumberBridging.testNSNumberBridgeFromInt32 : XCTAssertNil failed: "-2.14748e+09" - 
TestFoundation/TestNSNumberBridging.swift:252: error: TestNSNumberBridging.testNSNumberBridgeFromInt32 : XCTAssertNil failed: "2.14748e+09" - 
TestFoundation/TestNSNumberBridging.swift:252: error: TestNSNumberBridging.testNSNumberBridgeFromInt32 : XCTAssertNil failed: "2.14748e+09" - 
TestFoundation/TestNSNumberBridging.swift:252: error: TestNSNumberBridging.testNSNumberBridgeFromInt32 : XCTAssertNil failed: "2.14748e+09" - 
TestFoundation/TestNSNumberBridging.swift:252: error: TestNSNumberBridging.testNSNumberBridgeFromInt32 : XCTAssertNil failed: "2.14748e+09" - 
Test Case 'TestNSNumberBridging.testNSNumberBridgeFromInt32' failed (0.001 seconds)

```

**Comment by xedin** [comment]
I have a radar about this assigned to @natecook1000

**Comment by natecook1000** [comment]
That fix is here: https://github.com/apple/swift-corelibs-foundation/pull/1302#issuecomment-343196443 - working on merging it.

**Comment by natecook1000** [comment]
@swift-ci Please test Linux platform

**Comment by Rostepher** [comment]
Thanks @natecook1000! Going to merge this now.

**Pull request merged**
