### PR TITLE
Use toolchain clang on macOS

### PR DESCRIPTION
**Pull request by etcwilde**
Don't use the just-built clang on macOS. macOS does this more "right" than the Linux build. Linux will sometimes use the just-built Swift-driver with the just-built clang, but sometimes would use the system clang instead. macOS uses the toolchain Swift-driver with the toolchain clang. This is correct, but it means that if we force the other clang, we'll get mismatched sanitizer runtimes so the ASAN bot will fail.

rdar://128602427

### CODE REVIEW

**Comment by etcwilde** [comment]
@swift-ci please test

**Comment by etcwilde** [comment]
preset=asan
@swift-ci please test with preset macOS platform

**Review by hamishknight — APPROVED** [review]
Thanks!

**Comment by etcwilde** [comment]
preset=asan
@swift-ci please test with preset macOS platform

**Comment by etcwilde** [comment]
preset=asan
@swift-ci please test with preset Linux platform

**Comment by etcwilde** [comment]
@swift-ci please test

**Comment by etcwilde** [comment]
preset=asan
@swift-ci please test with preset macOS platform

**Comment by etcwilde** [comment]
preset=asan
@swift-ci please test with preset Linux platform

**Comment by etcwilde** [comment]
Ooohhh kay, so it appears that the combination of toolchain tools and just-built tools changes when building with ASAN vs not on Linux. 😭

Building normally
macOS: consistently uses the swiftc from the toolchain, so clang invocations and clang-linker invocations use the same
Linux: uses just-built swiftc which falls back on the toolchain clang for a bit, and then uses the just-built clang

Building with ASAN
both seem to use the swiftc from the toolchain instead of mixing just-built vs not.

**Comment by etcwilde** [comment]
preset=asan
@swift-ci please test with preset macOS platform

**Comment by etcwilde** [comment]
preset=asan
@swift-ci please test with preset Linux platform

**Comment by etcwilde** [comment]
I'm a bit confused about how the Linux ASAN ever worked. `libswiftCore.so` and `unittests/Threading/SwiftThreadingTests` are being built with different `clang`s, which means it's going to pick up different compiler resource directories and have mismatched sanitizers. I think let's get macOS working for now so that we have ASAN working somewhere, and then can look into Linux with the upcoming build fix work.

swiftcore is built with `/home/build-user/build/buildbot_incremental_asan/llvm-linux-x86_64/./bin/clang++`, while the threading unittests are built with `/opt/swift/5.8.1/usr/bin/clang++`.

**Comment by etcwilde** [comment]
@swift-ci please test

**Pull request merged**
