### PR TITLE
Do not inherit search paths from loaded binary Swift module dependencies in Swift 6

### PR DESCRIPTION
**Pull request by artemcm**

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci smoke test

**Comment by xymus** [comment]
I believe there are two tests that should be testing this behavior, would you mind upping them to expect the failure in Swift 6 mode just so we don't bring it back accidentally? `test/Serialization/search-paths-sdk.swift and test/Serialization/search-paths-relative.swift`.

**Review by xymus — APPROVED** [review]
Thank you!

**Comment by artemcm** [comment]
> I believe there are two tests that should be testing this behavior, would you mind updating them to expect the failure in Swift 6 mode just so we don't bring it back accidentally? `test/Serialization/search-paths-sdk.swift and test/Serialization/search-paths-relative.swift`.

Great call, thanks. Done!

**Comment by artemcm** [comment]
@swift-ci smoke test and merge

**Pull request merged**
