### PR TITLE
CMake: Pass -DRESILIENT_LIBRARIES when building _StringProcessing

### PR DESCRIPTION
**Pull request by tshortli**
See https://github.com/apple/swift-experimental-string-processing/pull/731.

### CODE REVIEW

**Comment by tshortli** [comment]
@swift-ci please smoke test

**Comment by tshortli** [comment]
https://github.com/apple/swift/pull/72333

@swift-ci please smoke test

**Comment by tshortli** [comment]
https://github.com/apple/swift-experimental-string-processing/pull/731

@swift-ci please smoke test

**Review by Azoy — APPROVED** [review]

**Comment by tshortli** [comment]
@swift-ci please smoke test Windows

**Comment by tshortli** [comment]
https://github.com/apple/swift-experimental-string-processing/pull/731

@swift-ci please smoke test Windows

**Comment by tshortli** [comment]
https://github.com/apple/swift-experimental-string-processing/pull/731

@swift-ci please smoke test Windows

**Pull request merged**
