### PR TITLE
Fix crash in `DependentGenericTypeResolver::resolveDependentMemberType`

### PR DESCRIPTION
**Pull request by jtbandes**
An erroneous `baseTy` would cause resolveArchetype to return nullptr, resulting in a null dereference.

<s>Apologies — the test suite is prohibitively large for me to run it fully before submitting this patch. The file `00626-swift-lexer-lexidentifier.swift` no longer crashes the compiler, so I've moved it to compiler_crashes_fixed. Before merging, though, someone will need to convince themselves that everything else still works.</s>

### CODE REVIEW

**Comment by jtbandes** [comment]
Note: the same sort of `resolveArchetype` call is made a few lines down, in `DependentGenericTypeResolver::resolveSelfAssociatedType()`. However, I couldn't find a case that would trigger the same crash, so I didn't modify that function. Based on git-blame, it looks like @DougGregor might be able to confirm this, or help find a crashing case.

**Comment by gribozavr** [comment]
> Apologies — the test suite is prohibitively large for me to run it fully before submitting this patch.

What configuration (hardware and bulid) are you using?  The full test suite runs within less than 10 minutes when the compiler is built in release mode, try `utils/build-script -RT`.

**Comment by jtbandes** [comment]
Just kidding — this fixed 335 of the crashing tests :smiley:

**Comment by jckarter** [comment]
Nice!

**Comment by lattner** [comment]
Wow, fantastic!  @DougGregor, please review this when you have a chance, thanks!

**Comment by jtbandes** [comment]
Updated with new fixed issues.

**Comment by DougGregor** [comment]
Please squash this into a single commit; we like to have the test suite in sync with the code.

**Comment by AlexDenisov** [comment]
Hm, why all the fixed crashers removed? Shouldn't they go into `fixed_crashers`?

**Comment by jtbandes** [comment]
@DougGregor: done.
@AlexDenisov: I think GitHub is just struggling to show the diff. The files were moved, but it decided they were deleted+added instead of just renamed. :shrug:

**Comment by yas375** [comment]
@jtbandes it looks like the moved files were not commited.

**Comment by jtbandes** [comment]
@yas375: They actually were. GitHub shows it incorrectly. If you pull jtbandes/swift@d781605a6d, you can see them locally.

**Comment by yas375** [comment]
@jtbandes you are right! I apologize.

I bet we can help `git` to understand that those are actually just file moves by using `git mv`. And the most important outcome from using `git mv` is that reviewer will be sure that those are file moves and there are no hidden changes in there.

I went ahead and did it locally and here is a list of steps to follow:

```
git reset --soft HEAD~1
git checkout validation-test/compiler_crashers/
git clean -fd
git status # you should see only `modified:   lib/Sema/TypeCheckGeneric.cpp`
```

I've created [a list](https://gist.github.com/yas375/ca9667526056c92afd05) of commands using string replacement on the output of the removed files to use `git mv`:

```
bash <(curl -s https://gist.githubusercontent.com/yas375/ca9667526056c92afd05/raw/d11107bc807ba9e718ad3031334ade9e588b4116/gistfile1.txt)
```

Now `git status` should report all file moves in the right way:

```
➜  swift git:(072a459) ✗ git st
HEAD detached from d781605
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

  renamed:    validation-test/compiler_crashers/00066-diagnoseunknowntype.swift -> validation-test/compiler_crashers_fixed/00066-diagnoseunknowntype.swift
  renamed:    validation-test/compiler_crashers/00626-swift-lexer-lexidentifier.swift -> validation-test/compiler_crashers_fixed/00626-swift-lexer-lexidentifier.swift
  renamed:    validation-test/compiler_crashers/01908-std-function-func-mapsignaturetype.swift -> validation-test/compiler_crashers_fixed/01908-std-function-func-mapsignaturetype.swift
  ...
  renamed:    validation-test/compiler_crashers/28179-void.swift -> validation-test/compiler_crashers_fixed/28179-void.swift

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

  modified:   lib/Sema/TypeCheckGeneric.cpp

```

Please rerun the tests to make sure I didn't break anything :)

---

I've also reported the issue with wrong statistics to GitHub support.

**Comment by yas375** [comment]
@jtbandes here is how changes will be shown on GitHub: http://screencast.com/t/NO5nEJDw

Thanks for your contribution! :+1:

**Comment by jtbandes** [comment]
Thanks @yas375! I wasn't aware that `git mv` did anything different from mv + git add. I'll update the diff.

**Comment by jtbandes** [comment]
Actually, that didn't help. (jtbandes/swift@3cbabd06b1b5328d855d1073fd7dc494bc353ca1). I think `git mv` is basically the same as mv + git add.

The problem is that in all of the moved files, I also changed one line, to remove the `--crash` flag.

I think this is as good as it will get. It's only a GitHub problem, not a git problem :)

**Comment by yas375** [comment]
@jtbandes this is weird. `git mv` should produce the right result. It works for me. See my [temporary pull request](https://github.com/yas375/swift/pull/1/files) and [commit itself](https://github.com/yas375/swift/commit/35ea2430e24256e309d3983fb0df86b7b72b1d85) where I used `git mv`. On both pages the changes displayed properly.

I don't think it matters, but just in case:
> ➜  git --version
> git version 2.6.2

**Comment by jtbandes** [comment]
@yas375 I'm using 2.6.3.

On your PR I see "File renamed without changes" for each of the test files. That seems wrong to me. The files are supposed to be modified as well as renamed.

**Comment by yas375** [comment]
@jtbandes oh, I'm sorry then. I thought those were just moves. Sorry for the confusion and taking you time.

Great job! :+1:

**Comment by jtbandes** [comment]
No worries, thanks for trying! It would have been nice if it worked :)

**Comment by jtbandes** [comment]
@DougGregor please let me know if there's anything else to be done here!

**Comment by jtbandes** [comment]
@DougGregor @gribozavr I've updated this PR to avoid conflicts from #398 and #405

**Pull request merged**
