### PR TITLE
[AutoDiff] Fix crasher on property getter in library evolution mode.

### PR DESCRIPTION
**Pull request by rxwei**
`SILBuilder::createAllocStack` expects a debug variable when the location is a `VarDecl`. Since we are in pullbacks, there's no debug variables so we pass an empty one.

General support for debug-info-in-pullbacks will be added as part of SR-13535.

Also add a negative test for SR-13866.

Resolves SR-13865.

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test

**Review by joshnewnham — APPROVED** [review]

**Comment by rxwei** [comment]
@swift-ci please test and merge

**Comment by rxwei** [comment]
@swift-ci please test macos platform and merge

**Comment by rxwei** [comment]
@swift-ci please test macos platform

**Pull request merged**
