### PR TITLE
define TensorPair, and reinstate Dataset zip

### PR DESCRIPTION
**Pull request by marcrasi**
Defines TensorPair, a 2-tuple-like struct that conforms to TensorGroup, so that users can use 2-tuples with APIs that require TensorGroups. TensorPair makes it possible to reinstate Dataset "zip".

There are two internal implementation details preventing the reinstated zip from working in graph mode, so I filed https://bugs.swift.org/browse/SR-9156 describing the problems. I'd like to get the API discussed and landed in this PR, and then asynchronously go fix those details later.

### CODE REVIEW

**Review by rxwei — APPROVED** [review]

**Comment by marcrasi** [comment]
Fixed some conflicts and addressed comments.

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Pull request merged**
