### PR TITLE
CastOptimizer: A load store to the existential box is not valid on ad…

### PR DESCRIPTION
**Pull request by aschwaighofer**
…dress only types

rdar://40949457

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test and merge

**Comment by aschwaighofer** [comment]
@swift-ci Please test and merge

**Comment by aschwaighofer** [comment]
@swift-ci Please test and merge

**Comment by atrick** [comment]
@aschwaighofer I don't see anything in the code that communicates this invariant. For example, I at least want to see a comment in the unit test explaining why a copy_addr needs to be emitted. Maybe a comment in the code explaining the same. Can SILVerifier catch this?

**Comment by aschwaighofer** [comment]
@atrick The invariant is that you can't load address-only types. That is a pretty fundamental property in SIL. At least for now.

This is not enforced by the SIL verifier apparently (because I think this was tripping up in IRGen in a non-assert build). It will trip an assert in an asserts build. I forgot whether it was the SILBuilder or the the LoadInst constructor.

**Pull request merged**
