### PR TITLE
[ConsumeAddrChecker] Diagnose consumes of borrows.

### PR DESCRIPTION
**Pull request by nate-chandler**
When checking a `mark_unresolved_move_addr` instruction, first check whether it is legal to consume the source.

rdar://127518559&125817827

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Review by atrick — APPROVED** [review]
LGTM

**Comment by nate-chandler** [comment]
```
UPasses:
  UPASS: rdar://128175704, penny-bot, 5.10, b30d76, Swift Package
```

**Pull request merged**
