### PR TITLE
[se-0405] Implement API additions

### PR DESCRIPTION
**Pull request by glessard**
API additions (and tests) from [SE-0405](https://github.com/apple/swift-evolution/blob/main/proposals/0405-string-validating-initializers.md), namely:
```
String.init?<Encoding>(
    validating codeUnits: some Sequence<Encoding.CodeUnit>,
    as encoding: Encoding.Type
  ) where Encoding: Unicode.Encoding

String.init?<Encoding>(
    validating codeUnits: some Sequence<Int8>,
    as encoding: Encoding.Type
  ) where Encoding: Unicode.Encoding, Encoding.CodeUnit == UInt8
```
The API renaming will come in a separate PR.

rdar://114999766

### CODE REVIEW

**Comment by glessard** [comment]
@swift-ci please test

**Comment by glessard** [comment]
GitHub is failing to pick up a push to this branch. Weird.

**Comment by glessard** [comment]
Re-opened as https://github.com/apple/swift/pull/68419

**Comment by simanerush** [comment]
@glessard  I had this problem yesterday and I solved it but pushing an empty commit and then deleting it

**Pull request closed without merging**
