### PR TITLE
Fix reflection_Optional_Any to support non-Apple platforms

### PR DESCRIPTION
**Pull request by tbkka**
Apple and non-Apple platforms happen to use different number
of extra inhabitants in 64-bit pointers.  This is already
supported by the test framework, we just need to fill it in
properly for this one test.

### CODE REVIEW

**Comment by tbkka** [comment]
@swift-ci Please test

**Comment by tbkka** [comment]
Related to #35513 and #35433

**Review by kastiglione — APPROVED** [review]

**Comment by kastiglione** [comment]
Also remove the:`REQUIRES: OS=macosx…` line

**Comment by tbkka** [comment]
@swift-ci Please test

**Pull request merged**
