### PR TITLE
[Typechecker] Disallow passing expression pattern inout to the match function

### PR DESCRIPTION
**Pull request by theblixguy**
The following code is legal:

```swift
func ~= (pattern: inout Int, value: Int) -> Bool {
  pattern = value
  return true
}

var x = 0

switch 49 {
case x:
  print("yup")
default:
  print("nope")
}

print(x) // 49
```

Disallow passing the expression pattern inout to the pattern matching function (`~=`). This is a source-breaking change, but is deemed acceptable by Joe Groff.

Resolves [SR-11488](https://bugs.swift.org/browse/SR-11488).

### CODE REVIEW

**Comment by theblixguy** [comment]
Should we add a diagnostic instead of simply discarding the choice?

**Comment by jrose-apple** [comment]
Honestly if we can figure out how to make the value being matched an rvalue instead of an lvalue we'd pretty much get this behavior for free, including a diagnostic. @xedin, is there an easy way to do that?

**Comment by theblixguy** [comment]
We don't call the above operator func if `x` is a let variable. This is the main reason why I didn't add a diagnostic.

**Comment by jrose-apple** [comment]
If it's the _only_ match operator for a type, though, it would still show up.

**Comment by theblixguy** [comment]
Hmm yeah, since the expr pattern has to be `Equatable` in order for `~=` to be called, we'll always have _at least_ one match operator func (i.e. `Swift.~=`). In the above case, we're choosing that over the one we've provided since `x` is immutable, so I thought I'd make sense to do that for mutable one as well (to keep the behaviour consistent).

**Comment by theblixguy** [comment]
Nevermind, it seems like if the expr pattern isn't `Equatable` we do use the custom one.

**Comment by jrose-apple** [comment]
I don't think the expr pattern has to be Equatable. Where do we check that?

**Comment by theblixguy** [comment]
```swift
class A {
  let id = UUID().uuidString
}

var x = A()
var y = A()

switch y {
case x: // argument type 'A' does not conform to expected type 'Equatable'
  print("yup")
default:
  print("nope")
}
```

**Comment by jrose-apple** [comment]
That's coming out of the constraint system trying to use the only generic `~=` it can find. If you define the inout one you'll get a different error.

**Comment by jrose-apple** [comment]
(None of these diagnostics are great.)

**Comment by theblixguy** [comment]
If I define:

```
func ~= (pattern: inout A, value: A) -> Bool {
  pattern = value
  return true
}
```

it compiles and prints "yup". Although when `x` is immutable, I get: `left side of mutating operator isn't mutable: 'x' is a 'let' constant`

**Comment by jrose-apple** [comment]
That's what I was getting at this whole time, although I guess it's a pretty lousy diagnostic. Still, it doesn't seem like we need to do *better* than what we do for `let`.

**Comment by xedin** [comment]
We have a couple of options here but the question I have is whether it should be valid to declare `~=` with inout parameters at all? I guess we could diagnose and strip `inout` away if that's not something which should be supported...

**Comment by theblixguy** [comment]
Diagnosing the declaration seems nice and it means the mistake can be caught earlier (rather than diagnosing when we attempt to `switch`).

**Comment by Azoy** [comment]
I understand that `~=` is a special operator, but I don't think it should be illegal to write this operator with inout. I do think that any version which uses inout parameters shouldn't be considered when type checking an expression pattern which is why I'm kind of in favor of the proposed implementation. (Although I would check all parameters rather than just the first one).

**Comment by theblixguy** [comment]
I suppose we can check both parameters but if the `value` parameter is `inout` or if both params are `inout`, then we don't get this behaviour, so maybe we only need to check the `pattern` parameter?

**Comment by xedin** [comment]
I think the best option might be to bring this up on the forum and probably update the accepted proposal afterwards.

**Comment by theblixguy** [comment]
Yeah, I’ll create a discussion thread on swift evolution shortly.

**Comment by xedin** [comment]
@theblixguy Thank you! Please CC me as well, I'm out for a week but I'll follow along when I have a minute.

**Comment by theblixguy** [comment]
Created a thread here: https://forums.swift.org/t/disallow-passing-expression-pattern-inout-to-the-match-function/29446

**Comment by jrose-apple** [comment]
So…what's up with this PR? Doug struck out the "`~=` should not have inout because it's only used for switch" interpretation, but that still leaves "filter out the inout cases" vs. "leave in the inout cases and let them error". (And I still prefer the latter.)

**Comment by xedin** [comment]
Looks like that forum post didn't get any traction, I think it would be great to document the behavior (I prefer the "leave and error" approach) in the proposal before we go ahead and implement it.

**Comment by theblixguy** [comment]
Does this need an evolution proposal to change the behavior? Thought it was considered a bug which didn't need one.

**Comment by jrose-apple** [comment]
Yeah, Joe said so on the original SR.

**Comment by xedin** [comment]
I have talked to @DougGregor about this today, and he is going to bring it up to the Core Team to discuss.  It might be possible to do this through amendment to existing proposal.

**Comment by theblixguy** [comment]
> through amendment to existing proposal

Which proposal?

**Comment by xedin** [comment]
Hm, I thought that there was one for that but I guess there is none, so it would have to a proposal.

**Comment by DougGregor** [comment]
The Core Team discussed this today. Our preference is to maintain the current type checking behavior, but error when this implicit `inout` conversion happens to the pattern during pattern matching. That would let us stage out the behavioral change over more than one release: diagnose the code that would break or change behavior "now", then in a future release we can disable the implicit `inout` conversion in the type checker. So the first example mentioned in the PR summary would be ill-formed "now", and fall back to the `Equatable` some time in the future.

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by CodaFi** [comment]
@theblixguy Are you still pursuing this?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
