### PR TITLE
PerformanceInliner:  protect against misuse of @inline(__always)

### PR DESCRIPTION
**Pull request by eeckstein**
Inline-always should only be used on relatively small functions. It must not be used on recursive functions.
Add a check that prevents that inlining of large @inline(__always) functions.

Also, add a command line option for better debugging large pass runtimes.

https://github.com/apple/swift/issues/64319
rdar://106655649

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Comment by karwa** [comment]
Is it possible for this to emit a diagnostic when `@inline(__always) ` gets ignored?

**Comment by troughton** [comment]
This could potentially break one thing I've been using `@inline(__always)` for, which is to force constant folding of a function based on particular arguments. https://github.com/troughton/Substrate/blob/9eabdd212ae29b537609e846560c1f8123ce52cf/Sources/SubstrateImage/GaussianBlur.swift#L43 is an example of this – I want the body of `_convolve` to be copied into each of its callers, the `pixelWeight` and `axis` arguments to be constant folded, then `_convolve` to be deleted.

**Comment by eeckstein** [comment]
> Is it possible for this to emit a diagnostic when @inline(__always)  gets ignored?

It's complicated. Inlining decisions are made in the optimizer pipeline based on heuristics. Such a diagnostic would be very brittle. For example, you wouldn't see it when building in debug configuration. Unrelated code changes could let the diagnostic appear/disappear.

`@inline(__always)` is not a as strict as its name suggest. At the end it's only a hint for the optimizer which might be followed or (in some rare cases) ignored.

**Comment by eeckstein** [comment]
> I want the body of _convolve to be copied into each of its callers, the pixelWeight and axis arguments to be constant folded, then _convolve to be deleted. Is there a way to support this use case while still disallowing recursive functions?

Is this for performance reasons? If yes, are you sure that the `@inline(__always)` makes a significant difference in performance?

It has a good reason that this attribute is underscored. The original intention of `@inline(__always)` was to annotate performance critical basic operations in the standard library.

There are only very few cases in "regular" programs (outside the stdlib) where `@inline(__always)` makes sense. Forcing inlining of a function doesn't necessarily improve performance and it's hard to predict the performance implications of `@inline(__always)` without considering the interaction with the inliner's default heuristic and other optimizations.

**Comment by eeckstein** [comment]
The optimizer does specialize functions for certain kind of constants, including closures. But it's not configurable

**Pull request merged**
