### PR TITLE
[ownership] Rename the cases of UseLifetimeConstraint to use clearer language

### PR DESCRIPTION
**Pull request by gottesmm**
Specifically,

* MustBeLive -> NonLifetimeEnding
* MustBeInvalidated -> LifetimeEnding

----

The main thing here is we are trying to avoid language associated with owned values and use more values that are sort of generic/algebraic.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Review by atrick — APPROVED** [review]
I think this is a really helpful clarification, especially for people looking at the code for the first time. Thanks!

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Pull request merged**
