### PR TITLE
build: add imported library for libedit

### PR DESCRIPTION
**Pull request by compnerd**
This allows us to use CMake more effectively rather than proliferating
the linking and header search path logic.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @edymtt @Rostepher @xiaobai @JDevlieghere

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@JDevlieghere I'm thinking of making this change here first, and then pushing this change to LLVM once this has been merged.

**Comment by JDevlieghere** [comment]
> @JDevlieghere I'm thinking of making this change here first, and then pushing this change to LLVM once this has been merged.

Sounds good!

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Pull request merged**
