### PR TITLE
[Demangler] Fix OldRemangler's handling of Subscript nodes.

### PR DESCRIPTION
**Pull request by al45tair**
The Subscript node isn't laid-out the way the code in OldRemangler thinks, which has the unfortunate result of causing crashes.

rdar://63410196

### CODE REVIEW

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
@swift-ci Please smoke test macOS platform

**Review by eeckstein — APPROVED** [review]
lgtm!

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Pull request merged**
