### PR TITLE
[BuilderTransform] Extract all builder related operations into `ResultBuilder` type

### PR DESCRIPTION
**Pull request by xedin**
This is a very first step towards transforming result builder handling into an AST transformation.
Makes it possible to share common functionality between existing and new transforms and cache
the information about the builder if needed.

The list of operations:

- `supports(...)`
- `buildCall(...)`
- `buildVar(...)`
- `buildVarRef(...)`

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Review by hborla — APPROVED** [review]
Nice!

**Comment by xedin** [comment]
@swift-ci please smoke test

**Pull request merged**
