### PR TITLE
[SourceKit] Reorganize code completion options

### PR DESCRIPTION
**Pull request by rintaro**
* Abolish `reuseastcontext` per-request option. Reusing ASTContext is essentially *non* per-request functionality. 
* Add `MaxASTContextReuseCount` global configuration instead.

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test macOS

**Comment by rintaro** [comment]
@swift-ci Please test Windows

**Review by benlangmuir — APPROVED** [review]

**Comment by rintaro** [comment]
Windows failure is unrelated. Merging

**Pull request merged**
