### PR TITLE
Diagnostic fixes to LifetimeDependence 

### PR DESCRIPTION
**Pull request by meg-gupta**
Also move the implementation to AST/

Fixes rdar://126385021

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci test

**Review by atrick — APPROVED** [review]
Awesome! Thanks.

Did all the tests from rdar://126385021 make it in?

**Comment by meg-gupta** [comment]
@atrick Yes! All the tests are fixed here

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Pull request merged**
