### PR TITLE
[Diag] QoI: ownership in protocol check should not be 'else' clause

### PR DESCRIPTION
**Pull request by davezarzycki**
Hey @DougGregor – This might be worth cherry-picking into the 4.2 branch.

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by davezarzycki** [comment]
@swift-ci please smoke test linux

**Review by xedin — APPROVED** [review]
Nice! I guess the idea here was that if something already set `attr->isInvalid()` there is no reason to try and diagnose it again... You might want to add that check to new condition as well.

**Comment by davezarzycki** [comment]
@xedin – I'm not following your comment. The idea here is that sometimes multiple errors need to be reported for a given AST node. There are two diagnostics here that should never have been joined via an `else` clause. The rest of the pull request is just code clean up.

@swift-ci please smoke test linux

**Comment by xedin** [comment]
I just wanted to point out that maybe it was `else if` because that places shouldn't have diagnosed for both these problems, but probably not...

**Comment by davezarzycki** [comment]
Digging through the git blame history, it looks like an honest mistake from the start. See #11744.

**Comment by xedin** [comment]
Sounds good!

**Pull request merged**
