### PR TITLE
[TypeCheckEffects] Diagnose type mismatches for thrown errors in contexts that throw `Never`.

### PR DESCRIPTION
**Pull request by hborla**
Previously, this mistake slipped through the effects checker (and crashed in SILGen) because it used a fallback type of `any Error` if a catch node had a null thrown error type. This change also fixes an issue where thrown error type mismatches were not diagnosed at all in autoclosures.

Resolves: rdar://124623418

### CODE REVIEW

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by hborla** [comment]
@swift-ci please smoke test

**Review by ktoso — APPROVED** [review]
Looks good AFAICS!

**Pull request merged**
