### PR TITLE
[build.ps1] add host SDK path when building foundation for Android on…

### PR DESCRIPTION
**Pull request by hyp**
… windows

This lets us build the FoundationMacros for the windows host

### CODE REVIEW

**Comment by hyp** [comment]
https://github.com/compnerd/swift-foundation/pull/1

**Comment by hyp** [comment]
@swift-ci please test

**Review by hjyamauchi — APPROVED** [review]

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test windows

**Comment by hyp** [comment]
@swift-ci please smoke test windows

**Comment by shahmishal** [comment]
@swift-ci please test windows

**Pull request merged**
