### PR TITLE
[IRGen] Make sure a C++ constructor thunk is called when it's needed

### PR DESCRIPTION
**Pull request by ahatanaka**
This fixes a bug where the thunk for a C++ constructor call wasn't being called when the constructor was called the second time.

### CODE REVIEW

**Review by egorzhdan — APPROVED** [review]
Awesome, thanks!

**Comment by ahatanaka** [comment]
@swift-ci please smoke test

**Review by hyp — APPROVED** [review]

**Comment by ahatanaka** [comment]
@swift-ci please smoke test

**Comment by ahatanak** [comment]
@swift-ci please smoke test

**Comment by ahatanaka** [comment]
@swift-ci please smoke test Windows

**Pull request merged**
