### PR TITLE
[benchmark] Existential Redux

### PR DESCRIPTION
**Pull request by palimondo**
This PR reintroduces the Existential benchmark family with **108** performance tests. It tests the performance of varying number of non-mutating and mutating method calls on instances of existential types of growing size and arrays thereof (**12** groups x **9** variants). 

It was previously marked as unstable and was not executed as part of the pre-commit suite. The root of the instability was too big inner loop multiplier (5_000_000 and 5_000), which meant the workload was very susceptible to accumulation of measurement error caused by context switching. Lowering the inner loop multipliers so that each benchmark runs in under 1000 μs results in clearly defined runtimes when measured with [More Robust Benchmark_Driver](https://github.com/apple/swift/pull/19910). 

The benchmarks were renamed according to naming convention proposed in #20334, as the original names were among the longest in the SBS. For example `ExistentialTestPassExistentialTwoMethodCalls_ClassValueBuffer4` became `Existential.Pass.method.2x.Ref4`.

Smaller workload revealed significant setup overhead caused by initialization of the existential array in the `Existential.Array` group, which was isolated into type specific `setUpFunction`s. New `Existential.Array.init` benchmark group was added to measure this explicitly.

New `BenchmarkCategory.existential` was added to tag these tests. Running these 108 test in a manner equivalent to `run_smoke_bench` (`time ./Benchmark_O --tags=existential --sample-time=0.0025  --num-samples=3`) take 1.3 seconds on my 2008 MBP — properly sized benchmarks improve measurement precision and have negligible impact on the overall time it takes to run benchmark suite.

**Procedural note:** This refactoring was facilitated by first reverse-engineering a `.gyb` file that generated the original 810 LOC swift file. This allowed for systematic changes of the template used to generate the original 99 tests. Isolating the array creation into setup method enabled removal of specialized `run_` functions, eliminating 144 LOC. This technique was than applied to the rest of test, eliminating another 202 LOC. The use of GYB has proven indispensable in performing this refactoring, vastly improving the code maintainability.

The refactoring is thoroughly documented in the commit descriptions, it is therefore best to review this PR by individual commits (check `.gyb` first, then the generated `.swift` for the results of the change).

### CODE REVIEW

**Comment by palimondo** [comment]
@aschwaighofer as original author of these benchmarks, could you please help me provide a description of their purpose? @atrick asked me to always add it for new tests over in #20552.

My impression is that the different variants (originally `IntValueBuffer[0-4]` and `ClassValueBuffer[1-4]`, renamed to `Val[0-4]` and `Ref[1-4]`) are meant to illustrate relative cost increases as the size of the underlying Existential type grows.

From the comment in [SortLargeExistentials](https://github.com/apple/swift/blob/master/benchmark/single-source/SortLargeExistentials.swift#L31):
> // Make this struct a large struct which does not fit into the 3-word
>  // existential inline buffer.

The `Val4` is clearly meant as a type that doesn't fit this inline buffer. What about the `Ref` types?
Why did you use `Int` for the 4th field in `ClassValueBuffer4/Ref4`? — this seems to lead to strange performance boost compared to `Ref[2-3]`, on par with `Val4` and `Ref1` in most tests. I thought this would warrant a performance bug report, once these are merged.

**Comment by palimondo** [comment]
@eeckstein can you please run benchmark here, too? 🤖 doesn't recognize me yet…
@swift-ci please benchmark

**Comment by aschwaighofer** [comment]
> @aschwaighofer as original author of these benchmarks, could you please help me provide a description of their purpose? @atrick asked me to always add it for new tests over in #20552.
> 
> My impression is that the different variants (originally `IntValueBuffer[0-4]` and `ClassValueBuffer[1-4]`, renamed to `Val[0-4]` and `Ref[1-4]`) are meant to illustrate relative cost increases as the size of the underlying Existential type grows.
> 
> From the comment in [SortLargeExistentials](https://github.com/apple/swift/blob/master/benchmark/single-source/SortLargeExistentials.swift#L31):
> 
> > // Make this struct a large struct which does not fit into the 3-word
> > // existential inline buffer.
> 
> The `Val4` is clearly meant as a type that doesn't fit this inline buffer. What about the `Ref` types?
> Why did you use `Int` for the 4th field in `ClassValueBuffer4/Ref4`? — this seems to lead to strange performance boost compared to `Ref[2-3]`, on par with `Val4` and `Ref1` in most tests. I thought this would warrant a performance bug report, once these are merged.

The purpose of those benchmarks was to evaluate different scenarios when I moved the implementation of existentials (protocol values) to heap based copy-on-write buffers to evaluate implementation decisions.

I don't think we want to run those as part of regular performance tests.

The performance boost of ClassValueBuffer4 vs ClassValueBuffer3 is expected because copying the existential only involves copying one reference of the heap based copy-on-write buffer (outline case) that holds the struct vs copying the individual fields of the struct in the inline case of ClassValueBuffer3.

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Comment by palimondo** [comment]
@swift-ci please smoke test

**Comment by palimondo** [comment]
@swift-ci Please benchmark

**Comment by palimondo** [comment]
@swift-ci Please benchmark

**Comment by palimondo** [comment]
@swift-ci Please benchmark

**Comment by palimondo** [comment]
@swift-ci please smoke test

**Comment by palimondo** [comment]
@swift-ci please smoke test

**Comment by palimondo** [comment]
As I've [explained above](https://github.com/apple/swift/pull/20666#issuecomment-439645049), the setup overhead cannot yet be completely eliminated due to [SR-9298](https://bugs.swift.org/browse/SR-9298).

The whole set of 109 benchmarks  adds less than 1 second to the full measured iteration of `run_smoke_bench`, which is totally negligible, I'm therefore strongly advocating for re-enabling this refactored benchmark family as part of the standard commit benchmark set.

@eeckstein Please review 🙏 (when you get back...)

**Comment by eeckstein** [comment]
As @aschwaighofer (the author of the benchmarks) already said, these benchmarks are not really there to find optimization regressions/improvements. Arnold added them to evaluate different implementation scenarios.
If we want to test if existential code generation works as expected, it's better to do that with FileCheck tests.

Even if they runtime of those benchmarks is minimal, I'm not in favor of adding benchmarks which are not really useful.

**Comment by palimondo** [comment]
In that case they should be removed from SBS altogether.

**Comment by palimondo** [comment]
@eeckstein Are you objecting to re-enabling these benchmarks or to the refactoring+renaming itself?
Would you be OK with merging this if I've replaced the `.existential` tag (formerly `.unstable`) with a `.skip`?

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
@swift-ci please smoke test

**Comment by palimondo** [comment]
@swift-ci please smoke test

**Comment by palimondo** [comment]
@swift-ci please smoke test

**Comment by palimondo** [comment]
@swift-ci please smoke test os x platform

**Comment by eeckstein** [comment]
> Would you be OK with merging this if I've replaced the `.existential` tag (formerly `.unstable`) with a `.skip`?

yes, that would be fine

**Comment by palimondo** [comment]
@eeckstein Would you put that in the review or can I just merge once the checks are completed?

**Review by eeckstein — APPROVED** [review]

**Pull request merged**
