### PR TITLE
[opt] Add three new perf annotations: `@_noRuntime`, `@_noExistentials`, and `@_noObjCBridging`.

### PR DESCRIPTION
**Pull request by zoecarver**
This is mostly boilerplate to hook up the existing infrastructure to some new annotations.

### CODE REVIEW

**Comment by zoecarver** [comment]
@swift-ci please smoke test

**Comment by zoecarver** [comment]
@swift-ci please smoke test

**Comment by zoecarver** [comment]
@swift-ci please smoke test macOS platform

**Review by eeckstein — APPROVED** [review]
lgtm

**Pull request merged**
