### PR TITLE
[CSBindings] A couple of minor adjustments to inferring default bindings from literal protocols

### PR DESCRIPTION
**Pull request by xedin**
- Don't track `ExpressibleByNilLiteral` as a coverable protocol because it can't produce a binding
- Coalesce `ExpressibleBy{Integer, Float}Literal` early
- Avoid double-checking whether protocol requirement is direct

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Review by hborla — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test

**Pull request merged**
