### PR TITLE
[5.9][move-only] Ensure that if we have an allocation that isn't fully initialized (and DI errors on it as such), the move checkers do not run on the allocation.

### PR DESCRIPTION
**Pull request by gottesmm**
• Description: [move-only] Ensure that if we have an allocation that isn't fully
  initialized (and DI errors on it as such), the move checkers do not run on the
  function in question.
• Risk: Low risk. Only affects noncopyable types.
• Original PR: #65773
• Reviewed By: @jckarter
• Testing: I added tests/updated other tests to make sure this did not happen.
• Resolves: rdar://108993297

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
Made the change smaller/simpler so that I don't have to touch the module format.

**Comment by gottesmm** [comment]
@swift-ci test

**Review by jckarter — APPROVED** [review]

**Comment by gottesmm** [comment]
Original PR: #65773

**Review by airspeedswift — APPROVED** [review]

**Pull request merged**
