### PR TITLE
[SIL] Phi with incoming lexical value is lexical.

### PR DESCRIPTION
**Pull request by nate-chandler**
Added `SILPhiArgument::isLexical`.  It's true for phis which have an incoming value that's lexical.  Dispatch to this member from `ValueBase::isLexical`.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test macOS platform

**Comment by nate-chandler** [comment]
@swift-ci please test macOS platform

**Comment by atrick** [comment]
LGTM

**Pull request merged**
