### PR TITLE
[Build Script] Pass down a CMake path to swift-driver's build script

### PR DESCRIPTION
**Pull request by artemcm**

### CODE REVIEW

**Comment by artemcm** [comment]
https://github.com/apple/swift-driver/pull/246
@swift-ci smoke test

**Comment by artemcm** [comment]
apple/swift-driver#246
@swift-ci Please Build Toolchain macOS Platform

**Comment by artemcm** [comment]
apple/swift-driver#246
@swift-ci smoke test

**Comment by artemcm** [comment]
apple/swift-driver#246
@swift-ci Please Build Toolchain macOS Platform

**Comment by artemcm** [comment]
apple/swift-driver#246
@swift-ci smoke test

**Comment by artemcm** [comment]
apple/swift-driver#246
@swift-ci smoke test OS X platform

**Comment by artemcm** [comment]
apple/swift-driver#246
@swift-ci smoke test OS X platform

**Comment by artemcm** [comment]
apple/swift-driver#246
@swift-ci smoke test OS X platform

**Comment by artemcm** [comment]
apple/swift-driver#246
@swift-ci smoke test OS X platform

**Comment by artemcm** [comment]
apple/swift-driver#246
@swift-ci Please Build Toolchain macOS Platform

**Comment by artemcm** [comment]
apple/swift-driver#246
@swift-ci smoke test

**Comment by artemcm** [comment]
apple/swift-driver#246
@swift-ci smoke test

**Comment by artemcm** [comment]
apple/swift-driver#246
@swift-ci smoke test

**Comment by artemcm** [comment]
apple/swift-driver#246
@swift-ci Please Build Toolchain macOS Platform

**Comment by artemcm** [comment]
apple/swift-driver#246
@swift-ci smoke test

**Comment by artemcm** [comment]
apple/swift-driver#246
@swift-ci Please Build Toolchain macOS Platform

**Comment by artemcm** [comment]
apple/swift-driver#246
@swift-ci smoke test

**Comment by artemcm** [comment]
apple/swift-driver#246
@swift-ci Please Build Toolchain macOS Platform

**Comment by artemcm** [comment]
apple/swift-driver#246
@swift-ci smoke test OS X platform

**Comment by artemcm** [comment]
apple/swift-driver#246
@swift-ci smoke test OS X platform

**Comment by artemcm** [comment]
apple/swift-driver#246
@swift-ci Please Build Toolchain macOS Platform

**Comment by artemcm** [comment]
apple/swift-driver#246
@swift-ci Please Build Toolchain macOS Platform

**Comment by artemcm** [comment]
apple/swift-driver#246
@swift-ci smoke test OS X platform

**Comment by artemcm** [comment]
apple/swift-driver#246
@swift-ci smoke test Linux Platform

**Comment by artemcm** [comment]
apple/swift-driver#246
@swift-ci Please Build Toolchain macOS Platform

**Review by nkcsgexi — APPROVED** [review]
Will this PR finalize rdar://69708243? If so, we could associate the PR with the radar by including the radar number in the PR description.

**Comment by artemcm** [comment]
> Will this PR finalize rdar://69708243? If so, we could associate the PR with the radar by including the radar number in the PR description.

It will be submitted simultaneously with: https://github.com/apple/swift-driver/pull/246. The combination of these PRs will resolve this radar. It is the corresponding swift-driver PR that contains the bulk of the work, and its description mentions this Radar.

**Pull request merged**
