### PR TITLE
Fix a syntax error in build script

### PR DESCRIPTION
**Pull request by adrian-prantl**

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci smoke test

**Comment by jrose-apple** [comment]
Out of shell scripting curiosity, what was wrong with your previous version?

**Comment by adrian-prantl** [comment]
tbh, I'm a little puzzled by it: https://ci.swift.org/view/LLDB/job/oss-lldb-asan-osx/845/console

**Comment by adrian-prantl** [comment]
perhaps the space before the `=`?

**Comment by jrose-apple** [comment]
Ah, yeah, that's a good guess.

**Pull request merged**
