### PR TITLE
[stdlib] Set/Dictionary: Make some implementation details non-inlinable

### PR DESCRIPTION
**Pull request by lorentey**
Do a quick inlinability audit pass for Set/Dictionary internals. Clean up obsolete gybisms.

* Classes and methods implementing Cocoa API (NSSet, NSDictionary, NSEnumerator) do not need to be included in the Swift ABI; make them internal.
* Make Set/Dictionary iteration state for the lazily bridged Cocoa case non-inlinable.
* Make the conversion from lazily bridged to native sets/dictionaries non-inlinable.
* Simplify code by refactoring some obsolete gybisms. (References to Key & Value in Set, pointless methods, `_HashBuffer`.)

rdar://problem/42282850

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci please smoke test

**Comment by lorentey** [comment]
@swift-ci please smoke test

**Comment by lorentey** [comment]
@swift-ci please smoke test

**Comment by lorentey** [comment]
@swift-ci please smoke test

**Comment by lorentey** [comment]
@swift-ci please benchmark

**Comment by lorentey** [comment]
@swift-ci please benchmark

**Comment by lorentey** [comment]
@swift-ci please smoke test

**Comment by lorentey** [comment]
@swift-ci please smoke test

**Comment by lorentey** [comment]
@swift-ci please smoke test

**Review by airspeedswift — APPROVED** [review]

**Pull request merged**
