### PR TITLE
Adjust space in property/subscript declarations

### PR DESCRIPTION
**Pull request by adrfer**
This is just a very simple cleanup to maintain consistency with the code style presented at [The Swift Programming Language](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language).

### CODE REVIEW

**Comment by gribozavr** [comment]
Thank you!  Could you revert the changes to trailing whitespace from the diff?

**Comment by adrfer** [comment]
Hmmm, I can see it by running `git diff --ignore-space-at-eol HEAD^`...

**Comment by gribozavr** [comment]
I'd just edit the patch by hand and remove the `@@` hunks that contain whitespace changes.

**Comment by adrfer** [comment]
Had the setting `"trim_trailing_white_space_on_save": true` on my editor. Anyways, guess everything is ok now :smile:

**Comment by gribozavr** [comment]
Thanks again!

**Pull request merged**
