### PR TITLE
[5.5] fix missing effects specifiers on some properties in swiftinterface

### PR DESCRIPTION
**Pull request by kavon**
Cherry-pick for 5.5 of https://github.com/apple/swift/pull/37156  and https://github.com/apple/swift/pull/37190 to resolve rdar://77324796

### CODE REVIEW

**Comment by kavon** [comment]
@swift-ci please smoke test

**Review by DougGregor — APPROVED** [review]

**Comment by kavon** [comment]
@swift-ci please test

**Comment by kavon** [comment]
@swift-ci please test and merge

**Comment by kavon** [comment]
@swift-ci please test

**Comment by kavon** [comment]
@swift-ci please test Windows platform

**Review by DougGregor — APPROVED** [review]

**Comment by DougGregor** [comment]
@swift-ci please test macOS

**Pull request merged**
