### PR TITLE
[parse-sil] Refactor huge per op code parsing switch into its own method.

### PR DESCRIPTION
**Pull request by gottesmm**
Done using Xcode's refactoring engine! Should be NFC.

I am going to turn this method into a visitor on the op code.

NOTE: Xcode's refactoring engine messd with the whitespace, so I also ran this
through git-clang-format.

----

Just done while I was bored last night. We have talked about doing this a long time since it is impossible to separate the rest of the functionality from the method from the huge switch.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Review by atrick — APPROVED** [review]
Nice first step. It's impossible to tell if any functionality changed but if it was automated then we can assume it's NFC. Thanks.

**Comment by gottesmm** [comment]
Linux failure was the infamous dispatch overlay thing.

**Comment by gottesmm** [comment]
@swift-ci test linux platform

**Comment by gottesmm** [comment]
@swift-ci test linux platform

**Pull request merged**
