### PR TITLE
Revert "[Regex] Really build _RegexParser without resilience."

### PR DESCRIPTION
**Pull request by tshortli**
This reverts https://github.com/apple/swift/pull/70953.

Resolves rdar://124541877

### CODE REVIEW

**Comment by tshortli** [comment]
@swift-ci please test

**Review by Azoy — APPROVED** [review]
This is most unfortunate.

**Comment by tshortli** [comment]
@swift-ci please test Linux

**Comment by tshortli** [comment]
@swift-ci please test Linux

**Pull request merged**
