### PR TITLE
Update -sanitize=fuzzer option to take into account new libFuzzer location

### PR DESCRIPTION
**Pull request by cheshire**
This change will not pass tests yet, as it is dependent on llvm/clang/compiler-rt changes being cherry-picked (and those in turn will fail tests without this change).
Putting this out for code review.

### CODE REVIEW

**Comment by cheshire** [comment]
Change is identical to https://github.com/apple/swift/pull/11594, but this one is on `master`, and other one is on `master-next`.

**Comment by gottesmm** [comment]
@cheshire if you want to test the PRs together, you can use cross repo pull request testing. There is information on how to do this in ./docs/ContinuousIntegration.md.

**Comment by gottesmm** [comment]
This: https://github.com/apple/swift/blob/master/docs/ContinuousIntegration.md#cross-repository-testing

**Comment by cheshire** [comment]
@gottesmm thanks, let's try that!

**Comment by cheshire** [comment]
Please test with following PR:
https://github.com/apple/swift-llvm/pull/57
https://github.com/apple/swift-clang/pull/118
https://github.com/apple/swift-compiler-rt/pull/12

@swift-ci Please smoke test

**Comment by cheshire** [comment]
Please test with following PR:
apple/swift-llvm#57
apple/swift-clang#118
apple/swift-compiler-rt#12

@swift-ci Please smoke test

**Comment by cheshire** [comment]
Please test with following PR:
apple/swift-llvm#57
apple/swift-clang#118
apple/swift-compiler-rt#12

@swift-ci Please smoke test

**Pull request merged**
