### PR TITLE
[5.1 EARLY]  Rename -enable-resilience to -enable-library-evolution and make it a driver flag

### PR DESCRIPTION
**Pull request by jrose-apple**
Cherry-picks @slavapestov's #23280 and #23336 in cut-down form for the old 5.1 branch, for Apple-internal purposes.

rdar://problem/49985713

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
Thanks

**Comment by jrose-apple** [comment]
Linux failure is because swift-corelibs-foundation doesn't have an early branch.

macOS failure is because I forgot to update tests, so let's try that again.

@swift-ci Please test macOS

**Comment by jrose-apple** [comment]
@swift-ci Please test macOS

**Pull request merged**
