### PR TITLE
Stop using SWIFT_STDLIB_SINGLE_THREADED_CONCURRENCY under SWIFT_STDLIB_TASK_TO_THREAD_MODEL_CONCURRENCY

### PR DESCRIPTION
**Pull request by kubamracek**
Using single-threaded concurrency was a temporary solution, now that the task-to-thread model actually supports multiple threads, let's switch off of it. Instead, let's introduce a "global executor none" option (implicitly set under the task-to-thread model) to denote that the concurrency model is not using a global executor.

rdar://99448771

### CODE REVIEW

**Comment by rokhinip** [comment]
As an additional guard, we might want to also enforce that `SWIFT_HAS_VOUCHERS` and `SWIFT_CONCURRENCY_ENABLE_PRIORITY_ESCALATION` are 0 under `SWIFT_CONCURRENCY_TASK_TO_THREAD`.

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by al45tair** [comment]
The failed test on macOS is being caused by an LLDB change that is being reverted (https://github.com/apple/llvm-project/pull/5866)

**Review by al45tair — APPROVED** [review]

**Comment by kubamracek** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Review by mikeash — APPROVED** [review]

**Comment by kubamracek** [comment]
The preset CI job is failing in the baseline already (due to nightly toolchain on swift.org not being new enough). I verified this PR builds and works locally instead (with a toolchain built from main). Merging.

**Pull request merged**
