### PR TITLE
[ConstraintSolver] Remove hack related to single parameter handling

### PR DESCRIPTION
**Pull request by xedin**

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
Failure is the compatibility suite seems unrelated (missing `_Incrementable` class declaration) but I'll wait for main run to finish.

@CodaFi When you added that hack did you have any specific failure in mind?

**Comment by CodaFi** [comment]
At the time I was hoping to use this to eventually enforce an invariant.  CSGen would be updated so it no longer created constraints that look like `t0 ~> (t1)` which would allow me to finally unify the logic in this function and `simplifyApplicableFn` and flush the hack.

**Comment by xedin** [comment]
@CodaFi let's see if we can do it another way without using `BindParam` here...

**Pull request merged**
