### PR TITLE
[Sema] Add a fix-it for non-optional bindings initialized with nil.

### PR DESCRIPTION
**Pull request by jrose-apple**
```
<stdin>:1:16: error: nil cannot initialize specified type 'Int'
var foo: Int = nil
               ^
<stdin>:1:10: note: add '?' to form the optional type 'Int?'
var foo: Int = nil
         ^
            ?
```

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by nkcsgexi** [comment]
Awesome! Fixits like this can make Swift tooling experience much sweeter.

**Comment by jrose-apple** [comment]
I'm basically going through my list of ideas for optional pointer migration work and doing the fix-it-ish ones first. :-)

**Comment by jrose-apple** [comment]
@swift-ci Please test.

**Comment by jrose-apple** [comment]
Linux failure still unrelated. Merging!

**Pull request merged**
