### PR TITLE
[DNM][stdlib][ABI] Make default implementation for _rawHashValue(seed:) non-inlinable

### PR DESCRIPTION
**Pull request by lorentey**
Baking the default implementation into binaries prevents types from diverging top-level hashing from `hash(into:)` in future releases.

### CODE REVIEW

**Comment by lorentey** [comment]
This change might have interesting performance effects.

@swift-ci please benchmark

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
That's not great, but it's what it is. The last commit combines this with the resilient hasher; let's see what happens now.

@swift-ci please benchmark

**Comment by lorentey** [comment]
@swift-ci please benchmark

**Comment by airspeedswift** [comment]
We should retest with the new String. I feel like taking the first one is OK (most of the regressions are just reclaiming perf wins vs 4.2), but not the resilient one due to the code size regressions.

**Comment by natecook1000** [comment]
@lorentey Has this ship sailed? Or alternatively, did this land through another channel?

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Comment by lorentey** [comment]
Closing -- this ship has long sailed.

**Pull request closed without merging**
