### PR TITLE
[NFC] Shortened SIL [init] flag.

### PR DESCRIPTION
**Pull request by nate-chandler**
Instead of writing out `[initalization]` for some instructions, use `[init]` everywhere.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by atrick — APPROVED** [review]
Great! It's about time.

**Comment by nate-chandler** [comment]
@swift-ci please test and merge

**Comment by nate-chandler** [comment]
@swift-ci please test linux platform

**Pull request merged**
