### PR TITLE
Enable Playground logging for Tensors.

### PR DESCRIPTION
**Pull request by dan-zheng**
Previously, Playground logging for Tensors was disabled because there was no
send/receive support: https://github.com/apple/swift/commit/5214c17604e9dc5c5b2ad45e13134e89dd46f057

Now that there is send/receive support, logging should be enabled for better
playground usability. The performance hit of send/receives is not particularly
important for Playgrounds.

screen shot 2018-06-26 at 5 58 37 pm

### CODE REVIEW

**Comment by dan-zheng** [comment]
Note: https://github.com/apple/swift/commit/5214c17604e9dc5c5b2ad45e13134e89dd46f057 introduced a lot of tooling (e.g. [`TypeContainsTensorHandle`](https://github.com/apple/swift/commit/5214c17604e9dc5c5b2ad45e13134e89dd46f057#diff-3fac5aad1c52486ae47fc397ddac1bafR38)) for detecting whether a type contains a `(Tensor|Resource|Variant)Handle`.
The only user of that code was PlaygroundTransform.cpp, so now the code is no longer used. Should it be removed?

**Comment by rxwei** [comment]
Let's keep it for now. I assume some logic in partitioning can use the tooling you mentioned.

**Review by rxwei — APPROVED** [review]
Very nice!

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Pull request merged**
