### PR TITLE
[6.0] Build and install swift-testing in toolchains

### PR DESCRIPTION
**Pull request by rintaro**
Cherry-pick #75515 and  #75909 into `release/6.0`

* **Explanation**: As mentioned in the (now approved) [A New Direction for Testing in Swift](https://github.com/swiftlang/swift-evolution/blob/main/visions/swift-testing.md#distribution) vision document, include the swift-testing project in Swift toolchains.
* **Scope**: Packaging, SwiftPM, SwiftTesting
* **Risk**: Low-Mid. This is a build-script only changes without any application code changes. As swift-testing in toolchain is a new addition, it won't break existing files. That being said, swiftpm may changes the behavior depending on the existence of swift-testing in the search paths.
* **Testing**: Passes current test suite. Manually tested PR toolchains
* **Issues**: rdar://123924911
* **Reviewer**: Eric Miotto (@edymtt), Evan Wilde (@etcwilde)

### CODE REVIEW

**Comment by rintaro** [comment]
https://github.com/swiftlang/swift-installer-scripts/pull/327
https://github.com/swiftlang/swift-package-manager/pull/7856
@swift-ci Please test

**Comment by finagolfin** [comment]
Note that now that `swift-testing` is in the trunk toolchain, [automated snapshot tags will need to be added to that repo](https://github.com/swiftlang/swift-testing/tags), else a tag checkout will give you a random commit from trunk. I think @shahmishal sets that up, don't know if anybody else can.

**Comment by rintaro** [comment]
https://github.com/swiftlang/swift-installer-scripts/pull/327
https://github.com/swiftlang/swift-package-manager/pull/7856
@swift-ci Please test

**Comment by rintaro** [comment]
https://github.com/swiftlang/swift-installer-scripts/pull/327
@swift-ci Please test

**Comment by rintaro** [comment]
https://github.com/swiftlang/swift-installer-scripts/pull/327
@swift-ci Please test

**Comment by rintaro** [comment]
https://github.com/swiftlang/swift-installer-scripts/pull/327
@swift-ci Please build toolchain macOS

**Comment by rintaro** [comment]
https://github.com/swiftlang/swift-installer-scripts/pull/327
@swift-ci Please build toolchain Windows

**Comment by rintaro** [comment]
https://github.com/swiftlang/swift-installer-scripts/pull/327
@swift-ci Please build toolchain Linux

**Comment by rintaro** [comment]
https://github.com/swiftlang/swift-installer-scripts/pull/327
@swift-ci Please test

**Comment by rintaro** [comment]
https://github.com/swiftlang/swift-installer-scripts/pull/327
https://github.com/apple/swift-corelibs-foundation/pull/5078
@swift-ci Please test

**Comment by rintaro** [comment]
https://github.com/swiftlang/swift-installer-scripts/pull/327
https://github.com/apple/swift-corelibs-foundation/pull/5078
@swift-ci Please test

**Comment by rintaro** [comment]
https://github.com/swiftlang/swift-installer-scripts/pull/327
https://github.com/apple/swift-corelibs-foundation/pull/5078
@swift-ci Please build toolchain macOS

**Comment by rintaro** [comment]
https://github.com/swiftlang/swift-installer-scripts/pull/327
https://github.com/apple/swift-corelibs-foundation/pull/5078
@swift-ci Please build toolchain Linux

**Comment by rintaro** [comment]
https://github.com/swiftlang/swift-installer-scripts/pull/327
https://github.com/apple/swift-corelibs-foundation/pull/5078
@swift-ci Please build toolchain Windows

**Review by grynspan — APPROVED** [review]

**Review by bnbarham — APPROVED** [review]

**Pull request merged**
