### PR TITLE
fix SILGen bug for cross-module actor let accesses

### PR DESCRIPTION
**Pull request by kavon**
When trying to access a let-bound property of an actor across
a moudule boundary, the operation should be treated as async.
But, upon reaching SILGen, the compiler would crash when trying
to emit the needed hop, because the base of the element reference
was missing. This commit fixes that and adds regression coverage.

resolves rdar://81812013

### CODE REVIEW

**Comment by kavon** [comment]
@swift-ci please smoke test and merge

**Review by DougGregor — APPROVED** [review]
LGTM. This code would crash the compiler before, and the value passed in is otherwise not queried, so this looks Very Safe.

**Comment by kavon** [comment]
I wanted to add a bit more regression test coverage in the test by adding a case where the access happens in an optional chain.

**Comment by kavon** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
