### PR TITLE
Fix bad SILGen for optional noescape closures [4.2]

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes <rdar://problem/38545956>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by gottesmm** [comment]
Hey Slava. Can this wait? I need to land +0 tonight and I am pretty sure this is going to cause me merge conflict problems.

**Comment by gottesmm** [comment]
oh... nm it is on the 4.2 branch. Sorry!

**Comment by slavapestov** [comment]
@gottesmm The changes are already on master.

**Comment by gottesmm** [comment]
@slavapestov No worries. Sorry for the noise! = ).

**Pull request merged**
