### PR TITLE
SourceKit: the swift-lang requires the SDK Overlay

### PR DESCRIPTION
**Pull request by compnerd**
The swift-lang swift module requires the SDK overlay to be built (for the
dependency on Darwin).  Ensure that this is taken into consideration when we
attempt to build it.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @nkcsgexi

**Comment by nkcsgexi** [comment]
Can we drop the Darwin dependency for SwiftLang so we don't need this change? I suspect SwiftLang still builds without the SDK overlay.

**Comment by compnerd** [comment]
@nkcsgexi - sure, I can loosen the dependency to just the standard library, pretty sure that works.

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Pull request merged**
