### PR TITLE
[gardening] Fix recently introduced typos: "decoarted" → "decorated", "conveneion" → "convention", "inteface" → "interface", "irredutable" → "irrefutable", "anyting" → "anything"

### PR DESCRIPTION
**Pull request by practicalswift**

### CODE REVIEW

**Comment by gribozavr** [comment]
@swift-ci Please smoke test

**Comment by gribozavr** [comment]
@practicalswift There are build issues...

**Comment by practicalswift** [comment]
@gribozavr Sorry, missed an instance of the inteface/interface typo in `include/swift/AST/PrintOptions.h`. Fixed and squashed :-)

**Comment by gribozavr** [comment]
@swift-ci Please smoke test

**Comment by practicalswift** [comment]
@gribozavr The smoke test build failure is unrelated? :-)

**Comment by gribozavr** [comment]
Yeah, but Linux is good!

**Pull request merged**
