### PR TITLE
LoopRotate: Fix avoiding copy_value hoisted to the pre-header

### PR DESCRIPTION
**Pull request by meg-gupta**
copy_value is marked as having no side effects.
Teach LoopRotate to avoid moving it to the pre header and instead duplicate it while rotating the loop.

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci test

**Review by atrick — COMMENTED** [review]
How does loop rotate handle other instructions which "may retain"?
Isn't `copy_value` considered to have a "retain" side effect? If not, that seems like a bigger bug.

**Comment by meg-gupta** [comment]
LoopRotate looks for mayHaveSideEffects - https://github.com/apple/swift/blob/5b9aef91f8e96dcc82ac3828c18fa26473d17fe6/lib/SILOptimizer/LoopTransforms/LoopRotate.cpp#L116 

`copy_value` is marked as having no side effects

**Review by atrick — APPROVED** [review]
Meghana pointed out that in `copy_value` is not actually supposed to have side effects. I think this change is fine and we can discuss how to move forward in parallel

**Comment by atrick** [comment]
@eeckstein Here's the issue:

In OSSA `copy_value` does not have any side-effects for the purpose of deleting the instruction or moving code around the instructions. As long as the OSSA constraints still hold-up, those transformations are legal. So, in that sense "may-retain" is false. But for the purpose of hoisting/sinking the `copy_value` itself, it does perform a retain. So in that sense, "may-retain" is true. Any idea how we want to model this kind of side-effect going forward?

**Pull request merged**
