### PR TITLE
(SR-8783) nicer textual sil for graph_op

### PR DESCRIPTION
**Pull request by marcrasi**
See `test/TensorFlow/graph_op_inst.sil` for some examples of the new textual format.

I also removed `addScalarOperand` and `addTFTensorToI1Operand` to make the printing & parsing logic simpler. The adjustments necessary turned out to be small and simple.

### CODE REVIEW

**Review by bgogul — APPROVED** [review]
Looks good!

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow linux cpu

**Comment by wanfakir96** [comment]
https://github.com/apple/swift/pull/19429

**Comment by wanfakir96** [comment]
https://github.com/apple/swift/pull/19429

**Comment by wanfakir96** [comment]
https://github.com/apple/swift/pull/19429

**Pull request merged**
