### PR TITLE
Allow dictionaries keyed by CodingKey to be Codable

### PR DESCRIPTION
**Pull request by itaiferber**
**What's in this pull request?**
Addresses [SR-5312](https://bugs.swift.org/browse/SR-5312).

`Dictionary<K, V>` can be `Codable` if `V` is `Codable` and `K` is `Codable` or if it conforms to `CodingKey`.

### CODE REVIEW

**Comment by itaiferber** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
We're not going to be able to implement this with conditional conformances. Maybe CodingKey should just inherit from Codable?

**Comment by jrose-apple** [comment]
cc @DougGregor

**Comment by itaiferber** [comment]
@jrose-apple Why? `extension Dictionary : Codable where Key : CodingKey, Value : Codable`, no?

**Comment by jrose-apple** [comment]
The current plan for conditional conformances is to still only allow one conformance per type, conditional or not. Allowing multiple ways for something to conform results in doing overload resolution on conformances at runtime, or picking different conformances based on static type information, neither of which we want.

**Comment by itaiferber** [comment]
@jrose-apple That seems limiting (especially for types which have multiple generic params)... Are you planning on ever expanding that? This requires us to make `CodingKey`s `Codable`, which doesn't necessarily always make sense.

**Comment by itaiferber** [comment]
@jrose-apple Scratch that, makes sense: https://github.com/apple/swift-evolution/blob/master/proposals/0143-conditional-conformances.md#overlapping-conformances

**Comment by itaiferber** [comment]
Going to put this on hold for a little bit to review; perhaps this isn't a good idea to begin with.

**Pull request closed without merging**
