### PR TITLE
Introduce IsImplicitlyUnwrappedOptionalRequest

### PR DESCRIPTION
**Pull request by slavapestov**
This moves the determination of whether a property, subscript, function or constructor produces an IUO value from validateDecl() into its own request.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@jrose-apple Are you OK with ConstructorDecl::getFailability() going away in favor of isFailable()/isImplicitlyUnwrappedOptional()? This introduces a new invalid state but gets rid of a different one, and it seemed to simplify clients overall.

**Comment by jrose-apple** [comment]
Yeah, I looked over that commit specifically and your justification seems reasonable.

**Pull request merged**
