### PR TITLE
[don't merge] Map opened archetypes to the instructions defining them.

### PR DESCRIPTION
**Pull request by swiftix**
#### What's in this pull request?

This is an alternative implementation of opened archetypes mapping, based on some comments from PR https://github.com/apple/swift/pull/2707
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

Introduce a helper class SILOpenedArchetypesTracker for creating and maintaining such mappings.

These mappings are constructed on demand and used by SILCloner, sil-inliner, sil-verifier and other optimizer passes to properly handle opened archetypes.

### CODE REVIEW

**Comment by swiftix** [comment]
@swift-ci Please test Linux

**Comment by swiftix** [comment]
swift-package test failures seem to be unrelated.

**Comment by swiftix** [comment]
@rudkx @atrick Is it more inline with your ideas of rebuilding the map on-demand?

**Comment by atrick** [comment]
Architecturally this is vastly simpler than adding hooks inside SILFunction. It is also simpler in terms of the work actually being done during compilation. The implementation is complicated and awkward because you now need to pass a tracker into SILCloner, and I'm not sure this is really useful as an Analysis either. AFAICT this mapping is really a just utility to be used within SILVerifier. SILCloner does need to be passed a mapping from opened type to open_existential, but only for the types involved in it's own substitution list, which I think could be provided directly by the inliner. I don't know why you need to pass over the function searching for open_existential to build that map. (probably missing something)

**Comment by slavapestov** [comment]
Is this obsolete?

**Comment by swiftix** [comment]
It is obsolete now.  Closing.

**Pull request closed without merging**
