### PR TITLE
[DebugInfo] Stop emitting spare bits mask in debug info

### PR DESCRIPTION
**Pull request by augusto2112**
We're now able to calculate the spare bits mask from other information. Stop emitting it in debug info.

### CODE REVIEW

**Comment by augusto2112** [comment]
https://github.com/swiftlang/llvm-project/pull/9425
@swift-ci test

**Comment by augusto2112** [comment]
https://github.com/swiftlang/llvm-project/pull/9425
@swift-ci test

**Comment by augusto2112** [comment]
https://github.com/swiftlang/llvm-project/pull/9425
@swift-ci test

**Review by adrian-prantl — COMMENTED** [review]
Nice if we don't need it any more!

**Comment by adrian-prantl** [comment]
I'll defer to @tbkka to accept this.

**Review by tbkka — APPROVED** [review]

**Review by al45tair — APPROVED** [review]

**Pull request merged**
