### PR TITLE
Mark legacy overloads of &+ and &- unavailable.

### PR DESCRIPTION
**Pull request by stephentyrone**
These were defined for both FixedWidthInteger and FixedWidthInteger & SignedInteger for source compatibility with Swift 3; the latter set probably should have been removed when we stabilized the ABI, but were not. We can't easily remove them entirely (because we need them for ABI stability now), but we can mark them unavailable so that the typechecker doesn't have to consider them.

https://forums.swift.org/t/very-long-compilation-times-with-custom-and-but-not-with-and/50789/3

### CODE REVIEW

**Comment by stephentyrone** [comment]
@swift-ci please test source compatibility

**Comment by stephentyrone** [comment]
@swift-ci please test compiler performance

**Review by hborla — APPROVED** [review]
Nice!

**Comment by stephentyrone** [comment]
@swift-ci smoke test

**Comment by stephentyrone** [comment]
@swift-ci smoke test

**Review by lorentey — APPROVED** [review]
Looks good! 🚀 

The source compat checker uses a separate exceptions file, so I expect it'll still complain.

**Comment by stephentyrone** [comment]
@swift-ci please smoke test

**Comment by stephentyrone** [comment]
@swift-ci please test source compatibility

**Comment by stephentyrone** [comment]
@swift-ci please test source compatibility

**Comment by stephentyrone** [comment]
@swift-ci please test compiler performance

**Comment by stephentyrone** [comment]
@swift-ci please test

**Comment by stephentyrone** [comment]
@swift-ci smoke test

**Comment by stephentyrone** [comment]
@swift-ci please test source compatibility

**Comment by stephentyrone** [comment]
@swift-ci test

**Comment by stephentyrone** [comment]
Linux failure is unrelated, compatibility suite looks to be noise.

**Pull request merged**
