### PR TITLE
Offset Indexing and Slicing

### PR DESCRIPTION
**Pull request by milseman**

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@nkcsgexi , the ABI checker is telling me: `+Func Collection._reverseOffsetIndex(_:by:) has been added as a protocol requirement`. However, this requirement has a default, so it should be ABI compatible to add.

CC @jrose-apple @DougGregor for confirmation.

**Comment by jrose-apple** [comment]
> @nkcsgexi , the ABI checker is telling me: `+Func Collection._reverseOffsetIndex(_:by:) has been added as a protocol requirement`. However, this requirement has a default, so it should be ABI compatible to add.
> 
> CC @jrose-apple @DougGregor for confirmation.

As long as it has availability, it should be okay, yeah.

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please test linux platform

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
