### PR TITLE
Revert "Begin untangling GenericEnvironment from GenericSignatureBuilder"

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/swift#38384

This regressed the windows builder and introduced an invalid access:
```
Assertion failed: Ptr && "Cannot dereference a null Type!", file C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\include\swift/AST/Type.h, line 220
```

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @slavapestov

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by slavapestov** [comment]
@compnerd How can I reproduce this without Windows?

**Comment by slavapestov** [comment]
Can you send me a symbolicated backtrace at least? The backtrace in the CI build log only has addresses in it.

**Pull request merged**
