### PR TITLE
[docs] Fix typo in docs/DevelopmentTips.md: `boostrapping` -> `bootstrapping`

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Saves copy-pasters some effort ;-)

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
@eeckstein Could you please review this?

**Review by etcwilde — APPROVED** [review]
LGTM.
Thank you for the contributions.

**Comment by etcwilde** [comment]
@swift-ci please smoke test

**Comment by cbjeukendrup** [comment]
Rebased, because of the Windows build failure that was recently fixed in the main branch.

**Comment by etcwilde** [comment]
@swift-ci please smoke test

**Comment by etcwilde** [comment]
> Rebased, because of the Windows build failure that was recently fixed in the main branch.
That's fine. This is a low-risk documentation change, so I'm fine with merging it once the required tests pass.
If it causes things to break, we have bigger issues to deal with.

**Pull request merged**
