### PR TITLE
[5.9][stdlib] Adjust availability of _CharacterRecognizer conformances

### PR DESCRIPTION
**Pull request by lorentey**
This is a cherry pick of #65086, reviewed by @glessard.

These never made it to 5.8, so their availability needs to be bumped to 5.9.

rdar://107909604

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test windows platform

**Comment by lorentey** [comment]
...

```
Failed Tests (2):
  Swift(windows-x86_64) :: IRGen/async/hop_to_executor.sil
  Swift(windows-x86_64) :: IRGen/async/non_musttail_target.sil
```

**Comment by lorentey** [comment]
@swift-ci test windows platform

**Review by stephentyrone — APPROVED** [review]

**Pull request merged**
