### PR TITLE
[CSBindings] Avoid to infer transitive defaults for DefaultClosureType

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
Just a part of #35503 which was reverted due to source compatibility impact.

### CODE REVIEW

**Comment by xedin** [comment]
@LucianoPAlmeida This is very much FC :)

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Review by xedin — APPROVED** [review]

**Comment by LucianoPAlmeida** [comment]
> @LucianoPAlmeida This is very much FC :)

Oops, you right =]

**Comment by LucianoPAlmeida** [comment]
@swift-ci please test source compatibility Release

**Comment by LucianoPAlmeida** [comment]
Seems like source compatibility failures on release are unrelated, 
One [project](https://ci.swift.org/job/swift-PR-source-compat-suite/5280/artifact/swift-source-compat-suite/FAIL_AsyncNinja-AsyncNinja.xcodeproj_4.0_BuildXcodeProjectScheme_AsyncNinja_generic-platform-macOS.log) is failing on `EscapeAnalysis::mayReleaseContent` that probably will be fixed by #36046
And [the other is failing](https://ci.swift.org/job/swift-PR-source-compat-suite/5280/artifact/swift-source-compat-suite/FAIL_SwiftDate-SwiftDate.xcodeproj_5.0_BuildXcodeProjectScheme_SwiftDate-iOS_generic-platform-iOS.log) on a Driver issue... should we wait until source compatibility is fixed?

**Comment by xedin** [comment]
Yeah, it's failing on main as well. Let's land this.

**Pull request merged**
