### PR TITLE
[AutoDiff] Fix `Array.append(_:)` pullback.

### PR DESCRIPTION
**Pull request by dan-zheng**
The derivative wrt `self` should drop the last element from the incoming seed.

Example:
- Incoming seed: `[1, 2, 3, 4]`
- Derivative wrt `self`: `[1, 2, 3]`
- Derivative wrt appended element: `4`

Gardening included: reorganization and consistent variable naming.

### CODE REVIEW

**Review by rxwei — APPROVED** [review]

**Comment by dan-zheng** [comment]
@swift-ci Please test

**Comment by dan-zheng** [comment]
@swift-ci Please test Linux

**Comment by dan-zheng** [comment]
@swift-ci Please test Linux

**Comment by dan-zheng** [comment]
@swift-ci Please test

**Comment by dan-zheng** [comment]
@swift-ci Please smoke test

**Comment by dan-zheng** [comment]
@swift-ci Please test Windows

**Comment by dan-zheng** [comment]
@swift-ci Please test Linux

**Pull request merged**
