### PR TITLE
Fix failing IRGen arm64e tests

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci smoke test

**Comment by kubamracek** [comment]
@swift-ci smoke test

**Comment by kubamracek** [comment]
@swift-ci smoke test

**Comment by kubamracek** [comment]
@swift-ci smoke test

**Comment by kubamracek** [comment]
@swift-ci smoke test

**Comment by kubamracek** [comment]
@swift-ci smoke test

**Comment by kubamracek** [comment]
@swift-ci smoke test

**Comment by kubamracek** [comment]
@swift-ci smoke test

**Comment by drodriguez** [comment]
@kubamracek: seems that this change, which sets linux-gnu with an stable ABI for testing, might broke the Android tests (https://ci-external.swift.org/job/oss-swift-RA-linux-ubuntu-16.04-android-arm64/3981). It seems that the code I am seeing generated might work with the stable ABI checks. Is it safe to put Android in that list of targets? (I can open the PR myself, but I want to double check that I am not doing something weird)

**Comment by kubamracek** [comment]
Sorry for the late reply! The “stable ABI” applies only to platforms that ship Swift in the OS (Darwin), and on Linux we should be emitting the stable ABI version of code. If this broke a test, a PR would be great and I can take a look.

**Pull request merged**
