### PR TITLE
[libSyntax] Added helper variables and methods for SwiftSyntax gyb

### PR DESCRIPTION
**Pull request by kimdv**
https://github.com/apple/swift-syntax/pull/268

This add a leading property for nodes and children.
This will help generating code for SwiftSyntaxBuilder

### CODE REVIEW

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/268

@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@kimdv Could you mark this as ready for review (non-draft)?

**Comment by kimdv** [comment]
@ahoppen the CI failed, don't know why. I just rebased on latest `main`.

**Comment by ahoppen** [comment]
Thanks. Let’s try again.

apple/swift-syntax#268

@swift-ci Please test

**Pull request merged**
