### PR TITLE
Tests: Make some IRGen tests less deployment target dependent

### PR DESCRIPTION
**Pull request by tshortli**
Also, use `%target-cpu` lit substitution in `IRGen/lto_autolink.swift`.

Resolves rdar://121344608

### CODE REVIEW

**Comment by tshortli** [comment]
@swift-ci please test

**Comment by tshortli** [comment]
@swift-ci please smoke test

**Comment by tshortli** [comment]
@swift-ci please smoke test

**Comment by tshortli** [comment]
https://github.com/apple/llvm-project/pull/8041

@swift-ci please smoke test

**Comment by tshortli** [comment]
https://github.com/apple/llvm-project/pull/8041
https://github.com/apple/swift/pull/71130

@swift-ci please smoke test

**Comment by tshortli** [comment]
https://github.com/apple/llvm-project/pull/8041

@swift-ci please smoke test

**Comment by kateinoigakukun** [comment]
`%target-cpu-unknown-linux-gnu` and `%target-cpu-apple-macosx10.15` can result in invalid triples like `wasm32-apple-macosx`. Unfortunately those invalid triples confuse LLVM: https://ci-external.swift.org/job/oss-swift-RA-linux-ubuntu-20.04-webassembly/1907/console

I think it would be better to hardcode supported target triples instead of constructing from `%target-cpu` for this kind of target-specific test. Or we need to exclude invalid triple combinations. I guess you intended to add arm64 / aarch64 targets, right? If so, I will open a PR to update the test case.

**Comment by tshortli** [comment]
Ok, these tests are failing when run on some platforms because not all bots produce x86_64 stdlibs and therefore the tests fail to find the Swift module. Also, hardcoding triples tends to make the tests run long because in some cases it forces the Swift module to be build for that architecture for the first time in the module cache. If we must hardcode the triples then we also need to limit the test to only running on very specific bots where those triples are known to work, and ideally the triple would be the "natural" triple for that bot. The target cpu substitution works well on macOS/iOS/etc to avoid the rebuild problem. Could you refactor this test to use REQUIREs to limit it to specific configurations?

**Comment by kateinoigakukun** [comment]
Okay makes sense to me, thanks for your explanation 🙏 I'll refactor the test in that way

**Pull request merged**
