### PR TITLE
Update module aliasing terms in diagnostics and comments

### PR DESCRIPTION
**Pull request by elsh**
Update module aliasing terms in diagnostics and comments
s/underlying_name/real_name

rdar://110028578

### CODE REVIEW

**Comment by elsh** [comment]
@swift-ci smoke test

**Review by tshortli — COMMENTED** [review]
The details look reasonable to me! I think aligning terminology with the proposal text does probably make sense, though `binary` does feel like a bit of an overloaded term and there's a part of me that feels the old terminology was easier to understand.

Nit: Could use a `git-clang-format` to fix whitespace alignment and line lengths in various places after the find and replace.

**Comment by elsh** [comment]
> The details look reasonable to me! I think aligning terminology with the proposal text does probably make sense, though `binary` does feel like a bit of an overloaded term and there's a part of me that feels the old terminology was easier to understand.
> 
> Nit: Could use a `git-clang-format` to fix whitespace alignment and line lengths in various places after the find and replace.

Will keep realName as is; just changed underlying_name to real_name in diags and comments.

**Comment by elsh** [comment]
@swift-ci smoke test

**Review by xymus — APPROVED** [review]
I like it, simple and to the point!

**Pull request merged**
