### PR TITLE
[IRGen] Do not hard code platform specific max extra inhabitant count

### PR DESCRIPTION
**Pull request by davezarzycki**

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by rjmccall** [comment]
I don't understand what you're trying to achieve here. 0x7FFF_FFFF is the maximum value of a 32-bit signed integer, not some platform-specific value.  The extra-inhabitant value witnesses use `int` as the extra-inhabitant index and use negative values to signal that something is not an extra inhabitant.  Are you planning to change something about that schema?

**Comment by davezarzycki** [comment]
No plans to change the schema. I should have said that this bug was filed based on a hunch ad I should have explained more of the debugging than assume that it would be obvious. Here we go:

WeakTypeInfo inherits its max extra inhabitant count from `FixedTypeInfo`, and `FixedTypeInfo` does not condition INT_MAX (a.k.a. 0x7FFF_FFFF) based on the platform, therefore it seems to me that non-objc platforms might end up with a weak having extra inhabitants that alias with valid pointers. :-(

**Comment by davezarzycki** [comment]
In trying to write a test case, I cannot find a path to WeakInfoType using 0x7FFF_FFFF on native platforms. I'm going to close this PR.

**Pull request closed without merging**
