### PR TITLE
[AST] NFC: Warn if ExtInfo "with*" API results are unused

### PR DESCRIPTION
**Pull request by davezarzycki**

### CODE REVIEW

**Comment by davezarzycki** [comment]
While learning to use the ExtInfo APIs, I was burned a couple times by the fact that the with* APIs are non-updating/non-mutating.

@swift-ci please smoke test

**Comment by davezarzycki** [comment]
Weird/random build failure on Linux. Let's try again:

@swift-ci please smoke test

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by shahmishal** [comment]
@swift-ci please clean smoke test Linux

**Comment by davezarzycki** [comment]
@swift-ci please clean smoke test linux

**Pull request merged**
