### PR TITLE
Constant fold array map

### PR DESCRIPTION
**Pull request by zoecarver**
This pull request adds limited constant folding for calls to `Array.map` where `Array` is an array literal. The optimization pass that I have added essentially checks to see if an array is created using literals. If so, it will remove the call to `.map` and call the closure (given to `.map`) with each of the elements supplied to the array when it was created. This makes it easy for the optimizer to inline and constant fold the calls to the closure. There is nothing done here that requires the array elements to be literals but, if they aren't literals, they won't be constant folded later so, this optimization doesn't make much sense. Additionally, it should be fairly easy to extend this optimization to other `Array` methods such as `compactMap` or `reduce`.

**This patch will need some work.** I had a few questions about the best way to do things and figured it would be better to put up a WIP patch here then ask on the forums. 

### TODO:
- [ ] Make this pass more robust. I suspect that as-is there will be a lot of code that will break this pass. 
- [ ] Use semantics everywhere I currently check `name.contains`.
- [ ] Move the helper functions I added.

### Questions:
- [ ] Is there any way to apply semantics to the closure that `.map` calls? Otherwise, I will have to do a fair bit of tree parsing which will be much more error-prone. 
- [ ] Do you think `8` is a good start-size for `SmallVector` in this case?
- [ ] Where should I put the helper functions (`getStructIfLiteral` and `getArrayLiteralElements`)?

At some point (probably not yet) I would be interested to see the benchmark deltas.

<details><summary>Input</summary>
<p>

```
func optimize_me_1() -> [Int] {
    let arr: [Int] = [1, 1, 1]
    return arr.map { $0 }
}

func optimize_me_2() -> [Int] {
   return [1, 1, 1].map { $0 }
}

func optimize_me_3() -> [Int] {
   return [0, 0, 0].map { $0 + 1 }
}

func optimize_me_4() -> [Int] {
   return [1, 1, 1]
}
```

</p>
</details>

<details><summary>Old output (570 lines)</summary>
<p>

```
_$s3run13optimize_me_1SaySiGyF:
	.cfi_startproc
	pushq	%rbp
	.cfi_def_cfa_offset 16
	.cfi_offset %rbp, -16
	movq	%rsp, %rbp
	.cfi_def_cfa_register %rbp
	pushq	%r15
	pushq	%r14
	pushq	%r13
	pushq	%rbx
	subq	$16, %rsp
	.cfi_offset %rbx, -48
	.cfi_offset %r13, -40
	.cfi_offset %r14, -32
	.cfi_offset %r15, -24
	movq	__swiftEmptyArrayStorage@GOTPCREL(%rip), %rbx
	movq	%rbx, -40(%rbp)
	movq	%rbx, %rdi
	callq	_swift_retain
	movq	%rbx, %rdi
	callq	_swift_isUniquelyReferenced_nonNull_native
	cmpq	$6, 24(%rbx)
	jb	LBB1_2
	testb	%al, %al
	jne	LBB1_3
LBB1_2:
	movq	__swiftEmptyArrayStorage@GOTPCREL(%rip), %r14
	movq	16(%r14), %rdi
	movl	$3, %esi
	callq	_$ss22_ContiguousArrayBufferV19_uninitializedCount15minimumCapacityAByxGSi_SitcfCSi_Tg5Tf4nnd_n
	movq	%rax, %rbx
	movq	16(%r14), %rdx
	leaq	32(%rax), %rdi
	shlq	$3, %rdx
	leaq	32(%r14), %rsi
	callq	_memcpy
	movq	%rbx, -40(%rbp)
	movq	%r14, %rdi
	callq	_swift_release
LBB1_3:
	movq	%rbx, %rdi
	callq	_swift_isUniquelyReferenced_nonNull_native
	testb	%al, %al
	je	LBB1_4
LBB1_5:
	movq	16(%rbx), %r14
	movq	24(%rbx), %rax
	leaq	1(%r14), %r15
	shrq	%rax
	cmpq	%r15, %rax
	jl	LBB1_6
LBB1_7:
	movq	%r15, 16(%rbx)
	movq	$1, 32(%rbx,%r14,8)
	movq	%rbx, %rdi
	callq	_swift_isUniquelyReferenced_nonNull_native
	testb	%al, %al
	je	LBB1_8
LBB1_9:
	movq	16(%rbx), %r14
	movq	24(%rbx), %rax
	leaq	1(%r14), %r15
	shrq	%rax
	cmpq	%r15, %rax
	jl	LBB1_10
LBB1_11:
	movq	%r15, 16(%rbx)
	movq	$1, 32(%rbx,%r14,8)
	movq	%rbx, %rdi
	callq	_swift_isUniquelyReferenced_nonNull_native
	testb	%al, %al
	je	LBB1_12
LBB1_13:
	movq	16(%rbx), %r14
	movq	24(%rbx), %rax
	leaq	1(%r14), %r15
	shrq	%rax
	cmpq	%r15, %rax
	jl	LBB1_14
LBB1_15:
	movq	%r15, 16(%rbx)
	movq	$1, 32(%rbx,%r14,8)
	movq	%rbx, %rax
	addq	$16, %rsp
	popq	%rbx
	popq	%r13
	popq	%r14
	popq	%r15
	popq	%rbp
	retq
LBB1_4:
	movq	16(%rbx), %rdi
	leaq	-40(%rbp), %r13
	callq	_$ss15ContiguousArrayV16_copyToNewBuffer8oldCountySi_tFSi_Tg5
	movq	-40(%rbp), %rbx
	jmp	LBB1_5
LBB1_6:
	leaq	-40(%rbp), %r13
	movq	%r14, %rdi
	callq	_$ss15ContiguousArrayV16_copyToNewBuffer8oldCountySi_tFSi_Tg5
	movq	-40(%rbp), %rbx
	jmp	LBB1_7
LBB1_8:
	movq	16(%rbx), %rdi
	leaq	-40(%rbp), %r13
	callq	_$ss15ContiguousArrayV16_copyToNewBuffer8oldCountySi_tFSi_Tg5
	movq	-40(%rbp), %rbx
	jmp	LBB1_9
LBB1_10:
	leaq	-40(%rbp), %r13
	movq	%r14, %rdi
	callq	_$ss15ContiguousArrayV16_copyToNewBuffer8oldCountySi_tFSi_Tg5
	movq	-40(%rbp), %rbx
	jmp	LBB1_11
LBB1_12:
	movq	16(%rbx), %rdi
	leaq	-40(%rbp), %r13
	callq	_$ss15ContiguousArrayV16_copyToNewBuffer8oldCountySi_tFSi_Tg5
	movq	-40(%rbp), %rbx
	jmp	LBB1_13
LBB1_14:
	leaq	-40(%rbp), %r13
	movq	%r14, %rdi
	callq	_$ss15ContiguousArrayV16_copyToNewBuffer8oldCountySi_tFSi_Tg5
	movq	-40(%rbp), %rbx
	jmp	LBB1_15
	.cfi_endproc

	.private_extern	_$s3run13optimize_me_4SaySiGyF
	.globl	_$s3run13optimize_me_4SaySiGyF
	.p2align	4, 0x90
_$s3run13optimize_me_4SaySiGyF:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	_$ss23_ContiguousArrayStorageCySiGML(%rip), %rdi
	testq	%rdi, %rdi
	jne	LBB2_3
	movq	_$sSiN@GOTPCREL(%rip), %rsi
	xorl	%edi, %edi
	callq	_$ss23_ContiguousArrayStorageCMa
	movq	%rax, %rdi
	testq	%rdx, %rdx
	jne	LBB2_3
	movq	%rdi, _$ss23_ContiguousArrayStorageCySiGML(%rip)
LBB2_3:
	leaq	_$s3run13optimize_me_4SaySiGyFTv_+8(%rip), %rsi
	callq	_swift_initStaticObject
	movq	%rax, %rdi
	popq	%rbp
	jmp	_swift_bridgeObjectRetain

	.private_extern	_$ss15ContiguousArrayV16_copyToNewBuffer8oldCountySi_tFSi_Tg5
	.globl	_$ss15ContiguousArrayV16_copyToNewBuffer8oldCountySi_tFSi_Tg5
	.weak_def_can_be_hidden	_$ss15ContiguousArrayV16_copyToNewBuffer8oldCountySi_tFSi_Tg5
	.p2align	4, 0x90
_$ss15ContiguousArrayV16_copyToNewBuffer8oldCountySi_tFSi_Tg5:
	.cfi_startproc
	pushq	%rbp
	.cfi_def_cfa_offset 16
	.cfi_offset %rbp, -16
	movq	%rsp, %rbp
	.cfi_def_cfa_register %rbp
	pushq	%r15
	pushq	%r14
	pushq	%rbx
	pushq	%rax
	.cfi_offset %rbx, -40
	.cfi_offset %r14, -32
	.cfi_offset %r15, -24
	movq	%rdi, %rbx
	incq	%rbx
	jo	LBB3_1
	movq	%rdi, %r14
	movq	(%r13), %r15
	movq	%r15, %rdi
	callq	_swift_retain
	movq	%r14, %rdi
	movq	%rbx, %rsi
	movq	%r15, %rdx
	callq	_$ss20_ArrayBufferProtocolPsE025_forceCreateUniqueMutableB0011countForNewB003minJ8Capacitys011_ContiguousaB0Vy7ElementQzGSi_SitFAGySiG_Tg5
	movq	%rax, %rbx
	movq	%r15, %rdi
	callq	_swift_release
	movq	%rbx, -32(%rbp)
	callq	_$ss20_ArrayBufferProtocolPsE22_arrayOutOfPlaceUpdateyys011_ContiguousaB0Vy7ElementQzGz_S2iySpyAGG_SitXEtFfA2_AEySiG_Tg5
	movq	%rdx, %rbx
	leaq	-32(%rbp), %rdi
	movq	%r14, %rsi
	xorl	%edx, %edx
	movq	%rax, %rcx
	movq	%rbx, %r8
	callq	_$ss20_ArrayBufferProtocolPsE22_arrayOutOfPlaceUpdateyys011_ContiguousaB0Vy7ElementQzGz_S2iySpyAGG_SitXEtFAEySiG_Tg5
	movq	%rbx, %rdi
	callq	_swift_release
	movq	-32(%rbp), %rdi
	addq	$8, %rsp
	popq	%rbx
	popq	%r14
	popq	%r15
	popq	%rbp
	jmp	_swift_release
LBB3_1:
	## InlineAsm Start
	## InlineAsm End
	ud2
	.cfi_endproc

	.private_extern	_$ss20_ArrayBufferProtocolPsE025_forceCreateUniqueMutableB0011countForNewB003minJ8Capacitys011_ContiguousaB0Vy7ElementQzGSi_SitFAGySiG_Tg5
	.globl	_$ss20_ArrayBufferProtocolPsE025_forceCreateUniqueMutableB0011countForNewB003minJ8Capacitys011_ContiguousaB0Vy7ElementQzGSi_SitFAGySiG_Tg5
	.weak_def_can_be_hidden	_$ss20_ArrayBufferProtocolPsE025_forceCreateUniqueMutableB0011countForNewB003minJ8Capacitys011_ContiguousaB0Vy7ElementQzGSi_SitFAGySiG_Tg5
	.p2align	4, 0x90
_$ss20_ArrayBufferProtocolPsE025_forceCreateUniqueMutableB0011countForNewB003minJ8Capacitys011_ContiguousaB0Vy7ElementQzGSi_SitFAGySiG_Tg5:
	.cfi_startproc
	pushq	%rbp
	.cfi_def_cfa_offset 16
	.cfi_offset %rbp, -16
	movq	%rsp, %rbp
	.cfi_def_cfa_register %rbp
	movq	%rdx, %rcx
	movq	%rsi, %rdx
	popq	%rbp
	jmp	_$ss20_ArrayBufferProtocolPsE025_forceCreateUniqueMutableB4Impl08countForB014minNewCapacity08requiredM0s011_ContiguousaB0Vy7ElementQzGSi_S2itFAHySiG_Tg5
	.cfi_endproc

	.private_extern	_$ss20_ArrayBufferProtocolPsE22_arrayOutOfPlaceUpdateyys011_ContiguousaB0Vy7ElementQzGz_S2iySpyAGG_SitXEtFfA2_AEySiG_Tg5
	.globl	_$ss20_ArrayBufferProtocolPsE22_arrayOutOfPlaceUpdateyys011_ContiguousaB0Vy7ElementQzGz_S2iySpyAGG_SitXEtFfA2_AEySiG_Tg5
	.weak_def_can_be_hidden	_$ss20_ArrayBufferProtocolPsE22_arrayOutOfPlaceUpdateyys011_ContiguousaB0Vy7ElementQzGz_S2iySpyAGG_SitXEtFfA2_AEySiG_Tg5
	.p2align	4, 0x90
_$ss20_ArrayBufferProtocolPsE22_arrayOutOfPlaceUpdateyys011_ContiguousaB0Vy7ElementQzGz_S2iySpyAGG_SitXEtFfA2_AEySiG_Tg5:
	.cfi_startproc
	pushq	%rbp
	.cfi_def_cfa_offset 16
	.cfi_offset %rbp, -16
	movq	%rsp, %rbp
	.cfi_def_cfa_register %rbp
	leaq	_$ss20_ArrayBufferProtocolPsE22_arrayOutOfPlaceUpdateyys011_ContiguousaB0Vy7ElementQzGz_S2iySpyAGG_SitXEtFfA2_yAI_SitcfU_AEySiG_Tg5(%rip), %rax
	xorl	%edx, %edx
	popq	%rbp
	retq
	.cfi_endproc

	.private_extern	_$ss20_ArrayBufferProtocolPsE22_arrayOutOfPlaceUpdateyys011_ContiguousaB0Vy7ElementQzGz_S2iySpyAGG_SitXEtFAEySiG_Tg5
	.globl	_$ss20_ArrayBufferProtocolPsE22_arrayOutOfPlaceUpdateyys011_ContiguousaB0Vy7ElementQzGz_S2iySpyAGG_SitXEtFAEySiG_Tg5
	.weak_def_can_be_hidden	_$ss20_ArrayBufferProtocolPsE22_arrayOutOfPlaceUpdateyys011_ContiguousaB0Vy7ElementQzGz_S2iySpyAGG_SitXEtFAEySiG_Tg5
	.p2align	4, 0x90
_$ss20_ArrayBufferProtocolPsE22_arrayOutOfPlaceUpdateyys011_ContiguousaB0Vy7ElementQzGz_S2iySpyAGG_SitXEtFAEySiG_Tg5:
	.cfi_startproc
	pushq	%rbp
	.cfi_def_cfa_offset 16
	.cfi_offset %rbp, -16
	movq	%rsp, %rbp
	.cfi_def_cfa_register %rbp
	pushq	%r15
	pushq	%r14
	pushq	%r13
	pushq	%r12
	pushq	%rbx
	subq	$72, %rsp
	.cfi_offset %rbx, -56
	.cfi_offset %r12, -48
	.cfi_offset %r13, -40
	.cfi_offset %r14, -32
	.cfi_offset %r15, -24
	movq	(%rdi), %r15
	movq	16(%r15), %rbx
	subq	%rsi, %rbx
	jo	LBB6_13
	subq	%rdx, %rbx
	jo	LBB6_14
	movq	%rsi, %r12
	movq	%r13, -96(%rbp)
	movq	(%r13), %r14
	movq	16(%r14), %r13
	movq	%r13, %rax
	subq	%rsi, %rax
	jo	LBB6_15
	movq	%r8, -64(%rbp)
	movq	%rcx, -72(%rbp)
	movq	%rdi, -112(%rbp)
	subq	%rbx, %rax
	jo	LBB6_16
	movq	%rax, -88(%rbp)
	leaq	32(%r15,%r12,8), %rax
	addq	$32, %r15
	movq	%rdx, -56(%rbp)
	movq	%rax, -48(%rbp)
	leaq	(%rax,%rdx,8), %rax
	movq	%rax, -80(%rbp)
	movq	%r14, %rdi
	callq	_swift_isUniquelyReferenced_nonNull_native
	testb	%al, %al
	je	LBB6_6
	movq	24(%r14), %rax
	shrq	%rax
	cmpq	%r13, %rax
	jb	LBB6_6
	leaq	32(%r14), %rsi
	leaq	32(%r14,%r12,8), %rax
	movq	%rax, -104(%rbp)
	shlq	$3, %r12
	movq	%r15, %rdi
	movq	%r12, %rdx
	callq	_memmove
	movq	%r14, %rdi
	callq	_swift_retain
	movq	-48(%rbp), %rdi
	movq	-56(%rbp), %rsi
	movq	-64(%rbp), %r13
	callq	*-72(%rbp)
	movq	-88(%rbp), %rax
	movq	-104(%rbp), %rcx
	leaq	(%rcx,%rax,8), %rsi
	shlq	$3, %rbx
	movq	-80(%rbp), %rdi
	movq	%rbx, %rdx
	callq	_memmove
	movq	$0, 16(%r14)
	movq	%r14, %rdi
	callq	_swift_release
	movq	-96(%rbp), %r14
	jmp	LBB6_12
LBB6_6:
	addq	$32, %r14
	leaq	(,%r12,8), %rdx
	movq	%r15, %rdi
	movq	%r14, %rsi
	callq	_memcpy
	movq	-48(%rbp), %rdi
	movq	-56(%rbp), %rsi
	movq	-64(%rbp), %r13
	callq	*-72(%rbp)
	movq	-88(%rbp), %rcx
	addq	%r12, %rcx
	jo	LBB6_17
	testq	%r12, %r12
	movq	-96(%rbp), %r14
	js	LBB6_18
	movq	(%r14), %rax
	movq	16(%rax), %rdx
	subq	%rcx, %rdx
	jl	LBB6_18
	jo	LBB6_19
	leaq	32(%rax,%rcx,8), %rsi
	shlq	$3, %rdx
	movq	-80(%rbp), %rdi
	callq	_memcpy
LBB6_12:
	movq	-112(%rbp), %rax
	movq	(%rax), %r15
	movq	%r14, %rbx
	movq	(%r14), %r14
	movq	%r15, %rdi
	callq	_swift_retain
	movq	%r14, %rdi
	callq	_swift_release
	movq	%r15, (%rbx)
	addq	$72, %rsp
	popq	%rbx
	popq	%r12
	popq	%r13
	popq	%r14
	popq	%r15
	popq	%rbp
	retq
LBB6_18:
	## InlineAsm Start
	## InlineAsm End
	ud2
LBB6_13:
	## InlineAsm Start
	## InlineAsm End
	ud2
LBB6_14:
	## InlineAsm Start
	## InlineAsm End
	ud2
LBB6_15:
	## InlineAsm Start
	## InlineAsm End
	ud2
LBB6_16:
	## InlineAsm Start
	## InlineAsm End
	ud2
LBB6_17:
	## InlineAsm Start
	## InlineAsm End
	ud2
LBB6_19:
	## InlineAsm Start
	## InlineAsm End
	ud2
	.cfi_endproc

	.private_extern	_$ss20_ArrayBufferProtocolPsE025_forceCreateUniqueMutableB4Impl08countForB014minNewCapacity08requiredM0s011_ContiguousaB0Vy7ElementQzGSi_S2itFAHySiG_Tg5
	.globl	_$ss20_ArrayBufferProtocolPsE025_forceCreateUniqueMutableB4Impl08countForB014minNewCapacity08requiredM0s011_ContiguousaB0Vy7ElementQzGSi_S2itFAHySiG_Tg5
	.weak_def_can_be_hidden	_$ss20_ArrayBufferProtocolPsE025_forceCreateUniqueMutableB4Impl08countForB014minNewCapacity08requiredM0s011_ContiguousaB0Vy7ElementQzGSi_S2itFAHySiG_Tg5
	.p2align	4, 0x90
_$ss20_ArrayBufferProtocolPsE025_forceCreateUniqueMutableB4Impl08countForB014minNewCapacity08requiredM0s011_ContiguousaB0Vy7ElementQzGSi_S2itFAHySiG_Tg5:
	.cfi_startproc
	pushq	%rbp
	.cfi_def_cfa_offset 16
	.cfi_offset %rbp, -16
	movq	%rsp, %rbp
	.cfi_def_cfa_register %rbp
	pushq	%r14
	pushq	%rbx
	.cfi_offset %rbx, -32
	.cfi_offset %r14, -24
	movq	%rdi, %r14
	movq	24(%rcx), %rbx
	shrq	%rbx
	cmpq	%rsi, %rbx
	jge	LBB7_2
	addq	%rbx, %rbx
	jo	LBB7_9
LBB7_2:
	cmpq	%rdx, %rbx
	cmovlq	%rdx, %rbx
	cmpq	%r14, %rbx
	cmovlq	%r14, %rbx
	testq	%rbx, %rbx
	je	LBB7_3
	movq	_$ss23_ContiguousArrayStorageCySiGML(%rip), %rdi
	testq	%rdi, %rdi
	jne	LBB7_7
	movq	_$sSiN@GOTPCREL(%rip), %rsi
	xorl	%edi, %edi
	callq	_$ss23_ContiguousArrayStorageCMa
	movq	%rax, %rdi
	testq	%rdx, %rdx
	jne	LBB7_7
	movq	%rdi, _$ss23_ContiguousArrayStorageCySiGML(%rip)
LBB7_7:
	leaq	32(,%rbx,8), %rsi
	movl	$7, %edx
	callq	_swift_allocObject
	movq	%rax, %rbx
	movq	%rax, %rdi
	callq	_malloc_size
	leaq	-32(%rax), %rcx
	sarq	$63, %rcx
	shrq	$61, %rcx
	leaq	-32(%rax,%rcx), %rax
	sarq	$3, %rax
	addq	%rax, %rax
	movq	%r14, 16(%rbx)
	movq	%rax, 24(%rbx)
	jmp	LBB7_8
LBB7_3:
	movq	__swiftEmptyArrayStorage@GOTPCREL(%rip), %rbx
	movq	%rbx, %rdi
	callq	_swift_retain
LBB7_8:
	movq	%rbx, %rax
	popq	%rbx
	popq	%r14
	popq	%rbp
	retq
LBB7_9:
	## InlineAsm Start
	## InlineAsm End
	ud2
	.cfi_endproc

	.private_extern	_$ss20_ArrayBufferProtocolPsE22_arrayOutOfPlaceUpdateyys011_ContiguousaB0Vy7ElementQzGz_S2iySpyAGG_SitXEtFfA2_yAI_SitcfU_AEySiG_Tg5
	.globl	_$ss20_ArrayBufferProtocolPsE22_arrayOutOfPlaceUpdateyys011_ContiguousaB0Vy7ElementQzGz_S2iySpyAGG_SitXEtFfA2_yAI_SitcfU_AEySiG_Tg5
	.weak_definition	_$ss20_ArrayBufferProtocolPsE22_arrayOutOfPlaceUpdateyys011_ContiguousaB0Vy7ElementQzGz_S2iySpyAGG_SitXEtFfA2_yAI_SitcfU_AEySiG_Tg5
	.p2align	4, 0x90
_$ss20_ArrayBufferProtocolPsE22_arrayOutOfPlaceUpdateyys011_ContiguousaB0Vy7ElementQzGz_S2iySpyAGG_SitXEtFfA2_yAI_SitcfU_AEySiG_Tg5:
	.cfi_startproc
	pushq	%rbp
	.cfi_def_cfa_offset 16
	.cfi_offset %rbp, -16
	movq	%rsp, %rbp
	.cfi_def_cfa_register %rbp
	popq	%rbp
	retq
	.cfi_endproc

	.private_extern	_$ss22_ContiguousArrayBufferV19_uninitializedCount15minimumCapacityAByxGSi_SitcfCSi_Tg5Tf4nnd_n
	.globl	_$ss22_ContiguousArrayBufferV19_uninitializedCount15minimumCapacityAByxGSi_SitcfCSi_Tg5Tf4nnd_n
	.weak_def_can_be_hidden	_$ss22_ContiguousArrayBufferV19_uninitializedCount15minimumCapacityAByxGSi_SitcfCSi_Tg5Tf4nnd_n
	.p2align	4, 0x90
_$ss22_ContiguousArrayBufferV19_uninitializedCount15minimumCapacityAByxGSi_SitcfCSi_Tg5Tf4nnd_n:
	.cfi_startproc
	pushq	%rbp
	.cfi_def_cfa_offset 16
	.cfi_offset %rbp, -16
	movq	%rsp, %rbp
	.cfi_def_cfa_register %rbp
	pushq	%r14
	pushq	%rbx
	.cfi_offset %rbx, -32
	.cfi_offset %r14, -24
	movq	%rsi, %rbx
	cmpq	%rdi, %rsi
	cmovlq	%rdi, %rbx
	testq	%rbx, %rbx
	je	LBB9_1
	movq	%rdi, %r14
	movq	_$ss23_ContiguousArrayStorageCySiGML(%rip), %rdi
	testq	%rdi, %rdi
	jne	LBB9_5
	movq	_$sSiN@GOTPCREL(%rip), %rsi
	xorl	%edi, %edi
	callq	_$ss23_ContiguousArrayStorageCMa
	movq	%rax, %rdi
	testq	%rdx, %rdx
	jne	LBB9_5
	movq	%rdi, _$ss23_ContiguousArrayStorageCySiGML(%rip)
LBB9_5:
	leaq	32(,%rbx,8), %rsi
	movl	$7, %edx
	callq	_swift_allocObject
	movq	%rax, %rbx
	movq	%rax, %rdi
	callq	_malloc_size
	leaq	-32(%rax), %rcx
	sarq	$63, %rcx
	shrq	$61, %rcx
	leaq	-32(%rax,%rcx), %rax
	sarq	$3, %rax
	addq	%rax, %rax
	movq	%r14, 16(%rbx)
	movq	%rax, 24(%rbx)
	jmp	LBB9_6
LBB9_1:
	movq	__swiftEmptyArrayStorage@GOTPCREL(%rip), %rbx
	movq	%rbx, %rdi
	callq	_swift_retain
LBB9_6:
	movq	%rbx, %rax
	popq	%rbx
	popq	%r14
	popq	%rbp
	retq
	.cfi_endproc

	.private_extern	_$s3run13optimize_me_2SaySiGyF
	.globl	_$s3run13optimize_me_2SaySiGyF
	.p2align	4, 0x90
_$s3run13optimize_me_2SaySiGyF:
	.cfi_startproc
	pushq	%rbp
	.cfi_def_cfa_offset 16
	.cfi_offset %rbp, -16
	movq	%rsp, %rbp
	.cfi_def_cfa_register %rbp
	popq	%rbp
	jmp	_$s3run13optimize_me_1SaySiGyF
	.cfi_endproc

	.private_extern	_$s3run13optimize_me_3SaySiGyF
	.globl	_$s3run13optimize_me_3SaySiGyF
	.p2align	4, 0x90
_$s3run13optimize_me_3SaySiGyF:
	.cfi_startproc
	pushq	%rbp
	.cfi_def_cfa_offset 16
	.cfi_offset %rbp, -16
	movq	%rsp, %rbp
	.cfi_def_cfa_register %rbp
	popq	%rbp
	jmp	_$s3run13optimize_me_1SaySiGyF
	.cfi_endproc

	.section	__DATA,__data
	.p2align	3
```
</p>
</details>

<details><summary>New output (175 lines)</summary>
<p>

```
_$s3run13optimize_me_1SaySiGyF:
	.cfi_startproc
	pushq	%rbp
	.cfi_def_cfa_offset 16
	.cfi_offset %rbp, -16
	movq	%rsp, %rbp
	.cfi_def_cfa_register %rbp
	leaq	_$s3run13optimize_me_1SaySiGyFTv_+8(%rip), %rdi
	popq	%rbp
	jmp	_$s3run13optimize_me_1SaySiGyFTm
	.cfi_endproc

	.private_extern	___swift_instantiateConcreteTypeFromMangledName
	.globl	___swift_instantiateConcreteTypeFromMangledName
	.weak_def_can_be_hidden	___swift_instantiateConcreteTypeFromMangledName
	.p2align	4, 0x90
___swift_instantiateConcreteTypeFromMangledName:
	movq	(%rdi), %rax
	testq	%rax, %rax
	js	LBB2_1
	retq
LBB2_1:
	pushq	%rbx
	movq	%rdi, %rbx
	movq	%rax, %rsi
	sarq	$32, %rsi
	negq	%rsi
	movslq	%eax, %rdi
	addq	%rbx, %rdi
	xorl	%edx, %edx
	xorl	%ecx, %ecx
	callq	_swift_getTypeByMangledNameInContext
	movq	%rax, (%rbx)
	popq	%rbx
	retq

	.private_extern	_$s3run13optimize_me_2SaySiGyF
	.globl	_$s3run13optimize_me_2SaySiGyF
	.p2align	4, 0x90
_$s3run13optimize_me_2SaySiGyF:
	.cfi_startproc
	pushq	%rbp
	.cfi_def_cfa_offset 16
	.cfi_offset %rbp, -16
	movq	%rsp, %rbp
	.cfi_def_cfa_register %rbp
	leaq	_$s3run13optimize_me_2SaySiGyFTv_+8(%rip), %rdi
	popq	%rbp
	jmp	_$s3run13optimize_me_1SaySiGyFTm
	.cfi_endproc

	.private_extern	_$s3run13optimize_me_3SaySiGyF
	.globl	_$s3run13optimize_me_3SaySiGyF
	.p2align	4, 0x90
_$s3run13optimize_me_3SaySiGyF:
	.cfi_startproc
	pushq	%rbp
	.cfi_def_cfa_offset 16
	.cfi_offset %rbp, -16
	movq	%rsp, %rbp
	.cfi_def_cfa_register %rbp
	leaq	_$s3run13optimize_me_3SaySiGyFTv_+8(%rip), %rdi
	popq	%rbp
	jmp	_$s3run13optimize_me_1SaySiGyFTm
	.cfi_endproc

	.p2align	4, 0x90
_$s3run13optimize_me_1SaySiGyFTm:
	.cfi_startproc
	pushq	%rbp
	.cfi_def_cfa_offset 16
	.cfi_offset %rbp, -16
	movq	%rsp, %rbp
	.cfi_def_cfa_register %rbp
	pushq	%r14
	pushq	%rbx
	.cfi_offset %rbx, -32
	.cfi_offset %r14, -24
	movq	%rdi, %rbx
	leaq	_$ss23_ContiguousArrayStorageCySiGMD(%rip), %rdi
	callq	___swift_instantiateConcreteTypeFromMangledName
	movq	%rax, %rdi
	movq	%rbx, %rsi
	callq	_swift_initStaticObject
	movq	%rax, %rbx
	xorl	%edi, %edi
	callq	_$ss28__ContiguousArrayStorageBaseCMa
	movq	%rax, %r14
	movq	%rbx, %rdi
	callq	_swift_retain
	movq	%r14, %rdi
	callq	__swift_objcClassUsesNativeSwiftReferenceCounting
	testb	$1, %al
	je	LBB5_2
	movq	%rbx, %rdi
	callq	_swift_release
	movq	%rbx, %rax
	popq	%rbx
	popq	%r14
	popq	%rbp
	retq
LBB5_2:
	subq	$8, %rsp
	leaq	L___unnamed_1(%rip), %rax
	leaq	L___unnamed_2(%rip), %rdi
	leaq	L___unnamed_3(%rip), %rcx
	movl	$11, %esi
	movl	$2, %edx
	movl	$0, %r8d
	movl	$2, %r9d
	pushq	$0
	pushq	$60
	pushq	$2
	pushq	$78
	pushq	%rax
	callq	_$ss18_fatalErrorMessage__4file4line5flagss5NeverOs12StaticStringV_A2HSus6UInt32VtF
	addq	$48, %rsp
	ud2
	.cfi_endproc

	.private_extern	_$s3run13optimize_me_4SaySiGyF
	.globl	_$s3run13optimize_me_4SaySiGyF
	.p2align	4, 0x90
_$s3run13optimize_me_4SaySiGyF:
	.cfi_startproc
	pushq	%rbp
	.cfi_def_cfa_offset 16
	.cfi_offset %rbp, -16
	movq	%rsp, %rbp
	.cfi_def_cfa_register %rbp
	pushq	%r14
	pushq	%rbx
	.cfi_offset %rbx, -32
	.cfi_offset %r14, -24
	leaq	_$ss23_ContiguousArrayStorageCySiGMD(%rip), %rdi
	callq	___swift_instantiateConcreteTypeFromMangledName
	leaq	_$s3run13optimize_me_4SaySiGyFTv_+8(%rip), %rsi
	movq	%rax, %rdi
	callq	_swift_initStaticObject
	movq	%rax, %r14
	xorl	%edi, %edi
	callq	_$ss28__ContiguousArrayStorageBaseCMa
	movq	%rax, %rbx
	movq	%r14, %rdi
	callq	_swift_retain
	movq	%rbx, %rdi
	callq	__swift_objcClassUsesNativeSwiftReferenceCounting
	testb	$1, %al
	je	LBB6_2
	movq	%r14, %rax
	popq	%rbx
	popq	%r14
	popq	%rbp
	retq
LBB6_2:
	subq	$8, %rsp
	leaq	L___unnamed_1(%rip), %rax
	leaq	L___unnamed_2(%rip), %rdi
	leaq	L___unnamed_3(%rip), %rcx
	movl	$11, %esi
	movl	$2, %edx
	movl	$0, %r8d
	movl	$2, %r9d
	pushq	$0
	pushq	$60
	pushq	$2
	pushq	$78
	pushq	%rax
	callq	_$ss18_fatalErrorMessage__4file4line5flagss5NeverOs12StaticStringV_A2HSus6UInt32VtF
	addq	$48, %rsp
	ud2
	.cfi_endproc

	.section	__DATA,__data
	.p2align	3
```

</p>
</details>

### CODE REVIEW

**Comment by harlanhaskins** [comment]
Awesome! Do you think integer range literals would be good candidates as well? (do we constant fold these?)

**Comment by zoecarver** [comment]
@harlanhaskins thanks! What do you mean? Range-based for loops (`for i in 0...3`)? We already constant fold the following (and similar):
```swift
func test() -> Bool {
    let arr = 0...3
    return arr.contains(0)
}
```
But, I don't think there is a special optimization for that. It is probably because we constant fold many (all?) struct literals.

**Review by eeckstein — COMMENTED** [review]
Do we really need this optimization?
Inlining of Array.map + loop unrolling should already do the job.

**Comment by zoecarver** [comment]
It doesn't seem to be doing the job (yet). 

I thought a bit more about this patch though, and I don't think this is actually the right way to do it. I think it would be better to either a) diagnose why loop unrolling isn't working or b) add a new array_literal` SIL instruction (this could be beneficial for lots of constant-folding optimizations). What do you think?

**Comment by eeckstein** [comment]
Well, it works with this simple code:
```
func testit(_ c: (Int) -> Int) -> [Int] {
  return [0, 1, 2].map(c)
}
```
We can tune the inlining and unroll heuristics to let it work for other examples, too.

**Comment by zoecarver** [comment]
Huh, good to know. I'll work on a patch to try to get it working for other examples (such as the one in this PR). Thanks for the example/info.

**Pull request closed without merging**
