### PR TITLE
[MoveAddrChecker] Look through mark_dependence to determine whether an address is initialized to begin with.

### PR DESCRIPTION
**Pull request by nate-chandler**
Extract the hack to determine whether an address starts out initialized into a separate function and then extend it to look through `mark_dependence` instructions.

Fixes a bug with nested accessors.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please test macos platform

**Review by atrick — APPROVED** [review]
LGTM

**Comment by nate-chandler** [comment]
@swift-ci please test windows platform

**Pull request merged**
