### PR TITLE
Fix benchmark suite on 32-bit platforms

### PR DESCRIPTION
**Pull request by lorentey**
- Fix integer overflow issues with iteration count
- Fix RandomIntegersLCG to use an integer type with a non-varying width

rdar://problem/41177686

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci please smoke test

**Comment by lorentey** [comment]
@swift-ci please smoke benchmark

**Review by natecook1000 — APPROVED** [review]
LGTM!

**Comment by gottesmm** [comment]
Same!

**Comment by lorentey** [comment]
@swift-ci please smoke test linux platform

**Comment by palimondo** [comment]
@lorentey @gottesmm @eeckstein I'm curious about the possibility of scale to overflow on 32-bit system this commit addresses. How are using the `--iter-scale` parameter in your internal tooling?

Looking at the code, I would have thought the only potential for overflow is on [line 395](https://github.com/lorentey/swift/blob/f7c4832bfe8050fa25adb5a25b02a78e3724e640/benchmark/utils/DriverUtils.swift#L395):
````swift
scale = UInt(time_per_sample / elapsed_time)
````
if the elapsed time is very low (worst case: 1 microsecond) it would take a manual setting of `iter-scale` to 4294 to overflow UInt32. Why would anyone want to run a single microbenchmark for 71 minutes?

I'm asking because I'm about to refactor the surrounding code and plant to replace all the exotic type selections (`UInt64`, `UInt`) with idiomatic Swift which uses simple platform dependent `Int`. I figure that the capacity for running a single micro-benchmark for 35 minutes on the 32-bit platforms is plenty enough, but I'd rather not overlook your internal use-case.

**Comment by lorentey** [comment]
There are some imperfect benchmarks in this suite that take effectively zero time, independent of the scale factor given to them. Most likely the 1 ... N loop gets optimized away entirely, and these benchmarks aren't measuring anything useful. So elapsed_time can be as low as a handful of nanoseconds.

However, the overflows I work around here happened in the benchmarks themselves, when they multiply the scaling factor with their own constants, which can be as high as 10,000 (or even 100,000 in places). Without the artificial limit I added, some benchmarks do try to run more than 2^31 iterations on 32-bit platforms (e.g., the i386 simulator).

**Comment by atrick** [comment]
There is nothing exotic about specifying the bitwidth of an integer. It's the appropriate thing to do in code that performs measurement and computation. Introducing platform specific behavior in the benchmark driver is not appropriate.

**Comment by palimondo** [comment]
@lorentey Oh I see: You're just putting an upper bound on the `i` passed down to each `runFunction`, so they don't overflow when computing the inner loop multiplier internally. Makes perfect sense. Thank you for the clarification!

@atrick I agree that it is important to be specific about integer width when it serves a concrete purpose. But Int-type choices in many parts of the benchmark driver are rather arbitrary and obfuscate more than clarify. Most of what I've seen so far would work safely with the capacity of `Int32` and would be therefore just fine with idiomatic plain old `Int`. When it comes to these modifications, I'll make sure to ask for your review. Thank you for the vigilance!

**Pull request merged**
