### PR TITLE
Updating docs with new CI triggers

### PR DESCRIPTION
**Pull request by etcwilde**
Adding docs for new toolchain CI triggers

### CODE REVIEW

**Comment by etcwilde** [comment]
@swift-ci please smoke test

**Comment by etcwilde** [comment]
Might be easier to review by looking at it in rendered form; https://github.com/etcwilde/swift/blob/ewilde/update-CI-docs/docs/ContinuousIntegration.md#build-swift-toolchain

**Comment by shahmishal** [comment]
There was small update missing, I applied to the PR.

**Comment by shahmishal** [comment]
Thanks @etcwilde for updating the Docs, soon I will also add support for AArch64.

**Pull request merged**
