### PR TITLE
Bump `wasi-libc` to `wasi-sdk-22` in `update-checkout-config.json`

### PR DESCRIPTION
**Pull request by MaxDesiatov**
Latest version has `PF_INET` and `PF_INET6` available, which makes porting SwiftNIO to WASI easier.

rdar://133045292

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci test webassembly

**Comment by kateinoigakukun** [comment]
Ok, I reviewed [all the diff between 20 and 22](https://github.com/WebAssembly/wasi-libc/compare/wasi-sdk-20...wasi-sdk-22). It now requires LLVM 15.0.7, especially this change (https://reviews.llvm.org/D136110) but I confirmed our LLVM includes the required changes.

**Review by kateinoigakukun — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci build toolchain

**Pull request merged**
