### PR TITLE
[Macros/ASTGen] Fix deprecation warnings from SwiftSyntax

### PR DESCRIPTION
**Pull request by ahoppen**
Also use the opportunity to make some implementation improvements in `syntax_macro_definitions.swift`.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Review by bnbarham — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please smoke test macOS

**Comment by ahoppen** [comment]
@swift-ci Please smoke test Linux

**Comment by ahoppen** [comment]
@swift-ci Please smoke test Linux

**Comment by ahoppen** [comment]
@swift-ci Please smoke test Linux

**Comment by ahoppen** [comment]
@swift-ci Please smoke test macOS

**Comment by ahoppen** [comment]
@swift-ci Please smoke test macOS

**Pull request merged**
