### PR TITLE
[cxx-interop][IRGen] Assign Clang function types to copy constructors

### PR DESCRIPTION
**Pull request by egorzhdan**
This fixes an assertion failure when building certain projects for arm64e with `-use-clang-function-types` Swift compiler flag:
```
Expected non-null Clang type for @convention(c)/@convention(block) function but found nullptr
```

rdar://121227452

### CODE REVIEW

**Comment by egorzhdan** [comment]
Not sure about the right way to test this, let me think for a bit

**Comment by egorzhdan** [comment]
@swift-ci please test

**Review by hyp — APPROVED** [review]
Any tests tho?

**Comment by egorzhdan** [comment]
@swift-ci please test

**Review by kubamracek — APPROVED** [review]

**Comment by egorzhdan** [comment]
@swift-ci please test

**Review by aschwaighofer — APPROVED** [review]
LGTM

Thank you

**Pull request merged**
