### PR TITLE
Update SE-0054: Rework diagnostics for IUOs and revise Swift 3 /4 semantics

### PR DESCRIPTION
**Pull request by ematejska**
Update https://github.com/apple/swift/pull/12849 to resolve test file conflicts.

### CODE REVIEW

**Comment by ematejska** [comment]
@swift-ci please test

**Comment by ematejska** [comment]
@swift-ci please smoke test

**Comment by ematejska** [comment]
@swift-ci please test source compatiblity

**Comment by ematejska** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
@ematejska Ah, I hadn't seen you were working on resolving the conflicts so I just went ahead and did so as well!

**Comment by ematejska** [comment]
@rudkx, awesome, let's continue yours then since you've resolved the conflicts there already as well and it's mergeable.  Closing this one.

**Pull request closed without merging**
