### PR TITLE
[test] Adjust new Substring test

### PR DESCRIPTION
**Pull request by lorentey**
This fixes the new Substring test that checks for the behavioral change introduced in #29094/#29146.

We don't have a good way to test exactly what version of the stdlib we're running on, so it isn't feasible to write two-way tests for behavior that is expected to change between stdlib versions. The `if #available(9999)` checks we have now *will* fail when we run these tests on a future released version of the stdlib that includes these changes. Even worse, the expected behavior on older stdlibs depends on whether the method is called in a Sequence-generic context. (The implementation is marked `@_alwaysEmitIntoClient`, so client code that directly calls it will have the new behavior; however, the Sequence witness table for Substring will still point to the default implementation in old stdlibs.)

Therefore, if the availability test fails, we cannot tell which behavior we need to expect, so we must stop checking for it. 

On the other hand, if the availability check succeeds, then we are guaranteed to have a new stdlib -- so we need to look at the expected behavior in that case, and only that case.

rdar://58868606

### CODE REVIEW

**Comment by lorentey** [comment]
Cc @Lukasa

**Comment by lorentey** [comment]
@swift-ci test

**Review by Lukasa — APPROVED** [review]
Thanks for this @lorentey, this looks like it preserves the test intent but fixes the issues.

**Review by milseman — APPROVED** [review]
LGTM

**Pull request merged**
