### PR TITLE
[stdlib] Add tests for all of the SetAlgebra methods on Set

### PR DESCRIPTION
**Pull request by lancep**
This adds tests to cover all the methods on SetAlgebra that Set implements.

<rdar://problem/21067949>

### CODE REVIEW

**Comment by lancep** [comment]
@swift-ci please smoke test

**Review by milseman — APPROVED** [review]
LGTM

**Comment by lancep** [comment]
@swift-ci please smoke test and merge

**Comment by lancep** [comment]
@swift-ci please smoke test

**Comment by lancep** [comment]
@swift-ci please smoke test linux platform

**Comment by dabrahams** [comment]
All these tests should be factored out into a generic test that checks the SetAlgebra conformance of its argument (if such a thing does not already exist in StdlibCollectionUnittests), and that can be applied to OptionSet as well.  StdlibCollectionUnittests already contains similar facilities for testing conformance to other protocols such as BidirectionalCollection.

**Pull request merged**
