### PR TITLE
[DO NOT MERGE]Add the ability to assert that an array won't be COWed

### PR DESCRIPTION
**Pull request by lancep**
This just a benchmark PR, if we end up doing this we'd need a SE proposal

### CODE REVIEW

**Comment by lancep** [comment]
@swift-ci please benchmark

**Comment by lancep** [comment]
CC @airspeedswift

**Comment by lancep** [comment]
@swift-ci please test

**Comment by lancep** [comment]
@swift-ci please smoke benchmark staging

**Comment by lancep** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
TEST                          | OLD  | NEW  | DELTA  | SPEEDUP 
---                           | ---  | ---  | ---    | ---     
**Improvement**               |      |      |        |         
MapReduceLazyCollectionShort  | 85   | 41   | -51.8% | **2.07x** 

LOL

**Comment by shahmishal** [comment]
@swift-ci test Linux

**Comment by lancep** [comment]
@swift-ci test Linux

**Pull request closed without merging**
