### PR TITLE
[Distributed] ID synthesis must be eager, or we run into issues in real projects

### PR DESCRIPTION
**Pull request by ktoso**
Without this, in real, multi module, multi file, projects we end up with issues as follows:

```
Greeter.swift:9:19: error: type 'Greeter' does not conform to protocol 'DistributedActor'
distributed actor Greeter {
                  ^
Greeter.swift:9:19: error: 'DistributedActor' requires the types 'ObjectIdentifier' and 'BonjourActorSystem.ActorID' (aka 'ActorIdentity') be equivalent
distributed actor Greeter {
                  ^
Greeter.swift:9:19: note: requirement specified as 'Self.ID' == 'Self.ActorSystem.ActorID' [with Self = Greeter]
distributed actor Greeter {
                  ^
Greeter.swift:9:19: error: protocol 'DistributedActor' is broken; cannot derive conformance for type 'Greeter'
distributed actor Greeter {
                  ^
```

From debugging it seems that the reason is that the resolve by lookup triggers early and determines that the `ID` shall be taken from the `extension Identifiable { var id: ObjectIdentifier {...} }` and only then other synthesis is run.

In order to avoid such mixups, we can be eager about the ID type synthesis.

This is limited to `distributed actor` decls, because in all other cases the default would be right and follow the usual rules, but because we synthesize the `ActorSystem` typealias and `ID` types later on, things got tricky here.

If there is a cleaner way to do this I'd happily revisit but this seems not to terrible for now at least and unbreaks projects.

Resolves rdar://91020060

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Review by xedin — APPROVED** [review]
Makes sense to me! Could you please add a couple more test cases with protocol that conform to a `DistributedActor` to make sure that fetching of the ActorSystem and other bits work correctly for that case too?

**Comment by ktoso** [comment]
Good idea, I actually don't do synthesis there but I guess I should maybe? Will think about it, thanks!

**Comment by ktoso** [comment]
@swift-ci please smoke test and merge

**Comment by ktoso** [comment]
Poked around a bit but protocols should not be impacted at all 👍

**Comment by xedin** [comment]
Sounds good!

**Comment by ktoso** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
