### PR TITLE
build: support excluding libraries from target sdks

### PR DESCRIPTION
**Pull request by compnerd**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

This adds the ability to have an inverse of the `TARGET_SDKS` option.  This is
useful for excluding some of the SDK libraries from various SDKs (primarily
meant to support Windows when cross-compiling the stdlib).

### CODE REVIEW

**Comment by compnerd** [comment]
CC @gribozavr 

Just for a bit of context: this significantly simplifies the handling for a few libraries that cannot be compiled for windows (pthreads, pthread tests, and temporarily, the collection unit tests).

**Comment by gribozavr** [comment]
Sorry, I'd rather not have two options for the same purpose.  I also think that negative options usually lead to tangled, hard to understand code.  (As we can see with `--skip-*` options in build-script, I think that was a mistake.)

**Comment by compnerd** [comment]
@gribozavr two options?  so, you think its better to explicitly at the individual libraries do a list remove item and pass that to TARGET_SDKS?  Just want to make sure that I understand your suggestion properly :-).

**Comment by gribozavr** [comment]
I think having an explicit list being passed to TARGET_SDKS would be better.  When/if that becomes intolerable, we can look into adding some shortcuts, but I still think they should be inclusive, not exclusive:

```CMake
TARGET_SDKS ALL_APPLE_PLATFORMS LINUX # only Apple platforms and Linux
TARGET_SDKS ALL_POSIX_PLATFORMS # Apple platforms, Linux, FreeBSD, but not Windows
# etc
```

**Comment by compnerd** [comment]
@gribozavr woah, thats very different from what I understood you meant.  Okay, with the new aliases, `ALL_POSIX_PLATFORMS` and `ALL_APPLE_PLATFORMS`, I think that this works just as well.

**Comment by compnerd** [comment]
Im going to do a separate PR for the aliases.  Thanks for the suggestion, its actually better than this approach.

**Pull request closed without merging**
