### PR TITLE
[CSBindings] Refactor literal protocol requirement handling

### PR DESCRIPTION
**Pull request by xedin**
These changes refactor literal protocol requirement handling in `PotentialBindings`
to be more incremental. Each literal requirement would now record meta-information
about itself (whether it's a direct or transitive requirement, is it covered by an existing binding,
what is its "source" constraint).

Also instead of checking coverage post-factum, during finalization step, that information
is inferred once new bindings and literal requirements are added to the set.

Uncovered defaultable requirements are transformed into bindings only when type variable
is picked for attempting.

Resolves: SR-10757
Resolves: rdar://problem/72770327

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test source compatibility debug

**Comment by xedin** [comment]
@swift-ci please smoke test compiler performance

**Review by MinKhent88 — APPROVED** [review]
Myanmar Buma

**Comment by xedin** [comment]
@swift-ci please smoke test compiler performance

**Comment by xedin** [comment]
Increase in `NumSourceLinesPerSecond` is considered a regression apparently :)

**Comment by xedin** [comment]
@swift-ci please test compiler performance

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@swift-ci please clean test macOS platform

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test source compatibility release

**Comment by xedin** [comment]
Looks like this would have to wait a bit, CI isn't feeling well after the holidays :)

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@swift-ci please clean test macOS platform

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test source compatibility release

**Review by hborla — APPROVED** [review]

**Pull request merged**
