### PR TITLE
Stdlib: Fix ReversedIndex compatibility alias

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
@airspeedswift

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please test and merge

**Review by airspeedswift — APPROVED** [review]

**Comment by AnthonyLatsis** [comment]
Should I cherry-pick this for 5.1?

**Comment by AnthonyLatsis** [comment]
`Swift(iphonesimulator-x86_64) :: Interpreter/objc_class_resilience_stubs.swift` failed, but I can't find that test in my build. Is this related to the change?

**Comment by airspeedswift** [comment]
Looks like it only just got added, I needed to pull to see it on mine.

**Comment by AnthonyLatsis** [comment]
@airspeedswift I built the stdlib for ios simulators using `--skip-build-ios-simulator false` in an attempt to run the test and see what's wrong but the tests remain unresolved. I am able to run them for `macosx-x86-64` just fine. The command is `./lit.py -sv --filter objc_class /Volumes/Elements/swift-source/build/Ninja-RelWithDebInfoAssert+swift-DebugAssert/swift-macosx-x86_64/test-iphonesimulator-x86_64/Interpreter`. This is the first time I try to run tests for something other than `macosx-x86-64`. What am I doing wrong?

**Comment by xwu** [comment]
Think we could fix the `renamed` copypasta [here](https://github.com/apple/swift/pull/24186/files#diff-b63730d3a7a5458d2cbc71695493546aR66) and [here](https://github.com/apple/swift/pull/24186/files#diff-b63730d3a7a5458d2cbc71695493546aR68) while we're at it?

**Comment by AnthonyLatsis** [comment]
@airspeedswift Can we try again? I am not able to reproduce the test failure using the preset from the bot.

**Comment by xwu** [comment]
@swift-ci please test

**Comment by AnthonyLatsis** [comment]
Thanks, Xiaodi!

**Pull request merged**
