### PR TITLE
[Sema] NFC: Move TypeChecker.h to include/swift/Sema

### PR DESCRIPTION
**Pull request by xedin**
In an effect to make Sema unit-testable, let's start by moving
`TypeChecker.h` to `include/swift/Sema` so it come be referenced
outside of `lib/Sema`.

### CODE REVIEW

**Comment by xedin** [comment]
Working towards getting constraint system related headers into `include/swift/Sema` so I can write some unit tests for binding inference and other things...

**Comment by xedin** [comment]
@swift-ci please clean test

**Comment by CodaFi** [comment]
I would really prefer we make a new header here. We've been trying for so long to eliminate `TypeChecker.h` altogether by farming its responsibilities out to real components.

**Comment by xedin** [comment]
@CodaFi I think we could do that separately right? I'm really working towards moving `ConstraintSystem.h` and related headers over to `include/swift/Sema`, this was just something I had to do to get there...

**Comment by CodaFi** [comment]
Can `ConstraintSystem.h` absorb the relevant parts of `TypeChecker.h`?

**Comment by xedin** [comment]
@CodaFi I'll look into doing that and going to keep this PR open for now.

**Comment by xedin** [comment]
Looks like I'd need to move both `typeCheckExpression` variants over to constraint system header together with `ContextualTypePurpose` and doesn't seem to be any other dependencies here expect that `ConstraintSystem.h` doesn't include everything it uses so I'd need to untangle that mess :/

**Pull request closed without merging**
