### PR TITLE
Remove build-script-impl target calculation

### PR DESCRIPTION
**Pull request by porglezomp**
This removes some code that was duplicated between `build-script` and `build-script-impl`. It was duplicated between these for migration purposes, but isn't needed for that purpose anymore.

### CODE REVIEW

**Review by Rostepher — APPROVED** [review]

**Comment by Rostepher** [comment]
Assuming this passes testing I'm all for getting rid of this cruft.

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by harlanhaskins** [comment]
@swift-ci please test Linux

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
Seems that IndexStoreDB is unhappy:

```
11:45:33 
/home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-master/indexstore-db/Tests/ISDBTibsTests/TibsBuildTests.swift:97: error: TibsBuildTests.testBuildMixedLang : XCTAssertEqual failed: ("["\'/home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-master/tmp/TibsBuildTests.testBuildMixedLang/src/b.c\'", "\'/home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-master/tmp/TibsBuildTests.testBuildMixedLang/src/e.mm\'", "\'/home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-master/tmp/TibsBuildTests.testBuildMixedLang/src/c.m\'", "\'/home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-master/tmp/TibsBuildTests.testBuildMixedLang/src/d.cpp\'", "Swift Module main"]") is not equal to ("["/home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-master/tmp/TibsBuildTests.testBuildMixedLang/src/c.m", "/home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-master/tmp/TibsBuildTests.testBuildMixedLang/src/d.cpp", "/home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-master/tmp/TibsBuildTests.testBuildMixedLang/src/b.c", "/home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-master/tmp/TibsBuildTests.testBuildMixedLang/src/e.mm", "Swift Module main"]") - 
```

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Pull request merged**
