### PR TITLE
[Tests] Fix RemoteMirror test to work when DYLD_LIBRARY_PATH is set.

### PR DESCRIPTION
**Pull request by al45tair**
Changed the RemoteMirror test to work around `DYLD_LIBRARY_PATH` when it's given an absolute path; when it's called from CI, we really want it to load the `libswiftRemoteMirror.dylib` that we just built, *not* the system one, which is what happens for some of the builders.

rdar://82124292

### CODE REVIEW

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
@swift-ci Please test Windows platform

**Comment by al45tair** [comment]
@swift-ci Please smoke test Windows platform

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Review by mikeash — APPROVED** [review]

**Pull request merged**
