### PR TITLE
[Gardening] Extract basic source info structs from RawComment.h

### PR DESCRIPTION
**Pull request by bnbarham**
NFC - move the Basic* structs out of RawComment into their own file. Had to fix up a bunch of other headers after cleaning up the imports in RawComment.h (namely removing SourceManager.h).

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
@swift-ci please test

**Review by rintaro — APPROVED** [review]

**Comment by bnbarham** [comment]
@swift-ci please smoke test

**Comment by bnbarham** [comment]
@swift-ci please smoke test

**Pull request merged**
