### PR TITLE
[5.3] Support cross compile Xcode toolchain for Apple Silicon

### PR DESCRIPTION
**Pull request by shahmishal**
(cherry picked from commit bf7c03b1f6cce062e27684abe5018a723a594662)

Master PR - https://github.com/apple/swift/pull/33490

### CODE REVIEW

**Comment by shahmishal** [comment]
https://github.com/apple/swift-package-manager/pull/2904
https://github.com/apple/swift-llbuild/pull/697

@swift-ci build toolchain

**Review by edymtt — APPROVED** [review]

**Comment by shahmishal** [comment]
apple/swift-llbuild#697

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#697

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#697

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#697

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#697

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#697

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#697

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#697

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#697

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#697

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#697

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#697

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#697

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#697

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#697

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#697

@swift-ci build toolchain macOS

**Review by dcci — APPROVED** [review]

**Comment by shahmishal** [comment]
apple/swift-llbuild#697

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#697

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#697

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#697

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#697

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#697

@swift-ci build toolchain Linux

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#697

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#697

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-llbuild#697

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
https://github.com/apple/swift-package-manager/pull/2917
apple/swift-llbuild#697

@swift-ci build toolchain macOS

**Comment by shahmishal** [comment]
apple/swift-package-manager#2917
apple/swift-llbuild#697

@swift-ci build toolchain macOS

**Review by tkremenek — APPROVED** [review]

**Pull request merged**
