### PR TITLE
ARCSequenceOpts: fix a wrong handling of applies with indirect out arguments

### PR DESCRIPTION
**Pull request by eeckstein**
Fixes a miscompile

https://github.com/apple/swift/issues/64921
rdar://109920867

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Comment by tomerd** [comment]
cc @weissi

**Review by atrick — APPROVED** [review]
LGTM

**Pull request merged**
