### PR TITLE
[Changelog] Add entries for more resolved issues in Swift 5.1

### PR DESCRIPTION
**Pull request by theblixguy**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test and merge

**Comment by slavapestov** [comment]
Thank you!

**Comment by theblixguy** [comment]
Unrelated OSX test failure: "/Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/IRGen/Output/class_resilience.swift.tmp/class_resilience.swift:95:16: error: CHECK-SAME: is not on the same line as the previous match"

@slavapestov can you kick off another test & merge or simply merge this without it? Thank you!

**Comment by slavapestov** [comment]
@theblixguy yeah, I think that might be related to some ABI-related work we landed together with stale CMake cache artifacts.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Comment by theblixguy** [comment]
@slavapestov Ah ok! Seems like the test has passed now!

**Pull request merged**
