### PR TITLE
[5.3][CodeCompletion] Give up fast-completion if dependent files are modified

### PR DESCRIPTION
**Pull request by rintaro**
- **Explanation**:  Fix a regression caused by fast-completion mode. Fast completion mode could not detect the modification in dependent files such as imported module file, header files in clang modules. Fix the problem by adding some logic to check if the decencies are modified
- **Scope**: Code completion inside function bodies or single file scripts
- **Risk**: Low-Mid. Increase chances to invalidate fast-completion. But the changes are closed in code completion, it should not affect other parts.
- **Issue**: rdar://problem/62336432
- **Testing**: Added regression test cases to check modifications are correctly propagated.
- **Reviewer**: Ben Langmuir (@benlangmuir )

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please test

**Review by akyrtzi — APPROVED** [review]

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by rintaro** [comment]
@swift-ci Please nominate

**Comment by rintaro** [comment]
@swift-ci Please nominate

**Pull request merged**
