### PR TITLE
build: do not modify user variables

### PR DESCRIPTION
**Pull request by compnerd**
`CMAKE_CXX_FLAGS` are not meant to be modified by the build system. If the build wishes to force certain flags, it should use the `add_compile_options` and `add_compile_definitions` (or preferably the target variants). This cleans up the handling in the shared configuration.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @etcwilde

**Comment by compnerd** [comment]
@swift-ci please test

**Review by etcwilde — APPROVED** [review]

**Comment by rintaro** [comment]
Changing `-Wno-nested-anon-types` to `-Wnested-anon-types` is causing tons of warnings. I guess it was not intentional?

**Comment by rintaro** [comment]
https://github.com/apple/swift/pull/70793

**Pull request merged**
