### PR TITLE
[gardening][AST] Remove unused DefaultValueExpr type

### PR DESCRIPTION
**Pull request by rintaro**
The last instantiation of this type was removed in 68bcb0d2af75e66a3666fae3a23d29d74647e983
I believe this is NFC.

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by DougGregor** [comment]
Huh, we're not using this because `TupleShuffleExpr` (weirdly) encodes caller-provided default arguments in its array. If at some point we fix that, we might bring `DefaultValueExpr` back... but it's better to delete it for now. Thanks!

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@DougGregor Thank you for the comment!
merging.

**Pull request merged**
