### PR TITLE
Allow parsing of function types in expr position

### PR DESCRIPTION
**Pull request by cwillmor**
#### What's in this pull request?

This pull request resolves SR-502 by adding the ability to parse expressions that contain function types, such as `[Int -> Int]()`. It does so by adding a new `Expr` type, `ArrowExpr`.
#### Resolved bug number: ([SR-502](https://bugs.swift.org/browse/SR-502))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

Previously it was not possible to parse expressions of the form

```
[Int -> Int]()
```

because no Expr could represent the '->' token and be converted later
into a FunctionTypeRepr. This commit introduces ArrowExpr which exists
solely to be converted to FunctionTypeRepr later by simplifyTypeExpr.

https://bugs.swift.org/browse/SR-502

### CODE REVIEW

**Comment by cwillmor** [comment]
@swift-ci please test

**Comment by cwillmor** [comment]
Looks like `[() -> Int]()` doesn't parse correctly; `simplifyTypeExpr` doesn't convert an empty `TupleExpr` to an empty `TupleTypeRepr`.

**Comment by cwillmor** [comment]
@swift-ci please test

**Comment by cwillmor** [comment]
@DougGregor, would you mind sanity-checking this change?

**Comment by jrose-apple** [comment]
Clever! Can you add an ASTVerifier check that no ArrowExprs survive past successful type-checking, and some tests for ArrowExprs that *won't* get turned into types?

**Comment by cwillmor** [comment]
@jrose-apple The `ArrowExpr` AST node is declared in ExprNodes.def with `UNCHECKED_EXPR`, so `ASTVerifier` will complain if an `ArrowExpr` makes it past type-checking.

What sort of tests did you have in mind? I've got it checking cases where either side of `->` cannot be interpreted as a type, e.g. `1 -> Int`…

**Comment by jrose-apple** [comment]
I'm more thinking about cases where the syntax is valid, but it's not in a TypeExpr position.

```swift
let a = Int -> Int
2 + () -> Int
() -> (Int, Int).2
```

(And, whoops, of course.)

**Pull request merged**
