### PR TITLE
[6.0] Add cross-compiling support for the windows toolchain

### PR DESCRIPTION
**Pull request by shahmishal**
Co-authrored with @compnerd

(cherry picked from commit f6ab729ffd8767373e291f035792db2600ebb1c8)

**Explanation**: Bring cross-compiling support for Windows arm64 to release/6.0 branch
**Scope**: Update the utils/build.ps1 script to include changes required to cross compile for arm64.
**Original PRs**: https://github.com/apple/swift/pull/71584, https://github.com/apple/swift/pull/73058, https://github.com/apple/swift/pull/73494, https://github.com/apple/swift/pull/73733
**Risk**: Low 
**Testing**: Verify the Windows toolchain for arm64 builds
**Reviewer**: @compnerd

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test windows

**Comment by shahmishal** [comment]
@swift-ci test macOS

**Comment by shahmishal** [comment]
@swift-ci test Linux

**Comment by shahmishal** [comment]
git log --oneline --no-merges origin/release/6.0..origin/main -- utils/build.ps1 

Need to cherry-pick following commits to enable arm64 support on Windows for release/6.0 branch: 
- eb6cd285daa Update utils/build.ps1
- 5440760612b utils: tweak the path before using a Swift toolchain
- 421c0cf890d utils: use cmark gfm for the build when running the compiler

@compnerd Do we need any of the following commits in release/6.0 and to support arm64? 
- 4222205f17d utils: do not install testable corelibs builds
- b7461456711 utils: enable curl websockets support when building with `build.ps1`
- 94c10c2a612 [Build] Pass in swift-syntax to SwiftPM
- 45f5cff9937 Remove unnecessary /usr/include/CSystem directory to avoid build errors
- 1bc7232d3b0 utils: build `makeOption` when building with `build.ps1`

@rintaro Should we pull this into release/6.0?
- 1a06b94a730 [Windows] Build SwiftCompilerPlugin module when testing swift


Both of these commits were made due to Android support: 
- dd5d6fac6e3 utils: update curl to 8.5.0
- 9944af3b8d1 update_checkout: update zlib to 1.3.1

**Comment by shahmishal** [comment]
@swift-ci test

**Review by compnerd — APPROVED** [review]

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
