### PR TITLE
Re-apply "SIL: Remove special meaning for @_semantics("stdlib_binary_…

### PR DESCRIPTION
**Pull request by slavapestov**
…only")"

With -sil-serialize-all gone, this no longer means anything; just
don't declare the function as @_inlineable instead.

Fixes <rdar://problem/34564380>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
This broke stuff before. A smoke test is not sufficient.

@swift-ci Please clean test

**Comment by jrose-apple** [comment]
(he says, wearing his build czar hat)

**Comment by jrose-apple** [comment]
And I've confirmed locally that the revert fixes things.

**Comment by slavapestov** [comment]
Can you send me a failing build log? PR testing doesn't build StdlibUnittest with -sil-serialize-all, only some presets do that. It was put in place originally to improve optimizer test coverage by a bit, but it blows up build time. I don't think we're losing much by removing that.

**Comment by jrose-apple** [comment]
https://ci.swift.org/job/oss-swift_tools-RA_stdlib-RD_test-simulator/177/

**Comment by jrose-apple** [comment]
If the stdlib and perf teams are okay with the loss of coverage then we're fine, but please hold off on removing stdlib_binary_only until -sil-serialize-all is actually gone (Roman's patch).

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
This has been merged into https://github.com/apple/swift/pull/12256, closing

**Pull request closed without merging**
