### PR TITLE
Merge tensorflow-merge (2020-03-19) into tensorflow

### PR DESCRIPTION
**Pull request by dan-zheng**
Merge https://github.com/apple/swift/commit/0a318a39f14bdcdf46bb9d56e4d539665b7e21f5 into `tensorflow`.

Update `utils/update_checkout/update-checkout-config.json` to `swift-DEVELOPMENT-SNAPSHOT-2020-03-03-a`. It's the closest working release tag.

### CODE REVIEW

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by compnerd** [comment]
Please test with following PRs:
apple/llvm-project#937

@swift-ci please test tensorflow

**Comment by compnerd** [comment]
Please test with following PRs:
apple/llvm-project#937

@swift-ci please test tensorflow

**Comment by compnerd** [comment]
Please test with following PRs:
apple/llvm-project#937

@swift-ci please clean test tensorflow

**Comment by compnerd** [comment]
@swift-ci please test tensorflow

**Comment by compnerd** [comment]
@swift-ci please clean test tensorflow

**Pull request merged**
