### PR TITLE
[String] ASCII fast-path for UTF16View

### PR DESCRIPTION
**Pull request by milseman**
Add an isASCII fast-path for many UTF16View operations. These are
heavily utilized in random-access scenarios, allowing us to both be
more efficient and skip generating breadcrumbs for ASCII strings.

### CODE REVIEW

**Review by Catfish-Man — APPROVED** [review]
This looks great. I probably mid-air collided part of it with the PR I just landed though; sorry!

**Comment by gottesmm** [comment]
Nice!

**Comment by milseman** [comment]
That's fine, I'll roll in the (less important but still a nice 30%) ASCII fast-path in `_nativeCopyUTF16CodeUnits` too.

**Comment by milseman** [comment]
@swift-ci please benchmark

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please benchmark

**Pull request merged**
