### PR TITLE
[IRGen] Emit bit for @main into entry section.

### PR DESCRIPTION
**Pull request by nate-chandler**
The `_swift5_entry` section contains a relative pointer to the entry-point function (spelled variously `_main` and `@main` depending on context). Support differentiating whether that entry point originates from a type annotated `@main` or something else (i.e. `main.swift`) via a second relative-pointer-sized field.  For now, that field is just a bit: 1 if there is a type annotated @main, 0 otherwise.  In the future, that field could be a relative pointer to the type descriptor for the type.

rdar://100130950

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by aschwaighofer — APPROVED** [review]
LGTM

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
Potentially!  Like the description says
> In the future, that field could be a relative pointer to the type descriptor for the type.

On the one hand, having a relative-pointer sized field which is non-zero just when there's a type annotated `@main` is a slightly more minimal ABI to commit to--that field could be upgraded to a full relative pointer later.  And perhaps keeping a reference to the descriptor would keep things alive unnecessarily.  On the other hand, maybe we're not saving much by not committing to that further ABI now.

What do you think, @jckarter?

**Comment by jckarter** [comment]
It's a good question. I was thinking that, if we're putting a flag bit there now, we would need to take another word to store a descriptor later. But on the other hand, having a flag word reserved is probably a good idea for adding future flags too. So this is probably fine as is.

**Comment by nate-chandler** [comment]
Makes sense.  I changed it over from being "a bit and eventually perhaps a type descriptor relative pointer" to instead being "a flag word containing a bit indicating that the entry point comes from `@main` and perhaps will eventually contain a bit indicating that there is a type descriptor that appears after the flag word".  That's NFC on x86_64 and arm64, but indicates the future direction.

**Comment by nate-chandler** [comment]
@swift-ci please test

**Pull request merged**
