### PR TITLE
[cxx-interop] Break when we find a linkage specification when traversing all decls in IRGen.

### PR DESCRIPTION
**Pull request by zoecarver**
Without this, we will find the linkage specification decl rather than a function decl (for example). The problem here is that we will check if we've already traversed this decl and bail out. If we do that we will not codegen the function decl (for example) and get linker errors. 

I have a test case that I'm trying to reduce and I will add that as a test. rdar://110439422

### CODE REVIEW

**Comment by zoecarver** [comment]
```
extern "C" {

inline void inlineFn();

void cacheMis();
void incorrectCacheHit() {
  inlineFn();
}

static void caller() {  
  cacheMis();
  incorrectCacheHit();
}

inline void inlineFn() {
}

}

// Swift

public func test() {
  caller()
}
```

**Comment by plotfi** [comment]
@zoecarver Ah so this is to keep the ClangDeclFinder from quitting on LinkageSpecDecls?

**Comment by zoecarver** [comment]
Yep added a test!

**Comment by zoecarver** [comment]
@swift-ci please smoke test

**Review by egorzhdan — APPROVED** [review]

**Review by plotfi — APPROVED** [review]

**Pull request merged**
