### PR TITLE
SIL: Use CaptureKind::Box for weak and unowned captures in noescape closures [4.0]

### PR DESCRIPTION
**Pull request by slavapestov**
* Description: Fixes a bug where a 'weak self' captured by a non-escaping closure could be released too early.

* Origination: Recent regression from #10041.

* Scope of the issue: I suspect this is more common than we think, because people defensively add `[weak self]` to closures.

* Tested: New test added to ensure the right SIL instructions are emitted.

* Reviewed by: @jckarter  

* Radar: <rdar://problem/32718153>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@gottesmm Can you please review?

**Comment by gottesmm** [comment]
@slavapestov I can review. I have a few questions. Lets talk about it in person.

**Comment by jckarter** [comment]
Seems fine as a stopgap for 4.0. The lifetime on nonescaping captures should really extend until after the callee returns, though.

**Review by jckarter — APPROVED** [review]

**Pull request merged**
