### PR TITLE
update-checkout: explicitly use tag name

### PR DESCRIPTION
**Pull request by compnerd**
We were attempting to checkout a tag, but did not specify that properly
and so certain versions of git may attempt to checkout a branch rather
than the tag.  This should address that to repair the Windows CI builds.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @rxwei @milseman @najacque @drewmaxwell-apple

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by rxwei** [comment]
Thanks!

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by drewmaxwell-apple** [comment]
Why are there no test results? Doesn't sending everything to NUL skip this?

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@drewmaxwell-apple, the redirection to `NUL` is to avoid printing to the console which significantly slows down the process.  This shaves ~2m off the build.  There are no test results because the test never gets kicked off due to the failure to clone.

**Comment by compnerd** [comment]
However, this is `build-windows.bat`, which is used for the CI jobs, not the toolchain jobs.

https://ci-external.swift.org/job/oss-swift-windows-toolchain-x86_64-vs2019/
is the failing job, which uses build-windows-toolchain.bat, so this change is not going to impact that

**Comment by compnerd** [comment]
BTW, the logging there is the interesting aspect:

```
+ git submodule update --recursive
Updating 'C:\Users\swift-ci\jenkins\workspace\oss-swift-windows-toolchain-x86_64-vs2019\swift-experimental-string-processing'
C:\Users\swift-ci\jenkins\workspace\oss-swift-windows-toolchain-x86_64-vs2019\swift-experimental-string-processing
b"error: pathspec 'dev/4' did not match any file(s) known to git\n"
Error on repo "C:\Users\swift-ci\jenkins\workspace\oss-swift-windows-toolchain-x86_64-vs2019\swift-experimental-string-processing": Traceback (most recent call last):
  File "C:\Users\swift-ci\jenkins\workspace\oss-swift-windows-toolchain-x86_64-vs2019\swift\utils\update_checkout\update_checkout\update_checkout.py", line 163, in update_single_repository
    result = shell.run(['git', 'rev-parse', checkout_target])
  File "C:\Users\swift-ci\jenkins\workspace\oss-swift-windows-toolchain-x86_64-vs2019\swift\utils\swift_build_support\swift_build_support\shell.py", line 244, in run
    raise eout
Exception: ['git', 'rev-parse', 'dev/4']

During handling of the above exception, another exception occurred:
```
This obviously makes sense - you aren't checking out a branch, you are checking out a tag, therefore you need to checkout `tag/dev/4`.

@rxwei - can we switch from tags to branches for the time being?

**Comment by compnerd** [comment]
@swift-ci please test windows platform

**Comment by rxwei** [comment]
Perhaps we can switch to a `dev/stable` branch which we manually integrate from main.

**Comment by compnerd** [comment]
> Perhaps we can switch to a `dev/stable` branch which we manually integrate from main.

Wait, dev/stable doesn't seem to be a branch?  https://github.com/apple/swift-experimental-string-processing/branches

**Comment by compnerd** [comment]
@drewmaxwell-apple okay, I think I finally understand what's going on.  You're going to have to go into the machine and force the clean clone; swift-experimental-string-processing was added after the toolchain builds were already setup, so it cloned it with `--no-tags` which means that the subsequent fetches will *not* fetch the tags.  The result is that `git rev-parse dev/4` will not succeed as the tags are not present.  If you can clean up the work directory, then it should clone everything afresh and include the tags on the clones.

**Comment by compnerd** [comment]
@drewmaxwell-apple cleaned the workspace, and I believe that should now restore the full CI.  Thanks @drewmaxwell-apple!

**Pull request closed without merging**
