### PR TITLE
AST/SILGen support for constant string literals

### PR DESCRIPTION
**Pull request by aschwaighofer**
rdar://30545013

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
Unrelated linux failure that also fails here: https://ci.swift.org/job/oss-swift-incremental-RA-linux-ubuntu-16_04/2577/

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test linux

**Comment by gottesmm** [comment]
@aschwaighofer Can you also add support for an objc convention as well? This is important so we can take advantage of NSConstantString. Or did I miss it?

**Comment by aschwaighofer** [comment]
Yes this could be done in the future.

**Comment by aschwaighofer** [comment]
How do you express NSConstantString literals in swift? I don't think you can.

**Comment by aschwaighofer** [comment]
@swift-ci Please test linux

**Comment by gottesmm** [comment]
It would be done via an optimization. I.e. if we have a string literal and immediately bridge it to objc, we could replace it with an objc string literal that would get converted at IRGen time into an NSConstantString.

**Comment by aschwaighofer** [comment]
@mgottesmm Good point!

**Pull request merged**
