### PR TITLE
update_checkout: bump s-a-p to 1.2.3

### PR DESCRIPTION
**Pull request by compnerd**
In order to work with further improvements to static linking on Windows to enable Swift in Swift and C++ Interop, we need to bump the s-a-p with a fix for underlinking.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
Updating tag check list: https://github.com/apple/swift/blob/main/docs/Branches.md#updating-branchtag

**Comment by shahmishal** [comment]
Please also update the `next` scheme.

**Comment by compnerd** [comment]
https://github.com/apple/swift-source-compat-suite/pull/838 is the swift-source-compat-suite change.

**Pull request merged**
