### PR TITLE
[Dependency Scanning] Add ability for `-scan-dependencies` action to serialize and deserialize dependency scanner cache from a `.moddepcache` file.

### PR DESCRIPTION
**Pull request by artemcm**
Using the serialization format added in https://github.com/apple/swift/pull/37585.

- Add load/save code for the `-scan-dependencies` code-path.
- If a scanner is invoked on a main module already contained in the cache, ensure the scanner updates the dependencies, instead of asserting that they do not yet exist. 
- Add `libSwiftDriver` entry-points to load/store the cache of a given scanner instance or reset the cache to start scanning with a clean slate.

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci please test

**Review by nkcsgexi — APPROVED** [review]
Thank you! Could you add some documentation comments in the C API header about why using scanning cache cannot be an implementation detail of the compiler?

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
> Thank you! Could you add some documentation comments in the C API header about why using scanning cache cannot be an implementation detail of the compiler?

Good idea. Done.

**Pull request merged**
