### PR TITLE
Update swift:main to support llvm-project:stable/20210726 changes (Rebranch merge)

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test source compat suite

**Comment by shahmishal** [comment]
@swift-ci Please Test Source Compatibility

**Comment by shahmishal** [comment]
@swift-ci Please Test Source Compatibility

**Comment by shahmishal** [comment]
@swift-ci clean test Linux

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by etcwilde** [comment]
Java! *shakes fist at sky*
Build log: https://ci-external.swift.org/job/swift-PR-windows/17194/console

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by etcwilde** [comment]
Looks like Linux is going to fail. The enum is going to need a little love so that it doesn't break on `-Welaborated-enum-base`. 
https://ci.swift.org/job/swift-PR-Linux/29106/console

**Comment by compnerd** [comment]
That's in the LLDB test suite; seems that to be something to adjust in the the llvm-project tree.  I wonder if we are missing an upstream cherry-pick and how that got through the CI.

**Comment by etcwilde** [comment]
Erg, no, I don't think it's what I thought it was. I thought it was related to the same issue as this PR: https://github.com/apple/swift-corelibs-foundation/commit/2e9d97daa69ba81e716e31b76e571f833eb5ed9a

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by etcwilde** [comment]
Another C++ interop failure:

```
********************
Failed Tests (1):
  Swift(windows-x86_64) :: Interop/Cxx/class/protocol-conformance-typechecker.swift


Testing Time: 171.16s
  Unsupported      : 1854
  Passed           : 5921
  Expectedly Failed:   46
  Failed           :    1
```

**Comment by etcwilde** [comment]
Linux failure is due to:

```
22:20:01 Failed Tests (4):
22:20:01   lldb-api :: lang/swift/enum_objc/TestEnumObjC.py
22:20:01   lldb-api :: lang/swift/expression/exclusivity_suppression/TestExclusivitySuppression.py
22:20:01   lldb-api :: lang/swift/implementation_only_imports/main_executable/TestMainExecutable.py
22:20:01   lldb-api :: lang/swift/po/sys_types/TestSwiftPOSysTypes.py
```

These failures are known and will be disabled with: https://github.com/apple/llvm-project/pull/3298.

**Comment by shahmishal** [comment]
@swift-ci clean test Linux

**Comment by shahmishal** [comment]
```

02:40:14 Failed Tests (1):
02:40:14   lldb-shell :: SwiftREPL/FoundationTypes.test

```
Cc: @JDevlieghere

**Comment by shahmishal** [comment]
@swift-ci test Amazon Linux 2

**Comment by shahmishal** [comment]
@swift-ci test centos 8

**Comment by shahmishal** [comment]
@swift-ci test Ubuntu 20.04

**Comment by shahmishal** [comment]
After multiple runs we are still seeing this test failure.

```

Failed Tests (1):
  Swift(windows-x86_64) :: Interop/Cxx/class/protocol-conformance-typechecker.swift

```

cc: @zoecarver any suggestions on whats going on?

**Comment by etcwilde** [comment]
@swift-ci test Ubuntu 20.04

**Comment by zoecarver** [comment]
> After multiple runs we are still seeing this test failure.
> 
> ```
> 
> Failed Tests (1):
>   Swift(windows-x86_64) :: Interop/Cxx/class/protocol-conformance-typechecker.swift
> ```
> 
> cc: @zoecarver any suggestions on whats going on?

It looks like last time it was `access-specifiers-typechecker.swift` and now it's `protocol-conformance-typechecker.swift`. Several people have reported this same issue recently across many PRs. I've also been seeing it myself. It seems like there's some race condition when loading modules on Windows... maybe in these small tests we don't wait for clang to load something? @compnerd any ideas?

Until we sort this out, I think your best bet is re-running the CI any time you see the `error: could not build C module` on Windows.

**Comment by shahmishal** [comment]
@zoecarver 
>Until we sort this out, I think your best bet is re-running the CI any time you see the error: could not build C module on Windows.
Unfortunately this is costly, can we disable these tests if they are flaky?

**Comment by zoecarver** [comment]
> Unfortunately this is costly, can we disable these tests if they are flaky?

I agree. This is really not ideal. But it seems like almost all the module-interface and typechecker tests are susceptible. 

Luckily it seems like the Windows bots have a lot of power, but still, not ideal.

**Comment by zoecarver** [comment]
Also CC @bnbarham. Any chance a recent swift driver change added a race condition when loading clang modules?

**Comment by compnerd** [comment]
@shahmishal I haven't been able to identify the change, but this is definitely something that is part of the rebranch.  There was flakiness before, but nothing at this scale.  There is most definitely a race condition that is now getting exposed.  On the local builds, I've seen a number of failures with the rebuild of the modules (which points to 766a08df12c111b15ed51d0fcac06042d2f68cd6).  Reverting that change locally seems to have a drastic improvement on the stability.

**Comment by shahmishal** [comment]
cc @bnbarham -- https://reviews.llvm.org/D105328

Any thoughts on why we are seeing this on Windows?

**Comment by bnbarham** [comment]
> cc @bnbarham -- https://reviews.llvm.org/D105328
> 
> Any thoughts on why we are seeing this on Windows?

Very strange. That PR changes what would (or could, technically) be a crash into a compiler error. It's invalid to return OutOfDate for a module that's already been finalized. I'm not sure why it would be worse on Windows either. Any ideas @vsapsai?

**Comment by shahmishal** [comment]
@swift-ci clean test

**Comment by etcwilde** [comment]
We will need https://github.com/apple/swift/pull/39498 to get past the SILOptimizer/mem2reg_lifetime.sil failure.

The Linux failure was due to a missing template parameter to the `SmallVector`.

**Comment by shahmishal** [comment]
@swift-ci clean test

**Comment by shahmishal** [comment]
@swift-ci test Ubuntu 20.04

**Comment by etcwilde** [comment]
Ubuntu 20.04 failure: Error: No such container: swift-pr-ubuntu-2004

**Comment by etcwilde** [comment]
```
20:26:09 Step 3/6 : ENV DEBIAN_FRONTEND="noninteractive"
20:26:09  ---> [Warning] IPv4 forwarding is disabled. Networking will not work.
20:26:10  ---> Running in 14c13bdffe6c
20:26:10 Removing intermediate container 14c13bdffe6c
20:26:10  ---> 882ad48dda20
20:26:10 Step 4/6 : RUN apt-get -y update && apt-get -y install   build-essential         clang                   cmake                   git                     icu-devtools            libcurl4-openssl-dev    libedit-dev             libicu-dev              libncurses5-dev         libpython3-dev          libsqlite3-dev          libxml2-dev             ninja-build             pkg-config              python                  python-six              python2-dev             python3-six             python3-distutils       rsync                   swig                    systemtap-sdt-dev       tzdata                  unzip                   uuid-dev
20:26:10  ---> [Warning] IPv4 forwarding is disabled. Networking will not work.
20:26:10  ---> Running in bb511ab47364
20:26:10 Err:1 http://archive.ubuntu.com/ubuntu focal InRelease
20:26:31   Temporary failure resolving 'archive.ubuntu.com'
20:26:31 Err:2 http://security.ubuntu.com/ubuntu focal-security InRelease
20:26:31   Temporary failure resolving 'security.ubuntu.com'
20:26:31 Err:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
20:26:51   Temporary failure resolving 'archive.ubuntu.com'
20:26:51 Err:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
20:27:11   Temporary failure resolving 'archive.ubuntu.com'
20:27:11 Reading package lists...
20:27:11 [91mW: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal/InRelease  Temporary failure resolving 'archive.ubuntu.com'
20:27:11 W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
20:27:11 W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
20:27:11 W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
20:27:11 W: Some index files failed to download. They have been ignored, or old ones used instead.
20:27:11 [0mReading package lists...
20:27:11 Building dependency tree...
20:27:11 Reading state information...
20:27:11 [91mE: Unable to locate package build-essential
20:27:11 E: Unable to locate package clang
20:27:11 E: Unable to locate package cmake
20:27:11 E: Unable to locate package git
20:27:11 E: Unable to locate package icu-devtools
20:27:11 E: [0m[91mUnable to locate package libcurl4-openssl-dev
20:27:11 E: Unable to locate package libedit-dev
20:27:11 E: [0m[91mUnable to locate package libicu-dev
20:27:11 E: Unable to locate package libncurses5-dev
20:27:11 E: Unable to locate package libpython3-dev
20:27:11 [0m[91mE: Unable to locate package libsqlite3-dev
20:27:11 E: Unable to locate package libxml2-dev
20:27:11 [0m[91mE: Unable to locate package ninja-build
20:27:11 E: Unable to locate package pkg-config
20:27:11 E[0m[91m: Unable to locate package python
20:27:11 E: Unable to locate package python-six[0m[91m
20:27:11 E: Unable to locate package python2-dev
20:27:11 E: Unable to locate package python3-six[0m[91m
20:27:11 E: Unable to locate package python3-distutils[0m[91m
20:27:11 E: Unable to locate package rsync
20:27:11 E: Unable to locate package swig[0m[91m
20:27:11 E: Unable to locate package systemtap-sdt-dev
20:27:11 E: Unable to locate package tzdata
20:27:11 E[0m[91m: Unable to locate package unzip
20:27:11 E[0m[91m: Unable to locate package uuid-dev
20:27:11 [0mThe command '/bin/sh -c apt-get -y update && apt-get -y install   build-essential         clang                   cmake                   git                     icu-devtools            libcurl4-openssl-dev    libedit-dev             libicu-dev              libncurses5-dev         libpython3-dev          libsqlite3-dev          libxml2-dev             ninja-build             pkg-config              python                  python-six              python2-dev             python3-six             python3-distutils       rsync                   swig                    systemtap-sdt-dev       tzdata                  unzip                   uuid-dev' returned a non-zero code: 100
```

**Comment by etcwilde** [comment]
@swift-ci clean test

**Comment by etcwilde** [comment]
More interop failures on Windows: 
```
  Swift(windows-x86_64) :: Interop/C/implementation-only-imports/check-function-transitive-visibility.swift
  Swift(windows-x86_64) :: Interop/C/implementation-only-imports/check-function-visibility.swift
```

**Comment by etcwilde** [comment]
Linux failure:
```
/home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-main/swift/lib/SILOptimizer/Transforms/SILMem2Reg.cpp:405:3: error: too few template arguments for class template 'SmallVector'
22:03:34   SmallVector<DeallocStackInst *> dsis;
22:03:34   ^
22:03:34 /home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-main/swift/include/swift/Basic/LLVM.h:47:43: note: template is declared here
22:03:34   template <typename T, unsigned N> class SmallVector;
22:03:34   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~       ^
22:03:34 /home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-main/swift/lib/SILOptimizer/Transforms/SILMem2Reg.cpp:409:3: error: too few template arguments for class template 'SmallVector'
22:03:34   SmallVector<SILBasicBlock *> lexicalBBIBlocks;
22:03:34   ^
22:03:34 /home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-main/swift/include/swift/Basic/LLVM.h:47:43: note: template is declared here
22:03:34   template <typename T, unsigned N> class SmallVector;
22:03:34   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~       ^
22:03:34 /home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-main/swift/lib/SILOptimizer/Transforms/SILMem2Reg.cpp:795:3: error: too few template arguments for class template 'SmallVector'
22:03:34   SmallVector<SILValue> vals;
22:03:34   ^
22:03:34 /home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-main/swift/include/swift/Basic/LLVM.h:47:43: note: template is declared here
22:03:34   template <typename T, unsigned N> class SmallVector;
22:03:34   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~       ^
22:03:34 /home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-main/swift/lib/SILOptimizer/Transforms/SILMem2Reg.cpp:405:35: warning: private field 'dsis' is not used [-Wunused-private-field]
22:03:34   SmallVector<DeallocStackInst *> dsis;
22:03:34                                   ^
22:03:34 /home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-main/swift/lib/SILOptimizer/Transforms/SILMem2Reg.cpp:409:32: warning: private field 'lexicalBBIBlocks' is not used [-Wunused-private-field]
22:03:34   SmallVector<SILBasicBlock *> lexicalBBIBlocks;
22:03:34                                ^
```

**Comment by etcwilde** [comment]
This PR should fix the issue on Linux: https://github.com/apple/swift/pull/39501

**Comment by etcwilde** [comment]
@swift-ci please test Linux platform

**Comment by shahmishal** [comment]
@swift-ci clean test macOS

**Comment by shahmishal** [comment]
@swift-ci test Ubuntu 20.04

**Comment by etcwilde** [comment]
Please test with the following pull request:
https://github.com/apple/llvm-project/pull/3309

@swift-ci please test Windows platform

**Comment by shahmishal** [comment]
@swift-ci test Amazon Linux 2

**Comment by shahmishal** [comment]
@swift-ci test CentOS 8

**Comment by compnerd** [comment]
Please test with the following pull request:
apple/llvm-project#3333

@swift-ci please test Windows platform

**Comment by compnerd** [comment]
Please test with the following pull request:
apple/llvm-project#3333

@swift-ci please test Windows platform

**Comment by compnerd** [comment]
Please test with the following pull request:
apple/llvm-project#3334

@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by shahmishal** [comment]
@swift-ci test CentOS 8

**Comment by shahmishal** [comment]
@swift-ci test Amazon Linux 2

**Comment by shahmishal** [comment]
@swift-ci test Ubuntu 20.04

**Comment by shahmishal** [comment]
@swift-ci build toolchain

**Comment by etcwilde** [comment]
I'm still banging my head against the `Glibc.pthread_mutex_t` resolution issue, so I expect that the Linux builds will still fail.

**Comment by compnerd** [comment]
Yeah, I wanted to make sure that the macOS builds are also good to go at this point.  Trying to ascertain where exactly we stand wrt the rebranch.

**Comment by shahmishal** [comment]
@swift-ci test CentOS 8

**Comment by shahmishal** [comment]
@swift-ci test Ubuntu 18.04

**Comment by shahmishal** [comment]
@swift-ci test Amazon Linux 2

**Comment by shahmishal** [comment]
Re-running CentOS 8

**Comment by shahmishal** [comment]
@swift-ci please test macOS

**Comment by shahmishal** [comment]
It was related to https://github.com/apple/llvm-project/pull/3316, @meg-gupta is cherry-pick the fix into `stable/20210726`.

**Comment by etcwilde** [comment]
> It was related to [apple/llvm-project#3316](https://github.com/apple/llvm-project/pull/3316), @meg-gupta is cherry picking the fix into `stable/20210726`.

Great. Thank you!

**Comment by shahmishal** [comment]
@swift-ci test Ubuntu 20.04

**Comment by shahmishal** [comment]
@swift-ci test Amazon Linux 2

**Comment by etcwilde** [comment]
Please test with the following PR:
https://github.com/apple/llvm-project/pull/3369

@swift-ci please test Linux platform

**Comment by etcwilde** [comment]
@swift-ci please test

**Comment by etcwilde** [comment]
@swift-ci test Amazon Linux 2

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by etcwilde** [comment]
Centos failure:
```
20:07:24 Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Delete http://%2Fvar%2Frun%2Fdocker.sock/v1.24/volumes/swift-pr-centos-8?force=1: dial unix /var/run/docker.sock: connect: permission denied
```

**Comment by compnerd** [comment]
Linux failure:
```
The following tests FAILED:
	1602 - TestFoundation.TestNSAttributedString-test_enumerateAttributes (Failed)
	1623 - TestFoundation.TestNSMutableAttributedString-test_reverse_attribute_enumeration_with_extend_attributed_replace (Failed)
	1624 - TestFoundation.TestNSMutableAttributedString-test_direct_attributes_enumeration_with_extend_attributed_replace (Failed)
	1625 - TestFoundation.TestNSMutableAttributedString-test_reverse_attributes_enumeration_with_extend_attributed_replace (Failed)
	1628 - TestFoundation.TestNSMutableAttributedString-test_direct_attributes_enumeration_with_reduct_attributed_replace (Failed)
	1629 - TestFoundation.TestNSMutableAttributedString-test_reverse_attributes_enumeration_with_reduct_attributed_replace (Failed)
	1630 - TestFoundation.TestNSMutableAttributedString-test_direct_attribute_enumeration_with_extend_replace (Failed)
	1631 - TestFoundation.TestNSMutableAttributedString-test_reverse_attribute_enumeration_with_extend_replace (Failed)
	1632 - TestFoundation.TestNSMutableAttributedString-test_direct_attributes_enumeration_with_extend_replace (Failed)
	1633 - TestFoundation.TestNSMutableAttributedString-test_reverse_attributes_enumeration_with_extend_replace (Failed)
	1634 - TestFoundation.TestNSMutableAttributedString-test_direct_attribute_enumeration_with_reduct_replace (Failed)
	1635 - TestFoundation.TestNSMutableAttributedString-test_reverse_attribute_enumeration_with_reduct_replace (Failed)
	1636 - TestFoundation.TestNSMutableAttributedString-test_direct_attributes_enumeration_with_reduct_replace (Failed)
	1637 - TestFoundation.TestNSMutableAttributedString-test_reverse_attributes_enumeration_with_reduct_replace (Failed)
	1845 - TestFoundation.TestAttributedString-testConversionFromObjC (ILLEGAL)
	1848 - TestFoundation.TestAttributedString-testIncompleteConversionFromObjC (ILLEGAL)
	1850 - TestFoundation.TestAttributedString-testConversionNestedScope (ILLEGAL)
	1855 - TestFoundation.TestAttributedString-testConversionCoalescing (ILLEGAL)
```

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Ubuntu 20.04 Platform

**Comment by compnerd** [comment]
@swift-ci please build linux toolchain

**Comment by compnerd** [comment]
@swift-ci please build linux toolchain

**Comment by etcwilde** [comment]
@swift-ci Please Build Toolchain Linux Platform

**Comment by compnerd** [comment]
Please test with the following PRs:
apple/swift-corelibs-foundation#3086

@swift-ci please test CentOS 8 Platform

**Comment by compnerd** [comment]
Please test with the following PRs:
apple/swift-corelibs-foundation#3086

@swift-ci please test test Ubuntu 20.04 Platform

**Comment by etcwilde** [comment]
apple/swift-corelibs-foundation#3086

@swift-ci please test test Ubuntu 20.04

**Pull request merged**
