### PR TITLE
[WIP] [Mangling] Make the conformances in a retroactive conformance substitutable

### PR DESCRIPTION
**Pull request by DougGregor**
The same mangled name may end up referring to the same conformance
multiple times as part of the retroactive-conformance mangling. Make
those protocol conformance substitution candidates for name
mangling. To do so, promote the protocol-conformance grammar
production to a normal operator mangling. This makes some manglings
one character longer (such as witness tables and witness table
thunks).

### CODE REVIEW

**Comment by DougGregor** [comment]
I haven't updated the full pile of test cases that now need changes due to mangling protocol conformances as operators. @rjmccall , is this the right way to go?

**Comment by rjmccall** [comment]
I guess so.  You could probably save the character hit from the top-level conformance symbols by giving them a single-character operator, or just give them a special-case mangling that suppresses the substitution candidate.

**Review by eeckstein — COMMENTED** [review]
A separate operator is not necessary to do substitution (as far as I can remember).
To do substitutions you only have to make sure that adding substitutions is in sync between the manger and demangler. E.g. whenever the mangler registers a substitution for a conformance, also the demangler has to register one if it demangles a conformance.

**Comment by DougGregor** [comment]
Suppressing the operator in "known" positions seems like a reasonable approach. I'll try that.

**Comment by DougGregor** [comment]
The expected win here is small enough that it's not worth pursuing.

**Pull request closed without merging**
