### PR TITLE
Temporarily disable LoopARC.

### PR DESCRIPTION
**Pull request by trentxintong**

### CODE REVIEW

**Comment by trentxintong** [comment]
@swift-ci Please smoke test

**Comment by trentxintong** [comment]
@swift-ci Please benchmark

**Comment by trentxintong** [comment]
The benchmark is unlikely to finish on time. Erik told me there is no significant performance regressions measured on his machine.

**Comment by trentxintong** [comment]
we did not measure such regression locally, especially the NSStringConversion. maybe its just noise. we will see on zperf.

**Comment by eeckstein** [comment]
zperf basically shows no regression, except noise

**Pull request merged**
