### PR TITLE
[CSBindings] NFC: Couple minor incrementality adjustments

### PR DESCRIPTION
**Pull request by xedin**
- Filter out some of the constraints which can't delay hole propagation
- Attempt `Void` fallback for closure result only when other choices have failed
- Attempt l-value fallback for force unwrap only after r-value type failed

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Review by hborla — APPROVED** [review]

**Comment by xedin** [comment]
`Dollar` is the only failure and it's failing on main as well.

**Pull request merged**
