### PR TITLE
[AST] Move getEffectiveAccess calls into SIL.

### PR DESCRIPTION
**Pull request by huonw**

### CODE REVIEW

**Comment by huonw** [comment]
@swift-ci Please smoke test.

**Comment by slavapestov** [comment]
This will conflict with https://github.com/apple/swift/pull/10380, can you wait until @swiftix checks that in? Also I think isConformanceSerialized() is a better name than isConformanceFixedLayout().

**Comment by huonw** [comment]
@swift-ci Please smoke test.

**Review by slavapestov — APPROVED** [review]

**Comment by huonw** [comment]
@swift-ci Please smoke test and merge.

**Comment by huonw** [comment]
@swift-ci Please smoke test.

**Comment by huonw** [comment]
@swift-ci Please smoke test

**Pull request merged**
