### PR TITLE
Fix the Effective Access Level of package Declarations

### PR DESCRIPTION
**Pull request by CodaFi**
swiftc mis-compiles package declarations today because it reports the effective access level of package declarations as less than public. There are a bunch of places in the optimizer that are checking the effective access level against an upper bound of public, so a lot of code winds up internalized or optimized as though it were internal when it definitely is not.

Fixes rdar://118081829

### CODE REVIEW

**Comment by nkcsgexi** [comment]
Thank you for fixing this, @CodaFi !

**Comment by nkcsgexi** [comment]
Could you add a test case that package symbols have public symbols?

**Comment by CodaFi** [comment]
Sure thing. I was moving rather quickly - tests will follow shortly.

**Comment by CodaFi** [comment]
Existing tests are rather wonky on my machine. 

@swift-ci smoke test

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by CodaFi** [comment]
@swift-ci test

**Review by elsh — APPROVED** [review]
Thanks for the fix and adding the tests!

**Pull request merged**
