### PR TITLE
[gardening][Foundation] Prefer macOS over OSX for `@available`

### PR DESCRIPTION
**Pull request by ikesyo**

### CODE REVIEW

**Comment by ikesyo** [comment]
@swift-ci smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by ikesyo** [comment]
Refs: #15230, #15292 and similar PRs

I'll go ahead.

@swift-ci Please smoke test and merge

**Comment by ikesyo** [comment]
@swift-ci Please smoke test and merge

**Pull request merged**
