### PR TITLE
[Exclusivity] Switch static checking to use IndexTrie instead of Proj…

### PR DESCRIPTION
**Pull request by devincoughlin**
…ectionPath

IndexTrie is a more light-weight representation and it works well in this case.
This requires recovering the represented sequence from an IndexTrieNode, so
also add a getParent() method.

### CODE REVIEW

**Comment by devincoughlin** [comment]
\cc @atrick

**Comment by devincoughlin** [comment]
@swift-ci Please smoke test and merge

**Comment by devincoughlin** [comment]
@swift-ci please test

**Comment by devincoughlin** [comment]
@swift-ci please test and merge

**Comment by atrick** [comment]
👍

**Comment by najacque** [comment]
Huh. something is wonky with the PR test.  Taking a look.

**Comment by najacque** [comment]
@swift-ci please test and merge

**Comment by najacque** [comment]
@swift-ci Please clean test

**Comment by najacque** [comment]
@swift-ci Please clean test

**Comment by najacque** [comment]
Master is busticated.  There's a PR going in in a few mins that should fix it, then I'll kick this off again.

**Comment by najacque** [comment]
@swift-ci please test and merge
Ok, let's try this again, now that master is fixed.

**Comment by najacque** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
Comment has to be before the trigger :)
@swift-ci please test and merge

**Comment by najacque** [comment]
jinx!

**Comment by najacque** [comment]
We had more breakage on master. Should be fixed now... Let's try this again.
@swift-ci please test

**Comment by devincoughlin** [comment]
Let's "trie" this again.
@swift-ci Please smoke test and merge

**Pull request merged**
