### PR TITLE
[SIL] Filter out macro decls in top level lookup

### PR DESCRIPTION
**Pull request by bnbarham**
Resolves rdar://106242860.

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]
LGTM, thank you!

**Comment by bnbarham** [comment]
@swift-ci please smoke test macOS platform

**Comment by bnbarham** [comment]
Test failure is unrelated (flakey LLDB test)

**Pull request merged**
