### PR TITLE
[Distributed] NFC: Re-enable remoteCall test-case on Linux

### PR DESCRIPTION
**Pull request by xedin**

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Comment by ktoso** [comment]
Build just timed out... 
```
14:24:21 PASS: Swift-validation(linux-x86_64) :: stdlib/FixedPoint.swift.gyb (15257 of 15258)
14:25:34 
Build timed out (after 60 minutes). Marking the build as failed.
```

**Comment by ktoso** [comment]
@swift-ci please smoke test Linux

**Comment by ktoso** [comment]
@swift-ci please test Linux platform

**Comment by xedin** [comment]
@ktoso The test it timed out on is remoteCall.swift, it's not in the listing anywhere...

**Comment by ktoso** [comment]
Eh I see, no good then... we have a radar about it hanging on Linux rdar://87240034 related to the one to reenable the tests rdar://88228867 ... So seems like no luck still then :-/

**Comment by xedin** [comment]
Yeah, we still need to debug what is going on Linux

**Comment by xedin** [comment]
@ktoso I think you should still land your changes to remove Foundation from the test-case.

**Comment by ktoso** [comment]
Okey will do :+1: Will be splitting up cleaning up my PR once I figure out the remaining dance with the type aliases there. Will just keep it in a separate commit there and land it

**Pull request closed without merging**
