### PR TITLE
[Macros] Serialize plugin search paths for LLDB use

### PR DESCRIPTION
**Pull request by xymus**
rdar://107030743

### CODE REVIEW

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by xymus** [comment]
The current implementation always writes the paths in the swiftmodule, it ignores `SerializeOptionsForDebugging`. I assume the only case where we'd want to ignore some of these search paths is when the swiftmodules are distributed. This may be more a check to apply on the reader side, in LLDB.

**Review by rintaro — APPROVED** [review]
Looks good to me as long as we're OK to serialize them unconditionally.
I agree that distributing `swiftmodule` is not common.

**Pull request merged**
