### PR TITLE
[Runtime/Metadata] Add ownership information to `_getTypeByMangledName`

### PR DESCRIPTION
**Pull request by xedin**
`_typeByMangledName` could encounter types which have ownership attributes
associated with them which are not representable by the metadata object
but nevertheless are important, so such ownership information should be
returned along with metadata itself from the call.

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Review by DougGregor — APPROVED** [review]
LGTM

**Pull request merged**
