### PR TITLE
[gardening] Standardize include guard in SILSuccessor.h

### PR DESCRIPTION
**Pull request by gottesmm**
2nd to last gardening commit from vacation.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci Please smoke test and merge

**Comment by gottesmm** [comment]
@shahmishal I triggered the smoke test an hour or two ago... whats going on?

**Comment by gottesmm** [comment]
@swift-ci Please smoke test and merge

**Comment by erg** [comment]
@swift-ci Please test and merge

**Comment by shahmishal** [comment]
@gottesmm Fixed, network issue.

**Pull request merged**
