### PR TITLE
Revert "[DebugInfo] Set the autogenerated bit to request recycled locations"

### PR DESCRIPTION
**Pull request by atrick**
Reverts apple/swift#15929

This breaks PR testing because it was only smoke tested.
```
/swift/test/DebugInfo/returnlocation.swift:188:22: error: CHECK_INIT-NEXT: is not on the line after the previous match
 // CHECK_INIT-NEXT: call void @swift_bridgeObjectRelease{{.*}}, !dbg [[retnLoc:![0-9]+]]
                     ^
<stdin>:752:2: note: 'next' match was here
 call void @swift_bridgeObjectRelease(%swift.bridge* %2) #4, !dbg !275
 ^
<stdin>:749:149: note: previous match ended here
 call swiftcc void @"$Ss5print_9separator10terminatoryypd_S2StF"(%swift.bridge* %2, i32 %16, i32 %17, i32 %18, i32 %20, i32 %21, i32 %22), !dbg !274
                                                                                                                                                    ^
<stdin>:750:1: note: non-matching line after previous match is here
 call void @"$Ss13_StringObjectV8_VariantOWOe"(i32 %20), !dbg !275
^

https://ci.swift.org/job/oss-swift_tools-RA_stdlib-RD_test-simulator/869/consoleFull#174822253ba62d58e-7248-467b-91e0-c7508d5cf947
```

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
Reverting this is blocked by PR #15930.

**Comment by atrick** [comment]
@swift-ci smoke test OS X Platform.

**Comment by atrick** [comment]
@swift-ci test.

**Comment by vedantk** [comment]
Sorry about this. There should be a simpler way to write this test.

**Pull request merged**
