### PR TITLE
utils: build Foundation macros for distribution

### PR DESCRIPTION
**Pull request by compnerd**
This adds a build of the Foundation macros for distribution in the toolchain.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-foundation#849

@swift-ci please test Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-foundation/pull/849

@swift-ci please test Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-foundation/pull/849

@swift-ci please test

**Comment by compnerd** [comment]
Explanation: Build changes necessary to support building macros for Windows.
Scope: Enables building and distributing the Foundation macros on all platforms.
Issue:
Original PR: https://github.com/apple/swift-foundation/pull/714
Risk: We would need additional changes to build and distribute the macros.
Testing: The original changes were tested as part of building the toolchain and the installer for Windows as well as the built image for Linux.
Reviewer: @jmschonfeld

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-foundation/pull/849

https://github.com/swiftlang/swift-installer-scripts/pull/330

@swift-ci please build toolchain Windows platform

**Review by stephentyrone — APPROVED** [review]

**Pull request merged**
