### PR TITLE
[Runtime/ABI] Optimize number of function metadata ABI endpoints

### PR DESCRIPTION
**Pull request by xedin**
- Removes `swift_get{Block|C|Thin|FunctionTypeMetadata` of the function metadata stubs;
- Adds `swift_getFunctionTypeMetadata0` to handle metadata retrieval for functions with no arguments, which is a common use-case;
- Removes `swift_getFunctionTypeMetadata{1|2|3}WithFlags` and replaces their use with the general endpoint instead, since it was minimal;
- Updates to "Function Metadata" section of `doc/TypeMetadata.rst` to mention what endpoints we currently have and why we've decided not to include more specialized ones.

Resolves: rdar://problem/36278686

### CODE REVIEW

**Comment by xedin** [comment]
@rjmccall Please take a look. Not sure if the wording in the doc is ok.

**Review by rjmccall — APPROVED** [review]
Thanks, this looks great.

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please clean test macOS platform

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please clean test macOS platform

**Comment by xedin** [comment]
@rjmccall There is something weird going on with macOS tests it keeps on failing with

```
Assertion failed: (isTypeMetadata()), function getDescription, file /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/include/swift/Runtime/Metadata.h, line 1489.
```

but it's related to nominal types which I didn't touch, any idea what might be going on?

**Comment by xedin** [comment]
I suspect this happens because function metadata size is calculated incorrectly for cases where parameters have flags, will investigate some more tomorrow.

**Comment by xedin** [comment]
@rjmccall I figured what is going on but I'm not sure what the right fix is - it has to do with `CreateLifetimeEnd` at the end of `default` block, it would erase the parameters. Is the right fix to remove the `CreateLifetime{Start|End}` or is it to copy them when we create `FunctionCacheEntry::Key` ?

**Comment by xedin** [comment]
It's seems like none of the solutions I thought of are actually going to help. It looks like Key might be used past the lifetime of the parameters somehow...

**Comment by rjmccall** [comment]
FunctionCacheEntry::Key is like the ArrayRef of a FunctionCacheEntry: it's a lightweight reference to some existing data, and we shouldn't need to copy just to create one.  We do need to end up copying when we actually allocate a FunctionCacheEntry and initialize it *from* the FunctionCacheEntry::Key, though.  However, from inspection it looks like we do, so I don't know what's going on.

**Comment by xedin** [comment]
One thing I know for sure is that when I remove `CreateLifetimeEnd` swiftpm builds locally and tests are all green :( It looks like there might be a problem somewhere we haven't seen before because default path hasn't been exercised enough for 1/2/3 arguments...

**Comment by rjmccall** [comment]
Is it maybe a bug in how some other code in the same function is using the lifetime intrinsics?

**Comment by rjmccall** [comment]
It's possible that using the lifetime intrinsics is allowing the function-parameters array to be allocated in the same space as some other allocation that *supposedly* doesn't need to be around for the same period of time but actually does.

**Comment by xedin** [comment]
But there are no other allocations in that function though - flags are const array... Maybe if the argument is a function type itself that's how it happens, because that's going to recur into the same code and generate the same lifetime intrinsics...

**Comment by rjmccall** [comment]
You'd have to consider the entire function that we're calling getFunctionTypeMetadata from, not just the local behavior of GenMeta.  That is, the important thing is the *source* function.

Have you been able to reproduce?  Do you know what source function (presumably in swiftpm) is calling getFunctionTypeMetadata?

**Comment by xedin** [comment]
I can reproduce with swiftpm but I can't get any info about where it happens, it's just this assertion failure and not stacktrace or anything.

**Comment by rjmccall** [comment]
No luck getting that in a debugger?

**Comment by xedin** [comment]
I tried, but no luck, because it happens as part of bigger build, maybe that's why it can't attach, i tried without --parallel-test too.

**Comment by xedin** [comment]
I just thought - we are caching a call right after `CreateLifetimeEnd` there, isn't that a problem if something else get's it and tries to use?

**Comment by rjmccall** [comment]
We're caching the result of the call, which no longer depends on the buffer being valid.

**Comment by rjmccall** [comment]
It is absolutely a bug if anything about the returned metadata relies on the validity of the buffer after the call returns.

**Comment by xedin** [comment]
@rjmccall @jckarter 

I did some refactoring in `visitFunctionType` to bring it close to how everything is done in `visitTupleType` but it doesn't fix the problem (although it makes the metadata function a bit smaller).

Checked IR generated for `swift_getFunctionTypeMetadata` to make sure that lifetime instructions are generated for correct address and in correct positions... And went through `FunctionCacheEntry` to verify that nothing is storing data from `FunctionCacheEntry::Key` in there.

 I've spent whole day today trying to figure it out, and I really need help to make it work at this point...

**Comment by xedin** [comment]
I've also tried to comment out all of the specialized cases for tuples but it didn't crash swiftpm build. I'm wondering if this might be related to Objective-C somehow?

**Comment by xedin** [comment]
I've try another thing - only use the default if there are no parameters and that didn't crash swiftpm, so I suspect it has something to do with how the flags are allocated and lifetime of the parameters...

**Comment by xedin** [comment]
I was able to narrow it down to function with 2 parameters where at least one has flags. Will continue tomorrow.

**Comment by rjmccall** [comment]
You need to be looking at the code for the function that *calls* swift_getFunctionTypeMetadata, if the bug is really that the buffer overlaps something else.  That's one reason it's so important to duplicate this in a debugger.  There's undoubtedly a way to get the build to print command lines for what it's doing.

**Comment by xedin** [comment]
That's exactly what I'm trying to do but what "buffer" are you talking about in this context? Memory used for `FunctionCacheEntry`?

**Comment by rjmccall** [comment]
No, I mean the array passed to swift_getFunctionTypeMetadata.

The lifetime markers basically scope the lifetime of that array to just around the call.  Without them, it effectively has the scope of the entire function.  Since its address is passed out of the function to code that the compiler can't reason about, absent the markers the compiler conservatively assumes that the callee might rely on the array sticking around for an arbitrary amount of time.  With the markers, the caller knows that the memory can be re-used, so it can allocate spills or other allocas to that same space in the stack frame.  So if you can just get the assembly for that caller, I'd be happy to look it over and help figure out what's going wrong.

**Comment by xedin** [comment]
Interesting. Thanks for the information! Theoretically speaking (while I'm trying to get more information), I wonder how flags plays into this at all since it's allocated as a global const array via `ConstantInitBuilder`? It looks like it might be related to `FunctionCacheEntry` size/allocation.

**Comment by rjmccall** [comment]
I wouldn't expect the flags to play any role in it.  The flags are created as a global array, i.e. something that lives forever and isn't ever modified.  It doesn't interfere with the stack at all.

**Comment by rjmccall** [comment]
Oh hey, try removing ReadNone from the list of flags on swift_getFunctionTypeMetadata; that is clearly not correct.

**Comment by xedin** [comment]
Ah wow, yeah that did work! :(

**Comment by xedin** [comment]
@swift-ci please clean test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please clean test

**Comment by gparker42** [comment]
Uh-oh. I assume we need to remove `ReadNone` from all of the other variants of `swift_getFunctionTypeMetadata` as well. 

I see a bunch of other suspicious `ReadNone` attributes in Metadata.h. For example `objc_lookUpClass` is not `ReadNone` if I understand the attribute correctly. We need to review every use of `ReadNone` in that file.

**Comment by jckarter** [comment]
@gparker42 `readnone` ought to be fine for any of the metadata functions that take their arguments by value, such as the `getFunctionTypeMetadataN` variants. The memory they read in that case doesn't have any semantic effect on the caller side of the program. We ought to be using the weaker `argmemonly` modifier on any metadata functions that read their arguments from buffers.

**Comment by rjmccall** [comment]
The other swift_getFunctionTypeMetadata variants are fine to be ReadNone because they don't read from program-visible mutable memory.  That plays into why this hasn't been a huge problem historically:

- For a long time, we encoded 'inout' by setting the low bit on the parameter metadata pointer, so you could always use swift_getFunctionTypeMetadata{1,2,3} unless you had 0 or more than 3 parameters.

- We changed that recently when we separated the flags out, but we simultaneously added WithFlags variants for {1,2,3}, so again you only needed swift_getFunctionTypeMetadata with 0 or more than 3 parameters.

- But this patch drops the WithFlags variants, so the bug calling swift_getFunctionTypeMetadata is a lot more prominent.

- And 0 was never a problem because of course the runtime doesn't read from the buffer when there's nothing in it.

**Comment by gparker42** [comment]
Where is our definition of readnone? Does it not match LLVM's readnone?

**Comment by rjmccall** [comment]
It's LLVM's readnone.  If you're thinking that that's literally a promise not to read memory or have side-effects, that's not really right; it's defined more operationally, in terms of the reordering/elision guarantees it enables.

**Comment by xedin** [comment]
Looks like everything is green, I am going to merge later tonight if there are no objections.

**Comment by gparker42** [comment]
Okay, where is *that* definition? The definition of readnone in LLVM's language reference manual only discusses memory and program state.

My understanding is that clang's `__attribute__(const)` is equivalent to LLVM's `readonly`. The test below demonstrates that marking `objc_lookUpClass()` as `__attribute__(const)` is incorrect.

```
#include <string.h>
extern void *objc_lookUpClass(const char *s) __attribute__((const));
void lookUpTwoClasses(void *output[2]) {
    char name[4];
    strcpy(name, "foo");
    output[0] = objc_lookUpClass(name);
    strcpy(name, "bar");
    output[1] = objc_lookUpClass(name);
}
```
The generated code (`clang -Os -o - -S`) only calls `objc_lookUpClass` once. That is permitted by a "does not dereference arguments" definition of `__attribute__((const))` but does not match the intended behavior.

The only way this could work would be if the Swift compiler somehow guarantees that the code it generates is not broken by LLVM's operational behavior even though it violates LLVM's requirements. If that is the way it works then we ought to document the hell out of it.

**Comment by gparker42** [comment]
(For the record I have no objection to this patch. Perhaps the attribute discussion ought to go somewhere else now.)

**Comment by rjmccall** [comment]
``__attribute__((const))`` is equivalent to LLVM's ``readnone``.  It's ``__attribute__((pure))`` that's equivalent to LLVM's ``readonly``.  Yes, this is the opposite of you might expect from the names, and yes, that's just the unfortunate reality.  (IIRC, It's historical: ``pure`` was added first.)

The practical definition is the general consensus among LLVM optimizer developers; I'm not sure it's well-documented.  Basically, ``readnone`` can be arbitrarily reordered and combined (as long as its dependencies are available, of course), and ``readonly`` can be reordered and combined except over writes to accessible memory.

The laxity in the rules is specifically intended to allow things like memoized functions, which is effective what the metadata accessors are.

Making ``objc_lookUpClass`` ``__attribute__((const))`` is wrong because it does read externally-accessible memory: it reads the contents of the string passed in.  ``__attribute__((pure))`` is correct if this function does not have "intentionally-observable" side effects.  If it forces the initialization of the class, either attribute would be wrong because it would be legal to not call the function at all if the result was unused.

**Comment by xedin** [comment]
Thanks for explanation, @rjmccall! I learned a lot of new things today :)

**Pull request merged**
