### PR TITLE
[test] Fix test that's failing on the Android CI since string processing was enabled by default

### PR DESCRIPTION
**Pull request by finagolfin**
Also, move the test to test/Frontend/ where it belongs and disable implicit concurrency import too.

@compnerd, you added this to the Driver tests three years ago in #25902, but `%swift` only invokes the frontend now (maybe it worked differently back then?) so I moved the test.

@drodriguez, this should get the Android CI green again.

I have no idea why this only started failing on the Android CI, but not on the linux CI too.

### CODE REVIEW

**Review by compnerd — APPROVED** [review]
Seems reasonable to me.  I think that it is very likely that the substitutions have changed in the intervening years.

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by buttaface** [comment]
Mac CI failure is unrelated.

**Comment by drodriguez** [comment]
@swift-ci please smoke test macOS platform

**Comment by buttaface** [comment]
Same Mac failure, looks like [the macOS CI has been broken for a day](https://ci.swift.org/job/swift-PR-macos-smoke-test/).

**Comment by buttaface** [comment]
Ping, Mac CI is working now, I think we can get this in.

**Comment by drodriguez** [comment]
@swift-ci please smoke test macOS platform

**Comment by buttaface** [comment]
@egorzhdan, would you merge?

**Pull request merged**
