### PR TITLE
Adjust for LLVM changes

### PR DESCRIPTION
**Pull request by smeenai**

### CODE REVIEW

**Comment by smeenai** [comment]
CC @compnerd @dcci @xiaobai @gmittert

**Comment by xiaobai** [comment]
@swift-ci please test

**Comment by xiaobai** [comment]
@swift-ci please test

**Comment by smeenai** [comment]
I don't actually see any failures in those test results? Seems like an infra issue.

**Comment by xiaobai** [comment]
@swift-ci please test

**Comment by smeenai** [comment]
Build failures look like infra issues.

**Review by dcci — APPROVED** [review]

**Comment by smeenai** [comment]
https://github.com/apple/swift/pull/27810 should fix all of this

**Pull request closed without merging**
