### PR TITLE
[stdlib] Surface NSKeyedArchiver issues in Xcode.

### PR DESCRIPTION
**Pull request by jrose-apple**
By calling through to swift_reportToDebugger, Xcode can pick up the NSKeyedArchiver/Unarchiver issues with Swift classes and display them in the Issues Navigator. This increases the probability that they'll be seen and acted upon.

For those watching: **This is not a fully-general interface yet, please do not start hooking random things up to it.** Especially if you're working on something that doesn't ship with Xcode itself. :-)

rdar://problem/32900735

### CODE REVIEW

**Comment by jrose-apple** [comment]
@jckarter, @rjmccall, and/or @gparker42: is it okay to expose this additional entry point in the runtime?

**Comment by jrose-apple** [comment]
Blocked by <rdar://problem/33248301> Multiple notes are not supported in run-time issues.

**Review by itaiferber — APPROVED** [review]
Looks like a reasonable change to me!

**Review by DougGregor — APPROVED** [review]
This looks fantastic to me

**Comment by slimjim1** [comment]
3https://github.com/apple/swift/commit/17b601c580782feb0a822dc4ea700f700e079319

**Comment by jckarter** [comment]
Seems fine to me for now. If you don't think the interface is fully baked, though, it might be good to represent that in the symbol name somehow.

**Comment by gottesmm** [comment]
@jckarter Adding an underscore to make it runtime SPI?

**Review by kubamracek — APPROVED** [review]
I would also put an underscore to swift_reportToDebugger. Otherwise look great.

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Pull request merged**
