### PR TITLE
Synthesize ==/hashValue for tuple fields/payloads

### PR DESCRIPTION
**Pull request by allevato**
The original PR (#9619) implementing `Equatable`/`Hashable` only covered types that directly conformed to those protocols. This is a bit restrictive for real-world usage—for example, a `struct` with an `Int?` field won't be able to synthesize, so this PR fills in some gaps for the sake of usability: synthesis for fields/associated values that are ~`Optional<T> where T: Equatable/Hashable` and for~ tuples where all fields are `Equatable`/`Hashable`.

~In each case, ~future language improvements will eventually allow the special cases to go away. ~For `Optional`, we need conditional conformances.~ For tuples, we need the ability to conform non-nominal types to protocols (and variadic generics).

**Update:** As discussed below, the support for `Optional` has been removed because it will be covered better by conditional conformances. Exciting!

### CODE REVIEW

**Comment by allevato** [comment]
**Open question:** Attempting to do this recursively (to allow synthesis in the presence of fields, say, of types `Int??`, `(Int?, Int?)`, or `(Int, Int)?`) gets quite a bit more complicated, so those have been left out.

But, there may be some value in extending this to handle `Array` and `Dictionary`—the `==` operator already exists for `[T]` and `[T: U]` where `T` and `U` are `Equatable`, and we could add helper functions in `Hashing.swift` for computing their hash values.

Thoughts?

**Comment by airspeedswift** [comment]
Once we have conditional conformance this can just be driven by Equatable conformance (except for tuples). And that should be pretty close based on @huonw’s recent commits. So probably better to hold off for now.

**Comment by allevato** [comment]
@airspeedswift That's great—I didn't realize they were that close. Making `==`/`hashValue` work with conditional conformances will require the ability to synthesize in a same-file extension, which we don't support today, but I can work on that in a different PR.

It sounds like I should remove the `Optional` support from this one and focus solely on tuples. WDYT?

**Comment by DougGregor** [comment]
Yeah, I'd prefer to remove `Optional` support from this pull request and focus solely on tuples, for which we won't be able to use conditional conformances.

**Comment by allevato** [comment]
Sounds good to me! I've updated the PR to cover tuples only.

**Comment by xwu** [comment]
Question: tuples have `==` implemented only up to arity 6, and that's an acknowledged hack. Instead of synthesizing `Equatable` for types that have a tuple _field_, can we fix the hack and actually synthesize `Equatable` for the tuples themselves?

**Comment by allevato** [comment]
@xwu I looked into it a little bit, but it seems that having non-nominal types conform to protocols is a much deeper change. Unfortunately I'm less familiar with where to go about getting started on that.

Since I don't know how much work it is, I'm not sure if it would make it by the Swift 4.1 deadline. If that change isn't possible in that timeframe, I'd like to not have the existing synthesis crippled because of that missing feature. The tuple-specific changes in this PR can be easily removed in the future once tuples have that capability.

**Comment by huonw** [comment]
> can we fix the hack and actually synthesize Equatable for the tuples themselves?

This also requires conditional conformances. It requires synthesizing something like `extension<T, U> (T, U): Equatable where T: Equatable, U: Equatable` (pseudo-Swift syntax), which is almost, but not quite, supported.

**Comment by allevato** [comment]
It's also less clear how tuples and `Hashable` conformance would interact. `Equatable` is "cleaner" because the requirement can be satisfied by synthesizing a global function.

What does it mean to attach a property to a tuple? What if my tuple is `(foo: Int, hashValue: Int)` and I want it to conform to `Hashable`? How is that collision handled?

**Comment by xwu** [comment]
This is one reason why the design of the derived `==` operator was changed so that the actual method is named `__derived_enum_equals` with an attribute `@_implements(Equatable, ==(_:_:))`. If it isn't already, the synthesized `hashValue` should be `__derived_struct_hashValue` with a corresponding attribute so that no funny shadowing occurs.

**Comment by CodaFi** [comment]
@allevato It's been a few years.  If you want to pursue this further, could you please pitch this to evolution so we can get the community's updated thoughts on the idea?

Sorry we weren't able to resolve this at the time.

**Pull request closed without merging**
