### PR TITLE
Fix SILGen ManagedValue::isPlusOne for addresses

### PR DESCRIPTION
**Pull request by atrick**
Fix ManagedValue::isPlusOne for addresses

    In-memory values cannot be reused after deinitialization.

    Add ManagedValue::isPlusOneOrTrivial() for situations where we want to
    forward a value without destroying the original memory.

    Fixes rdar://108001491 (SIL verification failed: Found mutating or
    consuming use of an in_guaranteed parameter?!:
    !ImmutableAddressUseVerifier().isMutatingOrConsuming(fArg))

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci test source compatibility

**Comment by atrick** [comment]
@swift-ci benchmark

**Comment by atrick** [comment]
Appeared to have a connection failure when running Swift driver tests after all regular tests passed.

**Comment by atrick** [comment]
@swift-ci test macOS Platform

**Review by jckarter — APPROVED** [review]

**Pull request merged**
