### PR TITLE
[SDK] Adjust dependency script & regenerate dependencies

### PR DESCRIPTION
**Pull request by lorentey**
The overlay dependencies are a bit out date with the SDKs that are in Xcode 11 beta 1, and this causes CI issues. Adjust the script to reduce the amount of noise it generates and regenerate overlay dependencies.

rdar://problem/51634433

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci clean test

**Comment by benlangmuir** [comment]
@swift-ci clean test macOS

**Comment by jrose-apple** [comment]
Make sure you do the generation against the internal SDKs. Better to have too many dependencies than not enough.

**Comment by lorentey** [comment]
11281 failures are a few more than I expected.

**Comment by lorentey** [comment]
@swift-ci clean test macOS platform

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci clean test

**Comment by lorentey** [comment]
That was slightly too many additions -- we have two cycles now: 

Dispatch → os → Dispatch
ObjectiveC → os → ObjectiveC

```
CMake Error: The inter-target dependency graph contains the following strongly connected component (cycle):
  "swiftDispatch-swiftmodule-iphonesimulator-i386" of type UTILITY
    depends on "lib-swift-iphonesimulator-Dispatch.swiftmodule-i386.swiftmodule" (strong)
  "lib-swift-iphonesimulator-Dispatch.swiftmodule-i386.swiftmodule" of type UTILITY
    depends on "swiftObjectiveC-swiftmodule-iphonesimulator-i386" (strong)
    depends on "swiftos-swiftmodule-iphonesimulator-i386" (strong)
  "swiftObjectiveC-swiftmodule-iphonesimulator-i386" of type UTILITY
    depends on "lib-swift-iphonesimulator-ObjectiveC.swiftmodule-i386.swiftmodule" (strong)
  "lib-swift-iphonesimulator-ObjectiveC.swiftmodule-i386.swiftmodule" of type UTILITY
    depends on "swiftos-swiftmodule-iphonesimulator-i386" (strong)
  "swiftos-swiftmodule-iphonesimulator-i386" of type UTILITY
    depends on "lib-swift-iphonesimulator-os.swiftmodule-i386.swiftmodule" (strong)
  "lib-swift-iphonesimulator-os.swiftmodule-i386.swiftmodule" of type UTILITY
    depends on "swiftDispatch-swiftmodule-iphonesimulator-i386" (strong)
    depends on "swiftObjectiveC-swiftmodule-iphonesimulator-i386" (strong)
```

**Comment by jrose-apple** [comment]
Hm, `ObjectiveC` definitely shouldn't depend on `os`. And I think `os` depend on `Dispatch` but not the other way around.

**Comment by benlangmuir** [comment]
@jrose-apple did you mean Dispatch depends on os?
```
<snip>/usr/include/dispatch/dispatch.h:
26:#include <os/availability.h>
28:#include <os/base.h>
30:#include <os/generic_win_base.h>
32:#include <os/generic_unix_base.h>
59:#include <os/object.h>
```

**Comment by jrose-apple** [comment]
No, `os_object` and `os_base` were broken out into their own modules to break this circularity.

```
module os [system] [extern_c] {
 module base {
  export Darwin.os.base
 }
 module lock {
  export Darwin.os.lock
 }
 module object {
  export os_object
 }
 // ...
}
```

**Comment by lorentey** [comment]
Rebased and reverted back to the public SDK.

@swift-ci test

**Pull request merged**
