### PR TITLE
[CSClosure] SE-0326: Type-checker statement conditions individually

### PR DESCRIPTION
**Pull request by xedin**
Instead of referencing whole statement condition, break it down to
individual elements and solve them separately.

Resolves: rdar://88720312

### CODE REVIEW

**Comment by xedin** [comment]
Temporarily re-enabling inference to test source compability.

**Comment by xedin** [comment]
Compat suite is green in both configurations, going drop the commit that re-enabled multi-statement closures.

**Comment by xedin** [comment]
@swift-ci please smoke test

**Review by hborla — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Comment by xedin** [comment]
Unrelated lldb failure on macOS -  `lldb-api :: lang/swift/implementation_only_imports/library_resilient/TestLibraryResilient.py`

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Pull request merged**
