### PR TITLE
Define availability for the 6.0 stdlib & runtime; define placeholder availability for 6.1

### PR DESCRIPTION
**Pull request by lorentey**
This PR updates the Standard Library to resolve `SwiftStdlib 6.0` to the new OS releases that were announced this week:

```
SwiftStdlib 6.0:macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0
```

It also updates RuntimeVersions.def to define availability for the 6.0 runtime within the compiler.

Additionally, this PR defines stdlib/runtime version 6.1 with placeholder availability, and updates `_SwiftStdlibVersion.current` to report itself as that.

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci benchmark

**Review by tshortli — APPROVED** [review]

**Review by Azoy — APPROVED** [review]

**Review by shahmishal — APPROVED** [review]

**Review by shahmishal — APPROVED** [review]
Thank you!

**Review by al45tair — APPROVED** [review]

**Review by ktoso — APPROVED** [review]
LGTM!

**Comment by lorentey** [comment]
Oh gosh, I missed a bunch of uses of 5.11 in FeatureAvailability.def.

```
<unknown>:0: error: fatal error encountered during compilation; please submit a bug report (https://swift.org/contributing/#reporting-bugs)
<unknown>:0: note: Missing runtime version data for Swift 5.11
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Program arguments: /home/build-user/build/buildbot_linux/swift-linux-x86_64/bin/swift-frontend -frontend -c /home/build-user/swift/stdlib/public/Concurrency/Actor.swift /home/build-user/swift/stdlib/public/Concurrency/AsyncLet.swift /home/build-user/swift/stdlib/public/Concurrency/CheckedContinuation.swift /home/build-user/swift/stdlib/public/Concurrency/Errors.swift /home/build-user/swift/stdlib/public/Concurrency/Executor.swift /home/build-user/swift/stdlib/public/Concurrency/ExecutorAssertions.swift /home/build-user/swift/stdlib/public/Concurrency/AsyncCompactMapSequence.swift /home/build-user/swift/stdlib/public/Concurrency/AsyncDropFirstSequence.swift /home/build-user/swift/stdlib/public/Concurrency/AsyncDropWhileSequence.swift /home/build-user/swift/stdlib/public/Concurrency/AsyncFilterSequence.swift /home/build-user/swift/stdlib/public/Concurrency/AsyncFlatMapSequence.swift /home/build-user/swift/stdlib/public/Concurrency/AsyncIteratorProtocol.swift /home/build-user/swift/stdlib/public/Concurrency/AsyncMapSequence.swift /home/build-user/swift/stdlib/public/Concurrency/AsyncPrefixSequence.swift /home/build-user/swift/stdlib/public/Concurrency/AsyncPrefixWhileSequence.swift /home/build-user/swift/stdlib/public/Concurrency/AsyncSequence.swift /home/build-user/swift/stdlib/public/Concurrency/AsyncThrowingCompactMapSequence.swift /home/build-user/swift/stdlib/public/Concurrency/AsyncThrowingDropWhileSequence.swift /home/build-user/swift/stdlib/public/Concurrency/AsyncThrowingFilterSequence.swift /home/build-user/swift/stdlib/public/Concurrency/AsyncThrowingFlatMapSequence.swift /home/build-user/swift/stdlib/public/Concurrency/AsyncThrowingMapSequence.swift /home/build-user/swift/stdlib/public/Concurrency/AsyncThrowingPrefixWhileSequence.swift /home/build-user/swift/stdlib/public/Concurrency/GlobalActor.swift /home/build-user/swift/stdlib/public/Concurrency/PartialAsyncTask.swift /home/build-user/swift/stdlib/public/Concurrency/Task.swift /home/build-user/swift/stdlib/public/Concurrency/TaskCancellation.swift -supplementary-output-file-map /tmp/TemporaryDirectory.sOlmmK/supplementaryOutputs-1 -disable-objc-attr-requires-foundation-module -target x86_64-unknown-linux-gnu -disable-objc-interop -I /home/build-user/swift/stdlib/public/Concurrency/InternalShims -I /home/build-user/build/buildbot_linux/swift-linux-x86_64/lib/swift/embedded -color-diagnostics -module-cache-path /home/build-user/build/buildbot_linux/swift-linux-x86_64/module-cache -module-link-name swift_Concurrency -parse-stdlib -static -swift-version 5 -O -D SWIFT_ENABLE_EXPERIMENTAL_CONCURRENCY -D SWIFT_ENABLE_EXPERIMENTAL_DISTRIBUTED -D SWIFT_ENABLE_EXPERIMENTAL_DIFFERENTIABLE_PROGRAMMING -D SWIFT_ENABLE_EXPERIMENTAL_STRING_PROCESSING -D SWIFT_ENABLE_EXPERIMENTAL_OBSERVATION -D SWIFT_ENABLE_SYNCHRONIZATION -D SWIFT_RUNTIME_OS_VERSIONING -D SWIFT_STDLIB_ENABLE_UNICODE_DATA -D SWIFT_STDLIB_ENABLE_VECTOR_TYPES -D SWIFT_STDLIB_HAS_COMMANDLINE -D SWIFT_STDLIB_HAS_STDIN -D SWIFT_STDLIB_SINGLE_THREADED_CONCURRENCY -D SWIFT_STDLIB_OVERRIDABLE_RETAIN_RELEASE -D SWIFT_THREADING_NONE -D SWIFT_CONCURRENCY_EMBEDDED -assume-single-threaded -enforce-exclusivity=unchecked -empty-abi-descriptor -disable-autolinking-runtime-compatibility-concurrency -disable-objc-interop -define-availability "SwiftStdlib 9999:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999" -define-availability "SwiftStdlib 5.0:macOS 10.14.4, iOS 12.2, watchOS 5.2, tvOS 12.2" -define-availability "SwiftStdlib 5.1:macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0" -define-availability "SwiftStdlib 5.2:macOS 10.15.4, iOS 13.4, watchOS 6.2, tvOS 13.4" -define-availability "SwiftStdlib 5.3:macOS 11.0, iOS 14.0, watchOS 7.0, tvOS 14.0" -define-availability "SwiftStdlib 5.4:macOS 11.3, iOS 14.5, watchOS 7.4, tvOS 14.5" -define-availability "SwiftStdlib 5.5:macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0" -define-availability "SwiftStdlib 5.6:macOS 12.3, iOS 15.4, watchOS 8.5, tvOS 15.4" -define-availability "SwiftStdlib 5.7:macOS 13.0, iOS 16.0, watchOS 9.0, tvOS 16.0" -define-availability "SwiftStdlib 5.8:macOS 13.3, iOS 16.4, watchOS 9.4, tvOS 16.4" -define-availability "SwiftStdlib 5.9:macOS 14.0, iOS 17.0, watchOS 10.0, tvOS 17.0" -define-availability "SwiftStdlib 5.10:macOS 14.4, iOS 17.4, watchOS 10.4, tvOS 17.4, visionOS 1.1" -define-availability "SwiftStdlib 6.0:macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0" -define-availability "SwiftStdlib 6.1:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999, visionOS 9999" -target-min-inlining-version min -enable-experimental-feature NoncopyableGenerics2 -enable-experimental-feature SuppressedAssociatedTypes -enable-experimental-feature ExtensionImportVisiblity -enable-experimental-feature Embedded -enable-experimental-feature IsolatedAny2 -empty-abi-descriptor -Xcc -working-directory -Xcc /home/build-user/build/buildbot_linux/swift-linux-x86_64/stdlib/public/Concurrency -resource-dir /home/build-user/build/buildbot_linux/swift-linux-x86_64/lib/swift -module-name _Concurrency -plugin-path /home/build-user/build/buildbot_linux/swift-linux-x86_64/lib/swift/host/plugins -plugin-path /home/build-user/build/buildbot_linux/swift-linux-x86_64/local/lib/swift/host/plugins -enable-default-cmo -parse-as-library -o /home/build-user/build/buildbot_linux/swift-linux-x86_64/stdlib/public/Concurrency/embedded/x86_64-unknown-linux-gnu/_Concurrency.o -runtime-compatibility-version none -disable-autolinking-runtime-compatibility-dynamic-replacements
1.	Swift version 6.0-dev (LLVM 57177aa1b91540b, Swift 240909bb9b7ca18)
2.	Compiling with effective version 5.10
3.	While evaluating request TypeCheckSourceFileRequest(source_file "/home/build-user/swift/stdlib/public/Concurrency/AsyncSequence.swift")
4.	While evaluating request TypeCheckFunctionBodyRequest(_Concurrency.(file)._contains(_:where:)@/home/build-user/swift/stdlib/public/Concurrency/AsyncSequence.swift:184:6)
5.	While type-checking statement at [/home/build-user/swift/stdlib/public/Concurrency/AsyncSequence.swift:187:26 - line:194:1] RangeText="{
  for try await element in self {
    if try await predicate(element) {
      return true
    }
  }
  return false
"
6.	While type-checking statement at [/home/build-user/swift/stdlib/public/Concurrency/AsyncSequence.swift:188:3 - line:192:3] RangeText="for try await element in self {
    if try await predicate(element) {
      return true
    }
  "
7.	While type-checking-for-each statement at [/home/build-user/swift/stdlib/public/Concurrency/AsyncSequence.swift:188:3 - line:192:3] RangeText="for try await element in self {
    if try await predicate(element) {
      return true
    }
  "
8.	While type-checking-target starting at /home/build-user/swift/stdlib/public/Concurrency/AsyncSequence.swift:188:3
```

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci benchmark

**Comment by lorentey** [comment]
Note to self: maybe do a local test run next time.

```
FAIL: Swift(linux-x86_64) :: ModuleInterface/distributed-actor.swift (4775 of 18113)
******************** TEST 'Swift(linux-x86_64) :: ModuleInterface/distributed-actor.swift' FAILED ********************
Script:
--
: 'RUN: at line 1';   rm -rf "/home/build-user/build/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/ModuleInterface/Output/distributed-actor.swift.tmp" && mkdir -p "/home/build-user/build/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/ModuleInterface/Output/distributed-actor.swift.tmp"
: 'RUN: at line 2';   split-file /home/build-user/swift/test/ModuleInterface/distributed-actor.swift /home/build-user/build/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/ModuleInterface/Output/distributed-actor.swift.tmp
: 'RUN: at line 4';   /home/build-user/build/buildbot_linux/swift-linux-x86_64/bin/swift-frontend -target x86_64-unknown-linux-gnu  -module-cache-path /home/build-user/build/buildbot_linux/swift-linux-x86_64/swift-test-results/x86_64-unknown-linux-gnu/clang-module-cache -swift-version 4  -define-availability 'SwiftStdlib 9999:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999' -define-availability 'SwiftStdlib 5.0:macOS 10.14.4, iOS 12.2, watchOS 5.2, tvOS 12.2' -define-availability 'SwiftStdlib 5.1:macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0' -define-availability 'SwiftStdlib 5.2:macOS 10.15.4, iOS 13.4, watchOS 6.2, tvOS 13.4' -define-availability 'SwiftStdlib 5.3:macOS 11.0, iOS 14.0, watchOS 7.0, tvOS 14.0' -define-availability 'SwiftStdlib 5.4:macOS 11.3, iOS 14.5, watchOS 7.4, tvOS 14.5' -define-availability 'SwiftStdlib 5.5:macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0' -define-availability 'SwiftStdlib 5.6:macOS 12.3, iOS 15.4, watchOS 8.5, tvOS 15.4' -define-availability 'SwiftStdlib 5.7:macOS 13.0, iOS 16.0, watchOS 9.0, tvOS 16.0' -define-availability 'SwiftStdlib 5.8:macOS 13.3, iOS 16.4, watchOS 9.4, tvOS 16.4' -define-availability 'SwiftStdlib 5.9:macOS 14.0, iOS 17.0, watchOS 10.0, tvOS 17.0' -define-availability 'SwiftStdlib 5.10:macOS 14.4, iOS 17.4, watchOS 10.4, tvOS 17.4, visionOS 1.1' -define-availability 'SwiftStdlib 6.0:macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0' -define-availability 'SwiftStdlib 6.1:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999, visionOS 9999'  -typo-correction-limit 10  -emit-module -module-name Library      -swift-version 5 -enable-library-evolution      -o /home/build-user/build/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/ModuleInterface/Output/distributed-actor.swift.tmp/Library.swiftmodule      -emit-module-interface-path /home/build-user/build/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/ModuleInterface/Output/distributed-actor.swift.tmp/Library.swiftinterface      /home/build-user/build/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/ModuleInterface/Output/distributed-actor.swift.tmp/Library.swift
: 'RUN: at line 11';   /usr/bin/python3.8 /home/build-user/swift/utils/PathSanitizingFileCheck --allow-unused-prefixes --sanitize BUILD_DIR=/home/build-user/build/buildbot_linux/swift-linux-x86_64 --sanitize SOURCE_DIR=/home/build-user/swift --use-filecheck /home/build-user/build/buildbot_linux/llvm-linux-x86_64/bin/FileCheck   /home/build-user/swift/test/ModuleInterface/distributed-actor.swift < /home/build-user/build/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/ModuleInterface/Output/distributed-actor.swift.tmp/Library.swiftinterface
: 'RUN: at line 14';   /home/build-user/build/buildbot_linux/swift-linux-x86_64/bin/swift-frontend -target x86_64-unknown-linux-gnu  -module-cache-path /home/build-user/build/buildbot_linux/swift-linux-x86_64/swift-test-results/x86_64-unknown-linux-gnu/clang-module-cache -swift-version 4  -define-availability 'SwiftStdlib 9999:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999' -define-availability 'SwiftStdlib 5.0:macOS 10.14.4, iOS 12.2, watchOS 5.2, tvOS 12.2' -define-availability 'SwiftStdlib 5.1:macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0' -define-availability 'SwiftStdlib 5.2:macOS 10.15.4, iOS 13.4, watchOS 6.2, tvOS 13.4' -define-availability 'SwiftStdlib 5.3:macOS 11.0, iOS 14.0, watchOS 7.0, tvOS 14.0' -define-availability 'SwiftStdlib 5.4:macOS 11.3, iOS 14.5, watchOS 7.4, tvOS 14.5' -define-availability 'SwiftStdlib 5.5:macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0' -define-availability 'SwiftStdlib 5.6:macOS 12.3, iOS 15.4, watchOS 8.5, tvOS 15.4' -define-availability 'SwiftStdlib 5.7:macOS 13.0, iOS 16.0, watchOS 9.0, tvOS 16.0' -define-availability 'SwiftStdlib 5.8:macOS 13.3, iOS 16.4, watchOS 9.4, tvOS 16.4' -define-availability 'SwiftStdlib 5.9:macOS 14.0, iOS 17.0, watchOS 10.0, tvOS 17.0' -define-availability 'SwiftStdlib 5.10:macOS 14.4, iOS 17.4, watchOS 10.4, tvOS 17.4, visionOS 1.1' -define-availability 'SwiftStdlib 6.0:macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0' -define-availability 'SwiftStdlib 6.1:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999, visionOS 9999'  -typo-correction-limit 10  -typecheck -module-name Client      -swift-version 5      /home/build-user/build/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/ModuleInterface/Output/distributed-actor.swift.tmp/Client.swift -I/home/build-user/build/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/ModuleInterface/Output/distributed-actor.swift.tmp
: 'RUN: at line 19';   rm /home/build-user/build/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/ModuleInterface/Output/distributed-actor.swift.tmp/Library.swiftmodule
: 'RUN: at line 20';   /home/build-user/build/buildbot_linux/swift-linux-x86_64/bin/swift-frontend -target x86_64-unknown-linux-gnu  -module-cache-path /home/build-user/build/buildbot_linux/swift-linux-x86_64/swift-test-results/x86_64-unknown-linux-gnu/clang-module-cache -swift-version 4  -define-availability 'SwiftStdlib 9999:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999' -define-availability 'SwiftStdlib 5.0:macOS 10.14.4, iOS 12.2, watchOS 5.2, tvOS 12.2' -define-availability 'SwiftStdlib 5.1:macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0' -define-availability 'SwiftStdlib 5.2:macOS 10.15.4, iOS 13.4, watchOS 6.2, tvOS 13.4' -define-availability 'SwiftStdlib 5.3:macOS 11.0, iOS 14.0, watchOS 7.0, tvOS 14.0' -define-availability 'SwiftStdlib 5.4:macOS 11.3, iOS 14.5, watchOS 7.4, tvOS 14.5' -define-availability 'SwiftStdlib 5.5:macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0' -define-availability 'SwiftStdlib 5.6:macOS 12.3, iOS 15.4, watchOS 8.5, tvOS 15.4' -define-availability 'SwiftStdlib 5.7:macOS 13.0, iOS 16.0, watchOS 9.0, tvOS 16.0' -define-availability 'SwiftStdlib 5.8:macOS 13.3, iOS 16.4, watchOS 9.4, tvOS 16.4' -define-availability 'SwiftStdlib 5.9:macOS 14.0, iOS 17.0, watchOS 10.0, tvOS 17.0' -define-availability 'SwiftStdlib 5.10:macOS 14.4, iOS 17.4, watchOS 10.4, tvOS 17.4, visionOS 1.1' -define-availability 'SwiftStdlib 6.0:macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0' -define-availability 'SwiftStdlib 6.1:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999, visionOS 9999'  -typo-correction-limit 10  -typecheck -module-name Client      -swift-version 5      /home/build-user/build/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/ModuleInterface/Output/distributed-actor.swift.tmp/Client.swift -I/home/build-user/build/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/ModuleInterface/Output/distributed-actor.swift.tmp
--
Exit Code: 1

Command Output (stderr):
--
/home/build-user/swift/test/ModuleInterface/distributed-actor.swift:70:11: error: CHECK: expected string not found in input
// CHECK: @available(iOS 9999, tvOS 9999, watchOS 9999, visionOS 9999, macOS 9999, *)
          ^
<stdin>:42:46: note: scanning from here
 public init(actorSystem system: ActorSystem)
                                             ^
<stdin>:43:2: note: possible intended match here
 @available(iOS 18.0, tvOS 18.0, watchOS 11.0, visionOS 2.0, macOS 15.0, *)
 ^

Input file: <stdin>
Check file: /home/build-user/swift/test/ModuleInterface/distributed-actor.swift

-dump-input=help explains the following input dump.

Input was:
<<<<<<
            .
            .
            .
           37:  public typealias SerializationRequirement = any Swift.Decodable & Swift.Encodable 
           38:  deinit 
           39:  nonisolated public var hashValue: Swift.Int { 
           40:  get 
           41:  } 
           42:  public init(actorSystem system: ActorSystem) 
check:70'0                                                  X error: no match found
           43:  @available(iOS 18.0, tvOS 18.0, watchOS 11.0, visionOS 2.0, macOS 15.0, *) 
check:70'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
check:70'1      ?                                                                           possible intended match
           44:  @_semantics("defaultActor") nonisolated final public var unownedExecutor: _Concurrency.UnownedSerialExecutor { 
check:70'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           45:  get 
check:70'0     ~~~~~
           46:  } 
check:70'0     ~~~
           47: } 
check:70'0     ~~
           48: @available(macOS 13.0, iOS 16.0, watchOS 9.0, tvOS 16.0, *) 
check:70'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            .
            .
            .
>>>>>>

--

********************
```

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci benchmark

**Pull request merged**
