### PR TITLE
Implement SE-0117

### PR DESCRIPTION
**Pull request by rjmccall**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

A smoke test on macOS does the following:
1. Builds the compiler incrementally.
2. Builds the standard library only for macOS. Simulator standard libraries and
   device standard libraries are not built.
3. lldb is not built.
4. The test and validation-test targets are run only for macOS. The optimized
   version of these tests are not run.

A smoke test on Linux does the following:
1. Builds the compiler incrementally.
2. Builds the standard library incrementally.
3. lldb is built incrementally.
4. The swift test and validation-test targets are run. The optimized version of these
   tests are not run.
5. lldb is tested.

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please smoke test.

**Comment by ultramiraculous** [comment]
10734326_526120340852998_1807512965_n

**Comment by gottesmm** [comment]
@swift-ci Please smoke test

**Comment by gottesmm** [comment]
(just restarting the build for John)

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Comment by rjmccall** [comment]
@swift-ci Please smoke test.

**Comment by rjmccall** [comment]
@swift-ci Please smoke test.

**Comment by rjmccall** [comment]
Okay, just the same failure about xctest.

@swift-ci Please test.

**Comment by rjmccall** [comment]
That's a real failure, and a suggestive one.  The new diagnostic is forcing a non-public method to be exposed just so the override can be open.  We're creating an inconsistency here.

After some discussion with Jordan and Doug, we're going to amend the proposal to lift that half of the "temporary" restriction, so open methods can override non-open ones.  This shouldn't be a problem for hierarchy analysis, which has to exhaustively find overrides anyway and can easily recognize when one is open.

**Comment by rjmccall** [comment]
So revised.

@swift-ci Please test.

**Comment by DougGregor** [comment]
The Linux failure is:

  fatal error: Attempt to invoke test on class TestNSAffineTransform with incompatible instance type XCTestCase: file /home/buildnode/jenkins/workspace/swift-PR-Linux@3/swift-corelibs-xctest/Sources/XCTest/Public/XCTestCase.swift, line 182

**Comment by DougGregor** [comment]
@swift-ci please smoke test Linux

**Comment by rjmccall** [comment]
Yeah, I've been looking into it.  This might be the first use of required inits; XCTest uses them heavily, and I'm worried we might be devirtualizing it (because it's not open) or something.

**Comment by rjmccall** [comment]
Okay, that seemed to fix it.  Trying to figure out a test case.  In the meantime,

@swift-ci Please test.

**Comment by rjmccall** [comment]
That last failure was a new test that hadn't been updated for 'open'.

@swift-ci Please smoke test.

**Comment by rjmccall** [comment]
I... don't think that's me?  I don't know how to interpret that failure.

**Comment by rjmccall** [comment]
Weird intermittent failure?

@swift-ci Please smoke test.

**Comment by rjmccall** [comment]
I should probably have renamed this pull request before actually merging it, huh.

**Comment by lattner** [comment]
LOL.  Congrats John!

**Comment by rjmccall** [comment]
:)

**Pull request merged**
