### PR TITLE
[SILOptimizer] Use BitfieldRef instead of invalidating SSAPrunedLiveness.

### PR DESCRIPTION
**Pull request by nate-chandler**
`SSAPrunedLiveness::invalidate` is used as though it reset the state of the instance it is called on.  Clients then reuse the instance with the expectation that it has been reset.  But since it has not been reset, this results in unexpected liveness results.

rdar://108627366

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by atrick — APPROVED** [review]
Thanks!

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Pull request merged**
