### PR TITLE
Fix SILParsing for forwarding ownership kind

### PR DESCRIPTION
**Pull request by meg-gupta**

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test Linux Platform

**Comment by meg-gupta** [comment]
@swift-ci test macOS Platform

**Review by eeckstein — APPROVED** [review]
lgtm!

Though, it would be nice to add the syntax definition to all the forwarding-accepting instructions in SIL.rst. But this is a minor thing - you can do that in a follow up commit.

**Pull request merged**
