### PR TITLE
[embedded] Workaround a build failure in non-assertion embedded stdlib builds, unblock CI

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please smoke test

**Review by glessard — APPROVED** [review]

**Comment by kubamracek** [comment]
@swift-ci please smoke test Windows platform

**Comment by glessard** [comment]
@swift-ci please smoke test Windows platform

**Comment by glessard** [comment]
(windows smoke test failure was actually a git failure.)

**Pull request merged**
