### PR TITLE
[ConstraintSystem] Remove `ConstraintSystemFlags::ReusePrecheckedType`.

### PR DESCRIPTION
**Pull request by hborla**
This change removes the last use of `ConstraintSystemFlags::ReusePrecheckedType` in operator code completion, and removes the option altogether from the constraint system.

Now that operator code completion uses an opaque value placeholder with the pre-checked type, code completion no longer needs to send a type checked AST through the constraint system, which was very brittle. Opaque value placeholder expressions were designed to be used as a placeholder for a fully type checked expression, making this a better approach for code completion paths that haven't yet been ported to solver-based completion.

### CODE REVIEW

**Review by xedin — APPROVED** [review]
Looks great!

**Comment by xedin** [comment]
@swift-ci Please SourceKit stress test

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by hborla** [comment]
Heh, looks like the SourceKit stress test "failed" because it expected https://github.com/apple/swift/issues/58891 to fail, but it was fixed by https://github.com/apple/swift/pull/59740

**Review by ahoppen — APPROVED** [review]
😍 One step closer to never type checking an expression twice.

**Pull request merged**
