### PR TITLE
[gardening] Change `static private` to `private static` for consistency

### PR DESCRIPTION
**Pull request by ikesyo**
Refs: #15182, #15153

Before the changes:

- `git grep "private static " | wc -l`: 97
- `git grep "static private " | wc -l`: 5

### CODE REVIEW

**Comment by ikesyo** [comment]
@swift-ci smoke test

**Comment by ikesyo** [comment]
@swift-ci smoke test

**Comment by jrose-apple** [comment]
Please don't do this to test files; some of them are testing that unusual orders still produce expected results!

**Comment by ikesyo** [comment]
Okay, sorry for bothering you 😓

**Comment by jrose-apple** [comment]
Ah, thank you in general for cleaning things up! It's just test files that I'm concerned about.

**Pull request closed without merging**
