### PR TITLE
[BatchMode] Rename FrontendInputs::AllFiles to AllInputs, etc

### PR DESCRIPTION
**Pull request by davidungar**
Renaming from File to Input (where the files are inputs), in preparation for batch mode.

### CODE REVIEW

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Review by jrose-apple — APPROVED** [review]

**Comment by davidungar** [comment]
@swift-ci please smoke test linux platform

**Pull request merged**
