### PR TITLE
 Move Generics.rst to archive folder

### PR DESCRIPTION
**Pull request by AgranatMarkit**
Update Generics.rst using modern Swift syntax

### CODE REVIEW

**Review by slavapestov — APPROVED** [review]

**Comment by CodaFi** [comment]
This seems to be a historic document that lays down rationales for technical decisions. I don't think we should alter the code here, I think we should move it under the `archive` directory and create a new document that provides more a more up-to-date view.

**Comment by CodaFi** [comment]
In fact, Slava has already committed [such a document](https://github.com/apple/swift/tree/main/docs/Generics)

**Comment by AnthonyLatsis** [comment]
@AgranatMarkit Could you revert all the changes to `Generics.rst` — except any typos — now that we've moved to the under the `archive` dir.?

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by CodaFi** [comment]
@AgranatMarkit Please resolve the merge conflict here.

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Pull request merged**
