### PR TITLE
[RemoteMirror] Update interop to handle 4.2 libraries.

### PR DESCRIPTION
**Pull request by mikeash**
The Remote Mirror interop header now accepts an arbitrary number of remote mirror libraries so that it can have 4.1, 4.2, and 5.0 loaded side by side.

rdar://problem/45808282

### CODE REVIEW

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci

**Comment by mikeash** [comment]
@swift-ci please smoke test and merge

**Comment by mikeash** [comment]
@swift-ci please smoke test and merge

**Comment by alexshap** [comment]
Sorry about the disturbance, if I'm not mistaken the script test.py refers to the source file test.swift
(it looks like the old files test4.swift, test5.swift were removed in https://github.com/apple/swift/commit/47be50cccc6fcfd0c5274185f28d75ea8eae026c#diff-fec5f6f30e172e9e11d336da7526c693 ), but I don't see test.swift (even on the master branch) anywhere, has it been committed / removed separately for some reason or maybe I'm missing something ?

**Comment by mikeash** [comment]
Good catch! I apparently just missed adding the file to git. Fortunately I still have it locally, so I was able to add it in. Here's the PR with it: https://github.com/apple/swift/pull/23556

Thank you for pointing this out.

**Pull request merged**
