### PR TITLE
[6.0][Concurrency] Fix preconcurrency downgrade behavior for `Sendable` closures and generic requirements.

### PR DESCRIPTION
**Pull request by hborla**
- **Explanation**: Sendable violations inside `@preconcurrency @Sendable` closures, or not satisfying a `Sendable` conformance requirement of a `@preconcurrency` generic declaration, should be suppressed in minimal checking, and diagnosed as warnings under complete checking, including the Swift 6 language mode. This change fixes an issue where warnings were still produced in minimal checking, and errors were still produced under -swift-version 6, which means that libraries cannot stage in new Sendable annotations if their clients have already migrated to Swift 6.
- **Scope**: This only impacts the diagnostic behavior of `@preconcurrency` declarations with `@Sendable` annotations or `where T: Sendable` generic requirements.
- **Issues**: rdar://138535438, rdar://139234188, https://github.com/swiftlang/swift/issues/76652
- **Original PRs**: https://github.com/swiftlang/swift/pull/77459, https://github.com/swiftlang/swift/pull/77510
- **Risk**: Low. While this change required a little bit of plumbing for whether a `Sendable` annotation was on a `@preconcurrency` declaration, the only effect of this change is downgrading some concurrency diagnostics.
- **Testing**: Added new CI tests.

### CODE REVIEW

**Comment by hborla** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
```
/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-release/6.0/swift/test/Concurrency/predates_concurrency_swift6.swift:183:25: error: expected note not produced
class NotSendable {} // expected-note 2 {{class 'NotSendable' does not conform to the 'Sendable' protocol}}
                    ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    
/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-release/6.0/swift/test/Concurrency/predates_concurrency_swift6.swift:190:6: error: expected warning not produced
  // expected-warning@-1 {{type 'NotSendable' does not conform to the 'Sendable' protocol}}
~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by hborla** [comment]
@swift-ci please test

**Comment by hborla** [comment]
@swift-ci please test

**Review by airspeedswift — APPROVED** [review]

**Review by DougGregor — APPROVED** [review]

**Comment by hborla** [comment]
@swift-ci please test

**Pull request merged**
