### PR TITLE
[5.5][Dependency Scanning] Include initial PCM arguments on Clang module dependency details

### PR DESCRIPTION
**Pull request by artemcm**
Cherry-pick of https://github.com/apple/swift/pull/39397
-----------------------------------------------------------------------------
- **Explanation**: Doing so will allow clients to know which Swift-specific PCM arguments are already captured from the scan that first discovered this module. SwiftDriver, in particular, will be able to use this information to avoid re-scanning a given Clang module if the initial scan was sufficient for all possible sets of PCM arguments on Swift modules that depend on said Clang module.
- **Risk**: Low
- **Reviewed by**: @nkcsgexi 
- **Testing**: Automated test modified to capture and exercise new behavior.

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci please test

**Review by nkcsgexi — APPROVED** [review]

**Comment by artemcm** [comment]
@swift-ci please test Windows platform

**Comment by artemcm** [comment]
@swift-ci please test

**Review by airspeedswift — APPROVED** [review]

**Comment by artemcm** [comment]
@swift-ci please test Windows platform

**Comment by artemcm** [comment]
@swift-ci please test Windows platform

**Pull request merged**
