### PR TITLE
Update swift-collections to 1.1.3

### PR DESCRIPTION
**Pull request by kateinoigakukun**
This updates the swift-collections dependency to 1.1.3, which includes a CMake fix for the WebAssembly target. "main", "next", and "rebranch" schemes are all updated.

### CODE REVIEW

**Comment by kateinoigakukun** [comment]
@swift-ci smoke test

**Comment by kateinoigakukun** [comment]
@swift-ci build toolchain

**Comment by kateinoigakukun** [comment]
@swift-ci smoke test macOS platform

**Review by MaxDesiatov — APPROVED** [review]

**Comment by glessard** [comment]
No new issues have cropped up with swift-collections 1.1.3, so merging this. Thanks!

**Comment by MaxDesiatov** [comment]
IIUC @shahmishal still needs to update some CI configuration to reflect the merged change. We usually keep PRs like this unmerged until his approval, unless CI configuration was updated already?

**Comment by glessard** [comment]
It's picked up automatically by the toolchain build as far as I can tell; is there some additional config for PR testing?

**Comment by MaxDesiatov** [comment]
I'm not sure, I only know there's additional configuration that needs to be done on CI manually, usually before or simultaneously with PRs that modify `update-checkout-config.json` are merged.

**Pull request merged**
