### PR TITLE
TypeDecoder: Be more forgiving of extra child nodes in demangled nominal types.

### PR DESCRIPTION
**Pull request by jckarter**
rdar://problem/40375014

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Comment by jckarter** [comment]
@DougGregor How's this look?

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Review by DougGregor — APPROVED** [review]
Nice catch, LGTM!

**Pull request merged**
