### PR TITLE
Re-apply "libSyntax: create a basic infrastructure for generating libSyntax entities by using Parser."

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@harlanhaskins have you found a good way to re-establish this?

**Comment by nkcsgexi** [comment]
@swift-ci Please test OS X platform

**Comment by harlanhaskins** [comment]
@nkcsgexi You should probably do a clean test.

**Comment by harlanhaskins** [comment]
@swift-ci please clean test

**Comment by shahmishal** [comment]
preset=buildbot,tools=RA,stdlib=DA
@swift-ci Please test macOS with preset

**Comment by shahmishal** [comment]
preset=buildbot,tools=RA,stdlib=DA
@swift-ci Please test macOS with preset

**Comment by shahmishal** [comment]
preset=buildbot,tools=RA,stdlib=DA
@swift-ci test macOS with preset

**Comment by shahmishal** [comment]
preset=buildbot,tools=RA,stdlib=DA
@swift-ci test macOS with preset

**Comment by shahmishal** [comment]
preset=buildbot,tools=RA,stdlib=DA

@swift-ci test macOS with preset

**Comment by shahmishal** [comment]
@swift-ci test macOS with preset

**Comment by nkcsgexi** [comment]
@swift-ci please clean test

**Pull request merged**
