### PR TITLE
[gardening] Use `!empty()` over `size() > 0`

### PR DESCRIPTION
**Pull request by ikesyo**
Similar to #14977

### CODE REVIEW

**Comment by ikesyo** [comment]
@swift-ci Please smoke test

**Comment by compnerd** [comment]
Please run git-clang-format over your patch, I think that it will help readability of the new code.

**Comment by ikesyo** [comment]
@compnerd Thanks for pointing it out. Just executed the tool. Could you please take another look?

**Comment by ikesyo** [comment]
@swift-ci Please smoke test

**Review by compnerd — APPROVED** [review]
LGTM

**Pull request merged**
