### PR TITLE
[WIP] Resilient stdlib

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please benchmark

**Comment by trentxintong** [comment]
@slavapestov Last night i checked, i think please benchmark is not working https://github.com/apple/swift/pull/2064

**Comment by slavapestov** [comment]
@trentxintong The benchmark results in the PR you linked look correct and complete to me -- what are you seeing?

**Comment by trentxintong** [comment]
@slavapestov I am expecting performance improvements and regressions which i measured on my local machine. If you look at https://ci.swift.org/job/swift-PR-osx-perf/30/ which is one of the jobs that produced the #s. Only one compiler is built, Should not we build 2 compilers, 1 with and 1 without the PR tested.

**Comment by slavapestov** [comment]
@trentxintong You're right... I only see SourceKit got recompiled.

**Comment by slavapestov** [comment]
And this PR just failed with:

    Undefined symbols for architecture x86_64:
      "swift::performSILGeneration(swift::FileUnit&, swift::SILOptions&, llvm::Optional<unsigned int>)", referenced from:
      void SourceKit::WorkQueue::DispatchData::callAndDelete<(anonymous namespace)::ASTProducer::getASTUnitAsync(SourceKit::SwiftASTManager::Implementation&, llvm::ArrayRef<llvm::IntrusiveRefCntPtr<SourceKit::ImmutableTextSnapshot> >, std::__1::function<void (llvm::IntrusiveRefCntPtr<SourceKit::ASTUnit>, llvm::StringRef)>)::$_2>(void*) in libSourceKitSwiftLang.a(SwiftASTManager.cpp.o)
    ld: symbol(s) not found for architecture x86_64

**Pull request closed without merging**
