### PR TITLE
build: explicitly execute `line-directive-tool` with Python3

### PR DESCRIPTION
**Pull request by compnerd**
The `line-directive-tool` is Python3 compliant.  Use the Python3
interpreter to execute this tool.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @drexin

**Review by drexin — APPROVED** [review]
LGTM, \cc @shahmishal

**Review by shahmishal — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Pull request merged**
