### PR TITLE
Some cleanup of SIMDVector and SIMDVectorTypes source files [NFC]

### PR DESCRIPTION
**Pull request by stephentyrone**
Bring formatting closer in line with the rest of the standard lib, remove "public" from extensions (moving it onto the contents defined therein). Restore Swift project headers that were apparently lost at some point.

"NFC," he said ...

### CODE REVIEW

**Comment by stephentyrone** [comment]
@swift-ci please test

**Comment by stephentyrone** [comment]
@swift-ci please test

**Comment by stephentyrone** [comment]
@swift-ci please smoke test

**Review by lorentey — APPROVED** [review]
Try as I might, I couldn't find any FC! 

Nitpick: in new code we usually have no space before colons in conformance lists and where clauses.

**Comment by stephentyrone** [comment]
@lorentey Swift-CI confirms the change is indeed NF (but so is everything, so it's not my fault).

**Comment by stephentyrone** [comment]
@swift-ci please smoke test linux

**Comment by stephentyrone** [comment]
@lorentey I'll fix the space issue on the sims-additions PR.

**Pull request merged**
