### PR TITLE
[stdlib] Drop @inlinable if @inline(never).

### PR DESCRIPTION
**Pull request by milseman**
Aggressively remove all `@inlinable` from any function that's
`@inline(never)` to see the impact.

`@inlinable @inline(never)` is a potential code smell. While it might
expose some optimization and specialization opportunities to the
optimizer, it's most commonly a sign that more thought is needed.

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please test compiler performance

**Comment by airspeedswift** [comment]
Hmm, that laughing emoji looks more like I was happy to see those build benchmarks, as opposed to a "lol, it got slower in debug but faster in release" kinda thing.

**Review by lorentey — APPROVED** [review]
Some of these could benefit from `@effects` declarations, but they don't seem performance critical. I  don't see why benchmarks disagree...  Is there more ARC traffic?

**Comment by milseman** [comment]
You might be right about the `@effects` being necessary now that the optimizer cannot peer into their bodies.

**Comment by milseman** [comment]
@eeckstein am I reading the results correctly? i.e. this change results in a 2% size reduction in the source compatibility suite and 6% compilation time improvement when the source compatibility suite is built with optimizations? Or, is "release/debug" referring to the standard library being built in release/debug and the reported metrics concern the stdlib itself?

**Comment by eeckstein** [comment]
yes, these are improvements for the source compatibility projects.
debug/release refers to the build configuration of the source compatibility projects and not of the stdlib. We always use an optimized stdlib

**Comment by milseman** [comment]
(to get a second opinion before I dig into any specific regression)

@swift-ci please smoke benchmark

**Comment by milseman** [comment]
I restored a handful of the `@inlinable` annotations, which reversed the `FilterEvenUsingReduce` slow down. @eeckstein can you help us understand how to better annotate these with (preferably) `@effects`, as this is quite a bit of code to emit into the user module.

**Comment by milseman** [comment]
@swift-ci please smoke benchmark

**Comment by milseman** [comment]
@swift-ci please smoke test compiler performance

**Comment by milseman** [comment]
Still some perf regressions. We know that we can reduce the size of the source compatibility suite by un-inlinable the following:

- _copyToNewBuffer
- _forceCreateUniqueMutableBuffer
- _forceCreateUniqueMutableBuffer
- _arrayOutOfPlaceUpdate

Even without those it's still worth it so far from a compilation time perspective, if we can fix the last regressions.

**Comment by milseman** [comment]
@swift-ci please smoke benchmark

**Comment by milseman** [comment]
@swift-ci please test Linux Platform

**Comment by milseman** [comment]
Filed [SR-7556](https://bugs.swift.org/browse/SR-7556) for StrToInt regression. 

"FrequenciesUsingReduceInto" does not repro locally, might be spurious.

The StringBuilder and StringInterpolationSmall produces identical or nearly-identical binaries, yet I can consistently repro them. String append is... very complex and needs a 2-way visitation pattern. 

String interpolation seems to involve some sub-optimizal printing-related code, which we want to work on with a reworking of String interpolation. Also, for some reason, both before and after misses @shajrawi's peephole. Filed [SR-7557](https://bugs.swift.org/browse/SR-7557) which has 6 missed peepholes that contribute to code size and (to a lessor extent) perf.

**Comment by milseman** [comment]
@swift-ci please clean test Linux Platform

**Comment by milseman** [comment]
@lancep any idea why changing some `@inlinable` annotations would cause crashes on Linux? Is there a chance that something involving lazy bridging is not properly factored out, but the optimizer just happened to do the right thing when the method body was exposed?

https://ci.swift.org/job/swift-PR-Linux/4541/consoleFull#289305111ba62d58e-7248-467b-91e0-c7508d5cf947

**Comment by lancep** [comment]
I ran the tests on a linux box and they repeatedly passed for me. I'll try running them again here.

**Comment by lancep** [comment]
@swift-ci please test Linux platform

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
I still want to drop more, but this should be merged.

**Pull request merged**
