### PR TITLE
Fix and cleanup build-script product source discovery

### PR DESCRIPTION
**Pull request by hughbe**
Always good to move logic from build-script-impl to build-script!

### CODE REVIEW

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by hughbe** [comment]
Let's get everything building too just to make sure

**Comment by hughbe** [comment]
@swift-ci please test

**Comment by hughbe** [comment]
Two separate issues here, both seemingly unrelated?
******************** TEST 'Swift-Unit :: Syntax/SwiftSyntaxTests/ThreadSafeCachingTests.ReturnGetExpression' FAILED ********************


/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/test/IRGen/struct_layout.sil:18:8: error: expected string not found in input

**Comment by hughbe** [comment]
@swift-ci please test

**Comment by hughbe** [comment]
@swift-ci please test

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by hughbe** [comment]
@swift-ci please python lint

**Comment by hughbe** [comment]
@swift-ci please python lint

**Comment by erg** [comment]
Except now it's now in six files instead of one! Merging anyway 👍

**Comment by hughbe** [comment]
Unfortunately it's necessary the way it's set up today. May look like annoying duplication but will simplify things if/when we move to python entirely

**Pull request merged**
