### PR TITLE
[Index][SR-9567] Allow unavailable decls to be walked

### PR DESCRIPTION
**Pull request by rockbruno**
Expressions inside availability clauses weren't being walked, which prevented sourcekitd from indexing them.

Resolves [SR-9567](https://bugs.swift.org/browse/SR-9567) - the ticket has an ongoing discussion about the implications.

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Review by nkcsgexi — APPROVED** [review]
LGTM! though I'm not sure if there're particular reasons we don't want to index unavailable declarations. cc: @akyrtzi @nathawes

**Comment by akyrtzi** [comment]
As @benlangmuir mentioned in https://bugs.swift.org/browse/SR-9567, there was a good reason that we ignored unavailable decls, so we shouldn't revert it without addressing the original reason, but I need some time to think about it before I make some suggestion.

**Comment by CodaFi** [comment]
@rockbruno If you're still interested in this, could you rebase this pull request?
@akyrtzi Has your thinking changed on this?

**Comment by akyrtzi** [comment]
@nathawes please take a look.

**Comment by nathawes** [comment]
From the SR it sounds like this check was intended to prevent indexing unavailable declarations coming from a module because they and their contents aren't printed in the module's interface, so there's no definition to jump to. 

@rockbruno I think you can still cover the original use case by refining the check to avoid walking into unavailable decls coming from modules (as opposed to source files) rather than removing it:
```
if (IsModuleFile && AvailableAttr::isUnavailable(D))
      return false;
```
That way we'll still get a definition for unavailable decls coming from source code (plus occurrences for everything they use), but not for those coming from modules. If those modules aren't system modules (like the stdlib or system frameworks) we'll still eventually get index data for their decls (unavailable or otherwise) when we index their source.

**Comment by rockbruno** [comment]
Sorry for the delay folks, I've rebased the repo with the change 🙂

**Review by nathawes — APPROVED** [review]
Looks good to me – thanks!

**Comment by nathawes** [comment]
@swift-ci please test

**Comment by nathawes** [comment]
@rockbruno Looks like `test/SourceKit/Indexing/index.swift.response` needs to be updated too:

```
******************** TEST 'Swift(macosx-x86_64) :: SourceKit/Indexing/index.swift' FAILED ********************
Script:
--
: 'RUN: at line 1';   /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/bin/sourcekitd-test -req=index /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/test/SourceKit/Indexing/index.swift -- -Xfrontend -serialize-diagnostics-path -Xfrontend /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/SourceKit/Indexing/Output/index.swift.tmp.dia /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/test/SourceKit/Indexing/index.swift | /usr/bin/python /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/test/SourceKit/Inputs/sourcekitd_path_sanitize.py | sed -e 's/key.usr: \".*\"/key.usr: <usr>/g' > /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/SourceKit/Indexing/Output/index.swift.tmp.response
: 'RUN: at line 2';   diff -u /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/test/SourceKit/Indexing/index.swift.response /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/SourceKit/Indexing/Output/index.swift.tmp.response
--
Exit Code: 1

Command Output (stdout):
--
--- /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/test/SourceKit/Indexing/index.swift.response	2020-01-06 10:58:02.000000000 -0800
+++ /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/SourceKit/Indexing/Output/index.swift.tmp.response	2020-01-06 14:39:04.000000000 -0800
@@ -1522,6 +1522,27 @@
     },
     {
       key.kind: source.lang.swift.decl.class,
+      key.name: "AlwaysUnavailableClass",
+      key.usr: <usr>,
+      key.line: 184,
+      key.column: 7,
+      key.entities: [
+        {
+          key.kind: source.lang.swift.decl.function.constructor,
+          key.usr: <usr>,
+          key.line: 184,
+          key.column: 7,
+          key.is_implicit: 1
+        }
+      ],
+      key.attributes: [
+        {
+          key.attribute: source.decl.attribute.available
+        }
+      ]
+    },
+    {
+      key.kind: source.lang.swift.decl.class,
       key.name: "ConditionalUnavailableClass1",
       key.usr: <usr>,
       key.line: 188,

--
```

********************
```

**Comment by rockbruno** [comment]
Updated. Sorry for that!

**Comment by nathawes** [comment]
@swift-ci please test

**Comment by nathawes** [comment]
OS X failure seems unrelated. Trying again 🤞

**Comment by nathawes** [comment]
@swift-ci please test OS X Platform

**Comment by nathawes** [comment]
@swift-ci please test and merge

**Comment by nathawes** [comment]
@swift-ci please smoke test Linux

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by CodaFi** [comment]
Shepherded in the linked PR. Thanks!

**Pull request closed without merging**
