### PR TITLE
Makes the DispatchIO initializer that accepts a path failable, reflec…

### PR DESCRIPTION
**Pull request by ktopley-apple**
…ting the fact that a relative or non-existent path is invalid.

(Radar 28564226)
rdar://problem/28564226

### CODE REVIEW

**Comment by ktopley-apple** [comment]
@mwwa @moiseev @jrose-apple @das please review

**Comment by ktopley-apple** [comment]
@swift-ci please test

**Comment by jrose-apple** [comment]
LGTM, but you should have test cases compiled in both Swift 3 mode and Swift 4 mode to verify that both are working correctly.

**Review by mwwa — APPROVED** [review]

**Comment by ktopley-apple** [comment]
@swift-ci please merge

**Comment by jrose-apple** [comment]
I don't think we have a "please merge", but please do not merge without test cases.

**Comment by ktopley-apple** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
@swift-ci please test

**Pull request merged**
