### PR TITLE
Revert "Don't import C++ class members that are protected or private"

### PR DESCRIPTION
**Pull request by martinboehme**
Reverts apple/swift#30233 -- it broke Windows bots.

### CODE REVIEW

**Comment by gribozavr** [comment]
@swift-ci Please smoke test

**Comment by CodaFi** [comment]
I don't think we need to revert if you can clean up the test for Windows. But if it's easier this way, then you should wait for the merge of #30532 which will clear up the Linux bots.

**Comment by gribozavr** [comment]
Attempting to fix Windows in #30536.

**Comment by gribozavr** [comment]
Merged a fix forward in #30536.

**Pull request closed without merging**
