### PR TITLE
[AutoDiff] Rename 'AutoDiffIndexSubset' to 'IndexSubset'.

### PR DESCRIPTION
**Pull request by rxwei**
Per @DougGregor's review comment (https://github.com/apple/swift/pull/27555#discussion_r333757205), `AutoDiffIndexSubset` data structure could have a more general name. We rename it to `IndexSubset` and move it to its own file.

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Review by dan-zheng — APPROVED** [review]

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Pull request merged**
