### PR TITLE
Fix a bunch of performance issues in Function Signature Optimizations

### PR DESCRIPTION
**Pull request by gottesmm**
Found a bunch of pretty bad performance problems in Function Signature Optimizations. Not going to say how they got here... but I am going to fix them real quick.

Specifically we were copying around ADTs just to read them. There is no excuse for that.

rdar://41146023

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Review by shajrawi — COMMENTED** [review]
LGTM!

**Pull request merged**
