### PR TITLE
[OpaqueValues] Fix closure handling.

### PR DESCRIPTION
**Pull request by nate-chandler**
Rewrote and tested all currently emittable variations of closure handling for opaque values.

In order to do that, made all types with packs be indirect even in opaque values for now.  This is motivated by the fact that getting from/setting to a pack currently requires addresses which aren't materialized for tuples.  In the fullness of time, these values should be direct in opaque values mode, but for now it can be postponed.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
Timeouts and a UPASS in the debug source compat failure.

**Comment by nate-chandler** [comment]
@swift-ci Please Test Source Compatibility Debug

**Comment by nate-chandler** [comment]
@swift-ci Please Test Source Compatibility Debug

**Comment by nate-chandler** [comment]
Same source compat failures as in rdar://114339248 .

**Review by atrick — APPROVED** [review]
Wow that's a lot! I can't vouch for the correctness of emitCaptures by code inspection alone, but I'm amazed by the thoroughness of the unit tests.

**Pull request merged**
