### PR TITLE
tests: update sil_combine_enum.sil testfile to fix SIL parse error

### PR DESCRIPTION
**Pull request by eeckstein**

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci smoke test and merge

**Comment by davezarzycki** [comment]
Verified

**Comment by davezarzycki** [comment]
The linux failure seems spurious

@swift-ci smoke test linux

**Comment by davezarzycki** [comment]
Still seems like a spurious failure

@swift-ci clean smoke test linux

**Comment by compnerd** [comment]
@swift-ci please test windows platform

**Comment by compnerd** [comment]
Seems that smoke test don’t trigger windows (cc @shahmishal)

**Comment by davezarzycki** [comment]
I merged this to honor @eeckstein's original "test and merge" CI request and because I verified this fix locally.

**Comment by eeckstein** [comment]
@davezarzycki Thanks!

**Comment by shahmishal** [comment]
> Seems that smoke test don’t trigger windows (cc @shahmishal)

```
@swift-ci smoke test and merge
```
Does not trigger Windows build, because automation will merge the PR with out checking if Windows passed or failed because it only checks required PR checks.

**Pull request merged**
