### PR TITLE
[SE-0248] String Gaps

### PR DESCRIPTION
**Pull request by milseman**
[pitch thread](https://forums.swift.org/t/pitch-string-gaps-and-missing-apis/20984)

[SE-0248](https://github.com/apple/swift-evolution/blob/master/proposals/0248-string-gaps-missing-apis.md)

* 8 simple APIs on Unicode’s various encodings
* 2 generic initializers for string indices and ranges of indices
* Substring.base, equivalent to Slice.base
* Make Character.UTF8View and Character.UTF16View public
* Add Unicode.Scalar.UTF8View

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please benchmark

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
What?
```
/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/llvm/tools/clang/lib/DirectoryWatcher/DirectoryWatcher-linux.inc.h:95:23: error: use of undeclared identifier 'RetryAfterSignal'
```

**Comment by tkremenek** [comment]
The evolution proposal for this change has been accepted.

**Comment by tkremenek** [comment]
@swift-ci clean test

**Comment by tkremenek** [comment]
@swift-ci clean test

**Comment by milseman** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/swift/test/stdlib/StringIndex.swift:205:8: error: no such module 'Foundation'

😕

**Comment by milseman** [comment]
Ah, so it seems we need to guard any of that functionality

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please test OS X platform

**Comment by milseman** [comment]
Jenkins crashed.

@swift-ci please test OS X platform

**Pull request merged**
