### PR TITLE
[CS] A couple of CSApply cleanups

### PR DESCRIPTION
**Pull request by hamishknight**
Generalize the delayed type-checking of local decls, factor out an abstract base class for target rewriting, and rip out the delaying logic for multi-statement closures.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
Hrm looks like we can't add the assertion in 59cb282a63dcbe2714fd380c5f47211e7e465415 quite yet, dropped it.

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Review by xedin — APPROVED** [review]

**Pull request merged**
