### PR TITLE
Fixes for stored property initializers

### PR DESCRIPTION
**Pull request by kavon**
There are two related fixes in this PR:

- Stored properties that are members of a type previously had the isolation applied to the var carry-over to the initializing expression. This can create an impossible-to-satisfy isolation requirement on the non-delegating initializers of the type. In line with the solution for this in SE-327, this PR removes that carry-over of isolation, making them effectively a nonisolated context. While this will cause a source break, the isolation was not being respected anyway. The workaround for this is to just not use the short-hand and initialize those properties in the type's initializer. If your type has an impossible constraint, then that problem should become apparent while trying to implement this workaround. (rdar://84225474)
- In some instances, static properties of a type marked with MainActor were not having their initializing expression run on the main thread. That has been resolved in this PR. (Resolves #57549, rdar://83411416)

### CODE REVIEW

**Comment by kavon** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]
Looks great, thanks!

**Comment by kavon** [comment]
@swift-ci please test and merge

**Comment by kavon** [comment]
@swift-ci please test and merge

**Pull request merged**
