### PR TITLE
Update determination of "too complex" expression to take time into account.

### PR DESCRIPTION
**Pull request by rudkx**
By default, end expression type checking after the elapsed process time
is more than 60 seconds for the current expression. This threshold can
be overridden by using `-solver-expression-time-threshold=<seconds>`.
    
Resolves rdar://problem/32859654

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
Is this a monotonic timer?

**Comment by rudkx** [comment]
@slavapestov Well, it ought to be. Why do you ask?

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Pull request merged**
