### PR TITLE
[Python] Replace global linting excludes with local line-level excludes ("noqa")

### PR DESCRIPTION
**Pull request by practicalswift**
#### What's in this pull request?

Replace the project global linting rule excludes (as defined in `.pep8`) with fine-grained `# noqa` annotations.

By using `noqa` annotations the excludes are made on a per line basis instead of globally.

These annotations are used where we make deliberate deviations from the standard linting rules.

To lint the Python code in the project:

```
  $ flake8
```

To install `flake8`:

```
  $ pip install flake8
```

See https://flake8.readthedocs.org/en/latest/ for details.

To enable checking of the PEP-8 naming conventions, install the optional extension `pep8-naming`:

```
  $ pip install pep8-naming
```

To enable checking of blind `except:` statements, install the optional extension `flake8-blind-except`:

```
  $ pip install flake8-blind-except
```

To enable checking of import statement order, install the optional extension `flake8-import-order`:

```
  $ pip install flake8-import-order
```
#### Resolved bug number: –

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by practicalswift** [comment]
@swift-ci Please test again - I think the build failures were unrelated to this PR :-)

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by practicalswift** [comment]
@swift-ci Please test again - I think the build failures were unrelated to this PR :-)

**Comment by gribozavr** [comment]
@swift-ci Please test

**Pull request merged**
