### PR TITLE
[ClangImporter] Allow direct explicit load when implicit module is enabled

### PR DESCRIPTION
**Pull request by cachemeifyoucan**
Improve clang importor so it can directly load explicit module even implicit module is enabled. This is a special configuration used by lldb because lldb sometimes need to load additional modules when binding external types. This provide the path in clang importer that can load explicit module without locating the clang module map, while fallback to module map lookup when implicit module is needed.

### CODE REVIEW

**Comment by cachemeifyoucan** [comment]
@swift-ci please smoke test

**Comment by cachemeifyoucan** [comment]
@swift-ci please test

**Comment by adrian-prantl** [comment]
We _know_ that there were situations where it was already doing this — which specific (new) situation does this address?

**Comment by cachemeifyoucan** [comment]
> We _know_ that there were situations where it was already doing this — which specific (new) situation does this address?

Let me know if you want me to look into it but I don't know how current lldb loads clang explicit module. If I just take all the command line options from the lldb logs and send to clang driver, every `-fmodule-files=` flag is dropped when converting to cc1 flag. I might need to step through the lldb to figure out how it finds the already built modules. Maybe @kastiglione knows?

**Comment by adrian-prantl** [comment]
> Let me know if you want me to look into it but I don't know how current lldb loads clang explicit module. If I just take all the command line options from the lldb logs and send to clang driver, every -fmodule-files= flag is dropped when converting to cc1 flag.

Since you're actively making changes here, I think it would be _great_ if you could clarify this and potentially document your findings. There's an explicit modules test in `test/API/lang/swift/ExplicitModules`.

**Comment by cachemeifyoucan** [comment]
> We know that there were situations where it was already doing this — which specific (new) situation does this address?

I think I figured out the difference. The behavior is that without this change, clang needs to find the module map for the module to import, even `-fmodule-file` is passed on the command-line. That means lldb need to inherit the entire full search paths to find all clang module maps, just to import prebuilt ones.

After this change, swift clang importer will just skip the module map lookup stage and directly importing explicit modules if those exists, and only fallback to module map lookup when an implicit build is needed.

**Comment by cachemeifyoucan** [comment]
@swift-ci please smoke test

**Comment by cachemeifyoucan** [comment]
Commit message updated to address the finding.

**Review by adrian-prantl — APPROVED** [review]

**Pull request merged**
