### PR TITLE
Revert "Merge pull request #37114 from apple/revert-36377-NewDriverDefault"

### PR DESCRIPTION
**Pull request by artemcm**
This reverts commit 937e1a365cf1bfebdb88c2d16026fdba736757b4, reversing
changes made to c2dc8e3d0748597e2c964a48aaeb9c20426f618f.

A change originally merged in https://github.com/apple/swift/pull/36377 got reverted in: https://github.com/apple/swift/pull/37114

The reason for this is because SwiftDriver's CMake build behaves differently when using CMake Version <3.17 and some developers who were using an older CMake started hitting errors.

This PR reverts the revert, bringing back the new driver as the default installation.

Before it gets merged one of two things needs to happen:
- Either bump the minimum required CMake version of Swift to 3.17 or 3.18 (Forum thread discussion: https://forums.swift.org/t/bump-cmake-version-to-3-18)
- Introduce manual workarounds for the CMake issue encountered by the driver build when using older CMake. (paths for an executable need to be specified manually)

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test Windows platform

**Comment by artemcm** [comment]
With: https://github.com/apple/swift-driver/pull/619
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test Windows platform

**Comment by gottesmm** [comment]
@swift-ci test macOS platform

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@shahmishal looks like PR bots on Linux have cmake 3.16, not cmake 3.17.

**Comment by gottesmm** [comment]
Actually, I am incorrect. That is the cmake that we are building now. I am going to update to a newer cmake using update-checkout.

**Comment by gottesmm** [comment]
Once #37210 lands, we should be good to merge this. @shahmishal would be good to update the Linux bots as well so we don't build this. But I think for now I want to unblock this.

**Comment by artemcm** [comment]
WIth https://github.com/apple/swift-driver/pull/619
@swift-ci please test

**Comment by artemcm** [comment]
WIth apple/swift-driver#619
@swift-ci please test macOS platform

**Pull request merged**
