### PR TITLE
Build position independent Linux binaries.

### PR DESCRIPTION
**Pull request by gmilos**
This PR fixes Linux executable to be position independent. It does so by adding `-pie` flag to `clang++` linker invocation.

Resolves [SR-5405](https://bugs.swift.org/browse/SR-5405).

### CODE REVIEW

**Comment by alblue** [comment]
@swift-ci please smoke test

**Comment by jrose-apple** [comment]
Do we need to compile the stdlib with -pie as well?

**Comment by gmilos** [comment]
@jrose-apple I'm assuming you meant `-fPIC` (`-pie` applies to executables). Standard library is compiled `-fPIC` already. In fact I'd be surprised if Linux allowed non `-fPIC` `.so`-s at all.

**Comment by jrose-apple** [comment]
Ah, I just straight-up forgot how these flags work. If we're already doing PIC everywhere then okay!

@swift-ci Please smoke test

**Comment by alblue** [comment]
@jrose-apple @jckarter can this be merged?

**Comment by jckarter** [comment]
LGTM, thanks!

**Pull request merged**
