### PR TITLE
Kill canonical mangling signature

### PR DESCRIPTION
**Pull request by slavapestov**
This PR builds upon my previous PRs which removed `AllArchetypes`, https://github.com/apple/swift/pull/4451 and https://github.com/apple/swift/pull/4524.

Now that `AllArchetypes` is gone, there were a few places the old order of generic requirements in a signature still came up. In particular, we had two ways of building generic signatures:
- we would first build a "maximal" signature containing all conformance requirements on all associated types nested in our generic parameters
- we had a second `getCanonicalManglingSignature()` which dropped requirements that could be inferred from protocol declarations, and also attempted to pick representatives of same-type classes in a more canonical way -- this was used for mangling, and for building substitution lists

This PR merges the additional canonicalization performed by the second step into the first step, so all generic signatures are minimized now, and representatives of same-type classes are always canonical according to a total order among archetypes.

This eliminates some code duplication and also uncovers a few places in the optimizer where we would make assumptions about the order of requirements in a signature. In these places, we would build substitution lists by hand. This PR changes the optimizer to use the new utility methods on GenericSignature where appropriate, which simplifies the code and makes it more robust.

For those following along, here are the next steps, but I can't promise I'll be working on these in any order or time frame:
- While substitution lists no longer contain conformances for nested types that can be derived from their parent types, they still contain the redundant nested types themselves. The main remaining difficulty here is some issues with how witness thunk emission uses archetypes -- I cleaned this up some to facilitate generic signature canonicalization, but more problems remain.
- Fixing the previous problem properly requires re-working the `ProtocolConformance` structures produced by the type checker to use interface type substitutions rather than archetypes.
- The code for producing a witness thunk's generic signature, as well as the SIL optimizer code for handling the abstraction change from call-site substitutions to method substitutions, have a similar structure and could be factored out into a `SubstitutedGenericSignature` structure. This might simplify some logic in IRGen for emitting metadata sources for protocol methods too.
- `AbstractTypeParamDecl::getArchetype()` is still there, but it's on its way out.
- `PolymorphicFunctionType` will go soon, and in the longer term, non-interface types in `ValueDecl`s.
- Once `ValueDecl`s no longer have archetypes appearing in their signatures, `AssociatedTypeType` can go.
- Another benefit of moving `ValueDecl`s to interface types completely is that we can stop serializing archetypes and `GenericEnvironment`s in the AST.
- SIL function bodies will still reference archetypes, but we can serialize archetypes in SIL function bodies by mapping them to interface types and serializing those, and then building a brand new `GenericEnvironment` after deserializing, and mapping them back to archetypes. This will eliminate a bunch of code for serializing `GenericEnvironment`s and archetypes.
- We don't really need to serialize `GenericParamList` either. It comes up in a few places in the AST printer and code completion, but we might be able to get away with just printing the generic signature instead, assuming enough sugar is retained. All other usages can be converted to look at `GenericSignature::getInnermostGenericParams()` instead.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
This is a ton of commits. Do any of them make sense to land separately?

(I appreciate you breaking up the logical changes, though!)

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please benchmark

**Comment by slavapestov** [comment]
@swift-ci Please performance test

**Comment by slavapestov** [comment]
@Please benchmark macOS

**Comment by slavapestov** [comment]
@swift-ci Please benchmark macOS

**Comment by shahmishal** [comment]
@swift-ci Please benchmark

**Pull request merged**
