### PR TITLE
stdlib: initialize va_list variables (NFC)

### PR DESCRIPTION
**Pull request by compnerd**
This silences `-Wuninitialized` warnings from clang when building the
swift stdlib for Windows ARM.  NFC.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Review by jrose-apple — CHANGES_REQUESTED** [review]
va_list is not a pointer type on all platforms.

**Comment by compnerd** [comment]
@jrose-apple mmm yeah ... struct type on ARMv7 at least.  Ugh.  I guess that I can do this under a `#if defined(_WIN32)` .. bleh

**Comment by jrose-apple** [comment]
I'm surprised `va_start` isn't sufficient to quiet -Wuninitialized. Anyway, I'd prefer you silence the warning, since not initializing a va_list is the most correct thing to do.

**Comment by compnerd** [comment]
@jrose-apple well, doing `-Wno-uninitialized` would be overly aggressive.  Should I sprinkle some pragmas to ignore this?  FWIW, I completely agree that `va_list` initialization is dumb.

**Comment by jrose-apple** [comment]
Yeah, pragmas sound like the least bad option, if not a great one. Maybe also a bug against Windows Clang to special case va_list.

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Review by jrose-apple — APPROVED** [review]

**Pull request merged**
