### PR TITLE
On Linux, make swift_reportError always print backtraces

### PR DESCRIPTION
**Pull request by kubamracek**
Recently, Swift runtime changed not to print backtraces in non-assert builds of the runtime. It seems that there shouldn't be any problems with printing backtraces on Linux, even in optimized builds, so this PR makes swift_reportError always print backtraces there.

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by gottesmm** [comment]
If the tests pass, LGTM.

**Review by gottesmm — COMMENTED** [review]
If the tests pass, LGTM.

**Comment by kubamracek** [comment]
@swift-ci please test

**Pull request merged**
