### PR TITLE
[DNM] Implement Float16

### PR DESCRIPTION
**Pull request by stephentyrone**
Implement IEEE 754 binary16 as `Float16` in the stdlib conforming to `BinaryFloatingPoint` and `SIMDScalar`. This PR does not include availability tags to make it easier for people to experiment, but all of this API will be marked available(9999) in the final PR.

Evolution proposal: https://github.com/apple/swift-evolution/pull/1120
Pitch thread: https://forums.swift.org/t/add-float16/33019/25

### CODE REVIEW

**Comment by stephentyrone** [comment]
@swift-ci please test

**Comment by Azoy** [comment]
@stephentyrone I tried out Float16 locally and I have to say that constructing literals is painful:
```swift
func x() {
  var x: Float16 = 1.0
}
```
results in the following SIL: https://gist.github.com/Azoy/12c131dd50b9d3610ac98e290123f8a8 .
I'm no floating point expert, but I tested going through float32 first then to float16 for literals to see if we could hit the constant folding pass in SIL:
```swift
% if bits == 16:
// Trunc to Float then trunc to Float16
self = ${Self}(Float(_builtinFloatLiteral: value))
% elif ...
```
which thankfully did get picked up by constant folding, but required adding float16 semantics:
```cpp
// lib/SILOptimizer/Utils/ConstantFolding.cpp Line: 963
case BuiltinFloatType::IEEE16:
  return IEESemantics(16, 5, 10, false);
```
this resulted in some very pleasing SIL: https://gist.github.com/Azoy/e9f644508454befd21c4b8cb1bfd99f0
which is lowered as a simple `store half 0xH3C00, half* %x._value, align 2` in LLVM IR.

**Comment by Azoy** [comment]
@rjmccall I also wanted to ask if it was at all feasible if floating point types could take advantage of a `Builtin.FloatLiteral` type like you did for integers. I'm not too sure how we would lower this type specifically in LLVM, but all occurrences of the float literal type should get replaced by one of the `Builtin.FPIEEE{bits}` types eventually which makes me think that this might be somewhat feasible. Although, at this point during the release cycle is seems very unlikely that such change would go through as it affects some of the stdlib API.

**Comment by stephentyrone** [comment]
> I wanted to ask if it's feasible to make this change for the `init(_builtinFloatLiteral value: Builtin.FPIEEE80)` initializer so that literals don't have to go through this workaround.

No, because that results in a double-rounding and gets some values wrong because of it. This is a temporary fix to get things working correctly, we can easily improve on it in the future.

**Comment by stephentyrone** [comment]
> @rjmccall I also wanted to ask if it was at all feasible if floating point types could take advantage of a `Builtin.FloatLiteral` type like you did for integers.

Yes, we can (and will) do this at some future point. In order to work efficiently and maintain ABI stability, it will probably be a bit more complex than the integer literals are, but it's on the radar.

**Comment by rjmccall** [comment]
The biggest complexity with arbitrary-precision floating-point literals is that we cannot losslessly change the base of the source literal: if the user wrote `0.1`, our representation has to be `1 × 10^-1`.  That's true even if we have no intention of ever supporting non-binary FP types (and I'd to, eventually).  We wouldn't necessarily need to support bases other than 2 and 10, but we'd need to support at least those.

The representation would therefore need to include:
- a sign
- a base (possibly just a 2 vs. 10 flag)
- an exponent (a fixed-width `Int32` would probably be fine for real use cases, but maybe we'd want this to be arbitrary-precision as well just because)
- an arbitrary-precision integer as the "significand"
- some way of expressing the infinities and various `NaN`s (maybe using the significand as a payload?)

And then maybe you'd also throw in a pre-computed `Double`, because it is not otherwise going to be efficient to turn one of these into an IEEE format.

**Comment by stephentyrone** [comment]
@rjmccall Right. We want to have good support for radix 2 and 10, and nothing else really matters. There are some details to work out, but supporting those radices efficiently isn't too bad (and yes, one option is including a pre-computed `Double` and `Float`, though it's not the only option).

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by stephentyrone** [comment]
Hmm, that's a merge gone wrong. Let's try that again.

**Comment by Azoy** [comment]
2630 commits to implement Float16? I knew IEEE754 was tough but I didn’t know it was that tough.

**Comment by stephentyrone** [comment]
Look, I just take "keep commits small" *really* seriously. One character max.

**Comment by Azoy** [comment]
Easier for code review I see 😆

**Comment by stephentyrone** [comment]
Real PR: https://github.com/apple/swift/pull/30130

**Pull request closed without merging**
