### PR TITLE
[gardening] Remove unreachable/unused/redundant code

### PR DESCRIPTION
**Pull request by practicalswift**
Cleanups include:
- Remove unused enums
- Remove unused functions
- Remove unused methods
- Remove unused structs
- Remove unused variables
- Bring parameter naming in forward declaration in sync with parameter naming in definition

### CODE REVIEW

**Comment by lattner** [comment]
Wow nice!  To ask the obvious, you ran the tests with this, right?

If so, I'm happy to merge this, but please squash this into one commit.  Thanks!

**Comment by gribozavr** [comment]
@practicalswift Could you resolve conflicts?

**Comment by practicalswift** [comment]
@gribozavr Conflicts resolved. Passes `utils/build-script -RT` :-)

**Comment by practicalswift** [comment]
@lattner Yes, I've run `utils/build-script -RT` many times while creating these changes - wouldn't dare changing a single line without it :-)  Now squashed into one commit too.

**Comment by gribozavr** [comment]
Thank you!

**Pull request merged**
