### PR TITLE
[WIP] [Remote] Assume clients can deal with non-key generic parameters

### PR DESCRIPTION
**Pull request by jrose-apple**
RemoteAST certainly can; it's got the information it needs in the regular AST. Unfortunately Remote Mirrors is still having problems, and someone else will need to dig into that.

Follow-up to #25984.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Review by jckarter — APPROVED** [review]
Thanks!

**Review by slavapestov — COMMENTED** [review]
Do we already have remote mirrors tests?

**Comment by jrose-apple** [comment]
I played with this some on Wednesday and found that Remote Mirrors does *not* quite handle this correctly, so I guess it's better to leave it as is (deterministically failing).

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
