### PR TITLE
Cleanups of various bash scripts

### PR DESCRIPTION
**Pull request by practicalswift**
Fixes:
- Use of `>` instead of `-gt` for numerical comparison. `>` is used for string comparisons.
- Superfluous `$` in arithmetic variables.
- Use of discouraged back-tick execution (instead of recommended `$(cmd)`)

### CODE REVIEW

**Comment by gribozavr** [comment]
@practicalswift LGTM, but `utils/install-package-helper.sh` is old and unused, let's just remove it.

**Comment by practicalswift** [comment]
@gribozavr Added commit to remove `utils/install-package-helper.sh`. May I remove `utils/install-test-script.sh` too?

**Comment by gribozavr** [comment]
@practicalswift Yes, good catch, that one should go, too.

**Comment by gribozavr** [comment]
Thank you!

**Comment by practicalswift** [comment]
@gribozavr Another question - may I delete `utils/demo-tool` from the repo? Seems like a nice tool, but I'm not sure the Swift repo is the right home for it :-)

**Pull request merged**
