### PR TITLE
[4.1] Fix "variable unused" warning in Metadata.cpp in non-assert build

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by gparker42** [comment]
Should we instead change this to `assert(numPatternWitnesses >= protocol->NumMandatoryRequirements);` and just drop the unused variable?

**Comment by kubamracek** [comment]
Sure, if you prefer that.

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
ping

**Review by rjmccall — APPROVED** [review]
Yes, this is fine, of course.

**Pull request merged**
