### PR TITLE
[Constant Evaluator] Add support for BinaryInteger.description which converts an integer to a string

### PR DESCRIPTION
**Pull request by ravikandhadai**
This patch adds an @_semantics annotation to the BinaryInteger.description function.

### CODE REVIEW

**Comment by ravikandhadai** [comment]
@eeckstein I just added a @_semantics annotation to the `BinaryInteger.description` stdlib function, so that it can be modeled in the constant evaluator.

**Comment by ravikandhadai** [comment]
@swift-ci Please test

**Comment by ravikandhadai** [comment]
@swift-ci Please benchmark

**Review by eeckstein — APPROVED** [review]
lgtm

**Pull request merged**
