### PR TITLE
[update-checkout] Update swift-argument-parser checkout to 0.3.0

### PR DESCRIPTION
**Pull request by owenv**
This will support https://github.com/apple/swift-package-manager/pull/2653, which adopts ArgumentParser in SPM. It'll require CI reconfiguration before merging.

### CODE REVIEW

**Review by abertelrud — APPROVED** [review]
Looks great.  Thanks!

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by owenv** [comment]
@swift-ci please test Linux

**Comment by abertelrud** [comment]
Looks like all test are now passing, so we just need @shahmishal's approval, and can then merge.

**Comment by shahmishal** [comment]
Jobs updated, can you also update the `"master-rebranch"` scheme?

**Comment by owenv** [comment]
@shahmishal thanks!

**Comment by owenv** [comment]
@swift-ci test

**Comment by owenv** [comment]
@swift-ci please test macOS

**Pull request merged**
