### PR TITLE
[5.7][CursorInfo] Add ObjC location to generated symbol graph

### PR DESCRIPTION
**Pull request by bnbarham**
Cherry-pick 680bf2e7537f66cf707ce0f735f31a53c2df4b77

-----

Add the file for an imported ObjC-symbol to the generated symbol graph
when ObjC documentation is requested.

Skips line/column information for now since it's not needed. If we add
those we should extract location retrieval to a common method for both
cursor info and symbol graph gen.

Resolves rdar://91658873.

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Review by airspeedswift — APPROVED** [review]

**Comment by bnbarham** [comment]
@swift-ci please test Linux platform

**Comment by bnbarham** [comment]
@swift-ci please clean test Linux platform

**Comment by bnbarham** [comment]
apple/swift-integration-tests#100

@swift-ci please test Linux platform

**Comment by bnbarham** [comment]
Linux failure is unrelated (seems to be caused by https://github.com/apple/swift-docc/pull/136 but not clear as to why).

**Pull request merged**
