### PR TITLE
ModuleTrace: use clang API to emit information in JSON

### PR DESCRIPTION
**Pull request by ahatanaka**

### CODE REVIEW

**Comment by ahatanaka** [comment]
The API is implemented here: https://github.com/swiftlang/llvm-project/pull/9519

**Review by nkcsgexi — APPROVED** [review]
Thank you for sharing the implementation here, Akira!

**Comment by ahatanaka** [comment]
@swift-ci Please test

**Comment by ahatanaka** [comment]
@swift-ci Please smoke test macOS

**Comment by ahatanaka** [comment]
@swift-ci Please smoke test Linux

**Comment by ahatanaka** [comment]
@swift-ci Please test Windows

**Comment by ahatanaka** [comment]
@swift-ci Please smoke test Linux

**Comment by ahatanaka** [comment]
@swift-ci Please smoke test Linux

**Pull request merged**
