### PR TITLE
Preload standard library in ModuleInterfaceBuilder 

### PR DESCRIPTION
**Pull request by beccadax**
Previously, when the standard library module interface was broken, Swift would try to rebuild it repeatedly during `-compile-module-from-interface` jobs because `ASTContext::getStdlibModule()` would try to load the standard library again each time it was called. This led to extremely slow compilations that repeatedly emitted the same errors, and sometimes to crashes in non-asserts compilers when they expected a standard library but couldn't find one.

To avoid this, we make `ModuleInterfaceBuilder` try to load the standard library right away and bail out if it can’t.

This PR also includes a couple of fixes for issues that occur when trying to use `-verify` mode with module interfaces. One of these (the SourceLoc translation issue) is implicitly exercised by the new test; the other is a simple command-line flag validation bug.

Fixes rdar://75669548.

### CODE REVIEW

**Comment by beccadax** [comment]
@swift-ci please smoke test

**Review by nkcsgexi — APPROVED** [review]
LGTM! This could also be fixed by explicit module build.

**Comment by beccadax** [comment]
@swift-ci please smoke test

**Comment by beccadax** [comment]
(Test needed to be tweaked for Windows.)

**Comment by beccadax** [comment]
@swift-ci please smoke test macOS platform

**Comment by beccadax** [comment]
@swift-ci please smoke test Linux platform

**Comment by beccadax** [comment]
This swift-driver error should have been cleared by apple/swift-driver#571...

@swift-ci please clean smoke test Linux platform

**Comment by beccadax** [comment]
@swift-ci please clean smoke test Linux platform

**Comment by beccadax** [comment]
@swift-ci please smoke test windows platform

**Comment by beccadax** [comment]
@swift-ci please smoke test

**Comment by beccadax** [comment]
@swift-ci please smoke test

**Pull request merged**
