### PR TITLE
Revert "IRGen: Deserialize SIL witness tables and shared-linkage definitions by need."

### PR DESCRIPTION
**Pull request by rudkx**
Reverts apple/swift#15590

Revert on the suspicion that it results in build breaks in a bunch of source compatibility tests.

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
@jckarter There are 87 source compat failures at the moment and this seems like a reasonable culprit, so I'm going to try running the source compat suite on the revert here.

```
Assertion failed: (Entry->getType() == Type && "Value Type mismatch?"), function getLocalValue, file /Users/buildnode/jenkins/workspace-private/swift-master-source-compat-suite/swift/lib/Serialization/DeserializeSIL.cpp, line 271.
```

**Comment by gottesmm** [comment]
Source compat passes... merging!

**Pull request merged**
