### PR TITLE
[TypeChecker] Warn if witness mismatches only on sendability until Sw…

### PR DESCRIPTION
**Pull request by xedin**
…ift 6 mode

This expands the downgrade for Objective-C requirements to all preconcurrency
requirements until strict concurrency checking is enabled (either via a flag in Swift 5
language mode or by switching to Swift 6 language mode).

Resolves: rdar://134503878

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test source compatibility release

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Review by hborla — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Pull request merged**
