### PR TITLE
[5.9][borrowing][consuming] Make borrowing and consuming no implicit copy parameters

### PR DESCRIPTION
**Pull request by gottesmm**
All commits but 617fd263b273ecdd626ffa144d72e3d32877d135
• Description: [borrowing/consuming] Make borrowing and consuming parameters no implicit copy types.
• Risk: Low risk. Only affects code which uses borrowing/consuming parameters (which is only new code).
• Original PR: #66381
• Reviewed By: @jckarter
• Testing: I added lots of tests for both diagnostics/code generation/and an interpreter test for code measure.
• Resolves: rdar://108383660

Commit 617fd263b273ecdd626ffa144d72e3d32877d135
• Description: [move-only] Fix class setters of address only move only types.
• Risk: Low risk. Only affects code using noncopyable types.
• Original PR: https://github.com/apple/swift/pull/66255
• Reviewed By: @jckarter
• Testing: I added a diagnostic test that showed we didn't error and also a SILGen test
• Resolves: rdar://109287977

Commit 98cbeecf091843b6f31b113382af8634e9fc770d
• Description: [borrowing/consuming] Be sure to visit boxes with trivial moveonly types.
• Risk: Low risk. Only affects code using noncopyable types.
• Original PR: https://github.com/apple/swift/pull/66402
• Reviewed By: @atrick
• Testing: I added sil-verify-all to the test that exposed this and validated that we no longer crashed.
• Resolves: rdar://110364874

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Review by jckarter — APPROVED** [review]

**Review by tbkka — APPROVED** [review]

**Comment by gottesmm** [comment]
I think I messed up the merge conflicts when I cherry-picked.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Review by jckarter — APPROVED** [review]

**Review by kavon — APPROVED** [review]

**Comment by gottesmm** [comment]
@swift-ci test macOS platform

**Comment by gottesmm** [comment]
the macOS test failure was due to the infamous cxxinterop Darwin bug.

**Comment by gottesmm** [comment]
@swift-ci clean test macOS platform

**Comment by gottesmm** [comment]
Just hit the Darwin error again...

**Comment by gottesmm** [comment]
@swift-ci clean test macOS platform

**Comment by gottesmm** [comment]
I don't know why the clean test isn't working...

**Comment by gottesmm** [comment]
@swift-ci test macOS platform

**Comment by gottesmm** [comment]
@swift-ci smoke test macOS platform

**Comment by gottesmm** [comment]
I think the little trick I just did got my macOS full test on a different machine. Hopefully it works now and does a clean build.

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
