### PR TITLE
[CMake] Merge Clang's features file with Swift's

### PR DESCRIPTION
**Pull request by bnbarham**
Clang has a new `redirecting-with` property in the VFS overlay files.
While this could be added to Swift's features as well, it is generally
the case that features provided by Clang can also be useful to know for
clients of Swift. Merge the features from Clang into Swift's features
file with the "clang-" prefix to differentiate them.

### CODE REVIEW

**Comment by bnbarham** [comment]
Adds https://github.com/apple/swift/pull/41547 back in. Removed the file output entirely and changed the CMake side to just redirect stdout into the merged file instead.

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
@swift-ci please test

**Review by compnerd — APPROVED** [review]
Incremental installs locally seem to be good, I think this should be a good approach.

**Pull request merged**
