### PR TITLE
test: apply some fix-its to DebugInfo tests

### PR DESCRIPTION
**Pull request by compnerd**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

These tests were causing the current swift compiler to emit fix-it hints for
changes since the tests were written.  NFC.

### CODE REVIEW

**Comment by compnerd** [comment]
CC @rudkx

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by rudkx** [comment]
CC @adrian-prantl, who is the best person to review these particular changes.

**Comment by tkremenek** [comment]
The tests do not pass on either Linux or OS X.

**Comment by compnerd** [comment]
I was able to reproduce the failures with a clean build.  *shrug*.  Sorry about that.  Updated the patches.  Seems that one of the changes actually changes semantics :-( (and Ive removed that from the change).  The rest still clean up the fix it hints, and adjust the checks for the modified LLVM IR output.

**Comment by adrian-prantl** [comment]
LGTM. Thanks!
@swift-ci test

**Pull request merged**
