### PR TITLE
NFC: Fix warnings

### PR DESCRIPTION
**Pull request by tshortli**
Fix various warnings emitted while building `swift-frontend`. See individual commit messages for details.

### CODE REVIEW

**Comment by tshortli** [comment]
@swift-ci please smoke test

**Comment by tshortli** [comment]
@swift-ci please smoke test

**Review by ahoppen — APPROVED** [review]
Parser changes LGTM.

**Comment by tshortli** [comment]
@swift-ci please smoke test Linux

**Comment by tshortli** [comment]
@swift-ci please smoke test Linux

**Pull request merged**
