### PR TITLE
IRGen: Use clang::Sema::LookupName instead of TranslationUnit::lookup to find NSInteger.

### PR DESCRIPTION
**Pull request by jckarter**
Sema's lookup is much more efficient.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test and merge

**Comment by jckarter** [comment]
@DougGregor Does this look better?

**Comment by jckarter** [comment]
lldb-mi timeout failure on Linux looks unrelated.

**Comment by DougGregor** [comment]
Yes, much better. Thank you!

**Comment by DougGregor** [comment]
I'd recommend this for the Swift 3 branch.

**Comment by ramsedsay** [comment]
Have never tried? What does this do to be exact?

**Comment by ramsedsay** [comment]
What is up I'm lost?

**Pull request merged**
