### PR TITLE
Do Not Merge: testing NoncopyableGenerics

### PR DESCRIPTION
**Pull request by kavon**

### CODE REVIEW

**Comment by kavon** [comment]
@swift-ci Please Test Source Compatibility

**Comment by kavon** [comment]
@swift-ci Please Test Source Compatibility

**Comment by kavon** [comment]
@swift-ci Please Test Source Compatibility

**Comment by kavon** [comment]
@swift-ci Please Test Source Compatibility

**Comment by kavon** [comment]
@swift-ci Please Test Source Compatibility

**Comment by xedin** [comment]
@swift-ci Please Test Source Compatibility

**Comment by xedin** [comment]
@swift-ci Please Test Source Compatibility

**Comment by kavon** [comment]
@swift-ci Please Test Source Compatibility

**Comment by kavon** [comment]
@swift-ci Please Test Source Compatibility

**Comment by kavon** [comment]
@swift-ci please build toolchain

**Comment by kavon** [comment]
@swift-ci please test

**Comment by kavon** [comment]
@swift-ci please test

**Comment by kavon** [comment]
@swift-ci please build toolchain

**Comment by kavon** [comment]
@swift-ci Please Test Source Compatibility

**Pull request closed without merging**
