### PR TITLE
[lit] Enable testing for iOS 32-bit simulator by default

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
macOS test expected to fail because ci.swift.org does not have older sim installed.

**Comment by shahmishal** [comment]
@jrose-apple Can you please review this?

**Review by jrose-apple — COMMENTED** [review]
Will Xcode automatically pick the right runtime if you say i386 and have the 10.3 runtime installed? If so, this looks good to me.

**Comment by shahmishal** [comment]
@jrose-apple Yes, because iOS 11 does not support 32bit devices.

**Comment by jrose-apple** [comment]
Ah, I understand the desired behavior, but I wasn't sure Xcode actually did it. Sounds good!

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci benchmark

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test macOS

**Comment by shahmishal** [comment]
@swift-ci test macOS

**Comment by shahmishal** [comment]
@swift-ci test macOS

**Comment by shahmishal** [comment]
@swift-ci test macOS

**Comment by shahmishal** [comment]
@swift-ci test macOS

**Comment by shahmishal** [comment]
@swift-ci test macOS

**Pull request merged**
