### PR TITLE
[value-lifetime] Cleanup constructors.

### PR DESCRIPTION
**Pull request by gottesmm**

### CODE REVIEW

**Comment by gottesmm** [comment]
Not much here... just no crazy template stuff.

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci test windows platform

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by gottesmm** [comment]
The key thing to notice here is that this API actually stores these uses in side of itself. So the actual type on the outside doesn't matter. What this patch does is make it so that one can pass a range of SILInstruction or a use iterator so one can also do SILValue::getUses() to seed the ValueLifetimeAnalysis.cpp. It is really nice for avoiding unnecessary container friction around SILInstruction, Operand trafficking.

**Comment by gottesmm** [comment]
The key thing to notice here is that this API actually stores these uses in side of itself. So the actual type on the outside doesn't matter. What this patch does is make it so that one can pass a range of SILInstruction or a use iterator so one can also do SILValue::getUses() to seed the ValueLifetimeAnalysis.cpp. It is really nice for avoiding unnecessary container friction around SILInstruction, Operand trafficking.

**Review by atrick — COMMENTED** [review]
lgtm

**Pull request merged**
