### PR TITLE
Update pull request template with new triggers

### PR DESCRIPTION
**Pull request by shahmishal**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

A smoke test on macOS does the following:
1. Builds the compiler incrementally.
2. Builds the standard library only for macOS. Simulator standard libraries and
   device standard libraries are not built.
3. lldb is not built.
4. The test and validation-test targets are run only for macOS. The optimized
   version of these tests are not run.

A smoke test on Linux does the following:
1. Builds the compiler incrementally.
2. Builds the standard library incrementally.
3. lldb is built incrementally.
4. The swift test and validation-test targets are run. The optimized version of these
   tests are not run.
5. lldb is tested.

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by shahmishal** [comment]
Please don't merge, testing CI with this PR.

**Comment by shahmishal** [comment]
@swift-ci Please smoke test macOS

**Comment by jtbandes** [comment]
To me it seems strange that all this detail about the CI is given in the PR template, when most people making PRs already know it, and it ends up producing a bulky PR comment. Would it make sense to document these in CONTRIBUTING.md, and just have a link to there? Such as
```
<!--
For information about triggering CI builds, please see
https://github.com/apple/swift/blob/master/CONTRIBUTING.md
-->
```

**Comment by jrose-apple** [comment]
It's nice to have the reference handy on the page. I know @gottesmm cared a lot about that.

(The rest of the template doesn't seem to be serving much purpose, though.)

**Comment by shahmishal** [comment]
@swift-ci test macOS

**Comment by jtbandes** [comment]
Maybe this, then:
```
<!-- CI Triggers:
All platforms:
@swift-ci Please test
@swift-ci Please clean test
@swift-ci Please test and merge

macOS:
@swift-ci Please test OS X platform
@swift-ci Please clean test OS X platform
@swift-ci Please benchmark

Linux:
@swift-ci Please test Linux platform
@swift-ci Please clean test Linux platform

Lint testing:
@swift-ci Please Python lint
-->
```

**Comment by shahmishal** [comment]
@swift-ci Please test and merge

**Comment by gottesmm** [comment]
Can you also update the continuous integration doc?

**Comment by gottesmm** [comment]
@jrose-apple It was just an ad-hoc idea. I have memorized it at this point so I do not really care as long as it is documented in ContinuousIntegration.md

**Pull request merged**
