### PR TITLE
Allow designated initializers outside the ClassDecl

### PR DESCRIPTION
**Pull request by jrose-apple**
Objective-C allows this in "class extensions" (nameless categories); what's worse is that it's actually useful-ish sometimes: when you want to put a particular initializer in an explicit submodule, or only expose it to the current target.

The second commit here is a refactoring to simplify `ClassDecl::inheritsSuperclassInitializers`, which is duplicating a bunch of the logic in the type checker's `resolveImplicitConstructors` operation. Collapse the duplication even though it makes `resolveImplicitConstructors` a little more complicated.

[SR-4566](https://bugs.swift.org/browse/SR-4566) / rdar://problem/37173549

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test compiler performance

**Comment by jrose-apple** [comment]
Oops, this is why we do PR testing. Forgot that required convenience inits can override other required convenience inits.

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by jrose-apple** [comment]
Source compat failure is [SR-7233](https://bugs.swift.org/browse/SR-7233), unrelated to this PR.

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
