### PR TITLE
Support actor isolation for property wrappers

### PR DESCRIPTION
**Pull request by DougGregor**
Property wrappers can provide global actor isolation based on the
property wrapper type itself (which affects the backing property),
`wrappedValue` (which affects the wrapped property), and
`projectedValue` (which affects the $ property). This allows us to
express, e.g., property wrappers that require accesses to occur on a
particular global actor.

Thanks to @hborla for walking through this with me.

More in support of rdar://74241687

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Review by hborla — APPROVED** [review]

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
Bah, updated for diagnostics changes merged recently

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@swift-ci please build toolchain

**Comment by DougGregor** [comment]
@swift-ci please smoke test macOS

**Comment by DougGregor** [comment]
@swift-ci please build toolchain macOS

**Pull request merged**
