### PR TITLE
[sil-capture-propagation] Switch to the new notifyAddFunction API

### PR DESCRIPTION
**Pull request by swiftix**
This fixes a build failure.

### CODE REVIEW

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please smoke test Linux

**Comment by swiftix** [comment]
@swift-ci please smoke test OS X

**Comment by gparker42** [comment]
Reverted in #8111. 
https://ci.swift.org/job/oss-swift-incremental-RA-osx/8805/

Do not commit again without a full test. The test failure only occurs with a release stdlib build. The smoke test performs a debug stdlib build.

**Pull request merged**
