### PR TITLE
[Demangler] Fix OldRemangler to cope with single argument functions.

### PR DESCRIPTION
**Pull request by al45tair**
The Demangler can sometimes output ArgumentTuples containing a single argument
without placing that argument inside a Tuple node.  OldRemangler failed to take
account of this and either crashed or failed with an assertion failure depending
on whether assertions were enabled or not.

rdar://63678072

### CODE REVIEW

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
Should we instead fix the Demangler to always wrap arguments in a tuple?

**Comment by al45tair** [comment]
I assume the reason we didn't is that it avoids allocating another Node.

**Comment by al45tair** [comment]
@swift-ci Please smoke test macOS platform

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
@swift-ci Please smoke test macOS platform

**Review by mikeash — APPROVED** [review]

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Pull request merged**
