### PR TITLE
build: allow unified builds on Windows

### PR DESCRIPTION
**Pull request by compnerd**
We cannot query the location of the clang target when clang is built in
a unified build.  Use a generator expression instead.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by jrose-apple** [comment]
Does the generator expression work in non-unified builds too? Can we just use it all the time?

**Comment by compnerd** [comment]
No, it wouldn't work on standalone builds since it needs a target :-(

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by jrose-apple** [comment]
Aw, I was hoping the CMake exports file would make things that qualified as valid targets. Okay.

**Comment by compnerd** [comment]
Yes, CMake exports would count as valid targets, unfortunately, we do not currently use that for the standalone builds.  I've been migrating to the exports files as part of the new Swift support in CMake (libdispatch is now exporting the targets for use in Foundation/XCTest).

**Comment by compnerd** [comment]
Wait, if Im doing a `get_target_property` - I should be able to use the generator expression everywhere.  Thanks @jrose-apple!

**Comment by compnerd** [comment]
@swift-ci please smoke test Linux platform

**Comment by compnerd** [comment]
@swift-ci please smoke test Linux platform

**Comment by compnerd** [comment]
@swift-ci please smoke test and merge

**Comment by compnerd** [comment]
@swift-ci please smoke test and merge

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Pull request merged**
