### PR TITLE
Update to swift-collections 1.1.1 on release/6.0, main, rebranch and next

### PR DESCRIPTION
**Pull request by lorentey**
I skipped doing this in February, but toolchain builds should use the latest public package release.

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci build toolchain

**Comment by finagolfin** [comment]
CMake too old? @etcwilde [plans to bump it to 3.26 or above later this year](https://forums.swift.org/t/implementing-parts-of-the-swift-compiler-in-swift/59524/49).

**Comment by etcwilde** [comment]
The capitalization of `Utilities/_UnsafeBitSet.swift` is wrong in the CMakeLists file. The filename is `_UnsafeBitset.swift` with a lowercase `s`.

**Comment by lorentey** [comment]
Yep; this is unfortunate as it will need to be corrected in a new swift-collections tag.

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci build toolchain

**Comment by lorentey** [comment]
Reverted this to a draft PR to avoid accidentally landing a branch spec here. (We are waiting for swift-collections 1.1.1 to ship.)

**Comment by lorentey** [comment]
Swift Collections 1.1.1 is out; this is ready for landing.

**Review by jmschonfeld — APPROVED** [review]

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci build toolchain

**Pull request merged**
