### PR TITLE
[Serialization] Do not assert when inherited type is null

### PR DESCRIPTION
**Pull request by bnbarham**
When compiling with allow errors, it's possible to have invalid
inherited types - both null and ErrorType.

Cleaned up the tests a little - moved the majority of
Frontend/allow-errors.swift into separate files in
Serialization/AllowErrors and use split_file.py instead of #defines.

Resolves rdar://78048470

### CODE REVIEW

**Comment by bnbarham** [comment]
@xymus what are your thoughts on the asserts? Should I add a check for whether compiling with errors or leave as is?

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by xymus** [comment]
Yeah, I think it would be worth taking into account `AllowModuleWithCompilerErrors` in the asserts. It can prevent us from introducing future regressions.

**Comment by bnbarham** [comment]
> Yeah, I think it would be worth taking into account `AllowModuleWithCompilerErrors` in the asserts. It can prevent us from introducing future unrelated regressions.

While updating this I realised that `addTypeRef` already has a null type + error check, so adding another would just be duplicating it.

**Review by xymus — APPROVED** [review]

**Pull request merged**
