### PR TITLE
Fix ownership of move-only structs in SIL

### PR DESCRIPTION
**Pull request by meg-gupta**

### CODE REVIEW

**Review by nate-chandler — APPROVED** [review]
lgtm!  (For structs and tuples.)

**Review by atrick — APPROVED** [review]
Thank you! LGTM as a quick fix. We might consider marking values as initialized instead if this continues to cause problems.

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci smoke test windows platform

**Comment by meg-gupta** [comment]
@swift-ci smoke test windows platform

**Pull request merged**
