### PR TITLE
Enable LLVM's HotColdSplitting pass

### PR DESCRIPTION
**Pull request by meg-gupta**
This pass can extract cold paths that end in traps. This along with the
MergeFunctions pass has potential for code size reduction as well

rdar://52147720

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@meg-gupta I am not sure if you are aware of this, but we also have a swift test compiler performance job that you can run that will report numbers about the source compat suite. It is documented here:

https://github.com/apple/swift/blob/master/docs/ContinuousIntegration.md#testing-compiler-performance

**Comment by gottesmm** [comment]
Keep in mind it takes a long time to run and its output needs to be improved (it only shows aggregate numbers), but I imagine it can provide some interesting data for you here.

**Comment by meg-gupta** [comment]
@swift-ci test compiler performance

**Comment by meg-gupta** [comment]
@swift-ci test compiler performance

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by compnerd** [comment]
Please provide a user controllable flag for this pass.  This pass is known to generate a lot of issues for Windows.

**Comment by meg-gupta** [comment]
Not planning to merge this now. This causes huge binary size increase for source-compat-suite (due to additional symbol table entries). Also affects debugging/crashreports.

**Pull request closed without merging**
