### PR TITLE
swift-api-digester: port swift-api-digester to swift 3.0 branch.

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci Please test OS X platform

**Comment by nkcsgexi** [comment]
@swift-ci Please test OS X platform

**Comment by nkcsgexi** [comment]
@swift-ci Please test OS X platform

**Comment by nkcsgexi** [comment]
@swift-ci Please test OS X platform

**Comment by shahmishal** [comment]
@swift-ci Please test macOS

**Pull request merged**
