### PR TITLE
[gardening] Fix trailing whitespace in *.cfg.in, *.html, *.mm and *.sil files

### PR DESCRIPTION
**Pull request by practicalswift**

### CODE REVIEW

**Comment by practicalswift** [comment]
@swift-ci please smoke test

**Comment by practicalswift** [comment]
@swift-ci please test

**Comment by Gankro** [comment]
Is there any reason the CI doesn't gate on this being true? Having periodic fixups like this makes rebasing harder.

**Comment by gottesmm** [comment]
I agree.

**Comment by practicalswift** [comment]
@gottesmm I agree that this should probably be guarded by CI. Should I skip fixing the remaining trailing whitespace issues? See #5532 :-)

**Comment by Gankro** [comment]
@practicalswift if we agree it should be part of the CI, I would defer these until the CI is ready to start checking it.

**Comment by rintaro** [comment]
Just FYI https://github.com/apple/swift/pull/2614

**Comment by gparker42** [comment]
> On Oct 29, 2016, at 7:13 AM, Alexis Beingessner <notifications@github.com> wrote:
> 
> Is there any reason the CI doesn't gate on this being true? Having periodic fixups like this makes rebasing harder.
> 

I thought our coding style was that we Officially Don't Care about trailing whitespace, in which case mass cleanup of trailing whitespace would be undesirable in the first place.


-- 
Greg Parker     gparker@apple.com <mailto:gparker@apple.com>     Runtime Wrangler

**Comment by gottesmm** [comment]
> On Oct 31, 2016, at 2:39 PM, Greg Parker <notifications@github.com> wrote:
> 
> 
> > On Oct 29, 2016, at 7:13 AM, Alexis Beingessner <notifications@github.com> wrote:
> > 
> > Is there any reason the CI doesn't gate on this being true? Having periodic fixups like this makes rebasing harder.
> > 
> 
> I thought our coding style was that we Officially Don't Care about trailing whitespace, in which case mass cleanup of trailing whitespace would be undesirable in the first place.

Greg is right. When I said I agree, I was more referring to generic formatting commits. It would be much better to fix those up pre-commit.

Michael

**Comment by dabrahams** [comment]
We have a policy against cluttering commit history and creating spurious diffs by stripping trailing whitespace.  IMO this should never have been merged.

**Comment by practicalswift** [comment]
@dabrahams Understood :-)

**Pull request merged**
