### PR TITLE
[stdlib] Delete unneeded inits

### PR DESCRIPTION
**Pull request by dabrahams**
These don't appear to be used or needed.

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please benchmark

**Comment by dabrahams** [comment]
@swift-ci Please test

**Comment by dabrahams** [comment]
@airspeedswift This is what we discussed earlier today.  If it merges we can strip the `.gyb` extension from the file.

**Comment by DougGregor** [comment]
IIRC, these non-generic `init(stringInterpolationSegment:)`overloads are here because the generic specializer/inliner wasn't handling the generic one as efficiently. The type checker itself will end up picking these non-generic ones.

I'd love to see this pile of overloads go away (it's likely even to help type checker performance by drastically reducing the overload set size), but we need to understand the performance impact.

**Comment by dabrahams** [comment]
on Thu Oct 13 2016, Doug Gregor <notifications-AT-github.com> wrote:

> IIRC, these non-generic `init(stringInterpolationSegment:)`overloads
> are here because the generic specializer/inliner wasn't handling the
> generic one as efficiently. The type checker itself will end up
> picking these non-generic ones.
>
> I'd love to see this pile of overloads go away (it's likely even to
> help type checker performance by drastically reducing the overload set
> size), but we need to understand the performance impact.

Sadly: https://github.com/apple/swift/pull/5268#issuecomment-253430734

-- 
-Dave

**Comment by DougGregor** [comment]
Yeah, I saw it. I mean, "I'm not surprised there is performance impact, but I hope we can solve it to get rid of these overloads"

**Comment by dabrahams** [comment]
How would we solve it?  Alternatively, can we make these inits internal?  If not, would underscoring the parameter name (not argument label) have any impact on the UX?

**Comment by dabrahams** [comment]
<rdar://28756496> Workarounds for poor optimization hurt UX

**Comment by jdfweb** [comment]
Great work

**Comment by swiftix** [comment]
@dabrahams Some of the removed initializers call `_toStringReadOnlyStreamable`, which allows for may optimizations, because this function is marked as `@effects(readonly)`. When these initializers are no longer available, the execution uses regular `Stream` APIs to write into strings. As a result, such calls cannot be optimized away even if their results are not used afterwards.

**Comment by nkcsgexi** [comment]
@dabrahams the OS X test fails because the expected APIs of stdlib have changed. If the change is desirable, could you update test/api-digester/source-stability.swift.expected?

**Comment by dabrahams** [comment]
@swiftix The question is, what can I do to have these APIs not show up publicly?

**Comment by swiftix** [comment]
@dabrahams I commented on the radar with some proposals regarding what could be done.

**Comment by airspeedswift** [comment]
We can close this since @DougGregor covered it with #7145, right?

**Pull request closed without merging**
