### PR TITLE
[Build System: CMake] New stdlib/toolchain directory for toolchain-only content. 

### PR DESCRIPTION
**Pull request by Rostepher**
This PR moves the `legacy_layouts` into `stdlib/toolchain` which is a new source directory for _toolchain-only_ content.

rdar://52351019

### CODE REVIEW

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by Rostepher** [comment]
@swift-ci please build macOS toolchain

**Comment by Rostepher** [comment]
@swift-ci please build toolchain macOS platform

**Comment by Rostepher** [comment]
@swift-ci please build toolchain macOS Platform

**Review by jckarter — APPROVED** [review]

**Comment by compnerd** [comment]
I don’t think that `toolchain` is the best directory for this because its confusing for the standard definition of the toolchain.  This is probably better as `data` or `configuration` IMO.

**Comment by Rostepher** [comment]
@compnerd `data` and `configuration` are also pretty generic terms and IMO they don't really describe this content well. The `layouts` (and the Compatibility libraries) are really content that needs to be built and installed along-side the compiler in what we currently call the toolchain, so it seemed an apt name for now.

We can consider the directory name temporary for the time being. I'm fine with changing the name (either soon or down the road a bit) to something else, but I kinda need to land this change pretty soon.

**Pull request merged**
