### PR TITLE
[4.1] Fix an issue with the constraint favoring code in the constraint optimizer.

### PR DESCRIPTION
**Pull request by rudkx**
- **Explanation**: Comparisons like `i != 10` where `i` is an IUO-typed value result in `i` being force-unwrapped rather than `10` being converted to an Optional<Int>.

- **Scope of Issue**: Anyone could potentially write code like this.

- **Origination**: The standard library added concrete versions of `!=`, `==`, and possibly other functions. This exposed a longstanding problem with the constraint optimization pass of the solver.

- **Risk**: Low. This makes the constraint optimizer slightly more conservative. There is a small risk it could make a few more expressions "too complex", but it seems very likely that they would be miscompiled without this fix (e.g. they would force an IUO as in this case).

- **Fixes**: rdar://problem/37073401

- **Reviewed By**: @xedin

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please test

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Review by xedin — APPROVED** [review]
LGTM!

**Comment by rudkx** [comment]
@swift-ci Please test

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
@swift-ci Please smoke test Linux platform

**Comment by rudkx** [comment]
@swift-ci Please smoke test Linux platform

**Comment by rudkx** [comment]
@swift-ci Please test Linux platform

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
@swift-ci please nominate

**Comment by rudkx** [comment]
@swift-ci please nominate

**Pull request merged**
