### PR TITLE
Add Codable conformance to common Foundation types

### PR DESCRIPTION
**Pull request by itaiferber**
**What's in this pull request?**
Take two of this PR because I broke the iOS builders last time.

Add conformances + unit tests for

* CGFloat
* AffineTransform
* Calendar
* CharacterSet
* DateComponents
* DateInterval
* Decimal
* IndexPath
* IndexSet
* Locale
* Measurement
* NSRange
* PersonNameComponents
* TimeZone
* URL
* UUID

along with some unit tests for each.

### CODE REVIEW

**Comment by itaiferber** [comment]
@swift-ci Please smoke test OSX

**Comment by itaiferber** [comment]
@swift-ci Please smoke test OS X

**Comment by jrose-apple** [comment]
Please do a full test on macOS before merging this time.

**Comment by itaiferber** [comment]
@jrose-apple Will do. Just want to make sure the tests compile and run here briefly before continuing.

**Comment by itaiferber** [comment]
@swift-ci Please smoke test OS X

**Comment by itaiferber** [comment]
@swift-ci Please smoke test OS X

**Comment by itaiferber** [comment]
@swift-ci Please smoke test OS X

**Comment by itaiferber** [comment]
@swift-ci Please test and merge

**Comment by itaiferber** [comment]
@swift-ci Please test and merge

**Comment by itaiferber** [comment]
@swift-ci Please test and merge

**Comment by itaiferber** [comment]
I don't know why GitHub suddenly reported a merge conflict that had to be resolved (because there was nothing really conflicting), but let's try this again...

**Comment by itaiferber** [comment]
@swift-ci Please test and merge

**Comment by itaiferber** [comment]
@swift-ci Please test and merge

**Pull request merged**
