### PR TITLE
[benchmark] ReportFormatter: Improved single_table headers

### PR DESCRIPTION
**Pull request by palimondo**
This PR improves `single_table` mode of `ReportFormatter`:
* Add unit test coverage.
* Print labels for the numeric columns on inline headers.
* Visually distinguish sections by a separator row preceding the the inline headers.
* Separate header label styles for `git` and `markdown` modes with UPPERCASE and **Bold**  formatting respectively.

### CODE REVIEW

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
I'm hoping some false change will pop up during benchmark, otherwise I will have to commit and revert some renamed benchmark… 🤞.

**Comment by PFCAwesome** [comment]
Stop

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Review by eeckstein — APPROVED** [review]

**Comment by palimondo** [comment]
@swift-ci smoke test and merge

**Comment by palimondo** [comment]
@swift-ci smoke test and merge

**Pull request merged**
