### PR TITLE
[stdlib] Add Int.init(bitPattern: OpaquePointer?)

### PR DESCRIPTION
**Pull request by jrose-apple**
(and the same for UInt)

@gribozavr  and I consider this an oversight in [SE-0016](https://github.com/apple/swift-evolution/blob/master/proposals/0016-initializers-for-converting-unsafe-pointers-to-ints.md), particularly since OpaquePointer has the inverse operation `init?(bitPattern: Int)`.

---

Before merging this pull request to apple/swift repository:
- [x] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by jrose-apple** [comment]
@MichaelBuckley, what do you think? @DougGregor, should this go through the SEP properly, or just be considered a bug fix?

@swift-ci Please test

**Comment by gribozavr** [comment]
I strongly suggest that we just amend the proposal.  This API is in spirit of the other ones, and we just overlooked `OpaquePointer`.

**Comment by MichaelBuckley** [comment]
I believe in the discussion of the original proposal (I'll try to find the link), we omitted OpaquePointer on purpose. (I believe because, at the time, it was slated to go away.)

**Comment by MichaelBuckley** [comment]
I can't find any mention of OpaquePointer in the discussion, so I must be misremembering. I agree with @gribozavr

**Comment by jrose-apple** [comment]
@dabrahams, as the standard library code owner and a core team member, do you feel this is a reasonable change to make without going through the Swift Evolution Process?

**Comment by lattner** [comment]
Just MHO, but this seems obviously fine to put in.  I'd recommend committing it and sending a heads up to swift-evolution.

-Chris

**Comment by dabrahams** [comment]
This is really about how seriously we’re taking “no api changes without evolution review.” I think I want @DougGregor to make the call.

**Comment by jrose-apple** [comment]
Per discussion today, I'll submit a PR to the swift-evolution repo to amend the proposal, and then Dave or Doug will accept it and send a message to the swift-evolution list noting the change. Any concerns can be addressed in the same way as regular post-commit review; either we'll refine the change based on feedback, or we'll revert pending further discussion.

**Comment by dabrahams** [comment]
on Wed Apr 20 2016, Jordan Rose <notifications-AT-github.com> wrote:

> Per discussion today, I'll submit a PR to the swift-evolution repo to amend the
> proposal, and then Dave or Doug will accept it and send a message to the
> swift-evolution list noting the change. Any concerns can be addressed in the
> same way as regular post-commit review; either we'll refine the change based on
> feedback, or we'll revert pending further discussion.

Great.  Note the new revision history policy we're following, c.f. the
header of
https://github.com/apple/swift-evolution/blob/master/proposals/0065-collections-move-indices.md

-- 
Dave

**Comment by jrose-apple** [comment]
Oh, that makes more sense. I'll do another swift-evolution PR to fix that.

**Pull request merged**
