### PR TITLE
[update-checkout] swift-argument-parser 0.0.5 -> 0.0.6

### PR DESCRIPTION
**Pull request by owenv**
The new version includes CMake changes which will allow it to be build during the SwiftPM build for use with swift-driver.

This will need to be updated in the source compatibility suite config too, I should have a PR up for that in a moment

### CODE REVIEW

**Comment by owenv** [comment]
@swift-ci smoke test

**Comment by owenv** [comment]
Source compatibility PR: https://github.com/apple/swift-source-compat-suite/pull/433

**Review by DougGregor — APPROVED** [review]

**Comment by shahmishal** [comment]
Next time we update the tag, please also me to the reviewer. The CI system needs to be updated to checkout the new tag separately.

**Comment by owenv** [comment]
@shahmishal sorry about that! Should I wait to merge this and/or revert the source compatibility suite change?

**Comment by shahmishal** [comment]
> @shahmishal sorry about that! Should I wait to merge this and/or revert the source compatibility suite change?

No worries, we can keep the changes on the branch. I am going to update CI now, and I will merge swift pull request after.

**Comment by shahmishal** [comment]
Tag updated on CI: 
```
0. OSS - LLDB - ASAN + UBSAN OS X (master) (Release)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
0. OSS - LLDB Incremental - Ubuntu 14.04 (master)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
0. OSS - LLDB Incremental - Ubuntu 16.04 (master)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
0. OSS - LLDB Incremental - Ubuntu 16.04 (master-next)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
0. OSS - LLDB Incremental - Ubuntu 16.10 (master-next)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
0. OSS - LLDB Incremental - Ubuntu 18.04 (master)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
0. OSS - LLDB Incremental - OS X (master) (CMake) (Release)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
0. OSS - LLDB Incremental - OS X (master-next)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
OSS - Swift Package Trigger (master)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
OSS - Swift Package Trigger (master-next)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
1. OSS - Swift ASAN - OS X (master)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
1. OSS - Swift ASAN - OS X (master-next)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
1. OSS - Swift ASAN - Ubuntu 16.04 (master)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
0. OSS - Swift Incremental RA - Ubuntu 16.04 (master)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
0. OSS - Swift Incremental RA - Ubuntu 16.04 - Long Test (master)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
0. OSS - Swift Incremental RA - Ubuntu 16.04 - Long Test (master-next)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
0. OSS - Swift Incremental RA - Ubuntu 16.04 (master-next)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
0. OSS - Swift Incremental RA - Ubuntu 18.04 (master)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
0. OSS - Swift Incremental RA - Ubuntu 18.04 - Long Test (master)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
1. OSS - Swift Leaks Sanitizer - LSAN - Ubuntu 18.04 (master)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
0. OSS - Swift Incremental RA - macOS (master) (Xcode)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
0. OSS - Swift Incremental RA - OS X (master)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
0. OSS - Swift Incremental RA - OS X (master-next)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
OSS - Swift Incremental RA - OS X - Trigger (master)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
1. OSS - Swift - TSAN - libdispatch - Ubuntu 18.04 (master-next)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
OSS - Swift Package - Ubuntu 14.04 (master)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
OSS - Swift Package - Ubuntu 16.04 (master)
	Skip: ${swift_argument_parser}
OSS - Swift Package - Ubuntu 16.04 (master-next)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
OSS - Swift Package - Ubuntu 18.04 (master)
	Skip: ${swift_argument_parser}
OSS - Swift Package - OS X (master)
	Skip: ${swift_argument_parser}
OSS - Swift Package - OS X (master-next)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
0. OSS - Swift Pull Request Test (status) (master)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
1. OSS - Swift - TSAN - libdispatch - Ubuntu 18.04 (master)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
1. OSS - Swift (Tools Opt+No Assert,  Stdlib Opt+DebInfo, Test Simulator) - OS X (master)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
1. OSS - Swift (Tools Opt+Assert, Stdlib DebInfo+Assert, Test Device non_executable) (master)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
1. OSS - Swift (Tools Opt+Assert, Stdlib DebInfo+Assert, Test Simulator) - OS X (master)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
1. OSS - Swift (Tools Opt+Assert, Stdlib DebInfo+Assert, Test Simulator) - OS X (master-next)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
2. Swift (Tools Opt+Assert, Stdlib Opt+Assert) (macOS 10.14.5) (Swift in the OS)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
1. OSS - Swift (Tools Opt+Assert,  Stdlib Opt+DebInfo, Test Simulator) - OS X (master)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
1. OSS - Swift (Tools Opt+Assert,  Stdlib Opt+DebInfo, Test Simulator) - OS X (master-next)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
1. OSS - Swift (Tools Opt+Assert, Stdlib Opt+DebInfo+Assert, Long Test) - OS X  (master)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
1. OSS - Swift (Tools Opt+Assert, Stdlib Opt+DebInfo+Assert, Long Test) - OS X  (master-next)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
1. OSS - Swift (Tools Opt+Assert, Stdlib Opt+DebInfo+Assert, Test Simulator) - OS X  (master)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
1. OSS - Swift (Tools Opt+Assert, Stdlib Opt+DebInfo+Assert, Test Simulator) - OS X  (master-next)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
Swift Argument Parser Pull Request Test Linux
	Skip: ${sha1}
Swift Argument Parser Pull Request Test macOS
	Skip: ${sha1}
Swift Argument Parser Pull Request Merge
	Skip: ${sha1}
2. Swift Sourcekit Stress Tester (master)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
2. Swift Sourcekit Stress Tester (master) (weekly)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
0. OSS - Swift Protobuf - Ubuntu 16.04 (master)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.0.5
	new Branch: 0.0.6
```

**Comment by owenv** [comment]
@shahmishal Thanks, and sorry again for the inconvenience!

**Comment by shahmishal** [comment]
@owenv don't worry about! :) Thanks for updating the version!

**Pull request merged**
