### PR TITLE
[Test] Generalize api-digester tests to all platforms.

### PR DESCRIPTION
**Pull request by DougGregor**
The API digester tests were being run only for macOS, mainly
because they were not using %target-swift consistently. Lift
the unnecessary restriction so we run these tests more widely.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Review by nkcsgexi — APPROVED** [review]
Thank you!

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test platform macOS

**Comment by DougGregor** [comment]
@swift-ci please test platform macOS

**Comment by CodaFi** [comment]
@swift-ci test macOS

**Comment by DougGregor** [comment]
@swift-ci test macOS

**Comment by DougGregor** [comment]
@swift-ci please test

**Pull request merged**
