### PR TITLE
[sil] Add thunk lowering and the thunk instruction.

### PR DESCRIPTION
**Pull request by gottesmm**
In this commit, I add a new instruction called thunk and a thunk lowering SIL pass that runs late. The current implementation just includes an identity thunk that I provided for testing purposes and as an example for other developers who want to add a thunk to cargo cult/modify.

I am going to use this in a subsequent PR to add a new kind of thunk for a concurrency experiment... but that is a discussion for that PR.

The reason why I am doing this is that:

1. Creating thunks in SILGen creates a bunch of complexity and is not always simple to test. By having a SILPass that does the lowering later, we can write focused SIL test cases that truly expose all of the corner cases.
2. SILGen is already really large and allowing one to avoid extending it with new functionality (especially around thunks) will improve code quality. With this change, one just needs to create a new instruction rather than a whole new function/etc in SILGen. It also prevents one from having to learn about SILGen and how SILGenThunk work.
3. This will improve compile time for diagnostic emission. Currently, diagnostics in the SIL pipeline require us to codegen all the thunks in the program to emit diagnostics. Since the thunk lowering pass runs late, after the point at which we stop processing SIL for diagnostic purposes... all those thousands of thunks do not need to be emitted reducing allocations and improving performance when emitting diagnostics in the editor.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by eeckstein** [comment]
It would be nice to implement the pass in swift. We really shouldn't add new C++ passes.

**Comment by rjmccall** [comment]
You're not actually going to simplify SILGen here unless you can get it completely out of the business of needing to do bridging and reabstraction of parameters and results.  Those code paths in SILGen mostly do not center around function value reabstraction.  I think you're just adding a new code path that has to do these operations rather than laying out a path to actually simplifying anything.

**Pull request merged**
