### PR TITLE
[Sema] Remove @unknown default requirement for package enums.

### PR DESCRIPTION
**Pull request by elsh**
`@unknown default` in switch statements are required for resilient enums since they might be modified with new fields in the future and modules defining the enums are generally not built together with the consuming modules.

However, if the modules are in the same package, they are required to be built together, thus the requirement for `@unknown default` can be skipped. This PR removes the need for that, enabling less boilerplate. Note this change only impacts typecheck and not SIL gen.

Resolves rdar://130015149.

### CODE REVIEW

**Comment by elsh** [comment]
@swift-ci smoke test

**Review by nkcsgexi — APPROVED** [review]
This change makes sense to me. Thank you for the exhaustive test case!

**Comment by elsh** [comment]
@swift-ci smoke test

**Comment by elsh** [comment]
pending https://github.com/swiftlang/swift/pull/75745 as new test covers interface flag related changes.

**Comment by elsh** [comment]
@swift-ci smoke test

**Comment by elsh** [comment]
@swift-ci smoke test linux

**Comment by elsh** [comment]
@swift-ci smoke test linux

**Comment by elsh** [comment]
@swift-ci smoke test linux

**Pull request merged**
