### PR TITLE
Revert "[stdlib] Add Substring comparison benchmarks"

### PR DESCRIPTION
**Pull request by shajrawi**
Reverts apple/swift#9917

Fails to build:
/Users/buildnode/jenkins/workspace/oss-swift-incremental-RA-osx/swift/benchmark/utils/main.swift:233:69: error: use of unresolved identifier 'run_EqualStringSubstringGenericStringProtocol'

### CODE REVIEW

**Comment by dabrahams** [comment]
OMG, you can't just comment out tests; you have to rename them.  Bah, humbug.

**Comment by palimondo** [comment]
@dabrahams Do you want me to mess with the regEx that gathers the test names to ignore those with single line comments?

**Comment by palimondo** [comment]
@dabrahams But I don't think it's worth it. It could not possibly cover your block comment. And there's the rule about not storing code in comments when we have version control… :-)

**Comment by palimondo** [comment]
@dabrahams Why did you want to comment them out? Your initial comment on #9917 does not explain this to me. If you just wanted to not have them run as precommit checks, you could just _stash_ them in the "string" test suite by modifying `[main.swift.gyb](https://github.com/apple/swift/blob/master/benchmark/utils/main.swift.gyb#L42)` to match them in this section:

```python
string_re = [
    "StringWalk.+",
]
```

**Comment by dabrahams** [comment]
on Wed May 24 2017, Pavol Vaskovic <notifications-AT-github.com> wrote:

> @dabrahams But I don't think it's worth it. It could not possibly
> cover your block comment. And there's the rule about not storing code
> in comments when we have version control… :-)

This code was never checked in, so that doesn't apply.

-- 
-Dave

**Pull request merged**
