### PR TITLE
Add debug_value [trace] attribute.

### PR DESCRIPTION
**Pull request by atrick**
This lets us write optimizer unit tests and selectively debug the optimizer in general. We'll be able trace analyses and control optimization selectively for certain values.

Adding a trace flag to debug_value is the easiest way to start using it experimentally and develop the rest of the infrastructure. If this takes off, then we can consider a new `trace_value` instruction. For now, reusing debug_value is the least intrusive way to start writing liveness unit tests.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci smoke test

**Review by eeckstein — COMMENTED** [review]
It's not clear to me what "trace" means in this context. I assume, it means optimizations can selectively output log messages based on this flag? So it's about compile time tracing (and not runtime tracing)?

Can you document this in SIL.rst?

**Comment by atrick** [comment]
@eeckstein it can be used to selectively output compile-time information. More importantly it can be used to control optimizations for the purpose of true unit testing. I often can't write unit tests for compiler bugs because passes don't have enough granularity.

**Comment by atrick** [comment]
@swift-ci smoke test

**Review by eeckstein — APPROVED** [review]
ok, thanks. lgtm

**Pull request merged**
