### PR TITLE
[Concurrency] Add compatibility overrides to Concurrency library.

### PR DESCRIPTION
**Pull request by mikeash**
Take the existing `CompatibilityOverride` mechanism and generalize it so it can be used in both the runtime and Concurrency libraries. The mechanism is preprocessor-heavy, so this requires some tricks. Use the `SWIFT_TARGET_LIBRARY_NAME` define to distinguish the libraries, and use a different `.def` file and mach-o section name accordingly.

We want the global/main executor functions to be a little more flexible. Instead of using the override mechanism, we expose function pointers that can be set by the compatibility library, or by any other code that wants to use a custom implementation.

rdar://73726764

### CODE REVIEW

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]

**Comment by mikeash** [comment]
@swift-ci please smoke test and merge

**Comment by mikeash** [comment]
@swift-ci please smoke test os x platform

**Comment by mikeash** [comment]
@swift-ci please smoke test os x platform

**Comment by mikeash** [comment]
@swift-ci please smoke test os x platform

**Pull request merged**
