### PR TITLE
[Diagnostics] Handle ambiguities related to use of `nil` literal

### PR DESCRIPTION
**Pull request by xedin**
When `nil` is passed as an argument to call with multiple overloads
it's possible that this would result in ambiguity where matched
expected argument type doesn't conform to `ExpressibleByNilLiteral`.

To handle situations like this locator for contextual mismatch
has to be adjusted to point to the call where `nil` is used, so
`diagnoseAmbiguityWithFixes` can identify multiple overloads and
 produce a correct ambiguity diagnostic.

Resolves: rdar://75514153

### CODE REVIEW

**Review by hborla — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Comment by xedin** [comment]
@swift-ci please test

**Pull request merged**
