### PR TITLE
Remove the extra-inhabitant value witness functions

### PR DESCRIPTION
**Pull request by rjmccall**
This is essentially a long-belated follow-up to Arnold's #12606.  The key observation here is that the enum-tag-single-payload witnesses are strictly more powerful than the XI witnesses: you can simulate
the XI witnesses by using an extra case count that's <= the XI count.  Of course the result is less efficient than the XI witnesses when actually running generic code, but that's less important than overall code size, and we can work on fast-paths in the future.

The extra inhabitant count is stored in a 32-bit field (always present) following the `ValueWitnessFlags`, which now occupy a fixed 32 bits.  This inflates non-XI VWTs on 32-bit targets by a word, but the net effect on XI VWTs is to shrink them by two words, which is likely to be the more important change.  Also, being able to access the XI count directly should be a nice win.

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please benchmark.

**Comment by rjmccall** [comment]
Note that a number of IRGen tests are still failing.

**Review by jckarter — APPROVED** [review]
Looks good! For a follow up, can we kill the SinglePayloadGeneric runtime functions entirely?

**Comment by rjmccall** [comment]
It's possible, but we'd have to do a lot of work inline in the cases that are currently relying on them (dynamic-layout single-payload enums and dynamic-layout structs).

**Comment by rjmccall** [comment]
@swift-ci test compiler performance

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Comment by rjmccall** [comment]
I might change the dynamic multi-payload implementation to use the fixed-style pattern, since the extra-inhabitants logic is totally static and the only dynamic thing is the offset of the tag.

**Comment by jckarter** [comment]
I wanted to make it so that single-payload enums with an added tag gave extra inhabitants from the tag like multi-payload enums do too, but ran out of time.

**Comment by rjmccall** [comment]
...the multi-payload tagging system, even in the purely dynamic, no-spare-bits case, is *way* weirder than I gave it credit for.  I do not understand all this stuff with rotation, but I'm basically going to have to leave the current practice intact.

**Comment by jckarter** [comment]
The rotation stuff should only impact spare-bits-using multi-payload enums, not any place where we're falling back to the dynamic implementation.

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Pull request merged**
