### PR TITLE
[gardening] Change an if-else over ApplySite to a covered switch over…

### PR DESCRIPTION
**Pull request by gottesmm**
… ApplySiteKind.

This will ensure that we get covered switch warnings if a new apply site is ever
added.

NFC.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
The os x failure is due to a non-deterministic test that @slavapestov is fixing. I disabled it in #22523. @slavapestov will re-enable once he has the fix.

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Comment by gottesmm** [comment]
@swift-ci smoke test OS X platform

**Comment by gottesmm** [comment]
@swift-ci smoke test OS X platform

**Comment by gottesmm** [comment]
@swift-ci smoke test OS X platform

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Comment by shahmishal** [comment]
@swift-ci smoke test os x platform

**Comment by shahmishal** [comment]
@swift-ci smoke test os x platform

**Comment by shahmishal** [comment]
@swift-ci smoke test macOS platform

**Comment by shahmishal** [comment]
@swift-ci smoke test macOS

**Comment by shahmishal** [comment]
@swift-ci smoke test macOS

**Pull request merged**
