### PR TITLE
[cxx-interop] Use a synthesized C++ method when invoking a base metho…

### LINKED ISSUE #65876: [cxx-interop] calls to __swift_interopStaticCast in synthesized base class member accessors should not copy C++ type by value
Right now, when Swift compiler synthesizes a call to `__swift_interopStaticCast` when creating a thunk for imported C++ type that calls a const base class  method (non-mutating), it ends up passing the C++ record by value, thus copying the given value. This should be avoided, we should pass them by const ref or pointer, like we do when invoking mutating methods.

### PR DESCRIPTION
**Pull request by hyp**
…d from a derived class synthesized method

The use of a synthesized C++ method allows us to avoid making a copy of self when invoking the base method from Swift

### CODE REVIEW

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
Still also should do that for field accessors.

**Comment by hyp** [comment]
@swift-ci please test linux platform

**Comment by hyp** [comment]
@swift-ci please test

**Review by egorzhdan — APPROVED** [review]
Awesome! 👍

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test source compatibility

**Comment by finagolfin** [comment]
It looks like this pull introduced 5 IRGen tests that assume a 64-bit platform, [causing them to fail on Android armv7](https://ci-external.swift.org/job/oss-swift-RA-linux-ubuntu-16.04-android/5585/consoleText):

```
/home/ubuntu/jenkins/workspace/oss-swift-RA-linux-ubuntu-16.04-android/swift/test/Interop/Cxx/class/inheritance/fields-irgen.swift:13:11: error: CHECK: expected string not found in input
// CHECK: %[[ADD_PTR:.*]] = getelementptr inbounds i8, ptr %{{.*}}, i64 4
          ^
<stdin>:119:183: note: scanning from here
define linkonce_odr noundef i32 @_ZNK30CopyTrackedDerivedDerivedClass55__synthesizedBaseCall___synthesizedBaseGetterAccessor_xEv(ptr noundef nonnull align 4 dereferenceable(8) %this) #6 comdat align 2 {
                                                                                                                                                                                      ^
<stdin>:124:6: note: possible intended match here
 %add.ptr = getelementptr inbounds i8, ptr %this1, i32 4
     ^
```
@natecook1000, do these tests also fail on 32-bit watchOS, presuming that's still being tested by some CI?

**Comment by hyp** [comment]
Fixing it.

**Comment by hyp** [comment]
Patch up: https://github.com/apple/swift/pull/69283

**Pull request merged**
