### PR TITLE
SILGen: Fix partial application of enum case with one-element labeled tuple

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes <rdar://problem/46748491>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Comment by slavapestov** [comment]
These are from Result and the XFAILs will be removed shortly:

```
20:44:20 UPasses:
20:44:20   UPASS: https://bugs.swift.org/browse/SR-9497, Alamofire, 4.0, a5cd9e, iOS Example, generic/platform=iOS
20:44:20   UPASS: https://bugs.swift.org/browse/SR-9497, Kickstarter-ReactiveExtensions, 4.0, 6b7887, ReactiveExtensions-TestHelpers-iOS, generic/platform=iOS
20:44:20   UPASS: https://bugs.swift.org/browse/SR-9497, Kickstarter-ReactiveExtensions, 4.0, 6b7887, ReactiveExtensions-iOS, generic/platform=iOS
20:44:20   UPASS: https://bugs.swift.org/browse/SR-9497, ReactiveCocoa, 4.0, 72dd20, ReactiveCocoa-watchOS, generic/platform=watchOS
20:44:20   UPASS: https://bugs.swift.org/browse/SR-9497, ReactiveCocoa, 4.0, 72dd20, ReactiveCocoa-tvOS, generic/platform=tvOS
20:44:20   UPASS: https://bugs.swift.org/browse/SR-9497, ReactiveCocoa, 4.0, 72dd20, ReactiveCocoa-iOS, generic/platform=iOS
20:44:20   UPASS: https://bugs.swift.org/browse/SR-9497, ReactiveCocoa, 4.0, 72dd20, ReactiveCocoa-macOS, generic/platform=macOS
20:44:20   UPASS: https://bugs.swift.org/browse/SR-9497, ReactiveSwift, 4.0, 46fb4d, ReactiveSwift-watchOS, generic/platform=watchOS
20:44:20   UPASS: https://bugs.swift.org/browse/SR-9497, ReactiveSwift, 4.0, 46fb4d, ReactiveSwift-tvOS, generic/platform=tvOS
20:44:20   UPASS: https://bugs.swift.org/browse/SR-9497, ReactiveSwift, 4.0, 46fb4d, ReactiveSwift-iOS, generic/platform=iOS
20:44:20   UPASS: https://bugs.swift.org/browse/SR-9497, ReactiveSwift, 4.0, 46fb4d, ReactiveSwift-macOS, generic/platform=macOS
```

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Review by jckarter — APPROVED** [review]
Looks good, thanks Slava!

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
```
15:19:35 TIMEOUT: test_dwarf (lang/swift/step_into_override/TestStepIntoOverride.py)
```

@dcci Is there a bug for these timeouts? They seem to be happening occasionally.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Pull request merged**
