### PR TITLE
[Wasm] Specify the least valid pointer for wasm32

### PR DESCRIPTION
**Pull request by kateinoigakukun**
WebAssembly doesn't reserve low addresses but without "extra inhabitants" of
the pointer representation, runtime performance and memory footprint are
worse. So assume that compiler driver uses wasm-ld and --global-base=1024 to
reserve low 1KB.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Comment by MaxDesiatov** [comment]
Hi @rjmccall, would you have a moment to take a look at this PR?

**Comment by tbkka** [comment]
I'd personally be happier with 4096 here (same as other Swift 32-bit platforms, minimizes the chance of unexpected dependencies you'll have to track down later).

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Comment by tbkka** [comment]
@swift-ci Please test

**Review by tbkka — APPROVED** [review]

**Comment by kateinoigakukun** [comment]
Thank you for your review and follow-up!

**Pull request merged**
