### PR TITLE
[AutoDiff] TF-208: Remove setter from `Differentiable.allDifferentiableVariables` requirement.

### PR DESCRIPTION
**Pull request by rxwei**
**`allDifferentiableVariables` should only have a setter if all non-`@noDerivative` members have a setter.**

* Change the protocol definition so that it won't require conforming types to have a settable `allDifferentiableVariables`.
* Updates derived conformance to not synthesize a setter for `allDifferentiableVariables` when a member is not settable.

WIP notes: The derived conformance piece is not complete yet. `derivedBody_allDifferentiableVariablesSetter` is synthesizing some incorrect assignment expressions.

### CODE REVIEW

**Comment by rxwei** [comment]
@dan-zheng If you can take over, that'd be great.

**Comment by dan-zheng** [comment]
I made some progress; pushed a commit.

From the commit description:

> Fix `allDifferentiableVariables` setter synthesis condition.
> The setter should be synthesized only if all differentiation stored properties
> are mutable and their `allDifferentiableVariables` computed property is also
> settable.
> 
> Remove default implementation of `Differentiable.allDifferentiableVariables`.
> 
> The default implementation is problematic because it leads to incorrect
> behavior when derived conformances for `allDifferentiableVariables` is not
> triggered.
> 
> Tests fail due to two missing conformances marked in `AutoDiff.swift`.
> The conformances should be valid; however, stdlib compilation fails when
> they are specified. This is likely due to some generic signature minimization
> bug.

The conclusion is:
* The default implementation of `allDifferentiableVariables` must be removed for correctness, because we always want derived conformances to trigger for `allDifferentiableVariables` so that we can decide whether or not to synthesize a setter.
* However, removing the default implementation of `allDifferentiableVariables` reveals unexpected test failures due to two missing requirements on `Differentiable` protocol: `CotangentVector.AllDifferentiableVariables == CotangentVector` and `TangentVector.AllDifferentiableVariables == TangentVector`. Specifying these constraints leads to weird compilation errors, likely due to generic signature minimization issues.

**Comment by dan-zheng** [comment]
This patch is obsolete now that `Differentiable.allDifferentiableVariables` has been removed. Closing.

**Comment by rxwei** [comment]
Thank you :)

**Pull request closed without merging**
