### PR TITLE
[AST] Fully replace NameAliasType with the new, sugary-sweet BoundNameAliasType

### PR DESCRIPTION
**Pull request by DougGregor**
Fix a number of small issues with `BoundNameAliasType` to bring it up to parity with `NameAliasType`, so the former will be able to replace the latter. This includes:

* Making `BoundNameAliasType`s profiling (for `FoldingSet`) and formation more robust against ill-formed ASTs
* Not recording module types or existential parent types in the AST, because serialization cannot handle the former and the latter shouldn't be well-formed at all anyway
* Adding lots of redundant logic so that we handle a `BoundNameAliasType` everywhere that we handle a `NameAliasType`, including for special cases where we currently always get a `NameAliasType`. This part is pure staging.

Once done, wwitch all references to type aliases over to the new sugar-and-substitution-preserving `BoundNameAliasType`. Then eliminate the (now-unused) `NameAliasType` and steal its name for `BoundNameAliasType`.

`NameAliasType` is dead. Long live `NameAliasType`!

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Review by Adam8989 — APPROVED** [review]

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
The LLDB failure is real and should be addressed by https://github.com/apple/swift-lldb/pull/452

**Comment by DougGregor** [comment]
Source compatibility is being tested by https://ci.swift.org/job/swift-PR-source-compat-suite/948/; looks good thus far.

**Comment by rudkx** [comment]
Can you update the PR description to provide more detail on the motivation and benefit of the changes? Is this just about producing better diagnostics as a result of being sugar-and-substitution-preserving?

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
It's partly about better diagnostics (because we keep more sugar), partly about explicitly modeling substitutions in Types (which we want to do elsewhere as well), and partly because we depend on that sugar for some semantics (including requirement inference, e.g., in support of https://github.com/apple/swift/pull/15513, and also for access control, which checks based on Type sugar).

**Comment by DougGregor** [comment]
@swift-ci smoke test

**Comment by DougGregor** [comment]
@swift-ci smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Pull request merged**
