### PR TITLE
[4.1][stdlib] Add derived equality/comparison operators to concrete integer types

### PR DESCRIPTION
**Pull request by moiseev**
* Explanation: This change helps resolve the ambiguities that started to arise after the recent constraint solver changes.
* Scope of Issue: Additive. The operators being added have always been there in form of default impleemntations on protocol extensions. Overloading them on concrete type takes advantage of certain shortcuts in the solver.
* Risk: Minimal
* Reviewed By: Pavel Yaskevich
* Testing: Automated test suite + a case for the regression reported in SR-6634
* Directions for QA: N/A
* Radar: <rdar://problem/36113283>

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please nominate

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
@swift-ci Please Test Source Compatibility

**Comment by moiseev** [comment]
Cherrypicked from https://github.com/apple/swift/pull/13817

**Review by xedin — APPROVED** [review]
LGTM!

**Pull request merged**
