### PR TITLE
[SIL.rst] Add an Ownership SSA sub-section about forwarding uses.

### PR DESCRIPTION
**Pull request by gottesmm**
Just resurrecting this against main.

### CODE REVIEW

**Comment by gottesmm** [comment]
@atrick I am going to fix your comments from the other PR but then I want to merge this. Lets do everything else post-commit.

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by atrick** [comment]
@gottesmm I don't remember what my comments were, but I think they were fundamental. I can re-review whenever those fundamentals are cleared up.

**Review by atrick — APPROVED** [review]
Very nice, thanks!

**Pull request merged**
