### PR TITLE
[Diagnostics] Improve missing conformance diagnostics for opaque return

### PR DESCRIPTION
**Pull request by xedin**
New diagnostic framework can already identify contextual failures
related to opaque return types, `RequirementFailure` just needs
to get adjusted to identify correct affected declaration and provide
tailored diagnostic.

Resolves: rdar://problem/49582531

### CODE REVIEW

**Review by jckarter — APPROVED** [review]
Thanks!

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@shahmishal @akyrtzi Is this a known problem in SwiftSyntax?

```
01:47:21 Failing Tests (1):
01:47:21     SwiftSyntax :: print_verify_tree.swift
```

**Comment by theblixguy** [comment]
Should be fixed soon: https://github.com/apple/swift/pull/24385

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Pull request merged**
