### PR TITLE
[stdlib] Adding a useful message to an unavailable &+

### PR DESCRIPTION
**Pull request by moiseev**

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please smoke test and merge
/cc @dabrahams

**Comment by jrose-apple** [comment]
You can't actually use that syntax with operators. If someone's gotten here, that probably means they used the wrong constraint on their generic parameters, not that they invoked the SignedInteger version of the operator directly.

**Comment by moiseev** [comment]
@jrose-apple That is exactly what I am trying to fix.

**Comment by jrose-apple** [comment]
My point is that it's not a good message. They don't want to invoke a different operator; they should change their generic requirements.

**Comment by moiseev** [comment]
Let it be no message then.

**Pull request closed without merging**
