### PR TITLE
[NFC] Add an EmitSortedSIL member to SILOptions for consistency.

### PR DESCRIPTION
**Pull request by varungandhi-apple**
It is a bit strange to have the FrontendOptions being used in writeSIL
instead of SILOptions, so this PR fixes that.

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
Unless I missed it, I think you also need to remove line 70 of ArgsToFrontendOptionsConverter.

**Comment by varungandhi-apple** [comment]
I don't think that should be removed. I didn't remove the flag from `FrontendOptions`, I only added it to `SILOptions`, so there is no need to modify `ArgsToFrontendOptionsConverter`.

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test Linux platform

Tuxboi, don't let me down like that

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test

Maybe third time's the charm?

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test Linux platform

Maybe third time's the charm?

**Comment by varungandhi-apple** [comment]
@swift-ci please clean smoke test Linux platform

**Review by CodaFi — APPROVED** [review]

**Pull request merged**
