### PR TITLE
[NFC] Fold The Tri-State In Optional<ProtocolConformanceRef>

### PR DESCRIPTION
**Pull request by CodaFi**
`ProtocolConformanceRef` already has an invalid state.  Use this instead of `None` to signal something has gone wrong or a witness is missing.  As this makes `ProtocolConformanceRef` behave like an Optional, give it an `operator bool` and a default constructor and clean up all the call sites.

The result has been `clang-format`'ed with some minor revisions to keep noise down. I apologize in advance for the size of this patch, but there should be no behavior changes so the diff should be read as a 1-1 mapping between APIs.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please test

**Comment by CodaFi** [comment]
@swift-ci please test source compatibility

**Review by DougGregor — APPROVED** [review]
This all looks reasonable to me, although wow is it a big change

**Comment by CodaFi** [comment]
Infrastructure outage

@swift-ci please test

**Comment by CodaFi** [comment]
@swift-ci please test source compatibility

**Pull request merged**
