### PR TITLE
[Tests] Re-enable Runtime/linux-fatal-backtrace.swift as the related radar is fixed

### PR DESCRIPTION
**Pull request by Teemperor**

### CODE REVIEW

**Comment by Teemperor** [comment]
@swift-ci test Ubuntu 20.04

**Comment by Teemperor** [comment]
```
00:33:14 Testing Time: 34616.43s
00:33:14 ********************
00:33:14 Failing Tests (2):
00:33:14     Swift(linux-x86_64) :: compiler_scale/enum_members.gyb
00:33:14     Swift(linux-x86_64) :: compiler_scale/protocol_members.gyb
00:33:14 
```

failures not related.

**Comment by Teemperor** [comment]
@swift-ci test Ubuntu 20.04

**Comment by adrian-prantl** [comment]
@swift-ci smoke test

**Comment by Teemperor** [comment]
@swift-ci smoke test

**Comment by Teemperor** [comment]
```
21:05:43     Swift(linux-x86_64) :: compiler_scale/struct_nested.gyb
21:05:43     Swift(linux-x86_64) :: compiler_scale/protocol_members.gyb
21:05:43     Swift(linux-x86_64) :: compiler_scale/enum_members.gyb
21:05:43     Swift(linux-x86_64) :: SILOptimizer/large_string_array.swift.gyb
```
failures are again not related to the re-enabled test. @fredriss can you force-merge that we get the test back running?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Comment by adrian-prantl** [comment]
@swift-ci test Ubuntu 20.04

**Comment by Teemperor** [comment]
Jonas already fixed that:
commit 7a128470bd281b254525008131e5cf639ccedaeb
Author: Jonas Devlieghere <jonas@devlieghere.com>
Date:   Wed Sep 23 18:58:21 2020 -0700

    [test] Re-enable linux-fatal-backtrace.swift
    
    This was fixed by #33235
    
    rdar://66389949

**Pull request closed without merging**
