### PR TITLE
[NFC] Remove some dead variadic tuple code

### PR DESCRIPTION
**Pull request by theblixguy**
We don't support variadic tuples anymore, so remove some leftover dead code.

### CODE REVIEW

**Review by slavapestov — APPROVED** [review]
Thanks!

**Comment by theblixguy** [comment]
@swift-ci please test

**Comment by theblixguy** [comment]
@swift-ci please test Linux

**Comment by theblixguy** [comment]
@swift-ci please test macOS

**Comment by theblixguy** [comment]
@swift-ci please clean test macOS

**Comment by theblixguy** [comment]
@swift-ci please test macOS

**Pull request merged**
