### PR TITLE
Update WindowsBuild.md

### PR DESCRIPTION
**Pull request by compnerd**
Simplify the CMake invocation for Swift and match `build-script`.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @gwynne

**Comment by compnerd** [comment]
@swift-ci please smoke test and merge

**Review by gwynne — APPROVED** [review]
And good riddance!

**Comment by compnerd** [comment]
@swift-ci please smoke test macOS platform

**Pull request merged**
