### PR TITLE
Scale test updates

### PR DESCRIPTION
**Pull request by rudkx**

### CODE REVIEW

**Comment by rudkx** [comment]
@graydon Can you take a look at the change to `scale-test`?

I am seeing the following local failures with the test updates, which shows that doing `not %scale-test` was hiding problems:
```
********************
Testing Time: 171.57s
********************
Failing Tests (6):
    Swift(macosx-x86_64) :: Sema/type_checker_perf/slow/rdar21720888.swift.gyb
    Swift(macosx-x86_64) :: Sema/type_checker_perf/slow/rdar21930551.swift.gyb
    Swift(macosx-x86_64) :: Sema/type_checker_perf/slow/rdar23327871.swift.gyb
    Swift(macosx-x86_64) :: Sema/type_checker_perf/slow/rdar26939465.swift.gyb
    Swift(macosx-x86_64) :: Sema/type_checker_perf/slow/rdar33289839.swift.gyb
    Swift(macosx-x86_64) :: Sema/type_checker_perf/slow/rdar33688063.swift.gyb
```
The first five are all `failed to fit either polynomial or exponential model` and the last is an `expression was too complex`.

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
Okay I've tweaked to where I think everything will pass.

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by moiseev** [comment]
@swift-ci Please python lint

**Comment by moiseev** [comment]
@swift-ci Please python lint

**Comment by rudkx** [comment]
@moiseev I found out the hard way yesterday that apparently the OS X test does python lint, but it's nice to know it can be triggered independently - I hadn't realized that.

**Pull request merged**
