### PR TITLE
 Demangling: Fix off-by-one assert in mangleOpaqueType

### PR DESCRIPTION
**Pull request by kastiglione**
Fixes off-by-one mistake in #58643.

rdar://88080388

### CODE REVIEW

**Comment by kastiglione** [comment]
@swift-ci smoke test

**Review by fredriss — APPROVED** [review]

**Comment by kastiglione** [comment]
@swift-ci smoke test Linux Platform

**Comment by kastiglione** [comment]
@swift-ci smoke test macOS Platform

**Comment by kastiglione** [comment]
@swift-ci smoke test macOS Platform

**Comment by kastiglione** [comment]
@swift-ci smoke test Linux Platform

**Comment by kastiglione** [comment]
@swift-ci smoke test macOS Platform

**Comment by kastiglione** [comment]
@swift-ci smoke test macOS Platform

**Comment by kastiglione** [comment]
@swift-ci smoke test Linux Platform

**Comment by kastiglione** [comment]
@swift-ci smoke test Linux Platform

**Comment by kastiglione** [comment]
@swift-ci smoke test macOS Platform

**Comment by kastiglione** [comment]
@swift-ci smoke test macOS Platform

**Comment by kastiglione** [comment]
@swift-ci test

**Comment by kastiglione** [comment]
@swift-ci please test

**Pull request merged**
