### PR TITLE
Spelling autodiff

### PR DESCRIPTION
**Pull request by jsoref**
This fixes some misspellings in Swift autodiff, it is split per https://github.com/apple/swift/pull/42421#issuecomment-1101092698

### CODE REVIEW

**Review by CodaFi — APPROVED** [review]

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by tshortli** [comment]
@swift-ci please smoke test Windows

**Comment by philipturner** [comment]
@jsoref there is a spelling error in one of the test's names. In test/AutoDiff/compiler_crashers_fixed/sr12886-sr112887-vjp-emitter-definite-initialization.swift, sr112887 has an extraneous second "1". I wanted to get this fix merged in a future PR, but perhaps it belongs here. Is it possible to rename that regression test before merging?

**Comment by jsoref** [comment]
@philipturner: quite happy to oblige.

**Comment by tshortli** [comment]
@swift-ci please smoke test

**Pull request merged**
