### PR TITLE
🍒[5.10][Distributed] Don't crash in thunk generation when missing SR conformance

### PR DESCRIPTION
**Pull request by ktoso**
**Problem:** We would properly diagnose the missing conformance; but the compiler would still try to emit a thunk for the errored func. Tests which only -typecheck -verify would not catch this issue because it is after type checking.
**Solution:** This prevents distributed thunks from being generated when the func they are based on already has errors -- otherwise we can run into missing types and null pointers as we try to generate the thunk.
**Risk:** Low, affects only this specific situation and just avoids emitting thunks when they cannot be correct to begin with -- when the funk is broken.
**Impact:** Only distributed functions; This provides a better failure path - rather than a crash, just the expected error reporting.

**Review by:** @xedin @slavapestov 
**Testing:** CI testing
**Original PR:** https://github.com/apple/swift/pull/69501
**Radar:** rdar://116261701

Related radar: rdar://117677422

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
Included another 1 line cleanup from https://github.com/apple/swift/pull/69901

**Comment by ktoso** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
