### PR TITLE
[NFC] Cleanup function templates implementation. Address post-commit review comments from #33053.

### PR DESCRIPTION
**Pull request by zoecarver**
Addresses the post-commit review comments from #33053. Just re-naming, commenting, and some other small cleanups, nothing functionally different.

### CODE REVIEW

**Review by gribozavr — APPROVED** [review]

**Comment by zoecarver** [comment]
@swift-ci please smoke test.

**Comment by zoecarver** [comment]
@swift-ci please smoke test.

**Comment by zoecarver** [comment]
@swift-ci please smoke test macOS.

**Comment by zoecarver** [comment]
@swift-ci please smoke test Windows.

**Comment by zoecarver** [comment]
@swift-ci please smoke test Windows.

**Comment by zoecarver** [comment]
@swift-ci please smoke test macOS.

**Pull request merged**
