### PR TITLE
[4.2] Cherry-pick dropping @inlinable and other cleanup

### PR DESCRIPTION
**Pull request by milseman**
This is a cherry-pick of https://github.com/apple/swift/pull/16578 and https://github.com/apple/swift/pull/16477

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please benchmark

**Comment by milseman** [comment]
@swift-ci please test compiler performance

**Comment by milseman** [comment]
@eeckstein, @lorentey this is a 4.2 cherry-pick of the other PRs

**Review by eeckstein — APPROVED** [review]
lgtm

**Review by lorentey — APPROVED** [review]

**Comment by milseman** [comment]
@swift-ci please test linux platform

**Comment by milseman** [comment]
@swift-ci please test linux platform

**Comment by milseman** [comment]
https://github.com/apple/swift/pull/16850 Included most of these. Still have the Array ones though...

**Comment by tkremenek** [comment]
@swift-ci test

**Pull request closed without merging**
