### PR TITLE
[5.3] Handle Boolean Patterns Matching Against Invalid Constructor Forms

### PR DESCRIPTION
**Pull request by CodaFi**
Cherry-pick of #32822

### CODE REVIEW

**Review by nathawes — APPROVED** [review]

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci test windows

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
