### PR TITLE
[Swift 2.2.1][Swift runtime] Deallocation of partial class instances for Objective-C-derived classes

### PR DESCRIPTION
**Pull request by DougGregor**
#### What's in this pull request?

Backport the fix for deallocation of partial class instances for Objective-C-derived classes to Swift 2.2. We had fixed this regression from Swift 2.1 on mainline, but it's causing trouble in Swift 2.2 as well.
#### Resolved bug number: ([SR-704](https://bugs.swift.org/browse/SR-704))

Teach swift_deallocPartialClassInstance how to deal with classes that
have pure Objective-C classes in their hierarchy. In such cases, we
need to make sure a few things happen:

1) We deallocate via objc_release rather than
swift_deallocClassInstance.
2) We only attempt to find an execute ivar destroyers for
Swift-defined classes in the hierarchy
3) When we hit the most-derived pure Objective-C class, make sure that we
only execute the dealloc of that class and not any of the subclasses
(which would end up trying to destroy ivars again).

Fixes rdar://problem/25023544 / SR-704.

@swift-ci Please test

### CODE REVIEW

**Comment by DougGregor** [comment]
@tkremenek please consider for a Swift 2.2 update.

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by DougGregor** [comment]
@swift-ci Please test

**Comment by tkremenek** [comment]
Accepted for Swift 2.2.1.

**Pull request merged**
