### PR TITLE
[next] Fixes for various test failures on rebranch

### PR DESCRIPTION
**Pull request by bnbarham**
Mostly just small test fixes. The only code changes are a mistake I made in fixing a compilation error (798134f605a21bf73e89c45c23558e94f2fd1b77) and 427a689a966343a99b67ae81c7d1f31decfbe16b which replaces some `const char *` fields with `StringRef` to fix an overload resolution.

@xymus f2bd6ce9cbe93287cd0119441ebb05060c3f067f
@ahoppen a6a6ae456ae549edcc9ee2da387802b9e46e0198
@artemcm f05fab3f3c03cae715859bf41dbb69b70d8ac392
@adrian-prantl 50ecb47a4605edceb9a884791c910394535ec907
@nkcsgexi 427a689a966343a99b67ae81c7d1f31decfbe16b

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Review by xymus — APPROVED** [review]

**Comment by bnbarham** [comment]
No idea why I ran the tests. LLDB is still failing so... we won't actually get to tests 😓. Habit I guess.

**Review by ahoppen — APPROVED** [review]
https://github.com/apple/swift/commit/a6a6ae456ae549edcc9ee2da387802b9e46e0198 LGTM

**Review by artemcm — APPROVED** [review]
https://github.com/apple/swift/commit/f05fab3f3c03cae715859bf41dbb69b70d8ac392 LGTM

**Pull request merged**
