### PR TITLE
IRGen: apply IR linkage to trivial property descriptors

### PR DESCRIPTION
**Pull request by compnerd**
This ensures that the trivial property descriptors is externally
accessible on targets like Windows which does not export symbols by
default.  Thanks to Joe Groff for the pointer about the global aliases
for trivial property descriptors!

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @jckarter

**Comment by compnerd** [comment]
@swift-ci please test

**Review by jckarter — APPROVED** [review]
Looks good, thanks!

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by slavapestov** [comment]
This needs a testcase

**Comment by compnerd** [comment]
@slavapestov hmm, I can add a separate test case for this, but the existing test cases cover this.

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Pull request merged**
