### PR TITLE
Fix asserts and crashes caused by skipping function bodies or allowing errors

### PR DESCRIPTION
**Pull request by bnbarham**
I ran the stress tester locally with the new TestModule request and found a few new asserts and crashes. I'll run it again with these changes to see if it finds any more. Might actually be able to enable by default - with skipping all function bodies and WMO enabled it took ~30 minutes locally, which includes actually building the projects.

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
@swift-ci please test Linux platform

**Comment by bnbarham** [comment]
@swift-ci please test macOS platform

**Review by akyrtzi — APPROVED** [review]

**Review by xymus — APPROVED** [review]
This look good but we should try to drop completely invalid code earlier, like a destructor on a source file. I don't think there's value to preserve these for the AllowModuleWithCompilerErrors use cases and it may require a decent amount of maintenance to keep this working.

**Comment by bnbarham** [comment]
Good point @xymus, thanks. I've changed the serialization to just skip destructors if they're invalid and we're allowing errors. I also added a further comment to the attribute commits - invalid attributes are *already* skipped, so:
1. the verification is a little superfluous (typechecking already has that check)
2. CustomAttr is a little special in that it isn't set to invalid and is thus serialized (hence the skip during deserialization)
 
@swift-ci please test

**Review by xymus — APPROVED** [review]
Thanks!

**Pull request merged**
