### PR TITLE
swift: update for LLVM SVN r344140

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @bob-wilson

**Comment by bob-wilson** [comment]
Can you please remove the whitespace and formatting changes? We don't want master-next to diverge more than absolutely necessary because it causes merge conflicts.

**Comment by compnerd** [comment]
@bob-wilson - updated, though, this does introduce some formatting incorrectness technically.  Hopefully those will get fixed up when this gets merged to master.

**Comment by bob-wilson** [comment]
Thanks. Feel free to submit a separate PR to fix the formatting on master.

**Pull request merged**
