### PR TITLE
Many minor/obvious SIL API improvements that address lowering depends on

### PR DESCRIPTION
**Pull request by atrick**
This large collection of very small and hopefully obvious changes to the SIL API and SIL verification was extracted from a rewrite of the address lowering pass. Merging this separately to simplify subsequent PRs for the opaque SIL values feature.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci smoke test linux

**Review by eeckstein — APPROVED** [review]
lgtm

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci test

**Pull request merged**
