### PR TITLE
[build] Use Xcode toolchain Python executables

### PR DESCRIPTION
**Pull request by kastiglione**
Set `Python3_EXECUTABLE` for lldb, to match the CMake config already being used for Swift.

This ensures that the Xcode Python is used, which is consistent with Swift. Without this, a Homebrew Python will be used for lldb.

### CODE REVIEW

**Review by compnerd — APPROVED** [review]
So much duplication since we dont build swift, lldb, and llvm together :'(

**Comment by kastiglione** [comment]
@swift-ci smoke test

**Comment by kastiglione** [comment]
@swift-ci smoke test Linux Platform

**Comment by kastiglione** [comment]
@swift-ci smoke test macOS Platform

**Pull request merged**
