### PR TITLE
[Sema] Improve diagnostic handling of multiple trailing closures

### PR DESCRIPTION
**Pull request by hamishknight**
Correct some fix-it logic to account for multiple trailing closures, and improve the extraneous argument diagnostic for trailing closures.

rdar://81278194
rdar://81289222

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility Debug

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Comment by hamishknight** [comment]
@swift-ci please test Linux

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Comment by xedin** [comment]
Sorry for a delay, @hamishknight, I'm going to take a look at these changes today.

**Comment by hamishknight** [comment]
No worries @xedin, this should hopefully be one of the last functionality changes to split off from https://github.com/apple/swift/pull/37435 :)

**Review by xedin — APPROVED** [review]

**Pull request merged**
