### PR TITLE
[SILGen] Make sure profile increments gets assigned the correct scope.

### PR DESCRIPTION
**Pull request by dcci**
<rdar://problem/46686369>

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by dcci** [comment]
@swift-ci please test

**Comment by dcci** [comment]
Turns out that order matters (TM), so I need to think about something else.

**Comment by vedantk** [comment]
Yes, I think the increment must occur before the statement body is emitted, otherwise control flow changes within the body might result in missed increments.

Would applying a line 0 location to the profile counter increment address the verifier failure?

**Comment by dcci** [comment]
@vedantk @adrian-prantl 
while I agree that applying line zero to the increment a good thing to do, I don't think it's going to fix the verifier failure. Is there an equivalent of `line 0` for scopes? I'm not aware of it.

Aside, maybe the verifier should skip instructions with a compiler generated line?

**Comment by adrian-prantl** [comment]
> @vedantk @adrian-prantl
> while I agree that applying line zero to the increment a good thing to do, I don't think it's going to fix the verifier failure. Is there an equivalent of `line 0` for scopes? I'm not aware of it.
The "equivalent" is using `SILBuildWithScope<>(insertionpoint)` which inherits the scope from the insertion point.

> Aside, maybe the verifier should skip instructions with a compiler generated line?
Probably not, they will still bloat .debug_info needlessly.

**Comment by dcci** [comment]
Superseded by https://github.com/apple/swift/pull/21777

**Pull request closed without merging**
