### PR TITLE
Update string processing checkout for 5.7-04182022.

### PR DESCRIPTION
**Pull request by rxwei**
swift/release/5.7-04182022 will be the corresponding branch.

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please smoke test

**Review by shahmishal — APPROVED** [review]

**Comment by shahmishal** [comment]
We should also cherry-pick this change to release/5.7-04182022

**Comment by rxwei** [comment]
@swift-ci  test

**Comment by rxwei** [comment]
> We should also cherry-pick this change to release/5.7-04182022

Created https://github.com/apple/swift/pull/42609

**Comment by rxwei** [comment]
@swift-ci please test

**Pull request merged**
