### PR TITLE
Leaks runner improvements

### PR DESCRIPTION
**Pull request by gottesmm**
This PR does two different things:

1. It makes leaks runner support C-c.
2. It makes leaks runner fail nicely when a subtask segfaults instead of just throwing an IndexError.

rdar://31544274

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@erg @shahmishal 

Question. I ran python lint and it succeeded. Why is it also failing when performing smoke tests?

**Comment by gottesmm** [comment]
*Why is it failing in the smoke tests when python lint succeeded on the bot.

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by shahmishal** [comment]
smoke test has python lint test now: 

```
FAIL: Swift(macosx-x86_64) :: Python/python-lint.swift (8776 of 9637)
******************** TEST 'Swift(macosx-x86_64) :: Python/python-lint.swift' FAILED ********************
Script:
--
/usr/bin/python /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/swift/utils/python_lint.py
--
Exit Code: 1

Command Output (stdout):
--
./benchmark/scripts/Benchmark_RuntimeLeaksRunner.in:115:19: E128 continuation line under-indented for visual indent

--

********************
```

**Comment by shahmishal** [comment]
> *Why is it failing in the smoke tests when python lint succeeded on the bot.

Good question.

**Pull request merged**
