### PR TITLE
Temporarily add fixed layout to _Hasher

### PR DESCRIPTION
**Pull request by shajrawi**
This should be removed / reverted once we have resolved the performance issues - radar rdar://problem/38549901

(@lorentey as we discussed over email)

### CODE REVIEW

**Comment by shajrawi** [comment]
@swift-ci Please smoke test and merge

**Review by lorentey — APPROVED** [review]

**Comment by lorentey** [comment]
Thanks!

**Comment by shajrawi** [comment]
@swift-ci Please smoke test and merge

**Comment by shajrawi** [comment]
@swift-ci Please smoke test Linux

**Comment by shajrawi** [comment]
@swift-ci Please smoke test Linux

**Comment by shajrawi** [comment]
@swift-ci Please smoke test Linux

**Comment by shajrawi** [comment]
@swift-ci Please clean test Linux

**Pull request merged**
