### PR TITLE
[stdlib] Prototype bidirectional UTF-8 Decoding

### PR DESCRIPTION
**Pull request by dabrahams**
statemachines

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please smoke test and merge

**Comment by dabrahams** [comment]
@swift-ci Please smoke test and merge

**Comment by shahmishal** [comment]
@swift-ci Please smoke test and merge

**Comment by dabrahams** [comment]
@swift-ci Please smoke test and merge

**Comment by dabrahams** [comment]
@swift-ci Please smoke test and merge

**Comment by dabrahams** [comment]
on Tue Nov 29 2016, Jordan Rose <notifications-AT-github.com> wrote:

> jrose-apple commented on this pull request.
>
>> @@ -9,9 +9,12 @@
>  // See http://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
>  //
>  //===----------------------------------------------------------------------===//
> -// RUN: %target-run-simple-swift
> +// RUN: %target-build-swift -parse-stdlib -Xfrontend -disable-access-control %s -o %t/a.out
>
> Why do you need this? Because it won't work in general.

I was just hoping it would work around what appears to be a SILGen bug
that shows up in CI but I wasn't able (at the time) to reproduce
locally.  I'm eager to remove it, but there's not much point until the
SILGen bug is fixed.

-- 
-Dave

**Comment by jckarter** [comment]
You can avoid the problem by not using @inline(__always) for the nested functions inside UTF8.parseForward, or else making `UTF8.Classification.init` public. It looks like we mark `@inline(__always)` functions as "fragile" to export their SIL even when they're private or nested, which seems unnecessary.

**Comment by dabrahams** [comment]
@swift-ci Please smoke test and merge

**Comment by dabrahams** [comment]
@swift-ci Please smoke test and merge

**Comment by dabrahams** [comment]
@airspeedswift

**Comment by jrose-apple** [comment]
Can you move this test to validation-test? StdlibUnicodeUnittest isn't built when just running the normal tests.

**Comment by gparker42** [comment]
This test is failing on iOS. Reverting in #6010.

**Comment by dabrahams** [comment]
on Thu Dec 01 2016, Jordan Rose <notifications-AT-github.com> wrote:

> Can you move this test to validation-test? StdlibUnicodeUnittest isn't built when just running the
> normal tests.

Okay, will do.

-- 
-Dave

**Comment by gparker42** [comment]
…and macOS:
https://ci.swift.org/job/oss-swift_tools-RA_stdlib-RD_test-simulator/2433/

Might be an intermittent failure.

**Pull request merged**
