### PR TITLE
[Sema] Propagate invalid bit during default param checking

### PR DESCRIPTION
**Pull request by davezarzycki**
Fixes: https://bugs.swift.org/browse/SR-11085

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke check

**Comment by CodaFi** [comment]
Sure, this is one way to do it. I think teaching default argument checking to be more careful with invalid parameters is another. What do you think @hamishknight?

**Review by hamishknight — COMMENTED** [review]
Unfortunately, I don't believe this will fix multi-file cases given we only check default arguments as a part of the parameter list for primary files. For example:

```swift
// a.swift
func foo(_ x: String = #line) {}

// b.swift
foo()
```

If we compile b.swift as a primary file, we'll still hit the assertion in CSApply as we haven't otherwise type-checked the default param.

My plan for fixing this was to move the caller-side default type-checking logic out of CSApply and into a request that can be called from SILGen when it wants to lower the default arg. That way we can still produce a complete solution for the apply even if the default arg is invalid (and we don't want to involve the default arg checking as a part of solving, as we don't want it to affect the solution's score). I'm waiting for https://github.com/apple/swift/pull/27756 to land first though.

**Comment by xedin** [comment]
@theblixguy had a PR which checked default arguments as part of the constraint system and could produce a nice tailored diagnostic for it, unfortunately in come cases that `argument conversion` relation should adjust the score so we had to revert it, but I think it's possible to avoid that behavior - https://github.com/apple/swift/pull/26973

**Comment by hamishknight** [comment]
@xedin I was planning on using `DefaultArgumentExpr` to represent both caller-side and callee-side defaults, which would allow us to produce a valid solution for an invalid caller-side default (which is currently what we already do for callee defaults). IMO the constraint system shouldn't care about the difference between these defaults, that's something SILGen should take care of.

As a nice bonus, this will also allow us to remove `CallerDefaultArgumentExpr` :)

**Comment by xedin** [comment]
I'll be happy with anything with doesn't require a call to `typeCheckExpression` in CSApply and produces good diagnostics :)

**Comment by davezarzycki** [comment]
Looks like people have better ideas. Closing.

**Pull request closed without merging**
