### PR TITLE
Not for merging

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test compiler performance

**Comment by slavapestov** [comment]
@swift-ci Please smoke test compiler performance

**Comment by slavapestov** [comment]
@swift-ci Please test compiler performance

**Comment by slavapestov** [comment]
@swift-ci Please smoke test compiler performance

**Comment by slavapestov** [comment]
> Unexpected test results, excluded stats for SourceKittenFramework, StencilSwiftKit, AMScrollingNavbar, ProcedureKit, GRDB, JSQDataSourcesKit, AsyncNinja, ReactiveCocoa, IBAnimatable, ObjectMapper

@graydon What does this mean?

**Comment by graydon** [comment]
@slavapestov it means that those projects had one or more failures during the set of 24 runs (2 compilers * 3 runs for noise prevention * 4 configurations), so all stats associated with all runs of those projects were excluded from analysis.

It's a warning that you might want to look into the failures, but also a reassurance that the data wasn't contaminated by partial counters from failed runs.

(If you look in the detailed stats you'll see there were still plenty of values collected to be reasonably confident in the results overall)

**Comment by graydon** [comment]
@slavapestov though if the change is truly a no-op, there are surprisingly many nonzero deltas! short of possible nondeterminism in the build, those deltas should all be zero (especially the counters).

**Comment by slavapestov** [comment]
@graydon it would be nice if those build failures were visible somewhere. Do you already skip XFAILd projects?

**Comment by graydon** [comment]
@slavapestov xfails are already skipped yes. you're right we should probably save-as-artifacts all the logs from those builds, and in fact you have already filed this as rdar://36644285 :)

**Comment by slavapestov** [comment]
@graydon Sorry my bad :)

**Pull request closed without merging**
