### PR TITLE
[sil-generic-specializer] Add @_semantics("optimize.sil.specialize.generic.partial.never") to disable partial specialization on specific functions

### PR DESCRIPTION
**Pull request by swiftix**
This new @_semantics is used to annotate some very big functions in the standard library. It reduced the code size of the stdlib by 2%.

### CODE REVIEW

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please smoke benchmark

**Comment by swiftix** [comment]
@swift-ci please smoke benchmark

**Comment by swiftix** [comment]
@swift-ci please smoke benchmark

**Comment by swiftix** [comment]
@swift-ci please smoke benchmark

**Comment by swiftix** [comment]
@swift-ci please smoke benchmark

**Comment by atrick** [comment]
@swiftix please add this (and any other missing attributes) to HighLevelSILOptimizations.rst.

**Pull request merged**
