### PR TITLE
[stdlib] Improve the flatMap deprecation message

### PR DESCRIPTION
**Pull request by moiseev**
<rdar://problem/36555646>

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by airspeedswift** [comment]
I wonder whether it should read "_this variant_ of flatMap is deprecated"

**Comment by jrose-apple** [comment]
That part comes from the compiler. It'd have to detect that there were other possible `flatMap`s around, or we'd have to add a flag to the availability attribute.

**Comment by airspeedswift** [comment]
Oh right.  I wonder if there’s any non-tortured phrasing to increase the clarity that it’s just this one not all flatmaps. But this might be as clear as we can get.

**Pull request merged**
