### PR TITLE
[WIP] Perftest from sib

### PR DESCRIPTION
**Pull request by gottesmm**
This is a pull request that will enable us to compile the PerfTestSuite solely from *.sib files.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci Please test OS X smoke test

**Comment by gottesmm** [comment]
@swift-ci Please test OS X smoke test

**Comment by gottesmm** [comment]
@swift-ci Please smoke test OS X platform

**Comment by DougGregor** [comment]
WIP from February; still relevant?

**Comment by gottesmm** [comment]
This is pretty old. If I look into it, I will do it fresh.

**Pull request closed without merging**
