### PR TITLE
Enable -Onone for tests that pass already.

### PR DESCRIPTION
**Pull request by bgogul**

### CODE REVIEW

**Comment by bgogul** [comment]
@swift-ci please test tensorflow

**Comment by mhong** [comment]
Nice!

Discussed with Gogul. One option to ensure no sends/recvs (or deabstraction) regression is to add a counter on the # sends/recvs, and check the counter does not change when turning off -O.

Also it might be possible for a lowered graph to be larger (less optimized) -when we turn off -O. e.g.
if we have a sequence of SSA values that can be const-folded:
```swift
let x = Tensor<Float>(1.0)
let y = x
let z = y
```

We are not so much concerned with performance regression due to larger graph at this point (grappler will likely performance similar optimization to the graph as Swift optimizer pipeline via -O), but debugging a larger graph (or displaying on tensorboard) could be a bit more work.

I don't think the concern on graph size should block the test transition though, as we can easily turn -O back on when we are debugging a graph_def.

**Review by mhong — APPROVED** [review]

**Comment by rxwei** [comment]
> Discussed with Gogul. One option to ensure no sends/recvs (or deabstraction) regression is to add a counter on the # sends/recvs, and check the counter does not change when turning off -O.

Having something like is a good idea, but that will not work because `debug_value` will trigger send/receive for every named variable in `-Onone` builds.

**Comment by mhong** [comment]
Can we avoid incrementing the counter for debug_value users? Another option is to introduce another compiler flag where we generate debug_value (e.g. -g). Otherwise no debug_value in -Onone mode.

**Comment by rxwei** [comment]
> Can we avoid incrementing the counter for debug_value users? 

Avoid counting sends-to-host that are operands to `debug_value` is the best solution IMO.

> Another option is to introduce another compiler flag where we generate debug_value (e.g. -g). Otherwise no debug_value in -Onone mode.

@lattner pointed out earlier that `-g` shouldn't change the code generated. It only changes debug metadata. So code emitted with `-Onone -g` shouldn't be different than just `-Onone`.

**Comment by dan-zheng** [comment]
I'll close this PR now since [graph program extraction code](https://github.com/apple/swift/pull/24418) has been deleted.

**Pull request closed without merging**
