### PR TITLE
[AutoDiff] Add negative tests for TF-952.

### PR DESCRIPTION
**Pull request by dan-zheng**
TF-952: incorrect zero derivatives regarding array literal initialization.
Add two "two element" array literal negative tests and activity analysis tests.
Gardening included.

---

Note: I'll start a partial fix soon, fixing one of the tests (`twoElementLiteralAddress`).

### CODE REVIEW

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Review by marcrasi — APPROVED** [review]

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow linux cpu

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow linux cpu

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow linux cpu

**Comment by dan-zheng** [comment]
Merging to unblock progress. Tested locally on macOS.

**Pull request merged**
