### PR TITLE
[SwiftSyntax] Allow for visiting SyntaxCollections

### PR DESCRIPTION
**Pull request by harlanhaskins**
This PR allows for visitors and syntax rewriters to visit and rewrite SyntaxCollections.

### CODE REVIEW

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test

**Review by nkcsgexi — APPROVED** [review]
LGTM!

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test

**Comment by harlanhaskins** [comment]
Linux failure seems unrelated.

@swift-ci please smoke test Linux platform

**Pull request merged**
