### PR TITLE
[stdlib] Revert first(where:) to use for-in loop

### PR DESCRIPTION
**Pull request by natecook1000**
The implementation for `first(where:)` uses `forEach` and throws an error to escape execution—this works properly, but when an Xcode breakpoint is added for Swift errors, that `throw` triggers the breakpoint. The stdlib doesn't typically use errors like this, so this PR reverts this implementation to a more traditional `for`-`in` loop.

Resolves [SR-3166](https://bugs.swift.org/browse/SR-3166).

### CODE REVIEW

**Comment by natecook1000** [comment]
@swift-ci Please smoke test

**Comment by dtorres** [comment]
the _StopIteration enum is unused with this change. Might as well remove it too

**Comment by jtbandes** [comment]
Interesting to read the comments on the ticket, in particular @russbishop:

> IIRC I did it this way to avoid allocating an iterator for types where that is expensive; the type itself may have a more optimal implementation of forEach since it can guarantee nothing escapes... the throwing is just a way to jump out of the forEach and has minimal overhead.

Has this concern been addressed? Is there anything we can benchmark?

**Comment by natecook1000** [comment]
@swift-ci Please smoke test

**Comment by natecook1000** [comment]
@jtbandes That _is_ a good question. I don't think we have any tests that show this issue in practice. I also doubt we can create any tests that would show a difference for standard library types, since we don't rely on `forEach` as an optimization anywhere, from either the concrete sequence side (the only types that provide a truly custom `forEach` are the flattening collections) or on the algorithmic side (the other sequence methods just use `for`-`in`).

**Comment by natecook1000** [comment]
@swift-ci Please smoke test

**Comment by russbishop** [comment]
@jtbandes The concern was theoretical and came up during review. I'm fine with putting this back to the original implementation, a type that has these concerns can provide its own implementation.

**Comment by moiseev** [comment]
It would perhaps be beneficial to mention these considerations in the code comment. What do you think?

**Comment by gribozavr** [comment]
I think there is a bigger question here.  Seems like if we take the argument to its logical conclusion, it means that code can not throw errors unless they are intended for user's code to handle.  That is, a framework can't call another framework that throws, catch that error and handle it without notifying user's code.  This does not seem right to me.  Because of this, I don't think LLDB's behavior to break on every `throw` is very useful.

Also, think about it like this: LLDB does not have a parallel feature to break on `-[NSError init:]`, does it?  This would be the Objective-C equivalent of Swift's `throw`.  Try putting a breakpoint on `-[NSError init:]` (and other initializers?), and see how frequently it would get hit (I have no idea).  This will give you a taste of how frequently "break on throw" will be hit in Swift when an average app starts to depend on more and more Swift libraries.

**Comment by gribozavr** [comment]
> I don't think we have any tests that show this issue in practice.

A tree type would be a good example of a type that would benefit from this optimization.

> a type that has these concerns can provide its own implementation.

It can't, because `first(where:)` is not a protocol requirement.  (And we don't want algorithms to become protocol requirements just because they depend on enumerating elements -- because then almost all of them would become protocol requirements.)

**Comment by natecook1000** [comment]
> I think there is a bigger question here. Seems like if we take the argument to its logical conclusion, it means that code can not throw errors unless they are intended for user's code to handle. That is, a framework can't call another framework that throws, catch that error and handle it without notifying user's code. This does not seem right to me. Because of this, I don't think LLDB's behavior to break on every throw is very useful.

> Also, think about it like this: LLDB does not have a parallel feature to break on -[NSError init:], does it? This would be the Objective-C equivalent of Swift's throw. Try putting a breakpoint on -[NSError init:] (and other initializers?), and see how frequently it would get hit (I have no idea). This will give you a taste of how frequently "break on throw" will be hit in Swift when an average app starts to depend on more and more Swift libraries.

LLDB does have that feature, since you can break on essentially any call (`viewDidLoad` is a fun one)—breakpoints like that (and the new "Swift Errors" breakpoint) are mostly only useful when they have additional constraints. For "break on throw" you can specify a specific error type that you want to break on—without that I agree with you that it isn't terribly useful. I think the "Swift Errors" breakpoint is needed specifically because Swift's errors operate differently from the way NSErrors are creating and can't be caught that way.

All that said, I'm having second thoughts about this PR, since "no throwing errors in the standard library" is a bummer of a limitation. I haven't even been able to reproduce this behavior in the latest Xcode beta—anyone else?

**Comment by natecook1000** [comment]
Closing for now since it isn't clear whether this is still an issue.

**Pull request closed without merging**
