### PR TITLE
[Dependency Scanning] Simplify the persistent dependency scanning cache

### PR DESCRIPTION
**Pull request by artemcm**
- Key into a global (shared) dependency scanning cache via context hash.
Introduces a concept of a dependency scanning action context hash, which is used to select an instance of a global dependency scanning cache which gets re-used across multiple dependency scanning actions. In practice, this means that `GlobalModuleDependenciesCache`'s map is keyed with a Context Hash that a given `CompilerInvocation` knows how to produce. 

- Removes disambiguation of 'GlobalModuleDependenciesCache' results by search path set
Previously, `GlobalModuleDependenciesCache ` was keyed by triple and returned a collection of results, one for each potential search path set. This is no longer necessary with the above change since the cache is always configured for the current scanning context hash, which includes the search path set.

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
@swift-ci test Linux Platform

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
@swift-ci test

**Review by nkcsgexi — APPROVED** [review]
Nice abstraction!

**Comment by artemcm** [comment]
@swift-ci test Windows platform

**Pull request merged**
