### PR TITLE
ASTScope: Clean up handling of PatternBindingDecls and AccessorDecls

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Review by davidungar — APPROVED** [review]
It will be great if it works; I hope things have changed enough since the original was written that it will.

Is there still an assertion check somewhere to detect the overlapping source ranges if the bugs ever come back? If not, what will be the symptom?

**Comment by slavapestov** [comment]
@davidungar Yes, when I disabled the specialized check for PatternBindingDecls, another assertion fired later on about overlapping source ranges.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Pull request merged**
