### PR TITLE
[runtime] Register a hook for class name lookup from libobjc

### PR DESCRIPTION
**Pull request by gparker42**
libobjc needs to look up classes by name. Some Swift classes, such as
instantiated generics and their subclasses, are created only on demand.
Now a by-name lookup from libobjc counts as a demand for those classes.

rdar://problem/27808571

### CODE REVIEW

**Comment by gparker42** [comment]
@slavapestov I only have tests for generic classes here; are there resilience cases that we can test now?

**Comment by gparker42** [comment]
@swift-ci please test

**Comment by slavapestov** [comment]
@gparker42 Look at how test/Interpreter/objc_class_resilience.swift builds and links test/Inputs/resilient_classes.swift and test/Inputs/resilient_structs.swift as a dylib with resilience enabled. What you want to do is test two cases:

- Class is defined inside your test itself, and it has a field whose type is a resilient struct. This triggers the runtime in-place initialization mechanism. To make sure the class metadata is properly initialized, try creating an instance of the class and access a field.

- Class is defined inside your test itself, and inherits from a class in another resilient module. This triggers the runtime relocation mechanism.

**Review by slavapestov — APPROVED** [review]
LGTM, but more tests will always be good of course

**Review by slavapestov — APPROVED** [review]

**Pull request merged**
