### PR TITLE
[AST] Choose an implied conformance source next to the type, if possible.

### PR DESCRIPTION
**Pull request by huonw**
If a conformance to a protocol is implied by several other
conformances (i.e. protocol P: Equatable {} and protocol Q: Equatable {} and a
type declares conformance to both P and Q), we should choose a source that's in
the same file as the type, if we can, because automatic synthesis of
conformances (for Equatable, Hashable, etc.) only works in that case.

Fixes rdar://problem/41852654.

### CODE REVIEW

**Comment by huonw** [comment]
@swift-ci please test source compatibility

**Comment by huonw** [comment]
The failure is ReactiveCocoa, which isn't caused by this PR (rdar://problem/41859797).

**Comment by slavapestov** [comment]
@huonw The ReactiveCocoa failure should now be fixed.

**Comment by huonw** [comment]
@swift-ci please test source compatibility

**Comment by huonw** [comment]
Those failures aren't related either "error: Failed to clean build folder: The file couldn’t be saved.".

**Review by slavapestov — APPROVED** [review]

**Pull request merged**
