### PR TITLE
[Constraint system] Turn explicit loop into llvm::any_of.

### PR DESCRIPTION
**Pull request by rudkx**

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
Bonus: we have an `llvm::any_of` that does the `begin`/`end` for you.

**Comment by rudkx** [comment]
Ah, I'll try that out. Thanks.

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Pull request merged**
