### PR TITLE
[SourceKit] Update for primary associated types

### PR DESCRIPTION
**Pull request by rintaro**
* InterfaceGen reports a primary associated type as a reference to the 'associatedtype' declaration
* CursorInfo on a primary associated type returns information of the 'associatedtype' declaration

rdar://93275458

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Review by bnbarham — APPROVED** [review]

**Comment by rintaro** [comment]
@QuietMisdreavus With this change, `DeclarationFragmentPrinter::printTypeRef()` is now called on primary associated types, and also `SymbolGraphASTWalker` might be affected by the `SourceEntityWalker.cpp` changes (since it's not overriding `visitDeclReference()`, probably not).

Could you double check? Let me know you need additional test, or you can add test cases for SymbolGraph after merging it as you need.

**Comment by QuietMisdreavus** [comment]
@rintaro Can you take the snippet you're using for Index and SourceKit tests and use it in a SymbolGraph test? I can build up a specific one tomorrow if you need, but copying the build lines from something like `test/SymbolGraph/Symbols/Names.swift` and inspecting the graph that comes out will probably suffice.

**Comment by rintaro** [comment]
@QuietMisdreavus Does this look good? If it looks good, let me merge this as is, and could you add a test case after that if needed?

```swift
// RUN: %empty-directory(%t)
// RUN: %target-build-swift %s -module-name MyModule -emit-module -emit-module-path %t/
// RUN: %target-swift-symbolgraph-extract -module-name MyModule -I %t -pretty-print -output-dir %t

public protocol WithPrimary<Assoc> {
   associatedtype Assoc
}
```
Result
<details>

```json
{
  "metadata": {
    "formatVersion": {
      "major": 0,
      "minor": 5,
      "patch": 3
    },
    "generator": "Swift version 5.8-dev (LLVM 278d67f38c6a910, Swift 4ae16bfef7bb240)"
  },
  "module": {
    "name": "MyModule",
    "platform": {
      "architecture": "x86_64",
      "vendor": "apple",
      "operatingSystem": {
        "name": "macosx",
        "minimumVersion": {
          "major": 10,
          "minor": 9,
          "patch": 0
        }
      }
    }
  },
  "symbols": [
    {
      "kind": {
        "identifier": "swift.protocol",
        "displayName": "Protocol"
      },
      "identifier": {
        "precise": "s:8MyModule11WithPrimaryP",
        "interfaceLanguage": "swift"
      },
      "pathComponents": [
        "WithPrimary"
      ],
      "names": {
        "title": "WithPrimary",
        "navigator": [
          {
            "kind": "identifier",
            "spelling": "WithPrimary"
          }
        ],
        "subHeading": [
          {
            "kind": "keyword",
            "spelling": "protocol"
          },
          {
            "kind": "text",
            "spelling": " "
          },
          {
            "kind": "identifier",
            "spelling": "WithPrimary"
          }
        ]
      },
      "declarationFragments": [
        {
          "kind": "keyword",
          "spelling": "protocol"
        },
        {
          "kind": "text",
          "spelling": " "
        },
        {
          "kind": "identifier",
          "spelling": "WithPrimary"
        },
        {
          "kind": "text",
          "spelling": "<"
        },
        {
          "kind": "typeIdentifier",
          "spelling": "Assoc"
        },
        {
          "kind": "text",
          "spelling": ">"
        }
      ],
      "accessLevel": "public"
    },
    {
      "kind": {
        "identifier": "swift.associatedtype",
        "displayName": "Associated Type"
      },
      "identifier": {
        "precise": "s:8MyModule11WithPrimaryP5AssocQa",
        "interfaceLanguage": "swift"
      },
      "pathComponents": [
        "WithPrimary",
        "Assoc"
      ],
      "names": {
        "title": "Assoc",
        "subHeading": [
          {
            "kind": "keyword",
            "spelling": "associatedtype"
          },
          {
            "kind": "text",
            "spelling": " "
          },
          {
            "kind": "identifier",
            "spelling": "Assoc"
          }
        ]
      },
      "declarationFragments": [
        {
          "kind": "keyword",
          "spelling": "associatedtype"
        },
        {
          "kind": "text",
          "spelling": " "
        },
        {
          "kind": "identifier",
          "spelling": "Assoc"
        }
      ],
      "accessLevel": "public"
    }
  ],
  "relationships": [
    {
      "kind": "requirementOf",
      "source": "s:8MyModule11WithPrimaryP5AssocQa",
      "target": "s:8MyModule11WithPrimaryP"
    }
  ]
}
```

</details>

**Comment by QuietMisdreavus** [comment]
@rintaro That looks great, thanks! I can add the test once this is merged.

**Pull request merged**
