### PR TITLE
Update checkout for TensorFlow repos.

### PR DESCRIPTION
**Pull request by rxwei**
* https://github.com/tensorflow/tensorflow/commit/5e8df789cc30098d791475c14a623ec68b50b4ed
* https://github.com/tensorflow/swift-bindings/commit/0957744551614e433dbabc725cba29ff5ddb91d3
* https://github.com/tensorflow/swift-apis/commit/18f937191bdc9ddbe5df8f99f0dc64e1a4c0ffab

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Review by dan-zheng — APPROVED** [review]

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow macOS

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow linux

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by eaplatanios** [comment]
@rxwei the failures were fixed in my latest commit [here](https://github.com/tensorflow/swift-apis/pull/70).

**Comment by rxwei** [comment]
Can you fix them in a separate patch? The PR description says "This is a work-in-progress PR that also depends on the advanced indexing PR". Since it's depends on other changes that have not been merged, we cannot merge it.

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow macOS

**Comment by rxwei** [comment]
@eaplatanios This is still not compiling for some reason.

**Comment by eaplatanios** [comment]
There were some more issues. Apparently there are two padding types now. It should have been fixed [here](https://github.com/tensorflow/swift-apis/pull/74), but we may be able to improve the API by also adding support for explicit paddings to the pooling ops.

**Comment by eaplatanios** [comment]
@rxwei This should compile fine after [this PR](https://github.com/tensorflow/swift-apis/pull/74) is merged.

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow Linux GPU

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow Linux GPU

**Comment by eaplatanios** [comment]
@rxwei There seem to be some test failures in the CI, but I can't currently access the CI web interface for some reason and have no idea what fails.

**Comment by eaplatanios** [comment]
@rxwei now I am able to access the failures. It seems that some tests are checking what ops get added to a TF graph and they are using the `Conv2D` op. Since the op now has an extra attribute, these fail. Since I cannot make edits to this PR, could you please fix those?

**Comment by dan-zheng** [comment]
I'll look into fixing the failures now. It seems to be a matter of updating test cases.

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow linux

**Comment by brettkoonce** [comment]
🍕

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by dan-zheng** [comment]
All tests finally pass! Merging.
cc @eaplatanios, FYI in case this unblocks some of your work

**Pull request merged**
