### PR TITLE
[build-script] Stop forcing the use of libcxx

### PR DESCRIPTION
**Pull request by davezarzycki**
Any C++ standard library is good enough these days.

### CODE REVIEW

**Comment by davezarzycki** [comment]
Let's do a full test to see if anything has a lingering dependency on libcxx being explicit.

@swift-ci please test

**Comment by jrose-apple** [comment]
Looks unrelated. Actually, those are timeouts from turning on resilience, whoops. (@slavapestov)

**Comment by davezarzycki** [comment]
Thanks @jrose-apple for checking. Given that you asked me to run this topic by the forums, how long do you want to wait for people to speak their mind about this topic?

**Comment by jrose-apple** [comment]
I'm not sure. Maybe till the end of the week? The other possibility would be to tag specific people on the forums who work on non-Apple platforms, like the IBM folks, and see if they have any specific concerns. But it's always something we can roll back if it causes problems.

(We really need that secondary buildbot suite…)

**Comment by davezarzycki** [comment]
Until the end of the week sounds fine. Somebody who works on Windows has already said via GitHub that the MS C++ standard library works fine, so now we're up three known working libraries. If it were up to me, and given that the cost of reverting this is super low, I'd just merge this PR at this point.

**Comment by davezarzycki** [comment]
Also, I don't know who the IBM folks are.

**Comment by davezarzycki** [comment]
@swift-ci please smoke test osx

**Comment by jrose-apple** [comment]
I can't reproduce [the two timeouts](https://ci.swift.org/job/swift-PR-osx/3648/) locally (though admittedly with my own preset, not the builder's). Maybe a clean test'll clear it up?

@swift-ci Please clean smoke test macOS

**Comment by jrose-apple** [comment]
@swift-ci Please clean smoke test OS X

**Comment by davezarzycki** [comment]
@swift-ci please clean smoke test OS X

**Comment by davezarzycki** [comment]
Maybe something is out of sync on the macOS side. I'm rebasing and trying again.

@swift-ci please smoke test

**Comment by davezarzycki** [comment]
The PowerPC and S390 folks at IBM signed off on this via the forums. I'm going to merge this now. We can always revert this.

**Pull request merged**
