### PR TITLE
[API Notes] Update test for new location of API notes in frameworks

### PR DESCRIPTION
**Pull request by DougGregor**

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by shahmishal** [comment]
One test failure: 

```
******************** TEST 'Swift(macosx-x86_64) :: ClangModules/objc_factory_method.swift' FAILED ********************
Script:
--
rm -rf /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/ClangModules/Output/objc_factory_method.swift.tmp && mkdir -p /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/ClangModules/Output/objc_factory_method.swift.tmp
/Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/buildbot_incremental/swift-macosx-x86_64/bin/swiftc -frontend -target x86_64-apple-macosx10.9  -module-cache-path '/var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/swift-testsuite-clang-module-cacheeBW95p' -sdk /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk   -sdk '/Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/swift/test'/Inputs/clang-importer-sdk  -I /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/ClangModules/Output/objc_factory_method.swift.tmp  -emit-module -o /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/ClangModules/Output/objc_factory_method.swift.tmp '/Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/swift/test'/Inputs/clang-importer-sdk/swift-modules/ObjectiveC.swift && /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/buildbot_incremental/swift-macosx-x86_64/bin/swiftc -frontend -target x86_64-apple-macosx10.9  -module-cache-path '/var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/swift-testsuite-clang-module-cacheeBW95p' -sdk /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk   -sdk '/Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/swift/test'/Inputs/clang-importer-sdk  -I /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/ClangModules/Output/objc_factory_method.swift.tmp  -emit-module -o /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/ClangModules/Output/objc_factory_method.swift.tmp '/Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/swift/test'/Inputs/clang-importer-sdk/swift-modules/CoreGraphics.swift && /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/buildbot_incremental/swift-macosx-x86_64/bin/swiftc -frontend -target x86_64-apple-macosx10.9  -module-cache-path '/var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/swift-testsuite-clang-module-cacheeBW95p' -sdk /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk   -sdk '/Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/swift/test'/Inputs/clang-importer-sdk  -I /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/ClangModules/Output/objc_factory_method.swift.tmp  -emit-module -o /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/ClangModules/Output/objc_factory_method.swift.tmp '/Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/swift/test'/Inputs/clang-importer-sdk/swift-modules/Foundation.swift
/Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/buildbot_incremental/swift-macosx-x86_64/bin/swiftc -frontend -target x86_64-apple-macosx10.9  -module-cache-path '/var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/swift-testsuite-clang-module-cacheeBW95p' -sdk /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk   -sdk '/Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/swift/test'/Inputs/clang-importer-sdk  -I /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/ClangModules/Output/objc_factory_method.swift.tmp  -target x86_64-apple-macosx10.51 -parse /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/swift/test/ClangModules/objc_factory_method.swift -verify
--
Exit Code: 1

Command Output (stderr):
--
/Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/swift/test/ClangModules/objc_factory_method.swift:95:26: error: unexpected error produced: 'widgetController()' is unavailable: use object construction 'NCWidgetController()'
  _ = NCWidgetController.widgetController()
                         ^
/Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/swift/test/ClangModules/objc_factory_method.swift:96:19: error: unexpected error produced: 'processInfo()' is unavailable: use object construction 'NSProcessInfo()'
  _ = ProcessInfo.processInfo()
                  ^

--

********************

```

**Comment by DougGregor** [comment]
Looks like it needed a Clang-side fix as well, which just made it into stable.

**Comment by shahmishal** [comment]
Thanks!

**Pull request merged**
