### PR TITLE
Split off objc_method / objc_super_method from class_method / super_method

### PR DESCRIPTION
**Pull request by slavapestov**
This is the first part of a refactoring to make Objective-C dispatch explicit in SIL, instead of relying on a poorly-named 'volatile' bit in the class_method / super_method / witness_method instructions.

The next step is to switch Objective-C protocol method calls over to use objc_method, since witness_method models Objective-C dispatch poorly.

The reason I'm doing this is because it is a general cleanup we've talked about for a while, and also because we might switch to a resilient method dispatch strategy where it would be advantageous to change class_method to take an isa pointer, and replace super_method with a super_metatype + class_method sequence. Since this separation doesn't make sense for Objective-C, I'm going to land this refactoring first.

Also, it might be possible to eliminate the dynamic_method instruction entirely now, but I haven't looked into that yet.

Unfortunately the new instructions do introduce a lot of new code, but some upcoming changes I'm planning on making to SILGen will eliminate the duplication for lowering call expressions a fair bit.

### CODE REVIEW

**Comment by slavapestov** [comment]
@rjmccall @jckarter Does this refactoring look reasonable, or at least not offensively bad?

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please benchmark

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please benchmark

**Comment by jrose-apple** [comment]
This broke a number of bots, such as https://ci.swift.org/job/oss-swift_tools-R_stdlib-RD_test-simulator/324/. I'm not sure how this wasn't caught by "please test" but there's definitely a problem here.

**Comment by jrose-apple** [comment]
Oops, hang on, sorry. Not this PR.

**Comment by jckarter** [comment]
This looks like good progress, thanks @slavapestov! Ultimately I think we should also go as far as making the instructions just take a selector (in whatever form the `@objc` attribute uses). That would let us eventually replace `dynamic_method[_br]` completely with this, plus a `responds_to_selector` instruction.

**Comment by gottesmm** [comment]
I haven't looked, but just in case... does this require any updates to SIL.rst?

Michael

**Pull request merged**
