### PR TITLE
[stdlib] Rename "PrivateDarwin" to "PrivateLibc"

### PR DESCRIPTION
**Pull request by modocache**
SwiftPrivateDarwinExtras is used by non-Darwin platforms as well; its name is misleading. Rename it to SwiftPrivateLibcExtras, which is closer to its actual function.

### CODE REVIEW

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by modocache** [comment]
Hmm, looks like the OS X tests are still broken due to the SwiftPM... glad to see it worked on Linux, though!

**Comment by dduan** [comment]
@modocache Yep. All CI runs today fail reliably on this one.

**Comment by gribozavr** [comment]
All other tests passed, though.  Should be good to merge!

**Comment by modocache** [comment]
Excellent, thanks!

**Pull request merged**
