### PR TITLE
[Foundation] Rework NSFastEnumerationIterator to be more performant

### PR DESCRIPTION
**Pull request by phausler**
Previously the implementation of NSFastEnumerationIterator would cause many allocations and was overly complex; leading to poor performance in certain cases like DirectoryEnumerator etc. This version instead acts more similarly to how the objc for-in syntax works.
Resolves:
rdar://problem/30905263

and partially addresses some of the concerns backing:
rdar://problem/30195113

### CODE REVIEW

**Comment by phausler** [comment]
@swift-ci test

**Comment by phausler** [comment]
@jckarter This includes the changes you were concerned about previously with the iterator.

**Comment by jckarter** [comment]
This will work if you're certain that the only inner pointer to the struct will be the exact itemsPtr. I still think it would be more robust, and better for the platform as a whole, to investigate whether stack promotion is already taking effect on the class-based iterator and make it work if it isn't already.

**Comment by phausler** [comment]
From what I could tell stack promotion was not occurring. Pulling this out and building in whole module optimization it was invoking malloc multiple times; I presumed since it is a reference type that was perfectly valid behavior. (which from a performance standpoint is definitely not)

**Comment by jckarter** [comment]
@eeckstein Is there something obvious blocking stack promotion of NSFastEnumerator classes in "for" loops?

**Comment by eeckstein** [comment]
Is this an objc class? We only do stack promotion for native swift classes.

**Comment by phausler** [comment]
the previous code was `final public class NSFastEnumerationIterator : IteratorProtocol` so it certainly should not have been `@objc` or inherited from NSObject etc.

**Comment by eeckstein** [comment]
Can you file a radar with an example for-loop where stack promotion does not occur (although it should)?

**Comment by phausler** [comment]
I am not fully certain where the exact set of failures stem from but there are definitely more problems than just stack promotion here.

rdar://problem/31685067

I could revert this back to a final class since the overall change is much more performant even without the stack based iterator. In practice collections do not carry huge amounts of elements but when they do this is a pretty gnarly bottleneck in that the previous code calls malloc way too many times.

**Pull request merged**
