### PR TITLE
SILGen: Don't override the SourceLoc for magic identifiers in stored property initializers.

### PR DESCRIPTION
**Pull request by jckarter**
Explanation: Refactoring stored property initializers to reuse the codegen for default argument generators caused them to accidentally inherit the suppression of default magic literal source locations, causing `#file` etc. to regress to empty values inside initializer expressions.

Scope: Regression from 3.0

Issue: SR-4325, rdar://problem/31483404

Risk: Low

Testing: Swift CI, test case from Jira

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
LGTM

**Pull request merged**
