### PR TITLE
[Sema] Descriptor for argument of PreCheckFunctionBuilderRequest

### PR DESCRIPTION
**Pull request by rintaro**
Follow-up to https://github.com/apple/swift/pull/32946#issuecomment-660262187

### CODE REVIEW

**Review by CodaFi — APPROVED** [review]

**Comment by rintaro** [comment]
@hamishknight @CodaFi I thought this is effectively NFC. But it crashes `test/Constraints/function_builder.swift` with
```
Assertion failed: (!isRecording && "Probably not a good idea to allow nested recording"), function replay, file /Users/rintaro/Repositories/swift-oss/swift/lib/AST/Evaluator.cpp, line 451.
```
What am I doing wrong?

**Comment by CodaFi** [comment]
We can try relaxing this invariant, since it's only supposed to prevent a request from re-entrantly calling the recording continuation.

```
DependencyCollector collector{*this};
{
  llvm::SaveAndRestore<bool> restore(isRecording, true);
  rec(collector);
  if (collector.empty()) {
    return;
  }
}
```

**Comment by rintaro** [comment]
@CodaFi I suppose the code you mentioned is in `evaluator::DependencyRecorder::record`, right? That doesn't resolve the crash. BTW, the assertion is in the one in `evaluator::DependencyRecorder::replay` https://github.com/apple/swift/blob/7b14c1dad735cbd357c739fae59a116b7d2249ce/lib/AST/Evaluator.cpp#L448-L452

**Comment by hamishknight** [comment]
It sounds like the call to `getBody()` is firing off a request in the equality and hashing functions while we're handling request dependencies. I'm not sure if we want to support this kind of re-entrant evaluation as it might cause iterator invalidation. Perhaps we should call `getBody()` when the descriptor is constructed and store it as a property? At least it's still encapsulated rather than being a direct input of the request.

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Review by hamishknight — APPROVED** [review]
LGTM!

**Comment by rintaro** [comment]
Windows: [Build Status](https://ci-external.swift.org/view/Pull%20Request/job/swift-PR-windows/5354/)

**Pull request merged**
