### PR TITLE
[DNM] SIMD, take 2

### PR DESCRIPTION
**Pull request by stephentyrone**
Updated SIMD implementation, based on feedback from first round of review.

This approach, suggested by Chris, is probably more flexible in the long run, but in the short-term we'll have some fairly ugly codegen with -Onone (-O builds are mostly OK except where masks come into it). We'll need some `@_semantics` wizardry to make this really work, but it definitely lets us have significantly less boilerplate going forward.

Under discussion as SE-0229

### CODE REVIEW

**Comment by rudkx** [comment]
Can you make sure to test the validation tests of a release no-assertions build to ensure they pass after the new overloads are added?

Specifically the tests in `validation-test/Sema/type_checker_perf`?

Those run on one of the builders but do not get tested by the normal PR testing.

**Comment by stephentyrone** [comment]
@rudkx Yup. There's a little bit of additional cleanup to do and I want to rebase on @rxwei's `AdditiveArithmetic` changes, and then I'll start in on that.

**Comment by lattner** [comment]
@rxwei FYI, this is the updated patch with some renamings to consider if you are interested.

**Comment by rxwei** [comment]
The proposal hasn't been updated to reflect the implementation. I have comments (many, i think) but I'd like to quote contents of the proposal instead of the PR.

**Comment by stephentyrone** [comment]
@swift-ci Please test

**Comment by stephentyrone** [comment]
@swift-ci Please test

**Comment by stephentyrone** [comment]
@swift-ci please test source compatibility

**Comment by stephentyrone** [comment]
@swift-ci Please test

**Comment by stephentyrone** [comment]
@swift-ci please test

**Comment by stephentyrone** [comment]
@swift-ci please test

**Comment by stephentyrone** [comment]
@swift-ci please test source compatibility

**Comment by stephentyrone** [comment]
@swift-ci Please test OS X platform

**Comment by stephentyrone** [comment]
@swift-ci please test

**Comment by stephentyrone** [comment]
@swift-ci please test OS X

**Comment by gottesmm** [comment]
@stephentyrone woot!

**Comment by xedin** [comment]
I think this should have been reviewed by either me or @rudkx, it looks like after these changes multiple previously resolved crashers are now crashing again (which is very concerning), and performance of expressions with multiple iterators have degraded...

**Pull request merged**
