### PR TITLE
[util] Add an IDE utility to print with colors. NFC

### PR DESCRIPTION
**Pull request by nkcsgexi**
Add an IDE utility to print with colors.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please test and merge

**Comment by DougGregor** [comment]
This is copy-paste from sourcekitd's logging header, and very similar to SILPrinter's handling of colors. Please factor out the existing version rather than cloning it.

**Comment by nkcsgexi** [comment]
I'm aware that this is a cloning from SourceKit/Support/Logging.h, actually @akyrtzi pointed me to this utility. However, I found it is hard to to factor this to a common place that can be shared among SourceKit/Support and the compiler due to the loss coupling between the two components.

**Comment by akyrtzi** [comment]
My suggestion was to move it to `include/swift/Basic`, that's where generic utility classes generally go. You can put it under its own header.

**Pull request closed without merging**
