### PR TITLE
[RemoteAST] Stop bypassing resilience when doing queries.

### PR DESCRIPTION
**Pull request by dcci**
Avoid going to IRGen with a resilient type to avoid crashing.
This is tested in lldb.

<rdar://problem/45049259>

### CODE REVIEW

**Comment by dcci** [comment]
Please test with following PR:
https://github.com/apple/swift-lldb/pull/999

@swift-ci Please test

**Review by rjmccall — APPROVED** [review]

**Comment by dcci** [comment]
Thank you, John.

**Review by slavapestov — APPROVED** [review]

**Comment by dcci** [comment]
Please test with following PR:
https://github.com/apple/swift-lldb/pull/999

@swift-ci please test

**Comment by dcci** [comment]
@swift-ci please test linux

**Pull request merged**
