### PR TITLE
[string] 32-bit String is still 3 words

### PR DESCRIPTION
**Pull request by milseman**
Update Reflection.mm to "reflect" this fact.
(• _ •)
( • _ •)>⌐■-■ 
(⌐■_■)

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@gparker42 please test :-)

**Comment by milseman** [comment]
(force) pushed a cleaner version

**Comment by milseman** [comment]
@swift-ci please smoke test

**Comment by milseman** [comment]
@swift-ci please test

**Comment by gparker42** [comment]
Is there a `static_assert` or other compile-time check that we can add somewhere to verify that the definitions of String are consistent?

**Comment by milseman** [comment]
@gparker42 that is a great idea. Not that I know of. @jckarter do you know of a good way to do this?

**Comment by gparker42** [comment]
This change fixed my armv7s tests.

**Comment by milseman** [comment]
@jrose-apple @shahmishal will merge when Linux passes, feel free to merge sooner.

**Comment by milseman** [comment]
Linux looks like a timeout:
```
Test Suite 'TestCodable' passed at 2018-01-23 23:49:12.361
	 Executed 18 tests, with 0 failures (0 unexpected) in 0.322 (0.322) seconds
Test Suite 'TestUnit' started at 2018-01-23 23:49:12.361
Test Case 'TestUnit.test_equality' started at 2018-01-23 23:49:12.361
Test Case 'TestUnit.test_equality' passed (0.0 seconds)
Test Suite 'TestUnit' passed at 2018-01-23 23:49:12.361
	 Executed 1 test, with 0 failures (0 unexpected) in 0.0 (0.0) seconds
Test Suite 'TestNSLock' started at 2018-01-23 23:49:12.361
Test Case 'TestNSLock.test_lockWait' started at 2018-01-23 23:49:12.361
Test Case 'TestNSLock.test_lockWait' passed (8.0 seconds)
Test Case 'TestNSLock.test_threadsAndLocks' started at 2018-01-23 23:49:20.362
Build timed out (after 45 minutes). Marking the build as failed.
```

This PR un-breaks bots, and passed all smoke (and full mac) testing, so merging.

**Comment by milseman** [comment]
@jckarter I'm interested if you're ok with this style as well as ideas on how we can assert or static_assert on this kind of layout.

**Comment by jrose-apple** [comment]
At the very least you could stick a `debugPrecondition(MemoryLayout<String>.size == 3, "the runtime is depending on this, update XYZ.cpp if you change it")` somewhere.

**Comment by jckarter** [comment]
Jordan's idea is probably the best you can do for now.

**Pull request merged**
