### PR TITLE
Base override section names on swift version

### PR DESCRIPTION
**Pull request by etcwilde**
This patch automates maintaining the right compatibility override section names so we don't need to remember to update them by hand with each version.

The expansions look like
'"__swift" "5" "9" "_hooks"' and
'"__s" "5" "9" "async_hook"'.

Note: The section names can only grow to be 16 characters long. If we
      see explosions regarding these names, that could be why.

### CODE REVIEW

**Comment by etcwilde** [comment]
@swift-ci please test

**Review by mikeash — APPROVED** [review]
Sweet.

**Comment by etcwilde** [comment]
Heh, missed a spot; https://github.com/apple/swift/blob/4b6b5109f4f2706c386b2ec7d7ba2d1576bc687d/unittests/runtime/CompatibilityOverrideRuntime.cpp#L65

**Comment by mikeash** [comment]
Good to see the test being helpful!

**Comment by etcwilde** [comment]
@swift-ci please test

**Pull request merged**
