### PR TITLE
[5.1-04-24-2019] IRGen: Don't emit opaque type descriptors twice

### PR DESCRIPTION
**Pull request by aschwaighofer**
rdar://50500620

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by brentdax** [comment]
Might want to add "[5.1 04-24]" (or something) to the title of this PR to distinguish it from its brethren.

**Comment by bob-wilson** [comment]
This change is different that what's on master and the 5.1 branch. Why the difference? Also, I see Slava had a comment about a test case. It would be good to add one if that's not too hard.

**Comment by bob-wilson** [comment]
OK, Arnold updated this to match the revised PR for master, and he's going to follow up with a test case later.

**Review by bob-wilson — APPROVED** [review]

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Pull request merged**
