### PR TITLE
Add a distinct hook for `swift_willThrowTypedImpl()`.

### PR DESCRIPTION
**Pull request by grynspan**
This PR adds a hook for `swift_willThrowTypedImpl()` that is distinct from `swift_willThrow()`. The current implementation of `swift_willThrowTypedImpl()` creates a temporary existential box for the thrown error and calls the `_swift_willThrow` hook that is set by XCTest and swift-testing. Unfortunately, this temporary existential box isn't very useful because its address is not expected to be stable.

Instead, expose a separate hook, `_swift_willThrowTypedImpl`, whose signature matches that of the new ABI function. This hook can then be used by XCTest and swift-testing to distinguish between typed throws and untyped throws and avoids creating a temporary existential box when it won't be useful.

As implemented, if `_swift_willThrowTypedImpl` is not set but `_swift_willThrow` is, the `swift_willThrowTypedImpl()` will fall back to calling `_swift_willThrow` with a temporary existential box. We might decide this is unnecessary, but I figured it would allow us more time to stage adoption of the new hook in the testing libraries.

Resolves rdar://122824443.

### CODE REVIEW

**Comment by grynspan** [comment]
@swift-ci please test

**Review by mikeash — APPROVED** [review]
I'd like to aim to eventually remove the fallback path for maximum efficiency in the common "no handlers set" case, but that can happen later if this is helpful for staging in the change.

**Comment by grynspan** [comment]
> I'd like to aim to eventually remove the fallback path for maximum efficiency in the common "no handlers set" case, but that can happen later if this is helpful for staging in the change.

For the moment, it allows Xcode's version of XCTest to make a best effort without needing to first learn about typed throws. (I presumably can't say anything about hypothetical future Xcode or XCTest changes here, so I won't.)

**Comment by grynspan** [comment]
@swift-ci please test

**Comment by grynspan** [comment]
@swift-ci please test linux

**Review by al45tair — APPROVED** [review]

**Comment by grynspan** [comment]
@swift-ci please test

**Comment by grynspan** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
