### PR TITLE
Remove special case for swift-ci in update-checkout.

### PR DESCRIPTION
**Pull request by varungandhi-apple**
Haven't filed a Radar with suggestions yet, will do so shortly.

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test

**Comment by jrose-apple** [comment]
Why this change? It'll pick something in the middle of a merge that's never been tested.

**Comment by shahmishal** [comment]
We can update this to check if it's merge commit, however it does not have to be Swift CI merge commit.

**Comment by varungandhi-apple** [comment]
Updated with `--merges` flag.

**Comment by jrose-apple** [comment]
That's still not good enough, since upstream-with-swift contains merges as well. How about `--first-parent`?

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test Linux

**Review by shahmishal — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
