### PR TITLE
For 'freestanding' SDK, allow using lipo for support multi-arch builds

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by compnerd — CHANGES_REQUESTED** [review]
This should really be based on the file format.  This is a macho feature, and we check the file format in places already (if you wish to check them for examples on how to do it).

**Comment by kubamracek** [comment]
Updated the PR, it's now based on SWIFT_SDK_${sdk}_OBJECT_FORMAT.

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by compnerd — APPROVED** [review]

**Pull request merged**
