### PR TITLE
Frontend: Really allow any experimental feature when compiling a module interface

### PR DESCRIPTION
**Pull request by tshortli**
The fix for https://github.com/apple/swift/pull/72632 was not sufficient because when modules are built from textual interface that happens in a sub-invocation which does not have typecheck-from-interface or compile-from-interface requested action. Instead of checking a requested action, set a language option to control whether non-production experimental features are allowed.

Resolves rdar://125561443

### CODE REVIEW

**Comment by tshortli** [comment]
@swift-ci please smoke test

**Review by artemcm — APPROVED** [review]

**Review by xymus — APPROVED** [review]

**Comment by drodriguez** [comment]
Can you add a `REQUIRES: asserts` in `test/ModuleInterface/ExperimentalFeatures.swiftinterface` that was modified in #72632 ?

Otherwise it fails if one tries to run the tests in a noasserts compiler with:

```
<unknown>:0: error: unexpected error produced: experimental feature 'ParserRoundTrip' cannot be enabled in production compiler
<unknown>:0: error: diagnostic produced elsewhere: experimental feature 'ParserRoundTrip' cannot be enabled in production compiler
```

**Comment by tshortli** [comment]
> Can you add a `REQUIRES: asserts` in `test/ModuleInterface/ExperimentalFeatures.swiftinterface` that was modified in #72632 ?
> 
> Otherwise it fails if one tries to run the tests in a noasserts compiler with:
> 
> ```
> <unknown>:0: error: unexpected error produced: experimental feature 'ParserRoundTrip' cannot be enabled in production compiler
> <unknown>:0: error: diagnostic produced elsewhere: experimental feature 'ParserRoundTrip' cannot be enabled in production compiler
> ```

This PR is fixing that issue you're reporting. Adding `REQUIRES: asserts` would defeat the purpose of the test; it is meant to validate that the test works in `no_asserts`, I just didn't accomplish that correctly on the first try.

**Comment by drodriguez** [comment]
Sorry then, I misunderstood how the fix worked.

**Comment by FouadMagdy01** [comment]
> > Can you add a `REQUIRES: asserts` in `test/ModuleInterface/ExperimentalFeatures.swiftinterface` that was modified in #72632 ?
> > Otherwise it fails if one tries to run the tests in a noasserts compiler with:
> > ```
> > <unknown>:0: error: unexpected error produced: experimental feature 'ParserRoundTrip' cannot be enabled in production compiler
> > <unknown>:0: error: diagnostic produced elsewhere: experimental feature 'ParserRoundTrip' cannot be enabled in production compiler
> > ```
> 
> This PR is fixing that issue you're reporting. Adding `REQUIRES: asserts` would defeat the purpose of the test; it is meant to validate that the test works in `no_asserts`, I just didn't accomplish that correctly on the first try.

How did you solve this
I get this issue
`<unknown>:0: experimental feature 'OpaqueTypeErasure' cannot be enabled in a production compiler`

**Pull request merged**
