### PR TITLE
[Swift Rebranch] Fix StringRef API usage

### PR DESCRIPTION
**Pull request by edymtt**
This is the same as #38176

`compare_lower` and `equals_lower` were replaced with `compare_insensitive` and `equals_insensitive`, respectively in llvm commits 2e4a2b8430aca6f7aef8100a5ff81ca0328d03f9 and 3eed57e7ef7da5eda765ccc19fd26fb8dfcd8d41.

rdar://79974226

### CODE REVIEW

**Review by etcwilde — APPROVED** [review]
Assuming it builds, LGTM.

**Comment by edymtt** [comment]
@swift-ci please smoke test

**Comment by edymtt** [comment]
It seems we are hitting different errors

Windows

```
C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\lib\ClangImporter\ImportDecl.cpp(1170): error C2039: 'VK_RValue': is not a member of 'clang'
```

Linux

```
/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test@2/branch-rebranch/swift/include/swift/AST/ReferenceStorage.def:189:1: error: use of undeclared identifier 'INT_MIN'
```

macOS

```
/Users/buildnode/jenkins/workspace/swift-PR-macos-smoke-test/branch-rebranch/swift/include/swift/Basic/MultiMapCache.h:65:26: error: no member named 'makeArrayRef' in namespace 'llvm'
```

**Comment by edymtt** [comment]
Merging to be able to test the next cherry-picks we need

**Pull request merged**
