### PR TITLE
[stdlib] Remove `static var one` from `PointwiseMultiplicative`.

### PR DESCRIPTION
**Pull request by dan-zheng**

### CODE REVIEW

**Comment by rxwei** [comment]
should also remove any mentions of “ring” from file names and file contents.

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by dan-zheng** [comment]
I accidentally deleted `tensorflow` branch, which closed this PR. That was not intentional, sorry!
It would be nice to protect `tensorflow` branch against deletion to prevent this from happening again.

**Comment by nicholasnovakovic** [comment]
Hello, I am a first time contributor and would like to contribute to this issue. I am still unclear with what needs to be done for this. Is it possible for you to clarify that with me? Thank you.

**Comment by dan-zheng** [comment]
> Hello, I am a first time contributor and would like to contribute to this issue. I am still unclear with what needs to be done for this. Is it possible for you to clarify that with me? Thank you.

Hi @nicholasnovakovic! I think that this pull request might actually not be the right direction. We shouldn't remove `PointwiseMultiplicative.one` if it has any users.

Context: `PointwiseMultiplicative` is a `tensorflow`-branch-only ad-hoc protocol (with derived conformances) added to support [tensorflow/swift-apis](https://github.com/tensorflow/swift-apis). I feel it's not likely to pass Swift Evolution in its current state. Eventually, we should strive to remove `PointwiseMultiplicative` and `VectorProtocol` altogether - removing specific unused protocol requirements isn't really meaningful.

**Comment by nicholasnovakovic** [comment]
Hi @dan-zheng !

Can you direct me to any issue which would be good for me work on? Or can you tell me what the general procedure is for wanting to contribute? Do I have to find something I think would be good to work on and then suggest it as an issue?

Thank you so much!

**Comment by dan-zheng** [comment]
Sure @nicholasnovakovic! Are you interested in contributing to Swift specifically, or Swift for TensorFlow?

**Comment by nicholasnovakovic** [comment]
@dan-zheng I'm interesting in contributing to either! I mainly code in C++ and Python so I should be able to contribute to projects which require these languages! :)

**Comment by dan-zheng** [comment]
That's cool! The Swift compiler is written in C++ (LLVM-style).

Check out the Swift forums: https://forums.swift.org/search?q=contributing
And starter issues (you may want to filter): https://bugs.swift.org/issues/?jql=labels%20%3D%20StarterBug

**Pull request closed without merging**
