### PR TITLE
[cxx-interop] do not add friend decls as a member of Swift type that …

### PR DESCRIPTION
**Pull request by hyp**
…represents a C++ class

Fixes an assertion when printing a module interface with such condition.

### CODE REVIEW

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test source compatibility

**Comment by hyp** [comment]
@swift-ci please test linux

**Comment by hyp** [comment]
@swift-ci please test linux

**Comment by hyp** [comment]
@swift-ci please test linux

**Comment by hyp** [comment]
@swift-ci please test linux

**Comment by hyp** [comment]
@swift-ci please test windows

**Comment by hyp** [comment]
@swift-ci please test windows

**Comment by hyp** [comment]
@swift-ci please test windows

**Comment by hyp** [comment]
@swift-ci please test macOS platform

**Comment by hyp** [comment]
@swift-ci please test macOS platform

**Comment by hyp** [comment]
@swift-ci please test macOS platform

**Review by egorzhdan — APPROVED** [review]

**Comment by hyp** [comment]
@swift-ci please test macOS platform

**Pull request merged**
