### PR TITLE
[Concurrency] Fix typo in internal variable name

### PR DESCRIPTION
**Pull request by ktoso**
deadine -> deadline

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please smoke test and merge

**Comment by ktoso** [comment]
@swift-ci please clean smoke test macOS

**Comment by ktoso** [comment]
@swift-ci please smoke test macOS and merge

**Comment by ktoso** [comment]
@swift-ci please smoke test macOS

**Review by phausler — APPROVED** [review]

**Pull request merged**
