### PR TITLE
Moves formerly statically-allocated RecursiveSharedTimer(s) effectively into ASTContext

### PR DESCRIPTION
**Pull request by davidungar**
Moves RecursiveSharedTimer into statistics structure pointed-to by ASTContext, instead of being statically-allocated.

Resolves rdar://34475709.

### CODE REVIEW

**Comment by davidungar** [comment]
@swift-ci Please smoke-test.

**Comment by davidungar** [comment]
@swift-ci Please smoke test.

**Comment by davidungar** [comment]
Merged per conversation with Slava.

**Comment by gottesmm** [comment]
Dave, in the future, can you clean up the git history or squash the commits. Having "First compiling run, WIP" as a commit in the history is sort of unfortunate. If you want, I can show you some tips and tricks for this.

**Comment by davidungar** [comment]
Tx, Michael. It’s a good reminder.

**Pull request merged**
