### PR TITLE
docs/Android: fix typo in build script invocation

### PR DESCRIPTION
**Pull request by AndrewSB**
@lanza please smoke test

### CODE REVIEW

**Comment by lanza** [comment]
@swift-ci please smoke test

**Review by lanza — APPROVED** [review]

**Comment by AndrewSB** [comment]
Hmm, maybe your trigger isn't setup properly @lanza?

@compnerd please smoke test?

**Comment by compnerd** [comment]
@swift-ci please smoke test and merge

**Comment by gottesmm** [comment]
@AndrewSB have you considered asking for commit access. You have been updating stuff a bit, I think it would be appropriate.

**Pull request merged**
