### PR TITLE
[API notes] CTFontManagerError is not a valid Error at this time.

### PR DESCRIPTION
**Pull request by jrose-apple**
CoreText is below Foundation in the framework stack, so its error enum uses a CFStringRef constant as its domain instead of an NSString. The importer doesn't know how to handle that yet, so for now, just don't import CTFontManagerError as a first-class error type.

rdar://problem/27722004

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

A smoke test on macOS does the following:
1. Builds the compiler incrementally.
2. Builds the standard library only for macOS. Simulator standard libraries and
   device standard libraries are not built.
3. lldb is not built.
4. The test and validation-test targets are run only for macOS. The optimized
   version of these tests are not run.

A smoke test on Linux does the following:
1. Builds the compiler incrementally.
2. Builds the standard library incrementally.
3. lldb is built incrementally.
4. The swift test and validation-test targets are run. The optimized version of these
   tests are not run.
5. lldb is tested.

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by jrose-apple** [comment]
@slavapestov Mind "reviewing"? (More looking for confirmation that my analysis makes sense than the actual review, but I will put you down as reviewer when cherry-picking to swift-3.0-branch.)

@swift-ci Please test OS X platform

**Comment by slavapestov** [comment]
Looks good.

Anything we want to change in the ClangImporter, for example assert or diagnose when this occurs?

**Comment by jrose-apple** [comment]
That's not a bad idea, but I think it's okay not to pull that part into the 3.0 branch. I'll clone the Radar to follow up on it later.

**Comment by jrose-apple** [comment]
(We definitely can't assert because users have no control over this.)

**Pull request merged**
