### PR TITLE
ClosureSpecializer: We don't need to insert releases for inlined thin_to_thick functions

### PR DESCRIPTION
**Pull request by aschwaighofer**
rdar://32595213

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please benchmark

**Comment by dabrahams** [comment]
@swift-ci Please benchmark

**Comment by dabrahams** [comment]
@swift-ci Please benchmark

**Comment by dabrahams** [comment]
@aschwaighofer you might need to push a dummy commit (or just revise the tip by adding a newline to the commit message and re-pushing) and re-request the benchmark (twice) for this to run.  Looks stuck to me.

**Comment by aschwaighofer** [comment]
@swift-ci Please benchmark

**Comment by aschwaighofer** [comment]
@swift-ci Please benchmark

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test

**Comment by aschwaighofer** [comment]
@swift-ci Please benchmark

**Comment by aschwaighofer** [comment]
Pretty please ...

**Comment by aschwaighofer** [comment]
@swift-ci Please benchmark

**Comment by dabrahams** [comment]
Might need a fresh PR?

**Comment by aschwaighofer** [comment]
To be continued here: https://github.com/apple/swift/pull/10153

**Pull request closed without merging**
