### PR TITLE
Add CHANGELOG entry for #41849 and #41978

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
Add CHANGELOG entry for #41849 and #41978

### CODE REVIEW

**Comment by AnthonyLatsis** [comment]
@slavapestov ping

**Review by slavapestov — APPROVED** [review]

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Comment by AnthonyLatsis** [comment]
Thanks, Slava!

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
