### PR TITLE
Fixes to ClosureLifetimeFixup's copy elimination for noncopyable values 

### PR DESCRIPTION
**Pull request by meg-gupta**
- On finding unrecognized user, reset `initialization` of the stack so that we
don't inadvertently eliminate copy
- For a mark_dependence user of the stack, look through the mark_dependence chain
to match the partial_apply

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Comment by Azoy** [comment]
Isn’t the latter resolved by: https://github.com/swiftlang/swift/pull/74593?

**Comment by meg-gupta** [comment]
@Azoy https://github.com/swiftlang/swift/pull/74593 did not handle cases like `testMultiCapture` where `markDepChain` was not initialized because the capture was a copyable type.

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Comment by meg-gupta** [comment]
@swift-ci test windows platform

**Comment by meg-gupta** [comment]
@swift-ci smoke test Linux platform

**Pull request merged**
