### PR TITLE
Add @_weakSymbol and a corresponding SIL attribute

### PR DESCRIPTION
**Pull request by jrose-apple**
This is mostly intended to be used for testing at this point; in the long run, we want to be using availability information to decide whether to weak-link something or not. You'll notice a bunch of FIXMEs in the test case that we may not need now, but will probably need to handle in the future.

I snuck in a few cleanups while I was here, too.

Groundwork for doing backward-deployment execution tests.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
I realized later that making this work with availability would probably be sufficient, since the runtime has a hook to pretend that it's on a certain version of a platform. But it's still simpler to just mark things as "weak".

**Comment by jrose-apple** [comment]
[Still need to fix up a Linux test.](https://ci.swift.org/job/swift-PR-Linux/3086/)

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
\*sigh\*

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
Wikipedia‘s article for “weak symbol” is about the other definition of weak that we don’t mean here:

https://en.m.wikipedia.org/wiki/Weak_symbol

I hate to bikeshed an internal only name, but since confusion is likely here something else might be called for.

**Comment by jrose-apple** [comment]
`@_weakLinked`, then?

Anything suspect on the technical side?

**Comment by jrose-apple** [comment]
(The equivalent GCC attribute is spelled `weakref`, although they allow `weak` to be used for the same purpose in addition to using it for weak definitions.)

**Comment by jckarter** [comment]
`@_weakLinked` sounds good to me.

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test Linux

**Pull request merged**
