### PR TITLE
[NFC] Move `WinSDK.swift` overlay

### PR DESCRIPTION
**Pull request by stevapple**
Move `WinSDK.swift` overlay to `stdlib/public/Platform`, where `Glibc.swift` overlay lies in.

This further aligns Windows build behavior to Linux, and simplifies directory structure by eliminating `stdlib/public/Windows`.

Depends on #41691

Resolves SR-NNNN.

### CODE REVIEW

**Comment by jckarter** [comment]
How does this look @compnerd?

**Comment by compnerd** [comment]
Hmm, seems like it just moves the location of the file?  As long as it doesn't break the installer, I think that should be okay.

**Comment by compnerd** [comment]
@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain Windows platform

**Review by compnerd — CHANGES_REQUESTED** [review]
Please drop the changes unrelated to the move

**Comment by stevapple** [comment]
@compnerd Which piece of change did you mean by “unrelated”?

**Comment by compnerd** [comment]
The changes to the directory creation bits are the "unnecessary" changes.  The movement of the file and the target creation should be a no-op.

**Comment by stevapple** [comment]
> The changes to the directory creation bits are the "unnecessary" changes. The movement of the file and the target creation should be a no-op.

That commit is in #41691 , where I shared the error encountered with moving `WinSDK.swift`

**Comment by stevapple** [comment]
This conflicts with the direction shown by apple/swift#63042, going to close it

**Pull request closed without merging**
