### PR TITLE
bumping compiler version number to 5.0.1

### PR DESCRIPTION
**Pull request by najacque**
This PR bumps the compiler version to 5.0.1 on the swift-5.0-branch

Resolves rdar://problem/49561140

### CODE REVIEW

**Comment by najacque** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
```
/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-swift-5.0-branch/swift-corelibs-foundation/TestFoundation/HTTPServer.swift:15:8: error: missing required modules: 'CDispatch', '_SwiftDispatchOverlayShims'
10:44:25 import Dispatch
```

@swift-ci test Linux

**Comment by shahmishal** [comment]
```
11:20:48 Failing Tests (1):
11:20:48     Swift(macosx-x86_64) :: Serialization/Recovery/types-5-to-4.swift
```
https://github.com/apple/swift/blob/swift-5.0-branch/test/Serialization/Recovery/types-5-to-4.swift#L19

We need to update this test to use `5.0.1` from `5.0`

**Comment by najacque** [comment]
@swift-ci please test

**Comment by najacque** [comment]
@swift-ci please smoke test

**Review by tkremenek — APPROVED** [review]

**Pull request merged**
