### PR TITLE
[AutoDiff] Remove `os(PS4)` check on TgmathDerivatives.swift.gyb

### PR DESCRIPTION
**Pull request by philipturner**
This is a minor cleanup of the import statement, as PS4 is OpenBSD and would already be supported by checking `os(OpenBSD)`.

### CODE REVIEW

**Comment by philipturner** [comment]
Thanks @WowbaggersLiquidLunch

**Comment by philipturner** [comment]
I found this branch, which gives me some answers. I'll link it here for reference:
https://github.com/rxwei/swift/tree/cross-import-overlay-differentiation

**Comment by CodaFi** [comment]
A cross-import overlay refers to a Swift module that is brought into scope when two or more Swift modules are imported. Prominent examples in the existing SDK are cross-import overlays for SwiftUI and something else (e.g. MapKit). The original bug refers to creating such a module for when autodiff is on and imports for Glibc/Darwin and _Differentiation appear in source.

I'm going to take this as a nice cleanup to the import platforms in this file, but this does not resolve the SR.

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by philipturner** [comment]
Thanks for clarifying.

**Comment by rxwei** [comment]
+1 on what Robert said. You can read about cross-import overlays in [this Swift Evolution pitch](https://forums.swift.org/t/cross-import-overlays/30868). SR-15584 is to make _Differentiation no longer depend on Glibc/Darwin/ucrt.

As for the cleanup of the `#if` conditionals, I don't have strong opinions about and I'm going to defer to @compnerd.

**Comment by philipturner** [comment]
From the build log, the CI failed on macOS because [TestSwiftGenericExpressions.py](lang/swift/expression/generic/TestSwiftGenericExpressions.py) timed out after 10 minutes. At the very end of the build log, this message also appeared:
```
[parameterized-trigger] Properties file re_build.properties did not exist.
```

**Comment by philipturner** [comment]
@compnerd you said that using `canImport` statements had some fundamental flaws. Looking at (https://github.com/rxwei/swift/commit/74f11f84f36c8ef369dc9f0d09952150da95047d), TgmathDerivative's hard-coded platform checks exactly match what's on the CMakeLists files. I'm now doubting whether it's a good idea to merge this pull request. What are your thoughts?

**Comment by compnerd** [comment]
Yeah, I agree, I think that this is fine as is.

**Comment by philipturner** [comment]
@compnerd I re-opened this pull request. I undid the addition of `canImport` and instead modified the platform-specific Glibc import. I figured it's best to reuse the PR topic/title and review assignees.

Sorry for it being a bit wierd. I need to clarify something. @compnerd you're the person who made the first PR to add PS4 support. The conditional import statement treats it like a separate platform from FreeBSD, while the little other code that mentions it tells me otherwise. Also, @rxwei why did the CMakeLists files in https://github.com/rxwei/swift/tree/cross-import-overlay-differentiation not account for Android?

**Comment by rxwei** [comment]
> @rxwei why did the CMakeLists files in https://github.com/rxwei/swift/tree/cross-import-overlay-differentiation not account for Android?

My WIP branch was a quick prototype to attempt to get some basic stuff to work (primarily macOS and Linux), and the omission of other platforms was not intentional.  Hope the prototype helps.

**Comment by philipturner** [comment]
Yes. I'm building on it right now, trying to bisect a flood of errors when it fails to build.

**Comment by philipturner** [comment]
@rxwei I encountered a major problem, which is the cause of the error I was bisecting. Enabling cross-import overlays causes compilation to fail badly, independent of whether it's cross-importing differentiation. I added file changes chronologically on your fork, reaching `Module.cpp`. When you enable cross-import overlay c. line 2627, the compiler completely breaks. I'm unable to make any further progress because of this.

The following is a PR that merged your branch to `patch-16` on my fork, which is the current state of my work. The files changed are almost the same as your branch. I was bisecting it onto the `patch-17` branch when it failed.
- https://github.com/philipturner/swift/pull/5/files

**Comment by philipturner** [comment]
To any reviewer, why does the last loop in TgmathDerivatives.swift exclude double precision?

**Comment by rxwei** [comment]
> To any reviewer, why does the last loop in TgmathDerivatives.swift.gyb exclude double precision?

Good question. This may be an accidental error. The following code (using `Double`) doesn't compile due to `pow(_: Double, _: Double)` missing a derivative.

```swift
import _Differentiation
gradient(at: 2.0) { x in pow(x, 3.0) }
```

Feel free to create a separate PR to add it and test it.

**Comment by philipturner** [comment]
I’d like to merge that in with this PR, hence the name change. Just to create less code churn, since it should be harmless.

**Comment by philipturner** [comment]
Ready for CI testing again, unless you have objections.

**Comment by philipturner** [comment]
Citing https://github.com/apple/swift/pull/40885#issuecomment-1019702840, discussion on the cross-import overlays thread you gave me ceased in 2020, ~1 year after it started. Assuming cross-import overlays for tgmath are too intractable to handle right now, should I make a draft PR from my patch-16 branch (renaming the branch, of course).

**Comment by philipturner** [comment]
Changing the name yet again back to WIP. I’ll take up both of Richard’s suggestions because they’re just the kind of experience I need right now.

One more thing - I’m going to need to add WASI to the CMakeLists for PlatformDifferentiation, unless I’m mistaken?

**Comment by philipturner** [comment]
The inability to differentiate `Double` is actually much more severe than it seems on the surface. The following give all kinds of errors on `AutoDiff/stdlib/tgmath_derivatives.swift` after patching to add `'Double'` to the loop, only when using double precision:
- `fmod`
- `remainder`
- `trunc`
- `round`
- `floor`
- `ceil`
- `sqrt`
- I didn't test or find errors for `pow` but we already know it's problematic too.

For example, the following code does not compile:
```swift
gradient(at: 2.0 as Double) { x in sqrt(x) }
```
When this does:
```swift
gradient(at: 2.0 as Float) { x in sqrt(x) }
```

Look at the completely unrolled [`TgmathDerivatives.swift`](https://github.com/philipturner/differentiation/blob/main/Sources/Differentiation/TgmathDerivatives.swift) from my Differentiation package. If and only if a function is generic, it is a problem causer (except for `pow`, a special case). This fact is especially worrisome because it means the problem's source is the compiler (maybe AST or SILGen), not the standard library. Although, it can be worked around (see the end of this comment).

When I add this declaration above it, it still doesn't compile for `Double`, but successfully compiles for `Float`:
```swift
@usableFromInline
@derivative(of: sqrt)
func _vjpSqrt<T: FloatingPoint & Differentiable> (
    _ x: T
) -> (value: T, pullback: (T) -> T) where T == T.TangentVector {
    let value = sqrt(x)
    return (value, { v in v / (2 * value) })
}
```

Yet, when I define an arbitrary function `foo`, this successfully compiles in contrast to the behavior with `sqrt`:
```swift
func foo<T: FloatingPoint & Differentiable>(_ x: T) -> T {
    x
}

@usableFromInline
@derivative(of: foo)
func _vjpSqrt<T: FloatingPoint & Differentiable> (
    _ x: T
) -> (value: T, pullback: (T) -> T) where T == T.TangentVector {
    let value = foo(x)
    return (value, { v in v / (2 * value) })
}

gradient(at: 2.0 as Float) { x in foo(x) }
gradient(at: 2.0 as Double) { x in foo(x) }
```

---

Now, for the workaround:
```swift
@usableFromInline
@derivative(of: sqrt)
func _vjpSqrt (
    _ x: Double
) -> (value: Double, pullback: (Double) -> Double)  {
    let value = sqrt(x)
    return (value, { v in v / (2 * value) })
}

gradient(at: 2.0 as Double) { x in sqrt(x) }
```
This approach is what S4TF did in one of its Colab notebook tutorials ([sharp edges in AutoDiff](https://github.com/tensorflow/swift/blob/main/docs/site/tutorials/Swift_autodiff_sharp_edges.ipynb)). The notebook said the following:
> A lot of transcendentals and other common built-in functions have already been made differentiable for `Float` and `Double`. There are fewer for `Double` than `Float`.

Then, it proceeded to manually define double-precision derivatives for `pow` (the source of my JIRA bug - [SR-15675](https://bugs.swift.org/browse/SR-15675)), `sqrt` (a problem-causer above), `abs`, and `max`. That tutorial was made in October 2020 while the respective stdlib functions were last modified [in May 2020](https://github.com/apple/swift/commit/b433920fe16c5856134ce2e520923dd697d24a4b). This means `Double` differentiation has had this bug for almost two years.

---

I suspect this is rooted somewhere in the C++ code and is out of my scope currently. I'm going to remove the addition of double-precision derivatives from this pull request, then try the workaround in another branch/PR. Should I file this on JIRA and add compiler crasher tests?

**Comment by rxwei** [comment]
The issue you described is not a bug, but something we can work around (that is, your PR #40991), and improve at the compiler level in the potentially distant future.

When you differentiate a function, the compiler will only try to differentiate the function you called. Many math functions, e.g. `sqrt`, have two overloads, one from C (`sqrt(_: Double) -> Double`) and one from Swift (`sqrt<T: FloatingPoint>(_: T) -> T`).  When you call `sqrt` on a `Double`, `sqrt(_: Double) -> Double` will be called because it's the most concrete. We don't have this issue for `Float` because the C version is named `sqrtf`.

**Comment by rxwei** [comment]
What exactly does the proposed change, after all the medications, do?  You should modify the PR description to describe the change.

**Comment by philipturner** [comment]
It was originally going to be a lot more changes than it is now.

**Comment by rxwei** [comment]
You modified the PR title, no the description.  The PR description refers to the first comment in the PR, i.e. https://github.com/apple/swift/pull/40885#issue-1106176767.

**Comment by philipturner** [comment]
Oh, sorry. The first comment is changed now.

**Review by CodaFi — CHANGES_REQUESTED** [review]
I think the platform conditional needs to stay.

> as PS4 is OpenBSD

There is a difference between the technologies that a platform is based upon and the platform's self-identification. This difference is borne out in abstractions like LLVM's target triples, where you can have the same underlying architecture, os, and environment but still have different vendors offering different target-specific features. In this case, the two os checks are not equivalent as you can provide `-target x86_64-scei-ps4` to make `#if os(PS4)` true and `-target x86_64-unknown-openbsd` to make `#if os(OpenBSD)` true but crucially not both.

The relevant code here is in LangOptions.cpp:

```
<snip>
  case llvm::Triple::OpenBSD:
    addPlatformConditionValue(PlatformConditionKind::OS, "OpenBSD");
    break;
  case llvm::Triple::PS4:
    if (Target.getVendor() == llvm::Triple::SCEI)
      addPlatformConditionValue(PlatformConditionKind::OS, "PS4");
    else
      UnsupportedOS = false;
    break;
</snip>
```

**Comment by philipturner** [comment]
@CodaFi thanks for explaining! I could not figure that out by typing `os(PS4)` into GitHub search.

**Pull request closed without merging**
