### PR TITLE
[docs] Add "IWYU" to lexicon

### PR DESCRIPTION
**Pull request by modocache**
#### What's in this pull request?

Add a blurb on "IWYU", which was used in the commit message for https://github.com/joewillsher/swift/commit/e7584975d61d2fc254bbb205f48e1096c8caf31d. It took me a few seconds to remember what this stood for, others may never have encountered the abbreviation before.

Feel free to close this pull request if you don't think the term belongs in the lexicon! 🙇 
#### Resolved bug number: None

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by gottesmm** [comment]
I think this is fine.

**Comment by jtbandes** [comment]
There's a typo: `mplementation`

**Comment by lattner** [comment]
Typo fixed in aba4bd5

**Comment by modocache** [comment]
Thanks for the merge, and for the typo fix!

**Pull request merged**
