### PR TITLE
[Demangler] Make swift-demangle faster by not using regex.

### PR DESCRIPTION
**Pull request by al45tair**
In my (admittedly silly) test case involving parsing a 48MB mangling, `swift-demangle` spends 78% of its time executing the regex to find things it might be able to unmangle, and only 21% of its time actually unmangling things. This seemed wrong, so I removed the regex and wrote code to match mangled strings instead.  It seems quite a bit faster overall.

rdar://80019851

### CODE REVIEW

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by gottesmm** [comment]
Can you add a benchmark for this? I think we may support gbenchmark stuff using LLVM... I don't remember. But saying we speed something up is something that should be quantified in some way to prevent regressions.

**Comment by al45tair** [comment]
I didn't say in the comment, but in my test case, `swift-demangle` with this code was 70% faster than it was with the `llvm::Regex`. However, you're right, there's definitely performance testing stuff and it would be nice to have a test case.

**Comment by gottesmm** [comment]
You did say in the comment ; ). I was aware of that. What is important is that we have the benchmark partially to guarantee the perf win, but more importantly, it is important so we can prevent regression.

**Comment by eeckstein** [comment]
Performance benchmarks in regression tests are tricky, because they depend on the machine, workload, etc.
I don't think it's worth the effort for this change to invest much in such an infrastructure.
`swift-demangle` performance in not that important.

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Review by mikeash — APPROVED** [review]

**Pull request merged**
