### PR TITLE
SILBridging: remove some #ifdef USED_IN_CPP_SOURCE

### PR DESCRIPTION
**Pull request by hjyamauchi**
Co-authored with @eeckstein

Related to https://github.com/swiftlang/swift/issues/74866

### CODE REVIEW

**Comment by hjyamauchi** [comment]
@swift-ci please test

**Comment by hjyamauchi** [comment]
@swift-ci please test

**Comment by hjyamauchi** [comment]
@swift-ci please test Linux Platform

**Comment by hjyamauchi** [comment]
@swift-ci please test macOS Platform

**Comment by hjyamauchi** [comment]
@swift-ci please test Windows Platform

**Review by eeckstein — APPROVED** [review]
thanks!

**Pull request merged**
