### PR TITLE
[AudoDiff] NFC: Replace 'SILAutoDiffIndices' with 'AutoDiffConfig'.

### PR DESCRIPTION
**Pull request by rxwei**
Resolve rdar://71678394 / SR-13889.

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test

**Comment by rxwei** [comment]
@swift-ci please test linux

**Review by dan-zheng — APPROVED** [review]
Nice!

<sub>(AutoDiff is misspelled in the commit title as Audodiff)</sub>

**Review by joshnewnham — APPROVED** [review]

**Comment by rxwei** [comment]
@swift-ci please test linux

**Comment by rxwei** [comment]
@swift-ci please smoke test linux

**Pull request merged**
