### PR TITLE
[PrunedLiveness] Addressed boundary TODO.

### PR DESCRIPTION
**Pull request by nate-chandler**
With guaranteed phis, we'll be able to encounter cases where the last users are BranchInsts which use but don't consume a value.  But even without them, we can still test the API.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test macOS platform

**Comment by nate-chandler** [comment]
@swift-ci please test macOS platform

**Comment by nate-chandler** [comment]
@swift-ci please smoke test

**Comment by nate-chandler** [comment]
@swift-ci please test macOS platform

**Comment by nate-chandler** [comment]
@swift-ci please test linux platform

**Review by atrick — APPROVED** [review]
👍

**Comment by nate-chandler** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
