### PR TITLE
Revert "Revert "[Build System: CMake] make add_swift_library a wrappe…

### PR DESCRIPTION
**Pull request by compnerd**
…r to add_llvm_library""

This reverts commit 103f9a8246beb385ca6d8a33003a0ebac035095d.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
@gottesmm kindly volunteered to help sort out the internal CI conflicts.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by gottesmm** [comment]
@swift-ci please test

**Comment by gottesmm** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@gottesmm - I suppose that this should wait until you're ready to deal with the internal merge?

**Comment by gottesmm** [comment]
Thanks for waiting. I'll take care of it.

**Pull request merged**
