### PR TITLE
Revert "[NoncopyableGenerics] Basic end-to-end testing (without stdlib)."

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/swift#69591

This seems to be causing a test failure on Windows.  It seems that the CI merged the change without waiting for completion or could be a timeout thing as there was a GH outage.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by kavon** [comment]
I think we only need to revert this test: https://github.com/apple/swift/pull/69591/commits/6fe00b665c395e86809cf81ce5fd3627ece559c5

**Comment by kavon** [comment]
Here's a PR to just remove the failing test: https://github.com/apple/swift/pull/69655

I know what the issue is but it'll take more fixes; the SILLinker likes to link stuff from the stdlib that I wasn't expecting it to on Windows and Linux, which is what's creating the difference.

**Review by kavon — CHANGES_REQUESTED** [review]
Here's a PR to just remove the failing test: https://github.com/apple/swift/pull/69655

I know what the issue is but it'll take more fixes; the SILLinker likes to link stuff from the stdlib that I wasn't expecting it to on Windows and Linux, which is what's creating the difference.

**Pull request closed without merging**
