### PR TITLE
[frontend] Don't destroy the compiler instance object inside performCompile()

### PR DESCRIPTION
**Pull request by akyrtzi**
This permits continuing to use the diagnostic engine object from the instance.

### CODE REVIEW

**Comment by akyrtzi** [comment]
@swift-ci smoke test

**Comment by slavapestov** [comment]
It would be cleaner to construct the diagnostic engine outside of the compiler instance and pass it in to the instance. Then you can still destroy the entire compiler instance.

**Comment by swiftix** [comment]
Does it have any impact on the memory consumption? In general, we tried to free the memory occupied by the compiler ASAP, to reduce the peak memory usage.

**Comment by akyrtzi** [comment]
A previous suggestion was to have `CompilerInstance` keep a shared pointer to a `DiagnosticEngine` object, and also have the `SourceManager` reference be a shared pointer since `DiagnosticEngine` references it, but @DougGregor was not a fan of this, since the `DiagnosticEngine` in general keeps state that is relevant to a compiler instance (like whether a fatal error occurred, etc.)

**Comment by akyrtzi** [comment]
@swiftix , the commit still frees the ASTContext and SILModule object, which should account for the vast majority of the memory consumption.

**Comment by akyrtzi** [comment]
@swift-ci smoke test

**Comment by jrose-apple** [comment]
cc @mxswd

**Comment by mxswd** [comment]
I will try to get a build with this change to evaluate the difference in peak memory usage before merging.

**Review by DougGregor — APPROVED** [review]
LGTM, but let's see what Maxwell finds

**Comment by mxswd** [comment]
I've double checked and it looks great to me! Thanks!

**Review by mxswd — APPROVED** [review]

**Pull request merged**
