### PR TITLE
Fix test where CHECK is used without a colon.

### PR DESCRIPTION
**Pull request by gottesmm**

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by rjmccall** [comment]
LGTM, assuming it works. :)  As noticed on #26077.

**Review by rjmccall — APPROVED** [review]

**Comment by rjmccall** [comment]
@swift-ci Please smoke test

**Comment by gottesmm** [comment]
I haven't dropped this John. I just keep getting side-tracked. Its on my queue.

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Pull request merged**
