### PR TITLE
Fix memory leak

### PR DESCRIPTION
**Pull request by valeriyvan**

### CODE REVIEW

**Comment by artemcm** [comment]
Ah, thank you very much @valeriyvan. 
What do you think about hoisting the code block:
```
if (localSubInstanceMap)
    delete subInstanceMap;
```
To right after we define `subInstanceMap` and in a `SWIFT_DEFER` [block](https://github.com/apple/swift/blob/main/include/swift/Basic/Defer.h#L38)?

That way adding new `return`s to this method won't require the developer to remember to do this.

**Review by artemcm — APPROVED** [review]

**Comment by valeriyvan** [comment]
> Ah, thank you very much @valeriyvan. What do you think about hoisting the code block:
> 
> ```
> if (localSubInstanceMap)
>     delete subInstanceMap;
> ```
> 
> To right after we define `subInstanceMap` and in a `SWIFT_DEFER` [block](https://github.com/apple/swift/blob/main/include/swift/Basic/Defer.h#L38)?
> 
> That way adding new `return`s to this method won't require the developer to remember to do this.

done

**Review by artemcm — APPROVED** [review]

**Comment by artemcm** [comment]
@swift-ci test and merge

**Comment by artemcm** [comment]
@swift-ci test and merge

**Comment by artemcm** [comment]
@swift-ci test

**Comment by valeriyvan** [comment]
ping

**Comment by AnthonyLatsis** [comment]
@valeriyvan Could you squash the commits?

**Comment by valeriyvan** [comment]
> @valeriyvan Could you squash the commits and add a "DependencyScan:" or similar tag at the start of the message?

done

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
