### PR TITLE
R345637+r345605

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @bob-wilson

**Comment by bob-wilson** [comment]
I don't suppose this will fix the ClangImporter/enum-anon.swift test failure that has been happening recently on master-next. Any idea what's causing that? I haven't had a chance to investigate.

**Comment by compnerd** [comment]
Hmm, that might be due to upstream changes.  Do you have a link to the build bot output?

**Comment by bob-wilson** [comment]
Yes, I'm pretty sure it is due to upstream changes. I saw it locally over at least a few days. You can probably see it in some of the master-next macOS build logs, but it's hard to sort through the other issues (like the one you fixed here) to find a link for you.

**Pull request merged**
