### PR TITLE
[cxx-interop] import static operator call from C++23 as member callAs…

### PR DESCRIPTION
**Pull request by compnerd**
…Function functions in Swift to preserve source compatibility

### CODE REVIEW

**Comment by compnerd** [comment]
**Explanation**: Correct importing of operator ()() from C++ types into Swift.
**Scope**: This fixes a small C++ interop issue in the compiler which is required for use of std::hash on Windows.
**Issue**:
**Risk**: This is a pretty narrow change to how we handle static operator()() which was added in C++23. It impacts only the C++ interop path where this method is declared.
**Testing**: This has been on main for quite some time and we failed to bring it over for the release.
**Reviewer**: @egorzhdan @hyp @al45tair

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by egorzhdan** [comment]
We should also cherry-pick a crash fix: https://github.com/swiftlang/swift/pull/76252

**Comment by compnerd** [comment]
Brought those over along with this change so that we do not split them up.

**Review by shahmishal — APPROVED** [review]

**Pull request merged**
