### PR TITLE
Update the `.swiftinterface` feature baseline

### PR DESCRIPTION
**Pull request by tshortli**
Thoroughly re-baseline the set of features that are accepted by supported older compilers and therefore can appear unguarded in `.swiftinterface` files. The only features which require guards at this point were introduced in late Spring 2024.

### CODE REVIEW

**Comment by tshortli** [comment]
@swift-ci please test

**Comment by slavapestov** [comment]
Awesome!

**Comment by tshortli** [comment]
@swift-ci please smoke test

**Comment by tshortli** [comment]
@swift-ci please smoke test

**Pull request merged**
