### PR TITLE
[SE-0276] Syntax and Parse updates

### PR DESCRIPTION
**Pull request by owenv**
The first commit is a cherry-pick of the Parse and Syntax changes from #27776 and reviewed by @rintaro, the second is the minimal set of changes needed to make them work with the old AST, plus a diagnostic saying the new syntax isn't yet supported.

The goal is to land the corresponding swift-syntax PR alongside this so the rest of #27776 becomes more manageable and easier to review.

### CODE REVIEW

**Comment by owenv** [comment]
apple/swift-syntax#190

@swift-ci please test

**Comment by owenv** [comment]
apple/swift-syntax#190

@swift-ci please test source compatibility

**Review by rintaro — APPROVED** [review]
Looks good. Thank you.

**Comment by owenv** [comment]
@rintaro thank you!

I also forgot to mention, I'm not sure if the rest of the SE-276 changes will be reviewed and merged before the 5.3 branch cut in a couple weeks. In that case, should we wait to merge this to avoid changing the swift-syntax API?

If you think this is ok to merge now, do you mind helping merge this alongside apple/swift-syntax#190? I don't have commit access to swift-syntax.

**Comment by DougGregor** [comment]
https://github.com/apple/swift/pull/27776 has landed

**Comment by DougGregor** [comment]
The main PR has been merged, so do we close this one?

**Comment by owenv** [comment]
yeah, this is no longer needed, closing

**Pull request closed without merging**
