### PR TITLE
IRGen: force lazy metadata initialization for PE/COFF

### PR DESCRIPTION
**Pull request by compnerd**
The metadata reference to the parent type cannot be supported on PE/COFF
due to the direct reference to a value in an external module that is in
static data (the model requires indirecting through memory).  Always
force the lazy initialization for the metadata on such platforms.

This requires a secondary change - to initialize the VWT as well.  This
is ideally moved into the runtime where we can do this uniformly.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @slavapestov

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by slavapestov** [comment]
Nitpick: please don't use the term "parent type" since that refers to an AST concept (Foo is the parent type of Foo.Bar). Let's just say that external references to data symbols are not supported, so we cannot directly reference the NativeObject value witness table, and leave it at that.

**Comment by slavapestov** [comment]
@compnerd There are other cases where we emit direct references to external value witness tables. One example is structs with certain known layouts, eg,

```
struct Foo { var x: Int8 }
```

**Comment by compnerd** [comment]
@slavapestov - hmm, I'm not seeing that in my current build.  Compiling this for windows x86_64 seems to be fine:

```
struct S {
  var i: Int8
}
```

**Comment by jckarter** [comment]
@slavapestov IIRC we already address those cases by disabling the optimization of using preexisting value withness tables on Windows.

**Review by jckarter — APPROVED** [review]
👍🏻

**Comment by compnerd** [comment]
The Windows build is currently broken anyways due to the use of the NativeObject VWT for `AtomicInt` in SwiftPrivate.  So, I'm going to go ahead and merge this.  The only thing that really remains now is the initialization of the VWT field as well.  I intentionally left out the emission of the placeholder for the VWT for this part of the change so that we can decouple it.

**Comment by compnerd** [comment]
(Updated the commit message for @slavapestov)

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Pull request merged**
