### PR TITLE
[SemanticARCOpts] Promote moved load [copy]s to load_borrows.

### PR DESCRIPTION
**Pull request by nate-chandler**
In the context of promoting a `load [copy]` to a `load_borrow`, allow the value representing the lifetime of the load to differ from the `load [copy]` itself--it may either be the load or its only user.

If promoting the `load [copy]` to a `load_borrow` with the load itself as the lifetime representative fails, look for a single `move_value` use of the load.  If found, attempt the optimization again with the `move_value` as the lifetime representative.

rdar://108514447

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
https://ci.swift.org/job/swift-PR-macos-perf/657/

```
------- Performance (x86_64): -O -------

REGRESSION           OLD   NEW     DELTA     RATIO
StringWithCString2   0.0   0.002   +200.0%   **0.33x (?)**

------- Code size: -O -------

------- Performance (x86_64): -Osize -------

REGRESSION                         OLD       NEW       DELTA    RATIO
FlattenListFlatMap                 2580.0    4076.0    +58.0%   **0.63x (?)**
CxxStringConversion.cxx.to.swift   131.875   142.333   +7.9%    **0.93x (?)**

IMPROVEMENT                        OLD       NEW       DELTA    RATIO
StringWithCString2                 0.002     0.0       -66.7%   **3.00x**

------- Code size: -Osize -------

------- Performance (x86_64): -Onone -------

REGRESSION                         OLD      NEW     DELTA    RATIO
CxxStringConversion.cxx.to.swift   139.75   181.5   +29.9%   **0.77x (?)**

------- Code size: -swiftlibs -------
```

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Review by atrick — APPROVED** [review]
LGTM

**Pull request merged**
