### PR TITLE
Turn off speculative devirtualization by default. 

### PR DESCRIPTION
**Pull request by meg-gupta**
Also, add a flag to enable the pass.

Fixes rdar://58778959 and rdar://58429282

### CODE REVIEW

**Comment by meg-gupta** [comment]
\cc @airspeedswift

**Comment by airspeedswift** [comment]
Thanks!

**Comment by airspeedswift** [comment]
@swift-ci please benchmark

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by meg-gupta** [comment]
@swift-ci please test

**Comment by meg-gupta** [comment]
@swift-ci please test

**Review by eeckstein — APPROVED** [review]
lgtm!

**Comment by meg-gupta** [comment]
@swift-ci please test

**Comment by meg-gupta** [comment]
@swift-ci please smoke test

**Pull request merged**
