### PR TITLE
IRGen: emitObjCMetadataRef needs to handle weakly linked Objective C …

### PR DESCRIPTION
**Pull request by aschwaighofer**
…classes which maybe null

WIP, test case to follow ...

rdar://28203571

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test os x platform

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@jckarter Can you review this? I would also like to pull this into swift-3.0-branch.

**Comment by jckarter** [comment]
Looks good as a quick fix. It might be better for code size and robustness to move the null check into the `swift_getObjCClassMetadata` runtime call.

**Comment by aschwaighofer** [comment]
Good point.

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test linux platform

**Pull request merged**
