### PR TITLE
[cxx-interop] Fix header guards in test/Interop

### PR DESCRIPTION
**Pull request by hlopko**

### CODE REVIEW

**Comment by hlopko** [comment]
@swift-ci please test.

**Review by scentini — APPROVED** [review]

**Comment by hlopko** [comment]
@swift-ci please test

**Review by zoecarver — APPROVED** [review]
LGTM.

**Comment by hlopko** [comment]
@swift-ci please test.

**Comment by hlopko** [comment]
@swift-ci please test.

**Comment by hlopko** [comment]
@swift-ci please test.

**Comment by hlopko** [comment]
@swift-ci please test.

**Comment by hlopko** [comment]
@swift-ci please test.

**Pull request merged**
