### PR TITLE
cmake: pluralize SWIFT_COMPONENT to allow tools to be installed in multiple components

### PR DESCRIPTION
**Pull request by nkcsgexi**
If one of the specified component is installing, the tool will be installed.

rdar://50149995

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by akyrtzi** [comment]
It's not clear to me what is the benefit of having a tool be part of multiple components, could you explain more ?

**Comment by nkcsgexi** [comment]
it mostly a walk around of defining toolchain-tools as a sub-component of tools. we'd like to install swift-api-digester to the OSS toolchain where toolchain-tools is included but tools is excluded. For internal scenario where tools component is included, we'll also install swift-api-digester. With this change, we don't need to update internal build settings.

**Comment by akyrtzi** [comment]
> we don't need to update internal build settings.

But updating our internal build presets is not a problem that needs solving, we can just update the internal preset.

This is related to my concern that this adds another dimension to consider how to install a tool ("*do I update the preset or add it to multiple components ?*"). The model where a tool belongs to a component, and the presets control the components that get installed, is simpler, in that it makes the presets the definite source of how to install tools. The fact that you need to update the preset to install the tool is *'behaves correctly'*.

I'd recommend that we keep the 'tools belong to a single component' model and just update presets appropriately to include `toolchain-tools`.

**Pull request closed without merging**
