### PR TITLE
[SwiftSyntax] Remove force unwrapping for source location

### PR DESCRIPTION
**Pull request by kimdv**
Companion of https://github.com/apple/swift-syntax/pull/1532

### CODE REVIEW

**Comment by kimdv** [comment]
https://github.com/apple/swift-syntax/pull/1532

@swift-ci please smoke test

**Review by ahoppen — APPROVED** [review]

**Comment by kimdv** [comment]
https://github.com/apple/swift-syntax/pull/1532

@swift-ci please smoke test

**Comment by kimdv** [comment]
https://github.com/apple/swift-syntax/pull/1532
https://github.com/apple/swift-format/pull/513
https://github.com/apple/swift-stress-tester/pull/233

@swift-ci please test

**Comment by kimdv** [comment]
https://github.com/apple/swift-syntax/pull/1532
https://github.com/apple/swift-format/pull/513
https://github.com/apple/swift-stress-tester/pull/233

@swift-ci please test smoke test

**Comment by kimdv** [comment]
https://github.com/apple/swift-syntax/pull/1532
https://github.com/apple/swift-format/pull/513
https://github.com/apple/swift-stress-tester/pull/233

@swift-ci please test smoke test

**Comment by kimdv** [comment]
https://github.com/apple/swift-syntax/pull/1532
https://github.com/apple/swift-format/pull/513
https://github.com/apple/swift-stress-tester/pull/233

@swift-ci please test smoke test

**Comment by kimdv** [comment]
https://github.com/apple/swift-syntax/pull/1532
https://github.com/apple/swift-format/pull/513
https://github.com/apple/swift-stress-tester/pull/233

@swift-ci please test smoke test

**Comment by kimdv** [comment]
https://github.com/apple/swift-syntax/pull/1532
https://github.com/apple/swift-format/pull/513
https://github.com/apple/swift-stress-tester/pull/233

@swift-ci please smoke test

**Comment by kimdv** [comment]
https://github.com/apple/swift-syntax/pull/1532
https://github.com/apple/swift-format/pull/513
https://github.com/apple/swift-stress-tester/pull/233

@swift-ci please smoke test

**Comment by kimdv** [comment]
https://github.com/apple/swift-syntax/pull/1532
https://github.com/apple/swift-format/pull/513
https://github.com/apple/swift-stress-tester/pull/233

@swift-ci please smoke test

**Pull request merged**
