### PR TITLE
Sema: Set the type of ParenExpr to ParenType

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@xedin I addressed your review feedback in a slightly different way -- the redundant "is single parameter with no label" check is actually not necessary at all, and it simplifies the ASTVerifier a little as well.

(The other patch is unrelated -- I just noticed someone recently removed some code from IRGen but forgot one function.)

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Review by xedin — APPROVED** [review]
Nice!

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Pull request merged**
