### PR TITLE
[PrintAsObjC] Pull the actual decl/type printer out to a separate file

### PR DESCRIPTION
**Pull request by jrose-apple**
I've tried several times to separate the type printing from the decl-printing and found it tricky, but at least both can be separated from the logic of walking the top-level decls in a module and scheduling them appropriately. No functionality change.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Review by beccadax — CHANGES_REQUESTED** [review]
Github didn't make it easy to understand what happened to DeclAndTypePrinter.cpp, so I built a gist to show the differences: https://gist.github.com/brentdax/ec2d1070c867de20274f02f32402778a/revisions?diff=unified

I still didn't give that diff a *really* detailed read, but skimming it LGTM; I just have one small request.

**Comment by jrose-apple** [comment]
I was expecting reviewers to skip the first PR since it's "just" moving things, or maybe only looking at what changed on the PrintAsObjC and DeclAndTypePrinter header sides. But yeah, comment is fair.

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Review by beccadax — APPROVED** [review]
This is about a thousand times better!

**Pull request merged**
