### PR TITLE
[AST] Break some header dependencies for faster rebuilds

### PR DESCRIPTION
**Pull request by jrose-apple**
DiagnosticEngine.h no longer depends on Attr.h.
Expr.h no longer depends on TypeRepr.h.

No functionality change.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
The original goal of this was to make Attr.def touch fewer files but I don't think I succeeded because of AttrKind.h.

**Review by varungandhi-apple — APPROVED** [review]

**Review by CodaFi — APPROVED** [review]
Good stuff. Is there a tool or methodology you have for detecting these coarse dependencies?

**Comment by jrose-apple** [comment]
Nothing so advanced, just find a header that bothers me and look wherever it's included in other headers (as opposed to .cpp files). If I can't break a link, see if I can break the *next* link after that.

**Pull request merged**
