### PR TITLE
Improve optimization of lazy properties.

### PR DESCRIPTION
**Pull request by eeckstein**
There are two main changes here:

* Prevent inlining of lazy property getters

Lazy property getters are usually non tivial functions (otherwise the user would not implement it as lazy property).
Inlining such getters would most likely not benefit other optimizations because the top-level switch_enum cannot be constant folded in most cases.
Also, not inlining lazy property getters enables optimizing them in CSE.

* Optimize calls of lazy property getters

If such a call is dominated by another call to the same getter, it is replaced by a direct load of the property - assuming that it is already computed.

rdar://problem/34715412

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci test

**Review by atrick — COMMENTED** [review]
Nice!

To be rigorous, it seems like `isLazyPropertyGetter` should check that the .some value is being returned by the function.

**Pull request merged**
