### PR TITLE
More accurately lower assign instruction in DI

### PR DESCRIPTION
**Pull request by trentxintong**

### CODE REVIEW

**Comment by trentxintong** [comment]
@swift-ci Please test

**Comment by trentxintong** [comment]
@gottesmm can you please review this ? I think its correct.

**Comment by trentxintong** [comment]
@swift-ci Please test

**Comment by lattner** [comment]
This looks fine to me from a correctness perspective.  Does it actually help with store->load forwarding?   I suppose that the issue is that you don't know if a release could call a deinit which could change the memory?

**Comment by trentxintong** [comment]
yep. we do not know whether the release is going to call deinit or not. And therefore RLE fails.

I have a microbenchmark that improved a lot because RC identity analysis can reason about the RR pairs after RLE happens and eliminate 1 RR pair.

I have not measured on the performance benchmark suite.

**Comment by lattner** [comment]
Cool, ok, makes sense.

**Comment by trentxintong** [comment]
I talked to Michael in person. He thinks its not particularly safe to do the release before the memory location is overwritten (i.e. the store). This would potentially leave us in a state which a memory is holding a reference to an object, but the object would been freed.

**Comment by jckarter** [comment]
That'd only be a concern if there's an alias to the memory that might read from it before it's reinitialized.

**Comment by trentxintong** [comment]
one of the concerns is if we have g.foo = foo() and we move the release %2 before the store, we could have a case which the deinit read g.foo and the user program is going to believe that we are calling deinit of an object which we still keeps a reference to in memory. 

retain %1
%2 = load  &g.foo
release %2
store %1 -> &g.foo

Do you think this is going to be a problem with the semantics of the language ?

**Comment by jckarter** [comment]
That's a good point. More generally, if `release %2` invokes a destructor and `&g.foo` has escaped, then it could be observed in its uninitialized state. If `&g.foo` is a local `alloc_stack` that shouldn't be possible, but generally you wouldn't be able to get away with this.

**Comment by atrick** [comment]
I explained this in the radar. Briefly:

A release cannot be moved above a store unless we can prove either
(a) the stored-to location cannot reference the released object
(b) the object's deinitializer cannot access the stored to location

**Comment by trentxintong** [comment]
I think we should leave DI to lower assign as what it is and rely on SILCodeMotion to move the release up.  Or let side-effect analysis to reason that the release can not overwrite the stored memory.

**Comment by lattner** [comment]
>I think we should leave DI to lower assign as what it is and rely on SILCodeMotion to move the release up, or let side-effect analysis to reason that the release can not overwrite the stored memory.

Agreed.

**Pull request closed without merging**
