### PR TITLE
[swift-inspect] Start at least building swift-inspect on Darwin.

### PR DESCRIPTION
**Pull request by gottesmm**
Just for testing for now.

### CODE REVIEW

**Comment by gottesmm** [comment]
@shahmishal What do you think?

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
Already passed, just want to check that we actually built it.

**Comment by gottesmm** [comment]
@swift-ci test macOS platform

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by gottesmm** [comment]
@mikeash one thing we may want to do is make this use the shared swiftpm build root. I think you are building ArgumentParser for the Nth time. I still think enabling this in the short terms good. I checked the macOS build and it did build swift inspect. That way we at least know it keeps working.

**Comment by mikeash** [comment]
Makes sense to me. How hard is it to make it use the shared build root?

**Comment by gottesmm** [comment]
Not much. It is easy to fix.

**Comment by gottesmm** [comment]
@mikeash looks like swift inspect doesn't work on Linux.  (Windows it isn't built).

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
I was wrong about the shared root. I thought we had more infrastructure for it. I am going to look into it in the future. Not much increase in compile time overall though.

**Pull request merged**
