### PR TITLE
[scale-test] Reporting an error if --step is wider than the begin/end range

### PR DESCRIPTION
**Pull request by moiseev**
I totally forgot to set `--step` and got a "division by zero" error for it.

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please python lint

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Review by graydon — APPROVED** [review]
LGTM

**Comment by moiseev** [comment]
@swift-ci Please python lint

**Comment by moiseev** [comment]
@swift-ci Please smoke test and merge

**Comment by moiseev** [comment]
@swift-ci Please python lint

**Comment by moiseev** [comment]
@swift-ci Please smoke test and merge

**Pull request merged**
