### PR TITLE
Adds KeyPath test to benchmark suite

### PR DESCRIPTION
**Pull request by taylorGeisler**
This pull request adds a test of KeyPaths performance to the benchmark suite. It creates a fixed size array struct and KeyPaths to its properties. It does work inside of a loop by accessing the properties with KeyPaths.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by CodaFi** [comment]
@swift-ci benchmark

**Review by eeckstein — CHANGES_REQUESTED** [review]
The key path accesses are all optimized away. You can use ``identity`` to prevent that, e.g.
```
    let kp0 = identity(FixedSizeArray10<Double>.getKeypathToElement(index: 0))
```

Also, it would be nice to benchmark other key path operations, like: subscripts, getters, setters.

**Comment by taylorGeisler** [comment]
@swift-ci benchmark

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Comment by taylorGeisler** [comment]
@eeckstein Overall I'd like this benchmark to highlight the performance difference between the KeyPath and Direct Access implementations in working with struct properties. Any further suggestions?

**Comment by eeckstein** [comment]
>  Overall I'd like this benchmark to highlight the performance difference between the KeyPath and Direct Access implementations

The difference between both benchmarks is not reported in a benchmark run, e.g. on CI. So the only way to see the difference is to compile the benchmarks locally and manually compare both results.
And ``runStructDirectAccessComputation`` as a stand-alone benchmark is not very useful, IMO.

You can keep ``runStructDirectAccessComputation`` if you think you'd like to do this manual comparison by your own, but then please add the ``skip`` tag, so that it does not run by default.
Or you just delete the benchmark.

**Review by eeckstein — APPROVED** [review]
lgtm, thanks!

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Comment by eeckstein** [comment]
@taylorGeisler I just saw that you moved the keypath variables out of the function and made them global. That is not good, because accesses to (non-trivial) globals is slow.
Please move those variables back into the function.

**Comment by BradLarson** [comment]
My coworker (from the same company that originated this PR) has been working on a more extensive set of keypath benchmarks in #60383, so I believe it is safe to close out this PR in favor of that newer one.

**Pull request closed without merging**
