### PR TITLE
[Serialization] Store the path inside ModuleSearchPath as a string, not a StringRef

### PR DESCRIPTION
**Pull request by ahoppen**
The idea behind storing a StringRef in https://github.com/apple/swift/pull/40155 was to reduce the memory footprint because we made the assumption that a `ModuleSearchPath` always outlives the `SearchPathOptions` it was created from. What I did not consider was that the path was referencing into a `std::vector`, which could get resized, thus invaliding the memory the `ModuleSearchPath`’s `StringRef` was pointing to, causing memory corruption.

To fix this, store the path string inisde the `ModuleSearchPath` itself. Since we store a `ModuleSearchPath` for every file inside that module search path in the `LookupTable`, by itself this would cause a new copy of the path to be stored for every file inside a module search path. To avoid this, make `ModuleSearchPath` ref counted and only store a reference to one shared `ModuleSearchPath` entry in the lookup table.

rdar://88888679

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Review by bnbarham — APPROVED** [review]
Would you mind adding something like "in `addImportSearchPath`/`addFrameworkSearchPath`" to the commit description, I was looking around for a little while wondering where they are added to outside of `set*Paths` 😆.

Another way we could do this would be to have a BumpPtrAllocator that we just copy the paths into and then clear on a rebuild. IMO that would be a little cleaner (no need to mess around with the ref counted pointer), but this method works as well 🤷.

Sorry for not noticing this in the original review. It's a super common problem and I should have picked up on it!

**Comment by ahoppen** [comment]
> Another way we could do this would be to have a BumpPtrAllocator that we just copy the paths into and then clear on a rebuild. IMO that would be a little cleaner (no need to mess around with the ref counted pointer), but this method works as well 🤷.

I tried the same but if we do this we need to be careful to always store strings in the bump allocator before referencing them in `ModuleSearchPath`. I decided that that’s just too easy to get wrong and that’s why I went with the ref-counted `ModuleSearchPath`. Plus it also had the benefit of de-duplicating the memory for `Kind`, `IsSystem` and `Index`.

We could think about storing the `ModuleSearchPath`s in a bump allocator, but again, I think the extra complexity of having to manage the bump allocator is not really worth the IMHO super minor performance benefit.

**Comment by bnbarham** [comment]
> I tried the same but if we do this we need to be careful to always store strings in the bump allocator before referencing them in `ModuleSearchPath`. I decided that that’s just too easy to get wrong and that’s why I went with the ref-counted `ModuleSearchPath`. Plus it also had the benefit of de-duplicating the memory for `Kind`, `IsSystem` and `Index`.

I meant an allocator in `ModuleSearchPathLookup`, so it would just be the one copy where the `new ModuleSearchPath` is right now. But as I said, I'm happy with either. Was just mentioning in case you thought it helped 👍

**Comment by ahoppen** [comment]
Ah, OK. Still, I think I like the ref-counted `ModuleSearchPath` better. Merging.

**Pull request merged**
