### PR TITLE
[AST] Change some builtins to conform their result to Escapable

### PR DESCRIPTION
**Pull request by Azoy**
Some of these builtins were not constraining their result type to conform to Escapable. This caused some inference failures when building the standard library.

Specifically I changed:
* `Builtin.load`
* `Builtin.take`
* `Builtin.copy`
* `Builtin.allocWithTailElems_N`
* `Builtin.COWBufferForReading`
* `Builtin.castReference`
* `Builtin.reinterpretCast`
* `Builtin.convertUnownedUnsafeToGuaranteed`

### CODE REVIEW

**Comment by Azoy** [comment]
@swift-ci please smoke test

**Review by meg-gupta — APPROVED** [review]
LGTM, thanks!

**Review by atrick — APPROVED** [review]
Thanks!

Eventually, we'll need to support `Builtin.load` and `Builtin.take` with `~Escapable` elements. We'll need to figure out a way around the type checker when that time comes.

**Comment by atrick** [comment]
Merging because I want to start filing downstream bugs. Apologies for not waiting for a full CI test.

**Pull request merged**
