### PR TITLE
build-script-impl: Don't let distcc farm out cmake to run on other machines.

### PR DESCRIPTION
**Pull request by erg**

### CODE REVIEW

**Comment by erg** [comment]
@swift-ci Please smoke test

**Comment by erg** [comment]
@gottesmm What do you think about the above patch idea?

**Comment by gottesmm** [comment]
@erg That was the original intention of that line. So I am all for this. We should make sure that this still solve's DaveA's issue before we continue though.

**Comment by dabrahams** [comment]
None of the changes we're making now make sense to me.  Maybe we should wait until we can discuss this in person.

**Pull request merged**
