### PR TITLE
[gardening] Remove uses of "importDeclCached" and cleanup "VisitEnumConstantDecl".

### PR DESCRIPTION
**Pull request by zoecarver**
Cleans up the EnumConstantDecl visitor by consolidating cases and removing calls to "importDeclCached".

There are many cleanups that need to happen (both in the design and QoI) for enums, but this is a start.

### CODE REVIEW

**Comment by zoecarver** [comment]
@swift-ci please smoke test.

**Comment by zoecarver** [comment]
@swift-ci please smoke test.

**Comment by zoecarver** [comment]
@swift-ci please smoke test.

**Review by slavapestov — APPROVED** [review]

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by zoecarver** [comment]
Thanks @slavapestov!

**Comment by zoecarver** [comment]
Looks like somehow the CI got messed up. It looks like the Linux and MacOS bots both succeeded but aren't getting reported properly. I'll re-trigger them.

**Comment by zoecarver** [comment]
@swift-ci please smoke test Linux.

**Comment by zoecarver** [comment]
@swift-ci please smoke test OS X.

**Comment by zoecarver** [comment]
@swift-ci please smoke test OS X.

**Pull request merged**
