### PR TITLE
[AutoDiff] Fix double release in indirect pullback results.

### PR DESCRIPTION
**Pull request by rxwei**
Previously two `destroy_addr`s may be emitted on the same result from a pullback when the result is indirect. This caused segfaults in [TF-437](https://bugs.swift.org/browse/TF-437).

Since we are looping over all pullback results in `AdjointEmitter::visitApplyInst`, we should release the unused ones and indirect ones as we go over and process them. There should not be a call to `emitRelease` before we deallocate all indirect adjoint buffers.

Resolves [TF-437](https://bugs.swift.org/browse/TF-437).

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
TODO: Add a test.

**Review by dan-zheng — APPROVED** [review]

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux

**Comment by marcrasi** [comment]
Does the "self" code directly above the loop that you modified need the same change?

**Comment by rxwei** [comment]
Yes good catch.

**Comment by rxwei** [comment]
Done!

**Comment by rxwei** [comment]
@marcrasi Oops, i was deleting "please test" comments and accidentally deleted yours!

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux

**Review by marcrasi — APPROVED** [review]

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux

**Pull request merged**
