### PR TITLE
Cherry pick some fixes to qualification branch

### PR DESCRIPTION
**Pull request by slavapestov**
rdar://problem/48218483

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by AnnaZaks** [comment]
This is a PR for 48218483(submission blocker), 48226583(swift 5.0 bug), and fixes that were when trying to build Amber resiliently (48218457).

**Comment by AnnaZaks** [comment]
This also contains a cherry-pick for a fix to Swift 5.0: 48226583 / https://github.com/apple/swift/pull/22737

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Pull request merged**
