### PR TITLE
[stdlib] Implement New UTF32 transcoding

### PR DESCRIPTION
**Pull request by dabrahams**

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please test

**Comment by dabrahams** [comment]
@swift-ci Please benchmark

**Comment by dabrahams** [comment]
@airspeedswift Merging this PR canceled the benchmark run AFAICT.

**Comment by airspeedswift** [comment]
I think it still turns up when it completes.

**Comment by airspeedswift** [comment]
You can still navigate to the job in CI by hovering over the gold dot (that hopefully will become a green tick) next to the commit.

**Pull request merged**
