### PR TITLE
[parse] Recover better from malformed subscript decls for code-completion

### PR DESCRIPTION
**Pull request by benlangmuir**
Code-completion of generic types expects to get a DeclContext for the
subscript, so make sure we recover well enough to produce a
SubscriptDecl.

rdar://35619175

### CODE REVIEW

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@DougGregor any concerns about the type-checker changes or in general about subscript element type now being potentially null?

**Comment by slavapestov** [comment]
Can we set the element type to ErrorType in the recovery path in the parser instead, so that downstream clients don't have to handle it?

**Comment by slavapestov** [comment]
Talked to @benlangmuir in person, we're both happy with the fix now.

**Comment by benlangmuir** [comment]
The test failure is a crash in a case we used to give up earlier.  We're crashing because there is no interface type on the parameter of the getter for the subscript:

```
frame #4: 0x0000000102a25878 swiftc`swift::ValueDecl::getInterfaceType(this=0x0000000113847f80) const at Decl.cpp:1923
frame #5: 0x0000000102bfdca1 swiftc`swift::ParameterList::getInterfaceType(this=0x0000000113848018, C=0x0000000114009a00) const at Parameter.cpp:147
frame #6: 0x0000000102249ef1 swiftc`swift::TypeChecker::configureInterfaceType(this=0x00007ffeefbf7c78, func=0x0000000113848040, sig=0x0000000113849570) at TypeCheckGeneric.cpp:910
frame #7: 0x000000010220230e swiftc`(anonymous namespace)::DeclChecker::visitFuncDecl(this=0x00007ffeefbf70f8, FD=0x0000000113848040) at TypeCheckDecl.cpp:5291
```

But I don't see how this was going to work.  In the parser, if a subscript is not inside a container type, we immediately set its interface type:
```C++
  if (Invalid) {
    Subscript->setInterfaceType(ErrorType::get(Context));
    Subscript->setInvalid();
  }
```

And the DeclChecker sees that the decl has a type, so it early-exits without setting types on the parameters of the Subscript.  Then we propagate the same types onto the Decl for the accessor, which then asserts because it expects a parameter type.

@slavapestov what part(s) of this chain of events are incorrect?  I'm not sure how to proceed.

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
Update: I talked to Doug in person about this and he suggested we not set the interface type in the parser but let the DeclChecker do it correctly.  I also took another look at how parameters are handled and discovered that while they can be null, that only should happen with closures not with functions, so instead of using null I'm setting ErrorTypeRepr on the element type to be more consistent, which is also closer to what Slava originally suggested.

**Comment by benlangmuir** [comment]
@swift-ci please test

**Pull request merged**
