### PR TITLE
[benchmark] Finish Naming Convention Support

### PR DESCRIPTION
**Pull request by palimondo**
These are few commits extracted from #20552, which has been stuck in limbo for a while, to fix the `LogParser` support for the new Benchmark Naming Convention from #20334 and use the 40 character limit to better align columns in `Benchmark_Driver`'s console output (in `-output-dir` mode).

### CODE REVIEW

**Comment by palimondo** [comment]
@swift-ci please benchamrk

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
@swift-ci please smoke test

**Comment by palimondo** [comment]
@eeckstein please review 🙏

**Review by eeckstein — APPROVED** [review]

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
@swift-ci please smoke test os x platform

**Pull request merged**
