### PR TITLE
[4.2 04-30] Fixes for String performance regressions

### PR DESCRIPTION
**Pull request by eeckstein**
For details see commits.

rdar://problem/39978743

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
**Explanation**: These changes fix some major regressions, which were introduced with the new String implementation
**Scope**: It affects much real-world code which deals with Strings.
**Radar/SR Issue**: rdar://problem/39978743
**Risk**: Low: the changes are simple and already tested since a while on master.
**Testing**: Tested with all the String tests in test suite.
**Reviewer**: @milseman

**Review by milseman — APPROVED** [review]
LGTM

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by milseman** [comment]
@swift-ci please test linux platform

**Pull request merged**
