### PR TITLE
Collection of rebranch fixes

### PR DESCRIPTION
**Pull request by etcwilde**
This is a collection of changes to `next` to get things working toward building. We still have some issues in LLVM and the optimizer to work through.

### CODE REVIEW

**Comment by etcwilde** [comment]
@swift-ci please smoke test

**Comment by etcwilde** [comment]
Okay, we're getting to later failures. This one is particularly cute since we have the definition coming from the stdlib copy of MathExtras, and because LLVM now has a new bit.h. I'll probably have to pull out a `bit.h` with the duplicate API's so that there is a consistent spelling that everything can resolve to without breaking ABI.

```
In file included from /Users/ec2-user/jenkins/workspace/swift-PR-macos-smoke-test/branch-next/swift/stdlib/public/SwiftRemoteMirror/SwiftRemoteMirror.cpp:26:
In file included from /Users/ec2-user/jenkins/workspace/swift-PR-macos-smoke-test/branch-next/swift/include/swift/RemoteInspection/ReflectionContext.h:24:
In file included from /Users/ec2-user/jenkins/workspace/swift-PR-macos-smoke-test/branch-next/llvm-project/llvm/include/llvm/Object/COFF.h:26:
/Users/ec2-user/jenkins/workspace/swift-PR-macos-smoke-test/branch-next/llvm-project/llvm/include/llvm/TargetParser/SubtargetFeature.h:99:22: error: no member named 'popcount' in namespace 'llvm'
   99 |       Count += llvm::popcount(B);
      |                ~~~~~~^
```

**Review by ahoppen — COMMENTED** [review]
`include/IDE` and `lib/IDE` changes LGTM.

**Comment by etcwilde** [comment]
@bnbarham I put up https://github.com/apple/swift/pull/67285 to migrate what deprecated-APIs could over on `main`.

**Review by bnbarham — APPROVED** [review]

**Pull request merged**
