### PR TITLE
remove not necessary '---'

### PR DESCRIPTION
**Pull request by ghost**
just in case if --- confuse the md

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please test

**Comment by CodaFi** [comment]
@shahmishal Is there any reason we wouldn't want to take this?  LLVM's YAML serializer is going to keep trying to put this comment line here - but otherwise there's no semantic change.

**Comment by shahmishal** [comment]
cc: @lorentey

**Comment by compnerd** [comment]
@CodaFi - are the APINotes processed as YAML through LLVM or MarkDown through CMark?

**Comment by compnerd** [comment]
CC: @jrose-apple

**Comment by jrose-apple** [comment]
YAML. It's true that [YAML documents are not required to start with the document separator](https://yaml.org/spec/1.2/spec.html#id2800967), so sure. (os.apinotes already doesn't have it.)

(…Markdown?)

**Comment by lorentey** [comment]
Sure. But what is the reason for this change? Just cosmetics? Or is there an actual issue?

FWIW, the latest Xcode beta ships with 94 apinotes files in the macOS SDK alone, most of which start with the triple dash.

**Comment by CodaFi** [comment]
There hasn't been movement here in a few months and this change isn't strictly necessary.  Going to close this out.  If you wish to pursue this further, please reopen this pull request.

**Pull request closed without merging**
