### PR TITLE
Add attr to enable lexical lifetime per function.

### PR DESCRIPTION
**Pull request by nate-chandler**
Enables modules to migrate to the new lifetime rules incrementally.

### CODE REVIEW

**Comment by nate-chandler** [comment]
Please test with following pull request:
https://github.com/apple/swift-syntax/pull/1349

@swift-ci Please test

**Comment by nate-chandler** [comment]
Please test with following pull request:
https://github.com/apple/swift-syntax/pull/1349

@swift-ci Please test

**Comment by nate-chandler** [comment]
Please test with following pull request:
https://github.com/apple/swift-syntax/pull/1349

@swift-ci Please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by xedin — APPROVED** [review]
Sema changes LGTM :)

**Review by atrick — COMMENTED** [review]
All changes look good. Thanks for doing this. It'll be nice to play with even if we don't end up using it. I notice that we still appear to support `_noEagerMove` too, so we have all the controls.

**Pull request merged**
