### PR TITLE
Add 'ExtraStringAPIs.swift' to make list.

### PR DESCRIPTION
**Pull request by natecook1000**
This one file was missing from the make list, resulting in `String.UTF16View.Index` not getting random-access index capabilities.

### CODE REVIEW

**Comment by gribozavr** [comment]
Could you add a test, checking that when Foundation is imported, the index gets the conformance, and does not otherwise?

**Comment by natecook1000** [comment]
Do you have advice about how/where to write such a test? I'm not totally familiar with the testing framework, and [this comment](https://github.com/apple/swift/blob/a30ae2bf55e21859418da6b8cd28273d5b71719c/test/1_stdlib/NoFoundation.swift#L21) implies that kind of test may be easier said than done. Is the test in that file validating the no-Foundation case via compilation?

**Comment by gribozavr** [comment]
@natecook1000 That test is checking that Foundation is not loaded by checking for the absence of the conformance.

To test for the presence of the conformance, just pass the index to a generic function that expects a random access index.  That code should compile (no need to run it).  That test can go into `test/1_stdlib/StringDiagnostics.swift`.

To test for the absence, do the same, but don't import Foundation, and add an expected diagnostic to the file.  You can put that into a new file, `StringDiagnostics_without_Foundation.swift`.

**Comment by natecook1000** [comment]
@gribozavr Thanks! I've added positive and negative conformance tests for all the string index types.

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by gribozavr** [comment]
@swift-ci Please test

**Pull request merged**
