### PR TITLE
[gardening] Address a typo and some punctuation in WindowsBuild.md

### PR DESCRIPTION
**Pull request by xwu**
This PR performs some minor gardening; specifically, it addresses a typo and some punctuation and capitalization.

### CODE REVIEW

**Comment by xwu** [comment]
@swift-ci Please smoke test

**Review by DougGregor — APPROVED** [review]
LGTM

**Comment by shahmishal** [comment]
@swift-ci Please smoke test

**Comment by xwu** [comment]
@swift-ci Please smoke test Linux platform

**Comment by AndrewSB** [comment]
LGTM, thanks @xwu!

**Pull request merged**
