### PR TITLE
[code-completion] Generic where clauses

### PR DESCRIPTION
**Pull request by benlangmuir**
* Explanation: Adds support for code-completion inside generic where clauses and along the way fixes some crashes when trying to code-complete in where clauses caused by looking up in the wrong decl context.  Note: there is some remaining work (rdar://problem/33678485) to do for finding conformances when completing in where clauses in `associatedtype` decls.
* Scope: Affects code-completion in generic where clauses.
* Radar: rdar://problem/20582394 and rdar://problem/31960902
* Risk: Low; mostly changes to recovery code to avoid throwing out ASTs and to have the parser more correctly set the parsed DeclContext which is used by code-completion.
* Testing: Regression tests added.

### CODE REVIEW

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
Note: there was a test merge issue on one of the crashers (0005); I tentatively marked all the RUN lines to no longer crash, which is how it behaves on master, but I may need to back out some of them because of unrelated differences in Sema between swift-4 and master.

**Comment by slavapestov** [comment]
@benlangmuir Thanks for fixing this!

**Review by DougGregor — APPROVED** [review]
Thank you!

**Pull request merged**
