### PR TITLE
[Diagnostics] Transfer previously resolved types directly from expressions

### PR DESCRIPTION
**Pull request by xedin**
While trying to diagnose the problem with previously type-checked
sub-expression, use its type-checked variant as a source of type
information, instead of transferring from its original constraint system,
because if expression was type-checked successfully it would
have all of the required information in AST, and that doesn't
rely on associated constraint system being present.

Resolves: rdar://problem/42056741

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test

**Review by rudkx — APPROVED** [review]
LGTM. That code was required at one point but I suspect we're caching more types in enough places that it's now more of a problem than a solution.

You can remove the tranferExprTypes() method at this point, too.

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
Removing `transferExprTypes` in the separate commit so it could be reverted if needed.

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by slavapestov** [comment]
Can you add the type checker test case as well? IIRC it didn’t crash on master but still emitted a duplicate diagnostic.

**Comment by xedin** [comment]
The example I've added doesn't crash without code-completion because that triggers diagnostics differently, I couldn't make it crash without using code completion, and it also doesn't produce duplicate diagnostics either, you might be thinking of a different example...

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Pull request merged**
