### PR TITLE
ClosureLifetimeFixup : Fix bug in lifetime extension of non escaping closure

### PR DESCRIPTION
**Pull request by meg-gupta**

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci test and merge

**Comment by meg-gupta** [comment]
@swift-ci test

**Review by atrick — APPROVED** [review]
Awesome! Very nice. Thank you.

Maybe @aschwaighofer will want to take a lot too.

Do you think there should be a SIL test to make it clear what the transformation actually does? Or maybe use the option to dump the OSSA module? The final non-OSSA SIL is a little confusing.

**Comment by meg-gupta** [comment]
@atrick just added a SIL test

**Comment by meg-gupta** [comment]
cc @eeckstein @nate-chandler Here's the fix for the closure lifetime issue

**Pull request merged**
