### PR TITLE
[DNM] Building toolchain

### PR DESCRIPTION
**Pull request by ktoso**
To get a more recent toolchain

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please build toolchain

**Comment by ktoso** [comment]
@swift-ci please build toolchain macOS

**Comment by drexin** [comment]
@swift-ci build toolchain macOS

**Comment by drexin** [comment]
@swift-ci build toolchain macos

**Comment by ktoso** [comment]
@swift-ci build toolchain macos

**Comment by drexin** [comment]
@swift-ci build toolchain macOS

**Comment by ktoso** [comment]
We got a toolchain locally, there's plenty unrelated issues flying around right now.
Closing for now.

**Pull request closed without merging**
