### PR TITLE
[Sema] Reject `@objc` functions with incompatible property wrapper in…

### PR DESCRIPTION
**Pull request by drexin**
… params

rdar://99443365

When genrating `@objc` functions, the parameters were not checked for property wrapper and instead only the wrapped type was checked for compatibility. Added checks and diagnostics for incompatible property wrappers.

### CODE REVIEW

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by jckarter** [comment]
Looks good, thanks for fixing this!

**Comment by drexin** [comment]
@swift-ci smoke test macos

**Comment by drexin** [comment]
@swift-ci smoke test macos

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@swift-ci smoke test

**Pull request merged**
