### PR TITLE
Future-proof the layout of AsyncTask

### PR DESCRIPTION
**Pull request by rjmccall**

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please test

**Comment by rjmccall** [comment]
@swift-ci Please test

**Review by ktoso — APPROVED** [review]
Awesome cleanup, thanks a lot! LGTM

**Comment by rjmccall** [comment]
@swift-ci Please test

**Comment by rjmccall** [comment]
@swift-ci Please test

**Pull request merged**
