### PR TITLE
[Driver] Pass -emit-irgen thru to frontend.

### PR DESCRIPTION
**Pull request by nate-chandler**
Add a new filetype for this mode option: "Raw LLVM IR". When the mode option is emit-irgen, the new filetype will be the output kind; conversely when determining the mode option to use, if the output kind is the new filetype, the mode option will be emit-irgen.

rdar://135437693

### CODE REVIEW

**Comment by nate-chandler** [comment]
@artemcm Is there a corresponding change to make in the swift-driver repo?

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
> Is there a corresponding change to make in the swift-driver repo?
The same reverse mapping seems to be done there too:
```
extension FileType {
  /// Determine the frontend compile option that corresponds to the given output type.
  fileprivate var frontendCompileOption: Option {
    switch self {
    ...
    case .llvmIR:
      return .emitIr
```

**Comment by nate-chandler** [comment]
https://github.com/swiftlang/swift-driver/pull/1706

@swift-ci please test

**Comment by nate-chandler** [comment]
https://github.com/swiftlang/swift-driver/pull/1706

@swift-ci please test

**Review by tshortli — APPROVED** [review]

**Comment by nate-chandler** [comment]
https://github.com/swiftlang/swift-driver/pull/1706

@swift-ci please test

**Comment by nate-chandler** [comment]
```
Test Suite 'AsyncUtilsTests' started at 2024-10-02 20:33:45.739.
Test Case '-[SKSupportTests.AsyncUtilsTests testWithTimeout]' started.
/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/sourcekit-lsp/Tests/SKSupportTests/AsyncUtilsTests.swift:21: error: -[SKSupportTests.AsyncUtilsTests testWithTimeout] : failed - Expression was expected to throw but did not throw
Test Case '-[SKSupportTests.AsyncUtilsTests testWithTimeout]' failed (2.941 seconds).
Test Suite 'AsyncUtilsTests' failed at 2024-10-02 20:33:48.681.
         Executed 1 test, with 1 failure (0 unexpected) in 2.941 (2.941) seconds
```

**Comment by nate-chandler** [comment]
https://github.com/swiftlang/swift-driver/pull/1706

@swift-ci please test macos platform

**Pull request merged**
