### PR TITLE
Implementation of rotate algorithm, equivalent to std::rotate() in C++

### PR DESCRIPTION
**Pull request by bolshedvorsky**
Initial implementation of rotate function in stdlib. Ticket #SR-125

Is it the right place for this function?
Is it the right place for the test?

### CODE REVIEW

**Comment by lattner** [comment]
Dmitri, this should go to swift-evolution first, right?

**Comment by lattner** [comment]
@gribozavr that is.

**Comment by gribozavr** [comment]
@lattner Yes, it should.

@bolshedvorsky Please write an informal proposal to swift-evolution.  One piece of feedback that you could immediately incorporate is that this algorithm should be defined on `MutableCollection` instead of `Arrray`.

**Comment by gribozavr** [comment]
@bolshedvorsky Are you planning to work on this in a different PR?

**Comment by bolshedvorsky** [comment]
Yes, I will work on this in a different PR. I'm finishing a formal proposal for this feature. I will create a new PR for this feature once the proposal will be accepted.

**Comment by gribozavr** [comment]
@bolshedvorsky Thanks!

**Pull request closed without merging**
