### PR TITLE
Linux: Fix -static-executable and remove swiftImageInspectionShared

### PR DESCRIPTION
**Pull request by spevans**
- Remove references to swiftImageInspectionShared on Linux and dont have
  split libraries between static/non-static linked executables.

- -static-executable now links correctly Linux.

  Note: swift::lookupSymbol() will not work on statically linked
        executables but this can be worked around by using the
        https://github.com/swift-server/swift-backtrace package.

### CODE REVIEW

**Comment by spevans** [comment]
Please test with following pull request:
apple/swift-integration-tests#69

@swift-ci please test

**Review by compnerd — APPROVED** [review]
This looks largely like my original change with the addition of a test case!

**Comment by spevans** [comment]
Please test with following pull request:
apple/swift-integration-tests#74

@swift-ci please test

**Comment by spevans** [comment]
Please test with following pull request:
apple/swift-integration-tests#74

@swift-ci please test

**Comment by spevans** [comment]
@swift-ci test and merge

**Comment by spevans** [comment]
@swift-ci test and merge

**Comment by brentdax** [comment]
@spevans @compnerd Hiya. [It looks like this change may have broken static linking on at least CentOS](https://ci.swift.org/job/oss-swift-package-centos-7/195/consoleFull):

```
******************** TEST 'Swift(linux-x86_64) :: Driver/static-executable-linux.swift' FAILED ********************
Script:
--
: 'RUN: at line 5';   rm -rf "/home/build-user/build/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/Driver/Output/static-executable-linux.swift.tmp" && mkdir -p "/home/build-user/build/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/Driver/Output/static-executable-linux.swift.tmp"
: 'RUN: at line 6';   /home/build-user/build/buildbot_linux/swift-linux-x86_64/bin/swiftc -target x86_64-unknown-linux-gnu -toolchain-stdlib-rpath  -module-cache-path '/home/build-user/build/buildbot_linux/swift-linux-x86_64/swift-test-results/x86_64-unknown-linux-gnu/clang-module-cache' -static-executable -o /home/build-user/build/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/Driver/Output/static-executable-linux.swift.tmp/static-executable /home/build-user/swift/test/Driver/static-executable-linux.swift
: 'RUN: at line 7';   /home/build-user/build/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/Driver/Output/static-executable-linux.swift.tmp/static-executable | /usr/bin/python3.6 '/home/build-user/swift/utils/PathSanitizingFileCheck' --sanitize BUILD_DIR='/home/build-user/build/buildbot_linux/swift-linux-x86_64' --sanitize SOURCE_DIR='/home/build-user/swift' --use-filecheck '/home/build-user/build/buildbot_linux/llvm-linux-x86_64/bin/FileCheck'  /home/build-user/swift/test/Driver/static-executable-linux.swift
: 'RUN: at line 8';   file /home/build-user/build/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/Driver/Output/static-executable-linux.swift.tmp/static-executable | /usr/bin/python3.6 '/home/build-user/swift/utils/PathSanitizingFileCheck' --sanitize BUILD_DIR='/home/build-user/build/buildbot_linux/swift-linux-x86_64' --sanitize SOURCE_DIR='/home/build-user/swift' --use-filecheck '/home/build-user/build/buildbot_linux/llvm-linux-x86_64/bin/FileCheck'  /home/build-user/swift/test/Driver/static-executable-linux.swift --check-prefix=FILE
--
Exit Code: 2

Command Output (stderr):
--
/home/build-user/build/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/Driver/Output/static-executable-linux.swift.script: line 4: file: command not found
FileCheck error: '<stdin>' is empty.
FileCheck command line:  /home/build-user/build/buildbot_linux/llvm-linux-x86_64/bin/FileCheck /home/build-user/swift/test/Driver/static-executable-linux.swift --check-prefix=FILE

--

********************
```

**Comment by spevans** [comment]
@brentdax Could it simply be the case that the `file` command is not installed?

The lit script is fairly simple but does include the command check:
```
// FILE: , statically linked,
```
Which is probably breaking it. However it looks like `test/Driver/static-executable-linux.swift` is actually a duplicate of `test/Driver/static-executable.swift` with the exception that the latter uses `ELF-NOT` instead. I will open a PR to remove this broken test.

Btw, is there anyway  to CI tests on Centos?

**Comment by spevans** [comment]
I have opened apple/swift#34275 to fix this.

**Pull request merged**
