### PR TITLE
[Frontend/Test] Fix flaky lock_interface test

### PR DESCRIPTION
**Pull request by xymus**
Testing that the compiler rebuilds the same module more than once with `-disable-interface-lock` was not reliable as some jobs could be executed after the module was rebuilt. Just make sure the compiler accepts the flag.

Also reorder permission change and FileCheck calls to make failures less likely to leave the tmp folder in an unwritable state.

This test was reenabled in #36185.

### CODE REVIEW

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by xymus** [comment]
@swift-ci Please test Ubuntu 20.04 platform

**Comment by xymus** [comment]
@swift-ci Please test CentOS 8 platform

**Review by CodaFi — APPROVED** [review]

**Comment by xymus** [comment]
The Ubuntu failure is unrelated, the test succeeded on both GNU/Linux platforms.

**Comment by davezarzycki** [comment]
`-j20` seems really arbitrary. What is the test trying to do?

**Comment by xymus** [comment]
It's trying to build many dependencies of Foo in parallel to make the implicit module build system try to rebuild Foo's module interface more than once. When the lock files are used it triggers a single rebuild, but without the lock files each of the frontend job can trigger its own rebuild. I believe the `-j20` is to make sure the driver runs enough job in parallel for it to be noticeable.

**Comment by davezarzycki** [comment]
1) This sounds like a stress test, since success/failure depends on good/bad luck. It should therefore have `REQUIRES: stress_test` in the test.
2) Why do you think `-j20` is the right number? Why not `-j2` or `-j2000`?

**Pull request merged**
