### PR TITLE
[build] Adjustment to reflect that we re-wrote swift-syntax/format.py in Swift

### PR DESCRIPTION
**Pull request by ahoppen**
Companion of https://github.com/apple/swift-syntax/pull/2022

### CODE REVIEW

**Review by kimdv — APPROVED** [review]

**Review by kimdv — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please smoke test macOS

**Comment by ahoppen** [comment]
@swift-ci Please smoke test Linux

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/2022

@swift-ci Please smoke test

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/2022

@swift-ci Please smoke test

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/2022

@swift-ci Please smoke test

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/2022

@swift-ci Please smoke test

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/2022

@swift-ci Please smoke test

**Pull request merged**
