### PR TITLE
[CSSimplify] Add special handling if specialized type comes from `TypeExpr`

### PR DESCRIPTION
**Pull request by xedin**
Add a special case for `TypeExpr` due to i.e. context specialization,
in such cases there is nothing for the solver to "open" so we need
to form opened type map manually.

Resolves: rdar://111059036

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@swift-ci please clean test macOS platform

**Comment by xedin** [comment]
@swift-ci please test source compatibility release

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
