### PR TITLE
[build-script] llvm-dsymutil's component is dsymutil.

### PR DESCRIPTION
**Pull request by gottesmm**
Oops...

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Review by compnerd — APPROVED** [review]
This is fine as a fix, but I think that we should just add `dsymutil` unconditionally to the list.

**Comment by gottesmm** [comment]
@compnerd my understanding is it is only on Darwin. @fredriss can confirm.

**Comment by fredriss** [comment]
It's only used on Darwin, but I suppose @compnerd knows this. I suppose you could build it as part of a cross-compile toolchain to target Darwin, but I'm not sure anyone tried this.

**Pull request merged**
