### PR TITLE
Update Metal test for Xcode 10 beta 5

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by xedin** [comment]
```
02:11:31 TIMEOUT: test_swift_let_int_dwarf (lang/swift/let_int/TestSwiftLetInt.py)
```
:(

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Review by xedin — COMMENTED** [review]
Thanks, @shahmishal!

**Pull request merged**
