### PR TITLE
[Testing] Make the 'Concurrency' directory imply `REQUIRES: concurrency'

### PR DESCRIPTION
**Pull request by davezarzycki**
Let's stop playing whack-a-mole.

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please smoke test macOS platform

**Comment by davezarzycki** [comment]
@swift-ci please smoke test macos

**Review by mikeash — APPROVED** [review]
But it's so fun....

**Review by kavon — APPROVED** [review]
Makes sense to me. In the future, I think it would be very rare to move a test out of the Concurrency directory, which would now require _adding_ a `REQUIRES: concurrency` line.

**Comment by davezarzycki** [comment]
@swift-ci please smoke test macos

**Comment by davezarzycki** [comment]
What the heck is going on with the `Concurrency/Runtime/data_race_detection.swift` failure? Is that just known broken test on `main` branch right now?

**Comment by mikeash** [comment]
@DougGregor Do you know what's going on with `data_race_detection.swift`?

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
For posterity:
```
******************** TEST 'Swift(macosx-x86_64) :: Concurrency/Runtime/data_race_detection.swift' FAILED ********************
Script:
--
: 'RUN: at line 1';   rm -rf "/Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/Concurrency/Runtime/Output/data_race_detection.swift.tmp" && mkdir -p "/Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/Concurrency/Runtime/Output/data_race_detection.swift.tmp" && xcrun --toolchain default --sdk '/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk' /Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/buildbot_incremental/swift-macosx-x86_64/bin/swiftc -target x86_64-apple-macosx10.9  -module-cache-path /Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/buildbot_incremental/swift-macosx-x86_64/swift-test-results/x86_64-apple-macosx10.9/clang-module-cache  -F '/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks' -toolchain-stdlib-rpath -Xlinker -rpath -Xlinker '/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks' -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -headerpad_max_install_names  -swift-version 4  -Xfrontend -define-availability -Xfrontend 'SwiftStdlib 9999:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999' -Xfrontend -define-availability -Xfrontend 'SwiftStdlib 5.0:macOS 10.14.4, iOS 12.2, watchOS 5.2, tvOS 12.2' -Xfrontend -define-availability -Xfrontend 'SwiftStdlib 5.1:macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0' -Xfrontend -define-availability -Xfrontend 'SwiftStdlib 5.2:macOS 10.15.4, iOS 13.4, watchOS 6.2, tvOS 13.4' -Xfrontend -define-availability -Xfrontend 'SwiftStdlib 5.3:macOS 11.0, iOS 14.0, watchOS 7.0, tvOS 14.0' -Xfrontend -define-availability -Xfrontend 'SwiftStdlib 5.4:macOS 11.3, iOS 14.5, watchOS 7.4, tvOS 14.5' -Xfrontend -define-availability -Xfrontend 'SwiftStdlib 5.5:macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0' -Xfrontend -define-availability -Xfrontend 'SwiftStdlib 5.6:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999'  -F '/Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/buildbot_incremental/swift-macosx-x86_64/lib' -Xlinker -rpath -Xlinker '/Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/buildbot_incremental/swift-macosx-x86_64/lib' -module-cache-path /Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/buildbot_incremental/swift-macosx-x86_64/swift-test-results/x86_64-apple-macosx10.9/clang-module-cache /Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/swift/test/Concurrency/Runtime/data_race_detection.swift  -Xfrontend -disable-availability-checking  -enable-actor-data-race-checks  -parse-as-library -o /Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/Concurrency/Runtime/Output/data_race_detection.swift.tmp/a.out -module-name main  && /Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/swift/utils/swift-darwin-postprocess.py /Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/Concurrency/Runtime/Output/data_race_detection.swift.tmp/a.out && /usr/bin/env DYLD_LIBRARY_PATH='/Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/buildbot_incremental/swift-macosx-x86_64/lib/swift/macosx' LD_LIBRARY_PATH='/Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/buildbot_incremental/swift-macosx-x86_64/lib/swift/macosx:' SIMCTL_CHILD_DYLD_LIBRARY_PATH='/Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/buildbot_incremental/swift-macosx-x86_64/lib/swift/macosx'  /Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/Concurrency/Runtime/Output/data_race_detection.swift.tmp/a.out > /Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/Concurrency/Runtime/Output/data_race_detection.swift.tmp.log 2>&1
: 'RUN: at line 2';   /Applications/Xcode-beta.app/Contents/Developer/usr/bin/python3 /Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/swift/utils/PathSanitizingFileCheck --allow-unused-prefixes --sanitize BUILD_DIR=/Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/buildbot_incremental/swift-macosx-x86_64 --sanitize SOURCE_DIR=/Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/swift --use-filecheck /Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/buildbot_incremental/llvm-macosx-x86_64/bin/FileCheck  /Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/swift/test/Concurrency/Runtime/data_race_detection.swift < /Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/Concurrency/Runtime/Output/data_race_detection.swift.tmp.log
--
Exit Code: 1

Command Output (stderr):
--
/Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/swift/test/Concurrency/Runtime/data_race_detection.swift:66:31: warning: non-sendable type '() -> Void' returned by implicitly asynchronous call to actor-isolated instance method 'getTaskOnMyActor()' cannot cross actor boundary
    let actorFn = await actor.getTaskOnMyActor()
                              ^
/Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/swift/test/Concurrency/Runtime/data_race_detection.swift:66:31: note: a function type must be marked '@Sendable' to conform to 'Sendable'
    let actorFn = await actor.getTaskOnMyActor()
                              ^
/Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/swift/test/Concurrency/Runtime/data_race_detection.swift:61:12: error: CHECK: expected string not found in input
 // CHECK: warning: data race detected: @MainActor function at main/data_race_detection.swift:23 was not called on the main thread
           ^
<stdin>:1:1: note: scanning from here
warning: data race detected: @MainActor function at main/data_race_detection.swift:22 was not called on the main thread
^

Input file: <stdin>
Check file: /Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/swift/test/Concurrency/Runtime/data_race_detection.swift

-dump-input=help explains the following input dump.

Input was:
<<<<<<
          1: warning: data race detected: @MainActor function at main/data_race_detection.swift:22 was not called on the main thread 
check:61     X~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ error: no match found
          2: warning: data race detected: actor-isolated function at main/data_race_detection.swift:51 was not called on the same actor 
check:61     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          3: Launching a main-actor task 
check:61     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          4: I'm on the main actor! 
check:61     ~~~~~~~~~~~~~~~~~~~~~~~
          5: Launching an actor-instance task 
check:61     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>>>>>>

--

********************
```

**Pull request closed without merging**
