### PR TITLE
{JSON,Plist}{En,De}coder defer container pops

### PR DESCRIPTION
**Pull request by itaiferber**
**What's in this pull request?**
Resolves #48633 (rdar://problem/34857336) resolves https://github.com/apple/swift-corelibs-foundation/issues/4051 (rdar://problem/36336754), which became more common failures after #13178.

Thanks to @zintus for #12969 — this expands on that and adds unit tests.

### CODE REVIEW

**Comment by itaiferber** [comment]
@swift-ci Please smoke test Linux

**Comment by itaiferber** [comment]
@swift-ci Please test macOS

**Review by phausler — APPROVED** [review]

**Comment by jrose-apple** [comment]
Given the number of reports this may be worth cherry-picking to 4.1 as well.

**Comment by itaiferber** [comment]
@jrose-apple Yep, that's the plan. BTW, looks like unrelated test failure in `IRGen/protocol_resilience_thunks.swift` — someone looking into that, or is this a transient failure?

**Comment by itaiferber** [comment]
@swift-ci Please clean test macOS

**Comment by jrose-apple** [comment]
Looks like a real mistake from someone who forgot we don't have the `swifterror` convention on i386.

**Comment by itaiferber** [comment]
Looks like job #1021 hit this this morning, too: https://ci.swift.org//job/oss-swift-package-osx/1021/consoleFull#-303088932ba62d58e-7248-467b-91e0-c7508d5cf947

**Comment by itaiferber** [comment]
I'm likely going to need to re-run this after #13883 is merged. @shahmishal Is there a way to kill CI jobs so they don't waste needless resources?

**Comment by jrose-apple** [comment]
@swift-ci Please test macOS

**Pull request merged**
