### PR TITLE
[SR-14282] Compiler crash in DictionaryTrapsObjC.swift

### PR DESCRIPTION
**Pull request by benrimmington**
The bug reported in SR-14282 is no longer reproducible.

<rdar://problem/74877200>

### CODE REVIEW

**Comment by benrimmington** [comment]
@swift-ci Please smoke test

**Comment by benrimmington** [comment]
@swift-ci Please smoke test Windows platform

**Comment by benrimmington** [comment]
@swift-ci Please smoke test macOS platform

**Comment by benrimmington** [comment]
@swift-ci Please smoke test macOS platform

**Comment by benrimmington** [comment]
@swift-ci Please smoke test Windows platform

**Comment by benrimmington** [comment]
@swift-ci Please test macOS platform

**Comment by benrimmington** [comment]
```
PASS: Swift(macosx-x86_64) :: stdlib/DictionaryTrapsObjC.swift (879 of 14345)
PASS: Swift(iphonesimulator-x86_64) :: stdlib/DictionaryTrapsObjC.swift (876 of 14345)
PASS: Swift(watchsimulator-i386) :: stdlib/DictionaryTrapsObjC.swift (875 of 14345)

Failed Tests (1):
  Swift(watchsimulator-i386) :: IRGen/async/hop_to_executor.sil
```

**Comment by benrimmington** [comment]
@swift-ci Please smoke test macOS platform

**Review by eeckstein — APPROVED** [review]
lgtm, thanks

**Pull request merged**
