### PR TITLE
Sema: Reject empty switch statements during type checking so that we can issue fixits to fill the unhandled switch cases.

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by slavapestov** [comment]
Could the exhaustiveness check be moved from SIL to Sema so that we can issue fixits with missing cases, not just empty switches?

**Comment by nkcsgexi** [comment]
@slavapestov we do have a fixit for the missing cases in a separate commit (d12d3c18cabea37f0756f88edaa7667bf891e457). Are you thinking about something different?

**Pull request merged**
