### PR TITLE
[lit] Add %utils and %line-directive substitutions. Use %gyb

### PR DESCRIPTION
**Pull request by rintaro**
#### What's in this pull request?

Added:
`%utils` => `${SWIFT_SOURCE_DIR}/utils`
`%line-directive` => `${SWIFT_SOURCE_DIR}/utils/line-directive`

Utilize `%gyb` instead of `%S/../../utils/gyb` or `%S/../../../utils/gyb`

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by rintaro** [comment]
Maybe, we should add `%target-run-simple-gyb` substitution.

**Comment by jrose-apple** [comment]
The `%target-` substitutions are specifically for those where there's a target and/or SDK being passed. Does that apply to any of the gyb invocations?

**Comment by rintaro** [comment]
@jrose-apple `%target-run-simple-gyb` would be substituted to:
```
rm -rf %t && mkdir -p %t && \
%gyb %s -o %t/main.swift && \
%line-directive %t/main.swift -- %target-build-swift %t/main.swift -o %t/a.out && \
%line-directive %t/main.swift -- %target-run %t/a.out
```

**Comment by jrose-apple** [comment]
Ah, got it. Seems reasonable to me, though I think it makes sense to make that a follow-up change.

**Comment by jrose-apple** [comment]
Also, would it make more sense to just add `swift/utils/` to the executable search path? I've argued with @gottesmm before that it makes more sense to use the percent-substitutions for things that don't just correspond to paths, on the grounds that anything that *is* using a substitution is either (a) something you might want to replace, (b) something that's non-obvious to compute, (c) something that's configuration-dependent, or (d) eliminating a lot of boilerplate. This weakly falls under (d), but it's not really anything more than just the executable.

**Comment by rintaro** [comment]
> Also, would it make more sense to just add swift/utils/ to the executable search path?

It makes sense for me.
But, I still want `%utils` substitution..
`%{python} -m unittest discover -s %utils/cmpcodesize`

**Comment by jrose-apple** [comment]
That seems reasonable. Another option would just be to provide a top-level substitution for the swift directory, something like `%swift-source-root` or `%swift-source-dir`. (That roughly matches the name in lit.cfg, `swift_source_root`, or the name in CMake, `SWIFT_SOURCE_DIR`.)

**Comment by gribozavr** [comment]
> Also, would it make more sense to just add swift/utils/ to the executable search path?

I would prefer lit to print shell scripts with full paths so that it is easy to reproduce the test without adjustments to `PATH`.

**Comment by gribozavr** [comment]
> Maybe, we should add `%target-run-simple-gyb` substitution.

It would be great!  We have been actually recently discussing the same with @harlanhaskins and @shahmishal for profile collection.  We were thinking that we would avoid running the compiled binaries during profile collection to make it faster.  Having this substitution would make it simpler to intercept everything.

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by gribozavr** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
@gribozavr Why doesn't that logic apply to every tool we use?

**Comment by gribozavr** [comment]
This?

> I would prefer lit to print shell scripts with full paths so that it is easy to run the test without adjustments to PATH.

I think it totally applies.  We should make it as easy as possible to re-run failed tests.

**Comment by jrose-apple** [comment]
:-/ My argument to @gottesmm has always been that substitutions are more opaque when *reading* the tests. It makes it harder to tell what I need to do to get the same effect on the command line *without* running the test.

**Comment by gribozavr** [comment]
This is an argument against any kind of abstraction in general.

**Comment by jrose-apple** [comment]
It's always a trade-off. If the abstraction isn't buying us much, I'd rather not have an extra layer to think about. (Which is only valid because sometimes I need to look under those layers.)

**Pull request merged**
