### PR TITLE
Taught const expr eval to const-evaluate a struct field as a const value, even if the entire struct itself is not a const.

### PR DESCRIPTION
**Pull request by mhong**
Resolves [SR-8463](https://bugs.swift.org/browse/SR-8463).

### CODE REVIEW

**Comment by mhong** [comment]
@swift-ci please test tensorflow

**Review by rxwei — APPROVED** [review]
Nice!

**Comment by mhong** [comment]
Submitting to unblock Richard's dataset work. Happy to address any additional comments afterwards!

**Comment by lattner** [comment]
This might fix this one specific case, but this is not a general solution.  I don't think this is the right direction to go.

**Comment by mhong** [comment]
Thanks @lattner for the discussion today. Sent out https://github.com/apple/swift/pull/18650 as a follow-up fix.

**Pull request merged**
