### PR TITLE
[Exclusivity] Extend SILVerifier for init_block_storage_header for ex…

### PR DESCRIPTION
**Pull request by devincoughlin**
…clusivity

Extend the SIL verifier to check for the assumptions that the static exclusivity
diagnostics make about conversions from noescape closures to noescape blocks.
Soundness of the static diagnostics requires that the analysis can locally
determine when a noescape closure is converted to a noescape and then
passed to a function.

### CODE REVIEW

**Comment by devincoughlin** [comment]
@swift-ci Please test

**Review by atrick — COMMENTED** [review]
LGTM

**Comment by atrick** [comment]
I'm not sure how the dead_array_elim test could have resulted from this change.

**Comment by gottesmm** [comment]
@atrick I am fixing that currently in #13799

**Comment by gottesmm** [comment]
@swift-ci test os x platform

**Comment by gottesmm** [comment]
@atrick @devincoughlin I restarted the OS X build now that my commit landed.

**Comment by devincoughlin** [comment]
@swift-ci Please smoke test and merge

**Pull request merged**
