### PR TITLE
[Tests] Mark macro test 'REQUIRES: swift_swift_parser'

### PR DESCRIPTION
**Pull request by rintaro**
rdar://116239522

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Review by bnbarham — APPROVED** [review]

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Review by compnerd — APPROVED** [review]

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Review by compnerd — APPROVED** [review]

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Pull request merged**
