### PR TITLE
Begin refactoring type variable binding code.

### PR DESCRIPTION
**Pull request by rudkx**
Move all the code specific to dealing with relational constraints out
into a separate function.

I expect to do more refactoring here so this is likely not the final
form for this code - just one step in the direction of breaking things
down into smaller logical pieces.

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Review by xedin — COMMENTED** [review]
Nice!

**Comment by rudkx** [comment]
Hmm, @vedantk have any ideas on this Linux failure?

```
18:12:15 CMake Error at CMakeLists.txt:87 (message):
18:12:15   LLDB test compilers not specified.  Tests will not run
18:12:15 
18:12:15 
18:12:15 -- Configuring incomplete, errors occurred!
```

**Comment by shahmishal** [comment]
@swift-ci Please clean smoke test

**Comment by rudkx** [comment]
Linux build timeout after 300 minutes

**Comment by rudkx** [comment]
@swift-ci Please clean smoke test Linux platform

**Pull request merged**
