### PR TITLE
swift-module-digester: diagnose type witness type changes when checking ABI stability.

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@DougGregor @rjmccall as we had discussed before, this patch should teach the ABI checker to diagnose any type witness type changes.

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test and merge

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test and merge

**Comment by rjmccall** [comment]
Thanks.  I don't really feel like I understand this code well enough to review it.

**Pull request merged**
