### PR TITLE
build: link unit tests against llvm support library

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

Link the tests against the LLVMSupport library.  This is needed in order to
fix some ilist behaviour changes.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci Please test

**Comment by compnerd** [comment]
CC @chrisbieneman @gottesmm 

Im not sure if there is a nicer way to do this as we can't really use the `LINK_LLVM_COMPONENTS` here.

**Comment by jrose-apple** [comment]
I think that was meant for @llvm-beanz.

**Comment by llvm-beanz** [comment]
This doesn't seem right to me. A few lines above the code you added is a call to swift_common_llvm_config, with support as its argument. Unless I'm missing something that should be covering this case.

**Comment by fjricci** [comment]
Yeah, this patch was written before the addition of the call to swift_common_llvm_config. Looks like it's no longer necessary.

**Pull request closed without merging**
