### PR TITLE
[benchmark] Package.swift: Don’t trap on stray files under single-source/

### PR DESCRIPTION
**Pull request by lorentey**
Make `benchmark/Package.swift` more robust against stray files (such as `.DS_store`) under `benchmark/single-source/` etc.

Currently it traps with an Array index bounds error, leading to a difficult-to-debug build issue.

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci smoke test

**Comment by lorentey** [comment]
@swift-ci benchmark

**Review by gottesmm — APPROVED** [review]
LGTM

**Comment by lorentey** [comment]
@swift-ci test Linux platform

**Comment by lorentey** [comment]
Ah, I missed the failure logs. :-(

@swift-ci please test linux platform

**Comment by lorentey** [comment]
@swift-ci test linux platform

**Comment by lorentey** [comment]
Ah, I finally caught the build failure in time to look at the logs. They're weird:

```
18:38:22 
/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/swift/benchmark/utils/main.swift:17:8: error: no such module 'Ackermann'
18:38:22 import Ackermann
18:38:22        ^
18:38:22 Traceback (most recent call last):
18:38:22   File "/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/swift/benchmark/scripts/build_script_helper.py", line 63, in <module>
18:38:22     main()
18:38:22   File "/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/swift/benchmark/scripts/build_script_helper.py", line 57, in main
18:38:22     perform_build(args, swiftbuild_path, "debug", "Benchmark_Onone", "-Onone")
18:38:22   File "/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/swift/benchmark/scripts/build_script_helper.py", line 39, in perform_build
18:38:22     shutil.copy(binpath, finalpath)
18:38:22   File "/usr/lib/python2.7/shutil.py", line 119, in copy
18:38:22     copyfile(src, dst)
18:38:22   File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
18:38:22     with open(src, 'rb') as fsrc:
18:38:22 IOError: [Errno 2] No such file or directory: '/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/buildbot_linux/benchmarks-linux-x86_64/Benchmark_Onone/debug/SwiftBench'
```

**Comment by lorentey** [comment]
🤦‍♂️

**Comment by lorentey** [comment]
@swift-ci test

**Pull request merged**
