### PR TITLE
[Compile Time Constant Extraction] Add extraction of arrays

### PR DESCRIPTION
**Pull request by jPaolantonio**
Add constant extraction for arrays

### CODE REVIEW

**Comment by jPaolantonio** [comment]
@swift-ci test

**Review by artemcm — APPROVED** [review]

**Comment by jPaolantonio** [comment]
@swift-ci test

**Comment by jPaolantonio** [comment]
@swift-ci test

**Comment by jPaolantonio** [comment]
@swift-ci test

**Pull request merged**
