### PR TITLE
Specify atomicity for compare_exchange_strong

### PR DESCRIPTION
**Pull request by AZero13**
waitQueue only needs to atomically be set to nullptr

### CODE REVIEW

**Comment by RSilicon** [comment]
@al45tair Thoughts?

**Review by al45tair — APPROVED** [review]
LGTM.

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by RSilicon** [comment]
Awesome!

**Comment by al45tair** [comment]
Thank-you for your contribution :-)

**Pull request merged**
