### PR TITLE
stdlib and runtime: a bunch of fixes for AnyHashable and id-as-Any

### PR DESCRIPTION
**Pull request by gribozavr**
This PR is a set of fixes related to `AnyHashable` and id-as-Any work:
- StdlibUnittest: change `Minimal~Class` types to actually be classes (these types were added for testing `AnyHashable`).
- Added tests for `AnyHashable.base`.
- Changed `_SwiftNativeNSError` to use the `Hashable` conformance, if the boxed value conforms to `Hashable`.  (rdar://problem/27574348)
- Changed `SwiftValue` to use the `Hashable` conformance, if the boxed value conforms to `Hashable`.  (rdar://problem/27574348)
- Changed `AnyHashable` to eagerly unbox `SwiftValue`.  Previously `AnyHashable` would consider `SwiftValue` to be a subclass of `NSObject` (which it is in practice) and return `false` when trying to compare an `AnyHashable` of a `SwiftValue` box to an `AnyHashable` of the unboxed value.

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

A smoke test on macOS does the following:
1. Builds the compiler incrementally.
2. Builds the standard library only for macOS. Simulator standard libraries and
   device standard libraries are not built.
3. lldb is not built.
4. The test and validation-test targets are run only for macOS. The optimized
   version of these tests are not run.

A smoke test on Linux does the following:
1. Builds the compiler incrementally.
2. Builds the standard library incrementally.
3. lldb is built incrementally.
4. The swift test and validation-test targets are run. The optimized version of these
   tests are not run.
5. lldb is tested.

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by tkremenek** [comment]
@swift-ci smoke test os x

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by gribozavr** [comment]
@jckarter @slavapestov Would you mind reviewing this PR for `swift-3.0-branch`?  This PR fixes a couple of separate issues, but it builds up infrastructure as it goes, so it is not easy to submit the commits as separate PRs.  I recommend reading the commits individually so that the purpose of each change is clear.

The most important fixes that need review are:

- (b162f60) Changed `_SwiftNativeNSError` to use the `Hashable` conformance, if the boxed value conforms to `Hashable`.  (rdar://problem/27574348)

- (45ab914) Changed `SwiftValue` to use the `Hashable` conformance, if the boxed value conforms to `Hashable`.  (rdar://problem/27574348)

- (f1ec334) Changed `AnyHashable` to eagerly unbox `SwiftValue`.  Previously `AnyHashable` would consider `SwiftValue` to be a subclass of `NSObject` (which it is in practice) and return `false` when trying to compare an `AnyHashable` of a `SwiftValue` box to an `AnyHashable` of the unboxed value.

**Comment by jckarter** [comment]
Looks good, thanks Dmitri!

**Comment by gribozavr** [comment]
@jckarter Thanks for the review!

**Comment by gribozavr** [comment]
Tests pass for me in local testing on Linux.  CI passes for macOS.  Merging.

**Pull request merged**
