### PR TITLE
[WIP] Break loadborrow

### PR DESCRIPTION
**Pull request by atrick**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test linux

**Comment by airspeedswift** [comment]
Switched this to a draft PR since it's WIP

**Comment by atrick** [comment]
This PR exposes `rdar://70403601 (After python upgrade, Ubuntu bot will not print error output: UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 1384: ordinal not in range(128))`

**Comment by atrick** [comment]
@swift-ci test linux

**Comment by atrick** [comment]
@swift-ci smoke test linux

**Comment by atrick** [comment]
The method that I used for generating unicode output when I posted this PR no longer works. But I'm confident this fix is correct, and it will have its own unit test
https://github.com/apple/swift/pull/58420

**Pull request closed without merging**
