### PR TITLE
Swift 4.x (x < 2) names are obsoleted in 4.2, not 5.

### PR DESCRIPTION
**Pull request by tkremenek**
In APINotes, when an unversioned name overrides a previously declared name with a Swift version, if the
previously declared name is guarded under version 4 the obsoleted version should be 4.2, not 5.  In all other cases, the obsoleted version is the next major Swift version.

Fixes rdar://problem/39950937

### CODE REVIEW

**Review by jrose-apple — APPROVED** [review]
Oof, right, that makes sense. Thanks, Ted.

**Comment by jrose-apple** [comment]
I think the else-block should preserve the minor version number iff it's 4.2. Another hardcoding, but it doesn't really make the problem *worse.*

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by tkremenek** [comment]
@jrose-apple Can you confirm my logic for the `else` block is what you wanted?

**Comment by tkremenek** [comment]
@swift-ci smoke test

**Comment by tkremenek** [comment]
@swift-ci smoke test

**Comment by tkremenek** [comment]
@swift-ci smoke test

**Review by jrose-apple — APPROVED** [review]
Yes, this looks fine (as far as hardcoding goes).

**Comment by tkremenek** [comment]
@swift-ci smoke test

**Pull request merged**
