### PR TITLE
Follow-up for fixing IDE/SourceKit tests after changes for [SE-0111]

### PR DESCRIPTION
**Pull request by akyrtzi**
#### What's in this pull request?

Reviewed by Ben Langmuir.

These are changes for fixing fallout on IDE/SourceKit after changes related to [SE-0111].
The changes are intrusive but they fix critical problems, for example failing to show external argument names in code-completion or cursor-info not showing local parameter names in function types.
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

rdar://27642873

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

A smoke test on macOS does the following:
1. Builds the compiler incrementally.
2. Builds the standard library only for macOS. Simulator standard libraries and
   device standard libraries are not built.
3. lldb is not built.
4. The test and validation-test targets are run only for macOS. The optimized
   version of these tests are not run.

A smoke test on Linux does the following:
1. Builds the compiler incrementally.
2. Builds the standard library incrementally.
3. lldb is built incrementally.
4. The swift test and validation-test targets are run. The optimized version of these
   tests are not run.
5. lldb is tested.

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by akyrtzi** [comment]
@swift-ci smoke test OS X platform

**Comment by akyrtzi** [comment]
@swift-ci test OS X platform

**Comment by akyrtzi** [comment]
test/IDE/complete_from_stdlib.swift fails because of a stdlib difference between the branches, will update the test.

**Comment by akyrtzi** [comment]
@swift-ci test OS X platform

**Comment by shahmishal** [comment]
@swift-ci test OS X platform

**Pull request merged**
