### PR TITLE
[AutoDiff] Significantly improve differentiation diagnostics

### PR DESCRIPTION
**Pull request by rxwei**
Revamp error propagation and differentiability diagnostics in the automatic differentiation pass. 

Also:
- Make synthesized primal and adjoint functions have unqualified ownership.

Example:

```swift
func f(_ x: Float) -> Float {
  return #gradient(g)(x)
}

func g(_ x: Float) -> Float {
  return f(y)
}
```

```console
test.swift:2:10: error: function is not differentiable
  return #gradient(g)(x)
         ^         ~
test.swift:6:10: note: expression is not differentiable
  return f(x)
         ^
test.swift:2:10: note: nested differentiation is not supported yet
  return #gradient(g)(x)
         ^
```

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
Merging to unblock progress. I'm happy to address review comments later!

**Review by dan-zheng — COMMENTED** [review]
Nice!

**Pull request merged**
