### PR TITLE
Gardening: Migrate test suite to GH issues p. 17

### PR DESCRIPTION
**Pull request by AnthonyLatsis**

### CODE REVIEW

**Review by xedin — APPROVED** [review]

**Comment by AnthonyLatsis** [comment]
@swift-ci please test

**Comment by AnthonyLatsis** [comment]
@swift-ci please test Windows

**Comment by AnthonyLatsis** [comment]
@swift-ci please clean test Windows

**Comment by AnthonyLatsis** [comment]
@swift-ci please test Windows

**Pull request merged**
