### PR TITLE
[Variadic Generics] type parameter pack syntax change: T... -> each T

### PR DESCRIPTION
**Pull request by sophiapoirier**

### CODE REVIEW

**Comment by sophiapoirier** [comment]
apple/swift-syntax#1384

@swift-ci please smoke test

**Comment by sophiapoirier** [comment]
btw I intend to add more tests cases for the `...` diagnostic and fixits, however since this PR needs to merge this week, I may do that separately.

**Comment by sophiapoirier** [comment]
I just rebased to latest main to absorb and fix one more recent addition of a `T...` syntax test.

**Comment by sophiapoirier** [comment]
https://github.com/apple/swift-syntax/pull/1384

@swift-ci please smoke test Linux

**Review by hborla — APPROVED** [review]
Looks good!

**Pull request merged**
