### PR TITLE
[stdlib] String.UnicodeScalarView: Fix some index validation issues

### PR DESCRIPTION
**Pull request by lorentey**
`String.UnicodeScalarView` currently lacks proper index validation in its `index(after:)` and `index(before:)` methods, leading to out-of-bounds memory accesses when index navigation methods in this view are given invalid indices.

(Also see https://github.com/apple/swift/pull/41598 and https://github.com/apple/swift/pull/41417)

rdar://89498541

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Review by Azoy — APPROVED** [review]
Thank you!

**Comment by lorentey** [comment]
```
[ RUN      ] StringTraps_debug.UnicodeScalarView index(before:) trap on startIndex after scalar alignment
expecting a crash, but the test did not crash
[     FAIL ] StringTraps_debug.UnicodeScalarView index(before:) trap on startIndex after scalar alignment
```

Oops, the tests forgot to call `.unicodeScalars` property, so they're actually exercising `String` itself. Lucky I split these up into separate PRs. 🤦‍♂️

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
Linux failure looks like an infrastructure issue:
```
Cannot contact i-05b7e823f2c5333d4: hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@3b46f0a6:i-05b7e823f2c5333d4": Remote call on i-05b7e823f2c5333d4 failed. The channel is closing down or has closed down
```

**Comment by lorentey** [comment]
@swift-ci test linux platform

**Comment by lorentey** [comment]
Hm, these look unrelated:

```
FAIL: lldb-api :: lang/swift/array_bridged_enum/TestArrayBridgedEnum.py (24 of 383)
******************** TEST 'lldb-api :: lang/swift/array_bridged_enum/TestArrayBridgedEnum.py' FAILED ********************
Script:
--
/usr/local/bin/python3 /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/llvm-project/lldb/test/API/dotest.py -u CXXFLAGS -u CFLAGS --inferior-env DYLD_LIBRARY_PATH="/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/swift-macosx-x86_64/lib/swift/macosx" --inferior-env LD_LIBRARY_PATH="/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/swift-macosx-x86_64/lib/swift/x86_64" --inferior-env SIMCTL_CHILD_DYLD_LIBRARY_PATH="/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/swift-macosx-x86_64/lib/swift/macosx" --out-of-tree-debugserver --build-dir /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/lldb-macosx-x86_64/lldb-test-build.noindex --skip-category=watchpoint --skip-category=dwo --env LLVM_LIBS_DIR=/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/llvm-macosx-x86_64/./lib --arch x86_64 --build-dir /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/lldb-macosx-x86_64/lldb-test-build.noindex --lldb-module-cache-dir /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/lldb-macosx-x86_64/lldb-test-build.noindex/module-cache-lldb/lldb-api --clang-module-cache-dir /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/lldb-macosx-x86_64/lldb-test-build.noindex/module-cache-clang/lldb-api --executable /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/lldb-macosx-x86_64/./bin/lldb --compiler /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/llvm-macosx-x86_64/./bin/clang --swift-compiler /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/swift-macosx-x86_64/bin/swiftc --dsymutil /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/llvm-macosx-x86_64/./bin/dsymutil --llvm-tools-dir /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/llvm-macosx-x86_64/./bin --lldb-libs-dir /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/lldb-macosx-x86_64/./lib --framework /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/lldb-macosx-x86_64/bin/LLDB.framework --skip-category=swiftmaccatalyst --setting symbols.use-swift-clangimporter=false /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/llvm-project/lldb/test/API/lang/swift/array_bridged_enum -p TestArrayBridgedEnum.py
--
Exit Code: 1

Command Output (stdout):
--
lldb version 13.0.0 (https://github.com/apple/llvm-project.git revision e5ccc9e85b9d4c78b27b72d25e4b949c8a5ea20e)
Apple Swift version 5.7-dev (LLVM e5ccc9e85b9d4c7, Swift d53af5ecc8c318d)
Skipping the following test categories: ['frame-diagnose', 'watchpoint', 'dwo', 'swiftmaccatalyst', 'libstdcxx', 'dwo', 'llgs', 'fork']

--
Command Output (stderr):
--
FAIL: LLDB (/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/llvm-macosx-x86_64/bin/clang-x86_64) :: test_dsym (lldbsuite.test.lldbtest.TestArrayBridgedEnum)
PASS: LLDB (/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/llvm-macosx-x86_64/bin/clang-x86_64) :: test_dwarf (lldbsuite.test.lldbtest.TestArrayBridgedEnum)
UNSUPPORTED: LLDB (/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/llvm-macosx-x86_64/bin/clang-x86_64) :: test_dwo (lldbsuite.test.lldbtest.TestArrayBridgedEnum) (test case does not fall in any category of interest for this run) 
UNSUPPORTED: LLDB (/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/llvm-macosx-x86_64/bin/clang-x86_64) :: test_gmodules (lldbsuite.test.lldbtest.TestArrayBridgedEnum) (skipping (gmodules only makes sense for clang tests)) 
======================================================================
ERROR: test_dsym (lldbsuite.test.lldbtest.TestArrayBridgedEnum)
----------------------------------------------------------------------
Error when building test subject.

Build Command:
['make', 'VPATH=/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/llvm-project/lldb/test/API/lang/swift/array_bridged_enum', '-C', '/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/lldb-macosx-x86_64/lldb-test-build.noindex/lang/swift/array_bridged_enum/TestArrayBridgedEnum.test_dsym', '-I', '/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/llvm-project/lldb/test/API/lang/swift/array_bridged_enum', '-I', '/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/llvm-project/lldb/packages/Python/lldbsuite/test/make', '-f', '/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/llvm-project/lldb/test/API/lang/swift/array_bridged_enum/Makefile', 'MAKE_DSYM=YES', 'all', 'ARCH=x86_64', 'CC="/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/llvm-macosx-x86_64/bin/clang"', 'SWIFTC="/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/swift-macosx-x86_64/bin/swiftc"', 'DSYMUTIL=/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/llvm-macosx-x86_64/./bin/dsymutil', 'CODESIGN=codesign', 'CLANG_MODULE_CACHE_DIR=/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/lldb-macosx-x86_64/lldb-test-build.noindex/module-cache-clang/lldb-api']

Build Command Output:
### Precompiling /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/llvm-project/lldb/test/API/lang/swift/array_bridged_enum/bridging-header.h
/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/swift-macosx-x86_64/bin/swift -frontend -emit-pch -g -Onone -serialize-debugging-options -module-cache-path /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/lldb-macosx-x86_64/lldb-test-build.noindex/module-cache-clang/lldb-api -sdk /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk -framework Foundation -framework CoreGraphics -enable-anonymous-context-mangled-names /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/llvm-project/lldb/test/API/lang/swift/array_bridged_enum/bridging-header.h -o /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/lldb-macosx-x86_64/lldb-test-build.noindex/lang/swift/array_bridged_enum/TestArrayBridgedEnum.test_dsym/bridging-header.pch
### Compiling /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/llvm-project/lldb/test/API/lang/swift/array_bridged_enum/main.swift
/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/swift-macosx-x86_64/bin/swift -frontend -c -primary-file /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/llvm-project/lldb/test/API/lang/swift/array_bridged_enum/main.swift \
	   \
	  -g -Onone -serialize-debugging-options -module-cache-path /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/lldb-macosx-x86_64/lldb-test-build.noindex/module-cache-clang/lldb-api -sdk /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk -framework Foundation -framework CoreGraphics -enable-anonymous-context-mangled-names -import-objc-header /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/lldb-macosx-x86_64/lldb-test-build.noindex/lang/swift/array_bridged_enum/TestArrayBridgedEnum.test_dsym/bridging-header.pch  \
	  -module-name a -emit-module-path \
	  /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/lldb-macosx-x86_64/lldb-test-build.noindex/lang/swift/array_bridged_enum/TestArrayBridgedEnum.test_dsym/main.partial.swiftmodule \
	  -o /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/lldb-macosx-x86_64/lldb-test-build.noindex/lang/swift/array_bridged_enum/TestArrayBridgedEnum.test_dsym/main.o
### Merging swift modules for a
/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/swift-macosx-x86_64/bin/swift -frontend -g -Onone -serialize-debugging-options -module-cache-path /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/lldb-macosx-x86_64/lldb-test-build.noindex/module-cache-clang/lldb-api -sdk /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk -framework Foundation -framework CoreGraphics -enable-anonymous-context-mangled-names -import-objc-header /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/lldb-macosx-x86_64/lldb-test-build.noindex/lang/swift/array_bridged_enum/TestArrayBridgedEnum.test_dsym/bridging-header.pch -merge-modules \
	  -emit-module \
	  -emit-module-interface-path /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/lldb-macosx-x86_64/lldb-test-build.noindex/lang/swift/array_bridged_enum/TestArrayBridgedEnum.test_dsym/a.swiftinterface \
	  main.partial.swiftmodule \
	  -disable-diagnostic-passes -disable-sil-perf-optzns \
	  -module-name a \
	  -o /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/lldb-macosx-x86_64/lldb-test-build.noindex/lang/swift/array_bridged_enum/TestArrayBridgedEnum.test_dsym/a.swiftmodule
<unknown>:0: error: module file '/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/lldb-macosx-x86_64/lldb-test-build.noindex/module-cache-clang/lldb-api/33T9XBXHO3JY3/Foundation-26LJKO9TWD70R.pcm' is out of date and needs to be rebuilt: signature mismatch
<unknown>:0: note: imported by '/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/lldb-macosx-x86_64/lldb-test-build.noindex/lang/swift/array_bridged_enum/TestArrayBridgedEnum.test_dsym/bridging-header.pch'
```

**Comment by lorentey** [comment]
@swift-ci test macOS platform

**Comment by lorentey** [comment]
@swift-ci clean test macOS platform

**Pull request merged**
