### PR TITLE
[generic-specializer] Fixes for partial_apply instructions and for specialization of self-recursive functions

### PR DESCRIPTION
**Pull request by swiftix**
Improve handling of self-recursive apply instructions

- re-factor the code so that all kinds of applies can reuse it
- properly handle self-recursive generic functions

Fixes rdar://31899989 and rdar://31886854

### CODE REVIEW

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by swiftix** [comment]
@swift-ci please smoke benchmark

**Comment by swiftix** [comment]
@swift-ci please smoke benchmark

**Comment by swiftix** [comment]
@eeckstein Do you mind taking a look? We may need it for 4.0

**Comment by slavapestov** [comment]
LGTM. Maybe we should push this down into SILCloner?

**Comment by swiftix** [comment]
@slavapestov Yes, it it possible. But TypeSubstCloner has this `Inlining` flag, which is needed by the logic in this PR. We could expose it to the SILCloner as well. Overall, we could move all visit methods from TypeSubstCloner into SILCloner. But I'm not sure that now is the right time to do that ;-)

**Pull request merged**
