### PR TITLE
[Runtime] Validate scribble data when metadata allocation scribbling is enabled.

### PR DESCRIPTION
**Pull request by mikeash**
Instead of scribbling each allocation as it's parceled out, scribble the entire chunk up-front. Then, when handing out an allocation, check to make sure it still has the right scribbled data in it.

### CODE REVIEW

**Comment by mikeash** [comment]
This catches the overflow fixed by https://github.com/apple/swift/pull/34822.

**Review by nate-chandler — APPROVED** [review]

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test os x platform

**Comment by mikeash** [comment]
@swift-ci please test os x platform

**Comment by mikeash** [comment]
@swift-ci please test os x platform

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test os x platform

**Comment by mikeash** [comment]
@swift-ci please test windows platform

**Pull request merged**
