### PR TITLE
[testing] Add missing REQUIRES: standalone_test

### PR DESCRIPTION
**Pull request by davezarzycki**

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test and merge

**Comment by buttaface** [comment]
I see no `standalone_test` defined anywhere, did you mean [`standalone_build`](https://github.com/apple/swift/blob/a313f62522c00e8327084820bd22dc3d2870610e/test/lit.site.cfg.in#L97)?

**Comment by davezarzycki** [comment]
> I see no `standalone_test` defined anywhere, did you mean [`standalone_build`](https://github.com/apple/swift/blob/a313f62522c00e8327084820bd22dc3d2870610e/test/lit.site.cfg.in#L97)?

Whoops. Yes. Sorry!

**Comment by davezarzycki** [comment]
Do you have a pull request ready? Or do you need me to fix it?

**Comment by buttaface** [comment]
Also, since `standalone_build` is defined in `test/lit.site.cfg.in`, will it be passed to these validation tests? Could you explain what this requirement signifies?

**Comment by davezarzycki** [comment]
There are two fundamental ways of building Swift:

1) As a standalone project using pre-built LLVM/clang libraries (and headers) available somewhere.
2) As a "unified build" where LLVM, clang, swift, etc are built together and build dependencies are integrated.

"standalone_build" means the former.

**Comment by buttaface** [comment]
Is the "unified build" ever built on the CI? If not, adding this requirement simply disables all these tests from the CI.

**Comment by davezarzycki** [comment]
As of today, CI doesn't do unified builds.

But that doesn't matter. This test is effectively always disabled when it shouldn't be.

**Comment by buttaface** [comment]
I ask because one of these tests should have tripped because of my pull #32860, but it didn't. I'll fix this, but I'm not sure how if the test is never run even with `standalone_build`.

**Comment by buttaface** [comment]
I'll look into the CMake config for unified builds more and get back to you later. I thought the CI is doing unified builds, based on your description, but I'm not sure so I will check.

Let me know about that `lit.site.cfg.in` issue I mentioned above, whenever you get a chance.

**Comment by davezarzycki** [comment]
CI uses the "build-script" which builds a bunch of projects serially/standalone. This makes it easy to build LLVM+clang optimized but with Swift unoptimized.

People that build "unified" are bypassing the build-script entirely

**Comment by buttaface** [comment]
I neglected to make clear that all the `standalone_build` tests you added appear to be disabled on the CI, not just these two with the wrong label. I downloaded [the full CI log for the last successful smoke test from last night](https://ci.swift.org/job/swift-PR-Linux/22427/consoleText) and checked, hence my confusion and further questions.

It appears there's something further wrong in the test setup than this pull and since you added that requirement, maybe you have some insight.

**Comment by buttaface** [comment]
OK, I think I have a fix for both problems, will submit a pull.

**Pull request merged**
