### PR TITLE
[Sema] Disallow derived conformances in disallowed contexts.

### PR DESCRIPTION
**Pull request by dan-zheng**
Disallow derived conformances in disallowed contexts for:
- `AdditiveArithmetic`
- `VectorNumeric`
- `KeyPathIterable`
- `Differentiable`
- `TensorArrayProtocol`
- `TensorGroup`

This is consistent with existing derived conformances for other protocols.
Remove `-verify-ignore-unknown` from various tests.

### CODE REVIEW

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Review by rxwei — APPROVED** [review]

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow macOS

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow linux GPU

**Pull request merged**
