### PR TITLE
Update ForwardIndexType for removal of ++ operator

### PR DESCRIPTION
**Pull request by nielsandriesse**
Successfully passed `build-script -t`

### CODE REVIEW

**Comment by nielsandriesse** [comment]
SIL is different: https://gist.github.com/nielsandriesse/3391d0fb06c2de6d5ede

**Comment by nielsandriesse** [comment]
Basically the same as _advanceForward(_:)

**Comment by nielsandriesse** [comment]
SIL is identical

**Comment by gribozavr** [comment]
@nielsandriesse Someone else already removed these, sorry!

**Pull request closed without merging**
