### PR TITLE
Eytzingerize word break data

### PR DESCRIPTION
**Pull request by Catfish-Man**
Fixes rdar://123278973

### CODE REVIEW

**Comment by Catfish-Man** [comment]
@swift-ci Please Apple Silicon benchmark

**Comment by Catfish-Man** [comment]
@swift-ci Please Apple Silicon benchmark

**Comment by Catfish-Man** [comment]
@swift-ci Please Apple Silicon benchmark

**Review by Azoy — APPROVED** [review]
LGTM, but I doubt the benchmarks will come up with anything useful because this is only exercised in the regex work.

**Comment by Catfish-Man** [comment]
@swift-ci please benchmark

**Comment by Catfish-Man** [comment]
Results from the new benchmark on my machine:

Before: 
```
  # TEST               SAMPLES      MIN   MEDIAN      MAX
 992 StringIterateWords         1 17802.638 17802.638 17802.638
```

After:
```
  # TEST               SAMPLES      MIN   MEDIAN      MAX
 992 StringIterateWords         1 5473.480 5473.480 5473.480
```

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Comment by Catfish-Man** [comment]
Build failure should be fixed by https://github.com/apple/swift-package-manager/pull/7350

**Comment by Catfish-Man** [comment]
@swift-ci please test macOS platform

**Comment by Catfish-Man** [comment]
@swift-ci please test macOS platform

**Pull request merged**
