### PR TITLE
Update canTriviallyDeleteOSSAEndScopeInst and a related assertion

### PR DESCRIPTION
**Pull request by meg-gupta**
A destroy_value of Optional.none can be deleted.

A move-only struct with deinit has a non trivial SILType but OwnershipKind::None, such values cannot be deleted.

### CODE REVIEW

**Review by nate-chandler — APPROVED** [review]

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Review by atrick — COMMENTED** [review]
I'm not opposed to this fix. I just want to make sure everyone understands that `Ownership.none` can never apply to a struct-with-deinit. `Ownership.none` literally means that the type is trivial on this path. Meaning we know there is no deinit on this path

**Comment by meg-gupta** [comment]
@atrick You are right. My observation was from the earlier @_moveOnly type attribute which used Ownership::None even in the presence of deinit.

**Comment by meg-gupta** [comment]
But we can't assume Ownership::None implies anymore because a ~Copyable struct without deinit has OwnershipKind::None and non-trivial SILType ?

**Comment by atrick** [comment]
> But we can't assume Ownership::None implies anymore because a ~Copyable struct without deinit has OwnershipKind::None and non-trivial SILType ?

I'm not really sure what assumptions are currently being made in move-only passes. I think `Ownership::None` always implies that the value is trivial. Even though its type might conservatively report non-trivial. That's the assumption in all the code I've written.

In my mind, we would like `BitwiseCopyable` implies `SILType.isTrivial` implies `Ownership::None`.  Right @nate-chandler?

**Comment by nate-chandler** [comment]
> we would like BitwiseCopyable implies SILType.isTrivial
That's a goal, yes.

**Comment by meg-gupta** [comment]
> I'm not opposed to this fix. I just want to make sure everyone understands that Ownership.none can never apply to a struct-with-deinit. Ownership.none literally means that the type is trivial on this path. Meaning we know there is no deinit on this path

@atrick I created https://github.com/apple/swift/pull/72160 to show we can have Ownership.none for a non-copyable struct.

**Pull request merged**
