### PR TITLE
[stdlib] Finish expunging atomic ops from ABI

### PR DESCRIPTION
**Pull request by milseman**

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please benchmark

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@airspeedswift only if we're also going to take this for 5.0

**Comment by harlanhaskins** [comment]
😅 SwiftSyntax uses `_stdlib_atomicLoadARCRef` and `_stdlib_atomicInitializeARCRef`...

https://github.com/apple/swift-syntax/blob/master/Sources/SwiftSyntax/AtomicCache.swift

**Comment by milseman** [comment]
Not gonna make 5.0

**Pull request closed without merging**
