### PR TITLE
[🍒5.10] utils: enable curl websockets support when building with `build.ps1`

### PR DESCRIPTION
**Pull request by lxbndr**
Cherry-pick of #73378

### CODE REVIEW

**Comment by lxbndr** [comment]
cc @compnerd

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @shahmishal @DougGregor @airspeedswift

**Review by compnerd — APPROVED** [review]

**Comment by compnerd** [comment]
**Explanation**: Enable the WebSocket backend in CURL for allowing use of WebSockets through Foundation.
**Scope**: This enables WebSocket support in CURL which is required for Foundation's WebSocket support to be enabled.
**Issue**: 
**Risk:** Very low - either curl builds with the websocket support or fails to build in CI
**Testing**: CI run
**Reviewer**: @compnerd

**Review by airspeedswift — APPROVED** [review]

**Pull request merged**
