### PR TITLE
Fix usage of uninitialized memory in swift_addNewDSOImage.

### PR DESCRIPTION
**Pull request by pschuh**
This should address https://bugs.swift.org/browse/SR-6848.

Couldn't transform the unsafeGet to get() because it would produce an infinite loop due to the fact that this gets called in the constructor. All non-reentrant versions will continue to use the safe version.

### CODE REVIEW

**Comment by pschuh** [comment]
@swift-ci please test

**Comment by pschuh** [comment]
@swift-ci please test linux

**Comment by pschuh** [comment]
@swift-ci please test macos

**Review by DougGregor — APPROVED** [review]
This looks fine to me, thanks!

**Comment by DougGregor** [comment]
@mikeash this make sense to you as well?

**Comment by DougGregor** [comment]
@pschuh sorry for the delay. I got buried in mentions while on vacation and am digging out

**Comment by mikeash** [comment]
Looks good to me!

**Comment by pschuh** [comment]
@swift-ci please test

**Pull request merged**
