### PR TITLE
[Profiler] Increment closure body count prior to the prolog

### PR DESCRIPTION
**Pull request by vedantk**
This fixes a 'SILBuilder has no valid insertion point' assertion failure
seen when compiling various projects from the source compat suite.

rdar://68759819

### CODE REVIEW

**Comment by vedantk** [comment]
@swift-ci Please Test Source Compatibility Debug

**Comment by vedantk** [comment]
@swift-ci smoke test

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Review by eeckstein — APPROVED** [review]

**Comment by xedin** [comment]
Looks like the changes didn’t fix the problem and release version is failing too now, I am going to merge my xfails to unblock CI while this is being investigated.

**Comment by vedantk** [comment]
It looks like there's more than one bug uncovered by Erik's assert. I'll merge this first fix now and investigate the second failure.

**Pull request merged**
