### PR TITLE
SourceKit: Fix cmake for ASAN builds on macos.

### PR DESCRIPTION
**Pull request by ematejska**
Merge #6687 to the 3.1 branch.
rdar://problem/29996274

### CODE REVIEW

**Comment by ematejska** [comment]
@swift-ci test

**Comment by ematejska** [comment]
@swift-ci please test os x

**Comment by erg** [comment]
@swift-ci Please smoke test OS X platform

**Comment by erg** [comment]
LGTM.

**Review by erg — APPROVED** [review]

**Comment by ematejska** [comment]
@swift-ci test os x

**Comment by ematejska** [comment]
@swift-ci test

**Comment by tkremenek** [comment]
@swift-ci test

**Pull request merged**
