### PR TITLE
CSGen: Infer generic arguments in typed placeholders

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
To be rebased on #33663, only the last 2 commits are relevant.

### CODE REVIEW

**Comment by slavapestov** [comment]
I'm going to punt reviewing this and ask @hborla or @xedin to take a look instead.

**Review by xedin — APPROVED** [review]
Nice simplification, thank you, @AnthonyLatsis!

**Comment by xedin** [comment]
@AnthonyLatsis Looks like you need to manually rebase...

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test Windows

**Pull request merged**
