### PR TITLE
[Build] Move the `.cfg` file generation to a new product.

### PR DESCRIPTION
**Pull request by al45tair**
We need to move the `.cfg` file generation to a new product so that we can land it in the default toolchain for Xcode.

rdar://128612098

### CODE REVIEW

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Review by edymtt — APPROVED** [review]

**Pull request merged**
