### PR TITLE
[Overlay/Dispatch]: Change DispatchQueue.setSpecific to take an optional

### PR DESCRIPTION
**Pull request by karwa**
Mirrors https://github.com/apple/swift-corelibs-libdispatch/pull/172

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by moiseev** [comment]
@swift-ci Please smoke test macOS platform

**Comment by slavapestov** [comment]
@moiseev Is this ready to merge?

**Comment by moiseev** [comment]
@slavapestov I pinged Matt from the Dispatch team over email.

**Review by mwwa — APPROVED** [review]

**Pull request merged**
