### PR TITLE
[cxx-interop] Add a test for instantiation of a default destructor

### PR DESCRIPTION
**Pull request by egorzhdan**
This is a follow-up to f56fa41.

rdar://124061505

### CODE REVIEW

**Comment by egorzhdan** [comment]
@swift-ci please test

**Comment by egorzhdan** [comment]
@swift-ci please test

**Review by Xazax-hun — APPROVED** [review]
LGTM!

**Comment by egorzhdan** [comment]
@swift-ci please test

**Comment by egorzhdan** [comment]
@swift-ci please test

**Comment by egorzhdan** [comment]
@swift-ci please test

**Pull request merged**
