### PR TITLE
Fix prespecialization for long-term maintainability and planned pipeline changes

### PR DESCRIPTION
**Pull request by atrick**
- Only check ABI when building the .dylib
- Disable-access-control
- Rewrite SwiftOnoneSupport.swift, remove the old implementation, create a new framework to handle all function signatures, add the missing symbols, make the specializations obvious and explicit.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci test

**Comment by slavapestov** [comment]
These internal symbols are all @usableFromInline right?

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@slavapestov TL;DR Yes, I assume they are all `@usableFromInline`.

Once it comes time so specialize an individual function, the specialization pass ultimately works the same way as it did before and after @eeckstein added the `@_semantics("prespecialize` feature. My patch just uses that attribute for internal symbols as well. So that the specialization is guaranteed to occur. But, either way, the generic code needs to be deserialized from `Swift.swiftmodule`. That can only happen if it is `@inlinable`. If you use the prespecialize attribute for a symbol that's not `@inlinable` then the specialization must fail because there's nothing to deserialize. Presumably, all types referenced from the `@inlinable` function are `@usableFromInline`.

**Comment by atrick** [comment]
With `-sil-verify-all` we hit an assert when generating SwiftOnone.swiftmodule for some reason.

SIL verification failed: external declarations of SILFunctions with shared visibility is not allowed: SingleFunction || !hasSharedVisibility(RefF->getLinkage()) || RefF->hasForeignBody()

function_ref closure #1 in MutableCollection<>.sort(by:)

**Review by eeckstein — APPROVED** [review]
Thanks for fixing this, LGTM!

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci smoke test and merge

**Comment by atrick** [comment]
@swift-ci smoke test and merge

**Pull request merged**
