### PR TITLE
[5.3] [SE-0286] Trailing closure forward scan

### PR DESCRIPTION
**Pull request by DougGregor**
Implementation of SE-0286 with the dual-scan source-compatibility trick and biasing toward maintaining existing behavior with the backward scan.

Implements rdar://problem/65615074

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
```
fatal: the remote end hung up unexpectedly
```

restarting some builds

**Comment by DougGregor** [comment]
@swift-ci please test macOS

**Comment by DougGregor** [comment]
```
/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-release/5.3/swiftpm/Tests/FunctionalTests/MiscellaneousTests.swift:230: error: -[FunctionalTests.MiscellaneousTestCase testSwiftTestParallel] : XCTAssertTrue failed
```

I'm certain I didn't break that. Try #3.

**Comment by DougGregor** [comment]
@swift-ci please test macOS

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility Release

**Comment by DougGregor** [comment]
```
error: index-pack died of signal 15
fatal: index-pack failed
```

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility Release

**Comment by DougGregor** [comment]
Jenkins error. Sigh.

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility Release

**Review by tkremenek — APPROVED** [review]

**Pull request merged**
