### PR TITLE
build-script / lldb: rename SWIFTCC -> SWIFTC

### PR DESCRIPTION
**Pull request by adrian-prantl**

### CODE REVIEW

**Comment by adrian-prantl** [comment]
https://github.com/apple/swift-lldb/pull/441
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci smoke test

**Comment by adrian-prantl** [comment]
https://github.com/apple/swift-lldb/pull/441
@swift-ci test

**Comment by shahmishal** [comment]
This failure for macOS is currently in master, its not related to this PR. 

https://ci.swift.org/job/oss-swift-pr-test/1685/testReport/

```

Swift(iphonesimulator-i386).DebugInfo.DumpDeclFromMangledName.swift 
Swift(iphonesimulator-i386).IRGen.property_descriptor.sil

``

**Pull request merged**
