### PR TITLE
Disable ExistentialSpecializer on generic functions.

### PR DESCRIPTION
**Pull request by atrick**
This is not implemented--we don't substitute the original archetypes
properly or even create a well-formed generic signature.

It doesn't make sense to me for the ExistentialSpecializer to work on
a generic before it has been fully specialized anyway. The premise of
this pass is that the generic specializer will be able to fully
specialize after generating a new "temporary" generic parameter.

Fixes rdar://56923071; [SR-11714]: Compiler crash when generic class is passed as
a parameter to a function accepting a generic class

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci benchmark

**Comment by slavapestov** [comment]
I don't see any reason why it couldn't be made to work in theory. You can imagine a generic function taking an existential argument, which gets converted into a new function taking an extra argument, which is then all specialized away.

**Comment by atrick** [comment]
@slavapestov 1. Of course it could be made to work, but we need a zero-risk fix for the current release. 2. Even if it could work, why would we want to speculatively convert an existential to a generic argument without knowing whether the function can be specialized? The goal of this pass is to first try to prove that full generic specialization is possible before creating any new generic args--it's not supposed to be speculative.

**Comment by atrick** [comment]
None of these benchmarks have anything to do with ExistentialSpecializer, so I don't know why the results are so flaky.

**Comment by slavapestov** [comment]
@atrick Passing an existential as a generic argument can still avoid some boxing overhead even if it won't be fully specialized later, no?

**Comment by atrick** [comment]
@slavapestov you're just arguing that we have the wrong ABI. This pass does not try to determine whether boxing overhead needs to be eliminated. It just tries to determine whether the existential argument can be converted to a concrete type. We could talk endlessly about hypothetical optimizations.

**Comment by atrick** [comment]
@slavapestov of course, you're free to file feature requests for new optimizations justifying why they're important!

**Review by nate-chandler — APPROVED** [review]
LGTM

**Pull request merged**
