### PR TITLE
[windows] Use the monorepo in the Windows build script for CI.

### PR DESCRIPTION
**Pull request by drodriguez**
Clone the monorepo, in the swift/master branch (since that seems to be
the one used by swift master branch), and create links for the different
parts of the LLVM project in the first level.

### CODE REVIEW

**Comment by drodriguez** [comment]
Checking if this works in the CI machines.

@swift-ci please test Windows platform

**Comment by drodriguez** [comment]
@swift-ci please test Windows platform

**Comment by drodriguez** [comment]
https://ci-external.swift.org/job/swift-PR-windows/139/ doesn't seem to have reported back here, but it failed during testing with `WindowsError: [Error 87] The parameter is incorrect`, which has been happening for the last couple of days and I am trying to figure out.

We should merge this as soon as possible to avoid using old checkouts.

@swift-ci please smoke test

**Review by compnerd — APPROVED** [review]
Sure, this at least migrates the CI to the new checkouts; Im looking into updating the instructions with the move.

**Pull request merged**
