### PR TITLE
build: enable macros during the build

### PR DESCRIPTION
**Pull request by compnerd**
Use WiX to extract a future toolchain to allow building the macros support when building the toolchain. We build swift-syntax and now wire that into the build itself.

### CODE REVIEW

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/246

@swift-ci please build toolchain Windows platform

**Comment by shahmishal** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/246

@swift-ci please build toolchain Windows platform

**Comment by shahmishal** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/246

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/246

@swift-ci please smoke test

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/246

@swift-ci please build toolchain windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/246

@swift-ci please build toolchain windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/246

@swift-ci please build toolchain windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/246

@swift-ci please build toolchain windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/246

@swift-ci please build toolchain windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/246

@swift-ci please build toolchain windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/246

@swift-ci please build toolchain windows platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
This work is now complete and merged in different PRs.

**Pull request closed without merging**
