### PR TITLE
Handle end_lifetime in SILInstruction::mayRelease

### PR DESCRIPTION
**Pull request by meg-gupta**

### CODE REVIEW

**Comment by meg-gupta** [comment]
Just hit a case where marking `end_lifetime` as not releasing, causes other issues in the verifier. Going to add a test and update.

**Comment by atrick** [comment]
Why is end_lifetime mayRelease? Just to avoid hoisting it above a use? If so, can you add that comment?

**Comment by meg-gupta** [comment]
> Just hit a case where marking `end_lifetime` as not releasing, causes other issues in the verifier. Going to add a test and update.

False alarm. This was a different issue.

@atrick Marking `end_lifetime` as `false` for `mayRelease` in the PR. (My previous comment is due to another issue with `end_lifetime`)

**Comment by meg-gupta** [comment]
@swift-ci test source compatibility

**Review by atrick — APPROVED** [review]
In that case, lgtm

**Pull request merged**
