### PR TITLE
[test] UnXFAILing and fixing SILOptimizer/eager_specialize.sil test

### PR DESCRIPTION
**Pull request by moiseev**

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Review by swiftix — APPROVED** [review]
LGTM! Thanks!

**Comment by moiseev** [comment]
The failure seems unrelated.
@swift-ci Please smoke test Linux platform

**Comment by swiftix** [comment]
@swift-ci Please smoke test Linux platform

**Pull request merged**
