### PR TITLE
Runtime: Handle universal bridging of class metatypes.

### PR DESCRIPTION
**Pull request by jckarter**
Class metatypes bridge to their `Class` objects in Objective-C.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Comment by jckarter** [comment]
@rjmccall Do you mind reviewing this?

**Comment by jckarter** [comment]
@shahmishal @gottesmm Is something wrong with the build script on Linux? Looks like a missing space in this command:

```
/tmp/hudson3646998341223527104.sh: line 32: /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/swift/utils/build-script--preset=buildbot_linux_1404: No such file or directory
```

**Comment by jckarter** [comment]
@swift-ci Please smoke test OS X

**Comment by rjmccall** [comment]
Seems good to me.

**Pull request merged**
