### PR TITLE
tests: replace 'rm -rf ... && mkdir -p ...' with a new substitution %empty-directory

### PR DESCRIPTION
**Pull request by gribozavr**
Replace various `rm -rf && mkdir` patterns we have in our tests with a new substitution `%empty-directory(directory-name)`.

### CODE REVIEW

**Comment by gribozavr** [comment]
@swift-ci Please smoke test

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by gribozavr** [comment]
@jrose-apple Would you mind reviewing?  (Not asking to look at the mechanical changes, but at the concept and whether it is a good thing to do.)

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by gottesmm** [comment]
I have a couple of thoughts.

1. We should change %t to %workspace, and perhaps while you are looking at this also change %s to %source_file, %S to %source_file_dir. This would help overall clarity. I am fine with this in a subsequent commit.

2. I dislike that %empty-directory does not have an action word in it. I would prefer something like: %ensure-empty-directory(). It does bug me a little bit that there is not a version of this with an implicit %workspace. Maybe: %ensure-empty-workspace-directory()? IIRC people use this solely with %t. It is weird that the API would not just assume a %t prefix.

In general I applaud this effort to try and make this code clearer at the "call site". In general people do not change these that often (and additionally tend to copy/paste the lines, or copy a test and change the body but leave the lit line alone), so it makes sense to optimize for readability over conciseness.

**Comment by jrose-apple** [comment]
-1 on this whole thing. The more substitutions we use, the more lit turns into "magic new language to learn" instead of "basically a shell".

**Comment by gribozavr** [comment]
> The more substitutions we use, the more lit turns into "magic new language to learn" instead of "basically a shell".

You're saying it as if it was a bad thing.  If we can add more substitutions to allow expressing commonly used patterns in a non-error-prone way, I only see it as a plus.  Could you explain your perspective?

**Comment by jrose-apple** [comment]
I like that lit tests are basically shell tests because it means newcomers can generally write them. That's less and less true for the actual compiler invocations at this point, and I think that's pretty unfortunate. Even within the team we're cargo-culting from existing tests instead of writing invocations from scratch, which leads to it being hard to tell which parts of an invocation are actually related to the test.

**Comment by gribozavr** [comment]
> Even within the team we're cargo-culting from existing tests instead of writing invocations from scratch, which leads to it being hard to tell which parts of an invocation are actually related to the test.

I think that is a sign that shell scripts are becoming too long and complex, and that people don't understand the reasons behind writing what is written in them.  There are too many details to worry about that are not relevant to the test (the temporary directory has to exist, the temporary files from the previous run need to be removed, the module cache should be in a certain place and not the system-wide one, the module cache should be shared between tests or the tests will be slow, full paths should be removed from the FileCheck input etc.) -- but those details are important for having a non-fragile testsuite, and we can't afford having each test separately take care of them, that's just too error-prone.

Things like `%target-run-simple-swift`, `%target-run-simple-swiftgyb` and `%target-parse-verify-swift` have been working really well I think, and I would like to see more of that actually.

**Comment by jrose-apple** [comment]
I'd rather that be environmental setup than invocations, though. Rather than remember which of `%empty-directory`, `%target-build-xyz-overlays`, etc. needs to go at the top of each test, lit should just *do* it. Why wouldn't we always have a fresh `%t` for every test at this point?

**Comment by gribozavr** [comment]
> Why wouldn't we always have a fresh `%t` for every test at this point?

I would not be opposed to it, but it would probably require a core lit change, or writing a custom test format for lit.

@ddunbar ?

**Comment by ddunbar** [comment]
I think this should be fixed in lit, this behavior was a bad choice I think.

**Comment by gribozavr** [comment]
> Why wouldn't we always have a fresh %t for every test at this point?

But something to keep in mind is that this wasn't the motivation for this change.  The motivation was to force our tests to always use `mkdir -p`, and to always empty the directory.  We are working on distributing test runs across machines, and in that setup remote machines don't have the full tree of temporary directories created by lit (because lit is not run on the remote machines at all).

**Comment by gribozavr** [comment]
> I think this should be fixed in lit, this behavior was a bad choice I think.

Something to keep in mind is that making this change will require a lot of test changes, because many tests use `%t.something` as their temporary file name.

**Comment by jrose-apple** [comment]
I don't think tests are required to use `%t` as an empty directory, but the bigger issue would be if they use `%t` as a *file.* As long as they're not doing that, it's fine if they use `%t.something` for some other purpose, no?

**Comment by gribozavr** [comment]
The issue would be that people would assume that all temporary content is cleared at the beginning of the test run, but that won't be true.  I think the best solution is to remove the parent directory of `%t` at the beginning of each test run.

**Comment by jrose-apple** [comment]
That's a *little* unfortunate because it would include output from other tests that may *not* be run in this invocation, but maybe it's okay. We could also remove anything with a *prefix* of `%t` rather than exactly matching it.

**Comment by slavapestov** [comment]
Do we still want this?

**Comment by jrose-apple** [comment]
I'm not sure who took over the task of experimenting with distributed tests, but they probably have the strongest opinions. @shahmishal, @erg?

I'm still against piles of substitutions, but @gribozavr made a good point that *without* them we just end up with long, arcane command lines with easy-to-forget pieces, and that the "all-in-one" substitutions have been really effective. I still think *this* problem is something that makes sense to solve environmentally, though.

**Comment by modocache** [comment]
+1, I think this is an improvement. I'd be in favor of merging it today, if the conflicts were resolved.

Even better, but in the longer term, would be either:

1. Adding another substitution to core lit, like `%{tempdir}`, then migrating LLVM/Clang/Swift over to it piecemeal, then removing `%t`.
2. Adding another substitution to core lit, like `%{tempdir}`, and having both available to users.

I prefer option (1). I'd work on it, but I probably won't have time to do so until April or so.

**Comment by erg** [comment]
@lplarson

**Comment by atrick** [comment]
@jrose-apple I'd be fine with a pile of substitutions if they were discoverable:
lit --show-substitutions
%key% = "string"

**Comment by modocache** [comment]
You'd need to pass the path to a valid `lit.cfg` in order to see all the substitutions, which is a little tricky with Swift and LLVM sometimes. But even without a config, `lit --show-substitutions` could list the built-in substitutions, like `%t`. Haivng an option like that seems like a good idea.

**Comment by lplarson** [comment]
+1 from me.

**Comment by jrose-apple** [comment]
Okay, I've been outvoted. I'll rebase and merge soon.

**Comment by CodaFi** [comment]
Resolved by  #10056

**Comment by jrose-apple** [comment]
Thanks for picking this up again, Robert.

**Pull request closed without merging**
