### PR TITLE
[upstream-update] driver: adapt to the new cl API

### PR DESCRIPTION
**Pull request by compnerd**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

This was changed in the LLVM SVN r274171.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci Please test

**Comment by compnerd** [comment]
CC @gottesmm @vedantk

**Comment by vedantk** [comment]
Are the required changes in llvm/stable-next? The build is failing with:
swift/tools/driver/api_notes.cpp:63:37: error: no member named 'TopLevelSubCommand' in namespace 'llvm::cl'

**Comment by vedantk** [comment]
@swift-ci Please smoke test Linux platform

**Comment by compnerd** [comment]
@vedantk hmm, no, its possible they arent in stable-next.  When they make their way over, this will become relevant.

**Comment by gottesmm** [comment]
I need to pull in some more commits, so I am doing another update. I will try this again there.

**Comment by gottesmm** [comment]
I just did the update. Lets see what the public master-next bots think:

https://ci.swift.org/view/swift-master-next/

**Comment by gottesmm** [comment]
I just hit this with my local build. Lets see...

@swift-ci Please test Mac OS Platform

**Comment by gottesmm** [comment]
@swift-ci Please test OS X platform

**Comment by gottesmm** [comment]
We also hit this on the master-next bots:

https://ci.swift.org/view/swift-master-next/job/oss-swift-incremental-RA-osx-master-next/2/console

**Comment by gottesmm** [comment]
This looks good. The builder got past it now. Now we are hitting a different unrelated error.

**Comment by gottesmm** [comment]
@compnerd In a subsequent commit, can you add back the braces around the for/if. Makes it easier to read IMHO.

**Pull request merged**
