### PR TITLE
Revert "Remove the CoreImage overlay as none of the things it contains are marked public"

### PR DESCRIPTION
**Pull request by lancep**
Reverts apple/swift#19745

### CODE REVIEW

**Comment by lancep** [comment]
@swift-ci please smoke test and merge

**Comment by slavapestov** [comment]
Why?

**Comment by lancep** [comment]
We suspect this might be the cause of some linker failures in CI. Reverting to test the theory

**Comment by lancep** [comment]
@swift-ci please smoke test

**Pull request merged**
