### PR TITLE
[CodeCompletion] Migrate some tests to batch completion test #2

### PR DESCRIPTION
**Pull request by rintaro**
```
23.50s: Swift(macosx-x86_64) :: IDE/complete_override.swift
22.69s: Swift(macosx-x86_64) :: IDE/complete_accessor.swift
22.64s: Swift(macosx-x86_64) :: IDE/complete_at_top_level.swift
21.07s: Swift(macosx-x86_64) :: IDE/complete_stmt_controlling_expr.swift
18.84s: Swift(macosx-x86_64) :: IDE/complete_in_accessors.swift
15.85s: Swift(macosx-x86_64) :: IDE/complete_after_super.swift
```
to
```
1.23s: Swift(macosx-x86_64) :: IDE/complete_at_top_level.swift
1.13s: Swift(macosx-x86_64) :: IDE/complete_stmt_controlling_expr.swift
1.10s: Swift(macosx-x86_64) :: IDE/complete_in_accessors.swift
1.01s: Swift(macosx-x86_64) :: IDE/complete_override.swift
0.73s: Swift(macosx-x86_64) :: IDE/complete_accessor.swift
0.64s: Swift(macosx-x86_64) :: IDE/complete_after_super.swift
```

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Review by bnbarham — APPROVED** [review]
Looks good. I really like that the new way makes it harder to have tests that don't actually test anything 😆.

**Comment by rintaro** [comment]
Windows failures are unrelated and this PR is test only changes. Merging.

**Comment by rintaro** [comment]
@swift-ci Please smoke test macOS

**Comment by rintaro** [comment]
Windows failures are unrelated. Merging

**Pull request merged**
