### PR TITLE
[build-script] Install SwiftSyntax to usr/lib instead of usr/lib/swift

### PR DESCRIPTION
**Pull request by ahoppen**
SwiftSyntax in the toolchain is only needed to run the stress tester executable. If a third-party library wants to use it, they are supposed to depend on the SwiftPM package.

As such, SwiftSyntax should not be installed in `usr/lib/swift` where the standard library lives. This PR changes the install location of SwiftSyntax to be `usr/lib`.

This also removes the code to install SwiftSyntax's `.swiftmodule` and `.swiftdoc` file since that code path was never exercised.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please build toolchain

**Comment by akyrtzi** [comment]
Is `@swift-ci Please build toolchain` running the package integration tests? (to ensure the stress-tester is working fine).

**Comment by ahoppen** [comment]
Verified that the stress tester still runs in the new toolchain and that libSwiftSyntax now lives in /usr/lib

Fixed some Python Lint errors, re-running CI to pick them up.

@swift-ci Please smoke test

**Review by akyrtzi — APPROVED** [review]

**Review by beccadax — APPROVED** [review]
Thank you!

**Comment by compnerd** [comment]
@swift-ci please smoke test macOS platform

**Comment by ahoppen** [comment]
Oh, forgot about this one. 

@swift-ci Please smoke test and merge

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by compnerd** [comment]
@ahoppen seems that it has passed, I'll go ahead and merge :)

**Comment by ahoppen** [comment]
@compnerd Thanks!

**Pull request merged**
