### PR TITLE
LifetimeDependence: handle dependent values in throwing calls.

### PR DESCRIPTION
**Pull request by atrick**
Fixes rdar://125564278 (~Escapable: crash in LifetimeDependenceInsertion)

And make drop_deinit a ForwardingInstruction.
Fixes rdar://125590074 ([NonescapableTypes] Nonescapable types cannot have deinits)

### CODE REVIEW

**Review by meg-gupta — APPROVED** [review]
LGTM

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci benchmark

**Pull request merged**
