### PR TITLE
[cxx-interop][SwiftCompilerSources] Use C++ enums directly from Swift

### PR DESCRIPTION
**Pull request by egorzhdan**
rdar://83361087

### CODE REVIEW

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test macOS

**Comment by egorzhdan** [comment]
@swift-ci please smoke test Linux

**Review by eeckstein — APPROVED** [review]
lgtm!

**Comment by egorzhdan** [comment]
@swift-ci please smoke test macOS

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by plotfi** [comment]
@egorzhdan  Is there more context on this PR that can be copied from the Radar? I'd like to better know how this changes how enums might be affected specifically when it comes to NS_OPTIONS.

**Comment by egorzhdan** [comment]
@plotfi sorry for the delay! The radar is just tracking replacement of bridged C types (such as `BridgedAccessKind`) with direct usages of C++ types in SwiftCompilerSources. This change only touches the implementation of SwiftCompilerSources, it doesn't have any visible effect on the compiler.

**Comment by plotfi** [comment]
Thank you @egorzhdan

**Pull request merged**
