### PR TITLE
[TBDGen] update header includes for TextAPI move, NFC

### PR DESCRIPTION
**Pull request by cyndyishida**

### CODE REVIEW

**Comment by cyndyishida** [comment]
Waiting to test this until https://reviews.llvm.org/D99811 moves into apple/llvm-project

**Comment by cyndyishida** [comment]
@swift-ci Please smoke test macos

**Comment by cyndyishida** [comment]
@swift-ci Please smoke test

**Comment by shahmishal** [comment]
@swift-ci Please smoke test

**Comment by cyndyishida** [comment]
the test failures look unrelated 

```12:33:45 In file included from /Users/buildnode/jenkins/workspace/swift-PR-macos-smoke-test/branch-next/swift/lib/ClangImporter/ImportDecl.cpp:18:
12:33:45 
/Users/buildnode/jenkins/workspace/swift-PR-macos-smoke-test/branch-next/swift/lib/ClangImporter/ImporterImpl.h:1576:48: error: unknown type name 'ModuleFileExtensionKind'; did you mean 'ModuleFileExtension'?
12:33:45         clang::ModuleFileExtension(static_cast<ModuleFileExtensionKind>(42)),
12:33:45                                                ^~~~~~~~~~~~~~~~~~~~~~~
12:33:45                                                ModuleFileExtension
```

**Pull request merged**
