### PR TITLE
Add several argument flags to split-cmdline

### PR DESCRIPTION
**Pull request by j-hui**
I noticed split-cmdline was missing several flags from its hard-coded list of flags that expect an argument, which I've added in this commit. These are all Swift compiler flags being generated by Xcode and SwiftPM.

### CODE REVIEW

**Review by eeckstein — APPROVED** [review]
lgtm, thanks!

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by j-hui** [comment]
@swift-ci Please smoke test

**Comment by j-hui** [comment]
@eeckstein I added the arguments scraped from `--help` as we discussed offline, and added a comment documenting how I did that so it can be updated in the future.

It's in a separate commit but I can squash these two when I merge. I've also rebased onto `main` so that the smoke test will pass.

**Comment by j-hui** [comment]
@swift-ci Please smoke test

**Pull request merged**
