### PR TITLE
CapturePromotion: Fix promotion of resilient but locally non-resilient types

### PR DESCRIPTION
**Pull request by aschwaighofer**
Pass the resilience expansion to the cloner so that it can correctly (in
agreement with the caller) decide whether something is address only.

rdar://52263202

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@slavapestov What happen here is that when we decide whether we can optimize a closure function we used the resilience expansion of the function that performs the partial_apply of said closure (which is correct IMO since anything we do with the optimized closure is "local" to that function).
But when we build the new closure that replaces the old closure the code used the minimal expansion. The two can mismatch and boom.
This fix passes the resilience expansion down to the code that builds the new closure.

**Review by slavapestov — COMMENTED** [review]
Can you add a Swift test case, or change the SIL test case to define a [serializable] and non-serializable function so that it actually demonstrates different resilience expansions?

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Pull request merged**
