### PR TITLE
libSyntax: avoid heap-allocated memory for syntax parsing context. NFC

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test and merge

**Comment by shahmishal** [comment]
@nkcsgexi ci.swift.org is down for update, I will re-trigger this PR once update has been completed.

**Comment by nkcsgexi** [comment]
@shahmishal thank you for the update!

**Comment by shahmishal** [comment]
@swift-ci please smoke test and merge

**Comment by shahmishal** [comment]
Re-started the jobs, Swift CI update completed.

**Comment by nkcsgexi** [comment]
We need to squash here. @swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Pull request merged**
