### PR TITLE
[Document] fix typo, iff to if

### PR DESCRIPTION
**Pull request by takecian**
#### What's in this pull request?

Fix typo in comments.

#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI </summary>

The swift-ci is triggered by writing a comment on this PR addressed to the github user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by damuellen** [comment]
This is not a typo, but rather an abbreviation for 'if and only if'.

**Comment by takecian** [comment]
oh ok..

**Comment by practicalswift** [comment]
@damuellen Correct! :laughing:

**Comment by tkremenek** [comment]
Since there was confusion on what "iff" meant, perhaps we should just expand that out to "if and only if" and see if it improves readability.

**Comment by takecian** [comment]
I expanded abbreviation. Any feedbacks are appreciate.

**Comment by dabrahams** [comment]
The right thing to do is to link all of the “iff”s to https://en.wikipedia.org/wiki/If_and_only_if

**Comment by dabrahams** [comment]
Specifically, it should be possible to replace `iff` with `[iff]` everywhere and add a reference-link, per http://kramdown.gettalong.org/syntax.html#reference-links

**Comment by bitjammer** [comment]
Based on the spec, it looks like it can go anywhere in the document, which would be the doc comment block in this case: http://spec.commonmark.org/0.23/#link-reference-definitions.

Both
```markdown
[iff]: https://en.wikipedia.org/wiki/If_and_only_if

[iff]
```

and

```markdown
[iff]

[iff]: https://en.wikipedia.org/wiki/If_and_only_if
```

look like they produce:

```html
<p><a href="https://en.wikipedia.org/wiki/If_and_only_if">iff</a></p>
```

Let me know if you run into any problems with QuickHelp.

**Comment by takecian** [comment]
Sure, i will replace iff with [iff] with link.
I will update PR at #1482 , as i already closed this PR.
Thanks.

**Comment by dabrahams** [comment]
@bitjammer Does this mean there’s no place I can drop a central instance of `[iff]: https://en.wikipedia.org/wiki/If_and_only_if` to be used by all the `[iff]`s in comment blocks?  If so, we really should fix that!

**Comment by bitjammer** [comment]
Yeah, that's right. Each doc comment block has to be its own cmark document because there is no other way to know when a doc comment ends and doc comments are fetched on demand per declaration. I don't think link reference definitions are actual cmark AST nodes anyway, they are always inlined into where the reference actually occurred.

**Comment by dabrahams** [comment]
@bitjammer 
Hmm, [this link](http://johnmacfarlane.net/babelmark2/?text=I+don’t+know+if+I+can+believe+that.++For+example%0A%0A*+Here+is%0A*+a+bullet+list%0A*+containing+%0A++%5Biff%5D%0A%0A%0A%0Aand+here+is+another+paragraph%0A%0Aand+finally+the+link+reference+definition%0A%0A%5Biff%5D%3A+https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FIf_and_only_if%0A#13) appears to show it working in kramdown even though the reference definition is outside the scope of the place where the reference is used.  Or are you saying something different?

@takecian 
If there’s no way around this, we might as well go with `[iff](https://en.wikipedia.org/wiki/If_and_only_if)` because using the other form isn’t going to save anything.

**Comment by bitjammer** [comment]
Yeah, that works because the parser is considering all of that text as a single document. If you have this in a doc comment, it will work:

```swift
/// Brief.
///
/// The link will be inlined [iff] the link reference is defined somewhere
/// in the same doc comment block.
///
/// - Here are some
/// - bullets
///
/// [iff]: https://en.wikipedia.org/wiki/If_and_only_if
```

screen shot 2016-03-01 at 2 16 39 pm

It's hard to see but that `iff` is a link. So yeah, you will need at least one `[iff]: https://en.wikipedia.org/wiki/If_and_only_if` per doc comment.

**Comment by dabrahams** [comment]
For some reason this PR was closed, and the issue has moved to #1482

**Pull request closed without merging**
