### PR TITLE
Easy compiler crashers

### PR DESCRIPTION
**Pull request by slavapestov**
A fixed crasher a day keeps @practicalswift at bay... or something

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by practicalswift** [comment]
Excellent! :-)

**Pull request merged**
