### PR TITLE
IRGen: Fix incorrect BitwiseCopyable conformance lookups

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes the regression introduced by d1bd039ebdb716c2e7aeb5030441135c26355975.

rdar://126637139, rdar://126779977

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Review by nate-chandler — APPROVED** [review]
Thank you!

**Pull request merged**
