### PR TITLE
[interop][SwiftToCxx] do not expose enums with a protocol type associ…

### PR DESCRIPTION
**Pull request by hyp**
…ated value

### CODE REVIEW

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test source compatibility

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test linux platform

**Review by ravikandhadai — APPROVED** [review]
LGTM!

**Pull request merged**
