### PR TITLE
[testing] Workaround unsorted output

### PR DESCRIPTION
**Pull request by davezarzycki**
`master-next` seems to sort the output differently.

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
Is it really non-deterministic which ordering you get? I would expect the message about the build record to at least be consistent.

**Review by davidungar — COMMENTED** [review]
It's OK for me to merge, but it would be nice to hear from @slavapestov 

The driver should be deterministic, scheduling according to the input files on the command line. @slavapestov , could the observed nondeterminism have anything to do with your recent changes?

**Review by davidungar — APPROVED** [review]
Since you're external, you might need my approval to unblock.

**Comment by davezarzycki** [comment]
Thanks guys, for reference:
```
/home/dave/s/n/swift/test/Driver/PrivateDependencies/driver-show-incremental-mutual-fine.swift:10:17: error: CHECK-FIRST: expected string not found in input
// CHECK-FIRST: Disabling incremental build: could not read build record
                ^
<stdin>:9:1: note: scanning from here

^

Input file: <stdin>
Check file: /home/dave/s/n/swift/test/Driver/PrivateDependencies/driver-show-incremental-mutual-fine.swift

-dump-input=help describes the format of the following dump.

Full input was:
<<<<<<
          1: Swift version 5.3-dev (LLVM fcd50f9b80, Swift 546d331e22)
          2: Target: x86_64-unknown-linux-gnu
          3: Incremental compilation could not read build record.
          4: Disabling incremental build: could not read build record
          5: /usr/bin/python2.7 SOURCE_DIR/test/Driver/PrivateDependencies/Inputs/update-dependencies.py /home/dave/b/n/t/bin/swift-dependency-tool -frontend -c -primary-file ./main.swift ./other.swift -emit-reference-dependencies-path ./main.swiftdeps -target x86_64-unknown-linux-gnu -disable-objc-interop -module-cache-path /home/dave/b/n/t/swift-test-results/x86_64-unknown-linux-gnu/clang-module-cache -swift-version 4 -enable-direct-intramodule-dependencies -ignore-module-source-info -module-name main -o ./main.o
          6: Handled main.swift
          7: /usr/bin/python2.7 SOURCE_DIR/test/Driver/PrivateDependencies/Inputs/update-dependencies.py /home/dave/b/n/t/bin/swift-dependency-tool -frontend -c ./main.swift -primary-file ./other.swift -emit-reference-dependencies-path ./other.swiftdeps -target x86_64-unknown-linux-gnu -disable-objc-interop -module-cache-path /home/dave/b/n/t/swift-test-results/x86_64-unknown-linux-gnu/clang-module-cache -swift-version 4 -enable-direct-intramodule-dependencies -ignore-module-source-info -module-name main -o ./other.o
          8: Handled other.swift
          9: 
check:10     X error: no match found
>>>>>>

```

**Pull request merged**
