### PR TITLE
IRGen: Strip a bitcast that might be there because a runtime function…

### PR DESCRIPTION
**Pull request by aschwaighofer**
… was previously declared of a different type

rdar://55914836

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test and merge

**Comment by aschwaighofer** [comment]
@swift-ci please test linux

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test linux

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test linux

**Comment by stephentyrone** [comment]
@swift-ci please smoke test linux

**Pull request merged**
