### PR TITLE
[Shims] Make SwiftShims Conform to [Modified] ObjC Calling Conventions

### PR DESCRIPTION
**Pull request by CodaFi**
#### What's in this pull request?

The CF-Object-returning parts of the shims were not properly annotated to indicate that they returned their arguments +1 causing Swift to leak them.
#### Resolved bug number: ([SR-1532](https://bugs.swift.org/browse/SR-1532))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

Thanks to @gribozavr for basically writing the majority of this patch.
I just cleaned it up and added a bit of memory management.  Sidenote:
These files do not need to be compiled with -fobjc-arc.  It won’t
change a thing.

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please test and merge

**Comment by moiseev** [comment]
/cc @CodaFi, @mxcl 
Looks like it's failing somewhere inside the swiftpm.

**Comment by CodaFi** [comment]
On it.

**Comment by CodaFi** [comment]
Fixing this bug has revealed a whole rats nest of others in bridging-related code.  I'm closing this in lieu of a more comprehensive patch later.

**Pull request closed without merging**
