### PR TITLE
[NFC] Fix typos

### PR DESCRIPTION
**Pull request by mdznr**

### CODE REVIEW

**Review by LucianoPAlmeida — APPROVED** [review]
LGTM! 
It would be good to be a single commit, but I think this could be squashed on merge

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test

**Comment by mdznr** [comment]
> LGTM!
> It would be good to be a single commit, but I think this could be squashed on merge

I’ll switch to doing that. Wasn’t sure if we wanted different commit message for each of the typos (for `git blame`).

**Review by varungandhi-apple — APPROVED** [review]
LGTM, we can squash on merge as Luciano suggested.

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
