### PR TITLE
OSSA support for Box types. AccessedStorage Box handling. isBorrowedAddress utility.

### PR DESCRIPTION
**Pull request by atrick**
These 4 commits are interdependent as far as avoiding test regressions. The two main features are
- Unify Box/Class/Tail handling in AccessedStorage/MemAccessUtils.
- Add `isBorrowedAddress`, which is required for OSSA-based transformations. 

 Add a tiny BorrowedAddress utility.

    Determines whether an address might be inside a borrowed scope. If so,
    then any address substitution needs to find that scope boundary to
    avoid violating its basic guarantee that all uses are within scope.

 MemAccessUtils: unify Box/Class/Tail storage for consistency and usability

    It was originally convenient for exclusivity optimization to treat
    boxes specially. We wanted to know that the 'Box' kind was always
    uniquely identified. But that's not really important. And now that
    AccessedStorage is being used more generally, the inconsistency is
    problematic.

    A consistent model is also must easier to understand and explain.

    This also make the implementation of the utility simpler and more powerful.

    Functional changes:

    isRCIdentical will look through mark_dependence and mark_uninitialized.

    findReferenceRoot is used consistently everywhere increasing analysis precision.

### CODE REVIEW

**Comment by atrick** [comment]
The `isBorrowedAddress` utility will help fix https://github.com/apple/swift/pull/38672 (OSSA+TempRVO fix) and is required by https://github.com/apple/swift/pull/38470 (OSSA utilities)

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci test source compatibility

**Comment by atrick** [comment]
@swift-ci benchmark

**Comment by atrick** [comment]
All SCK builds passed (although I don't know how to make them build with -sil-verify-all).

**Comment by atrick** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
Thanks @atrick ! lgtm

**Pull request merged**
