### PR TITLE
[runtime] Remove unused lldb symbols

### PR DESCRIPTION
**Pull request by kastiglione**
These symbols aren't used by lldb and were removed from lldb source 4.5 years ago https://github.com/apple/llvm-project/commit/c5929696eede490bfeaac44a9debd22b8e412749.

It appears their use was introduced (https://github.com/apple/llvm-project/commit/262e2ed134564246fdad5ef1cc386109ffc6aeda) and reverted on the same day.

### CODE REVIEW

**Comment by kastiglione** [comment]
@swift-ci test

**Comment by kastiglione** [comment]
@swift-ci test

**Review by adrian-prantl — APPROVED** [review]
I had no idea these existed!

**Review by mikeash — APPROVED** [review]
Huh, never knew about these. If lldb isn't using them, then this seems fine to me.

**Pull request merged**
