### PR TITLE
[Serialization] Reduce file size by splitting dep dirnames from basenames

### PR DESCRIPTION
**Pull request by jrose-apple**
Dependency tracking for cached compiled modules (compiled from swiftinterfaces) can lead to a high percentage of the module being SDK-relative paths when `-track-system-dependencies` is on. Cut down on this by storing directory names in a separate record that gets referenced from each file dependency. (Since a lot of per-file dependencies are header files in a common directory, this is a win.)

We can do something more clever in the future, but this is a reasonable start for, say, the overlays.

rdar://problem/50449802

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Review by harlanhaskins — APPROVED** [review]

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Comment by compnerd** [comment]
This broke CI on Windows!  https://dev.azure.com/compnerd/windows-swift/_build/results?buildId=2061

**Comment by jrose-apple** [comment]
\*sigh\* We really need to get that into "please test".

**Pull request merged**
