### PR TITLE
Sema: Open type cleanup

### PR DESCRIPTION
**Pull request by slavapestov**
Splitting up https://github.com/apple/swift/pull/3033 into smaller pieces for testing and review.

This is all part of the nested generics work. Getting close now...

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by DougGregor** [comment]
This looks fantastic!

**Comment by slavapestov** [comment]
@swift-ci Please test and merge

**Comment by slavapestov** [comment]
I'm merging this manually. The tests passed, but Jenkins threw an IOException.

**Pull request merged**
