### PR TITLE
Reimplement lowering of __tf_tensor_from_scalars/__tf_tensor_from_scalars_1d in deabstraction

### PR DESCRIPTION
**Pull request by lattner**
This can be factored better, and I'd like to move array deletion to a
new pass, but this is a big step forward to making deabstraction more
complete.

### CODE REVIEW

**Comment by lattner** [comment]
@swift-ci please test

**Comment by lattner** [comment]
@swift-ci please test tensorflow

**Comment by lattner** [comment]
@swift-ci please test tensorflow

**Comment by lattner** [comment]
The normal swift tests were run on accident, their failure is expected.

**Comment by lattner** [comment]
Merging this optimistically.  I welcome feedback and I'm more than happy to improve this in follow-on patches, but I'd like to put the refactorings in.

**Comment by rxwei** [comment]
LGTM

**Pull request merged**
