### PR TITLE
NFC: Use SWIFT_APPLE_PLATFORMS in is_darwin_based_sdk instead of another list of SDKs

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Review by compnerd — APPROVED** [review]
This is an improvement, but at this point easier to inline at the sites IMO and just remove the function call.

**Comment by kubamracek** [comment]
Fair point! I've updated the PR to inline each call site.

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Pull request merged**
