### PR TITLE
Synthesize modify accessors for resilient global variables

### PR DESCRIPTION
**Pull request by rjmccall**
rdar://32936947

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Review by slavapestov — APPROVED** [review]

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Comment by rjmccall** [comment]
@slavapestov Significant new ugliness that you might want to re-review.

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Comment by rjmccall** [comment]
@swift-ci Please test source compatibility

**Comment by rjmccall** [comment]
Source compatibility is a UPASS?  Presumably not my problem.

**Pull request merged**
