### PR TITLE
[CSSimplify] Fix warning check to account that "from" might be less optional than "to" type

### PR DESCRIPTION
**Pull request by xedin**
While checking whether compiler needs to produce a checked cast warning,
account for the fact that "from" could be less optional than "to" e.g.
`0 as Any?`, so the difference has to be stored as a signed integer
otherwise it's going to underflow and result in a crash or infinite
recursion in the diagnostics.

Resolves: rdar://79523605

### CODE REVIEW

**Review by hborla — APPROVED** [review]

**Comment by LucianoPAlmeida** [comment]
I feel like I introduced this issue, sorry ...
One question is if we should add a regression test with this case?

**Comment by xedin** [comment]
Ugh, did I not commit a new file again...

**Comment by xedin** [comment]
Ok, now everything is in order! :)

**Comment by LucianoPAlmeida** [comment]
> Ok, now everything is in order! :)

Awesome :)

**Comment by xedin** [comment]
> I feel like I introduced this issue, sorry ...

Don't worry about it! Thanks for all the contributions! :)

**Comment by LucianoPAlmeida** [comment]
> Don't worry about it! 

Ok, Thanks for the fix :)

> Thanks for all the contributions! :)

No problem, happy to help and just grateful for all the learning!

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test MacOS Platform

**Pull request merged**
