### PR TITLE
Enable heuristic that tries to keep large values in memory

### PR DESCRIPTION
**Pull request by aschwaighofer**
rdar://123916109

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci test

**Comment by aschwaighofer** [comment]
@swift-ci test macOS

**Comment by aschwaighofer** [comment]
@swift-ci test linux

**Comment by aschwaighofer** [comment]
@swift-ci test

**Comment by aschwaighofer** [comment]
@swift-ci Please Test Source Compatibility Release

**Comment by aschwaighofer** [comment]
@swift-ci test macOS

**Comment by aschwaighofer** [comment]
@swift-ci test windows

**Comment by aschwaighofer** [comment]
@swift-ci test source compatibility debug

**Comment by aschwaighofer** [comment]
@swift-ci test windows

**Review by eeckstein — APPROVED** [review]
lgtm

**Comment by aschwaighofer** [comment]
@swift-ci test windows

**Pull request merged**
