### PR TITLE
[stdlib] ContiguousArray & ArraySlice: Stop swapping self in wUMBP

### PR DESCRIPTION
**Pull request by lorentey**
Implements https://github.com/apple/swift/pull/38867 for ContiguousArray and ArraySlice -- these have the same unnecessary swapping logic.

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci benchmark

**Review by glessard — APPROVED** [review]
Fewer instructions to do the same thing. LGTM

**Comment by lorentey** [comment]
Surprisingly, swapping `self` with `[]` has a measurable effect sometimes: in the case of https://github.com/apple/swift-collections/pull/78, the compiler isn't able to eliminate retains/releases of the empty array singleton in `Heap.insert` benchmarks, which makes the `withUnsafeMutableBufferPointer` variant slower than the regular Array one!

**Pull request merged**
