### PR TITLE
Update _DropFirstSequence.next() for removal of ++ operator

### PR DESCRIPTION
**Pull request by nielsandriesse**

### CODE REVIEW

**Comment by nielsandriesse** [comment]
SIL is different (bb6, bb8 and bb9), but the amount of instructions appears to be the same: https://gist.github.com/nielsandriesse/91a12210170125eaba17

**Comment by gribozavr** [comment]
@nadavrot Any concerns?  The change LGTM.

**Comment by nadavrot** [comment]
LGTM. We'll track the performance changes after this commit lands.

**Comment by gribozavr** [comment]
Thanks, Nadav.

**Pull request merged**
