### PR TITLE
[Do Not Merge] Experiment disabling ASTScope lookup by default

### PR DESCRIPTION
**Pull request by rintaro**
Do not merge

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by rintaro** [comment]
@swift-ci Please Test Source Compatibility

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by DougGregor** [comment]
What's your goal here?

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by rintaro** [comment]
@DougGregor There's a bug in code completion where unqualified lookups doesn't work in fast-completion. Since ASTScope is not enabled for code-completion, we need to modify legacy `UnqualifiedLookup` code. I just wanted to make sure, it still works perfectly. When I have a fix for the completion bug, I will re-use this PR to check that the fix is also good for compilations.

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by rintaro** [comment]
@swift-ci Please Test Source Compatibility

**Pull request closed without merging**
