### PR TITLE
Remove dead witness tables, including dead witness functions.

### PR DESCRIPTION
**Pull request by eeckstein**
A witness table is dead if it is not used outside the module (private/internal) and it’s not used by any instruction or other witness table in the module.
Also the meta-type of the conforming type must not escape, because it’s possible to test any opaque type if it conforms to a protocol.

This gives about 2.5% code size reduction on stdlib.
Also some benchmarks see code size reductions, but this depends on the benchmark. For most benchmarks (especially our micro-benchmarks, where we don't define any types) there is no improvement. For some larger benchmarks there are significant size reductions. On average it's 2.4%.

rdar://problem/23026019

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci Please test

**Comment by eeckstein** [comment]
@swift-ci Please test

**Comment by eeckstein** [comment]
@swift-ci Please test linux

**Comment by jrose-apple** [comment]
> "Also the meta-type of the conforming type must not escape"

What if an *instance* of the type escapes?

**Comment by jckarter** [comment]
Depends. An instance could escape into a concrete context that can handle the value without metadata. Anywhere we need to escape an instance into a context that also needs the type metadata to work with the instance, that should be tracked independently.

**Comment by jrose-apple** [comment]
It's fuzzy but I can imagine this:

```swift
internal class Impl: SomeProto { /* … */ }

public func produce() -> AnyObject { return Impl() }
public func consume(_ value: AnyObject) {
  guard let interestingValue = value as? SomeProto else { return }
  // …
}
```

I'm pretty sure in this case the witness table is never referenced statically and the metatype does not escape (because we're using AnyObject rather than Any), but we still need the witness table at run-time dynamically.

**Comment by eeckstein** [comment]
> What if an instance of the type escapes?

@jrose-apple The question is if someone outside the translation unit can dynamically check if a value conforms to a protocol. This is done by looking up the metatype of that value in the protocol_conformances section. So if the metatype does not escape we are good.

**Comment by eeckstein** [comment]
@swift-ci Please test linux

**Comment by jrose-apple** [comment]
Why does it matter whether the lookup happens outside the translation unit?

**Comment by eeckstein** [comment]
> I'm pretty sure in this case the witness table is never referenced statically and the metatype does not escape (because we're using AnyObject rather than Any), but we still need the witness table at run-time dynamically.

The metatype does escape because it's stored in the Impl() instance header.

**Comment by eeckstein** [comment]
> Why does it matter whether the lookup happens outside the translation unit?

It doesn't. My mistake

**Comment by jrose-apple** [comment]
Ah, right. I didn't think about the metatype being either passed as a constructor argument or directly stored in the type.

**Pull request merged**
