### PR TITLE
[PropertyWrappers] Fix a bug with property type being overwritten with wrong type

### PR DESCRIPTION
**Pull request by theblixguy**
In some cases, we were incorrectly setting the type of the property wrapper's value. For example:

```swift
@propertyWrapper
struct Foo<T> {
  init(wrappedValue: T) {}
  var wrappedValue: T {
    fatalError()
  }
}

struct Bar {
  @Foo var property: Int = nil // we are overwriting the type of 'property' to 'Int?'
}
```

We should be using an `Equal` constraint between the property type and the initializer's type, rather than a `Conversion` constraint.

Resolves [SR-10900](https://bugs.swift.org/browse/SR-10900), [SR-11381](https://bugs.swift.org/browse/SR-11381) & [SR-11443](https://bugs.swift.org/browse/SR-11443)
Resolves rdar://problem/55229986

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Review by DougGregor — APPROVED** [review]
Of course, this makes perfect sense. Thank you!

**Comment by jrose-apple** [comment]
Can we pull this into 5.1? It's technically a source-break and so I'd rather have it in a point release than have to wait until 5.2.

**Comment by theblixguy** [comment]
Sure, I can create a PR against the `swift-5.1-branch`.

**Comment by DougGregor** [comment]
Thanks @theblixguy

**Pull request merged**
