### PR TITLE
[CMake] Explicitly set Android lib prefix/suffix

### PR DESCRIPTION
**Pull request by modocache**
When compiling the Swift standard library for Android on Linux, the target prefixes and suffixes for static and shared libraries happen to be the same for both platforms. When using a macOS host to compile, however, the suffixes are different, causing build errors.

Explicitly set the prefixes and suffixes to prevent errors when building on macOS.

This was pulled out of the larger pull request https://github.com/apple/swift/pull/4972, which addresses [SR-1362](https://bugs.swift.org/browse/SR-1362).

### CODE REVIEW

**Comment by modocache** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
You're all starting to convince me that using CMake's support would be an improvement.

**Comment by modocache** [comment]
Haha, do you mean https://cmake.org/services/? 😂  Maybe if we pool our money together...

**Comment by jrose-apple** [comment]
Ah, no, just meant using CMake for cross-compilation instead of doing it manually.

**Comment by modocache** [comment]
Oh! Haha, I thought you were getting frustrated reviewing all these pull requests. Again, I really appreciate it!

**Comment by modocache** [comment]
I'm going to go ahead and merge this -- seems like no real opposition, the tests pass, the code simply adds to an existing, reviewed pattern from #5068, and it's specifically for Android. Hope that's OK! :)

**Comment by llvm-beanz** [comment]
@jrose-apple I spent a lot of time over the last year fighting with hand-rolled cross-compiling in compiler-rt. I strongly advise using CMake's built-in support for it. It is *way* simpler.

I've been moving LLVM.org to using CMake's built-in cross-compilation support for building all the runtime library projects via the LLVM "runtimes" directory. There are a few rough edges in CMake that make it challenging, but I think we can work with the CMake community to improve the experience.

**Comment by gottesmm** [comment]
@llvm-beanz I have come to the same conclusion. It would clean up the cmake build system so much conceptually by removing target/sdk specific code out of the compiler code paths.

I have on a separate branch written a prototype that allows us to perform the separate compilation using what we have today. It would then allow us to begin refactoring out the code paths:

https://github.com/gottesmm/swift/tree/external-swift-stdlib

**Pull request merged**
