### PR TITLE
[Syntax] Create UnknownDecl node for orphan #else, et al. and SIL nodes

### PR DESCRIPTION
**Pull request by rintaro**
rdar://problem/54278083

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Review by nkcsgexi — APPROVED** [review]
LGTM, Thank you for fixing it!

**Comment by rintaro** [comment]
@swift-ci Please smoke test macOS

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test Linux

**Pull request merged**
