### PR TITLE
[master-next] Finish getting the importer over to using clang::ModuleMacro

### PR DESCRIPTION
**Pull request by jrose-apple**
Second half of #10519, fixing issues with redeclarations and macros defined in terms of other macros. Fixes *almost* all the remaining master-next issues.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
cc @bob-wilson

**Comment by jrose-apple** [comment]
Looks like LLDB still has some master-next work to do too, but I think either @llvm-beanz or @lhames is on that.

**Comment by llvm-beanz** [comment]
@scallanan is our current czar, so I think master-next issues fall to him at the moment.

**Comment by jrose-apple** [comment]
Hooray, only the three known failures on the macOS bot! (Plus a PythonLint problem.)

**Comment by jrose-apple** [comment]
Not sure if this is hooked up. Let's find out!

@swift-ci Please test source compatibility

**Comment by jrose-apple** [comment]
Source compatibility failures match master. Okay, I'm going to merge this.

**Pull request merged**
