### PR TITLE
[4.0][stdlib] Use CF for Hashing (#9203)

### PR DESCRIPTION
**Pull request by airspeedswift**
Cherry pick of #9203 onto 4.0

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please test and merge

**Comment by shahmishal** [comment]
@swift-ci please clean test and merge

**Comment by tkremenek** [comment]
Timeout on Linux.  Re-testing.

**Comment by tkremenek** [comment]
@swift-ci clean test linux

**Comment by dabrahams** [comment]
How sure are we that CF hashing semantics are consistent with the semantics we have for ==?

**Comment by airspeedswift** [comment]
For ASCII – which is all this PR changes – this is what we're already doing, except we currently go via`NSString`. This just skips that step.

**Pull request merged**
