### PR TITLE
build: add a workaround for the build to use Python2 instead of Python3

### PR DESCRIPTION
**Pull request by compnerd**
Python3 sometimes doesn't get found, add a temporary workaround.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
@swift-ci please test Windows

**Pull request merged**
