### PR TITLE
Propagate "-O" to Clang (as "-Os")

### PR DESCRIPTION
**Pull request by rjmccall**
It affects Clang IRGen, among other things.

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please smoke test and merge.

**Comment by jrose-apple** [comment]
This broke a number of tests that use precompiled bridging headers. I'm not sure why that didn't show up in your smoke test, but it's pretty clearly this commit since it refers to a change in the `__OPTIMIZE__` macro.

**Comment by rjmccall** [comment]
Okay.  @graydon, what did I do wrong here?  Do I need to include this in PCHHashComponents despite it presumably being accounted for in Clang's module hashing?

**Comment by jrose-apple** [comment]
It looks like the O group of options isn't part of the driver's `addCommonFrontendOptions`, probably because it might trigger SIL passes during module merging or extra optimization in the REPL. So the PCH generation job isn't getting this at all.

**Comment by rjmccall** [comment]
It's probably not blocking CI because CI probably doesn't run optimized tests.

**Comment by swiftix** [comment]
Please see rdar://problem/33541306

**Comment by rjmccall** [comment]
Fixing in #11216.

**Pull request merged**
