### PR TITLE
[Rebranch] Resolve Immediate Conflicts

### PR DESCRIPTION
**Pull request by zachary-kent**
Resolves a main -> rebranch merge conflict in Immediate.

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
```
/home/build-user/swift/lib/Immediate/SwiftMaterializationUnit.cpp:85:11: error: no viable conversion from 'llvm::JITTargetAddress' (aka 'unsigned long') to 'llvm::orc::ExecutorAddr'
      ES, llvm::pointerToJITTargetAddress(&handleLazyCompilationFailure));
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by zachary0kent** [comment]
> /home/build-user/swift/lib/Immediate/SwiftMaterializationUnit.cpp:85:11: error: no viable conversion from 'llvm::JITTargetAddress' (aka 'unsigned long') to 'llvm::orc::ExecutorAddr'
>       ES, llvm::pointerToJITTargetAddress(&handleLazyCompilationFailure));
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Ah yup let me update that as well

**Comment by zachary0kent** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
Thanks @zachary0kent!

**Pull request merged**
