### PR TITLE
Fix some guidelines violations and typos

### PR DESCRIPTION
**Pull request by valzevul**
Fix a couple of typos and update whitespaces to look more general.

### CODE REVIEW

**Comment by lattner** [comment]
This patch looks fine to me, Jordan do you have a specific concern?

**Comment by jrose-apple** [comment]
Yes, see the comment on the second commit.

(I have no problem with this if the test passes, just wanted to make sure @valzevul did check that.)

**Comment by gribozavr** [comment]
I'll run tests and merge.

**Comment by gribozavr** [comment]
The tests broke:

```
<src>/swift/test/SILGen/coverage_member_closure.swift:6:16: warning: will never be executed
    if (false) { // CHECK: [[@LINE]]:16 -> [[@LINE+2]]:6 : 1
               ^
<src>/swift/test/SILGen/coverage_member_closure.swift:6:8: note: condition always evaluates to false
    if (false) { // CHECK: [[@LINE]]:16 -> [[@LINE+2]]:6 : 1
       ^
<src>/swift/test/SILGen/coverage_member_closure.swift:13:12: error: expected string not found in input
 // CHECK: [[@LINE+1]]:55 -> [[@LINE+1]]:77 : 2
```

@valzevul Please run `utils/build-script -RT` and update the pull request.

**Comment by frootloops** [comment]
@valzevul @gribozavr @jrose-apple it's already merged https://github.com/apple/swift/pull/610 you can close this PR

**Pull request closed without merging**
