### PR TITLE
Fix Windows dependency library names

### PR DESCRIPTION
**Pull request by hughbe**
- CMark is called `cmark.lib` on Windows
- Clang is called `libClang*.lib` on Windows

### CODE REVIEW

**Review by compnerd — APPROVED** [review]
This is rather unfortunate that we need to do this.  I don't see a better way though.

**Comment by compnerd** [comment]
CC @llvm-beanz in case you see a better way (other than re-architecting the cross-compilation)

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test linux platform

**Comment by llvm-beanz** [comment]
I have a really crazy idea that we might be able to use to make some of this stuff simpler. It would be very non-traditional CMake, but it might make this world better in the short term.

Long term, as I've said before, Swift needs to stop fighting with CMake's cross-compilation strategy.

Short term, *I think* we might be able to streamline some of the platform handling goop with a few convenience wrappers. But we'd have to be careful to do it only in places where the platform-handling code can be placed in its own scope.

What I'm thinking here is that we could do something like:

`
if("${SWIFT_HOST_VARIANT_SDK}" STREQUAL "WINDOWS")
  include(Windows)
else()
  include(UNIX)
endif()
set(dep "${LLVM_LIBRARY_OUTPUT_INTDIR}/${dep}.${CMAKE_STATIC_LIBRARY_SUFFIX}")
`

I believe that doing this in an isolated scope (inside a function) should be safe, and it would allow for more generic code.

We could even abstract the if block into a macro for re-use.

**Pull request merged**
