### PR TITLE
[test] Add s390x support for test/IRGen/pic.swift

### PR DESCRIPTION
**Pull request by levivic**
This is adding s390x support for `test/IRGen/pic.swift`.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Hmm, I don't know s390 assembly to properly review this.  Why does `$s4main6globalSivp` not need any modifiers for the PIC access?

**Comment by rjmccall** [comment]
Looks like `lgrl` takes a 32-bit relative offset.

It looks like this is hard-coding a specific frame layout.  Are you okay with potentially changing this test whenever you change the backend?

**Comment by levivic** [comment]
> Hmm, I don't know s390 assembly to properly review this. Why does `$s4main6globalSivp` not need any modifiers for the PIC access?

By reading the check label for other cpu (e.g., x86_64, aarch64) within this test file, I am not sure what kind of modifier `$s4main6globalSivp` needs. On s390x, `lgrl` load `$s4main6globalSivp` into `REG2` and `REG2` is `stg` stored into address `REG4 +160`.

**Comment by levivic** [comment]
> Looks like `lgrl` takes a 32-bit relative offset.
> 
> It looks like this is hard-coding a specific frame layout. Are you okay with potentially changing this test whenever you change the backend?

You mean potentially change of this test whenever the backend platform is changed? If so, yes, our team has been closely following the development of swift, as well as the platform we are using.

**Comment by rjmccall** [comment]
> I am not sure what kind of modifier $s4main6globalSivp needs.

@compnerd is just unfamiliar with z/Architecture assembly.  In many assembly languages, the fact that the immediate is PC-relative would be more explicit.

> You mean potentially change of this test whenever the backend platform is changed? If so, yes, our team has been closely following the development of swift, as well as the platform we are using.

It just feelings like an unnecessary burden to have frontend tests breaks when unrelated backend changes occur.  If this test is just checking that we generate PIC, I think the only line you actually need here is the `lgrl`.

**Comment by levivic** [comment]
> It feels like an unnecessary burden to have frontend tests break from unrelated backend changes. If this test is just checking that we generate PIC, I think the only line you actually need here is the `lgrl`.

Sure, will provide an update. Thanks.

**Review by rjmccall — APPROVED** [review]
Great, thanks!

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Pull request merged**
