### PR TITLE
NFC: Test printing swiftinterfaces containing declarations originally written using typealiases from another module

### PR DESCRIPTION
**Pull request by tshortli**
This test establishes a baseline for the behavior of swiftinterface emission when public declarations of all kinds reference typealiases from another module. It seems that for many types of declarations, the printer is looking through the typealias definition and printing the original type instead of a fully qualified reference to the typealias. This behavior can cause swiftinterfaces to be unparsable since the original type may not be declared in the module declaring the typealias.

Every CHECK line in this test that includes a reference to fully qualified type from the `Original` module represents an instance of this bug.

Once this behavior is corrected, it should be possible to succesfully parse `UsesAliases.swiftinterface` and the `RUN:` line for doing so should be uncommented.

### CODE REVIEW

**Comment by tshortli** [comment]
@swift-ci please smoke test

**Comment by xymus** [comment]
@slavapestov @CodaFi Are you aware of this issue by chance? Or would you know what could make the compiler print the underlying type of typealiases when used in the context of generics, `any`, and `some`?

I think this issue has been present for a while now, it's affecting a decent number of swiftinterfaces.

**Comment by CodaFi** [comment]
CC @hborla

**Comment by hborla** [comment]
> Or would you know what could make the compiler print the underlying type of typealiases when used in the context of generics, any, and some?

I'm aware of this behavior with `any` and it's due to https://github.com/apple/swift/pull/59041, which is a hack that we need to figure out how to solve in a different way.

**Comment by tshortli** [comment]
@swift-ci please smoke test and merge

**Comment by tshortli** [comment]
@swift-ci please smoke test and merge

**Comment by tshortli** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
