### PR TITLE
[Diagnostics] Tailored diagnostic for "condition" expression

### PR DESCRIPTION
**Pull request by xedin**
Since all condition expressions supposed to be convertible
to `Bool`, let's use that type as contextual and produce a
tailored diagnostic.

### CODE REVIEW

**Comment by xedin** [comment]
Unfortunately this has to wait until https://github.com/apple/swift/pull/27063 lands.

**Comment by xedin** [comment]
@swift-ci please smoke test

**Review by hborla — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Comment by xedin** [comment]
Looks like the Python lint failure should be fixed by https://github.com/apple/swift/pull/27278

**Comment by xedin** [comment]
@swift-ci please smoke test

**Pull request merged**
