### PR TITLE
[stdlib] String.index(before:): Fix index validation issues

### PR DESCRIPTION
**Pull request by lorentey**
`String.index(before:)` (and methods that rely on it, such as `Substring.index(before:)`, `.distance(from:to:)` etc.) does not currently verify that the given index falls before the `endIndex` before aligning it to a scalar boundary. This allows an out-of-bounds memory access when the provided index points to a position beyond the end of `self`’s storage.

Additionally, the `i > startIndex` check needs to be done after scalar alignment, not before, as alignment can round the index down to `startIndex`.

rdar://89497074&89495373

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test

**Review by Azoy — APPROVED** [review]
These look good to me, thanks!

**Comment by lorentey** [comment]
Ah, macOS failed due to an infrastructure issue.

@swift-ci test macOS platform

**Comment by lorentey** [comment]
@swift-ci test macOS platform

**Pull request merged**
