### PR TITLE
[TypeChecker] Add retired constraints to the front of the list in SolverScope

### PR DESCRIPTION
**Pull request by xedin**
Since retired constraints are re-added back to the circulation in LIFO
order, make sure that all of the constraints are added to the front of
SolverScope::retiredConstraints list.

### CODE REVIEW

**Comment by DougGregor** [comment]
I don't understand how it is that this resolves a crash?

**Comment by xedin** [comment]
@DougGregor The reason why it helps is because crash happens in `salvage` where the last `SolverScope` (created by `solveRec`) have been deallocated and all retired constraints should be returned but since in `removeInactiveConstraint` I'm calling `push_back` instead of `push_front` disjunction generated by `optimizeConstraints` has not returned to the InactiveConstraints - since constraints are re-inserted in LIFO order - and, at the same time, was returned to the graph... I've also went through all of the usages of `retiredConstraints` and made sure that everything is using `push_front`.

**Comment by rudkx** [comment]
Yeah the basic problem is that in ~SolverScope we restore the retiredConstraints to where they were prior to this scope, but that code assumes new retired constraints are pushed on the front of the list.

It would be good to clean this up to refactor into clearly documented functions that capture the current state, restore the previous current state, and add newly retired constraints so that all the logic is kept together in one place. Otherwise this is just too easy to get wrong.

@xedin Would you mind taking a crack at that? It doesn't have to be anything fancy - just something that makes it less likely to put constraints at the wrong end of the list in the future.

**Comment by xedin** [comment]
@rudkx Absolutely!

**Comment by xedin** [comment]
@rudkx Done! I've abstracted coupling between state and scope into register/rollback sequence, so state is now responsible for actual rollback logic, and added getter/setter methods to retired/generated constraints.

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Review by rudkx — APPROVED** [review]
Awesome, LGTM!

**Comment by DougGregor** [comment]
I understand now, thank you for the fix (and the education)!

**Pull request merged**
