### PR TITLE
Speed up class_getImageName

### PR DESCRIPTION
**Pull request by tbkka**
When building for Apple OS, dyld_image_path_containing_address
is much, much faster than dladdr.

Resolves rdar://42137685
Resolves SR-14759

### CODE REVIEW

**Comment by tbkka** [comment]
@swift-ci Please test

**Review by allevato — APPROVED** [review]
Thanks!

Out of curiosity, do the CI presets use a configuration that builds the core libraries for in-the-OS distribution, so that `mach-o/dyld_priv.h` is available and the new code path gets utilized?

**Comment by tbkka** [comment]
I thought we specifically wanted to avoid any non-public calls unless building for in-the-OS distribution?

**Comment by mikeash** [comment]
We have quite a few others already. The main thing is just to make sure we can support building with older SDKs (not sure how far back we actually intend to support, but often we're supporting the previous year when calls show up) which is why we look up a lot of stuff dynamically. This call is pretty old so that's not a concern.

**Comment by mikeash** [comment]
I should say, building with older SDKs and running on slightly older OSes. We still support development on macOS 11 currently, so the runtimes built by developers still need to work on macOS 11. But still not an issue here.

**Pull request merged**
