### PR TITLE
[SDK] Remove the obsolete XCTest overlay

### PR DESCRIPTION
**Pull request by lorentey**
The actual XCTest overlay has not been maintained in this repository for years. (It is distributed in Xcode (libXCTestSwiftSupport.dylib), along with XCTest.framework itself.)

The code we have here is badly out of date, and the fact that we have it on the module path in CI makes it interfere with the contents of recent SDKs.

Remove the XCTest overlay from this repository; pick it up from the SDK instead.

rdar://76915582

### CODE REVIEW

**Comment by lorentey** [comment]
My local build hasn't finished yet; I think we should be able to pick up XCTest.swiftmodule from the SDK (because we are able to link XCTest.framework), but it's possible we'll need to need the test configuration.

@swift-ci test

**Review by edymtt — APPROVED** [review]

**Comment by gottesmm** [comment]
@swift-ci test windows platform

**Comment by lorentey** [comment]
```
Script:
--
: 'RUN: at line 6';   rm -rf "/Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/buildbot_incremental/swift-macosx-x86_64/validation-test-macosx-x86_64/ParseableInterface/Output/verify_all_overlays.py.tmp" && mkdir -p "/Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/buildbot_incremental/swift-macosx-x86_64/validation-test-macosx-x86_64/ParseableInterface/Output/verify_all_overlays.py.tmp"
: 'RUN: at line 7';   /Applications/Xcode.app/Contents/Developer/usr/bin/python3 /Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/swift/validation-test/ParseableInterface/verify_all_overlays.py macosx x86_64-apple-macos /Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/buildbot_incremental/swift-macosx-x86_64/lib/swift/macosx /Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/buildbot_incremental/swift-macosx-x86_64/validation-test-macosx-x86_64/ParseableInterface/Output/verify_all_overlays.py.tmp    /Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/buildbot_incremental/swift-macosx-x86_64/bin/swift-frontend -target x86_64-apple-macosx10.9  -module-cache-path /Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/buildbot_incremental/swift-macosx-x86_64/swift-test-results/x86_64-apple-macosx10.9/clang-module-cache -sdk '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk'  -swift-version 4  -define-availability 'SwiftStdlib 5.5:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999' -typo-correction-limit 10  -build-module-from-parseable-interface      -Fsystem "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk"/System/Library/PrivateFrameworks/      | sort > /Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/buildbot_incremental/swift-macosx-x86_64/validation-test-macosx-x86_64/ParseableInterface/Output/verify_all_overlays.py.tmp/failures.txt
: 'RUN: at line 11';   grep '# macosx:' /Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/swift/validation-test/ParseableInterface/verify_all_overlays.py > /Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/buildbot_incremental/swift-macosx-x86_64/validation-test-macosx-x86_64/ParseableInterface/Output/verify_all_overlays.py.tmp/filter.txt || true
: 'RUN: at line 12';   test ! -e /Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/buildbot_incremental/swift-macosx-x86_64/validation-test-macosx-x86_64/ParseableInterface/Output/verify_all_overlays.py.tmp/failures.txt ||    diff /Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/buildbot_incremental/swift-macosx-x86_64/validation-test-macosx-x86_64/ParseableInterface/Output/verify_all_overlays.py.tmp/filter.txt /Users/buildnode/jenkins/workspace/swift-PR-macos/branch-main/buildbot_incremental/swift-macosx-x86_64/validation-test-macosx-x86_64/ParseableInterface/Output/verify_all_overlays.py.tmp/failures.txt
--
Exit Code: 1

Command Output (stdout):
--
1d0
< # macosx: XCTest

--
```

D'oh, I also need to remove XCTest from the expected failure list.

**Comment by lorentey** [comment]
@swift-ci test

**Pull request merged**
