### PR TITLE
Tweak FSO explosion heuristics

### PR DESCRIPTION
**Pull request by gottesmm**
This is still in progress.

rdar://39957093

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci performance

**Comment by gottesmm** [comment]
or actually I should make sure it actually compiles first I guess before seeing code-size numbers.

**Comment by gottesmm** [comment]
Something we may want to try later as well is if we have a large non-trivial type only whose trivial parts are used, we could create a new struct that only contains those trivial leaf parts (maybe flattened?) and just pass those in. We won't have the code-size impact from creating many arguments since we aren't creating many arguments and the IRGen passes should still be able to change it to be passed by pointer.

Getting rid of the ARC overhead for such structs would improve performance.

**Comment by gottesmm** [comment]
Finishing this up.

**Comment by gottesmm** [comment]
Some notes for those watching:

1. I tried disabling our partial PRE of trivial arguments. Turns out we /are/ dependent on this feature of FSO and if we turn it off the stdlib increases in size by 1%. But it does give us significantly more on the benchmark suite. I am going to investigate what we can do about this.
2. This is just the first part of a few more heuristics that I am going to add.

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
Some data.

This reduces the amount of FSO thunks in the stdlib by 20%. In Benchmark_O it reduces it by 16%.

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke compiler performance

**Comment by gottesmm** [comment]
@swift-ci smoke compiler performance

**Comment by gottesmm** [comment]
@swift-ci smoke test compiler performance

**Comment by gottesmm** [comment]
@swift-ci smoke test compiler performance

**Comment by gottesmm** [comment]
*NOTE* I am expecting a few fso test failures since I need to re-update the tests.

**Comment by gottesmm** [comment]
@swift-ci test compiler performance

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
I am putting this down for a second. I implemented a simplified heuristic that reduces the amount that we explode arguments. I think that I can get significantly more if we have access to better information in the Caller. I tried over the weekend to extract out of dead function elimination its better more complete information of the caller analysis, but it seems like a pretty big change.

Instead I am going to do a simpler experiment with the caller analysis that makes it able to for functions to conservatively figure out if we have all of the call sites and make this significantly more aggressive. If I get good results I am going to stop there. Otherwise I am going to try again the whole DFE extraction.

**Comment by gottesmm** [comment]
To be clear the reason I am putting this down right now is I need to fix some bugs ; ).

**Comment by gottesmm** [comment]
Back on this. Current state via cmpcodesize:

```
Title                              Section             Old             New  Percent
Benchmark_O                         __text:        1567491         1551459    -1.0%
Benchmark_Onone                     __text:        2000179         1999843    -0.0%
Benchmark_Osize                     __text:        1326083         1326083     0.0%
libswiftCore.dylib                  __text:        3528114         3536354     0.2%
```

I think I can get back more on swiftCore.dylib. I have setup some infrastructure that I am going to upstream using the yaml stuff I have been committing over the past month or so that makes one able to reason about how thunks are created in an ipython notebook. I am just pushing this update so I can measure compiler performance.

**Comment by gottesmm** [comment]
@swift-ci test compiler performance

**Comment by gottesmm** [comment]
@swift-ci test compiler performance

**Comment by gottesmm** [comment]
This is an S-curve of the current results on the benchmark suite. Down is good. Once I finish taming the remaining stdlib issues, I am going to dig into some of these a bit more.

perf test result

**Comment by gottesmm** [comment]
Found the problem!

**Comment by gottesmm** [comment]
@swift-ci test compiler performance

**Comment by gottesmm** [comment]
@swift-ci test compiler performance

**Comment by gottesmm** [comment]
@swift-ci test compiler performance

**Comment by gottesmm** [comment]
@graydon Question. Is there scripting/facilities for gathering this data per project? I would like to get a more finer grained picture here and would rather not script it myself if you already have something. = ).

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
