### PR TITLE
[DiagnosticsQoI] Refactor ArrayExpr visitor for better QoI

### PR DESCRIPTION
**Pull request by CodaFi**
[SR-6623](https://bugs.swift.org/browse/SR-6623) inspired me to take look around here and clean it up.  The diff is a mess, but the changes in diagnostics in the existing tests are indicative of the improvements the patch provides.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by NachoSoto** [comment]
Better than what we have! 👍

**Comment by NachoSoto** [comment]
None of the test cases are exactly what's in the Jira though, or did I miss one?

**Comment by CodaFi** [comment]
I didn't solve your particular issue with this patch, so I'm going to save it for later.

**Comment by NachoSoto** [comment]
@CodaFi gotcha, thanks for improving this though 👍

**Review by xedin — APPROVED** [review]
LGTM! Thanks, @CodaFi !

**Pull request merged**
