### PR TITLE
[Macros] Generalize `MacroExpansionExpr` and use it for both freestanding and attached macros.

### PR DESCRIPTION
**Pull request by hborla**
* `MacroExpansionExpr` now carries a `MacroRole` that is used to filter out macro declarations during lookup.
* `MacroExpansionExpr` now always has an argument list. If an explicit argument list is not written, an implicit, empty argument list is created.

This change enforces a consistent invocation model between freestanding and attached macros, which also allows the implementation to share more type checking code.

### CODE REVIEW

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by rxwei** [comment]
Nice!

**Review by DougGregor — APPROVED** [review]

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by hborla** [comment]
@swift-ci please smoke test

**Pull request merged**
