### PR TITLE
IUO: Do not short-circuit disjunctions if we had to apply fixes.

### PR DESCRIPTION
**Pull request by rudkx**
There are cases where disjunctions created for IUOs can be solved with
the Optional choice if a fix is applied. We do not want to stop with
this solution as we may be able to solve the constraint system without
a fix by selecting the non-Optional side.

I have opened a JIRA, SR-6626, to investigate one small regression in
diagnostics with this change.

### CODE REVIEW

**Comment by xedin** [comment]
@rudkx As part of trying to remove `solveRec` before `salvage` I actually have to do that as well, I think you'd need to do the same check in `shouldSkipDisjunctionChoice` too to prevent skipping of the generic solutions if non-generic one had a fix in it.

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
Yes, good point. I'll push another change for that and then restart tests in a bit.

**Comment by xedin** [comment]
My changes enable fixes by default but some of the tests are broken because _currently_ when solver tries to re-add unsolved constraint with restriction it doesn't do it correctly, so we end up recording force casts fixes in situations where chaining is the only way to go...

**Comment by rudkx** [comment]
The change you're talking about would be to make:

```
    if (score[SK_ForceUnchecked] == 0 && score[SK_Unavailable] == 0)
      return true;
```

also check that `score[SK_Fix] == 0`, correct?

**Comment by xedin** [comment]
Yes, that's right.

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Review by xedin — APPROVED** [review]
Thanks!

**Comment by rudkx** [comment]
@xedin Thank you for mentioning it!

**Pull request merged**
