### PR TITLE
[build-script] Introduce an option to skip local build.

### PR DESCRIPTION
**Pull request by dcci**
This is useful for cross-compiling.

<rdar://problem/55916729>

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by dcci** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
Please add `skip-local-build` flag to https://github.com/apple/swift/blob/master/utils/build_swift/driver_arguments.py

**Comment by shahmishal** [comment]
Good example for adding new flag to build system: https://github.com/apple/swift/commit/718a5bf3687f33fcc04f17e6ce643ffa77179cb5

**Comment by dcci** [comment]
The github UI is acting a little funny today, I can't reopen this.

**Comment by dcci** [comment]
@swift-ci test

**Comment by dcci** [comment]
@shahmishal can you please take another look?

**Comment by dcci** [comment]
@swift-ci test

**Review by shahmishal — APPROVED** [review]

**Comment by dcci** [comment]
```
18:02:22 ******************** TEST 'Swift(macosx-x86_64) :: Python/python-lint.swift' FAILED ********************
18:02:22 Script:
18:02:22 --
18:02:22 : 'RUN: at line 1';   /usr/bin/python /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/utils/python_lint.py
18:02:22 --
18:02:22 Exit Code: 1
18:02:22 
18:02:22 Command Output (stdout):
18:02:22 --
18:02:22 ./utils/build_swift/driver_arguments.py:308:13: E127 continuation line over-indented for visual indent
```

**Comment by dcci** [comment]
I should be able to fix this tomorrow.

**Comment by dcci** [comment]
@swift-ci test and merge

**Comment by dcci** [comment]
@swift-ci test and merge

**Comment by dcci** [comment]
@swift-ci test and merge

**Pull request merged**
