### PR TITLE
s390x fix objc_simd.sil test failure

### PR DESCRIPTION
**Pull request by levivic**
The change is specific to s390x to make it pass on s390x platforms.

### CODE REVIEW

**Comment by bob-wilson** [comment]
This needs to get changed on master first. Since it's only touching a test file in a way that is specific to s390x, I'll be happy to approve it for Swift 5.0 once the change is on master.

**Comment by levivic** [comment]
@bob-wilson, understand. I have looked into the master, and noticed that 5.0 branch hasn't picked up the commit 0af0d5fddc2674ecf96684cae3dc127365f42f0e in the master. This means whatever changes i made in master maynot be applicable here, unless 5.0 branch picks up that commit. Do you plan to merge that commit into 5.0? If not, i would keep this pull request alive.

**Comment by bob-wilson** [comment]
No, I don't think 0af0d5fddc should go to the 5.0 branch, but it isn't clear to me how that interacts with this change. It touches the IRGen/objc_simd.sil test but only to remove the "trivial" ownership kind.

**Comment by CodaFi** [comment]
There hasn't been movement here in quite a while, and this change still needs to go into master.  I'm going to close this pull request.  If I've done this in error, please submit a pull request to the relevant release branch and master.

**Pull request closed without merging**
