### PR TITLE
build: add an option to optionally build tensorflow-swift-apis

### PR DESCRIPTION
**Pull request by compnerd**
Now that the autodifferentiation support is being upstreamed, add an
option to enable building the TensorFlow swift-apis package optionally.
This enables easier development cycles for the engineers working on it.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
CC: @shahmishal @saeta @dan-zheng @marcrasi

**Review by dan-zheng — APPROVED** [review]
LGTM with approval from Apple folks!

**Review by shahmishal — APPROVED** [review]

**Pull request merged**
