### PR TITLE
[5.5] Restrict uses of 'self' in actor initializers

### PR DESCRIPTION
**Pull request by kavon**
Explanation: Actor initializers permit races due to unrestricted use of 'self', and this radar plugs that hole by rejecting unsafe uses of 'self'.
Risk: Low. Any developers that have written non-trivial code in an actor's initializer will be affected by a source break. This primarily would be early adopters of actors, and will _not_ affect any uses of @MainActor.
Original PRs: https://github.com/apple/swift/pull/37075 and https://github.com/apple/swift/pull/38096
Radar/SR Issue: rdar://78790369
Reviewed By: Konrad Malawski
Testing: Regression tests are included

### CODE REVIEW

**Comment by kavon** [comment]
@swift-ci please test

**Review by ktoso — APPROVED** [review]

**Comment by kavon** [comment]
@swift-ci please test

**Comment by kavon** [comment]
@swift-ci please test

**Comment by kavon** [comment]
@swift-ci nominate

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
