### PR TITLE
[readme] Eliminate autoconf as a dependency for Linux.

### PR DESCRIPTION
**Pull request by gottesmm**
libdispatch uses cmake now.

### CODE REVIEW

**Comment by gottesmm** [comment]
Actually, I think we can also get rid of libtool as well since autoconf is the only thing that requires it.

**Comment by gottesmm** [comment]
I just updated the PR and removed libtool as well.

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by jrose-apple** [comment]
I'm going to abdicate as reviewer; I don't know the current state of the Linux build.

**Review by compnerd — APPROVED** [review]

**Pull request merged**
