### PR TITLE
[3.1] Runtime: Look through artificial ObjC subclasses when building demangle trees for classes.

### PR DESCRIPTION
**Pull request by jckarter**
Fixes rdar://problem/29962114, a regression in presenting the stringified names of ObjC classes that have been dynamically subclassed by KVO.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@slavapestov Mind reviewing this for inclusion in 3.1?

**Comment by slavapestov** [comment]
LGTM

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Pull request merged**
