### PR TITLE
[Compile Time Constant Extraction] Split `fields.swift` test file into 3 files with clear scoping and naming.

### PR DESCRIPTION
**Pull request by quinntaylor**
Divide existing tests into `Extract{Calls,Groups,Literals}.swift` and semantic structs within each file.
Rename structs and properties for even greater clarity.

### CODE REVIEW

**Comment by quinntaylor** [comment]
@swift-ci test

**Review by artemcm — APPROVED** [review]
Thanks!

**Review by jPaolantonio — APPROVED** [review]

**Comment by jPaolantonio** [comment]
@swift-ci test macOS Platform

**Comment by artemcm** [comment]
@swift-ci test macOS Platform

**Pull request merged**
