### PR TITLE
build-script: force LLVM to use libc++ on Darwin

### PR DESCRIPTION
**Pull request by gribozavr**
Under certain circumstances, when the OS X machine has the `/usr/include` directory that contains stale headers (not from the current Xcode installation), the build might fail.  This patch works around the issue by ensuring that LLVM CMake scripts don't try to look in `/usr/include`.

rdar://problem/24452118

### CODE REVIEW

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by gribozavr** [comment]
@bitjammer Could you review for Swift 2.2?

**Comment by bitjammer** [comment]
LGTM.

**Comment by gribozavr** [comment]
The failure was unrelated:

```
Failing Tests (1):
    Swift :: IDE/crashers/059-swift-iterativetypechecker-processinheritedprotocols.swift
```

**Pull request merged**
