### PR TITLE
[Preset] Add LLDB buildbot preset for macOS

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
preset=LLDB_buildbot,macOS
@swift-ci Please test macOS with preset

**Comment by shahmishal** [comment]
preset=LLDB_buildbot,macOS

@swift-ci Please test macOS with preset

**Comment by shahmishal** [comment]
preset=LLDB_buildbot,macOS
@swift-ci test with preset

**Comment by vedantk** [comment]
This might be superseded by https://github.com/apple/swift/pull/14380

**Pull request closed without merging**
