### PR TITLE
Remove SubstitutedType

### PR DESCRIPTION
**Pull request by slavapestov**
Swift.swiftmodule is 670KB smaller now.

### CODE REVIEW

**Comment by lattner** [comment]
Awesome!

**Comment by DougGregor** [comment]
I'd be more impressed if it were the `.dylib` rather than the `.swiftmodule` :)

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Pull request merged**
