### PR TITLE
[ABI] [Mangling] Only look for retroactive conformances in conditional reqs

### PR DESCRIPTION
**Pull request by jrose-apple**
Previously, the mangler searched for retroactive conformances in *any* of a generic type's substitutions, but really we only care about the ones that affect the generic type's conformance, i.e. those that affect generic parameters. Refining this results in shorter mangled names involving instantiations of generic types.

Builds on top of #21448. The last commit is the interesting one.

Follow-up work for rdar://problem/46735592.

### CODE REVIEW

**Comment by jrose-apple** [comment]
There are a whole pile of LLDB failures on the Linux tests and I don't think they're related to this change.

**Review by DougGregor — APPROVED** [review]

**Comment by jrose-apple** [comment]
Same for the Mac bots.

@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
New(er) grammar:

    // same module as conforming type, or non-unique
    protocol-conformance-ref ::= protocol 'HP'
    // same module as protocol
    protocol-conformance-ref ::= protocol 'Hp'
    // retroactive
    protocol-conformance-ref ::= protocol module

We don't make use of this distinction anywhere yet, but we could in the future.

@rjmccall Looks good now?

@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Review by rjmccall — APPROVED** [review]
Yes, thanks!

**Pull request merged**
