### PR TITLE
[Gardening] Remove YieldingContinuation since that approach was disfavored to AsyncStream

### PR DESCRIPTION
**Pull request by phausler**
Remove YieldingContinuation since that was found to be insufficient to accomplish the goals of custom-non-async-sources to be made into AsyncSequences.

Fun fact... this was already removed from the CMakeLists.txt so it wasn't being built! So this is not an ABI breaking change and really just a gardening change ;)

Resolves rdar://78174691

### CODE REVIEW

**Comment by phausler** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test macOS

**Comment by phausler** [comment]
@swift-ci please smoke test macOS

**Review by DougGregor — APPROVED** [review]

**Comment by DougGregor** [comment]
> Fun fact... this was already removed from the CMakeLists.txt so it wasn't being built! So this is not an ABI breaking change and really just a gardening change ;)

It looks like `YieldingContinuation.swift` *is* in `CMakeLists.txt` on the 5.5 branch, though

**Pull request merged**
