### PR TITLE
[docs] Add some additional ways of invoking lit tests by using llvm-l…

### PR DESCRIPTION
**Pull request by gottesmm**
…it and working in the actual swift build directory.

I generally run lit tests in this way and was asked by @weissi to document this
here since my workflow has helped him to become more efficient.

### CODE REVIEW

**Review by weissi — APPROVED** [review]
thanks @gottesmm, that's great. Convinced that will save other newcomers lots of time!

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Review by jrose-apple — CHANGES_REQUESTED** [review]
When we first put up Testing.md, we thought about things like this, and decided it was better to standardize on one recommendation (using the source version of lit). llvm-lit doesn't actually buy you anything in the Swift repo.

**Comment by jrose-apple** [comment]
Can you instead change the lines that use the source directory lit.py to include all your tips? And maybe get off the "build/test/subdir" recommendation that's not as flexible as --filter.

**Comment by gottesmm** [comment]
@jrose-apple The reason to use llvm-lit and do this in the build-directory is that it is significantly less lines to type and can be autocompleted really quickly when you are already in the swift build directory. For me it is ~8-9 key strokes. I would also be fine if we created a symlink called swift-lit in the swift build's bin directory. Would that be an acceptable compromise? That would even make it easier to invoke.

**Comment by jrose-apple** [comment]
As you know, I'm generally against wrapper scripts that don't add significant value over the thing they wrap. :-(

My invocation is `../llvm/utils/lit/lit.py -sv ../build/ninja/swift-macosx-x86_64/test-macosx-x86_64`, from the Swift source directory. Yours is `../llvm-macosx-x86_64/utils/llvm-lit -sv test-macosx-x86_64`, with a shell session in the Swift build directory. I don't really see one of these as "simpler" than the other, especially since it's uncommon to type the whole thing out of scratch instead of running it from history.

**Comment by gottesmm** [comment]
@jrose-apple The statement that people will always invoke lit via their history is IMO a projection of ones own workflow and habits onto others... for example I definitely never invoke lit in this manner via my history. In my case, there are a few reasons that I do not do this:

1. I am often working headless on another machine with multiple shells open. I have found that the history file gets corrupted sometimes so I just type.
2. In docker containers, one can not have a history file unless one creates a long lived home directory which may not be an option for all users. I generally do not have that setup so I invoke it directly.

Additionally, I disagree that value is not provided. The value provided here is convenience and ease of use from the command line without needing to remember a weird path into LLVM. Instead, this places the given tool in the place where one would actively look for a script to run swift's test... the swift bin directory.

That being said, I would like to turn the problem around. Would adding this script actively hurt anyone's workflow? IMO given that it doesn't have impacts on anyone else and I would be spending my own time to add it (not yours = p)... I think it would be fine to add.

**Comment by jrose-apple** [comment]
Adding the script means the script needs to be built, which means that the recommended testing workflow is more likely to fall over if you've only built specific targets (a pretty common thing to do). Having more ways to do things means behavior is more likely to diverge.

You're right that I'm projecting about the history. That said, *I* find having a shell open to the build directory to be very weird—that's part of *your* workflow but not mine.

The form that's recommended now is the most general form. We could make it clear that these are relative paths and therefore will work if you shorten either of them. After all, if you really wanted to make this short, you could just put lit.py in your PATH.

**Comment by gottesmm** [comment]
Ok. I am fine with that. Thanks for the discussion.

**Pull request closed without merging**
