### PR TITLE
[SILCombine] Handle indirect error in apply(convert_function).

### PR DESCRIPTION
**Pull request by nate-chandler**
Previously, only the indirect results and the parameters were handled. However, the indirect error doesn't show up in the list of indirect results (or in the list of parameters).  But it sure does show up in the list of arguments.  Here, that argument too is handled.

rdar://127468646

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by atrick — APPROVED** [review]
LGTM

**Pull request merged**
