### PR TITLE
Update checkout for 'tensorflow/swift-apis' and remove circular dependency from tests

### PR DESCRIPTION
**Pull request by rxwei**
* Update 'tensorflow/swift-apis' revision to track https://github.com/tensorflow/swift-apis/commit/470dbd7e7f27f761fd01686f5526803857e4bb7f.
* Resolves [TF-264](https://bugs.swift.org/browse/TF-264): Tests that depend on the DeepLearning library should not be in the compiler repo. Copied a mini ML library to test files.

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Review by dan-zheng — APPROVED** [review]

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Pull request merged**
