### PR TITLE
[cmake] Move the 'routines' of SourceKit's cmake into a cmake module.

### PR DESCRIPTION
**Pull request by gottesmm**
This is a NFC change that makes it easier to read SourceKit's main
CMakeLists.txt file since you only see "actions" rather than also this huge list
of helper routines.

----

Just a quick cleanup while I was understanding what happened with a build breakage today.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci clean smoke test

**Comment by gottesmm** [comment]
@swift-ci clean smoke test linux platform

**Comment by gottesmm** [comment]
@swift-ci clean smoke test linux platform

**Comment by compnerd** [comment]
@swift-ci please clean smoke test Linux platform

**Comment by gottesmm** [comment]
@compnerd Thanks!

**Pull request merged**
