### PR TITLE
SIL: Fix unconditional checked cast's memory behavior

### PR DESCRIPTION
**Pull request by aschwaighofer**
The instruction reads memory (the type).

rdar://32990161

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please benchmark

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@eeckstein We should probably refined upon this by specifying

```
  SideEffectAnalysis::analyzeInstruction

   case ValueKind::UnconditionalCheckCastInst:
      FInfo->FE.getEffectsOn(cast<UnconditionalCheckCastInst>(I)->getOperand())->Reads = true;
      return;
```

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by eeckstein** [comment]
LGTM

**Pull request merged**
