### PR TITLE
[QoI] Move from RAII to direct sub-expression cleanup. NFC

### PR DESCRIPTION
**Pull request by xedin**
While trying to shrink constraint system try to explicitly cleanup _implicitly_ created 
sub-expressions.

### CODE REVIEW

**Comment by xedin** [comment]
/cc @slavapestov @gparker42 

Sorry for this whole mess... Is there a way for me to verify if this is going to fail ASAN or not?

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
No worries! You can enable ASAN with a build-script flag. Use build-script-impl -help to get the full list of flags.

**Comment by xedin** [comment]
Thanks, @slavapestov! Let me try that right now.

**Comment by xedin** [comment]
@slavapestov I've run `./utils/build-script -r -T --enable-asan true` locally and it passes successfully with current master, and I think this patch legitimately breaks cleanup (as indicated by CI) so let me dig into this deeper tonight and maybe come up with something else...

**Comment by slavapestov** [comment]
Might also be worth seeing if you can get the test to fail locally with the old patch.

**Comment by xedin** [comment]
Yeah, that's what I'm trying to do currently...

**Comment by xedin** [comment]
@slavapestov Was able to reproduce ASAN failures with original code, which lead me to realize that `CleanupIllFormedExpressionRAII` is actually inappropriate while solving candidates because its going to change types to ErrorType, which prevents upper level expressions from being solved correctly. Switched everything to direct implicit expression cleanup and (in additional commit) made is to candidates that have closures inside are not type-checked because changes to the parameter lists can't be rolled back. Ran everything with `./utils/build-script -r -T --enable-asan true --clean` multiple types to make sure no new regressions and ASAN is happy.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by xedin** [comment]
@slavapestov Looks like I fixed one of the crashers and didn't make it, can you please re-run?

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by xedin** [comment]
@slavapestov Thanks and sorry once again, it was 5 AM and I have overlooked that I didn't commit the crasher...

**Pull request merged**
