### PR TITLE
Add debug info support for boxed arguments in async functions.

### PR DESCRIPTION
**Pull request by adrian-prantl**
Usually debug info only ever describes the result of a projectBox
call. To display a boxed parameter of an async continuation object,
however, the debug info can only describe the box itself and thus also
needs to emit a box type for it so the debugger knows to call into
Remote Mirrors to unbox the value.

Fixes https://bugs.swift.org/browse/SR-14059.

### CODE REVIEW

**Comment by adrian-prantl** [comment]
Looks like I can factor some code from ASTBuilder::demangleGenericSignature into TypeDecorder...

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by gwynne** [comment]
The Windows build failure is fixed in #35566

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by gwynne** [comment]
@swift-ci please smoke test macos

**Comment by gwynne** [comment]
@swift-ci please test macos

**Comment by gwynne** [comment]
@adrian-prantl Is there anything further blocking this?

**Comment by adrian-prantl** [comment]
> @adrian-prantl Is there anything further blocking this?

A review from @slavapestov over in https://github.com/apple/swift/pull/35443.

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Pull request merged**
