### PR TITLE
Add find_package(PythonInterp) to CMake

### PR DESCRIPTION
**Pull request by hughbe**
- Python is required
- Previously you'd have to manually pass `PYTHON_EXECUTABLE` on Windows

### CODE REVIEW

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by gottesmm** [comment]
Can you do a clean test as well since this is a CMake change?

**Comment by gottesmm** [comment]
Or you know what...

**Comment by gottesmm** [comment]
@swift-ci Please clean smoke test

**Comment by hughbe** [comment]
Cheers! Didn't know about `clean smoke test`. Let me know if you're happy with the change or have any comments

**Comment by gottesmm** [comment]
feel free to merge at your leasure

**Pull request merged**
