### PR TITLE
[AutoDiff upstream] Enable `@differentiable` on setters.

### PR DESCRIPTION
**Pull request by dan-zheng**
Enable `@differentiable` attribute on setters of properties and
subscripts in `Differentiable`-conforming types.

Upstreams https://github.com/apple/swift/pull/30178 from `tensorflow` branch. Resolves TF-1166.

### CODE REVIEW

**Comment by dan-zheng** [comment]
@swift-ci Please test

**Review by rxwei — COMMENTED** [review]
- Are there tests to verify that derivatives of differentiable setters can be computed end-to-end?
- Are there tests to verify that differentiable setters aren't causing issues related to TBDGen, `-enable-testing`, `-g`, or library evolution mode?

**Comment by dan-zheng** [comment]
> * Are there tests to verify that derivatives of differentiable setters can be computed end-to-end?

Yes, those tests (derivative registration and automatic differentiation of setters) actually already exist. It's just declaring setters as `@differentiable` that wasn't supported.

https://github.com/apple/swift/blob/4fb787a8103d9b963c94bec8cb57a145e3a91a60/test/AutoDiff/validation-test/derivative_registration.swift#L121-L153

> * Are there tests to verify that differentiable setters aren't causing issues related to TBDGen, `-enable-testing`, `-g`, or library evolution mode?

Just added TBDGen tests, thanks for the reminder!

**Comment by rxwei** [comment]
> > * Are there tests to verify that derivatives of differentiable setters can be computed end-to-end?
> 
> Yes, those tests (derivative registration for and automatic differentiation of setters) actually already exist. It's just declaring setters as `@differentiable` that wasn't supported.

Thanks for the pointer. However, I was mainly asking about whether the _automatically_ differentiated setters are tested. In the file you pointed it seems to be only testing a manually registered derivative.

**Comment by dan-zheng** [comment]
> However, I was mainly asking about whether the _automatically_ differentiated setters are tested.

Here's one: https://github.com/apple/swift/blob/7afb399610b7bbcd8b3d29754bded64a0f1a3787/test/AutoDiff/validation-test/inout_parameters.swift#L112-L131

I think that's decent for the purposes of this PR - happy to add more if you'd like to test specific cases.

**Comment by dan-zheng** [comment]
@swift-ci Please test

**Review by rxwei — APPROVED** [review]
It would be be good to have a cross-module test suite (in the future) that verifies automatically differentiated functions (triggered by `@differentiable` attribute) can be taken the derivative of in a different module, for not just computer property setters but all decls. I'm suggesting this because we are exporting and finding differentiability witnesses using the AST `@differentiable` attributes.

**Comment by rxwei** [comment]
> I think that's decent for the purposes of this PR - happy to add more if you'd like to test specific cases.

I'm sorry my suggestion was not super clear. The test that you pointed to, i.e. inout_parameters.swift, totally counts as a case of "automatically differentiated setters", but it feels slightly less relevant to this patch because it is not using a `@differentiable` attribute to trigger differentiation on the setter, which is _the feature_ introduced by this PR.  Does this clarify my suggestion?

**Comment by dan-zheng** [comment]
> Does this clarify my suggestion?

Yep, thanks! Added an automatically differentiated `@differentiable` setter test.

**Comment by dan-zheng** [comment]
> It would be be good to have a cross-module test suite (in the future) that verifies automatically differentiated functions (triggered by `@differentiable` attribute) can be taken the derivative of in a different module, for not just computer property setters but all decls. I'm suggesting this because we are exporting and finding differentiability witnesses using the AST `@differentiable` attributes.

Good idea! More cross-module tests in general sound great, there've been some latent autodiff issues discovered in SwiftPM packages but not caught by the test suite.

**Comment by dan-zheng** [comment]
@swift-ci Please test

**Review by BradLarson — APPROVED** [review]

**Pull request merged**
