### PR TITLE
[Sema] Warn on `@_implementationOnly` imports from a module without library-evolution

### PR DESCRIPTION
**Pull request by xymus**
Add a warning on uses of `@_implementationOnly` from an importer module without library-evolution. `@_implementationOnly` was designed for use from resilient modules only, using it from non-resilient modules is unsupported and can lead to run time crashes.

If anyone hits this warning, they should either enable library-evolution or consider adopting the new `internal import` when it is available as it handles this scenario properly.

More about what actually leads to a crash: an `@_implementationOnly` import fully hides the dependency from indirect clients. This can lead to the compiler being unaware of some internal details (mostly incomplete memory layouts) of a non-resilient module when building a client against it. In turn, this may lead to run time crashes caused by miscompilation. We don't see this problem with resilient modules as the required information is queried at run time.

In general, one could still use `@_implementationOnly` in a non-resilient modules as long as it's referenced only from function bodies. However, using imported types for even non-public properties does lead to important memory layout information being hidden from clients of the module.

rdar://78129903

### CODE REVIEW

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Review by artemcm — APPROVED** [review]

**Comment by xymus** [comment]
Fixing more tests and adding more `-swift-version 5`.

@swift-ci Please smoke test

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by DmT021** [comment]
> In general, one could still use @_implementationOnly in a non-resilient modules as long as it's referenced only from function bodies. However, using imported types for even non-public properties does lead to important memory layout information being hidden from clients of the module.

@xymus Are there other problems due to using implementationOnly in non-resilient modules? Could we produce a warning when a type is used incorrectly instead of this warning?
We are using `@_implementationOnly` extensively in a bunch of non-resilient modules and have warnings-as-errors. The update to Xcode 15.3 brought us this warning and it seems like there's no good workaround.

**Pull request merged**
