### PR TITLE
Fix some low-hanging request evaluator performance fruit

### PR DESCRIPTION
**Pull request by slavapestov**
We've added a lot of new requests lately and converted more of the declaration checker to use requests. This has led to an increase in per-request overhead. This PR addresses some of this overhead:

- Don't build the request dependency graph by default since it's currently only used for debugging
- Look for a cached result before checking for a cycle to avoid expensive AnyRequest allocation

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@DougGregor if this PR looks OK, please also approve the 5.2 cherry-pick -- it should be very low risk: https://github.com/apple/swift/pull/29089

**Review by CodaFi — APPROVED** [review]
LGTM

**Comment by CodaFi** [comment]
Just to see wall time stuff - don't let this block anything.

@swift-ci please test compiler performance

**Comment by CodaFi** [comment]
@swift-ci please test compiler performance

**Pull request merged**
