### PR TITLE
[6.0🍒] NCGenerics: permit syntax always

### PR DESCRIPTION
**Pull request by kavon**
- Explanation: Removes guards to the syntax of NoncopyableGenerics. Clean up now-unused code.
- Scope: Just syntactic
- Issue: rdar://126730410
- Original https://github.com/apple/swift/pull/73131
- Risk: None
- Testing: Tests included
- Reviewer:

### CODE REVIEW

**Comment by kavon** [comment]
@swift-ci test

**Comment by kavon** [comment]
@swift-ci test

**Review by tbkka — APPROVED** [review]

**Comment by kavon** [comment]
@swift-ci test

**Comment by kavon** [comment]
@swift-ci test

**Review by tbkka — APPROVED** [review]

**Comment by kavon** [comment]
@swift-ci test

**Comment by kavon** [comment]
windows failure had lots of this:
```
PermissionError: [WinError 5] Access is denied
```
@swift-ci please test windows

**Pull request merged**
