### PR TITLE
Add DebugPrefixMap remapping back to module creation

### PR DESCRIPTION
**Pull request by DavidGoldman**
@adrian-prantl This was accidentally removed in commit 10004edf49e39f98f2c7498f9c15a79d364eb05c.

EDIT: Also would be great to merge this into swift-5.0-branch (minor update) if possible. Thanks!

### CODE REVIEW

**Comment by adrian-prantl** [comment]
We'll need to add a testcase for this or else this will break again.

**Comment by DavidGoldman** [comment]
True, I'll try to add one.

**Comment by DavidGoldman** [comment]
@adrian-prantl done, tested added

**Comment by adrian-prantl** [comment]
Nice. Could you please open a separate PR making the same change on the master branch? There is no automerger from 5.1 -> master.

**Comment by DavidGoldman** [comment]
Done in https://github.com/apple/swift/pull/23628

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
> Also would be great to merge this into swift-5.0-branch (minor update) if possible. Thanks!
Could you please create a pull request and add me and @fredriss as a reviewer? Again, no promises.

**Review by adrian-prantl — APPROVED** [review]

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by DavidGoldman** [comment]
Looks like it failed due to an unrelated Linux error:

```
/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-swift-5.1-branch/swift-corelibs-foundation/TestFoundation/TestThread.swift:65: error: TestThread.test_threadName : XCTAssertEqual failed: ("Thread2-1") is not equal to ("Thread2-2") - 
/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-swift-5.1-branch/swift-corelibs-foundation/TestFoundation/TestThread.swift:65: error: TestThread.test_threadName : XCTAssertEqual failed: ("Thread2-1") is not equal to ("Thread2-2") - 
Test Case 'TestThread.test_threadName' failed (0.001 seconds)
Test Case 'TestThread.test_mainThread' started at 2019-03-29 18:09:21.529
Test Case 'TestThread.test_mainThread' passed (0.0 seconds)
Test Case 'TestThread.test_callStackSymbols' started at 2019-03-29 18:09:21.529
Test Case 'TestThread.test_callStackSymbols' passed (0.001 seconds)
Test Case 'TestThread.test_callStackReurnAddresses' started at 2019-03-29 18:09:21.530
Test Case 'TestThread.test_callStackReurnAddresses' passed (0.0 seconds)
Test Suite 'TestThread' failed at 2019-03-29 18:09:21.530
	 Executed 6 tests, with 2 failures (0 unexpected) in 0.007 (0.007) seconds
```

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Pull request merged**
