### PR TITLE
Fix effects checking for rethrowing functions involving parameter packs

### PR DESCRIPTION
**Pull request by DougGregor**
Effects checking for rethrowing functions was using unsubstituted interface types for the parameter list. When a rethrows function has parameter pack arguments, the interface type may have a different number of parameters from the resulting argument list, causing the effects checking to bail out early.

This has been wrong since the introduction of parameter packs, but recent refactoring of effects checking ended up promoting this bug to a compiler crash. Fix the bug, introduce an assertion so we catch when the effects checker is failing to reason about valid code (which would have caught this earlier), and make the effects checker still produce sensible ASTs when that assertion is disabled.

Fixes rdar://116740385.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please build toolchain

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please build toolchain

**Comment by grynspan** [comment]
@swift-ci please build toolchain

**Comment by grynspan** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please build toolchain

**Comment by DougGregor** [comment]
ARGH, still something to fix here

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please build toolchain

**Pull request merged**
