### PR TITLE
Remove slide calculation

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @dcci @jckarter @alexshap

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by jckarter** [comment]
Awesome, it's great we don't need that anymore!

**Comment by alexshap** [comment]
))))

**Pull request merged**
