### PR TITLE
Fix out-of-bounds when providing fixits for the @available attribute.

### LINKED ISSUE #64694: Semantic checking crashes on @available(renamed:) with varargs
**Description**
The Swift front-end compiler hits an assert and crashes during semantic checking (`diagnoseExplicitUnavailability` / `fixItAvailableAttrRename`) when the `@available(renamed:)` attribute is used on a function with variadic args. 

**Steps to reproduce**
Create `CrashRepro.swift` as:

```swift
func log(message: String) {}

@available(*, unavailable, renamed: "foo(arg:)")
func log(format: String, _ args: Any...) { fatalError() }

log(format: "")
```

Run `swiftc CrashRepro.swift`

Result: the compiler crashes in type checking

```
C:\Code\swift-playground>swiftc CrashRepro.swift -IS:\Library\Developer\Platforms\Windows.platform\Developer\Library\XCTest-development\usr\lib\swift\windows\x86_64 -LS:\Library\Developer\Platforms\Windows.platform\Developer\Library\XCTest-development\usr\lib\swift\windows\x86_64
error: compile command failed due to exception 3 (use -v to see invocation)
Assertion failed: this->isReferenceToStorage(CI) && "Iterator to erase is out of bounds.", file S:\SourceCache\llvm-project\llvm\include\llvm/ADT/SmallVector.h, line 745
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.      Program arguments: S:/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/bin/swift-frontend.exe -frontend -c -primary-file NSPredicateCrashRepro.swift -target x86_64-unknown-windows-msvc -disable-objc-interop -sdk S:\\Library\\Developer\\Platforms\\Windows.platform\\Developer\\SDKs\\Windows.sdk -I S:\\Library\\Developer\\Platforms\\Windows.platform\\Developer\\Library\\XCTest-development\\usr\\lib\\swift\\windows\\x86_64 -color-diagnostics -empty-abi-descriptor -plugin-path S:\\Library\\Developer\\Toolchains\\unknown-Asserts-development.xctoolchain\\usr\\lib\\swift\\host\\plugins -plugin-path S:\\Library\\Developer\\Toolchains\\unknown-Asserts-development.xctoolchain\\usr\\local\\lib\\swift\\host\\plugins -resource-dir S:\\Library\\Developer\\Toolchains\\unknown-Asserts-development.xctoolchain\\usr\\lib\\swift -module-name NSPredicateCrashRepro -o C:\\Users\\micro\\AppData\\Local\\Temp\\TemporaryDirectory.pveUAJ\\NSPredicateCrashRepro-1.o
1.      Swift version 5.9-dev (LLVM 442d36fbd7d4187, Swift 21701ace65163e8)
2.      Compiling with the current language version
3.      While evaluating request TypeCheckSourceFileRequest(source_file "NSPredicateCrashRepro.swift")
4.      While type-checking extension of NSPredicate (at NSPredicateCrashRepro.swift:3:8)
5.      While type-checking declaration 0x2731cc30708 (at NSPredicateCrashRepro.swift:4:5)
6.      While evaluating request PatternBindingEntryRequest((unknown decl), 0, 0)
7.      While type-checking expression at [NSPredicateCrashRepro.swift:4:26 - line:4:65] RangeText="NSPredicate(format: "isEnabled == true""
8.      While type-checking-target starting at NSPredicateCrashRepro.swift:4:26
Exception Code: 0x80000003
 #0 0x00007ff6dc81f465 HandleAbort S:\SourceCache\llvm-project\llvm\lib\Support\Windows\Signals.inc:414:0
 #1 0x00007fffbd79e5f5 (C:\Windows\System32\ucrtbase.dll+0x7e5f5)
 #2 0x00007fffbd79f601 (C:\Windows\System32\ucrtbase.dll+0x7f601)
 #3 0x00007fffbd7a0fae (C:\Windows\System32\ucrtbase.dll+0x80fae)
 #4 0x00007fffbd7a11f1 (C:\Windows\System32\ucrtbase.dll+0x811f1)
 #5 0x00007ff6d7a71c0a std::_Copy_memmove C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\xutility:4239:0
 #6 0x00007ff6d7a71c0a std::_Move_unchecked C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\xutility:4599:0       
 #7 0x00007ff6d7a71c0a std::move C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\xutility:4617:0
 #8 0x00007ff6d7a71c0a llvm::SmallVectorImpl<class swift::SILValue>::erase(class swift::SILValue const *) S:\SourceCache\llvm-project\llvm\include\llvm\ADT\SmallVector.h:749:0
 #9 0x00007ff6d8581637 fixItAvailableAttrRename::__l2::<lambda_2>::operator() S:\SourceCache\swift\lib\Sema\TypeCheckAvailability.cpp:2528:0
#10 0x00007ff6d8581637 fixItAvailableAttrRename S:\SourceCache\swift\lib\Sema\TypeCheckAvailability.cpp:2553:0
#11 0x00007ff6d8574e53 llvm::function_ref<void __cdecl(swift::InFlightDiagnostic &)>::callback_fn<`swift::diagnoseExplicitUnavailability'::`2'::<lambda_1> > S:\SourceCache\llvm-project\llvm\include\llvm\ADT\STLFunctionalExtras.h:47:0
#12 0x00007ff6d857c089 swift::diagnoseExplicitUnavailability(class swift::ValueDecl const *, class swift::SourceRange, class swift::ExportContext const &, class swift::OptionSet<enum swift::DeclAvailabilityFlag, unsigned char>, class llvm::function_ref<(class swift::InFlightDiagnostic &)>) S:\SourceCache\swift\lib\Sema\TypeCheckAvailability.cpp:3141:0
#13 0x00007ff6d857b9a6 swift::diagnoseDeclAvailability(class swift::ValueDecl const *, class swift::SourceRange, class swift::Expr const *, class swift::ExportContext const &, class swift::OptionSet<enum swift::DeclAvailabilityFlag, unsigned char>) S:\SourceCache\swift\lib\Sema\TypeCheckAvailability.cpp:3693:0 
#14 0x00007ff6d857bda0 `anonymous namespace'::ExprAvailabilityWalker::diagnoseDeclRefAvailability S:\SourceCache\swift\lib\Sema\TypeCheckAvailability.cpp:3590:0
#15 0x00007ff6d8584ef5 swift::DeclRefExpr::getSourceRange S:\SourceCache\swift\include\swift\AST\Expr.h:1237:0
#16 0x00007ff6d8584ef5 `anonymous namespace'::ExprAvailabilityWalker::walkToExprPre S:\SourceCache\swift\lib\Sema\TypeCheckAvailability.cpp:3254:0
#17 0x00007ff6d8b03e31 `anonymous namespace'::Traversal::doIt S:\SourceCache\swift\lib\AST\ASTWalker.cpp:1445:0
#18 0x00007ff6d8b08564 `anonymous namespace'::Traversal::visitSelfApplyExpr S:\SourceCache\swift\lib\AST\ASTWalker.cpp:1003:0
#19 0x00007ff6d8b0533e swift::ASTVisitor<`anonymous namespace'::Traversal,swift::Expr *,swift::Stmt *,bool,swift::Pattern *,bool,void>::visit S:\SourceCache\swift\include\swift\AST\ASTVisitor.h:69:0
#20 0x00007ff6d8b03800 `anonymous-namespace'::Traversal::SetParentRAII::{dtor} S:\SourceCache\swift\lib\AST\ASTWalker.cpp:93:0
#21 0x00007ff6d8b03800 `anonymous-namespace'::Traversal::visit S:\SourceCache\swift\lib\AST\ASTWalker.cpp:100:0
#22 0x00007ff6d8b03800 `anonymous-namespace'::Traversal::doIt::__l2::<lambda_1>::operator() S:\SourceCache\swift\lib\AST\ASTWalker.cpp:1447:0
#23 0x00007ff6d8b03800 llvm::function_ref<swift::Expr * __cdecl(swift::Expr *)>::callback_fn<``anonymous namespace'::Traversal::doIt'::`2'::<lambda_1> > S:\SourceCache\llvm-project\llvm\include\llvm\ADT\STLFunctionalExtras.h:45:0
#24 0x00007ff6d8b03ec6 `anonymous namespace'::Traversal::doIt S:\SourceCache\swift\lib\AST\ASTWalker.cpp:1445:0
#25 0x00007ff6d8b052ef swift::ASTVisitor<`anonymous namespace'::Traversal,swift::Expr *,swift::Stmt *,bool,swift::Pattern *,bool,void>::visit S:\SourceCache\swift\include\swift\AST\ASTVisitor.h:69:0
#26 0x00007ff6d8b03800 `anonymous-namespace'::Traversal::SetParentRAII::{dtor} S:\SourceCache\swift\lib\AST\ASTWalker.cpp:93:0
#27 0x00007ff6d8b03800 `anonymous-namespace'::Traversal::visit S:\SourceCache\swift\lib\AST\ASTWalker.cpp:100:0
#28 0x00007ff6d8b03800 `anonymous-namespace'::Traversal::doIt::__l2::<lambda_1>::operator() S:\SourceCache\swift\lib\AST\ASTWalker.cpp:1447:0
#29 0x00007ff6d8b03800 llvm::function_ref<swift::Expr * __cdecl(swift::Expr *)>::callback_fn<``anonymous namespace'::Traversal::doIt'::`2'::<lambda_1> > S:\SourceCache\llvm-project\llvm\include\llvm\ADT\STLFunctionalExtras.h:45:0
#30 0x00007ff6d8b03ec6 `anonymous namespace'::Traversal::doIt S:\SourceCache\swift\lib\AST\ASTWalker.cpp:1445:0
#31 0x00007ff6d8b08966 swift::Expr::walk(class swift::ASTWalker &) S:\SourceCache\swift\lib\AST\ASTWalker.cpp:2159:0
#32 0x00007ff6d857caa2 llvm::SmallVector<swift::Expr const *,16>::{dtor} S:\SourceCache\llvm-project\llvm\include\llvm\ADT\SmallVector.h:1207:0
#33 0x00007ff6d857caa2 swift::diagnoseExprAvailability(class swift::Expr const *, class swift::DeclContext *) S:\SourceCache\swift\lib\Sema\TypeCheckAvailability.cpp:3892:0
#34 0x00007ff6d86326e7 swift::performSyntacticExprDiagnostics(class swift::Expr const *, class swift::DeclContext const *, bool, bool) S:\SourceCache\swift\lib\Sema\MiscDiagnostics.cpp:5815:0
#35 0x00007ff6d856e235 swift::constraints::performSyntacticDiagnosticsForTarget(class swift::constraints::SyntacticElementTarget const &, bool, bool) S:\SourceCache\swift\lib\Sema\TypeCheckConstraints.cpp:377:0
#36 0x00007ff6d8573ef5 swift::TypeChecker::typeCheckTarget(class swift::constraints::SyntacticElementTarget &, class swift::OptionSet<enum swift::TypeCheckExprFlags, unsigned int>) S:\SourceCache\swift\lib\Sema\TypeCheckConstraints.cpp:488:0
#37 0x00007ff6d8572329 swift::TypeChecker::typeCheckExpression(class swift::constraints::SyntacticElementTarget &, class swift::OptionSet<enum swift::TypeCheckExprFlags, unsigned int>) S:\SourceCache\swift\lib\Sema\TypeCheckConstraints.cpp:408:0
#38 0x00007ff6d85706f6 swift::TypeChecker::typeCheckBinding(class swift::Pattern *&, class swift::Expr *&, class swift::DeclContext *, class swift::Type, class swift::PatternBindingDecl *, unsigned int, class swift::OptionSet<enum swift::TypeCheckExprFlags, unsigned int>) S:\SourceCache\swift\lib\Sema\TypeCheckConstraints.cpp:793:0
#39 0x00007ff6d8573a1d swift::TypeChecker::typeCheckPatternBinding(class swift::PatternBindingDecl *, unsigned int, class swift::Type, class swift::OptionSet<enum swift::TypeCheckExprFlags, unsigned int>) S:\SourceCache\swift\lib\Sema\TypeCheckConstraints.cpp:860:0
#40 0x00007ff6d8471b8e swift::PatternBindingEntryRequest::evaluate(class swift::Evaluator &, class swift::PatternBindingDecl *, unsigned int, bool) const S:\SourceCache\swift\lib\Sema\TypeCheckStorage.cpp:432:0
#41 0x00007ff6d8346e08 swift::SimpleRequest<class swift::PatternBindingEntryRequest, (class swift::PatternBindingDecl *, unsigned int, bool), 4>::evaluateRequest(class swift::PatternBindingEntryRequest const &, class swift::Evaluator &) S:\SourceCache\swift\include\swift\AST\SimpleRequest.h:292:0
#42 0x00007ff6d8435014 swift::Evaluator::getResultUncached<class swift::PatternBindingEntryRequest>(class swift::PatternBindingEntryRequest const &) S:\SourceCache\swift\include\swift\AST\Evaluator.h:362:0
#43 0x00007ff6d84308bb swift::Evaluator::operator() S:\SourceCache\swift\include\swift\AST\Evaluator.h:264:0
#44 0x00007ff6d84308bb swift::evaluateOrDefault<class swift::PatternBindingEntryRequest>(class swift::Evaluator &, class swift::PatternBindingEntryRequest, class swift::PatternBindingEntry const *) S:\SourceCache\swift\include\swift\AST\Evaluator.h:105:0
#45 0x00007ff6d84ea3f1 `anonymous namespace'::DeclChecker::visitPatternBindingDecl S:\SourceCache\swift\lib\Sema\TypeCheckDeclPrimary.cpp:2226:0
#46 0x00007ff6d84e4ebc `anonymous namespace'::DeclChecker::visit S:\SourceCache\swift\lib\Sema\TypeCheckDeclPrimary.cpp:1880:0
#47 0x00007ff6d84e909d swift::DeclIterator::operator++ S:\SourceCache\swift\include\swift\AST\Decl.h:8674:0
rceCache\swift\include\swift\AST\Evaluator.h:393:0
#55 0x00007ff6d835f596 swift::evaluateOrDefault<class swift::TypeCheckSourceFileRequest>(class swift::Evaluator &, class swift::TypeCheckSourceFileRequest, class std::tuple<>) S:\SourceCache\swift\include\swift\AST\Evaluator.h:106:0
#56 0x00007ff6d836d2ba swift::performTypeChecking(class swift::SourceFile &) S:\SourceCache\swift\lib\Sema\TypeChecker.cpp:260:0#57 0x00007ff6d74ea23c llvm::function_ref<bool __cdecl(swift::SourceFile &)>::callback_fn<`swift::CompilerInstance::performSema'::`2'::<lambda_1> > S:\SourceCache\llvm-project\llvm\include\llvm\ADT\STLFunctionalExtras.h:45:0#58 0x00007ff6d74f097e swift::CompilerInstance::forEachFileToTypeCheck(class llvm::function_ref<(class swift::SourceFile &)>) S:\SourceCache\swift\lib\Frontend\Frontend.cpp:1305:0#59 0x00007ff6d74f5ca5 swift::CompilerInstance::performSema(void) S:\SourceCache\swift\lib\Frontend\Frontend.cpp:1230:0
#60 0x00007ff6d73095a7 performAction S:\SourceCache\swift\lib\FrontendTool\FrontendTool.cpp:1375:0#61 0x00007ff6d730bd92 swift::performFrontend(class llvm::ArrayRef<char const *>, char const *, void *, class swift::FrontendObserver *) S:\SourceCache\swift\lib\FrontendTool\FrontendTool.cpp:2328:0#62 0x00007ff6d72c90b6 run_driver S:\SourceCache\swift\lib\DriverTool\driver.cpp:201:0
#63 0x00007ff6d72c8be9 swift::mainEntry(int, char const **) S:\SourceCache\swift\lib\DriverTool\driver.cpp:418:0
#64 0x00007ff6dc8aea9c invoke_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78:0#65 0x00007ff6dc8aea9c __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288:0
#66 0x00007fffbeaa26bd (C:\Windows\System32\KERNEL32.DLL+0x126bd)#67 0x00007fffbfeaa9f8 (C:\Windows\SYSTEM32\ntdll.dll+0x5a9f8)
error: fatalError
```

**Expected behavior**
The file should succeed compiling without asserts or crashes.

**Environment**
- Swift compiler version info: Swift version 5.9-dev (LLVM 442d36fbd7d4187, Swift 21701ace65163e8) (built from github/main 21701ace65163e8ea03ca1e299e1165f497961fb / Thu Mar 23 20:32:50 2023 -0700)
- Xcode version info: N/A
- Deployment target: Windows in this instance

### PR DESCRIPTION
**Pull request by tristanlabelle**
Fixes an out-of-bounds iterator access when providing fixits for the @available attribute.

None of the code paths in `updateLabelsForArg` should execute once we've reached the end of the `argumentLabelIDs` vector, but not all cases tested for this.

Fixes #64694

### CODE REVIEW

**Comment by compnerd** [comment]
Please add a test case for this that triggered the failure case.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test

**Review by xedin — APPROVED** [review]
LGTM! @tshortli could you take a look as well please?

**Review by tshortli — APPROVED** [review]
Looks good, thanks for the fix!

**Comment by xedin** [comment]
@swift-ci please clean test macOS platform

**Pull request merged**
