### PR TITLE
Use swift-frontend from the host for SupportedFeatures.json

### PR DESCRIPTION
**Pull request by edymtt**
Addresses rdar://71282911

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci please build toolchain

**Comment by edymtt** [comment]
@swift-ci please smoke test

**Comment by edymtt** [comment]
Follow up of #34655

**Comment by compnerd** [comment]
Hmm, Im not sure how this is supposed to work.  There are two scenarios here:
1. you are building the standard library only and you specify the `SWIFT_NATIVE_SWIFT_TOOLS_PATH`
2. you are building the Swift toolchain for testing which will build the standard library.  In such a case, `SWIFT_NATIVE_SWIFT_TOOLS_PATH` is not set, and `swift-frontend` should be used from `SWIFT_RUNTIME_OUTPUT_INTDIR`.

In fact, I would argue that the first case doesn't apply to this at all - the `SupportedFeatures.json` should be generated when generating the toolchain, so it should always be executed from the output directory.  Even in the cross-compilation case, it should be the version of the toolchain that is being built that determines the features of the toolchain, not the host toolchain that may be used in the generation of the toolchain.

Perhaps the right thing to do here is to only generate it if the toolchain is not being cross-compiled, that is:
`if(NOT CMAKE_CROSSCOMPILING)`.

**Comment by edymtt** [comment]
`SWIFT_NATIVE_SWIFT_TOOLS_PATH` is used during the compilation of the macOS toolchain -- in particular when we are cross compiling we are setting that to the host toolchain we just built (see https://github.com/apple/swift/blob/main/utils/build-script-impl#L1791), which should be what we want.

This target seems only run if we are building `bin\swift-frontend`, so the change should not affect building the stdlib only

**Comment by edymtt** [comment]
@swift-ci please test Windows

**Comment by edymtt** [comment]
@swift-ci please test stdlib with toolchain

**Comment by compnerd** [comment]
> This target seems only run if we are building `bin/swift-frontend`, so the change should not affect building only the standard library

Thats what I had assumed and hence why I had said
>> I would argue that the first case doesn't apply to this at all - the SupportedFeatures.json should be generated when generating the toolchain

This code path is specific to building the toolchain.  But, I wanted to verify that the assumption was correct.  It seems that it is.

> `SWIFT_NATIVE_SWIFT_TOOLS_PATH` is used during the compilation of the macOS toolchain -- in particular when we are cross compiling we are setting that to the host toolchain we just built (see https://github.com/apple/swift/blob/main/utils/build-script-impl#L1791), which should be what we want.

This is where I think that the problem actually is.

>> Perhaps the right thing to do here is to only generate it if the toolchain is not being cross-compiled, that is:
if(NOT CMAKE_CROSSCOMPILING).

AIUI, the features are meant to be the features of the toolchain being built, not the features with which the toolchain was built.  This means that we need to run the binary that is being generated.  This requires that we are not cross-compiling.  In the case that we are cross-compiling, we have no good way to ensure that the toolchain was built at the same revision and same configuration (configuration can impact the feature set in theory).

**Comment by edymtt** [comment]
Sorry for not understanding your point in the first place -- I based my fix on a similar issue (https://github.com/apple/swift/pull/33402) without realizing that in this case that the role of the executable itself is more relevant.

**Comment by buttaface** [comment]
Just a note about this point,
```
you are building the Swift toolchain for testing which will build the standard library.
In such a case, SWIFT_NATIVE_SWIFT_TOOLS_PATH is not set
```
[Even if `SWIFT_NATIVE_SWIFT_TOOLS_PATH` is not externally passed in by CMake, it is internally defined and used](https://github.com/apple/swift/blob/6387a7b3ae58096a027a08f1e49ca9d149a808dc/CMakeLists.txt#L513), so it has always been set to something and can be used for invocations like this. I don't know about features.json, so not saying anything about the overall pull.

**Review by nkcsgexi — CHANGES_REQUESTED** [review]
This won't work because we intend to use the just-built compiler to emit this file.

**Comment by edymtt** [comment]
Thanks everyone for the feedback!

Closing this for the sake of clarity.

**Pull request closed without merging**
