### PR TITLE
[cxx-interop] Remove redundant condition for invoking move ctor

### PR DESCRIPTION
**Pull request by Xazax-hun**
There is no reason to require a body for move/copy ctors to use them.

### CODE REVIEW

**Comment by Xazax-hun** [comment]
@swift-ci please smoke test

**Review by compnerd — APPROVED** [review]
This is fine to merge, but I wonder if we should just delete the line that follows as it is already commented out. Or was the radar related to the deleted ctor?

**Comment by Xazax-hun** [comment]
The rdar was about uncommenting the commented out line but did not provide any context what is blocking us from doing that.

**Comment by rjmccall** [comment]
Okay. Note that you do still have that line in the code about move constructors, and it's weird to be using different rules for them.

I was hoping the explanatory comment was going to be something like "There's a bug in how we interact with the fact that C++ does blah blah blah with inline copy constructors, so don't require a body for now". If we really don't know why we had that condition in the first place, I tend to agree with Saleem that we should just remove it (in both places). Abstractly, I certainly don't see any reason why we would only look for constructors defined inline in the class, which seems to be what this condition is doing.

**Comment by Xazax-hun** [comment]
> it deserves a real comment regardless

I agree with everything you said. Unfortunately, I looked at the commit that introduced this code and the rdar that was linked but none of them provided the context why the two methods are not symmetric. 

I will give removing this call in both places a try and see if anything breaks.

**Comment by Xazax-hun** [comment]
@swift-ci please test

**Comment by Xazax-hun** [comment]
@swift-ci please test

**Comment by Xazax-hun** [comment]
@swift-ci please test

**Review by egorzhdan — APPROVED** [review]

**Pull request merged**
