### PR TITLE
[build] don't run strip for libclang_rt.tvossim.a

### PR DESCRIPTION
**Pull request by edymtt**
1) strip will fail parsing that in Xcode 13.0b1
2) that library is copied from the Xcode installation
and it is already stripped

Addresses rdar://80098850

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci please build toolchain

**Comment by edymtt** [comment]
@swift-ci please smoke test

**Comment by edymtt** [comment]
@swift-ci please build toolchain

**Comment by edymtt** [comment]
@swift-ci please smoke test

**Review by shahmishal — APPROVED** [review]

**Comment by edymtt** [comment]
@swift-ci please smoke test Linux

**Comment by edymtt** [comment]
The testing highlighted two issues
* my change was wrong
* the error does also happen with Xcode 12.3, not only with 13.0b1

After a bit more investigation, I realized this was the same issue tackled in #34361

I will be reintroducing the same solution as part of https://github.com/apple/swift/pull/38262
and closing this one

**Pull request closed without merging**
