### PR TITLE
[DO NOT MERGE][benchmarking] StringGuts: Alternate designs

### PR DESCRIPTION
**Pull request by milseman**

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please smoke benchmark

**Comment by milseman** [comment]
That's the experimental results of just storing `count` directly. Doing that will, in addition to speeding up count, simplify ARC optimization logic surrounding calls to count by eliminating the branches or failures to inline.

**Comment by milseman** [comment]
@swift-ci please smoke benchmark

**Comment by milseman** [comment]
The above was checking if, in addition to storing the count at a known place, we also store the pointer, making things like `_unmanagedContiguous` near-trivial.

**Comment by milseman** [comment]
@swift-ci please smoke benchmark

**Comment by milseman** [comment]
And the above is testing if we scrapped BridgeObject for AnyObject, effectively making it very similar to existing _StringCore. That should be a net loss (increase in complexity), but as an artifact it effectively inlines the "isValue" check into user code and is more analyzable by the current ARC optimizer.

**Comment by airspeedswift** [comment]
Closing – the good parts are incorporated into #12442 and the bad parts we're ditching.

**Pull request closed without merging**
