### PR TITLE
utils: adjust Windows build to use shared LMDB

### PR DESCRIPTION
**Pull request by compnerd**
This adjusts the build to create a shared (static) build of LMDB. Re-order the build rules, wire up the LMDB build into IndexStoreDB and SourceKit-LSP.

### CODE REVIEW

**Comment by compnerd** [comment]
Please test with following PRs:
swiftlang/swift-lmdb#6
swiftlang/indexstore-db#228
swiftlang/sourcekit-lsp#1823

@swift-ci please test Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/swiftlang/swift-lmdb/pull/6
https://github.com/swiftlang/indexstore-db/pull/228
https://github.com/swiftlang/sourcekit-lsp/pull/1823

@swift-ci please test Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/swiftlang/swift-lmdb/pull/6
https://github.com/swiftlang/indexstore-db/pull/228
https://github.com/swiftlang/sourcekit-lsp/pull/1823

@swift-ci please test Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/swiftlang/swift-lmdb/pull/6
https://github.com/swiftlang/indexstore-db/pull/228
https://github.com/swiftlang/sourcekit-lsp/pull/1823

@swift-ci please test Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/swiftlang/swift-lmdb/pull/6
https://github.com/swiftlang/indexstore-db/pull/228
https://github.com/swiftlang/sourcekit-lsp/pull/1823
https://github.com/swiftlang/sourcekit-lsp/pull/1826

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/swiftlang/swift-lmdb/pull/6
https://github.com/swiftlang/indexstore-db/pull/228
https://github.com/swiftlang/sourcekit-lsp/pull/1823

@swift-ci please test

**Comment by bnbarham** [comment]
https://github.com/swiftlang/indexstore-db/pull/228
https://github.com/swiftlang/sourcekit-lsp/pull/1823

@swift-ci please build toolchain

**Comment by matthewbastien** [comment]
swiftlang/sourcekit-lsp#1823
swiftlang/indexstore-db#228
swiftlang/swift-lmdb#10

@swift-ci please test

**Comment by matthewbastien** [comment]
swiftlang/sourcekit-lsp#1823
swiftlang/indexstore-db#228
swiftlang/swift-lmdb#10

@swift-ci please build toolchain

**Comment by matthewbastien** [comment]
swiftlang/sourcekit-lsp#1823
swiftlang/indexstore-db#228
swiftlang/swift-lmdb#10

@swift-ci Please Build Toolchain Linux Platform

**Review by bnbarham — APPROVED** [review]

**Pull request merged**
