### PR TITLE
[SourceKit] don't build libdispatch shared library twice, other than on Mac/Windows

### PR DESCRIPTION
**Pull request by finagolfin**
Reboots #30096, now disabling the extra build of libdispatch altogether. I simply disabled the install before, as I wasn't sure if some other needed libdispatch headers were also installed by this, but I checked and those are installed later anyway.

@drexin, if you can kick off the CI, let's see what fails.

### CODE REVIEW

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@buttaface what's the high level here? Why isn't this needed on these other platforms. If a specific platform doesn't support them we should special case that instead. Can you explain this to me?

**Comment by drexin** [comment]
@buttaface I think I found the actual culprit and put up a PR: https://github.com/apple/swift/pull/31048

I don't know why reverting your patch appeared to fix the problem, but I ran into it again, which made me take a closer look.

**Comment by drexin** [comment]
So I think we can revert my revert of your original PR @buttaface. Sorry for the hassle.

**Comment by buttaface** [comment]
@drexin, would you like me to submit the patch from #30096 again or can you just revert the revert?

@gottesmm, see #30096, the installed toolchain was unnecessarily installing libdispatch.so/libBlocksruntime.so twice, at least on ELF platforms based on the rpath (I haven't checked mac/Windows and don't know much about how their runtime path works, so I always left those two alone). I thought maybe even building it in libdispatch-prefix was unneeded, but maybe I missed something.

**Comment by buttaface** [comment]
Closing for #31064.

**Pull request closed without merging**
