### PR TITLE
Revert "Revert "Bump the Yams and swift-argument-parser tag for main and release/5.4""

### PR DESCRIPTION
**Pull request by shahmishal**
Reverts apple/swift#36361

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci build toolchain

**Comment by shahmishal** [comment]
Required PRs: 
https://github.com/apple/swift-package-manager/pull/3338
https://github.com/apple/swift-package-manager/pull/3339
https://github.com/apple/swift-driver/pull/534
https://github.com/apple/sourcekit-lsp/pull/374

**Comment by CodaFi** [comment]
@swift-ci test Apple Silicon macOS platform

**Comment by shahmishal** [comment]
apple/swift-package-manager#3339
apple/swift-driver#534
apple/sourcekit-lsp#374
@swift-ci test

**Comment by shahmishal** [comment]
apple/swift-package-manager#3339
apple/swift-driver#534
apple/sourcekit-lsp#374
@swift-ci test Apple Silicon

**Comment by shahmishal** [comment]
apple/swift-package-manager#3339
apple/swift-driver#534
apple/sourcekit-lsp#374
@swift-ci test Apple Silicon

**Comment by shahmishal** [comment]
@swift-ci test Linux

**Comment by shahmishal** [comment]
@swift-ci clean test Linux

**Comment by shahmishal** [comment]
@swift-ci clean test Linux

**Comment by shahmishal** [comment]
@swift-ci clean test Linux

**Comment by shahmishal** [comment]
@swift-ci test Linux

**Comment by shahmishal** [comment]
@swift-ci test Linux

**Comment by artemcm** [comment]
@swift-ci test Linux

**Comment by artemcm** [comment]
@swift-ci build toolchain

**Comment by artemcm** [comment]
@swift-ci test Apple Silicon macOS platform

**Comment by shahmishal** [comment]
https://github.com/apple/swift-xcode-playground-support/pull/54
@swift-ci test Apple Silicon macOS platform

**Comment by shahmishal** [comment]
@swift-ci test Apple Silicon macOS platform

**Comment by shahmishal** [comment]
@swift-ci test Apple Silicon macOS platform

**Comment by shahmishal** [comment]
```
11:32:01 Test Case '-[SwiftDriverTests.JobExecutorTests testDarwinBasic]' started.
11:32:01 /Users/buildnode/jenkins/workspace/swift-PR-macos-apple-silicon/branch-main/swift-driver/Sources/SwiftDriverExecution/MultiJobExecutor.swift:296: error: -[SwiftDriverTests.JobExecutorTests testDarwinBasic] : failed: caught error: "fatalError"
11:32:01 Test Case '-[SwiftDriverTests.JobExecutorTests testDarwinBasic]' failed (28.004 seconds).
11:32:01 Test Suite 'JobExecutorTests' failed at 2021-03-24 11:32:01.015.
```

**Comment by shahmishal** [comment]
@swift-ci test Apple Silicon macOS platform

**Comment by shahmishal** [comment]
@swift-ci test Apple Silicon macOS platform

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test Linux

**Comment by shahmishal** [comment]
@swift-ci test Apple Silicon macOS platform

**Comment by shahmishal** [comment]
```
11:29:44 Test Case '-[FunctionalTests.PluginTests testUseOfVendedBinaryTool]' started.
11:29:44 
/Users/buildnode/jenkins/workspace/swift-PR-macos-apple-silicon/branch-main/swiftpm/Tests/FunctionalTests/PluginTests.swift:115: error: -[FunctionalTests.PluginTests testUseOfVendedBinaryTool] : failed - terminated(1): /Users/buildnode/jenkins/workspace/swift-PR-macos-apple-silicon/branch-main/buildbot_incremental/swiftpm-macosx-arm64/arm64-apple-macosx/release/swift-build --package-path /var/folders/ld/md151_257fldz2fn_bzqb5hm0000gp/T/Miscellaneous_Plugins.1NXiPb/MyBinaryToolPlugin --configuration debug --product MyLocalTool output:
11:29:44     'MyBinaryToolPlugin' /private/var/folders/ld/md151_257fldz2fn_bzqb5hm0000gp/T/Miscellaneous_Plugins.1NXiPb/MyBinaryToolPlugin: warning: found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
11:29:44         /private/var/folders/ld/md151_257fldz2fn_bzqb5hm0000gp/T/Miscellaneous_Plugins.1NXiPb/MyBinaryToolPlugin/Sources/MyLocalTool/foo.dat
11:29:44     
11:29:44     error: running plugin script failed: signalled(signal: 5):
11:29:44     Fatal error: Error raised at top level: plugin doesn’t have access to any tool named ‘mytool’ [line 13]: file Swift/ErrorType.swift, line 200
11:29:44     
11:29:44     
11:29:44 Test Case '-[FunctionalTests.PluginTests testUseOfVendedBinaryTool]' failed (5.059 seconds).
```

**Comment by shahmishal** [comment]
@swift-ci test windows

**Comment by shahmishal** [comment]
@swift-ci build toolchain

**Comment by shahmishal** [comment]
@swift-ci test Apple Silicon macOS platform

**Pull request merged**
