### PR TITLE
[Stdlib] Move SwiftNativeNSObject to libswiftCore.

### PR DESCRIPTION
**Pull request by mikeash**
This type can be put to good use outside of the concurrency runtime. Reexport it from libswift_Concurrency so it can still be found there as well.

rdar://79352061

### CODE REVIEW

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]
Looks great, thank you!

**Pull request merged**
