### PR TITLE
[Demangle] Fix OldDemangler DependentMemberTypeName infinite loop

### PR DESCRIPTION
**Pull request by dmcyk**
- Fixes infinite loop given certain input in the `OldDemangler`
- Adds broken input test cases to the test suite

Resolves [SR-10961](https://bugs.swift.org/browse/SR-10961).

### CODE REVIEW

**Comment by dmcyk** [comment]
hey @rjmccall, would you be able to have a look at this? Or any suggestions on who would?

**Comment by jrose-apple** [comment]
@eeckstein would be the best choice, but he's not available right now. I think this is pretty safe to take, though.

@swift-ci Please smoke test

**Review by jrose-apple — APPROVED** [review]

**Comment by dmcyk** [comment]
Great, thank you! Can this be included in 5.1 as well?

**Comment by dmcyk** [comment]
Linux failure seems to be unrelated

**Comment by jrose-apple** [comment]
It seems reasonable to me to cherry-pick, sure.

@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
Thank you!

**Pull request merged**
