### PR TITLE
fix tests for FileCheck behaviour

### PR DESCRIPTION
**Pull request by compnerd**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

FileCheck does not support the combination negation.  These tests were incorrect
and silently passing rather than checking what they intended.  The changes in
the DAG tests are due to the fact that they ensure that the order is matched,
which the tests seem to not be interested in.

### CODE REVIEW

**Comment by jrose-apple** [comment]
Most of these aren't testing the same thing—they're either weaker tests, or cases where we should have been failing all along. I'm not sure if there's always a better way to fix them, but I'd want the owners of the tests to come take a look. Most of them are IDE and SourceKit, so @benlangmuir and @nkcsgexi?

**Comment by benlangmuir** [comment]
I think all of the NEXT-NOT to NOT changes would be okay, but the DAG to DAG-NOT changes indicate we need to do something else in the test, since FileCheck doesn't re-order DAGs across NOTs (which I must not have known at the time I wrote all those tests).  @compnerd, do you feel up to improving the DAG-NOT cases?  If not, feel free to just drop them from this PR and I can take a look at them later.

**Comment by compnerd** [comment]
@benlangmuir I agree that the NEXT-NOT to NEXT changes should be inconsequential.  I think I explicitly called out the DAG changes in the commit message as being somewhat less stringent.  Im happy to help improve the DAG tests, but Im not sure I know what you have in mind.  Given the nature of the change, I think that a split into two PRs may be wise.  The first one would take care of the NEXT-NOT to NEXT cases so that we can get these enabled ASAP.  A second PR can tackle the DAG-NOT changes with the improvements that you may have in mind.

**Comment by benlangmuir** [comment]
> Given the nature of the change, I think that a split into two PRs may be wise. The first one would take care of the NEXT-NOT to NEXT cases so that we can get these enabled ASAP

Yes please.

> I think I explicitly called out the DAG changes in the commit message as being somewhat less stringent. Im happy to help improve the DAG tests, but Im not sure I know what you have in mind.

For the DAG cases: I think most of these just want to check for the complete absence of something, so we could add a separate _NEGATIVE check prefix variant for those tests, and just put the NOT there. E.g.
`-// DEFAULT_ARGS_8-DAG-NOT: methodWithDefaultArgsInSub1()`

Would become
`+// DEFAULT_ARGS_8_NEGATIVE-NOT: methodWithDefaultArgsInSub1()`

plus a change to the RUN lines to run both checks.  I don't know if there's a better way to accomplish that, since it feels a bit clunky.

**Comment by compnerd** [comment]
Ill push an update to split it in a bit.  I think that there were a couple of cases where the complete negation check will fail though.

**Comment by compnerd** [comment]
Anything else that should be changed on this PR?

**Comment by benlangmuir** [comment]
@swift-ci Please test

**Comment by benlangmuir** [comment]
LGTM, I'll merge when tests pass.

**Comment by compnerd** [comment]
Seems like an unrelated failure?

**Comment by benlangmuir** [comment]
Yep!  Thanks for working on this.

**Pull request merged**
