### PR TITLE
[3.1] Emit delayed conformance diagnostics in multi-file scenarios

### PR DESCRIPTION
**Pull request by DougGregor**
The protocol conformance checker tries to delay the emission of
diagnostics related to the failure of a type to conform to a protocol
until the source file that contains the conformance is encountered, to
provide redundant diagnostics. However, if a file produced only such
delayed diagnostics, such that all diagnostics were suppressed,
invalid ASTs could slip through to later stages in the pipeline where
they would cause verification errors and crashes. This happens
generally with whole-module-optimization builds, where we are re-using
an ASTContext when typing multiple source files.

This is a narrow-ish fix to stop dropping diagnostics from one source
file to the next in whole-module-optimization builds, along with another fix to detect cases where we're suppressing an error due to a conformance-related diagnostic that will be emitted in another file and emit something.

Resolves rdar://problem/29689007.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@shahmishal , the Linux build ( https://ci.swift.org/job/swift-PR-Linux/4773/consoleFull#89513194756633f0f-8823-4f82-9a4a-0c0d97ce7760 ) timed out trying to fetch the repos

**Comment by DougGregor** [comment]
@swift-ci please test Linux

**Comment by shahmishal** [comment]
@swift-ci please test Linux

**Comment by shahmishal** [comment]
> @shahmishal , the Linux build ( https://ci.swift.org/job/swift-PR-Linux/4773/consoleFull#89513194756633f0f-8823-4f82-9a4a-0c0d97ce7760 ) timed out trying to fetch the repos

This sounds like network issue on Github servers.

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Pull request merged**
