### PR TITLE
Swift 3.0 branch cmake overlay dependencies

### PR DESCRIPTION
**Pull request by erg**
This patch explicitly lists all overlay dependencies in the cmake files and adds a script to update them thus making the build more correct.

Resolves: rdar://problem/28501090

Risk: Low, only touches cmake files and a utils/ script that does not run automatically

### CODE REVIEW

**Comment by erg** [comment]
@swift-ci Please test

**Comment by erg** [comment]
@zisko Please review.

**Comment by zisko** [comment]
Looks good to me, I'm going to run a clean build of this on a fast machine to verify.

**Comment by erg** [comment]
@swift-ci Please test

**Comment by erg** [comment]
@swift-ci Please test

**Comment by erg** [comment]
@swift-ci Please test

**Comment by erg** [comment]
@swift-ci Please test

**Comment by erg** [comment]
@swift-ci Please test OS X platform

**Pull request merged**
