### PR TITLE
build: Don't link against libatomic on Linux

### PR DESCRIPTION
**Pull request by drexin**
The dependency on libatomic was removed in 97df90fbf157b9a6f80c9854aa8b4728cb941655. This commit removes leftover cases that still link against libatomic.

### CODE REVIEW

**Comment by drexin** [comment]
@swift-ci please test

**Comment by drexin** [comment]
@compnerd Found some cases I missed in the original PR.

**Comment by drexin** [comment]
@swift-ci please test

**Comment by gottesmm** [comment]
I am fine with this. Just be careful! Make sure you do your due diligence!

**Comment by drexin** [comment]
@swift-ci please test

**Comment by drexin** [comment]
@swift-ci please test

**Comment by drexin** [comment]
@swift-ci please test

**Review by compnerd — APPROVED** [review]

**Pull request merged**
