### PR TITLE
IRGen: Support for variadic generic types with dynamic layout

### PR DESCRIPTION
**Pull request by slavapestov**
Depends on https://github.com/apple/swift/pull/64222.

You can now have a stored property whose type is a tuple containing a pack expansion type. We model the entire tuple as a single resilient blob right now, which is insufficient in the general case, but enough for now. We can fulfill shapes from the nominal metadata, which allows working with pack archetypes and pack conformances inside contexts such as the metadata completion callback where we compute the layout, and value witness functions.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by rjmccall** [comment]
By request, I finished the fixes to IRGen's type metadata fulfillment necessary to get Slava's test case working; there isn't much interesting history here, so I've just opened #64273 and closed this PR.

**Pull request closed without merging**
