### PR TITLE
[fso] Do not try to specialize pseudo-generic functions today.

### PR DESCRIPTION
**Pull request by gottesmm**
This is just fixing an assert violation. I also needed to add support for
target-sil-opt(mock-sdk: ...) so I added support to lit for that here.

<rdar://problem/62262811>

----

NOTE: I ran into a problem with target-sil-opt(mock-sdk: ). I asked @jrose-apple for some help here and will fix it once they get back to me.

### CODE REVIEW

**Comment by slavapestov** [comment]
We could specialize them though, and just drop the @pseudogeneric bit.

**Comment by gottesmm** [comment]
@slavapestov I don't want to mess with this now. If someone else wants to take it on fine. I am just fixing the bug.

**Comment by gottesmm** [comment]
[IOW, I am working down my bug queue =---(].

**Comment by gottesmm** [comment]
Also, I figured out how to do the mock-sdk thing with @jrose-apple's help. Thanks so much!

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test windows platform

**Comment by gottesmm** [comment]
@swift-ci test windows platform

**Comment by atrick** [comment]
LGTM for 5.2

**Pull request merged**
