### PR TITLE
Remove a missing dependency edge on Windows

### PR DESCRIPTION
**Pull request by CodaFi**
Unblock the Windows bots

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by CodaFi** [comment]
Alright, that got the Windows failures. Let's see is Linux is still acting up.

**Comment by CodaFi** [comment]
LLDB test timed out

@swift-ci smoke test macOS platform

**Comment by CodaFi** [comment]
Have a hunch Linux is behaving poorly because of memory corruption. Going to put up another PR that defensively copies more strings.

**Review by compnerd — APPROVED** [review]

**Comment by CodaFi** [comment]
⛵️

**Pull request merged**
