### PR TITLE
[SILOpt] Print functions during inlining.

### PR DESCRIPTION
**Pull request by nate-chandler**
Enable caller and callee to be printed as inlining runs.  The printing is filtered based on -sil-print-function/-sil-print-functions and includes finer-grained info than those do already.  The caller before (`-Xllvm -sil-print-inlining-caller-before`) and after (`-Xllvm -sil-print-inlining-caller-after`) each callee is inlined can be printed as well as the callee on its own (`-Xllvm -sil-print-inlining-callee`) as it exists when inlining occurs.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please clean test linux platform

**Review by atrick — APPROVED** [review]
I quickly scanned this. It looks good. In the past I've always traced the inlining pass itself, in addition to printing functions before/after inlining. But I think inlining deserves first-class tracing. Anything we can do to better visualize inlining is worthwhile.

**Comment by nate-chandler** [comment]
@swift-ci please test and merge

**Pull request merged**
