### PR TITLE
[Sema/SIL] InitAccessors: Support default initialization of init accessor properties

### PR DESCRIPTION
**Pull request by xedin**
- Emit default initialization of init accessor properties in user-defined initializers
- Make sure that init accessor properties take over default initialization of all stored properties listed in "initializes"
- Teach default class initializer emission (`init()`) about init accessors (even if a stored property doesn't have an initializer expression, the compiler needs to check whether init accessor property that handles it does).
- Fix a bug in DI which used incorrect field indexes for subclasses.

Resolves: rdar://112417250

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Review by jckarter — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

**Review by hborla — APPROVED** [review]

**Pull request merged**
