### PR TITLE
[Tests] NFC: Vectors are not always 128 bits

### PR DESCRIPTION
**Pull request by davezarzycki**

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test and merge

**Comment by jrose-apple** [comment]
That's not NFC, and `{{}}` in FileCheck does regex matching.

**Comment by davezarzycki** [comment]
Why is it not NFC? It is just a test, not the language, and {{}} was intentional. I was trying to get the test to pass on an 512-bit wide vector machine (i.e. 8 x i64).

**Comment by jrose-apple** [comment]
Hm. I've always taken "[Tests]" to already imply that there was no change to the language. So an NFC test change would mean that it's checking for the same things it was before.

The {{}} comment was separate; you've used something that's technically a valid regex but isn't really idiomatic. (Did You Mean™ `[248]` or `(2|4|8)` instead of `[2,4,8]`?)

**Comment by davezarzycki** [comment]
I see. I wrote "NFC" because I felt the odds of a regression in test coverage should be zero; as opposed to a nontrivial refactoring of a test which might drop coverage accidentally. I'll keep your perspective in mind in the future.

As for the regex, sure, I can make it idiomatic. Do you want a new pull request?

**Comment by jrose-apple** [comment]
Yes please! Whenever you get around to it, though; clearly it's not urgent.

**Pull request merged**
