### PR TITLE
[test][IRGen] Maybe Windows needs dso_local.

### PR DESCRIPTION
**Pull request by 3405691582**
In #33816, we forked the local_extern test omitting the check for the
extern function, because it wasn't obvious what the match was. It might
actually just be missing the dso_local annotation again for the
function. Let's try that.

### CODE REVIEW

**Comment by 3405691582** [comment]
cc @compnerd. Can you run this through Windows CI? If it works, great. If not, then I'll try something else.

**Comment by xedin** [comment]
@swift-ci please smoke test Windows platform

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
Okay, I finally have the build worked out again; Looking at this locally, yes, this looks like it was the issue.

**Review by compnerd — APPROVED** [review]

**Pull request merged**
