### PR TITLE
AccessEnforcementSelection: An @out parameter can be used

### PR DESCRIPTION
**Pull request by aschwaighofer**

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@atrick I ran into a similar pattern while working on trivial noescape closures.

AccessEnforcementSelection would run into this pattern when run over a (deserialized) function out of the standard library. The optimizer pipline was in a state where many of the  trivial noescape closures were not optimized -- while with the current pipeline they probably would have.

**Comment by aschwaighofer** [comment]
This was the function.

```
    sil public_external [serialized] @$Ss23_ContiguousArrayStorageC32_withVerbatimBridgedUnsafeBufferyqd__Sgqd__SRyyXlGKXEKlF : $@convention(method) <Element><R> (@noescape @callee_guaranteed (UnsafeBufferPointer<AnyObject>) -> (@out R, @error Error), @guaranteed _ContiguousArrayStorage<Element>) -> (@out Optional<R>, @error Error) {
    // %0                                             // users: %71, %11, %8
    // %1                                             // user: %11
    // %2                                             // users: %93, %74, %69, %60, %36
    bb0(%0 : $*Optional<R>, %1 : $@noescape @callee_guaranteed (UnsafeBufferPointer<AnyObject>) -> (@out R, @error Error), %2 : $_ContiguousArrayStorage<Element>):
      %3 = alloc_stack $Optional<R>                   // users: %9, %8, %6
      %4 = alloc_stack $Optional<R>                   // users: %7, %6, %5
      inject_enum_addr %4 : $*Optional<R>, #Optional.none!enumelt // id: %5
      copy_addr [take] %4 to [initialization] %3 : $*Optional<R> // id: %6
      dealloc_stack %4 : $*Optional<R>                // id: %7
      copy_addr [take] %3 to [initialization] %0 : $*Optional<R> // id: %8
      dealloc_stack %3 : $*Optional<R>                // id: %9
      // function_ref closure #1 in _ContiguousArrayStorage._withVerbatimBridgedUnsafeBuffer<A>(_:)
      %10 = function_ref @$Ss23_ContiguousArrayStorageC32_withVerbatimBridgedUnsafeBufferyqd__Sgqd__SRyyXlGKXEKlFyAEKXEfU_ : $@convention(thin) <τ_0_0><τ_1_0> (UnsafeBufferPointer<AnyObject>, @inout_aliasable Optional<τ_1_0>, @noescape @callee_guaranteed (UnsafeBufferPointer<AnyObject>) -> (@out τ_1_0, @error Error)) -> @error Error // user: %11
      %11 = partial_apply [callee_guaranteed] %10<Element, R>(%0, %1) : $@convention(thin) <τ_0_0><τ_1_0> (UnsafeBufferPointer<AnyObject>, @inout_aliasable Optional<τ_1_0>, @noescape @callee_guaranteed (UnsafeBufferPointer<AnyObject>) -> (@out τ_1_0, @error Error)) -> @error Error // users: %75, %70, %34, %13, %12
```

**Review by atrick — APPROVED** [review]
Thanks Arnold.

**Comment by aschwaighofer** [comment]
@swift-ci Please test source compatibility

**Pull request merged**
