### PR TITLE
[5.7] [SILOpt] Added flag to disable destroy hoisting.

### PR DESCRIPTION
**Pull request by nate-chandler**
It is on by default.  The default changes with the value of the CopyPropagation setting.  But it can still be overridden.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test macOS platform

**Review by atrick — APPROVED** [review]
👍

**Comment by nate-chandler** [comment]
@swift-ci please clean test macos platform

**Comment by nate-chandler** [comment]
@tbkka Could you approve this?

**Review by tbkka — APPROVED** [review]

**Pull request merged**
