### PR TITLE
build-script: Make `--xcode` imply `--skip-build --skip-early-swift-driver`

### LINKED ISSUE #61906: Make `--xcode` imply `--skip-build --skip-early-swift-driver`
* Make `--xcode` imply `--skip-build --skip-early-swift-driver`
* Update documentation to reflect new `--xcode` behavior

### LINKED ISSUE #61910: Make `--xcode` emit a warning about the generated projects that links out to integration with Ninja tutorial

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
Closes #61906, closes #61910

### CODE REVIEW

**Comment by AnthonyLatsis** [comment]
@swift-ci please python lint

**Review by xedin — APPROVED** [review]

**Comment by AnthonyLatsis** [comment]
@swift-ci please python lint
@swift-ci please smoke test

**Comment by AnthonyLatsis** [comment]
@swift-ci please python lint

**Comment by AnthonyLatsis** [comment]
@swift-ci please python lint

**Pull request merged**
