### PR TITLE
Sema/IRGen: Add clang decl support to `#_hasSymbol`

### PR DESCRIPTION
**Pull request by tshortli**
Update `if #_hasSymbol` diagnostics and codegen to support clang functions and Obj-C class declarations. Support for global variables requires more infrastructural changes and will be handled in a follow up. Support for direct Obj-C methods/properties will also be implemented in the future.

Resolves rdar://103408651

### CODE REVIEW

**Comment by tshortli** [comment]
@swift-ci please test

**Review by nkcsgexi — APPROVED** [review]
Cool! Can these clang decls also be handled via `respondsToSelector`?

**Comment by tshortli** [comment]
@swift-ci please test

**Comment by tshortli** [comment]
> Cool! Can these clang decls also be handled via `respondsToSelector`?

Selectors represent Obj-C methods so they can't be used to represent C functions or globals.

**Comment by nkcsgexi** [comment]
> > Cool! Can these clang decls also be handled via `respondsToSelector`?
> 
> Selectors represent Obj-C methods so they can't be used to represent C functions or globals.

Makes sense.

**Comment by tshortli** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
