### PR TITLE
[update-checkout] Remove the symlink from update-checkout because we …

### PR DESCRIPTION
**Pull request by shahmishal**
…are using llvm projects directly

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci clean test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by benrimmington** [comment]
You could also remove the [`import errno`](https://github.com/apple/swift/blob/c2be4a125a5ab83f7b40cb7d87ae4ae00739f931/utils/update_checkout/update_checkout/update_checkout.py#L14) line, which was added in #27799.

**Comment by shahmishal** [comment]
@swift-ci clean test

**Comment by shahmishal** [comment]
@swift-ci clean test

**Comment by shahmishal** [comment]
@swift-ci build toolchain

**Comment by shahmishal** [comment]
@swift-ci build toolchain

**Comment by shahmishal** [comment]
https://github.com/apple/swift-syntax/pull/180

@swift-ci test macOS

**Pull request merged**
