### PR TITLE
guard assume on executor API against task-to-thread runtimes

### PR DESCRIPTION
**Pull request by kavon**
without these guards, building for minimal runtimes will fail with errors about global actors, which aren't permitted when compiling with the task-to-thread concurrency model.

rdar://106434422

### CODE REVIEW

**Comment by kavon** [comment]
@swift-ci please smoke test

**Review by ktoso — APPROVED** [review]
Thanks, LGTM

**Comment by kavon** [comment]
https://github.com/apple/swift/pull/64202
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by kavon** [comment]
@swift-ci smoke test linux platform

**Comment by kavon** [comment]
https://github.com/apple/swift/pull/64202
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by kavon** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by kavon** [comment]
@swift-ci smoke test

**Comment by al45tair** [comment]
#64234 
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by al45tair** [comment]
https://github.com/apple/swift/pull/64234
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by al45tair** [comment]
I'm not convinced that mentioning my PR actually did anything different here. I don't see the `--swift-enable-backtracing 0` that I'd expect to see in the `build-script` step at the top.

**Review by rokhinip — APPROVED** [review]

**Pull request merged**
