### PR TITLE
Implement Hashable conformance for Tuples

### PR DESCRIPTION
**Pull request by Azoy**
The relevant commit is the last one where I implement the conformance. The rest of the commits come from https://github.com/apple/swift/pull/30142

Tests coming soon™

cc: @jckarter @rjmccall

### CODE REVIEW

**Comment by Azoy** [comment]
P.S. It feels super crazy to be able to have tuple keys for dictionaries!
```swift
var grid = [(x: Int, y: Int): String]()
grid[(x: 0, y: 0)] = "Bob"
print(grid[(x: 0, y: 0)]) // Bob
```

**Comment by milseman** [comment]
@Azoy, can you update this PR and fix the conflicts so that we can evaluate its impact on source compatibility? Could you also remove the redundant operator definitions in https://github.com/apple/swift/blob/master/stdlib/public/core/Tuple.swift.gyb?

The SE proposal mentions https://github.com/apple/swift/pull/30142 and https://github.com/apple/swift/pull/28833, but this seems to be a superset of those. I think it makes sense to just have this all on one PR so we can use CI to do source-compatibility testing. I noticed that https://github.com/apple/swift/pull/28833 does have an additional commit https://github.com/apple/swift/pull/28833/commits/7af1562f477d556cb2cf8de97d7e6d2fe90636fb, is that needed here?

Thanks

**Comment by Azoy** [comment]
@milseman In the equatable pr I asked Joe about separating the prs, so I’ve been working on that pr to solidify a design. I can pull in the comparable changes and these changes into that pr if it makes things easier for testing. I’ve been fixing conflicts and updating the implementation for equatable these past couple of days, so I’ll push those soon.

**Comment by milseman** [comment]
@Azoy great, can you CC me on the PR you decide to go off of and close the others when it's ready? Thanks

**Comment by Azoy** [comment]
This is superseded by https://github.com/apple/swift/pull/28833

**Pull request closed without merging**
