### PR TITLE
Modified code snippet in OptimizationTips.rst

### PR DESCRIPTION
**Pull request by x-0o0**
There is a minor modification. The given code snippet assigns some value to the method: `doSomething()`, but it seems that it should be just in the form of method invocation.

### CODE REVIEW

**Comment by jaesung-0o0** [comment]
@swift-ci test

**Comment by jaesung-0o0** [comment]
@swift-ci smoke test

**Comment by jaesung-0o0** [comment]
@CodaFi Could you check this PR please? I don't know who to mention since it's my first contributing.

**Review by eeckstein — APPROVED** [review]
lgtm!

**Comment by eeckstein** [comment]
@swift-ci smoke test and merge

**Pull request merged**
