### PR TITLE
[WIP][IRGen] Emit type field descriptors for imported structs

### PR DESCRIPTION
**Pull request by xedin**
Having field descriptors for imported structs helps to implement new reflection
call to retrieve field names/types.

### CODE REVIEW

**Comment by xedin** [comment]
Opaque metadata goes to reflection Builtins section, so I need to register that with `swift_registerTypeMetadata` call so it's discoverable by `_typeByMangledName`.

**Comment by jckarter** [comment]
Shouldn't the nominal type descriptor for an opaque-metadata type still end up in the RuntimeResolvableTypes array?

**Comment by xedin** [comment]
I realized that yes, it should but currently it doesn't, that's the only way to establish name -> metadata relationship...

**Comment by xedin** [comment]
@jckarter I'm kind of stuck here because I'm not sure if it's valid to look into properties of the nominal types which are being added for lazy metadata emission, it doesn't seem like the best approach. It looks like if we were to do that we'd actually pollute binary with unnecessary lazy callbacks. Another way maybe it to augment lazy metadata access function to emit lazy type metadata accessors for its fields when evaluated?

 I'm leaning towards closing this and actually leaving lazy field types accessor  for imported types, so runtime hook can use reflection for regular swift types and `getFieldType` lazy accessor for imported ones, but that would be ugly...

**Comment by xedin** [comment]
Thinking about that some more, we can't actually lazily emit metadata accessors for the fields because they require reserved global var space to hook initialization too, which means we have to actually look inside of the imported structs etc. :(

**Comment by jckarter** [comment]
It seems to me that we would end up emitting the exact same set of type metadata as we do today, since we currently force all of the field type metadata indirectly by generating the `get_field_types` hook.

**Comment by xedin** [comment]
@jckarter Finally finished this up I think, for every field it's going to invoke `getAddrOfForeignTypeMetadataCandidate` if there is a struct inside to make sure that type metadata is generated. Please take a look!

**Comment by xedin** [comment]
@swift-ci please test

**Comment by jckarter** [comment]
Looks good! Maybe add some tests for Swift structs containing fields with imported types in structural positions, e.g.:

```
struct Foo {
  var a: (ImportedTypeX, ImportedTypeY)
  var b: ImportedTypeZ?
}
```

should force `ImportedType[XYZ]` metadata to get generated too.

**Comment by xedin** [comment]
@jckarter `test/Reflection/typeref_decoding_imported.swift` does exactly that, but I wonder how can I verify that metadata itself is generated?

**Comment by jckarter** [comment]
I see. The fact that the types now show up in the dumper output (and you test for that) should be sufficient then.

**Comment by xedin** [comment]
@jckarter presence of such metadata is going to be extensively tested by https://github.com/apple/swift/pull/13926 because `swift_getFieldAt` is going to rely on it being always present, so I guess I'll hold up merging this until I get some more progress at https://github.com/apple/swift/pull/13926

**Comment by jckarter** [comment]
It shouldn't harm anything to land this first.

**Comment by xedin** [comment]
Alright :)

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
Aha! Good that I re-ran the tests, since this is impacted by changes made by @rudkx where "!" is going to generate "Optional<T>", going to change the test and merge.

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Comment by xedin** [comment]
@swift-ci please smoke test Linux platform

**Pull request merged**
