### PR TITLE
Tensorflow merge

### PR DESCRIPTION
**Pull request by pschuh**
Merging in newest changes from master.

### CODE REVIEW

**Comment by pschuh** [comment]
@swift-ci please clean test tensorflow

**Review by marcrasi — APPROVED** [review]

**Comment by pschuh** [comment]
@swift-ci please test tensorflow

**Comment by pschuh** [comment]
@swift-ci please test tensorflow

**Comment by pschuh** [comment]
@swift-ci please test tensorflow

**Comment by pschuh** [comment]
@swift-ci please test tensorflow

**Comment by pschuh** [comment]
@swift-ci please test tensorflow

**Pull request merged**
