### PR TITLE
Fix typo in PerformanceInliner

### PR DESCRIPTION
**Pull request by shajrawi**

### CODE REVIEW

**Comment by shajrawi** [comment]
@swift-ci Please smoke test and merge

**Review by gottesmm — APPROVED** [review]
LGTM. Thanks!

**Comment by shajrawi** [comment]
@swift-ci Please smoke test and merge

**Comment by shajrawi** [comment]
@swift-ci Please smoke test and merge

**Comment by shajrawi** [comment]
@swift-ci Please smoke test and merge

**Comment by shajrawi** [comment]
@swift-ci Please smoke test OS X

**Comment by shajrawi** [comment]
@swift-ci Please smoke test OS X

**Comment by shajrawi** [comment]
@swift-ci Please smoke test OS X

**Comment by shajrawi** [comment]
@swift-ci Please clean smoke test OS X

**Pull request merged**
