### PR TITLE
[Clang importer] swift_newtype'd types are bridged when their underlying type is bridged

### PR DESCRIPTION
**Pull request by DougGregor**
#### What's in this pull request?

This commit fixes a problem in the interaction between swift_wrapper/swift_newtype (SE-0033) and importing ObjC lightweight generics (SE-0057), where we would end up bringing in a bridged type in a position (i.e., a type argument to an imported ObjC generic type) where a class type is required.
#### Resolved bug number: (rdar://problem/26340353)

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

…ing types are.

A swift_wrapper/swift_newtype'd type can wrap a bridged type. In such
cases, we need to report both the unbridged type (which is the
unbridged underlying type) and the bridged type (which is the
importer-created wrapper type). This fixes a problem where Objective-C
generic specializations would use the wrapper types on type parameters
with "AnyObject" constraints, which... doesn't work.

Fixes rdar://problem/26340353.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
I'm certain that wasn't me, but let's try again...

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by tkremenek** [comment]
@swift-ci smoke test os x platform

**Pull request merged**
