### PR TITLE
[Sema] NFC - Make #15419 work with weak vars

### PR DESCRIPTION
**Pull request by davezarzycki**
This extends the tuple liternal type checking optimization to handle weak variables.

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by rudkx** [comment]
I don't think this makes sense. `weak` can only be used on class and class-bound protocol types.

**Comment by davezarzycki** [comment]
Can you elaborate? The validation test suite passes on my Linux box.

**Comment by davezarzycki** [comment]
I think I get it now, the #15419 optimization doesn't optimize anything if the expression is not a tuple/dictionary/array literal, and weak variables will never be tuple/array/dictionary literals.

I guess this pull request is superficial. Do you find the resulting code to be prettier? Or would you rather have two switch statements?

**Comment by rudkx** [comment]
Oh sorry, I just meant that it wouldn't be legal code.

Compiling:

```
class C {}
weak var x = (C(), C())
```

Results in:

```
/tmp/weak.swift:2:10: error: 'weak' may only be applied to class and class-bound protocol types, not '(C, C)'
weak var x = (C(), C())
```

I had originally tried to make this work, as well as things with `inout` on the RHS, and all forms of nested patterns. It would be nice to get the latter working.

Now having said that, it would produce a diagnostic faster (or at all the the case of expressions where we would otherwise bail out with "expression was too complex").

When I had a similar change I wasn't really able to convince myself that it was actually correct, though, since the RHS might be inferred to be an optional as well, so whether you're wrapping it in another optional or not really shouldn't depend on whether we knew we had an optional on the RHS before the type checker runs.

**Comment by rudkx** [comment]
> And what about weak var (x,y,z) = (a,b,c)? Won't the optimization kick in then?

That's a tuple pattern, which already recursively decomposes the elements (see `PatternKind::Tuple` father down).

**Comment by davezarzycki** [comment]
Oh, duh, yes you're right about tuple patterns. As for weak variables, they're kind of gross. They intentionally let this work, which is why this pull request does what it does:

```
class C {}
let c = C()
let oc : C? = c
weak var w1 = c
weak var w2 = oc
```

Are faster weak diagnostics worth it?

**Comment by rudkx** [comment]
> Are faster weak diagnostics worth it?

Probably not worth the effort. We've only had the exponential tuple type checking issue reported a few times. I happened to be looking into exponential cases involving arrays and dictionaries and noticed that the tuple case was pretty easy to fix for the simple pattern kinds, so I did that, and then spent way too much time trying to generalize it :).

**Comment by davezarzycki** [comment]
What about bypassing the optimization in the `unowned` or `unmanaged` cases, which like `weak` can never be tuples?

**Comment by rudkx** [comment]
> What about bypassing the optimization in the unowned or unmanaged cases, which like weak can never be tuples?

I think it's fine to leave it as is, since we should report the error faster with the optimization in place.

**Comment by davezarzycki** [comment]
I get the impression that you want me to abandon this pull request then. For the record, it seems lame to me unnecessarily different logic for weak versus unowned/unmanaged, especially when the work to unify the code has already been done in this PR. Please confirm that you want me to abandon this PR. Thanks.

**Comment by slavapestov** [comment]
I think this PR is reasonable as a cleanup.

**Comment by rudkx** [comment]
@davezarzycki I'm not suggesting you abandon the PR. I'm just not sure it's worth trying to fix this case, and as I mentioned I abandoned a similar change because I couldn't convince myself it would work.

I just spent a few minutes putting together a test case, and this is the sort of thing that I think will be broken if you were to use the same type variable that appears on the RHS and then attempt to wrap that type variable in an optional: https://github.com/apple/swift/pull/15557

**Comment by davezarzycki** [comment]
I updated this PR to handle #15557.

@swift-ci please smoke test

**Comment by davezarzycki** [comment]
BTW – Whether this PR is "worth the effort" or not, good things have happened because of it. Like your test in #15557, and my understanding of this code improved too (which improved the QoI of my branch). Thanks. :-)

**Comment by rudkx** [comment]
Sure, I don’t mean to tell you how to spend your time for sure, and appreciate any efforts towards generalizing things to remove special cases. I’ll take another look at your updated code when I am in front of a keyboard again rather than on my phone.

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by davezarzycki** [comment]
Hi @rudkx – Out of respect to the tentative "make reviewing mandatory" policy discussion, can you please approve, decline, or actionably comment on this change? Thanks!

**Review by slavapestov — APPROVED** [review]

**Review by rudkx — CHANGES_REQUESTED** [review]
One request: Please add a test case showing that we are now fast when `weak` is used.

**Comment by davezarzycki** [comment]
@rudkx – I'm not familiar with performance sensitive tests. How does one show that a particular semantic scenario is "fast"?

**Comment by rudkx** [comment]
Actually I just realized that I didn't do that with my original change. Let's merge your change and then I will set up a validation test with my original test update and a new test for `weak`.

We have two mechanisms for this, neither of which is perfect. Timer-based testing, and `scale-test`-based testing. The existing tests sit under `validation-test/Sema/type_checker_perf` and I inadvertently just left the tests that I had written for these patterns in the pattern test rather than moving them over.

**Review by rudkx — APPROVED** [review]

**Comment by rudkx** [comment]
Merge at will, thanks!

**Pull request merged**
