### PR TITLE
Add SIL SinkAddressProjections utility to avoid address phis.

### PR DESCRIPTION
**Pull request by atrick**
Enable this utility during jump-threading in SimplifyCFG.

Ultimately, the SIL verifier should prevent all address-phis and we'll
need to use this utility in a few more places.

Fixes <rdar://problem/55320867> SIL verification failed: Unknown
formal access pattern: storage

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci benchmark

**Comment by atrick** [comment]
@swift-ci test source compatibility

**Review by aschwaighofer — APPROVED** [review]
LGTM

**Pull request merged**
