### PR TITLE
[Sema] Move @objc-without-Foundation checking to TypeCheckAttr

### PR DESCRIPTION
**Pull request by hamishknight**
There doesn't seem to be any reason to delay this diagnostic until after type-checking has finished any more, so run it along with the rest of attribute checking.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
@swift-ci please test Linux

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility Release

**Review by CodaFi — APPROVED** [review]

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Comment by hamishknight** [comment]
@swift-ci please test macOS

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility Debug

**Comment by hamishknight** [comment]
@swift-ci please test macOS

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility Release

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility Debug

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility Release

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility Debug

**Pull request merged**
