### PR TITLE
[DCE] Tweaked code to end borrows before destroys.

### PR DESCRIPTION
**Pull request by nate-chandler**
If a phi argument is dead and reborrowing it was dependent on some other value, that other value on which it was dependent may have already itself been deleted.  In that case, the destroy_value would have been added just before the terminator of the predecessors of the block which contained the dead phi.  So, when deciding where to insert the end_borrow, iterate backwards from the end of the block, skipping the terminator updating the insertion point every time a destroy_value instruction is encountered until we hit an instruction with a different opcode.  This ensures that no matter how many destroy_values may have been added just before the terminator, the end_borrow will preceed them.

This commit just tweaks the preexisting logic that checked for this condition.  Specifically, the previous code didn't handle the case where the block contains only a terminator and a `destroy_value`.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please clean test windows platform

**Review by atrick — APPROVED** [review]
The original code looks like it could be secretly shrinking the borrow scope, and consequently reordering destroys. Not something I expected this pass to do. It's probably ok but either merits
- a warning in the file-level pass comment that this pass shrinks scopes and reoders destroys
- or a FIXME here to make sure the scope is only hoisted over newly inserted destroys. That would require a SmallPtrSet of inserted destroy_value instructions

**Comment by nate-chandler** [comment]
@swift-ci please smoke test and merge

**Comment by nate-chandler** [comment]
@swift-ci please smoke test linux platform

**Pull request merged**
