### PR TITLE
[AutoDiff upstream] add @noDerivative to AnyFunctionType params

### PR DESCRIPTION
**Pull request by marcrasi**
Adds the `@noDerivative` attribute to `AnyFunctionType` parameters.

This attribute is used to determine which parameters a differentiable function type is differentiable with respect to, e.g. `@differentiable (Float, @noDerivative Float) -> Float` is only differentiable with respect to its first parameter.

Also adds serialization for the attribute.

This resolves TF-870.

### CODE REVIEW

**Comment by lattner** [comment]
The name `@nondiff` is a bit weird.  Was `@nondifferentiable` considered?

**Comment by lattner** [comment]
Well, that isn't right either, because it is possible differentiable but you don't want it in this case - better names still desired :)

**Review by lattner — APPROVED** [review]
this LGTM, but the name @nondiff isn't great.  For the time being, I'd suggest going with `@nondifferentiable` to align with the name inside of the compiler unless there is a better suggestion.

**Comment by marcrasi** [comment]
I discussed the naming with @dan-zheng, and we think that `@noDerivative` would be a pretty good name, because the meaning is very similar to the `@noDerivative` attribute on struct fields. For example, if you wanted to explode a struct in a function type, keeping `@noDerivative` on the corresponding fields is exactly what you need to do:

```
struct Foo {
  let a: Float
  @noDerivative let b: Float
}

let f: @differentiable (Foo) -> Float
let g: @differentiable(Float, @noDerivative Float) -> Float
```

It's already named `@nondiff` in the `tensorflow` branch, and various client code uses it, so I'm going to have to do a deprecate-then-remove thingy, but this shouldn't be too hard.

cc @rxwei for opinions.

I'll wait a bit to see if anyone disagrees before I make the code changes.

**Comment by dan-zheng** [comment]
`@noDerivative` sounds good to me!

Unifying `@noDerivative` on function parameters and [`@noDerivative` on stored properties](https://github.com/apple/swift/blob/master/docs/DifferentiableProgramming.md#synthesis-conditions) makes sense - great example showing the connection between the two.

**Comment by rxwei** [comment]
I think we should use `@noDerivative`.

**Comment by marcrasi** [comment]
I have renamed this to `@noDerivative`. I will run tests but wait until Monday to merge, to avoid causing any postsubmit CI failures over the weekend.

**Comment by marcrasi** [comment]
@swift-ci please test

**Comment by marcrasi** [comment]
@swift-ci please test

**Comment by lattner** [comment]
+1 for `@noDerivative` !

**Comment by marcrasi** [comment]
I have resolved merge conflicts, and I plan to do a test and merge soon.

**Comment by marcrasi** [comment]
@swift-ci please test and merge

**Comment by marcrasi** [comment]
@swift-ci please test and merge

**Pull request merged**
