### PR TITLE
[SILGen] Handled transforming Bridged? -> Swift.

### PR DESCRIPTION
**Pull request by nate-chandler**
Previously, the function emitCBridgedToNativeValue handled three situations around optionals:
- Bridged?, Native?
- Bridged, Native?
- Bridged, Native

Here, handling for the fourth case
- Bridged?, Native

is added.

To enable this, the number of Optional wrappings that the bridged type has that the native type does not is passed in to the function.  Then, in the portions of the function where actual transformations are done, the values are unwrapped an appropriate number of times.  Mostly that means force unwrapping N times before doing the transformation.  In the case of types that conform to _ObjectiveCBridgeable, however, it means force unwrapping the value N-1 times after doing the transformation because _ObjectiveCBridgeable._unconditionallyBridgeFromObjectiveC performs one layer of unwrapping itself.

rdar://81590807

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by jckarter** [comment]
Hm, does this defeat the special handling of null bridging for types like NSString, where we intentionally map nil to empty `""` String in this case?

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
(For cross-referencing purposes, the behavior was changed in a force-push to preserve the behavior and is tested at https://github.com/apple/swift/pull/38773/files#diff-154a8dcf6adb593e4e77f29be44041d0ccc9ef9546fd0ef6bdb56dcb51119d87R34 .)

**Pull request merged**
