### PR TITLE
Bump the Swift Version to 5.4

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by najacque** [comment]
@shahmishal I believe you also need to update test/IRGen/objc.swift

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by shahmishal** [comment]
@swift-ci please test Windows platform

**Comment by shahmishal** [comment]
@swift-ci test macOS

**Pull request merged**
