### PR TITLE
[SR-656] When invoking `swiftc -v`, link with `-v`

### PR DESCRIPTION
**Pull request by modocache**
#### Resolved bug number: ([SR-656](https://bugs.swift.org/browse/SR-656))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

A smoke test on macOS does the following:
1. Builds the compiler incrementally.
2. Builds the standard library only for macOS. Simulator standard libraries and
   device standard libraries are not built.
3. lldb is not built.
4. The test and validation-test targets are run only for macOS. The optimized
   version of these tests are not run.

A smoke test on Linux does the following:
1. Builds the compiler incrementally.
2. Builds the standard library incrementally.
3. lldb is built incrementally.
4. The swift test and validation-test targets are run. The optimized version of these
   tests are not run.
5. lldb is tested.

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by modocache** [comment]
@swift-ci please test

**Comment by jtbandes** [comment]
@swift-ci clean test macOS

**Comment by jtbandes** [comment]
@swift-ci smoke test macOS

**Comment by compnerd** [comment]
This is an odd behavior.  It also is contrary to how C/C++ compilers behave.  Furthermore, you also break usage with non-GNU-esque linkers.  There is no `-v` or `/v` option for link.  It is spelt `/verbose`.  And it is a hybrid of a few different options, so its extremely verbose.  I don't think that this is a good thing to add here.  If you want to invoke the linker in verbose mode, you can explicitly request it.

**Comment by modocache** [comment]
Ah, too bad. When you say it "is contrary to how C/C++ compilers behave", do you mean that the original feature request in [SR-656](https://bugs.swift.org/browse/SR-656) is contradictory as well? If so, I'll see about getting that bug report closed instead of adding this code.

**Comment by jrose-apple** [comment]
The original bug wasn't actually requesting `-v` to be passed to the linker, either; it wants it passed to the Clang invocation used to invoke the linker on GenericUnix platforms. We don't currently have a way to pass arguments to that invocation, so I could still see this being useful.

**Comment by compnerd** [comment]
@jrose-apple doesnt `-Xlinker` to the frontend let you do just that though?  The behavior would differ on targets that don't use a gcc-like driver and we dispatch to the driver.

**Comment by jrose-apple** [comment]
`-Xlinker` forwards all the way through to the linker, i.e. on platforms where we use Clang to link, we pass the arguments through with `-Xlinker`. I'm not sure if that's better or worse.

**Comment by modocache** [comment]
I'm giving up on this for now, but may revisit in the future. Thanks for the feedback!

**Pull request closed without merging**
