### PR TITLE
Update typeref_decoding_asan.swift

### PR DESCRIPTION
**Pull request by sarveshtamba**
Update 'typeref_decoding_asan.swift' as a result of SR-10341 on ppc64le.

### CODE REVIEW

**Comment by sarveshtamba** [comment]
@compnerd @dcci Please review and approve.

**Comment by compnerd** [comment]
I think that you should do a bit more investigation into why this is failing.  This is trying to construct a string from a `NUL` value which is incorrect.  The question is what is that string and why is it being constructed in an invalid way.

**Comment by sarveshtamba** [comment]
Hi @compnerd 

I have built swift toolchain in release mode as debug build runs out of space (needs more than 80GB space and 6 hrs of build time).
However I did manage to debug to a certain extent using print statements in file ReflectionContext.h and this is what I found:-

- The code flow crashes while accessing 'StrTab' variable at the following statement while constructing std::string in file 'ReflectionContext.h:455' inside "function bool readELFSections(RemoteAddress ImageStart)":-
	**auto SecName = std::string(StrTab + Offset);**

- Following is the error thrown:-		
	terminate called after throwing an instance of 'std::logic_error'
	  what():  basic_string::_M_construct null not valid		

- I tried printing the value of StrTab, however as expected, it crashes at that step too.
- "StrTabBuf.get()" which is used to construct variable 'StrTab' prints 0

Can anyone explain what this piece of code is trying to do? I tried going through the code in the stack trace, however I am not well versed with the finer details of the code and will require help from swift community. Anyone you could point me to who can guide me on this and help fix this issue?

**Comment by compnerd** [comment]
It is just reading the image.  The string table should be present in the binary.  I would try to figure out why that is missing.

**Comment by sarveshtamba** [comment]
> It is just reading the image. The string table should be present in the binary. I would try to figure out why that is missing.

Thanks @compnerd , please do let me know.

**Comment by compnerd** [comment]
I meant that you should try to figure out why `StrTab` is 0.  This unfortunately requires the build output to diagnose.

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by CodaFi** [comment]
I'm going to close this out due to age and inactivity. The PR's contents appear to have changed significantly as well.

**Pull request closed without merging**
