### PR TITLE
Merge main into rebranch - 2021-07-16

### PR DESCRIPTION
**Pull request by edymtt**
Conflicts:
            lib/IRGen/IRGenFunction.cpp
        Take the changes made in #38386

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci please smoke test

**Comment by edymtt** [comment]
The failures are due to `apple/stable/20210716` not fully merged into `swift/rebranch` llvm branch

**Comment by edymtt** [comment]
Trying the same merge for next #38435 to see if I get some signal

**Comment by edymtt** [comment]
No luck with next, merging as is to allow the llvm automerger to make progress.

**Comment by etcwilde** [comment]
Yeah, it looks like the issue is in `instance.getTarget().adjust(clangDiags, instance.getLangOpts());`. So apparently the clang `TargetInfo::adjust` function hasn't received the update to take two args. Should be fine.

**Pull request merged**
