### PR TITLE
Test and Fix: subset and superset for empty character set

### PR DESCRIPTION
**Pull request by MuhammadAnnaqeeb**
1- add tests for subset and superset for empty character set
2- fix runtime crash of 
```
CharacterSet(charactersIn: "ab").isSuperset(of: CharacterSet())
```
3- fix return value of
```
CharacterSet().isSuperset(of: CharacterSet())
```
expected value is true, currently returned value is false

### CODE REVIEW

**Comment by MuhammadAnnaqeeb** [comment]
@swift-ci Please smoke test

**Comment by gparker42** [comment]
Good catch. Can you add tests for the two false comparisons? (`emptySet.isSuperset(of: immutableSet`) and `immutableSet.isSubset(of: emptySet)`)

**Comment by MuhammadAnnaqeeb** [comment]
Thank you for your kind words.

**Comment by gparker42** [comment]
@swift-ci Please smoke test

**Comment by gparker42** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
I'm not sure this is the right fix. Why would just this one API be broken? cc @phausler

**Comment by phausler** [comment]
I would guess this is not the only one broken here; most likely there are other cases that will fail too - my guess is actually it has to do with the secondary character set being passed across. So `formUnionWithCharacterSet:` or `formIntersectionWithCharacterSet:` might be broken too

**Comment by gparker42** [comment]
The new test is also failing (runtime segfault) on the resilience bot. Did it uncover a resilience bug?

**Comment by gparker42** [comment]
New test also segfaulted on watchOS simulator. I assume we have unresolved CharacterSet bugs somewhere. I'll revert this change and file bug reports for now.

**Comment by gparker42** [comment]
Filed rdar://29474937. We'll revisit this once the bug is fixed.

**Comment by gparker42** [comment]
Filed https://bugs.swift.org/browse/SR-3311 for the incorrect empty set behavior that this change was trying to fix. @jrose-apple and @phausler, if you suspect other empty set problems then please follow up there.

**Comment by MuhammadAnnaqeeb** [comment]
I added tests for the resilience bug, so as to force the bug to appear in every testing causing runtime error. I also added tests for 3 other functions : isStrictSubset() and isStrictSuperset() and equality operator . Current file is at : https://github.com/MuhammadAnnaqeeb/swift/blob/master/test/stdlib/TestCharacterSet.swift   Please  reopen this Pull Request just for enough period to run tests. I only want to see if the tests would now constantly fails.

**Comment by jrose-apple** [comment]
I don't think we can re-open a PR that was merged and then reverted. Can you make a new one?

**Comment by MuhammadAnnaqeeb** [comment]
OK, I will open another PR.

**Pull request merged**
