### PR TITLE
Add a new SourceFileKind and InputFileKind for textual interfaces

### PR DESCRIPTION
**Pull request by jrose-apple**
And test this by tweaking the rules to allow functions without definitions, like SIL files.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Review by harlanhaskins — APPROVED** [review]

**Comment by harlanhaskins** [comment]
Minor nitpick: Do you think there's any chance that someone may confuse `InputFileKind::LLVM` for Bitcode now that the IR suffix is gone?

**Comment by jrose-apple** [comment]
I checked and we're *already* using that value when someone passes in a .bc file, so that'd actually be just fine.

**Comment by harlanhaskins** [comment]
Sounds good, then!

**Pull request merged**
