### PR TITLE
[DNM] Perf Improvements for Evaluator Dependencies

### PR DESCRIPTION
**Pull request by CodaFi**

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci test compiler performance

**Comment by CodaFi** [comment]
@swift-ci test compiler performance

**Comment by CodaFi** [comment]
@swift-ci test compiler performance

**Comment by CodaFi** [comment]
@swift-ci test compiler performance

**Comment by CodaFi** [comment]
@swift-ci test compiler performance

**Comment by artemcm** [comment]
@swift-ci test compiler performance

**Pull request closed without merging**
