### PR TITLE
[cxx-interop] Avoid a ClangImporter dependency on Sema

### PR DESCRIPTION
**Pull request by egorzhdan**
My recent change started linking ClangImporter with Sema, which accidentally introduced a circular dependency between the two.

This patch avoid the usage of type checker logic from ClangImporter's automatic protocol conformance logic.

rdar://101763817

### CODE REVIEW

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Review by tshortli — APPROVED** [review]
Thanks!

**Review by hyp — APPROVED** [review]

**Comment by tshortli** [comment]
Looks like undoing this cycle exposed more code that was inadvertently depending on the dependency cycles (which is not surprising, I've been wading through a lot of this throughout the project). I'll look into fixing these to unblock you:

```
lib/libswiftSILGen.a(SILGen.cpp.o):SILGen.cpp:function swift::ASTLoweringRequest::evaluate(swift::Evaluator&, swift::ASTLoweringDescriptor) const: error: undefined reference to 'swift::SerializedSILLoader::getAllForModule(swift::Identifier, swift::FileUnit*)'
lib/libswiftSIL.a(SILModule.cpp.o):SILModule.cpp:function swift::SILModule::~SILModule(): error: undefined reference to 'swift::SerializedSILLoader::~SerializedSILLoader()'
lib/libswiftSIL.a(SILModule.cpp.o):SILModule.cpp:function swift::SILModule::lookUpDefaultWitnessTable(swift::ProtocolDecl const*, bool): error: undefined reference to 'swift::SerializedSILLoader::lookupDefaultWitnessTable(swift::SILDefaultWitnessTable*)'
lib/libswiftSIL.a(SILModule.cpp.o):SILModule.cpp:function swift::SILModule::getSILLoader(): error: undefined reference to 'swift::SerializedSILLoader::SerializedSILLoader(swift::ASTContext&, swift::SILModule*, swift::DeserializationNotificationHandlerSet*)'
lib/libswiftSIL.a(SILModule.cpp.o):SILModule.cpp:function swift::SILModule::getSILLoader(): error: undefined reference to 'swift::SerializedSILLoader::~SerializedSILLoader()'
lib/libswiftSIL.a(SILModule.cpp.o):SILModule.cpp:function swift::SILModule::deleteWitnessTable(swift::SILWitnessTable*): error: undefined reference to 'swift::SerializedSILLoader::invalidateWitnessTable(swift::SILWitnessTable*)'
lib/libswiftSIL.a(SILModule.cpp.o):SILModule.cpp:function swift::SILModule::loadFunction(swift::SILFunction*, swift::SILModule::LinkingMode): error: undefined reference to 'swift::SerializedSILLoader::lookupSILFunction(swift::SILFunction*, bool)'
lib/libswiftSIL.a(SILModule.cpp.o):SILModule.cpp:function swift::SILModule::loadFunction(llvm::StringRef, swift::SILModule::LinkingMode, llvm::Optional<swift::SILLinkage>): error: undefined reference to 'swift::SerializedSILLoader::lookupSILFunction(llvm::StringRef, llvm::Optional<swift::SILLinkage>)'
lib/libswiftSIL.a(SILModule.cpp.o):SILModule.cpp:function swift::SILModule::updateFunctionLinkage(swift::SILFunction*): error: undefined reference to 'swift::SerializedSILLoader::lookupSILFunction(swift::SILFunction*, bool)'
lib/libswiftSIL.a(SILModule.cpp.o):SILModule.cpp:function swift::SILModule::hasFunction(llvm::StringRef): error: undefined reference to 'swift::SerializedSILLoader::hasSILFunction(llvm::StringRef, llvm::Optional<swift::SILLinkage>)'
lib/libswiftSIL.a(SILModule.cpp.o):SILModule.cpp:function swift::SILModule::invalidateSILLoaderCaches(): error: undefined reference to 'swift::SerializedSILLoader::invalidateAllCaches()'
lib/libswiftSIL.a(SILModule.cpp.o):SILModule.cpp:function swift::SILModule::invalidateFunctionInSILCache(swift::SILFunction*): error: undefined reference to 'swift::SerializedSILLoader::invalidateFunction(swift::SILFunction*)'
lib/libswiftSIL.a(SILModule.cpp.o):SILModule.cpp:function swift::SILModule::eraseGlobalVariable(swift::SILGlobalVariable*): error: undefined reference to 'swift::SerializedSILLoader::invalidateGlobalVariable(swift::SILGlobalVariable*)'
lib/libswiftSIL.a(SILModule.cpp.o):SILModule.cpp:function swift::SILModule::lookUpVTable(swift::ClassDecl const*, bool): error: undefined reference to 'swift::SerializedSILLoader::lookupVTable(swift::ClassDecl const*)'
lib/libswiftSIL.a(SILModule.cpp.o):SILModule.cpp:function swift::SILModule::lookUpMoveOnlyDeinit(swift::NominalTypeDecl const*, bool): error: undefined reference to 'swift::SerializedSILLoader::lookupMoveOnlyDeinit(swift::NominalTypeDecl const*)'
lib/libswiftSIL.a(SILModule.cpp.o):SILModule.cpp:function swift::SILModule::loadDifferentiabilityWitness(swift::SILDifferentiabilityWitness*): error: undefined reference to 'swift::SerializedSILLoader::lookupDifferentiabilityWitness(swift::SILDifferentiabilityWitnessKey)'
lib/libswiftSIL.a(Linker.cpp.o):Linker.cpp:function swift::SILLinkerVisitor::deserializeAndPushToWorklist(swift::SILFunction*): error: undefined reference to 'swift::SerializedSILLoader::lookupSILFunction(swift::SILFunction*, bool)'
lib/libswiftSIL.a(Linker.cpp.o):Linker.cpp:function swift::SILLinkerVisitor::visitProtocolConformance(swift::ProtocolConformanceRef): error: undefined reference to 'swift::SerializedSILLoader::lookupWitnessTable(swift::SILWitnessTable*)'
```

**Comment by tshortli** [comment]
> Looks like undoing this cycle exposed more code that was inadvertently depending on the dependency cycles

Ok, I looked at the issues and I think they're all simple to resolve, we just need to add explicit dependency edges from both `SILGen` and `SIL` to `Serialization`. I think it would make sense to add those edges in this PR.

**Comment by egorzhdan** [comment]
Thanks @tshortli! Let me reproduce and fix this locally.

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Review by zoecarver — APPROVED** [review]
This LGTM.

For posterity: I feel like the layering violation here is on Sema. Sema should only depend on `ClangModuleUnit`, not the `ClangImporter` itself.

**Comment by tshortli** [comment]
New Linux linking failure:
```
lib/libswiftSIL.a(DynamicCasts.cpp.o):DynamicCasts.cpp:function classifyDynamicCastToProtocol(swift::ModuleDecl*, swift::CanType, swift::CanType, bool): error: undefined reference to 'swift::ModuleDecl::conformsToProtocol(swift::Type, swift::ProtocolDecl*)'
```

Looks like `SIL` is missing an edge to `Sema`.

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Pull request merged**
