### PR TITLE
Avoid doing an aggregate store to initialize the block header

### PR DESCRIPTION
**Pull request by rjmccall**

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please smoke test and merge.

**Comment by jrose-apple** [comment]
Out of curiosity, why is the aggregate store a problem?

**Comment by rjmccall** [comment]
It usually takes the backend out of fast paths, like fast isel.  It's also hard to maintain — anything that we might want to do that requires any of the initializers to be non-constant, or wants to do something with one of the field addresses besides just store into it, would require exactly this rewrite.

**Comment by jrose-apple** [comment]
Thanks for the explanation.

**Pull request merged**
