### PR TITLE
[5.3] @main: Attribute to add an entry point to a type.

### PR DESCRIPTION
**Pull request by nate-chandler**
Here a new attribute @main is added. The type or extension that it is added to must have a static function () -> Void or () throws -> Void visible from the attribute. If it does, that function will be called at process launch. The same restrictions that apply to the existing @UIApplicationMain and @NSApplicationMain apply to the new attribute as well.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by natecook1000** [comment]
@swift-ci Please test Windows platform

**Comment by nate-chandler** [comment]
@swift-ci please test os x platform

**Comment by nate-chandler** [comment]
@swift-ci please test os x platform

**Comment by nate-chandler** [comment]
@swift-ci please test windows platform

**Pull request merged**
