### PR TITLE
[AST] NFC: Make 'isSelfExpr()' available for general use

### PR DESCRIPTION
**Pull request by davezarzycki**

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by davezarzycki** [comment]
The Linux failure looks spurious.

@swift-ci please smoke test linux

**Comment by davezarzycki** [comment]
I updated the patch to optionally look through `DerivedToBaseExpr` too, which my code needs.

@swift-ci please smoke test

**Comment by davezarzycki** [comment]
Ping

**Review by xedin — APPROVED** [review]
LGTM! I'm just wondering though what are other usages for this new method?

**Comment by davezarzycki** [comment]
Thanks @xedin. I'm researching an atomicity/reentrancy/concurrency model, and I need a method like this.

**Comment by xedin** [comment]
Good to know, @davezarzycki !

**Pull request merged**
