### PR TITLE
Various refactorings for __owned.

### PR DESCRIPTION
**Pull request by huonw**
Various problems I noticed, along with a rename, to reflect the two sorts of ownership, plus pulling the shared/inout bits into a unified enum, to reflect their mutual exclusivity.

### CODE REVIEW

**Review by CodaFi — APPROVED** [review]

**Comment by huonw** [comment]
@swift-ci please smoke test and merge

**Comment by huonw** [comment]
https://github.com/apple/swift/pull/14874

@swift-ci please smoke test

**Comment by huonw** [comment]
Oh, that's a bit embarrassing. Let's use the right link this time.

https://github.com/apple/swift-lldb/pull/355

@swift-ci please smoke test

**Comment by huonw** [comment]
apple/swift-lldb#355

@swift-ci please smoke test

**Comment by huonw** [comment]
apple/swift-lldb#355

@swift-ci please smoke test

**Comment by huonw** [comment]
apple/swift-lldb#355

@swift-ci please smoke test

**Comment by huonw** [comment]
apple/swift-lldb#355

@swift-ci please smoke test.

**Comment by huonw** [comment]
apple/swift-lldb#355

@swift-ci please smoke test.

**Comment by huonw** [comment]
apple/swift-lldb#355

@swift-ci please smoke test.

**Comment by huonw** [comment]
apple/swift-lldb#355

@swift-ci please smoke test.

**Comment by huonw** [comment]
apple/swift-lldb#355

@swift-ci please smoke test.

**Comment by huonw** [comment]
apple/swift-lldb#355

@swift-ci please smoke test

**Comment by huonw** [comment]
apple/swift-lldb#355

@swift-ci please smoke test

**Comment by huonw** [comment]
apple/swift-lldb#355

@swift-ci please smoke test

**Comment by huonw** [comment]
apple/swift-lldb#355

@swift-ci Please smoke test

**Comment by huonw** [comment]
apple/swift-lldb#355

@swift-ci please smoke test.

**Comment by adrian-prantl** [comment]
I'm afraid this change broke all the LLDB bots. Could you please take a look?
When renaming API, a full test might be more appropriate.

**Comment by adrian-prantl** [comment]
Note that this might block full pull request testing.

**Pull request merged**
