### PR TITLE
Optimizer: fix a crash in keypath folding

### PR DESCRIPTION
**Pull request by eeckstein**
The KeyPathProjector utility crashed for keypaths  to stored objectiveC properties.

rdar://132780588

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci test

**Review by kubamracek — APPROVED** [review]

**Comment by eeckstein** [comment]
@swift-ci test linux

**Pull request merged**
