### PR TITLE
[stdlib] Speed up char iteration on ASCII strings.

### PR DESCRIPTION
**Pull request by milseman**
By doing a fast check for CR-LF, we can speed up forwards and
backwards character iteration on ASCII strings by ~2-3x. This speedup
can be seen in the stringTests suite (previous PR).

It is done as a fast path inside of
_measureExtendedGraphemeClusterForward/Backward, which is never
inlined. Doing the fast path inline would yield even more dramatic
improvements, and might be an area for future exploration, but would
slightly pessimize non-ASCII strings due to code bloat. Additionally,
the current implementation has not been micro-optimized yet. It's
possible that more optimal code would be smaller and have less of an
impact on the general case.

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please test and benchmark

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please benchmark

**Comment by milseman** [comment]
Thank you SwiftPM for catching my bug!

@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please benchmark

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
Hold off on the merge until I can fix the perf regression

**Comment by milseman** [comment]
Alright, with that one we should be back to perf parity when non-ASCII, with the ASCII case resulting in 2-3x faster perf when walking Characters forwards and backwards.

**Comment by milseman** [comment]
@swift-ci please smoke test

**Comment by milseman** [comment]
@swift-ci please benchmark

**Comment by milseman** [comment]
@swift-ci please smoke test Linux platform

**Comment by milseman** [comment]
@swift-ci thank you

**Review by airspeedswift — APPROVED** [review]

**Pull request merged**
