### PR TITLE
[3.1] Improve compile-time performance of string interpolation

### PR DESCRIPTION
**Pull request by DougGregor**
Constraint generation for interpolated string literals was
meticulously producing a constraint system that included all of the
generated calls to `init(stringInterpolationSegment:)`. While accurate,
this is completely unnecessary (because the
`ExpressibleByStringInterpolation` protocol allows *anything* to be
interpolated) and leads to large, intertwined constraint systems
where:

(1) There are two additional type variables per string interpolation
segment, and
(2) Those type variables form a bridge between the string
interpolation's type variable and the type variables of each string
interpolation segment, and
(3) `init(stringInterpolationSegment:)` tends to be overloaded (17 overloads on `String`!)

which left each string interpolation as a large connected component
with big disjunctions.

Drop the calls to `init(stringInterpolationSegment:)` from the
constraint system. This eliminates two type
variables per segment (due to (1) going away), and breaks the bridge
described in (2), so that each string interpolation segment is
treated as an separate connected component and, therefore, will be
solved independently. The actual resolution of
`init(stringInterpolationSegment:)` overloads is pushed to the
constraint application phase, where we are only dealing with concrete
types and *much* smaller constraint systems. Still, eliminate 16 concrete-type overloads of `String.init(stringInterpolationSegment:)` in favor of 3 generic ones.

Fixes rdar://problem/29389887.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
Stack trace printing failed? Weird.

**Comment by DougGregor** [comment]
@swift-ci please test Linux

**Comment by ematejska** [comment]
@swift-ci please test Linux

**Comment by DougGregor** [comment]
We need a 3.1 cherry-pick of https://github.com/apple/swift-lldb/commit/dbb730e8ca79a468e87c49c302c31d1d0fe96f22 for this to work

**Comment by DougGregor** [comment]
@swift-ci please test Linux

**Pull request merged**
