### PR TITLE
[pruned-liveness] Implement FieldSensitiveAddressPrunedLiveness.

### PR DESCRIPTION
**Pull request by gottesmm**
This is the same algorithm as pruned liveness but assumes that one is tracking
liveness from an address and uses the same scheme as DI to track liveness as a
bit vector.

### CODE REVIEW

**Comment by gottesmm** [comment]
Not used anywhere, just slicing the larger patch down.

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci test windows platform

**Comment by gottesmm** [comment]
Windows failure is due to a CAS issue being fixed here: https://github.com/apple/llvm-project/pull/5236

**Comment by gottesmm** [comment]
@swift-ci test windows platform

**Review by atrick — APPROVED** [review]
As discussed, we'll want to split the pruned field liveness into a separate analysis and optimize the scalar liveness to avoid the block-keyed DenseMap completely.

The element numbering code should become its own standard SIL utility.

**Pull request merged**
