### PR TITLE
[Freestanding] Disable unstructured tasks.

### PR DESCRIPTION
**Pull request by nate-chandler**
Add a new task-to-thread concurrency model for use by freestanding, and disable
task creation, global actors, MainActor, and custom executors there.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by shahmishal** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by nate-chandler** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by jckarter — APPROVED** [review]

**Comment by nate-chandler** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by nate-chandler** [comment]
@swift-ci please test macos platform

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by nate-chandler** [comment]
@swift-ci please test

**Pull request merged**
