### PR TITLE
[sil] Rather than maintaining manually the textual opcode for SILInst…

### PR DESCRIPTION
**Pull request by gottesmm**
[sil] Rather than maintaining manually the textual opcode for SILInsructions, just put the name in SILNodes.def and use metaprogramming.

This is a cleanup for SILParsing/Printing. I verified that everything was
spelled correctly by taking the current parsing switch moving that into a file,
regenerating it using the .def file and then diffed them. The diff was the same.

rdar://28685236

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci Please test and merge

**Comment by gottesmm** [comment]
Made a mistake and messed up the formatting. git-clang-format HEAD^ to the rescue! Restarting the testing.

**Comment by gottesmm** [comment]
@swift-ci Please test and merge

**Comment by gottesmm** [comment]
@swift-ci Please test and merge

**Comment by gottesmm** [comment]
Failed due to a swiftpm issue.

**Comment by gottesmm** [comment]
@swift-ci Please clean test Linux platform

**Comment by gottesmm** [comment]
@shahmishal A clean build on Linux passed:

https://ci.swift.org/job/swift-PR-Linux/4163/

I think the PR is bugged.

**Comment by gottesmm** [comment]
Going to try this to see what happens.

@swift-ci Please smoke test linux platform

**Comment by eeckstein** [comment]
nice!

**Pull request merged**
