### PR TITLE
[NameLookup, ASTScope] Create lazily-parsed function body scopes.

### PR DESCRIPTION
**Pull request by davidungar**
Fixes ASTScope lookup for lazily-parsed function bodies in non-primary files.
Adds a test.
Addresses rdar://56384593
Also includes better debugging printing in a separate commit.
Suggest reviewing each commit separately.

### CODE REVIEW

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please smoke test Linux platform

**Comment by xedin** [comment]
@swift-ci please smoke test Linux platform

**Comment by compnerd** [comment]
This has subtle UB, that I'm still trying to isolate.  The `isNotAfter` does not provide a strict weak ordering, which makes it an invalid comparator.

**Comment by davidungar** [comment]
rdar://56540917

**Pull request merged**
