### PR TITLE
Updated note in case of concurrency

### LINKED ISSUE #74751: Presentation different for identical concurrency note
### Motivation

I found two situations that are recommending the same thing, but in different ways.

input 1:

```swift
var global = 42
```

diagnostics 1:

```
test.swift:1:5: error: var 'global' is not concurrency-safe because it is non-isolated global shared mutable state
1 | var global = 42
  |     |- error: var 'global' is not concurrency-safe because it is non-isolated global shared mutable state
  |     |- note: convert 'global' to a 'let' constant to make 'Sendable' shared state immutable
  |     |- note: annotate 'global' with '@MainActor' if property should only be accessed from the main actor
  |     `- note: disable concurrency-safety checks if accesses are protected by an external synchronization mechanism
2 | 
```

Highlight:

`note: annotate 'global' with '@MainActor' if property should only be accessed from the main actor`

input 2:

```swift
var global = 42

func mutate() {
    global += 1
}
```

diagnostics 2:

```
test.swift:4:5: error: main actor-isolated var 'global' can not be mutated from a non-isolated context
1 | var global = 42
  |     `- note: mutation of this var is only permitted within the actor
2 | 
3 | func mutate() {
  |      `- note: add '@MainActor' to make global function 'mutate()' part of global actor 'MainActor'
4 |     global += 1
  |     `- error: main actor-isolated var 'global' can not be mutated from a non-isolated context
5 | }
6 | 
```

highlight: `note: add '@MainActor' to make global function 'mutate()' part of global actor 'MainActor'`

### Proposed solution

I think the second note seems like its more general-purpose. But, I think including "annotate" does help.

`note: annotate 'global' with '@MainActor' if property should only be accessed from the main actor`

could become:

`note: add '@MainActor' annotation to make property 'global' part of global actor 'MainActor'`

### Alternatives considered

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by adityaanand176**
Resolves: https://github.com/swiftlang/swift/issues/74751

### CODE REVIEW

**Comment by ktoso** [comment]
you'll have to actually change implementation, not just the assertion.

**Review by ktoso — CHANGES_REQUESTED** [review]
Can't just change the test without changing implementation -- look for where the note is emitted and you'll have to change that

**Comment by AnthonyLatsis** [comment]
This issue was resolved in #75235.

**Comment by AnthonyLatsis** [comment]
@adityaanand176 Next time please ask us to assign you to the issue to avoid conflicts. See: [How do I pick something to work on?](https://github.com/swiftlang/swift/blob/a22dd98bfa1732b2b4936f11e5a426de54d0cf6f/docs/HowToGuides/FirstPullRequest.md#how-do-i-pick-something-to-work-on)

**Comment by adityaanand176** [comment]
Hey! For sure. I'm new to this, so I'm learning a lot.

**Pull request closed without merging**
