### PR TITLE
[5.3][build] specify deployment targets for compatibility libraries

### PR DESCRIPTION
**Pull request by edymtt**
This is needed in situations where the minimum deployment target is
specified in build-script -- these libraries do not to obey to that
since we need to ensure we are able to back deploy those correctly.

Addresses rdar://59249988

Explanation: ensure deployment targets for macOS back compatibility libraries is set correctly
Scope: part of build system that generates such files
Radar (and possibly SR Issue): rdar://59249988
Risk: Low -- this may affect automation testing backward compatibility for macOS
Testing: PR testing, local testing and manual inspection of toolchain

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci please test

**Comment by edymtt** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by edymtt** [comment]
This is a cherry-pick of #31473

**Comment by edymtt** [comment]
@swift-ci please nominate

Explanation: ensure deployment targets for macOS back compatibility libraries is set correctly
Scope: part of build system that generates such files
Radar (and possibly SR Issue): rdar://59249988
Risk: Low -- this may affect automation testing backward compatibility for macOS
Testing: PR testing, local testing and manual inspection of toolchain

**Review by shahmishal — APPROVED** [review]

**Pull request merged**
