### PR TITLE
[5.10][build] Move libdispatch earlier in the build so it can be used by the compiler validation suite

### PR DESCRIPTION
**Pull request by finagolfin**
Cherrypick of #65829 and #68565

__Explanation:__ The libdispatch and several concurrency tests in the validation suite were inadvertently disabled a couple years ago. This enables them again by making sure the target libdispatch is built first and using the new `dispatch-vfs-overlay.yaml` it now generates.

__Scope:__ Enabling compiler tests again

__Issue:__ #53973

__Risk:__ negative, as it is only testing more code, thus lowering risk

__Testing:__ Passes all CI on trunk for the last couple days, and I've been doing this manually on Android for years without a problem.

__Reviewer:__ @gottesmm

### CODE REVIEW

**Comment by finagolfin** [comment]
@bnbarham, please run the CI on this.

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by finagolfin** [comment]
@gottesmm, should I try to enable these for the 5.9 branch also?

**Comment by bnbarham** [comment]
> @gottesmm, should I try to enable these for the 5.9 branch also?

There should be *very* few changes going to 5.9 at this point, so probably not worth it in my mind.

**Comment by finagolfin** [comment]
> There should be very few changes going to 5.9 at this point, so probably not worth it in my mind.

@bnbarham, this changes zero behavior in the toolchain though, only slightly modifying the build order and some tests to enable several tests on the CI again. That's why I thought it might be worth it for 5.9 too, as it might catch 5.9 regressions better by having several dozen more tests run.

**Comment by finagolfin** [comment]
Pinging @tbkka, ready for review.

**Comment by finagolfin** [comment]
Ping @DougGregor, tiny pull that re-enables several tests on the linux CI.

**Comment by finagolfin** [comment]
Ping @bnbarham, can you review and merge? I didn't know you could get pulls into 5.10.

**Review by bnbarham — APPROVED** [review]

**Pull request merged**
