### PR TITLE
[AutoDiff] TF-274: Fix usefulness propagation for address-type outputs.

### PR DESCRIPTION
**Pull request by dan-zheng**
Recursively propagate usefulness for address-type outputs, instead of only
marking them as useful.

Resolves [TF-274](https://bugs.swift.org/browse/TF-274). Update tests.

### CODE REVIEW

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Review by rxwei — APPROVED** [review]

**Pull request merged**
