### PR TITLE
[udpate-checkout] Add --quiet flag

### PR DESCRIPTION
**Pull request by kastiglione**
Add a `--quiet` (and `-q`) flag to `update-checkout` to generate less terminal output.

This `--quiet` flag is currently only threaded through to the `git fetch` which is the most noisiest operation.

### CODE REVIEW

**Comment by kastiglione** [comment]
This is a proposal to get feedback before plumbing quiet mode into more places.

**Comment by gottesmm** [comment]
@kastiglione I am going to need a test for this.

**Comment by gottesmm** [comment]
@kastiglione something like this: https://github.com/apple/swift/blob/master/utils/update_checkout/tests/test_clone.py

**Comment by gottesmm** [comment]
You can also check the output if you want. The test case works by using a mock git repo that we create for each test case.

**Comment by kastiglione** [comment]
I added a test. To check the output, I modified `call_quietly` to return the contents of stdout and stderr. The changes here are compatible with python 3 only, but the Swift repo is all python 3 now, right?

**Comment by kastiglione** [comment]
After talking with Saleem, I think only the scripts invoked by CMake are python3, so this would need to support python2.

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Comment by kastiglione** [comment]
@shahmishal done

**Comment by shahmishal** [comment]
@swift-ci smoke test

**Review by shahmishal — APPROVED** [review]

**Pull request closed without merging**
