### PR TITLE
BooleanLiteralFolding: remove dead blocks

### PR DESCRIPTION
**Pull request by eeckstein**
Remove all dead blocks which are a result of constant folding conditional branches

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by asl** [comment]
Great, thanks! Will check tomorrow on my testcases.

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@kavon Can you please check if the change in the discard_checking testfile looks good? IMO it makes sense, because the `discard` is in dead code and the compiler is now "smart enough" to detect this.

**Comment by asl** [comment]
This looks ok to me! Autodiff is more robust wrt unreachable blocks as in https://github.com/apple/swift/pull/71356 Though I'm not sure it covers 100% of cases :)

**Pull request merged**
