### PR TITLE
Sema: Progress towards an improved "too complex" check

### PR DESCRIPTION
**Pull request by slavapestov**
This PR adds some statistical counters for counting trail steps, and makes improvements to the flags:
- The scope threshold was hard-coded at 1 million, now it can be set with `-Xfrontend -solver-scope-threshold=...`. Setting it to 0 disables the limit entirely.
- Passing `-Xfrontend -solver-expression-time-threshold=0` will now disable the timer, instead of setting it to 0 so it always fails.
- There is a new `-Xfrontend -solver-trail-threshold=...` flag. This is set to 64 million by default. This counts steps in the trail so it's more fine-grained than scopes. As with the other two, it can be set to 0 to disable the limit.

My goal is to disable the expression timer by default. Right now it is set to 10 minutes, so in practice 'too complex' expressions are caught by the solver memory or scope thresholds. Since `llvm::TimeRecord` class collects a lot of information, we spend a lot of CPU time just querying system calls for a pointless timer we don't need.

The trail check is almost good enough to replace the timer, except it doesn't quite replicate the behaviors of the existing timer with conjunctions and closures, so I'll look at that next.

This will address rdar://109613871 once the timer is turned off by default.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Review by xedin — APPROVED** [review]

**Pull request merged**
