### PR TITLE
Import as member

### PR DESCRIPTION
**Pull request by milseman**
#### What's in this pull request?

Implementation for SE-0044 Import as member https://github.com/apple/swift-evolution/blob/master/proposals/0044-import-as-member.md
#### Resolved bug number: ([SR-1053](https://bugs.swift.org/browse/SR-1053))

Initial implementation for SR-1053 https://bugs.swift.org/browse/SR-1053. There will continue to be a tail of fixes and tweaks, but the majority of implementation work is done.

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by milseman** [comment]
I will do another merge with master to squash these conflicts, and re-test.

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
Fixed test case changes with ToT.

@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please test and merge

**Comment by milseman** [comment]
@swift-ci  please test and merge

**Comment by DougGregor** [comment]
@swift-ci  Please test and merge

**Comment by shahmishal** [comment]
@swift-ci Please test and merge

**Comment by milseman** [comment]
Setting status of 16edcaffd27570e5eb92dea5cd3911b2af79959c to FAILURE with url https://ci.swift.org/job/swift-PR-merge/5/ and message: 'Build finished. No test results found.'

**Comment by milseman** [comment]
@swift-ci please test and merge

**Comment by milseman** [comment]
The @swift-ci failures are unrelated issues, and it's looking like they will continue to have some problems in the near term. I will test myself locally on both OS X and Linux.

**Comment by milseman** [comment]
Everything passes

**Comment by milseman** [comment]
Pass!

**Pull request merged**
