### PR TITLE
[ConstraintSystem] NFC: Extract `PotentialBinding(s)` and auxiliary types/logic into separate header and namespace

### PR DESCRIPTION
**Pull request by xedin**
- Add a new namespace - `swift::constraints::inference`
- Place all of the types and logic related to type inference into aforementioned new namespace:
  - `PotentialBinding(s)` and auxiliary types
  - `getPotentialBindingFromRelationalConstraint`, `checkTypeOfBinding` etc.
 
This is a final step in preparation to storing bindings in constraint graph nodes to
avoid re-computation.

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please clean test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Review by hborla — APPROVED** [review]
I mostly skimmed since this is largely moving code around. The removal of `simplifyType` from `checkTypeOfBinding` looks fine. LGTM!

**Pull request merged**
