### PR TITLE
[SIL] Add test case for crash triggered in swift::Parser::parseSILVTable()

### PR DESCRIPTION
**Pull request by practicalswift**
I've started fuzzing Swift SIL optimizer. This is my first crash :-)

Stack trace:

```
sil-opt: /path/to/swift/lib/Parse/ParseSIL.cpp:790: llvm::PointerUnion<ValueDecl *, Module *> lookupTopDecl(swift::Parser &, swift::Identifier): Assertion `DeclLookup.isSuccess() && DeclLookup.Results.size() == 1' failed.
9  sil-opt         0x0000000000a24740 swift::Parser::parseSILVTable() + 640
10 sil-opt         0x00000000009f38d3 swift::Parser::parseTopLevel() + 707
11 sil-opt         0x00000000009eecbb swift::parseIntoSourceFile(swift::SourceFile&, unsigned int, bool*, swift::SILParserState*, swift::PersistentParserState*, swift::DelayedParsingCallbacks*) + 107
12 sil-opt         0x0000000000738ad6 swift::CompilerInstance::performSema() + 2918
13 sil-opt         0x000000000072373c main + 1916
Stack dump:
0.  Program arguments: sil-opt -enable-sil-verify-all
1.  With parser at source location: <stdin>:2:13
```

### CODE REVIEW

**Comment by rudkx** [comment]
Can you add a newline (one and only one) at the end of the file?

**Comment by practicalswift** [comment]
@rudkx Done! :-)

**Comment by rudkx** [comment]
@practicalswift Thanks. One more small request - can you squash and push -f to the branch so that it's a single atomic commit adding the test with the newline at the end? I'll merge after.

**Comment by practicalswift** [comment]
@rudkx Done! :-)

**Comment by rudkx** [comment]
Thanks!

**Pull request merged**
