### PR TITLE
Fix RangeIteration and StringWalk benchmarks' use of globals

### PR DESCRIPTION
**Pull request by atrick**
StringWalk benchmark: remove global variable access from the loop.
    
    Global variables are being used as if they are "free black
    holes". They might be even more expensive than actually calling
    blackHole. But the right thing to do is use local variables and pass
    them into a black hole at the end of computation.

    RangeIteration benchmark: remove global variable access from the critical path.
    
    This benchmark was "accidentally" accessing a global variable in the
    main iteration loop, which is in some situations very expensive and
    has nothing to do with what the benchmark is trying to test.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci benchmark

**Comment by atrick** [comment]
@swift-ci smoke test

**Review by lorentey — APPROVED** [review]
Interesting; this was a weird pattern.

**Comment by atrick** [comment]
@swift-ci smoke test

**Review by milseman — APPROVED** [review]
LGTM

**Comment by atrick** [comment]
@swift-ci smoke test

**Comment by atrick** [comment]
@swift-ci smoke test

**Pull request merged**
