### PR TITLE
[stdlib] Fix FloatingPoint.init(exactly:)

### PR DESCRIPTION
**Pull request by natecook1000**
This initializer wasn't actually checking the exact conversion. Corrects the tests as well.

SR: https://bugs.swift.org/browse/SR-4634

### CODE REVIEW

**Comment by natecook1000** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
Build error:
```
09:30:24 stdout>>> check failed at /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/validation-test/stdlib/ValidationNSNumberBridging.swift, line 659
09:30:24 stdout>>> this code should not be executed
09:30:24 stdout>>> Optional(1.84467441e+19) != nil Float
09:30:24 stdout>>> check failed at /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/validation-test/stdlib/ValidationNSNumberBridging.swift, line 665
09:30:24 stdout>>> this code should not be executed
09:30:24 stdout>>> Optional(1.8446744073709552e+19) != nil Double
09:30:24 stdout>>> check failed at /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/validation-test/stdlib/ValidationNSNumberBridging.swift, line 659
09:30:24 stdout>>> this code should not be executed
09:30:24 stdout>>> Optional(1.84467441e+19) != nil Float
09:30:24 stdout>>> check failed at /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/validation-test/stdlib/ValidationNSNumberBridging.swift, line 665
09:30:24 stdout>>> this code should not be executed
09:30:24 stdout>>> Optional(1.8446744073709552e+19) != nil Double
09:30:24 stdout>>> check failed at /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/validation-test/stdlib/ValidationNSNumberBridging.swift, line 659
09:30:24 stdout>>> this code should not be executed
09:30:24 stdout>>> Optional(1.84467441e+19) != nil Float
09:30:24 stdout>>> check failed at /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/validation-test/stdlib/ValidationNSNumberBridging.swift, line 665
09:30:24 stdout>>> this code should not be executed
09:30:24 stdout>>> Optional(1.8446744073709552e+19) != nil Double
09:30:24 stdout>>> check failed at /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/validation-test/stdlib/ValidationNSNumberBridging.swift, line 659
09:30:24 stdout>>> this code should not be executed
09:30:24 stdout>>> Optional(1.84467441e+19) != nil Float
09:30:24 stdout>>> check failed at /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/validation-test/stdlib/ValidationNSNumberBridging.swift, line 665
09:30:24 stdout>>> this code should not be executed
09:30:24 stdout>>> Optional(1.8446744073709552e+19) != nil Double
09:30:24 [     FAIL ] NSNumberBridgingValidation.Bridge UInt
09:30:24 NSNumberBridgingValidation: Some tests failed, aborting
09:30:24 UXPASS: []
09:30:24 FAIL: ["Bridge UInt"]
```

**Comment by moiseev** [comment]
@swift-ci Please smoke benchmark

**Comment by natecook1000** [comment]
It looks like this test failure is because bridging from `NSNumber` back to `Double` calls `Double.init(exactly:)`. This used to succeed for large values like `UInt.max`, but now doesn't. I suppose we can just opt out of the `Float`/`Double` tests for values that are too large—would that be an okay fix for this? The `Int` bridging tests don't test floating point conversions at all.

**Comment by xwu** [comment]
@natecook1000 I do believe that there were some patches, at least in swift-corelibs-foundation, addressing the issue of `NSNumber` exact bridging. I'm hazy on the conclusion but it'd be unfortunate if fixing `Double.init(exactly:)` broke the agreed-upon semantics for `NSNumber` bridging.

**Comment by natecook1000** [comment]
cc @phausler

**Comment by natecook1000** [comment]
@swift-ci Please smoke test

**Review by phausler — COMMENTED** [review]
There is a second test beyond the validation btw that will need to be changed

**Comment by natecook1000** [comment]
@swift-ci Please smoke test

**Comment by natecook1000** [comment]
Please test with following pull request:
https://github.com/apple/swift-corelibs-foundation/pull/1273

@swift-ci Please smoke test Linux platform

**Comment by phausler** [comment]
Huzzah! Thanks for addressing this. Looks great to me.

**Comment by natecook1000** [comment]
Please test with following pull request:
apple/swift-corelibs-foundation#1273

@swift-ci Please smoke test Linux platform

**Comment by gparker42** [comment]
This is causing failures on 32-bit iOS simulator and on Linux. I'm reverting it and apple/swift-corelibs-foundation#1274 .

**Comment by gparker42** [comment]
Ugh, automatic revert failed. Nate, please revert this and the corresponding Foundation changes ASAP.

**Comment by gparker42** [comment]
Please test with following pull request:
apple/swift-corelibs-foundation#1276
@swift-ci please smoke test

**Comment by gparker42** [comment]
Please test with following pull request:
apple/swift-corelibs-foundation#1276
@swift-ci please smoke test

**Pull request merged**
