### PR TITLE
Make the `@Observable` macro class only

### PR DESCRIPTION
**Pull request by natecook1000**
This removes the ability for the Observable macro to apply to structs, and adds diagnostic tests for the three disallowed declaration kinds. It also adds `Codable` and `Hashable` conformance to the `ObservationRegistrar` type, in order to smooth the future direction of `@Observable` support for structs.

### CODE REVIEW

**Comment by natecook1000** [comment]
@swift-ci Please test

**Comment by natecook1000** [comment]
@swift-ci Please test

**Comment by natecook1000** [comment]
@swift-ci Please test

**Comment by natecook1000** [comment]
@swift-ci Please test macOS platform

(unrelated failure last time)

**Review by phausler — APPROVED** [review]

**Comment by natecook1000** [comment]
@swift-ci Please test macOS platform

**Comment by natecook1000** [comment]
@swift-ci Please test and merge

**Comment by natecook1000** [comment]
@swift-ci Please test macOS platform

**Comment by natecook1000** [comment]
@swift-ci Please test

**Pull request merged**
