### PR TITLE
Un-XFAIL 2 Concurrency tests on Windows

### PR DESCRIPTION
**Pull request by meg-gupta**

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Review by ktoso — APPROVED** [review]
LGTM, hopefully things work there by now? It was some issues with async code in general, not specifically those two types.

**Comment by meg-gupta** [comment]
@swift-ci smoke test macOS Platform

**Comment by meg-gupta** [comment]
Now that the lldb test is disabled. Trying testing again... @swift-ci smoke test macOS Platform

**Pull request merged**
