### PR TITLE
[SE-0081][stdlib] Apply tail style "where" clause to stdlib

### PR DESCRIPTION
**Pull request by rintaro**
#### What's in this pull request?

Follow-up on [SE-0081](https://github.com/apple/swift-evolution/blob/master/proposals/0081-move-where-expression.md) c5bf433490f4fe471584550b431695498a6adc0e
Migrate stdlib core to tail style `where` clause.
#### Resolved bug number: (Related [SR-1561](https://bugs.swift.org/browse/SR-1561))

---

Before merging this pull request to apple/swift repository:
- [x] Fix consistent code style
- [ ] Test pull request on Swift continuous integration.

### CODE REVIEW

**Comment by rintaro** [comment]
I'm wavering between dangling `where` and new line `where`:

```swift
func funcName< ... >( ... ) throws -> (Some) -> LongReturnType where
  S.Iterator.Element == Element {
  // ...
}
// OR
func funcName< ... >( ... ) throws -> (Some) -> LongReturnType
  where S.Iterator.Element == Element {
  ...
}
```

Also, Primary constraints should be in `< generic-parameter-list­­ >` or `where` clause:
```swift
func funcName<C : Collection, S : Sequence>( ... )
  where S.Iterator.Element == C.Iterator.Element {
  // ...
}
// OR
func funcName<C, S>( ... )
  where
  C : Collection,
  S : Sequence,
  S.Iterator.Element == Element {
  // ...
}
```

@gribozavr Could you give some advice?

**Comment by gribozavr** [comment]
This one feels more natural:

```swift
func funcName< ... >( ... ) throws -> (Some) -> LongReturnType
  where S.Iterator.Element == Element {
  ...
}
```

**Comment by gribozavr** [comment]
For the second question, I think it highly depends on context.

In this case I prefer the primary constraint in the brackets because the signature `init<I>(_ base: I)` is not comprehensible otherwise.

```swift
public init<I : IteratorProtocol>(_ base: I) where I.Element == Element // ✅ I like this one.

public init<I>(_ base: I) where I : IteratorProtocol, I.Element == Element // The beginning is unreadable.

public init<Source : Sequence>(_ sequence: Source) // ✅ I like this one.  (Initialize from a sequence.  Then, secondary information: what kind of sequence?  One with matching elements.)
  where Source.Iterator.Element == Element
```

Same here, but my preference is weaker (knowing the typical patterns we have in the code, you can probably infer that `Base` is the wrapped sequence even without looking at the type annotation -- but you might need to think about that):

```swift
public struct FlattenSequence<Base : Sequence> : Sequence // ✅ I like this one.
  where Base.Iterator.Element : Sequence

public struct FlattenSequence<Base> : Sequence // Not as good as above, but OK.
  where
  Base : Sequence,
  Base.Iterator.Element : Sequence
```

In this case I prefer everything at the end because (1) the collection type itself is used at the end, (2) there are fewer unrelated things between the words of the phrase "replace subrange":

```swift
  mutating func replace<C>(
    subRange: Range<Int>,
    with newCount: Int,
    elementsOf newValues: C
) where C : Collection, C.Iterator.Element == Element
```

... but such cases are in the minority.  I couldn't find a second similar one where I felt strongly about not including the constraints in `<>`.  Even splitting the phrase in `public mutating func append<S : Sequence>(contentsOf newElements: S)` does not look bad, because "append Sequence" also reads well.  But I can see this being argued both ways.

What do **you** think is more readable?

**Comment by rintaro** [comment]
> What do **you** think is more readable?

I see, the **readability** is the highest priority 👍

**Comment by rintaro** [comment]
@gribozavr Could you take a look again?

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by gribozavr** [comment]
@rintaro Thank you for working on this!  Please let me know when you would like to get this PR merged -- currently you have marked it as a WIP.

**Comment by rintaro** [comment]
I've finished self review during CI testing.
If it looks OK, please merge this :)

**Comment by gribozavr** [comment]
@rintaro Thank you!

**Pull request merged**
