### PR TITLE
[Refactoring] Merge identical cases of switch

### PR DESCRIPTION
**Pull request by valeriyvan**

### CODE REVIEW

**Review by CodaFi — COMMENTED** [review]
This diff doesn't look quite right. I think the changes to delete the ResumeThrowingContinuationReturning case didn't come through.

**Comment by valeriyvan** [comment]
> This diff doesn't look quite right. I think the changes to delete the ResumeThrowingContinuationReturning case didn't come through.

fixed

**Review by atrick — COMMENTED** [review]
LGTM

**Review by atrick — APPROVED** [review]

**Comment by valeriyvan** [comment]
ping

**Comment by AnthonyLatsis** [comment]
Can you do a rebase instead?

**Comment by valeriyvan** [comment]
> Can you do a rebase instead?

done

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Pull request merged**
