### PR TITLE
[AutoDiff] NFC: separate non-upstreamed tests.

### PR DESCRIPTION
**Pull request by dan-zheng**
Move non-upstreamed tests on `tensorflow` branch to `test/AutoDiff/downstream`.

As tests are upstreamed to `master` branch in organized `test/AutoDiff`
subdirectories, corresponding tests in `test/AutoDiff/downstream` can be
deleted from `tensorflow` branch.

This patch only moves tests without changing any of them.

Resolves TF-1098.

### CODE REVIEW

**Comment by compnerd** [comment]
@dan-zheng minor thing, what do you think of `test/AutoDiff/downstream` instead of `test/AutoDiff/nonupstreamed`?

**Comment by dan-zheng** [comment]
> @dan-zheng minor thing, what do you think of `test/AutoDiff/downstream` instead of `test/AutoDiff/nonupstreamed`?

I don't feel strongly, but I like the brevity! Renamed to `test/AutoDiff/downstream`.

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Review by marcrasi — APPROVED** [review]

**Review by rxwei — APPROVED** [review]

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Review by compnerd — APPROVED** [review]

**Pull request merged**
