### PR TITLE
Optimizer peephole for tagged BridgeObjects

### PR DESCRIPTION
**Pull request by shajrawi**
rdar://problem/35735541

BridgeObjects skip ref-counting when either of the potential tag bits are set. The optimizer can take advantage of this fact to avoid calls to the Swift runtime that effectively nop.

Peepholes:

retain(x | _objCTaggedPointerBits) => nop
release(x | _objCTaggedPointerBits) => nop

This PR includes the following:
* ValueToBridgeObject Builtin which is used in the standard library and replaces calls to reinterpret cast when dealing with tagged bits
* StringObjectOr Builtin, used in the standard library, that replaces using 'or' when tagging bits, this adds extra safety / insures no-one misused ValueToBridgeObject.
* A new peephole optimization that given a strong retain/release of tagged bridge objects.

### CODE REVIEW

**Comment by shajrawi** [comment]
@swift-ci Please test

**Comment by shajrawi** [comment]
@swift-ci Please benchmark

**Comment by shajrawi** [comment]
@swift-ci Please test OS X

**Comment by shajrawi** [comment]
The couple of regressions are just noise as far as I can tell.
I can confirm the string performance improvements (10-20%)

**Comment by eeckstein** [comment]
nice work!

**Pull request merged**
