### PR TITLE
Make the collections implementation of `indexOf` a little bit more Swift-like

### PR DESCRIPTION
**Pull request by chriseidhof**
I'm not sure if these changes are welcome. I think both of these changes are a bit more Swift-like. They remove a level of indentation (which I think is mostly a good thing).

I've checked the SIL and it seems to be exactly the same (except that the branches are swapped around).

### CODE REVIEW

**Comment by gribozavr** [comment]
Sorry, I don't think this is a readability win.  It puts two different constructs -- iteration and comparison -- on the same line.

**Comment by chriseidhof** [comment]
Okay! Even in the first case? Isn't this exactly what `where` is for? Good to know!

**Comment by gribozavr** [comment]
It is a matter of style and personal preference.  I'd be hesitant to make blanket statements about `for ... where`.

**Comment by chriseidhof** [comment]
Fair enough, thanks for explaining. In my code, I've been writing things like this, and have started to appreciate it. But I appreciate there be a consistent style throughout the stdlib, so feel free to close it! Thanks =)

**Pull request closed without merging**
