### PR TITLE
Use -[NSSet getObjects:] instead of -[NSSet getObjects:count:] to maintain compatibility with existing code passing NSArrays into this function

### PR DESCRIPTION
**Pull request by Catfish-Man**
5.2 version of https://github.com/apple/swift/pull/28817

Fixes rdar://57801853

### CODE REVIEW

**Review by lorentey — APPROVED** [review]
👍

**Review by kylemacomber — APPROVED** [review]
LGTM! Thanks for adding the [test](https://github.com/apple/swift/pull/28863)

**Comment by Catfish-Man** [comment]
@swift-ci please smoke test and merge

**Comment by Catfish-Man** [comment]
@swift-ci please test and merge

**Pull request merged**
