### PR TITLE
Convert var to let with default value

### PR DESCRIPTION
**Pull request by frootloops**
I expect It could works faster than previous version. Is it true?

### CODE REVIEW

**Comment by nadavrot** [comment]
@frootloops There are two ways to find out. First, you can inspect the SIL. And second, you can write a benchmark.

**Comment by frootloops** [comment]
@nadavrot  As I understand it: The compiler transform `let startIndex: Index =  0` to 
```
public init(count: Int, repeatedValue: Element) {
     // ....
     self. startIndex = 0 // implicit 
   }
```

SIL:
```
// Repeat.Repeat.init <A> (Repeat.Repeat<A>.Type)(count : Swift.Int, repeatedValue : A) -> Repeat.Repeat<A>
sil @_TFV6Repeat6RepeatCurfMGS0_q__FT5countSi13repeatedValueq__GS0_q__ : $@convention(thin) <Element> (@out Repeat<Element>, Int, @in Element, @thin Repeat<Element>.Type) -> () {
bb0(%0 : $*Repeat<Element>, %1 : $Int, %2 : $*Element, %3 : $@thin Repeat<Element>.Type):
  %4 = alloc_stack $Repeat<Element>  // var self  // users: %9, %11, %13, %15, %16, %18
  debug_value %1 : $Int  // let count             // id: %5
  debug_value_addr %2 : $*Element  // let repeatedValue // id: %6
  %7 = integer_literal $Builtin.Int64, 0          // user: %8 <- startIndex value
  %8 = struct $Int (%7 : $Builtin.Int64)          // user: %10
  %9 = struct_element_addr %4#1 : $*Repeat<Element>, #Repeat.startIndex // user: %10
  store %8 to %9 : $*Int                          // id: %10
  %11 = struct_element_addr %4#1 : $*Repeat<Element>, #Repeat.count // user: %12
  store %1 to %11 : $*Int                         // id: %12
  %13 = struct_element_addr %4#1 : $*Repeat<Element>, #Repeat.repeatedValue // user: %14
  copy_addr [take] %2 to [initialization] %13 : $*Element // id: %14
  copy_addr %4#1 to [initialization] %0 : $*Repeat<Element> // id: %15
  destroy_addr %4#1 : $*Repeat<Element>           // id: %16
  %17 = tuple ()                                  // user: %19
  dealloc_stack %4#0 : $*@local_storage Repeat<Element> // id: %18
  return %17 : $()                                // id: %19
}
```

And then just read the value from a memory:

```
// Repeat.Repeat.startIndex.getter : Swift.Int
sil [transparent] [fragile] @_TFV6Repeat6Repeatg10startIndexSi : $@convention(method) <Element> (@in_guaranteed Repeat<Element>) -> Int {
bb0(%0 : $*Repeat<Element>):
  debug_value_addr %0 : $*Repeat<Element>  // let self // id: %1
  %2 = struct_element_addr %0 : $*Repeat<Element>, #Repeat.startIndex // user: %3
  %3 = load %2 : $*Int                            // user: %4
  return %3 : $Int                                // id: %4
}
```

The previous version always creates and returns a new value:

```
// Repeat.Repeat.startIndex.getter : Swift.Int
sil @_TFV6Repeat6Repeatg10startIndexSi : $@convention(method) <Element> (@in_guaranteed Repeat<Element>) -> Int {
bb0(%0 : $*Repeat<Element>):
  %1 = integer_literal $Builtin.Int64, 0          // user: %2
  %2 = struct $Int (%1 : $Builtin.Int64)          // user: %3
  return %2 : $Int                                // id: %3
}
```

So my solution better in the case of frequent reading but it uses more memory. And  it looks like we don't use `startIndex` at all. So...

**Comment by gribozavr** [comment]
`let` is a stored variable currently.  `var` can be computed.  Also, `let` provides additional guarantees, as compared to `var`.

I think until we would be able to make `let`s without storage, the current approach is the best.

**Comment by gribozavr** [comment]
@frootloops Please factor out the test into a separate PR though!

**Pull request closed without merging**
