### PR TITLE
[NFC] Re-alphabetize underscored attributes reference

### PR DESCRIPTION
**Pull request by xwu**
The introductory material says that we're alphabetizing, so let's make sure we stick with it!

### CODE REVIEW

**Comment by xwu** [comment]
@swift-ci smoke test

**Comment by xwu** [comment]
Hi @typesanitizer, can you point me to who might have oversight over these docs nowadays? Just want to make sure I ping them for awareness.

**Comment by typesanitizer** [comment]
Sorry, I don't know; you could ask in the forums or look at `git log -- docs` in case you didn't already. Generally, it should be OK to have someone with some contribution experience + some edits to the same/related files sign off, unless something has changed recently.

**Comment by xwu** [comment]
Thanks. Let's see if @gottesmm would know as a recent contributor to this file...

**Pull request merged**
