### PR TITLE
Introduce Builtin.bindMemory and SIL bind_memory.

### PR DESCRIPTION
**Pull request by atrick**
Required for SE-0107: UnsafeRawPointer.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci Please test and merge.

**Comment by atrick** [comment]
@swift-ci Please smoke test and merge.

**Comment by atrick** [comment]
This passed full swift-ci testing on OSX and Linux. But the linux bots are too backed up right now to do the auto-mege.

**Comment by gottesmm** [comment]
Just an FYI for everyone. Part of the reason that things are so backed up is that (I believe) a few days ago Ted made the incremental linux smoke test bot non-incremental to work around a build issue. Thus the smoke tests were taking significantly longer than previously. I fixed this.

Michael

**Comment by atrick** [comment]
Thanks Michael. Ted's fix was after I requested someone from the working group to simply clear the workspace because I don't have permission to do it and at the time no one seemed to be monitoring  the builds.

**Pull request merged**
