### PR TITLE
ClangImporter: Adjust call to BinaryOperator constructor after clang change r298877.

### PR DESCRIPTION
**Pull request by eeckstein**
Thanks @anemet for the fix.

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci Please smoke test and merge

**Comment by slavapestov** [comment]
@shahmishal Can you force merge this? CI is still working on it but everything compiled so it should work.

**Comment by shahmishal** [comment]
@eeckstein We might also have to cherry pick this fix in swift-4.0-branch.

**Comment by eeckstein** [comment]
It's https://github.com/apple/swift/pull/8605

**Pull request merged**
