### PR TITLE
Adding missing changes on the Pull Request #402

### PR DESCRIPTION
**Pull request by gabrielPeart**
Pushing missing classes from the previous Pull Request

/cc @gottesmm

### CODE REVIEW

**Comment by djwbrown** [comment]
I made the same changes and I'm still getting 4/6 tests failing. Have you been able to build with all tests passing?

--- Building tests for cmark ---
+ /usr/local/bin/cmake --build /Users/dylan/Developer/Swift/build/Ninja-DebugAssert/cmark-macosx-x86_64 -- api_test
ninja: no work to do.
--- Running tests for cmark ---
--- test ---
+ cd /Users/dylan/Developer/Swift/build/Ninja-DebugAssert/cmark-macosx-x86_64
+ /usr/local/Cellar/cmake/3.4.0/bin/ctest --force-new-ctest-process
Test project /Users/dylan/Developer/Swift/build/Ninja-DebugAssert/cmark-macosx-x86_64
    Start 1: api_test
1/6 Test #1: api_test .........................   Passed    0.00 sec
    Start 2: html_normalization
2/6 Test #2: html_normalization ...............***Failed    0.08 sec
    Start 3: spectest_library
3/6 Test #3: spectest_library .................***Failed    0.06 sec
    Start 4: pathological_tests_library
4/6 Test #4: pathological_tests_library .......   Passed    0.80 sec
    Start 5: spectest_executable
5/6 Test #5: spectest_executable ..............***Failed    0.06 sec
    Start 6: smartpuncttest_executable
6/6 Test #6: smartpuncttest_executable ........***Failed    0.06 sec

33% tests passed, 4 tests failed out of 6

**Comment by djwbrown** [comment]
I made the same changes but I'm still failing 4/6 tests. Have you been able to build with all tests passing?

**Comment by gabrielPeart** [comment]
Could you give the points that are not passing?
Yes, it has passed and generated the libswiftStdlibUnittest.dylib

**Comment by gabrielPeart** [comment]
Are you performing:

check-swift
check-swift-validation

check-swift-all
?

**Comment by djwbrown** [comment]
I had been using: utils/build-script -t
Could you tell me where to find check-swift?

**Comment by gabrielPeart** [comment]
utils/build-script as well, just use the respective targets:

check-swift
(Runs tests from the ${SWIFT_SOURCE_ROOT}/test directory.)

check-swift-validation
(Runs tests from the ${SWIFT_SOURCE_ROOT}/validation-test directory.)

check-swift-all
(Runs all tests.)

**Pull request merged**
