### PR TITLE
Enable stdlib resilience

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes <https://bugs.swift.org/browse/SR-5658>, <rdar://problem/33767772>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please benchmark

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test compiler performance

**Comment by slavapestov** [comment]
Linux build fixed in https://github.com/apple/swift/pull/13575

**Comment by slavapestov** [comment]
Most of the source compat failures are variations on the following:

```
Assertion failed: (!archetype->isPrimary() && "type metadata for primary archetype was not bound in context"), function emitArchetypeTypeMetadataRef, file /Users/spestov/src/swift/lib/IRGen/GenArchetype.cpp, line 64.
0  swift                    0x000000010df6cb68 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 40
1  swift                    0x000000010df6d226 SignalHandler(int) + 470
2  libsystem_platform.dylib 0x00007fff59989f5a _sigtramp + 26
3  libsystem_platform.dylib 0x00000000000034d8 _sigtramp + 2791806360
4  libsystem_c.dylib        0x00007fff597b532a abort + 127
5  libsystem_c.dylib        0x00007fff5977d380 basename_r + 0
6  swift                    0x000000010a92d8f6 swift::irgen::emitArchetypeTypeMetadataRef(swift::irgen::IRGenFunction&, swift::CanTypeWrapper<swift::ArchetypeType>) + 182
7  swift                    0x000000010a9df87a llvm::Value* swift::CanTypeVisitor<(anonymous namespace)::EmitTypeMetadataRef, llvm::Value*>::visit<>(swift::CanType) + 826
8  swift                    0x000000010a9d16f0 swift::irgen::IRGenFunction::emitTypeMetadataRef(swift::CanType) + 96
9  swift                    0x000000010a9e1a67 void llvm::function_ref<void (unsigned int, swift::CanType, llvm::Optional<swift::ProtocolConformanceRef>)>::callback_fn<(anonymous namespace)::GenericArguments::collect(swift::irgen::IRGenFunction&, swift::CanType)::'lambda'(unsigned int, swift::CanType, llvm::Optional<swift::ProtocolConformanceRef>)>(long, unsigned int, swift::CanType, llvm::Optional<swift::ProtocolConformanceRef>) + 55
10 swift                    0x000000010a9ff0e5 swift::irgen::GenericTypeRequirements::enumerateFulfillments(swift::irgen::IRGenModule&, swift::SubstitutionMap const&, llvm::function_ref<void (unsigned int, swift::CanType, llvm::Optional<swift::ProtocolConformanceRef>)>) + 261
11 swift                    0x000000010a9e1676 emitNominalMetadataRef(swift::irgen::IRGenFunction&, swift::NominalTypeDecl*, swift::CanType) + 342
12 swift                    0x000000010a9df693 llvm::Value* swift::CanTypeVisitor<(anonymous namespace)::EmitTypeMetadataRef, llvm::Value*>::visit<>(swift::CanType) + 339
13 swift                    0x000000010a9d16f0 swift::irgen::IRGenFunction::emitTypeMetadataRef(swift::CanType) + 96
14 swift                    0x000000010a99537f (anonymous namespace)::MultiPayloadEnumImplStrategy::loadDynamicTag(swift::irgen::IRGenFunction&, swift::irgen::Address, swift::SILType) const + 95
15 swift                    0x000000010a997254 (anonymous namespace)::MultiPayloadEnumImplStrategy::emitIndirectInitialize(swift::irgen::IRGenFunction&, swift::irgen::Address, swift::irgen::Address, swift::SILType, swift::IsTake_t, bool) const + 324
16 swift                    0x000000010a990a80 (anonymous namespace)::MultiPayloadEnumImplStrategy::initializeWithCopy(swift::irgen::IRGenFunction&, swift::irgen::Address, swift::irgen::Address, swift::SILType, bool) const + 416
17 swift                    0x000000010a97e11c void llvm::function_ref<void (swift::irgen::TypeInfo const&, swift::irgen::IRGenFunction&, swift::irgen::Address, swift::irgen::Address, swift::SILType)>::callback_fn<swift::irgen::IRGenModule::getOrCreateOutlinedInitializeWithCopyFunction(swift::irgen::TypeInfo const&, llvm::Type*, swift::SILType, llvm::MapVector<swift::CanType, llvm::Value*, llvm::DenseMap<swift::CanType, unsigned int, llvm::DenseMapInfo<swift::CanType>, llvm::detail::DenseMapPair<swift::CanType, unsigned int> >, std::__1::vector<std::__1::pair<swift::CanType, llvm::Value*>, std::__1::allocator<std::__1::pair<swift::CanType, llvm::Value*> > > > const*)::$_9>(long, swift::irgen::TypeInfo const&, swift::irgen::IRGenFunction&, swift::irgen::Address, swift::irgen::Address, swift::SILType) + 44
18 swift                    0x000000010a97e03b void llvm::function_ref<void (swift::irgen::IRGenFunction&)>::callback_fn<swift::irgen::IRGenModule::getOrCreateOutlinedCopyAddrHelperFunction(swift::irgen::TypeInfo const&, llvm::Type*, swift::SILType, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, llvm::function_ref<void (swift::irgen::TypeInfo const&, swift::irgen::IRGenFunction&, swift::irgen::Address, swift::irgen::Address, swift::SILType)>, llvm::MapVector<swift::CanType, llvm::Value*, llvm::DenseMap<swift::CanType, unsigned int, llvm::DenseMapInfo<swift::CanType>, llvm::detail::DenseMapPair<swift::CanType, unsigned int> >, std::__1::vector<std::__1::pair<swift::CanType, llvm::Value*>, std::__1::allocator<std::__1::pair<swift::CanType, llvm::Value*> > > > const*)::$_7>(long, swift::irgen::IRGenFunction&) + 203
19 swift                    0x000000010a977715 swift::irgen::IRGenModule::getOrCreateHelperFunction(llvm::StringRef, llvm::Type*, llvm::ArrayRef<llvm::Type*>, llvm::function_ref<void (swift::irgen::IRGenFunction&)>, bool) + 293
20 swift                    0x000000010a978972 swift::irgen::IRGenModule::getOrCreateOutlinedCopyAddrHelperFunction(swift::irgen::TypeInfo const&, llvm::Type*, swift::SILType, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, llvm::function_ref<void (swift::irgen::TypeInfo const&, swift::irgen::IRGenFunction&, swift::irgen::Address, swift::irgen::Address, swift::SILType)>, llvm::MapVector<swift::CanType, llvm::Value*, llvm::DenseMap<swift::CanType, unsigned int, llvm::DenseMapInfo<swift::CanType>, llvm::detail::DenseMapPair<swift::CanType, unsigned int> >, std::__1::vector<std::__1::pair<swift::CanType, llvm::Value*>, std::__1::allocator<std::__1::pair<swift::CanType, llvm::Value*> > > > const*) + 354
```

@shajrawi I see a similar fix went in a while ago -- https://github.com/apple/swift/commit/2c857dc6a8258d0f6a1373a0e5855779fd41d302 -- can you take a look if it needs to be revised or generalized?

The problem is easy to reproduce, `build-script -R --swift-stdlib-enable-resilience` and then point the source compat suite's runner.py script at your just-built swiftc.

**Comment by slavapestov** [comment]
@gottesmm The Alamofire failure is our old friend:

```
/Users/spestov/src/swift-source-compat-suite/project_cache/Alamofire/Source/Request.swift:592:27: error: matching type ''URLRequest'' in multiple patterns is not yet supported; use separate cases instead
        case .data(_, let urlRequest), .file(_, let urlRequest), .stream(_, let urlRequest):
                          ^
/Users/spestov/src/swift-source-compat-suite/project_cache/Alamofire/Source/AFError.swift:276:38: error: matching type ''URL'' in multiple patterns is not yet supported; use separate cases instead
        case .bodyPartURLInvalid(let url), .bodyPartFilenameInvalid(let url), .bodyPartFileNotReachable(let url),
                                     ^
```

Do you have a radar or a JIRA for this? Are there plans to fix it before opaque values land? It's an unfortunate limitation because it creates a source compatibility break when resilience is enabled.

**Comment by slavapestov** [comment]
@swift-ci Please test Linux

**Comment by shajrawi** [comment]
@swift-ci Please benchmark

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by shajrawi** [comment]
@swift-ci Please test

**Comment by shajrawi** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@shajrawi Looks like we still have a counterexample for this assert:

```
Assertion failed: (!archetype->isPrimary() && "type metadata for primary archetype was not bound in context"), function emitArchetypeTypeMetadataRef, file /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite/swift/lib/IRGen/GenArchetype.cpp, line 64.
0  swift                    0x0000000111db2f28 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 40
1  swift                    0x0000000111db35e6 SignalHandler(int) + 470
2  libsystem_platform.dylib 0x00007fffe920cb3a _sigtramp + 26
3  libsystem_platform.dylib 000000000000000000 _sigtramp + 383726816
4  libsystem_c.dylib        0x00007fffe9091420 abort + 129
5  libsystem_c.dylib        0x00007fffe9058893 basename_r + 0
6  swift                    0x000000010e7298b6 swift::irgen::emitArchetypeTypeMetadataRef(swift::irgen::IRGenFunction&, swift::CanTypeWrapper<swift::ArchetypeType>) + 182
```

**Comment by slavapestov** [comment]
@shajrawi Thanks for the quick turnaround!

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by DougGregor** [comment]
AWESOME!

**Comment by shajrawi** [comment]
w00t!!!

**Comment by swiftix** [comment]
Finally!!!

**Comment by vedantk** [comment]
Hi @slavapestov, this change is triggering 5 distinct test failures in lldb (https://ci.swift.org/job/oss-lldb-swift-master-llvm-swift5-transition-incremental-osx/73/, rdar://36663932). Could you take a look?

**Comment by gottesmm** [comment]
+1! +1! Major Props to @swiftix, @slavapestov, @shajrawi, and most importantly to @swift-ci ; ).

**Pull request merged**
