### PR TITLE
Exterminate tests

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
@jrose-apple any idea what to do about the top most commit here?  It seems that the wrapper is causing pain :-(.

**Comment by compnerd** [comment]
CC: @jmittert

**Comment by jrose-apple** [comment]
Is there a way to make it use a batch script or something else implicitly executable on Windows? Or does that only work from the command line and not arbitrary subprocess spawns?

**Comment by compnerd** [comment]
Yeah, unfortunately, that doesn't work from the process creation :-(.  That requires an explicit path to the interpreter (even the batch files need to be launched with `cmd.exe /c`).

**Comment by jrose-apple** [comment]
Hm. I'd rather not slow down all these tests by building-and-linking a wrapper just to call Python, but I can't think of anything better. Alternately, we could change `-driver-use-frontend-path` to take multiple arguments (if we're very careful about escaping) or add some other functionality for testing this.

**Comment by compnerd** [comment]
I was leaning towards the latter, it would be the most flexible and shouldn't slow down things very much.

**Comment by jrose-apple** [comment]
Passing down the Python path is probably fine. I don't love the idea of dummy tokens in the frontend path, but I guess spaces would be a problem for spaces-in-path, and this is just for testing anyway. Tabs? Newlines? Semicolons?

**Comment by compnerd** [comment]
Closing this as I believe that this should no longer be needed thanks to #22638

**Pull request closed without merging**
