### PR TITLE
[IDE] Use the passed in Action for setting up an invocation

### PR DESCRIPTION
**Pull request by bnbarham**
There was a recent change to error early if the stdlib couldn't be
loaded when semantic functionality is required. Since
`ide::initCompilerInvocation` was ignoring the given `Action` and just
setting to `Typecheck` instead, this would cause an error even if
semantic functionality *wasn't* required.

Resolves rdar://88968608.

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
I'm not sure about this change. It really seems like we want to evaluate `#if`. Thoughts?

**Comment by ahoppen** [comment]
Not the best of all ideas but could we add another `ActionType` that parsers + evaluates `#if`. We might also want to use that action for other syntactic SourceKit functionality.

**Comment by bnbarham** [comment]
> Not the best of all ideas but could we add another `ActionType` that parsers + evaluates `#if`. We might also want to use that action for other syntactic SourceKit functionality.

Interesting. I wouldn't be super opposed to that. Given this change really only affects `#if <constant>` and `#if ... #else ...` (opposite to what we'd want anyway) but fixes requiring the stdlib, I think we should just get it in now and then think about the `active` vs `inactive` case more later.

**Comment by benlangmuir** [comment]
>  It really seems like we want to evaluate #if.

**Review by ahoppen — APPROVED** [review]

**Pull request merged**
