### PR TITLE
Implement function signature rewriter and cloner

### PR DESCRIPTION
**Pull request by trentxintong**
This change implements the function signature optimization cloner and rewriter.

### CODE REVIEW

**Comment by trentxintong** [comment]
@rudkx Please take a look.

Currently there is a quadratic complexity introduced by the existCaller function. 

We need an analysis to do this.  This analysis should tell us whether a function has a caller or not inside current module.  i.e. if no caller inside current module, we do not FSO. Not doing so, i.e. FSO blindly, breaks a lot of test cases i.e. those .swift that relies on -O.

While i am working on the analysis, you can start reviewing the code.

**Comment by trentxintong** [comment]
@swift-ci Please test

**Comment by rudkx** [comment]
@trentxintong Do you have a version of this that works with your caller analysis and passes tests?

If so, can you push that up for review?

Also, it's best if you push to something other than master, so that if you're pushing for multiple different pull requests they do not end up overwriting each other and/or pushed up together.

**Comment by trentxintong** [comment]
Yes, I do. Do you mind i open a new PR ?

**Comment by rudkx** [comment]
A new PR sounds good.

**Pull request closed without merging**
