### PR TITLE
[sil-opt] Only notify the pass manager of newly added functions in SI…

### PR DESCRIPTION
**Pull request by gottesmm**
…LOptFunctionBuilder.

To do so this commit does a few different things:

1. I changed SILOptFunctionBuilder to notify the pass manager's logging
functionality when new functions are added to the module and to notify analyses
as well. NOTE: This on purpose does not put the new function on the pass manager
worklist since we do not want to by mistake introduce a large amount of
re-optimizations. Such a thing should be explicit.

2. I eliminated SILModuleTransform::notifyAddFunction. This just performed the
operations from 1. Now that SILOptFunctionBuilder performs this operation for
us, it is not needed.

3. I changed SILFunctionTransform::notifyAddFunction to just add the function to
the passmanager worklist. It does not need to notify the pass manager's logging
or analyses that a new function was added to the module since
SILOptFunctionBuilder now performs that operation. Given its reduced
functionality, I changed the name to addFunctionToPassManagerWorklist(...). The
name is a little long/verbose, but this is a feature since one should think
before getting the pass manager to rerun transforms on a function. Also, giving
it a longer name calls out the operation in the code visually, giving this
operation more prominance when reading code. NOTE: I did the rename using
Xcode's refactoring functionality!

rdar://42301529

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@atrick this one is more complex than the others, can I get a review?

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci asan test

**Review by atrick — APPROVED** [review]
What's the functional change here if any? Calling `notifyAnalysisOfFunction` earlier shouldn't affect any of these passes right? Can we assume that doesn't actually invalidate any analysis that needed to remain valid after a pass called createFunction?

If you're confident about that and don't see performance regressions, I say LGTM. I definitely like the new APIs.

**Comment by gottesmm** [comment]
@atrick It is not an issue. All analysiess that use this use it to add to a recompute list. Also the semantics is that the notification should be sent right after the function is created.

**Comment by gottesmm** [comment]
I am going to fix the doc comments in a forthcoming PR.

**Pull request merged**
