### PR TITLE
Updating usage of SanitizerCoverage.

### PR DESCRIPTION
**Pull request by plotfi**
(cherry picked from commit 913977bfb1ac07c1e8f8fe24a757c758371289e8)

Bringing back Sanitizer Coverage fix due to r367053

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by plotfi** [comment]
```
11:24:01 CMake Error at cmake/modules/LLDBConfig.cmake:236 (message):
11:24:01   Found incompatible Python interpreter (2.7.10) and Python libraries
11:24:01   (2.7.16)
11:24:01 Call Stack (most recent call first):
11:24:01   CMakeLists.txt:23 (include)
11:24:01 
11:24:01 
11:24:01 -- Configuring incomplete, errors occurred!
```

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Pull request closed without merging**
