### PR TITLE
[test] Add 'remote-run', a tool to run executable tests over SSH

### PR DESCRIPTION
**Pull request by jrose-apple**
(instead of locally)

The primary use case I'm looking at is easier testing across macOS versions, but it could also be used for cross-compilation tests in general (someday).

You can use this by providing these parameters to lit.py using the `--param` flag:
- remote_run_host: Mandatory, taking the form "`[user@]host[:port]`".
- remote_run_tmpdir: Mandatory. A safe directory on the remote host to upload things to.
- remote_run_identity: Optional. A custom SSH private key file.
- remote_run_skip_upload_stdlib: Optional. If present, the standard library dylibs won't be uploaded before the tests are run. This is meant for repeat runs.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Review by shahmishal — APPROVED** [review]
LGTM! I think it would great to add doc about using remote-run in https://github.com/apple/swift/blob/master/docs/Testing.md.

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Comment by davezarzycki** [comment]
Hi @jrose-apple – My Linux distro (Red Hat Fedora) did not install a sftp server by default. Are sftp client/server packages now required for development testing?

**Comment by jrose-apple** [comment]
Oops, I didn't realize SFTP wasn't standard enough for this. I'll add a check in lit.

**Comment by davezarzycki** [comment]
Ya. AFAIK, some Linux "workstation" distros err on the side of not installing "server" packages for security reasons.

**Comment by davezarzycki** [comment]
PS - I installed vsftpd and the tests passed

**Comment by jrose-apple** [comment]
#18759

**Pull request merged**
