### PR TITLE
[test] Re-disable objc_nonnull_lie_hack.swift.

### PR DESCRIPTION
**Pull request by jrose-apple**
The CHECK lines are too restrictive under different optimization. Disable the test to unblock the buildbots. Filed rdar://problem/33495516 to pick it up again later.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test and merge

**Comment by slavapestov** [comment]
How about `XFAIL: optimized_stdlib`?

**Comment by jrose-apple** [comment]
I don't actually know what the failure condition is, but I don't think that's it. I build with optimized_stdlib myself, and so does PR testing.

**Comment by jckarter** [comment]
Optimization level changes shouldn't affect SILGen, and the whole point of the "nonnull lie hack" is to prevent optimization from eating necessary null checks. Is there a real problem here?

**Comment by jrose-apple** [comment]
No, the CHECK line that failed to match was the function header.

**Pull request merged**
