### PR TITLE
[TBDGen] Fix check for global accessors

### PR DESCRIPTION
**Pull request by harlanhaskins**
Previously, TBDGen skipped emitting lazy initializers for globals that
appeared in any file with an entry point. This breaks, however on files
that have an `NSApplicationMain`/`UIApplicationMain` class in them, where
the entry point is synthesized but top-level globals are not locally
scoped. This change re-uses SILGen's check and only skips variable
declarations that appear at top level in a script mode file.

Resolves rdar://43549749

### CODE REVIEW

**Review by jrose-apple — APPROVED** [review]

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test

**Comment by slavapestov** [comment]
Does it ever make sense for script mode declarations to have public symbols? Maybe we should fix the linkage computation for the initializer instead

**Comment by slavapestov** [comment]
Also why would you want to generate a TBD for something with a main() function? Isn’t TBD only for dynamic libraries?

**Comment by harlanhaskins** [comment]
If `-enable-testing` is passed, global lazy inits get public symbols, but that's a useless flag if you're compiling in script mode.

Currently, in Debug on Apple platforms, we validate the TBD file symbol generation against generated IR unless explicitly told not to via `-validate-tbd-against-ir=none`, so even if we're not going to emit a TBD file directly, we still support the symbol validation logic. Maybe we could revisit that policy for modules with a `main`.

**Comment by jrose-apple** [comment]
It's still sensible to try to parallelize building test targets with building the app target.

**Pull request merged**
