### PR TITLE
[stdlib] Remove workaround for sort optimization issue

### PR DESCRIPTION
**Pull request by natecook1000**

### CODE REVIEW

**Comment by natecook1000** [comment]
@swift-ci Please test

**Comment by natecook1000** [comment]
@swift-ci Please test Linux platform

**Comment by natecook1000** [comment]
@swift-ci Please smoke benchmark

**Comment by natecook1000** [comment]
@swift-ci Please test Linux platform

**Comment by shajrawi** [comment]
@swift-ci Please test

**Comment by natecook1000** [comment]
@swift-ci Please test macOS platform

**Pull request closed without merging**
