### PR TITLE
[Gardening] Use os(..) checks instead of canImport(Darwin) in CTypes.swift

### PR DESCRIPTION
**Pull request by varungandhi-apple**
Reverts a small part of cddf73ecdbd79edf456fe17a7dba19a8adff9186.

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test

**Comment by varungandhi-apple** [comment]
Fixes rdar://problem/65006695

**Comment by CodaFi** [comment]
@swift-ci smoke test macOS

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
