### PR TITLE
[stdlib] Add Substring comparison benchmarks

### PR DESCRIPTION
**Pull request by dabrahams**
This reveals lots of unimplemented cases, which will cause us to uncomment the
disabled code.

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please smoke benchmark

**Comment by dabrahams** [comment]
@swift-ci Please smoke test and merge

**Comment by dabrahams** [comment]
@eeckstein do I need to regenerate some harness to get this to pass?

**Comment by eeckstein** [comment]
@dabrahams Yes, run  benchmark/scripts/generate_harness/generate_harness.py

**Comment by dabrahams** [comment]
@swift-ci Please smoke benchmark

**Comment by dabrahams** [comment]
@swift-ci Please smoke benchmark

**Comment by dabrahams** [comment]
@swift-ci Please smoke test and merge

**Comment by dabrahams** [comment]
@swift-ci Please smoke test and merge

**Pull request merged**
