### PR TITLE
[Serialization] Add missing record into block info block

### PR DESCRIPTION
**Pull request by cachemeifyoucan**
OptionBlocks has missing block record for some of the record types. Add the missing record types into block info block and order the block record in the same order as the declaration so it is easier to check for which kind is missing.

### CODE REVIEW

**Comment by cachemeifyoucan** [comment]
I don't think this breaks binary module compatibility. Didn't bump the version.

**Comment by cachemeifyoucan** [comment]
@swift-ci please smoke test

**Comment by cachemeifyoucan** [comment]
ping. Any objection for this?

**Review by xymus — APPROVED** [review]
It looks good, thank you for the clean up!

**Pull request merged**
