### PR TITLE
[SourceKit] Syntax parsing performance improvements

### PR DESCRIPTION
**Pull request by ahoppen**
This PR bundles a bunch of small performance improvements for parsing a syntax tree from a Swift file using SourceKit.

The separate improvements are described in the respective commit messages.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Review by rintaro — APPROVED** [review]
Looks good.

**Review by nkcsgexi — APPROVED** [review]

**Comment by ahoppen** [comment]
Fixed some merge conflicts.

@swift-ci Please smoke test and merge

**Comment by ahoppen** [comment]
@swift-ci Please smoke test and merge

**Pull request merged**
