### PR TITLE
Port almost all remaining FunctionType::get() usages to new representation

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
https://github.com/apple/swift-lldb/pull/839
@swift-ci Please test

**Review by xedin — APPROVED** [review]
Nice! When do you think we will be able to completely remove `Input` from the `AnyFunctionType`?

**Comment by slavapestov** [comment]
@xedin I have another set of changes to remove usages from the constraint solver, but it's still WIP.

**Pull request merged**
