### PR TITLE
Tensor documentation update. (#TF-448)

### PR DESCRIPTION
**Pull request by ksasi**
Updated documentation for Tensor in Tensor.swift file

Resolves [TF-448](https://bugs.swift.org/browse/TF-448).

### CODE REVIEW

**Comment by krilnon** [comment]
I have some thoughts on writing style here that could build on what you've written:

- You're missing spaces after periods in a couple spots. 
- The summary/abstract [should be a single sentence fragment](https://swift.org/documentation/api-design-guidelines/); so I'd separate out the rest of your additions by adding a blank `///` doc comment line in between the first sentence and the rest.
- Usually it's helpful to avoid duplicating the symbol name in its summary. You might say "A multidimensional array that's a generalization of vectors and […]" or something along those lines.

**Comment by ksasi** [comment]
Thanks for the feedback, I have made updates as per the suggestions.

**Comment by ksasi** [comment]
Please advise of any changes/updates that would be needed so that this pull request can be taken to closure.

**Comment by rxwei** [comment]
Sorry for the delay! We've recently moved the entire TensorFlow library to https://github.com/tensorflow/swift-apis. Would you mind starting a PR there?

**Comment by ematejska** [comment]
This no longer applies so closing.  Thank you!

**Pull request closed without merging**
