### PR TITLE
[SourceKit/CodeFormat] Indentation fixes for multi-line string, UnresolvedSpecializeExpr, and trailing target handling.

### PR DESCRIPTION
**Pull request by nathawes**
1) Fixes a bug were we were indenting within a multi-line string when we shouldn't have been. The checks for walking into an AST node or not were based on their end source loc, which is the start of their last token. If that token was a multi-line string and line being indented was within it, we we wouldn't walk into the node, and so never set the flag to indicate we were attempting to indent within a string.

2) We weren't handling UnresolvedSpecializeExpr when determining if an expression was 'outdenting' or not, so we ended up indenting the filter call below when we shouldn't have:
    ```
     let x = foo<
         Int,
         String,
         Int
     >()
          .filter { $0 > 10 }
    ```
    It's now handled correctly.

3) Fixes up ListAligner (and the code using it) to handle trailing indentation targets in many more cases. This makes the as-you-type indentation more consistent with select-and-reindent-after-you're-done indentation. Hitting enter after a comma in an incomplete list, or after an empty list that requires at least one element now give the correct indentation in many more cases (including guard/if/while conditions, and enum case elements). A few lists still don't handle trailing indentation targets properly, though, because the parser drops them from the AST when incomplete or empty.

Resolves rdar://problem/62061741

### CODE REVIEW

**Comment by nathawes** [comment]
@swift-c please test

**Comment by nathawes** [comment]
@swift-ci please smoke test

**Comment by nathawes** [comment]
@swift-ci please test

**Comment by nathawes** [comment]
@swift-ci please stress test

**Review by benlangmuir — APPROVED** [review]

**Pull request merged**
