### PR TITLE
Concurrency runtime: Fix location of tsan_release edges for actors.

### PR DESCRIPTION
**Pull request by jckarter**
The TSAN release edge should appear before the actual cmpxchg-release.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Review by yln — APPROVED** [review]
My understanding is that in both cases the `while (true) { ... compare_exchange_weak(); ... }` will eventually succeed (no other out flows) and corresponds to a conceptual "unlock()" operation.

LGTM, thanks!

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by DougGregor** [comment]
The test was failing sporadically in CI, so I've gone ahead and merged this

**Pull request merged**
