### PR TITLE
[ownership] Add an extra run of the early inliner to expose more code to semantic arc opts.

### PR DESCRIPTION
**Pull request by gottesmm**
Not expecting anything specific from this, but it should strengthen the optimization by allowing me to put some more stuff around load promotion/etc in between this and semantic arc opts.

That being said, who knows, maybe we get some wins? = p.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci test compiler performance

**Comment by gottesmm** [comment]
Thats insane

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by gottesmm** [comment]
Doing an experiment where we do not inline unless all callees/caller are in sync. If we are out of sync then the caller will just be inlined later after we lower ownership. In a separate PR I am going to test the same thing with stdlib only.

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci test compiler performance

**Comment by gottesmm** [comment]
@swift-ci test compiler performance

**Comment by gottesmm** [comment]
@swift-ci test compiler performance

**Comment by gottesmm** [comment]
@swift-ci test compiler performance

**Comment by gottesmm** [comment]
@swift-ci test compiler performance

**Comment by gottesmm** [comment]
@swift-ci test compiler performance

**Pull request closed without merging**
