### PR TITLE
Swift 5.1 branch rdar47467128 part1

### PR DESCRIPTION
**Pull request by gottesmm**
Cherry-picking #23320 23378 to 5.1 branch.

rdar://problem/47467128

----

EDIT: This is a cherry-pick actually of PR: #23378.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Review by akyrtzi — APPROVED** [review]

**Comment by gottesmm** [comment]
@shahmishal Do you know why the tests didn't trigger here?

**Comment by slavapestov** [comment]
You linked the wrong PR in your description :)

**Comment by gottesmm** [comment]
@slavapestov oops... you are right! The right one is: #23378

**Comment by gottesmm** [comment]
Looks like it was a bad autocomplete via github.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Pull request merged**
