### PR TITLE
[NFC] Use consistent naming scheme for predicate methods.

### PR DESCRIPTION
**Pull request by varungandhi-apple**
Rename: bool throws() -> isThrowing(), bool async() -> isAsync().

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test

**Review by CodaFi — APPROVED** [review]
:shipit:

**Comment by varungandhi-apple** [comment]
@swift-ci please test Windows

**Comment by theblixguy** [comment]
It might be worth renaming `hasThrows` and `hasAsync` methods on AbstractFunctionDecl as well (e.g. to `isThrowing` and `isAsync` respectively). WDYT?

**Comment by varungandhi-apple** [comment]
Yeah, that's a fair point. I considered it, then I decided against it because it sounded a bit strange in my head -- a function _type_ being throwing sounds okay-ish, but a declaration is not throwing itself. I don't feel strongly about it though.

**Pull request merged**
