### PR TITLE
Avoid setting the extendedType before and after computing the generic signature.

### PR DESCRIPTION
**Pull request by varungandhi-apple**

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
@swift-ci please test

**Review by slavapestov — APPROVED** [review]
Looks great, thanks!

**Comment by jrose-apple** [comment]
Does this fix the SR on its own, or is there more follow-up work? If the former, can you add the test for it?

**Comment by varungandhi-apple** [comment]
@jrose-apple this does not fix the issue by itself, it is a cleanup PR. I will add an XFAIL test case as you've suggested.

**Comment by varungandhi-apple** [comment]
@swift-ci please test

**Comment by varungandhi-apple** [comment]
@swift-ci please test

**Pull request merged**
