### PR TITLE
Initial TBD push: list of (some) public symbols

### PR DESCRIPTION
**Pull request by huonw**
This makes some pieces of IRGen publicly accessible, and glues them together with some pieces of SIL to form a basic tool for listing all the public symbols in a module (the `-emit-tbd` flag). The listing is woefully incomplete, but this pull request also includes infrastructure for determining just how incomplete, via the `-validate-tbd-against-ir` frontend flag.

The validation flag does a comparison between the symbols listed in the TBD file and the external symbols in the IR, flagging any that are in one set but not the other. Some simple tests are included, but all but `functions` tests do not pass `-validate-tbd-against-ir`, and FileCheck is used to confirm that the failures are "known" failures and that changes that introduce more (or fewer) mismatches are noticed.

I've put little effort into actually dissecting the failures, this pull request is only establishes any support to to be able to test the rest of the infrastructure.

### CODE REVIEW

**Comment by slavapestov** [comment]
FWIW eventually I think we want to enable the TBD validation in all (asserts) builds, which will cause existing tests to catch mishaps.

**Comment by jckarter** [comment]
This looks like a good start. @slavapestov @jrose-apple  Can the `isPrivateDecl` condition also unconditionally filter out `@_inlineable` or `@_transparent` declarations without availability, since those should be emitted in-client?

**Comment by huonw** [comment]
> FWIW eventually I think we want to enable the TBD validation in all (asserts) builds, which will cause existing tests to catch mishaps.

Yeah, I agree. I chose to have it it opt-in with custom tests here because 3000 failing tests will have a low signal-to-noise ratio.

**Comment by jrose-apple** [comment]
> Can the isPrivateDecl condition also unconditionally filter out `@_inlineable` or `@_transparent` declarations without availability, since those should be emitted in-client?

I'm not sure we've actually implemented that yet, but that is the hope, yes.

**Comment by huonw** [comment]
@swift-ci please smoke test.

**Comment by slavapestov** [comment]
@huonw @jrose-apple Right now transparent emits into client and @swiftix is looking at generalizing this to inlineable, but we need to do more work, for example until merge modules is preserving SIL, emitting inlineable into client is wrong because we have no way to call it if the SIL is lost. I wouldn't worry too much about resilience-related attributes for now to be honest.

**Comment by slavapestov** [comment]
I would think though that instead of having this code special-case inlineable, it would be better to re-use existing machinery for getting the linkage of SILDeclRefs and such. Then if that changes your code will just work too. What do you think?

**Comment by huonw** [comment]
> What do you think?

I've now dug through more of the compiler to find all/most of the various bits that seem to play into this. It looks like `LinkInfo` is what IRGen uses, but unfortunately computing that currently requires an IRGenModule, which may take a little while to tease out. I would prefer to land initial patch now, and then I can push the improvements to the  symbol visibility algorithm later. 

One down side of directly using all of that machinery is that TBDGen is no longer as good as being a declarative definition of what exactly our ABI is, as compared to what we currently have in IRGen.

**Comment by slavapestov** [comment]
Once you tease apart LinkInfo from IRGenModule and do some other related refactoring along those lines, we should still be able to have a minimal common set of support routines that "declaratively" define what symbols we export.

**Comment by huonw** [comment]
@swift-ci please smoke test and merge.

**Comment by huonw** [comment]
@swift-ci please smoke test and merge.

**Comment by huonw** [comment]
@swift-ci please smoke test

**Comment by huonw** [comment]
@swift-ci please smoke test

**Comment by shahmishal** [comment]
@swift-ci please smoke test

**Comment by huonw** [comment]
@swift-ci Please smoke test

**Comment by huonw** [comment]
@swift-ci Please smoke test Linux

**Pull request merged**
