### PR TITLE
Fix and temporarily disable tests for rebranch

### PR DESCRIPTION
**Pull request by eeckstein**
rdar://102151684
rdar://102151774
rdar://102151836
rdar://102858524

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by egorzhdan** [comment]
C++ interop tests will be fixed by https://github.com/apple/swift/pull/62190.

**Comment by eeckstein** [comment]
@swift-ci clean smoke test linux

**Comment by eeckstein** [comment]
@swift-ci test linux

**Comment by egorzhdan** [comment]
The C++ interop tests should now be fixed, @eeckstein could you please exclude them from this patch?

**Comment by eeckstein** [comment]
will do. Thanks!

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Pull request merged**
