### PR TITLE
[SILGen] NFC: Make adding new ReferenceStorageTypes easier

### PR DESCRIPTION
**Pull request by davezarzycki**
Failing at compile time is better than at runtime.

@swift-ci please smoke test

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by davezarzycki** [comment]
If Swift CI stays offline, I've smoke tested this locally.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by CodaFi** [comment]
@swift-ci Please smoke test

**Comment by davezarzycki** [comment]
Hi @rjmccall – While this patch works, I can see an argument for updating TypeNodes.def to create a REFERENCESTORAGE_TYPE macro instead of leaning on the Ownership enum. Do you think people would care one way or another?

**Comment by rjmccall** [comment]
No, I think the way you've done it here is fine.

**Comment by davezarzycki** [comment]
Thanks John. Just to be clear, do you mean "no, REFERENCESTORAGE_TYPE is a bad idea", or "[don't bother], I think the way you've done it here is fine"?

**Comment by rjmccall** [comment]
I think you could do a REFERENCE_STORAGE_TYPE, but that switching over ownership is also a perfectly acceptable way of handling it.

**Comment by davezarzycki** [comment]
Thanks for clarifying John :-)

**Pull request merged**
