### PR TITLE
Implement SE-0163

### PR DESCRIPTION
**Pull request by dabrahams**
- Explanation: Late-breaking Standard Library enhancements to String and Low-level Unicode handling corresponding to https://github.com/apple/swift-evolution/blob/master/proposals/0163-string-revision-1.md
- Scope: source-compatible Standard Library Change
- Radar: <[rdar://32165976](rdar://32165976)> Implement SE-0163
- Risk: It's a very large change.  We think we've tested it thoroughly on master and that regression testing on the swift-4.0 branch are likely enough to validate it, but mistakes are always possible.
- Testing: Passed full validation on master and 4.0 branch + source compatibility test (see below)

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please test

**Comment by dabrahams** [comment]
@swift-ci Please benchmark

**Comment by moiseev** [comment]
@swift-ci Please Test Source Compatibility

**Comment by dabrahams** [comment]
@moiseev Good idea.

**Comment by moiseev** [comment]
Build failure:
~~~
+ /Users/buildnode/jenkins/workspace/swift-PR-osx-perf/Ninja-Release/swift-macosx-x86_64/bin/Benchmark_Driver compare --log-dir /Users/buildnode/jenkins/workspace/swift-PR-osx-perf/Ninja-Release/swift-macosx-x86_64/benchmark/logs --swift-repo /Users/buildnode/jenkins/workspace/swift-PR-osx-perf/swift --compare-script /Users/buildnode/jenkins/workspace/swift-PR-osx-perf/swift/benchmark/scripts/compare_perf_tests.py
Unable to find benchmark logs for master branch. Set a baseline benchmark log by passing --benchmark to build-script while on master branch.
~~~

But the benchmark results are actually in the log!

**Comment by dabrahams** [comment]
That should not prevent a merge.

**Comment by dabrahams** [comment]
@swift-ci Please benchmark

**Comment by airspeedswift** [comment]
I don't think CI is handling the 4.0 branch benchmark case - it's saying unable to find baseline for master.

**Comment by dabrahams** [comment]
@airspeedswift I'm assuming you'll merge this in due course, then.

**Pull request merged**
