### PR TITLE
Revert "Symbol graph support"

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/swift#28678

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @bitjammer @brentdax

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by bitjammer** [comment]
What happened, @compnerd?

**Comment by bitjammer** [comment]
Ah, saw in the PR. Looking.

**Comment by compnerd** [comment]
I think that #29144 should fix it ... let this continue just incase

**Pull request closed without merging**
