### PR TITLE
Add rudimentary nested closure param/return/throws support for Doxygen

### PR DESCRIPTION
**Pull request by bitjammer**
There isn't a great nested argument feature that we can use in our
Doxygen emitter but we can approximate it by nesting unordered lists
with labels.

rdar://problem/24794725

### CODE REVIEW

**Comment by bitjammer** [comment]
@swift-ci Please smoke test

**Comment by tkremenek** [comment]
@bitjammer Should there be a test case for this change?

**Comment by bitjammer** [comment]
Yes indeed, there is a file I can repurpose to establish how it should look in Objective-C. I'll follow up with another commit.

**Comment by bitjammer** [comment]
@swift-ci Please smoke test

**Comment by tkremenek** [comment]
Thanks!

**Pull request merged**
