### PR TITLE
[ConstraintSystem] Rename getFixedType/assignFixedType/getFixedTypeRecursive.

### PR DESCRIPTION
**Pull request by rudkx**
A few renames:
- getFixedType => getBoundType
- assignedFixedType => assignBoundType
- getFixedTypeRecursive => resolveTypeVariable

**Note** this PR also has all of https://github.com/apple/swift/pull/18325.

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by xedin** [comment]
`{get, assign}BoundType` - `{get, assign}Type`, because it retrieves or assigns/binds a type for/to a type variable, and `resolveTypeVariable` - `resolveType` because it could resolve/simplify multiple type variables?

**Comment by rudkx** [comment]
@xedin I had considered `{get, assign}Type`, but `getType` is already in use on `ConstraintSystem` and I didn't want to overload it for that purpose.

I started looking at this because I have other changes where I ended up calling `getFixedType()` instead of `getFixedTypeRecursive()` and that's an easy mistake to make. The former is just grabbing whatever type was assigned via `assignFixedType()`,  i.e. the one bound to the type variable, whereas the latter drills down into dependent members and nested type variables, ultimately getting you to the most specific concrete type we can resolve to.

I'm not convinced `resolveType()` would be more clear than `resolveTypeVariable()`. They both have the very generic term `resolve`, which I'm not thrilled with but it attempts to convey the idea that we're doing something more than just a lookup.

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by xedin** [comment]
The reason why I want to drop `Bound` is because I don't think it carries any meaning, as soon as you want to assign a type or get a type for something it has to be a "bound" type, right?

Re: `getFixedTypeRecursive` maybe we should change it to `resolveTypeVariables` so at least it's plural?

**Comment by rudkx** [comment]
Lots of conflicts. It's easy enough to do a global rename at a later date; closing.

**Pull request closed without merging**
