### PR TITLE
Revert "[WIP][IRGen] Emit type field descriptors for imported structs"

### PR DESCRIPTION
**Pull request by rudkx**
Reverts apple/swift#14185

Testing a revert to see if this might be responsible for some of the failures in https://forums.swift.org/t/source-compatibility-bots-in-bad-shape/9526.

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
I'm going to preemptively merge as soon as smoke tests pass, as it looks like this was the only thing merged in the build where the new failures started showing up.

**Comment by xedin** [comment]
Thanks, @rudkx! Didn’t expect this to have impact on the source compatibility...

**Comment by xedin** [comment]
I am just going to merge it without waiting for compat suite.

**Pull request merged**
