### PR TITLE
Don't DCE @owned phis that may have escaped

### PR DESCRIPTION
**Pull request by meg-gupta**

### CODE REVIEW

**Comment by meg-gupta** [comment]
Needs https://github.com/apple/swift/pull/64708 to be merged first.

**Review by nate-chandler — APPROVED** [review]
LGTM

**Comment by meg-gupta** [comment]
@swift-ci test and merge

**Review by atrick — APPROVED** [review]

**Comment by meg-gupta** [comment]
@swift-ci smoke test and merge

**Pull request merged**
