### PR TITLE
[5.0][runtime] Fix some bugs when the stable ABI's is-Swift bit is set.

### PR DESCRIPTION
**Pull request by gparker42**
* cmake: Propagate SWIFT_DARWIN_ENABLE_STABLE_ABI_BIT to overlay builds.
* runtime: Clear the correct bit in getROData()
* test/IRGen/objc_class_export.swift: Allow either is-Swift bit.
* test/stdlib/SwiftObjectNSObject.swift: Allow either name for SwiftObject.

rdar://46543463 rdar://46601969

### CODE REVIEW

**Comment by gparker42** [comment]
@swift-ci please test

**Comment by gparker42** [comment]
@apple/swift5-branch-managers This fixes several bugs that are uncovered when the is-Swift bit is set to the new value for the stable ABI.

**Comment by gparker42** [comment]
@apple/swift5-branch-managers This is not important for the current convergence.

**Review by bob-wilson — APPROVED** [review]

**Comment by shahmishal** [comment]
Please check the comment in <rdar://problem/46601969> before merging this PR. Thanks!

**Comment by gparker42** [comment]
Requires #21422 and #21196.

**Comment by gparker42** [comment]
@swift-ci please smoke test

**Comment by bob-wilson** [comment]
@swift-ci please test

**Pull request merged**
