### PR TITLE
Implement \ syntax for Swift key paths.

### PR DESCRIPTION
**Pull request by huonw**
This introduces a few unfortunate things because the syntax is awkward.
In particular, the period and following token in \.[a], \.? and \.! are
token sequences that don't appear anywhere else in Swift, and so need
special handling. This is somewhat compounded by \foo.bar.baz possibly
being \(foo).bar.baz or \(foo.bar).baz (parens around the type), and,
furthermore, needing to distinguish \Foo?.bar from \Foo.?bar.

rdar://problem/31724243

### CODE REVIEW

**Comment by huonw** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
Does this include the missed tests from #9205?

**Comment by huonw** [comment]
Yeah, the last commit.

(It seems like GitHub is even smart enough to detect that the testing that I ran on that commit to land in master also applies here. Neat.)

**Comment by jckarter** [comment]
Sounds good.

**Pull request merged**
