### PR TITLE
[concurrency] update test missed in #34640, resolving rdar://71212904

### PR DESCRIPTION
**Pull request by kavon**
Resolves  rdar://71212904.

### CODE REVIEW

**Comment by kavon** [comment]
@swift-ci please smoke test and merge

**Review by ktoso — APPROVED** [review]
LGTM 👍

**Comment by kavon** [comment]
The Linux smoke test failed with:

```
FAIL: Swift-Unit :: runtime/./SwiftRuntimeTests/ConcurrentReadableArrayTest.MultiThreaded2 (608 of 13768)
******************** TEST 'Swift-Unit :: runtime/./SwiftRuntimeTests/ConcurrentReadableArrayTest.MultiThreaded2' FAILED ********************
Note: Google Test filter = ConcurrentReadableArrayTest.MultiThreaded2
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from ConcurrentReadableArrayTest
[ RUN      ] ConcurrentReadableArrayTest.MultiThreaded2
/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-main/swift/unittests/runtime/Concurrent.cpp:134: Failure
Expected: (element.threadNumber) < (writerCount), actual: 528 vs 16
[  FAILED  ] ConcurrentReadableArrayTest.MultiThreaded2 (2084 ms)
[----------] 1 test from ConcurrentReadableArrayTest (2084 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (2084 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ConcurrentReadableArrayTest.MultiThreaded2

 1 FAILED TEST
```

This is either a spurious test failure or a pre-existing condition of `main`.

**Comment by kavon** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
