### PR TITLE
build: switch gyb to Python3

### PR DESCRIPTION
**Pull request by compnerd**
Change the build system to invoke gyb with python3 instead of python2.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @stephentyrone @drodriguez @tachoknight @edymtt @shahmishal @JDevlieghere @gwynne

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by compnerd** [comment]
CC: @nathawes - you may also be interested in this since SwiftSyntax depends on gyb'ed output

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@nathawes I can't seem to figure out why the tests on macOS are failing with this change.  Happen to have any hints on why the tests are hitting this error:

```
The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax
Run lit-test-helper -help for more help.
```

**Comment by akyrtzi** [comment]
swift-syntax repo also invokes gyb via its build-script to generate its swift code. `def calculate_node_hash()` is used to ensure swift-side parser and swift-syntax library are compatible.

If swift-side uses python3 and that function generates different hash than python2 from swift-syntax, there will be a mismatch.

**Comment by compnerd** [comment]
@akyrtzi ah, thanks for that explanation.  I'll try to get swift-syntax synced up then

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci Please Python lint

**Comment by compnerd** [comment]
@swift-ci Please Python lint

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by shahmishal** [comment]
Thanks @compnerd!

**Pull request merged**
