### PR TITLE
[silgen] Scope conditionally emitted code by emitBoolDispatch.

### PR DESCRIPTION
**Pull request by gottesmm**
rdar://45602910

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Review by rjmccall — APPROVED** [review]

**Comment by gottesmm** [comment]
Forgot to disable the test on linux.

**Comment by gottesmm** [comment]
macOS passed. I am going to disable the test if we don't have objc_interopt and smoke test.

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
The broken test was due to the smoke test being configured not building the ARM codegenerator. I made the test conditional on that being around in #20210. So once that lands, I am going to do another macOS smoke test.

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Pull request merged**
