### PR TITLE
Update licm_and_global_addr.swift

### PR DESCRIPTION
**Pull request by compnerd**
Mark as executable test

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @eeckstein

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by eeckstein** [comment]
Thanks for fixing this!

**Pull request merged**
