### PR TITLE
[Driver] Pass `-lld-allow-duplicate-weak` for coverage on Windows

### PR DESCRIPTION
**Pull request by hamishknight**
Legacy driver version of swiftlang/swift-driver#1655 + an integration test for both the legacy and new driver.

rdar://129337999

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please smoke test

**Comment by hamishknight** [comment]
@swift-ci please smoke test

**Comment by hamishknight** [comment]
@swift-ci please smoke test

**Comment by hamishknight** [comment]
Hrm looks like while Windows CI does build the new driver, it does not seem like it gets picked up:

```
<unknown>:0: warning: using (deprecated) legacy driver, Swift installation does not contain swift-driver at: 'T:\5\bin\swift-driver-new.exe'
```

Is that expected @compnerd?

**Comment by hamishknight** [comment]
Okay, well I have at least tested locally that the swift-driver change works as expected

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Review by bnbarham — APPROVED** [review]

**Comment by artemcm** [comment]
> > ```
> > <unknown>:0: warning: using (deprecated) legacy driver, Swift installation does not contain swift-driver at: 'T:\5\bin\swift-driver-new.exe'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is that expected @compnerd?
> 
> Yes, this is expected. We do not rename the binary, but we do use it with the "old" name in some places.

@compnerd is there a good reason for this? It seems like it's causing some tests to behave differently only in Windows builds.

**Comment by compnerd** [comment]
> @compnerd is there a good reason for this? It seems like it's causing some tests to behave differently only in Windows builds.

Windows doesn't really do symlinks and the names of the files are important, especially for multi-call scenarios. IIRC, I had some trouble with the renamed binary working properly. If it works, a change to build.ps1 would be fine to do :)

**Comment by hamishknight** [comment]
@swift-ci please test macOS

**Pull request merged**
