### PR TITLE
[Diagnostics] Clarify the wording of `error_in_future_swift_version`.

### PR DESCRIPTION
**Pull request by hborla**
Folks are confused about language mode versus compiler version, and this warning does not specify which one it is talking about. Clarify that the warning will become an error in the next major language version, not the tools version. Also, add an educational note explaining tools version versus language mode version.

### CODE REVIEW

**Review by bnbarham — APPROVED** [review]

**Comment by hborla** [comment]
@swift-ci please smoke test

**Review by xedin — APPROVED** [review]

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by hborla** [comment]
@swift-ci please test Windows

**Comment by hborla** [comment]
@swift-ci please smoke test

**Pull request merged**
