### PR TITLE
Add and use AbstractFunctionDecl::getTypecheckedBody

### PR DESCRIPTION
**Pull request by hamishknight**
Refactor `TypeCheckFunctionBodyRequest` to return the type-checked body, and remove `typeCheckAbstractFunctionBody` in favor of a method on `AbstractFunctionDecl`. In addition, start returning an `ErrorExpr` body instead of a partially type-checked body if type-checking fails.

Then, start using `getTypecheckedBody` in SILGen to allow lazy type-checking when emitting function definitions.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Comment by hamishknight** [comment]
https://github.com/apple/llvm-project/pull/1753

@swift-ci please test

**Review by CodaFi — APPROVED** [review]

**Comment by hamishknight** [comment]
https://github.com/apple/llvm-project/pull/1753

@swift-ci please test

**Pull request merged**
