### PR TITLE
[master-next] Merge #29412

### PR DESCRIPTION
**Pull request by beccadax**
This resolves a merge conflict between #29412 and master-next.

To get this to build, I also needed to patch Immediate.cpp to adjust to an upstream change, but I'm not sure that what I've done is correct. I'll tag a couple people who might know for a review.

### CODE REVIEW

**Comment by brentdax** [comment]
@lhames @ributzka Can one of you take a look at 8c2aeb387cead9a6b0f4dda7e804713a58846329 and tell me if it's correct? Doing this twice seems rather strange.

**Comment by brentdax** [comment]
@swift-ci please smoke test

**Comment by lhames** [comment]
Oops — misread this.

Your resolution for the merge conflict looks good. Doing this twice is wrong, but benign — the second call will be a no-op. I can fix the rest up next week.

**Comment by brentdax** [comment]
@swift-ci please smoke test

**Comment by brentdax** [comment]
This at least gets us building on macOS. Merging it.

**Pull request merged**
