### PR TITLE
Check default arguments even if a function has no body

### PR DESCRIPTION
**Pull request by jrose-apple**
This is needed for textual interfaces, but the behavior doesn't have to be specific to that, since functions without bodies don't come up in other situations.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Review by slavapestov — APPROVED** [review]

**Comment by jrose-apple** [comment]
Oops. I saw that this test failed, but it's relying on old behavior of SourceLoader and isn't worth preserving.

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Review by harlanhaskins — APPROVED** [review]

**Comment by jrose-apple** [comment]
> 22:46:46 Failing Tests (3):
> 22:46:46     lldb-Suite :: lang/swift/conditional_breakpoints/TestSwiftConditionalBreakpoint.py
> 22:46:46     lldb-Suite :: lang/swift/stepping/TestSwiftStepping.py
> 22:46:46     lldb-Suite :: lang/swift/struct_init_display/TestSwiftStructInit.py

[These three again](https://bugs.swift.org/browse/SR-8245). @dcci, maybe it's worth re-excluding them for now?

**Comment by jrose-apple** [comment]
@swift-ci Please test Linux

**Comment by dcci** [comment]
@jrose-apple yes, I think we should exclude them again (cc: @fredriss/ @vedantk)

**Comment by dcci** [comment]
In fact, I thought they're still excluded (they're still marked as swift-test, but not swift-pr). I think this is because we now run the full suite (sorry I don't have more details, this was presumably deployed last week when I was out).

**Comment by vedantk** [comment]
The swiftpr test whitelist was disabled recently. I filed a bug tracking a fix to the underlying issue with these tests. I'll mark these tests as being fully skipped for now.

**Pull request merged**
