### PR TITLE
[PrintAsObjC] Defend against macros named 'any'

### PR DESCRIPTION
**Pull request by jrose-apple**
SourceKit uses a clever pragma to automatically attach an attribute to every declaration in the file. However, the form of this pragma (`clang attribute push`) uses a parenthesized list marked with 'any', which turns out to be a name that people sometimes use for macros. Guard against this
using the `push_macro` pragma (originally from MSVC), under the assumption that anyone who supports the highly-use-specific 'external_source_symbol' attribute probably implements this more common extension. This does make the generated header a little uglier, but it's not like it was really pretty to begin with.

rdar://problem/34168022

### CODE REVIEW

**Review by akyrtzi — APPROVED** [review]
LGTM.

**Comment by gparker42** [comment]
clang attributes often support `__thing__` in place of `thing` to help prevent macro damage. Does that not work here?

**Review by nathawes — APPROVED** [review]
LGTM too!

**Comment by jrose-apple** [comment]
> clang attributes often support `__thing__` in place of `thing` to help prevent macro damage. Does that not work here?

In this case it's part of a custom-parsed attribute syntax, so we'd have to explicitly recognize that form. @akyrtzi, would you prefer that as a fix?

**Comment by akyrtzi** [comment]
I'd suggest filing to keep track as enhancement but I don't think it is important.

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
Filed <rdar://problem/34961370> Support underscored variant of parameters to 'clang attribute push'.

**Pull request merged**
