### PR TITLE
Move `build-script` apply default arguments into separate module

### PR DESCRIPTION
**Pull request by Rostepher**
# Purpose

This PR moves the `apply_default_arguments` logic out of the main `build-script` code into the `driver_arguments` module in order to better stage for #11872 and eventually #11880. The diff will show that the move was not strictly a copy-paste, the chunk for determining if ninja ought be built requires the `toolchain` information which only exists in the `BuildScriptInvocation` class. I've opted instead to single out that single case and keep it where it was, everything else was moved verbatim.

rdar://problem/34336890

### CODE REVIEW

**Comment by Rostepher** [comment]
@swift-ci please smoke test

**Comment by Rostepher** [comment]
@swift-ci please smoke test

**Comment by Rostepher** [comment]
@swift-ci please smoke test

**Comment by Rostepher** [comment]
As soon as the builds for this branch pass I'll merge it, then onwards to #11872!

**Comment by davezarzycki** [comment]
This broke the build-script on my machine. It can no longer find ninja in /usr/local/bin. What do you need to help debug this?

**Comment by Rostepher** [comment]
@davezarzycki I've made a PR to address the issue #11919. I'll have it merged tonight or in the morning, Sorry for the inconvenience.

**Comment by tishansteve** [comment]
Can you unsubscribe me from this email service cause I don’t want any
emails from git hub

**Comment by Rostepher** [comment]
@tishansteve You can change your email preferences in your Github account settings. I can't do anything about it.

**Pull request merged**
