### PR TITLE
Bump the deployment target for the compiler to macOS 13.0

### PR DESCRIPTION
**Pull request by benlangmuir**

### CODE REVIEW

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please build toolchain

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please test Linux

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please test

**Review by ian-twilightcoder — APPROVED** [review]

**Review by etcwilde — APPROVED** [review]

**Comment by etcwilde** [comment]
CC @shahmishal

**Review by shahmishal — APPROVED** [review]

**Pull request merged**
