### PR TITLE
C11 cl

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @aschwaighofer @jckarter @slavapestov

**Comment by jmittert** [comment]
This also is included in https://github.com/apple/swift/blob/ab2f4ce43a813d09fb3193e16ed067eaba0a7a5d/include/swift/ABI/Metadata.h#L42 which looks like it may be harder to work around.

**Review by jckarter — CHANGES_REQUESTED** [review]
We're trying to avoid hardcoding the size here. Why is this change needed?

**Comment by compnerd** [comment]
@jckarter - the use of HeapObject pulls in `SwiftSwtddef.h`.  That uses constructs assuming that it will only be used with a C11 compatible compiler (well, more specifically `clang`) as it is part of the shims.  This prevents building the tools with the host compiler on Windows.

**Comment by jckarter** [comment]
Can we make SwiftStddef.h not depend on Clang somehow? The shim-iness of these headers is only important for building the runtime and standard library, so it may be OK to do something like, `#if !__clang__`, just #include the real stddef.h and typedef the standard definitions.

**Pull request closed without merging**
