### PR TITLE
Enable opening of an existential `var`

### PR DESCRIPTION
**Pull request by DougGregor**
Perform appropriate lvalue adjustments when opening a `var` of existential type. 

Fixes rdar://95874158. Thank you to @johnno1962 for doing 99% of the work here.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
macOS failure looks totally unrelated. Trying again...

**Comment by DougGregor** [comment]
@swift-ci please smoke test macOS

**Comment by DougGregor** [comment]
@swift-ci please clean smoke test macOS

**Comment by johnno1962** [comment]
Thanks for picking this up @DougGregor, checks out this end 👍

**Comment by DougGregor** [comment]
@swift-ci please clean smoke test macOS

**Comment by DougGregor** [comment]
@swift-ci please clean smoke test macOS

**Comment by DougGregor** [comment]
@swift-ci please clean smoke test macOS

**Comment by DougGregor** [comment]
@swift-ci please clean smoke test macOS

**Comment by DougGregor** [comment]
https://github.com/apple/swift-driver/pull/1140

@swift-ci please smoke test macOS

**Pull request merged**
