### PR TITLE
[libSyntax] Small improvements

### PR DESCRIPTION
**Pull request by ahoppen**
- Move error function to standalone `Utils.py` because that function really doesn’t belong in `Node.py`
- In ParsedSyntaxBuilders `child_elt_name` was inferred from the last iteration of the loop above, which was incorrect.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
```
./utils/gyb_syntax_support/Utils.py:3:1: E302 expected 2 blank lines, found 1
./utils/gyb_syntax_support/Node.py:1:1: F401 'sys' imported but unused
./utils/gyb_syntax_support/Node.py:5:1: I100 Import statements are in the wrong order. 'from .Utils import error' should be before 'from .kinds import SYNTAX_BASE_KINDS, kind_to_type, lowercase_first_word'
./utils/gyb_syntax_support/Node.py:5:1: I202 Additional newline in a group of imports. 'from .Utils import error' is identified as Application Relative and 'from .kinds import SYNTAX_BASE_KINDS, kind_to_type, lowercase_first_word' is identified as Application Relative.
./utils/gyb_syntax_support/Node.py:9:1: E303 too many blank lines (3)
```

**Comment by rintaro** [comment]
> In ParsedSyntaxBuilders child_elt_name was inferred from the last iteration of the loop above, which was incorrect.

Good catch! I don't like Python's name scope...

**Review by rintaro — APPROVED** [review]
LGTM after fixing the python-lint

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Pull request merged**
