### PR TITLE
[stdlib] Simplify buffer pointer initialization.

### PR DESCRIPTION
**Pull request by Lukasa**
UnsafeRawBufferPointer was not made self-slicing, but is instead sliced
by Slice<UnsafeRawBufferPointer>. When working with
UnsafeRawBufferPointer objects it is quite common to want to transform
back into the underlying collection, which is why the
UnsafeRawBufferPointer provides a constructor from its subsequence:
UnsafeRawBufferPointer.init(rebasing:).

Unfortunately for an initializer on this extremely low-level type, this
initializer is surprisingly expensive. When disassembled on Linux it
emits 7 separate traps and 11 branches. This relative heft means this
method often gets outlined, which is a shame, as several of the branches
could often be eliminated due to checks elsewhere in functions where
this initializer is used.

Almost all of these branches and almost all of the traps are
unnecessary. We can remove them by noting that it is impossible to
construct a Slice whose endIndex is earlier than its startIndex. All
Slice inits are constructed with bounds expressed as Range, and Range
enforces ordering on its endpoints.

For this reason, we can do unchecked arithmetic on the start and end
index of the slice, and remove 5 traps in one fell swoop. This greatly
cheapens the cost of the initializer, improving its odds of being
inlined and having even more of its branches optimised away.

For what it's worth, I also considered trying to remove the last two
preconditions. Unfortunately I concluded I couldn't confidently do that.
I wanted to remove them based on the premise that a valid Slice must
have indices that were in-bounds for its parent Collection, and so we
could safely assume that if the parent base address was nil the count
would have to be zero, and that adding start index to the base address
would definitely not overflow. However, the existence of the
Slice.init(base:bounds:) constructor led me to be a bit suspicions of
removing those checks. Given that
UnsafeRawBufferPointer.init(start:count:) enforces those invariants, I
decided it was safest for us to continue to do that.

### CODE REVIEW

**Comment by Lukasa** [comment]
@swift-ci test

**Comment by Lukasa** [comment]
CC @atrick and @gottesmm who are likely both interested here.

To the two of you: I can get rid of the last two preconditions, but doing so removes some guard rails. The two preconditions come from `init(start:count:)` and they are:

https://github.com/apple/swift/blob/887464b7b67d5202bfa7adc4e3f045ff1027a5a7/stdlib/public/core/UnsafeRawBufferPointer.swift.gyb#L435-L437

The second precondition here is impossible, for the same reason we could do unchecked subtraction on startIndex and endIndex: `Range` is ordered. So we can also kill that branch and trap. However, the other one is a bit closer to the wire. _Technically_, I can lean on the requirement that a `Slice` is only valid if both `startIndex` and `endIndex` are valid for the base `Collection`, and that when the base address is `nil` the only valid values for `startIndex` and `endIndex` are `0`. This already meets our precondition, so we can technically remove it.

However, users are capable of screwing this up because you can just whip up a `Slice` from anywhere, and unlike with `Range` it does not warn you about the danger of using `Slice.init(base:bounds:)`. In general I think I'm comfortable with removing this precondition as well and making this function essentially trivial, but I wanted your opinion here.

**Comment by Lukasa** [comment]
Worked around in SwiftNIO at #apple/swift-nio#1696.

**Comment by Lukasa** [comment]
@swift-ci test

**Comment by karwa** [comment]
> I can get rid of the last two preconditions, but doing so removes some guard rails. The two preconditions come from init(start:count:) and they are:

I'm trying to remove these in #34747 but it caused some benchmark regressions (e.g. SuffixAnySequence, +200% at -Osize is probably not noise). I haven't had a chance to investigate those in detail, but my hunch is that they allow other preconditions/overflow checks to be omitted later on. I don't think we have a way to tell the compiler "assume this statement is true, but don't trap if it isn't" (well... I kind of discovered [a way](https://bugs.swift.org/browse/SR-12805?focusedCommentId=56611&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-56611), but it's _awful_).

**Comment by Lukasa** [comment]
> I'm trying to remove these in #34747 but it caused some benchmark regressions (e.g. SuffixAnySequence, +200% at -Osize is probably not noise). I haven't had a chance to investigate those in detail, but my hunch is that they allow other preconditions/overflow checks to be omitted later on. I don't think we have a way to tell the compiler "assume this statement is true, but don't trap if it isn't" (well... I kind of discovered a way, but it's awful).

I’m not proposing to remove them in full generality, just in the specific constructor from `Slice`.

**Comment by Lukasa** [comment]
@swift-ci benchmark

**Comment by Lukasa** [comment]
@swift-ci test

**Comment by Lukasa** [comment]
@swift-ci test

**Review by ktoso — APPROVED** [review]
Fantastic stuff, Cory 👍

**Review by atrick — APPROVED** [review]
This PR itself is great. Thanks a lot! I'll add some comments to the discussion about the other possibilities.

**Comment by atrick** [comment]
@Lukasa  @lorentey I'm going to invent some rationale for when we need preconditions, so I'd like to hear what you think about it too.

I'll claim that we want preconditions the check consistency across user-provided arguments whenever we construct a value, regardless of whether the value's type is Unsafe.

For example, UBP.init(start:count:) should always check count >= 0 and non-nil start for count > 0.

When it comes to accessing that type, we may demote the argument check to a debugPrecondition, as in UBP.subscript().

On the other hand, when constructing Unsafe types, we can assume that any single argument value is already self-consistent. So, UBP.init(rebasing:) does not need to re-check the validity of Slice. After all, constructing an invalid Slice requires using Range.init(uncheckedBounds:).

So what could we do better:

- As Cory suggests, we could eliminate the remaining checks from UBP.init(rebasing:) by bypassing the checked UBP.init(start:count:). I think that would be fine.

- It seems like there's a bigger opportunity to optimize Slice.count here. Can we assume Slice is well-formed in general? Since it's not an Unsafe type, we can't really justify removing preconditions. But don't those preconditions belong on Slice construction, not access to the count? After all, users already implictly assume the start/endIndex properties are valid when they are directly accessed.

Are we confident enough that users won't misuse Slice.init(uncheckedBounds:) to do this? I did notice that Range.init(from decoder:) does not have any preconditions, which seems a little alarming.

**Comment by Lukasa** [comment]
> On the other hand, when constructing Unsafe types, we can assume that any single argument value is already self-consistent. So, UBP.init(rebasing:) does not need to re-check the validity of Slice. After all, constructing an invalid Slice requires using Range.init(uncheckedBounds:)

Disappointingly I think this isn’t true. `Slice` has this constructor:
 https://github.com/apple/swift/blob/b13a8e9ba3b4a1ae77e72f93813644a19206fc9f/stdlib/public/core/Slice.swift#L109-L114

This constructor allows an arbitrary Range and base instance to be provided for Slicing. While this constructor is _primarily_ intended for users conforming to Collection, in principle it can be used arbitrarily. Because it does not validate that the bounds are valid for the base collection, nothing prevents users doing this:

```
let base = UnsafeRawBufferPointer(start: nil, count: 0)  // Well formed
let slice = Slice(base: base, bounds: 5..<10)  // Well-formed range, ill-formed slice, no precondition
let newBase = UnsafeRawBufferPointer(rebasing: slice)  // ???
```

I think it’s totally fine to assume that `Range` is well-formed, because the type enforces the constraint unless the user volunteers to opt-out. I think it’s less obviously fine to assume that `Slice` is well-formed, and so you could argue that we need to tolerate the possibility it isn’t. The question is, does that go so far as to bounds check the Slice provided? If we don’t feel we have to bounds check that Slice, do we have to check that the base pointer is nil? Why are these cases different?

**Comment by lorentey** [comment]
I think the theory with `Slice` was that the underlying collection will perform index validation on every access anyway, so there is no need to perform any checking in the slice itself. (Beyond `_failEarlyRangeCheck`, which is a half-baked, underdocumented, non-public best-effort thing.)

Supposing the following statements are true:

- `Unsafe[Mutable][Raw]BufferPointer` intentionally does not perform any index validation in optimized builds.
- Passing a slice is intended to be semantically equivalent to passing the base collection along with a range of indices, with no guarantees whatsoever about how that range may or may not be valid in the collection.

I think it's reasonable to say that in release builds, constructing a buffer pointer from a slice must do exactly as many checks as constructing one through `init(start:count:)` -- which is none whatsoever.

(That said, we should definitely have `_debugPrecondition`s in the rebasing initializers to help people catch issues.)


If we had a time machine, I would go back to the evolution discussion & I would be arguing loudly to make these buffer types self-slicing, with pointers as their index type. Unfortunately we don't have one, so we are stuck with a one-size-fits-all SubSequence implementation on a very unusual collection type.

**Comment by lorentey** [comment]
> Are we confident enough that users won't misuse ~`Slice`~`Range.init(uncheckedBounds:)` to do this? 

Yes, definitely! But `init.(uncheckedBounds:)` is currently missing a debugPrecondition, which is rather embarrassing.

> I did notice that Range.init(from decoder:) does not have any preconditions, which seems a little alarming.

That is very alarming. It should signal invalid data by throwing an error.

**Comment by atrick** [comment]
> Then I think it's reasonable to say that in release builds, constructing a buffer pointer from a slice must do exactly as many checks as constructing one through `init(start:count:)` -- which is none whatsoever. (Edit: Except for the `count >= 0` check, which is in this case obviated by the use of `Range`, and the non-nil check, which can only be elided in a new initializer that takes a `Range<UnsafePointer>` instead of a start/count.)

Right, I was suggesting that `UBP.init(rebasing:)` should not need the `count >= 0` check or non-nil check, so it should be free.

**Comment by atrick** [comment]
@lorentey URBP was originally self-slicing (and UBP must have been too), before DaveA pointed out that generic algorithms broke because of non-transferable indices. Yeah, it's really unfortunate they don't have pointer indices, and I don't know what the historical reason for that was.

**Comment by atrick** [comment]
@Lukasa @lorentey I still don't understand why `Slice.count` needs any checks. Presumably it has an overflow check  because the default `Container.count` uses `distance`?

**Comment by lorentey** [comment]
Yeah -- Slice.count gets the default `count`, which dispatches to `distance`, which in `UMBP`'s case reduces to a subtraction:

```swift
  @inlinable // unsafe-performance
  public func distance(from start: Int, to end: Int) -> Int {
    // NOTE: this is a manual specialization of index movement for a Strideable
    // index that is required for UnsafeBufferPointer performance. The
    // optimizer is not capable of creating partial specializations yet.
    // NOTE: Range checks are not performed here, because it is done later by
    // the subscript function.
    return end - start
  }
```

Unfortunately, if we accept that calling `Slice(base: foo, bounds: Int.min..<Int.max)` is legal, then we cannot really get rid of the overflow check. (Not even in `.init(rebasing:)` 😭)

**Comment by lorentey** [comment]
We could replace `-` with `subtractingReportingOverflow`, though:

```swift
public func distance(from start: Int, to end: Int) -> Int {
  let result = end.subtractingReportingOverflow(start)
  _debugPrecondition(!result.overflow)
  return result.partialValue
}
```

**Comment by atrick** [comment]
Interesting... and annoying that a valid Range has an invalid distance

**Comment by lorentey** [comment]
Hm, expanding on the legal theory above: 

1. `Collection.distance(from:to:)` is only defined to operate on indices that are valid in the collection value at the time `distance` is called. Crucially, there is no requirement for `distance` to diagnose invalid indices -- which is why it is okay for e.g. `Array.distance(from:to:)` not to perform bounds checking on its input. Checking is still preferable to no checking, but performance concerns may override this, and in the case of `U[M]BP`, they probably should.

    If `start < end`, then ideally `base.distance(from: start, to: end)` wouldn't return a negative value. But if `start` and `end` are invalid indices, then comparing them or calculating their distance are meaningless operations -- so it is probably okay for them to return inconsistent results (such as when the subtraction overflows in `distance`).

2. `Slice` evidently does not guarantee that its `startIndex` and `endIndex` are valid indices, just that start <= end. We are technically allowed to call the `.init(base:bounds:)` initializer with indices that aren't valid in the `base` collection. However, if we do so, most operations on the resulting slice will not have well-defined results. (Except the primitive accessors `base`, `startIndex` and `endIndex`.) In particular, `slice.count` forwards to `distance` on the base collection, so it is evidently okay for it to return silly values:

    ```swift
    let slice = Slice<Range<Int>>(base: 0..<10, bounds: 1000 ..< 11000)
    slice.count // ⟹ 10000
    ```

    Returning a negative count would be especially silly. But I think it is technically allowed.

3. The `Unsafe*BufferPointer` types are special in that in release builds, their operations are allowed to invoke full-blown undefined behavior (complete with nasal demons) when they are misused. (Misuse includes passing subscripting with an out-of-bounds index, or trying to access an invalid memory location.) In debug builds, they must diagnose out-of-bounds access, but (for obvious reasons) they aren't required to detect issues with the state of the underlying memory.

So, if I understand correctly:

- `U[M]BP.distance(from:to:)` does not need to perform any bounds checking, and it is allowed to silently overflow if given invalid indices.
- `U[M]BP.Slice` is allowed to hold out-of-bounds `startIndex` and/or `endIndex` values. It doesn't matter what `count` returns in these cases.
- `U[M]BP.init(rebasing:)` is required to diagnose out-of-bounds slices *in debug builds*. (Otherwise the resulting buffer may allow obviously out-of-bounds accesses in future operations.) However, in release builds, the initializer is allowed to assume that the input slice contains valid indices.

So if all this is right, then we should probably change `U*BP.distance(from:to:)` to the `subtractingReportingOverflow` definition above and rewrite the `rebasing` initializers in this PR with versions that perform full-blown bounds checking in debug mode:

```swift
  public init(rebasing slice: Slice<UnsafeMutableBufferPointer<Element>>) {
     // We should probably not call _failEarlyRangeCheck here because creating the range arguments would likely emit unnecessary checks.
    let base = slice.base.baseAddress?.advanced(by: slice.startIndex)
    let count = slice.count
    _debugPrecondition(slice.startIndex >= 0 && slice.endIndex <= slice.base.count && (base != nil || count == 0), 
      "Invalid slice") 
    self.init(start: base, count: count)
   }
```

**Comment by Lukasa** [comment]
That sounds reasonable to me. I’ll throw together a patch to that effect today.

**Comment by lorentey** [comment]
I'm on it already 😉 -- I have a new PR integrating what we learned from #34747, #34879, and #34951 and that is coming as soon as finish fixing the test failures.

**Comment by Lukasa** [comment]
Ace, I love not doing work I don't have to!

**Pull request merged**
