### PR TITLE
[WIP] Allow operator functions to have extra arguments with default values

### PR DESCRIPTION
**Pull request by davedelong**
This changes how operator functions are detected. Before they were required to only have an explicit number of parameters that matches the operator arity. After this change, they can have extra arguments, as long as all of those arguments have default values.

The upshot of this is that you're able to create operator functions that capture things like the `#file` and `#line` of where they're used. This is incredibly useful while debugging.

### CODE REVIEW

**Comment by gottesmm** [comment]
@davedelong _waves_.

**Comment by davedelong** [comment]
I would appreciate some guidance on the SILGen and Executable tests. I've been trying to fudge together some SILGen tests by poking and prodding at existing ones, but I'm not having much success.

Also, what sorts of things should I be checking for in these tests?

**Comment by slavapestov** [comment]
In the executable test I would check that calling a simple operator with a default argument works. Perhaps the operator can just return a struct with its input values and defaulted argument, and you can check that the result is correct. For the SILGen test, ensure a call to the default argument is emitted. Look at the existing default argument tests for ideas.

**Comment by CodaFi** [comment]
@davedelong Are you still interested in pursuing this change?

**Comment by davedelong** [comment]
This is a change I would like to see made, but I am not skilled enough to make all of the necessary changes, nor do I have time to invest in figuring out what I’d need to know.

**Comment by CodaFi** [comment]
Alright.  I've filed SR-11885 to track this if you or somebody else would like to return to it.  In the mean time, I'm going to close out this pull request.

Thanks for your interest here.

**Pull request closed without merging**
