### PR TITLE
Fix `update-checkout --dump-hashes` and add `update-checkout --dump-hashes-config`

### PR DESCRIPTION
**Pull request by gmilos**
Minor fix to stop erroneous exit from `./utils/update-checkout --dump-hashes`.

Also adds `update-checkout --dump-hashes-config`. Which outputs JSON config, that can later be used with `update-checkout  --config`

### CODE REVIEW

**Comment by gottesmm** [comment]
@gmilos Just an FYI, we want to eventually drop the branch argument. The bots have just not been updated.

**Comment by gottesmm** [comment]
Actually, I am going to just fix that now.

**Comment by gottesmm** [comment]
#6793

**Comment by gottesmm** [comment]
I committed the change, so feel free to continue!

**Comment by gmilos** [comment]
@gottesmm, your PR isn't conflicting with my in any way AFAICS. Appreciate the heads up though.

**Comment by gmilos** [comment]
@gottesmm Any chance you could kick off the tests as well? I don't have the rights to do it. Thanks.

**Comment by gottesmm** [comment]
@swift-ci Please smoke test and merge

**Comment by gottesmm** [comment]
I'll do one better and get it to merge ; )

**Comment by gmilos** [comment]
@gottesmm much appreciated!

**Pull request merged**
