### PR TITLE
[NameLookup] Add requests for module and AnyObject lookup (master)

### PR DESCRIPTION
**Pull request by hamishknight**
Add `LookupInModuleRequest` for module-level lookup, and `AnyObjectLookupRequest` for AnyObject lookup.

This is a cherry-pick of https://github.com/apple/swift/pull/28395 to master.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by CodaFi** [comment]
Hm, smoke test label jobs are a little eager today.

**Review by CodaFi — APPROVED** [review]

**Comment by hamishknight** [comment]
@CodaFi I think it actually picked up the test results from the PR against `swift-incremental-dependency-tracking`

**Comment by CodaFi** [comment]
⛵️

**Pull request merged**
