### PR TITLE
[CopyPropagation] Canonicalize all values.

### PR DESCRIPTION
**Pull request by nate-chandler**
Previously, the lifetimes of only values which were copied were canonicalized during the non-mandatory CopyPropagation pass.  The mandatory pass (i.e. MandatoryCopyPropagation) has been disabled, meaning that non-copied values lifetimes were  never canonicalized.  So enable canonicalization of all lifetimes during regular CopyPropagation.

rdar://54335055

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
```
------- Performance (x86_64): -O -------

REGRESSION                                     OLD     NEW    DELTA    RATIO
PrefixWhileArrayLazy                           20      26     +30.0%   **0.77x (?)**
DifferentiationIdentity                        247     320    +29.6%   **0.77x (?)**
DifferentiationSquare                          444     537    +20.9%   **0.83x (?)**
PrefixWhileAnySeqCntRange                      114     129    +13.2%   **0.88x (?)**
RemoveWhereMoveInts                            17      19     +11.8%   **0.89x (?)**
Data.hash.Empty                                47      52     +10.6%   **0.90x (?)**

IMPROVEMENT                                    OLD     NEW    DELTA    RATIO
SortArrayInClass                               14976   311    -97.9%   **48.15x**
DropWhileArrayLazy                             49      31     -36.7%   **1.58x**
FlattenListLoop                                1379    939    -31.9%   **1.47x (?)**
FlattenListFlatMap                             4234    3004   -29.1%   **1.41x (?)**
NSArray.nonbridged.mutableCopy.objectAtIndex   578     431    -25.4%   **1.34x (?)**
NSArray.nonbridged.objectAtIndex               560     424    -24.3%   **1.32x (?)**
PrefixWhileSequenceLazy                        26      20     -23.1%   **1.30x (?)**
DropWhileAnyCollectionLazy                     49      38     -22.4%   **1.29x**
NSArray.bridged.objectAtIndex                  278     216    -22.3%   **1.29x**
NSArray.bridged.mutableCopy.objectAtIndex      733     615    -16.1%   **1.19x (?)**
DropWhileAnySeqCRangeIterLazy                  45      38     -15.6%   **1.18x (?)**
DropWhileAnySeqCntRangeLazy                    45      38     -15.6%   **1.18x (?)**
DictionarySubscriptDefaultMutation             172     148    -14.0%   **1.16x (?)**
DropWhileSequenceLazy                          67      62     -7.5%    **1.08x (?)**
PrefixArray                                    14      13     -7.1%    **1.08x (?)**
Diffing.Similar                                373     347    -7.0%    **1.07x (?)**
PrefixWhileAnySequence                         198     185    -6.6%    **1.07x (?)**

------- Code size: -O -------

IMPROVEMENT                    OLD     NEW     DELTA    RATIO
Differentiation.o              7695    6063    -21.2%   **1.27x**
SortArrayInClass.o             2708    2612    -3.5%    **1.04x**
DictionarySubscriptDefault.o   19090   18770   -1.7%    **1.02x**

------- Performance (x86_64): -Osize -------

REGRESSION                                     OLD     NEW    DELTA    RATIO
DropWhileCountableRangeLazy                    49      71     +44.9%   **0.69x (?)**
DifferentiationIdentity                        253     332    +31.2%   **0.76x (?)**
DropWhileAnySeqCRangeIterLazy                  127     166    +30.7%   **0.77x (?)**
DropWhileAnySeqCntRangeLazy                    127     166    +30.7%   **0.77x (?)**
PrefixWhileAnyCollection                       111     144    +29.7%   **0.77x (?)**
Set.filter.Int100.28k                          37      47     +27.0%   **0.79x (?)**
SequenceAlgosRange                             1740    2170   +24.7%   **0.80x (?)**
Set.filter.Int100.16k                          21      26     +23.8%   **0.81x (?)**
Set.filter.Int100.20k                          26      32     +23.1%   **0.81x (?)**
Set.filter.Int100.24k                          31      38     +22.6%   **0.82x (?)**
DifferentiationSquare                          443     541    +22.1%   **0.82x**
SequenceAlgosArray                             1860    2180   +17.2%   **0.85x (?)**
ObjectiveCBridgeStubDateAccess                 130     152    +16.9%   **0.86x (?)**
PrefixWhileAnyCollectionLazy                   94      107    +13.8%   **0.88x (?)**
PrefixWhileAnySequence                         188     213    +13.3%   **0.88x (?)**
RemoveWhereMoveInts                            19      21     +10.5%   **0.90x (?)**
RemoveWhereQuadraticString                     186     201    +8.1%    **0.93x (?)**
LineSink.scalars.complex                       137     148    +8.0%    **0.93x (?)**

IMPROVEMENT                                    OLD     NEW    DELTA    RATIO
SortArrayInClass                               15158   403    -97.3%   **37.61x**
PrefixWhileCountableRangeLazy                  40      21     -47.5%   **1.90x (?)**
PrefixWhileSequenceLazy                        40      26     -35.0%   **1.54x**
DropWhileSequenceLazy                          71      49     -31.0%   **1.45x**
NSArray.nonbridged.objectAtIndex               568     424    -25.4%   **1.34x (?)**
NSArray.nonbridged.mutableCopy.objectAtIndex   577     431    -25.3%   **1.34x (?)**
RecursiveOwnedParameter                        327     251    -23.2%   **1.30x (?)**
PrefixWhileArrayLazy                           26      20     -23.1%   **1.30x (?)**
NSArray.bridged.objectAtIndex                  278     216    -22.3%   **1.29x**
NSStringConversion.UTF8                        718     592    -17.5%   **1.21x (?)**
NSArray.bridged.mutableCopy.objectAtIndex      733     619    -15.6%   **1.18x (?)**
NSStringConversion.Medium                      354     299    -15.5%   **1.18x (?)**
NSStringConversion.InlineBuffer.ASCII          293     257    -12.3%   **1.14x (?)**
SequenceAlgosContiguousArray                   1920    1710   -10.9%   **1.12x (?)**
Set.isSuperset.Seq.Empty.Int                   45      41     -8.9%    **1.10x (?)**
Set.isSubset.Int.Empty                         45      41     -8.9%    **1.10x (?)**
NSStringConversion.Long                        708     649    -8.3%    **1.09x (?)**
StringWalk                                     3520    3240   -8.0%    **1.09x (?)**
PrefixWhileAnySequenceLazy                     1179    1086   -7.9%    **1.09x (?)**
PrefixAnySequenceLazy                          1192    1112   -6.7%    **1.07x (?)**

------- Code size: -Osize -------

REGRESSION           OLD     NEW     DELTA    RATIO
Hash.o               18682   18997   +1.7%    **0.98x**

IMPROVEMENT          OLD     NEW     DELTA    RATIO
Differentiation.o    7225    5881    -18.6%   **1.23x**
SortArrayInClass.o   2956    2876    -2.7%    **1.03x**

------- Performance (x86_64): -Onone -------

REGRESSION                                        OLD     NEW    DELTA    RATIO
NSStringConversion.InlineBuffer.ASCII             5890    6705   +13.8%   **0.88x (?)**
NSStringConversion.InlineBuffer.UTF8              3606    4075   +13.0%   **0.88x (?)**

IMPROVEMENT                                       OLD     NEW    DELTA    RATIO
CharIteration_punctuatedJapanese_unicodeScalars   10360   9680   -6.6%    **1.07x (?)**

------- Code size: -swiftlibs -------
```

**Review by atrick — APPROVED** [review]
Good. This means the lifetime of owned values will be consistently canonicalized, within the new boundaries of lexical lifetimes.

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test macos platform

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test macos platform

**Comment by nate-chandler** [comment]
@swift-ci please test linux platform

**Comment by nate-chandler** [comment]
@swift-ci please clean test macos platform

**Comment by nate-chandler** [comment]
@swift-ci please clean test linux platform

**Comment by atrick** [comment]
Thanks for fixing the outliner to handle consuming arguments. It's good to have this pass working well with OSSA!

**Comment by nate-chandler** [comment]
@swift-ci please clean test linux platform

**Comment by atrick** [comment]
@nate-chandler I just realized this never landed. Anything holding it up?

**Comment by nate-chandler** [comment]
There were some docs test failures earlier.  Let's see if those were spurious.

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Pull request merged**
