### PR TITLE
Cleanup: move ArrayPropertyOpt out of COWArrayOpt.cpp.

### PR DESCRIPTION
**Pull request by atrick**
These are separate, mostly unrelated passes. Putting them in their own
files makes it easier to read the code, understand how to control the
passes, and makes it possible to independently trace, and debug them.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test

**Review by aschwaighofer — APPROVED** [review]
lgtm

**Comment by atrick** [comment]
This is part of my work to consolidate SILCloner logic and fully ban address-type block args.

**Comment by atrick** [comment]
@swift-ci smoke test and merge

**Pull request merged**
