### PR TITLE
[AutoDiff] Add a code path for loadable types in AdjointEmitter

### PR DESCRIPTION
**Pull request by rxwei**
* Add a code path for loadable types in AdjointEmitter.
* Switch to floating point scalar initialization.
* Add division test (pending [SR-8584](https://bugs.swift.org/browse/SR-8584)).

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by shahmishal** [comment]
@swift-ci please test tensorflow Linux GPU

**Comment by shahmishal** [comment]
@swift-ci test testsorflow macOS

**Comment by shahmishal** [comment]
@rxwei Please ignore the macOS Platform with GPU. 

@swift-ci test testsorflow macOS

**Comment by shahmishal** [comment]
@swift-ci test testsorflow macOS

**Comment by shahmishal** [comment]
@swift-ci test testsorflow macOS

**Comment by shahmishal** [comment]
@swift-ci test tensorflow macOS

**Comment by shahmishal** [comment]
@rxwei Please ignore the macOS Platform with GPU.

**Comment by rxwei** [comment]
Great. Thanks for setting up the commands!

**Comment by rxwei** [comment]
@marcrasi FYI.

**Pull request closed without merging**
