### PR TITLE
[stdlib] Use write(2) in print()

### PR DESCRIPTION
**Pull request by ianpartridge**
Opening for feedback/comment.

Use write(2) instead of iterating calling putchar_unlocked() repeatedly, in print()

### CODE REVIEW

**Comment by gribozavr** [comment]
Calling `putchar()` ensures that we play nicely with C's stdio.  If we call `write()`, we would not be synchronized with stdio, and we would be responsible for implementing our own buffering.

**Comment by ianpartridge** [comment]
But the write() is wrapped by flockfile() and funlockfile() - doesn't this ensure synchronisation?

**Comment by gribozavr** [comment]
I don't think that ensures synchronization with stdio.  Even if that ensured the synchronization part, stdio still has its own buffers, which we would have to force-flush every time we avoid stdio.

**Comment by ianpartridge** [comment]
If I am reading `man flockfile` correctly, it does ensure synchronisation.

Perhaps a better solution is `fwrite(3)` though?  This is the stdio function which will handle buffering etc, so no flushing required.

**Comment by gribozavr** [comment]
@ianpartridge Yes, `fwrite` would be a better choice that cooperates with stdio buffering.

**Comment by ianpartridge** [comment]
OK I will open a new pull request to do that. Thanks!

**Pull request closed without merging**
