### PR TITLE
Disallow some implicit pointer conversions in autoclosures.

### PR DESCRIPTION
**Pull request by rudkx**
Disallow implicit conversion or arguments from Array, String, and
InOut (formed by &) to pointer types if the argument is for an
@autoclosure parameter.

These conversions were really only intended to be used for C/ObjC
interop, and in some contexts like autoclosures they are not safe.

Fixes: rdar://problem/31538995

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
The diagnostics for the `&` cases here are unfortunate.

**Comment by rudkx** [comment]
@slavapestov I renamed an existing (and oddly named) locator to directly track type matches on the result of an auto closure expr.

**Review by xedin — APPROVED** [review]
LGTM!

**Comment by rudkx** [comment]
https://github.com/apple/swift-corelibs-foundation/pull/1552

@swift-ci Please smoke test Linux platform

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Pull request merged**
