### PR TITLE
[DO NOT MERGE] Forward driver calls to new driver if new driver exists

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please build toolchain

**Comment by davidungar** [comment]
I like it, but can you imagine there might be a situation where one would want to disable the forwarding in a particular case without deleting `swift-driver`? MIght a `-disable-swift-driver` option be useful?

**Comment by nkcsgexi** [comment]
@davidungar Thank you for taking a look! I don't currently plan to merge this commit. This is to facilitate automated testing for real-world projects.

**Comment by davidungar** [comment]
> @davidungar Thank you for taking a look! I don't currently plan to merge this commit. This is to facilitate automated testing for real-world projects.

My pleasure. I actually really like the idea, and suspect there will come a time when we want to merge this.

**Comment by nkcsgexi** [comment]
@swift-ci please build toolchain

**Comment by nkcsgexi** [comment]
@swift-ci please build toolchain

**Comment by nkcsgexi** [comment]
@swift-ci please build toolchain

**Pull request closed without merging**
