### PR TITLE
Allow cross-actor calls to synchronous global actor functions.

### PR DESCRIPTION
**Pull request by DougGregor**
... and add some tests I've had lying around locally.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@swift-ci please smoke test macOS

**Comment by DougGregor** [comment]
@swift-ci please smoke test macOS

**Review by ktoso — APPROVED** [review]
LGTM :)

**Pull request merged**
