### PR TITLE
SILCombine: Handle result conversions for apply (convert_function) peephole

### PR DESCRIPTION
**Pull request by jckarter**
If a `convert_function` instruction operates on a function with indirect
results, or changes the type of direct results, then we can transform
an application of the converted function into an application of the
original function followed by bitwise conversions of the results, just
like we have done for arguments. Now that closures are emitted at their
context abstraction level, they are more likely to be emitted with
indirect results, so the inability to simplify function conversions
in this case would lead to missed inlining opportunities we used to
take.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please benchmark

**Comment by drexin** [comment]
@swift-ci benchmark

**Comment by drexin** [comment]
### Performance (x86_64): -O

**Improvement**              | **OLD** | **NEW** | **DELTA** | **RATIO**
:---                         | ---: | ---: | ---:  | ---:     
FlattenListFlatMap           | 2796 | 2583 | -7.6% | **1.08x (?)**
DictionaryKeysContainsCocoa  | 15   | 14   | -6.7% | **1.07x (?)**
DictionaryKeysContainsNative | 15   | 14   | -6.7% | **1.07x (?)**

### Code size: -O


### Performance (x86_64): -Osize

**Improvement**         | **OLD** | **NEW** | **DELTA** | **RATIO**
:---                    | ---: | ---: | ---:  | ---:     
DropFirstArray          | 14   | 13   | -7.1% | **1.08x (?)**
Dict.FilterAllMatch.28k | 1176 | 1097 | -6.7% | **1.07x (?)**
FlattenListFlatMap      | 3670 | 3426 | -6.6% | **1.07x (?)**

### Code size: -Osize


### Performance (x86_64): -Onone

**Improvement**                | **OLD** | **NEW** | **DELTA** | **RATIO**
:---                           | ---: | ---: | ---:  | ---:     
ObjectiveCBridgeStubDateAccess | 3598 | 3301 | -8.3% | **1.09x (?)**

### Code size: -swiftlibs

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test source compatibility

**Comment by jckarter** [comment]
@swift-ci Please test

**Pull request merged**
