### PR TITLE
[ConstraintSystem] Add new FailureDiagnostic abstraction

### PR DESCRIPTION
**Pull request by xedin**
Aim of this new diagnostic abstraction is to encapsulate each
individual failure into its own class with some shared base.
Good example of this - diagnostics related to generic requirement
failures, where each kind (conformance, same-type etc.) has
some specific logic e.g. diagnostic message but the all share
the same traits like affected declaration/requirement.

Currently ported conformance and labeling failure diagnostics.

### CODE REVIEW

**Review by slavapestov — COMMENTED** [review]
It might be better to put the new code in a new header and source file, since CSDiag is a collection of largely-unrelated code

**Comment by xedin** [comment]
@slavapestov Absolutely! I'm trying to make sure that the new abstraction makes sense, and if so I can put it into `Diagnostics{.h, .cpp}`

**Comment by xedin** [comment]
@swift-ci please clean test

**Review by DougGregor — APPROVED** [review]
This looks much cleaner! At the risk of being annoying... can we call the new files `CSDiagnostics.(h|cpp)`? I find the prefixes to be very useful in narrowing down the files I'm looking for.

**Comment by xedin** [comment]
@DougGregor Sure! :)

**Review by rudkx — APPROVED** [review]
LGTM and +1 on leaving `CS` on the beginning of anything related to the constraint system.

**Comment by xedin** [comment]
Done, files are now named `CSDiagnostics.(h, cpp)`

**Comment by xedin** [comment]
@swift-ci please clean test

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Comment by xedin** [comment]
@swift-ci please smoke test Linux platform

**Comment by xedin** [comment]
There are couple lldb related failures, which shouldn't be related to diagnostic changes...

**Comment by xedin** [comment]
@swift-ci please smoke test Linux platform

**Comment by xedin** [comment]
More precisely:

```
19:33:25     lldb :: tools/lldb-mi/exec/exec-next-instruction.test
19:33:25     lldb :: tools/lldb-mi/exec/exec-next.test
19:33:25     lldb :: tools/lldb-mi/exec/exec-step-instruction.test
19:33:25     lldb :: tools/lldb-mi/exec/exec-step.test
```

**Pull request merged**
