### PR TITLE
[Runtime] Change ProtocolCache, NominalCache, and HashableConformances to ConcurrentReadableHashMap.

### PR DESCRIPTION
**Pull request by mikeash**
rdar://problem/70220804

### CODE REVIEW

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by jckarter** [comment]
Looks good! Any idea what the performance difference is?

**Comment by mikeash** [comment]
I was thinking these aren't on critical paths, but now that you mention it, I'm not so sure. Let's see what benchmarks have to say.

**Comment by mikeash** [comment]
@swift-ci please benchmark

**Comment by mikeash** [comment]
Everything has a (?) on it, but that still looks better than I expected.

**Comment by jckarter** [comment]
Nice! AnyHashable is probably on the hot path for set/dictionary bridging, at least, so I would expect there to be some potential movement in bridging tests, at least.

**Comment by mikeash** [comment]
Oh, good point. And the performance improvement ought to be even better in real apps, where the caches will be larger. Neat.

**Pull request merged**
