### PR TITLE
[CSBindings] Refactor `getPotentialBindings` into `inferBindingsFor` + `infer`

### PR DESCRIPTION
**Pull request by xedin**
Split `getPotentialBindings` in two:

- `inferBindingsFor` should take responsibility for finding constraints
   to be evaluated as potential binding sources;
- `PotentialBindings::infer` would process constraints provided by
   `inferBindingsFor` and "extract" bindings from them.

This is done to separate "sourcing" logic from "inference" and
make the former pluggable, so bindings could be computed based
on changes in constraint graph in the future.

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test source compatibility release

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility release

**Comment by xedin** [comment]
@swift-ci please smoke test

**Review by hborla — APPROVED** [review]
LGTM!

**Pull request merged**
