### PR TITLE
Update CMakeLists.txt

### PR DESCRIPTION
**Pull request by compnerd**
Add a lowercase spelling for ARM64.  For some reason in CMake's infinite wisdom where it matches strings case insensitively, it performs a case sensitive match in this case.  :sigh:

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Review by etcwilde — APPROVED** [review]
Ha, that's funny.

**Comment by llvm-beanz** [comment]
Can confirm, this patch resolves CMake configuration failures on Apple M1 build hosts.

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Pull request merged**
