### PR TITLE
SILCloner: fix critical edge handling; remove previous workarounds

### PR DESCRIPTION
**Pull request by atrick**
There are multiple reasons this is needed.

    1. Most passes do not perform CFG transformations. However, we often
    need to split critical edges and remember to invalidate all SIL
    analyses at the end of virtually every pass. This is very innefficient
    and highly bug prone.

    2. Many SIL analysis algorithms needs to reason about CFG
    edges. Avoiding critical edges leads to far simpler and more efficient
    designs when edges can be identified by blocks.

    3. Handling block arguments on conditional branches create complexity
    at the lowest level of the SIL interface. This complexity is difficult
    to abstract over and bleeds until any algorithm that needs to reason
    about phi operands. It's far easier to work with phis if we can easily
    recover the phi operand with only a reference to the predecessor
    block.

    4. Attempting to preserve critical edges in high-level and mid-level IR
    prevents optimization that otherwise have no business optimizing
    branches. Branch optimization should always be defered to machine
    level IR where the most relevant heuristics are employed to remove
    unconditional branches. If code didn't need to be placed on a critical
    edges, then a branch optimization can easily remove that code from the
    critical edge.

### CODE REVIEW

**Comment by atrick** [comment]
TODO: This verification should be tied to OSSA form so we can incrementally migrate the .sil tests.

**Comment by atrick** [comment]
@meg-gupta @gottesmm I plan to check-in some form of this once I'm back from vacation. I posted this so you can see what i'm planning in case you're working on SimplifyCFG, ArrayPropertyOpts, LoopRotate, LoopUnroll.

Basically, we should avoid creating critical edges when transforming the CFG. Otherwise, SIL is in an invalid state for some arbitrary time when other utilities can run. Waiting to the end of the pass and calling `splitCriticalEdge` is not a good solution.

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci benchmark

**Comment by atrick** [comment]
@swift-ci test source compatibility

**Comment by atrick** [comment]
AFAICT the apparent -O regressions are caused by code alignment. The disassembly in the hot loops are identical.

**Comment by atrick** [comment]
@swift-ci smoke test linux

**Comment by gottesmm** [comment]
Thats a lot of nice workarounds removed!

**Pull request merged**
