### PR TITLE
[interop] adopt a swift-6 interoperability mode for new features in t…

### PR DESCRIPTION
**Pull request by hyp**
…he next release

### CODE REVIEW

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test source compatibility

**Review by egorzhdan — APPROVED** [review]
Thanks!
I wonder if we should also update all of the stdlib tests that pass `-cxx-interoperability-mode=upcoming-swift` to also pass `-cxx-interoperability-mode=swift-6`, but that doesn't have to happen in this PR 🙂

**Comment by hyp** [comment]
@swift-ci please smoke test

**Comment by hyp** [comment]
@swift-ci please test

**Pull request merged**
