### PR TITLE
[overlay] Add Metal, MetalKit overlays, and new APIs to ARKit

### PR DESCRIPTION
**Pull request by moiseev**

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by shahmishal** [comment]
@swift-ci Please clean test

**Comment by moiseev** [comment]
@swift-ci Please test Linux platform

**Comment by moiseev** [comment]
@swift-ci Please clean test Linux platform

**Comment by moiseev** [comment]
@swift-ci Please test macOS platform

**Pull request merged**
