### PR TITLE
utils: simplify the lldb build-script-impl invocation

### PR DESCRIPTION
**Pull request by compnerd**
Merge the cmake invocation for lldb on MacOS and the other targets.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @adrian-prantl @fredriss @dcci @Rostepher

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by adrian-prantl** [comment]
This looks good assuming that it is NFC?

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by weliveindetail** [comment]
Interesting, the log doesn't tell which CMake version is used right? As the Linux bot runs Xenial and complains about < 3.7, I guess it's still on the 3.5.1 default. The macOS one reports Xcode 10.1 GM, which ships 3.9.3 I believe. Same versions on all bots might be preferable in the future.

**Review by weliveindetail — APPROVED** [review]
Apart from the `LLDB_BUILD_FRAMEWORK` setting, this looks good to me. It's a good first step in a long way. Thanks!

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Pull request merged**
