### PR TITLE
IRGen: Access concrete type metadata by mangled name.

### PR DESCRIPTION
**Pull request by jckarter**
When we generate code that asks for complete metadata for a fully concrete specific type that
doesn't have trivial metadata access, like `(Int, String)` or `[String: [Any]]`,
generate a cache variable that points to a mangled name, and use a common accessor function
that turns that cache variable into a pointer to the instantiated metadata. This saves a bunch
of code size, and should have minimal runtime impact, since the demangling of any string only
has to happen once.

This mostly just works, though it exposed a couple of issues:

- Mangling a type ref including objc protocols didn't cause the objc protocol record to get
  instantiated. Fixed as part of this patch.
- The runtime type demangler doesn't correctly handle retroactive conformances. If there are
  multiple retroactive conformances in a process at runtime, then even though the mangled string
  refers to a specific conformance, the runtime still just picks one without listening to the
  mangler. This is left to fix later, rdar://problem/53828345.

There is some more follow-up work that we can do to further improve the gains:

- We could improve the runtime-provided entry points, adding versions that don't require size
  to be cached, and which can handle arbitrary metadata requests. This would allow for mangled
  names to also be used for incomplete metadata accesses and improve code size of some generic
  type accessors. However, we'd only be able to take advantage of the new entry points in
  OSes that ship a new runtime.
- We could choose to always symbolic reference all type references, which would generally reduce
  the size of mangled strings, as well as make runtime demangling more efficient, since it wouldn't
  need to hit the runtime caches. This would however require that we be able to handle symbolic
  references across files in the MetadataReader in order to avoid regressing remote mirror
  functionality.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test compiler performance

**Comment by jckarter** [comment]
@swift-ci Please benchmark

**Comment by jckarter** [comment]
@swift-ci Please benchmark

**Comment by jckarter** [comment]
The performance numbers look reasonable to my untrained eye; the ones that are out of the 1x band all look too variable to get much signal from. @palimondo would you agree?

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test source compatibility

**Comment by jckarter** [comment]
@swift-ci Please test compiler performance

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test source compatibility

**Comment by jckarter** [comment]
@swift-ci Please test compiler performance

**Comment by jckarter** [comment]
@swift-ci Please test Linux

**Comment by jckarter** [comment]
@swift-ci Please benchmark

**Comment by jckarter** [comment]
@swift-ci Please test source compatibility

**Comment by palimondo** [comment]
That’s a lot of numbers from the benchmarks! On a first glance: The most recent run (after the force-push) looks much less intrusive than the first two. Should I look more closely?

**Comment by palimondo** [comment]
The regression in `-O` benchmark `PrefixArrayLazy` concerns me. Could you have a closer look there, please?

**Comment by palimondo** [comment]
Also the regressions and improvements in`-Osize` benchmarks for sequence operations (`Drop*`, `Prefix*`, `Suffix*`) seems to indicate the heuristic needs more tuning?

**Comment by jckarter** [comment]
@palimondo `PrefixArrayLazy` also seems noisy to me, since it didn't show up at all in the first benchmark run (against identical code), and in the second run, it's both 0.58x slower at -O and 1.86x faster at -Osize, when the difference in optimization passes should not make that much of a difference.

**Comment by jckarter** [comment]
Source compat failure in RxSwift looks unrelated:

```
CompileSwift normal x86_64 /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/macOS/NSTextView+Rx.swift (in target 'RxCocoa' from project 'Rx')
    cd /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift
    /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/build/compat_macos/install/toolchain/usr/bin/swift -frontend -c /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UISlider+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UIScrollView+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/macOS/NSSlider+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UIPickerView+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Foundation/Logging.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UIWebView+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/macOS/NSControl+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Common/DelegateProxyType.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Common/RxTarget.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UITextView+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/DataSources/RxTableViewReactiveArrayDataSource.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Traits/Driver/BehaviorRelay+Driver.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/Proxies/RxCollectionViewDataSourceProxy.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Traits/SharedSequence/SchedulerType+SharedSequence.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/Proxies/RxTextStorageDelegateProxy.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Traits/Driver/Driver.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/Proxies/RxTableViewDelegateProxy.swift -primary-file /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/macOS/NSTextView+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UIRefreshControl+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UIStepper+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Traits/Signal/ObservableConvertibleType+Signal.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Traits/ControlEvent.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Traits/Signal/ControlEvent+Signal.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UIImageView+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/Proxies/RxPickerViewDataSourceProxy.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UIControl+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Common/Binder.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Common/SectionedViewDataSourceType.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/Proxies/RxCollectionViewDataSourcePrefetchingProxy.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UISearchController+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/macOS/NSImageView+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UITableView+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Common/RxCocoaObjCRuntimeError+Extensions.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/DataSources/RxCollectionViewReactiveArrayDataSource.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Foundation/URLSession+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/Proxies/RxSearchControllerDelegateProxy.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/Proxies/RxCollectionViewDelegateProxy.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UIAlertAction+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/Proxies/RxScrollViewDelegateProxy.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Foundation/KVORepresentable.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Common/TextInput.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UILabel+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Traits/Driver/ControlEvent+Driver.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Traits/Driver/Driver+Subscription.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UINavigationItem+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UIPageControl+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/Proxies/RxSearchBarDelegateProxy.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/Protocols/RxPickerViewDataSourceType.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Traits/Signal/Signal+Subscription.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Common/KeyPathBinder.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UITabBarItem+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UIApplication+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/Proxies/RxPickerViewDelegateProxy.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/RxCocoa.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Traits/SharedSequence/SharedSequence.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Traits/SharedSequence/SharedSequence+Operators+arity.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UITabBarController+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Foundation/NSObject+Rx+RawRepresentable.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UIView+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/DataSources/RxPickerViewAdapter.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Foundation/KVORepresentable+CoreGraphics.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Common/Observable+Bind.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Deprecated.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UISegmentedControl+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UIProgressView+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UIViewController+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/macOS/NSButton+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/macOS/NSTextField+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Traits/Signal/PublishRelay+Signal.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Traits/Signal/Signal.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/macOS/NSView+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UIButton+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Traits/SharedSequence/ObservableConvertibleType+SharedSequence.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Traits/ControlProperty.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/Proxies/RxTabBarControllerDelegateProxy.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Traits/SharedSequence/SharedSequence+Operators.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UIActivityIndicatorView+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/NSTextStorage+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/Proxies/RxTextViewDelegateProxy.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Foundation/KVORepresentable+Swift.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Traits/Driver/ObservableConvertibleType+Driver.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/Proxies/RxNavigationControllerDelegateProxy.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UIBarButtonItem+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Foundation/NSObject+Rx+KVORepresentable.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UIDatePicker+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/Proxies/RxTableViewDataSourceProxy.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Common/NSLayoutConstraint+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UIGestureRecognizer+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Traits/Driver/ControlProperty+Driver.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Common/DelegateProxy.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Foundation/NSObject+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UINavigationController+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UITabBar+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/Proxies/RxTabBarDelegateProxy.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UISwitch+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UICollectionView+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/Protocols/RxCollectionViewDataSourceType.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Platform/DispatchQueue+Extensions.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UITextField+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/Proxies/RxWebViewDelegateProxy.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/UISearchBar+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Foundation/NotificationCenter+Rx.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/Events/ItemEvents.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/Common/ControlTarget.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/Protocols/RxTableViewDataSourceType.swift /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/iOS/Proxies/RxTableViewDataSourcePrefetchingProxy.swift -emit-module-path /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/build/Build/Intermediates.noindex/Rx.build/Debug/RxCocoa.build/Objects-normal/x86_64/NSTextView+Rx\~partial.swiftmodule -emit-module-doc-path /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/build/Build/Intermediates.noindex/Rx.build/Debug/RxCocoa.build/Objects-normal/x86_64/NSTextView+Rx\~partial.swiftdoc -serialize-diagnostics-path /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/build/Build/Intermediates.noindex/Rx.build/Debug/RxCocoa.build/Objects-normal/x86_64/NSTextView+Rx.dia -emit-dependencies-path /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/build/Build/Intermediates.noindex/Rx.build/Debug/RxCocoa.build/Objects-normal/x86_64/NSTextView+Rx.d -emit-reference-dependencies-path /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/build/Build/Intermediates.noindex/Rx.build/Debug/RxCocoa.build/Objects-normal/x86_64/NSTextView+Rx.swiftdeps -target x86_64-apple-macos10.9 -enable-objc-interop -sdk /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -I /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/build/Build/Products/Debug -F /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/build/Build/Products/Debug -application-extension -enable-testing -g -import-underlying-module -module-cache-path /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/build/ModuleCache.noindex -swift-version 5 -enforce-exclusivity=checked -Onone -D TRACE_RESOURCES -D DEBUG -serialize-debugging-options -enable-anonymous-context-mangled-names -Xcc -I/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/build/Build/Intermediates.noindex/Rx.build/Debug/RxCocoa.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/build/Build/Intermediates.noindex/Rx.build/Debug/RxCocoa.build/RxCocoa-generated-files.hmap -Xcc -I/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/build/Build/Intermediates.noindex/Rx.build/Debug/RxCocoa.build/RxCocoa-own-target-headers.hmap -Xcc -I/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/build/Build/Intermediates.noindex/Rx.build/Debug/RxCocoa.build/RxCocoa-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/build/Build/Intermediates.noindex/Rx.build/Debug/RxCocoa.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/build/Build/Intermediates.noindex/Rx.build/Debug/RxCocoa.build/RxCocoa-project-headers.hmap -Xcc -I/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/build/Build/Products/Debug/include -Xcc -I/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/build/Build/Intermediates.noindex/Rx.build/Debug/RxCocoa.build/DerivedSources-normal/x86_64 -Xcc -I/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/build/Build/Intermediates.noindex/Rx.build/Debug/RxCocoa.build/DerivedSources/x86_64 -Xcc -I/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/build/Build/Intermediates.noindex/Rx.build/Debug/RxCocoa.build/DerivedSources -Xcc -DDEBUG=1 -Xcc -DTRACE_RESOURCES=1 -Xcc -ivfsoverlay -Xcc /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/build/Build/Intermediates.noindex/Rx.build/Debug/RxCocoa.build/unextended-module-overlay.yaml -Xcc -working-directory/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift -module-name RxCocoa -o /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/build/Build/Intermediates.noindex/Rx.build/Debug/RxCocoa.build/Objects-normal/x86_64/NSTextView+Rx.o
/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/project_cache/RxSwift/RxCocoa/macOS/NSTextView+Rx.swift:20:12: error: 'NSTextView' is incompatible with 'weak' references
    public weak private(set) var textView: NSTextView?
           ^~~~~
```

**Comment by palimondo** [comment]
> PrefixArrayLazy also seems noisy to me

I'm looking into it, but my general stance is: there are no noisy benchmarks.

**Comment by palimondo** [comment]
Just to clarify, the first two benchmark runs here were done on identical code, correct? If so, I really have a beef with the `run_smoke_bench`… I'm working on something to fix that.

**Comment by jckarter** [comment]
@palimondo Yeah, I ran it twice on the same code to begin with. (For the third one, I was more interested in the code size benchmarks.)

**Comment by palimondo** [comment]
Did you see anything similarly strange when running benchmarks locally? (Did you use `Benchmark_Driver` or `run_smoke_bench` for that?)

**Comment by jckarter** [comment]
@palimondo I hadn't tried running locally. I'll give that a shot.

**Comment by jckarter** [comment]
@swift-ci Please benchmark

**Comment by jckarter** [comment]
@swift-ci Please benchmark

**Comment by palimondo** [comment]
JFC! I'll have more robust `run_smoke_bench` PR up in few minutes…

**Comment by jckarter** [comment]
@swift-ci Please benchmark

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test Linux

**Comment by jckarter** [comment]
@swift-ci Please test Linux

**Comment by jckarter** [comment]
So I investigated the size and performance regressions, and they look like about what I'd expect—increased one-time initialization time from demangling, and size increases from the added mangled names themselves. In both cases, the effect only really seems noticeable in smaller programs, and I have followup work planned to mitigate both issues. Having mangled names always symbolic-reference nominal types ought to significantly decrease both demangling time and mangled string size.

**Pull request merged**
