### PR TITLE
[cxx-interop] Fix libstdc++ test failure with Ubuntu 18.04

### PR DESCRIPTION
**Pull request by egorzhdan**
When importing an older version of libstdc++, the decls might get printed in a different order. This change makes the test work properly for libstdc++-7 as well as libstdc++-9.

rdar://91518316

### CODE REVIEW

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please test Ubuntu 18.04 platform

**Comment by egorzhdan** [comment]
@swift-ci please test Ubuntu 18.04 platform

**Comment by egorzhdan** [comment]
@swift-ci Please test Ubuntu 18.04 platform

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test Linux

**Review by eeckstein — APPROVED** [review]

**Comment by eeckstein** [comment]
@egorzhdan This test now fails at https://ci.swift.org/job/oss-swift-package-centos-7/323/console

**Pull request merged**
