### PR TITLE
 [ParseableInterfaces] Re-escape multi-line strings in attribute messages

### PR DESCRIPTION
**Pull request by harlanhaskins**
Previously, we would print multi-line string literals with single quotes, which were not re-parseable. Instead, re-escape their contents and print them out escaped.

rdar://47682919

### CODE REVIEW

**Comment by harlanhaskins** [comment]
cc: @johnno1962 Is this the right use of this API?

**Comment by johnno1962** [comment]
LGTM, or you could instantiate an EncodedDiagnosticMessage if TypeChecker.h is available.
```
    EncodedDiagnosticMessage EncodedMessage(Attr->Message);
    diagnose(ReferenceRange.Start, diag::availability_deprecated_msg,
             RawAccessorKind, Name, Attr->hasPlatform(), Platform,
             Attr->Deprecated.hasValue(), DeprecatedVersion,
             EncodedMessage.Message) // EncodedMessage.Message is the encoded string.
      .highlight(Attr->getRange());
```

**Comment by harlanhaskins** [comment]
@johnno1962 Unfortunately this is in the AST, so we don’t have the typechecker.

**Comment by johnno1962** [comment]
👍

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test

**Review by jrose-apple — APPROVED** [review]

**Pull request merged**
