### PR TITLE
Enable a bunch of IRGen tests that are x86 only for arm64 too

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test Windows platform

**Review by compnerd — APPROVED** [review]
I guess it's really meant to be SIZEOF_POINTER == 8?  Perhaps we should add that as a lit feature?

**Comment by kubamracek** [comment]
Yeah, I guess you're right, and actually lit already supports that under `REQUIRES: PTRSIZE=64`.

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Thanks for the cleanup!

**Pull request merged**
