### PR TITLE
[Windows] Allow sourcekit-lsp to import swift-crypto

### PR DESCRIPTION
**Pull request by ahoppen**
Companion of https://github.com/apple/sourcekit-lsp/pull/859

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
https://github.com/apple/sourcekit-lsp/pull/859 

@swift-ci Please test Windows

**Review by compnerd — APPROVED** [review]

**Comment by ahoppen** [comment]
https://github.com/apple/sourcekit-lsp/pull/859

@swift-ci Please test Windows

**Comment by ahoppen** [comment]
https://github.com/apple/sourcekit-lsp/pull/859

@swift-ci Please smoke test

**Pull request merged**
