### PR TITLE
[build-script] Add an option to only run executable tests. Off by def…

### PR DESCRIPTION
**Pull request by gottesmm**
…ault.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by compnerd** [comment]
I'm not sure I fully understand under what conditions this is particularly useful (e.g. the non-executable-tests only allow you to test CodeGen for foreign targets).  This on the other hand only runs the executable tests, which I assume is a means of running tests which can run locally.  I think that having another option such as `-native_only` would be better (there is no reason to disallow the CodeGen tests which can run locally).  Alternatively - since I believe the goal here is to ease standard library development, add an option to run the standard library test suite only (split the two category of tests out).

**Comment by gottesmm** [comment]
@compnerd I am not trying to run tests that can only run locally. I am trying to run all executable tests. That is it. I am fine doing renamings later if you want. I want to get this in now so lets do it in a follow up.

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Pull request merged**
