### PR TITLE
build: explicitly pass the path to python2,python3

### PR DESCRIPTION
**Pull request by compnerd**
Explicitly pass the path to the python interpreter on macOS by using
`xcrun` to find the tools.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @shahmishal @drexin

**Review by shahmishal — APPROVED** [review]
thanks!

**Comment by shahmishal** [comment]
@swift-ci test Linux

**Pull request merged**
