### PR TITLE
Update swift-rpathize.py to work with Python 3.8 and Python 2.7

### PR DESCRIPTION
**Pull request by tbkka**
Just need to explicitly convert the bytes blob into a real string before trying to pattern-match.

(In Python 2, str() and bytes are basically the same, so it's a lot more forgiving of such mixups.)

### CODE REVIEW

**Comment by tbkka** [comment]
@swift-ci Python lint

**Comment by tbkka** [comment]
@swift-ci Please test

**Review by rjmccall — APPROVED** [review]
Thanks.  This seems reasonable to me.

**Comment by tbkka** [comment]
macOS CI seems to be having problems apparently unrelated to this PR.  I'll resubmit.

**Comment by tbkka** [comment]
@swift-ci Please test macOS

**Comment by tbkka** [comment]
@swift-ci Please test macOS

**Comment by tbkka** [comment]
@swift-ci Please test macOS

**Comment by tbkka** [comment]
@swift-ci Please test macOS

**Comment by tbkka** [comment]
@swift-ci Please clean test macOS

**Pull request merged**
