### PR TITLE
[swiftc] Add non-fuzzing crash case submitted by @kiliankoe

### PR DESCRIPTION
**Pull request by practicalswift**
#### What's in this pull request?

Non-fuzzing crash case submitted by @kiliankoe and minimized by me :-)

Credits: https://twitter.com/kiliankoe/status/752090953977036800
#### Resolved bug number: –

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by jtbandes** [comment]
Further reduction:
```
protocol P {}
struct A<T> {
    func foo<B where T: P>() -> B {
    }
}
```

**Comment by practicalswift** [comment]
@jtbandes Thank you! PR updated :-)

**Comment by jtbandes** [comment]
@slavapestov Any clue how this is *supposed* to make it through ASTVerifier? The type's `getRequirements()` is returning `[T witness marker, T conforms to P, B witness marker]`, which I think makes sense. But for the outer param list (which is traversed first), `archetype->getConformsTo()` doesn't return anything, so it just removes the `T witness marker`. Then when it handles the inner param list, the `T conforms to P` requirement is still dangling at the front of the list.

**Comment by slavapestov** [comment]
I'm not sure, maybe @DougGregor knows.

However this code is cleraly invalid, because 'T : P' is an invalid requirement. Requirements can only reference generic parameters from the innermost parameter list.

**Comment by jtbandes** [comment]
@slavapestov Interesting. Maybe I'm missing it, but I don't even see a diagnostic for that defined in DiagnosticsSema.def. Do you know if it's currently enforced at all?

**Comment by slavapestov** [comment]
Maybe not. It should be enforced, though.

**Comment by jtbandes** [comment]
Would that be the fault of [`resolveArchetype`](https://github.com/apple/swift/blob/02f32984b42869609847c6634ca5e5a04acf36ff/lib/AST/ArchetypeBuilder.cpp#L1425) returning an archetype when it shouldn't? (Should the outer type be represented in PotentialArchetypes?)

**Comment by jtbandes** [comment]
The archetype builder doesn't seem to have any notion of the correct depth at which to accept requirements.

**Comment by DougGregor** [comment]
IIRC, the archetype builder enforces 'depth' in a backwards way: outer type parameter have assigned archetypes, so they're treated like concrete types and aren't supposed to have additional requirements placed on them.

**Comment by jtbandes** [comment]
Then I guess the ASTVerifier may be at fault? https://github.com/apple/swift/blob/02f32984b42869609847c6634ca5e5a04acf36ff/lib/AST/ASTVerifier.cpp#L2126

**Pull request merged**
