### PR TITLE
[Explicit Module Builds] Do not attempt to re-load module dependency from  interface for index.

### PR DESCRIPTION
**Pull request by artemcm**
An explicit module build compile is unable to do so because it does not have access to the interfaces. Doing this in the first place is a workaround for a known bug, which will require to be solved at the root cause instead (e.g. Deserialization Safety feature).

Resolves rdar://113165898

### CODE REVIEW

**Comment by artemcm** [comment]
A follow-up will be a change to make concrete when Explicitly-Prebuilt dependencies can emit forwarding modules. But that change has a dependency on driver changes for blocklists. In the meantime, this unblocks explicit module builds for affected projects.

**Review by bnbarham — APPROVED** [review]

**Review by xymus — APPROVED** [review]

**Comment by artemcm** [comment]
@swift-ci smoke test

**Comment by artemcm** [comment]
@swift-ci smoke test

**Comment by artemcm** [comment]
@swift-ci smoke test

**Pull request merged**
