### PR TITLE
Add a -verify-exclusivity option.

### PR DESCRIPTION
**Pull request by atrick**
This option runs exhaustive verification of SIL access markers during
the DiagnoseStaticExclusivity pass. It's a good validation of the
exclusivity model implementation.

We can't enable the option by default yet because it generates a
substantial number of useless begin_access [unsafe] markers. This
bloats the SIL, potentially interferes with optimization, and is
prohibitively disruptive to SIL test cases.

The long-term goal is to always emit enough markers for exhaustive
verification, but to simplify SIL/SILGen enough that it isn't as
messy. This can be revisited after generalized accessors and
opaque values are enabled by default.

For now, this option will be tested on the side by "verification" bots
and motivated developers.

### CODE REVIEW

**Comment by atrick** [comment]
I'm adding the unit tests while waiting for full CI testing.

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci Please Test Source Compatibility

**Comment by atrick** [comment]
@swift-ci test and merge.

**Comment by jrose-apple** [comment]
I don't think this should be a driver option. If it has to be, I'd prefer it come in enable/disable variants.

**Comment by atrick** [comment]
@jrose-apple This flag is meant to be added under "Other Swift Flags: Debug". Not being a driver flag would kind of defeat the purpose. I'm fine adding enable/disable variants for now, but I'm afraid the disable variant will never be implemented, so what's the point? Eventually this should just be always-on.

**Comment by jrose-apple** [comment]
Past experience has shown that it's *always* useful to be able to turn off flags that aren't on all the time. Maybe one part of the build system starts adding this all the time, and we need to turn it off temporarily to test something.

As to why I don't want it in the driver at all, driver flags are forever (unless they start with -debug, maybe). Even hidden ones. If this is really just temporary staging, then I don't see a problem with leaving it behind `-Xfrontend`.

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
@jrose-apple totally agree on the options.

@rjmccall already reviewed the SILGen changes.

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
@swift-ci smoke test.

**Comment by atrick** [comment]
Note: This PR passed full testing and SCK testing a week ago. Nothing has changed except for the unit tests. I have to resort to smoke test because full PR testing appears to be broken for the past couple of days.

**Pull request merged**
