### PR TITLE
Add visitAccessPathBaseUses API

### PR DESCRIPTION
**Pull request by atrick**
For the move-only checker

### CODE REVIEW

**Review by gottesmm — APPROVED** [review]
LGTM

**Comment by atrick** [comment]
Added SIL unit tests

**Comment by atrick** [comment]
@swift-ci smoke test and merge

**Comment by atrick** [comment]
@swift-ci smoke test linux

**Comment by atrick** [comment]
@swift-ci smoke test windows

**Comment by gottesmm** [comment]
The windows platform test is for something unrelated.

**Comment by gottesmm** [comment]
This was rdar://105295374

**Pull request merged**
