### PR TITLE
[TF] Remove `ParameterGroup` and `Parameterized`.

### PR DESCRIPTION
**Pull request by rxwei**
`ParameterGroup` and `Parameterized` have been superceded by `KeyPathIterable`, which is used in our TF stdlib, deep learning APIs as well as models.

Resolves [TF-154](https://bugs.swift.org/browse/TF-154).

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Review by dan-zheng — APPROVED** [review]

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Pull request merged**
