### PR TITLE
[cleanup] Remove demo-tool from the Swift repo and fix find-unused-diagnostics.sh

### PR DESCRIPTION
**Pull request by practicalswift**
- `utils/demo-tool` seems like a nice general purpose presentation tool but since it is not directly Swift related I suggest removing it from the Swift repo.
- `utils/find-unused-diagnostics.sh` was added in 2013 and has been untouched since then. It reads from a file that currently does not exist so I assume this script is not in heavy use any more :-)

### CODE REVIEW

**Comment by gribozavr** [comment]
`utils/find-unused-diagnostics.sh` is still useful and almost working -- it just needs to be fixed to read from `include/swift/AST/Diagnostics*.def` instead.  It actually finds unused diagnostics, that would be an idea for another PR.

As for `utils/demo-tool`, I would defer to @krememek and @DougGregor.

**Comment by practicalswift** [comment]
@gribozavr I've now fixed `utils/find-unused-diagnostics.sh`. Committed, rebased and pushed.

**Comment by gribozavr** [comment]
@practicalswift Thanks, still waiting on @krememek on @DougGregor to comment about `demo-tool`.

**Comment by lattner** [comment]
demo-tool is dead, feel free to nuke it.

**Comment by gribozavr** [comment]
Awesome, thanks @lattner!

**Comment by practicalswift** [comment]
@lattner, @gribozavr Thanks for clarifying and thanks for merging! :-)

While hunting for obsolete/abandoned files I ran a quick check for all files that are not referenced from another file in the repo.

These are the non-referenced files:

```
cmake/modules/FindBSD.cmake
cmake/modules/FindICU.cmake
cmake/modules/FindUUID.cmake
stdlib/public/SDK/Foundation/ExtraStringAPIs.swift
tools/SourceKit/utils/buildbot-package-sourcekit.sh
utils/analyze_deps.rb
utils/cmpcodesize/tests/test_list_function_sizes.py
utils/create-filecheck-test.py
utils/demo-tool
utils/error_enum_to_cases.pl
utils/find-unused-diagnostics.sh
utils/pass-pipeline/scripts/pipeline_generator.py
utils/pass-pipeline/scripts/pipelines_build_script.py
utils/pre-commit-benchmark
utils/resolve-crashes.py
utils/runtime_statistics.d
utils/sil-opt-verify-all-modules.py
utils/submit-benchmark-results
```

Are there any of the files above that look like candidates for deletion?

**Comment by lattner** [comment]
I'd suggest asking about this on swift-dev.  I don't know what most of those do :-)

**Pull request merged**
