### PR TITLE
Make fix for dynamic lookup on Any work for more general expressions.

### PR DESCRIPTION
**Pull request by rudkx**
#### What's in this pull request?

A more general fixit for dynamic lookup on Any.
#### Resolved bug number: ([rdar://problem/27639935](rdar://problem/27639935))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

A smoke test on macOS does the following:
1. Builds the compiler incrementally.
2. Builds the standard library only for macOS. Simulator standard libraries and
   device standard libraries are not built.
3. lldb is not built.
4. The test and validation-test targets are run only for macOS. The optimized
   version of these tests are not run.

A smoke test on Linux does the following:
1. Builds the compiler incrementally.
2. Builds the standard library incrementally.
3. lldb is built incrementally.
4. The swift test and validation-test targets are run. The optimized version of these
   tests are not run.
5. lldb is tested.

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

Follow-up to 56a5ef00a4234966698dda1d0aedded170a0b305.

Thanks to Jordan for noticing and suggesting this!

rdar://problem/27639935

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please test and merge.

**Comment by jrose-apple** [comment]
Yep, seems good for now. I was thinking about trying to infer the downcast type but (a) that won't work for generic types, and (b) the fix-it would insert either `as!` or `as?` into the code, which does change the behavior.

**Comment by rudkx** [comment]
@shahmishal @tkremenek Both of the individual tests appear to have passed, but this reports as a failure. Is that because I did "test and merge" rather than "test"?

Anyway, it appears to all pass so it should be okay to merge.

**Comment by tkremenek** [comment]
@rudkx It's not clear why "test and merge" is not working — @shahmishal would know.  Perhaps it is not wired yet to work with the branch restrictions.

**Comment by shahmishal** [comment]
@rudkx / @tkremenek, @swift-ci did not have permission to merge to master. It's fixed now, please let me know if you still see this issue in the future. Thanks!

**Pull request merged**
