### PR TITLE
Merge #6547 to 3.1 branch

### PR DESCRIPTION
**Pull request by ematejska**
Merge #6547 from master to 3.1 branch to fix up source compatibility.

### CODE REVIEW

**Comment by ematejska** [comment]
@swift-ci please test

**Review by jrose-apple — APPROVED** [review]
If it merges cleanly, I think we're good! cc @CodaFi

**Comment by shahmishal** [comment]
@swift-ci Please test macOS

**Comment by ematejska** [comment]
@swift-ci please test os x

**Comment by slavapestov** [comment]
The playgrounds logger failure is not caused by this patch. We thought it was a regression from my patch but it's still happening after that got reverted too. Ewa, can you ask someone on playgrounds to take a look?

**Comment by ematejska** [comment]
@swift-ci test os x

**Comment by ematejska** [comment]
@swift-ci test

**Comment by ematejska** [comment]
@swift-ci please test linux

**Pull request merged**
