### PR TITLE
Update AndroidBuild.md

### PR DESCRIPTION
**Pull request by philipturner**
Please refer to the last comment I made on https://github.com/apple/swift/pull/40992. I accidentally deleted the patch-20 branch, so I had to make a new PR.

### CODE REVIEW

**Comment by philipturner** [comment]
CC: @compnerd

**Comment by compnerd** [comment]
I would retain the auto-numbering and instead drop the heading state for the entries (which is why it doesn't auto-number).

**Review by compnerd — CHANGES_REQUESTED** [review]
Just drop the `##` on the steps.

**Comment by philipturner** [comment]
@compnerd when it says you requested changes, I don't see any difference from the changes I already made. It was the same way with the last pull request. 

Did you make any suggested modifications to the file when you requested changes? From the last comment, I'm unsure what you intended since you told me do "drop `##`" after possibly suggesting a change in code.

**Comment by philipturner** [comment]
Sorry for the very long comment, but showing images should clarify what I'm trying to do. 

I can't just turn the headers into something else, because these are section titles. What I suggested (1, 2, 3, 4...) is already implemented in the raw Markdown for [Android.md](https://github.com/apple/swift/blob/main/docs/Android.md#hello-world-on-android). It results in this rendering output:
Screen Shot 2022-01-26 at 7 21 47 PM

[AndroidBuild.md](https://github.com/apple/swift/blob/main/docs/AndroidBuild.md) has the (1, 1, 1, 1...) convention in raw Markdown, which produces this:
Screen Shot 2022-01-26 at 7 24 47 PM

**Comment by philipturner** [comment]
Is my evidence sufficient proof that this PR should be merged, or am I misunderstanding something here?

**Comment by philipturner** [comment]
Dropping the `##` instead of the number interferes with other numbered lists. Is it okay to just manually number them?

**Review by compnerd — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please smoke test and merge

**Comment by philipturner** [comment]
@compnerd would you mind running the tests again? They failed when you pinged @swift-ci.

**Comment by buttaface** [comment]
I'm not a committer, maybe @CodaFi or @compnerd will get this in soon.

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by philipturner** [comment]
Merge conflict resolved.

**Pull request closed without merging**
