### PR TITLE
Remove ICU from the toolchain

### LINKED ISSUE #70966: utils/update-checkout error from git checkout icu maint/maint-69
### Description

https://github.com/apple/swift/blob/main/docs/HowToGuides/GettingStarted.md#cloning-the-project

Hi! I just tried following the `cloning-the-project` steps on a new (vanilla) `swift` checkout (from latest `main`). I'm seeing some errors on console:

```
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/rick/Developer/swift-project/swift/utils/update_checkout/update_checkout/update_checkout.py", line 376, in obtain_additional_swift_sources
    shell.run(['git', '--git-dir',
  File "/Users/rick/Developer/swift-project/swift/utils/swift_build_support/swift_build_support/shell.py", line 257, in run
    raise eout
Exception: ['git', '--git-dir', '/Users/rick/Developer/swift-project/icu/.git', '--work-tree', '/Users/rick/Developer/swift-project/icu', 'checkout', 'maint/maint-69']
```

I tried running `cloning-the-project` again and see similar errors:

```
[icu]                                   + git checkout maint/maint-69
[icu]                                   error: Your local changes to the following files would be overwritten by checkout:
[icu]                                   	.ci-builds/.azure-exhaustive-tests.yml
[icu]                                   	.ci-builds/.azure-pipelines.yml
[icu]                                   	.ci-builds/data-filter.json
...
[icu]                                   error: The following untracked working tree files would be overwritten by checkout:
[icu]                                   	.appveyor.yml
[icu]                                   	.ci-builds/.azure-valgrind.yml
[icu]                                   	.github/workflows/icu_ci.yml
...
[icu]                                   	ic
```

Anyone seen these errors before or know the steps to work around and test building `swift` locally? I'm on Apple Silicon BTW. Thanks!

### Reproduction

```shell
mkdir swift-project
cd swift-project
git clone https://github.com/apple/swift.git swift
cd swift
utils/update-checkout --clone-with-ssh
```

### Expected behavior

`utils/update-checkout` succeeds and installs deps with no errors.

### Environment

```shell
uname -a
Darwin C97RX2X127.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6020 arm64
```

```shell
sw_vers
ProductName:		macOS
ProductVersion:		14.2.1
BuildVersion:		23C71
```

```shell
git --version
git version 2.39.3 (Apple Git-145)
```

```shell
git remote -v
origin	git@github.com:apple/swift.git (fetch)
origin	git@github.com:apple/swift.git (push)
git branch
* main
git rev-parse HEAD
e7475c89edb66a26d762c6e9a24c9bdb1a80b87a
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jmschonfeld**
Now that Foundation builds against its own swift-foundation-icu repo, we no longer need to build the upstream libicu repo for the toolchain. This removes the libicu build from the toolchain

### CODE REVIEW

**Comment by jmschonfeld** [comment]
@swift-ci please smoke test

**Review by compnerd — APPROVED** [review]
Probably a good idea to do a toolchain build on this.

**Comment by compnerd** [comment]
@swift-ci please build toolchain

**Review by parkera — APPROVED** [review]

**Review by shahmishal — APPROVED** [review]

**Comment by finagolfin** [comment]
Oh nice, but I see [some docs](https://github.com/swiftlang/swift/blob/main/docs/WindowsBuild.md#dependencies-icu-sqlite3-curl-libxml2-and-zlib) that [still refer](https://github.com/swiftlang/swift/blob/main/docs/AndroidBuild.md#1-build-foundation) to [this libicu checkout](https://github.com/swiftlang/swift/blob/main/docs/HowToGuides/GettingStarted.md#troubleshooting-cloning-issues), maybe those should be removed too?

**Comment by jmschonfeld** [comment]
> Oh nice, but I see [some docs](https://github.com/swiftlang/swift/blob/main/docs/WindowsBuild.md#dependencies-icu-sqlite3-curl-libxml2-and-zlib) that [still refer](https://github.com/swiftlang/swift/blob/main/docs/AndroidBuild.md#1-build-foundation) to [this libicu checkout](https://github.com/swiftlang/swift/blob/main/docs/HowToGuides/GettingStarted.md#troubleshooting-cloning-issues), maybe those should be removed too?

I think the first two files are just quite old and out of date in general - I see lots of details in each file unrelated to ICU that are incorrect or no longer the case at this point. I think that those could definitely use an update, but they should probably be updated wholesale rather than just this piece so I think it might be best to save that for a future PR. The final one seems like it could make sense to remove the part related to ICU (but leave the LFS comment in place in case it applies to other repos). I can update that once the toolchain builds pass so they can finish before adding a commit if we want to remove that comment from the document

**Comment by AnthonyLatsis** [comment]
> The final one seems like it could make sense to remove the part related to ICU (but leave the LFS comment in place in case it applies to other repos)

That item is [ICU-specific](https://github.com/swiftlang/swift/issues/70966), so please remove it entirely. Thanks!

**Comment by jmschonfeld** [comment]
@compnerd it looks like all of the full toolchain builds passed 👍🏻

**Comment by jmschonfeld** [comment]
@swift-ci please smoke test

**Review by AnthonyLatsis — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please smoke test Linux platform

**Comment by jmschonfeld** [comment]
@swift-ci please smoke test Linux platform

**Comment by jmschonfeld** [comment]
@swift-ci please clean smoke test Linux platform

**Comment by jmschonfeld** [comment]
@swift-ci please clean smoke test Linux platform

**Comment by jmschonfeld** [comment]
@swift-ci please clean smoke test Linux platform

**Pull request merged**
