### PR TITLE
[ClangImporter] Preserve the names of imported ObjC properties.

### PR DESCRIPTION
**Pull request by jrose-apple**
This is necessary for proper working of `#keyPath`, as well as improving the experience of PrintAsObjC.

rdar://problem/28543037. Some discussion of trickier problems in [SR-3075](https://bugs.swift.org/browse/SR-3075).

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test macOS

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test Linux

**Comment by jrose-apple** [comment]
```
18:32:36 
/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/test/ClangImporter/objc_parse.swift:489:5: error: unexpected error produced: Objective-C method 'started' provided by getter for 'isStarted' does not match the requirement's selector ('isStarted')
18:32:36     get { return _started }
18:32:36     ^
```

Huh. Well, that's what tests are for.

**Comment by jrose-apple** [comment]
Okay, this change uncovered another issue: `@objc` names of accessors are not inferred from a protocol that has a matching requirement. Setting this aside for now.

**Comment by jrose-apple** [comment]
Recursively ~shaved yaks~ fixed issues in #6698 and #6634 in order to clear the way for this, which should now work. @milseman, mind checking the last commit? (The other two are covered by the other PRs.)

@swift-ci Please test macOS

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test Linux

**Comment by milseman** [comment]
Post-hoc LGTM.

**Pull request merged**
