### PR TITLE
Make waiting on condition variables error out on SWIFT_STDLIB_SINGLE_THREADED_RUNTIME

### PR DESCRIPTION
**Pull request by kubamracek**
...instead of having an undefined symbol.

### CODE REVIEW

**Comment by mikeash** [comment]
The changes in `Mutex.h` seem to be redundant, as the existing code will call through to the code in `MutexSingleThreaded.h` and hit the fatal error there. Should this just change `MutexSingleThreaded.h`?

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test stdlib with toolchain

**Comment by kubamracek** [comment]
> The changes in `Mutex.h` seem to be redundant, as the existing code will call through to the code in `MutexSingleThreaded.h` and hit the fatal error there. Should this just change `MutexSingleThreaded.h`?

Sure! I was just thinking that it would be nicer to hit the error in the layer above.

**Comment by mikeash** [comment]
@kubamracek OK, I'm fine with that if you think it would be clearer.

One more tiny comment, while I'm bikeshedding: it would be good for the error message to say why it can't wait. Something like, "single-threaded runtime cannot wait for condition".

**Review by mikeash — APPROVED** [review]

**Comment by kubamracek** [comment]
@swift-ci please test

**Pull request merged**
