### PR TITLE
[DeadObjectElimination] Zero init is not a barrier

### PR DESCRIPTION
**Pull request by Azoy**
The zero init builtin has an address form which can create a use site for potentially dead allocs. Teach DOE that it can always zap this instruction.

### CODE REVIEW

**Comment by Azoy** [comment]
@swift-ci please test

**Comment by Azoy** [comment]
@swift-ci please test

**Review by eeckstein — APPROVED** [review]
lgtm

**Comment by Azoy** [comment]
@swift-ci please smoke test

**Pull request merged**
