### PR TITLE
[stdlib] Implement SE-0171: Reduce with inout 

### PR DESCRIPTION
**Pull request by d-ronnqvist**
This PR implements [SE-0171: Reduce with inout][se171], which is accepted but not implemented.

Trying to mimic the existing `reduce(_:_:)` implementation as closely as possible there are a few differences between this implementation and the proposal that's worth noting:

 - The `initial` parameter was renamed `initialResult` to match the first parameter in `reduce(_:_:)`.
 - The unnamed `combining` parameter was renamed `updateAccumulatingResult` to try and resemble the naming of the closure parameter in `reduce(_:_:)`.
 - The closure throws and `reduce(into:_)` re-throws.

I've tried to keep the `reduce(into:_:)` documentation close to the existing `reduce(_:_:)` documentation but also mention that `reduce(into:_)` is preferred over `reduce(_:_:)` when the result is a copy-on-write type and include an example where the result is a dictionary.

I've added a few benchmarks and updated one expected error message (since there are now two `reduce` methods, the diagnostic is different). 

I didn't know how an implementation like this should be tested and I couldn't find much inspiration from existing reduce testing. (Comments and feedback are appreciated). 

Implements [SE-0171][se171]. I couldn't find a bug number for it in the Swift bug tracker.

[se171]: https://github.com/apple/swift-evolution/blob/master/proposals/0171-reduce-with-inout.md

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
@swift-ci Please smoke benchmark

**Comment by d-ronnqvist** [comment]
That’s odd. It looks like the benchmarks didn’t find `reduce(into:_:)` (complaining about an extraneous argument label ‘into:’)

**Comment by moiseev** [comment]
@d-ronnqvist Can you please add a few unit tests to see if that reproduces the problem (which might be a compiler picking another overload for some reason, and not seeing the new one), otherwise it's the problem with the benchmarking setup. Having unit tests is not a bad idea anyway. Thanks!

**Comment by dabrahams** [comment]
@swift-ci Please clean benchmark

**Comment by dabrahams** [comment]
@swift-ci Please clean benchmark

**Comment by dabrahams** [comment]
@swift-ci Please  benchmark

**Comment by natecook1000** [comment]
@dabrahams @moiseev Benchmarking won't work in this case since it will try to run the benchmark with the pre-merge version of the stdlib, which doesn't have `reduce(into:_:)`. In general, unless the CI has gotten smarter, I don't think benchmarking works on a PR that adds a benchmark.

**Comment by natecook1000** [comment]
@swift-ci Please smoke test

**Comment by moiseev** [comment]
@natecook1000 Benchmarking just runs two separate builds: pre- and post- merge. And the new benchmarks are reflected in a special session, since they did not exist-pre-merge, there is nothing to compare to.

**Comment by moiseev** [comment]
The above comment is my understanding of it, anyway.

**Comment by dabrahams** [comment]
@swift-ci Please benchmark

**Comment by dabrahams** [comment]
@swift-ci Please benchmark

**Comment by dabrahams** [comment]
@natecook1000 My understanding matches @moiseev's

**Comment by natecook1000** [comment]
😬 Yep, I'm totally off-base on the compiler error question! I think it still chokes when the number of benchmarks doesn't match up, but perhaps that got fixed somewhere along the way.

**Comment by dabrahams** [comment]
@natecook1000 I've only ever seen it not-choke on those.

**Comment by dabrahams** [comment]
Can we compare the performance of the two forms of reduce, e.g. for accumulating both lightweight (`Int`) and heavyweight (`Array`) types?

**Comment by d-ronnqvist** [comment]
@dabrahams That would be great! Is it possible to write a test that does that comparison or did you mean to write benchmarks for each form of reduce and manually compare the numbers?

**Comment by dabrahams** [comment]
@d-ronnqvist The former _could_ be done by testing a change that switches tests from one implementation to the other, but I actually think the latter is the better approach.

**Comment by d-ronnqvist** [comment]
I've updated the benchmark to perform three tasks - reducing to `[Int]`, `[Character: Int]`, and `Int` - for both forms of reduce. Below is a sample output from when I ran it on my machine:

```
143 FilterEvenUsingReduce          15    1835    2035     1921      0       1921   10923486
144 FilterEvenUsingReduceInto      15     352     372      365      0        365   10926217
145 FrequenciesUsingReduce         15   10367   11630    10865      0      10865   10990933
146 FrequenciesUsingReduceInto     15    5490    6321     5822      0       5822   10990114
...
334 SumUsingReduce                 15     883     974      912      0        912   10854127
335 SumUsingReduceInto             15     875     942      911      0        911   10836651
```

I tried to implement the `reduce(_:_:)` filter as both

```
if num % 2 == 0 {
  return acc + [num]
}
return acc
```
and
```
var a = acc
if num % 2 == 0 {
  a.append(num)
}
return a
```

Both had the same performance so I went with the latter because it uses the same "style" as the dictionary benchmark.

**Comment by moiseev** [comment]
@swift-ci Please smoke benchmark

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by moiseev** [comment]
@swift-ci Please smoke benchmark

**Comment by d-ronnqvist** [comment]
Same problem as previously: `error: extraneous argument label 'into:' in call`. 

Is there something different in how the benchmark was invoked when it worked compared to the other two times? Is it necessary to `clean` if the benchmarks are using new methods? Or does `smoke benchmark` behave differently than just `benchmark`?

**Comment by dabrahams** [comment]
on Tue Jul 18 2017, David Rönnqvist <notifications-AT-github.com> wrote:

> Same problem as previously: `error: extraneous argument label 'into:' in call`. 
>
> Is there something different in how the benchmark was invoked when it
> worked compared to the other two times? Is it necessary to `clean` if
> the benchmarks are using new methods? Or does `smoke benchmark` behave
> differently than just `benchmark`?

The build system is missing dependencies; if smoke benchmark does an
incremental build it could easily be hitting that problem.

https://bugs.swift.org/browse/SR-4608



-- 
-Dave

**Comment by d-ronnqvist** [comment]
If there could be a problem with incremental builds, should we run the benchmarks again on a clean build? (Can anyone give commands to the CI or is it only members who have that permission?)

**Comment by d-ronnqvist** [comment]
@moiseev @dabrahams Is there anything more that's needed from this PR or anything more that I can do to help it get merged? Should I squash and/or rebase my changes? As a user I would love to start using this.

**Comment by dabrahams** [comment]
@swift-ci Please benchmark

**Comment by dabrahams** [comment]
@swift-ci Please benchmark

**Comment by dabrahams** [comment]
@d-ronnqvist When benchmarks pass, IMO, it's good to go.

**Pull request merged**
