### PR TITLE
Revert "Merge pull request #61606 from NuriAmari/fwd-declarations"

### PR DESCRIPTION
**Pull request by Azoy**
This introduced 12 failing tests:
```
Failed Tests (12):
  Swift(macosx-x86_64) :: ClangImporter/incomplete_objc_types_availability.swift
  Swift(macosx-x86_64) :: ClangImporter/incomplete_objc_types_base_interface_swift_6.swift
  Swift(macosx-x86_64) :: ClangImporter/incomplete_objc_types_compatibility_complete_incomplete.swift
  Swift(macosx-x86_64) :: ClangImporter/incomplete_objc_types_compatibility_incomplete_incomplete.swift
  Swift(macosx-x86_64) :: ClangImporter/incomplete_objc_types_full_availability_swift_6.swift
  Swift(macosx-x86_64) :: ClangImporter/incomplete_objc_types_importing_limitations_diagnostics.swift
  Swift(macosx-x86_64) :: ClangImporter/incomplete_objc_types_no_reference.swift
  Swift(macosx-x86_64) :: ClangImporter/incomplete_objc_types_no_root_protocol.swift
  Swift(macosx-x86_64) :: ClangImporter/incomplete_objc_types_nsproxy.swift
  Swift(macosx-x86_64) :: ClangImporter/incomplete_objc_types_swift_definition_imported.swift
  Swift(macosx-x86_64) :: ClangImporter/incomplete_objc_types_swift_definition_imported_implementationOnly.swift
  Swift(macosx-x86_64) :: ClangImporter/incomplete_objc_types_swift_definition_imported_name_conflict.swift
```

https://ci.swift.org/job/oss-swift_tools-R_stdlib-RD_test-simulator/2677/

### CODE REVIEW

**Review by zoecarver — APPROVED** [review]

**Comment by Azoy** [comment]
@swift-ci please test

**Comment by drodriguez** [comment]
It seems that all that's missing is adding a `REQUIRES: asserts` to those test to avoid `--swift-version 6` from being rejected.

Can we fix forward instead of reverting? We could have a fix ready in some minutes.

**Comment by Azoy** [comment]
That would explain the `--swift-version 6` errors, but I don't think it solves the other errors in the failures no?

**Comment by NuriAmari** [comment]
> [Azoy](/Azoy)



> That would explain the `--swift-version 6` errors, but I don't think it solves the other errors in the failures no?

I will double check, but I don't see other failures? Do you have an example

**Comment by NuriAmari** [comment]
Every failing tests uses `-swift-version 6`, there is other noise from diagnostics, but those are intended as far as I see.

https://github.com/apple/swift/pull/64357

**Comment by drodriguez** [comment]
We have the asserts preset building and passing in #64355. To avoid a landing race, is everyone ok closing this PR and going with the other PR?

**Pull request closed without merging**
