### PR TITLE
Simplify performMemberLookup()

### PR DESCRIPTION
**Pull request by davezarzycki**
Simplify performMemberLookup() by having the normal code path handle both simple and compound named constructors. As a part of the fallout, a redundant diagnostic can also be removed.

This branch continues the favored constructor optimization.

All validation tests pass on my machine.

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Review by rudkx — APPROVED** [review]
LGTM as long as the compatibility suite passes.

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
@shahmishal It looks like the compatibility test suite isn't triggering.

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by rudkx** [comment]
Thanks Dave!

**Comment by davezarzycki** [comment]
Thanks for helping me debug this. Am I wrong, or should the trace favored type logic in CSSimplify.cpp move to CSGen.cpp where the rest of the favored type logic lives?

**Comment by rudkx** [comment]
I don't believe this can be moved into `CSGen.cpp` because these are member lookups that are happening as we're solving the constraint system.

**Pull request merged**
