### PR TITLE
[ASTPrinter] Print typealias generic requirements

### PR DESCRIPTION
**Pull request by johnfairh**
This PR prints the 'where' clause for generic type aliases, I think just an oversight this was omitted.
Affects Xcode quick help etc.

First commit fixes the bug, second refactors the various paths that print generic params + reqs.

@benlangmuir could you review please?

### CODE REVIEW

**Comment by slavapestov** [comment]
@Swift-ci Please smoke test

**Comment by slavapestov** [comment]
Great job!

**Review by benlangmuir — CHANGES_REQUESTED** [review]
Nice fix!   The implementation LGTM, but this should include a test for annotated declaration printing.  If you look in test/SourceKit/CursorInfo/cursor_info.swift, and search for `<decl.typealias>` you will see other tests for annotation printing on typealias decls.  It doesn't need to be extensive, just one test that shows that the where clause is included and doesn't garble the structure or anything bad like that.

Thanks!

**Comment by johnfairh** [comment]
Thanks - added CursorInfo test, looks fine.

**Review by benlangmuir — APPROVED** [review]
LGTM, thanks!

**Comment by benlangmuir** [comment]
@swift-ci please smoke test

**Comment by johnfairh** [comment]
Could you try CI again please - Linux timed out.

**Comment by xedin** [comment]
@swift-ci please smoke test Linux platform

**Comment by johnfairh** [comment]
Thanks - I think this is good to merge now then.

**Comment by johnfairh** [comment]
Sorry to bother again @benlangmuir - could you merge this?

**Comment by benlangmuir** [comment]
@johnfairh sorry I didn't notice this was still waiting!  Merged.

**Comment by johnfairh** [comment]
No worries - thanks!

**Pull request merged**
