### PR TITLE
Basic: Remove VariadicGenerics feature

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
https://github.com/apple/llvm-project/pull/6948
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
https://github.com/apple/llvm-project/pull/6948
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Review by tshortli — APPROVED** [review]

**Pull request merged**
