### PR TITLE
 [CS] Add specific accessors for path element info

### PR DESCRIPTION
**Pull request by hamishknight**
This PR replaces the `getValue()` and `getValue2()` members on
`ConstraintLocator::PathElement` with specific accessors for each
expected path component kind. IMO this adds some clarity to the call
sites, especially for `getArgIdx()` and `getParamIdx()`.

In addition, this PR adds a couple of assertions to make sure we
don't truncate values when creating a path element.

### CODE REVIEW

**Comment by hamishknight** [comment]
cc. @xedin

**Comment by hamishknight** [comment]
Ping @xedin

**Comment by xedin** [comment]
Sorry I completely missed this one :( Would you mind setting me as a reviewer next time so it shows up in my queue?

**Review by xedin — COMMENTED** [review]
IMHO it's still awkward to work with path elements because `Kind` still needs to be checked before calling right method to retrieve a value, so these changes might be increasing cognitive load by requiring to call different accessors. Maybe we could do something more comprehensive here?

**Comment by hamishknight** [comment]
> Would you mind setting me as a reviewer next time so it shows up in my queue?

Unfortunately I believe only users with commit access can do that :/

> IMHO it's still awkward to work with path elements because `Kind` still needs to be checked before calling right method to retrieve a value, so these changes might be increasing cognitive load by requiring to call different accessors. 

Fair enough, I definitely agree that path elements will still be awkward to use with this patch, though IMO it's still an overall improvement. Most notably we're now asserting that we've got the correct path element kind in a couple of places where we weren't previously (in `fixRequirementFailure` & `CollectionElementContextualFailure::diagnoseAsError`). 

> Maybe we could do something more comprehensive here?

Did you have a specific design in mind? The best I can think of is creating `ConstraintLocator::PathElement` subclasses for path elements that need to expose accessors and use the `dyn_cast`/`cast`/`isa` framework to cast to them.

On the plus side, this would eliminate the confusion of which accessor to call on a specific path element. On the negative side, it might be a bit awkward to use when doing things like switching over the kind of path element and using `std::find_if` to find a specific path element in a locator.

If something like that isn't viable, as a compromise for now we could modify this patch to just define accessors on `ConstraintLocator::PathElement` for cases that are currently particularly suboptimal (which IMO are `getArgIdx()`, `getParamIdx()` & `getRequirementKind()`). We'd then keep `getValue()` for the other cases.

Thoughts?

**Comment by xedin** [comment]
> Unfortunately I believe only users with commit access can do that :/

Ah, for some reason I thought that you have access already :/

>  The best I can think of is creating ConstraintLocator::PathElement subclasses for path elements that need to expose accessors and use the dyn_cast/cast/isa framework to cast to them.

That's something I was thinking about, it makes this less awkward because right now we have to the check kind of element anyway before using its specific accessor, which then also asserts internally... We could probably keep `kind` around too to make iteration and find_if less awkward.

**Comment by hamishknight** [comment]
@xedin Sorry for taking a little while to get back to this! I've gone ahead and added `LocatorPathElt` subclasses to expose specific path info accessors. In addition, I've added a few convenience members to `ConstraintLocator` that make it easier to search for a specific kind of element in its path. As suspected, it's now a bit more awkward to use around switches, but overall I'm fairly happy with how it turned out. 

Going forward, it might even be worth creating subclasses for every kind of path element through macros, which would allow us to replace `isLastElement` with a version that takes a template for a specific `LocatorPathElt` subclass in order to match `getLastElementAs`/`castLastElementTo`. We could also then replace a bunch of uses of `getKind() ==` with calls to `.is`. What are your thoughts on this? I'm happy to tackle this in a follow-up (as I feel this PR is already getting pretty big).

**Review by xedin — APPROVED** [review]
Looks great, thank you!

**Comment by xedin** [comment]
I'm totally fine if you'd like all of the changes you mentioned in the follow-up. This is a great step forward!

**Comment by hamishknight** [comment]
@xedin Thanks for the fast review! Would you mind kicking off the CI for me?

**Comment by xedin** [comment]
Gladly.

@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@hamishknight Could you please follow instructions in "Commit Access" located here https://swift.org/contributing/#contributing-code so we can get you access?

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Comment by hamishknight** [comment]
> @hamishknight Could you please follow instructions in "Commit Access" located here swift.org/contributing/#contributing-code so we can get you access?

Sure thing! I had been meaning to for a little while now, but never got round to it :) I've gone ahead and done that now.

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Pull request merged**
