### PR TITLE
[SyntaxParse] Adjust parseMatchingToken()

### PR DESCRIPTION
**Pull request by rintaro**
* Now returns `ParsedSyntaxResult<ParsedTokenSyntax>` instead of `Optional<ParsedTokenSyntax>`.
* Remove `TokLoc` parameter because Syntax parsing doesn't need the location.
* Add `silenceDiag` parameter flag which prevents diagnostics even if it cannot be parsed.
  This simplifies the client code. For example for:
  ```swift
    var a: (<type A>, <type B>
  ```
  If parsing `<type B>` ends up with an error, we do still want to parse `)`, but we don't want to emit `missing ')'` error even if it's missing.

### CODE REVIEW

**Comment by rintaro** [comment]
@nathawes This affects your https://github.com/apple/swift/pull/27460 .

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Review by nathawes — APPROVED** [review]

**Comment by rintaro** [comment]
@swift-ci Please smoke test Linux

**Comment by rintaro** [comment]
@swift-ci Please smoke test Linux

**Comment by rintaro** [comment]
@swift-ci Please smoke test Linux

**Pull request merged**
