### PR TITLE
 [ParseableInterface] Module-qualify protocol types and typealiases

### PR DESCRIPTION
**Pull request by jrose-apple**
Otherwise we can get in trouble when a local type is named, say, 'Sequence'. Slurps in the non-controversial parts of Harlan's #22799.

rdar://problem/48298527 and rdar://problem/49426322

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by harlanhaskins** [comment]
Should we also set `PreferTypeRepr = false` here?

**Comment by jrose-apple** [comment]
That was the controversial part. ;-) These changes can go in now and let me make progress on [latest test case] even before you/we work out the issues with dropping TypeReprs.

**Comment by harlanhaskins** [comment]
Sure, sounds good, then!

**Review by nathawes — APPROVED** [review]
LGTM!

**Review by harlanhaskins — APPROVED** [review]

**Review by slavapestov — APPROVED** [review]

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@nkcsgexi This changes *some* but not *all* of the generic signatures in the API digester output and the SourceKit document structure, and that seems…concerning?

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
Oops, I think I forgot to amend a commit.

**Comment by jrose-apple** [comment]
@swift-ci Please test macOS

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
Oh, I actually did break this thing in LLDB. Whoops.

**Comment by jrose-apple** [comment]
apple/swift-lldb#1417
@swift-ci Please test

**Comment by harlanhaskins** [comment]
```
Command Output (stderr):
--
<unknown>:0: error: error opening '/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/api-digester/Output/compare-dump.swift.tmp.mod1/cake.swiftmodule' for output: No such file or directory

--
```

?

**Comment by jrose-apple** [comment]
\*obligatory Portal reference\*

I forgot to actually create the new directories I was relying on, will fix.

**Comment by jrose-apple** [comment]
apple/swift-lldb#1417
@swift-ci Please test macOS

**Comment by jrose-apple** [comment]
apple/swift-lldb#1417
@swift-ci Please smoke test Linux

**Pull request merged**
