### PR TITLE
[5.9.0][CMake] Support Macros in Linux

### PR DESCRIPTION
**Pull request by rintaro**
Cherry-pick #68190 into `release/5.9.0`

* **Explanation**: Enable Macros in Linux. Swift parser integration is required for enabling macros. Since Linux doesn't have ABI stable `swiftCore` in `/usr/lib` or any other stable location, executables and shared libraries that contains Swift module need to have `RUNPATH` to the runtime in its own toolchain. This PR forces "hosttools" bootstrapping mode, but set the `RUNPATH` to the currently-being-built toolchain.
* **Scope**: CMake build script
* **Risk**: Mid. This PR is carefully crafted not to affect Darwin platforms. For Linux, this is necessary for enabling macros.
* **Testing**: Passes current test suite.
* **Issues**: rdar://104346187
* **Reviewers**: TBA

### CODE REVIEW

**Comment by rintaro** [comment]
https://github.com/apple/llvm-project/pull/7354
https://github.com/apple/swift-syntax/pull/2117
@swift-ci Please test

**Comment by rintaro** [comment]
https://github.com/apple/llvm-project/pull/7354
https://github.com/apple/swift-syntax/pull/2117
@swift-ci Please Build Toolchain

**Comment by shahmishal** [comment]
https://github.com/apple/llvm-project/pull/7354
https://github.com/apple/swift-syntax/pull/2117
@swift-ci Please Build Toolchain UBI9

**Comment by shahmishal** [comment]
https://github.com/apple/llvm-project/pull/7354
https://github.com/apple/swift-syntax/pull/2117
@swift-ci Please Build Toolchain CentOS 7

**Comment by shahmishal** [comment]
https://github.com/apple/llvm-project/pull/7354
https://github.com/apple/swift-syntax/pull/2117
@swift-ci Please Build Toolchain Ubuntu 18.04

**Comment by shahmishal** [comment]
https://github.com/apple/llvm-project/pull/7354
https://github.com/apple/swift-syntax/pull/2117
@swift-ci Please Build Toolchain Ubuntu 22.04

**Comment by shahmishal** [comment]
https://github.com/apple/llvm-project/pull/7354
https://github.com/apple/swift-syntax/pull/2117
@swift-ci Please Build Toolchain Amazon Linux 2

**Comment by shahmishal** [comment]
```
=== /home/build-user/swift/stdlib/public/core/Macros.swift:34 ===
Traceback (most recent call last):
  File "/home/build-user/swift/utils/line-directive", line 738, in <module>
    run()
  File "/home/build-user/swift/utils/line-directive", line 732, in run
    sys.stdout.write(output)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2506' in position 10: ordinal not in range(128)
ninja: build stopped: subcommand failed.
```
Ubuntu 18.04 failure

**Comment by rintaro** [comment]
https://github.com/apple/llvm-project/pull/7354
https://github.com/apple/swift-syntax/pull/2117
@swift-ci Please test

**Comment by rintaro** [comment]
https://github.com/apple/llvm-project/pull/7354
https://github.com/apple/swift-syntax/pull/2117
@swift-ci Please Build Toolchain

**Comment by rintaro** [comment]
https://github.com/apple/llvm-project/pull/7354
https://github.com/apple/swift-syntax/pull/2117
@swift-ci Please Build Toolchain UBI9

**Comment by rintaro** [comment]
https://github.com/apple/llvm-project/pull/7354
https://github.com/apple/swift-syntax/pull/2117
@swift-ci Please Build Toolchain CentOS 7

**Comment by rintaro** [comment]
https://github.com/apple/llvm-project/pull/7354
https://github.com/apple/swift-syntax/pull/2117
@swift-ci Please Build Toolchain Ubuntu 18.04

**Comment by rintaro** [comment]
https://github.com/apple/llvm-project/pull/7354
https://github.com/apple/swift-syntax/pull/2117
@swift-ci Please Build Toolchain Ubuntu 22.04

**Comment by rintaro** [comment]
https://github.com/apple/llvm-project/pull/7354
https://github.com/apple/swift-syntax/pull/2117
@swift-ci Please Build Toolchain Amazon Linux 2

**Comment by rintaro** [comment]
https://github.com/apple/llvm-project/pull/7354
https://github.com/apple/swift-syntax/pull/2117
@swift-ci Please test

**Comment by rintaro** [comment]
https://github.com/apple/llvm-project/pull/7354
https://github.com/apple/swift-syntax/pull/2117
@swift-ci Please Build Toolchain

**Comment by rintaro** [comment]
https://github.com/apple/llvm-project/pull/7354
https://github.com/apple/swift-syntax/pull/2117
@swift-ci Please Build Toochain UBI9

**Comment by rintaro** [comment]
https://github.com/apple/llvm-project/pull/7354
https://github.com/apple/swift-syntax/pull/2117
@swift-ci Please Build Toolchain CentOS 7

**Comment by rintaro** [comment]
https://github.com/apple/llvm-project/pull/7354
https://github.com/apple/swift-syntax/pull/2117
@swift-ci Please Build Toolchain

**Comment by rintaro** [comment]
https://github.com/apple/llvm-project/pull/7354
https://github.com/apple/swift-syntax/pull/2117
@swift-ci Please Build Toolchain UBI9

**Comment by rintaro** [comment]
https://github.com/apple/llvm-project/pull/7354
https://github.com/apple/swift-syntax/pull/2117
@swift-ci Please Build Toolchain Ubuntu 18.04

**Comment by rintaro** [comment]
https://github.com/apple/llvm-project/pull/7354
https://github.com/apple/swift-syntax/pull/2117
@swift-ci Please Build Toolchain Ubuntu 22.04

**Comment by rintaro** [comment]
https://github.com/apple/llvm-project/pull/7354
https://github.com/apple/swift-syntax/pull/2117
@swift-ci Please Build Toolchain Amazon Linux 2

**Review by airspeedswift — APPROVED** [review]

**Pull request merged**
