### PR TITLE
[5.0][TypeChecker] Always emit a fallback error if type-check failed witho

### PR DESCRIPTION
**Pull request by xedin**
…ut producing one

Sometimes constraint solver fails without producing any diagnostics,
it could happen during different phases e.g. pre-check, constraint
generation, or even while attempting to apply solution. Such behavior
leads to crashes down the line in AST Verifier or SILGen which are
hard to diagnose.

Let's guard against that by tracking if solver produced any diagnostics
upon its failure and if no errors were or are scheduled to be produced,
let's produce a fallback fatal error pointing at affected expression.

Resolves: rdar://problem/38885760

### CODE REVIEW

**Comment by xedin** [comment]
@AnnaZaks It seems like @DougGregor and @rjmccall think that this is going to be worth to have in 5.0 since it helps in come cases already (diagnostic which points to expression instead of a crash).

**Comment by DougGregor** [comment]
Despite the amount of new code here, this is a safe addition that will help avoid compiler crashes later in the pipeline.

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
Ah, I probably just need to land another PR related to this I forgot about. There was a legit bug these changes discovered where type wasn’t set, which I fixed separately on master.

**Comment by xedin** [comment]
Ok, cherry-picked a fix for `LazyInitializerExpr` not having type set explicitly.

**Comment by xedin** [comment]
@swift-ci please test

**Review by AnnaZaks — APPROVED** [review]

**Pull request merged**
