### PR TITLE
add_swift_target_library: remove TARGET_LIBRARY parameter

### PR DESCRIPTION
**Pull request by compnerd**
This is implicit in the invocation of this function now.  Remove the
unneeded parameter.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @gottesmm @Rostepher

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Review by Rostepher — APPROVED** [review]
Looks like a simple change to me. 👍

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by CodaFi** [comment]
Not sure why the original merge failed.  @compnerd Could you rebase this please?

**Comment by compnerd** [comment]
Seems that I had re-done this at some point.

**Pull request closed without merging**
