### PR TITLE
Bump swift-argument-parser

### PR DESCRIPTION
**Pull request by miggs597**
Needed by apple/swift-package-manager/pull/3473

### CODE REVIEW

**Comment by miggs597** [comment]
apple/swift-package-manager#3473
@swift-ci please smoke test

**Comment by miggs597** [comment]
apple/swift-package-manager#3473
@swift-ci please test

**Comment by miggs597** [comment]
apple/swift-package-manager#3473
@swift-ci please test linux

**Comment by miggs597** [comment]
apple/swift-package-manager#3473
@swift-ci please test linux

**Comment by shahmishal** [comment]
apple/swift-package-manager#3473
@swift-ci please test linux

**Pull request merged**
