### PR TITLE
Sema: Cache Solution::getTotalMemory()

### PR DESCRIPTION
**Pull request by slavapestov**
This is showing up in performance profiles.

Fixes rdar://136106973.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Review by xedin — APPROVED** [review]

**Comment by slavapestov** [comment]
@swift-ci Please test Windows

**Comment by slavapestov** [comment]
@swift-ci Please test Windows

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Pull request merged**
