### PR TITLE
Verify OSSA address phis.

### PR DESCRIPTION
**Pull request by atrick**
Verify that address phis are prohibited in all OSSA passes.

Eventually they should be prohibited in all passes. This at least
allows preserving access markers in OSSA passes.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci test source compatibility

**Comment by atrick** [comment]
Test failure: emit-forward-modules.swift

swiftmodule '/Volumes/swift-ci/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/test-iphonesimulator-i386/ModuleInterface/Output/emit-forward-modules.swift.tmp/Foo.swiftmodule/i386-apple-ios-simulator.swiftmodule' is not a forwarding module!

**Comment by atrick** [comment]
@swift-ci smoke test macOS

**Comment by atrick** [comment]
@gottesmm @meg-gupta OSSA passes should be able to rely on the presence of begin/end_access markers. I believe SemanticARCOpts already does. We should make sure AccessMarkerElimination always runs after OwnershipElimination. As part of migrating tests to OSSA, we should also add the access markers. Eventually, AccessMarkerElimination can go away entirely. When access markers present it's easier to analyze memory access, and also allows fixing some of the pass ordering problems today where access enforcement selection can only be done very early.

**Comment by gottesmm** [comment]
LGTM. Thanks!

**Review by gottesmm — COMMENTED** [review]
Nice LGTM!

**Pull request merged**
