### PR TITLE
Temporary removal of RangeSet/DiscontiguousSlice

### PR DESCRIPTION
**Pull request by natecook1000**

### CODE REVIEW

**Comment by natecook1000** [comment]
@swift-ci Please smoke test

**Comment by natecook1000** [comment]
@swift-ci Please smoke test

**Comment by drodriguez** [comment]
I might be wrong, but maybe https://github.com/apple/swift/blob/main/test/api-digester/stability-stdlib-abi-without-asserts.test should have the same modification as the `-with-asserts.test`. It seems to be making the CI fail and not publish nightlies: https://ci.swift.org/view/Packages/job/oss-swift-package-osx/.

**Comment by benrimmington** [comment]
The API removals should *only* be listed in the `-without-asserts.test` file, which is then used by the other file:

https://github.com/apple/swift/blob/6a6689554a61fddda1ee9601ae20194c74099cd8/test/api-digester/stability-stdlib-abi-with-asserts.test#L30-L31

If you list them in *both* files, then the test will fail (or at least it did when I tried it a few months ago).

**Pull request merged**
