### PR TITLE
[CMake] Build macro plugin and plugin servers as a package

### PR DESCRIPTION
**Pull request by rintaro**
Build swift-syntax libraries in `lib/swift/host`, macro plugin libraries, and plugin servers as a single package "Toolchain"
This enables CMO between them.

### CODE REVIEW

**Comment by rintaro** [comment]
https://github.com/swiftlang/swift-syntax/pull/2828
@swift-ci Please smoke test

**Comment by rintaro** [comment]
https://github.com/swiftlang/swift-syntax/pull/2828
@swift-ci Please smoke test

**Comment by rintaro** [comment]
https://github.com/swiftlang/swift-syntax/pull/2828
@swift-ci Please smoke test Windows

**Comment by rintaro** [comment]
https://github.com/swiftlang/swift-syntax/pull/2828
@swift-ci Please smoke test

**Review by bnbarham — APPROVED** [review]

**Pull request merged**
