### PR TITLE
DriverTool: add support for WebAssembly autolink entries

### PR DESCRIPTION
**Pull request by MaxDesiatov**
This change adds support for `.swift1_autolink_entries` in WebAssembly object files to `lib/DriverTool/autolink_extract_main.cpp`. This is implemented in a similar way to existing ELF autolink entries handling.

Related to SR-9307.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Comment by MaxDesiatov** [comment]
CC @kateinoigakukun

**Comment by MaxDesiatov** [comment]
@swift-ci please test Windows platform

**Review by compnerd — APPROVED** [review]
This is rather unfortunate.  Since WASM is still relatively new, I still think that we should consider just requiring LLD and falling back to the LLVM extensions.

**Pull request merged**
