### PR TITLE
 build-script: Pass path to just-built libddispatch and Foundation to dotest.py

### PR DESCRIPTION
**Pull request by adrian-prantl**
rdar://problem/37354542

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@adrian-prantl I am not suggesting this now, but have you guys considered using cmake packages to just pull this in like we do for LLVM in Swift?

**Comment by gottesmm** [comment]
(In fact, I am not even sure if it would work, just a random thought).

**Comment by adrian-prantl** [comment]
@gottesmm The problem is that we need to locate the swift foundation and libdispatch in their *build* directories because the tests can be run without installing anything.

**Comment by gottesmm** [comment]
Ok.

**Pull request merged**
