### PR TITLE
Reduce the code size of the standard library by about 5%-6%

### PR DESCRIPTION
**Pull request by swiftix**
Reduce the code size of the standard library by about 5%-6% by adding annotations preventing inlining and/or generic specialization in a couple of places. These places were identified by means of the cmpcodesize utility.

• Explanation: Reduce the code size of the standard library dylib.

• Scope of Issue: Inlining and specialization of some generic functions were causing significant code increase without providing any performance improvements. This PR addresses this issue.

• Origination: N/A

• Risk: Very low. This patch is cherry-picked from the master, where these changes have been landed a week ago and have not caused any issues or performance regressions. The only effect of this PR is the reduced code size of the stdlib.

rdar://problem/32776747

### CODE REVIEW

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by swiftix** [comment]
@aschwaighofer Could you please review this PR?

**Comment by aschwaighofer** [comment]
LGTM

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
Nice!

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by swiftix** [comment]
@swift-ci please test osx

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please smoke test Linux

**Comment by swiftix** [comment]
@swift-ci please test linux

**Comment by swiftix** [comment]
@swift-ci please test OS X

**Comment by swiftix** [comment]
@swift-ci please smoke test OS X

**Pull request merged**
