### PR TITLE
Update linux-fatal-backtrace.swift

### PR DESCRIPTION
**Pull request by sarveshtamba**
Cherry-pick PR#23621 from master to swift-5.1-branch

### CODE REVIEW

**Comment by sarveshtamba** [comment]
@compnerd please review and approve.

**Review by compnerd — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please smoke test and merge

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by sarveshtamba** [comment]
compnerd can this be tested and merged?

**Comment by sarveshtamba** [comment]
@compnerd anything on this?

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Pull request merged**
