### PR TITLE
[SILGen] Only emit Builtin.swift3ImplicitObjCEntrypoint() calls in Swift 4

### PR DESCRIPTION
**Pull request by DougGregor**
Only emit calls to `Builtin.swift3ImplicitObjCEntrypoint()` when we are
in Swift 4 mode with `-enable-swift3-objc-inference`, which is a
transitional state in which one is debugging the use of the
deprecated `@objc` entrypoints. Fixes rdar://problem/32122408.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Review by jrose-apple — APPROVED** [review]

**Comment by DougGregor** [comment]
Forgot about that test. Sigh.

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
