### PR TITLE
Add expectDebugCrash to StdlibUnittest

### PR DESCRIPTION
**Pull request by frootloops**
History: https://github.com/apple/swift/pull/13411 -> https://github.com/apple/swift/pull/13431 -> https://github.com/apple/swift/pull/13460

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
Isn't `fatalError` still a crash?

**Comment by gparker42** [comment]
`expectCrash` and `expectDebugCrash` should be tested in `validation-test/StdlibUnittest/CrashingTests.swift`.

**Comment by gparker42** [comment]
And yes, `fatalError` is a crash according to `expectCrashLater`.

**Review by jrose-apple — CHANGES_REQUESTED** [review]
What we really want is for expectCrashLater to check that the output is definitely not what expectUnreachable would output.

**Comment by jrose-apple** [comment]
Oops, that would be solving a different problem. I see what's going on here: we're *trying* to trigger the crash in a debug configuration, because it wouldn't crash otherwise. I'm not sure we can observe failure this way, though.

**Comment by CodaFi** [comment]
@frootloops If you wish to pursue this change, please send us an updated pull request that responds to the feedback here.  I'm going to close this since it's been a few years without any activity here.

**Pull request closed without merging**
