### PR TITLE
build: split and rename `add_swift_library`

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please clean test Linux platform

**Comment by compnerd** [comment]
CC: @Rostepher @gottesmm 

This is a cleaned up version of the first patch to split up and replace `add_swift_library` to just wrap up `llvm_add_library`.  I cannot reproduce the failure locally, @shahmishal can you verify that there isn't a version of the swift libraries that has leaked onto the host?  It seems like the wrong version of the library might be in use.

**Comment by gottesmm** [comment]
@compnerd if this isn't working, perhaps do the split/debriding as a separate PR from changing to use LLVM on the host side. Too many changes at once can cause problems.

**Comment by compnerd** [comment]
@gottesmm - this doesn't use the`llvm_*` functions yet.  This is the same code as before just splatted out.

**Comment by compnerd** [comment]
Rebased.

**Pull request closed without merging**
