### PR TITLE
Serialization: Don't serialize the 'self' parameter

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test compiler performance

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by bob-wilson** [comment]
This seems to have caused a CI regression:
https://ci.swift.org/job/oss-swift_tools-R_stdlib-RD_test-simulator/624 (rdar://problem/35639403)

**Pull request merged**
