### PR TITLE
[Serialization] Mark decls that can never be cross-referenced

### PR DESCRIPTION
**Pull request by jrose-apple**
This allows us to filter them out in cases that would otherwise be ambiguous. The particular prompting situation looks a lot like the test case: a protocol, plus a forward-declared class with the same name. (Normally we ignore forward-declared classes, but SourceKit's module interface generation feature makes dummy ClassDecls for them instead.)

[SR-4851](https://bugs.swift.org/browse/SR-4851), plus possibly other SourceKit crashes in ModuleFile::readConformance.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Review by DougGregor — APPROVED** [review]
The approach is reasonable for dodging deserialization bugs. Adding an attribute for this feels really heavyweight to solve the problem (vs. a bit), but I guess you did this so we don’t pollute the Decl itself with this one-off thing?

**Comment by jrose-apple** [comment]
That was the idea, yeah. If you'd prefer a bit I can switch to that, but since most decls won't have it I didn't want to claim the space forever.

**Pull request merged**
