### PR TITLE
[upstream-update] Include llvm/Support/MemoryBuffer.h directly to unb…

### PR DESCRIPTION
**Pull request by gottesmm**
…reak the master-next build.

rdar://36765072

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
I am just verifying that we get to at least the tests like we did on my local machine. I am not sure if the tests pass, but unbreaking the actual build is the first step to that.

**Comment by bob-wilson** [comment]
Hah, I just finished testing the identical change in a local build.... Heads-up: after that fix, the IRGen/ordering_x86.sil test is failing. Should I look at that or do you have a local build where you can triage it?

**Comment by gottesmm** [comment]
I have a local build where I can triage it.

**Pull request merged**
