### PR TITLE
Debug Info: Encode Archetype names in DWARF

### PR DESCRIPTION
**Pull request by adrian-prantl**
Currently LLDB calls into ide::getDeclFromMangledSymbolName() to get
to this information and we would like to get rid of this call.

rdar://problem/47798056

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by slavapestov** [comment]
Sorry for the inconvenience but do you mind rebasing this on top of https://github.com/apple/swift/pull/22252 ? We really only need names for top-level generic parameters; dependent member type names are part of the mangling and don't need to be recorded here.

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-lldb/pull/1318
@swift-ci test

**Comment by adrian-prantl** [comment]
@slavapestov I think rebasing this on #22252 or vice versa shouldn't be hard at all so the order in which we land these probably doesn't matter too much.

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-lldb/pull/1318
@swift-ci test

**Comment by adrian-prantl** [comment]
Linux test failed because a Foundation test failed, which is likely unrelated to this patch.

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-lldb/pull/1318
@swift-ci test

**Pull request merged**
