### PR TITLE
Runtime/standard library: fix tuple printing, reflection, and casting

### PR DESCRIPTION
**Pull request by DougGregor**
This pull request provides various improvements for the runtime handling of tuples, including:
- Printing the labels with `print` and `String.init(describing:)`
- Providing label names in mirrors
- Dynamic casting between tuple types element-by-element

Resolves at least rdar://problem/23130016, rdar://problem/22191852, and rdar://problem/19892202

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@shahmishal the macOS smoke test failed with a "wrong sha" failure:

  https://ci.swift.org/view/Pull%20Request/job/swift-PR-osx-smoke-test/1843/console

**Comment by DougGregor** [comment]
Linux smoke test succeeded here: https://ci.swift.org/view/Pull%20Request/job/swift-PR-Linux-smoke-test/1339/console

**Comment by jrose-apple** [comment]
I don't think we should support dynamic casting if we don't support static casting, no?

```swift
let x: (Any, Any) = (1, 1) as (Int, Int)
```

**Comment by DougGregor** [comment]
Yeah, but this works:

    let x: (Any, Any) = (1, 1)

**Comment by DougGregor** [comment]
All tests pass, but the status API doesn't see it. Forcing the issue.

**Comment by jrose-apple** [comment]
That's not the same thing. Constructing a new tuple coerces the elements, but going from one tuple to another doesn't.

```swift
let x: (Int, Int) = (1, 2)
let y: (Any, Any) = x
```

**Comment by jckarter** [comment]
The "cannot express" is the infamous "LAME:" error message we output because we don't have the AST nodes necessary to represent tuple-to-tuple conversions. AIUI covariant tuple conversions are intended to work. Elementwise conversions do work:

```
let x1 = 1
let x2 = 2
let y: (Any, Any) = (x1, x2)
```

**Pull request merged**
