### PR TITLE
Mangling: Make sure we have different names for function overloads with all args in a tuple.

### PR DESCRIPTION
**Pull request by eeckstein**
For example:
public func test(_ a: Int, _ b: Int)
public func test(_ t: (Int, Int))

fixes rdar://problem/31211238

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci Please smoke test and merge

**Comment by jrose-apple** [comment]
This is also [SR-1795](https://bugs.swift.org/browse/SR-1795) and rdar://21655241.

**Comment by jrose-apple** [comment]
Another test case:

```swift
func foo(_: ()) {}
func foo() {}
```

**Comment by slavapestov** [comment]
Another case we currently get wrong is varargs that are not in the last argument position. @jckarter knows the details.

**Comment by jrose-apple** [comment]
That one's [SR-1076](https://bugs.swift.org/browse/SR-1076). :-)

**Comment by eeckstein** [comment]
@swift-ci Please smoke test and merge

**Comment by eeckstein** [comment]
@jrose-apple Thanks for the additional test case!

**Comment by eeckstein** [comment]
@swift-ci Please smoke test and merge

**Pull request merged**
