### PR TITLE
[AddressLowering] Factored out unconditional_checked_cast rewriting.

### PR DESCRIPTION
**Pull request by nate-chandler**
Previously, there were three places where `unconditional_checked_cast` instructions were rewritten as `unconditional_checked_cast_addr` instructions:
- from address-only
- to address-only
- neither

Here, all three are made to factor through the new `rewriteUnconditionalCheckedCast` function.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test and merge

**Comment by nate-chandler** [comment]
@swift-ci please test linux platform

**Review by atrick — COMMENTED** [review]
Nice

**Pull request merged**
