### PR TITLE
IRGen/Runtime: Allow mangled type refs to embed "symbolic references" to type context descriptors.

### PR DESCRIPTION
**Pull request by jckarter**
This makes resolving mangled names to nominal types in the same module more efficient, and for eventual secrecy improvements, also allows types in the same module to be referenced from mangled typerefs without encoding any source-level name information about them.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test source compatibility

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test source compatibility

**Comment by xedin** [comment]
@jckarter would this help with finding locally declared nominal types? e.g.

```swift
func foo() {
  class A {}
}
```

**Comment by jckarter** [comment]
@xedin I hope so! My hope is that this should unblock the last bit of your work to replace the field type accessors with remote mirror field metadata.

**Comment by xedin** [comment]
@jckarter Awesome!

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test OS X

**Comment by jckarter** [comment]
@swift-ci Please test

**Pull request merged**
