### PR TITLE
[SR-237][build-script] Migrate --skip-{variant} --skip-build-{variant} arguments

### PR DESCRIPTION
**Pull request by rintaro**
#### What's in this pull request?

More work on [[SR-237] Merge `build-script-impl` into `build-script`](https://bugs.swift.org/browse/SR-237).

Eliminate calculating
`SKIP_BUILD_{VARIANT}_{DEVICE,SIMULATOR}` and `SKIP_TEST_{VARIANT}_{HOST,SIMULATOR}`
from `build-script-impl`.

Migrated arguments:
`--skip-{ios,tvos,watchos}`
`--skip-build-{osx,ios,tvos,watchos,android}`
`--skip-build-{osx,ios,tvos,watchos,android}-{device,simulator}`
`--skip-test-osx`

Removed from `build-script-impl`: 
`--skip-{ios,tvos,watchos}`
`--skip-build-{osx,ios,tvos,watchos,android}`
These arguments are merely shorthands for `--skip-build-{ios,tvos,watchos}-{device,simulator}` and `--skip-test-{ios,tvos,watchos}-{host,simulator}`
## 

Prior to this task, strictly separated "argument tweaks" and "build-script-impl args generation".
Typically: 

``` python
    if not args.host_test:
        build_script_impl_inferred_args += [
            "--skip-test-ios-host",
            "--skip-test-tvos-host",
            "--skip-test-watchos-host",
        ]

    # ... something ...

    if args.skip_test_ios_host:
         build_script_impl_args += ['--skip-test-ios-host']

    build_script_impl_args += build_script_impl_inferred_args
```

into 

``` python
    if not args.host_test:
        args.skip_test_ios_host = True
        args.skip_test_tvos_host = True
        args.skip_test_watchos_host = True

    # ... something ...

    if args.skip_test_ios_host:
         build_script_impl_args += ['--skip-test-ios-host']
```

Because the former style leads to "race" condition where `args.skip_test_ios_host` could be `False`, but actually, `--skip-test-ios-host` is passed to `build-script-impl`.
#### Resolved bug number: (Partially [SR-237](https://bugs.swift.org/browse/SR-237))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

### CODE REVIEW

**Comment by rintaro** [comment]
CC: @gribozavr @shahmishal @modocache @gottesmm 
This PR is modifying most critical part of `build-script`.
I hope at least 2 of you could review this.

**Comment by gribozavr** [comment]
LGTM, let's see what the CI says.

**Comment by gribozavr** [comment]
@swift-ci Please test and merge

**Comment by gribozavr** [comment]
@swift-ci Please test and merge

**Pull request merged**
