### PR TITLE
[6.0] Macro plugin related changes

### PR DESCRIPTION
**Pull request by rintaro**
Cherry-pick recent macro plugin related changes to release/6.0
* https://github.com/apple/swift/pull/69240
* https://github.com/apple/swift/pull/72999
* https://github.com/apple/swift/pull/73517

Info:

* **Explanation**: Bundle of recent macro plugin related changes. By this, the compiler uses the same JSON encoder/decoder as the plugins including `swift-plugin-server`. Also, move most of the `swift-plugin-server` code  to `swift-syntax` repository. This improves re-usability of the code, so other future components can use it.
* **Risk**: Mid, Changing JSON coder has some risk, but the new coder has more test coverage. Also, this changes the type discovery mechanism of `swift-plugin-server` form `dlsym` type metadata accessors to `_typeByName` runtime function, but the function exist for long time and well reliable.
* **Scope**: Macro plugins
* **Issue**: N/A
* **Reviewer**: Alex Hoppen (@ahoppen) Hamish Knight (@hamishknight)

### CODE REVIEW

**Comment by rintaro** [comment]
https://github.com/apple/swift-syntax/pull/2643
@swift-ci Please test

**Comment by rintaro** [comment]
@swift-ci Please test Linux

**Comment by rintaro** [comment]
https://github.com/apple/swift-syntax/pull/2643
@swift-ci Please test

**Comment by rintaro** [comment]
https://github.com/apple/swift-syntax/pull/2643
@swift-ci Please test

**Review by bnbarham — APPROVED** [review]

**Pull request merged**
