### PR TITLE
Rename OutputStream to OutputStreamable [SE-0086]

### PR DESCRIPTION
**Pull request by parkera**
#### What's in this pull request?

Per the accepted [SE-0086](https://github.com/apple/swift-evolution/blob/master/proposals/0086-drop-foundation-ns.md), rename the standard library `OutputStream` type to `OutputStreamable`. `NSOutputStream` will become `OutputStream` in a different commit.
#### Resolved bug number

rdar://27355220

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by parkera** [comment]
@swift-ci please test

**Comment by parkera** [comment]
cc @dabrahams @gribozavr

**Comment by dabrahams** [comment]
I’m sorry, I didn’t expect to find stdlib API changes in a proposal with that title, so I didn’t review this, and nobody brought it to my attention.  `OutputStreamable` is not the right name for this protocol.  It represents things into which bits of text can be streamed, not things that can themselves be streamed.  `TextOutputStream` would be an acceptable name.

**Comment by xwu** [comment]
How about `OutputStreaming` or the delightfully uncreative `OutputStreamProtocol`?

**Comment by dabrahams** [comment]
on Mon Jul 18 2016, Xiaodi Wu <notifications-AT-github.com> wrote:

> How about `OutputStreaming` or the delightfully uncreative `OutputStreamProtocol`?

To me these seem much weaker than TextOutputStream; the first is
ambiguous about whether the conforming type is the stream or the
to-be-streamed and both leave out the Text part which is a very specific
constraint of this protocol.

**Comment by parkera** [comment]
Fine, `TextOutputStream`. Looks like we need a PR for swiftpm as well.

**Comment by parkera** [comment]
kicking off tests again; swiftpm will fail but at least we'll know the rest is right.

**Comment by parkera** [comment]
@swift-ci please test

**Comment by parkera** [comment]
I'm going to add a temporary typealias to avoid the lock-step build dependencies between projects.

**Comment by parkera** [comment]
@swift-ci Please test and merge

**Comment by parkera** [comment]
We're going to go ahead and merge this.

**Pull request merged**
