### PR TITLE
ABI: Clean up context and method descriptor pointers

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by slavapestov** [comment]
@compnerd I'm in no rush to merge this so it can wait until this is resolved, but do you have any ideas what's going on?

```
 > git fetch --tags --progress https://github.com/apple/swift.git +refs/pull/*:refs/remotes/origin/pr/*
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/apple/swift.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:894)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1161)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1192)
	at org.jenkinsci.plugins.multiplescms.MultiSCM.checkout(MultiSCM.java:143)
	at hudson.scm.SCM.checkout(SCM.java:504)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1208)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
	at hudson.model.Run.execute(Run.java:1810)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
```

**Comment by slavapestov** [comment]
@swift-ci Please test Windows platform

**Comment by compnerd** [comment]
@slavapestov nope - @shahmishal might have a better idea - that crops up from time to time and a re-run usually cleans it up

**Comment by slavapestov** [comment]
@swift-ci Please test Windows platform

**Comment by slavapestov** [comment]
This doesn't look like its from my changes:

```
Failing Tests (1):
    Swift(windows-x86_64) :: CrossImport/module-trace.swift
```

**Comment by shahmishal** [comment]
@compnerd Is this flaky test on Windows?

**Comment by shahmishal** [comment]
Created: https://bugs.swift.org/browse/SR-12249

**Pull request merged**
