### PR TITLE
[Serialization] Serialize hasCReferences to keep linkage

### PR DESCRIPTION
**Pull request by kateinoigakukun**
hasCReferences is used to determine that the function is externally
available. If a function has @_cdecl and not used from anywhere in Swift
side code, it will be emitted due to its hasCReferences. But if the
attribute is not restored from sib, it won't be emitted even if it's
used externally. So we need to serialize the attribute.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Review by xymus — APPROVED** [review]
This looks good, thank you! Can you fix the conflict so we can launch the tests?

**Comment by kateinoigakukun** [comment]
@xymus Thanks for review! I rebased this branch 👍

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by kateinoigakukun** [comment]
Hmm, it seems linux CI failure is not related to this change. Could you trigger again?

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by xymus** [comment]
@swift-ci Please test Linux platform

**Pull request merged**
