### PR TITLE
Remove SWIFTLIB_SINGLE_TARGET_LIBRARY

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test windows platform

**Review by compnerd — APPROVED** [review]
Thanks for the clean up!  This looks right to me - they are always "target" libraries in this sub-project.

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@compnerd, the Windows bot says:
```
LINK: command "C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1429~1.300\bin\Hostx64\x64\link.exe /nologo lib\swift\windows\x86_64\swiftrt.obj stdlib\private\BlocksRuntimeStubs\CMakeFiles\BlocksRuntimeStub-windows-x86_64.dir\BlocksRuntime.c.obj /out:test-windows-x86_64\BlocksRuntime.dll /implib:test-windows-x86_64\BlocksRuntime.lib /pdb:test-windows-x86_64\BlocksRuntime.pdb /dll /version:0.0 /INCREMENTAL:NO /INCREMENTAL:NO -LIBPATH:T:\llvm\.\lib -LIBPATH:T:\swift\.\lib\swift\windows\x86_64 -LIBPATH:T:\swift\.\bin\..\lib\swift\windows\x86_64 -LIBPATH:T:\swift\.\bin\..\lib\swift\windows -LIBPATH:\usr\lib\swift -LIBPATH:C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1429~1.300\Lib\x64 -LIBPATH:C:\PROGRA~2\WI3CF2~1\10\Lib\100177~1.0\ucrt\x64 -LIBPATH:C:\PROGRA~2\WI3CF2~1\10\Lib\100177~1.0\um\x64 -LIBPATH:T:\swift\winsdk_lib_x86_64_symlinks -LIBPATH:C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\icu-64_2\lib64 kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:test-windows-x86_64\BlocksRuntime.dll.manifest" failed (exit code 1120) with the following output:
   Creating library test-windows-x86_64\BlocksRuntime.lib and object test-windows-x86_64\BlocksRuntime.exp
swiftrt.obj : error LNK2019: unresolved external symbol __imp_swift_addNewDSOImage referenced in function "void __cdecl swift_image_constructor(void)" (?swift_image_constructor@@YAXXZ)
test-windows-x86_64\BlocksRuntime.dll : fatal error LNK1120: 1 unresolved externals
```

That sounds related to this change... Any ideas?

**Comment by compnerd** [comment]
https://github.com/apple/swift/pull/38978/files?w=1#diff-e2e2a250882f66d531f2a42c201e013fa2d8be892b2880a32d6596710761f470L878-L895

You are now linking in the runtime object on Linux and Windows, this is an incorrect functional change.

**Comment by kubamracek** [comment]
@compnerd Thanks!

**Comment by kubamracek** [comment]
@swift-ci please test

**Pull request merged**
