### PR TITLE
[SourceKit] Enable ASTContext caching in other completion-like requests

### PR DESCRIPTION
**Pull request by rintaro**
TypeContextInfo and ConformingMethodList

rdar://problem/64782333

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please Build Toolchain macOS

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Review by benlangmuir — COMMENTED** [review]
We should add an option for this like we do with regular code-completion so that it's possible to disable, even if we default to true.

**Comment by rintaro** [comment]
@benlangmuir Made it configurable.

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Review by benlangmuir — APPROVED** [review]

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test Linux

**Pull request merged**
