### PR TITLE
[Dependency Scanner] Add API to query emitted diagnostics during a scan

### PR DESCRIPTION
**Pull request by artemcm**
Adds a simple, opaque API to libSwiftScan to query the scanner's diagnostics emitted so far. 

This is accomplished by the `DependencyScanningTool` keeping around a new `DependencyScannerDiagnosticCollectingConsumer` which collects all diagnostics emitted during a scan. Also adds an API to clear the collected-so-far diagnostics by clients.

### CODE REVIEW

**Comment by artemcm** [comment]
API exercised and tested in https://github.com/apple/swift-driver/pull/1174

**Comment by artemcm** [comment]
https://github.com/apple/swift-driver/pull/1174
@swift-ci test

**Comment by artemcm** [comment]
https://github.com/apple/swift-driver/pull/1174
@swift-ci test Windows platform

**Comment by artemcm** [comment]
https://github.com/apple/swift-driver/pull/1174
@swift-ci test Windows platform

**Review by nkcsgexi — APPROVED** [review]
Very cool!

**Pull request merged**
