### PR TITLE
Gardening.

### PR DESCRIPTION
**Pull request by dan-zheng**
- Remove unused `SWIFT_ENABLE_TENSORFLOW` known protocols.
- Readd AutoDiff test, previously accidentally removed.

### CODE REVIEW

**Review by rxwei — APPROVED** [review]

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Pull request merged**
