### PR TITLE
Bespoke array iterator [NOMERGE]

### PR DESCRIPTION
**Pull request by dabrahams**
Work on moving `Sequence._copyContents` to `Iterator._initialize` (to be used for `String` optimization) speeds up most things a lot but breaks a couple of optimizations and reveals a type checker bug.

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please benchmark

**Comment by dabrahams** [comment]
@swift-ci Please smoke test Linux platform

**Comment by dabrahams** [comment]
@rudkx @DougGregor [this failure](https://ci.swift.org/job/swift-PR-Linux-smoke-test/8844/consoleFull#1470028186ee1a197b-acac-4b17-83cf-a53b95139a76) is a really strange type-checker effect.  Any ideas?

**Comment by rudkx** [comment]
@dabrahams It appears that `_ = [1].reversed().makeIterator()` is also considered ambiguous after your changes. I'm taking a closer look.

**Comment by DougGregor** [comment]
That ambiguity is pretty nonsensical. I think the type checker is lying to you in its diagnostics.

**Comment by rudkx** [comment]
I think there is a bug in how we compare solutions and that perhaps even without your changes it would have come up as ambiguous if this bug wasn't there. Independent of that bug I don't like how we do that comparison and it's definitely on the table to review for the future (although we need to be careful about source compatibility).

In this case it looks like we decide `RandomAccessCollection.reversed()` is better than `BidirectionalCollection.reversed()` but `ReversedCollection.makeIterator()` is better than `Collection.makeIterator()`, which is why it calls chaining them ambiguous.

**Comment by rudkx** [comment]
In https://github.com/apple/swift/pull/10600 I've fixed the type checker issue, but as I suspect we'll now consider this code in swift-corelibs-foundation ambiguous even without your change. We'll either need to find a way to make one of the solutions the "winner" here and in the short term perhaps just work-around it in swift-corelibs-foundation by splitting the expression up so that reversed() and makeIterator() are in separate expressions.

**Comment by rudkx** [comment]
I'm not sure if you're still planning on trying to merge this at some point, but the aforementioned type checker issue was fixed sometime in the last few months.

**Comment by dabrahams** [comment]
@milseman should decide whether this has value. The idea was to improve perf IIRC

**Comment by milseman** [comment]
CC @lancep for the Array part.

I'm missing some background here. Why is `Iterator._initializing` better than `Array._copyContents(initializing:)`?

**Comment by dabrahams** [comment]
Aside from being a decent API worthy of being de-underscored you mean? 😉

Suppose you have a sequence like Array that has an optimized implementation, you’re in a generic context, and you need to write whatever will fit into buffer1 and then the remainder into buffer2?  How do you do it without losing the optimization for the second write?  This comes up especially when appending a sequence to contiguous, resizable storage, for example. Clearly from the commit message I saw some speedups at one point. I think it’s also probably important for supporting segmented collections, FWIW.  There are probably other reasons more specific to String, though I don’t remember them offhand.

**Comment by CodaFi** [comment]
@dabrahams Just pinging the old PRs.  Should we keep this one open as well?

**Comment by dabrahams** [comment]
@CodaFi for each of these, please ask the person responsible for the relevant part of the standard library to have a look and make a judgement call.  I'm fine with whatever they want to do.

Thanks!

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by CodaFi** [comment]
Spoke with @milseman and we agreed to close this one out.

Thanks Dave.

**Pull request closed without merging**
