### PR TITLE
[Gardening] Migrate complete_expr_postfix_begin test to use new batching

### PR DESCRIPTION
**Pull request by bnbarham**
I changed this test in my other PR. Figured it would be good to migrate it over to the new batch mode while I was there.

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
Going to leave running the tests again since there's a failure on main at the moment

**Comment by bnbarham** [comment]
I'd be more comfortable with a full test but OSX is failing on main at the moment :(

**Comment by bnbarham** [comment]
@swift-ci please smoke test

**Review by rintaro — APPROVED** [review]
Looks good!

**Comment by bnbarham** [comment]
I'll wait until yours is merged and then change this one to use the new XFAIL instead

**Comment by bnbarham** [comment]
@swift-ci please smoke test

**Pull request merged**
