### PR TITLE
[6.0][Distributed] remote calls over-retain returned values

### PR DESCRIPTION
**Pull request by ktoso**
**Description**: We missed to deinitialize a return value buffer and only destroyed it, leading to over-retained objects returned from remote calls.
**Scope/Impact**: Impacts all remote calls on distributed actors
**Risk:** Low, trivial missing deinit call
**Testing**: CI testing, verified the leak existed and is fixed
**Reviewed by**: @mikeash @xedin 

**Original PR:** https://github.com/swiftlang/swift/pull/76595 https://github.com/swiftlang/swift/pull/76862 https://github.com/swiftlang/swift/pull/76888
**Radar:**
rdar://136313477
rdar://136338200

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
Now also includes https://github.com/swiftlang/swift/pull/76862

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
