### PR TITLE
[WIP] Conditionally conform stdlib types to Hashable

### PR DESCRIPTION
**Pull request by lorentey**
As a followup to [SE-0143], this adds conditional conformance to `Hashable` to the following types in the standard library:

* `Optional`
* `Array`, `ContiguousArray`, `ArraySlice`
* `Dictionary`
* `Range`, `ClosedRange`
* `AnyCollection`
* `DictionaryLiteral`
* `CollectionOfOne`

This PR also adds unconditional conformance to `Hashable` for `EmptyCollection`.

This makes synthesized `Hashable` implementations ([SE-0185]) available for structs and enums that include fields of these types, freeing programmers from having to manually deal with hash combinators.

[SE-0185]: https://github.com/apple/swift-evolution/blob/master/proposals/0185-synthesize-equatable-hashable.md

As part of this work, this PR also adds conditional conformances to `Equatable` to the following types:  

* `AnyCollection`
* `DictionaryLiteral`
* `CollectionOfOne`

Resolves [SR-6910].

[SE-0143]: https://github.com/apple/swift-evolution/blob/master/proposals/0143-conditional-conformances.md
[SR-6910]: https://bugs.swift.org/browse/SR-6910

### CODE REVIEW

**Comment by lorentey** [comment]
This is a continuation of @mortenbekditlevsen's PR #14247; having a dedicated branch makes it easier to collaborate on landing this change.

**Comment by xwu** [comment]
@lorentey Perhaps this is obvious to all involved already, but I am discovering that in fact Swift ignores `@available` attributes for extensions, so it appears that we can't use that solution for the standard library changes here to coordinate with SwiftPM.

**Comment by lorentey** [comment]
@xvu That's unfortunate; I think we may still get it to work by also adding the attribute to the individual members that implement the conformances. (At the cost of adding more warnings to stdlib's build logs.)

Or we may just leave these types out for now; however, shipping conditional conformances without full stdlib coverage would probably lead to people adding these conformances in their own code, causing even more issues. cc @airspeedswift

**Comment by xwu** [comment]
We didn't have this problem with `Array`, for instance, because `==` was already provided by the standard library since it was so useful even without conditional conformance.

I really think `DictionaryLiteral` qualifies as a corner case that can be dropped if needed. If you think about it, the scenario we're in arose because `DictionaryLiteral` didn't ship with `==`, not because now we're trying to state the conditional conformance.

**Comment by lorentey** [comment]
I agree that `DictionaryLiteral` should not delay this PR; we can add its conformances later(*), if this proves to be a difficult issue. (We've already punted `Slice` to a followup PR.) But we're not yet ready to merge this PR anyway, so we have a little time to work on a solution before doing that.

The `hashValue` implementations in this PR are all new, and they could easily cause similar compatibility issues in other packages. (Thankfully swiftpm is not affected.) They need to have the same availability attribute.

(*) However, *later* cannot mean a subsequent Swift release, because that would leave the door wide open for even more serious problems. If the stdlib didn't provide conditional `Equatable` conformance to `DictionaryLiteral` etc., then the logical next step for packages currently implementing '==' overloads would be to add these *conformances* on their own. (What would happen when someone tried to use two of these packages in the same binary?)

Ideally, the stdlib should add conformances for its own protocols to its own types whenever doing that makes even the slightest sense, to prevent packages from trying to do it themselves.

**Comment by lorentey** [comment]
Adding `@availability` attributes to `DictionaryLiteral.==` in the stdlib and swiftpm (`introduced` and `obsoleted`, respectively) resolves the test failure. It also allows swiftpm to keep source compatibility with previous compiler versions (but not with earlier revisions of 4.1/5.0 in git).

**Comment by xwu** [comment]
Well, actually... A key difference between `hashValue` and `==` is that the latter is independently useful. There's essentially no point in implementing `hashValue` without conformance to `Hashable`, and since conditional conformances have not previously been available, I doubt that there are packages "out there" for which these problems arise.

As to your general point, I would disagree that the bar for adding conditional conformances for standard library protocols is that it "makes even the slightest sense." When there are multiple reasonable semantics for doing so, adopting one such conditional conformance bars end users from conforming in any other way.

This is particularly problematic when the standard library type in question is generic: It may make extraordinary sense to conform `StandardLibraryType<MyCustomType>` to `StandardLibraryProtocol` with some particular semantics, but the standard library vending a "slightest-sense" implementation of `StandardLibraryType<T> : StandardLibraryProtocol where T : SomeOtherConstraint` would stop me from doing so.

In general, we should reiterate that conforming a type you don't own to a protocol you don't own is not advised. We don't need to undertake heroics to design around such shenanigans, just as we don't in general make design decisions explicitly to prevent abuses.

**Comment by lorentey** [comment]
The "slightest sense" argument clearly does not apply to `DictionaryLiteral`, for which `Equatable` conformance obviously makes perfect sense. You may be right about `hashValue`, but why have the compatibility risk?

In any case, my opinion is that users should never, ever conform stdlib types to stdlib protocols, conditionally or otherwise -- that is the sole prerogative of the standard library. The way to customize/override the behavior of stdlib types is to wrap them in little structs, making the deviation explicit. Do you have an example where such a conformance may in fact be necessary? (We should probably take this to the forums, though.)

**Comment by xwu** [comment]
I think we largely agree on the general principle.

As to the appending of attributes, have you explored avoiding build warnings by instead using conditional compilation directives?

**Comment by lorentey** [comment]
`#if swift(>=x.y)` works great in swiftpm and other external packages, but sadly it doesn't work inside the stdlib. (We don't make separate builds of the stdlib for each distinct language version supported by the compiler, because we need to support linking code built in any version mode together in the same binary.)

**Comment by lorentey** [comment]
@swift-ci please test

**Comment by lorentey** [comment]
@swift-ci please test source compatibility

**Comment by lorentey** [comment]
@swift-ci please smoke test compiler performance

**Comment by lorentey** [comment]
I pushed some changes to fix the two failures in the Swift tests. I also added `@available` attributes to pave the way for a fix for the compatibility issue with swiftpm.

I expect the Linux build will still fail for now. (In fact, the package manager failure will prevent the compiler performance and source compatibility tests from succeeding, either. D'oh.)

**Comment by xwu** [comment]
Since you've annotated `ClosedRange.Index`, I've taken the same approach to add in the remainder of the annotations to changes in #12777.

**Comment by lorentey** [comment]
Oops, that was a serious oversight on my part; I intended to annotate `ClosedRange` itself. 🤦‍♂️💦

But if we mark the ones we add now, we should also mark the conformances added for SE-0188, so let's consider it a lucky mistake. (We may end up choosing to remove all of these attributes but the one for `DictionaryLiteral.==`, though. Your point about `hashValue` not likely to be defined elsewhere is valid.)

**Comment by xwu** [comment]
@lorentey Gimme 30 minutes to test apple/swift-package-manager#1494, which should unblock this work.

**Comment by lorentey** [comment]
I'm itching to try the cross-repo test mechanism, so dear friendly build robot, would you please test with the following PR:
https://github.com/apple/swift-package-manager/pull/1494

@swift-ci Please test linux platform

**Comment by xwu** [comment]
That PR is merged :)

**Comment by xwu** [comment]
@swift-ci Please smoke test OS X platform

**Comment by xwu** [comment]
@swift-ci Please smoke test OS X platform

**Comment by xwu** [comment]
@swift-ci Please smoke test Linux platform

**Comment by xwu** [comment]
@swift-ci Please smoke test Linux platform

**Comment by lorentey** [comment]
Even if the tests pass, I'm still waiting for a confirmation that this work is covered under SE-0143, so we shouldn't merge it just yet. (There is still a chance that we will need to put together a proposal for it.)

**Comment by xwu** [comment]
@swift-ci Please test source compatibility

**Comment by xwu** [comment]
@swift-ci Please test source compatibility

**Comment by xwu** [comment]
@swift-ci Please smoke test compiler performance

**Comment by xwu** [comment]
@swift-ci Please smoke test compiler performance

**Comment by xwu** [comment]
@swift-ci Please smoke test compiler performance

**Comment by xwu** [comment]
@lorentey The alternative, by the way, to all these attributes and build warnings is to implement `Equatable.==` as follows:

```swift
@_implements(Equatable, ==(_:_:))
public static func __equals(_ lhs: T, _ rhs: T) -> Bool {
  // ...
}
```

**Comment by xwu** [comment]
All checks passed (including source compatibility). I'll merge in the PR attempting an alternative solution to run some tests. We can revert if it's no good.

**Comment by xwu** [comment]
@swift-ci Please smoke test OS X platform

**Comment by xwu** [comment]
@swift-ci Please smoke test OS X platform

**Comment by xwu** [comment]
@swift-ci Please smoke test OS X platform

**Comment by xwu** [comment]
Fun. `@_implements` doesn't work in an `extension` at the moment. :/

**Comment by xwu** [comment]
@swift-ci Please smoke test

**Comment by xwu** [comment]
@swift-ci Please smoke test

**Comment by xwu** [comment]
@swift-ci Please smoke test

**Comment by xwu** [comment]
@swift-ci Please smoke test

**Comment by xwu** [comment]
@lorentey We don't need `@available` attributes for `hashValue`. Swift does the right thing here: end user definitions shadow library-vended ones without any ambiguity.

The only scenario where this fails is in the case of operators. Down the road, we'll want to fix that issue definitively; operator overload resolution has all sorts of messy issues at the moment.

**Comment by xwu** [comment]
With respect to `Equatable` conformance, though, with time I'm still not very happy with this `@available` workaround. The underscored attribute `@_implements` was _created_ in part for this purpose and we should make it work appropriately. With such an implementation, end users can continue to have their custom `==` where defined _and_ seamlessly enjoy the benefit of `Hashable` conformance.

Until then, if the worry is that leaving out a conditional conformance will cause end users to use their own, we can prohibit such use with a placeholder such as `extension AnyCollection: Equatable where Element == Never`.

**Comment by xwu** [comment]
...I have an alternative solution

**Comment by xwu** [comment]
@swift-ci Please smoke test

**Comment by xwu** [comment]
Please test with the following PR: apple/swift-package-manager#1495
@swift-ci Please smoke test Linux platform

**Comment by xwu** [comment]
Please test with the following PR: apple/swift-package-manager#1495
@swift-ci Please smoke test Linux platform

**Comment by xwu** [comment]
@swift-ci Please test source compatibility

**Comment by xwu** [comment]
@swift-ci Please test source compatibility

**Comment by mortenbekditlevsen** [comment]
May I ask: What is the next step for this PR?

**Comment by airspeedswift** [comment]
It was a little late in the 4.1 convergence cycle to get this in for that release, especially as it involves workarounds, adding an `_`-ed protocol beneath `Equatable` etc. We also need to discuss exactly which types should get this – I think the `AnyCollection` conformance to `Equatable` is debatable so needs to be discussed on evolution (though most of the other conformances are probably a simple matter that everyone will agree on).

**Comment by mortenbekditlevsen** [comment]
Super - thanks for the update! I'll move parts of the implementation to 'user space' until it lands in Swift 4.2 or Swift 5.0. :-)

**Comment by xwu** [comment]
@mortenbekditlevsen That's...not ideal if you can avoid it. Doing so guarantees that we'll be source-breaking when this does land.

**Comment by mortenbekditlevsen** [comment]
@xwu Thanks - it's only for some non-public libraries that we use internally at work, so we'll be fine with the source breaking update. 
I'm just so eager to get rid of all our own (sub-par) Hashable conformance implementations. :-)

**Comment by tkrajacic** [comment]
Will this realistically be possible to land in Swift 4.2?

I have seen there are a few open PRs concerning hashing and quite the discussion about the `Hashable` API. Would it make sense to implement this using the existing hashing API or will this need to be postponed until that discussion is sorted out?

**Comment by lorentey** [comment]
This change is orthogonal to `Hashable` discussions, and it can be done without waiting for the outcome of those. SE-0143 does not explicitly mention `Hashable` conformances, but we consider these changes to be *mostly* covered by it; an amendment might be in order to spell this out explicitly.

To get things moving again, I'm going to rebase and update this PR to incorporate recent changes in hashing, which made hash compositions much easier to implement.

While the source compatibility issue is important, I believe adding the `_Equatable` protocol to work around `@_implements` limitations is not the right way to approach this problem. With apologies to @xwu, I'm going to revert that change, along with the `DictionaryLiteral` change that triggered the swiftpm issue. (We should work this through in a separate PR.)

`AnyCollection`'s conditional conformances have proved controversial, I'm going to remove those from this PR as well, pending further discussion on swift-evolution.

**Comment by lorentey** [comment]
I opened #15382 as the rebased & updated version of this PR, with a view towards landing it soon.

**Pull request closed without merging**
