### PR TITLE
Revert "Add a verify-di-hole assertion to SILBuilder."

### PR DESCRIPTION
**Pull request by nate-chandler**
It seems to have broken building the stdlib noasserts.

rdar://107146237

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please clean benchmark

**Comment by nate-chandler** [comment]
@swift-ci Please Apple Silicon benchmark

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci Please Apple Silicon benchmark

**Comment by nate-chandler** [comment]
Building the release noassert configuration locally succeeds with the revert and fails without it.  The benchmark bots seem to need a clean, but there's no "clean benchmark" trigger.

**Comment by adrian-prantl** [comment]
Thanks for taking care of the revert, I'll see if I can fix the underlying issue!

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Pull request merged**
