### PR TITLE
[Shepherd] Support classes with missing designated inits

### PR DESCRIPTION
**Pull request by CodaFi**
Shepherds #26060

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please test

**Comment by CodaFi** [comment]
@swift-ci please test source compatibility

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
Off to 5.2 with you.

⛵️

**Comment by compnerd** [comment]
@CodaFi I think that this has caused a regression on android: https://ci-external.swift.org/job/oss-swift-RA-linux-ubuntu-16.04-android-arm64/3159/console

**Comment by CodaFi** [comment]
Hm, that’s not a particularly illuminating failure log. Do you have access to an android environment to gather more information?

**Pull request merged**
