### PR TITLE
[Runtime] Add a NULL check to MetadataAllocator.

### PR DESCRIPTION
**Pull request by mikeash**
MetadataAllocator should never return NULL, but bugs or corruption could potentially make that happen. On the large path, switch from malloc to swift_slowAlloc, which aborts on failure. On the pool path, check for a NULL allocation pointer, and log a bunch of information about the allocation request and the allocator's current state.

rdar://84503396

### CODE REVIEW

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test linux platform

**Comment by mikeash** [comment]
@swift-ci please test

**Review by al45tair — APPROVED** [review]
It might be nice to assert that `alignment` is a power of 2. Otherwise looks good to me.

**Comment by mikeash** [comment]
The Windows test failure is unrelated, merging.

**Pull request merged**
