### PR TITLE
[SE-0376] Rename `@_backDeploy(before:)` to `@backDeployed(before:)`

### PR DESCRIPTION
**Pull request by tshortli**
Update the spelling of the `@_backDeploy(before:)` attribute to `@backDeployed(before:)` in accordance with the resolution of SE-0376.

For now, swiftinterfaces will continue to print the attribute as `@_backDeploy(before:)` since the older compilers cannot parse the new spelling.

The corresponding swift-syntax PR is: https://github.com/apple/swift-syntax/pull/1304

Resolves rdar://102792909

### CODE REVIEW

**Comment by tshortli** [comment]
https://github.com/apple/swift-syntax/pull/1304

@swift-ci please test

**Comment by tshortli** [comment]
@swift-ci please test

**Comment by tshortli** [comment]
> **CHANGELOG.md**
> 
> * The example code could use syntax highlighting.
> * It may also need an `@available` above the extension.
> * The `degreesCelcius` should be `degreesCelsius`.
> * A reference (at the end of the file) is needed.

Thanks, I fixed all of these except for the omission of availability on the extension which was intentional. It is common in SDK modules for extensions to be declared without availability and to instead annotate each member individually, which I want to do in the example for clarity.

**Comment by tshortli** [comment]
https://github.com/apple/swift-syntax/pull/1304

@swift-ci please test

**Review by nkcsgexi — APPROVED** [review]
🎉

**Review by artemcm — APPROVED** [review]

**Pull request merged**
