### PR TITLE
[ASTGen] Implement some Expr generation

### PR DESCRIPTION
**Pull request by rintaro**
TODO: test cases

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Review by hamishknight — APPROVED** [review]

**Comment by rintaro** [comment]
@swift-ci Please smoke test Linux

**Comment by rintaro** [comment]
@swift-ci Please smoke test Linux

**Pull request merged**
