### PR TITLE
Use @_borrowed on a few declarations in the stdlib and overlays

### PR DESCRIPTION
**Pull request by rjmccall**

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Comment by rjmccall** [comment]
@swift-ci Please benchmark

**Comment by rjmccall** [comment]
@airspeedswift It looks like all the really serious non-`Onone` regressions here are in `AnySequence` benchmarks.  Should I be worrying about those, or are they getting ripped out?

**Comment by rjmccall** [comment]
By the way, I think the perf hit here is that we're calling the read accessor and it's having to allocate space dynamically for its frame.

**Comment by rjmccall** [comment]
@airspeedswift By "ripped out", I mean "having the guts of the implementation so thoroughly replaced that I don't need to worry about a short-term regression".

**Comment by airspeedswift** [comment]
Yeah, probably. Which isn't to say you'll still be causing regressions after this but impossible to say what. Let me rebase my PR on this one and see.

**Comment by airspeedswift** [comment]
#20454

**Comment by airspeedswift** [comment]
@swift-ci please benchmark

**Comment by airspeedswift** [comment]
Re-benchmarking now I’ve merged #20221

**Comment by palimondo** [comment]
Also, generally speaking, how much weight should we assign the performance regressions in `Onone` builds? The changes in commits looks trivial on the surface, but the slowdowns in unoptimized build look quite massive. Isn't it something that should not be overlooked?

**Pull request merged**
