### PR TITLE
[cxx-interop] Import `typedef`-ed template instantiations #32950

### PR DESCRIPTION
**Pull request by hlopko**
This is a roll-forward of https://github.com/apple/swift/pull/32950, with explicit c++17 version removed from tests. This is not needed since C++17 is the default anyway.

--

In this PR we teach `ClangImporter` to import typedef statements with template instantiation as its underlying type.

```c++
template<class T>
struct MagicWrapper {
  T t;
};

struct MagicNumber {};

typedef MagicWrapper<MagicNumber> WrappedMagicNumber;
```

will be made available in Swift as if `WrappedMagicNumber` is a regular struct. 

In C++, multiple distinct typedeffed instantiations resolve to the same canonical type. We implement this by creating a hidden intermediate struct that typedef aliasses.

The struct is named as `__CxxTemplateInst` plus Itanium mangled type of the instantiation. For the example above the name of the hidden struct is `__CxxTemplateInst12MagicWrapperI11MagicNumberE`. Double underscore (denoting a reserved C++ identifier) is used to discourage direct usage. We chose Itanium mangling scheme because it produces valid Swift identifiers and covers all C++ edge cases.

Imported module interface of the example above:

```swift
struct __CxxTemplateInst12MagicWrapperI11MagicNumberE {
  var t: MagicNumber
}
struct MagicNumber {}
typealias WrappedMagicNumber = __CxxTemplateInst12MagicWrapperI11MagicNumberE
```

We modified the `SwiftLookupTable` logic to show hidden structs in `swift_ide_test` for convenience.

Resolves https://bugs.swift.org/browse/SR-12591.

### CODE REVIEW

**Comment by hlopko** [comment]
@swift-ci please test

**Comment by hlopko** [comment]
CC @meg-gupta

**Review by gribozavr — APPROVED** [review]

**Comment by hlopko** [comment]
@swift-ci please test

**Comment by hlopko** [comment]
@swift-ci please test

**Comment by hlopko** [comment]
@swift-ci please test

**Comment by hlopko** [comment]
@swift-ci please test

**Comment by hlopko** [comment]
@swift-ci Please test Windows platform

**Comment by hlopko** [comment]
@swift-ci please test

**Comment by hlopko** [comment]
@swift-ci Please test Windows platform

**Review by gribozavr — APPROVED** [review]

**Comment by hlopko** [comment]
@swift-ci Please test Windows platform

**Comment by meg-gupta** [comment]
@hlopko This is causing an error in https://ci.swift.org/job/oss-swift_tools-R_stdlib-RD_test-simulator/ 
Can you please take a look ? Please run the preset once you have a fix.

Failing test: 
 Swift(macosx-x86_64) :: Interop/Cxx/templates/decl-with-definition-irgen.swift

From the log:
/Users/buildnode/jenkins/workspace/oss-swift_tools-R_stdlib-RD_test-simulator/swift/test/Interop/Cxx/templates/decl-with-definition-irgen.swift:12:11: error: CHECK: expected string not found in input
21:03:05 // CHECK: %magicInt = alloca %TSo037__CxxTemplateInst12MagicWrapperI10IntE1EV, align 4
21:03:05           ^
21:03:05 <stdin>:23:63: note: scanning from here
21:03:05 define swiftcc i32 @"$s4main18getWrappedMagicInts5Int32VyF"() #0 {
21:03:05                                                               ^
21:03:05 <stdin>:25:2: note: possible intended match here
21:03:05  %0 = alloca %TSo037__CxxTemplateInst12MagicWrapperI10IntE1EV, align 4
21:03:05

**Comment by meg-gupta** [comment]
Most likely a minor filecheck mismatch. I created #33507 to disable the test

**Pull request merged**
