### PR TITLE
Parser: Don't skip functions with a nested `typealias` or `actor` for LLDB

### PR DESCRIPTION
**Pull request by xymus**
The flag `-experimental-skip-non-inlinable-function-bodies-without-types` is used by the emit-module-separately phase to quickly extract the API of the target module to unblock building dependents. It is designed to preserve compatibility with LLDB by not skipping functions with nested types.

This logic relies on a simple heuristic to find nested type. It should detect nested tyealiases and actors declarations.

rdar://120928396

### CODE REVIEW

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Review by tshortli — APPROVED** [review]

**Comment by karwa** [comment]
Protocols can also be nested in functions, BTW.

**Comment by xymus** [comment]
@karwa Good point, thanks for pointing it out!

@adrian-prantl Does LLDB read nested protocols from swiftmodule files? I assume it does if it reads typealiases.

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by adrian-prantl** [comment]
@adrian-prantl Does LLDB read nested protocols from swiftmodule files? I assume it does if it reads typealiases.

Anything that can show up as a type of a variable or function call would be relevant for LLDB.

**Comment by karwa** [comment]
@adrian-prantl

> Anything that can show up as a type of a variable or function call would be relevant for LLDB.

Within the function they are declared in, they can be used just like any other protocol.

```swift
func test() -> Int {
    
    protocol ABC {
        func doSomething() -> Int
    }
    struct One: ABC {
        func doSomething() -> Int { 1 }
    }
    struct Two: ABC {
        func doSomething() -> Int { 2 }
    }

    // Function return value uses a local protocol.
    func makeOne() -> some ABC {
        One()
    }

    // Type of variable is a local protocol.
    let x: any ABC = Bool.random() ? makeOne() : Two()

    // Function argument uses a local protocol.
    func makeCall(_ input: some ABC) -> Int {
        input.doSomething()
    }

    return makeCall(x)
}
```

[Godbolt](https://swift.godbolt.org/z/s8nGo76Y4), showing that the above compiles cleanly on 5.10 nightly.

**Comment by xymus** [comment]
@swift-ci Please smoke test macOS

**Comment by adrian-prantl** [comment]
```
(lldb) r
Process 13083 launched: '/tmp/a.out' (arm64)
Process 13083 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
    frame #0: 0x0000000100003bd0 a.out`makeCall #1 <Builtin.RawPointer>(input=One @ 0xffffffffffffffff) in test() at t.swift:23:15
   21  	    // Function argument uses a local protocol.
   22  	    func makeCall(_ input: some ABC) -> Int {
-> 23  	        input.doSomething()
   24  	    }
   25  	
   26  	    return makeCall(x)
Target 0: (a.out) stopped.
(lldb) p input
(One)  {}
(lldb) p input.doSomething()
(Int) 1
(lldb) frame variable input
(One) input = {}
(lldb) frame variable --dynamic-type=no-dynamic-values input                                                                          (Builtin.RawPointer) input =
(lldb) 
```
There is nothing preventing you from using these local types in LLDB. I don't know in what situation having access to the protocol itself is going to be useful, but I'm sure we can come up with an example where that matters, too.

**Comment by xymus** [comment]
@swift-ci Please smoke test macOS

**Comment by xymus** [comment]
@swift-ci Please smoke test Linux

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by xymus** [comment]
@swift-ci Please smoke test Windows

**Pull request merged**
