### PR TITLE
Tweak benchmark setup so generate_harness.py works again [NFC]

### PR DESCRIPTION
**Pull request by natecook1000**
The templates for `generate_harness.py` have gotten slightly out of date and a few tests are being missed by the script due to being in a subdirectory of the `single-source` directory. This fixes both those issues so running the script properly generates a new test harness after adding a new test file.

### CODE REVIEW

**Comment by natecook1000** [comment]
@swift-ci Please smoke test

**Comment by djwbrown** [comment]
Thank you, I noticed this when adding a benchmark recently.

**Comment by aschwaighofer** [comment]
LGTM.

**Comment by gottesmm** [comment]
Something we should consider doing is migrating the benchmarks to swiftpm and then creating an automatic self registration. I hacked up a prototype, but it is not ready for prime time. If someone is interested, I can put it on a branch.

**Comment by natecook1000** [comment]
@gottesmm That would be great. Another improvement would be to have room for some manual-only benchmarks that might take longer than we want in CI.

@djwbrown Thank *you*—I ran into earlier, too, but left it alone until your comment on that other issue made me dig in. 👍

**Pull request merged**
