### PR TITLE
[stdlib] Remove `Strideable` closed range operator

### PR DESCRIPTION
**Pull request by benrimmington**
This pull request removes the closed range operator on `Strideable`.
It was originally for `CountableClosedRange`, when that was a separate type.
The other countable range operators on `Strideable` were removed in #13342.

### CODE REVIEW

**Comment by benrimmington** [comment]
Cc: @airspeedswift, @natecook1000

Should any of the removed documentation be transferred to the `Comparable` extension?

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@swift-ci please test source compatibility

**Comment by benrimmington** [comment]
There were five failures in the Source Compatibility Suite.

```
  FAIL: Kitura, 4.0, f1c316, Swift Package
  FAIL: NetService, 4.2, 927eb1, Swift Package
  FAIL: SRP, 4.0, b16683, Swift Package
  FAIL: SwiftLint, 4.2, 60f98e, Swift Package
  FAIL: SwiftLint, 4.0, 60f98e, Swift Package
```

Each log contained "error: dependency graph is unresolvable; found these conflicting requirements"...

**Comment by benrimmington** [comment]
The projects were XFAILed in apple/swift-source-compat-suite@5d5f2582953c254b38be49848cd563900febef60

**Comment by benrimmington** [comment]
Rebased to resolve conflict.

**Comment by jrose-apple** [comment]
Passerby testing

@swift-ci please test

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by airspeedswift** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
