### PR TITLE
Store ProtocolDecl rather than TypeLoc for designated protocol.

### PR DESCRIPTION
**Pull request by rudkx**

### CODE REVIEW

**Comment by rudkx** [comment]
```
20:56:42 /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/lldb/unittests/Disassembler/TestArmv7Disassembly.cpp:70: Failure
20:56:42 Expected: (nullptr) != (disass_sp.get()), actual: 8-byte object <00-00 00-00 00-00 00-00> vs NULL
```

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please smoke test OS X platform

**Review by jrose-apple — APPROVED** [review]
Thanks, this definitely seems like a useful step.

**Pull request merged**
