### PR TITLE
[SIL] Make sure @objc thunks for 'mutableCopy' are treated as +1

### PR DESCRIPTION
**Pull request by jrose-apple**
A nice cleanup (part of #14825) turned out to have a bug in it. Revert that and add tests to keep it from happening again.

rdar://problem/40373771

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Review by jckarter — APPROVED** [review]
Looks good!

**Comment by jrose-apple** [comment]
@stephan-tolksdorf: can't believe neither you nor I caught this at the time. :-( At least we found it!

**Comment by stephan-tolksdorf** [comment]
@jrose-apple Yeah, I should have noticed that! Sorry! :-(

**Pull request merged**
