### PR TITLE
[gyb] added feature to gyb.py to search for an process a new template…

### PR DESCRIPTION
**Pull request by flyin1600**
… tag, when encountered in AST it is processed in line

Added new tag <{TEMPLATE_FILE_NAME} for processing embedded templates in gyb templates. Created a new class to represent a template, and when they are encountered in the AST they are processed in place in a new ParseContext

### CODE REVIEW

**Comment by flyin1600** [comment]
@swift-ci Please smoke test

**Comment by dabrahams** [comment]
Why is adding this a good idea?  We already have `${expand(...)}` which serves the same purpose without adding new syntactic elements, properly interacts with line-directive and the build system, and is more flexible.  See [here](https://github.com/apple/swift/blob/unicode-rethink/stdlib/public/core/ForwardingWrapper.swift.gyb#L78-L82) for an example.

**Comment by dabrahams** [comment]
@flyin1600 accordingly, closing this PR.  If you disagree, feel free to reopen it.

**Comment by flyin1600** [comment]
no problem, it seems like this is, in fact, duplicating existing functionality

**Pull request closed without merging**
