### PR TITLE
Fix DeclarationMacro deprecations

### PR DESCRIPTION
**Pull request by AZero13**
These deprecations are simple renames, but this PR should get rid of the warnings.

### CODE REVIEW

**Comment by AtariDreams** [comment]
@CodaFi thoughts?

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
Thanks for doing this! I've kicked off PR testing.

**Review by DougGregor — APPROVED** [review]

**Comment by AtariDreams** [comment]
@DougGregor It passed!

**Pull request merged**
