### PR TITLE
[build-script] Refactor swift_build_support to prepare for moving more projects to swift_build_suppport

### PR DESCRIPTION
**Pull request by ahoppen**
This PR moves some common functionality that needs to be implemented in every `swift_build_support` product up to common locations.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by taher-mosbah — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please build toolchain macos

**Comment by ahoppen** [comment]
Manually verified that no files are missing from the toolchain generated by this PR compared to the Open Source toolchain.

**Comment by benlangmuir** [comment]
LGTM. Nitpick: we usually use « should » rather than « shall ».

**Comment by ahoppen** [comment]
Thanks for the review @benlangmuir. I have changed “shall” to “should”. I will just run the smoke tests now to get it merged.

@swift-ci Please smoke test and merge

**Comment by ahoppen** [comment]
CI failed to start. Let’s try again.

@swift-ci Please smoke test and merge

**Pull request merged**
