### PR TITLE
Revert "Remove CBasicBridging + CASTBridging"

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/swift#69440

This breaks the Windows build: https://github.com/thebrowsercompany/swift-build/actions/runs/6706204565/job/18222316183

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @hamishknight

**Comment by compnerd** [comment]
@swift-ci please smoke test Linux platform

**Comment by compnerd** [comment]
@swift-ci please smoke test macOS platform

**Comment by finagolfin** [comment]
Yep, [this broke the community Android CI too](https://ci-external.swift.org/job/oss-swift-RA-linux-ubuntu-16.04-android-arm64/5660/console). The problem appears to be that this pull requires that a prebuilt host Swift compiler be installed (maybe inadvertently?), but the linked Windows and Android CIs don't have one.

**Comment by hamishknight** [comment]
This should be resolved now by https://github.com/apple/swift/pull/69537

**Comment by compnerd** [comment]
@finagolfin right; this has been mitigated with the additional check in #69537

**Pull request closed without merging**
