### PR TITLE
[stdlib] Switch ManagedBuffer.header to use _modify

### PR DESCRIPTION
**Pull request by airspeedswift**
First go at trying this with a property rather than a subscript...

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
@swift-ci please test

**Review by lancep — APPROVED** [review]
Looks good!

**Comment by airspeedswift** [comment]
@swift-ci please smoke test compiler performance

**Comment by moiseev** [comment]
YOLO!

**Comment by airspeedswift** [comment]
@swift-ci please test compiler performance

**Comment by airspeedswift** [comment]
@swift-ci please smoke test compiler performance

**Comment by airspeedswift** [comment]
@swift-ci please test compiler performance

**Comment by airspeedswift** [comment]
I think the wall time regression on the smoke compiler bench was noise.

**Pull request merged**
