### PR TITLE
[embedded] Avoid strip-ing .a embedded libraries

### PR DESCRIPTION
**Pull request by kubamracek**
Some of the embedded .a libraries are ELF files -- we should avoid strip-ing those. Resolves a CI failure preventing macOS toolchains from being built:
```
LLVM ERROR: malformed uleb128, extends past end
xargs: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: terminated with signal 6; aborting
```

rdar://128857716

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by hamishknight — APPROVED** [review]
Thanks!

**Comment by kubamracek** [comment]
@swift-ci please smoke test macOS platform

**Comment by kubamracek** [comment]
@swift-ci please smoke test Windows platform

**Pull request merged**
