### PR TITLE
[TensorFlow] Fix LLDB compilation.

### PR DESCRIPTION
**Pull request by eaplatanios**
@rxwei @pschuh this should fix [TF-770](https://bugs.swift.org/browse/TF-770).

### CODE REVIEW

**Review by rxwei — APPROVED** [review]

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Review by pschuh — CHANGES_REQUESTED** [review]
Hi, This drops all our local changes to lldb. I don't think we can merge this pr.

**Comment by rxwei** [comment]
ah right, I forgot about that.

**Review by pschuh — COMMENTED** [review]
lldb should be: 27b495a4292696b48389ed109b0cf232a125e614

**Comment by eaplatanios** [comment]
Thanks @pschuh ! I wasn't aware there were S4TF-specific changes. I updated the commit hash.

**Review by pschuh — APPROVED** [review]

**Comment by pschuh** [comment]
@swift-ci please clean test tensorflow

**Comment by pschuh** [comment]
@swift-ci please clean test tensorflow

**Pull request merged**
