### PR TITLE
[DO NOT MERGE] WIP: Try a slightly different fix for rdar://22898292

### PR DESCRIPTION
**Pull request by rudkx**
Currently fails on `test/Migrator/tuple-arguments.swift`

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by xedin** [comment]
@rudkx The reason why it does is that `subtype` constraint de-prioritizes only valid building in the list, de-prioritization like that could only be applied locally - to type variable on the other side of the `subtype` constraint (like what https://github.com/apple/swift/pull/11747 does), instead of globally - like what happens with the flag.

**Comment by xedin** [comment]
Btw, I did the same thing in https://github.com/apple/swift/pull/11736

**Comment by rudkx** [comment]
It's not the exactly the same though :). This keeps the `BindParam` "penalty" in the same position and moves the new one later. It was an experiment that didn't work out.

**Comment by xedin** [comment]
@rudkx Ah I didn't realize that I re-wrote it, I actually did try it too - separate into two flags and leave bind param at the same spot but move IsSubtypeOf to the back of the tuple... It's the first comment I left there in PR :)

**Pull request closed without merging**
