### PR TITLE
[benchmark] Extract Setup from Benchmarks

### PR DESCRIPTION
**Pull request by palimondo**
This PR should land in tandem with #19910, which changes the measurement method used in `Benchmark_Driver` to run `Benchmark_O` with `--num-iters=1`. That change would appear to increase the reported runtime for benchmarks that have measurable setup overhead, which would be no longer amortized across multiple iterations.

Where appropriate, benchmarks were modified to use `setUpFunction` for costlier workload initialization. In some cases, extracting parts of the workload into constants was a sufficient change that has only minor impact on the first measured sample. `MapReduceClass` and `MapReduceClassSmall` were only two benchmarks, where the changes to extract setup resulted in significantly changed runtimes that do not resemble the original values (compared to the multi-iteration-amortized setup inside run function).

*Running the benchmarks locally, it looks like unmodified benchmark `RecursiveOwnedParameter` is reporting a change (20% improvement). Do we still have an issue with spurious performance changes when adding/removing benchmarks caused by code alignment?*

----

The PR is structured as a series of small, incremental changes with detailed descriptions in the commit messages, it is therefore best [reviewed sequentially by individual commits](https://github.com/apple/swift/pull/20048/commits/4bbb635fcad45fb485641294c84ff33c5723f8e3).

### CODE REVIEW

**Comment by palimondo** [comment]
@eeckstein Please review 🙏

**Comment by palimondo** [comment]
Unrelated to this PR, I'm a bit concerned about the lower precision changes detected by `run_smoke_bench.py`. Granted, I ran it on machine that wasn't super calm -- I had text editor and Google Chrome open… but still the second iteration re-examined some 59 test and last one focused on only 4 "changed" benchmarks:

````
 $ ./run_smoke_bench.py -O ${PREV_SBS} ${SBS}
Testing optimization level -O
    Iteration 1 for /Users/mondo/Developer/swift-source/build/20181025-96ff53d5c7: num samples = 3, running all tests
    Iteration 1 for /Users/mondo/Developer/swift-source/build/20181025-c71d8631dc: num samples = 3, running all tests
    Iteration 2 for /Users/mondo/Developer/swift-source/build/20181025-96ff53d5c7: num samples = 4, re-testing 59 tests
    Iteration 2 for /Users/mondo/Developer/swift-source/build/20181025-c71d8631dc: num samples = 4, re-testing 59 tests
    Iteration 3 for /Users/mondo/Developer/swift-source/build/20181025-96ff53d5c7: num samples = 5, re-testing 19 tests
    Iteration 3 for /Users/mondo/Developer/swift-source/build/20181025-c71d8631dc: num samples = 5, re-testing 19 tests
    Iteration 4 for /Users/mondo/Developer/swift-source/build/20181025-96ff53d5c7: num samples = 6, re-testing 12 tests
    Iteration 4 for /Users/mondo/Developer/swift-source/build/20181025-c71d8631dc: num samples = 6, re-testing 12 tests
    Iteration 5 for /Users/mondo/Developer/swift-source/build/20181025-96ff53d5c7: num samples = 7, re-testing 9 tests
    Iteration 5 for /Users/mondo/Developer/swift-source/build/20181025-c71d8631dc: num samples = 7, re-testing 9 tests
    Iteration 6 for /Users/mondo/Developer/swift-source/build/20181025-96ff53d5c7: num samples = 8, re-testing 7 tests
    Iteration 6 for /Users/mondo/Developer/swift-source/build/20181025-c71d8631dc: num samples = 8, re-testing 7 tests
    Iteration 7 for /Users/mondo/Developer/swift-source/build/20181025-96ff53d5c7: num samples = 9, re-testing 7 tests
    Iteration 7 for /Users/mondo/Developer/swift-source/build/20181025-c71d8631dc: num samples = 9, re-testing 7 tests
    Iteration 8 for /Users/mondo/Developer/swift-source/build/20181025-96ff53d5c7: num samples = 10, re-testing 7 tests
    Iteration 8 for /Users/mondo/Developer/swift-source/build/20181025-c71d8631dc: num samples = 10, re-testing 7 tests
    Iteration 9 for /Users/mondo/Developer/swift-source/build/20181025-96ff53d5c7: num samples = 10, re-testing 7 tests
    Iteration 9 for /Users/mondo/Developer/swift-source/build/20181025-c71d8631dc: num samples = 10, re-testing 7 tests
    Iteration 10 for /Users/mondo/Developer/swift-source/build/20181025-96ff53d5c7: num samples = 10, re-testing 7 tests
    Iteration 10 for /Users/mondo/Developer/swift-source/build/20181025-c71d8631dc: num samples = 10, re-testing 7 tests
Logfiles written to /Users/mondo/Developer/swift-source/build/20181025-96ff53d5c7/result_O and /Users/mondo/Developer/swift-source/build/20181025-c71d8631dc/result_O
````

Here's the comparison report:

`$ ./compare_perf_tests.py --changes-only --single-table --old-file /Users/mondo/Developer/swift-source/build/20181025-c71d863
1dc/result_O --new-file=/Users/mondo/Developer/swift-source/build/20181025-96ff53d5c7/result_O`

TEST                          | OLD   | NEW   | DELTA  | RATIO     
---                           | ---   | ---   | ---    | ---       
**Improvement**               |       |       |        |           
ArrayAppendStrings            | 24426 | 14806 | -39.4% | **1.65x** 
SortSortedStrings             | 3160  | 2270  | -28.2% | **1.39x** 
RandomShuffleLCG2             | 5136  | 4104  | -20.1% | **1.25x** 
RecursiveOwnedParameter       | 2341  | 1890  | -19.3% | **1.24x** 
ArrayInClass                  | 534   | 446   | -16.5% | **1.20x** 
IterateData                   | 4854  | 4164  | -14.2% | **1.17x** 
DictionaryOfObjects           | 9045  | 8286  | -8.4%  | **1.09x (?)** 
DropLastAnySeqCRangeIter      | 21074 | 20050 | -4.9%  | **1.05x** 
**Added**                     |       |       |        |           
DropLastArray                 | 42    | 42    | 42     | —       
DropLastArrayLazy             | 52    | 52    | 52     | —       
DropLastCountableRange        | 17    | 17    | 17     | —       
DropLastCountableRangeLazy    | 17    | 21    | 18     | —       
DropWhileArray                | 202   | 202   | 202    | —       
MapReduceClass2               | 5676  | 5714  | 5691   | —       
MapReduceClassShort2          | 13150 | 13314 | 13220  | —       
PrefixWhileAnySeqCntRange     | 315   | 321   | 317    | —       
PrefixWhileAnySeqCntRangeLazy | 198   | 199   | 198    | —       
PrefixWhileCountableRange     | 57    | 57    | 57     | —       
PrefixWhileCountableRangeLazy | 55    | 55    | 55     | —       
SuffixArray                   | 55    | 55    | 55     | —       
SuffixArrayLazy               | 52    | 52    | 52     | —       
SuffixCountableRange          | 18    | 18    | 18     | —       
SuffixCountableRangeLazy      | 18    | 18    | 18     | —       
**Removed**                   |       |       |        |           
MapReduceClass                | 12381 | 12580 | 12498  | —       
MapReduceClassShort           | 18956 | 19221 | 19054  | —       

I've also compared the logs from the modified (more robust) Benchmark_Driver that included #19910:

`$ ./compare_perf_tests.py --single-table --changes-only --old-file /Users/mondo/Developer/swift-source/build/Ninja-ReleaseAssert/swift-ma
cosx-x86_64/benchmark/logs/master/Benchmark_O-20181025212330-c71d8631dc.log --new-file /Users/mondo/Developer/swift-source/build/Ninja-ReleaseAssert/swift-mac
osx-x86_64/benchmark/logs/i-just-do-eyes/Benchmark_O-20181024114556-96ff53d5c7.log`

TEST                                       | OLD     | NEW     | DELTA  | RATIO     
---                                        | ---     | ---     | ---    | ---       
**Regression**                             |         |         |        |           
DataAppendDataLargeToLarge                 | 262302  | 290075  | +10.6% | **0.90x (?)** 
ObjectiveCBridgeToNSSet                    | 57129   | 62631   | +9.6%  | **0.91x (?)** 
DataAppendBytes                            | 16815   | 18095   | +7.6%  | **0.93x (?)** 
DataAccessBytes                            | 4440    | 4708    | +6.0%  | **0.94x (?)** 
**Improvement**                            |         |         |        |           
ArrayAppendStrings                         | 24633   | 14679   | -40.4% | **1.68x** 
SortSortedStrings                          | 3163    | 2315    | -26.8% | **1.37x** 
RecursiveOwnedParameter                    | 2329    | 1889    | -18.9% | **1.23x** 
SubstringComparable                        | 286     | 232     | -18.9% | **1.23x** 
DataCount                                  | 91      | 75      | -17.6% | **1.21x** 
RandomShuffleLCG2                          | 4944    | 4104    | -17.0% | **1.20x** 
ArrayInClass                               | 532     | 445     | -16.4% | **1.20x** 
IterateData                                | 4544    | 4037    | -11.2% | **1.13x** 
PrefixArray                                | 132     | 119     | -9.8%  | **1.11x** 
Phonebook                                  | 20516   | 18758   | -8.6%  | **1.09x** 
PrefixWhileArrayLazy                       | 168     | 154     | -8.3%  | **1.09x** 
DropFirstArrayLazy                         | 168     | 154     | -8.3%  | **1.09x** 
PrefixArrayLazy                            | 168     | 154     | -8.3%  | **1.09x** 
DropFirstArray                             | 171     | 158     | -7.6%  | **1.08x** 
DictionaryOfObjects                        | 9164    | 8489    | -7.4%  | **1.08x** 
Dictionary                                 | 2050    | 1904    | -7.1%  | **1.08x** 
RandomIntegersLCG                          | 536     | 502     | -6.3%  | **1.07x (?)** 
CStringShortAscii                          | 15778   | 14835   | -6.0%  | **1.06x (?)** 
DictionaryFilter                           | 295405  | 277985  | -5.9%  | **1.06x** 
DictionaryCopy                             | 391730  | 369231  | -5.7%  | **1.06x** 
ObjectiveCBridgeStubToNSDate2              | 3660    | 3467    | -5.3%  | **1.06x (?)** 
ObjectiveCBridgeFromNSArrayAnyObjectForced | 29064   | 27564   | -5.2%  | **1.05x (?)** 
StringEdits                                | 1428698 | 1355276 | -5.1%  | **1.05x (?)** 
**Added**                                  |         |         |        |           
DropLastArray                              | 42      | 42      | 42     | 204800    
DropLastArrayLazy                          | 52      | 52      | 52     | 200704    
DropLastCountableRange                     | 17      | 17      | 17     | 192512    
DropLastCountableRangeLazy                 | 17      | 17      | 17     | 196608    
DropWhileArray                             | 201     | 202     | 201    | 208896    
MapReduceClass2                            | 5565    | 5897    | 5697   | 266240    
MapReduceClassShort2                       | 13510   | 13762   | 13628  | 225280    
PrefixWhileAnySeqCntRange                  | 315     | 319     | 316    | 245760    
PrefixWhileAnySeqCntRangeLazy              | 198     | 198     | 198    | 249856    
PrefixWhileCountableRange                  | 57      | 57      | 57     | 192512    
PrefixWhileCountableRangeLazy              | 54      | 55      | 54     | 196608    
SuffixArray                                | 55      | 55      | 55     | 212992    
SuffixArrayLazy                            | 52      | 52      | 52     | 196608    
SuffixCountableRange                       | 18      | 18      | 18     | 192512    
SuffixCountableRangeLazy                   | 18      | 18      | 18     | 196608    
**Removed**                                |         |         |        |           
MapReduceClass                             | 12350   | 12899   | 12638  | 299008    
MapReduceClassShort                        | 19091   | 19852   | 19513  | 217088    

Once these changes land, I'll look at improving the sensitivity of smoke benchmark using the improvements from #19910.

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Comment by eeckstein** [comment]
@airspeedswift Do those (re-)added benchmark add any value for stdlib benchmarking?

**Comment by palimondo** [comment]
As their original author, I’d like to point out that the goal of expanding the Sequence API benchmark coverage was to demonstrate its interaction with various concrete underlying Sequence and Collection types. It verifies that  the optimizer can deal with all the combinations that can arise from stdlib types. For example, note how it demonstrates the extremely poor performance of the lazy subsystem in the `Onone` mode. (3 orders of magnitude slower!)

**Comment by palimondo** [comment]
Note: The changes reported here by `run_smoke_bech.py` for `ArrayAppendStrings`, `ArrayAppendAsciiSubstring`, `SortSortedStrings`, `IterateData`, `DictionaryOfObjects` are caused by it's use of `--sample-time` that's too short to amortize their setup. I have verified locally that all these benchmarks should report the same runtimes pre/post this PR, if measured with the original benchmarking method with 1s sample time. Your internal script used for long-term performance tracking shouldn't see these as changes, if it is measuring with proper methodology.

**Comment by palimondo** [comment]
Based on the comments by @airspeedswift in [the forums](https://forums.swift.org/t/weird-de-optimization-in-mapreduceclass-benchmark/17135/6), I've appropriated the `MapReduceClass2` for measuring a Swift class and moved the old test to `MapReduceNSDecimalNumber`, while lowering the base workload by a factor of 10. @eeckstein, can you please re-run the benchmark?

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Comment by palimondo** [comment]
@eeckstein are you still waiting for @airspeedswift to chime in, or can we merge this as is?
My experiment with `legacyFactor` depends on some of these and I'd like to show you how promising that one looks. 🤓

**Comment by eeckstein** [comment]
The legacyFactor is a great idea. Does it make sense to implement that first and use that to compensate for these benchmark changes?

**Comment by palimondo** [comment]
No. As I said above, the changes reported here are just artifacts of low `sample-time` in `run_smoke_bench`. Without removing this setup overhead out of measurement my demonstration of `legacyFactor` is reporting bogus changes because of it.

**Comment by palimondo** [comment]
If you restored the the old `Benchmark_Driver run` based measurement as something we could ask @swift-ci to run for us (`full benchmark`? — as a temporary counterpoint to `smoke benchmark`) you would see this PR doesn’t change any reported runtimes.

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by eeckstein** [comment]
For now it seems that the re-added benchmarks are not unstable. I'm merging this. If it turns out that some of those benchmarks are unstable, we can disable them again.

**Pull request merged**
