### PR TITLE
[Dependency Scanning] Respect the Language Option for cross-import overlay enablement

### PR DESCRIPTION
**Pull request by artemcm**
Resolves rdar://130451623

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci test

**Review by cachemeifyoucan — APPROVED** [review]
LGTM

**Review by nkcsgexi — APPROVED** [review]

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
@swift-ci test Windows platform

**Pull request merged**
