### PR TITLE
Make note on `PYTHON_EXECUTABLE` more prominent in WindowsBuild.md

### PR DESCRIPTION
**Pull request by martinboehme**
Make the note on needing to adjust `PYTHON_EXECUTABLE` more prominent, and repeat in in the place where that argument actually needs to be adjusted.

### CODE REVIEW

**Comment by martinboehme** [comment]
@swift-ci Please test

**Review by compnerd — APPROVED** [review]
Seems like a reasonable thing.

@swift-ci please smoke test

**Comment by martinboehme** [comment]
@swift-ci Please test

**Comment by martinboehme** [comment]
@swift-ci Please smoke test.

**Comment by martinboehme** [comment]
@swift-ci Please smoke test Linux

**Comment by martinboehme** [comment]
@swift-ci Please smoke test Linux

**Comment by martinboehme** [comment]
@swift-ci Please smoke test Linux

**Comment by martinboehme** [comment]
@swift-ci Please smoke test

**Pull request merged**
