### PR TITLE
Manual merge of main into next

### PR DESCRIPTION
**Pull request by xymus**
Manual merge to address merge-conflict.

@zoecarver The conflict was on the change with `MAYBE_SUGAR_TYPE`. Can you tell me if the merge looks good to you?

### CODE REVIEW

**Comment by xymus** [comment]
@swift-ci Please test

**Comment by zoecarver** [comment]
Can't speak to the rest of the patch but the changes in `ImportType.cpp` look good to me. Sorry about the merge conflict :) Thanks for fixing.

**Comment by xymus** [comment]
@swift-ci Please test

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Pull request closed without merging**
