### PR TITLE
Implement `np.ndarray` conversion to `Array`, `ShapedArray`, and `Tensor`.

### PR DESCRIPTION
**Pull request by dan-zheng**
Original PR: https://github.com/google/swift/pull/31

The bridging implementation is cost-free: the raw data pointer from
`numpy.ndarray` (via `ndarray.__array_interface__["data"]`) is converted to
`UnsafeBufferPointer`.

The conversion initializers for `Array` and `ShapedArray` are basically
instantaneous.

The conversion initializer for Tensor takes more time since there's no
cost-free bridge to `TF_Tensor` (`TF_AllocateTensor` is called).

### CODE REVIEW

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Review by rxwei — APPROVED** [review]
LGTM

**Pull request merged**
