### PR TITLE
[cmake] Rename COMPONENT_DEPENDS to LLVM_COMPONENT_DEPENDS

### PR DESCRIPTION
**Pull request by gottesmm**

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci Please test OS X platform

**Comment by compnerd** [comment]
Nice, this makes my head hurt less!

**Comment by gottesmm** [comment]
@swift-ci Please smoke test os x

**Comment by gottesmm** [comment]
@compnerd Being explicit is a general good IMO.

**Pull request merged**
