### PR TITLE
🍒[5.7][Distributed] Prevent overloading on async in distributed methods, for wire compat

### PR DESCRIPTION
**Pull request by ktoso**
**Description:** In order to be better for wire compatibility, we actually encode the `YaK` (async throws) distributed thunk based names for the distributed accessible functions. This currently leads to crashes if one does overload on "just asyncness". After discussing if we should allow these overloads (#59831) or ban them (this PR) we came to the conclusion this is better for distributed calls. This PR bans async overloading on distributed methods.
**Risk:** Low, prevents a crash by preventing bad declarations.
**Review by:** @DougGregor 
**Testing:** PR testing
**Original PR:** https://github.com/apple/swift/pull/59880
**Radar:** rdar://96179707

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
This PR does not change the mangling strategy, but just prevents a compile time crash when declaring conflicting methods, as such, it can land a bit later if it has to.

**Comment by ktoso** [comment]
@swift-ci please test Linux

**Comment by ktoso** [comment]
Tho it seems this missed the train -- heh my bad.
Thankfully it does not affect mangling or ABI in any way; it is just a "nicer error message"

**Review by DougGregor — APPROVED** [review]

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
Thanks for review Doug!

**Pull request merged**
