### PR TITLE
[SE-0112] [3.0] Provide default implements for the requirements of CustomNSError

### PR DESCRIPTION
**Pull request by DougGregor**
This PR provides default implementations for the three requirements of `CustomNSError`. The default implementations were actually part of [SE-0112](https://github.com/apple/swift-evolution/blob/master/proposals/0112-nserror-bridging.md), but I forgot to implement them. Further confusing the issue, we thought they had been omitted from the proposal, and therefore required an amendment... which is not the case.

Resolves [rdar://problem/23511842](rdar://problem/23511842).

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@jckarter, please review. Most of the work here is in shifting the default implementation of `NSError._code` from the code synthesis into protocol extensions with a new runtime hook to determine the code for an enum from metadata.

**Comment by jckarter** [comment]
Looks good.

**Comment by DougGregor** [comment]
@tkremenek approved off-line; merging.

**Pull request merged**
