### PR TITLE
 When generating debug info for AllocStackInst, make sure to describe

### PR DESCRIPTION
**Pull request by adrian-prantl**
…the alloca.

This way an llvm.dbg.declare instrinsic is used, which is valid for
the entire lifetime of the alloca.

rdar://problem/36663932

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test platform linux

**Comment by shahmishal** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
Now it's failing with an unrelated error that is also failing on all other pull requests.

@swift-ci smoke test and merge

**Comment by adrian-prantl** [comment]
@swift-ci smoke test and merge

**Comment by adrian-prantl** [comment]
@swift-ci smoke test and merge

**Pull request merged**
