### PR TITLE
utils: attempt to replace custom variables

### PR DESCRIPTION
**Pull request by compnerd**
CMake defaults to using a special <package>_DIR for finding packages.
Prefer this to import the CMake package for LLVM/Clang/Swift rather than
custom paths.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by gwynne** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please build toolchain

**Review by gwynne — APPROVED** [review]
Let's get it done!

**Comment by compnerd** [comment]
This passed tests, smoke tests, and the toolchain build, going to restore this.

**Pull request merged**
