### PR TITLE
 Fix some LValue type checking issues exposed by key paths.

### PR DESCRIPTION
**Pull request by rudkx**
We had an inconsistency in the handling of ConstraintKind::Equal in that we would take
      $T1 Equal $T2
where $T2 was previously bound to a type, and bind the RValue type of $T2's type to $T1.

This can cause problems if we later attempt to bind the LValue version of that type to $T1, which happens as a result of simplifying other constraints.

Instead, defer binding types in Equal constraint where the unbound type variable can be bound to an LValue.

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please test

**Comment by rudkx** [comment]
Test failures due to unrelated change.

**Comment by rudkx** [comment]
@swift-ci Please test

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
We do not appear to have support for PR testing for source compatibility on the swift-4.0-branch.

**Comment by ematejska** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
It looks like there were no source compatibility failures, but there was one unexpected pass (which I think is unrelated to my changes).

It looks like there was some kind of script failure for the test runner:
```
Traceback (most recent call last):
  File "./swift-source-compat-suite/run", line 218, in <module>
    sys.exit(main())
  File "./swift-source-compat-suite/run", line 44, in main
    execute_runner(workspace, args)
  File "./swift-source-compat-suite/run", line 128, in execute_runner
    common.check_execute(runner_command, timeout=9999999)
  File "/Users/buildnode/jenkins/workspace/swift-PR-source-compat-suite/swift-source-compat-suite/common.py", line 321, in check_execute
    raise ExecuteCommandFailure(command, returncode)
common.ExecuteCommandFailure: ExecuteCommandFailure(command="./runner.py --swiftc /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite/build/compat_macos/install/toolchain/usr/bin/swiftc --projects projects.json --swift-version 3 --include-actions 'action.startswith("Build")' --swift-branch swift-4.0-branch --sandbox-profile-xcodebuild ../../../workspace-private/swift-source-compat-suite-sandbox/sandbox_xcodebuild.sb --sandbox-profile-package ../../../workspace-private/swift-source-compat-suite-sandbox/sandbox_package.sb", returncode=1)
Build step 'Execute shell' marked build as failure
```

**Review by DougGregor — APPROVED** [review]
LGTM, thank you!

**Comment by lplarson** [comment]
@rudkx This looks like it finished the run and exited with a UPASS issue. It currently throws an exception on error (UPASS), but doing so makes it look like there's an infrastructure issues, so I plan to change this behavior.

**Pull request merged**
