### PR TITLE
Fix compiler Test Registry to use a StringMap.

### PR DESCRIPTION
**Pull request by atrick**
We have no guarantee that the StringRef passed to the registry lives in the static data segment.

This resulted in memory corruption during compiler bootstrapping, which is particularly difficult to diagnose and reproduce.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci smoke test

**Review by nate-chandler — APPROVED** [review]
Thanks!

**Comment by atrick** [comment]
@nate-chandler  I pushed another closely related commit.

**Comment by atrick** [comment]
@swift-ci smoke test

**Review by nate-chandler — APPROVED** [review]

**Pull request merged**
