### PR TITLE
[WIP] [AutoDiff] Revamp differentiation diagnostics internals.

### PR DESCRIPTION
**Pull request by dan-zheng**
Revamp `DifferentiationInvoker`: simplify the representation and support
indirect differentiation diagnostics.

`DifferentiationInvoker` has two cases:
- `[differentiable]`: differentiation triggered by an attribute. We treat
  this invoker as top-level, with no parent invoker.
- `autodiff_function`: differentiation triggered by an `AutoDiffFunctionInst`.
  This invoker can have a parent (differentiation transform can generated
  new `autodiff_function` instructions).

### CODE REVIEW

**Comment by dan-zheng** [comment]
@rxwei: could you please help take over this?

Some notes:
* `DifferentiationInvoker` stores either a `SILDifferentiable *` pointer or an `AutoDiffFunctionInst *` pointer. Thus, to prevent redundancy, change `ADContext::autoDiffFunctionInsts`  `ADContext::differentiableAttributeInvokers` to just `SmallVector<DifferentiationInvoker *>` if possible.
* This patch should re-enable the indirect differentiation test in `autodiff_diagnostics.swift`. Currently, the test crashes because the `AutoDiffFunctionInst *` pointers stored in the invokers in `ADContext::autoDiffFunctionInsts` are not updated after calls to `promoteToDifferentiableFunction`.
* Consider reverting `BumpPtrAllocator` changes, if using an allocator is not necessary.

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by dan-zheng** [comment]
I accidentally deleted `tensorflow` branch, which closed this PR. That was not intentional, sorry!
It would be nice to protect `tensorflow` branch against deletion to prevent this from happening again.

**Comment by rxwei** [comment]
I had no idea this was created so sorry for the lack of timely responses, but I think refactoring `DifferentiationInvoker` is something we should definitely do!

**Comment by dan-zheng** [comment]
Yeah! I started this patch trying to fix diagnostics but didn't quite fix all bugs/tests yet.

**Comment by dan-zheng** [comment]
Closing due to staleness. It would be nice to revive this sometime.

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
