### PR TITLE
[Backtracing] Fix out-of-process async backtraces.

### PR DESCRIPTION
**Pull request by al45tair**
These weren't working correctly because I made the unwinder call `_swift_task_getCurrent()`, but of course when out-of-process, it calls that in `swift-backtrace`, which is wrong.  Remove that for now.

While I'm here, I also tweaked the formatting slightly, and I noticed that we were saying that all thunks were also system functions, which seemed unnecessary and odd.

Plus there were a couple of extra system functions I added to make the async crash backtraces nicer in friendly mode.

rdar://106363539

### CODE REVIEW

**Review by mikeash — APPROVED** [review]
swift-inspect knows how to get the current task of a remote thread (on Darwin, anyway) if you want to crib from that at some point. It's not pretty.

**Comment by al45tair** [comment]
How odd. The macOS build failed to demangle some of the symbols. (There's some other problem that someone has introduced in the meantime that's broken PR testing also.)

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
Ah, I wonder if the issue is that the macOS CI is running an older macOS that can't demangle async function names. That would make sense as it's clearly demangled the top frame correctly.

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Review by ktoso — APPROVED** [review]
LGTM, would be interesting to be able to get the task like @mikeash mentioned but that's extra / future stuff 👍

**Pull request merged**
