### PR TITLE
build-script: Rerun all lldb Swift tests with DWARFImporter.

### PR DESCRIPTION
**Pull request by adrian-prantl**
rdar://problem/57880844

### CODE REVIEW

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/llvm-project/pull/568
@swift-ci test

**Comment by adrian-prantl** [comment]
@shahmishal This change adds ~100s to the cost of the LLDB test suite. Compared to the time spent compiling, I doubt that this will really show up as a bottleneck, but I thought you should know in the odd case it does.

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/llvm-project/pull/568
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci Please test Linux platform

**Comment by shahmishal** [comment]
@adrian-prantl I don't see the big problem having these test enabled because it's only adding 100s. However, can we make sure these tests are stable?

**Comment by adrian-prantl** [comment]
I don't have any reason to believe that they wouldn't be stable, but I'll monitoring the bots closely to make sure there isn't any flakiness being introduced.

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/llvm-project/pull/568
@swift-ci smoke test

**Comment by adrian-prantl** [comment]
Weird.. it didn't pick up the related PR.

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/llvm-project/pull/568
@swift-ci test

**Pull request merged**
