### PR TITLE
Better use if with braces in memory-sensitive code

### PR DESCRIPTION
**Pull request by danra**
#### What's in this pull request?

Better use if with braces in memory-sensitive code

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by gottesmm** [comment]
I understand what you are trying to do here, but we do not have a policy against ifs without braces. Until we do that, I feel that this change is just noise. If you think that we should do this, feel free to send an email to swift-dev requesting the change.

**Comment by danra** [comment]
Following the "goto fail" bug, I believe that at least security/memory
sensitive code should use braces,
However, I'm not passionate enough about this fix to pursue it if you feel
differently. :)

**Comment by gottesmm** [comment]
We have the -Wunreachable-code warning enabled, so we should never hit that issue.

Michael

**Comment by danra** [comment]
That's true specifically for goto fail, but not for e.g.

if (address != nullptr)
  ++address;
  ++address;

**Comment by danra** [comment]
Also: Doesn't it make sense to borrow swift's enforced convention of always braced ifs, which I guess was debated seriously before decided on, in Swift's source code? :)

**Comment by gparker42** [comment]
Changes to the style convention in Swift's implementation should be proposed on swift-dev. 

The style convention in Swift's implementation is closely based on the llvm and clang style. Your argument that the Swift convention is different might work.

**Pull request closed without merging**
