### PR TITLE
windows: convert swift-crypto to static linking

### PR DESCRIPTION
**Pull request by compnerd**
We should be able to use static linking here without negatively impacting code size.
___

Cherry pick of #63393.

### CODE REVIEW

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-installer-scripts#173

@swift-ci please build toolchain windows platform

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @airspeedswift @DougGregor @shahmishal - this has been here for a while, it is a pretty straightforward change and only impacts windows.

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
CC: @tkremenek

**Comment by tkremenek** [comment]
@compnerd, thanks for CC'ing me.  I'm missing some context behind the change.  What does it do?

**Comment by compnerd** [comment]
@tkremenek it just changes the Windows build to use static linking for the SwiftCrypto library for use in Swift PM.  It's a small size and distribution win.  This is a build only change that is limited to windows.  There is the associated change for swift-installer-scripts but is quite self contained.

**Pull request merged**
