### PR TITLE
[Runtime] Enable mangled type name roundtrip checking by default.

### PR DESCRIPTION
**Pull request by DougGregor**
For an assertions-enabled runtime, enable the round-trip checking for
mangled type names <-> type metadata on metadata completion. This
checking was off-by-default due to various bugs, but could be enabled
by SWIFT_ENABLE_MANGLED_NAME_VERIFICATION. Turn it on always now.

Fixes rdar://problem/37551850.

### CODE REVIEW

**Comment by DougGregor** [comment]
https://github.com/apple/swift/pull/19571 eliminates the last of the issues exposed by our testsuite, so I'll wait until that lands before testing this one.

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please benchmark

**Comment by slavapestov** [comment]
Yay!

**Comment by DougGregor** [comment]
@swift-ci please smoke test macOS

**Comment by mikeash** [comment]
So much yay!

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
The last three commits fix all but 2 of the failures that show up when promoting the round-trip warning to an error. The two remaining failures are `test/Interpreter/objc_extensions.swift' and `test/Prototypes/CollectionTransformers.swift`.

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
