### PR TITLE
drop Comparable requirement on Collection.Index (in Progress)

### PR DESCRIPTION
**Pull request by dabrahams**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please test

**Comment by gribozavr** [comment]
Please also drop Comparable from MinimalIndex.

**Comment by natecook1000** [comment]
I was just looking at the comments for `_failEarlyRangeCheck` and thinking they weren't correct. This is not the fix I was planning! 😂

**Comment by dabrahams** [comment]
@swift-ci Please test

**Comment by dabrahams** [comment]
@natecook1000 This is just the hard, Dave-fighting-the-compiler to make everything build again, part of the change.  It’s going to need a complete comment review when it’s done.

**Comment by dabrahams** [comment]
@swift-ci Please test

**Comment by dabrahams** [comment]
We decided not to do this.  The rationale is in [this thread](https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20160704/023494.html)

**Pull request closed without merging**
