### PR TITLE
[CopyPropagation] Hoist end_borrows over users of copies.

### PR DESCRIPTION
**Pull request by nate-chandler**
Enable hoisting end_borrow instructions in a few more cases.  In the following
`%borrow = begin_borrow %val` for some `%val` and `%copy = copy_value %borrow`.

(1) Hoist over and rewrite copies of the borrow.
```
copy_value %borrow
end_borrow %borrow
```
->
```
end_borrow %borrow
copy_value %val
```

(2) Hoist over applies that use the copy but don't use the borrow.
```
apply %fn(..., %copy, ...) //here neither %borrow nor a derived value into which ownership was forwarded appears in the ellipses
end_borrow %borrow
```

(3) Hoist over borrows of the copy:
```
begin_borrow %copy
end_borrow %borrow
```

(4) Hoist over copies of the copy:
```
copy_value %copy
end_borrow %borrow
```

Thanks to (1), some copy_value instructions are rewritten.  Update CopyPropagation to handle this properly by waiting to examine copy_value instructions until after ShrinkBorrowScope runs.

### CODE REVIEW

**Review by atrick — APPROVED** [review]
LGTM thanks!

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Pull request merged**
