### PR TITLE
[5.1] Fix bounds check in bridged ASCII String comparison 5.1

### PR DESCRIPTION
**Pull request by Catfish-Man**
Cherry-pick of https://github.com/apple/swift/pull/24457

Fixes rdar://problem/50407214

### CODE REVIEW

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@Catfish-Man - do I detect a reference to Dollhouse?  if so, amazing!

**Comment by Catfish-Man** [comment]
Indeed! Though I honestly forget how the pun was supposed to work semantically, it's been long enough since I made the original branch 😅

**Comment by Catfish-Man** [comment]
Something about NSString's indexes being a two byte stride or something like that

**Comment by Catfish-Man** [comment]
Branch names don't go in the title, silly github

**Review by airspeedswift — APPROVED** [review]

**Pull request merged**
