### PR TITLE
[5.7] FeatureFlags: rename feature flag enable-bare-slash-regex. NFC

### PR DESCRIPTION
**Pull request by nkcsgexi**
rdar://92703659

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Review by airspeedswift — APPROVED** [review]

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Comment by nkcsgexi** [comment]
@swift-ci Please clean test OS X platform

**Pull request merged**
