### PR TITLE
(un-revert) Remove apparently obsolete builtin functions (#20947)

### PR DESCRIPTION
**Pull request by xedin**
* Remove apparently obsolete builtin functions.

- Remove s_to_u_checked_conversion and u_to_s_checked_conversion functions from builtin AST parsing, SIL/IR generation and from SIL optimisations.

* Remove apparently obsolete builtin functions - unit tests.

- Remove unit tests for SIL transformations relating to s_to_u_checked_conversion and u_to_s_checked_conversion builtin functions.

**Has been reverted, but now getting restored because it's unrelated to watchOS bot problems**

Fixes <rdar://problem/46430442>

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by stephentyrone** [comment]
LGTM.

**Comment by xedin** [comment]
@stephentyrone Do we want this for 5.0 branch as well?

**Pull request merged**
