### PR TITLE
Limit `@_moveOnly` to structs and enums

### PR DESCRIPTION
**Pull request by kavon**
Per the existing proposal, we're not supporting move-only reference types right now.

This PR makes it illegal to put the attribute on a reference type, unless if you additionally provide the flag `-enable-experimental-feature MoveOnlyClasses`.

This extra flag is really there only for internal development purposes, because there are a number of existing tests that rely on such types in a very limited way (convenient leaf type).

resolves rdar://102777947

### CODE REVIEW

**Comment by kavon** [comment]
@swift-ci please test

**Comment by kavon** [comment]
@swift-ci please test and merge

**Comment by kavon** [comment]
@swift-ci please test and merge

**Review by gottesmm — COMMENTED** [review]
Thanks! LGTM

**Pull request merged**
