### PR TITLE
small sentence structuring errors

### PR DESCRIPTION
**Pull request by KrishMunot**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [x] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by tkremenek** [comment]
Replacing "surname" with "last name" is not technically correct for all cultures.  While this change is well-intended, I don't see the changes as a clear improvement.

**Comment by KrishMunot** [comment]
@tkremenek That might be true. However, lastname is the most preferred and commonly used parameter online for name fields.

**Comment by ephemer** [comment]
"lastname" isn't a word in English. Also removing '`the`' in the first line you changed makes the sentence less clear in my opinion..

**Comment by KrishMunot** [comment]
"lastname" could also be changed to "last name" if that is something which you may consider. The omission of 'the' looks good to me, however, either way it sounds fine. 
So, we can have the extra white space omitted.

**Comment by jrose-apple** [comment]
I'd say both of these sentences are correct as is.

**Pull request closed without merging**
