### PR TITLE
Spelling sema

### PR DESCRIPTION
**Pull request by jsoref**
This fixes some misspellings in Swift documentation, it is split per https://github.com/apple/swift/pull/42421#issuecomment-1101092698

There's a bit of interaction between Sema and AST, so I've pulled a couple of changes out of the AST PR and into here.

### CODE REVIEW

**Comment by tshortli** [comment]
@swift-ci please test

**Comment by AnthonyLatsis** [comment]
I wish CI could some day do these static checks for us.

**Comment by jsoref** [comment]
Which "static checks"?

The tooling I'm using is available as a GitHub workflow 🙂.

**Comment by jsoref** [comment]
Well, Jenkins can definitely respond to PRs and jobs/pipelines.

Can't tell if there's a policy your system has to reduce risk without first having some human decide a PR isn't malicious/spammy. (GitHub has recently added more bits to their environment because of such problems.)

**Comment by tshortli** [comment]
Thank you, these changes all look reasonable to me. @CodaFi do you want to take a look as well?

**Review by tshortli — APPROVED** [review]

**Review by xedin — APPROVED** [review]

**Review by CodaFi — APPROVED** [review]

**Comment by AnthonyLatsis** [comment]
> Well, Jenkins can definitely respond to PRs and jobs/pipelines.

It can be done of course. Though I doubt the community or us contributors have much of a say in this kind of stuff.

**Pull request merged**
