### PR TITLE
Add top-level request for TBDGen

### PR DESCRIPTION
**Pull request by hamishknight**
Introduce `GenerateTBDRequest` which returns the TBD interface file along with a set of public symbols.

### CODE REVIEW

**Comment by hamishknight** [comment]
https://github.com/apple/llvm-project/pull/785

@swift-ci please test

**Comment by hamishknight** [comment]
https://github.com/apple/llvm-project/pull/785

@swift-ci please test

**Review by DougGregor — APPROVED** [review]
This is awesome!

**Comment by CodaFi** [comment]
Only comment is that we should make the TBDGen entrypoint more functional.  But that should absolutely be done in a follow-up.

**Comment by nkcsgexi** [comment]
Thank you for requestifying TBD gen!

**Pull request merged**
