### PR TITLE
[ClangImporter] Import builtins returning size_t as returning Int.

### PR DESCRIPTION
**Pull request by jrose-apple**
...which is consistent with other library functions return size_t. But don't break compatibility with Swift 3.

("Builtins" are functions that Clang has, well, built-in knowledge about, and whose declarations can therefore be produced directly in the compiler. This bypassed some of our checking for special typedefs like size_t. We discovered this when 'wcslen' got added as a new built-in in the Swift 4 timeframe.)

rdar://problem/30545505

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
Whoops. Glibc doesn't have strlcpy, strlcat, or wcslen—and the last is one of the things specifically being tested.

**Review by DougGregor — APPROVED** [review]
Looks good (excepting the glibc issue)

**Comment by jrose-apple** [comment]
@swift-ci Please test Linux

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test macOS

**Pull request merged**
