### PR TITLE
[Distributed] clean up some of the initialization code to be more robust

### PR DESCRIPTION
**Pull request by kavon**

### CODE REVIEW

**Comment by kavon** [comment]
@swift-ci please build toolchain

**Comment by ktoso** [comment]
Toolchain build broken with:

```
Undefined symbols for architecture arm64:
  "_swift_get_time", referenced from:
      swift_task_enqueueGlobalWithDeadlineImpl(long long, long long, long long, long long, int, swift::Job*) in GlobalExecutor.cpp.o
ld: symbol(s) not found for architecture arm64
```

**Comment by ktoso** [comment]
Might resolve rdar://92142457

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
@swift-ci please smoke test and merge

**Review by ktoso — APPROVED** [review]

**Comment by ktoso** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
