### PR TITLE
Use the right key for the image thumbnail dictionaries in the URL resources struct

### PR DESCRIPTION
**Pull request by parkera**
The swift importer made a bit of a mess out of the string key here; the real one we want to use is URLThumbnailDictionaryItem.

Fixes rdar://27556178

### CODE REVIEW

**Comment by parkera** [comment]
@swift-ci please test

**Comment by parkera** [comment]
@swift-ci please test

**Comment by jrose-apple** [comment]
Just to be clear, we're considering this not a source-breaking change because the old code never worked? It still seems like it could break someone's compilation.

**Comment by parkera** [comment]
Which "this" are you talking about? Changing the type of the property in the AppKit/UIKit extensions of  the URL resources struct or deleting the errant enum?

**Comment by jrose-apple** [comment]
Both, really. Someone could have been using an explicit type (wrong as it was) and now it won't compile. Maybe leaving behind an unavailable/renamed typealias would help?

**Comment by jrose-apple** [comment]
(It's still not strictly source-compatible, though.)

**Comment by parkera** [comment]
I filed another bug for Foundation to figure out the source compat story so I can close out this important fix. 30578582

**Comment by parkera** [comment]
@swift-ci test and merge

**Comment by jrose-apple** [comment]
Something funky happened here. I'll restart.

Note that we're past our final branch for Swift 3.1. Should this get cherry-picked there as well?

@swift-ci Please test

**Comment by parkera** [comment]
We don't need this for Swift 3.1.

**Pull request merged**
