### PR TITLE
[Build] Repair the build for non-static-only static stdlib builds

### PR DESCRIPTION
**Pull request by kateinoigakukun**
When SWIFT_BUILD_STATIC_STDLIB=ON, SWIFT_BUILD_DYNAMIC_STDLIB=OFF, and the sdk being built is not a static-only (e.g. WASI), the build fails due to duplicate custom command rules against the same output path. In the case of WASI, the static archive should be copied into lib/swift by the first lipo target, and then the second lipo target should copy it into lib/swift_static.

```
CMake Error at cmake/modules/SwiftAddCustomCommandTarget.cmake:144 (add_custom_command):
  Attempt to add a custom rule to output

    /home/build-user/build/buildbot_linux/wasmstdlib-linux-x86_64/lib/swift_static/wasi/libswiftCore.a.rule

  which already has a custom rule.
Call Stack (most recent call first):
  stdlib/cmake/modules/AddSwiftStdlib.cmake:673 (add_custom_command_target)
  stdlib/cmake/modules/AddSwiftStdlib.cmake:2657 (_add_swift_lipo_target)
  stdlib/public/core/CMakeLists.txt:401 (add_swift_target_library)
```
https://ci.swift.org/job/oss-swift-pr-test-crosscompile-wasm-ubuntu-20_04/585/console

### CODE REVIEW

**Comment by kateinoigakukun** [comment]
@swift-ci test WebAssembly

**Comment by kateinoigakukun** [comment]
@swift-ci smoke test

**Review by al45tair — APPROVED** [review]

**Comment by al45tair** [comment]
Thanks for this; I think this also broke the embedded SDK :-(

**Comment by kateinoigakukun** [comment]
Wasm CI job failed but the CMake issue itself seems resolved
```
/home/build-user/swift-nightly-install/usr/bin/swiftc: symbol lookup error: /home/build-user/build/buildbot_linux/earlyswiftdriver-linux-x86_64/release/dependencies/swift-tools-support-core/lib/libTSCBasic.so: undefined symbol: $s8Dispatch0A5QueueC5async5group3qos5flags7executeyAA0A5GroupCSg_AA0A3QoSVAA0A13WorkItemFlagsVyyXBtF
```

**Comment by al45tair** [comment]
Let's just merge this; it fixes a problem on macOS (specifically the embedded build) that for some reason I didn't spot before (I probably ran a smoke test instead of a full test, which was a mistake).

**Pull request merged**
