### PR TITLE
build: guard against builds where SwiftSyntax may not be enabled

### PR DESCRIPTION
**Pull request by compnerd**
Fix the build after #69440

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by hamishknight** [comment]
Thanks!

**Comment by hamishknight** [comment]
@swift-ci please smoke test Linux

**Review by bnbarham — APPROVED** [review]

**Comment by hamishknight** [comment]
@swift-ci please smoke test macOS

**Pull request merged**
