### PR TITLE
Propagate '-application-extension' to module interface loader sub-invocations.

### PR DESCRIPTION
**Pull request by artemcm**
This flag restricts availability of certain symbols to ensure the code cannot use declarations that are explicitly unavalable to extensions. This restriction should be passed down to dependency modules also.

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci test

**Review by nkcsgexi — APPROVED** [review]
Nice catch!

**Comment by DougGregor** [comment]
https://github.com/apple/swift-format/pull/424

@swift-ci please smoke test

**Comment by artemcm** [comment]
@swift-ci please smoke test macOS platform

**Comment by artemcm** [comment]
@swift-ci please test macOS platform

**Pull request merged**
