### PR TITLE
Revert "[cxx-interop] Support class templates containing typedefs."

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/swift#34557

This seems to have caused a regression on Windows: https://ci-external.swift.org/job/oss-swift-windows-x86_64-vs2019/3362/consoleText

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
CC: @zoecarver @hlopko

**Review by zoecarver — APPROVED** [review]
@compnerd sorry about that. I will try to re-land later today. Thanks for reverting. 

When I ran `swift-ci smoke test and merge` it didn't trigger the Windows bots. Is that intentional or a bug?

**Comment by compnerd** [comment]
@zoecarver that's a bug, @shahmishal might be able to identify why exactly it failed to trigger in the particular case.

**Comment by shahmishal** [comment]
This is known issue because windows is part of different infrastructure (Swift Community-Hosted CI vs Swift CI).

**Comment by zoecarver** [comment]
Good to know. In the future, I'll just do a smoke test and merge manually then.

**Pull request merged**
