### PR TITLE
Fix dependent protocol conformance records

### PR DESCRIPTION
**Pull request by slavapestov**
Protocol conformance records for dependent conformances (ie, requiring instantiation) directly referenced the witness table pattern and not the accessor function. This is incorrect. To prevent the problem from happening again, give witness table patterns a different mangling with private linkage. Also, change the runtime use witness table accessors rather than direct references to witness tables in the Foundation module in a couple of spots. These conformances are resilient and also require instantiation.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Review by DougGregor — APPROVED** [review]
LGTM! Thanks for re-using `isDependentConformance`.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Pull request merged**
