### PR TITLE
[ConstraintSystem] Add an option to disable the constraint solver per…

### PR DESCRIPTION
**Pull request by rudkx**
…f hacks.

This is helpful in experimenting with constraint solver changes that
might help us remove some of these unsound options. It's not ever mean
to be enabled, but if we're able to remove the things guarded by the
option we can eventually remove the option.

### CODE REVIEW

**Comment by rudkx** [comment]
@xedin I'm probably missing some things here...anything else you can think of?

**Review by xedin — COMMENTED** [review]
- In `optimizeConstraints` whole block related to `LinkedExprCollector` (which calls `LinkedExprAnalyzer` inside) - 
https://github.com/apple/swift/blob/master/lib/Sema/CSGen.cpp#L3543L3552

- `pruneOverloadSet` closure in `solveForDisjunction`.

And I think that's pretty much it :)

**Comment by rudkx** [comment]
@xedin I am skipping all of `optimizeConstraints` with these changes (if the command-line option is used). I left `pruneOverloadSet` in because it's really not a hack per se. I was looking at reimplementing that differently last week but that didn't work out.

**Comment by rudkx** [comment]
@xedin ...having said that, I don't think `pruneOverloadSet` can actually do anything with `optimizeConstraints` disabled, so eventually I may just remove it if I can remove `optimizeConstraints`.

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by xedin** [comment]
Ah right, sorry, If the whole `optimizeConstraints` if skipped, that's good!

**Pull request merged**
