### PR TITLE
Mangle imported declarations using their C names

### PR DESCRIPTION
**Pull request by jrose-apple**
Reviving #8871 for Swift 5. Using C names for imported declarations makes them consistent no matter what shenanigans are pulled by the importer, particularly NS_ENUM vs. NS_OPTIONS and NS_SWIFT_NAME. (Up until now we've just been using the Swift 4 name to mangle everything, which *sorta* works but doesn't scale.)

Still to improve:

- [x] The 'NSErrorDomain' API note nearly works with this, but the synthesized error struct is still mangled as a Swift declaration, which means it's not rename-stable. Fortunately, these are rare to appear at API boundaries. *Now handled in #13841.*

- [ ] For NS_STRING_ENUM: when this is applied, a typedef is imported as a unique struct, but without it it's just a typealias for the underlying type. I don't know if there's a good answer for this; we might just have to stick with Swift 3/4's "ignore an API that doesn't match up" practice. *Yep, I think that's the best we can do.*

- [x] Synthesized conformances have a module mangled into the witness table symbol. This isn't critical because that symbol is linkonce_odr, but we should still clean it up.

~This probably still needs more tests, especially around "type reconstruction" (going from mangled names back to AST types, as used by LLDB and SourceKit).~

rdar://problem/24688918

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by jrose-apple** [comment]
Oh, this is probably going to mess with corelibs-foundation, huh.

**Comment by jrose-apple** [comment]
Passed Linux tests --> maybe not. It *will* need a rebase on top of Pavel's mangling work, though.

**Comment by jrose-apple** [comment]
Rebased! @swift-ci Please test

**Comment by jrose-apple** [comment]
I think this is ready for review. I'll tackle the NS_ERROR_ENUM problem in a follow-up PR, and I'll try to think a bit more about the versioned NS_TYPED_ENUM problem.

- @nkcsgexi, can you review the type reconstruction parts?
- @eeckstein, can you review the mangling parts?
- @DougGregor, can you review the ClangImporter part? (small)
- @slavapestov, you just seem like generally a good person to look at this

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Review by eeckstein — APPROVED** [review]
lgtm!

**Review by nkcsgexi — APPROVED** [review]
The type reconstruction part LGTM!

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
Hm. The Linux one is just a test mistake, but the Apple platforms one is a timeout. Nothing here should make things take significantly longer, so let's try again.

@swift-ci Please test macOS

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test compiler performance

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test compiler performance

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test compiler performance

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
Whew!

**Pull request merged**
