### PR TITLE
[SILProfiler] Do not set up a profiler for a function twice

### PR DESCRIPTION
**Pull request by vedantk**
rdar://58861159

### CODE REVIEW

**Comment by vedantk** [comment]
@swift-ci smoke test and merge

**Comment by theblixguy** [comment]
Seems like this fixes https://bugs.swift.org/browse/SR-12045 

Could you mark it as resolved once this is merged?

**Comment by vedantk** [comment]
Hi @theblixguy, I've sent a PR for the 5.2 branch as well. I'll update SR-12045 once that PR is resolved.

**Comment by theblixguy** [comment]
Sounds good!

**Pull request merged**
