### PR TITLE
[Reflection] NFC: Enable building after clang r331013

### PR DESCRIPTION
**Pull request by davezarzycki**

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by bob-wilson** [comment]
This appears to have broken the master-next bots:
https://ci.swift.org/view/swift-master-next/job/oss-swift-incremental-RA-osx-master-next/

**Comment by davezarzycki** [comment]
Hi @bob-wilson – Weird. This implies that the host compiler is top-of-tree-ish (at least enough to be considered "clang 7.0"). Is that correct? How do I find out what the last merge of clang into the host compiler is? Does it include r331013?

**Comment by davezarzycki** [comment]
I speculatively merged #16221. Please let me know if that doesn't fix it.

**Comment by bob-wilson** [comment]
Yes, the master-next branch builds with top-of-trunk Clang/LLVM. We build the runtime with the copy of Clang that gets built with Swift, so that will also be top-of-trunk.

**Comment by davezarzycki** [comment]
Can you confirm that `__APPLE_CC__` equals the underlying clang/llvm version?

**Comment by davezarzycki** [comment]
So what's the right way to detect the underlying llvm/clang version then?

**Comment by bob-wilson** [comment]
I was just asking @jrose-apple about that. It sounds like any sort of version check is not going to work well. Jordan suggested a \_\_has\_feature check, but the change in r331013 looks to me like a bug fix. If that's really the case, it seems like there ought to be a way to write that code so that it works with both old and new compilers.

**Comment by bob-wilson** [comment]
I'll try some things....

**Comment by bob-wilson** [comment]
It doesn't look like Clang (at least the versions we care about) requires "template" in those cases. See https://github.com/apple/swift/pull/16372

**Pull request merged**
