### PR TITLE
Replace custom `Deque` implementation with swift-collection `Deque`

### PR DESCRIPTION
**Pull request by FranzBusch**
# Motivation
For AsyncStream we created a custom internal Deque implementation to use for the buffering. This implementation was relatively bare-bones compared to the one in swift-collections. Furthermore, it lacked some methods that we need to implement the new `AsyncStream` APIs that support producer backpressure.

# Modification
This PR copies over the Deque implementation of swift-collections and makes it internal and non-inlinable.

# Result
We now have a fully functional Deque.

### CODE REVIEW

**Comment by FranzBusch** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
LGTM about getting the swift-collection's deque.

This keeps it internal so that's fine, but maybe prepare a pitch as well to make it part of stdlib? It is used all over the place being copied around 🤔 WDYT @lorentey ?

If we intend to keep this copy around like this though, would it be good to automate copying the files a bit so it is easier to keep the two impls in sync? Or working towards removing the one in swift-collections in favor or a public pitched one from the stdlib.

**Comment by FranzBusch** [comment]
Yeah it would be great if we could get `Deque` officially moved into the stdlib. It is the one type that I consistently reach for in every `AsyncSequence` implementation.

**Comment by ktoso** [comment]
Up to @lorentey to give the thumbs up or down here, but yeah this type would definitely be useful in concurrency library even for our internals

**Comment by lorentey** [comment]
Yes, this is clearly an interim solution. Manually vendoring these implementations into every single ABI stable OS component is not going to be a good approach in the long term.

The big blocker for adding `Deque` as a public stdlib type is that there is a really good chance that Swift's incoming ownership features will render the implementation obsolete in a few months/years -- so we'd probably regret if we baked its current layout into the ABI right now.

**Review by lorentey — APPROVED** [review]
I recommend adding prominent comments at the top of source files pointing to their upstream location, to try prevent things from diverging too much from upstream.

In case the _Concurrency module ends up needing to make substantial changes/fixes to this code, those ought to be propagated back into the swift-collections package.

**Review by ktoso — APPROVED** [review]
Thanks for the detailed thoughts @lorentey! Looks good then.

Maybe a README or something in the Deque directory pointing at https://github.com/apple/swift-collections/tree/main/Sources/DequeModule could do it as well?

**Comment by FranzBusch** [comment]
@swift-ci please smoke test

**Comment by FranzBusch** [comment]
@swift-ci please test

**Comment by FranzBusch** [comment]
@swift-ci please smoke test

**Comment by FranzBusch** [comment]
@swift-ci please test

**Comment by FranzBusch** [comment]
@swift-ci please test macos

**Comment by FranzBusch** [comment]
@swift-ci please smoke test

**Comment by FranzBusch** [comment]
@swift-ci please test

**Comment by FranzBusch** [comment]
@swift-ci please smoke test

**Comment by FranzBusch** [comment]
@swift-ci please test macos

**Pull request merged**
