### PR TITLE
Fix several bugs in dynamic casts

### PR DESCRIPTION
**Pull request by rjmccall**
#### What's in this pull request?

Fix the cast optimizer to handle CF/NS bridging correctly, and fix the dynamic cast runtime to handle class + enum casts to AnyHashable correctly.

This should unblock @jrose-apple's fix for [SR-2388](https://bugs.swift.org/browse/SR-2388)

rdar://27942352

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

A smoke test on macOS does the following:
1. Builds the compiler incrementally.
2. Builds the standard library only for macOS. Simulator standard libraries and
   device standard libraries are not built.
3. lldb is not built.
4. The test and validation-test targets are run only for macOS. The optimized
   version of these tests are not run.

A smoke test on Linux does the following:
1. Builds the compiler incrementally.
2. Builds the standard library incrementally.
3. lldb is built incrementally.
4. The swift test and validation-test targets are run. The optimized version of these
   tests are not run.
5. lldb is tested.

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please test and merge.

**Comment by rjmccall** [comment]
@jckarter Would you mind reviewing this?

**Comment by rjmccall** [comment]
Pushed fix for broken regression test.

@swift-ci Please clean test Linux.
@swift-ci Please test Mac OS.

**Comment by rjmccall** [comment]
I think that probably was too clever by half.

@swift-ci Please test OS X.

**Comment by rjmccall** [comment]
Or maybe CI is just down / slow.

**Comment by gparker42** [comment]
@swift-ci please test OS X platform

**Comment by shahmishal** [comment]
@swift-ci Please clean test Linux.

**Comment by shahmishal** [comment]
@swift-ci Please clean test Linux.

**Comment by gparker42** [comment]
Test failure looks real. While building XCTest:
SIL verification failed: unchecked_ref_cast requires a heap object reference type: SILType::canRefCast(AI->getOperand()->getType(), AI->getType(), AI->getModule())

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Comment by rjmccall** [comment]
Linux CI busted?

**Comment by shahmishal** [comment]
@swift-ci Please test Linux

**Comment by shahmishal** [comment]
macOS failure is due to
```
21:26:36 Failing Tests (1):
21:26:36     Swift(macosx-x86_64) :: SILOptimizer/cast_folding_objc_generics.swift
21:26:36 
21:26:36   Expected Passes    : 8423
21:26:36   Expected Failures  : 12
21:26:36   Unsupported Tests  : 91
21:26:36   Unexpected Failures: 1
```
Linux failure was due to timeout 3mins, this was config issue. I have fixed this now, please wait for new build to completed. [Build](https://ci.swift.org/job/swift-PR-Linux/3570/)

**Comment by rjmccall** [comment]
Test failure was a failure to revert a test change that had been necessary in a prior iteration of the patch.  Hazards of developing with a limited time budget.

@swift-ci Please test.

**Comment by DougGregor** [comment]
These changes LGTM.

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by rjmccall** [comment]
This has passed a full test, but that apparently no longer satisfies the smoke test requirement.  Can we get an admin to merge this, please?

**Comment by slavapestov** [comment]
Or we can just run the smoke test :)

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Pull request merged**
