### PR TITLE
TypeChecker: consolidate func & subscript signature validation

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
cc @slavapestov

### CODE REVIEW

**Comment by AnthonyLatsis** [comment]
Let me see if I can resolve this without a clean build..

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by AnthonyLatsis** [comment]
A clang conflict that happened because of the merge? I guess I must do a clean build & rebase after all.

**Comment by AnthonyLatsis** [comment]
Excuse the delay, it took a while to update everything. I also merged in the new logic for opaque return types, so this *will* create a conflict with [#22072](https://github.com/apple/swift/pull/22072). [Here](https://github.com/apple/swift/pull/22072/files#diff-915d07a1722823b4187b5085453248f1) is the relevant diff.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by AnthonyLatsis** [comment]
Hmm. Both of these fails don't seem related. Although looking at the logs I can barely tell what happened to Source Compat at such an early stage – unless I'm misinterpreting, it didn't even start building the stdlib. Any ideas?

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Comment by slavapestov** [comment]
Thank you!

**Pull request merged**
