### PR TITLE
[python interop][TF-361] improve error message in dynamicallyCall

### PR DESCRIPTION
**Pull request by realdoug**
This small change resolves [TF-361](https://bugs.swift.org/projects/TF/issues/TF-361) by improving the error output produced from a Python exception.  My first contribution to swift4tf.

Please see my comment [here](https://bugs.swift.org/browse/TF-361?focusedCommentId=44878&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-44878) on the issue.  My understanding of the bug is that it requires "option A" -- just relating to the error message and not to changing the failure mode altogether.  And I think this change is a small incremental improvement that is worth making in anyway.

### CODE REVIEW

**Comment by dan-zheng** [comment]
Could you please add a test case based on [TF-361](https://bugs.swift.org/browse/TF-361)?

Here's what the reproducer looks like in Python:
```console
$ python
Python 2.7.10 (default, Aug 17 2018, 19:45:58)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> a = object()
>>> a
<object object at 0x1059bf090>
>>> a.hmm = a
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'object' object has no attribute 'hmm'
```

However, currently in Swift, it seems the invalid member access doesn't produce a crash.
```swift
import Python
let x = Python.object()
x.hmm = x // doesn't crash
// print(x) // only crashes when calling another Python function
```

It seems to me the right fix would be to "catch the invalid member access right after it happens" instead of "checking for error state in `dynamicallyCall`". Does this make sense to you?

**Comment by realdoug** [comment]
@dan-zheng yep, it does.  Looks like the bug was that the return type of ```PyObject_SetAttrString``` needed to explicitly be 32 bit to match the rest.  I also kept the previous change since it still seems like an improvement, but can set it back to generic fatalError if you prefer.

**Review by dan-zheng — APPROVED** [review]
Nice catch about the `Int32` return type! Thanks for adding a test.

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Review by rxwei — APPROVED** [review]
thanks!

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Pull request merged**
