### PR TITLE
[Parse] Split ParseSIL out into its own library.

### PR DESCRIPTION
**Pull request by jrose-apple**
...finally breaking the dependency of Parse on Sema.

There are still some unfortunate dependencies here – @nkcsgexi's working on getting *AST* not dependent on Sema – but this is a step forward.  It is a little strange that parseIntoSourceFile is in ParseSIL, and therefore that that's still a dependency for anyone trying to, well, parse. However, nearly all clients that parse want to type-check as well, and that requires Sema, Serialization, and the ClangImporter... and Serialization and SIL currently require each other as well (another circular dependency). So it's not actively causing us trouble right now.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Review by slavapestov — APPROVED** [review]

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by jrose-apple** [comment]
Almost there!

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Pull request merged**
