### PR TITLE
Add --fast flag to utils/update-checkout

### PR DESCRIPTION
**Pull request by takebayashi**
To build snapshots, it is not necessary to fetch all history.
`--clone --fast` flags make `utils/update-checkout` fetch latest revisions only.

### CODE REVIEW

**Comment by gribozavr** [comment]
I think this is a good addition, but 'fast' does not describe what the flag does.  "Clone sources in fast way" -- "of course I want my sources fast, why isn't this the default".

Can you think of a better way to name the flag so that the implications are clear?

**Comment by dduan** [comment]
It's safe to assume users of this script understand what `--depth=1` means (or at least can guess/google it), I would include it in the help text.

@gribozavr beat me to it. The flag name should be clearer. My $0.02:

* --shallow
* --skip-history

**Comment by takebayashi** [comment]
renamed to `--skip-history`

**Comment by gribozavr** [comment]
@takebayashi Thank you!

**Pull request merged**
