### PR TITLE
Revert "Builtin.FixedArray"

### PR DESCRIPTION
**Pull request by MaxDesiatov**
Reverts swiftlang/swift#76831 due to failing Wasm job

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci test webassembly

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Comment by Azoy** [comment]
Can you link the failing job?

**Comment by aschwaighofer** [comment]
https://ci.swift.org/job/oss-swift-pr-test-crosscompile-wasm-ubuntu-20_04/1730/

**Comment by aschwaighofer** [comment]
It is possible that @jckarter is trying to fix this issue here: https://github.com/swiftlang/swift/pull/77205

**Pull request closed without merging**
