### PR TITLE
[Compile Time Constant Extraction] Extract line and file information

### PR DESCRIPTION
**Pull request by jPaolantonio**
This PR adds line number and filename extraction for types and properties.

It also restructures tests to have `CHECK` after the declared code to help limit future line number changes.

### CODE REVIEW

**Comment by jPaolantonio** [comment]
@swift-ci test

**Review by artemcm — APPROVED** [review]
This looks great. 

It made me think that additionally we may want to include the source-file name in the output also? When running the compiler in WMO mode, it will be processing many different source-file inputs in a single ruin for a single JSON output, and line-numbers alone probably won't be sufficient for clients to act on.

**Comment by jPaolantonio** [comment]
> This looks great.
> 
> It made me think that additionally we may want to include the source-file name in the output also? When running the compiler in WMO mode, it will be processing many different source-file inputs in a single ruin for a single JSON output, and line-numbers alone probably won't be sufficient for clients to act on.

Makes sense to me. Let me add file.

**Comment by jPaolantonio** [comment]
@artemcm - Added source file support.

**Review by artemcm — APPROVED** [review]

**Comment by artemcm** [comment]
@swift-ci test

**Comment by jPaolantonio** [comment]
@swift-ci test

**Comment by jPaolantonio** [comment]
@swift-ci test

**Comment by jPaolantonio** [comment]
@swift-ci test

**Comment by jPaolantonio** [comment]
@swift-ci test

**Comment by jPaolantonio** [comment]
@swift-ci test

**Pull request merged**
