### PR TITLE
stdlib: restructure for OS family layout of SDK overlay

### PR DESCRIPTION
**Pull request by compnerd**
The SDK directory is now confusing as the Windows target also has a SDK
overlay.  In order to make this more uniform, move the SDK directory to
Darwin which covers the fact that this covers the XNU family of OSes.
The Windows directory contains the SDK overlay for the Windows target.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by jrose-apple** [comment]
Ross has been swamped this week with Apple-internal things, sorry.

**Review by Rostepher — APPROVED** [review]
The changes look sensible to me. If possible a little heads-up before you merge would be greatly appreciated.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Pull request merged**
