### PR TITLE
[gardening] Fix end-of-namespace comment mismatch

### PR DESCRIPTION
**Pull request by practicalswift**
@jrose-apple - would you mind reviewing? :-)

### CODE REVIEW

**Comment by jrose-apple** [comment]
I think the correct answer is to remove the namespace altogether. Everything in it is just implementing something that's already been declared in the header file.

**Comment by jrose-apple** [comment]
Actually, it'd be interesting to know if there are *any* sensible non-anonymous namespaces outside of header files. Our style mostly suggests there shouldn't be.

**Comment by practicalswift** [comment]
@swift-ci please smoke test and merge

**Comment by practicalswift** [comment]
@swift-ci please test and merge

**Comment by practicalswift** [comment]
@jrose-apple Namespace removed.

I'll look into writing a gardening script that hunts for redundant namespaces. Thanks for the idea!

**Comment by practicalswift** [comment]
@swift-ci please smoke test and merge

**Comment by practicalswift** [comment]
@swift-ci please test and merge

**Comment by practicalswift** [comment]
@swift-ci please smoke test and merge

**Comment by practicalswift** [comment]
@swift-ci please test and merge

**Comment by practicalswift** [comment]
@swift-ci please smoke test

**Comment by practicalswift** [comment]
@swift-ci please test

**Pull request merged**
