### PR TITLE
viewcfg: use the 'helvetica' font

### PR DESCRIPTION
**Pull request by atrick**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci smoke test and merge

**Comment by atrick** [comment]
@swift-ci smoke test

**Review by eeckstein — APPROVED** [review]
lgtm

**Comment by atrick** [comment]
I can't get the build logs to load (having this problem for the past week). So I'll just retry.

**Comment by atrick** [comment]
@swift-ci smoke test and merge

**Comment by atrick** [comment]
@swift-ci smoke test and merge

**Comment by atrick** [comment]
@swift-ci smoke test and merge

**Comment by atrick** [comment]
@swift-ci smoke test and merge

**Comment by atrick** [comment]
@swift-ci smoke test linux

**Comment by atrick** [comment]
@swift-ci smoke test linux

**Pull request merged**
