### PR TITLE
[4.2] Don't mangle generic type aliases at all

### PR DESCRIPTION
**Pull request by DougGregor**
**Explanation:** The recently-introduced mangling for generic typealiases produced both incorrect manglings as well as correct manglings that both the demangler and remangler would break on. Remove this functionality, which effectively reverts the behavior back to what was in Swift <= 4.1.
**Scope:** Affects debug builds of effectively any Swift project, because only debug builds include mangling of typealiases. A number of these were triggering compiler assertions (when the compiler was built with assertions).
**Risk:** Very low; we're effectively reverting back to a non-typealias mangling, which puts the debug-info path on the same code path as the rest of the compiler.
**Testing:** Compiler regression tests, built various other projects that were 
**Reviewer:** @dcci 
**SR / Radar:** rdar://problem/41444286

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Review by dcci — APPROVED** [review]

**Comment by DougGregor** [comment]
@swift-ci please nominate

**Comment by DougGregor** [comment]
https://github.com/apple/swift-lldb/pull/724 loosens the LLDB test that was checking for a generic typealias demangling.

**Comment by DougGregor** [comment]
@swift-ci please test macOS

**Comment by DougGregor** [comment]
"Jenkins error". ARGH!

**Comment by DougGregor** [comment]
@swift-ci please test macOS

**Comment by DougGregor** [comment]
@swift-ci please test macOS

**Pull request merged**
