### PR TITLE
ClosureLifetimeFixup: fix a crash due to an iterator invalidation problem.

### PR DESCRIPTION
**Pull request by eeckstein**
The fix is the use the InstructionDeleter to iterate over (the not yet deleted) instructions in a block.

rdar://80093482

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci test

**Review by atrick — APPROVED** [review]
LGTM- thanks

**Comment by eeckstein** [comment]
@swift-ci test macOS

**Comment by eeckstein** [comment]
@swift-ci test macOS

**Pull request merged**
