### PR TITLE
[gardening] Improve readability of `pstdev` in swift-bench.py

### PR DESCRIPTION
**Pull request by alexwlchan**
#### What's in this pull request?

This doesn't change how the function works, just makes it easier to follow:
- Add a docstring that explains how standard deviation is computed
- Use `sample` instead of `l` for the input variable
- Use `math.sqrt` for readability
- Break it down into a couple of intermediate steps for ease of comprehension

Plus a nicer error message in the case where you try to get the standard deviation of an empty list (previously you got a not-completely obvious ZeroDivisionError).
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

This isn't resolving any Swift bugs (that I know of).

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by gribozavr** [comment]
@swift-ci Please Python lint

**Comment by alexwlchan** [comment]
Looking at the lint issues

**Comment by alexwlchan** [comment]
Lint issues should be fixed

**Comment by practicalswift** [comment]
@alexwlchan Excellent stuff! Thanks for some great contributions, please continue cleaning up the Python code in the repo if time permits :-)

**Pull request merged**
