### PR TITLE
🍒[6.0][Concurrency] Reimplement @TaskLocal as a macro

### PR DESCRIPTION
**Pull request by ktoso**
Resolves rdar://120914014

**Description**: This reimplements @TaskLocal as a peer + accessor macro.

This is necessary to avoid sendable warnings about task locals having "mutable state" which property wrappers do introduce for the storage.

**Scope/Impact**: This removes mutable state errors from Swift 6.0 mode, without resorting to compiler hack to turn off the warning for this specific case. 
**Risk:** There is one source compatibility edge case problem this has:
 - because macros don't have type information, we cannot handle this situation:
```
typealias MyOptionInt = Int?
@TaskLocal static var example: MyOptionInt
```

Previously, the compiler would have known that this property is an option, and default it to `nil`. Now, users have to default it explicitly. We make efforts to not break the usual scenario of people declaring a task local with `Optional<T>` or `T?` types -- by parsing string types and trying to check for this. This is the best we can do here with macros.

**Testing**: CI testing
**Reviewed by**: @hborla

**Original PR:** https://github.com/apple/swift/pull/73078
**Radar:** rdar://120914014

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please test

**Review by hborla — APPROVED** [review]

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
https://github.com/apple/swift-driver/pull/1592
@swift-ci please test

**Pull request merged**
