### PR TITLE
Revert "[NFC; Incremental] Rename BasicSourceFileInfo.InterfaceHash"

### PR DESCRIPTION
**Pull request by davidungar**
Reverts apple/swift#36133.

### CODE REVIEW

**Comment by davidungar** [comment]
@swift-ci please smoke test and merge

**Review by rintaro — APPROVED** [review]

**Comment by davidungar** [comment]
Thank you, @rintaro .

**Comment by davidungar** [comment]
@swift-ci please smoke test and merge

**Comment by davidungar** [comment]
@swift-ci please smoke test and merge

**Comment by davidungar** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
