### PR TITLE
Pass the early SwiftSyntax build directory down to build-script-impl.

### PR DESCRIPTION
**Pull request by DougGregor**
This gives LLDB's CMake build access to the build directory.

### CODE REVIEW

**Comment by DougGregor** [comment]
https://github.com/apple/llvm-project/pull/5289

@swift-ci please smoke test

**Comment by CodaFi** [comment]
https://github.com/apple/llvm-project/pull/5289

@swift-ci please smoke test

**Comment by DougGregor** [comment]
https://github.com/apple/llvm-project/pull/5289

@swift-ci please smoke test macOS

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Pull request merged**
