### PR TITLE
[SwiftSyntax] Fix SyntaxChildren iteration

### PR DESCRIPTION
**Pull request by allevato**
`SyntaxChildren.Iterator` stops the first time it sees a nil child. Since it traverses all indexes without considering presence, this seems to be causing it to terminate iteration early if there is a missing child in the list.

### CODE REVIEW

**Comment by allevato** [comment]
I would like to add unit tests for this change, but it looked like `build-script -t` wasn't causing the tests in test/SwiftSyntax to build or run. Is there a flag I'm missing?

**Comment by gottesmm** [comment]
I forgot, -t goes to --test, right? In that case, it sounds like a bug. @harlanhaskins your thoughts? If it is a bug, please fix in a different PR, then loop back to this one with tests.

**Comment by harlanhaskins** [comment]
Hmm...I checked for those tests when I ran CI when we fixed the build. Are you testing on macOS? Also, thanks for finding this bug!

**Comment by allevato** [comment]
Sorry about that—false alarm! I must have missed the output when I ran the full test suite, and I'm still getting used to the process to run individual tests documented in [Testing.md](https://github.com/apple/swift/blob/master/docs/Testing.md), so when it says to pass a build-relative path like `${SWIFT_BUILD_DIR}/test-macosx-x86_64/SwiftSyntax/` to `lit.py` I was expecting there to be actual files there 🙂  There aren't, but it turns out it still executes the tests.

I've pushed a new commit that adds some basic tests for the iterator.

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test

**Comment by harlanhaskins** [comment]
This LGTM. Thanks for this!

**Pull request merged**
