### PR TITLE
[AutoDiff] Cherry-pick AutoDiff bug fixes and two features into 5.3

### PR DESCRIPTION
**Pull request by rxwei**
This PR attempts to cherry-pick the latest differentiable programming changes into release/5.3, including various bug fixes and two notable features:
* #31173: [AutoDiff] Support differentiation of wrapped properties.
* #32069: [AutoDiff] Support differentiation of branching cast instructions.

Since the entire differentiable programming feature is gated by `import _Differentiation`, merging this into 5.3 should be low-risk.

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please smoke test

**Comment by rxwei** [comment]
@swift-ci please smoke test macOS

**Review by dan-zheng — APPROVED** [review]

**Comment by rxwei** [comment]
```console
18:34:16 --
18:34:16 Exit Code: 2
18:34:16 
18:34:16 Command Output (stderr):
18:34:16 --
18:34:16 <unknown>:0: warning: using sysroot for 'MacOSX' but targeting 'iPhone'
18:34:16 
/Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-release/5.3/swift/test/IRGen/framepointer_arm64.sil:13:8: error: no such module 'Swift'
18:34:16 import Swift
18:34:16        ^
18:34:16 FileCheck error: '-' is empty.
18:34:16 FileCheck command line:  /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-release/5.3/buildbot_incremental/llvm-macosx-x86_64/bin/FileCheck /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-release/5.3/swift/test/IRGen/framepointer_arm64.sil --check-prefix=CHECK
```

The test failure seems unrelated to this change.

**Comment by rxwei** [comment]
@swift-ci please test

**Comment by rxwei** [comment]
@swift-ci Please test linux

**Comment by rxwei** [comment]
@swift-ci Please test linux

**Comment by rxwei** [comment]
@swift-ci Please test linux

**Comment by tkremenek** [comment]
This looks fine to me.

@DougGregor any concerns about taking this patch into 5.3?  Most of it exclusively touches autodiff.

**Review by tkremenek — APPROVED** [review]

**Pull request closed without merging**
