### PR TITLE
[stdlib][DNM] Replace several subscript gets with reads

### PR DESCRIPTION
**Pull request by airspeedswift**
Giving this a go. Seems to make the compiler a bit crashy though...

### CODE REVIEW

**Comment by airspeedswift** [comment]
```
---
2.	While emitting property descriptor for 'subscript(_:)' at /Users/ben/src/swift-source/swift/stdlib/public/core/UnsafeBufferPointer.swift.gyb:269:10
0  swift                    0x0000000108896178 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 40
1  swift                    0x0000000108895555 llvm::sys::RunSignalHandlers() + 85
2  swift                    0x0000000108896782 SignalHandler(int) + 258
3  libsystem_platform.dylib 0x00007fff63e8b87d _sigtramp + 29
4  libsystem_platform.dylib 0x00007fbd049fc080 _sigtramp + 2696349728
5  swift                    0x0000000105d9c893 swift::Lowering::SILGenFunction::emitRValueForStorageLoad(swift::SILLocation, swift::Lowering::ManagedValue, swift::CanType, bool, swift::AbstractStorageDecl*, swift::Lowering::PreparedArguments&&, swift::SubstitutionMap, swift::AccessSemantics, swift::Type, swift::Lowering::SGFContext, bool) + 787
6  swift                    0x0000000105da345a getOrCreateKeyPathGetter(swift::Lowering::SILGenModule&, swift::SILLocation, swift::AbstractStorageDecl*, swift::SubstitutionMap, swift::GenericEnvironment*, llvm::ArrayRef<std::__1::pair<swift::CanType, swift::SILType> >, swift::CanType, swift::CanType) + 2378
7  swift                    0x0000000105da2651 swift::Lowering::SILGenModule::emitKeyPathComponentForDecl(swift::SILLocation, swift::GenericEnvironment*, unsigned int&, bool&, swift::SubstitutionMap, swift::AbstractStorageDecl*, llvm::ArrayRef<swift::ProtocolConformanceRef>, swift::CanType, bool) + 11265
8  swift                    0x0000000105d547d3 swift::Lowering::SILGenModule::tryEmitPropertyDescriptor(swift::AbstractStorageDecl*) + 595
9  swift                    0x0000000105df8e4b SILGenExtension::emitExtension(swift::ExtensionDecl*) + 59
10 swift                    0x0000000105df8e05 swift::Lowering::SILGenModule::visitExtensionDecl(swift::ExtensionDecl*) + 21
11 swift                    0x0000000105d55140 swift::Lowering::SILGenModule::emitSourceFile(swift::SourceFile*) + 832
12 swift                    0x0000000105d55d90 swift::SILModule::constructSIL(swift::ModuleDecl*, swift::SILOptions&, swift::FileUnit*) + 368
13 swift                    0x0000000105d56150 swift::performSILGeneration(swift::ModuleDecl*, swift::SILOptions&) + 16
14 swift                    0x00000001055a910d performCompile(swift::CompilerInstance&, swift::CompilerInvocation&, llvm::ArrayRef<char const*>, int&, swift::FrontendObserver*, swift::UnifiedStatsReporter*) + 13357
15 swift                    0x00000001055a4dc4 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 3028
16 swift                    0x000000010555e5c4 main + 660
17 libdyld.dylib            0x00007fff63c9fa2d start + 1
<unknown>:0: error: unable to execute command: Segmentation fault: 11
```

**Comment by airspeedswift** [comment]
cc @rjmccall

**Comment by rjmccall** [comment]
I'll take a look.

**Comment by slavapestov** [comment]
What about the unsafeAddressWithNativeOwner in ManagedBuffer?

**Comment by airspeedswift** [comment]
I pulled that one out in the hope that was what was causing the crash (it wasn't)

**Comment by rjmccall** [comment]
Okay, a bunch of patches I have in flight at the moment collectively seem to get the stdlib building with this PR.

**Comment by rjmccall** [comment]
The last of those PRs is landing as https://github.com/apple/swift/pull/20352.

**Comment by airspeedswift** [comment]
@swift-ci please benchmark

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@swift-ci please smoke test compiler performance

**Comment by airspeedswift** [comment]
@swift-ci please test linux platform

**Comment by airspeedswift** [comment]
@rjmccall do you have a view on those benchmark numbers from this change being expected/unexpected?

**Comment by rjmccall** [comment]
I'm seeing similar things with https://github.com/apple/swift/pull/20415, and I've been trying to tweak the heuristics accordingly.  I know that we're not really taking advantage of read accessors very much right now on the caller side, but some of these are, yeah, not where we want them.  You might try testing the combination to see if it helps.

**Comment by airspeedswift** [comment]
@swift-ci please benchmark

**Comment by airspeedswift** [comment]
@swift-ci please benchmark

**Comment by airspeedswift** [comment]
Re-benchmarking to see if much has changed after a few other things like the new String have landed.

**Pull request closed without merging**
