### PR TITLE
Add a Test Demonstrating Superfluous Cascading Across Module Boundaries

### PR DESCRIPTION
**Pull request by CodaFi**
The idea is this: If we can have private intra-module dependencies, why
not also have private inter-module dependencies. Currently, this is
impossible because all edges from the CompilerInstance-level
DependencyTracker are unconditionally registered as cascading. In
addition, module loads are charged as depenendents to all files in
a given batch, which means the exact set of external dependencies is
some (non-deterministic) superset of all files in the batch.

This test case demonstrates one outcome of this approach: we recompile
*way* too much when a dependent module changes.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci smoke test and merge

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please smoke test Linux platform

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
