### PR TITLE
[ASTWalker] Don't visit capture list vars twice

### PR DESCRIPTION
**Pull request by hamishknight**
Previously we were walking them once when visiting the capture list, and then again as a part of the pattern binding decl. Change the logic to only visit them as a part of their pattern binding decl.

This fixes a bug that's exposed by https://github.com/apple/swift/pull/37720. Because it requires that change to reproduce, I'll be adding the test case there.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
Source compat failures unrelated

**Review by CodaFi — APPROVED** [review]
Nice catch. Let's just delete the VarDecl here. Any callers that need it can access `PatternBindingDecl::getSingleVar`. It's also surprising to me that the modeling implies that you cannot destructure in a capture list...

**Comment by hamishknight** [comment]
@CodaFi Ah yes, that's a nice simplification, how does this look?

IMO it's still nice to expose a `getVar` accessor on `CaptureListEntry`, and I also noticed there's a couple more simplifications that could be done here.

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by CodaFi** [comment]
LGTM

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Pull request merged**
