### PR TITLE
[5.8] IRGen: Generate #_hasSymbol helpers for `dynamic` and `@_dynamicReplacement(for:)` functions

### PR DESCRIPTION
**Pull request by tshortli**
Cherry pick of https://github.com/apple/swift/pull/62651 to release/5.8.

Resolves rdar://103404707

### CODE REVIEW

**Comment by tshortli** [comment]
@swift-ci please smoke test

**Review by nkcsgexi — APPROVED** [review]

**Comment by tshortli** [comment]
@swift-ci please test

**Comment by tshortli** [comment]
@swift-ci please test macOS

**Comment by tshortli** [comment]
@swift-ci test macOS

**Comment by tshortli** [comment]
@swift-ci test macOS

**Pull request merged**
