### PR TITLE
[SILOptimizer] Constant Folding - Style modifications based on review

### PR DESCRIPTION
**Pull request by shajrawi**
rdar://problem/29522851

follow up to https://github.com/apple/swift/pull/23720

### CODE REVIEW

**Comment by shajrawi** [comment]
@swift-ci Please smoke test and merge

**Comment by shajrawi** [comment]
@swift-ci Please smoke test and merge

**Comment by shajrawi** [comment]
@swift-ci Please smoke test and merge

**Comment by shajrawi** [comment]
@swift-ci Please smoke test and merge

**Comment by gottesmm** [comment]
Looks beautiful! Thanks!

**Pull request merged**
