### PR TITLE
Performance improvements for new integers

### PR DESCRIPTION
**Pull request by swiftix**
A set of of small peepholes to improve the performance of new integers:
- peepholes for comparisons with Int.Max
- peepholes for some variants of cond_br
- some overflow-check-removal improvements.

### CODE REVIEW

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by dabrahams** [comment]
@swiftix thank you, and thanks especially for a solution that doesn't need to touch the standard library!

**Comment by swiftix** [comment]
@swift-ci please benchmark

**Comment by eeckstein** [comment]
cool!

**Pull request merged**
