### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by benrimmington**
Add [release date](https://swift.org/blog/swift-4-1-released/) and references

### CODE REVIEW

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test

**Comment by benrimmington** [comment]
@harlanhaskins, I've rebased and squashed. Please try `@swift-ci smoke test and merge` if possible.

**Comment by harlanhaskins** [comment]
Where are your manners? 😜

@swift-ci please smoke test and merge

**Comment by benrimmington** [comment]
Build failed: "Wrong sha 627a216d0bc220719cefa17cdbc8fa4763f3e482"

<https://ci.swift.org/job/swift-PR-smoke-merge/1770/console>

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test

**Comment by benrimmington** [comment]
@harlanhaskins, the smoke test succeeded.

Please could you merge this without swift-ci (to avoid the "wrong sha" issue).

**Comment by harlanhaskins** [comment]
Thanks for updating the changelog!

**Pull request merged**
