### PR TITLE
Bump swift-crypto to 2.2.3

### PR DESCRIPTION
**Pull request by yim-lee**
This is for https://github.com/apple/swift-package-manager/pull/5920

rdar://82934196

### CODE REVIEW

**Comment by yim-lee** [comment]
@swift-ci please test

**Comment by yim-lee** [comment]
@swift-ci please smoke test

**Comment by yim-lee** [comment]
@swift-ci Please Test Source Compatibility

**Comment by yim-lee** [comment]
cc @tomerd

**Review by tomerd — APPROVED** [review]

**Comment by yim-lee** [comment]
Please don't merge yet. We might need https://github.com/apple/swift-crypto/pull/136

**Comment by yim-lee** [comment]
@swift-ci please test

**Comment by yim-lee** [comment]
@swift-ci please test Linux

**Comment by yim-lee** [comment]
@swift-ci Please Test Source Compatibility

**Comment by yim-lee** [comment]
@swift-ci please test linux

**Comment by yim-lee** [comment]
@swift-ci Please Test Source Compatibility

**Comment by yim-lee** [comment]
@swift-ci please smoke test linux

**Comment by yim-lee** [comment]
https://github.com/apple/swift-package-manager/pull/5920

@swift-ci please smoke test linux

**Comment by yim-lee** [comment]
https://github.com/apple/swift-package-manager/pull/5920

@swift-ci please smoke test

**Comment by yim-lee** [comment]
https://github.com/apple/swift-package-manager/pull/5920

@swift-ci please smoke test

**Comment by yim-lee** [comment]
Replaced by https://github.com/apple/swift/pull/62890

**Pull request closed without merging**
