### PR TITLE
[SwiftCompilerModules] Link lib_InternalSwiftSyntaxParser to libswift

### PR DESCRIPTION
**Pull request by rintaro**
To use _RegexParser from SwiftSyntax.

* Create `libswiftCompilerModules_SwiftSyntax.a` which is a subset of `libswiftCompilerModules.a`
* Link `lib_InternalSwiftSyntaxParser` to `libswiftCompilerModules_SwiftSyntax.a`
* Factor out swift runtime linking logic in CMake so that dynamic libraries can link to Swift runtime, in addition to executables
* Link `lib_InternalSwiftSyntaxParser` to swift runtime

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by rintaro** [comment]
@swift-ci Please test

**Review by eeckstein — APPROVED** [review]
lgtm

**Pull request merged**
