### PR TITLE
[MoveOnlyAddressChecker] Fix enum representation.

### PR DESCRIPTION
**Pull request by nate-chandler**
Based on https://github.com/apple/swift/pull/72463 .

Change FieldSensitive's enum representation to allow distinguishing among the elements with associated value.  Consider `unchecked_take_enum_data_addr` to consume all other fields than that taken.

rdar://125113258

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by jckarter — APPROVED** [review]

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test linux platform

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Pull request merged**
