### PR TITLE
[ConstraintSystem] Always propagate inout/variadic flags to type-less…

### PR DESCRIPTION
**Pull request by xedin**
… closure parameters

Instead of infer all of the flags only for anonymous parameters,
let's infer inout/variadic for all type-less parameters - anonymous
and named. This allows to correctly form internal parameter type and
reduce amount of inference in the body (e.g. `BindParam` could be
simplified inline).

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Comment by xedin** [comment]
@swift-ci please test source compatibility debug

**Review by hborla — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test source compatibility debug

**Pull request merged**
