### PR TITLE
Ensure internal ObjC classes aren't exposed in archives.

### PR DESCRIPTION
**Pull request by michael-lehew**
#### What's in this pull request?

Changes to ensure that new NSObject subclasses aren't accidentally persisted into NSCoder archives (and thus need to be maintained forever). 
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

N/A

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

We currently specify a few internal ObjC classes.  This commit ensures that they can not be accidentally exposed (and thus need to be supported) into the future. Luckily, NSData and NSDictionary/NSMutableDictionary already specify classForCoder in a general way. NSCharacterSet does not.

This commit also establishes unit tests to ensure all three types do not regress from this into the future.

Also, for completeness, it ensures classForArchiver and classForKeyedArchiver return appropriately as well.

### CODE REVIEW

**Comment by michael-lehew** [comment]
@swift-ci Please test and merge

**Comment by gottesmm** [comment]
It looks like this failed due to renaming changes that are related. Trying this again.

**Comment by gottesmm** [comment]
@swift-ci Please test and merge

**Comment by michael-lehew** [comment]
Thanks, I was waiting for things to quiet down and be green, since it didn't look like my PR was the underlying cause. *fingers crossed*

**Comment by michael-lehew** [comment]
Another unrelated build-failure. Will try again later.

**Comment by michael-lehew** [comment]
@swift-ci Please test and merge

**Comment by michael-lehew** [comment]
Try again following merge. 

@swift-ci Please test and merge

**Comment by michael-lehew** [comment]
Found a problem in this commit thanks to CI (funny it wasn't failing locally). 

@swift-ci Please test and merge

**Comment by gottesmm** [comment]
@swift-ci Please test and merge

**Comment by gottesmm** [comment]
The tree is green right now.

**Pull request merged**
