### PR TITLE
Sema: Look through inout when mapping IUOs to Optionals.

### PR DESCRIPTION
**Pull request by rudkx**
We translate IUOs to Optionals when generating signatures, but were
failing to look through inout in the process, so we were allowing
functions to be overloaded by Optional vs. IUO when the parameter was
inout.

Fixes https://bugs.swift.org/browse/SR-6685 / rdar://problem/36255630.

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by jrose-apple** [comment]
I'm very unhappy with breaking source in this way, even if 97% of the time simply deleting the IUO overload is the right thing to do.

**Comment by rudkx** [comment]
Discussion happening here: https://bugs.swift.org/browse/SR-6690

**Comment by rudkx** [comment]
As expected there's a failure on ObjectMapper in the source compatibility suite due to this change.

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Pull request merged**
