### PR TITLE
[cxx-interop] Emit IR for templated static members with an out-of-line definition

### LINKED ISSUE #63055: Linker error when a templated C++ class declares a static out-of-line member
Using `std::u16string` from Swift on CentOS 7 causes a linker issue:
```
/home/build-user/build/buildbot_linux/swift-linux-x86_64/lib/swift/linux/libswiftstd.so: error: undefined reference to 'std::basic_string<char16_t, std::char_traits<char16_t>, std::allocator<char16_t> >::_Rep::_S_empty_rep_storage'
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
```

This happens because `_S_empty_rep_storage` is a static member that has a templated definition outside of the class.

Here is a smaller reproducer:

```cpp
// C++
template <class T>
struct HasStaticOutOfLineMember {
  static int values[];
  
  static int getFirstValue() {
    return values[0];
  }
};

template <class T>
int HasStaticOutOfLineMember<T>::values[123];

typedef HasStaticOutOfLineMember<int> HasStaticOutOfLineMemberInt;
```

```swift
// Swift
import ClassTemplateWithOutOfLineMember

public func usesStaticMember() {
  let x = HasStaticOutOfLineMemberInt.getFirstValue()
}
```

```
Undefined symbols for architecture x86_64:
  "__ZN24HasStaticOutOfLineMemberIiE6valuesE", referenced from:
      __ZN24HasStaticOutOfLineMemberIiE13getFirstValueEv in class-template-with-static-out-of-line-member-17251a.o
ld: symbol(s) not found for architecture x86_64
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
```

### PR DESCRIPTION
**Pull request by egorzhdan**
This fixes https://github.com/apple/swift/issues/63055.

rdar://101539308

### CODE REVIEW

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Review by zoecarver — APPROVED** [review]
LGTM, thanks, Egor!

**Pull request merged**
