### PR TITLE
Eliminate context descriptor cache

### PR DESCRIPTION
**Pull request by airspeedswift**
Joe's recent changes to how we look up metadata should have reduced the need for this. Reverts #26579

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please benchmark

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]
Definitely the right thing to do. Joe's approach is far better overall, whereas this cache can be pretty large.

**Comment by mikeash** [comment]
I'm happy to see this go. Is there a convenient link to the changes that made this unnecessary?

**Pull request merged**
