### PR TITLE
fix cross-compiled library names

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC @modocache @hughbe

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by hughbe** [comment]
Looks good to me. Btw I'm not bothered but you seem to keep making changes that I've already made, and you've already commented on (e.g the pipe commit) - might it be more helpful just to merge that PR? Same goes for some of the lib name stuff

**Comment by hughbe** [comment]
Nice!

**Comment by hughbe** [comment]
Btw, I get the following build warnings with this change. I think it may be the reason why I was getting the IMPLIB errors in my Windows port:
```
ninja: warning: multiple rules generate lib/swift/windows/x86_64/swiftCore.lib. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]
ninja: warning: multiple rules generate lib/swift/windows/x86_64/swiftSwiftOnoneSupport.lib. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]
ninja: warning: multiple rules generate lib/swift/windows/x86_64/swiftRemoteMirror.lib. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]
ninja: warning: multiple rules generate lib/swift/windows/x86_64/swiftMSVCRT.lib. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]
ninja: warning: multiple rules generate lib/swift/windows/x86_64/swiftSwiftExperimental.lib. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]
ninja: warning: multiple rules generate lib/swift/windows/x86_64/swiftSwiftPrivate.lib. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]
```

**Comment by compnerd** [comment]
I suspect that you are building both static and dynamic libraries.  That would show up like this.  I included part of your change which is why this would show up (we head different prefixes on static libraries previously).  I assume that it was causing more confusion then its worth as only a few libraries from Microsoft follow the convention that we were following previously.  I can restore the original behavior of you think that we should support building both simultaneously for Windows.

**Comment by hughbe** [comment]
I don't really mind - I'd say merge this and the other PR in - I'd like to fix the merge conflicts resulting from them!

**Comment by llvm-beanz** [comment]
As long as this passes tests it LGTM.

**Pull request merged**
