### PR TITLE
[semantic-arc] Eliminate ARC traffic from phi args that are dead except for said traffic

### PR DESCRIPTION
**Pull request by gottesmm**
This PR actually contains two different commits, the second which is the main commit.

1. A change to SemanticARCOptVisitor to make it a SILValueVisitor instead of a SILInstructionVisitor. This allows for me to make it visit SILArguments. This makes sense anyways since its internal worklist is on values.
2. I added a new optimization to SemanticARC to eliminate owned/guaranteed phi nodes that are only alive due to debug uses and end scope instructions like end_borrow, destroy_value. In such a case, we move the end_scope instruction onto the arg's incoming values in the pred blocks, change the br insts to take undef, and change the arg's ownership kind to None.

NOTE: The reason why I do not delete the phi node in (2) is b/c in such a case, I will need to replace the branch instructions invalidating terminators (which I don't want to do in the pass). A phi node taking only undef is trivial for simplify-cfg or something later to take care of and won't hurt anything in the mean time.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
Just curious on the benchmark thing.

**Comment by gottesmm** [comment]
The test failure is due to my using the loc of the branch on one of my values. Hmm... I am going to use an autogenerated location.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
Hit an eager specializer bug.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
I am pretty sure the differentiation difference is that we hit some threshold around inlining given that we decreased perf and massively decreased code-size. A change like this wouldn't cause such a change.

**Comment by gottesmm** [comment]
Interesting. This commit even with a small change I added to delete the dead arguments before semantic ar copts ends, I am breaking outlining. I am looking into what's wrong with the pattern match.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
preset=buildbot,tools=RA,stdlib=RD,test=non_executable
@swift-ci Please test with preset macOS

**Comment by gottesmm** [comment]
Fixed the outlining test.

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
preset=buildbot,tools=RA,stdlib=RD,test=non_executable
@swift-ci Please test with preset macOS

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
This is turning out to break a ton of things. I think that I am going to see if I can /not/ use this.

**Comment by atrick** [comment]
Wow, too bad so much of our SIL is still relying on not optimizing ARC.

**Pull request closed without merging**
