### PR TITLE
[Parse] Offer fixits to #elseif for #elsif & #elif.

### PR DESCRIPTION
**Pull request by huonw**
Fixes rdar://problem/29216842.

### CODE REVIEW

**Comment by huonw** [comment]
@swift-ci please smoke test

**Comment by rintaro** [comment]
I'm wondering adding new `tok` kind is good thing or not for this.
If we do this, libSyntax must handle them and treat `#elif` and `#elsif` as a "valid" token for `IfConfigClauseSyntax.PoundKeyword`.
If we don't, `#elif` is tokenized as `{ tok::pound, tok::identifier }`. Although we can handle them in `Parser` and produce valid AST, but libSyntax will not be able to construct `IfConfigClause`.
@nkcsgexi, @ahoppen What do you think?

**Comment by ahoppen** [comment]
I'm not really happy about adding tokens to the compiler that are in fact invalid.

Wouldn't it be possible to catch this in the lexer instead of the parser? I.e. in [Lexer.cpp:660](https://github.com/apple/swift/blob/master/lib/Parse/Lexer.cpp#L660) before entering the `llvm::StringSwitch` check if the text of identifier text is `#elif` or `#elsif`. If it is, set `Kind` to `#elseif` and emit the error.

**Comment by nkcsgexi** [comment]
I agree that adding new token kinds for common erroneous input is an overkill. Can we check the content of tokens in the parser instead?

**Comment by rintaro** [comment]
Sorry, please don't `setKind(tok::pound_elseif)` unless it's actually `#elseif`. libSyntax assumes that the text of `PoundElseifToken` is always `"#elseif"`. CC: @ahoppen .

**Comment by ahoppen** [comment]
We need some way to represent corrected tokens in the libSyntax tree. 

We could, with the current architecture, add the real token that occurs in source as `TriviaPiece::garbageText` and then add an `#elseif` token with `SourcePresence` set to `missing`. That would maintain roundtripness for the source text. 

@nkcsgexi: Do you think that should be the recommended way or should we have some more dedicated way to represent corrected tokens? One idea:
Have a new `SourcePresence` named e.g. `Corrected`. In that case the token should not automatically infer its text but always consult the string stored in the `RawSyntax` node. This would mean that we can only correct tokens with a predefined text and not e.g. identifiers. But maybe that's not a major restriction. What do you think?

**Pull request closed without merging**
