### PR TITLE
Include source ranges for statements, declarations, and parameter lists in the AST dump

### PR DESCRIPTION
**Pull request by bdash**
Source ranges are currently missing from statements, declarations, and parameter lists in the AST dump. This PR addresses that.

For some background: we have a Swift-based domain-specific language that works by analyzing AST dumps and transforming them into new Swift code. In cases where the input doesn't match the constraints of our DSL, we emit errors that point to the problems in the original Swift source. The lack of source range information on these node types makes this difficult for certain types of errors.

This is #16473 rebased on master, with the necessary fixes made to tests.

### CODE REVIEW

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by bdash** [comment]
It looks like the OS X test failure was due to a Jenkins issue. Is typical practice to simply re-run the CI job in this situation?

**Comment by benlangmuir** [comment]
@swift-ci please test macOS

**Comment by bdash** [comment]
Any chance we can get this merged? The longer it sits, the more likely other test changes will be made that will need to be accommodated in this PR.

**Comment by bdash** [comment]
Thanks, @benlangmuir!

**Pull request merged**
