### PR TITLE
[Minor][SIL] Refactor `matches` function in `Effects`

### PR DESCRIPTION
**Pull request by Mayank-84**
- This PR refactors the existing conditional check within the `matches` function. 
- This improves code readability and reduces the number of lines.

### CODE REVIEW

**Comment by Mayank-84** [comment]
Hi @eeckstein, I see that we can follow latest swift syntaxes like shorter versions of if-let, etc at multiple places. Wanted to understand why are we not using this within these files? Are there any constraints related to CI or any platform versions that it is supporting?

**Comment by eeckstein** [comment]
> Are there any constraints related to CI or any platform versions that it is supporting?

The only constraint is that It should be buildable with swift 5.9 (or later). If that's the case we can change to the newer syntax.

**Review by eeckstein — APPROVED** [review]
lgtm

**Comment by Mayank-84** [comment]
@swift-ci smoke test

**Comment by Mayank-84** [comment]
@eeckstein Can you trigger the smoke test CI pipeline? I guess it is not accessible to me.

**Comment by Mayank-84** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Pull request merged**
