### PR TITLE
Fix `async_task_priority.swift` test failure

### PR DESCRIPTION
**Pull request by etcwilde**
This patch updates `async_task_priority.swift` to only run on Apple platforms since it directly imports `Darwin`.
Additionally, replaces `@_predatesConcurrency` with the final `@preconcurrency` spelling.

### CODE REVIEW

**Comment by etcwilde** [comment]
@swift-ci please test

**Review by rokhinip — APPROVED** [review]

**Review by ktoso — APPROVED** [review]

**Comment by etcwilde** [comment]
@swift-ci please test Linux

**Comment by etcwilde** [comment]
@swift-ci Please Build Toolchain Linux Platform

**Comment by etcwilde** [comment]
@swift-ci please test Linux

**Pull request merged**
