### PR TITLE
[Frontend] Avoid passing CompilerInvocation + CompilerInstance

### PR DESCRIPTION
**Pull request by hamishknight**
Instead of passing both a `CompilerInvocation` and `CompilerInstance` throughout FrontendTool, just pass the `CompilerInstance` and use it to get the invocation.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Review by CodaFi — APPROVED** [review]

**Comment by hamishknight** [comment]
@swift-ci please smoke test

**Comment by hamishknight** [comment]
@swift-ci please smoke test

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Pull request merged**
