### PR TITLE
[6.0] Parser: Don't skip functions with a nested typealias, protocol or actor for LLDB

### PR DESCRIPTION
**Pull request by xymus**
The flag `-experimental-skip-non-inlinable-function-bodies-without-types` is used by the emit-module-separately phase to quickly extract the API of the target module to unblock building dependents. It is designed to preserve compatibility with LLDB by not skipping functions with nested types. This logic relies on a simple heuristic to find nested type.

This change adds detection of nested typealiases, protocols and actors declarations to force parsing functions containing them.

- Scope: The emit-module-separately job used in regular debug builds will parse more function bodies.
- Risk: Low, the newly parsed function bodies are already parsed by other compiler jobs.
- Testing: Extended an existing test to cover these cases.
- Reviewer: @tshortli 
- Issue: rdar://120928396

### CODE REVIEW

**Comment by xymus** [comment]
@swift-ci Please test

**Review by nkcsgexi — APPROVED** [review]

**Comment by xymus** [comment]
@swift-ci Please test macOS

**Comment by xymus** [comment]
@swift-ci Please test Linux

**Comment by xymus** [comment]
@swift-ci Please test macOS

**Comment by xymus** [comment]
@swift-ci Please test Linux

**Comment by xymus** [comment]
@swift-ci Please test macOS

**Pull request merged**
