### PR TITLE
Merging swift-DEVELOPMENT-SNAPSHOT-2019-11-11-a into tensorflow.

### PR DESCRIPTION
**Pull request by bgogul**
Finishing the merge from upstream.

### CODE REVIEW

**Comment by bgogul** [comment]
@swift-ci please clean test tensorflow

**Review by dan-zheng — APPROVED** [review]
LGTM! I only looked at `utils/update_checkout/update-checkout-config.json`.

**Comment by dan-zheng** [comment]
There are two test failures on macOS:
```
Failing Tests (2):
    Swift(macosx-x86_64) :: Sema/type_checker_perf/slow/rdar33688063.swift
    Swift(macosx-x86_64) :: Sema/SwiftUI/rdar56710317.swift
```

I believe these failures are related to Xcode version: the CI machine is using Xcode 11 beta 1 while Xcode 11.2 is now required.

I'll upgrade the CI machine to Xcode 11.2 and run tests again.

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow macOS

**Comment by dan-zheng** [comment]
macOS CI failed: https://ci-external.swift.org/job/swift-PR-TensorFlow-macOS/2271
It seems the connection was broken. Retriggering.

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow macOS

**Comment by dan-zheng** [comment]
`Sema/type_checker_perf/slow/rdar33688063.swift` still fails on the CI machine after upgrading to Xcode 11.2:
```
******************** TEST 'Swift(macosx-x86_64) :: Sema/type_checker_perf/slow/rdar33688063.swift' FAILED ********************
/Users/swiftci/jenkins/workspace/swift-PR-TensorFlow-macOS/swift/validation-test/Sema/type_checker_perf/slow/rdar33688063.swift:4:79: error: unexpected error produced: the compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions
let _ = 1 | UInt32(0) << 0 | UInt32(1) << 1 | UInt32(2) << 2 | UInt32(3) << 3 | UInt32(4) << 4
                                                                              ^
...

Failing Tests (1):
    Swift(macosx-x86_64) :: Sema/type_checker_perf/slow/rdar33688063.swift
```

It seems the test has been [disabled on `master`](https://github.com/apple/swift/commit/7a3d2307f7711450cde0cac12c18c968670c75f9), so I'll cherry-pick the disabling patch.

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow macOS

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow macOS

**Pull request merged**
