### PR TITLE
[Foundation] Guard Data access to NSData._isCompact under availabilit…

### PR DESCRIPTION
**Pull request by parkera**
#12601 made it into the swift-4.0-branch but not the later branches.

### CODE REVIEW

**Comment by parkera** [comment]
@swift-ci please smoke test

**Comment by zisko** [comment]
@swift-ci please smoke test

**Comment by zisko** [comment]
@swift-ci please smoke test

**Comment by parkera** [comment]
@itaiferber this is the same change from the swift-4.0, 4.1, 4.2, and master branches and we need to merge it here.

**Review by itaiferber — APPROVED** [review]

**Comment by parkera** [comment]
@swift-ci please smoke test linux

**Comment by shahmishal** [comment]
Should this be going to swift-5.0-branch?

**Comment by shahmishal** [comment]
We don't currently support swift-5.0-branch testing, in the future we will be re-branching from master for swift-5.0-branch so this does not need to be committed into swift-5.0-branch.

**Comment by parkera** [comment]
I guess if we rebranch later then this change will be picked up from master. Thanks!

**Pull request closed without merging**
