### PR TITLE
[Index] Convert to hashing to `HashBuilder` with BLAKE3

### PR DESCRIPTION
**Pull request by bnbarham**
`Hashing.h` is non-deterministic between runs. Update the index hashing to use BLAKE3 for the record hash. xxhash is faster in benchmarks that I've found, but there's no easy `HashBuilder` option for it today.

### CODE REVIEW

**Comment by bnbarham** [comment]
https://github.com/swiftlang/llvm-project/pull/9140

@swift-ci please test

**Review by ahoppen — APPROVED** [review]

**Comment by bnbarham** [comment]
https://github.com/swiftlang/llvm-project/pull/9140

@swift-ci please test

**Comment by bnbarham** [comment]
https://github.com/swiftlang/llvm-project/pull/9140

@swift-ci please test

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
https://github.com/swiftlang/llvm-project/pull/9140

@swift-ci please test

**Comment by bnbarham** [comment]
https://github.com/swiftlang/llvm-project/pull/9140

@swift-ci please test

**Comment by bnbarham** [comment]
https://github.com/swiftlang/llvm-project/pull/9140

@swift-ci please test Windows platform

**Comment by bnbarham** [comment]
https://github.com/swiftlang/llvm-project/pull/9140

@swift-ci please test macOS platform

**Comment by bnbarham** [comment]
https://github.com/swiftlang/llvm-project/pull/9140

@swift-ci please test macOS platform

**Comment by bnbarham** [comment]
https://github.com/swiftlang/llvm-project/pull/9140

@swift-ci please test Windows platform

**Comment by bnbarham** [comment]
https://github.com/swiftlang/llvm-project/pull/9140

@swift-ci please test Windows platform

**Pull request merged**
