### PR TITLE
Fix multisource benchmarks

### PR DESCRIPTION
**Pull request by gottesmm**
This PR fixes multisource benchmarks and converts the single-source benchmark Prims into a multi-source test called PrimsSplit to ensure that there is at least 1 multi-source benchmark.

rdar://34556274

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test and mergec

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by gottesmm** [comment]
Linux test timed out for some reason.

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by gottesmm** [comment]
Linux failed again. Due to a CI issue.

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by shahmishal** [comment]
Merged to unblock CI testing.

**Comment by gottesmm** [comment]
Thanks Mishal!

**Pull request merged**
