### PR TITLE
[TF] Removed 'HackyTensorflowMigrationSupport'.

### PR DESCRIPTION
**Pull request by eaplatanios**
@rxwei @pschuh Removed `HackyTensorflowMigrationSupport.swift`.

Friend PR: tensorflow/swift-apis#139.

### CODE REVIEW

**Review by rxwei — APPROVED** [review]

**Comment by eaplatanios** [comment]
@rxwei I update the dependency hash so we should be able to run tests now.

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow Linux

**Comment by eaplatanios** [comment]
@rxwei, this is a separate issue but for lack of better communication channel I'll post it here. I tried enabling compiler optimizations for the `TensorFlow` module by setting these flags:
```
list(APPEND swift_stdlib_compile_flags "-O" "-whole-module-optimization")
```
but I still get failures for multiple tests even though GPE is now gone. I believe we should start looking into why this happens as it could potentially have significant performance impact. One very simple test that fails with a set fault, for example, is this:
```swift
StringDescriptionTests.test("Vector") {
  do {
    let vector = Tensor<Int32>(ones: [4])
    expectEqual("[1, 1, 1, 1]", vector.description)
  }

  do {
    var vector = Tensor<Float>([1, 2, 3, 4])
    expectEqual("[1.0, 2.0, 3.0, 4.0]", vector.description)
    vector[1] = Tensor<Float>(-2)
    expectEqual("[ 1.0, -2.0,  3.0,  4.0]", vector.description)
  }

  // Test long vector (above 1000 scalar threshold).
  do {
    let vector = Tensor<Float>(repeating: 3, shape: [1001])
    expectEqual("[3.0, 3.0, 3.0, ..., 3.0, 3.0, 3.0]", vector.description)
  }
}
```
Again, this is separate from this PR so sorry for posting it here if it's confusing.

**Comment by bgogul** [comment]
@rxwei @eaplatanios Is it OK to have known protocols and derived conformances for those protocols that are not part of stdlib?

**Comment by eaplatanios** [comment]
@bgogul I believe that technically they are since `TensorFlow` is part of stdlib. They are just hosted in a separate repository.

Generally though, it'd be great if we found an elegant way to add support for such derivations at the language level, similar to what Scala supports, so that all this can be implemented in Swift. :)

**Comment by eaplatanios** [comment]
I just pushed an edit that fixes the failing test. It only fails on Linux and I don't really understand why but it should be fine now.

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Pull request merged**
