### PR TITLE
Make scripts/pipeline_generator.py usable again

### PR DESCRIPTION
**Pull request by practicalswift**
Before this commit:

```
$ utils/pass-pipeline/scripts/pipeline_generator.py
utils/pass-pipeline/scripts/pipeline_generator.py
Traceback (most recent call last):
  File "utils/pass-pipeline/scripts/pipeline_generator.py", line 15, in <module>
    normal_pipeline = [x for x in pass_pipeline_library.normal_passpipelines()]
  File "/path/to/swift/utils/pass-pipeline/src/pass_pipeline_library.py", line 106, in normal_passpipelines
    x.addPass(specialization_passlist())
NameError: global name 'specialization_passlist' is not defined
```

After this commit:

```
$ utils/pass-pipeline/scripts/pipeline_generator.py
[
    [
        "HighLevel",
        "run_n_times",
        2,
        "SimplifyCFG",
…
```

### CODE REVIEW

**Comment by gottesmm** [comment]
TBH this is the wrong fix. Instead of removing the Prespecialize part of the code, the correct fix is to make it so that pass pipeline generator is generated from Passes.cpp in some way.

**Comment by gottesmm** [comment]
The reason why that is a better fix is that the pass pipeline currently being generated by the pass pipeline generator is from a few months ago and I think things have changed since then. This would make the tool always correct.

**Comment by practicalswift** [comment]
@gottesmm Thanks for clarifying!

It appears that the `NameError` was introduced in this commit when `specialization_passlist()` was removed: https://github.com/apple/swift/commit/4c622040074b4652bec05f4ff54f910d0de4267e#diff-8d3fd7df27dc9794e566b65345350c9aL103

Is there some way we can avoid the `NameError` until the long term fix (auto-generation from `Passes.cpp`) is in place?

**Comment by gottesmm** [comment]
Ok. SGTM. I would file a bug to make sure the auto generation gets fixed.

**Pull request merged**
