### PR TITLE
Add fixit for uses of obsoleted subscripts that return String

### PR DESCRIPTION
**Pull request by rudkx**

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@bitjammer @jrose-apple @moiseev @airspeedswift @xedin 

I still need to add tests for this, but in the meantime, any feedback on either the code or the text output here? 

```
error: 'subscript' is unavailable: subscripts returning String are unavailable; construct a String to select the subscript returning Substring
  fn(s[s.startIndex..<s.endIndex])
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
     String(                     )
Swift.String:3:12: note: 'subscript' was obsoleted in Swift 4
    public subscript(bounds: Range<String.Index>) -> String { get }
```

**Comment by jrose-apple** [comment]
I think I would drop one of the "unavailable" pieces:

- "subscripts returning String are unavailable; explicitly construct a String instead"
- "'subscript' is unavailable: explicitly construct a String from a Substring instead"

You could even squash in the note, since you're doing a special-case diagnostic:

- "subscripts returning String were obsoleted in Swift 4; explicitly construct a String instead"

**Comment by moiseev** [comment]
As I mentioned yesterday, when you see "blah is unavailable" you don't read further, and get confused. Agree with @jrose-apple that it should be a completely custom string like the last one he suggested.

**Comment by jrose-apple** [comment]
If we weren't bothering to provide a custom fix-it it wouldn't be worth it, but since we are it's suddenly not hard to provide a custom diagnostic as well.

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@jrose-apple @moiseev @airspeedswift How does this look?

I tweaked the logic slightly to not fire on subscripts with T<Int> (e.g. Range<Int>) as we do not have versions of these that return Substrings in 4 and thus do not want this special diagnostic. It might be better to whitelist the things we should emit this special error on, but I don't know if that's limited to substring with T<{Sub,}String.Index> arguments or not (and am running out of cycles to devote to this).

**Comment by jrose-apple** [comment]
Looks okay. Are there also going to be diagnostics for the .substring family of functions?

**Comment by rudkx** [comment]
@jrose-apple The only `substring(...)` methods I see return String. Is there something I'm missing?

**Comment by jrose-apple** [comment]
Oh, I figured those were being deprecated or obsoleted in Swift 4 mode too. I didn't actually check.

**Comment by dabrahams** [comment]
on Mon May 15 2017, Jordan Rose <notifications-AT-github.com> wrote:

> Oh, I figured those were being deprecated or obsoleted in Swift 4 mode too. I didn't actually check.

@airspeedswift yeah, the substring methods that come from Foundation
look problematic for us, not least since they return String.

-- 
-Dave

**Pull request merged**
