### PR TITLE
IRGen: Always eliminate frame pointers of leaf functions

### PR DESCRIPTION
**Pull request by aschwaighofer**
rdar://20933449

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please benchmark

**Comment by CodaFi** [comment]
So we tried this a few times in the past and there were some shocking code size regressions that need to be investigated.

**Comment by CodaFi** [comment]
rdar://59172266

**Comment by aschwaighofer** [comment]
The regression are due to increased exception handling frame info.

```
% LIB=libswiftDarwin.dylib ; size -m swift-macosx-x86_64-before/lib/swift/macosx/$LIB ; size -m swift-macosx-x86_64/lib/swift/macosx/$LIB     
Segment __TEXT: 32768
        Section __text: 17466
        Section __stubs: 834
        Section __stub_helper: 1406
        Section __const: 856
        Section __swift5_typeref: 115
        Section __cstring: 213
        Section __swift5_reflstr: 44
        Section __swift5_fieldmd: 28
        Section __swift5_builtin: 40
        Section __swift5_assocty: 72
        Section __swift5_proto: 40
        Section __swift5_types: 12
        Section __info_plist: 567
        Section __unwind_info: 276
        Section __eh_frame: 184
        total 22153
Segment __DATA: 4096
        Section __nl_symbol_ptr: 8
        Section __got: 368
        Section __la_symbol_ptr: 1112
        Section __const: 96
        Section __objc_imageinfo: 8
        Section __data: 56
        Section __bss: 1424
        total 3072
Segment __LINKEDIT: 102400
total 139264
Segment __TEXT: 40960
        Section __text: 17093
        Section __stubs: 834
        Section __stub_helper: 1406
        Section __const: 856
        Section __swift5_typeref: 115
        Section __cstring: 226
        Section __swift5_reflstr: 44
        Section __swift5_fieldmd: 28
        Section __swift5_builtin: 40
        Section __swift5_assocty: 72
        Section __swift5_proto: 40
        Section __swift5_types: 12
        Section __info_plist: 567
        Section __unwind_info: 2572
        Section __eh_frame: 8664
        total 32569
Segment __DATA: 4096
        Section __nl_symbol_ptr: 8
        Section __got: 368
        Section __la_symbol_ptr: 1112
        Section __const: 96
        Section __objc_imageinfo: 8
        Section __data: 56
        Section __bss: 1424
        total 3072
Segment __LINKEDIT: 102400
total 147456
```

**Comment by aschwaighofer** [comment]
Moving code code from the instruction cache onto the disk (eh frame info is cold) at the expense of some disk space is a good trade off IMO.

**Comment by compnerd** [comment]
Does it make sense to have a knob for this (similar to `-fno-omit-frame-pointer` and `-fno-omit-leaf-frame-pointer` in watson cc - yes, clang has `-mno-omit-leaf-frame-pointer` but the spelling is more confusing)?

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please benchmark

**Comment by atrick** [comment]
After @rjmccall 's patch https://github.com/apple/swift/pull/31906, should we just use the clang default attribute unless Swift users override it with -no-fp-elim?

**Comment by atrick** [comment]
I have no idea where those perf regressions would come from. I didn't see any regressions on arm64, but feel free to double check...

**Comment by aschwaighofer** [comment]
@atrick AFAICT clang sets "frame-pointer"="all" (see also my comment on slack)

**Comment by aschwaighofer** [comment]
I have looked at DataAppendSequence and other than the omitted frame instructions there is no difference in the function where we spend our time. So some kinda of cache effect (alignment or otherwise).

**Comment by atrick** [comment]
My questions are

Why are we setting the frame pointer explicitly at all when we just want to inherit clang's behavior (at least after John's patch)?

And in the case that -no-omit-frame-pointer is used, why do we override it both in `createClangCodeGenerator` and `setHasFramePointer`?

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
Of course we can't cherry-pick this version to 5.3 since John's change won't be there. Going back to the previous change.

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@atrick Can you review this change for 5.3?

Ultimately on master i will add a third commit so that we set and use clang's setting see https://github.com/apple/swift/pull/31944. But for 5.3 we can't do that because John's change is not on 5.3.

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by atrick** [comment]
This code makes it seem as if we're still telling clang to emit all frame pointers
```
  CGO.setFramePointer(Opts.DisableFPElim
                          ? clang::CodeGenOptions::FramePointerKind::All
                          : clang::CodeGenOptions::FramePointerKind::None);
```

I don't know if you should remove the code completely, or add a check for DisableFPElim and set it to FramePointerKind::NonLeaf

**Comment by aschwaighofer** [comment]
This only affects C functions that we import (i.e inline foo()).

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Review by atrick — APPROVED** [review]
Looks like this patch will do the right thing. Approved for 5.3!

For after John's patch: the design of the flags is still unacceptably bad. There should only be one place (in the driver) where we interpret the sense of the options: disable/enable/emit/omit whatever! There should be only one place where we check the IRGen flags--why is it different for imported functions? Those flags should first indicate whether the Swift driver has overridden clang's frame-pointer default so it's obvious to someone reading the code that the IRGen options are normally irrelevant. There should probably be two IRGen options:
1. overrideLLVMFramePointerAttribute = T/F (clearly for experimentation only)
2. framePointerAttributeOverride = none/nonleaf/all (clearly only only when the swift driver sets a flag)

Or make flag #2 optional if that's possible.

Finally, some Swift functions will override both LLVM *and* Swift driver flags to suppress frame pointers. And this should all be commented.

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Review by atrick — APPROVED** [review]
isArch64() check LGTM

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by compnerd** [comment]
This seems to have caused a regression on most of the bots.  I think that the test needs to be adjusted.  Reverting until this can be looked at.

**Comment by aschwaighofer** [comment]
Which bot?

**Comment by aschwaighofer** [comment]
Failures in framepointer_arm64.sil should be addressed by https://github.com/apple/swift/pull/31987.

**Pull request merged**
