### PR TITLE
Implement a few silcombine transformations for arrays

### PR DESCRIPTION
**Pull request by lattner**
- Useless existential_ref <-> class conversions.
 - mark_dependence_inst depending on uninteresting instructions.
 - release(init_existential_ref(x)) -> release(x) when hasOneUse(x)
 - Update COWArrayOpt to handle the new forms generated by this.

these aren't massive performance wins, but do shrink the size of SIL when
dealing with arrays.

This updates and subsumes PR 12338

### CODE REVIEW

**Comment by lattner** [comment]
@swift-ci please test and merge

**Comment by lattner** [comment]
@swift-ci please test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@lattner there is a bug in the CI system where after you do a force push, you need to ask it to test twice.

**Comment by gottesmm** [comment]
(I think my 2nd test command caused it to work around the issue).

**Comment by lattner** [comment]
Thank you for the help @gottesmm!

**Comment by bob-wilson** [comment]
There is a new assertion failure on the oss-swift_tools-RA_stdlib-RD_test-simulator bot (https://ci.swift.org/job/oss-swift_tools-RA_stdlib-RD_test-simulator/524/) and this PR is the only thing on the blame list. @lattner can you please take a look?

**Comment by lattner** [comment]
Sure, taking a look @bob-wilson

**Comment by lattner** [comment]
I can't repro this @bob-wilson, but hopefully PR 13656 will fix this.

**Comment by lattner** [comment]
Just to close the loop on this, oss-swift_tools-RA_stdlib-RD_test-simulator is back to happiness.

**Pull request merged**
