### PR TITLE
Turn on formation of Const graph_op's in deabstraction even for the non-strict-deabstraction case

### PR DESCRIPTION
**Pull request by lattner**
This will start producing graph_op in more cases, and inches towards strict deabstraction being on by default.

This will mostly be about updating testcases, which I'll iterate in the PR.

### CODE REVIEW

**Comment by lattner** [comment]
@swift-ci please test tensorflow

**Comment by lattner** [comment]
I expect this to fail a bunch of testcases, I'll iterate here in the PR and request review when I converge.

**Review by rxwei — APPROVED** [review]

**Comment by lattner** [comment]
@swift-ci please test tensorflow

**Comment by lattner** [comment]
@swift-ci please test tensorflow

**Comment by lattner** [comment]
@swift-ci please test tensorflow

**Review by mhong — APPROVED** [review]

**Pull request merged**
