### PR TITLE
Small update to diagnostics to avoid the word yet in disgnostics

### PR DESCRIPTION
**Pull request by ematejska**
Small improvements to diagnostics wording to avoid the word yet.

rdar://problem/16997751

### CODE REVIEW

**Comment by ematejska** [comment]
@swift-ci please test

**Comment by ematejska** [comment]
@swift-ci please smoke test

**Comment by ematejska** [comment]
@swift-ci please test linux

**Comment by shahmishal** [comment]
@swift-ci please clean test linux

**Review by jrose-apple — APPROVED** [review]

**Pull request merged**
