### PR TITLE
Add CHANGELOG entry for #34140

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
Couldn't come up with a decent example for Dictionary, but I guess that's fine. I also chose not to mention the subtle impact on conformances in non-final classes. I think we can document that once we have proper support for covariant `Self` inside classes. Right now the change affects only the contravariant case, which I found problematic to explain in isolation from an end user perspective.

### CODE REVIEW

**Review by slavapestov — APPROVED** [review]
Was there a JIRA bug for this one?

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by AnthonyLatsis** [comment]
> Was there a JIRA bug for this one?

None that I know of. I'll do a quick search. Do you want me to file one otherwise?

**Comment by slavapestov** [comment]
No, don't worry about it.

**Pull request merged**
