### PR TITLE
SILGen: Implement missing function conversions from tuples to Any

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes <https://bugs.swift.org/browse/SR-3267> and <rdar://problem/22465834>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by practicalswift** [comment]
Excellent! This is one of the oldest still open crashes around. Really nice to see this one fixed! Thanks! 💯

**Comment by slavapestov** [comment]
This is now part of #6484.

**Pull request closed without merging**
