### PR TITLE
[lldb-moduleimport] Add the logic for testing getDeclBySymbolName().

### PR DESCRIPTION
**Pull request by dcci**
Adrian already found and reported a bug, which I'm going to fix
in a later commit. Eventually this will go away, but in the meanwhile,
we should add test for this codepath.

<rdar://problem/38720742>

(I also decided to sneak in another commit to address Jordan's post commit reviews).

### CODE REVIEW

**Comment by dcci** [comment]
@swift-ci please smoke test and merge

**Comment by adrian-prantl** [comment]
It looks like this is preventing any pull requests from getting through because the test fails on i386. Could you disable it for 32 bits until a proper fix is available?

**Comment by dcci** [comment]
https://github.com/apple/swift/pull/15432 should take care of this.

**Comment by dcci** [comment]
(and sorry)

**Pull request merged**
