### PR TITLE
[SourceKit] Report synthesized protocol conformances for DocSupport request. rdar://36882292

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@jrose-apple please notice the doc-info request doesn't report any protocol conformances on MyNSStringEnum. When you've fixed the root cause, the test should fail.

**Comment by jrose-apple** [comment]
It turned out not to be the same issue after all, sorry. :-(

**Comment by nkcsgexi** [comment]
@jrose-apple thanks for letting me know!

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by jrose-apple** [comment]
Ah, that makes sense! Retroactive whoops, glad the fix was straightforward.

**Pull request merged**
