### PR TITLE
[Runtime] Fix gatherWrittenGenericArgs crashing when description is NULL

### PR DESCRIPTION
**Pull request by mikeash**
rdar://problem/54775582
SR-11374

### CODE REVIEW

**Comment by mikeash** [comment]
@DougGregor Can you verify that this is the proper fix? I think this is just a missing NULL check but I want to double-check and make sure I'm not actually papering over the real problem.

**Review by DougGregor — APPROVED** [review]
An Objective-C class won't have a type descriptor (and won't have its generic parameters exposed as metadata in any way), so yes, this is a reasonable fix.

**Comment by mikeash** [comment]
Thanks Doug! That’s what I thought, but wanted to be sure I didn’t miss something.

**Comment by mikeash** [comment]
@swift-ci please test and merge

**Comment by mikeash** [comment]
@swift-ci please test and merge

**Comment by mikeash** [comment]
@swift-ci please test and merge

**Comment by mikeash** [comment]
@swift-ci please test and merge

**Pull request merged**
