### PR TITLE
docs: fix doc build error

### PR DESCRIPTION
**Pull request by eeckstein**

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci smoke test and merge

**Comment by eeckstein** [comment]
@swift-ci smoke test macOS

**Comment by martinboehme** [comment]
Thanks, but I'm wondering: Why is a "term not in glossary" warning ever treated as an error? I've just come back to an incomplete build because of this -- this seems suboptimal.

**Comment by martinboehme** [comment]
Realizing the right place to comment is not here but on the commit that introduced the breakage:

https://github.com/apple/swift/commit/e674ab81b34645f646a696e97cd6f7fc16355a25#diff-7a164fa79d24a3f9f06f784b29a3b41d

**Comment by harlanhaskins** [comment]
Oh, thank you! Apologies for this.

**Pull request merged**
