### PR TITLE
[Runtime] Provide ivar Metadata for ivar_getTypeEncoding()

### PR DESCRIPTION
**Pull request by johnno1962**
#### What's in this pull request?

A minor change to GenClass.cpp to populate at least some information about the type of ivars so it can be accessed by ivar_getTypeEncoding(). This sort of introspection is useful to implement automated JSON or databse table mapping into Swift objects and vice versa along with generic object inspectors.

It is not strictly correct in that it yields the type of the property but in practice this would be more useful as for object types the property accessors should be used to convert to/from an Objective-C accessible type anyway. It’s an improvement over the existing code which makes no attempt to provide information.

Tested by building toolchain and compiling a large project with a variety of Swift code. Also used from inside an example project containing largely the same code as is included in the test with this PR. Does not apply to Linux.
#### Resolved bug number:

rdar://17637431

### CODE REVIEW

**Comment by lattner** [comment]
@jckarter @slavapestov any thoughts?

**Comment by jckarter** [comment]
I defer to @gparker42. IIRC there are some ABI differences between what gets encoded for ivars and for properties, so we might need to pave another path through Clang to do this right. Greg, are the property type encodings compatible enough with ivars for this to work?

**Comment by slavapestov** [comment]
Hi @johnno1962, we are working on a Swift-native facility for introspection of class instances and values. In particular, your use case of knowing references contained inside a value is handled.

Take a look at https://github.com/apple/swift/blob/master/include/swift/SwiftRemoteMirror/SwiftRemoteMirror.h.

Perhaps if the new interface meets your requirements we don't need to mess around with ivar_getTypeEncoding() at all? As you noted, it cannot express all Swift types, in particular values types or generics.

**Comment by johnno1962** [comment]
Hi @slavapestov, looks like a step in the right direction. Reflection on a class seems like a must have feature to me. Given you can get the information this PR uses from property_getAttributes() if pressed I’ll close this PR now and await developments with SwiftRemoteMirror.h.

**Pull request closed without merging**
