### PR TITLE
isInvalid() Is Finally Semantic

### PR DESCRIPTION
**Pull request by CodaFi**
The `isInvalid()` bit is intended to be sync'd to the presence of an `ErrorType` in the interface type of a `ValueDecl` (for a regular `Decl`, it's kinda higgledy-piggledy).  Historically, this had to be handled in an ad-hoc manner and callers had to make sure to set both lest they leave invalid ASTs in an inconsistent state.  We even went so far as to teach the constraint solver to reset the invalid bit when it was unwinding which meant we had to track every single `ValueDecl`.

Instead, make this predicate ask for the interface type.  The setter now handles setting the interface type as well.  A *lot* of cleanup falls out of this one change:

- No more `!getInterfaceType() || isInvalid()` dances
- No more `PossiblyInvalidDecls`
- No more `setInvalid(); setInterfaceType(ErrorType::get())`
- A lot less `variable 'x' is not bound by any pattern` because we're actually invalidating the AST correctly!

A few places had to be patched up to break the new cycles this introduces, but serendipitously the cycle breaker in `getUnopenedTypeOfReference` appears to be unnecessary.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please test

**Comment by CodaFi** [comment]
@swift-ci please test source compatibility

**Comment by CodaFi** [comment]
@swift-ci please smoke test macOS platform

**Review by slavapestov — APPROVED** [review]

**Comment by CodaFi** [comment]
Love 2 have my build ICE'd

@swift-ci Please Test Source Compatibility Release

**Comment by CodaFi** [comment]
@swift-ci Please Test Source Compatibility Release

**Comment by CodaFi** [comment]
@swift-ci Please Test Source Compatibility Release

**Comment by CodaFi** [comment]
@swift-ci please test

**Comment by CodaFi** [comment]
@swift-ci please clean test macOS platform

**Comment by CodaFi** [comment]
@swift-ci please clean test macOS platform

**Comment by CodaFi** [comment]
@swift-ci Please Test Source Compatibility Release

**Comment by CodaFi** [comment]
This *finally* passes and naturally there's a merge conflict...

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
⛵️

**Pull request merged**
