### PR TITLE
[AST] Record invalid conformance for unsatisfied conformance requirement

### PR DESCRIPTION
**Pull request by rintaro**
Fixes a crash in code completion.

rdar://problem/43625800

### CODE REVIEW

**Comment by rintaro** [comment]
@DougGregor @slavapestov 
I'm not sure this is the ideal fix for the issue. Could you take a look?

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
Unfortunately I'm afraid this is probably not the right fix. There is an invariant here that the list of associated conformances should have the same size as the number of conformance requirements in the requirement signature, and it's being violated somehow. I suspect the caller of `NormalProtocolConformance::populateSignatureConformances()` is doing something wrong.

**Comment by slavapestov** [comment]
The problem is that `TypeChecker::checkGenericArguments()` doesn't invoke the listener at all for invalid constraints, so we end up skipping that index in the associated conformances array.

This means the subsequent (valid) conformances might also be at invalid offsets, which will cause problems elsewhere. I think the right solution is to fix checkGenericArguments(), and simply inserting checks of `isInvalid()` is going to be more error-prone because any time you forget such a check you run the risk of indexing the invalid array.

**Comment by slavapestov** [comment]
@rintaro Give this a shot (untested)

```
diff --git a/lib/AST/ProtocolConformance.cpp b/lib/AST/ProtocolConformance.cpp
index f2f03c6573..8aa7833c2b 100644
--- a/lib/AST/ProtocolConformance.cpp
+++ b/lib/AST/ProtocolConformance.cpp
@@ -530,7 +530,7 @@ void NormalProtocolConformance::setSignatureConformances(
   auto &ctx = getProtocol()->getASTContext();
   SignatureConformances = ctx.AllocateCopy(conformances);
 
-#if !NDEBUG
+#ifndef NDEBUG
   unsigned idx = 0;
   for (const auto &req : getProtocol()->getRequirementSignature()) {
     if (req.getKind() == RequirementKind::Conformance) {
@@ -578,7 +578,8 @@ NormalProtocolConformance::populateSignatureConformances() {
 
       // Allocate the buffer of conformance requirements.
       auto &ctx = self->getProtocol()->getASTContext();
-      buffer = ctx.AllocateUninitialized<ProtocolConformanceRef>(numConformanceRequirements);
+      buffer = ctx.AllocateUninitialized<ProtocolConformanceRef>(
+        numConformanceRequirements);
 
       // Skip over any non-conformance requirements in the requirement
       // signature.
@@ -600,11 +601,20 @@ NormalProtocolConformance::populateSignatureConformances() {
       other.owning = false;
     }
 
-    void operator()(ProtocolConformanceRef conformance){
+    ~Writer() {
+      if (!owning)
+        return;
+      while (!requirementSignature.empty())
+        (*this)(ProtocolConformanceRef::forInvalid());
+    }
+
+    void operator()(ProtocolConformanceRef conformance) {
       // Make sure we have the right conformance.
       assert(!requirementSignature.empty() && "Too many conformances?");
-      assert(conformance.getRequirement() ==
-               requirementSignature.front().getSecondType()->castTo<ProtocolType>()->getDecl());
+      assert(conformance.isInvalid() ||
+             conformance.getRequirement() ==
+               requirementSignature.front().getSecondType()
+                 ->castTo<ProtocolType>()->getDecl());
       assert((!conformance.isConcrete() ||
               !conformance.getConcrete()->getType()->hasArchetype()) &&
              "signature conformances must use interface types");

```

**Comment by rintaro** [comment]
@slavapestov Thanks for the explanation, and the patch!
Though, I'm wondering if this patch addresses your concern "the subsequent (valid) conformances might also be at invalid offsets, which will cause problems elsewhere.". Are we able to rely on the behavior that `checkGenericArguments()` exits early when it find any unsatisfied requirement?
https://github.com/apple/swift/blob/ae55481a0b13713168857004b644b035a7632b95/lib/Sema/TypeCheckGeneric.cpp#L978

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
We have assertions that the types line up, so if this ever changes we should find out.

**Review by slavapestov — APPROVED** [review]

**Comment by rintaro** [comment]
OK, thanks!

**Pull request merged**
