### PR TITLE
The initial version of the NonAtomicRC optimization pass.

### PR DESCRIPTION
**Pull request by swiftix**
#### What's in this pull request?

The initial version of the NonAtomicRC optimization pass.

Reference counting on non-escaping objects can be marked as non-atomic.

THIS IS A WORK IN PROGRESS. DON'T MERGE YET.
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [x] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by swiftix** [comment]
@swift-ci Please test

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by swiftix** [comment]
@swift-ci Please test

**Comment by swiftix** [comment]
@swift-ci Please benchmark

**Comment by swiftix** [comment]
@swift-ci Please benchmark

**Comment by rudkx** [comment]
@swiftix Is this still being worked on or can we close it out?

**Comment by swiftix** [comment]
The newer version was merged into master a while ago. Closing.

**Pull request closed without merging**
