### PR TITLE
[Parse] Create DiagnosticTransaction along with BacktrackingScope

### PR DESCRIPTION
**Pull request by rintaro**
to prevent duplicated diagnostics.

For instance, on `Int8(exactly: 0xG)`, the following error was emitted two times:

```
test.swift:1:21: error: expected a digit after integer literal prefix
_ = Int8(exactly: 0xG)
                    ^
test.swift:1:21: error: expected a digit after integer literal prefix
_ = Int8(exactly: 0xG)
                    ^
```

In this change,
`DiagnosticTransaction` is committed on `BacktrackingScope::cancelBacktrack()`,
or aborted during `BacktrackingScope` destruction.

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
This PR will affect the testcase of #5270.
Either one should be merged first.
CC: @DougGregor @CodaFi

**Comment by CodaFi** [comment]
Could you merge this one first please?  I already have to edit the diagnostics in #5270 anyway.

**Comment by DougGregor** [comment]
LGTM! I'll go ahead and merge so @CodaFi can land his change.

**Pull request merged**
