### PR TITLE
query string fetching for URL.swift

### PR DESCRIPTION
**Pull request by ImanX**
add a function for simply fetch from URL path query strings

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by parkera** [comment]
Hi @ImanX: is your intent here to add new API to Foundation's URL type? The process to follow here is to make a pitch on the forums first.

**Comment by ImanX** [comment]
Hi @parkera  
Yes, URL class need to this API or function to simply fetching query strings in my opinion.
What your mean forums?
Where is forums? What is url address?

**Comment by parkera** [comment]
Try here: forums.swift.org

**Comment by ImanX** [comment]
@parkera do we must create new topic If we wanna add a new API or function ? 
could not we add func by Pull request ?

**Comment by parkera** [comment]
We have an extensive API review process we follow for all new Foundation API. The first step in that would be a pitch on the forums. If it gains traction there, we can talk about what the next steps are after that. Thanks.

**Comment by ImanX** [comment]
@parkera OK , Thanks

**Pull request closed without merging**
