### PR TITLE
[stdlib] add a fast path to UMRBP.initialize(as:from:)

### PR DESCRIPTION
**Pull request by glessard**
Add fast path via `withContiguousStorageIfAvailable` and `_copyContents` for `UnsafeMutableRawBufferPointer.initialize(as:from:)`.
The current implementation just copies element-by-element, and the performance could be better.

Resolves SR-14982 (rdar://81168547)

### CODE REVIEW

**Comment by glessard** [comment]
@swift-ci please benchmark

**Comment by glessard** [comment]
@swift-ci please smoke test

**Comment by glessard** [comment]
@swift-ci please test Windows platform

**Comment by glessard** [comment]
@swift-ci please benchmark

**Comment by atrick** [comment]
btw, there's something wrong with the `DictionaryOfAnyHashableStrings_insert`. It regresses arbitrarily on CI. No one has gotten around to investigating and disabling it

**Comment by glessard** [comment]
@swift-ci please benchmark

**Comment by glessard** [comment]
@swift-ci please smoke test

**Review by lorentey — CHANGES_REQUESTED** [review]
I think I caught a potential memory management issue; see review comment.

**Review by atrick — COMMENTED** [review]
The approach of guarding customizations that use `wCSIA` or `_copyContents` under `Collection` conformance seems like a nice way to simplify the implementation.

**Comment by glessard** [comment]
This has been resolved in a different way in [SE-0370](https://apple.github.io/swift-evolution/#?proposal=SE-0370), by implementing a separate method to initialize from a collection: `UnsafeMutableRawBufferPointer.initialize(as:fromContentsOf:)`.

**Pull request closed without merging**
