### PR TITLE
[SR-4978] Fix compiler crash for malformed ASTs

### PR DESCRIPTION
**Pull request by ghost**
Resolves [SR-4978](https://bugs.swift.org/browse/SR-4978).

### CODE REVIEW

**Comment by contraultra** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
Do you mind adding a test case?

**Comment by contraultra** [comment]
New to this but I will try to have a go at it

**Comment by jrose-apple** [comment]
Thanks, Nate! I think for the test you'd just want to have a file with a bunch of those declarations at the top level (`init`, `deinit`, `case` etc.). You can add them to tests/NameBinding/reference-dependencies-errors.swift, then check that the test fails before your change and succeeds after it. (There's information on how to run a single test in docs/Testing.rst.)

**Comment by contraultra** [comment]
Thank you Jordan for the direction. Tested.

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Review by jrose-apple — APPROVED** [review]

**Pull request merged**
