### PR TITLE
[polymorphic-builtin] Fix ASAN error.

### PR DESCRIPTION
**Pull request by gottesmm**

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test asan

**Comment by gottesmm** [comment]
@swift-ci asan test

**Comment by davezarzycki** [comment]
Hi @gottesmm – I can’t test this until tomorrow at the earliest. I hope that’s okay

**Comment by gottesmm** [comment]
@davezarzycki I wasn't going to ask you to test this. I hit the same error locally with ASAN. If the ASAN test here passes I feel comfortable merging. I just wanted to give you the heads up that I have a fix.

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
failure on osx is not mine:

7:38     Swift(macosx-x86_64) :: Python/python-lint.swift

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Comment by gottesmm** [comment]
I tested this locally and it fixed the ASAN error for me locally. The asan bot itself seems not to be working now. I am merging to unblock the build.

**Pull request merged**
