### PR TITLE
Get update-checkout working on Windows

### PR DESCRIPTION
**Pull request by hughbe**
So this is *grim*.

### Problem
The internal implementation of forking on Windows calls `find_module(sys.modules[__name__], ...)`. 

However, `sys.modules[__name__]` == `update-checkout`. `update-checkout` is **not a valid python module name**, as it contains `-` and doesn't end with `.py`.

This means that Python is not able to find the module `update-checkout`, and can't continue forking, as seen in this error log:
```sh
C:\Users\hughb\Documents\GitHub\swift>python ./swift/utils/update-checkout -j=1
Running ``update_single_repository`` with up to 1 processes.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "C:\Python27\lib\multiprocessing\forking.py", line 503, in prepare
    file, path_name, etc = imp.find_module(main_name, dirs)
ImportError: No module named update-checkout
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "C:\Python27\lib\multiprocessing\forking.py", line 503, in prepare
    file, path_name, etc = imp.find_module(main_name, dirs)
ImportError: No module named update-checkout
...
```

### Fix
The fix here is to move the contents of `update-checkout` to a file called `update_checkout`. Since we want to preserve `update-checkout`, we call `update_checkout.main()` from `update-checkout`.

However (ugh), internally, Python doesn't use the current module when forking. Nope, it uses the original module when forking (remember `sys.modules[__name__]`?). This means that we need to manually set `sys.modules[__name__]`:
```py
sys.modules[__name__] = sys.modules['update_checkout']
```
An alternative would be to call `subprocess.call` but this is complicated

### CODE REVIEW

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by hughbe** [comment]
> /tmp/hudson3342152727912985048.sh: line 62: /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/swift/utils/update-checkout: Permission denied

Looks like I've reset the `chmod` permissions for `update-checkout`

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by erg** [comment]
@hughbe Your solution looks pythonic.

When I tried ``update-checkout`` on Windows it complained that my timeout was too high. (The timeout is a hack that allows ``map_async`` to handle ctrl-c correctly instead of just getting into an unstoppable loop.)

I wonder why my Windows rejected the timeout and yours did not. Maybe you could remove a single 9 in these places:

```
coverage/coverage-touch-tests
129:    ).get(9999999))

coverage/coverage-generate-data
228:    pool.map_async(merge_profdir, folders).get(9999999)
232:    pool.map_async(dump_coverage_data, merged_profraw_files).get(9999999)
236:    pool.map_async(demangle_coverage_data, coverage_log_files).get(9999999)

swift_build_support/swift_build_support/shell.py
232:    results = pool.map_async(func=fn, iterable=pool_args).get(9999999)
```

**Comment by hughbe** [comment]
`update_checkout.py` completely works on my Windows box with this change, but I'll dive in and check

**Comment by hughbe** [comment]
@erg do you have a sample log for your error? I'm on python 2.7.12, Windows 10 64 bit. Not sure if those specs matter

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by erg** [comment]
@hughbe I can try again this weekend and see exactly which python version and Windows 10 versions and even get the exact error message.

**Review by erg — APPROVED** [review]
Looks good now!

**Comment by erg** [comment]
@hughbe I'm using 32bit python on 64bit Windows 10.

I can make it fail with:

``OverflowError: timeout value is too large``

Or with a larger timeout:

``OverflowError: timestamp too large to convert to C _PyTime_t``

**Pull request merged**
