### PR TITLE
[Sema] NFC: Do one cache lookup instead of three

### PR DESCRIPTION
**Pull request by davezarzycki**
@swift-ci please smoke test

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Review by DougGregor — APPROVED** [review]
LGTM

**Comment by davezarzycki** [comment]
How long does it take for Swift CI to notice test requests?

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test

**Comment by harlanhaskins** [comment]
Looks like it just missed that one. @shahmishal?

**Comment by rjmccall** [comment]
Usually it either responds within a few seconds or it's just completely missed it and you need to ask again.  Also, if it doesn't recognize your request, it will just silently ignore it, so don't get too cute. :)

**Comment by harlanhaskins** [comment]
I'm still a big fan of @swift-ci please fix

**Pull request merged**
