### PR TITLE
[4.0] [QoI] Improve contextual error diagnostics related to calls

### PR DESCRIPTION
**Pull request by xedin**
* Description: Currently some contextual errors are discovered too late
                       which leads to diagnostics of unrelated problems like argument
                       mismatches, these changes attempt to improve the situation
                       and try to diagnose contextual errors related to calls
                       before everything else.

* Scope of the issue: diagnostic improvements for contextual errors related to calls.

* Risk: Low.

* Tested: New test cases added, Swift CI.

* Reviewed by: Mark Lacey.

* Resolves: SR-5045, rdar://problem/32934129

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@rudkx please review for 4.0

**Review by rudkx — APPROVED** [review]
LGTM!

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Pull request merged**
