### PR TITLE
[cxx-interop] Implicitly import `Cxx` module

### PR DESCRIPTION
**Pull request by egorzhdan**
This lifts the requirement for the user to explicitly add `import Cxx` in Swift code that relies on protocols from the `Cxx` module, such as `CxxSequence`.

### CODE REVIEW

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by stevapple** [comment]
Should we rename it to `_Cxx` to align with other implicitly imported "standard" libraries?

**Comment by egorzhdan** [comment]
@stevapple underscored names are generally used for something the developer wouldn't need to reference directly from Swift code. This module could be referenced directly, for example, if someone needs to provide a utility extension to one of the protocols from `Cxx` module:
```swift
// Util.swift
import Cxx

extension CxxSequence where RawIterator: ... {
  func doSomething() { ... }
}
```
Note that we don't _always_ implicitly import `Cxx`, we only do that for C++ modules that are being imported into Swift, so without `import Cxx` the above snippet wouldn't compile.

**Comment by stevapple** [comment]
Ah, makes sense👌

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Review by zoecarver — APPROVED** [review]
Thanks for fixing all these tests!

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
Hooray, makes a lot of sense +1

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test macOS

**Pull request merged**
