### PR TITLE
[PropertyWrappers] Fix lvalue computation in buildStorageReference

### PR DESCRIPTION
**Pull request by theblixguy**
When computing whether the immediate access to a property wrapper requires an lvalue, use `getPropertyWrapperMutability()` (which takes wrapper composition into consideration), instead of the first underlying property's mutating-ness. Otherwise, we will crash in SILGen if the first wrapper is a struct and the second is a class for example.

Resolves [SR-11603](https://bugs.swift.org/browse/SR-11603).
Resolves rdar://problem/56255391

### CODE REVIEW

**Review by beccadax — APPROVED** [review]
Looks about right to me. Thanks for the fix!

**Comment by theblixguy** [comment]
@swift-ci please smoke test

**Comment by theblixguy** [comment]
Hmm we're hitting an assert in SILGenApply when compiling with `-primary-file`, but not otherwise.

**Review by DougGregor — APPROVED** [review]
Looks great, thank you!

**Comment by theblixguy** [comment]
@swift-ci please smoke test

**Comment by theblixguy** [comment]
@swift-ci please smoke test

**Review by DougGregor — APPROVED** [review]

**Comment by theblixguy** [comment]
Found another bug - if the `wrappedValue` has a mutating getter and a non-mutating setter & the property wrapper var is inside a struct, then we have the same crash. So, we need to perform the same checks for `isSelfLValue` as well.

**Comment by theblixguy** [comment]
@swift-ci please smoke test

**Review by DougGregor — APPROVED** [review]
Keeps getting better, thank you!

**Comment by theblixguy** [comment]
Unfortunately that didn't fix the crash for that specific scenario me locally :/ On Swift 5.1, we flag it as an error i.e `cannot assign to property: 'self' is immutable`. Am I missing something @DougGregor?

**Comment by brentdax** [comment]
@theblixguy If you’re not sure what to do at this stage, I would set a breakpoint on the line where we diagnose that error, then when you hit that breakpoint, dump the AST so you can see what the compiler is working on. That might give you a better idea of what code we’re generating incorrectly.

**Comment by theblixguy** [comment]
@brentdax It seems like we are crashing when emitting the setter for `text` (see the 2nd test case) for the same reason the code in the SR was crashing. Note that this happens with and without my changes, so it's not something that's caused by the new logic.

The mutating-ness of the getter is the deciding factor here - if the getter is nonmutating, then we don't crash, otherwise we do. Strangely, this is the _only_ combination (of mutating-ness, wrapper being struct/class and wrapper property being in a struct/class) that crashes, so there's definitely something funny going on!

I think that this is a bug elsewhere, because the AST for the setter looks the same, minus missing type information on Swift 5.1 (release) because of the error. I think I'll get this change in and then investigate and fix this specific issue in a follow-up PR.

**Comment by theblixguy** [comment]
@swift-ci please smoke test

**Comment by theblixguy** [comment]
@swift-ci please smoke test

**Pull request merged**
