### PR TITLE
[stdlib/private][os log] Simplify the OSLogPrototype private module and eliminate the dependency on os overlay.

### PR DESCRIPTION
**Pull request by ravikandhadai**
This PR simplifies the OSLogPrototype private module to contain only code necessary for testing the compiler optimizations and diagnostics. This commit comprises the following changes:

1. Rename the OSLogPrototype module to OSLogTestHelper and rename the files.
2. Make the private module: OSLogTestHelper independent of os overlay.
3. Simplify the os log test suites and make them not perform logging.
4. Enable the os log test suites on all platforms.

<rdar://problem/60542172>

### CODE REVIEW

**Comment by ravikandhadai** [comment]
@swift-ci please test

**Comment by ravikandhadai** [comment]
@swift-ci Please test

**Comment by ravikandhadai** [comment]
@swift-ci please test

**Comment by ravikandhadai** [comment]
@swift-ci Please test

**Comment by ravikandhadai** [comment]
@swift-ci Please test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Pull request merged**
