### PR TITLE
[SourceKit] Add local variables to structure (SR-5057)

### PR DESCRIPTION
**Pull request by marcelofabri**
Reopening #11262 to make @swift-ci work 🙏.

// cc @nkcsgexi 

---

This PR includes local variables (`source.lang.swift.decl.var.local`) to structures provided by SourceKit. This also makes variables declared in `for` and `while` statements available in the structure.

Resolves [SR-5057](https://bugs.swift.org/browse/SR-5057).

This is super important for [SwiftLint](https://github.com/realm/SwiftLint), as you can see on https://github.com/realm/SwiftLint/issues/136 and all duplicated issues. I'm not sure if there's a historical reason for this not be included until now.

### CODE REVIEW

**Comment by felix91gr** [comment]
Thank you for working on SourceKit 🙌🏻

**Comment by shahmishal** [comment]
@marcelofabri Thanks!

**Comment by shahmishal** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
@swift-ci please test macOS

**Comment by shahmishal** [comment]
@swift-ci test macOS

**Review by nkcsgexi — APPROVED** [review]
I've reviewed this in the previous PR. LGTM!

**Pull request merged**
