### PR TITLE
[sil.rst] Update Ownership SSA section given further feedback

### PR DESCRIPTION
**Pull request by gottesmm**
Just some more edits after an offline discussion between Andy and I.

I folded in the change from #35161.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Review by atrick — APPROVED** [review]
Much better, thanks!

**Comment by gottesmm** [comment]
@swift-ci smoke test OS X platform

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Pull request merged**
