### PR TITLE
 Allow declarations to opt in to suppressing `@isolated(any)` instead of suppressing the entire declaration

### PR DESCRIPTION
**Pull request by rjmccall**
This PR also includes a significant NFC improvement to how we use suspended diagnostics in the parser.

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please test

**Review by ahoppen — COMMENTED** [review]
Could you also add a test case for this in the new parser?

**Comment by rjmccall** [comment]
@swift-ci Please test macOS

**Comment by rjmccall** [comment]
@swift-ci Please smoke test

**Comment by rjmccall** [comment]
@swift-ci Please smoke test Linux

**Pull request merged**
