### PR TITLE
Remove pinning in reference counting and pinning runtime entry points

### PR DESCRIPTION
**Pull request by eeckstein**
rdar://problem/35401813

plus some minor follow-ups from my previous remove-pinning PR.

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci please smoke benchmark staging

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci test

**Review by gparker42 — APPROVED** [review]
Good.

**Pull request merged**
