### PR TITLE
Fixed the broken table of markdown.

### PR DESCRIPTION
**Pull request by oden**
Added one space character to fix a broken table as markdown of github.

### CODE REVIEW

**Comment by oden** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
Pull requests targeting 3.1 branch are usually cherry-picked, and at this point are supposed to be [critical fixes](https://swift.org/blog/swift-3-1-release-process/#pull-requests-for-release-branch).  If you want a shot for this to be included, please cherry-pick #8200.

**Comment by louisdh** [comment]
Swift 3.1 is now [officially released](https://swift.org/blog/swift-3-1-released/), can this be closed?

**Comment by CodaFi** [comment]
It can.

**Pull request closed without merging**
