### PR TITLE
[test] Shortened filenames for Windows.

### PR DESCRIPTION
**Pull request by nate-chandler**

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please smoke test and merge

**Comment by nate-chandler** [comment]
@swift-ci please smoke test windows

**Comment by nate-chandler** [comment]
@compnerd It looks like the clone was successful.

**Review by compnerd — APPROVED** [review]
Thanks!

**Comment by nate-chandler** [comment]
@swift-ci please smoke test and merge

**Comment by compnerd** [comment]
@swift-ci please smoke test and merge

**Comment by compnerd** [comment]
@swift-ci please test windows platform

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by nate-chandler** [comment]
@swift-ci please smoke test linux platform

**Comment by nate-chandler** [comment]
@swift-ci please smoke test linux platform

**Pull request merged**
