### PR TITLE
Enforce consistent usage of -experimental-hermetic-seal-at-link flag

### PR DESCRIPTION
**Pull request by kubamracek**
We've recently added the `-experimental-hermetic-seal-at-link` compiler flag, which turns on aggressive dead-stripping optimizations and assumes that library code can be optimized against client code because all users of the library code/types are present at link/LTO time. This means that any module that's built with `-experimental-hermetic-seal-at-link` requires all clients of this module to also use `-experimental-hermetic-seal-at-link`. This PR enforces that by storing a bit in the serialized module, and checking the bit when importing modules.

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test Windows platform

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test Windows platform

**Review by eeckstein — COMMENTED** [review]
basically lgtm. Can you add some comment(s) on what this option is about?

**Comment by kubamracek** [comment]
Added comments into code, into the commit message and into the PR description :)

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by eeckstein — APPROVED** [review]

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test Windows platform

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Pull request merged**
