### PR TITLE
[4.2] Fix order of operations when a mutating method invoked on an existential returns Self.

### PR DESCRIPTION
**Pull request by jckarter**
Explanation: The compiler would crash when invoking a mutating method that returns `Self` on an existential.

Scope: Regression from 4.1

Issue: rdar://problem/43507711

Risk: Moderate-low; the fix affects order of operations for potentially all existential codegen in a way that should be benign.

Testing: Test case from Radar, test suite, source compatibility suite, benchmark suite

Reviewed by: @slavapestov

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test OS X

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test Linux

**Comment by jckarter** [comment]
@swift-ci Please test source compatibility

**Comment by jckarter** [comment]
@swift-ci Please nominate

**Comment by slavapestov** [comment]
LGTM

**Pull request merged**
