### PR TITLE
[ConstraintSystem] Fail `~=` synthesis if constraint generation fails

### PR DESCRIPTION
**Pull request by xedin**
If constraint generation for application of `~=` failed, that should
result in an immediate synthesis failure.

Also add `LLVM_NODISCARD` to `generate*` methods
to make it harder to make such a mistake in the future.

Resolves: rdar://92366212

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Review by hborla — APPROVED** [review]

**Comment by xedin** [comment]
@compnerd I didn't know that `__attribute__ ((warn_unused_result))` is not supported on Windows, should I make it a macro or is there a better option?

```
C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\include\swift/Syntax/Syntax.h(505): warning C4996: 'swift::syntax::RawSyntax::dump': only for use in the debugger
C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\include\swift/Sema/ConstraintSystem.h(4591): error C2059: syntax error: '('
C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\include\swift/Sema/ConstraintSystem.h(4591): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\include\swift/Sema/ConstraintSystem.h(4591): error C2059: syntax error: ')'
C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\include\swift/Sema/ConstraintSystem.h(4591): error C2059: syntax error: ')'
C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\include\swift/Sema/ConstraintSystem.h(4592): warning C4183: '__attribute__': missing return type; assumed to be a member function returning 'int'

```

**Comment by compnerd** [comment]
Everything spelt with `attribute` is unavailable as that is a GNU extension (similar to how `declspec` is unavailable on Darwin).  I would prefer the standard `[[nodiscard]]` which should work on everything, though there might be a vestigial `LLVM_NODISCARD` macro.

**Comment by xedin** [comment]
@compnerd Thanks! I'll give it a try right now

**Comment by xedin** [comment]
`LLVM_NODISCARD` is what I have been looking for...

**Comment by xedin** [comment]
@swift-ci please test

**Pull request merged**
