### PR TITLE
Fix canImport submodule checking in loaders not supporting submodules

### PR DESCRIPTION
**Pull request by ApolloZhu**
Changes all module loaders that cannot load submodules to return false when checking if it canImport a submodule. `CompilerInstance::setUpModuleLoaders` in `Frontend.cpp` mentions that there are 6 types of loaders, and they are all fixed with changes in this PR (or don't need to be fixed):

- [x] `SourceLoader` (already working, but changed to use `hasSubmodule()` for consistency)
- [x] `MemoryBufferSerializedModuleLoader`
- [x] `ExplicitSwiftModuleLoader`
- [x] `ModuleInterfaceLoader`
- [x] `ImplicitSerializedModuleLoader` (handled in `SerializedModuleLoaderBase`)
- [x] `ClangImporter` (already working, no change)

## Why?

As implemented in #34094, when checking `canImport(CoreImage.Anything)`, because `CoreImage` is a serialized framework, SerializedModuleLoader checked if it can import CoreImage (ignoring submodule path) and incorrectly return true. I discovered this issue after trying out the latest toolchain, thus this fix + a test involving a submodule in a mixed framework (where multiple module loaders can import the top module).

I ran the new test using the unfixed implementation, and indeed it doesn't pass:

```
$ swift --version
Apple Swift version 5.6-dev (LLVM 031406b6cea8006, Swift 9f7d3fccad66d76)
Target: x86_64-apple-macosx12.0
$ swift-frontend -typecheck -verify -disable-objc-attr-requires-foundation-module can_import_submodule_in_framework.swift -F .
can_import_submodule_in_framework.swift:23:8: error: expected error not produced
    // expected-error@-1 {{cannot find 'fromSubmodule' in scope}}
~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
zsh: exit 1     swift-frontend -typecheck -verify  can_import_submodule_in_framework.swift -F
```

### CODE REVIEW

**Comment by WowbaggersLiquidLunch** [comment]
@swift-ci please smoke test

**Comment by ApolloZhu** [comment]
@CodaFi would you mind taking a look at this when you have time?

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by ApolloZhu** [comment]
Seems that the tests have passed and this is still mergeable. Let me know if there are additional changes needed.

**Comment by ApolloZhu** [comment]
@CodaFi do you think it's possible for us to merge this before the [Swift 5.7](https://forums.swift.org/t/swift-5-7-release-process/56316) cut-off date (April 4th), so we can ship a less buggy version in that release?

**Comment by ApolloZhu** [comment]
Rebased on top of main, tested locally and everything still works, hopefully now Windows platform CI check won't fail

**Comment by xwu** [comment]
@swift-ci test

**Comment by ApolloZhu** [comment]
CI status update: all existing checks have passed

**Comment by xwu** [comment]
cc @beccadax as the last person to work on some of these files, in case there's other more appropriate reviewers

**Comment by ApolloZhu** [comment]
Created https://github.com/apple/swift/pull/42179 for potential inclusion in the Swift 5.7 release.

**Review by DougGregor — APPROVED** [review]

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
The change looks good to me. Kicking off another CI round to merge it in, thank you!

**Pull request merged**
