### PR TITLE
IRGen: Mask all spare bits in multi-payload enums when injecting the tag.

### PR DESCRIPTION
**Pull request by jckarter**
Single-payload enum layout unfortunately assumes that constructing the payload case is a no-op, such
as when building Optional.some(x) for a value x. For multi-payload enums, now that we use the unused
spare bits to form extra inhabitants when the enum is in turn wrapped in an Optional or other single-
payload enum, this means we have to zero all of those bits. The spare bits may have been selected from
intra-field or tail padding bytes that are undefined in the underlying payload types. Fixes
rdar://problem/47635801.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test source compatibility

**Comment by aschwaighofer** [comment]
The test failure on Mac OS X looks unrelated. It also happens on at least one of the bots:
https://ci.swift.org/job/oss-swift_tools-RA_stdlib-DA_test-simulator/550/testReport/Swift(iphonesimulator-i386)/stdlib/KVOKeyPaths_swift/

**Comment by aschwaighofer** [comment]
Oh, it also fails the PR tester bot https://ci.swift.org/job/oss-swift-pr-test/6059/testReport/Swift(iphonesimulator-i386)/stdlib/KVOKeyPaths_swift/

We should disable the test to unblock PR merging.

**Comment by aschwaighofer** [comment]
https://bugs.swift.org/browse/SR-9838 I am going to disable the test on i386

**Review by aschwaighofer — APPROVED** [review]
LGTM

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test OS X

**Pull request merged**
