### PR TITLE
[Diagnostics] Make sure that fixes associated with function builders …

### PR DESCRIPTION
**Pull request by xedin**
…are found and diagnosed

Current logic in `applySolutionFixes` didn't actually look inside
of single-expression closures (because of brace statement) or
closures which are transformed by function builders.

Resolves: rdar://problem/51167632

### CODE REVIEW

**Review by DougGregor — APPROVED** [review]
Very nice!

**Comment by xedin** [comment]
I have simplified this a bit more and now instead of using sub-walker it just replaces original closure expression with transformed.

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
full macOS build failed with unrelated unexpected warning on 32-bit platform in `test/attr/require_explicit_availability.swift` - `<unknown>:0: error: unexpected warning produced: using sysroot for ‘iPhoneSimulator’ but targeting ‘MacOSX’`

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Pull request merged**
