### PR TITLE
[IRGen] Cond. conformance witness table count isn't needed dynamically.

### PR DESCRIPTION
**Pull request by huonw**
The count of the number of witness tables was designed to be an
assertion/check that we've hooked up all the infrastructure
correctly. Everything is now implemented, and the assertion has never
triggered, so it can be removed, saving some work.

### CODE REVIEW

**Comment by huonw** [comment]
@swift-ci please smoke test

**Comment by huonw** [comment]
This changes the code from passing a `swift.witness_table_slice*` to passing a `witness_table**` (i.e. a pointer to an array of witness table pointers, which ends up being a `void***`) to the `void ** instantiationArgs` argument of `swift_getGenericWitnessTable`. This seems like a moderately unusual argument type (that is, plain `void *` is more conventional for context parameters IME) which makes me think there was reasoning for that particular choice, but it seems like it wasn't used until conditional conformances, nor changed since it was introduced. I'm inclined to change the argument to `void ***` instead, and make the compiler code and IR slightly simpler, but would like confirmation that this fits with the design.

@rjmccall it looks like you introduced this scheme originally, so maybe you're best positioned to comment on the above?

**Comment by rjmccall** [comment]
You're not talking about changing anything about the actual bits we're passing, right?  I don't really care about the exact pointer type we use in the function's IR declaration; if i8*** is convenient, and I agree that it probably is, then let's go with that.

**Comment by huonw** [comment]
This is changing the bits, slightly: when I first implemented conditional conformances, it did something like

```cpp
struct WitnessTableSlice {
    WitnessTable **requirements;
    size_t count;
};
size_t count = ...;
WitnessTable *conditionalRequirements[count] = { ... };
WitnessTableSlice slice = { conditionalRequirements, count };
swift_getGenericWitnessTable(..., (void**)&slice);
```

But now it does

```cpp
WitnessTable *conditionalRequirements[count] = { ... };
swift_getGenericWitnessTable(..., (void**)conditionalRequirements);
```

But, those (currently, at least) just get passed straight through to the instantiation function, which is also controlled by the code that decides the format for that argument, so the exact format of the data doesn't seem like it matters for ABI.

**Comment by rjmccall** [comment]
Well, the runtime should in theory be able to inspect all the witness tables being passed in; consider that we might want to do dynamic partial specialization of the conformance or something.  But it also seems to me that, much like getGenericMetadata, the length of that array should be fixed for any given generic witness table, so it doesn't need to be passed in separately.

**Comment by rjmccall** [comment]
Which is to say that I agree that this change is a good one.

**Comment by huonw** [comment]
@swift-ci please test

**Comment by huonw** [comment]
@swift-ci please test

**Comment by huonw** [comment]
@swift-ci please smoke test

**Comment by huonw** [comment]
@swift-ci please smoke test

**Comment by huonw** [comment]
@swift-ci please smoke test.

**Pull request merged**
