### PR TITLE
Documentation: move the `@_specialize` discussion into proposals/UnsupportedOptimizationAttributes.rst

### PR DESCRIPTION
**Pull request by atrick**
proposals/UnsupportedOptimizationAttributes.rst.

### CODE REVIEW

**Comment by atrick** [comment]
@swiftix, once this is in, can you update the description to explain the current state of `@_specialize`, then decide if we should pick the docs changes onto 4.0?

**Comment by swiftix** [comment]
@atrick Sure.

**Review by swiftix — APPROVED** [review]

**Comment by jrose-apple** [comment]
Thanks, Andy!

**Comment by swiftix** [comment]
@swift-ci please smoke test and merge

**Comment by swiftix** [comment]
@atrick I added some documentation about `@_specialize` in https://github.com/apple/swift/pull/10095

**Comment by dabrahams** [comment]
@swiftix …which I then had to revert.  Did you ever get that straightened out?

**Comment by swiftix** [comment]
@dabrahams You reverted the #10073.  Afterwards I  submitted and merged a fixed PR #10095

**Pull request merged**
