### PR TITLE
[stdlib] Temporarily exclude DoubleWidth from the standard library

### PR DESCRIPTION
**Pull request by moiseev**

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
@swift-ci Please smoke benchmark

**Comment by moiseev** [comment]
@swift-ci please smoke test compiler performance

**Comment by jrose-apple** [comment]
I'm pretty sure the arithmetic operators are supposed to stay transparent for both overflow analysis and debug info. I'm not sure why you'd see a difference between `_transparent` and `inline(__always)` either.

**Comment by moiseev** [comment]
@jrose-apple early inlining, more convoluted code, less optimization? I don't honestly know. But evidence is that it helps. As for the overflow diagnostics, there are tests that should show if we regress.

**Comment by jckarter** [comment]
IIRC some of the overflow diagnostic tests were already broken by other work you all did last year; have those been restored yet?

If removing `@_transparent` really saves a significant amount of binary size, can we make transparent things always-emit-into-client? The symbols ought to be rarely needed in practice since they'll almost always be inlined.

**Comment by jrose-apple** [comment]
Looks like only one debug info test failed; we should probably have more. You really can't remove `_transparent` here; [this is what it was made for](https://github.com/apple/swift/blob/master/docs/TransparentAttr.rst).

**Comment by moiseev** [comment]
The problem is not with transparent per se. It’s saving some space in the implementation of `DoubleWidth`. But it’s not enough. So I’ll just leave it as is, until we have a better solution.

And no, those overflow diagnostics tests have not been fixed, and I am very aware of that =(

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by moiseev** [comment]
@swift-ci Please test and merge

**Comment by natecook1000** [comment]
@swift-ci Please test and merge

**Pull request merged**
