### PR TITLE
Adding macOS alias for conditional compilation blocks

### PR DESCRIPTION
**Pull request by erica**
Alias OSX to macOS for conditional compilation blocks `os()` test

Starting in Sierra, Apple's Mac-based OS (OS X) will be renamed "macOS".
The `#if os(OSX)` test should be aliased to `#if os(macOS)`.

With any luck, I've managed to do this right.. 
#### Resolved bug number: ([SR-1823](https://bugs.swift.org/browse/SR-1823))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by karwa** [comment]
Maybe add a test?

**Comment by jakepetroules** [comment]
👍

**Comment by erica** [comment]
I duplicated test/Parse/ConditionalCompilation/x64OSXTarget.swift and updated the condition from OSX to macOS

**Comment by gribozavr** [comment]
Why not add to the existing test file?  (Every test has a non-zero startup cost, adding to existing tests is cheaper.)

**Comment by erica** [comment]
@gribozavr because I'm unsure of the protocol and this is my first (technically my second, but the first time just added a line of text) time doing a code submission

**Comment by gribozavr** [comment]
It would be best to add the tests to the existing file.

**Comment by erica** [comment]
@gribozavr And done

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by gribozavr** [comment]
@erica Please take a look at the test issues.

**Comment by jrose-apple** [comment]
Unfortunately, addPlatformConditionValue doesn't support multiple values for the *same* condition. (It should probably assert that.) I think we need to canonicalize to a particular value before checking it.

If you're busy with other things I can take this on from your starting point.

**Comment by rintaro** [comment]
@jrose-apple 
`LangOptions:: PlatformConditionValues` does contain multiple values.
I added one commit on @erica 's change: https://github.com/apple/swift/compare/master...rintaro:SR-1823
It seems to work. How do you think about this?

**Comment by jrose-apple** [comment]
Right, we only *expect* one value. I admit I didn't think of changing the matcher to search the whole list instead of just getting the first one, but I think we should keep it unique for now and just canonicalize.

**Pull request closed without merging**
