### PR TITLE
Add RISCV to standard set of architectures for incremental buildbots

### PR DESCRIPTION
**Pull request by DougGregor**
I think this will unbreak the incremental buildbots

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Review by ktoso — APPROVED** [review]

**Comment by finagolfin** [comment]
You could also remove these two lines and [always just build the default set of architectures](https://github.com/apple/swift/blob/04f950c084e1fe4cb0066296a47613503aeaab28/utils/build_swift/build_swift/driver_arguments.py#L1262).

**Review by kubamracek — APPROVED** [review]

**Comment by DougGregor** [comment]
> You could also remove these two lines and [always just build the default set of architectures](https://github.com/apple/swift/blob/04f950c084e1fe4cb0066296a47613503aeaab28/utils/build_swift/build_swift/driver_arguments.py#L1262).

You're right, we should probably just do that instead. We're not likely to save ourselves much build time by limiting the architectures, but we will cause ourselves surprises like this.

**Pull request merged**
