### PR TITLE
Revert "[SwiftLexicalLookup] New unqualified lookup implementation validation"

### PR DESCRIPTION
**Pull request by bnbarham**
Reverts swiftlang/swift#77140 as it causes nightly toolchain failures for Debian 12/Fedora 39/Ubuntu 24.04.

### CODE REVIEW

**Comment by bnbarham** [comment]
@MAJKFL I believe the issue here is that there's now a cycle from swiftAST -> swiftParse/swiftSema -> swiftASTGen -> swiftAST. It passed on PR testing as it uses Ubuntu 20.04 and ends up using `lld` rather than `gold`, which appears to handle the cycle.

**Comment by bnbarham** [comment]
@swift-ci please smoke test

**Review by MAJKFL — APPROVED** [review]
Ah, I see there’s a cycle. Thank you for caching that! It does seem to be a bit tricky to fix. I don’t think it would be possible to move the validation outside of `ASTGen` as it uses it to e.g. access cached if config configured regions, or the parsed source file itself. 

Would it make sense to move the logic somewhere outside of `swiftAST`, or to possibly inject `LoggingASTScopeDeclConsumer` at all unqualified lookup entry points? If it’s not a viable option, do you perhaps have any suggestions for an alternative approach? @bnbarham @DougGregor 

I think it's a good idea to revert it for now and I'll look into fixing it in a subsequent PR.

**Comment by bnbarham** [comment]
> Would it make sense to move the logic somewhere outside of swiftAST, or to possibly inject LoggingASTScopeDeclConsumer at all unqualified lookup entry points

I think the easiest thing here would probably be to have a new Swift module, ie. move `LexicalLookup` out of `ASTGen`. I assume it's mostly just there out of convenience today?

**Comment by hjyamauchi** [comment]
I think the original PR introduces the new dll `_CompilerSwiftLexicalLookup.dll` and it needed to be added to the installer manifest around here https://github.com/swiftlang/swift-installer-scripts/blob/6cecc7c46d1170a3bc3e1ff8838181418e037397/platforms/Windows/bld/bld.wxs#L418 ?

**Comment by bnbarham** [comment]
Thanks @hjyamauchi, will indeed need to add to swift-installer-scripts too.

**Comment by rintaro** [comment]
I will see if we can extract ExportedSourceFile related code out of `ASTGen`, so `ASTGen` and the lexical lookup module depend on it.

**Pull request merged**
