### PR TITLE
[sil] Ban passing trivial values to copy_value, destroy_value.

### PR DESCRIPTION
**Pull request by gottesmm**
I also fixed a small violation in SILGenProlog/added a test for it.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
The linux failure is a .sil test that needs to be updated (it is actually violating in plain text what is happening here since the assertion happening in the SIL parser).

**Comment by gottesmm** [comment]
Debug source compat passed...

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by slavapestov** [comment]
You mean ban passing _trivial_ values?

**Comment by gottesmm** [comment]
@slavapestov yes. Sorry. My brain was tired.

**Pull request merged**
