### PR TITLE
[5.0][stdlib] Remove Swift 3-only Compatibility Shims

### PR DESCRIPTION
**Pull request by airspeedswift**
Cherry pick of #21019.

The ABI changes are false positives. These are method deletions and none have been callable since 3.0 support was removed.

Pulling this into 5.0 as it has library size benefits and found to improve some odd type diagnostic errors.

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@swift-ci please test source compatibility

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@swift-ci please test

**Review by AnnaZaks — APPROVED** [review]

**Review by milseman — APPROVED** [review]
LGTM

**Pull request merged**
