### PR TITLE
Terminology change: 'garbage' -> 'unexpected'

### PR DESCRIPTION
**Pull request by rintaro**
There are no "garbage" characters in Swift code. They are just "unexpected."

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please Python lint

**Comment by rintaro** [comment]
https://github.com/apple/swift-syntax/pull/593
@swift-ci Please smoke test

**Review by DougGregor — APPROVED** [review]

**Comment by rintaro** [comment]
https://github.com/apple/swift-syntax/pull/593
@swift-ci Please smoke test

**Comment by rintaro** [comment]
Added a few rewrites in comments

**Pull request merged**
