### PR TITLE
build: define an additional variable for configuration

### PR DESCRIPTION
**Pull request by compnerd**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

If we are building the stdlib with the just built toolchain, we need to ensure
that the tools directory is specified otherwise we try to invoke "/clang++" as
clang.

### CODE REVIEW

**Comment by compnerd** [comment]
CC @gottesmm @gribozavr

**Comment by gottesmm** [comment]
@compnerd What build did this come up in.

**Comment by compnerd** [comment]
@gottesmm Linux x86_64 D+A with building the stdlib with the just built toolchain.

**Comment by gottesmm** [comment]
@compnerd Can you give me a build-script line? I just want to understand what is actually going on here.

**Comment by gottesmm** [comment]
Also the linux platform would be good (i.e. 14.04 or 15.10).

**Comment by compnerd** [comment]
@gottesmm exherbo Linux with `BUILD_RUNTIME_WITH_HOST_COMPILER=0 swift/utils/build-script --foundation --debug --assertions --extra-cmake-options=-DCMAKE_AR=/usr/x86_64-pc-linux-gnu/bin/llvm-ar,-DPKG_CONFIG_EXECUTABLE=/usr/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-pkg-config`

**Comment by compnerd** [comment]
Haven't hit this recently; lets go ahead and close this for now.  We can always revive the changes if necessary.

**Pull request closed without merging**
