### PR TITLE
[gardening] Fix typos

### PR DESCRIPTION
**Pull request by koogawa**
* getTopLeveDecls -> getTopLevelDecls
* silModue -> silModule
* Evaludate -> Evaluate
* OptioanlPayload -> OptionalPayload
* confromance -> conformance
* chcking -> checking
* settting -> setting
* tpye -> type
* resoved -> resolved
* ahve -> have ? 🤔

### CODE REVIEW

**Comment by alblue** [comment]
These look good to me. Everything is comment based apart from ed8c4d0b7 which is changing a local variable name, and all of the references seem to have been captured.

**Comment by koogawa** [comment]
@alblue OK, I reverted https://github.com/apple/swift/commit/ed8c4d0b715b2913a529e2a9ceff8ef58ff8515c

**Comment by CodaFi** [comment]
Going to squash this on my end.

⛵️ 

@swift-ci please smoke test

**Comment by CodaFi** [comment]
Thanks!

**Comment by practicalswift** [comment]
Wow! Excellent gardening work @koogawa. Please keep it coming! :-)

**Comment by alblue** [comment]
Yeah, great work @koogawa. By the way, my comment regarding the silModue typo wasn't that it shouldn't be merged, just that if @codafi or others were to review the patch they might have wanted to double check that particular change. The rename looked safe to me, so I hadn't intended that you roll that back necessarily :-)

**Pull request merged**
