### PR TITLE
Remove custom handling in add_swift_host_library

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
CC: @gottesmm @Rostepher @gwynne

**Review by gwynne — COMMENTED** [review]
I'm not presently qualified to give an unqualified thumbs-up on this, but I definitely approve! 👍

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@Rostepher, @gottesmm - is this okay?

**Comment by compnerd** [comment]
@Rostepher @gottesmm - ping x 2?

**Comment by compnerd** [comment]
@Rostepher @gottesmm - ping x 3

**Comment by gottesmm** [comment]
I checked all instances of uses of this and it merges cleanly. LGTM.

**Pull request merged**
