### PR TITLE
[AccessEnforcement] DEBUG is now called LLVM_DEBUG. NFCI.

### PR DESCRIPTION
**Pull request by dcci**
@bob-wilson / @atrick let me know if this is reasonable to you. I would like to unblock master-next and get the corresponding lldb branch in some usable state.

### CODE REVIEW

**Review by jrose-apple — APPROVED** [review]
We've done a number of other changes like this on master-next, go for it. (I'm tempted to say we should support both on swift-llvm `stable` for a while so that this doesn't keep popping up.)

**Comment by dcci** [comment]
@jrose-apple thanks.

**Comment by atrick** [comment]
This is pretty annoying. I would support DEBUG temporarily if not indefinitely.

**Comment by bob-wilson** [comment]
This should all be temporary, right? Once we update the stable branch of LLVM to something recent, we should just use LLVM_DEBUG consistently. I expect that will happen sometime in the next month or so.

**Pull request merged**
