### PR TITLE
[stdlib] Implement slice Indices using their base Indices

### PR DESCRIPTION
**Pull request by airspeedswift**
Resolves this issue:

```
// FIXME(ABI)#67 (Associated Types with where clauses):
//
//   public typealias Indices = Base.Indices
//   public var indices: Indices { ... }
//
// We can't do it right now because we don't have enough
// constraints on the Base.Indices type in this context.
```

Now that we are constraining `Collection.Indices` to be its own slice type we can implement a slice's `Indices` in terms of it.

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please test source compatibility

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
@swift-ci please smoke test compiler performance

**Comment by airspeedswift** [comment]
@swift-ci please clean test linux platform

**Comment by airspeedswift** [comment]
@swift-ci please test macOS platform

**Comment by airspeedswift** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
Do you want to consider the `Collection` requirement `Indices.Indices == Indices` as part of this?

**Comment by airspeedswift** [comment]
@DougGregor I'm kind of ambivalent. I can't think of any good reason for that constraint ever to not be fulfilled, but also can't think of a use case where it would be useful. I could be missing one tho.

**Pull request merged**
