### PR TITLE
[wasm] Mark `errno` as nonisolated(unsafe) in wasi-libc

### PR DESCRIPTION
**Pull request by kateinoigakukun**
This patch is a workaround to reflect the fact that `errno` is thread-local and can be accessed from any actor. This is a temporary solution until we have [`__swift_attr__` support in apinotes](https://github.com/swiftlang/swift/issues/75819) or [`thread_local` support in ClangImporter](https://github.com/swiftlang/swift/issues/75820).

This change is required to build swift-corelibs-foundation with Swift 6 language mode.

### CODE REVIEW

**Comment by kateinoigakukun** [comment]
@swift-ci test WebAssembly

**Comment by kateinoigakukun** [comment]
@swift-ci smoke test

**Review by MaxDesiatov — APPROVED** [review]

**Comment by al45tair** [comment]
An alternative might be to do what every other platform does and wrap it with a Swift wrapper that calls some inline C functions that access `errno`? That would avoid having to patch `__errno.h`, I think.

**Comment by kateinoigakukun** [comment]
@al45tair We had been taking that approach, but unfortunately providing a Swift wrapper for an importable C declaration results in ambiguous identifier resolution, so we removed the shim https://github.com/swiftlang/swift/pull/75747

**Comment by al45tair** [comment]
> We had been taking that approach, but unfortunately providing a Swift wrapper for an importable C declaration results in ambiguous identifier resolution, so we removed the shim https://github.com/swiftlang/swift/pull/75747

You should be able to use API Notes to fix that already; if you mark the `errno` declaration from the C library as `SwiftPrivate` (aka `NS_REFINED_FOR_SWIFT` in other contexts), I think you should find that the compiler always uses the Swift definition instead.

**Comment by kateinoigakukun** [comment]
Thanks @al45tair! `SwiftPrivate` is what I was looking for. (not sure why I couldn't find it)

**Comment by kateinoigakukun** [comment]
@swift-ci smoke test

**Comment by kateinoigakukun** [comment]
@swift-ci test WebAssembly

**Review by al45tair — APPROVED** [review]

**Pull request merged**
