### PR TITLE
[Preset] Add Linux preset for XCTest pull request testing

### LINKED ISSUE #54639: [SR-12213] Use preset in xctest repository
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12213      |
   |Radar             | rdar://problem/59491081         |
   |Original Reporter | @aciidb0mb3r      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Project Infrastructure    |
   |Labels            | Bug        |
   |Assignee          | @shahmishal      |
   |Priority          | Medium      |

   Watchers: @shahmishal

   md5: 39036114cc831e4a4d0741ca01e2eba8

  </details>

**Issue Description:**

Linux CI on corelibs-xctest is broken right now because swiftpm established dependency on indexstore but it's not marked to be installed in the build script invocation:

> /home/buildnode/jenkins/workspace/swift-corelibs-xctest-PR-Linux/swift/utils/build-script --libicu -R -T --llbuild --swiftpm --xctest --foundation --libdispatch --reconfigure --install-foundation --install-libdispatch --install-libicu --install-libcxx --install-swift --install-llbuild --install-swiftpm --install-xctest

I think using a preset in this job will resolve the issue.

### PR DESCRIPTION
**Pull request by shahmishal**
Fixes #54639

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci smoke test and merge

**Review by compnerd — APPROVED** [review]
Sure, seems reasonable first attempt to repair the XCTest build

**Comment by shahmishal** [comment]
@swift-ci smoke test and merge

**Comment by shahmishal** [comment]
@swift-ci smoke test and merge

**Comment by shahmishal** [comment]
@swift-ci smoke test and merge

**Comment by shahmishal** [comment]
@swift-ci smoke test and merge

**Comment by shahmishal** [comment]
@swift-ci smoke test and merge

**Pull request merged**
