### PR TITLE
Use the `BorrowingSwitch` implementation for all noncopyable switches.

### PR DESCRIPTION
**Pull request by jckarter**
It works well enough now that it should be an acceptable replacement for both borrowing and consuming switches that works in more correct situations than the previous implementation. This does however expose a few known issues that I'll try to fix in follow ups:

- cases with multiple pattern labels aren't yet supported (rdar://125188955)
- copyable types with the `borrowing` or `consuming` modifiers should probably use noncopyable pattern matching.

The `BorrowingSwitch` flag is still necessary to enable the surface-level syntax changes (switches without `consume` and the `_borrowing` modifier, for instance).

rdar://126209276

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test source compatibility

**Comment by jckarter** [comment]
@swift-ci Please test macOS

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test source compatibility

**Review by eeckstein — APPROVED** [review]
nice!
lgtm

**Pull request merged**
