### PR TITLE
[benchmark][driver] Teach the Benchmark_Driver how to parse ./Benchmark_O{,none} --list now that tags are output as well.

### PR DESCRIPTION
**Pull request by gottesmm**
[benchmark][driver] Teach the Benchmark_Driver how to parse ./Benchmark_O{,none} --list now that tags are output as well.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
Just realized that the benchmarks are going to do a before/after and before won't work... @airspeedswift said that this fixed Bench_Driver for him locally, so I am going to push this in. Plan is to iterate/watch the bots tonight just in case.

**Comment by airspeedswift** [comment]
Won't have much luck smoke benchmarking if the benchmarks are currently busted :)

**Comment by gottesmm** [comment]
@airspeedswift ; )

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
Thats what I get for simplifying my implementation, different python lint errors = /. Lets try this again.

**Comment by gottesmm** [comment]
Thats what I get for simplifying my implementation, different python lint errors = /. Lets try this again.

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Pull request merged**
