### PR TITLE
[embedded] Fix editor placeholders by adding a StaticString variant of _undefined

### PR DESCRIPTION
**Pull request by kubamracek**
rdar://119563638

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by rauhul** [comment]
wow you're fast...

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Pull request merged**
