### PR TITLE
[benchmark] run_smoke_bench tweaks

### PR DESCRIPTION
**Pull request by palimondo**
Two small fixes:
* use SWIFT_DETERMINISTIC_HASHING
* allow running tests with dot and dash in the name

The naming change is to allow for measuring tests conforming to proposed naming convention in  #20334 (only partial support for `.` and `-`, for now without `!` and `?`), like the #20552 and #20666.

If these get accepted, the Apple-internal script that measures benchmarks and submits them to LNT should also be updated to work with such names.

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Review by eeckstein — APPROVED** [review]
lgtm

**Comment by palimondo** [comment]
Thank you Erik!

**Comment by palimondo** [comment]
@eeckstein just quick a reminder from above, as it looks like #20769 also uses periods in names:
> If these get accepted, the Apple-internal script that measures benchmarks and submits them to LNT should also be updated to work with such names.

**Comment by lorentey** [comment]
If the dots cause any trouble, I can still change them!

**Pull request merged**
