### PR TITLE
[TF] Re-implement tensor shape/rank operators using TFE runtime APIs.

### PR DESCRIPTION
**Pull request by rxwei**
Do not merge. See if it's faster.

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Review by pschuh — APPROVED** [review]
This is actually good to submit as-is if it is better for performance. Because this already converts shapeTensor and rankTensor to scalars, this won't hurt tracing or graph extraction.

**Comment by rxwei** [comment]
This actually segfaults on macOS.

**Comment by eaplatanios** [comment]
@rxwei Implemented in tensorflow/swift-apis#141.

**Pull request closed without merging**
