### PR TITLE
Re-land Clang types in SIL

### PR DESCRIPTION
**Pull request by varungandhi-apple**
Fixed merge conflicts etc.

TODO:

- [ ] Update some test cases in the last commit introduced in the serialization PR: https://github.com/apple/swift/pull/29670

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
@swift-ci please test

**Comment by varungandhi-apple** [comment]
@swift-ci please test source compatibility

**Comment by varungandhi-apple** [comment]
Follow up to PR https://github.com/apple/swift/pull/29239

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by varungandhi-apple** [comment]
Closing this PR, since it was submitted from a now-deleted clone.

I've fixed some of the conflicts locally, will create a new PR after fixing the rest soon.

**Pull request closed without merging**
