### PR TITLE
Enable modulewrap test on darwin

### PR DESCRIPTION
**Pull request by keith**
This passes on macOS now

### CODE REVIEW

**Comment by keith** [comment]
tbd if this passes on windows I guess

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci test macOS

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by keith** [comment]
Looks like the logs rotated, any idea if it was this test failing?

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
> FileCheck error: '<stdin>' is empty.

**Comment by CodaFi** [comment]
Unfortunately, I think there's some more work to be done.

**Pull request closed without merging**
