### PR TITLE
[CSSolver] Hide witness overloads behind protocol requirements they match

### PR DESCRIPTION
**Pull request by xedin**
If overload set contains both protocol requirement and its witnesses
let's only leave requirement itself active until we know that it matches,
in such case we'd re-enable witness methods and attempt them. This
helps to significantly reduce the number of overload choices we consider
upfront e.g. for '==' operator we can hide 53 choices behind Equatable
protocol from total number of 68 choices.

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test compiler performance

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test compiler performance

**Comment by slavapestov** [comment]
@xedin I've never had much luck with the full perf test, but smoke test seems to work most of the time.

**Comment by slavapestov** [comment]
@xedin But in this case at least it looks like the failures are real :)

Eg,

```
/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite/project_cache/SwiftDate/Sources/SwiftDate/DateInRegion+Components.swift:230:57: error: expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions
                let hour = Double(utc.hour) + Double(utc.minute)/60.0 + (Double(utc.second)+Double(utc.nanosecond)/1e9)/3600.0
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
````

**Comment by xedin** [comment]
@slavapestov Thanks! This needs some more work, just wanted to get preliminary numbers since stdlib compiled successfully :)

**Comment by jrose-apple** [comment]
Again, this is technically a behavior change. I would appreciate a test case that shows we're acknowledging that.

**Comment by xedin** [comment]
@jrose-apple Absolutely! I'm just trying to figure out if this is going to work at all, but at the end of the day, I'll absolutely try to come up with such test-case and add it to the suite.

**Pull request closed without merging**
