### PR TITLE
[TypeReconstruction] Refactor handling of local decl names.

### PR DESCRIPTION
**Pull request by dcci**
<rdar://problem/38428830>

### CODE REVIEW

**Comment by dcci** [comment]
@swift-ci please test and merge

**Comment by dcci** [comment]
@slavapestov this is the new, correct version.

**Comment by dcci** [comment]
There are two stdlib test failures, but they don't seem related (timeouts).
@airspeedswift / @milseman may I ask you to take a look?

**Comment by dcci** [comment]
@swift-ci please test macOS

**Comment by milseman** [comment]
I've never seen those failures before, and it's also possible something happened to the builder. Let's see how this run goes.

**Comment by milseman** [comment]
Looks like this one got to LLDB test failures:
```
[TestSwiftLocalTypes.py FAILED]
```

**Comment by dcci** [comment]
Yes, the `stdlib` issue went away, thanks.
The bug in lldb is a legitimate one (can't resolve the type of a frame variable), so I'll investigate it now.

**Comment by dcci** [comment]
This is the reason why it's failing, according to the log:

```
                 ((SwiftASTContext*)0x7fc3b2fc0880)->GetTypeFromMangledTypename('$S4fail4mainSiyF3FooL_VD')
                 ((SwiftASTContext*)0x7fc3b2fc0880)->GetTypeFromMangledTypename('$S4fail4mainSiyF3FooL_VD') -- not cached, searching
                 ((SwiftASTContext*)0x7fc3b2fc0880)->GetTypeFromMangledTypename('$S4fail4mainSiyF3FooL_VD') -- error: type for symbolname '$S4fail4mainSiyF3FooL_VD' was not found
```

So, fixing one case in the compiler, breaking one in the debugger :(

**Comment by dcci** [comment]
After a discussion with @slavapestov  and @jrose-apple I realized this can't possibly work with source files, as it ends up looking up in a fake module.
I'm going to refactor this function as in one case tries to reconstruct the type of a variable given a variable and in the other case it tries to reconstruct the type of a variable given the mangled type name. Hopefully this will be removed soonish so we won't have to deal with this again.

**Comment by dcci** [comment]
@swift-ci please test and merge

**Comment by dcci** [comment]
@swift-ci please test and merge

**Pull request merged**
