### PR TITLE
[5.0] Get the ModelAssistant source compatibility project building with the swift-5.0-branch

### PR DESCRIPTION
**Pull request by rudkx**
Explanation: There were a couple issues with how rethrows diagnostics were dealing with optional function types, resulting in a verification issue in a new source compatibility suite project.

Issue: [SR-9102](https://bugs.swift.org/browse/SR-9102) / rdar://problem/45615204

Scope: Only affects code that has arguments with are optional throwing function types.

Risk: Low.

Testing: Added a new test for the case where we were failing verification.

Reviewed by: @rjmccall, @xedin 

Does not affect ABI.

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please test

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Review by AnnaZaks — APPROVED** [review]
Approved for after convergence.

**Comment by rudkx** [comment]
@shahmishal IIRC, cross-repo testing doesn't work with the source compatibility suite. Am I remembering that correctly?

**Comment by shahmishal** [comment]
https://github.com/apple/swift-source-compat-suite/pull/298

@swift-ci Please test source compatibility

**Pull request merged**
