### PR TITLE
[Property wrappers] Reject opaque result types when there is no initializer

### PR DESCRIPTION
**Pull request by DougGregor**
Fixes rdar://problem/63169705 / FB7699647.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by hborla** [comment]
Does this only affect default initialization of property wrappers? It seems like this would also cause the crash when generating the memberwise initializer for `X`:

```swift
@propertyWrapper
struct SomeWrapper<T> {
  var wrappedValue: T

  init(wrappedValue: T) { self.wrappedValue = wrappedValue }
}

protocol P { }

struct X {
  @SomeWrapper var property: some P
}
```

**Comment by DougGregor** [comment]
> Does this only affect default initialization of property wrappers?

You're absolutely right! Fixed in the second commit, and added your example. Thank you!

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Review by hborla — APPROVED** [review]
LGTM!

**Pull request merged**
