### PR TITLE
Enable Leaf Frame Pointer Elimination

### PR DESCRIPTION
**Pull request by CodaFi**

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please test

**Comment by CodaFi** [comment]
@swift-ci please benchmark

**Comment by CodaFi** [comment]
Those code size changes are freaky.  That should not be happening...

**Comment by stephentyrone** [comment]
> Those code size changes are freaky. That should not be happening...

It would be worth disassembling one of the smaller ones to see what's going on.

**Comment by CodaFi** [comment]
I've just run two builds of stdlib for macOS at -O and come up with the following IR and Assembly output from the frontend jobs:
[FPElim-O.zip](https://github.com/apple/swift/files/4069018/FPElim-O.zip)

Barring the file path differences in the strings sections (and the really annoying debug info differences), the resulting assembly is exactly what I would expect: the baseline minus frame bookkeeping instructions in leaf functions. There's a pretty good code size savings from that.

Gonna try -Osize

**Comment by CodaFi** [comment]
Same thing at -Osize.

[FPElim-Osize.zip](https://github.com/apple/swift/files/4069039/FPElim-Osize.zip)

**Comment by CodaFi** [comment]
@swift-ci please benchmark

**Comment by CodaFi** [comment]
@swift-ci please benchmark

**Comment by CodaFi** [comment]
@swift-ci please benchmark

**Comment by CodaFi** [comment]
Filed rdar://59172266 to investigate this further.  Closing it out. Having it around for posterity's sake  is still good.

**Pull request closed without merging**
