### PR TITLE
[Stdlib] Add Darwin/Glibc as a dependency for SwiftPrivate.

### PR DESCRIPTION
**Pull request by mikeash**
The changes in https://github.com/apple/swift/pull/19614 require Darwin/Glibc to build first. This usually happened anyway (and thus the problem wasn't noticed for a while) but sometimes SwiftPrivate would win the race and the build would fail.

rdar://problem/45624328

### CODE REVIEW

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by mikeash** [comment]
@compnerd You beat me to it! I just finished building it locally and it was fine. Hopefully a transient test failure.

**Comment by mikeash** [comment]
@swift-ci please test Linux platform

**Comment by mikeash** [comment]
@swift-ci please test Linux platform

**Pull request merged**
