### PR TITLE
[5.5][Serialization] Do not assert when inherited type is null

### PR DESCRIPTION
**Pull request by bnbarham**
Cherry-picks https://github.com/apple/swift/pull/37441

-----

When compiling with allow errors, it's possible to have invalid
inherited types - both null and ErrorType.

Cleaned up the tests a little - moved the majority of
Frontend/allow-errors.swift into separate files in
Serialization/AllowErrors and use split_file.py instead of #defines.

Resolves rdar://78048470

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
Didn't notice these failed, don't think I got an email with them 🤔. Jobs deleted now so just going to run again.

@swift-ci please test

**Comment by bnbarham** [comment]
@swift-ci please test

**Review by akyrtzi — APPROVED** [review]

**Comment by bnbarham** [comment]
@swift-ci please test Linux platform

**Comment by bnbarham** [comment]
@swift-ci please test Linux platform

**Pull request merged**
