### PR TITLE
[concurrency] IRGen:: do ptrauth for hop_to_executor

### PR DESCRIPTION
**Pull request by eeckstein**
Sign the resume-function pointer which is stored in AsyncTask.ResumeTask

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Review by aschwaighofer — APPROVED** [review]
Looks good to me.

**Review by rjmccall — COMMENTED** [review]
LGTM

**Pull request merged**
