### PR TITLE
[passmanager] Move SILOptimizerRequests.cpp into ./lib/SILOptimizer/PassManager/*

### PR DESCRIPTION
**Pull request by gottesmm**
I am doing this move for two reasons:

1. This file only works directly with parts of the PassManager.
2. In the SILOptimizer, we do not have files in the top level of the file tree
and instead group them in one of the subject subfolders.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test OS X platform

**Review by atrick — APPROVED** [review]
thanks

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Comment by gottesmm** [comment]
@swift-ci clean smoke test OS X platform

**Comment by gottesmm** [comment]
@swift-ci clean smoke test OS X platform

**Comment by gottesmm** [comment]
@swift-ci clean smoke test OS X platform

**Pull request merged**
