### PR TITLE
[Tests] Enable SILGen tests that were xfailed since the time when the

### PR DESCRIPTION
**Pull request by ravikandhadai**
integer protocols changed the way basic arithmetic operations were
called.

This commit re-enables those tests and updates the SIL that was checked
in the tests to be consistent with the one generated by the current
compiler.

<rdar://29939484> has more information.

### CODE REVIEW

**Comment by ravikandhadai** [comment]
@swift-ci please smoke test

**Comment by moiseev** [comment]
Awesome! 🎉

**Review by moiseev — APPROVED** [review]
:shipit:

**Review by rjmccall — APPROVED** [review]
Thanks!

**Pull request merged**
