### PR TITLE
RedundantLoadElimination: support redundant loads of array elements with non-constant index

### PR DESCRIPTION
**Pull request by eeckstein**
For example:
```
func test3(_ arr: Array<Int>, index: Int) -> Int {
  return arr[index] + arr[index]
}
```

rdar://138519664

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Review by atrick — APPROVED** [review]
Seems like a reasonable approach to me

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci test macos

**Comment by eeckstein** [comment]
@swift-ci test

**Pull request merged**
