### PR TITLE
[NFC] Allow for ptrauth in @_objcImpl test

### PR DESCRIPTION
**Pull request by beccadax**
Fixes rdar://101420862.

### CODE REVIEW

**Comment by beccadax** [comment]
@swift-ci please smoke test

**Comment by beccadax** [comment]
@swift-ci please smoke test

**Comment by beccadax** [comment]
@swift-ci please smoke test

**Comment by beccadax** [comment]
@swift-ci please smoke test macOS platform

**Comment by beccadax** [comment]
@swift-ci please clean smoke test macOS platform

**Review by hamishknight — APPROVED** [review]

**Comment by hamishknight** [comment]
@swift-ci please clean smoke test macOS platform

**Comment by hamishknight** [comment]
Merging to fix CI

**Pull request merged**
