### PR TITLE
[RemoteAST] Fix metadata reader to properly read tuple type metadata

### PR DESCRIPTION
**Pull request by xedin**
Because `readMetadata` correctly reads tuple type metadata bounds,
there is no need to call for remote read of the memory allocated
for element types, since they are going to be laid out right after
tuple metadata itself and could be accessed using accessors in
`TargetTupleTypeMetadata`.

### CODE REVIEW

**Comment by xedin** [comment]
@rjmccall In PRhttps://github.com/apple/swift/pull/12500 you mentioned that function metadata should be read the same way as tuple metadata, I've noticed that reader might be improved for tuple metadata as well which was still reading using remote mechanism. WDYT?

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by rjmccall** [comment]
Yes, this looks like a very nice improvement (and a good catch about tuple elements).

**Comment by xedin** [comment]
@swift-ci please test and merge

**Pull request merged**
