### PR TITLE
Code Size: Outline copy addr instruction

### PR DESCRIPTION
**Pull request by shajrawi**
radar rdar://problem/33942466

Part 1 one `copy_addr` outlining: supports opaque existentials, address-only existentials, loadable types and loadable enums.

### CODE REVIEW

**Comment by shajrawi** [comment]
@swift-ci Please clean test

**Review by aschwaighofer — CHANGES_REQUESTED** [review]
LGTM with changes to refactor the repetitive code

**Comment by shajrawi** [comment]
@swift-ci Please clean test

**Comment by shajrawi** [comment]
@swift-ci Please clean test

**Comment by shajrawi** [comment]
@swift-ci Please benchmark

**Comment by shajrawi** [comment]
@swift-ci Please benchmark

**Comment by shajrawi** [comment]
@aschwaighofer I refactored the code per your review

**Review by aschwaighofer — APPROVED** [review]
LGTM.

We might have to make this conditional on Osize if some of the regressions are real

**Pull request merged**
