### PR TITLE
[update-checkout] Do not run tests when testing simulators.

### PR DESCRIPTION
**Pull request by gottesmm**
Feedback from Mishal on 0b8381ae78091c495127dde8f877dd38b3b02eee.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Review by shahmishal — APPROVED** [review]
Thanks! LGTM!

**Pull request merged**
