### PR TITLE
[build-script] Add a default-enabled "clean" step for swift-driver and swiftpm products

### PR DESCRIPTION
**Pull request by artemcm**
Along with options to disable the mandatory clean using: `--skip-clean-swift-driver` and `--skip-clean-swiftpm`.

This change will ensure that every invocation of `build-script` will, by default, clean up all build artifacts of these projects and re-build them from scratch.
This is needed for all builds because today arbitrary changes to the compiler can lead to being unable to incrementally build components that are themselves written in Swift (e.g. SwiftPM and swift-driver). This causes now-frequent failures in incremental build bots, and is a scenario that is encountered by developers (For example, see: rdar://65006593).

The proper long-term solution is to enable library evolution for these projects. 
Until this is done, the only safe thing to do is to always rebuild them.

Resolves rdar://65006593

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please smoke test

**Review by gottesmm — COMMENTED** [review]
Are there any other products that should have this set? I imagine it is anything that uses a notion of a shared workspace. I have seen this same error before btw and it was on my list of things to fix. Thanks for taking the initiative here!

**Comment by artemcm** [comment]
> Are there any other products that should have this set? I imagine it is anything that uses a notion of a shared workspace. I have seen this same error before btw and it was on my list of things to fix. Thanks for taking the initiative here!

I imagine so. So far these are the only two projects that have caused a problem. I will look over the other products to see if they could potentially run into this.

**Pull request merged**
