### PR TITLE
[viewcfg] Add an argparse based argument parser and enable the user to select to use dot instead of graphviz.

### PR DESCRIPTION
**Pull request by gottesmm**

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test OS X platform

**Review by eeckstein — APPROVED** [review]
lgtm

**Comment by gottesmm** [comment]
@swift-ci smoke test OS X platform

**Pull request merged**
