### PR TITLE
Conform Never to Identifiable

### PR DESCRIPTION
**Pull request by kylemacomber**
Incorporating into `main` as part of evolution review discussion. This can be reverted if the Core team decides to not accept this change.

rdar://75988520

### CODE REVIEW

**Comment by kylemacomber** [comment]
@swift-ci please smoke test

**Comment by benrimmington** [comment]
Would a `CaseIterable` conformance also be useful?
Either synthesized by the compiler, or as below?

```swift
@available(macOS 9999, iOS 9999, watchOS 9999, tvOS 9999, *)
extension Never: CaseIterable {
  public typealias AllCases = EmptyCollection<Self>
  public static var allCases: AllCases { AllCases() }
}
```

**Comment by kylemacomber** [comment]
@swift-ci please smoke test

**Comment by kylemacomber** [comment]
@swift-ci please test

**Comment by kylemacomber** [comment]
@swift-ci please smoke test macOS platform

**Review by lorentey — APPROVED** [review]

**Comment by kylemacomber** [comment]
@swift-ci please smoke test

**Comment by kylemacomber** [comment]
@swift-ci please smoke test macOS platform

**Comment by kylemacomber** [comment]
@swift-ci please test Windows platform

**Pull request merged**
