### PR TITLE
Fix crash in member lookup when base type contains type variables.

### PR DESCRIPTION
**Pull request by rudkx**
We were crashing during performTypoCorrection if the base type contained
    type variables.

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please test OS X platform

**Comment by rudkx** [comment]
@DougGregor Can you review this for swift-3.0-branch as well?

**Comment by DougGregor** [comment]
LGTM, thanks!

**Comment by ematejska** [comment]
@swift-ci please test

**Comment by rudkx** [comment]
The failure here is from the initial test run timing out after 300 minutes.

**Pull request merged**
