### PR TITLE
Revert "[DefiniteInitialization] Fix the bug that allows overwriting immutable"

### PR DESCRIPTION
**Pull request by ravikandhadai**
This reverts commit 82abf974f2e6ec10c0e21365840268ee419dd5d0 as it breaks
compatability of some existing benchmarks.

### CODE REVIEW

**Comment by ravikandhadai** [comment]
@swift-ci please test

**Comment by gottesmm** [comment]
@ravikandhadai Your commit message here needs more information. What benchmarks failed? What was the error message? Without that it is impossible to know anything from what you wrote here and really it isn't useful.

**Comment by ravikandhadai** [comment]
@jckarter I am sorry for not being clear. I just would like to revert it for the time being while I am investigating the issue. It looks like there could be a bug in the DI, the benchmarks appears to the correct.

**Comment by ravikandhadai** [comment]
@gottesmm  What benchmarks failed? Pegasus.
Please see this radar for more information: <rdar://41501480>

**Comment by ravikandhadai** [comment]
@swift-ci  please test

**Comment by ravikandhadai** [comment]
@swift-ci please test

**Pull request merged**
