### PR TITLE
[ASTBridging] Move some code to MiscBridging.cpp

### PR DESCRIPTION
**Pull request by rintaro**
Also this fixes a weird 'undefined symbol' error when linking with gold.

rdar://137326126

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci please build toolchain Ubuntu 22.04

**Comment by rintaro** [comment]
@swift-ci please build toolchain Linux

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Review by bnbarham — APPROVED** [review]
🤔

**Pull request merged**
