### PR TITLE
Only #include <TargetConditionals.h> when present

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by compnerd — CHANGES_REQUESTED** [review]
I'm not sure that this check makes sense.  TargetConditionals has nothing to do with isa masking, and in fact isn't even from the ObjC runtime.  Can we find an alternate name?

**Comment by mikeash** [comment]
It just so happens that we only use `TargetConditionals.h` macros inside `#if SWIFT_HAS_ISA_MASKING`. Maybe this should be a `__has_include` check instead? Including this file when it's available but `SWIFT_HAS_ISA_MASKING` is off would be harmless.

**Comment by al45tair** [comment]
Agreed. `__has_include` would probably be better for this one, or maybe move the `#include` inside the `#if SWIFT_HAS_ISA_MASKING` where the target macros are actually used?

**Comment by compnerd** [comment]
I considered suggesting `__has_include` but backed away since its clang specific ... but this header is in the stdlib, which cannot be built without clang, so either is fine.  But I do like the idea of just moving the header into the same region.

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test macOS platform

**Comment by kubamracek** [comment]
Switched to `__has_include`. @al45tair, @compnerd, does that look good now?

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by mikeash — APPROVED** [review]

**Pull request merged**
