### PR TITLE
[SwiftSyntax] Add an API to enable or disable bare slash regex literals from SwiftSyntax

### PR DESCRIPTION
**Pull request by ahoppen**
This adds C functions that can be called from SwiftSyntax to enable or disable bare slash regex parsing. 

It also adds a function to set the Swift language version - while this is not of top priority at the moment it will become important once we introduce a new language mode again.

rdar://93750821

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test macOS

**Review by rintaro — APPROVED** [review]

**Comment by hamishknight** [comment]
@ahoppen Looks like this caused `Syntax/Parser/unterminated_regex.swift` to start failing: https://ci.swift.org/job/oss-swift-incremental-RA-macos/762/

**Comment by ahoppen** [comment]
Fixing in https://github.com/apple/swift/pull/59157

**Pull request merged**
