### PR TITLE
[Sema] Add logic to diagnose regex feature availability

### PR DESCRIPTION
**Pull request by hamishknight**
Add the necessary compiler-side logic to allow the regex parsing library to hand back a set of features for a regex literal, which can then be diagnosed by ExprAvailabilityWalker if the availability context isn't sufficient. No tests as this only adds the necessary infrastructure, we don't yet hand back the features from the regex parsing library.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Review by tshortli — APPROVED** [review]

**Comment by hamishknight** [comment]
@swift-ci please test

**Pull request merged**
