### PR TITLE
[5.5] Don't include tests for back deploy concurrency product

### PR DESCRIPTION
**Pull request by edymtt**
Addresses rdar://83777172

(cherry picked from commit 6fbc9623fb18a641ac8f9b95ec7a0b6e00ca322a)

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci please python lint

**Comment by edymtt** [comment]
@swift-ci please python lint

**Comment by edymtt** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]

**Comment by edymtt** [comment]
@swift-ci please test Windows

**Pull request merged**
