### PR TITLE
Enable late OME via an experimental flag

### PR DESCRIPTION
**Pull request by meg-gupta**
Experimental flag to test late OwnershipModelElimination in place of -enable-ossa-modules to temporarily workaround lack of caching leading to repeated recompile of stdlib with -enable-ossa-modules

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Comment by meg-gupta** [comment]
@swift-ci smoke test windows platform

**Review by atrick — APPROVED** [review]
LGTM. What's the current status of testing with this flag enabled?

**Comment by atrick** [comment]
@meg-gupta do you plan to change the two unit tests that use -enable-ossa-modules in a different PR?

**Comment by meg-gupta** [comment]
@atrick Yes, I'll just create a new PR for that.

**Pull request merged**
