### PR TITLE
Rename Some .rst Files to Remove Spaces

### PR DESCRIPTION
**Pull request by sdulal**
Naming conventions.

### CODE REVIEW

**Comment by moiseev** [comment]
Makes sense. Can you also, please, take care of 'Failable Initializers.rst' and 'Pattern Matching.rst'?

**Comment by sdulal** [comment]
On it.

**Comment by moiseev** [comment]
Unfortunate conflicts. Please also make sure that the files being renamed are not referenced anywhere in text.

**Comment by jrose-apple** [comment]
To @moiseev's point, you should be able to generate HTML documentation using Sphinx without any errors.

**Comment by practicalswift** [comment]
Closing this PR since these renames have been incorporated in the repo :-)

**Pull request closed without merging**
