### PR TITLE
Sema: Infer 'dynamic' for overrides of imported methods

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes <rdar://problem/31104529>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
Is it worth limiting this to `open` methods?

**Comment by jckarter** [comment]
The "infer as dynamic" hack has had a bunch of annoying weird side effects when we used it for extensions to ObjC classes. Is that the best approach here? I don't think we want the full effects of late binding, we only want to funnel dispatch through the ObjC method dispatch interface.

**Comment by jrose-apple** [comment]
I think we *do* need the full effects of late binding—the point is that there may be overrides that cannot be seen by the program, possibly even in the base class.

**Comment by jckarter** [comment]
Is there any reason to prevent devirtualization, though, in situations where you can see the overrides?

**Comment by jrose-apple** [comment]
Devirtualizing the super call would not be okay. Devirtualizing a direct call probably is.

I don't suspect this will be a major hit since this is how Objective-C works all the time.

**Comment by jrose-apple** [comment]
(To be clear, I fully sympathize with the "bunch of weird side effects". This will trigger diagnostics about things being marked `dynamic`, for example. I would have preferred to do this later as well. But a lot of the semantics of `dynamic`, such as automatically being inherited, do match what we want here, and it's conservative.)

**Comment by jckarter** [comment]
Will `final` or `static` overrides gets the mystery "declaration cannot be both final and dynamic" error?

**Comment by jrose-apple** [comment]
That should already be checked for in this method, but adding a test case is good.

**Pull request merged**
