### PR TITLE
Fix windows build failure from #40487.

### PR DESCRIPTION
**Pull request by rxwei**

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please smoke test

**Comment by gottesmm** [comment]
@rxwei thanks!

**Review by gottesmm — APPROVED** [review]

**Review by etcwilde — APPROVED** [review]
LGTM

**Comment by DougGregor** [comment]
Linux and macOS builds got far enough along that I'm going to force-merge this to unbreak Windows CI

**Comment by rxwei** [comment]
Thanks!

**Pull request merged**
