### PR TITLE
[CodeCompletion] Avoid unnecessary performTypeChecking() in REPL

### PR DESCRIPTION
**Pull request by rintaro**
This is a leftover from #27981 .

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by CodaFi** [comment]
We really oughta just remove code completion in the REPL at this point...

**Comment by rintaro** [comment]
@CodaFi I agree. That's buggy already.

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by CodaFi** [comment]
Superseded by #31135. Thanks!

**Pull request closed without merging**
