### PR TITLE
Remove lit --param bootstrapping_mode

### PR DESCRIPTION
**Pull request by atrick**

### CODE REVIEW

**Comment by atrick** [comment]
@eeckstein I think this PR makes sense as-is.

When you add a platform check you can change these lines

> if "@BOOTSTRAPPING_MODE@" != "OFF":
>   config.available_features.add('swift_in_compiler')

to instead assert that you can't turn off bootstrapping any more if swift_in_compiler is a feature?
(I didn't realize we were abandoning the possibility of turning off bootstrapping)

**Comment by atrick** [comment]
@swift-ci test

**Review by eeckstein — APPROVED** [review]
lgtm!

**Comment by atrick** [comment]
@swift-ci test linux platform

**Comment by atrick** [comment]
@swift-ci test

**Pull request merged**
