### PR TITLE
Revert "[android] Update to NDK 23"

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/swift#39045

This broke the Windows CI due to incorrect testing.

### CODE REVIEW

**Comment by compnerd** [comment]
Given that the dispatch changes still need some alteration (I agree that dispatch should not be including bits/stdatomic.h), I think its better to revert than to fix.

**Comment by buttaface** [comment]
> is the variable SWIFT_HOST_VARIANT_SDK set on Windows?

Oh yeah, that must be it. I assumed `SWIFT_HOST_VARIANT_SDK` would be set by `build-script`, which the Windows CI is not using here. Instead, it must be depending on the automatic recognition later in this CMake file.

A simple way to fix this would be for you to set `SWIFT_HOST_VARIANT_SDK` explicitly to Windows on your CI instead. This goes back to the issue I've been raising for years now, that this repo inconsistently mixes `CMAKE_SYSTEM_NAME` and `SWIFT_HOST_VARIANT_SDK` to signify the host to build for. I tried to use the latter correctly here, instead of the incorrect usage surrounding it, and while that works for `build-script`, I guess it doesn't for such manual usage that doesn't conform to how `build-script` does it.

**Comment by compnerd** [comment]
Use of `<atomic>` in C++ seems reasonable to me, does that not work?

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by buttaface** [comment]
> As was commented on in the lib dispatch PR , using things in bits is not good. Using the atomic header is the correct approach.

[As I responded there in August, that didn't work either](https://github.com/apple/swift-corelibs-libdispatch/pull/568#issuecomment-907575993), because it doesn't change the fundamental issue that you're invoking C++ declarations inside an extern C block.

The real problem is in `src/internal.h` not following the C++ standard, but I'm not sure how that's best fixed.

**Comment by buttaface** [comment]
Getting back to this pull, what about the fix I mentioned earlier: "A simple way to fix this would be for you to set SWIFT_HOST_VARIANT_SDK explicitly to Windows on your CI instead."

**Comment by compnerd** [comment]
That doesn't work for Windows - the split is important for the split build that Windows does.

**Comment by buttaface** [comment]
> There is a fairly simple mapping:
CMAKE_SYSTEM_NAME: all host tools
CMAKE_HOST_SYSTEM_NAME: all build tools
SWIFT_HOST_VARIANT_SDK: everything in stdlib.

I don't think that is the way it works now- for example, when the host tools are cross-compiled to Apple Silicon, [`build-script` only passes in `SWIFT_HOST_VARIANT_SDK` not `CMAKE_SYSTEM_NAME`](https://github.com/apple/swift/blob/46f3cc9dd83e26bea4245a327c4ddae70d5ae327/utils/build-script-impl#L574)- maybe that changes eventually once @gottesmm moves the build to using CMake toolchain files.

> Given that the CI has been broken for >12 hours now, I'd like to merge this for the time being. We can revert the revert and work on repairing the android builds subsequently.

Alright, understood, please go ahead and revert.

> build-script doesn't work for windows - it assumes bash, which is not reasonable.

That's not what I suggested. You are currently passing a lot of variables on the Windows CI:
```
cmake    -B "T:\swift"    -G Ninja    -DCMAKE_BUILD_TYPE=Release    -DCMAKE_C_COMPILER=cl    -DCMAKE_CXX_COMPILER=cl    -DCMAKE_MT=mt    -DCMAKE_INSTALL_PREFIX:PATH=T:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr    -DClang_DIR:PATH=T:\llvm\lib\cmake\clang    -DSWIFT_PATH_TO_CMARK_BUILD:PATH=T:\cmark    -DSWIFT_PATH_TO_CMARK_SOURCE:PATH=C:\Users\swift-ci\jenkins\workspace\oss-swift-windows-x86_64-vs2019\cmark    -DSWIFT_PATH_TO_LIBDISPATCH_SOURCE:PATH=C:\Users\swift-ci\jenkins\workspace\oss-swift-windows-x86_64-vs2019\swift-corelibs-libdispatch    -DLLVM_DIR:PATH=T:\llvm\lib\cmake\llvm    -DLLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN=ON    -DSWIFT_INCLUDE_DOCS:BOOL=NO    -DSWIFT_WINDOWS_x86_64_ICU_UC_INCLUDE:PATH=C:\Users\swift-ci\jenkins\workspace\oss-swift-windows-x86_64-vs2019\icu-64_2\include\unicode    -DSWIFT_WINDOWS_x86_64_ICU_UC:PATH=C:\Users\swift-ci\jenkins\workspace\oss-swift-windows-x86_64-vs2019\icu-64_2\lib64\icuuc.lib    -DSWIFT_WINDOWS_x86_64_ICU_I18N_INCLUDE:PATH=C:\Users\swift-ci\jenkins\workspace\oss-swift-windows-x86_64-vs2019\icu-64_2\include    -DSWIFT_WINDOWS_x86_64_ICU_I18N:PATH=C:\Users\swift-ci\jenkins\workspace\oss-swift-windows-x86_64-vs2019\icu-64_2\lib64\icuin.lib    -DSWIFT_BUILD_DYNAMIC_STDLIB:BOOL=YES    -DSWIFT_BUILD_DYNAMIC_SDK_OVERLAY:BOOL=YES    -DSWIFT_BUILD_STATIC_STDLIB:BOOL=NO    -DSWIFT_BUILD_STATIC_SDK_OVERLAY:BOOL=NO    -DLLVM_INSTALL_TOOLCHAIN_ONLY:BOOL=YES    -DSWIFT_BUILD_SOURCEKIT:BOOL=YES    -DSWIFT_ENABLE_SOURCEKIT_TESTS:BOOL=YES    -DSWIFT_ENABLE_EXPERIMENTAL_CONCURRENCY=YES    -DSWIFT_ENABLE_EXPERIMENTAL_DISTRIBUTED=YES    -DSWIFT_ENABLE_EXPERIMENTAL_DIFFERENTIABLE_PROGRAMMING=YES    -DSWIFT_INSTALL_COMPONENTS="autolink-driver;compiler;clang-resource-dir-symlink;stdlib;sdk-overlay;editor-integration;tools;sourcekit-inproc;swift-remote-mirror;swift-remote-mirror-headers"    -DSWIFT_PARALLEL_LINK_JOBS=8    -DPYTHON_EXECUTABLE:PATH="C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64"\python.exe    -DCMAKE_CXX_FLAGS:STRING="/GS- /Oy"    -DCMAKE_EXE_LINKER_FLAGS:STRING=/INCREMENTAL:NO    -DCMAKE_SHARED_LINKER_FLAGS:STRING=/INCREMENTAL:NO    -DSWIFT_LIT_ARGS="--time-tests"    -S "C:\Users\swift-ci\jenkins\workspace\oss-swift-windows-x86_64-vs2019\swift"   || (exit /b )
```
I'm simply suggesting you add this one to that list.

Anyway, please go ahead and revert, we can hash this out later.

**Comment by drodriguez** [comment]
@compnerd: sorry for the breakage. It seems that "test and merge" didn't kick off the Windows tests (not even as non-blocking). I would try not to use it in the future.

**Pull request merged**
