### PR TITLE
[DNM] test PR for SwiftPM feature

### PR DESCRIPTION
**Pull request by tomerd**
test for to testing https://github.com/apple/swift-package-manager/pull/4135

### CODE REVIEW

**Comment by tomerd** [comment]
https://github.com/apple/swift-package-manager/pull/4135

@swift-ci please test

**Comment by tomerd** [comment]
@swift-ci test Windows

**Comment by tomerd** [comment]
https://github.com/apple/swift-package-manager/pull/4135

@swift-ci please test windows

**Comment by compnerd** [comment]
I don't think that this works as expected - this is not going to trigger the actual desired build - which is the toolchain build and test: https://ci-external.swift.org/job/oss-swift-windows-toolchain-x86_64-vs2019/

This is going to trigger the toolchain build: https://ci-external.swift.org/job/oss-swift-windows-x86_64-vs2019/

**Comment by tomerd** [comment]
https://github.com/apple/swift-package-manager/pull/4135

@swift-ci please test

**Comment by tomerd** [comment]
@compnerd is this a good enough test to merge https://github.com/apple/swift-package-manager/pull/4135?

**Comment by compnerd** [comment]
Afraid that this doesn't actually exercise the SPM path - so this doesn't work; I can try to run it locally (or if @shahmishal can setup a trigger for https://ci-external.swift.org/job/oss-swift-windows-toolchain-x86_64-vs2019/ that might work)

**Comment by tomerd** [comment]
thanks @compnerd would be nice to have a CI that can help us test such things on Windows. could you loop back on https://github.com/apple/swift-package-manager/pull/4135 when you have results?

**Pull request closed without merging**
