### PR TITLE
[Const evaluator] Improve diagnostics for unknown symbolic values

### PR DESCRIPTION
**Pull request by ravikandhadai**

### CODE REVIEW

**Comment by ravikandhadai** [comment]
@marcrasi I made some minor changes to how diagnostics are emitted. This is meant to address two main issues: 
* The call-stack was not emitted in some cases and in some cases (like recursion) too many notes were produced. 
* Diagnostic notes was not emitted when the unknown value has an associate SILNode that is not a SILInstruction.

**Comment by ravikandhadai** [comment]
Please see only changes in the latest commit which are relevant to this PR. Other commits are associated with earlier PRs.

**Comment by ravikandhadai** [comment]
@swift-ci Please smoke test

**Comment by ravikandhadai** [comment]
Added more changes that improve diagnostics. Specifically, added different diagnostics for different kinds of failures that can happen during interpretation (instead of using Unknown::Default) and make the diagnostic notes more informative.

**Comment by ravikandhadai** [comment]
@swift-ci Please smoke test

**Comment by ravikandhadai** [comment]
@swift-ci Please smoke test

**Comment by ravikandhadai** [comment]
@swift-ci Please smoke test

**Comment by ravikandhadai** [comment]
@swift-ci Please smoke test

**Comment by ravikandhadai** [comment]
@swift-ci Please smoke test

**Comment by shahmishal** [comment]
@swift-ci smoke test

**Review by marcrasi — APPROVED** [review]

**Pull request merged**
