### PR TITLE
[benchmark] Janitor Duty: Sisyphus Legacy

### PR DESCRIPTION
**Pull request by palimondo**
This PR follows-up  #20861, #21413, #21516, #21794 and #22026 in clean-up efforts to enable [robust performance measurements](https://forums.swift.org/t/towards-robust-performance-measurement/11490) by adjusting workloads to run in reasonable time (< 1000 μs), minimizing the accumulated error. To maintain long-term performance tracking, it applies [legacy factor](https://github.com/apple/swift/pull/20212) where necessary.

This one's just the remainder of benchmarks wading through the rest of the alphabet. (There still might be some loose ends to tie later on...)

### CODE REVIEW

**Comment by palimondo** [comment]
@swift-ci Please benchmark

**Comment by palimondo** [comment]
@swift-ci Please smoke test

**Comment by palimondo** [comment]
@eeckstein Please review 🙏

**Comment by palimondo** [comment]
@gottesmm Could you review this in Erik's stead, while he's away please?

**Comment by gottesmm** [comment]
Sorry, I am not available for review for this code.

**Comment by palimondo** [comment]
@atrick Would you be available to review this, please? 🙏

**Review by eeckstein — APPROVED** [review]

**Comment by palimondo** [comment]
@eeckstein Thank you!

**Pull request merged**
