### PR TITLE
Fix OOB access in SemanticARCOpts

### PR DESCRIPTION
**Pull request by meg-gupta**

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test linux platform

**Comment by meg-gupta** [comment]
@swift-ci test linux platform

**Review by gottesmm — COMMENTED** [review]
@meg-gupta LGTM. Can you be more specific in the commit message next time? I would have liked to know more of the why (just saying we were not handling @out arguments correctly would have been fine for me).

**Pull request merged**
