### PR TITLE
Preparation for enabling the  inlining of generics

### PR DESCRIPTION
**Pull request by swiftix**

### CODE REVIEW

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please smoke test Linux

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by slavapestov** [comment]
Why do you disable generic inlining when creating pre-specializations?

**Comment by swiftix** [comment]
@slavapestov Because the generic methods we want to pre-specialize get inlined instead into the caller inside `SwiftOnoneSupport.swift`

**Comment by slavapestov** [comment]
Would a more general solution be to prefer specialization to generic inlining if all substitutions are concrete?

**Comment by swiftix** [comment]
@slavapestov In fact, the PR tries to do exactly  this https://github.com/swiftix/swift/blob/386064b38253caefe9ec0b045574177f4524123f/lib/SILOptimizer/Transforms/PerformanceInliner.cpp#L325-L328 among other things. But it didn't work for pre-specializations somehow.

**Comment by slavapestov** [comment]
Might be worth investigating :)

**Comment by swiftix** [comment]
Yes, but it is not critical at the moment. I'm more curious about the Linux runtime crashes.

**Comment by swiftix** [comment]
@swift-ci please test

**Comment by swiftix** [comment]
@swift-ci please smoke test Linux

**Comment by swiftix** [comment]
please smoke test Linux

**Comment by swiftix** [comment]
@swift-ci please smoke test Linux

**Comment by swiftix** [comment]
@swift-ci please test

**Pull request merged**
