### PR TITLE
utils: start wiring up platform in the build

### PR DESCRIPTION
**Pull request by compnerd**
Introduce android and start wiring up the platform to additional sites. While we cannot yet build the android SDK, this improves the summary to use the platform identifier and sets up the ability to build android variants.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @hjyamauchi @hyp

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Review by hjyamauchi — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
New summary output:
```

Platform Arch    Checkout                    Elapsed Time    
-------- ----    --------                    ------------    
 Windows x86_64  \llvm-project\llvm          00:39:07.5255748
 Windows x86_64  \llvm-project\llvm          00:22:45.4693670
 Windows x86_64  \swift-docc                 00:10:54.7919055
 Windows i686    \swift                      00:07:39.9735858
 Windows x86_64  \swift                      00:06:54.5330712
 Windows aarch64 \swift                      00:06:54.4790912
 Windows x86_64  \swift-corelibs-foundation  00:04:45.2711583
 Windows x86_64  \llvm-project\llvm          00:02:39.2261218
 Windows x86_64  \swiftpm                    00:02:12.7250906
 Windows x86_64  \icu\icu4c                  00:01:38.7579692
 Windows x86_64  \swift-driver               00:01:25.1002192
 Windows i686    \swift-corelibs-foundation  00:01:13.7865960
 Windows aarch64 \swift-corelibs-foundation  00:01:09.7424351
 Windows x86_64  \swift\tools\swift-inspect  00:01:09.4409064
 Windows x86_64  \swift-corelibs-foundation  00:01:08.6071103
 Windows x86_64  \sourcekit-lsp              00:01:06.4244185
 Windows x86_64  \swift-format               00:00:50.7473788
 Windows i686    \icu\icu4c                  00:00:46.0085312
 Windows x86_64  \swift-corelibs-libdispatch 00:00:45.7182262
 Windows aarch64 \icu\icu4c                  00:00:42.1930213
 Windows i686    \llvm-project\llvm          00:00:41.2377941
 Windows aarch64 \llvm-project\llvm          00:00:41.0898002
 Windows i686    \swift-corelibs-libdispatch 00:00:41.0107161
 Windows x86_64  \llvm-project\llvm          00:00:40.4786450
 Windows x86_64  \swift-corelibs-libdispatch 00:00:39.7896180
 Windows aarch64 \swift-corelibs-libdispatch 00:00:39.5779858
 Windows aarch64 \curl                       00:00:37.8629640
 Windows i686    \curl                       00:00:33.8221393
 Windows x86_64  \curl                       00:00:33.0346716
 Windows x86_64  \swift-corelibs-xctest      00:00:32.9574871
 Windows x86_64  \swift-tools-support-core   00:00:32.1557637
 Windows x86_64  \cmark                      00:00:32.1320800
 Windows x86_64  \llbuild                    00:00:30.9843382
 Windows x86_64  \swift-markdown             00:00:24.8323613
 Windows x86_64  \Yams                       00:00:22.7636170
 Windows x86_64  \swift-crypto               00:00:22.6766892
 Windows aarch64 \zlib                       00:00:19.9930611
 Windows x86_64  \swift-argument-parser      00:00:19.5428470
 Windows x86_64  \indexstore-db              00:00:18.9804310
 Windows i686    \zlib                       00:00:18.3703707
 Windows x86_64  \swift-system               00:00:17.5436190
 Windows x86_64  \swift-certificates         00:00:16.6266127
 Windows x86_64  \sqlite-3.43.2              00:00:12.4156450
 Windows x86_64  \swift-collections          00:00:09.6321462
 Windows x86_64  \swift-asn1                 00:00:09.4925852
 Windows x86_64  \libxml2                    00:00:07.3756859
 Windows i686    \swift-corelibs-xctest      00:00:06.7223372
 Windows x86_64  \swift-corelibs-xctest      00:00:06.6532220
 Windows aarch64 \swift-corelibs-xctest      00:00:06.3460038
 Windows aarch64 \libxml2                    00:00:06.1733075
 Windows x86_64  \zlib                       00:00:05.1113199
 Windows i686    \libxml2                    00:00:05.0597315
```

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Pull request merged**
