### PR TITLE
[Sema] Walk patterns for syntactic diagnostics

### LINKED ISSUE #75389: Patterns in `if case` avoid MiscDiagnostics
The following is incorrectly allowed to compile:

```swift
@available(*, unavailable)
func foo() -> Int { 0 }

func bar() {
  if case foo() = 0 {}
}
```

### PR DESCRIPTION
**Pull request by hamishknight**
Use `SyntacticElementTarget::walk`, ensuring we walk to any ExprPatterns.

Resolves #75389
rdar://132185976

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
@swift-ci please test

**Review by xedin — APPROVED** [review]

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Pull request merged**
