### PR TITLE
[Test] Replace unused variable with _

### PR DESCRIPTION
**Pull request by Keno42**
Replace unused variable `a0` and `a1` with `_` in a test file. This used to show a warning when some test case in this file failed.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by xwu** [comment]
When discarding a result, write `_` instead of `let _`.

**Comment by Keno42** [comment]
@xwu Thank you. Fixed it in 63aed1d782f499e2739c3cc4b2ac50d900e17c5a

**Comment by Keno42** [comment]
@swift-ci smoke test

**Comment by CodaFi** [comment]
@Keno42 CI requires privileges for security purposes.

@swift-ci please smoke test

**Pull request merged**
