### PR TITLE
[SIL] Add SIL builtin for Thread Sanitizer inout accesses

### PR DESCRIPTION
**Pull request by devincoughlin**
...and IRGen it into a call to __tsan_write1 in compiler-rt. This is
preparatory work for a later patch that will add an experimental
option to treat Swift inout accesses as TSan writes.

### CODE REVIEW

**Comment by gottesmm** [comment]
My only comment is that I think the way you wrote this will allow the builtin it to be called directly by the standard library. I imagine you don't actually want that = p.

Can you at least create code in SILGenBuiltin to cause any such use to blow up with an llvm_unreachable? This builtin is compiler API at this point. We don't want people using it.

**Comment by devincoughlin** [comment]
I've added an llvm_unreachable() to SILGenBuiltin.cpp. It relies on a new macro in Builtins.def, BUILTIN_SANITIZER_OPERATION.

**Comment by gottesmm** [comment]
LGTM!

**Comment by devincoughlin** [comment]
@swift-ci Please test and merge

**Comment by devincoughlin** [comment]
@swift-ci please smoke test

**Pull request merged**
