### PR TITLE
[5.5] Future-proof the layout of AsyncTask

### PR DESCRIPTION
**Pull request by rjmccall**
5.5 version of #37530

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please test

**Comment by rjmccall** [comment]
@swift-ci Please test

**Comment by rjmccall** [comment]
@swift-ci Please test

**Comment by rjmccall** [comment]
@swift-ci Please test

**Comment by rjmccall** [comment]
@ktoso You approved the main version of this; mind reviewing this version as well so I can merge it?

**Review by ktoso — APPROVED** [review]
Absolutely, LGTM.

**Pull request merged**
