### PR TITLE
Field offset symbols of resilient classes have hidden linkage

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes <rdar://problem/34078503>.

Also fix an optimizer bug exposed after #13865 by building the standard library with resilience enabled. Yay for tightening up symbol visibility!

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
https://github.com/apple/swift-lldb/pull/272
@swift-ci Please smoke test Linux

**Comment by slavapestov** [comment]
https://github.com/apple/swift-lldb/pull/272
@swift-ci Please smoke test macOS

**Comment by jrose-apple** [comment]
Looks like this broke on the 32-bit simulator. https://ci.swift.org/job/swift-PR-osx/2373/testReport/junit/Swift(iphonesimulator-i386)/IRGen/protocol_resilience_thunks_swift/

**Pull request merged**
