### PR TITLE
Re-enable `asan_recover.swift` on Linux.

### PR DESCRIPTION
**Pull request by ghost**
This depends on a fix (821a4930956c9ab4b0dd9052c4e15680f27b93c0) in
llvm-project.

rdar://problem/58702902

### CODE REVIEW

**Comment by danliew-apple** [comment]
@swift-ci please test

**Comment by danliew-apple** [comment]
Hmm the macOS failure looks unrelated to this change.

```
** Building SwiftSyntax **
/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/toolchain-macosx-x86_64/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift build --package-path /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift-syntax --configuration release --build-path /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/unified-swiftpm-build-macosx-x86_64 --multiroot-data-file /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/utils/build_swift/resources/SwiftPM-Unified-Build.xcworkspace --verbose --product SwiftSyntax
Building the standard library for: swift-stdlib-macosx-x86_64 swift-stdlib-iphonesimulator-i386 swift-stdlib-iphonesimulator-x86_64 swift-stdlib-iphoneos-armv7 swift-stdlib-iphoneos-armv7s swift-stdlib-iphoneos-arm64 swift-stdlib-watchsimulator-i386 swift-stdlib-watchos-armv7k
Running Swift tests for: check-swift-validation-macosx-x86_64 check-swift-validation-iphonesimulator-i386 check-swift-validation-iphonesimulator-x86_64 check-swift-validation-watchsimulator-i386
--- Building swiftpm ---
--- Running tests for swiftpm ---
--- Finished tests for swiftpm ---
--- Installing swiftpm ---
--- Building swiftsyntax ---
ERROR: command terminated with a non-zero exit status 1, aborting

ERROR: command terminated with a non-zero exit status 1, aborting
```

@ahoppen @akyrtzi @Rostepher The output hints at something wrong with building `swiftsyntax` but I'm not really sure. Any ideas?

**Comment by danliew-apple** [comment]
Trying again.

@swift-ci Please clean test OS X platform

**Comment by danliew-apple** [comment]
@swift-ci Please clean smoke test OS X platform

**Comment by akyrtzi** [comment]
\cc @rintaro @aciidb0mb3r the log is a bit confusing, above the section you posted there is this:
```
error: Error Domain=NSCocoaErrorDomain Code=260 "The folder “TSC” doesn’t exist." UserInfo={NSFilePath=/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swiftpm/TSC, NSUserStringVariant=(
    Folder
), NSUnderlyingError=0x7fb6bac45720 {Error Domain=NSOSStatusErrorDomain Code=-43 "fnfErr: File not found"}}
FAIL: Building SwiftSyntax failed
Executing: /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/toolchain-macosx-x86_64/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift build --package-path /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift-syntax --configuration release --build-path /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/unified-swiftpm-build-macosx-x86_64 --multiroot-data-file /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/utils/build_swift/resources/SwiftPM-Unified-Build.xcworkspace --verbose --product SwiftSyntax
```

**Comment by ahoppen** [comment]
@akyrtzi This seems to be related to https://github.com/apple/swift-package-manager/commit/33f5b7b5c5cacfd1b31a9364d8b0244b1919a647 TSC has been renamed to `swift-tools-support-core`

**Comment by danliew-apple** [comment]
I'm going to land this PR anyway. This change only effects Linux and those tests passed.

**Pull request merged**
