### PR TITLE
Teach the Dependency Verifier to Emit Fixits

### PR DESCRIPTION
**Pull request by CodaFi**

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci test Windows

**Comment by CodaFi** [comment]
@swift-ci smoke test Linux platform

**Review by davidungar — APPROVED** [review]
Looks very nice! Crisp and clear.

**Comment by CodaFi** [comment]
Saleem tells me I should try teaching gen-output-file-map to open files in binary mode. Let's give it a shot.

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by CodaFi** [comment]
@swift-ci test Windows platform

**Comment by CodaFi** [comment]
@swift-ci test Windows platform

**Comment by CodaFi** [comment]
@swift-ci test Windows platform

**Comment by CodaFi** [comment]
@swift-ci test Windows platform

**Comment by CodaFi** [comment]
@swift-ci test Windows platform

**Comment by CodaFi** [comment]
@swift-ci test Windows platform

**Comment by CodaFi** [comment]
@swift-ci test Windows platform

**Comment by CodaFi** [comment]
@swift-ci test Windows platform

**Comment by CodaFi** [comment]
@swift-ci test Windows platform

**Comment by CodaFi** [comment]
@swift-ci test Windows platform

**Comment by CodaFi** [comment]
The workaround didn't actually work around anything. Going to special-case this test for Windows because there's no reason we should block this long for this small a problem.

**Comment by CodaFi** [comment]
@swift-ci test Windows

**Comment by CodaFi** [comment]
@swift-ci test Windows

**Comment by CodaFi** [comment]
@swift-ci test Windows

**Comment by CodaFi** [comment]
@swift-ci test Windows

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci test Windows

**Comment by CodaFi** [comment]
⛵️

**Pull request merged**
