### PR TITLE
Add benchmark for UTF-8 decoding

### PR DESCRIPTION
**Pull request by PatrickPijnappel**
#### What's in this pull request?

Adds a performance test for UTF-8 decoding.

I didn't pre-multiply N, since the [README](https://github.com/apple/swift/blob/master/benchmark/README.md) suggest that, but the other benchmarks all seem to be premultiplying it. What's the preferred approach here? 

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by gribozavr** [comment]
I'd recommend adding multiple long runs of 2-byte and 3-byte characters into the test string.  That's the typical case, whereas mixed-language case is not.

**Comment by gribozavr** [comment]
What do you mean by 'pre-multiply'?

**Comment by PatrickPijnappel** [comment]
The other benchmark do `for i in 0...1000*N { ... }` (or times whatever constant), while the README suggests `for i in 0...N { ... }`

**Comment by gribozavr** [comment]
@gottesmm What's your recommendation?

**Comment by lplarson** [comment]
We only pre-multiply if a single iteration (N=1) doesn't provide a stable duration to multiply off of to reach a one second sample. If you're seeing a one second sample time, don't pre-multiply.

**Comment by lplarson** [comment]
@swift-ci Please test

**Comment by PatrickPijnappel** [comment]
Ok this test case probably needs a pre-applied multiplier because the setup code otherwise would skew the results, will add one.

**Comment by PatrickPijnappel** [comment]
@lplarson I looked at the benchmark script to get a better understanding and added some clarifications to the benchmark README for future reference (#1514).

**Comment by PatrickPijnappel** [comment]
@nadavrot I accidentally benchmarked that against an old build, it does take longer. Adjusment in #1521.

**Pull request merged**
