### PR TITLE
[Foundation] searching in slices should index relative to the slice (4.1)

### PR DESCRIPTION
**Pull request by phausler**
Searching in slices incorrectly passed the base index rather than the relative slice indexes. This change adjusts the indexing for searching in slices to be relative.

This addresses the following issues
https://bugs.swift.org/browse/SR-5209
rdar://problem/36261057

Tests were added to validate this failure has been addressed (kudos to the filer of the issue for providing a good unit test)

### CODE REVIEW

**Comment by phausler** [comment]
@swift-ci please test

**Review by parkera — APPROVED** [review]
Looks good. Can you double check Swift-corelibs as well?

**Comment by phausler** [comment]
The flaw exists there too so I will duplicate it back here shortly to swift-corelibs

**Comment by phausler** [comment]
@swift-ci please smoke test

**Comment by phausler** [comment]
@swift-ci Please nominate

Explanation: Data indexes passed to a bridged context in searching were incorrect
Scope: This is limited to searching of slices of Data
Radar:rdar://problem/36261057
Origination: Internal & third-party reports (SR-5209)
Risk: Low
Reviewed by: @parkera
Testing: Adds new unit tests to catch regressions to this behavior

**Comment by phausler** [comment]
@swift-ci please test

**Comment by phausler** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
Testing: 

@swift-ci Please nominate

Explanation: Data indexes passed to a bridged context in searching were incorrect
Scope: This is limited to searching of slices of Data
Radar:rdar://problem/36261057
Origination: Internal & third-party reports (SR-5209)
Risk: Low
Reviewed by: @parkera
Testing: Adds new unit tests to catch regressions to this behavior

**Pull request merged**
