### PR TITLE
[stdlib] Add initial Substring benchmarks

### PR DESCRIPTION
**Pull request by dabrahams**

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please smoke test and merge

**Comment by dabrahams** [comment]
@swift-ci Please smoke test and merge

**Comment by dabrahams** [comment]
@swift-ci Please smoke test and merge

**Comment by dabrahams** [comment]
The failure has nothing to do with this change :(

**Comment by moiseev** [comment]
Should be fixed here: https://github.com/apple/swift/pull/9559

**Comment by moiseev** [comment]
@swift-ci Please smoke test and merge

**Pull request merged**
