### PR TITLE
[move-only] Enable the move-only address transform and a small additional fix

### PR DESCRIPTION
**Pull request by gottesmm**
This enables the full move only address transform. I was waiting for 525ba8c07bf2a48fc104a6589e0d007ec4da8a69 to land before landing this.

I also discovered a small problem around simple assignment when writing tests for this. (I thought that `let _ = x` and `_ = x` were codegened the same... but they are not).

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by glessard** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Pull request merged**
