### PR TITLE
Reduce code size of the stdlib

### PR DESCRIPTION
**Pull request by swiftix**
This should reduce the code size of the stdlib by 1.5%.

### CODE REVIEW

**Comment by swiftix** [comment]
@swift-ci please smoke benchmark

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please benchmark

**Comment by dabrahams** [comment]
@swiftix These numbers look good!  StringHasPrefix and StringHasSuffix, like most other tests  dominated by intrinsics like `memcmp`, fluctuate wildly and are probably meaningless.

**Pull request merged**
