### PR TITLE
sourcekitd: using gyb to generate UIDs instead of a def file. NFC

### PR DESCRIPTION
**Pull request by nkcsgexi**
Inspired by the infrastructure of SwiftSyntax, a gyb file can facilitate
cross-language sharing.

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Comment by nkcsgexi** [comment]
@swift-ci please test source compatibility

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci Please clean test Linux platform

**Comment by nkcsgexi** [comment]
@swift-ci please test source compatibility

**Comment by nkcsgexi** [comment]
@swift-ci please test source compatibility

**Comment by davezarzycki** [comment]
This broke unified builds. Why was `generated_sourcekit_uids` added to `tools/CMakeLists.txt`? That seems wrong when it doesn't work and overkill when it does work.

**Comment by davezarzycki** [comment]
Thanks @nkcsgexi. That seems to fix unified builds.

**Pull request merged**
