### PR TITLE
[Autodiff upstream] @transpose attr typechecking

### PR DESCRIPTION
**Pull request by ematejska**
Adding the typechecking support for the @transpose attr.

This resolves TF-830.

### CODE REVIEW

**Comment by ematejska** [comment]
@swift-ci please smoketest

**Comment by ematejska** [comment]
@swift-ci please test

**Comment by ematejska** [comment]
@swift-ci please smoketest linux

**Comment by ematejska** [comment]
@swift-ci please smoketest

**Review by dan-zheng — APPROVED** [review]
Thank you!

**Comment by ematejska** [comment]
@swift-ci please smoketest

**Comment by dan-zheng** [comment]
@swift-ci Please smoke test Linux

**Comment by dan-zheng** [comment]
@swift-ci Please smoke test

**Comment by dan-zheng** [comment]
@swift-ci Please smoke test Linux

**Pull request merged**
