### PR TITLE
Enforce keypath exclusivity as an error.

### PR DESCRIPTION
**Pull request by atrick**
It turns out that it's necessary to special case exclusivity Builtins and add flags to SIL instructions because of a couple circumstances:
- Swift 3 mode exclusivity warnings will continue to be warnings.
- The standard library will continue building in Swift 3 mode (for the foreseeable future).

### CODE REVIEW

**Comment by atrick** [comment]
In case some tooling needs the radar number in the PR instead of the commit log:
rdar://40115738 [Exclusivity] Enforce Keypath access as an error, not a warning in 4.2.

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
@swift-ci test source compatibility.

**Comment by atrick** [comment]
I don't think the two stdlib validation test timeouts are related to these changes. Both tests pass quickly in my local build.

**Comment by atrick** [comment]
@swift-ci test.

**Review by gottesmm — APPROVED** [review]

**Pull request merged**
