### PR TITLE
SILOptimizer: improvements for dead alloc_stack elimination

### PR DESCRIPTION
**Pull request by eeckstein**
This allows to eliminate a dead stack location which contains an existential.

rdar://problem/32272199

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Comment by dabrahams** [comment]
Thank you @eeckstein for such a quick fix!

**Comment by dabrahams** [comment]
Sadly, it doesn't fix the original example from [SR-12710](https://bugs.swift.org/browse/SR-12710).  Please hold the radar open until that's addressed, if possible!

**Comment by eeckstein** [comment]
Thanks for letting me know!
Obviously I forgot to test with the original code. I'll take a look.

**Comment by dabrahams** [comment]
You're the best, @eeckstein !

**Pull request merged**
