### PR TITLE
[Runtime] Fix concurrent lookups of types by name (again).

### PR DESCRIPTION
**Pull request by mikeash**
Fix a potential false positive if we check a class for a protocol conformance and its superclasses aren't yet instantiated.

This was partially fixed before, but we were incorrectly saying that all superclasses had been instantiated if they had been instatiated by the LAST check in conformsToProtocol. That left us open for a possible false positive in an earlier check to go unnoticed.

This change fixes it by checking for uninstantiated superclasses after each iteration over superclasses, not just the last one.

This change also makes the concurrentTypeByName test much more robust. The original test caught this bug only rarely, but the new one catches it it reliably. We now look up 1000 types per test run. Testing locally, we typically hit the race after less than 100 types.

rdar://82364236

### CODE REVIEW

**Comment by mikeash** [comment]
@swift-ci please test

**Review by al45tair — APPROVED** [review]
Wow. That's potentially a gnarly bug to track down :-) LGTM.

**Comment by mikeash** [comment]
Only took me a year, NBD.

**Comment by mikeash** [comment]
@swift-ci please test and merge

**Pull request merged**
