### PR TITLE
[stdlib] Updated minor refactor of StrideThroughGenerator.next()

### PR DESCRIPTION
**Pull request by PatrickPijnappel**
#### What's in this pull request?

Updated version of #1524.
- Move a branch away from the main path.
- Add a clarifying comment.
- Clarify a variable name.

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by CodaFi** [comment]
Fantastic.  Thank you.

@swift-ci please test

**Comment by CodaFi** [comment]
Add the test you suggested to the series defined in #3362.

**Comment by PatrickPijnappel** [comment]
@CodaFi I fixed an error in the original commit and squashed, could you retest?

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by gribozavr** [comment]
@swift-ci Please benchmark

**Comment by gribozavr** [comment]
@swift-ci Please benchmark

**Comment by moiseev** [comment]
After giving it another thought with @gribozavr we think that this refactoring does not fix the `stride(from: 0 as UInt8, through: 255, by: 2)` problem. Filed [a bug](https://bugs.swift.org/browse/SR-2016).
Would be great if you could fix it, @PatrickPijnappel.

Thanks for working on this!

**Comment by gribozavr** [comment]
@swift-ci Please test and merge

**Comment by PatrickPijnappel** [comment]
@moiseev Yeah you're right. I actually meant a different test, which already passed before this PR but which I think is worth checking for so it's not broken accidentally. It's the one the added comment is referring too:
```swift
stride(from: 0 as UInt8, through: 255, by: 5)
```
However, the `stride(from: 0 as UInt8, through: 255, by: 2)` problem is indeed something we should fix. I'll look into it and add the test!

**Pull request merged**
