### PR TITLE
Irgen use runtime function attributes

### PR DESCRIPTION
**Pull request by aschwaighofer**
* Add some ZExt function attributes on functions returning bool
* swift_dynamicCast is not readonly as it writes to the 'dest' buffer
* Fix tail_alloc.sil test

rdar://20802330

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Review by atrick — COMMENTED** [review]
👍 lgtm

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test os x platform

**Pull request merged**
