### PR TITLE
[Concurrency] More precise modeling of `ActorIsolation` for isolated arguments and captures.

### PR DESCRIPTION
**Pull request by hborla**
Teach `ActorIsolation` that a `nil` isolated argument is statically nonisolated, and a reference to `GlobalActor.shared` statically has global actor isolation:

```swift
func sync(isolatedTo actor: isolated (any Actor)?) {}

@MainActor func onMain() {
  sync(isolatedTo: MainActor.shared)

  sync(isolatedTo: nil) // okay to call synchronously from anywhere with `nil`
}
```

This change also models arbitrary actor instance isolation using `VarDecl`s when possible, which allows comparing two `ActorIsolation` values that may represent different actor instances. Previously, `ActorIsolation` was modeled only by storing the nominal actor type and the parameter index, so the actor isolation value for two different actors was considered to be equal. Now, the nominal actor type is only used for isolated `self` in cases where there is no implicit self parameter decl, such as for stored properties. This modeling change fixes an issue where `Task { ... }` would not properly inherit actor isolation when used in a function with an isolated parameter other than `self`:

```swift
class NotSendable {}
actor MyActor{}

func testNonSendableCaptures(ns: NotSendable, a: isolated MyActor) {
  Task {
    _ = a
    _ = ns
  }
}
```

### CODE REVIEW

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by hborla** [comment]
@swift-ci please build toolchain

**Review by DougGregor — APPROVED** [review]

**Comment by mattmassicotte** [comment]
I love this!! But I am a tiny bit surprised that you can pass a `nil` to a non-optional type, but I'll take it!

**Comment by hborla** [comment]
>But I am a tiny bit surprised that you can pass a nil to a non-optional type

You can't; the example that I typed-without-actually-compiling in the PR description is just wrong. I've edited the PR description to avoid confusion, thanks for catching that!

**Comment by mattmassicotte** [comment]
I promise that I am not attempting to make your life more difficult, but that code (with my Swift 5.10 compiler) also does not compile.

```swift
// 'isolated' parameter has non-actor type '(any Actor)?'
func sync(isolatedTo actor: isolated (any Actor)?) {}
```

Does *that* support come from another change?

**Comment by hborla** [comment]
>Does that support come from another change?

Yes, supporting optional isolated parameters is currently gated behind `-enable-experimental-feature OptionalIsolatedParameters` (implementation only on `main`), and that enhancement is currently under SE review at https://forums.swift.org/t/se-0420-inheritance-of-actor-isolation/69638/

**Pull request merged**
