### PR TITLE
Reapply: [Parser] Decouple the parser from AST creation (part 1)

### PR DESCRIPTION
**Pull request by rintaro**
Reapply #25193 with fix

### CODE REVIEW

**Comment by rintaro** [comment]
preset=buildbot_incremental_linux,lsan,tools=RDA,stdlib=DA,test=no
@swift-ci Please test with preset Linux Platform

**Comment by rintaro** [comment]
preset=buildbot_incremental_linux,lsan,tools=RDA,stdlib=DA,test=no
@swift-ci Please test with preset Linux Platform

**Comment by rintaro** [comment]
@swift-ci Please clean test

**Comment by rintaro** [comment]
preset=buildbot_incremental_linux,lsan,tools=RDA,stdlib=RDA,test=no
@swift-ci Please test with preset Linux Platform

**Comment by rintaro** [comment]
preset=buildbot_incremental_linux,lsan,tools=RDA,stdlib=RDA,test=no
@swift-ci Please test with preset Linux Platform

**Comment by rintaro** [comment]
@swift-ci Please clean test

**Comment by rintaro** [comment]
preset=buildbot_incremental_linux,lsan,tools=RDA,stdlib=DA,test=no
@swift-ci Please test with preset Linux Platform

**Comment by rintaro** [comment]
@swift-ci Please clean test

**Comment by rintaro** [comment]
preset=buildbot_incremental_linux,lsan,tools=RDA,stdlib=DA,test=no
@swift-ci Please test with preset Linux Platform

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by rintaro** [comment]
preset=buildbot_incremental_linux,lsan,tools=RDA,stdlib=DA,test=no
@swift-ci Please test with preset Linux Platform

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by rintaro** [comment]
preset=buildbot_incremental_linux,lsan,tools=RDA,stdlib=DA,test=no
@swift-ci Please test with preset Linux Platform

**Comment by marcrasi** [comment]
I think this might have caused some other memory leaks. I posted details here: https://github.com/apple/swift/pull/26403 . Could you take a look? Since you already fixed a few leaks in this change, maybe you'll immediately know where to look for that leak :)

**Comment by rintaro** [comment]
I'll look into it. Thanks!

**Pull request merged**
