### PR TITLE
Module selectors (formerly module qualifiers)

### PR DESCRIPTION
**Pull request by beccadax**
This pull request begins to implement "module selectors", which allow references to declarations to be unambiguously prefixed with a module they can be found through:

```
class MyClass: ObjectiveC::NSObject {}  // OK, ObjectiveC defines NSObject
class MyClass: Foundation::NSObject {}  // OK, Foundation re-exports NSObject
class MyClass: Swift::NSObject {}       // error, Swift does not re-export or define NSObject
class MyClass: MyModule::NSObject {}    // error, MyModule does not re-export or define NSObject
```

This PR parses module selectors and partially implements lookup and diagnostics for them. The new functionality is hidden behind an `-enable-experimental-module-selector` frontend flag. There is one diagnostic regression with that flag enabled, but I've made sure that it keeps working when the diagnostic is disabled.

I will need to switch to other tasks soon, so I plan to merge this work in its current incomplete state to keep it from rotting in a branch.

Makes progress on rdar://problem/19481048.

### CODE REVIEW

**Comment by brentdax** [comment]
I’m unfortunately running out of time to work on this, so I’ll need clean it up and land it behind a feature flag to keep it from rotting.

**Comment by brentdax** [comment]
@swift-ci please test

**Comment by brentdax** [comment]
@swift-ci please test

**Comment by brentdax** [comment]
#28936 broke this branch; force-pushed to correct the code.

**Comment by brentdax** [comment]
@swift-ci please test

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
