### PR TITLE
Optimizer: fix simplification of unchecked_enum_data

### PR DESCRIPTION
**Pull request by eeckstein**
When replacing an `enum` - `unchecked_enum_data` pair and the enum's operand is another non-trivial enum which is constructed with a trivial payload, and this happens in different basic blocks, we need to insert a compensating `destroy_value`.

This peephole optimization was implemented both in SILCombine and as instruction simplification in the SwiftCompilerSources. Both implementations had the same problem. I fixed it in the instruction simplification and made the instruction simplification available in SILCombine. The old SILCombine implementation is not needed anymore.

Fixes a verifier crash
rdar://139787167

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Review by meg-gupta — APPROVED** [review]
Thanks!

**Comment by eeckstein** [comment]
@swift-ci test

**Pull request merged**
