### PR TITLE
Adding a key FAQ

### PR DESCRIPTION
**Pull request by KrishMunot**

### CODE REVIEW

**Comment by jckarter** [comment]
Good idea! Your markdown isn't quite right though; there needs not to be a space between `] (` for the link to be rendered. Thanks!

**Comment by KrishMunot** [comment]
Well, that's funny. I have left a space between ] ( , but the link still doesn't seem to render. I just cross checked it on another repo and it works fine except for this repo.

**Comment by jckarter** [comment]
The great thing about Markdown is that there are so many to choose from. Sorry if I wasn't clear, there *shouldn't* be a space there for Github to render it as a link.

**Comment by KrishMunot** [comment]
I made a new PR for this, kindly check [that](https://github.com/apple/swift/pull/200)

**Comment by jckarter** [comment]
Thanks! I'll close this.

**Pull request closed without merging**
