### PR TITLE
[Function builders] Align buildDo() implementation with the pitch.

### PR DESCRIPTION
**Pull request by DougGregor**
Rather than passing the result of buildBlock() into buildDo(), follow
the (better) design from the function builders pitch by passing in the
components from the block directly into buildDo(). This means that
buildDo() will need to take separate parameters for each component,
but allows buildDo() to treat the components separately.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci smoke test Windows

**Comment by DougGregor** [comment]
@swift-ci smoke test Linux

**Comment by DougGregor** [comment]
@swift-ci smoke test Linux

**Comment by compnerd** [comment]
Its the same s-p-m issue that has been cropping up

**Comment by compnerd** [comment]
@swift-ci please smoke test Linux platform

**Pull request merged**
