### PR TITLE
Improve Python 3 compatibility

### PR DESCRIPTION
**Pull request by practicalswift**

### CODE REVIEW

**Comment by practicalswift** [comment]
@swift-ci please test

**Comment by practicalswift** [comment]
@swift-ci please test

**Comment by practicalswift** [comment]
@swift-ci please smoke test

**Comment by practicalswift** [comment]
@swift-ci please test

**Comment by practicalswift** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please python lint.

**Comment by CodaFi** [comment]
@swift-ci please python lint

**Pull request merged**
