### PR TITLE
Fix a globalvariable initializer bug in LLVMSwiftARC

### PR DESCRIPTION
**Pull request by trentxintong**

### CODE REVIEW

**Comment by trentxintong** [comment]
@swift-ci Please smoke test

**Comment by trentxintong** [comment]
@rudkx can you please take a look ?

**Comment by rudkx** [comment]
@trentxintong I'm really not the best choice to review this.

**Comment by trentxintong** [comment]
@eeckstein can you take a look ?

**Comment by eeckstein** [comment]
LGTM

**Pull request merged**
