### PR TITLE
[Onone][prespecialize] Added iteration through reversed() arrays.

### PR DESCRIPTION
**Pull request by djwbrown**
In response to [SR-3334], which pointed out a large cost to iteration over
ReversedRandomAccessCollections at optimization level -Onone. By adding
iteration through a.reversed() in the _Prespecialize struct, we can get to
about the same performance as forward iteration.

Resolves [SR-3334](https://bugs.swift.org/browse/SR-3334).

### CODE REVIEW

**Comment by djwbrown** [comment]
@swift-ci Please smoke test

**Comment by djwbrown** [comment]
@swift-ci Please benchmark

**Comment by gottesmm** [comment]
@djwbrown I stopped paying attention to this, but you added the benchmark, right?

**Comment by djwbrown** [comment]
Yes, the benchmark has been [merged](https://github.com/apple/swift/commit/ad0948a1102996f9423a28795bff7e2d4a9ad3d5).

I think the CI did not pick up on the comments above. It never queued properly and the 'Details' links are broken. Should I comment again?

**Comment by gottesmm** [comment]
@shahmishal Thoughts?

**Comment by gottesmm** [comment]
Also @djwbrown, thanks for adding the benchmark! We are trying to have all perf oriented commits add benchmarks to prevent unnoticed regressions.

**Comment by djwbrown** [comment]
@gottesmm I had a previous pull request #6496 with the same branch name 'djwbrown:djwbrown-OnoneSupport-reversed'. I accidentally closed that PR by deleting my branch when separating the benchmark commit from the optimization commit. I think that reopening a new pull request with the same branch name may have tripped up the CI, but I'm not sure.

**Comment by swiftix** [comment]
@swift-ci Please benchmark

**Comment by swiftix** [comment]
@djwbrown Oh, I'm wrong. I should have looked at the -Onone performance. ReversedArray is much faster now. Do we expect any speedups for any other datatypes?

**Comment by djwbrown** [comment]
@swiftix No other improvements expected, just reversed arrays with -Onone. [SR-3334](https://bugs.swift.org/browse/SR-3334).

**Comment by djwbrown** [comment]
@swift-ci Please smoke test

**Comment by swiftix** [comment]
@swift-ci Please smoke test

**Comment by swiftix** [comment]
@djwbrown Thanks again for your contribution! Merging.

**Comment by djwbrown** [comment]
Cool! Thanks everyone for your guidance.

**Pull request merged**
