### PR TITLE
[Concurrency] add comment about bug causing Sendable conformance test…

### PR DESCRIPTION
**Pull request by sophiapoirier**
… case to be error rather than warning (follow up to e8d98047d)

### CODE REVIEW

**Comment by sophiapoirier** [comment]
addressing request by @hborla

**Review by hborla — APPROVED** [review]
Thanks!

**Comment by sophiapoirier** [comment]
@swift-ci please test

**Comment by sophiapoirier** [comment]
@swift-ci please test macOS

**Review by ktoso — APPROVED** [review]
thx for the note, maybe issue would be good to go with it. unless it's tracked perhaps somewhere already :)

**Comment by hborla** [comment]
> maybe issue would be good to go with it. unless it's tracked perhaps somewhere already :)

I have issues for this that I'm working on!

**Pull request merged**
