### PR TITLE
[5.1 06-12] Add the notion of @_implementationOnly overrides

### PR DESCRIPTION
**Pull request by jrose-apple**
Cherry-pick of #25447 and #25538 to the early 5.1 branch for Apple-internal purposes. Reviewed by @slavapestov.

(I'll have a regular 5.1 PR soon, but I want to get a jump on testing this one.)

rdar://50827914

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by jrose-apple** [comment]
Source compat: [Debug](https://ci.swift.org/job/swift-PR-source-compat-suite-debug/1340/), [Release](https://ci.swift.org/job/swift-PR-source-compat-suite/3114/)

@swift-ci Please test

**Comment by shahmishal** [comment]
@swift-ci Please test source compatibility

**Comment by shahmishal** [comment]
@swift-ci Please test source compatibility

**Comment by jrose-apple** [comment]
Linux failure is in LLDB, not related to this change: `SwiftREPL/SwiftInterface.test`

**Comment by jrose-apple** [comment]
@swift-ci Please test Linux

**Comment by jrose-apple** [comment]
Source compat failures are in line with the XFAILs for the regular 5.1 branch.

**Pull request merged**
