### PR TITLE
[upstream-update] update IRGen

### PR DESCRIPTION
**Pull request by compnerd**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

The DI type enumeration has been changed in SVN r265077.  Update the API usage
accordingly.

### CODE REVIEW

**Comment by gottesmm** [comment]
Assigning to @rjmccall. He is handling the merge this week.

**Comment by gottesmm** [comment]
@swift-ci Please smoke test

**Comment by compnerd** [comment]
repo_branch = NEXT_BRANCHES[dir_name]
KeyError: 'compiler-rt'

Seems that the changes to support testing on the next branches needs an update?

**Comment by compnerd** [comment]
Ping?

**Comment by rjmccall** [comment]
We do one merge a week.  I haven't gotten to it yet.

**Comment by compnerd** [comment]
Seems that @DougGregor already applied this from another source?

**Comment by compnerd** [comment]
Seems like someone else's change was pulled instead.

**Pull request closed without merging**
