### PR TITLE
Runtime: Fix breakage when generic subclasses directly inherit NSObject

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by gparker42** [comment]
Test failure looks like #4893.

**Comment by slavapestov** [comment]
@swift-ci Please test and merge

**Comment by slavapestov** [comment]
@swift-ci Please test and merge

**Pull request merged**
