### PR TITLE
Losslessly Optimize Images

### PR DESCRIPTION
**Pull request by daknob**
Optimize all repository images using lossless compression (ImageOptim was used).

### CODE REVIEW

**Comment by ssuchanowski** [comment]
I think you went too far with ones with red background

**Comment by katzenbaer** [comment]
Can you change the title of Pull Requests? You have a typo: `Optmize` instead of `Optimize`.

**Comment by wadestuart** [comment]
Yeah,  you will find that images that have strong 1 color channel prevalent areas tend to get pretty sever artifacts and color shift when doing this type of optimization.

**Comment by tmandry** [comment]
Problem is, these are already part of the git history... overwriting them will only make the repo larger. For docs it makes sense if they are hosted as web pages, but not really for tests/utils.

**Comment by DaKnOb** [comment]
Update: All changes have been reverted. Only Documentation images are now optimized since there is no quality loss. 

Thanks for the feedback.

**Comment by alanmcgovern** [comment]
Committing something and immediately reverting it will bloat the repository, as was already mentioned. You should squash the commits into one so there's no unnecessary images added to history. Or just re-issue the PR using the third commit, which is the only one that matters.

**Pull request closed without merging**
