### PR TITLE
[AutoDiff] Modify non-`@differentiable` external function diagnostic.

### PR DESCRIPTION
**Pull request by dan-zheng**
Change diagnostic text from "external function" to "functions from other modules".
Add test.

### CODE REVIEW

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Review by rxwei — COMMENTED** [review]
This is not an accurate description and it may confuse the user. The restriction is cross-module not only in Swift but also in SIL. It should say something like “cannot differentiate functions from other **files** ...”. There’s also a linguistic ambiguity where the relative clause can be thought of as attached to “modules” instead of “functions” in the sentence. Moreover, what would the error be if this is a non-@differentiable property/initializer/subscript? Would it still refer to them as “functions”?

**Comment by dan-zheng** [comment]
> This is not an accurate description and it may confuse the user. The restriction is cross-module not only in Swift but also in SIL. It should say something like “cannot differentiate functions from other **files** ...”. There’s also a linguistic ambiguity where the relative clause can be thought of as attached to “modules” instead of “functions” in the sentence.

That's a good point. What do you think is an ideal message?

> Moreover, what would the error be if this is a non-@differentiable property/initializer/subscript? Would it still refer to them as “functions”?

I think this is orthogonal - the diagnostic can be improved to show accurate declaration kind separately.

**Comment by rxwei** [comment]
> How about `cannot differentiate functions from other files that have not been marked '@differentiable'`?

I don't have a good suggestion, but this still has the relative clause ambiguity problem as it seems to tell the user to mark the "other files" `@differentiable`.

**Comment by dan-zheng** [comment]
> I don't have a good suggestion, but this still has the relative clause ambiguity problem as it seems to tell the user to mark the "other files" `@differentiable`.

I see. Adding a comma may help disambiguate, but I think the result is a bit unnatural: `cannot differentiate functions from other files, that have not been marked '@differentiable'`.

A longer message is unambiguous: `cannot differentiate functions that have not been marked '@differentiable' and that are defined in other files`. How about this?

**Comment by rxwei** [comment]
> A longer message is unambiguous: `cannot differentiate functions that have not been marked '@differentiable' and that are defined in other files`. How about this?

Sounds good

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
There appears to be one unrelated failing test:
```
Failing Tests (1):
    Swift(linux-x86_64) :: IDE/complete_tf_195.swift
```

i can't reproduce it locally on macOS. Kicked off a Ubuntu 18.04 build to try to reproduce it.
Retriggering clean CI build, then merging.

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by rxwei** [comment]
Ah I see! I believe this is the dynamic callable issue I mentioned earlier. I cannot reproduce it on macOS.

**Comment by rxwei** [comment]
This is the same unrelated Python test, so nothing's blocking the merge. I'll merge this before I build a new toolchain.

**Pull request merged**
