### PR TITLE
Mark another flatMap variant as obosleted in a future version

### PR DESCRIPTION
**Pull request by moiseev**

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
@swift-ci Please test Linux platform

**Comment by benrimmington** [comment]
@moiseev The previous failure was in [TestURLSession.test_dataTaskWithHttpInputStream](https://github.com/apple/swift-corelibs-foundation/blob/0bdef0ee6a6092dc451932fe58604a0d84941b90/TestFoundation/TestURLSession.swift#L170).

> Test Case 'TestURLSession.test_dataTaskWithHttpInputStream' started at 2019-02-22 20:47:22.088
> /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/swift-corelibs-foundation/TestFoundation/TestURLSession.swift:170: error: TestURLSession.test_dataTaskWithHttpInputStream : XCTAssertEqual failed: ("1316 bytes") is not equal to ("1323 bytes") - Response Data and Data is not equal
> Test Case 'TestURLSession.test_dataTaskWithHttpInputStream' failed (0.003 seconds)

See also the comments in https://github.com/apple/swift/pull/22813#issuecomment-466528893.

**Comment by moiseev** [comment]
@airspeedswift are you OK with making this change?

**Comment by jrose-apple** [comment]
Please don't do this; we want the obsoletion to match whatever language mode we end up adding, and right now it looks like we're not going to have a `-swift-version 5.1`.

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by stephentyrone** [comment]
Closing this for now, since we're not taking it until we have a language mode.

**Pull request closed without merging**
