### PR TITLE
[Sema] [gardening] Refactor diagnoseMemoryLayoutMigration [NFC]

### PR DESCRIPTION
**Pull request by xwu**
During implementation of SE-0136 in #4041 (restoring `MemoryLayout.size(ofValue:)` and related methods), a chunk of the diagnostics for `MemoryLayout` migration interfered with the restored methods and were therefore removed.

Although all functional changes were made in that PR, the diagnostics that remain could use some clean-up to remove unused plumbing. This PR provides that refactoring.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
Hi @xwu, sorry for losing track of this. Do you mind fixing the merge conflict and pushing a new version I can merge?

**Comment by xwu** [comment]
@slavapestov Done.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test and merge

**Comment by slavapestov** [comment]
@xwu Thank you!

**Comment by xwu** [comment]
@slavapestov Seems Linux smoke test failed this time, but I can't see the details. One more try?

**Comment by slavapestov** [comment]
@swift-ci Please smoke test and merge

**Comment by slavapestov** [comment]
Looks like all builds are failing right now:

```
b/sanitizer_common/CMakeFiles/RTSanitizerCommon.x86_64.dir/sanitizer_posix.cc.o: In function `__sanitizer::FindAvailableMemoryRange(unsigned long, unsigned long, unsigned long)':
/home/buildnode/disk2/workspace/swift-PR-Linux-smoke-test/branch-master/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_posix.cc:362: multiple definition of `__sanitizer::FindAvailableMemoryRange(unsigned long, unsigned long, unsigned long)'
lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.x86_64.dir/sanitizer_linux.cc.o:/home/buildnode/disk2/workspace/swift-PR-Linux-smoke-test/branch-master/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_linux.cc:1393: first defined here
```

@shahmishal Any ideas?

**Comment by slavapestov** [comment]
@swift-ci Please smoke test and merge

**Comment by shahmishal** [comment]
@slavapestov This was due to compiler-rt missing one fix, Anna already fixed it.

**Comment by erg** [comment]
This was due to a change that has been fixed.

**Pull request merged**
