### PR TITLE
[Foundation] searching in slices should index relative to the slice (5.0)

### PR DESCRIPTION
**Pull request by phausler**
Searching in slices incorrectly passed the base index rather than the relative slice indexes. This change adjusts the indexing for searching in slices to be relative.

This addresses the following issues
https://bugs.swift.org/browse/SR-5209
rdar://problem/36261057

Tests were added to validate this failure has been addressed (kudos to the filer of the issue for providing a good unit test)

### CODE REVIEW

**Comment by phausler** [comment]
@swift-ci please test

**Comment by phausler** [comment]
@swift-ci please smoke test

**Comment by phausler** [comment]
@swift-ci please test

**Comment by phausler** [comment]
@swift-ci please test and merge

**Comment by phausler** [comment]
No failures but marked as failed? Very strange.

@swift-ci please test and merge

**Comment by shahmishal** [comment]
Xcode update.. re-trigger CI

@swift-ci please test and merge

**Review by parkera — APPROVED** [review]

**Comment by parkera** [comment]
@swift-ci please test and merge

**Comment by tkremenek** [comment]
This PR was open before the final `swift-5.0-branch` was cut.  If this was in `master` as of November 16, 2018, then this change was pulled into the final re-branching of Swift 5.  Closing as this PR was opened against an older version of this branch.  If this change should be pulled in, please open a new PR.

**Pull request closed without merging**
