### PR TITLE
[NFC] OSSA jump-threading support

### PR DESCRIPTION
**Pull request by atrick**
These are a few commits from 1 year ago. I didn't check them in at the time because the underlying OSSA support was not robust enough to handle all cases that could be exposed, and there was no good way to unit test those utilities.

I'm merging them now under a flag so we can begin simultaneously testing OSSA simplify-cfg and adding unit tests for OSSA.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@meg-gupta the checked-cast jump-threading tests are updated for guaranteed phis and all enabled. I'm ready to merge it.

There is a FIXME to better organize the tests: 
`// FIXME: which of these tests actually require -jumpthread-simplify-cfg instead of -simplify-cfg?`

And one extra copy that we shouldn't need when RAUW is fixed:
`// FIXME_rauw: revisit these fixme's after the OwnershipRAUW utility is rewritten in terms of OwnershipLiveness.`

**Comment by atrick** [comment]
@swift-ci test macOS platform

**Comment by atrick** [comment]
@swift-ci test macOS platform

**Review by meg-gupta — APPROVED** [review]

**Pull request merged**
