### PR TITLE
Improve the interfaces for working with integer widths

### PR DESCRIPTION
**Pull request by rjmccall**
Preparation for `Builtin.IntegerLiteral`.  Builds on top of https://github.com/apple/swift/pull/20177

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please smoke test.

**Comment by rjmccall** [comment]
@swift-ci Please smoke test.

**Comment by rjmccall** [comment]
@swift-ci Please smoke test.

**Comment by rjmccall** [comment]
@swift-ci Please smoke test.

**Comment by rjmccall** [comment]
@swift-ci Please smoke test Linux.

**Comment by rjmccall** [comment]
Linux test failure is not mine.

**Comment by rjmccall** [comment]
@swift-ci Please smoke test.

**Comment by rjmccall** [comment]
(Should be unblocked by https://github.com/apple/swift-llvm/commit/c8d253a85eac347c20277203573b993cb39028b8)

**Comment by rjmccall** [comment]
@swift-ci Please smoke test Linux.

**Comment by rjmccall** [comment]
Didn't propagate?

**Comment by nkcsgexi** [comment]
@swift-ci Please smoke test Linux.

**Pull request merged**
