### PR TITLE
 Propagate concrete types for all arguments of an apply instruction

### PR DESCRIPTION
**Pull request by rajbarik**
Relates to merged and reverted PR https://github.com/apple/swift/pull/17370 that was reverted due to ASAN build problems as mentioned at https://ci.swift.org/job/oss-lldb-asan-osx/11/consoleFull#5770858633122a513-f36a-4c87-8ed7-cbc36a1ec144

### CODE REVIEW

**Comment by rajbarik** [comment]
@atrick @slavapestov the updated PR without use-after-scope problem. please review.

**Review by atrick — APPROVED** [review]
Briefly re-reviewed. LGTM.

**Comment by rajbarik** [comment]
@atrick thanks. Who should review/smoke test etc. next?

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
Sorry, I always forget you need me to run testing. I only use smoke test to retest after making a trivial change to the PR, like changing the commit message or comments. Otherwise, I do the full test.

**Pull request merged**
