### PR TITLE
[5.1] Fix off-by-one when initializing Data with discontiguous, underestimated Sequences

### PR DESCRIPTION
**Pull request by itaiferber**
**What's in this pull request?**
Cherry-picks #23244 to swift-5.1-branch (resolves rdar://problem/48868256)

### CODE REVIEW

**Comment by itaiferber** [comment]
@swift-ci Please test macOS

**Comment by itaiferber** [comment]
@swift-ci Please smoke test linux

**Review by airspeedswift — APPROVED** [review]

**Comment by airspeedswift** [comment]
@swift-ci please test linux

**Comment by shahmishal** [comment]
@itaiferber We re-branched 5.1 from master, do we still need this change? If not, can we close this PR?

**Comment by itaiferber** [comment]
@shahmishal Indeed, verified the changes are present in the re-branch, and this is no longer necessary. Thanks!

**Pull request closed without merging**
