### PR TITLE
Correct a path in the Windows build instructions

### PR DESCRIPTION
**Pull request by texasmichelle**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
Just doing a drive by test (not reviewing)

**Review by compnerd — APPROVED** [review]
*sigh* I somehow missed that when I migrated the paths.  Thank you!

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Pull request merged**
