### PR TITLE
[CoreGraphics Renaming] Overhaul CG apinotes

### PR DESCRIPTION
**Pull request by milseman**
#### What's in this pull request?

```
[Import as Member] Skip needless prefix words.

When adding a prefix to the first argument of an initializer, skip
needless leading words such as "With" or "CF".

[CoreGraphics Renaming] Overhaul CG apinotes

Adds many more API renamings to CoreGraphics.apinotes
```
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please test

**Comment by modocache** [comment]
Quick question: I'm trying to learn how apinotes work. Does a change like this affect what's produced in https://github.com/apple/swift-3-api-guidelines-review?

**Comment by milseman** [comment]
@modocache Good question. It definitely will affect how the CoreGraphics APIs will appear. I'll look into updating the repo, but it might not happen until it can coincide with a developer preview.

If you want to play around with it, you can use the swift-ide-test tool that is build as a part of swift. It's capable of dumping out Swift headers for imported C/ObjC modules.

**Comment by milseman** [comment]
@modocache Example invocation:
```swift-ide-test -print-module -source-filename foo.swift -sdk <path-to-my-sdk> -module-to-print=CoreGraphics.CGColor```

This tool is also invoked by utils/swift-api-dump.py

**Comment by modocache** [comment]
Cool, thanks for the tips! I wonder if I can use this to fix [SR-1165](https://bugs.swift.org/browse/SR-1165)...

**Pull request merged**
