### PR TITLE
Fix some unused function warnings in reflection test.

### PR DESCRIPTION
**Pull request by rudkx**

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
These functions are used on Linux.

**Comment by rudkx** [comment]
@slavapestov Yes, that's why I moved them rather than deleting them.

**Comment by rudkx** [comment]
@swift-ci Please smoke test Linux platform

**Comment by mikeash** [comment]
I'm late to the party, but, LGTM.

**Pull request merged**
