### PR TITLE
[CodeCompletion] Delete `SanitizeExpr`

### PR DESCRIPTION
**Pull request by ahoppen**
Delete a bunch of code that is now dead since we have migrated everything to solver-based completions and then also delete `SanitizeExpr`, which shouldn’t be needed anymore.

rdar://111756748

### CODE REVIEW

**Comment by slavapestov** [comment]
So happy to see this code gone!

**Review by slavapestov — APPROVED** [review]

**Review by xedin — APPROVED** [review]
Awesome, cannot believe we finally made it to this point! :)

**Review by hamishknight — APPROVED** [review]
🎉

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please SourceKit stress test

**Pull request merged**
