### PR TITLE
[SILGen] Emit unreachable in emitProlog() for uninhabited arguments after other codegen

### PR DESCRIPTION
**Pull request by maxovtsin**
The compiler was crashing when data race check instructions were inserted into an already terminated BB.

### CODE REVIEW

**Comment by maxovtsin** [comment]
@swift-ci Please smoke test

**Comment by maxovtsin** [comment]
@slavapestov could you take a look, I believe you already fixed this bug? 🙂

**Comment by drodriguez** [comment]
@swift-ci please smoke test

**Comment by drodriguez** [comment]
@swift-ci please smoke test

**Comment by jckarter** [comment]
LGTM, thanks!

**Pull request merged**
