### PR TITLE
[stdlib] Covariance is not enough

### PR DESCRIPTION
**Pull request by moiseev**
Even though the non-failable initializer satisfies the conformance, trying to force-unwrap the `String("")!` results in an error.
Reverting the original change and adding a test case.

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by moiseev** [comment]
@swift-ci Please Test Source Compatibility

**Comment by dabrahams** [comment]
@moiseev What kind of error?

**Comment by moiseev** [comment]
@dabrahams 
```
/Users/buildnode/jenkins/workspace-private/swift-master-source-compat-suite/build/compat_macos/install/toolchain/usr/bin/swiftc -module-name Commander -incremental -emit-dependencies -emit-module -emit-module-path /Users/buildnode/jenkins/workspace-private/swift-master-source-compat-suite/project_cache/R.swift/.build/release/Commander.swiftmodule -output-file-map /Users/buildnode/jenkins/workspace-private/swift-master-source-compat-suite/project_cache/R.swift/.build/release/Commander.build/output-file-map.json -parse-as-library -whole-module-optimization -num-threads 8 -c /Users/buildnode/jenkins/workspace-private/swift-master-source-compat-suite/project_cache/R.swift/.build/checkouts/Commander.git-8842944228949165507/Sources/ArgumentConvertible.swift /Users/buildnode/jenkins/workspace-private/swift-master-source-compat-suite/project_cache/R.swift/.build/checkouts/Commander.git-8842944228949165507/Sources/ArgumentDescription.swift /Users/buildnode/jenkins/workspace-private/swift-master-source-compat-suite/project_cache/R.swift/.build/checkouts/Commander.git-8842944228949165507/Sources/ArgumentParser.swift /Users/buildnode/jenkins/workspace-private/swift-master-source-compat-suite/project_cache/R.swift/.build/checkouts/Commander.git-8842944228949165507/Sources/Command.swift /Users/buildnode/jenkins/workspace-private/swift-master-source-compat-suite/project_cache/R.swift/.build/checkouts/Commander.git-8842944228949165507/Sources/CommandRunner.swift /Users/buildnode/jenkins/workspace-private/swift-master-source-compat-suite/project_cache/R.swift/.build/checkouts/Commander.git-8842944228949165507/Sources/CommandType.swift /Users/buildnode/jenkins/workspace-private/swift-master-source-compat-suite/project_cache/R.swift/.build/checkouts/Commander.git-8842944228949165507/Sources/Commands.swift /Users/buildnode/jenkins/workspace-private/swift-master-source-compat-suite/project_cache/R.swift/.build/checkouts/Commander.git-8842944228949165507/Sources/Error.swift /Users/buildnode/jenkins/workspace-private/swift-master-source-compat-suite/project_cache/R.swift/.build/checkouts/Commander.git-8842944228949165507/Sources/Group.swift -I /Users/buildnode/jenkins/workspace-private/swift-master-source-compat-suite/project_cache/R.swift/.build/release -swift-version 3 -target x86_64-apple-macosx10.10 -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -O -j8 -DSWIFT_PACKAGE -module-cache-path /Users/buildnode/jenkins/workspace-private/swift-master-source-compat-suite/project_cache/R.swift/.build/release/ModuleCache
/Users/buildnode/jenkins/workspace-private/swift-master-source-compat-suite/project_cache/R.swift/.build/checkouts/Commander.git-8842944228949165507/Sources/ArgumentConvertible.swift:51:23: error: cannot force unwrap value of non-optional type '()'
      self.init(value)!
      ~~~~~~~~~~~~~~~~^
```

The code is here: https://github.com/kylef/Commander/blob/ad1451c13c6b3579c76efdd6937a800251d3f719/Sources/ArgumentConvertible.swift#L51

```swift
extension String : ArgumentConvertible {
  public init(parser: ArgumentParser) throws {
    if let value = parser.shift() {
      self.init(value)!
    } else {
      throw ArgumentError.missingValue(argument: nil)
    }
  }
}
```

**Pull request merged**
