### PR TITLE
[SymbolGraphGen] allow cursor symbol graphs from function params

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
Resolves rdar://105516823

When SourceKit requests a symbol graph for a function or closure parameter, SymbolGraphGen currently doesn't report anything, as `ParamDecl`s are unsupported. This PR adds support for `ParamDecl` by treating it as a `VarDecl`.

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
@swift-ci Please smoke test

**Review by bnbarham — APPROVED** [review]

**Review by rintaro — APPROVED** [review]

**Comment by QuietMisdreavus** [comment]
@swift-ci Please smoke test

**Comment by bnbarham** [comment]
URI still has a `/` in rather than `\\`. FWIW in general I think it'd be better to reduce the check as much as possible, all we really care about is variable name + type. The rest are just checks we'll have to fix if up the output of the symbol graph ever changes 😅

**Comment by QuietMisdreavus** [comment]
@swift-ci Please smoke test

**Pull request merged**
