### PR TITLE
IDE: IWYU

### PR DESCRIPTION
**Pull request by compnerd**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

Add missing string inclusion.  Fixes a compile issue against non-Ubuntu linux
compilation.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci Please smoke test and merge.

**Comment by compnerd** [comment]
@swift-ci Please smoke test Linux platform

**Comment by atrick** [comment]
swift-ci has not been effective all day because of constant breakage, but I think this is safe to go in...

**Comment by rudkx** [comment]
I missed that this went into master and just did my own (somewhat more complete) fix on master-next.

[My fix](37ec98540e68d94cb401ee05a8b0de6c669e9871) also adds headers for all the other things that are used and apparently currently being pulled in implicitly.

I don't think it's crucial to cherry-pick this back to master if the build is unbroken, but if we see more breakages we might consider it.

**Pull request merged**
