### PR TITLE
Wysiwyg interface type

### PR DESCRIPTION
**Pull request by CodaFi**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci test source compatibility

**Comment by CodaFi** [comment]
⛵️

**Review by xedin — COMMENTED** [review]
LGTM!

**Pull request merged**
