### PR TITLE
[Typechecker] Remove 'NSObject.hashValue' warning now that hashValue is no longer marked 'open'

### PR DESCRIPTION
**Pull request by theblixguy**
This code is no longer required because `NSObject.hashValue` is no longer marked [`open`](https://github.com/apple/swift-corelibs-foundation/pull/1850) in Foundation (core-libs). The current diagnostic is emitted by the typechecker in `checkOverrideAccessControl()`, so this is no longer needed.

### CODE REVIEW

**Comment by theblixguy** [comment]
@swift-ci please smoke test

**Comment by theblixguy** [comment]
@swift-ci please smoke test

**Comment by theblixguy** [comment]
Jenkins keeps erroring out due to "invalid SHA" and kicks of a new build but it doesn't show up here 🤷‍♂ I'll let it run and see what happens.

**Comment by theblixguy** [comment]
Let’s try again:

@swift-ci please clean smoke test

**Comment by theblixguy** [comment]
:/ 

@swift-ci please smoke test

**Comment by theblixguy** [comment]
cc @shahmishal do you have any idea why the CI keeps failing the build ("invalid SHA")?

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci please smoke test

**Comment by shahmishal** [comment]
I am not able to checkout this PR, can you close it and create a new one? 

```
git -C swift fetch origin pull/29314/head:test-29314
```

**Pull request closed without merging**
