### PR TITLE
Reapply patch with test, but this time add a pizza unicode emoji to make sure we do not use tagged pointers

### PR DESCRIPTION
**Pull request by gottesmm**

### CODE REVIEW

**Comment by gottesmm** [comment]
Going to do a full test after verifying locally this thing works.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by slavapestov** [comment]
Ah, the old "pizza emoji" trick.

**Comment by gottesmm** [comment]
The test failure on macOS was the String memory test. This test succeeded on i386. Going to smoke test.

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Pull request merged**
