### PR TITLE
[AutoDiff][stdlib] Fix `FloatingPoint.squareRoot()`'s derivative again.

### PR DESCRIPTION
**Pull request by rxwei**
Fix the not-so-correct derivative introduced in #23124. Thanks folks for pointing that out :)

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by xwu** [comment]
Are there tests for this?

**Comment by stephentyrone** [comment]
This is truly the gift that keeps giving =)

**Comment by rxwei** [comment]
> Are there tests for this?
There definitely should be :) Gonna systematically set up derivative tests later when we sort out the derivative registration system.

**Pull request merged**
