### PR TITLE
[Serialization] Opaque types: serialize conditionally available under…

### PR DESCRIPTION
**Pull request by xedin**
…lying types

Resolves: rdar://90595158

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Review by xymus — APPROVED** [review]
It looks good!

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please smoke test Linux platform

**Comment by xedin** [comment]
@swift-ci please smoke test Linux platform

**Pull request merged**
