### PR TITLE
Update runtime_attributes.swift

### PR DESCRIPTION
**Pull request by compnerd**
Correct some misspelt check sigils. The rebranch updates will refresh lit which has new features that identified this misspelling.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Review by xedin — APPROVED** [review]
Thank you!

**Review by grynspan — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
One more time.

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Pull request merged**
