### PR TITLE
[scale-test] Diagnose exponential growth explicitly.

### PR DESCRIPTION
**Pull request by huonw**
This, somewhat questionably, fits the polynomial model and the
exponential model, and then chooses the one with the best R^2. However,
no matter how statistically valid this is, it works reasonably in
practice.

Slow growing things sometimes get classified as 1.0^n or 1.1^n, but
these are either spurious or not relevant, and so a similar thresholding
to the polynomial fit is used.

### CODE REVIEW

**Comment by huonw** [comment]
cc @rudkx

**Comment by huonw** [comment]
@swift-ci Please smoke test and merge.

**Review by graydon — APPROVED** [review]
Two thumbs up!

**Comment by huonw** [comment]
@swift-ci Please smoke test and merge.

**Comment by huonw** [comment]
@swift-ci Please smoke test and merge.

**Comment by huonw** [comment]
@swift-ci Please smoke test

**Pull request merged**
