### PR TITLE
[WIP] SR-7293 Customize Equatable Conformance

### PR DESCRIPTION
**Pull request by mohitathwani**
Refactoring tool to add equatable conformance to a class

Resolves [SR-7293](https://bugs.swift.org/browse/SR-7293).

### CODE REVIEW

**Comment by mohitathwani** [comment]
@harlanhaskins @nkcsgexi I'm ready for round two :)

**Comment by mohitathwani** [comment]
@nkcsgexi In my previous PR, I created a function
```c++
SourceLoc collectMembersForInit(ResolvedCursorInfo CursorInfo,
                           SmallVectorImpl<std::string>& memberNameVector,
                           SmallVectorImpl<std::string>& memberTypeVector)
```

This function gets you all the members of a class along with their types, for this PR, I need to get all the members only, I don't think I need to know the type. Is it okay to rename this function and update it's references in this PR?

**Comment by CodaFi** [comment]
@mohitathwani If you're still interested in pursuing this change, could you rebase this pull request and tag one of us for review?

**Comment by mohitathwani** [comment]
@CodaFi Is there a date you need this by? I haven't made any significant progress and won't be able to get to it until January

**Comment by CodaFi** [comment]
There's no rush.  But if you aren't going to be able to address the SR then I'd like to close this pull request and release it back into the community so somebody else can take a look.  Does that sound good?

**Comment by mohitathwani** [comment]
Yeah go ahead... Sorry for sitting on it for so long...

**Comment by CodaFi** [comment]
It’s no big deal.  You’re free to continue to work on it, and if you would like to keep going here you can just rebase this and reopen it when you’re ready.  I’d just like to see if somebody else would like to try in the mean time.

**Pull request closed without merging**
