### PR TITLE
Avoid introducing critical edges in SimplifyCFG

### PR DESCRIPTION
**Pull request by atrick**
Passes will end up resplitting them, forcing SimplifyCFG to
continually rerun.

Also, we want to allow SIL utilities to assume no critical edges, and
avoid the need for several passes to internally split edges and modify
the CFG for no reason.

Preparation for adding invariants that simplify working with OSSA form and opaque values.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci benchmark

**Comment by atrick** [comment]
All tests passed, but the performance regressions are still blocked on my fixes so semantic call inlining from a year ago. I'll see if I can get those fixes checked in first.

**Review by eeckstein — APPROVED** [review]
lgtm!

Do you know the reason for the benchmark regressions?

**Comment by atrick** [comment]
@eeckstein I've been investigating these regressions for the past week and attempting to stabilize the inliner/pipeline to avoid this sort of thing. They all look like arbitrary consequences of slight inlining changes. Unfortunately, any change I make to stabilize inlining requires other changes to avoid more regressions up to the point where the pass pipeline needs to be rewritten.

Many of the regressions are in Data.init/append. The executed code does not change at all here. It's a 6-instruction loop in Sequence._copyContents that appears extremely sensitive to code placement. I see these benchmarks swing one way or the other whenever I make a small change to inlining costs.

Instead of this PR, I have a series of smaller commits so it's easier to see where regressions first showed up.

**Comment by atrick** [comment]
https://github.com/apple/swift/pull/34502 should avoid all the regressions

**Pull request closed without merging**
