### PR TITLE
swift-lang: shuffle the source directory structure (NFC)

### PR DESCRIPTION
**Pull request by compnerd**
This moves the swift-lang library out of the tools/SourceKit directory
and into the stdlib directory.  As it stands, the library required that
the standard library and the SDK overlay was being built.  This is
implicitly done when building the stdlib subdirectory.  Furthermore, it
had an odd tie between the flags for Swift and SourceKit which now have
the logic separated.  This clearly delineates the host and target
components in the repository.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @nathawes @akyrtzi @gottesmm

**Comment by nathawes** [comment]
I think SwiftLang's only being used by the stress tester at the moment. Long term it should probably be a package that the stress tester and SourceKit-LSP both use to talk to sourcekitd, but for now we can just copy it (or SourceKit-LSP's sourcekitd wrapper code) into the stress tester repo and remove it. I'm working on something else at the minute but should be able to give that a go tomorrow or early next week.

**Comment by compnerd** [comment]
@karwa this is also related to that change btw

**Comment by compnerd** [comment]
@nathawes - this is going to kinda block some work that I am hoping to get done.  Do you think you could manage to do this today?

**Comment by akyrtzi** [comment]
@compnerd  could you clarify, are the changes in this PR allowing the stress-tester to build and run successfully?

**Comment by compnerd** [comment]
@akyrtzi this should have no impact on the current status quo.  Moving the sources into the stress-tester repository is a better solution.  This just moves the sources out of source kit and into the stdlib directory.

**Comment by akyrtzi** [comment]
If it preserves status quo I don't see a reason not to take this PR and move the sources later.

**Comment by compnerd** [comment]
If @nathawes is going to be able to move the sources today, I think that it is a better solution.  But, yes, otherwise, I think that I can fix up the small typo issue, and move forward.

**Comment by nathawes** [comment]
@compnerd I don't think I'll be done by today, sorry, so feel free to go ahead with this PR.

**Comment by compnerd** [comment]
@nathawes, alright, thanks.

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows plaform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Pull request merged**
