### PR TITLE
[test] Re-enable very large allocation codegen test

### PR DESCRIPTION
**Pull request by xwu**
A follow-up to #63034, #63093, #63110, #63095.
Hopefully this completes the saga.

Resolves rdar://104435186.

### CODE REVIEW

**Comment by xwu** [comment]
@swift-ci test

**Comment by xwu** [comment]
cc @ahoppen, @grynspan

**Comment by xwu** [comment]
@shahmishal, is there any good way to test this on the AArch64 Ubuntu CI platform before merging?

**Comment by ahoppen** [comment]
AFAIK, I don’t think there is a way to test AArch64 Ubuntu it in PR testing. I wouldn’t take that for a definite answer though.

**Comment by shahmishal** [comment]
We don't have aarch64 support available on PR testing right now, however we are able to trigger Apple Silicon testing if that help.

**Comment by xwu** [comment]
@shahmishal I suppose it wouldn’t hurt to test, but as I understand it that wasn’t giving any trouble…

I guess otherwise since all the bots are green the strategy can only be to merge and revert if necessary?

**Comment by ahoppen** [comment]
Yes, let's merge and if it breaks bots, we will need to revert again.

**Pull request merged**
