### PR TITLE
[benchmark] Expand ParseInt benchmarks

### PR DESCRIPTION
**Pull request by PatrickPijnappel**
Expands the integer parsing benchmarks to distinguish between:
- **Signed vs. unsigned:** shows sign handling performance.
- **32-bit vs. 64-bit integers:** both are common parsing cases and can perform significantly different due to small vs large strings.

These are in preparation for a full rewrite of integer parsing (which I finally found some time to finish up), where performance will clearly vary along these axes.

### CODE REVIEW

**Comment by PatrickPijnappel** [comment]
@swift-ci Please benchmark

**Comment by PatrickPijnappel** [comment]
@swift-ci Please benchmark

**Review by eeckstein — CHANGES_REQUESTED** [review]
Is it possible to pick a few (maybe ~ 5) representative benchmarks which cover most of the scenarios?
We should avoid inflating the number of benchmarks too much, because we want to keep the total runtime of benchmarking on an acceptable level. If we add exhaustive benchmarks for each small piece of the library and the language it's just too much.

I suggest to pick a few and add the .skip tag to all others. If someone wants to run all the integer parsing benchmarks, it's still possible with the -skipTags option.  See ExistentialPerformance.swift as an example.

Also, we should avoid using gyb, especially in the benchmarks. Eventually we want to convert the benchmarks to a swiftpm package, where we cannot use gyb. Beside that, gyb has other problems (e.g. it complicates debugging).

**Comment by PatrickPijnappel** [comment]
@eeckstein Thanks, I added `.skip` to all but the key ones, which where the ones we already had. Is there some way to trigger a swift-ci benchmark on GitHub that includes skipped tests? E.g. in a pull request specifically about improving integer performance, where the detailed numbers are desirable

Good to know about the gyb usage. For this one do you want to just leave it as is for now, or delete the gyb file? (or another suggestion)

**Comment by PatrickPijnappel** [comment]
@swift-ci Please benchmark

**Comment by eeckstein** [comment]
> Is there some way to trigger a swift-ci benchmark on GitHub that includes skipped tests?

Unfortunately no. But you can run benchmark/scripts/run_smoke_bench locally on your machine. You'll need to modify run_smoke_bench to pass the right options to the benchmark executable.

> For this one do you want to just leave it as is for now, or delete the gyb file?

My preference is to not add the gyb file.

**Comment by compnerd** [comment]
There has been an effort to de-gyb, so it would certainly be preferable to not introduce new gyb based sources.

**Comment by PatrickPijnappel** [comment]
@eeckstein @compnerd 👍 I've removed the gyb file.

Let me know if you think we should try to generalize the test implementation functions as well.

**Comment by PatrickPijnappel** [comment]
I'm also now skipping all but five specific tests, that should be representative both of the different code paths and fairly common real-world use cases.

**Review by eeckstein — APPROVED** [review]
Thanks!

**Comment by PatrickPijnappel** [comment]
@swift-ci Please smoke test

**Comment by PatrickPijnappel** [comment]
@swift-ci Please benchmark

**Pull request merged**
