### PR TITLE
Markup: re-export libcmark_static

### PR DESCRIPTION
**Pull request by compnerd**
Unfortunately, Swift exports the library targets for LLDB.  This
requires the transitive dependencies be exported.  `libcmark_swift` was
not in the export set.  This breaks the unified build.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @xiaobai @JDevlieghere

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by xiaobai** [comment]
How does this break the unified build, exactly? Are you not building lldb in that unified setup?

**Comment by compnerd** [comment]
https://dev.azure.com/compnerd/swift-build/_build/results?buildId=23467&view=logs&j=0e514031-a9b0-5d19-4075-e5711178f10f&t=6491fbec-4801-5529-2943-0955e3c2f90f

**Comment by compnerd** [comment]
I am building LLDB, but, thats not the issue, the issue is that `swiftMarkup` is being exported, but that is a static library, and that library has a dependency on `libcmark_static` which is not being exported.

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-cmark#15

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-cmark#15

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-cmark#15

@swift-ci please test

**Pull request merged**
