### PR TITLE
[5.7][ChangeLog] synchronize with main

### PR DESCRIPTION
**Pull request by glessard**
- adds SE-0333 and SE-0334 to the changelog
- also synchronizes the rest of the log with the main branch, since they were somewhat out of sync.

### CODE REVIEW

**Comment by glessard** [comment]
@swift-ci please smoke test

**Comment by AnthonyLatsis** [comment]
@glessard May I ask that you drop the changes from https://github.com/apple/swift/commit/144be6c85386dd365b0920f2b8371dc37cdec986 or move them into their own commit with the same message as https://github.com/apple/swift/pull/42361/commits/5db44c3e4735769d69059f4fb23177e8933a8def? We tend not to add links for PR-specific entries in the change log so I would like to at least have a link attached to a commit.

**Comment by glessard** [comment]
@AnthonyLatsis do you mean adding that commit to this PR?

**Comment by glessard** [comment]
@AnthonyLatsis do you mean adding that commit to this PR?

**Comment by AnthonyLatsis** [comment]
The thing is that I already have a PR (#42361) that picks the changes from that commit over to the release branch, and I noticed the syncing in this PR does that as well — which I don't mind, but would really appreciate if those changes were applied under a separate commit with a matching message.

**Comment by glessard** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
And... I merged a PR that causes conflicts here, sorry @glessard !

**Comment by glessard** [comment]
@DougGregor The longer it waits, the more conflicted it gets 🤷🏽

**Comment by AnthonyLatsis** [comment]
I went ahead and merged my PR since you ran into a conflict. Thanks again, anyway!

**Comment by glessard** [comment]
@swift-ci please test

**Review by stephentyrone — APPROVED** [review]

**Pull request merged**
