### PR TITLE
Address truncation in types

### PR DESCRIPTION
**Pull request by compnerd**
We were truncating the parameter by using an incorrect parameter type in various locations.  Adjust the types to account for 64-bit platforms which use LLP64.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @DougGregor @bnbarham @rintaro

**Comment by compnerd** [comment]
@swift-ci please test

**Review by xedin — APPROVED** [review]
I'm not overly familiar with CASTBridging related code but it doesn't look specific so looks good!

**Comment by DougGregor** [comment]
There's a more complete fix in https://github.com/apple/swift/pull/68278

**Pull request closed without merging**
