### PR TITLE
Fix crash-on-invalid when calling non-required init on a metatype

### PR DESCRIPTION
**Pull request by slavapestov**
We were missing some checks. Reported by a user on Twitter.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Review by rudkx — COMMENTED** [review]
Do we have any tests that use 'super.init'?

From a brief glance it's not clear to me that the right thing will necessarily happen in that case.

**Comment by slavapestov** [comment]
Do you mean super.init from inside a static method? I’ll try it out. It should probably be banned

**Comment by slavapestov** [comment]
@rudkx This works right now:

```
public class C {
  init() {}
}

public class D : C {
  static func f() -> D {
    return super.init()
  }
}
```

It emits a statically-dispatched call to C.init, just like if you had written `return C()`. I can add a test case for this in a separate PR if you feel its necessary.

**Comment by rudkx** [comment]
I only brought it up because you deleted a line of code checking explicitly for `SuperRefExpr` and it wasn't clear to me that handling it correctly would just fall out from the remaining code. I'll leave it to your best judgement on whether we're already testing adequately for that.

**Pull request merged**
