### PR TITLE
IRGen: ObjC method lists are not const.

### PR DESCRIPTION
**Pull request by jckarter**
Put them in __objc_data instead of __objc_const. rdar://problem/66630432

### CODE REVIEW

**Review by mikeash — APPROVED** [review]

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please clean test OS X

**Comment by jckarter** [comment]
@swift-ci Please clean test OS X

**Comment by jckarter** [comment]
@swift-ci Please test OS X

**Pull request merged**
