### PR TITLE
[Sema] Properly handle missing coding keys in enum Codable synthesis

### PR DESCRIPTION
**Pull request by drexin**
rdar://79671408

### CODE REVIEW

**Comment by drexin** [comment]
@swift-ci smoke test

**Review by ktoso — APPROVED** [review]

**Comment by drexin** [comment]
@swift-ci smoke test macos

**Comment by drexin** [comment]
@swift-ci smoke test windows

**Comment by drexin** [comment]
Windows build failure unrelated to these changes.

**Comment by drexin** [comment]
@swift-ci smoke test windows

**Comment by drexin** [comment]
@swift-ci smoke test windows

**Comment by drexin** [comment]
@swift-ci smoke test windows

**Pull request merged**
