### PR TITLE
[TypeChecker] SE-0326: Enable multi-statement closure inference by default

### PR DESCRIPTION
**Pull request by xedin**
- Adjusts all of the improved test-cases
- Fixes all the troubles with syntactic diagnostics inside of multi-statement closures (availability, constness, `.self` use, local declarations etc.)
- Makes constraint system respect `LeaveClosureBodyUnchecked` flag
- Fixes `DebuggerTestingTransform` to avoid re-using AST nodes
- Restores discarded expressions warnings (expressions appearing directly in a brace statement)
- Allows conjunctions to be considered before closure result or generic parameters are bound to holes, which improves diagnostic experience because result types could now be inferred from the body, so no more extraneous "cannot infer generic parameter '...'" diagnostics relates to multi-statement closures.
- Enables multi-statement closure inference by default.

### CODE REVIEW

**Comment by xedin** [comment]
@hborla This is a draft because I'd like to wait for the Core Team decision on this and if everything goes fine I'm just going to drop frontend flag in a follow-up commit...

**Comment by xedin** [comment]
@swift-ci please clean test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please clean test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please clean test

**Comment by xedin** [comment]
Infra issues, both source compat and macOS failed with `EOFException`, re-running.

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please clean test macOS platform

**Comment by xedin** [comment]
@hborla I dropped two commits that removed the frontend, instead for the time being it would just be enabled by default. We can clean it up later.

**Comment by xedin** [comment]
@swift-ci please clean test

**Review by hborla — APPROVED** [review]
The diagnostic changes in the test suite look awesome 👍🏻

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Pull request merged**
