### PR TITLE
Enable ArrayCountPropagation on OSSA

### PR DESCRIPTION
**Pull request by meg-gupta**
Most of the work was already done in  #34549

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test macOS Platform

**Comment by meg-gupta** [comment]
@swift-ci test Linux Platform

**Review by eeckstein — APPROVED** [review]
LGTM!

**Comment by meg-gupta** [comment]
@swift-ci test

**Pull request merged**
