### PR TITLE
Pull in the upstream @differentiable attribute changes 

### PR DESCRIPTION
**Pull request by bgogul**
This PR pulls in the changes from the upstream PR https://github.com/apple/swift/pull/27506 before that can be merged.

### CODE REVIEW

**Comment by bgogul** [comment]
@swift-ci please test tensorflow

**Review by dan-zheng — APPROVED** [review]
Nice!

**Comment by bgogul** [comment]
@swift-ci please test tensorflow

**Comment by bgogul** [comment]
@swift-ci please test tensorflow

**Pull request merged**
