### PR TITLE
[CMake] Remove LINK_LIBRARIES option from _add_swift_executable_single

### PR DESCRIPTION
**Pull request by bulbazord**
This option has been unused since commit
dd85d79105b1311bb2d1e5cfedc699ee231b5f00. We now use
target_link_libraries instead of this option.

cc @gottesmm @compnerd

### CODE REVIEW

**Review by compnerd — APPROVED** [review]
Thanks for this cleanup!

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by gottesmm** [comment]
This may require internal swift cmake sources to be changed. @Rostepher how does this look?

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by xiaobai** [comment]
@Rostepher Mind taking a quick look at this when you get the chance?

**Comment by xiaobai** [comment]
@Rostepher Friendly ping. Could you please look when you have a moment? Thanks!

**Comment by xiaobai** [comment]
@Rostepher ping!

**Review by Rostepher — APPROVED** [review]
Removing this shouldn't cause any issues. So long as testing passes we are good to merge this. 👍

**Pull request merged**
