### PR TITLE
[sil] Eliminate end_borrow_argument now that end_borrow has a single …

### PR DESCRIPTION
**Pull request by gottesmm**
…operand.

I changed all of the places that used end_borrow_argument to use end_borrow.

rdar://33440767

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Review by rjmccall — APPROVED** [review]
Progress!

**Comment by gottesmm** [comment]
While looking at those failing tests I discovered we aren't strictly verifying guaranteed arguments as much as we can. The behavior that we want is that a guaranteed argument must be contained strictly within the parent borrowed scope. I have an additional commit that is going to tighten this up and adds a bunch of tests to check the behavior.

**Comment by gottesmm** [comment]
It is ok to ignore that for now since SILGen doesn't emit +0 non-function arguments.

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
Lets try this one last time.

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Pull request merged**
