### PR TITLE
Benchmarks for equating/comparing substrings

### PR DESCRIPTION
**Pull request by airspeedswift**
For checking impact of avoiding buffer copies.

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
@swift-ci please smoke test

**Comment by moiseev** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
@swift-ci please smoke test and merge

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
@swift-ci please smoke test

**Pull request merged**
