### PR TITLE
Platform: add legacy compatibility macros to MSVCRT

### PR DESCRIPTION
**Pull request by compnerd**
Although technically these shouldn't be needed on Windows since there is
no compatibility to maintain since there is no version that exists
previously.  However, this will ease porting of sources to the platform.
It also ensures that future tests added cover windows as well.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @jrose-apple

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @stephentyrone

**Comment by stephentyrone** [comment]
LGTM. Merging this will need to wait until after Christmas break.

**Review by stephentyrone — APPROVED** [review]

**Pull request merged**
