### PR TITLE
[migrator] Handle AppKit protocol migrations

### PR DESCRIPTION
**Pull request by akyrtzi**
This is https://github.com/apple/swift/pull/18226 but with a fix for the test to be macos specific.
rdar://42480588

### CODE REVIEW

**Comment by akyrtzi** [comment]
@swift-ci Please test

**Comment by akyrtzi** [comment]
@swift-ci test OS X platform

**Comment by akyrtzi** [comment]
@swift-ci test OS X platform

**Comment by nkcsgexi** [comment]
Thank you!

**Pull request merged**
