### PR TITLE
[test][stdlib] Beef up Unicode.Scalar.Properties testing

### PR DESCRIPTION
**Pull request by Azoy**
Right now, this is depending on https://github.com/apple/swift/pull/39597 landing first before testing this PR.

Adds a new test that reads the Unicode data files and compares answers for all scalar properties for every scalar. Obviously this is marked as a `long_test`, but in this way we can ensure that we aren't returning incorrect information with our data structures storing the Unicode data.

### CODE REVIEW

**Comment by Azoy** [comment]
@swift-ci please smoke test

**Review by milseman — COMMENTED** [review]
This test looks great to me. Let's make sure we run it at the right granularity level. This is a fairly exhaustive programmatic test that is very useful before publishing toolchains or releases, but shouldn't impact anyone's development cycle.

**Comment by Azoy** [comment]
@swift-ci please smoke test

**Comment by Azoy** [comment]
@swift-ci please smoke test

**Pull request merged**
