### PR TITLE
[5.5] Fix SILGen of access to isolated static properties

### PR DESCRIPTION
**Pull request by kavon**
Explanation: Accesses to actor-isolated static properties, such as those isolated to the MainActor, were being miscompiled, which led to missing synchronization and "hopping" to the main thread.
Risk: Low.
Original PRs: https://github.com/apple/swift/pull/38114
Radar/SR Issue: rdar://78292384
Reviewed By: Konrad Malawski 
Testing: Regression tests are included

### CODE REVIEW

**Comment by kavon** [comment]
@swift-ci please test

**Review by ktoso — APPROVED** [review]
Reviewed this before on main, looks good and is important to fix, LGTM 👍

**Comment by kavon** [comment]
@swift-ci please test Linux platform

**Comment by kavon** [comment]
@swift-ci please nominate

**Review by DougGregor — APPROVED** [review]

**Comment by kavon** [comment]
@swift-ci please clean test and merge

**Comment by kavon** [comment]
@swift-ci please clean test linux platform

**Pull request merged**
