### PR TITLE
[region-isolation] Fixes that enable the stdlib to build with region based isolation

### PR DESCRIPTION
**Pull request by gottesmm**
Decided to use the stdlib to test out region based isolation. Found some issues. They are:

1. I discovered in a bunch of cases, we cannot rely on the AST in a real way to determine argument locations around for in loops. Rather than fix that AST, I just did the right thing and made it so that in those cases we emit a diagnostic that infers the name of the value from SIL rather than a type from the AST. I refactored code from the MoveChecker for this purpose and I also added the ability to test the VariableNameInferrer (the utilities name) independently of both by using specify_test.
2. I found I was not handling a few instructions correctly. I updated them.
3. We were transferring @out parameters in certain cases rather than treating them as initializing a value. Of course in cases where it is illegal to use such a value Sema will error. But we should handle it correctly.
4. There is a part of MemAccessUtils that as a hack until we have opaque values treat (project_box (load %boxAddr)) as a projection. I assumed we would never see a project_box as a projection and asserted. We hit that assert in the stdlib.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by gottesmm** [comment]
@swift-ci smoke test macOS platform

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by gottesmm** [comment]
Looks like they all failed:

```
/home/build-user/swift/lib/IRGen/GenCall.cpp:5853:52: error: no member named 'coro_end_results' in namespace 'llvm::Intrinsic'; did you mean 'coro_end_async'?
      Builder.CreateIntrinsicCall(llvm::Intrinsic::coro_end_results, args);
                                  ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
                                                   coro_end_async
/home/build-user/build/buildbot_linux/llvm-linux-x86_64/include/llvm/IR/IntrinsicEnums.inc:44:5: note: 'coro_end_async' declared here
    coro_end_async,                            // llvm.coro.end.async
    ^
```

**Comment by hborla** [comment]
@swift-ci please smoke test

**Pull request merged**
