### PR TITLE
Run instruction profiling pass at the start of the pipeline for the legacy pass manager

### PR DESCRIPTION
**Pull request by hamishknight**
This is already fixed for the new pass manager, add a test case and apply the fix to the legacy pass manager too (cherry-pick of #38197). This prevents LLVM from optimizing out a profiler increment before lowering it, ensuring that we still emit name data for the coverage mapping, even if the increment itself gets optimized out.

This doesn't help in cases where the SIL optimizer optimizes out a profiler increment, but in that case we decline to emit the coverage mapping, so the result is lost coverage instead of a malformed mapping. I'm tracking fixing that in rdar://99813754.

rdar://77217762

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test macOS

**Comment by hamishknight** [comment]
@swift-ci please test

**Review by aschwaighofer — COMMENTED** [review]
👍

**Pull request merged**
