### PR TITLE
[Distributed] fix deprecation warning in `LocalTesting`

### PR DESCRIPTION
**Pull request by MaxDesiatov**
This change fixes following warnings:

```
LocalTestingDistributedActorSystem.swift:30:30: warning: 'LocalTestingActorAddress' is deprecated: renamed to 'LocalTestingActorID'
  public typealias ActorID = LocalTestingActorAddress
                             ^
LocalTestingDistributedActorSystem.swift:30:30: note: use 'LocalTestingActorID' instead
  public typealias ActorID = LocalTestingActorAddress
                             ^~~~~~~~~~~~~~~~~~~~~~~~
                             LocalTestingActorID
LocalTestingDistributedActorSystem.swift:117:29: warning: 'LocalTestingActorAddress' is deprecated: renamed to 'LocalTestingActorID'
    mutating func next() -> LocalTestingActorAddress {
                            ^
LocalTestingDistributedActorSystem.swift:117:29: note: use 'LocalTestingActorID' instead
    mutating func next() -> LocalTestingActorAddress {
                            ^~~~~~~~~~~~~~~~~~~~~~~~
                            LocalTestingActorID
```

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci please test Windows platform

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Review by ktoso — APPROVED** [review]
Awesome, thank you :-)

**Pull request merged**
