### PR TITLE
[CMake] Don't install FileCheck by default

### PR DESCRIPTION
**Pull request by davezarzycki**
I'm not sure what the right solution is here.

@compnerd – What do you think?

### CODE REVIEW

**Comment by compnerd** [comment]
Don't think this works.  `FileCheck` is part of LLVM, which is not guaranteed to be built in tree (although, I would love for us to get to that point).  The `LLVM_BUILD_BINARY_TREE` is expected to be set currently when built through `build-script`, though it seems that you, much like me, do not use that.  Really, we need the root of the LLVM build tree, which is required to install `FileCheck`.  I think as a horrible workaround, you could force this value into the cache through the command line.

All the technical details conveyed, personally, I think that we really should consider just removing the installation `FileCheck` from swift.  If it is something which is useful to actually install, I think that we should work with the rest of the LLVM community and provide a proper installation mechanism for that in the LLVM build system (which probably comes with the cost of, who is going to be responsible for this tool?).

**Comment by davezarzycki** [comment]
Okay, let's just make Swift's CMake setup not install `FileCheck` by default because it conflicts/overlaps with the LLVM install target during unified builds. The build-script can always opt into this install target if it wants.

@swift-ci please smoke test

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
CC: @Rostepher @gottesmm - I don't expect that this should break anything internally.

**Comment by compnerd** [comment]
@swift-ci please smoke test Linux platform

**Review by compnerd — APPROVED** [review]
Looks good to me, though, ideally you would poke @Rostepher as well.

**Review by Rostepher — APPROVED** [review]
This looks good to me. As far as I can tell the only tool that uses the "toolchain-dev-tools" install component is FileCheck.

**Pull request merged**
