### PR TITLE
api_checker: Drop support for Python 2

### PR DESCRIPTION
**Pull request by jorng**
This converts the `utils/api_checker` scripts to support Python 3 only. It removes all `from __future__` imports, and switches any `python` shebangs to `python3`.

This is part of an ongoing effort to explicitly move to Python 3 and remove any implied support for Python 2.

### CODE REVIEW

**Comment by jorng** [comment]
@swift-ci please smoke test

**Review by nkcsgexi — APPROVED** [review]

**Review by edymtt — APPROVED** [review]

**Comment by jorng** [comment]
@swift-ci please smoke test

**Comment by edymtt** [comment]
@swift-ci please smoke test

**Comment by edymtt** [comment]
cc @dduan -- using this PR to address one script that #42086 did not cover

**Review by dduan — APPROVED** [review]
Lgtm

**Pull request merged**
