### PR TITLE
[TF] Merge tag 'swift-DEVELOPMENT-SNAPSHOT-2018-11-01-a' into tensorflow

### PR DESCRIPTION
**Pull request by rxwei**
This is a completely trivial merge. Almost no conflicts.

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow Linux CPU

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux CPU

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux CPU

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux CPU

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux CPU

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux CPU

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux CPU

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux CPU

**Comment by bgogul** [comment]
@swift-ci please clean test tensorflow

**Comment by bgogul** [comment]
@swift-ci please clean test tensorflow

**Comment by rxwei** [comment]
@bgogul Looks good!

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by bgogul** [comment]
@swift-ci please clean test tensorflow

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by bgogul** [comment]
Tests passed. I will go ahead and merge these changes into tensorflow.

**Pull request merged**
