### PR TITLE
[pruned-liveness] Make some small fixes that only are exposed when working with multi-bit code

### PR DESCRIPTION
**Pull request by gottesmm**
I am fixing some issues that I discovered in FieldSensitive liveness which internally uses pruned live blocks. There are a few things that I did here that fix some architectural issues:

1. Rather than attempting to perform operations all at once for multiple bits, we instead now just work one bit at a time. This simplifies the internal implementation and also more importantly allows me to specialize the internal implementation for single bit usage.
2. I changed getBlockLiveness to only return enough block liveness for the requested bits. If we returned extra dead bits we perform computeUseBlockLiveness additional times for bits where we do not want to do so. This can cause weird propagation issues.

NOTE: This is an interim change. I plan on splitting PrunedLiveBlocks into two separate implementations in a subsequent commit. The first will take advantage of SILNodeBits and only handle single bits and we will have a separate FieldSensitive one that handles multiple bits.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
The reason why I think this hasn't hit the main move only address impl is that I am now fixing how we hoist destroy_addr which exposes these issues when we have partially deinited structs.

**Comment by gottesmm** [comment]
@swift-ci test

**Review by atrick — APPROVED** [review]
Thanks. It'll be great to separate the field sensitive code.

**Comment by gottesmm** [comment]
I just merged this and I think GitHub hit an issue where it didn't realize the merge went through? I guess I am just going to close this PR.

**Pull request closed without merging**
