### PR TITLE
[AutoDiff] move all stdlib derivatives to separate files

### PR DESCRIPTION
**Pull request by marcrasi**
Moves all stdlib derivatives into separate files:
* Moves derivatives from `Array.swift`, `FloatingPoint.swift`, and `SIMDVector.swift` to `Differentiation/DifferentiationSupport.swift`.
* Moves derivatives from `FloatingPointTypes.swift.gyb` to `Differentiation/FloatingPointTypesDerivatives.swift`.
* Moves derivatives from `Platform/tgmath.swift.gyb` to `Platform/tgmath_derivatives.swift.gyb` and tests from `stdlib/tgmath.swift.gyb` to `test/AutoDiff/downstream/tgmath_derivatives.swift.gyb`.
  * As a future improvement, we might want to move these into a totally separate directory like `PlatformDifferentiation`, so that they can be in a separate module on upstream.

As a result, these files are now perfectly in sync with master:
* `Array.swift`
* `FloatingPoint.swift`

However, we still have some diff from master in other files:
* `SIMDVector.swift` needs a change to work around TF-1103.
* All the tgmath-related files, and `FloatingPointTypes.swift.gyb`, have non-AD-related diffs to master, because we reverted the revert of ElementaryFunctions, which affects tgmath-related files.

### CODE REVIEW

**Review by dan-zheng — APPROVED** [review]
> As a result, these files are now perfectly in sync with master:
> 
> * `Array.swift`
> * `FloatingPoint.swift`

Tremendous, congratulations!

**Review by dan-zheng — COMMENTED** [review]
> Moves derivatives from `Platform/tgmath.swift.gyb` to `Platform/tgmath_derivatives.swift.gyb` and tests from `stdlib/tgmath.swift.gyb` to `test/AutoDiff/downstream/tgmath_derivatives.swift.gyb`.
> * As a future improvement, we might want to move these into a totally separate directory like `PlatformDifferentiation`, so that they can be in a separate module on upstream.

Is it possible to move `Platform/tgmath_derivatives.swift.gyb` to `stdlib/public/Differentiation` to keep things contained?

**Comment by marcrasi** [comment]
> Is it possible to move Platform/tgmath_derivatives.swift.gyb to stdlib/public/Differentiation to keep things contained?

I do not think so.

The stdlib does not depend on Platform, and it can't declare derivatives on Platform functions unless we make it depend on Platform. Changing the dependencies of the stdlib is probably not something we should do.

**Comment by marcrasi** [comment]
Unless you mean just moving the file without changing the module that it gets built into. That should work. But I think that would be confusing: having different files in stdlib/public/Differentiation being built into different modules.

**Review by rxwei — APPROVED** [review]
Love this!

**Comment by marcrasi** [comment]
@swift-ci please test tensorflow

**Pull request merged**
