### PR TITLE
TODO: this is not required anymore. Remove it. + Zapping missing serializeAll parameter

### PR DESCRIPTION
**Pull request by gabrielPeart**
Rebased + Tests pass

### CODE REVIEW

**Comment by gottesmm** [comment]
Please eliminate the merge commit. Please just rebase. I need to look at the rest of it still.

**Comment by nadavrot** [comment]
Also, please make sure that this lands as a single commit, not 5 different commits.

**Comment by gottesmm** [comment]
Can Fix Typo in Stack Promotion go into a different pull request?

**Comment by nadavrot** [comment]
@gottesmm @gabrielPeart Pull requests should have one commit per issue, and contain exactly one distinct fix area. Mixing fixes to StackPromotion with the other stuff is not a good idea.

**Comment by gabrielPeart** [comment]
You guys are right, I'm going to so a new pull request with a single commit and close this one.

**Pull request closed without merging**
