### PR TITLE
[SE-0099 Restructuring Condition Clauses] Flip the switch

### PR DESCRIPTION
**Pull request by milseman**
#### What's in this pull request?

```
Now that some time has passed, switch the warnings to errors,
completing SE-0099.
```
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

Now that some time has passed, switch the warnings to errors,
completing SE-0099.

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
It seems I'll need to update corelibs Foundation first.

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please test

**Comment by ematejska** [comment]
@swift-ci please test

**Comment by milseman** [comment]
Blocked on: https://github.com/apple/swift-corelibs-foundation/pull/479

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
Unrelated LLDB test failure

**Pull request merged**
