### PR TITLE
[Runtime] Allow overrides or swift_getAssociated(Type|Conformance)Witness

### PR DESCRIPTION
**Pull request by DougGregor**
Split these two functions into a fast path (for the cached case) and a slow
path. Make the slow path overridable, so we can patch it in the future if
needed.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Review by mikeash — APPROVED** [review]
Looks good! Can you add tests for these to `unittests/runtime/CompatibilityOverride.cpp`? Hopefully simple, the test doesn't need to actually pass sensible parameters, it just ensures that the override gets called when present.

This is probably not the right time for it, but I wonder if we can generate the tests themselves from the `.def` file too....

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@mikeash added!

**Comment by mikeash** [comment]
@DougGregor <3

**Pull request merged**
