### PR TITLE
[IRGen] Don't emit coverage maps for synthesized Clang decls

### LINKED ISSUE #57483: [SR-15160] swift-frontend: Assertion Loc.isValid() failed
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15160      |
   |Radar             | rdar://problem/82820628         |
   |Original Reporter | Catenacyber (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

This happens on Ubuntu

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 84212df75f8e2907575e1bf73e68e7b3

  </details>

**Issue Description:**

Found while trying to generate coverage for swift-nio project, 

Log stated 

\> Please submit a bug report (<https://swift.org/contributing/#reporting-bugs)> and include the project and the crash backtrace.

so here it is.

 

Complete build log can be found here :

<https://oss-fuzz-build-logs.storage.googleapis.com/log-ce87fb72-af21-43cd-be61-fa22cf3d190c.txt>

 

Relevant stack trace is

``` java
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64": swift-frontend: /home/build-user/llvm-project/clang/lib/Basic/SourceManager.cpp:1481: SrcMgr::CharacteristicKind clang::SourceManager::getFileCharacteristic(clang::SourceLocation) const: Assertion `Loc.isValid() && "Can't get file characteristic of invalid loc!"' failed.
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64": Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project and the crash backtrace.
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64": Stack dump:
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64": 0.   Program arguments: /usr/bin/swift-frontend -frontend -c /src/swift-nio/Sources/NIOHTTP1/ByteCollectionUtils.swift -primary-file /src/swift-nio/Sources/NIOHTTP1/HTTPDecoder.swift /src/swift-nio/Sources/NIOHTTP1/HTTPEncoder.swift /src/swift-nio/Sources/NIOHTTP1/HTTPPipelineSetup.swift /src/swift-nio/Sources/NIOHTTP1/HTTPServerPipelineHandler.swift /src/swift-nio/Sources/NIOHTTP1/HTTPServerProtocolErrorHandler.swift /src/swift-nio/Sources/NIOHTTP1/HTTPServerUpgradeHandler.swift /src/swift-nio/Sources/NIOHTTP1/HTTPTypes.swift /src/swift-nio/Sources/NIOHTTP1/NIOHTTPClientUpgradeHandler.swift /src/swift-nio/Sources/NIOHTTP1/NIOHTTPObjectAggregator.swift -emit-module-path /src/swift-nio/swift-nio-fuzz/.build/x86_64-unknown-linux-gnu/debug/NIOHTTP1.build/HTTPDecoder~partial.swiftmodule -emit-module-doc-path /src/swift-nio/swift-nio-fuzz/.build/x86_64-unknown-linux-gnu/debug/NIOHTTP1.build/HTTPDecoder~partial.swiftdoc -emit-module-source-info-path /src/swift-nio/swift-nio-fuzz/.build/x86_64-unknown-linux-gnu/debug/NIOHTTP1.build/HTTPDecoder~partial.swiftsourceinfo -emit-dependencies-path /src/swift-nio/swift-nio-fuzz/.build/x86_64-unknown-linux-gnu/debug/NIOHTTP1.build/HTTPDecoder.d -emit-reference-dependencies-path /src/swift-nio/swift-nio-fuzz/.build/x86_64-unknown-linux-gnu/debug/NIOHTTP1.build/HTTPDecoder.swiftdeps -target x86_64-unknown-linux-gnu -disable-objc-interop -I /src/swift-nio/swift-nio-fuzz/.build/x86_64-unknown-linux-gnu/debug -enable-testing -g -module-cache-path /src/swift-nio/swift-nio-fuzz/.build/x86_64-unknown-linux-gnu/debug/ModuleCache -profile-generate -profile-coverage-mapping -sanitize=fuzzer -swift-version 5 -Onone -D SWIFT_PACKAGE -D DEBUG -enable-anonymous-context-mangled-names -Xcc -fmodule-map-file=/src/swift-nio/swift-nio-fuzz/.build/x86_64-unknown-linux-gnu/debug/CNIOHTTPParser.build/module.modulemap -Xcc -I -Xcc /src/swift-nio/Sources/CNIOHTTPParser/include -Xcc -fmodule-map-file=/src/swift-nio/Sources/CNIOWindows/include/module.modulemap -Xcc -I -Xcc /src/swift-nio/Sources/CNIOWindows/include -Xcc -fmodule-map-file=/src/swift-nio/swift-nio-fuzz/.build/x86_64-unknown-linux-gnu/debug/CNIODarwin.build/module.modulemap -Xcc -I -Xcc /src/swift-nio/Sources/CNIODarwin/include -Xcc -fmodule-map-file=/src/swift-nio/swift-nio-fuzz/.build/x86_64-unknown-linux-gnu/debug/CNIOLinux.build/module.modulemap -Xcc -I -Xcc /src/swift-nio/Sources/CNIOLinux/include -Xcc -fmodule-map-file=/src/swift-nio/swift-nio-fuzz/.build/x86_64-unknown-linux-gnu/debug/CNIOAtomics.build/module.modulemap -Xcc -I -Xcc /src/swift-nio/Sources/CNIOAtomics/include -Xcc -O1 -Xcc -fno-omit-frame-pointer -Xcc -gline-tables-only -Xcc -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -Xcc -fprofile-instr-generate -Xcc -fcoverage-mapping -Xcc -pthread -Xcc -Wl,--no-as-needed -Xcc -Wl,-ldl -Xcc -Wl,-lm -Xcc -Wno-unused-command-line-argument -parse-as-library -module-name NIOHTTP1 -o /src/swift-nio/swift-nio-fuzz/.build/x86_64-unknown-linux-gnu/debug/NIOHTTP1.build/HTTPDecoder.swift.o -index-store-path /src/swift-nio/swift-nio-fuzz/.build/x86_64-unknown-linux-gnu/debug/index/store -index-system-modules -use-static-resource-dir 
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64": 1.   Swift version 5.4.2 (swift-5.4.2-RELEASE)
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64": 2.   While evaluating request IRGenRequest(IR Generation for file "/src/swift-nio/Sources/NIOHTTP1/HTTPDecoder.swift")
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64": 3.   Generating code for declaration '$So11http_parserV$status_code$getter'
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64":  #&#8203;0 0x00000000055f5914 PrintStackTraceSignalHandler(void*) (/usr/bin/swift-frontend+0x55f5914)
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64":  #&#8203;1 0x00000000055f350e llvm::sys::RunSignalHandlers() (/usr/bin/swift-frontend+0x55f350e)
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64":  #&#8203;2 0x00000000055f5af5 SignalHandler(int) (/usr/bin/swift-frontend+0x55f5af5)
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64":  #&#8203;3 0x00007faf77aa93c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x153c0)
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64":  #&#8203;4 0x00007faf7755018b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4618b)
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64":  #&#8203;5 0x00007faf7752f859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x25859)
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64":  #&#8203;6 0x00007faf7752f729 (/lib/x86_64-linux-gnu/libc.so.6+0x25729)
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64":  #&#8203;7 0x00007faf77540f36 (/lib/x86_64-linux-gnu/libc.so.6+0x36f36)
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64":  #&#8203;8 0x000000000522b561 clang::SourceManager::getFileCharacteristic(clang::SourceLocation) const (/usr/bin/swift-frontend+0x522b561)
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64":  #&#8203;9 0x0000000002aeaa62 clang::CodeGen::CodeGenPGO::emitCounterRegionMapping(clang::Decl const*) (/usr/bin/swift-frontend+0x2aeaa62)
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64": #&#8203;10 0x0000000002aea705 clang::CodeGen::CodeGenPGO::assignRegionCounters(clang::GlobalDecl, llvm::Function*) (/usr/bin/swift-frontend+0x2aea705)
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64": #&#8203;11 0x0000000002aa0a6a clang::CodeGen::CodeGenFunction::GenerateCode(clang::GlobalDecl, llvm::Function*, clang::CodeGen::CGFunctionInfo const&) (/usr/bin/swift-frontend+0x2aa0a6a)
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64": #&#8203;12 0x0000000002abdcdd clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/usr/bin/swift-frontend+0x2abdcdd)
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64": #&#8203;13 0x0000000002ab6abc clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/usr/bin/swift-frontend+0x2ab6abc)
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64": #&#8203;14 0x0000000002aab6d0 clang::CodeGen::CodeGenModule::EmitDeferred() (/usr/bin/swift-frontend+0x2aab6d0)
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64": #&#8203;15 0x0000000002aaa8c7 clang::CodeGen::CodeGenModule::Release() (/usr/bin/swift-frontend+0x2aaa8c7)
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64": #&#8203;16 0x0000000002b4ee24 (anonymous namespace)::CodeGeneratorImpl::HandleTranslationUnit(clang::ASTContext&) (/usr/bin/swift-frontend+0x2b4ee24)
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64": #&#8203;17 0x0000000000791d49 swift::irgen::IRGenModule::finalize() (/usr/bin/swift-frontend+0x791d49)
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64": #&#8203;18 0x000000000076a5cf swift::IRGenRequest::evaluate(swift::Evaluator&, swift::IRGenDescriptor) const (/usr/bin/swift-frontend+0x76a5cf)
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64": #&#8203;19 0x00000000007945e5 swift::GeneratedModule swift::SimpleRequest<swift::IRGenRequest, swift::GeneratedModule (swift::IRGenDescriptor), (swift::RequestFlags)9>::callDerived<0ul>(swift::Evaluator&, std::integer_sequence<unsigned long, 0ul>) const (/usr/bin/swift-frontend+0x7945e5)
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64": #&#8203;20 0x0000000000794539 swift::SimpleRequest<swift::IRGenRequest, swift::GeneratedModule (swift::IRGenDescriptor), (swift::RequestFlags)9>::evaluateRequest(swift::IRGenRequest const&, swift::Evaluator&) (/usr/bin/swift-frontend+0x794539)
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64": #&#8203;21 0x0000000000778ff7 llvm::Expected<swift::IRGenRequest::OutputType> swift::Evaluator::getResultUncached<swift::IRGenRequest>(swift::IRGenRequest const&) (/usr/bin/swift-frontend+0x778ff7)
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64": #&#8203;22 0x000000000076d5b2 swift::performIRGeneration(swift::FileUnit*, swift::IRGenOptions const&, swift::TBDGenOptions const&, std::unique_ptr<swift::SILModule, std::default_delete<swift::SILModule> >, llvm::StringRef, swift::PrimarySpecificPaths const&, llvm::StringRef, llvm::GlobalVariable**) (/usr/bin/swift-frontend+0x76d5b2)
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64": #&#8203;23 0x000000000051c325 performCompileStepsPostSILGen(swift::CompilerInstance&, std::unique_ptr<swift::SILModule, std::default_delete<swift::SILModule> >, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::PrimarySpecificPaths const&, int&, swift::FrontendObserver*) (/usr/bin/swift-frontend+0x51c325)
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64": #&#8203;24 0x000000000051b6e6 performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) (/usr/bin/swift-frontend+0x51b6e6)
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64": #&#8203;25 0x000000000050ffbe swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) (/usr/bin/swift-frontend+0x50ffbe)
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64": #&#8203;26 0x000000000049cb51 main (/usr/bin/swift-frontend+0x49cb51)
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64": #&#8203;27 0x00007faf775310b3 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b3)
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64": #&#8203;28 0x000000000049c66e _start (/usr/bin/swift-frontend+0x49c66e)
Step #&#8203;3 - "compile-libfuzzer-coverage-x86_64": ********************************************************************************
```

 

To reproduce you can, with Docker, run

git clone <https://github.com/google/oss-fuzz>

cd oss-fuzz

python infra/helper.py build_image swift-nio

python infra/helper.py build_fuzzers --sanitizer coverage --engine libfuzzer --architecture x86_64 swift-nio

### PR DESCRIPTION
**Pull request by hamishknight**
We don't need to perform coverage mapping for any Clang decls we've synthesized, as they have no user-written code. This is also needed to avoid a Clang crash when attempting to emit coverage for decls without source locations (rdar://100172217).

rdar://82820628
Resolves #57483

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please build toolchain

**Comment by hamishknight** [comment]
@swift-ci please build toolchain macOS

**Comment by hamishknight** [comment]
@swift-ci please test

**Review by beccadax — APPROVED** [review]
LGTM.

**Pull request merged**
