### PR TITLE
IRGen: Remove -gdwarf-types

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Review by compnerd — COMMENTED** [review]
This breaks functionality on Windows severely unfortunately.  Currently, the debugging on WIndows is reliant on PDBs and WinDBG (lldb is not even remotely ready) and that works by serializing the type information into the PDB.  Removing the option is fine, but please don't remove the generation bits.

**Comment by slavapestov** [comment]
@compnerd Ok, I'll leave this alone then. Thanks for speaking up!

**Pull request closed without merging**
