### PR TITLE
[5.3] Remove The Parser Hack For If-Let

### PR DESCRIPTION
**Pull request by CodaFi**
Cherry-pick #31760

––– Nomination Information –––
• Radar: rdar://problem/68154772
• Explanation: Swift has had a longstanding hack in its parser that would rewrite certain pattern bindings to insert a phantom optional type annotation. This type would get propagated down into semantic analysis and would influence the way the pattern was type checked. Subsequently, changes to pattern typechecking had the unintended effect of skipping an error about optionality mismatches in these special patterns. However, this skipping was inconsistent. After removing the parser hack - via the linked PR - the error surfaced once again consistently.
• Origination: The parser hack was introduced during the resolution of rdar://20883147
• Risk: Very Low. Source compatibility for external adopters should be preserved.
• Reviewed By: Doug Gregor

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci test source compatibility

**Review by DougGregor — APPROVED** [review]
The Core Team has approved this (minor) source break as a bug fix.

**Comment by CodaFi** [comment]
Oops, type resolution changes aren’t on this branch. Just a second.

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci test source compatibility

**Comment by CodaFi** [comment]
@swift-ci test source compatibility

**Comment by DougGregor** [comment]
The only failures are known ones. Merging

**Pull request merged**
