### PR TITLE
[5.5] include comments on SPI symbols when they're in symbol graphs

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
Resolves rdar://79695909

This PR ports #38070 to `release/5.5`.

**Change information**
- Explanation: When emitting a symbol graph with the `-include-spi-symbols` flag, the serialization code properly processes comments on SPI symbols.
- Scope of Issue: Currently, doc comments are stripped from SPI symbols in symbol graphs.
- Risk: Low.
- Automated Testing: The lit test "SymbolGraph/Symbols/Mixins/SPI" has been updated to exercise this change.

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Comment by QuietMisdreavus** [comment]
@swift-ci Please build toolchain macOS platform

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Comment by QuietMisdreavus** [comment]
@swift-ci Please build toolchain macOS platform

**Comment by QuietMisdreavus** [comment]
Using https://github.com/apple/llvm-project/pull/3070

@swift-ci Please test

**Comment by QuietMisdreavus** [comment]
Using https://github.com/apple/llvm-project/pull/3070

@swift-ci Please build toolchain macOS platform

**Comment by QuietMisdreavus** [comment]
Using apple/llvm-project#3070

@swift-ci Please test

**Comment by QuietMisdreavus** [comment]
Using apple/llvm-project#3070

@swift-ci Please build toolchain macOS platform

**Comment by QuietMisdreavus** [comment]
Using apple/llvm-project#3070

@swift-ci Please test

**Comment by QuietMisdreavus** [comment]
Using apple/llvm-project#3070

@swift-ci Please build toolchain macOS platform

**Comment by QuietMisdreavus** [comment]
```
FAIL: Swift(windows-x86_64) :: Concurrency/Runtime/checked_continuation.swift (986 of 7555)
```

Using apple/llvm-project#3070

@swift-ci Please test

**Comment by QuietMisdreavus** [comment]
Failed in the SwiftPM tests?

Using apple/llvm-project#3070

@swift-ci Please test macOS platform

**Review by akyrtzi — APPROVED** [review]

**Pull request merged**
