### PR TITLE
Update algorithm to insert dealloc_stack for partial_apply [on_stack]

### PR DESCRIPTION
**Pull request by meg-gupta**
A partial_apply [on_stack] can be copied via copy_value. In such cases, dealloc_stack for the partial_apply should be at the boundary of lifetime ends of both partial_apply and the copies while lowering to non-ossa.
Without this, we may end up inserting a dealloc_stack earlier than some of the partial_apply [on_stack]  uses.

### CODE REVIEW

**Comment by meg-gupta** [comment]
A similar fix is needed for SILCloner, but it is blocked on another issue. PR for SILCloner will follow.

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test

**Review by atrick — APPROVED** [review]
This is really nice! All up to the last commit where we lower ownership in the middle of the standard SIL cloner.

With the SIL cloner, it would be nicer if the partial apply lifetime information were contained in a separate utility, like maybe an OwnershipLoweringCloner subclass. And the deallocs were only inserted at the end as a post-pass that revisited the lifetime ending instructions, rather than doing it on-the-fly, complicating the normal cloner. I don't know if that's possible.

**Comment by meg-gupta** [comment]
This PR was intended to fix the insertion of dealloc_stack if the copy's lifetime end was after the partial_apply's lifetime end. In practice this can't happen today. Closing this PR.

**Pull request closed without merging**
