### PR TITLE
Cleaning up _runAsyncMain a bit

### PR DESCRIPTION
**Pull request by etcwilde**
I'm making two cleanups here. First, the closure going into
`_runAsyncMain` needs to be `@Sendable` or passing it to the task is not
safe. This will also result in a warning being emitted.
Second, I'm making this @usableFromInline and `internal`. This function
is around for legacy reasons, but it's part of the ABI, so we can't pull
it out entirely, but we don't want folks using it.

rdar://74942340

### CODE REVIEW

**Comment by etcwilde** [comment]
@swift-ci please test

**Comment by etcwilde** [comment]
@swift-ci please test

**Comment by etcwilde** [comment]
@swift-ci please test

**Comment by etcwilde** [comment]
@swift-ci please test

**Comment by etcwilde** [comment]
Windows builds are currently broken due to https://github.com/apple/llvm-project/pull/3537.
`LINK : fatal error LNK1181: cannot open input file 'swiftCompilerModules.lib'`

PR https://github.com/apple/llvm-project/pull/3736 reverts that PR and will fix the issue.
Failing build: https://ci-external.swift.org/job/swift-PR-windows/19556.

**Comment by etcwilde** [comment]
@swift-ci please test

**Comment by etcwilde** [comment]
@swift-ci please test linux

**Comment by etcwilde** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]

**Comment by hamishknight** [comment]
This caused `api-digester/stability-concurrency-abi.test` to start failing on CI https://ci.swift.org/job/oss-swift-pr-test-macoss/139/. Looks like a conflict with https://github.com/apple/swift/pull/41253.

Reverting in https://github.com/apple/swift/pull/41689.

**Comment by etcwilde** [comment]
> This caused `api-digester/stability-concurrency-abi.test` to start failing on CI https://ci.swift.org/job/oss-swift-pr-test-macoss/139/. Looks like a conflict with #41253.
> 
> Reverting in #41689.

yeah, I probably should have re-run that before merging. I can't see the CI at the moment. I'm getting a 403 again.

**Pull request merged**
