### PR TITLE
Revert "Give multi-payload enums extra inhabitants."

### PR DESCRIPTION
**Pull request by xedin**
Reverts apple/swift#20561

Trying to see if this caused failures in Kickstarter, Reactive{Cocoa, Swift}

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please smoke test Linux platform

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by jckarter** [comment]
Thanks! I think I can fix this fairly quickly though.

**Comment by jckarter** [comment]
https://github.com/apple/swift/pull/20582 should fix this.

**Pull request closed without merging**
