### PR TITLE
[Interop] [SwiftToCxx] Using the hardcode noexcept flags on the compiler only to non throwing functions

### PR DESCRIPTION
**Pull request by Robertorosmaninho**
This PR aims to modify the use of the hardcode flags that, so far, represented an unreal behavior from Swift functions that assume that every function doesn't throw an exception. The tests introduced by this [PR](#59217) show the need for a new implementation to handle thrown functions. 

This PR enable the tests [swift-functions-errors.swift](https://github.com/apple/swift/compare/main...Robertorosmaninho:interop/SwiftToCxxErrorHandling?expand=1#diff-95751b9663a6f895f190092c7a3a130983b4f5b21ee32c50dfbfe7f34a92a438) and  [swift-functions-errors-execution.cpp](https://github.com/apple/swift/compare/main...Robertorosmaninho:interop/SwiftToCxxErrorHandling?expand=1#diff-6e56f9a7dcc273e66801494f1c061fea4dc4a6e90ace005f2c4968f652a51c09) and check that are correctly passing.

The main idea of this PR is to insert a condition to print the `SWIFT_NOEXCEPT` and the `noexcept` on the functions inside the bridging header files generated by Swift to interop with C++.

### CODE REVIEW

**Comment by Robertorosmaninho** [comment]
Hey @hyp, could you check if you agree with these modifications? If yes, could you call swift-ci to run the necessary tests?

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
Interestingly enough, it fails on watchOS 32 bit simulator. The tests look fine to me, so I wonder what's wrong. We can XFAIl it for the 32 bit simulator, but perhaps you can take a look at the Swift IR to see what would be the expected call that we have to make, and why exactly are we failing? I suspect we might need to pass a parameter to the function.

**Comment by Robertorosmaninho** [comment]
>  We can XFAIl it for the 32 bit simulator, but perhaps you can take a look at the Swift IR to see what would be the expected call that we have to make, and why exactly are we failing? 
Do you mean the SIL generated for the `swift-functions-errors.swift`?

> I suspect we might need to pass a parameter to the function.
An argument on each function defined by us?

Is there a way to test reproduce this test locally? If so, how can I do it?

**Comment by hyp** [comment]
We should look at the LLVM IR generated there.

I don't think there's an easy way to reproduce this but we can try compiling the Swift file for 32 bit watchOS target and then dumping the LLVM IR for it. This will let us investigate it. Also, if you have access to Xcode you can try making an Xcode project that builds for watchOS simulator and create a simple Swift file that has a function that throws an error like in your test and investigate its IR. What kind of signature what a function like that have in LLVM IR?

**Comment by hyp** [comment]
yes, in the IR you can see that we're writing to the error pointer:

```
  store i8 1, i8* %99, align 1
  store %swift.error* %95, %swift.error** %1, align 4
  call swiftcc void @swift_willThrow(i8* swiftself undef, %swift.error** noalias nocapture readonly dereferenceable(4) %1) #7
  store %swift.error* null, %swift.error** %1, align 4
  store %swift.error* %95, %swift.error** %1, align 4
```

we will need to model the error parameter in the C function signature, and then pass in a dummy pointer to get it to work for now without even supporting error.

**Comment by hyp** [comment]
Let me check what we can use from IRGen to model that.

**Comment by hyp** [comment]
We will need to provide access to `SignatureExpansion` that is able to tell us to add `self` and `error parameter` through `IRABIDetailsProvider`. Let me think about a reasonable approach for this. Unfortunately there's no easy solution, we'll have deep dig and extract/refactor some code out.

**Pull request closed without merging**
