### PR TITLE
[Type checker] Introduce requests for @objc, override, and 'dynamic' checking

### PR DESCRIPTION
**Pull request by DougGregor**
Introduce new type checker requests to cover three more aspects of type-checking the interface of a declaration, peeled off from `validateDecl` and mostly separated from the type checker:

* `ValueDecl::getOverriddenDecl(s)`: determines which declaration(s) are overridden by a given declaration
* `ValueDecl::isObjC()`: determines whether the given declaration is exposed to Objective-C.
* `ValueDecl::isDynamic()`: a replacement for directly querying `DynamicAttr` on a declaration, this determines whether a particular declaration is 'dynamic'.

All of these effectively need to be done together to break down otherwise-cyclic dependencies, e.g., because `@objc` can be inherited from an override and `dynamic` is dependent on `@objc` (as well as being inherited).

### CODE REVIEW

**Comment by DougGregor** [comment]
The computation of 'dynamic' was also tangled up with `@objc` and overrides, so separate that into its own request.

**Comment by DougGregor** [comment]
Rebased. Here goes nothing!

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please test compiler performance

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please test compiler performance

**Comment by DougGregor** [comment]
Well, that went poorly.

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
Nice! I believe this will also fix [SR-5317] :)

[SR-5317]: https://bugs.swift.org/browse/SR-5317

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please test compiler performance

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please smoke test macOS

**Comment by DougGregor** [comment]
@swift-ci please smoke test Linux

**Comment by DougGregor** [comment]
@swift-ci please test Linux

**Comment by DougGregor** [comment]
@swift-ci please test Linux

**Pull request merged**
