### PR TITLE
[overlay] Make an overlay for the clang _Builtin_float module

### PR DESCRIPTION
**Pull request by ian-twilightcoder**
Clang's builtin float.h is no longer included in OS/SDK modules, and so it needs its own overlay.

rdar://122351557

### CODE REVIEW

**Comment by ian-twilightcoder** [comment]
@swift-ci smoke test

**Comment by ian-twilightcoder** [comment]
@swift-ci test

**Comment by ian-twilightcoder** [comment]
```
/Users/ec2-user/jenkins/workspace/swift-PR-macos-smoke-test/branch-main/swift/test/stdlib/FloatConstants.swift:21:5: error: unexpected error produced: ambiguous use of 'FLT_RADIX'
_ = FLT_RADIX // expected-warning {{is deprecated}}
    ^
```
Hmm, we need some way to figure out if _Builtin_Float actually declares anything...

**Comment by ian-twilightcoder** [comment]
> ```
> /Users/ec2-user/jenkins/workspace/swift-PR-macos-smoke-test/branch-main/swift/test/stdlib/FloatConstants.swift:21:5: error: unexpected error produced: ambiguous use of 'FLT_RADIX'
> _ = FLT_RADIX // expected-warning {{is deprecated}}
>     ^
> ```
> 
> Hmm, we need some way to figure out if _Builtin_Float actually declares anything...

No wait, this is a problem with the test. `_Builtin_Float` should never be directly imported, it will come in via one of the other modules if `-fbuiltin-headers-in-system-modules` is not used.

**Comment by ian-twilightcoder** [comment]
@swift-ci smoke test

**Comment by ian-twilightcoder** [comment]
Hmm, does this one make sense to anyone?
```
C:/Users/swift-ci/jenkins/workspace/swift-PR-windows/swift/stdlib/public/ClangOverlays/float.swift.gyb:25:36: error: type 'Float80' has no member 'significandBitCount'
```

**Comment by ian-twilightcoder** [comment]
@swift-ci smoke test Windows

**Comment by ian-twilightcoder** [comment]
> Hmm, does this one make sense to anyone?
> 
> ```
> C:/Users/swift-ci/jenkins/workspace/swift-PR-windows/swift/stdlib/public/ClangOverlays/float.swift.gyb:25:36: error: type 'Float80' has no member 'significandBitCount'
> ```

Ah, the different overlays did different things with Float80, they just need to be conditionalized by os.

**Comment by ian-twilightcoder** [comment]
@swift-ci smoke test

**Comment by ian-twilightcoder** [comment]
@swift-ci test

**Comment by ian-twilightcoder** [comment]
@swift-ci smoke test

**Comment by ian-twilightcoder** [comment]
@swift-ci test

**Comment by ian-twilightcoder** [comment]
@swift-ci smoke test

**Comment by ian-twilightcoder** [comment]
@swift-ci test

**Comment by ian-twilightcoder** [comment]
@swift-ci smoke test

**Comment by ian-twilightcoder** [comment]
@swift-ci test

**Comment by ian-twilightcoder** [comment]
@swift-ci smoke test

**Comment by ian-twilightcoder** [comment]
@swift-ci test

**Comment by ian-twilightcoder** [comment]
@swift-ci smoke test

**Comment by ian-twilightcoder** [comment]
@swift-ci test

**Review by edymtt — APPROVED** [review]

**Pull request merged**
