### PR TITLE
Some fixes for DynamicSelfType

### PR DESCRIPTION
**Pull request by slavapestov**
- <https://bugs.swift.org/browse/SR-9429>
- <https://bugs.swift.org/browse/SR-9430>
- <rdar://problem/32288771>
- <rdar://problem/46982573>

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Review by jckarter — APPROVED** [review]
LGTM, thanks Slava!

**Comment by slavapestov** [comment]
Thanks for taking a look. There’s one test failure but I don’t expect the fix to require radical changes.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Pull request merged**
