### PR TITLE
Don't print extensions to conform to protocols that aren't printed

### PR DESCRIPTION
**Pull request by jrose-apple**
Try a little harder to avoid printing empty extensions by seeing if any of the inherited protocols are actually going to be printed. Previously this just made things a little prettier, but with implementation-only imports it's a correctness issue, since there may be extensions of implementation-only types that do in fact conform to non-public protocols.

rdar://problem/50748072

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
Ugh, didn't mean to put this in the main repo either, but it's already running tests…

**Comment by jrose-apple** [comment]
iOS sim failure looks unrelated, but I'll wait to see if more bots hit it before restarting.

**Comment by jrose-apple** [comment]
@swift-ci Please test macOS

**Comment by jrose-apple** [comment]
This time an unrelated failure in LLDB.

@swift-ci Please test macOS

**Review by rintaro — APPROVED** [review]

**Review by beccadax — APPROVED** [review]

**Pull request merged**
