### PR TITLE
[WIP] [Syntax] Documentation generation for Syntax nodes

### PR DESCRIPTION
**Pull request by harlanhaskins**
This PR adds an infrastructure for documenting Syntax nodes and their children, and inserts that documentation in the node definitions. Lots more work needs to be done actually writing this documentation.

### CODE REVIEW

**Review by nkcsgexi — APPROVED** [review]
LGTM!

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test and merge

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test and merge

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test and merge

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test and merge

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test and merge

**Comment by harlanhaskins** [comment]
Tests passed, but the merge failed?

**Pull request merged**
