### PR TITLE
[5.1] Return elision SE-255

### PR DESCRIPTION
**Pull request by nate-chandler**

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci Please smoke test OS X platform

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please clean test

**Comment by CodaFi** [comment]
In the future, could you please squash patches like this down to just a few commits?  This should go into 5.1 the same way it went into master though.

**Pull request merged**
