### PR TITLE
Fix SIL mandatory inlining crash that could occur with public override of an internal property

### PR DESCRIPTION
**Pull request by slavapestov**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

Radar: rdar://problem/26408353

### CODE REVIEW

**Comment by slavapestov** [comment]
Can I please get a review from one of:

- @bitjammer You worked in this area most recently
- @jckarter Benevolent SIL overlord

**Comment by bitjammer** [comment]
LGTM.

**Comment by tkremenek** [comment]
@swift-ci test linux
@swift-ci smoke test os x platform

**Comment by tkremenek** [comment]
@swift-ci test linux

**Comment by jckarter** [comment]
Looks good.

**Pull request merged**
