### PR TITLE
[Gardening] Remove An Unused TLCD Checking Entrypoint

### PR DESCRIPTION
**Pull request by CodaFi**
We appear to have internalized all of the callers here some time ago.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci smoke test and merge

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Review by slavapestov — APPROVED** [review]

**Comment by CodaFi** [comment]
@swift-ci smoke test Linux platform

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
