### PR TITLE
[gardening] Remove bool tableIsAlive and call to isVisibleExternally(…)

### PR DESCRIPTION
**Pull request by practicalswift**

### CODE REVIEW

**Comment by practicalswift** [comment]
@swift-ci please smoke test

**Comment by practicalswift** [comment]
@swift-ci please test

**Comment by practicalswift** [comment]
`tableIsAlive` was introduced by commit d3b2336366d6b5dddf6b2d4e0b81b2d992841d00 yesterday :-)

**Comment by hughbe** [comment]
I think https://github.com/apple/swift/pull/6468 beat you to it :D

**Pull request closed without merging**
