### PR TITLE
[Frontend] Populate files in getMainModule

### PR DESCRIPTION
**Pull request by hamishknight**
Rather than waiting until one of the `performXXX` methods are called on the `CompilerInstance`, populate the main module's files up-front when `getMainModule` is called.

This allows us to remove `performParseOnly` in favour of lazy parsing, and allows us to inline `performSemaUpTo` into `performParseAndResolveImportsOnly` & `performSema`.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility Release

**Review by CodaFi — APPROVED** [review]

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Pull request merged**
