### PR TITLE
[benchmark] Janitor Duty: Sweep I

### PR DESCRIPTION
**Pull request by palimondo**
A little bit of benchmark cleanup.

### CODE REVIEW

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
@swift-ci please smoke test

**Comment by palimondo** [comment]
@eeckstein Please review 🙏

**Comment by eeckstein** [comment]
basically lgtm.
Does it make sense to rename the ArrayLiteral benchmark?

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
@swift-ci please smoke test

**Comment by palimondo** [comment]
@swift-ci please smoke test

**Comment by palimondo** [comment]
@swift-ci please smoke test

**Comment by palimondo** [comment]
@eeckstein Hmm… from the above report, I would argue that we should not rename the `ArrayLiteral` benchmark, as the `-Osize` and `-Onone` performance was unchanged and only the `-O` is being fixed by the `blackHole` application to go from `0` to some regular number.

**Review by eeckstein — APPROVED** [review]
ok, LGTM

**Comment by palimondo** [comment]
I’m confused now. You approved this with the changed name… Do you want me to merge this as is (`ArrayLiteral2`) or with original name `ArrayLiteral` (the version before last force push) to maintain tracking continuity in `-Osize` and `-Onone`?

**Comment by eeckstein** [comment]
Please merge it as is (with ArrayLiteral2)

**Pull request merged**
