### PR TITLE
[passmanager] Change SIL pass pipeline plan to use an LLVM YAML representation.

### PR DESCRIPTION
**Pull request by gottesmm**
This eliminates a bunch of code and will make it significantly easier to
maintain/add to this code/use this code.

Just had this on a branch. This should make it really easy to fuzz the optimizer by manipulating the pass pipeline. I wonder if we could even use a libfuzzer based approach.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci test linux platform

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by gottesmm** [comment]
I want to fix a couple of things in this area. So I am going to fix this real quick.

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Review by atrick — COMMENTED** [review]
Looks simpler to me!

**Pull request merged**
