### PR TITLE
Remove @inlinable from some .description properties

### PR DESCRIPTION
**Pull request by airspeedswift**
Inlineability shouldn't matter in these cases, running some benchmarks to see.

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by xwu** [comment]
Q: ...shouldn't matter even if users access the description property directly?

**Comment by airspeedswift** [comment]
They're not generic (well, apart from `AnyHashable`) so it shouldn't be important for them to be inlinable in order to be specialized.

**Comment by natecook1000** [comment]
@airspeedswift Checking on old PRs — is this work still valid?

**Comment by CodaFi** [comment]
I think the change is good but the PR is stale.

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
