### PR TITLE
[WIP] Demangle extension contexts at runtime

### PR DESCRIPTION
**Pull request by jckarter**
TODO:

- still need to fix extensions of extensions
- handle real same-type constraints

### CODE REVIEW

**Comment by slavapestov** [comment]
What is an extension of an extension?

**Comment by jckarter** [comment]
@slavapestov An extension of a nested type defined in an extension, sorry.

**Comment by jckarter** [comment]
Like the currently failing test case here: https://github.com/apple/swift/pull/16287/files#diff-21ee09231cf6e8a275005fbdcbc60f5eR350

**Comment by slavapestov** [comment]
Oh I see, thanks.

**Comment by DougGregor** [comment]
I picked up this commit in https://github.com/apple/swift/pull/16533

**Pull request closed without merging**
