### PR TITLE
[5.7] Separate out ASCII and UTF8 in NSString accessors, and use the ASCII one where we really need ASCII

### PR DESCRIPTION
**Pull request by Catfish-Man**
Cherry pick of https://github.com/apple/swift/pull/61086

### CODE REVIEW

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Review by stephentyrone — APPROVED** [review]

**Pull request merged**
