### PR TITLE
[rebranch] Manually merge main

### PR DESCRIPTION
**Pull request by sophiapoirier**
Conflicts caused by `llvm::` on rebranch for `SmallSetVector`.

### CODE REVIEW

**Comment by sophiapoirier** [comment]
@gottesmm all of the conflicts came from https://github.com/apple/swift/commit/37d60a08bbfcce95d97e7dd9efaed97712ee3227

**Comment by sophiapoirier** [comment]
@swift-ci please build

**Comment by sophiapoirier** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by sophiapoirier** [comment]
@swift-ci please test

**Pull request merged**
