### PR TITLE
[4.0][Exclusivity] Suggest Fix-Its to replace swap() with swapAt()

### PR DESCRIPTION
**Pull request by devincoughlin**
Extend the static diagnostics for exclusivity violations to suggest replacing

  swap(&collection[index1], &collection[index2]

with

  collection.swapAt(index1, index2).

when 'collection' is a MutableCollection.

To do so, repurpose some vestigial code that was previously used to suppress all
exclusivity diagnostics for calls to swap() and add some additional syntactic,
semantic,  and textual pattern matching.

rdar://problem/31916085

### CODE REVIEW

**Comment by devincoughlin** [comment]
@bitjammer Would you be willing to review this Fix-It to suggest replacing swap() with collection.swapAt() for CCC for inclusion into swift-4.0-branch?

**Comment by bitjammer** [comment]
Sure thing.

**Review by bitjammer — APPROVED** [review]
Looks great. Have you checked to see if the migrator picks up on these changes as expected?

**Comment by devincoughlin** [comment]
CCC Information
Explanation: Add a Fix-It to to suggest uses of swap() that violate exclusivity to use
MutableCollection's swapAt() instead when it is safe to do so.

Scope: This affects clients of the Standard Library's swap() API who use to
on collections. This is relatively rare, but is used in some generic
algorithms. Without this, some people who adopt Swift 4 will get compile-time
errors rather than be able to have the fix suggested for them.

Radar: <rdar://problem/32284514>
Risk: This as a relatively low-risk change. The new code path only kicks in
for functions that call swap() (which is quite rare) and it only occurs in
situations in which the compiler would already diagnose a warning or an error.

Testing: We've extended the regression tests and also manually tested on a
simple sample project.

**Comment by devincoughlin** [comment]
@swift-ci Please smoke test

**Comment by devincoughlin** [comment]
@swift-ci please test

**Pull request merged**
