### PR TITLE
[build] Remove unused `GLIBC_INCLUDE_PATH` macro

### PR DESCRIPTION
**Pull request by egorzhdan**
This macro was previously substituted when generating `glibc.modulemap` file during the compiler build. Now Swift detects the location of Glibc dynamically and injects `glibc.modulemap` into it using LLVM VFS. The last usage of `GLIBC_INCLUDE_PATH` was removed in 78c0540b.

This also removes `SWIFT_SDK_${sdk}_ARCH_${arch}_LIBC_INCLUDE_DIRECTORY` which doesn't have any usages left.

### CODE REVIEW

**Comment by egorzhdan** [comment]
cc @buttaface @3405691582

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Review by compnerd — APPROVED** [review]
Seems like a reasonable cleanup.

**Review by finagolfin — APPROVED** [review]
Glad to see this gone, but [you missed one that @3405691582 added recently](https://github.com/apple/swift/pull/60823/files#diff-93f5cec01637ba26aaa5615da2a16fa1dcd382d8eee2b07f3bd18551396b6a85R410).

Pinging @kateinoigakukun to sign off on WASI change.

**Comment by egorzhdan** [comment]
> Glad to see this gone, but [you missed one that @3405691582 added recently](https://github.com/apple/swift/pull/60823/files#diff-93f5cec01637ba26aaa5615da2a16fa1dcd382d8eee2b07f3bd18551396b6a85R410).

Thanks, forgot to update my checkout :)

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Review by kateinoigakukun — APPROVED** [review]
Thank you for cleaning up :)

**Pull request merged**
