### PR TITLE
SSE no more

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
@CC: moiseev

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by gottesmm** [comment]
This looks reasonable to me. @moiseev is there anything holding up this pr?

**Comment by moiseev** [comment]
Not sure what's going on, but looks harmless =)

**Comment by compnerd** [comment]
@moiseev, haha, its nothing invasive.  Just some harmless renaming to make it plausible to merge the x86_64/s390x codepaths with aarch64 in the future.

**Pull request merged**
