### PR TITLE
Fix asyncMainDrainQueue noreturn warning

### PR DESCRIPTION
**Pull request by etcwilde**
The async main drain queue function is noreturn, but was emitting a warning due to the override compatibility returning the result of the overridden function in the wrapper override function. To work around this, I've added the `OVERRIDE_TASK_NORETURN` macro, which provides an override point for noreturn functions in the concurrency library that doesn't return the result from the wrapped function, avoiding the warning. In the event that the function is not set, the macro is set to the normal `OVERRIDE` with the return type set to `void`.

rdar://85521851

### CODE REVIEW

**Comment by etcwilde** [comment]
@swift-ci please test

**Comment by etcwilde** [comment]
macOS:
```
ld: warning: Could not find or use auto-linked library 'SwiftParserDiagnostics'
ld: warning: Could not find or use auto-linked library 'SwiftBasicFormat'
ld: warning: Could not find or use auto-linked library '_SwiftSyntaxMacros'
ld: warning: Could not find or use auto-linked library 'SwiftParser'
ld: warning: Could not find or use auto-linked library 'SwiftSyntaxBuilder'
ld: warning: Could not find or use auto-linked library 'SwiftSyntax'
ld: warning: Could not find or use auto-linked library 'SwiftDiagnostics'
ld: warning: Could not find or use auto-linked library 'SwiftOperators'
Undefined symbols for architecture x86_64:
  "type metadata accessor for SwiftParserDiagnostics.ParseDiagnosticsGenerator", referenced from:
      closure #1 () -> Swift.Int32 in SwiftCompilerSupport._parserConsistencyCheck(bufferPtr: Swift.UnsafePointer<Swift.UInt8>, bufferLength: Swift.Int, filename: Swift.UnsafePointer<Swift.UInt8>, flags: Swift.UInt32, hookCtx: Swift.OpaquePointer, diagnosticHook: @convention(c) (Swift.Int, Swift.UnsafePointer<Swift.Int8>, Swift.OpaquePointer) -> ()) -> Swift.Int32 in libSwiftCompilerSupport.a(ConsistencyCheck.swift.o)
      closure #1 () throws -> A in closure #1 (Swift.UnsafeBufferPointer<Swift.UInt8>) throws -> A in (extension in SwiftSyntaxBuilder):SwiftSyntaxBuilder.SyntaxExpressibleByStringInterpolation.init(stringInterpolationOrThrow: SwiftSyntaxBuilder.SyntaxStringInterpolation) throws -> A in libSwiftSyntaxBuilder.a(Syntax+StringInterpolation.swift.o)
  "static SwiftParserDiagnostics.ParseDiagnosticsGenerator.diagnostics<A where A: SwiftSyntax.SyntaxProtocol>(for: A) -> [SwiftDiagnostics.Diagnostic]", referenced from:
      closure #1 () -> Swift.Int32 in SwiftCompilerSupport._parserConsistencyCheck(bufferPtr: Swift.UnsafePointer<Swift.UInt8>, bufferLength: Swift.Int, filename: Swift.UnsafePointer<Swift.UInt8>, flags: Swift.UInt32, hookCtx: Swift.OpaquePointer, diagnosticHook: @convention(c) (Swift.Int, Swift.UnsafePointer<Swift.Int8>, Swift.OpaquePointer) -> ()) -> Swift.Int32 in libSwiftCompilerSupport.a(ConsistencyCheck.swift.o)
      closure #1 () throws -> A in closure #1 (Swift.UnsafeBufferPointer<Swift.UInt8>) throws -> A in (extension in SwiftSyntaxBuilder):SwiftSyntaxBuilder.SyntaxExpressibleByStringInterpolation.init(stringInterpolationOrThrow: SwiftSyntaxBuilder.SyntaxStringInterpolation) throws -> A in libSwiftSyntaxBuilder.a(Syntax+StringInterpolation.swift.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

Linux:
```
In file included from /home/build-user/swift/stdlib/public/Concurrency/Task.cpp:1582:
/home/build-user/swift/stdlib/public/Concurrency/../CompatibilityOverride/CompatibilityOverrideConcurrency.def:162:1: error: unknown type name 'Override_task_asyncMainDrainQueue'
OVERRIDE_TASK_NORETURN(task_asyncMainDrainQueue,
^
/home/build-user/swift/stdlib/public/Concurrency/Task.cpp:1572:12: note: expanded from macro 'OVERRIDE_TASK_NORETURN'
    static Override_##name Override;                                           \
           ^
<scratch space>:152:1: note: expanded from here
Override_task_asyncMainDrainQueue
^
In file included from /home/build-user/swift/stdlib/public/Concurrency/Task.cpp:1582:
/home/build-user/swift/stdlib/public/Concurrency/../CompatibilityOverride/CompatibilityOverrideConcurrency.def:162:1: error: use of undeclared identifier 'getOverride_task_asyncMainDrainQueue'; did you mean 'swift_task_asyncMainDrainQueue'?
/home/build-user/swift/stdlib/public/Concurrency/Task.cpp:1575:45: note: expanded from macro 'OVERRIDE_TASK_NORETURN'
        &Predicate, [](void *) { Override = getOverride_##name(); }, nullptr); \
                                            ^
<scratch space>:153:1: note: expanded from here
getOverride_task_asyncMainDrainQueue
^
/home/build-user/swift/stdlib/public/Concurrency/../CompatibilityOverride/CompatibilityOverrideConcurrency.def:162:1: note: 'swift_task_asyncMainDrainQueue' declared here
/home/build-user/swift/stdlib/public/Concurrency/Task.cpp:1571:32: note: expanded from macro 'OVERRIDE_TASK_NORETURN'
  attrs ccAttrs void namespace swift_##name COMPATIBILITY_PAREN(typedArgs) {   \
                               ^
<scratch space>:150:1: note: expanded from here
swift_task_asyncMainDrainQueue
^
```

Windows:
```
In file included from C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\stdlib\public\Concurrency\Task.cpp:1582:
C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\stdlib\public\Concurrency/../CompatibilityOverride/CompatibilityOverrideConcurrency.def(162,1): error: unknown type name 'Override_task_asyncMainDrainQueue'
OVERRIDE_TASK_NORETURN(task_asyncMainDrainQueue,
^
C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\stdlib\public\Concurrency\Task.cpp(1572,12): note: expanded from macro 'OVERRIDE_TASK_NORETURN'
    static Override_##name Override;                                           \
           ^
<scratch space>(48,1): note: expanded from here
Override_task_asyncMainDrainQueue
^
In file included from C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\stdlib\public\Concurrency\Task.cpp:1582:
C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\stdlib\public\Concurrency/../CompatibilityOverride/CompatibilityOverrideConcurrency.def(162,1): error: use of undeclared identifier 'getOverride_task_asyncMainDrainQueue'; did you mean 'swift_task_asyncMainDrainQueue'?
C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\stdlib\public\Concurrency\Task.cpp(1575,45): note: expanded from macro 'OVERRIDE_TASK_NORETURN'
        &Predicate, [](void *) { Override = getOverride_##name(); }, nullptr); \
                                            ^
<scratch space>(49,1): note: expanded from here
getOverride_task_asyncMainDrainQueue
^
C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\stdlib\public\Concurrency/../CompatibilityOverride/CompatibilityOverrideConcurrency.def(162,1): note: 'swift_task_asyncMainDrainQueue' declared here
C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\stdlib\public\Concurrency\Task.cpp(1571,32): note: expanded from macro 'OVERRIDE_TASK_NORETURN'
  attrs ccAttrs void namespace swift_##name COMPATIBILITY_PAREN(typedArgs) {   \
                               ^
<scratch space>(46,1): note: expanded from here
swift_task_asyncMainDrainQueue
^
```

**Comment by etcwilde** [comment]
@swift-ci please test

**Review by mikeash — APPROVED** [review]
Looks good, thanks!

**Comment by etcwilde** [comment]
Linux:
```
/tmp/lit-tmp-hv4anj_5/async_task_detach-aedf8a.o:async_task_detach-aedf8a.o:function main: error: undefined reference to 'swift_task_asyncMainDrainQueue'
```

Windows:
```
_Concurrency.obj : error LNK2019: unresolved external symbol swift_task_asyncMainDrainQueue referenced in function $ss13_runAsyncMainyyyyYaKcF
```

**Comment by etcwilde** [comment]
@swift-ci please test

**Comment by etcwilde** [comment]
@mikeash I had some fun writing that test. Turns out it's pretty tricky testing a `noreturn` function when you need to return control to validate the run of the test. I used pthreads, but if you have any better ideas, I'm all ears.

**Comment by mikeash** [comment]
I don't think I have any better ideas. You could get out of it by throwing an exception, but I don't think that qualifies as "better."

**Comment by etcwilde** [comment]
macOS failure:
`swift/SwiftCompilerSources/Sources/Basic/SourceLoc.swift:63:49: error: value of type 'swift.CharSourceRange' has no member 'getByteLength'
    self.init(start: start, byteLength: bridged.getByteLength())`

Not my fault this time.

**Comment by etcwilde** [comment]
@swift-ci please test macOS

**Comment by etcwilde** [comment]
macOS failure should be fixed by: https://github.com/apple/swift/pull/64029

**Comment by etcwilde** [comment]
@swift-ci please test macOS

**Pull request merged**
