### PR TITLE
[NFC] Clean Up FrontendTool

### PR DESCRIPTION
**Pull request by CodaFi**
Try to impose a simple structure that splits performing actions from the
pre and post-pipeline conditions. Wherever actions would take more than
a simple return, split them into functions. Refine functions that
perform effects to return status codes when they fail. Finally,
delineate functions that need semantic analysis from those that do not.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci test source compatibility

**Review by hamishknight — APPROVED** [review]
Very nice!

**Comment by CodaFi** [comment]
@swift-ci test Linux

**Comment by CodaFi** [comment]
@swift-ci clean test Linux

**Comment by CodaFi** [comment]
@swift-ci test Windows

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
