### PR TITLE
[SR-13466]: Fix demangling of optionals containing function types.

### PR DESCRIPTION
**Pull request by al45tair**
ImplFunctionType nodes inside optionals are wrapped in Type nodes,
which means that isSimpleType() needs to look through the Type node
when we're printing them, or we fail to wrap them with parentheses.

<rdar://67915116>

### CODE REVIEW

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Review by eeckstein — APPROVED** [review]
LGTM!

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
@swift-ci Please clean smoke test macOS platform

**Pull request merged**
