### PR TITLE
[Docs] s/OS X/macOS/.

### PR DESCRIPTION
**Pull request by huonw**

### CODE REVIEW

**Comment by huonw** [comment]
@swift-ci please smoke test

**Comment by huonw** [comment]
@shahmishal, could you confirm that the triggers all respond to "macOS" instead of/as well as "OS X"?

**Review by shahmishal — COMMENTED** [review]
Check status have not been updated to use macOS yet, hopefully I will get to it soon.

**Comment by huonw** [comment]
@shahmishal have you had time for this? (It's not a priority at all, just going through older PRs.)

**Comment by CodaFi** [comment]
@shahmishal One more ping here.  Did the check status commands get updated?

**Comment by shahmishal** [comment]
Not yet, we can close this for now.

**Pull request closed without merging**
