### PR TITLE
Revert "[Diagnostics] Hint contextual type diagnostics with expression type if known"

### PR DESCRIPTION
**Pull request by huonw**
Reverts apple/swift#16556

I strongly suspect this is causing failures like https://ci.swift.org/job/oss-swift-package-osx/1664/:

```
07:18:14 FAIL: Swift(macosx-x86_64) :: Constraints/diagnostics.swift (10920 of 11116)
07:18:14 
******************** TEST 'Swift(macosx-x86_64) :: Constraints/diagnostics.swift' FAILED ********************
07:18:14 Script:
07:18:14 --
07:18:14 /Users/buildnode/jenkins/workspace/oss-swift-package-osx/build/buildbot_osx/swift-macosx-x86_64/bin/swiftc -frontend -target x86_64-apple-macosx10.9  -module-cache-path '/Users/buildnode/jenkins/workspace/oss-swift-package-osx/build/buildbot_osx/swift-macosx-x86_64/swift-test-results/x86_64-apple-macosx10.9/clang-module-cache' -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -swift-version 3  -typecheck -verify -disable-objc-attr-requires-foundation-module /Users/buildnode/jenkins/workspace/oss-swift-package-osx/swift/test/Constraints/diagnostics.swift
07:18:14 --
07:18:14 Exit Code: 1
07:18:14 
07:18:14 Command Output (stderr):
07:18:14 --
07:18:14 
/Users/buildnode/jenkins/workspace/oss-swift-package-osx/swift/test/Constraints/diagnostics.swift:536:77: error: incorrect message found
07:18:14   let closureIndex = closures.index{$0 === testClosure} // expected-error {{cannot check reference equality of functions; operands here have types '_' and '([Int]) -> Bool'}}
07:18:14                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
07:18:14                                                                             cannot check reference equality of functions; operands here have types 'MyClosure' (aka '(Array<Int>) -> Bool') and '([Int]) -> Bool'
07:18:14 
07:18:14 --
```

### CODE REVIEW

**Comment by huonw** [comment]
@swift-ci please test and merge

**Comment by huonw** [comment]
cc @xedin

**Comment by xedin** [comment]
Re-applying via https://github.com/apple/swift/pull/16576

**Comment by huonw** [comment]
> It looks like that test-case must have been added after I ran all of the tests, because my full suite was green...

No, it was added in 2015/2016. It seems to only be failing occasionally, so it's possible that it either just happened to pass on all the pull request CI platforms when your patch landed, or that it wasn't caused by your patch.

**Comment by huonw** [comment]
I just looked through the CI bots, and the ones that failed are now passing (across multiple builds) that this has landed, so I'm even more inclined to say it was your patch. :( it's always annoying when it's not consistent.

**Pull request merged**
