### PR TITLE
Disable objc_nonnull_lie_hack.swift test until we work out the issues.

### PR DESCRIPTION
**Pull request by jrose-apple**
Underlying issue discussed in #4622. Filed rdar://problem/28313536 to make sure we re-enable it.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test and merge

**Comment by jrose-apple** [comment]
In the spirit of "don't just let flaky tests flake": @benlangmuir , any idea what's up with the completion test failure here? https://ci.swift.org/job/swift-PR-osx-smoke-test/1687/ 

But since this PR is itself helping with flaky tests:

@swift-ci Please smoke test OS X platform

**Comment by benlangmuir** [comment]
@jrose-apple huh, never seen that failure before. I'll take a look.

**Comment by benlangmuir** [comment]
@jrose-apple I ran that test in a loop 30,000 times without fail.  Then I tried deleting the clang module cache directory in the middle of the test.  Usually, that produced no completions at all, but occasionally it produced the same symptoms as the failure in that PR test build.  So far that's the only guess I have about what happened, and deleting the cache directory mid-build is a big no-no (deleting the individual .pcms should be okay).

**Comment by jrose-apple** [comment]
Hm. Maybe it's something similar to this test itself, where we use different API notes in different tests, and cache the result? (See #4622 for more discussion.)

**Comment by gribozavr** [comment]
@benlangmuir I think what causes the failure is a different test run order.

**Pull request merged**
