### PR TITLE
SILGen: Ignore invalid associated conformances

### PR DESCRIPTION
**Pull request by tshortli**
With lazy type checking, invalid conformances can make it all the way to SILGen. As a result, `SILGenModule::useConformance()` needs to handle invalid conformances more gracefully by ignoring them instead of asserting.

Resolves rdar://128286622

### CODE REVIEW

**Comment by tshortli** [comment]
@swift-ci please smoke test

**Comment by slavapestov** [comment]
Maybe this should assert that an error was diagnosed, and/or be conditional on lazy type checking being enabled. Otherwise it will mask bugs.

**Comment by tshortli** [comment]
I'll limit this to lazy type checking for now. In terms of asserting that there are errors, shouldn't we really be checking that when the conformance is marked invalid, rather than here?

**Comment by slavapestov** [comment]
lookupConformance() returns an invalid ProtocolConformanceRef without diagnosing if the type doesn’t conform. But if it appears here, something should have been diagnosed earlier, unless you’re in lazy type checking mode.

The invalid flag on a ProtocolConformance is something different (and we should remove it).

**Comment by slavapestov** [comment]
However if you decide to go with your current approach of squashing the assertion, please just remove it from useConformance() instead of adding this check to the caller.

**Comment by tshortli** [comment]
@swift-ci please smoke test

**Comment by tshortli** [comment]
@swift-ci please smoke test

**Pull request merged**
