### PR TITLE
Add Order File Flag

### PR DESCRIPTION
**Pull request by michaeleisel**
As discussed in https://forums.swift.org/t/order-file-generation-support-in-swiftc/37012/2, it would be great to have a simple flag to enable order file support and match clang's behavior. Order files are used with success by some of the largest apps in the world, and adding first-class support would make using them with Swift easier. According to the thread, @vedantk believes that just adding this LLVM pass should do everything that's necessary. Besides that, my one concern is as we see in clang:
```
  if (Args.hasArg(options::OPT_forder_file_instrumentation)) {
     CmdArgs.push_back("-forder-file-instrumentation");
     // Enable order file instrumentation when ThinLTO is not on. When ThinLTO is
     // on, we need to pass these flags as linker flags and that will be handled
     // outside of the compiler.
     if (!D.isUsingLTO()) {
       CmdArgs.push_back("-mllvm");
       CmdArgs.push_back("-enable-order-file-instrumentation");
     }
  }
```

I'm not sure which linker flags would enable this with LTO, but since Swift doesn't support LTO currently anyways (correct?), I guess we could cross that bridge when we get there

### CODE REVIEW

**Comment by vedantk** [comment]
@michaeleisel thanks for the patch!

Could you please:
- Add a driver test (see e.g. test/Driver/profiling.swift). This should pass -order-file-instrumentation to the driver and check that the frontend arguments it produces are correct.
- Add a runtime test (see e.g. test/Profiler/coverage_smoke.swift). This should run a program compiled with -order-file-instrumentation and validate the generated .profraw file.

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Comment by keith** [comment]
@michaeleisel we'd like to see this one too, any chance you're going to update it?

**Comment by michaeleisel** [comment]
yeah, one of these days i suppose haha. if you want to take over, feel free. also, to be clear, this shouldn't block you from using the order file stuff via the llvm flags directly. my big question is when LTO is expected to be done. when LTO is done, i'm actually less interested in this flag, since LTO would do it regardless

**Pull request closed without merging**
