### PR TITLE
Doc comment fixes

### PR DESCRIPTION
**Pull request by amartini51**
Resolves the following:

* rdar://60543202
* rdar://68225196
* rdar://76254761
* rdar://78548755
* rdar://78889410
* rdar://78890316
* rdar://78890491
* rdar://79412011
* rdar://79539036

### CODE REVIEW

**Comment by amartini51** [comment]
@swift-ci Please test.

**Review by DougGregor — APPROVED** [review]

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test macOS

**Comment by amartini51** [comment]
@swift-ci Please test and merge

**Comment by DougGregor** [comment]
@swift-ci please test

**Pull request merged**
