### PR TITLE
Refactor some AbstractFunctionDecl accessors

### PR DESCRIPTION
**Pull request by slavapestov**
Splitting up an earlier PR and testing each piece separately.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test Linux

**Comment by slavapestov** [comment]
@swift-ci Please test macOS

**Comment by slavapestov** [comment]
@swift-ci Please test Linux

**Comment by slavapestov** [comment]
@swift-ci Please test Linux

**Comment by slavapestov** [comment]
@swift-ci Please test Linux

**Comment by slavapestov** [comment]
Hi @graydon, have you seen this failure before? xcrun definitely doesn't exist on Linux. Is PR testing just broken right now?

```
17:54:56 ----------------------------------------------------------------------
17:54:56 Collected 1 test
17:54:56 
17:54:56 /bin/sh: 1: xcrun: not found
17:54:56 ======================================================================
17:54:56 ERROR: testREPL (TestREPLStructs.REPLStructsTestCase)
17:54:56 ----------------------------------------------------------------------
```

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by graydon** [comment]
@slavapestov I have found the source of the xcrun error message but it's not, as far as I can tell, the source of the LLDB breakage; it's just an incidental error printed while probing the environment.

LLDB-on-linux in general appears to be in trouble at the moment: all the CI bots on all the branches are showing different types of communication and breakpoint-setting failures. I can't reproduce _any_ of the failures locally, either on a VM or on a physical machine, so I'm a little baffled.

Meanwhile yes, everyone's ignoring that and using smoketests. I wish I had a better answer :(

**Comment by slavapestov** [comment]
@graydon Ok, I'll hold off on merging anything into master for now.

**Comment by slavapestov** [comment]
FWIW, when I run the lldb tests locally, I get a single failure:

```
======================================================================
FAIL: test_dsym (TestExec.ExecTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/slava/new/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 1695, in dsym_test_method
    return attrvalue(self)
  File "/Users/slava/new/lldb/packages/Python/lldbsuite/test/decorators.py", line 110, in wrapper
    func(*args, **kwargs)
  File "/Users/slava/new/lldb/packages/Python/lldbsuite/test/functionalities/exec/TestExec.py", line 101, in test
    "Stopped at breakpoint in exec'ed process.")
AssertionError: False is not True : Stopped at breakpoint in exec'ed process.
Config=x86_64-/Users/slava/new/build/Ninja-ReleaseAssert/llvm-macosx-x86_64/bin/clang-4.0
======================================================================
FAIL: test_dwarf (TestExec.ExecTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/slava/new/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 1705, in dwarf_test_method
    return attrvalue(self)
  File "/Users/slava/new/lldb/packages/Python/lldbsuite/test/decorators.py", line 110, in wrapper
    func(*args, **kwargs)
  File "/Users/slava/new/lldb/packages/Python/lldbsuite/test/functionalities/exec/TestExec.py", line 101, in test
    "Stopped at breakpoint in exec'ed process.")
AssertionError: False is not True : Stopped at breakpoint in exec'ed process.
Config=x86_64-/Users/slava/new/build/Ninja-ReleaseAssert/llvm-macosx-x86_64/bin/clang-4.0
======================================================================
FAIL: test_gmodules (TestExec.ExecTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/slava/new/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 1725, in gmodules_test_method
    return attrvalue(self)
  File "/Users/slava/new/lldb/packages/Python/lldbsuite/test/decorators.py", line 110, in wrapper
    func(*args, **kwargs)
  File "/Users/slava/new/lldb/packages/Python/lldbsuite/test/functionalities/exec/TestExec.py", line 101, in test
    "Stopped at breakpoint in exec'ed process.")
AssertionError: False is not True : Stopped at breakpoint in exec'ed process.
Config=x86_64-/Users/slava/new/build/Ninja-ReleaseAssert/llvm-macosx-x86_64/bin/clang-4.0
----------------------------------------------------------------------
Ran 3 tests in 4.527s
```

Not making much progress on narrowing it down, because every time I run the tests it does a full rebuild of LLDB, and I don't know how to run individual tests.

**Comment by graydon** [comment]
Never seen those failures either :(((

**Comment by kvinto555** [comment]
g

**Pull request closed without merging**
