### PR TITLE
[4.0] Update test case for s390x

### PR DESCRIPTION
**Pull request by samding01**
Update test case test/IRGen/c_functions.swift for s390x for v4.0
Thanks,

### CODE REVIEW

**Comment by gottesmm** [comment]
Just starting a drive by test. I am not reviewing this.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci text linux platform

**Comment by gottesmm** [comment]
@swift-ci test linux platform

**Comment by samding01** [comment]
@gottesmm , Can you merge it? Thanks!

**Comment by gottesmm** [comment]
@samding01 I can't merge. I think @tkremenek needs to review/merge.

**Pull request merged**
