### PR TITLE
[Distributed] Runtime: Add missing accessible function section registration on ELF

### PR DESCRIPTION
**Pull request by xedin**
Resolves: rdar://87240034

### CODE REVIEW

**Review by ktoso — COMMENTED** [review]
WAT? That's the fix? Dear god.

**Review by ktoso — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Review by compnerd — COMMENTED** [review]
Did you make the appropriate change to the Windows path? (COFF)

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Comment by xedin** [comment]
@compnerd Windows is XFail’ed for now due to other issues so ww cannot really test it yet, once that is dealt with I will verify that everything is properly registered.

**Comment by xedin** [comment]
Actually, I am just going to open a PR add that on Windows as well, accessible functions aren’t in Swift-COFF.cpp

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Pull request merged**
