### PR TITLE
[cxx-interop] Move included stdlib headers from libstdcxx.h to the modulemap

### PR DESCRIPTION
**Pull request by egorzhdan**
By referencing the C++ stdlib header directly from the modulemap, we make sure that the header is treated as a part of the stdlib, not a part of the first clang module to include it.

Addresses the issue described in https://forums.swift.org/t/llvm-fails-to-build-with-modules/59700/8.

### CODE REVIEW

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by hyp** [comment]
This looks incorrect - Why do you want to do this only for those two headers? Shouldn't you libstdcxx.h be an umbrella header instead?

**Comment by hyp** [comment]
You can also try making libstdcxx.h an umbrella header, since VFS places it into the libstdcxx directory.

**Comment by egorzhdan** [comment]
Yeap, you're right, we should try to refer to the stdlib headers in a consistent way. I moved these two headers only for now to make sure this doesn't cause too much fallout – moving all headers into the modulemap at once could produce a lot of compiler errors which would be hard to investigate.

I tried making `libstdcxx.h` an umbrella header in the past, the problem is that it causes clang to treat libstdc++ headers as different submodules, and that causes "duplicate definition" errors for types like `size_t` which are defined in multiple headers (behind something like `#if SIZE_T_DEFINED`).

**Comment by egorzhdan** [comment]
A change like this could cause new modularization errors if, for example, there is a C++ stdlib header that is not directly referenced from the modulemap, but is `#include`-d from a user project. This happened when I tried moving `tuple` only (without `functional`) to the modulemap in this PR.

> at this point you're just playing whack a mole with the errors reported on the forums (there could be more), so wouldn't it make sense to address this correctly?

I agree, I'm going to move more headers to the modulemap before merging this.

I wonder if it's possible to move the optional headers (those under `#if __has_include`) to the modulemap without having to generate the modulemap in the compiler. I guess it isn't, unless we inject empty headers into libstdc++ via VFS.

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
I will move the rest of the headers (those that are under `#if __has_include`) to the modulemap in a separate PR.

**Pull request merged**
