### PR TITLE
DO NOT MERGE: See what benchmarks care about _fromCodeUnits

### PR DESCRIPTION
**Pull request by milseman**

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please smoke benchmark

**Comment by milseman** [comment]
@swift-ci please smoke benchmark

**Comment by milseman** [comment]
@swift-ci please smoke benchmark

**Comment by milseman** [comment]
@swift-ci please smoke benchmark

**Comment by milseman** [comment]
Oops, @shahmishal or @jrose-apple can you kill https://ci.swift.org/job/swift-PR-osx-smoke-perf/178/ ?

I should do this locally instead...

**Comment by jrose-apple** [comment]
Killed. How did you manage *that?*

**Comment by milseman** [comment]
I was trying to see what benchmarks care about the performance of `_fromCodeUnits` by inserting a 1-millisecond sleep...

**Pull request closed without merging**
