### PR TITLE
Document which registers are used for the async context on x86-64/ARM64.

### PR DESCRIPTION
**Pull request by grynspan**
This change updates the calling convention documentation to document which registers are used for the async context on x86-64/ARM64.

### CODE REVIEW

**Comment by grynspan** [comment]
@swift-ci please smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test macos

**Review by al45tair — APPROVED** [review]
LGTM (and you've saved me a [very small] job; I was going to make that change when I had a spare moment).

**Comment by al45tair** [comment]
@swift-ci Please smoke test macOS platform

**Comment by grynspan** [comment]
Welp, my reply to @al45tair ended up as the commit message… yay.

**Pull request merged**
