### PR TITLE
Revert "CMake: generate SupportedFeatures.json while building and install it into toolchain"

### PR DESCRIPTION
**Pull request by edymtt**
Reverts apple/swift#34655

Addresses rdar://71282911

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci please build toolchain

**Comment by edymtt** [comment]
@swift-ci please smoke test

**Comment by edymtt** [comment]
Root cause is addressed in #34686, keeping this around in case I misunderstood the fix

**Comment by nkcsgexi** [comment]
Thank you for reverting this!

**Pull request merged**
