### PR TITLE
[concurrency] a fix for actor lifetimes

### PR DESCRIPTION
**Pull request by kavon**
By @phausler. One of the tests here subsumes #36248

Fixes rdar://74281361

### CODE REVIEW

**Comment by kavon** [comment]
@swift-ci please smoke test

**Review by phausler — APPROVED** [review]
looks great to me

**Review by ktoso — APPROVED** [review]
Looks good, thanks a ton @phausler @kavon 👍

**Comment by ktoso** [comment]
Unrelated failure:

```
11:00:24 Test Case '-[CommandsTests.RunToolTests testUsage]' started.
11:00:24 
/Users/buildnode/jenkins/workspace/swift-PR-macos-smoke-test/branch-main/swiftpm/Tests/CommandsTests/RunToolTests.swift:27: error: -[CommandsTests.RunToolTests testUsage] : XCTAssertTrue failed - got stdout:
11:00:24 OVERVIEW: Build and run an executable product
11:00:24 
```

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Review by jckarter — APPROVED** [review]

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by kavon** [comment]
@swift-ci please smoke test and merge

**Comment by kavon** [comment]
@swift-ci please smoke test and merge

**Comment by kavon** [comment]
ok that Linux failure was just some cosmic rays or something:

```
09:06:31 Process leaked file descriptors. See https://jenkins.io/redirect/troubleshooting/process-leaked-file-descriptors for more information
09:07:25 Build step 'Execute shell' marked build as failure
09:09:18 FATAL: java.io.IOException: Unexpected termination of the channel
09:09:18 
java.io.EOFException
09:09:18 	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2759)
```

**Comment by DougGregor** [comment]
@swift-ci please smoke test Linux

**Comment by DougGregor** [comment]
@swift-ci please clean smoke test Linux

**Comment by atrick** [comment]
hmm, the 4pm build still hit
 `LLDBWrapPython.cpp:80128:1: error: 'LLDBSwigPythonBreakpointCallbackFunction' has C-linkage`

**Comment by atrick** [comment]
@swift-ci smoke test linux

**Comment by DougGregor** [comment]
@swift-ci smoke test linux

**Comment by DougGregor** [comment]
@swift-ci please clean test Linux

**Pull request merged**
