### PR TITLE
[Constraint solver] Reduce timer overhead associated with "expression too complex"

### PR DESCRIPTION
**Pull request by DougGregor**
This pull request reduces the overhead associated with polling timers to determine whether a given expression is "too complex" to be solved in a reasonable amount of time. Before this pull request, the timing overhead for type-checking the standard library is ~5.7%; afterward, it's a more-acceptable ~1.7%. There were two changes:

* Remove debugging-only API that allowed us to see how long a specific solver state was alive; if we need it, we can bring it back behind a debugging flag.
* Limit the places where we poll the timer. Now we check at decision points (before we try type variable bindings or visit a disjunction) and at the end (to make sure we fail consistently when the expression is "too complex")

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please smoke test compiler performance

**Review by rudkx — APPROVED** [review]
LGTM.

After simplifying the "too complex" decision recently, my hope was to eliminate the timer, but currently it's the only thing that ensures we consider the time spent in "shrink", and my experiment to remove that recently failed, so I left the timer in.

Independent of all that I was planning on converting all of these release-no-asserts-build-only tests into testing the scope counter instead (through a new command-line option). Then once we're confident we don't need the timer to at all, we can rip it out.

**Comment by DougGregor** [comment]
Okay, thanks @rudkx

**Comment by DougGregor** [comment]
Not sure what happened with those iphonesimulator tests:

```
18:08:15 lit.py: /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/llvm/utils/lit/lit/TestingConfig.py:101: fatal: unable to parse config file '/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/test/lit.cfg', traceback: Traceback (most recent call last):
18:08:15   File "/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/llvm/utils/lit/lit/TestingConfig.py", line 88, in load_from_path
18:08:15     exec(compile(data, path, 'exec'), cfg_globals, None)
18:08:15   File "/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/test/lit.cfg", line 641, in <module>
18:08:15     config.available_features('DARWIN_SIMULATOR=ios')
18:08:15 TypeError: 'set' object is not callable
18:08:15 
18:08:15 *** Failed while running tests for swift (check-swift-validation-iphonesimulator-i386)
```

**Comment by DougGregor** [comment]
@swift-ci please smoke test macOS

**Pull request merged**
