### PR TITLE
[5.0] [String] UTF8View.withContiguousStorageIfAvailable

### PR DESCRIPTION
**Pull request by milseman**
5.0 cherry-pick of https://github.com/apple/swift/pull/21178

<rdar://problem/34598630>

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please test

**Review by airspeedswift — APPROVED** [review]
Looks good but are you going to add tests too?

**Comment by milseman** [comment]
Definitely, I'm working on that now. I don't know cutoffs, feel free to await those

**Comment by milseman** [comment]
@airspeedswift pushed the tests to this branch too

**Comment by milseman** [comment]
@swift-ci please test

**Pull request merged**
