### PR TITLE
[5.1 early] [ModuleInterface] Emit remarks when rebuilding from an interface

### PR DESCRIPTION
**Pull request by harlanhaskins**
Cherry-picked from #24424 (reviewed by @jrose-apple)
rdar://47792754

### CODE REVIEW

**Comment by harlanhaskins** [comment]
@swift-ci please test

**Comment by harlanhaskins** [comment]
@swift-ci please test

**Review by AnnaZaks — APPROVED** [review]

**Comment by harlanhaskins** [comment]
```
clang-7: error: unable to make temporary file: No such file or directory
```

@swift-ci please test Linux

**Comment by harlanhaskins** [comment]
@swift-ci please test Linux

**Pull request closed without merging**
