### PR TITLE
Revert https://github.com/apple/swift/pull/40269

### PR DESCRIPTION
**Pull request by hborla**
https://github.com/apple/swift/pull/40269 is a source breaking change, as noted [here](https://github.com/apple/swift/pull/40269#issuecomment-1028262631):

```swift
protocol P { associatedtype A = Int }
protocol Q { associatedtype B }
protocol R: P, Q where A == B {}

struct S: R {}
```

This code compiles today, but breaks with the associated type inference refactoring. Unfortunately, there's real-world code relying on the old behavior.

Resolves: rdar://90402522

### CODE REVIEW

**Comment by hborla** [comment]
@AnthonyLatsis do you think it'd be relatively straightforward to put the new behavior behind a flag? I'm not too familiar with your change, but with your help, I'll happily attempt to put it behind a flag instead of the revert.

**Comment by AnthonyLatsis** [comment]
Bummer! Let us see... We would need to revert [this](https://github.com/apple/swift/pull/40269/commits/98567e87a3388746c7da67da1cca84e3270abf0d) to resurrect the old code and conditionalise the inference method in `AssociatedTypeInference::inferAbstractTypeWitnesses` with respect to [these](https://github.com/apple/swift/pull/40269/commits/a40aa11f3d66e03cdf534d11e865247e1c48dc81) changes (disregard all the `const` additions). Sounds relatively straightforward from what I see. The backup plan would be to trade duplication for easiness and define a second `inferAbstractTypeWitnesses`. Everything else should be good to keep.

**Comment by AnthonyLatsis** [comment]
@hborla In case you haven't started working on the flag yet — just want to be honest and let you know that I don't feel right about having you fix a problem that I'm responsible for, and I'd gladly handle it myself. I hope you don't get the wrong idea, it's totally fine if you're interested in seeing this through personally.

**Comment by hborla** [comment]
@AnthonyLatsis I have not started working on the flag yet! I was working on a couple other PRs that I wanted to get up before doing that, but if you'd like to add the flag instead, please go for it 🙂

**Comment by hborla** [comment]
@AnthonyLatsis Thank you! Closing this in favor of your PR 🙏🏻

**Pull request closed without merging**
