### PR TITLE
Emit bind optional fixes

### PR DESCRIPTION
**Pull request by gottesmm**
This fixes the remaining issues with bind optional by changing select_enum usage to switch_enum.

rdar://34222540

### CODE REVIEW

**Comment by gottesmm** [comment]
(doing a quick rebase)

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
... I guess I need to update the linux one separately. = /.

**Comment by gottesmm** [comment]
Lets try this one last time.

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
... introduced a merge conflict on my own branch *sigh*.

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by davezarzycki** [comment]
Hi @gottesmm – Commit `dde4f58625d2bee728667654c5a5b5ac5a826b17` broke a test on my Linux box. You can find the test output here:

http://znu.io/opaque_values_silgen.swift.out

And the output from `lit` here:

```
/home/dave/s/u/tools/swift/test/SILGen/opaque_values_silgen.swift:822:11: error: expected string not found in input
// CHECK: [[SENUM:%.*]] = select_enum [[COPY__ARG]]
          ^
<stdin>:1440:21: note: scanning from here
 %5 = copy_value %4 : $Optional<@callee_guaranteed () -> @out T> // users: %6, %8, %13
                    ^
<stdin>:1440:21: note: with variable "COPY__ARG" equal to "%5"
 %5 = copy_value %4 : $Optional<@callee_guaranteed () -> @out T> // users: %6, %8, %13
                    ^
<stdin>:1456:2: note: possible intended match here
 %13 = unchecked_enum_data %5 : $Optional<@callee_guaranteed () -> @out T>, #Optional.some!enumelt.1 // users: %14, %16, %18
 ^
```

**Comment by gottesmm** [comment]
I wonder why it didn't trigger on the bots.

**Comment by davezarzycki** [comment]
I'm not running the same distribution of Linux (Fedora versus Ubuntu), which could cause tiny differences.

**Comment by gottesmm** [comment]
@davezarzycki Can you provide more information about the OS you are using.  I want to try and reproduce. What version of Fedora are you using, versions of tools/etc.

**Comment by davezarzycki** [comment]
Just a bit. Let me eliminate some variables first. If you really want to go down this route, you can start by installing Fedora 27: https://getfedora.org/en/workstation/download/

Then `sudo dnf update` to install updates, and `sudo dnf install clang lldb lld libcxx libcxx-devel cmake ninja-build libuuid libuuid-devel libicu libicu-devel` to get ensure that various LLVM goodies and dependencies are installed. You can use `dnf search' to find packages that you need that aren't installed.

**Comment by davezarzycki** [comment]
Ugh. My first few guesses were wrong. I think this is one of those rare `build-script` versus unified build bugs. Please hold off while I dig further.

**Comment by davezarzycki** [comment]
Okay, apparently the `opaque_values_silgen.swift` test assumes `-DSWIFT_STDLIB_ENABLE_RESILIENCE=TRUE`. Is `-DSWIFT_STDLIB_ENABLE_RESILIENCE=FALSE` no longer supported?

**Comment by davezarzycki** [comment]
In either case, sorry for the noise @gottesmm!

**Comment by gottesmm** [comment]
@davezarzycki No worries! = )

**Pull request merged**
