### PR TITLE
Revert "Revert "Isolated synchronous deinit""

### PR DESCRIPTION
**Pull request by ktoso**
Remove task-local tests from isolated deinit, as we don't guarantee behavior of them

This was changing back and forth during review but proposal now states that

> This proposal does not define how Swift runtime should behave when
> running isolated deinit. It may use task-local values as seen at the
> point of the last release, reset them to default values, or use some
> other set of values. Behavior is allowed to change without notice. But
> future proposals may change specification by defining a specific
> behavior.

and indeed we observed different behaviors failing the test. It seems we may want to drop that test entirely tbh.

### CODE REVIEW

**Comment by benrimmington** [comment]
The proposal hasn't been updated yet, but it was [accepted with modifications](https://forums.swift.org/t/accepted-with-modifications-se-0371-isolated-synchronous-deinit/74042):

> Lastly, on the topic of task locals, the LSG agreed with reviewers who expressed that the approach of 'make no promises' was likely to result in users inadvertently relying on implementation details which would turn out to be difficult to change later, and so decided to adopt the consistent rule that task locals will *always* be cleared when entering an `isolated deinit`.

**Comment by ktoso** [comment]
Heh, my bad for assuming the proposal is up to date. Thanks for the reminder

**Comment by benrimmington** [comment]
I've created swiftlang/swift-evolution#2558 to update the proposal.

**Comment by ktoso** [comment]
Thanks, LGTM on that update.

**Comment by ktoso** [comment]
Still trying to figure out how the failures here could have ever happened... they're not possible to reproduce reliably heh.

**Comment by ktoso** [comment]
A crash we saw is

```
Command Output (stdout):
--
[ RUN      ] Isolated Deinit.class sync fast path
[       OK ] Isolated Deinit.class sync fast path
[ RUN      ] Isolated Deinit.class sync slow path
stdout>>> check failed at /Users/ec2-user/jenkins/workspace/oss-swift_tools-RA_stdlib-RD_test-simulator/swift/test/Concurrency/Runtime/async_task_locals_isolated_deinit.swift, line 121
stdout>>> first:  105553152229376 (of type Swift.Int)
stdout>>> second: 0 (of type Swift.Int)
stderr>>> CRASHED: SIGILL
the test crashed unexpectedly
[     FAIL ] Isolated Deinit.class sync slow path
[ RUN      ] Isolated Deinit.actor sync fast path
[       OK ] Isolated Deinit.actor sync fast path
[ RUN      ] Isolated Deinit.actor sync slow path
[       OK ] Isolated Deinit.actor sync slow path
[ RUN      ] Isolated Deinit.no TLs
[       OK ] Isolated Deinit.no TLs
Isolated Deinit: Some tests failed, aborting
UXPASS: []
FAIL: ["class sync slow path"]
SKIP: []
To debug, run:
$ /Users/ec2-user/jenkins/workspace/oss-swift_tools-RA_stdlib-RD_test-simulator/build/Ninja-ReleaseAssert/swift-macosx-x86_64/test-macosx-x86_64/Concurrency/Runtime/Output/async_task_locals_isolated_deinit.swift.tmp/a.out --stdlib-unittest-in-process --stdlib-unittest-filter "class sync slow path"
```

showing a corrupted value on self -- the task local value is properly 0 as expected though...

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please smoke test macOS

**Comment by ktoso** [comment]
@swift-ci please smoke test macOS

**Comment by ktoso** [comment]
@swift-ci please  test macOS

**Comment by ktoso** [comment]
@swift-ci please test macOS

**Pull request merged**
