### PR TITLE
Created HyperLink to sphinx-doc for easy acess

### PR DESCRIPTION
**Pull request by codestergit**

### CODE REVIEW

**Comment by jrose-apple** [comment]
Good idea, but then we might as well drop the URL from the following parentheses. What do you think?

**Comment by codestergit** [comment]
@jrose-apple  that would be good as in ReadMe.md other tools(like cmake ninja) also shown as hyperlink so it will make it consistent. I am doing that change. Is it fine?

**Comment by codestergit** [comment]
@jrose-apple  Updated the commit. Please let me know if any thing else needed. Thanks.

**Comment by jrose-apple** [comment]
Thanks! One last nitpick: we try to stick to an 80-column limit (a convention we inherited from LLVM). Can you reflow the paragraph so that it fits?

**Comment by codestergit** [comment]
@jrose-apple Done the changes. Thanks!

**Pull request merged**
