### PR TITLE
Demonstration of SILGen crash

### PR DESCRIPTION
**Pull request by dabrahams**
Fixes for `swift-hide-bodies` in emacs mode

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please smoke test and merge

**Comment by atrick** [comment]
@dabrahams I don't think pattern matching is supposed to be in this PR.

**Comment by dabrahams** [comment]
on Mon Nov 21 2016, Andrew Trick <notifications-AT-github.com> wrote:

> @dabrahams I don't think pattern matching is supposed to be in this PR.

No, it's not, but there's a radar open against the test failures it
generated so we're leaving it alone.

-- 
-Dave

**Comment by jckarter** [comment]
The crash here appears to be a failure of archetype exemplarization to lower the return type `Optional<SubSequence>` of `Collection.subscript_` to the same LLVM type from its interface type and its contextual archetypes. It's possible that the generic environment builder has a bug, since the structure of the archetypes is different. In one case, the nested `SubSequence.Index` shows up as `T.SubSequence.Index`:

```
(archetype_type name=τ_0_0.SubSequence.Index address=0x1103cf288 conforms_to=Swift.(file).Comparable parent=0x1103cf1c8 assoc_type=Swift.(file)._IndexableBase.Index
)
```

whereas in the other case, it shows up as `T.Index`:

```
(archetype_type name=τ_0_0.Index address=0x10fdaef90 conforms_to=Swift.(file).Comparable parent=0x10fdaeed0 assoc_type=Swift.(file)._IndexableBase.Index
)
```

possibly because one side or other of a same-type constraint is winning nondeterministically. Sound likely, @DougGregor or @slavapestov ?

**Comment by slavapestov** [comment]
Sounds likely. It looks like @DougGregor is ripping out IRGen's exemplarization while working on recursive constraints, so maybe a fix will fall out naturally here.

**Comment by DougGregor** [comment]
OH! I may have a fix... found a place where which representative gets picked would affect the protocol conformances seen while refactoring yesterday. That could be it.

**Comment by DougGregor** [comment]
I believe that 

  https://github.com/apple/swift/pull/5995

fixes the issue. It kills some nondeterminism which could have manifest this way, and I can no longer reproduce the issue with that PR applied locally.

**Comment by DougGregor** [comment]
Or perhaps not... it's blowing up in the Devirtualizer when built with optimization.

**Comment by dabrahams** [comment]
The bug has been fixed so closing.

**Pull request closed without merging**
