### PR TITLE
[Runtime] Ptrauth for runAsyncAndBlock.

### PR DESCRIPTION
**Pull request by nate-chandler**
rdar://72357371

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test macos platform

**Comment by nate-chandler** [comment]
@swift-ci please test linux platform

**Pull request merged**
