### PR TITLE
Disable TSan support under 32bit.

### PR DESCRIPTION
**Pull request by cheshire**
Refactor slightly the relevant LIT code.

### CODE REVIEW

**Comment by cheshire** [comment]
@swift-ci please test and merge

**Comment by cheshire** [comment]
@swift-ci please test and merge
@shahmishal could you take a look at a failure message on Linux? Looks infrastructure-specific

**Comment by shahmishal** [comment]
libdispatch test failed due to undefined symbol. 
```
/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/buildbot_linux/libdispatch-linux-x86_64/tests/.libs/lt-bsdtestharness: symbol lookup error: /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/buildbot_linux/libdispatch-linux-x86_64/src/.libs/libdispatch.so: undefined symbol: _T0s19_emptyStringStorages6UInt32Vvp
FAIL dispatch_timer_bit63 (exit status: 127)
```

**Comment by shahmishal** [comment]
@swift-ci clean test

**Comment by shahmishal** [comment]
macOS failed due to: 

```
fatal: unable to parse config file '/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/test/lit.cfg', traceback: Traceback (most recent call last):
  File "/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/llvm/utils/lit/lit/TestingConfig.py", line 88, in load_from_path
    exec(compile(data, path, 'exec'), cfg_globals, None)
  File "/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/test/lit.cfg", line 927, in <module>
    config.available_features.remove('tsan_runtime')
KeyError: 'tsan_runtime'

*** Failed while running tests for swift (check-swift-validation-iphonesimulator-i386)
```

**Comment by cheshire** [comment]
@swift-ci please test and merge

**Comment by cheshire** [comment]
@swift-ci please test and merge

**Comment by cheshire** [comment]
@shahmishal now seems stuck at "waiting for status to be reported"

**Comment by shahmishal** [comment]
Its running. 
screen shot 2017-09-14 at 1 40 10 pm

**Comment by cheshire** [comment]
@swift-ci please test and merge

**Comment by cheshire** [comment]
@swift-ci please test and merge

**Comment by cheshire** [comment]
@swift-ci please test

**Comment by cheshire** [comment]
@swift-ci please test

**Comment by cheshire** [comment]
@swift-ci please test

**Pull request merged**
