### PR TITLE
[LLDB] Use CMake build instead of xcodebuild for LLDB

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci smoke test

**Comment by shahmishal** [comment]
After smoke test passes, I will try full test to make sure we don't cause any issues with PR testing.

**Review by fredriss — APPROVED** [review]

**Comment by shahmishal** [comment]
```
xcodebuild -target desktop -configuration CustomSwift-Release LLDB_PATH_TO_LLVM_SOURCE=/Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/llvm LLDB_PATH_TO_CLANG_SOURCE=/Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/llvm/tools/clang LLDB_PATH_TO_SWIFT_SOURCE=/Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/swift LLDB_PATH_TO_LLVM_BUILD=/Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/buildbot_incremental/llvm-macosx-x86_64 LLDB_PATH_TO_CLANG_BUILD=/Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/buildbot_incremental/llvm-macosx-x86_64 LLDB_PATH_TO_SWIFT_BUILD=/Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/buildbot_incremental/swift-macosx-x86_64 LLDB_IS_BUILDBOT_BUILD=1 'LLDB_BUILD_DATE="2019-04-05"' SYMROOT=/Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/buildbot_incremental/lldb-macosx-x86_64 OBJROOT=/Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/buildbot_incremental/lldb-macosx-x86_64 -UseNewBuildSystem=NO MACOSX_DEPLOYMENT_TARGET=10.13 DEBUGSERVER_DISABLE_CODESIGN=1 DEBUGSERVER_DELETE_AFTER_BUILD=1 DEBUGSERVER_USE_FROM_SYSTEM=1
```
try again

**Comment by shahmishal** [comment]
@swift-ci smoke test macOS

**Comment by shahmishal** [comment]
```
13:34:40 -- Linker detection: ld64
13:34:40 CMake Error at /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/buildbot_incremental/llvm-macosx-x86_64/lib/cmake/llvm/LLVM-Config.cmake:175 (message):
13:34:40   Target ARM is not in the set of libraries.
13:34:40 Call Stack (most recent call first):
13:34:40   /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/buildbot_incremental/llvm-macosx-x86_64/lib/cmake/llvm/AddLLVM.cmake:548 (llvm_map_components_to_libnames)
13:34:40   cmake/modules/AddLLDB.cmake:55 (llvm_add_library)
13:34:40   source/Plugins/Disassembler/llvm/CMakeLists.txt:1 (add_lldb_library)
13:34:40 
13:34:40 
13:34:40 -- Configuring incomplete, errors occurred!

```
/cc @dcci

**Comment by shahmishal** [comment]
@swift-ci clean smoke test macOS

**Review by dcci — APPROVED** [review]
LGTM

**Comment by shahmishal** [comment]
Closed due to https://github.com/apple/swift/pull/23908

**Pull request closed without merging**
