### PR TITLE
Use the new mangling for reflection.

### PR DESCRIPTION
**Pull request by eeckstein**
For this we are linking the new re-mangler instead of the old one into the swift runtime library.
Also we are linking the new de-mangling into the swift runtime library.

It also switches to the new mangling for class names of generic swift classes in the metadata.
Note that for non-generic class we still have to use the old mangling, because the ObjC runtime in the OS depends on it (it de-mangles the class names).
But names of generic classes are not handled by the ObjC runtime anyway, so there should be no problem to change the mangling for those.
The reason for this change is that it avoids linking the old re-mangler into the runtime library.

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci Please test

**Comment by eeckstein** [comment]
@swift-ci Please test linux

**Comment by eeckstein** [comment]
@swift-ci Please clean test

**Comment by eeckstein** [comment]
@swift-ci Please clean test

**Comment by slavapestov** [comment]
Thanks!

**Comment by eeckstein** [comment]
@swift-ci Please test

**Pull request merged**
