### PR TITLE
Exclude properties of class with type Self

### PR DESCRIPTION
**Pull request by johnno1962**
Hi Apple,

as a followup to https://github.com/apple/swift/pull/22863, prevent people from declaring properties of type `Self` which seems to not work particularly well as mentioned in the Jira below and the [previous PR](https://github.com/apple/swift/pull/22863#issuecomment-475434671). This isn't really a solution but prevents compiler crashes and erratic diagnostics. cc @slavapestov. It now gives the error below when a user tries to declare a property with type `Self` in a class:
```
h.swift:155:15: error: 'Self' is only available in a protocol or as the result of a method in a class; did you mean 'A1'?
  var copied: Self {
              ^~~~
              A1
```
Resolves #52537.

### CODE REVIEW

**Comment by xwu** [comment]
Is there a reason to exclude this for concrete value types?

**Comment by johnno1962** [comment]
Value types work so I've pushed another commit. @xwu, are you able to run tests for me please?

**Comment by johnno1962** [comment]
I've re-synced to apple/master and got texts working now so this change should be good to go.

**Comment by xwu** [comment]
@swift-ci Please test

**Comment by johnno1962** [comment]
👍, thanks @xwu, LGTM.

**Comment by johnno1962** [comment]
@swift-ci Please test

**Comment by johnno1962** [comment]
@xwu, when you have a spare moment could you @swift-ci Please test again for me?

**Comment by xwu** [comment]
@swift-ci Please test

**Comment by johnno1962** [comment]
Thanks @xwu, over to you @slavapestov

**Review by slavapestov — APPROVED** [review]
If you want, you can try to lift the restriction on get-only properties returning Self in a subsequent PR. It shouldn't be difficult!

**Comment by johnno1962** [comment]
Thanks @slavapestov, another time perhaps. Would you be able to cherry pick it to 5.1 for me please. I've exhausted my git skills wit the fork I have which doesn't have a swift-5.1-branch.

**Comment by slavapestov** [comment]
Sure.

**Comment by slavapestov** [comment]
Here you go: https://github.com/apple/swift/pull/23613

**Comment by johnno1962** [comment]
ta!

**Pull request merged**
