### PR TITLE
typo and grammer fixes

### PR DESCRIPTION
**Pull request by vicky002**
I have closed my previous [PR](https://github.com/apple/swift/pull/336).  and quashed all commits into one as discussed.

@jrose-apple Sir please review it once.

Thanks!

### CODE REVIEW

**Comment by jrose-apple** [comment]
Looks good. Thanks!

**Comment by jrose-apple** [comment]
Oops, @gottesmm is right. Thanks, Michael.

**Comment by vicky002** [comment]
ohh @gottesmm Thanks.  I'll change it.

**Comment by jrose-apple** [comment]
That'd be nice, yes. Note that if you force push to the same branch the pull request should be updated. (This is one reason why a lot of people use dedicated branches for pull requests.)

**Pull request closed without merging**
