### PR TITLE
 Remove InoutAliasingAssumption, improving EscapeAnalysis.

### PR DESCRIPTION
**Pull request by atrick**
Simplifies isNotAliasingArgument and pointsToLocalObject APIs.
    
Rename to isExclusiveArgument to avoid double-negative bugs.
    
The motivation is to simplify the APIs, but a side effect is that
EscapeAnlysis will no longer consider @inout arguments to be aliasing
with other indirect arguments or globals. This is valid since
exclusivity has been fully enforced for at least a major release cycle.

(Only the third commit is specific to this PR; I'm still waiting on review for the previous PRs.)

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci test source compatibility

**Comment by atrick** [comment]
@swift-ci benchmark

**Comment by atrick** [comment]
@swift-ci test OSX platform

**Comment by atrick** [comment]
@swift-ci test OS X Platform

**Review by eeckstein — APPROVED** [review]
lgtm

**Comment by atrick** [comment]
These changes have been committed in separate PR.

**Pull request closed without merging**
