### PR TITLE
[libSyntax] Incremental syntax tree transfer

### PR DESCRIPTION
**Pull request by ahoppen**
This PR adds the ability to incrementally transfer a libSyntax tree from the C++ side to the Swift side of swiftSyntax. 

The basic idea behind it is that we assign a unique ID to each node. If the node has been pulled from the SyntaxParsingCache during incremental syntax parsing, we know that the client already has that node. So, instead of serialising it again, we just add a stub node to the transferred tree that consists of only the node's ID. The client can then substitute the stub node with the node of that ID which is already present in its old syntax tree.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@nkcsgexi I implemented the changes you requested in the comments and have refactored the swiftSyntax entry point API so that we no longer need to pass the `IncrementalParsingSession` around.

**Review by nkcsgexi — APPROVED** [review]
Thanks! I've no other comments.

**Comment by rintaro** [comment]
> So, instead of serialising it again, we just add a stub node to the transferred tree that consists of only the node's ID.

I couldn't find JSON output test cases for `"omitted": true` node. Could you add some? Or am I missing something?

**Comment by ahoppen** [comment]
@rintaro It's implicitly tested when we do the round trip through swiftSyntax. But good point. I'll add a test case.

**Comment by ahoppen** [comment]
@rintaro I've added a test case that checks the JSON syntax tree with omitted nodes.

@swift-ci Please smoke test

**Comment by ahoppen** [comment]
Test failure seems unrelated.

@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please Python lint

**Review by rintaro — APPROVED** [review]
Thanks!

**Pull request merged**
