### PR TITLE
Generalize sanitizer tests.

### PR DESCRIPTION
**Pull request by cheshire**
- Remove redundant XFAIL/REQUIRE, *_runtime variable should be
sufficient to specify whether the test can be run.
 - Provide required machinery to pass environment variables
to different operating systems in a generalized way
(e.g. iOS Simulator only passes environment variables starting with a
certain prefix).

### CODE REVIEW

**Comment by cheshire** [comment]
@swift-ci please smoke test

**Comment by AnnaZaks** [comment]
LGTM

**Comment by cheshire** [comment]
@swift-ci please smoke test Linux platform

**Comment by cheshire** [comment]
Please smoke test OS X platform

**Comment by cheshire** [comment]
@swift-ci please smoke test Linux platform

**Comment by cheshire** [comment]
@swift-ci please smoke test OS X platform

**Comment by rintaro** [comment]
I think you should run full test (`please test`) on OS X. Smoke test doesn't run tests for simulators.

**Comment by cheshire** [comment]
@rintaro currently in the open-source swift none of the sanitizers are being compiled for the simulators, thus the tests would be disabled.

**Pull request merged**
