### PR TITLE
[stdlib] Improvements to `Random` and some doc fixes

### PR DESCRIPTION
**Pull request by Azoy**
- Some docs fixes for `Bool` and `RandomNumberGenerator`
cc: @natecook1000 

- Adds `@inlinable` and `@_fixed_layout` to some places in `Random`
cc: @lorentey 

- Removes a warning in `[Closed]Range.randomElement(using:)`

Also, should I add `@inlinable` to the `_fill(bytes:)` methods and `FixedWidthInteger._random()` methods?
@milseman pointed out that we could probably fast path the `FixedWidthInteger._random()` method, is this something we could also tackle in this PR as well?

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci please test

**Comment by lorentey** [comment]
@swift-ci please benchmark

**Review by lorentey — APPROVED** [review]
Looks good!

**Comment by lorentey** [comment]
I think we can make `Random._fill(bytes:)` and `Random.next()` both inlinable (possibly eliminating the need for the `@effects` attribute on the latter). The same goes for `Int._random(using:)` and all the other integer variants. These should give us a nice performance boost.

I'm less certain about `FixedWithInteger._random(using:)`. Its implementation is rather rudimentary and we probably want to optimize it later (pending new initializer APIs). It's also not particularly performance sensitive -- none of the standard fixed width integers use it. 

Do you mean to fast path the `bitWidth <= UInt64.bitWidth` condition? Sure, if it helps -- but I expect that condition will be optimized away anyway as long as the body is specialized. (And if it isn't, then _fastPath won't help much.)

**Comment by Azoy** [comment]
I don't know if you've seen yet, but Jens reported that simple operations like `Double.random(in: 0 ..< 1, using: &rng)` are roughly 45x slower than an implementation [he implemented](https://forums.swift.org/t/generating-double-values-in-unit-range-using-random-api-is-about-45-times-slower-than-necessary/12992). I concluded that the stdlib integer types all use their custom implementation of `FixedWidthInteger._random(using:)` where it calls that generator's `_fill(bytes:)`. This is really unnecessary for the stdlib types because they can use the `bitWidth <= UInt64.bitWidth` branch without having to fill a buffer through `_fill(bytes:)`.

My solution to fixing this slowdown would require moving `next<T>() -> T` as a protocol requirement (which I can add to the `fill(bytes:)` proposal hopefully). From there, we can add another internal requirement to `FixedWidthInteger` called `_random()` which is simply `return T._random(using: &Random.default)`. After doing this, we can remove the stdlib integer implementation of `T._random(using:)` in favor of simply `T._random()` which would have the same implementation of the current `T._random(using:)`. `Random.default` would define it's implementation of `next<T>() -> T` simply as `return T._random()`.

This solution allows the stdlib integer types to be initialized via `_stdlib_random` from `Random.default`, while being able to take `bitWidth <= UInt64.bitWidth` for other generators. Does this sound correct to hopefully gain a lot of performance back when using generators? Would simply inlining `_fill(bytes:)` suffice?

I need to writeup a proposal soon and hopefully I can submit an implementation so you have a visual of what I'm talking about, and we can perform some benchmarks.

**Comment by lorentey** [comment]
I think it's important to guarantee that `random()` and `random(using: Random.default)` have the same behavior; the two spellings should have the exact same performance.

What if we just changed the `_random(using:)` implementations for the standard integer types to call `Self(truncatingIfNeeded: rng.next() as UInt64)`? (It may also be possible to replace the `_random(using:)` requirement with a simple extension method using the same implementation for all types. However, we have to be careful to ensure we have acceptable performance in unspecialized generic contexts, where the rng is not known at compile time.)

It would probably make sense to expose a direct runtime operation for producing 64-bit random values. If we intend to keep using `RNG.next()` as the primitive API, then we should have a direct match for it in the runtime, too. (I haven't measured it, but I think `arc4random_buf` may be a little bit slower than two calls to `arc4random`.)

Note that the default `_fill` implementation is not yet optimized, and I suspect it is much slower than it should be. Currently, it laboriously fills the buffer byte by byte rather than splitting it into 64-bit chunks. (I did it this way because we were pressed on time, and I didn't want to accidentally introduce alignment issues.) We probably have a significant optimization opportunity there.

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci benchmark

**Comment by lorentey** [comment]
@swift-ci benchmark

**Comment by natecook1000** [comment]
> (I haven't measured it, but I think arc4random_buf may be a little bit slower than two calls to arc4random.)

I have! It's a lot slower (around 4x in my testing).

**Comment by lorentey** [comment]
@Azoy Let's get this merged! We can try more improvements in followup PRs.

**Comment by Azoy** [comment]
SGTM

**Comment by Azoy** [comment]
@lorentey can you merge?

**Pull request merged**
