### PR TITLE
Re-import LLVMSupport from llvm-project and enforce header includes only being used from the Swift fork when building stdlib

### PR DESCRIPTION
**Pull request by kubamracek**
This is supposed to be a continuation of <https://github.com/apple/swift/pull/31665>. It looks like that today when building the stdlib, we silently include a handful of headers from llvm-project instead of the LLVMSupport fork inside the swift project. Not sure if this is a new regression since <https://github.com/apple/swift/pull/31665>, but looks undesirable. This PR does a few things:

- imports the remaining ADT+Support headers into our fork (just like <https://github.com/apple/swift/pull/31665>)
- namespaces the definitions in the fork (just like <https://github.com/apple/swift/pull/31665>)
- actually enforces this to not regress again in the future by removing llvm-project/llvm/include from the include search path when building the stdlib -- this works in all of stdlib, with one exception, and that's SwiftRemoteMirrors, which needs more than just ADT+Support from LLVM, so I'm leaving fixing SwiftRemoteMirrors as a possible future improvement

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by compnerd — COMMENTED** [review]
I think that this is the right thing to do.  I just have a question about the implementation.  What revision of LLVMSupport did you pull the new headers from?  I would rather that we kept the entire implementation at a single revision.

The other thing is, perhaps we should have a test to catch this type of issue in the future?  We should ensure that any symbol in the runtime is `__swift::__runtime::llvm` and not `::llvm::`.

**Comment by kubamracek** [comment]
> I think that this is the right thing to do. I just have a question about the implementation. What revision of LLVMSupport did you pull the new headers from? I would rather that we kept the entire implementation at a single revision.

OK, let's try to use the same revision that #31665 imported, but I wonder whether it might be too old at this point. But I'll try and we'll see :)

In general, is the fork supposed to move forward with "upstream" at some point? Should we (later, separately) bump it to be up to date?

> The other thing is, perhaps we should have a test to catch this type of issue in the future? We should ensure that any symbol in the runtime is __swift::__runtime::llvm and not ::llvm::.

Right! That would be a very similar test to the "freestanding dependency check", right? If we had that, would you want to drop the CMake changes that try to un-include the search path to llvm-project, or would you want to keep both?

**Comment by compnerd** [comment]
> > I think that this is the right thing to do. I just have a question about the implementation. What revision of LLVMSupport did you pull the new headers from? I would rather that we kept the entire implementation at a single revision.
> 
> OK, let's try to use the same revision that #31665 imported, but I wonder whether it might be too old at this point. But I'll try and we'll see :)

Thanks!

> In general, is the fork supposed to move forward with "upstream" at some point? Should we (later, separately) bump it to be up to date?

It should absolutely move forward when we need to.  Otherwise ... well, reality is that it wont unless it happens without human intervention, and I'm not up to setting that up as of yet because I have some pressing items on my plate.

> > The other thing is, perhaps we should have a test to catch this type of issue in the future? We should ensure that any symbol in the runtime is __swift::__runtime::llvm and not ::llvm::.
> 
> Right! That would be a very similar test to the "freestanding dependency check", right? If we had that, would you want to drop the CMake changes that try to un-include the search path to llvm-project, or would you want to keep both?

Yes, it would be nearly identical - just no allowlist,.  I'd love to be able to drop the CMake change, but I wouldn't really fight it if you wanted to keep it.

**Comment by kubamracek** [comment]
@compnerd I can't seem to find the LLVM revision "22492eead218ec91d349c8c50439880fbeacf2b7" mentioned in <https://github.com/apple/swift/pull/31665#issuecomment-626064573> and in the commit message anywhere. GitHub doesn't know this commit hash on <https://github.com/llvm/llvm-project/>. Can you point me to this commit somehow? Is is possible it has a typo or that it's a local commit?

**Review by mikeash — APPROVED** [review]

**Comment by compnerd** [comment]
Ugh; I thought I was careful about using a revision in apple/llvm-project; I kinda want to suggest that we re-fork the file set if we cannot find it. 🤐

**Comment by kubamracek** [comment]
:) Ok, let me do that 👍

**Comment by kubamracek** [comment]
@compnerd Done. The PR diff is now pretty useless for review, so I recommend looking at individual commits instead.

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test Windows platform

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test macOS platform

**Comment by kubamracek** [comment]
@compnerd ok, this finally seems to build :) could you take a look?

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
Hmm, I don't fully understand the "pruning" commit.  It doesn't prune the header set, it changes the implementation in a bunch of places (including things like assertions).  I don't remember doing that.  The intent was to keep everything inline with upstream's implementation.

**Comment by kubamracek** [comment]
Let me re-do the history so make it more clear, but I actually believe that the changes you’re referring to are from you and I’m just re-applying them :) See e.g. DenseMap.h from < https://github.com/apple/swift/pull/31665/commits/bb102707ed86748d839ecd3cc1dbef725df69368>.

**Comment by kubamracek** [comment]
My guess is that those changes were meant to drop the dependency on EpochTracker.h?

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@compnerd History redone with more explanation in commit messages. Does it look good now?

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@compnerd ping :)

**Review by compnerd — APPROVED** [review]
Thanks, with the new patch set, its more understandable how/why the changes are being made.  I think that this should be okay (with swift-ci's blessing).

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test Windows platform

**Comment by kubamracek** [comment]
@swift-ci please test Windows platform

**Comment by kubamracek** [comment]
@swift-ci please test Windows platform

**Comment by kubamracek** [comment]
@swift-ci please test Windows platform

**Comment by kubamracek** [comment]
Dammit I clicked 'Squash' by accident :/

**Comment by kubamracek** [comment]
@compnerd suggestions? revert and re-merge without squashing? or leave it be and whoever wants to see the individual commits has to go find this PR?

**Comment by compnerd** [comment]
Bleh; hmm, I wonder how horrible it would be to just deal with the backlink to this PR.  They are individual here, so we don't necessary lose the content ... I don't think that this will get GC'ed right?

**Comment by kubamracek** [comment]
https://github.com/apple/swift/pull/40393

**Pull request merged**
