### PR TITLE
[PrunedLiveness] Branch summary merges to ending.

### PR DESCRIPTION
**Pull request by nate-chandler**
A branch instruction that is both a lifetime-ending user and also a non-lifetime-ending of a value should be regarded as a lifetime-ending user.

Without this, utilities that rely on PrunedLiveness such as `LinearLiveness` and `InteriorLiveness` both incorrectly report that a branch featuring a value and also a reborrow or guaranteed phi are non-ending.

rdar://130427564

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Review by atrick — APPROVED** [review]
LGTM thanks!

**Pull request merged**
