### PR TITLE
Remove a retain release pair in foreign string hashing

### PR DESCRIPTION
**Pull request by Catfish-Man**
Fixes rdar://problem/52157564

### CODE REVIEW

**Comment by Catfish-Man** [comment]
@swift-ci please benchmark

**Comment by Catfish-Man** [comment]
@swift-ci please smoke benchmark

**Comment by Catfish-Man** [comment]
wrong command >.<

**Comment by Catfish-Man** [comment]
@swift-ci please smoke test

**Review by milseman — APPROVED** [review]
LGTM, good find

**Pull request merged**
