### PR TITLE
[API notes] Remove all API notes present in the Xcode 9 SDKs.

### PR DESCRIPTION
**Pull request by jrose-apple**
The framework versions already superseded the files here, so let's not even bother building and packaging them. There *are* still a few frameworks that aren't shipping their own API notes at the moment, however, though some of them are deprecated in their entirety.

rdar://problem/32908357

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please clean test macOS

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test Linux

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by DougGregor** [comment]
Yay!

**Comment by jrose-apple** [comment]
@huonw, I can't reproduce this locally, and it doesn't seem related. Any ideas? https://ci.swift.org/job/swift-PR-osx/9040/testReport/junit/Swift(appletvsimulator-x86_64)/Driver/loaded_module_trace_append_swift/

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test Linux

**Comment by jrose-apple** [comment]
@swift-ci Please clean test macOS

**Comment by jrose-apple** [comment]
@swift-ci Please clean test macOS

**Comment by jrose-apple** [comment]
@swift-ci Please clean test macOS

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test Linux

**Comment by jrose-apple** [comment]
Blocked on updating the builders to beta 2 or later, where GameplayKit's API notes appear correctly in the iOS SDK. @shahmishal?

**Comment by shahmishal** [comment]
Xcode updated to Xcode 9 beta 2

@swift-ci Please test macOS

**Comment by jrose-apple** [comment]
Thanks, Mishal! It matters that the API notes are actually absent from the build directory, so just to be sure…

@swift-ci Please clean test macOS

**Review by xpl0re — COMMENTED** [review]
Looks fine to me although did you mean to remove the linebreak at the end of NotificationCenter.apinotes?
Is there a way that we can get the latest version of the apinotes from the latest SDK rather than relying on potentially old copies in the test directory?

**Comment by jrose-apple** [comment]
If we're not grabbing headers from the SDKs, we shouldn't really grab new copies of the API notes either. These are all test data at this point—in many cases I deliberately removed most of the annotations that are in the real SDKs.

I didn't mean to remove the linebreak but it doesn't make a difference.

**Comment by jrose-apple** [comment]
Ah, note that these testing API notes will never be used with real SDKs, only with the testing headers. That's why it's not an issue.

**Pull request merged**
