### PR TITLE
[stdlib] Use subscript { _read } for various views

### PR DESCRIPTION
**Pull request by airspeedswift**
One more, using it mostly for all the lazy wrappers.

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please benchmark

**Comment by airspeedswift** [comment]
@rjmccall benchmarks are neutral for this set, is the feeling if it doesn't do any harm it's better to make this switch?

**Comment by rjmccall** [comment]
Yeah, I'd say so.  We'll eventually take advantage of it better.

**Comment by airspeedswift** [comment]
@swift-ci please test

**Pull request closed without merging**
