### PR TITLE
Add benchmarks exercizing bridged rangeOfString more thoroughly

### PR DESCRIPTION
**Pull request by Catfish-Man**

### CODE REVIEW

**Comment by Catfish-Man** [comment]
@swift-ci please smoke benchmark

**Comment by Catfish-Man** [comment]
@swift-ci please smoke benchmark

**Comment by Catfish-Man** [comment]
@swift-ci please smoke test

**Review by natecook1000 — APPROVED** [review]
Looks great! 👏🏻

**Pull request merged**
