### PR TITLE
Merge tag 'swift-DEVELOPMENT-SNAPSHOT-2019-12-02-a' into tensorflow-merge

### PR DESCRIPTION
**Pull request by burmako**

### CODE REVIEW

**Comment by burmako** [comment]
@swift-ci Please test tensorflow

**Comment by burmako** [comment]
@swift-ci Please test tensorflow

**Comment by burmako** [comment]
@swift-ci Please clean test tensorflow

**Review by dan-zheng — APPROVED** [review]

**Comment by burmako** [comment]
@swift-ci Please clean test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by burmako** [comment]
@swift-ci Please test tensorflow

**Comment by burmako** [comment]
@swift-ci Please test tensorflow

**Comment by burmako** [comment]
@swift-ci Please test tensorflow

**Comment by burmako** [comment]
@swift-ci Please test tensorflow

**Comment by burmako** [comment]
@swift-ci Please clean test tensorflow

**Comment by burmako** [comment]
@swift-ci Please clean test tensorflow

**Comment by burmako** [comment]
@swift-ci Please clean test tensorflow

**Comment by burmako** [comment]
Status update:
* `utils/build-script --preset=tensorflow_test` works on Linux.
* `utils/build-script --preset=tensorflow_test` works on macOS.
* `utils/build-toolchain-tensorflow -t` works on Linux except for https://bugs.swift.org/browse/TF-1045.
* `utils/build-toolchain-tensorflow -t` works on macOS according to Dan.
* Rapid works.
* CI is in progress.

We decided the following:
* Wait until CI finishes (we expect a success because similar checks succeeded above).
* Merge this PR as is.
* Disable llbuild tests in `utils/build-toolchain-tensorflow -t` in subsequent PR to work around https://bugs.swift.org/browse/TF-1045.

**Pull request merged**
