### PR TITLE
 [AutoDiff] Fix printing/serialization for `@differentiating` attribute.

### PR DESCRIPTION
**Pull request by dan-zheng**
Print and serialize `@differentiating` attribute `wrt` parameters. Add tests.

### CODE REVIEW

**Comment by dan-zheng** [comment]
This PR depends on https://github.com/apple/swift/pull/23379; rebase after it is merged.

**Review by rxwei — APPROVED** [review]

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
Merge after https://github.com/apple/swift/pull/23384; tests are blocked because they use `@differentiating` on derivatives with extra generic constraints.

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow linux

**Pull request merged**
