### PR TITLE
[stdlib] Test if two ascii string pointers are equal before memcmp

### PR DESCRIPTION
**Pull request by airspeedswift**
Initially just an experiment to see if it impacts our benchmarks.

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please benchmark

**Comment by airspeedswift** [comment]
@swift-ci please smoke test

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@swift-ci please benchmark

**Review by milseman — APPROVED** [review]
LGTM.

**Pull request merged**
