### PR TITLE
[TF] Helpers to facilitate the move to swift-apis.

### PR DESCRIPTION
**Pull request by eaplatanios**
@rxwei This should allow testing tensorflow/swift-apis#137.

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Review by rxwei — APPROVED** [review]
Let's make them internal again once things get moved.

**Comment by eaplatanios** [comment]
> Let's make them internal again once things get moved.

Sounds good. They are internal in TensorFlowGraph/swift-apis#109 and my plan is to keep that PR updated to our "desired state" and then after merging all component PRs, merge that one which will revert minor changes such as this one.

**Comment by rxwei** [comment]
Did it compile for you locally?

**Comment by eaplatanios** [comment]
It's still compiling and didn't get to that point. I'll fix this now. One issue I'm having is that I made these changes in a complete new clone of the repo so I need to wait for a clean compile to finish before I use incremental compilation.

**Comment by eaplatanios** [comment]
I fixed this failure and pushed but still waiting for it compile locally. It'd probably be faster to rerun the CI tests.

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Pull request merged**
