### PR TITLE
Switch back to the old mangling for ObjC runtime names.

### PR DESCRIPTION
**Pull request by eeckstein**
To be backward compatible to existing archives created by the NSKeyedArchiver

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci Please smoke test and merge

**Comment by slavapestov** [comment]
What so we need the old remangler for?

**Comment by slavapestov** [comment]
Instead of using the old remangler to remangle the name, can we directly construct the old name? It should be a non-generic class so there are only a couple of cases to handle, and it's a lot less new code.

**Comment by eeckstein** [comment]
@slavapestov No, we also do it for generic classes at runtime. And for that we need the re-mangler.
What we could do is to remove the code for all nodes which are not really created in the node tree.

**Comment by slavapestov** [comment]
That is really unfortunate. I recently added two new node kinds. What will the oldnremangler  do if they appear in the tree?

**Comment by eeckstein** [comment]
It's not that unfortunate because it's only a temporary thing. We'll remove the old remangler again.

> What will the oldnremangler do if they appear in the tree?

The old remangler will not compile.
But as I said, we could just support the nodes which are really created at runtime. This needs some refactoring. But then adding new nodes will not require changes in the old remangler.

**Comment by eeckstein** [comment]
@swift-ci Please smoke test and merge

**Comment by eeckstein** [comment]
@swift-ci Please smoke test and merge

**Comment by eeckstein** [comment]
@swift-ci Please smoke test and merge

**Pull request merged**
