### PR TITLE
Reduce breaks in CodeView linetables

### PR DESCRIPTION
**Pull request by ellishg**
Summary:
CodeView does not recognize zero as an artificial line location
and so a line location of zero causes unexpected behavior when
stepping through user code. If we find a line location of zero
and our scope has not changed, we use the most recent debug
location. That is expected to be the user code that most likely
relates to the current instruction and is similar to the behavior
in LLDB.

Test Plan:
test/DebugInfo/linetable-codeview.swift

### CODE REVIEW

**Comment by sparkasaurusRex** [comment]
@dcci These changes were reverted earlier because of a failed test. I fixed the test by capturing the name of `myArray` and I think it should work now.
apple/swift#18430

**Comment by dcci** [comment]
@swift-ci please test

**Review by dcci — APPROVED** [review]
lgtm

**Comment by dcci** [comment]
@sparkasaurusRex please take a look at the bots and don't hesitate to submit a follow up to fix/revert in case something is wrong :)

**Comment by dcci** [comment]
(in the meanwhile, I merged the request)

**Pull request merged**
