### PR TITLE
Updated quick help XML to separate the comment data from the metadata

### PR DESCRIPTION
**Pull request by mxswd**
This way you know which parts are from comments and which parts are from the compiler.

### CODE REVIEW

**Comment by mxswd** [comment]
@swift-ci please test

**Comment by mxswd** [comment]
@swift-ci please test

**Comment by mxswd** [comment]
@swift-ci please test

**Comment by mxswd** [comment]
@swift-ci please test

**Comment by mxswd** [comment]
@swift-ci please test

**Review by bitjammer — APPROVED** [review]

**Pull request merged**
