### PR TITLE
Add `libSwiftScan` entry-point to query target info.

### PR DESCRIPTION
**Pull request by artemcm**
This provides the library with functionality to answer `-print-target-info` queries in place of calls to `swift-frontend`.

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test Linux platform

**Review by nkcsgexi — APPROVED** [review]

**Comment by artemcm** [comment]
@swift-ci please test Linux platform

**Comment by artemcm** [comment]
@swift-ci please test macOS platform

**Pull request merged**
