### PR TITLE
Re-apply thunk generic signature optimization

### PR DESCRIPTION
**Pull request by slavapestov**
Tests are still WIP.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please benchmark

**Comment by slavapestov** [comment]
@swiftix and @eeckstein, do the optimizer fixes look reasonable?

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please benchmark

**Comment by slavapestov** [comment]
Test failure looks like a simulator issue:

```
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator10.0.sdk simctl spawn 'Apple TV 1080p'  /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/validation-test-appletvsimulator-x86_64/stdlib/Prototypes/Output/PersistentVector.swift.gyb.tmp/a.out
01:47:50 --
01:47:50 Exit Code: 133
01:47:50 
01:47:50 Command Output (stdout):
01:47:50 --
01:47:50 dyld: bad rebase type 0 in /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/validation-test-appletvsimulator-x86_64/stdlib/Prototypes/Output/PersistentVector.swift.gyb.tmp/a.out
01:47:50 Child process terminated with signal 5: Trace/BPT trap
```

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Comment by eeckstein** [comment]
EscapeAnalysis: good catch! LGTM. Thanks for fixing this!

**Pull request merged**
