### PR TITLE
Debug Info: Handle vector types when extending variable live ranges.

### PR DESCRIPTION
**Pull request by adrian-prantl**
This fixes a crash in IRGen (rdar://problem/27891980).

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci Please test

**Comment by adrian-prantl** [comment]
@swift-ci Please smoke test and merge

**Comment by adrian-prantl** [comment]
Linux test failure is unrelated
@swift-ci Please smoke test Linux platform and merge

**Comment by adrian-prantl** [comment]
@swift-ci Please smoke test Linux Platform

**Comment by adrian-prantl** [comment]
@swift-ci Please merge

**Comment by eeckstein** [comment]
LGTM

**Pull request merged**
