### PR TITLE
Rdar 29016063 swift 3.1 branch precompile bridging header

### PR DESCRIPTION
**Pull request by graydon**
Cherry-pick for swift-3.1-branch of https://github.com/apple/swift/pull/5977

Includes option setting the bridging PCH system to off by default.

See rdar://29016063

### CODE REVIEW

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by graydon** [comment]
Unfortunately it won't build without its corresponding change in clang: https://github.com/apple/swift-clang/pull/61

**Comment by jrose-apple** [comment]
Which we can do!

apple/swift-clang#61
@swift-ci Please test

**Comment by jrose-apple** [comment]
…unless update_checkout fails for some reason. @erg?

**Comment by graydon** [comment]
apple/swift-clang#61
@swift-ci Please test

**Comment by graydon** [comment]
"18:39:57 NameError: global name 'lock' is not defined" uh yes, that's not me!

**Comment by erg** [comment]
The swift-3.1-branch got the update-checkout parallelize patch but not the fix for that patch 8526d16c0b0bfa3f20571a2547b62628c1d1673c.

If you use ``shell.run`` before calling ``run_parallel`` the global lock that synchronizes writes to console is not initialized yet.

This patch 8526d16c0b0bfa3f20571a2547b62628c1d1673c  should get into swift-3.1-branch.

**Pull request merged**
