### PR TITLE
[ConstraintSolver] Skip generic overloads only if non-generic choices produce higher score solutions

### PR DESCRIPTION
**Pull request by xedin**
Restrict skipping of the generic overloads only to the situations
when non-generic solution doesn't have any restrictions/fixes, because
there is a possibility that generic overload could produce a better
solution.

Resolves: rdar://problem/32204609.

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@rudkx Could you please take a look and let me know if that's a good generic direction for this? 

There is a test failure related to unmapped generic parameters in the solution in the IDE test, I'll debug that later if you think that this is a viable approach.

**Review by DougGregor — APPROVED** [review]
LGTM, and looking forward to the generalization of the new score kind to all pointer conversions.

**Review by rudkx — APPROVED** [review]
LGTM!

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Pull request merged**
