### PR TITLE
Start gutting ExprCleaner and friends

### PR DESCRIPTION
**Pull request by slavapestov**
Thanks to @rudkx's work on the constraint system type map, we can actually enforce that Exprs don't get type variables stored into them.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
Cool, thanks! @xedin took care of the `TypeLoc` issues here. I had thought the last time I attempted to rip some of these save & restore type things out I hit issues with the diagnostics code, but perhaps I made some obvious mistake.

**Pull request merged**
