### PR TITLE
[+0-all-args] Make SILGenBuilder::createUncheckedBitCast more correct.

### PR DESCRIPTION
**Pull request by gottesmm**
The main change here is that we no longer forward ownership through
unchecked_bitwise_cast. The reason why is that unchecked_bitwise_cast creates a
new "reference count" identity to the optimizer. This is reflected in the SIL
ownership model by unchecked_bitwise_cast returning a value with unowned
ownership. We really do not want to traffic in such values, so we copy the value
after the cast to ensure that result is valid.

Found while updating SILGen tests for +0.

rdar://34222540

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by gottesmm** [comment]
@swift-ci clean smoke test linux platform

**Comment by atrick** [comment]
This invalidates comments in the ownership classifier:
```
// If both the operand and the result are nontrivial, then either the types must
// be compatible so that TBAA doesn't allow the destroy to be hoisted above uses
// of the cast, or the programmer must use Builtin.fixLifetime.
```
I think it would be a good idea to comment reinterpret cast in Builtins.def and Builtinst.swift (on the API too) to set the expectation that it copies nontrivial, nonreference types, but doesn't copy plain old references (most unfortunate).

**Comment by atrick** [comment]
Correction. I think the only issue with this PR is the wrong comment in the ownership classifier. I was originally thinking that users would assume that Builtin.reinterpretCast doesn't make a semantic copy of its argument. But we can't provide that guarantee anyway. I just hope this doesn't regress performance somewhere important.

**Comment by gottesmm** [comment]
Before I commit this, I am going to add some more testing around this to prove/disprove what Andy is saying.

**Comment by gottesmm** [comment]
(prove/disprove is too strong, but I think it is unfortunate that we don't have tests here AFAIKT. I am going to look for them and verify them or if they don't exist write them)

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by gottesmm** [comment]
I am going to use this PR to land a few other changes that depend on this singular change.

**Comment by gottesmm** [comment]
@atrick I filed https://bugs.swift.org/browse/SR-7175 and added a fat FIXME.

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by atrick** [comment]
I think your change makes sense and is safer. As long as we don't have a serious regression then I'm all for it.

**Pull request merged**
