### PR TITLE
[5.0] [String] Last-minute ABI adjustment: 4-bit discriminator

### PR DESCRIPTION
**Pull request by milseman**
5.0 cherry-pick of https://github.com/apple/swift/pull/21310

rdar://problem/46663653

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
Failure is:

```
/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.0-branch/swiftpm/Sources/SourceControl/RepositoryManager.swift:42:37: error: 'Result' is ambiguous for type lookup in this context
19:41:24     public typealias LookupResult = Result<RepositoryHandle, AnyError>
19:41:24                                     ^~~~~~
19:41:24 Swift.Result:1:13: note: found this candidate
19:41:24 public enum Result<Success, Failure> where Failure : Error {
19:41:24             ^
19:41:24 Basic.Result:1:13: note: found this candidate
19:41:24 public enum Result<Value, ErrorType> where ErrorType : Error {
19:41:24             ^
19:41:24 --- bootstrap: error: build failed with exit status 1
```

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
Please test with following pull request:
apple/swift-lldb#1169

@swift-ci please test

**Comment by milseman** [comment]
Please test with following pull request:
apple/swift-lldb#1169

@swift-ci please test os x platform

**Comment by milseman** [comment]
@apple/swift5-branch-managers

### Convergence

We will want this ASAP, preferably beta 1.

### ABI impact

This change's String's ABI to only use the high 4 bits of `_BridgeObject`, effectively extending the address space to 60 bits. This is especially important for architectures implementing ARMv8.5 memory tagging.

**Comment by milseman** [comment]
Failure is due to an ABI checker bug that hasn't been cherry-picked to 5.0

**Comment by milseman** [comment]
Please test with following pull request:
apple/swift-lldb#1169

@swift-ci please test

**Review by AnnaZaks — APPROVED** [review]

**Pull request merged**
