### PR TITLE
IRGen: Don't emit debug info for dependent member types

### PR DESCRIPTION
**Pull request by slavapestov**
Follow-up to https://github.com/apple/swift-lldb/pull/1259.

### CODE REVIEW

**Review by adrian-prantl — APPROVED** [review]

**Comment by adrian-prantl** [comment]
Is anything on the LLDB side blocking us from landing this? It would be good to get this into the swift-5.1 branches of LLDB and Swift since that is where most upstream Swift LLDB development is happening.

**Comment by slavapestov** [comment]
@adrian-prantl Thanks for the nudge. I need to finish off https://github.com/apple/swift-lldb/pull/1286 (just a couple of test failures on Linux...)

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Comment by compnerd** [comment]
This caused a regression on the Windows build.

**Pull request merged**
