### PR TITLE
Make the DWARF version emitted by the Swift compiler configurable.

### PR DESCRIPTION
**Pull request by adrian-prantl**
Previously it was hardcoded to version 4 on all platforms.
This patch introduces new driver and frontend flags -dwarf-version=<N>.

This PR includes https://github.com/apple/swift/pull/69255, due to a tiny dependency.

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test with https://github.com/apple/swift-driver/pull/1467

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-driver/pull/1467
@swift-ci test

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-driver/pull/1467
@swift-ci test

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-driver/pull/1467
@swift-ci test

**Review by artemcm — APPROVED** [review]

**Comment by adrian-prantl** [comment]
(There's an LLDB dependency that I didn't forsee so I'll put his on ice until after rebranch)

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-driver/pull/1467
test with https://github.com/apple/llvm-project/pull/7668
@swift-ci smoke test

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-driver/pull/1467
test with https://github.com/apple/llvm-project/pull/7668
@swift-ci test windows

**Pull request merged**
