### PR TITLE
[stdlib] Break infinite recursion false positive in _fatalErrorMessage

### PR DESCRIPTION
**Pull request by harlanhaskins**
Introduce an inner function that breaks the infinite recursion check, silencing this warning:

```
swift/stdlib/public/core/AssertCommon.swift:166:15: warning: all paths through this function will call itself
internal func _fatalErrorMessage(
              ^
```

### CODE REVIEW

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test

**Comment by natecook1000** [comment]
Thaaaaaaank you

**Comment by harlanhaskins** [comment]
That's what I get for using the GitHub Web Editor :sweat_smile:

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test

**Comment by harlanhaskins** [comment]
Manually checked the log, the warning is gone.

**Review by airspeedswift — APPROVED** [review]

**Pull request merged**
