### PR TITLE
[stdlib] Fix memory leaks in readLine()

### PR DESCRIPTION
**Pull request by benrimmington**
<https://bugs.swift.org/browse/SR-6127>

### CODE REVIEW

**Comment by benrimmington** [comment]
@milseman This pull request only fixes memory leaks (NFC). There hasn't been much feedback for #21586 on the [forums](https://forums.swift.org/t/newlines-in-text-streams/19346).

**Comment by benrimmington** [comment]
@mikeash The `swift_stdlib_readLine_stdin` function is currently marked `SWIFT_RUNTIME_STDLIB_API`. Have [RuntimeShims.h](https://github.com/apple/swift/blob/master/stdlib/public/SwiftShims/RuntimeShims.h) and [RuntimeStubs.h](https://github.com/apple/swift/blob/master/stdlib/public/SwiftShims/RuntimeStubs.h) been audited yet?

**Comment by mikeash** [comment]
I don't know! Which probably means... no?

**Review by milseman — APPROVED** [review]
LGTM

**Comment by milseman** [comment]
@benrimmington sorry, there's been some last-minute 5.0 fixes coming up. I'll try to follow up on that thread later this week.

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please test OS X Platform

**Comment by milseman** [comment]
@swift-ci please test os x platform

**Comment by benrimmington** [comment]
@milseman All checks have passed. I also used the `leaks` command, to show that [SR-6127](https://bugs.swift.org/browse/SR-6127) has been fixed. The `getline` API can allocate memory even if EOF is encountered, so the `defer` statement is placed before any `return` statements.

* What should happen if `swift_stdlib_readLine_stdin` returns zero? This results in an empty string with the old implementation.
* I'm also worried that `String._fromUTF8Repairing` might not handle an empty buffer pointer with a `nil` base address.

**Comment by benrimmington** [comment]
@milseman The `swift_stdlib_readLine_stdin` for Windows returns -1 if `(ch == EOF && Pos == 0)`.

I'd expect `getline` to block if there's no data available. The `man getline` page on macOS has example code that treats both -1 and zero as EOF. We could do the same here.

**Comment by benrimmington** [comment]
> A size > 0 should imply a non-null pointer, so we can assert or precondition failure on.

@milseman Can we rely on the existing [_precondition](https://github.com/apple/swift/blob/005abcc3e9a378afa1984727bf9e4c0a16b6df2f/stdlib/public/core/UnsafeBufferPointer.swift.gyb#L403-L405) in UnsafeBufferPointer?

**Comment by benrimmington** [comment]
@milseman I've squashed the commits. Please merge if possible.

**Comment by milseman** [comment]
@swift-ci please test and merge

**Comment by benrimmington** [comment]
* Build [#1635](https://ci.swift.org/job/swift-PR-merge/1635/console) failed with "Automatically restarting the build, due to invalid sha";

* Build [#1636](https://ci.swift.org/job/swift-PR-merge/1636/console) failed with "ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job."

**Comment by milseman** [comment]
@swift-ci please test

**Comment by benrimmington** [comment]
All checks have passed.

**Comment by airspeedswift** [comment]
I think it makes sense to let this get picked up for 5.1.

**Pull request merged**
