### PR TITLE
[docs] Modernize LibraryEvolution.rst, part 1

### PR DESCRIPTION
**Pull request by jrose-apple**
- Remove discussion of future directions and open issues. I'll put this back soon, in a different place.
- Bring the per-decl restrictions up to date, and replace the term "versioned" with the term "ABI-public" from [SE-0193](https://github.com/apple/swift-evolution/blob/master/proposals/0193-cross-module-inlining-and-specialization.md).
- Add in notes about Swift 5 and 5.1 language features: property wrappers, `@dynamicCallable`…and function builders, even though they haven't formally been accepted to the language yet.

Part 2 (#28007) will be bringing back the future directions and open issues in a separate document, ~and possibly making this one a little more convenient for people just wanting to check whether they're following the rules~.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Comment by Gankra** [comment]
request: please explicitly call out the implications of a struct with a "please pass all the fields" default initializer. A naive reading of this document suggests it "should" be ABI-compatible to add a field, but it's not because it changes the signature of the default initializer, and I don't see any way that version attributes would allow the old version of the initializer to continue to exist (since nothing declares a default value to use).

(Might be implied by a section I skimmed over, happy to be wrong)

```swift

// Library Code

// version 1
struct MyTypeV1 {
    public var x: Int;
}

// version 2
struct MyTypeV2 {
    public var x: Int;
    public var y: Int;
}




// App Code

MyTypeV1(x: 0); // linked against v1
MyTypeV2(x: 0); // linked against v2

// error: missing argument for parameter 'y' in call
// MyTypeV2(x: 0); // linked against v2
//              ^
//              , y: <#Int#>
```

**Comment by Gankra** [comment]
Following up on twitter discussion, you should maybe remove the link to your hosted rendering that's at the top of this document, assuming you don't want that to exist anymore.

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Pull request merged**
