### PR TITLE
[5.0] Teach the SIL cast optimizer to handle conditional conformance.

### PR DESCRIPTION
**Pull request by atrick**
Previously the cast optimizer bailed out on any conformance with
requirements.

We can now constant-propagate this:

```
protocol P {}
struct S<E> {
  var e: E
}

extension S : P where E == Int {}

func specializeMe<T>(_ t: T) {
  if let p = t as? P {
    // do fast things.
  }
}

specializeMe(S(e: 0))
```

This turns out to be as simple as calling the TypeChecker.

<rdar://problem/46375150> Inlining does not seem to handle
specialization properly for Data.

This enabled two SIL transformations required to optimize
the code above:

(1) The witness method call can be devirtualized.

(2) The allows expensive dynamic runtime checks such as:

  unconditional_checked_cast_addr Array<UInt8> in %array : $*Array<UInt8> to ContiguousBytes in %protocol : $*ContiguousBytes

Will be converted into:

  %value = init_existential_addr %existential : $*ContiguousBytes, $Array<UInt8>
  store %array to %value : $*Array<UInt8>

(cherry picked from commit 0976c1f76e8126e3a6a422191a1df69ee2e65b1b)

### CODE REVIEW

**Comment by atrick** [comment]
** --- CCC --- **

Explanation: Teach the SIL cast optimizer to handle conditional conformance.

Scope: Only affects -O builds. Broadens existing optimization to apply to code with conditional conformance.

Issue: <rdar://problem/46375150> Blocking DataProtocol: specializing the Data initializer from Sequence fails to remove the protocol type check with conditional conformance.

Risk: Medium. Changes the cast optimizer's conformance lookup to use an existing TypeChecker API. There is no new conformance checking logic and no new optimization. It just enables existing optimization by using the more precise TypeChecker API. As always, enabling more optimization risks exposing other optimizer bugs.

Testing: New unit tests were added to cover all the interesting cases. Testing and benchmarking was also done on the pending DataProtocol branch.

**Comment by atrick** [comment]
@slavapestov could you review for 5.0. This is the code that you reviewed on master with

- one additional call to the new `conformsToProtocol` from the CastOptimizer, with only indentation changes following that call.

- some unit tests.

**Comment by atrick** [comment]
I forgot to mention in CCC: The reason for taking this into 5.0 is that it blocks the addition of DataProtocol which is an ABI change.

**Comment by atrick** [comment]
@DougGregor Do you have a quick moment to review. I'm told we want to merge this now before the branch is 5.0 tagged this afternoon.

It's the same thing you reviewed on master with:
- one additional call to the new conformsToProtocol from the CastOptimizer, with only indentation changes following that call.

- some unit tests.

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
@swift-ci test source compatibility.

**Comment by atrick** [comment]
@swift-ci test OS X platform.

**Comment by atrick** [comment]
@swift-ci smoke test linux platform.

**Comment by atrick** [comment]
SCK testing fails the same way on Jenkins:
<rdar://problem/46676048> Swift CI OSS: SCK project line-sdk-ios-swift_4.2: SILGenLValue.cpp, 847. Assertion failed: (base.getType().isAddress() && "base value of open-existential component was not an address?")

**Review by eeckstein — APPROVED** [review]
lgtm

**Comment by eeckstein** [comment]
@swift-ci test linux

**Review by slavapestov — APPROVED** [review]

**Comment by atrick** [comment]
The full linux build failed earlier on the unit test added by this PR because of a dependence on another PR. The linux smoke test reran that same unit test and passed.

**Pull request merged**
