### PR TITLE
Emit references to shadowed variables in if-let shorthands

### LINKED ISSUE #76805: Indexstore for if let shorthand bound variables references shadowed declaration instead of local variable
### Description

When compiling with indexstore outputs, the indexstore data is inconsistent when a file contains if-let shorthand syntax compared to when it does not use the shorthand. When using the shorthand, the indexstore references inside of the block reference the shadowed declaration instead of the local variable defined by the if-let pattern. When not using the shorthand, the indexstore references inside of the block reference the local variable defined in the if-let pattern.

### Reproduction

```swift
class Foo {
  var bar: Int?

  func doSomething() {
    if let bar {
      print(bar)
    }
    if let bar = self.bar {
      print(bar)
    }
  }
}
```

### Expected behavior

Consistent indexstore behavior for references inside of the if-statement blocks when using if-let shorthand and when not using if-let shorthand.

The sample code demonstrates both states. The indexstore for the 1st if-statement uses shorthand, and `bar` referenced in `print(bar)` references the instance variable of the class. For the 2nd if-statement, the `bar` referenced in `print(bar)` references a local variable.

In order to index local variables, you must enable `-index-include-locals`.

### Environment

swift-driver version: 1.113 Apple Swift version 6.0 (swiftlang-6.0.0.7.6 clang-1600.0.24.1)
Target: arm64-apple-macosx14.0

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dylansturg**
Variables defined in if-let shorthand now get their own definition and references to the variable use that definition.

Track the original-decl/captured decl as part of the symbol passed to the IndexConsumer. This allows the Rename consumer to check if the symbol is a shadowed reference to a decl being renamed, without the index skipping the other relevant output when visiting shadowing variables.

This change stores variables from if-let shorthand syntax in the indexstore, when indexing locals, because those are local variables too. As opposed to purely being references to their shadowed declaration.

Resolves https://github.com/swiftlang/swift/issues/76805

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Review by bnbarham — APPROVED** [review]
Thanks for working through this @dylansturg 🙇‍♂️. LGTM assuming all the other tests pass!

**Comment by dylansturg** [comment]
The failure for macOS seems unrelated. It looks like the build at head is failing with the same error; looking at https://ci.swift.org/job/oss-swift-incremental-RA-macos/.

Hopefully that's resolved soon and we can retry.

**Comment by hamishknight** [comment]
@swift-ci please test macOS

**Review by hamishknight — APPROVED** [review]

**Pull request merged**
