### PR TITLE
Fix a pair of crashes with '@unknown'

### PR DESCRIPTION
**Pull request by jrose-apple**
Fixes a pair of issues @rintaro caught around misuse of `@unknown default`. Let's not crash on bad user input!

[SR-7408](https://bugs.swift.org/browse/SR-7408), [SR-7409](https://bugs.swift.org/browse/SR-7409)

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Review by rintaro — APPROVED** [review]
Diagnostics look great. Thank you!

**Comment by CodaFi** [comment]
If the `@unknown` is structural, I think it ought to go into the type checker proper before we enter the exhaustiveness checker.  That'll let you keep your assertion.

**Comment by jrose-apple** [comment]
Yeah, I forgot about `limitedChecking` when I wrote this. The first commit is probably still valuable, but the second should just be caught earlier.

**Comment by jrose-apple** [comment]
New version of the second commit (SR-7409).

@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by jrose-apple** [comment]
Snuck in another PrettyStackTrace too.

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Pull request merged**
