### PR TITLE
[metadata prespecialization] Add canonical prespecialization to end of type descriptors.

### PR DESCRIPTION
**Pull request by nate-chandler**
Enumerating the canonical prespecializations at the end of the type descriptors enables both (1) lifting one of the limitations on cross-module prespecializations and also (2) lifting the logic for iterating through the canonical prespecializations from individual metadata accessors into getGenericMetadata.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test windows

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test macos

**Comment by nate-chandler** [comment]
@swift-ci please test windows

**Pull request merged**
