### PR TITLE
Revert "[metadata prespecialization] Support for classes."

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/swift#30089

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
Hi @compnerd , wouldn't it be more expedient to simply change the name in a different PR?

**Comment by compnerd** [comment]
@nate-chandler that sounds good to me.  Could you please put up a PR to do that?  My machine is updating.

This is the output from the logs:
```
stderr: error: unable to create file test/IRGen/prespecialized-metadata/class-fileprivate-inmodule-1argument-2ancestors-1distinct_use-1st_ancestor_generic-1argument-1st_argument_constant_int-2nd_ancestor_generic-1st-argument_constant_double.swift: Filename too long
error: unable to create file test/IRGen/prespecialized-metadata/class-fileprivate-inmodule-1argument-2ancestors-1distinct_use-1st_ancestor_generic-1argument-1st_argument_constant_int-2nd_ancestor_generic-1st-argument_subclass_argument.swift: Filename too long
error: unable to create file test/IRGen/prespecialized-metadata/class-fileprivate-inmodule-1argument-2ancestors-1distinct_use-1st_ancestor_generic-1argument-1st_argument_subclass_argument-2nd_ancestor_generic-1st-argument_constant_int.swift: Filename too long
```

**Comment by nate-chandler** [comment]
@compnerd Yup, doing it now.  Thanks for the logs!

**Comment by nate-chandler** [comment]
Okay, renaming PR is smoke testing at https://github.com/apple/swift/pull/32098 .

**Comment by compnerd** [comment]
Thanks for fixing up things!

**Pull request closed without merging**
