### PR TITLE
[ClangImporter] Add versioned stubs for import-as-member renames.

### PR DESCRIPTION
**Pull request by jrose-apple**
Builds on #8269 with a more general solution: import all versions of a name that are going to show up as members, ignore those that aren't.

Further work on \<rdar://problem/29170671> Import APIs under their Swift 3 names.

### CODE REVIEW

**Comment by jrose-apple** [comment]
(I'm going to wait for Michael's review on this one, but merge the other one as soon as possible to fix the crash.)

@swift-ci Please test

**Comment by jrose-apple** [comment]
The Linux failure was in LLDB? I suspect it's nothing, but let's go again.

@swift-ci Please test Linux

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test macOS

**Comment by jrose-apple** [comment]
Linux build got interrupted, but it looks like it made it through all the tests.

@swift-ci Please smoke test Linux

**Review by milseman — APPROVED** [review]
Cool. LGTM!

**Pull request merged**
