### PR TITLE
[SR-9713] [benchmark] Add script to automatically generate new benchmarks

### PR DESCRIPTION
**Pull request by BalestraPatrick**
After working on [SR-8908](https://bugs.swift.org/browse/SR-8908) as part of [SR-8905](https://bugs.swift.org/browse/SR-8905), I think the process of adding a new benchmark could be improved and automated. Right now, the [documentation](https://github.com/apple/swift/tree/master/benchmark#adding-new-benchmarks) mentions 3 steps in order to create and register a new single-source benchmark with the driver:
1. Add a new Swift file (YourTestNameHere.swift), built according to the template below, to the {{single-source}}directory.
2. Add the filename of the new Swift file to CMakeLists.txt
3. Edit main.swift. Import and register your new Swift module.
 
I'd like to see this process automated with a simple script that takes the name of a new benchmark and correctly creates, sets up the files and inserts the benchmark in the correct and sorted position for example. This is my implementation with a Python script that when invoked, generates the following:
```bash
swift-source$ ./swift/benchmark/scripts/create_benchmark.py InsertCollection
```

insert-bencmark

Resolves [SR-9713](https://bugs.swift.org/browse/SR-9713).

### CODE REVIEW

**Comment by palimondo** [comment]
@swift-ci python lint

**Comment by palimondo** [comment]
@swift-ci smoke test

**Comment by palimondo** [comment]
@swift-ci python lint

**Comment by palimondo** [comment]
@swift-ci smoke test

**Comment by BalestraPatrick** [comment]
Fixed all of them for real now after running the linter locally!

**Comment by palimondo** [comment]
Sorry, I cannot finish the review today, it’s too late here… maybe @eeckstein or @gottesmm can take over. Otherwise I’ll have a look at this tomorrow.

**Review by eeckstein — APPROVED** [review]

**Comment by BalestraPatrick** [comment]
Thanks @eeckstein for reviewing! CI might need a re-trigger since I pushed some new stuff since the last time it ran 👍

**Comment by palimondo** [comment]
@swift-ci python lint

**Comment by palimondo** [comment]
@swift-ci python lint

**Comment by palimondo** [comment]
@swift-ci smoke test and merge

**Pull request merged**
