### PR TITLE
Teach findAccessedStorage about global addressors.

### PR DESCRIPTION
**Pull request by atrick**
All but the last commit are covered by: https://github.com/apple/swift/pull/16870.

The only new change here is to enable strict verification of formal access on global variables and add unit tests.

AccessedStorage now properly represents access to global variables, even if they
haven't been fully optimized down to global_addr instructions.

This is essential for optimizing dynamic exclusivity checks. As a verified SIL property, all access to globals and class properties needs to be identifiable.

### CODE REVIEW

**Comment by atrick** [comment]
@shajrawi please look at just the last commit in this PR: https://github.com/apple/swift/pull/16877/commits/d72c91a242e8ff53b8f78fff5d37c2fcc4fc4c07

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
@swift-ci test source compatibility.

**Comment by atrick** [comment]
@swift-ci test.

**Comment by shajrawi** [comment]
@atrick d72c91a LGTM!

**Comment by shajrawi** [comment]
re PR - I do see this problem on the OS X bots:
```
Assertion failed: (address->getType().is<SILBoxType>()), function findAccessedStorage, file /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/lib/SIL/MemAccessUtils.cpp, line 269.
```

**Pull request closed without merging**
