### PR TITLE
[DNM] Experimentally disable speculative devirtualization

### PR DESCRIPTION
**Pull request by airspeedswift**
Just an experiment looking at code size vs benchmark impact.

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please benchmark

**Comment by airspeedswift** [comment]
@swift-ci please test compiler performance

**Comment by airspeedswift** [comment]
Note the "huge" regressions in the benchmarks are re-regressing use cases that were previously around this performance in the prior Swift release. Those benchmarks don't really represent true use cases. My view is the overall binary size cost of this optimization (LLVM bytes output reduces by 2% when it's turned off) isn't justified and we should probably turn it off until we can come up with a more targeted optimization.

**Comment by atrick** [comment]
@airspeedswift this optimization has hidden cost for compiler engineers--it significantly complicates and bloats the IR. I have always thought that speculative optimization should only be done in response to dynamic profiling or intelligent heuristics based on conventional use cases.

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
