### PR TITLE
Add script to build toolchain

### PR DESCRIPTION
**Pull request by johnno1962**
#### What's in this pull request?

A short script to document how to/build toolchain

master PR as per: 
https://github.com/apple/swift/pull/1563

duplicate of https://github.com/apple/swift/pull/1608 from fresh fork without unnecessary merges
#### Resolved bug number:

https://bugs.swift.org/browse/SR-174

### CODE REVIEW

**Comment by shahmishal** [comment]
Thanks!

**Comment by modocache** [comment]
Thanks so much for this, @johnno1962! This made it **much** easier for me to build an OS X toolchain.

**Comment by johnno1962** [comment]
Where were all those core files you found @modocache. You’ve got me worried now..

**Comment by modocache** [comment]
I found out that that was unrelated, but they appeared in `/cores`.

**Comment by danieleggert** [comment]
You need to start the script with `#!/bin/bash`, not `#/bin/bash`

**Comment by johnno1962** [comment]
Thanks Daniel, I’ll file a PR to fix this today.

**Pull request merged**
