### PR TITLE
Add builtin support for starting a task on a specific executor

### PR DESCRIPTION
**Pull request by rjmccall**

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please test

**Review by ktoso — APPROVED** [review]

**Comment by ktoso** [comment]
Looks good :)

**Comment by rjmccall** [comment]
@swift-ci Please smoke test macOS

**Comment by rjmccall** [comment]
The full macOS test run failed with some unrelated DocC thing; trying a smoke test.

**Comment by rjmccall** [comment]
@swift-ci Please smoke test macOS

**Pull request merged**
