### PR TITLE
[WIP] SemanticARCOpts: Don't copy let properties of classes.

### PR DESCRIPTION
**Pull request by jckarter**
If the lifetime of a value copied out of a let property in a class is dominated by the lifetime
of the base object it was copied from, then we don't need to copy at all, since the value of the
`let` is guaranteed as long as the base object is. rdar://problem/54531607

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please benchmark

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please benchmark

**Comment by jckarter** [comment]
@swift-ci Please benchmark

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by gottesmm** [comment]
Interesting. We are clearly with the global thing hitting more retain/release (look at those code-size improvements!) Wonder what the perf change is from.

**Comment by jckarter** [comment]
@gottesmm I would guess that global string constants could account for a lot of the code size difference, since even though they have no-op refcounts, the compiler still probably naively generates retains and releases for them.

**Pull request merged**
