### PR TITLE
Fix the scope guards in Scope.h

### PR DESCRIPTION
**Pull request by gottesmm**
This PR just fixes the scope guards of Scope.h.

Not much to see here.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci Please smoke test and merge

**Comment by jrose-apple** [comment]
You snuck another commit in here…

**Comment by gottesmm** [comment]
@jrose-apple I know.

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Pull request merged**
