### PR TITLE
[ownership] Move semantic-arc-opts and destroy hoisting right before eliminating ownership from non-transparent functions.

### PR DESCRIPTION
**Pull request by gottesmm**
Title says it all.

### CODE REVIEW

**Comment by gottesmm** [comment]
@eeckstein if you take this PR and run the test:

```
2.      While running pass #88 SILFunctionTransform "DestroyHoisting" on SILFunction "@$s22constrained_extensions12GenericClassCAAytRs_rlEyyxcig".
 for getter for subscript(_:) (at /Volumes/Files/gottesmm/work/solon/swift/test/SILGen/constrained_extensions.swift:164:10) 
```

You will hit that verification error.

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by eeckstein** [comment]
This is the fix: https://github.com/apple/swift/pull/28381

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Comment by gottesmm** [comment]
Rather than moving destroy hoisting as well (and dealing with any issues that may rise from that), I am instead just going to add an extra run later in the pipeline.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test Linux platform

**Comment by gottesmm** [comment]
@swift-ci test Linux platform

**Comment by gottesmm** [comment]
@swift-ci test linux platform

**Comment by varungandhi-apple** [comment]
@gottesmm in case that doesn't work, Mishal suggested trying a clean build.

**Pull request merged**
