### PR TITLE
Fix SILInliner Compilation on MSVC

### PR DESCRIPTION
**Pull request by gmittert**
`SILBuilder` contains a `SILBuilderContext` which contains a `SILModule` which
has a deleted operator=. Assigning an `Optional<BeginApplySite>` causes MSVC
to attempt to create `operator=` for `SILBuilder` which fails due to the
deleted `operator=`. This changes `BeginApplySite` to use a `SILBuilder*`
instead of a `SILBuilder&` to get around it.

Previously: 
```
C:\Users\jmittertreiner\LocalSwift\llvm\include\llvm/ADT/Optional.h(54): error C2280: 'swift::BeginApplySite &swift::BeginApplySite::operator =(const swift::BeginApplySite &)': attempting to reference a deleted function
C:\Users\jmittertreiner\LocalSwift\swift\lib\SILOptimizer\Utils\SILInliner.cpp(226): note: compiler has generated 'swift::BeginApplySite::operator =' here
C:\Users\jmittertreiner\LocalSwift\swift\lib\SILOptimizer\Utils\SILInliner.cpp(226): note: 'swift::BeginApplySite &swift::BeginApplySite::operator =(const swift::BeginApplySite &)': function was implicitly deleted because 'swift::BeginApplySite' has a data member 'swift::BeginApplySite::Builder' of reference type
C:\Users\jmittertreiner\LocalSwift\swift\lib\SILOptimizer\Utils\SILInliner.cpp(75): note: see declaration of 'swift::BeginApplySite::Builder'
C:\Users\jmittertreiner\LocalSwift\llvm\include\llvm/ADT/Optional.h(52): note: while compiling class template member function 'llvm::optional_detail::OptionalStorage<T,false> &llvm::optional_detail::OptionalStorage<T,false>::operator =(T &&)'
        with
        [
            T=swift::BeginApplySite
        ]
C:\Users\jmittertreiner\LocalSwift\llvm\include\llvm/ADT/Optional.h(65): note: see reference to function template instantiation 'llvm::optional_detail::OptionalStorage<T,false> &llvm::optional_detail::OptionalStorage<T,false>::operator =(T &&)' being compiled
        with
        [
            T=swift::BeginApplySite
        ]
C:\Users\jmittertreiner\LocalSwift\llvm\include\llvm/ADT/Optional.h(132): note: see reference to class template instantiation 'llvm::optional_detail::OptionalStorage<T,false>' being compiled
        with
        [
            T=swift::BeginApplySite
        ]
C:\Users\jmittertreiner\LocalSwift\swift\lib\SILOptimizer\Utils\SILInliner.cpp(93): note: see reference to class template instantiation 'llvm::Optional<swift::BeginApplySite>' being compiled
```

### CODE REVIEW

**Comment by gottesmm** [comment]
Just a meta comment (this is not a functionality review). Can you run this through git-clang-format? Swift does 'Type *', not 'Type*'

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by atrick** [comment]
LGTM

**Pull request merged**
