### PR TITLE
[CodeCompletion] Fix SR-627 Code Completion does not resolve generics…

### PR DESCRIPTION
**Pull request by ahoppen**
… that have been assigned a concrete type

### CODE REVIEW

**Comment by ahoppen** [comment]
No, I did a few modifications to PrinterArchetypeTransformer:
1) In the initialiser I added a loop to iterate over the superclasses of the type that provides more specific type information. This is necessary for the second test case, where I have something like the following

	class SR627_BaseClass<T> {
	  func myFunction(x: T) -> T? {
	    return nil
	  }
	}
	
	class SR627_Sublcass: BaseClass<String> {
	}
	
	class SR627_Sublcass: SR627_Sublcass {
	  #^COMPLETE_HERE^#
	}

T has been specialised one types further up in the inheritance chain and to pick this instantiation up, I need to have a look at all the superclasses.

2) I wrapped the implementation of `transformByName` in `Ty.transform` in order to instantiate generic types that are wrapped. Say a generic parameter `T` has ben instantiated with `String`, now `T?` is substituted by `String?` whereas previously the substitution would only have happened for the bare type `T`.

I couldn’t find any situation where the two changes would not make sense and they didn’t break any tests…

**Comment by ahoppen** [comment]
Wait a second before merging the pull request, just realised that I forgot to add the new test cases at the top of the file so that they are actually run

**Comment by ahoppen** [comment]
Fixed the issue with the tests, could you have a look at it again?

**Comment by nkcsgexi** [comment]
Could you squash them into one commit?

**Comment by ahoppen** [comment]
Sure, just squashed them

**Pull request merged**
