### PR TITLE
[AutoDiff] Rewrite and simplify activity analysis.

### PR DESCRIPTION
**Pull request by rxwei**
Rewrite activity analysis as two iterative loops over the dominator tree and the post-dominator tree. It cut the code length by half.

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux

**Review by dan-zheng — APPROVED** [review]
Astonishing elegance!

**Comment by rxwei** [comment]
Ok, this doesn't generalize side-effecting code yet. I'll start a follow-up patch.

**Pull request merged**
