### PR TITLE
[TypeResolution] Remove unnecessary parameter pack special case from function type resolution.

### PR DESCRIPTION
**Pull request by hborla**
This code is a remnant from when parameter packs and classic variadic parameters both used the '...' syntax. Now, parameter packs can use the standard `resolveType` code path.

### CODE REVIEW

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by sophiapoirier** [comment]
I wonder whether `maybeResolvePackExpansionType` as a distinct method even should exist with this change, or just be incorporated into `resolvePackExpansionType`?

**Comment by hborla** [comment]
@sophiapoirier you're right, `maybeResolvePackExpansionType` seems completely unnecessary now! I'll fold it into `resolvePackExpansionType`

**Comment by hborla** [comment]
@swift-ci please smoke test

**Pull request merged**
