### PR TITLE
[IRGen] Fix misalignment of conditional invertible requirement counts

### PR DESCRIPTION
**Pull request by Azoy**
The conditional invertible protocol set is alone as a 16 bit slot in the generic context, but items here are expected to be 4 bytes large, so some padding needs to accompany this value. If the number of invertible protocols that we're conditional on is even, we can stick a 0 after all of the requirement counts. Also, we were using `countBitsUsed` to determine how many requirement counts there were, but this is really testing the first bit in [1, 64] that is turned on instead of actually saying how many bits are turned on.

### CODE REVIEW

**Comment by Azoy** [comment]
@swift-ci please smoke test

**Review by DougGregor — APPROVED** [review]
Very nice find

**Comment by Azoy** [comment]
@swift-ci please smoke test Windows

**Comment by Azoy** [comment]
@swift-ci please smoke test Windows

**Comment by Azoy** [comment]
@swift-ci please smoke test

**Comment by Azoy** [comment]
@swift-ci please smoke test

**Comment by Azoy** [comment]
@swift-ci please smoke test

**Comment by Azoy** [comment]
@swift-ci please smoke test

**Comment by hjyamauchi** [comment]
@Azoy I haven't precisely reproduced but this PR might have caused [this build error](https://github.com/thebrowsercompany/swift-build/actions/runs/8913037213/job/24478448044) on windows ARM64 (it is fine on X86_64):

```
   Creating library lib\_InternalSwiftStaticMirror.lib and object lib\_InternalSwiftStaticMirror.exp
swiftStaticMirror.lib(ObjectFileContext.cpp.obj) : error LNK2019: unresolved external symbol __popcnt referenced in function "protected: unsigned int __cdecl swift::TrailingGenericContextObjects<struct swift::TargetAnonymousContextDescriptor<struct swift::External<struct swift::NoObjCInterop<struct swift::RuntimeTarget<4> > > >,struct swift::TargetGenericContextDescriptorHeader,struct swift::TargetMangledContextName<struct swift::External<struct swift::NoObjCInterop<struct swift::RuntimeTarget<4> > > > >::getNumConditionalInvertibleProtocolsRequirementCounts(void)const " (?getNumConditionalInvertibleProtocolsRequirementCounts@?$TrailingGenericContextObjects@U?$TargetAnonymousContextDescriptor@U?$External@U?$NoObjCInterop@U?$RuntimeTarget@$03@swift@@@swift@@@swift@@@swift@@UTargetGenericContextDescriptorHeader@2@U?$TargetMangledContextName@U?$External@U?$NoObjCInterop@U?$RuntimeTarget@$03@swift@@@swift@@@swift@@@2@@swift@@IEBAIXZ)

bin\_InternalSwiftStaticMirror.dll : fatal error LNK1120: 1 unresolved externals
```

It seems like `__popcnt` isn't available on Windows ARM64 according to https://developercommunity.visualstudio.com/t/-popcnt-popcnt64-intrinsics-not-provided-for-aarch/344160#T-N637429

**Comment by Azoy** [comment]
@hjyamauchi that header isn't available to the runtime unfortunately. We can just manually define our own popcount like I did here: https://github.com/apple/swift/pull/73384

**Comment by hjyamauchi** [comment]
@Azoy Alejandro, gotcha. Thanks for the fix!

**Pull request merged**
