### PR TITLE
[gardening] Fix URLs. Fix spacing. Remove unused methods. Fix headers.

### PR DESCRIPTION
**Pull request by practicalswift**

### CODE REVIEW

**Comment by practicalswift** [comment]
@swift-ci please smoke test

**Comment by practicalswift** [comment]
@swift-ci please smoke test

**Comment by palimondo** [comment]
@practicalswift What’s the secret behind the “*- swift -*” in headers for gyb files?

**Comment by palimondo** [comment]
Also, in the benchmarks, I’m about to tackle [SR-4572](https://bugs.swift.org/browse/SR-4572) - switch harness templating from jinja to gyb. I think I can fix that in the manual process with `generate_test_harness.py` just fine.

I will attempt modify the build process in order to fix [SR-4675](https://bugs.swift.org/browse/SR-4675) Report detailed build version from Benchmark drivers.

That means I should probably see about doing the GYB during a build instead of requiring manual generation of harness... then remove the .swift files where there’s a gyb from git, add them to .gitignore? 

I really need some advice if I’m on the right track with my thinking here...

**Comment by palimondo** [comment]
Ah, no. I forgot, when I tagged support for GYB in benchmarks, @lplarson wanted to be able to compile benchmark suite without external dependencies - without the GYB, so that’s why we commit both .gyb and generated .swift.

**Comment by practicalswift** [comment]
@palimondo `-*- swift -*-` is needed in the `*.swift.gyb` files to trigger Swift mode in Emacs since it is not auto-triggered by the normal `*.swift` file extension :-)

**Pull request merged**
