### PR TITLE
stdlib: Fix SR-587 – Array(count:repeatedValue:)

### PR DESCRIPTION
**Pull request by Moximillian**
#### What's in this pull request?

Fixes SR-587 by removing the specific array implementation of Array(count:repeatedValue:) and instead using the RangeReplaceableCollection -protocol's implementation.
#### Resolved bug number: ([SR-587](https://bugs.swift.org/browse/SR-587))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by gribozavr** [comment]
This implementation is likely faster than the default.  Did you benchmark it?

**Comment by Moximillian** [comment]
Sorry, no didn't benchmark it, I though this was the way to fix SR-587...

**Comment by gribozavr** [comment]
SR-587 was primarily about adding a new defaulted requirement to RangeReplaceableCollection (which we already did).

Whether concrete types should keep its customization is a different story.  If a concrete implementation is faster, then we should keep it.  About this one in particular, it looks like it would be faster than calling `append()` in a loop.

**Comment by Moximillian** [comment]
Ok, misunderstood what the bug was about then. Still learning about all this stuff :)

**Pull request closed without merging**
