### PR TITLE
SR-8876: Always build libicu on Linux

### PR DESCRIPTION
**Pull request by spevans**
- Uses version 61.1 from ICU Github unicode-org/icu repository.

- Updates mixin_linux_installation to add liblic option.

- Use -j when building libicu.

- Resolves [SR-8876](https://bugs.swift.org/browse/SR-8876).

- `build-script-impl` updates to make all tests work.

Also resolves:

[SR-5618](https://bugs.swift.org/browse/SR-5618): libicu compilation should happen in parallel respecting -j.

Note, ICU 62.1 currently causes a regression with `swift-corelibs-foundation` on Linux which will be looked at separately once this PR is merged.

### CODE REVIEW

**Comment by parkera** [comment]
This is great!

**Comment by spevans** [comment]
@swift-ci test

**Comment by milseman** [comment]
Will this change to update-checkout cause it to be cloned on Darwin as well, and if so can we make it only do so on Linux?

**Comment by spevans** [comment]
@milseman Currently it will clone on all platforms, I will fix `update-checkout` to allow specifying platforms in `utils/update_checkout/update-checkout-config.json`

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
cc @millenomi I added the change to namespace the symbols with a `_swift` suffix and the library files have `swift` appended to them using the ICU configure option `--with-library-suffix=swift`.

**Comment by millenomi** [comment]
@shahmishal who could review this?

**Comment by tkremenek** [comment]
As this is adding a new library dependency, this falls under:

https://swift.org/contributing/#adding-external-library-dependencies

I'll need to go review this for any legal concerns, but this is on me.

**Comment by spevans** [comment]
@tkremenek Have you had a chance to look at this? thanks

**Comment by spevans** [comment]
@swift-ci test

**Comment by maxdesiatov** [comment]
@tkremenek hope this can be approved soon. Thank you!

**Comment by tkremenek** [comment]
Sorry for the delay here; I should have an answer shortly.

**Comment by tkremenek** [comment]
OK, I got legal confirmation that this is OK.  There is no problem with statically linking in ICU into the Standard Library in this way; ICU's license clearly allows this.

However, we should also include the ICU license in the distribution of Swift when we do this, as the license apples to the ICU data files that will now need to be bundled with the Standard Library.  Does this PR do that?

**Comment by spevans** [comment]
Ive updated the PR to copy the ICU license into the distribution. It gets copied into `usr/share/icuswift/61.1/LICENSE`

**Comment by spevans** [comment]
Please test with the following PRs:
https://github.com/apple/swift-corelibs-foundation/pull/1744

@swift-ci please test

**Comment by shahmishal** [comment]
@spevans we are seeing this issue with recent development toolchain https://bugs.swift.org/browse/SR-9251. It might be related to this PR changes.

**Comment by millenomi** [comment]
@shahmishal Do you know if we’re distributing these binaries? If not, can we add them to the toolchain?

**Comment by millenomi** [comment]
@shahmishal I meant whether we were distributing specifically the libicu*swift binaries, which apparently we are:

```
millenomi $ find /Users/millenomi/Downloads/swift-DEVELOPMENT-SNAPSHOT-2018-11-15-a-ubuntu18.04 -name libicu\*
/Users/millenomi/Downloads/swift-DEVELOPMENT-SNAPSHOT-2018-11-15-a-ubuntu18.04/usr/lib/swift_static/linux/libicuucswift.a
/Users/millenomi/Downloads/swift-DEVELOPMENT-SNAPSHOT-2018-11-15-a-ubuntu18.04/usr/lib/swift_static/linux/libicui18nswift.a
/Users/millenomi/Downloads/swift-DEVELOPMENT-SNAPSHOT-2018-11-15-a-ubuntu18.04/usr/lib/swift_static/linux/libicudataswift.a
/Users/millenomi/Downloads/swift-DEVELOPMENT-SNAPSHOT-2018-11-15-a-ubuntu18.04/usr/lib/swift/linux/libicui18nswift.so
/Users/millenomi/Downloads/swift-DEVELOPMENT-SNAPSHOT-2018-11-15-a-ubuntu18.04/usr/lib/swift/linux/libicudataswift.so.61
/Users/millenomi/Downloads/swift-DEVELOPMENT-SNAPSHOT-2018-11-15-a-ubuntu18.04/usr/lib/swift/linux/libicuucswift.so.61.1
/Users/millenomi/Downloads/swift-DEVELOPMENT-SNAPSHOT-2018-11-15-a-ubuntu18.04/usr/lib/swift/linux/libicuucswift.so.61
/Users/millenomi/Downloads/swift-DEVELOPMENT-SNAPSHOT-2018-11-15-a-ubuntu18.04/usr/lib/swift/linux/libicudataswift.so
/Users/millenomi/Downloads/swift-DEVELOPMENT-SNAPSHOT-2018-11-15-a-ubuntu18.04/usr/lib/swift/linux/libicui18nswift.so.61.1
/Users/millenomi/Downloads/swift-DEVELOPMENT-SNAPSHOT-2018-11-15-a-ubuntu18.04/usr/lib/swift/linux/libicudataswift.so.61.1
/Users/millenomi/Downloads/swift-DEVELOPMENT-SNAPSHOT-2018-11-15-a-ubuntu18.04/usr/lib/swift/linux/libicuucswift.so
/Users/millenomi/Downloads/swift-DEVELOPMENT-SNAPSHOT-2018-11-15-a-ubuntu18.04/usr/lib/swift/linux/libicui18nswift.so.61
```

@spevans Can you investigate? Perhaps the final RPATHs are incorrect?

**Comment by spevans** [comment]
@millenomi This should have been fixed by https://github.com/apple/swift-corelibs-foundation/pull/1769 but it is not working correctly. Im taking a look

**Comment by spevans** [comment]
Looks like there are 2 `libFoundation.so` files in the tar:
```
$ find swift-DEVELOPMENT-SNAPSHOT-2018-11-15-a-ubuntu18.04/usr/lib -name libFoundation.so
swift-DEVELOPMENT-SNAPSHOT-2018-11-15-a-ubuntu18.04/usr/lib/swift/linux/x86_64/libFoundation.so
swift-DEVELOPMENT-SNAPSHOT-2018-11-15-a-ubuntu18.04/usr/lib/swift/linux/libFoundation.so
```
And the one in the `x86_64` directory is being loaded:
```
$ ldd hello|grep libFoundation
	libFoundation.so => /home/spse/swift-DEVELOPMENT-SNAPSHOT-2018-11-15-a-ubuntu18.04/usr/lib/swift/linux/x86_64/libFoundation.so (0x00007f07ae29d000)
```
so this is setting the `$ORIGIN` to the `x86_64` subdirectory and then failing to find `libicu*`
```
$ ./hello
./hello: error while loading shared libraries: libicuucswift.so.61: cannot open shared object file: No such file or directory
```

Deleting this extra `libFoundation.so` makes it fall back to the one in `usr/lib/swift/linux` and everything works:

```
$ rm /home/spse/swift-DEVELOPMENT-SNAPSHOT-2018-11-15-a-ubuntu18.04/usr/lib/swift/linux/x86_64/libFoundation.so
ubuntu1804:~ spse$ ldd hello|grep libFoundation
	libFoundation.so => /home/spse/swift-DEVELOPMENT-SNAPSHOT-2018-11-15-a-ubuntu18.04/usr/lib/swift/linux/libFoundation.so (0x00007f5986fcc000)
ubuntu1804:~ spse$ ldd hello|grep libicu.*61
	libicuucswift.so.61 => /home/spse/swift-DEVELOPMENT-SNAPSHOT-2018-11-15-a-ubuntu18.04/usr/lib/swift/linux/libicuucswift.so.61 (0x00007f393c962000)
	libicui18nswift.so.61 => /home/spse/swift-DEVELOPMENT-SNAPSHOT-2018-11-15-a-ubuntu18.04/usr/lib/swift/linux/libicui18nswift.so.61 (0x00007f393c46c000)
	libicudataswift.so.61 => /home/spse/swift-DEVELOPMENT-SNAPSHOT-2018-11-15-a-ubuntu18.04/usr/lib/swift/linux/libicudataswift.so.61 (0x00007f393a0f7000)
ubuntu1804:~ spse$ ./hello
Hello
```

I'll see if I can set see what is adding the `libFoundation.so` into the `x86_64` directory  and remove it as no other `.so` libraries are stored in there. However I still cant work out why the `x86_64` directory is preferred over its parent looking at the `RUNPATH`s of all the other libraries.

**Comment by spevans** [comment]
Hopefully this second fix to solve the issue: https://github.com/apple/swift-corelibs-foundation/pull/1776

**Pull request merged**
