### PR TITLE
Revert "Try disabling CSV benchmarks to see if that unsticks PR benchmark runs"

### PR DESCRIPTION
**Pull request by milseman**
Reverts apple/swift#14220

Trying to determine why this is stalling benchmarks. Might be poor choice of loop iteration scales, as it worked fine for smoke benchmark but not full.

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please smoke benchmark

^^^ Expecting this to work just fine

**Comment by jrose-apple** [comment]
No no no, this is the one that's causing hangs. Please work on this locally.

**Comment by milseman** [comment]
It doesn't hang locally for me, that's the thing. What is different about the bot's configuration?

**Comment by airspeedswift** [comment]
As another data point, it _does_ hang locally on my machine.

**Comment by jrose-apple** [comment]
Optimized vs. non-optimized stdlib?

**Comment by lancep** [comment]
The hang is resolved by https://github.com/apple/swift/pull/14314#pullrequestreview-93139346

**Comment by lancep** [comment]
@swift-ci please smoke benchmark

**Comment by lancep** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
