### PR TITLE
Fix propagation of SWIFT_ENABLE_REFLECTION from CMake into lit.cfg and re-enable 'REQUIRES: reflection' tests

### PR DESCRIPTION
**Pull request by kubamracek**
https://bugs.swift.org/browse/SR-15661

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test Windows platform

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Comment by kubamracek** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@kubamracek - the windows builds need to be fixed by @eeckstein, there was some breakage that was introduced by changes to the libswift work.

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test macOS platform

**Comment by benrimmington** [comment]
I've added a comment to SR-15661 (the _validation_ tests are still unsupported).

**Pull request merged**
