### PR TITLE
Just use a generic subscript's generic context in its accessors (NFC)

### PR DESCRIPTION
**Pull request by rjmccall**
The main purpose of doing this is to eliminate the need for some special cases for materializeForSet (and read and modify) in the requirements-gathering code, but it should also be a small performance improvement for code that's heavy in generic subscripts.

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Review by slavapestov — APPROVED** [review]

**Comment by rjmccall** [comment]
@swift-ci Please test Linux.

**Comment by shahmishal** [comment]
@swift-ci Please clean test Linux

**Comment by shahmishal** [comment]
```
Failing Tests (4):
    lldb :: tools/lldb-mi/exec/exec-next-instruction.test
    lldb :: tools/lldb-mi/exec/exec-next.test
    lldb :: tools/lldb-mi/exec/exec-step-instruction.test
    lldb :: tools/lldb-mi/exec/exec-step.test
```

@fredriss @dcci Do you know why it's failing on this PR?

**Comment by fredriss** [comment]
@dcci Why do we even run the MI tests on a Swift PR? This is wrong.

**Comment by dcci** [comment]
Looks like one of the unwanted side-effects of the `master-next` merge is that everything is a lit test, so we run all the tests instead of honoring `-swift-test-only`. 
I think the correct way of fixing this is implementing support for `-swift-test-only` in lit.

**Comment by fredriss** [comment]
@dcci OK, in the meantime, I think we should XFAIL all the pexpect based lldb-mi tests on Linux at least.

**Comment by dcci** [comment]
The unwanted part is not that everything is a `lit` test, that's expected. The unwanted part is that we don't honor the flag.

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Pull request merged**
