### PR TITLE
Bump SWIFT_VERSION to 4.2.4

### PR DESCRIPTION
**Pull request by kevints**

### CODE REVIEW

**Comment by kevints** [comment]
@swift-ci test 4.2

**Review by weissi — APPROVED** [review]
thanks!

**Comment by kevints** [comment]
@swift-ci please test

**Comment by kevints** [comment]
@swift-ci clean test

**Comment by shahmishal** [comment]
@swift-ci test 4.2 macOS

**Review by weissi — APPROVED** [review]
Ok, this passed everything (apart from the non-4.2 macOS which is expected to always fail for 4.2 branch)

**Pull request merged**
