### PR TITLE
DiagnosticEngine: require clients to explicitly specify source locations when emitting diagnostics. NFC

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@nkcsgexi If it's acceptable to not provide source location, it seems like adding `SourceLoc()` to every call is worse than just handling it in the `diagnose`?

**Comment by nkcsgexi** [comment]
This change is requested by @jrose-apple, and I tend to agree with him that sourceloc-less diagnostics are the less common case. So if we wanna emit them, we should be specific at the call sites.

**Comment by xedin** [comment]
Sure, but I think you'd want to re-phrase commit message a bit, because these changes don't really disallow diagnostics without location, but rather require location to be always specified even if its empty (non-existent).

**Comment by nkcsgexi** [comment]
@xedin ah, sure. I've updated the PR title.

**Review by jrose-apple — APPROVED** [review]

**Comment by jrose-apple** [comment]
Thanks!

**Review by xedin — APPROVED** [review]
Thanks!

**Comment by xedin** [comment]
Another approach might be to delete existing one and rename to `diagnoseWithoutLoc` so it's explicit that location is not specified, which avoids `SourceLoc()` everywhere...

**Comment by jrose-apple** [comment]
I'm okay with that too, but I'm not sure it's really any better than `diagnose(SourceLoc()`.

**Comment by xedin** [comment]
Either way works for me! It seems that if we really want to distinguish the case without loc it’s best done with special API endpoint, and the rest diagnostic methods having an assert to make sure that loc is really there...

**Pull request merged**
