### PR TITLE
[5.1] [ParseableInterfaces] Stop explicitly optimizing cached modules

### PR DESCRIPTION
**Pull request by harlanhaskins**
Cherry-pick of #23725 onto 5.1

### CODE REVIEW

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test and merge

**Review by nathawes — APPROVED** [review]

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test

**Comment by harlanhaskins** [comment]
https://github.com/apple/swift-lldb/pull/1465
@swift-ci please smoke test

**Comment by harlanhaskins** [comment]
apple/swift-lldb#1465
@swift-ci please smoke test Linux

**Comment by harlanhaskins** [comment]
apple/swift-lldb#1465
@swift-ci please smoke test Linux

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test

**Comment by harlanhaskins** [comment]
Oh, wait, I need to full test.
@swift-ci please test

**Comment by harlanhaskins** [comment]
Last CI hiccup, hopefully.

@swift-ci please test macOS

**Comment by harlanhaskins** [comment]
Last CI hiccup, hopefully.

@swift-ci please test macOS

**Pull request merged**
