### PR TITLE
[cmake] Add support for compiling all swift libraries with guaranteed…

### PR DESCRIPTION
**Pull request by gottesmm**
… normal arguments.

I was using --extra-swift-args before, but lets do this for real now.

rdar://34222540

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@Rostepher Do you mind if I just stick this here?

**Comment by gottesmm** [comment]
[I have paged out if there is a more idiomatic place to put this =---(].

**Comment by Rostepher** [comment]
LGTM!

**Review by Rostepher — APPROVED** [review]

**Pull request merged**
