### PR TITLE
[SourceKit] Fix majority of 7.3b5 “Quick Help” crashes

### PR DESCRIPTION
**Pull request by johnno1962**
#### What's in this pull request?

Xcode 7.3beta5 and current swift-2.2-branch snapshot exhibit SourceKit crashes when a user selects some fairly common variations of text for “Quick Help” in the Xcode editor. For example, in the following code:

```
// from Alamofire

public enum Result<Value, Error: ErrorType> {
    case Success(Value)
    case Failure(Error)

    /// Returns `true` if the result is a success, `false` otherwise.
    public var isSuccess: Bool {
        switch self {
        case .Success:
            return true
        case .Failure:
            return false
        }
    }

    ...
}
```

selecting the .Success or .Failure inside the isSuccess method will crash SourceKit due to an assertion failure at line 667 in ASTPrinter.cpp. Another example is the “.bytes” method of NSData instances.

This change has the code fall back to the printer for the non-nominal type which avoids the assertion failure and restores “Quick Help” functionality in more than 90% of failing cases.

In order to test this a modified version of the https://github.com/johnno1962/siteify program was used to check all possible cursorinfo requests for text that had a related USR in all sources of the https://github.com/artsy/eidolon OSS project which contains a rich cross section of Swift code. Without this patch crashes were innuerable while with this patch there remain only 11 places in the 36,000 line codebase that can generate a SourceKit crash for a cursorinfo request with the following stack trace which has not been pursued:

Thread 2 Crashed:: Dispatch queue: sourcekit.swift.ConsumeAST
0   com.apple.SourceKitService.     0x000000010b900924 swift::TypeBase::getRecursiveProperties() const + 20 (Types.h:367)
1   com.apple.SourceKitService.     0x000000010b5f609b swift::SubstitutedType::get(swift::Type, swift::Type, swift::ASTContext const&) + 43 (ASTContext.cpp:3259)
2   com.apple.SourceKitService.     0x000000010b8f7a7f swift::Type::subst(swift::ModuleDecl_, llvm::DenseMap<swift::TypeBase_, swift::Type, llvm::DenseMapInfoswift::TypeBase*, llvm::detail::DenseMapPair<swift::TypeBase*, swift::Type> >&, swift::OptionSet<swift::SubstFlags, unsigned int>) const::$_6::operator()(swift::Type) const + 783 (Type.cpp:2392)

A toolchain was also built and cases of text previously crashing SourceKit were selected from inside Xcode 7.3b5 to verify that “Quick Help” now worked and that the information displayed was correct.
#### Resolved bug number:

rdar://25034667

A copy of the SourceKit XPC binary built with this fix is attached to the rdar for further testing.

### CODE REVIEW

**Comment by tkremenek** [comment]
@swift-ci Please test

**Comment by tkremenek** [comment]
@akyrtzi Please review

**Comment by tkremenek** [comment]
@johnno1962 This change should have a test case that show the crash is eliminated.

**Comment by tkremenek** [comment]
@johnno1962 Also, has this change already gone into the `master` branch?  That's where bug fixes should land first.  We then consider pulling them into release branches.

**Comment by johnno1962** [comment]
Hi @tkremenek, this fix doesn’t work on the master branch as the code has moved on and I’ve not looked at it. I’ll look at adding a simple test for you.

**Comment by tkremenek** [comment]
@johnno1962 Thanks.  `swift-2.2-branch` will not be merged into `master`, so any fixes only there will not propagate to future releases.  Thanks for working on a test case.  This is pedantic, but please make sure the test case fails without your change.

This is late to take for Swift 2.2, but definitely want to consider it.  I'll also want one of the SourceKit folks to review it.

**Comment by johnno1962** [comment]
@tkremenek, I understand about master being master ;) I’ve been focused on the 2.2 branch working up to now and there is more test data. I’ll submit the tests to the master branch and look to take a look if there is still a problem. I see the code in this area has been re-worked since 2.2. It’s a reasonably conservative change as the alternative is the hard assertion failure. The tests will take a "couple of hours".

**Comment by johnno1962** [comment]
@tkremenek, I’ve submitted a test case for the common failure mode if you want to re-test.

**Comment by tkremenek** [comment]
@swift-ci Please test

**Comment by akyrtzi** [comment]
The test needs a bit of clean-up and commented with details here:
https://github.com/johnno1962a/swift/commit/adeafef88dc9bf327c0884da53127c946d558351

As I mentioned there, the test doesn't crash in master but we should get it anyway to increase test coverage, with a new pull request against master for just the test. The actual fix for swift-2.2 looks good to me.

**Comment by johnno1962** [comment]
@akyrtzi, Test updated after your feedback for re-test.

**Comment by johnno1962** [comment]
@akyrtzi, zut! Adding the comment at the last minute changed the line offsets. Have pushed new versions of the test here and in master. Apologies for all the iterations!

**Comment by tkremenek** [comment]
@swift-ci Please test

**Pull request merged**
