### PR TITLE
Remove extensions on ImplicitlyUnwrappedOptional from the stdlib.

### PR DESCRIPTION
**Pull request by rudkx**
Extensions on ImplicitlyUnwrappedOptional are not actually accessible
because we force the optional (and thus can only access things on the
type it is wrapping).

Remove these from the stdlib in order to pave the way toward fully
implementing SE-0054.

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
Actually, look at this:

```
func f(x: Int!) -> Any {
  return x
}

protocol P { func foo() }

extension ImplicitlyUnwrappedOptional : P { func foo() { print("Hello") } }

(f(x: 3) as! P).foo()
```

The problem is the SILGen for f(),

```
%3 = init_existential_addr %0 : $*Any, $ImplicitlyUnwrappedOptional<Int>
```

It appears that in this case the IUO does not 'decay' into an Optional as you expect with SE-0054. Perhaps if this corner case is fixed, you'll be able to rip out these extensions for real.

**Comment by slavapestov** [comment]
Basically we need to ensure Sema never produces AST nodes that construct RValues of IUO type.

**Comment by slavapestov** [comment]
And even this works, without the Any:

```
func f(x: Int!) -> P {
  return x
}

protocol P { func foo() }

extension ImplicitlyUnwrappedOptional : P { func foo() { print("Hello") } }

f(x: 3).foo()
```

So I think the first step is to ensure that getOpenedTypeOfReference() always produces an optional when you reference an IUO parameter or property.

**Review by moiseev — APPROVED** [review]

**Pull request closed without merging**
