### PR TITLE
Sema: Move the fixit for adding missing enum cases to a separate note instead of attaching to the exhaustive error itself.

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Review by CodaFi — APPROVED** [review]
Thanks!  #9180 should get any remaining problems with IDE integration

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
⛵️

**Comment by nkcsgexi** [comment]
@CodaFi these commits should be squashed

**Comment by CodaFi** [comment]
Oh, my bad.  I must have changed that setting since my last merge.

**Pull request merged**
