### PR TITLE
[Diagnostics] Skip overloaded locations where all solutions have the same type

### PR DESCRIPTION
**Pull request by xedin**
If there are multiple overloads, let's skip locations that produce
the same type across all of the solutions, such location is most
likely a consequence of ambiguity and not its source.

Resolves: rdar://109245375

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Review by hborla — APPROVED** [review]
Nice!

**Comment by xedin** [comment]
@swift-ci please smoke test

**Pull request merged**
