### PR TITLE
Pack expansion closures, part 6

### LINKED ISSUE #66917: Compiler Crash when using a Type Parameter Pack in a closure
**Description**
I am unable to compile a type parameter pack in a function if I use the the types in a closure.

**Steps to reproduce**
Try compiling the below function in `repl` or with `swift build`

```swift
public func values<each T>() -> (repeat (each T)?) {
  (repeat { () -> (each T)? in
    nil
  }())
}
```

**Expected behavior**
A warning, error, or a successful build.

**Environment**
- Swift compiler version info 
swift-driver version: 1.82.2 Apple Swift version 5.9 (swiftlang-5.9.0.114.10 clang-1500.0.29.1)
- Xcode version info: Xcode 15.0 Build version 15A5161b
- Deployment target: macOS 13.4 (22F66)
- 
```
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  lldb                     0x0000000104f137c0 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  lldb                     0x0000000104f12d1c llvm::sys::RunSignalHandlers() + 112
2  lldb                     0x0000000104f13e44 SignalHandler(int) + 304
3  libsystem_platform.dylib 0x00000001a214ea24 _sigtramp + 56
4  LLDB                     0x00000001188f8f68 llvm::Optional<swift::Type> llvm::function_ref<llvm::Optional<swift::Type> (swift::TypeBase*)>::callback_fn<swift::rewriting::RequirementMachine::getReducedType(swift::Type, swift::ArrayRefView<swift::Type, swift::GenericTypeParamType*, swift::GenericTypeParamType* swift::staticCastHelper<swift::GenericTypeParamType>(swift::Type const&), true>) const::$_1>(long, swift::TypeBase*) + 868
5  LLDB                     0x000000011895a254 swift::Type::transformWithPosition(swift::TypePosition, llvm::function_ref<llvm::Optional<swift::Type> (swift::TypeBase*, swift::TypePosition)>) const + 92
6  LLDB                     0x000000011895bffc swift::Type::transformRec(llvm::function_ref<llvm::Optional<swift::Type> (swift::TypeBase*)>) const + 36
7  LLDB                     0x00000001188f7144 swift::rewriting::RequirementMachine::getReducedType(swift::Type, swift::ArrayRefView<swift::Type, swift::GenericTypeParamType*, swift::GenericTypeParamType* swift::staticCastHelper<swift::GenericTypeParamType>(swift::Type const&), true>) const + 56
8  LLDB                     0x0000000118853754 swift::GenericSignatureImpl::getReducedType(swift::Type) const + 136
9  LLDB                     0x00000001189503a0 swift::TypeBase::getReducedType(swift::GenericSignature) + 32
10 LLDB                     0x0000000117f8ec64 swift::Lowering::AbstractionPattern::unsafeGetSubstFieldType(swift::ValueDecl*, swift::CanType, swift::SubstitutionMap) const + 244
11 LLDB                     0x000000011805c9fc (anonymous namespace)::LowerType::visitAnyEnumType(swift::CanType, swift::Lowering::AbstractionPattern, swift::EnumDecl*, swift::Lowering::IsTypeExpansionSensitive_t) + 636
12 LLDB                     0x000000011805a114 swift::CanTypeVisitor<(anonymous namespace)::LowerType, swift::Lowering::TypeLowering*, swift::Lowering::AbstractionPattern, swift::Lowering::IsTypeExpansionSensitive_t>::visit(swift::CanType, swift::Lowering::AbstractionPattern, swift::Lowering::IsTypeExpansionSensitive_t) + 232
13 LLDB                     0x00000001180536b4 (anonymous namespace)::TypeClassifierBase<(anonymous namespace)::LowerType, swift::Lowering::TypeLowering*>::visit(swift::CanType, swift::Lowering::AbstractionPattern, swift::Lowering::IsTypeExpansionSensitive_t) + 132
14 LLDB                     0x000000011805350c swift::Lowering::TypeConverter::getTypeLowering(swift::Lowering::AbstractionPattern, swift::Type, swift::TypeExpansionContext) + 732
15 LLDB                     0x0000000117fcb3ac (anonymous namespace)::DestructureResults::destructure(swift::Lowering::AbstractionPattern, swift::CanType) + 116
16 LLDB                     0x0000000117fca434 getSILFunctionType(swift::Lowering::TypeConverter&, swift::TypeExpansionContext, swift::Lowering::AbstractionPattern, swift::CanTypeWrapper<swift::AnyFunctionType>, swift::SILExtInfoBuilder, (anonymous namespace)::Conventions const&, swift::ForeignInfo const&, llvm::Optional<swift::SILDeclRef>, llvm::Optional<swift::SILDeclRef>, llvm::Optional<swift::SubstitutionMap>, swift::ProtocolConformanceRef) + 3168
17 LLDB                     0x0000000117fc3988 getNativeSILFunctionType(swift::Lowering::TypeConverter&, swift::TypeExpansionContext, swift::Lowering::AbstractionPattern, swift::CanTypeWrapper<swift::AnyFunctionType>, swift::SILExtInfoBuilder, llvm::Optional<swift::SILDeclRef>, llvm::Optional<swift::SILDeclRef>, llvm::Optional<swift::SubstitutionMap>, swift::ProtocolConformanceRef) + 1164
18 LLDB                     0x0000000117fc5bcc getUncachedSILFunctionTypeForConstant(swift::Lowering::TypeConverter&, swift::TypeExpansionContext, swift::SILDeclRef, swift::Lowering::TypeConverter::LoweredFormalTypes) + 952
19 LLDB                     0x0000000117fc6330 swift::Lowering::TypeConverter::getConstantInfo(swift::TypeExpansionContext, swift::SILDeclRef) + 192
20 LLDB                     0x0000000117fbe984 swift::SILFunctionBuilder::getOrCreateFunction(swift::SILLocation, swift::SILDeclRef, swift::ForDefinition_t, llvm::function_ref<swift::SILFunction* (swift::SILLocation, swift::SILDeclRef)>, swift::ProfileCounter) + 132
21 LLDB                     0x0000000117ec0068 swift::Lowering::SILGenModule::getFunction(swift::SILDeclRef, swift::ForDefinition_t) + 332
22 LLDB                     0x0000000117ec3150 swift::Lowering::SILGenModule::emitClosure(swift::AbstractClosureExpr*) + 92
23 LLDB                     0x0000000117ede474 (anonymous namespace)::SILGenApply::visitAbstractClosureExpr(swift::AbstractClosureExpr*) + 132
24 LLDB                     0x0000000117ecc8ac swift::Lowering::SILGenFunction::emitApplyExpr(swift::ApplyExpr*, swift::Lowering::SGFContext) + 648
25 LLDB                     0x0000000117f0c950 swift::Lowering::SILGenFunction::emitExprInto(swift::Expr*, swift::Lowering::Initialization*, llvm::Optional<swift::SILLocation>) + 204
26 LLDB                     0x0000000117f21a88 void llvm::function_ref<void (swift::Lowering::Initialization*)>::callback_fn<(anonymous namespace)::RValueEmitter::visitPackExpansionExpr(swift::PackExpansionExpr*, swift::Lowering::SGFContext)::$_7::operator()(swift::SILValue, swift::SILValue, swift::SILValue) const::'lambda'(swift::Lowering::Initialization*)>(long, swift::Lowering::Initialization*) + 48
27 LLDB                     0x0000000117f455b8 swift::Lowering::InPlacePackExpansionInitialization::performPackExpansionInitialization(swift::Lowering::SILGenFunction&, swift::SILLocation, swift::SILValue, llvm::function_ref<void (swift::Lowering::Initialization*)>) + 340
28 LLDB                     0x0000000117f21a40 void llvm::function_ref<void (swift::SILValue, swift::SILValue, swift::SILValue)>::callback_fn<(anonymous namespace)::RValueEmitter::visitPackExpansionExpr(swift::PackExpansionExpr*, swift::Lowering::SGFContext)::$_7>(long, swift::SILValue, swift::SILValue, swift::SILValue) + 108
29 LLDB                     0x0000000117f44c3c swift::Lowering::SILGenFunction::emitDynamicPackLoop(swift::SILLocation, swift::CanTypeWrapper<swift::PackType>, unsigned int, swift::SILValue, swift::SILValue, swift::GenericEnvironment*, bool, llvm::function_ref<void (swift::SILValue, swift::SILValue, swift::SILValue)>) + 1136
30 LLDB                     0x0000000117f452f8 swift::Lowering::SILGenFunction::emitDynamicPackLoop(swift::SILLocation, swift::CanTypeWrapper<swift::PackType>, unsigned int, swift::GenericEnvironment*, llvm::function_ref<void (swift::SILValue, swift::SILValue, swift::SILValue)>) + 40
31 LLDB                     0x0000000117f19e5c (anonymous namespace)::RValueEmitter::visitPackExpansionExpr(swift::PackExpansionExpr*, swift::Lowering::SGFContext) + 176
32 LLDB                     0x0000000117f0c950 swift::Lowering::SILGenFunction::emitExprInto(swift::Expr*, swift::Lowering::Initialization*, llvm::Optional<swift::SILLocation>) + 204
33 LLDB                     0x0000000117f19788 (anonymous namespace)::RValueEmitter::visitTupleExpr(swift::TupleExpr*, swift::Lowering::SGFContext) + 304
34 LLDB                     0x0000000117f0c950 swift::Lowering::SILGenFunction::emitExprInto(swift::Expr*, swift::Lowering::Initialization*, llvm::Optional<swift::SILLocation>) + 204
35 LLDB                     0x0000000117f6d244 swift::Lowering::SILGenFunction::emitReturnExpr(swift::SILLocation, swift::Expr*) + 740
36 LLDB                     0x0000000117f6b6b4 swift::ASTVisitor<(anonymous namespace)::StmtEmitter, void, void, void, void, void, void>::visit(swift::Stmt*) + 6416
37 LLDB                     0x0000000117f6ae7c swift::ASTVisitor<(anonymous namespace)::StmtEmitter, void, void, void, void, void, void>::visit(swift::Stmt*) + 4312
38 LLDB                     0x0000000117f69d98 swift::Lowering::SILGenFunction::emitStmt(swift::Stmt*) + 24
39 LLDB                     0x0000000117f28fb0 swift::Lowering::SILGenFunction::emitFunction(swift::FuncDecl*) + 348
40 LLDB                     0x0000000117ec1d80 swift::Lowering::SILGenModule::emitFunctionDefinition(swift::SILDeclRef, swift::SILFunction*) + 5728
41 LLDB                     0x0000000117ec2dc4 emitOrDelayFunction(swift::Lowering::SILGenModule&, swift::SILDeclRef) + 172
42 LLDB                     0x0000000117ec070c swift::Lowering::SILGenModule::emitFunction(swift::FuncDecl*) + 156
43 LLDB                     0x0000000117ec4e50 swift::ASTLoweringRequest::evaluate(swift::Evaluator&, swift::ASTLoweringDescriptor) const + 1932
44 LLDB                     0x0000000117f69878 std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>> swift::SimpleRequest<swift::ASTLoweringRequest, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>> (swift::ASTLoweringDescriptor), (swift::RequestFlags)9>::callDerived<0ul>(swift::Evaluator&, std::__1::integer_sequence<unsigned long, 0ul>) const + 200
45 LLDB                     0x0000000117cb3188 llvm::Expected<swift::ASTLoweringRequest::OutputType> swift::Evaluator::getResultUncached<swift::ASTLoweringRequest>(swift::ASTLoweringRequest const&) + 240
46 LLDB                     0x0000000117ec5a38 swift::performASTLowering(swift::FileUnit&, swift::Lowering::TypeConverter&, swift::SILOptions const&, swift::IRGenOptions const*) + 88
47 LLDB                     0x000000011701efa8 lldb_private::SwiftExpressionParser::Parse(lldb_private::DiagnosticManager&, unsigned int, unsigned int) + 13868
48 LLDB                     0x000000011702ffec lldb_private::SwiftUserExpression::GetTextAndSetExpressionParser(lldb_private::DiagnosticManager&, std::__1::unique_ptr<lldb_private::SwiftExpressionSourceCode, std::__1::default_delete<lldb_private::SwiftExpressionSourceCode>>&, lldb_private::ExecutionContext&, lldb_private::ExecutionContextScope*) + 5248
49 LLDB                     0x00000001170309d8 lldb_private::SwiftUserExpression::Parse(lldb_private::DiagnosticManager&, lldb_private::ExecutionContext&, lldb_private::ExecutionPolicy, bool, bool) + 1208
50 LLDB                     0x0000000116e63b08 lldb_private::UserExpression::Evaluate(lldb_private::ExecutionContext&, lldb_private::EvaluateExpressionOptions const&, llvm::StringRef, llvm::StringRef, std::__1::shared_ptr<lldb_private::ValueObject>&, lldb_private::Status&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, lldb_private::ValueObject*) + 2228
51 LLDB                     0x0000000116e61b38 lldb_private::REPL::IOHandlerInputComplete(lldb_private::IOHandler&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&) + 2308
52 LLDB                     0x0000000116dd009c lldb_private::IOHandlerEditline::Run() + 284
53 LLDB                     0x0000000116db52b0 lldb_private::Debugger::RunIOHandlers() + 140
54 LLDB                     0x0000000116dba4a0 std::__1::__function::__func<lldb_private::Debugger::StartIOHandlerThread()::$_4, std::__1::allocator<lldb_private::Debugger::StartIOHandlerThread()::$_4>, void* ()>::operator()() + 28
55 LLDB                     0x0000000116e6bb44 lldb_private::HostNativeThreadBase::ThreadCreateTrampoline(void*) + 108
56 LLDB                     0x000000011ac518f0 lldb_private::HostThreadMacOSX::ThreadCreateTrampoline(void*) + 32
57 libsystem_pthread.dylib  0x00000001a211ffa8 _pthread_start + 148
58 libsystem_pthread.dylib  0x00000001a211ada0 thread_start + 8
[1]    44363 segmentation fault  swift repl
```

### LINKED ISSUE #69947: Bad pointer dereference crash when using parameter pack
```swift
class Thing<T> {
  var value: T
  init(_ value: T) { self.value = value }

  func combineThings<each U>(head: Thing<T>, tail: repeat Thing<each U>) { 
    repeat (each tail).doSomething(each tail) { _ in }
  }

  func doSomething(_ value: AnyObject, closure: @escaping (T) -> Void) {}
}
```

This crashes on latest nightly (`Swift version 5.11-dev (LLVM 82306b901067e3c, Swift cabb5e109fa373f)`) with:

> Archetype τ_2_0 not allowed in this context
Archetype generic signature: <τ_0_0, each τ_1_0, τ_2_0>
Context generic signature: <T, each U>

and further down it says

> Program crashed: Bad pointer dereference at 0x0000000000000000

Similar crash on 5.9 too.

### PR DESCRIPTION
**Pull request by slavapestov**
Follow-up to https://github.com/apple/swift/pull/73685.

This implements support for autoclosures, closures and local functions nested within a pack iteration for loop, in what I believe is full generality.

Some combinations of closures also work with pack expansion expressions, but not all; this part needs more work in the solver.

General idea:
- Capture analysis records references to ElementArchetypeTypes that are defined outside of the scope of the current function.
- SIL type lowering extends the generic signature of the closure or local function with new generic parameters corresponding to the captured local archetypes.
- Interface types of AST declarations in local context may contain element archetypes; SIL type lowering maps them to interface types in the extended signature.
- SILGen lowers the code using the old generic signature's primary archetypes and local archetypes, which are out of scope, as before. A post-pass rewrites SIL instructions, replacing the old primary archetypes and local archetypes with primary archetypes for the new signature.
- SILGen rewrites substitution maps when calling a closure, forwarding substitutions for any local archetypes it captures.

When a closure doesn't capture any local archetypes, the extended generic signature is the same as the original generic signature, and we skip the substitution map transform, etc.

Fixes https://github.com/apple/swift/issues/66917.
Fixes https://github.com/apple/swift/issues/69947.
Fixes rdar://113505724.
Fixes rdar://122293832.
Fixes rdar://124329076.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by simanerush** [comment]
Looks like this also resolves #73551 🙂

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Pull request merged**
