### PR TITLE
[DNM: ASTScope lookup] Fix backwards PatternBindingEntry::getSourceRange

### PR DESCRIPTION
**Pull request by davidungar**
`PatternBindingEntry::getSourceRange` uses the end of the initializer for the end of the range. But, if the initializer is a property wrapper, the initializer comes before the start of the `PatternBindingEntry.` Prevent the  computation from using such an initializer. 

At present, this change isn't quite ready for prime time because uses a check that bypasses the `SourceManager::isBeforeInBuffer` abstraction, since I don't see how to get the `SourceManager` into play where it is needed.

In addition to a fix being needed for ASTScope lookup, this fix will be needed to address part of rdar://53637494

### CODE REVIEW

**Comment by davidungar** [comment]
@swift-ci please smoke test os x platform

**Comment by davidungar** [comment]
@slavapestov @DougGregor Here is some functionality that would be very useful for ASTScope lookup. Without it, I'll have to intercept calls to `getSourceRange` to correct the result for `PattternEntry`s. The issue is that the fix here bypasses `isBeforeInBuffer` because the `SourceManager` seems to be unavailable. Can you suggest some sort of fix? Thanks

**Comment by slavapestov** [comment]
Would it be better if property wrappers synthesized the pattern to have the correct source location?

**Comment by davidungar** [comment]
@slavapestov @DougGregor I think I found a way to do this that works without violating encapsulation. It uses the presence of the equals sign to detect a "following" initializer instead of a property wrapper one.

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Comment by davidungar** [comment]
Don't review yet--needs more thought. Tx.

**Pull request closed without merging**
