### PR TITLE
Sema/SIL: NSError has no special powers without ObjC interop.

### PR DESCRIPTION
**Pull request by jckarter**
In particular, it doesn't "toll-free bridge" to the Error existential on non-ObjC-interop platforms, and we would miscompile as if it could. This should fix SR-585.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test Linux

**Comment by jckarter** [comment]
@swift-ci Please test Linux

**Comment by jckarter** [comment]
@swift-ci Please test Linux

**Comment by jckarter** [comment]
@swift-ci Please test Linux

**Comment by jckarter** [comment]
@swift-ci Please test Linux

**Comment by jckarter** [comment]
@swift-ci Please test Linux

**Comment by jckarter** [comment]
@swift-ci Please test Linux

**Comment by jckarter** [comment]
@swift-ci Please test Linux

**Comment by lupinglade** [comment]
Thank you! This is a huge fix in terms of usability of Swift on Linux!

**Comment by jckarter** [comment]
@lupinglade I have to ask, why do you need NSError on Linux in the first place?

**Comment by jckarter** [comment]
@swift-ci Please test OS X

**Comment by lupinglade** [comment]
@jckarter We're catching NSErrors thrown by corelibs-foundation. I think this is a common use case.

**Comment by gwynne** [comment]
I can confirm this fixed the crash for me. As for fixing Foundation not to throw NSError on Linux, I may be able to find time this weekend to do that pull request myself... I hope so anyhow.

**Comment by jckarter** [comment]
@swift-ci Please test OS X

**Comment by jckarter** [comment]
@swift-ci Please test OS X

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test Linux

**Comment by jckarter** [comment]
@shahmishal Looks like the Linux builders might be hitting resource limits on the validation test suite:

```
[ RUN      ] ThreadSafeCachingTests.ReturnGetExpression
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
```

**Comment by lupinglade** [comment]
Can we get this into the swift 3.1 branch?

**Pull request merged**
