### PR TITLE
Only define ValueStorageMap::dump in DEBUG.

### PR DESCRIPTION
**Pull request by nate-chandler**
NFC

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
Running benchmarks just because that's a place where the build failure can be seen currently.  ( https://ci.swift.org/job/swift-PR-macos-perf/91/consoleText )

**Comment by nate-chandler** [comment]
Benchmark still fails with 

/Users/ec2-user/jenkins/workspace/swift-PR-macos-perf/swift/lib/SILOptimizer/Mandatory/AddressLowering.cpp:369:23: error: out-of-line definition of 'dump' does not match any declaration in 'swift::ValueStorageMap'

but it is showing the old line number, indicating maybe that that is from attempting to build ndebug without this patch.

**Review by atrick — APPROVED** [review]

**Comment by atrick** [comment]
Merged to unblock CI

**Pull request merged**
