### PR TITLE
build: cherry-picks from main for dependencies and Windows build

### PR DESCRIPTION
**Pull request by compnerd**
Update to using build.ps1 on release/5.10 as well to get the complete toolchain build on Windows. Switch to using update-checkout for checking out the following dependencies:
- CURL
- ICU
- libxml2
- zlib

Update the CURL dependency to 8.4.0 to match 5.9.1.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
This appears to be failing due to the inability to run `swift`.

`$s013CompilerSwiftA21PluginMessageHandling0c6ToHostD0O17expandMacroResultyACSSSg_SayAA0cD0O10DiagnosticVGtcACmFWC` is missing in `_InternalSwiftScan.dll`
`$s013CompilerSwiftA21PluginMessageHandling0cD0O10DiagnosticV5FixItV6ChangeV5rangeAE13PositionRangeVvg` is missing in `swift-frontend.exe`.

CC: @bnbarham @rintaro @DougGregor 

I'm not sure what is going on here. We previously had this problem on main due to the linking between swift-syntax and LSP was done dynamically and we would hit the namespacing.

**Comment by compnerd** [comment]
@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
Can you also verify this does not cause any issues for swift-corelibs-foundation for release/5.10 branch?

**Comment by compnerd** [comment]
https://github.com/apple/swift-corelibs-foundation/pull/4840

**Comment by compnerd** [comment]
@shahmishal https://ci.swift.org/job/swift-corelibs-foundation-PR-Linux/307/ - seems to be good!

**Review by shahmishal — APPROVED** [review]

**Pull request merged**
