### PR TITLE
Reuse `_ContiguousArrayStorage<AnyObject>` metadata for any class or objc generic type

### PR DESCRIPTION
**Pull request by aschwaighofer**
Reduces the number of _ContiguousArrayStorage metadata.

In order to support constant time bridging we do need to set the correct
metadata when we bridge to Objective-C. This is so that the type check
succeeds when bridging back from Objective-C to reuse the storage
instance rather than bridging the elements.

To support dynamically setting the `_ContiguousArrayStorage` element
type i needed to add support for optimizing `alloc_ref_dynamic`
throughout the optimizer.

Possible future improvements:
* Use different metadata such that we can disambiguate native Swift
  classes during destruction -- allowing native release rather then unknown
  release usage.
* Optimize the newly added semantic function
  getContiguousArrayStorageType

rdar://86171143

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci test windows

**Comment by aschwaighofer** [comment]
@swift-ci benchmark

**Comment by aschwaighofer** [comment]
@swift-ci benchmark

**Comment by aschwaighofer** [comment]
@swift-ci benchmark

**Comment by aschwaighofer** [comment]
@swift-ci benchmark

**Comment by aschwaighofer** [comment]
@swift-ci test

**Comment by aschwaighofer** [comment]
@swift-ci benchmark

**Comment by shahmishal** [comment]
@swift-ci benchmark

**Pull request merged**
