### PR TITLE
Fix "Cannot use Swift.Error protocol in ObjC protocols"

### PR DESCRIPTION
**Pull request by colemancda**
#### What's in this pull request?

Allows conforming to Objective-C protocols that contain NSError as an argument. This would previously crash the compiler
#### Resolved bug number: ([SR-2159](https://bugs.swift.org/browse/SR-2159))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

A smoke test on macOS does the following:
1. Builds the compiler incrementally.
2. Builds the standard library only for macOS. Simulator standard libraries and
   device standard libraries are not built.
3. lldb is not built.
4. The test and validation-test targets are run only for macOS. The optimized
   version of these tests are not run.

A smoke test on Linux does the following:
1. Builds the compiler incrementally.
2. Builds the standard library incrementally.
3. lldb is built incrementally.
4. The swift test and validation-test targets are run. The optimized version of these
   tests are not run.
5. lldb is tested.

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by colemancda** [comment]
Here is a reproducible case.https://github.com/colemancda/SR-2159

**Comment by jrose-apple** [comment]
Thanks! Can you add a test case in the style of the ones already in test/PrintAsObjC/ ?

**Comment by colemancda** [comment]
@jrose-apple Done.

**Comment by DougGregor** [comment]
@swift-ci please smoke test OS X and merge

**Comment by DougGregor** [comment]
@swift-ci please smoke test OSX and merge

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
That's a legitimate failure:

Assertion failed: (proto->isObjC()), function visitProtocolType, file /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/swift/lib/PrintAsObjC/PrintAsObjC.cpp, line 1249.
0  swiftc                   0x00000001059957eb llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 43
1  swiftc                   0x0000000105994a16 llvm::sys::RunSignalHandlers() + 70
2  swiftc                   0x00000001059960c1 SignalHandler(int) + 641
3  libsystem_platform.dylib 0x00007fff90d5d52a _sigtramp + 26
4  swiftc                   0x00000001062e35e1 cmark_strbuf__initbuf + 66096
5  swiftc                   0x0000000105995d0e abort + 14
6  swiftc                   0x0000000105995cf1 __assert_rtn + 81
7  swiftc                   0x00000001034e2054 (anonymous namespace)::ObjCPrinter::visitProtocolType(swift::ProtocolType*, llvm::Optional<swift::OptionalTypeKind>, bool) + 356
8  swiftc                   0x00000001034e0a70 swift::TypeVisitor<(anonymous namespace)::ObjCPrinter, void, llvm::Optional<swift::OptionalTypeKind> >::visit(swift::Type, llvm::Optional<swift::OptionalTypeKind>) + 800
9  swiftc                   0x00000001034e0390 (anonymous namespace)::ObjCPrinter::print(swift::Type, llvm::Optional<swift::OptionalTypeKind>, swift::Identifier) + 208
10 swiftc                   0x00000001034ebcc6 (anonymous namespace)::ObjCPrinter::printAbstractFunctionAsMethod(swift::AbstractFunctionDecl*, bool, bool) + 2118
11 swiftc                   0x00000001034eb0d2 (anonymous namespace)::ObjCPrinter::printMembers(swift::IteratorRange<swift::DeclIterator>) + 338
12 swiftc                   0x00000001034e9a40 swift::ASTVisitor<(anonymous namespace)::ObjCPrinter, void, void, void, void, void, void>::visit(swift::Decl*) + 4752
13 swiftc                   0x00000001034dc334 swift::printAsObjC(llvm::raw_ostream&, swift::ModuleDecl*, llvm::StringRef, swift::Accessibility) + 1700
14 swiftc                   0x0000000103045eed printAsObjC(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, swift::ModuleDecl*, llvm::StringRef, bool) + 461
15 swiftc                   0x000000010304442d performCompile(swift::CompilerInstance&, swift::CompilerInvocation&, llvm::ArrayRef<char const*>, int&, swift::FrontendObserver*) + 12989
16 swiftc                   0x000000010303fe9b swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 2795
17 swiftc                   0x0000000103002890 main + 2320
18 libdyld.dylib            0x00007fff8d52f5ad start + 1
Stack dump:
0.	Program arguments: /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/buildbot_incremental/swift-macosx-x86_64/bin/swiftc -frontend -target x86_64-apple-macosx10.9 -module-cache-path /var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/swift-testsuite-clang-module-cache7MXroU -sdk /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -sdk /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/swift/test/PrintAsObjC/../Inputs/clang-importer-sdk -I /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/PrintAsObjC/Output/error-delegate.swift.tmp -import-objc-header /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/swift/test/PrintAsObjC/Inputs/error-delegate.h -parse-as-library /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/PrintAsObjC/Output/error-delegate.swift.tmp/error-delegate.swiftmodule -parse -emit-objc-header-path /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/PrintAsObjC/Output/error-delegate.swift.tmp/error-delegate.h

**Comment by colemancda** [comment]
@DougGregor I think that assertion needs to be changed there too to deal with Swift.Error.

**Comment by colemancda** [comment]
@DougGregor Is there a way to quickly compile and run the tests on my local machine?

**Comment by colemancda** [comment]
@DougGregor Can we try again? Changed that assertion.

**Comment by jrose-apple** [comment]
@swift-ci Please test OS X platform

**Comment by jrose-apple** [comment]
If I'm trying to test things quickly, I usually just build the compiler (the "swift" target in Ninja or Xcode), and then [run tests directly](https://github.com/apple/swift/blob/master/docs/Testing.rst). For Ninja, that looks like `ninja -C build/$SUBDIR/swift-macosx-x86_64/ swift`. Of course, this isn't equivalent to rebuilding everything properly.

**Comment by DougGregor** [comment]
It would be good to check that an Error? parameter comes through properly as well.

**Comment by colemancda** [comment]
Could you give me an example syntax please? I haven’t seen how optionals are checked in the code.

	Coleman,

**Comment by colemancda** [comment]
I fixed the compilation error. @DougGregor I will amend the test case for `Error?`.

**Comment by colemancda** [comment]
Done. Please test.

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
I'm looking at this; it's going to require a slightly different approach.

**Comment by DougGregor** [comment]
I ended up tweaking this a little and committing it as

  https://github.com/apple/swift/commit/a00fa74b8d0e7183b1697101ce4afe9ced7a91a7

**Comment by colemancda** [comment]
Thanks! @DougGregor

**Pull request closed without merging**
