### PR TITLE
[benchmark] Rename InsertCharacter to String.insert

### PR DESCRIPTION
**Pull request by palimondo**
Applying new Benchmark Naming Convention #20334

### CODE REVIEW

**Comment by palimondo** [comment]
@eeckstein I'll try to kill two birds with one stone here 😜:

This can be used to validate working of #20807, because the new naming convention hasn't landed yet and the Benchmark Check will complain that the new names don't match the `UpperCamelCase` convention…

…but given these are quite recent additions, could we rename them for real, without disturbing the long-term performance tracking?

**Comment by eeckstein** [comment]
> could we rename them for real, without disturbing the long-term performance tracking?

Renaming them will make these benchmarks useless until we do a rebase.
Therefore I prefer to apply the new naming conventions only on new benchmarks.

**Comment by palimondo** [comment]
What is the rebase in this case?

**Comment by palimondo** [comment]
@eeckstein ^^

...also, analyzing weird memory behavior of these benchmarks with @milseman in  https://github.com/apple/swift/pull/20807#issuecomment-442965562, we've discovered these benchmarks need to be corrected to perform linear work regardless of `N`/`--num-iters`. If that fix changes reported times it might make sense to couple that with this rename, right?

**Comment by CodaFi** [comment]
There hasn't been movement here in a year.  It seems like the consensus is that we shouldn't take this without some more work.  I'm going to close this out, but if you would like to pursue this please reopen it and respond to the feedback, or give us a new pull request.

Thanks @palimondo!

**Pull request closed without merging**
