### PR TITLE
[move-only] Fix two small errors around handling capturing of noncopyable self by local functions

### PR DESCRIPTION
**Pull request by gottesmm**
Specifically:

----
```
[move-only] Do not try to capture self as an immutable box.

The problem here is that the logic was conditionalized on all noncopyable
parameters that are borrowed as having the ValueOwnership::Shared flag set. This
is only true for user written parameters. Implicit noncopyable parameters like
self do not have ValueOwnership::Shared set upon them. We could potentially do
that in Sema, but Sema does not know what the proper convention of self is since
that information is in TypeLowering today.

With that in mind, conditionalize the logic here so we do the right thing.

rdar://112547982
```
----
```
[move-only] Make sure we mark local function inout parameters with mark_must_check.

Originally, we were relying on capture info to determine if we needed to insert
this mark_must_check. This ignored that the way that we are handling
escaping/non-escaping is something that is approximated in the AST but actually
determined at SIL level. With that in mind, rather than relying on the capture
info here, just rely on us having an inout argument. The later SIL level
checking for inout escapes is able to handle mark_must_check and knows how to
turn off noncopyable errors in the closure where we detect the error to prevent
us from emitting further errors due to the mark_must_check here.

I discovered this while playing with the previous commit.

rdar://112555589
```

----

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
The reason why we still don't emit the mark_must_check errors is that the  inout usage by closure pass puts a semantic function on the violating closure that says do not emit move only diagnostics in this function.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Review by jckarter — APPROVED** [review]

**Pull request merged**
