### PR TITLE
[ArraySemantics] Simplify the code a bit. NFCI.

### PR DESCRIPTION
**Pull request by dcci**

### CODE REVIEW

**Comment by dcci** [comment]
@swift-ci please test

**Comment by dcci** [comment]
@swift-ci please clean test

**Comment by dcci** [comment]
@swift-ci please test

**Comment by dcci** [comment]
@swift-ci please test

**Comment by dcci** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
@swift-ci please test

**Pull request merged**
