### PR TITLE
Fix an overspecific lit check: unsafebufferpointer.swift.

### PR DESCRIPTION
**Pull request by atrick**
<rdar://problem/48016982> TEST 'Swift(iphonesimulator-i386) :: SILOptimizer/unsafebufferpointer.swift' FAILED

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci smoke test and merge.

**Comment by atrick** [comment]
@swift-ci smoke test

**Comment by atrick** [comment]
We'll see if this works... I was never able to get the iphonesimulator-i386 platform to build.

**Comment by atrick** [comment]
@swift-ci smoke test and merge.

**Comment by atrick** [comment]
@swift-ci smoke test and merge.

**Comment by shahmishal** [comment]
@atrick smoke test will not test iphonesimulator-i386

**Comment by shahmishal** [comment]
@swift-ci test macOS

**Pull request merged**
