### PR TITLE
SIL: Introduce `has_symbol` instruction

### PR DESCRIPTION
**Pull request by tshortli**
Create a dedicated SIL instruction for `if #_hasSymbol` conditions. This solves two issues with the previous implementation:
- `if #_hasSymbol()` can now be successfully inlined across module boundaries.
- SIL functions that are referenced by the `#_hasSybmol` directive can be marked alive during dead function elimination, ensuring that the correct IR is generated even when the functions are otherwise unused in the program.

Resolves rdar://102159307

### CODE REVIEW

**Comment by tshortli** [comment]
@swift-ci please test

**Comment by tshortli** [comment]
Fixing the Linux build failure with https://github.com/apple/swift/pull/62150.

**Review by nkcsgexi — APPROVED** [review]
Love it! Much cleaner than emitting call sites and function definitions separately👍.

**Review by xymus — APPROVED** [review]

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Pull request merged**
