### PR TITLE
[moveOnly] Make _move public.

### PR DESCRIPTION
**Pull request by gottesmm**
This was just a mistake on my part. Thanks to Guillaume for helping find this
with me!

### CODE REVIEW

**Comment by gottesmm** [comment]
Actually going to add a quick test

**Comment by glessard** [comment]
We're not including `_copy` as well?

**Comment by gottesmm** [comment]
@glessard I haven't landed that yet. Maybe the thing to do is do both at the same time.

**Comment by gottesmm** [comment]
Lets do that.

**Pull request closed without merging**
