### PR TITLE
 SILGen: Allocating entry points for @objc dynamic inits should use alloc_ref_dynamic

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes <rdar://problem/49560721>, <https://bugs.swift.org/browse/SR-10285>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Review by jckarter — APPROVED** [review]
Thanks for fixing this!

**Pull request merged**
