### PR TITLE
[stdlib] fix some inconsistent declarations

### PR DESCRIPTION
**Pull request by glessard**
`private` function declarations should never be allowed to carry the `@_alwaysEmitIntoClient` attribute. This has been allowed by mistake for a while, but newer compilers should make this an error. The strange consequence of this combination of keywords was that these `private` symbols were emitted into the swiftinterface file.

Also: opportunistically changed a `bindMemory()` usage to use temporary rebinding instead.

Addresses rdar://132941798

### CODE REVIEW

**Comment by glessard** [comment]
@swift-ci please smoke test

**Review by lorentey — APPROVED** [review]
Yes please!

**Comment by glessard** [comment]
@swift-ci please smoke test

**Comment by glessard** [comment]
@swift-ci please test

**Comment by glessard** [comment]
@swift-ci please test linux platform

**Pull request merged**
