### PR TITLE
Begin migrating AbstractionPattern over to the new function type representation

### PR DESCRIPTION
**Pull request by slavapestov**
`AbstractionPattern::getFunctionInputType()` loses the distinction between an argument list and a single argument of tuple type, because the underlying type of an AbstractionPattern is canonical. It also forces us to construct tuple types that contain InOutType and varargs, which is something we want to move away from. An earlier PR introduced `AbstractionPattern::getFunctionParamType()`; this PR fleshes it out and uses it in more places. Note that a couple of usages of `AbstractionPattern::getFunctionInputType()` still remain, but I'm going to tackle those in a subsequent PR.

### CODE REVIEW

**Comment by slavapestov** [comment]
@jckarter @CodaFi please take a look.

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by jckarter** [comment]
Makes sense.

**Comment by slavapestov** [comment]
@swift-ci Please test macOS

**Pull request merged**
