### PR TITLE
[NFC] Remove Syntax's dependency on Sema

### PR DESCRIPTION
**Pull request by harlanhaskins**
This patch removes `Semantics.cpp` of `libSyntax` from `Sema` and into `AST`. It also moves `LegacyASTTransformer`, the only user of `Sema/Semantics` into `AST`.

This ensures the dependency graph looks like this:

```
    Syntax
   /  |
  |  AST
   \  | 
    Parse
      |
     Sema
```

### CODE REVIEW

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test

**Review by jrose-apple — APPROVED** [review]
Thanks, Harlan!

**Comment by harlanhaskins** [comment]
Will squash and merge once CI passes. 👍

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test and merge

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test and merge

**Comment by harlanhaskins** [comment]
That test failure is not mine. Looks like it might be @CodaFi’s inout changes?

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test and merge

**Comment by harlanhaskins** [comment]
That failure is also unrelated – this is related to the weird failures we’ve been seeing the past few days 😕

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test and merge

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test and merge

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test and merge

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test and merge

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test

**Comment by harlanhaskins** [comment]
⛵️

**Pull request merged**
