### PR TITLE
[TypeChecker] Enable result builder AST transform by default

### PR DESCRIPTION
**Pull request by xedin**
This PR:

- Drops experimental feature flag (`ResultBuilderASTTransform`)
- Adjusts code completion (changes by @ahoppen)
- Adjusts all the improved test-cases

Resolves: rdar://89880662
Resolves: rdar://97388257
Resolves: rdar://95235303
Resolves: rdar://96343005
Resolves: rdar://91731420
Resolves: rdar://95977761
Resolves: rdar://80680636

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Review by hborla — APPROVED** [review]
Awesome!

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
lldb test-case failure :/

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Pull request merged**
