### PR TITLE
Debugging: Extend the live ranges of local values at -Onone.

### PR DESCRIPTION
**Pull request by adrian-prantl**
#### What's in this pull request?

```
Debugging: Extend the live ranges of local values at -Onone.

For many local values we can avoid a shadow alloca by directly
describing them with a dbg.value. This also enables precise liveness
so variables don't show up in the debugger before they are
initialized. Unfortunately this also means that values will disappear
when they are no longer needed.

This patch inserts an empty inline assembler expression depending on
the llvm::Value that is being described in the blocks dominated by it.
This uses less stack space than full shadow copies *and* allows us to
track the liveness of the variable completely. It may cause values to
be spilled onto the stack, though.

<rdar://problem/26627376>
```
#### Resolved bug number: rdar://problem/26627376

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

@swift-ci Please test and merge

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci Please test and merge

**Comment by adrian-prantl** [comment]
@swift-ci Please test and merge

**Comment by adrian-prantl** [comment]
@swift-ci Please test and merge

**Comment by adrian-prantl** [comment]
@swift-ci Please test and merge

**Comment by jrose-apple** [comment]
Won't this break bitcode?

**Comment by adrian-prantl** [comment]
Legitimate question! It won't, because empty inline assembler expressions are ignored.

Note that we're already playing similar tricks in IRGenSILFunction::visitCondFailInst() and IRGenModule::getObjCRetainAutoreleasedReturnValueMarker() to defeat optimizations.

**Comment by jrose-apple** [comment]
Good to know, thank you!

**Pull request merged**
