### PR TITLE
[5.0][Stdlib] Rename AnyKeyPath's ObjC name and _VaListBuilder to avoid conflicts with older stdlibs.

### PR DESCRIPTION
**Pull request by mikeash**
Cherry-pick #21127 to `swift-5.0-branch`.

rdar://problem/46546165

### CODE REVIEW

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@apple/swift5-branch-managers Not critical for convergence and does not affect ABI.

**Review by bob-wilson — APPROVED** [review]
We need this to be sure we can support runtime coexistence with older versions of Swift. Mike, can you please merge the master PR a day or two before this one? Just in case that exposes any issues....

**Comment by mikeash** [comment]
Ok. I merged the master PR and I’ll sit on this one for a bit.

**Comment by bob-wilson** [comment]
I haven't heard about any fallout on master, so I'll go ahead and merge this now.

**Pull request merged**
