### PR TITLE
[CS] Allow simplification of key path subscript arg locators

### PR DESCRIPTION
**Pull request by hamishknight**
This PR allows `simplifyLocator` to look into key path subscript arguments, which enables a few fixes to properly emit diagnostics for contextual failures of such arguments. 

Resolves [SR-11476](https://bugs.swift.org/browse/SR-11476).

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Review by xedin — APPROVED** [review]
@hamishknight FYI, I think we should be able to remove `CTP_CallArgument` soon, first step https://github.com/apple/swift/pull/27063 went in last night. The logic associated with key path component arguments would have to be moved to `ArgumentMismatchFailure` in the future...

**Comment by hamishknight** [comment]
@swift-ci please smoke test

**Comment by hamishknight** [comment]
@swift-ci please smoke test

**Comment by hamishknight** [comment]
@xedin That would be great if we could! I believe key path subscript args should already use `ArgumentMismatchFailure` for general contextual failures, as they should generate similar constraints to normal calls.

One problem with the contextual `nil` case is that the locator for its conformance constraint gets anchored directly on the `nil` expr rather than being an apply-arg-to-param locator. We may want to look into doing something similar to what you recently suggested where the "parent" locator builder is available during CSGen so we can have better locators for constraints like this.

**Pull request merged**
