### PR TITLE
[5.5] Include locations for external files in cursor info results

### PR DESCRIPTION
**Pull request by bnbarham**
Add locations for external files to cursor info results, include line and column in all results so that clients need not map those themselves.

As part of this change, serialize the offset of each location so that the `SourceLoc` can be built directly, without having to first generate the line map. Also output the source location directives to allow presumed locations to be constructed as per normal, rather than outputting the presumed location (which was being used as if it was a regular source location).

Resolves rdar://75582627

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Review by akyrtzi — APPROVED** [review]

**Comment by bnbarham** [comment]
@swift-ci please nominate

--- CCC ---

Explanation: Adds external locations (including line and column) to cursor info results by using the information provided in .swiftsourceinfo.

To avoid performance regressions, updated .swiftsourceinfo to serialize the offset of each location so that the SourceLoc can be built directly, without having to first generate the line map. Since the serialized location is used in `Decl::getLoc`, there's a further fix to output the actual location rather than the presumed one. Location directives are also output, allowing the presumed location can be built as per normal when actually required.

Tests previously ignored .swiftsourceinfo by default in order to not pick up stdlib's .swiftsourceinfo. The stdlib no longer outputs these though, so that option has been removed.

Radar/SR Issue: rdar://75582627

Risk: Minimal. There's a risk in having updated the .swiftsourceinfo format, but it's reasonably simple and exercised by the added tests. SourceKit requests previously did not take .sourceinfo into account, so I performed additional testing to increase confidence it doesn’t introduce regressions.

Testing: Added a new test for diagnostics and cursor info across modules that utilize .swiftsourceinfo. Modified lit so that .swiftsourceinfo is no longer ignored by default (this was added to ignore stdlib .swiftsourceinfo files, but these are no longer output).

Gathered timings for type checking and cursor info requests over some large generated examples (many diagnostics over many files). Only saw very small performance regression when .swiftsourceinfo files exist vs not, on the order of an additional 20ms for typechecking the file, with 1000 diagnostics emitted from 100 different modules (10 per module). Code-completion performance is unaffected.

**Comment by bnbarham** [comment]
@swift-ci please test macOS platform

**Comment by bnbarham** [comment]
@swift-ci please test Windows platform

**Comment by bnbarham** [comment]
Windows failure unrelated

**Pull request merged**
