### PR TITLE
[5.10 🍒][Explicit Module Builds] Restore prior behavior of consuming .h dependencies of binary module dependencies directly, instead of attempting to load their PCH

### PR DESCRIPTION
**Pull request by artemcm**
Cherry-pick of https://github.com/apple/swift/pull/69109
--------------------
• Release: Swift 5.10
• Explanation: We will now only record these dependencies in CAS mode, because we require explicit PCH tasks to be produced for imported header of binary module dependencies. In the meantime, in non-CAS mode loading clients will consume the `.h` files encoded in the `.swiftmodules` directly.

Followup changes to SwiftDriver will enable explicit PCH compilation of such dependenceis, but for the time being restore prior behavior for non-CAS explicit module builds.
• Scope of Issue: Explicit module builds 
• Risk: Minimal, this change affects only code paths for explicit module builds, which are not yet default.
• Origination: Explicit Module Build feature development and addition of CAS-specific functionality. 

Resolves rdar://116006619

### CODE REVIEW

**Review by nkcsgexi — APPROVED** [review]

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
@swift-ci test and merge

**Comment by artemcm** [comment]
@swift-ci test and merge

**Comment by artemcm** [comment]
https://github.com/apple/swift-driver/pull/1464
@swift-ci test

**Comment by artemcm** [comment]
https://github.com/apple/swift-driver/pull/1464
@swift-ci test Windows platform

**Pull request merged**
