### PR TITLE
[ownership] Move ownership lowering past SROA.

### PR DESCRIPTION
**Pull request by gottesmm**
I already updated SROA for this and we already have tests/etc. We have just been
waiting on some other passes to be moved afterwards.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
Windows failure is I believe an lldb failure. Not this.

**Review by meg-gupta — COMMENTED** [review]
lgtm

**Pull request merged**
