### PR TITLE
Hi ho, Typo!

### PR DESCRIPTION
**Pull request by Coeur**
Typo fix.

Credit to @Julcompa for finding it.

### CODE REVIEW

**Comment by Julcompa** [comment]
Thanks for the credit @Coeur  that's a substantial PR lol 😂.

**Comment by slavapestov** [comment]
Nice catch, thanks

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by natecook1000** [comment]
Thanks, @Coeur & @Julcompa! 👏🐎🏜⛺️

**Pull request merged**
