### PR TITLE
SIL: update for LLVM iplist/ilist changes

### PR DESCRIPTION
**Pull request by compnerd**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

A smoke test on macOS does the following:
1. Builds the compiler incrementally.
2. Builds the standard library only for macOS. Simulator standard libraries and
   device standard libraries are not built.
3. lldb is not built.
4. The test and validation-test targets are run only for macOS. The optimized
   version of these tests are not run.

A smoke test on Linux does the following:
1. Builds the compiler incrementally.
2. Builds the standard library incrementally.
3. lldb is built incrementally.
4. The swift test and validation-test targets are run. The optimized version of these
   tests are not run.
5. lldb is tested.

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

Update SIL to deal with the behaviour of iplist/ilist changing to avoid UB.
NFC.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @dexonsmith @gottesmm

**Comment by gottesmm** [comment]
This one looks like it is going to be relatively nasty.

**Comment by gottesmm** [comment]
Just based on my experience of messing with this sort of thing ; )

**Comment by compnerd** [comment]
@gottesmm never would've guessed this is going to be nasty!  The worst part of it is that this is one of two parallel sets of major restructuring :-(.  I need to look into a similarly nasty one involving GraphTraits still.  That may actually be worse than this.

**Comment by compnerd** [comment]
This time with more testing.  This definitely works, as with this an other patches, I finally have tests passing on Linux again.

**Comment by compnerd** [comment]
Okay, this is now the first in a series of patches for dealing with iplist changes on the LLVM side.  I don't really know what the best way forward is, but having the patches just sit around probably isn't the best.  @gottesmm ideas on how to deal with this?

**Comment by gottesmm** [comment]
@bob-wilson Is I think using your patch as a starting point for the next merge.

**Comment by bob-wilson** [comment]
I've got a smaller set of patches almost ready to go. Some of the changes here, such as switching to use lists with a parent pointer, are orthogonal to making things work with the ilist changes. We could consider some of those, but first we should just do the minimal thing to make the code work.

**Comment by bob-wilson** [comment]
I think we can close this now, since master-next has been working with the ilist changes for a while.

**Pull request closed without merging**
