### PR TITLE
[cxx-interop] Recognize `CxxStdlib` as an alias for `std`

### PR DESCRIPTION
**Pull request by egorzhdan**
C++ standard library module is called `std`. To make it more clear to a Swift developer that this module is a C++ stdlib, and not a Swift stdlib, let's rename it to `CxxStdlib`.

This is the first step in the module rename. We don't ban `std` in this patch to be able to build SwiftCompilerSources with hosttools until a new Swift compiler is shipped.

### CODE REVIEW

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by hyp** [comment]
Can you add a test where you `import CxxStdlib` from source?

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
> Can you add a test where you import CxxStdlib from source?

@hyp yeap, added a test.

**Review by hyp — APPROVED** [review]

**Pull request merged**
