### PR TITLE
FlattenSequence/distance(from:to:) enhancements.

### PR DESCRIPTION
**Pull request by oscbyspro**
I was looking through Swift's issues tab and found this issue (#57496), which points out the poor performance of `FlattenSequence/count`. The current `count` implementation calls `distance(from:to:)`, which iterates through the entire collection, so I thought I'd improve that method. The new version computes the distance as the sum of three parts, with a fast path when both indices belong to the same underlying collection. Note that it does this by calling either `count` or `distance(from:to:)` on each underlying collection, which makes `[repeatElement(0, count: Int.max)].joined().count` instant, for example.

<details>
<summary>Here's some code I've used to test it...</summary>

```swift
/// Loops through every index pair for some random instances.
func testFlattenSequenceDistanceFromTo() {
  for _ in 0 ..< 10000 {
    let joined = (0 ..< Int.random(in: 0 ..< 10)).map({ Array(repeating: $0, count: Int.random(in: 0 ..< 10)) }).joined()
          
    var index0 = joined.startIndex; var offset0 = 0; loop0: while index0 <= joined.endIndex {
    var index1 = joined.startIndex; var offset1 = 0; loop1: while index1 <= joined.endIndex {
      
      precondition(joined.distance(from: index0, to: index1) == offset1 - offset0)
      precondition(joined.distance(from: index1, to: index0) == offset0 - offset1)
      
      if index1 < joined.endIndex { joined.formIndex(after: &index1); offset1 += 1 } else { break loop1 }
    };if index0 < joined.endIndex { joined.formIndex(after: &index0); offset0 += 1 } else { break loop0 }
    }
  }
}
```

</details>

### CODE REVIEW

**Comment by glessard** [comment]
I'm not certain this is exercised by one of our benchmarks, but it might be.

**Comment by glessard** [comment]
@swift-ci please benchmark

**Comment by oscbyspro** [comment]
I see. I arrived at a somewhat faster (and safer) version while fiddling some more with it. The unchecked stuff did not matter, so I changed it in the most recent commit. I've also tested variations of the code I used for testing, and it was much faster for random access bases and some 5x faster for collections of strings (compared to the original version).

**Comment by glessard** [comment]
@swift-ci please benchmark

**Comment by glessard** [comment]
@swift-ci please smoke test

**Comment by glessard** [comment]
### Performance (x86_64): -O

| **Regression**                           |  **OLD** |  **NEW** | **DELTA** |     **RATIO** |
| :--------------------------------------- | -------: | -------: | --------: | ------------: |
| LessSubstringSubstring                   |   23.829 |   30.921 |    +29.8% |     **0.77x** |
| EqualSubstringString                     |    23.83 |     30.8 |    +29.2% | **0.77x (?)** |
| LessSubstringSubstringGenericComparable  |   23.939 |   30.919 |    +29.2% | **0.77x (?)** |
| EqualSubstringSubstring                  |    23.95 |   30.909 |    +29.1% | **0.77x (?)** |
| EqualStringSubstring                     |   24.179 |   31.037 |    +28.4% |     **0.78x** |
| EqualSubstringSubstringGenericEquatable  |   24.031 |   30.808 |    +28.2% | **0.78x (?)** |
| UTF8Decode_InitFromBytes                 |   145.25 |    182.3 |    +25.5% | **0.80x (?)** |
| UTF8Decode_InitFromData                  |  146.333 |    181.2 |    +23.8% | **0.81x (?)** |
| StringComparison_longSharedPrefix        |    206.2 |  243.857 |    +18.3% | **0.85x (?)** |
| Data.hash.Medium                         |    24.29 |   28.074 |    +15.6% | **0.87x (?)** |
| StringBuilder                            |    232.0 |  259.222 |    +11.7% | **0.89x (?)** |
| Breadcrumbs.UTF16ToIdx.longASCII         |   39.328 |   43.586 |    +10.8% | **0.90x (?)** |
| CharacterRecognizer.ascii                |   90.647 |   99.692 |    +10.0% | **0.91x (?)** |
| String.replaceSubrange.ArrChar           |    36.05 |   39.458 |     +9.5% | **0.91x (?)** |
| &nbsp;                                   |          |          |           |               |
| **Improvement**                          |  **OLD** |  **NEW** | **DELTA** |     **RATIO** |
| FlattenDistanceFromTo.Array.Array.08.08  |   2025.0 |   74.613 |    -96.3% |    **27.14x** |
| FlattenDistanceFromTo.Array.Array.08.04  |    503.5 |   29.125 |    -94.2% |    **17.29x** |
| FlattenDistanceFromTo.Array.Array.04x08  |    265.0 |   15.886 |    -94.0% |    **16.68x** |
| FlattenDistanceFromTo.Array.Array.04.04  |   65.735 |    6.489 |    -90.1% |    **10.13x** |
| FlattenDistanceFromTo.Array.String.08.08 |   5177.0 |   2262.0 |    -56.3% |     **2.29x** |
| FlattenDistanceFromTo.Array.String.08.04 |    821.5 |    366.2 |    -55.4% |     **2.24x** |
| FlattenDistanceFromTo.Array.String.04.08 |  680.333 |  333.167 |    -51.0% |     **2.04x** |
| FlattenDistanceFromTo.Array.String.04.04 |    112.0 |   57.775 |    -48.4% |     **1.94x** |
| FlattenListLoop                          |   1626.0 |    977.0 |    -39.9% | **1.66x (?)** |
| ArrayAppendGenericStructs                |   1770.0 |   1180.0 |    -33.3% | **1.50x (?)** |
| UTF8Decode_InitFromCustom_contiguous     |  165.727 |  139.438 |    -15.9% | **1.19x (?)** |
| UTF8Decode_InitDecoding                  |    167.1 |  140.625 |    -15.8% | **1.19x (?)** |
| UTF8Decode_InitFromCustom_noncontiguous  |  210.333 |  182.667 |    -13.2% | **1.15x (?)** |
| ObjectiveCBridgeStringHash               |   75.387 |   66.571 |    -11.7% | **1.13x (?)** |
| NSStringConversion.InlineBuffer.UTF8     |    710.0 |    639.0 |    -10.0% | **1.11x (?)** |
| BridgeString.find.native.longNonASCII    |  457.333 |   416.25 |     -9.0% | **1.10x (?)** |
| String.replaceSubrange.String            |   10.887 |    9.988 |     -8.3% | **1.09x (?)** |
| ArrayAppendAscii                         | 1957.125 | 1808.476 |     -7.6% | **1.08x (?)** |
| InsertCharacterEndIndex                  |   95.105 |    88.81 |     -6.6% | **1.07x (?)** |
| InsertCharacterEndIndexNonASCII          |     30.6 |   28.581 |     -6.6% | **1.07x (?)** |

### Code size: -O

| **Regression**          | **OLD** | **NEW** | **DELTA** | **RATIO** |
| :---------------------- | ------: | ------: | --------: | --------: |
| FlattenDistanceFromTo.o |   10057 |   10793 |     +7.3% | **0.93x** |

### Performance (x86_64): -Osize

| **Regression**                           |  **OLD** | **NEW** | **DELTA** |     **RATIO** |
| :--------------------------------------- | -------: | ------: | --------: | ------------: |
| FlattenListLoop                          |    987.0 |  1640.0 |    +66.2% | **0.60x (?)** |
| EqualStringSubstring                     |   23.194 |  30.136 |    +29.9% | **0.77x (?)** |
| EqualSubstringSubstring                  |   23.256 |  30.154 |    +29.7% | **0.77x (?)** |
| UTF8Decode_InitFromData                  |  142.071 |   183.4 |    +29.1% | **0.77x (?)** |
| EqualSubstringSubstringGenericEquatable  |     23.4 |  30.154 |    +28.9% |     **0.78x** |
| EqualSubstringString                     |   24.176 |  31.143 |    +28.8% |     **0.78x** |
| LessSubstringSubstringGenericComparable  |   24.279 |   31.25 |    +28.7% |     **0.78x** |
| LessSubstringSubstring                   |   24.273 |  31.227 |    +28.6% | **0.78x (?)** |
| UTF8Decode_InitFromBytes                 |  145.667 | 182.857 |    +25.5% | **0.80x (?)** |
| StringComparison_longSharedPrefix        |    204.6 |   239.9 |    +17.3% | **0.85x (?)** |
| Data.hash.Medium                         |   24.258 |  28.094 |    +15.8% | **0.86x (?)** |
| StringBuilder                            |  230.833 |   257.0 |    +11.3% | **0.90x (?)** |
| FindString.Loop1.Substring               |  298.875 | 329.571 |    +10.3% | **0.91x (?)** |
| &nbsp;                                   |          |         |           |               |
| **Improvement**                          |  **OLD** | **NEW** | **DELTA** |     **RATIO** |
| FlattenDistanceFromTo.Array.Array.08.08  |   2075.0 |    70.0 |    -96.6% |    **29.64x** |
| FlattenDistanceFromTo.Array.Array.04x08  |  278.429 |  14.969 |    -94.6% |    **18.60x** |
| FlattenDistanceFromTo.Array.Array.08.04  |    515.5 |  28.486 |    -94.5% |    **18.10x** |
| FlattenDistanceFromTo.Array.Array.04.04  |   66.588 |   6.404 |    -90.4% |    **10.40x** |
| FlattenDistanceFromTo.Array.String.08.08 |   5387.0 |  2219.0 |    -58.8% |     **2.43x** |
| FlattenDistanceFromTo.Array.String.08.04 |    846.5 | 361.333 |    -57.3% |     **2.34x** |
| FlattenDistanceFromTo.Array.String.04.08 |    709.0 | 325.667 |    -54.1% |     **2.18x** |
| FlattenDistanceFromTo.Array.String.04.04 |  115.833 |  56.469 |    -51.2% |     **2.05x** |
| StringWithCString2                       |    0.001 |     0.0 |    -50.0% | **2.00x (?)** |
| Array.removeAll.keepingCapacity.Object   |    7.172 |   5.837 |    -18.6% | **1.23x (?)** |
| UTF8Decode_InitFromCustom_contiguous     |  168.364 |   141.0 |    -16.3% |     **1.19x** |
| UTF8Decode_InitDecoding                  |    166.9 | 140.364 |    -15.9% | **1.19x (?)** |
| ObjectiveCBridgeStringHash               |   75.429 |  65.935 |    -12.6% | **1.14x (?)** |
| String.replaceSubrange.String            |   11.218 |   9.913 |    -11.6% | **1.13x (?)** |
| ArrayAppendAscii                         | 2058.889 |  1849.6 |    -10.2% | **1.11x (?)** |
| InsertCharacterEndIndexNonASCII          |   30.967 |  28.129 |     -9.2% | **1.10x (?)** |
| BridgeString.find.native.longNonASCII    |    457.0 |   416.5 |     -8.9% | **1.10x (?)** |
| StringDistance.characters.ascii          |   3182.0 |  2909.0 |     -8.6% | **1.09x (?)** |
| UTF8Decode_InitFromCustom_noncontiguous  |  331.571 | 305.429 |     -7.9% | **1.09x (?)** |
| InsertCharacterEndIndex                  |   95.158 |  88.294 |     -7.2% | **1.08x (?)** |
| Breadcrumbs.IdxToUTF16.longASCII         |   44.673 |   41.49 |     -7.1% | **1.08x (?)** |

### Code size: -Osize

| **Regression**          | **OLD** | **NEW** | **DELTA** | **RATIO** |
| :---------------------- | ------: | ------: | --------: | --------: |
| FlattenDistanceFromTo.o |    8593 |   10165 |    +18.3% | **0.85x** |

### Performance (x86_64): -Onone

| **Regression**                           | **OLD** | **NEW** | **DELTA** |     **RATIO** |
| :--------------------------------------- | ------: | ------: | --------: | ------------: |
| Array.removeAll.keepingCapacity.Object   |    5.66 |   8.796 |    +55.4% | **0.64x (?)** |
| EqualSubstringSubstring                  |  28.216 |   36.25 |    +28.5% | **0.78x (?)** |
| EqualStringSubstring                     |  27.818 |  35.632 |    +28.1% |     **0.78x** |
| UTF8Decode_InitFromData                  | 142.375 | 181.909 |    +27.8% | **0.78x (?)** |
| LessSubstringSubstringGenericComparable  |  26.469 |  33.419 |    +26.3% | **0.79x (?)** |
| EqualSubstringSubstringGenericEquatable  |  26.903 |  33.862 |    +25.9% | **0.79x (?)** |
| EqualSubstringString                     |  28.531 |   35.71 |    +25.2% | **0.80x (?)** |
| LessSubstringSubstring                   |  28.483 |    35.5 |    +24.6% |     **0.80x** |
| UTF8Decode_InitFromBytes                 | 148.538 | 182.857 |    +23.1% | **0.81x (?)** |
| String.replaceSubrange.ArrChar           |  39.423 |  44.891 |    +13.9% | **0.88x (?)** |
| Data.hash.Medium                         |    28.5 |  32.048 |    +12.4% | **0.89x (?)** |
| DropFirstArrayLazy                       | 29154.0 | 32048.0 |     +9.9% | **0.91x (?)** |
| SuffixArrayLazy                          |  9785.0 | 10655.0 |     +8.9% | **0.92x (?)** |
| PrefixArrayLazy                          | 29424.0 | 31950.0 |     +8.6% | **0.92x (?)** |
| DropLastArrayLazy                        |  9770.0 | 10581.0 |     +8.3% | **0.92x (?)** |
| &nbsp;                                   |         |         |           |               |
| **Improvement**                          | **OLD** | **NEW** | **DELTA** |     **RATIO** |
| FlattenDistanceFromTo.Array.Array.08.08  | 46452.0 | 10092.0 |    -78.3% |     **4.60x** |
| FlattenDistanceFromTo.Array.String.08.08 | 45107.0 | 11749.0 |    -74.0% |     **3.84x** |
| FlattenDistanceFromTo.Array.Array.04x08  |  6392.0 |  2042.0 |    -68.1% |     **3.13x** |
| FlattenDistanceFromTo.Array.String.04.08 |  6232.0 |  2228.0 |    -64.2% |     **2.80x** |
| FlattenDistanceFromTo.Array.Array.08.04  |  7104.0 |  2569.0 |    -63.8% |     **2.77x** |
| FlattenDistanceFromTo.Array.String.08.04 |  6762.0 |  2723.0 |    -59.7% |     **2.48x** |
| FlattenDistanceFromTo.Array.Array.04.04  |  1041.0 |   521.0 |    -50.0% |     **2.00x** |
| FlattenDistanceFromTo.Array.String.04.04 |  1010.5 |   551.0 |    -45.5% |     **1.83x** |
| ArrayAppendGenericStructs                |  1392.5 |  1102.5 |    -20.8% | **1.26x (?)** |
| UTF8Decode_InitFromCustom_contiguous     |   179.2 | 148.167 |    -17.3% | **1.21x (?)** |
| UTF8Decode_InitDecoding                  |  176.25 | 147.333 |    -16.4% | **1.20x (?)** |
| ObjectiveCBridgeStringHash               |  76.143 |  66.258 |    -13.0% | **1.15x (?)** |
| String.replaceSubrange.String            |   12.52 |  11.225 |    -10.3% | **1.12x (?)** |
| BridgeString.find.native.longNonASCII    |   457.0 | 415.667 |     -9.0% | **1.10x (?)** |
| StringInterpolationSmall                 |  2322.5 |  2130.0 |     -8.3% | **1.09x (?)** |
| SIMDReduce.Int8                          |  6949.0 |  6422.0 |     -7.6% | **1.08x (?)** |

### Code size: -swiftlibs



<details>
  <summary><strong>How to read the data</strong></summary>
The tables contain differences in performance which are larger than 8% and
differences in code size which are larger than 1%.


If you see any unexpected regressions, you should consider fixing the
regressions before you merge the PR.

**Noise**: Sometimes the performance results (not code size!) contain false
alarms. Unexpected regressions which are marked with '(?)' are probably noise.
If you see regressions which you cannot explain you can try to run the
benchmarks again. If regressions still show up, please consult with the
performance team (@eeckstein).
</details>

<details>
  <summary><strong>Hardware Overview</strong></summary>


      Model Name: Mac mini
      Model Identifier: Macmini8,1
      Processor Name: 6-Core Intel Core i7
      Processor Speed: 3.2 GHz
      Number of Processors: 1
      Total Number of Cores: 6
      L2 Cache (per Core): 256 KB
      L3 Cache: 12 MB
      Memory: 32 GB

</details>

**Comment by glessard** [comment]
There are a lot of noisy benchmarks in here, but since we touched this area maybe it would be worth checking whether there is something to the change in the "FlattenListLoop" benchmark?

**Comment by oscbyspro** [comment]
Hm, can you try again? I find the result FlattenListLoop odd. It looks like noise:

```
FlattenListLoop: A -> B with -O
FlattenListLoop: B -> A with -Osize
```

Moreover, it flattens an array of tuples by hand and does not use FlattenSequence:

https://github.com/apple/swift/blob/e7f7900063348ddc3d90d8e9951d4123e6f80596/benchmark/single-source/FlattenList.swift#L37-L56

**Comment by glessard** [comment]
Thanks for checking, I agree it looks like noise!

**Comment by glessard** [comment]
Thanks @oscbyspro !

**Pull request merged**
