### PR TITLE
[stdlib]Custom message for recursive Strideable witness

### PR DESCRIPTION
**Pull request by CodaFi**
The wording for the errors and the docs needs to be shopped, but otherwise this should do it.

Improves QoI for rdar://33668987

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Review by moiseev — CHANGES_REQUESTED** [review]
As discussed in person. The problem with StdlibUnittest style test is that it would succeed even without your patch. Validating the message is essential in this case, and so it should be a file-check style test.

A minor nitpick: all the non-mutating binary operators in `InvalidStrideable` are not needed, since there are default implementations for them.

**Comment by CodaFi** [comment]
@moiseev It seems that they are required, otherwise I get ambiguities with requirements inherited, unsurprisingly, from Strideable extensions.

**Comment by CodaFi** [comment]
@swift-ci please test

**Comment by CodaFi** [comment]
@swift-ci please test

**Review by moiseev — APPROVED** [review]

**Comment by moiseev** [comment]
This change adds even more overloads to an already crowded space. Worth timing stdlib compile times... Just to be sure.

**Comment by natecook1000** [comment]
Out of curiosity, did we consider removing `Strideable`'s default implementations of `==` and `<` as an alternative solution?

**Comment by CodaFi** [comment]
I originally wanted to, but doing so is source-breaking.  FWIW, these are correct witnesses in every case but the one in the validation test/radar, you really have to struggle with basically re-implementing a numeric type to come close to this trap.

**Comment by CodaFi** [comment]
(Or, in my case, break overload resolution for all the numeric types and wonder why LLVM was inserting infinite loops in odd places)

**Comment by jrose-apple** [comment]
Hm. This is a little unfortunate because they become part of the ABI, but I guess they're tiny. Can you also mark them deprecated, so that the user will get a warning at compile time too? (Unfortunately they can't be unavailable because that affects overload resolution.)

**Comment by jckarter** [comment]
The ABI impact could be nullified by making them inlinable, when we have that.

**Comment by CodaFi** [comment]
@swift-ci please test

**Comment by CodaFi** [comment]
@swift-ci please test

**Comment by CodaFi** [comment]
@swift-ci please test source compatibility

**Comment by CodaFi** [comment]
@swift-ci please test source compatibility

**Comment by CodaFi** [comment]
⛵️

**Pull request merged**
