### PR TITLE
Don't try to build compiler-rt when cross-compiling

### PR DESCRIPTION
**Pull request by vedantk**
#### What's in this pull request?

This PR makes build-script skip building compiler-rt when cross-compiling.

A user has reported a build-time failure when building swift-compiler-rt along with `--cross-compile-tools-deployment-targets` set. We should have a workaround in place before investigating a longer-term fix.

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by vedantk** [comment]
@llvm-beanz Could you take a look?

**Comment by llvm-beanz** [comment]
The option you want to be turning Off is LLVM_TOOL_COMPILER_RT_BUILD. LLVM_BUILD_EXTERNAL_COMPILER_RT is just what controls whether or not you use an in-tree built clang.

**Comment by vedantk** [comment]
Updated. I think the bugfix to `false_true` should be its own commit. Is it ok apart from that?

**Comment by llvm-beanz** [comment]
LGTM.

**Pull request merged**
