### PR TITLE
benchmarks: Mark some unstable benchmarks as unstable.

### PR DESCRIPTION
**Pull request by eeckstein**
Which excludes them from the list of executed benchmarks.

And  remove legacy benchmark lists in Driver. They are not used anymore.

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
+1!

**Comment by eeckstein** [comment]
@swift-ci smoke test and merge

**Comment by eeckstein** [comment]
@swift-ci smoke test and merge

**Pull request merged**
