### PR TITLE
For Swift 3/4 mode, do not treat IUOs in illegal positions as Optionals.

### PR DESCRIPTION
**Pull request by rudkx**
Instead, just emit a deprecation warning and suggest switching to Optionals.

The old behavior caused several projects to break, so before we change
the behavior here we need to investigate whether we can mitigate most
of those breaks.

rdar://problem/35831769

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Review by DougGregor — APPROVED** [review]
LGTM, thank you!

**Comment by rudkx** [comment]
I missed updating one migrator input file.

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Pull request merged**
