### PR TITLE
SimplifyBeginCOWMutation: don't eliminate `end_cow_mutation` instructions with the `[keep_unique]` flag

### PR DESCRIPTION
**Pull request by eeckstein**
This flag is important for following optimizations. Therefore such `end_cow_mutation` instructions must not be removed.

rdar://119178823

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Review by meg-gupta — APPROVED** [review]
LGTM

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by eeckstein** [comment]
@swift-ci smoke test linux

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by eeckstein** [comment]
@swift-ci smoke test linux

**Pull request merged**
