### PR TITLE
[Sema] NFC: Simplify InOut asserts via boolean logic

### PR DESCRIPTION
**Pull request by davezarzycki**

### CODE REVIEW

**Comment by CodaFi** [comment]
Please don't futz with these quite yet.  I need the first layer to catch future invalid callers that set the flag but don't pass the base, and the second to catch current invalid callers that drop the flags and keep the type.

**Comment by CodaFi** [comment]
For future reference: This side of things is accompanies a representation change for function types where here we hope to eliminate `InOutType` in as many places as possible and represent it as a bit on a `Param` type that represents the input to a function arrow - see a lot of callers skittishly calling `getInOutObjectType()`.

**Comment by davezarzycki** [comment]
Right. I know that InOutType is going away. If you build a truth table (flag T/F, InOutType T/F), then you'll see that the first if+assert followed by the second if+assert ensures that the passed in type can never be InOutType, regardless of whether the flag is set. In other words, the future is closer than you might realize.

**Comment by CodaFi** [comment]
Right, but this scheme loses desired entropy; callers today get told which specific part of the contract they're not abiding by.  If there were a simplification to be had, it would be to merge the `if`s into the `assert`s.

**Pull request closed without merging**
