### PR TITLE
SILCombine: remove a problematic cast peephole optimization.

### PR DESCRIPTION
**Pull request by eeckstein**
This optimization inserted bit casts based on structural properties of types.
It caused a miscompile in case of imported C structs. Also, by inspection, I found that checks for resilient types are missing.
As this optimization does not have any noticeable impact on the benchmarks it's better to remove it at all, together with the complexity for checking the types.

rdar://problem/40074362

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by eeckstein** [comment]
@swift-ci smoke benchmark

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Review by atrick — APPROVED** [review]
I think it's great to remove this complexity.

I'm a little concerned that someone will try to add the unchecked_addr_cast -> unchecked_bit_cast optimization back later without realizing it's not generally valid. I'll look for a place to add some comments. Probably SIL.rst.

**Comment by shahmishal** [comment]
@swift-ci smoke test

**Comment by shahmishal** [comment]
@swift-ci smoke test

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by shahmishal** [comment]
@swift-ci smoke test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci smoke test

**Comment by shahmishal** [comment]
@swift-ci smoke test

**Comment by shahmishal** [comment]
@swift-ci smoke test

**Comment by shahmishal** [comment]
@swift-ci smoke test

**Pull request merged**
