### PR TITLE
build: duplicate and rename the `_add_variant_*` functions

### PR DESCRIPTION
**Pull request by compnerd**
This allows us to start splitting up the swift and C/C++ specific paths.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by compnerd** [comment]
CC: @drexin @gottesmm

**Comment by compnerd** [comment]
@swift-ci please clean test

**Review by drexin — APPROVED** [review]
LGTM

**Pull request merged**
