### PR TITLE
[Type checker] Don't check near-miss candidates of the wrong kind.

### PR DESCRIPTION
**Pull request by DougGregor**
Fixes rdar://problem/35832679.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by jrose-apple** [comment]
error: PR only contains test

**Comment by DougGregor** [comment]
Oh hey, at least we know I didn't fake the test.

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
