### PR TITLE
Replace old DEBUG macro with new LLVM_DEBUG

### PR DESCRIPTION
**Pull request by jrose-apple**
...using a sed command provided by Vedant:

```
$ find . -name \*.cpp -print -exec sed -i "" -E "s/ DEBUG\(/ LLVM_DEBUG(/g" {} \;
```

### CODE REVIEW

**Comment by jrose-apple** [comment]
apple/swift-llvm#104
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
DEBUG isn't gone yet, but if we switch to LLVM_DEBUG we'll stop breaking master-next. What do y'all think?

**Review by shajrawi — APPROVED** [review]
I'm fine with that sed command - see no reason to oppose such a change

**Review by rjmccall — APPROVED** [review]
Seems reasonable to me.

**Comment by gottesmm** [comment]
@jrose-apple This is the right approach. We should have done this some time ago to reduce the delta. Can we add something to the database to make sure no more sneak in?

**Comment by jrose-apple** [comment]
Hm…I can't think of an easy way to do it within the build. Normally I would think of poisoning the identifier somehow, but there might be uses of DEBUG in the LLVM or Clang headers. Still, I tagged the people who use it most frequently, so hopefully that'll help?

…I suppose we could add a test that does a git grep?

**Comment by gottesmm** [comment]
@jrose-apple I think that might work. If that becomes too difficult, I imagine we could write a clang plugin or something like that maybe? It would require us to on the bots also check out clang-tools-extra or something like that maybe, but given that cmake always create compilation databases, this is something we could do.

**Comment by jrose-apple** [comment]
Test turned out to be pretty easy, so I think we're good to go!

@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test macOS

**Pull request merged**
