### PR TITLE
[DeclChecker] Don't try to derive conformances for invalid enums

### PR DESCRIPTION
**Pull request by xedin**
If one of the cases is invalid, let's mark parent enum as invalid
as well, and avoid trying to derive any conformances related to it.

Resolves: rdar://problem/36989792

### CODE REVIEW

**Comment by jrose-apple** [comment]
Do we have to leave out the type, or would it be possible to mark it invalid without that? Would slightly improve the experience to still have a valid type around…but only if it's not going to lead to more crashes.

**Comment by xedin** [comment]
@swift-ci please smoke test

**Review by DougGregor — APPROVED** [review]
This version LGTM

**Pull request merged**
