### PR TITLE
5.6: Fix SR-15785 by adding a cached reference to the last linked list node, avoiding n^2 append scaling

### PR DESCRIPTION
**Pull request by Catfish-Man**
Explanation: Adding children to a TaskGroup is currently n^2, which is causing severe performance issues for users of Swift Concurrency.

Scope:  This change improves the performance of adding 50,000 children to a group from 10-15 seconds to less than 0.2 seconds. It costs one word of memory per child.

Radar/SR Issue: SR-15785 

Risk: If I got the change wrong we could potentially see crashes or other misbehavior when using TaskGroups

Testing: Test suite passes, community provided benchmark shows expected improvement

Reviewer: @DougGregor (I think you're the Concurrency code owner? CODE_OWNERS doesn't list it)

Original PR: https://github.com/apple/swift/pull/41165

### CODE REVIEW

**Comment by Catfish-Man** [comment]
@swift-ci please nominate

**Review by ktoso — APPROVED** [review]

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Comment by Catfish-Man** [comment]
@swift-ci please test windows platform

**Review by DougGregor — APPROVED** [review]

**Comment by Catfish-Man** [comment]
@swift-ci please test macOS platform

**Pull request merged**
