### PR TITLE
Swift 2.3 Apply deprecation warning fixits

### PR DESCRIPTION
**Pull request by benlangmuir**
#### What's in this pull request?

- Explanation:
  These commits enhance the Swift 2.3 JSON-fixit-rewriter to apply fixits from various deprecation warnings that provide useful migrations.  These are automatically applied by the Swift migrator when migrating to Swift 2.3.  Note: The ++ and C-style for-loop changes are implicitly accepted in the Swift 3 compiler because unlike in 2.3 they are errors.
- Scope of Issue: Affects anyone migrating to Swift 2.3.
- Risk: Low; only affects migration, not compilation
- Reviewed By: Argyrios
- Testing: Added regression tests.
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

rdar://problem/26678923

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by benlangmuir** [comment]
@akyrtzi could you review this for me?

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by akyrtzi** [comment]
LGTM!

**Comment by benlangmuir** [comment]
Linux failures are unrelated to this PR.

**Pull request merged**
