### PR TITLE
[CSSolver] NFC: Refactor `openGenericRequirements` to fix ASAN failure

### PR DESCRIPTION
**Pull request by xedin**

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please ASAN test

**Comment by slavapestov** [comment]
Well, its not NFC, because it fixes an ASAN failure :)

**Comment by xedin** [comment]
@slavapestov It's NFC because it makes it identical to how it used to look when it was a part of `openGeneric` :)

**Comment by xedin** [comment]
@swift-ci please smoke test

**Pull request merged**
