### PR TITLE
Split off StorageImplInfo from AccessorRecord

### PR DESCRIPTION
**Pull request by slavapestov**
This is in service of creating a request to compute AbstractStorageDecl::getStorageImplInfo(). Should be NFC.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Review by rjmccall — COMMENTED** [review]
It would be easier to review patches if you focused on one thing per PR instead of also throwing in a refactor of how we represent storage specifiers.

Please continue using a specifier enum on `VarDecl` instead of a boolean `isLet`; it's clearer in source and will allow minor extensions in this area (e.g. local shared/inout bindings) to avoid having to refactor it back.

The parts of the patch that are actually specific to the representation of `StorageImplInfo` in an AbstractStorageDecl seem reasonable.

**Comment by slavapestov** [comment]
https://github.com/apple/swift-lldb/pull/1820
@swift-ci Please test

**Comment by slavapestov** [comment]
@rjmccall Alright, I'm now using a new VarDecl::Introducer enum to distinguish `var` from `let`.

**Comment by slavapestov** [comment]
apple/swift-lldb#1820
@swift-ci Please test

**Comment by slavapestov** [comment]
apple/swift-lldb#1820
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
apple/swift-lldb#1820
@swift-ci Please test Linux

**Pull request merged**
