### PR TITLE
[Serialization] Handful of cleanups and possibly memory usage improvements

### PR DESCRIPTION
**Pull request by jrose-apple**
Tweak serialization and a few SIL structures for lower memory usage. In particular:
- Compact some types.
- Allow non-Identifiers to go in the string table, so that those strings don't get uniqued in the ASTContext too.

This is probably easiest to look at commit-by-commit.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test compiler performance

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Review by harlanhaskins — APPROVED** [review]

**Comment by slavapestov** [comment]
In theory we could use something like Identifier but allocated in the SIL bump allocator, but in any case this looks great.

**Comment by jrose-apple** [comment]
I thought about having a SILIdentifier, but the only time SIL looks things up by strings is when it gets them out of modules, and those have to be string-keyed anyway (unless we want to eagerly deserialize keys, or use something other than OnDiskHashTable).

**Comment by graydon** [comment]
@jrose-apple those are fascinating deltas. We're at least capturing the stats files and logs now, so I will check, thanks. I'm really unclear on what is causing them -- it doesn't just randomly make up numbers.

**Pull request merged**
