### PR TITLE
[ClangImporter] "Handle" the new ObjCTypeParamType.

### PR DESCRIPTION
**Pull request by jrose-apple**
"Handle" is in quotes because we're dropping protocols on the floor, i.e. we import `ElementType <NSCopying>` as if it were just `ElementType`. Why? Because that's how Swift 3 did it. (We'll fix this for Swift 4 if possible.)

This is written using a helper function so that it's not revlocked with Clang. There are no test changes here because everything breaks *without* this change when the corresponding Clang change goes in.

rdar://problem/28376996

### CODE REVIEW

**Comment by jrose-apple** [comment]
Test without the Clang change:

@swift-ci Please test

**Comment by DougGregor** [comment]
Thank you!

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test Linux platform

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@shahmishal, what happened to the Linux test?

**Comment by shahmishal** [comment]
@swift-ci Please smoke test Linux platform

**Pull request merged**
