### PR TITLE
 IRGen/Runtime: Reference field descriptor directly from type context descriptors.

### PR DESCRIPTION
**Pull request by jckarter**
This saves us some expensive cross-referencing and caching in the runtime, and lets us reclaim the `isReflectable` bit from the context descriptor flags (since a null field descriptor is a suitable and more accurate indicator of whether a type is reflectable).

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@tanner0101 Hopefully with this change, interpreting the type context descriptor format directly is straightforward enough that the Swift runtime doesn't need to provide infrastructure to cross-reference the type and field descriptors. Would you be able to work with this change?

**Review by rjmccall — APPROVED** [review]
Makes sense to me.

**Review by mikeash — APPROVED** [review]

**Review by xedin — APPROVED** [review]
Great! Not looking through the whole section worth of type descriptors helps a lot :)

I'm wondering though, we didn't we have it like that originally, do you recall?

**Comment by jckarter** [comment]
IIRC you were having circularity issues with IRGen previously when you tried this last year. I didn’t seem to run into any trouble this time, though, so hopefully we resolved those problems independently...

**Comment by xedin** [comment]
Ah right, I remember now... Thank you!

**Comment by slavapestov** [comment]
Nice!

**Pull request merged**
