### PR TITLE
[ScanDependency] Respect working directory set inside invocation

### PR DESCRIPTION
**Pull request by cachemeifyoucan**
Teach scanner to respect the working directory set in the invocation through scanner C API.

Also add test infrastructure to testing scanner from C API. Break up DependencyScan lib into two so the swift-scan-test and remain small without understanding swift AST.

rdar://127626011

### CODE REVIEW

**Comment by cachemeifyoucan** [comment]
@swift-ci please smoke test

**Comment by cachemeifyoucan** [comment]
@swift-ci please smoke test

**Comment by cachemeifyoucan** [comment]
@swift-ci please smoke test

**Comment by cachemeifyoucan** [comment]
@swift-ci please smoke test

**Comment by cachemeifyoucan** [comment]
ping

**Review by artemcm — APPROVED** [review]

**Comment by cachemeifyoucan** [comment]
@swift-ci please smoke test

**Pull request merged**
