### PR TITLE
[SourceKit/CursorInfo] Report the set of decls referenced in the symbol graph's "declarationFragments" field.

### PR DESCRIPTION
**Pull request by nathawes**
For each referenced decl, also report whether it is a system symbol and/or SPI, its access level, source language, file path, module name, and parent contexts.
 
Resolves rdar://75809521

### CODE REVIEW

**Comment by nathawes** [comment]
@swift-ci please test

**Review by bnbarham — APPROVED** [review]
LGTM

**Comment by nathawes** [comment]
@swift-ci please test

**Review by QuietMisdreavus — APPROVED** [review]
Symbol Graph side looks good. The only thing i would ask for is a doc comment on things like `Symbol::getFragmentInfo` so i can spend less time squinting at it next time to figure out what it does 🤣 Otherwise i like it!

**Comment by nathawes** [comment]
@swift-ci please test and merge

**Comment by nathawes** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by nathawes** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by nathawes** [comment]
@swift-ci please test macOS

**Comment by nathawes** [comment]
@swift-ci please test macOS

**Comment by nathawes** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Pull request merged**
