### PR TITLE
Make -disable-implicit-concurrency-module-import imply that the concurrency compat library should not be implicitly linked either

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by DougGregor — CHANGES_REQUESTED** [review]
I don't think this is the right direction. Disabling the implicit import of `_Concurrency` still allows you to import `_Concurrency` explicitly. Clients that want to disable both can pass `-disable-autolinking-runtime-compatibility-concurrency -disable-implicit-concurrency-module-import`

**Comment by kubamracek** [comment]
Abandoning in favor of <https://github.com/apple/swift/pull/39385>.

**Pull request closed without merging**
