### PR TITLE
swift-reflection-dump: fix -Wpessimizing-move warning

### PR DESCRIPTION
**Pull request by compnerd**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

  warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
    auto Expected = std::move(llvm::object::createBinary(binaryFileName)
                    ^
  note: remove std::move call here
    auto Expected = std::move(llvm::object::createBinary(binaryFilename)
                    ^~~~~~~~~

### CODE REVIEW

**Comment by jrose-apple** [comment]
Maybe *fix* -Wpessimizing-move warning? ;-)

@swift-ci Please test

**Comment by jrose-apple** [comment]
Let's try that again.

@swift-ci Please test.

**Comment by compnerd** [comment]
I don't think that the master-next support has ever worked:

Traceback (most recent call last):
  File "/Users/buildnode/jenkins/workspace/swift-PR-osx/swift/utils/update-checkout", line 164, in <module>
    sys.exit(main())
  File "/Users/buildnode/jenkins/workspace/swift-PR-osx/swift/utils/update-checkout", line 146, in main
    clone_with_ssh, branch, skip_history, args.skip_repository)
  File "/Users/buildnode/jenkins/workspace/swift-PR-osx/swift/utils/update-checkout", line 99, in obtain_additional_swift_sources
    repo_branch = NEXT_BRANCHES[dir_name]
KeyError: 'compiler-rt'

The dictionary is missing keys.  I can't remember the person who was working on the test infrastructure :-(.

**Comment by jrose-apple** [comment]
Ah, I didn't even notice that. I guess I'll trust the change on master-next to be correct, and then your change to be correct on top of that. Thanks.

**Pull request merged**
