### PR TITLE
Avoid reserving space for a breadcrumbs pointer when we know we won't need one

### PR DESCRIPTION
**Pull request by Catfish-Man**

### CODE REVIEW

**Comment by Catfish-Man** [comment]
@swift-ci please smoke test

**Comment by Catfish-Man** [comment]
@swift-ci please smoke benchmark

**Comment by milseman** [comment]
Just curious, is there any additional motivation for this change?

**Review by milseman — CHANGES_REQUESTED** [review]
Just curious, is there any additional motivation for this change?

The reason I ask is that this change seems incomplete and could be a regression. We're still asking for 8 more bytes from the allocator to store a breadcrumb pointer, so rounding up to a multiple of 16 still seems undesirable.

**Comment by milseman** [comment]
Let's see if we can find a more structured approach on that front. We also want to check/measure this in our testing.

**Pull request closed without merging**
