### PR TITLE
Adding swift.xcodeproj

### PR DESCRIPTION
**Pull request by amraboelela**

### CODE REVIEW

**Comment by amraboelela** [comment]
This would facilitate browsing / searching through Swift repo files.

**Comment by compnerd** [comment]
Please don't do this.  If you want to use Xcode, you can use the Xcode generator with cmake.

**Comment by amraboelela** [comment]
Ok, np, but may I know the reason?

**Comment by CodaFi** [comment]
> Ok, np, but may I know the reason?

Because the build system is perfectly capable of generating these kinds of projects on its own.  In addition, an Xcodeproj file, or any other project file for any other IDE, is not a database and would not facilitate indexing this project. 

It may actually be harmful to the project because it ties us to a hand-made project file that we would have to update and nitpick about every time a new version of the tools came around.  That said, I'm going to close this.

**Comment by amraboelela** [comment]
Ok, can we at least add xcode in the .gitignore so when I switch from my develop branch to master, I don't have to worry about deleting my xcode project (the I created) everytime?

**Comment by CodaFi** [comment]
If you build with `-x` the project files are generated in your build folder and we already have that ignored.

**Comment by gottesmm** [comment]
> On Oct 20, 2017, at 4:00 PM, Amr Aboelela <notifications@github.com> wrote:
> 
> Ok, can we at least add xcode in the .gitignore so when I switch from my develop branch to master, I don't have to worry about deleting my xcode project (the I created) everytime?
> 
> 

Are you doing an in-tree build? Please use out-of-tree builds in a build directory outside of the source tree. If you use build-script, it will do this for you.

**Comment by gottesmm** [comment]
(beat me to it)

**Comment by amraboelela** [comment]
I don't use xcode for building, I just use it for browsing, searching, editing, and commiting the files.

**Comment by jrose-apple** [comment]
While I too recommend the build-script-generated Xcode project (if you build with it once you get indexing and code completion), you can get the effect of a local gitignore by [editing .git/info/exclude](https://help.github.com/articles/ignoring-files/#explicit-repository-excludes).

**Comment by amraboelela** [comment]
This needs to be documented some where, how to ignore the *.xcodeproj or just add it to .gitignore

**Comment by CodaFi** [comment]
> This needs to be documented some where, how to ignore the *.xcodeproj or just add it to .gitignore

How do you mean?  I'm not so sure it makes sense to document this for non-standard configurations like yours - it'll lead to corner cases in the docs.  

Just use an in-tree build.  You don't even have to use Xcode to *build* the project and you'll get a much more complete, machine-generated version of the project that still lets you search and edit.

**Comment by compnerd** [comment]
It is documented in the man page for git.  It already covers how to exclude items without using the gitignore for the project.  You can globally ignore a pattern or individual names.

**Pull request closed without merging**
