### PR TITLE
[CopyForwarding] Removed destroy hoisting.

### PR DESCRIPTION
**Pull request by nate-chandler**
It has been replaced by the destroy hoisting in SSADestroyHoisting.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci benchmark

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
```
------- Performance (x86_64): -O -------

REGRESSION                            OLD    NEW    DELTA    RATIO    
ArrayAppendRepeatCol                  400    500    +25.0%   **0.80x (?)**
Breadcrumbs.MutatedUTF16ToIdx.Mixed   184    218    +18.5%   **0.84x (?)**
Breadcrumbs.MutatedIdxToUTF16.Mixed   188    222    +18.1%   **0.85x (?)**
StringBuilderSmallReservingCapacity   190    217    +14.2%   **0.88x (?)**
StringBuilder                         184    209    +13.6%   **0.88x (?)**
ArrayAppendLatin1                     1598   1802   +12.8%   **0.89x (?)**
ArrayAppendAscii                      1598   1768   +10.6%   **0.90x (?)**
StringUTF16Builder                    200    220    +10.0%   **0.91x (?)**
Set.isSubset.Seq.Empty.Int            74     81     +9.5%    **0.91x (?)**
Set.isStrictSubset.Box0               75     82     +9.3%    **0.91x (?)**
Set.isDisjoint.Seq.Empty.Box          81     88     +8.6%    **0.92x (?)**
StringAdder                           249    268    +7.6%    **0.93x (?)**

IMPROVEMENT                           OLD    NEW    DELTA    RATIO    
DictionaryBridgeToObjC_Access         655    600    -8.4%    **1.09x (?)**
Array2D                               4480   4160   -7.1%    **1.08x (?)**
StringHasSuffixAscii                  1590   1480   -6.9%    **1.07x (?)**

------- Code size: -O -------

IMPROVEMENT                                        OLD     NEW     DELTA   RATIO  
BinaryFloatingPointConversionFromBinaryInteger.o   30200   29608   -2.0%   **1.02x**


------- Performance (x86_64): -Osize -------

REGRESSION                            OLD    NEW    DELTA    RATIO    
FlattenListFlatMap                    2332   4220   +81.0%   **0.55x (?)**
ArrayAppendRepeatCol                  500    850    +70.0%   **0.59x (?)**
Breadcrumbs.MutatedUTF16ToIdx.Mixed   183    219    +19.7%   **0.84x (?)**
Breadcrumbs.MutatedIdxToUTF16.Mixed   189    223    +18.0%   **0.85x (?)**
StringBuilderSmallReservingCapacity   189    215    +13.8%   **0.88x (?)**
Set.isStrictSubset.Int0               72     80     +11.1%   **0.90x (?)**
Set.isSubset.Empty.Int                110    122    +10.9%   **0.90x (?)**
Set.isStrictSubset.Empty.Int          113    125    +10.6%   **0.90x (?)**
Set.isDisjoint.Seq.Empty.Int          79     87     +10.1%   **0.91x (?)**
StringUTF16Builder                    200    220    +10.0%   **0.91x (?)**
Set.isSubset.Seq.Empty.Int            74     81     +9.5%    **0.91x (?)**
Set.isStrictSubset.Box0               75     82     +9.3%    **0.91x (?)**

IMPROVEMENT                           OLD    NEW    DELTA    RATIO    
FlattenListLoop                       1586   1385   -12.7%   **1.15x (?)**
Set.subtracting.Empty.Int             31     28     -9.7%    **1.11x (?)**
RemoveWhereSwapInts                   23     21     -8.7%    **1.10x (?)**
RemoveWhereFilterInts                 25     23     -8.0%    **1.09x (?)**
Set.isStrictSubset.Int.Empty          38     35     -7.9%    **1.09x (?)**
ArrayInClass                          1230   1135   -7.7%    **1.08x (?)**
ArraySetElement                       330    305    -7.6%    **1.08x (?)**
DictionaryBridgeToObjC_Access         651    605    -7.1%    **1.08x (?)**
NormalizedIterator_slowerPrenormal    290    270    -6.9%    **1.07x (?)**

------- Code size: -Osize -------

IMPROVEMENT                                        OLD     NEW     DELTA   RATIO  
BinaryFloatingPointConversionFromBinaryInteger.o   29208   28613   -2.0%   **1.02x**

------- Performance (x86_64): -Onone -------

REGRESSION                             OLD     NEW     DELTA    RATIO    
Breadcrumbs.MutatedUTF16ToIdx.Mixed    187     222     +18.7%   **0.84x**
Breadcrumbs.MutatedIdxToUTF16.Mixed    198     233     +17.7%   **0.85x (?)**
ArrayOfPOD                             670     735     +9.7%    **0.91x (?)**

IMPROVEMENT                            OLD     NEW     DELTA    RATIO    
RandomDouble01LCG                      24386   21756   -10.8%   **1.12x (?)**
CharIteration_chinese_unicodeScalars   40920   38120   -6.8%    **1.07x (?)**

------- Code size: -swiftlibs -------
```

**Comment by atrick** [comment]
👍

**Pull request merged**
