### PR TITLE
[Sema] Adding deprecation warning for protocol inheritance 'class' syntax

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
Just come across this comment https://forums.swift.org/t/class-only-protocols-class-vs-anyobject/11507/15 on the forums and it seems like the idea is there for some time so this PR tries to address that. So let me know what you think :)

### CODE REVIEW

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test Linux platform

**Review by CodaFi — APPROVED** [review]
LGTM

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
