### PR TITLE
Update FileList tests to support both swift-driver and integrated driver

### PR DESCRIPTION
**Pull request by cltnschlosser**

### CODE REVIEW

**Comment by cltnschlosser** [comment]
@DougGregor @owenv

**Comment by owenv** [comment]
@cltnschlosser were you able to get this test working with swift-driver locally? The problem I ran into is that it uses test/Driver/Inputs/filelists/check-filelist-abc.py as a fake frontend, and when swift-driver tries to use -print-target-info it errors.

**Comment by owenv** [comment]
@swift-ci smoke test

**Comment by cltnschlosser** [comment]
> @cltnschlosser were you able to get this test working with swift-driver locally? The problem I ran into is that it uses test/Driver/Inputs/filelists/check-filelist-abc.py as a fake frontend, and when swift-driver tries to use -print-target-info it errors.

Yes, but before `-print-target-info` stuff was added. I've had this change sitting around for a while.

**Comment by owenv** [comment]
@cltnschlosser Oh, that makes sense. Out of curiosity, does this test cover any functionality that's not already tested by the unit tests you added to swift-driver? If not, we could mark it as `REQUIRES: cplusplus_driver` (which I just added in https://github.com/apple/swift/pull/33961), along with a comment explaining the test cases have been ported. My thinking is that because it's using this python script as a fake frontend, it's basically a unit test anyway, and it might be hard to fix the -print-target-info issue without some hard-to-maintain hacks. We can still pursue this if you think it'd be valuable though.

**Comment by cltnschlosser** [comment]
I just double checked and we don't have coverage for these tests. These are testing the save-temps functionality which isn't implemented in swift-driver at all yet. Everything else is covered though.
```
// RUN: (cd %t && env TMPDIR="%t/tmp/" %swiftc_driver_plain -driver-use-frontend-path %S/Inputs/filelists/check-filelist-abc.py -c ./a.swift ./b.swift ./c.swift -module-name main -target x86_64-apple-macosx10.9 -driver-filelist-threshold=0 -output-file-map=%S/Inputs/filelists/output.json -whole-module-optimization -num-threads 1 -save-temps 2>&1 | %FileCheck -check-prefix=CHECK-WMO-THREADED %s)
// RUN: ls %t/tmp/sources-* %t/tmp/outputs-*

// RUN: mkdir -p %t/tmp-fail/
// RUN: (cd %t && env TMPDIR="%t/tmp-fail/" not %swiftc_driver_plain -driver-use-frontend-path %S/Inputs/fail.py -c ./a.swift ./b.swift ./c.swift -module-name main -target x86_64-apple-macosx10.9 -driver-filelist-threshold=0 -output-file-map=%S/Inputs/filelists/output.json -whole-module-optimization -num-threads 1)
// RUN: not ls %t/tmp-fail/sources-*
// RUN: not ls %t/tmp-fail/outputs-*

// RUN: mkdir -p %t/tmp-crash/
// RUN: (cd %t && env TMPDIR="%t/tmp-crash/" not %swiftc_driver_plain -driver-use-frontend-path %S/Inputs/crash.py -c ./a.swift ./b.swift ./c.swift -module-name main -target x86_64-apple-macosx10.9 -driver-filelist-threshold=0 -output-file-map=%S/Inputs/filelists/output.json -whole-module-optimization -num-threads 1)
// RUN: ls %t/tmp-crash/sources-* %t/tmp-crash/outputs-*
```

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
