### PR TITLE
SimplifyCFG: fix an infinite jump-threading loop.

### PR DESCRIPTION
**Pull request by eeckstein**
The JumpThreadingCost map in Simplify CFG is used to prevent infinite jump threading loops.
There was a missing update of the cost for blocks which are cloned:
Jump threading loops were prevented for infinitely cloning the original block, but not for re-cloning the cloned block.

A test case is already added in https://github.com/apple/swift/pull/35604

rdar://73357726, [SR-14068]

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci test macOS

**Comment by eeckstein** [comment]
@swift-ci test macOS

**Comment by atrick** [comment]
It looks like you want to use `JumpThreadingCost` to be an accumulator on any block that has been cloned so that the current cost is the original cost multiplied by the number of clones. That's not obvious from the comments.

I do think it's a good idea to generally limit run-away jump-threading. But I'm still worried about small loops, so still like this safeguard: https://github.com/apple/swift/pull/35608

The thing that is particularly baffling to me is that this cost is initialized in `simplifyBranchBlock` which is unreliable.

**Review by atrick — APPROVED** [review]
This looks good to me. I'll merge this PR and add the necessary comments in a follow-up PR.

**Pull request merged**
