### PR TITLE
Fix IndexSet intersection and symmetric difference [SR-1818]

### PR DESCRIPTION
**Pull request by xwu**
#### What's in this pull request?

Previously, `IndexSet.isStrictSubset(of:)` was found to emit incorrect results. Namely,

```
IndexSet([0,2]).isStrictSubset(of: IndexSet([0,1,2]))
```

evaluates to `false`. This issue arises from how the private helper type `IndexSetBoundaryIterator` has been implemented, causing `IndexSet.intersection()` to start and end intersecting ranges incorrectly with certain inputs.

This PR modifies that type to always return lower bounds or one-past-the-end upper bounds, then corrects the implementation of `IndexSet.intersection()` and `IndexSet.symmetricDifference()` to start and end ranges correctly for all (valid) inputs. The result initially reported to be incorrect is consequently fixed.

Additional tests have been added for `intersection()` and `symmetricDifference()`.
#### Resolved bug number: ([SR-1818](https://bugs.swift.org/browse/SR-1818))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by xwu** [comment]
@phausler @parkera Since you guys commented on the bug or have worked on IndexSet, would you mind reviewing?

**Comment by parkera** [comment]
Thanks! I'll take a closer look today.

**Comment by parkera** [comment]
@swift-ci please test

**Comment by xwu** [comment]
OS X failure seems unrelated?

**Comment by parkera** [comment]
Agreed. Thanks for your work on this @xwu .

**Pull request merged**
