### PR TITLE
[SILGen] Fixed handler formal arg type indexing.

### PR DESCRIPTION
**Pull request by nate-chandler**
In the synthesized completion handler that is passed to ObjC methods that are called as async, the formal type of each argument is the corresponding parameter of the formal type of the block.  The non-error, non-index arguments need to be prepared so that they can be used to fulfill the continuation; the lambda which does that preparation for each such argument takes the formal type of that argument.  As such, the call to that lambda needs to pass the type of the corresponding parameter of the formal type of the block to that lambda.  Doing so entails skipping over the error and flag parameters if they appear before some of the non-error, non-index arguments.

Previously, no parameters were skipped over.  Consequently, when an error or flag argument preceded one of the non-error, non-index arguments, the wrong formal type was passed to the preparation lambda.

Here, that is fixed by passing the correct index.  The to-be-used indices for the formal block parameters are the same as the to-be-used indices for the lowered block parameters minus one reflecting the fact that the lowered block always has an initial block_storage parameter as the first argument which the formal type never has.

Based on https://github.com/apple/swift/pull/38773 .

rdar://81617749

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please clean test linux platform

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please clean test windows platform

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by jckarter — APPROVED** [review]
Looks good, thanks Nate!

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please clean test macos platform

**Pull request merged**
