### PR TITLE
[cxx-interop] Modularize __msvc_bit_utils on Windows

### PR DESCRIPTION
**Pull request by egorzhdan**
`__msvc_bit_utils.hpp` was added in a recent version of MSVC, and it is causing build errors for SwiftCompilerSources:
```
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\numeric:598:12: error: function '_Select_countr_zero_impl<unsigned long long, (lambda at C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\numeric:598:55)>' with deduced return type cannot be used before it is defined
    return _Select_countr_zero_impl<_Common_unsigned>([=](auto _Countr_zero_impl) {
```

This change references the `__msvc_bit_utils.hpp` header from the modulemap. Since we still need to support older versions of Visual Studio that do not provide `__msvc_bit_utils.hpp`, this also teaches ClangImporter to inject an empty header file named `__msvc_bit_utils.hpp` into the system include directory, unless it already exists.

rdar://137066642

### CODE REVIEW

**Comment by egorzhdan** [comment]
@swift-ci please test Windows

**Review by compnerd — COMMENTED** [review]
Won't this cause issues for older releases which didn't include the header?

**Comment by egorzhdan** [comment]
Yeah, it might – I was trying to use the Windows CI to see if we could get away with declaring a module with a single non-existent header. But it looks like the pull request CI uses a more recent version of Visual Studio 2022, where the header is already present.

**Comment by egorzhdan** [comment]
Looks like we can't have an empty submodule after all. Let me come up with an alternative solution.

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Review by Xazax-hun — APPROVED** [review]
LGTM!

**Review by compnerd — APPROVED** [review]

**Pull request merged**
