### PR TITLE
[embedded] Don't emit metadata references from C++ interop

### PR DESCRIPTION
**Pull request by kubamracek**
This resolves a compiler crash when using C++ interop in Embedded Swift:
```
Assertion failed: (LazyTypeMetadata.empty()), function emitLazyDefinitions, file GenDecl.cpp, line 1330.
...
8  swift-frontend           0x000000010093cf60 swift::irgen::IRGenerator::emitLazyDefinitions() + 3212
9  swift-frontend           0x0000000100a580f8 swift::IRGenRequest::evaluate(swift::Evaluator&, swift::IRGenDescriptor) const + 2632
10 swift-frontend           0x0000000100aa64a4 swift::GeneratedModule swift::SimpleRequest<swift::IRGenRequest, swift::GeneratedModule (swift::IRGenDescriptor), (swift::RequestFlags)17>::callDerived<0ul>(swift::Evaluator&, std::__1::integer_sequence<unsigned long, 0ul>) const + 200
```

### CODE REVIEW

**Review by eeckstein — APPROVED** [review]

**Review by egorzhdan — APPROVED** [review]
LGTM!

**Review by Xazax-hun — APPROVED** [review]
LGTM!

**Comment by kubamracek** [comment]
Added a test that reproduces the compiler crash.

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Pull request merged**
