### PR TITLE
[lib/Parse] #58741 Do not suggest moving `any` or `some` to the beginning of a compositi…

### LINKED ISSUE #58741: Fix-it for repeated `any` and `some` in composition results in incorrect code
**Describe the bug**

When `some` or `any` appear within a composition instead of at the beginning, the compiler suggests moving the keyword to the beginning. If either of the keywords already appear at the beginning of the composition, the code after the application of the fix-it will be syntactically incorrect.

**To Reproduce**

Consider the following example:
```
protocol P1 {}
protocol P2 {}
struct S: P1, P2 {}

let _: any P1 & any P2
let x: some P1 & some P2 = S()
```

Applying the suggested fix-its results in the following code:
```
protocol P1 {}
protocol P2 {}
struct S: P1, P2 {}

let _: any any P1 & P2
let x: some some P1 & P2 = S()
```

**Expected behavior**

The compiler knows enough to propose the following code:
```
let _: any P1 & P2
let x: some P1 & P2 = S()
```

**Additional context**

The compiler currently also proposes moving misplaced keywords to the beginning if both `some` and `any` are used in the same composition. I think it is at least debatable if this behaviour adds any value.

### PR DESCRIPTION
**Pull request by moritzdietsche**
…on if the first type is already an existential or opaque type.

When `some` or `any` appear within a composition instead of at the beginning, the compiler suggests moving the keyword to the beginning. If either of the keywords already appear at the beginning of the composition, the code after the application of the fix-it will be syntactically incorrect.

This change checks if `some` or `any` are already specified at the beginning of the composition and, if yes, simply suggests to remove the occurrence within the composition instead of moving it to the beginning

Resolves https://github.com/apple/swift/issues/58741.

### CODE REVIEW

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test

**Review by hborla — APPROVED** [review]
Sorry for the late review, looks great to me!

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by LucianoPAlmeida** [comment]
⛵

**Comment by hborla** [comment]
@LucianoPAlmeida @moritzdietsche are either of you interested in cherry-picking this to the `release/5.7` branch?

**Comment by LucianoPAlmeida** [comment]
Sure, I can do it real quick =]

**Comment by LucianoPAlmeida** [comment]
Done :)

**Pull request merged**
