### PR TITLE
Parse: explicitly state ordering of parsing (NFC)

### PR DESCRIPTION
**Pull request by compnerd**
When the parameters are inlined, with optimizations, the evaluation
order is under specified (with MSVC, the arguments are evaluated right
to left rather than left to right).  This results in the arguments being
processed incorrectly.  Create local variables to enforce the ordering
of the processed tokens.  Fixes the build on Windows with optimizations.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @rintaro

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by slavapestov** [comment]
This is not NFC since it fixes the build on Windows! :)

**Comment by compnerd** [comment]
@slavapestov hah, fair point :)

**Comment by rintaro** [comment]
Thank you Saleem!

**Pull request merged**
