### PR TITLE
[silgenpattern] Fix the box handling in the old silgenpattern enum co…

### PR DESCRIPTION
**Pull request by gottesmm**
…de to not pass a load_borrow payload as BorrowAlways instead of TakeAlways.

Thanks to Luiz Fernando Silva for the test case!

SR-9871
rdar://problem/47852446

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Review by jckarter — APPROVED** [review]
Looks good, thanks Michael!

**Comment by gottesmm** [comment]
Hmmm... looks like on Linux we are leaking protocol descriptors?! That is not this bug... I will see if I can turn off that check on linux and create a separate PR with a separate test that checks for that leak that is XFAILed.

**Comment by gottesmm** [comment]
Disabled leaks checking in the asan test.

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Pull request merged**
