### PR TITLE
Fix calling convention mismatch on `Builtin.getCurrentAsyncTask`

### PR DESCRIPTION
**Pull request by kateinoigakukun**
`Builtin.getCurrentAsyncTask` emits a call of `swift_task_getCurrent`.
User code can declare the same name function with slightly different signature at LLVM level (data size should be same) using @_silgen_name. 

Task.swift declares to be `() -> Builtin.NativeObject?`,
https://github.com/apple/swift/blob/90c1fece9ed6d2fea90ef5a2f72a3df3d13d99e5/stdlib/public/Concurrency/Task.swift#L666-L667

but `Builtin.getCurrentAsyncTask` is `() -> Builtin.NativeObject` and used here.

https://github.com/apple/swift/blob/90c1fece9ed6d2fea90ef5a2f72a3df3d13d99e5/stdlib/public/Concurrency/TaskCancellation.swift#L35

In that case, IRGen inserts a cast inst to cast the function to the expected signature. But this cast inst drops calling convention info, so call inst was emitted without swiftcc.
This results that the `Builtin.getCurrentAsyncTask` was lowered to a call of `swift_task_getCurrent` without swiftcc.

This patch changed to emit a call of swift_task_getCurrent with the explicit calling convention.

This convention mismatch was found by strict signature checking of Wasm.

CC: @MaxDesiatov , @rjmccall 

Resolves SR-NNNN.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci please test Windows platform

**Review by ktoso — APPROVED** [review]
This looks correct to me, thank you!

I'll double check with someone fluent in IRGen just to be safe though

**Review by varungandhi-apple — APPROVED** [review]
This looks correct based on:

```
/// Return the current thread's active task reference.
SWIFT_EXPORT_FROM(swift_Concurrency) SWIFT_CC(swift)
AsyncTask *swift_task_getCurrent(void);
```

🚢

**Pull request merged**
