### PR TITLE
Revert recursive protocol constraints changes

### PR DESCRIPTION
**Pull request by rudkx**
The type checking time for Swift.o is more than three times longer than it was before these changes. Backing out until Doug has a chance to take a look.

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test and merge

**Comment by rudkx** [comment]
@shahmishal Mishal, any idea why this would have picked up changes from @harlanhaskins PR? He tells me these changes aren't in master yet. https://ci.swift.org/job/swift-PR-osx-smoke-test/9474/

**Comment by rudkx** [comment]
@swift-ci Please smoke test OS X platform

**Comment by johnno1962** [comment]
Not sure this was the problem. I’ve building https://github.com/SwiftJava using a toolchain from master over the last few days. Xcode9b3 5mins build time. Before this revert 9 mins. After this revert 11 mins.

**Comment by rudkx** [comment]
I verified before backing this out that https://github.com/apple/swift/commit/ded45a6e1c498e69e56f38ddf32c8942f407db8c was the cause of the 3x slow-down in building the stdlib.

I don't know how much generic code SwiftJava has, but the stdlib uses generics extensively and it would not be surprising to me that changes to the handling of generics that substantially regress the build time for the stdlib would not also regress the build time for other projects.

**Comment by johnno1962** [comment]
I may be wrong, this code doesn’t use generics at all. I’m just noticing that a toolchain built with utils/build-toolchain on master seems a lot slower than the last beta. Would that be expected?

**Comment by rudkx** [comment]
Yes. Toolchains are built with assertions and more expensive verification code enabled.

**Comment by johnno1962** [comment]
Ah, ok. Sorry for the noise.

**Pull request merged**
