### PR TITLE
[Test] Don't test _swift_willThrow on older runtimes.

### PR DESCRIPTION
**Pull request by mikeash**
rdar://problem/56752866

### CODE REVIEW

**Comment by mikeash** [comment]
@swift-ci please test and merge

**Comment by mikeash** [comment]
@swift-ci please test linux platform

**Comment by mikeash** [comment]
@swift-ci please test linux platform

**Comment by benlangmuir** [comment]
This passed all the interesting tests.  Merging to fix CI sooner.

**Pull request merged**
