### PR TITLE
Broaden the set of benchmarks tagged under .cpubench

### PR DESCRIPTION
**Pull request by atrick**
These have all shown to be interesting, relevant, stable, and
optimized well enough by the compiler to be useful for cpu performance
tracking.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci benchmark

**Comment by govom2p** [comment]
Can you help me change to vietnames language github board because I am not familiar with this application and have language weaknesses

**Comment by govom2p** [comment]
> ### Performance: -O
> 
> 
> ### Code size: -O
> 
> 
> ### Performance: -Osize
> 
> **Improvement**      | **OLD** | **NEW** | **DELTA** | **RATIO**
> :---                 | ---: | ---: | ---:   | ---:     
> ParseFloat.Float.Exp | 10  | 9   | -10.0% | **1.11x (?)**
> 
> ### Code size: -Osize
> 
> 
> ### Performance: -Onone
> 
> **Regression** | **OLD** | **NEW** | **DELTA** | **RATIO**
> :---      | ---: | ---: | ---:  | ---:     
> TypeFlood | 139 | 150 | +7.9% | **0.93x (?)**
> 
> ### Code size: -swiftlibs
> 
> 
> 
> <details>
>   <summary><strong>How to read the data</strong></summary>
> The tables contain differences in performance which are larger than 8% and
> differences in code size which are larger than 1%.
> 
> If you see any unexpected regressions, you should consider fixing the
> regressions before you merge the PR.
> 
> **Noise**: Sometimes the performance results (not code size!) contain false
> alarms. Unexpected regressions which are marked with '(?)' are probably noise.
> If you see regressions which you cannot explain you can try to run the
> benchmarks again. If regressions still show up, please consult with the
> performance team (@eeckstein).
> </details>
> 
> <details>
>   <summary><strong>Hardware Overview</strong></summary>
> 
>       Model Name: Mac mini
>       Model Identifier: Macmini8,1
>       Processor Name: 6-Core Intel Core i7
>       Processor Speed: 3.2 GHz
>       Number of Processors: 1
>       Total Number of Cores: 6
>       L2 Cache (per Core): 256 KB
>       L3 Cache: 12 MB
>       Memory: 64 GB
> 
> </details>

**Comment by atrick** [comment]
@swift-ci smoke test and merge

**Pull request merged**
