### PR TITLE
SILOptimizer: move DestroyHoisting out of the mandatory pipeline

### PR DESCRIPTION
**Pull request by gottesmm**
Now that we have OSSA also in the early stage of the -O pipeline, we can do DestroyHoisting there.

----

Patch from ErikE here: #36401. Just moved destroy hoisting after semantic arc opts so we can look at the perf impact.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
Talked with @atrick. I am going to still keep destroy hoisting turned off behind lexical lifetimes.

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci build toolchain

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
Looks like the earlier benchmark results are bogus due to a mistake I made. I am going to delete them and re-benchmark with my new small optimization.

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
I looked at DataCreateEmptyArray. The inner loop is the same except for the address of some globals in the inner loop. I have a feeling what happened here is I slightly churned the code-size and messed with alignment of global variables or something like that.

I am going to take a quick look at the small code-size changes to see if I can do something there.

**Comment by gottesmm** [comment]
FlattenListLoop also has an unchanged kernel

**Comment by gottesmm** [comment]
StringBuilderLong also has the same inner kernel

**Review by eeckstein — CHANGES_REQUESTED** [review]
Can you please add a top-level comment somewhere with a simple SIL example to show what this optimization does?
It's really hard to understand the code without an idea what it should do.

**Comment by eeckstein** [comment]
Nice work, BTW. I love to see DestroyHoisting be moved out of the mandatory pipeline.

**Pull request closed without merging**
