### PR TITLE
[Runtime][Stdlib][Overlays] Rename various Objective-C classes and methods to avoid conflicts.

### PR DESCRIPTION
**Pull request by mikeash**
These classes and methods would conflict when loading old Swift libraries into a process alongside ABI-stable libraries.

rdar://problem/35768222

### CODE REVIEW

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by parkera** [comment]
Do you think it might be useful to use something besides an additional `_` to indicate new vs old? That could get extremely confusing when looking at backtraces or other metadata.

**Comment by mikeash** [comment]
I'm torn between the desire to more clearly distinguish between old and new, and the desire to keep things short and simple for what will soon be the common case of only having the new stuff loaded. I don't want some `ABIStableSwift` prefix littering crash logs years down the line. If you have any ideas that would be a better compromise I'm open to ideas. I made a small script to handle the renaming so it's easy to redo it with a different scheme.

**Comment by parkera** [comment]
Maybe it would be sufficient to note somewhere near the `@interface` for these that the single-underscore version of that name is reserved for old runtimes, so we don't accidentally introduce a conflict sometime in the future.

**Comment by mikeash** [comment]
That definitely sounds like a wise idea to me.

**Comment by mikeash** [comment]
https://github.com/apple/swift-lldb/pull/911
https://github.com/apple/swift-corelibs-foundation/pull/1696

@swift-ci please test

**Comment by mikeash** [comment]
(I'm just checking to see if this will pass PR testing, I'll be sure to add those comments before I actually merge.)

**Comment by mikeash** [comment]
apple/swift-lldb#911
apple/swift-corelibs-foundation#1696

@swift-ci please test

**Comment by mikeash** [comment]
apple/swift-lldb#911
apple/swift-corelibs-foundation#1696

@swift-ci please test OS X platform

**Comment by mikeash** [comment]
apple/swift-lldb#911
apple/swift-corelibs-foundation#1696

@swift-ci please test OS X platform

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
apple/swift-lldb#911
apple/swift-corelibs-foundation#1696

@swift-ci please test

**Pull request merged**
