### PR TITLE
Revert "Build workaround: only consider shims to be protected in Swif…

### PR DESCRIPTION
**Pull request by compnerd**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

…t code on Darwin."

This reverts commit 3e20817f8cb4cb56fd30ccb6bf1648ad4e780377.  Now that we are
using gold, this should work.  The work around is only needed for BFD linkers.

### CODE REVIEW

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by gribozavr** [comment]
@compnerd It looks like we have more failures than we have on Linux on the master branch.  Do you think this is unrelated?

**Comment by compnerd** [comment]
The errors look like swift-package errors?  I don't think that they would be related.  Errors from this would appear in the build of swiftCore.so.

**Comment by gribozavr** [comment]
Yes, but there are more of them than we see on master.  On master there are just two.  Let's re-run.

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by gribozavr** [comment]
This time we have only two failures, so never mind!

**Comment by compnerd** [comment]
Ping?

**Comment by modocache** [comment]
Another win thanks to #2609 -- thanks @compnerd! Does anyone have any additional thoughts here? If not I'll merge once the tests pass. /cc @gribozavr

@swift-ci please test

**Comment by gribozavr** [comment]
Sorry, this is in my review queue.  I want to make sure I understand what is this macro controlling and what we would be changing.

**Comment by compnerd** [comment]
@gribozavr the macro is controlling an indicator to the compiler that the current module being compiled is swiftCore, and in that case, we can consider the interfaces declared in the shims to have protected visibility on ELF.  This basically means that the symbols are externally visible, but cannot be interpositioned.  ELF defaults to all external symbols being interpositionable, but that is something which does not make sense for the shims.

**Comment by gribozavr** [comment]
LGTM, sorry it took so long!

@swift-ci Please smoke test and merge

**Pull request merged**
