### PR TITLE
Add access marker removal to AccessEnforcementOpts.

### PR DESCRIPTION
**Pull request by atrick**
Still looking at test cases and benchmarks.

### CODE REVIEW

**Comment by atrick** [comment]
FYI @shajrawi.

**Review by shajrawi — COMMENTED** [review]
Current changes LGTM! Need to add test-cases of course.

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
@swift-ci benchmark.

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
@swift-ci benchmark.

**Comment by atrick** [comment]
The benchmark results above aren't meaningful. With exclusivity enabled, this optimization improves the "MultiFile" benchmarks by 10%. This pass only removes local access markers when either:
(a) static diagnostics sees escaping access, but closures are subsequently inlined by the optimization pipeline.
(b) static diagnostics sees escaping access, but none of the local accesses span a call site.

**Comment by jrose-apple** [comment]
Looks like this broke the debug stdlib: https://ci.swift.org/view/Dashboard/job/oss-swift_tools-RA_stdlib-DA_test-simulator/295/. Are you going to have time to look at this or should I revert?

**Comment by atrick** [comment]
I'll look at it now, but revert the aggressive verification in the meantime.

**Comment by atrick** [comment]
Attempting to revert the verifier change here: https://github.com/apple/swift/pull/16823

**Pull request merged**
