### PR TITLE
[4.2] enforce keypath exclusivity as error

### PR DESCRIPTION
**Pull request by atrick**
It turns out that it's necessary to special case exclusivity Builtins and add flags to SIL instructions because of a couple circumstances:

Swift 3 mode exclusivity warnings will continue to be warnings.
The standard library will continue building in Swift 3 mode (for the foreseeable future).

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test.

**Comment by gottesmm** [comment]
LGTM

**Review by gottesmm — APPROVED** [review]

**Comment by atrick** [comment]
=== CCC Information ===

Explanation: All exclusivity violations should be errors in Swift 4.2
when building in Swift 4 mode. This was not yet true for KeyPaths
because they are enforced at runtime within the standard library which
still builds in Swift 3 mode.

Scope of Issue: Code that uses KeyPaths in a way that violates
exclusivity will now trap at runtime with detailed diagnostics.

KeyPaths are a Swift 4 language feature. However, it is possible that
projects are still building in Swift 3 mode but have added KeyPaths to
the project. KeyPath exclusivity violations will now be reported at
runtime as errors regardless of the language mode. This is necessary
for Swift 4 projects, and desirable for Swift 3 projects.

Origination: Both the KeyPath and exclusivity feature were introduced
in Swift 4.0, but KeyPaths that violated exclusivity were not
enforced. In 4.2 we recently introduced enforcement of KeyPath
exclusivity, but it was still only a warning:

commit 08e66246896889f9d06c5a7994a25d3730075800
Merge: 9a8a9d44b9 abab49e54c
Author: Andrew Trick <atrick@apple.com>
Date:   Fri Apr 20 08:29:01 2018

    Merge pull request #16051 from atrick/exclusive-key-path-fix
    
    [Exclusivity] Enforce exclusive access for class offsets in KeyPaths


Risk: Swift 3 mode projects that violate exclusivity with KeyPaths
could now trap at runtime with detailed diagnostics. This is a
desirable outcome anyway, since this code needs to be fixed.

Reviewed By: Michael Gottesman

Testing: Several unit tests are checked in. We have bots that test the
SCK with a special exclusivity verification mode.

Directions for QA:  N/A

**Comment by atrick** [comment]
rdar://40115738 [Exclusivity] Enforce Keypath access as an error, not a warning in 4.2.

**Pull request merged**
