### PR TITLE
SILCombine and SIL adjustFunctionType fix for @callee_guaranteed

### PR DESCRIPTION
**Pull request by aschwaighofer**
- SIL: Make adjustFunction type of closures parameterized on whether we use
guaranteed closures
This is going to go away once we change the default to guaranteed
closures.

- SILCombine: Fix @callee_guaranteed combine of try_apply
I missed another place where we were releasing the context.

SR-5441
rdar://33255593

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by shahmishal** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test macos

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test macos

**Comment by aschwaighofer** [comment]
@swift-ci Please test macOS

**Pull request merged**
