### PR TITLE
[Typechecker] Check conforming protocols of context when resolving a custom attribute

### PR DESCRIPTION
**Pull request by theblixguy**
When we try to resolve a custom attribute, we do not look into the protocols that the context conforms to. For example:

```swift
@propertyWrapper
struct S {
  var wrappedValue: Int
}

protocol P {
  typealias Wrapper = S
}

struct C: P {
  @Wrapper var answer = 42 // error: unknown attribute 'Wrapper'
}
```

This is because `CustomAttrNominalRequest` calls into `directReferencesForUnqualifiedTypeLookup`, which does unqualified lookup but ignores protocol members, which means if the user has defined a typealias inside the protocol then we will fail to find it and throw an error instead.

Resolves [SR-11288](https://bugs.swift.org/browse/SR-11288), [SR-11131](https://bugs.swift.org/browse/SR-11131) and [SR-11120](https://bugs.swift.org/browse/SR-11120).
Resolves rdar://problem/53107788
Resolves rdar://problem/53107270

### CODE REVIEW

**Comment by theblixguy** [comment]
> What happens if it finds an associated type? (Ignoring requirements is why ignoring protocol members is the default.)

Nothing happens... I mean until you try to use the `associatedtype` as a wrapper, in which case you'll get `error: unknown attribute 'AssocType'` (if it has a default value) or `cannot be used as an attribute` (if you add a typealias) error.

**Comment by theblixguy** [comment]
I suppose we could filter out associated types if it could be problematic.

**Comment by jrose-apple** [comment]
(I confess I'm waiting for one of the other tagged reviewers to chime in.)

**Comment by theblixguy** [comment]
@DougGregor @slavapestov do you have a moment to take a look at this? Apologies if you are busy. Thank you!

**Review by DougGregor — APPROVED** [review]
This looks right to me, thank you!

**Review by DougGregor — COMMENTED** [review]
Actually, a few comments:

* I think we should make sure we reject the attribute if it refers to an associated type; we don't want associated type resolution to be involved in attribute resolution
* Please test that we get reasonable behavior when the type alias is in a constrained protocol extension
* Please test that we get reasonable behavior when the type that conforms to the protocol is generic

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by theblixguy** [comment]
@swift-ci please smoke test

**Comment by tanner0101** [comment]
I just tested this on `swift-DEVELOPMENT-SNAPSHOT-2019-09-04` and it works great. 👍 This is the final piece I needed to get property wrappers working for my use case. Thanks, @theblixguy! 

@DougGregor / @jrose-apple will this be cherry picked into `swift-5.1-branch`?

**Comment by theblixguy** [comment]
I think it's probably too late to get this cherry-picked (only critical bug fixes are eligible as far as I know), but I'll leave the decision to Jordan/Doug.

**Comment by tanner0101** [comment]
@theblixguy does this patch rely on anything else that was on master or could it be applied directly to 5.1?

**Comment by theblixguy** [comment]
It can be applied to 5.1 without any issues, but the criteria for acceptance is much more strict since we're close to release. As I said, the final decision lies with the Swift team.

**Comment by tanner0101** [comment]
@theblixguy ok that makes sense. 👍 

To the Swift team: At least for me, this bug is critical. I can't make use of property wrappers correctly until it is fixed. Especially given how small this change is, I think it makes sense to merge into 5.1. Thanks!

**Comment by jrose-apple** [comment]
It's definitely too risky to take for 5.1.0 at this point, but perhaps a point-release. Can you elaborate on your use case? Anything that's about typealiases always has a workaround, so I don't see how it could be "critical".

**Comment by tanner0101** [comment]
@jrose-apple that's unfortunate, but understandable. I think I'll need to wait for Swift 5.2 then as I'm not sure I can make a specific patch release a minimum version requirement for my package.

My use case (for the server-side Swift packages [vapor/vapor](https://github.com/vapor/vapor) and [vapor/fluent](https://github.com/vapor/fluent)) looks something like this:

```swift
protocol Model { }

@propertyWrapper
struct ModelField<Root, Value> 
    where Root: Model, Value: Codable
{
    // access to `Root` in this scope is valuable
    var wrappedValue: Value { ... }
}

extension Model {
    typealias Field<Value> = ModelField<Self, Value>
}

struct User: Model {
    @Field var name: String
}
```

The `typealias` allows for just `@Field` to be inside the model declaration. This keeps a concise API while allowing for the actual property wrapper to still get strong type information on the root type. 

This doesn't work properly on 5.1 since the property wrapper lookup doesn't see type aliases.

**Pull request merged**
