### PR TITLE
[DO NOT MERGE] Refactoring Generics (GenericParamList)

### PR DESCRIPTION
**Pull request by technicated**
As stated in [this](https://forums.swift.org/t/starting-to-implement-variadic-generics/21159/5) thread on the Swift Forums, before introducing Variadic Generics we might want to refactor a little bit how generics are handled in the compiler, one piece at a time.

This PR is about two things:
1) it introduces a new type, `GenericParam`, which is a wrapper class+enum for any kind of generic parameter declaration (for now, only `GenericTypeParamDecl`)
2) it (mainly) edits `GenericParamList` to use `GenericParam` instead of `GenericTypeParamDecl`s. Code that depends on it has been changed as well.

~~The new type `GenericParam` has no code comments attached to it, might want to write them before merging this PR.~~

### CODE REVIEW

**Comment by technicated** [comment]
@DougGregor may I tag you here?

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by CodaFi** [comment]
@technicated It's been quite a while since there was any movement here. Do you still want us to hold this open?

**Comment by technicated** [comment]
@CodaFi unfortunately I've not been able to work on this lately - but in the meanwhile, I've tried to formalise a complete pitch for Variadic Generics. The code for this initial refactor might to be stale, I don't know how much the compiler has changed in this area since last year... there seems to be a lot of conflicts. Could it be better to start a new branch in the future (even to repurpose the same changes, if possible / useful)? I hope I can still put my effort on this once things settle down for me...

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
