### PR TITLE
Fix a bunch of python lint errors

### PR DESCRIPTION
**Pull request by tbkka**
Python 3 lint seems to catch a lot more issues than Python 2 lint.

This PR contains fixes for a number of them.  The issues include:
* Use of `l` as a variable name.  This is easily confused with `1` or `I`.  (Python_lint also complains about `O` as a variable name for the same reason.)
* Unused variable names.
* Missing parentheses in `print()` statements (these are required in python 3)

### CODE REVIEW

**Comment by tbkka** [comment]
@swift-ci Please test

**Comment by CodaFi** [comment]
@swift-ci python lint

**Comment by CodaFi** [comment]
> ./utils/protocol_graph.py:190:9: E128 continuation line under-indented for visual indent

**Comment by tbkka** [comment]
@swift-ci python lint

**Comment by CodaFi** [comment]
@swift-ci python lint

**Comment by tbkka** [comment]
@swift-ci Please test

**Comment by tbkka** [comment]
@CodaFi There are about a dozen more issues still to be fixed before Python 3 lint is happy with this.  Once that's done, it would be great to get the "python lint" CI updated to use Python 3 lint.

**Comment by shahmishal** [comment]
@swift-ci Please test windows

**Comment by shahmishal** [comment]
@swift-ci Please test windows

**Comment by shahmishal** [comment]
@swift-ci Please test windows

**Pull request merged**
