### PR TITLE
build: support cross-compiling to windows

### PR DESCRIPTION
**Pull request by compnerd**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @gribozavr 

This is mostly a preliminary change.  The ABI issue is blocking this.  There is a small wrinkle in this patch that the library name for ICU doesnt match exactly by default.  So you end up having to create a symlink (or rename the import library).  Additionally, 2 symlinks are currently needed due to the module map handling for MSVCRT.  Beyond that, this is sufficient to cross-compiling Windows on Linux.

I wanted to put this up here since it is a slightly larger change.  I wanted to get your opinion on the changes here and see if there is a better way to approach it.

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by CodaFi** [comment]
@swift-ci please test Linux platform.

**Comment by CodaFi** [comment]
:boom: :camel:

**Pull request merged**
