### PR TITLE
[ownership] init_existential_ref is not forwarding: it should only tr…

### PR DESCRIPTION
**Pull request by gottesmm**
…affic in owned values.

This was true already on the ValueOwnership side. This was exposed by a test in
test/Interpreter/FunctionConversions.swift where we emitted SIL like the test
for this PR.

rdar://43398898

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Review by atrick — APPROVED** [review]
Makes sense to me.

**Comment by gottesmm** [comment]
This hit an ordering problem with #21099. I need to get that in first.

**Comment by gottesmm** [comment]
I fixed this in a different PR.

**Pull request closed without merging**
