### PR TITLE
TODO: This is not require anymore. Remove it + Zapping missing serializeAll parameter

### PR DESCRIPTION
**Pull request by gabrielPeart**
Removing the missing part of the scope.
Thank you Nadav and Chris for the information.

### CODE REVIEW

**Comment by nadavrot** [comment]
@gabrielPeart Did you compile this code and run all of the tests (swift check-all) ?

**Comment by nadavrot** [comment]
@gabrielPeart Please squash these commits into a single commit, and if the tests pass I will merge the pull request.

**Comment by gabrielPeart** [comment]
@nadavrot Sorry about the delay! Yes, all tests pass and was possible to build the code.

**Comment by nadavrot** [comment]
@gabrielPeart Please squash all of the changes into a single commit (I think that you need to create a new pull request) and assign it to @gottesmm for review.

**Comment by gabrielPeart** [comment]
@nadavrot  I'm going to close this pull request and open a new one, is that okay?

**Comment by nadavrot** [comment]
@gabrielPeart perfect.

**Comment by jrose-apple** [comment]
For future reference, you can update an existing pull request by force-pushing to the same branch.

**Comment by gabrielPeart** [comment]
Thank you @jrose-apple

**Pull request closed without merging**
