### PR TITLE
Move TempRValueOpt from CopyForwarding.cpp -> TempRValueElimination.cpp.

### PR DESCRIPTION
**Pull request by gottesmm**
The pass is standalone from CopyForwarding and is big enough to stand on its
own.

This changes is NFC beyond clang-format + xcode rename.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
Fixed a typo.

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by atrick** [comment]
thanks... been meaning to do this

**Pull request merged**
