### PR TITLE
[syntax parser] Fix another assertion hit related to invalid composition type

### PR DESCRIPTION
**Pull request by akyrtzi**
Found by the stress tester.

### CODE REVIEW

**Comment by akyrtzi** [comment]
@swift-ci smoke test and merge

**Comment by compnerd** [comment]
This causes a regression on Windows!   Seems that the compiler is crashing on Windows :-(.

**Comment by akyrtzi** [comment]
I seriously doubt that these changes introduced the crash. Could you file a JIRA with details of the crash ?

**Comment by akyrtzi** [comment]
> I seriously doubt that these changes introduced the crash. Could you file a JIRA with details of the crash ?

To clarify, if we revert this and the crash goes away, all we'll have accomplished is hide the underlying crash. We might as well XFAIL it for Windows in such a case.

**Pull request merged**
