### PR TITLE
[stdlib] Removing a few harmful overloads of <

### PR DESCRIPTION
**Pull request by moiseev**
At some point during the implementation of integer protocols these
overloads were necessary to make expressions like `i32 < 0` faster
and unambiguous.
Now they are no longer necessary, and also cause problems for
expressions like `(u64 - u64) < u64`, where they cause the deprecated
`func - (Strideable, Strideable) -> Stride` be used, which is wrong, as
it will trap in many cases, where `func - (UInt64, UInt64) -> UInt64`
would not.

Fixes: <rdar://problem/31909031>

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please smoke-benchmark

**Comment by moiseev** [comment]
@swift-ci Please smoke benchmark

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
@swift-ci Please benchmark

**Comment by moiseev** [comment]
All the full checks passed earlier, before I added an extra commit, therefore triggering a smoke test run.
@swift-ci Please smoke test

**Comment by tkremenek** [comment]
@moiseev what's the verdict?

**Comment by airspeedswift** [comment]
I'm concerned about the perf regression of `Character` comparison. But it's also very strange, because the path for the comparison that ought to be happing for ASCII (which the regressed benchmarks use exclusively) ought to be using `Bool(Builtin.cmp_uge_Int63(lbits, _minASCIICharReprBuiltin))` so it oughtn't to be affected by this change at all.

**Comment by moiseev** [comment]
@swift-ci Please smoke benchmark

**Comment by moiseev** [comment]
@swiftix can you please have a look at [this commit](https://github.com/apple/swift/pull/9207/commits/d366503d9e7322da336f8ad0e0aa9cdcd8df589c). Are there any concerns? Like the result binary size etc...

**Comment by airspeedswift** [comment]
Looks like this did the trick.

**Comment by moiseev** [comment]
@airspeedswift yeah, and regressed elsewhere. :cry:

**Comment by airspeedswift** [comment]
Those benchmarks are quite jittery, I'm less concerned about them than I am about Chars and StringMatch, those are much more important. Also you appear to have sped up Calculator which is another benchmark that matters.

**Comment by airspeedswift** [comment]
@swift-ci please smoke test and merge

**Comment by moiseev** [comment]
@swift-ci Please smoke test and merge

**Pull request merged**
