### PR TITLE
[sil] Rename ValueOwnershipKind::{Any,None}

### PR DESCRIPTION
**Pull request by gottesmm**
At @atrick's suggestion.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
And for anyone listening in, I didn't do this by hand. I used Xcode's refactoring engine! So useful!

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Review by atrick — APPROVED** [review]
Yay! Now we can talk about "constraints" on ownership where the constraint can be: None, Owned, Guaranteed, or Any. If you "apply" the constraint (using the customary lattice-join operation for constraining types) and applying the constraint does not change the ownership kind, then you know the value already met that constraint! No more kind maps!

**Pull request merged**
