### PR TITLE
[DiagnosticsQoI] SR-3599: Better recovery for decls with consecutive identifiers

### PR DESCRIPTION
**Pull request by matthewcarroll**
Add diagnostics to fix decls with consecutive identifiers. This applies to
types, properties, variables, and enum cases. The diagnostic adds a camel-cased option if it is different than the first option.

```swift
let a b = 0
// error: found an unexpected second identifier in variable declaration; is there an accidental break?
// note: join the identifiers together
  var a b = 0
      ~~^
      ab

```

https://bugs.swift.org/browse/SR-3599

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
Looks like you accidentally fixed a compiler_crasher.

**Comment by matthewcarroll** [comment]
@slavapestov,

Would you like me to remove the expectation of crashing in the test `28619-basety-islvaluetype-basety-is-anymetatypetype`?

**Comment by CodaFi** [comment]
@matthewcarroll  If you want to automate the process, 

```
../llvm/utils/lit/lit.py -sv ../build/Ninja-DebugAssert/swift-macosx-x86_64/validation-test-macosx-x86_64/compiler_crashers/ | ./utils/resolve-crashes.py
```

**Comment by matthewcarroll** [comment]
@slavapestov, @CodaFi, 

Thanks! I ran the script on the test.

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Pull request merged**
