### PR TITLE
[Python] Fix bug: Config.free() does not take any arguments

### PR DESCRIPTION
**Pull request by practicalswift**
#### What's in this pull request?

Fix bug: `Config.free()` does not take any arguments.
#### Resolved bug number: –

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by practicalswift** [comment]
Pinging original author @akyrtzi :pager:

**Comment by rintaro** [comment]
`free` is decorated with `CachedProperty` that is a [descriptor](https://docs.python.org/2/howto/descriptor.html), and returns a function which receives one [`c_void_p`](https://docs.python.org/2/library/ctypes.html#ctypes.c_void_p) type argument.
There was nothing wrong with it, I think.

**Comment by jrose-apple** [comment]
And this would do something very different than the original code. I don't think this is correct.

**Comment by practicalswift** [comment]
@rintaro @jrose-apple You're absolutely right - the original code is correct. Mine is not :-)

This `pylint` warning fooled me:

```
$ pylint tools/SourceKit/bindings/python/sourcekitd/capi.py
E:104, 8: Too many positional arguments for method call (too-many-function-args)
```

Sorry for taking up your time @rintaro - I was way too sloppy and trigger happy in this case (an unfortunate combination :-)). Sorry, I'll be more careful going forward!

**Comment by practicalswift** [comment]
@akyrtzi @rintaro Do you know if the method `function_exists` ([code](https://github.com/apple/swift/blob/42b7e3f8d65183953c113185f10311752a593201/tools/SourceKit/bindings/python/sourcekitd/capi.py#L627)) is used?

It looks unused, but since I managed to mess up last time I thought it would be best to discuss the issue prior to jumping to (incorrect) conclusions :-)

**Comment by akyrtzi** [comment]
I don't think it's used.
As a general comment, ideally we'd have some 'nosetests' in-place before making changes, but anyway.. Removing 'function_exists' is fine by me.

**Pull request closed without merging**
