### PR TITLE
CapturePropagation: Can't forward to a function if it is not swift co…

### PR DESCRIPTION
**Pull request by aschwaighofer**
…nvention compatible

This causes breakage in check-swift-optimize_size on a release stdlib
bot.

Test case to follow.

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test

**Comment by aschwaighofer** [comment]
Should fix https://ci.swift.org/job/oss-swift_tools-RA_stdlib-RD_test-simulator/667/consoleFull#-1842550954ba62d58e-7248-467b-91e0-c7508d5cf947

stdlib/NSValueBridging.swift.gyb

**Comment by aschwaighofer** [comment]
FYI @nkcsgexi

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test and merge

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test and merge

**Comment by aschwaighofer** [comment]
Timeout :(

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test linux

**Comment by aschwaighofer** [comment]
@shahmishal Two timeouts in a row

Last one was here: https://ci.swift.org/job/swift-PR-Linux-smoke-test/4462/consoleFull#-18214046597673623-2881-452e-8a87-fc2a90be9a24

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test linux

**Comment by shahmishal** [comment]
Looks like we have a test taking 30+mins to complete.

**Comment by nkcsgexi** [comment]
Tests seem passing. Merged.

**Comment by shahmishal** [comment]
Please file a bug on bugs.swift.org for test causing the issue.

**Pull request merged**
