### PR TITLE
[test] Restrict spi-available inline to macosx only

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
Follow-up to #42051

### CODE REVIEW

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test

**Comment by nkcsgexi** [comment]
Not sure `&&` works properly here. Could you split it into two `REQUIRES` lines?

**Comment by LucianoPAlmeida** [comment]
> Not sure `&&` works properly here. Could you split it into two `REQUIRES` lines?

No problem, just done ;)

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test

**Review by xedin — APPROVED** [review]

**Comment by gottesmm** [comment]
I am merging this to unblock the bots. Got a review. @LucianoPAlmeida please do full tests rather than break the build to be careful with this sort of thing.

**Comment by LucianoPAlmeida** [comment]
> @LucianoPAlmeida please do full tests rather than break the build to be careful with this sort of thing.

Roger that! Sorry for the trouble

**Pull request merged**
