### PR TITLE
[5.1] Avoid the overhead of looking up the current CFAllocator in String bridging

### PR DESCRIPTION
**Pull request by Catfish-Man**
Cherry pick

### CODE REVIEW

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Comment by Catfish-Man** [comment]
Linux failure is a known unrelated one

**Comment by Catfish-Man** [comment]
Original PR: https://github.com/apple/swift/pull/24000

**Review by airspeedswift — APPROVED** [review]

**Comment by Catfish-Man** [comment]
@swift-ci please test linux platform

**Pull request merged**
