### PR TITLE
Added op device placement (including GPU support) in eager mode.

### PR DESCRIPTION
**Pull request by mhong**
Compared to the non-eager C API, the eager API TFE_OpSetDevice() is more strict
with the device string name. It does not accept "/device:CPU:0", but accepts
"/job:localhost/replica:0/task:0/device:CPU:0", so we changed the graph code
path to use the latter as well.

In the case of "ALL_DEVICES", just let the eager runtime pick a default device (e.g. it'd prefer GPU over CPU if GPU is available).

### CODE REVIEW

**Comment by mhong** [comment]
@swift-ci please test tensorflow

**Comment by mhong** [comment]
@swift-ci please test tensorflow

**Review by rxwei — APPROVED** [review]
LGTM

**Comment by bgogul** [comment]
Thanks, Ming. I believe the naming was the issue when I tried to connect to a remote session in eager mode. This patch should take care of that.

**Comment by mhong** [comment]
Great!

**Pull request merged**
