### PR TITLE
Sourcekit/DocSupport: include fully annotated generic signatures for extension decls.

### PR DESCRIPTION
**Pull request by nkcsgexi**
rdar://40906297
rdar://43820510

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by slavapestov** [comment]
Why not include them for nominal types as well?

**Comment by nkcsgexi** [comment]
because they're included in the fully annotated decls for nominal types.

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Pull request merged**
