### PR TITLE
[CSDiag] Remove nested type and use TC.isConvertible instead

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
cc @xedin 

Noticed we have existing functionality for convertibility checking

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Review by xedin — APPROVED** [review]
Looks reasonable, but involving matchTypes might not always produces the same results as simplified code TypeConvertibleChecker had.

**Comment by AnthonyLatsis** [comment]
I’ll add a leading isEqual then. Might be even better to prepend it in TC.isConvertible as a fast path if it isn’t there.

**Comment by slavapestov** [comment]
I'm fine with this. It removes some duplication, and if isConvertible() is wrong we need to fix any problems there.

**Pull request merged**
