### PR TITLE
[CodeCompletion] Add test case for SR-14711

### PR DESCRIPTION
**Pull request by ahoppen**
The issue has been fixed on `main` recently. Since we have a reproducing test case, add it to the test suite.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Review by rintaro — DISMISSED** [review]

**Comment by rintaro** [comment]
Since this was not a crasher. Could you move this test file to `test/IDE`?

**Comment by ahoppen** [comment]
Oh, you’re right of course. Moved it to `test/IDE`.

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test Linux

**Comment by ahoppen** [comment]
@swift-ci Please smoke test Windows

**Review by rintaro — APPROVED** [review]

**Pull request merged**
