### PR TITLE
[semantic-arc-opts] Follow ups to #30289

### PR DESCRIPTION
**Pull request by gottesmm**
Fixing some things that Andy and I agreed upon offline.

### CODE REVIEW

**Comment by gottesmm** [comment]
#30289

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Review by atrick — APPROVED** [review]
I like the renames. I guess this is part 1 of N.

**Comment by gottesmm** [comment]
Yes.

**Comment by gottesmm** [comment]
I was hoping to do the small ones here and the larger one that we talked about (the data structure change) in a separate commit.

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Review by atrick — COMMENTED** [review]
kewl

**Pull request merged**
