### PR TITLE
[Test] Update batch-mode-llvmIRHash-consistency.swift to use make-old…

### PR DESCRIPTION
**Pull request by shahmishal**
….py to avoid touch issue

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test Windows

**Comment by shahmishal** [comment]
@swift-ci test Windows

**Comment by shahmishal** [comment]
@swift-ci test Windows

**Comment by davidungar** [comment]
Thanks for doing this. I assume it’s because Windows does not have the touch command? What I’m confused about, is that touch makes something new, but the Python command here is called make-old. Is the name of the Python command a misnomer?

**Comment by CodaFi** [comment]
@swift-ci test Windows

**Comment by shahmishal** [comment]
@swift-ci test Windows

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test windows

**Pull request merged**
