### PR TITLE
Properly compute actor isolation of local functions with captures.

### PR DESCRIPTION
**Pull request by DougGregor**
Non-Sendable local functions can be actor-isolated if they capture an
isolated parameter. Treat them as such. Fixes rdar://83090397.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Review by ktoso — APPROVED** [review]
Sweet! LGTM

**Comment by DougGregor** [comment]
@swift-ci please test Windows

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Pull request merged**
