### PR TITLE
[ConstraintSystem] NFC: Factor operator overload identification and partitioning.

### PR DESCRIPTION
**Pull request by xedin**
- Add new `isOperatorDisjunction` and `getOverloadChoiceDecl` methods
- Move `partition*` methods under `DisjunctionChoiceProducer`
- Replace `isOperatorBindOverload` and some duplicate logic with new `isOperatorDisjunction` and remove it.

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please smoke test

**Review by hborla — APPROVED** [review]
This looks much cleaner, thank you!

**Comment by xedin** [comment]
@swift-ci please smoke test Windows platform

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Pull request merged**
