### PR TITLE
Add underscore prefix to extern attribute

### PR DESCRIPTION
**Pull request by kateinoigakukun**
It's already guarded by a feature flag, but it would be nice to signal users that it's not stable yet by adding an underscore prefix.

This change is suggested by @lorentey

### CODE REVIEW

**Comment by kateinoigakukun** [comment]
@swift-ci test

**Review by lorentey — APPROVED** [review]
Thank you! 👍

**Comment by kateinoigakukun** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Pull request merged**
