### PR TITLE
[build] Don't infer Clang path when crosscompiling

### PR DESCRIPTION
**Pull request by edymtt**
Addresses rdar://71240426

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci build toolchain macOS

**Comment by edymtt** [comment]
@swift-ci please smoke test

**Comment by edymtt** [comment]
Follow up to #34437

**Comment by edymtt** [comment]
@swift-ci please test stdlib with toolchain

**Comment by edymtt** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Review by shahmishal — APPROVED** [review]

**Comment by edymtt** [comment]
@swift-ci Please Test Source Compatibility

**Comment by edymtt** [comment]
@swift-ci please smoke test Linux

**Comment by shahmishal** [comment]
```
16:12:18 Failed Tests (2):
16:12:18   Swift(macosx-x86_64) :: stdlib/KeyPathAppending.swift
16:12:18   Swift(macosx-x86_64) :: stdlib/ArrayDiagnostics.swift
```
Not sure why it's failing on this change

**Comment by edymtt** [comment]
That failures seems to be happening on the "main" job as well and makes me think they are unrelated to this change

https://ci.swift.org/job/oss-swift-test-stdlib-with-toolchain/62/

I would need to double check locally just in case

**Comment by compnerd** [comment]
Hey @edymtt could you share a bit more context on this?  I don't understand what this is supposed to do/what it does.

From ~CMakeLists.txt:465
```cmake
if("${SWIFT_NATIVE_LLVM_TOOLS_PATH}" STREQUAL "")
  set(SWIFT_CROSS_COMPILING FALSE)
else()
  set(SWIFT_CROSS_COMPILING TRUE)
endif()
```

The `NOT SWIFT_CROSS_COMPILING` implies that `SWIFT_NATIVE_TOOLS_LLVM_PATH` would be `""`, which means that this was just setting the variable to empty (so it should be a no-op)?

**Comment by edymtt** [comment]
To the best of my understanding, when we are building Swift for the host architecture, we expect `SWIFT_NATIVE_TOOLS_LLVM_PATH`/`SWIFT_NATIVE_CLANG_TOOLS_PATH` to not be set when CMake is invoked (as per toolchain job log) -- the code in `cmake/modules/SwiftSharedCMakeConfig.cmake` will then leverage the values obtained by finding the LLVM package to set the path for the compiler.

When we are cross compiling, those values are set when invoking CMake and we want to consider them -- as such my patch is basically mimicking what we are already doing at https://github.com/apple/swift/pull/34664/files#diff-af70c8d589bfadd011360af736827b9f3e3bd1655f7ceb9f08db8fc3045acaeeR62 for `SWIFT_NATIVE_TOOLS_LLVM_PATH`, when we sense `SWIFT_CROSS_COMPILING` to understand if that what's the case and avoid overwriting the value

Let me know if anything is missing in my explanation.

**Review by compnerd — APPROVED** [review]
Ah, if the checks are for the value being set rather than empty, that would explain that.  Thanks!

**Comment by edymtt** [comment]
Closing this in favor of #34628

**Pull request closed without merging**
