### PR TITLE
Merging swift-DEVELOPMENT-SNAPSHOT-2019-06-06-a into tensorflow

### PR DESCRIPTION
**Pull request by dan-zheng**
For `apple/swift`: merge https://github.com/apple/swift/commit/58827bbed338194eca2072e99214330b73441cba (from 2019-06-11).
For all other repositories: merge `swift-DEVELOPMENT-SNAPSHOT-2019-06-06-a `.

### CODE REVIEW

**Comment by dan-zheng** [comment]
Current status:
* All compiler tests pass (`swift/utils/build-script --preset tensorflow_test`).
* A bunch of LLDB tests fail:

```
Failing Tests (25):
    LLDB :: Swift/No.swiftmodule.test
    LLDB :: Swift/global.test
    LLDB :: SwiftREPL/Basic.test
    LLDB :: SwiftREPL/BreakpointSimple.test
    LLDB :: SwiftREPL/Class.test
    LLDB :: SwiftREPL/ComputedProperties.test
    LLDB :: SwiftREPL/Deadlock.test
    LLDB :: SwiftREPL/Dict.test
    LLDB :: SwiftREPL/ErrorReturn.test
    LLDB :: SwiftREPL/ExclusivityREPL.test
    LLDB :: SwiftREPL/GenericTypealias.test
    LLDB :: SwiftREPL/Generics.test
    LLDB :: SwiftREPL/MetatypeRepl.test
    LLDB :: SwiftREPL/Optional.test
    LLDB :: SwiftREPL/OptionalUnowned.test
    LLDB :: SwiftREPL/RecursiveClass.test
    LLDB :: SwiftREPL/SimpleExpressions.test
    LLDB :: SwiftREPL/Struct.test
    LLDB :: SwiftREPL/Subclassing.test
    LLDB :: SwiftREPL/SwiftInterface.test
    LLDB :: SwiftREPL/SwiftInterfaceForceModuleLoadMode.test
    LLDB :: SwiftREPL/SwiftTypeLookup.test
    LLDB :: SwiftREPL/UninitVariables.test
    LLDB :: SwiftREPL/ZeroSizeStruct.test
    LLDB :: SwiftREPL/rdar30147367.test
```

@marcrasi: could you please help look into the lldb failures?
`swift-lldb` friend merge PR: https://github.com/apple/swift-lldb/pull/1672

**Comment by marcrasi** [comment]
All LLDB tests pass for me (and in fact, all toolchain tests pass for me) at commit e2b06ef5275507a48e252fb4cb186d0bf42dca90.

Maybe you were getting flakiness? Or maybe it's that the LLDB tests are very sensitive to the python version that you have on your system.

**Comment by dan-zheng** [comment]
> All LLDB tests pass for me (and in fact, all toolchain tests pass for me) at commit [e2b06ef](https://github.com/apple/swift/commit/e2b06ef5275507a48e252fb4cb186d0bf42dca90).
> 
> Maybe you were getting flakiness? Or maybe it's that the LLDB tests are very sensitive to the python version that you have on your system.

Thank you for verifying that LLDB tests pass! I assume the failures I encountered are environment-related.

---

Running tests now, then merging.

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Comment by dan-zheng** [comment]
Tested manually on macOS. There's only one failure, which is [known](https://bugs.swift.org/browse/TF-571).

```
********************
Testing Time: 1001.12s
********************
Failing Tests (1):
    Swift(macosx-x86_64) :: ClangImporter/cxx_interop.swift

  Expected Passes    : 11896
  Expected Failures  : 26
  Unsupported Tests  : 210
  Unexpected Failures: 1
```

**Pull request merged**
