### PR TITLE
[AutoDiff] Make AD function names not demanglable & fix primal value struct access control

### PR DESCRIPTION
**Pull request by rxwei**
* Make AD function names not demanglable by prepending `AD__`. Re-enabled ObjectOutliner since it will no longer try to demangle AD-generated functions. This partially reverts #19163.
* Make primal value structs `@_fixed_layout` and ABI-public.

### CODE REVIEW

**Review by marcrasi — APPROVED** [review]

**Comment by rxwei** [comment]
@swift-ci please test tensorflow linux cpu

**Comment by rxwei** [comment]
@swift-ci please test tensorflow linux cpu

**Comment by rxwei** [comment]
@swift-ci please test tensorflow linux cpu

**Comment by rxwei** [comment]
@swift-ci please test tensorflow linux cpu

**Pull request merged**
