### PR TITLE
[stdlib] Add benchmarks for Character's unicodeScalars view

### PR DESCRIPTION
**Pull request by dabrahams**
In local testing, these benchmark results change as follows due to f212fac7171:

<details open>
  <summary>Regression (20)</summary>

TEST                                              | OLD    | NEW    | DELTA   | SPEEDUP
---                                               | ---    | ---    | ---     | ---
CharIteration_utf16_unicodeScalars                | 33074  | 79510  | +140.4% | **0.42x**
CharIteration_utf16_unicodeScalars_Backwards      | 73826  | 115515 | +56.5%  | **0.64x**

</details>

<details open>
  <summary>Improvement (43)</summary>

TEST                                              | OLD    | NEW    | DELTA   | SPEEDUP
---                                               | ---    | ---    | ---     | ---
CharIndexing_korean_unicodeScalars                | 118425 | 10360  | -91.3%  | **11.43x**
CharIndexing_tweet_unicodeScalars_Backwards       | 226366 | 19850  | -91.2%  | **11.40x**
CharIndexing_tweet_unicodeScalars                 | 240596 | 21178  | -91.2%  | **11.36x**
CharIndexing_japanese_unicodeScalars_Backwards    | 136265 | 12032  | -91.2%  | **11.33x**
CharIndexing_chinese_unicodeScalars               | 92226  | 8146   | -91.2%  | **11.32x**
CharIndexing_russian_unicodeScalars               | 100908 | 8948   | -91.1%  | **11.28x**
CharIndexing_japanese_unicodeScalars              | 145414 | 12895  | -91.1%  | **11.28x**
CharIndexing_ascii_unicodeScalars                 | 121438 | 10779  | -91.1%  | **11.27x**
CharIndexing_russian_unicodeScalars_Backwards     | 94190  | 8367   | -91.1%  | **11.26x**
CharIndexing_korean_unicodeScalars_Backwards      | 110175 | 9803   | -91.1%  | **11.24x**
CharIndexing_chinese_unicodeScalars_Backwards     | 86479  | 7715   | -91.1%  | **11.21x**
CharIndexing_ascii_unicodeScalars_Backwards       | 113255 | 10132  | -91.1%  | **11.18x**
CharIteration_ascii_unicodeScalars_Backwards      | 114873 | 13701  | -88.1%  | **8.38x**
CharIteration_chinese_unicodeScalars_Backwards    | 85778  | 10411  | -87.9%  | **8.24x**
CharIteration_russian_unicodeScalars_Backwards    | 94504  | 11471  | -87.9%  | **8.24x**
CharIteration_japanese_unicodeScalars_Backwards   | 136231 | 16569  | -87.8%  | **8.22x**
CharIteration_tweet_unicodeScalars_Backwards      | 222907 | 27165  | -87.8%  | **8.21x**
CharIteration_korean_unicodeScalars_Backwards     | 110132 | 13443  | -87.8%  | **8.19x**
CharIteration_korean_unicodeScalars               | 79540  | 11859  | -85.1%  | **6.71x**
CharIteration_russian_unicodeScalars              | 68209  | 10211  | -85.0%  | **6.68x**
CharIteration_japanese_unicodeScalars             | 98016  | 14690  | -85.0%  | **6.67x**
CharIteration_tweet_unicodeScalars                | 161177 | 24227  | -85.0%  | **6.65x**
CharIteration_chinese_unicodeScalars              | 61702  | 9278   | -85.0%  | **6.65x**
CharIteration_ascii_unicodeScalars                | 81049  | 12218  | -84.9%  | **6.63x**

</details>

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please smoke benchmark

**Comment by dabrahams** [comment]
@swift-ci Please smoke test and merge

**Comment by palimondo** [comment]
Can we do something to the naming of these tests? They don't follow the convention established so far… and also are horribly long.

**Comment by palimondo** [comment]
I suggest:
* drop underscores
* use abbreviated country codes and proper capitalization of abbreviations
* drop `unicodeScalars` suffix - they all have it…
* shorten Backwards to Back

E.g.: `CharIterationRU`, `CharIterationBackRU`, `CharIterationUTF16`, etc.

**Comment by palimondo** [comment]
Or `CharIterationRevCN`, as in reverse (instead of `Back`)

**Comment by palimondo** [comment]
@dabrahams I'm looking over these benchmarks and wonder about the motivation for testing `.reversed` iteration and indexing. I can see this might be important in character iteration for Boyer–Moore string-search algorithm. But why is this applicable on the `unicodeScalar` level?

**Comment by dabrahams** [comment]
I'm sorry, I don't think I can offer any real insight.  I think the idea was to make sure all the new components were performant and didn't regress.

**Comment by palimondo** [comment]
Also, I have tried to test locally a modified versions without first copying the `Character`s to `Array`, thinking `String` is fully materialized collection, there shouldn't be much difference, only to find 3-4x slowdown (30-60 on "utf16" variant), both for imperative `for-each` approach and functional `map.reduce`. I was hoping to recover some performance by going `.lazy`, but it didn't help.

**Comment by palimondo** [comment]
How realistic is testing iteration over `Character`'s `unicodeScalar` view from `Array`, and not directly from `String`?

**Comment by palimondo** [comment]
@milseman Do you have opinion about this?

**Comment by milseman** [comment]
> But why is this applicable on the unicodeScalar level?

Reversed decoding can be more expensive, and is not optimizable by using a customized iterator.

> How realistic is testing iteration over Character's unicodeScalar view from Array, and not directly from String?

Sorry, could you re-phrase this? BTW, I introduced a custom iterator for String.UnicodeScalarView, which makes pure iteration much faster than the indexing approach.

**Comment by palimondo** [comment]
I was questioning the practical applicability (or realism) of how this benchmark is currently built. I can understand the importance of reverse iteration on the character view as that's used for example in the Boyer–Moore string-search algorithm. I guess this is also applicable to the `String`'s `.unicodeScalar` view… I see "backwards iteration" mentioned in the TR on [Unicode text segmentation](https://unicode.org/reports/tr29/#Random_Access) boundary detection and such. 

But the `CharIteration` and `CharIndexing` benchmarks seem too synthetic to me,  because they focus only on testing **`Character`**'s `.unicodeScalar` view. Of all the workloads, only the `utf16` contains different number of characters vs. unicodeScalars. Which means we are mostly testing forward and `.reverse` iteration on a single element collections retrieved from `Character`. Moreover, these `Character`s are not accessed from a`String`, as I guess would be typical in string processing, but are precomputed into `Array<Character>`. So I think we end up redundantly measuring a really thin aspect here.

Shouldn't these benchmarks be changed to measure forward and reverse iteration on the `characters` and `unicodeScalar` views from the String? As mentioned above, that results in runtimes that are 3-6x slower (30-60 on "utf16" variant) than the synthetic-once we currently have. It looks like there is quite significant overhead in creating the individual `Character`'s from the strings?

**Pull request merged**
