### PR TITLE
Better runtime failure messages (not yet enabled by default)

### PR DESCRIPTION
**Pull request by eeckstein**
Meaning:
- Make runtime failure messages visible in release mode, which were previously only available in debug builds
- Add messages for runtime failures, which didn't have a message at all, like arithmetic overflow.

All this is done via debug info, so there is no overhead in code generation. Thanks @adrian-prantl for the idea of implementing this with inline functions in the debug info.
When having debug info available, e.g. when running in the debugger, the failure message is displayed as inline function.

Examples:
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x0000000100000c9c a.out`testit1(_:) [inlined] arithmetic overflow at test.swift:4:12 [opt]
   1   	
   2   	@inline(never)
   3   	func testit1(_ a: Int8) -> Int8 {
-> 4   	  return a + 1
   5   	}
   6   	
```
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x0000000100000cbf a.out`testit3(_:) [inlined] Unexpectedly found nil while unwrapping an Optional value at test.swift:14:11 [opt]
   11
   12  	@inline(never)
   13  	func testit(_ a: Int?) -> Int {
-> 14  	  return a!
   15  	}
   16
```

This change is currently not enabled by default, but can be enabled with the option "-Xllvm -enable-trap-debug-info". Enabling this feature needs some changes in lldb. When the lldb part is done, this option can be removed and the feature enabled by default.

rdar://problem/51278690

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by brentdax** [comment]
@eeckstein We've reverted this because we think it may have broken four tests:

* SILOptimizer/pound_assert.swift
* SILOptimizer/existential_transform.swift
* IRGen/condfail_message.swift
* DebugInfo/linetable-codeview.swift

See e.g. https://ci.swift.org/job/oss-swift_tools-RA_stdlib-DA_test-simulator/715 for examples of the failures.

**Pull request merged**
