### PR TITLE
Get the compiler building again on 32-bit architectures

### PR DESCRIPTION
**Pull request by finagolfin**
I've had to use this [since earlier in the year when cross-compiling the toolchain for Android armv7](https://github.com/buttaface/termux-packages/commit/3e036bb06a16a7ec9c0c7018dc9caa0d4ec6a97f#diff-041d6f17b0656a05d2ad4e29d86e9aad4f9f3140e5294501f2529aa28dded147), along with a version of apple/llvm-project#5883.

@CodaFi, since this is a small modification to your #41743, please review whenever you get back from winter break.

### CODE REVIEW

**Comment by buttaface** [comment]
Pinging @CodaFi, small pull.

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by buttaface** [comment]
Windows CI failure when building libdispatch is unrelated.

**Comment by Mztea928** [comment]
Omw I love u pete

**Pull request merged**
