### PR TITLE
[swiftBasic] Fix description in comment of ClusteredBitVector

### PR DESCRIPTION
**Pull request by omochi**
I think that this comment is wrong.
Sorry if I misunderstood something.

### CODE REVIEW

**Review by Jceciliani — APPROVED** [review]
I believe that the change of == instead of the current != is correct to test whether all bits are zero, in regards to the comments given.

**Comment by hiragram** [comment]
👍

**Comment by CodaFi** [comment]
Apologies for not getting a reviewer for this sooner.  The implementation for this has changed quite a bit recently and this documentation change is no longer necessary as of 192bcb2.  Thank you for the patch, regardless.  We will try to be more diligent about getting this reviewed in the future.

**Comment by omochi** [comment]
@CodaFi OK.

I saw that you were checking many patches which had been opened long time recently.
It is great job.
I will try to contribute more in future.

**Pull request closed without merging**
