### PR TITLE
[update-checkout] Pin swift-asn1 and swift-certificates; bump swift-crypto

### PR DESCRIPTION
**Pull request by yim-lee**

### CODE REVIEW

**Comment by yim-lee** [comment]
https://github.com/apple/swift-package-manager/pull/6262
@swift-ci please smoke test

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/64285
@swift-ci please test

**Comment by yim-lee** [comment]
https://github.com/apple/swift-package-manager/pull/6262
@swift-ci please test

**Comment by yim-lee** [comment]
cc @Lukasa @tomerd @neonichu

**Review by tomerd — APPROVED** [review]

**Comment by yim-lee** [comment]
https://github.com/apple/swift-package-manager/pull/6262
@swift-ci please smoke test

**Comment by yim-lee** [comment]
https://github.com/apple/swift-package-manager/pull/6262
@swift-ci please test

**Comment by yim-lee** [comment]
https://github.com/apple/swift-package-manager/pull/6262
@swift-ci please test

**Pull request merged**
