### PR TITLE
[ConstraintSystem] Adjust contextual locators to support updated Double/CGFloat conversion

### PR DESCRIPTION
**Pull request by xedin**
-  Adjust contextual locator of single expression closure before coercion

Contextual conversion constraint is placed on `result of closure body`
and solution application logic should match that.

- Don't use special locator for value-to-value conversions related to contextual type

Previously locator for value-to-value conversion would just drop
all the contextual information if the conversion occurred while
converting expression to a contextual type. This is incorrect for
i.e. `return` statements and other targets because because they
are solved separately and using the same locator would result in
a clash when solutions are merged.

Resolves: rdar://99059525

### CODE REVIEW

**Comment by xedin** [comment]
Note for posterity - I think we can remove `ClosureBody` locator element and use `ContextualType(CTP_ClosureResult)`, just need to figure out what it means for diagnostics and where to store `hasReturn` bit that it currently uses (one possibility - a separate element in the path).

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Review by hborla — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Pull request merged**
