### PR TITLE
AST: Refactor SelfReferenceKind in preparation for #33767

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
This will enable us to allow members containing references to Self or associated types
only in covariant position to be used on an existential.

### CODE REVIEW

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Review by slavapestov — APPROVED** [review]

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Comment by AnthonyLatsis** [comment]
@swift-ci please test source compatibility release

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Comment by AnthonyLatsis** [comment]
@swift-ci please test source compatibility release

**Comment by AnthonyLatsis** [comment]
@swift-ci please test source compatibility release

**Comment by AnthonyLatsis** [comment]
@swift-ci please test source compatibility

**Comment by AnthonyLatsis** [comment]
The few source compat FAILs are clone failures that can be observed in some neighbouring builds too, so I think the patch will are alright.

**Comment by AnthonyLatsis** [comment]
@slavapestov Thank you for looking through this in such short terms.

**Pull request merged**
