### PR TITLE
Extension Block Symbols: Fix `inheritsFrom` Relationship 

### PR DESCRIPTION
**Pull request by theMomax**
This PR fixes a bug in the extension block format for Symbol Graphs. When extending an external `swift.class` symbol that has a superclass, the respective `inheritsFrom` relationship between the extended `swift.class` symbol and its superclass symbol was emitted not only in the symbol graph file that includes the external `class`' symbol, but also in every symbol graph file that contains a `swift.extension` symbol extending the same `swift.class` symbol.

E.g. in the following snippet both `External.symbols.json` as well as `Main@External.symbols.json` included the `inheritsFrom` relationship between `C` and `Superclass`.

```swift
// "External" Target
public class Superclass { }
public class C: Superclass { }

// "Main" Target
public extension C {
    func foo() { }
}
```

This bug has no associated issue or radar.

### CODE REVIEW

**Comment by jaesmoke** [comment]
waiting for checks to complete

**Review by QuietMisdreavus — APPROVED** [review]
This looks good, thanks!

**Comment by QuietMisdreavus** [comment]
@swift-ci Please smoke test

**Comment by theMomax** [comment]
@QuietMisdreavus thanks!  This can be merged right away independently of the other PRs.

**Pull request merged**
