### PR TITLE
SIL: Remove -disable-sil-linking frontend flag

### PR DESCRIPTION
**Pull request by slavapestov**
Just cleaning up some loose ends from the SIL linker rework.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Review by gottesmm — COMMENTED** [review]
Moving LinkingMode/changing it in this way should be done in a separate commit from removing this option.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Pull request merged**
