### PR TITLE
[Constraint system] Allow the solver to bind collection literal types…

### PR DESCRIPTION
**Pull request by rudkx**
… earlier.

When this kicks in it can result in substantially speeding up type
inference for collection literals.

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Review by xedin — COMMENTED** [review]
LGTM!

**Comment by DougGregor** [comment]
Makes sense to me, thanks!

**Pull request merged**
