### PR TITLE
test: adjust various tests for Windows

### PR DESCRIPTION
**Pull request by compnerd**
Smorgasbord of test fixes to improve test rate on Windows.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @rjmccall @jckarter @slavapestov

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by rjmccall** [comment]
Not sure about `%target-abi` for the substitution name.  Most of these differences come down to the extra limitations of COFF, right?  And it's not like Win32 and Win64 would be different.

**Comment by compnerd** [comment]
@rjmccall ... actually, not all of them are due to the limitations in COFF, at least not directly.  The strategy pattern being singleton rather than the default causes a couple of members to not be initialized in the metadata.  But, there are differences in the `c_layout` which are not due to the COFF limitations but rather the argument passing conventions.  Those just happen to be the same across the two, since the argument passing tries to be somewhat similar across win32 and win64, though if you start looking at where the arguments are stored, they would be different.

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by rjmccall** [comment]
Hmm.  So I can see the merit of calling this `%target-abi` (or `%target-os-cconv`?) with options of `sysv` or `windows`/whatever for the `c_functions` case, to try to capture the fact that most OSes use the same x86_64 calling conventions and it's just Windows that stands out.  The options there would logically be arch-specific so that e.g. on ARM32 we'd use something like `apcs` and `aapcs` instead of `sysv`, and that would very neatly let us share CHECK lines across Linux, FreeBSD, and whatever else might support ARM32 using the same system CC.

That said, I don't think that's the right way of thinking about the test changes that really do just reflect COFF's inability to reference imported declarations from the data segment.  Those should use a more targeted substitutions.

I don't believe it's important to minimize the set of substitutions we apply.

**Comment by compnerd** [comment]
I'm fine with more substitutions, I've added a bunch and got some push back, which is why I was trying to reduce them :-).  What about a second one of `%target-initialization-strategy` for the case with the initializers?

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by rjmccall** [comment]
> I'm fine with more substitutions, I've added a bunch and got some push back, which is why I was trying to reduce them :-).

Heh.  Well, feel free to CC me in if you get more pushback.

> What about a second one of `%target-initialization-strategy` for the case with the initializers?

I think that's too specific of a name.  The root cause is COFF vs. non-COFF, or specifically the ability to have imported symbols in DATA, and we know that the same limitation affects more than just metadata initialization.  And COFF also requires `dllimport` / `dllexport` annotations and several other differences.  Can we just have `%target-coff` that's either `coff` or `noncoff`?

**Comment by compnerd** [comment]
Sure, I am open to renaming the variable.  I think my problem with something like `%target-coff` is that it feels like a boolean which is fine, but that doesn't work very well for filecheck itself.  `%target-obj` already tells us if something is COFF specific or not.  Its just that MachO and ELF both work similarly enough to let us get away with one.  I am totally okay with using `%target-obj` though ... its only a slight bit of duplication (and we are already loosening the tests for some of that e.g. `{{(protected )?}}` - so switching to that does make the tests a bit more stricter which is nice.

**Comment by rjmccall** [comment]
> Sure, I am open to renaming the variable. I think my problem with something like `%target-coff` is that it feels like a boolean which is fine, but that doesn't work very well for filecheck itself. `%target-obj` already tells us if something is COFF specific or not. Its just that MachO and ELF both work similarly enough to let us get away with one. I am totally okay with using `%target-obj` though ... its only a slight bit of duplication (and we are already loosening the tests for some of that e.g. `{{(protected )?}}` - so switching to that does make the tests a bit more stricter which is nice.

`%target-obj` is fine, too, especially for cases where it makes sense; but if it reduces redundancy, I think having a boolean `obj-is-coff` substitution is okay as well.  Obviously the *values* of this substitution should not be `true`/`false`; that's why I suggested `coff`/`noncoff`.

Maybe we should just have a convenience substitution which builds on `%FileCheck` to also add a bunch of arguments that we want to use for IRGen, like `-DINT=i%target-ptrsize` and `-check-prefix CHECK -check-prefix CHECK-%target-obj -check-prefix CHECK-%target-obj-is-coff` etc.

**Comment by compnerd** [comment]
Alright, created a `%target-import-type` for `DIRECT` or `INDIRECT` referencing the MachO/ELF behaviour vs the PE/COFF behaviour.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by rjmccall** [comment]
> Alright, created a `%target-import-type` for `DIRECT` or `INDIRECT` referencing the MachO/ELF behaviour vs the PE/COFF behaviour.

Thanks, that sounds like a reasonable name.

**Comment by compnerd** [comment]
@swift-ci please clean test Linux platform

**Comment by compnerd** [comment]
@swift-ci please clean test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@rjmccall, @jckarter, @slavapestov - any objections to merging this to get the IRGen tests to pass on Windows?

**Comment by compnerd** [comment]
Going to merge this since it really should have no impact on the non-windows targets, but at least makes the Windows IRGen tests pass.  I'm pretty sure that the couple of places where Windows is different is correct (which is primarily due to layout differences).

**Pull request merged**
