### PR TITLE
[SR-2003] Relax the static Self restriction for nested functions

### PR DESCRIPTION
**Pull request by CodaFi**
#### What's in this pull request?

Search parent decl contexts for a protocol extension context instead of just the current context to allow nested functions using `Self`.
#### Resolved bug number: ([SR-2003](https://bugs.swift.org/browse/SR-2003))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please test.

**Comment by CodaFi** [comment]
@slavapestov How does it look?

**Comment by jrose-apple** [comment]
It seems important that the inner Self is a static Self and not dynamic. Is it possible to test that?

**Comment by CodaFi** [comment]
If we're in a protocol extension `Self` is always static.

**Comment by CodaFi** [comment]
Package manager has some syntax errors to fix!

**Comment by jrose-apple** [comment]
What if it's a class-bound protocol?

**Comment by jrose-apple** [comment]
(I believe that that's the way things are today. I don't think we're necessarily going to stick to that, though, and I think we should have a test so that we know when it changes.)

**Comment by CodaFi** [comment]
That's a great idea.  I will update the test.

**Comment by slavapestov** [comment]
Thanks for fixing this @CodaFi.

I believe we should also allow local functions to return _dynamic_ Self inside class methods that return dynamic Self. Now that the machinery for closures to capture Self is wired up, this should work without any issues.

**Comment by CodaFi** [comment]
@swift-ci please test and merge.

**Pull request merged**
