### PR TITLE
[Do Not Merge!] Empty commit for cross-repo testing of SwiftDriver PR #929

### PR DESCRIPTION
**Pull request by abertelrud**
This is an empty pull request for doing a cross-repo toolchain test with SwiftDriver https://github.com/apple/swift-driver/pull/929.

It will be deleted once the test passes and the SwiftDriver PR has been merged.

### CODE REVIEW

**Comment by abertelrud** [comment]
apple/swift-driver#929
@swift-ci please smoke test

**Comment by abertelrud** [comment]
The Windows smoke test seems to be unrelated to making SwiftDriver depend on the `release/5.6` branch of llbuild and toolsupportcore instead of `main`.  @compnerd do you agree with that assessment?  I'm trying to find out if that should block https://github.com/apple/swift-driver/pull/929

**Comment by compnerd** [comment]
I don't think that this should as it seems to be a flake.  The Windows tests are relatively quick, so it doesn't hurt to spin off another run.

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by abertelrud** [comment]
> I don't think that this should as it seems to be a flake. The Windows tests are relatively quick, so it doesn't hurt to spin off another run.

Thanks @compnerd.  This time is seems to have succeeded but with "Build finished. No test results found."   Is that expected?

**Comment by abertelrud** [comment]
> I don't think that this should as it seems to be a flake. The Windows tests are relatively quick, so it doesn't hurt to spin off another run.

Thanks @compnerd.  This time is seems to have succeeded but with "Build finished. No test results found."   Is that expected?

**Comment by compnerd** [comment]
> > I don't think that this should as it seems to be a flake. The Windows tests are relatively quick, so it doesn't hurt to spin off another run.
> 
> Thanks @compnerd. This time the Windows build seems to have succeeded but with "Build finished. No test results found." Is that expected?

Yeah; it is rather odd.  The output is there in the link, the message is just odd.  🤷‍♂️

**Comment by abertelrud** [comment]
This PR has served its purpose.  Closing the PR.

**Pull request closed without merging**
