### PR TITLE
Revert "Math functions for Swift"

### PR DESCRIPTION
**Pull request by xedin**
Reverts apple/swift#23140

Just the test to see if this is really what introduced source compatibility regressions:

https://ci.swift.org/view/Source%20Compatibility/job/swift-master-source-compat-suite/3384/console

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
Currently failing:
```
02:04:20   FAIL: IBAnimatable, 4.0, eb4acb, IBAnimatableApp, generic/platform=iOS
02:04:20   FAIL: IBAnimatable, 4.0, eb4acb, IBAnimatable, generic/platform=iOS
02:04:20   FAIL: Surge, 5.0, 38a328, Surge-watchOS, generic/platform=watchOS
02:04:20   FAIL: Surge, 5.0, 38a328, Surge-tvOS, generic/platform=tvOS
02:04:20   FAIL: Surge, 5.0, 38a328, Surge-macOS, generic/platform=macOS
02:04:20   FAIL: Surge, 5.0, 38a328, Surge-iOS, generic/platform=iOS
02:04:20   FAIL: Surge, 4.2, 38a328, Surge-watchOS, generic/platform=watchOS
02:04:20   FAIL: Surge, 4.2, 38a328, Surge-tvOS, generic/platform=tvOS
02:04:20   FAIL: Surge, 4.2, 38a328, Surge-macOS, generic/platform=macOS
02:04:20   FAIL: Surge, 4.2, 38a328, Surge-iOS, generic/platform=iOS
02:04:20   FAIL: SwifterSwift, 4.0, d3c3fd, SwifterSwift-watchOS, generic/platform=watchOS
02:04:20   FAIL: SwifterSwift, 4.0, d3c3fd, SwifterSwift-tvOS, generic/platform=tvOS
02:04:20   FAIL: SwifterSwift, 4.0, d3c3fd, SwifterSwift-macOS, generic/platform=macOS
02:04:20   FAIL: SwifterSwift, 4.0, d3c3fd, SwifterSwift-iOS, generic/platform=iOS
```

**Comment by xedin** [comment]
@stephentyrone @airspeedswift Math functions PR introducted multiple source compatibility regressions in external and internal projects

**Comment by tkremenek** [comment]
Let's get the change reverted until we can resolve the source compatibility breaks before we land.  All API changes to the Standard Library should go through the compatibility suite before merging.

**Comment by xedin** [comment]
Looks like this is going to be a non-trivial revert because there are conflicts already. @stephentyrone would be the best person to do that.

**Comment by stephentyrone** [comment]
@xedin https://github.com/apple/swift/pull/23800

**Comment by xedin** [comment]
@stephentyrone thank you!

**Pull request closed without merging**
