### PR TITLE
[Distributed] avoid double typechecking dist func decl

### PR DESCRIPTION
**Pull request by ktoso**
Resolves rdar://90817485

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
@swift-ci please build toolchain macOS

**Review by DougGregor — APPROVED** [review]

**Comment by ktoso** [comment]
ok all good but just to be sure another full test run

@swift-ci please test and merge

**Comment by ktoso** [comment]
`  Swift(watchsimulator-i386) :: Sema/spi-available-inline.swift`

**Comment by ktoso** [comment]
@swift-ci please build toolchain macOS

Need a toolchain to verify if this helped resolve the radar.

**Comment by ktoso** [comment]
CI fixed in https://github.com/apple/swift/pull/42075

@swift-ci please build toolchain macOS

**Comment by ktoso** [comment]
mac CI hanged... `Cannot contact macos-node-i-018d7e169fd77215d: java.lang.InterruptedException`

**Pull request merged**
