### PR TITLE
Fix TaskLocal documentation issue

### PR DESCRIPTION
**Pull request by Kyle-Ye**
Fix some documentation issue on TaskLocal

### CODE REVIEW

**Comment by Kyle-Ye** [comment]
@swift-ci test

**Review by ktoso — COMMENTED** [review]
Thanks!

**Review by ktoso — APPROVED** [review]

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by Kyle-Ye** [comment]
Thanks for the quick response.

Also note another issue here:

The `TaskLocal-macro` is not working as expected here

SCR-20241204-nelh

We have a correct usage in Observable by using \`\`Observation/Observable()\`\`.

And we should use \`\`_Concurrency/TaskLocal()-swift.macro\`\` to refer the macro.

- _Concurrency can be omitted since we are in the same module
- `-swift` and `.macro` can also be omitted here as there is no conflict

> Source: https://www.swift.org/documentation/docc/linking-to-symbols-and-other-content

**Comment by Kyle-Ye** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Pull request merged**
