### PR TITLE
[CMake] Install swift-api-dump.py and FileCheck as executable

### PR DESCRIPTION
**Pull request by jrose-apple**
rdar://problem/28621658

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci smoke test

**Comment by jrose-apple** [comment]
@swift-ci build toolchain

**Review by Rostepher — APPROVED** [review]
This looks like a trivial change. Thanks for fixing this!

**Comment by jrose-apple** [comment]
…we don't ship either of those things in a normal toolchain build, so I can't see if there was a difference. 😭

@nkcsgexi, swift-api-checker.py might deserve the same treatment, but that can happen in a separate PR.

**Pull request merged**
