### PR TITLE
[gardening][(JSON|Plist)Encoder] Prefer `!isEmpty` over `count > 0`

### PR DESCRIPTION
**Pull request by ikesyo**

### CODE REVIEW

**Comment by ikesyo** [comment]
@swift-ci Please smoke test

**Comment by ikesyo** [comment]
@swift-ci smoke test

**Comment by ikesyo** [comment]
The failure looks unrelated.

@swift-ci Please clean smoke test Linux platform

**Review by itaiferber — COMMENTED** [review]
Thanks for taking the time to put this together; the change itself looks okay, but is there a concrete reason for the code churn?

**Comment by ikesyo** [comment]
@itaiferber I'm a fan of using `isEmpty` over checking `count` as described in the doc comments of `Collection.count`:

```swift
  /// The number of elements in the collection.
  ///
  /// To check whether a collection is empty, use its `isEmpty` property
  /// instead of comparing `count` to zero. Unless the collection guarantees
  /// random-access performance, calculating `count` can be an O(*n*)
  /// operation.
  ///
  /// - Complexity: O(1) if the collection conforms to
  ///   `RandomAccessCollection`; otherwise, O(*n*), where *n* is the length
  ///   of the collection.
```

Or the doc comments is not right or is misleading? Is that only about `count == 0` case and not about `count > 0`?

**Comment by ikesyo** [comment]
Ref: https://github.com/apple/swift/pull/15326

**Comment by ikesyo** [comment]
See also #12638.

**Comment by ikesyo** [comment]
Please let me know if I have overlooked something 😄

**Comment by harlanhaskins** [comment]
@itaiferber At the very least, changing the instance of `stringKey.count > 0` in `_convertToSnakeCase` is taking it from an `O(n)` operation to an `O(1)` operation.

**Comment by itaiferber** [comment]
From a correctness perspective, I don't disagree — it's just that our collections offer O(1) `count` and JSON keys are rarely long (and overwhelmingly often ASCII), so O(n) vs. O(1) won't make much of a difference there. Just trying to find a balance between correctness and code churn.

**Comment by itaiferber** [comment]
Please make a similar change over on https://github.com/apple/swift-corelibs-foundation, if you don't mind.

**Pull request merged**
