### PR TITLE
[6.0] Support Package CMO 

### PR DESCRIPTION
**Pull request by elsh**
This PR contains squashed commits of the following PRs that support Package CMO.

https://github.com/apple/swift/pull/74531
https://github.com/apple/swift/pull/74468
https://github.com/apple/swift/pull/74416
https://github.com/apple/swift/pull/74070
https://github.com/apple/swift/pull/73902
https://github.com/apple/swift/pull/73754
https://github.com/apple/swift/pull/73717
https://github.com/apple/swift/pull/72606
https://github.com/apple/swift/pull/73566
https://github.com/apple/swift/pull/73478
https://github.com/apple/swift/pull/73686
https://github.com/apple/swift/pull/72937
https://github.com/apple/swift/pull/73708
https://github.com/apple/swift/pull/73751
https://github.com/apple/swift/pull/73794

rdar://128647016&126877247

### CODE REVIEW

**Comment by elsh** [comment]
@swift-ci test

**Comment by elsh** [comment]
@swift-ci test

**Comment by elsh** [comment]
@swift-ci test windows

**Comment by elsh** [comment]
@swift-ci test

**Comment by elsh** [comment]
@swift-ci test windows

**Comment by nkcsgexi** [comment]
@swift-ci test

**Comment by elsh** [comment]
@swift-ci test

**Review by nkcsgexi — APPROVED** [review]

**Comment by elsh** [comment]
@swift-ci test

**Comment by elsh** [comment]
@swift-ci test windows

**Comment by elsh** [comment]
@swift-ci test

**Comment by elsh** [comment]
@swift-ci test macos

**Pull request merged**
