### PR TITLE
[AddressLowering] Don't end_borrow trivial args.

### PR DESCRIPTION
**Pull request by nate-chandler**
When loading an argument, first check whether its type is trivial.  If so, produce a `load [trivial]`.  Only then produce `load [take]`s or `load_borrow`s.  Fixes an issue where values passed @in_guaranteed were `load [trivial]`'d and then `end_borrow`'d.

Also added the inlining logging used in the performance inliner to the mandatory inliner.  It was used to track down this issue.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test macOS platform

**Comment by nate-chandler** [comment]
@swift-ci please clean test macOS platform

**Comment by nate-chandler** [comment]
@swift-ci please test and merge

**Review by atrick — APPROVED** [review]
Thanks. Incidentally, the emitLoadBorrow/emitEndBorrow helpers are supposed to do this for you.

**Pull request merged**
