### PR TITLE
Remove all references to unused LitRe tool

### PR DESCRIPTION
**Pull request by gwynne**
`CMakeLists.txt` and a few other things still refer to LitRe, a tool once used for validating examples in `.rst`-format documentation. No distribution of this tool still exists and nothing in Swift still depends on it or would be validated by its use, so remove all remaining references. As a bonus, in the process a duplicate redundant invocation of `find_program()` for `sphinx-build` is also removed.

### CODE REVIEW

**Comment by gottesmm** [comment]
Looks reasonable to me. @dabrahams I think is the one who committed this. Any objections DaveA?

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by dabrahams** [comment]
I'm a wholehearted endorser of this change.

**Review by gottesmm — APPROVED** [review]
Lets do this!

**Pull request merged**
