### PR TITLE
[ConstraintSystem] Improve the "transitive conformance" heuristic and remove early conformance checking from `DisjunctionStep::shouldSkip`

### PR DESCRIPTION
**Pull request by hborla**
The "transitive conformance" constraint is a generalization of the early conformance checking in `DisjunctionStep::shouldSkip`. The code in `DisjunctionStep` ignored the potential for implicit conversions if the best score is equal to the current score, because if the current path needs an implicit conversion to satisfy a conformance requirement, that score would be worse anyway. We can use this assumption when simplifying a transitive conformance constraint, and remove the conformance checking from `DisjunctionStep`.

### CODE REVIEW

**Comment by hborla** [comment]
@swift-ci please test source compatibility

**Comment by hborla** [comment]
@swift-ci please test compiler performance

**Review by xedin — APPROVED** [review]
Awesome!

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by hborla** [comment]
@swift-ci please test Windows platform

**Comment by hborla** [comment]
Not sure what's going on with the debug performance results, but an increase in constraint scopes in the release results is expected. With the old code, overloads were pruned in `DisjunctionStep` before the overload was attempted. With the new code, the overload is pruned right after it's attempted, so a new constraint scope will be created before the solver fails the transitive conformance constraint. This is fine, because the solver isn't actually exploring more space than before.

**Pull request merged**
