### PR TITLE
Fix CastOptimizer for guaranteed values while handling checked_cast_br

### PR DESCRIPTION
**Pull request by meg-gupta**
Fixes rdar://77684045

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci test Linux platform

**Comment by atrick** [comment]
In the interest of avoiding extra borrow scopes, I think we can replace the checked-cast's block argument (its terminator result) with the newly cast value instead of creating a degenerate phi.

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test Linux platform

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Comment by meg-gupta** [comment]
@atrick Sorry for the delay on this. I have fixed it by getting rid of the unnecessary borrow scope, and instead replace the success/failure value with the casted/original value.

**Review by atrick — APPROVED** [review]
Thanks!

**Pull request merged**
