### PR TITLE
[Driver] Add test for vfs path behavior (NFC)

### PR DESCRIPTION
**Pull request by keith**
This is a regression test for https://bugs.swift.org/browse/SR-15123

It depends on https://github.com/apple/llvm-project/pull/3536

### CODE REVIEW

**Comment by keith** [comment]
cc @dexonsmith

**Comment by keith** [comment]
cc @JDevlieghere

**Comment by kastiglione** [comment]
It seems we'd need to wait until https://github.com/apple/llvm-project/pull/3536 is merged before we can test this?

**Comment by keith** [comment]
Correct

**Comment by keith** [comment]
(it wouldn't hurt to verify it fails without it, but probably not worth the CPU time)

**Comment by kastiglione** [comment]
@swift-ci test

**Comment by kastiglione** [comment]
@swift-ci test Linux Platform

**Comment by MaxDesiatov** [comment]
@swift-ci test Linux Platform

**Comment by keith** [comment]
I think this one is good to merge if someone doesn't mind!

**Comment by kastiglione** [comment]
gonna re-test just to make sure, then I can merge.

**Comment by kastiglione** [comment]
@swift-ci test

**Comment by keith** [comment]
Thanks!

**Pull request merged**
