### PR TITLE
[build] Amend target options for common C flags

### PR DESCRIPTION
**Pull request by edymtt**
Follow up of #35406

Addresses rdar://73502059

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci please test

**Comment by edymtt** [comment]
@swift-ci please test windows

**Review by CodaFi — APPROVED** [review]
Heh, whoops. Thanks!

**Comment by edymtt** [comment]
@swift-ci please test windows

**Comment by edymtt** [comment]
@swift-ci please test macos

**Comment by edymtt** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by edymtt** [comment]
@swift-ci please test macos

**Comment by edymtt** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Pull request merged**
