### PR TITLE
[Sema] A couple more MiscDiagnostics cleanups/fixes

### LINKED ISSUE #77453: Duplicate statement diagnostics in result builder
The following gives a duplicate diagnostic:

```swift
@resultBuilder
struct Builder {
  static func buildBlock<T>(_ components: T...) -> T {
    components.first!
  }
  static func buildEither<T>(first component: T) -> T {
    component
  }
  static func buildEither<T>(second component: T) -> T {
    component
  }
}

func takesClosure(_ fn: () -> Void) -> Int? { nil }

@Builder
func foo() -> Int {
  if let x = takesClosure {} { // 2x warning: trailing closure in this context is confusable with the body of the statement
    0
  } else {
    1
  }
}
```

### LINKED ISSUE #77553: Existential spelling diagnostic missing for `catch`
This is an error:

```swift
protocol P {
  associatedtype X
}

func foo(_ x: Any) {
  switch x {
  case is P: // error: use of protocol 'P' as a type must be written 'any P'
    break
  default:
    break
  }
}
```

but this is currently allowed:

```swift
do {

} catch is P {}
```

We ought to raise the same error.

### PR DESCRIPTION
**Pull request by hamishknight**
- Avoid calling `performStmtDiagnostics` in CSApply, instead leaving it up to the SyntacticDiagnosticWalker
- Ensure we run `performStmtDiagnostics` for `catch` clauses, including allowing the ambiguous where clause diagnostic to be emitted for it
- Cleanup `diagnoseStmtAvailability` + `ExprAvailabilityWalker` a bit
- Make sure we visit MacroExpansionDecl args, I missed this in #77534

Resolves #77453
Resolves #77553

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
@swift-ci please test

**Review by tshortli — APPROVED** [review]
Availability changes look good.

**Review by xedin — APPROVED** [review]

**Pull request merged**
