### PR TITLE
[AutoDiff] Cleanup 4: Kill `#adjoint` expression.

### PR DESCRIPTION
**Pull request by rxwei**
`#adjoint` served us very well in building ML models when AD was not ready. Today, with generalized differentiability in place, we are proudly killing `#adjoint`.

### CODE REVIEW

**Review by dan-zheng — APPROVED** [review]

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Pull request merged**
