### PR TITLE
[DNM] Just for making a toolchain

### PR DESCRIPTION
**Pull request by gottesmm**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by gottesmm** [comment]
I am just using this to produce a toolchain for @cwakamo to test apple/swift-lldb#1268.

**Comment by gottesmm** [comment]
@swift-ci build toolchain

**Comment by gottesmm** [comment]
actually @dcci hasn't merged this to 5.0 yet, so the toolchain won't be the right one.

**Comment by atrick** [comment]
Actually the lldb change is merged to 5.0 but it isn't clear whether this build picked it up. Let's see if I can just restart the build.

**Comment by atrick** [comment]
@swift-ci build toolchain

**Comment by dcci** [comment]
@swift-ci please build toolchain 
https://github.com/apple/swift-lldb/pull/1265

**Comment by dcci** [comment]
@swift-ci build toolchain
apple/swift-lldb#1265

**Comment by dcci** [comment]
@swift-ci build toolchain
apple/swift-lldb#1265

**Comment by dcci** [comment]
apple/swift-lldb#1265

@swift-ci build toolchain

**Comment by shahmishal** [comment]
https://github.com/apple/swift-lldb/pull/1265
@swift-ci build toolchain

**Comment by gottesmm** [comment]
@dcci Can I close this?

**Pull request closed without merging**
