### PR TITLE
Update WindowsBuild.md

### PR DESCRIPTION
**Pull request by compnerd**
Add a workaround to try to reduce the path lengths a bit since it is unlikely that LLVM will accept changes to improve `lit` to support long paths on Windows.  There is strong opposition to improvements there from @rui314 and @nico at https://reviews.llvm.org/D57533 .

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @gottesmm @jrose-apple @gwynne 

Unfortunately, this means that we can't really support parallel builds, but the push back from @rui314 means that it is unlikely that we will be able to support reasonable paths in `lit` and a number of tests with long names using `%t` completely blow past the limited 251 characters.

**Comment by jrose-apple** [comment]
We can't use your Unicode path trick?

**Comment by compnerd** [comment]
@jrose-apple, yes, absolutely!  That is what my change to `lit` there does :-).  You use the NT path with a unicode encoding, and it does work to get through the build in my testing.  The problem is the resistance to adding that support in `lit`.

**Comment by gwynne** [comment]
I do understand the resistance, stuffing all that extra `ctypes` curd in there isn't really the loveliest look for the code. But it can be made much nicer (including that `llvm-rm` idea someone mentioned) and correct support for long paths on Windows isn't an issue that I see as going away.

**Comment by jrose-apple** [comment]
Ah, yeah, I meant if we could do some of that locally (in a way that isn't going to cause merge conflicts forever), by just changing particular substitutions. I didn't actually look to see if your patch changes the guts of lit or just the way it sets up the default substitutions.

**Comment by compnerd** [comment]
Oh, I don't think that we can do this in the substitutions, we need to change the actual implementation of `rm` in `lit` which is what I was doing.  I suspect that with the recent attempts to move `lit` to python3, we probably will get some conflicts as things get shuffled around.  But, if that is what we need to do, I can create a PR against swift-llvm for that (although, IMO, adding support for that in LLVM is the better thing to do to ensure that it is resilient against long paths in its own testing - and the chromium folks did hit that too).

**Comment by nico** [comment]
FWIW I'd be in favor of making an `rm` not a lit built-in on the llvm side, and then you can just use an `rm` that can handle long paths and things will work.

**Pull request merged**
