### PR TITLE
[gardening] 2017 -> current

### PR DESCRIPTION
**Pull request by AndrewSB**
I prefer this copyright notice to explicit upper bound dates that need
to be changed on a yearly cadence.

### CODE REVIEW

**Comment by xwu** [comment]
Copyright notices require actual dates; you can't just pre-emptively claim a copyright for every future year :P

**Comment by AndrewSB** [comment]
@xwu are you sure? I've seen companies that use this pattern

**Comment by xwu** [comment]
Not a lawyer, but better to be conservative on these matters, you know :)

**Comment by AndrewSB** [comment]
It probably is, they're only useful when there is an issue.
If someone at Apple wants to ask their legal team (cc @jrose-apple), The change would reduce the maintenance cost of someone remembering to do this every year.

**Comment by AndrewSB** [comment]
It probably is, they're only useful when there is an issue.
If someone at Apple wants to ask their legal team (cc @jrose-apple), The change would reduce the maintenance cost of someone remembering to do this every year.

**Comment by tkremenek** [comment]
I conferred with Apple's lawyers and they said this change was not OK.  We need to put the actual year.

Technically speaking,  the year or years listed are meant to correspond to the year(s) of first publication of the copyrighted work.  So if the file was not published in 2014 and didn’t even exist then, we should definitely not be putting that year on the copyright line. 

https://www.copyright.gov/circs/circ03.pdf

**Comment by AndrewSB** [comment]
Thanks for checking on this @tkremenek. I appreciate it.

**Pull request closed without merging**
