### PR TITLE
[test] Get Swift-Unit test suite to work

### PR DESCRIPTION
**Pull request by rintaro**
#### What's in this pull request?

Fix typo(?) in `test/Unit/lit.site.cfg.in`.
Use correct variable name.

`config.llvm_src_root` is unrelated.
Wrong `config.build_mode` was preventing `lit.discovery` from discovering test cases.

Error in CI console log:

```
lit.py: discovery.py:190: warning: test suite 'Swift-Unit' contained no tests
```

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by gribozavr** [comment]
@gottesmm Could you review please?

**Comment by rintaro** [comment]
Before  98db2cbca996177747308ef214fc6ed1b3ba6de6, `LLVM_BUILD_MODE` was set in `configure_lit_site_cfg`.
I'm not sure `SWIFT_BUILD_MODE` is equivalent to it.

**Comment by gottesmm** [comment]
This LGTM. I also double checked that those methods are not set anywhere else.

**Comment by gottesmm** [comment]
The linux failure is unrelated.

**Pull request merged**
