### PR TITLE
SIL: KeyPathInst has to have side effects, since it retains.

### PR DESCRIPTION
**Pull request by jckarter**
Fixes rdar://problem/31975279.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Comment by jckarter** [comment]
preset=buildbot,tools=RA,stdlib=RD
@swift-ci Please test macOS with preset

**Comment by jckarter** [comment]
@shahmishal Did I phrase the "with preset" command correctly? I'm trying to follow https://github.com/apple/swift/blob/master/docs/ContinuousIntegration.md#specific-preset-testing in order to reproduce a failure: https://ci.swift.org/view/Dashboard/job/oss-swift-4.0_tools-RA_stdlib-RD_test-simulator/53/consoleFull#-998457498fca400bf-2f4a-462e-b517-e058d770b2d7

**Comment by shahmishal** [comment]
Looks good! 

preset=buildbot,tools=RA,stdlib=RD
@swift-ci Please test macOS with preset

**Comment by shahmishal** [comment]
preset=buildbot,tools=RA,stdlib=RD
@swift-ci Please test macOS with preset

**Comment by jckarter** [comment]
@shahmishal Will the status show up in Github, or do I have to look at ci.swift.org?

**Comment by shahmishal** [comment]
> @shahmishal Will the status show up in Github, or do I have to look at ci.swift.org?
It should show up on GitHub, I am going to look into it.

**Pull request merged**
