### PR TITLE
[Macros] Mangle attached macros for accessors

### PR DESCRIPTION
**Pull request by DougGregor**
Attached macro mangles for accessors were using a fallback case that
triggers an assertion in +Asserts builds, and conflicting manglings is
non-Asserts builds. Provide a custom mangling for these cases that's
embedded in the identifier.

This is a narrow hack to eliminate an assertion. We are considering a
different approach for the long term that uses entity manglings with a
placeholder type, which will be more flexible long-term.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test macOS

**Comment by DougGregor** [comment]
https://github.com/apple/swift-driver/pull/1348

@swift-ci please smoke test macOS

**Comment by kastiglione** [comment]
Breadcrumbs, see followup: https://github.com/apple/swift/pull/70435.

**Pull request merged**
