### PR TITLE
[NFC] Flatten conditionals in convertBeginApplyWithOpaqueYield.

### PR DESCRIPTION
**Pull request by nate-chandler**
De-nested the expressions in convertBeginApplyWithOpaqueYield, noting which cases are handled.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test and merge

**Comment by nate-chandler** [comment]
@swift-ci please test and merge

**Review by atrick — COMMENTED** [review]
Thanks

**Pull request merged**
