### PR TITLE
[4.2][CSRanking] Swift 4.1 compatibility hack for favouring properties on concrete types over protocols

### PR DESCRIPTION
**Pull request by hamishknight**
*(4.2 cherry-pick of #18952)*

- Explanation: For some protocol `P` and non-conforming class `C` where both types declare a property `foo`, in contexts where members from both `C` and `P` are accessible, an access to `foo` would be considered ambiguous.

- Scope: Resolves a 4.2 source compatibility regression.

- SR Issue: [SR-7425](https://bugs.swift.org/browse/SR-7425)

- Risk: Low – the added logic is narrow and specifically designed not to introduce any new ambiguities.

- Testing: Added tests for Swift 4 property overloading behaviour, Test suite, Compatibility suite

- Reviewers: @rudkx

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@rudkx Looks like the Linux test timed out, could you try again?

**Comment by rudkx** [comment]
@swift-ci Please smoke test Linux platform

**Comment by hamishknight** [comment]
@rudkx As I understand it, it's the full Linux test that needs re-running – could you please kick it off?

**Comment by rudkx** [comment]
Ah yes, I always reach for the "saved reply" for smoke testing.

**Comment by rudkx** [comment]
@swift-ci Please test Linux platform

**Comment by hamishknight** [comment]
Any news on this (and #19562)? I don't know when the cut off point for getting stuff into 4.2.1 is, so I don't know how urgent it is.

**Comment by tkremenek** [comment]
I sincerely apologize for now seeing this sooner, and I appreciate you filing the PR.

Swift 4.2.1 is a very focused release, and there are always a chance of regressions being introduced by changes like this.  We should hold this fix to Swift 5.

**Pull request closed without merging**
