### PR TITLE
Sema: Properly handle inference for abstract fixed type witnesses

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
This fixes inference for some fixed type witness chains - SR-10831, for example:
```swift
protocol P {
  associatedtype A
  associatedtype B
}
protocol Q: P where A == G<B> {}
protocol R: Q where B == Int {}

struct Foo: R {} // OK
```

And adds inference of fixed type witnesses containing `Self` - SR-11671:
```swift 
protocol P {
  associatedtype A
}
protocol Q: P where A == Self {}

struct Foo: Q {} // OK, Self == Foo
```
@slavapestov

### CODE REVIEW

**Comment by AnthonyLatsis** [comment]
@jckarter Can you take a quick look?

**Comment by AnthonyLatsis** [comment]
@slavapestov bumping this up in case you have some bandwidth

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by AnthonyLatsis** [comment]
After almost a year I can tell the approach here is flawed and quite narrow. Closing to revisit this once we settle on the implementation details of a new conformance checker.

**Pull request closed without merging**
