### PR TITLE
Fix copy_value to have 'None' side-effects.

### PR DESCRIPTION
**Pull request by atrick**
Copies can be moved as much as you like as long as OSSA is legal.

This fixes some instruction deletion utilities for OSSA and any other
utilities that check side effects. Copies are common.

It also finally allows pure functions to be CSE'd!

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci benchmark

**Comment by atrick** [comment]
I need to figure out why this miscompiles libswift_Concurrency. I think there's a missing manual retain somewhere in the implementation.

**Review by eeckstein — APPROVED** [review]
LGTM!

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci benchmark

**Comment by atrick** [comment]
@swift-ci smoke test

**Comment by atrick** [comment]
@swift-ci benchmark

**Comment by atrick** [comment]
The benchmark regression is being worked on in parallel.
rdar://80746149 (Fix 90% performance regression in benchmark DictionaryOfAnyHashableStrings_insert)

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
Other PRs are hitting the same Linux test failure:
validation-test/IDE/slow/rdar45511835.swift:13:11: error: CHECK: expected string not found in input

**Comment by atrick** [comment]
@swift-ci benchmark

**Pull request merged**
