### PR TITLE
Revert "Revert "[LTO] Build lld on Windows CI""

### PR DESCRIPTION
**Pull request by kateinoigakukun**
This reverts commit 8c9649eb95751ba5f3cede15976b9c60e034eed3.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by kateinoigakukun** [comment]
Hmm, please try again CI 🙏

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by marcioejade** [comment]
Obrigado

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Pull request merged**
