### PR TITLE
Correcting the hyperlink to redirect

### PR DESCRIPTION
**Pull request by KrishMunot**

### CODE REVIEW

**Comment by jrose-apple** [comment]
You're missing a "the" before "code of conduct", and for consistency with itself (if not much of the internet) "Swift.org" *should* be capitalized.

Sorry to continue dragging this out!

(Also, feel free to just squash commits and update the existing pull request rather than making a new one.)

**Comment by KrishMunot** [comment]
I am sorry for all the trouble. I have made the necessary changes. 
Thanks! :)

**Comment by jrose-apple** [comment]
Didn't this all start because you wanted the "the" outside the link? :-) @mattt did agree with you there. What do you think?

**Comment by KrishMunot** [comment]
Haha! We are back to square one then. :) His statement didn't explicitly support my argument, although I think I must have missed out some meaning out there. 
Just made the correction and made a commit.

**Comment by jrose-apple** [comment]
Great. Let's go with this. Can you squash all the changes into a single commit? (You can force-push to update your pull request branch.)

**Comment by KrishMunot** [comment]
I am so sorry for the late update. There were a lot of merge conflicts and complexities and I am unable to squash all my commits to one.
I am submitting a new pull request to resolve this.

**Comment by johnantoni** [comment]
cool, let me know @KrishMunot if you want a hand with this

**Comment by KrishMunot** [comment]
@johnantoni I am looking into this and will update in a day or two. Thanks! :)

**Comment by KrishMunot** [comment]
Thanks @jrose-apple and @johnantoni , I have resolved this issue in another [PR](https://github.com/apple/swift/pull/2131/commits/d2e98f46338e655d715c548b676700e0a071c695) which is now merged

**Pull request closed without merging**
