### PR TITLE
 [Foundation] Collapse (SignedInteger|UnsignedInteger) reqts into FixedWidthInteger

### PR DESCRIPTION
**Pull request by DougGregor**
Simplify the default implementations provided for RawRepresentable
error types whose raw values are integral, replacing duplicated code
(for SignedInteger or UnsignedInteger) with a single constraint on
BinaryInteger.

Fixes rdar://problem/35230187.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Review by jrose-apple — CHANGES_REQUESTED** [review]
I remember looking at making this change and deciding that it did the wrong thing for unsigned integers. Since the code is just a bit pattern, you want to reinterpret-cast between Int and the raw type rather than numeric-cast.

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test Linux

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please smoke test Linux

**Comment by DougGregor** [comment]
@swift-ci please smoke test Linux

**Comment by DougGregor** [comment]
@swift-ci please smoke test Linux

**Comment by DougGregor** [comment]
@swift-ci please smoke test Linux

**Comment by DougGregor** [comment]
@swift-ci please smoke test Linux

**Review by jrose-apple — APPROVED** [review]
I guess this works. Don't forget to update corelibs Foundation too.

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
Corelibs Foundation bit is in https://github.com/apple/swift-corelibs-foundation/pull/1675

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Pull request merged**
