### PR TITLE
Add implicit conversions and casts from T:Hashable <-> AnyHashable.

### PR DESCRIPTION
**Pull request by jckarter**
rdar://27615802

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Comment by tkremenek** [comment]
@swift-ci test OS X

**Comment by DougGregor** [comment]
@swift-ci please test Linux

**Comment by DougGregor** [comment]
The Linux failure is a CI issue that Mishal is looking into, and it already passed the smoke test there. Force-merging because I need to build on this.

**Pull request merged**
