### PR TITLE
Sema: Fix dynamic Self behavior for a «super» base expression

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
Resolves SR-1736.

Also discovered another bug along the way: SR-14295

### CODE REVIEW

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test macOS

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test macOS

**Comment by AnthonyLatsis** [comment]
@swift-ci please clean smoke test macOS

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Comment by AnthonyLatsis** [comment]
I wonder what's causing these spurious compilation errors..

**Comment by slavapestov** [comment]
I think super.init() and self.init() in a static method are OK. They’re basically the same as MyClass.init(), and not the special delegation syntax inside an initializer.

**Comment by AnthonyLatsis** [comment]
> I think super.init() and self.init() in a static method are OK. They’re basically the same as MyClass.init(), and not the special delegation syntax inside an initializer.

I thought so too, but there is still the issue with the 'super' case currently creating an object of type `Self`.

**Comment by slavapestov** [comment]
Calling a non-required initializer on DynamicSelfType should be an error, just like if you tried to do it on a metatype value or a class-constrained archetype.

**Comment by AnthonyLatsis** [comment]
Sorry, I meant that even if `super.init()` is intentionally allowed within a static method, there is still this bug where it creates an object the 'Self' type:

```
class A {
  required init() {}
}
class B: A {
  static func staticMethod() {
    let foo = super.init()
    print(foo is B) // true
  }
}

```

**Comment by AnthonyLatsis** [comment]
@slavapestov After a bit of thought, I think we shouldn't allow it after all, because even though we dispatch statically with 'super', it's still not a statically derived metatype inside a static method.

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Review by xedin — APPROVED** [review]
LGTM!

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Comment by AnthonyLatsis** [comment]
@xedin Thanks for giving this an eye!

**Pull request merged**
