### PR TITLE
IRGen: remove ELF autolink discard gadget

### PR DESCRIPTION
**Pull request by compnerd**
The ELF autolink section was previously relying on the SHF_EXCLUDE flag
being applied through module-level assembly.  Remove this gadget and
sink the handling down into LLVM.  The latest improvements to LLVM now
cause this workaround to be insufficient as the section is explicitly
marked as SHF_ALLOC, which will implicitly negate the SHF_EXCLUDE.  As a
result, we no longer discard the metadata.  Once this is sunk into LLVM
the attribute is unnecessary.  Furthermore, due to uniquing, will
actually cause a problem as there is no uniform handling for metadata
section prefixes.

rdar://82640394

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
Please test with following PRs:
apple/llvm-project#3249

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/llvm-project#3249

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/llvm-project#3249

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/llvm-project#3249

@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/llvm-project#3249

@swift-ci please clean test Linux platform

**Comment by compnerd** [comment]
This  does fix the particular issue it set out to fix: check-swift-all-optimize-linux-x86_64 passes now.  It should at least enable further work on the rebranch.  I am merging this for now; if I have misinterpreted the results, we can revert the changes.

CC: @etcwilde

**Comment by etcwilde** [comment]
LGTM. It looks like we're just getting further through the build now.

**Pull request merged**
