### PR TITLE
[Python: flake8] Update the utils/python_lint.py script to fail with a non-zero exit code if flake8 and flake8-import-order are not installed.

### PR DESCRIPTION
**Pull request by Rostepher**

### CODE REVIEW

**Comment by Rostepher** [comment]
@swift-ci please smoke test

**Review by compnerd — APPROVED** [review]

**Review by shahmishal — APPROVED** [review]

**Comment by shahmishal** [comment]
We should execute this test on macOS or Linux, we dont need to run it twice.

**Comment by shahmishal** [comment]
Recommenced macOS

**Comment by Rostepher** [comment]
Looks like the Linux tests failed because they don't have flake8 installed.

**Comment by shahmishal** [comment]
> Looks like the Linux tests failed because they don't have flake8 installed.

I would recommend setting the test to only run on macOS, because we dont currently have flake8 installed.

**Comment by Rostepher** [comment]
@swift-ci please smoke test

**Comment by Rostepher** [comment]
So for historical reasons the `utils/gyb.py` and `utils/line-directive` scripts were linting themselves in their doctests. Since we run a `flake8` lint pass over both of those scripts in the `validation-test/Python/python_lint.swift` test it's no longer necessary to have those scripts lint themselves.

Per an offline discussion with @Mishal I've also set the Python lint test to run _only_ on macOS for the time being. In the future we can install `flake8` on the Linux bots and run this test there.

**Comment by Rostepher** [comment]
@swift-ci please smoke test Linux platform

**Pull request merged**
