### PR TITLE
[Sema][SR-14096] Change conditions in which key path component mismatch fix are diagnosed

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
We were [skipping](https://github.com/apple/swift/blob/c5a751212d3ec8c144c5022733eeb05c44958dc3/lib/Sema/CSSimplify.cpp#L3801) diagnostics for cases where the key path type was a function which result was equal the contextual key path value or function result type (key path as function). So in cases where this is the only constraint failing, that would lead type check an incorrect value type, leading to hit an assertion is `CSApply`.
Example:
```swift
extension String {
  var boolean : (Self) throws -> Bool {
    { $0.contains("a") }
  }
  var integer : (Self) throws -> Int {
    { $0.count }
  }
}
let a : [String] = [ "asd", "bcd", "def" ]

_ = a.filter(\.integer) // correctly diagnosed 
_ = a.filter(\.boolean) // diagnostic skipped since (String)-> Bool result Bool is equal contextual type expected 
}
```

So in this PR we remove this check (in fact we change the check) to make sure this is diagnosed correctly.
Also, a tailored diagnostic on argument mismatch for key path as function. 

Resolves SR-14096.

### CODE REVIEW

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test MacOS platform

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test Windows

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test Windows platform

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test Linux platform

**Review by xedin — APPROVED** [review]
Great! Thank you!

**Pull request merged**
