### PR TITLE
[SILGen] Add SILDeclRef for main entry-point

### PR DESCRIPTION
**Pull request by hamishknight**
Allow SILDeclRef to refer to the main program entry-point, which will either be for a main SourceFile, or a synthetic main such as an `@main` decl. Adjust the various SILDeclRef related functions to handle this new case, and change the emission to go through `emitFunctionDefinition`.

This change will allow the entry-point for an `@main` decl (and eventually a main SourceFile) to be emitted on-demand from its symbol name.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test macOS

**Review by CodaFi — APPROVED** [review]
I like that we're using more of the built-in machinery in SILGen to emit this entrypoint. The changes here look good, in particular to TBDGen. I'm going to tag @eeckstein for a closer look at the SILDeclRef representation changes for which I have much less experience.

**Review by eeckstein — APPROVED** [review]
LGTM, though it would be good if @slavapestov could also take a look.

**Review by slavapestov — APPROVED** [review]

**Comment by hamishknight** [comment]
@swift-ci please test

**Pull request merged**
