### PR TITLE
[Sema] Check protocol conformance availability for member reference and type erasing expressions

### PR DESCRIPTION
**Pull request by tshortli**
Diagnose uses of potentially unavailable protocol conformances in member reference expressions (`x.foo` where `foo` is a property of `x`) and type erasure expressions (`let p: P = S` where `S` conforms to `P`) since unguarded uses of these conformances can cause crashes at runtime.

Expands conformance availability tests to include test cases covering member references, key paths, and invocation of functions taking existentials.

Resolves rdar://87795154 and rdar://83731428.

### CODE REVIEW

**Comment by tshortli** [comment]
@swift-ci please smoke test

**Comment by tshortli** [comment]
@swift-ci please smoke test

**Review by slavapestov — APPROVED** [review]
Nice catch! IIRC there is another missing case with ErasureExpr that occurs when forming an existential from a concrete type, if the concrete type's conformance to the protocol is not available.

**Comment by tshortli** [comment]
> Nice catch! IIRC there is another missing case with ErasureExpr that occurs when forming an existential from a concrete type, if the concrete type's conformance to the protocol is not available.

Thanks! I'll see what it would take to expand this to cover that expression as well.

**Comment by slavapestov** [comment]
@tshortli here is @beccadax's radar for that one by the way: rdar://83731428

**Comment by tshortli** [comment]
@swift-ci please smoke test

**Comment by tshortli** [comment]
@swift-ci please smoke test

**Comment by tshortli** [comment]
@swift-ci please test macOS

**Comment by tshortli** [comment]
@swift-ci please smoke test macOS

**Review by slavapestov — APPROVED** [review]

**Pull request merged**
