### PR TITLE
ArrayElementValuePropagation: explicitly reserve space for new elements when doing the array-content-of optimization

### PR DESCRIPTION
**Pull request by eeckstein**
When Array.append(contentOf:) is replaced by individual Array.append(element) calls, an explicit reserveCapacityForAppend is inserted.

Also improve some SILCombine/SimplifyCFG enum-related optimizations to deal with the slightly different code.

This changes are mostly neutral for most of our benchmarks.
Except for ArrayPlusEqualThreeElements, where it gives a 2.5x improvement.

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci Please smoke benchmark

**Comment by eeckstein** [comment]
@swift-ci Please smoke test

**Comment by eeckstein** [comment]
@swift-ci Please smoke test linux

**Comment by eeckstein** [comment]
@dabrahams There is a change in stdlib Array. Can you please look at that?

**Comment by med69** [comment]
العمل الجماعي

**Comment by eeckstein** [comment]
@swift-ci Please smoke test and merge

**Comment by med69** [comment]
العمل الجماعي

**Comment by eeckstein** [comment]
@swiftix Thanks, https://github.com/apple/swift/pull/9088

**Pull request merged**
