### PR TITLE
[update-checkout] Allow --dump-hashes to skip directories.

### PR DESCRIPTION
**Pull request by jrose-apple**
If I don't have certain things checked out, it shouldn't crash.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Comment by gottesmm** [comment]
@jrose-apple Maybe emit a warning?

**Comment by gottesmm** [comment]
Also, can you create a tmp variable for:

```
os.path.join(SWIFT_SOURCE_ROOT, repo_name)
```

**Comment by jrose-apple** [comment]
Hm. I deliberately don't have certain things checked out, so I wouldn't want it to be a warning per se. How about just emitting the line as `ninja   -` or `ninja   (not checked out)` or something?

**Comment by gottesmm** [comment]
@jrose-apple SGTM!

**Comment by gottesmm** [comment]
[to the ninja (not checked out) option]

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test and merge

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test and merge

**Pull request merged**
