### PR TITLE
Sema: Various TypeRefinementContext tree fixes

### PR DESCRIPTION
**Pull request by tshortli**
There were a number of ways that the tree produced by `TypeRefinementContextBuilder` could be malformed:
- Overlapping sibling nodes for enum cases that contain more than one element.
- Overlapping sibling nodes for var decls with pattern binding decl as parents.
- In multi-file compilation jobs, entire duplicate subtrees of the root node for a source file.

Fortunately, because the duplicated tree content was always ordered after the canonical child, the malformed trees never resulted in incorrect query results. Building the extra nodes did waste CPU and memory, though.

### CODE REVIEW

**Comment by tshortli** [comment]
@swift-ci please smoke test

**Comment by tshortli** [comment]
@swift-ci please smoke test

**Review by slavapestov — APPROVED** [review]
ASTScope has some logic that runs in asserts builds that ensures each child node is a subrange of its parents, and that children are disjoint, etc. Maybe we can try adding something similar here?

**Comment by tshortli** [comment]
These fixes actually came out of writing a verifier for the `TypeRefinementContext` tree. I'm still working on cleaning up the verifier and a few other things about TRCs but I wanted to get these fixes in separately since they're improvement

**Comment by slavapestov** [comment]
Awesome!

**Comment by tshortli** [comment]
https://github.com/swiftlang/swift-driver/pull/1702

@swift-ci please smoke test Linux

**Comment by tshortli** [comment]
https://github.com/swiftlang/swift-syntax/pull/2858

@swift-ci please smoke test Linux

**Pull request merged**
