### PR TITLE
[gardening] Use American English.

### PR DESCRIPTION
**Pull request by practicalswift**

### CODE REVIEW

**Comment by practicalswift** [comment]
@swift-ci please smoke test

**Comment by practicalswift** [comment]
@swift-ci please test

**Review by troughton — CHANGES_REQUESTED** [review]
The alteration of 'analyses' to 'analyzes' is incorrect in many places here; analyses is used as a noun (being the plural of analysis), while the Americanisation only applies to its use as a verb. For instance, "analyzes that benefit..." should stay "analyses that benefit", but "by analysing" should change to "by analyzing".

**Comment by practicalswift** [comment]
@troughton Whoops! Thanks for reviewing. Could you review the remaining changes? Looks good? :-)

**Comment by practicalswift** [comment]
@swift-ci please smoke test

**Review by troughton — APPROVED** [review]
Everything here looks fine to me.

**Comment by practicalswift** [comment]
@swift-ci please smoke test

**Comment by practicalswift** [comment]
@swift-ci please smoke test and merge

**Comment by practicalswift** [comment]
@swift-ci please test and merge

**Comment by practicalswift** [comment]
@swift-ci please test

**Comment by practicalswift** [comment]
@swift-ci Please smoke test Linux platform

**Comment by practicalswift** [comment]
@swift-ci Please test Linux platform

**Pull request merged**
