### PR TITLE
[test] Disable UnicodeLongTest.swift on watchos

### PR DESCRIPTION
**Pull request by milseman**
rdar://problem/46609532

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please test

**Review by jrose-apple — APPROVED** [review]

**Comment by jrose-apple** [comment]
Is there *somewhere* we run this test on a 32-bit platform, though? Can we allow it on the watch simulator but not the watch device or something?

**Comment by milseman** [comment]
How would I do that?

**Comment by jrose-apple** [comment]
`UNSUPPORTED: OS=watchos && CPU=armv7k` or something? But try it out locally to make sure it's still working in the simulator, then.

**Comment by milseman** [comment]
@swift-ci please test

**Pull request merged**
