### PR TITLE
Support translateAndImplodeIntoAny under opaque value mode

### PR DESCRIPTION
**Pull request by shajrawi**
Small part of radar rdar://problem/30080769

This PR adds support for translating and imploding into Any under opaque value mode

### CODE REVIEW

**Comment by shajrawi** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
Can you maybe add additional RUN lines to some existing SILGen tests to run them under opaque value mode (and ignore the CHECK: lines), instead of adding all new tests?

**Comment by slavapestov** [comment]
I think eventually we want to keep existing SILGen tests since they cover a lot of ground, even if the CHECK: lines become obsolete.

**Comment by shajrawi** [comment]
That's the long term plan I had in mind, yes: all current SILGen test should have an opaque value(s) mode as an additional RUN line.
For now I am creating small(er) test(s) in one area to for a more readable / understandable test during development.

**Pull request merged**
