### PR TITLE
Build.ps1: More detailed exception printing

### PR DESCRIPTION
**Pull request by tristanlabelle**
This should help diagnose errors such as in https://ci-external.swift.org/job/swift-main-windows-toolchain/34/console :
```
C:\Users\swift-ci\jenkins\workspace\swift-main-windows-toolchain\swift\utils\build.ps1 : Exception calling 
"DownloadFile" with "2" argument(s): "An exception occurred during a WebClient request."
    + CategoryInfo          : NotSpecified: (:) [build.ps1], MethodInvocationException
    + FullyQualifiedErrorId : WebException,build.ps1
```

Here's an example output from a synthetic DownloadFile failure:
image

### CODE REVIEW

**Review by compnerd — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
CC: @shahmishal

**Comment by compnerd** [comment]
@swift-ci please smoke test Linux platform

**Comment by compnerd** [comment]
@swift-ci please smoke test macOS platform

**Comment by shahmishal** [comment]
Thanks I just merged it as it only impacts Windows CI.

**Pull request merged**
