### PR TITLE
Sema: Check conformance availability when ranking solutions

### PR DESCRIPTION
**Pull request by slavapestov**
This completes the work on <rdar://problem/35158274>, and also
adds a test case for <rdar://problem/50627401>.

### CODE REVIEW

**Review by xedin — APPROVED** [review]
Nice!

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please clean test Linux

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please clean smoke test Linux

**Pull request merged**
