### PR TITLE
Enable import of the _Concurrency module by default.

### PR DESCRIPTION
**Pull request by DougGregor**

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by drexin** [comment]
@swift-ci test linux

**Comment by drexin** [comment]
@swift-ci test windows

**Comment by drexin** [comment]
Linux failed with

```
23:33:27 ---
23:33:27 3.	While evaluating request ExecuteSILPipelineRequest(Run pipelines { PrepareOptimizationPasses, EarlyModulePasses, HighLevel,Function+EarlyLoopOpt, HighLevel,Module+StackPromote, Serialize, MidLevel,Function, ClosureSpecialize, LowLevel,Function, LateLoopOpt, SIL Debug Info Generator } on SIL for Foundation.Foundation)
23:33:27 4.	While running pass #25160 SILFunctionTransform "DCE" on SILFunction "@$s10Foundation10FileHandleC25readInBackgroundAndNotify8forModesySayAA7RunLoopC4ModeVGSg_tFy8Dispatch0N4DataV_s5Int32VtcfU_yycfU_Tf2nin_n".
23:33:27  for expression at [/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/swift-corelibs-foundation/Sources/Foundation/FileHandle.swift:878:38 - line:880:13] RangeText="{
23:33:27                 NotificationQueue.default.enqueue(Notification(name: FileHandle.readCompletionNotification, object: self, userInfo: userInfo), postingStyle: .asap, coalesceMask: .none, forModes: modes)
23:33:27             "
23:33:27  #0 0x0000000005a231f3 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0x5a231f3)
23:33:27  #1 0x0000000005a21300 llvm::sys::RunSignalHandlers() (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0x5a21300)
23:33:27  #2 0x0000000005a2357a SignalHandler(int) (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0x5a2357a)
23:33:27  #3 0x00007f749994b390 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11390)
23:33:27  #4 0x00007f74984ca438 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x35438)
23:33:27  #5 0x00007f74984cc03a abort (/lib/x86_64-linux-gnu/libc.so.6+0x3703a)
23:33:27  #6 0x00007f74984c2be7 (/lib/x86_64-linux-gnu/libc.so.6+0x2dbe7)
23:33:27  #7 0x00007f74984c2c92 (/lib/x86_64-linux-gnu/libc.so.6+0x2dc92)
23:33:27  #8 0x0000000000e32caf (anonymous namespace)::DCE::markValueLive(swift::SILValue) (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0xe32caf)
23:33:27  #9 0x0000000000e2ebfb (anonymous namespace)::DCEPass::run() (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0xe2ebfb)
23:33:27 #10 0x0000000000d8d022 swift::SILPassManager::runPassOnFunction(unsigned int, swift::SILFunction*) (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0xd8d022)
23:33:27 #11 0x0000000000d8de71 swift::SILPassManager::runFunctionPasses(unsigned int, unsigned int) (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0xd8de71)
23:33:27 #12 0x0000000000d90700 swift::SILPassManager::execute() (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0xd90700)
23:33:27 #13 0x0000000000d8bac1 swift::SILPassManager::executePassPipelinePlan(swift::SILPassPipelinePlan const&) (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0xd8bac1)
23:33:27 #14 0x0000000000d8b8eb swift::ExecuteSILPipelineRequest::evaluate(swift::Evaluator&, swift::SILPipelineExecutionDescriptor) const (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0xd8b8eb)
23:33:27 #15 0x0000000000da65ab swift::SimpleRequest<swift::ExecuteSILPipelineRequest, std::tuple<> (swift::SILPipelineExecutionDescriptor), (swift::RequestFlags)1>::evaluateRequest(swift::ExecuteSILPipelineRequest const&, swift::Evaluator&) (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0xda65ab)
23:33:27 #16 0x0000000000d9556d llvm::Expected<swift::ExecuteSILPipelineRequest::OutputType> swift::Evaluator::getResultUncached<swift::ExecuteSILPipelineRequest>(swift::ExecuteSILPipelineRequest const&) (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0xd9556d)
23:33:27 #17 0x0000000000d8bba5 swift::executePassPipelinePlan(swift::SILModule*, swift::SILPassPipelinePlan const&, bool, swift::irgen::IRGenModule*) (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0xd8bba5)
23:33:27 #18 0x0000000000d96eff swift::runSILOptimizationPasses(swift::SILModule&) (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0xd96eff)
23:33:27 #19 0x000000000070ca52 swift::CompilerInstance::performSILProcessing(swift::SILModule*) (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0x70ca52)
23:33:27 #20 0x0000000000586537 performCompileStepsPostSILGen(swift::CompilerInstance&, std::unique_ptr<swift::SILModule, std::default_delete<swift::SILModule> >, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::PrimarySpecificPaths const&, int&, swift::FrontendObserver*) (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0x586537)
23:33:27 #21 0x0000000000585df8 performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0x585df8)
23:33:27 #22 0x000000000057992f swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0x57992f)
23:33:27 #23 0x00000000004d3945 main (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0x4d3945)
23:33:27 #24 0x00007f74984b5840 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20840)
23:33:27 #25 0x00000000004d3569 _start (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0x4d3569)
23:33:27 
<unknown>:0: error: unable to execute command: Aborted
```

**Comment by DougGregor** [comment]
Hmm. Those DCE failures were happening elsewhere, too

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test Linux

**Comment by DougGregor** [comment]
@swift-ci please test macOS

**Pull request merged**
