### PR TITLE
[SILGen] Don't SILGen an @objc entry point for a deinit with no body

### PR DESCRIPTION
**Pull request by jrose-apple**
In general we'll want to investigate what we are and aren't SILGen-ing for textual interfaces of resilient modules, but for fragile modules we may as well generate everything we can for potential optimization purposes.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Review by harlanhaskins — APPROVED** [review]

**Comment by jrose-apple** [comment]
…\*sigh\* right.

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Review by slavapestov — COMMENTED** [review]
Why is this specific to destructors? Does constructor and method emission need similar checks?

**Comment by jrose-apple** [comment]
Hm. We have been testing those with non-`@objc` entry points, but not with `@objc`. I'll add that.

(Right now we're mostly trying to get the stdlib and overlays all building successfully, and this one came up in Foundation while the others didn't. But that doesn't mean we shouldn't have tests.)

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
Uh, hm, that's fun. I guess we're emitting unnecessary thunks for constructors too, but it's only a problem on Linux!

**Comment by jrose-apple** [comment]
Filed [SR-8877](https://bugs.swift.org/browse/SR-8877) for the Linux failure. I want to get the console output before moving on, so

@swift-ci Please smoke test Linux

**Comment by jrose-apple** [comment]
[Linux CI run on old test file](
https://ci.swift.org/job/swift-PR-Linux-smoke-test/10095/)

@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
Ugh, right, that kills the previous job for normal tests. Oh well.

**Pull request merged**
