### PR TITLE
Add getPtrOr to NullablePtr

### PR DESCRIPTION
**Pull request by davidungar**
Add convenience method, `getPtrOr` to `NullablePtr` and change `getPtrOrNull` to use it.

### CODE REVIEW

**Comment by davidungar** [comment]
@gottesmm Michael, I've been using `NullablePtr` a lot; really like it. I'd like to add a convenience method to it, `getPtrOr`. Would you care to review?

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Review by gottesmm — APPROVED** [review]
LGTM

**Comment by davidungar** [comment]
Thanks, Michael.

**Pull request merged**
