### PR TITLE
[build-script] Respect TOOLCHAINS environment variable

### PR DESCRIPTION
**Pull request by Rostepher**
# Purpose

This PR modifies `build-script` to respect the environment variable `TOOLCHAINS`. If the `--darwin-xcrun-toolchain` flag is used then the environment variable will be ignored in favor of the explicit command line option.

I've also fixed the hardcoded toolchain in `test/lit.cfg`, which explicitly overwrites the `TOOLCHAINS` environment variable with `default` rather than passing the `config.darwin_xcrun_toolchain` or examining the system environment.

rdar://24795244
rdar://23397534

### CODE REVIEW

**Comment by Rostepher** [comment]
@swift-ci please test

**Review by shahmishal — APPROVED** [review]
LGTM!

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
@swift-ci build toolchain

**Comment by shahmishal** [comment]
@Rostepher Sorry! I hit the wrong button.

**Comment by shahmishal** [comment]
@swift-ci build toolchain

**Comment by shahmishal** [comment]
@swift-ci build toolchain

**Pull request merged**
