### PR TITLE
[CodeCompletion] Always look into decls to find the parsed expression

### PR DESCRIPTION
**Pull request by rintaro**
In fast completion scenario, `AbstractFunctionDecl` may have the body from the different file than the decl itself. That may confuses source range checking.

As a workaround, always look into decls regardless of the range. This should not regress the speed of the searching much because statements/expressions (including the nested function bodies) in the decl is still skipped if they are outside the range.

rdar://problem/58098222

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@benlangmuir Another solution is to only check  the end loc (i.e. `!SM.isBeforeInBuffer(Node->getEndLoc, TargetRange)`)  because,  in the case, the end loc points `}` and it's from the same buffer as the parse expression. However it's just a coincidence, and perhaps we might want to use the brace `{ ... }` locations from the original buffer, for some reasons.
What do you think?

**Review by benlangmuir — APPROVED** [review]
LGTM as a workaround

**Pull request merged**
