### PR TITLE
[5.3] [Function builders] Infer function builder from a protocol requirement.

### PR DESCRIPTION
**Pull request by DougGregor**
Allow a protocol requirement for a function or property to declare
a function builder. A witness to such a protocol requirement will
infer that function builder when all of the following are two:
* The witness does not explicitly adopt a function builder
* The witness is declared within the same context that conforms to the
protocol requirement (e.g., same extension or primary type declaration)
* The witness's body does not contain a "return" statement (since those
disable the function builder transform).

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test macOS

**Comment by DougGregor** [comment]
@swift-ci test

**Comment by DougGregor** [comment]
@swift-ci test

**Comment by DougGregor** [comment]
@swift-ci test

**Comment by DougGregor** [comment]
@swift-ci test

**Review by tkremenek — APPROVED** [review]

**Pull request merged**
