### PR TITLE
Always Import FieldDecls from Records

### PR DESCRIPTION
**Pull request by CodaFi**
When we switched this path over to use lazy member loading, a
subsequent commit introduced a check that members were canonical. In
certain extremely twisty scenarios involving multiple modular frameworks
pulling in non-modular headers, this check can fail which results in us
silently dropping these members on the floor.

It's ultimately correct to only pull in the canonical members, but real-world
examples of "system" frameworks evading modularity diagnostics exist so this
is strictly a regression.

Drop the canonicity check for FieldDecls.

rdar://86740970

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
I have been trying for hours to get the stars to align to test for this and I have failed...

**Review by DougGregor — APPROVED** [review]

**Comment by DougGregor** [comment]
@swift-ci please smoke test macOS

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by DougGregor** [comment]
Thank for you finding and fixing this. Silly me, thinking the world is as it should be.

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
