### PR TITLE
[Concurrency] Add `@_inheritActorContext` hidden parameter attribute.

### PR DESCRIPTION
**Pull request by DougGregor**
This new attribute can be used on parameters of `@Sendable async` type
to indicate that the closures arguments passed to such parameters
should inherit the actor context where they are formed, which is not
the normal behavior for `@Sendable` closures.

Another part of rdar://76927008.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Review by ktoso — APPROVED** [review]
This is great 👍 

// funny that `ActorContext` came up as the wording; it's a great word for this (and has prior art too) and I love the use of it, just that we didn't really talk about "actor context" much before. :-)

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test macOS

**Pull request merged**
