### PR TITLE
[stdlib] Switch Int/Float inits + join to be on StringProtocol

### PR DESCRIPTION
**Pull request by airspeedswift**
Per SE-183

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
@swift-ci please test source compatibility

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@swift-ci please test macOS platform

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by moiseev** [comment]
@swift-ci Please test macOS platform

**Comment by moiseev** [comment]
@swift-ci Please clean test macOS

**Comment by moiseev** [comment]
@swift-ci Please Test Source Compatibility

**Pull request merged**
