### PR TITLE
Fix a build error caused my missing #include <string>

### PR DESCRIPTION
**Pull request by atrick**
(on some versions of LLVM apparently)

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci Please smoke test and merge.

**Comment by compnerd** [comment]
See also https://github.com/apple/swift/pull/3540

**Comment by gottesmm** [comment]
@atrick @compnerd Was this handled by that other PR.

**Comment by atrick** [comment]
I merged #3540.
Thanks @gottesmm

**Pull request closed without merging**
