### PR TITLE
Add default implementations for AdditiveArithmetic.{+=, -=}.

### PR DESCRIPTION
**Pull request by rxwei**
This patch defines a default implementation for `+=` and `-=` in `extension AdditiveArithmetic` implemented in terms of `+` and `-`.

### CODE REVIEW

**Comment by stephentyrone** [comment]
@swift-ci please smoke test

**Comment by jrose-apple** [comment]
These need availability (or `@_alwaysEmitIntoClient`, which is probably fair since they're so simple).

**Comment by rxwei** [comment]
@swift-ci please smoke test

**Comment by rxwei** [comment]
> These need availability (or `@_alwaysEmitIntoClient`, which is probably fair since they're so simple).

Added `@_alwaysEmitIntoClient`.

**Comment by rxwei** [comment]
@stephentyrone There isn't a default implementation for `Numeric.*=` either. Should we add one for that?

**Comment by xedin** [comment]
FYI, default implementation could affect type-checker performance because we currently consider both protocol requirement and it's default implementation, so let's at least run smoke perf suite on these changes.

**Comment by xedin** [comment]
@swift-ci please smoke test compiler performance

**Comment by rxwei** [comment]
@stephentyrone is this patch ready?

**Comment by airspeedswift** [comment]
@stephentyrone @xedin I’m good merging this if you are

**Comment by stephentyrone** [comment]
@airspeedswift How do you feel about the use of `@aEIC` here? I don't think it's actually necessary, right?

**Comment by airspeedswift** [comment]
I think it's fine. The implementations are so trivial so inlining would always be optimal, and it'd be infuriating to have to `if #available` them.

**Comment by stephentyrone** [comment]
LGTM, then.

**Review by xedin — APPROVED** [review]

**Pull request merged**
