### PR TITLE
More class layout cleanups and a better fix for SR-4687

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@aschwaighofer You implemented the original fix for https://bugs.swift.org/browse/SR-4687; do you mind taking a look at my changes extending it to classes with any Objective-C ancestry, not just an immediate superclass?

The other cleanups should hopefully be straightforward, they're in support of some class resilience work I'm doing right now.

**Review by aschwaighofer — APPROVED** [review]
Looks good

**Pull request merged**
