### PR TITLE
[Sema] Avoid relying on ParenType in a couple of places

### PR DESCRIPTION
**Pull request by hamishknight**
Split out a couple of Sema changes from #59141, should be NFC.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Review by xedin — APPROVED** [review]

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Pull request merged**
