### PR TITLE
[CMake] add_swift_target_library shouldn't implicitly set INSTALL_IN_TARGET

### PR DESCRIPTION
**Pull request by bulbazord**
This makes it more explicit what the install component of a target
library is if you don't see one (and its marked as IS_SDK_OVERLAY).
Explicit in this case makes more sense, as you don't have to rely on
knowledge of how `add_swift_target_library` is implemented to understand
what component is used to install the target.

cc @compnerd @gottesmm @Rostepher

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by xiaobai** [comment]
@swift-ci please smoke test

**Comment by xiaobai** [comment]
@swift-ci please smoke test

**Comment by xiaobai** [comment]
@swift-ci please smoke test Linux platform

**Comment by Rostepher** [comment]
I appreciate that you're making this explicit. LGTM!

**Pull request merged**
