### PR TITLE
[Concurrency] Use pthread_specific for thread-local storage on Darwin.

### PR DESCRIPTION
**Pull request by mikeash**
The pthread_specific APIs are better than C++ thread_local storage on Darwin since we can use Swift's reserved pthread keys there.

rdar://79504652

### CODE REVIEW

**Comment by mikeash** [comment]
@swift-ci please test

**Review by ktoso — APPROVED** [review]
LGTM, thanks! Nice to use it for the locals as well, and if we run out of keys we can change that piece.

Thanks, Mike!

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test windows platform

**Comment by mikeash** [comment]
The Windows failure is unrelated, merging.

**Pull request merged**
