### PR TITLE
[c++-interop] APINotes test for ObjCMethods

### PR DESCRIPTION
**Pull request by plotfi**
This is swift test to go with https://github.com/apple/llvm-project/pull/4118

The test is verifying that a ObjCMethod that is annotated by an APINote
is in fact getting the APINote applied. These types of APINotes are
heavily used by UIKit for instance in didMoveToParentViewController in
UIViewController.

### CODE REVIEW

**Comment by plotfi** [comment]
@hyp @zoecarver @bulbazord @drodriguez

**Comment by drodriguez** [comment]
apple/llvm-project#4118

@swift-ci please smoke test

**Review by zoecarver — APPROVED** [review]

**Comment by plotfi** [comment]
https://github.com/apple/llvm-project/pull/4118

@swift-ci please smoke test

**Comment by plotfi** [comment]
@swift-ci please smoke test

**Comment by plotfi** [comment]
Going to merge this soon since @zoecarver's https://github.com/apple/llvm-project/pull/4148 would make this test pass.

**Comment by plotfi** [comment]
@swift-ci smoke test macos

**Comment by plotfi** [comment]
@swift-ci smoke test macos

**Comment by plotfi** [comment]
@swift-ci smoke test macos

**Pull request merged**
