### PR TITLE
Fix a bug with inlining self-conformances

### PR DESCRIPTION
**Pull request by rjmccall**

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please smoke test.

**Comment by slavapestov** [comment]
Thanks!

**Comment by slavapestov** [comment]
@rjmccall I think this needs a test case though.

**Comment by rjmccall** [comment]
It's in #20629.  There are no self-conformances that don't satisfy this `isObjCExistentialType()` without that.

**Pull request merged**
