### PR TITLE
[SIL] Relax the verifier on unchecked address casts from raw layout

### PR DESCRIPTION
**Pull request by Azoy**
If we're checking if an immutable address has any mutable or consuming uses, currently we trip the verifier up with some uses of `@_rawLayout` (expectedly so, this is still a hack in some sense). Weird how `unchecked_addr_cast` is actually being checked the verifier here, but `address_to_pointer` is not..? Regardless, relax this check only if we're coming from `@_rawLayout`.

This can occur with the following:
```swift
@_rawLayout(like: T)
struct Cell<T: ~Copyable>: ~Copyable {
  var address: UnsafeMutablePointer<T> {
    .init(Builtin.unprotectedAddressOfBorrow(self))
  }
}

func something(with x: borrowing Cell<Int>, do body: (inout Int) -> ()) {
  body(&x.address.pointee)
}
```

Here we pass `Cell<Int>` as a borrow and get a pointer to itself and pass it to the closure as an `inout`. This violates exclusivity in this simple example, but consider a `Mutex` implementation where we've dynamically enforced exclusivity of the underlying value and can pass an `inout` reference to the data in that case.

Resolves: rdar://125052819

### CODE REVIEW

**Comment by Azoy** [comment]
@swift-ci please smoke test

**Review by eeckstein — APPROVED** [review]
lgtm, but @atrick should also take a look

**Comment by atrick** [comment]
I refrained from commenting earlier because I don't understand how the original Swift code is valid, let alone the .sil. And the fix is safe for non-rawLayout code. But now that I think about it, the fix may hide deeper bugs in rawLayout.

@jckarter, @johnm are we saying values of `@_rawLayout` type are actually always-mutable. How would the compiler be expected to know that this:
`func something(with x: borrowing Cell<Int>,..`
may modify `x`? It needs to know that to avoid optimization.

Approach 1: represent the mutability of rawLayout borrows

It seems require some sort of opaque address-to-pointer transformation at every call site that might mutate the value to prevent optimization.

Furthermore, rawLayout would not be allowed to participate in the generic type system as existentials or archetypes (example below). Is that right? Otherwise, the compiler's basic assumption that this
`func something<T: ~Copyable>(with x: borrowing T,...)`
cannot mutate `x` is wrong.

Approach 2: lie about rawLayout immutabilty

Or, instead, do we expect that the rawLayout value is completely opaque to the compiler at all times?

Doing this safely seems to require:

- Only allow access to the value via some opaque builtin, like Builtin.unprotectedAddressOfBorrow

- Preserve that SIL builtin until IRGen

- Figure out how to lower that builtin to something that LLVM can't optimize through either (since LLVM may also be aware of that some addresses don't allow mutation).

Regarding `address_to_pointer`, that's only *supposed* to happen when the user asks for an unsafe pointer, so the SIL verifier has no business policing that. But those sometimes get optimized to `unchecked_addr_cast`. See `visitPointerToAddressInst`. We could suppress that optimization for `_rawLayout` as an alternative to disabling the verifier here.

If we implemented Approach 2 though, then we would not need to selectively disable optimization that might rely on immutability, which doesn't seem maintainable, or even possible if we have rawLayout generics.

###
@jckarter should this code be allowed?
```
// -emit-sil -enable-experimental-feature NoncopyableGenerics -enable-experimental-feature RawLayout -enable-experimental-feature BuiltinModule

import Builtin

protocol RawLayout: ~Copyable {
  associatedtype T: ~Copyable
  var address: UnsafeMutablePointer<T> { borrowing get }
}

@_rawLayout(like: T)
struct Cell<T: ~Copyable>: ~Copyable, RawLayout {
  var address: UnsafeMutablePointer<T> {
    .init(Builtin.unprotectedAddressOfBorrow(self))
  }
}

func something_generic<R: RawLayout & ~Copyable>(with x: borrowing R, do body: (inout R.T) -> ()) {
  body(&x.address.pointee)
}

func test() {
  let cell = Cell<Int>()
  something_generic(with: cell) { _ = $0 }
}
```

**Comment by johnm** [comment]
@atrick I think you mean to tag a different John. Cheers!

**Comment by atrick** [comment]
> @atrick I think you mean to tag a different John. Cheers!

yep, copy-paste and forgot to edit

**Comment by jckarter** [comment]
> @jckarter, @rjmccall are we saying values of @_rawLayout type are actually always-mutable. How would the compiler be expected to know that this:
> func something(with x: borrowing Cell<Int>,..
> may modify x? It needs to know that to avoid optimization.

I think, from SIL's perspective, we want the `@_rawLayout` storage to always appear completely opaque, so it doesn't matter to SIL whether it's physically mutated or not. We could think of the raw storage as being like an out-of-line allocation that gets allocated when the value is initialized or moved-into and deallocated when the value is destroyed or moved-out-of, and it being stored inline is "just an optimization" arising from the fact that the buffer is uniquely owned by the value.

To that end, I was thinking it might make sense to use an instruction specific to projecting out the raw storage, we could call it `address_to_raw_storage_pointer`, so that normal `address_to_pointer` analyses don't apply. We could treat this instruction as notionally loading the pointer to the raw storage buffer.

**Comment by rjmccall** [comment]
Should we have this conversation on the forums instead of this PR?

**Pull request closed without merging**
