### PR TITLE
Sema: Don't warn on @_exported public imports that are not used in API

### PR DESCRIPTION
**Pull request by xymus**
An `@_export public import` is meaningful on its own as it declares a relationship between two modules and how clients see them. As such that import doesn't have to be referenced from API to be appropriate. Let's not report public import with an `@_export` attribute as being superfluous.

Also test the behavior of the same diagnostics with `@_spiOnly` imports without related logic changes.

rdar://122032960

### CODE REVIEW

**Review by tshortli — APPROVED** [review]
Makes sense!

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by xymus** [comment]
@swift-ci Please smoke test Windows

**Pull request merged**
