### PR TITLE
[Executors][Distributed] assumeOnLocalDistributedActorExecutor

### PR DESCRIPTION
**Pull request by ktoso**
Adds the assumeOnLocalDistributedActorExecutor from SE-0392

Depends on #64171
Depends on #64237

### CODE REVIEW

**Comment by ktoso** [comment]
This is unblocked now, just needs a rebase

**Comment by ktoso** [comment]
@swift-ci please smoke test and merge

**Comment by ktoso** [comment]
@swift-ci please smoke test and merge

**Comment by bnbarham** [comment]
@shahmishal apparently `smoke test and merge` doesn't check windows results? `Distributed/Runtime/distributed_actor_assume_executor.swift` failed.

**Comment by ktoso** [comment]
I thought we started to require windows passing 😕 seems not heh, thanks for the fix in https://github.com/apple/swift/pull/64439

**Pull request merged**
