### PR TITLE
IRGen: Don't outline enum value functions when they involve open existential types

### PR DESCRIPTION
**Pull request by aschwaighofer**
We don't support doing so.

rdar://41009775

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test and merge

**Comment by aschwaighofer** [comment]
@swift-ci Please test and merge

**Comment by aschwaighofer** [comment]
@swift-ci Please test and merge

**Comment by aschwaighofer** [comment]
@shajrawi Can you review this?

**Review by shajrawi — COMMENTED** [review]
LGTM!

**Pull request merged**
