### PR TITLE
[stdlib] Adopt _pointerBitWidth conditional

### PR DESCRIPTION
**Pull request by lorentey**
Replace `arch(foo) || arch(bar) || arch(fred)` incantations with the new `_pointerBitWidth` conditional.

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Review by stephentyrone — APPROVED** [review]

**Comment by stephentyrone** [comment]
Thanks for working on this one!

**Comment by lorentey** [comment]
Oops, typo:

```
diff --git a/stdlib/public/core/StringObject.swift b/stdlib/public/core/StringObject.swift
index f3a440139b3..cd47c3b5313 100644
--- a/stdlib/public/core/StringObject.swift
+++ b/stdlib/public/core/StringObject.swift
@@ -101,7 +101,7 @@ internal struct _StringObject {
     self._object = Builtin.valueToBridgeObject(UInt64(0)._value)
   }
 
-#elseif _pointerBitWidth(_64)
+#elseif _pointerBitWidth(_32)
 
   @usableFromInline @frozen
   internal enum Variant {
```

I'll amend the existing commit.

**Comment by lorentey** [comment]
@swift-ci test

**Review by glessard — APPROVED** [review]

**Comment by lorentey** [comment]
The last commit normalized the ordering of the conditional clauses to 64 bit → 32 bit → error, even outside of StringObject. Putting the (far) more common case first is a nice didactic tool for avoiding confusion. (Thanks @glessard)

**Comment by lorentey** [comment]
@swift-ci test

**Review by glessard — APPROVED** [review]

**Pull request merged**
