### PR TITLE
[RequirementMachine] InferredGenericSignatureRequest uses valid location for generic signature requirements.

### PR DESCRIPTION
**Pull request by nate-chandler**
`InferredGenericSignatureRequest` creates `StructuralRequirement`s for the requirements of the generic signature that is passed to it (if one is).

Previously, it used invalid `SourceLoc`s for these requirements.  The result was that when errors that were emitted as a result of those `StructuralRequirement`s (during concrete type contraction), they would also have invalid `SourceLoc`s.  The effect was that those errors were ignored during `diagnoseRequirementErrors`.

Here, use the available loc for those requirements.

rdar://108963047

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Review by slavapestov — APPROVED** [review]

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Pull request merged**
