### PR TITLE
build: fix spelling of clang

### PR DESCRIPTION
**Pull request by edymtt**
Addresses rdar://problem/56866783

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test Windows

**Review by compnerd — APPROVED** [review]
Sure, though this doesnt really have any functional change.  The `Clang` spelling is correct, and should match both `AppleClang` and `Clang` as identified by CMake.  Furthermore, the check is case insensitive, so this should remain the same?  If I'm wrong about the case, we should notice it pretty quickly with failures on Azure.

**Comment by edymtt** [comment]
According to our tests, MATCHES seems case sensitive (and I cannot see any way to make that case sensitive).

Also, `CMAKE_C_COMPILER` seems to point to a path (in which case I would expect `clang` to be lower case) -- wondering if we should test `CMAKE_C_COMPILER_ID` instead

**Comment by compnerd** [comment]
UGH, you are correct, the variable being checked is incorrect - that was supposed to be `CMAKE_C_COMPILER_ID`, not `CMAKE_C_COMPILER`.

**Comment by compnerd** [comment]
I put up #28058 that corrects the variable.  Sorry about that!

**Comment by edymtt** [comment]
Thanks!

Closing this in favor of https://github.com/apple/swift/pull/28058

**Pull request closed without merging**
