### PR TITLE
[SyntaxParse] Fix the end location for CompositionTypeRepr

### PR DESCRIPTION
**Pull request by rintaro**
The end loc should be the loc of the last token of the last type element.

CC: @davidungar

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test Linux

**Review by nkcsgexi — APPROVED** [review]
LGTM!

**Pull request merged**
