### PR TITLE
[CodeCompletion] Improve context type analysis for overloaded method

### PR DESCRIPTION
**Pull request by rintaro**
For:

```swift
    class MyClass {
        func foo(x: SomeType)
        func foo(x: OtherType)
    }

    func test(obj: MyClass) {
        obj.foo(x: #^COMPLETE^#
    }
```
Type checker doesn't keep overloaded choices for `obj.foo` in the AST after typechecking. Code completion need to lookup members to collect possible parameter types.

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by benlangmuir** [comment]
We should share the lookup code here with the subscript case from #20066 if we can.  I suggest changing this PR to pull that into a function and then use that from #20066.  Otherwise LGTM.

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Pull request merged**
