### PR TITLE
[cxx-interop] Enable C++ stdlib overlay on Linux

### PR DESCRIPTION
**Pull request by egorzhdan**

### CODE REVIEW

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test Linux

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Review by zoecarver — APPROVED** [review]
LGTM. As always, thank you for the excellent work, Egor!

**Pull request merged**
