### PR TITLE
Update compiler version to 4.0

### PR DESCRIPTION
**Pull request by aciidgh**
@jrose-apple can you take a look?

### CODE REVIEW

**Comment by rintaro** [comment]
We need test case to validate `#if swift(>=3.1)` still works with `-swift-version 3` .

**Comment by aciidb0mb3r** [comment]
Hm that does seem to work fine, maybe it was fixed? But this does look like this is more involved than I thought. I'll close this PR and file a bug instead. Ran into this issue during compilation:

```
[46/85] Generating /home/ankit_aggarwal/swift.org/build/Ninja-ReleaseAssert/swift-linux-x86_64/./lib/swift/linux/x86_64/Swift.swiftmodule
FAILED: cd /home/ankit_aggarwal/swift.org/build/Ninja-ReleaseAssert/swift-linux-x86_64/stdlib/public/core && /home/ankit_aggarwal/swift.org/swi
ft/utils/line-directive @/home/ankit_aggarwal/swift.org/build/Ninja-ReleaseAssert/swift-linux-x86_64/stdlib/public/core/VHWme.txt -- /home/anki
t_aggarwal/swift.org/build/Ninja-ReleaseAssert/swift-linux-x86_64/./bin/swiftc -emit-module -o /home/ankit_aggarwal/swift.org/build/Ninja-Relea
seAssert/swift-linux-x86_64/./lib/swift/linux/x86_64/Swift.swiftmodule -sdk / -target x86_64-unknown-linux-gnu -resource-dir /home/ankit_aggarw
al/swift.org/build/Ninja-ReleaseAssert/swift-linux-x86_64/./lib/swift -O -D INTERNAL_CHECKS_ENABLED -I /home/ankit_aggarwal/swift.org/build/Nin
ja-ReleaseAssert/swift-linux-x86_64/./lib/swift/linux/x86_64 -module-cache-path /home/ankit_aggarwal/swift.org/build/Ninja-ReleaseAssert/swift-
linux-x86_64/./module-cache -no-link-objc-runtime -nostdimport -parse-stdlib -module-name Swift -Xfrontend -group-info-path -Xfrontend /home/an
kit_aggarwal/swift.org/swift/stdlib/public/core/GroupInfo.json -Xfrontend -sil-serialize-all -module-link-name swiftCore -force-single-frontend
-invocation -Xcc -D__SWIFT_CURRENT_DYLIB=swiftCore -parse-as-library @/home/ankit_aggarwal/swift.org/build/Ninja-ReleaseAssert/swift-linux-x86_
64/stdlib/public/core/VHWme.txt
/home/ankit_aggarwal/swift.org/swift/stdlib/public/core/IntegerArithmetic.swift.gyb:152:13: error: generic parameter 'Args' could not be inferr
ed
  return x~>_abs()
            ^
/home/ankit_aggarwal/swift.org/swift/stdlib/public/core/IntegerArithmetic.swift.gyb:123:15: note: in call to function '_abs'
internal func _abs<Args>(_ args: Args) -> (_Abs, Args) {
              ^
/home/ankit_aggarwal/swift.org/swift/stdlib/public/core/ManagedBuffer.swift:91:16: error: generic parameter 'R' could not be inferred
    return try withUnsafeMutablePointers { return try body($0.1) }
               ^
/home/ankit_aggarwal/swift.org/swift/stdlib/public/core/ManagedBuffer.swift:265:16: error: generic parameter 'R' could not be inferred
    return try withUnsafeMutablePointers { return try body($0.1) }
               ^
/home/ankit_aggarwal/swift.org/swift/stdlib/public/core/ManagedBuffer.swift:265:55: error: closure use of non-escaping parameter 'body' may all
ow it to escape
    return try withUnsafeMutablePointers { return try body($0.1) }
```

**Comment by aciidb0mb3r** [comment]
https://bugs.swift.org/browse/SR-3790

**Comment by rintaro** [comment]
https://bugs.swift.org/browse/SR-3791

**Comment by jrose-apple** [comment]
We should discuss on swift-dev what it means to bump the version to 4.0. It's not just changing the defaults in CMake.

**Pull request closed without merging**
