### PR TITLE
Introduce SWIFT_FREESTANDING_FLAVOR to select whether the FREESTANDING stdlib should be built/tested using an Apple SDK, or another SDK (e.g. Linux, not implemented yet)

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Review by compnerd — APPROVED** [review]

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test macOS platform with toolchain

**Comment by kubamracek** [comment]
@swift-ci please test stdlib with toolchain

**Comment by kubamracek** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by kubamracek** [comment]
@swift-ci please test

**Pull request merged**
