### PR TITLE
[cxx-interop] Add class template tests

### PR DESCRIPTION
**Pull request by hlopko**
In this PR we add tests testing more complicated template scenarios for https://github.com/apple/swift/pull/32950. Specifically:

* class template with variadic parameter
* class template with non-type parameter
* class template with template template parameter

This PR depends on https://github.com/apple/swift/pull/32950.

### CODE REVIEW

**Comment by hlopko** [comment]
(you can use https://github.com/hlopko/swift/compare/typedefs...hlopko:add_template_tests to see the diffbase on typedefs PR)

**Comment by hlopko** [comment]
@swift-ci please test

**Comment by hlopko** [comment]
@swift-ci please test

**Comment by gribozavr** [comment]
Could you rebase? I can open the diff view that you linked, but I can't leave comments there.

**Comment by scentini** [comment]
@gribozavr rebased, PTAL

**Comment by hlopko** [comment]
@swift-ci please test

**Comment by hlopko** [comment]
@swift-ci please test Windows platform

**Comment by hlopko** [comment]
@swift-ci please test

**Comment by hlopko** [comment]
@swift-ci please test

**Comment by hlopko** [comment]
@swift-ci please test Windows platform

**Comment by hlopko** [comment]
@swift-ci please test

**Comment by hlopko** [comment]
@swift-ci please test

**Comment by hlopko** [comment]
@swift-ci please test windows platform

**Comment by hlopko** [comment]
Skipping class-template-variadic test on Windows, the culprit is https://bugs.swift.org/browse/SR-13129.

**Comment by hlopko** [comment]
@swift-ci please test

**Comment by hlopko** [comment]
@swift-ci please test

**Comment by hlopko** [comment]
@swift-ci please test

**Comment by hlopko** [comment]
@swift-ci please test

**Comment by hlopko** [comment]
@swift-ci please test windows platform

**Review by gribozavr — APPROVED** [review]

**Comment by tbkka** [comment]
The `class-template-variadic.swift` test is failing on both Linux and macOS CI.

**Comment by hlopko** [comment]
Sad, I'll prepare a revert.

**Pull request merged**
