### PR TITLE
[Build System: CMake] Update the default install_name_dir to /usr/lib/swift for the standard library and overlays.

### PR DESCRIPTION
**Pull request by Rostepher**
rdar://46736483

### CODE REVIEW

**Comment by Rostepher** [comment]
@swift-ci please smoke test

**Review by compnerd — COMMENTED** [review]
Is there some private changes that require this to be a parameter?  I really want to move towards using CMake rather than the custom variant that we keep building and tearing down.  Can we not just use the global variable in the core add_library_single rather than passing it down all the way?

**Comment by Rostepher** [comment]
@swift-ci please smoke test Linux platform

**Comment by Rostepher** [comment]
@compnerd I'm not sure what global variable you are referencing. We intend to change this `install_name_dir` for the standard library and overlays, but not for the private libraries that aren't installed. If there's a cleaner way to do this then I'm more than happy to do so.

**Comment by compnerd** [comment]
@Rostepher `SWIFT_DARWIN_STDLIB_INSTALL_NAME_DIR` is a global variable, you can just reference it in the innermost function rather than pass it along from the top level

**Comment by Rostepher** [comment]
@compnerd I realize that and we are using that variable for all the public stdlib content. The private content that isn't actually installed now uses `SWIFT_DARWIN_STDLIB_PRIVATE_INSTALL_NAME_DIR` which I manually pass along via this variable.

**Comment by compnerd** [comment]
Oh, I get it now.  You are using that to override the value.  I wonder if we can infer the private-ness/public-ness and avoid passing this down.  But, if there isn't a way to do that, I imagine that you need this right now, so we can deal with rewriting this later.

**Comment by Rostepher** [comment]
I thought about trying to infer the value, but it seemed messier to me to have even more magic inside `add_swift_target_library`. Instead I opted to have a more general purpose argument that would allow us to control this.

**Comment by compnerd** [comment]
I think that we should reconsider that.  We need to move away from the custom argument thing so that we can adopt regular CMake best practices.  The current mechanism really breaks cross-compilation and we need to strip out the changes to make that work properly.

**Review by letterlover — APPROVED** [review]

**Pull request merged**
