### PR TITLE
[stdlib] Disable test that's sometimes failing on Linux

### PR DESCRIPTION
**Pull request by lancep**
Disable the COW.Fast.RemoveAllDoesNotReallocate test because it's sometimes failing on Linux.
<rdar://problem/34268868>

### CODE REVIEW

**Comment by lancep** [comment]
@swift-ci please smoke test

**Comment by graydon** [comment]
Could you hold off merging this please? 
https://github.com/apple/swift/pull/11741 is a plausible real-fix of the issue
(see also rdar://34209577)

**Comment by lancep** [comment]
Will do!

**Comment by moiseev** [comment]
@lancep FYI: you can use:
```swift
tests.test("my test")
  .skip { .linuxAny("EXPLANATION_HERE") }
  .code {
  // test body here
}
```

See example: [link](https://github.com/apple/swift/blob/92b13b809e6c6fd6068d5db2351111a6e0acbed8/validation-test/stdlib/String.swift#L333)

**Comment by graydon** [comment]
Thanks :)

**Comment by graydon** [comment]
@lancep I wish I had good news for you here but sadly it seems Joe's fix did not fix this change. Would you like to post a version that does .skip the way @moiseev suggested? Then I guess we ought to land this (though: alarming bug! removeAll(keepingCapacity: true) appears to change capacity sometimes!)

**Comment by lancep** [comment]
@swift-ci please smoke test and merge

**Comment by lancep** [comment]
At least the capacity gets bigger!

**Comment by lancep** [comment]
@swift-ci please smoke test

**Pull request merged**
