### PR TITLE
[CoroutineAccessors] SIL represents callee alloc.

### PR DESCRIPTION
**Pull request by nate-chandler**
When its operand has coroutine kind `yield_once_2`, a `begin_apply` instruction produces an additional value representing the storage allocated by the callee.  This storage must be deallocated by a `dealloc_stack` on every path out of the function.  Like any other stack allocation, it must obey stack discipline.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Comment by nate-chandler** [comment]
@swift-ci please smoke test

**Comment by rjmccall** [comment]
Can we settle on whether this is really what we want to do before adding SIL support for it?

**Comment by nate-chandler** [comment]
As we chatted about, we do want to separate deallocation from coroutine resumption (except in the case of the malloc/free allocator in which case stack discipline needn't be maintained so we can deallocate in the second funclet) as is represented in the SIL here.

**Pull request merged**
