### PR TITLE
[func-sig-opts] Add a new mangling for the guaranteed->owned transfor…

### PR DESCRIPTION
**Pull request by gottesmm**
…mation.

I followed the example of the owned->guaranteed transformation.

rdar://38196046

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by slavapestov** [comment]
@rajbarik You might want to check out the code being edited by @gottesmm here -- it will give you ideas for how to implement the mangling for your existential specialization pass.

**Review by eeckstein — APPROVED** [review]
lgtm

**Comment by rajbarik** [comment]
Thanks. I think I did this already in the PR
https://github.com/apple/swift/pull/13991

Do we care about these files?

   - lib/Demangling/OldDemangler.cpp
   <https://github.com/apple/swift/pull/16196/files#diff-4>
   - lib/Demangling/OldRemangler.cpp
   <https://github.com/apple/swift/pull/16196/files#diff-5>

**Comment by eeckstein** [comment]
@rajbarik In general yes. The old remangler is used to create runtime type names.
But for your change, no. A specialized function cannot be the context of a type.

**Pull request merged**
