### PR TITLE
[Runtime] Remove FIXMEs and hacks for tail calls.

### PR DESCRIPTION
**Pull request by varungandhi-apple**
Reverts hack from 9b4f7d62cd2d09e9f24866d0d1f51de4b493ddc2.

Fixes rdar://78058239

### CODE REVIEW

**Review by aschwaighofer — APPROVED** [review]
LGTM. Should we add comments to the lines that require a return explaining that they are not just cosmetic but change code emission?

**Comment by varungandhi-apple** [comment]
Added comments where explicit `return` is used to force a tail call.

**Comment by varungandhi-apple** [comment]
@swift-ci test

**Comment by aschwaighofer** [comment]
Thank you

**Pull request merged**
