### PR TITLE
[Build System: build-script] Adopt the six compatibility library in the build_swift module.

### PR DESCRIPTION
**Pull request by Rostepher**
Based on the changes in #29243

### CODE REVIEW

**Comment by Rostepher** [comment]
@swift-ci please smoke test

**Comment by Rostepher** [comment]
Looks like `six` is not installed on the Linux nodes. It comes default with macOS, so maybe we should also consider adding it to the Linux images we use?

**Comment by Rostepher** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@Rostepher - yeah, I think @shahmishal would be able to help with that.

**Comment by shahmishal** [comment]
Yes, I will look into this tomorrow.

**Comment by Rostepher** [comment]
@swift-ci please smoke test

**Comment by Rostepher** [comment]
@swift-ci please smoke test

**Comment by Rostepher** [comment]
@swift-ci please smoke test

**Comment by Rostepher** [comment]
@swift-ci please smoke test

**Comment by Rostepher** [comment]
@swift-ci please smoke test

**Comment by Rostepher** [comment]
Fun fact, I think the version of `six` that comes pre-installed on macOS (or at least the one on the macOS build nodes) is at least 5 years old as it doesn't include `six.moves.shlex_quote`.

**Comment by Rostepher** [comment]
@swift-ci please smoke test

**Comment by Rostepher** [comment]
@swift-ci please smoke test

**Comment by Rostepher** [comment]
And thus the age of Python 2 fades into the twilight, Python 3 looms over the horizon.

**Comment by drodriguez** [comment]
@shahmishal: maybe on Tuesday someone should send an email about this new requirement for the community CI nodes maintainers. The Android ones didn't have this dependency installed.

@Rostepher: maybe you should create an additional PR to change the READMEs (https://github.com/apple/swift/blob/master/README.md in the Linux section, and maybe https://github.com/apple/swift/blob/master/docs/Ubuntu14.md if it is still necessary). And maybe create a `requirements.txt` as a reference.

**Pull request merged**
