### PR TITLE
Fix crash during type checking when adding members to an extension.

### PR DESCRIPTION
**Pull request by rudkx**
#### What's in this pull request?

Cherry-picking a fix from master to the swift-3.0-branch.
#### Resolved bug number: ([rdar://problem/27671033](rdar://problem/27671033))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

A smoke test on macOS does the following:
1. Builds the compiler incrementally.
2. Builds the standard library only for macOS. Simulator standard libraries and
   device standard libraries are not built.
3. lldb is not built.
4. The test and validation-test targets are run only for macOS. The optimized
   version of these tests are not run.

A smoke test on Linux does the following:
1. Builds the compiler incrementally.
2. Builds the standard library incrementally.
3. lldb is built incrementally.
4. The swift test and validation-test targets are run. The optimized version of these
   tests are not run.
5. lldb is tested.

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

If the extension ended up with ErrorType, we could crash while we
continue trying to process its body adding members.

Just bail out in this case.

rdar://problem/27671033

(code cherry picked from commit c9ec7e398b4a2fc5f44b9d40fad4c29fd756b29d)
(test cherry picked from commit 107d602940665903280271905ef9f9c7abf6a9e2)

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Test.

**Comment by rudkx** [comment]
@DougGregor Can you review for the swift-3.0-branch?

**Comment by DougGregor** [comment]
LGTM!

**Comment by DougGregor** [comment]
@shahmishal the Linux failure is a problem on the builder:

14:27:37 Building remotely on Ubuntu-14.04-2 (Ubuntu-14.04) in workspace /home/buildnode/jenkins/workspace/swift-PR-Linux@2
14:27:37  > git rev-parse --is-inside-work-tree # timeout=10
14:27:37 Fetching changes from the remote Git repository
14:27:37  > git config remote.origin.url git@github.com:apple/swift.git # timeout=10
14:27:37 ERROR: Error fetching remote repo 'origin'
14:27:37 hudson.plugins.git.GitException: Failed to fetch from git@github.com:apple/swift.git
14:27:37 	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:763)
14:27:37 	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1012)
14:27:37 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1043)
14:27:37 	at org.jenkinsci.plugins.multiplescms.MultiSCM.checkout(MultiSCM.java:129)
14:27:37 	at hudson.scm.SCM.checkout(SCM.java:485)
14:27:37 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1276)
14:27:37 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:607)
14:27:37 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
14:27:37 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
14:27:37 	at hudson.model.Run.execute(Run.java:1738)
14:27:37 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
14:27:37 	at hudson.model.ResourceController.execute(ResourceController.java:98)
14:27:37 	at hudson.model.Executor.run(Executor.java:410)
14:27:37 Caused by: hudson.plugins.git.GitException: Command "git config remote.origin.url git@github.com:apple/swift.git" returned status code 4:
14:27:37 stdout: 
14:27:37 
stderr: error: failed to write new configuration file .git/config.lock
14:27:37

**Comment by DougGregor** [comment]
@swift-ci please test Linux

**Pull request merged**
