### PR TITLE
Fix typos 🎁 

### PR DESCRIPTION
**Pull request by practicalswift**

### CODE REVIEW

**Comment by practicalswift** [comment]
Merged with #773 as per @rjmccall:s request. Squashed and pushed.

**Comment by gribozavr** [comment]
@practicalswift Seems to conflict with something new in master, could you rebase please?

**Comment by practicalswift** [comment]
@gribozavr Done! :-) Rebased and pushed.

**Comment by lattner** [comment]
Looks great, thanks for keeping Metadata.cpp to 80 cols.

**Pull request merged**
