### PR TITLE
[docs] Fix cut off sentence and correct Throwing discarding task group docs

### PR DESCRIPTION
**Pull request by ktoso**
We cut off a sentence, this corrects that issue.

resolves rdar://115519046

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Review by FranzBusch — APPROVED** [review]

**Review by amartini51 — APPROVED** [review]
I pushed some minor wording fixes — looks good, thanks!

**Comment by amartini51** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
Thanks Alex!

**Pull request merged**
