### PR TITLE
[SILOpt] Enabled SSADestroyHoisting.

### PR DESCRIPTION
**Pull request by nate-chandler**
The new destroy_addr hoisting respects lexical lifetimes.  It will replace all other destory hoisting.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test linux platform

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by shinancao** [comment]
亲，你的信件我已收到，我会在最快的时间内来处理，谢谢合作！

**Review by atrick — APPROVED** [review]
Awesome! Thanks for the fixes.

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please test macOS platform

**Comment by nate-chandler** [comment]
@swift-ci please test compiler performance

**Pull request merged**
