### PR TITLE
[stdlib] Implement updates to SE-0104

### PR DESCRIPTION
**Pull request by moiseev**
- Delete `ArithmeticOverflow` type
- Make `BinaryInteger.init` generic over `BinaryFloatingPoint` instead of `FloatingPoint`
- Rename `init(extendingOrTruncating:)` to `init(truncatingIfNeeded:)`

Shift operation changes  can be found [here](https://github.com/apple/swift/pull/11044).

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please test macOS platform

**Comment by moiseev** [comment]
@swift-ci Please smoke benchmark

**Comment by moiseev** [comment]
@swift-ci Please Test Source Compatibility

**Comment by moiseev** [comment]
https://github.com/apple/swift-corelibs-foundation/pull/1136
https://github.com/apple/swift-package-manager/pull/1289
@swift-ci Please test Linux platform

**Comment by moiseev** [comment]
@swift-ci Please test macOS platform

**Comment by moiseev** [comment]
@swift-ci Please Test Source Compatibility

**Comment by moiseev** [comment]
apple/swift-package-manager#1289
@swift-ci Please test macOS

**Comment by moiseev** [comment]
@swift-ci Please Test Source Compatibility

**Comment by moiseev** [comment]
@swift-ci Please Test Source Compatibility

**Comment by natecook1000** [comment]
apple/swift-package-manager#1289
@swift-ci Please Test Source Compatibility

**Comment by natecook1000** [comment]
apple/swift-corelibs-foundation#1136
apple/swift-package-manager#1289
@swift-ci Please test Linux platform

**Comment by natecook1000** [comment]
apple/swift-package-manager#1289
@swift-ci Please test macOS platform

**Comment by shahmishal** [comment]
apple/swift-corelibs-foundation#1136
apple/swift-package-manager#1289
@swift-ci Please test

**Comment by moiseev** [comment]
@swift-ci Please Test Source Compatibility

**Pull request merged**
