### PR TITLE
SILGen/Sema: Add `@_backDeploy` support for constructors

### PR DESCRIPTION
**Pull request by tshortli**
Also, fix some mistakes in existing diagnostics meant to reject `@_backDeploy` on methods that may be invoked with dynamic dispatch.

Resolves rdar://94436652

### CODE REVIEW

**Comment by tshortli** [comment]
@swift-ci please test

**Review by nkcsgexi — APPROVED** [review]
LGTM!

**Comment by tshortli** [comment]
@swift-ci please smoke test

**Review by artemcm — COMMENTED** [review]
Late drive-by: this looks great.

**Pull request merged**
