### PR TITLE
[GSB] Easy performance improvements for `GenericSignatureBuilder`

### PR DESCRIPTION
**Pull request by DougGregor**
A small collection of easy performance wins for the `GenericSignatureBuilder`, focused on a tiny example

    let _ = [1, 2]

where type-checking performance regressed significantly recently due largely to the `GenericSignatureBuilder` as used in deserializing generic environments from the standard library. Specific improvements:

* Caching of archetype anchors (15% speedup type-checking standard library, 9% on the example)
* Don't finalize a canonical `GenericSignatureBuilder` because it doesn't need to do that work (3x speedup on the example).

Part of rdar://problem/32116933

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by slavapestov** [comment]
LGTM!

**Review by slavapestov — APPROVED** [review]

**Comment by DougGregor** [comment]
Turns out a broke a bunch of stuff on ill-formed code that I need to investigate, but the performance win is significant.

**Comment by DougGregor** [comment]
Looks like ~3.7x speedup in type checking time (all in deserialization) on that example with a +Asserts compiler.

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
