### PR TITLE
[3.0] Dependency fixes for overlays

### PR DESCRIPTION
**Pull request by jckarter**
Try to fix build races.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test OS X

**Comment by jckarter** [comment]
@atrick Do these look good for 3.0, assuming it builds cleanly?

**Review by atrick — APPROVED** [review]
LGTM for Swift 3!

**Comment by atrick** [comment]
@tkremenek please merge.

**Comment by jrose-apple** [comment]
Or @ematejska, perhaps? This should clear up build issues we're seeing on the branch without having any affect on functionality.

**Pull request merged**
