### PR TITLE
[5.1] [Doc] [SR-10094]  Add missing documentation for SE-0237

### PR DESCRIPTION
**Pull request by fassko**
https://bugs.swift.org/browse/SR-10094

This is cherry pick #25301

### CODE REVIEW

**Comment by fassko** [comment]
@lorentey Please review this.

**Comment by lorentey** [comment]
@swift-ci test

**Comment by jrose-apple** [comment]
> `no such module '_SwiftClockKitOverlayShims'`

Some of the Apple folks are working on this non-deterministic issue…but for now…

@swift-ci Please test macOS

**Comment by brentdax** [comment]
@swift-ci Please test macOS

**Pull request merged**
