### PR TITLE
Start implementing C++ operator interop

### PR DESCRIPTION
**Pull request by MForster**
This imports the four basic arithmetic operators `+`, `-`, `*`, `/`
declared as inline non-member functions.

More to come.

This is part of addressing SR-12748.

### CODE REVIEW

**Comment by MForster** [comment]
@swift-ci Please test.

**Comment by gribozavr** [comment]
LGTM, but I'm deferring approval until the Windows build is fixed.

**Comment by MForster** [comment]
@swift-ci Please test.

**Comment by MForster** [comment]
@swift-ci Please test Windows.

**Comment by MForster** [comment]
@swift-ci Please test Windows

**Review by gribozavr — APPROVED** [review]

**Comment by MForster** [comment]
@swift-ci Please test Linux

**Comment by MForster** [comment]
@swift-ci Please test Linux platform

**Comment by MForster** [comment]
@swift-ci Please test Linux platform

**Comment by MForster** [comment]
@swift-ci Please smoke test Linux platform

**Comment by MForster** [comment]
@swift-ci Please test Linux platform

**Pull request merged**
