### PR TITLE
[SE-0258] Diagnostic cleanups for property wrappers

### PR DESCRIPTION
**Pull request by DougGregor**
* Clarify diagnostic banning the declaration of names using `$`
* Drop the lowercasing restriction on property wrapper names

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by shahmishal** [comment]
@swift-ci Python lint

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
