### PR TITLE
[AutoDiff] Type-check `@differentiable` attributes during validation.

### PR DESCRIPTION
**Pull request by dan-zheng**
Type-check `@differentiable` attributes during `TypeChecker::validateDecl` for
all relevant declaration kinds (initializers, subscripts, variables), not just
function declarations.

Resolves [TF-888](https://bugs.swift.org/browse/TF-888).
[TF-789](https://bugs.swift.org/browse/TF-789) tracks proper request-based type-checking for `@differentiable` attribute.

### CODE REVIEW

**Review by rxwei — APPROVED** [review]

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
The newly added test fails on Linux:
```
Failing Tests (1):
    Swift(linux-x86_64) :: AutoDiff/differentiable_attr_cross_module/main.swift
```

```
/tmp/lit_tmp_Ch1io5/differentiable_attr_other_module-a40872.o:differentiable_attr_other_module-a40872.o:function $sSf3cosyS2fFZ: error: undefined reference to 'cosf'
/tmp/lit_tmp_Ch1io5/differentiable_attr_other_module-a40872.o:differentiable_attr_other_module-a40872.o:function $sSf3sinyS2fFZ: error: undefined reference to 'sinf'
/tmp/lit_tmp_Ch1io5/differentiable_attr_other_module-a40872.o:differentiable_attr_other_module-a40872.o:function $sSf3tanyS2fFZ: error: undefined reference to 'tanf'
/tmp/lit_tmp_Ch1io5/differentiable_attr_other_module-a40872.o:differentiable_attr_other_module-a40872.o:function $sSf4acosyS2fFZ: error: undefined reference to 'acosf'
/tmp/lit_tmp_Ch1io5/differentiable_attr_other_module-a40872.o:differentiable_attr_other_module-a40872.o:function $sSf4asinyS2fFZ: error: undefined reference to 'asinf'
/tmp/lit_tmp_Ch1io5/differentiable_attr_other_module-a40872.o:differentiable_attr_other_module-a40872.o:function $sSf4atanyS2fFZ: error: undefined reference to 'atanf'
/tmp/lit_tmp_Ch1io5/differentiable_attr_other_module-a40872.o:differentiable_attr_other_module-a40872.o:function $sSf4coshyS2fFZ: error: undefined reference to 'coshf'
/tmp/lit_tmp_Ch1io5/differentiable_attr_other_module-a40872.o:differentiable_attr_other_module-a40872.o:function $sSf4sinhyS2fFZ: error: undefined reference to 'sinhf'
/tmp/lit_tmp_Ch1io5/differentiable_attr_other_module-a40872.o:differentiable_attr_other_module-a40872.o:function $sSf4tanhyS2fFZ: error: undefined reference to 'tanhf'
/tmp/lit_tmp_Ch1io5/differentiable_attr_other_module-a40872.o:differentiable_attr_other_module-a40872.o:function $sSf5acoshyS2fFZ: error: undefined reference to 'acoshf'
/tmp/lit_tmp_Ch1io5/differentiable_attr_other_module-a40872.o:differentiable_attr_other_module-a40872.o:function $sSf5asinhyS2fFZ: error: undefined reference to 'asinhf'
/tmp/lit_tmp_Ch1io5/differentiable_attr_other_module-a40872.o:differentiable_attr_other_module-a40872.o:function $sSf5atanhyS2fFZ: error: undefined reference to 'atanhf'
/tmp/lit_tmp_Ch1io5/differentiable_attr_other_module-a40872.o:differentiable_attr_other_module-a40872.o:function $sSf3expyS2fFZ: error: undefined reference to 'expf'
/tmp/lit_tmp_Ch1io5/differentiable_attr_other_module-a40872.o:differentiable_attr_other_module-a40872.o:function $sSf4exp2yS2fFZ: error: undefined reference to 'exp2f'
/tmp/lit_tmp_Ch1io5/differentiable_attr_other_module-a40872.o:differentiable_attr_other_module-a40872.o:function $sSf5exp10yS2fFZ: error: undefined reference to 'powf'
/tmp/lit_tmp_Ch1io5/differentiable_attr_other_module-a40872.o:differentiable_attr_other_module-a40872.o:function $sSf5expm1yS2fFZ: error: undefined reference to 'expm1f'
/tmp/lit_tmp_Ch1io5/differentiable_attr_other_module-a40872.o:differentiable_attr_other_module-a40872.o:function $sSf3logyS2fFZ: error: undefined reference to 'logf'
/tmp/lit_tmp_Ch1io5/differentiable_attr_other_module-a40872.o:differentiable_attr_other_module-a40872.o:function $sSf4log2yS2fFZ: error: undefined reference to 'log2f'
/tmp/lit_tmp_Ch1io5/differentiable_attr_other_module-a40872.o:differentiable_attr_other_module-a40872.o:function $sSf5log10yS2fFZ: error: undefined reference to 'log10f'
/tmp/lit_tmp_Ch1io5/differentiable_attr_other_module-a40872.o:differentiable_attr_other_module-a40872.o:function $sSf5log1pyS2fFZ: error: undefined reference to 'log1pf'
/tmp/lit_tmp_Ch1io5/differentiable_attr_other_module-a40872.o:differentiable_attr_other_module-a40872.o:function $sSf3powyS2f_SftFZ: error: undefined reference to 'powf'
/tmp/lit_tmp_Ch1io5/differentiable_attr_other_module-a40872.o:differentiable_attr_other_module-a40872.o:function $sSf3powyS2f_SitFZ: error: undefined reference to 'powf'
/tmp/lit_tmp_Ch1io5/differentiable_attr_other_module-a40872.o:differentiable_attr_other_module-a40872.o:function $sSf4rootyS2f_SitFZ: error: undefined reference to 'powf'
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
```

I'm able to reproduce this error on Ubuntu but not on macOS.
Explicitly linking the math library via `-lm` fixes the issue but that doesn't seem robust.

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Pull request merged**
