### PR TITLE
[AutoDiff] Fix TBDGen issues for derivative dispatch thunks and method descriptors.

### PR DESCRIPTION
**Pull request by rxwei**
- Add `DispatchThunkDerivative` and `MethodDescriptorDerivative` as link entities. The derivative functions of initializers, subscripts, properties, and methods are **all methods**, so we don't need other link entities for this purpose.
- Mangle dispatch thunks and method descriptors. Make `AutoDiffFunction` a context node since it can be nested.

Resolves SR-13866 (rdar://71318828) and SR-13125 (rdar://65240599).

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test

**Review by dan-zheng — APPROVED** [review]

**Review by joshnewnham — APPROVED** [review]

**Comment by rxwei** [comment]
@swift-ci please test and merge

**Comment by rxwei** [comment]
@swift-ci please test and merge

**Comment by rxwei** [comment]
@swift-ci please test and merge

**Pull request merged**
