### PR TITLE
[SIL] Added borrow scopes to alloc_boxes.

### PR DESCRIPTION
**Pull request by nate-chandler**
Because AllocBoxToStack is not able to transform every alloc_box into an alloc_stack, it's necessary to add begin_borrow [lexical] to every alloc_box in order to provide lexical scopes for those alloc_boxes which will not be transformed into alloc_stacks.
    
Now that alloc_boxes whose lifetimes are lexical are emitted with begin_borrow [lexical]/end_borrow, AllocBoxToStack needs to be able to see through those new borrow scopes in order to continue stack promoting the same boxes that it was able to before those lexical scopes were emitted.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please clean test macos platform

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by atrick — APPROVED** [review]
Thanks! That's a ton of tests to fix!

**Comment by nate-chandler** [comment]
@swift-ci please test macos platform

**Pull request merged**
