### PR TITLE
Revert "Support @noescape SIL function types. (#12420)"

### PR DESCRIPTION
**Pull request by gparker42**
This reverts commit d369aa40705d14a3ddf3bbbc026f77632f52e756.
It is failing in ASAN tests.

### CODE REVIEW

**Comment by gparker42** [comment]
@swift-ci please test asan

**Comment by gparker42** [comment]
@swift-ci please asan test

**Comment by gparker42** [comment]
@swift-ci please smoke test

**Comment by atrick** [comment]
Fixed in https://github.com/apple/swift/pull/12505.

**Comment by gparker42** [comment]
Good thing the tests took so long. Thanks, Andy.

**Pull request closed without merging**
