### PR TITLE
[benchmark] Add a version of Prims that uses Unmanaged._withUnsafeGuaranteedRef

### PR DESCRIPTION
**Pull request by gottesmm**
I also added versions that use closure access for the other benchmark prims just to make comparisons fair.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
The only setup time overhead is from initializing the priority queue. I think if we have that, it is probably ok.

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Review by lorentey — COMMENTED** [review]
lgtm!

**Review by lorentey — APPROVED** [review]

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Pull request merged**
