### PR TITLE
[DON'T MERGE][stdlib] Set, Dictionary: Make storage classes resilient

### PR DESCRIPTION
**Pull request by lorentey**
Let's try removing `@_fixed_layout` from `Set` and `Dictionary` storage classes.

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci please smoke test

**Comment by lorentey** [comment]
@swift-ci please smoke benchmark

**Comment by lorentey** [comment]
@swift-ci please smoke test

**Comment by lorentey** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@lorentey Do you still want to hold this open?  The change is ABI breaking.

**Comment by lorentey** [comment]
Oh no, we can close this now.

**Pull request closed without merging**
