### PR TITLE
[test] modify to be compatible with minimal stdlib

### PR DESCRIPTION
**Pull request by glessard**
- validate that unaligned loads work for types with large alignments
- in the minimal stdlib, only `Builtin` types can be used for this

This is a better fix for rdar://97029576, improving on https://github.com/apple/swift/pull/60061

### CODE REVIEW

**Comment by glessard** [comment]
@swift-ci please test

**Review by atrick — APPROVED** [review]
Looks good!

**Comment by glessard** [comment]
@swift-ci please test and merge

**Comment by glessard** [comment]
@swift-ci please test macOS platform

**Comment by glessard** [comment]
@swift-ci please test Windows platform

**Pull request merged**
