### PR TITLE
[Do Not Merge] Testing SourceKit error response

### PR DESCRIPTION
**Pull request by rintaro**
🙅‍♂️ just testing.

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by rintaro** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by rintaro** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by rintaro** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by CodaFi** [comment]
@rintaro Do you still need this PR?

**Pull request closed without merging**
