### PR TITLE
[Incremental] Supports per-type-body fingerprints, on-by-default

### PR DESCRIPTION
**Pull request by davidungar**
1. Changed granularity of (fine-grained) dependency graph traversal to support tracking changes to individual node fingerprints.
2. Changed semantics of transitive traversal to simplify meaning of a mark from "was a dependent of a cascading job" to "this node has been traversed".
3. Adds -enable-type-fingerprints disabled by default.
4. Changes driver handling of jobs when one job fails. Don't bother marking all unfinished jobs as cascading if they were previously thought to be. Just mark then as non-cascading-build required. On next run, if they are cascading the dependent jobs will get run.
5. When the option above is set, the parser will hash tokens within a nominal type body or extension body into a per-body hash instead of the whole-file interface hash.
6. Adjust tests accordingly.

-- A virtually-identical PR, 29482, has been examined by @CodaFi

### CODE REVIEW

**Comment by davidungar** [comment]
@swift-ci please smoke test os x platform

**Comment by davidungar** [comment]
@swift-ci please smoke test os x platform

**Comment by davidungar** [comment]
@swift-ci please clean smoke test os x platform

**Comment by davidungar** [comment]
@swift-ci please smoke test os x platform

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Comment by davezarzycki** [comment]
Why MD5? Why not SHA1 which can be hardware accelerated on some processors? (Yes, SHA1 is slightly bigger, but you can just truncate the result if that matters.)

**Comment by CodaFi** [comment]
I imagine it’s because LLVM already has the facilities for this. I’d prefer we use something like 128-bit siphash but it’s certainly a decision we can revisit.

**Comment by davidungar** [comment]
Yes, the use of MD5 follows what was done for the original, whole-file, interface hash.

**Pull request merged**
