### PR TITLE
[stdlib] Change some stdlib method arguments to __owned

### PR DESCRIPTION
**Pull request by airspeedswift**
Gonna start small at first just with `Array.append(_:)` and go from there.

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
Ohhhkay, not so much with the performance wins with that one. Trying a few more. Not at all convinced these are the right defaults for dictionary values, but let's see what the numbers say.

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
It's ok swift-ci I understand, it's early and you haven't had your coffee yet.

**Comment by gottesmm** [comment]
@airspeedswift Keep in mind that some of the regressions we spoke about yesterday are a result of certain optimizations being turned off. Specifically the contentsOf bug and some stuff around literals are things I am going to fix ASAP.

**Comment by airspeedswift** [comment]
\*tap tap\* is this thing on?

**Pull request closed without merging**
