### PR TITLE
AST: Stricter verifier check for TupleExpr

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@jrose-apple You added the original verifier check. Any reason it was a subtype relation and not type equality?

**Comment by slavapestov** [comment]
(I guess I'm about to learn once the test suite completes)

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
Apparently it wasn't important after all. Stricter verifier checks are better!

**Pull request merged**
