### PR TITLE
[WIP] Failure analysis based on the constraint solver information

### PR DESCRIPTION
**Pull request by xedin**
This is an alternative approach to current status quo, where we try to type-check
each sub-expressions to try and locate the error. Instead of doing that, this
patch tracks constraint solver failures and each path taken, and based on that tries
to produce diagnostics according to most common failure locations.

This makes it very easy to locate and diagnose failures related to structure of parameters,
shadowing, contextual conversions and generic requirements among many others.

### CODE REVIEW

**Comment by xedin** [comment]
@rudkx This is still very raw please take an initial look, here are some cases were diagnostics are much better than right now:

```swift
extension Sequence where Iterator.Element == (key: String, value: String) {
  func f() -> Array<Int> {
    return []
  }
}

func a(_ b: Array<Int>) {}

func b() {
  ["a": 2].f()
}
```

Is going to produce following diagnostic:

```
error: cannot convert value of type 'Int' to expected dictionary value type 'String'
    ["a": 2].f()
          ^
```

```swift
func foo(answer: Int) -> String { ... }
func foo(answer: String) -> String { ... }

let _: [String] = [42].map { foo($0) }
```

Produces:

```
error: missing argument label 'answer:' in call
let _: [String] = [42].map { foo($0) }
                                 ^
                                 answer:
```

**Comment by rudkx** [comment]
Was this separate from your other changes to capture more state at the point of failure in the solver, or do those changes supersede this?

**Comment by xedin** [comment]
@rudkx I think they should supersede this, this PR is just an experiment to see if we can track the state in constraint system to be used by diagnostics. Going to close it.

**Pull request closed without merging**
