### PR TITLE
Moving IDE code to GenericSignature and GenericFunctionType

### PR DESCRIPTION
**Pull request by slavapestov**
This cleans up code completion, module interface printing, and the SourceKit CursorInfo thing to stop using `PolymorphicFunctionType` as well as some obsolete functionality on a `GenericParamList`.

The old code contained a number of workarounds for limitations of the type-checked `RequirementRepr` representation, which should no longer be used in favor of `GenericSignature::getRequirements()`. The new code for printing `GenericSignatures` and `GenericFunctionTypes` is a lot simpler in comparison. Everything is written with interface types, and requirements are canonicalized and easily substitutable.

This means we don't have to serialize the requirements section of a `GenericParamList` anymore at all -- previously both the types and string representations of requirements had to be serialized, and the strings later _parsed_, which was gross.

The parameters of a `GenericParamList` are still serialized, to give a home to `GenericTypeParamDecls` that appear in sugared `GenericTypeParamTypes`, which makes sense I think.

There were some minor changes to code completion and interface printing output. I hope that's okay. We should just add whatever heuristics we need to the new GenericSignature-based printing instead.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by nkcsgexi** [comment]
@slavapestov awesome! Thanks for simplifying the ide part.

**Comment by slavapestov** [comment]
@nkcsgexi Any ideas about the IDE/complete_constructor failure? When I run it locally, I see that if I run the test in isolation, it passes, but if I run it with the other IDE tests, the code completion cache somehow gets 'polluted', so when the HAVE_COMMA_1 query is performed, we have constructors in the results that we didn't expect.

I don't think my changes affect which decls are chosen in the results, perhaps the existing completion cache code has a bug where it sometimes encounters cache collisions of this form?

**Comment by nkcsgexi** [comment]
I cannot see any of your changes make the completion selection different. Have you tried to erase cache before running the tests (even though I think this is the default)? is it still failing?

**Comment by slavapestov** [comment]
Yes, it's failing in ci. Every test run starts with a fresh completion cache, but any tests that appear before complete_constructor seem to affect the cache.

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please clean test Linux

**Comment by slavapestov** [comment]
@swift-ci Please clean test macOS

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by DougGregor** [comment]
This is fantastic. Merge it! ;)

**Pull request merged**
