### PR TITLE
Merge tag 'swift-DEVELOPMENT-SNAPSHOT-2019-08-05-a' into tensorflow

### PR DESCRIPTION
**Pull request by burmako**

### CODE REVIEW

**Comment by burmako** [comment]
@swift-ci please clean test tensorflow

**Comment by burmako** [comment]
@pschuh I had to disable `ClangImporter/cxx_interop.swift` and `ClangImporter/cxx_interop_ir.swift` to make tests pass. Please let me know if this needs to be fixed right away, or we can turn this into a ticket.

**Review by dan-zheng — APPROVED** [review]
LGTM! (`Sema` changes make sense to me.)

**Comment by burmako** [comment]
@swift-ci please clean test tensorflow

**Review by pschuh — APPROVED** [review]

**Comment by burmako** [comment]
@swift-ci please clean test tensorflow

**Pull request merged**
