### PR TITLE
ObjC Interop

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by DougGregor** [comment]
Hey, this is cool. Thanks @compnerd

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@fjricci took over this patch while I was away.  Let him finish off the work

**Comment by gcasa** [comment]
Please let me know if the GNUstep community can be of any assistance in integrating this as it is of interest to myself and others.

**Pull request closed without merging**
