### PR TITLE
[AutoDiff] Remove deprecated method-style differential operators.

### PR DESCRIPTION
**Pull request by dan-zheng**
Remove deprecated APIs, since they've been deprecated for a full release cycle.

### CODE REVIEW

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Review by rxwei — APPROVED** [review]

**Comment by dan-zheng** [comment]
Running extended test suite to detect breakages.

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
Merging to unblock progress. validation-test/Python/python_lint.swift can be fixed later.

**Pull request merged**
