### PR TITLE
[Mangling] Improve handling of the variadic function parameters

### PR DESCRIPTION
**Pull request by xedin**
Currently when function types like `(_: Int...) -> Void` are mangled
their names are going to include enclosing sugar BoundGenericType(Array),
which is not necessary and doesn’t play well with `AnyFunctionType::Param`
which strips the sugar away.

Resolves: rdar://problem/34941557

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please clean test

**Review by DougGregor — APPROVED** [review]
This LGTM, thanks!

**Review by eeckstein — APPROVED** [review]
lgtm
Thanks!

**Pull request merged**
