### PR TITLE
Refactor accessibility checking to use TypeReprs (most of the time) rather than Types

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@jrose-apple I'd like you to review this before I check it in.

**Comment by jrose-apple** [comment]
The point of the original caching code was that pieces of types are reused quite a bit. I don't think the work of computing an access scope is enough to cache, but if it is it's probably worth caching *outside* of Sema.

Didn't @DougGregor just do this?

**Comment by DougGregor** [comment]
I just did this for *availability* checking, here: https://github.com/apple/swift/pull/6036

**Comment by jrose-apple** [comment]
Wait no don't merge this yet

**Comment by slavapestov** [comment]
Oops, sorry. I can revert or make any changes you request.

**Comment by jrose-apple** [comment]
Please revert for now. Either we care about the caching thing or we don't; beyond that I haven't really looked at what it's doing yet.

**Pull request merged**
