### PR TITLE
[Distributed] Add fixits for distributed system adhoc requirements

### PR DESCRIPTION
**Pull request by ktoso**
We only printed text of what the methods should be, rather than emitting a fixit for the ad-hoc requirements the actor system is cursed/blessed with 👻

Instead, we now offer a proper fixit such that adopting `DistributedActorSystem` will be as simple as normal types: clicking the fixit button.

Before merging I want to test drive this in Xcode to see the diagnostics really work and feel the same as normal ones.

rdar://114185115

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please build toolchain

**Review by xedin — APPROVED** [review]

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
Failed to clone

**Comment by ktoso** [comment]
@swift-ci please smoke test macOS

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
@swift-ci please build toolchain macOS

**Comment by ktoso** [comment]
@swift-ci please smoke test and merge

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Pull request merged**
