### PR TITLE
ModuleTrace: address code review comments. NFC

### PR DESCRIPTION
**Pull request by nkcsgexi**
Addressing code review comments on the previous PR: https://github.com/swiftlang/swift/pull/77217

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Review by artemcm — APPROVED** [review]
Thanks!

**Review by bnbarham — APPROVED** [review]

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Pull request merged**
