### PR TITLE
[CSDiagnostics] When emitting rawValue init fix-it, check if there's a label-less init

### PR DESCRIPTION
**Pull request by theblixguy**
If we have the following code:

```swift
enum Foo: RawRepresentable {
  init(_ rawValue: Int) {}
  init(rawValue: Int) {}
  var rawValue: Int { return 0 }
}

func takesFoo(_: Foo) {}
takesFoo(0)
```

We'll trigger the following error:

```
cannot convert value of type 'Int' to expected argument type 'Foo'
```

along with a fix-it to insert `Foo(rawValue:)`:

```
takesFoo(0)
         ^
         Foo(rawValue:  )

After fix-it is applied -> takesFoo(Foo(rawValue: 0))
```

However, `Foo` also has a label-less init (`_: rawValue: Int`), which would be nicer to use instead:

```
takesFoo(0)
         ^
         Foo( )

After fix-it is applied -> takesFoo(Foo(0))
```

Resolves SR-4723
Resolves rdar://problem/32265506

### CODE REVIEW

**Comment by theblixguy** [comment]
@swift-ci please smoke test

**Review by xedin — CHANGES_REQUESTED** [review]
Sorry but I don't think that this is quite right. `init(rawValue:)` could have completely different logic comparing to `init(_:)`. If you want to make this work, you'd have to create a separate fix which attempts to construct an initializer call passing argument as its argument, match it against the parameter type and produce a special diagnostic for it.

**Comment by theblixguy** [comment]
@xedin This only considers label-less initializers that accept a _single_ argument of the _raw_ type, so I think it shouldn’t be a problem?

At the moment, it doesn’t check the argument label but we can add another restriction that it must be `rawValue` as well.

**Comment by xedin** [comment]
What I'm trying to say is that regardless of particular `RawRepresentable` case we'd probably want a separate fix which would suggest to call label-less initializer if one exists, that would improve user experience in a bunch of cases. In a current form of a `RawPresentable` type mismatch we can only suggest a requirement `init(rawValue:)` because that's targeted to ease of migration of cases where argument used to be a string or a number which has been converted to `RawPresentable` enum once that became available in the language.

**Comment by theblixguy** [comment]
Okay, sure, I think I understand you’re trying to say. Although I’m not sure why it has to be a separate ConstraintFix, because I think we can just attach a note to the argument type mismatch diagnostic which offers a fix-it to call the label-less initialiser, in addition to whatever fix-it tryRawRepresentableFixIt adds. Is that reasonable?

**Comment by xedin** [comment]
bq. Although I’m not sure why it has to be a separate ConstraintFix

This is not about just the note. We need to make sure that initializer we are trying to suggest does indeed match what if it's `<T: Numeric>init(_: T)` where the argument is a `String`? Suggesting that initialier doesn't lead to a valid code.

**Comment by xedin** [comment]
That initializer could also be overloaded and there could be a couple of choices which match.

**Comment by theblixguy** [comment]
Such cases are already handled though, because it looks for a concrete `init(_ argumentLabel: RawType)` and as long as there's at least one, it will be suggested. But sure, we can make it smarter and handle other cases (such as if the type had a `init<T: StringProtocol>(_ argumentLabel: T)` and we passed a value of type `String`, then that `init` can be suggested).

My thinking was to have a simple and conservative check, so we can easily handle the common case. But if you think it's better to create a fix, then I can surely do that :)

**Comment by xedin** [comment]
Yes, I think if we really want to do this let's do it via the most general fix possible that would make it possible to remove special cases for `String` and integer types as well.

**Comment by xedin** [comment]
And provide a list of potential overloads in other cases.

**Comment by theblixguy** [comment]
Sounds good! To clarify, instead of recording an argument type mismatch fix, we record a new fix instead which is specifically for raw representable types, so if the expected argument type is a raw representable type and it contains an initializer that takes the passed argument type then we create that fix?

**Comment by xedin** [comment]
I think we should do it the following way - in `repairFailures` check whether parameter type has any initializers with a single parameter without a label (via lookup just like you did in the diagnostic), form an implicit constructor call where every choice is going to have a special fix attached (similar to what how we have it for member refs), and one more choice in the end which is going to produce generic `ArgumentTypeMismatch` in situation where none of the constructors did match. I think this is a general enough thing so it should be done for any type. Does it make sense?

**Comment by theblixguy** [comment]
Sure! Could you clarify the “form an implicit constructor call” part?

**Comment by xedin** [comment]
Sometimes it also calls into `matchTypes` too which generates constraints :) In this particular case we'd need to emulate what `member` constraint would do and add a `applicable fn` constraint:

1. Call lookupMember to find initializers with base type being metatype of parameter type (filter on each having only one parameter without a label);
2. Create a new `member type` type variable and disjunction constraint which binds it to each result of step 1 (each choice would have to have a new fix attached to it);
3. Add `applicable fn` constraint which relates member type from step 2 with current argument type e.g. `(<arg type>) -> <param type> applicable to <member type>`;
3. `return true;` and let the solver run.

This way if at least one overload matches solution would record the viable declaration which note can point to, as well as the fix which would suggest add call to initializer.

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
