### PR TITLE
[Foundation] Implementation of SE-0170 for safer NSNumber bridging

### PR DESCRIPTION
**Pull request by phausler**
This is the implementation for the updated bridging behavior for numeric types and NSNumber.

### CODE REVIEW

**Comment by phausler** [comment]
@swift-ci please test and merge

**Comment by tkremenek** [comment]
@swift-ci clean test

**Comment by phausler** [comment]
hmm I claim shenanigans!

```swift
import Foundation
let t = -Int64(bitPattern: 6)
let n = NSNumber(value: t)
let n2 = NSNumber(value: -Int64(bitPattern: 6))
```

that builds just fine. Why does the test on the build bot think that 6 is a double literal? Is this a regression?

**Comment by phausler** [comment]
also NSNumberBridging.swift.gyb was deleted and it failed even after the clean build?

**Comment by phausler** [comment]
The Linux compile failure is not associated with this commit. None of the changes should be built for that platform

**Comment by parkera** [comment]
The NSNumberBridging.swift.gyb file that failed is not the one you deleted but one in the validation tests.

`/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/validation-test-macosx-86_64/stdlib/Output/NSNumberBridging.swift.gyb.tmp/main.swift`

**Comment by phausler** [comment]
@swift-ci test and merge

**Comment by phausler** [comment]
@swift-ci please test and merge

**Comment by phausler** [comment]
@swift-ci please test and merge

**Comment by tkremenek** [comment]
This is failing on the simulator:

~~~
******************** TEST 'Swift(iphonesimulator-i386) :: stdlib/ValidationNSNumberBridging.swift' FAILED ********************
13:56:37 Script:
13:56:37 --
13:56:37 rm -rf /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/validation-test-iphonesimulator-i386/stdlib/Output/ValidationNSNumberBridging.swift.tmp && mkdir -p /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/validation-test-iphonesimulator-i386/stdlib/Output/ValidationNSNumberBridging.swift.tmp && xcrun --toolchain default --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/bin/swiftc -target i386-apple-ios7.0  -module-cache-path '/var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/swift-testsuite-clang-module-cachekeujqp' -F /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk/../../../Developer/Library/Frameworks  -swift-version 3  -module-cache-path '/var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/swift-testsuite-clang-module-cachekeujqp' /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/validation-test/stdlib/ValidationNSNumberBridging.swift -o /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/validation-test-iphonesimulator-i386/stdlib/Output/ValidationNSNumberBridging.swift.tmp/a.out -module-name main && xcrun --toolchain default --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk simctl spawn 'iPhone 6'  /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/validation-test-iphonesimulator-i386/stdlib/Output/ValidationNSNumberBridging.swift.tmp/a.out
13:56:37 --
13:56:37 Exit Code: 134
13:56:37 
13:56:37 Command Output (stdout):
13:56:37 --
13:56:37 [ RUN      ] NSNumberBridgingValidation.Bridge Int8
13:56:37 [       OK ] NSNumberBridgingValidation.Bridge Int8
13:56:37 [ RUN      ] NSNumberBridgingValidation.Bridge UInt8
13:56:37 [       OK ] NSNumberBridgingValidation.Bridge UInt8
13:56:37 [ RUN      ] NSNumberBridgingValidation.Bridge Int16
13:56:37 [       OK ] NSNumberBridgingValidation.Bridge Int16
13:56:37 [ RUN      ] NSNumberBridgingValidation.Bridge UInt16
13:56:37 [       OK ] NSNumberBridgingValidation.Bridge UInt16
13:56:37 [ RUN      ] NSNumberBridgingValidation.Bridge Int32
13:56:37 [       OK ] NSNumberBridgingValidation.Bridge Int32
13:56:37 [ RUN      ] NSNumberBridgingValidation.Bridge UInt32
13:56:37 [       OK ] NSNumberBridgingValidation.Bridge UInt32
13:56:37 [ RUN      ] NSNumberBridgingValidation.Bridge Int64
13:56:37 [       OK ] NSNumberBridgingValidation.Bridge Int64
13:56:37 [ RUN      ] NSNumberBridgingValidation.Bridge UInt64
13:56:37 [       OK ] NSNumberBridgingValidation.Bridge UInt64
13:56:37 [ RUN      ] NSNumberBridgingValidation.Bridge Int
13:56:37 [       OK ] NSNumberBridgingValidation.Bridge Int
13:56:37 [ RUN      ] NSNumberBridgingValidation.Bridge UInt
13:56:37 stdout>>> check failed at /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/validation-test/stdlib/ValidationNSNumberBridging.swift, line 605
13:56:37 stdout>>> this code should not be executed
13:56:37 stdout>>> Optional(4.2949673e+09) != nil Float
13:56:37 stdout>>> check failed at /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/validation-test/stdlib/ValidationNSNumberBridging.swift, line 605
13:56:37 stdout>>> this code should not be executed
13:56:37 stdout>>> Optional(4.2949673e+09) != nil Float
13:56:37 stdout>>> check failed at /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/validation-test/stdlib/ValidationNSNumberBridging.swift, line 605
13:56:37 stdout>>> this code should not be executed
13:56:37 stdout>>> Optional(4.2949673e+09) != nil Float
13:56:37 stdout>>> check failed at /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/validation-test/stdlib/ValidationNSNumberBridging.swift, line 605
13:56:37 stdout>>> this code should not be executed
13:56:37 stdout>>> Optional(4.2949673e+09) != nil Float
13:56:37 [     FAIL ] NSNumberBridgingValidation.Bridge UInt
13:56:37 [ RUN      ] NSNumberBridgingValidation.Bridge Float
13:56:37 [       OK ] NSNumberBridgingValidation.Bridge Float
13:56:37 [ RUN      ] NSNumberBridgingValidation.Bridge Double
13:56:37 [       OK ] NSNumberBridgingValidation.Bridge Double
13:56:37 [ RUN      ] NSNumberBridgingValidation.Bridge CGFloat
13:56:37 [       OK ] NSNumberBridgingValidation.Bridge CGFloat
13:56:37 [ RUN      ] NSNumberBridgingValidation.bitPattern to exactly
13:56:37 [       OK ] NSNumberBridgingValidation.bitPattern to exactly
13:56:37 NSNumberBridgingValidation: Some tests failed, aborting
13:56:37 UXPASS: []
13:56:37 FAIL: ["Bridge UInt"]
13:56:37 SKIP: []
13:56:37 To debug, run:
13:56:37 $ /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/swift-macosx-x86_64/validation-test-iphonesimulator-i386/stdlib/Output/ValidationNSNumberBridging.swift.tmp/a.out --stdlib-unittest-in-process --stdlib-unittest-filter "Bridge UInt"
13:56:37 
13:56:37 --
13:56:37 Command Output (stderr):
13:56:37 --
13:56:37 Child process terminated with signal 6: Abort trap
13:56:37 
13:56:37 --
13:56:37 
~~~

**Comment by tkremenek** [comment]
@swift-ci clean test macOS

**Comment by phausler** [comment]
That test failure is legit. Will have a fix pushed tomorrow

**Comment by phausler** [comment]
so this is yet another version of the `Float.init?(exactly:)` failure.

**Comment by phausler** [comment]
@swift-ci please test and merge

**Pull request merged**
