### PR TITLE
Fix flipped 0/1 values in SimplifyBuiltin.optimizeAssertConfig

### PR DESCRIPTION
**Pull request by kubamracek**
The expectations for the resolved values of `Builtin.assert_configuration()` are (per AssertCommon.swift):
```
    // The values for the assert_configuration call are:
    // 0: Debug
    // 1: Release
    // 2: Fast / Unchecked
```
And this is how ConstantFolding.cpp implements it, but it turns out that the complementary SimplifyBuiltin pass is using wrong integer values. Let's fix that.

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Review by eeckstein — APPROVED** [review]
Thanks for fixing this!
You also need to fix the test case in SILOptimizer/simplify_builtin.sil

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Pull request merged**
