### PR TITLE
DO NOT MERGE: speculatively change semantics of _fastPath

### PR DESCRIPTION
**Pull request by milseman**
_fastPath has the unfortunate side effect of blowing AC all over the rest of the code. Let's combat code cooling by trying a benchmark run where we have its semantics merely be builtin_expect.

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please benchmark

**Comment by milseman** [comment]
CC @dabrahams

**Comment by dabrahams** [comment]
@milseman Use smoke benchmark for faster turnaround times.

**Comment by airspeedswift** [comment]
Uh... ok then.

**Comment by milseman** [comment]
@eeckstein this subvert the "branchhint" semantics, but keeps the "fastpath" semantics as well as the builtin_expect semantics. I'll also try a run tonight where we do a total no-op without any semantic clues.

**Comment by eeckstein** [comment]
Please also look at code size differences. The effect of the "cold-block-info" is mostly to prevent inlining and thus reduce code size

**Comment by gottesmm** [comment]
@shahmishal @eeckstein @lplarson Hmmm... I am pretty sure that swift-ci benchmark could gather code size measurements on the perf test object files for sure.

**Comment by milseman** [comment]
@swift-ci please smoke benchmark

**Pull request closed without merging**
