### PR TITLE
Remove ~moduleonly Duplicate of Compilation Record

### PR DESCRIPTION
**Pull request by CodaFi**
We thought we would need this while exploring  certain pre-build optimizations a la rdar://problem/37725110. This information was never used.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by rintaro** [comment]
Just to clarify. This PR just removes the build record duplicated to '~moduleonly'  when building normally. But it preserves the behavior in `-emit-module` only build (using `~moduleonly` build record). Is it your intention?

**Comment by CodaFi** [comment]
> Is it your intention?

Oh, good point. No, I want all of this scrubbed out of the Driver. Here's a more aggressive copy.

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Review by rintaro — APPROVED** [review]

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
