### PR TITLE
[Syntax] Update DeclNodes.py for designated protocols parsing support.

### PR DESCRIPTION
**Pull request by rudkx**
SwiftSyntax support for https://github.com/apple/swift/pull/19145.

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by harlanhaskins** [comment]
Looks correct. Can you update the grammar comment above that node to

```
# infix-operator-group -> ':' identifier ‘,’? identifier?
```

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Review by harlanhaskins — APPROVED** [review]
LGTM!

**Pull request merged**
