### PR TITLE
[test] Version-guard some emoji tests.

### PR DESCRIPTION
**Pull request by milseman**
Gate some emoji tests on a new enough iOS version.

rdar://problem/42139928

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
CC @allevato

**Comment by milseman** [comment]
The properties are available, just the answers to queries can change with the version of Unicode. This is no different than say, `String.count`, which also changes with each new version of Unicode.

Separately, yes, bundling a version of ICU would help Linux. It wouldn't affect this change, as Darwin should use the system's ICU.

**Comment by milseman** [comment]
@swift-ci please test and merge

**Comment by allevato** [comment]
> The properties are available, just the answers to queries can change with the version of Unicode. This is no different than say, `String.count`, which also changes with each new version of Unicode.

Ok, that's fair (the fact that we already have that issue with `String.count`, or with grapheme cluster breaking).

The fact that some of these properties are still unreliable depending on OS version still makes me a bit uncomfortable though, since I don't believe there's any obvious way for a user to map their platform/OS version to the version of Unicode that the system supports. One thing that came up during the proposal review was adding an API to the `Unicode` namespace that would let the user get the version triple of the Unicode that the system supported. Should we consider adding that so that the user has a trap door if they need fallback logic?

**Comment by milseman** [comment]
> One thing that came up during the proposal review was adding an API to the Unicode namespace that would let the user get the version triple of the Unicode that the system supported. Should we consider adding that so that the user has a trap door if they need fallback logic?

Definintely!

**Comment by milseman** [comment]
@swift-ci please test and merge

**Pull request merged**
