### PR TITLE
Add test case for disabling lexical lifetimes.

### PR DESCRIPTION
**Pull request by atrick**
Make sure the option for restoring pre-5.7 lifetime behavior works in
the 5.7 release.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test

**Review by nate-chandler — APPROVED** [review]
LGTM!

**Comment by atrick** [comment]
@swift-ci smoke test and merge

**Comment by atrick** [comment]
@swift-ci clean smoke test and merge

**Pull request merged**
