### PR TITLE
Use correct associated context for SIL parsing

### PR DESCRIPTION
**Pull request by hamishknight**
Adjust `SILModule::createEmptyModule` to accept a `FileUnit` or `ModuleDecl`, and pass the corresponding context for SIL generation and parsing. This change means that SIL parsing will now correctly use a `SourceFile` associated context when in single-file mode.

In addition, tighten up some invariants around `SILModule` construction.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Review by slavapestov — APPROVED** [review]

**Comment by hamishknight** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
