### PR TITLE
[stdlib][DNM] Test out perf impact of making Hasher resilient

### PR DESCRIPTION
**Pull request by airspeedswift**
Just a perf experiment at this point.

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark staging

**Comment by jrose-apple** [comment]
That's…not nearly as bad as it was the first time we tried it!

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark

**Comment by jrose-apple** [comment]
Oops; after #18862, this diff might not be the right test anymore.

**Comment by jrose-apple** [comment]
Whoops, that should be #19332.

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
OK let's try again with the full fixed-layout removal.

**Comment by jrose-apple** [comment]
Okay, about the same after all.

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
Nope!

**Pull request closed without merging**
