### PR TITLE
[Gardening] Simplify excessive conditional expression: (A && !B) || (!A && B) is equivalent to bool(A) != bool(B)

### PR DESCRIPTION
**Pull request by valeriyvan**

### CODE REVIEW

**Comment by stephentyrone** [comment]
@swift-ci test

**Comment by stephentyrone** [comment]
@swift-ci test macOS

**Comment by valeriyvan** [comment]
ping

**Comment by AnthonyLatsis** [comment]
@valeriyvan "Refactoring" refers a source tooling library and will be misinterpreted. Could you use "Gardening" instead in the commit message?

**Review by hborla — APPROVED** [review]
Heh, oops. Thanks for the simplification!

**Comment by AnthonyLatsis** [comment]
> Could you use "Gardening" instead in the commit message?

Apparently you edited the pull request title, not the commit message.

**Comment by valeriyvan** [comment]
> > Could you use "Gardening" instead in the commit message?
> 
> Apparently you edited the pull request title, not the commit message.

Edited commit message as well.

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
