### PR TITLE
Introduce a new SILGenThunk.cpp

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@gottesmm I hope this is not too disruptive for you. I have some PRs that will have conflicts in them as well now ;-) I'll be doing a lot of work on thunks for class resilience and inlineable, so having the relevant code in one file should help. I'm still not happy with some of the division of responsibility between SILGenThunk.cpp and SILGenPoly.cpp, but one step at a time.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
Also coming up soon, is gutting curry thunks. That should be nice...

**Comment by gottesmm** [comment]
@slavapestov No worries!

**Pull request merged**
