### PR TITLE
docs: convert `weak.rst` document to Markdown

### PR DESCRIPTION
**Pull request by MaxDesiatov**
Converts one of the doc files from reStructuredText to Markdown.

Continues work on SR-7454.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Comment by benrimmington** [comment]
The new file could be renamed to `WeakReferences.md`

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Review by benrimmington — APPROVED** [review]

**Pull request merged**
