### PR TITLE
[DO NOT MERGE] dummy PR for swift-syntax PR testing (master)

### PR DESCRIPTION
**Pull request by rintaro**
**DO NOT MERGE**
This is a dummy PR for testing PRs in `swift-syntax` repo.

### CODE REVIEW

**Comment by rintaro** [comment]
https://github.com/apple/swift-syntax/pull/2
https://github.com/apple/swift-syntax/pull/3
https://github.com/apple/swift-syntax/pull/4
https://github.com/apple/swift-syntax/pull/5
https://github.com/apple/swift-syntax/pull/7

@swift-ci Please smoke test

**Comment by rintaro** [comment]
https://github.com/apple/swift-syntax/pull/2
@swift-ci Please test

**Comment by rintaro** [comment]
apple/swift-syntax#3
@swift-ci Please test

**Comment by rintaro** [comment]
apple/swift-syntax#4
@swift-ci Please test

**Comment by rintaro** [comment]
https://github.com/apple/swift-syntax/pull/4
@swift-ci Please test

**Comment by rintaro** [comment]
https://github.com/apple/swift-syntax/pull/4
@swift-ci Please test

**Comment by rintaro** [comment]
@shahmishal CI seems to be ignoring me.

**Comment by shahmishal** [comment]
@rintaro new line character in the comment caused it to not trigger.
screen shot 2018-09-11 at 12 34 48 pm

**Comment by rintaro** [comment]
https://github.com/apple/swift-syntax/pull/5
@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/5
@swift-ci Please test

**Pull request closed without merging**
