### PR TITLE
[Foundation] Fallback to presuming 32-bit platforms if we dont explicitly know that it is 64 bit; this allows for better portability

### PR DESCRIPTION
**Pull request by phausler**
This should resolve <rdar://problem/46683060>

### CODE REVIEW

**Comment by phausler** [comment]
@swift-ci please smoke test

**Review by itaiferber — APPROVED** [review]
Looks reasonable to me. We'll need to be careful to correctly add 64-bit platforms in the future, but being conservative is good.

**Comment by jrose-apple** [comment]
This seems like a bad idea to me. Most platforms people are trying to port Swift to are 64-bit these days. `#else` + `#error` would be a lot safer.

**Comment by itaiferber** [comment]
@jrose-apple Is there a more future-proof way to avoid breaking the build?

**Comment by jrose-apple** [comment]
This seems like one of those "trap early" philosophy things: it is better to break the build at the point where something is unknown, with an explicit message, then to stumble on and fail later when you don't know what's missing.

**Comment by phausler** [comment]
@swift-ci please smoke test

**Comment by phausler** [comment]
I really wish we had a `#if bits(64) or #if bits(32)` or something like that. It would alleviate this type of error.

**Comment by phausler** [comment]
@swift-ci please smoke test

**Pull request merged**
