### PR TITLE
Fix snippet in OptimizationTips.rst

### PR DESCRIPTION
**Pull request by valeriyvan**
Fix snippet to be compiled

### CODE REVIEW

**Comment by LucianoPAlmeida** [comment]
Not related to the PR itself, but the block above the change states "In Swift, all parameters are passed in at +1,
i.e. the parameters are retained before a callsite, and then are released at the
end of the callee." Is this still correct? As far as I remember calling convention changed since Swift 4.2 and the release was no longer done in the callee right ... cc @CodaFi @varungandhi-apple

**Comment by varungandhi-apple** [comment]
I looked at a toy example and both the retain and release seem to be happening in the caller.

**Comment by LucianoPAlmeida** [comment]
Thanks for looking @varungandhi-apple :)
I found this blog post https://www.jessesquires.com/blog/2018/07/05/swifts-new-calling-convention/ and also a gist from @gottesmm https://gist.github.com/gottesmm/524fca6a4e9fb3d5736a1b9d6686c5e8
It seems like it is indeed the case, so this statement probably needs updating

**Comment by CodaFi** [comment]
> As far as I remember calling convention changed since Swift 4.2 and the release was no longer done in the callee right

Swift is now +0 (guaranteed) by default, yes. 

> I looked at a toy example and both the retain and release seem to be happening in the caller.

But, crucially, not of the parameter itself, which would occur in the caller. The first retain is needed for the store to semantically become a copy. The second occurs because `a` is returned `owned` to the caller.  https://swift.godbolt.org/z/qjxPYf

**Comment by CodaFi** [comment]
@swift-ci smoke test and merge

**Comment by CodaFi** [comment]
@swift-ci smoke test Linux

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
