### PR TITLE
[swift-4.1-branch][stdlib] Utilize conditional conformances for lazy collections

### PR DESCRIPTION
**Pull request by moiseev**
* Explanation: Utilize conditional conformances to simplify
LazyFilter/LazyMap/Lazy Collection hierarchies.
* Scope of Issue: Reduces the API surface (fewer types) of the standard
library, which results in simpler user code.
* Risk: Minimal
* Reviewed By: Ben Cohen
* Testing: Existing automated test suite
* Directions for QA: N/A
* Radar: <rdar://problem/35944334>

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
@swift-ci Please nominate

**Comment by moiseev** [comment]
@swift-ci Please test

**Review by airspeedswift — APPROVED** [review]

**Comment by graydon** [comment]
Sorry but this seems to have broken CI bots again (see rdar://35902381), need to back it out.

**Pull request merged**
