### PR TITLE
Add descriptive doc comments to withMemoryRebound(to:capacity:_:) and…

### PR DESCRIPTION
**Pull request by atrick**
… bindMemory(to:capacity:).

SR-2480: Improve documentation for withMemoryRebound(to:capacity:_:)
rdar://problem/28440528

### CODE REVIEW

**Comment by atrick** [comment]
––– CCC Information –––
• Explanation: Users migrating to Swift 3 often hit a compiler error with a diagnostic pointing them to this API. I have interacted with several developers who don't understand how to use the API. A more detailed description was necessary in the doc comments.
• Scope of Issue: Developers migrating to Swift 3 and using UnsafePointers.
• Origination: SE-0107 UnsafeRawPointer--terse doc comments.
• Risk: None whatsoever.
• Reviewed By: Dave Abrahams
• Testing: None needed.
• Directions for QE: None

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
@swift-ci test OS X.

**Comment by bob-wilson** [comment]
@swift-ci test OS X

**Comment by shahmishal** [comment]
This failed because it was merged before testing was completed.

**Pull request merged**
