### PR TITLE
[SR-5036]: Segfault using KeyPath with NSObject

### PR DESCRIPTION
**Pull request by jckarter**
We need to use the ivar offset variables in this case, since the Swift field offset vector doesn't pick up the adjusted offsets from the ObjC runtime. Fixes SR-5036 | rdar://problem/32488871.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@aciidb0mb3r This swiftpm failure ring a bell?

```
/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/swiftpm/Tests/FunctionalTests/MiscellaneousTests.swift:360: error: MiscellaneousTestCase.testSecondBuildIsNullInModulemapGen : XCTAssertTrue failed - 
17:16:56 Test Case 'MiscellaneousTestCase.testSecondBuildIsNullInModulemapGen' failed (4.209 seconds)
17:16:56 Test Suite 'MiscellaneousTestCase' failed at 2017-06-15 19:15:58.032
17:16:56 	 Executed 1 test, with 1 failure (0 unexpected) in 4.209 (4.209) seconds
17:16:56 Test Suite 'Selected tests' failed at 2017-06-15 19:15:58.032
17:16:56 	 Executed 1 test, with 1 failure (0 unexpected) in 4.209 (4.209) seconds--- bootstrap: error: tests failed with exit status 1
```

**Comment by aciidb0mb3r** [comment]
@jckarter Nope, haven't seen this failure before.

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Pull request merged**
