### PR TITLE
[DNM] Enable `/.../` by default

### PR DESCRIPTION
**Pull request by hamishknight**

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test source comptability

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Comment by shahmishal** [comment]
@swift-ci build toolchain

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
This was tested with the tweaked operator splitting behavior implemented in https://github.com/apple/swift/pull/58505.

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by rintaro** [comment]
@swift-ci build toolchain

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
@swift-ci please build toolchain

**Pull request closed without merging**
