### PR TITLE
[Constraint solver] Move all partitioning into partitionDisjunction

### PR DESCRIPTION
**Pull request by DougGregor**
Centralize the various attempts to partition an overload set into `ConstraintSystem::partitionDisjunction()`, so we have a single place where this logic can be reasoned about and updated.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Review by xedin — COMMENTED** [review]
Nice!

**Comment by DougGregor** [comment]
@swift-ci please smoke test macOS

**Comment by DougGregor** [comment]
@swift-ci please smoke test macOS

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
