### PR TITLE
Enable mandatory copy propagation (shortens -Onone lifetimes)

### PR DESCRIPTION
**Pull request by atrick**
Only the final, one-line commit is new to this PR:
```
- if (P.getOptions().EnableCopyPropagation)
+ if (!P.getOptions().DisableCopyPropagation) {
```
The rest of the commits are included in an NFC commit:
https://github.com/apple/swift/pull/36389

To eliminate ARC traffic, the optimizer reorders object destruction. This changes observable program behavior. If a custom deinitializer produces side effects, code may observe those side effects earlier after optimization. Similarly, code that dereferences a weak reference may observe a 'nil' reference after optimization, while the unoptimized code observed a valid object.

Developers have overwhelmingly requested that object lifetimes have similar behavior in -Onone and -O builds in order to find and diagnose program bugs involving weak references and other lifetime assumptions.

Enabling the copy propagation at -Onone is simply a matter of flipping a switch. -Onone runtime and code size will improve. By design, copy propagation, has no direct affect on compile time. It will indirectly improve optimized compile times, but in debug builds, it simply isn't a factor.

To support debugging, a "poison" flag is added to new destroy_value instructions generated by copy propagation.
When OwnershipModelEliminator lowers destroy_value [poison] it will generate new debug_value instructions with a “poison” flag. Support for poising references was added here:
https://github.com/apple/swift/pull/36389

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci test source compatibility

**Comment by atrick** [comment]
@swift-ci benchmark

**Comment by atrick** [comment]
Full SCK debug build passed.

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci smoke test

**Comment by atrick** [comment]
Please test with following PR:
https://github.com/apple/llvm-project/pull/2674

@swift-ci smoke test

**Comment by atrick** [comment]
Test with the following LLVM PR:
https://github.com/apple/llvm-project/pull/2674

@swift-ci test

**Comment by atrick** [comment]
Test with the following LLVM PR:
apple/llvm-project#2674

@swift-ci test

**Comment by atrick** [comment]
@swift-ci test

**Comment by davezarzycki** [comment]
Hi @atrick – This change caused a 3.45x regression in `ninja check-swift-validation` performance on my machine. Is this expected? The problem seems to be that `FixedPoint.swift.gyb` is significantly slower and the overall test suite performance can be "fixed" by pushing this test into the `long_test` test suite. What should we do?

**Comment by atrick** [comment]
@davezarzycki Temporarily moved the test to long_test
https://github.com/apple/swift/pull/36450

Working on fixing the pathological behavior
https://bugs.swift.org/browse/SR-14363

**Pull request merged**
