### PR TITLE
[CodeCompletion] Look through @dynamicMemberLookup key path functions

### PR DESCRIPTION
**Pull request by ahoppen**
This enables us to provide proper code completion for the function that is being referenced by the dynamic key path.

rdar://79092371
Resolves #57088

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please smoke tes

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please SourceKit stress test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please SourceKit stress test

**Review by rintaro — APPROVED** [review]
I'm not super familiar with `Solution` APIs, but this LGTM

**Review by xedin — APPROVED** [review]

**Pull request merged**
