### PR TITLE
Revert "Merge pull request #42242 from eeckstein/escapeinfo"

### PR DESCRIPTION
**Pull request by compnerd**
This reverts commit c05e064cd831dda5c47ac6360dc82b31fe587d1f, reversing
changes made to c1534d5af9a480f82e0da9d7a4ec5d5341b5a1ab.

This caused a regression on Windows.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @eeckstein @atrick

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by eeckstein** [comment]
@compnerd what regression?

**Comment by eeckstein** [comment]
Anything else than the test fail, which is fixed by https://github.com/apple/swift/pull/42555?

**Comment by eeckstein** [comment]
Never mind, I saw your comment in the other PR. This is already fixed by https://github.com/apple/swift/pull/42555. So the revert was actually not necessary.

**Comment by compnerd** [comment]
https://ci-external.swift.org/job/oss-swift-windows-toolchain-x86_64-vs2019/547/console

Why should the test be an XFAIL?  If you are XFAILing it, do you have a timeline for repairing it?

**Comment by eeckstein** [comment]
The XFAIL was only the workaround from the build wrangler. The problem is a wrong check-pattern.

**Pull request merged**
