### PR TITLE
[5.3] Pull in changes from PR 34323, 34327, 34445 and 34495

### PR DESCRIPTION
**Pull request by shahmishal**
Pull in changes from: 

* [5.3] Fix a miscompile of global variables
* [5.3][stdlib] Fix Array.append(contentsOf:) for arguments of type NSArray 
* [temp-rvalue-opt] Disable handling of load [take] in temp-rvalue-elim. 
* [5.3][Sema] Consider inherited platform unavailability to silence diagnostics

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
Why did you include https://github.com/apple/swift/pull/32621? It's not a bug fix.

**Comment by shahmishal** [comment]
@eeckstein It was merged in to 5.3-20201012 branch - https://github.com/apple/swift/pull/34495

**Comment by eeckstein** [comment]
Ah sorry, it was actually a bug fix

**Review by eeckstein — APPROVED** [review]
lgtm

**Pull request merged**
