### PR TITLE
[Index][SR-9567] Allow unavailable decls to be walked

### PR DESCRIPTION
**Pull request by CodaFi**
Shepherd #21587

@rockbruno

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by rockbruno** [comment]
Thanks for saving these PRs! Rebasing them after so long revealed other issues, so the only way was to start over...

**Comment by CodaFi** [comment]
@nathawes Could you take one more look at this? Should be the same as the other one.

**Review by nathawes — APPROVED** [review]
LGTM – thanks!

**Pull request merged**
