### PR TITLE
Platform: add a definition for `std` on Windows

### PR DESCRIPTION
**Pull request by compnerd**
This adds the c++ module for Windows to help further the C++ interop.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @egorzhdan @zoecarver @hyp

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please build toolchain windows platform

**Review by egorzhdan — APPROVED** [review]
Looks amazing! Does clang report any modularization issues when trying to import that module? If not, that's great!

Could you please also add a test for the stdlib module interface? We already have these tests for libc++ and libstdc++ (`swift/test/Interop/Cxx/stdlib`).
(doesn't have to be a part of this PR)

**Comment by compnerd** [comment]
clang doesn't seem to object any longer.  There was a fair amount of restructuring that I did to get this to work.  The tests and a couple of small samples locally seem to be able to use `-fmodules` with `clang++` with this.  Sure, I can add a test in a follow up.

**Pull request merged**
