### PR TITLE
[Test] Fix implementation-only-import-suggestion for Apple Silicon

### PR DESCRIPTION
**Pull request by xymus**
Fix test on Apple Silicon causing https://ci.swift.org/job/oss-swift-incremental-RA-macos-apple-silicon/280/.

### CODE REVIEW

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by xymus** [comment]
@swift-ci test Apple Silicon macOS platform

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by xymus** [comment]
@swift-ci test Apple Silicon macOS platform

**Comment by xymus** [comment]
@swift-ci test Apple Silicon macOS platform

**Comment by xymus** [comment]
@swift-ci test Apple Silicon macOS platform

**Comment by shahmishal** [comment]
@swift-ci test Apple Silicon macOS platform

**Comment by xymus** [comment]
@swift-ci Please smoke test Linux platform

**Comment by xymus** [comment]
@swift-ci Please smoke test Linux

**Comment by xymus** [comment]
The test passed on Apple Silicon, it now fails at building Yams. https://ci.swift.org/job/swift-PR-macos-apple-silicon/39/

**Comment by xymus** [comment]
The Yams issue is tracked by rdar://75042876.

**Pull request merged**
