### PR TITLE
[ownership] Move ownership lowering after serialization on stdlibCore.

### PR DESCRIPTION
**Pull request by gottesmm**
Title says it all. This has a few small PRs to fix issues that I found. I am probably going to test and then rebase.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
Funny story, the test failure is actually a test that had the regex setup to only pattern match a register up to %9 (that is it wouldn't pattern match %10). I fixed the test so we can do the pattern match appropriately now.

**Comment by gottesmm** [comment]
I am going to wait for the benchmarks to run then I am going to do another push with the fix/redo the test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci build toolchain

**Comment by eeckstein** [comment]
Any idea why there is so much churn in the benchmarks?

**Comment by gottesmm** [comment]
I started to look at Breadcrumbs. I think @_specialize may be broken.

**Comment by gottesmm** [comment]
Debug source compat failed due to Jenkins error

**Comment by gottesmm** [comment]
preset=buildbot,tools=RA,stdlib=RD,test=non_executable
@swift-ci Please test with preset macOS

**Comment by gottesmm** [comment]
Testing non-executable macOS as well

**Comment by gottesmm** [comment]
@swift-ci test linux platform

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci asan test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci clean test linux platform

**Comment by gottesmm** [comment]
Linux failure is some sort of deserialization failure.

lgcc_s && :
03:25:13 swift-frontend: /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/swift/lib/Serialization/DeserializeSIL.cpp:1617: bool swift::SILDeserializer::readSILInstruction(swift::SILFunction *, swift::SILBuilder &, unsigned int, SmallVectorImpl<uint64_t> &): Assertion `g && "Can't deserialize global variable"' failed.
03:25:13 Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project and the crash backtrace.
03:25:13 Stack dump:
03:25:13 0.	Program arguments: /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/swift-linux-x86_64/bin/swift-frontend -frontend -merge-modules -emit-module Sources/FoundationXML/CMakeFiles/FoundationXML.dir/XMLDocument.swift.swiftmodule Sources/FoundationXML/CMakeFiles/FoundationXML.dir/XMLDTD.swift.swiftmodule Sources/FoundationXML/CMakeFiles/FoundationXML.dir/XMLDTDNode.swift.swiftmodule Sources/FoundationXML/CMakeFiles/FoundationXML.dir/XMLElement.swift.swiftmodule Sources/FoundationXML/CMakeFiles/FoundationXML.dir/XMLNode.swift.swiftmodule Sources/FoundationXML/CMakeFiles/FoundationXML.dir/XMLParser.swift.swiftmodule Sources/FoundationXML/CMakeFiles/FoundationXML.dir/CFAccess.swift.swiftmodule -parse-as-library -disable-diagnostic-passes -disable-sil-perf-optzns -target x86_64-unknown-linux-gnu -disable-objc-interop -I swift -I /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/libdispatch-linux-x86_64/src/swift/swift -I /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/libdispatch-linux-x86_64 -I /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/swift-corelibs-libdispatch -I /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/swift-corelibs-libdispatch/src -I /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/libdispatch-linux-x86_64/src -I /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/swift-corelibs-libdispatch/src/BlocksRuntime -module-cache-path /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/foundation-linux-x86_64/module-cache -module-link-name FoundationXML -O -D DEPLOYMENT_RUNTIME_SWIFT -D FoundationXML_EXPORTS -Xcc -F/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/foundation-linux-x86_64 -emit-module-doc-path swift/FoundationXML.swiftdoc -emit-module-source-info-path swift/FoundationXML.swiftsourceinfo -module-name FoundationXML -o swift/FoundationXML.swiftmodule
03:25:13 1.	Swift version 5.4-dev (LLVM 19b0c6e14bd16e1, Swift 5631bb6b91028c6)
03:25:13 2.	While evaluating request ASTLoweringRequest(Lowering AST to SIL for module FoundationXML)
03:25:13 3.	While deserializing SIL function "$sSa22_allocateUninitializedySayxG_SpyxGtSiFZ13FoundationXML7XMLNodeC7OptionsV_Tgq5"
03:25:13  #0 0x0000000005a6e243 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0x5a6e243)
03:25:13  #1 0x0000000005a6c350 llvm::sys::RunSignalHandlers() (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0x5a6c350)
03:25:13  #2 0x0000000005a6e5ca SignalHandler(int) (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0x5a6e5ca)
03:25:13  #3 0x00007f27d8add390 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11390)
03:25:13  #4 0x00007f27d765c438 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x35438)
03:25:13  #5 0x00007f27d765e03a abort (/lib/x86_64-linux-gnu/libc.so.6+0x3703a)
03:25:13  #6 0x00007f27d7654be7 (/lib/x86_64-linux-gnu/libc.so.6+0x2dbe7)
03:25:13  #7 0x00007f27d7654c92 (/lib/x86_64-linux-gnu/libc.so.6+0x2dc92)
03:25:13  #8 0x0000000001091e17 swift::SILDeserializer::readSILInstruction(swift::SILFunction*, swift::SILBuilder&, unsigned int, llvm::SmallVectorImpl<unsigned long>&) (/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/buildbot_linux/swift-linux-x86_64/bin/swift-frontend+0x1091e17)
03:25:13  #9 0x0000000001084a2f swift::SILDeseri

I am going to run a clean build to see if it is some weird state issue.

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
macOS failed due to a lifetime verifier false positive. I am testing with it locally. I am going to push once the benchmark posts. I peeked on the bots, the code-size is better at -O, -Osize showing that my simplify-cfg changes have helped (beyond making things compile quicker).

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
*sigh* I forgot that was fixed

**Comment by gottesmm** [comment]
@swift-ci clean test Linux platform

**Comment by gottesmm** [comment]
@swift-ci test windows platform

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
Compnerd says he cleaned the windows machine. Getting that green.

**Comment by gottesmm** [comment]
@swift-ci test windows platform

**Comment by gottesmm** [comment]
@swift-ci test windows platform

**Comment by gottesmm** [comment]
@swift-ci asan test

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
Turns out my change (on top of Meghana's change) hurt perf. So I removed it.

**Comment by gottesmm** [comment]
After a little bit of testing I am going to throw on Andys commit from this PR: https://github.com/apple/swift/pull/35937. Locally he mentioned these are the -O results for him:

```
IMPROVEMENT                OLD       NEW       DELTA   RATIO
libswiftCore.dylib         3932160   3833856   -2.5%   **1.03x**
libswiftFoundation.dylib   1343488   1310720   -2.4%   **1.02x**
REGRESSION                                                 OLD     NEW     DELTA     RATIO
ConvertFloatingPoint.MockFloat64Exactly2                   6       16      +166.6%   **0.38x**
NSStringConversion.Long                                    591     1445    +144.5%   **0.41x**
NSStringConversion.Medium                                  270     616     +128.1%   **0.44x**
NSStringConversion.MutableCopy.Long                        385     593     +54.0%    **0.65x**
NSStringConversion.UTF8                                    501     711     +41.9%    **0.70x**
NSStringConversion.MutableCopy.Medium                      475     643     +35.4%    **0.74x**
AngryPhonebook                                             259     350     +35.1%    **0.74x**
AngryPhonebook.ASCII2.Small                                119     160     +34.5%    **0.74x**
StringWordBuilderReservingCapacity                         1670    2230    +33.5%    **0.75x**
StringWordBuilder                                          1700    2260    +32.9%    **0.75x (?)**
NSStringConversion.Rebridge.LongUTF8                       37      47      +27.0%    **0.79x**
NSStringConversion.Rebridge.UTF8                           311     395     +27.0%    **0.79x**
RemoveWhereFilterString                                    205     260     +26.8%    **0.79x**
StrCat                                                     4372    5494    +25.7%    **0.80x**
Join                                                       155     194     +25.2%    **0.80x (?)**
ObjectiveCBridgeFromNSString                               835     1020    +22.2%    **0.82x**
StringUtilsUnderscoreCase                                  912     1107    +21.4%    **0.82x**
IMPROVEMENT                                                OLD     NEW     DELTA     RATIO
StringFromLongWholeSubstring                               3       2       -33.3%    **1.50x**
Breadcrumbs.CopyUTF16CodeUnits.ASCII                       22      15      -31.8%    **1.47x**
SumUsingReduceInto                                         88      64      -27.3%    **1.37x**
SumUsingReduce                                             88      64      -27.3%    **1.37x**
UTF8Decode_InitFromData                                    171     129     -24.6%    **1.33x**
UTF8Decode_InitFromBytes                                   178     135     -24.2%    **1.32x**
UTF8Decode_InitFromCustom_noncontiguous                    321     248     -22.7%    **1.29x**
UTF8Decode_InitDecoding                                    164     130     -20.7%    **1.26x**
LessSubstringSubstring                                     29      23      -20.7%    **1.26x**
EqualSubstringSubstring                                    29      23      -20.7%    **1.26x**
EqualSubstringString                                       29      23      -20.7%    **1.26x**
ArrayAppendRepeatCol                                       490     390     -20.4%    **1.26x (?)**
UTF8Decode_InitFromCustom_contiguous                       167     133     -20.4%    **1.26x**
ParseInt.UIntSmall.Binary                                  791     631     -20.2%    **1.25x**
EqualStringSubstring                                       30      24      -20.0%    **1.25x (?)**
EqualSubstringSubstringGenericEquatable                    30      24      -20.0%    **1.25x**
LessSubstringSubstringGenericComparable                    30      24      -20.0%    **1.25x**
Prims.NonStrongRef.UnmanagedUGR                            138     114     -17.4%    **1.21x (?)**
Prims.NonStrongRef.UnmanagedUGR.Closure                    138     114     -17.4%    **1.21x**
Prims.NonStrongRef.Unmanaged.Closure                       138     115     -16.7%    **1.20x**
Prims.NonStrongRef.Unmanaged                               138     115     -16.7%    **1.20x (?)**
```

**Comment by gottesmm** [comment]
I just pushed a small disable for a test I need to tweak the FileCheck lines for. I want to allow for the rest of the testing while I am figuring out why we are crashing when deserializing a global variable in foundation on linux.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
I am going to cherry-pick Andy's change into a different PR on top of this work and test it. The PR is #35942.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
I am talking with @xymus about the deserialization issue.

**Comment by gottesmm** [comment]
@swift-ci test macOS platform

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
windows test failure is being fixed by compnerd on another PR. Not from this PR.

**Comment by gottesmm** [comment]
Woot! Linux succeeded! Not surprised that it would though (I am not enabling this on Linux in this PR).

**Comment by gottesmm** [comment]
Funny story, I actually need to check in: https://github.com/apple/llvm-project/pull/2483

**Comment by gottesmm** [comment]
apple/llvm-project#2483

@swift-ci test macOS platform

**Comment by gottesmm** [comment]
@swift-ci test windows platform

**Comment by gottesmm** [comment]
... Erik merged something and created a merge conflict ... And the merge conflict was just an include line...

I am going to smoke test this in since I did a full test.

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Review by atrick — APPROVED** [review]
This looks identical to the one I reviewed:
https://github.com/apple/swift/pull/35958

**Comment by gottesmm** [comment]
It is identical except in the other one I tweaked the triple conditional to be isMacOS instead of this PR which is isDarwin.

**Comment by atrick** [comment]
@eeckstein The fix for the (String) Breadcrumbs benchmark regression is pending. rdar://74296355 (OSSA benchmark regression; Breadcrumbs.MutatedUTF16ToIdx 4x slower)

We also fixed the NSStringConversion regressions. It think it was Meghana's pipeline change.

Benchmark data with fixes:
https://github.com/apple/swift/pull/35942

I think there are still a few significant regressions at -Osize that don't show up at -O, so that's inlining related.

**Comment by atrick** [comment]
@gottesmm @meg-gupta 👏 👏 👏 So great to see this landing!

**Comment by drodriguez** [comment]
I am trying to find clues about some breakage in the Android ARMv7 CI from yesterday.

The test that broke is `SILOptimizer/dead_array_elim.swift`. The PR that started making it fail is #36118, which enables the test, which was disabled #35978. This PR landed while the test was disabled, and that's why I think it wasn't noticed until now. Before that, the test broke once before in a similar way in #35737, but was fixed in #35776 (/cc @eeckstein).

I tried bisecting the problem (carefully enabling the test) and I end up in the commits of #36025, which enables this for non-Darwin platforms. Then I tested again these changes and the test pass when `SerializeStdlibWithOwnershipWithOpts` is `false`, but not when it is `true`. Before these changes the test doesn't fail.

I tried comparing the previous solution in #35776 with the code introduced here, but I don't clearly see where the same solution might be possible (it might just be a red herring).

I was wondering if someone has any idea of what might be going wrong and if it can be fixed.

Thanks!

**Pull request merged**
