### PR TITLE
Add arm64_32 support for Swift

### LINKED ISSUE #56106: [SR-13709] Public Swift toolchains emit a warning on #if arch(arm64_32)
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13709      |
   |Radar             | rdar://problem/70080391         |
   |Original Reporter | @lorentey      |
   |Type              | Bug    |
   |Status            | Reopened        |
   |Resolution        |     |
        
<details>
  <summary>Environment</summary>

ubuntu:20.04 via Docker  
swift-5.3-RELEASE-ubuntu20.04

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | @stephentyrone      |
   |Priority          | Medium      |

   

   md5: db9c54368b283d82820693a3cd76e91a

  </details>

**Issue Description:**

The following code (from the swift-atomics package) emits a warning when compiled with the swift.org 5.3 toolchain for Ubuntu 20.04:

      @inline(__always)
      fileprivate static var _readersBitWidth: Int {
        #if arch(i386) || arch(arm) || arch(arm64_32)
        return 8
        #else
        return 16
        #endif
      }

    root@a7f9a25d4f88:/host/swift-atomics# swift build -Xcc -mcx16           
    /host/swift-atomics/Sources/Atomics/AtomicStrongReference.swift:77:41: warning: unknown architecture for build configuration 'arch'
        #if arch(i386) || arch(arm) || arch(arm64_32)
                                            ^
    /host/swift-atomics/Sources/Atomics/AtomicStrongReference.swift:77:41: note: did you mean 'arm64'?
        #if arch(i386) || arch(arm) || arch(arm64_32)
                                            ^~~~~~~~
                                            arm64
    [14/14] Merging module Atomics

Even though the public compiler doesn't currently support emitting code for arm64_32, it should at least admit that the architecture exists.

Packages that need to work on watchOS as well as swift.org releases ought0 to be able to compile their code without superfluous warnings.

### PR DESCRIPTION
**Pull request by CodaFi**
Commit the platform definition and build script work necessary to
cross-compile for arm64_32.

arm64_32 is a variant of AARCH64 that supports an ILP32 architecture.

Resolves #56106.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci please clean test macOS

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by stephentyrone** [comment]
Is this going to go onto 5.5? If not, we will want to land just the parse workaround there.

**Pull request merged**
