### PR TITLE
Bind layout type metadata correctly in outlined helper functions

### PR DESCRIPTION
**Pull request by rjmccall**
Fixes a regression in the source-compatibility suite.

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please test and merge.

**Comment by slavapestov** [comment]
@rjmccall This looks much cleaner, thanks!

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Comment by shahmishal** [comment]
@rjmccall Can you cherry-pick this on to swift-4.2-branch?

**Comment by rjmccall** [comment]
@shahmishal Yeah, I will be bringing that over as soon as it checks out here.

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Comment by shajrawi** [comment]
LGTM! Thanks John - much cleaner 👍

**Pull request merged**
