### PR TITLE
SILGen/ClangImporter: Handle async imports with a boolean error flag argument.

### PR DESCRIPTION
**Pull request by jckarter**
Import APIs with the `swift_async_error` attribute in `zero_argument` or `nonzero_argument`
modes by checking the corresponding boolean argument to indicate the error status, instead of
treating it as part of the result tuple. rdar://70594666

### CODE REVIEW

**Review by Narin4488 — APPROVED** [review]

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please clean test

**Review by DougGregor — APPROVED** [review]

**Comment by jckarter** [comment]
@swift-ci Please build toolchain

**Comment by jckarter** [comment]
@swift-ci Please test OS X

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by DougGregor** [comment]
@swift-ci please test Linux

**Pull request merged**
