### PR TITLE
Followup for #61505

### PR DESCRIPTION
**Pull request by meg-gupta**
#61505 had leftover places where begin_borrows were being created to pass a @guaranteed function argument as a phi operand. This PR gets rid of them. Because with @guaranteed forwarding phi support, no @guaranteed value needs additional borrow scope for being used as a phi operand.

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by atrick** [comment]
@meg-gupta did you mean to revert two commits in this PR?

On the verifier revert: Can we just verify that the operand of a `begin_borrow` is always a borrow introducer? If we do that, then we don't need the SILVerifier check for phis, which I didn't completely understand anyway.

What's going on with the ConditionVerifier revert?

**Comment by meg-gupta** [comment]
@atrick ConditionForwarding was turned off for @guaranteed function arguments, I reverted it, so they can be optimized too.

CopyPropagation needs to be fixed to clean up unnecessary begin_borrows after doing some @owned to @guaranteed transformation. I'll enable the verifier assert after that is fixed.

**Pull request merged**
