### PR TITLE
[5.1] Replace mapIntoContext with DWARF Archetype name lookup.

### PR DESCRIPTION
**Pull request by adrian-prantl**
This cherry-picks https://github.com/apple/swift/pull/22752 to the 5.1 branch.
rdar://problem/47798056

### CODE REVIEW

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-lldb/pull/1321
@swift-ci test

**Comment by slavapestov** [comment]
LGTM. Sorry for blowing up your qualification branch with merge conflicts :)

**Comment by adrian-prantl** [comment]
That was a SIL verification error; I don't think that could have been caused by this commit?

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-lldb/pull/1321
@swift-ci test

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-lldb/pull/1321
@swift-ci smoke test

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-lldb/pull/1321
@swift-ci test

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-lldb/pull/1321
@swift-ci smoke test

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-lldb/pull/1321
@swift-ci test platform linux

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-lldb/pull/1321
@swift-ci test

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-lldb/pull/1321
@swift-ci smoke test

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-lldb/pull/1321
@swift-ci smoke test

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-lldb/pull/1321
@swift-ci test

**Pull request merged**
