### PR TITLE
[Mangling/ABI] Mangle function names with parameter labels

### PR DESCRIPTION
**Pull request by xedin**
Instead of mangling parameter labels as part of the function type
move them to the end of the function name instead, to match the
language semantics.

Resolves: rdar://problem/34920390

### CODE REVIEW

**Comment by xedin** [comment]
@eeckstein Can you please take a quick look to see if I'm on the right track so far before I got fixing all of the tests?

**Comment by xedin** [comment]
Going to update the Mangling.rst separately at the end.

**Comment by eeckstein** [comment]
looks good so far

**Comment by eeckstein** [comment]
If you didn't do that already, can you check what the impact is on the stdlib symbol sizes?

**Comment by eeckstein** [comment]
LGTM!

**Comment by xedin** [comment]
@swift-ci please clean test

**Comment by xedin** [comment]
Looks like there is a conflict now in one of the tests, I'm going to resolve and re-run everything...

**Comment by xedin** [comment]
@swift-ci please clean test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
Ok, looks like compatibility suite is green, there are couple more failures tho, which I'm going to address momentarily.

**Comment by xedin** [comment]
@swift-ci please clean test

**Comment by xedin** [comment]
@swift-ci please clean test

**Comment by xedin** [comment]
@swift-ci please clean test

**Comment by xedin** [comment]
@swift-ci please clean test

**Comment by xedin** [comment]
@swift-ci please clean test macOS

**Comment by xedin** [comment]
@swift-ci please clean test Linux platform

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please clean test Linux

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
I've also ran lldb tests locally and they've succeeded. So if Linux and Compatibility Suite are green then I will merge everything in the morning so I can address any breakages during the day.

**Review by eeckstein — APPROVED** [review]
lgtm!

**Pull request merged**
