### PR TITLE
ppc64le custom presets.

### PR DESCRIPTION
**Pull request by asowani**
Contains custom build presets for ppc64le.

### CODE REVIEW

**Comment by asowani** [comment]
The build presets contained in this PR are required for building 4.2-branch on ppc64le CI. Can those be cherry-picked? Relevant discussion is at https://github.com/apple/swift/pull/16884

**Comment by airspeedswift** [comment]
Hi @asowani – sorry for the confusion. Let's get this PR reviewed, tested and landed on master (looks like some conflicts need resolving). Once that's done we can talk about whether it should be taken into the 4.2 branch, but please hold off on raising 4.2 PRs until after things are merged to master in general.

**Comment by asowani** [comment]
I have modified test/IRGen/clang_iniline_opt.swift to resolve the conflict. "-enable-objc-interop" got added to master after my PR, hence the conflict. Is it possible to merge this PR now? Thanks!

**Comment by shahmishal** [comment]
@asowani can you resolve the conflict?

```
<<<<<<< master
// UNSUPPORTED: CPU=powerpc64le
=======
>>>>>>> master
```

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
Rebased this.  Going to merge it in #28328

**Pull request closed without merging**
