### PR TITLE
[sourcekitd] Add test case for rdar://70017224

### PR DESCRIPTION
**Pull request by ahoppen**
rdar://70017224 ([SR-13658](https://bugs.swift.org/browse/SR-13658)) seems to be fixed. Add a test case for it.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Review by nathawes — APPROVED** [review]
LGTM - thanks!

**Comment by ahoppen** [comment]
@swift-ci Please smoke test Linux

**Comment by ahoppen** [comment]
@swift-ci Please smoke test Windows

**Pull request merged**
