### PR TITLE
Accept `borrowing` in pattern matches without underscore.

### PR DESCRIPTION
**Pull request by jckarter**
rdar://126305009

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
Please test with following pull request:
https://github.com/apple/swift-syntax/pull/2599

@swift-ci Please test

**Comment by jckarter** [comment]
Please test with following pull request:
https://github.com/apple/swift-syntax/pull/2599

@swift-ci Please test Linux

**Review by atrick — APPROVED** [review]
LGTM

**Pull request merged**
