### PR TITLE
[stdlib] BinaryInteger.Words needs to be a Collection

### PR DESCRIPTION
**Pull request by moiseev**
<rdar://problem/31736375>

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
@swift-ci Please smoke benchmark

**Comment by moiseev** [comment]
@swift-ci please smoke test compiler performance

**Comment by moiseev** [comment]
Need moar numbers!
@swift-ci Please test compiler performance

**Review by lorentey — APPROVED** [review]

**Comment by lorentey** [comment]
I wouldn't have expected this to affect runtime benchmarks at all; do you think these numbers are valid?

**Comment by moiseev** [comment]
@lorentey I'm not too worried about the benchmarks, it is most likely the artifact of "smoke benchmark", but the compile time regressions are something we can't have. ;-(

**Pull request closed without merging**
