### PR TITLE
[SIL] Don't drop a default when switching on a non-exhaustive enum

### PR DESCRIPTION
**Pull request by jrose-apple**
This was undoing the effects of #14724, which is supposed to guarantee trapping behavior on unexpected values. Worse, it put switches that *actually had defaults* back into undefined-behavior-land if a case were added.

~The verifier changes are in lieu of test changes;~ this was originally caught by IRGen/CoreGraphics_test.swift.

rdar://problem/42775178

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
preset=buildbot,tools=RA,stdlib=RDA
@swift-ci Please test with preset

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by jrose-apple** [comment]
@eeckstein This looks bigger than the original version, but it's still basically the same thing, and I think it's a bad enough problem to get into 4.2.

**Comment by jrose-apple** [comment]
Hmm. The source compat suite [failed Kitura in AllocStackToBox](https://ci.swift.org/job/swift-PR-source-compat-suite/1631/artifact/swift-source-compat-suite/FAIL_Kitura_4.0_BuildSwiftPackage.log), which is *not* one of the passes I changed. But the whole pipeline is stuck together, so…

**Review by eeckstein — APPROVED** [review]
lgtm!

**Comment by jrose-apple** [comment]
One more test fix (left in a `Builtin.Int64`).

@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by jrose-apple** [comment]
The source compat failure is happening on master too, so it shouldn't block this change.

**Pull request merged**
