### PR TITLE
[opt] Teach mem2reg about begin_access.

### PR DESCRIPTION
**Pull request by zoecarver**
Mem2reg can now follow, project, and remove being_access instructions. This will be particularly beneficial for #30810.

### CODE REVIEW

**Comment by zoecarver** [comment]
@swift-ci please benchmark.

**Comment by zoecarver** [comment]
I suspect that there won't be significant improvement because mem2reg only optimizes tuples and structs and those rarely have access markers around them or their members.

**Comment by zoecarver** [comment]
@swift-ci please benchmark

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Comment by zoecarver** [comment]
Now that #34276 has landed, I'm going to try benchmarking this again.

**Comment by zoecarver** [comment]
At some point, it would probably also be good to re-write the patch to use the `AccessPath` utility.

**Comment by zoecarver** [comment]
@swift-ci please benchmark.

**Comment by zoecarver** [comment]
@swift-ci please benchmark.

**Comment by eeckstein** [comment]
@zoecarver I'm wondering if mem2reg actually needs to handle access instructions. Wouldn't access marker elimination remove those markers anyway?
Did you see a swift code pattern where this change makes a difference?

**Comment by zoecarver** [comment]
I'm surprised to see such a large regression. I wonder what's causing that. 

> @zoecarver I'm wondering if mem2reg actually needs to handle access instructions. Wouldn't access marker elimination remove those markers anyway?
Did you see a swift code pattern where this change makes a difference?

Yes, marker elimination should remove these. I thought that happened later in the pass pipeline than it does. It looks like it happens in the high-level function pipeline, though, so that should be sufficient (which explains why there aren't performance gains here).

I was looking at [code patterns as simple as](https://swift.godbolt.org/z/9zKGse):
```
struct Foo { var x = 0 }

func test() -> Int {
    var f = Foo()
    f.x = 1
    return f.x
}
```

Because of how early the mem2reg pass runs in the pipeline, it looked like it was getting tripped up on the access markers.

**Pull request closed without merging**
