### PR TITLE
Support class extensions in objcImpl

### PR DESCRIPTION
**Pull request by beccadax**
Their requirements are now included when typechecking the main body extension.

Fixes rdar://118535473.

### CODE REVIEW

**Comment by beccadax** [comment]
@swift-ci please test

**Comment by beccadax** [comment]
@swift-ci please test

**Comment by beccadax** [comment]
@swift-ci please smoke test compiler performance

**Comment by beccadax** [comment]
@swift-ci please test Windows platform

**Comment by beccadax** [comment]
@tshortli Think you could give this a review?

**Review by tshortli — APPROVED** [review]

**Pull request merged**
