### PR TITLE
[NOMERGE] Make Sequence be a typealias for Collection

### PR DESCRIPTION
**Pull request by dabrahams**
# Work In Progress

See [this thread](https://forums.swift.org/t/pitch-make-collection-super-convenient-and-retire-sequence) for background.

## TODO

- [x] Make `DefaultIndex` into a `struct` that contains an enum.
- [x] Rename the compiler-known protocol `Sequence` to `_Sequence` and introduce `Sequence` typealias (induces SourceKit crashes, but https://github.com/dabrahams/swift/tree/ezCollection)
- [ ] Make the compiler-known protocol be `Collection`.

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please test

**Comment by dabrahams** [comment]
Filed <rdar://41143798> to track the compiler crash.

**Comment by natecook1000** [comment]
I think it's causing problems to make the `DefaultIndex<Self>` the actual default index for `Collection`. With the `DefaultIndex`-bound extension and having the iterator default to `IndexingIterator`, it means that this compiles but crashes on instantiation:

```swift
struct ThisIsFine: Collection {}
ThisIsFine()
```
results in:
```
Assertion failed: (entry.is<const TypeInfo*>() && "getting TypeInfo recursively!"), function getCompleteTypeInfo, file .../swift/lib/IRGen/GenType.cpp, line 1370.
...
1.	while processing REPL source:
struct ThisIsFine: Collection {}
ThisIsFine()
2.	While running pass #42 SILModuleTransform "LoadableByAddress".
3.	While converting type 'DefaultIndex<ThisIsFine>'
4.	While converting type '(Int, Slice<ThisIsFine>, IndexingIterator<ThisIsFine>)'
5.	While converting type 'Slice<ThisIsFine>'
```

**Comment by dabrahams** [comment]
Okay, do you want to report the compiler bug, then force-push a commit without that feature and see if it gets through all the tests?

**Comment by natecook1000** [comment]
Filed [SR-8005](https://bugs.swift.org/browse/SR-8005). Type inference is picking up the `DefaultIndex` extension even when that isn't the default index type, which means people conforming to `Collection` won't get any hints about what to implement. Okay for now, but unfortunate long term.

**Comment by natecook1000** [comment]
@dabrahams Okay to close this? Pretty far past the point where we could just make this change, so any refinement will need to take a different route…

**Pull request closed without merging**
