### PR TITLE
build: bump curl to 8.4.0 on Windows

### PR DESCRIPTION
**Pull request by compnerd**
Bump curl to address security issues in curl.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please clean test

**Review by shahmishal — APPROVED** [review]

**Comment by compnerd** [comment]
```
/home/build-user/swiftpm/Sources/PackageCollectionsSigning/CertificatePolicy.swift:405:56: error: cannot find type 'OCSPRequesterQueryResult' in scope
    func query(request: [UInt8], uri: String) async -> OCSPRequesterQueryResult {
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~
```

This seems odd to be broken on Linux when that should not be touched.  CC: @yim-lee

**Comment by yim-lee** [comment]
@compnerd The change was automerged from `main` to 5.10. We reverted it here: https://github.com/apple/swift-package-manager/pull/6988

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Pull request merged**
