### PR TITLE
Fix basic callee analysis to see noescape partial_applies.

### PR DESCRIPTION
**Pull request by atrick**
This in turn allows side-effect analysis to handle directly applied noescape
closures.

### CODE REVIEW

**Comment by atrick** [comment]
@eeckstein this is a small, obvious (I think) change.

**Comment by atrick** [comment]
@swift-ci test.

**Review by aschwaighofer — APPROVED** [review]
Thank you!

**Review by eeckstein — APPROVED** [review]
lgtm!

**Pull request merged**
