### PR TITLE
Fix a regression that caused the compiler to drop the path names of g… 

### PR DESCRIPTION
**Pull request by adrian-prantl**
…enerated

macro expansion source code when emitting DWARF 4 or earlier.

rdar://126688061

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci smoke test

**Review by augusto2112 — APPROVED** [review]

**Comment by adrian-prantl** [comment]
Windows paths!

**Comment by adrian-prantl** [comment]
@swift-ci smoke test

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test

**Pull request merged**
