### PR TITLE
[AST] NFC: Rename get*OrBoundGeneric* to be clearer and shorter

### PR DESCRIPTION
**Pull request by davezarzycki**
The get\*OrBoundGeneric\* methods are, in practice, simple getters that extract a Decl node. Let's rename the APIs accordingly and make them shorter at the same time. This is similar to the DeclContext changes made by Jordan Rose in: 537954fb9338951ce94dbe8549bbc7f0e2b1395f

- getNominalOrBoundGenericNominal -> getNominalDecl
- getStructOrBoundGenericStruct -> getStructDecl
- getClassOrBoundGenericClass -> getClassDecl
- getEnumOrBoundGenericEnum -> getEnumDecl

This is purely a mechanical change.

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by davezarzycki** [comment]
Oh, of course LLDB needs an update. How does one tell CI to test two pull requests together again?

**Comment by theblixguy** [comment]
@davezarzycki I think you can do it like this:

```
[apple/swift-lldb#<NUMBER>](https://github.com/apple/swift-lldb/pull/NUMBER)
@swift-ci Please smoke test
```

**Comment by jrose-apple** [comment]
Hm. The distinction between `getNominalDecl` and `getAnyNominal` is way too subtle at this point, but I don't know if we actually *care* about treating unbound generic types differently either. Maybe we can unify those. @DougGregor, @slavapestov, thoughts?

Stepping back, `getClassDecl` seems a little weird to me when we don't know that the Type is a class-related type at all yet, but I'll probably be able to live with that.

Suyash is correct about cross-repo testing, though GitHub will automatically link anything in the `org/repo#PRNUM` format, so you don't have to write the link yourself.

**Comment by jrose-apple** [comment]
P.S. I only bring up the `getAnyNominal` / `getNominalDecl` thing because it affects naming. Right now those names are too similar for my tastes; if we can just drop one of them then everything's fine, but if we want to keep both then I'm concerned about us not being consistent. (We're probably already not consistent.)

**Comment by davezarzycki** [comment]
Hi @jrose-apple – As it turns out, only two tests and one fixed compiler crasher regressions occur when all uses of `getNominalDecl` are replaced with `getAnyNominal`. This seems like the path to pursue. I'll try and break this into two commits. One mechanical search and replace, and then one that deals with the subtle difference between the two APIs (where unbound generic decls are ignored or not).

As a tangent, why did you drop the word "as" from the API names in 537954fb9338951ce94dbe8549bbc7f0e2b1395f? To me, `getExample` and `getAsExample` read very differently. The former retrieves a value, whereas the latter is a `dyn_cast` wrapper.

**Comment by davezarzycki** [comment]
https://github.com/apple/swift-lldb/pull/1324
@swift-ci please smoke test

@jrose-apple – I've addressed your concern. :-)

**Comment by davezarzycki** [comment]
https://github.com/apple/swift-lldb/pull/1324
@swift-ci please smoke test

**Comment by davezarzycki** [comment]
https://github.com/apple/swift-lldb/pull/1324
@swift-ci please test platform

**Comment by jrose-apple** [comment]
> As a tangent, why did you drop the word "as" from the API names in [537954f](https://github.com/apple/swift/commit/537954fb9338951ce94dbe8549bbc7f0e2b1395f)? To me, `getExample` and `getAsExample` read very differently. The former retrieves a value, whereas the latter is a `dyn_cast` wrapper.

Most of those are *not* `dyn_cast` wrappers, because they work on extensions too. That's why the "Self" is in the names. Maybe it should have been `getSelfTypeClassDecl` instead of just `getSelfClassDecl`, but (a) that's longer for not that much extra benefit, and (b) there was a `getAsTypeOrTypeExtensionContext` to rename, and that would have turned into `getSelfTypeTypeDecl`. `getAsDeclOrDeclExtensionContext` *did* go to `getAsDecl`.

I do still want someone else's opinion on whether the unbound thing is significant.

**Comment by slavapestov** [comment]
This sounds good. Ideally we would unify FooType and BoundGenericFooType though. There's no reason to have the distinction at all.

**Comment by davezarzycki** [comment]
> This sounds good. Ideally we would unify FooType and BoundGenericFooType though. There's no reason to have the distinction at all.

I think that unification is well beyond the scope of this pull request though.

**Comment by davezarzycki** [comment]
Poke. Might somebody review this? In particular, @jrose-apple has a concern about the subtle difference between `getAnyNominal` and `getNominalOrBoundGenericNominal` being lost. In practice, only one caller needed updating, but the concern is reasonable.

**Comment by davidungar** [comment]
As someone who is relatively new to this source base, I find that the longer method names help me learn the code. So, I would not favor this change, unless the current names are inaccurate.

**Comment by davezarzycki** [comment]
Hi @davidungar – I never cared much for the `getFooOrBoundGenericFoo`. To me, it either reads like it is returning a pointer union of `Foo` and `BoundGenericFoo` (which it does not), or it reads like "please return a Foo, and if necessary, do the work to bound up a generic one" (which is also not the case). If one doesn't mind a mouthful of an API name, then `getFooDeclIfFooTypeOrBoundGenericFooType` would be accurate.

**Comment by davezarzycki** [comment]
Ping? Any review would be nice. Thanks!

**Comment by davezarzycki** [comment]
@DougGregor, @rjmccall, @slavapestov, @jrose-apple – Ping.

I had hoped that the precedented clean up in 537954fb9338951ce94dbe8549bbc7f0e2b1395f by @jrose-apple would make this a simple thumbs up / thumbs down review. Should I just abandon this change? If so, then why?

**Comment by jrose-apple** [comment]
@slavapestov, was your response an actual "it's okay to unify `getNominalOrBoundGenericNominal` with `getAnyNominal`", or are you still waiting for someone else to confirm that?

(I think "the planned names here increase the chances of confusion in an already confusing space because of the existence of `getAnyNominal`; we should get rid of that first if possible" is a valid line of reasoning. But someone needs to confirm or deny that "possible".)

**Comment by davidungar** [comment]
@davezarzycki Sorry I didn't see your comment to me before! I like the longer names you suggested: such as `getFooDeclIfFooTypeOrBoundGenericFooType`, but I'm sure I'm in a minority here. Is there some deeper purpose to these functions that would yield an intension-revealing name?

**Comment by davezarzycki** [comment]
> @slavapestov, was your response an actual "it's okay to unify `getNominalOrBoundGenericNominal` with `getAnyNominal`", or are you still waiting for someone else to confirm that?

@jrose-apple – I was waiting for someone to click "reviewed".
 
> (I think "the planned names here increase the chances of confusion in an already confusing space because of the existence of `getAnyNominal`; we should get rid of that first if possible" is a valid line of reasoning. But someone needs to confirm or deny that "possible".)

Right. From the commit message and comments in this thread, I think I addressed this. Now both `getNominalOrBoundGenericNominal` and `getAnyNominal` are replaced with `getNominalTypeDecl`.

**Comment by davezarzycki** [comment]
@davidungar – I don't think there is any deep purpose to these methods. They're just convenience methods so that do one or two dynamic casts and then a "getDecl" call if the dynamic cast succeeds, therefore "getClassDecl" (etc) are reasonably apt names.

**Comment by davidungar** [comment]
@davezarzycki Thanks. OK, sigh... The name issue is probably a symptom of a potential clean-up in the architecture. Anyway, it looks like they can return null. 

How would you feel about a name ending in `IfAny`? It could maybe prevent a radar in the future. (I realize that DOxygen comments should also mention this fact, but a name is visible without an extra action.)

**Comment by davezarzycki** [comment]
Hi @davidungar – What problem does the `IfAny` suffix solve? Where is the precedent?

**Comment by jrose-apple** [comment]
> > @slavapestov, was your response an actual "it's okay to unify getNominalOrBoundGenericNominal with getAnyNominal", or are you still waiting for someone else to confirm that?

> @jrose-apple – I was waiting for someone to click "reviewed".

Sorry, this was a question for Slava, not you.

**Comment by davidungar** [comment]
@davezarzycki The "IfAny" suffix alerts the reader, or the user of the method that the result may be null. It's a poor man's substitute for those lovely optional types in Swift, which were one of the reasons I fell in love with Swift. We have llvm::Optional for values, but for pointers tend to follow the old way of just leaving the distinction between may-be-null and will-never-be-null implicit.

I would like it even more if we used llvm::Optional for pointer values which may be null. That would be even better. Swift incorporates many ideas which help make large programs more maintainable and this is one. I have noticed that our code base seems to be less accessible and more brittle (at least to me) than I would have hoped, and I believe that, now that the project is mature it is time to move the needle a bit in favor of maintainability and malleability. For example, I recently learned that we have four different implementations of name lookup, none of which is completely correct. I have also seen micro-optimizations that diffuse the invariants for little gain. In general--and I am as guilty of this as the next person--there seems to be too much "what" and not enough "why" in our code.

Folks who've grown up with llvm and the Swift compiler (as I assume you have) might have a hard time realizing what it is like to bring someone new onboard to the point where the newbie can confidently make changes and enhancements. But we need to be able to do that.  I like to think that because I am *not* familiar with the code base, but have other experience with fairly large systems and language implementations, I can offer a perspective that can be useful.

I like to think of the four-in-the-morning test: anything a language or IDE can do to help you keep being productive at 4 am is a good thing. Maybe that idea helps explain why I favor more informative, intention-revealing function names.

**Comment by gottesmm** [comment]
@davidungar There is such a thing: https://github.com/apple/swift/blob/master/include/swift/Basic/NullablePtr.h

**Comment by davezarzycki** [comment]
Hi @davidungar – I'm sympathetic your points, but as the author of this pull request I'm not looking to change Swift compiler conventions (which largely follow LLVM conventions, which largely follow C/C++ conventions). I just want shorter/clearer names, and I wouldn't have proposed anything if I hadn't seen @jrose-apple rename a bunch of wordy DeclContext APIs.

Also, I am more recently new to the swift compiler code than you might think, despite having joined the Swift project from its inception at Apple. (At the time, I focused on the runtime/stdlib bootstrap, management of a team, and I only dabbled in compiler source changes, often the lexer/parser.) As a C/assembly programmer without formal education, I also found many parts of LLVM/Swift source to be overwhelming — but that would be true of joining any large project and any education. To the credit of LLVM and derived projects like Swift, I think they make a valiant effort to be approachable given the complexity of the subject area. Nevertheless, learning the various subsystems and conventions of any large project simply takes time and there aren't any serious shortcuts (other than being able to walk down a hallway and ask a question directly from an expert).

In any case and as I wrote above, I'd like to limit the subject of this pull request to a simple, non-convention changing rename. Thanks for understanding.

**Comment by davidungar** [comment]
Thanks, @davezarzycki . Sorry I didn't see your response sooner; my email filtering is flawed. I understand your reluctance to (as I see it) improve the culture. (Others will surely disagree with me, anyway.)  Anyway, since I'm not a reviewer, I don't have to go on record one way or the other! There are a few "ifAny"s in the compiler already, probably all mine. Would love to sit down with you sometime over coffee and brainstorm ways to improve the accessibility of this code base. Good luck with this PR!

**Comment by davezarzycki** [comment]
Ping. Hi @slavapestov – I'm still waiting for your input and response to @jrose-apple's question here: https://github.com/apple/swift/pull/22853#issuecomment-473985059

**Comment by davidungar** [comment]
@gottesmm Thanks! I will be using NullablePtr.h as I move forward with my own code.

**Comment by davezarzycki** [comment]
Closing due to lack of the interest/responses by the reviewers.

**Pull request closed without merging**
