### PR TITLE
DO NOT MERGE: Disable static knowledge of graphemes.

### PR DESCRIPTION
**Pull request by milseman**
With the standard library now relying on ICU for grapheme breaking,
what is and is not a valid grapheme is unknowable at compilation time
as the supported Unicode version is supplied at run time. Rather than
give incorrect errors, or even downgrade to un-suppressable warnings,
all non-empty Strings are considered to potentially be graphemes.

Future directions could include warnings/errors for known stable
non-graphemes, multi-version grapheme breaking implementations coupled
with deployment-target checking, etc. In any case, we should be
careful to not give users the false impression that static checks
are sufficient/exhaustive.

This commit is meant to be minimally invasive. A subsequent commit
will more aggressively strip the compiler of grapheme knowledge.

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please benchmark

**Comment by milseman** [comment]
@rudkx can you review the `interpolation_segments.swift` changes and comment on whether more permissive grapheme logic might have unintended effects on the constraint system.

**Comment by milseman** [comment]
@jrose-apple or @rintaro, if you have any feedback as well that would be appreciated.

**Comment by rudkx** [comment]
I believe this could break source compatibility in at least one case I can think of:

```
func foo<T: ExpressibleByStringLiteral>(_ hi: T) {}
func foo<T: ExpressibleByExtendedGraphemeClusterLiteral>(_ hi: T) {}

foo("hi")
```

Will now select the second overload rather than the first.

**Comment by milseman** [comment]
@rudkx yeah, unfortunately that's inherent to having any static notion of what a grapheme is. Perhaps the long-term solution is to deprecate and remove ExpressibleByExtendedGraphemeClusterLiteral.

This PR has the effect of making all non-empty strings be ExpressibleByExtendedGraphemeClusterLiteral. Unfortunately, that sort of obviates the point of ExpressibleByStringLiteral. If we do the reverse, that is never form an ExpressibleByExtendedGraphemeClusterLiteral by taking grapheme breaking out of the compiler, then we end up with an API change (requiring se process) to deprecate the protocol and change Character to be ExpressibleByStringLiteral.

**Comment by milseman** [comment]
@dabrahams recommended an intermediary step of doing *some* stable grapheme breaking for the purposes of determining ExpressibleByExtendedGraphemeClusterLiteral vs ExpressibleByStringLiteral for Swift 4, and deferring the longer term solutions (e.g. removing ExpressibleByExtendedGraphemeClusterLiteral) until later. This keeps both protocols around and non-trivial.

**Comment by milseman** [comment]
I'm probably going to take a slightly different direction here, but want to keep this open for now.

**Pull request closed without merging**
