### PR TITLE
[DebuggingTheCompiler] Document a few flags for dumping llvm-ir.

### PR DESCRIPTION
**Pull request by gottesmm**
I needed to use these and realized they were not documented here. I had them in
my brain, but others may not, so seemed good to do.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by shahmishal** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Pull request merged**
