### PR TITLE
[test] enable prefix/suffix test for the native runtime

### PR DESCRIPTION
**Pull request by glessard**
un-skips the prefix/suffix test of String in the absence of ObjC, and verifies the matches without relying on an NSString method.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
Lost the failure

@swift-ci please smoke test macOS platform

**Comment by CodaFi** [comment]
@swift-ci please smoke test Linux platform

**Comment by lorentey** [comment]
This looks good to me, but cc @milseman for a second opinion.

**Comment by CodaFi** [comment]
Looks like we can’t quite un-XFAIL this test.

**Comment by milseman** [comment]
LGTM

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by CodaFi** [comment]
@swift-ci smoke test Linux

**Comment by CodaFi** [comment]
Huh, okay. Well, I guess we can't take this after all.

Thanks for your efforts here, but I believe we'll need a deeper change to get this to pass.

**Comment by glessard** [comment]
Sorry: I haven't been able to build on Linux lately, so I couldn't do anything about this PR.

**Pull request closed without merging**
