### PR TITLE
Use LLVM_READONLY instead of __attribute__((__pure__))

### PR DESCRIPTION
**Pull request by hughbe**
https://github.com/apple/swift-llvm/blob/e44c29ad5d92878e5d60b4bea39f4af6977846ef/include/llvm/Support/Compiler.h#L170

### CODE REVIEW

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by hughbe** [comment]
Seems like we can't import the LLVM file in shims - not sure why... investigating

**Comment by hughbe** [comment]
@jrose-apple I got errors (no such file "llvm/Support/Compiler.h"). I couldn't explain them, but I thought they were perhaps related to the fact that the shims don't include any LLVM paths... I tried including them and got some errors (module LLVMSupport requires feature cplusplus)

**Comment by jrose-apple** [comment]
SwiftShims get *installed,* they can't reference LLVM headers.

**Comment by hughbe** [comment]
> SwiftShims get installed, they can't reference LLVM headers.

Installed where? I understand they're being copied from code in the runtime. However, could it be a good idea to also copy Compiler.h (and llvm-config.h)

Might be overkill, but let me know what you think - could let us clean up some stuff in swiftShims

**Comment by jrose-apple** [comment]
Ah, elaborating: SwiftShims are headers needed to properly import the Swift standard library. As such, they should be standalone. Including llvm-config.h in particular would be incorrect, since that's configured for the host system rather than the target system, but even without that we need to be able to define a single, self-contained module that doesn't import anything else (or else we get circularity issues due to the Platform overlay).

**Comment by hughbe** [comment]
Got it, cheers

**Pull request closed without merging**
