### PR TITLE
IRGen: Fix Clang type conversion to map Swift.Bool to _Bool instead o…

### PR DESCRIPTION
**Pull request by slavapestov**
rdar://problem/26314060

### CODE REVIEW

**Comment by slavapestov** [comment]
Hi @jrose-apple, I haven't heard from @tkremenek if we want this in swift-3.0-preview-1-branch yet, but in case we do, mind reviewing this?

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
To clarify this change has no effect on Darwin platforms

**Comment by jrose-apple** [comment]
Yep, happy to take this, even if @rjmccall has ways to improve it later.

**Pull request merged**
