### PR TITLE
[Parse] Move SyntaxParsingContext to 'Parse'

### PR DESCRIPTION
**Pull request by rintaro**
`SyntaxParsingContext` is actually a part of `Parser`.
Moving this to `Parse` resolves a dependency problem where `libAST` and `libSyntax` used to depend on each other.

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please clean smoke test

**Review by nkcsgexi — APPROVED** [review]
LGTM.

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Pull request merged**
