### PR TITLE
Add a regression test for https://bugs.swift.org/browse/SR-15790

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test and merge

**Comment by philipturner** [comment]
@slavapestov since you mentioned Richard Wei in the old thread, could we continue our conversation about crash_6 here temporarily? That should prevent polluting the old thread.

**Comment by philipturner** [comment]
I just added the crash to my repository. It looks very similar to crash_2.swift. Given that they were on different toolchains, they might be the same one. However, their stack traces look nothing alike. @BradLarson said the following about crash_2 in JIRA:

> For your crash_2 case, I think that's another manifestation of SR-15666. If I'm interpreting that right, I think these are cases where the function really isn't differentiable, but a diagnostic to that effect is missing and thus the assertion failure. In the cases where I hit this, the code wouldn't work to begin with, so it hadn't been a high priority to fix. I just filed that reproducer because I had it on hand.

I can't fully tell whether this is the same as the bug mentioned in SR-15666 or even related to it. It also seems like there isn't anything directly related to AutoDiff in the stack trace for crash_6. Could you investigate this?

**Comment by philipturner** [comment]
Thanks for helping me out! I was worried that the AutoDiff bugs were intrinsically tied to RequirementMachine, and I would have to simultaneously patch AutoDiff and RequirementMachine. Now that I know they're all encapsulated within AutoDiff, there's less work to do.

**Comment by philipturner** [comment]
https://github.com/apple/swift/pull/40812

**Pull request merged**
