### PR TITLE
Fixing grammar in error messages.

### PR DESCRIPTION
**Pull request by cheshire**
"is obsoleted" is only used in context of "X is obsoleted by Y".
When used as a rough synonym of "deprecated" the proper grammar is "is
obsolete".

### CODE REVIEW

**Comment by AnnaZaks** [comment]
LGTM. 

+ Jordan

**Comment by cheshire** [comment]
@swift-ci please smoke test

**Comment by jrose-apple** [comment]
We do want the sense that something has changed though. I think a more direct fix would be "has been obsoleted", but it would be better to just rewrite the diagnostic to explain the correct thing to do. @huonw?

**Comment by huonw** [comment]
Maybe "deprecated" would be a way to sound more active and sidestep grammar issues with "obsolete"?

**Comment by dduan** [comment]
"has become obsolete"

**Comment by jrose-apple** [comment]
"deprecated" implies "but you can still use it for now" in the Xcode ecosystem, so it's not appropriate for a hard error.

"has become obsolete" is okay, but feels like the compiler isn't able to offer an authoritative word on it—as if someone *else* has made it obsolete.

I forgot there was a fix-it here, which makes the lack of explanation more acceptable. Still, how about something like "'where' clause must be written following the declaration's type", and not even mention the old way?

(@cheshire: no good deed goes unpunished!)

**Comment by cheshire** [comment]
@jrose-apple While I like your suggestion, I think it's also valuable to specify that this code was previously perfectly acceptable. Maybe combine the two?

```
'where' clause next to generic parameters is obsolete,
must be written following the declaration's type.
```

feels like the best option to me.

I personally don't see the issue with "obsolete": to me, if something is "obsolete" now, then necessarily was "not obsolete" some time ago.

**Comment by xwu** [comment]
Agree with @cheshire:

"Obsolete" has no grammatic issues and itself means that something has become disused. "Become obsolete" is a redundant redundancy that would mean, to break it down fully, "changed to be changed to be not continued to be commonly used."

Not mentioning the old way is fine, but I do think it's nice if the compiler acknowledges, "No, you're not crazy; this was once OK, but it's now no longer OK." And the fix-it, I would agree, makes the lack of explanation totally reasonable.

**Comment by cheshire** [comment]
@xwu The fixit does not seem very informative though (maybe that's a yet another bug!):

```
$ swiftc test/Sanitizers/witness_table_lookup.swift
witness_table_lookup.swift:32:16: error: 'where' clause next to generic parameters is obsoleted
struct A<T : Q where T : Q2> : P {
              ~^~~~~~~~~~~~
                                 where T : Q2
```

**Comment by xwu** [comment]
@cheshire What information is it missing?

**Comment by cheshire** [comment]
@xwu It does not tell me anything, and just exactly repeats the code already present in the source file.

**Comment by huonw** [comment]
That's how fixits are formatted on the command line: the new code is directly below where it should be inserted. (The automatic fixit interface in Xcode puts it in the right spot, too.)

**Comment by cheshire** [comment]
@swift-ci please smoke test

**Comment by cheshire** [comment]
@swift-ci Please smoke test Linux platform

**Pull request merged**
