### PR TITLE
[5.1] Bump compiler version to Swift 5.1

### PR DESCRIPTION
**Pull request by tkremenek**
Bump compiler version to 5.1

### CODE REVIEW

**Comment by tkremenek** [comment]
@swift-ci clean test

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by tkremenek** [comment]
@swift-ci clean test

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
Note, the tgmath.swift obsolescences haven't made it onto 5.1 branch.

**Pull request merged**
