### PR TITLE
[DNM] Cross repo for swift-markdown

### PR DESCRIPTION
**Pull request by Kyle-Ye**
Test PR for cross-repo testing apple/swift-markdown#50 and apple/swift-docc#295

### CODE REVIEW

**Comment by Kyle-Ye** [comment]
https://github.com/apple/swift-markdown/pull/50
https://github.com/apple/swift-docc/pull/295

@swift-ci please smoke test

**Comment by Kyle-Ye** [comment]
https://github.com/apple/swift-markdown/pull/50
https://github.com/apple/swift-docc/pull/295
@swift-ci please smoke test

**Comment by Kyle-Ye** [comment]
https://github.com/apple/swift-markdown/pull/50
https://github.com/apple/swift-docc/pull/295
@swift-ci please build toolchain

**Comment by Kyle-Ye** [comment]
https://github.com/apple/swift-markdown/pull/50
https://github.com/apple/swift-docc/pull/295
@swift-ci please test

**Comment by Kyle-Ye** [comment]
https://github.com/apple/swift-markdown/pull/50
https://github.com/apple/swift-docc/pull/295
@swift-ci please test

**Comment by franklinsch** [comment]
The macOS failure seems unrelated:

```
/Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/swift/test/SIL/Parser/moveonly_to_copyable.sil:11:17: error: CHECK-LABEL: expected string not found in input
// CHECK-LABEL: sil [ossa] @foo : $@convention(thin) (@owned Klass) -> @owned Klass {
```

Retriggering: 

https://github.com/apple/swift-markdown/pull/50
https://github.com/apple/swift-docc/pull/295
@swift-ci please test macOS Platform

**Comment by franklinsch** [comment]
The toolchain build failure seems unrelated. Since the tests pass, I'm considering this as working

**Pull request closed without merging**
