### PR TITLE
Make symbolicate-linux-fatal and test work with Python 3.

### PR DESCRIPTION
**Pull request by gmilos**
symbolicate-linux-fatal is fixed to work with Python 3 and the tests are improved to work in environments with multiple versions of Python installed.

### CODE REVIEW

**Comment by alblue** [comment]
@swift-ci please smoke test

**Comment by jrose-apple** [comment]
Does this also still work with Python 2?

**Comment by gmilos** [comment]
@jrose-apple It's meant to. I'm investigating the failure, it's not totally clear whether it's related to this change, but I need access to the workspace (unlikely) or local repo to verify.

For now, I'll ask @alblue to kick off one more set of tests to see if it was one-off.

**Comment by alblue** [comment]
@swift-ci please smoke test

**Comment by alblue** [comment]
@swift-ci please smoke test

**Comment by alblue** [comment]
@swift-ci Please clean smoke test Linux platform

**Comment by alblue** [comment]
@swift-ci please smoke test

**Comment by gmilos** [comment]
The latest test failure is due to unrelated issue:
`Assertion failed: (!V->hasBrokenDebugInfo() && "Module contains invalid debug info"), function doFinalization, file /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/llvm/lib/IR/Verifier.cpp, line 4535.`

**Comment by alblue** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
The IRVerifier issue is interesting.  I've been trying to chase that down, but I have a fix for it.  I'll try to get that committed to clang today.

**Comment by gmilos** [comment]
@jimingham Could you take a look at this patch, it's in the same ballpark as https://github.com/apple/swift/pull/7744

**Comment by shahmishal** [comment]
@jimingham and @gmilos What is the status of this PR?

**Comment by gmilos** [comment]
I'm not allowed to set the reviewer field. I set it to you @jimingham. If you're OK with the high level approach, I can rebase the patch to up-to-date master (and make sure it succeeds the checks).

**Comment by kevints** [comment]
@gmilos can you rebase this one?

**Comment by CodaFi** [comment]
@kevints If you wish to take up this patch, you can rebase it yourself and resubmit it.

**Comment by CodaFi** [comment]
It's been a year.  @gmilos, I'm going to close this, but it seems like the changes may still be necessary.  Could you either rebase this pull request and reopen it or send us another pull request?

**Pull request closed without merging**
