### PR TITLE
Circular validation cleanups, part 1

### PR DESCRIPTION
**Pull request by slavapestov**
I'm chipping away at validateDecl() cycles, so that we can have validateDecl() diagnose instead of silently returning if the declaration is already being validated. This PR has some preliminary cleanups.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility Debug

**Review by CodaFi — APPROVED** [review]
LGTM

**Pull request merged**
