### PR TITLE
[SILGen] Emit unreachable code diagnostic for single expression closures with implicit returns too

### PR DESCRIPTION
**Pull request by theblixguy**
We don't emit unreachable code diagnostic for single expression closures if it has an implicit return. For example:

```swift
func map<T>(_ block: (Never) -> T) {}
map { _ in return 5 } // warning: will never be executed
map { _ in 5 } // no warning
```

This is because we skip implicit statements in SILGen if we encounter an unreachable location.

For implicit return statements in single expression closure or functions, the result expression is not implicit. So, let's use this knowledge to prevent skipping over the return statement.

---

Resolves SR-13432

### CODE REVIEW

**Comment by theblixguy** [comment]
@swift-ci please smoke test

**Comment by theblixguy** [comment]
@swift-ci please smoke test

**Comment by theblixguy** [comment]
@swift-ci please smoke test

**Comment by theblixguy** [comment]
@swift-ci please smoke test

**Comment by theblixguy** [comment]
@swift-ci please smoke test macOS

**Comment by theblixguy** [comment]
Ping. @slavapestov @jckarter can you review? thanks!

**Comment by theblixguy** [comment]
Ping.

**Comment by theblixguy** [comment]
Ping.

**Review by jckarter — APPROVED** [review]
Looks reasonable to me.

**Comment by theblixguy** [comment]
@swift-ci please smoke test

**Pull request merged**
