### PR TITLE
[Concurrency] Fix some typos in PartialAsyncTask

### PR DESCRIPTION
**Pull request by Jager-yoo**
Hi, I fixed some typos in `Concurrency/PartialAsyncTask.swift`.
Please check out the changes. Thank you for reviewing in advance.
cc. @amartini51

### CODE REVIEW

**Review by amartini51 — APPROVED** [review]
These changes look reasonable to me — thanks!

**Comment by amartini51** [comment]
@swift-ci Please smoke test.

**Comment by amartini51** [comment]
@ktoso Can you please take a quick review and merge?

**Review by ktoso — APPROVED** [review]
LGTM, thanks! We can't merge during the holiday (thanks giving week in the US) but just after let's do so

**Pull request merged**
