### PR TITLE
[5.0] Fold "canonical" thunks into reabstraction thunks

### PR DESCRIPTION
**Pull request by rjmccall**
This is necessary because the callee of a currying thunk does not necessarily match the abstraction pattern of the function actually being curried, e.g. due to concrete overrides of methods of generic classes.

This is possible because we can easily derive the abstraction patterns from the appropriate `SILDeclRefs` and feed that into the reabstraction logic.

Fixes rdar://45671537 and [SR-4425](https://bugs.swift.org/browse/SR-4425).

This is the 5.0 version of #21932.  It is not ABI-affecting.

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Comment by rjmccall** [comment]
@swift-ci Please test source compatibility

**Review by slavapestov — APPROVED** [review]

**Comment by AnnaZaks** [comment]
Since this is not a new regression, I'd rather hold this for the future release.

**Comment by rjmccall** [comment]
Okay, I can accept that.  I'll leave it open just in case.

**Comment by tkremenek** [comment]
Let's please close 5.0 PRs that we aren't being considered at this point.  It is easy to file new PRs.

**Pull request closed without merging**
