### PR TITLE
SILGen: Caller-side codegen for invoking foreign async functions

### PR DESCRIPTION
**Pull request by jckarter**
Immediately before invoking the ObjC API, get the current continuation, capture it into a block to
pass as the completion handler, and then await the continuation, whose resume/error successors
serve as the semantic return/throw result of the call. This should complete the caller-side part
of SILGen; the completion handler block implementation is however still only a stub.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Review by DougGregor — APPROVED** [review]
Looks like a great start!

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Review by DougGregor — APPROVED** [review]

**Comment by jckarter** [comment]
@swift-ci Please test

**Review by DougGregor — APPROVED** [review]
Nifty!

**Comment by jckarter** [comment]
@swift-ci Please test Linux

**Pull request merged**
