### PR TITLE
[libSyntax] Parse ReturnStmt Syntax nodes

### PR DESCRIPTION
**Pull request by harlanhaskins**
This patch adds libSyntax parsing for `ReturnStmtSyntax` nodes.

### CODE REVIEW

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test

**Review by nkcsgexi — APPROVED** [review]
Glad to see some help here!

**Comment by harlanhaskins** [comment]
Glad to see such awesome abstractions!

**Comment by harlanhaskins** [comment]
Build failure seems unrelated.

@swift-ci please smoke test and merge

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
