### PR TITLE
[5.9][IRGen] Reject enums with inaccessible tpye metadata in layout string…

### PR DESCRIPTION
**Pull request by drexin**
… generation

Cherry-picked from: https://github.com/apple/swift/pull/65016

rdar://107679697

Because we are currently handling most enums in layout strings by going through the metadata, we have to ensure that the metadata is accessible from the current module and reject the enum otherwise.

### CODE REVIEW

**Comment by drexin** [comment]
@swift-ci test

**Comment by drexin** [comment]
@swift-ci test

**Comment by drexin** [comment]
@swift-ci test

**Comment by drexin** [comment]
@tbkka The PR to main was reviewed and approved by @aschwaighofer. Would you mind approving this?

**Review by tbkka — APPROVED** [review]

**Pull request merged**
