### PR TITLE
[Diagnostics] Introduce -suppress-warnings and -warnings-as-errors flags

### PR DESCRIPTION
**Pull request by milseman**
This PR introduces two new flags, "-suppress-warnings" and "-warnings-as-errors" that causes Swift to ignore warnings and treat warnings as errors, respectively. 

It includes some gardening, in that I remove the CATEGORY field from diagnostics that was both unused and generally deemed useless. I also generalize (and document) the determining of what action to take on a diagnostic, with the aim that this will be a useful foundation to build upon in the future if we ever want real categories, tags, pragma-like blocks, etc.

### CODE REVIEW

**Comment by gribozavr** [comment]
Thank you!  I wanted warnings-as-errors for standard library tests for a long time!

**Comment by milseman** [comment]
What if someone invokes Swift with "-frontend"? Or, should I check and error out in each?

**Comment by jrose-apple** [comment]
Invoking -frontend manually is unsupported; it's for testing purposes only. (It's equivalent to invoking -cc1 directly.)

I mean, it's fine to diagnose it, but it's also fine to just assert. I guess "one of them silently wins" isn't such a happy option.

**Comment by milseman** [comment]
Alright, I put it in the driver proper. Inside of swift -frontend, it will assert. Thanks for the feedback!

**Comment by jrose-apple** [comment]
Looks good! Feel free to merge after rebasing.

**Comment by milseman** [comment]
Rebased (squashing last commit) and merged. Will approve when my local tests pass.

**Pull request merged**
