### PR TITLE
[5.1] SR-10294: convertBoolToDarwinBool and friends should be inlined

### PR DESCRIPTION
**Pull request by Catfish-Man**
Cherry pick

### CODE REVIEW

**Comment by Catfish-Man** [comment]
Jordan feel free to ignore, just wanted to make sure you were on this since it includes your test fix

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Comment by Catfish-Man** [comment]
Original PR: https://github.com/apple/swift/pull/23802

**Review by airspeedswift — APPROVED** [review]

**Comment by Catfish-Man** [comment]
@swift-ci please test osx platform

**Comment by Catfish-Man** [comment]
Sigh, test results disappeared before I got back to this. Once more with feeling!

**Comment by Catfish-Man** [comment]
@swift-ci please test osx platform

**Comment by Catfish-Man** [comment]
@swift-ci please test osx platform

**Comment by Catfish-Man** [comment]
Not sure why that's not working

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Comment by Catfish-Man** [comment]
Ah, looks like the fix that this requires wasn't cherry-picked to 5.1. I think I'm ok with leaving this one out.

**Pull request closed without merging**
