### PR TITLE
Revert "[SE-0368] StaticBigInt"

### PR DESCRIPTION
**Pull request by etcwilde**
Reverts apple/swift#40722

This caused the minimal toolchain build to fail: https://ci.swift.org/job/oss-swift-test-stdlib-with-toolchain-minimaln//3006

### CODE REVIEW

**Comment by etcwilde** [comment]
@swift-ci please smoke test

**Review by benrimmington — APPROVED** [review]
I don't understand the failure. Should files using the new builtins have `#if compiler(>=5.8)` guards?

**Comment by glessard** [comment]
A thought (and shot in the dark): the minimal toolchain does not have any of the 128-bit types. I had a failure on the minimal toolchain bot when I included a test of a SIMD type for `loadUnaligned()`.

**Comment by etcwilde** [comment]
It's affecting the non-minimal standard library build too: https://ci.swift.org/job/oss-swift-test-stdlib-with-toolchain//3006

**Comment by rjmccall** [comment]
@benrimmington This is actually an instance of a general problem that we've come to call "condfails", and it does need to be fixed.  Basically, it's important that we tolerate at least a little bit of version slop to allow old compilers to work with new SDKs.  You don't have to make the functions actually *work* with the old compiler — it's not usually possible — but you do need to allow the module to *compile*.  Generally you do this with `#if compiler`; [here's an example](https://github.com/apple/swift/blob/a7726f19aa07b46e8cfa490980440cff4511f85a/stdlib/public/Concurrency/Executor.swift#L62).

**Pull request closed without merging**
