### PR TITLE
Harden `isKindOfClass:` check

### PR DESCRIPTION
**Pull request by tbkka**
We've seen some Obj-C NSProxy subclass implementations that are broken and will
crash if you send them a standard `isKindOfClass:` message.  This came out because
the casting machinery is now more aggressive about trying different casting options which
means some of these broken objects are being queried in new ways.

This adds an additional check before calling `isKindOfClass:` to verify that
this object is not using the default NSProxy selector routing.  If it is,
we just assume it's not whatever class is being tested for since we cannot
do anything better.

Resolves rdar://73799124

### CODE REVIEW

**Comment by tbkka** [comment]
@swift-ci Please test

**Comment by tbkka** [comment]
@swift-ci Please test

**Comment by tbkka** [comment]
For the record:  This is really all @mikeash work; he told me what to write, fixed it when I screwed it up anyway, and tested it for me.

**Comment by mikeash** [comment]
I did the fun bits, you did the annoying part of actually turning the thoughts into stuff that will compile.

**Comment by tbkka** [comment]
@swift-ci Please test macOS Platform

**Comment by tbkka** [comment]
@swift-ci Please test Linux Platform

**Comment by tbkka** [comment]
@swift-ci Please test Windows Platform

**Comment by tbkka** [comment]
@swift-ci Please test

**Pull request merged**
