### PR TITLE
[5.6] move function upstreaming

### PR DESCRIPTION
**Pull request by gottesmm**
Just upstreaming move function changes that I made on main.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
Windows failure is a SourceKit test that is unrelated.

**Comment by gottesmm** [comment]
macOS failed due to libswift @eeckstein

**Comment by gottesmm** [comment]
@swift-ci test macOS platform

**Comment by gottesmm** [comment]
@swift-ci test macOS platform

**Review by atrick — APPROVED** [review]
I scanned through these commits. They are all 5.6 worthy.

**Pull request merged**
