### PR TITLE
[String] Speed up UTF-8 initialization from non-stdlib types

### PR DESCRIPTION
**Pull request by milseman**
Avoid generic code paths if initializing for UTF-8 (the vast majority
of the time) from a non-stdlib type (such as Data).

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please benchmark

**Comment by milseman** [comment]
@swift-ci please benchmark

**Comment by milseman** [comment]
@Catfish-Man this might interest you

**Comment by Catfish-Man** [comment]
Very cool!

**Comment by karwa** [comment]
Alternatively, we could add `withContiguousBytesIfAvailable` on `Sequence` (perhaps underscored for now, like `_copyToContiguousArray`). 

That's better than `_HasContiguousBytes`, because `Data` could implement it. Basically like https://github.com/apple/swift/pull/22028, but without the changing the internal String functions to remove the `assumingMemoryBound`.

But so long as we're using `_HasContiguousBytes`, I'll just point out that we could add a conditional conformance to `Slice`, so `Slice<UnsafeRawBufferPoiner>` can use that fast-path too.

**Comment by milseman** [comment]
Yes, we will want to switch to a `withContiguousBytesIfAvailable` when we have that in lieu of `_HasContiguousBytes`. Even for collections which do not answer that, though, making the Array ahead of time is much much faster. So I view this as being a code path that will persist, while the `_HasContiguousBytes` will be replaced with `withContiguousBytesIfAvailable`.

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please benchmark

**Comment by milseman** [comment]
(locally, I see the newly added benchmarks being around 4X faster with this change).

**Pull request merged**
