### PR TITLE
[IDE] Scrub SwiftIDE of References to getInput()

### PR DESCRIPTION
**Pull request by CodaFi**
Does what it says on the tin.  Unblocked a bit of refactoring and flushed some dead code in the process.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
Missed the API digester tests locally

@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
Could we avoid changing the index dumped from the api-digester? We need to teach the migrator part to incorporate such change.

**Comment by CodaFi** [comment]
@nkcsgexi Had a chat with @nathawes about this.  I'm pulling the API digester changes into a separate patch.

**Comment by nkcsgexi** [comment]
@CodaFi thank you!

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test and merge

**Comment by CodaFi** [comment]
@swift-ci please smoke test Linux platform

**Comment by CodaFi** [comment]
⛵️

**Pull request merged**
