### PR TITLE
Finish removing finalizeDecl()

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Review by DougGregor — APPROVED** [review]
w00t!

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test compiler performance

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Pull request merged**
