### PR TITLE
Preliminary support for function builders

### PR DESCRIPTION
**Pull request by rjmccall**
Provide basic support for function builders, which allow the convenient creation of eDSLs for complex lists and hierarchies.

An evolution pitch for this is forthcoming.  That pitch proposes a somewhat more general feature than is implemented here; this work reflects what's available in the current Xcode developer preview.

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci build toolchain

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci build toolchain

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Comment by rjmccall** [comment]
@DougGregor Thanks for fixing the build!  Unfortunately I didn't notice that you did this until after I clobbered it with my own fix. 😃

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Comment by rjmccall** [comment]
We are planning to merge this now in order to simplify progressive development on top of it, since (1) the core team is in basic agreement that we should add this feature in some form and (2) it's a rather large patch and requires constant attention to keep valid.  We still anticipate significant changes to the design.  I'll be making a similar announcement in the pitch thread.

**Pull request merged**
