### PR TITLE
[WIP][stdlib] Array & friends: Add more _read/_modify accessors

### PR DESCRIPTION
**Pull request by lorentey**
Replace getters with _read accessors in `Array.subscript` & `ContiguousArray.subscript`.
Review array buffer subscripting and add _read/_modify where appropriate.

### CODE REVIEW

**Comment by lorentey** [comment]
I expect this will break all sorts of Array optimization tests, but I want to see a benchmark before changing anything.

@swift-ci benchmark

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci benchmark

**Comment by lorentey** [comment]
@swift-ci benchmark

**Comment by lorentey** [comment]
@swift-ci benchmark

**Comment by lorentey** [comment]
@swift-ci benchmark

**Comment by lorentey** [comment]
@swift-ci test macOS platform

**Comment by lorentey** [comment]
@swift-ci test macOS platform

**Comment by lorentey** [comment]
Well, that's not great.

**Comment by lorentey** [comment]
ArraySlice.subscript.read doesn't get inlined, while subscript.get does.

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Comment by lorentey** [comment]
Closing.

**Pull request closed without merging**
