### PR TITLE
Parse typecheck flag

### PR DESCRIPTION
**Pull request by bitjammer**
Rename the -parse flag to -typecheck

A parse-only option is needed for parse performance tracking and the
current option also includes semantic analysis.

Add back the -parse flag, which doesn't typecheck

### CODE REVIEW

**Comment by bitjammer** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
Looks good to me; the conflicts are caused by those tests moving to compiler_crashers_fixed.

**Comment by bitjammer** [comment]
Thanks!

@swift-ci Please smoke test

**Comment by bitjammer** [comment]
@swift-ci Please smoke test

**Comment by bitjammer** [comment]
Looks like a git error. Trying again.

**Comment by bitjammer** [comment]
@swift-ci Please smoke test

**Comment by bitjammer** [comment]
Git still failing. I'll try again later.

**Comment by bitjammer** [comment]
@swift-ci Please smoke test

**Pull request merged**
