### PR TITLE
[Swift 5.6 compat] use compat threading library

### PR DESCRIPTION
**Pull request by etcwilde**
Use the compatibility threading library instead of linking against the normal threading library. The normal threading library target doesn't exist yet.

rdar://99646957

### CODE REVIEW

**Comment by etcwilde** [comment]
@swift-ci please test

**Review by artemcm — APPROVED** [review]

**Review by al45tair — APPROVED** [review]
Not sure why it wasn’t already using the compatibility version.

**Comment by etcwilde** [comment]
> Not sure why it wasn’t already using the compatibility version.

I think it's because you landed those changes between when I wrote that part of the 5.6 compat libs and when landed the PR.

**Comment by etcwilde** [comment]
The windows failure is due to the missing link dependency between swiftAST and swiftBasic added in https://github.com/apple/swift/pull/61001.
Merging.

**Pull request merged**
