### PR TITLE
SIL: Clean up ownership handling in `createAsyncTask` builtins.

### PR DESCRIPTION
**Pull request by jckarter**
The underlying runtime functions really want to be able to consume the closure being used
to spawn the task, but the implementation was trying to hide this by introducing a retain
at IRGen time, which is not very ARC-optimizer-friendly. Correctly model the builtin operands
as consumed so that the ownership verifier allows them to be taken +1. Also fix a leak here
by making the builtins lower their function argument as `@callee_owned`; since the runtime
entry points work by setting up the closure's entry point as the initial entry point of the task,
with the context passed in like an argument, nobody else but the closure's own implementation
can really be responsible for releasing that closure context when it's done.

rdar://74973364

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Review by DougGregor — APPROVED** [review]
Looks great, thank you!

**Comment by jckarter** [comment]
@aschwaighofer noted that the partial application forwarder codegen the first take on this might be broken, and probably isn't great for code size in general. I've reworked the non-`_f` variants of `swift_task_create` to accept closure values as-is (since the older forms were unused) and unpack the invocation function and initial context on the callee side so IRGen doesn't need to splat out that logic at every use site. When creating a task with a closure context, we now also set up the task's return address to transfer control to a `completeTask` variant that releases the context for us, fixing the leak without requiring a thunk on the closure itself. @aschwaighofer how does this approach look?

**Comment by jckarter** [comment]
@swift-ci Please test

**Review by aschwaighofer — APPROVED** [review]
LGTM

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test Apple Silicon macOS Platform

**Review by ktoso — APPROVED** [review]
LGTM, the specific impl details a bit above my head but the described behavior and changes make sense :-)

**Pull request merged**
