### PR TITLE
SILCombine: handle upcasts when converting from alloc_ref_dynamic to alloc_ref

### PR DESCRIPTION
**Pull request by eeckstein**

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci Please smoke test and merge

**Review by gottesmm — CHANGES_REQUESTED** [review]
Can you improve the commit message with what was missing here and what prompted the change here? (Is there a radar?)

**Comment by gottesmm** [comment]
(btw, the only reason I requested the changes was to stop the merge from the smoke test.)

**Review by gottesmm — APPROVED** [review]

**Comment by gottesmm** [comment]
Looks great Erik!

**Comment by eeckstein** [comment]
@swift-ci Please smoke test and merge

**Pull request merged**
