### PR TITLE
[Backtracing] Security improvements.

### PR DESCRIPTION
**Pull request by al45tair**
Use `task_read_for_pid()` rather than having the crashing program pass its own task port through.  This opts us in to additional OS security measures surrounding the use of this call.

rdar://107362003

### CODE REVIEW

**Comment by al45tair** [comment]
This is a cherry pick of #65066.

**Comment by al45tair** [comment]
@swift-ci Please test

**Review by mikeash — APPROVED** [review]

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
@swift-ci Please test

**Review by tbkka — APPROVED** [review]

**Pull request merged**
