### PR TITLE
Adding fs::convertFDToNativeFile conversion to FileSystem.cpp.

### PR DESCRIPTION
**Pull request by plotfi**

### CODE REVIEW

**Comment by compnerd** [comment]
This seems like a functional change, the parameter is now different, so, the behaviour is going to be different.

**Comment by compnerd** [comment]
CC: @jrose-apple

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by jrose-apple** [comment]
Can you explain what `convertFDToNativeFile` does?

**Comment by jrose-apple** [comment]
…Okay, I looked at the docs for `convertFDToNativeFile` and this looks like it should be fine.

**Comment by jrose-apple** [comment]
@shahmishal "Python 2.7 or later is required" again?

**Comment by plotfi** [comment]
@jrose-apple This seems to have been broken since last week. We are going to look into something to change in build script to set the python correctly.

**Comment by plotfi** [comment]
Alright, waiting on PR26169. This should fix the infra fails.

**Comment by compnerd** [comment]
Okay, I've fixed the python issue, libdispatch has been fixed by @pschuh and I.  There are additional changes needed for lldb, but, this brings swift to a point where it can build again at least.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Linux:
```
14:51:52 FAILED: bin/lldb-server 
14:51:52 : && /usr/bin/clang++   -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -w -fdiagnostics-color -ffunction-sections -fdata-sections -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-strict-aliasing -Wno-deprecated-register -Wno-vla-extension -O3  -Wl,-rpath-link,/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/lldb-linux-x86_64/./lib  -Wl,-O3 -Wl,--gc-sections tools/lldb-server/CMakeFiles/lldb-server.dir/Acceptor.cpp.o tools/lldb-server/CMakeFiles/lldb-server.dir/lldb-gdbserver.cpp.o tools/lldb-server/CMakeFiles/lldb-server.dir/lldb-platform.cpp.o tools/lldb-server/CMakeFiles/lldb-server.dir/lldb-server.cpp.o tools/lldb-server/CMakeFiles/lldb-server.dir/LLDBServerUtilities.cpp.o tools/lldb-server/CMakeFiles/lldb-server.dir/SystemInitializerLLGS.cpp.o  -o bin/lldb-server  /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMSupport.a -lpthread lib/liblldbBase.a lib/liblldbHost.a lib/liblldbInitialization.a lib/liblldbPluginProcessLinux.a lib/liblldbPluginObjectFileELF.a lib/liblldbPluginInstructionARM.a lib/liblldbPluginInstructionMIPS.a lib/liblldbPluginInstructionMIPS64.a lib/liblldbPluginProcessGDBRemote.a lib/liblldbPluginProcessPOSIX.a lib/liblldbCore.a lib/liblldbSymbol.a lib/liblldbTarget.a lib/liblldbPluginProcessUtility.a lib/liblldbInterpreter.a lib/liblldbBreakpoint.a lib/liblldbDataFormatters.a lib/liblldbExpression.a lib/liblldbPluginCPlusPlusLanguage.a lib/liblldbPluginObjCLanguage.a lib/liblldbPluginPlatformMacOSX.a lib/liblldbPluginExpressionParserClang.a lib/liblldbPluginExpressionParserSwift.a lib/liblldbPluginSymbolFileDWARF.a lib/liblldbPluginSymbolFilePDB.a lib/liblldbPluginObjCRuntime.a lib/liblldbPluginSwiftLanguage.a lib/liblldbCommands.a lib/liblldbPluginObjectFileJIT.a lib/liblldbPluginClangCommon.a lib/liblldbPluginCPPRuntime.a lib/liblldbPluginAppleObjCRuntime.a lib/liblldbPluginPlatformPOSIX.a lib/liblldbPluginSymbolFileNativePDB.a lib/liblldbCore.a lib/liblldbSymbol.a lib/liblldbTarget.a lib/liblldbPluginProcessUtility.a lib/liblldbInterpreter.a lib/liblldbBreakpoint.a lib/liblldbDataFormatters.a lib/liblldbExpression.a lib/liblldbPluginCPlusPlusLanguage.a lib/liblldbPluginObjCLanguage.a lib/liblldbPluginPlatformMacOSX.a lib/liblldbPluginExpressionParserClang.a lib/liblldbPluginExpressionParserSwift.a lib/liblldbPluginSymbolFileDWARF.a lib/liblldbPluginSymbolFilePDB.a lib/liblldbPluginObjCRuntime.a lib/liblldbPluginSwiftLanguage.a lib/liblldbCommands.a lib/liblldbPluginObjectFileJIT.a lib/liblldbPluginClangCommon.a lib/liblldbPluginCPPRuntime.a lib/liblldbPluginAppleObjCRuntime.a lib/liblldbPluginPlatformPOSIX.a lib/liblldbPluginSymbolFileNativePDB.a lib/liblldbCore.a lib/liblldbSymbol.a lib/liblldbTarget.a lib/liblldbPluginProcessUtility.a lib/liblldbInterpreter.a lib/liblldbBreakpoint.a lib/liblldbDataFormatters.a lib/liblldbExpression.a lib/liblldbPluginCPlusPlusLanguage.a lib/liblldbPluginObjCLanguage.a lib/liblldbPluginPlatformMacOSX.a lib/liblldbPluginExpressionParserClang.a lib/liblldbPluginExpressionParserSwift.a lib/liblldbPluginSymbolFileDWARF.a lib/liblldbPluginSymbolFilePDB.a lib/liblldbPluginObjCRuntime.a lib/liblldbPluginSwiftLanguage.a lib/liblldbCommands.a lib/liblldbPluginObjectFileJIT.a lib/liblldbPluginClangCommon.a lib/liblldbPluginCPPRuntime.a lib/liblldbPluginAppleObjCRuntime.a lib/liblldbPluginPlatformPOSIX.a lib/liblldbPluginSymbolFileNativePDB.a lib/liblldbCore.a lib/liblldbSymbol.a lib/liblldbTarget.a lib/liblldbPluginProcessUtility.a lib/liblldbInterpreter.a lib/liblldbBreakpoint.a lib/liblldbDataFormatters.a lib/liblldbExpression.a lib/liblldbPluginCPlusPlusLanguage.a lib/liblldbPluginObjCLanguage.a lib/liblldbPluginPlatformMacOSX.a lib/liblldbPluginExpressionParserClang.a lib/liblldbPluginExpressionParserSwift.a lib/liblldbPluginSymbolFileDWARF.a lib/liblldbPluginSymbolFilePDB.a lib/liblldbPluginObjCRuntime.a lib/liblldbPluginSwiftLanguage.a lib/liblldbCommands.a lib/liblldbPluginObjectFileJIT.a lib/liblldbPluginClangCommon.a lib/liblldbPluginCPPRuntime.a lib/liblldbPluginAppleObjCRuntime.a lib/liblldbPluginPlatformPOSIX.a lib/liblldbPluginSymbolFileNativePDB.a -lswiftASTSectionImporter -lswiftReflection -lswiftRemoteAST /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libclangCodeGen.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMCoroutines.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMCoverage.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMLTO.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMObjCARCOpts.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMPasses.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMCodeGen.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libclangRewriteFrontend.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libclangFrontend.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libclangDriver.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libclangParse.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMOption.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libclangSerialization.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libclangSema.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libclangAPINotes.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libclangEdit.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libclangAnalysis.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libclangASTMatchers.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMipo.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMBitWriter.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMIRReader.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMAsmParser.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMInstrumentation.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMLinker.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMScalarOpts.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMAggressiveInstCombine.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMInstCombine.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMVectorize.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMTransformUtils.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMMCJIT.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMExecutionEngine.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMRuntimeDyld.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMTarget.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMAnalysis.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMProfileData.a -lswiftBasic -lswiftFrontend /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libclangRewrite.a -lswiftIDE -lswiftParse -lswiftSIL -lswiftSILOptimizer -lswiftSerialization /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMDebugInfoDWARF.a -lswiftAST -lswiftClangImporter lib/liblldbBase.a lib/liblldbHost.a /usr/lib/x86_64-linux-gnu/libedit.so lib/liblldbUtility.a /usr/lib/x86_64-linux-gnu/libxml2.so -lcurses /usr/lib/x86_64-linux-gnu/libform.so /usr/lib/x86_64-linux-gnu/libpanel.so /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libclangAST.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libclangLex.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libclangBasic.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMDebugInfoPDB.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMObject.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMBitReader.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMBitstreamReader.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMCore.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMRemarks.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMMCParser.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMMC.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMBinaryFormat.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMDebugInfoCodeView.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMDebugInfoMSF.a /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMSupport.a -lrt -ldl -ltinfo -lpthread -lm /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/lib/libLLVMDemangle.a -Wl,-rpath,"\$ORIGIN/../lib:/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/buildbot_linux/llvm-linux-x86_64/./lib" && :
14:51:52 /usr/bin/ld: cannot find -lswiftASTSectionImporter
14:51:52 /usr/bin/ld: cannot find -lswiftReflection
14:51:52 /usr/bin/ld: cannot find -lswiftRemoteAST
14:51:52 /usr/bin/ld: cannot find -lswiftBasic
14:51:52 /usr/bin/ld: cannot find -lswiftFrontend
14:51:52 /usr/bin/ld: cannot find -lswiftIDE
14:51:52 /usr/bin/ld: cannot find -lswiftParse
14:51:52 /usr/bin/ld: cannot find -lswiftSIL
14:51:52 /usr/bin/ld: cannot find -lswiftSILOptimizer
14:51:52 /usr/bin/ld: cannot find -lswiftSerialization
14:51:52 /usr/bin/ld: cannot find -lswiftAST
14:51:52 /usr/bin/ld: cannot find -lswiftClangImporter
```

Darwin:
```
15:09:21 CMake Error at /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master-next/buildbot_incremental/llvm-macosx-x86_64/lib/cmake/llvm/LLVMDistributionSupport.cmake:24 (message):
15:09:21   Specified distribution component 'debugserver' doesn't have an install
15:09:21   target
15:09:21 Call Stack (most recent call first):
15:09:21   CMakeLists.txt:253 (llvm_distribution_add_targets)
15:09:21 
15:09:21 
15:09:21 CMake Error at /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master-next/buildbot_incremental/llvm-macosx-x86_64/lib/cmake/llvm/LLVMDistributionSupport.cmake:30 (message):
15:09:21   Specified distribution component 'debugserver' doesn't have an
15:09:21   install-stripped target.  Its installation target creation should be
15:09:21   changed to use add_llvm_install_targets, or you should manually create the
15:09:21   'install-debugserver-stripped' target.
15:09:21 Call Stack (most recent call first):
15:09:21   CMakeLists.txt:253 (llvm_distribution_add_targets)
15:09:21 
15:09:21 
15:09:21 -- Configuring incomplete, errors occurred!
```

I think that the Linux failure is worrisome as that seems like a regression from the previous state.

**Comment by lanza** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Bleh, seems that the Darwin builds have regressed again:

```
15:52:53 -- Found PythonInterp: /usr/bin/python2.7 (found version "2.7.10") 
15:52:53 -- Found PythonLibs: /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.tbd (found version "2.7.16") 
15:52:53 CMake Error at cmake/modules/LLDBConfig.cmake:236 (message):
15:52:53   Found incompatible Python interpreter (2.7.10) and Python libraries
15:52:53   (2.7.16)
15:52:53 Call Stack (most recent call first):
15:52:53   CMakeLists.txt:20 (include)
```

Seems that the system python now differs from the SDK python framework :-(.  This is a regression, lets get this merged.

CC: @gottesmm @jrose-apple @shahmishal

**Comment by jrose-apple** [comment]
I mean, those *are* allowed to diverge. That's how SDKs work.

**Pull request merged**
