### PR TITLE
sourcekitd/test: add an interface grouping test for user module.

### PR DESCRIPTION
**Pull request by nkcsgexi**
rdar://45903094

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test and merge

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test and merge

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by benlangmuir** [comment]
This broke when testing for iphone simulator: https://ci.swift.org/view/Packages/job/oss-swift-package-osx/2959/

I hava a revert PR: https://github.com/apple/swift/pull/22650

Please do a full (non-smoke) CI tests before re-applying.  I think the fix will be to add the command-line arguments that %target-swift-frontend does into the sourcekit command; at the minimum you'll want to add `-target %target-triple`, but there may be other things you need.

**Comment by nkcsgexi** [comment]
@benlangmuir thank for reverting! I’ll take a look

**Pull request merged**
