### PR TITLE
[Coverage] Get 'analyze-code-coverage=merged' to work.

### PR DESCRIPTION
**Pull request by rintaro**
#### What's in this pull request?

`build-script --swift-analyze-code-coverage=merged` was not working.
In `test/CMakeList.txt`, set `profdata_merge` command after `test_results_dir` is initialized.

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

### CODE REVIEW

**Comment by gribozavr** [comment]
This is my fault!  LGTM, thank you!

**Comment by gribozavr** [comment]
@swift-ci Please test and merge

**Comment by rintaro** [comment]
Could someone please re-run test and merge this?

**Comment by gribozavr** [comment]
@swift-ci Please test and merge

**Pull request merged**
