### PR TITLE
Allow generic requirements that augment Self in Swift 3 compatibility mode

### PR DESCRIPTION
**Pull request by DougGregor**
PR #5857 started rejecting generic requirements that adding
constraints directly to 'Self', which means the requirements would be
unsatisfiable by some models. At the time that commit was merged, we
had thought the compiler crashed on all instances of this problem.

It turns out that, with assertions disabled, these protocols would be
accepted and could be used, so downgrade the error to a 'deprecated'
warning in Swift 3 compatibility mode.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by jrose-apple** [comment]
Wait, how are you *supposed* to express it?

**Comment by DougGregor** [comment]
@jrose-apple , [SE-0142](https://github.com/apple/swift-evolution/blob/master/proposals/0142-associated-types-constraints.md)

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by jrose-apple** [comment]
Oh, of course. I missed that this was on the extension.

**Pull request merged**
