### PR TITLE
[SwiftSyntax] Remove default empty string in `Token`'s `text`

### PR DESCRIPTION
**Pull request by kimdv**
https://github.com/apple/swift-syntax/pull/341

### CODE REVIEW

**Comment by kimdv** [comment]
https://github.com/apple/swift-syntax/pull/341

@swift-ci Please smoke test

**Review by ahoppen — APPROVED** [review]

**Comment by kimdv** [comment]
https://github.com/apple/swift-syntax/pull/341

@swift-ci Please smoke test

**Comment by kimdv** [comment]
https://github.com/apple/swift-syntax/pull/341

@swift-ci Please smoke test MacOS

**Comment by kimdv** [comment]
@ahoppen the CI for MacOS did fail yesterday evening and now it passed? 
Am I good to go?

**Comment by ahoppen** [comment]
Yes, if CI passed you can merge.

**Pull request merged**
