### PR TITLE
[IRGen] Sign the value witness table pointer

### PR DESCRIPTION
**Pull request by Azoy**

### CODE REVIEW

**Comment by Azoy** [comment]
@swift-ci please test

**Comment by Azoy** [comment]
@swift-ci please test

**Review by mikeash — APPROVED** [review]

**Review by aschwaighofer — COMMENTED** [review]
This is a change in ABI   — there is code inlined by the compiler that now authenticates that did not before. So old code that loads the vwt from metadata would break.

**Comment by aschwaighofer** [comment]
Oh, right this part of the arm64e ABI has not been up streamed. Go ahead and ignore me.

**Pull request closed without merging**
