### PR TITLE
Mark start/stop sections as SHF_GNU_RETAIN

### LINKED ISSUE #5698: Linking with lld stopped working on linux/Android since lld 13 and this repo enabled `--gc-sections`
### Description

After dead-stripping was enabled in #4135, [various people reported problems with using lld](https://github.com/apple/swift-package-manager/pull/4135#issuecomment-1050485754), though it wouldn't always show up. It appears to be some change with lld 13, as lld 12 works fine, perhaps the commit @drodriguez linked (I'll try reverting that commit and report back later).

Obviously, this is really a regression in how Swift interacts with lld 13 and 14, but I'm reporting it here first as we'll probably want to amend SPM 5.7 quickly before the underlying lld issue is figured out. @keith, maybe we should disable stripping on ELF if the linker is lld for now?

@3405691582, can you reproduce on OpenBSD?

### Expected behavior

Linking to work fine with lld, as it does with gold.

### Actual behavior

Several linker errors like this show up instead:
```
ld.lld: error: undefined hidden symbol: __start_swift5_protocols
>>> referenced by SwiftRT-ELF.cpp
>>>               /home/butta/swift-DEVELOPMENT-SNAPSHOT-2022-07-25-a-ubuntu20.04/usr/lib/swift/linux/x86_64/swiftrt.o (swift_image_constructor())
```

### Steps to reproduce

1. Clone swift-argument-parser
2. Remove a file because of [some unrelated bug](https://github.com/apple/swift-argument-parser/issues/463): `rm Sources/ArgumentParserTestHelpers/TestHelpers.swift`
3. Build the package in release mode with lld: `../swift-DEVELOPMENT-SNAPSHOT-2022-07-25-a-ubuntu20.04/usr/bin/swift build -v -c release -Xswiftc -use-ld=lld`

### Swift Package Manager version/commit hash

latest Jul. 25 trunk snapshot and 5.7 Jul. 23 snapshot

### Swift & OS version (output of `swift --version && uname -a`)

Swift 5.8 and 5.7 on Ubuntu 20.04 x86_64

### LINKED ISSUE #60406: lld 13+ stopped working with the linker flag `--gc-sections` and Swift on ELF platforms
**Describe the bug**
SPM turned on `--gc-sections` in trunk six months ago, apple/swift-package-manager#4135-  just before that, [a linux user reported this bug with lld 13](https://forums.swift.org/t/swift-and-clang-interop-broken-with-clang-13-on-linux/55203) but didn't respond when I asked for more info- and [others soon reported similar problems with SPM and lld](https://github.com/apple/swift-package-manager/pull/4135#issuecomment-1050485754). The issue appears to be [a change to how `--gc-sections` works in lld that was added last year](https://reviews.llvm.org/D96914), which was then [flipped on by default](https://reviews.llvm.org/rG6d2d3bd0a61f5fc7fd9f61f48bc30e9ca77cc619) and produces linker errors like these when the repro command below is run:
```
Swift version 5.6.2 (swift-5.6.2-RELEASE)
Target: x86_64-unknown-linux-gnu
/home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/bin/swift-frontend -frontend -c -primary-file swift/test/Interpreter/hello_toplevel.swift -target x86_64-unknown-linux-gnu -disable-objc-interop -new-driver-path /home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/bin/swift-driver -resource-dir /home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/lib/swift -module-name hello_toplevel -o /tmp/TemporaryDirectory.s5r53T/hello_toplevel-1.o
/home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/bin/swift-autolink-extract /tmp/TemporaryDirectory.s5r53T/hello_toplevel-1.o -o /tmp/TemporaryDirectory.s5r53T/hello_toplevel-2.autolink
/home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/bin/clang -fuse-ld=lld -pie -Xlinker -rpath -Xlinker /home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/lib/swift/linux /home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/lib/swift/linux/x86_64/swiftrt.o /tmp/TemporaryDirectory.s5r53T/hello_toplevel-1.o @/tmp/TemporaryDirectory.s5r53T/hello_toplevel-2.autolink -L /home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/lib/swift/linux -lswiftCore --target=x86_64-unknown-linux-gnu -v -Xlinker --gc-sections -o hello_toplevel
error: link command failed with exit code 1 (use -v to see invocation)
clang version 13.0.0 (https://github.com/apple/llvm-project.git f765bf5b71fd3637a6f6d1d3e6ab95ca91892a0c)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/bin/ld.lld" -pie -z relro --hash-style=gnu --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o hello_toplevel /lib/x86_64-linux-gnu/Scrt1.o /lib/x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/9/crtbeginS.o -L/home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/lib/swift/linux -L/usr/lib/gcc/x86_64-linux-gnu/9 -L/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -L/home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/bin/../lib -L/lib -L/usr/lib -rpath /home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/lib/swift/linux /home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/lib/swift/linux/x86_64/swiftrt.o /tmp/TemporaryDirectory.s5r53T/hello_toplevel-1.o -lswift_Concurrency -lswiftCore -lswiftSwiftOnoneSupport -lswiftCore --gc-sections -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-linux-gnu/9/crtendS.o /lib/x86_64-linux-gnu/crtn.o
ld.lld: error: undefined hidden symbol: __start_swift5_protocols
>>> referenced by SwiftRT-ELF.cpp
>>>               /home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/lib/swift/linux/x86_64/swiftrt.o:(swift_image_constructor())

ld.lld: error: undefined hidden symbol: __stop_swift5_protocols
>>> referenced by SwiftRT-ELF.cpp
>>>               /home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/lib/swift/linux/x86_64/swiftrt.o:(swift_image_constructor())

ld.lld: error: undefined hidden symbol: __start_swift5_protocol_conformances
>>> referenced by SwiftRT-ELF.cpp
>>>               /home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/lib/swift/linux/x86_64/swiftrt.o:(swift_image_constructor())

ld.lld: error: undefined hidden symbol: __stop_swift5_protocol_conformances
>>> referenced by SwiftRT-ELF.cpp
>>>               /home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/lib/swift/linux/x86_64/swiftrt.o:(swift_image_constructor())

ld.lld: error: undefined hidden symbol: __start_swift5_type_metadata
>>> referenced by SwiftRT-ELF.cpp
>>>               /home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/lib/swift/linux/x86_64/swiftrt.o:(swift_image_constructor())

ld.lld: error: undefined hidden symbol: __stop_swift5_type_metadata
>>> referenced by SwiftRT-ELF.cpp
>>>               /home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/lib/swift/linux/x86_64/swiftrt.o:(swift_image_constructor())

ld.lld: error: undefined hidden symbol: __start_swift5_typeref
>>> referenced by SwiftRT-ELF.cpp
>>>               /home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/lib/swift/linux/x86_64/swiftrt.o:(swift_image_constructor())

ld.lld: error: undefined hidden symbol: __stop_swift5_typeref
>>> referenced by SwiftRT-ELF.cpp
>>>               /home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/lib/swift/linux/x86_64/swiftrt.o:(swift_image_constructor())

ld.lld: error: undefined hidden symbol: __start_swift5_reflstr
>>> referenced by SwiftRT-ELF.cpp
>>>               /home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/lib/swift/linux/x86_64/swiftrt.o:(swift_image_constructor())

ld.lld: error: undefined hidden symbol: __stop_swift5_reflstr
>>> referenced by SwiftRT-ELF.cpp
>>>               /home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/lib/swift/linux/x86_64/swiftrt.o:(swift_image_constructor())

ld.lld: error: undefined hidden symbol: __start_swift5_fieldmd
>>> referenced by SwiftRT-ELF.cpp
>>>               /home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/lib/swift/linux/x86_64/swiftrt.o:(swift_image_constructor())

ld.lld: error: undefined hidden symbol: __stop_swift5_fieldmd
>>> referenced by SwiftRT-ELF.cpp
>>>               /home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/lib/swift/linux/x86_64/swiftrt.o:(swift_image_constructor())

ld.lld: error: undefined hidden symbol: __start_swift5_assocty
>>> referenced by SwiftRT-ELF.cpp
>>>               /home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/lib/swift/linux/x86_64/swiftrt.o:(swift_image_constructor())

ld.lld: error: undefined hidden symbol: __stop_swift5_assocty
>>> referenced by SwiftRT-ELF.cpp
>>>               /home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/lib/swift/linux/x86_64/swiftrt.o:(swift_image_constructor())

ld.lld: error: undefined hidden symbol: __start_swift5_replace
>>> referenced by SwiftRT-ELF.cpp
>>>               /home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/lib/swift/linux/x86_64/swiftrt.o:(swift_image_constructor())

ld.lld: error: undefined hidden symbol: __stop_swift5_replace
>>> referenced by SwiftRT-ELF.cpp
>>>               /home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/lib/swift/linux/x86_64/swiftrt.o:(swift_image_constructor())

ld.lld: error: undefined hidden symbol: __start_swift5_replac2
>>> referenced by SwiftRT-ELF.cpp
>>>               /home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/lib/swift/linux/x86_64/swiftrt.o:(swift_image_constructor())

ld.lld: error: undefined hidden symbol: __stop_swift5_replac2
>>> referenced by SwiftRT-ELF.cpp
>>>               /home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/lib/swift/linux/x86_64/swiftrt.o:(swift_image_constructor())

ld.lld: error: undefined hidden symbol: __start_swift5_builtin
>>> referenced by SwiftRT-ELF.cpp
>>>               /home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/lib/swift/linux/x86_64/swiftrt.o:(swift_image_constructor())

ld.lld: error: undefined hidden symbol: __stop_swift5_builtin
>>> referenced by SwiftRT-ELF.cpp
>>>               /home/foo/swift-5.6.2-RELEASE-ubuntu20.04/usr/lib/swift/linux/x86_64/swiftrt.o:(swift_image_constructor())

ld.lld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Steps To Reproduce**
1. `./swift-5.6.2-RELEASE-ubuntu20.04/usr/bin/swiftc swift/test/Interpreter/hello_toplevel.swift -use-ld=lld -Xlinker --gc-sections -v`

Removing the lld flag makes it default to the system gold linker on linux, which works fine. Make sure you're running lld 13+ as in the output above, as I think it may pick up an earlier lld installed in the system if one is there.

**Expected behavior**
Linking with lld 13+ and `--gc-sections` to work

**Environment (please fill out the following information)**
 - OS: Ubuntu 20.04 x86_64 and Android 12 AArch64

**Additional context**
Since linux uses gold by default and the Android LTS NDK used lld 12 till a couple weeks ago, it looks like this wasn't affecting too many people, but will if SPM 5.7 turns on dead-stripping by default, so that change is being backed out of SPM temporarily, apple/swift-package-manager#5698, till we can fix it here.

@keith has proposed #60357 to fix this, but it may not be enough. @drodriguez ran [that fix](https://github.com/apple/swift-package-manager/issues/5698#issuecomment-1203373062) and [the new lld flag `-z nostart-stop-gc`](https://github.com/apple/swift-package-manager/issues/5698#issuecomment-1204188946) through the compiler validation suite on linux x86_64 and got a couple dozen more test failures.

I tried replicating what he did natively on Android with the July 25 source snapshot, which uses lld 14 from the Termux environment, and got the following compiler validation suite test results:

No changes, ie just the stock test run with lld - 36 test failures
lld with `SWIFT_DRIVER_TEST_OPTIONS=" -Xlinker --gc-sections"` - 1113 test failures
lld with `SWIFT_DRIVER_TEST_OPTIONS=" -Xlinker --gc-sections"` and the stdlib fix from #60357 - 159 test failures
lld with `SWIFT_DRIVER_TEST_OPTIONS=" -Xlinker --gc-sections -Xlinker -z -Xlinker nostart-stop-gc"` - 54 test failures

I also tried applying both the stdlib fix and `-z nostart-stop-gc`, but that made no difference in the test results compared to `-z nostart-stop-gc` alone.

Comparing that last run to the first stock run, I see 19 additional test failures- 18 TypeDecoder tests and DebugInfo.ASTSection- that all invoke `lldb-moduleimport-test` and fail with `FileCheck error: '<stdin>' is empty.`, similar to @drodriguez's results (LinkerSections.function_sections-lld that failed in the stock run now passes with `-z nostart-stop-gc` applied, as that test was already using `--gc-sections`). I will look into those further.

I'm looking for feedback from the Swift compiler devs on what we should do about this: apply one of these fixes or try something different?

@3405691582, let me know if you can reproduce on OpenBSD.

### PR DESCRIPTION
**Pull request by keith**
Fixes https://github.com/apple/swift-package-manager/issues/5698
Fixes https://github.com/apple/swift/issues/60406

### CODE REVIEW

**Comment by keith** [comment]
@swift-ci Please test Linux platform

**Comment by MaxDesiatov** [comment]
@swift-ci build toolchain

**Comment by keith** [comment]
we might have to test with https://github.com/apple/swift-driver/pull/1402 to be 100% sure this is working

**Comment by keith** [comment]
Please test with following pull request:
https://github.com/apple/swift-driver/pull/1402

@swift-ci Please test Linux platform

**Comment by keith** [comment]
Hrm our jobs failed but I don't _think_ it's related to this, but the issues from this in the past were subtle so it could be

**Comment by keith** [comment]
apple/swift-driver#1402

@swift-ci Please test Linux platform

**Comment by keith** [comment]
I believe this is the relevant part of the log:

```
---
4.	While evaluating request ExecuteSILPipelineRequest(Run pipelines { PrepareOptimizationPasses, EarlyModulePasses, HighLevel,Function+EarlyLoopOpt, HighLevel,Module+StackPromote, MidLevel,Function, ClosureSpecialize, LowLevel,Function, LateLoopOpt, SIL Debug Info Generator } on SIL for Swift)
5.	While running pass #38079 SILFunctionTransform "ComputeSideEffects" on SILFunction "@$sSNsSxRzSZ6StrideRpzrlE10startIndexSNsSxRzSZABRQrlE0C0Oyx_Gvg".
 for getter for startIndex (at /home/build-user/swift/stdlib/public/core/ClosedRange.swift:209:14)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
/home/build-user/build/buildbot_linux/swift-linux-x86_64/bootstrapping1/bin/swift-frontend[0x6da26d3]
```

**Comment by finagolfin** [comment]
This is failing when bootstrapping: my guess is that something about this attribute is making the bootstrap1 compiler crash, as the bootstrap0 compiler works fine on the linux CI. The difference is that the bootstrap1 compiler links against the Swift stdlib that you're modifying here, while the bootstrap0 compiler doesn't.

Is this working for you locally?

**Comment by keith** [comment]
It works for me locally but I'm not bootstrapping, I'll try that flow!

**Comment by keith** [comment]
Doesn't fail for me with this command either:

```
./swift/utils/build-script --release-debuginfo --skip-early-swift-driver --skip-early-swiftsyntax --sccache --build-subdir raw-cmd --extra-cmake-options="-DLLVM_USE_LINKER=/home/ksmiley/.bin/ld.lld,-DSWIFT_ENABLE_EXPERIMENTAL_CXX_INTEROP=NO,-DSWIFT_USE_LINKER=lld"
```

**Comment by keith** [comment]
trying with the command from CI:

```
./swift/utils/build-script --assertions --swift-enable-ast-verifier=0 --no-swift-stdlib-assertions '--swift-install-components=autolink-driver;compiler;clang-resource-dir-symlink;stdlib;swift-remote-mirror;sdk-overlay;static-mirror-lib;toolchain-tools;license;sourcekit-inproc' '--llvm-install-components=llvm-ar;llvm-cov;llvm-profdata;IndexStore;clang;clang-resource-headers;compiler-rt;clangd;lld;LTO;clang-features-file' --llbuild --swiftpm --swift-driver --xctest --libicu --swiftdocc --build-ninja --install-llvm --install-swift --install-lldb --install-llbuild --install-swiftpm --install-swift-driver --install-swiftsyntax --install-xctest --install-libicu --install-prefix=/usr --install-sourcekit-lsp --install-swiftformat --install-swiftdocc --build-swift-static-stdlib --build-swift-static-sdk-overlay --build-swift-stdlib-unittest-extra --test-installable-package --toolchain-benchmarks --install-destdir=/home/build-user/swift-nightly-install --installable-package=/home/build-user/PR-ubuntu2004.tar.gz --relocate-xdg-cache-home-under-build-subdir --skip-early-swift-driver --skip-early-swiftsyntax --build-subdir=buildbot_linux --lldb --release --test --validation-test --long-test --stress-test --test-optimized --foundation --libdispatch --indexstore-db --sourcekit-lsp --swiftdocc '--lit-args=-v --time-tests' --lldb-test-swift-only --install-foundation --install-libdispatch --reconfigure
```

**Comment by finagolfin** [comment]
Does adding `-DSWIFT_ENABLE_EXPERIMENTAL_CXX_INTEROP=NO` disable bootstrapping, because the bootstrap relies on C++ Interop? That may be why that command works for you.

**Comment by keith** [comment]
🙃 I can try without that, I added that to avoid a different issue originally:

```
<unknown>:0: warning: the '-enable-experimental-cxx-interop' flag is deprecated; please pass '-cxx-interoperability-mode=' instead
<unknown>:0: note: Swift will maintain source compatibility for imported APIs based on the selected compatibility mode, so updating the Swift compiler will not change how APIs are imported
=== /home/ksmiley/dev/oss-swift/swift/stdlib/public/Cxx/std/std.swift:13:19 ===
12 |
13 | @_exported import CxxStdlib // Clang module
   |                   ^ error: underlying Objective-C module 'CxxStdlib' not found
14 | @_exported import Cxx // Swift module
```

**Comment by keith** [comment]
I don't think it disables bootstrapping because I see this in the output:

```
-- Building host Swift tools for LINUX x86_64
--   Build type:     RelWithDebInfo
--   Assertions:     TRUE
--   LTO:
--   Bootstrapping:  BOOTSTRAPPING
```

but I will try without it anyways

**Comment by finagolfin** [comment]
> error: underlying Objective-C module 'CxxStdlib' not found

This should be fixed by #65534, if you update to latest trunk or apply that patch to your checkout.

**Comment by finagolfin** [comment]
> I don't think it disables bootstrapping

You can check by running something like this on your build:
```bash
> readelf -d build/Ninja-Release/swift-linux-x86_64/bootstrapping1/bin/swift-frontend | grep libswiftCore
```

**Comment by keith** [comment]
Locally this one still passes:

```
./swift/utils/build-script --release-debuginfo --skip-early-swift-driver --skip-early-swiftsyntax --sccache --build-subdir raw-cmd2 --extra-cmake-options="-DLLVM_USE_LINKER=/home/ksmiley/.bin/ld.lld,-DSWIFT_USE_LINKER=lld"
```

The CI command is still running

**Comment by keith** [comment]
> You can check by running something like this on your build:

I'm not sure exactly what you see as the difference here but I see:

```
% readelf -d build/raw-cmd2/swift-linux-x86_64/bootstrapping1/bin/swift-frontend| grep -i core
 0x0000000000000001 (NEEDED)             Shared library: [libswiftCore.so]
```

In this case

**Comment by keith** [comment]
Interestingly the CI command fails with:

```
ld.lld: error: relocation R_X86_64_PC32 cannot be used against symbol stderr; recompile with -fPIC
>>> defined in /lib/x86_64-linux-gnu/libc.so.6
>>> referenced by stdio2.h:100 (/usr/include/x86_64-linux-gnu/bits/stdio2.h:100)
>>>               object.o:(_PyObject_AssertFailed) in archive /home/ksmiley/.pyenv/versions/3.10.4/lib/libpython3.10.a
```

But maybe that's because i'm using not the system python in this case so I'll try to remove that and build again

**Comment by finagolfin** [comment]
Are you doing clean rebuilds locally? The final thing to try would be to remove your `--extra-cmake-options` changing the linker to lld, as the linux CI uses gold.

**Comment by keith** [comment]
Yea I guess the reason I'm using lld is because the bug only surfaces with that, so if it does end up passing with gold (after that crash is resolved) I'm not sure we'd be validating the change actually works

**Comment by keith** [comment]
In this case my builds were clean yes (I passed a new build-subdir) (although I am using sccache)

**Comment by finagolfin** [comment]
> I guess the reason I'm using lld is because the bug only surfaces with that, so if it does end up passing with gold (after that crash is resolved) I'm not sure we'd be validating the change actually works

The problem is that this pull is currently crashing the linux CI with gold, so you'll have to fix that first to ever have a hope of getting this in.

**Comment by kateinoigakukun** [comment]
@swift-ci Please test

**Comment by finagolfin** [comment]
Anything change recently that should make this work?

**Comment by kateinoigakukun** [comment]
I don't know but I'm going to work on a similar issue for wasm, so I'd like to know the latest status of the fix.

**Comment by keith** [comment]
I believe the current issue is that there is some other place not covered by this change where these sections are created as well, and we need to flip this option in that place as well. That's just an assumption but the current result is ld.gold crashes I assume because of that mismatch

**Comment by keith** [comment]
@etcwilde you might be interested in this, I feel like it's close but haven't had the time to dig into it more

**Comment by kateinoigakukun** [comment]
Just FYI: I'm doing some experiments on https://github.com/apple/swift/pull/71373

**Comment by keith** [comment]
https://github.com/apple/swift/pull/72061

**Pull request closed without merging**
