### PR TITLE
[5.5][Serialization] Recover from failures when correcting typos in `ModuleFile::lookupClassMembers`

### PR DESCRIPTION
**Pull request by xymus**
When diagnostics search for possible typos in the name of a member of an `AnyObject` instance the compiler looks at all classes and their members in all imported modules. This can cause a deserialization failure if a nonpublic class member refers to an implementation-only imported type. This change makes the compiler recover from such deserialization failure instead of crashing.

- Scope: This blocks internal tests and could crash the compiler when reading partial or invalid code.
- Risk: Low, the change only avoids potential crashes.
- Origination: Likely the introduction of `@_implementationOnly`.
- Resolves rdar://79427805
- Cherry-pick of #38046

### CODE REVIEW

**Comment by xymus** [comment]
@swift-ci Please test

**Comment by xymus** [comment]
@swift-ci Please test macOS

**Review by artemcm — APPROVED** [review]
LGTM for the 5.5 branch.

**Comment by xymus** [comment]
@swift-ci Please nominate

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
