### PR TITLE
[libSyntax] Represent raw string delimiters

### PR DESCRIPTION
**Pull request by jansvoboda11**
This PR adds amends the parser and libSyntax to accomodate raw string delimiters.

Resolves [SR-10620](https://bugs.swift.org/browse/SR-10620).

Depends on [PR #124](https://github.com/apple/swift-syntax/pull/124) to swift-syntax.

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by rintaro** [comment]
https://github.com/apple/swift-syntax/pull/124
@swift-ci Please test

**Comment by rintaro** [comment]
Ah, https://github.com/apple/swift/pull/24464 introduced a conflict.
@jansvoboda11 Mind rebasing on the current master?

**Comment by jansvoboda11** [comment]
@rintaro I've rebased, but I'm not sure why the build failed before that.

**Comment by rintaro** [comment]
Thanks. iOS simulator failure looks unrelated.

**Comment by rintaro** [comment]
apple/swift-syntax#124
@swift-ci Please test

**Comment by rintaro** [comment]
Thank you Jan!

**Pull request merged**
