### PR TITLE
Applying API guidelines to The Standard Library

### PR DESCRIPTION
**Pull request by moiseev**
#### Applying swift API naming guidelines to The Standard Library

This PR applies the guidelines to The Standard Library according to [this proposal](https://github.com/apple/swift-evolution/blob/master/proposals/0006-apply-api-guidelines-to-the-standard-library.md).

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by dduan** [comment]
😍👏

**Comment by shawnce** [comment]
:tada:

**Comment by zeeshankhan** [comment]
🎉👏👍

**Comment by diogoAntunes** [comment]
:clap:

**Comment by ZuymantO** [comment]
Amazing  🎊🎖

--
J. Charles

**Pull request merged**
