### PR TITLE
LibcShims android fix

### PR DESCRIPTION
**Pull request by amraboelela**

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please smoke test

**Review by milseman — APPROVED** [review]
LGTM. Thank you so much for finding and fixing this!

**Comment by milseman** [comment]
(do you have a Twitter handle I can use for a shout-out?)

**Comment by amraboelela** [comment]
@milseman no, but my email is amraboelela@gmail.com

**Comment by amraboelela** [comment]
This is the fastest PR, to be merged, I have ever made :)

**Comment by milseman** [comment]
Shout out to Swift's CI and @shahmishal's continued vigilance!

**Pull request merged**
