### PR TITLE
[TF] Remove TensorFlowUnittest.

### PR DESCRIPTION
**Pull request by dan-zheng**
`TensorFlowUnittest` is deprecated.
`TensorFlow` module and tests have moved to https://github.com/tensorflow/swift-apis.

### CODE REVIEW

**Review by rxwei — APPROVED** [review]

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Review by bgogul — APPROVED** [review]

**Comment by dan-zheng** [comment]
[`test/TensorFlowRuntime/tensor_autodiff_control_flow.swift`](https://github.com/apple/swift/blob/tensorflow/test/TensorFlowRuntime/tensor_autodiff_control_flow.swift) needs to be ported to [`Tests/TensorFlowTests/TensorAutoDiffTests.swift`](https://github.com/tensorflow/swift-apis/blob/master/Tests/TensorFlowTests/TensorAutoDiffTests.swift) in `tensorflow/swift-apis`.

```
FAIL: Swift(macosx-x86_64) :: TensorFlowRuntime/tensor_autodiff_control_flow.swift (8201 of 12272)
******************** TEST 'Swift(macosx-x86_64) :: TensorFlowRuntime/tensor_autodiff_control_flow.swift' FAILED ********************
/Users/swiftci/jenkins/workspace/swift-PR-TensorFlow-macOS/swift/test/TensorFlowRuntime/tensor_autodiff_control_flow.swift:12:8: error: no such module 'TensorFlowUnittest'
import TensorFlowUnittest
       ^

********************
Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90.. 
Testing Time: 811.42s
********************
Failing Tests (1):
    Swift(macosx-x86_64) :: TensorFlowRuntime/tensor_autodiff_control_flow.swift

  Expected Passes    : 12034
  Expected Failures  : 26
  Unsupported Tests  : 211
  Unexpected Failures: 1
```

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by dan-zheng** [comment]
Thanks @rxwei!

**Pull request merged**
