### PR TITLE
Fix MetadataReader's isa-chasing on platforms that use indexed isa.

### PR DESCRIPTION
**Pull request by rjmccall**
This is just implementing Greg Parker's spec for how to do it.

rdar://29996920

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Comment by rjmccall** [comment]
Starting tests, but I'm going to hold this until I see that it's fixing the armv7k problems on trunk.

**Comment by rjmccall** [comment]
In the meantime, @slavapestov would you mind reviewing?

**Comment by slavapestov** [comment]
Looks good, thanks!

**Comment by rjmccall** [comment]
Looks like the trunk change did not fix the issue.  Holding this for source updates.

**Comment by rjmccall** [comment]
Bot finally came back clean on that test, so the new revision is good to go.

@swift-ci Please test.

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Pull request merged**
