### PR TITLE
[CodeCompletion] Complete code completion tokens after if-statement as top-level

### PR DESCRIPTION
**Pull request by ahoppen**
Instead of setting the code completion position when parsing the if-statement, which doesn’t create a `CodeCompletionExpr`, parse it as a new top-level expression.

As far as test-cases are concerned, this removes the “RareKeyword” flair from top-level completions in the modified test case. This makes sense IMO.

---

I came across this while migrating expression completions to solver-based, which started having issues because we were completing `StmtOrExpr` without a `CodeCompletionExpr`.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
Nice find, but this makes `completeAfterIfStmt(/*hasElse=*/false)` branch non-reachable. I think that is still usable because 
```swift
if condition {
  ...
}
#^HERE^#
```
In this case, we want to suggest `else` and the global expression completions. Otherwise, we should not suggest `else` (other than after conditions for `guard`). But that can be done in followups.

**Review by rintaro — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test Linux

**Pull request merged**
