### PR TITLE
utils: Provide error message for missing build preset options

### PR DESCRIPTION
**Pull request by 13rac1**
Adds a try/catch block to utils/SwiftBuildSupport.py to catch ConfigParser.InterpolationMissingOptionError caused by missing required preset options such as: install_destdir.

Changes this:

```
$ ./build-script --preset=buildbot_linux_1404
Traceback (most recent call last):
  File "./build-script", line 755, in <module>
    sys.exit(main())
  File "./build-script", line 749, in main
    return main_preset()
  File "./build-script", line 77, in main_preset
    args.preset_substitutions, args.preset_file_names, args.preset)
  File "/home/user/swift/utils/SwiftBuildSupport.py", line 169, in get_preset_options
    _get_preset_options_impl(config, substitutions, preset_name)
  File "/home/user/swift/utils/SwiftBuildSupport.py", line 147, in _get_preset_options_impl
    _get_preset_options_impl(config, substitutions, mixin)
  File "/home/user/swift/utils/SwiftBuildSupport.py", line 137, in _get_preset_options_impl
    for o, a in config.items(section_name):
  File "/usr/lib/python2.7/ConfigParser.py", line 655, in items
    for option in options]
  File "/usr/lib/python2.7/ConfigParser.py", line 691, in _interpolate
    self._interpolate_some(option, L, rawval, section, vars, 1)
  File "/usr/lib/python2.7/ConfigParser.py", line 723, in _interpolate_some
    option, section, rest, var)
ConfigParser.InterpolationMissingOptionError: Bad value substitution:
    section: [preset: mixin_linux_installation]
    option : install-destdir
    key    : install_destdir
    rawval : 
```

To this:

```
$ ./build-script --preset=buildbot_linux_1404
./build-script: missing option 'install_destdir' for preset: mixin_linux_installation
```

### CODE REVIEW

**Comment by bitjammer** [comment]
Thank you, nice improvement! If I may, could I ask you to take this one step further and:

- Don't `sys.exit(1)` right then and there
- Store some kind of `missing_options` bool
- Exit just after the loop terminates if `missing_options == True`

This will emit all of the missing interpolations instead of wasting time running the command several times to find out you've missed another option.

**Comment by eosrei** [comment]
Yes, sounds good.

**Comment by eosrei** [comment]
Ok, hows this?

The exception occurs in the items() generator:
```
        for o, a in config.items(section_name):
```
Which breaks out of the entire for loop, so I've changed it to use `config.options()` and `config.get()`.
`_get_preset_options_impl()` itself is recursive (you can see it called twice in the traceback above). The missing options list must return back down the call stack to the `get_preset_options()` to collect all missing options. The same code path `build_script_opts` and `build_script_impl_opts` take.

**Comment by eosrei** [comment]
Output example:
```bash
user@server $ ./build-script --preset=buildbot_linux_140
./build-script: preset 'buildbot_linux_140' not found
user@server $ ./build-script --preset=buildbot_linux_1404 install_destdir="/tmp"
./build-script: missing option(s) for preset 'buildbot_linux_1404': installable_package
user@server $ ./build-script --preset=buildbot_linux_1404 
./build-script: missing option(s) for preset 'buildbot_linux_1404': install_destdir, installable_package
```

**Comment by bitjammer** [comment]
Fantastic. Let's pull it in.

**Pull request merged**
