### PR TITLE
[DO NOT MERGE] Update swift-argument-parser

### PR DESCRIPTION
**Pull request by jakepetroules**

### CODE REVIEW

**Comment by jakepetroules** [comment]
apple/swift-package-manager#3843
apple/sourcekit-lsp#434
apple/swift-driver#899
apple/swift#40103

@swift-ci Please test

**Review by finagolfin — APPROVED** [review]

**Comment by jakepetroules** [comment]
apple/swift-package-manager#3843
apple/sourcekit-lsp#434
apple/swift-driver#899
apple/swift-docc#32
apple/swift-markdown#17
#40103

@swift-ci Please test

**Comment by jakepetroules** [comment]
apple/swift-package-manager#3843
apple/sourcekit-lsp#434
apple/swift-driver#899
apple/swift-docc#32
apple/swift-markdown#17
#40103

@swift-ci Please test

**Comment by jakepetroules** [comment]
DO NOT MERGE. This is waiting for @shahmishal.

**Comment by shahmishal** [comment]
```
7. OSS - LLDB - ASAN + UBSAN macOS (main) (Release)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.4.4
	new Branch: 1.0.1
5. OSS - LLDB Incremental - Ubuntu 16.04 (main)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.4.4
	new Branch: 1.0.1
6. OSS - LLDB Incremental - Ubuntu 18.04 (main)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.4.4
	new Branch: 1.0.1
4. OSS - LLDB Incremental - macOS (main)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.4.4
	new Branch: 1.0.1
OSS - Swift Package Trigger (main)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.4.4
	new Branch: 1.0.1
1. OSS - Swift ASAN - macOS (main)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.4.4
	new Branch: 1.0.1
1. OSS - Swift ASAN - Ubuntu 16.04 (main)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.4.4
	new Branch: 1.0.1
0. OSS - Swift Incremental RA - Ubuntu 16.04 (main)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.4.4
	new Branch: 1.0.1
0. OSS - Swift Incremental RA - Ubuntu 16.04 - Long Test (main)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.4.4
	new Branch: 1.0.1
0. OSS - Swift Incremental RA - Ubuntu 18.04 (main)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.4.4
	new Branch: 1.0.1
0. OSS - Swift Incremental RA - Ubuntu 18.04 - Long Test (main)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.4.4
	new Branch: 1.0.1
1. OSS - Swift Leaks Sanitizer - LSAN - Ubuntu 18.04 (main)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.4.4
	new Branch: 1.0.1
0. OSS - Swift Incremental RA - macOS (main)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.4.4
	new Branch: 1.0.1
0. OSS - Swift Incremental RA - macOS (main) (Apple Silicon)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.4.4
	new Branch: 1.0.1
OSS - Swift Incremental RA - macOS - Trigger (main)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.4.4
	new Branch: 1.0.1
0. OSS - Swift Incremental RA - macOS (main) (Xcode)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.4.4
	new Branch: 1.0.1
OSS - Swift Package - Ubuntu 16.04 (main)
	Skip: ${swift_argument_parser}
OSS - Swift Package - Ubuntu 18.04 (main)
	Skip: ${swift_argument_parser}
OSS - Swift Package - macOS (main)
	Skip: ${swift_argument_parser}
0. OSS - Swift Pull Request Test (status) (main)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.4.4
	new Branch: 1.0.1
2. Swift Build Standard Library with Toolchain (main)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.4.4
	new Branch: 1.0.1
2. Swift Build Standard Library with Toolchain (main) (minimal)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.4.4
	new Branch: 1.0.1
1. OSS - Swift - TSAN - libdispatch - Ubuntu 18.04 (main)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.4.4
	new Branch: 1.0.1
1. OSS - Swift (Tools Opt+No Assert,  Stdlib Opt+DebInfo, Test Simulator) - macOS (main)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.4.4
	new Branch: 1.0.1
1. OSS - Swift (Tools Opt+Assert, Stdlib DebInfo+Assert, Test Device non_executable) (main)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.4.4
	new Branch: 1.0.1
1. OSS - Swift (Tools Opt+Assert, Stdlib DebInfo+Assert, Test Simulator) - macOS (main)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.4.4
	new Branch: 1.0.1
2. Swift (Tools Opt+Assert, Stdlib Opt+Assert) (macOS 10.14.5) (Swift in the OS)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.4.4
	new Branch: 1.0.1
1. OSS - Swift (Tools Opt+Assert,  Stdlib Opt+DebInfo, Test Simulator) - macOS (main)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.4.4
	new Branch: 1.0.1
1. OSS - Swift (Tools Opt+Assert, Stdlib Opt+DebInfo+Assert, Long Test) - macOS  (main)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.4.4
	new Branch: 1.0.1
1. OSS - Swift (Tools Opt+Assert, Stdlib Opt+DebInfo+Assert, Test Simulator) - macOS  (main)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.4.4
	new Branch: 1.0.1
2. Swift Sourcekit Stress Tester (main)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.4.4
	new Branch: 1.0.1
2. Swift Sourcekit Stress Tester (main) (weekly)
	Repo: git@github.com:apple/swift-argument-parser.git
	Branch: 0.4.4
	new Branch: 1.0.1
```

**Pull request merged**
