### PR TITLE
[IRGen] Don't use extended encoding for async @objc protocol methods.

### PR DESCRIPTION
**Pull request by varungandhi-apple**
It should only be used for `@objc` classes.

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
@swift-ci smoke test

**Comment by varungandhi-apple** [comment]
@swift-ci smoke test macOS

**Comment by varungandhi-apple** [comment]
Test failure due to https://github.com/apple/swift/pull/36688

**Comment by varungandhi-apple** [comment]
@swift-ci smoke test macOS

**Review by mikeash — APPROVED** [review]

**Pull request merged**
