### PR TITLE
Tweak test to make it fail to compile regardless of SE-0110.

### PR DESCRIPTION
**Pull request by rudkx**

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Review by bitjammer — COMMENTED** [review]
Won't this successfully compile?

**Comment by rudkx** [comment]
`never_compiles_safely_exits.swift` calls that like this:
```
func bar() {
  foo(bar)
}
```

**Comment by bitjammer** [comment]
Ah, right. Cool.

**Review by bitjammer — APPROVED** [review]

**Pull request merged**
