### PR TITLE
[Parse] Stop ignoring private decls for incremental purposes.

### PR DESCRIPTION
**Pull request by jrose-apple**
We'd really like to say that private decls can't affect other files, but we don't have enough information at parse-time:
- Private members of non-private classes still show up in vtables, which affects subclasses and callers in other files.
- Private stored properties of non-private structs change the layout of the struct.
- Private types may be used in private stored properties, affecting the layout of the containing struct.
- Private decls of /any kind/ can be used as the initial value of a stored property without an explicit type.
  
  ``` swift
  private class Evil {
    class func defaultAlignment() -> Alignment { return .evil }
  }
  public struct Character {
    // Inferred type here!
    private var alignment = Evil.defaultAlignment()
  }
  ```

To be safe and correct, go back to only ignoring method bodies.

**[SR-1030](https://bugs.swift.org/browse/SR-1030)**

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test OS X platform

**Comment by slavapestov** [comment]
What about adding a new top-level private function -- do we (correctly) ignore those?

Now that I think about it though, a top-level operator might witness a protocol requirement. I'm going to sleep now and don't feel like thinking this through, but there might be something we can do there in any case.

**Comment by jrose-apple** [comment]
That's not correct either.

```swift
private func defaultAlignment() -> Alignment { return .evil }
public struct Character {
  // Inferred type here!
  private var alignment = defaultAlignment()
}
```

The token-based interface hash just isn't flexible enough to do this.

**Comment by jrose-apple** [comment]
@swift-ci Please test OS X platform

**Pull request merged**
