### PR TITLE
Re-enable a test requiring an optimized stdlib to ensure we pattern match.

### PR DESCRIPTION
**Pull request by gottesmm**
rdar://84780237

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by etcwilde** [comment]
@swift-ci please test macOS platform

**Comment by etcwilde** [comment]
Do we want to ensure the behaviour of debug code as well, or are we not expecting move-only to work with debug builds?

**Comment by gottesmm** [comment]
@etcwilde the issue is that the _move builtin itself isn't being optimized enough. So the problem isn't an issue as long as we don't use the builtin in the stdlib since all over code should use a release stdlib. That may need to change with time though.

**Review by etcwilde — APPROVED** [review]
I'm slightly concerned that the optimization level used to build the stdlib effects how client code is emitted since that sounds like grounds for ABI issues later down the line, but I'm approving so we can get the testing turned back on here.

**Comment by compnerd** [comment]
This seems to be failing consistently on the builders now? https://ci-external.swift.org/job/oss-swift-windows-x86_64-vs2019/7621/console

**Comment by etcwilde** [comment]
Yeah, this probably should have been re-tested before merging.

**Comment by compnerd** [comment]
Seems to be failing on Linux as well: https://ci.swift.org/job/swift-PR-Linux-smoke-test/32054/console

**Pull request merged**
