### PR TITLE
[Macros] Emit diagnostics from plugins

### PR DESCRIPTION
**Pull request by rxwei**
Make `_rewrite` return an buffer containing diagnostics and emit them.

### CODE REVIEW

**Comment by rxwei** [comment]
apple/swift-syntax#1085
@swift-ci please test

**Comment by rxwei** [comment]
apple/swift-syntax#1085
@swift-ci please test

**Comment by rxwei** [comment]
apple/swift-syntax#1085
@swift-ci please test

**Comment by rxwei** [comment]
apple/swift-syntax#1085
@swift-ci please smoke test macos

**Review by DougGregor — APPROVED** [review]
Looks great to me, thank you!

**Pull request merged**
