### PR TITLE
[abi.rst] Fix incorrect mangling substitution example

### PR DESCRIPTION
**Pull request by xtravar**
Before: CS0_zoo -> after: CS0_3zoo - note the missing 'normal' to determine identifier length

### CODE REVIEW

**Comment by jckarter** [comment]
Nice catch. There's another incorrect mention of `CS0_zoo` without the run length right above it too.

**Comment by gottesmm** [comment]
The Before/after comment should be in the commit message body.

**Comment by jckarter** [comment]
Looks good. Squash the commits and I'll merge.

**Comment by xtravar** [comment]
I could use some pro-tips as I'm just flopping around editing on github.com.

**Comment by gottesmm** [comment]
@xtravar No worries. I view this as an education process. I am showing you how we do things = ). Otherwise, how would you know.

**Comment by xtravar** [comment]
Thanks for the patience.  So what I did is close the pull requests and re-do things, but that's probably not the way it's supposed to be done, right?

**Comment by dabrahams** [comment]
> On Dec 16, 2015, at 12:38 PM, Mike <notifications@github.com> wrote:
> 
> Thanks for the patience. So what I did is close the pull requests and re-do things, but that's probably not the way it's supposed to be done, right?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/apple/swift/pull/600#issuecomment-165232109>.
> 


Using git push -f to update the branch in your pull request usually works out better.

-Dave

**Comment by kud1ing** [comment]
@xtravar Soley from the browser this is probably not supported:
* https://help.github.com/articles/github-flow-in-the-browser/
* https://help.github.com/articles/about-git-rebase/

**Pull request closed without merging**
