### PR TITLE
[APINotes] Fix mis-annotated error code enums.

### PR DESCRIPTION
**Pull request by jrose-apple**
Some files accidentally _renamed_ the enums using `SwiftName` rather than associating them with an error domain constant using `NSErrorDomain`. Amazingly, we've gotten no complaints about this.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test OS X platform

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test Linux platform

**Comment by jrose-apple** [comment]
@DougGregor, can you review?

**Comment by DougGregor** [comment]
This looks good. For reference, the QuartzCore notes were actually needed when NS prefix stripping was a function of the Clang importer, because QuartzCore forward-declared NSEnumerator. But it's useless now.

**Comment by jrose-apple** [comment]
Huh. Wouldn't have expected that to affect anything, as a forward declaration. Okay.

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test Linux platform

**Pull request merged**
