### PR TITLE
Make VFE / WME / conditional records work even with ObjC interop and with reflection metadata

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by eeckstein — APPROVED** [review]
lgtm!
@aschwaighofer should also take a look

**Review by aschwaighofer — APPROVED** [review]
lgtm

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Pull request merged**
