### PR TITLE
[SILGen/DI] InitAccessors: Fix handling of `nonmutating set` when type has other stored properties

### LINKED ISSUE #67827: Init accessor with non mutating set results in compiler error
Using init accessor with a nonmutating set (or _modify) using Xcode 15 beta 6, results in compiler error (this is a regression from beta 5):

```swift
struct Test {
    private var _count = 0

    var count: Int = 0
    {
        @storageRestrictions(initializes: _count)
        init {
            _count = newValue
        }
        get {
            _count
        }
        nonmutating set {
            // Update store
        }
    }
}
```

`Variable 'self._count' used before being initialized`

Note: This code is typically generated from a macro, where the original would look like (similar to @Observable):

```swift
@SomeMacro
struct Test {
    var count: Int = 0
}
```

### PR DESCRIPTION
**Pull request by xedin**
The original change supported only the case where all stored properties were controlled
by an init accessor but when other fields were involved SILGen would emitted copies of
loaded "self" for each setter application which is redundant and due to the fact that the
setter was escaping. 

These changes make partial application of the setter non-escaping which means that
"self" can be borrowed instead of copied.

Resolves: https://github.com/apple/swift/issues/67827

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please build toolchain macOS

**Review by jckarter — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test source compatibility release

**Comment by xedin** [comment]
@swift-ci please test source compatibility debug

**Comment by xedin** [comment]
This failure in distributed actors looks unrelated but I am going to wait for main branch suite run to complete.

**Comment by mansbernhardt** [comment]
Thanks @xedin for fixing this. Would it be possible to get this fix into the 5.9.x branch/release as well?

**Comment by xedin** [comment]
Unfortunately I think it might be too risky of a change for 5.9.x but I'll see what I can do.

**Comment by mansbernhardt** [comment]
Hello @xedin, I tried your fix out in the latest Xcode 15.3 beta (15E5178i), and it seem to work fine for the examples I reported, but if I change them slightly to include e.g. let constant it fails to compile again `Variable 'self._count' used before being initialized`:

```swift
struct Test {
    let id: UUID
    private var _count: Int

    var count: Int
    {
        @storageRestrictions(initializes: _count)
        init {
            _count = newValue
        }
        get {
            _count
        }
        nonmutating set {
            // Update store
        }
    }

    init(id: UUID, count: Int) {
        self.id = id
        self.count = count // << Variable 'self._count' used before being initialized
    }
}
```

**Comment by xedin** [comment]
I will take a look!

**Comment by xedin** [comment]
Hm, `var id` doesn't work either, `var` and `let` result in the same SIL so it must be something in DI that I haven't accounted for.

**Comment by mansatgigset** [comment]
Interesting. Switching UUID to Date also fails.

**Comment by xedin** [comment]
Right, I think both Date and UUID are big enough to force indirect access to the `Test`, this is something we didn't account for because for that a copy of `Test` has to be allocated.

**Comment by xedin** [comment]
I think I figured it out, the problem is not actually SILGen, it's Sema because it generates a load from "self" of `count` though it shouldn't be doing that. There is a special handling of that for property wrappers but not for init accessors, I should be able to fix this tomorrow.

**Comment by xedin** [comment]
Here is the fix - https://github.com/apple/swift/pull/71248

**Comment by mansbernhardt** [comment]
@xedin I tested the above with the latest Xcode beta, and it seems to work, but if I modify it slightly it still fails with the same error (the below is a closer match to my macros is generating its code).

```swift
struct Test {
  let id: UUID
  private var _count: Int

  var count: Int
  {
    @storageRestrictions(initializes: _count)
    init {
      _count = newValue
    }
    _read {
      yield _count
    }
    nonmutating _modify {
      var val = _count
      yield &val
    }
  }

  init(id: UUID, count: Int) {
    self.id = id
    self.count = count // << Variable 'self._count' used before being initialized
  } // << Return from initializer without initializing all stored properties
}

```

**Pull request merged**
