### PR TITLE
[stdlib] Make some trivial Substring methods inlinable

### PR DESCRIPTION
**Pull request by karwa**
These look like simple oversights.

CC @milseman

### CODE REVIEW

**Comment by slavapestov** [comment]
This limits future evolution of the standard library. Is there a measurable performance benefit from these changes that justifies any loss in flexibility?

**Comment by karwa** [comment]
@slavapestov 

- Substring.*: trivial forwarding to `Slice`, like everything else. No way the stdlib could evolve differently given everything else that is inlinable. Almost everything else in Substring is already inlinable.
- Substring.UTF8View: the equivalent methods in .UTF16View are inlinable.

@milseman should be able to say more about if these were intentionally withheld from inlining (if so, maybe it's worth a comment).

I don't know if we actually benchmark these code-paths. I think it's likely going to be worth it to inline the subscript, at least.

**Comment by milseman** [comment]
@karwa the reasoning is usually the other way around: we prefer to not mark something inlinable unless there is sufficient justification. Marking a method inlinable can significantly *harm* performance, as it will block inlining of non-inlinable code that the method calls.

String.replaceSubrange is not inlinable, so making Substring.replaceSubrange is more likely to hurt performance than not. If Substring.replaceSubrange is *not* inlinable, then String.replaceSubrange can be inlined fully into it.

Substring.subscript could be a candidate, as well as the Substring.UTF8View methods. Do you have a benchmark or scenario demonstrating the performance improvement?

**Comment by karwa** [comment]
@milseman Nope, I just noticed these while adding `withContiguousStorageIfAvailable` forwarding (String.UTF8View implements it, Substring.UTF8View does not). Could you request some from CI to start with? It can take a solid half-day to rebuild a branch and run benchmarks locally for me.

**Comment by milseman** [comment]
@swift-ci please benchmark

**Comment by karwa** [comment]
@milseman Hmm... that doesn't seem to have worked. Mind trying again?

**Comment by milseman** [comment]
(Just to double check the trend)

@swift-ci please benchmark

**Comment by CodaFi** [comment]
@swift-ci please benchmark

**Comment by milseman** [comment]
Some of those seem spurious, but the CSVParser.UTF8 one doesn't. 

@swift-ci please benchmark

**Comment by karwa** [comment]
@milseman what do you think?

**Comment by milseman** [comment]
I'm in favor

@swift-ci please test

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by milseman** [comment]
@swift-ci please test

**Comment by karwa** [comment]
@milseman It seems the test was manually aborted:

```
00:21:39 ninja: build stopped: interrupted by user.
00:21:39 Build was aborted
00:21:39 Aborted by mishal_shah@apple.com
```

**Comment by CodaFi** [comment]
@swift-ci test

**Pull request merged**
