### PR TITLE
When building standalone stdlib, use Clang resource dir from the toolchain, not the system default

### PR DESCRIPTION
**Pull request by kubamracek**
This is to resolve this failure: <https://ci.swift.org/job/swift-PR-stdlib-with-toolchain-osx/6/consoleFull>

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci test stdlib with toolchain

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by compnerd — CHANGES_REQUESTED** [review]
This seems wrong, this is under the use the host compiler path, and the resource dir cannot be mixed and matched as the headers may not be parseable.

**Comment by kubamracek** [comment]
The alternative is to change build-script-impl to explicitly set CMAKE_C_COMPILER to clang from `native_clang_tools_path`. Would that work?

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by compnerd — APPROVED** [review]

**Comment by kubamracek** [comment]
@swift-ci test stdlib with toolchain

**Comment by shahmishal** [comment]
@swift-ci test stdlib with toolchain

**Comment by kubamracek** [comment]
@swift-ci please test Linux platform

**Comment by buttaface** [comment]
@kubamracek, this is wrong and will need to be reverted. The reason the standalone stdlib preset uses the host clang is because [the `build-runtime-with-host-compiler=1` flag is explicitly set by that preset](https://github.com/apple/swift/blob/52bbe11161f908d4c58cbdd2a423c68b9688b191/utils/build-presets.ini#L2247), which you're now incoherently overriding. Not only that but this solution now applies the `native-clang-tools-path` to _all_ build-script-impl products, not just the stdlib, which could cause problems.

@gottesmm, you first added this flag in #25108 last year, perhaps you can chime on whether it's really necessary and how best to fix the issue he was having.

**Comment by kubamracek** [comment]
Can you describe what actual problem are you seeing that's caused by this change? It's been merged in for 2 months, so I'm not sure reverting is a good option. But it depends on what kind of regression are you seeing.

I guess the important point is "What exactly is native-clang-tools-path supposed to mean?" I would argue that it's technically supposed to mean something like "When set, use this path for clang/clang++ for all C/C++ compilations, avoid using any other compilers". Given that, this PR is actually fixing an important bug, which has nothing to do with the other flags or with the preset.

Let's also get @compnerd's take on this.

**Comment by buttaface** [comment]
> Can you describe what actual problem are you seeing that's caused by this change?

It has not caused a problem for me yet, but it's the wrong way to fix your problem.

> I guess the important point is "What exactly is native-clang-tools-path supposed to mean?" I would argue that it's technically supposed to mean something like "When set, use this path for clang/clang++ for all C/C++ compilations, avoid using any other compilers".

Well, that's not what it does even now, let me explain as I have been looking into this lately. The build-script requires a `host_cc` to be set, which it looks up in the path or can be passed in with `--host-cc` and then [it sets `CMAKE_{C,CXX}_COMPILER` for _all_ CMake invocations with that host clang/clang++](https://github.com/apple/swift/blob/e01893cb56f989b20ba4309286450105211f031e/utils/swift_build_support/swift_build_support/cmake.py#L138). Then, several build products override that with another `CMAKE_{C,CXX}_COMPILER` invocation, either set to the freshly built Swift clang or `native_clang_tools_path`, #32922.

On top of this, you've now added a third `CMAKE_{C,CXX}_COMPILER` invocation for _all_ `build-script-impl` CMake invocations, including when compiling CMark, LLVM, and Swift. These multiple redefinitions of the C/C++ compiler used can cause problems, as I mentioned in #33724.

> this PR is actually fixing an important bug, which has nothing to do with the other flags or with the preset.

It matters because the reason given above is to fix that preset, which explicitly has a flag set to only use the `host _cc` and so you're subverting the preset by changing this. Maybe that preset doesn't really need that `build-runtime-with-host-compiler=1` flag though, in which case, the correct fix for your problem is removing that flag.

If you change the reason for this pull to other products, I noted above that several were already using `native_clang_tools_path` and you've simply added another possible breakage for products that for whatever reason don't override the `host_cc` till this pull.

**Pull request merged**
