### PR TITLE
Rebind Memory Idiomatically

### PR DESCRIPTION
**Pull request by glessard**
While working on `String` stuff, I came across many lines that could be replaced by a single, more modern utterance.

(no related issue)

### CODE REVIEW

**Comment by glessard** [comment]
@swift-ci please test

**Comment by glessard** [comment]
Apologies for the review request spam; I'm not sure why this happened.

**Review by Azoy — APPROVED** [review]
looks good to me!

**Comment by glessard** [comment]
@swift-ci please benchmark Apple silicon

**Comment by glessard** [comment]
### Performance (arm64): -O

| **Improvement**                 | **OLD** | **NEW** | **DELTA** |      **RATIO** |
| :------------------------------ | ------: | ------: | --------: | -------------: |
| NaiveRRC.append.largeContiguous |   0.082 |     0.0 |    -98.8% | **83.00x (?)** |
| Set.subtracting.Empty.Box       |  13.413 |  12.163 |     -9.3% |  **1.10x (?)** |
| ReversedBidirectional           |  4775.0 |  4338.0 |     -9.2% |  **1.10x (?)** |
| DataSetCountMedium              | 202.667 | 184.857 |     -8.8% |  **1.10x (?)** |

### Code size: -O


### Performance (arm64): -Osize

| **Regression**          |  **OLD** |  **NEW** | **DELTA** |     **RATIO** |
| :---------------------- | -------: | -------: | --------: | ------------: |
| ObserverForwarderStruct |  192.727 |  218.125 |    +13.2% | **0.88x (?)** |
| &nbsp;                  |          |          |           |               |
| **Improvement**         |  **OLD** |  **NEW** | **DELTA** |     **RATIO** |
| DataSetCountMedium      |  205.814 |    185.0 |    -10.1% | **1.11x (?)** |
| StringHasSuffixAscii    | 1403.846 | 1279.333 |     -8.9% |     **1.10x** |
| ReversedBidirectional   |   5431.0 |   4994.0 |     -8.0% | **1.09x (?)** |

### Code size: -Osize


### Performance (arm64): -Onone

| **Regression**                      |  **OLD** |  **NEW** | **DELTA** |     **RATIO** |
| :---------------------------------- | -------: | -------: | --------: | ------------: |
| SubstringRemoveFirst1               |    0.077 |    0.125 |    +61.5% | **0.62x (?)** |
| ArrayAppendGenericStructs           |  649.412 |    860.0 |    +32.4% | **0.76x (?)** |
| ArrayAppendToGeneric                |  327.797 |  366.571 |    +11.8% | **0.89x (?)** |
| StringHasPrefixAscii                | 1435.294 |   1560.0 |     +8.7% |     **0.92x** |
| BufferFillFromSlice                 |   11.533 |     12.5 |     +8.4% | **0.92x (?)** |
| StringHasSuffixAscii                | 1497.857 | 1622.667 |     +8.3% | **0.92x (?)** |
| &nbsp;                              |          |          |           |               |
| **Improvement**                     |  **OLD** |  **NEW** | **DELTA** |     **RATIO** |
| ArrayOfGenericPOD2                  |   1176.5 |    855.0 |    -27.3% | **1.38x (?)** |
| RawBuffer.copyContents              |   13.607 |   11.382 |    -16.4% | **1.20x (?)** |
| IterateData                         |   1558.0 |   1364.0 |    -12.5% | **1.14x (?)** |
| DataSetCountMedium                  |  230.851 |  209.744 |     -9.1% |     **1.10x** |
| ObjectiveCBridgeStubDateAccess      |   3342.0 |   3098.0 |     -7.3% | **1.08x (?)** |
| ObjectiveCBridgeStubNSDateRefAccess |   4227.0 |   3948.0 |     -6.6% | **1.07x (?)** |

### Code size: -swiftlibs



<details>
  <summary><strong>How to read the data</strong></summary>
The tables contain differences in performance which are larger than 8% and
differences in code size which are larger than 1%.


If you see any unexpected regressions, you should consider fixing the
regressions before you merge the PR.

**Noise**: Sometimes the performance results (not code size!) contain false
alarms. Unexpected regressions which are marked with '(?)' are probably noise.
If you see regressions which you cannot explain you can try to run the
benchmarks again. If regressions still show up, please consult with the
performance team (@eeckstein).
</details>

<details>
  <summary><strong>Hardware Overview</strong></summary>


      Model Name: Mac mini
      Model Identifier: Macmini9,1
      Total Number of Cores: 8 (4 performance and 4 efficiency)
      Memory: 16 GB

</details>

**Comment by glessard** [comment]
After inspecting the prefix and suffix benchmarks, I don't believe these are real regressions, or related to this.

**Pull request merged**
