### PR TITLE
Serialize/deserialize lifetime dependence when present

### PR DESCRIPTION
**Pull request by meg-gupta**

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Comment by meg-gupta** [comment]
@atrick @xedin Let me know if you have any comments, I can fix them in a follow on commit.

**Comment by atrick** [comment]
LGTM

**Pull request merged**
