### PR TITLE
ClangImporter: Targeted fix for <rdar://problem/29081276>

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test and merge

**Comment by slavapestov** [comment]
@swift-ci Please smoke test and merge

**Review by jrose-apple — APPROVED** [review]

**Comment by slavapestov** [comment]
The timeout is a bug (we need to skip the new logic on Linux)

**Comment by slavapestov** [comment]
@swift-ci Please smoke test and merge

**Comment by slavapestov** [comment]
@swift-ci Please smoke test and merge

**Pull request merged**
