### PR TITLE
Move certain ops & gradients to swift-apis

### PR DESCRIPTION
**Pull request by tanmayb123**
Moving relevant ops & gradients to swift-apis (PR: https://github.com/tensorflow/swift-apis/pull/63)

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by tanmayb123** [comment]
Seems like there's a bunch of errors since `swift-apis` can't find the right operations & such.

**Comment by tanmayb123** [comment]
I also forgot to remove the tests. Just did that.

**Comment by rxwei** [comment]
I updated swift-apis' checkout hash for you.

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by tanmayb123** [comment]
Tests have passed. Anything else that needs to be added/removed here?

**Comment by rxwei** [comment]
Merged. Thanks.

**Pull request merged**
