### PR TITLE
[CMake] Switch to building the overlays in Swift 5 mode

### PR DESCRIPTION
**Pull request by jrose-apple**
Now that that's stabilized, we don't have to keep them in Swift 4 mode any longer. (Arguably we don't need the CMake variable at all, but it may be useful again in the future.)

rdar://problem/49040980

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Review by Rostepher — APPROVED** [review]
The CMake changes look reasonable to me.

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Review by moiseev — APPROVED** [review]

**Comment by jrose-apple** [comment]
@swift-ci Please test Linux

**Pull request merged**
