### PR TITLE
Implicit tuple interpolations, take two

### PR DESCRIPTION
**Pull request by beccadax**
When the parser encounters a "weird" string interpolation, like `\(x, y)` or `\(foo: x)`, it sometimes produces a `TupleExpr` instead of a `ParenExpr`. This change wraps any such `TupleExpr`s in `ParenExpr`s to keep them from being interpreted as argument lists. This doesn't stop us from getting strange nodes like single-expression labeled tuples, but at least they're strange in ways that the compiler can cope with, and unlike #17074, this solution doesn't appear to cause any source breakage.

I'll post on Evolution soon about how to deal with these interpolations on a more permanent basis.

Resolves [SR-7958](https://bugs.swift.org/browse/SR-7958) (again).

cc @CodaFi

### CODE REVIEW

**Comment by slavapestov** [comment]
Thanks!

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by brentdax** [comment]
@slavapestov Ugh. What are you supposed to do when fixing a crasher makes it actually compile successfully, instead of diagnosing an error? Or is the answer "you fool, you should always diagnose an error when you fix a crasher"?

**Comment by brentdax** [comment]
Mind running that again? I guess I shouldn't put too much faith in the resolve-crashes script.

**Comment by CodaFi** [comment]
@swift-ci please test source compatibility

**Comment by CodaFi** [comment]
Let's try this again

⛵️

**Pull request merged**
