### PR TITLE
Follow up for allowing same-file extensions with Swift 3 compatibility, tests and tweaked diagnostic locations.

### PR DESCRIPTION
**Pull request by huonw**
#16376

### CODE REVIEW

**Comment by huonw** [comment]
@swift-ci please smoke test

**Comment by huonw** [comment]
@swift-ci please test source compatibility

**Comment by huonw** [comment]
@swift-ci please smoke test

The process starts again.

**Comment by huonw** [comment]
@swift-ci please smoke test

**Comment by huonw** [comment]
@swift-ci please smoke test

**Comment by huonw** [comment]
@swift-ci please smoke test

**Comment by huonw** [comment]
@swift-ci please test source compatibility

**Comment by huonw** [comment]
@swift-ci please smoke test

**Comment by huonw** [comment]
@swift-ci please smoke test

**Review by DougGregor — APPROVED** [review]
Fantastic, thank you!

**Comment by slavapestov** [comment]
@huonw Thanks for the explanation, it makes sense. I forgot that Swift 3 had the old private behavior.

**Comment by huonw** [comment]
@swift-ci please smoke test

**Comment by huonw** [comment]
@swift-ci please smoke test

**Comment by huonw** [comment]
@swift-ci please smoke test

**Comment by shahmishal** [comment]
@swift-ci please smoke test

**Comment by shahmishal** [comment]
@swift-ci please smoke test

**Comment by shahmishal** [comment]
@swift-ci please smoke test macOS

**Comment by huonw** [comment]
@swift-ci please test source compatibility

**Comment by shahmishal** [comment]
Started on previous sha 

https://ci.swift.org/view/Pull%20Request/job/swift-PR-source-compat-suite/1176/parameters/

ce5a599a430216d5e7f07acc0b06af13f49cbaaf

**Comment by shahmishal** [comment]
@swift-ci please test source compatibility

**Pull request merged**
