### PR TITLE
[CMake] Expand SWIFT_MODULE_DEPENDS_* to Android

### PR DESCRIPTION
**Pull request by modocache**
#### What's in this pull request?

2633a0f3 expanded SWIFT_MODULE_DEPENDS_\* to treat Linux and FreeBSD separately. Android needs the same treatment. These changes fix an Android build error, in which Glibc was not linked to private stdlib libraries that relied upon it.

/cc @compnerd, since he added this logic in #3316
#### Resolved bug number: None

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by modocache** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Why is treating it as Linux here not sufficient?

**Comment by modocache** [comment]
You mean this?

```diff
diff --git a/cmake/modules/AddSwift.cmake b/cmake/modules/AddSwift.cmake
index b51b105..f57b065 100644
--- a/cmake/modules/AddSwift.cmake
+++ b/cmake/modules/AddSwift.cmake
@@ -1207,7 +1207,7 @@ function(add_swift_library name)
         elseif("${sdk}" STREQUAL "FREEBSD")
           list(APPEND swiftlib_module_depends_flattened
                ${SWIFTLIB_SWIFT_MODULE_DEPENDS_FREEBSD})
-        elseif("${sdk}" STREQUAL "LINUX")
+        elseif("${sdk}" STREQUAL "LINUX" OR "${sdk}" STREQUAL "ANDROID")
           list(APPEND swiftlib_module_depends_flattened
               ${SWIFTLIB_SWIFT_MODULE_DEPENDS_LINUX})
```

This would also work, I think. Is this be preferable?

**Comment by modocache** [comment]
The OS X build failure is unrelated.

**Comment by gribozavr** [comment]
> This would also work, I think. Is this be preferable?

How different do you expect Android to be in near future, in terms of the set of provided libraries from this repository?

**Comment by compnerd** [comment]
+1 on @gribozavr's comment.  My reasoning was the same.  I really think that Android should be treated as Linux, unless there is a strong reason to do so otherwise.

**Comment by modocache** [comment]
Sounds good! I'll update this pull request to the diff I mentioned above. If either of you find any other spots where CMake provides special treatment to Android, where it should instead treat is as Linux, please ping me or create an issue on Swift JIRA.

**Comment by modocache** [comment]
@swift-ci please test

**Comment by modocache** [comment]
One of the package tests, for the REPL, timed out during the Linux test run. It's unrelated to this change.

**Comment by modocache** [comment]
Seems like the consensus was on this approach, a simple one-line change that only affects Android, so I went ahead and merged myself. Thanks for the feedback, everyone!

**Pull request merged**
