### PR TITLE
cherry-pick patches for LLVM ilist changes

### PR DESCRIPTION
**Pull request by bob-wilson**
Swift changes to match https://github.com/apple/swift-llvm/pull/36 and https://github.com/apple/swift-clang/pull/50. These changes were already on the master-next branch, so this is just cherry-picking them back to master.

### CODE REVIEW

**Comment by bob-wilson** [comment]
Please test with the following PRs:
https://github.com/apple/swift-llvm/pull/36
https://github.com/apple/swift-clang/pull/50

@swift-ci please test

**Comment by bob-wilson** [comment]
I pulled in some more patches to the LLVM PR. Let's try this again.
Please test with the following PRs:
apple/swift-llvm#36
apple/swift-clang#50

@swift-ci please test

**Comment by gparker42** [comment]
We need similar changes on the 3.1 branch. @bob-wilson, can you take that?
https://ci.swift.org/view/swift-3.1-branch/job/oss-swift-3.1-incremental-RA-osx/18/

**Comment by bob-wilson** [comment]
Mishal is going to rebranch/merge swift-3.1, so that will resolve it.

**Pull request merged**
