### PR TITLE
[interop] add a testcase for inserting into std::set from Swift

### PR DESCRIPTION
**Pull request by hyp**

### CODE REVIEW

**Comment by hyp** [comment]
@swift-ci please smoke test

**Comment by hyp** [comment]
@plotfi let's see how CI reacts 🙈

**Comment by plotfi** [comment]
I know the feeling; I had a PR for testing out insertion a while ago that was weird on CI even though it “worked” locally

**Comment by hyp** [comment]
@swift-ci please smoke test

**Comment by hyp** [comment]
@swift-ci please smoke test

**Comment by hyp** [comment]
@swift-ci please test

**Comment by egorzhdan** [comment]
We actually already have tests for `std::set::insert` in `swift/test/Interop/Cxx/stdlib/use-std-set.swift`, I added a few tests in a recent PR: https://github.com/apple/swift/pull/66764

**Comment by hyp** [comment]
Cool, will close it then.

**Pull request closed without merging**
