### PR TITLE
swift-symbolgraph-extract: Mark required args

### PR DESCRIPTION
**Pull request by bitjammer**
- Mark required arguments
- Print help usage on zero args

rdar://problem/58770554

### CODE REVIEW

**Comment by bitjammer** [comment]
@swift-ci Please smoke test

**Comment by bitjammer** [comment]
@swift-ci Please test Windows platform

**Comment by bitjammer** [comment]
@swift-ci Please smoke test OS X Platform

**Comment by bitjammer** [comment]
@swift-ci Please smoke test

**Comment by bitjammer** [comment]
@swift-ci Please test Windows platform

**Comment by bitjammer** [comment]
@swift-ci Please smoke test

**Comment by bitjammer** [comment]
@swift-ci Please test Windows platform

**Comment by bitjammer** [comment]
@swift-ci Please smoke test

**Comment by bitjammer** [comment]
@swift-ci Please test Windows platform

**Comment by bitjammer** [comment]
@swift-ci Please smoke test

**Comment by bitjammer** [comment]
@swift-ci Please test Windows platform

**Comment by compnerd** [comment]
LGTM

**Pull request merged**
