### PR TITLE
Revert "IRGen: Always eliminate frame pointers of leaf functions"

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/swift#31921

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @aschwaighofer

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by aschwaighofer** [comment]
Is this addressed by https://github.com/apple/swift/pull/31987?

**Comment by compnerd** [comment]
Yeah, that should fix it; I just uploaded the same change >.<  Thanks!

**Pull request closed without merging**
