### PR TITLE
Add -Osize optimization documentation

### PR DESCRIPTION
**Pull request by Vercantez**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by gottesmm** [comment]
LGTM

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
Ah. @Vercantez, this is the wrong branch. I thought you were committing this to master. Please change this PR to be against master instead of 4.1.

**Comment by Vercantez** [comment]
My mistake, I mistakenly thought I should commit this to 4.1 because it was a new feature. I'll make another PR

**Comment by gottesmm** [comment]
@Vercantez no problem!

**Pull request closed without merging**
