### PR TITLE
Update build-windows-toolchain to build.ps1

### PR DESCRIPTION
**Pull request by compnerd**
build.ps1 is a replacement to build.cmd that has been recently under active development.  This script automates the build, packaging, and testing of a toolchain end-to-end.  It also adds most of the remaining pieces of the toolchain distribution.  It adds new functionality and capability to the script to allow us to control the behaviour of the toolchain.  It also will enable future work to start trying to inject in support for Swift in swiftc.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please build toolchain Windows platform

**Review by tristanlabelle — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/233

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/233

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/233

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/233

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/233

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/233

@swift-ci please test Linux platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/233

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/233

@swift-ci please test Windows platform

**Pull request closed without merging**
