### PR TITLE
[cxx-interop] Do not crash when passing `Bool` as `const T&` parameter

### PR DESCRIPTION
**Pull request by egorzhdan**
The type bridging logic assumed that if a value of type `Swift.Bool` is passed to a Clang function as an argument, then the type of the parameter must be a Clang built-in type (usually `_Bool`). This is not always correct. For instance, the type might be a templated const reference.

rdar://125508505

### CODE REVIEW

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Review by ahatanaka — APPROVED** [review]

**Comment by ahatanaka** [comment]
> This is not always correct. For instance, the type might be a templated const reference.

It crashes when passing a boolean value to a non-template function too. Is that right?

**Comment by fahadnayyar** [comment]
@egorzhdan can you please add these 3 test cases as well (I was seeing crash in these also):

// Case 1 : Non template function.
// C++
bool Set(const bool& value) {
    return true;
}
//Swift
// Set(false)

// Case 2 : Non const ref, non template
// C++
bool Set(bool& value) {
    return true;
}
//Swift
// var x = false
// Set(&x)

// Case 3 : Non const ref, template
template <typename T>
bool Set(T& value) {
    return true;
}
//Swift
// var x = false
// Set(&x)

**Comment by egorzhdan** [comment]
That's right, thanks @ahatanaka @fahadnayyar, I added more tests

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Review by fahadnayyar — APPROVED** [review]

**Pull request merged**
