### PR TITLE
Add tests for spurious API changes

### PR DESCRIPTION
**Pull request by harlanhaskins**
#### What's in this pull request?

A test that checks the swift-api-dump against a known correct dump, to avoid unintended API changes.

Ideally, if an API change is intended, the easiest way to fix the test is to just copy your diffs, wholesale, into the Inputs of this test.

~~@gribozavr or @DougGregor Should this live in `test/`? It takes about 3 minutes to run.~~
#### Resolved bug number: N/A

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by gribozavr** [comment]
I feel like it should be under validation-test, and maybe even a long test.

```
--- /dev/null
+++ b/test/Renaming/check_diffs_appletvos.swift
@@ -0,0 +1,5 @@
+// REQUIRES: OS=macosx
+
+// RUN: mkdir -p %t/Outputs
```

Spurious empty line?

**Comment by harlanhaskins** [comment]
@gribozavr I also moved it to validation-test and added the long_test requirement to it.

**Comment by gparker42** [comment]
Is this test going to break every time the OS API changes?

**Comment by harlanhaskins** [comment]
It is; Maybe there should be a single script to automatically replace the current Inputs with the current API dump?

**Comment by gparker42** [comment]
That won't solve the internal development problems. The engineers and test bots won't all use the exact same SDK version, and it's likely that a single source branch will need to support multiple SDKs sometimes.

Perhaps this can be structured as a dedicated CI test job, directly comparing the outputs of two different Swifts using a single SDK, instead of running inside the existing test machinery?

**Comment by harlanhaskins** [comment]
I think that's fair. Think that's doable, @shahmishal?

**Comment by DougGregor** [comment]
I'd prefer that the reference data live somewhere else, outside the tree.

**Pull request closed without merging**
