### PR TITLE
[WIP] Remove ParameterTypeFlags from ParenType and TupleType

### PR DESCRIPTION
**Pull request by hamishknight**
This will almost certainly be split into a bunch of smaller patches, just want to give it an initial run over the source compat suite.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
@slavapestov Another cleanup you might be interested in :)

**Comment by slavapestov** [comment]
Great stuff!

**Comment by slavapestov** [comment]
It might be worth getting rid of TypeBase::isMaterializable() now, and replacing it with `isLValue() || is<InOutType>()` checks (or in cases where only one of those can happen, simplifying it further). "Materializable" is a bit of jargon we can forget about entirely in that case.

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
@swift-ci please test macOS

**Comment by hamishknight** [comment]
@swift-ci please test compiler performance

**Comment by hamishknight** [comment]
@swift-ci please test compiler performance

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test compiler performance

**Comment by hamishknight** [comment]
@swift-ci please test compiler performance

**Comment by hamishknight** [comment]
@swift-ci please test compiler performance

**Comment by hamishknight** [comment]
Finally got around to re-visiting this, fresh PR: https://github.com/apple/swift/pull/60263

**Pull request closed without merging**
