### PR TITLE
[Sema] Fix a crash when attempting to synthesise raw representable conformance

### PR DESCRIPTION
**Pull request by theblixguy**
This PR fixes a crash when attempting to derive raw representable conformance for an enum which has cases with payloads.

```swift
enum Crash: String {
  case foo
  case bar(String)
    
  static let shared = Crash()
}

extension Crash {
  init() { self = .foo }
}
```

Resolves [SR-10108](https://bugs.swift.org/browse/SR-10108).

### CODE REVIEW

**Comment by theblixguy** [comment]
cc @jrose-apple @xedin @slavapestov

**Comment by jrose-apple** [comment]
Thanks, Suyash! Do we still produce the usual diagnostic about mixing raw values and associated types?

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by theblixguy** [comment]
Yeah, we do!

**Comment by theblixguy** [comment]
Unrelated build failure: `12:09:32 /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/lib/ClangImporter/ClangImporter.cpp:769:23: error: no matching constructor for initialization of 'clang::Preprocessor'`

**Comment by jrose-apple** [comment]
Must have caught it between Duncan's Clang and Swift patches.

@swift-ci Please test

**Comment by jrose-apple** [comment]
…right, it's not just the merge into Clang; it has to propagate from 5.1 to stable.

**Comment by theblixguy** [comment]
@jrose-apple The changes got reverted, so it should be fine now. Could you trigger the CI again? Thanks!

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by theblixguy** [comment]
Oops, I forgot to prefix the RUN args with `not` 😅 @jrose-apple Can you trigger the CI one more time? Sorry!

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
…

@swift-ci Please test macOS

**Comment by jrose-apple** [comment]
This one's probably good to cherry-pick too!

**Comment by theblixguy** [comment]
@jrose-apple Done - https://github.com/apple/swift/pull/23428

**Pull request merged**
