### PR TITLE
Tests for set operations for CharacterSet

### PR DESCRIPTION
**Pull request by MuhammadAnnaqeeb**
Tests for set operations for CharacterSet. 
Tests for  rdar://29474937

Resolves  https://bugs.swift.org/browse/SR-3311 partially, but only  when  rdar://29474937 is fixed.

### CODE REVIEW

**Comment by MuhammadAnnaqeeb** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Review by jrose-apple — CHANGES_REQUESTED** [review]
(marking as just for running tests, not for committing; we should fix the underlying problem)

cc @phausler

**Comment by phausler** [comment]
I think we have a solution for the underlying problem - so happens the Data refactor has exposed some better practices that look like they will address the real issue at hand. The problem is that NSCharacter set can't be fully subclassed outside of Foundation (unless it is for minimal and specific use). The overlay usage is far too general for what it does support. I have a feeling that no amount of small fixes will solve the problems.

I will sync up with Tony on Monday and follow up on this.

**Comment by parkera** [comment]
Yes, I'm already working on a different fix for this. Thanks for the tests, I will try them against my new code to make sure it works.

**Comment by parkera** [comment]
I did run across some other character set equality bugs in Foundation itself while working on this as well (29499644). That's not helping the tests from Swift.

**Comment by MuhammadAnnaqeeb** [comment]
@parkera  You are  welcome.

**Comment by CodaFi** [comment]
@parkera has these tests committed elsewhere and issues are being tracked by the radar.  As this is blocked and hasn't been touched in a year I'm going to close it.

**Pull request closed without merging**
