### PR TITLE
SILVerifier: async functions can be called from async functions only

### PR DESCRIPTION
**Pull request by meg-gupta**
Fixes rdar://66869571

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Review by nate-chandler — APPROVED** [review]

**Comment by meg-gupta** [comment]
LLDB error, trying again

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Pull request merged**
