### PR TITLE
[SR-933] rename flatten to flattened

### PR DESCRIPTION
**Pull request by frootloops**
#### What's in this pull request?

> The 'flatten()' method didn't get the Swift 3 API renaming treatment it should have, to go along with reversed, sorted, joined, etc.

So I renamed the function.

#### Resolved bug number: ([SR-933](https://bugs.swift.org/browse/SR-933))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by gribozavr** [comment]
@dabrahams @moiseev What do you think?  Looks like a good change to me, but unfortunately, requires a short proposal on swift-evolution.

**Comment by moiseev** [comment]
:+1:
Perhaps `s/FlattenSequence/FlattenedSequence` as well, for completeness.

**Comment by frootloops** [comment]
@moiseev @gribozavr don't you think now we have to rename them all (mapped, filtered, flatMapped, reduced, and flattened) ?

**Comment by moiseev** [comment]
@frootloops not really. The type prefix so far matches the function name. `ReversedCollection` and `reversed()` for example.

**Comment by frootloops** [comment]
@moiseev @gribozavr Ok. What we gonna do with this pull request?

**Pull request closed without merging**
