### PR TITLE
[SILOptimizer] Fix a bug in edge-splitting wherein we did not create a new phi argument for blocks

### PR DESCRIPTION
**Pull request by shajrawi**
Exposed in stack promotion / when doing stack nesting

rdar://problem/48603037

### CODE REVIEW

**Comment by shajrawi** [comment]
@swift-ci Please test and merge

**Comment by shajrawi** [comment]
I can't merge to 5.1 due to unrelated failure:
```
/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.1-branch/swift-syntax/Sources/SwiftSyntax/SyntaxParser.swift:31:25: error: use of undeclared type 'swiftparser_diagnostic_t'
15:02:16 typealias CDiagnostic = swiftparser_diagnost
```

**Comment by stephentyrone** [comment]
@swift-ci Please test and merge

**Comment by shajrawi** [comment]
@swift-ci Please test macOS

**Pull request merged**
