### PR TITLE
Add buildbot profile for cross-compiling for linux-armv7 using external sysroot

### PR DESCRIPTION
**Pull request by xtremekforever**
- **Explanation**:
     Added new buildbot profiles that allow cross-compiling Swift 5.10 for linux-armv7. This provides 2 different build steps that must be performed to cross compile:

     - `buildbot_linux_crosscompile_armv7,llvm`
     - `buildbot_linux_crosscompile_armv7,stdlib,corelibs`

    The first step is required to get some sort of llvm-linux-x86_64 directory created in the buildbot_linux_armv7 directory, which is required for the rest of the build.

    This does require an external sysroot to be provided, but I created a guide on my blog how to do this, and also how to use the buildbot profiles: https://medium.com/@jesselzamora/cross-compiling-swift-5-10-1-for-linux-armv7-b15986c0f1bf. 

  - **Scope**:
    This mostly adds the new buildbot profiles, but also fixes an issue that prevented cross compilation starting in Swift 5.10, as well as tweaking the hardcoded `--gcc-toolchain` that prevented an external sysroot from being used to compile CXX interop modules.

    I also had to patch the `COMMON_SWIFT_FLAGS` that are passed to `-DCMAKE_Swift_FLAGS` since it was including extra quotes that made any usage of `common-swift-flags=` in the build-presets.ini file crash and burn when building libdispatch, foundation, etc.
  - **Issues**:
    - Cross compilation issue: #75341
    - CXX Interop issue: #75344
  - **Original PRs**:
     - release/5.10
  - **Risk**:
    As far as I can tell these changes should NOT negatively impact other builds, but we need to run the CIs against it.
  - **Testing**:
    All the existing CIs should be run against this to make sure that nothing was broken, especially with the CXX interop patch. 
      I tested all of this on a Raspberry Pi 3B+ running Raspberry Pi OS 12 (32-bit) and it all works great. This should be able to be replicated on other Pis and other people's systems. I did not try building these profiles on a macOS host- just on Ubuntu and Debian hosts with the correct dependencies installed.
  - **Reviewers**:
    - @MaxDesiatov 

Please feel free to suggest better ways to do things here. I did spend a lot of time figuring out what *doesn't work* but if there are other ways this can be improved and still work, I'm all ears.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@xtremekforever IIUC 5.10 is no longer taking patches in, and generally any changes have to land on `main` first, so I'm not sure if we can proceed with this PR.

**Comment by xtremekforever** [comment]
@MaxDesiatov in that case I can replicate this on `main` then, no problem...

**Comment by MaxDesiatov** [comment]
> EDIT: If we PR to main and it's accepted, is there a chance of it being able to eventually make it into release/6.0 since it hasn't been released yet?

To 6.0 yes, but the window is very short and closing down.

**Comment by xtremekforever** [comment]
@MaxDesiatov I wasn't able to get it building with `main` since some source files appeared to not cross compile due to not being able to find headers in the sysroot. It seems like a much deeper investigation to get this working on `main`, and it's a much faster moving target.

However, the latest 6.0 snapshot works perfectly fine when I cross compile it from armv7 with the buildbot. I would like to instead try to get this into release/6.0 since the changes are small- maybe it would be considered then.

**Pull request closed without merging**
