### PR TITLE
[AutoDiff] [stdlib] Switch to '@differentiating' as much as possible.

### PR DESCRIPTION
**Pull request by rxwei**
`@differentiable(vjp: ...)` will be deprecated as soon as we support parameter selection and generic constraints with retroactive derivative registration (`@differentiating(...)`).

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Review by dan-zheng — APPROVED** [review]

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
Aha, right, this thing didn't have libSyntax support yet.

**Comment by dan-zheng** [comment]
Retriggering tests.
Syntax support for `@differentiating` added in https://github.com/apple/swift/pull/23340.
Differentiation parameter inference fixed in https://github.com/apple/swift/pull/23350.

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
Working on the final fix for things to compile!
(serialization of `AutoDiffParameterIndices` for `@differentiating` attribute)

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow linux

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow gpu

**Comment by rxwei** [comment]
Exciting!

**Pull request merged**
