### PR TITLE
[cxx-interop] Do not crash for `static operator()`

### PR DESCRIPTION
**Pull request by egorzhdan**
This is a cherry-pick of https://github.com/swiftlang/swift/pull/75907 since this issues has started occurring in `main` as well as `rebranch`.

### CODE REVIEW

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Review by compnerd — APPROVED** [review]
Thanks! This looks good to me, though I do wonder if we can run into additional cases outside of the `static operator ()` where we need to elide the `this` pointer.

**Review by hyp — APPROVED** [review]

**Review by hyp — COMMENTED** [review]
EDIT: NVM this was my fault, I only cherry-picked the last commit. This should work!

> Actually I just tested this with the windows build, and this patch doesn't fix the crash we see with MSVC's operator () specifically, so my patch is still needed probably. I'm doing another test round right now to confirm

**Comment by egorzhdan** [comment]
Awesome, thanks a lot for confirming @hyp!

**Comment by hyp** [comment]
I validated this fully, this works. Thanks again!

**Pull request merged**
