### PR TITLE
StringOptimization: bug fixes

### PR DESCRIPTION
**Pull request by eeckstein**
Fix some bugs in the optimization and in the test files.

rdar://problem/66283894

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci smoke test and merge

**Comment by compnerd** [comment]
Hey @eeckstein this seems to have caused some regressions on the Windows builder: https://ci-external.swift.org/job/oss-swift-windows-x86_64-vs2019/2289/consoleText

Could you please take a look?

**Comment by eeckstein** [comment]
Thanks. I'll fix it asap.
(I'm wondering why this didn't show up in the linux pr testing)

**Comment by eeckstein** [comment]
https://github.com/apple/swift/pull/33204

**Comment by compnerd** [comment]
Thanks!

**Pull request merged**
