### PR TITLE
Use a SmallVector rather than SmallDenseMap to hold solver scopes.

### PR DESCRIPTION
**Pull request by rudkx**
The vector makes more sense given these follow a stack discipline.

NFC.

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test and merge

**Comment by rudkx** [comment]
@adrian-prantl Adrian, does this look familiar?

https://ci.swift.org/job/swift-PR-osx-smoke-test/5744/consoleFull#-782349436c38edd5a-00f9-40a2-abac-1db59f7a90ca

```
!dbg attachment points at wrong subprogram for function
!19898 = distinct !DISubprogram(name: "replaceSubrange", linkageName: "_TFVs15ContiguousArray15replaceSubrangeuRxzWd__8Iterator7Element_d__s10CollectionrfTGVs5RangeSi_4withqd___T_", scope: !2, file: !25, type: !19899, isLocal: false, isDefinition: true, isOptimized: true, unit: !39, variables: !6)
void (i64, i64, %swift.opaque*, %swift.type*, %swift.type*, i8**, %Ts15ContiguousArrayV*)* @_TFVs15ContiguousArray15replaceSubrangeuRxzWd__8Iterator7Element_d__s10CollectionrfTGVs5RangeSi_4withqd___T_
  %85 = bitcast { %swift.type* }* %8 to i8*, !dbg !19948
!19948 = !DILocation(line: 0, scope: !18991)
!18991 = distinct !DISubprogram(linkageName: "_TMaVs22_ContiguousArrayBuffer", scope: !2, file: !25, type: !164, isLocal: false, isDefinition: true, flags: DIFlagArtificial, isOptimized: true, unit: !39, variables: !6)
!18991 = distinct !DISubprogram(linkageName: "_TMaVs22_ContiguousArrayBuffer", scope: !2, file: !25, type: !164, isLocal: false, isDefinition: true, flags: DIFlagArtificial, isOptimized: true, unit: !39, variables: !6)
Assertion failed: (!V->hasBrokenDebugInfo() && "Module contains invalid debug info"), function doFinalization, file /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/llvm/lib/IR/Verifier.cpp, line 4535.
0  swift                    0x00000001062f2158 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 40
1  swift                    0x00000001062f2806 SignalHandler(int) + 454
2  libsystem_platform.dylib 0x00007fff9ec85bba _sigtramp + 26
3  libsystem_platform.dylib 000000000000000000 _sigtramp + 1631036512
4  libsystem_c.dylib        0x00007fff9eb0c420 abort + 129
5  libsystem_c.dylib        0x00007fff9ead3893 basename_r + 0
6  swift                    0x0000000106247f19 (anonymous namespace)::VerifierLegacyPass::doFinalization(llvm::Module&) + 185
7  swift                    0x00000001061c4860 llvm::FPPassManager::doFinalization(llvm::Module&) + 80
8  swift                    0x00000001061c4d9d llvm::legacy::PassManagerImpl::run(llvm::Module&) + 1261
9  swift                    0x000000010363e238 swift::performLLVMOptimizations(swift::IRGenOptions&, llvm::Module*, llvm::TargetMachine*) + 1912
10 swift                    0x000000010363eebd swift::performLLVM(swift::IRGenOptions&, swift::DiagnosticEngine*, llvm::sys::SmartMutex<false>*, llvm::GlobalVariable*, llvm::Module*, llvm::TargetMachine*, swift::version::Version const&, llvm::StringRef) + 2765
11 swift                    0x00000001034fcbd6 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 15654
12 swift                    0x00000001034b88c0 main + 3168
13 libdyld.dylib            0x00007fff9ea78255 start + 1
```

**Comment by rudkx** [comment]
@swift-ci Please smoke test OS X platform

**Comment by adrian-prantl** [comment]
Yes, I cherry-picked a couple of LLVM changes today and one of them uncovered this bug. I reverted them for now.

**Pull request merged**
