### PR TITLE
[sil] Rename SILBasicBlock::getParent() -> getFunction().

### PR DESCRIPTION
**Pull request by gottesmm**
This is a refactoring that we have talked about for a while with an eye towards
providing a consistent name across all IR constructs for getting its
corresponding SILFunction (if it has one).

This refactoring was done using Xcode's refactoring engine. I then
git-clang-formatted the result and eliminated a couple of places where
clang-format didn't do a good job with ternary operations.

### CODE REVIEW

**Comment by gottesmm** [comment]
@atrick as you requested. I used Xcode's refactoring support.

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
... and it looks like the dom tree impl requires this.

**Comment by gottesmm** [comment]
Yes. We will need to add some sort of indirection upstream. Check this:

**Comment by gottesmm** [comment]
```
  static_assert(std::is_pointer<typename GraphTraits<NodeT *>::NodeRef>::value,
                "Currently DominatorTreeBase supports only pointer nodes");
  using NodeType = NodeT;
  using NodePtr = NodeT *;
  using ParentPtr = decltype(std::declval<NodeT *>()->getParent());
  static_assert(std::is_pointer<ParentPtr>::value,
                "Currently NodeT's parent must be a pointer type");
  using ParentType = typename std::remove_pointer<ParentPtr>::type;
```

Taken from the impl in GenericDomTree.h.

**Comment by gottesmm** [comment]
Really it should be using pointer like type traits and perhaps add something that describes the parent type to graph traits.

**Review by atrick — APPROVED** [review]
I like this, except we can't get rid of `getParent`. LLVM data types need a `getParent()` but it doesn't need to return a `SILFunction`. It could be any `SILBasicBlock` container that supports `front()` to get the entry block. The hurdle is that `std::is_pointer<ParentPtr>` also needs to be true. Or, we can assert that `getParent` is never called for static initializers, and therefore static initializers don't have a domtree. And of course there's the option of changing LLVM's `is_pointer` check. I'm not sure what's best without investigating deeper.

**Comment by gottesmm** [comment]
@atrick same. I was thinking of doing the dom-tree wrapper, but the is_pointer check got in the way. That being said, I don't understand why it isn't using PointerLikeTypeTraits

**Comment by gottesmm** [comment]
Going to close this until we fix something upstream.

**Pull request closed without merging**
