### PR TITLE
Simplify accessed storage proj

### PR DESCRIPTION
**Pull request by atrick**
Replace AccessedStorage projection with an index.
    
Further simplify AccessedStorage. Shrink it to two words. Remove the
Projection abstraction and streamline the projection logic.

There is only one new commit here "Replace AccessedStorage projection with an index". The previous commits build on previous PRs.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test.

**Review by shajrawi — APPROVED** [review]
LGTM

**Comment by atrick** [comment]
@swift-ci smoke test

**Comment by atrick** [comment]
@swift-ci smoke test and merge

**Comment by atrick** [comment]
@swift-ci smoke test and merge

**Pull request merged**
