### PR TITLE
Add a new mandatory optimization pass for unrolling forEach calls over arrays created from array literals.

### PR DESCRIPTION
**Pull request by ravikandhadai**
This enables optimizing further the output of the OSLogOptimization pass, and results in highly-compact and optimized IR for calls to the new os log API. Some examples of the optimized IR that would be generated for the new os log calls is available in the new test suite: `test/SILOptimizer/OSLogPrototypeFullOptTest.swift`. 

This PR has two commits. The latest commit (f40d225) has changes specific to this PR  and the previous commit is a minor extension to the ArraySemantics.h and refactoring of a utility function, which is discussed separately in this PR: https://github.com/apple/swift/pull/29643. 

The new mandatory optimization is implemented in the file: `lib/SILOptimizer/LoopTransforms/ForEachLoopUnroll.cpp`. This optimization is added before the MandatoryCombine pass in the pass pipeline.

<rdar://58928427>

### CODE REVIEW

**Comment by ravikandhadai** [comment]
@swift-ci Please test

**Comment by ravikandhadai** [comment]
@swift-ci Please benchmark

**Comment by ravikandhadai** [comment]
@swift-ci Please benchmark

**Comment by ravikandhadai** [comment]
@swift-ci Please test

**Comment by ravikandhadai** [comment]
@swift-ci Please test

**Comment by ravikandhadai** [comment]
@swift-ci Please test

**Comment by ravikandhadai** [comment]
@swift-ci Please test

**Comment by ravikandhadai** [comment]
@atrick I have rebased the PR on master since the commit this PR was depending on has been merged. Now, there is only one commit in this PR which has the relevant changes. I have also added more comments to the code. In particular, I have added an overview of the algorithm.

**Comment by ravikandhadai** [comment]
@swift-ci Please test macOS platform

**Comment by ravikandhadai** [comment]
@swift-ci Please test macOS Platform

**Review by atrick — APPROVED** [review]
This looks really nice and very very thorough!

Just some thoughts... I'm always wary of adding borrow scopes. I think they will interfere with later optimization. The alternative is allocating sufficient stack space for all the elements. All those extra copies will end up needing stack space anyway if the array is large, and the total number of stores will be the same either way. If you just immediately store into the stack, you don't need any copies or borrows.

**Comment by ravikandhadai** [comment]
Thanks @atrick. I see your point regarding borrow scopes. I will make that change.

**Comment by ravikandhadai** [comment]
@swift-ci Please test and merge

**Comment by ravikandhadai** [comment]
@swift-ci Please test and merge

**Comment by ravikandhadai** [comment]
@swift-ci Please test macOS platform

**Comment by ravikandhadai** [comment]
@swift-ci Please test and merge

**Comment by ravikandhadai** [comment]
@swift-ci Please test and merge

**Comment by ravikandhadai** [comment]
@swift-ci Please test

**Comment by ravikandhadai** [comment]
@swift-ci Please test macOS Platform

**Pull request merged**
