### PR TITLE
Add reduced crasher for SR-7958

### PR DESCRIPTION
**Pull request by beccadax**
Trying to use an argument label in an interpolation can cause various crashes. In swiftlang-1000.0.16.7, these are usually in SILGen; in master at 8f6028d, they’re in CSApply.

The file includes two samples. In swiftlang-1000.0.16.7, the first crashes in exactly the same place as the code snippet in [SR-7958](https://bugs.swift.org/browse/SR-7958), while the second crashes elsewhere in SILGen. In master at 8f6028d, they both seem to crash in the same place.

### CODE REVIEW

**Comment by brentdax** [comment]
@CodaFi

**Comment by CodaFi** [comment]
LGTM.  You can merge this first and rebase your fix PR after running the fix compiler crashers script or merge the fix first and run the script here.

**Comment by brentdax** [comment]
@CodaFi Should be fixed now. I didn't realize crasher tests passed by still crashing!

**Review by CodaFi — APPROVED** [review]
⛵️

**Comment by CodaFi** [comment]
@swift-ci test and merge

**Pull request merged**
