### PR TITLE
Debug Info: Encode let-bindings using DW_TAG_const_type.

### PR DESCRIPTION
**Pull request by adrian-prantl**
This allows the debugger to distinguish constant "let" values from mutable "var" variables.
    
rdar://problem/16042546

### CODE REVIEW

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-lldb/pull/2015

**Comment by adrian-prantl** [comment]
Sorry for the long patch, it will get shorter, once https://github.com/apple/swift/pull/27238 has landed.

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-lldb/pull/2015
@swift-ci test

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-lldb/pull/2015
@swift-ci test

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-lldb/pull/2015
@swift-ci test

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-lldb/pull/2015
@swift-ci test

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift-lldb/pull/2015
@swift-ci test

**Review by dcci — APPROVED** [review]
The compiler bits look good to me.

**Pull request merged**
