### PR TITLE
[ClosureLifetimeFixup] Dealloc args on frontier.

### PR DESCRIPTION
**Pull request by nate-chandler**
Previously, the `dealloc_stack`s created for the `alloc_stack`s used to pass `@in_guaranteed` arguments to `on_stack` closures were created after the users of the closure.  When SILGen created these `alloc_stack`s in the same block as the users, this happened to work.  Now that AddressLowering creates such `alloc_stack`s elsewhere, this approach results in invalid SIL.

Here, the `dealloc_stack`s are instead at the end of each block in the dominance frontier of the `alloc_stack`.

Based on https://github.com/apple/swift/pull/62082 .

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by atrick — APPROVED** [review]
LGTM. Hopefully this fix works. It's an overall improvement. But if this fix is too problematic, we could say that AddressLowering must run after ClosureLifetimeFixup.

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Pull request merged**
