### PR TITLE
[StdlibUnittest] Make output for expected crashes less fatalistic

### PR DESCRIPTION
**Pull request by harlanhaskins**
#### What's in this pull request?

A small change that disables printing stderr for expected crashes in StdlibUnittest

For example:

``` swift
$ cat t.swift 
import StdlibUnittest

TestSuite("Foo").test("bar") {
  expectCrashLater()
  assert(false)
}
runAllTests()
```

Would print:

```
$ ./t 
[ RUN      ] Foo.bar
err>>> assertion failed: file t.swift, line 6
err>>> CRASHED: SIGILL
[       OK ] Foo.bar
```

Which is problematic, because at a glance it looks like a failure.
With this change, it prints:

```
$ ./t 
[ RUN      ] Foo.bar
[       OK ] Foo.bar
```

#### Resolved bug number: rdar://18081448

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by harlanhaskins** [comment]
@benlangmuir

**Comment by gribozavr** [comment]
I tend to disagree... you really want all output possible from the CI in the log.

I'd rather have us look for better way to present the information.

**Comment by benlangmuir** [comment]
Some suggestions off the top of my head for improving presentation:
* Don't prefix with "err>>>".  That makes it sound like an error.
* Replace CRASHED: SIGILL with something like "OK: saw expected crash sigill"

If we can make the most important information (did it pass) more obvious and the less frequently used information (what was printed to stderr when it crashed even though we expected the crash) less LOUD in the output I think it would go along way.

**Comment by gribozavr** [comment]
> Don't prefix with "err>>>". That makes it sound like an error.

We can replace "err>>>" with "stderr>>>", that's what it is supposed to stand for.

> Replace CRASHED: SIGILL with something like "OK: saw expected crash sigill"

Good idea!

**Comment by harlanhaskins** [comment]
I agree with all of that. Updated that (and the requisite tests)

**Comment by benlangmuir** [comment]
LGTM

**Comment by benlangmuir** [comment]
@swift-ci Please test

**Comment by gribozavr** [comment]
LGTM!

**Comment by gribozavr** [comment]
Thanks @harlanhaskins!

**Pull request merged**
