### PR TITLE
ARC code motion: handle unowned retains/releases correctly.

### PR DESCRIPTION
**Pull request by eeckstein**
This fixes an assert-crash in the ReleaseHoisting pass.

rdar://problem/40525543

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@eeckstein you never describe what the actual error was in the commit message. Why was it crashing?

**Comment by eeckstein** [comment]
It was crashing with this assert:

Assertion failed: (isRetainInstruction(I) || isReleaseInstruction(I) && "Extracting RC root from invalid instruction"), function getRCRoot, file /Users/erik/proj/swift-work/swift/lib/SILOptimizer/Transforms/ARCCodeMotion.cpp, line 193.

because the check for unowned ARC instructions was missing.

**Comment by gottesmm** [comment]
Thanks!

**Pull request merged**
