### PR TITLE
Update prefix-drop regression test

### PR DESCRIPTION
**Pull request by CodaFi**
Updates the regression test and provides us an opportunity to benchmark the prefix-drop optimization change.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci benchmark

**Comment by CodaFi** [comment]
@swift-ci benchmark

**Comment by CodaFi** [comment]
@swift-ci benchmark

**Comment by CodaFi** [comment]
@dabrahams Just as I suspected: No measurable (benchmarkable?) impact.

**Comment by dabrahams** [comment]
@swift-ci Please smoke test and merge

**Comment by CodaFi** [comment]
@swift-ci please python lint

**Comment by CodaFi** [comment]
@swift-ci please smoke test and merge

**Comment by CodaFi** [comment]
(Merge [happening here](https://ci.swift.org/job/swift-PR-smoke-merge/2229/))

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
⛵️

**Comment by dabrahams** [comment]
@CodaFi what does the sailboat mean?

**Comment by CodaFi** [comment]
Some people use 🚢 (`:ship:`) or :shipit: (`:shipit:`) to signal a merge.  I just like ⛵️ (`:boat:`) better is all.

**Comment by palimondo** [comment]
@CodaFi I'm curious, how should the change in **validation-test** provide
> an opportunity to benchmark the prefix-drop optimization change

? 🤷‍♂️ It seems inevitable that it provides
>  No measurable (benchmarkable?) impact.

Was this commit missing some parts?

**Comment by CodaFi** [comment]
We couldn't get the benchmark build to work on the 3.1 release branch, so this pull request allowed me to kill two birds with one stone by demonstrating no regression in performance by making the change as well as fix the test.

**Pull request merged**
