### PR TITLE
Sema: Don't report ambiguities on an explicitly public import

### PR DESCRIPTION
**Pull request by xymus**
Silence errors on ambiguous implicitly public imports when a different import is explicitly public. In this case all imports are public so the ambiguity is not dangerous and this configuration can happen during adoption of access-levels on imports. Keep the error when an explicit import is `package`, `internal` or below.

rdar://129037503

### CODE REVIEW

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Review by tshortli — APPROVED** [review]

**Review by nkcsgexi — APPROVED** [review]
Thank you!

**Comment by nkcsgexi** [comment]
This should be safe enough to cherry pick to swift 6. Could you do that?

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Pull request merged**
