### PR TITLE
[sil-opt] Add a new option -disable-sil-linking to dump swiftmodules "as is"

### PR DESCRIPTION
**Pull request by swiftix**
Usually, if you use `sil-opt my.swiftmodule` it would dump a lot of SIL, because it would try to link external SIL functions linked by the module (e.g. functions from the standard library) and dump them as well.

The new option allows for dumping only the SIL contained in the swiftmodule. This is very useful if you want to inspect the content of a swiftmodule.

### CODE REVIEW

**Comment by swiftix** [comment]
@gottesmm @atrick I think such an option is handy. Or is it possible by means of a different option already?

**Comment by gottesmm** [comment]
Can you add it to sil-func-extractor as well? It may be good to make this the default behavior there actually.

**Comment by atrick** [comment]
@swiftix: interesting. I hadn't really noticed this with unit tests, but it does seem like a useful option.

**Comment by swiftix** [comment]
@gottesmm Here you go! :-)

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Comment by swiftix** [comment]
@swift-ci please smoke test

**Pull request merged**
