### PR TITLE
[stdlib] add more debug-mode range checking to UnsafeBufferPointer

### PR DESCRIPTION
**Pull request by glessard**
Adds `_debugPrecondition` calls to `_failEarlyRangeCheck` in `Unsafe{Mutable}BufferPointer`.

`_failEarlyRangeCheck` in `Slice` forwards to its Base. In the case of the UnsafeBufferPointers, that is an empty function. This means that one can use a Slice to get or set to any index of its base BufferPointer, not limited to the indices in the slice's `startIndex..<endIndex` range. While this is fine in release mode, this is surprising in debug mode, where the UnsafeBufferPointers do perform some range checking.

Should be merged after https://github.com/apple/swift/pull/12504

Resolves [SR-6549](https://bugs.swift.org/browse/SR-6549).

### CODE REVIEW

**Comment by glessard** [comment]
Ping @lorentey

**Comment by lorentey** [comment]
@swift-ci Please smoke test

**Comment by lorentey** [comment]
@swift-ci Please benchmark

**Comment by lorentey** [comment]
@swift-ci please benchmark OS X platform

**Comment by lorentey** [comment]
@swift-ci Please smoke test

**Comment by lorentey** [comment]
The benchmarks look just fine! I think this is ready to merge after #12504, so 
we can remove the cherry-picked commit.

**Comment by glessard** [comment]
Cool! I removed the cherry-picked commits from this branch. Thanks for your help

**Comment by glessard** [comment]
@lorentey thanks for merging https://github.com/apple/swift/pull/12504; this one should be ready too

**Comment by lorentey** [comment]
@swift-ci test and merge

**Pull request merged**
