### PR TITLE
Experiment: Do not skip disjunction choices unless explicitly disabled.

### PR DESCRIPTION
**Pull request by rudkx**

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by xedin** [comment]
@rudkx I have tried that recently, it breaks a bunch of perf tests

**Comment by rudkx** [comment]
@xedin I’m sure it does. I want to get some logs for several experiments and see what gets slow.

**Comment by rudkx** [comment]
@xedin ...more importantly see what the impact is on the source company suite.

**Comment by xedin** [comment]
@rudkx Sure, some of the project became too complex too unfortunately :(

**Comment by rudkx** [comment]
Interesting. We cannot even build the stdlib. I am pretty sure it built locally, so that's really odd.

**Comment by rudkx** [comment]
```
Failing Tests (14):
    Swift(macosx-x86_64) :: Sema/complex_expressions.swift
    Swift(macosx-x86_64) :: stdlib/FixedPointDiagnostics.swift.gyb
    Swift(macosx-x86_64) :: compiler_crashers/28739-unreachable-executed-at-swift-lib-ast-type-cpp-229.swift
    Swift(macosx-x86_64) :: Sema/type_checker_perf/fast/rdar23327871.swift.gyb
    Swift(macosx-x86_64) :: Sema/type_checker_perf/fast/rdar22836718.swift.gyb
    Swift(macosx-x86_64) :: Sema/type_checker_perf/fast/rdar19738292.swift.gyb
    Swift(macosx-x86_64) :: stdlib/SIMDParameterPassing.swift.gyb
    Swift(macosx-x86_64) :: stdlib/ParameterPassing.swift.gyb
    Swift(macosx-x86_64) :: stdlib/IntegerCompatibility.swift
    Swift(macosx-x86_64) :: expr/expressions.swift
    Swift(macosx-x86_64) :: SILGen/coverage_label.swift
    Swift(macosx-x86_64) :: SILGen/conditionally_unreachable.swift
    Swift(macosx-x86_64) :: Interpreter/binary_operator_perf.swift
    Swift(macosx-x86_64) :: ClangImporter/custom-include.swift
```

**Comment by rudkx** [comment]
We're able to build the standard library in the Linux and macOS smoke test runs, but not on the build used for the source compatibility tests. Very strange.

**Pull request closed without merging**
