### PR TITLE
[SIL Inlining] Extract out a reusable code snippet in PerformanceInliner into a utility function in SILInliner.

### PR DESCRIPTION
**Pull request by ravikandhadai**
This helper function will also be used in the OSLogOptimization.cpp pass available as a PR [here](https://github.com/apple/swift/pull/24336)

### CODE REVIEW

**Comment by ravikandhadai** [comment]
@swift-ci Please test

**Comment by ravikandhadai** [comment]
@swift-ci Please benchmark

**Review by eeckstein — COMMENTED** [review]
Does it make sense to use the new utility function also in MandatoryInlining?

**Comment by ravikandhadai** [comment]
I tried that but the MandatoryInliner is trying to inline even indirect calls like applications of closures (partial-applies) as long as its actual targets are identifiable. There is quite a bit of complexity in the [inlining code](https://github.com/apple/swift/blob/6cd476be47448f6981cedf9c34af95d9c6346ed2/lib/SILOptimizer/Mandatory/MandatoryInlining.cpp#L835) because of that and doesn't seem easy to unify with this. The way it is computing the callee function, arguments, SubstitutionMap and OpenedArchetypesTracker are quite different to handle partial applies.

**Review by eeckstein — APPROVED** [review]
lgtm!

**Pull request merged**
