### PR TITLE
[gardening] Use the idiomatic convention of naming unused variables "_"

### PR DESCRIPTION
**Pull request by practicalswift**

### CODE REVIEW

**Comment by practicalswift** [comment]
@jrose-apple Good point - I've now re-introduced `testName` and `itersComputed` as per your suggestion. Please let me know if any further changes are needed.

**Comment by jrose-apple** [comment]
I'm just not sure how far that goes. We use _ in Swift too, but sometimes it's good documentation to say what you're ignoring.

**Comment by practicalswift** [comment]
@jrose-apple If I re-introduce `stderr` (from `p.communicate(…)`) and `dirs` (from `os.walk(…)`), then the remaining changes should be OK? :-)

**Comment by jrose-apple** [comment]
Yeah, those are definitely non-controversial. :-)

**Comment by practicalswift** [comment]
@jrose-apple Pull request updated accordingly :-)

**Comment by jrose-apple** [comment]
Thanks!

**Pull request merged**
