### PR TITLE
SwiftMergeFunction: Rewrite the byval/structret attributes when we bitcast the function type

### PR DESCRIPTION
**Pull request by aschwaighofer**
rdar://101089253

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci test

**Comment by aschwaighofer** [comment]
@swift-ci test source compat

**Review by eeckstein — APPROVED** [review]
lgtm, thanks

**Comment by aschwaighofer** [comment]
@swift-ci test macOS

**Pull request merged**
