### PR TITLE
Merge 'swift-DEVELOPMENT-SNAPSHOT-2018-10-22-a' to 'tensorflow'

### PR DESCRIPTION
**Pull request by rxwei**
This merge is pretty trivial except that we need to change the access level of `SILCloner`'s `ValueMap` and `BBMap` to `protected`, since TF code paths are customizing these two maps ([SR-9085](https://bugs.swift.org/browse/SR-9085)).

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by atrick** [comment]
@rxwei If you're customizing BBMap and ValueMap then you're violating SILCloner's abstraction the same problematic way that many in-tree clients were previously doing. But I could pretty easily show you how to fix your code so you're not doing that. Would that be helpful?

**Comment by rxwei** [comment]
@atrick That would be great. We have four files that are customizing the maps. Could you take a look?

https://github.com/apple/swift/blob/tensorflow/lib/SILOptimizer/Mandatory/TFDifferentiation.cpp
https://github.com/apple/swift/blob/tensorflow/lib/SILOptimizer/Mandatory/TFDevicePartition.cpp
https://github.com/apple/swift/blob/tensorflow/lib/SILOptimizer/Mandatory/TFPartition.cpp
https://github.com/apple/swift/blob/tensorflow/lib/SILOptimizer/Mandatory/TFCanonicalizeCFG.cpp

Some may take quite some effort to fix, so if it's too much work, we'll merge this and fix them next week.

**Review by mhong — APPROVED** [review]
Thanks!

**Comment by atrick** [comment]
I see no reason to hold up this merge. I just don't want to create unnecessary friction for future merges. I'll try to look at these sometime in the next few days.

**Comment by rxwei** [comment]
Cool. Thanks Andy!

**Pull request merged**
