### PR TITLE
Update checkout for tensorflow and swift-apis.

### PR DESCRIPTION
**Pull request by dan-zheng**
https://github.com/tensorflow/tensorflow/commit/f23a914b52d1935602d0a94c426ccab15c8fed69
https://github.com/tensorflow/swift-apis/commit/c09de96f739aa8bfce0c41e19213bd2d7fa9a4ba

### CODE REVIEW

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Review by BradLarson — APPROVED** [review]

**Comment by dan-zheng** [comment]
CI failed:
```
Please upgrade your bazel installation to version 0.27.1 or higher to build TensorFlow!
```

I'll upgrade bazel on the CI machines and retrigger.

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
CI failed on Linux while building TensorFlow:
```
+ bazel build -c opt --define framework_shared_object=false //tensorflow:libtensorflow.so
...
 - /home/swiftci/jenkins/workspace/swift-PR-TensorFlow-Linux/tensorflow/WORKSPACE:19:1
ERROR: An error occurred during the fetch of repository 'local_config_python':
   Traceback (most recent call last):
	File "/home/swiftci/jenkins/workspace/swift-PR-TensorFlow-Linux/tensorflow/third_party/py/python_configure.bzl", line 345
		_create_local_python_repository(<1 more arguments>)
	File "/home/swiftci/jenkins/workspace/swift-PR-TensorFlow-Linux/tensorflow/third_party/py/python_configure.bzl", line 296, in _create_local_python_repository
		_get_numpy_include(<2 more arguments>)
	File "/home/swiftci/jenkins/workspace/swift-PR-TensorFlow-Linux/tensorflow/third_party/py/python_configure.bzl", line 276, in _get_numpy_include
		_execute(repository_ctx, <3 more arguments>)
	File "/home/swiftci/jenkins/workspace/swift-PR-TensorFlow-Linux/tensorflow/third_party/py/python_configure.bzl", line 56, in _execute
		_fail(<1 more arguments>)
	File "/home/swiftci/jenkins/workspace/swift-PR-TensorFlow-Linux/tensorflow/third_party/py/python_configure.bzl", line 27, in _fail
		fail(<1 more arguments>)
Python Configuration Error: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named numpy
```

I verified that installing numpy (`sudo apt-get install python-pip` and `sudo pip install numpy`) fixes the issue.

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow linux

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow linux

**Comment by dan-zheng** [comment]
There's a new linker error for `libswiftTensorFlow.dylib`:
```
[1341/1829][ 73%][1580.361s] Linking CXX shared library lib/swift/macosx/x86_64/libswiftTensorFlow.dylib
FAILED: lib/swift/macosx/x86_64/libswiftTensorFlow.dylib 
: && /Users/swiftci/jenkins/workspace/swift-PR-TensorFlow-macOS/Ninja-ReleaseAssert+stdlib-Release/llvm-macosx-x86_64/./bin/clang++ -Wno-unknown-warning-option -Werror=unguarded-availability-new -fno-stack-protector -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -std=c++14 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-class-memaccess -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -fdiagnostics-color -Werror=switch -Wdocumentation -Wimplicit-fallthrough -Wunreachable-code -Woverloaded-virtual -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -O3 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -dynamiclib -Wl,-headerpad_max_install_names -dynamiclib\ -Wl,-headerpad_max_install_names -Xlinker -compatibility_version -Xlinker 1 -target x86_64-apple-macosx10.9 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -arch x86_64 -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/../../../Developer/Library/Frameworks -mmacosx-version-min=10.9 -Wl,-dead_strip -Wl,-sectcreate,__TEXT,__info_plist,/Users/swiftci/jenkins/workspace/swift-PR-TensorFlow-macOS/Ninja-ReleaseAssert+stdlib-Release/swift-macosx-x86_64/stdlib/public/TensorFlow/Info.plist -Wl,-application_extension  "-L/Users/swiftci/jenkins/workspace/swift-PR-TensorFlow-macOS/Ninja-ReleaseAssert+stdlib-Release/swift-macosx-x86_64/./lib/swift/macosx/x86_64" "-L/Users/swiftci/jenkins/workspace/swift-PR-TensorFlow-macOS/Ninja-ReleaseAssert+stdlib-Release/swift-macosx-x86_64/./bin/../lib/swift/macosx/x86_64" "-L/Users/swiftci/jenkins/workspace/swift-PR-TensorFlow-macOS/Ninja-ReleaseAssert+stdlib-Release/swift-macosx-x86_64/./bin/../lib/swift/macosx" -o lib/swift/macosx/x86_64/libswiftTensorFlow.dylib -install_name @rpath/libswiftTensorFlow.dylib stdlib/public/TensorFlow/OSX/x86_64/TensorFlow.o stdlib/public/CTensorFlow/CMakeFiles/swiftCTensorFlow-macosx-x86_64.dir/ctensorflow_init.cpp.o -L/Users/swiftci/jenkins/workspace/swift-PR-TensorFlow-macOS/Ninja-ReleaseAssert+stdlib-Release/llvm-macosx-x86_64/./lib -Wl,-rpath,/Users/swiftci/jenkins/workspace/swift-PR-TensorFlow-macOS/tensorflow/bazel-bin/tensorflow lib/swift/macosx/x86_64/libswiftSwiftOnoneSupport.dylib lib/swift/macosx/x86_64/libswiftPython.dylib lib/swift/macosx/x86_64/libswiftCore.dylib lib/swift/macosx/x86_64/libswiftDarwin.dylib /Users/swiftci/jenkins/workspace/swift-PR-TensorFlow-macOS/tensorflow/bazel-bin/tensorflow/libtensorflow.so && :
ld: warning: linking against a dylib which is not safe for use in application extensions: /Users/swiftci/jenkins/workspace/swift-PR-TensorFlow-macOS/tensorflow/bazel-bin/tensorflow/libtensorflow.so
ld: warning: linking against a dylib which is not safe for use in application extensions: /Users/swiftci/jenkins/workspace/swift-PR-TensorFlow-macOS/Ninja-ReleaseAssert+stdlib-Release/swift-macosx-x86_64/lib/swift/macosx/libtensorflow.so
Undefined symbols for architecture x86_64:
  "_TF_GraphToFunction", referenced from:
      closure #1 (Swift.UnsafeBufferPointer<Swift.OpaquePointer?>) -> Swift.OpaquePointer in TensorFlow.TFFunction.init(trace: TensorFlow.LazyTensorTrace, name: Swift.String?) -> TensorFlow.TFFunction in TensorFlow.o
  "_TF_FunctionName", referenced from:
      TensorFlow.TFFunction.name.getter : Swift.String in TensorFlow.o
      TensorFlow.TFFunction.execute(_: [TensorFlow.TFETensorHandle], usingXLA: Swift.Bool) -> [TensorFlow.TFETensorHandle] in TensorFlow.o
ld: symbol(s) not found for architecture x86_64
```

@bgogul: do you have any idea why this error occurs?
`TF_GraphToFunction` is still [defined in `tensorflow/c/c_api.h`](https://github.com/tensorflow/tensorflow/blob/f23a914b52d1935602d0a94c426ccab15c8fed69/tensorflow/c/c_api.h#L1097) and doesn't appear to have changed.

**Comment by dan-zheng** [comment]
This patch is obsolete now. Both `tensorflow` and `tensorflow-swift-apis` have been updated in other PRs.

**Pull request closed without merging**
