### PR TITLE
[DO NOT MERGE] Speculative optimization: inline many Iterator.next() impls

### PR DESCRIPTION
**Pull request by dabrahams**
failure to inline an Iterator's next() method has proven to be a very common ARC
optimization barrier.

This creates many indiscriminate @_versioned annotations, so should be carefully reviewed before merging.

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please smoke benchmark

**Comment by palimondo** [comment]
This is exactly what I was seeing in my Mandelbrot benchmark. I was planning to include it to performance test suite. I'm very excited there is work being done on this area!

**Comment by dabrahams** [comment]
Well, the right long-term fix is in the ARC optimizer, not the standard library, but this could produce some immediate wins for code that uses Iterators defined in the standard library.

**Comment by dabrahams** [comment]
Meh; pretty underwhelming.  It's possible one needs larger-scale benchmarks to see the effects.

**Comment by palimondo** [comment]
I'd say those are just measurement noise. I've also observed adding @inline(__always) doesn't help much. I really need to add my Mandelbrot benchmark for you to see what I was seeing there.

BTW I have another potential optimization suggestion. Where's the best place to discuss this?

**Comment by dabrahams** [comment]
I don't know.  Maybe swift-dev?

**Comment by dabrahams** [comment]
Note that because our code is constantly tuned to prevent the benchmarks from regressing, it's very likely that any of the `Iterator.next()` implementations that are critical to benchmarks are already being inlined in the use cases the benchmarks exercise.  So it's not entirely surprising that this has no apparent effect. That's why I'm saying it might be more interesting to see what happens with larger-scale benchmarks.

**Pull request closed without merging**
