### PR TITLE
[Concurrency] Make error logging more robust

### PR DESCRIPTION
**Pull request by drexin**
rdar://104967560

### CODE REVIEW

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Review by artemcm — APPROVED** [review]
Looks good, thanks for the fix!

**Review by ktoso — APPROVED** [review]

**Comment by artemcm** [comment]
@swift-ci smoke test macOS Platform

**Comment by ktoso** [comment]
This was added into https://github.com/apple/swift/pull/63344 which will fix the same issue on 5.8 (the previous state of that PR was not enough to fix). Thank you @drexin for looking into it 🙏

**Pull request merged**
