### PR TITLE
[build-script] Remove extra "cross tools" variable

### PR DESCRIPTION
**Pull request by modocache**
#### What's in this pull request?

We can use one variable here instead of two, in order to make the build script a little easier to read.
#### Resolved bug number: None

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by modocache** [comment]
@gribozavr Friendly ping! The fact that two very similarly named variables exist confuses me every time, including earlier today. :)

**Comment by modocache** [comment]
@swift-ci Please test

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by tkremenek** [comment]
@gribozavr This looks fine to me.  Any concerns?

**Comment by gribozavr** [comment]
LGTM.

**Comment by modocache** [comment]
Great! Thanks.

**Pull request merged**
