### PR TITLE
[silgen] Now that we have destructure, use it in RValue to reduce cop…

### PR DESCRIPTION
**Pull request by gottesmm**
…ies emitted by SILGen.

rdar://43493020

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
... I forgot to stage in a fix...

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Review by jckarter — APPROVED** [review]
Nice cleanup!

**Pull request merged**
