### PR TITLE
SourceKit: Reduce the duplication of key definitions. NFC

### PR DESCRIPTION
**Pull request by nkcsgexi**
We should have a single and unambiguous place to add new keys and request IDs to Sourcekitd.

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by akyrtzi** [comment]
I suggest rename `Keys.def` to `ProtocolUIDs.def`, since it is more general (it also includes requests), otherwise LGTM!

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Pull request merged**
