### PR TITLE
Improved commands with shell syntax

### PR DESCRIPTION
**Pull request by xhpwn**
#### What's in this pull request?

Simple documentation change, adding '$' before in commands, to emulate shell syntax.
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

Added '$' to emulate shell syntax

### CODE REVIEW

**Comment by lattner** [comment]
@gribozavr What do you think about this?  It is traditional, but also hurts copy & pasteability.

**Comment by tkremenek** [comment]
I'm not inclined to take this change.  I don't think it improves readability.  Have we had any complaints about the current form impinging on people understanding README.md?

**Comment by gribozavr** [comment]
This is the traditional way to present shell sessions, so I think this change makes the commands easily recognizable as commands that one needs to type into a terminal.  I don't have a strong opinion about this though.

It would be best if we found a way to add the prompt in a way that it would not get copied to the clipboard.

**Comment by xhpwn** [comment]
@lattner @tkremenek @gribozavr Thank you all for your time reviewing my pull request. I'm really ambitious about getting an internship at Apple next Summer.
@tkremenek, agreed, there are no complaints about readability.
@gribozavr, according to me, the only possible ways of adding the '$' without it copying is to use a small image or the emoji 💲. I've created a repository [here](https://github.com/xhpwn/SwiftDocDemo) demonstrating the same.

**Comment by kurisubrooks** [comment]
By using the emoji you break support for almost every Linux distro without Symbola, leaving only OS X and Windows having support to see the character. Let alone the emoji is larger and looks more out of place than it would as text. Just my thoughts.

**Comment by gribozavr** [comment]
Agreed, I don't think emoji is a good solution.  What I had in mind is some CSS trick (are we allowed to do this in markdown?  how bad would it look like in the source?)

**Comment by kurisubrooks** [comment]
I'm not aware that markdown allows for custom styling, but GitHub flavoured
markdown does allow for HTML snippets, though they also do not allow for
custom styling.

**Comment by CodaFi** [comment]
As the repository vending this branch has been taken down and this patch hasn't been touched in a while, I'm going to close it.

**Pull request closed without merging**
