### PR TITLE
Cleaning up anchor finding in interpolated strings

### PR DESCRIPTION
**Pull request by etcwilde**
The arglist stuff didn't exist when I originally wrote this.
With that, we can knock down the pyramid of dyn-casts and make it look nicer.

### CODE REVIEW

**Comment by etcwilde** [comment]
@swift-ci please test

**Comment by etcwilde** [comment]
Hmm, this isn't doing as much as I was hoping for. There used to be a tower of dyn-casts, but it doesn't look so bad.
The asserts could stay, or could not. If anything needs to go, it's probably just the comment really.
Anyway, I should probably go to bed instead of trying to make decisions at midnight.

**Review by hamishknight — APPROVED** [review]
Makes sense to me if the assertions are no longer needed, I can't say I'm too familiar with this code tho

**Comment by etcwilde** [comment]
@swift-ci please test macOS

**Comment by etcwilde** [comment]
Yeah, I don't think that most of them are necessary anymore.
Most of them were meant to trigger if my assumptions were off about how interpolated strings worked, since that would result in the `await` insertion fix-it being emitted into the wrong location. I haven't heard anything about crashes here or issues with incorrect fix-its in about a year now, so I think it's safe to trim them back. Especially given that the argument list mechanism is more generalized.
We probably could keep the check that `parent` is a `nullptr` though because that would indicate that `isEffectAnchor` is not working correctly.

**Comment by etcwilde** [comment]
@swift-ci please test

**Pull request merged**
