### PR TITLE
Re-instate: "SILPassManager: After a new function is pushed on the stack don't restart the pipeline on the old function."

### PR DESCRIPTION
**Pull request by eeckstein**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

A smoke test on macOS does the following:
1. Builds the compiler incrementally.
2. Builds the standard library only for macOS. Simulator standard libraries and
   device standard libraries are not built.
3. lldb is not built.
4. The test and validation-test targets are run only for macOS. The optimized
   version of these tests are not run.

A smoke test on Linux does the following:
1. Builds the compiler incrementally.
2. Builds the standard library incrementally.
3. lldb is built incrementally.
4. The swift test and validation-test targets are run. The optimized version of these
   tests are not run.
5. lldb is tested.

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci Please smoke test OS X platform

**Comment by shahmishal** [comment]
@swift-ci Please smoke test OS X platform

**Comment by gparker42** [comment]
How did you fix the memory footprint problem? Did you measure the heap size of test Interpreter/enum.swift ?

**Comment by eeckstein** [comment]
The problem was that new functions were created in an infinite loop. So the test did not only consume a huge amount of memory, but it also did not finish compiling at all (if it had infinite available memory).

**Comment by eeckstein** [comment]
@trentxintong that's what I did in 759a05ee2523cf58e90933cc8951e742a2ba2909

**Comment by eeckstein** [comment]
@trentxintong sorry, I didn't notice that your comment was on that commit

**Comment by gparker42** [comment]
I didn't see an infinite loop. I saw the test use 30 GB of memory and then succeed.

**Comment by trentxintong** [comment]
@eeckstein what do you think ? https://github.com/apple/swift/pull/4441

**Comment by eeckstein** [comment]
LGTM

**Comment by eeckstein** [comment]
@gparker42
> I saw the test use 30 GB of memory and then succeed.
Hm, that's strange. Anyway, now it only uses a few MB.

**Pull request merged**
