### PR TITLE
[Index] Add index support for cross import overlays.

### PR DESCRIPTION
**Pull request by nathawes**
Also add a frontend option to skip indexing the stdlib so index tests that pass `-index-system-modules` and aren't interested in the stdlib don't spend a bunch of time indexing it.

Resolves rdar://problem/59445445

### CODE REVIEW

**Comment by nathawes** [comment]
@swift-ci please test

**Review by akyrtzi — APPROVED** [review]

**Comment by nathawes** [comment]
@swift-ci please test

**Comment by nathawes** [comment]
@swift-ci please test and merge

**Comment by nathawes** [comment]
@swift-ci please test

**Pull request merged**
