### PR TITLE
[ownership] Change thin_to_thick function to always produce a none value

### PR DESCRIPTION
**Pull request by gottesmm**
It can already only accept values with none ownership and the merging of
ownership around ownership phis ensure that if we phi this with a partial_apply
or the like, we get the appropriate ownership on any such ownership phi values.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
Looks like some sort of funkiness in Autodiff

**Comment by gottesmm** [comment]
@rxwei can you look at the differentiation part to see if I need to change anything else.

**Comment by gottesmm** [comment]
@adrian-prantl just to double check, the debug info test removal is cool with you?

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test OS X platform

**Review by rxwei — APPROVED** [review]
AutoDiff changes LGTM.

**Review by adrian-prantl — APPROVED** [review]

**Comment by gottesmm** [comment]
Just in case to catch small test perturbations.

**Comment by gottesmm** [comment]
preset=buildbot,tools=RA,stdlib=RD,test=non_executable
@swift-ci Please test with preset macOS

**Pull request merged**
