### PR TITLE
Add benchmarks for withContiguousStorageIfAvailable on bridged NSArrays

### PR DESCRIPTION
**Pull request by Catfish-Man**

### CODE REVIEW

**Comment by Catfish-Man** [comment]
@swift-ci please Apple Silicon benchmark

**Comment by Catfish-Man** [comment]
@swift-ci please Apple Silicon benchmark

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Comment by Catfish-Man** [comment]
@swift-ci please Apple Silicon benchmark

**Review by glessard — APPROVED** [review]

**Pull request merged**
