### PR TITLE
[AST] Use consistent variadic generics terminology.

### PR DESCRIPTION
**Pull request by hborla**
This change renames `SequenceArchetype` to `PackArchetype`, and standardizes on "type parameter pack" instead of "type sequence" across the frontend.

Note that I didn’t change the `@_typeSequence` attribute, because that syntax is temporary anyway.

### CODE REVIEW

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by hborla** [comment]
https://github.com/apple/llvm-project/pull/5423

@swift-ci please smoke test

**Review by slavapestov — APPROVED** [review]

**Comment by hborla** [comment]
https://github.com/apple/llvm-project/pull/5423

@swift-ci please smoke test macOS

**Comment by hborla** [comment]
https://github.com/apple/llvm-project/pull/5423

@swift-ci please smoke test macOS

**Comment by hborla** [comment]
https://github.com/apple/llvm-project/pull/5423

@swift-ci please smoke test macOS

**Comment by slavapestov** [comment]
Holly is out of the office so I'm merging this PR to avoid merge conflicts with my work.

**Pull request merged**
