### PR TITLE
test: define and use `%target-rpath`

### PR DESCRIPTION
**Pull request by compnerd**
Create a new capturing substitution for adding a rpath to a target
library.  This is needed as Windows doesn't really support the concept
of a rpath.  This also makes it possible to remove the parameter from
the command line on windows.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @jrose-apple

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by jrose-apple** [comment]
I feel like we're reaching substitution soup, but I don't have a better answer. Is this *sufficient* to get these tests passing on Windows (because IIRC Windows always searches the executable's directory for DLLs) or do we need to do more?

**Comment by compnerd** [comment]
Yes, the tests are now running, not necessarily passing (there is some bug resulting in a crash, I need to look into that).  But, really, this needs to happen since you are trying to pass linker specific flags through the driver ... you don't know what the underlying linker is going to be.

**Comment by compnerd** [comment]
@jrose-apple - okay, the current failures tend to be coming from unresolved issues in the test harness, not related to this.  AFAICS in the output, the library name issues in the test execution have been fixed with this.

**Review by jrose-apple — APPROVED** [review]

**Pull request merged**
