### PR TITLE
[semantic-sil] Enable the mandatory sil ownership optimization on all…

### PR DESCRIPTION
**Pull request by gottesmm**
… stdlib overlays.

We can do this b/c all overlays pass the ownership verifier, so it is safe.

### CODE REVIEW

**Comment by gottesmm** [comment]
Killing the smoke test jobs.

**Review by shajrawi — APPROVED** [review]

**Comment by gottesmm** [comment]
Part of what is going on here is that when I put in the code to only run on stdlibCore, I forgot that I had already put in an option to turn off/on the mandatory semantic arc opts. I removed the code that checked the stdlib and instead changed to rely on that code.

This will let me via cmake enable this in the appropriate places by putting in the enable-... instead of disabling it in selective places.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Pull request merged**
