### PR TITLE
[DO NOT MERGE] Try to ensure we try to solve BindParam constraints left-to-right.

### PR DESCRIPTION
**Pull request by rudkx**
Builds on https://github.com/apple/swift/pull/11118, but attempts to deal with BindParam constraints differently.

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test

**Comment by rudkx** [comment]
@swift-ci Please smoke test OS X platform

**Comment by xedin** [comment]
@swift-ci please smoke test Linux Platform

**Comment by rudkx** [comment]
@swift-ci Please smoke test OS X platform

**Comment by shahmishal** [comment]
@rudkx Updating CI with new Xcode

**Comment by rudkx** [comment]
I've opened a new PR for my part of this fix: https://github.com/apple/swift/pull/11629

**Pull request closed without merging**
