### PR TITLE
[6.0] Do not install binary swiftmodule for Darwin

### PR DESCRIPTION
**Pull request by edymtt**
**Explanation**: only install swiftinterface for Darwin when building for macOS to support Apple internal configurations
**Radar**: rdar://124390643
**Scope**: build logic that installs the swiftmodules in the final location
**Risk**: low

* this behaviour is opt in, so all other swiftmodules for all supported platforms are not affected
* the additional cleanup was needed to make this change more maintanable in the future, and it does not affect functionality

**Testing**:

* run compatibility suite to ensure adopters are able to use the swiftinterface
* spot checked macOS toolchain to ensure only the Darwin binary swiftmodule was removed
* spot checked Linux toolchain to ensure no binary swiftmodule was removed

**Reviewed By**: Ian Anderson on #72590

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci please test

**Comment by edymtt** [comment]
@swift-ci please test WebAssembly

**Comment by edymtt** [comment]
@swift-ci please build toolchain

**Comment by edymtt** [comment]
@swift-ci Please Test Source Compatibility Release

**Review by ian-twilightcoder — APPROVED** [review]

**Comment by edymtt** [comment]
The failures in the compatibility suite are the same as the [6.0 job](https://ci.swift.org/view/Swift%206.0/job/swift-6.0-source-compat-suite)

**Comment by edymtt** [comment]
Verified that the Linux toolchain has no swiftmodule changes, and the macOS ones does not have the binary swiftmodules for Darwin:

```
> diff -u <(pushd swift-6.0-DEVELOPMENT-SNAPSHOT-2024-03-26-a-ubuntu20.04 > /dev/null && find . -name "*.swiftmodule") <(pushd PR-ubuntu2004-6.0 > /dev/null && find . -name "*.swiftmodule")
> diff -u <(pushd swift-6.0-DEVELOPMENT-SNAPSHOT-2024-03-26-a-osx/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-03-26-a-osx-package.pkg > /dev/null && find . -name "*.swiftmodule") <(pushd swift-PR-72667-1203-osx/Library/Developer/Toolchains/swift-PR-72667-1203.xctoolchain/ > /dev/null && find . -name "*.swiftmodule")
--- /dev/fd/11	2024-03-28 15:15:33
+++ /dev/fd/12	2024-03-28 15:15:33
@@ -72,8 +72,6 @@
 ./usr/lib/swift/appletvsimulator/_StringProcessing.swiftmodule/arm64-apple-tvos-simulator.swiftmodule
 ./usr/lib/swift/appletvsimulator/_StringProcessing.swiftmodule/x86_64-apple-tvos-simulator.swiftmodule
 ./usr/lib/swift/appletvsimulator/Darwin.swiftmodule
-./usr/lib/swift/appletvsimulator/Darwin.swiftmodule/arm64-apple-tvos-simulator.swiftmodule
-./usr/lib/swift/appletvsimulator/Darwin.swiftmodule/x86_64-apple-tvos-simulator.swiftmodule
 ./usr/lib/swift/appletvsimulator/RegexBuilder.swiftmodule
 ./usr/lib/swift/appletvsimulator/RegexBuilder.swiftmodule/arm64-apple-tvos-simulator.swiftmodule
 ./usr/lib/swift/appletvsimulator/RegexBuilder.swiftmodule/x86_64-apple-tvos-simulator.swiftmodule
@@ -126,8 +124,6 @@
 ./usr/lib/swift/watchos/_StringProcessing.swiftmodule/arm64_32-apple-watchos.swiftmodule
 ./usr/lib/swift/watchos/_StringProcessing.swiftmodule/armv7k-apple-watchos.swiftmodule
 ./usr/lib/swift/watchos/Darwin.swiftmodule
-./usr/lib/swift/watchos/Darwin.swiftmodule/arm64_32-apple-watchos.swiftmodule
-./usr/lib/swift/watchos/Darwin.swiftmodule/armv7k-apple-watchos.swiftmodule
 ./usr/lib/swift/watchos/RegexBuilder.swiftmodule
 ./usr/lib/swift/watchos/RegexBuilder.swiftmodule/arm64_32-apple-watchos.swiftmodule
 ./usr/lib/swift/watchos/RegexBuilder.swiftmodule/armv7k-apple-watchos.swiftmodule
@@ -168,8 +164,6 @@
 ./usr/lib/swift/iphoneos/_StringProcessing.swiftmodule/arm64e-apple-ios.swiftmodule
 ./usr/lib/swift/iphoneos/_StringProcessing.swiftmodule/arm64-apple-ios.swiftmodule
 ./usr/lib/swift/iphoneos/Darwin.swiftmodule
-./usr/lib/swift/iphoneos/Darwin.swiftmodule/arm64e-apple-ios.swiftmodule
-./usr/lib/swift/iphoneos/Darwin.swiftmodule/arm64-apple-ios.swiftmodule
 ./usr/lib/swift/iphoneos/RegexBuilder.swiftmodule
 ./usr/lib/swift/iphoneos/RegexBuilder.swiftmodule/arm64e-apple-ios.swiftmodule
 ./usr/lib/swift/iphoneos/RegexBuilder.swiftmodule/arm64-apple-ios.swiftmodule
@@ -206,7 +200,6 @@
 ./usr/lib/swift/appletvos/_StringProcessing.swiftmodule
 ./usr/lib/swift/appletvos/_StringProcessing.swiftmodule/arm64-apple-tvos.swiftmodule
 ./usr/lib/swift/appletvos/Darwin.swiftmodule
-./usr/lib/swift/appletvos/Darwin.swiftmodule/arm64-apple-tvos.swiftmodule
 ./usr/lib/swift/appletvos/RegexBuilder.swiftmodule
 ./usr/lib/swift/appletvos/RegexBuilder.swiftmodule/arm64-apple-tvos.swiftmodule
 ./usr/lib/swift/appletvos/Observation.swiftmodule
@@ -242,9 +235,6 @@
 ./usr/lib/swift/watchsimulator/_StringProcessing.swiftmodule/i386-apple-watchos-simulator.swiftmodule
 ./usr/lib/swift/watchsimulator/_StringProcessing.swiftmodule/arm64-apple-watchos-simulator.swiftmodule
 ./usr/lib/swift/watchsimulator/Darwin.swiftmodule
-./usr/lib/swift/watchsimulator/Darwin.swiftmodule/x86_64-apple-watchos-simulator.swiftmodule
-./usr/lib/swift/watchsimulator/Darwin.swiftmodule/i386-apple-watchos-simulator.swiftmodule
-./usr/lib/swift/watchsimulator/Darwin.swiftmodule/arm64-apple-watchos-simulator.swiftmodule
 ./usr/lib/swift/watchsimulator/RegexBuilder.swiftmodule
 ./usr/lib/swift/watchsimulator/RegexBuilder.swiftmodule/x86_64-apple-watchos-simulator.swiftmodule
 ./usr/lib/swift/watchsimulator/RegexBuilder.swiftmodule/i386-apple-watchos-simulator.swiftmodule
@@ -294,8 +284,6 @@
 ./usr/lib/swift/macosx/_StringProcessing.swiftmodule/arm64-apple-macos.swiftmodule
 ./usr/lib/swift/macosx/_StringProcessing.swiftmodule/x86_64-apple-macos.swiftmodule
 ./usr/lib/swift/macosx/Darwin.swiftmodule
-./usr/lib/swift/macosx/Darwin.swiftmodule/arm64-apple-macos.swiftmodule
-./usr/lib/swift/macosx/Darwin.swiftmodule/x86_64-apple-macos.swiftmodule
 ./usr/lib/swift/macosx/RegexBuilder.swiftmodule
 ./usr/lib/swift/macosx/RegexBuilder.swiftmodule/arm64-apple-macos.swiftmodule
 ./usr/lib/swift/macosx/RegexBuilder.swiftmodule/x86_64-apple-macos.swiftmodule
@@ -404,8 +392,6 @@
 ./usr/lib/swift/iphonesimulator/_StringProcessing.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
 ./usr/lib/swift/iphonesimulator/_StringProcessing.swiftmodule/arm64-apple-ios-simulator.swiftmodule
 ./usr/lib/swift/iphonesimulator/Darwin.swiftmodule
-./usr/lib/swift/iphonesimulator/Darwin.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
-./usr/lib/swift/iphonesimulator/Darwin.swiftmodule/arm64-apple-ios-simulator.swiftmodule
 ./usr/lib/swift/iphonesimulator/RegexBuilder.swiftmodule
 ./usr/lib/swift/iphonesimulator/RegexBuilder.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
 ./usr/lib/swift/iphonesimulator/RegexBuilder.swiftmodule/arm64-apple-ios-simulator.swiftmodule
```

**Comment by edymtt** [comment]
macOS job has a failure in a sourcekit-lsp test:

```
/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-release/6.0/sourcekit-lsp/Tests/SourceKitLSPTests/RenameTests.swift:1146: error: -[SourceKitLSPTests.RenameTests testRenameAfterFileMove] : XCTAssertEqual failed: ("Optional(LanguageServerProtocol.WorkspaceEdit(changes: Optional([file:///private/var/folders/bb/hcrjxg1s0b96pfst0ymhmp240000gn/T/sourcekit-lsp-test-scratch/testRenameAfterFileMove-72C4BAE8/Sources/MyLibrary/caller.swift: [LanguageServerProtocol.TextEdit(_range: LanguageServerProtocol.CustomCodable<LanguageServerProtocol.PositionRange>(wrappedValue: Range(Position(line: 1, utf16index: 2)..<Position(line: 1, utf16index: 5))), newText: "bar")]]), documentChanges: nil, changeAnnotations: nil))") is not equal to ("Optional(LanguageServerProtocol.WorkspaceEdit(changes: Optional([file:///private/var/folders/bb/hcrjxg1s0b96pfst0ymhmp240000gn/T/sourcekit-lsp-test-scratch/testRenameAfterFileMove-72C4BAE8/Sources/MyLibrary/caller.swift: [LanguageServerProtocol.TextEdit(_range: LanguageServerProtocol.CustomCodable<LanguageServerProtocol.PositionRange>(wrappedValue: Range(Position(line: 1, utf16index: 2)..<Position(line: 1, utf16index: 5))), newText: "bar")], file:///private/var/folders/bb/hcrjxg1s0b96pfst0ymhmp240000gn/T/sourcekit-lsp-test-scratch/testRenameAfterFileMove-72C4BAE8/Sources/MyLibrary/movedDefinition.swift: [LanguageServerProtocol.TextEdit(_range: LanguageServerProtocol.CustomCodable<LanguageServerProtocol.PositionRange>(wrappedValue: Range(Position(line: 0, utf16index: 5)..<Position(line: 0, utf16index: 8))), newText: "bar")]]), documentChanges: nil, changeAnnotations: nil))")
Test Case '-[SourceKitLSPTests.RenameTests testRenameAfterFileMove]' failed (9.496 seconds).
```

Retrying to see if this is transient

**Comment by edymtt** [comment]
@swift-ci please test macOS

**Review by najacque — APPROVED** [review]

**Pull request merged**
