### PR TITLE
Implement \ syntax for Swift key paths.

### PR DESCRIPTION
**Pull request by huonw**
This introduces a few unfortunate things because the syntax is awkward.
In particular, the period and following token in \.[a], \.? and \.! are
token sequences that don't appear anywhere else in Swift, and so need
special handling. This is somewhat compounded by \foo.bar.baz possibly
being \(foo).bar.baz or \(foo.bar).baz (parens around the type), and,
furthermore, needing to distinguish \Foo?.bar from \Foo.?bar.

rdar://problem/31724243

### CODE REVIEW

**Comment by huonw** [comment]
cc @jckarter

**Comment by huonw** [comment]
@swift-ci Please smoke test

**Comment by jckarter** [comment]
Seems reasonable, thanks Huon!

**Comment by huonw** [comment]
@swift-ci Please smoke test and merge

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Pull request merged**
