### PR TITLE
DNM: testing a fix for #41764

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-installer-scripts#89

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/89

@swift-ci please build toolchain Windows platform

**Comment by etcwilde** [comment]
https://github.com/apple/swift-installer-scripts/pull/89
@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-installer-scripts/pull/89

@swift-ci please build toolchain Windows platform

**Pull request closed without merging**
