### PR TITLE
[NFC] Drastically Reduce The Scope of the "Global LLVMContext"

### PR DESCRIPTION
**Pull request by CodaFi**
Swift needed its own global context because LLVM removed the concept of the "Global LLVMContext" upstream a while ago. This context infected a bunch of the compiler infrastructure.

This patch chases all of those global context dependencies back down to a single file: the builtins. Notably, 

* The integrated REPL now allocates its own LLVMContext to start instead of using the global context.
* llvm-opt now parses IR into a separate context.
* The SILRemarkStreamer now allocates and owns its own scratch context. 

I also noticed a potential use-after-move in the SILRemarksStreamer construction code that I've fixed by just refactoring the construction interface.

The builtins are still using a global context out of convenience. We could probably just refactor builtin lookup to be a service installed in the ASTContext and give it its own context for scratch space. For now, I'll just preserve the managed static that was here in case there is a better option I'm overlooking.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
⛵

**Comment by francisvm** [comment]
Hey @CodaFi, thanks for fixing the issues you found in the remark streamer.

Unfortunately, the `LLVMContext` used by the remark streamer needs to be the same one used for compiling the IR module, since LLVM will use that to embed some metadata in a remark section in the object files. Ideally all this data would be part of the `llvm::Module` and serialized, but right now it's not.

Is there any way to make that work? It also sounds like I might have missed a test for this, but I'm not sure how to add this kind of end-to-end test, that breaks after this patch:

```
$ swiftc src.swift -save-optimization-record=bitstream -g -o dst.o -wmo -O -c
$ otool -l dst.o | grep -A1 remarks
  sectname __remarks
   segname __LLVM
```

or

```
$ swiftc src.swift -save-optimization-record=bitstream -g -o dst -wmo -O
$ file dst.dSYM/Contents/Resources/Remarks/dst
dst.dSYM/Contents/Resources/Remarks/dst: data
```

**Comment by CodaFi** [comment]
Aha, good to know. In that case, I think we can delay installing this on an LLVMContext until we pair a `SILModule` with an `IRGenerator`.

**Pull request merged**
