### PR TITLE
[stdlib] Add custom implementations of removeLast and remove(at:) to Array

### PR DESCRIPTION
**Pull request by airspeedswift**
These currently use `replaceRange` which is way to big to inline. Let's see if these are faster. Not sure if this is covered by benchmarks though.

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
Benchmarks don't seem to be able to run at the moment. But local benchmarking on my machine suggests this is a win for some use cases. I'm going to merge, and then add some more benchmarks and measure perf using a revert when they're up again.

**Comment by airspeedswift** [comment]
Also seems to help code size a little bit.

**Comment by jrose-apple** [comment]
It looks like the implementation isn't actually correct; [it's failing under optimization](https://ci.swift.org/view/Dashboard/job/oss-swift_tools-RA_stdlib-RD_test-simulator/626/). Reverting for now.

**Pull request merged**
