### PR TITLE
[IRGenDebugInfo] Fix usage of dbg.declare

### PR DESCRIPTION
**Pull request by Snowy1803**
- Allow multiple dbg.declare on a single alloca: This is unnecessarily dropping debug info. The sharing of stack slot can happen because of AllocStackHoisting, which is run at -Onone too.
- Disable usage of dbg.declare in optimized code: It is incorrect in some cases to emit a dbg.declare, as the same variable appearing in both a dbg.declare and another debug intrinsic is not allowed, which could happen in optimized code.

### CODE REVIEW

**Comment by Snowy1803** [comment]
@swift-ci please test

**Comment by Snowy1803** [comment]
@swift-ci please test source compatibility

**Review by adrian-prantl — APPROVED** [review]

**Comment by adrian-prantl** [comment]
We're getting
```
Assertion failed: (FragmentOffset >= OffsetInBits && "overlapping or duplicate fragments"), function addFragmentOffset, file DwarfExpression.cpp, line 686.
```
This is something I've been meaning to fix at the LLVM level (rdar://124625723) — LLVM should be able to just split two overlapping fragments into two.

**Comment by Snowy1803** [comment]
In SwiftArgumentParser, we also have a
```
Assertion failed: ((FrameIndexExprs.size() == 1 || llvm::all_of(FrameIndexExprs, [](FrameIndexExpr &FIE) { return FIE.Expr && FIE.Expr->isFragment(); })) && "conflicting locations for variable"), function addFrameIndexExpr, file DwarfDebug.cpp, line 322.
```
which is the same as rdar://128155050

**Comment by Snowy1803** [comment]
@swift-ci please test

**Comment by Snowy1803** [comment]
@swift-ci please test source compatibility

**Comment by Snowy1803** [comment]
Source compatibility tests are passing, fixed the one failing AutoDiff test

**Comment by Snowy1803** [comment]
@swift-ci please smoke test

**Comment by Snowy1803** [comment]
@swift-ci please test

**Comment by Snowy1803** [comment]
@swift-ci please test macOS platform

**Pull request merged**
