### PR TITLE
Update cmake version to 3.16.5

### PR DESCRIPTION
**Pull request by drexin**
3.15.1 contains a bug that causes libraries that use the CMake Swift module to be built with -Onone, even in release mode.

### CODE REVIEW

**Comment by drexin** [comment]
@swift-ci smoke test

**Review by compnerd — APPROVED** [review]
LGTM, assuming @shahmishal doesn't have any concerns.

**Comment by shahmishal** [comment]
This will require additional changes to CI before this can be merged, please hold off from merging it.

**Review by shahmishal — APPROVED** [review]

**Comment by shahmishal** [comment]
```
20:00:39 -- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR) 
20:00:39 CMake Error at Utilities/cmcurl/CMakeLists.txt:454 (message):
20:00:39   Could not find OpenSSL.  Install an OpenSSL development package or
20:00:39   configure CMake with -DCMAKE_USE_OPENSSL=OFF to build without OpenSSL.
```

@swift-ci clean smoke test Linux

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@swift-ci smoke test windows

**Comment by drexin** [comment]
@swift-ci smoke test windows

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@swift-ci smoke test linux

**Comment by drexin** [comment]
@swift-ci smoke test windows

**Comment by RLovelett** [comment]
Two questions:

1. Should the [README](https://github.com/apple/swift/tree/963c7fccc3592fb0b6a1a9de27e8433e09b4e82c#cmake) also be updated?
2. Should the [`CMakeLists.txt`](https://github.com/apple/swift/blob/963c7fccc3592fb0b6a1a9de27e8433e09b4e82c/CMakeLists.txt#L1) be updated?

**Comment by compnerd** [comment]
@RLovelett - updating the README is probably a good idea.  The CMakeLists.txt update - in its current state any version is less than useful as it is an implementation of CMake in CMake.  The work to clean up the build system is still incomplete, but help is welcome!

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@compnerd @shahmishal Bumped version in `README` and `CMakeLists.txt`. I think it's better to at least fail when it doesn't have the correct version. WDYT? I also changed the version for swift-5.2-branch back to 3.15.1 in `update-checkout-config.json`, since we decided not to upgrade there.

**Comment by drexin** [comment]
@swift-ci clean smoke test

**Comment by shahmishal** [comment]
I don't think we should bump the CMakeLists.txt, README is fine. We don't want to force everyone to update to CMakeList.txt 3.16.5 to build the Swift compiler.

**Comment by drexin** [comment]
Ok, makes sense. I'll revert that.

**Comment by drexin** [comment]
@swift-ci clean smoke test

**Comment by drexin** [comment]
@swift-ci clean smoke test

**Comment by drexin** [comment]
@swift-ci clean smoke test

**Comment by drexin** [comment]
@swift-ci clean smoke test

**Comment by drexin** [comment]
@swift-ci smoke test windows

**Comment by compnerd** [comment]
Sure, bumping both is fine, I just meant that it doesn’t really convey much at the moment.

**Pull request merged**
