### PR TITLE
[IRGen] RuntimeMetadata: Reference type descriptors indirectly when required

### PR DESCRIPTION
**Pull request by xedin**
Type descriptors cannot always be referenced directly (i.e. when
a type is declared in a different module), so let's use
`getAddrOfLLVMVariableOrGOTEquivalent` facility that knows how
to handle that correctly.

Resolves: rdar://problem/103878515

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please smoke test

**Review by DougGregor — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please build toolchain macOS platform

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Comment by xedin** [comment]
@swift-ci please build toolchain macOS platform

**Review by stmontgomery — APPROVED** [review]

**Pull request merged**
