### PR TITLE
[Frontend] allow -emit-symbol-graph-dir and -supplementary-output-file-map at the same time

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
Resolves rdar://75155133

When the `-emit-symbol-graph[-dir]` flags were added, they were not completely integrated into the supplementary output file map structure. If a symbol graph is requested, these flags are passed to the frontend regardless of whether other supplementary outputs are collected into a file map. Because the frontend treats `-emit-symbol-graph-dir` and `-supplementary-output-file-map` as incompatible, this creates a situation where an error is reported through no fault of the user. This PR removes the check to disallow `-emit-symbol-graph-dir`, since this information is not being emitted in the file map right now.

A future PR will properly integrate `-emit-symbol-graph-dir` into the supplementary file map in the swift driver; this is meant as a stopgap for the meantime.

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
@swift-ci Please smoke test

**Review by bitjammer — APPROVED** [review]

**Review by artemcm — APPROVED** [review]

**Comment by QuietMisdreavus** [comment]
@swift-ci Please build toolchain macOS platform

**Comment by QuietMisdreavus** [comment]
The toolchain hit an error when building symbol graphs in certain situations, so i've updated this PR with a fix to ensure that symbol graphs can still render when using supplementary file maps.

@swift-ci Please smoke test

**Comment by QuietMisdreavus** [comment]
```
fatal: unable to access 'https://github.com/apple/swift-llbuild.git/': Could not resolve host: github.com
```

@swift-ci Please smoke test macOS platform

**Comment by QuietMisdreavus** [comment]
Same error. Looks like that node is having issues...

@swift-ci Please smoke test macOS platform

**Pull request merged**
