### PR TITLE
utils: build Foundation macros for distribution

### PR DESCRIPTION
**Pull request by compnerd**
This adds a build of the Foundation macros for distribution in the toolchain.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @hyp @jmschonfeld

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-foundation#714

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-foundation/pull/714
https://github.com/swiftlang/swift-installer-scripts/pull/325

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-foundation/pull/714
https://github.com/swiftlang/swift-installer-scripts/pull/325

@swift-ci please build toolchain Windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-foundation/pull/714
https://github.com/swiftlang/swift-installer-scripts/pull/325

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-foundation/pull/714
https://github.com/swiftlang/swift-installer-scripts/pull/325

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-foundation/pull/714
https://github.com/swiftlang/swift-installer-scripts/pull/325

@swift-ci please build toolchain windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-foundation/pull/714
https://github.com/swiftlang/swift-installer-scripts/pull/325

@swift-ci please build toolchain windows platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-foundation/pull/714
https://github.com/swiftlang/swift-installer-scripts/pull/325

@swift-ci please test

**Review by jmschonfeld — APPROVED** [review]

**Pull request merged**
