### PR TITLE
[simplify-cfg] When determining/searching for the end of a switch_enu…

### PR DESCRIPTION
**Pull request by gottesmm**
…ms diamond using single successors, make sure we do not have single block self-loop.

Otherwise, we infinite loop.

rdar://52131975

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
preset=buildbot,tools=RA,stdlib=RD
@swift-ci Please test with preset macOS Platform

**Comment by gottesmm** [comment]
One of the tests I modified only runs when asserts are disabled on the stdlib. So I am doing a preset test as well just to be careful.

**Review by aschwaighofer — APPROVED** [review]
Yikes. LGTM

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by andree-surya** [comment]
> When this code wil be available in production or in Xcode11, we have Xcode 11 GM and still have this problem? Here they said that this code is fixing a very annoying problem with Carthage and this library?
> [scinfu/SwiftSoup#116 (comment)](https://github.com/scinfu/SwiftSoup/issues/116#issuecomment-525848246)

We also would like to know whether this fix is incorporated into the official release of Xcode 11? We're currently seeing a problem with Xcode 11 in which the build system stuck when building our project with `-Osize`. Changing the optimization setting to `-Onone` unstuck the build process, but it's not a solution for us.

**Comment by gottesmm** [comment]
@andree-surya @catluc @imWildCat I can confirm that this fix is /not/ in the GM release. I can not confirm when a fix will be released.

That being said, I would strongly suggest filing a radar or a bug on bugs.swift.org with a project that reproduces the behavior. My reason for suggesting this is that:

1. The actual test case that was given previously that exposed this problem was a corner case example, so what you are seeing may be a different issue in a similar part of the compiler.
2. The snapshot that claimed to fix the bug may be fixing the bug for other reasons (for instance due to changing codegen).

By posting a project that reproduces, we can get to the bottom of this.

**Comment by imWildCat** [comment]
@gottesmm Thanks for your reply!

The related radar has been submitted on 8/20/2019 (FB7084207).

**Comment by gottesmm** [comment]
Hi @imWildCat @andree-surya @catluc – we are working on getting this resolved in a future Xcode release. Could you try downloading the toolchain that you can find [here](https://github.com/apple/swift/pull/27423#issuecomment-536251807) and see if this resolves the issue? This would be very helpful in establishing whether the issues all have the same root cause, or if there are different issues with similar symptoms.

**Comment by interstateone** [comment]
@gottesmm I've submitted FB7347879 with a project attached that has similar symptoms as what's discussed in this thread. The toolchain you linked fixed the issue for that project.

**Comment by imWildCat** [comment]
I was trying to test this toolchain but got this error:


> ld: file not found: /Applications/Xcode.app/Contents/Developer/Toolchains/swift-PR-27423-387.xctoolchain/usr/lib/arc/libarclite_iphoneos.a
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by gottesmm** [comment]
@imWildCat arclite isn't in open source toolchains, it should be found from the xcode default toolchain. Normally xcode finds the right path itself. Do you have any unusual linker flags in the project?

**Comment by gottesmm** [comment]
actually @imWildCat before we get to linker flags, I was just looking at the path of the toolchain. I think that is the wrong path and that may be leading to the issue here.

If you look at the linked instructions it says:

**Comment by gottesmm** [comment]
(sorry fat finger)

```
Install command
tar -zxf swift-PR-27423-387-osx.tar.gz --directory ~/

This will install the toolchain in $HOME/Library/Developer/Toolchains/ where Xcode will automatically pick it up.

To use the toolchain in Xcode

Open Xcode’s Preferences, navigate to Components > Toolchains and select the installed Swift toolchain (Swift PR - 27423 (387)).
```

Can you install the toolchain into $HOME/Library/Developer/Toolchains/ as mentioned in the instructions?

**Pull request merged**
