### PR TITLE
Prevent partial_apply cloning.

### PR DESCRIPTION
**Pull request by atrick**
partial_apply cannot be cloned, even in OSSA. OSSA lowering does not know how to allocate for multiple partial applies.

Fixes rdar://119768691 (OwnershipModelEliminator triggers assertion when lowering certain [on_stack] partial_applys in certain circumstances)

This fixes a regression caused by the move-only representation change in 5.9.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci benchmark

**Comment by meg-gupta** [comment]
LGTM

**Review by nate-chandler — APPROVED** [review]
LGTM.  Would it be worth adding verification for?

**Comment by atrick** [comment]
@swift-ci smoke test

**Comment by atrick** [comment]
> LGTM. Would it be worth adding verification for?

Ideally yes. `PartialApplyInst::visitOnStackLifetimeEnds` is the logic we need for verification. It runs when lowering OSSA. It isn't worth it to me to integrate into the verifier right now--there's no real danger of ad-hoc cloning of closures. I changed the assert to a release-mode informative diagnostic:

```
partial_apply [on_stack] use:
   %7 = argument of bb2 : $FakeOptional<Klass>    // users: %13, %8
     %8 = select_enum %7 : $FakeOptional<Klass>, case #FakeOptional.some!enumelt: %2, case #FakeOptional.none!enumelt: %3 : $Builtin.Int1 // user: %13
     %11 = mark_dependence %10 : $@noescape @callee_guaranteed () -> () on %1 : $*Klass // users: %13, %12
     %12 = begin_borrow [lexical] %11 : $@noescape @callee_guaranteed () -> () // user: %13
->   br bb5(%7 : $FakeOptional<Klass>, %8 : $Builtin.Int1, %11 : $@noescape @callee_guaranteed () -> (), %12 : $@noescape @callee_guaranteed () -> ()) // id: %13
LLVM ERROR: partial_apply [on_stack] cannot be cloned
```

**Pull request merged**
