### PR TITLE
[6.0][sending] Remove transferring.

### PR DESCRIPTION
**Pull request by gottesmm**
Explanation: This PR removes support from the compiler for parsing/handling transferring.

Radars:

- rdar://130253724

Original PRs:

- https://github.com/swiftlang/swift/pull/74610

Risk: Low. Just deletes code that has to do with transferring.
Testing: Made sure that rest of compiler still works via testing.
Reviewer: N/A

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
https://github.com/swiftlang/swift-syntax/pull/2716
@swift-ci test

**Comment by gottesmm** [comment]
https://github.com/swiftlang/swift-syntax/pull/2716
@swift-ci test

**Review by tbkka — APPROVED** [review]

**Comment by tbkka** [comment]
A nice bit of clean-up!

**Pull request merged**
