### PR TITLE
[Sema] Cleanup resolveTypeInContext

### PR DESCRIPTION
**Pull request by JaSpa**
The first commit handles the correct resolving of associated types in nested protocols (6 crashers fixed).
Next I'll look into moving the first `for` loop with its `switch` statement into the other loop as well.

### CODE REVIEW

**Comment by slavapestov** [comment]
Nice work!

I wonder if we can remove the 'if (!parent)' check in this patch, and replace it with an assertion:

ac95c1318fa68ac6c2659be237a13ef264a9f1eb

The root cause there was that we were looking up associated types on the wrong base type -- but your patch might fix that. You should see if all crasher tests still pass with that changed.

**Comment by lattner** [comment]
@slavapestov feel free to merge this if you think the patch looks good.  You know this area as well as anyone else :-)

**Comment by JaSpa** [comment]
@slavapestov Right away the assertion would trigger but I'll take a look at that as well.

**Comment by slavapestov** [comment]
@JaSpa Do you feel the commit is ready to merge as-is or do you want to wait?

Also it would be great if you could derive some small test cases for test/decl/nested.swift, but not very important for nested protocols (which we'll never support), only nested generic types (which we do want to allow, eventually).

**Comment by JaSpa** [comment]
@slavapestov I think it's ready as is. Over the next week I'll do some follow-up work which I'll put then into its own pull request.

About the test case, there seems to be already a test with nested generics in the file near the top. Did you have something else mind?

**Comment by JaSpa** [comment]
I think the main part is done, I'll take a look on the `!parent` stuff but I'll open a new pull request when I found a solution.

**Comment by slavapestov** [comment]
About the test case: what I had in mind is reducing one of the crashers with nested protocols to something minimal, and adding that to nested.swift. You can try that if you like but its up to you.

**Pull request merged**
