### PR TITLE
serialization: encode allowable client names in binary module format

### PR DESCRIPTION
**Pull request by nkcsgexi**
rdar://102741256

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Review by artemcm — APPROVED** [review]
LGTM! Thanks @nkcsgexi

**Pull request merged**
