### PR TITLE
LoopUnroller: Teach the loop unroller about >= terminated loops

### PR DESCRIPTION
**Pull request by aschwaighofer**

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test

**Comment by dabrahams** [comment]
Thank you thank you thank you.

**Comment by dabrahams** [comment]
oh, I presume this will work for `<`,`>`, and `<=` as well?

**Comment by aschwaighofer** [comment]
I was missing >. The others get canonicalized by the instruction combiner.

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test

**Pull request merged**
