### PR TITLE
[NFC] Restructed LexicalDestroyFolding.

### PR DESCRIPTION
**Pull request by nate-chandler**
Separate distinct multi-step tasks into distinct multi member function classes.  Clarify when values are produced and consumed.

### CODE REVIEW

**Review by atrick — APPROVED** [review]
Wow! Thanks. I'm curious if @eeckstein has any thoughts.

If you want to avoid long qualified names, you can just use an anonymous namespace and static functions. The `LexicalDestroyFolding` namespace seems redundant with the filename.

**Comment by atrick** [comment]
To the question of whether all the refactoring is really worthwhile...

I realize you split 3 classes: Candidates, FindCandidates, and FilterCandidates, even though there's only one piece of exposed state, Candidates. I realize that was to avoid passing IntroducerUsage and BorroweeUsage around as arguments. But I think it would be fine to pass those around across a few APIs since they're already nicely encapsulated. We always need to make these kind of tradeoffs. I don't think strictly following one design rule over others leads to the best outcome. What you did here was the extreme end of some design strategies I was advocating in the previous PR. I wouldn't have taken it this far for a relatively simple utility 😄

**Comment by nate-chandler** [comment]
Yeah, the 3 classes: FindCandidates, FilterCandidates and Rewriter are the ones doing the work, writing to (the first two) and reading from (the last) the one instance of Candidates.  

In this case, it seemed a bit cleaner (highly subjective) to me to have the constant reference IntroducerUsage and BorroweeUsage be members of classes rather than passing them around to several functions.  This way the related functions are grouped together into a single namespace and the noise of passing the arguments explicitly isn't there.  And you can easily find out how the members are used within those related functions by finding usages of the symbol.

**Comment by nate-chandler** [comment]
@swift-ci please smoke test

**Comment by eeckstein** [comment]
nice!

**Pull request merged**
