### PR TITLE
Move `build-script` argument parser to separate module

### PR DESCRIPTION
**Pull request by Rostepher**
# Purpose

This PR simply moves the argument parsing logic from the `build-script` main function into a separate module. There are no functional changes here apart from wrapping up the parser instantiation into a new `create_argument_parser` function. Having the parser in a separate module will allow for testing and stage future changes on the path to merging #11872.

rdar://problem/34336890

### CODE REVIEW

**Comment by gottesmm** [comment]
LGTM. Thank you for splitting this out!

**Review by gottesmm — APPROVED** [review]

**Comment by Rostepher** [comment]
@swift-ci smoke-test

**Comment by Rostepher** [comment]
@swift-ci smoke test

**Comment by Rostepher** [comment]
I'm going to merge this change and then move on to rebase and test #11882.

**Review by najacque — APPROVED** [review]
LGTM.  Splitting this out definitely helps reviewing!

**Pull request merged**
