### PR TITLE
Drop `-index-header-map`, adopt new `Module::Headers` API

### PR DESCRIPTION
**Pull request by jansvoboda11**
Makes Swift correctly build with https://github.com/swiftlang/llvm-project/pull/9507.

### CODE REVIEW

**Comment by jansvoboda11** [comment]
https://github.com/swiftlang/llvm-project/pull/9507
@swift-ci please test

**Comment by jansvoboda11** [comment]
https://github.com/swiftlang/llvm-project/pull/9507
@swift-ci please smoke test

**Comment by jansvoboda11** [comment]
https://github.com/swiftlang/llvm-project/pull/9507
@swift-ci please test Windows platform

**Comment by jansvoboda11** [comment]
https://github.com/swiftlang/llvm-project/pull/9507
@swift-ci please test Windows platform

**Review by artemcm — APPROVED** [review]

**Pull request merged**
