### PR TITLE
Per-request caches and dependency maps

### PR DESCRIPTION
**Pull request by slavapestov**
Based on @hamishknight's PR https://github.com/apple/swift/pull/31143.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
https://github.com/apple/llvm-project/pull/2279
@swift-ci Please test

**Comment by hamishknight** [comment]
Glad you were able to put the patch to use! Another approach [I was experimenting with](https://github.com/apple/swift/pull/32588) (originally suggested by @CodaFi) was to instead allow small requests and outputs to be stored inline in `AnyRequest` & `AnyValue`, which would come with a couple of benefits:

- It would allow large requests to have their storage shared by both the evaluator and dependency tracker
- `AnyValue` would be able to keep its indirection in certain cases, which could allow for the evaluator returning certain outputs by reference, which could cut down on copies for e.g cached `std::vector` returns, and would allow for move-only cached outputs.

However I was getting some regressions for `AnyRequest` which I didn't get round to fully tracking down (applying the change just to `AnyValue` gave a decent performance win though). I'd still be interested in pursuing it further to see what the resulting win would be (if any), but am also more than happy to take the concrete performance win in this change :)

I was also planning on (but never started) experimenting with stamping out specialized caches for e.g AST nodes that would store all the request outputs together (essentially mimicking external caching storage but encapsulated within the evaluator), but that can be done on top of any caching implementation.

**Comment by slavapestov** [comment]
@hamishknight I'll leave AnyValue and AnyRequest in place for now.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
https://github.com/apple/llvm-project/pull/2279
@swift-ci Please test

**Comment by slavapestov** [comment]
https://github.com/apple/llvm-project/pull/2279
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test Linux

**Comment by slavapestov** [comment]
apple/llvm-project#2279
@swift-ci Please test Linux

**Comment by slavapestov** [comment]
apple/llvm-project#2279
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
apple/llvm-project#2279
@swift-ci Please test Linux

**Comment by slavapestov** [comment]
@swift-ci Please test Linux

**Pull request merged**
