### PR TITLE
[CodeCompletion] Migrate CaseStmtBeginning to solver-based

### PR DESCRIPTION
**Pull request by ahoppen**
Migrate code completion inside `case` statements of `switch`-statements to solver-based

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please SourceKit stress test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please SourceKit stress test

**Review by rintaro — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Pull request merged**
