### PR TITLE
[5.9] [SE-0400] SE-0400: Enable InitAccessors feature by default

### PR DESCRIPTION
**Pull request by DougGregor**
This feature was accepted, so remove it as an "experimental feature" and enable it by default. Fixes rdar://113708096.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Review by hborla — APPROVED** [review]

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
(fixed a bad cherry-pick)

**Pull request merged**
