### PR TITLE
[Sema] Always install property wrappers during qualified lookup

### PR DESCRIPTION
**Pull request by CodaFi**
Revert the property wrappers part of dd51251.

Every part of the qualified lookup stack needs to synthesize property
wrapper members, otherwise we'll be subject to the relativistic effects
of semantic lookups in different files. Besides, Codable was the main
source of cycles and circularity under the old scheme.

Resolves rdar://59531889

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please test source compatibility

**Comment by CodaFi** [comment]
@swift-ci clean test source compatibility

**Comment by CodaFi** [comment]
@swift-ci test source compatibility

**Review by slavapestov — APPROVED** [review]

**Comment by CodaFi** [comment]
⛵️

**Pull request merged**
