### PR TITLE
Kill TypeBase::gatherAllSubstitutions()

### PR DESCRIPTION
**Pull request by slavapestov**
Last set of cleanups I want to do on SubstitutionMap for a while. This gets rid of gatherAllSubstitutions(), which would allocate memory in the permanent arena, often needlessly. Many, but not all places that constructed SubstitutionLists directly as arrays of Substitution values are now using the new APIs.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swiftix TypeBase::getRootGenericParam() is for you ;)

**Comment by swiftix** [comment]
@slavapestov 
> TypeBase::getRootGenericParam() is for you ;)

I'm touched ;)

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Pull request merged**
