### PR TITLE
Move compiler versioning code/compiler vendor code to swift_build_support from build-script-impl

### PR DESCRIPTION
**Pull request by gottesmm**
Made a github mistake before. So github closed my PR = (.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci Please python lint

**Comment by gottesmm** [comment]
There are going to be some python lint errors from other parts of the codebase, but I am checking that my python changes are clean.

**Comment by gottesmm** [comment]
@swift-ci Please smoke test OS X

**Comment by gottesmm** [comment]
@swift-ci Please python lint

**Comment by gottesmm** [comment]
@swift-ci Please smoke test OS X

**Comment by najacque** [comment]
@gottesmm Not sure why it's not reporting status.  Smoke test ran, and passed.  Do you want me to merge?

https://ci.swift.org/view/Pull%20Request/job/swift-PR-osx-smoke-test/1120/

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@najacque I just was not merging since I am just doing a little gardening while I travel around. It is therapeutic for me = ). I did this yesterday and am going to merge it in a bit. Maybe later.

**Comment by gottesmm** [comment]
@swift-ci Please smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci Please smoke test

**Pull request merged**
