### PR TITLE
Implement value witness table for @differentiable functions

### PR DESCRIPTION
**Pull request by asl**
@differentiable function is actually a triple (function, jvp, vjp). Previously normal thick function value witness table was used. As a result, for example,  only function was copied, but none of differential components.

This was the cause of uninitialized memory accesses and subsequent segfaults.

Should fix (now unavailable) TF-1122

### CODE REVIEW

**Comment by asl** [comment]
@swift-ci Please test

**Comment by asl** [comment]
Tagging @BradLarson

**Review by rxwei — APPROVED** [review]

**Comment by asl** [comment]
@swift-ci Please test macOS platform

**Review by dan-zheng — APPROVED** [review]

**Comment by asl** [comment]
@dan-zheng @rxwei I checked locally and for me all disabled parts with `#if REQUIRES_SR14042` work now. Do you happen to remember where they failed? On Windows?

**Comment by dan-zheng** [comment]
Checking the blame: https://github.com/apple/swift/pull/35384

> These tests fail on Windows due to an invalid parameter during the reabstraction of the generic differentiable parameters.

Since Windows tests pass, removing `#if REQUIRES_SR14042` seems good.

**Comment by asl** [comment]
> Checking the blame: #35384
> 
> > These tests fail on Windows due to an invalid parameter during the reabstraction of the generic differentiable parameters.
> 
> Since Windows tests pass, removing `#if REQUIRES_SR14042` seems good.

Right. I need to include the last disabled test then. And likely re-run everything on CI.

I was a bit surprised to see that value witness table was missed :)

**Comment by asl** [comment]
@swift-ci Please test

**Comment by asl** [comment]
@AnthonyLatsis I believe some tests still fail. But I reenabled ones that were fixed

**Pull request merged**
