### PR TITLE
[Sema] Decouple ConstraintSystem and TypeChecker headers

### PR DESCRIPTION
**Pull request by xedin**
* NFC: Move implementation of `isReadOnlyKeyPathComponent` to .cpp
* Switch `typeCheckExpression` to use `ContextualTypeInfo`
* Move `FreeTypeVariableBinding` to constraint system header
* NFC: Move `ContextualTypePurpose` to constraint system header

### CODE REVIEW

**Comment by xedin** [comment]
A possible replacement of https://github.com/apple/swift/pull/34194

**Comment by CodaFi** [comment]
Thank you!

**Review by CodaFi — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please smoke test Windows platform

**Pull request merged**
