### PR TITLE
[stdlib] Stop copying the _ContiguousArrayBuffer when initializing an ArraySlice from a literal

### PR DESCRIPTION
**Pull request by benlangmuir**
#### What's in this pull request?

Stop copying the _ContiguousArrayBuffer when initializing an ArraySlice from a literal.  Also, rename stdlib-private init(_ _buffer:) to init(_buffer:).  This is good hygiene, to avoid this issue happening again accidentally.

Thanks to Dmitri for help with this fix!
#### Resolved bug number: ([SR-1873](https://bugs.swift.org/browse/SR-1873))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by benlangmuir** [comment]
@swift-ci Please test

**Comment by benlangmuir** [comment]
@gribozavr could you please take a look?

**Comment by gribozavr** [comment]
@swift-ci Please benchmark

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by gribozavr** [comment]
@swift-ci Please benchmark

**Comment by gribozavr** [comment]
StringWalk regression is surprising.  Checking if it is a flake:

@swift-ci Please benchmark

**Comment by benlangmuir** [comment]
Huh, it seems to be consistent...

**Comment by gribozavr** [comment]
Now it is gone.  Let's do another one:

@swift-ci Please benchmark

**Comment by benlangmuir** [comment]
... And it's back again.  I'm not sure where we go from here.

**Comment by gribozavr** [comment]
I spent the last two hours doing builds with the exact same build settings as the bot and I can't reproduce the regression.

**Comment by gribozavr** [comment]
I re-benchmarked in https://github.com/apple/swift/pull/3238 and I can't reproduce this 109.0% regression in StringWalk.  Instead, it shows an 8% regression in MapReduce, which I can't reproduce locally.

**Pull request merged**
