### PR TITLE
[stdlib] Grapheme break fast-paths for Cyrillic, Arabic, Hangul

### PR DESCRIPTION
**Pull request by milseman**
Add in more grapheme break fast paths for scripts based on Cyrillic,
Arabic, or Hangul. Generates significant performance wins, similar to
those for the unihan fast paths.

While every extra check does slow down the runtime of
_internalExtraCheckGraphemeBreakBetween as currently implemented, I've
not found the performance cost to be relevant for workloads with
occasional mixed emoji contents, nor for workloads that his the
earlier checks. A pure Korean workload (currently the last check) does
pays a rather noticable price for the previous checks, but this is
only because the workload is now so greatly improved. Optimizing this
implementation is interesting future work, but not urgent.

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@aschwaighofer @eeckstein @gottesmm @swiftix 
This change seems to crash the SIL optimizer. Any steps I can take to help unblock or help diagnose?

**Comment by milseman** [comment]
Link to crash: https://ci.swift.org/job/swift-PR-osx/7986/consoleFull#577085863ee1a197b-acac-4b17-83cf-a53b95139a76

**Comment by swiftix** [comment]
@milseman The log seems to be elaborative enough. It should be possible to reproduce. At the first glance it looks like a use moved above the def or may be hoisted above the def. 

If the crasher could be reduced to something small, it would be of course very nice. But don't spend a lot of time on it, if it is non-obvious how to reduce.

**Comment by milseman** [comment]
@swiftix I actually haven't been able to reproduce locally on master. I was using -R --no-assertions, and will try other configurations.

**Comment by milseman** [comment]
Debug build of stdlib also didn't reproduce locally :-(

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
Amended. I accidentally the De Morgans.

**Comment by milseman** [comment]
@swift-ci please test

**Comment by swiftix** [comment]
@milseman Is it still crashing or not? Do we need to look into it?

**Comment by milseman** [comment]
Not currently. I'm not sure if there was a configuration issue or if the new code is simple enough to not trigger it. I never was able to repro locally.

**Comment by milseman** [comment]
@swift-ci please benchmark

**Comment by dabrahams** [comment]
@milseman Shouldn't there be a regression test that demonstrates an improvement before we check in any optimization?

**Comment by milseman** [comment]
There are two, they are just not part of the pre-commit suite.

**Comment by dabrahams** [comment]
👌

**Pull request merged**
