### PR TITLE
[cmake] Change CMake Policy CMP0054 for Cygwin

### PR DESCRIPTION
**Pull request by tinysun212**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

A smoke test on macOS does the following:
1. Builds the compiler incrementally.
2. Builds the standard library only for macOS. Simulator standard libraries and
   device standard libraries are not built.
3. lldb is not built.
4. The test and validation-test targets are run only for macOS. The optimized
   version of these tests are not run.

A smoke test on Linux does the following:
1. Builds the compiler incrementally.
2. Builds the standard library incrementally.
3. lldb is built incrementally.
4. The swift test and validation-test targets are run. The optimized version of these
   tests are not run.
5. lldb is tested.

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

In CMake 3.4.3, if `CMP0054` policy isn't set to any value, `cmake`
uses the OLD behavior and issues a long warning message for every
`if()` statement having a quoted variable whose value is an other
variable's name.

For example,

```
set(FOO 1)
set(VAR_A FOO)
set(VAR_B BAR)
if ("${VAR_A}" STREQUAL "FOO")
endif()
if ("${VAR_B}" STREQUAL "BAR")
endif()
```

issues `CMP0054` warning message for `"${VAR_A}"` and not for
`"${VAR_B}"`.

Cygwin `cmake` defines the variable `CMAKE_SYSTEM_NAME` as `CYGWIN`
and defines the variable `CYGWIN` as 1(TRUE).

Linux `cmake` defines the variable `CMAKE_SYSTEM_NAME` as `Linux`
and there is no variable `Linux`.

So, if we didn't set any value to `CMP0054` policy, every
`if ("${CMAKE_SYSTEM_NAME}" ...)` generated long warning message in
Cygwin, but did not generate in Linux.

### CODE REVIEW

**Comment by jrose-apple** [comment]
Please just set this all the time on all platforms, and put it next to the other `POLICY` command.

**Comment by tinysun212** [comment]
Modified as commented.

**Comment by jrose-apple** [comment]
Thanks!

@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Pull request merged**
