### PR TITLE
[IRGen][runtime] Simplify runtime CCs and entry point ABIs

### PR DESCRIPTION
**Pull request by gparker42**
* Remove RegisterPreservingCC. It was unused.
* Remove DefaultCC from the runtime. The distinction between C_CC and DefaultCC
  was unused and inconsistently applied. Separate C_CC and DefaultCC are
  still present in the compiler.
* Remove function pointer indirection from runtime functions except those
  that are used by Instruments. The remaining Instruments interface is
  expected to change later due to function pointer liability.
* Remove swift_rt_ wrappers. Function pointers are an ABI liability that we
  don't want, and there are better ways to get nonlazy binding if we need it.
  The fully custom wrappers were only needed for RegisterPreservingCC and
  for optimizing the Instruments function pointers.

rdar://35611235
rdar://35611185
rdar://36755525

### CODE REVIEW

**Comment by gparker42** [comment]
@swift-ci please test

**Comment by troughton** [comment]
Not a major point, but I think this touches a few areas that the [TwoWordPair removal](https://github.com/apple/swift/pull/14079#issuecomment-359865228) also touched. If the issue there was a simple missing `SWIFT_CC`, would it make sense to reapply that before this is merged and thereby avoid conflicts?

**Comment by gparker42** [comment]
@swift-ci please test

**Comment by gparker42** [comment]
I suspect that the total number of merge conflicts would be about the same. This fix should prevent the problem that broke #14079 so we'll be able to reinstate that with no additional bug fixes.

**Comment by gparker42** [comment]
@swift-ci please test macos

**Comment by gparker42** [comment]
@swift-ci please test os x platform

**Comment by gparker42** [comment]
@swift-ci please clean test os x platform

**Pull request merged**
