### PR TITLE
Fix availability checking for stored properties and enum cases with associated values

### PR DESCRIPTION
**Pull request by slavapestov**
The old behavior:
* Stored properties could not have `@available` at all.
* Enum elements with associated values could be `@available` without restriction.

When computing the in-memory layout of a type we require that all stored types are available at runtime, that is, not any newer than the intersection of the current deployment target and the availability context of their type.

This means that stored properties and enum elements with associated values must have the same availability checking behavior as each other, and also that both existing behaviors were wrong.

The new rule is that `@available` is only allowed on either kind of declaration if the OS version is not any newer than the enclosing availability context.

### CODE REVIEW

**Comment by slavapestov** [comment]
@xymus I suspect there are some similar edge cases with SPI that need to be straightened out.

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Review by xymus — APPROVED** [review]
This looks good!

**Comment by slavapestov** [comment]
@swift-ci Please test Linux

**Comment by AnthonyLatsis** [comment]
I believe the second commit message should say "as new as the enclosing availability context"?

**Comment by jerrydudu** [comment]
@slavapestov  Why It Not work in Xcode14-beta now?

**Pull request merged**
