### PR TITLE
Add random-access rotation algorithm

### PR DESCRIPTION
**Pull request by natecook1000**
This is an implementation of a cycle-based rotation algorithm for random-access collections, for comparison algorithms designed for forward and bidirectional collections.

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please test

**Comment by dabrahams** [comment]
@natecook1000 nice work!  Care to create some benchmarks?

**Comment by dabrahams** [comment]
@swift-ci Please test and merge

**Comment by natecook1000** [comment]
@dabrahams Sure! Is there a system in place for comparative benchmarks, or do I roll my own? `/benchmark` looks like it's more for testing language/compiler performance.

**Comment by dabrahams** [comment]
@gottesmm what would you recommend for @natecook1000?

**Pull request merged**
