### PR TITLE
Add swift-format to update-checkout tensorflow scheme

### PR DESCRIPTION
**Pull request by johnlinvc**
Fix the `update-checkout` script exception when running with 
`./swift/utils/update-checkout --clone --scheme tensorflow`

Added the missing swift-format & llvm-project to the scheme.

error message

======UPDATE FAILURES======
Traceback (most recent call last):
  File "./swift/utils/update-checkout", line 15, in <module>
    update_checkout.main()
  File "./swift/utils/update_checkout/update_checkout/update_checkout.py", line 580, in main
    fail_count += shell.check_parallel_results(update_results, "UPDATE")
  File "./swift/utils/swift_build_support/swift_build_support/shell.py", line 262, in check_parallel_results
    print("%s failed (ret=%d): %s" % (r.repo_path, r.ret, r))
AttributeError: 'exceptions.KeyError' object has no attribute 'repo_path'
```

### CODE REVIEW

**Comment by dan-zheng** [comment]
I'm not able to reproduce this error from current `tensorflow` branch HEAD (https://github.com/apple/swift/commit/4df23c8e12f718b47729d5546a0fe188eab1d490).

Could you please clarify how you reproduced the `AttributeError: 'exceptions.KeyError' object has no attribute 'repo_path'` error? (including your operating system)

**Comment by johnlinvc** [comment]
Can be reproduced with a clean checkout.
The issue happens if the the repo have run `update-checkout` with master branch once.

Steps to reproduce:
```
git clone https://github.com/apple/swift.git
cd swift
git checkout tensorflow
cd ..
./swift/utils/update-checkout --clone --scheme tensorflow
cd swift
git checkout master
cd ..
./swift/utils/update-checkout --clone --scheme tensorflow
cd ..
git checkout tensorflow
./swift/utils/update-checkout --clone --scheme tensorflow
# error here
```

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Review by dan-zheng — APPROVED** [review]
Thanks @johnlinvc! Sorry for the late review, only `swift-format` needs to be added now.

**Pull request merged**
