### PR TITLE
[ConstraintSystem] Treat arithmetic SIMD operators like other generic operators when partitioning an overload set.

### PR DESCRIPTION
**Pull request by hborla**
A very small first step toward improving the type checker performance of SIMD code. An example:

```swift
func test(p0: SIMD2<Float>, p1: SIMD2<Float>, p2: SIMD2<Float>, p3: SIMD2<Float>) {
  let a = -p0 + p1*3.0 - p2*3.0 + p3
}
```

This code causes the type checker to time out in Swift 5.4. It type checks on main in ~40 seconds. With this change, it type checks in <1 second.

Resolves: rdar://75485647

### CODE REVIEW

**Comment by hborla** [comment]
@swift-ci please smoke test compiler performance

**Comment by hborla** [comment]
@swift-ci please test compiler performance

**Comment by hborla** [comment]
I think the solver can still skip the SIMD overloads if it already found a solution, which will hopefully get rid of the increase in constraint scopes

**Comment by hborla** [comment]
@swift-ci please test compiler performance

**Comment by hborla** [comment]
@swift-ci please smoke test compiler performance

**Comment by hborla** [comment]
@swift-ci please test compiler performance

**Comment by hborla** [comment]
@swift-ci please smoke test compiler performance

**Comment by xedin** [comment]
@swift-ci please clean test

**Comment by hborla** [comment]
@swift-ci please smoke test

**Review by xedin — APPROVED** [review]

**Comment by hborla** [comment]
The slight increase in constraint system statistics is expected, because the SIMD overloads are no longer in a separate partition that gets completely skipped once a solution is found. The overloads are still attempted, but I expect in most cases they'll be pruned quickly by the other heuristics (e.g. transitive conformance for arguments)

**Pull request merged**
