### PR TITLE
[AST] check modules before recursing for display decls

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
Resolves rdar://87601741

In https://github.com/apple/swift/pull/40810, `ModuleDecl::getDisplayDecls` started to recurse into modules that were marked as `@_exported import` for collecting decls. This caused some failures in source compatibility testing, due to recursing into Clang modules during serialization that tripped an assertion. This PR adds a check against these modules before recursing, so that Clang modules that should not be recursed into can be skipped.

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test source compatibility

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Comment by QuietMisdreavus** [comment]
After testing locally with one of the original source-compat failures, it seems like this still creates a failure if you try to generate symbol graphs. I'm going to try a different approach and push that up.

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test source compatibility

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Review by slavapestov — COMMENTED** [review]
Can you add a reduced test case for the crash?

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test source compatibility

**Comment by QuietMisdreavus** [comment]
This PR now contains the change from https://github.com/apple/swift/pull/40810, as it was reverted in https://github.com/apple/swift/pull/40877.

**Review by slavapestov — APPROVED** [review]

**Pull request merged**
