### PR TITLE
Don't include benchmarks when building back deploy concurrency

### PR DESCRIPTION
**Pull request by edymtt**

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci please smoke test

**Comment by edymtt** [comment]
@swift-ci please build toolchain macOS

**Review by shahmishal — APPROVED** [review]
thanks

**Comment by edymtt** [comment]
@swift-ci please python lint

**Comment by edymtt** [comment]
@swift-ci please build toolchain macOS

**Comment by edymtt** [comment]
@swift-ci please smoke test macOS

**Comment by shahmishal** [comment]
Failure on macOS toolchain was not related.

**Pull request merged**
