### PR TITLE
Revert "Use in_guaranteed for let captures"

### PR DESCRIPTION
**Pull request by rintaro**
Reverts apple/swift#29812
https://ci.swift.org/job/oss-swift-incremental-ASAN-RA-osx/4458

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please test ASAN

**Comment by rintaro** [comment]
@swift-ci Please ASAN test

**Comment by rintaro** [comment]
@meg-gupta I'm going to merge this once the PR test successfully build stdlib.

**Comment by atrick** [comment]
@meg-gupta Shouldn't this revert go ahead? I thought that https://github.com/apple/swift/pull/29812 was accidentally merged because it was never rebased and there's no commit message

**Comment by meg-gupta** [comment]
@atrick It wasn't merged by accident.

**Comment by meg-gupta** [comment]
I did a squash merge and I do see a commit message ?

**Comment by atrick** [comment]
Never mind. Apparently the original PR *was* merged correctly. I just expected to see the commits squashed in a rebase.

**Pull request merged**
