### PR TITLE
[NFC] Pre- increment and decrement where possible

### PR DESCRIPTION
**Pull request by AnthonyLatsis**

### CODE REVIEW

**Comment by CodaFi** [comment]
I assume you used `clang-tidy` to find these, right?

**Comment by CodaFi** [comment]
The overall refactor LGTM. We should get more eyes on this due to its size and scope, though.

**Comment by AnthonyLatsis** [comment]
> I assume you used `clang-tidy` to find these, right?

Not really. But now I know what to do next time will :-)

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test Linux

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test Linux

**Pull request merged**
