### PR TITLE
[DNM] Generating a toolchain

### PR DESCRIPTION
**Pull request by Azoy**

### CODE REVIEW

**Comment by Azoy** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by Azoy** [comment]
@swift-ci please build toolchain macOS platform

**Comment by Azoy** [comment]
@swift-ci please build toolchain macOS platform

**Comment by Azoy** [comment]
@swift-ci please build toolchain macOS platform

**Comment by airspeedswift** [comment]
@swift-ci please build toolchain macOS platform

**Comment by Azoy** [comment]
@swift-ci please build toolchain macOS platform

**Comment by airspeedswift** [comment]
@swift-ci please build toolchain macOS platform

**Comment by airspeedswift** [comment]
@swift-ci please build toolchain macOS platform

**Comment by glessard** [comment]
https://ci.swift.org/job/swift-PR-toolchain-macos/1103/artifact/branch-main/swift-PR-71618-1103-osx.tar.gz

**Pull request closed without merging**
