### PR TITLE
Sema: Only run extension binding once

### PR DESCRIPTION
**Pull request by slavapestov**
There's no need to walk all imports of all source files, and bind the
extensions defined therein. The only time that a non-main module
contains source files is when using -enable-source-import, and we
can just explicitly call bindExtensions() in the right place.

### CODE REVIEW

**Comment by slavapestov** [comment]
LLVM change: https://github.com/apple/llvm-project/pull/1183

**Comment by slavapestov** [comment]
apple/llvm-project#1183
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
apple/llvm-project#1183
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
apple/llvm-project#1183
@swift-ci Please smoke test macOS

**Comment by slavapestov** [comment]
apple/llvm-project#1183
@swift-ci Please smoke test macOS

**Comment by CodaFi** [comment]
@swift-ci test Windows

**Pull request merged**
