### PR TITLE
Compiler crashers: Sync with https://github.com/practicalswift/swift-compiler-crashes

### PR DESCRIPTION
**Pull request by practicalswift**
Add 342 compiler crashes.

### CODE REVIEW

**Comment by gribozavr** [comment]
Thanks!  I'll run tests on Linux and OS X and merge.

**Comment by radex** [comment]
@practicalswift FWIW I think there are a bunch more test cases from swift-compiler-crashes that didn't get synced — I can't, for example, find this one: https://github.com/practicalswift/swift-compiler-crashes/blob/736d5c8bee75f676ff3750e4ad3165d81059fe03/crashes/26296-duplicate-subscript-declaration.swift

**Comment by gribozavr** [comment]
These tests don't crash on Linux and OS X, please move them to the directory for fixed crashers:

```
Failing Tests (4):
    Swift :: compiler_crashers/27818-swift-astvisitor.swift
    Swift :: compiler_crashers/28181-llvm-irbuilder.swift
    Swift :: compiler_crashers/28182-anonymous-namespace-favorcalloverloads.swift
    Swift :: compiler_crashers/28183-swift-typebase-isequal.swift
```

**Comment by stefanstefan2001** [comment]
I know this isn't the best place to ask. How do you run the test ?

**Comment by gribozavr** [comment]
@stefanstefan2001 `utils/build-script -RT`.  More information in https://github.com/apple/swift/blob/master/docs/Testing.rst.

**Comment by stefanstefan2001** [comment]
@gribozavr Thank you.

**Comment by practicalswift** [comment]
@gribozavr Let me know if any further adjustments are needed :-)

**Comment by jtbandes** [comment]
I think it's quite possible that my PRs #253, #266, and #272 will fix some of these, so might want to wait for them to be merged, then re-run the tests. (Or I could rebase, but I'd have to do it 3 times 😳)

**Comment by lattner** [comment]
Nice!  Thank you @practicalswift , you continue to be awesome!

**Comment by gribozavr** [comment]
@practicalswift One more thing: these two tests are actually valid programs, so they don't need `not` in their RUN line:

```
Failing Tests (2):
    Swift :: compiler_crashers_fixed/27818-swift-astvisitor.swift
    Swift :: compiler_crashers_fixed/28181-llvm-irbuilder.swift
```

**Comment by practicalswift** [comment]
@gribozavr Fixed! Sorry about this - still trying to grasp all aspects of the RUN annotations used in the project :-)

**Comment by practicalswift** [comment]
@radex Thanks for notifying! Your test case `26296-duplicate-subscript-declaration.swift` is added as part of https://github.com/apple/swift/pull/294 :-)

**Comment by radex** [comment]
:)

**Pull request merged**
