### PR TITLE
Dummy PR - do not merge

### PR DESCRIPTION
**Pull request by hartbit**

### CODE REVIEW

**Comment by hartbit** [comment]
@shahmishal Do you know which swift-ci invocation invokes the `swift-integration-test` tests?

**Comment by shahmishal** [comment]
`@swift-ci test` will run the swift-integration-test.

**Comment by hartbit** [comment]
Please test with following pull request:
https://github.com/apple/swift-integration-tests/pull/55

@swift-ci test

**Comment by hartbit** [comment]
Please test with following pull request:
https://github.com/apple/swift-integration-tests/pull/56
https://github.com/apple/swift-package-manager/pull/2050

@swift-ci test

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by CodaFi** [comment]
I figure y'all probably don't need this anymore

**Pull request closed without merging**
