### PR TITLE
[5.5] [SILGen] Precompute "returned" completion handler indices.

### PR DESCRIPTION
**Pull request by nate-chandler**
Explanation: When generating the completion handler that is passed to ObjC methods that are being called as async Swift functions, the parameters taken by the generated completion handler are matched up with the values that are returned from the async function.  Some of the parameters to the completion handler (the block_storage, and the flag and error parameters if present) do not correspond to values to be returned from the function into the calling Swift code.  So it's necessary to avoid matching returned values up with those non-corresponding parameters.

Previously, the matching was done by testing candidate parameter indices against the non-corresponding indices in order while doing the matching.  There were cases where the matching up didn't work out correctly for certain completion handler shapes.  The result was to miscompile certain generated completion handlers.

Here, those to-be-ignored indexes are filtered out first.

Issue: rdar://80847020

Testing: New regression test, Swift CI

Reviewed by: @jckarter

Risk: Low, simplifies existing indexing logic.

Scope: Limited to Swift import of ObjC methods as async functions.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by jckarter — APPROVED** [review]

**Comment by nate-chandler** [comment]
@swift-ci please nominate

**Review by DougGregor — APPROVED** [review]

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test windows platform

**Comment by nate-chandler** [comment]
@swift-ci please clean test windows platform

**Comment by nate-chandler** [comment]
@swift-ci please clean test macos platform

**Pull request merged**
