### PR TITLE
Local lazy vars

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
To make this a high-quality contribution I really need some feedback and ideas, especially from people that wrote and maintain the parts of the compiler involved in this change.
___

The most important step to directly implementing support for local lazy variables is obviously preparation. Preparation here means to provide an efficient way to supplement the list of elements contained within a `BraceStmt` after allocating it. I have next to no experience in using `TrailingObjects`, but from looking at all the other use sites and, specifically, how extensions and nominal types use `IterableDeclContext`, it seems like it was not designed for arrays of dynamic size. I decided to use an approach similar to `IterableDeclContext`, but am still thinking whether this is a positive change. I also thought about how having `ASTNode` be a base class rather than a pointer union would make the iterable approach less brittle. 

Next was the need for a way to access the innermost `BraceStmt` that contains the `VarDecl` at hand. Propagating the brace statement through lazy accessor generation and request evaluation proved to be almost impossible, hence the decision to add a `ParentBraceStmt` field to `VarDecl`.

___

### Edit: Implemented in #35803

### CODE REVIEW

**Comment by jrose-apple** [comment]
:-/ In the days of property wrappers, I'm not sure it's worth it to port the built-in `lazy` to local contexts. I'm not saying it has *no* value, but it might not be worth the added complexity.

**Comment by AnthonyLatsis** [comment]
@jrose I thought about that. `lazy` has its perks, but however it goes, this is still a great experience for me :)

**Comment by jckarter** [comment]
`lazy` and property wrappers are still deeply related in their implementation approach. Making `lazy` work in local, global, etc. contexts should make it easier to support wrapped properties in those contexts too.

**Comment by slavapestov** [comment]
Instead of adding the lazy variable's storage to the parent BraceStmt, which introduces considerable complexity, how about we change SILGenStmt to explicitly visit the storage when visiting a local lazy var (or property wrapper).

**Comment by AnthonyLatsis** [comment]
@slavapestov Sounds promising, thanks!

**Comment by AnthonyLatsis** [comment]
@slavapestov I missed that since we don't add the storage to the AST we also need to do the same thing in *all* other Visitor subclasses that care about it. Some places such as `ASTDumper` should only care about the storage if it was already created. This seems like a lot of duplication..

**Comment by nuclearace** [comment]
@AnthonyLatsis I noticed you have a bullet for SE evolution proposal. I was under the impression that this could actually just be treated as a bug/outstanding feature that should have always worked in Swift, but didn't because of implementation issues.

I vaguely remember seeing this get discussed by @DougGregor, I think maybe in the context of property wrappers.

**Comment by AnthonyLatsis** [comment]
@nuclearace I suspect the Swift team will be in favor of a new discussion and SE proposal. It *is* sort of obvious, but not really a broken feature or, judging by how SE was conducted hitherto, something trivial enough to just land through SR, I think. More so if we extend this to property wrappers at the same time. 

Here's [another discussion](https://forums.swift.org/t/declaring-local-variables-as-lazy/9287/11?u=anthonylatsis) from last year.

**Comment by AnthonyLatsis** [comment]
> Instead of adding the lazy variable's storage to the parent BraceStmt, which introduces considerable complexity, how about we change SILGenStmt to explicitly visit the storage when visiting a local lazy var (or property wrapper).

@slavapestov I have updated the implementation to reflect this idea, and it works just fine. However, as it turns out, there's a considerable amount of duplication and ad hoc logic that needs to be run every time a walker or visitor encounters a `TopLevelCodeDecl` or PBD, because the storage is not part of the AST. At this rate property wrappers will only exacerbate the issue.

Would using a list instead of `TrailingObjects` for `BraceStmt` significantly impact compiler performance?

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
