### PR TITLE
swift-reflection-dump: ELF ObjectMemoryReader support for relocations

### PR DESCRIPTION
**Pull request by jckarter**
Collect the relative and symbol relocations from ELF images in order to resolve pointer values
read from disk. This allows us to enable symbolic-referencing-all-the-things for ELF platforms.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@davezarzycki Would you be able to test whether this works for you on your Fedora box?

**Review by davezarzycki — APPROVED** [review]
`ninja check-swift-validation` still passes on Fedora 31 (x86_64) with a unified build and top-of-tree llvm/clang/lld.

**Comment by jckarter** [comment]
Thanks!

**Pull request merged**
