### PR TITLE
Rename "build configurations" to "conditional compilation blocks".

### PR DESCRIPTION
**Pull request by jrose-apple**
...because "build configuration" is already the name of an Xcode feature.
- `#if` et al are "conditional compilation directives".
- The condition is a "conditional compilation expression", or just "condition" if it's obvious.
- The predicates are "platform conditions" (including `swift(>=...)`)
- The options set with -D are "custom conditional compilation flags". (Thanks, @kballard!)

I left "IfConfigDecl" as is, as well as SourceKit's various "BuildConfig" settings because some of them are part of the SourceKit request format. We can change these in follow-up commits, or not. (cc @akyrtzi and @nkcsgexi)

rdar://problem/19812930

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by lattner** [comment]
This approach makes sense to me.  Thank you for fixing the diagnostics to be more specific instead of referring to "conditional compilation blocks" mechanically.

**Comment by nkcsgexi** [comment]
Text in source kit request format is expensive to change. I am fine with leaving as it is.

**Comment by jrose-apple** [comment]
Pretty sure that's not my failure, merging anyway!

**Pull request merged**
