### PR TITLE
Parser: use parser to generate a refined token stream to help syntax coloring.

### PR DESCRIPTION
**Pull request by nkcsgexi**
This patch allows Parser to generate a refined token stream to satisfy tooling's need. For syntax coloring, token stream from lexer is insufficient because (1) we have contextual keywords like `get` and `set`; (2) we may allow keywords to be used as argument labels and names; and (3) we need to split tokens like "==<". In this patch, these refinements are directly fulfilled through parsing without additional heuristics. The refined token vector is optionally saved in SourceFile instance.

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci Please test OS X platform

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by harlanhaskins** [comment]
Seems the new tokens `string_interpolation_anchor` and `contextual_keyword` tokens didn't make their way into `Token.py`, which breaks `SwiftSyntax`. I'm making a PR to add them now, and will add a test to make sure it doesn't get caught up again.

**Pull request merged**
