### PR TITLE
[stdlib] Refactor availability code

### PR DESCRIPTION
**Pull request by PatrickPijnappel**
Miscellaneous refactoring:
- Removed (correct me if I'm wrong) redundant code.
- Renamed local variables for consistency.
- Rewrote `< (_:_:)` implementation for readability.
  - New implementation does one more comparison in case `lhs.majorVersion < rhs.majorVersion` but equal or less comparisons in all other cases. Not sure if it matters after optimization though.
- Patch passes `build-script -R -t`.

### CODE REVIEW

**Comment by gribozavr** [comment]
Please keep the `func >=`.  It is important to keep for optimization because the compiler calls that comparison -- every bit helps.

**Comment by gribozavr** [comment]
Adding a comment about that would be a good idea, by the way.

**Comment by PatrickPijnappel** [comment]
By defining `func >=` though, we are effectively manually inlining. Wouldn't that decision be better left to the compiler?

**Comment by gribozavr** [comment]
@PatrickPijnappel It is not just inlining -- it is a clear win in the number of branches.  If you can show that the optimizer can do the same in apps compiled with `-Onone`, I'd be happy to remove the function.

**Pull request closed without merging**
