### PR TITLE
[stdlib] Fold multiple layers of LazyMapSequence/LazyMapCollection

### PR DESCRIPTION
**Pull request by moiseev**

### CODE REVIEW

**Comment by moiseev** [comment]
Let's see if it breaks anything...

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by moiseev** [comment]
@swift-ci Please Test Source Compatibility

**Comment by airspeedswift** [comment]
Looks good. Presumably some cases that relied on the return type could get the other overload via type context. We should add tests to make sure the right overloads are getting picked without context, tho.

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
@swift-ci please smoke test compiler performance

**Comment by moiseev** [comment]
@swift-ci Please smoke test and merge

**Comment by moiseev** [comment]
@swift-ci Please smoke test and merge

**Pull request merged**
