### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 0x973**
change the version for Xcode9

### CODE REVIEW

**Comment by CodaFi** [comment]
Is this true @shahmishal?

**Comment by ZhengShouDong** [comment]
About Xcode 9 beta 4 document
https://download.developer.apple.com/Developer_Tools/Xcode_9_beta_4/Xcode_9_beta_4_Release_Notes.pdf

**Comment by CodaFi** [comment]
@ZhengShouDong this repository does not necessarily track the latest and greatest Xcode as a build requirement.  We periodically update the SDKs/Xcode install on the bots and only then do we update the README.

**Comment by shahmishal** [comment]
We don't currently support building Swift compiler with Xcode 9 beta 4 yet.

**Comment by rjmccall** [comment]
And in fact we require patches to build with it, although those patches are quite minor.

**Pull request closed without merging**
