### PR TITLE
IRGen: Fix cast of existential type with anyobject to super class constraint existential

### PR DESCRIPTION
**Pull request by aschwaighofer**
rdar://55987397
SR-11565

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
Nice catch! We need some form of cast fuzzer don't we...

**Comment by aschwaighofer** [comment]
@swift-ci please smoke test linux

**Pull request merged**
