### PR TITLE
[stdlib] Access a Character's .unicodeScalars without allocation

### PR DESCRIPTION
**Pull request by dabrahams**

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please smoke benchmark

**Comment by dabrahams** [comment]
@swift-ci Please smoke test and merge

**Comment by dabrahams** [comment]
Note: full tests were run locally and I happen to know that no tests outside the smoke suite actually touch this view.

**Comment by dabrahams** [comment]
@airspeedswift The StringWithCString regression was a big surprise and it's almost unfathomable how it's related.  I will try to look into that tonight.

**Comment by dabrahams** [comment]
@airspeedswift I am losing confidence that StringWithCString is measuring anything real.  The changed code is never called by that test (verified in debug build with breakpoint), so I don't see how I could have regressed it.

**Comment by airspeedswift** [comment]
Yep seems that way. It's a bit of a weird test – it doesn't do anything with the C string as part of the test. The other tests in that file do more work while still exercising `withCString` and seem more stable.

**Comment by dabrahams** [comment]
@airspeedswift not to mention that it is measuring the cost of copying a 6MB C string, which is completely atypical.  I am seeing a pattern: the tests that are dominated by a call to an intrinsic like `memcmp` or `memcpy` tend to be completely erratic.  The StringHasPrefix/Suffix tests fall into that bucket (no, they don't optimize down to nothing). IMO we should just remove them all.

**Comment by airspeedswift** [comment]
We probably need a benchmark for Character's unicodeScalars view though.

**Pull request merged**
