### PR TITLE
[ImgBot] optimizes images

### PR DESCRIPTION
**Pull request by ImgBotApp**
Hey there. I've just optimized all of your images. They are the same dimensions and quality as before, only they take up less space now.

\docs\refactoring\Cursor.png (22.64%))
\docs\refactoring\Range.png (23.55%))
\docs\InstrumentsProfile.png (29.58%))
\docs\refactoring\Toolchain.png (27.37%))
\lib\Syntax\.doc\SyntaxExample.png (7.68%))
\docs\InstrumentsExpandedProfile.png (7.96%))
\docs\PerfReport.png (13.2%))

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by harlanhaskins** [comment]
This is a cool bot. 👍

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test

**Comment by gottesmm** [comment]
@harlanhaskins What did the bot do to the images specifically?

**Comment by harlanhaskins** [comment]
Seems that it just applies extra compression to them. It’s a common practice on the web to compress PNGs like this because there are algorithms that can heavily compress without affecting quality in any noticeable way.

**Comment by harlanhaskins** [comment]
Looking at the actual repo, looks like it just runs `ImageMagick`'s `LosslessCompress` routine on the PNG and writes it back out to a file:

https://github.com/dabutvin/ImgBot/blob/78efe1179df81acb9990bbba52cee072e6ac42d9/ImgBot.Function/CompressImages.cs#L64-L89

**Comment by dabutvin** [comment]
that's exactly it @harlanhaskins 👍 

If you want more prs from ImgBot here, or any of your other projects, feel free to install the GitHub app.

https://github.com/apps/ImgBot

Once installed into any repo, ImgBot will run the `LosslessCompress` routine on an ongoing basis and open PRs to keep your images optimized.

**Comment by harlanhaskins** [comment]
@gottesmm Any reason we shouldn't merge this?

**Comment by harlanhaskins** [comment]
@dabutvin: We really appreciate your efforts with @ImgBotApp, but unfortunately we are hesitant to merge a PR from a bot into this repo. I'm going to re-apply the ImageMagick conversions manually and credit you in a follow-up PR.

Thanks again!

**Comment by dabutvin** [comment]
Totally understand. Thanks for the support :)

**Pull request closed without merging**
