### PR TITLE
Add an isStrict flag to SIL pointer_to_address.

### PR DESCRIPTION
**Pull request by atrick**
Required for SE-0107: UnsafeRawPointer API.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci Please test and merge.

**Comment by gottesmm** [comment]
+1!

**Comment by gottesmm** [comment]
Question. I thought that the default was going to be the other way? (I.e. an aliasing flag) so that by default at the SIL level we still have strict aliasing?

I guess it is safer to make the conservative answer the default.

Michael

**Comment by atrick** [comment]
@gottesmm I would have preferred to make the common case the default, however there's no good name for the attribute other than [nonstrict] and we want our attributes to be positively named.

"[raw] *Type" does not make sense since raw memory is untyped and "[aliasing] *Type" is not accurate since we don't know anything about actual aliases.

For now, I'm most concerned with people understanding what the attribute means and a "strict address type" makes sense. Later we can change this to something else if it's too much clutter in the SIL, but I need something in place now to unblock other source breaking changes which can't easily be changed later.

**Pull request merged**
