### PR TITLE
Revert "Generic metadata prespecialization, part 1"

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/swift#28610

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @nate-chandler @jckarter

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
This broke on the Windows bot.  There were a series of failures on CI today and I think that this went through during that window.  It went in with @bitjammer's change which covered up this failure.  Logs from run:

https://dev.azure.com/compnerd/swift-build/_build/results?buildId=24034&view=logs&j=0e514031-a9b0-5d19-4075-e5711178f10f&t=243ec988-361f-5423-88d1-9b4dda6aad2e

**Comment by nate-chandler** [comment]
Let's just mark these tests unsupported on windows for now: https://github.com/apple/swift/pull/29148 .

**Comment by compnerd** [comment]
I don’t think that they are unsupported.  Please don’t do that.  The tests should pass.  They are over fitted for the targets.

**Pull request closed without merging**
