### PR TITLE
[benchmark] Janitor Duty: Final Sweep

### PR DESCRIPTION
**Pull request by palimondo**
Hopefully last of the cleanups…

### CODE REVIEW

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
Hmm… I was trying to lower the workload of `RemoveWhereQuadratic` because on my machine the runtimes were simply egregious:

TEST | MIN(μs)
---|---
RemoveWhereQuadraticInts | 10397
RemoveWhereQuadraticStrings | 25880

but I see that these are much different on on modern hardware:

TEST | OLD | NEW | DELTA | RATIO
-- | -- | -- | -- | --
RemoveWhereQuadraticInts | 480 | 98 | -79.6% | 4.90x
RemoveWhereQuadraticStrings | 1134 | 316 | -72.1% | 3.59x

I'm unable to use `legacyFactor` here, because there is non-linear relationship between the workload size and resulting runtime. I think the performance of this benchmark is heavily dependent on L1 and L2 cache size. I'm going to leave it as is.

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci benchmark

**Comment by palimondo** [comment]
@eeckstein I seem to have forgotten about this one. Thank's for remininding me, @CodaFi. Please review.

**Review by eeckstein — APPROVED** [review]
lgtm

**Pull request merged**
