### PR TITLE
[cmpcodesize][2] Convert script into Python package

### PR DESCRIPTION
**Pull request by modocache**
**This pull request should be reviewed and merged _after_ #548. Sorry for any confusion, but I wanted to separate one group of changes from another.**
## What's in this pull request?

`cmpcodesize` contains two complex sets of logic:
1. Parsing the user's arguments. Because it can be used in so many different ways (many args, no args, mutually exclusive arguments like `-l` and `-a`), this ends up getting complicated.
2. Actually comparing the code size of files using `subprocess` and `otool`.

In order to separate those sets of logic, this pull request converts `cmpcodesize` into a Python package that contains multiple files.
## Why merge this pull request?

A Python package isn't just beneficial for splitting up code, it also allows users to install `cmpcodesize` to their PATH:

``` sh
$ python utils/cmpcodesize/setup.py install
```

And developers may run unit tests:

``` sh
$ python utils/cmpcodesize/setup.py test
```

Furthermore, like [LLVM's lit](https://pypi.python.org/pypi/lit), we may choose to distribute `cmpcodesize` outside of the Swift project. Users may then install it:

``` sh
$ pip install cmpcodesize
```
## What downsides are there to merging this pull request?
- Depending on how you view `cmpcodesize`, you may consider it overkill to turn it into a Python package.
- Some may think a single-file, 400-line Python script isn't so large as to warrant splitting up.

### CODE REVIEW

**Comment by gribozavr** [comment]
@eeckstein @swiftix You wrote most of this script if I remember correctly, would you mind reviewing this PR?

**Comment by swiftix** [comment]
I had a brief look at your changes. Overall, looks good. I haven't tested it yet to check if the functionality was eventually changed in scope of re-factoring.

I'm a bit worried about one thing - the naming of the python package. I think `cmpcodesize ` is not a very representative name, especially if someone installs it globally. May be we should rename it into something more meaningful and self-descriptive? E.g. `swift-cmpcodesize` or something like that?

**Comment by modocache** [comment]
> I think `cmpcodesize` is not a very representative name, especially if someone installs it globally.

Totally agree. `swift-cmpcodesize` sounds good to me. We could also brainstorm further... `swift-executable-compare` or something?

**Comment by nadavrot** [comment]
@modocache I prefer to keep the file as a separate utility and not as a package that needs to be installed.

**Comment by modocache** [comment]
@nadavrot Keep in mind that installation isn't necessary--users will still be able to run via the command line, by invoking:

```sh
$ utils/cmpcodesize/cmpcodesize.py
```

**Comment by nadavrot** [comment]
oh okay. In that case, let's commit this. 

I can't approve this pull request because there are merge conflicts.

**Comment by modocache** [comment]
@nadavrot Ah, my bad--I thought you were going to merge in #548 first. I've rebased this pull request onto master. It contains all the commits from #548, so I'll close that one after this is merged. Thanks! :+1:

**Pull request merged**
