### PR TITLE
utils: Fix build-script-impl with distcc.

### PR DESCRIPTION
**Pull request by erg**

### CODE REVIEW

**Comment by erg** [comment]
@swift-ci Please smoke test and merge

**Comment by erg** [comment]
This is not necessary anymore because I reverted the offending patch and will incorporate this fix into my next patch.

**Comment by dabrahams** [comment]
I'm still not getting any distcc action.

**Comment by erg** [comment]
I reverted all my patches to the build-script and build-script-impl. FYI, I can only get distcc to work with user@machine syntax in the .distcc/hosts file instead of just the machine name.

**Comment by erg** [comment]
This patch is only useful if the other patches are applied.
2b923f38461390db3bd68d0bcb4bf55108171399
f3b74853697cfac23526cfc904c3c226b7873dcc
e480227d82299c0ba76242b9178e4c0df7cc75f2

**Pull request closed without merging**
