### PR TITLE
IRGen: Type layout based value witness generation

### PR DESCRIPTION
**Pull request by aschwaighofer**
Value witnesses for frozen generic types with sub fields will instantiate generic metadata for those sub fields to compute field offsets. This is a source of slow down.

This patch set instead computes type layouts that can be used to compute the
field offsets recursively.

Value witnesses are implemented in terms of those type layouts and will
no longer instantiate generic metadata (except for resilient types) for
fields.

This will allow for replacing outlined value functions by the witness
implementation without too much overhead in a follow up patch.

This behavior is conditionalized on a flag in IRGenOptions that is
turned off for now.

Note: Once this is in tree I will work on outlining some of the code used in TypeLayout.cpp to reduce code size.

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by compnerd** [comment]
@aschwaighofer - are there any tests for the new path?

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci please test windows

**Comment by aschwaighofer** [comment]
Latest windows PR runs here: https://ci-external.swift.org/job/swift-PR-windows/452

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci please test windows

**Comment by aschwaighofer** [comment]
Latest windows build: https://ci-external.swift.org/job/swift-PR-windows/453/

**Comment by aschwaighofer** [comment]
@swift-ci please test windows

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test windows

**Comment by aschwaighofer** [comment]
Latest windows run: https://ci-external.swift.org/job/swift-PR-windows/465/

**Comment by aschwaighofer** [comment]
@swift-ci Please test linux

**Comment by aschwaighofer** [comment]
@swift-ci Please test linux

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci please test windows

**Comment by aschwaighofer** [comment]
@swift-ci Please test macOS

**Comment by aschwaighofer** [comment]
@swift-ci Please clean test macOS

**Comment by aschwaighofer** [comment]
@swift-ci please test

**Comment by aschwaighofer** [comment]
@swift-ci please test linux

**Comment by aschwaighofer** [comment]
@swift-ci please test windows

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci please test windows

**Comment by aschwaighofer** [comment]
@swift-ci please test windows

**Pull request merged**
