### PR TITLE
[Sema] Fix errors due to implicitly deleted copy constructor.

### PR DESCRIPTION
**Pull request by dcci**

### CODE REVIEW

**Comment by dcci** [comment]
This fixes a build failure on FreeBSD with recent clang.

**Comment by nadavrot** [comment]
@dcci What is the error message on FreeBSD?

Can you use "=default " as the body?

**Comment by dcci** [comment]
Hi Nadav, I tried with =default but I keep getting the same error (which is weird). Anyway, looking at it again I'm not entirely convinced it's the right fix.
As per your request, here's the error message:

/exps/swift/swift/include/swift/Sema/TypeCheckRequestKinds.def:29:1: error: call to implicitly-deleted copy constructor of 'swift::TypeCheckRequest'
TYPE_CHECK_REQUEST(QualifiedLookupInDeclContext, DeclContextLookup)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/exps/swift/swift/include/swift/Sema/TypeCheckRequest.h:154:10: note: expanded from macro 'TYPE_CHECK_REQUEST'
  return TypeCheckRequest(TypeCheckRequest::Request, payload);                 \
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/exps/swift/swift/include/swift/Sema/TypeCheckRequest.h:79:5: note: copy constructor of 'TypeCheckRequest' is implicitly deleted because field 'Payload' has a deleted copy constructor
  } Payload;
    ^
/exps/swift/swift/include/swift/Sema/TypeCheckRequest.h:73:5: note: explicitly defaulted function was implicitly deleted here
    PayloadType(const PayloadType &) = default;
    ^
/exps/swift/swift/include/swift/Sema/TypeCheckRequestPayloads.def:37:28: note: copy constructor of 'PayloadType' is implicitly deleted because variant field 'InheritedClauseEntry' has a non-trivial
 copy constructor
TYPE_CHECK_REQUEST_PAYLOAD(InheritedClauseEntry, std::pair<llvm::PointerUnion<TypeDecl *, ExtensionDecl *>, unsigned>)
                           ^
/exps/swift/swift/include/swift/Sema/TypeCheckRequest.h:76:17: note: expanded from macro 'TYPE_CHECK_REQUEST_PAYLOAD'
    __VA_ARGS__ PayloadName;
                ^

Thanks!

--
Davide

**Comment by dcci** [comment]
Clang seems to DTRT:

http://en.cppreference.com/w/cpp/language/copy_constructor
 the implicitly-declared or defaulted copy constructor for class T is defined as deleted if any of the following conditions are true: 
 T is a union and has a variant member with non-trivial copy constructor

**Comment by tbartelmess** [comment]
@dcci What version of clang are you using to compile?

**Comment by jckarter** [comment]
Does FreeBSD use an outdated Clang by default? There was another PR floating around to make us explicitly use `clang35` or later IIRC.

**Comment by tbartelmess** [comment]
@jckarter 
```
$ clang++ --version
FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
Target: x86_64-unknown-freebsd10.2
Thread model: posix
$ 
```

**Comment by gribozavr** [comment]
Pull request #169 discusses that.  I think Clang 3.4 is just too old, and there will be more issues once we get past this one.

**Comment by dcci** [comment]
This is clang 3.7 on FreeBSD -CURRENT and not 3.4 on stable-10

**Comment by gribozavr** [comment]
@dcci I know.  What I was suggesting is that we use "clang35" on stable-10 as a special case, and "clang" on FreeBSD versions we don't special case.

**Comment by dcci** [comment]
So, I can confirm my suspicion that this fix isn't quite right.
While this is able to build swift the generated executable crashes while compiling the standard library:
Top of the stack:
Core was generated by `swift'.
Program terminated with signal SIGBUS, Bus error.
#0  llvm::PointerIntPair<swift::Type, 1u, bool, llvm::PointerLikeTypeTraits<swift::Type> >::getPointer (this=0x89f07d99f836d848) at /exps/swi
ft/llvm/include/llvm/ADT/PointerIntPair.h:77
77                               reinterpret_cast<void*>(Value & PointerBitMask));
(gdb) bt
#0  llvm::PointerIntPair<swift::Type, 1u, bool, llvm::PointerLikeTypeTraits<swift::Type> >::getPointer (this=0x89f07d99f836d848) at /exps/swi
ft/llvm/include/llvm/ADT/PointerIntPair.h:77
#1  0x0000000000435c75 in swift::TypeLoc::getType (this=0x89f07d99f836d848) at /exps/swift/swift/include/swift/AST/TypeLoc.h:66
#2  0x00000000014bb7c0 in swift::IterativeTypeChecker::isResolveInheritedClauseEntrySatisfied (this=0x7fffffff1578, payload=...) at /exps/swi
ft/swift/lib/Sema/ITCDecl.cpp:85
#3  0x00000000014ba0cf in swift::IterativeTypeChecker::isSatisfied (this=0x7fffffff1578, request=...) at /exps/swift/swift/include/swift/Sema
/TypeCheckRequestKinds.def:37
#4  0x00000000014ba3b9 in swift::IterativeTypeChecker::satisfy (this=0x7fffffff1578, request=...) at /exps/swift/swift/lib/Sema/IterativeType
Checker.cpp:70

+ @DougGregor who originally wrote this code and may have insights on the right fix.

**Comment by GuillaumeBibaut** [comment]
I'm getting the same compilation error than @dcci.
I'm on FreeBSD 10.2-RELEASE with clang 3.7 installed and used by the building script. Mainly:

```
apple/swift/include/swift/Sema/TypeCheckRequestKinds.def:54:1: error: call to implicitly-deleted copy constructor of 'swift::TypeCheckRequest'
TYPE_CHECK_REQUEST(ResolveTypeDecl, TypeDeclResolution)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/home/yom/Projects/apple/swift/include/swift/Sema/TypeCheckRequest.h:154:10: note: expanded from macro 'TYPE_CHECK_REQUEST'
  return TypeCheckRequest(TypeCheckRequest::Request, payload);                 \
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/home/yom/Projects/apple/swift/include/swift/Sema/TypeCheckRequest.h:79:5: note: copy constructor of 'TypeCheckRequest' is implicitly deleted because field 'Payload' has a deleted copy constructor
  } Payload;
    ^
/usr/home/yom/Projects/apple/swift/include/swift/Sema/TypeCheckRequest.h:73:5: note: explicitly defaulted function was implicitly deleted here
    PayloadType(const PayloadType &) = default;
    ^
/usr/home/yom/Projects/apple/swift/include/swift/Sema/TypeCheckRequestPayloads.def:37:28: note: copy constructor of 'PayloadType' is implicitly deleted because variant field 'InheritedClauseEntry' has a non-trivial copy constructor
TYPE_CHECK_REQUEST_PAYLOAD(InheritedClauseEntry, std::pair<llvm::PointerUnion<TypeDecl *, ExtensionDecl *>, unsigned>)
                           ^
/usr/home/yom/Projects/apple/swift/include/swift/Sema/TypeCheckRequest.h:76:17: note: expanded from macro 'TYPE_CHECK_REQUEST_PAYLOAD'
    __VA_ARGS__ PayloadName;
                ^
```

**Comment by dcci** [comment]
I think that a way to fix this might be implementing copy-constructor and operator= so that it picks the correct underlying constructor depending on the type. Something like this, modulo mistakes. Thoughts?

diff --git a/include/swift/Sema/TypeCheckRequest.h b/include/swift/Sema/TypeCheckRequest.h
index b5767e5..38c9fb0 100644
--- a/include/swift/Sema/TypeCheckRequest.h
+++ b/include/swift/Sema/TypeCheckRequest.h
@@ -114,7 +114,45 @@ public:
   }

 #include "swift/Sema/TypeCheckRequestPayloads.def"
-
+
+  TypeCheckRequest(const TypeCheckRequest &T) { *this = T; }
+
+  TypeCheckRequest& operator=(const TypeCheckRequest &T) {
+    switch (getPayloadKind(getKind())) {
+    case PayloadKind::Class:
+      Payload.Class = T.Payload.Class;
+      break;
+    case PayloadKind::Enum:
+      Payload.Enum = T.Payload.Enum;
+      break;
+    case PayloadKind::InheritedClauseEntry:
+      // XXX: FIXME
+      new (&Payload.InheritedClauseEntry) std::pair<llvm::PointerUnion<TypeDecl *, ExtensionDecl *>, unsigned>();
+      Payload.InheritedClauseEntry = T.Payload.InheritedClauseEntry;
+      break;
+    case PayloadKind::Protocol:
+      Payload.Protocol = T.Payload.Protocol;
+      break;
+    case PayloadKind::DeclContextLookup:
+      new (&Payload.DeclContextLookup) DeclContextLookupInfo();
+      Payload.DeclContextLookup = T.Payload.DeclContextLookup;
+      break;
+    case PayloadKind::TypeResolution:
+      // XXX: FIXME
+      new (&Payload.InheritedClauseEntry) std::tuple<TypeRepr *, DeclContext *, unsigned>();
+      Payload.TypeResolution = T.Payload.TypeResolution;
+      break;
+    case PayloadKind::TypeDeclResolution:
+      Payload.TypeDeclResolution = T.Payload.TypeDeclResolution;
+      break;
+#if 0
+    default:
+      llvm_unreachable("unknown kind");
+#endif
+    }
+    return *this;
+  }
+
   /// Determine the kind of type check request.
   Kind getKind() const { return TheKind; }

**Comment by dcci** [comment]
I have a new pull request for this (on a different branch) that I'll submit shortly.

**Pull request closed without merging**
