### PR TITLE
[DNM] Test clean toolchain build

### PR DESCRIPTION
**Pull request by jmschonfeld**

### CODE REVIEW

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-corelibs-foundation/pull/4990

@swift-ci please build toolchain Linux platform

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-corelibs-foundation/pull/4990

@swift-ci please build toolchain Linux platform

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-corelibs-foundation/pull/4990

@swift-ci please build toolchain Linux platform

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-corelibs-foundation/pull/5003

@swift-ci please build toolchain

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-corelibs-foundation/pull/5004

@swift-ci please build toolchain Windows platform

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-corelibs-foundation/pull/5004
https://github.com/apple/swift-foundation/pull/730

@swift-ci please build toolchain Windows platform

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-corelibs-foundation/pull/4990
https://github.com/apple/swift-foundation/pull/730

@swift-ci please build toolchain Windows platform

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-corelibs-foundation/pull/4990
https://github.com/apple/swift-foundation/pull/731

@swift-ci please build toolchain Windows platform

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-corelibs-foundation/pull/4990
https://github.com/apple/swift-foundation/pull/731

@swift-ci please test Windows platform

**Comment by jmschonfeld** [comment]
https://github.com/swiftlang/swift-installer-scripts/pull/312
https://github.com/apple/swift-corelibs-foundation/pull/4990
https://github.com/apple/swift-foundation/pull/731

@swift-ci please build toolchain Windows platform

**Comment by jmschonfeld** [comment]
https://github.com/swiftlang/swift-installer-scripts/pull/312
https://github.com/apple/swift-corelibs-foundation/pull/4990
https://github.com/apple/swift-foundation/pull/731

@swift-ci please build toolchain Windows platform

**Comment by jmschonfeld** [comment]
https://github.com/swiftlang/swift-installer-scripts/pull/312
https://github.com/apple/swift-corelibs-foundation/pull/4990
https://github.com/apple/swift-foundation/pull/731

@swift-ci please build toolchain Windows platform

**Comment by jmschonfeld** [comment]
https://github.com/swiftlang/swift-installer-scripts/pull/312
https://github.com/apple/swift-corelibs-foundation/pull/4990
https://github.com/apple/swift-foundation/pull/731

@swift-ci please test Windows platform

**Comment by parkera** [comment]
https://github.com/swiftlang/swift-installer-scripts/pull/312
https://github.com/apple/swift-corelibs-foundation/pull/4990
https://github.com/apple/swift-foundation/pull/731
https://github.com/apple/swift-foundation-icu/pull/31

@swift-ci please test Windows platform

**Comment by parkera** [comment]
https://github.com/swiftlang/swift-installer-scripts/pull/312
https://github.com/apple/swift-corelibs-foundation/pull/4990
https://github.com/apple/swift-foundation/pull/731
https://github.com/apple/swift-foundation-icu/pull/31

@swift-ci please test Windows platform

**Comment by jmschonfeld** [comment]
https://github.com/swiftlang/swift-installer-scripts/pull/312
https://github.com/apple/swift-corelibs-foundation/pull/4990
https://github.com/apple/swift-foundation/pull/734
https://github.com/apple/swift-foundation-icu/pull/31

@swift-ci please build toolchain Windows platform

**Pull request closed without merging**
