### PR TITLE
Switch on key paths.

### PR DESCRIPTION
**Pull request by jckarter**

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
Is there value in keeping the flag?

**Comment by jckarter** [comment]
@slavapestov If something goes horribly wrong and we have to turn it off, perhaps, but from a churn-minimization standpoint it also seems better to turn the switch on first then pull it out.

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Pull request merged**
