### PR TITLE
Adjust for SVN r298393

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
CC: @bob-wilson

**Comment by bob-wilson** [comment]
Thanks!
Also cc: @DougGregor since he's in charge of watching over master-next at the moment

**Comment by bob-wilson** [comment]
The Linux build failed with a complaint about an unknown source file (utils/CxaDemangle.cpp) and a request to update /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master-next/lldb/source/Utility/CMakeLists.txt.

**Comment by bob-wilson** [comment]
I don't see how that has anything to do with this change, so I'm going to merge it anyway.

**Pull request merged**
