### PR TITLE
Sema: Fix crash-on-invalid with 'enclosing self' property wrappers

### PR DESCRIPTION
**Pull request by slavapestov**
The diagnostic is still terrible, but at least we shouldn't crash.

Fixes one manifestation of <rdar://problem/57726880>.

I also filed <https://bugs.swift.org/browse/SR-11989> to track improving
the diagnostic.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Review by DougGregor — APPROVED** [review]

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Pull request merged**
