### PR TITLE
ABI: Change the mangling prefix from _T0 to $S

### PR DESCRIPTION
**Pull request by eeckstein**
rdar://problem/33753898

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci clean test

**Comment by rudkx** [comment]
Why do some of the new manglings have quotes (`"$S..."`) around them?

I have a bunch of mangling changes on my machine related to removing IUO from the type system. Presumably I can just do search/replace of _T0 with $S to fix things up?

**Comment by eeckstein** [comment]
@rudkx Quotes are just needed in textual llvm IR (because of the $).

Yes, replacing _T0 with $S should work.

**Comment by eeckstein** [comment]
Please test with following pull request:
https://github.com/apple/swift-corelibs-foundation/pull/1390

@swift-ci test

**Comment by eeckstein** [comment]
Please test with following pull request:
https://github.com/apple/swift-corelibs-foundation/pull/1390

@swift-ci test

**Comment by eeckstein** [comment]
Please test with following pull request:
https://github.com/apple/swift-corelibs-foundation/pull/1390

@swift-ci test

**Comment by eeckstein** [comment]
Please test with following pull request:
https://github.com/apple/swift-corelibs-foundation/pull/1390

@swift-ci test

**Comment by eeckstein** [comment]
Please test with following pull request:
https://github.com/apple/swift-corelibs-foundation/pull/1390

@swift-ci test

**Comment by eeckstein** [comment]
Please test with following pull request:
https://github.com/apple/swift-corelibs-foundation/pull/1390

@swift-ci test

**Comment by eeckstein** [comment]
Please test with following pull request:
https://github.com/apple/swift-corelibs-foundation/pull/1390

@swift-ci test

**Comment by eeckstein** [comment]
Please test with following pull request:
https://github.com/apple/swift-corelibs-foundation/pull/1390

@swift-ci test

**Comment by eeckstein** [comment]
Please test with following pull request:
https://github.com/apple/swift-corelibs-foundation/pull/1390

@swift-ci test

**Comment by eeckstein** [comment]
rdar://problem/33753898

**Pull request merged**
