### PR TITLE
Enabling copy propagation enables lexical lifetimes.

### PR DESCRIPTION
**Pull request by nate-chandler**
The effect of passing -enable-copy-propagation is both to enable the CopyPropagation pass to shorten object lifetimes and also to enable lexical lifetimes to ensure that object lifetimes aren't shortened while a variable is still in scope and used.

Add a new flag, -enable-lexical-borrow-scopes to override -enable-copy-propagation's effect (setting it to ::ExperimentalLate) on SILOptions::LexicalLifetimes that sets it to ::Early even in the face of -enable-copy-propagation.  The preexisting flag -disable-lexical-lifetimes continues to set that flag to ::Off even when -enable-copy-propagation is passed.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by atrick** [comment]
@nate-chandler why not just use `-disable-lexical-lifetimes` for this purpose?

**Comment by nate-chandler** [comment]
@atrick Fixed.  Now using `-enable-lexical-borrow-scopes` alongside `-enable-copy-propagation` has the same effect that `-enable-copy-propagation` on its own used to have.

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by atrick — COMMENTED** [review]
For your consideration, relevant commend line combinations:

```

-enable-copy-propagation // optimize object lifetimes (xcode does this)

-enable-lexical-lifetimes // Test lexical lifetimes without running copyprop

-enable-copy-propagation -enable-lexical-lifetimes=false // Test copy propagation without lexical constraints

-enable-lexical-borrow-scopes=false // disable SILGen diagnostic support

-enable-lexical-lifetimes enable-lexical-borrow-scopes=false // not allowed
```

**Comment by nate-chandler** [comment]
@atrick Fixed.  There is now `-enable-lexical-borrow-scopes=false` (which was `-disable-lexical-lifetimes`), `-enable-lexical-borrow-scopes=true`, `-enable-lexical-lifetimes=false`, `-enable-lexical-lifetimes=true` and a synonym `-enable-lexical-lifetimes`.

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Pull request merged**
