### PR TITLE
[main, rebranch, next] Update to latest releases of swift-atomics, swift-collections, swift-numerics, swift-system

### PR DESCRIPTION
**Pull request by lorentey**
Oops, toolchain builds are still on wildly obsolete package releases. Update them.

rdar://118090030

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci build toolchain macOS platform

**Comment by lorentey** [comment]
@swift-ci build toolchain Linux platform

**Review by glessard — APPROVED** [review]

**Comment by lorentey** [comment]
(Note: I'll file a separate PR for release/5.10 once this passes review & testing.)

**Comment by lorentey** [comment]
macOS toolchain build appears to have failed while building swift-syntax:

```
** Building swift-format **
+ /Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/swift-format/build-script-helper.py install --toolchain /Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/buildbot_osx/intermediate-install/macosx-x86_64/Library/Developer/Toolchains/swift-PR-69714-926.xctoolchain/usr --configuration release --build-path /Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/buildbot_osx/unified-swiftpm-build-macosx-x86_64 --multiroot-data-file /Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/swift/utils/build_swift/resources/SwiftPM-Unified-Build.xcworkspace --update --prefix /Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/buildbot_osx/intermediate-install/macosx-x86_64/Library/Developer/Toolchains/swift-PR-69714-926.xctoolchain/usr
warning: --multiroot-data-file is an *unsupported* option which can be removed at any time; do not rely on it
Building for production...
[0/2] Write swift-version--1C965AB9FA4D5D6C.txt
Build complete! (1.74s)
** Updating dependencies of swift-format **
** Building swift-format **
** Installing swift-format **
+ /Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/indexstore-db/Utilities/build-script-helper.py build --package-path /Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/indexstore-db --build-path /Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/buildbot_osx/unified-swiftpm-build-macosx-x86_64 --configuration release --toolchain /Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/buildbot_osx/intermediate-install/macosx-x86_64/Library/Developer/Toolchains/swift-PR-69714-926.xctoolchain/usr --ninja-bin /Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/buildbot_osx/ninja-build/ninja --multiroot-data-file /Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/swift/utils/build_swift/resources/SwiftPM-Unified-Build.xcworkspace
warning: --multiroot-data-file is an *unsupported* option which can be removed at any time; do not rely on it
error: 'yams': error while executing `/usr/bin/sandbox-exec -p (version 1)
(deny default)
(import "system.sb")
(allow file-read*)
(allow process*)
(allow mach-lookup (global-name "com.apple.lsd.mapdb"))
(allow file-write*
    (subpath "/Users/ec2-user/Library/Caches/org.swift.swiftpm/manifests")
    (subpath "/private/var/folders/7n/r31lzfjx6556jgc6vg55_cg80000gn/T/TemporaryItems/NSIRD_swift-build_3wvgCW")
    (subpath "/private/var/folders/7n/r31lzfjx6556jgc6vg55_cg80000gn/T/TemporaryItems")
)
 /var/folders/7n/r31lzfjx6556jgc6vg55_cg80000gn/T/TemporaryDirectory.PgTsCJ/yams-manifest -fileno 17 -context {"packageDirectory":"\/Users\/ec2-user\/jenkins\/workspace\/swift-PR-toolchain-macos\/branch-main\/yams"}`: close error: Undefined error: 0 (0)
error: ExitCode(rawValue: 1)
```

This appears to be an ongoing issue, independent of this PR.

**Comment by lorentey** [comment]
These old warnings (fixed in 1.0.5) do indicate that the change did not actually take root during the build:

```
/Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/swift-collections/Sources/OrderedCollections/HashTable/_HashTable+UnsafeHandle.swift:487:14: warning: 'assign(repeating:count:)' is deprecated: renamed to 'update(repeating:count:)'
    _buckets.assign(repeating: 0, count: wordCount)
             ^
/Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/swift-collections/Sources/OrderedCollections/HashTable/_HashTable+UnsafeHandle.swift:487:14: note: use 'update(repeating:count:)' instead
    _buckets.assign(repeating: 0, count: wordCount)
             ^~~~~~
             update
/Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/swift-collections/Sources/OrderedCollections/Utilities/_UnsafeBitset.swift:177:25: warning: 'assign(repeating:count:)' is deprecated: renamed to 'update(repeating:count:)'
    _words.baseAddress!.assign(repeating: .empty, count: _words.count)
                        ^
/Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/swift-collections/Sources/OrderedCollections/Utilities/_UnsafeBitset.swift:177:25: note: use 'update(repeating:count:)' instead
    _words.baseAddress!.assign(repeating: .empty, count: _words.count)
                        ^~~~~~
                        update
```

**Comment by lorentey** [comment]
Ah indeed, it still checkout out the old setup:

```
[swift-system]                          Updating '/Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/swift-system'
[swift-system]                          + git checkout 1.1.1
[swift-system]                          HEAD is now at 836bc45 Merge pull request #74 from compnerd/leaky-cauldron
[swift-atomics]                         Updating '/Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/swift-atomics'
[swift-atomics]                         + git checkout 1.0.2
[swift-atomics]                         HEAD is now at 919eb1d Merge pull request #48 from lorentey/fix-UnsafeAtomic-Sendable
[swift-collections]                     Updating '/Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/swift-collections'
[swift-collections]                     + git checkout 1.0.1
[swift-collections]                     HEAD is now at 2d33a0e Merge pull request #111 from neonichu/fix-aarch64
[swift-numerics]                        Updating '/Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/swift-numerics'
[swift-numerics]                        + git checkout 1.0.1
[swift-numerics]                        HEAD is now at 0a23770 Merge pull request #198 from stephentyrone/clarify-stability-differentiable

**Comment by lorentey** [comment]
Looking at the (correct) build log, I can see that we are checking out the right versions:

```
[swift-atomics]                         Updating '/Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/swift-atomics'
[swift-atomics]                         + git checkout 1.2.0
[swift-atomics]                         HEAD is now at cd142fd Merge pull request #106 from lorentey/release-cleanup
[swift-collections]                     Updating '/Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/swift-collections'
[swift-collections]                     + git checkout 1.0.5
[swift-collections]                     HEAD is now at a902f18 Merge pull request #314 from lorentey/fix-c++-benchmarks
[swift-numerics]                        Updating '/Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/swift-numerics'
[swift-numerics]                        + git checkout 1.0.2
[swift-numerics]                        HEAD is now at 0a5bc04 Merge pull request #215 from stephentyrone/arm64-mac-cmake-1.0
[swift-system]                          Updating '/Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/swift-system'
[swift-system]                          + git checkout 1.2.1
[swift-system]                          HEAD is now at 025bcb1 Merge pull request #93 from apple/revert-89-sb/resize-windows
[...]
update-checkout succeeded
[...]
swift-atomics                      : cd142fd2f64be2100422d658e7411e39489da985
swift-collections                  : a902f1823a7ff3c9ab2fba0f992396b948eda307
swift-numerics                     : 0a5bc04095a675662cf24757cc0640aa2204253b
swift-system                       : 025bcb1165deab2e20d4eaba79967ce73013f496
```

Bootstrapping seems to proceed normally, and it managed to get successful CMake builds of swift-collections and swift-system. swift-atomics and swift-numerics don't seem to get build; I'm not sure why we pull them into the toolchains.

```
--- bootstrap: note: Building swift-collections
-- The C compiler identification is Clang 17.0.0
-- The Swift compiler identification is Apple 5.11
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/buildbot_osx/intermediate-install/macosx-x86_64/Library/Developer/Toolchains/swift-PR-69714-926.xctoolchain/usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working Swift compiler: /Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/buildbot_osx/intermediate-install/macosx-x86_64/Library/Developer/Toolchains/swift-PR-69714-926.xctoolchain/usr/bin/swiftc
-- Check for working Swift compiler: /Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/buildbot_osx/intermediate-install/macosx-x86_64/Library/Developer/Toolchains/swift-PR-69714-926.xctoolchain/usr/bin/swiftc - works
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/buildbot_osx/swiftpm-macosx-x86_64/apple/Products/swift-collections
[1/3][ 33%][2.365s] Linking Swift shared library lib/libDequeModule.dylib
[2/3][ 66%][2.916s] Linking Swift shared library lib/libOrderedCollections.dylib
[3/3][100%][3.193s] Linking Swift shared library lib/libCollections.dylib
env MACOSX_DEPLOYMENT_TARGET=12.0 /usr/local/bin/cmake -G Ninja -DCMAKE_MAKE_PROGRAM=/Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/buildbot_osx/ninja-build/ninja -DCMAKE_BUILD_TYPE:=Debug -DCMAKE_Swift_FLAGS='-sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -module-cache-path "/Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/buildbot_osx/swiftpm-macosx-x86_64/apple/Products/swift-collections/module-cache"' -DCMAKE_Swift_COMPILER:=/Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/buildbot_osx/intermediate-install/macosx-x86_64/Library/Developer/Toolchains/swift-PR-69714-926.xctoolchain/usr/bin/swiftc -DCMAKE_C_COMPILER:=/Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/buildbot_osx/intermediate-install/macosx-x86_64/Library/Developer/Toolchains/swift-PR-69714-926.xctoolchain/usr/bin/clang -DCMAKE_AR:PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar -DCMAKE_RANLIB:PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -DCMAKE_C_FLAGS=-target x86_64-apple-macosx12.0 -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 -DCMAKE_C_FLAGS=-target x86_64-apple-macosx12.0 -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 /Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/swiftpm/../swift-collections
```

```
--- bootstrap: note: Building swift-system
-- The C compiler identification is Clang 17.0.0
-- The Swift compiler identification is Apple 5.11
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/buildbot_osx/intermediate-install/macosx-x86_64/Library/Developer/Toolchains/swift-PR-69714-926.xctoolchain/usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working Swift compiler: /Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/buildbot_osx/intermediate-install/macosx-x86_64/Library/Developer/Toolchains/swift-PR-69714-926.xctoolchain/usr/bin/swiftc
-- Check for working Swift compiler: /Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/buildbot_osx/intermediate-install/macosx-x86_64/Library/Developer/Toolchains/swift-PR-69714-926.xctoolchain/usr/bin/swiftc - works
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/buildbot_osx/swiftpm-macosx-x86_64/apple/Products/swift-system
[1/1][100%][2.133s] Linking Swift static library lib/libSystemPackage.a
env MACOSX_DEPLOYMENT_TARGET=12.0 /usr/local/bin/cmake -G Ninja -DCMAKE_MAKE_PROGRAM=/Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/buildbot_osx/ninja-build/ninja -DCMAKE_BUILD_TYPE:=Debug -DCMAKE_Swift_FLAGS='-sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -module-cache-path "/Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/buildbot_osx/swiftpm-macosx-x86_64/apple/Products/swift-system/module-cache"' -DCMAKE_Swift_COMPILER:=/Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/buildbot_osx/intermediate-install/macosx-x86_64/Library/Developer/Toolchains/swift-PR-69714-926.xctoolchain/usr/bin/swiftc -DCMAKE_C_COMPILER:=/Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/buildbot_osx/intermediate-install/macosx-x86_64/Library/Developer/Toolchains/swift-PR-69714-926.xctoolchain/usr/bin/clang -DCMAKE_AR:PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar -DCMAKE_RANLIB:PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -DCMAKE_C_FLAGS=-target x86_64-apple-macosx12.0 -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 /Users/ec2-user/jenkins/workspace/swift-PR-toolchain-macos/branch-main/swiftpm/../swift-system
```

**Comment by lorentey** [comment]
@swift-ci build toolchain macOS platform

**Comment by lorentey** [comment]
The last push removed the parts that updated the release/5.10 config, as I gave up on landing https://github.com/apple/swift/pull/69737.

**Comment by lorentey** [comment]
@swift-ci build toolchain

**Comment by lorentey** [comment]
@swift-ci build

**Comment by lorentey** [comment]
@swift-ci test

**Pull request merged**
