### PR TITLE
Fix build failure for importing NSUInteger as Int instead of the previously tested ok UInt

### PR DESCRIPTION
**Pull request by phausler**
fixes rdar://problem/30899471

### CODE REVIEW

**Comment by phausler** [comment]
@swift-ci please test and merge

**Comment by phausler** [comment]
@jrose-apple Why would the previous PR build and test ok with the failure? It seems rather fishy.

**Comment by jrose-apple** [comment]
[Terrible reasons](https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20170130/031327.html). I tried to stir up interest to fix this but there didn't seem to be any takers.

**Comment by jrose-apple** [comment]
You may be able to avoid this in the future by adding `[system]` to Foundation's module map, so that it'll be treated as a system module no matter where you import it from.

**Comment by phausler** [comment]
Do I need to add [system] to the shim module map?

**Comment by jrose-apple** [comment]
...ah. [Well, drat.](https://github.com/apple/swift/blob/master/lib/ClangImporter/ClangImporter.cpp#L326-L330). Can you make a PR for that?

**Comment by phausler** [comment]
for adding `[system]` to the module map like this?

```
module _SwiftCoreFoundationOverlayShims [system] {
  header "CoreFoundationOverlayShims.h"
}

module _SwiftFoundationOverlayShims [system] {
  header "FoundationOverlayShims.h"
}
```

**Comment by phausler** [comment]
@swift-ci please test

**Comment by jrose-apple** [comment]
No, to change the importer to always import shims as system modules. The only reason we didn't was to catch warnings, but we can add a test that just uses -Wsystem-headers.

**Comment by phausler** [comment]
so you are saying instead that I should change them to be:

```c
#define SHIMS_INCLUDE_FLAG "-isystem"
```

unconditionally no matter if it is NDEBUG or not?

**Comment by jrose-apple** [comment]
Yes, I think that's the right thing to do going forward.

**Comment by phausler** [comment]
so to be clear; the `[system]` change is inappropriate and should not be done then?

**Comment by phausler** [comment]
@swift-ci please test

**Review by jrose-apple — APPROVED** [review]

**Comment by phausler** [comment]
@swift-ci please test and merge

**Comment by gottesmm** [comment]
@phausler I think the OS X platform build failed again. The UI is just a bit messed up I believe. See:

https://ci.swift.org/job/swift-PR-osx/5888/

It looks like it is testing your latest commit and it failed.

**Comment by phausler** [comment]
@swift-ci please test and merge

**Comment by phausler** [comment]
```
Started by upstream project Swift Test and Merge build number 1566
originally caused by:
GitHub pull request #7979 of commit 125ef78a518e340a0bd6226bc6ecabfe478002fc, no merge conflicts.
```

that is the wrong sha1; it should be 00f3908c9cfe4c059ed3e97d0b5da71218165352
yet again another failure by the CI not picking up the right commits

**Comment by phausler** [comment]
the latest build is showing a build of 00f3908c9cfe4c059ed3e97d0b5da71218165352 which is correct
however this is now failing due to something that looks like something completely different?

```
/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/validation-test/compiler_crashers/28697-anonymous-namespace-findcapturedvars-checktype-swift-type-swift-sourceloc.swift:9:1: error: top-level statement cannot begin with a closure expression
09:58:04 {{extension{init(UInt=_=1 + 1 as?Int?Int){var f=nil?Int
09:58:04 ^
```

@jrose-apple should I just revert this whole ball of wax?

**Comment by jrose-apple** [comment]
It's possible we have a non-deterministic test. We should really try to get this in because it's blocking all our no-asserts builds. Let's just merge by hand once we pass a test.

@swift-ci Please smoke test macOS

**Comment by jrose-apple** [comment]
(I blame Past Me for leaving this trap in there.)

**Comment by dabrahams** [comment]
@jrose-apple I can force the merge even with tests failing if you think that's the right thing to do.

**Comment by jrose-apple** [comment]
It passed the smoke tests, so no force needed.

Thanks, Philippe!

**Pull request merged**
