### PR TITLE
Improve runtime errors for conditionally-Codable types

### PR DESCRIPTION
**Pull request by itaiferber**
**What's in this pull request?**
Improve the error message you see when you try to encode or decode types like `[String : Encodable]` or `[Decodable]`.

### CODE REVIEW

**Comment by itaiferber** [comment]
@swift-ci Please smoke test

**Review by milseman — APPROVED** [review]
LGTM. Thank you for the better errors!

**Comment by milseman** [comment]
Feel free to merge when you're ready, or ask me to do so.

**Comment by milseman** [comment]
When it's in, could you also cherry pick into a 4.0 PR, or ask me to do so?

**Comment by itaiferber** [comment]
@milseman Thanks! And yep, putting up against `swift-4.0-branch` momentarily.

**Pull request merged**
