### PR TITLE
[stdlib] Set, Dictionary: Flatten switch statements

### PR DESCRIPTION
**Pull request by lorentey**
The optimizer needs to work extra hard to process nested switch statements. Flatten them out to simplify optimization and to hopefully speed things up a little, especially around opaque stuff.

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci please smoke benchmark

**Comment by lorentey** [comment]
@swift-ci please test

**Comment by lorentey** [comment]
@swift-ci please smoke benchmark

**Comment by lorentey** [comment]
Hm, actually, this seems to only slow down the _modify accessor of the Values view. That's an easy fix.

I'll run some local benchmarks to see a bit more detail.

**Comment by airspeedswift** [comment]
Meanwhile I'm going to see if rebasing #18953 on top of this helps with that PR's regressions.

**Comment by lorentey** [comment]
@swift-ci please smoke benchmark

**Comment by lorentey** [comment]
@swift-ci please smoke benchmark

**Comment by lorentey** [comment]
@swift-ci please smoke benchmark

**Comment by lorentey** [comment]
@swift-ci please smoke benchmark

**Comment by lorentey** [comment]
@swift-ci please smoke benchmark

**Comment by lorentey** [comment]
@swift-ci please smoke test compiler performance

**Comment by lorentey** [comment]
@swift-ci please smoke test compiler performance

**Comment by lorentey** [comment]
@swift-ci please smoke test compiler performance

**Comment by lorentey** [comment]
@swift-ci please smoke test compiler performance

**Comment by lorentey** [comment]
The swapAt slowdown was due to a bug in my uniqueness checks; it should be fixed now.

**Comment by airspeedswift** [comment]
This got superseded, right?

**Comment by lorentey** [comment]
@airspeedswift Yes; a simplified variant landed, and then #19688 switched Set/Dictionary from using enums to Bridge Objects anyway. Closing.

**Pull request closed without merging**
