### PR TITLE
[6.0][Concurrency] Remove last usages of @_unsafeInheritExecutor

### PR DESCRIPTION
**Pull request by ktoso**
**Description**: We still had a few stray uses of @_unsafeInheritExecutor which we are intending to stop using entirely. The uses were in task cancellation handler (which I noticed), and withTaskGroup*.
**Scope/Impact**: Use the official way of inheriting isolation, rather than the fragile unofficial attribute. Impact on users is more correct inheritance of context, making APIs usable in actors in Swift 6 mode.
**Risk:** Low, Verified ABI method remain and only adds #isolation new API 
**Testing**: CI testing, added tests to verify behavior of task cancellation handler inside actor
**Reviewed by**: @hborla

**Original PR:** https://github.com/apple/swift/pull/73568
**Radar:** rdar://127874129

-- 

depends on #74563

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]
Looks great, thank you!

**Comment by ktoso** [comment]
Hmmm, there's one problem we need to discuss and solve about isolation of the closure still.
I.e. how should we properly handle: 
```
actor A {
  func g() { }
  var num: Int = 0

  func f() async throws {
    await withTaskGroup(...) { group in
      g()
      num += 1
    }
  }
}
```

Blocking on rdar://125078448

**Comment by ktoso** [comment]
Unblocked and cleaned up 🎉

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
Meh, depends on https://github.com/apple/swift/pull/74563 so this will fail this run.

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please test macOS

**Pull request merged**
