### PR TITLE
[Swift Rebranch] Cherry-picking swift changes from next branch

### PR DESCRIPTION
**Pull request by etcwilde**
This is a mega-merge of the necessary commits from the swift-next branch that were required to get things building.
These changes were merged into the next branch in the following PRs:
- https://github.com/apple/swift/pull/38182
- https://github.com/apple/swift/pull/38134
- https://github.com/apple/swift/pull/38135
- https://github.com/apple/swift/pull/38131
- https://github.com/apple/swift/pull/38136
- https://github.com/apple/swift/pull/38230

This is getting me pretty close to having things building locally. I'm seeing the build failure associated with https://github.com/apple/llvm-project/pull/3060, and still seeing the crashes that were associated with https://github.com/apple/llvm-project/pull/3074 so I think we need to go poke that repo to get much further. I am seeing some additional crashes in the coroutine splitting that 3074 doesn't fix, so we may need additional fixes for that.

### CODE REVIEW

**Comment by etcwilde** [comment]
@swift-ci please smoke test

**Review by edymtt — APPROVED** [review]

**Comment by edymtt** [comment]
@swift-ci please smoke test

**Comment by edymtt** [comment]
Retesting after merging https://github.com/apple/llvm-project/pull/3080

**Comment by etcwilde** [comment]
It looks like the auto merger is blocked. Investigating now.

**Comment by etcwilde** [comment]
I'm missing the fixes for the `TargetInfo::adjust` API change. Update coming soon after I verify that I have everything locally.

**Comment by etcwilde** [comment]
@swift-ci please smoke test

**Comment by etcwilde** [comment]
I'm going to go ahead and merge this so that we can break the dependency cycle with the rebranch auto merger. Once it runs cleanly, we should start seeing failures from the compiler rather than build failures.

**Pull request merged**
