### PR TITLE
Small SILCombiner cleanup

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@rajbarik Please take a look

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Review by atrick — COMMENTED** [review]
I think that field was replaced by a `lookupConformance` helper.

**Pull request merged**
