### PR TITLE
[ClangImporter] Non-class member initializers are not "factory" inits.

### PR DESCRIPTION
**Pull request by jrose-apple**
Structs and enums don't distinguish between different initializer kinds in the declaration, because there is no inheritance. This occurs with import-as-member.

This slurps in #8539, where I discovered the issue, because it was easy to add a test that way.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by milseman** [comment]
Whoops, did I drop the ball on this PR? @jrose-apple do you still want to do this?

The code looks ok to me, but I'm afraid my brain has purged all memory of any details pertaining to import-as-factory-init.

**Comment by jrose-apple** [comment]
I didn't actually manage to get it to pass tests, so I'm keeping it around for later. Thanks for following up, though.

**Comment by milseman** [comment]
ping?

**Comment by jrose-apple** [comment]
Have never gotten back to this one, sorry. (My gripe today was about PRs all opened in the last month.)

**Review by shahzadlone — APPROVED** [review]

**Comment by CodaFi** [comment]
@jrose-apple Do you still want to hold this open?

**Comment by jrose-apple** [comment]
It's still more correct in theory, but it definitely broke things at the time, and I don't know when I'd be back to it. I'll close-but-not-delete like the others.

**Pull request closed without merging**
