### PR TITLE
[Build] Pass in swift-syntax to SwiftPM

### PR DESCRIPTION
**Pull request by bnbarham**
SwiftPM is using swift-syntax for its new manifest refactorings.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Review by DougGregor — APPROVED** [review]
Thank you!

**Review by compnerd — APPROVED** [review]

**Comment by compnerd** [comment]
Going to merge this as it seems pretty straightforward and has passed CI.

**Pull request merged**
