### PR TITLE
ABIChecker: ignore accessors with forced static dispatch

### PR DESCRIPTION
**Pull request by nkcsgexi**
rdar://53776566

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci Please smoke test OS X platform

**Comment by slavapestov** [comment]
Here's another idea: instead of visiting _all_ accessors, including those randomly synthesized (you're calling `getAccessors()`), try calling `getOpaqueAccessors()`, which only returns exactly those which are ABI.

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Pull request merged**
