### PR TITLE
[Macros] Parse MacroExpansionExpr and MacroExpansionDecl

### PR DESCRIPTION
**Pull request by rxwei**
Introduce `MacroExpansionExpr` and `MacroExpansionDecl` and plumb them through. Parse them in roughly the same way we parse `ObjectLiteralExpr`.

The syntax is gated under `-enable-experimental-feature Macros`.

### CODE REVIEW

**Review by DougGregor — APPROVED** [review]
This all looks reasonable to me, thank you!

**Comment by rxwei** [comment]
@swift-ci please test

**Comment by rxwei** [comment]
@swift-ci please test

**Comment by rxwei** [comment]
@swift-ci please test and merge

**Pull request merged**
