### PR TITLE
[DiagnosticVerifier] More accurate wording when printing diagnostics from external sources

### PR DESCRIPTION
**Pull request by owenv**
https://github.com/apple/swift/pull/30028 marked these diags as "produced by Clang", but they can also often be notes attached to diagnostics in the verified file which point out declarations elsewhere. Change the message intro to read, "diagnostic produced elsewhere:" to avoid confusion in those cases.

### CODE REVIEW

**Comment by owenv** [comment]
@swift-ci please smoke test

**Comment by owenv** [comment]
cc @martinboehme , @gribozavr

**Comment by owenv** [comment]
@swift-ci smoke test

**Comment by martinboehme** [comment]
Sorry, completely missed this when you originally sent it.

The wording "diagnostic produced elsewhere" seems strangely vague, but I also can't think of a good alternative -- and this is definitely better than just assuming the diagnostic came from Clang.

**Review by gribozavr — APPROVED** [review]

**Pull request merged**
