### PR TITLE
SwiftCompilerSources: introduce the AST module

### PR DESCRIPTION
**Pull request by eeckstein**
As the optimizer uses more and more AST stuff, it's now time to create an "AST" module.
Initially it defines following AST datastructures:
* declarations: `Decl` + derived classes
* `Conformance`
* `SubstitutionMap`
* `Type` and `CanonicalType` (pls LMK if you think `CanType` is better)

Some of those were already defined in the SIL module and are now moved to the AST module.
This change also cleans up a few things:
* proper definition of `NominalTypeDecl`-related APIs in `SIL.Type`
* rename `ProtocolConformance` to `Conformance`
* use `AST.Type`/`AST.CanonicalType` instead of `BridgedASTType` in SIL and the Optimizer
* rename `AssociatedTypeProtocolWitness` -> `AssociatedConformanceWitness` in SILWitnessTable
* implement WitnessTable.Entry as enum
* remove "public" from the Optimizer module, because it's a leaf module
* on the C++ side, fix casting of Decl to GenericContext

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci clean test

**Comment by eeckstein** [comment]
@swift-ci clean test

**Review by atrick — COMMENTED** [review]
Great, thanks!

Minor point: I noticed the removal of many `public` SIL APIs. But those APIs should mostly move into the SIL module instead. The SIL module should contain everything essential to working with SIL. Including verification and unit testing. If the definition of valid SIL depends on any analysis, then we want that in the SIL module.
Dominators and dead-end blocks are part of the definition of SIL. Probably alias analysis as well.

**Comment by eeckstein** [comment]
That would require a bigger reorganization, because those utilities need a `Context` which is part of the Optimizer module.

**Comment by eeckstein** [comment]
@swift-ci test linux

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Pull request merged**
