### PR TITLE
[CSApply] Use declaration context associated with rewriter

### PR DESCRIPTION
**Pull request by xedin**
`ExprRewriter` could be created for a solution application target,
which could have its own declaration context if it's e.g. an inner
statement or a pattern binding.

### CODE REVIEW

**Review by hborla — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
No new issues in the source compat suite still problems with fopen and sandbox.

**Pull request merged**
