### PR TITLE
Revert "[cxx-interop] A few cleanups and fixes for function templates."

### PR DESCRIPTION
**Pull request by shahmishal**
Reverts apple/swift#41217

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci smoke test

**Comment by zoecarver** [comment]
Thank you Mishal.

**Comment by shahmishal** [comment]
```
error: link command failed with exit code 1 (use -v to see invocation)
Undefined symbols for architecture x86_64:
  "_$s11SwiftDriver21ModuleDependencyGraphC5phaseAC5PhaseOvw", referenced from:
      _$s11SwiftDriver21ModuleDependencyGraphC0aB5TestsE14simulateReload___18includePrivateDeps19hadCompilationErrorSaySiGSi_SDyAD04MockD4KindOSaySSGGSSSgS2btFyyXEfU_ in ModuleDependencyGraphTests.swift.o
      _$s11SwiftDriver21ModuleDependencyGraphC0aB5TestsE14simulateReload___18includePrivateDeps19hadCompilationErrorSaySiGSi_SDyAD04MockD4KindOSaySSGGSSSgS2btFyyXEfU_TA in ModuleDependencyGraphTests.swift.o
```

**Comment by shahmishal** [comment]
Failure is unrelated, merged

**Pull request merged**
