### PR TITLE
Fix test for 32 bit platforms by removing align from FileCheck pattern.

### PR DESCRIPTION
**Pull request by gottesmm**
Fix test for 32 bit platforms by removing align from FileCheck pattern.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci Please smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci Please test and merge

**Comment by gottesmm** [comment]
I killed the smoke test and merge, since I want to do a full test here.

**Comment by gottesmm** [comment]
@swift-ci Please test and merge

**Comment by gottesmm** [comment]
@swift-ci Please test and merge

**Comment by jrose-apple** [comment]
"REQUIRES=macosx" is very different from "disable for 32-bit". What are you actually trying to do?

**Comment by gottesmm** [comment]
I just wanted to disable it for 32-bit. Otherwise, I would need to create two different runs one for 32 bit and one for 64 bit. That just adds redundant time to the build with no benefit.

I am pretty sure since I specified it as an OS check, this is fine.

**Comment by jrose-apple** [comment]
I'm fine with you disabling 32-bit, but you've also disabled iOS and Linux testing too. That seems like a bad idea.

It looks like there's a `REQUIRES: PTRSIZE=64`; can you use that instead? Or `REQUIRES: CPU=x86_64`.

**Comment by gparker42** [comment]
One non-disabling solution is:
1. add `--check-prefix=CHECK --check-prefix=CHECK-%target-ptrsize` to your `FileCheck` invocation
2. write both `CHECK-32:` and `CHECK-64:` lines for your checks that are pointer size specific.

**Comment by gottesmm** [comment]
@gparker42 yea... I was trying to be lazy and not do that. I think jordan is right about PTRSIZE=64.

**Pull request merged**
