### PR TITLE
[Build] Add option to alter default location of module cache in Linux

### PR DESCRIPTION
**Pull request by edymtt**
This is meant to support parallel CI runs on the same Linux bot, so that
they don't share the module cache and reduce (hopefully) the likelihood
of issues related to invalid signatures.

When the option is enabled, the environment variable `XDG_CACHE_HOME`
is explicitly set in `build-script` and should be inherited by all the
child processes.
Currently we don't check the operating system before setting the
variable (since it should be a noop for other OSes).

Addresses rdar://73887745

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci please python lint

**Comment by edymtt** [comment]
@swift-ci please smoke test

**Review by compnerd — APPROVED** [review]

**Review by shahmishal — APPROVED** [review]
Thanks! LGTM. 

Can you also update the preset to use this flag for Linux? It does not have to be in this PR.

**Comment by edymtt** [comment]
Sure -- I was planning to do that as a separate step (to both catch unanticipated fallout and have a bit of control over the "rollout" of this flag)

**Pull request merged**
