### PR TITLE
Update WindowsBuild.md

### PR DESCRIPTION
**Pull request by bulbazord**
Let's make sure that the LLVM/Clang builds match the other projects builds.

cc @compnerd

### CODE REVIEW

**Comment by compnerd** [comment]
This is intentionally different.  This actually generates a slightly faster clang/LLVM (stupid `cl`).  That's why I opted to use the `Release` mode with `LLVM_ENABLE_PDB`.  It would be nice to actually have swift learn the same idiom for the time being (until `RelWithDebInfo` on LLVM does the same thing as `Release` + `LLVM_ENABLE_PDB`).

**Comment by xiaobai** [comment]
In that case, the paragraph above the LLVM/Clang build instructions should be different, no?

**Comment by compnerd** [comment]
Yes, please adjust that.  It should be that either everything is `Debug` or everything is a `Release` variant.

**Comment by xiaobai** [comment]
@compnerd: I have adjusted it, as well as added another commit to update the doc further with something else I found.

**Comment by compnerd** [comment]
@swift-ci please smoke test and merge

**Review by compnerd — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
