### PR TITLE
[caller-analysis] Change the dumping format to be a yaml format and u…

### PR DESCRIPTION
**Pull request by gottesmm**
…pdate tests to use that format.

The current dumping format consists of 1 row of information per function. This
will become unweildy to write patterns for when I add additional state to
FunctionInfo.

Instead, this commit converts the dumping format of the caller analysis into a
multi line yaml format. This yaml format looks as follows:

```
  ---
  calleeName:      closure1
  hasCaller:       false
  minPartialAppliedArgs: 1
  partialAppliers:
    - partial_apply_one_arg
    - partial_apply_two_args1
  fullAppliers:
  ...
```

This can easily expand over time as we expand the queries that caller analysis
can answer.

As an additional advantage, there are definitely yaml parsers that can handle
multiple yaml documents in sequence in a stream. This means that by running via
sil-opt the caller-analysis-printer pass, one now will get a yaml description of
the caller analysis state, perfect and ready for analysis.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Review by aschwaighofer — COMMENTED** [review]
LGTM. The const'ification of getCallerInfo is a little cheeky.

**Comment by gottesmm** [comment]
@aschwaighofer I agree, but I think it should be fine. Passes that are using this shouldn't be modifying the callgraph while using this IMO. That being said, let me add some invariants to force this.

**Comment by gottesmm** [comment]
Erm... I think I have a way to do that.

**Pull request merged**
