### PR TITLE
Split the NO_DYLD CMake flag into separate HAS_DLADDR and STATIC_IMAGE_INSPECTION flags

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by mikeash — APPROVED** [review]

**Review by compnerd — COMMENTED** [review]
There are a number of instances of `SWIFT_RUNTIME_STATIC_IMAGE_INSPECTION` ... which perhaps I missed it, but I don't believe is ever defined?  If that was supposed to be for the "static single image" case, I think that `SWIFT_RUNTIME_STATIC_IMAGE_INSPECTION` is enormously better than `SWIFT_RUNTIME_SINGLE_STATIC_IMAGE`.

That leads to my second thought on this patch.  Note, this is entirely subjective, and very likely a misunderstanding on my part.  When using swift stdlib in a static library, you can't have more than one image technically right?  If you do, none of the other ones can use swift - because you risk ODR violations for the runtime.  So, Im not sure that the "single static image" is the right thing to use.

**Comment by kubamracek** [comment]
> SWIFT_RUNTIME_STATIC_IMAGE_INSPECTION

Ah, yes, that should be SWIFT_RUNTIME_SINGLE_STATIC_IMAGE.

> That leads to my second thought on this patch. Note, this is entirely subjective, and very likely a misunderstanding on my part. When using swift stdlib in a static library, you can't have more than one image technically right? If you do, none of the other ones can use swift - because you risk ODR violations for the runtime. So, Im not sure that the "single static image" is the right thing to use.

Excellent point, let me elaborate on that. I think it's not just static vs. dynamic, there's technically at least 3 levels that all can (be made to) work with different nuances:

(1) A fully statically linked binary. No dyld or ld.so involved at all. No problem there, since there really *is* only a single image. Unfortunately, on Darwin, it's very hard to build/run such programs, because you'd have to bundle your own Libc (and there's other complications). But if your target platform/environment does provide static libraries of Libc, and something like crt0.o, etc., then it's actually useful to build+run this way, with SWIFT_RUNTIME_SINGLE_STATIC_IMAGE=1, and the name of this config var actually reflects reality. ImageInspection does not need to worry about other modules, it can just peek at its own sections with the magical linker symbols.

(2) Statically linked libswiftCore.a with all other Swift code (libraries, app client code), but still producing a dynamic executable that will run with dyld/ld.so, except that all Swift code and all Swift runtime support has been folded into a single module (the executable). This is how the 'freestanding' preset is being tested in ci.swift.org right now — out of necessity mostly, because I don't think we can get mode no. 1 to reasonably work on a Darwin host OS. When you run such a program, there are other dynamic modules present (system libraries). You are absolutely correct that there's an assumption that none of the other modules contain Swift code. As long as this assumption holds, it doesn't really matter whether ImageInspection only scans its own module, or whether it asks dyld/ld.so for a list of all modules and scans those too. I think our testing job on ci.swift.org should probably have SWIFT_RUNTIME_SINGLE_STATIC_IMAGE set to 0, to be correct, but I don't expect anything to change even if it's 1.

(3) Dynamic libswiftCore.so/.dylib, the usual "normal" way most users use Swift. SWIFT_RUNTIME_SINGLE_STATIC_IMAGE=0, of course.

**Comment by kubamracek** [comment]
With that all said... would you prefer the config var to be called `SWIFT_RUNTIME_STATIC_IMAGE_INSPECTION` over `SWIFT_RUNTIME_SINGLE_STATIC_IMAGE`?

**Comment by compnerd** [comment]
I think that I would prefer `SWIFT_RUNTIME_STATIC_IMAGE_INSPECTION`.  FWIW, I believe that even on Linux, the first scenario is difficult to support - and while plausible with musl, most Linux distributions are glibc based still.

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by kubamracek** [comment]
@swift-ci please test macOS platform

**Comment by kubamracek** [comment]
@compnerd does this look good now?

**Review by compnerd — APPROVED** [review]

**Pull request merged**
