### PR TITLE
[5.7][IRGen] Emit opaque type descriptors into client for `@_alwaysEmitI…

### PR DESCRIPTION
**Pull request by xedin**
…ntoClient` decls

Cherry-pick of https://github.com/apple/swift/pull/60010
Cherry-pick of https://github.com/apple/swift/pull/60048

--- 

- Explanation:

If opaque result type has availability conditions and is associated with
an `@_alwaysEmitIntoClient` declaration, its metadata descriptor has to
be emitted into a client module because availability blocks in the body of
such inlined declaration are allowed to produce different underlying types
at runtime and cannot be substituted at compile-time.

- Scope: `@_alwaysEmitIntoClient` declarations that return opaque result type with availability conditions being used for back-deployment purposes.

- Main Branch PR: https://github.com/apple/swift/pull/60010, https://github.com/apple/swift/pull/60048

- Resolves: rdar://82791712

- Risk: Very low

- Reviewed By: @aschwaighofer 

- Testing:  Added a regression test-case to the suite.

Resolves: rdar://82791712
(cherry picked from commit 76ab70c3a8602c8b51073737d2e3a13b80bb5dd5)

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Comment by airspeedswift** [comment]
are you all calling it `@_alwaysInlineIntoClient` to mess with me or is there a new attribute I don't know about...

**Review by airspeedswift — APPROVED** [review]

**Comment by xedin** [comment]
@airspeedswift supposed to be Emit* 🤦‍♂️

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test

**Pull request merged**
