### PR TITLE
Protocol superclass constraints part 4

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes rdar://problem/38077232 / https://bugs.swift.org/browse/SR-5581, and rdar://problem/34812895 / https://bugs.swift.org/browse/SR-6000.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@aciidb0mb3r Any ideas?

```
00:33:32 Failing Tests (6):
00:33:32     swift-package-tests :: swift-build-self-host.py
00:33:32     swift-package-tests :: swift-build.txt
00:33:32     swift-package-tests :: swift-package-with-spaces.txt
00:33:32     swift-package-tests :: test-complex-xctest-package/test-xctest-package.txt
00:33:32     swift-package-tests :: test-foundation-package/test-foundation-package.txt
00:33:32     swift-package-tests :: test-xctest-package/test-xctest-package.txt
```

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by aciidb0mb3r** [comment]
@slavapestov sorry about that, I’ll fix them first thing in the morning.

**Comment by aciidb0mb3r** [comment]
Disabled the tests in https://github.com/apple/swift-integration-tests/commit/a39ef351c003c74b5a119aa5dab3b6231d045adf

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Comment by slavapestov** [comment]
The source compat suite is broken right now. I'll keep an eye on the bots after merging this.

**Pull request merged**
