### PR TITLE
[stdlib] Use capacity when selecting buckets in hashed collections

### PR DESCRIPTION
**Pull request by natecook1000**
This addresses quadratic performance when rebuilding a hashed collection by iterating over the contents in hash-storage order. This fix mixes the capacity of the storage with each element's hash value before further hashing and squeezing the value to that capacity, guaranteeing different layouts of a hash's elements at different capacities.

Resolves [SR-3268](https://bugs.swift.org/browse/SR-3268).

### CODE REVIEW

**Comment by natecook1000** [comment]
@swift-ci Please benchmark

**Comment by natecook1000** [comment]
@swift-ci Please benchmark

**Comment by natecook1000** [comment]
@Gankro What do you think of this fix? Seems like there's a small hashing penalty, but this uses only the information already in a hashed collection, so we don't need to store anything additional. I added the "HashQuadratic" benchmark so we can see the improvement; I'm not sure what benchmark "173" is, but it also seems improved ¯\_(ツ)_/¯

**Comment by Gankro** [comment]
Capacity is always a power of two, so this is just flipping a single bit in the hash. But then _squeezeHashValue mixes it, so that bit's affects should properly shuffle a bit. I suggest moving this logic into _squeezeHashValue just so it's clear, and all the hash hacks are properly centralized.

This seems fine; it doesn't make our hashing architecture any less principled than it already is (wrt determined attackers), and seems to suppress the perf issues reasonably well.

**Comment by natecook1000** [comment]
Great point, thanks! Moved into _squeezeHashValue, along with the explanation.

**Comment by natecook1000** [comment]
@swift-ci Please smoke test

**Comment by natecook1000** [comment]
@swift-ci Please benchmark

**Comment by natecook1000** [comment]
@swift-ci Please smoke test

**Comment by natecook1000** [comment]
@swift-ci Please smoke test

**Comment by natecook1000** [comment]
@swift-ci Please smoke test Linux platform

**Comment by dabrahams** [comment]
would it work just as well to iterate the elements in reverse when rebuilding, or does that not help?

**Comment by natecook1000** [comment]
Not sure! I'm a little stuck on this test failure so I'll give it a try.

**Comment by natecook1000** [comment]
@dabrahams No dice—not seeing any improvement in #8071, it looks like going in reverse still has the same linear seek problems as going forward (which makes sense, they're still all in a line). Having a different preferred bucket at each capacity level solves the issue because you essentially get a different "random" distribution at each level.

**Comment by natecook1000** [comment]
@swift-ci Please smoke test

**Comment by natecook1000** [comment]
@swift-ci Please smoke test Linux platform

**Comment by natecook1000** [comment]
@swift-ci Please smoke test

**Comment by Gankro** [comment]
The curse is over 😩

**Pull request closed without merging**
