### PR TITLE
Add locations from external modules to cursor info results

### PR DESCRIPTION
**Pull request by bnbarham**
Use .swiftsourceinfo to include location information for results from external modules. Also add line and column so that clients don't need to map them from the offset.

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
@swift-ci please test Linux platform

**Comment by bnbarham** [comment]
Added target triple to sourcekitd requests in the multi module test.

@swift-ci please test

**Comment by bnbarham** [comment]
I forgot to check the symbol graph result in the multi-module test. Adding that now but the comments aren't showing up - so this isn't ready to merge yet!

**Comment by bnbarham** [comment]
Turned out we weren't attaching comments when emitting only a .swiftsourceinfo. I've changed that to now attach them (in practice it doesn't really matter, usually .swiftdoc would be output which *would* attach comments). @nkcsgexi was not attaching them intentional?

@swift-ci please test

**Comment by bnbarham** [comment]
Windows failure was \\ vs /.

@swift-ci please test

**Comment by bnbarham** [comment]
@swift-ci please test macOS platform

**Comment by bnbarham** [comment]
Another spurious (but different) failure

@swift-ci please test macOS platform

**Comment by bnbarham** [comment]
@swift-ci please test macOS platform

**Comment by bnbarham** [comment]
@swift-ci please test Windows platform

**Review by benlangmuir — APPROVED** [review]

**Pull request merged**
