### PR TITLE
[benchmark] Legacy Factor

### PR DESCRIPTION
**Pull request by palimondo**
This PR adds optional `legacyFactor` to the `BenchmarkInfo`, which allows for linear modification of constants that unnecessarily inflate the base workload of benchmarks, while maintaining the continuity of log-term benchmark tracking.

For example, if a benchmark uses `for _ in N*10_000` in its run function, we could lower this to `for _ in N*1_000` and adding a `legacyFactor: 10` to its `BenchmarkInfo`.

Note that this doesn’t affect the real measurements gathered from the `--verbose` output. The `BenchmarkDoctor` has been slightly adjusted to work with these real samples, therefore `Benchmark_Driver check` will not flag these benchmarks for slow run time reported in the summary, if their real runtimes fall into the recommended range.

This PR also modifies benchmarks with long runtimes to use the `legacyFactor` and lowers their base workloads, so that they run in around the 1ms mark.

### CODE REVIEW

**Comment by palimondo** [comment]
@eeckstein Please run benchmark here. A have a pending commit for legacy factor of `ArrayAppend*`, but it depends in removing the setup overhead from PR #20048.

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Comment by palimondo** [comment]
@eeckstein It looks like the demonstration of `legacyFactor` has been successful: the modified benchmarks reported no changes.

I'm a bit worried by the amount of other noise reported here. Any thoughts what's causing it? Why are there so many code size changes? Somethings smells 🐟🐠🐡 here...

**Comment by palimondo** [comment]
@eeckstein Let's land this as is and next I'll go through the whole Swift Benchmark Suite and apply the `legacyFactor` where appropriate. This will give us much more robust and more precise measurements when using `Benchmark_Driver`. As a side effect, it will also make running smoke bench faster.

**Comment by eeckstein** [comment]
The code size changes are clear: you added a field to BenchmarkInfo. That adds to the initialization code in basically every benchmark source file.
I'm also not surprised by the reported performance differences. That can be code alignment issues again.

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by eeckstein** [comment]
We already page-align all the benchmark modules. But that does not help if there are code changes inside the benchmark files.

**Pull request merged**
