### PR TITLE
[move-only] Preliminary work for wiring up debug info

### PR DESCRIPTION
**Pull request by gottesmm**
Just doing some cleanups/fixups to the consume operator debug info implementation before I wire up move only types to it. Just slicing off parts of a larger patch.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Review by eeckstein — APPROVED** [review]
lgtm

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
Did it in a different pr

**Pull request closed without merging**
