### PR TITLE
[test] Make sure tests use just-built libraries if use_os_stdlib isn't set

### PR DESCRIPTION
**Pull request by lorentey**
In some cases, tests are trying to load OS-supplied libswift* libraries instead of the ones we just built. (This was uncovered by the recent work to create a new stdlib module in #27229.)

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test Windows platform

**Comment by lorentey** [comment]
The Windows build is progressing at https://ci-external.swift.org/job/swift-PR-windows/567/console; it's assigned to 8eee4f3, but nevertheless it seems to build the correct hash.

**Comment by lorentey** [comment]
macOS failure is unrelated; other recent builds have been failing the same way.

```
21:46:25 Failing Tests (1):
21:46:25     Swift(iphonesimulator-i386) :: TBD/app-extension.swift
```

**Comment by lorentey** [comment]
@swift-ci smoke test macOS platform

**Comment by lorentey** [comment]
@swift-ci smoke test macOS platform

**Pull request merged**
