### PR TITLE
[wasm][build] Recognize wasi-wasm32 as valid host

### PR DESCRIPTION
**Pull request by kateinoigakukun**
wasi-wasm32 support in build system was added in
b1236e92f9c8f07620f4993486fbb872c9575954 but we forgot to add it to the host for the case when we are building the standalone stdlib for the target.

### CODE REVIEW

**Comment by kateinoigakukun** [comment]
@swift-ci Please smoke test

**Review by MaxDesiatov — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
@swift-ci build toolchain

**Comment by MaxDesiatov** [comment]
@swift-ci build toolchain UBI9

**Comment by MaxDesiatov** [comment]
@swift-ci build toolchain Linux

**Comment by MaxDesiatov** [comment]
@swift-ci build toolchain Linux

**Pull request merged**
