### PR TITLE
[cxx-interop] Don't import C++ objects that we can't destroy.

### PR DESCRIPTION
**Pull request by zoecarver**
Don't import C++ objects if they have a public destructor that is not deleted.

### CODE REVIEW

**Comment by hlopko** [comment]
I'm a bit torn on this. I can imagine a reasonable C++ type with a deleted destructor, for example singleton, or a type that assumes to be allocated in an arena. Importing these types would be useful imho.

Maybe instead of not importing them we could generate a destructor that throws?

**Comment by zoecarver** [comment]
Fair enough, another example that we might want to support is a type with static members. 

Maybe we could emit a diagnostic when constructing the object. I can't think of an example where Swift would be responsible for destroying the object and would not have created it. 

I'm very hesitant to throw in the destructor. Worst case we should probably create an `unreachable`/`fatalError`. But, ideally, we'd never actually hit a deleted destructor. I think we should try to find a solution where we always emit a diagnostic at some point before emitting a call to a deleted destructor. Then we can keep the assertion in IRGen.

**Comment by CodaFi** [comment]
I agree with the idea of a fatal deinitializer thunk. There's code in SILGen to do this today for constructors.

**Comment by rjmccall** [comment]
We should not import a type that we can't implement value operations for right now.  If we want to start supporting types with reduced value operations and then diagnosing uses of unsupported operations, we can find proper ways to do that incrementally, as the need arises.

**Review by rjmccall — APPROVED** [review]
Your commit message is backwards in parts.

**Comment by zoecarver** [comment]
Ah, yes, I'll fix that. 

I agree that is the best course of action. I think we should have support for importing this kind of type, but maybe not right now. At least not in this patch. As you said, we can add proper support and diagnostics down the road, when the need arises.

**Comment by zoecarver** [comment]
@swift-ci please smoke test.

**Comment by zoecarver** [comment]
@swift-ci please smoke test.

**Comment by zoecarver** [comment]
@swift-ci please smoke test Linux

**Comment by zoecarver** [comment]
@swift-ci please smoke test OS X

**Comment by zoecarver** [comment]
@swift-ci please smoke test OS X

**Pull request merged**
