### PR TITLE
[ASTGen] Generate standalone macro expansions

### PR DESCRIPTION
**Pull request by rintaro**
Support MacroExpansionExprSyntax and MacroExpansionDeclSyntax. For now, disable ASTGen for macro expanded source file.

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Review by hamishknight — APPROVED** [review]

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test Linux

**Pull request merged**
