### PR TITLE
[build-script] Use the build-script-impl from the swift repo that invoked build-script.

### PR DESCRIPTION
**Pull request by gottesmm**
[build-script] Use the build-script-impl from the swift repo that invoked build-script.

In the past if one wanted to be able to develop using multiple swift repos, one
was often stymied by build-script always using build-script-impl from the swift
directory. This includes the case where one invokes the build-script from a
hypothetical directory called swift-2.

This is just a productivity enhancement.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci Please python lint

**Comment by gottesmm** [comment]
@swift-ci Please smoke test and merge

**Comment by gottesmm** [comment]
Looks like some stripped off the executable bit from python lint. I ran it locally and everything passed.

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
I fixed python lint in this commit.

**Comment by gottesmm** [comment]
@swift-ci python lint

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by hughbe** [comment]
I'm slightly confused with this. This isn't the repo name, but actually the repo path for swift:
```py
...
def _get_default_swift_repo_name():
    result = ""

    # Are we in a Swift checkout? Start from this file and check its parent
    # directories.
    #
    # $SWIFT_SOURCE_ROOT/$SWIFT_REPO_NAME/utils/SwiftBuildSupport.py
    (swift_path, parent_dirname) = os.path.split(os.path.dirname(__file__))
    if parent_dirname != "utils":
        return result
    if not os.path.exists(os.path.join(swift_path, 'CMakeLists.txt')):
        return result
    return swift_path


# Set SWIFT_REPO_NAME in your environment to control the name of the swift
# directory name that is used.
SWIFT_REPO_NAME = os.environ.get(
    "SWIFT_REPO_NAME", _get_default_swift_repo_name())
print(SWIFT_REPO_NAME)
...
```

> C:\Users\hughb\Documents\GitHub\swift\swift

**Comment by hughbe** [comment]
This doesn't actually matter, though:

```py
print(os.path.join('C:/Users', 'C:/Users/hugh'))
```

This just prints `C:/Users/hugh`, as it adjusts for relative paths

**Pull request merged**
