### PR TITLE
[xcodegen] Enable buildable folders by default

### LINKED ISSUE #77418: Adopt buildable folders in swift-xcodegen
Xcode 16 introduced the concept of "buildable folders", folder references that have an associated target from which to pull build settings. We ought to see if we can adopt this in swift-xcodegen to avoid the need to regenerate the project when new files are added.

### PR DESCRIPTION
**Pull request by hamishknight**
I've been living on this for a bit without issue, enable by default. Filed #77790 to track splitting up "umbrella" targets such that they can benefit.

Resolves #77418

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please smoke test

**Comment by hamishknight** [comment]
Bah

@swift-ci please test Windows

**Comment by hamishknight** [comment]
@swift-ci please smoke test

**Comment by hamishknight** [comment]
@swift-ci please smoke test

**Review by AnthonyLatsis — APPROVED** [review]

**Pull request merged**
