### PR TITLE
[Dependency Scanner] Add option to execute an import prescan

### PR DESCRIPTION
**Pull request by artemcm**
With this option enabled, the dependency scanner gathers all import statements in source files of the main module (non-transitive) and outputs a list of imported modules.
This will be used by build systems and the swift-driver as a way to avoid redundant re-scanning in incremental contexts.

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci please smoke test

**Review by nkcsgexi — APPROVED** [review]
I presume this also works in batch scanning mode?

**Comment by artemcm** [comment]
> I presume this also works in batch scanning mode?

👍 Now it does.
I thought `scanDependencies` was called in the batch code-path, but I went to double-check and it turns out it doesn't.

**Comment by artemcm** [comment]
@swift-ci please smoke test

**Comment by artemcm** [comment]
@swift-ci please smoke test Windows platform

**Comment by artemcm** [comment]
@swift-ci please smoke test Windows platform

**Pull request merged**
