### PR TITLE
IRGen: Deal with broken AST from batch mode

### PR DESCRIPTION
**Pull request by aschwaighofer**
rdar://59552858

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Review by slavapestov — APPROVED** [review]

**Review by slavapestov — APPROVED** [review]
A better fix might be to change IRGen's type lowering to accept ErrorType and produce a zero-sized or uninhabited type or something.

**Comment by aschwaighofer** [comment]
@swift-ci Please test macOS

**Comment by aschwaighofer** [comment]
@swift-ci please clean test macOS

**Comment by slavapestov** [comment]
Yeah, looking at this again I suggest sinking the fix down into the type lowering code. Otherwise you'll hit a similar crash when iterating over the stored properties of structs and enums.

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Review by slavapestov — APPROVED** [review]

**Comment by slavapestov** [comment]
Thank you!

**Comment by aschwaighofer** [comment]
@swift-ci please test

**Pull request merged**
