### PR TITLE
[simplify-cfg] Only check if we can remove releases by performing simple jump threading if our block argument is not a trivial type.

### PR DESCRIPTION
**Pull request by gottesmm**
Eliminates unnecessary work and reduces compile time.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Review by meg-gupta — APPROVED** [review]

**Comment by gottesmm** [comment]
@swift-ci smoke test OS X platform

**Comment by gottesmm** [comment]
@swift-ci smoke test OS X platform

**Comment by atrick** [comment]
I'm not sure what the intention is here since `tryJumpThreading` is still disabled with OSSA. If it's meant to be a short-term placeholder for fully migrating the code then please use `TODO: OSSA`

**Comment by gottesmm** [comment]
@swift-ci smoke test macOS platform

**Comment by meg-gupta** [comment]
@swift-ci smoke test macOS platform

**Pull request merged**
