### PR TITLE
[stdlib] Addressing Dmitri Gribenko's feedback re #2993

### PR DESCRIPTION
**Pull request by austinzheng**
#### What's in this pull request?

Improvements per comments on #2993 @gribozavr @moiseev 

(Will update this space once OS X tests pass or fail)

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

Changes:
- Moved only-used-once helper methods into call sites
- Parameterized tests that might expect a crash
- Fixed some comments and formatting; renamed some test helper APIs

### CODE REVIEW

**Comment by gribozavr** [comment]
@swift-ci Please test and merge

**Comment by austinzheng** [comment]
@gribozavr Sorry, you'll have to trigger the CI again :(. I pushed a fix to a unit test right after you started it.

**Comment by austinzheng** [comment]
You were absolutely right, by the way; at least one error in the test definitions was uncovered by parameterizing the tests.

**Comment by gribozavr** [comment]
@swift-ci Please test and merge

**Pull request merged**
