### PR TITLE
fix documentation comment of flatMap<SegmentOfResult : Sequence>

### PR DESCRIPTION
**Pull request by creaaa**
Hello, I'm Masa, Swift lover.

I noticed that one documentation comment remained old and doesn't change since 2 years ago, so I fixed it.

Is this PR acceptable?
This PR only includes a fixed single file.
I really appreciate it if you would tell me if there is a defect in this PR.

I'm deeply grateful to you for all your passionate work.

Thank you,
Masa

### CODE REVIEW

**Comment by harlanhaskins** [comment]
Good catch, @creaaa! This LGTM, but I want @natecook1000 to spot-check it if he has time.

**Review by harlanhaskins — APPROVED** [review]

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test

**Comment by natecook1000** [comment]
@creaaa Thanks so much!

**Comment by creaaa** [comment]
Thanks too, @harlanhaskins, @natecook1000 !
This made my love to Swift unwavering. I'll keep learning to contribute more!

**Pull request merged**
