### PR TITLE
swift-module-digester: include non-resilient class decls when checking ABI stability.

### PR DESCRIPTION
**Pull request by nkcsgexi**
Also regenerate the ABI checker baseline after recent fixes.

### CODE REVIEW

**Comment by nkcsgexi** [comment]
By `methods`, do you mean any `AbstractFunctionDecl`?

**Comment by slavapestov** [comment]
@nkcsgexi Well, mostly FuncDecls only. ConstructorDecls have more complex rules.

Perhaps the best thing would be to dump the vtable layout using the SILVTableVisitor, and compare that, instead of looking at AST declarations.

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@slavapestov the sequence check for non-final functions in non-resilient class has been added. Mind taking another look?

**Pull request merged**
