### PR TITLE
Enhancements to Codable API

### PR DESCRIPTION
**Pull request by itaiferber**
**What's in this pull request?**
* Adds conformance of `Optional` to `Codable`
* `encode(...)` arguments are no longer `Optional`; `Optional` values go through generic version
* `encodeIfPresent` added to `KeyedEncodingContainerProtocol` to mirror `decodeIfPresent`
* `Optional` values synthesize `encodeIfPresent(...)` and `decodeIfPresent(...)` calls instead of `encode(...)` and `decode(...)`
* `encodeNil()` and `decodeNil()` added as proper primitives on `SingleValueEncodingContainer` and `SingleValueDecodingContainer`, as well as `encode<T : Encodable>(_: T)` and `decode<T : Decodable>(_: T) throws -> T`
* `JSONEncoder` and `PropertyListEncoder` updated to reflect these changes

> NOTE: These changes are currently going through API review, but we want to have them up and ready unless something changes. These changes will be reflected in the swift-evolution proposal, and will go out to swift-evolution.

### CODE REVIEW

**Comment by itaiferber** [comment]
@swift-ci Please smoke test

**Comment by itaiferber** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
I don't think we want to take the unconditional conformance of Optional to Codable. Someone could accidentally depend on that in a case where the conditional conformance would said no, and then us changing it would break source compatibility. Please continue to special-case Optional.

**Comment by itaiferber** [comment]
@jrose-apple The same case can be made for `Array`, `Set`, and `Dictionary`, which are already in... We cannot change the rest of the API once this is in, and this is a really important part of the feature.

Encoding/decoding will fail at runtime (so you can't actually encode a non-`Codable` `Optional` value and rely on it in any way), but the commit I just pushed will prevent derived conformance if you've got properties of any of these types if they won't actually be `Codable` at runtime.

**Comment by jrose-apple** [comment]
I don't think it's correct for Array, Set, or Dictionary either, and I'm sorry I didn't catch that the first time around. That still doesn't mean you can introduce a pitfall like this, though. It's *much* easier to add the API that handles these wrapping types, and then later (or even now) provide a default implementation for them.

**Comment by itaiferber** [comment]
@jordan-rose This is a stop-gap until conditional conformance lands. We can't prevent people from encoding arrays, sets, dictionaries, and optionals. If we add a combinatorial explosion of overloads supporting these types, we cannot remove them later, nor can we handle recursive types with them.

Let's take this to email though. Please CC @parkera too.

**Comment by tkremenek** [comment]
@swift-ci test

**Review by parkera — APPROVED** [review]

**Comment by itaiferber** [comment]
@swift-ci Please test

**Comment by itaiferber** [comment]
@swift-ci Please test

**Pull request merged**
