### PR TITLE
Revert "Revert "Merge pull request #40595 from hamishknight/straw-bales""

### PR DESCRIPTION
**Pull request by milseman**
Reverts apple/swift#40623

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please test and merge

**Comment by milseman** [comment]
@swift-ci please test

**Comment by rxwei** [comment]
With workaround 7bff9da, CI should pass even if for some reason the repo is not checked out or is empty.

**Comment by rxwei** [comment]
@swift-ci please test

**Pull request merged**
