### PR TITLE
Fix SR-13490: Fix LT operator and add tests for ImportPath

### PR DESCRIPTION
**Pull request by Interfere**
Declare an order relation for `ImportPath` entities based on lexicographical comparison. The goal for the relations is to behave as a lexicographical order for basic strings.
Example:
A < A.A < A.A.A < A.A.B < A.B < A.B.A < AA < B < B.A

**Alternatives considered**
* Transform an existing `ImportPath` to `std::string` and compare using LT operator from STL.
* Transform an existing `ImportPath` to `llvm::Twine` and compare using LT operator for `llvm::Twine`.

These options are similar and would just increase the complexity of an algorithm.

* Implement `compare()` method for `ImportPath` and use it in implementation of order operators.
This is a possible solution, but it's a bit out of scope, since the only current use of the relation is to sort paths in the corresponding printing routine.

Resolves #55932.

### CODE REVIEW

**Comment by Interfere** [comment]
@brentdax @nathawes could you please review. thanks.

**Comment by nathawes** [comment]
@swift-ci please test

**Review by nathawes — APPROVED** [review]
Looks good to me. Thanks!

**Comment by Interfere** [comment]
> **Build failed**
> [Swift Test OS X Platform](https://ci.swift.org/job/swift-PR-osx/23837/)
> Git Sha - [bc6f841](https://github.com/apple/swift/commit/bc6f841cfe6586282af5781b2f16142e764d533b)

I cannot access `ci.swift.org` for some reason. @nathawes could you, please, give me an access or share a log? Thanks.

**Review by nathawes — APPROVED** [review]

**Comment by nathawes** [comment]
@swift-ci test and merge

**Pull request merged**
