### PR TITLE
[5.3] [Function builders] Run syntactic diagnostics for function bodies.

### PR DESCRIPTION
**Pull request by DougGregor**
When a function body has had a function builder applied to it, make
sure that we run all of the syntactic diagnostics for expressions and
statements within the body.

Fixes rdar://problem/64493626.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Review by tkremenek — APPROVED** [review]

**Comment by tkremenek** [comment]
@swift-ci clean test

**Comment by DougGregor** [comment]
The cherry-pick had to be adapted for 5.3, which doesn't have other refactorings.

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci test

**Comment by DougGregor** [comment]
@swift-ci test

**Pull request merged**
