### PR TITLE
[Driver] More robust tool searching logic

### PR DESCRIPTION
**Pull request by stevapple**
- Fix searching for Swift Driver on Windows;
- Search subcommand with `llvm::sys::findProgramByName`;
- Change fallback subcommand path to its name.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by stevapple** [comment]
Anyone to review and test?

**Comment by stevapple** [comment]
Ping @jrose-apple

**Comment by stevapple** [comment]
Ping

**Comment by artemcm** [comment]
@swift-ci test

**Review by artemcm — APPROVED** [review]

**Comment by stevapple** [comment]
Anyone to merge now?

**Pull request merged**
