### PR TITLE
Fix IRGen abi_v7k test case

### PR DESCRIPTION
**Pull request by aschwaighofer**
rdar://30584635

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by aschwaighofer** [comment]
@swiftix  Can you review this? This is a fix for a test case on armv7k. LLVM and our code generation has changed since this last tested successfully (for example we have change from i1 to i8 in IRGen).

**Comment by swiftix** [comment]
@aschwaighofer LGTM

**Comment by aschwaighofer** [comment]
@swiftix Thank you!

**Comment by aschwaighofer** [comment]
• Explanation: Fix IRGen abi_v7k test case. The generated assembly code has changed since this was last tested (llvm changed and IRGen code generation changed, we no longer lower to i1 but to i8).

• Scope of Issue: This is a currently failing test case on the 3.1-branch.

• Origination: Don’t know.

• Risk: Low. This is only a change to a test case.

• Testing: Swift CI

**Pull request merged**
