### PR TITLE
[LifetimeCompletion] Don't destroy alloc_boxes.

### PR DESCRIPTION
**Pull request by nate-chandler**
A `destroy_value` of an `alloc_box` unconditionally destroys the value within the box.  On unreachable paths, such memory may not be initialized, so it cannot be destroyed unconditionally.  Moreover, destroying values stored in memory is outside the purview of OSSA lifetime completion.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by atrick — APPROVED** [review]
Nice!

**Pull request merged**
