### PR TITLE
[4.0][stdlib] Add Sequence.Element

### PR DESCRIPTION
**Pull request by airspeedswift**
And change ExpressibleByArrayLiteral.Element to ArrayLiteralElement (#8990)

4.0 merge of #8990

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please test source compatibility

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
Huh. Looks like the regressed crashers that needed to be XFAIL'd on master don't crash on the 4.0 branch. Which is... good, I guess?

cc @DougGregor

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@swift-ci please test macOS platform

**Review by moiseev — APPROVED** [review]
:shipit:

**Comment by norio-nomura** [comment]
This changes introduced breaking changes to https://github.com/drmohundro/SWXMLHash/ :
[failed log](https://travis-ci.org/jpsim/SourceKitten/jobs/234170070#L230-L235)
```
SWXMLHash.XMLIndexer:72:22: error: invalid redeclaration of 'Element'
    public typealias Element = (SWXMLHash.XMLIndexer)
                     ^
/home/travis/build/jpsim/SourceKitten/.build/checkouts/SWXMLHash.git-4935070468589473534/Source/SWXMLHash.swift:457:10: note: 'Element' previously declared here
    case Element(XMLElement)
```
This error can not be avoided even by using `-swift-version 3`.

**Comment by norio-nomura** [comment]
filed [SR-4951](https://bugs.swift.org/browse/SR-4951)

**Pull request merged**
