### PR TITLE
Add `#include "swift/Basic/Assertions.h"` to a lot of source files

### PR DESCRIPTION
**Pull request by tbkka**
This makes the new assertion macros from #73675 available throughout the project.

**This does not change any current behavior.** The new assertion macros have different names and will have no impact until folks start using `ASSERT`, `CONDITIONAL_ASSERT`, and `DEBUG_ASSERT` in code instead of the old `assert` macro.

Although I don't plan to bring over new assertions wholesale into the current release branch, it's entirely possible that various changes in main will use the new assertions; having this basic support in the release branch will simplify that. (This is why I'm adding the includes as a separate pass from rewriting the individual assertions, to make it possible to implement the support in the release branch without copying any actual assertion changes.)

### CODE REVIEW

**Comment by tbkka** [comment]
@swift-ci Please test

**Review by beccadax — APPROVED** [review]
Weird flex, but okay.

(I'd like to understand why Assertions.h imports stdint.h, though; there's a comment about that now on the previous PR.)

**Comment by tbkka** [comment]
@swift-ci Please smoke test Linux platform

**Comment by tbkka** [comment]
@swift-ci Please smoke test

**Pull request merged**
