### PR TITLE
Escaping attribute fixes [5.1]

### PR DESCRIPTION
**Pull request by slavapestov**
- <https://bugs.swift.org/browse/SR-10256>, <rdar://problem/49522774>.
- <https://bugs.swift.org/browse/SR-9991>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@ddunbar Seen this before?

```
/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.1-branch/swiftpm/Sources/SPMLLBuild/llbuild.swift:13:19: error: compiled module was created by an older version of the compiler; rebuild 'llbuildSwift' and try again: /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.1-branch/buildbot_incremental/llbuild-macosx-x86_64/products/llbuildSwift/llbuildSwift.swiftmodule
22:45:42 @_exported import llbuildSwift
22:45:42                   ^
```

**Comment by slavapestov** [comment]
@swift-ci Please test macOS

**Comment by slavapestov** [comment]
@ddunbar Same error again.

**Comment by ddunbar** [comment]
Nope, new one to me. Maybe @aciidb0mb3r knows?

**Comment by ddunbar** [comment]
@dmbryson have we landed anything which might be causing the llbuild issues?

**Comment by aciidb0mb3r** [comment]
I suspect this https://github.com/apple/swift-llbuild/commit/822f4739810642b41351c4139a5854ee57648ee5

**Comment by slavapestov** [comment]
It looks like llbuildSwift is not getting rebuilt. The reason it started to fail with this PR is that I bumped the module format version.

**Comment by dmbryson** [comment]
🤔 I’m guessing that version check is not working.

**Comment by slavapestov** [comment]
@swift-ci Please clean test macOS

**Comment by ddunbar** [comment]
@swift-ci Please test macOS

**Comment by ddunbar** [comment]
@slavapestov its been reverted, let me know if this does not resolve it

**Pull request merged**
