### PR TITLE
Avoid using -sil-inline-generics and -sil-partial-specialization when building MinSizeRel stdlib to save ~15% on codesize

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please benchmark

**Comment by airspeedswift** [comment]
I'm guessing this won't benchmark this change, since it's for a new config.

**Comment by kubamracek** [comment]
@aschwaighofer any remaining concerns about this?

**Review by aschwaighofer — APPROVED** [review]
I think this makes sense. If generic performance becomes a concern we can revisit with a more target application of those optimizations based on annotations.

**Comment by kubamracek** [comment]
Ok thanks!

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test macOS platform

**Pull request merged**
