### PR TITLE
[4.2 2018-06-11] [Mangling] Mangle more standard substitutions

### PR DESCRIPTION
**Pull request by DougGregor**
**Explanation:** Use more of the "standard substitution" mangling space (`S<character>`), for commonly-used standard library types, like `Dictionary` (which goes from `s10DictionaryV` to `SD`), including standard substitution manglings for protocols (like `Collection`). This results in a code-savings win (~470k for the standard library itself in development builds).
**Scope:** Affects the mangled names in all Swift projects.
**Risk:** Low; mangling/demangling changes like this are straightforward and get heavily tested simply by building code.
**Testing:** Compiler regression tests
**Reviewer:** @jrose-apple , @jckarter 
**SR / Radar:** rdar://problem/40468532

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please nominate

**Comment by shahmishal** [comment]
@swift-ci please nominate

**Comment by najacque** [comment]
@swift-ci please nominate

**Pull request merged**
