### PR TITLE
+0 Guaranteed Arguments

### PR DESCRIPTION
**Pull request by gottesmm**
This PR contains the final work to convert the compiler to +0. There are still some tests failing, but I would like to get start performing PR testing of the branch.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

(just for testing purposes)

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
Forgot to turn on +0 in the runtime... sorry! So now I need to restart everything = (.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
Debugging the swiftpm crash now.

**Comment by gottesmm** [comment]
Interesting. It seems to be due to this line in swiftpm:

https://github.com/apple/swift-package-manager/blob/c75ee580152fb692937787755f699af42b3550b5/Sources/Commands/SwiftTool.swift#L315

**Comment by gottesmm** [comment]
(the reason why it is interesting is that there is a last runtime fix that I need to look at around subclassing existentials getting wonky and I think the way this code is working, subclass existentials come up, but I need to look further at the SIL.

**Comment by gottesmm** [comment]
(i.e. I just reduced the swift test case a bit)

**Comment by gottesmm** [comment]
Alright... lets try this again.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
Funny story. The assert that the linux build hit in Foundation is the assert that I have been avoiding fixing that fixes the last 1-2 SILGen tests. I guess I should go fix those tests!!!

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Comment by gottesmm** [comment]
Figured out the problem. I thought that I had enabled the runtime to be built with +0 by default. But turns out what I did only worked locally. I am going to change build-script to do the right thing.

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Comment by gottesmm** [comment]
@swift-ci smoke test os x platform

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci smoke test benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke test benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke test benchmark

**Comment by gottesmm** [comment]
Just checked in the individual PRs. The ENABLE_GUARANTEED_NORMAL_ARGUMENT flag is set properly now.

**Comment by gottesmm** [comment]
The linux one is still going to fail in Foundation since I need to fix that harmless assertion (it is the same one that shows up in the vtable tests).

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by huonw** [comment]
https://github.com/apple/swift/pull/14948 has now landed.

**Comment by gottesmm** [comment]
Thanks Huon!

**Comment by gottesmm** [comment]
Just seeing if anything has broken in the mean time.

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
Linux failure is expected. That is just something annoying that I am going to fix today.

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci asan test

**Comment by gottesmm** [comment]
@swift-ci asan test

**Comment by gottesmm** [comment]
The failing benchmark was fixed here: https://github.com/apple/swift/pull/15300#event-1526155380. It was unrelated to +0.

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci asan

**Comment by gottesmm** [comment]
@swift-ci asan

**Comment by gottesmm** [comment]
@swift-ci asan

**Comment by gottesmm** [comment]
@swift-ci asan

**Comment by gottesmm** [comment]
@swift-ci asan

**Comment by gottesmm** [comment]
@swift-ci asan test

**Comment by gottesmm** [comment]
@swift-ci ASAN test

**Comment by gottesmm** [comment]
Just passed Linux full test.

**Comment by gottesmm** [comment]
The OS X failure was caused by my missing a simulator check. I am going to go fix it now. Just an oversight on my part.

**Comment by gottesmm** [comment]
Looks like type checker broke ASAN. Too bad. It is on the bots as well. See:

https://ci.swift.org/job/oss-swift-incremental-ASAN-RA-osx/1301/consoleFull#5770858633122a513-f36a-4c87-8ed7-cbc36a1ec144

**Comment by gottesmm** [comment]
Benchmarks passed.

**Comment by gottesmm** [comment]
Assuming source compatibility looks good, I am going to merge this after doing a full test on OS X, but a smoke test on linux.

**Comment by gottesmm** [comment]
*assuming source compatibility and that the change in the failing test was just updating the test.

**Comment by gottesmm** [comment]
Source Compatibility passed besides the test Siesta that is also failing on the bots. For instance:

https://ci.swift.org/view/Source%20Compatibility/job/swift-master-source-compat-suite/1462/console

**Comment by gottesmm** [comment]
Just updated with the simulator test update applied.

**Comment by gottesmm** [comment]
@swift-ci test os x platform

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by gottesmm** [comment]
@swift-ci test os x platform

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by gottesmm** [comment]
Java failure...

**Comment by gottesmm** [comment]
*sigh* merge conflict.

**Comment by gottesmm** [comment]
@swift-ci test os x platform

**Comment by gottesmm** [comment]
@swift-ci test os x platform

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
There is going to be an lldb stepping test failure in this rebase change that I am testing now. I am waiting for @jimingham to help me debug it after he gets back from a meeting.

**Comment by gottesmm** [comment]
Hmm... interesting. I guess I did not resolve the merge conflict perfectly. Lets see.

**Comment by gottesmm** [comment]
I figured out the lldb problem in concert with @jimingham. We have changed stepping behavior slightly. I am fixing now.

**Comment by gottesmm** [comment]
lldb update PR: apple/swift-lldb#427

**Comment by gottesmm** [comment]
Going to fix the merge conflict and wait for the dust to settle a little from the day now that I hopefully can avoid merge conflicts.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test linux platform

**Comment by gottesmm** [comment]
@swift-ci test linux platform

**Comment by gottesmm** [comment]
apple/swift-lldb#427

@swift-ci test

**Comment by gottesmm** [comment]
apple/swift-lldb#427

@swift-ci test

**Comment by gottesmm** [comment]
apple/swift-lldb#427

@swift-ci test

**Comment by gottesmm** [comment]
apple/swift-lldb#427

@swift-ci test

**Comment by gottesmm** [comment]
apple/swift-lldb#427

@swift-ci test linux platform

**Comment by gottesmm** [comment]
And its done.

**Comment by eeckstein** [comment]
awesome! great work!

**Pull request merged**
