### PR TITLE
Build dependency list once

### PR DESCRIPTION
**Pull request by ladd**
`emitMakeDependenciesIfNeeded` can be a bottleneck for large Xcode projects. In our profiling, we observed a hot spot in this function, due to redundant work, and unbuffered use of `raw_fd_ostream`. For our project with ≈1M lines of mixed Swift & Obj-C, this patch improves build time from ≈470 seconds to ≈430 seconds, an 8% improvement.

This project has a very large dependency chain: each dependency line has 2000+ entries, and it's repeated four times:

```
file.o
file~partial.swiftmodule
file~partial.swiftdoc
file~partial.swiftsourceinfo
```

Also filed a separate feedback request to fix the Xcode limitation on .d files having a single target per line: FB7725318

@swift-ci Please smoke test
@swift-ci Please test compiler performance

### CODE REVIEW

**Review by CodaFi — APPROVED** [review]

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by CodaFi** [comment]
I'm not sure how much signal we'll get out of testing the source compat suite, but this should be a universal win that scales quadratically with the number of files in a given project.

We'll merge after the tests pass, the compiler perf suite will take a day to get back to you.

@swift-ci test compiler performance

**Review by nkcsgexi — APPROVED** [review]
🙏Thank you!

**Comment by CodaFi** [comment]
CI is have some trouble. Will reschedule the perf run when it's back up.

**Comment by CodaFi** [comment]
@swift-ci test compiler performance

**Comment by CodaFi** [comment]
⛵

**Comment by ladd** [comment]
Thanks for the speedy assistance getting this merged!

**Pull request merged**
