### PR TITLE
Enable optional unowned/unowned(unsafe) references

### PR DESCRIPTION
**Pull request by davezarzycki**
@rjmccall okayed this change in a comment on GitHub pull request: #16237

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by jrose-apple** [comment]
This is a big new change (and one that's been requested for a long time, rdar://problem/17277899!). Can you add some execution tests (in test/Interpreter) to show that this is working with both ObjC and non-ObjC types? And can you update CHANGELOG.md?

**Comment by davezarzycki** [comment]
@jrose-apple – Adding the interpreter tests found a bug. So yay for more tests.
@rjmccall – Can you please double check the changes to IRGenSIL.cpp? Thanks!

@swift-ci please test

**Comment by jrose-apple** [comment]
Aack. I hate to delay this even more, but I realized we probably don't want to land it without checking debugger support, or at least a commitment from the debugger folks to add that soon. @dcci, @jimingham, I wouldn't *expect* this to require any work beyond what we already do for `unowned` references, but if LLDB is assuming they're non-null anywhere… What do you think?

**Comment by davezarzycki** [comment]
Hi @jrose-apple – The delay is fine. The ease of this pull request is the result of #16237, which took two months to land, so waiting a few more days isn't a big deal.

**Comment by davezarzycki** [comment]
@dcci and @jimingham – Ping. Your feedback is appreciated. Thanks!

**Review by dcci — APPROVED** [review]
@davezarzycki To the. best of my understanding the compiler bits are fine, but I think some work might be needed to get stuffs to work in the debugger. That said, I think it's not worth delaying this PR merge more, so please go ahead.

I think if you're interested you might want to consider adding a REPL tests in `lldb` for what you added, and then we can go from there. If you don't have time for this, I'd appreciate if you can at least open a bug on JIRA.

**Comment by davezarzycki** [comment]
Thanks @dcci – I have something that might work for lldb. I'll follow up with a pull request.

**Pull request merged**
