### PR TITLE
[DO NOT MERGE] [ClangImporter] Import NSUInteger as Int everywhere.

### PR DESCRIPTION
**Pull request by jrose-apple**
(instead of just in system modules)

If we do make this change, it will only be in Swift 4 mode, and will not involve just commenting code!

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by DougGregor** [comment]
Very curious to see these results

**Comment by jrose-apple** [comment]
…and the results were "the XCTest overlay has a bug". Grr.

**Comment by jrose-apple** [comment]
I don't actually expect this to be too meaningful, since most of the projects in the compat-suite are pure Swift.

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
I was wondering when this would come up again :)

**Comment by DougGregor** [comment]
Heh, the `XCTest` overlay didn't build, so you got no signal :)

**Comment by jrose-apple** [comment]
It took until the second time around that it didn't build *because* of this patch. We must be using -F instead of -Fsystem somewhere.

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test macOS

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Pull request closed without merging**
