### PR TITLE
[android] Switch armv7 vendor to 'unknown' in target triple to match other arches

### PR DESCRIPTION
**Pull request by finagolfin**
Recent changes have made 'none' and 'unknown' not interchangeable anymore, so standardize on 'unknown' for armv7 too.

I don't know exactly when this change was introduced in trunk, maybe with #31170, but both vendors work with the release/5.3 branch. When I just tried to cross-compile the corelibs for armv7 with #33724, where [I use 'unknown' in the triple](https://github.com/apple/swift/pull/33724/files#diff-cc09c8923370b808ebb7439cf4be9d2dde15e81796e80161576ae4cee0502ae7R161), applied to the Nov. 26 trunk source snapshot, I hit this error when CMake checks that the Swift compiler works when configuring libdispatch, which this pull fixes:
```
<unknown>:0: error: could not find module 'Swift' for target 'armv7-unknown-linux-android'; found: armv7-none-linux-android
```
Another way to reproduce is by trying to cross-compile a "hello world" executable by using the Android cross-compilation flags from the docs:
```
> ./swift-DEVELOPMENT-SNAPSHOT-2020-11-26-a-ubuntu20.04/usr/bin/swiftc
-tools-directory android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/
-L android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/armv7-a/
-sdk android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/sysroot
-resource-dir build/Ninja-Release/swift-android-armv7/lib/swift
swift/test/Interpreter/hello_toplevel.swift -target armv7-unknown-linux-androideabi24
<unknown>:0: error: could not find module 'Swift' for target 'armv7-unknown-linux-android'; found: armv7-none-linux-android
```
I've modified a couple armv7 tests to use the new vendor, while leaving in [others that are meant to check that the vendor and triple are changed before being passed to the linker](https://github.com/apple/swift/blob/main/test/Driver/android-link.swift#L2).

@drodriguez and @compnerd, I'm not sure why these tests on the Android CI didn't catch this, should I add a test that does?

### CODE REVIEW

**Comment by drodriguez** [comment]
It should have been `unknown` all along, I think. `none` doesn't have a special meaning in the vendor field, and it might have been taken as `unknown` anyway (it can be seen in the test you link and haven't modified, in where `none` and `more` are both transformed internally into `unknown`). `none` might have been interpreted as an specific vendor, which did not match when `unknown` is explicitly specified.

@swift-ci please test

**Comment by buttaface** [comment]
Linux passes, mac single test failure is unrelated, and Windows CI fails when checking out git.

**Comment by drodriguez** [comment]
@swift-ci please test macOS platform

**Comment by drodriguez** [comment]
@swift-ci please test Windows platform

**Review by compnerd — APPROVED** [review]
Yes please.  I think that as long as the build succeeds with this change, this is something we should get merged right away.  The only concern is with the tool prefixing that might happen in some cases (with the NDK toolchain).

**Comment by drodriguez** [comment]
@swift-ci please test Windows platform

**Comment by drodriguez** [comment]
@swift-ci please test macOS platform

**Comment by buttaface** [comment]
Mac CI dies when cross-compiling stdlib for Mac-ARM64, running out of memory? Unrelated to this pull of course.

> The only concern is with the tool prefixing that might happen in some cases

If you're talking about NDK paths that use these variables, I just checked and they don't. There is [a separate `SWIFT_SDK_ANDROID_ARCH_${arch}_NDK_TRIPLE` variable for that, which never used a vendor](https://github.com/apple/swift/blob/f91fe9c0c1d7fa5e0b74d119ea58bb8b929966e8/cmake/modules/SwiftConfigureSDK.cmake#L291).

**Comment by buttaface** [comment]
Ping, we should get this in.

**Comment by xwu** [comment]
@swift-ci please test macOS platform

**Comment by buttaface** [comment]
Yet another spurious failure on the Mac CI.

**Comment by drodriguez** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
I believe that this is safe and everyone is in agreement here, merging.

**Pull request merged**
