### PR TITLE
Sema: Don't try bridged classes as default literal types.

### PR DESCRIPTION
**Pull request by jckarter**
One last bit of SE-0072. We shouldn't fall back to bridged classes in the absence of type context for literals anymore. By itself, this kind of hoses the use of literals with NS types, but I think we can get most of the QoI back with overlay changes I plan to propose following this.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@tkremenek I ran the full tests in order to maximize coverage. Would you be able to merge this if the tests pass?

**Comment by jckarter** [comment]
@milseman swiftpm fails due to an escaping closure:

```
/home/buildnode/jenkins/workspace/swift-PR-Linux/swiftpm/Sources/Basic/LazyCache.swift:41:21: error: invalid conversion from non-escaping function of type '(Class) -> () -> T' to potentially escaping function type '(_) -> () -> _'
        self.body = body
                    ^~~~
```

**Comment by gottesmm** [comment]
@milseman said he is going to revert the change.

**Comment by jckarter** [comment]
@milseman Looks like swiftpm failed to build on Linux because of the escaping change, in case you haven't seen that yet.

**Comment by jckarter** [comment]
@swift-ci smoke test

**Comment by jckarter** [comment]
OS X build fails on playground support, looks related. I'll investigate.

**Comment by milseman** [comment]
swiftpm should be fine now, builders are passing

**Comment by jckarter** [comment]
@milseman Thanks!

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
Fixed the swiftpm failure. Trying again.

**Comment by jckarter** [comment]
@swift-ci Please test OS X

**Comment by parkera** [comment]
@jckarter what's the PR for the follow up work?

**Comment by jckarter** [comment]
@parkera Haven't filed a public pr yet, but I filed 27616753 internally.

**Pull request merged**
