### PR TITLE
Revert "[SR-9425][Sema] Use derived conformance as witness when possible for == operator of raw representable enums"

### PR DESCRIPTION
**Pull request by slavapestov**
Reverts apple/swift#36752 to "fix" rdar://problem/80466745.

The problem is that we assume a swiftinterface built with the older compiler has a synthesized == witness, when in fact it was relying on the generic implementation before, so the synthesized == witness is not even in the dylib.

The proper fix will be to disable automatic derivation of == in swiftinterface files, since they already spell out the conformance explicitly.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by LucianoPAlmeida** [comment]
> The problem is that we assume a swiftinterface built with the older compiler has a synthesized == witness, when in fact it was relying on the generic implementation before, so the synthesized == witness is not even in the dylib.
> 

Ah that's unfortunate, thank you for reverting this @slavapestov :)

> The proper fix will be to disable automatic derivation of == in swiftinterface files, since they already spell out the conformance explicitly.

If I understand correctly, this implementation is still valid. We just need to make sure that together with that automatic derivation of equatable conformances don't get emitted when compiling swift interface files?

**Comment by slavapestov** [comment]
> If I understand correctly, this implementation is still valid. We just need to make sure that together with that automatic derivation of equatable conformances don't get emitted when compiling swift interface files?

Right, when building a swiftmodule from a swiftinterface, we can't derive the conformance, because we're not actually going to emit the witness. If the synthesized == overload does not appear in the swiftinterface, we should not assume the dylib has one, because it won't if built with an older compiler.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by LucianoPAlmeida** [comment]
> Right, when building a swiftmodule from a swiftinterface, we can't derive the conformance, because we're not actually going to emit the witness. If the synthesized == overload does not appear in the swiftinterface, we should not assume the dylib has one, because it won't if built with an older compiler.

Ah I see, understood it now. Thank you!
I can give it a shot in fix it. Not sure when, but we can reopen the ticket and I can assign to myself to work on it again soon as possible.

**Pull request closed without merging**
