### PR TITLE
Allow identification of OSLogMessage by a @_semantics attribute instead of just name

### PR DESCRIPTION
**Pull request by kubamracek**
OSLogOptimization currently special-cases the type name "OSLogMessage" and applies special treatment to it (skips over synthesized witness methods). Let's allow explicitly annotating types with `@_semantics("oslog.message.type")` to trigger the same treatment. This will be useful for custom implementations of OSLog-like APIs.

rdar://83325012

### CODE REVIEW

**Comment by ravikandhadai** [comment]
@kubamracek Thanks Kuba for making the PR. Are the OSLog* LIT tests passing? Is semantics attributes now possible on types?

**Comment by ravikandhadai** [comment]
I wonder if it may be better to rename the OSLogMessage type in the `OSLogTestHelper` module apply this semantics attribute. This may enable testing this change.

**Comment by kubamracek** [comment]
Semantics attributes on types were added via < https://github.com/apple/swift/commit/454dd00e439ea661387dc5364b0f0a7cd48c43fa>, yes.

**Comment by kubamracek** [comment]
> I wonder if it may be better to rename the OSLogMessage type in the OSLogTestHelper module apply this semantics attribute. This may enable testing this change.

I tried that, and it ended being a bit invasive on the code OSLogTestHelper. Let's see if you prefer that, but I can also perhaps revert and switch only the AnimationFormatString.OSLogMessage type, which can be done as a minimally invasive change.

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@ravikandhadai This is what only changing the type name on AnimationFormatString.OSLogMessage looks like: https://github.com/kubamracek/swift/commit/668b204a664104900b894033ecd971826158d36a

Let me know if you'd prefer that.

**Comment by ravikandhadai** [comment]
> @ravikandhadai This is what only changing the type name on AnimationFormatString.OSLogMessage looks like: [kubamracek@668b204](https://github.com/kubamracek/swift/commit/668b204a664104900b894033ecd971826158d36a)
> 
> Let me know if you'd prefer that.

Yes. Changing AnimationFormatString.OSLogMessage sounds great. Thanks Kuba. 

On a slightly different note, if you are only interested in converting a string interpolation to a static format string and not very concerned about optimizing varargs lmk. There is a very small design change possible on the client side, compared to the current implementation of OSLogMessage and os_log, that would enable creating a very general custom string interpolation type that can be used in any context and create a static format string.

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
> On a slightly different note, if you are only interested in converting a string interpolation to a static format string and not very concerned about optimizing varargs lmk. There is a very small design change possible on the client side, compared to the current implementation of OSLogMessage and os_log, that would enable creating a very general custom string interpolation type that can be used in any context and create a static format string.

I'm not sure, TBH. Maybe @Catfish-Man does?

**Comment by Catfish-Man** [comment]
I'm not sure either tbh. It sounds interesting at least!

**Comment by kubamracek** [comment]
@swift-ci please test Windows platform

**Review by ravikandhadai — APPROVED** [review]
LGTM!

**Comment by ravikandhadai** [comment]
> I'm not sure either tbh. It sounds interesting at least!

No worries. Feel free to cc me on the PR you create for that.

**Pull request merged**
