### PR TITLE
Kill off some usages of the DeclChecker::IsFirstPass bit

### PR DESCRIPTION
**Pull request by slavapestov**
Follow-up to https://github.com/apple/swift/pull/15408. For most declaration kinds, moves all of the type checking work to the 'first pass'. Classes, enums, functions and pattern binding decls still remain. Once those are done, we'll be doing nothing in the 'second pass', at which point the flag and walk over the AST can be removed.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test compiler performance

**Review by davezarzycki — APPROVED** [review]
Hi @slavapestov – I can mark this as reviewed, but I'm not sure what value I'm adding here. While I've been experimenting with the code recently, I don't feel like I intuitively understand it yet.

Also, if you weren't trying to rid us of `IsFirstPass`, I'd request that it be renamed to something semantically meaningful. :-)

What I'd really like to see (and this is separable feedback) is for some deduplication of logic in parallel Decl validation paths. For example, the nominal decls do very similar things for the most part, but it isn't clear which differences are essential and which are accidental.

**Comment by slavapestov** [comment]
@davezarzycki You've been working on this area recently cleaning up the various state bits and we had the forum discussion so I wanted to bring these PRs to your attention. I'm not looking for any specific feedback, but if you have any I'm happy to listen!

My goal is to completely eliminate `IsFirstPass`, I'm just doing it a bit at a time. I agree that if it made sense to keep a better name would help, but one of the reasons it doesn't make sense is that there isn't a good name for it, since it's not doing anything useful at this stage.

Cleaning up duplication between the various typeCheck and validateDecl cases would be nice. In addition to the ones you pointed out, there is also duplication between functions, constructors and destructors, in particular the manner in which we calculate the generic function type.

My approach so far as been to avoid attacking the 'surface-level' duplication, and instead try to simplify the underlying APIs so that there's less stuff to de-duplicate later. Also, I've been trying to make more fundamental structural changes to the declaration checker, like simplifying how we detect and track circularity, and this current project to eliminate passes. I hope that after enough iteration of this, the duplication will go away on its own.

**Comment by slavapestov** [comment]
The SwifterSwift failure is in expression type checking and not related to my changes (and since the expression type checker ran it probably means the decl checker was OK).

**Pull request merged**
