### PR TITLE
For the 'minimal' stdlib, disable Objective-C interop

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Review by mikeash — APPROVED** [review]

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test Windows platform

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test macOS platform

**Comment by gottesmm** [comment]
LGTM. @kubamracek there is actually a lot more work that can be done here in terms of eliminating objc stuff from runtime data structures. Would be generally useful for Linux and other platforms as well to lower memory usage.

**Pull request merged**
