### PR TITLE
Revert "Merge pull request #6807 from alblue/SR-1676"

### PR DESCRIPTION
**Pull request by alblue**
This reverts commit c85cbe5c785cd729b28e802bcfa69a549fa78df7, reversing
changes made to 5d293ab9d214b4997e235f53f60fcecc91b3513d.

Build fails on Ubuntu 14.04 with 'unsupported compiler'. Unclear why this fails when this code builds as part of libdispatch project already, and it appears to be using the correct compiler.

In file included from allocator.c:21:
In file included from ./internal.h:616:
./shims.h:252:2: error: unsupported compiler
#error unsupported compiler
 ^

### CODE REVIEW

**Comment by rintaro** [comment]
Toolchain build uses "just built" `clang` in LLVM build directory.
https://github.com/apple/swift/blob/master/utils/build-script-impl#L2470-L2471
not `/usr/bin/clang`.

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by alblue** [comment]
So it looks like the build fails when running against a 3.6 compiler, but works against a 3.8 compiler:

root@2f406866081b:/tmp# clang-3.8 foo.c
root@2f406866081b:/tmp# clang-3.6 foo.c
In file included from foo.c:1:
./foo.h:8:2: error: unsupported compiler
#error unsupported compiler
 ^
1 error generated.

That would be consistent with the libdispatch using its own version, so I'll see if I can replicate that. Thanks!

**Comment by alblue** [comment]
I've managed to reproduce the error seen here, and have something that works to build it. I'll do some more testing and then push an updated patch later.

**Comment by alblue** [comment]
Thanks

**Pull request merged**
