### PR TITLE
Add documentation for generating a Visual Studio project on Windows

### PR DESCRIPTION
**Pull request by hughbe**
Sorry, I think I accidently created a branch under apple/swift rather than hughbe/swift. Sorry

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test and merge

**Comment by RUSshy** [comment]
Wait, swift is coming to windows ? :o when? this is fantastic news!

**Comment by compnerd** [comment]
@RUSshy swift already supports windows natively (without cygwin/mingw).  This work is for building on windows rather than cross-compiling.

**Comment by hughbe** [comment]
@compnerd is correct. And the work for building *on* Windows is almost done - what remains is #5904 (when I fix the merge conflicts!)

There are obviously more fixes to be done that I am investigating. These include
- Fixing the unresolved symbol errors when linking `swiftPrivate.dll`
- Fixing the unresolved symbol errors when compiling
```swift
class C {}
```
- Fixing an AccessViolationException acessing 0x7FFFFFFF... when compiling
```swift
print("Hello, World")
```

**Comment by RUSshy** [comment]
It will be available for 3.x cycle or for 4.x ?

**Pull request merged**
