### PR TITLE
[Interpreter] Temporarily prefer /usr/lib/swift for Swift dylibs loaded by the interpreter

### PR DESCRIPTION
**Pull request by mikeash**
This is a cherry-pick of some 5.0 work plus a bit more, that's temporarily needed for 5.1. That need will hopefully go away soon, at which point I'll redo this to prefer the libraries next to the `swift` binary, and use `/usr/lib/swift` as a fallback.

rdar://problem/49610198

### CODE REVIEW

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
@swift-ci test macOS

**Comment by mikeash** [comment]
@swift-ci please test linux

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
```
00:53:37.045 ******************** TEST 'Swift(macosx-x86_64) :: Driver/environment-mac.swift' FAILED ********************
00:53:37.045 Script:
00:53:37.045 --
00:53:37.045 : 'RUN: at line 3';   env SDKROOT= '/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.1-branch/buildbot_incremental/swift-macosx-x86_64/bin/swift' -module-cache-path '/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.1-branch/buildbot_incremental/swift-macosx-x86_64/swift-test-results/x86_64-apple-macosx10.9/clang-module-cache' -swift-version 4  -driver-use-frontend-path /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.1-branch/swift/test/Driver/Inputs/print-var.sh /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.1-branch/swift/test/Driver/environment-mac.swift DYLD_LIBRARY_PATH | '/usr/bin/python' '/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.1-branch/swift/utils/PathSanitizingFileCheck' --sanitize BUILD_DIR='/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.1-branch/buildbot_incremental/swift-macosx-x86_64' --sanitize SOURCE_DIR='/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.1-branch/swift' --use-filecheck '/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.1-branch/buildbot_incremental/llvm-macosx-x86_64/bin/FileCheck' /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.1-branch/swift/test/Driver/environment-mac.swift
00:53:37.045 --
00:53:37.045 Exit Code: 1
00:53:37.045 
00:53:37.045 Command Output (stderr):
00:53:37.045 --
00:53:37.045 
/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-5.1-branch/swift/test/Driver/environment-mac.swift:5:11: error: CHECK: expected string not found in input
00:53:37.045 // CHECK: {{^/usr/lib/swift:}}
00:53:37.045           ^
00:53:37.045 <stdin>:2:1: note: scanning from here
00:53:37.045 
00:53:37.045 ^
00:53:37.045 
00:53:37.045 --
00:53:37.045 
00:53:37.045 ********************
```

**Comment by mikeash** [comment]
@swift-ci please smoke test

**Comment by mikeash** [comment]
@swift-ci please smoke test

**Comment by mikeash** [comment]
@swift-ci please smoke test

**Comment by mikeash** [comment]
@swift-ci please smoke test OS X platform

**Comment by mikeash** [comment]
@swift-ci please test OS X platform

**Comment by mikeash** [comment]
@swift-ci please smoke test

**Comment by mikeash** [comment]
@swift-ci please test OS X platform

**Comment by mikeash** [comment]
@swift-ci please smoke test and merge

**Comment by mikeash** [comment]
@swift-ci please smoke test and merge

**Comment by mikeash** [comment]
@swift-ci please smoke test and merge

**Comment by mikeash** [comment]
@swift-could please test

**Comment by mikeash** [comment]
@swift-ci please test

**Pull request merged**
