### PR TITLE
[NFC] Get rid of -Wrange-loop-analysis warnings.

### PR DESCRIPTION
**Pull request by varungandhi-apple**
Cherry-pick https://github.com/apple/swift/pull/31324 onto 5.3.

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
@swift-ci please test

**Comment by varungandhi-apple** [comment]
@swift-ci please test

**Comment by varungandhi-apple** [comment]
@swift-ci please test macOS platform

**Comment by varungandhi-apple** [comment]
cc @DougGregor

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
