### PR TITLE
Enable resilience again

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes recent performance regression.

### CODE REVIEW

**Comment by slavapestov** [comment]
@eeckstein I think this is it

**Comment by slavapestov** [comment]
@swift-ci Please benchmark

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@dcci Any ideas?

```
18:30:55 CMake Error at CMakeLists.txt:90 (message):
18:30:55   LLDB test compilers not specified.  Tests will not run
```

**Comment by slavapestov** [comment]
@swift-ci Please test Linux

**Review by eeckstein — COMMENTED** [review]
Thanks for fixing. Let's wait for the benchmark results

**Comment by dcci** [comment]
@slavapestov apparently the merge did last week screwed up incremental builds. Please clean before running the tests (I hit this as well) and that should fix it.
cc: @vedantk who's looking at the issue.

**Comment by jrose-apple** [comment]
cc @milseman: looks like more things should be marked fixed-contents or inlinable

**Pull request merged**
