### PR TITLE
[AutoDiff] Make `transpose(of:)` available.

### PR DESCRIPTION
**Pull request by rxwei**
Depends on #28469. Resolves SR-11845.

### CODE REVIEW

**Review by dan-zheng — APPROVED** [review]

**Review by dan-zheng — APPROVED** [review]
Very cool!

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
This helped discover a serious bug: SR-11856.  Arguments being passed to `transpose(of:)` need to be reabstracted most of the time, but AD reabstraction thunk generation currently treats all differentiable functions as having `Normal` differentiability (disregarding linearity) and emits incorrect code.

**Pull request merged**
