### PR TITLE
[stubs] Autolink against icucore on Darwin.

### PR DESCRIPTION
**Pull request by milseman**
Programs using a statically linked build of the standard library need
to explicitly link against icucore. There are various potential
hacks^Wsolutions to this problem, and this is an attempt at a lesser
of evils approach.

Emit a linker directive to perform autolinking against icucore on
Darwin systems. This allows us to avoid hacking the compiler driver
and propagating that hack onto any build systems that don't go through
the driver.

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please test

**Review by jrose-apple — APPROVED** [review]
Looks good to me. We should add `-lc++` and `-framework Foundation` in a follow-up commit too. (Unfortunately for us the only options supported are `-l` and `-framework`, IIRC.)

**Comment by milseman** [comment]
@swift-ci please test Linux Platform

**Comment by milseman** [comment]
@swift-ci please test Linux Platform

**Comment by milseman** [comment]
@swift-ci please test OS X platform

**Comment by milseman** [comment]
(issue was unrelated and already fixed elsewhere)

**Pull request merged**
