### PR TITLE
[Diagnostics] Refactor `FailureDiagnostic` to operate on `TypedNode`

### PR DESCRIPTION
**Pull request by xedin**
Switch all of the relevant `FailureDiagnostic` APIs to use `TypedNode` instead of `Expr *`
and refactor diagnostic implementations to avoid relying on anchors being expressions where
possible.

Since `FailureDiagnostic` is the biggest user of `ConstraintLocator` this refactoring enables
to transition locator from being anchored only on expressions.

### CODE REVIEW

**Review by hborla — APPROVED** [review]
Looks great!

**Comment by xedin** [comment]
@swift-ci please smoke test

**Review by hamishknight — APPROVED** [review]
LGTM!

**Comment by xedin** [comment]
@swift-ci please smoke test Linux platform

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please smoke test

**Pull request merged**
