### PR TITLE
Add "IgnoreAccessControl" to UnqualifiedLookup.

### PR DESCRIPTION
**Pull request by jrose-apple**
...and use it when top-level type and decl-ref lookup fails, to produce better diagnostics.

Finishes rdar://problem/27663403.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@DougGregor, since you've been in the lookup area, mind checking this over?

@swift-ci Please test

**Comment by jrose-apple** [comment]
Gosh, I just instinctively kicked that off after having a discussion "my PR failed" / "yeah, they're updating the bots right now".

**Comment by jrose-apple** [comment]
I know, @swift-ci, I'm sorry.

**Comment by slavapestov** [comment]
Ideally name lookup would always ignore accessibility, leaving that up to the clients. The reason is we want to avoid having name lookup recursively validate decls (of course the if caller needs to validate the decl they will, but that should be a decision made there)

**Comment by jrose-apple** [comment]
Yep, I discussed this with @DougGregor a bit offline. This is targeted at swift-3.0-branch, though.

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
[Mac](https://ci.swift.org/view/Pull%20Request/job/swift-PR-osx/3757/), [Linux](https://ci.swift.org/view/Pull%20Request/job/swift-PR-Linux/3900/)

**Comment by jrose-apple** [comment]
An (unrelated) failure in the kqueue tests. @das, have you seen this one yet?

```
15:42:03 FAIL: kqtest
15:42:03 ============
15:42:03 
15:42:03 bind-1: Address already in use
15:42:03 Running 1 iterations
15:42:03 1: test_peer_close_detection()	
15:42:03 2: test_kqueue()	
15:42:03 3: test_kevent()	
15:42:03 4: test_ev_receipt()	
15:42:03 unable to bind to port 23456
```

**Comment by jrose-apple** [comment]
@swift-ci Please test Linux platform

**Comment by das** [comment]
@jrose-apple  no, looks like that is from is the Linux-specific [libkqueue socket test](https://github.com/mheily/libkqueue/blob/master/test/read.c#L25).

@dgrove-oss or somebody else more familiar with those tests may be able to say more but this looks like a spurious failure to me (maybe another instance of the test also running and having the same port open?)

**Comment by jrose-apple** [comment]
[Mac build passed](https://ci.swift.org/view/Pull%20Request/job/swift-PR-osx/3757/). Still waiting for @DougGregor's review, though.

**Comment by jrose-apple** [comment]
I'm going to merge to kick off a CI build on the 3.0 branch, but we won't pull it in until Doug okays it.

**Pull request merged**
