### PR TITLE
[6.0][Concurrency] Further prevent crashes in legacy mode of isSameExecutor concurrency

### PR DESCRIPTION
**Pull request by ktoso**
**Description**:  This cleans up interactions with the "legacy mode" where we're not allowed to crash in the isCurrentExecutor impl.

**Scope/Impact**: Dynamic actor isolation checks are inserted by Swift 6. Without this patch they would crash existing applications without them recompiling. This patch corrects logic to only start doing so when recompiled against new SDK. It also corrects some logic that would have prevented `checkIsolated` from being invoked in some cases.

**Risk:** Medium, the change is fleshing out logic in `swift_task_isCurrentExecutorImpl` interactions between flags. However we took great lengths to verify this logic is now correct.
**Testing**: Verified manually; Improved tests to now run in swift 6 AND legacy mode.
**Reviewed by**: @hborla @mikeash 

**Original PR:** https://github.com/apple/swift/pull/73813
**Radar:** rdar://127400013

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
Last commit here is unbreaking embedded.

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please test

**Pull request merged**
