### PR TITLE
IRGen: fix a corner-case wherein a partial_apply was not converted in LoadableByAddress

### PR DESCRIPTION
**Pull request by shajrawi**
rdar://problem/36826848

fix a corner-case wherein a partial_apply was not converted in LoadableByAddress
It also cleans up shouldTransformParameter, fixing a corner-case for optional function parameter, and re-creates *all* partial applies that only contain function/optional function parameters

### CODE REVIEW

**Comment by shajrawi** [comment]
@swift-ci Please smoke test

**Review by aschwaighofer — APPROVED** [review]
LGTM for swift-4.1-branch

**Comment by jrose-apple** [comment]
This broke with a non-optimized stdlib, https://ci.swift.org/view/Dashboard/job/oss-swift_tools-RA_stdlib-DA_test-simulator/177/. I'm going to disable the test in that configuration for now, but that seems like a bug—optimization shouldn't affect calling conventions here, no?

**Comment by jrose-apple** [comment]
#14217

**Comment by shajrawi** [comment]
Thanks for fixing that! It does call into the standard library, the array operation, for which the signature is different in an optimized build...

**Comment by jrose-apple** [comment]
It seems like you'd need to change the test anyway to deal with -enable-resilience. After all, the test will be permanently unsupported after that.

**Pull request merged**
