### PR TITLE
WIP: batch processing missing witnesses to allow enhanced fixits.

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@DougGregor @jrose-apple Mind taking a look on this patch? The idea here is that we should allow users to invoke one fixit to fill the stubs for all missing witnesses, instead of the current scheme that one fixit fills one missing witness.

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test OS X Platform

**Comment by nkcsgexi** [comment]
No idea what happened to CI:
Assertion failed: (!V->hasBrokenDebugInfo() && "Module contains invalid debug info"), function doFinalization, file /Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/llvm/lib/IR/Verifier.cpp, line 4535.
0  swift                    0x0000000108cf6138 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 40
1  swift                    0x0000000108cf67e6 SignalHandler(int) + 454
2  libsystem_platform.dylib 0x00007fff9ec85bba _sigtramp + 26
3  libsystem_platform.dylib 0x00007fdbaaf77a20 _sigtramp + 204414592
4  libsystem_c.dylib        0x00007fff9eb0c420 abort + 129
5  libsystem_c.dylib        0x00007fff9ead3893 basename_r + 0
6  swift                    0x0000000108c4bef9 (anonymous namespace)::VerifierLegacyPass::doFinalization(llvm::Module&) + 185
7  swift                    0x0000000108bc8840 llvm::FPPassManager::doFinalization(llvm::Module&) + 80
8  swift                    0x0000000108bc8d7d llvm::legacy::PassManagerImpl::run(llvm::Module&) + 1261
9  swift                    0x0000000106040ae8 swift::performLLVMOptimizations(swift::IRGenOptions&, llvm::Module*, llvm::TargetMachine*) + 1912
10 swift                    0x000000010604176d swift::performLLVM(swift::IRGenOptions&, swift::DiagnosticEngine*, llvm::sys::SmartMutex<false>*, llvm::GlobalVariable*, llvm::Module*, llvm::TargetMachine*, swift::version::Version const&, llvm::StringRef) + 2765
11 swift                    0x0000000105eff486 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 15654
12 swift                    0x0000000105ebb170 main + 3168
13 libdyld.dylib            0x00007fff9ea78255 start + 1
14 libdyld.dylib            0x00000000000000a2 start + 1633189454

**Comment by nkcsgexi** [comment]
@swift-ci smoke test

**Comment by nkcsgexi** [comment]
@swift-ci Please smoke test OS X Platform

**Comment by jrose-apple** [comment]
Doug should probably be the one to review this.

**Pull request merged**
