### PR TITLE
Gardening: Migrate test suite to GH issues p. 29

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
I didn’t know that git was smart enough to recognize renamed files with modified contents these days, so this is to complement already merged stuff that touched file contents only.

### CODE REVIEW

**Comment by AnthonyLatsis** [comment]
@xedin Please review this one before the rest.

**Review by xedin — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

**Comment by AnthonyLatsis** [comment]
@swift-ci please test macOS

**Comment by AnthonyLatsis** [comment]
@swift-ci please test macOS

**Pull request merged**
