### PR TITLE
ABI: Introduce TargetRelativeProtocolRequirementPointer

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test Windows platform

**Comment by Azoy** [comment]
Can I ask if there is any advantage to doing changes like this? Is it purely for stylistic purposes? (I don't oppose to this change, just curious why the sudden typealias.)

**Comment by slavapestov** [comment]
@Azoy It's part of something else I'm working on.

**Pull request merged**
