### PR TITLE
Spelling irgen

### PR DESCRIPTION
**Pull request by jsoref**
This fixes some misspellings in Swift irgen, it is split per https://github.com/apple/swift/pull/42421#issuecomment-1101092698

### CODE REVIEW

**Comment by CodaFi** [comment]
Let's see if that missing CHECK-line mattered, eh?

@swift-ci smoke test

**Review by CodaFi — APPROVED** [review]

**Comment by jsoref** [comment]
I've dropped the `check` commit @tshortli moved it to #42507

**Comment by jsoref** [comment]
I've dropped the `check` commit @tshortli moved it to #42507

**Comment by tshortli** [comment]
@swift-ci please smoke test

**Pull request merged**
