### PR TITLE
Fixes for witness method devirtualization

### PR DESCRIPTION
**Pull request by swiftix**
Fix a couple of issues in sil-combine and devirtualizer.

Resolves [SR-2623](https://bugs.swift.org/browse/SR-2623).

### CODE REVIEW

**Comment by swiftix** [comment]
@swift-ci Please smoke test

**Comment by swiftix** [comment]
@eeckstein Erik, do you mind taking a look?

**Comment by eeckstein** [comment]
LGTM! Thanks for fixing this

Just a minor suggestion: maybe it makes sense to factor out the code which checks for legal upcasts in to a utility function. If you like you can do this in a separate commit

**Comment by swiftix** [comment]
@eeckstein Do you mean something like what I just pushed?

**Comment by eeckstein** [comment]
Yes, and also use this function in SILVerifier::checkUpcast. (Of course we would have only a single failure-message then, but I think this is OK).

**Comment by swiftix** [comment]
@swift-ci Please smoke test

**Pull request merged**
