### PR TITLE
Add a timeout for lit tests to help diagnose/fail long running tests

### PR DESCRIPTION
**Pull request by zisko**
Adds a timeout for lit tests to help diagnose long running tests.

rdar://30453045

### CODE REVIEW

**Comment by zisko** [comment]
@swift-ci please test

**Comment by zisko** [comment]
Hey @jrose-apple @shahmishal 🍮

**Review by shahmishal — COMMENTED** [review]
LGTM!

**Review by shahmishal — APPROVED** [review]

**Comment by jrose-apple** [comment]
Didn't we already do this? #5830

**Comment by jrose-apple** [comment]
Oh, right, it had to be reverted. Okay, cool.

**Comment by zisko** [comment]
@jrose-apple + this is for 3.1-branch.

**Pull request merged**
