### PR TITLE
Fix inconsiderate naming

### PR DESCRIPTION
**Pull request by pcbro**
Fixes inconsiderate naming in test

### CODE REVIEW

**Comment by peterkellyonline** [comment]
I really do not think Leader / Follower conveys the actual relationship as well as Master / Slave does. Master / Slave are two widely used words in the English language that, when used together in technology, are a well understood and widely-used metaphor. I think if you're offended by that naming in some *codebase* then you need to have a long hard look at yourself and how much time you have on your hands.

**Comment by Jaxan** [comment]
It is not even used as a metaphor. One definition of slave in my dictionary is:

* a device, or part of one, directly controlled by another: [ as modifier ] : a slave cassette deck. Compare with master1.

So it is the proper use of the word.

**Comment by peterkellyonline** [comment]
get a grip people

**Comment by neilkimmett** [comment]
Ignore the haters, I'm a fan of this change. Nice work @pcbro

**Comment by peterkellyonline** [comment]
Master / Slave are perfectly acceptable words in the English language and are very well understood and widely-used term in technology. Leader / Follower as a metaphor does not describe the relationship as well. This change is objectively pointless and introduces inconsistent terminology. If you are offended by this term in some *codebase* then you most likely have too much time on your hands. Perhaps we can ask them to also change the name of the repo? Apple offends me and is inconsiderate because I think of Adam & Eve and the devil...

**Comment by tangentfairy** [comment]
Would replica/primary be a better solution for everyone?

**Comment by Shirk** [comment]
I can only agree with @peterkellyonline and the comment provided by @Jaxan makes it clear that this usage is targeted at the technical application of the terms..

**Comment by s3itz** [comment]
The guys name is 'pcbro' and obviously refers to South Park. Hard to tell if this is genuine or a troll.

**Comment by clooth** [comment]
He's just running stuff through (Alex)[https://github.com/wooorm/alex] I think.

**Comment by ashfurrow** [comment]
If this nomenclature wasn't in Swift 2, would it be added to Swift 3?

I think it's worth considering. If leader/follower isn't the right metaphor, then find a new one.

**Comment by swizzlr** [comment]
Quite beside the point who originated this patch. I don't object at all to "leader" or "follower", and I doubt you'll find anyone who does.

If you're objecting to the _motivation_ of this patch, that is also quite beside the point. The Swift open source community will entirely benefit from a slightly more inclusive change in name that has no impact on development, and more to the point, by accepting this patch (and the untold hundreds of "typo" patches that went through last night) it can be publicly demonstrated that all contributions are welcome and considered on their merits alone.

**Comment by cannyboy** [comment]
Merging into 'master'? Outrageous.

**Comment by Shirk** [comment]
@cannyboy - are you proposing Linus should rename the default branch to `leader` in the next git release? (sorry.. couldn't help myself)

**Comment by peterkellyonline** [comment]
I object to Leader / Follower because it does not describe the concept as well as Master / Slave, which everyone is familiar with. And it is perfectly acceptable terminology used as it is in a technology domain. But more importantly, just because you are offended by something doesn't mean it has to change.

**Comment by cannyboy** [comment]
@shirk the default branch should of course be ````beautiful-melting-pot```` which we all merge into

**Comment by tangentfairy** [comment]
Boy, that escalated quickly

**Comment by jordanekay** [comment]
`master` on its own is fine. `master` and `slave` used the way they are is not.

**Comment by pilky** [comment]
Yeah, removing Master/Slave terminology is certainly worthwhile. Appealing that something was ok in the  past generally isn't a good enough argument to keep it (after all, the whole reason people are starting to question this terminology is because of it's relation to something that was deemed "ok" in the past, but which we no longer view as acceptable).

That said, while Leader/Follower is an improvement I'm not entirely sure it's ideal. Maybe Primary/Replica would be better.

**Comment by czechboy0** [comment]
Manager/worker?

**Comment by neilkimmett** [comment]
Even just master/worker would be fine?

**Comment by czechboy0** [comment]
:+1:

**Comment by Rosyna** [comment]
The English word "Master" is used in technology for a few different reasons.

1. It is the thing that all others are created from. Like master branch, master tape, golden master.

2. It is the thing that gets all requests/orders/dividends and then determines where something should go. This is similar to how Master works with IDE when two drives are on the same bus. See "Marshal".

Sometimes "host" is used instead of "master" (networks, USB, et cetera) as they are synonyms.

When an antonym to "master" was required to indicate a *similar* item that is not defined as "master", "slave" is generally chosen. Not necessarily because of the meaning of the word but because it is an antonym for most uses of the word "master".

**Comment by neilkimmett** [comment]
Its used in a different context, but theres a lot of good discussion on this django PR https://github.com/django/django/pull/2692

**Comment by jckarter** [comment]
Looks good, thanks!

**Pull request merged**
