### PR TITLE
[CSDiagnostics] Don't mention special names in requirement diagnostics

### PR DESCRIPTION
**Pull request by xedin**
Instead of `initializer 'init' of ...` diagnostic should only
mention kind e.g. `initializer of ...` of the declaration
with a special name.

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
I think it doesn't really make sense to mention special names because note is going to point to the right place anyway...

**Comment by jrose-apple** [comment]
No, the names are there so that you can see the parameter names. Please revert.

**Comment by xedin** [comment]
Alright, fair enough

**Comment by xedin** [comment]
As mentioned in the linked PR, I'd change the condition to skip names only if they are special and there are no labels.

**Pull request merged**
