### PR TITLE
[Reflection] Ignore BuiltinTypeDescriptors with zero size, alignment, or stride.

### PR DESCRIPTION
**Pull request by mikeash**
rdar://problem/56784375

### CODE REVIEW

**Comment by jckarter** [comment]
What happens if we remove the check for `Size > 0` altogether? A Swift type could legitimately have zero size.

**Comment by jckarter** [comment]
It'd also be good to strengthen the check on `Alignment` to make sure that it's a power of two (or a power of two minus one, I forget what representation we use here), more than just being greater than zero.

**Comment by slavapestov** [comment]
Can you add a test case?

**Comment by mikeash** [comment]
I added a test and remove the size check. I will also fix up the alignment check as suggested.

**Review by jckarter — APPROVED** [review]
Looks good, thanks!

**Comment by mikeash** [comment]
@swift-ci please test

**Pull request merged**
