### PR TITLE
[ClangImporter] Don't put forward-declared structs in the lookup table.

### PR DESCRIPTION
**Pull request by jrose-apple**
Otherwise, the lookup table for "CGColor" has two entries, because of this:

```
typedef struct CGColor *CGColorRef;
```

and that interferes with our ability to import things as members of "CGColor" (as opposed to "CGColorRef"), which affects the fix-its we generate when you try to use the non-member form.

This isn't necessarily the best long-term solution (as noted in the FIXME) but it is expedient and won't break any current users.

Once this is in, update the CoreGraphics API notes to use non-"Ref" forms for its import-as-member renamings. Since we print the type name in diagnostic text and in fix-its, it's important to use the name that Swift sources use.

rdar://problem/26347297

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by jrose-apple** [comment]
Discussed with @milseman and @DougGregor; this seems like the best way to handle this for now.

@swift-ci Please test

**Comment by jrose-apple** [comment]
…guess now's not a good time to land patches. Will wait for a clean trunk.

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by milseman** [comment]
Linux failure doesn't appear related:
Foundation/NSGeometry.swift:39:25: error: value of type 'NativeType' (aka 'Double') has no member '_toBitPattern'
        return Int(self.native._toBitPattern())
                   ~~~~~^~~~~~ ~~~~~~~~~~~~~

**Comment by jrose-apple** [comment]
Yeah, but I'll wait for a clean trunk anyway.

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by DougGregor** [comment]
@jrose-apple , this looks great. Thanks!

**Comment by milseman** [comment]
LGTM. Thanks for getting this in!

**Comment by jrose-apple** [comment]
Linux failure is in Foundation (unrelated). Merging.

**Pull request merged**
