### PR TITLE
[test] Avoid creating new tmp directory for syntax round-trip testing. rdar://38567449

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by slavapestov** [comment]
That was fast, thanks!

**Comment by nkcsgexi** [comment]
@swift-ci please clean test

**Comment by rintaro** [comment]
It's not easy to clean every bots, right?
How about adding `RUN: rm -rf %t` at the top?

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Pull request merged**
