### PR TITLE
Address TODO about prefixing TF_ to constant names.

### PR DESCRIPTION
**Pull request by pschuh**
Simple TODO fix to test contributing as I'm joining the swift-for-tensorflow team.

### CODE REVIEW

**Comment by bgogul** [comment]
@swift-ci please test tensorflow

**Comment by mhong** [comment]
Very nice. Congrats on getting the first patch out so smoothly and quickly!

Note some (fairly trivial) conflicts with another on-going patch https://github.com/apple/swift/pull/19835. Please coordinate with @marcrasi on submission ordering if needed.

**Review by mhong — APPROVED** [review]

**Comment by rxwei** [comment]
Great!

**Comment by marcrasi** [comment]
I just submitted the conflicting PR.

**Comment by pschuh** [comment]
Merged with Marc's conflicting change.
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@bgogul Loop canonicalization is mysteriously failing [here](https://ci-external.swift.org/job/swift-PR-TensorFlow-macOS/168/testReport/). Is it non-deterministic?

**Comment by bgogul** [comment]
> @bgogul Loop canonicalization is mysteriously failing [here](https://ci-external.swift.org/job/swift-PR-TensorFlow-macOS/168/testReport/). Is it non-deterministic?

Yes, I noticed this in a different PR as well. It is failing only in the macos and I am looking into it. Will update when I find out more. Don't think we should block merging this PR though.

**Comment by rxwei** [comment]
Merging SGTM. Maybe file a bug to track this so that we prioritize the fix next week?

**Pull request merged**
