### PR TITLE
Convert ActionType from "enum" to "enum class".

### PR DESCRIPTION
**Pull request by davidungar**
Convert ActionType from "enum" to "enum class".
Helps with my upcoming PRs.

### CODE REVIEW

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Review by jrose-apple — APPROVED** [review]
Ahhh, we probably avoided the "class" because it's accessed from outside FrontendOptions, and now it's very verbose. It's probably still worth it, though!

**Comment by davidungar** [comment]
@swift-ci Please smoke test

**Comment by davidungar** [comment]
Yes, it is more verbose. But it did find a bug in one of my other changes. Too bad we can't program this in Swift!

**Comment by davidungar** [comment]
Thanks, Jordan, for getting to this so quickly!

**Pull request merged**
