### PR TITLE
Run non-actor-isolated async functions on the generic executor

### PR DESCRIPTION
**Pull request by rjmccall**
Fixes rdar://79284465

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please test

**Comment by rjmccall** [comment]
@swift-ci Please test

**Comment by rjmccall** [comment]
@swift-ci Please test

**Comment by rjmccall** [comment]
@swift-ci Please test

**Comment by rjmccall** [comment]
@swift-ci Please test

**Comment by rjmccall** [comment]
@swift-ci Please test Linux

**Comment by rjmccall** [comment]
Please test with following pull request:
https://github.com/apple/llvm-project/pull/3851

@swift-ci Please test macOS

**Review by DougGregor — COMMENTED** [review]
Looks great, thank you!

**Pull request merged**
