### PR TITLE
Fixes [SR-78] swift compiler seg fault

### PR DESCRIPTION
**Pull request by manavgabhawala**
See #293 
Fixes broken test case which caused revert.

### CODE REVIEW

**Comment by rudkx** [comment]
Did you run -RT?

Can you please rebase & squash so that we do not have a commit in the history that is broken?

**Comment by manavgabhawala** [comment]
The broken commits are a part of the apple/swift repo not my fork so I can't rebase those (the new pull request just has the patched test case). As for running the tests every time I run it I get this error, I don't know what I'm doing wrong:
```
The following tests FAILED:
	  2 - html_normalization (Failed)
	  3 - spectest_library (Failed)
	  5 - spectest_executable (Failed)
	  6 - smartpuncttest_executable (Failed)
Errors while running CTest
*** Failed while running tests for cmark (test)
```

**Comment by rudkx** [comment]
@manavgabhawala It should be possible to rebase your branch against the current apple/swift master and squash. the two commits (reapplying the change, and fixing the test) into one.

I don't know why you're seeing cmark failures.

It should be possible to reconfigure and build without the CMark testing by doing:
  ./utils/build-script -RT -- --skip-test-cmark
(note the -- is intentional, followed by --skip-test-cmark).

**Comment by manavgabhawala** [comment]
@rudkx I fixed the branches. 
About the tests thanks for the tip for the life of me I could not get the tests to run. I know you guys are really busy but I think it might be really worthwhile to flesh out the Testing.rst document because its kind of confusing right now and I found it really difficult to understand. This seems to be passing the tests locally when I run it with `./utils/build-script -RT -- --skip-test-cmark`.

**Comment by rudkx** [comment]
@manavgabhawala I noticed that your test case differs from the one from the original bug. I tried your test case with a compiler that does not have your fix, and it compiles without error, whereas the test case from the original bug demonstrates the problem you're fixing.

Can you please update the test to include an example where it fails without your fix?

Also, since you fixed the enum code as well (which is awesome BTW - good catch), can you include a test case involving enums that fails without your fix but works with it?

Thanks!

**Comment by manavgabhawala** [comment]
@rudkx fixed

**Comment by rudkx** [comment]
LGTM, thanks!

**Pull request merged**
