### PR TITLE
[build-script] Installation support for sourcekit-lsp

### PR DESCRIPTION
**Pull request by benlangmuir**
Add --install-sourcekit-lsp option to build-script and update presets
for package bots to install it.

### CODE REVIEW

**Comment by benlangmuir** [comment]
https://github.com/apple/sourcekit-lsp/pull/142

@swift-ci please build toolchain

**Comment by benlangmuir** [comment]
https://github.com/apple/sourcekit-lsp/pull/142

@swift-ci please smoke test

**Comment by benlangmuir** [comment]
apple/sourcekit-lsp#142

@swift-ci please smoke test

**Comment by benlangmuir** [comment]
apple/sourcekit-lsp#142

@swift-ci please smoke test

**Comment by benlangmuir** [comment]
apple/sourcekit-lsp#142

@swift-ci please build toolchain

**Comment by benlangmuir** [comment]
apple/sourcekit-lsp#142

@swift-ci please build toolchain

**Comment by gottesmm** [comment]
nice!

**Pull request merged**
