### PR TITLE
[Concurrency] Delete runAsyncAndBlock

### PR DESCRIPTION
**Pull request by etcwilde**
This patch deletes `runAsyncAndBlock` since we don't want folks getting comfortable with it.

We had several places in the testing where we used that function, so the standard library unittest framework needed up be updated to run async functions. The top-level function for running the tests is `runAllTestsAsync`. Once we have async working at the top-level, it will probably make more sense to just make `runAllTests` async and get rid of that. Then we can merge the duplicate async implementations of everything. Just grep'ing, I see 366 places where `runAllTests` gets called and I don't really want to wrap all of those places in the async-main, so having the split async/sync implementations is necessary until the top-level can have an async context.

Since we're using async in the unit tests, we need to link in the concurrency library into the stdlib unit tests too. This shouldn't affect anyone using the language since we don't vend the stdlib unittest framework and it isn't public.

Resolves: rdar://73906556

### CODE REVIEW

**Comment by etcwilde** [comment]
@swift-ci please smoke test

**Comment by etcwilde** [comment]
@swift-ci please smoke test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test macOS

**Comment by etcwilde** [comment]
@swift-ci please test macOS

**Comment by etcwilde** [comment]
@swift-ci please smoke test

**Comment by etcwilde** [comment]
@swift-ci please test

**Comment by etcwilde** [comment]
@swift-ci please test macOS platform

**Comment by etcwilde** [comment]
The test is failing while building cmark. This PR doesn't touch anything in CMark or CMark related, so I don't know what's going on there.

**Comment by etcwilde** [comment]
@swift-ci please smoke test

**Comment by etcwilde** [comment]
lldb had some references to `runAsyncAndBlock` in their tests.
I've posted https://github.com/apple/llvm-project/pull/2758 to remove it.

**Comment by etcwilde** [comment]
@swift-ci please smoke test Windows

**Comment by etcwilde** [comment]
@swift-ci please smoke test macOS

**Comment by etcwilde** [comment]
@swift-ci please smoke test Windows

**Comment by etcwilde** [comment]
@swift-ci please smoke test Windows

**Comment by etcwilde** [comment]
@swift-ci please smoke test

**Comment by etcwilde** [comment]
@swift-ci please smoke test

**Comment by etcwilde** [comment]
@swift-ci please smoke test

**Comment by davezarzycki** [comment]
Commit `1d06521f32d823f163824ff25e8e300846b9ab7d` broke the ability to compile the unit tests when doing a "minimal dependency" build of Swift which is useful/interesting for various reasons. Yes, I know "minimal dependency" builds aren't the supported path, but I'd really like to keep them working as long as possible.

Can we break the concurrency dependent unit tests out into something that can be disabled?

**Comment by etcwilde** [comment]
> Commit `1d06521f32d823f163824ff25e8e300846b9ab7d` broke the ability to compile the unit tests when doing a "minimal dependency" build of Swift which is useful/interesting for various reasons. Yes, I know "minimal dependency" builds aren't the supported path, but I'd really like to keep them working as long as possible.
> 
> Can we break the concurrency dependent unit tests out into something that can be disabled?

Sure, can you give me more information on how to set up a minimal dependency build and what the necessary cmake flags are so that I can plumb that info through? Thanks.

**Comment by davezarzycki** [comment]
I don't think reproducing my build setup is strictly necessary. I don't use `build-script` but passing `--extra-cmake-options -DSWIFT_ENABLE_EXPERIMENTAL_CONCURRENCY=FALSE` should hopefully do the trick. You can verify by grepping for `SWIFT_ENABLE_EXPERIMENTAL_CONCURRENCY` in the resulting CMakeCache.txt in the build directory.

Also, I'm already trying to figure out a workaround.

**Comment by etcwilde** [comment]
Okay, I'll take a look when I get a moment.

**Comment by davezarzycki** [comment]
I found a workaround and I added it to the existing PR fix: #36841

**Pull request merged**
