### PR TITLE
Fix IRGen debug info for swift_task_alloc'ed variables.

### PR DESCRIPTION
**Pull request by adrian-prantl**
The old code attempted to load the variable despite not knowing its size. Fixed by describing the variable's address on the task heap.

### CODE REVIEW

**Comment by adrian-prantl** [comment]
Matching LLDB test can be found in https://github.com/apple/llvm-project/pull/5768

**Comment by adrian-prantl** [comment]
Discovered via https://github.com/apple/swift/pull/62499

**Review by aschwaighofer — APPROVED** [review]
LGTM. Thank you!

**Comment by JetForMe** [comment]
I wasn't sure but also didn't think so. Just trying to be thorough. I may know the words and grammar, but reading that code is like Darmok & Jalad at Tanagra.

**Comment by JetForMe** [comment]
Hmm, I'm still experiencing the symptom of the Xcode debugger not seeing some local variables that are clearly in scope and accessible, in this case running in a `Task { }` block (via function call) on macOS. Happy to provide this project.

**Comment by adrian-prantl** [comment]
> Happy to provide this project.

That would be great. Either bugs.swift.org or feedback.apple.com work.

**Comment by JetForMe** [comment]
Set a breakpoint in DaemonCollector.swift:153 and run it. It should stop there almost immediately. Try to inspect the variables lower in the list in the Xcode variables pane (interestingly, it seems there's a line on the list above which variables are inspectable, below which they are not, and I feel like this has always been the case).

See the screenshot for examples (I context-clicked on `label` and `executablePath` and chose “Print description of”):

Screenshot 2023-02-06 at 16 57 03

[Exorcist.zip](https://github.com/apple/swift/files/10670435/Exorcist.zip)

**Comment by adrian-prantl** [comment]
Thanks! Here's an even shorter reproducer:

**Pull request merged**
