### PR TITLE
[stdlib] Silence some standard library warnings

### PR DESCRIPTION
**Pull request by Azoy**
The protocol refinement warning is informational, but for the specific case of `SIMDScalar` implicitly inheriting from `Hashable`, `Encodable`, and `Decodable` we cannot add those to the protocol signature because it would alter its ABI. Skip those cases as we can't fix them in the foreseeable future.

The macro warnings are simply due to the fact that the macro definitions are referencing builtin types that do not exist, so the parser emits a warning and skips that declaration entirely. Just ifdef them out until someone does come around and implement those builtins.

### CODE REVIEW

**Comment by Azoy** [comment]
@swift-ci please smoke test

**Comment by Azoy** [comment]
@swift-ci please smoke test

**Comment by Azoy** [comment]
@swift-ci please smoke test macOS

**Comment by Azoy** [comment]
@swift-ci please smoke test

**Review by glessard — APPROVED** [review]
A good quality-of-life improvement for stdlib development.

**Pull request merged**
