### PR TITLE
Remove redundant assertion, which is already checked at lower level.

### PR DESCRIPTION
**Pull request by davidungar**

### CODE REVIEW

**Comment by davidungar** [comment]
@swift-ci please smoke test os x platform

**Comment by jrose-apple** [comment]
I think we've reached the point where you don't need my review on this sort of thing. It's in code you've already touched and it should be a "no-functionality-change" commit. (That said, it's not an unreasonable principle to say *every* PR should have a second pair of eyes.)

**Comment by davidungar** [comment]
@swift-ci please smoke test linux platform

**Review by graydon — APPROVED** [review]
I guess? I don't see the harm in redundant asserts, but if it's truly checked elsewhere (where?) then sure.

**Pull request merged**
