### PR TITLE
Sema: implement `existentialTypeSupported` using a request evaluator.

### PR DESCRIPTION
**Pull request by hborla**
Add the request `ExistentialTypeSupportedRequest` to lazily determine
if we are allowed to refer to an existential type conforming to a
protocol.

### CODE REVIEW

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by hborla** [comment]
@swift-ci please test source compatibility

**Review by xymus — APPROVED** [review]

**Review by slavapestov — APPROVED** [review]

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by hborla** [comment]
Restarting the tests since the python lint error is fixed: https://github.com/apple/swift/pull/26281/commits

**Comment by hborla** [comment]
@swift-ci please smoke test OS X

**Pull request merged**
