### PR TITLE
[gardening] Fix incorrect header. PEP-8 fixes. Fix spacing. Fix \t.

### PR DESCRIPTION
**Pull request by practicalswift**
Misc gardening:
- Fix incorrect header.
- PEP-8 fixes.
- Fix accidental `\t`.
- Fix incorrect spacing.

### CODE REVIEW

**Comment by practicalswift** [comment]
@swift-ci please smoke test and merge

**Comment by CodaFi** [comment]
@swift-ci please python lint.

**Comment by CodaFi** [comment]
Strange that it doesn't report this violation clearly

> Import statements are in the wrong order. import argparse should be before from multiprocessing

**Comment by moiseev** [comment]
@swift-ci Please smoke test Linux platform

**Comment by practicalswift** [comment]
@CodaFi Good point! Will take that fix in another PR

**Pull request merged**
