### PR TITLE
Add PR test presets for sourcekit-lsp and indexstore-db

### PR DESCRIPTION
**Pull request by benlangmuir**
rdar://47984030

### CODE REVIEW

**Comment by benlangmuir** [comment]
preset=buildbot_sourcekitlsp_macos
@swift-ci Please test with preset macOS Platform

**Comment by benlangmuir** [comment]
preset=buildbot_sourcekitlsp_linux
@swift-ci Please test with preset Linux Platform

**Comment by benlangmuir** [comment]
@swift-ci please smoke test

**Comment by benlangmuir** [comment]
preset=buildbot_indexstoredb_linux
@swift-ci Please test with preset Linux Platform

**Review by shahmishal — APPROVED** [review]

**Pull request merged**
