### PR TITLE
[5.1 04-24-2019] [IRGen] Emit lazy opaque type descriptors.

### PR DESCRIPTION
**Pull request by DougGregor**
These were recorded but never emitted. Fixes rdar://problem/50258536.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@AnnaZaks FYI

**Comment by DougGregor** [comment]
@swift-ci please test

**Review by AnnaZaks — APPROVED** [review]

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test Linux

**Comment by DougGregor** [comment]
@swift-ci please test Linux

**Pull request merged**
