### PR TITLE
[cxx-interop] Emit retain/release correctly for FRT's that are stored…

### PR DESCRIPTION
**Pull request by zoecarver**
… in optionals and have custom ref counting instructions.

### CODE REVIEW

**Comment by zoecarver** [comment]
@swift-ci please test

**Review by hyp — APPROVED** [review]

**Comment by zoecarver** [comment]
@swift-ci please test

**Comment by zoecarver** [comment]
@swift-ci please test

**Comment by zoecarver** [comment]
@swift-ci please test

**Comment by zoecarver** [comment]
@swift-ci please test

**Pull request merged**
