### PR TITLE
[6.0][stdlib] Undo the generalization of `Result.map` & `.flatMap` for now

### PR DESCRIPTION
**Pull request by lorentey**
(This is a cherry pick of #72477.)

The generalization of `Result.map` is currently causing source compatibility issues, as `map` variants defined in downstream projects are no longer considered to shadow the stdlib original. (rdar://125016028)

Similar issues can affect pretty much every API generalized for `~Copyable`, so the right thing to do is probably to adjust the compiler to maintain the original shadowing semantics. But for now, we can take out the cases that we see causing problems as we encounter them.

We have not generalized `Optional`’s `map` and `flatMap` yet, so it seems premature to do it for `Result`, anyway.

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test source compatibility

**Comment by lorentey** [comment]
(Apologies for the review request noise, everyone! I initially set the wrong target branch.)

**Review by tbkka — APPROVED** [review]

**Comment by lorentey** [comment]
@swift-ci test

**Pull request merged**
