### PR TITLE
[TF] Enable optimizations on the TensorFlow module.

### PR DESCRIPTION
**Pull request by rxwei**
Enable optimizations when building the TensorFlow module.

Resolves [TF-95](https://bugs.swift.org/browse/TF-95).

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Review by dan-zheng — APPROVED** [review]

**Comment by eaplatanios** [comment]
@rxwei I still had test failures when I tried that. You might need to remove the `list(APPEND swift_stdlib_compile_flags "-Onone")` line following the line you added. I'm not sure if `-O` overrides `-Onone` if both are provided.

**Comment by rxwei** [comment]
> @rxwei I still had test failures when I tried that. You might need to remove the `list(APPEND swift_stdlib_compile_flags "-Onone")` line following the line you added. I'm not sure if `-O` overrides `-Onone` if both are provided.

Oh good catch!

**Review by bgogul — APPROVED** [review]

**Comment by rxwei** [comment]
There are two failures.

```console
********************
Testing Time: 36.97s
********************
Failing Tests (2):
    Swift(macosx-x86_64) :: TensorFlowRuntime/model_autodiff_runtime.swift
    Swift(macosx-x86_64) :: TensorFlowRuntime/string_description.swift

  Expected Passes    : 34
  Expected Failures  : 1
  Unexpected Failures: 2
```

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux

**Comment by eaplatanios** [comment]
> There are two failures.
> 
> ```
> ********************
> Testing Time: 36.97s
> ********************
> Failing Tests (2):
>     Swift(macosx-x86_64) :: TensorFlowRuntime/model_autodiff_runtime.swift
>     Swift(macosx-x86_64) :: TensorFlowRuntime/string_description.swift
> 
>   Expected Passes    : 34
>   Expected Failures  : 1
>   Unexpected Failures: 2
> ```

Yes, that matches what I got earlier today I think.

**Comment by rxwei** [comment]
@swift-ci please test tensorflow Linux

**Comment by eaplatanios** [comment]
@dan-zheng I just tested this as mentioned earlier and I get an error when compiling:
```
1.      Swift version 5.1-dev (LLVM 200186e28b, Swift 5bbe84be09)
2.      While running pass #1079646 SILFunctionTransform "GenericSpecializer" on SILFunction "@$sSass14DifferentiableRzlE0A4ViewV10TensorFlows23PointwiseMultiplicativeRzrlE3zmeoiyyACyx_Gz_AGtFZ".
 for '.*=(_:_:)' (at /Users/eaplatanios/Development/GitHub/swift-source-temp/tensorflow-swift-apis/Sources/TensorFlow/StdlibExtensions.swift:265:12)
0  swift                    0x0000000114a8772c llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 60
1  swift                    0x0000000114a87c89 PrintStackTraceSignalHandler(void*) + 25
2  swift                    0x0000000114a850a6 llvm::sys::RunSignalHandlers() + 118
3  swift                    0x0000000114a8da02 SignalHandler(int) + 210
4  libsystem_platform.dylib 0x00007fff6634cb5d _sigtramp + 29
5  libsystem_platform.dylib 000000000000000000 _sigtramp + 2580231360
6  libsystem_c.dylib        0x00007fff662066a6 abort + 127
7  swift                    0x00000001148e7860 llvm::install_out_of_memory_new_handler() + 0
8  swift                    0x000000010ca84639 (anonymous namespace)::TypeClassifierBase<(anonymous namespace)::TypeClassifier, swift::Lowering::TypeLowering::RecursiveProperties>::visitAbstractTypeParamType(swift::CanType) + 345
9  swift                    0x000000010ca83285 (anonymous namespace)::TypeClassifierBase<(anonymous namespace)::TypeClassifier, swift::Lowering::TypeLowering::RecursiveProperties>::visitDependentMemberType(swift::CanTypeWrapper<swift::DependentMemberType>) + 37
10 swift                    0x000000010ca8248b swift::CanTypeVisitor<(anonymous namespace)::TypeClassifier, swift::Lowering::TypeLowering::RecursiveProperties>::visit(swift::CanType) + 2235
11 swift                    0x000000010ca77e9b classifyType(swift::CanType, swift::SILModule&, swift::CanGenericSignature, swift::ResilienceExpansion) + 75
12 swift                    0x000000010ca935ed (anonymous namespace)::LowerType::visitAnyStructType(swift::CanType, swift::StructDecl*) + 669
13 swift                    0x000000010ca8cd86 (anonymous namespace)::TypeClassifierBase<(anonymous namespace)::LowerType, swift::Lowering::TypeLowering*>::visitStructType(swift::CanTypeWrapper<swift::StructType>) + 70
14 swift                    0x000000010ca7a681 swift::CanTypeVisitor<(anonymous namespace)::LowerType, swift::Lowering::TypeLowering*>::visit(swift::CanType) + 1185
15 swift                    0x000000010ca7950a swift::Lowering::TypeConverter::getTypeLowering(swift::Lowering::AbstractionPattern, swift::Type, swift::ResilienceExpansion) + 1034
16 swift                    0x000000010c856434 swift::Lowering::TypeConverter::getLoweredType(swift::Lowering::AbstractionPattern, swift::Type, swift::ResilienceExpansion) + 116
17 swift                    0x000000010bc76e60 swift::Lowering::TypeConverter::getLoweredRValueType(swift::Lowering::AbstractionPattern, swift::Type) + 112
18 swift                    0x000000010c87f525 (anonymous namespace)::SILTypeSubstituter::visitType(swift::CanType) + 805
19 swift                    0x000000010c87f940 swift::CanTypeVisitor<(anonymous namespace)::SILTypeSubstituter, swift::CanType>::visitNominalType(swift::CanTypeWrapper<swift::NominalType>) + 48
20 swift                    0x000000010c87eac0 swift::CanTypeVisitor<(anonymous namespace)::SILTypeSubstituter, swift::CanType>::visitStructType(swift::CanTypeWrapper<swift::StructType>) + 48
21 swift                    0x000000010c87dd41 swift::CanTypeVisitor<(anonymous namespace)::SILTypeSubstituter, swift::CanType>::visit(swift::CanType) + 1185
22 swift                    0x000000010c86f382 (anonymous namespace)::SILTypeSubstituter::subst(swift::SILType) + 50
23 swift                    0x000000010c86f2cb swift::SILType::subst(swift::SILModule&, llvm::function_ref<swift::Type (swift::SubstitutableType*)>, llvm::function_ref<llvm::Optional<swift::ProtocolConformanceRef> (swift::CanType, swift::Type, swift::ProtocolDecl*)>, swift::CanGenericSignature, bool) const + 475
24 swift                    0x000000010c86f465 swift::SILType::subst(swift::SILModule&, swift::SubstitutionMap) const + 181
25 swift                    0x000000010c60f2d2 swift::TypeSubstCloner<swift::GenericCloner, swift::SILOptFunctionBuilder>::remapType(swift::SILType) + 114
26 swift                    0x000000010c60f077 swift::GenericCloner::populateCloned() + 631
27 swift                    0x000000010c635708 swift::GenericCloner::cloneFunction(swift::SILOptFunctionBuilder&, swift::SILFunction*, swift::ReabstractionInfo const&, swift::SubstitutionMap, llvm::StringRef, std::__1::function<void (swift::SILInstruction*, swift::SILInstruction*)>) + 264
28 swift                    0x000000010c63535c swift::GenericFuncSpecializer::tryCreateSpecialization() + 412
29 swift                    0x000000010c636ec9 swift::trySpecializeApplyOfGeneric(swift::SILOptFunctionBuilder&, swift::ApplySite, llvm::SmallSetVector<swift::SILInstruction*, 8u>&, llvm::SmallVectorImpl<swift::SILFunction*>&, swift::OptRemark::Emitter&) + 1897
30 swift                    0x000000010c470b88 (anonymous namespace)::GenericSpecializer::specializeAppliesInFunction(swift::SILFunction&) + 1192
31 swift                    0x000000010c47069b (anonymous namespace)::GenericSpecializer::run() + 203
32 swift                    0x000000010c2f3ad9 swift::SILPassManager::runPassOnFunction(unsigned int, swift::SILFunction*) + 1401
33 swift                    0x000000010c2f6356 swift::SILPassManager::runFunctionPasses(unsigned int, unsigned int) + 1094
34 swift                    0x000000010c2f7b80 swift::SILPassManager::execute() + 848
35 swift                    0x000000010b7737bb swift::SILPassManager::executePassPipelinePlan(swift::SILPassPipelinePlan const&) + 315
36 swift                    0x000000010c3221ba swift::runSILOptimizationPasses(swift::SILModule&) + 282
37 swift                    0x000000010b98b69e performSILOptimizations(swift::CompilerInvocation&, swift::SILModule*) + 350
38 swift                    0x000000010b98b36b swift::CompilerInstance::performSILProcessing(swift::SILModule*, swift::UnifiedStatsReporter*) + 267
39 swift                    0x000000010b3c58af performCompileStepsPostSILGen(swift::CompilerInstance&, swift::CompilerInvocation&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule> >, bool, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::PrimarySpecificPaths const&, bool, int&, swift::FrontendObserver*, swift::UnifiedStatsReporter*) + 1215
40 swift                    0x000000010b3bb1b0 performCompile(swift::CompilerInstance&, swift::CompilerInvocation&, llvm::ArrayRef<char const*>, int&, swift::FrontendObserver*, swift::UnifiedStatsReporter*) + 1888
41 swift                    0x000000010b3b9bf8 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 2552
42 swift                    0x000000010b2a0290 run_driver(llvm::StringRef, llvm::ArrayRef<char const*>) + 912
43 swift                    0x000000010b29eb6b main + 2715
44 libdyld.dylib            0x00007fff661613d5 start + 1
<unknown>:0: error: unable to execute command: Abort trap: 6
<unknown>:0: error: compile command failed due to signal 6 (use -v to see invocation)
```

**Comment by rxwei** [comment]
It could be a bug from upstream.

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
