### PR TITLE
[Incremental] Adjust test to cope with better remark in new driver

### PR DESCRIPTION
**Pull request by davidungar**
Unblocks https://ci.swift.org/job/swift-PR-macos/ by adjusting test to cope with the improved remark in https://github.com/apple/swift-driver/pull/728 .

### CODE REVIEW

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Comment by davidungar** [comment]
@swift-ci please smoke test macos platform

**Comment by davidungar** [comment]
@swift-ci please smoke test macos platform

**Comment by DougGregor** [comment]
@swift-ci please smoke test macos

**Comment by davidungar** [comment]
Thanks, @DougGregor !

**Pull request merged**
