### PR TITLE
Re-integrate python-lint into tests

### PR DESCRIPTION
**Pull request by hughbe**
This was reverted as it caused build failures after it was committed.

The reasons for this were twofold:
- Simultaneous committing of non-conformant python code in `build-script`
- Incorrectly configured `.flake8` config file that seemingly non-deterministically gave errors or didn't

As you can see, there are lots of places that should've been picked up, but weren't

### CODE REVIEW

**Comment by hughbe** [comment]
@swift-ci please test

**Comment by hughbe** [comment]
@swift-ci Please asan test

**Comment by shahmishal** [comment]
We should only run python lint test once.

```19:44:09 PASS: Swift(macosx-x86_64) :: Python/python-lint.swift (480 of 9570)
19:55:57 PASS: Swift(iphonesimulator-i386) :: Python/python-lint.swift (488 of 9570)
20:07:46 PASS: Swift(iphonesimulator-x86_64) :: Python/python-lint.swift (488 of 9570)
20:20:00 PASS: Swift(appletvsimulator-x86_64) :: Python/python-lint.swift (488 of 9570)
20:32:10 PASS: Swift(watchsimulator-i386) :: Python/python-lint.swift (488 of 9570)```

**Comment by hughbe** [comment]
Do you know how we can do that?

**Comment by gottesmm** [comment]
I would just disable it on those platforms using UNSUPPORTED. And also put in a large comment above the UNSUPPORTED lines saying why you are doing it.

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by hughbe** [comment]
Thanks @gottesmm, done

**Comment by hughbe** [comment]
I'm going to hold off fixing merge conflicts for this PR until @erg's refactorings to build-script are stable and don't keep causing merge conflicts :)

**Comment by erg** [comment]
@hughbe You can merge this if you want and I'll deal with the merge conflicts.

**Comment by hughbe** [comment]
@swift-ci please smoke test and merge

**Comment by hughbe** [comment]
@swift-ci please smoke test and merge

**Comment by hughbe** [comment]
Okay, thanks @erg. I didn't want to create merge conflicts for you or potentially break the build by having several files committed at the same time (now any python lint violations will be found during `smoke test`)

**Comment by hughbe** [comment]
If we get any problems with this after it merges, I suggest the following:
- If it's due to files committed at the same time or non-rebased python files: don't revert this PR but fix the violations. This should be easy
- If it's due to the python linting being broken or non-deterministic, don't revert this entire PR, but commit fbad5fdfa68e5b55a86dfb70a7bdb275edda888f only

**Pull request merged**
