### PR TITLE
IRGen: Don't emit opaque type descriptors twice

### PR DESCRIPTION
**Pull request by aschwaighofer**
rdar://50500620

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
I guess a test case would require the lazy opaque type to be referenced before its definition point? So probably again lifting it to a typealias via associated type inference might be the easiest way

**Comment by aschwaighofer** [comment]
I will follow-up with a test case later.

**Pull request merged**
