### PR TITLE
[5.10][Build] Enable macros on 5.10

### PR DESCRIPTION
**Pull request by bnbarham**
Fetch and extract a prebuilt toolchain to enable macros support on 5.10. This is a squashed cherry-pick of #68319, #68641, and #68835.

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Review by compnerd — APPROVED** [review]
If it builds, ship it!

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
Ah we need the installer script changes too :(

**Comment by bnbarham** [comment]
I missed https://github.com/apple/swift/pull/68411. Added that in.

**Comment by bnbarham** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
