### PR TITLE
cleanup LangOptions

### PR DESCRIPTION
**Pull request by compnerd**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by gottesmm** [comment]
@dgregor what do you think?

**Comment by compnerd** [comment]
I have a building backlog of patches.  I'd like to get this merged so I can start flushing them.

**Pull request merged**
