### PR TITLE
Fix `'linker' input unused` warnings in Explicit Module Builds

### PR DESCRIPTION
**Pull request by artemcm**
- Use `=` version of `-working-directory` flag when passing it to clang
Under some circumstances this prevents the directory argument from being treated as an arbitrary path input.

- Omit path to `clang` from PCM build command-line
It gets interpreted as just an executable we feed to the linker, since we launch `emit-pcm` actions via `swift-frontend` invocations, not `clang`.

Resolves rdar://83104047

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci please test

**Review by nkcsgexi — APPROVED** [review]

**Comment by artemcm** [comment]
@swift-ci please test Windows platform

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test macOS platform

**Comment by artemcm** [comment]
@swift-ci please test windows platform

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test Windows platform

**Comment by artemcm** [comment]
@swift-ci please test Windows platform

**Pull request merged**
