### PR TITLE
Remove AnyObject protocol once and for all

### PR DESCRIPTION
**Pull request by slavapestov**
@DougGregor told me that SE-0156 is not really done until the AnyObject protocol is gone. So here you go.

I'm going to debug and land https://github.com/apple/swift/pull/9096 first; this PR only contains one additional patch on top of that one.

### CODE REVIEW

**Comment by slavapestov** [comment]
@DougGregor only 199 test failures :-) Yeah, it needs a bit of work still. But the stdlib builds!

**Comment by DougGregor** [comment]
Once the stdlib builds, the rest is easy

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Pull request closed without merging**
