### PR TITLE
[5.9] Fix MoveOnlyAddressChecker to handle value deinits

### PR DESCRIPTION
**Pull request by atrick**
Fixes rdar://110232973 ([move-only] Checker should distinguish in between field of single field struct vs parent field itself (was: mutation of field in noncopyable struct should not trigger deinit))

(cherry picked from commit a8c45c55c4839ba58344073b201507ba6a59dc35)

--- CCC ---

- Explanation: Track liveness of self so we don't accidentally think that such types can be memberwise reinitialized.

- Scope of Issue: Miscompilation occurs for a NonCopyable struct with a deinit. The deinitializer incorrectly runs when the programmer reassigns the struct fields.

- Risk: This change only affects the MoveOnlyAddressChecker, which was already miscompiling cases that weren't explicitly tested.

- PR to main: https://github.com/apple/swift/pull/66691

- Reviewed By: Michael Gottesman

- Resolves: rdar://110232973 ([move-only] Checker should distinguish in between field of single field struct vs parent field itself (was: mutation of field in noncopyable struct should not trigger deinit))

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test

**Review by tbkka — APPROVED** [review]

**Comment by atrick** [comment]
Note that this needed to be updated for 5.9:

```
73:14: error: no member named 'isValueTypeWithDeinit' in 'swift::SILType'
    if (type.isValueTypeWithDeinit()) {
        ~~~~ ^
```

Needs to be

```
if (auto *nominal = getNominalOrBoundGenericNominal()) {
    if (nominal->getValueTypeDestructor() != nullptr) {
```

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci test

**Pull request merged**
