### PR TITLE
[SILOpt] Make sure that dynamically replaced function is kept alive

### PR DESCRIPTION
**Pull request by xedin**
Don't really know how to test this properly, noticed while working on https://github.com/apple/swift/pull/42252.

### CODE REVIEW

**Review by aschwaighofer — APPROVED** [review]
The dynamically replaced function declaration/definition should be kept alive by such a reference.

This LGTM.

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Review by ktoso — APPROVED** [review]
Huh, makes sense same as distributed 👍

**Pull request merged**
