### PR TITLE
[silgenpattern] Change all loadable types to always go through the ownership preserving tuple code.

### PR DESCRIPTION
**Pull request by gottesmm**
[silgenpattern] Change all loadable types to always go through the ownership preserving tuple code.

To do this the commit does a few things:

1. If we enter the tuple dispatch code with an address that is loadable, we
always immediately perform a load_borrow and change the consumable managed value
to BorrowAlways.

2. If we have a take_on_success object, we immediately borrow. We do not want to
do with TakeOnSuccess since we want to define away the need to unforward since
unforwarding recreates a destroy on the already invalidated parent tuple object.

Notice that this code still handles TakeAlways so in simple cases where we have
a +1 value, everything still works.

Since emitTupleDispatchWithOwnership now handles only objects, I renamed it to
emitTupleObjectDispatch.

rdar://29791263

----

Note the commit in question is just the last commit. I have a string of commits that this is based upon that are being committed in other PRs: apple/swift#19837 and apple/swift#19838

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
Going to consolidate these changes into 1 PR as per Slava's request.

**Comment by gottesmm** [comment]
Or actually, I am going to use this 1 PR for all of them.

**Comment by gottesmm** [comment]
@slavapestov I made the changes you requested to the first commit.

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Review by slavapestov — APPROVED** [review]

**Pull request merged**
