### PR TITLE
[opt-remark] Rather than just dropping debug info when emitting RR ops, use the location of the insertPt instruction.

### PR DESCRIPTION
**Pull request by gottesmm**
This will ensure that we are not adding new locations to step and when we emit
opt-remarks, we can still emit a source location for where the rr ended up.

I only changed things around RR where we just created the SILBuilderWithScope at the insert pt so it was obvious the correct location to use.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
preset=buildbot,tools=RA,stdlib=RD,test=non_executable
@swift-ci Please test with preset macOS

**Comment by gottesmm** [comment]
I am testing as much as I can since in the past when we messed with line tables sometimes we hit verification errors. So I am just trying to compile as much code as possible.

**Comment by gottesmm** [comment]
@swift-ci test windows platform

**Comment by gottesmm** [comment]
Yep. I was right:

```
SIL verification failed: artificial locations are only allowed on Unreachable instructions: InstKind == SILInstructi\
onKind::UnreachableInst                                                                                              
Verifying instruction:                                                                                               
     %18 = copy_value %17 : $@callee_guaranteed () -> @owned String // users: %22, %19                               
->   destroy_value %18 : $@callee_guaranteed () -> @owned String // id: %22
```

@adrian-prantl do you have any suggestions on how to deal with this? My thought is that we should for rr maybe have a wrapper SILLocation (like Mandatory Inlined Location) for when we move it. That way we know that the source location on the RR is special and can early out from this. IMO we want to be able to arbitrarily move around rr and having assertions like this I don't know if they even make sense for ARC.

```
// String._nativeCopyUTF16CodeUnits(into:range:)
sil [ossa] @$sSS25_nativeCopyUTF16CodeUnits4into5rangeySrys6UInt16VG_SnySS5IndexVGtF : $@convention(method) (UnsafeMutableBufferPointer<UInt16>, Range<String.Index>, @guaranteed String) -> () {
// %0 "buffer"                                    // user: %3
// %1 "range"                                     // user: %4
// %2 "self"                                      // user: %5
bb0(%0 : $UnsafeMutableBufferPointer<UInt16>, %1 : $Range<String.Index>, %2 : @guaranteed $String):
  debug_value %0 : $UnsafeMutableBufferPointer<UInt16>, let, name "buffer", argno 1 // id: %3
  debug_value %1 : $Range<String.Index>, let, name "range", argno 2 // id: %4
  debug_value %2 : $String, let, name "self", argno 3 // id: %5
  %6 = string_literal utf8 "/Volumes/swift-ci/jenkins/workspace/swift-PR-osx/branch-master/swift/stdlib/public/core/LegacyABI.swift" // user: %11
  %7 = integer_literal $Builtin.Word, 103         // user: %11
  %8 = integer_literal $Builtin.Int1, -1          // user: %11
  %9 = metatype $@thin StaticString.Type          // user: %11
  // function_ref StaticString.init(_builtinStringLiteral:utf8CodeUnitCount:isASCII:)
  %10 = function_ref @$ss12StaticStringV08_builtinB7Literal17utf8CodeUnitCount7isASCIIABBp_BwBi1_tcfC : $@convention(method) (Builtin.RawPointer, Builtin.Word, Builtin.Int1, @thin StaticString.Type) -> StaticString // user: %11
  %11 = apply %10(%6, %7, %8, %9) : $@convention(method) (Builtin.RawPointer, Builtin.Word, Builtin.Int1, @thin StaticString.Type) -> StaticString // user: %21
  %12 = integer_literal $Builtin.IntLiteral, 80   // user: %15
  %13 = metatype $@thin UInt.Type                 // user: %15
  // function_ref UInt.init(_builtinIntegerLiteral:)
  %14 = function_ref @$sSu22_builtinIntegerLiteralSuBI_tcfC : $@convention(method) (Builtin.IntLiteral, @thin UInt.Type) -> UInt // user: %15
  %15 = apply %14(%12, %13) : $@convention(method) (Builtin.IntLiteral, @thin UInt.Type) -> UInt // user: %21
  // function_ref default argument 0 of fatalError(_:file:line:)
  %16 = function_ref @$ss10fatalError_4file4lines5NeverOSSyXK_s12StaticStringVSutFfA_ : $@convention(thin) () -> @owned @callee_guaranteed () -> @owned String // user: %17
  %17 = apply %16() : $@convention(thin) () -> @owned @callee_guaranteed () -> @owned String // user: %18
  %18 = copy_value %17 : $@callee_guaranteed () -> @owned String // users: %22, %19
  %19 = convert_escape_to_noescape %18 : $@callee_guaranteed () -> @owned String to $@noescape @callee_guaranteed () -> @owned String // user: %21
  // function_ref fatalError(_:file:line:)
  %20 = function_ref @$ss10fatalError_4file4lines5NeverOSSyXK_s12StaticStringVSutF : $@convention(thin) (@noescape @callee_guaranteed () -> @owned String, StaticString, UInt) -> Never // user: %21
  %21 = apply %20(%19, %11, %15) : $@convention(thin) (@noescape @callee_guaranteed () -> @owned String, StaticString, UInt) -> Never
  destroy_value %18 : $@callee_guaranteed () -> @owned String // id: %22
  unreachable                                     // id: %23
} // end sil function '$sSS25_nativeCopyUTF16CodeUnits4into5rangeySrys6UInt16VG_SnySS5IndexVGtF'
```

Failed in:

4.      While running pass #128168 SILFunctionTransform "ClosureLifetimeFixup" on SILFunction "@$sSS25_nativeCopyUTF\
16CodeUnits4into5rangeySrys6UInt16VG_SnySS5IndexVGtF".

**Comment by adrian-prantl** [comment]
> Yep. I was right:
> 
> ```
> SIL verification failed: artificial locations are only allowed on Unreachable instructions: InstKind == SILInstructi\
> onKind::UnreachableInst                                                                                              
> Verifying instruction:                                                                                               
>      %18 = copy_value %17 : $@callee_guaranteed () -> @owned String // users: %22, %19                               
> ->   destroy_value %18 : $@callee_guaranteed () -> @owned String // id: %22
> ```
> 
> @adrian-prantl do you have any suggestions on how to deal with this? My thought is that we should for rr maybe have a wrapper SILLocation (like Mandatory Inlined Location) for when we move it. That way we know that the source location on the RR is special and can early out from this. IMO we want to be able to arbitrarily move around rr and having assertions like this I don't know if they even make sense for ARC.

CC: @vedantk 

I think this may need a bigger discussion first. Based on our previous conversation my understanding is that you want to be able to generate opt remarks that refer to release/retain instructions and you wanted extract those locations from dbg_values referring to the entity that is being retained/released. But this patch seems to do something entirely different, so I'm a bit confused. Why are you not doing that? A retain/release intentionally has an artificial (line 0) location because it doesn't refer to any source code the developer wrote. Changing that needs design first.

**Comment by gottesmm** [comment]
@adrian-prantl and I sat down via video chat and talked about this.

His concerns were that by not using auto generated locations, we get weird behavior with profile and (potentially) with stepping. We really would need to modify debug info or add a new SILLocation kind to do this correctly. As a straw man (noting Adrian and I didn't talk about what I am about to say in this sentence), we want something along the lines of a SILLocation that has SourceLoc info at the SIL level but for which we still emit 0 into the line table.

Instead he suggested that rather than hold this up on those discussions, we instead in opt-remark find a way of inferring the right line location to use via the surrounding code. I think as a first approximation this will work and later we can make it more accurate if we need to.

**Comment by atrick** [comment]
It's pretty clear there are two distinct source locations, one for diagnostics and one for debugging. We seem to keep flipping back and forth between what the SIL location means rather than modeling it correctly. I would expect clang to have the same problem but haven't researched how others are handling it. When I solved this problem in a past life, I gave each IR stage had its own location ID that all mapped back to the previous stage, so you could track progress through the compiler and diagnose issues at any level.

**Comment by gottesmm** [comment]
I am going to do this differently.

**Pull request closed without merging**
