### PR TITLE
Make our singletons explode if overreleased

### PR DESCRIPTION
**Pull request by Catfish-Man**

### CODE REVIEW

**Comment by Catfish-Man** [comment]
@swift-ci please benchmark

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Review by lorentey — APPROVED** [review]
💯💯💯

I remember tearing my hair out on at least one nonsensical crash that would've been made crystal clear by this.

**Comment by Catfish-Man** [comment]
We went with making them immortal instead

**Pull request closed without merging**
