### PR TITLE
[Backtracing] Add an indication that we're working on a backtrace.

### PR DESCRIPTION
**Pull request by al45tair**
When we crash, emit a message straight away that says we're working on a backtrace.  If starting the backtracer fails, report that also.

Finally, add a duration to the messages output by the backtracer, so that we can see how long it took.

rdar://118055527

### CODE REVIEW

**Comment by al45tair** [comment]
**Explanation**: Generating backtraces can take a significant amount of time, particularly for statically linked binaries on Linux, because it involves scanning through _all_ of the debug information, which means parsing DWARF data, which is just slow. This is particularly problematic in Kubernetes, because pods often have health check timeouts set such that Kubernetes will kill the pod if it doesn't respond within a certain time; if a container crashes, it won't be responding to the health checks, and if the backtrace takes longer than the timeout, it'll be killed before it completes. Previously we output the entire backtrace at the end, so in that case you'd get no useful information about the crash. This PR changes things so that (a) we output the crash location itself straight-away along with a message indicating that we're backtracing, and (b) we say at the end how long it took, to give people something they can use to tell if their timeouts are close to the time it'll take to generate a trace.
**Original PR**: 69697
**Reviewed by**: @mikeash
**Resolves**: rdar://118055527
**Tests**: Adds new tests for the two new messages.

**Comment by al45tair** [comment]
@swift-ci Please test

**Review by tomerd — APPROVED** [review]

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
@swift-ci Please test

**Pull request merged**
