### PR TITLE
[stdlib] De-gyb Sort

### PR DESCRIPTION
**Pull request by airspeedswift**
Taking another run at this. Should improve stdlib code size, so long as it doesn't hurt the benchmarks.

Also moves the `sort`/`sorted` definitions on the protocols over to live with the sort implementation itself.

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
@swift-ci please smoke test compiler performance

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
Helps if you commit the CMake change.

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
@swift-ci please smoke test compiler performance

**Comment by airspeedswift** [comment]
@swift-ci please benchmark

**Comment by jrose-apple** [comment]
…Um. Is this worth the regression? NibbleSort and PhoneBook are both actual sorting tests, no?

**Comment by airspeedswift** [comment]
NibbleSort is kind of a pathological case, but we do care about PhoneBook. But it's easier to debug why the hand-specialization is needed after landing on master. We can revert if it can't be figured out in time for 5.0. I raised https://bugs.swift.org/browse/SR-8267 to track that.

**Comment by airspeedswift** [comment]
Also, note this isn't just for the sake of de-gybbing, this was code bloat in the std lib (two near-identical copies of multiple functions)

**Pull request merged**
