### PR TITLE
[Parser] Support 'any' type in SwiftSyntax

### PR DESCRIPTION
**Pull request by ahoppen**
Previously, SwiftSyntax wasn’t able to parse 'any' types. Add support for them now.

@hborla Is there a more generic name for the 'some' or 'any' types? I went with `SomeOrAnyType` for now but if there’s a better name, I’d like to change it.

rdar://90077430

### CODE REVIEW

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/369

@swift-ci Please smoke test

**Comment by hborla** [comment]
> Is there a more generic name for the 'some' or 'any' types? I went with SomeOrAnyType for now but if there’s a better name, I’d like to change it.

There isn't one anywhere in the code base yet, but we could invent one. Maybe something like `ConstrainedSugarType`?

**Review by ktoso — APPROVED** [review]
Thanks a lot for the fix, this unblocks some of our code which wanted to use the proper `any Something` :)

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/369

@swift-ci Please smoke test

**Comment by ahoppen** [comment]
> There isn't one anywhere in the code base yet, but we could invent one. Maybe something like `ConstrainedSugarType`?

Lacking any better ideas, I adopted the name.

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/369

@swift-ci Please smoke test

**Pull request merged**
