### PR TITLE
stdlib: Speed up UTF8View -> Array conversion by using _copyContents

### PR DESCRIPTION
**Pull request by eeckstein**

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by eeckstein** [comment]
@swift-ci smoke benchmark

**Review by milseman — APPROVED** [review]
This is ok as is. I would actually try to just convert it to taking an `UnsafeBufferPointer`, as it's internal and all calls to this are passing something that is contiguously stored.

I've seen the excess overhead of `_copyContents` forming the un-used iterator, extra branches at the top, etc., contribute to inlining heuristics and runtime perf.

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by milseman** [comment]
@swift-ci please smoke benchmark

**Comment by milseman** [comment]
@swift-ci please smoke test compiler performance

**Comment by milseman** [comment]
@eeckstein were these the numbers you were expecting? What gains were we hoping for?

**Comment by eeckstein** [comment]
Yes, that's what I expected

**Pull request merged**
