### PR TITLE
[stdlib] Fix some Clock issues

### PR DESCRIPTION
**Pull request by lorentey**
- Standard clocks: Fix `.now` and `.minimumResolution` implementations. These used to set the clock id incorrectly, leading to zero results. Fix that and also make the underlying entry point abort if it gets an invalid ID, preventing this from reoccurring.
- `Duration`: add a (non-public) initializer that takes low/high components. Having a direct initializer in the ABI is critically important — otherwise we wouldn’t be able to add back deployable conversion initializers in the future (without going through unnecessary overhead).
- `Int128`: Fix `Words`. `Words.Iterator.next()` used to call `Int128(truncatingIfNeeded:)`, which in turn iterates over words, leading to an infinite recursion. 
- `Int128`: Implement half-width multiplication from scratch instead of masking off the full width results.

### CODE REVIEW

**Comment by lorentey** [comment]
These fixes are enough to have the benchmark suite adopt these APIs; however, that we may not be able to land without adding additional code to backport these APIs to earlier releases.

Another issue we will need to fix is the lack of regression test cases for these APIs.

**Comment by lorentey** [comment]
@swift-ci test

**Comment by phausler** [comment]
I am still working on regression tests and such for those types. Hopefully will have something ready next week. 

Overall the changes look reasonable to me.

**Comment by lorentey** [comment]
@swift-ci test

**Pull request merged**
