### PR TITLE
[AutoDiff] Change `TangentVector` memberwise initializer access level.

### PR DESCRIPTION
**Pull request by dan-zheng**
Previously, memberwise initializers of synthesized `TangentVector` structs were
internal by default. Now, they are public by default, improving usability.

Note that public synthesized memberwise initializers have no precedent in
Swift. For normal public structs, it's possible to manually define a public
memberwise initializer, skipping synthesis. However, since `TangentVector`
structs are always synthesized with a memberwise initializer, manually defining
a public memberwise initializer in an extension leads to a redeclaration error.

A broader discussion on memberwise initializer access levels may be
worthwhile.

Resolves TF-1077.
Note that public synthesized memberwise initializers have no precedent in
Swift. For normal public structs, it's possible to manually define a public
memberwise initializer, skipping synthesis. However, since `TangentVector`
structs are always synthesized with a memberwise initializer, manually defining
a public memberwise initializer in an extension leads to a redeclaration error:

```console
$ cat foo.swift
public struct Foo: Differentiable {}
extension Foo.TangentVector {
  public init() {}
}

$ swift foo.swift
foo.swift:3:10: error: invalid redeclaration of synthesized memberwise 'init()'
  public init() {}
         ^
```

A broader discussion on memberwise initializer access levels may be
worthwhile.

Resolves TF-1077. Unblocks a [concrete use case](https://github.com/tensorflow/swift-models/pull/231#discussion_r360560878): cc @eaplatanios.

### CODE REVIEW

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Review by rxwei — APPROVED** [review]

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow linux

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by porterchild** [comment]
Is this still in effect? I'm currently getting a 
```
'MyType.TangentVector' initializer is inaccessible due to 'internal' protection level
```
compiler error, and I get the 
```
invalid redeclaration of synthesized memberwise 'init()'
```
error if I try to make a public init in an extension. (using 0.11 Release)

**Pull request merged**
