### PR TITLE
[silgen] Change silgen pattern to use destructure_tuple instead of bo…

### PR DESCRIPTION
**Pull request by gottesmm**
…rrow + tuple_extract + copy.

rdar://29791263

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Review by slavapestov — APPROVED** [review]
No existing tests exercise switch with ownership?

**Comment by gottesmm** [comment]
@slavapestov this code is only conditionally enabled on sil ownership being enabled. Since SILGenPattern is not completely able to work with ownership yet the current switch tests do not run with ownership enabled... so yes.

**Review by rjmccall — COMMENTED** [review]
LGTM.

**Pull request merged**
