### PR TITLE
Fix CLion getting started, swift-syntax is also required now

### PR DESCRIPTION
**Pull request by ktoso**
Also include the swift-syntax path, otherwise CMake import in CLion will fail.

### CODE REVIEW

**Review by egorzhdan — APPROVED** [review]
LGTM!
I wonder if the CMake scripts could assume that the dependency projects are located in the same directory as Swift itself by default, that would make it more convenient for people to build Swift with CMake directly.

**Comment by ktoso** [comment]
Yeah that sounds like a safe thing to assume tbh. I'll do a follow up ticket for it

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
Follow up here: https://github.com/apple/swift/issues/62291

**Comment by ktoso** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
