### PR TITLE
[AutoDiff] Propagate `@frozen` and `@usableFromInline` to `TangentVector` struct.

### PR DESCRIPTION
**Pull request by dan-zheng**
During `Differentiable` derived conformances, propagate `@frozen` and `@usableFromInline` from conforming types to synthesized `TangentVector` structs.

### CODE REVIEW

**Comment by rxwei** [comment]
Also `@usableFromInline`  :)

**Comment by dan-zheng** [comment]
> Also `@usableFromInline` :)

Done!

**Review by rxwei — APPROVED** [review]
Thanks!

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci TensorFlow commands appear broken. I've just emailed @shahmishal asking for help.
Locally verified that tests pass via `ninja check-swift`. Merging.

**Pull request merged**
