### PR TITLE
[AddressLowering] Handle builtins for resumes.

### PR DESCRIPTION
**Pull request by nate-chandler**
The builtins for resuming UnsafeContinuations traffic in generic values and must be rewritten to use addresses instead of values.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by meg-gupta — APPROVED** [review]
LGTM

**Review by atrick — APPROVED** [review]

**Comment by nate-chandler** [comment]
@swift-ci please clean test macOS platform

**Pull request merged**
