### PR TITLE
[IRGen] Report error in reading legacy layouts non-fatally.

### PR DESCRIPTION
**Pull request by DougGregor**
Taking down the compiler for this is wholly unnecessary.
Part of rdar://71439646.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test Windows

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by DougGregor** [comment]
@swift-ci please smoke test Linux

**Pull request merged**
