### PR TITLE
[Dependency Scanning] Include initial PCM arguments on Clang module dependency details

### PR DESCRIPTION
**Pull request by artemcm**
Doing so will allow clients to know which Swift-specific PCM arguments are already captured from the scan that first discovered this module.
SwiftDriver, in particular, will be able to use this information to avoid batch re-scanning a given Clang module if the initial scan was sufficient for all possible sets of PCM arguments on Swift modules that depend on said Clang module.

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
Corresponding driver PR that queries the newly-added `libSwiftScan` entry-points in order to avoid redundant batch re-scanning:
https://github.com/apple/swift-driver/pull/848

**Comment by artemcm** [comment]
@swift-ci please test Windows platform

**Comment by artemcm** [comment]
@swift-ci please test Windows platform

**Review by nkcsgexi — APPROVED** [review]
Thanks!

**Comment by artemcm** [comment]
@swift-ci please test Windows platform

**Pull request merged**
