### PR TITLE
Add a benchmark for bridging date components

### PR DESCRIPTION
**Pull request by Catfish-Man**
Turns out this is slower than hoped-for, so let's get a test keeping an eye on it

### CODE REVIEW

**Comment by Catfish-Man** [comment]
@swift-ci please benchmark

**Review by itaiferber — APPROVED** [review]

**Comment by Catfish-Man** [comment]
@swift-ci please smoke test and merge

**Comment by Catfish-Man** [comment]
@swift-ci please smoke test and merge

**Comment by Catfish-Man** [comment]
It's failing trying to merge the PR, somehow

**Pull request merged**
