### PR TITLE
[TF] Fix precedencegroup and operator decl lookup

### PR DESCRIPTION
**Pull request by dan-zheng**
Cherry-pick of https://github.com/apple/swift/commit/cc062ee2bb96c4624dc787e394f021f5258ae804 to `tensorflow` branch.

---

https://github.com/apple/swift/commit/cc062ee2bb96c4624dc787e394f021f5258ae804 added `include/swift/AST/OperatorNameLookup.h`.

For some reason, this file exists on `master` branch but not `tensorflow` branch, even though the commit was merged into `tensorflow` branch. Very weird.

This should fix CI error: https://dev.azure.com/compnerd/3133d6ab-80a8-4996-ac4f-03df25cd3224/_apis/build/builds/32388/logs/32
```
2020-05-28T01:27:02.3539750Z /Users/runner/runners/2.168.2/work/1/s/toolchain/lldb/source/Symbol/SwiftASTContext.cpp:34:10: fatal error: 'swift/AST/OperatorNameLookup.h' file not found
2020-05-28T01:27:02.3540970Z #include "swift/AST/OperatorNameLookup.h"
2020-05-28T01:27:02.3541930Z          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-05-28T01:27:02.3542850Z 4 warnings and 1 error generated.
```

### CODE REVIEW

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Review by compnerd — APPROVED** [review]
Thanks for tracking this down!

**Comment by dan-zheng** [comment]
CI failed:

<details>
/home/swiftci/jenkins/workspace/swift-PR-TensorFlow-Linux/swift/lib/AST/OperatorNameLookup.cpp:48:45: error: no member named 'EnableNewOperatorLookup' in 'swift::LangOptions'
    if (results.size() <= 1 || ctx.LangOpts.EnableNewOperatorLookup) {
                               ~~~~~~~~~~~~ ^
/home/swiftci/jenkins/workspace/swift-PR-TensorFlow-Linux/swift/lib/AST/OperatorNameLookup.cpp:49:7: error: no matching function for call to 'removeShadowedDecls'
      removeShadowedDecls(results, moduleDC);
      ^~~~~~~~~~~~~~~~~~~
/home/swiftci/jenkins/workspace/swift-PR-TensorFlow-Linux/swift/lib/AST/OperatorNameLookup.cpp:114:10: note: in instantiation of function template specialization 'lookupOperatorImpl<swift::OperatorDecl>' requested here
  return lookupOperatorImpl<OperatorDecl>(
         ^
/home/swiftci/jenkins/workspace/swift-PR-TensorFlow-Linux/swift/include/swift/AST/NameLookup.h:455:6: note: candidate function not viable: no known conversion from 'TinyPtrVector<swift::OperatorDecl *>' to 'SmallVectorImpl<swift::ValueDecl *> &' for 1st argument
bool removeShadowedDecls(SmallVectorImpl<ValueDecl*> &decls,
     ^
/home/swiftci/jenkins/workspace/swift-PR-TensorFlow-Linux/swift/lib/AST/OperatorNameLookup.cpp:49:7: error: no matching function for call to 'removeShadowedDecls'
      removeShadowedDecls(results, moduleDC);
      ^~~~~~~~~~~~~~~~~~~
/home/swiftci/jenkins/workspace/swift-PR-TensorFlow-Linux/swift/lib/AST/OperatorNameLookup.cpp:224:10: note: in instantiation of function template specialization 'lookupOperatorImpl<swift::PrecedenceGroupDecl>' requested here
  return lookupOperatorImpl<PrecedenceGroupDecl>(
         ^
/home/swiftci/jenkins/workspace/swift-PR-TensorFlow-Linux/swift/include/swift/AST/NameLookup.h:455:6: note: candidate function not viable: no known conversion from 'TinyPtrVector<swift::PrecedenceGroupDecl *>' to 'SmallVectorImpl<swift::ValueDecl *> &' for 1st argument
bool removeShadowedDecls(SmallVectorImpl<ValueDecl*> &decls,
     ^
</details>

It seems cherry-picking https://github.com/apple/swift/commit/cc062ee2bb96c4624dc787e394f021f5258ae804 to get `include/swift/AST/OperatorNameLookup.h` on `tensorflow` branch is not sufficient. I'll look further.

**Comment by dan-zheng** [comment]
I was wrong: `git log` for `tensorflow` branch doesn't contain https://github.com/apple/swift/commit/cc062ee2bb96c4624dc787e394f021f5258ae804!

So it's expected that `include/swift/AST/OperatorNameLookup.h` doesn't exist on `tensorflow` branch.

---

That leaves the [Azure build failure](https://dev.azure.com/compnerd/3133d6ab-80a8-4996-ac4f-03df25cd3224/_apis/build/builds/32388/logs/32) unexplained.

The next `tensorflow-merge -> tensorflow` merge (https://github.com/apple/swift/pull/32077) adds the `include/swift/AST/OperatorNameLookup.h` file, so perhaps that will fix the Azure build failure.

**Pull request closed without merging**
