### PR TITLE
[build-script] Support for Android aarch64

### PR DESCRIPTION
**Pull request by drodriguez**
Support for Android aarch64 in many parts of the build-script. Most of
the changes are reuse variables/parameters that already existed for
Android ARMv7. There is also a new parameter to specify the ICU
data library, which is used by #19503.

With this one can build either armv7 or aarch64, since building both
at the same time requires more changes like #19432 (and probably
more work to support two set of paths).

### CODE REVIEW

**Review by compnerd — APPROVED** [review]
LGTM

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by drodriguez** [comment]
Doesn’t look like I should have affected `DebugInfo/local-vars.swift.gyb` and #20195 looks like it disables that test.

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Pull request merged**
