### PR TITLE
Fix spelling: an -> and

### PR DESCRIPTION
**Pull request by ludwwwig**
Fix spelling: an -> and
in file: utils/dev-scripts/split-cmdline

### CODE REVIEW

**Comment by Azoy** [comment]
Thanks!
@swift-ci please smoke test

**Comment by ludwwwig** [comment]
@Azoy I updated my local branch with updates from apple:main, which seems to require the tests to be run again. Would you be able to help me perform the smoke tests again? Thanks!

**Comment by ludwwwig** [comment]
@swift-ci please smoke test

**Comment by AnthonyLatsis** [comment]
@ludwwwig Before we relaunch the tests, could you do a rebase over `main` instead of the three-way merge? This way we avoid polluting the history with unnecessary merge commits. I also encourage you to use the imperative mood in commit messages, e.g., "fix something" vs. "fixed something"—we conventionally phrase commits as actions.

**Comment by ludwwwig** [comment]
@AnthonyLatsis Thanks for your guidance on writing commit messages. Are you able to see if I have rebased successfully? I wasn't able to figure out how to change my commit message.

**Comment by AnthonyLatsis** [comment]
You can hard-reset to your first commit, `git reset --hard your_commit_sha`, then `git rebase main`.

**Comment by ludwwwig** [comment]
@AnthonyLatsis Does it look good now? Took me some time to figure it all out.

**Comment by AnthonyLatsis** [comment]
You beat me to it, nice! Thanks too!

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Comment by ludwwwig** [comment]
@AnthonyLatsis Awesome! At first I didn't realize that I could reset the merges I did on Github by simply calling git reset --hard... Anyways, thanks for the help!

**Pull request merged**
