### PR TITLE
[WIP] [NO-MERGE] Make "unique" flag more robust and update access enforcement opts to make use of it. 

### PR DESCRIPTION
**Pull request by zoecarver**
This is a WIP PR to get a benchmark of the performance improvements of access enforcement opts when it promotes uniquely identified storage accesses to statically enforced accesses. 

I'm not sure to what degree `AccessedStorage::isUniquelyIdentified` is used throughout the optimizer. I wouldn't be supprised if this PR doesn't have any meaningful performance gains. I think another pass that just updated accesses of "unique" references might be much more beneficial (performance-wise). We'll see. 

Later, I'll clean up these individual commits and break each one into its own PR. The tests do not currently pass, this PR is just for benchmarking. 

Refs (and based on) #32844. [Related forum post](https://forums.swift.org/t/adding-a-unique-flag-to-alloc-ref/38398).

### CODE REVIEW

**Comment by zoecarver** [comment]
@swift-ci please benchmark.

**Comment by zoecarver** [comment]
@swift-ci please benchmark.

**Comment by zoecarver** [comment]
@swift-ci please benchmark

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
