### PR TITLE
Divide the SIL concepts of values and instructions

### PR DESCRIPTION
**Pull request by rjmccall**
This is in preparation for multi-valued instructions.

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please test and merge.

**Comment by eeckstein** [comment]
A small patch :-)
LGTM!

**Comment by rjmccall** [comment]
@swift-ci Please test and merge.

**Comment by rjmccall** [comment]
@swift-ci Please test

**Comment by rjmccall** [comment]
@swift-ci Please test and merge.

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Comment by rjmccall** [comment]
@swift-ci Please test Linux

**Comment by rjmccall** [comment]
Looks like ubuntu-16.04-04 is maybe messed up.

**Comment by rjmccall** [comment]
Okay, it passed the OS build.  Resolved the merge and trying a smoke test.

**Comment by rjmccall** [comment]
@swift-ci Please smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci Please smoke test and merge

**Comment by rjmccall** [comment]
Rebased again, bumped the module version out of an abundance of caution.

**Comment by rjmccall** [comment]
@swift-ci Please smoke test and merge

**Comment by gottesmm** [comment]
@rjmccall after a force push, due to a bug in the jenkins, you need to write the comment twice.

**Comment by rjmccall** [comment]
@gottesmm Ah, interesting, thanks.

**Comment by gottesmm** [comment]
No worries. I got you = ).

**Comment by rjmccall** [comment]
Thanks for shepharding. :)

**Comment by gottesmm** [comment]
Woot!

**Pull request merged**
