### PR TITLE
Implement rethrowing from variadic and array arguments.

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
For example, this allows `func foo(args: () throws -> Void...) rethrows`.

Previously, the compiler ignored `Array`s that are bound to throwing function types when verifying `rethrows`.

I'm not sure how reasonable it would be to expand this for dictionaries or arbitrary generic types, but an array of throwing predicates is quite a sensible use case.

### CODE REVIEW

**Comment by AnthonyLatsis** [comment]
cc @DougGregor

**Comment by AnthonyLatsis** [comment]
@jrose-apple, have a couple of minutes to check this out?

**Comment by jrose-apple** [comment]
I don't think this actually works. You don't have any call site tests.

**Comment by jrose-apple** [comment]
Also, this at least needs a sign-off from a core team member that this doesn't need to go through evolution.

**Comment by AnthonyLatsis** [comment]
> I don't think this actually works. You don't have any call site tests.

You've got a point, I'll take a look and add them if it does.

> Also, this at least needs a sign-off from a core team member that this doesn't need to go through 
> evolution.

Ok, thank you. I didn't expect it could be that big of a change since we already support standalone throwing closures.

**Comment by jrose-apple** [comment]
Sorry, I just realized how negative I was being. This is cool stuff! But I think the hard part is getting the call site to work, and there's also a language complexity issue about where we want to draw the line for `rethrows`.

**Comment by AnthonyLatsis** [comment]
No worries, it didn't come across that way :)
> and there's also a language complexity issue about where we want to draw the line for `rethrows`.
This likely correlates to what I wrote about supporting all kinds of generic cases; I barely use any throwing in my own Swift code, but the question of why `rethrows` couldn't just be `throws` did occur to a couple times.

**Comment by AnthonyLatsis** [comment]
@jrose-apple Now I see what you meant. It's probably impossible to always statically deduce whether we are dealing with a call to a throwing function from the given array. It could be done through anything: a loop, a known subscript, method or property like `first`, you name it..
Would it be OK if I narrow this down to `Array.subscript` and, maybe, loops?

**Comment by jrose-apple** [comment]
:-( I didn't even think about what was inside the function; I was just worried about the call site. Yeah, I don't know if I can get onboard with this without having a good understand of what does and doesn't count.

**Comment by AnthonyLatsis** [comment]
This patch allows rethrowing variadics and `Array` elements through `Array.subscript(index:)`. It also fixes a couple bugs.

An apparent improvement would be to expand the set of supported builtin `Array` methods through some `returnsValidArrayElement` function that iterates over known methods or simply by checking whether *this* is a method on `Array` that resides in the stdlib and returns `Element`. Regarding the latter, `-> Element` is of course not a guarantee of getting an existing stored `Element`, but hopefully the Standard Library is reliable enough to consider this a safe approach.

@DougGregor, I would be glad to know your opinion on this addition. Do you think this should go through evolution?

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by AnthonyLatsis** [comment]
Will not be revisiting this anytime soon, so closing this for now.

**Pull request closed without merging**
