### PR TITLE
[stdlib]hashing benchmarks for String

### PR DESCRIPTION
**Pull request by lancep**
We have some good test data for String comparison benchmarks. Why not re-use it for hashing as well?

### CODE REVIEW

**Comment by lancep** [comment]
@swift-ci please smoke benchmark

**Comment by lancep** [comment]
@swift-ci please test

**Comment by lancep** [comment]
@swift-ci please test linux platform

**Review by stephentyrone — COMMENTED** [review]
Good stuff, thanks for adding this!

**Pull request merged**
