### PR TITLE
[5.9][CodeCompletion] Fix a crash when completing an argument to a function taking a parameter pack

### PR DESCRIPTION
**Pull request by ahoppen**
* **Explanation**: We previously asserted that for a call the function type had the same number of parameters as the declaration. But that’s not true for parameter packs anymore because the parameter pack will be exploded in the function type to account for passing multiple arguments to the pack.
To fix this, use `ConcreteDeclRef` instead of a `ValueDecl`, which has a substitution map and is able to account for the exploded parameter packs when accessed using `getParameterAt`.
* **Scope**: Code completion of arguments
* **Risk**: 2/5
* **Testing**: Added regression test
* **Issue**: rdar://100066716
* **Reviewer**: @xedin and @rintaro on https://github.com/apple/swift/pull/65720

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test macOS

**Review by airspeedswift — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Linux

**Pull request merged**
