### PR TITLE
[build-toolchain] Add support for specifying a preset file.

### PR DESCRIPTION
**Pull request by gottesmm**

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci build toolchain

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Review by shahmishal — APPROVED** [review]
thanks!

**Comment by gottesmm** [comment]
Going to add some more stuff to this. Going to add support for adding multiple custom preset files and also customizing the invoked preset from the cmdline.

**Comment by gottesmm** [comment]
@swift-ci build-toolchain

**Comment by gottesmm** [comment]
@swift-ci build-toolchain

**Comment by gottesmm** [comment]
@swift-ci build-toolchain

**Comment by gottesmm** [comment]
@swift-ci build-toolchain

**Comment by gottesmm** [comment]
@swift-ci build-toolchain

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci build toolchain

**Comment by gottesmm** [comment]
@swift-ci test windows platform

**Pull request merged**
