### PR TITLE
revert hack for building overlays with missing frameworks in public SDKs

### PR DESCRIPTION
**Pull request by bob-wilson**
Several years ago we had problems building the overlays from bitcode because of inconsistencies between internal and public SDKs. In the process, Doug added a -disable-autolink-framework option and CMake support for per-SDK build options. We ended up using a different solution for those problems so the Swift changes are not needed.
rdar://problem/21490972

### CODE REVIEW

**Comment by bob-wilson** [comment]
@swift-ci please test

**Comment by bob-wilson** [comment]
The Linux build timed out. Let's try again.

@swift-ci please test linux platform

**Comment by bob-wilson** [comment]
I just discovered that Xcode is using this option, so we can't merge this yet.

**Review by DougGregor — APPROVED** [review]
I suggest splitting out the overlay-building and CMake changes (which can be merged now) from the command-line option itself (which might need to live a little longer for Xcode's sake).

**Comment by CodaFi** [comment]
This hack is still in Xcode and has spread to other frameworks. We should probably disable it compiler-side first and then ask them to delete whatever this is working around.

Closing this out.

**Pull request closed without merging**
