### PR TITLE
[Diagnostics] Add a basic terminal markdown printer for educational notes

### PR DESCRIPTION
**Pull request by owenv**
Currently the printer only supports the subset of markdown used by educational notes. It bolds headers, improves the appearance of lists and horizontal rules, and does basic indenting of block quotes and code blocks.

### CODE REVIEW

**Comment by owenv** [comment]
I'm not sure who has the most context to review markup library changes these days, it looks like it hasn't changed much in the past few years. If anyone could recommend a reviewer I'd appreciate it!

**Comment by owenv** [comment]
Hi @nkcsgexi , I looked in the code-owners file and saw that you're the swiftMarkup owner. Do you mind taking a look at this PR or recommending a reviewer?

**Comment by owenv** [comment]
@swift-ci please test

**Comment by owenv** [comment]
@swift-ci please test windows platform

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by owenv** [comment]
@nkcsgexi friendly ping

**Comment by owenv** [comment]
@swift-ci please test Windows platform

**Comment by owenv** [comment]
@swift-ci please test Windows platform

**Comment by owenv** [comment]
Windows run passed: https://ci-external.swift.org/view/Pull%20Request/job/swift-PR-windows/580/console

@swift-ci please smoke test

**Comment by owenv** [comment]
@swift-ci please smoke test Linux

**Comment by owenv** [comment]
@nkcsgexi bump, do you mind looking over these markup changes or recommending a reviewer?

**Comment by nkcsgexi** [comment]
@nathawes could you review this PR please?

**Review by nathawes — APPROVED** [review]
Looks good to me! Thanks @owenv and sorry for the delay in reviewing.

**Comment by owenv** [comment]
@nathawes No problem, thanks for the review!

**Comment by owenv** [comment]
@swift-ci smoke test and merge

**Comment by owenv** [comment]
@swift-ci smoke test and merge

**Comment by owenv** [comment]
@swift-ci smoke test and merge

**Pull request merged**
