### PR TITLE
corrected implementation of parsing nonisolated(unsafe) as decl contextual keyword in top-level global scope

### PR DESCRIPTION
**Pull request by sophiapoirier**
follow up to https://github.com/apple/swift/pull/69624

### CODE REVIEW

**Comment by sophiapoirier** [comment]
@swift-ci please test

**Comment by sophiapoirier** [comment]
@swift-ci please test

**Review by ahoppen — APPROVED** [review]
Could you also add a test case?

**Comment by sophiapoirier** [comment]
> Could you also add a test case?

@ahoppen there already are a couple of test cases:
https://github.com/apple/swift/blob/44e1e54e1391f988b566477dca9a8456bc84dcbc/test/Concurrency/experimental_feature_strictconcurrency.swift#L48
https://github.com/apple/swift/blob/44e1e54e1391f988b566477dca9a8456bc84dcbc/test/Concurrency/experimental_feature_strictconcurrency.swift#L61
This PR is not really new functionality, but a more correct implementation of the functionality added in https://github.com/apple/swift/pull/69624 which was done in a somewhat hacky manner to unblock a language proposal review.

**Comment by ahoppen** [comment]
Oh, I see. This is just removing the original hack in favor of something better. 👍🏽

**Pull request merged**
