### PR TITLE
[test] Stop a test relying on inconsistent formatting of an error message.

### PR DESCRIPTION
**Pull request by huonw**
Fixes rdar://problem/42351773.

### CODE REVIEW

**Comment by huonw** [comment]
@swift-ci please smoke test and merge

**Comment by jrose-apple** [comment]
You could use `expected-error {{}}` if you didn't want to change the test. Or just drop `-verify` altogether and use `not`.

**Comment by huonw** [comment]
I want to be specifically testing that the `T` type is the expected one inside the `extension`, and the error message was the first way I thought of doing that, but just writing the type seems better.

**Comment by huonw** [comment]
@swift-ci please smoke test Linux

**Pull request merged**
