### PR TITLE
[const-expr] Teach ConstExpr how to handle switch_enum/unchecked_enum…

### PR DESCRIPTION
**Pull request by gottesmm**
…_data in ossa.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by ravikandhadai** [comment]
LGTM.

**Review by ravikandhadai — APPROVED** [review]

**Comment by gottesmm** [comment]
@shahmishal the linux test failed due to I believe a change from the stable merge (or not cleaning). Are the bots cleaned?

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by shahmishal** [comment]
I triggered a clean build job, but you can request a clean build from PR testing too.

**Comment by gottesmm** [comment]
@shahmishal happened again

**Comment by gottesmm** [comment]
@swift-ci clean smoke test

**Review by marcrasi — APPROVED** [review]

**Pull request merged**
