### PR TITLE
[AddressLowering] Handle try_apply with enum'd return.

### PR DESCRIPTION
**Pull request by nate-chandler**
When a block argument is a terminator result from a `try_apply`, use the ApplyRewriter to convert the `try_apply`.

In the case where the result is stored into an enum, with this change, the `init_enum_data_addr` instruction is created prior to the `try_apply`, which is necessary in order for it to be passed as an argument to the `try_apply`.

Based on https://github.com/apple/swift/pull/61950 .

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by atrick — APPROVED** [review]
LGTM

**Comment by nate-chandler** [comment]
Something went wrong here.  The PR was merged at https://github.com/apple/swift/commit/b2e34b2ba06ae738904ad18a94cd4532482c1b6a , but remained open in GitHub's UI.  Rebasing and pushing a branch without commits resulted in closing and automatically requesting review.  Sorry for the noise!

**Pull request closed without merging**
