### PR TITLE
update_checkout: re-read config for cross-repo testing

### PR DESCRIPTION
**Pull request by MaxDesiatov**
When updating versions of some dependencies, it's important to be able to re-read the checkout config to get the new versions to actually check them out. This not working prevents us from making CI green in cross-repo PRs that update these dependencies.

I also used this as an opportunity to refactor out some common code and add Python docstrings to some functions for easier maintenance.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Review by shahmishal — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Pull request merged**
