### PR TITLE
Fix reading elf section from file buffer

### PR DESCRIPTION
**Pull request by augusto2112**
This pr fixes a bug where reading elf sections from the file buffer would read less data than intended.

@adrian-prantl

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci smoke test

**Comment by shahmishal** [comment]
@swift-ci smoke test

**Comment by shahmishal** [comment]
@swift-ci smoke test macOS

**Comment by shahmishal** [comment]
@swift-ci smoke test Linux

**Comment by augusto2112** [comment]
@adrian-prantl all checks passed, but I double-checked the code and there was still a possible bug there, so I had to push again.

**Comment by adrian-prantl** [comment]
@swift-ci smoke test

**Comment by augusto2112** [comment]
@adrian-prantl Some other PRs seem to have the tests running now. Could you try restarting the tests here one more time please?

**Comment by augusto2112** [comment]
Actually, looks like the linux build just started.

**Pull request merged**
