### PR TITLE
pcm-emit-direct-cc1-mode.swift also fails on Android

### PR DESCRIPTION
**Pull request by ian-twilightcoder**
Extend the recently added XFAIL to Android.

### CODE REVIEW

**Comment by ian-twilightcoder** [comment]
@swift-ci smoke test

**Comment by ian-twilightcoder** [comment]
@swift-ci test

**Comment by ian-twilightcoder** [comment]
@swift-ci test

**Comment by ian-twilightcoder** [comment]
@swift-ci test Windows

**Review by finagolfin — APPROVED** [review]
@bnbarham, please review and merge.

**Comment by finagolfin** [comment]
Yep, this test is bypassed on the Android CI now.

**Pull request merged**
