### PR TITLE
test: make StdlibUnittest.CrashingTests pass on Windows

### PR DESCRIPTION
**Pull request by compnerd**
The output can be interleaved differently.  Accept either ordering.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @kubamracek

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
*sigh* lldb again

**Comment by compnerd** [comment]
@swift-ci please smoke test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by drodriguez** [comment]
So I think I have some idea why this one was needed and why is failing again in Azure in another of the test. For all the platforms except Windows, the stdlib unit test framework uses `select` to read from the pipes connected to the `stdout` and `stderr` of the test processes. `select` should maintain the relative order of the messages generated by the test process. However, in Windows, we spin two threads that read from the handles "at the same time", which will not maintain the relative order.

I tried to play a little and enable using `select` also in Windows, but I got into a lot of dead ends. I wonder if there's a better alternative to the two threads in Windows. Something that can maintain the relative order of the events without leaving it to the scheduler.

Adding `DAG` to more cases is not only a nuisance, but also wrong, because output happens before error, but the test is saying that it doesn't matter.

**Pull request merged**
