### PR TITLE
Audit and correct AsyncSequence Sendability

### PR DESCRIPTION
**Pull request by phausler**
This corrects Sendable annotations for the following types (and their iterators and closures):

AsyncCompactMapSequence
AsyncDropFirstSequence
AsyncDropWhileSequence
AsyncFilterSequence
AsyncFlatMapSequence
AsyncMapSequence
AsyncPrefixSequence
AsyncPrefixWhileSequence
AsyncThrowingCompactMapSequence
AsyncThrowingDropWhileSequence
AsyncThrowingFilterSequence
AsyncThrowingMapSequence
AsyncThrowingPrefixWhileSequence

Conditionally, if an AsyncSequence is based on a Sendable AsyncSequence and the produced element is Sendable then that composed AsyncSequence should be Sendable. Same applies to the iterator.

### CODE REVIEW

**Comment by phausler** [comment]
@swift-ci please smoke test

**Comment by phausler** [comment]
@swift-ci Please Test Source Compatibility

**Comment by phausler** [comment]
@swift-ci please smoke test

**Comment by phausler** [comment]
@swift-ci Please Test Source Compatibility

**Comment by phausler** [comment]
@swift-ci please smoke test

**Comment by phausler** [comment]
@swift-ci please smoke test

**Comment by phausler** [comment]
@swift-ci please smoke test

**Review by ktoso — APPROVED** [review]
Skimming through LGTM, as long as CI gets happy someday

**Comment by phausler** [comment]
@swift-ci please smoke test and merge

**Comment by phausler** [comment]
@swift-ci please smoke test

**Comment by phausler** [comment]
@swift-ci please smoke test macOS

**Review by DougGregor — COMMENTED** [review]
This is awesome. I've noted a few places where you'll need to mark declarations that are ABI as `@preconcurrency` because `@Sendable` alters their type (and therefore mangled name).

**Comment by DougGregor** [comment]
How close does this get us to being `-require-explicit-sendable`-clean?

**Comment by phausler** [comment]
@swift-ci please smoke test

**Comment by phausler** [comment]
@swift-ci please smoke test

**Comment by phausler** [comment]
@swift-ci please smoke test

**Comment by phausler** [comment]
@swift-ci Please Test Source Compatibility and merge

**Comment by phausler** [comment]
@swift-ci Please Test Source Compatibility

**Comment by phausler** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
