### PR TITLE
Attempt to fix IRGen test affected by clang change

### PR DESCRIPTION
**Pull request by benlangmuir**
r325446 added the 'sahf' target feature.

rdar://40333809

### CODE REVIEW

**Comment by benlangmuir** [comment]
@swift-ci please smoke test

**Comment by benlangmuir** [comment]
Hey @aschwaighofer to future proof this, could we make this test more robust to only check for features we care about instead of the exact target-features string?

**Comment by aschwaighofer** [comment]
The comment above says:

>  // Make sure that the target features are ordered. ....

**Comment by benlangmuir** [comment]
We can test the ordering of various features without checking every single one.  If you think it's important to check all of them, I'm okay with leaving it, I just wanted to check since this just broke every single ci bot for master and swift-4.2...

**Comment by benlangmuir** [comment]
The mac failure is unrelated (and should be fixed already).  The linux bot has made it past this test successfully.  I'm merging this without waiting for the rest of the tests to try to fix  CI.

**Pull request merged**
