### PR TITLE
XFAIL decl/protocol/protocols_with_self_or_assoc_reqs_executable.swift

### PR DESCRIPTION
**Pull request by beccadax**
To work around failure seen in https://ci.swift.org/job/oss-swift_tools-RA_stdlib-RDA_test-simulator/4027.

rdar://83066987

### CODE REVIEW

**Comment by beccadax** [comment]
@swift-ci smoke test and merge

**Comment by AnthonyLatsis** [comment]
@beccadax I take it this is an internal issue?

**Comment by beccadax** [comment]
@AnthonyLatsis We saw it in an open-source bot—see the first message. Don't think it's been really investigated yet.

**Comment by AnthonyLatsis** [comment]
Yeah, I already looked at the logs (I coauthored this test recently); was wondering because it simply says "test unexpectedly crashed", not even a stack trace.

**Comment by beccadax** [comment]
The failure in the smoke test was downstream of this project. Merging to make progress unblocking bots.

**Pull request merged**
