### PR TITLE
[Serialization] Recover if an enum's generic requirements are broken

### PR DESCRIPTION
**Pull request by jrose-apple**
Follow-up to #12979 that adds a similar feature for enums. This probably doesn't come up much, but the infrastructure's already there. Also, add some additional tests to cover at least the simple cases for functions, subscripts, and initializers.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test compiler performance

**Comment by jrose-apple** [comment]
@swift-ci Please test macOS

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test compiler performance

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test compiler performance

**Comment by jrose-apple** [comment]
@swift-ci Please test macOS

**Review by slavapestov — APPROVED** [review]
LGTM, but what about classes and structs?

I guess eventually this will break code like

```enum E<T> where T : P, T.X == E<T> {}```

But for now we can't type check that anyway.

**Comment by jrose-apple** [comment]
The "get the list of dependency types" logic already knows to ignore things inside the same module. The bigger problem is that it'll want a type for `E` in order to build the declaration for `E`.

Neither structs nor classes have *any* support for this kind of recovery at the moment—that is, if a stored property in a struct is missing, we'll still deserialize the struct. It's probably worth adding it, but it's not as small a change.

**Comment by jrose-apple** [comment]
@swift-ci Please test macOS

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Pull request merged**
