### PR TITLE
[Test] Fix test cases

### PR DESCRIPTION
**Pull request by rintaro**
#34492 conflicts with #34467

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by davezarzycki** [comment]
@swift-ci Please smoke test

**Comment by davezarzycki** [comment]
Is there an ETA for getting this merged? The main branch seems to be broken right now.

**Comment by davezarzycki** [comment]
Shouldn't we move `validation-test/Sema/type_checker_crashers_fixed/rdar27830834.swift` out of the "fixed" directory? Adding `not` to the test hides the regression.

**Comment by tbkka** [comment]
Force-merging to try to get things sane again.

**Comment by rintaro** [comment]
@davezarzycki This is a crasher test. Since it *successfully* fails, it's still "fixed".
This failure happened because #34492 was merged during https://github.com/apple/swift/pull/34505 was testing.

**Pull request merged**
