### PR TITLE
IUO: Generate Optional<T> rather than ImplicitlyUnwrappedOptional<T>

### PR DESCRIPTION
**Pull request by rudkx**
Stop creating ImplicitlyUnwrappedOptional<T> so that we can remove it
from the type system.

Enable the code that generates disjunctions for Optional<T> and
rewrites expressions based on the original declared type being `T!`.

Most of the changes supporting this were previously merged to master,
but some things were difficult to merge to master without actually
removing IUOs from the type system:
- Dynamic member lookup and dynamic subscripting
- Changes to ensure the bridging peephole still works

Past commits have attempted to retain as much fidelity with how we
were printing things as possible. There are some cases where we still
are not printing things the same way:
- In diagnostics we will print `?` rather than `!`
- Some SourceKit and Code Completion output where we print a Type
  rather than Decl.

Things like module printing via swift-ide-test attempt to print `!`
any place that we now have Optional types that were declared as IUOs.

There are some diagnostics regressions related to the fact that we can
no longer "look through" IUOs. For the same reason some output and
functionality changes in Code Completion. I have an idea of how we can
restore these, and have opened a bug to investigate doing so.

There are some small source compatibility breaks that result from
this change:
- Results of dynamic lookup that are themselves declared IUO can in
  rare circumstances be inferred differently. This shows up in
  `test/ClangImporter/objc_parse.swift`, where we have 
      `var optStr = obj.nsstringProperty`
  Rather than inferring optStr to be `String!?`, we now infer this to
  be `String??`, which is in line with the expectations of SE-0054.
  The fact that we were only inferring the outermost IUO to be an
  Optional in Swift 4 was a result of the incomplete implementation of
  SE-0054 as opposed to a particular design. This should rarely cause
  problems since in the common case of actually using the property rather
  than just assigning it to a value with inferred type, we will behave
  the same way.
- Overloading functions with inout parameters strictly by a difference
  in optionality (i.e. `Optional<T>` vs. `ImplicitlyUnwrappedOptional<T>`)
  will result in an error rather than the diagnostic that was added
  in Swift 4.1.
- Any place where `!` was being used where it wasn't supposed to be
  allowed by SE-0054 will now treat the `!` as if it were `?`.
  Swift 4.1 generates warnings for these saying that putting `!`
  in that location is deprecated. These locations include for example
  typealiases or any place where '!' is nested in another type like
  `Int!?` or `[Int!]`.

This commit effectively means `ImplicitlyUnwrappedOptional<T>` is no
longer part of the type system, although I haven't actually removed
all of the code dealing with it yet.

`ImplicitlyUnwrappedOptional<T>` is is dead, long live implicitly
unwrapped `Optional<T>`!

Resolves rdar://problem/33272674.

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please test

**Comment by rudkx** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
@swift-ci Please test

**Comment by rudkx** [comment]
@swift-ci Please test Linux platform

**Comment by rudkx** [comment]
Please test with following PR:
https://github.com/apple/swift-source-compat-suite/pull/127

@swift-ci Please test source compatibility

**Comment by deepeshwp** [comment]
@rudkx just a suggestion why don't we get rid of IUO and just have optionals ( ? ) in place. To me IUO sounds pretty confusing especially in the examples section of ( https://github.com/apple/swift-evolution/blob/master/proposals/0054-abolish-iuo.md ) where the type changes automatically depending on what operation is performed which is dangerous. Also for dev what would be the good practice just to get rid of all the forced bang operation and use ? optional types. Please can you help.

**Pull request merged**
