### PR TITLE
Support for Open Existentials that do no take an address

### PR DESCRIPTION
**Pull request by shajrawi**
Small part of radar rdar://problem/30080769

Bootstrapping SILGen for opaque values - This PR adds support for open_existential instruction that takes an opaque value + moves the corresponding test-case from the todo file into a completed one.

Worth noting: while support has been added (almost) everywhere, including our utilities, The SIL Optimizer passes have not been changed / asked to make any special considerations for this new instruction.

### CODE REVIEW

**Comment by shajrawi** [comment]
@atrick can you please review?

**Comment by shajrawi** [comment]
@swift-ci Please smoke test

**Comment by gottesmm** [comment]
@shajrawi Quick question. Why not call this open_existential_value? Or some name that distinguishes it from open_existential_ref.

**Comment by gottesmm** [comment]
My fear is that from a naming perspective since open_existential is a prefix of open_existential_ref, readers will be confused about the difference in between the two.

Another idea, open_existential_opaque_value?

**Comment by shajrawi** [comment]
@gottesmm That was @atrick offline suggestion :) I called it open_existential_opaque before. Felt we need a suffix like you do. @atrick Felt we should not add any because all other SIL instructions that take a value do not have a special suffix

**Comment by gottesmm** [comment]
For people listening in, we talked offline about this. My feeling was that if we were going to choose the name open_existential, since it was a prefix of open_existential_ref, that a class should be able to be passed to open_existential. I was under the mistaken assumption that open_existential would only work with opaque values, which was not the case!

**Comment by atrick** [comment]
@gottesmm I'm on the fence now regarding the suffix.

After looking at the patch, I agree this could be called `open_existential_value` because the returned value always has an opaque type--it can't be substituted with a concrete type. I thought the `_opaque` suffix was a little strange just be cause we don't use it anywhere else and won't need it for any other instructions.

But if we do want `open_existential_value` then we would also want `init_existential_value` and `deinit_existential_value` to keep them in the same family, and those could work on any type, not just opaque types.

**Comment by atrick** [comment]
@shajrawi I finished reviewing your patch. It looks great, but I need to completely reverse what I just said about the opcode suffix. What you had originally, `open_existential_opaque` was perfect, but I misunderstood the intent. The suffix here reflects the container's representation. This instruction will only work with `Opaque` containers. (It's got nothing to do with the value's type). e.g. You can't operate on a `ref` container as if it were an `opaque` container.

Also, I need to add the caveat that the new instruction is experimental because I haven't through issues we might hit while lowering it.

**Comment by shajrawi** [comment]
@atrick I updated the PR / renamed it to `open_existential_opaque`

**Comment by shajrawi** [comment]
@swift-ci Please smoke test

**Comment by atrick** [comment]
👍 sorry to make extra work.

**Pull request merged**
