### PR TITLE
[DO NOT MERGE] Namespacing Common Fatal Scenarios/Extending `fatalError`

### PR DESCRIPTION
**Pull request by erica**
Responding to [Namespacing for common Swift error scenarios](https://forums.swift.org/t/introducing-namespacing-for-common-swift-error-scenarios/) with preliminary implementation.

@swift-ci please smoke benchmark

### CODE REVIEW

**Comment by erica** [comment]
@swift-ci Please test

**Comment by erica** [comment]
@swift-ci Please test source compatibility

**Comment by erica** [comment]
@swift-ci Please smoke test

**Comment by erica** [comment]
@swift-ci Please test

**Comment by erica** [comment]
@swift-ci Please benchmark

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
