### PR TITLE
[Parse] Minor fix for parsing SIL BuiltinInst.

### PR DESCRIPTION
**Pull request by dan-zheng**
The expected token in the diagnostic should be `")"`, not `"("`.

Contributed during the [try! Swift San Jose 2018 event](https://www.tryswift.co/events/2018/sanjose/)!

### CODE REVIEW

**Comment by dan-zheng** [comment]
@swift-ci Please smoke test

**Review by jrose-apple — COMMENTED** [review]
Thanks, Dan! Can you add a test case for this under test/SIL/Parser/ ?

**Comment by dan-zheng** [comment]
Sure thing, I'll do so later today.

**Comment by dan-zheng** [comment]
I added a test case in `errors.sil`.
I couldn't add the erroneous `BuiltinInst` to the end of `@local_value_errors` because that disrupted the previous expected error, so I added it to a new function `@local_value_errors2` instead.

**Comment by dan-zheng** [comment]
@swift-ci Please smoke test

**Review by jrose-apple — APPROVED** [review]
LGTM!

**Comment by dan-zheng** [comment]
Thanks @jrose-apple :)

**Pull request merged**
