### PR TITLE
[Sema] Restrict new optional-to-archetype casting behaviour to Swift 5 mode

### PR DESCRIPTION
**Pull request by hamishknight**
In #13910, the behaviour of optional-to-archetype casts changed such that we're now more conservative with the unwrapping of the operand at compile time in order to account for the fact that an optional type could be substituted at runtime. This brought such casting behaviour inline with that in a non-generic context, however it wasn't properly gated by Swift version, leading to compatibility issues.

This PR restricts the new behaviour to Swift 5 mode and above.

Resolves [SR-8704](https://bugs.swift.org/browse/SR-8704).

### CODE REVIEW

**Comment by slavapestov** [comment]
Hey @hamishknight, can you add entries to CHANGELOG.md for the various Swift 5-specific changes you've made, such as this fix and the redeclaration checking change?

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by hamishknight** [comment]
@slavapestov I've added changelog entries for this and the redeclaration change (happy to split the latter off into a separate PR if you feel it would be better reviewed separately). 

I wasn't sure whether to add an entry for #18951 as it feels more like a bug fix for the existing "favour members on concrete types over protocol members" rule – even though it is technically source breaking for a small number of quite contrived cases. Thoughts?

**Comment by hamishknight** [comment]
Debug compat suite failure appears to be unrelated – Chatto is failing quite consistently, and ProcedureKit is failing intermittently (e.g also in https://ci.swift.org/job/swift-PR-source-compat-suite-debug/72/). Release compat suite [passed](https://ci.swift.org/job/swift-PR-source-compat-suite/1842/).

**Comment by hamishknight** [comment]
Just realised that the new behaviour doesn't entirely follow the rule of matching the behaviour in a non-generic context, as the compiler can perform eager optional injection if it knows you're casting to a more optional type (which was the case even before #13910).

For example:

```swift
func forceCast<T>(_ value: Any?, to type: T.Type) -> T {
  return value as! T
}

let value: Any? = Any??.none
print(value as! Any??) // Optional(nil)
print(forceCast(value, to: Any??.self)) // nil
```

I've therefore edited the wording in the changelog to more accurately reflect this.

**Comment by hamishknight** [comment]
Just resolved a merge conflict in the changelog – is this good to go? If possible, I'd like to open a 4.2 cherry-pick for a potential 4.2.1 release to minimise compatibility issues.

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Review by DougGregor — APPROVED** [review]
LGTM.

**Comment by hamishknight** [comment]
Oops, needed to update a test for the new mangling prefix. Compat suite passed ([Release](https://ci.swift.org/job/swift-PR-source-compat-suite/1901/)) ([Debug](https://ci.swift.org/job/swift-PR-source-compat-suite-debug/126/)).

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by hamishknight** [comment]
Thanks Slava! Opened a 4.2 cherry-pick: https://github.com/apple/swift/pull/19562

**Pull request merged**
