### PR TITLE
Quickhelp xml swift 4.0 branch

### PR DESCRIPTION
**Pull request by mxswd**
Cherry pick.

### CODE REVIEW

**Review by bitjammer — APPROVED** [review]
Assuming tests are fine, again, LGTM.

**Comment by mxswd** [comment]
@swift-ci please smoke test and merge

**Comment by jrose-apple** [comment]
Release branches need a full test before you can merge.

@swift-ci Please test

**Review by anuragranjan629 — APPROVED** [review]

**Comment by jrose-apple** [comment]
Unrelated Linux failure.

@swift-ci Please test Linux

**Pull request merged**
