### PR TITLE
Merge tensorflow-merge into tensorflow

### PR DESCRIPTION
**Pull request by asuhan**

### CODE REVIEW

**Comment by asuhan** [comment]
Had a few minor conflicts following today's cleanups in the tensorflow branch.

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Review by dan-zheng — APPROVED** [review]
I checked only [`utils/update_checkout/update-checkout-config.json`](https://github.com/apple/swift/pull/27751/files#diff-1f9697a031abfd47a4ce3b4e90cad8ad), which looks correct.

**Comment by asuhan** [comment]
No point in merging this, https://github.com/apple/swift/commit/4ebb91046476f0700a61e293d78d78b270d517ef introduces new merge conflicts.

**Comment by dan-zheng** [comment]
> No point in merging this, [4ebb910](https://github.com/apple/swift/commit/4ebb91046476f0700a61e293d78d78b270d517ef) introduces new merge conflicts.

Sorry about that! I don't plan to create any more PRs today.
The GitHub interface suggests there aren't actually merge conflicts though.

**Comment by asuhan** [comment]
Fixed. There weren't any physical merge conflicts, just broken build because of `GenericSignature` changes from pointer to value.

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Pull request merged**
