### PR TITLE
[ConstraintSystem][NFC] add test cases for argument matching

### PR DESCRIPTION
**Pull request by omochi**
This patch adds test cases for argument matching.

When I am working for #32082 , 
I need more odd inputs to test behavior.

I extract test cases from there and make it.

To add them into master is useful for review future changes of this area.

### CODE REVIEW

**Comment by omochi** [comment]
@swift-ci please smoke test

**Comment by omochi** [comment]
@swift-ci please smoke test Linux

**Review by xedin — APPROVED** [review]
Looks great! I think it would be useful to add tests like that for defaulted and variadic arguments as well.

**Comment by xedin** [comment]
@swift-ci please smoke test Linux platform

**Comment by omochi** [comment]
@xedin OK, I will add it as another patch.

**Pull request merged**
