### PR TITLE
Mangled name -> metadata] Add built-in types support

### PR DESCRIPTION
**Pull request by xedin**
Includes changes to Metadata to add Builtin.Float* types, Metadata lookup to use all known builtin types and demangler to we able to create mangling nodes from metadata for builtin opaque types.

### CODE REVIEW

**Comment by xedin** [comment]
@DougGregor for some reason I can't use `Builtin.Int8.self` or other Builitn types in the `test/Runtime/demangleToMetadata.swift`, so I'm wondering what is the best way to test this?

**Review by DougGregor — COMMENTED** [review]
Is there a way to use preprocess meta programming (with a .def file) to generate all of these from the same source? It’d be cleaner, and we won’t miss a any places if we add new builtins in the future. 

For testing, we add the ‘-parse-stdlib’ flag to enable the ‘Builtin’ module.

**Comment by xedin** [comment]
@DougGregor I will try but I'm new to such dark magic :)

**Comment by xedin** [comment]
Going to close this one and open new PR with meta-programming changes.

**Pull request closed without merging**
