### PR TITLE
Use withUnsafeTemporaryAllocation instead of a temporary Array

### PR DESCRIPTION
**Pull request by Catfish-Man**

### CODE REVIEW

**Comment by Catfish-Man** [comment]
@swift-ci please smoke test

**Comment by Catfish-Man** [comment]
@swift-ci please benchmark

**Review by grynspan — APPROVED** [review]

**Comment by Catfish-Man** [comment]
@swift-ci please benchmark

**Comment by Catfish-Man** [comment]
@swift-ci please smoke test

**Comment by Catfish-Man** [comment]
@swift-ci please smoke benchmark

**Comment by Catfish-Man** [comment]
@swift-ci please test macOS platform

**Comment by Catfish-Man** [comment]
@swift-ci please benchmark

**Pull request merged**
