### PR TITLE
Revert "Allow implicit self in escaping closures when self usage is unlikely to cause cycle"

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/swift#23934

This should restore the Windows CI to green.  Revert to ensure that the CI is green during lockdown.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by shahmishal** [comment]
@swift-ci smoke test

**Comment by theblixguy** [comment]
cc @Jumhyn it seems like `expr/closures.swift` test is [failing](https://ci-external.swift.org/job/oss-swift-windows-x86_64/2301/) on Windows due to your changes. Could you investigate why this is happening?

**Comment by drodriguez** [comment]
By the way, I think the problem lies in https://github.com/apple/swift/pull/23934/files#diff-3f6a161822412eea4b0e705487dd88c1L2446-L2447

```
    bracketRange = SourceRange(consumeToken(tok::l_square),
    consumeToken(tok::r_square);
                               consumeToken(tok::r_square));
```

The order in which the parameters are evaluated is implementation defined, and in MSVC happens to be reverse order.

So I think the assertion happens because `tok::r_square` is being consumed before `tok::l_square`.

If everyone agrees, I would not mind preparing a PR with the change.

**Comment by drodriguez** [comment]
Created #28906 with a possible fix. Linux doesn't show a difference. I hope MSVC will.

**Comment by theblixguy** [comment]
Thank you @drodriguez!

**Comment by compnerd** [comment]
Yeah, lets go with #28906 instead.

**Comment by Jumhyn** [comment]
Was traveling all day today so just catching up on this. Thanks for jumping on that @drodriguez! Is there a reason that Windows is not a part of the CI workflow before merging?

**Comment by drodriguez** [comment]
Many. The Windows machines (2) are not managed by Apple. They are part of the community CI. Growing that number further will allow pre-merge validation, but growing that number if painful because deploying/managing Windows is painful and the community CI requirements. We are quite diligent in catching most problems post-merge, but with the branch freezes, we have a little bit of a scramble.

In any case, thanks for the contribution. It was a very non obvious things to catch coding or reviewing (it took me a couple of times looking where the assertion was happening for my lightbulb to light up :D).

**Comment by Jumhyn** [comment]
Gotcha, thanks for the context. Excellent catch!

**Pull request closed without merging**
