### PR TITLE
Fix block merging after inlining to be linear, not quadratic.

### PR DESCRIPTION
**Pull request by atrick**
A recent SILCloner rewrite removed a special case hack for single
basic block callee functions:

commit c6865c0dff6bca722d6847e4ce8327203760b726
Merge: 76e6c4157e 9e440d13a6
Author: Andrew Trick <atrick@apple.com>
Date:   Thu Oct 11 14:23:32 2018

    Merge pull request #19786 from atrick/silcloner-cleanup

    SILCloner and SILInliner rewrite.

Instead, the new inliner simply merges trivial unconditional branches
after inlining the return block. This way, the CFG is always in
canonical state after inlining. This is more robust, and avoids
interfering with subsequent SIL passes when non-single-block callees
are inlined.

The problem is that inlining a series of calls within a large block
could result in interleaved block splitting and merging operations,
which is quadratic in the block size. This showed up when inlining the
tens of thousands of array subscript calls emitted for a large array
initialization.

The fix is to simply defer block merging until all calls are
inlined. This both solves the original problem of canonicalizing the
inliner output and eliminates the quadratic behavior.

We can't expect SimplifyCFG to run immediately after inlining, nor
would we want to do that, *especially* for mandatory inlining. This
fix instead exposes block merging as a trivial utility.

Fixes SR-9223: Inliner exhibits slow compilation time with a large
static array.

Note: by eliminating some unconditional branches, this change could
reduce the number of debug locations emitted. This does not
fundamentally change any debug information guarantee, and I was unable
to observe any behavior difference in the debugger.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
@swift-ci test source compatibility.

**Comment by atrick** [comment]
@swift-ci test.

**Review by eeckstein — APPROVED** [review]
LGTM!

**Comment by atrick** [comment]
@swift-ci smoke test.

**Comment by atrick** [comment]
@swift-ci test.

**Pull request merged**
