### PR TITLE
[SIL] Extract reoccuring allocation patterns.

### PR DESCRIPTION
**Pull request by huonw**
No need to write a pile of manual memcpy's.

### CODE REVIEW

**Comment by atrick** [comment]
Nice.

**Comment by huonw** [comment]
@swift-ci Please smoke test and merge.

**Comment by huonw** [comment]
@swift-ci Please smoke test and merge.

**Comment by huonw** [comment]
@swift-ci Please smoke test and merge.

**Comment by gottesmm** [comment]
+1!

**Comment by gottesmm** [comment]
@swift-ci Please smoke test and merge.

**Comment by gottesmm** [comment]
@huonw Not sure why it didn't trigger when you did this.
@shahmishal Any idea of what happened here?

**Comment by shahmishal** [comment]
It was triggered but it might have take few mins before it updated the status. 

https://ci.swift.org/job/swift-PR-smoke-merge/1684/parameters/

**Pull request merged**
