### PR TITLE
[Vim] vim syntax update for concurrency keyword

### PR DESCRIPTION
**Pull request by cachemeifyoucan**
Update swift.vim to contain concurrency keywords like `async` and `await`.

### CODE REVIEW

**Review by compnerd — APPROVED** [review]
Thanks!

**Comment by cachemeifyoucan** [comment]
@swift-ci please smoke test

**Comment by zixu-w** [comment]
🎉 

Should we keep the alphabetical order in the lists?

**Comment by compnerd** [comment]
> Should we keep the alphabetical order in the lists?

Certainly would be nice.

**Comment by cachemeifyoucan** [comment]
I not only didn't realize it was in alphabetical order but also wondering why keywords that are related were so far apart.

Will fix

**Comment by cachemeifyoucan** [comment]
@swift-ci please test

**Review by zixu-w — APPROVED** [review]

**Pull request merged**
