### PR TITLE
Python improvements in utils/80+-check

### PR DESCRIPTION
**Pull request by alexwlchan**
#### What's in this pull request?
- The original version had an off-by-one error in the line number
  (assuming you use the GitHub model of starting lines at 1).  Fix this
  error, and move to using `enumerate()` instead of tracking the
  `count` variable ourselves.
- Add a comment about the exit codes to the help message.
- Increase clarity in variable/argument names.
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

This isn’t resolving any bugs in the Swift bug tracker (or at least, not intentionally so).

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by gribozavr** [comment]
@swift-ci Please Python lint

**Comment by gribozavr** [comment]
@alexwlchan Thanks!  Could you take a look at lint issues?

**Comment by alexwlchan** [comment]
@gribozavr Lint issues should be fixed.

**Comment by gottesmm** [comment]
@swift-ci Please Python lint

**Pull request merged**
