### PR TITLE
Do not skip `earlyswiftdriver` in SwiftPM Linux CI Preset

### PR DESCRIPTION
**Pull request by artemcm**

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
Nitpicky title update to make search easier: official name is SwiftPM and when searching for SwiftPM in issues/PRs, anything that uses "SPM" won't show up in search results.

**Review by MaxDesiatov — COMMENTED** [review]
Issue description is empty, I don't have much experience with the toolchain build system, I don't know where documentation for this `build-script` flag is, or what this flag is doing, so I'm not sure how to review this. What impact does it have?

**Comment by artemcm** [comment]
> Issue description is empty, I don't have much experience with the toolchain build system, I don't know where documentation for this `build-script` flag is, or what this flag is doing, so I'm not sure how to review this. What impact does it have?

https://github.com/apple/swift/blob/e5742be3afb5456357ba548b25f0d9bbb7c70ca5/utils/build_swift/build_swift/driver_arguments.py#L695

This flag skips building the "early" swift driver which gets built using the host toolchain and gets used as the default driver in the compiler build directory. Building the early swift driver is otherwise the default today, and I'm not sure if there's a good reason it gets skipped here.

**Comment by artemcm** [comment]
We should test this by launching a CI run in the SwiftPM repo against this change, if possible, too.

**Comment by MaxDesiatov** [comment]
I've just started a cross-repo Linux job here https://github.com/apple/swift-package-manager/pull/7273#issuecomment-1899383036

**Comment by artemcm** [comment]
> Thanks for the explanation! I've just started a cross-repo Linux job here [apple/swift-package-manager#7273 (comment)](https://github.com/apple/swift-package-manager/pull/7273#issuecomment-1899383036)

Thanks!

**Comment by artemcm** [comment]
@swift-ci test

**Review by MaxDesiatov — APPROVED** [review]
Ship it!

**Pull request merged**
