### PR TITLE
[5.9][ConstraintSystem] Improvements to variadic generics inference

### PR DESCRIPTION
**Pull request by xedin**
Cherry-pick of https://github.com/apple/swift/pull/64733
Cherry-pick of https://github.com/apple/swift/pull/64780

---

- Explanation:

  - Fixes crash-on-invalid when argument is a tuple that needs to be exploded into N arguments.
  - Fixes multiple issues in solution application logic related to variadic generic parameters:
     1. conversions/loads handling
     2. default arguments handling

- Scope: Calls to variadic generic functions with defaulted parameters, multiple variadic parameters and/or arguments that require conversions or l-value loading.

- Main Branch PRs: https://github.com/apple/swift/pull/64733, https://github.com/apple/swift/pull/64780

- Resolves: rdar://106775969

- Risk: Low

- Reviewed By: @hborla

- Testing:  Added a regression test-case to the suite.

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test macOS platforms

**Review by hborla — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Pull request merged**
