### PR TITLE
[SILGen] Directly silgen access of #dsohandle

### PR DESCRIPTION
**Pull request by bitjammer**
Synthesizing a VarDecl for #dsohandle causes some unwanted accessors to
be expected, but we really don't need them: this is a global variable
for the start of the image. There are only two uses of getDSOHandle:
getting the type and emitting the SIL for it. Rather than perform
acrobatics to turn off switches, just emit access directly where it's
needed.

rdar://problem/26565092

### CODE REVIEW

**Comment by bitjammer** [comment]
@swift-ci Please smoke test

**Comment by bitjammer** [comment]
@swift-ci Please smoke test

**Comment by bitjammer** [comment]
@swift-ci Please smoke test

**Comment by bitjammer** [comment]
OS X passes but it looks like the Linux pull request bot is having problems with the standard library, unrelated to my change. I'll rebase and try Linux again before merging.

**Comment by bitjammer** [comment]
@swift-ci Please smoke test Linux

**Comment by bitjammer** [comment]
Looks like an unrelated LLDB failure on the Linux bot.

**Comment by bitjammer** [comment]
@swift-ci Smoke test

**Comment by bitjammer** [comment]
@swift-ci Smoke test

**Comment by bitjammer** [comment]
@swift-ci Smoke test

**Comment by bitjammer** [comment]
@swift-ci Smoke test

**Comment by jckarter** [comment]
Looks good!

**Pull request merged**
