### PR TITLE
[OnoneSimplify] Handle tuple(destructure_tuple()).

### PR DESCRIPTION
**Pull request by nate-chandler**
It's a noop.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please benchmark apple silicon

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please test linux platform

**Comment by nate-chandler** [comment]
@swift-ci please test source compatibility

**Comment by nate-chandler** [comment]
@swift-ci please test linux platform

**Review by eeckstein — APPROVED** [review]
lgtm!

**Comment by nate-chandler** [comment]
@swift-ci please apple silicon benchmark

**Pull request merged**
