### PR TITLE
Pass optimization options to the -emit-pch job

### PR DESCRIPTION
**Pull request by rjmccall**
Now that the Clang importer honors and expects -O, make sure we pass it to the PCH job.

rdar://33541306

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please smoke test.

**Comment by jrose-apple** [comment]
So this *will* pass -O to merge-module jobs, which I think means SIL passes will actually get run. Can you check that?

**Comment by rjmccall** [comment]
From inspection, yes, that seems to be true.

Is it safe to set the merge-modules job up to use a non-matching PCH?

**Comment by rjmccall** [comment]
Alternatively, it would be easy to tell the frontend that this is overall an optimized build but that it does not need to re-run the optimizer, either specially or be inferring it somehow from the command line.

**Comment by jrose-apple** [comment]
The merge-modules job doesn't use the PCH at the moment, which is a whole other story, but whether it does or not people could be conditionalizing on `__OPTIMIZE__`. So this is clearly the way to go, but we need to stop the job from running SIL passes first.

**Comment by jrose-apple** [comment]
(I tried at one point and it seemed non-trivial, and so I gave up and filed [SR-3063](https://bugs.swift.org/browse/SR-3063) to get to it later.)

**Comment by rjmccall** [comment]
The SIBGen stuff is known to the driver and isn't just a MergeModulesJob, right?  Or is it?

**Comment by jrose-apple** [comment]
I don't remember. :-( If we break SIBGen for now that's probably acceptable.

**Comment by jrose-apple** [comment]
Sorry for the mess here. You've just stumbled over an existing hole.

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Comment by jrose-apple** [comment]
Heh. Okay, that works. Thanks, John.

**Comment by rjmccall** [comment]
@swift-ci Please test and merge.

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Comment by rjmccall** [comment]
@swift-ci Please smoke test.

**Pull request merged**
