### PR TITLE
[ClangImporter] Make sure that headers from the bridging header are considered 'isBeforeInTranslationUnit' compared to headers imported from swift code

### PR DESCRIPTION
**Pull request by akyrtzi**
Previously headers from the bridging header and imported modules had the exact same top location so comparison with them was not sound. This resulted in missing documentation comments from declarations and possible assertion hits while clang was trying to determine the comment for a declaration, but I could not create a reduced test case that triggered an assertion hit.
    
rdar://34925466

### CODE REVIEW

**Comment by akyrtzi** [comment]
@swift-ci smoke test

**Review by jrose-apple — APPROVED** [review]
Thanks for figuring out this mess!

**Comment by akyrtzi** [comment]
@swift-ci smoke test linux platform

**Comment by akyrtzi** [comment]
@swift-ci smoke test OS X platform

**Pull request merged**
