### PR TITLE
Fix store_borrow generation and improve its verification

### PR DESCRIPTION
**Pull request by meg-gupta**
This change makes SILGen, SILOptimizer and SILVerifier changes to ensure all store_borrows are ended with an end_borrow, and uses of the store_borrow destination are all in the enclosing store_borrow scope and are via the store_borrow return address.

### CODE REVIEW

**Comment by meg-gupta** [comment]
TODO: A utility to insert end_borrows for store_borrows

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci source compatibility test

**Comment by meg-gupta** [comment]
@swift-ci test source compatibility

**Comment by meg-gupta** [comment]
@swift-ci smoke test

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci benchmark

**Comment by meg-gupta** [comment]
@swift-ci test source compatibility

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by atrick** [comment]
A couple things to follow up on

Add the verifier tests cases. Make sure we have one for nested scopes: store borrow within load borrow within store borrow

TODO: GenericCloner should insert end_borrows at the function exit points

The ScopedAddressOperand/ScopedAddressValue utilities can be merged into a single ScopedAddress utility

Probably no longer need the `endScope` utilities. Or keep them but make them failable, or the client needs to use a bailable computeLiveness analysis first. Then call endScopeAtLiveness only if it succeeds.

Don't need some new "use-specific" utilities

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test and merge

**Comment by asl** [comment]
@meg-gupta It seems that https://github.com/apple/swift/blob/main/docs/SIL.rst#store-borrow should be modified as well to outline the semantics of returned value of `store_borrow`.

**Pull request merged**
