### PR TITLE
[IRGen] Make (most) builtin type metadata round-trippable.

### PR DESCRIPTION
**Pull request by DougGregor**
Rather than mapping all of the builtin floating-point and vector
types down to the type metadata symbols for power-of-two integers,
map down to the type metadata symbols provided by the runtime.
This allows us to round-trip type metadata <-> mangled name for all of
the builtin types that have such symbols. When we don’t have a runtime
symbol, we will fail to link if that builtin type gets referenced. Expose symbols for metadata for
the various builtin floating point types and vector types. This is used by the demangler to
handle builtin names.

This is a narrow fix for rdar://problem/45569984 (where we couldn’t
demangle a builtin vector type). A more extensive fix will require us
to add a general runtime facility for creating opaque type metadata
with specific size/alignment/stride/uniquing name.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Hmm, I have a suspicion that this broke the Windows build :-(.  The problem is with clang:

```
swift/stdlib/public/runtime/MetadataImpl.h:98:15: error: definition with same mangled name '?destroy@?$NativeBox@T__m128@@$0BA@$0BA@$0BA@@metadataimpl@swift@@SAXPEAT__m128@@@Z' as another definition
```

Even better is that `llvm-undname` fails to undecorate the name.  This is:
`public: static void __cdecl swift::metadataimpl::NativeBox<union __m128,16,16,16>::destroy(union __m128 * __ptr64)`

**Comment by compnerd** [comment]
I have a fix for clang, but while thinking about this a bit, I came up with a clever workaround by aliasing the 4-vector to the 3-vector types since the 3-vector is supposed to be backed by a 4-vector type but with only 3 of the lanes used.  I put that up at https://github.com/apple/swift/pull/20113.

**Pull request merged**
