### PR TITLE
Add missing setIsParseError() during enum case parsing

### PR DESCRIPTION
**Pull request by jtbandes**
An invalid `case` construct would incorrectly return a successful status, causing `parseDecl` to crash later when it assumed there were valid decls in the `Entries` vector.

### CODE REVIEW

**Comment by cwillmor** [comment]
Whoa, well spotted. It looks like the minimal crasher for this is `class case, case`. Could you please add that as a test case to `test/stmt/statements.swift` with the appropriate expected diagnostics?

**Comment by jtbandes** [comment]
@cwillmor Updated. I'm not sure these diagnostics are really great, but I guess it's valuable to have them tested anyway?

**Comment by cwillmor** [comment]
Yeah, the main idea is that it shouldn't crash. Thanks for putting this together.

**Comment by jtbandes** [comment]
:tophat:

**Pull request merged**
