### PR TITLE
Update tensorflow repo to check out a specific commit.

### PR DESCRIPTION
**Pull request by mhong**

### CODE REVIEW

**Comment by mhong** [comment]
@swift-ci please test tensorflow

**Review by dan-zheng — APPROVED** [review]
Thank you!

**Comment by mhong** [comment]
On https://ci-external.swift.org/job/swift-PR-TensorFlow-Linux/253/console, it has error:

```
======UPDATE FAILURES======
/home/swiftci/jenkins/workspace/swift-PR-TensorFlow-Linux/tensorflow failed (ret=128): ['git', 'checkout', u'9752b117ff63f204c4975cad52b5aab5c1f5e9a9']
fatal: reference is not a tree: 9752b117ff63f204c4975cad52b5aab5c1f5e9a9
```

Will try clean test as suggested by Dan.

**Comment by mhong** [comment]
@swift-ci please clean test tensorflow

**Review by rxwei — APPROVED** [review]

**Pull request merged**
