### PR TITLE
Remove archetype mangling

### PR DESCRIPTION
**Pull request by slavapestov**
Other than the special 'qualified archetype' mangling for debug info, we have no good reasons to mangle archetypes anymore. This PR removes this mangling, which came up with variables and closures. Instead we just mangle the interface type.

Tests still need updating.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test Linux

**Comment by jrose-apple** [comment]
Does this affect SourceKit and USRs?

**Comment by slavapestov** [comment]
This PR is actually wrong because LLDB breaks for some reason. I'll invesigate.

I believe USR mangling already calls getInterfaceType(), but I might be wrong.

**Comment by DougGregor** [comment]
@slavapestov I think you told me why LLDB used this information, but now I've completely forgotten. If you remember, can you record it here for posterity? This is close to being in my critical path.

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
This is a rebased version. It will still fail in LLDB tests (unless that magically got fixed) -- I'll finish this up tomorrow.

**Comment by slavapestov** [comment]
@swift-ci Please test Linux

**Comment by DougGregor** [comment]
Yippee!

**Pull request merged**
