### PR TITLE
[silgen] Eliminate last use of emitCheckedCastBranchOld and delete de…

### PR DESCRIPTION
**Pull request by gottesmm**
…ad code.

rdar://29791263

### CODE REVIEW

**Comment by gottesmm** [comment]
I think there may be a few test failures still. Getting some testing in.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci asan test

**Comment by gottesmm** [comment]
Linux failed when building swiftpm.

**Comment by gottesmm** [comment]
Lets see how far macOS gets with a smoke test (where it doesn't build swiftpm IIRC).

**Comment by gottesmm** [comment]
@swift-ci smoke test OSX platform

**Comment by gottesmm** [comment]
@swift-ci smoke test osx platform

**Comment by gottesmm** [comment]
@swift-ci smoke test osx platform

**Comment by gottesmm** [comment]
@swift-ci  smoke test OS X platform

**Comment by gottesmm** [comment]
@swift-ci smoke test OS X platform

**Comment by gottesmm** [comment]
Found the problem.

**Review by jckarter — APPROVED** [review]
Looks good.

**Pull request merged**
