### PR TITLE
Sourcekit+Evaluator: refactor cursor-info resolver to using the evaluator model. NFC

### PR DESCRIPTION
**Pull request by nkcsgexi**
This change adds a new IDE request ID zone and refactors the cursor-info resolver
to use the request evaluator model.

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci Please Sourcekit Stress test

**Comment by nkcsgexi** [comment]
@swift-ci please stress test

**Comment by DougGregor** [comment]
This is very cool, thank you!

**Pull request merged**
