### PR TITLE
[DebugInfo] Reenable 2 failings watch tests

### PR DESCRIPTION
**Pull request by augusto2112**
The tests were not taking into account running in 32 bit platforms

rdar://124465351

### CODE REVIEW

**Comment by augusto2112** [comment]
@swift-ci smoke test

**Comment by augusto2112** [comment]
@swift-ci test

**Review by adrian-prantl — APPROVED** [review]
Looks reasonable.

**Review by adrian-prantl — COMMENTED** [review]
You can also change the type in the program to Int32 maybe?

**Pull request merged**
