### PR TITLE
Remove incorrect early exit from type access checking.

### PR DESCRIPTION
**Pull request by jrose-apple**
…then downgrade the resulting errors to warnings to be compatible with Swift 3.0GM.

This was a correct compile-time optimization for Swift 2, but Swift 3 has multiple levels of "private" that need to be taken into account. Fortunately these cases are all safe; they're the cases that would all be `fileprivate` in Swift 2.

Resolves [SR-2579](https://bugs.swift.org/browse/SR-2579).

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@aleksgapp, since you've been working on the access scope patch, would you mind checking my work here? (Sorry for creating yet another merge conflict…but at least it explains what those weird conditions in checkTypeAccessibilityImpl were.)

@jckarter, would you mind reviewing as well?

**Comment by jrose-apple** [comment]
Linux failure is a known-flaky Foundation test that Philippe commented about in another PR.

@swift-ci Please test Linux platform

**Comment by jrose-apple** [comment]
Two in a row. @phausler, maybe we should just disable the test for now?

**Comment by jckarter** [comment]
LGTM.

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test Linux platform

**Pull request merged**
