### PR TITLE
Handle begin_apply in TempRVO

### PR DESCRIPTION
**Pull request by meg-gupta**
A tempobj passed to begin_apply instruction and cannot be modified by it
(is guaranteed and doesn't alias with other inout args) has potential to be optimized
away.

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci please test

**Comment by meg-gupta** [comment]
@swift-ci benchmark

**Comment by meg-gupta** [comment]
@swift-ci please benchmark

**Review by atrick — CHANGES_REQUESTED** [review]
Thanks for fixing this. But remember that a begin_apply operand is used at the point of the end_apply. So the end_apply needs to be considered the use-point for things like checkNoSourceModification.

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test linux

**Comment by meg-gupta** [comment]
@swift-ci please test

**Review by atrick — COMMENTED** [review]
LGTM

**Pull request merged**
