### PR TITLE
[CMake] Make swift-frontend the primary Swift binary.

### PR DESCRIPTION
**Pull request by DougGregor**
Build swift-frontend as the primary Swift binary, and have
`swift`/`swiftc`/etc. symlink over to it. This is a step toward allowing
[swift-driver](https://github.com/apple/swift-driver) to replace `swift` and `swiftc` binaries.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test platform windows

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test platform Windows

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by DougGregor** [comment]
> @swift-ci please test Windows platform

How can I track down the results when we run these tests?

**Comment by drodriguez** [comment]
https://ci-external.swift.org/view/Pull%20Request/job/swift-PR-windows/160/ (but I don't know why it wasn't reported back here).

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci test

**Comment by DougGregor** [comment]
@swift-ci test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test macOS

**Comment by DougGregor** [comment]
@swift-ci please test Windows

**Comment by DougGregor** [comment]
@swift-ci test Windows

**Comment by DougGregor** [comment]
@swift-ci test macOS

**Comment by DougGregor** [comment]
@swift-ci test macOS

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility Debug

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility Debug

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility Debug

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility debug

**Comment by DougGregor** [comment]
Source-compatibility failures are actually UPASS's, so we'll get that cleaned up. Windows failure is unrelated. Time to merge!

**Comment by davezarzycki** [comment]
Hi @DougGregor – This broke unified builds:

```
CMake Error at /home/dave/s/u/swift/tools/swift-remoteast-test/CMakeLists.txt:13 (add_dependencies):
  Cannot add target-level dependencies to non-existent target "swift".

  The add_dependencies works for top-level logical targets created by the
  add_executable, add_library, or add_custom_target commands.  If you want to
  add file-level dependencies see the DEPENDS option of the add_custom_target
  and add_custom_command commands.


```

**Pull request merged**
