### PR TITLE
[4.0] Make all CF types Equatable and Hashable.

### PR DESCRIPTION
**Pull request by jrose-apple**
Cherry-pick of #4568 to the 4.0 branch. Reviewed by @DougGregor.

[SR-2388](https://bugs.swift.org/browse/SR-2388) / rdar://problem/32003073

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by lplarson** [comment]
@swift-ci please test source compatibility

**Comment by phausler** [comment]
you should probably check CFAllocator (because it has slightly different behavior than the other CF types when it comes to bridges)

as well as bridged subclasses, e.g. a subclass of NSString as a CFString and validating the appropriate hash function is called

**Comment by jrose-apple** [comment]
Thanks. I'm not sure whether I care *that* much about people trying to hash or compare allocators—it'll be no worse than doing it in C—but I'll check. The bridging is a good end-to-end test that I'll add on master.

**Comment by jrose-apple** [comment]
@lplarson: The source compat failures all seem unrelated to this change. Was there something up with that? https://ci.swift.org/job/swift-PR-source-compat-suite/52

**Comment by phausler** [comment]
Per the allocator that one was just a class that I knew followed a slightly different layout pattern and could cause "issues"

**Comment by lplarson** [comment]
@jrose-apple Expected failures haven't been configured for 4.0 yet. I'm working on that today.

**Pull request merged**
