### PR TITLE
Close Soundness Hole in Incremental Build

### PR DESCRIPTION
**Pull request by CodaFi**
Fix a longstanding bug in the driver where the incremental build would
fail to execute dependent jobs and allow errors in primaries in later
waves to become buried. A simplified version of a situation that exposes
this bug has been committed into the tests.

Imagine two files:

```
// one.swift

struct A {}

// two.swift

func use() {
  let _ = A()
}
```

After a clean build, we modify one.swift as follows:

```
// one.swift

struct B< {}
```

The syntax error in this file caused the baseline driver to fail the
build immediately and thus we would not schedule two.swift for
execution. This is incorrect! Consider correcting the syntax error in
one.swift:

```
// one.swift

struct B {}
```

two.swift _still_ won't be rebuilt because
1) It was never modified during any step of this process
2) The swiftdeps of two.swift have not been updated to flush out the
   dependency on A.

rdar://72800626

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by CodaFi** [comment]
This fix is somewhat narrow so that it is CCC'able. We may want to do something more drastic like poison the build record entries for any dependents of a failed job.

**Comment by davidungar** [comment]
> Fix a longstanding bug in the driver where the incremental build would
> fail to execute dependent jobs and allow errors in primaries in later
> waves to become buried. A simplified version of a situation that exposes
> this bug has been committed into the tests.
> 
> Imagine two files:
> 
> ```
> // one.swift
> 
> struct A {}
> 
> // two.swift
> 
> func use() {
>   let _ = A()
> }
> ```
> 
> After a clean build, we modify one.swift as follows:
> 
> ```
> // one.swift
> 
> struct B< {}
> ```
> 
> The syntax error in this file caused the baseline driver to fail the
> build immediately and thus we would not schedule two.swift for
> execution. This is incorrect! Consider correcting the syntax error in
> one.swift:
> 
> ```
> // one.swift
> 
> struct B {}
> ```
> 
> two.swift _still_ won't be rebuilt because
> 
> 1. It was never modified during any step of this process
> 2. The swiftdeps of two.swift have not been updated to flush out the
>    dependency on A.
> 
> rdar://72800626
Great catch! We need to fix this problem for sure.

However at first glance, I have some doubts about whether this is the most correct fix. Rather than continue the job, and increase compilation time, I think there might be a better way:

It feels to me that the problem may be--I haven't looked at the code closely yet--in the computation of jobs that must be recompiled after *reloading* a swiftdeps file. If I'm not mistaken, in the example above once the syntax error is corrected, the swiftdeps file for one.swift *loses* a definition upon which two.swift depends. Apparently this loss is *not* triggering the recompilation of `two.swift`. I'll look at it tomorrow, I could certainly be wrong. But my hunch is that the driver is wrongly insensitive to the loss of a definition from a `SourceFileDependencyGraph`.

**Review by davidungar — CHANGES_REQUESTED** [review]
At this point, I harbor doubts about this change being the best fix. (See my comment quoting the bug scenario.)

**Comment by CodaFi** [comment]
Integration can’t detect this because the priors for the jobs that get skipped are not regenerated. It effectively is waiting for a posterior to signal that `A` has been deleted but it will never have that signal because we’re really modifying `B`, which it has no dependency on.

**Comment by CodaFi** [comment]
If you’re worried about the impact on compile time, we need to pursue the fix I alluded to wherein we poison the second wave from the failing job to force the swiftdeps to turn over on the next rebuild.

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Pull request merged**
