### PR TITLE
Eliminate C-style ForStmt

### PR DESCRIPTION
**Pull request by rintaro**
As per discussion in #11307 .

Now C-style `for` are diagnosed as:
```
test.swift:1:1: error: C-style for statement has been removed in Swift 3
for var x = 1; x < 12; x += 1 {
^   ~~~~~~~~~~~~~~~~~~~~~~~~~
test.swift:4:1: error: C-style for statement has been removed in Swift 3
for (var x = 1; x < 12; x += 1) {
^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
without fix-it.

### CODE REVIEW

**Comment by rintaro** [comment]
I'm thinking about adding back diagnostics fix-it in `Parser` .
WIP-branch: https://github.com/apple/swift/commit/a002390f413b780de1b939a86bbdac738df5bce9

What do you think @DougGregor , @jrose-apple ?

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
The for loop was deprecated over a year ago, I think we don't need a fixit anymore.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by huonw** [comment]
Wow, -800 is awesome!

**Comment by jrose-apple** [comment]
As stated on the other thread, it's still nice to have a fix-it for people manually porting new C code, or copying old old Swift code from websites.

**Comment by jrose-apple** [comment]
Oops, about the fix-it. Yes, it's probably okay to drop the "clever" fix-its.

**Comment by DougGregor** [comment]
I guess I kinda like keeping the Fix-Its (i.e., the WIP branch); we already have most of the work done there, it improves the user experience, and the code is localized to the parser.

**Comment by rintaro** [comment]
@jerrywaters I'm not sure what you mean. Could you elaborate?

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by DougGregor** [comment]
+202 −1,072 is awesome.  This LGTM once the compatibility suite finishes

**Pull request merged**
