### PR TITLE
[stdlib] replace uses of assert in the Concurrency module

### PR DESCRIPTION
**Pull request by glessard**
- `assert` was still detectable in released dylibs of libswift_Concurrency, costing execution time and code size
- defined a local equivalent to `_internalInvariant` that will compile to nothing in release builds

Solves rdar://85258838

### CODE REVIEW

**Comment by glessard** [comment]
@swift-ci please test

**Comment by glessard** [comment]
@swift-ci please test

**Review by phausler — APPROVED** [review]
This looks good to me, obviously the better solution would be to make Deque part of the standard library, but this seems like a reasonable step.

**Comment by glessard** [comment]
@swift-ci please test Windows platform

**Pull request merged**
