### PR TITLE
[Frontend] Ignore adjacent swiftmodule in compiler host modules

### PR DESCRIPTION
**Pull request by bnbarham**
`lib/swift/host` contains modules/libraries that are built by the host compiler. Their `.swiftmodule` will never be able to be read, ignore them entirely.

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
FWIW this came up in https://github.com/apple/swift/pull/66043. Macro tests are failing because they are built with the just-built compiler using modules from `lib/swift/host`. Those modules are built with the host compiler (so eg. 5.7) and thus the swiftmodule are not compatible with the just-built compiler, which is what we're using to build the macros. This doesn't happen right now because only the swift interfaces are copied from early-swiftsyntax.

Another solution would be to emit the modules in a separate directory and only emit the interfaces in `lib/swift/host`, which I could do, but that felt worse. Once we switch to 3.26 and remove these workaround functions to build swift libraries, that may also get a little more difficult.

**Review by xymus — APPROVED** [review]
It looks good!

**Comment by bnbarham** [comment]
@swift-ci please test

**Pull request merged**
