### PR TITLE
Do not install binary swiftmodule for Darwin

### PR DESCRIPTION
**Pull request by edymtt**
This is needed to support Apple internal configurations that would fail
consuming such binary swiftmodule (but work as expected when rebuilding
from the swiftinterface).

Take the chance to cleanup the installation code for stdlib modules -- namely remove duplication and align the macCatalyst logic.

Addresses rdar://124390643

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci please test

**Comment by edymtt** [comment]
@swift-ci please test WebAssembly

**Comment by edymtt** [comment]
@swift-ci please build toolchain

**Comment by edymtt** [comment]
Discussed this with Evan offline -- the long term solution would be to leverage the `-sysroot` option that is being proposed in #72352, this PR would serve as a short term solution while the above is being discussed.

**Comment by compnerd** [comment]
Does it make sense to invert the flag and add an install Swift module flag instead?

**Review by ian-twilightcoder — APPROVED** [review]

**Comment by edymtt** [comment]
@swift-ci please test

**Comment by edymtt** [comment]
@swift-ci please test WebAssembly

**Comment by edymtt** [comment]
@swift-ci please build toolchain

**Comment by edymtt** [comment]
@swift-ci Please Test Source Compatibility Release

**Comment by edymtt** [comment]
@compnerd: yes, it makes sense -- I was focused on getting something out to gauge my approach, and I was tempted to go down the fast route.

Reworked this in cd17f74a9c133e041b98fbdee555de112247f5fc (with some added logic to make the installation the default action)

**Comment by edymtt** [comment]
@swift-ci please test

**Comment by edymtt** [comment]
@swift-ci please test WebAssembly

**Comment by edymtt** [comment]
@swift-ci please build toolchain

**Comment by edymtt** [comment]
@swift-ci Please Test Source Compatibility Release

**Comment by edymtt** [comment]
@swift-ci please clean test macOS

**Comment by edymtt** [comment]
The source compatibility suite has the same 9 failures of the main run.

**Review by etcwilde — APPROVED** [review]

**Review by compnerd — APPROVED** [review]

**Comment by edymtt** [comment]
Verified this has no changes for the Linux toolchain, and only Darwin binary swiftmodules are dropped in the macOS one:

```
> diff -u <(pushd swift-DEVELOPMENT-SNAPSHOT-2024-03-27-a-ubuntu18.04 > /dev/null  && find . -name "*.swiftmodule" ) <(pushd PR-ubuntu2004 > /dev/null  && find . -name "*.swiftmodule")
> diff -u <(pushd swift-DEVELOPMENT-SNAPSHOT-2024-03-27-a-osx/swift-DEVELOPMENT-SNAPSHOT-2024-03-27-a-osx-package.pkg/ > /dev/null && find . -name "*.swiftmodule") <(pushd swift-PR-72590-1200-osx/Library/Developer/Toolchains/swift-PR-72590-1200.xctoolchain/ > /dev/null && find . -name "*.swiftmodule")
--- /dev/fd/11	2024-03-28 08:00:38
+++ /dev/fd/12	2024-03-28 08:00:38
@@ -72,8 +72,6 @@
 ./usr/lib/swift/appletvsimulator/_StringProcessing.swiftmodule/arm64-apple-tvos-simulator.swiftmodule
 ./usr/lib/swift/appletvsimulator/_StringProcessing.swiftmodule/x86_64-apple-tvos-simulator.swiftmodule
 ./usr/lib/swift/appletvsimulator/Darwin.swiftmodule
-./usr/lib/swift/appletvsimulator/Darwin.swiftmodule/arm64-apple-tvos-simulator.swiftmodule
-./usr/lib/swift/appletvsimulator/Darwin.swiftmodule/x86_64-apple-tvos-simulator.swiftmodule
 ./usr/lib/swift/appletvsimulator/RegexBuilder.swiftmodule
 ./usr/lib/swift/appletvsimulator/RegexBuilder.swiftmodule/arm64-apple-tvos-simulator.swiftmodule
 ./usr/lib/swift/appletvsimulator/RegexBuilder.swiftmodule/x86_64-apple-tvos-simulator.swiftmodule
@@ -126,8 +124,6 @@
 ./usr/lib/swift/watchos/_StringProcessing.swiftmodule/arm64_32-apple-watchos.swiftmodule
 ./usr/lib/swift/watchos/_StringProcessing.swiftmodule/armv7k-apple-watchos.swiftmodule
 ./usr/lib/swift/watchos/Darwin.swiftmodule
-./usr/lib/swift/watchos/Darwin.swiftmodule/arm64_32-apple-watchos.swiftmodule
-./usr/lib/swift/watchos/Darwin.swiftmodule/armv7k-apple-watchos.swiftmodule
 ./usr/lib/swift/watchos/RegexBuilder.swiftmodule
 ./usr/lib/swift/watchos/RegexBuilder.swiftmodule/arm64_32-apple-watchos.swiftmodule
 ./usr/lib/swift/watchos/RegexBuilder.swiftmodule/armv7k-apple-watchos.swiftmodule
@@ -168,8 +164,6 @@
 ./usr/lib/swift/iphoneos/_StringProcessing.swiftmodule/arm64e-apple-ios.swiftmodule
 ./usr/lib/swift/iphoneos/_StringProcessing.swiftmodule/arm64-apple-ios.swiftmodule
 ./usr/lib/swift/iphoneos/Darwin.swiftmodule
-./usr/lib/swift/iphoneos/Darwin.swiftmodule/arm64e-apple-ios.swiftmodule
-./usr/lib/swift/iphoneos/Darwin.swiftmodule/arm64-apple-ios.swiftmodule
 ./usr/lib/swift/iphoneos/RegexBuilder.swiftmodule
 ./usr/lib/swift/iphoneos/RegexBuilder.swiftmodule/arm64e-apple-ios.swiftmodule
 ./usr/lib/swift/iphoneos/RegexBuilder.swiftmodule/arm64-apple-ios.swiftmodule
@@ -206,7 +200,6 @@
 ./usr/lib/swift/appletvos/_StringProcessing.swiftmodule
 ./usr/lib/swift/appletvos/_StringProcessing.swiftmodule/arm64-apple-tvos.swiftmodule
 ./usr/lib/swift/appletvos/Darwin.swiftmodule
-./usr/lib/swift/appletvos/Darwin.swiftmodule/arm64-apple-tvos.swiftmodule
 ./usr/lib/swift/appletvos/RegexBuilder.swiftmodule
 ./usr/lib/swift/appletvos/RegexBuilder.swiftmodule/arm64-apple-tvos.swiftmodule
 ./usr/lib/swift/appletvos/Observation.swiftmodule
@@ -242,9 +235,6 @@
 ./usr/lib/swift/watchsimulator/_StringProcessing.swiftmodule/i386-apple-watchos-simulator.swiftmodule
 ./usr/lib/swift/watchsimulator/_StringProcessing.swiftmodule/arm64-apple-watchos-simulator.swiftmodule
 ./usr/lib/swift/watchsimulator/Darwin.swiftmodule
-./usr/lib/swift/watchsimulator/Darwin.swiftmodule/x86_64-apple-watchos-simulator.swiftmodule
-./usr/lib/swift/watchsimulator/Darwin.swiftmodule/i386-apple-watchos-simulator.swiftmodule
-./usr/lib/swift/watchsimulator/Darwin.swiftmodule/arm64-apple-watchos-simulator.swiftmodule
 ./usr/lib/swift/watchsimulator/RegexBuilder.swiftmodule
 ./usr/lib/swift/watchsimulator/RegexBuilder.swiftmodule/x86_64-apple-watchos-simulator.swiftmodule
 ./usr/lib/swift/watchsimulator/RegexBuilder.swiftmodule/i386-apple-watchos-simulator.swiftmodule
@@ -294,8 +284,6 @@
 ./usr/lib/swift/macosx/_StringProcessing.swiftmodule/arm64-apple-macos.swiftmodule
 ./usr/lib/swift/macosx/_StringProcessing.swiftmodule/x86_64-apple-macos.swiftmodule
 ./usr/lib/swift/macosx/Darwin.swiftmodule
-./usr/lib/swift/macosx/Darwin.swiftmodule/arm64-apple-macos.swiftmodule
-./usr/lib/swift/macosx/Darwin.swiftmodule/x86_64-apple-macos.swiftmodule
 ./usr/lib/swift/macosx/RegexBuilder.swiftmodule
 ./usr/lib/swift/macosx/RegexBuilder.swiftmodule/arm64-apple-macos.swiftmodule
 ./usr/lib/swift/macosx/RegexBuilder.swiftmodule/x86_64-apple-macos.swiftmodule
@@ -404,8 +392,6 @@
 ./usr/lib/swift/iphonesimulator/_StringProcessing.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
 ./usr/lib/swift/iphonesimulator/_StringProcessing.swiftmodule/arm64-apple-ios-simulator.swiftmodule
 ./usr/lib/swift/iphonesimulator/Darwin.swiftmodule
-./usr/lib/swift/iphonesimulator/Darwin.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
-./usr/lib/swift/iphonesimulator/Darwin.swiftmodule/arm64-apple-ios-simulator.swiftmodule
 ./usr/lib/swift/iphonesimulator/RegexBuilder.swiftmodule
 ./usr/lib/swift/iphonesimulator/RegexBuilder.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
 ./usr/lib/swift/iphonesimulator/RegexBuilder.swiftmodule/arm64-apple-ios-simulator.swiftmodule
```

**Pull request merged**
