### PR TITLE
Change the feature name for BuiltinTaskGroup.

### PR DESCRIPTION
**Pull request by DougGregor**
**Explanation**: Change a feature name so that `_Concurrency.swiftmodule/*-*-.swiftinterface` files from newer compilers can be parsed with older compilers and vice-versa.
**Scope**: Only affects inalienable code in the `_Concurrency` module.
**Radar/SR Issue**:  rdar://79561865
**Risk**: Low.
**Testing**: PR testing and CI on main.
**Original PR**: https://github.com/apple/swift/pull/38047

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please nominate

**Comment by DougGregor** [comment]
@swift-ci please nominate

**Review by tkremenek — APPROVED** [review]

**Pull request merged**
