### PR TITLE
Android toolchain

### PR DESCRIPTION
**Pull request by amraboelela**
https://bugs.swift.org/browse/SR-4443

Resolves [SR-4443](https://bugs.swift.org/browse/SR-4443).

### CODE REVIEW

**Comment by CodaFi** [comment]
Same here 

> Please rebase instead of pulling with a merge to clear out these superfluous commits.

**Comment by amraboelela** [comment]
It is: Copy ICU libs to toolchain

**Comment by amraboelela** [comment]
I rebased it to master

**Review by modocache — CHANGES_REQUESTED** [review]
The code change looks good, thanks @amraboelela! Two asks, though:

1. Could you get rid of the merge commit 82e1653aab021d7462abf2864010f9f46d49f950?
2. Could you provide a more detailed commit message? As I mentioned on #11404, I think it would be best if the commit message mentioned "Android", and explained why the change was necessary.

**Comment by amraboelela** [comment]
Made the required changes

**Comment by modocache** [comment]
@swift-ci please smoke test and merge

**Review by modocache — APPROVED** [review]
Thanks, @amraboelela! 💯

**Comment by milseman** [comment]
@swift-ci please smoke test and merge

**Comment by harlanhaskins** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
