### PR TITLE
Add support to skip watchOS 32-bit simulator by default

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci smoke test Linux

**Comment by shahmishal** [comment]
@swift-ci test macOS

**Comment by shahmishal** [comment]
@swift-ci Python lint

**Comment by shahmishal** [comment]
```
00:03:20.860 + ./utils/python_lint.py
00:03:25.777 ./test/attr/Inputs/access-note-gen.py:28:10: E127 continuation line over-indented for visual indent
00:03:25.777 ./test/attr/Inputs/access-note-gen.py:29:10: E127 continuation line over-indented for visual indent
```

Not related to this PR

**Comment by shahmishal** [comment]
@swift-ci smoke test Linux

**Comment by shahmishal** [comment]
@swift-ci test macOS

**Review by devmaximilian — APPROVED** [review]

**Comment by shahmishal** [comment]
Closing this PR in favor of https://github.com/apple/swift/pull/36694

**Pull request closed without merging**
