### PR TITLE
[ownership] Fix the eager specializer for ownership

### PR DESCRIPTION
**Pull request by gottesmm**
This is an in progress PR to fix the open coded part of the eager specializer for ownership now that the generic specializer itself is now fixed for OSSA.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test linux platform

**Review by atrick — COMMENTED** [review]
Look pretty good. I don't see test cases for
- the load_borrow code path
- the code path for a specializing a loadable, nontrivial generic type, where the members don't depend on the generic parameter

**Comment by gottesmm** [comment]
Those test cases are there. I just didn't put in explicit FileCheck checks. I'll add them.

**Comment by gottesmm** [comment]
@atrick I made it more explicit.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test source compatibility

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci test windows platform

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci test windows platform

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by gottesmm** [comment]
Compatibility failures I think are due to a swiftpm issue. The full linux test is failing in lldb in a way that can't be caused by this patch (I am not even running this in the pipeline yet).

**Pull request merged**
