### PR TITLE
[Foundation] Update & simplify class name stability check

### PR DESCRIPTION
**Pull request by lorentey**
Move the ObjC class name stability check logic to the Swift runtime, exposing it as a new SPI called _swift_isObjCTypeNameSerializable.

Update the reporting logic. The ObjC names of generic classes are considered stable now, but private classes and classes defined in function bodies or other anonymous contexts are unstable by design.

On the overlay side, rewrite the check’s implementation in Swift and considerably simplify it.

rdar://57809977

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci test macOS

**Comment by lorentey** [comment]
The test failures on macOS are expected (there is at least one logic error in the implementation and I haven't adjusted the tests yet) -- I was mostly curious about potential build errors on other platforms.

**Comment by lorentey** [comment]
@swift-ci please test Windows platform

**Comment by lorentey** [comment]
@swift-ci test

**Review by mikeash — APPROVED** [review]

**Review by jckarter — APPROVED** [review]
Looks good, thanks Karoy!

**Comment by lorentey** [comment]
@swift-ci test

**Pull request merged**
