### PR TITLE
[Threading] Add ConditionVariable support.

### PR DESCRIPTION
**Pull request by al45tair**
Swift Concurrency would like to be able to use condition variables. Add support to the threading packages.

rdar://100236038

### CODE REVIEW

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
@swift-ci Please test

**Review by mikeash — APPROVED** [review]

**Pull request merged**
