### PR TITLE
Update WindowsBuild.md

### PR DESCRIPTION
**Pull request by compnerd**
Explicitly use the path to python2.7 (although the tool can support python 3.x, the path is much much unwieldy as `"C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe"`

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @keith

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Review by keith — APPROVED** [review]
thanks!

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
