### PR TITLE
Fix uninitialized IRGenOptions field

### PR DESCRIPTION
**Pull request by beccadax**
apple/swift#42094 added a new `IRGenOptions::CompactAbsoluteFunctionPointer` field, but did not initialize it. We subsequently started seeing flaky test failures in LLDB tests that tried to resolve relocations in metadata, so we think this may have resulted in the option sometimes being set to `true` in the REPL.

Hopefully fixes rdar://91127507.

### CODE REVIEW

**Comment by beccadax** [comment]
@swift-ci smoke test and merge

**Comment by beccadax** [comment]
@kateinoigakukun

**Comment by JDevlieghere** [comment]
Thanks @beccadax!

**Comment by kateinoigakukun** [comment]
Thank you @beccadax 🙏

**Pull request merged**
