### PR TITLE
[cxx-interop] Add `std::span` tests

### PR DESCRIPTION
**Pull request by susmonteiro**
Creates a few simple tests for `std::span`.

### CODE REVIEW

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by susmonteiro** [comment]
@swift-ci please smoke test

**Review by egorzhdan — APPROVED** [review]
LGTM, thanks!

**Comment by susmonteiro** [comment]
@swift-ci please smoke test

**Comment by susmonteiro** [comment]
@swift-ci please smoke test

**Comment by susmonteiro** [comment]
@swift-ci please smoke test

**Comment by susmonteiro** [comment]
@swift-ci please smoke test

**Pull request merged**
