### PR TITLE
test: repair the test after #32355

### PR DESCRIPTION
**Pull request by compnerd**
Fix the tests that #32355 broke.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @nkcsgexi

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
Thank you, @compnerd ! Could you hold on fixing this after merging https://github.com/apple/swift/pull/32450? That PR has changed the same test.

**Comment by compnerd** [comment]
@nkcsgexi - the CI has been broken for ~24h now, I'd like to get CI fixed immediately.

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by stephentyrone** [comment]
Merging to unblock the Windows CI.

**Pull request merged**
