### PR TITLE
Revert "Regex literal runtime plumbing."

### PR DESCRIPTION
**Pull request by etcwilde**
This reverts https://github.com/apple/swift/pull/40487
Build failure: https://ci-external.swift.org/job/oss-swift-windows-x86_64-vs2019/7396/

```
C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1429~1.300\bin\Hostx64\x64\cl.exe  /nologo /TP -DCMARK_STATIC_DEFINE -DGTEST_HAS_RTTI=0 -DLLVM_ON_WIN32 -DSWIFT_LLVM_SUPPORT_IS_AVAILABLE -DUNICODE -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_CRT_USE_WINAPI_FAMILY_DESKTOP_APP -D_DLL -D_ENABLE_ATOMIC_ALIGNMENT_FIX -D_ENABLE_EXTENDED_ALIGNED_STORAGE=1 -D_HAS_EXCEPTIONS=0 -D_HAS_STATIC_RTTI=0 -D_MD -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -D_UNICODE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Ilib\SILGen -IC:\Users\swift-ci\jenkins\workspace\oss-swift-windows-x86_64-vs2019\swift\lib\SILGen -Iinclude -IC:\Users\swift-ci\jenkins\workspace\oss-swift-windows-x86_64-vs2019\swift\include -IC:\Users\swift-ci\jenkins\workspace\oss-swift-windows-x86_64-vs2019\llvm-project\llvm\include -IT:\llvm\include -IC:\Users\swift-ci\jenkins\workspace\oss-swift-windows-x86_64-vs2019\llvm-project\clang\include -IT:\llvm\tools\clang\include -IC:\Users\swift-ci\jenkins\workspace\oss-swift-windows-x86_64-vs2019\cmark\src -IT:\cmark\src -IC:\Users\swift-ci\jenkins\workspace\oss-swift-windows-x86_64-vs2019\swift-corelibs-libdispatch\src\BlocksRuntime -IC:\Users\swift-ci\jenkins\workspace\oss-swift-windows-x86_64-vs2019\swift-corelibs-libdispatch -I"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\\include" -I"C:\Program Files (x86)\Windows Kits\10\\Include\10.0.17763.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\10\\Include\10.0.17763.0\shared" -I"C:\Program Files (x86)\Windows Kits\10\\Include\10.0.17763.0\um" /GS- /Oy /Zc:inline /Zc:__cplusplus /Zc:strictStrings /Oi /Zc:rvalueCast /bigobj /W4 -wd4141 -wd4146 -wd4244 -wd4267 -wd4291 -wd4351 -wd4456 -wd4457 -wd4458 -wd4459 -wd4503 -wd4624 -wd4722 -wd4100 -wd4127 -wd4512 -wd4505 -wd4610 -wd4510 -wd4702 -wd4245 -wd4706 -wd4310 -wd4701 -wd4703 -wd4389 -wd4611 -wd4805 -wd4204 -wd4577 -wd4091 -wd4592 -wd4319 -wd4709 -wd4324 -w14062 -we4238 /Gw /we4062 /wd4068 /permissive- -DOBJC_OLD_DISPATCH_PROTOTYPES=0 /O2 /Ob2  /MD -MD  /EHs-c- /GR- -UNDEBUG -O2 /GR- -U_DEBUG -std:c++14 /showIncludes /Folib\SILGen\CMakeFiles\swiftSILGen.dir\SILGenApply.cpp.obj /Fdlib\SILGen\CMakeFiles\swiftSILGen.dir\swiftSILGen.pdb /FS -c C:\Users\swift-ci\jenkins\workspace\oss-swift-windows-x86_64-vs2019\swift\lib\SILGen\SILGenApply.cpp
C:\Users\swift-ci\jenkins\workspace\oss-swift-windows-x86_64-vs2019\swift\lib\SILGen\SILGenApply.cpp(1913): error C2668: 'swift::Lowering::PreparedArguments::PreparedArguments': ambiguous call to overloaded function
C:\Users\swift-ci\jenkins\workspace\oss-swift-windows-x86_64-vs2019\swift\lib\SILGen\ArgumentSource.h(307): note: could be 'swift::Lowering::PreparedArguments::PreparedArguments(swift::Lowering::PreparedArguments &&)'
C:\Users\swift-ci\jenkins\workspace\oss-swift-windows-x86_64-vs2019\swift\lib\SILGen\ArgumentSource.h(294): note: or       'swift::Lowering::PreparedArguments::PreparedArguments(llvm::ArrayRef<swift::AnyFunctionType::Param>)'
C:\Users\swift-ci\jenkins\workspace\oss-swift-windows-x86_64-vs2019\swift\lib\SILGen\SILGenApply.cpp(1913): note: while trying to match the argument list '(initializer list)'
```

### CODE REVIEW

**Comment by etcwilde** [comment]
@swift-ci please test

**Review by rxwei — APPROVED** [review]

**Comment by rxwei** [comment]
Here's a fix https://github.com/apple/swift/pull/40510.

**Comment by etcwilde** [comment]
> Here's a fix #40510.

I’ll close this one once that merges.

**Comment by etcwilde** [comment]
Windows main/PR testing is green as of merging #40510.
Closing.

**Pull request closed without merging**
