### PR TITLE
stdlib: map `wchar_t` to `UInt16` on Windows

### PR DESCRIPTION
**Pull request by compnerd**
This is an ABI breaking change for Windows.  `WCHAR` on Windows is mapped to `short` (`-fshort-wchar` makes it `unsigned short`).  When C++ interop is enabled, `WCHAR` will be mapped to `wchar_t` which is then mapped to `short` (or `unsigned short` if `-fshort-wchar` is specified). Correct the mapping type to get the desired behaviour.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by DougGregor** [comment]
Pity that `wchar_t` is 16 bits on Windows vs. 32-bit elsewhere, because it'll be harder to write portable code with `CWideChar`... but this is the right fix. Thank you!

**Comment by compnerd** [comment]
@DougGregor yeah, `wchar_t` and `long` are the two types that differ.  For the case of `long` I think that we can avoid the issue by not mapping `Int` to `long` on Linux and Windows (sadly the ship has sailed for Apple platforms).

**Comment by compnerd** [comment]
CC: @lorentey @glessard

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test

**Pull request merged**
