### PR TITLE
[SR-2409] Rephrase diagnostic to consider Objective-C interop

### PR DESCRIPTION
**Pull request by d-ronnqvist**
This PR picks up where [rephrase diagnostic #4587](https://github.com/apple/swift/pull/4587) left off, looking at the value of `EnableObjCInterop` to choose between "C" and "Objective-C" as suggested by [jrose-apple](https://github.com/jrose-apple) (in the conversation of that PR).

It updates one of the tests to check for different results on macOS and on Linux, similar to the 32/64-bit example in the [Testing Swift document](https://github.com/apple/swift/blob/master/docs/Testing.rst).

Resolves [SR-2409](https://bugs.swift.org/browse/SR-2409).

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by d-ronnqvist** [comment]
From the test output it looks like `%target-os` was "linux-gnu" making the check prefix expression: 
```
--check-prefix=CHECK-linux-gnu
```

This is different than what's listed in the [Testing Swift document](https://github.com/apple/swift/blob/master/docs/Testing.rst), which is `macosx`, `darwin`, `linux`, `freebsd`, `windows-cygnus`, `windows-gnu`.

**Comment by d-ronnqvist** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
Ah, could you use `--check-prefix=CHECK-%target-runtime` ?
It will be substituted by `CHECK-objc`(for macOS, iOS etc) or `CHECK-native` (for Linux, etc.)

**Comment by d-ronnqvist** [comment]
Yes. That's probably closer to what I had intended.

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
Looks great. Thanks, David!

**Pull request merged**
