### PR TITLE
[TBDGen] support targets instead of arch&platform

### PR DESCRIPTION
**Pull request by cyndyishida**
Should be paired with https://github.com/apple/llvm-project/pull/64

second half of resolving rdar://problem/56727346

### CODE REVIEW

**Comment by cyndyishida** [comment]
Please test with following PR:
https://github.com/apple/llvm-project/pull/64

@swift-ci Please test

**Comment by cyndyishida** [comment]
it's possible this build failure comes from some configuration issue, maybe since its testing against the `llvm-project/apple/stable/20190619` branch 
```
12:36:28 CMake Error at /Applications/CMake.app/Contents/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
12:36:28   Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR)
12:36:28 Call Stack (most recent call first):
12:36:28   /Applications/CMake.app/Contents/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
12:36:28   /Applications/CMake.app/Contents/share/cmake-3.10/Modules/FindSWIG.cmake:63 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
12:36:28   scripts/CMakeLists.txt:16 (find_package)
12:36:28 
12:36:28 
12:36:28 -- Configuring incomplete, errors occurred!
12:36:28 See also "/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/lldb-macosx-x86_64/CMakeFiles/CMakeOutput.log".
12:36:28 See also "/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/buildbot_incremental/lldb-macosx-x86_64/CMakeFiles/CMakeError.log".
12:36:28 Building the standard library for: swift-stdlib-macosx-x86_64 swift-stdlib-iphonesimulator-i386 swift-stdlib-iphonesimulator-x86_64 swift-stdlib-iphoneos-armv7 swift-stdlib-iphoneos-armv7s swift-stdlib-iphoneos-arm64 swift-stdlib-appletvsimulator-x86_64 swift-stdlib-appletvos-arm64 swift-stdlib-watchsimulator-i386 swift-stdlib-watchos-armv7k
12:36:28 Running Swift tests for: check-swift-validation-macosx-x86_64 check-swift-validation-iphonesimulator-i386 check-swift-validation-iphonesimulator-x86_64 check-swift-validation-appletvsimulator-x86_64 check-swift-validation-watchsimulator-i386
12:36:28 /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/utils/build-script: fatal error: command terminated with a non-zero exit status 1, aborting
12:36:28 /Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/utils/build-script: fatal error: command terminated with a non-zero exit status 1, aborting
12:36:28 Build step 'Execute shell' marked build as failure
12:36:29 INFO: Starting to record.
12:36:29 INFO: Processing JUnit
12:36:32 ERROR: Step ‘Publish xUnit test result report’ failed: [JUnit] - No test report file(s) were found with the pattern 'branch-master/buildbot_incremental/swift-macosx-x86_64/swift-test-results/**/*.xml' relative to '/Users/buildnode/jenkins/workspace/swift-PR-osx' for the testing framework 'JUnit'.
12:36:32 Did you enter a pattern relative to (and within) the workspace directory?
12:36:32 Did you generate the result report(s) for 'JUnit'?"
```

**Comment by cyndyishida** [comment]
Please test with following PR:
https://github.com/apple/llvm-project/pull/71

@swift-ci Please test

**Comment by cyndyishida** [comment]
Please test with following PR:
apple/llvm-project#71

@swift-ci Please test

**Review by harlanhaskins — APPROVED** [review]
Thank you!

**Pull request merged**
