### PR TITLE
[Frontend] Enable type wrapper feature by default for testing

### PR DESCRIPTION
**Pull request by xedin**
A PR to obtain a toolchain with type wrappers enabled.

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please build toolchain macOS platform

**Comment by xedin** [comment]
@swift-ci please build toolchain macOS

**Comment by xedin** [comment]
@swift-ci please build toolchain macOS

**Comment by phausler** [comment]
The following configuration crashes in SIL verification:
```
@typeWrapper
struct WrappedSelfContainingStorageTests<W, S> {
  var storage: S
  init(for: W.Type, storage: S) {
    self.storage = storage
  }
  
  subscript<V>(propertyKeyPath _: KeyPath<W, V>, storageKeyPath path: KeyPath<S, V>) -> V {
    get { fatalError() }
    set { }
  }
  
  subscript<V>(propertyKeyPath _: KeyPath<W, V>, storageKeyPath path: WritableKeyPath<S, V>) -> V {
    get { fatalError() }
    set { }
  }
  
  subscript<V>(wrappedSelf w: W, propertyKeyPath _: KeyPath<W, V>, storageKeyPath path: WritableKeyPath<S, V>) -> V {
    get { fatalError() }
    set { }
  }
  
  subscript<V>(wrappedSelf w: W, propertyKeyPath _: KeyPath<W, V>, storageKeyPath path: KeyPath<S, V>) -> V {
    get { fatalError() }
  }
}


@WrappedSelfContainingStorageTests
final class Test {
  var baz: String = "asdf"
}
```

With the failure of:
```
Write:   store %2 to [init] %11 : $*Test                 // id: %12
SIL verification failed: Found load borrow that is invalidated by a local write?!: loadBorrowImmutabilityAnalysis.isImmutable(LBI)
Verifying instruction:
     %6 = begin_access [read] [dynamic] %5 : $*WrappedSelfContainingStorageTests<Test, Test.$Storage> // users: %21, %7
->   %7 = load_borrow %6 : $*WrappedSelfContainingStorageTests<Test, Test.$Storage> // users: %20, %10
     %10 = store_borrow %7 to %9 : $*WrappedSelfContainingStorageTests<Test, Test.$Storage> // users: %17, %14
     end_borrow %7 : $WrappedSelfContainingStorageTests<Test, Test.$Storage> // id: %20
In function:
// Test.baz.getter
sil [ossa] @$s19UpdatedTypeWrappers4TestC3bazSSvg : $@convention(method) (@guaranteed Test) -> @owned String {
// %0 "self"                                      // users: %5, %2, %1
bb0(%0 : @guaranteed $Test):
  debug_value %0 : $Test, let, name "self", argno 1, implicit // id: %1
  %2 = copy_value %0 : $Test                      // user: %12
  %3 = keypath $KeyPath<Test, String>, (root $Test; settable_property $String,  id @$s19UpdatedTypeWrappers4TestC3bazSSvg : $@convention(method) (@guaranteed Test) -> @owned String, getter @$s19UpdatedTypeWrappers4TestC3bazSSvpACTK : $@convention(thin) (@in_guaranteed Test) -> @out String, setter @$s19UpdatedTypeWrappers4TestC3bazSSvpACTk : $@convention(thin) (@in_guaranteed String, @in_guaranteed Test) -> ()) // users: %24, %14
  %4 = keypath $WritableKeyPath<Test.$Storage, String>, (root $Test.$Storage; stored_property #Test.$Storage.baz : $String) // users: %23, %14
  %5 = ref_element_addr %0 : $Test, #Test.$storage // user: %6
  %6 = begin_access [read] [dynamic] %5 : $*WrappedSelfContainingStorageTests<Test, Test.$Storage> // users: %21, %7
  %7 = load_borrow %6 : $*WrappedSelfContainingStorageTests<Test, Test.$Storage> // users: %20, %10
  %8 = alloc_stack $String                        // users: %22, %19, %14
  %9 = alloc_stack $WrappedSelfContainingStorageTests<Test, Test.$Storage> // users: %18, %10
  %10 = store_borrow %7 to %9 : $*WrappedSelfContainingStorageTests<Test, Test.$Storage> // users: %17, %14
  %11 = alloc_stack $Test                         // users: %16, %15, %14, %12
  store %2 to [init] %11 : $*Test                 // id: %12
  // function_ref WrappedSelfContainingStorageTests.subscript.getter
  %13 = function_ref @$s19UpdatedTypeWrappers33WrappedSelfContainingStorageTestsV07wrappedE015propertyKeyPath07storagekL0qd__x_s0kL0Cyxqd__Gs08WritablekL0Cyq_qd__Gtcluig : $@convention(method) <τ_0_0, τ_0_1><τ_1_0> (@in_guaranteed τ_0_0, @guaranteed KeyPath<τ_0_0, τ_1_0>, @guaranteed WritableKeyPath<τ_0_1, τ_1_0>, @in_guaranteed WrappedSelfContainingStorageTests<τ_0_0, τ_0_1>) -> @out τ_1_0 // user: %14
  %14 = apply %13<Test, Test.$Storage, String>(%8, %11, %3, %4, %10) : $@convention(method) <τ_0_0, τ_0_1><τ_1_0> (@in_guaranteed τ_0_0, @guaranteed KeyPath<τ_0_0, τ_1_0>, @guaranteed WritableKeyPath<τ_0_1, τ_1_0>, @in_guaranteed WrappedSelfContainingStorageTests<τ_0_0, τ_0_1>) -> @out τ_1_0
  destroy_addr %11 : $*Test                       // id: %15
  dealloc_stack %11 : $*Test                      // id: %16
  end_borrow %10 : $*WrappedSelfContainingStorageTests<Test, Test.$Storage> // id: %17
  dealloc_stack %9 : $*WrappedSelfContainingStorageTests<Test, Test.$Storage> // id: %18
  %19 = load [take] %8 : $*String                 // user: %25
  end_borrow %7 : $WrappedSelfContainingStorageTests<Test, Test.$Storage> // id: %20
  end_access %6 : $*WrappedSelfContainingStorageTests<Test, Test.$Storage> // id: %21
  dealloc_stack %8 : $*String                     // id: %22
  destroy_value %4 : $WritableKeyPath<Test.$Storage, String> // id: %23
  destroy_value %3 : $KeyPath<Test, String>       // id: %24
  return %19 : $String                            // id: %25
} // end sil function '$s19UpdatedTypeWrappers4TestC3bazSSvg'
```

**Comment by xedin** [comment]
@swift-ci build toolchain macOS

**Comment by xedin** [comment]
@atrick could you please advice on what is actually going on with that verifier failure?

**Comment by meg-gupta** [comment]
@swift-ci build toolchain macOS

**Comment by xedin** [comment]
@swift-ci build toolchain macOS

**Comment by xedin** [comment]
@swift-ci clean build toolchain macOS

**Comment by xedin** [comment]
@swift-ci build clean toolchain macOS

**Comment by xedin** [comment]
@swift-ci build toolchain macOS

**Comment by xedin** [comment]
@swift-ci please build toolchain macOS

**Comment by xedin** [comment]
@swift-ci please build toolchain macOS

**Comment by xedin** [comment]
@swift-ci please build toolchain macOS

**Comment by xedin** [comment]
@swift-ci please build toolchain macOS platform

**Pull request closed without merging**
