### PR TITLE
incrparse: move include to top

### PR DESCRIPTION
**Pull request by compnerd**
Address feedback from ahoppen.  NFC.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @ahoppen - style change as you requested

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Review by ahoppen — APPROVED** [review]
Thanks!

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Pull request merged**
