### PR TITLE
[stdlib] NFC: Restore doc comment for Unsafe[Mutable]BufferPointer

### PR DESCRIPTION
**Pull request by krilnon**
Moves a `//` comment up above a `///` documentation comment, since the latter needs to be attached directly to the declaration or it won't be picked up as documentation.

### CODE REVIEW

**Comment by krilnon** [comment]
@swift-ci please smoke test

**Comment by krilnon** [comment]
I’m fine with that approach too, Ben. My goal here is just to bring the documentation back; hopefully someone more familiar with the status of the FIXME can comment on whether it’s best to move or remove the comment.

**Review by glessard — APPROVED** [review]
I agree that we can remove this `FIXME`. ABI stability makes the change suggested here untenable, therefore removing it is the right thing to do.

**Comment by glessard** [comment]
@swift-ci please smoke test and merge

**Comment by glessard** [comment]
macOS smoke test failed on a `lipo` call; will try again later.

**Comment by glessard** [comment]
@swift-ci please smoke test and merge

**Comment by krilnon** [comment]
@swift-ci please smoke test and merge

**Comment by krilnon** [comment]
@glessard Made one in #63362; let me know if anything looks off about the structure/reviewers, etc. Haven't done the release cherry-pick thing before.

**Comment by glessard** [comment]
Looks okay. Restating the purpose wouldn't be amiss, especially since the original description for this one has become out of date.

**Pull request merged**
