### PR TITLE
[Refactoring] Fix invalid legacy body for Result<Void, ...> handler

### PR DESCRIPTION
**Pull request by bnbarham**
When adding an async alternative for a function with a `(Result<Void,
...>) -> Void` completion handler, the legacy body was adding a call to
the handler with `.success(result)`. We don't assign to `result` for
Void handlers, so pass `()` instead.

Resolves rdar://81829392

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Review by ahoppen — APPROVED** [review]
We really should try and only use `refactor-check-compiles` tests, which would have caught the issue…

**Comment by bnbarham** [comment]
> We really should try and only use `refactor-check-compiles` tests, which would have caught the issue…

Good point, I didn't even notice that we weren't. I assume the majority of these were added before it existed? I'll convert these now in a separate commit (and put the unrelated _ change with it).

**Review by hamishknight — APPROVED** [review]
Good catch!

**Comment by bnbarham** [comment]
Updated all the tests in convert_function.swift to compile as well. For the tests that weren't checking the legacy body I also changed to -convert-to-async.

Also noticed that we already had the `Task { ... }` checks in `basic.swift`, just none for the `Result` case so I added that one and removed the `Task { ... }` from `convert_function.swift`.

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
@swift-ci please test

**Pull request merged**
