### PR TITLE
Move the similar function merging pass into the LLVM repo

### PR DESCRIPTION
**Pull request by vedantk**
This makes it easier to experiment with function merging in clang.

This set of PRs just does pure code movement.

Depends on:
https://github.com/apple/swift-llvm/pull/123
https://github.com/apple/swift-clang/pull/231

rdar://45707083

### CODE REVIEW

**Comment by vedantk** [comment]
apple/swift-llvm#123
apple/swift-clang#231
@swift-ci please smoke test

**Comment by aschwaighofer** [comment]
LGTM

**Review by eeckstein — APPROVED** [review]
lgtm!

**Comment by vedantk** [comment]
apple/swift-llvm#123
apple/swift-clang#231
@swift-ci please smoke test

**Comment by vedantk** [comment]
apple/swift-llvm#123
apple/swift-clang#231
@swift-ci please smoke test

**Comment by vedantk** [comment]
@eeckstein @aschwaighofer thanks for the reviews!

Here's my plan for landing this:
1) Commit the llvm & clang parts to github/upstream-with-swift, then cherry-pick to swift-5.0-branch.
2) Wait until the changes are auto-merged into the swift-{llvm,clang}/stable branches. This can't be forced -- those branches are gated.
3) Merge this PR to delete swift's copy of the pass.

Does that sound right?

**Comment by vedantk** [comment]
On second thought, it might be more difficult to maintain a copy of this pass in the upstream-with-swift branch, as it would require more effort to keep it in sync with llvm.org. Let's wait until we can really upstream this pass to do this.

**Pull request closed without merging**
