### PR TITLE
[gardening] Add missing comments

### PR DESCRIPTION
**Pull request by danra**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by gottesmm** [comment]
This commit does not match LLVM style. Can you fix the namespace/c++ comment issue like in the other commits I commented on?

**Comment by gottesmm** [comment]
This LGTM.

**Comment by gottesmm** [comment]
BTW: In the future @danra, can you rebase these changes. I should have told you to do this, but I forgot.

**Comment by danra** [comment]
Sure

**Pull request merged**
