### PR TITLE
[cmake] Use a helper macro to simplify adding sources to the SILOptim…

### PR DESCRIPTION
**Pull request by gottesmm**
…izer library.

All this does is automate the creation of the ${DIRNAME}_SOURCES variables that we already create and allows for the author to avoid having to prefix with the directory name, i.e.:

set(FOOBAR_SOURCES
  FooBar/Source.cpp
  PARENT_SCOPE)

=>

silopt_register_sources(
  Source.cpp)

Much easier and cleaner to read. I put the code that implements this in the
CMakeLists.txt file just for the SILOptimizer.

----

I have been meaning to do this for a minute. Finally got around to it.

### CODE REVIEW

**Review by eeckstein — APPROVED** [review]

**Comment by gottesmm** [comment]
Just cleaning up my branches.

**Comment by gottesmm** [comment]
Fixed the remaining cmake issues. I was doing something stupid = (.

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Pull request merged**
