### PR TITLE
[5.1] [IRGen] Emit lazy opaque type descriptors.

### PR DESCRIPTION
**Pull request by DougGregor**
These were recorded but never emitted. Fixes rdar://problem/50258536.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test and merge

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
It looks like we have a Clang-related problem:

```
10:56:21 Failing Tests (29):
10:56:21     Swift(linux-x86_64) :: Serialization/xref-nested-clang-type.swift
10:56:21     Swift(linux-x86_64) :: SILGen/objc_bridged_block_optionality_diff.swift
10:56:21     Swift(linux-x86_64) :: SILGen/objc_bridged_generic_conformance.swift
10:56:21     Swift(linux-x86_64) :: SILGen/lying_about_optional_return_objc.swift
10:56:21     Swift(linux-x86_64) :: IRGen/related_entity.sil
10:56:21     Swift(linux-x86_64) :: IRGen/objc_properties_jit.swift
10:56:21     Swift(linux-x86_64) :: IRGen/objc_generic_protocol_conformance.swift
10:56:21     Swift(linux-x86_64) :: IRGen/objc_properties_imported.swift
10:56:21     Swift(linux-x86_64) :: IRGen/objc_int_encoding.sil
10:56:21     Swift(linux-x86_64) :: IRGen/objc_bridged_generic_conformance.swift
10:56:21     Swift(linux-x86_64) :: IRGen/objc_factory_method.sil
10:56:21     Swift(linux-x86_64) :: IRGen/class_resilience_objc.swift
10:56:21     Swift(linux-x86_64) :: Frontend/dependencies.swift
10:56:21     Swift(linux-x86_64) :: ClangImporter/objc_parse_verifier.swift
10:56:21     Swift(linux-x86_64) :: ClangImporter/objc_diags.swift
10:56:21     Swift(linux-x86_64) :: ClangImporter/ctypes_parse_objc.swift
10:56:21     Swift(linux-x86_64) :: ClangImporter/bad-ns-extensible-string-enum.swift
10:56:21     Swift(linux-x86_64) :: ClangImporter/no-import-objc.swift
10:56:21     Swift(linux-x86_64) :: ClangImporter/enum-error-redeclared.swift
10:56:21     Swift(linux-x86_64) :: ClangImporter/enum-dataflow.swift
10:56:21     Swift(linux-x86_64) :: ClangImporter/import-as-member-objc.swift
10:56:21     Swift(linux-x86_64) :: ClangImporter/nullability.swift
10:56:21     Swift(linux-x86_64) :: ClangImporter/attr-objc_subclassing_restricted.swift
10:56:21     Swift(linux-x86_64) :: ClangImporter/MixedSource/mixed-target-using-header.swift
10:56:21     Swift(linux-x86_64) :: ClangImporter/MixedSource/Xcc_include.swift
10:56:21     Swift(linux-x86_64) :: ClangImporter/MixedSource/resolve-cross-language.swift
10:56:21     Swift(linux-x86_64) :: ClangImporter/MixedSource/import-mixed-with-header-twice.swift
10:56:21     Swift(linux-x86_64) :: ClangImporter/MixedSource/mixed-target-using-header-swift4.swift
10:56:21     Swift(linux-x86_64) :: ClangImporter/MixedSource/mixed-target-using-module.swift
```

**Comment by DougGregor** [comment]
@swift-ci please test Linux

**Review by jckarter — APPROVED** [review]
🤦🏻‍♂️ Thanks!

**Comment by DougGregor** [comment]
@swift-ci please test Linux

**Pull request merged**
