### PR TITLE
[benchmark] Driver Improvements

### PR DESCRIPTION
**Pull request by palimondo**
This PR adds 3 features to the benchmark driver:
1)  **`--min-samples`** attribute to specify minimal number of samples to gather.
2) **`--meta`** option to log measurement metadata in the benchmark summary (along with corresponding support for parsing such log format):
    * number of memory **pages** used,
    * number of **involuntary context switches**,
    * number of voluntary **yields**.
3) Support for running benchmarks using substring filters: 
    * Positional arguments prefixed with a single + or - sign are interpreted as benchmark name filters. Executes all benchmarks whose names include any of the strings prefixed with a plus sign but none of the strings prefixed with a minus sign.'

Example:
````
$ ./Benchmark_O --num-iters=1 --quantile=4 --meta +Angry -Small
#,TEST,SAMPLES,MIN(μs),Q1(μs),Q2(μs),Q3(μs),MAX(μs),PAGES,ICS,YIELD
2,AngryPhonebook,200,6762,6846,6846,6881,17178,11,161,22
3,AngryPhonebook.ASCII,200,1840,1859,1866,1885,2929,18,355,50
5,AngryPhonebook.Armenian,200,678,684,690,697,1290,46,384,15
7,AngryPhonebook.Cyrillic,200,668,674,682,701,1804,53,552,15
9,AngryPhonebook.Strasse,200,610,612,621,628,4360,56,632,14

Total performance tests executed: 5
````

### Motivation
The support for running benchmarks using substring filter is meant as an alternative to running benchmarks using `tags` (and `skip-tags`). Maybe if we consistently applied the benchmark naming convention to the whole Swift Benchmark Suite, the tags could be retired? Let's see how we'll like that in practice…

I'd like to further experiment with the measurement process to find a better balance between runtime and robustness of measurement by doing parallel benchmarking. The `--meta` option surfaces the key data about the quality of measurement environment, without the need to resort to the much more expensive `--verbose` mode. The `--min-samples` controls the minimal sample size for a proper statistical analysis, so that we could rely more on `--sample-time` (when measuring with `--num-samples=1`), without needing to set it too high in order to get enough data from the worst cases (slow benchmarks).

Best reviewed by [individual commits](https://github.com/apple/swift/pull/26303/commits/ad24ca4ba6734f98d1e0fc34fbbf3114d3c47aa9).

### CODE REVIEW

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
@swift-ci please test

**Comment by palimondo** [comment]
@swift-ci please benchmark

**Comment by palimondo** [comment]
I’m re-running the benchmarks to see if the reported false changes are stable across the runs or random (I hope). I suspect the instability is caused by the small sample size, since the `run_smoke_bench` is in the end doing just `--nun-samples=10`. My working theory is that this is too small a sample, ergo the need to gather larger samples. It’s possible some
benchmarks are not reaching a steady performance state during such brief sampling.

**Comment by palimondo** [comment]
Hrm… stable change. @eeckstein, do you have some theory that could explain this?

**Comment by eeckstein** [comment]
Some benchmarks are just unstable. We should consider disabling them

**Review by eeckstein — APPROVED** [review]

**Comment by palimondo** [comment]
I have #20552 open that would address the `FlattenListFlatMap`, FWIW. But I have a hard time accepting the “Some benchmarks are just unstable” thesis without understanding the reason behind it. I’ll try to examine `Dictionary4` in more detail once I’m back from dog walk. (You’re responding in an atypical time for you… vacation?)

**Comment by palimondo** [comment]
Looking at the stability of benchmark results during measurement, I would not call `Dictionary4` unstable in any way, but it seems to [pop-up from time to time](https://github.com/apple/swift/pulls?utf8=%E2%9C%93&q=is%3Apr+Dictionary4) in CI reports. Most recently [here above](https://github.com/apple/swift/pull/26303#issuecomment-514470098), then [16 days ago](https://github.com/apple/swift/pull/25985#issuecomment-508885460), [20 days ago](https://github.com/apple/swift/pull/25309#issuecomment-508241673), before than [back in May](https://github.com/apple/swift/pull/24765#issuecomment-492426643)...

@lorentey, maybe you have some idea to explain the 23–26% jumps in [`Dictionary4`](https://github.com/apple/swift/blob/master/benchmark/single-source/DictTest4.swift) performance? It seems it is triggered by some code alignment when the binary size changes. The benchmark seems to stress the automatic hashable conformance of a large key.

**Pull request merged**
