### PR TITLE
[CS] Some more NFC changes

### PR DESCRIPTION
**Pull request by hamishknight**
Split a couple more changes off #63963

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Review by xedin — APPROVED** [review]

**Comment by AnthonyLatsis** [comment]
@hamishknight Why is `SyntacticElementTarget` a better name than `SolutionApplicationTarget`?

**Comment by xedin** [comment]
Mostly consistency, we have SyntacticElement{ConstraintGenerator, SolutionApplication} and it makes sense to move away from "solution application" because it's a solver target as well.

**Comment by xedin** [comment]
> Also, isn’t SyntacticElementConstraintGenerator used for stuff inside closures only, unlike SyntacticElementTarget? 

No, it's not only for closures, it could be used in any supported context which includes function/accessor declarations and if/switch expressions and soon string interpolations.

I personally don't like `TypeCheck` in the name because I think it's important to maintain distinction that this type is part of the constraint solver.

**Comment by AnthonyLatsis** [comment]
Maybe `ConstraintSystemTarget` then?

**Comment by xedin** [comment]
I suggested `ConstraintSolverTarget` before but it seems kind of tautological...

**Comment by AnthonyLatsis** [comment]
> I suggested `ConstraintSolverTarget` before but it seems kind of tautological...

Totally works for me as well. There is no `ConstraintSolver` type but I don’t think that hurts clarity of purpose. I’m not sure I catch on to the tautology though: I see a clear separation between stuff that does the solving (action) and the thing + context data acted upon.

**Pull request merged**
