### PR TITLE
[nfc] [ownership] move ownership checks to visitors in sil combine

### PR DESCRIPTION
**Pull request by zoecarver**
I'm going to update one visitor at a time to support ownership. This patch updates _all_ the visitors to bail on ownership (except for the non-ossa instructions).

### CODE REVIEW

**Comment by zoecarver** [comment]
@swift-ci please smoke test.

**Comment by gottesmm** [comment]
Can you put an assert that we are not visiting something with ownership in visitReleaseValueInst? visitRetainValueInst? visitStrongRetainInst, visitStrongReleaseInst. This is more of a documentation that the code is expecting non-ossa code.

In a forthcoming commit, can you get rid of those simple nullptr visitors as well?

After that LGTM.

**Comment by zoecarver** [comment]
@gottesmm updated. I'll make a patch for the nullptr fix.

**Comment by zoecarver** [comment]
@swift-ci please smoke test and merge.

**Comment by zoecarver** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
