### PR TITLE
[interop] do not import functions whose return type is not imported

### LINKED ISSUE #64401: [interop] C++ function returning `NonCopyable` type returns `Never` in Swift and is callable
This code:

```c++
struct NonCopyable {
    NonCopyable(const NonCopyable &) = delete;
    
    int x;
};

NonCopyable returnsNoncopyable();
```

Produces callable `returnsNoncopyable` function in Swift module interface that returns `Never`:

```swift
func returnsNoncopyable() -> Never
```

This function is callable, and doesn't result in an error unless the return value is attempted to be used.

### PR DESCRIPTION
**Pull request by hyp**
Resolves #64401

### CODE REVIEW

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test source compatibility

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please smoke test linux

**Comment by hyp** [comment]
@swift-ci please test macOS platform

**Review by egorzhdan — APPROVED** [review]

**Pull request merged**
