### PR TITLE
[transferring] Make transferring conditionally suppressible and validate that we do suppress transferring in swift interface files.

### PR DESCRIPTION
**Pull request by gottesmm**
Importantly I added tests that validated this behavior.

rdar://126780823

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Review by tshortli — APPROVED** [review]
Thanks!

**Comment by tshortli** [comment]
If a lot of existing APIs are going to adopt `transferring`, we may want to invert this by always printing a suppressed alternative so that we don't accidentally make APIs disappear by adopting transferring and forgetting `@_allowFeatureSuppression`. Is there a motivation for only conditionally printing suppressed alternatives? The `@_disallowFeatureSuppression` attribute exists for edge cases where we need to hide the alternatives.

**Comment by gottesmm** [comment]
For anyone listening in, @tshortli and I touched base offline and agreed that it made sense to not conditionally suppress and just suppress.

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Review by tshortli — APPROVED** [review]

**Pull request merged**
