### PR TITLE
[DI] Add a way to determine full initialization points

### PR DESCRIPTION
**Pull request by xedin**
Logic that used to determine where `self` is completely initialized to inject 
actor hops has been generalized and is now available via 
`findFullInitializationPoints` method.

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Review by kavon — APPROVED** [review]
looks good nice refactoring

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Pull request merged**
