### PR TITLE
Collate Codable failure diagnostics

### PR DESCRIPTION
**Pull request by itaiferber**
**What's in this pull request?**
Codable failures produced diagnostics and notes explaining what failed during synthesis. These diagnostics were being output as they were generated, which was suboptimal because it meant that NOTEs could be produced before the error they were related to.

This was bad for consumers like Xcode, which associate NOTEs with the last error or warning diagnostic. If the only error in produced was a diagnostic from Codable synthesis, the initial NOTEs would be lost in the Xcode UI.

This collates these notes using a diagnostic transaction and only outputs the errors if something actually goes wrong.

### CODE REVIEW

**Comment by itaiferber** [comment]
@swift-ci Please test

**Comment by itaiferber** [comment]
@swift-ci Please test macOS

**Comment by itaiferber** [comment]
Looks like unrelated test failure in `decl/protocol/conforms/fixit_stub_editor.swift`.

**Comment by itaiferber** [comment]
@swift-ci Please test macOS

**Comment by itaiferber** [comment]
@nkcsgexi Looks like you added the availability here that's causing the test failure (`a2e5910efa6024be4a0a66d3223195eae4f27ead`). Is this expected?

**Comment by itaiferber** [comment]
@swift-ci Please test macOS

**Review by parkera — APPROVED** [review]
I'll leave the detailed compiler review to @jrose-apple but the rest looks good to me.

**Comment by jrose-apple** [comment]
This needs a test, probably using FileCheck so that the order of diagnostics is checked. I don't think I've seen DiagnosticTransaction used this way either; I'd personally prefer to collect callbacks or something instead. @DougGregor, what do you think?

**Comment by DougGregor** [comment]
A `FileCheck` test would be good, to make sure the order doesn't break. 

We don't currently have anything that uses`DiagnosticTransaction` specifically this way, but it seems reasonable and easily fits the LIFO constraint of `DiagnosticTransaction`.

**Comment by itaiferber** [comment]
@jrose-apple @DougGregor I'll add a `FileCheck` test now. I'd like to keep the `DiagnosticTransaction`s for the time being if reasonable — it was a relatively easy way to integrate diagnostic collection and I'd rather not have to rip that out at the moment (time better spent on some other things).

**Comment by jrose-apple** [comment]
Okay, if Doug's okay with it I'll get used to it. :-)

**Pull request merged**
