### PR TITLE
Downgrade concurrency-related error to a warning.

### PR DESCRIPTION
**Pull request by DougGregor**
We are diagnosing this condition more completely now, so downgrade
from an error to a warning to not break existing code.

Fixes rdar://88649197.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by gabeSecula** [comment]
Looks like this is happening on main as of ~1-2 weeks ago. Not sure if we want to merge this PR or explicitly keep this a client side error. Made a new radar to track this as the last was closed: rdar://90881215

**Comment by gsecula** [comment]
Looks like this is happening on main as of ~1-2 weeks ago. Not sure if we want to merge this PR or explicitly keep this a client side error. Made a new radar to track this as the last was closed: rdar://90881215

**Comment by DougGregor** [comment]
Superseded by https://github.com/apple/swift/pull/60119

**Pull request closed without merging**
