### PR TITLE
update_checkout (tests): Use 'main' for test branch

### PR DESCRIPTION
**Pull request by jorng**
This updates the tests for `utils/update_checkout` to use `main` for the test branch names in git (as opposed to `master`).  In addition to following current best practices for inclusive terms, this also fixes an issue that occurs if a user has customized their local git config to use an alternate default branch name (using `init.defaultBranch`).

If a user has set `init.defaultBranch` in their git config to anything other than `master`, the tests fail. By updating the `git init` call to use `--initial-branch=main`, the user's setting will not affect the test.

### CODE REVIEW

**Review by edymtt — APPROVED** [review]

**Comment by jorng** [comment]
@swift-ci Please smoke test

**Review by compnerd — APPROVED** [review]
This is good, but please do check with @shahmishal that this shouldn't cause any unintentional issues.

**Comment by jorng** [comment]
@swift-ci Please smoke test

**Comment by jorng** [comment]
As far as I can tell, it looks like the `--initial-branch=main` option is not working for the `git init --bare` call. Perhaps the test environments don't have a new enough version of `git`?

I've updated this to use `git symbolic-ref HEAD refs/heads/main`, which should be more compatible.

@swift-ci Please smoke test

**Review by jambestwick — COMMENTED** [review]
change main to master

**Comment by jorng** [comment]
OK, one more try here.  It still doesn't seem to be respecting the `main` branch name in the "local" repo. Added the `symbolic-ref` call to the local repo too. Let's see if that does the trick.

@swift-ci Please smoke test

**Comment by jorng** [comment]
@swift-ci Please smoke test Linux

**Comment by jorng** [comment]
@shahmishal any opposition to merging this?

**Comment by shahmishal** [comment]
LGTM, merged

**Pull request merged**
