### PR TITLE
Don't Merge: IRGen: _getObjCTypeEncoding should return null for types it does not understand

### PR DESCRIPTION
**Pull request by aschwaighofer**
rdar://47706453

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
I'm not sure this is an improvement—it's turning a (bad) compile-time failure into a run-time failure. Can we diagnose instead?

**Comment by jrose-apple** [comment]
…I guess in order to diagnose, we'd have to resolve this during the mandatory passes, but the point stands.

**Comment by aschwaighofer** [comment]
I think @phausler wanted this to return null rather than fail at compile time.

I must admit I had not read the doc comment which states that the compilation failure is the expected behavior.

```
/// Get the ObjC type encoding for a type as a pointer to a C string.
///
/// This is used by the Foundation overlays. The compiler will error if the
/// passed-in type is generic or not representable in Objective-C
```

**Comment by phausler** [comment]
I would take a variant that Foundation can call that just returns nil and leave this one as it is.

**Comment by jrose-apple** [comment]
If it's for the NSValue thing, I don't think you want that either. You'll get different behavior in Debug and Release builds, and really based on the whims of the optimizer.

**Comment by jrose-apple** [comment]
The specific thing that will not work is `@encode` of a generic type acting on the runtime type. If you want that, it'll have to be implemented as a runtime function, not a compiler builtin. I'm not sure if that's possible either.

**Comment by jrose-apple** [comment]
Even if we said it's okay to return `nil` for a type that doesn't come from C, you need a way to say "this must be applied to a concrete type", and we don't have that right now.

**Comment by jrose-apple** [comment]
@jckarter suggests using the type encoding to check the size and maybe alignment of the stored type and using Swift's MemoryLayout to check that the generic type is compatible with that. You could also check that the Swift type is trivial (though I don't remember how to do that myself).

**Comment by phausler** [comment]
`MemoryLayout<Type>.size == the size returned from NSGetSizeAndAlignment from the objCType of the NSValue` is not sufficient. 

```
struct TwoObjects {
   var a: AnyObject
   var b: AnyObject
}
```
would be the same size and alignment as NSRange (on 64 bit platforms).

So the work-around MUST include a triviality check.

**Comment by aschwaighofer** [comment]
``_isPOD`` (Builtin.swift)

**Comment by jckarter** [comment]
You can't put a nontrivial Swift type in an NSValue to begin with (at least, not without brute force), so checking the size and PODness should be as good as you can get.

**Pull request closed without merging**
