### PR TITLE
[build-script] Update build-script to support building and installing the SourceKit stress tester

### PR DESCRIPTION
**Pull request by nathawes**
Adds support to build-script to build, test and install the [SourceKit stress tester](https://github.com/apple/swift-stress-tester). Most of the actual build/install is handled by a [helper script](https://github.com/apple/swift-stress-tester/blob/master/SourceKitStressTester/Utilities/build-script-helper.py) in the swift-stress-tester repo.

This also updates the OS X package builder presets to build and install the stress tester executables (`sk-stress-test` and `sk-swiftc-wrapper`). I have a swift-integration-tests pull request open [here](https://github.com/apple/swift-integration-tests/pull/42) to check it works correctly once it's in.

### CODE REVIEW

**Comment by nathawes** [comment]
@swift-ci please test

**Comment by nathawes** [comment]
@swift-ci please test

**Comment by nathawes** [comment]
@swift-ci please test

**Comment by nathawes** [comment]
@swift-ci Please build Toolchain macOS Platform

**Comment by nathawes** [comment]
@swift-ci please test

**Review by nkcsgexi — APPROVED** [review]
LGTM!

**Comment by nathawes** [comment]
@swift-ci Please build Toolchain Linux Platform

**Review by shahmishal — APPROVED** [review]
LGTM! Thanks!

**Comment by shahmishal** [comment]
@nathawes We are seeing failure due to missing script. 

https://ci.swift.org/job/oss-swift-package-osx/2522/console

```
/Users/buildnode/jenkins/workspace/oss-swift-package-osx/swift/utils/build-script-impl: line 277: /Users/buildnode/jenkins/workspace/oss-swift-package-osx/swift-stress-tester/SourceKitStressTester/Utilities/build-script-helper.py: No such file or directory
```

**Pull request merged**
