### PR TITLE
[stdlib] Revert addition of some recursive where clauses on Collection protocols

### PR DESCRIPTION
**Pull request by airspeedswift**
These were causing build performance issues.

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
@swift-ci please clean test macOS platform

**Review by DougGregor — APPROVED** [review]
The change looks fine, but we should verify that it does indeed improve build times again.

**Comment by airspeedswift** [comment]
@swift-ci please smoke test

**Comment by airspeedswift** [comment]
@swift-ci please test macOS platform

**Comment by airspeedswift** [comment]
@swift-ci please smoke test linux platform

**Pull request merged**
