### PR TITLE
Add release date to CHANGELOG.md

### PR DESCRIPTION
**Pull request by benrimmington**

### CODE REVIEW

**Comment by benrimmington** [comment]
@theblixguy Please merge if possible. The second commit fixes a typo in 7691fbdc766166c51d0fd34200f3e05fe37499fd.

**Comment by theblixguy** [comment]
Could you remove the last commit? Someone just fixed it and I didn’t see this before I approved their PR.

**Review by theblixguy — APPROVED** [review]

**Comment by theblixguy** [comment]
@swift-ci please smoke test and merge

**Comment by theblixguy** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
