### PR TITLE
[cxx-interop] Synthesize conformances to `CxxRandomAccessCollection`

### PR DESCRIPTION
**Pull request by egorzhdan**
This makes ClangImporter automatically conform C++ collection types to `Cxx.CxxRandomAccessCollection` protocol.

We consider a C++ sequence type to be a random access collection type its iterator conforms to `UnsafeCxxRandomAccessIterator`.

### CODE REVIEW

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Review by zoecarver — APPROVED** [review]
Awesome, thanks!

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please smoke test Linux

**Comment by egorzhdan** [comment]
@swift-ci please smoke test Windows

**Comment by egorzhdan** [comment]
@swift-ci please smoke test Windows

**Comment by egorzhdan** [comment]
@swift-ci please smoke test Windows

**Pull request merged**
