### PR TITLE
AllocBoxToStack should notify the PassManager of new functions.

### PR DESCRIPTION
**Pull request by atrick**
In preparation for fixing this bug.
- Separate general SIL utilities, liveness, escape analysis,
  and promotion.
- Give promotion routines access to the current pass.

Ideally, the current pass would be accessible via TLS. In the meantime,
pass routines should always have access to a state object that
encapsulates the pass information corresponding to a single invocation
of the pass.

Access to the pass' state should be consistent and idiomatic; it should
not depend on the where we are in the call stack. This makes the code much easier to understand and refactor, and it enables exploratory changes.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test.

**Comment by atrick** [comment]
@swift-ci smoke test compiler performance.

**Comment by atrick** [comment]
@swift-ci test linux platform.

**Comment by atrick** [comment]
@swift-ci smoke test compiler performance.

**Comment by atrick** [comment]
@eeckstein AFAICT "smoke test compiler performance" did not do anything. In this case,  I don't expect this to change compilation time modulo bugs, and all benchmark binaries are identical, so nothing to worry about. But I'm wondering how to test compilation time in my next PR.

**Comment by eeckstein** [comment]
@graydon any idea why "smoke test compiler performance" didn't work?

**Pull request merged**
