### PR TITLE
stdlib: remove an unused-function

### PR DESCRIPTION
**Pull request by compnerd**
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

This function is only used in the ObjC interop case.  Control it via the
preprocesor.

### CODE REVIEW

**Comment by lattner** [comment]
@swift-ci Please smoke test Linux platform and merge

**Comment by lattner** [comment]
@swift-ci Please test and merge

**Comment by compnerd** [comment]
The test failures seem unrelated?

**Comment by modocache** [comment]
I recall the lldb test failure from yesterday and can confirm it's unrelated. Considering @swift-ci would have merged if not for the spurious failure, I'll go ahead and merge this myself! 🙇

**Pull request merged**
