### PR TITLE
[do not merge] Test PR for Swift-Markdown #13

### PR DESCRIPTION
**Pull request by franklinsch**
Test PR for cross-repo testing https://github.com/apple/swift-markdown/pull/13.

### CODE REVIEW

**Comment by franklinsch** [comment]
https://github.com/apple/swift-markdown/pull/13
@swift-ci please smoke test

**Comment by Kyle-Ye** [comment]
> [apple/swift-markdown#13](https://github.com/apple/swift-markdown/pull/13)
> @swift-ci please smoke test

How does the cross-repo test working? I did not see any config file change. Is this grammar mean that we are testing swift repo with swift-markdown on this markdown-PR's branch?

**Comment by franklinsch** [comment]
> Is this grammar mean that we are testing swift repo with swift-markdown on this markdown-PR's branch?

Yes, that's right. It builds swift main with the Swift-Markdown PR.

**Comment by Kyle-Ye** [comment]
In macOS Platform log's end
> ERROR: command terminated with a non-zero exit status 1, aborting

I did not find what's wrong with the test. What's the actually failure about this? Is there something related to me to fix?

**Comment by franklinsch** [comment]
It looks like the build is failing with:

```
11:57:06 error: unknown package 'swift-cmark' in dependencies of target 'Markdown'; valid packages are: 'swift-cmark-gfm', 'swift-argument-parser'
```

Which seems to be related to the changes in the Swift-Markdown PR

**Comment by Kyle-Ye** [comment]
> It looks like the build is failing with:
> 
> ```
> 11:57:06 error: unknown package 'swift-cmark' in dependencies of target 'Markdown'; valid packages are: 'swift-cmark-gfm', 'swift-argument-parser'
> ```
> 
> Which seems to be related to the changes in the Swift-Markdown PR

Got the issue. In the past, we do not need to write package name for the dependence.
```swift
dependencies: ["cmark-gfm", "cmark-gfm-extensions", "CAtomic"])
```
But in the recent version of SPM(swift 5.x), if a dependence is in the same package, we could use the old way (byNameTarget), but if a dependence is in other package, we need to explicitly use something like `.product(name: "cmark-gfm", package: "swift-cmark")`.

And in the bottom, we have this.

```swift
if ProcessInfo.processInfo.environment["SWIFTCI_USE_LOCAL_DEPS"] == nil {
    // Building standalone, so fetch all dependencies remotely.
    package.dependencies += [
        .package(url: "https://github.com/apple/swift-cmark.git", .branch("gfm")),
        .package(url: "https://github.com/apple/swift-argument-parser", .upToNextMinor(from: "0.4.4")),
    ]
} else {
    // Building in the Swift.org CI system, so rely on local versions of dependencies.
    package.dependencies += [
        .package(path: "../swift-cmark-gfm"),
        .package(path: "../swift-argument-parser"),
    ]
}
```
Then the product's name should be swift-cmark-gfm if we are have "SWIFTCI_USE_LOCAL_DEPS".

**Comment by Kyle-Ye** [comment]
we could solve this by introduce a var like this.
```
let swiftCmarkPackageName = ProcessInfo.processInfo.environment["SWIFTCI_USE_LOCAL_DEPS"] == nil ? "swift-cmark" : "swift-cmark-gfm"
``` 
Let me check a while to see if there is a better solution.

**Comment by Kyle-Ye** [comment]
I think the folder "swift-cmark-gfm" is here because we have "swift-cmark" folder already for the main branch of "swift-cmark" repo. Right? Can we have a better structure for this? 

Or should we file a bug/feature to SPM to support this.
I think the dependence `.product(name: "cmark-gfm", package: "swift-cmark")`'s package name should be the name in the Package.swift's Package name rather the folder/url name.

**Comment by Kyle-Ye** [comment]
Update the branch, could we run test again? Thanks

**Comment by franklinsch** [comment]
This is a change introduced in [SE-0226](https://github.com/apple/swift-evolution/blob/main/proposals/0226-package-manager-target-based-dep-resolution.md):

> Starting with the SwiftPM version following 5.4 (exact number TBD), SwiftPM will actively discourage the use of the name attribute on the package dependency declaration (will emit warning when used with tools-version >= TBD) and instead will compute an identity for the declared dependency by using the last path component of the dependency URL (or path in the case of local dependencies) in the dependencies section

As such, your proposed fix looks good to me.

**Comment by franklinsch** [comment]
https://github.com/apple/swift-markdown/pull/13
@swift-ci please smoke test

**Comment by Kyle-Ye** [comment]
> This is a change introduced in [SE-0226](https://github.com/apple/swift-evolution/blob/main/proposals/0226-package-manager-target-based-dep-resolution.md?rgh-link-date=2021-11-04T10%3A18%3A25Z):
> 
> > Starting with the SwiftPM version following 5.4 (exact number TBD), SwiftPM will actively discourage the use of the name attribute on the package dependency declaration (will emit warning when used with tools-version >= TBD) and instead will compute an identity for the declared dependency by using the last path component of the dependency URL (or path in the case of local dependencies) in the dependencies section
> 
> As such, your proposed fix looks good to me.

Got it, so it is a feature already discussed under swift-evolution.

**Comment by Kyle-Ye** [comment]
The Windows Platform test seems to be cancelled by the user.

**Comment by franklinsch** [comment]
@swift-ci please build toolchain

**Comment by franklinsch** [comment]
https://github.com/apple/swift-markdown/pull/13
@swift-ci please build toolchain

**Pull request closed without merging**
