### PR TITLE
[libSyntax] Parse attributes on closures

### PR DESCRIPTION
**Pull request by ahoppen**
https://github.com/apple/swift/pull/36012 introduced attribtues on closures. Support them in libSyntax.

Fixes rdar://77923956

### CODE REVIEW

**Review by akyrtzi — APPROVED** [review]

**Comment by akyrtzi** [comment]
Does this need a SwiftSyntax change to change the parser lib hash?

**Comment by ahoppen** [comment]
Yes, forgot to push it.

https://github.com/apple/swift/pull/37566

@swift-ci Please test

**Comment by ahoppen** [comment]
Yes, forgot to push it.

https://github.com/apple/swift-syntax/pull/287

@swift-ci Please test

**Review by rintaro — APPROVED** [review]

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/287

@swift-ci Please test

**Pull request merged**
