### PR TITLE
Only run predictable mem opts in the guaranteed pipeline.

### PR DESCRIPTION
**Pull request by gottesmm**
Just an experiment to see the performance impact of this. I am currently updating this pass for ownership and this will make it significantly easier to do.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
I believe that this was done originally since we were late in the schedule and needed to make up some performance issues later in the pipeline. I am going to try to fix it outside of PMO and remove this run.

Then I can make PMO work only on OSSA. Part of the problem here is that removing allocations is more complex in ossa vs non-ossa since in ossa one has to deal with the store being a +1 use of the original value. In non-ossa we rely on retain/release so we don't have to care about this.

**Comment by slavapestov** [comment]
You might also want to incorporate my old PR: https://github.com/apple/swift/pull/15968

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
DataCountMedium I think has one extra copy. Hmm.

**Comment by gottesmm** [comment]
Both regressions have to do with outlined consumes of Data.Representation.

**Comment by gottesmm** [comment]
The linux failure I believe is spurious since there was a similar failure on the main 16.04 bot. I am going to try it again.

**Comment by gottesmm** [comment]
@swift-ci smoke test linux platform

**Comment by gottesmm** [comment]
The problem in DataCountMedium is that we aren't eliminating this copy:

```
  %5 = alloc_stack $Data                          // users: %31, %30, %26, %16
  %6 = alloc_stack $Data                          // users: %15, %12, %9
  // function_ref specialized Data._Representation.init(count:)
  %7 = function_ref @$s10Foundation4DataV15_RepresentationO5countAESi_tcfCTf4nd_n : $@convention(thin) (Int) -> @owned Data._Representation // user: %8
  %8 = apply %7(%3) : $@convention(thin) (Int) -> @owned Data._Representation // users: %13, %11, %10
  %9 = struct_element_addr %6 : $*Data, #Data._representation // user: %10
  store %8 to %9 : $*Data._Representation         // id: %10
  %11 = struct $Data (%8 : $Data._Representation) // user: %16
  %12 = load %6 : $*Data                          // user: %14
  retain_value %8 : $Data._Representation         // id: %13
  release_value %12 : $Data                       // id: %14
  dealloc_stack %6 : $*Data                       // id: %15
```

The good SIL:

```
  %5 = alloc_stack $Data                          // users: %24, %23, %19, %9                                                     
  // function_ref specialized Data._Representation.init(count:)                                                                   
  %6 = function_ref @$s10Foundation4DataV15_RepresentationO5countAESi_tcfCTf4nd_n : $@convention(thin) (Int) -> @owned Data._Repr$
  %7 = apply %6(%3) : $@convention(thin) (Int) -> @owned Data._Representation // user: %8                                         
  %8 = struct $Data (%7 : $Data._Representation)  // user: %9                                                                     
  store %8 to %5 : $*Data                         // id: %9 
```

Hmmm...

**Comment by gottesmm** [comment]
CreateCount is as stupid. I wonder if it is some sort of phase ordering issue.

```
  %27 = alloc_stack $Data                         // users: %32, %30, %28
  %28 = struct_element_addr %27 : $*Data, #Data._representation // user: %29
  store %16 to %28 : $*Data._Representation       // id: %29
  %30 = load %27 : $*Data                         // user: %31
  release_value %30 : $Data                       // id: %31
  dealloc_stack %27 : $*Data                      // id: %32
```

**Comment by gottesmm** [comment]
yea... with the following test case, RLE doesn't handle this... it feels like it should!

```
sil_stage canonical

import Builtin
import Swift
import SwiftShims

import Foundation

// specialized Data._Representation.init(count:)
sil @$s10Foundation4DataV15_RepresentationO5countAESi_tcfCTf4nd_n : $@convention(thin) (Int) -> @owned Data._Representation

// getCount(blackHole:)
sil @$s4main8getCount9blackHoleyySiXE_tF : $@convention(thin) (@noescape @callee_guaranteed (Int) -> ()) -> () {
bb0(%0 : $@noescape @callee_guaranteed (Int) -> ()):
  %1 = integer_literal $Builtin.Int64, 1033       // user: %2
  %2 = struct $Int (%1 : $Builtin.Int64)          // user: %6
  %3 = alloc_stack $Data                          // users: %16, %15, %14
  %4 = alloc_stack $Data                          // users: %13, %10, %7
  // function_ref specialized Data._Representation.init(count:)
  %5 = function_ref @$s10Foundation4DataV15_RepresentationO5countAESi_tcfCTf4nd_n : $@convention(thin) (Int) -> @owned Data._Repre
sentation // user: %6
  %6 = apply %5(%2) : $@convention(thin) (Int) -> @owned Data._Representation // users: %11, %9, %8
  %7 = struct_element_addr %4 : $*Data, #Data._representation // user: %8
  store %6 to %7 : $*Data._Representation         // id: %8
  %9 = struct $Data (%6 : $Data._Representation)  // user: %14
  %10 = load %4 : $*Data                          // user: %12
  retain_value %6 : $Data._Representation         // id: %11
  release_value %10 : $Data                       // id: %12
  dealloc_stack %4 : $*Data                       // id: %13
  store %9 to %3 : $*Data                         // id: %14
  destroy_addr %3 : $*Data                        // id: %15
  dealloc_stack %3 : $*Data                       // id: %16
  %17 = tuple ()                                  // user: %18
  return %17 : $()                                // id: %18
} // end sil function '$s4main8getCount9blackHoleyySiXE_tF'
```

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci test and merge

**Comment by gottesmm** [comment]
@swift-ci test and merge

**Comment by gottesmm** [comment]
@swift-ci test and merge

**Comment by gottesmm** [comment]
@swift-ci test and merge

**Comment by gottesmm** [comment]
@swift-ci test and merge

**Pull request merged**
