### PR TITLE
[Freestanding] Remove uses of stat() and dlsym().

### PR DESCRIPTION
**Pull request by al45tair**
We shouldn't be using stat() or dlsym() in the freestanding runtime.

rdar://111214571
rdar://106555012

### CODE REVIEW

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by al45tair** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
@swift-ci Please smoke test Windows platform

**Comment by al45tair** [comment]
Oops. I hit the Merge button prematurely. It's passed all the tests but nobody actually reviewed it. I think it should be fine, but if anyone has any problem with it, please revert and I'll raise a new PR to fix.

**Comment by kubamracek** [comment]
LGTM! :)

**Pull request merged**
