### PR TITLE
build-script: install swiftsyntax dylib in the OSS toolchain.

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by gottesmm** [comment]
@nkcsgexi are you sure this is the right way to do this? Shouldn't it just be an install component?

**Comment by compnerd** [comment]
@gottesmm I think this is right since its a separate repository

**Review by nathawes — COMMENTED** [review]
Thanks for adding the dylib only option, Xi!
Also, is the package + no test preset the right one to change here? (just checking)

**Comment by nkcsgexi** [comment]
@gottesmm @compnerd we are actually inspired by SwiftPM of this way to install. As @compnerd mentioned, install_component isn't handy for cross-repo install.

**Comment by akyrtzi** [comment]
> @gottesmm @compnerd we are actually inspired by SwiftPM of this way to install. As @compnerd mentioned, install_component isn't handy for cross-repo install.

I think it's more exact to say that we don't use CMake in this repo.

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
