### PR TITLE
[APINotes] Protocols cannot use import-as-member.

### PR DESCRIPTION
**Pull request by jrose-apple**
We could support this in the future but right now it's causing problems. There's also a potential ambiguity issue here where a protocol and class could have the same name.

In addition to updating the importer, remove the two entries from the CryptoTokenKit API notes that were trying to use this feature.

rdar://problem/27990168

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

A smoke test on macOS does the following:
1. Builds the compiler incrementally.
2. Builds the standard library only for macOS. Simulator standard libraries and
   device standard libraries are not built.
3. lldb is not built.
4. The test and validation-test targets are run only for macOS. The optimized
   version of these tests are not run.

A smoke test on Linux does the following:
1. Builds the compiler incrementally.
2. Builds the standard library incrementally.
3. lldb is built incrementally.
4. The swift test and validation-test targets are run. The optimized version of these
   tests are not run.
5. lldb is tested.

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test OS X platform

**Comment by jrose-apple** [comment]
@milseman Can you review this?

**Comment by jrose-apple** [comment]
Or @DougGregor, I guess.

(fixing tests now)

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test OS X platform

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test OS X platform

**Comment by jrose-apple** [comment]
One more test fix. For review, I'm specifically interested in confirmation whether everything I deleted in the tests is really correct to delete.

@swift-ci Please smoke test OS X platform

**Comment by jrose-apple** [comment]
https://ci.swift.org/view/Pull%20Request/job/swift-PR-osx-smoke-test/1360/

**Comment by milseman** [comment]
This part LGTM. Do we issue a good error when trying to import onto a protocol?

**Comment by jrose-apple** [comment]
We get the generic warning
```
<unknown>:0: warning: imported declaration 'TKTokenKeyAlgorithm' could not be mapped to 'TKTokenSessionDelegate.KeyAlgorithm'
```
so "not really", but that's something we can clean up later.

**Comment by jrose-apple** [comment]
Smoke tests passed, merging.

**Comment by milseman** [comment]
LGTM

**Pull request merged**
