### PR TITLE
[AST] Completely replace Module with ModuleDecl

### PR DESCRIPTION
**Pull request by modocache**
The typedef `swift::Module` was a temporary solution that allowed `swift::Module` to be renamed to `swift::ModuleDecl` without requiring every single callsite to be modified.

Modify all the callsites, and get rid of the typedef.

### CODE REVIEW

**Comment by modocache** [comment]
@swift-ci please smoke test

**Comment by modocache** [comment]
Please test with following pull request:
https://github.com/apple/swift-lldb/pull/115

@swift-ci Please test

**Comment by modocache** [comment]
Please test with following pull request:
https://github.com/apple/swift-lldb/pull/117

@swift-ci Please test

**Review by DougGregor — APPROVED** [review]
Looks great, thank you!

**Comment by CodaFi** [comment]
⛵️

**Comment by modocache** [comment]
Thanks!

**Pull request merged**
