### PR TITLE
[sending] Mark Task.init, Task.detached and friends as taking a sending closure instead of a __owned @Sendable

### LINKED ISSUE #74382: Swift 6: incorrect compiler error when passing a `sending` closure from a global-actor-isolated function
### Description

The Swift 6 compiler that ships with Xcode 16.0 beta (16A5171c) produces an invalid compiler error when the following conditions are met:

- A function accepts a `sending @escaping () -> Void` parameter.
- This function is called from a global-actor isolated function.

### Reproduction

Package.swift

```swift
// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "SwiftIssue",
    platforms: [
        .macOS(.v10_15),
    ],
    products: [
        .library(name: "SwiftIssue", targets: ["SwiftIssue"]),
    ],
    targets: [
        .target(name: "SwiftIssue"),
    ]
)
```

SwiftIssue.swift

```swift
@globalActor actor MyGlobalActor: GlobalActor {
    static let shared = MyGlobalActor()
}

func acceptSendingClosure(completion: sending @escaping () -> Void) { }
func acceptMainActorClosure(completion: @escaping @MainActor () -> Void) { }
func acceptMyGlobalActorClosure(completion: @escaping @MyGlobalActor () -> Void) { }

@MainActor func mainActorIsolatedFunction() {
    // error: main actor-isolated value of type '() -> ()' passed as a
    // strongly transferred parameter; later accesses could race
    acceptSendingClosure { }
    
    acceptMainActorClosure { }     // OK
    acceptMyGlobalActorClosure { } // OK
}

@MyGlobalActor func myGlobalActorIsolatedFunction() {
    // error: global actor 'MyGlobalActor'-isolated value of type '() -> ()'
    // passed as a strongly transferred parameter; later accesses could race
    acceptSendingClosure { }
    
    acceptMainActorClosure { }     // OK
    acceptMyGlobalActorClosure { } // OK
}

actor MyActor {
    func actorIsolatedFunction() {
        acceptSendingClosure { }       // OK
        acceptMainActorClosure { }     // OK
        acceptMyGlobalActorClosure { } // OK
    }
}
```

Build errors:

```
% swift package clean && swift build
Building for debugging...
/Users/groue/Desktop/SwiftIssue/Sources/SwiftIssue/SwiftIssue.swift:12:5: error: main actor-isolated value of type '() -> ()' passed as a strongly transferred parameter; later accesses could race
10 |     // error: main actor-isolated value of type '() -> ()' passed as a
11 |     // strongly transferred parameter; later accesses could race
12 |     acceptSendingClosure { }
   |     `- error: main actor-isolated value of type '() -> ()' passed as a strongly transferred parameter; later accesses could race
13 |     
14 |     acceptMainActorClosure { }     // OK

/Users/groue/Desktop/SwiftIssue/Sources/SwiftIssue/SwiftIssue.swift:21:5: error: global actor 'MyGlobalActor'-isolated value of type '() -> ()' passed as a strongly transferred parameter; later accesses could race
19 |     // error: global actor 'MyGlobalActor'-isolated value of type '() -> ()'
20 |     // passed as a strongly transferred parameter; later accesses could race
21 |     acceptSendingClosure { }
   |     `- error: global actor 'MyGlobalActor'-isolated value of type '() -> ()' passed as a strongly transferred parameter; later accesses could race
22 |     
23 |     acceptMainActorClosure { }     // OK
```

In the Swift 5 language mode, the errors are emitted as warnings:

<details><summary>Variant of Package.swift for reproduction in Swift 5 language mode</summary>

```swift
// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "SwiftIssue",
    platforms: [
        .macOS(.v10_15),
    ],
    products: [
        .library(name: "SwiftIssue", targets: ["SwiftIssue"]),
    ],
    targets: [
        .target(
            name: "SwiftIssue",
            swiftSettings: [
                .enableUpcomingFeature("StrictConcurrency"),
                .enableExperimentalFeature("RegionBasedIsolation"),
                .enableExperimentalFeature("TransferringArgsAndResults"),
            ]
        )
    ],
    swiftLanguageVersions: [.v5]
)
```

</details>

### Expected behavior

No compiler error in the Swift 6 language mode.

No compiler warning in the Swift 5 language mode.

### Environment

swift-driver version: 1.109.2 Apple Swift version 6.0 (swiftlang-6.0.0.3.300 clang-1600.0.20.10)
Target: arm64-apple-macosx14.0

### Additional information

This compiler error is pretty concerning, because **it makes it impossible to call a function that accepts a completion block from a global-actor-isolated function**. Functions with completion blocks **still exist**, and global-actor-isolated functions are **pervasive** in user code.

Please see [this forum post](https://forums.swift.org/t/relaxing-sendable-constraint-to-sending-closures-creates-undesired-warnings/72367) for the initial report, and more information.

### PR DESCRIPTION
**Pull request by gottesmm**
Just creating the PR now for discussion. Going to add more here.

Resolves: https://github.com/apple/swift/issues/74382

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by groue** [comment]
Hello @gottesmm, I'm pretty happy that this pull request has shipped in Xcode 16 beta 4. 🙏 

I was expecting that `DispatchQueue.async(execute:)` would also be amended to use `sending` instead of requiring a `@Sendable` closure. Is it worth reporting somewhere, or do you think it will just ship in a future beta?

**Comment by hborla** [comment]
> I was expecting that DispatchQueue.async(execute:) would also be amended to use sending instead of requiring a @Sendable closure.

Michael's PR here is part of the implementation for SE-0430, which only includes adoption of `sending` in the Concurrency library. Changes to Dispatch are not subject to the Swift Evolution process.

That said:

> Is it worth reporting somewhere

It's a known issue.

**Pull request merged**
