### PR TITLE
[Testing] NFC: Make top five slowest IDE tests concurrent

### PR DESCRIPTION
**Pull request by davezarzycki**
This is enough to get the IDE tests out of the top twenty slowest tests overall on my machine.

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by davezarzycki** [comment]
Well, not perfectly out of the top twenty slowest. One very specific completion test is still the third slowest overall:
```
Slowest Tests:
--------------------------------------------------------------------------
30.41s: Swift(linux-x86_64) :: stdlib/CharacterPropertiesLong.swift
26.98s: Swift(linux-x86_64) :: stdlib/FixedPoint.swift.gyb
25.92s: Swift(linux-x86_64) :: IDE/complete_ambiguous/BEST_SOLUTION_FILTER2.test
```

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by davezarzycki** [comment]
@swift-ci please smoke test macos linux windows

**Comment by davezarzycki** [comment]
@swift-ci please test Windows platform

**Review by rintaro — CHANGES_REQUESTED** [review]
Sorry, our plan is migrating to `-batch-code-completion` mode (https://github.com/apple/swift/pull/28946). Instead of splitting test files, could you try it out?

**Comment by davezarzycki** [comment]
Nothing to be sorry for. That change seems like a reasonable approach too. What's the timeline for adopting #28946?

**Pull request closed without merging**
