### PR TITLE
🍒[5.7][Distributed] Implement distributed computed properties

### PR DESCRIPTION
**Pull request by ktoso**
**Description:** Add support for parsing distributed var <name> : <type> { ... } declarations and type-checking them by injecting distributed thunks during Sema.
**Risk:** Low, applies only to distributed properties and funcs.
**Review by:** @DougGregor
**Testing:** PR testing, validated the toolchain against complex project
**Original PR:** https://github.com/apple/swift/pull/59481
**Radar:** rdar://91283164

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please build toolchain
@swift-ci please test

**Comment by ktoso** [comment]
Failure was 

Failed Tests (1):
  lldb-shell :: SwiftREPL/ImportFoundation.test

**Comment by ktoso** [comment]
@swift-ci smoke test macOS

**Comment by ktoso** [comment]
@swift-ci please test macOS

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
