### PR TITLE
[benchmark] FloatingPointPrinting: Fix benchmark failures

### PR DESCRIPTION
**Pull request by lorentey**
#15234 introduced some benchmarks that are currently failing on master.

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci please smoke test

**Comment by lorentey** [comment]
@swift-ci some benchmark

**Comment by lorentey** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@lorentey Can you just merge this and file an SR. This will block me from doing +0 work.

**Comment by lorentey** [comment]
@gottesmm can't push to a protected branch :(

**Comment by gottesmm** [comment]
Thanks @atrick

**Pull request merged**
