### PR TITLE
Enable lldb test and test-installable-package (33715252)

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test and merge

**Comment by slavapestov** [comment]
This has been disabled for ages, good to see it finally getting re-enabled!

**Comment by shahmishal** [comment]
Blocked by -- https://bugs.swift.org/browse/SR-6123

**Comment by shahmishal** [comment]
https://github.com/apple/swift-corelibs-libdispatch/pull/313

@swift-ci test

**Comment by shahmishal** [comment]
```
FAILED: source/Symbol/CMakeFiles/lldbSymbol.dir/SwiftASTContext.cpp.o 
/usr/bin/clang++   -DGTEST_HAS_RTTI=0 -DHAVE_ROUND -DLIBXML2_DEFINED -DLLDB_USE_BUILTIN_DEMANGLER -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Isource/Symbol -I/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/lldb/source/Symbol -Iinclude -I/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/lldb/include -I/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/buildbot_linux/llvm-linux-x86_64/include -I/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/buildbot_linux/llvm-linux-x86_64/tools/clang/include -I/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/llvm/include -I/include -I/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/llvm/tools/clang/include -I/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/buildbot_linux/swift-linux-x86_64/include -I/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/swift/include -I/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/lldb/source -I/usr/include/python2.7 -I/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/lldb/tools/clang/include -I../clang/include -I/usr/include/libxml2 -I/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/lldb/source/. -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -w -fcolor-diagnostics -ffunction-sections -fdata-sections -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-strict-aliasing -Wno-deprecated-register -Wno-vla-extension -O3    -UNDEBUG  -fno-exceptions -fno-rtti -MMD -MT source/Symbol/CMakeFiles/lldbSymbol.dir/SwiftASTContext.cpp.o -MF source/Symbol/CMakeFiles/lldbSymbol.dir/SwiftASTContext.cpp.o.d -o source/Symbol/CMakeFiles/lldbSymbol.dir/SwiftASTContext.cpp.o -c /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/lldb/source/Symbol/SwiftASTContext.cpp
/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/lldb/source/Symbol/SwiftASTContext.cpp:7654:31: error: member access into incomplete type 'swift::GenericSignature'
      auto depTy = generic_sig->getGenericParams()[arg_idx];
                              ^
/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/swift/include/swift/AST/Type.h:38:7: note: forward declaration of 'swift::GenericSignature'
class GenericSignature;
      ^
/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/lldb/source/Symbol/SwiftASTContext.cpp:7657:60: error: expected '(' for function-style cast or type construction
                              ->castTo<swift::ArchetypeType>());
                                       ~~~~~~~~~~~~~~~~~~~~^
/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/lldb/source/Symbol/SwiftASTContext.cpp:7657:62: error: expected expression
                              ->castTo<swift::ArchetypeType>());
                                                             ^
3 errors generated.

```

**Comment by shahmishal** [comment]
@swift-ci test and merge

**Comment by shahmishal** [comment]
@swift-ci test and merge

**Comment by shahmishal** [comment]
@swift-ci test and merge

**Comment by shahmishal** [comment]
https://github.com/apple/swift-corelibs-libdispatch/pull/315

@swift-ci test Linux

**Comment by shahmishal** [comment]
apple/swift-corelibs-libdispatch#315

@swift-ci clean test Linux

**Comment by shahmishal** [comment]
@swift-ci clean test Linux

**Comment by aciidb0mb3r** [comment]
@swift-ci clean test Linux

**Comment by aciidb0mb3r** [comment]
@swift-ci test Linux

**Comment by aciidb0mb3r** [comment]
@swift-ci test and merge

**Pull request merged**
