### PR TITLE
Sema: Give constraints a more dignified retirement

### LINKED ISSUE #77008: nullptr access in `DisjunctionStep::~DisjunctionStep`
https://github.com/swiftlang/swift/pull/76921 caused a `nullptr` access in `DisjunctionStep::~DisjunctionStep` in the following new test case

```swift
// RUN: %target-swift-frontend -typecheck %s
Binding<Bool>Binding<Bool>
```

<details><summary>Stack trace</summary>
<p>

```
0.	Program arguments: /Users/alex/src/build/buildbot_incremental/swift-macosx-arm64/bin/swift-frontend -target arm64-apple-macosx14.0 -module-cache-path /Users/alex/src/build/buildbot_incremental/swift-macosx-arm64/swift-test-results/arm64-apple-macosx14.0/clang-module-cache -sdk /Applications/Geode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk -swift-version 4 -define-availability "SwiftStdlib 9999:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999" -define-availability "SwiftStdlib 5.0:macOS 10.14.4, iOS 12.2, watchOS 5.2, tvOS 12.2" -define-availability "SwiftStdlib 5.1:macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0" -define-availability "SwiftStdlib 5.2:macOS 10.15.4, iOS 13.4, watchOS 6.2, tvOS 13.4" -define-availability "SwiftStdlib 5.3:macOS 11.0, iOS 14.0, watchOS 7.0, tvOS 14.0" -define-availability "SwiftStdlib 5.4:macOS 11.3, iOS 14.5, watchOS 7.4, tvOS 14.5" -define-availability "SwiftStdlib 5.5:macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0" -define-availability "SwiftStdlib 5.6:macOS 12.3, iOS 15.4, watchOS 8.5, tvOS 15.4" -define-availability "SwiftStdlib 5.7:macOS 13.0, iOS 16.0, watchOS 9.0, tvOS 16.0" -define-availability "SwiftStdlib 5.8:macOS 13.3, iOS 16.4, watchOS 9.4, tvOS 16.4" -define-availability "SwiftStdlib 5.9:macOS 14.0, iOS 17.0, watchOS 10.0, tvOS 17.0" -define-availability "SwiftStdlib 5.10:macOS 14.4, iOS 17.4, watchOS 10.4, tvOS 17.4, visionOS 1.1" -define-availability "SwiftStdlib 6.0:macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0" -define-availability "SwiftStdlib 6.1:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999, visionOS 9999" -typo-correction-limit 10 -typecheck /Users/alex/src/swift/test/SourceKit/test.swift
1.	Apple Swift version 6.1-dev (LLVM 95f3fb07f8f5294, Swift 24e5a828e6ac67d)
2.	Compiling with effective version 4.1.50
3.	While evaluating request TypeCheckSourceFileRequest(source_file "/Users/alex/src/swift/test/SourceKit/test.swift")
4.	While type-checking statement at [/Users/alex/src/swift/test/SourceKit/test.swift:2:1 - line:2:26] RangeText="Binding<Bool>Binding<Bool"
5.	While type-checking expression at [/Users/alex/src/swift/test/SourceKit/test.swift:2:1 - line:2:26] RangeText="Binding<Bool>Binding<Bool"
6.	While type-checking-target starting at /Users/alex/src/swift/test/SourceKit/test.swift:2:1
 #0 0x00000001077b40e0 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/Users/alex/src/build/buildbot_incremental/swift-macosx-arm64/bin/swift-frontend+0x1053800e0)
 #1 0x00000001077b250c llvm::sys::RunSignalHandlers() (/Users/alex/src/build/buildbot_incremental/swift-macosx-arm64/bin/swift-frontend+0x10537e50c)
 #2 0x00000001077b472c SignalHandler(int) (/Users/alex/src/build/buildbot_incremental/swift-macosx-arm64/bin/swift-frontend+0x10538072c)
 #3 0x0000000183a64184 (/usr/lib/system/libsystem_platform.dylib+0x180484184)
 #4 0x000000010359d038 swift::constraints::DisjunctionStep::~DisjunctionStep() (/Users/alex/src/build/buildbot_incremental/swift-macosx-arm64/bin/swift-frontend+0x101169038)
 #5 0x000000010359bdc8 swift::constraints::DisjunctionStep::~DisjunctionStep() (/Users/alex/src/build/buildbot_incremental/swift-macosx-arm64/bin/swift-frontend+0x101167dc8)
 #6 0x000000010358d398 swift::constraints::ConstraintSystem::solveImpl(llvm::SmallVectorImpl<swift::constraints::Solution>&) (/Users/alex/src/build/buildbot_incremental/swift-macosx-arm64/bin/swift-frontend+0x101159398)
 #7 0x000000010361c3c4 swift::constraints::ConstraintSystem::salvage() (/Users/alex/src/build/buildbot_incremental/swift-macosx-arm64/bin/swift-frontend+0x1011e83c4)
 #8 0x000000010358e408 swift::constraints::ConstraintSystem::solve(swift::constraints::SyntacticElementTarget&, swift::FreeTypeVariableBinding) (/Users/alex/src/build/buildbot_incremental/swift-macosx-arm64/bin/swift-frontend+0x10115a408)
 #9 0x000000010370b264 swift::TypeChecker::typeCheckTarget(swift::constraints::SyntacticElementTarget&, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>) (/Users/alex/src/build/buildbot_incremental/swift-macosx-arm64/bin/swift-frontend+0x1012d7264)
#10 0x000000010370b0f8 swift::TypeChecker::typeCheckExpression(swift::constraints::SyntacticElementTarget&, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>) (/Users/alex/src/build/buildbot_incremental/swift-macosx-arm64/bin/swift-frontend+0x1012d70f8)
#11 0x000000010370afcc swift::TypeChecker::typeCheckExpression(swift::Expr*&, swift::DeclContext*, swift::constraints::ContextualTypeInfo, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>) (/Users/alex/src/build/buildbot_incremental/swift-macosx-arm64/bin/swift-frontend+0x1012d6fcc)
#12 0x00000001037d4608 (anonymous namespace)::StmtChecker::typeCheckASTNode(swift::ASTNode&) (/Users/alex/src/build/buildbot_incremental/swift-macosx-arm64/bin/swift-frontend+0x1013a0608)
#13 0x00000001037d7958 swift::ASTVisitor<(anonymous namespace)::StmtChecker, void, swift::Stmt*, void, void, void, void>::visit(swift::Stmt*) (/Users/alex/src/build/buildbot_incremental/swift-macosx-arm64/bin/swift-frontend+0x1013a3958)
#14 0x00000001037d6180 bool (anonymous namespace)::StmtChecker::typeCheckStmt<swift::BraceStmt>(swift::BraceStmt*&) (/Users/alex/src/build/buildbot_incremental/swift-macosx-arm64/bin/swift-frontend+0x1013a2180)
#15 0x00000001037d6224 swift::TypeChecker::typeCheckTopLevelCodeDecl(swift::TopLevelCodeDecl*) (/Users/alex/src/build/buildbot_incremental/swift-macosx-arm64/bin/swift-frontend+0x1013a2224)
#16 0x000000010381d4ac swift::TypeCheckSourceFileRequest::evaluate(swift::Evaluator&, swift::SourceFile*) const (/Users/alex/src/build/buildbot_incremental/swift-macosx-arm64/bin/swift-frontend+0x1013e94ac)
#17 0x000000010381ef94 swift::TypeCheckSourceFileRequest::OutputType swift::Evaluator::getResultUncached<swift::TypeCheckSourceFileRequest, swift::TypeCheckSourceFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckSourceFileRequest>(swift::Evaluator&, swift::TypeCheckSourceFileRequest, swift::TypeCheckSourceFileRequest::OutputType)::'lambda'()>(swift::TypeCheckSourceFileRequest const&, swift::TypeCheckSourceFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckSourceFileRequest>(swift::Evaluator&, swift::TypeCheckSourceFileRequest, swift::TypeCheckSourceFileRequest::OutputType)::'lambda'()) (/Users/alex/src/build/buildbot_incremental/swift-macosx-arm64/bin/swift-frontend+0x1013eaf94)
#18 0x000000010381d3bc swift::performTypeChecking(swift::SourceFile&) (/Users/alex/src/build/buildbot_incremental/swift-macosx-arm64/bin/swift-frontend+0x1013e93bc)
#19 0x00000001028b0444 bool llvm::function_ref<bool (swift::SourceFile&)>::callback_fn<swift::CompilerInstance::performSema()::$_0>(long, swift::SourceFile&) (/Users/alex/src/build/buildbot_incremental/swift-macosx-arm64/bin/swift-frontend+0x10047c444)
#20 0x00000001028a9fa8 swift::CompilerInstance::forEachFileToTypeCheck(llvm::function_ref<bool (swift::SourceFile&)>) (/Users/alex/src/build/buildbot_incremental/swift-macosx-arm64/bin/swift-frontend+0x100475fa8)
#21 0x00000001028a9eec swift::CompilerInstance::performSema() (/Users/alex/src/build/buildbot_incremental/swift-macosx-arm64/bin/swift-frontend+0x100475eec)
#22 0x00000001026853b0 withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) (/Users/alex/src/build/buildbot_incremental/swift-macosx-arm64/bin/swift-frontend+0x1002513b0)
#23 0x000000010267aea8 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) (/Users/alex/src/build/buildbot_incremental/swift-macosx-arm64/bin/swift-frontend+0x100246ea8)
#24 0x000000010267a5c8 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) (/Users/alex/src/build/buildbot_incremental/swift-macosx-arm64/bin/swift-frontend+0x1002465c8)
#25 0x000000010246dcc0 swift::mainEntry(int, char const**) (/Users/alex/src/build/buildbot_incremental/swift-macosx-arm64/bin/swift-frontend+0x100039cc0)
#26 0x00000001836ac274 
```

</p>
</details>

### PR DESCRIPTION
**Pull request by slavapestov**
When we retire a constraint, there is no guarantee that it is at the end of the list, so it is not correct to always reinsert it at the end of the list when the constraint comes out of retirement. Instead, remember the position where we removed it from, so that we can always reinsert it in the correct position. This allows us to replace some bespoke logic in CSStep.h with a call to `retireConstraint()`.

Fixes https://github.com/swiftlang/swift/issues/77008
Also fixes rdar://problem/138246764

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Review by xedin — APPROVED** [review]

**Comment by hjyamauchi** [comment]
Hi @slavapestov the windows rebranch CI started to fail: https://ci-external.swift.org/job/swift-rebranch-windows-toolchain/515/consoleText

```
Failed Tests (6):
  Swift(windows-x86_64) :: Concurrency/async_overload_filtering.swift
  Swift(windows-x86_64) :: Constraints/common_type.swift
  Swift(windows-x86_64) :: Constraints/init_literal_via_coercion.swift
  Swift(windows-x86_64) :: Constraints/one_way_solve.swift
  Swift(windows-x86_64) :: Constraints/overload_filtering.swift
  Swift(windows-x86_64) :: Constraints/result_builder_conjunction_selection.swift
```

Could this https://github.com/swiftlang/swift/pull/77152 from https://ci-external.swift.org/job/swift-rebranch-windows-toolchain/515/changes#58a6a64647aeb270897241d6b229c1ffe17c37dd 
be causing it? Sorry if I'm mistaken as I'm not familiar with the constraints :)

**Comment by hjyamauchi** [comment]
CC @bnbarham

**Comment by hjyamauchi** [comment]
Thanks for the fix @slavapestov

**Pull request merged**
