### PR TITLE
Add missing CHECK directives to the deabstraction_finished test

### PR DESCRIPTION
**Pull request by bgogul**
This is related to https://bugs.swift.org/browse/SR-8487

### CODE REVIEW

**Comment by bgogul** [comment]
@swift-ci please test tensorflow Linux

**Comment by bgogul** [comment]
@swift-ci please test tensorflow macOS

**Review by rxwei — APPROVED** [review]
Thanks!

**Review by mhong — APPROVED** [review]

**Comment by bgogul** [comment]
@swift-ci please test tensorflow Linux GPU

**Comment by bgogul** [comment]
Tests on Linux GPU passing now: https://ci-external.swift.org/view/Pull%20Request/job/swift-PR-TensorFlow-Linux/746/

**Pull request merged**
