### PR TITLE
[embedded] Make assert helper functions always inlined to avoid trap basic blocks from merging

### PR DESCRIPTION
**Pull request by kubamracek**
Various internal assert helpers are marked as `@inline(never)`, which makes sense if the code for the helpers is in a libswiftCore.dylib that ships with the OS, but this ends up causing some problems in Embedded Swift where all the stdlib code is linked into the client code and is also optimized against it. If a function has multiple calls to fatalError, assert preconditionFailure, etc. those end up inlining up to the point of the `@inline(never)` functions, and so we end up with IR of:

```
define {{.*}}@"$s4main6foobar1iySi_tF"{{.*}} {
entry:
  ...
1:
  call @_asssertionFailure
  unreachable
2:
  call @_asssertionFailure
  unreachable
}
```

And LLVM will merge the two blocks into one, which breaks the expectation that trap points are unique. What we ideally want in Embedded Swift, is to actually force inlining of `_asssertionFailure` so that the traps end up in the callee, and those are already prevented from merging.

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by rauhul** [comment]
Makes sense. Do we have a front end flag to allow these regions to be merged for the sake of codesize over debuggability?

**Comment by kubamracek** [comment]
Not that I'm aware of, though I do think we should add and expose that option (separately).

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by eeckstein** [comment]
Wouldn't `_assertionFailure` report the file and line number, which makes the message unique?

**Comment by kubamracek** [comment]
> Wouldn't _assertionFailure report the file and line number, which makes the message unique?

Only in Debug builds. In Release builds, what ends up happening is that _assertionFailure is just a trap, and we end up optimizing against that fact -- callers stop passing the filename/linenumber arguments because they're unused, and then the call sites become identical, and then LLVM happily merges them.

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by eeckstein — APPROVED** [review]
lgtm!

**Comment by kubamracek** [comment]
@swift-ci please test macOS platform

**Comment by kubamracek** [comment]
@swift-ci please test macOS platform

**Comment by kubamracek** [comment]
@swift-ci please test macOS platform

**Pull request merged**
