### PR TITLE
IRGen: fix statically initialized globals which contain an empty type.

### PR DESCRIPTION
**Pull request by eeckstein**
This caused a compiler assert or a miscompile

rdar://problem/34123143

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci smoke test and merge

**Comment by eeckstein** [comment]
smoke test macos

**Comment by eeckstein** [comment]
@swift-ci smoke test macos

**Comment by eeckstein** [comment]
@swift-ci Please smoke test OS X platform

**Review by jckarter — APPROVED** [review]
Looks good, thanks Erik!

**Pull request merged**
