### PR TITLE
Fix a ptrauth test that I broke in #34213

### PR DESCRIPTION
**Pull request by rjmccall**
I broke this in #34213.  Still not sure how the test run didn't catch this.

rdar://70104537

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Comment by rjmccall** [comment]
@swift-ci Please smoke test Linux

**Comment by shahmishal** [comment]
@swift-ci Please smoke test Linux

**Comment by compnerd** [comment]
The TSC tests timed out on Linux (I think that @brentdax was looking into that)

**Comment by compnerd** [comment]
@swift-ci please smoke test Linux platform

**Comment by brentdax** [comment]
Killed the test, as it was hanging. Fortunately, the fix should have landed in SwiftPM by now.

@swift-ci please smoke test Linux platform

**Comment by rjmccall** [comment]
Hooray, a Linux buiild passed.  Thank you, @brentdax and @compnerd.

**Pull request merged**
