### PR TITLE
Update swift-5.2-branch to build with Xcode 11.4

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test new Xcode

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test new Xcode

**Comment by shahmishal** [comment]
@swift-ci test new Xcode

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test

**Review by DougGregor — APPROVED** [review]

**Comment by shahmishal** [comment]
@swift-ci test windows

**Comment by shahmishal** [comment]
@swift-ci test new Xcode

**Comment by shahmishal** [comment]
```
Invalid parameter - S:
Invalid parameter - S:
Build step 'Execute Windows batch command' marked build as failure
```
Windows failure looks like related to the script in swift-5.2-branch. Going to merge this change, as it passed for Windows on master branch.

**Pull request merged**
