### PR TITLE
[Don't merge] docs: description of new mangling scheme, version 2

### PR DESCRIPTION
**Pull request by eeckstein**
This PR is a proposal for a new mangling scheme. It's still draft and probably the grammar contains several bugs. But it should give an idea how it could look like.

These are the main changes:

1) Change the order of the mangling to a post-fix like structure.

This is the biggest change.
It will help to get more common prefixes in the mangled names to optimize the trie in the mach-o object files.
The length of the mangled names will mostly stay the same but the order of 'operands' inside the mangling is more or less reversed.
This change also required to use different 'operator' characters in some cases.

2) Word-substitutions

Similar to the S-substitutions, but finer grained. See section 'Identifiers'.
Reduces the size of mangled names in general.

3) Combined substitutions

A more efficient way to mangle multiple S-substitutions.
Reduces the size of mangled names with lots of substitutions, e.g. specialized functions.

4) Change the '_T' prefix to '_S'

(on John's request)
Because it's basically a completely new mangling scheme.

### CODE REVIEW

**Comment by eeckstein** [comment]
This new version incorporates feedback from @jckarter 
Also I added mangling for partially specialized functions.

**Comment by eeckstein** [comment]
@slavapestov 
> Alternatively we could keep the old mangling format around until we're ready to do an ABI break there.
Yes, that's what I'm going to do.

**Comment by eeckstein** [comment]
@gottesmm 
>Since you are changing the prefix from _T => _S, we are probably going to have to change strip as well.

good point

**Comment by eeckstein** [comment]
@jckarter I addressed your comments in the second commit

**Comment by slavapestov** [comment]
Can this PR be closed now?

**Pull request closed without merging**
