### PR TITLE
ClangImporter: Support for subclass existentials

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please clean test

**Comment by slavapestov** [comment]
@swift-ci smoke test Linux

**Comment by slavapestov** [comment]
@aciidb0mb3r Can you take a look at the Linux test failure here? https://ci.swift.org/job/swift-PR-Linux/6876/consoleFull#-5114079ee1a197b-acac-4b17-83cf-a53b95139a76

**Comment by aciidb0mb3r** [comment]
Ah, that was a non-deterministic test. It was fixed by: https://github.com/apple/swift-package-manager/pull/1097

**Comment by slavapestov** [comment]
Thanks!

**Pull request merged**
