### PR TITLE
Sema: Make type resolution for EnumElementPattern less eager

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
Delay contextual type resolution for `EnumElementPattern` until `coercePatternToType` is called to further reduce the scope of `UnboundGenericType`, and use name lookup instead to resolve the pattern.

The definitive fix would be to move `CaseStmt` checking into the constraint system (AFAIK `CaseStmt` is the only remaining place where `EnumElementPattern` checking still relies on `coercePatternToType`).

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Review by slavapestov — APPROVED** [review]

**Review by CodaFi — APPROVED** [review]

**Comment by hamishknight** [comment]
What about cases where the contextual type is needed to resolve the case? I believe this will no longer compile with this change:

```swift
enum E {
  case e
}

struct S<T> {}
extension S where T == E {
  func foo(_ x: Any) {
    switch x {
    case T.e:
      break
    default:
      break
    }
  }
}
```

As you say, it would be nice if we could move this into the constraint system such that we resolve patterns while generating constraints, which would allow us to keep the generic opening contained and allow the above example to remain valid.

**Comment by AnthonyLatsis** [comment]
Argh.. well noticed. @CodaFi Should we revert this? Not sure if I can figure out the proper constraint-system-oriented fix in reasonable time, considering the regression.

**Comment by hamishknight** [comment]
Yeah IMO we should revert this if a fix for the above case isn't going to be landed soon.

**Pull request merged**
