### PR TITLE
Revert "Runtime: Only demangle symbolic references in constant memory."

### PR DESCRIPTION
**Pull request by jckarter**
This reverts commit 99842f991976ddc7b2c7e945e7d0c96c4601a075.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
Is this because it broke the JIT? Maybe JITted code should not use symbolic references at all, since we don't care about memory usage as much?

**Comment by jckarter** [comment]
@slavapestov In some cases that would require us to have two different metadata formats, which seems like a lot of complication only to support the integrated REPL and immediate mode. In the latter case, it's not clear to me that we *don't* care about memory usage; it seems like we should care about as much as we do for offline-compiled programs.

**Comment by jckarter** [comment]
Like @gparker42 noted, we also have to declare `_dyld_is_immutable` in the right way for it to be weak-linked for supporting older targets, which dyld's own headers don't do.

**Pull request merged**
