### PR TITLE
Refactor AreAllStoredPropertiesDefaultInitableRequest for Property Wrappers

### PR DESCRIPTION
**Pull request by CodaFi**
Do a bit of cleanup here. Also expand the storage check to query the
backing variable for any attached property wrappers. If these are not
default-initialized or default initializable then the generated
initializer will contain unfixable DI errors.

Resolves rdar://58495602

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
Technically, this removes a default initializer, even if that initializer was malformed

@swift-ci test source compatibility

**Comment by CodaFi** [comment]
⛵️

**Comment by slavapestov** [comment]
@CodaFi This needs a test case.

**Comment by CodaFi** [comment]
Writing one up before the CCC

**Pull request merged**
