### PR TITLE
test: make `round-trip-syntax-test` Python 3 friendly

### PR DESCRIPTION
**Pull request by compnerd**
Make the `round-trip-syntax-test` tool Python 3 friendly by tweaking the
open modes and using `reduce` from `functools` as it has been removed in
Python 3.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @tachoknight @drexin @akyrtzi

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please python lint

**Comment by compnerd** [comment]
@swift-ci please python lint

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Review by drexin — APPROVED** [review]

**Pull request merged**
