### PR TITLE
[Sema] Record opaque type decls for type reconstruction after creation instead of in the parser

### PR DESCRIPTION
**Pull request by angela-laar**
Initial work to record implicit opaque types in OpaqueResultTypeRequest for type reconstruction. For now, modules should continue to record opaque types only if the parser sees the `some` keyword (an explicit opaque type). 

Before modules can begin printing implicit some,  the type checker will need a way to we need to derive the opaque type decl from mangled name. I will add this in a secondary PR. 

Fixes rdar://102584541

### CODE REVIEW

**Comment by angela-laar** [comment]
@swiftci please test

**Comment by angela-laar** [comment]
@swift-ci Please test

**Comment by angela-laar** [comment]
@swift-ci please smoke test

**Comment by angela-laar** [comment]
@swift-ci please smoke test

**Comment by angela-laar** [comment]
@swift-ci please test macOS

**Comment by angela-laar** [comment]
@swift-ci please smoke test macOS

**Review by hborla — APPROVED** [review]

**Pull request merged**
