### PR TITLE
[GenPack] Always heapify metadata packs.

### PR DESCRIPTION
**Pull request by nate-chandler**
Until the optimization to leave packs on-stack is in place.  Even then, we'll want to keep this as a fallback and for functions where leaving them on-stack can't be done.

rdar://110123679

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by aschwaighofer — APPROVED** [review]
lgtm

**Comment by nate-chandler** [comment]
@swift-ci please test macos platform

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Pull request merged**
