### PR TITLE
Fix the computation of the re-borrow flags for guaranteed phi arguments

### PR DESCRIPTION
**Pull request by eeckstein**
Re-borrow flags were computed based on the presence of forwarding instructions in the incoming values.
This is not correct in all cases, because optimizations can optimize away forwarding instructions.

Now, compute the re-borrow flags based on the presence of an end_borrow in the transitive uses.
To do this:
1.  Automatically set the re-borrow flags for phi-arguments when creating an `end_borrow` or setting the operand of an `end_borrow`. This already  catches most of the cases.
2. For some optimizations it's required to explicitly update the re-borrow flags. This is done in `updateAllBorrowArguments` and `updateBorrowArguments`.

Re-borrow flags are only set, but never cleared. If an optimization creates a dead-end block by cutting off the control flow before an end_borrow, the re-borrow flags still have to remain without the possibility to re-calculate them from the (now missing) end_borrows.

Fixes a verifier crash: rdar://139280579

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci please test source compatibility

**Comment by eeckstein** [comment]
@swift-ci test macos

**Comment by eeckstein** [comment]
@swift-ci test

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Review by atrick — APPROVED** [review]
Nice!

> With the new re-borrow flag computation, verification can fail before the re-borrow flags are updated at the end of the pass.

This sort of thing is unfortunate. A good goal is to be able to verify SIL immediately after every transformation, not just after a pass. Otherwise, we don't know what SIL utilities are valid within the pass. I wonder why your other fixes are not sufficient to keep the reborrow flags in a valid state during LoopRotate. It should be enough to avoid rotating if a begin_borrow has no scope-ending uses and then to automatically update the reborrow flag when creating the new phi.

**Pull request merged**
