### PR TITLE
[stdlib] Kill old set/dictionary-specific bridging entrypoints

### PR DESCRIPTION
**Pull request by airspeedswift**
These can now just be expressed using `as?`/`as!`.

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by lorentey** [comment]
@swift-ci please benchmark

**Review by lorentey — APPROVED** [review]
So the performance regressions are gone now? Neat!

**Review by DougGregor — APPROVED** [review]
Wonderful, thank you!

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark staging

**Comment by airspeedswift** [comment]
@lorentey not so fast... I haven't actually benchmarked it yet, I was going to do it on the PR :)

**Comment by airspeedswift** [comment]
while also trying out the fancy new CI benchmarks...

**Comment by airspeedswift** [comment]
yay, new benchmarks ftw

Given removing these is an ABI break, I feel like this regression is livable as something we can merge to master and try and recoup. Dictionary bridging is +65% vs 4.1 currently so it's also giving up less than was recently gained.

**Comment by airspeedswift** [comment]
Also note, the benchmark is doing something in a tight loop that you should very much never do – bridge a dictionary of non-verbatim-bridged types.

**Comment by airspeedswift** [comment]
+ @parkera for the removal of the uses from Foundation.

**Review by parkera — APPROVED** [review]

**Comment by parkera** [comment]
cc @millenomi

**Pull request merged**
