### PR TITLE
[rebranch] update how libcxx is configured

### PR DESCRIPTION
**Pull request by edymtt**

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
This won't get past all the other compilation failures. I can either add it to mine, or just remove the commit that removes libcxx/install-libcxx and then merge that PR?

**Comment by bnbarham** [comment]
> As it's more convenient for you -- my main concern was to have a diff out to fix the issue you were seeing.

Thanks, really appreciate it :)

**Comment by bnbarham** [comment]
I included this in my changes, so feel free to close @edymtt. Thanks again!

**Pull request closed without merging**
