### PR TITLE
[Concurrency] Clear Slab's fake metadata pointer before freeing it.

### PR DESCRIPTION
**Pull request by mikeash**
This helps ensure that memory analysis tools don't get confused by leftover metadata pointers in reallocated memory that hasn't been initialized yet.

rdar://88494373

### CODE REVIEW

**Review by eeckstein — APPROVED** [review]
lgtm!

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test macos platform

**Comment by mikeash** [comment]
@swift-ci please test windows platform

**Review by al45tair — APPROVED** [review]

**Pull request merged**
