### PR TITLE
[AutoDiff] Fix windows build failure introduced in #29590.

### PR DESCRIPTION
**Pull request by rxwei**

### CODE REVIEW

**Comment by rxwei** [comment]
@compnerd is there a way to trigger a Windows build for this branch here?

**Comment by rxwei** [comment]
Actual this needs a different fix. Will push soon.

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Review by compnerd — APPROVED** [review]
Thanks!

**Comment by compnerd** [comment]
running on Azure: https://dev.azure.com/compnerd/swift-build/_build/results?buildId=25484&view=results

**Comment by compnerd** [comment]
I'm trying to get regular CI setup for Windows, and would like to get Windows CI going for tensorflow as well.  Longer term, migrating to master will prove to be a better solution for CI.

**Comment by compnerd** [comment]
The toolchain side of the build passed on Windows, this should be good to merge as soon as the macOS build is verified.

**Comment by compnerd** [comment]
The Linux GPU builder is inaccessible, merging.

**Pull request merged**
