### PR TITLE
[test] reenable sanitizer driver tests

### PR DESCRIPTION
**Pull request by aralisza**
reenable select sanitizer tests, they should pass in CI

rdar://64784401
rdar://72514092

### CODE REVIEW

**Comment by aralisza** [comment]
@swift-ci please test

**Comment by danliew-apple** [comment]
LGTM

**Comment by danliew-apple** [comment]
@nkcsgexi Just a heads up that we are re-enabling these tests. @aralisza cannot reproduce failures. If they start failing again please send this to me or @aralisza. If the failure is internal only please only disable there so that this test doesn't get disabled in places where it is passing.

**Review by ghost — APPROVED** [review]
LGTM

**Review by nkcsgexi — APPROVED** [review]
Thank you! Do we have equivalent tests in the swift-driver side?

**Comment by danliew-apple** [comment]
@nkcsgexi Not yet. @aralisza is looking into this.

**Pull request merged**
