### PR TITLE
[CMake] Install swiftinterface files alongside swiftmodules

### PR DESCRIPTION
**Pull request by jrose-apple**
This may not be their final destination, but at least this will get them into built toolchains, which means it'll be easier to do integration testing once all the other pieces are in place.

rdar://problem/43823937

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please build toolchain

**Comment by jrose-apple** [comment]
@swift-ci Please test Linux

**Review by Rostepher — APPROVED** [review]
This looks good to me! 👍

**Pull request merged**
