### PR TITLE
Merge tag 'swift-DEVELOPMENT-SNAPSHOT-2019-09-30-a' into tensorflow

### PR DESCRIPTION
**Pull request by burmako**

### CODE REVIEW

**Comment by burmako** [comment]
@swift-ci please test tensorflow

**Comment by burmako** [comment]
@swift-ci please test tensorflow

**Comment by burmako** [comment]
@swift-ci please test tensorflow

**Comment by burmako** [comment]
@swift-ci please test tensorflow

**Review by dan-zheng — APPROVED** [review]

**Comment by burmako** [comment]
@swift-ci please test tensorflow

**Comment by burmako** [comment]
@swift-ci please test tensorflow

**Comment by burmako** [comment]
@swift-ci please test tensorflow

**Comment by burmako** [comment]
Due to some reason, CI refuses to run on macOS, but I can confirm that I ran tests successfully on my laptop.

**Pull request merged**
