### PR TITLE
Rename UnsafePointer assign/initialize and eliminate Backward variants.

### PR DESCRIPTION
**Pull request by atrick**
As proposed in SE-0107: UnsafeRawPointer.

Also fixes the comments to clarify that source and self memory
must be disjoint.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci Please smoke test OS X.

This passes build-toolchain on both linux and darwin when including the corelibs PR:
https://github.com/apple/swift-corelibs-foundation/pull/452

**Comment by atrick** [comment]
@swift-ci Please smoke test OS X.

**Comment by jckarter** [comment]
Why eliminate the backward variants?

**Comment by atrick** [comment]
During proposal review, we agreed that we could add assumingNonOverlapping variants of assign(from:) and moveInitialize(from:) as a separate follow-up proposal if we want to remove the check for overlapping regions. In my benchmarks, I haven't seen a reason to do that yet.

I don't understand how anyone can use the "backward" variant of these API's without implementing the check that's already in the standard library.

From swift-evolution
---
The only value in having 2 APIs is that many times the user knows the regions are non-overlapping and may not want a runtime check. In that case forward copying makes more sense.

If the regions may overlap, and if the user somehow knows the relationship between pointers, then the compiler should also. Otherwise, if the pointer comparison is not done in the stdlib, we’re just forcing the user to do it, or allowing them to forget to do it.

**Comment by jckarter** [comment]
The cost of the check is probably miniscule, I agree. It seems to me there are plenty of places in Array's implementation when you know the direction of overlap, such as during insert/remove operations, but maybe the compiler can optimize out the branch in those cases already.

**Comment by jckarter** [comment]
If the cost of the branch is inconsequential, maybe we should push it into the bulk-move value witnesses. It would save a couple of vwtable slots if we don't need both variants.

**Comment by atrick** [comment]
I see one VWT entry that could be removed, I made a note to follow up on it...
<rdar://problem/27412867> Remove VWT entry for InitializeArrayWithTakeBackToFront

**Comment by jckarter** [comment]
Ah, you're right, we never added `assignArray` witnesses. Still worth saving a vwtable slot.

**Pull request merged**
