### PR TITLE
[stdlib] Remove optional comparison operators (SE-0121)

### PR DESCRIPTION
**Pull request by jtbandes**
#### What's in this pull request?

An "implementation" (it's pretty much just deleting code) of [SE-0121](https://github.com/apple/swift-evolution/blob/master/proposals/0121-remove-optional-comparison-operators.md): removing the versions of `<`, `<=`, `>`, and `>=` which accept Optional operands.

---

Before merging this pull request to apple/swift repository:
- [x] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

A smoke test on macOS does the following:
1. Builds the compiler incrementally.
2. Builds the standard library only for macOS. Simulator standard libraries and
   device standard libraries are not built.
3. lldb is not built.
4. The test and validation-test targets are run only for macOS. The optimized
   version of these tests are not run.

A smoke test on Linux does the following:
1. Builds the compiler incrementally.
2. Builds the standard library incrementally.
3. lldb is built incrementally.
4. The swift test and validation-test targets are run. The optimized version of these
   tests are not run.
5. lldb is tested.

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by CodaFi** [comment]
Congratulations on the proposal acceptance Jacob!

@swift-ci please test and merge.

**Comment by jtbandes** [comment]
Thanks! I haven't tested this with corelibs-foundation, so may have missed some uses. I guess we'll see :)

**Comment by jtbandes** [comment]
OK, I've created apple/swift-package-manager#515 and apple/swift-corelibs-foundation#459 to remove the few uses of these operators. Once those are merged we can re-run this build.

**Comment by jtbandes** [comment]
@CodaFi Can you re-trigger CI? Assuming it automatically pulls the latest swiftpm and corelibs-foundation, I think the build should work now.

**Comment by parkera** [comment]
@swift-ci Please test and merge

**Comment by jtbandes** [comment]
OK, another try @parkera, if you don't mind 😄

**Comment by gribozavr** [comment]
@swift-ci Please test and merge

**Comment by gribozavr** [comment]
@jtbandes 

```
Foundation/IndexSet.swift:440:31: error: value of optional type 'Element?' not unwrapped; did you mean to use '!' or '?'?
        if range.lowerBound > last || (range.upperBound - 1) < first {
```

**Comment by jtbandes** [comment]
@gribozavr yep, I made a PR to fix that: https://github.com/apple/swift-corelibs-foundation/issues/464

**Comment by moiseev** [comment]
@swift-ci Please test and merge

**Comment by jtbandes** [comment]
@moiseev I think I've fixed the additional test failures. Building/testing locally now.

**Comment by gribozavr** [comment]
@swift-ci Please test and merge

**Comment by jtbandes** [comment]
Failure looks unrelated:

```
Command 2: "python" "/home/buildnode/jenkins/workspace/swift-PR-Linux/swift-integration-tests/repl/test-repl-glibc.py" "/home/buildnode/jenkins/workspace/swift-PR-Linux/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swift"
Command 2 Result: 1
Command 2 Output:
None

Command 2 Stderr:
Traceback (most recent call last):
  File "/home/buildnode/jenkins/workspace/swift-PR-Linux/swift-integration-tests/repl/test-repl-glibc.py", line 35, in <module>
    repl.expect('\r\nhello, world.*\r\n')
  File "/usr/lib/python2.7/dist-packages/pexpect/__init__.py", line 1418, in expect
    timeout, searchwindowsize)
  File "/usr/lib/python2.7/dist-packages/pexpect/__init__.py", line 1433, in expect_list
    timeout, searchwindowsize)
  File "/usr/lib/python2.7/dist-packages/pexpect/__init__.py", line 1535, in expect_loop
    raise TIMEOUT(str(err) + '\n' + str(self))
pexpect.TIMEOUT: Timeout exceeded.
```

**Comment by jtbandes** [comment]
🎊

**Pull request merged**
