### PR TITLE
[test] Add explicit targets to tests depending on the default

### PR DESCRIPTION
**Pull request by benlangmuir**
Add specific deployment target versions to some tests that need to test 10.x-specific behaviours and are currently depending on the default deployment target.

Certain tests were only checking either the stable or unstable ABI depending on the platform the test was running. In those cases I doubled up the checks so that we would test both cases on platforms that supported it. This might use a bit of extra time on targets that only support the stable ABI, but it seemed worth it for the additional coverage in CI.

### CODE REVIEW

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please test

**Review by tshortli — APPROVED** [review]

**Pull request merged**
