### PR TITLE
[SR-7076] Codable tests for ContiguousArray

### PR DESCRIPTION
**Pull request by benrimmington**
<https://bugs.swift.org/browse/SR-7076>

Follow-up to apple/swift#20715

### CODE REVIEW

**Comment by benrimmington** [comment]
@anayini @moiseev Please review

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by moiseev** [comment]
LGTM

**Comment by benrimmington** [comment]
@moiseev All checks have passed. Can this be merged now?

**Comment by anayini** [comment]
@benrimmington - Thanks so much - sorry I didn't get around to this :(

**Pull request merged**
