### PR TITLE
[NFC] Replace StringMap<char, A> with StringSet<A>

### PR DESCRIPTION
**Pull request by varungandhi-apple**

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test

**Review by jrose-apple — APPROVED** [review]
Ooh, I thought I had gotten all of those.

**Comment by varungandhi-apple** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@varungandhi-apple Thank you! Originally when I added `TransactionStrings` `StringSet` didn't have a constructor which accepted an allocator as an argument.

**Comment by varungandhi-apple** [comment]
@xedin yep, I recognize that; this is a relatively new addition to the StringSet API.

**Pull request merged**
