### PR TITLE
Unsafe*Pointer types should not be Sendable.

### PR DESCRIPTION
**Pull request by atrick**
To send them across actors, they need to be wrapped in an '@unchecked
Sendable' type. Typically such a wrapper type would be be responsible
for ensuring its uniqueness or immutability.

Inferring Sendability for arbitrary types that contain Unsafe*Pointers
would introduce race conditions without warning or any explicit
acknoledgement from the programmer that the pointer is in fact unique.

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test

**Comment by atrick** [comment]
@swift-ci smoke test

**Review by lorentey — APPROVED** [review]
This looks good to me! 🚢

**Comment by atrick** [comment]
@swift-ci smoke test

**Pull request merged**
