### PR TITLE
Added fix-it to add the `@unchecked Sendable` conformance if it is not re-stated

### LINKED ISSUE #74500: Fix-it to restate inherited '@unchecked Sendable' conformance
### Motivation

Given the scenario, I think it is very likely that developers will want to either just automatically re-state the conformance or opt into full checking (which doesn't currently work: https://github.com/apple/swift/issues/74498)

```swift
class A: @unchecked Sendable {
}

// warning: class 'B' must restate inherited '@unchecked Sendable' conformance
class B: A {
}
```

### Proposed solution

Fix it to add the `@unchecked Sendable`

### Alternatives considered

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tplaymeow**
- Added `@unchecked Sendable` fix-it
- Updated test

Resolves https://github.com/swiftlang/swift/issues/74500.

### CODE REVIEW

**Comment by ktoso** [comment]
Good fix, let's see if that's all the places that needed adjustment

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by tplaymeow** [comment]
Hi @ktoso! It looks like the tests have successfully passed. Could you please review it?

**Review by ktoso — APPROVED** [review]
Looks good to me, low risk since just adding the fixme.

Thank you!

**Pull request merged**
