### PR TITLE
Add an option for an explicit interface build without an additional Compile SubInstance

### PR DESCRIPTION
**Pull request by artemcm**
- Refactor `ModuleInterfaceBuilder` to separate `CompilerInstance` setup logic from compilation logic (moved to `ExplicitModuleInterfaceBuilder`).
- Factor out reading flags/version from an interface from setting up a Compiler subinstance.
- Invoke Explicit Interface Build when `-explicit-interface-module-build` is specified on a `-compile-module-from-interface` frontend action, using the `CompilerInstance` instantiated directly from the command-line in order to build the module.

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci please test

**Review by tshortli — APPROVED** [review]

**Review by nkcsgexi — APPROVED** [review]
Makes sense to me!

**Comment by artemcm** [comment]
@swift-ci please test

**Comment by artemcm** [comment]
@swift-ci please test

**Pull request merged**
