### PR TITLE
[NO-MERGE] Benchmarking Enabling Exclusivity Checks on Stdlib

### PR DESCRIPTION
**Pull request by gottesmm**

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@atrick

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by gottesmm** [comment]
@swift-ci smoke benchmark

**Comment by slavapestov** [comment]
Not bad!

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by gottesmm** [comment]
Keep in mind this is just for stdlibCore so that we can land @devincoughlin's work to fix exclusivity/keypaths.

**Pull request closed without merging**
