### PR TITLE
[AutoDiff] Fix forward-mode crashes related to tangent buffers

### PR DESCRIPTION
**Pull request by dan-zheng**
Cherry-pick of https://github.com/apple/swift/pull/33633 to `tensorflow` branch.

---

Fixes foward-mode crashed related to:
- Missing tangent buffers for non-wrt `inout` parameters.
- Tangent buffers not being initialized due to the corresponding original
  buffer intialization instructions being non-active.
- Non-varied indirect results not being initialized.
- `emitDestroyValue` crashes due to `TangentVector` value category mismatch.

Resolves TF-984 and SR-13447.

### CODE REVIEW

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Review by efremale — APPROVED** [review]

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
Test failures are known (missing CI machine dependencies) and unrelated. Merging now.

**Pull request merged**
