### PR TITLE
[SR-15049][Diagnostics] Infer throwing in async let patter synthesized auto closure for SelfCallExpr initialization

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
async let pattern is wrapped in an synthesized auto closure by the rewriter and those implicit auto closure are being considered in effects diagnostics which leads to unwanted errors and misleading `autoclosure` messages. 
This PR is basically:
* Tracking `async let _:<Type>` as async let pattern binding declaration. (The current logic doesn't account this as being an async let pattern)
* Making implicit synthesized auto closure transparent to some effects diagnostic heuristics.

Resolves SR-15049.

### CODE REVIEW

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test

**Review by xedin — COMMENTED** [review]
If I understand it correctly the issue here is not that type-effects checker is wrong, but that autoclosure is not marked as `throws` although it should be, because `async let` should infer all of the attributes of the underlying call? Is that correct @DougGregor?

**Comment by LucianoPAlmeida** [comment]
> If I understand it correctly the issue here is not that type-effects checker is wrong, but that autoclosure is not marked as `throws` although it should be, because `async let` should infer all of the attributes of the underlying call? Is that correct @DougGregor?

It does makes sense @xedin, I'll look into it a little bit more but it seems like `TypeChecker::canThrow` here https://github.com/apple/swift/blob/a54213c313ae7e8ee3929bed7416815157e20867/lib/Sema/CSApply.cpp#L8335
should detect the throw in underlying call. 
Thank you for the great feedback as always :)

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test MacOS platform

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test MacOS platform

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test MacOS platform

**Comment by LucianoPAlmeida** [comment]
This PR was closed just because I was having some [issues with the build locally](https://forums.swift.org/t/ninja-build-local-failure/55613) and keep pushing to run on the CI was not productive. A new PR ready for feedback is opened now :) 
#41661

**Pull request closed without merging**
