### PR TITLE
Added Build Android Toolchain section

### PR DESCRIPTION
**Pull request by amraboelela**
This update is needed to show how to run the newly added android/build-toolchain script

### CODE REVIEW

**Comment by amraboelela** [comment]
In this PR, I moved the content of README.md in https://github.com/apple/swift/pull/11870 to the existing docs/Android.md

**Comment by amraboelela** [comment]
@modocache pls check this

**Comment by modocache** [comment]
@swift-ci please smoke test and merge

**Comment by CodaFi** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
