### PR TITLE
[5.7] [stdlib] fix unaligned loads of large SIMD vectors on x86_64

### PR DESCRIPTION
**Pull request by glessard**
Unaligned loads of SIMD vectors with alignment larger than 8 was failing on Intel platforms. This implements a library-level workaround until a compiler correction can be validated.

Cherry-pick of https://github.com/apple/swift/pull/60025 and https://github.com/apple/swift/pull/60061.

Addresses rdar://96918344.

### CODE REVIEW

**Comment by glessard** [comment]
@swift-ci please test

**Comment by glessard** [comment]
@swift-ci please test

**Comment by glessard** [comment]
@swift-ci please test

**Comment by glessard** [comment]
@swift-ci please test

**Comment by glessard** [comment]
Test failure is related to docc. The test introduced here succeeded.

**Review by stephentyrone — APPROVED** [review]

**Comment by glessard** [comment]
===== Submission Nomination Information =====
Risk Level (Low | Medium | High): Low
Risk Details:
This reimplements a newly introduced API (Unsafe{Mutable}RawPointer.loadUnaligned) using a common C idiom (swiftified) instead of using a Swift compiler builtin. This is due to a newly-identified assumption baked into the Swift runtime, which made x86_64 programs using this API crash when trying to load e.g. a large SIMD vector from an unaligned address.
The standard library needs to be rebuild, and any users of loadUnaligned.
Reward Level (Low | Medium | High): High.
Reward Details:
The new API will now function as expected in all cases.
If we don’t take this fix, the API doesn’t always do what it’s supposed to. In particular, many Intel binaries trying to use this API may crash.
All of these are, by definition, new adopters. Note that the old recommended workarounds for unaligned loads are still applicable.
Code Reviewed By: Steve Canon
Testing Details: Confirmed in CI (with new test).

**Pull request merged**
