### PR TITLE
Fix linking libuuid on Windows

### PR DESCRIPTION
**Pull request by hughbe**
We use Windows SDKs to create UUID's (see #5949)

We have to link `rpcrt4.lib` to get these Win32 APIs - this is available on all Windows PCs.

Extracted from #5904

### CODE REVIEW

**Comment by compnerd** [comment]
This is not globally available.  The store partition does not permit it.  Can we change the UUID generation to call `::CoCreateGuid` instead of `CreateUuid`?  That would link against `Ole32.lib` instead, and would be more portable across Windows families.

**Comment by hughbe** [comment]
Hmm, according to the docs, CoCreatsGuid is a kind of wrapper of UUIDCreate:

> The CoCreateGuid function calls the RPC function UuidCreate, which creates a GUID, a globally unique 128-bit integer. Use CoCreateGuid when you need an absolutely unique number that you will use as a persistent identifier in a distributed environment.To a very high degree of certainty, this function returns a unique value – no other invocation, on the same or any other system (networked or not), should return the same value.

**Comment by compnerd** [comment]
Right :)  It's merely about Microsoft blessing it for more broad usage.

**Comment by hughbe** [comment]
Yeah, I was just investigating - I have pushed a change to use `ole32.lib`, and changed `UUIDCreate` to `CoCreateGuid` as you suggested. I've left everything renamed to `uuid` and used `UUID` instead of `GUID`, to simplify the diff. This doesn't matter, as `<objbase.h>` includes `<rpc.h>` so these definitions still exist. I think!

**Review by compnerd — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by hughbe** [comment]
@slavapestov I'm getting a 404 for one of the test runs: https://ci.swift.org/job/swift-PR-osx/4766/

Seems to be blocking the PR from merging

**Pull request merged**
