### PR TITLE
[stdlib] Fixes for Unicode 9 Grapheme Clusters and Flags

### PR DESCRIPTION
**Pull request by johnno1962**
Hi, This PR resolves a few outstanding problems segmenting complex unicode sequences in stdlib specifically handling of skin tone modifiers, zero width joiners and segmenting flags correctly.

At the moment the following code prints the following using Xcode 8.1 repl:

```
Welcome to Apple Swift version 3.0.2 (swiftlang-800.0.61 clang-800.0.42.1). Type :help for assistance.
  1> func segment(_ str: String) {
  2.     print(str)
  3.     var start = str.startIndex
  4.     while start < str.endIndex {
  5.         let next = str.index(start, offsetBy:1)
  6.         print(str[start..<next])
  7.         start = next
  8.     }
  9. }
 10.
 11. segment("👦🏾")
 12. segment("👨‍👨‍👧‍👧")
 13. segment("🇭🇺🇭🇺🇭🇺")
👦🏾
👦
🏾
👨‍👨‍👧‍👧
👨👨‍
👨👨‍
👧👧‍
👧
🇭🇺🇭🇺🇭🇺
🇭🇺🇭🇺🇭🇺
```

The skin tone is not combined with the emoji, the family emoji characters are not combined into one grapheme and sequences of flags are treated as one character. Placing some extra code into stdlib/public/core/StringCharacterView.swift handles these cases and results in the following correct output in the repl and compiled programs:

```
(swift) func segment(_ str: String) {
              print(str)
              var start = str.startIndex
              while start < str.endIndex {
                  let next = str.index(start, offsetBy:1)
                  print(str[start..<next])
                  start = next
            }
        }
(swift)
(swift) segment("👦\U+1F3FE")
👦🏾
👦🏾
(swift) segment("👨\U+200D👨\U+200D👧\U+200D👧")
👨‍👨‍👧‍👧
👨‍👨‍👧‍👧
(swift) segment("🇭🇺🇭🇺🇭🇺")
🇭🇺🇭🇺🇭🇺
🇭🇺
🇭🇺
🇭🇺
(swift)
```

The extra code required results in a 1% speed regression in the following code:

```Swift
    var str = "12345678901234567890123456789012345678901234567890"

    for i in 0..<10 {
        str += str
    }

    let len = str.utf16.count
    for i in 0..<5000 {
        str.index( str.startIndex, offsetBy: len )
    }
```

Raw data:

    print( (36.989+37.337+36.992+37.369)/4.0 ) // 37.17175 forward original
    print( (78.057+78.092+78.305+77.454)/4.0 ) // 77.977 backward original
    print( (37.689+37.558+37.550+37.421)/4.0 ) // 37.5545 forward modified
    print( (79.010+79.085+79.070+79.129)/4.0 ) // 79.0735 backward modified

    print( (37.5545/37.17175-1)*100 ) // 1.02% speed regression forward
    print( (79.0735/77.977-1)*100 ) // 1.40% speed regression backward

Perhaps it would be good not to bake Unicode knowledge into StringCharacterView.swift or modify the existing UnicodeTrie code instead but I couldn’t find an alternative that wasn’t slower or more difficult to understand. Flags are a special case and could never be done using the Trie as they are coded in pairs.

Resolves https://bugs.swift.org/browse/SR-2413, rdar://23051890, 20511834.

### CODE REVIEW

**Comment by xwu** [comment]
I'm by no means an expert on this, but if I understand correctly, Swift is finding clusters according to Unicode 8 rules and just hasn't migrated to Unicode 9 yet. I believe there's an outstanding patch already to update Swift to use Unicode 9, which (when the kinks are worked out) should take care of this without special-case code.

**Comment by johnno1962** [comment]
Hi @xwu, you’re right having started out looking at the problem with flags (regional indicators) I got drawn into the full Unicode 9 port of the Trie instead of the special casing. The PR is at the point of only 13 out of the new 822 tests failing which I’ve muzzled for now in utils/GYBUnicodeDataUtils.py.

I think the special casing is still required for flag emojis however as they come in pairs and it’s not possible using the Trie approach to break sequences of multiple flags.

Anyway. see what you can salvage from the PR which is in fairly good shape..

**Comment by xwu** [comment]
@johnno1962 Probably won't be able to look into this much in the next few weeks, but all I was trying to say was that I believe someone on the core team, by the sounds of the bug report, is already assigned to the Unicode 9 issue. I doubt your approach to flag emoji is correct, as only valid pairs of region indicators make for one extended grapheme cluster unless I'm mistaken. How did you conclude that the Trie approach can't handle flags?

**Comment by xwu** [comment]
Update: I couldn't resist reading some more. As far as I can tell, Swift is segmenting flag emoji correctly. According to UAX 29 (Unicode Text Segmentation): 

"The base [for a grapheme cluster] can be single characters, or be any sequence of Hangul Jamo characters that form a Hangul Syllable, as defined by D133 in The Unicode Standard, or be any sequence of Regional_Indicator (RI) characters. The RI characters are used in pairs to denote Emoji national flag symbols corresponding to ISO country codes. Sequences of more than two RI characters should be separated by other characters, such as U+200B ZERO WIDTH SPACE (ZWSP)."

Thus, any run of contiguous regional indicators without a zero-width space *should* be segmented as they are. If that seems counterintuitive, it'd be a bug in Unicode and not in Swift.

**Comment by ole** [comment]
@xwu I agree that Swift handles flags correctly (according to Unicode 8.0). For example, this counts as one character:

```swift
let s = "🇩🇪🇺🇸"
s.characters.count // 1
```

Furthermore, there is no concept of "valid" and "invalid" combinations of regional indicator symbols.

However, it seems the rule has changed slightly in Unicode 9.0. In Unicode 8.0, it reads as follows:

> GB8a: Do not break between regional indicator symbols.
> (http://www.unicode.org/reports/tr29/tr29-27.html#GB8a)

In Unicode 9.0, the rule says:

> GB12: Do not break within emoji flag sequences. That is, do not break between regional indicator (RI) symbols if there is an odd number of RI characters before the break point.
> (http://unicode.org/reports/tr29/#GB12)

I.e. currently Swift also treats a string of three (or five) regional indicators as one character:

```swift
let s = "🇩🇪🇽"
s.characters.count // 1
```

I haven't tested this in Unicode 9.0, but from the wording of the rule I would expect this to change when Swift adopts Unicode 9.

**Comment by xwu** [comment]
@ole Ah yes, you're quite right. Looks like the Swift core team is already on to it:

```
// FIXME(ABI)#74 : don't mark this type versioned, or any of its APIs inlineable.
// Grapheme cluster segmentation uses a completely different algorithm in
// Unicode 9.0.
```

For that reason I think it's premature to insert a special case in `stdlib/public/core/StringCharacterView.swift` when it's clear that the core team has an ongoing plan for implementation of Unicode 9 that's just not yet fully baked. For now, Swift is doing perfectly standards-compliant Unicode 8, which is the logical state of things until Unicode 9.

**Comment by ole** [comment]
I agree.

**Comment by johnno1962** [comment]
Clearly there is a higher power at work here… I’ll downgrade this special casing code to “one alternative that may help implementing Unicode 9” if it should break after an even number of RI chars. It sounds like this might be the case from the document you mention which goes on to say “otherwise break everywhere".

**Comment by xwu** [comment]
Just based off of comments in PR #3125, it looks like we'll need a state machine to implement Unicode 9, given the new rule `(E_Base | EBG) Extend* × E_Modifier`. AFAIK, a state machine will make it possible to implement the new RI segmentation rule as well.

Since we can't have Unicode 9 without the state machine, and since RI parsing will naturally fall out of that implementation, I'd imagine that's the preferred solution to work towards. If I have some spare time over the holidays I might try to learn some more about how difficult that might be, but I'd bet money that core team members are already on it.

**Pull request closed without merging**
