### PR TITLE
🍒[5.9][Concurrency] SerialExecutor.isSameExclusiveExecutionContext

### PR DESCRIPTION
**Pull request by ktoso**
**Description:** This adds the ability for different SerialExecutor _instances_ opt into "complex equality" which they can implement themselfes. This logic is opted in by returning the executor as an `UnownedSerialExecutor(complexEquality: self)`, and then the Swift runtime may choose to call the `isSameExclusiveExecutionContext` on the executor allowing it to implement "those two executors are using the same thread/queue and therefore should be considered the same exclusive context".
**Risk:** Low, the API is feature guarded and additive with a default implementation. 
**Review by:** @jckarter @rokhinip @rjmccall 
**Testing:** CI testing; tests were added for this specific pattern.
**Original PR:** https://github.com/apple/swift/pull/64604
**Radar:** rdar://107174704

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please test linux

**Comment by ktoso** [comment]
@swift-ci please test macOS
@swift-ci please test Windows

**Comment by ktoso** [comment]
@swift-ci please test macOS

**Review by DougGregor — APPROVED** [review]

**Pull request merged**
