### PR TITLE
[Distributed] rename _Distributed to module 

### PR DESCRIPTION
**Pull request by ktoso**
Module rename is pretty tricky so we have to land it sooner rather than later.

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Review by xedin — APPROVED** [review]

**Comment by ktoso** [comment]
Flag removal in https://github.com/apple/swift/pull/41780

The module rename has to wait for a while.

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
Rebased and ready to go when CI stops being broken by unrelated tests.

**Comment by ktoso** [comment]
Unblocked by https://github.com/apple/swift-syntax/pull/371/files

**Comment by ktoso** [comment]
@swift-ci please clean test and merge

**Comment by ktoso** [comment]
@swift-ci please smoke test and merge

**Comment by ktoso** [comment]
Sigh... a new file appeared on `main` so this PR made that break, rebased again.

**Comment by ktoso** [comment]
@swift-ci please smoke test and merge

**Comment by compnerd** [comment]
This broke the Windows build because you didn't update all the references: https://ci-external.swift.org/job/oss-swift-windows-toolchain-x86_64-vs2019/1154/

**Pull request merged**
