### PR TITLE
[stdlib] Suppress noisy warnings

### PR DESCRIPTION
**Pull request by dabrahams**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

We don't have a way yet to say "this is deprecated for users, but let
the stdlib use it without complaining" so we need to do refactoring
shenanigans.

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please test and merge

**Comment by dabrahams** [comment]
@swift-ci Please test Linux platform

**Comment by gottesmm** [comment]
@swift-ci Please test and merge

**Comment by dabrahams** [comment]
@swift-ci Please smoke test Linux platform

**Pull request merged**
