### PR TITLE
Fix memory violation when build record is bad.

### PR DESCRIPTION
**Pull request by davidungar**
Return a string instead of a StringRef for why incrementality is being disabled.
rdar://57437165 & rdar://57540981

### CODE REVIEW

**Comment by davidungar** [comment]
@swift-ci please smoke test

**Comment by davidungar** [comment]
@swift-ci please smoke test asan

**Comment by shahmishal** [comment]
@swift-ci test macOS

**Comment by shahmishal** [comment]
@swift-ci please asan test

**Comment by davidungar** [comment]
@swift-ci please asan test

**Comment by shahmishal** [comment]
@swift-ci please asan test

**Comment by shahmishal** [comment]
@swift-ci please test

**Pull request merged**
