### PR TITLE
[Tests] Add tests for unary operators on tuples

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
Adds tests for [SR-294](https://bugs.swift.org/browse/SR-294), resolved in [#19580](https://github.com/apple/swift/pull/19580)

@slavapestov

### CODE REVIEW

**Review by slavapestov — COMMENTED** [review]
Perhaps this should be incorporated into an existing test file. Otherwise looks good.

**Comment by AnthonyLatsis** [comment]
I tried to find a file with a similar "theme" in Sema, but they seem to be off the subject everywhere. How about [/expr/expressions.swift](https://github.com/apple/swift/blob/master/test/expr/expressions.swift)?

**Comment by slavapestov** [comment]
How about `test/decl/func/operator.swift`?

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
Linux failure isn't you:

```
00:26:12 ********************
00:26:12 Testing Time: 14.29s
00:26:12 ********************
00:26:12 Failing Tests (1):
00:26:12     SwiftXCTestFunctionalTests :: Asynchronous/Expectations/main.swift
```

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux

**Comment by AnthonyLatsis** [comment]
Does it fail from time to time?

**Pull request merged**
