### PR TITLE
Introduce SymbolSourceMapRequest

### PR DESCRIPTION
**Pull request by hamishknight**
Add a request that leverages the TBDGenVisitor to produce a mapping from a mangled symbol name to the SIL or IR entity that emits it. This will be used to enable lazy compilation where only a specific set of symbols need to be emitted

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test macOS

**Review by DougGregor — APPROVED** [review]
Very nice!

**Comment by nkcsgexi** [comment]
Super cool, Thank you, @hamishknight !

**Pull request merged**
