### PR TITLE
SILGen: Use VarDecl::getInterfaceType instead of getType in emitForeignToNativeThunk.

### PR DESCRIPTION
**Pull request by jckarter**
getType() only gets set if the decl is type-checked, and is deprecated moreover. Fixes rdar://problem/32280288.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Comment by jckarter** [comment]
Unrelated test failure on Linux:

```
FAIL dispatch_starfish (exit status: 1)
```

@phausler Would you know who to ping about Linux libdispatch?

**Comment by jckarter** [comment]
@swift-ci Please smoke test Linux

**Comment by phausler** [comment]
@das or @dgrove-oss might have some insight here (or know the right people to look at it)

**Comment by dgrove-oss** [comment]
I'll look at upping the max latency in the dispatch tests that are time sensitive.

**Pull request merged**
