### PR TITLE
Update Python build scripts to use the print function

### PR DESCRIPTION
**Pull request by alexwlchan**
In Python 3, 'print' was changed from a statement to a function.  Using
the __future__ module allows scripts to use print function whether
running with Python 2.6+ or Python 3.x.  This commit changes as many
instances of print as I could find to use the print function and the
__future__ module.

This is part of ongoing work to get the Python scripts running under
both Python 2 and 3; see PR #90.

### CODE REVIEW

**Comment by modocache** [comment]
Thanks for continuing to push this through!! :+1:

How does this pull request relate to #90? You mentioned you'd split up #90, but this pull request is even larger than that one.

**Comment by alexwlchan** [comment]
@modocache Two differences:

* The original PR was just looking for files that ended in *.py, which turns out not to be a good indicator of whether a file uses Python. I missed a lot of stuff. Now I’m just grepping for anything that looks like a print statement.
* The original PR was an attempt to get a clean run of all scripts against Python 3, which involves a substantial number of changes. This is a single, specific change that is hopefully easier to review.

**Comment by modocache** [comment]
Ah, gotcha. Well, all the changes look good to me!! Looks like you have a merge conflict, though.

**Comment by alexwlchan** [comment]
Rebased; merged conflicts fixed.

**Comment by gribozavr** [comment]
LGTM, tested on Ubuntu 14.04 and OS X.

**Comment by practicalswift** [comment]
@alexwlchan This is what I've used to find all Python files in the repo:

`(git grep '#.*python'; find . -name '*.py' -type f) | grep -v .gitignore | sed 's|^./||g' | cut -f1 -d: | sort | uniq`

Nice work cleaning up BTW! :-)

**Pull request merged**
