### PR TITLE
Unblock The master -> master-next Automerger

### PR DESCRIPTION
**Pull request by CodaFi**

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
⚠️ Please Don't Merge This Until It's Finished Smoke Testing ⚠️

**Review by stephentyrone — APPROVED** [review]
I don't see anything suspicious, so let's go ahead with this once smoke test clears.

**Comment by CodaFi** [comment]
Whoops, took the internal-master side of the FineGrainedDependencyDriverGraph merge instead of the master side.

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
⛵️

**Comment by stephentyrone** [comment]
The OS X failure that remained is a little suspicious, but this is certainly less broken post-merge than it was before, and we can chase that down separately if we need to. Getting the merge bots unblocked is more important right now.

**Pull request merged**
