### PR TITLE
Revert "Fix existential specializer for unowned ownership"

### PR DESCRIPTION
**Pull request by compnerd**
Reverts swiftlang/swift#77933

This might be causing https://github.com/swiftlang/swift/issues/77955

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by meg-gupta** [comment]
@compnerd It doesn't look like https://github.com/swiftlang/swift/pull/77933 is in the blamelist for https://ci-external.swift.org/job/swift-main-windows-toolchain/867/

**Comment by hjyamauchi** [comment]
I reduced it to a small test: https://github.com/swiftlang/swift/issues/77955

**Comment by compnerd** [comment]
@meg-gupta sure, but, we don't have a specific change that we can pin it to right now. Consider https://ci-external.swift.org/job/swift-PR-windows/33954/ ... the change is to a shell expansion and it shows up with the same thing. Whatever the cause is, it is preventing any changes from going in.

**Pull request closed without merging**
