### PR TITLE
Scale benchmarks with 6-figure times back to 5-figures

### PR DESCRIPTION
**Pull request by dabrahams**
They seem to take disproportionately long in the benchmark suite.

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please benchmark

**Comment by dabrahams** [comment]
@swift-ci Please smoke test

**Comment by dabrahams** [comment]
@swift-ci Please smoke benchmark

**Comment by dabrahams** [comment]
@swift-ci Please smoke benchmark

**Comment by dabrahams** [comment]
@eeckstein Do you think this is worth doing?  If not, I'll close the PR.

**Comment by eeckstein** [comment]
@dabrahams I don't think so. There is no problem with 6-figure benchmark scores. The N for a benchmark is scaled to let the benchmark run for 1 sec, anyway. So there is no benchmark runtime overhead.

**Comment by CodaFi** [comment]
Closing this due to age.

**Pull request closed without merging**
