### PR TITLE
[gardening] Fix a link and some minor formatting in readme

### PR DESCRIPTION
**Pull request by xwu**
Some trivial and "obvious" changes to the readme. The main impetus for this PR is to serve as the suggested test commit to ensure that I can now trigger CI.

### CODE REVIEW

**Comment by xwu** [comment]
@swift-ci Please smoke test and merge

**Comment by xwu** [comment]
All righty then, I will try again in a little while. Please leave this PR untested and unmerged.

**Comment by xwu** [comment]
@swift-ci Please smoke test and merge

**Comment by xwu** [comment]
@swift-ci please smoke test and merge

**Comment by CodaFi** [comment]
@xwu When you rebase, sometimes CI has trouble hearing you the first time (it’s a Github timestamp bug, don’t ask).  Try it again.

**Comment by xwu** [comment]
@swift-ci Please smoke test and merge

**Comment by xwu** [comment]
@swift-ci Please smoke test and merge

**Comment by xwu** [comment]
@swift-ci Please smoke test and merge

**Comment by CodaFi** [comment]
Hm.  I wonder if this is stuck

@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
Nope, not stuck.  @shahmishal any ideas?

**Comment by shahmishal** [comment]
@CodaFi Looks like its going, are you talking about test and merge?

**Comment by xwu** [comment]
I think @CodaFi's attempt works. Not sure about mine though.

**Comment by xwu** [comment]
@swift-ci Please smoke test and merge

**Comment by xwu** [comment]
Nope.

**Comment by xwu** [comment]
@swift-ci Please smoke test and merge

**Comment by xwu** [comment]
@swift-ci Please smoke test and merge

**Pull request merged**
