### PR TITLE
utils: add support for testing self-hosted SPM

### PR DESCRIPTION
**Pull request by compnerd**
`-Test swiftpm` will use the self-hosted build of SPM to run the test suite. By using the `SWIFTCI_USE_LOCAL_DEPS=1` environment variable, we do reduce some of the cost of this by not recloning the repositories, but the entire dependency tree must be built a second time due to the switch in the build system.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @bnbarham @hyp @hjyamauchi

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Review by hjyamauchi — APPROVED** [review]

**Comment by bnbarham** [comment]
Sure, sounds reasonable to me 👍 Thanks for putting that up already!

**Review by bnbarham — APPROVED** [review]

**Comment by compnerd** [comment]
Ah, found a small difference between my local usage and CI usage - will tweak this to make sure it works on both.

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
I am going to merge this for now as it improves the build.ps1 state to allow local development with this. https://github.com/apple/swift-package-manager/issues/7320 tracks the universal enablement while https://github.com/apple/swift/pull/71349 demonstrated that this does function on CI though the test suite crashes during execution.

**Pull request merged**
