### PR TITLE
Fix objc_bridging_test on non-osx platforms.

### PR DESCRIPTION
**Pull request by gottesmm**
Fix objc_bridging_test on non-osx platforms.

rdar://problem/30559806

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci Please test and merge

**Comment by gottesmm** [comment]
@swift-ci Please test and merge

**Comment by gottesmm** [comment]
@swift-ci Please test and merge

**Comment by gparker42** [comment]
Why do some architectures affirmatively check for `[[BORROWED_FOO_OBJ]]` and others simply allow `{{%.*}}`?

**Comment by gottesmm** [comment]
@gparker42 That is why the testing missed this.

**Comment by gottesmm** [comment]
@gparker42 That is why the OS X tests didn't catch the failure. I can normalize it. 1 sec.

**Comment by gottesmm** [comment]
@swift-ci Please test

**Comment by gottesmm** [comment]
@gparker42 Hows that look?

**Comment by gparker42** [comment]
Still lax in `CHECK-ios-i386-LABEL: sil hidden @_TF13objc_bridging6setZim` and `CHECK-macosx-x86_64-LABEL: sil hidden @_TF13objc_bridging6setZim

**Comment by gottesmm** [comment]
@gparker42 Are you talking about matching the full name of the function? What is happening there is that the writer is trying to avoid adding the parameter type mangling to the name so that if the parameters change the value is still safe. That is common SILGen practice...

Or are you talking about something else?

**Comment by gottesmm** [comment]
@swift-ci Please test

**Comment by gottesmm** [comment]
@swift-ci Please test

**Comment by gottesmm** [comment]
@gparker42 I believe that I fixed what you asked me to fix. I am going to commit this if all of the OS X tests pass. Lets do any further feedback with post-commit review if necessary. I want to move on from this.

**Pull request merged**
