### PR TITLE
Run tests with -swift-version 4

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@airspeedswift A few tests still fail, but it's mostly ready.

**Comment by airspeedswift** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
(just to get the list)

**Comment by slavapestov** [comment]
@airspeedswift I'm fixing the last test now.

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Pull request merged**
