### PR TITLE
[FreeBSD] Add missing link to `compiler-rt-builtins` in unittests.

### PR DESCRIPTION
**Pull request by dcci**
This is in line with what done elsewhere (and in these specific
CMake targets, for Linux).

### CODE REVIEW

**Comment by dcci** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Ugh, I really think that we should be doing this in the driver rather than the build system.

**Comment by jrose-apple** [comment]
Runtime tests are C++ tests, not Swift tests.

**Comment by compnerd** [comment]
@jrose-apple even better ... `-rtlib=compiler-rt` should add the link then :-)

**Comment by gparker42** [comment]
Isn't compiler-rt the default if no -rtlib option is specified?

Where is the analogous code for Linux? I don't see it.

**Comment by dcci** [comment]
@gparker42 

```
  elseif(SWIFT_HOST_VARIANT STREQUAL "linux")
    list(APPEND PLATFORM_TARGET_LINK_LIBRARIES
      "atomic"
      )
```

except that there's no libatomic on FreeBSD, as it's GPL-free (so they use compiler-rt).
There was a similar problem that was fixed in this very same way, but I'm no expert in the swift build, so I might miss something.

**Comment by dcci** [comment]
This is the change I'm referring to:
https://github.com/apple/swift/pull/12528/files#diff-72a829713c96d210e727174a26ea85be

**Comment by compnerd** [comment]
@gparker42 no the default is target dependent (e.g. libgcc on Linux).

**Comment by dcci** [comment]
Can we go ahead with this?

**Comment by compnerd** [comment]
Since that would unblock you, please do file a SR to clean this up if you are not doing that now.

**Comment by dcci** [comment]
@compnerd good idea, https://bugs.swift.org/browse/SR-6444

**Comment by dcci** [comment]
ping?

**Comment by jrose-apple** [comment]
Most Apple people were on vacation the whole week of (American) Thanksgiving. I'd still like @Rostepher to get a chance to at least glance at this.

**Comment by gparker42** [comment]
I still don't understand why we need to explicitly link to libclang_rt.builtins here. My understanding is that the library is part of the compiler runtime, and that the compiler (compiler driver?) is supposed to link it for us.

The Linux libatomic case is a different issue. libatomic is not the compiler runtime; it is an ordinary library that the Swift runtime needs to use on that platform. Non-test link lines also add it.

**Comment by dcci** [comment]
This is too old to be relevant.

**Pull request closed without merging**
