### PR TITLE
[AST/Serialization] Fix circularity issue with deserialized protocols and composition types

### PR DESCRIPTION
**Pull request by xedin**
`InheritedProtocols` request used to reach for a requirement signature of a deserialized
protocol, that is circular because typealiases are deserialized as part of the signature and
they can reference the protocol itself.

Instead of storing inherited types protocol layout should store a superclass (if any)
together with the list of inherited protocols, this way `InheritedProtocols` can be 
cached during deserialization of the protocols which breaks circularity. 

Resolves: rdar://100127674

### CODE REVIEW

**Comment by xedin** [comment]
This is a draft because I need to fix a couple of source kit tests that are using `getInherited()` instead of `getInheritedProtocols()` on protocols.

**Comment by xedin** [comment]
@swift-ci please build toolchain macOS platform

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test

**Review by slavapestov — APPROVED** [review]
Thank you!

**Pull request merged**
