### PR TITLE
[6.0] CMake: add option to link Swift content from Darwin toolchain

### PR DESCRIPTION
**Pull request by edymtt**
**Explanation**: introduce a CMake option that allow Swift binaries to link against content in Darwin toolchains -- this is needed in some Apple internal configurations
**Radar**: rdar://127014753
**Scope**: CMake build logic that configure the build for Swift binaries on Darwin platforms
**Risk**: low -- this behaviour is opt in
**Testing**: CI testing -- in particular ensured we can build a toolchain

**Reviewed By**: @compnerd and @al45tair in #73255

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci please test

**Comment by edymtt** [comment]
@swift-ci please build toolchain

**Comment by edymtt** [comment]
@swift-ci please test WebAssembly

**Review by compnerd — APPROVED** [review]

**Comment by edymtt** [comment]
This will need #73303 to be picked as well before merging.

**Comment by edymtt** [comment]
@swift-ci please test

**Comment by edymtt** [comment]
@swift-ci please build toolchain

**Comment by edymtt** [comment]
@swift-ci please test WebAssembly

**Comment by edymtt** [comment]
@swift-ci please test Windows

**Review by shahmishal — APPROVED** [review]

**Pull request merged**
