### PR TITLE
Use new-style _Nullable keywords in obj-c header

### PR DESCRIPTION
**Pull request by lilyball**
Use the keywords `_Nullable`, `_Nonnull`, and `_Null_unspecified`
instead of the older compatibility forms `__nullable`, `__nonnull`, and
`__null_unspecified`.

Part of rdar://problem/23614638

### CODE REVIEW

**Comment by jeremyhu** [comment]
This would reduce compatibility with older toolchains.

**Comment by lattner** [comment]
Which ones are relevant to working with swift 2.2?

-Chris

**Comment by jeremyhu** [comment]
I'm just wondering if we'd have bootstrapping problems by doing that.

**Comment by lattner** [comment]
I don't think that is a concern.  No released public clang supported the __nullable forms, and Swift includes its own drop of clang with it, that does support the new forms.  If there was a compatibility issue, a few -D_Nullable=__nullable flags seem like they could be used to work around it.

That said, I'd like @jrose-apple to review this when it isn't the weekend :-)

**Comment by jeremyhu** [comment]
Ok, then that sounds good to me.  I haven't looked at the build system yet, but as long as it uses the built clang instead of the bootstrap compiler, that should be fine.  (see https://llvm.org/bugs/show_bug.cgi?id=25753 for why I bring this up).

**Comment by DougGregor** [comment]
Xcode 6.3 used the double-underscored forms, and we changed the syntax in Xcode 7. That's why I'd been holding off on making this change.

**Comment by DougGregor** [comment]
That said, this only affects code using the generated (Objective-)C headers, and the double-underscored keywords will cause problems on Linux. Merging.

**Pull request merged**
