### PR TITLE
update versions of stdlib libraries

### PR DESCRIPTION
**Pull request by tomerd**
update versions of stdlib libraries

swift-atomics -> 1.0.2
swift-collections -> 1.0.1
swift-numerics -> 1.0.1
swift-system -> 1.0.0

### CODE REVIEW

**Comment by tomerd** [comment]
@kylemacomber @milseman @lorentey

@shahmishal

**Comment by shahmishal** [comment]
Please also update the Source Compat suite to use the new versions

**Comment by tomerd** [comment]
@shahmishal: https://github.com/apple/swift-source-compat-suite/pull/585/

**Comment by shahmishal** [comment]
@swift-ci smoke test

**Comment by tomerd** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci build toolchain

**Comment by tomerd** [comment]
@swift-ci smoke test linux

**Comment by tomerd** [comment]
@swift-ci test linux

**Review by lorentey — APPROVED** [review]
Looks good! 🎉

**Pull request merged**
