### PR TITLE
update swift-collections to 0.0.5

### PR DESCRIPTION
**Pull request by tomerd**
motivation: swift-collections 0.0.5 includes critical fixes for SwiftPM use of it

changes: update swift-collections to 0.0.5

### CODE REVIEW

**Comment by tomerd** [comment]
cc @lorentey @neonichu

**Comment by tomerd** [comment]
@emish ptal this is required for https://github.com/apple/swift/pull/38881

**Comment by tomerd** [comment]
@swift-ci please test

**Comment by tomerd** [comment]
@swift-ci please smoke test

**Review by finagolfin — APPROVED** [review]

**Comment by tomerd** [comment]
```
01:23:01 FAIL: Swift(linux-x86_64) :: AutoDiff/compiler_crashers_fixed/sr14625-over-consume-in-subset-parameters-thunk.swift (110 of 14744)
01:23:01 ******************** TEST 'Swift(linux-x86_64) :: AutoDiff/compiler_crashers_fixed/sr14625-over-consume-in-subset-parameters-thunk.swift' FAILED ********************
01:23:01 Script:
01:23:01 --
01:23:01 : 'RUN: at line 1';   /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-main/buildbot_linux/swift-linux-x86_64/bin/swiftc -target x86_64-unknown-linux-gnu -toolchain-stdlib-rpath  -module-cache-path /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-main/buildbot_linux/swift-linux-x86_64/swift-test-results/x86_64-unknown-linux-gnu/clang-module-cache -swift-version 4  -Xfrontend -define-availability -Xfrontend 'SwiftStdlib 5.5:macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0'  /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-main/swift/test/AutoDiff/compiler_crashers_fixed/sr14625-over-consume-in-subset-parameters-thunk.swift
01:23:01 --
01:23:01 Exit Code: 254
01:23:01 
01:23:01 Command Output (stderr):
01:23:01 --
01:23:01 
clang-10: error: unable to execute command: Bus error (core dumped)
01:23:01 clang-10: error: linker command failed due to signal (use -v to see invocation)
01:23:01 <unknown>:0: error: link command failed with exit code 254 (use -v to see invocation)
01:23:01 
01:23:01 --
01:23:01 
01:23:01 ********************
01:23:01 PASS: Swift(linux-x86_64) :: AutoDiff/compiler_crashers_fixed/sr12548-siloptimizer-rewrite-partial-apply-convention-method.swift (111 of 14744)
01:23:01 PASS: Swift(linux-x86_64) :: AutoDiff/stdlib/collection_higher_order_functions.swift (112 of 14744)
01:23:01 PAS
```

@shahmishal ^^

@swift-ci please smoke test linux

**Comment by tomerd** [comment]
@swift-ci please smoke test linux

**Review by neonichu — APPROVED** [review]

**Comment by shahmishal** [comment]
@tomerd can you also update the source Compat suite with the new version?

**Comment by tomerd** [comment]
> @tomerd can you also update the source Compat suite with the new version?

normally that would be done by the library maintainer, correct? cc @lorentey

**Comment by shahmishal** [comment]
This would be done by me or someone that is proposing the new tag for build, this is different than testing for source compet.

**Comment by shahmishal** [comment]
https://github.com/apple/swift-source-compat-suite/blob/main/common.py#L50

**Comment by tomerd** [comment]
https://github.com/apple/swift-source-compat-suite/pull/573

**Comment by tomerd** [comment]
ping @shahmishal

**Comment by shahmishal** [comment]
```
7. OSS - LLDB - ASAN + UBSAN macOS (main) (Release)
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
5. OSS - LLDB Incremental - Ubuntu 16.04 (main)
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
6. OSS - LLDB Incremental - Ubuntu 18.04 (main)
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
4. OSS - LLDB Incremental - macOS (main)
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
OSS - Swift Package Trigger (main)
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
1. OSS - Swift ASAN - macOS (main)
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
1. OSS - Swift ASAN - Ubuntu 16.04 (main)
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
0. OSS - Swift Incremental RA - Ubuntu 16.04 (main)
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
0. OSS - Swift Incremental RA - Ubuntu 16.04 - Long Test (main)
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
0. OSS - Swift Incremental RA - Ubuntu 18.04 (main)
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
0. OSS - Swift Incremental RA - Ubuntu 18.04 - Long Test (main)
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
1. OSS - Swift Leaks Sanitizer - LSAN - Ubuntu 18.04 (main)
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
0. OSS - Swift Incremental RA - macOS (main)
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
0. OSS - Swift Incremental RA - macOS (main) (Apple Silicon)
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
OSS - Swift Incremental RA - macOS - Trigger (main)
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
0. OSS - Swift Incremental RA - macOS (main) (Xcode)
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
OSS - Swift Package - Ubuntu 16.04 (main)
	Skip: ${swift_collections}
OSS - Swift Package - Ubuntu 18.04 (main)
	Skip: ${swift_collections}
OSS - Swift Package - macOS (main)
	Skip: ${swift_collections}
0. OSS - Swift Pull Request Test (status) (main)
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
2. Swift Build Standard Library with Toolchain (main)
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
2. Swift Build Standard Library with Toolchain (main) (minimal)
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
1. OSS - Swift - TSAN - libdispatch - Ubuntu 18.04 (main)
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
1. OSS - Swift (Tools Opt+No Assert,  Stdlib Opt+DebInfo, Test Simulator) - macOS (main)
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
1. OSS - Swift (Tools Opt+Assert, Stdlib DebInfo+Assert, Test Device non_executable) (main)
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
1. OSS - Swift (Tools Opt+Assert, Stdlib DebInfo+Assert, Test Simulator) - macOS (main)
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
2. Swift (Tools Opt+Assert, Stdlib Opt+Assert) (macOS 10.14.5) (Swift in the OS)
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
1. OSS - Swift (Tools Opt+Assert,  Stdlib Opt+DebInfo, Test Simulator) - macOS (main)
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
1. OSS - Swift (Tools Opt+Assert, Stdlib Opt+DebInfo+Assert, Long Test) - macOS  (main)
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
1. OSS - Swift (Tools Opt+Assert, Stdlib Opt+DebInfo+Assert, Test Simulator) - macOS  (main)
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
2. Swift Source Compatibility Suite (main)
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
2. Swift Source Compatibility Suite (main) (Debug)
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
2. Swift Sourcekit Stress Tester (main)
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
2. Swift Sourcekit Stress Tester (main) (weekly)
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
Swift Package Collection Generator
	Repo: git@github.com:apple/swift-collections.git
	Branch: 0.0.4
	new Branch: 0.0.5
```

**Pull request merged**
