### PR TITLE
Build-script: ensure we can target armv7k with watchOS 9 SDK

### PR DESCRIPTION
**Pull request by edymtt**
Updating to match `SDKSettings.plist`

Addresses rdar://100563701

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci please test

**Comment by edymtt** [comment]
@swift-ci please build toolchain

**Comment by edymtt** [comment]
@swift-ci please python lint

**Review by shahmishal — APPROVED** [review]

**Comment by edymtt** [comment]
@swift-ci please test

**Comment by edymtt** [comment]
@swift-ci please test

**Comment by edymtt** [comment]
@swift-ci please build toolchain

**Comment by edymtt** [comment]
@swift-ci please test

**Comment by edymtt** [comment]
@swift-ci please build toolchain

**Comment by edymtt** [comment]
@swift-ci please test macOS

**Pull request merged**
