### PR TITLE
[TF] Update raw ops

### PR DESCRIPTION
**Pull request by rxwei**
Update the TensorFlow module to reflect https://github.com/tensorflow/swift-bindings/pull/6.

### CODE REVIEW

**Comment by rxwei** [comment]
Do not merge until tensorflow/swift-bindings#6 is merged.

**Review by LaurentMazare — APPROVED** [review]

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Comment by rxwei** [comment]
@swift-ci please clean test tensorflow

**Pull request merged**
