### PR TITLE
modernise optional (NFCI)

### PR DESCRIPTION
**Pull request by compnerd**
Replace `llvm::None` with `std::nullopt`, `llvm::NoneType` with `std::nullopt_t`, and some `llvm::Optional` with `std::optional`. This helps make the output more useful by silencing a large number of warnings, some of which are very verbose due to the template instantiation.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Review by tshortli — APPROVED** [review]

**Comment by bnbarham** [comment]
I'm all for this in general, but I (we?) were hoping to wait until 5.10 is mostly finished taking merges in order to avoid the merge conflicts. What's missing here is:
1. LLDB doesn't have SWIFT_TARGET defined in it's compilation, so the deprecation warning isn't skipped
2. Swift + C++ interop (ie. SwiftCompilerSources) isn't defining it either, so we get warnings there too

We should fix (1) and (2) and then use std::optional later.

**Comment by compnerd** [comment]
> > This helps make the output more useful by silencing a large number of warnings, some of which are very verbose due to the template instantiation.
> 
> What is an example of such a warning?

```
C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift\include\swift/AST/Decl.h(1332): warning C4996: 'llvm::None': Use std::nullopt instead.
C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift\include\swift/AST/Decl.h(1329): note: while compiling class template member function 'std::optional<swift::EnumElementDecl *> swift::AvailableDuringLoweringDeclFilter<swift::EnumElementDecl>::operator ()(T *) const'
        with
        [
            T=swift::EnumElementDecl
        ]
C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift\include\swift/Basic/STLExtras.h(498): note: see reference to function template instantiation 'std::optional<swift::EnumElementDecl *> swift::AvailableDuringLoweringDeclFilter<swift::EnumElementDecl>::operator ()(T *) const' being compiled
        with
        [
            T=swift::EnumElementDecl
        ]
C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift\include\swift/Basic/STLExtras.h(489): note: see reference to class template instantiation 'swift::AvailableDuringLoweringDeclFilter<swift::EnumElementDecl>' being compiled
C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift\include\swift/AST/Decl.h(4370): note: see reference to class template instantiation 'swift::OptionalTransformRange<swift::EnumDecl::ElementRange,swift::AvailableDuringLoweringDeclFilter<swift::EnumElementDecl>,swift::OptionalTransformIterator<Iterator,OptionalTransform>>' being compiled
        with
        [
            Iterator=swift::DeclIterator,
            OptionalTransform=swift::DowncastAsOptional<swift::EnumElementDecl>
        ]
C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift\include\swift/Basic/STLExtras.h(544): warning C4996: 'llvm::None': Use std::nullopt instead.
C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift\include\swift/Basic/STLExtras.h(450): note: see reference to function template instantiation 'std::optional<swift::EnumElementDecl *> swift::DowncastAsOptional<Subclass>::operator ()<swift::Decl*>(const Superclass &) const' being compiled
        with
        [
            Subclass=swift::EnumElementDecl,
            Superclass=swift::Decl *
        ]
C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift\include\swift/Basic/STLExtras.h(450): note: see reference to function template instantiation 'std::optional<swift::EnumElementDecl *> swift::DowncastAsOptional<Subclass>::operator ()<swift::Decl*>(const Superclass &) const' being compiled
        with
        [
            Subclass=swift::EnumElementDecl,
            Superclass=swift::Decl *
        ]
C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift\include\swift/Basic/STLExtras.h(450): note: while compiling class template member function 'swift::EnumElementDecl *swift::OptionalTransformIterator<Iterator,OptionalTransform>::operator *(void)'
        with
        [
            Iterator=swift::DeclIterator,
            OptionalTransform=swift::DowncastAsOptional<swift::EnumElementDecl>
        ]
C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift\include\swift/AST/Decl.h(4387): note: see reference to function template instantiation 'swift::EnumElementDecl *swift::OptionalTransformIterator<Iterator,OptionalTransform>::operator *(void)' being compiled
        with
        [
            Iterator=swift::DeclIterator,
            OptionalTransform=swift::DowncastAsOptional<swift::EnumElementDecl>
        ]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\__msvc_iter_core.hpp(505): note: see reference to class template instantiation 'swift::OptionalTransformIterator<Iterator,OptionalTransform>' being compiled
        with
        [
            Iterator=swift::DeclIterator,
            OptionalTransform=swift::DowncastAsOptional<swift::EnumElementDecl>
        ]
C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift\include\swift/Basic/STLExtras.h(512): note: see reference to class template instantiation 'std::iterator_traits<swift::OptionalTransformIterator<Iterator,OptionalTransform>>' being compiled
        with
        [
            Iterator=swift::DeclIterator,
            OptionalTransform=swift::DowncastAsOptional<swift::EnumElementDecl>
        ]
C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift\include\swift/Basic/STLExtras.h(561): note: see reference to class template instantiation 'swift::OptionalTransformRange<Range,swift::DowncastAsOptional<Subclass>,IteratorT>' being compiled
        with
        [
            Range=swift::DeclRange,
            Subclass=swift::EnumElementDecl,
            IteratorT=swift::DeclIterator
        ]
C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift\include\swift/Basic/STLExtras.h(485): note: see reference to class template instantiation 'swift::DowncastFilterRange<swift::EnumElementDecl,swift::DeclRange>' being compiled
C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift\include\swift/AST/Attr.h(2594): warning C4996: 'llvm::None': Use std::nullopt instead.
C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift\include\swift/AST/Attr.h(2591): note: while compiling class template member function 'std::optional<const ATTR *> swift::ToAttributeKind<ATTR,false>::operator ()(const swift::DeclAttribute *) const'
        with
        [
            ATTR=swift::SemanticsAttr
        ]
C:\Users\swift-ci\jenkins\workspace\swift-PR-build-toolchain-windows\swift\include\swift/Basic/STLExtras.h(498): note: see reference to function template instantiation 'std::optional<const ATTR *> swift::ToAttributeKind<ATTR,false>::operator ()(const swift::DeclAttribute *) const' being compiled
        with
        [
            ATTR=swift::SemanticsAttr
        ]
```

**Comment by compnerd** [comment]
@bnbarham I wouldn't be as annoyed by that, but the use of it in templates results in that monstrosity above.

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by bnbarham** [comment]
Haha, sure. The notes are attached to the warning, I didn't think it mattered since we shouldn't be outputting them anyway :P. Fix https://github.com/apple/llvm-project/pull/7674

**Comment by compnerd** [comment]
We can probably close this as @bnbarham was looking into doing this.

**Pull request closed without merging**
