### PR TITLE
[Async CC] Pass witness metadata to callees.

### PR DESCRIPTION
**Pull request by nate-chandler**
Previously, the WitnessMetadata values that were collected were just ignored when making a function call, although space was reserved for them in the async context.  Here, that error is corrected by actually storing them into the async context if they are present.

Previously, when saving NecessaryBindings for an async function, if a type that was passed-in happened to be an archetype, a lookup for that type's conformance would always be done.  However, that lookup was not always necessary or possible such as in the case where both the metadata and the witness table were provided to the function in an async context.  Here, that is fixed by using the conformance that was seen when constructing the NecessaryBindings if one is available.

rdar://problem/72397303

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]
Thanks!

**Comment by nate-chandler** [comment]
@swift-ci please clean test windows platform

**Comment by nate-chandler** [comment]
@swift-ci please clean test windows platform

**Pull request merged**
