### PR TITLE
stdlib: remove Boolean protocol

### PR DESCRIPTION
**Pull request by gribozavr**
Per [SE-0109](https://github.com/apple/swift-evolution/blob/master/proposals/0109-remove-boolean.md).

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by gribozavr** [comment]
@swift-ci Please test

**Comment by lattner** [comment]
Thanks Dmitri, but I was already working on this, and it just landed.

**Comment by gribozavr** [comment]
@lattner No problem, but this PR also removes the `Bool.boolValue` API, which we don't need anymore.  I'll refresh the PR.

**Comment by lattner** [comment]
I'm pretty sure that I removed Bool.boolValue, but please feel free to clean up anything you think should be improved.

**Comment by gribozavr** [comment]
@lattner It is still referenced in `validation-test/stdlib/FixedPoint.swift.gyb` for example, and other places.

**Comment by gribozavr** [comment]
@swift-ci Please test and merge

**Comment by lattner** [comment]
I just removed that as part of fixing the validation tests.

**Comment by gribozavr** [comment]
@swift-ci Please test and merge

**Comment by gribozavr** [comment]
@lattner I see now.  OK, I call this PR a grab bag of cleanups then.

**Comment by lattner** [comment]
SGTM, thanks!  Sorry for stepping on your toes.  I'm done touching bool stuff. :-)

**Comment by gribozavr** [comment]
@swift-ci Please test and merge

**Comment by gribozavr** [comment]
@swift-ci Please test and merge

**Comment by gribozavr** [comment]
@swift-ci Please test OS X platform

**Comment by gribozavr** [comment]
@swift-ci Please test OS X platform

**Comment by gribozavr** [comment]
@swift-ci Please smoke test OS X platform

**Pull request merged**
