### PR TITLE
WIP [Serialization] Cross-reference imported ObjC methods by selector.

### PR DESCRIPTION
**Pull request by jrose-apple**
This guards against the names of Objective-C methods changing via `NS_SWIFT_NAME`, or the types changing by "fixing" optionality or adding generic arguments to a collection. In most cases, references to such methods should just pick up the new definition rather than resulting in a failure to load.

I'd like to extend this model to initializers, properties, and subscripts as well; properties and subscripts should use the getter's selector as a key.

This is currently guarded by a frontend flag, -enable-experimental-objc-xrefs, and off by default. It does potentially have problematic implications, such as serialized SIL having a type change out from under it. We need to think through this a little more (and add more tests) before turning it on.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test OS X platform

**Comment by jrose-apple** [comment]
Not planning to merge this right now, but I want to see if there are any obvious errors in what's been implemented by seeing what happens downstream.

**Comment by jrose-apple** [comment]
…but I would have had to turn it on everywhere to get that testing. Oops.

**Comment by jrose-apple** [comment]
@swift-ci Please test OS X platform

**Comment by jrose-apple** [comment]
@swift-ci Please test OS X platform

**Comment by milseman** [comment]
@jrose-apple do you still want this PR?

**Comment by jrose-apple** [comment]
Hm. I still want the branch, but if our convention is not to leave open PRs with no plan, we can close it.

**Comment by tkremenek** [comment]
This was opened in early 2017.  Is this still relevant?

**Comment by jrose-apple** [comment]
The comment from above still stands, but I guess that means I should indeed close the PR.

**Pull request closed without merging**
