### PR TITLE
Optimize Documentation Images to Save Bandwidth

### PR DESCRIPTION
**Pull request by daknob**
This commit optimizes the images available in the
docs folder in order to  save  on  bandwidth  and
also decrease page loading time.

Images updated:
- docs/Array.png
- docs/ArrayBridge.png
- docs/ArrayCast.png
- docs/ArrayImplementation.png
- docs/ContiguousArray.png
- docs/Slice.png

### CODE REVIEW

**Comment by krememek** [comment]
What is the actual win of doing this compression?  How much space is saved?

Note that doing this change actually increases the size of the cloned repository.

**Comment by DaKnOb** [comment]
@krememek This increases the git repository size overall but it will decrease the amount of bandwidth required to serve the Swift Documentation website. Since there are more people viewing the documentation than cloning the repository I believe there is a benefit. 

The reported size decrease is here, per file:

```
Total Size Before: 769.7 kB
Total Size After: 564.9 kB

File                        Savings
Array.png                     35.3%
ArrayBridge.png               26.2%
ArrayCast.png                 24.1%
ArrayImplementation.png       20.6%
ContiguousArray.png           39.6%
Slice.png                     37.0%
```

**Comment by eosrei** [comment]
@DaKnOb :+1: 200kb saved per doc user vs 564kb cost for clones. Worth it.

**Comment by masters3d** [comment]
Where in the swift.org site is this documentation? I could not find.

**Pull request merged**
