### PR TITLE
[SwiftShims] Make the void* arguments of memcmp nullable

### PR DESCRIPTION
**Pull request by xymus**
This should correspond to the definition of `memcmp` in `usr/include/string.h` and keep it from being a source of confusion for the compiler.

rdar://69876253

### CODE REVIEW

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by xymus** [comment]
@swift-ci Please smoke test macOS

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Review by beccadax — APPROVED** [review]

**Comment by beccadax** [comment]
@swift-ci please smoke test

**Comment by xymus** [comment]
@swift-ci please smoke test

**Comment by xymus** [comment]
The libs compiled fine under Linux this time but the test failed.

@swift-ci please smoke test

**Comment by xymus** [comment]
@swift-ci please smoke test

**Comment by xymus** [comment]
@swift-ci Please smoke test macOS

**Comment by xymus** [comment]
@swift-ci please smoke test

**Pull request merged**
