### PR TITLE
[ASTWalker] Walk ForEachStmt in source order

### PR DESCRIPTION
**Pull request by hamishknight**
Make sure to visit the sequence expr before the the where clause as the refactoring logic expects nodes to be visited in source order.

rdar://78781061

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
@swift-ci please test

**Review by bnbarham — APPROVED** [review]

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
Source compat failures are unrelated

**Pull request merged**
