### PR TITLE
[utils] Slightly better exceptions in gyb_stdlib_support.py

### PR DESCRIPTION
**Pull request by alexwlchan**
#### What's in this pull request?

If we get an unknown traversal passed to one of these functions, raise a ValueError that includes the name of the unknown traversal -- should we hit this case, this will make it slightly easier to debug.
#### Resolved bug number: ([SR-](https://bugs.swift.org/browse/SR-))

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by moiseev** [comment]
@alexwlchan why is `if...elif...else` form preferred over what was there before? All cases `return` after all. So `raise` instead of `assert` would have the same behavior.

**Comment by CodaFi** [comment]
@swift-ci Please Python lint.

**Comment by CodaFi** [comment]
@swift-ci Please Python lint.

**Comment by CodaFi** [comment]
@moiseev I'm inclined to take the change even with that point.  Even though I agree flow of control is unambiguous in either case (and I actually lean towards your side here in general).

**Comment by CodaFi** [comment]
Thanks @alexwlchan!

**Pull request merged**
