### PR TITLE
[analysis] Add a new form of verification SILAnalysis::verifyFull().

### PR DESCRIPTION
**Pull request by gottesmm**
This has a default implementation of just calling verify() and is only invoked
in PassManager destructors. I am going to use this to ensure that the
PassManagerVerifierAnalysis only runs at such points (even when sil-verify-all
is enabled) since it is too expensive to run otherwise.

rdar://42301529

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Review by aschwaighofer — APPROVED** [review]
LG

**Comment by gottesmm** [comment]
Looks like in certain cases, we hit assertions when I call verify() as a default for verifyFull() in the pass manager's destructor. I don't have time to look into this right now, so I am going to file an SR and give verifyFull() an empty default implementation. I just need to use it for the pass manager notification verification.

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
@swift-ci smoke test and merge

**Comment by gottesmm** [comment]
I decided to scale back the verification here since I am out of engineering time to invest here and instead filed some SRs for people to look into this. Specifically:

1. I found that 1-2 tests need to be updated given this change if we make verifyFull() call verify() by default. I don't have time to fix these now. I filed: https://bugs.swift.org/browse/SR-8557.
2. On linux, when we call SILModule::verify() in SILPassManager destructors we hit a problem where we catch a missing -Onone line table entry. I filed an SR for the debug info people to look at: https://bugs.swift.org/browse/SR-8558.

**Pull request merged**
