### PR TITLE
[6.0] Teach #isolation to respect the flow-sensitive nature of actor initializers

### PR DESCRIPTION
**Pull request by DougGregor**
**Explanation**: Perform flow-sensitive lowering of `#isolation` within actor initializers so that it lowers to `nil` before the actor is fully-initialized and `self` (or `self.asLocalActor` in the distributed case) after the actor is fully-initialized.
**Original PR**: https://github.com/apple/swift/pull/74225
**Radar/issue**: rdar://127080037
**Reviewed by**: @ktoso 
**Risk**: Low. Only affects actor initializers that use `#isolation` or the asynchronous for-in loop on new-enough platforms (where the new `AsyncIteratorProtocol.next(isolation:)` is present).

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test Windows

**Comment by DougGregor** [comment]
@swift-ci please test Windows

**Review by hborla — APPROVED** [review]

**Review by ktoso — APPROVED** [review]

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Pull request merged**
