### PR TITLE
[Docs] Fix broken url and filename

### PR DESCRIPTION
**Pull request by gabeiglio**
in swift/docs the Literal.md url points to a 404 page not found, this commit fixes the url by changing the url to Literals.md, the name as well in the list is corrected.

### CODE REVIEW

**Review by slavapestov — APPROVED** [review]

**Comment by benrimmington** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by benrimmington** [comment]
@gabeiglio If you push more commits, the smoke test has to be run again before merging.

**Comment by benrimmington** [comment]
@swift-ci Please smoke test

**Comment by benrimmington** [comment]
@gabeiglio Thanks.

I recommend that you create a new branch for each pull request, instead of using your [`gabeiglio:master`](https://github.com/gabeiglio/swift/tree/master) branch.

**Comment by gabeiglio** [comment]
@benrimmington Sure thing, thanks for the advice!

**Pull request merged**
