### PR TITLE
RequirementMachine: Same-type requirements imply same-shape requirements [5.9]

### PR DESCRIPTION
**Pull request by slavapestov**
* Description: A same-type requirement between two member types did not imply a same-shape requirement between the root generic parameters. This could produce an incorrect mangling (if the same-shape requirement was inferred by some other means, it would not be minimized away), cause the type checker to reject valid code (if the user tried to do something with the two packs that required them to have the same shape), or possibly other unforeseen soundness issues.

* Scope of the issue: You need a generic signature with at least two generic parameter packs to observe any difference in behavior.

* Risk: This only impacts variadic generics type checking, for the most part. It introduces new rewrite rules in the Requirement Machine, but to reduce the chance of regressions with unrelated code, the new rules are only added if the generic signature declares at least one generic parameter pack.

  I also cherry-picked a refactoring PR which changes `GenericSignature::getGenericParams()` to return `ArrayRef` instead of `TypeArrayView`. Without this change, the new logic in this PR would require some ugly casts, and it would cause main and release/5.9 to diverge in a way that is likely to lead to merge conflicts. This refactoring touches a number of source files but it's a purely mechanical change that probably doesn't even affect generated code. I'm pretty confident it is safe.

* Tested: Some new tests added

* Radar: rdar://101813873 and rdar://108319167

* Reviewed by: @hborla

### CODE REVIEW

**Comment by slavapestov** [comment]
https://github.com/apple/llvm-project/pull/7050
@swift-ci Please test

**Review by hborla — APPROVED** [review]

**Comment by slavapestov** [comment]
@swift-ci Please test Windows

**Comment by slavapestov** [comment]
@swift-ci Please test Windows

**Comment by slavapestov** [comment]
@swift-ci Please clean test Windows

**Comment by hborla** [comment]
@swift-ci please test Windows

**Comment by hborla** [comment]
https://github.com/apple/llvm-project/pull/7050
@swift-ci please test Windows

**Pull request merged**
