### PR TITLE
[WIP][SR-1052] Added `(non)mutatingvariant` doc fields

### PR DESCRIPTION
**Pull request by tanadeau**
#### What's in this pull request?

Part 4 of SR-1052: Parse and recognize the new `mutatingvariant` and `nonmutatingvariant` doc fields and connect them to code completion.
#### Resolved bug number: Part 4 of [SR-1052](https://bugs.swift.org/browse/SR-1052)

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

 **Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| OS X platform | @swift-ci Please test OS X platform |
| Linux platform | @swift-ci Please test Linux platform |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by lattner** [comment]
LGTM, @gribozavr any concerns with this?

**Comment by gribozavr** [comment]
CC @bitjammer @nkcsgexi

**Comment by bitjammer** [comment]
Cool! 👍🏻

**Comment by nkcsgexi** [comment]
@tanadeau Thanks for working on this!

**Comment by tanadeau** [comment]
Very happy to do this. When anyone has time, could someone give me a pointer to the question I asked on the linked JIRA ticket about the next part of this work? It's about how to handle generic return types.

**Pull request merged**
