### PR TITLE
[swift-4.0-branch] [stdlib] Spot fix for https://bugs.swift.org/browse/SR-5401

### PR DESCRIPTION
**Pull request by dabrahams**
Resolves [SR-5401](https://bugs.swift.org/browse/SR-5401) / <rdar://33216769>.

### CODE REVIEW

**Comment by dabrahams** [comment]
@swift-ci Please smoke test

**Comment by dabrahams** [comment]
@swift-ci Please test

**Review by milseman — APPROVED** [review]
LGTM

**Comment by dabrahams** [comment]
@swift-ci Please test

**Comment by dabrahams** [comment]
@swift-ci Please test

**Pull request merged**
