### PR TITLE
[build] Fix generated header files in standalone overlay builds.

### PR DESCRIPTION
**Pull request by gparker42**

### CODE REVIEW

**Comment by gparker42** [comment]
@swift-ci please test

**Comment by gparker42** [comment]
@compnerd, does your build workflow still work after this?

**Comment by compnerd** [comment]
I'll try it out to verify, but, I suspect that this should be fine.

**Comment by compnerd** [comment]
Doesn't seem to break for incremental at least, thanks for the heads up though!

**Pull request merged**
