### PR TITLE
[AutoDiff] Fix stdlib `@derivative(of: subscript)` crash.

### PR DESCRIPTION
**Pull request by dan-zheng**
Fix `@derivative(of: subscript)` crash for `SIMD{n}` types.
Strangely, the crash is not easily reproducible via standalone tests:
```swift
// Standalone reproducer: no crash.
 extension SIMD2 {
  @differentiable(
    where Scalar : EuclideanDifferentiable & BinaryFloatingPoint,
          Scalar.TangentVector : BinaryFloatingPoint)
  public subscript(index index: Int) -> Scalar {
    @_transparent get { fatalError() }
    @_transparent set { fatalError() }
  }
}
extension SIMD2
  where Scalar : EuclideanDifferentiable & BinaryFloatingPoint,
        Scalar.TangentVector : BinaryFloatingPoint {
  @usableFromInline
  @derivative(of: subscript(index:))
  internal func _vjpSubscript(index: Int)
  -> (value: Scalar, pullback: (Scalar.TangentVector) -> TangentVector) {
    return (self[index], { v in
      var zeros = Self.zero
      zeros[index] = Scalar(v)
      return zeros
    })
  }
}
```

Resolves TF-1090.

Exposes TF-1094: during `.swiftinterface` compilation: unserialized
`@derivative` function is not registered for serialized `@differentiable`
function.

---

Issue originally reported by @bartchr808 in https://github.com/apple/swift/pull/28930/commits/73d43cf7d9d939e67159e6326f411c202356aff1.

### CODE REVIEW

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Review by bartchr808 — APPROVED** [review]
Looks great! Looking back, making SIMD differentiable has brought to light several interesting bugs 😄

**Review by rxwei — APPROVED** [review]

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Pull request merged**
