### PR TITLE
[Runtime] Fix swift_conformsToProtocol crashing on conformances to unavailable classes.

### PR DESCRIPTION
**Pull request by mikeash**
An extension on a class creates a conformance record that's always visible even when that class is not present at runtime. In that case, the type pointer in the conformance record is NULL. The runtime did not like this, and crashed. This fixes it to ignore such records instead.

For back deployment to Swift 5.0, the `swiftCompatibility50` library is extended to find conformance records with NULL type pointers and rewrite those pointers to point to a dummy type that will be ignored by the runtime.

rdar://problem/54054895

### CODE REVIEW

**Review by DougGregor — APPROVED** [review]

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please smoke test

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please smoke test

**Comment by mikeash** [comment]
@swift-ci please smoke test

**Pull request merged**
