### PR TITLE
Revert "Create fewer generic signature builders"

### PR DESCRIPTION
**Pull request by shajrawi**
Trying non-smoke test that reverts apple/swift#12062

See if it fixes the validation tests

### CODE REVIEW

**Comment by shajrawi** [comment]
@swift-ci Please test

**Comment by DougGregor** [comment]
@shajrawi can you give me a few minutes to look into this?

**Comment by DougGregor** [comment]
(I'll merge your PR this evening if I can't get a fix in fast)

**Comment by shajrawi** [comment]
Sure thing - no worries

**Comment by CodaFi** [comment]
@swift-ci please clean test Linux platform

**Comment by CodaFi** [comment]
@swift-ci please clean test Linux platform

**Comment by DougGregor** [comment]
Ugh. Cannot reproduce this, and ci.swift.org is being unresponsive tonight

**Comment by CodaFi** [comment]
Seems cleared up on my end.  The failures appear in `SIL/SIL/parse_stdlib_*`

**Pull request merged**
