### PR TITLE
[5.10 🍒][Dependency Scanning] Implement parallel imported module resolution

### PR DESCRIPTION
**Pull request by artemcm**
Cherry-pick of https://github.com/apple/swift/pull/68252
-------------------------------------
- [Dependency Scanning] Refactor primary scan operations into ModuleDependencyScanner class
From being a scattered collection of static methods in ScanDependencies.cpp
and member methods of ASTContext. This makes ScanDependencies.cpp much easier
to read, and abstracts the actual scanning logic away to a place with common
state which will make it easier to reason about in the future.

- [Dependency Scanning] Implement parallel imported module resolution
ModuleDependencyScanner maintains a Thread Pool along with a pool of workers
which are capable of executing a filesystem lookup of a named module dependency.
When resolving imports of a given Swift module, each import's resolution
operation can be issued asynchronously.

For the time being, the scanner is restricted to still run single-threaded, with a new frontend option -parallel-scan enabling multi-threaded dependency scanning.

### CODE REVIEW

**Comment by nkcsgexi** [comment]
Although scanning in parallel is opt-in, is there any chance that this may regress the current explicit module builds?

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
> Although scanning in parallel is opt-in, is there any chance that this may regress the current explicit module builds?

Chances are low, since without enabling parallelism this is intended to be a NFC refactor. Still, I will try and verify with some larger projects I have.

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
@swift-ci test

**Review by nkcsgexi — APPROVED** [review]

**Pull request merged**
