### PR TITLE
[stdlib][NFC] Simplify partition(by:)’s implementation

### PR DESCRIPTION
**Pull request by lorentey**
Getting rid of the labeled breaks makes things a little easier to follow for me.

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Comment by NevinBR** [comment]
I think the implementation can be simplified further, so it only has two loops instead of three:

```
var lo = startIndex
var hi = endIndex

while lo < hi {
  if try belongsInSecondPartition(self[lo]) {
    repeat {
      formIndex(before: &hi)
      guard lo < hi else { return lo }
    } while try belongsInSecondPartition(self[hi])
    
    swapAt(lo, hi)
  }
  
  formIndex(after: &lo)
}

return lo
```

**Comment by lorentey** [comment]
I like the way the original follows easily understandable steps; it also matches the way Hoare originally described this algorithm.

Reducing the number of loops does not seem to increase readability for me; in fact, I find it's quite the opposite,.

**Comment by NevinBR** [comment]
Perhaps it’s just a personal preference, but I find the one-loop version significantly easier to understand than the three-loop version. So much so that the explanatory comments struck me as unnecessary and redundant, so I removed them.

**Comment by lorentey** [comment]
FWIW, I still find my boring version easier to follow; there is also a symmetry to it that is lost in the two-loop `lastIndex(where:)` variant.

To be fair, I find both of these to be more accessible than the original one with the goto statements. ¯\_(ツ)_/¯

**Pull request merged**
