### PR TITLE
IRGen: Don't drop method descriptors for vtable-elided internal methods.

### PR DESCRIPTION
**Pull request by jckarter**
We still use the method descriptor for key path identity and other uses. Fixes rdar://problem/66280170.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@rxwei @dan-zheng I noticed a problem with derivative functions' method descriptors here. They were getting mangled the same as the method descriptor for the original method, and silently colliding before (and now crashing when they end up becoming distinct definitions instead of aliases after this patch). I disabled emitting method descriptors for derivative functions here, since I figured you probably don't need them to work with library evolution yet. Is that OK?

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by dan-zheng** [comment]
> I disabled emitting method descriptors for derivative functions here, since I figured you probably don't need them to work with library evolution yet. Is that OK?

That sounds good, thanks! I think there's also a duplicate derivative function method descriptor TBDGen issue that we haven't looked into yet: SR-13125.

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@dan-zheng I'm having trouble finding the `AutoDiff/validation-test/class_differentiation.swift` test that's still failing in CI here. Is it in a different repository from the compiler?

**Comment by dan-zheng** [comment]
The test exists on master branch: [`test/AutoDiff/validation-test/class_differentiation.swift`](https://github.com/apple/swift/blob/master/test/AutoDiff/validation-test/class_differentiation.swift). It may have been added to master branch after this PR was created, you should be able to access the test if you pull from master.

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@dan-zheng Since this test was added recently, would it be OK if I disabled it temporarily, so that we can get this correctness fix in for other code?

**Comment by dan-zheng** [comment]
That sounds good! If you have any ideas on what's causing the test failure and how to eventually fix it, that would be quite helpful.

**Comment by jckarter** [comment]
Sure, I'll look into it once I land this.

**Comment by jckarter** [comment]
Ultimately, I think you'll want to feed the `derivativeIdentifier` from the SILDeclRef through into the LinkEntity for the derivative's MethodDescriptor and MethodOverrideDescriptor, so we can include the identifier in a distinct mangling for these method entries.

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@dan-zheng I think I worked out an approach that keeps the existing AutoDiff test behavior working for now, while still fixing the problem I'm trying to address for other code.

**Comment by jckarter** [comment]
@swift-ci Please test

**Pull request merged**
