### PR TITLE
[AutoDiff] SR-12526: cross-module @derivative deserialization

### PR DESCRIPTION
**Pull request by marcrasi**
When deserializing a `@derivative` attribute that declares a derivative for a function in a different module, we can't immediately resolve the reference to the function. So this PR adds a lazy resolver to the `@derivative` attribute that resolves the original function only when we actually need it (most of this was done by @dan-zheng, thanks!). To handle the case where the `@derivative` attribute is parsed and typechecked, we keep the `AbstractFunctionDecl*` pointer too. The `getOriginalFunction` request returns the `AbstractFunctionDecl*` if it's available, and otherwise uses the lazy resolver. 

Resolves SR-12526.

### CODE REVIEW

**Comment by marcrasi** [comment]
@swift-ci please test

**Review by dan-zheng — APPROVED** [review]
Clever `PointerUnion` design, nice!

**Comment by marcrasi** [comment]
@swift-ci please test

**Comment by marcrasi** [comment]
@swift-ci please test

**Comment by marcrasi** [comment]
Wow, I have realized that this PR is completely broken: there is no code path that sets the lazy resolver!

The only reason this PR fixes the test is that I add the `public init()` to fix a typechecker error, and this somehow has the side effect of making deserialization succeed. Maybe the typechecker error triggers extra deserialization that doesn't happen when the code is fully valid. This test is not a very "robust" test of the problem.

So I'm going to add a code path that sets the lazy resolver, and I'm going try to make a more robust test.

**Comment by marcrasi** [comment]
Okay, this PR is fixed now. I wasn't able to quickly find any other way of triggering the error other than the missing `init()`, so I have left the test with the missing `init()` even though it seems a bit non-robust.

**Comment by marcrasi** [comment]
@swift-ci please test

**Comment by marcrasi** [comment]
@swift-ci please test

**Comment by dan-zheng** [comment]
> Maybe the typechecker error triggers extra deserialization that doesn't happen when the code is fully valid. This test is not a very "robust" test of the problem.

I believe the extra deserialization occurs when a declaration (the missing `Struct.init`) cannot be found. A reference to a missing declaration triggers deserialization to find the declaration if at all possible.

**Pull request merged**
