### PR TITLE
build-script: Implement support for --(no-)lldb-assertions

### PR DESCRIPTION
**Pull request by vedantk**
* LLDB assertions are on by default, like swift assertions

* LLDB assertions can be enabled/disabled globally with the --assertions
  and --no-assertions options

Partially addresses: rdar://38524846

### CODE REVIEW

**Comment by vedantk** [comment]
@swift-ci smoke test and merge

**Comment by vedantk** [comment]
@swift-ci smoke test and merge

**Comment by vedantk** [comment]
@swift-ci smoke test and merge

**Comment by shahmishal** [comment]
@swift-ci smoke test linux

**Comment by vedantk** [comment]
@swift-ci clean smoke test Linux platform

**Pull request merged**
