### PR TITLE
[Gardening] test/Sema

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
Gardening for `test/Sema`

### CODE REVIEW

**Comment by AnthonyLatsis** [comment]
Ah... All the commits got involved again

**Comment by xedin** [comment]
@AnthonyLatsis you just need to checkout a new branch from master and cherry-pick your last commit there e.g.

```
git checkout -b gardening-test-sema --track origin/master
git cherry-pick 3663793
git push <origin> gardening-test-sema
```

**Comment by AnthonyLatsis** [comment]
I force-pushed to avoid creating a new PR. Thanks @xedin, I wasn't aware of the cherry-pick command.

**Review by xedin — COMMENTED** [review]
I only have one question - what is the main goal for (what do we gain besides 80 line limit) changing all these messages? The down-side is that it would be harder to figure out who originally added/modified content of the messages/test-cases in the suite.

**Comment by AnthonyLatsis** [comment]
You have a point. It's not really about a line limit, I was simply trying to make everything readable and tidy. But if this is fraught with regression complications, I would agree it isn't worth it.

**Comment by xedin** [comment]
To be honest I don't think this is worth it because of aforementioned reason, but it seems like this was a lot of work so I don't really want to just throw it all out either...

**Comment by AnthonyLatsis** [comment]
Don't worry, I understand the reasons. It's perfectly fine. I have learned something new, after all :)

**Comment by xedin** [comment]
Alright, sounds good! I'm going to close this one then...

**Pull request closed without merging**
