### PR TITLE
[gardening][Parse] Dead code elimination

### PR DESCRIPTION
**Pull request by rintaro**
Remove two conditional statements.

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test Linux

**Comment by rintaro** [comment]
[First try](https://ci.swift.org/job/swift-PR-Linux-smoke-test/1487/console):
@ddunbar Have you ever seen this?
```
******************** TEST 'llbuild :: BuildSystem/Build/missing-inputs.llbuild' FAILED ********************
...
inputs.llbuild:12:18: error: expected string not found in input
# CHECK-FAILURE: missing input 'input' and no rule to build it
                 ^
/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/buildbot_linux/llbuild-linux-x86_64/tests/BuildSystem/Build/Output/missing-inputs.llbuild.tmp.out:1:1: note: scanning from here
/bin/sh -c true
^
/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/buildbot_linux/llbuild-linux-x86_64/tests/BuildSystem/Build/Output/missing-inputs.llbuild.tmp.out:4:26: note: possible intended match here
<unknown>:0: error: cannot build 'output-1' due to missing input
                         ^
```


[Second try](https://ci.swift.org/job/swift-PR-Linux-smoke-test/1489/console): 😞 
```
TestFoundation/TestNSURLSession.swift:40: error: TestURLSession.test_dataTaskWithURL : Asynchronous wait failed - Exceeded timeout of 12.0 seconds, with unfulfilled expectations: data task
TestFoundation/TestNSURLSession.swift:42: error: TestURLSession.test_dataTaskWithURL : XCTAssertEqual failed: ("unknown") is not equal to ("Kathmandu") - test_dataTaskWithURLRequest returned an unexpected result
```

**Comment by rintaro** [comment]
@swift-ci Please smoke test Linux

**Comment by DougGregor** [comment]
Good find, thanks!

**Comment by ddunbar** [comment]
@rintaro nope, I haven't. Worth a JIRA and you can put it on me.

**Pull request merged**
