### PR TITLE
NSNumber custom AnyHashable fix

### PR DESCRIPTION
**Pull request by itaiferber**
**What's in this pull request?**
Resolves rdar://problem/33105735.

When we give `NSNumber` a custom `AnyHashable` representation, we want to give it as large a box as possible. When we want to compare it against other `AnyHashable` boxes such as `Int` or `UInt`, it's always possible to upcast the `Int`/`UInt` to a larger integer size like `Int64` or `UInt64` for the comparison. By eliminating the smaller boxes we create, we can maintain the existing behavior that `_SwiftTypePreservingNSNumber` gave us.

### CODE REVIEW

**Comment by itaiferber** [comment]
@swift-ci Please test macOS

**Comment by itaiferber** [comment]
@swift-ci Please smoke test Linux

**Comment by parkera** [comment]
cc @airspeedswift

**Review by parkera — APPROVED** [review]

**Comment by airspeedswift** [comment]
Thanks for fixing!

**Pull request merged**
