### PR TITLE
Standardize "future" OS versions on 99.99.

### PR DESCRIPTION
**Pull request by mikeash**
We had multiple different "future" versions for different OSes. Make them all the same for consistency.

rdar://101929999

### CODE REVIEW

**Comment by mikeash** [comment]
@swift-ci please test

**Review by tbkka — APPROVED** [review]

**Review by nate-chandler — APPROVED** [review]

**Review by eeckstein — APPROVED** [review]

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
Looks like an update to LLVM will be needed:

```
<unknown>:0: error: invalid version number in '-target x86_64-apple-watchos99.99.0-simulator'
Assertion failed: (OsVersion < VersionTuple(10) && "Invalid version!"), function getDarwinDefines, file OSTargets.cpp, line 101.
```

And here's that assertion:

```
  // llvm-project/clang/lib/Basic/Targets/OSTargets.cpp:100
  } else if (Triple.isWatchOS()) {
    assert(OsVersion < VersionTuple(10) && "Invalid version!");
```

**Comment by tbkka** [comment]
CC: @drexin

**Comment by nate-chandler** [comment]
Looks to have been handled over on rebranch: https://github.com/apple/llvm-project/blob/stable/20221013/clang/lib/Basic/Targets/OSTargets.cpp#L73 by https://github.com/apple/llvm-project/commit/e039490a684067 .

**Comment by mikeash** [comment]
That explains it! I'll try again with that.

**Comment by mikeash** [comment]
@swift-ci please test

**Pull request merged**
