### PR TITLE
[silgen] Change SILGenApply to use destructure, eliminating copies at…

### PR DESCRIPTION
**Pull request by gottesmm**
… -Onone, and simplifying code.

rdar://43493020

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Review by slavapestov — APPROVED** [review]

**Review by rjmccall — APPROVED** [review]
LGTM.

**Comment by gottesmm** [comment]
I forgot locally a using declaration. Did a force push to fix the issue. Nothing else has changed.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@swift-ci test

**Pull request merged**
