### PR TITLE
[AutoDiff] [stdlib] Conform 'Array.DifferentiableView' to collection protocols.

### PR DESCRIPTION
**Pull request by rxwei**
* Conform 'Array.DifferentiableView' to collection protocols.
* Massively revamp precondition messages.

### CODE REVIEW

**Comment by rxwei** [comment]
cc @eaplatanios

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by rxwei** [comment]
An IRGen crasher is expected.

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by dan-zheng** [comment]
I accidentally deleted `tensorflow` branch, which closed this PR. That was not intentional, sorry!

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
