### PR TITLE
Remove \brief commands from doxygen comments.

### PR DESCRIPTION
**Pull request by adrian-prantl**
[This is analogous to LLVM r331272 and CFE r331834]

We've been running doxygen with the autobrief option for a couple of
years now. This makes the \brief markers into our comments
redundant. Since they are a visual distraction and we don't want to
encourage more \brief markers in new code either, this patch removes
them all.

Patch produced by

      for i in $(git grep -l '\\brief'); do perl -pi -e 's/\\brief //g' $i & done

### CODE REVIEW

**Review by jckarter — APPROVED** [review]
Sounds great to me!

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
Next up on the chopping block: the really old style of "FooMethod - Does the foo thing."

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
That test failure looks unrelated.

@swift-ci smoke test

**Pull request merged**
