### PR TITLE
[build-script] build and test indexstore-db and sourcekit-lsp

### PR DESCRIPTION
**Pull request by benlangmuir**
Add support to build-script to build and test the indexstore-db and
sourcekit-lsp projects. A future change will add support for installing
these products and putting them in the toolchain.  To build the new
products, add the `--sourcekit-lsp` or `--indexstore-db` options to a
`build-script` invocation.

We add the notion of a Product that is not part of build-script-impl and
build these products after the install phase of build-script-impl. These
products are built using the installed toolchain - either using the
default location within the build subdirectory, or the user-specified
`--install-dest`. This is somewhat rigid setup, since it requires the
toolchain used to build to be the same as the final installed toolchain
(if any), but it makes for a simpler change to the existing builds while
still making progress towards a toolchain-based build model.

*Note*: currently, if you are not using a preset you will need to
manually specify all of the dependencies (on macOS this is
swiftpm and llbuild, on other platforms you additionally need
libdispatch, icu, foundation, and xctest), and the install flags for the
same projects (`--install-llbuild --install-swiftpm ...`). This is not
particularly user-friendly, but it matches the current behaviour of the
other targets, and there is not yet any infrastructure in build-script
to describe these dependencies.

### CODE REVIEW

**Comment by benlangmuir** [comment]
@swift-ci please smoke test

**Comment by benlangmuir** [comment]
@swift-ci please smoke test

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
The failure is a perf test that has too high a stddev.  We really don't want to check the performance when running in CI unless it's explicitly configured, since otherwise the variation is likely to be very high on loaded machines.  We'd still like to run the test if possible.

**Comment by benlangmuir** [comment]
@swift-ci please test Linux

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please build toolchain

**Comment by benlangmuir** [comment]
@swift-ci please test macOS

**Comment by benlangmuir** [comment]
@swift-ci please build toolchain macOS

**Comment by benlangmuir** [comment]
preset=buildbot_incremental,tools=RA,stdlib=RA
@swift-ci Please test with preset macOS

**Comment by benlangmuir** [comment]
preset=buildbot_incremental_linux
@swift-ci Please test with preset Linux

**Comment by benlangmuir** [comment]
@shahmishal could you please look at the preset changes here? I can also split those into a separate PR if that makes sense.  I've tested the basics (toolchains, smoke test PR, non-smoke PR) and am currently running the presets we use for incremental bots.  Not sure what else is worth checking.

**Comment by benlangmuir** [comment]
@Rostepher I'd appreciate your review on the build-script changes.

**Comment by benlangmuir** [comment]
preset=buildbot_incremental_linux
@swift-ci Please test with preset Linux

**Review by shahmishal — APPROVED** [review]
LGTM, before we merge this I will need to update CI bot to check out two new repositories

**Comment by benlangmuir** [comment]
@swift-ci please smoke test

**Comment by benlangmuir** [comment]
Verified that the toolchains contain libc++ headers and that my C++ project will build using this toolchain's clang.

**Comment by benlangmuir** [comment]
Test failure should be fixed by https://github.com/apple/sourcekit-lsp/pull/82

**Comment by benlangmuir** [comment]
@swift-ci please smoke test Linux

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please smoke test macOS

**Comment by benlangmuir** [comment]
@swift-ci please build toolchain

**Comment by benlangmuir** [comment]
@swift-ci please test macOS

**Pull request merged**
