### PR TITLE
build: switch swift-corelibs-foundation to CMake

### PR DESCRIPTION
**Pull request by compnerd**
swift-corelibs-foundation has had a CMake based build system for a while
now.  Switch the official builds over to it.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-corelibs-foundation/pull/1720

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720

@swift-ci please test

**Comment by gottesmm** [comment]
Nice! @compnerd does this mean that we don't need to use the weird build.py thing on Linux anymore?

**Comment by compnerd** [comment]
@gottesmm, yeap, that build.py can go away once this is merged!

**Comment by gottesmm** [comment]
Awesome! Another of the swift project's build systems bites the dust!

**Comment by compnerd** [comment]
Ugh, FindICU was added in CMake 3.7.  Time to replicate.

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720

@swift-ci please test Linux platform

**Comment by gottesmm** [comment]
@compnerd Took a quick look at the error. I think that somethings are getting imported wrong from the Framework. See:

01:03:31 /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/swift-corelibs-foundation/Foundation/NSCalendar.swift:15:35: error: type 'CFCalendarUnit' (aka 'UInt') has no member 'day'
01:03:31 internal let kCFCalendarUnitDay = CFCalendarUnit.day.rawValue
01:03:31                                   ^~~~~~~~~~~~~~ ~~~

Clearly it is expected to be an enum I think.

**Comment by compnerd** [comment]
@gottesmm ... that sounds very likely.  Yes, it is an enum (see `CoreFoundation.framework/Headers/CFCalendar.h`).  That would explain why it works for me locally but fails on the build bot!

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720

@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@gottesmm, @DougGregor - okay, this now reproduces the weird failure with plutil:

```
15:33:55 /home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-master/swift-corelibs-foundation/Tools/plutil/main.swift:205:80: error: cannot call value of non-function type 'DisplayType'
15:33:55                 fatalError("plists should have strings as keys but got a \(type(of: $0.0))")
15:33:55                                                                            ~~~~^
15:33:55 /home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-master/swift-corelibs-foundation/Tools/plutil/main.swift:305:42: error: cannot call value of non-function type 'DisplayType'
15:33:55         fatalError("unhandled type \(type(of: plist))")
15:33:55                                      ~~~~^
```

@millenomi - you may be interested in this as well.

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720

@swift-ci please test Linux platform

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720

@swift-ci please test

**Comment by millenomi** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720
https://github.com/apple/swift-llbuild/pull/388

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720
apple/swift-llbuild#388

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720
apple/swift-llbuild#388

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720
apple/swift-llbuild#388
https://github.com/apple/swift-package-manager/pull/1833

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-corelibs-foundation/pull/1738
apple/swift-corelibs-foundation#1720
apple/swift-llbuild#388
apple/swift-package-manager#1833

@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1740
apple/swift-corelibs-foundation#1720
apple/swift-llbuild#388
apple/swift-package-manager#1833

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1740
apple/swift-corelibs-foundation#1720
apple/swift-llbuild#388
apple/swift-package-manager#1833

@swift-ci please test Linux platform

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720
apple/swift-llbuild#388
apple/swift-package-manager#1833

@swift-ci please test Linux platform

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720
apple/swift-llbuild#388
apple/swift-package-manager#1833

@swift-ci please test Linux platform

**Comment by gottesmm** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720
apple/swift-llbuild#388
apple/swift-package-manager#1833

@swift-ci please test Linux platform

**Comment by gottesmm** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720
apple/swift-llbuild#388
apple/swift-package-manager#1833

@swift-ci please test Linux platform

**Comment by gottesmm** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720
apple/swift-llbuild#388
apple/swift-package-manager#1833

@swift-ci please test Linux platform

**Comment by gottesmm** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720
apple/swift-llbuild#388
apple/swift-package-manager#1833

@swift-ci please test Linux platform

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720
apple/swift-llbuild#388
apple/swift-package-manager#1833

@swift-ci please test Linux platform

**Comment by gottesmm** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720
apple/swift-llbuild#388
apple/swift-package-manager#1833

@swift-ci please test Linux platform

**Comment by gottesmm** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720
apple/swift-llbuild#388
apple/swift-package-manager#1833

@swift-ci please test Linux platform

**Comment by gottesmm** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720
apple/swift-llbuild#388
apple/swift-package-manager#1833

@swift-ci please test Linux platform

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720
apple/swift-llbuild#388
apple/swift-package-manager#1833

@swift-ci please test Linux platform

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720
apple/swift-llbuild#388
apple/swift-package-manager#1833

@swift-ci please test Linux platform

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720
apple/swift-llbuild#388
apple/swift-package-manager#1833
https://github.com/apple/swift-llvm/pull/121

@swift-ci please test Linux platform

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720
apple/swift-llbuild#388
apple/swift-package-manager#1833
apple/swift-llvm#121
https://github.com/apple/swift-corelibs-xctest/pull/230

@swift-ci please test Linux platform

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720
apple/swift-llbuild#388
apple/swift-package-manager#1833
apple/swift-llvm#121
apple/swift-corelibs-xctest#230

@swift-ci please test Linux platform

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720
apple/swift-llbuild#388
apple/swift-package-manager#1833
apple/swift-llvm#121
apple/swift-corelibs-xctest#230

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720
apple/swift-llbuild#388
apple/swift-package-manager#1833
apple/swift-llvm#121
apple/swift-corelibs-xctest#230

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#1720
apple/swift-llbuild#388
apple/swift-package-manager#1833
apple/swift-llvm#121
apple/swift-corelibs-xctest#230

@swift-ci please test

**Comment by spevans** [comment]
@compnerd Will this still build and install the `libFoundation.a` static library?

**Comment by spevans** [comment]
@compnerd I think this may be causing some issues with xctest not being able to find CoreFoundation.h on macOS, see:

https://ci.swift.org/view/Pull%20Request/job/swift-corelibs-foundation-PR-macOS/139/consoleFull#12153878463122a513-f36a-4c87-8ed7-cbc36a1ec144

https://ci.swift.org/view/Pull%20Request/job/swift-corelibs-foundation-PR-macOS/138/console

`/Users/buildnode/jenkins/workspace/swift-corelibs-foundation-PR-macOS/branch-master/Ninja-ReleaseAssert/xctest-macosx-x86_64/Release/usr/local/include/CoreFoundation/module.modulemap:2:21: error: umbrella header 'CoreFoundation.h' not found`

**Pull request merged**
