### PR TITLE
[Serialization] InitAccessors: Use correct code for `@storageRestrict…

### PR DESCRIPTION
**Pull request by xedin**
…ions` serialization

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test

**Review by xymus — APPROVED** [review]
Thank you!

**Comment by xedin** [comment]
@swift-ci please clean test Linux

**Comment by xedin** [comment]
@swift-ci please test Linux

**Pull request merged**
