### PR TITLE
[SILGen] Consuming a param implies it's eager-move.

### PR DESCRIPTION
**Pull request by nate-chandler**
If a parameter is marked consuming and its type is Copyable, that parameter has eager-move semantics.  Apply that attribute to the `SILFunctionArgument` corresponding to the parameter.

rdar://108385761

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by atrick — APPROVED** [review]
Perfect!

**Comment by nate-chandler** [comment]
@swift-ci please test

**Pull request merged**
