### PR TITLE
[NFC] Give test input header a meaningful name.

### PR DESCRIPTION
**Pull request by zoecarver**
Re-name the file "foo.h" in the SILOptimizer inputs to "TypesWithUserProvidedDestructor.h" which better describes its purpose (to define types with user-provided destructors).

### CODE REVIEW

**Comment by gottesmm** [comment]
Please add something to the name that makes it clear the header has cxx code in it.

**Comment by gottesmm** [comment]
LGTM

**Review by gottesmm — APPROVED** [review]

**Comment by zoecarver** [comment]
@gottesmm thanks!

**Comment by zoecarver** [comment]
@swift-ci please smoke test and merge

**Comment by zoecarver** [comment]
@swift-ci please smoke test and merge.

**Comment by zoecarver** [comment]
@swift-ci please smoke test

**Comment by zoecarver** [comment]
@swift-ci please smoke test OS X platform

**Pull request merged**
