### PR TITLE
[tests] Make `ninja check-swift` 4.1x faster on high-end workstations

### PR DESCRIPTION
**Pull request by davezarzycki**

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test

**Comment by jckarter** [comment]
Will PR testing still run this test? Is there any way we can make the test itself faster and still get useful coverage from it?

**Comment by davezarzycki** [comment]
There might be a better solution. This was just the quickest. Who owns this test?

**Comment by davezarzycki** [comment]
PS – This test is almost as long as the *entire* validation test suite on my Linux box. :-(

**Comment by benlangmuir** [comment]
@nkcsgexi Most of the time in this test is spent in the python code that diffs the results.  If I skip the diff, this test takes 10 seconds on my machine.  With the diff it's around 80 seconds.

**Comment by davezarzycki** [comment]
What’s wrong with classic-and-fast `diff`? Also, 10 seconds without the diffing is okay but not great. That’s still almost half of the entire `ninja check-swift` time on a fast workstation.

**Comment by benlangmuir** [comment]
This test could also be trivially parallelized since it's running independently over each file and just reducing at the end to set the return code.

**Comment by harlanhaskins** [comment]
@davezarzycki IIRC the switch from `diff` was for Windows support.

**Review by nkcsgexi — APPROVED** [review]
The change looks reasonable to me! In longer term, we plan to rely more on the stress-tester to run SwiftSyntax on user projects; the importance of running on the stdlib source will decrease.

**Comment by benlangmuir** [comment]
Here's a fix for the difflib slowness by first comparing for `==` before doing the slow diff.  https://github.com/apple/swift/pull/22653

**Comment by davezarzycki** [comment]
Abandoned in favor of #22653

**Pull request closed without merging**
