### PR TITLE
[BitwiseCopyable] Fix resilient enum type info.

### PR DESCRIPTION
**Pull request by nate-chandler**
Like other `EnumTypeInfo`s, the `TypeInfo` subclasses `EnumTypeInfoBase` and store the `EnumImplStrategy`.

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please smoke test

**Comment by nate-chandler** [comment]
@swift-ci please smoke test linux platform

**Comment by nate-chandler** [comment]
@swift-ci please smoke test linux platform

**Review by aschwaighofer — APPROVED** [review]
LGTM

**Pull request merged**
