### PR TITLE
[AutoDiff] Add adjoints for sum and mean.

### PR DESCRIPTION
**Pull request by dan-zheng**
Add adjoints for sum and mean, which are commonly used reduction operations.
Overload variadic `Tensor` ops with array argument versions. Array argument versions
are more general than variadic versions.
Remove redundant conformances from `Tensor` gradient operators.

### CODE REVIEW

**Review by rxwei — APPROVED** [review]

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by rxwei** [comment]
@swift-ci please test tensorflow

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow

**Pull request merged**
