### PR TITLE
[interop] 'conforms_to' attribute should be qualified with module name

### PR DESCRIPTION
**Pull request by hyp**
Also, improve the diagnostics for 'conforms_to'

### CODE REVIEW

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test source compatibility

**Review by zoecarver — APPROVED** [review]
This is a wonderful improvement. Thank you, Alex!

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test source compatibility

**Pull request merged**
