### PR TITLE
Fixes for @_versioned/@_inlineable

### PR DESCRIPTION
**Pull request by slavapestov**
A couple of corner cases that only really matter for the standard library. Thanks to @swiftix for the bug reports.

Fixes <rdar://problem/34572209>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please clean smoke test Linux

**Comment by swiftix** [comment]
@moiseev You can update your PR now.

**Pull request merged**
