### PR TITLE
DOCS: Add missing periods

### PR DESCRIPTION
**Pull request by amartini51**
Fixes: rdar://131169795

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Review by ktoso — APPROVED** [review]

**Comment by ktoso** [comment]
Thanks Alex, approved it

**Comment by amartini51** [comment]
@swift-ci Please smoke test.

**Comment by lamtrinhdev** [comment]
Dear @ktoso ,

Could you please help us to trigger @swift-ci again?

Thanks,
Lam

**Comment by ktoso** [comment]
@swift-ci please smoke test Linux

**Comment by ktoso** [comment]
Done and enabled auto merge

**Comment by lamtrinhdev** [comment]
Dear @ktoso ,

Thank you for your support.

Thanks,
Lam

**Pull request merged**
