### PR TITLE
AST: Make $SpecializeAttributeWithAvailability a baseline feature

### PR DESCRIPTION
**Pull request by tshortli**
It has been available since at least Swift 5.8.

### CODE REVIEW

**Comment by tshortli** [comment]
@swift-ci please smoke test

**Comment by tshortli** [comment]
https://github.com/swiftlang/swift-driver/pull/1702

@swift-ci please smoke test Linux

**Review by DougGregor — APPROVED** [review]
Thank you!

**Comment by tshortli** [comment]
https://github.com/swiftlang/swift-syntax/pull/2858

@swift-ci please smoke test Linux

**Comment by tshortli** [comment]
https://github.com/swiftlang/swift-syntax/pull/2858

@swift-ci please smoke test Linux

**Comment by tshortli** [comment]
@swift-ci please smoke test Linux

**Pull request merged**
