### PR TITLE
[5.9] [Changelog] Add changelog entry for SE-0380

### PR DESCRIPTION
**Pull request by hamishknight**
*5.9 cherry-pick of https://github.com/apple/swift/pull/65887*

SE-0380

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please smoke test

**Comment by hamishknight** [comment]
@swift-ci please test

**Review by airspeedswift — APPROVED** [review]

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Comment by altairdeark** [comment]
Hi @hamishknight , i am facing an issue with SE-0380 and latest xcode Beta. Now **Return** have unexpected behavior in case if **if** or **switch** used after it.

Compilable
```
func test() {
          print('1')
          return /// expect the end of progamm here

          if true {
               print('2') /// still will be executable, bcs if now is equal to ()
          } else {
               print('3')
          }

          return
}
```


Result:
```
1
2
```
2 is unexpected

I believe Swift update should complement rather than break the existing one. Is it a known issue?

**Comment by hamishknight** [comment]
@altairdeark This is expected, see https://github.com/apple/swift-evolution/blob/main/proposals/0380-if-switch-expressions.md#source-compatibility:

> As proposed, this addition has one source incompatibility, related to unreachable code. The following currently compiles, albeit with a warning that the if statement is unreachable (and the values in the branches unused):
> 
> ```swift
> func foo() {
>   return
>   if .random() { 0 } else { 0 }
> }
> ```

The code provided produces the following warning:

```swift
func test() {
  print("1")
  return

  if true { // warning: expression following 'return' is treated as an argument of the 'return'
    print("2")
  } else {
    print("3")
  }

  return
}
```

**Comment by altairdeark** [comment]
@hamishknight ,

Still it is breaks the **old code**, and not everyone will recheck whole code base to fix this warning, since in older project i have 1000+ warnings. In my case in `if` i was having an unexpected server API calls which was a total surprise for me since i was not aware of SE-0380. I believe it could also breaks others project, libs and else.

Do we have any option to solve it? like: when after `return` we have a new line or `\r`, so it should not treat `If` as an argument for `return` and just behave as it was.

**Comment by hamishknight** [comment]
@altairdeark You can add a `;` to the end of the `return` to avoid treating the following expression as part of the `return`

**Pull request merged**
