### PR TITLE
[CSBindings] A couple of adjustments to transitive protocol inference

### PR DESCRIPTION
**Pull request by xedin**
-  Use all equivalence chain members while interring transitive protocols
- Infer transitive protocols only for unresolved member base

Resolves: rdar://75978086

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please smoke test

**Review by hborla — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please smoke test Windows platform

**Comment by xedin** [comment]
@swift-ci please smoke test Linux platform

**Comment by xedin** [comment]
@swift-ci please smoke test Linux platform

**Comment by xedin** [comment]
@swift-ci please smoke test Windows platform

**Pull request merged**
