### PR TITLE
Fail cleanly for certain invalid manglings

### PR DESCRIPTION
**Pull request by tbkka**
There are certainly more such issues in this code, but this is one that was recently reported.

While here, re-enable some disabled test cases that currently pass.

Resolves rdar://104671103

### CODE REVIEW

**Review by al45tair — APPROVED** [review]
LGTM. I notice we have a few tests with the `->` versus `--->` problem still; presumably they only "work" because they're missing the `$` from the front as well?

**Comment by tbkka** [comment]
@swift-ci Please test

**Comment by tbkka** [comment]
Test lines that do not use `--->` are ignored entirely.   I looked at re-enabling all such tests, but a number of them still fail.   Obviously, we should look into those.

**Comment by tbkka** [comment]
@swift-ci Please test Linux

**Pull request merged**
