### PR TITLE
Revert "Emit Debug Variables for Errors Bound in Catch Clauses"

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/swift#40372

This regressed the windows CI: https://ci-external.swift.org/job/swift-PR-windows/18932/consoleText

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
CC: @CodaFi

**Comment by CodaFi** [comment]
This is not the cause of the async regression AFAICT.

**Comment by compnerd** [comment]
@CodaFi CI seems to indicate so, the buildbot seems to agree (note that the CI has returned green on Windows vs main).

**Comment by CodaFi** [comment]
Could we XFAIL this if I trade you a radar/SR pair? This test has been historically flaky and is usually a leading indicator of instability in async code gen.

**Comment by compnerd** [comment]
@CodaFi if you throw in a forced merge, I'll bite.

**Comment by CodaFi** [comment]
https://bugs.swift.org/browse/SR-15552

**Pull request closed without merging**
