### PR TITLE
resolve-crashes.py: remove "REQUIRES: asserts" as well

### PR DESCRIPTION
**Pull request by jrose-apple**
We keep doing this by hand and there's no reason to do so.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
@swift-ci Please Python lint

**Comment by practicalswift** [comment]
Looks good! :-)

**Review by practicalswift — APPROVED** [review]

**Comment by DougGregor** [comment]
Good call, thanks!

**Pull request merged**
