### PR TITLE
CMake: Break some dependency cycles between compiler libraries

### PR DESCRIPTION
**Pull request by tshortli**
- Remove cycle between `swiftIRGen` and `swiftTBGen`.
- Remove cycle between `swiftSIL` and `swiftSerialization`.
- Remove cycle between `swiftFrontendTool` and `swiftIDE`.

### CODE REVIEW

**Comment by tshortli** [comment]
@swift-ci please smoke test

**Comment by etcwilde** [comment]
@swift-ci Build Toolchain macOS Platform

**Review by etcwilde — APPROVED** [review]
Love to see it. Assuming the tests all pass and we can build a successful toolchain build, LGTM!

**Comment by tshortli** [comment]
@swift-ci please smoke test Windows

**Pull request merged**
