### PR TITLE
Disable semantic arc opts for MichaelI benchmark run.

### PR DESCRIPTION
**Pull request by gottesmm**
Just for benchmarking to answer MichaelI's question.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci benchmark

**Comment by milseman** [comment]
@swift-ci please benchmark

**Comment by gottesmm** [comment]
Keep in mind b/c I disabled this, the performance is inverted. The improvements are regressions and vis-a-versa.

**Comment by milseman** [comment]
Sweet! Those LessSubstringSubstring are kinda crappy nano benchmarks that just measure the order in which we check fast paths. However, it is weird to see them regress. I wonder what else could cause that, as I don't think they have ARC involved (they're smol strings usually).

**Comment by gottesmm** [comment]
@milseman it could be due to layout changes caused by removing more ARC operations.

**Pull request closed without merging**
