### PR TITLE
[docs] Fix ReST errors in SIL.rst

### PR DESCRIPTION
**Pull request by jrose-apple**

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test and merge

**Comment by jrose-apple** [comment]
@rjmccall Please be careful when updating .rst files to make sure they build!

**Comment by jrose-apple** [comment]
Whoops, looks like Erik beat me to it in #12799.

**Comment by rjmccall** [comment]
Is there a good reason why building documentation isn't part of either level of CI testing?  I assume it's basically a zero-time build step.  Just installation complexity?

**Comment by jrose-apple** [comment]
Yeah, I assume the buildbots don't have Sphinx installed. I'll file a Radar.

**Comment by jrose-apple** [comment]
rdar://problem/35417894

**Pull request closed without merging**
