### PR TITLE
[ConstraintSystem] Refactor openGeneric/openFunctionType

### PR DESCRIPTION
**Pull request by xedin**
**Summary**:

- Remove unused parameters
- Extract logic related to opening generic parameters into `openGenericParameters`
- Remove `skip*` boolean flags from everywhere expect to `openGenericRequirements`
- Remove code duplication in CSRanking

### CODE REVIEW

**Comment by xedin** [comment]
This is actually a net negative loc PR which is NFC-ish :)

**Review by slavapestov — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
Looks like source compat suite fails with the same errors as master branch which are unrelated to my changes.

**Pull request merged**
