### PR TITLE
[Driver] Add missing `whole-archive` for sanitizer runtimes on Linux

### PR DESCRIPTION
**Pull request by yln**
Quickest possible fix for https://bugs.swift.org/browse/SR-10152

### CODE REVIEW

**Comment by yln** [comment]
@swift-ci Please test Linux

**Comment by yln** [comment]
Please test Linux

**Comment by yln** [comment]
@swift-ci Please test Linux

**Comment by jrose-apple** [comment]
:-( I liked your "pass `-fsanitize=` to Clang" answer better.

**Comment by yln** [comment]
> :-( I liked your "pass `-fsanitize=` to Clang" answer better.

I will create a follow-up pull request. Can we merge this quick fix (after CI says it's okay) to unblock me?

**Comment by jrose-apple** [comment]
I won't stop you but it doesn't seem like the other one is really harder. Either way you need a test case, though.

**Comment by compnerd** [comment]
I agree with @jrose-apple - this would be better with a test.  At that point, just using the `-fsanitize=` is better and more portable (it will eventually be needed for Windows too).

**Pull request closed without merging**
