### PR TITLE
[5.9][CMake] Replace early swift-syntax with FetchContent

### PR DESCRIPTION
**Pull request by rintaro**
Cherry-pick #68408 (and dependent #68273, #68388, and #68527)   into `release/5.9`

* **Explanation**: Build the `swift-syntax` host libraries using FetchContent rather than early-swiftsyntax. This simplifies the overall toolchain build process and fix the issues we've seen caused by swift-syntax not being rebuilt. We should be able to use this to fix cross-compiling on Linux
* **Scope**: Build system
* **Risk**: Mid, since we update the build mechanism. But removes some nasty hacks.
* **Testing**: Passes the current test suite
* **Issues**: rdar://115439072
* **Reviewer**: Ben Barham (@bnbarham)

### CODE REVIEW

**Comment by rintaro** [comment]
https://github.com/apple/llvm-project/pull/7543
https://github.com/apple/swift-syntax/pull/2250
@swift-ci Please test

**Comment by finagolfin** [comment]
Nice, I slapped up [my own 5.9 backport online a couple hours ago](https://github.com/termux/termux-packages/pull/18010/files#diff-d8ded119268bd7008c6bcacdcea5e06114a39a688bbebae777851581e4891f0b).

**Comment by rintaro** [comment]
https://github.com/apple/llvm-project/pull/7543
https://github.com/apple/swift-syntax/pull/2250
@swift-ci Please test

**Comment by rintaro** [comment]
https://github.com/apple/llvm-project/pull/7543
https://github.com/apple/swift-syntax/pull/2250
@swift-ci Please test

**Comment by rintaro** [comment]
https://github.com/apple/llvm-project/pull/7543
https://github.com/apple/swift-syntax/pull/2250
@swift-ci Please test

**Comment by rintaro** [comment]
https://github.com/apple/swift-installer-scripts/pull/248
https://github.com/apple/llvm-project/pull/7543
https://github.com/apple/swift-syntax/pull/2250
@swift-ci Please test

**Pull request closed without merging**
