### PR TITLE
build: recognize `amd64` in `CMAKE_SYSTEM_PROCESSOR`

### PR DESCRIPTION
**Pull request by mhjacobson**
On FreeBSD, cmake populates `CMAKE_SYSTEM_PROCESSOR` with `uname -p`, which results in "amd64", not "AMD64".

### CODE REVIEW

**Review by finagolfin — APPROVED** [review]

**Comment by mhjacobson** [comment]
Thanks—would you mind kicking off tests for me?

**Comment by buttaface** [comment]
I don't have commit/CI access, will have to wait till Monday morning.

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by mhjacobson** [comment]
Hey @CodaFi, I'm not sure where the test results went.  Is it possible it wants you to ask for a "Please smoke test" instead?  Sorry for the hassle.

**Comment by mhjacobson** [comment]
Thanks for kicking them off again.  Looks like both failed with the same error:

```
/Users/ec2-user/jenkins/workspace/swift-PR-macos@tmp/durable-21b9f011/script.sh: line 1: unexpected EOF while looking for matching `''
```

```
/tmp/jenkins-6c726955/workspace/swift-PR-Linux@tmp/durable-4bf9ee6c/script.sh: line 1: unexpected EOF while looking for matching `''
```

I don't currently know what this means, but it seems like a failure in the CI infrastructure rather than in building or testing.

**Comment by mhjacobson** [comment]
@CodaFi, I hate to be a bother, but I think I'm stuck here: I don't know what went wrong with the CI system, and I seem to have limited visibility into it.  Would you mind giving me a hand (again)?  Thanks!

**Comment by mhjacobson** [comment]
@compnerd, @al45tair, could one of you re-kick tests and review, please?  Thanks.

**Comment by al45tair** [comment]
@swift-ci Please test

**Review by compnerd — APPROVED** [review]

**Pull request merged**
