### PR TITLE
Fast-path contains() for empty Dictionaries

### PR DESCRIPTION
**Pull request by Catfish-Man**

### CODE REVIEW

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Comment by Catfish-Man** [comment]
@swift-ci please benchmark

**Review by lorentey — APPROVED** [review]
🚀

**Comment by lorentey** [comment]
I **love** how this shows a significant regression in `DictionaryOfAnyHashableStrings_insert`, even though afaict that benchmark doesn't go anywhere near the `contains` code path. 

The flaky 11% regression in `-Osize` for `DictionaryKeysContainsNative` could be due to a different inlining decision -- I don't think it's cause for worry. (FWIW, I think that benchmark is mostly about exercising `-[NSString hash/isEqual:]` on tagged pointers.)

**Comment by Catfish-Man** [comment]
That's some really weird benchmark results >.<

**Comment by Catfish-Man** [comment]
Yeah I'm gonna say something weird is going on with the benchmarks. ArrayAppendOptionals, which supposedly got 2x faster, literally does not contain any Dictionaries. Just gonna merge it.

**Comment by Panajev** [comment]
Apologies @Catfish-Man @lorentey but should not this warrant a benchmark fix to prove this PR is improving performance? I am not disputing the change nor I claim to be as competent as either of you, but from a process point of view (PR’s are history for a project) the only data the automation provided is mostly regressions and a very few performance improvements.
It feels like the tests should have been fixed before merging this, sorry if it comes off as presumptuous or rude.

**Comment by lorentey** [comment]
`DictionaryOfAnyHashableStrings_insert` keeps popping up in other benchmark runs (https://github.com/apple/swift/pull/38621) -- although usually it's marked as unreliable. It would likely be worth figuring out what makes it so unstable and fix it (or replace it altogether). The same goes for the other benchmarks that keep popping up with `(?)`, although it seems `DictionaryOfAnyHashableStrings_insert` has the wildest swings of them all.

**Pull request merged**
