### PR TITLE
Sema: Eliminate some piecemeal unavailability diagnostics

### PR DESCRIPTION
**Pull request by tshortli**
There were a few parts of the compiler that were specifically diagnosing just the _unavailability_ of declarations in certain synthesized code:

- Extraction of enum elements from `ClangImporter` synthesized enum element accessors with Swift 2-era names.
- References to `wrappedValue` accessors in synthesized property accessors for wrapped vars.

These piecemeal diagnostics can be subsumed by performing full availability checks on the decl refs instead to catch more issues while also reducing the amount of availability spaghetti there is to maintain and refactor.

### CODE REVIEW

**Comment by tshortli** [comment]
@swift-ci please smoke test

**Comment by tshortli** [comment]
@swift-ci please smoke test

**Comment by aschwaighofer** [comment]
Could this have caused the failures on https://ci.swift.org/job/swift-main-source-compat-suite/938/ and  https://ci.swift.org/job/swift-main-source-compat-suite-debug/938/


```
/Users/ec2-user/jenkins/workspace/swift-main-source-compat-suite-debug/swift-source-compat-suite/project_cache/Doggie/Sources/DoggieGeometry/ApplePlatform/Geometry/CGPath.swift:238:19: error: 'curveTo' is only available in macOS 11.0 or newer
206 | #elseif canImport(AppKit)
207 | 
208 | extension NSBezierPath: BezierPathConvertible {
    | `- note: add @available attribute to enclosing extension
209 |     
210 |     fileprivate var _currentPoint: Point {
    :
228 |     }
229 |     
230 |     fileprivate func _copy<Other: BezierPathConvertible>(to path: inout Other) {
    |                      `- note: add @available attribute to enclosing instance method
231 |         
232 |         var points = [CGPoint](repeating: CGPoint(), count: 3)
    :
236 |             case .moveTo: path._move(to: Point(points[0]))
237 |             case .lineTo: path._line(to: Point(points[0]))
238 |             case .curveTo: path._curve(to: Point(points[2]), control1: Point(points[0]), control2: Point(points[1]))
    |                   |- error: 'curveTo' is only available in macOS 11.0 or newer
    |                   `- note: add 'if #available' version check
239 |             case .closePath: path._close()
240 |             @unknown default: break

```
rdar://138771328

**Comment by tshortli** [comment]
> Could this have caused the failures on https://ci.swift.org/job/swift-main-source-compat-suite/938/ and https://ci.swift.org/job/swift-main-source-compat-suite-debug/938/

Yes, it probably has. I'm taking a look, thanks for the heads up!

**Pull request merged**
