### PR TITLE
[GSB] Never drop type-parameter-to-concrete requirements.

### PR DESCRIPTION
**Pull request by DougGregor**
Generic signature canonicalization/minimization never removes type
parameters, so we cannot suppress type-parameter-to-concrete
requirements even when they are derived.

Fixes the rest of the known cases of rdar://problem/30478915.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test and merge

**Comment by slavapestov** [comment]
Awesome! @swiftix This might make you happy...

**Comment by DougGregor** [comment]
I'm sure the @swiftix fuzzer will find more cases ;)

**Comment by swiftix** [comment]
Yay! Looks like the fuzzer will have a lot of fun today! :-) Be prepared for more corner cases!

**Comment by DougGregor** [comment]
The idempotence assertion still fails in a few cases, so we're not "done" yet.

**Comment by DougGregor** [comment]
The idempotence assertion is re-introduced in https://github.com/apple/swift/pull/8317, which passes locally for me

**Comment by swiftix** [comment]
@DougGregor If I enable partial specialization and try to build the stdlib, I hit:


Assertion failed: (builder->getGenericSignature()->getCanonicalSignature() == sig), function getOrCreateGenericSignatureBuilder, file /Users/roman/src/s/swift/lib/AST/ASTContext.cpp, line 1220.

**Pull request merged**
