### PR TITLE
Parse: Offer a fix-it when platform is specified with the wrong case in availability attributes and queries

### PR DESCRIPTION
**Pull request by tshortli**
Example:
```
availability.swift:23:12: warning: unknown platform 'macos' for attribute 'available'; did you mean 'macOS'?
@available(macos, unavailable)
           ^~~~~
           macOS
```

Resolves rdar://100195680

### CODE REVIEW

**Review by xymus — APPROVED** [review]
Nice QOL improvement.

I don't know if it's worth it here but I believe this could also handle simple typos if we use the string distance services `StringRef::edit_distance` to compare the original platform name with all known platform names and return the closest one.

**Comment by tshortli** [comment]
> Nice QOL improvement.
> 
> I don't know if it's worth it here but I believe this could also handle simple typos if we use the string distance services `StringRef::edit_distance` to compare the original platform name with all known platform names and return the closest one.

That's a good idea - I opened https://github.com/apple/swift/issues/61237 to track investigating that as a follow up.

**Comment by tshortli** [comment]
@swift-ci please test

**Comment by tshortli** [comment]
@swift-ci please smoke test and merge

**Comment by tshortli** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
