### PR TITLE
[c-interop] Make Extern a suppressible language feature

### PR DESCRIPTION
**Pull request by tshortli**
Fixes building the standard library's .swiftinterface with older Swift compilers.

### CODE REVIEW

**Comment by tshortli** [comment]
Addresses regression from https://github.com/apple/swift/pull/69352.

**Comment by tshortli** [comment]
@swift-ci please smoke test

**Comment by kateinoigakukun** [comment]
@tshortli Thank you for fixing this :pray: I don't know when older compiler parses newer stdlib's module interface, but is it safe to change the symbol name depending on whether the compiler supports the feature?

Looks like other suppressible language features are not ABI-affecting features but `@_extern` is.

**Comment by tshortli** [comment]
If `@_extern` here affects the ABI of something that was existing and therefor users in this configuration might actually depend on then I suppose your concern is valid. If that's the case I'm afraid we need to revert https://github.com/apple/swift/pull/69352 and go back to the drawing board with how to implement it in a way that does not break the stdlib interface for older compilers.

**Comment by kateinoigakukun** [comment]
Thanks for your detailed explanation. Those functions attributed with `@_extern` are only referenced from debugger, so hopefully it just breaks LLDB's `language swift refcount` command. To avoid the breakage, I think the safest way would be to keep the old wrong (but works on most platforms) way like below:

```swift
#if compiler(>=5.3) && $Extern
@_extern(c, "swift_retainCount") @usableFromInline
#else
@_silgen_name("swift_retainCount")
#endif
internal func _swift_retainCount(_: UnsafeMutableRawPointer) -> Int
```

**Comment by tshortli** [comment]
It looks to me like the functions that gained `@_extern(c)` in https://github.com/apple/swift/pull/69352 are only the `retainCount` family of functions, which are only ever used from the debugger right? If that's the case, I'm inclined to say that it's unfortunate but not a showstopper that they be broken in the configuration where an older compiler is being used. However, we should fix this properly in a follow up. It looks to me like maybe a proper fix for this would be to print the `@_silgen_name(<name>)` attribute instead of `@_extern(c, <name>)` for the branch where the `@_extern` attribute is not supported. Does that make sense? It seems like it would return things to the status quo from before https://github.com/apple/swift/pull/69352.

**Review by lorentey — APPROVED** [review]
Looks good! Thank you for following up on this. 👍

**Comment by kateinoigakukun** [comment]
> It looks to me like the functions that gained @_extern(c) in https://github.com/apple/swift/pull/69352 are only the retainCount family of functions, which are only ever used from the debugger right?

Yes, that's correct.

> If that's the case, I'm inclined to say that it's unfortunate but not a showstopper that they be broken in the configuration where an older compiler is being used. 

Yeah, that's reasonable. If it's not critical path, I think we can accept the breakage.

> It looks to me like maybe a proper fix for this would be to print the @_silgen_name(<name>) attribute instead of @_extern(c, <name>) for the branch where the @_extern attribute is not supported. Does that make sense?

Hmm, they have slightly different ABI semantics and we can expect there is no other usage of `@_extern` except for stdlib at the moment, so falling back as a part of compiler output might be too much.

**Review by kateinoigakukun — APPROVED** [review]

**Comment by tshortli** [comment]
@swift-ci please smoke test macOS

**Comment by tshortli** [comment]
@swift-ci please smoke test Linux

**Comment by tshortli** [comment]
@swift-ci please smoke test

**Pull request merged**
