### PR TITLE
[test] XFAIL Dictionary test to unblock CI

### PR DESCRIPTION
**Pull request by moiseev**
<rdar://problem/41871587>

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by moiseev** [comment]
```
UXPASS: ["BridgedToObjC.KeyValue_ValueTypesCustomBridged", "BridgedToObjC.Key_ValueTypeCustomBridged"]
```
🤔

**Comment by slavapestov** [comment]
Looks like it passes in PR testing but fails in CI. Could be related to enabling/disabling asserts, or running tests with optimizations, etc.

**Comment by lorentey** [comment]
I keep failing to reproduce this locally. While I'm working on finding the root cause, I'll try unconditionally disabling these tests in #17853.

**Pull request closed without merging**
