### PR TITLE
[swift-3.0-branch] Implementing SE-0137

### PR DESCRIPTION
**Pull request by moiseev**
#### What's in this pull request?
- Explanation: Implementation for [SE-0137](https://github.com/apple/swift-evolution/blob/master/proposals/0137-avoiding-lock-in.md). Commits are cherry-picked from the individual PRs opened against master.
- Scope of Issue: Applying this change will result in several new deprecation warnings during compilation, but no code will stop compiling. Most of the deprecation attributes have a hint for the XCode on how to fix it.
- Origination: Last minute changes to avoid committing to the current design of protocols in the standard library.
- Risk: Minimal
- Reviewed By: Dave Abrahams
- Testing: Ran the existing test suite.
- Directions for QA: N/A

rdar://problem/27894275

---

Before merging this pull request to apple/swift repository:
- [ ] Test pull request on Swift continuous integration.

<details>
  <summary>

Triggering Swift CI</summary>

The swift-ci is triggered by writing a comment on this PR addressed to the GitHub user @swift-ci. Different tests will run depending on the specific comment that you use. The currently available comments are:

**Smoke Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please smoke test |
| All supported platforms | @swift-ci Please smoke test and merge |
| OS X platform | @swift-ci Please smoke test OS X platform |
| Linux platform | @swift-ci Please smoke test Linux platform |

A smoke test on macOS does the following:
1. Builds the compiler incrementally.
2. Builds the standard library only for macOS. Simulator standard libraries and
   device standard libraries are not built.
3. lldb is not built.
4. The test and validation-test targets are run only for macOS. The optimized
   version of these tests are not run.

A smoke test on Linux does the following:
1. Builds the compiler incrementally.
2. Builds the standard library incrementally.
3. lldb is built incrementally.
4. The swift test and validation-test targets are run. The optimized version of these
   tests are not run.
5. lldb is tested.

**Validation Testing**

| Platform | Comment |
| --- | --- |
| All supported platforms | @swift-ci Please test |
| All supported platforms | @swift-ci Please test and merge |
| OS X platform | @swift-ci Please test OS X platform |
| OS X platform | @swift-ci Please benchmark |
| Linux platform | @swift-ci Please test Linux platform |

**Lint Testing**

| Language | Comment |
| --- | --- |
| Python | @swift-ci Please Python lint |

Note: Only members of the Apple organization can trigger swift-ci.
</details>

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by moiseev** [comment]
@swift-ci Please smoke test Linux platform

**Comment by rintaro** [comment]
I think, https://github.com/apple/swift/pull/4214 also needed.

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by moiseev** [comment]
Good catch, @rintaro! Thanks.

**Comment by moiseev** [comment]
Cherry picked the #4214 commit and removed the renaming of `Streamable` to `TextOutputStreamable` for now. Will include that one separately.
@swift-ci Please test

**Comment by tkremenek** [comment]
Enough tests are passing to merge.

**Pull request merged**
