### PR TITLE
[semantic-sil] Use SILGenFunction::emitManagedBufferWithCleanup instead of entering in a random cleanup.

### PR DESCRIPTION
**Pull request by gottesmm**
[semantic-sil] Use SILGenFunction::emitManagedBufferWithCleanup instead of entering in a random cleanup.

This is a small cleanup where we are creating a cleanup for an uninitialized
buffer that will be verified as initialized later by DI and then creating a +0
unmanaged ManagedValue for the value.

This violates the "norms" of using ManagedValue in SILGen which is that one
should use the SILGenFunction::emitManaged* methods for creating/propagating
cleanups around.

### CODE REVIEW

**Comment by gottesmm** [comment]
Hey Joe. I am pretty sure this is correct, but I want to get another set of eyes to look at this. The only reason I can think that this would be incorrect is if in general we do not propagate the cleanups for uninitialized things that DI will handle.

**Comment by gottesmm** [comment]
@swift-ci Please test

**Comment by gottesmm** [comment]
@jckarter Sorry, should have @ed you.

**Comment by gottesmm** [comment]
@ ed you.

**Comment by jckarter** [comment]
Seems reasonable. It definitely looks fishy the way it is.

**Review by jckarter — APPROVED** [review]
LGTM

**Comment by gottesmm** [comment]
Thanks Joe!

**Pull request merged**
