### PR TITLE
Revert "[CMake] Better dependency checking"

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/swift#38154

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
CC: @davezarzycki

**Comment by davezarzycki** [comment]
Context?

**Comment by compnerd** [comment]
https://github.com/apple/swift/pull/38154#issuecomment-873270990

Basically, the Windows builds actually build the swift standard library standalone, and use the `SWIFT_BUILD_RUNTIME_WITH_HOST_COMPILER` to avoid rebuilding the compiler, this check actually breaks that.

**Comment by compnerd** [comment]
Discussed offline with DaveZ.  Going to go forward with the revert for now, but we should look into what is causing a build issue on the different setup.  I think that with #38239 we should be able to handle the different variations of the build.  Going to test that on the Windows nightlies as well.

**Pull request merged**
