### PR TITLE
SILGen: Don't override the SourceLoc for magic identifiers in stored property initializers.

### PR DESCRIPTION
**Pull request by jckarter**
Refactoring stored property initializers to reuse the codegen for default argument generators caused them to accidentally inherit this additional bit of policy we don't want. Fixes SR-4325.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
Slava, mind reviewing this for possible inclusion in the 3.1 branch?

**Comment by jckarter** [comment]
Failures are in LLDB; should be unrelated.

**Comment by jckarter** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
LGTM. I think this was my bad, sorry about that.

**Pull request merged**
