### PR TITLE
IRGen: Allow stored_property keypaths on class constraint archetypes

### PR DESCRIPTION
**Pull request by aschwaighofer**
rdar://50271944

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
The failures look unrelated:
```
2019-06-06 09:19:04.240 xcodebuild[63419:6184456]  DVTDownloadable: Failed to get authorization with error Error Domain=DVTDownloadableErrors Code=3 "The authorization was denied since no user interaction was possible." UserInfo={AuthorizationErrorCode=-60007, NSLocalizedDescription=The authorization was denied since no user interaction was possible.}
xcodebuild: error: The authorization was denied since no user interaction was possible.
```

**Review by jckarter — APPROVED** [review]
Thanks Arnold!

**Comment by slavapestov** [comment]
Cool! Can you test a generic superclass too? <T, U where T : GenericClass<U>>

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Pull request merged**
