### PR TITLE
[ConstraintSolver] Fix `shrink` to use correct primary expression as a candidate

### PR DESCRIPTION
**Pull request by xedin**
When trying to identify candidates for shrinking we are missing the case
when apply expression is a source of the assignment operator, which leads
to incorrect results in some situations, because shrink is going to miss
some required contextual information about assignment.

Resolves: rdar://problem/33190087

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by slavapestov** [comment]
Test case?

**Review by DougGregor — APPROVED** [review]
The change looks safe. As I understand it, the removal of `ReturnAllDiscovered` resolves the perf. issue and the `isSrcOfPrimaryAssignment` is a more narrow fix for the previously-fixed source compatibility issue.

**Comment by xedin** [comment]
@slavapestov The test-case for this is already included, it's just a different way to fix the original problem...

**Comment by rudkx** [comment]
@xedin Is it possible to reduce the performance regression to something reasonable that we can add to the test suite? IIRC the case here is a new operator with many concrete overloads and a long chain of uses of the operator. That should be possible to add as a test case.

You could use the new solver time threshold option that I added to make it an error if it takes too long to compile. Just pick a "too long" value that will still pass with a debug ASAN-enabled build.

**Review by rudkx — APPROVED** [review]
LGTM!

**Comment by xedin** [comment]
@rudkx I'll try to do that!

**Comment by xedin** [comment]
Compatibility suite failed with the same `UPass` as all of its previous builds, which is unrelated to this patch.

**Pull request merged**
