### PR TITLE
[test] Add Range Overlaps Benchmark

### PR DESCRIPTION
**Pull request by PatrickPijnappel**
Separate PR for benchmark from #23293, to merge first so that PR can compare its performance to master. Let me know if there is a better way to achieve this. I've run the benchmark locally, would just like the CI to verify.

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please benchmark

**Comment by airspeedswift** [comment]
@swift-ci please smoke test

**Comment by airspeedswift** [comment]
Hi @PatrickPijnappel – can you tweak the number of iterations a little to keep the benchmark runs performant?

**Comment by PatrickPijnappel** [comment]
@airspeedswift Thanks! Updated. Also split up the set up to fix the other warnings

**Comment by PatrickPijnappel** [comment]
@swift-ci Please benchmark

**Comment by PatrickPijnappel** [comment]
@swift-ci Please benchmark

**Comment by PatrickPijnappel** [comment]
@swift-ci Please smoke test

**Pull request merged**
