### PR TITLE
[stdlib] GYBify Codable.swift [NFC]

### PR DESCRIPTION
**Pull request by natecook1000**
This converts `Codable.swift` to the `.gyb` format, removing replicated symbols using code generation. It also reindents and rewraps the code to match the rest of the standard library. This reformat is needed as preparation for future work.

### CODE REVIEW

**Comment by natecook1000** [comment]
@swift-ci Please test

**Comment by natecook1000** [comment]
@swift-ci Please test macOS platform

**Comment by shahmishal** [comment]
@swift-ci Please test macOS platform

**Comment by natecook1000** [comment]
@swift-ci Please smoke test

**Comment by airspeedswift** [comment]
OK but 😢. Is there no way to do some of this generically instead?

**Comment by natecook1000** [comment]
Maybe some of it? Most of the repetition seems inherent in the design.

**Comment by natecook1000** [comment]
@swift-ci Please smoke test and merge

**Pull request merged**
