### PR TITLE
[QoI] make several improvements to the unused expression diagnostics,…

### PR DESCRIPTION
**Pull request by tkremenek**
Pulls in 3549ec540408d760c255a526b1cff85644cb96d5 from `master`.

### CODE REVIEW

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by tkremenek** [comment]
Some test failures:

~~~
swift/validation-test/Sema/OverridesAndOverloads.swift:125:19: error: unexpected warning produced: expression of type 'C1' is unused
  Derived().foo() as C1
                  ^
...
~~~

@lattner Is there another commit I need to pull in?

**Comment by gribozavr** [comment]
@tkremenek Yes, 05397e3fb5e86df1d17f3a8638f1fba93265e4f9.

**Comment by tkremenek** [comment]
@swift-ci test

**Pull request merged**
