### PR TITLE
[Concurrency] Deprecate `AnyActor`.

### PR DESCRIPTION
**Pull request by hborla**
This marker protocol isn't useful for abstracting over actors and distributed actors because it doesn't have any runtime requirements, so there's no way to switch to the given actor. Instead, you should use `isolated (any Actor)?` parameters, and the compiler will compute a local actor value from a distributed actor using `DistributedActor.asLocalActor`.

Also, obsolete a few deprecated typealiases to `Sendable` in Swift 6.

### CODE REVIEW

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by hborla** [comment]
@swift-ci please smoke test

**Review by ktoso — APPROVED** [review]
I guess this is probably okey. I’m not sure I hate AnyActor enough to kill it but I guess the proliferation of non language evolution marker protocols has been quite messy… and one has to as? Cast them anyway.

it’s okey to pass as an any Actor only when you have a local one so this isn’t equivalent to passing AnyActor. Or even there isn’t an equivalent to AnyActor & MyProtocol now, but I guess one cannot do anything with the “actorness” anyway… 

it’s definitely true that we’ve not seen APIs which needed the AnyActor in practice yet.

**Comment by hborla** [comment]
@swift-ci please smoke test

**Pull request merged**
