### PR TITLE
Fix resilient build

### PR DESCRIPTION
**Pull request by slavapestov**
Not quite ready for checkin.
rdar://problem/28409189

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by swiftix** [comment]
@slavapestov Builds of benchmarks are broken with this PR due to linking problems.

```
build/swift-macosx-x86_64/benchmark/bin/Benchmark_O

Undefined symbols for architecture x86_64:
  "type metadata accessor for Swift._NativeDictionaryStorageOwner", referenced from:
      DictTest3.run_Dictionary3OfObjects (Swift.Int) -> () in DictTest3.o
      type metadata accessor for Swift._NativeDictionaryStorageOwner<DictTest3.Box<Swift.String>, DictTest3.Box<Swift.Int>> in DictTest3.o
  "type metadata accessor for Swift.DictionaryIteratorRepresentation", referenced from:
      DictTest3.run_Dictionary3OfObjects (Swift.Int) -> () in DictTest3.o
      type metadata accessor for Swift.DictionaryIteratorRepresentation<DictTest3.Box<Swift.String>, DictTest3.Box<Swift.Int>> in DictTest3.o
ld: symbol(s) not found for architecture x86_64

```

**Comment by slavapestov** [comment]
I'll take a look, thanks.

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swiftix The patches themselves need some cleanup, but this should now work well enough for preliminary testing. Let me know how it goes!

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test clean macOS

**Comment by slavapestov** [comment]
@swift-ci Please retest macOS

**Comment by slavapestov** [comment]
@swift-ci Please clean test macOS

**Comment by swiftix** [comment]
@slavapestov Great job! I can build & test now.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please clean smoke test macOS

**Comment by slavapestov** [comment]
@swift-ci Please smoke clean test macOS

**Comment by slavapestov** [comment]
@swift-ci Please clean test macOS

**Comment by jrose-apple** [comment]
I'm seeing the test fail:

```
[ RUN      ] ResilientProtocol.DynamicCastToResilientProtocol
stderr>>> CRASHED: SIGSEGV
the test crashed unexpectedly
[     FAIL ] ResilientProtocol.DynamicCastToResilientProtocol
```

**Comment by jrose-apple** [comment]
(in a non-resilient build, to be clear)

**Pull request merged**
