### PR TITLE
🍒[5.7][Distributed] onReturn ad-hoc req must not allow mutating witness

### PR DESCRIPTION
**Pull request by ktoso**
**Description:** Some adhoc requirements were missing the requirement checking for `mutating`. Without this fix errors appear in synthesized code, confusing developers about what they did wrong.
**Risk:** Low.
**Review by:** @xedin 
**Testing:** PR testing
**Original PR:** https://github.com/apple/swift/pull/59162
**Radar:** rdar://94127604
**Issue:** https://github.com/apple/swift/issues/59159

### CODE REVIEW

**Comment by ktoso** [comment]
First merge: https://github.com/apple/swift/pull/58683

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]

**Comment by ktoso** [comment]
@swift-ci please test and merge

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
@swift-ci please test and merge

**Pull request merged**
