### PR TITLE
More ASTScope cleanups

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Review by davidungar — APPROVED** [review]
All this code was there originally to help me debug these tough bugs that happened when the AST changed out from under ASTScopes.￼￼

I didn't quite remember this code when we spoke about it earlier today. 

I don't mind deleting it, but it would sure be great if we could add a flag somewhere that would prevent the creation of any new explicit DECLs after the first ASTScope lookup. Is there any possibility of that?￼￼

**Comment by slavapestov** [comment]
I’ll think about that along with the other assertions I promised you I would add.

**Comment by davidungar** [comment]
> I’ll think about that along with the other assertions I promised you I would add.

Thanks. It you figure out a good way do it, it would be so cool to just replace the other assertions. No need to add most of them if we can do that.

**Pull request merged**
