### PR TITLE
Update Changelog to include SE-0080

### PR DESCRIPTION
**Pull request by ultramiraculous**
Resolves [SR-1491](https://bugs.swift.org/browse/SR-1491).

### CODE REVIEW

**Comment by CodaFi** [comment]
I don't think we ever PR'd this into 3.1-branch if you want to cherry-pick it over.

**Comment by ultramiraculous** [comment]
Ah, weird. I must have mis-used GitHub's UI b/c I swear it looked like it was picked already. I'll make another PR.

**Comment by CodaFi** [comment]
The first 3/4ths got picked up, but I don't remember seeing the last one I reviewed.

**Comment by ultramiraculous** [comment]
I just checked out `swift-3.1-branch` and it looks like the merge commit for that last PR  (883ca16ab92579b4595b2a714c4faaf2d867bace) is part of it.

**Comment by ultramiraculous** [comment]
Based on @jtbandes [over here](https://bugs.swift.org/browse/SR-1491). It seems like there was a merge from master into 3.1?

**Comment by jtbandes** [comment]
(copied from apple/swift-evolution#586)
Just tested the 1/17 snapshot from https://swift.org/download/#snapshots; it looks like Float->Int is still not there, although the changes appear in https://github.com/apple/swift/commits/swift-3.1-branch/stdlib/public/core/FloatingPointTypes.swift.gyb. Perhaps the next snapshot will have it.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@ultramiraculous Since the change is in 3.1, do you mind preparing a PR for swift-3.1-branch updating the CHANGELOG there as well?

**Comment by jtbandes** [comment]
@slavapestov Can you confirm whether this will actually be in 3.1? As mentioned in the comment I noticed the nightly didn't actually have the float->int versions yet.

**Comment by slavapestov** [comment]
It looks like Linux pull request testing is broken right now because of an unrelated lldb issue. I'll merge this when things are cleared up.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
Hi @ultramiraculous, I looked and all your changes are in swift-3.1-branch (except this CHANGELOG update of course). Mind creating a new PR to cherry-pick it over?

**Pull request merged**
