### PR TITLE
[cxx-interop] test, run another test on windows

### PR DESCRIPTION
**Pull request by hyp**

### CODE REVIEW

**Comment by hyp** [comment]
@swift-ci please test and merge

**Comment by hyp** [comment]
@swift-ci please test windows platform

**Comment by hyp** [comment]
@swift-ci please test windows platform

**Comment by hyp** [comment]
@swift-ci please test windows platform

**Comment by hyp** [comment]
@swift-ci please test windows platform

**Review by egorzhdan — APPROVED** [review]

**Comment by hyp** [comment]
@swift-ci please test windows platform

**Pull request merged**
