### PR TITLE
Compiler crashers: Rename old crash cases to match the current naming scheme.

### PR DESCRIPTION
**Pull request by practicalswift**
Will allow for easy import of crash cases from swift-compiler-crashes.

### CODE REVIEW

**Comment by gribozavr** [comment]
Verified tests passing on Ubuntu 14.04.

**Comment by jtbandes** [comment]
This probably breaks #253 and #272 which were moving some of these files too. I'll need to rebase. Is there any chance those will be able to merge before any more breaking changes like this go through?

**Comment by gribozavr** [comment]
@jtbandes Sorry!

**Comment by jtbandes** [comment]
Just checked and #272 is fine. I'm working on re-testing #253

**Pull request merged**
