### PR TITLE
[CodeCompletion] Add a regression test for SR-2560

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
сс @rintaro 

[SR-2560](https://bugs.swift.org/browse/SR-2560) seems to have been unknowingly fixed.

### CODE REVIEW

**Review by rintaro — APPROVED** [review]
Thank you!

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by AnthonyLatsis** [comment]
Although the way it prints doesn't perfectly match the requirement's generic signature style. Do you think we should always make sure to perfectly match the style of the base declaration?

**Comment by rintaro** [comment]
I don't think they should perfectly match, but we internally have some issues which complains that.
Ideally, I think we should keep constraints position (generic params or where clause).
So in this case, 
```swift
    foo<S: Sequence>(x: S) where S.Element == Int {
        <#code#>
    }
```
is preferable because the original `: Sequence` constraint is in the generic param clause.

**Comment by AnthonyLatsis** [comment]
Yes, agreed. 

I am going to work on [SR-9560](https://bugs.swift.org/browse/SR-9560) soon; taking advantage of the moment, could you hint me where to look at for how ↵(enter) actions on placeholders are implemented?

**Comment by rintaro** [comment]
@AnthonyLatsis Commented in SR-9560 👍

**Pull request merged**
