### PR TITLE
[Preset] Add corelibs foundation presets (SR-9950)

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Review by millenomi — COMMENTED** [review]
Can we mixin eg the relevant parts of buildbot_incremental so that we build like the apple/swift repository does?

**Comment by shahmishal** [comment]
@swift-ci smoke test

**Comment by millenomi** [comment]
Looks good.

**Review by millenomi — APPROVED** [review]

**Comment by shahmishal** [comment]
@swift-ci smoke test Linux

**Pull request merged**
