### PR TITLE
Remove numpy dependency

### PR DESCRIPTION
**Pull request by practicalswift**

### CODE REVIEW

**Comment by modocache** [comment]
Wow, from what I understand `numpy` is not a light dependency. This change seems well worth the two extra lines. Thanks, @practicalswift!

**Comment by practicalswift** [comment]
@modocache Yes, `numpy` is quite heavy - it is roughly 265 000 lines of code :smile:

**Comment by mxcl** [comment]
This is the kind of unrecognized but important contribution that helps big projects stay lean 👏

**Comment by jrose-apple** [comment]
@nadavrot, is anyone even using this script? It hasn't been updated in a long time, but I can't tell if that's because it's unused or because it's simple and working as is.

**Comment by nadavrot** [comment]
I think that Andy and Arnold are using this script (based on the output of their reports).

**Comment by jrose-apple** [comment]
Okay. Any objections, @atrick, @aschwaighofer?

(I assume this is almost automatically a desireable change but the script doesn't exactly have an owner right now.)

**Comment by atrick** [comment]
I've never used numpy!

**Pull request merged**
