### PR TITLE
[ConstraintSystem] Ignore patterns in linked expression analysis

### PR DESCRIPTION
**Pull request by rintaro**
Fixes an assertion hit in "pattern in binary expression" case.

rdar://problem/41071587

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test OS X platform

**Review by xedin — APPROVED** [review]
Makes sense, thank you @rintaro!

**Comment by xedin** [comment]
Let's run source compatibility just in case too.

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Pull request merged**
