### PR TITLE
Revert "[Driver] Derive '-external-plugin-path'"

### PR DESCRIPTION
**Pull request by rintaro**
rdar://109851266

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please test

**Review by artemcm — APPROVED** [review]

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test Linux

**Comment by rintaro** [comment]
@swift-ci Please smoke test Linux

**Review by bnbarham — APPROVED** [review]

**Pull request merged**
