### PR TITLE
[CMake] Update host platform check for macro support

### PR DESCRIPTION
**Pull request by rintaro**
Followup to #68082 
"Support Macros in Linux" patches was inconsistent with checking platforms. Some only checked `LINUX` but some matches `LINUX|ANDROID|OPENBSD|FREEBSD`. Although I don't have tested other platoforms than Linux at all, there's no reason to limit it to Linux. So use the consistent check to match `LINUX|ANDROID|OPENBSD|FREEBSD`

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please Build Toolchain Linux

**Review by bnbarham — APPROVED** [review]
There's also the one or two `if(darwin) else` cases that we should fix up too

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please Build Toolchain Linux

**Comment by finagolfin** [comment]
Should macros work on linux now? I tried downloading [this toolchain from the CI](https://download.swift.org/tmp/pull-request/68224/562/ubuntu2004/PR-ubuntu2004.tar.gz) and it still fails on Doug's macro examples repo:
```
> swift build
...
/home/foo/swift-macro-examples/MacroExamplesPlugin/ObservableMacro.swift:110:28: error: cannot find type 'ConformanceMacro' in scope extension ObservableMacro: ConformanceMacro {
```

**Pull request merged**
