### PR TITLE
[DiagnosticsQoI] Sema: Use 'underlying' instead of 'concrete' in opaque result type diagnostic

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
For the sake of consistency. See [comment](https://github.com/apple/swift/pull/62924#discussion_r1084565046).

### CODE REVIEW

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Review by LucianoPAlmeida — APPROVED** [review]
Looks good to me but I'd let @xedin have the final word

**Review by xedin — APPROVED** [review]
`underlying` indeed fits better here!

**Comment by xedin** [comment]
@swift-ci please smoke test Windows platform

**Pull request merged**
