### PR TITLE
Update -sanitize=fuzzer option to take into account new libFuzzer location

### PR DESCRIPTION
**Pull request by cheshire**

### CODE REVIEW

**Comment by cheshire** [comment]
@swift-ci please smoke test and merge

**Comment by cheshire** [comment]
@swift-ci please smoke test and merge

**Comment by cheshire** [comment]
@shahmishal Jenkins died with:

```
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1903)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1622)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:71)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:348)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:545)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
```

**Comment by cheshire** [comment]
@swift-ci please smoke test and merge

**Comment by cheshire** [comment]
Linux ToT should hopefully build now.

**Comment by cheshire** [comment]
@swift-ci please smoke test and merge

**Comment by shahmishal** [comment]
@Cheshire Do you have a link to the build where you saw the Jenkins error?

**Comment by cheshire** [comment]
@shahmishal nope. Seems to be working now.

**Pull request merged**
