### PR TITLE
Fix a couple cases of ArrayRef capturing compiler temps.

### PR DESCRIPTION
**Pull request by rudkx**
Use a SmallVector for scratch space to use to build the ArrayRefs
instead.

rdar://problem/28644568

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please smoke test and merge.

**Comment by DougGregor** [comment]
These are painfully subtle, but LGTM as a fix.

**Comment by rudkx** [comment]
@swift-ci Please clean smoke test and merge.

**Comment by jrose-apple** [comment]
I'll go fix this in LLVM.

```c++
/*implicit*/ ArrayRef(T &&Temporary) = delete;
```

**Comment by rudkx** [comment]
@jrose-apple That would be awesome!

**Pull request merged**
