### PR TITLE
[benchmark] fixes index(of:) deprecation warnings in ArgParse

### PR DESCRIPTION
**Pull request by nordicio**
Fixes two deprecation warnings in ArgParse.swift in benchmark when building Swift from scratch on macOS 10.14.1 with the toolchain from Xcode 10.1 (10B61).

Running
`$ ninja swift-benchmark-macosx-x86_64`

Produced the following output:
```
<path>/swift-source/swift/benchmark/utils/ArgParse.swift:69:38: warning: 'index(of:)' is deprecated: renamed to 'firstIndex(of:)'
      let ss = r[r.startIndex ..< (r.index(of:"/") ?? r.endIndex)]
                                     ^
<path>/swift-source/swift/benchmark/utils/ArgParse.swift:69:38: note: use 'firstIndex(of:)' instead
      let ss = r[r.startIndex ..< (r.index(of:"/") ?? r.endIndex)]
                                     ^~~~~
                                     firstIndex
<path>/swift-source/swift/benchmark/utils/ArgParse.swift:69:38: warning: 'index(of:)' is deprecated: renamed to 'firstIndex(of:)'
      let ss = r[r.startIndex ..< (r.index(of:"/") ?? r.endIndex)]
                                     ^
<path>/swift-source/swift/benchmark/utils/ArgParse.swift:69:38: note: use 'firstIndex(of:)' instead
      let ss = r[r.startIndex ..< (r.index(of:"/") ?? r.endIndex)]
                                     ^~~~~
                                     firstIndex
<path>/swift-source/swift/benchmark/utils/ArgParse.swift:49:38: warning: 'index(of:)' is deprecated: renamed to 'firstIndex(of:)'
      let s = type.index(after: type.index(of:"<")!)
                                     ^
<path>/swift-source/swift/benchmark/utils/ArgParse.swift:49:38: note: use 'firstIndex(of:)' instead
      let s = type.index(after: type.index(of:"<")!)
                                     ^~~~~
                                     firstIndex
```

This PR just applies the suggested fixes.

### CODE REVIEW

**Comment by nordicio** [comment]
@swift-ci Please smoke test

**Comment by nordicio** [comment]
Whoops, should’ve tagged responsible from CODE_OWNERS (first PR 😊) @eeckstein

**Comment by eeckstein** [comment]
@swift-ci benchmark

**Review by eeckstein — APPROVED** [review]
lgtm!

**Comment by gottesmm** [comment]
@swift-ci Please smoke test

**Pull request merged**
