### PR TITLE
[Sema] Don’t allow unresolved type variables if `LeaveBraceStmtBodyUnchecked` is `true`

### PR DESCRIPTION
**Pull request by ahoppen**
[Sema] Don’t allow unresolved type variables if `LeaveBraceStmtBodyUnchecked` is `true`

According to Pavel, we want to eliminate allowing unresolved variables as much as possible. Removing this flag doesn’t break any test cases (at least not in a meaningful way) and fixes a crasher, so it seems reasonable to remove it.

When doing operator completion, we re-type-check the sequence expression. If we have an unresolve type already applied to `ParsedExpr`, which is the last element of the sequence, the type checker crashes in `validation-test/IDE/crashers_2_fixed/0008-must-conform-to-literal-protocol.swift`, because there are still inactive constraints in the constraint system when it finishes solving.

Previously, we would ignore because we allowed free type variables, which we no longer do since the last commit.

Fixes rdar://76686564

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Review by xedin — COMMENTED** [review]
Is a solution with holes applied to the AST because this particular completion kind is still using old logic that relies on type-checked AST? If so, I think this fix is okay for now since in the future we’ll just stop doing AST transforms as switch to use `typeCheckForCodeCompletion`.

**Comment by ahoppen** [comment]
Yeah, AFAICT conforming method lists hasn’t been ported to `typeCheckForCompletion` yet(https://github.com/apple/swift/blob/main/lib/IDE/ConformingMethodList.cpp#L71).

**Comment by ahoppen** [comment]
@xedin Thanks for your feedback. As discussed offline, removing the `AllowUnresolvedTypeVariables` flag seems to fix the crash and not cause any other regressions, so it seems like a reasonable fix to me (especially since you would like to eliminate allowing unresolved type variables anyway).

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by xedin — APPROVED** [review]
Makes sense to me!

**Comment by ahoppen** [comment]
@swift-ci Please test macOS

**Comment by rintaro** [comment]
We should remove another usage of `TypeCheckExprFlags::AllowUnresolvedTypeVariables` in `visitReturnStmt`.  In fact the reproducer in rdar://76686564 is not fixed without removing it (probably because it's in an implicit `ReturnStmt`).

**Comment by xedin** [comment]
@ahoppen @rintaro It looks like there are just a couple of usages of `TypeCheckExprFlags::AllowUnresolvedTypeVariables` in lib/Sema, should we try to remove all of them and see what in code completion breaks?

**Pull request merged**
