### PR TITLE
AST: Fix ExistentialLayout::isObjC() handling of marker protocols 

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes rdar://problem/119541554.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Review by xedin — APPROVED** [review]

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by xedin** [comment]
Could you please cherry-pick to 5.10 as well?

**Comment by slavapestov** [comment]
Yep! https://github.com/apple/swift/pull/70512

**Comment by xedin** [comment]
Thank you!

**Pull request merged**
