### PR TITLE
(WIP) Type metadata access by mangled name

### PR DESCRIPTION
**Pull request by jckarter**
Experiment with accessing concrete types with complex instantiation sequences by mangling their names and interpreting with `getTypeByMangledName` instead of with open-coded accessors. In my experiments this saves about 128KB of code size in the dylibs.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please benchmark

**Comment by slavapestov** [comment]
Cute.

**Comment by jckarter** [comment]
@swift-ci Please benchmark

**Comment by rjmccall** [comment]
Can we reasonably combine this with the embedded type-descriptor references that we do in the remote-mirrors metadata?  It would avoid some expensive symbol-table lookups and fix any potential problems we might have with local types.

**Comment by rjmccall** [comment]
In particular, if we combined direct type-descriptor references with a more efficient type demangler that didn't construct an intermediate demangling tree, it would probably cut the runtime overhead of this to the point of possibly vanishing in the i-cache improvements (assuming we still have one level of caching in the runtime).

**Comment by jckarter** [comment]
@rjmccall Yeah, this already uses the same format as the remote mirror type references, including support for embedded pointers in the mangling to refer to private or local types.

**Comment by jckarter** [comment]
Closing this in favor of a new implementation coming shortly.

**Pull request closed without merging**
