### PR TITLE
🛑 [stdlib] Turn StrideTo into a slice and conditionally conform to Collection

### PR DESCRIPTION
**Pull request by moiseev**
This changes StrideTo.SubSequence from AnySequence to StrideTo, so it is by definition is not source compatible. How bad is the breakage... let's see.

### CODE REVIEW

**Comment by moiseev** [comment]
@swift-ci Please smoke test

**Comment by moiseev** [comment]
@swift-ci Please Test Source Compatibility

**Comment by moiseev** [comment]
For the record: all the compatibility suite failures are "failed to clone".

**Comment by CodaFi** [comment]
Closing out this old testing PR.

**Pull request closed without merging**
