### PR TITLE
[Sema] Restore 5.10 implicit self behavior prior to Swift 6 mode

### PR DESCRIPTION
**Pull request by hamishknight**
Unfortunately we've encountered another source breaking case here:

```swift
class C {
  func method() {}

  func foo() {
    Task { [weak self] in
      Task {
        method()
      }
    }
  }
}
```

In 5.10 we'd only do the unqualified lookup for `self` when directly in a `weak self` closure, but with the implicit self rework (#70575), we'd start using the `weak self` here, leading to a type-checker error.

At this point, adding more edge cases to the existing logic is going to make things much more complicated. Instead, reinstate the 5.10 implicit self lookup behavior and diagnostic logic, switching over to the new logic only under Swift 6 mode.

rdar://129475277

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
FYI @calda, unfortunately I think we have to keep the old behavior prior to Swift 6 mode

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Review by calda — APPROVED** [review]
Makes sense, thanks for the fix

**Comment by hamishknight** [comment]
@swift-ci please test

**Pull request merged**
