### PR TITLE
[Driver] Default SDKROOT to / on FreeBSD.

### PR DESCRIPTION
**Pull request by dcci**
As suggested by Jordan Rose on the mailing lists.

Thanks!
## 

Davide

### CODE REVIEW

**Comment by gribozavr** [comment]
Since this is a driver change, it should be possible to write a direct test... but leaving it to @jrose-apple.

**Comment by jrose-apple** [comment]
No, indeed, please add a test case along the lines of test/Driver/sdk.swift. You should be able to use env to make sure SDKROOT is unset.

I'd say we should do this for all non-Darwin platforms. I don't think anyone else commonly has multiple copies of headers on their system, and with Xcode you always use 'xcrun' anyway (which sets SDKROOT). If someone *is* cross-compiling they'll notice something wrong pretty quick.

**Comment by dcci** [comment]
No problem, I'll try to write a test right away. Thanks for the quick review!
BTW, what's the recommended way to pass a freebsd triple to the driver?

**Comment by jrose-apple** [comment]
Looks like Clang uses `-target x86_64-unknown-freebsd`.

**Comment by dcci** [comment]
OK, thanks. there's too much noise currently running the test suite on FreeBSD, so to make sure, I'll spawn a Linux VM and try to run there to see if the test passes.

Thanks,

--
Davide

**Comment by tkremenek** [comment]
@swift-ci please test

**Comment by tkremenek** [comment]
@dcci were you able to write a test case?

**Comment by dcci** [comment]
Haven't yet, but will take a look at this in the next day or two. Sorry for the delay on this :|

**Comment by tkremenek** [comment]
@swift-ci Please test

**Comment by dcci** [comment]
Sorry for slacking off on this one. I plan to fix it today or tomorrow.

**Comment by dcci** [comment]
This one is superseded by https://github.com/apple/swift/pull/1500 
Closing this one.

**Pull request closed without merging**
