### PR TITLE
fixed urls for cloning repositories in README.md

### PR DESCRIPTION
**Pull request by AndreasPrang**

### CODE REVIEW

**Comment by qorcjftns** [comment]
`git@github...` works too, isnt it?

**Comment by asumaran** [comment]
@qorcjftns Yes it does

**Comment by AndreasPrang** [comment]
for me it was not working:

$ git clone git@github.com/apple/swift-lldb.git lldb
fatal: repository 'git@github.com/apple/swift-lldb.git' does not exist
$ git clone https://github.com/apple/swift-lldb.git lldb
Cloning into 'lldb'...
remote: Counting objects: 150034, done.
remote: Total 150034 (delta 0), reused 0 (delta 0), pack-reused 150034
Receiving objects: 100% (150034/150034), 37.41 MiB | 845.00 KiB/s, done.
Resolving deltas: 100% (115039/115039), done.
Checking connectivity... done.

**Comment by Mitame** [comment]
This should be merged... `git@github.com...` requires that you have ssh support and that you have an ssh key linked on github. `https://github.com...` doesn't require any of this and just requires that you have access to github.com. It also means those without a github account can clone the repo. THis is mostly just an ease of use thing, but it would be nice for those of us that copy and paste of have encrypted ssh keys.

**Comment by nico** [comment]
+1, the current URLs didn't work for me either, the URLs in this pull request do.

**Comment by bbashy** [comment]
@AndreasPrang You used the wrong SSH URL by the looks of it?

```
// yours
git clone git@github.com/apple/swift-lldb.git lldb

// readme's
git clone git@github.com:apple/swift-lldb.git lldb
```

**Comment by yurikoles** [comment]
Those urls are from his previous PR #80

**Comment by krememek** [comment]
I have taken the suggestion of this pull request and committed a different answer in 15428fb81b489187335bcf18aace5d0008f3fc7c which provides instructions for both people using https or SSH.

**Pull request closed without merging**
