### PR TITLE
Fix emitting bodies of local functions declared in unreachable code into SIL

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: SR-15507

Previously, `StmtEmitter::visitBraceStmt` would stop looking any further as soon as it reached an unreachable point in the code. As a result, bodies of local functions that were declared in unreachable code would not be emitted into SIL, even when the local function was used in reachable code. This resulted in undefined symbols or the assertion failure described in SR-15507.

Now, it will continue scanning unreachable code, and will still visit local functions declared there, so that their bodies make it into SIL; of course, making sure that we don't visit nodes that are _not_ interesting when they are in unreachable code, and that we still emit a diagnostic about unreachability only once.

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
@swift-ci please test

**Comment by WowbaggersLiquidLunch** [comment]
@swift-ci please smoke test

**Comment by WowbaggersLiquidLunch** [comment]
@swift-ci please smoke test

**Comment by cbjeukendrup** [comment]
@jckarter Hi! I saw that you are the code owner for SILGen. Could you please take a look at this PR?

**Comment by xwu** [comment]
Seems likely, given the timing, that your paths just crossed. In my experience, the code owners tend to be pretty responsive, but don't be shy about being proactive when you've got a fix coming down the pipeline to get on their radar even as you're drafting it.

**Pull request closed without merging**
