### PR TITLE
test: Remove duplicate test for -static-executable

### PR DESCRIPTION
**Pull request by spevans**
- test/Driver/static-executable-linux.swift is duplicated by
  test/Driver/static-executable.swift

- Additionally, test/Driver/static-executable-linux.swift uses 'FILE'
  instead of 'ELF-NOT' to detect if the executable is statically linked
  and this breaks on Centos7.

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
cc @brentdax

**Comment by spevans** [comment]
@swift-ci test

**Comment by brentdax** [comment]
I'm going to force-merge this early—it's passed on Linux and should have even less effect on macOS, and it should clear at least one bot.

**Pull request merged**
