### PR TITLE
Move non-transparent OME to just before Mem2Reg

### PR DESCRIPTION
**Pull request by meg-gupta**
By default move Ownership Model Elimination to use before Mem2Reg.

### CODE REVIEW

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test Linux Platform

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci benchmark

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by meg-gupta** [comment]
@swift-ci test

**Review by atrick — APPROVED** [review]
Thanks for fixing all the blocking issues. It does seem like it's better to make this change sooner rather than later.

**Comment by meg-gupta** [comment]
@swift-ci please test Linux platform

**Comment by meg-gupta** [comment]
@swift-ci test

**Pull request merged**
