### PR TITLE
Support new changes from swift/rebranch on llvm-project repo 

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
https://github.com/apple/llvm-project/pull/2397
@swift-ci please test

**Comment by shahmishal** [comment]
apple/llvm-project#2397
@swift-ci build toolchain

**Comment by shahmishal** [comment]
apple/llvm-project#2397
@swift-ci please test

**Comment by shahmishal** [comment]
apple/llvm-project#2397
@swift-ci build toolchain

**Comment by shahmishal** [comment]
@swift-ci Please build toolchain

**Comment by shahmishal** [comment]
apple/llvm-project#2397
@swift-ci build toolchain

**Review by xymus — APPROVED** [review]
Looks good, thank you!

Note that this does not include the disabling of a test from this morning #35689 and will likely fail on `Interop/Cxx/value-witness-table/witness-layout-opts-irgen.swift` which is affecting main.

**Comment by shahmishal** [comment]
apple/llvm-project#2397
@swift-ci smoke test

**Pull request merged**
