### PR TITLE
Promote some stdlib/swift CMake flags into build-script settings

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

**Review by compnerd — APPROVED** [review]
This is fine, though I'm not a big fan of this.  I think that having the cmake options spelt out is better - it makes it easier for someone to know how to translate the ini file into a command line without having to dig through a ton of stuff.

**Comment by kubamracek** [comment]
@swift-ci please test macOS platform

**Pull request merged**
