### PR TITLE
Spelling test printasobjc

### PR DESCRIPTION
**Pull request by jsoref**
This fixes some misspellings in Swift test/printasobjc, it is split per https://github.com/apple/swift/pull/42421#issuecomment-1101092698

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci smoke test

**Comment by tshortli** [comment]
@swift-ci please smoke test

**Comment by jsoref** [comment]
@tshortli: how'd this go?

**Review by tshortli — APPROVED** [review]

**Comment by tshortli** [comment]
> @tshortli: how'd this go?

Sorry for losing track of this; please rebase and I'll get it merged.

**Comment by tshortli** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
