### PR TITLE
[CodeCompletion][Sema] Multiple improvements to prepare for migration of PostfixExprParen to solver-based

### PR DESCRIPTION
**Pull request by ahoppen**
This is a collection of multiple changes, which I hope aren’t too controversial, that are needed to migrate PostfixExprParen to solver-based. It might make sense to look at the commits individually for review to see the scope of each change.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please SourceKit stress test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Review by xedin — APPROVED** [review]

**Comment by ahoppen** [comment]
Removed on change (Don't increase the score for holes at the code completion token) from this PR because it was causing stress tester failures. I’m looking at addressing it in a separate PR.

**Comment by ahoppen** [comment]
@swift-ci Please SourceKit stress test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please smoke test macOS

**Review by rintaro — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Pull request merged**
