### PR TITLE
[5.1] [Typechecker] Allow bridging of Unmanaged to Objective-C for throwing functions

### PR DESCRIPTION
**Pull request by theblixguy**
Cherry-pick of #24135

---

Previously, we would emit an error diagnostic if a throwing `@objc` function returned `Unmanaged<T>`. This is now allowed when `T` is representable in Objective-C.

For example:

```swift
class Foo {}

@objc protocol Bar {
  func throwingMethod1() throws -> Unmanaged<CFArray> // ok
  func throwingMethod2() throws -> Unmanaged<Foo> // error
}
```
  

Resolves [SR-9035](https://bugs.swift.org/browse/SR-9035).

### CODE REVIEW

**Comment by theblixguy** [comment]
cc @jrose-apple

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Review by AnnaZaks — APPROVED** [review]

**Comment by jrose-apple** [comment]
:-( Looks like the IR looked different in 5.1. You'll have to update the test.

**Comment by theblixguy** [comment]
Ah, I didn't expect the IR to be slightly different. No worries, I have updated the test. Could you invoke the CI again? Thanks!

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
Thanks, @theblixguy!

**Pull request merged**
