### PR TITLE
Stack buffer that can be used to allocate SIL instructions.

### PR DESCRIPTION
**Pull request by zoecarver**
Adds a stack allocator for allocating instructions. If there's room in the 8 MB stack buffer, small instructions can be allocated on the stack which is slightly faster.

This is particularly fast in Onone when most of the instructions can be fit in the stack buffer.

When compiling the stdlib it was about 6% faster on my machine. When compiling the Onone benchmarks it was about 13% faster. It's possible that's just noise, though. So, I'll run the compiler benchmarks to see this is actually beneficial at all.

### CODE REVIEW

**Comment by zoecarver** [comment]
@swift-ci please smoke test compiler performance

**Comment by gottesmm** [comment]
This is basically a bump ptr allocator. BumpPtrAllocation should be basically as fast as this. There is a way I think to change SILInstruction's back to using BumpPtrAllocation instead of malloc/free.

We changed b/c we found that BumpPtrAllocation like this can result in very large memory usage.

**Comment by zoecarver** [comment]
@gottesmm this should use way less memory. We can always deallocate instructions (whereas with a bump allocator, we can't, IIUC). 

Let's see what the benchmarks say. If there isn't a significant improvement, or if there's high memory usage, or there's some other reason not to use this, I'll close this PR.

**Comment by zoecarver** [comment]
@swift-ci please smoke test compiler performance

**Comment by gottesmm** [comment]
@zoecarver you can deallocate with a recycling bump ptr allocator that llvm has.

**Comment by zoecarver** [comment]
@gottesmm OK good to know. Why did it use more memory then? Just tracking where pointers where in the buffer?

**Comment by zoecarver** [comment]
@swift-ci please smoke test compiler performance

**Comment by zoecarver** [comment]
I keep getting the same (broken) bot. I'll wait a bit and try it again.

**Comment by zoecarver** [comment]
@swift-ci please smoke test compiler performance

**Comment by zoecarver** [comment]
@swift-ci please smoke test compiler performance

**Comment by zoecarver** [comment]
@swift-ci please smoke test compiler performance

**Pull request closed without merging**
