### PR TITLE
SourceKit: Account for existing braces when expanding closure placeholders

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
[SR-9560](https://bugs.swift.org/browse/SR-9560)

cc @rintaro

### CODE REVIEW

**Comment by AnthonyLatsis** [comment]
@nkcsgexi Reminder

**Comment by AnthonyLatsis** [comment]
@benlangmuir It looks like Xi has been busy lately, so I am tagging you in case you find the time to take glance before Xi joins in.

**Comment by benlangmuir** [comment]
@swift-ci please smoke test

**Comment by benlangmuir** [comment]
@swift-ci please smoke test Linux

**Review by benlangmuir — APPROVED** [review]

**Comment by AnthonyLatsis** [comment]
Thanks a lot, Ben.

**Pull request merged**
