### PR TITLE
Revert "[CMake] Remove TARGET_LIBRARY option from add_swift_target_li…

### PR DESCRIPTION
**Pull request by xedin**
…brary"

This reverts commit a16c71cc86bb568d123de658cbf30a9112af8755.

### CODE REVIEW

**Comment by xedin** [comment]
@xiaobai We have hit some problem with this PR in the CI so I have to revert it to unblock everything.

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@xedin could you please provide some information about what problem you are seeing?  This passed the CI and is a cleanup that should have no effect, so could you please provide some information on what happened?

CC: @AnnaZaks

**Comment by xedin** [comment]
This is failing internal CI, I will try to figure out with @russbishop what exactly we can share in terms of details.

**Pull request closed without merging**
