### PR TITLE
[5.9.1] Enable macros for Windows in 5.9.1

### PR DESCRIPTION
**Pull request by bnbarham**
Squashed cherry-pick of #68334 and #68743.

### CODE REVIEW

**Comment by bnbarham** [comment]
https://github.com/apple/swift-syntax/pull/2248
https://github.com/apple/swift-driver/pull/1456
https://github.com/apple/llvm-project/pull/7540
https://github.com/apple/swift-installer-scripts/pull/247
https://github.com/apple/swift-corelibs-foundation/pull/4832

@swift-ci please test

**Comment by bnbarham** [comment]
https://github.com/apple/swift-syntax/pull/2248
https://github.com/apple/swift-driver/pull/1456
https://github.com/apple/llvm-project/pull/7540
https://github.com/apple/swift-installer-scripts/pull/247
https://github.com/apple/swift-corelibs-foundation/pull/4832

@swift-ci please build toolchain windows platform

**Comment by bnbarham** [comment]
Somehow missed https://github.com/apple/swift/commit/2227f8e90291b5e6aa10576c6a390413cddad625, though it's really not clear to me how that is the case.

**Comment by bnbarham** [comment]
https://github.com/apple/swift-syntax/pull/2248
https://github.com/apple/swift-driver/pull/1456
https://github.com/apple/llvm-project/pull/7540
https://github.com/apple/swift-installer-scripts/pull/247
https://github.com/apple/swift-corelibs-foundation/pull/4832

@swift-ci please build toolchain windows platform

**Comment by bnbarham** [comment]
https://github.com/apple/swift-syntax/pull/2248
https://github.com/apple/swift-driver/pull/1456
https://github.com/apple/llvm-project/pull/7540
https://github.com/apple/swift-installer-scripts/pull/247
https://github.com/apple/swift-corelibs-foundation/pull/4832

@swift-ci please test

**Review by DougGregor — APPROVED** [review]

**Comment by al45tair** [comment]
FWIW, this was missing a line somehow; it should have removed
```
config.substitutions.append( ('%swift-host-lib-dir', config.swift_host_lib_dir))
```
from `lit.cfg`.

Fixing here: https://github.com/apple/swift/pull/68988/commits/efbf21a0e0ded1e7257613d14890e50fc7565132

**Comment by bnbarham** [comment]
Ah, thanks. Beat me to it :). I assume I must have kept both when I was fixing a merge conflict, which I'm still very confused about. https://github.com/apple/swift/pull/68904 doesn't show the `%swift-plugin-dir` removal, but it definitely was (see https://github.com/apple/swift/pull/68904/commits/9dbdd5e14e70b440206717dc3c2e4191e18ebb4d)

**Pull request merged**
