### PR TITLE
[SourceKit] XML escape Swift declarations from Clang modules

### PR DESCRIPTION
**Pull request by johnfairh**
When producing the SourceKit XML doc comment field as part of docInfo or cursorInfo for an imported decl, the Swift declaration is not XML-escaped.  This causes problems for downstream tools trying to parse the XML.

Simple change here to do the escaping.

@nkcsgexi could you take a look please?

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Review by nkcsgexi — APPROVED** [review]
LGTM!

**Comment by nkcsgexi** [comment]
@swift-ci Please clean test Linux platform

**Comment by johnfairh** [comment]
thanks!

**Pull request merged**
