### PR TITLE
IRGen: Always use symbolic references in mangled names (on Mach-O platforms)

### PR DESCRIPTION
**Pull request by jckarter**
Wire up support in `swift-reflection-dump` to correctly handle pointer values and walk the binding table in Mach-O images to follow unresolved symbol references, so that we can safely unconditionally use symbolic references in runtime mangled names without regressing offline reflection support.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test Windows

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test Windows

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test Windows

**Comment by jrose-apple** [comment]
Expect any run-time perf changes from this? Better, worse, smaller code size?

**Comment by jckarter** [comment]
Code size is slightly smaller but not really notably so. Performance of demangling strings should be much better, and we’ll avoid warming up the type lookup cache and allocating a bunch of memory. I was going to experiment with using mangled names for all metadata accessed after this.

**Comment by jckarter** [comment]
To be on a fully equal footing with open-coded accessor functions, we'll also need a way to encode pointers to conformances used by the type directly in the mangled name too, but that would need a new symbolic reference form, so we'd have to deployment-target-gate it.

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test Windows

**Comment by jckarter** [comment]
@swift-ci Please test Windows

**Comment by jckarter** [comment]
@swift-ci Please clean test Windows

**Comment by jckarter** [comment]
@jrose-apple Aside from performance and code size, another benefit of this is that it should define away the issues we've been having with mangled names and static linking, since now mangled names will always contain real symbol references to the metadata objects they require to be instantiated at runtime.

**Pull request merged**
