### PR TITLE
Change ABI checker to sort expected changes before comparison

### PR DESCRIPTION
**Pull request by airspeedswift**
Hopefully this will get us out of the constant cycle of merge conflicts.

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please test

**Review by nkcsgexi — APPROVED** [review]

**Comment by airspeedswift** [comment]
My PR to avoid merge issues hit merge issues.

**Comment by airspeedswift** [comment]
@swift-ci please smoke test and merge

**Comment by milseman** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
