### PR TITLE
[cxx-interop] Emit IR for std::get in structured bindings declaration

### LINKED ISSUE #62448: [interop] Interop doesn't IRGen C++17 destructuring `get` calls in Swift module
**Description**
test.h
```
#pragma once

namespace std {

template<class X, class Y>
struct pear {
    //X x;
    //Y y;
    
    pear(X x, Y y) {}
    
    X getX() const {
        return 0;
    }
    Y getY() const {
        return 42;
    }
};

template<class T>
struct tuple_size {
    constexpr static const int value = 2;
};

template<int n, class T>
struct tuple_element {
};

template<class X, class Y>
struct tuple_element<0, pear<X, Y>> {
    using type = X;
};

template<class X, class Y>
struct tuple_element<1, pear<X, Y>> {
    using type = Y;
};

template<int N, class X, class Y>
inline typename tuple_element<N, pear<X, Y>>::type get(const pear<X, Y> & value) {
    if constexpr (N == 0) {
        return value.getX();
    } else {
        return value.getY();
    }
}

}

inline int testDestructure(int x) {
    auto val = std::pear<int, int>( x, x + 2 );
    auto [y,z] = val;
    return z;
}
```
test.swift
```
import Testi

func test() {
    testDestructure(20)
}

test()
```

**Steps to reproduce**
Build:
```
swift-frontend -c -enable-experimental-cxx-interop -I . -Onone test.swift -sdk $(xcrun --show-sdk-path) -emit-ir -o ir.ir -Xcc -std=c++17
```

You'll see a declaration but not definition for:

```
_ZSt3getILi0EiiENSt13tuple_elementIXT_ESt4pearIT0_T1_EE4typeERKS4_
```

### PR DESCRIPTION
**Pull request by hyp**
Fixes #62448

### CODE REVIEW

**Comment by hyp** [comment]
@swift-ci please test

**Review by ktoso — APPROVED** [review]
Nice, thank you!

**Review by egorzhdan — APPROVED** [review]

**Comment by hyp** [comment]
@swift-ci please test windows platform

**Comment by hyp** [comment]
Landing, the windows failure is unrelated.

**Pull request merged**
