### PR TITLE
[stdlib] Remove redundant >, <=, >= on Comparable types

### PR DESCRIPTION
**Pull request by airspeedswift**
Very similar to #19535 but for `Comparable`

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please smoke benchmark

**Comment by airspeedswift** [comment]
@swift-ci please smoke test compiler performance

**Comment by airspeedswift** [comment]
Grr. Floating point's Comparable implementation ruins everything. Again.

**Comment by jckarter** [comment]
You should be able to remove the operations on integers, at least.

**Comment by CodaFi** [comment]
@airspeedswift Do you want to revisit this or should we close it?

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
