### PR TITLE
[Reflection] Try to read only the reflection sections.

### PR DESCRIPTION
**Pull request by dcci**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by dcci** [comment]
@apple/swift5-branch-managers no ABI impact, fixes a substantial performance regression in `swift-lldb`.

**Comment by dcci** [comment]
@swift-ci please test

**Comment by bob-wilson** [comment]
Is this already on master? Is it associated with a radar number?

**Comment by dcci** [comment]
@swift-ci test linux

**Review by bob-wilson — APPROVED** [review]

**Comment by dcci** [comment]
I'm not really authorized to merge this, but I would appreciate if somebody can do it on my behalf.

**Pull request merged**
