### PR TITLE
[Build System: build-script] Remove the diagnostics module from swift_build_support.

### PR DESCRIPTION
**Pull request by Rostepher**
The `diagnostics` module is a rather poor replacement for actual logging. Since it's only used in a few places I've either inlined the calls or added equivalent helper functions for printing notes and exiting with a fatal error.

In the future we should adopt the standard Python `logging` module which is thread safe.

### CODE REVIEW

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
A strong +1 on the use of `logging` instead of this.

**Review by compnerd — APPROVED** [review]
Id prefer using `logging`, but I suppose doing that in a separate change isnt too terrible

**Comment by Rostepher** [comment]
> Id prefer using `logging`, but I suppose doing that in a separate change isnt too terrible

We can transition to `logging` in a separate PR, but that's definitely where we _should_ be going.

**Pull request merged**
