### PR TITLE
Try to derive a type witness in a known conformance before attempting associated type inference

### PR DESCRIPTION
**Pull request by slavapestov**
Sema can infer type witnesses for a small set of known conformances, to RawRepresentable, CaseIterable, and Differentiable.
    
Previously, we would try to compute the type witness in this order:
    
1) First, via name lookup, to find an explicit nested type with the same name as an associated type.
    
2) Second, we would attempt inference.
    
3) Third, we would attempt derivation.
    
Instead, let's do 3) before 2). This avoids circularity errors in situations where the witness can be derived, but inference fails.
    
This breaks source compatibility with enum declarations where the raw type in the inheritance clause is a lie, and the user defines their own witnesses with mismatched types. However, I suspect this does not come up in practice, because if you don't synthesize witnesses, there is no way to access the actual raw literal values of the enum cases.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@dan-zheng @rxwei Please take a look at the AutoDiff change I had to make here to get the test suite to pass.

**Review by dan-zheng — APPROVED** [review]
Thanks!

**Review by rxwei — APPROVED** [review]

**Comment by slavapestov** [comment]
The source compat failures are caused by a swiftpm issue and they're failing on the main branch as well.

**Pull request merged**
