### PR TITLE
Remove trailing whitespace

### PR DESCRIPTION
**Pull request by JaSpa**
This pull request removes all trailing whitespace throughout the repository except for the `docs/` directory where I'll take a separate look.

I ran the full `build-script -T` test suite and encountered 10 test cases relying on trailing whitespace, this is fixed (simply by re-adding the whitespace) in d6029b6. I hope there are no other issues falling into the 115 unsupported tests.

### CODE REVIEW

**Comment by JaSpa** [comment]
Ok, I have added whitespace removal for the `docs/` directory

**Comment by gribozavr** [comment]
Thank you, but we prefer not creating extra code churn by removing whitespace.

**Comment by JaSpa** [comment]
@gribozavr @DougGregor said in #781 that “we should clean those up anyway”

**Comment by DougGregor** [comment]
I'm sorry, my flippant remark in #781 caused confusion. Whitespace-only changes tend to screw up history for no real benefit, so we try to avoid them. Sometimes we end up cleaning up a little bit of whitespace within the code we're already changing, and that's okay.

**Comment by JaSpa** [comment]
Ok, thanks for the clarification.

**Pull request closed without merging**
