### PR TITLE
runtime: remove `llvm/DataTypes.h`, `llvm-c/DataTypes.h`

### PR DESCRIPTION
**Pull request by compnerd**
Inline the standard headers that they included and remove the extra
include path.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @mikeash @jckarter

**Comment by compnerd** [comment]
@swift-ci please test

**Review by mikeash — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Pull request merged**
