### PR TITLE
AST: Replace recently-added IsInOut bit with simpler check, NFC

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test and merge

**Comment by slavapestov** [comment]
@swift-ci Please smoke test and merge

**Comment by lattner** [comment]
+1 for this patch, thank you @slavapestov !

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by slavapestov** [comment]
@tkremenek The failure is due to an IDE crasher that now passes. I'll push a new version shortly.

**Pull request closed without merging**
