### PR TITLE
If local LLVM folder has a copy of libcxx, don't create symlink

### PR DESCRIPTION
**Pull request by patcheng**
When libcxx is cloned to swift-source/libcxx, building LLVM would copy the libcxx headers to `$llvm_build_dir/include/c++` automatically, don't have to create symlink.

### CODE REVIEW

**Comment by patcheng** [comment]
@swift-ci Please clean test

**Comment by patcheng** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
It's been a while, but @gottesmm could you take a look at this and see if it still makes sense?

**Comment by CodaFi** [comment]
Well, let's at least see if this works.

@swift-ci please clean test

**Comment by CodaFi** [comment]
Turns out this is still not safe to do.  See the compiler-rt comment above for a rationale.

Gonna close this out then.

**Pull request closed without merging**
