### PR TITLE
tests: cleanup for two ownership verifier tests.

### PR DESCRIPTION
**Pull request by eeckstein**
This is a follow-up of https://github.com/apple/swift/pull/36211

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci smoke test and merge

**Comment by eeckstein** [comment]
@swift-ci smoke test macos

**Comment by CodaFi** [comment]
@swift-ci smoke test macOS

**Comment by eeckstein** [comment]
@swift-ci smoke test macOS

**Pull request merged**
