### PR TITLE
[IRGen] Restored single refcounted object opt for async partial applies.

### PR DESCRIPTION
**Pull request by nate-chandler**
As part of bringup, specifically in order to support storing the size of the async context as the first entry in the thick context, the optimization that allows the partial application of a single refcounted object to avoid the allocation of a thick context was disabled.

Now that we have async function pointers for partial application forwarders, that rationale is moot, so, here, the optimization is restored.

rdar://76372871

### CODE REVIEW

**Comment by nate-chandler** [comment]
@swift-ci please test

**Review by aschwaighofer — APPROVED** [review]
lgtm

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test linux platform

**Comment by nate-chandler** [comment]
@swift-ci please clean test linux platform

**Comment by nate-chandler** [comment]
@swift-ci please test linux platform

**Pull request merged**
