### PR TITLE
[Sema] Refactor enum Codable synthesis

### PR DESCRIPTION
**Pull request by drexin**

### CODE REVIEW

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@beccadax Sorry it took so long, but here are the changes 🙂

**Comment by drexin** [comment]
@swift-ci smoke windows

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@swift-ci smoke test linux

**Comment by drexin** [comment]
@swift-ci smoke test windows

**Comment by ktoso** [comment]
@swift-ci smoke test linux

**Comment by drexin** [comment]
@swift-ci smoke test linux

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@beccadax ping

**Pull request merged**
