### PR TITLE
Clean up handling of CMark library dependency.

### PR DESCRIPTION
**Pull request by llvm-beanz**
This change depends on:

https://github.com/apple/swift-cmark/pull/4

This PR modifies Swift's handling of CMark to import the CMark exported targets. This allows the Swift project to directly depend on CMark's targets instead of hand-constructing the library path. This eliminates the need to have platform-handling in constructing the CMark library path.

### CODE REVIEW

**Comment by llvm-beanz** [comment]
@swift-ci Please Test

**Comment by gottesmm** [comment]
@llvm-beanz This looks ok to me overall. A few questions:

1. Isn't the canonical name CMarkTargets.cmake?
2. Can we provide a CmarkConfig.cmake so that we can import this using find_package like we do LLVM,Clang. See SwiftSharedCMakeConfig.cmake. This line specifically:

  # Then we import LLVMConfig. This is going to override whatever cached value                                                  
  # we have for LLVM_ENABLE_ASSERTIONS.                                                                                         
  find_package(LLVM REQUIRED CONFIG                                                                                             
    HINTS "${PATH_TO_LLVM_BUILD}" NO_DEFAULT_PATH)

**Comment by gottesmm** [comment]
(sorry for the formatting problem, I edited the post on github to use the proper comment quotes).

Michael

**Comment by llvm-beanz** [comment]
@gottesmm The reason I did the change this way was to minimize the scope of the change required to CMark. Producing a fully "package" that is compatible with find_package, and does all the right things there is larger than the one line patch I applied to CMark.

If we want to have a fully featured package, I think the right approach would be to get the CMark upstream developers to implement it, and we can pull it down.

**Comment by gottesmm** [comment]
@llvm-beanz. Ok SGTM to me!

**Review by gottesmm — APPROVED** [review]

**Comment by llvm-beanz** [comment]
@swift-ci Please test Linux Platform

**Pull request merged**
