### PR TITLE
Revert "Revert "Playground Transform: Fix assertion failure in generic code [3.1]""

### PR DESCRIPTION
**Pull request by shahmishal**
Reverts apple/swift#6737

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
Looks like the failure really is caused by my patch?

**Comment by shahmishal** [comment]
@slavapestov Does not look like it, however this was the only commit between successful and failure build.

**Comment by shahmishal** [comment]
@swift-ci Please test macOS

**Comment by slavapestov** [comment]
I think this can be merged now.

**Pull request merged**
