### PR TITLE
Support unavailable and obsoleted attributes on extensions

### PR DESCRIPTION
**Pull request by xymus**
Members of an extension should inherit the availability of the extension. This was previously supported for `introduced` and `deprecated`, but not `unavailable` and `obsoleted`.

### CODE REVIEW

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by xymus** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
This is worth a CHANGELOG entry.

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by xymus** [comment]
@swift-ci Please test source compatibility

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by xymus** [comment]
@swift-ci Please test source compatibility

**Review by slavapestov — APPROVED** [review]

**Pull request merged**
