### PR TITLE
[Driver] <rdar://43955209> Remove obsolete/fragile batch mode 'repartitioning' code.

### PR DESCRIPTION
**Pull request by graydon**
Remove the batch-mode support for repartitioning the input batches to try to fit inside argv limits.

This code is obsolete / dead because:

  - Repartitioning was only subdividing down the batch partition which isn't able to minimize overlong argv that could happen in (say) the list of all inputs. So the "remedy" it was applying wouldn't always work.
  - With support for supplementary output file maps, any invocation with more than 8 primaries was going to trigger the use of a supplementary output file map anyways (limit of 128 divided by 16 filetypes), leaving only the rare chance of executing on a platform with extremely small argv (POSIX sets minimum at 4096 bytes, but it's 32kb on win32 and over 200kb on macosx) exceeded by fewer-than-8 filenames.
  - Subsequent support for response files uses the same sysconf-based measurement to make even this case not possible anyways: it's caught and remedied correctly right at the end of command-line construction.

Given the dead-code-ness and the fact that the test for it "working" fails sporadically causing endless annoyance to czars, I propose dropping it.

rdar://43955209

### CODE REVIEW

**Comment by graydon** [comment]
@swift-ci please test

**Review by davidungar — APPROVED** [review]
Looks good to me! Thanks in advance for adding the assertion to ensure that response files are always allowed between driver and frontend.

**Comment by graydon** [comment]
@swift-ci please test and merge

**Comment by davidungar** [comment]
Nice comment on the assertion!

**Comment by graydon** [comment]
@swift-ci please test linux platform

**Comment by graydon** [comment]
@swift-ci please test macos platform

**Pull request merged**
