### PR TITLE
[Benchmark] Speed up compilation time; add String benchmarks

### PR DESCRIPTION
**Pull request by milseman**
This speeds up the compilation time of main.swift in the benchmark suite from taking a minute or two to about a second. NFC.

Starts a String perf test suite called stringTests which is
off-by-default, but allows us to place some lower-level targeted
benchmarking.

### CODE REVIEW

**Comment by milseman** [comment]
@aschwaighofer @eeckstein does this look reasonable to you as a start? I've not touched the benchmark suite before.

**Comment by milseman** [comment]
Also, I hope to expand this to have more of a notion of sub-suites. Perhaps some of the recent existentials can go in its own sub-suite, etc.

**Comment by milseman** [comment]
@swift-ci please smoke test

**Comment by aschwaighofer** [comment]
@milseman Is the compile time improvement because type checking for the array is horrible?

Does benchmark/scripts/generate_harness/generate_harness.py still work?

**Comment by milseman** [comment]
Yes, and this is a dictionary not an array (appending multiple literals is not as ergonomic).

I was not aware of generate_harness.py. I was assuming that main was hand-coded

**Comment by aschwaighofer** [comment]
right this is a dictionary :).

I did not know about it either until I recently broke it with the existential commit. I think most of us hand code main and it just happens to work if you follow the naming scheme.

**Comment by aschwaighofer** [comment]
Subtests sound good to me.

**Comment by milseman** [comment]
Given that you already have to add new files by hand to the CMakeLists.txt, why not have it be a CMake template instead? I really don't understand the organization of this suite.

**Comment by aschwaighofer** [comment]
I am not the author. Doesn't generate harness also populate the CMakeLists file.

**Comment by milseman** [comment]
Ah, so the build system doesn't generate the suite? Is this just something we periodically run?

**Comment by aschwaighofer** [comment]
Some people seem to run it. I have never run it myself (though I added plenty of tests).

The build system does not run it. You will only know if you broke it because people scream at you (or me) for breaking it ;) .. or you happen to really read the readme ...

**Comment by milseman** [comment]
@aschwaighofer what do you think of this? Everything should be moved into the generator now

**Comment by milseman** [comment]
@swift-ci please smoke test

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke benchmark

**Comment by aschwaighofer** [comment]
LGTM.

**Comment by milseman** [comment]
Failure was from python linting. I'm getting set up to address that now.

**Comment by milseman** [comment]
@swift-ci please smoke test

**Comment by milseman** [comment]
@shahmishal this looks unrelated. I have a follow up PR that I'd like to test separately. Do you know if this is a current issue? Can you merge if so?

**Comment by milseman** [comment]
@swift-ci Please clean smoke test Linux platform

**Comment by milseman** [comment]
While I'm happy to take credit for any speedups, they are unlikely the result of these changes. Linux failure is still a mystery.

**Comment by milseman** [comment]
@swift-ci Please clean smoke test Linux platform

**Review by aschwaighofer — APPROVED** [review]

**Comment by milseman** [comment]
@swift-ci Please smoke test Linux platform

**Comment by palimondo** [comment]
@aschwaighofer , @milseman Re: "You will only know if you broke it because people scream at you (or me) for breaking it”

There is now [validation test](https://github.com/apple/swift/blob/master/benchmark/scripts/generate_harness/test_generate_harness.sh) that catches manual edits of main.swift and CMakeList.txt. (Added 16 days ago)

**Comment by palimondo** [comment]
@milseman Looking at your benchmark branch, it looks inactive since this merged, are you done here? I’m about to muck around there and want to prevent conflicts.

**Comment by milseman** [comment]
@palimondo Sure, I'll revisit this again sometime in the future, but no immediate plans.

**Pull request merged**
