### PR TITLE
runtime: add undecoration support for Windows

### PR DESCRIPTION
**Pull request by compnerd**
Use the Windows API `UnDecorateSymbolName` rather than `__cxa_demangle`
to undecorate the C++ symbols.  `__cxa_demangle` is only available in
the itanium ABI, not under MS ABI.  This allows us to properly
undecorate symbols on Windows.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @gottesmm

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by gottesmm** [comment]
This LGTM. But question is UnDecorating what demangling is called on Windows?

**Comment by gparker42** [comment]
UnDecorateSymbolName is fine. But it is documented as thread-unsafe. What locking do we need around it?

**Comment by compnerd** [comment]
@gottesmm, yeah, "mangling" -> "decoration", "demangling" -> "undecoration"

@gparker42 yeah, we could just do a `std::unique_lock<std::mutex>` around the call.  Concurrent calls can result in the undeocrated name being corrupt is my reading of the docs.

**Comment by compnerd** [comment]
Doesn't make sense to not just do the locking.  Thanks for the reminder on that @gparker42!

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by gparker42** [comment]
Adding a lock here isn't sufficient to protect against other callsites potentially in other libraries. I don't know what the usual Windows practice is here.

Having said that, is this code only called when we're already going to halt the process? I suppose the risk of thread-unsafety versus some other library is acceptable in that situation.

**Comment by compnerd** [comment]
@gparker42 yeah that's a good point.  I don't think that there is some general pattern.  I believe that this would be on the termination code path, so the risk of the thread-unsafety is generally outweighed by the benefits.  This would help identify the issue and provide a symbolicated stack trace.

**Comment by compnerd** [comment]
I believe that @gparker42's concerns have been addressed.  This is improving the state of things.  The best that we can do is add a comment.  I don't see a good way to ensure that the lookup is not used elsewhere.  Since this is the termination path, this is still valuable.

**Pull request merged**
