### PR TITLE
[Docs] Add missing `else` to guard statements in code listing

### PR DESCRIPTION
**Pull request by amartini51**
Fixes <rdar://84895831>

### CODE REVIEW

**Comment by amartini51** [comment]
@swift-ci Please test.

**Comment by amartini51** [comment]
Re-targeted this from the Swift 5.5 release branch to 'main'.

**Review by ktoso — APPROVED** [review]
Nice catch, thank you!

**Comment by ktoso** [comment]
@swift-ci please smoke test and merge

**Pull request merged**
