### PR TITLE
Delete unused include/swift/Syntax/Format.h

### PR DESCRIPTION
**Pull request by Teemperor**
This file includes the non-existent Rewriter.h which was deleted in commit
a5098e6b69b2e7f69a1075b2668e1ae56ab462c6 . From what I can see this file
can also be deleted as it anyway doesn't compile anymore.

### CODE REVIEW

**Comment by Teemperor** [comment]
@swift-ci test

**Comment by Teemperor** [comment]
@swift-ci test

**Comment by Teemperor** [comment]
@swift-ci smoke test

**Review by mikeash — APPROVED** [review]
C's preprocessor/include system is just the best.

**Review by akyrtzi — APPROVED** [review]

**Comment by Teemperor** [comment]
@swift-ci test

**Comment by Teemperor** [comment]
@swift-ci test

**Comment by Teemperor** [comment]
Also giving up on this one, there is just so many times I want to ask swift-ci to test.

**Pull request closed without merging**
