### PR TITLE
[ConstraintSystem] Generalize uninitialized wrapped variable targets

### PR DESCRIPTION
**Pull request by xedin**
- Allow solution application targets to support both wrapped variables and patterns.
- Implement support for uninitialized pattern bindings.

### CODE REVIEW

**Review by hborla — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@swift-ci please smoke test

**Pull request merged**
