### PR TITLE
[stdlib] Implement the Indic grapheme breaking rules

### PR DESCRIPTION
**Pull request by Azoy**
This implements the CLDR Indic grapheme sequences rule in the stdlib that was also handled by ICU. The rule can be found here: https://github.com/unicode-org/cldr/tree/main/common/properties/segments

### CODE REVIEW

**Comment by Azoy** [comment]
@swift-ci please smoke test

**Comment by Azoy** [comment]
@swift-ci please benchmark

**Review by milseman — COMMENTED** [review]
Quick pass over LGTM, but I haven't looked too deeply at `checkIfInIndicSequence`. IIRC, that's similar to other kinds of scan-backwards checks we have for regional indicators. Is the logic sufficiently similar that we could share the algorithm, or is it fairly distinct?

**Comment by Azoy** [comment]
They're both similar in that they need to walk backwards, but the logic afterwards is fairly distinct. We could parameterize the logic and share a backwards walker if we wanted.

**Pull request merged**
