### PR TITLE
Re-add dependency on libatomic for 32-bit Linux platforms

### PR DESCRIPTION
**Pull request by drexin**

### CODE REVIEW

**Comment by drexin** [comment]
cc: @buttaface

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@swift-ci smoke test macos

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by buttaface** [comment]
I think you will have to add it back for the stdlib too, which has its own CMake config now in `stdlib/cmake`.

Could you add it back for the Android armv7 stdlib too, [as I do here](https://github.com/buttaface/termux-packages/commit/caa22e24be7bbb279c210cefe6b42818480c9e28#diff-2587a829c1dff85339003c6946945249960d25ec122ae053969ed30b36bdded8R73)? Do you think those atomic loads can be avoided altogether if some modifications are made to those stdlib source files, as you previously did for linux x86_64?

**Comment by drexin** [comment]
@swift-ci smoke test

**Comment by drexin** [comment]
@swift-ci smoke test windows

**Comment by drexin** [comment]
@swift-ci smoke test windows

**Review by compnerd — APPROVED** [review]
I wonder if there are any flags which will give us 64-bit atomic operations on 32-bit but this seems reasonable for now.

**Pull request merged**
