### PR TITLE
[TypeChecker] Respect access control flag while validating superclass…

### PR DESCRIPTION
**Pull request by xedin**
… relation

Otherwise it's impossible to declare a subclass in integrated REPL

### CODE REVIEW

**Review by slavapestov — APPROVED** [review]
Thanks! Can you also add a test that overriding user-defined methods works? Your existing test only overrides a synthesized init.

**Comment by xedin** [comment]
@slavapestov Turns out that actually doesn't work :) I'm going to open a separate PR for that.

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by jrose-apple** [comment]
Can you also add a test that doesn't involve the REPL? There's a `-disable-access-control` frontend flag for this purpose.

**Comment by xedin** [comment]
Sure, I'll add that in the upcoming PR.

**Pull request merged**
