### PR TITLE
[PrintAsObjC] Revert emission of header #imports

### PR DESCRIPTION
**Pull request by DougGregor**
Revert the various commits implementing the emission of #imports in the generated header. We want this functionality, but getting it *exactly* right has proven quite challenging. Get back to a known "working" state while we figure out the details.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Review by nkcsgexi — APPROVED** [review]
Reverting these seems reasonable to me. The framework case should be straightforward, we simply always print `<Framework/Framework.h>`. The tricky case is the non-framework case, where I'm not sure there's an elegant and generic solution other than piling up known heuristics.

**Comment by DougGregor** [comment]
> Reverting these seems reasonable to me. The framework case should be straightforward, we simply always print `<Framework/Framework.h>`. The tricky case is the non-framework case, where I'm not sure there's an elegant and generic solution other than piling up known heuristics.

Yeah, I'm thinking that for the non-framework case, we basically need to take a "diff" between the path to the header file and the Clang include path through which the module map was found.

**Comment by nkcsgexi** [comment]
oh, interesting. We could assume the directory of the modulemap is among the header search paths so the include of the header file could anchor from there?

**Comment by DougGregor** [comment]
@swift-ci please smoke test Linux

**Comment by DougGregor** [comment]
@swift-ci please smoke test Linux

**Comment by DougGregor** [comment]
@swift-ci please test Linux

**Pull request merged**
