### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by weitieda**
`count down` -> `countdown`

### CODE REVIEW

**Comment by weitieda** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
Hm, both this patch and the existing docs read correctly. @natecook1000 What do you think?

**Comment by xwu** [comment]
Reads correctly to me; the sense being conveyed is that “down” is the direction of iteration. To put it more explicitly, one might say “iterate over the countdown down to zero,” but that does not read well.

**Comment by weitieda** [comment]
> Reads correctly to me; the sense being conveyed is that “down” is the direction of iteration. To put it more explicitly, one might say “iterate over the countdown down to zero,” but that does not read well.

I understand your point, I think it makes sense too. The way I see it is that "iterate over the countdown to zero", `countdown` here should be a noun. And if we google "count down" as a noun, it's "countdown" instead of "count down". That's why I created this PR.

**Comment by natecook1000** [comment]
The current wording could surely be improved, but right now the sentence means "iterate downward over the count". I don't think the new version perserves that meaning.

**Comment by natecook1000** [comment]
Closing this for now — @weitieda feel free to re-open if you'd like to revisit!

**Pull request closed without merging**
