### PR TITLE
SIL : Use the enum 's generic signature and the payloads type for an …

### PR DESCRIPTION
**Pull request by aschwaighofer**
…indirect enum payload's box type.

i.e for:

```
enum Indirect<T> {
  indirect cast payload(first: T, second :T)
}

let _ = Indirect<X>
```

The payload's SIL box type will be:

```
$<t_0_0> { var (first: t_0_0, second: t_0_0) } <X>
```
rdar: //36799330

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test source compatibility

**Comment by aschwaighofer** [comment]
@rjmccall John is that what you had in mind?

**Comment by aschwaighofer** [comment]
@swift-ci Please smoke test linux

**Comment by aschwaighofer** [comment]
@swift-ci Please test linux

**Comment by aschwaighofer** [comment]
The source compat tests also currently fail on master e.g.:

```
fatal: unable to access 'https://github.com/vapor/crypto.git/': error setting certificate verify locations:
  CAfile: /etc/ssl/cert.pem
  CApath: none
```

**Comment by rjmccall** [comment]
Yes, that looks exactly right, thanks!  I'm glad it worked out so easily.

**Pull request merged**
