### PR TITLE
[CSGen] Don't increase optionality of `weak var` patterns

### PR DESCRIPTION
**Pull request by xedin**
If the externally-imposed type is already optional,
let's not add optionality to the pattern.

### CODE REVIEW

**Review by hborla — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
Source compatibility is UPASS.

**Comment by davezarzycki** [comment]
Whoa. Interesting. How did this not get caught until now?

**Pull request merged**
