### PR TITLE
[NFC] Use the presence of an argument type to check for associated values

### PR DESCRIPTION
**Pull request by CodaFi**
Noticed by inspection while working on some exhaustiveness checker stuff.

`hasOnlyCasesWithoutAssociatedValues` returns true for any serialized
enum declaration whether or not it has cases.  This never really came
up because it's mostly relevant to Sema's proto-deriving mechanism.  Fix
this by using the presence of the case's argument type instead.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by slavapestov** [comment]
You can also make the cache bit mutable, or use const_cast to cast off the const.

**Comment by CodaFi** [comment]
I was hoping it wouldn't come to that, but it would be nice to avoid some linear work in a question that gets asked a bit more than when this code was first written.

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
Alright, so this *was* relying on that tricky little invariant about also being a check for cases.  I'm going to separate those two conditions.

**Comment by slavapestov** [comment]
This looks good but is there any real reason to not derive those conformances for empty enums, ie `Never`?

**Comment by CodaFi** [comment]
It causes some fun errors when trying to build stdlib if that check isn't there.

**Comment by CodaFi** [comment]
@swift-ci please smoke test.

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
@swift-ci please smoke test

**Comment by CodaFi** [comment]
I'll try to modify the derived conformances stuff to enable this and see what happens.  It will *technically* be a stdlib API change and may need to go through evolution // @airspeedswift @dabrahams

**Comment by CodaFi** [comment]
⛵️

**Pull request merged**
