### PR TITLE
[Runtime] Diagnose conflicting retroactive conformances

### PR DESCRIPTION
**Pull request by DougGregor**
When the environment variable `SWIFT_ENABLE_CONFLICTING_CONFORMANCES_CHECK` is set, and runtime conformance lookup finds more than one retroactive conformance, produce a warning like this:

```
***Swift runtime warning: multiple conformances for
'RetroactiveCommon.CommonStruct: CommonP1' found in modules
'RetroactiveA' and 'RetroactiveB'. Arbitrarily selecting conformance
from module 'RetroactiveA'
```

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by natecook1000** [comment]
@DougGregor Looks like this may have been picked up through other commits? Okay to close?

**Comment by DougGregor** [comment]
I think some of the early commits got pulled in, but I don’t think we’re actually diagnosing multiple retroactive conformances yet

**Comment by futurejones** [comment]
Can one of the admins verify this patch?

**Comment by shahmishal** [comment]
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

**Pull request closed without merging**
